### ISSUE TITLE
Proxy via Kubernetes API is not supported, breaking preferred access to Kubernetes Dashboard  

### ISSUE THREAD

**Issue by seanknox** [Azure/AKS#1]
Proxy via the Kubernetes API is not currently supported. This breaks access to kubernetes-dashboard as the preferred method of access is via kubectl proxy then localhost:8001/ui. 

As a workaround, users can run `az aks browse` to access the Dashboard pod via `kubectl port-forward`.

**Comment by squillace** [comment]
Still having issues with ukwest: 
![image](https://user-images.githubusercontent.com/1422718/32032334-6be95060-b9bb-11e7-8c99-0f9065624da4.png)

but the connection seems to be there:
![image](https://user-images.githubusercontent.com/1422718/32032345-7cc8c21c-b9bb-11e7-951d-b80438ec3390.png)

**Comment by seanknox** [comment]
Try removing the "/ui" at the end of the URL.

**Comment by squillace** [comment]
AH! Sorry; it took about 30 seconds to appear, and I didn't realize I had to wait that long. it's there now. Apologies; I'll note that you have to be a bit patient there.

**Comment by dtzar** [comment]
Just verified - this works too at the moment without having to use `az aks` 
https://github.com/Azure/AKS/issues/8#issuecomment-342084751

**Comment by jespernohr** [comment]
@dtzar  -  did you manage to access the dashboard/web UI with the following workaround ?

_In order to open the dashboard you need to run the following command:
kubectl port-forward kubernetes-dashboard-1672970692-375tg 9090 --namespace kube-system
you need to replace "kubernetes-dashboard-1672970692-375tg" with your pod name which run the dashboard. you can get it by running the following command:
kubectl get pods --all-namespaces_

**Comment by slack** [comment]
New tunnel infrastructure landed in East US and will be available in all new regions.
