### ISSUE TITLE
ApiServer options

### ISSUE THREAD

**Issue by mwieczorek** [Azure/AKS#10]
I have some questions about apiserver configuration:
1. --feature-gates - are they set by default values? Is it possible to turn on/off any of them (f.e. initializers)? Or will it be possible in the near future?
2. OIDC - is it possible to provide auth configuration (oidc-issuer-url etc)? Will it be possible in the near future?

**Comment by khenidak** [comment]
@seanknox FYI

currently not supported. Can you share with us the scenarios you are looking to support?

**Comment by mwieczorek** [comment]
The main use cases:
1. Using istio with automatic sidecar injection - so there's need for initializers
2. Using somewhere auth providers, f.e. with DEX.

**Comment by pfongkye** [comment]
hi,
I would like to add my use case also. It's also related to api server configuration:
Using Azure Active Directory  to authenticate API requests with OpenID Connect as communication protocol.

**Comment by khenidak** [comment]
@pfongkye AAD is coming on its own as Aks feature, the api-server option/args will probably stand as its own feature.

CC: @slack

**Comment by sylus** [comment]
Glad this issue was already created as am looking to get AKS working with initializers for istio.

Right now resorting to:

```sh
   helm get app | sed -e '1,/MANIFEST:/d' | istioctl kube-inject -f - | kubectl apply -f -
```

**Comment by jasonkenneth** [comment]
We're looking at enabling chron jobs on a 1.7 cluster per [ACS issue #178](https://github.com/Azure/acs-engine/issues/178).

**Comment by levidehaan** [comment]
our use case is using preemption: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#how-to-use-priority-and-preemption
which requires a --feature-gates flag set on the api server.
is this an option you're considering?

**Comment by pabSec** [comment]
Using keycloak as an identity and access manager would be nice, so it's need OIDC kube-apiserver configuration.

Any news on this?

**Comment by gurvindersingh** [comment]
I have a similar use case where we have our own OIDC provider and would like to use it with AKS cluster and have same RBAC policy rules as our on prem cluster with user and groups having the same identity across clusters. So any ETA on this would be great.

**Comment by seanknox** [comment]
AAD/OIDC is supported in AKS now. No current plans to enable feature gates for the API server, but will take it under consideration.

**Comment by gurvindersingh** [comment]
@seanknox can you point me to the docs which can help to setup my OIDC provider with AKS, as that can solve my current use case without needing API sever options. As from docs, I could see only Azure AD support.

**Comment by seanknox** [comment]
Sorry I misspoke, OIDC is not yet supported I believe. For feature requests, please go here: https://aka.ms/aks/feedback

**Comment by bergerx** [comment]
Created https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/35100826-support-oidc-parameters

**Comment by nazarikus** [comment]
Can somebody reply regarding ETA for getting Priority Admission Controller/FeatureGate in AKS?

**Comment by IbraheemAlSaady** [comment]
Are there any updates regarding this?
