### ISSUE TITLE
Please add support for addon Registry

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#100]
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry

**Comment by slack** [comment]
We likely won't support a deep integration with the docker registry addon. If you do need private registry support, I'd recommend:
* Using Azure Container Registry: https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-prepare-acr
* Install a registry using Helm: https://github.com/kubernetes/charts/tree/master/stable/docker-registry
