### ISSUE TITLE
Region: Support Norway East/West

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#1002]
Tracking issue for Norway East/West region AKS support.

**Comment by evenh** [comment]
This region is GA tomorrow ;-)

**Comment by asbjorne** [comment]
Norway East is available as a region when creating cluster now, but all node-sizes are unavailable. 
Any idea when they will be available?

**Comment by aklepaker** [comment]
What we did was open a quota request and we got access to the requested node types within a few hours.
