### ISSUE TITLE
[Feature][Passive] Node automatic repair

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#1003]
Tracking issue for AKS support for node auto repair.

Supports service remediation when detecting an unhealthy node. AKS automatically initiates a set of repair processes if a node health check fails.

**Comment by jluk** [comment]
This capability is a passive feature in AKS today, AKS will take remediation action when detecting a node not ready. The public documentation on this will be available in the coming weeks.

**Comment by jluk** [comment]
Document is published at aka.ms/aks/autorepair
