### ISSUE TITLE
Support for large scale clusters (via multiple node pools)

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#1004]
Tracking issue for support (via multiple node pools) increased worker node counts within AKS. Each scale chunk (eg 500, 1000 nodes) will be released separately for preview and testing.

**Comment by kim0** [comment]
@jnoller .. Would you please help me understand the maximum number of nodes that can be attached to AKS (VMSS mode) .. Thanks

**Comment by jluk** [comment]
Closing as AKS now supports 1000 nodes in a single cluster, with 10 pools at 100 each.
