### ISSUE TITLE
Cannot add new Windows pool - error: Windows profile definition is missing for the cluster

### ISSUE THREAD

**Issue by jjindrich** [Azure/AKS#1005]
Hi,

I have existing AKS cluster and trying to add new nodepool on windows with command:
az aks nodepool add --resource-group rg --cluster-name myaks --os-type Windows --name npwin --node-count 1 
--kubernetes-version 1.14.0
I'm getting this error: Operation failed with status: 'Bad Request'. Details: Windows profile definition is missing for the cluster

My existing AKS cluster - linux pool with version 1.12.7

**Comment by stephenpope** [comment]
This means its looking for a windows username / password to use for the node for example ..
```
az aks create \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --node-count 1 \
    --enable-addons monitoring \
    --kubernetes-version 1.14.0 \
    --generate-ssh-keys \
    --windows-admin-password $PASSWORD_WIN \
    --windows-admin-username azureuser \
    --enable-vmss \
    --network-plugin azure
```

.. the only way I know of is to add this when then cluster is created .. im sure that someone will know how to add this post-cluster creation but I couldnt find anything about this in the docs. The add nodepool add command doesn't have these options so I had to re-create my cluster (which I understand may not be an option).
 Also you will need to be running the `azure` network plugin or else it will also fail.

**Comment by jjindrich** [comment]
Wow, good finding. But I need to find way how to add this profile to existing cluster....

**Comment by jnoller** [comment]
Adding windows node pools to existing clusters is unsupported  currently as it requires Other preview only features, is in preview only, etc. we will examine the possibility of adding windows pools to existing cluster when we graduate the features required to GA

**Comment by jnoller** [comment]
Also I believe you found another bug; you have an older 1.12 cluster and you’re attempting to add a 1.14 pool of windows nodes, which should be explicitly blocked

**Comment by jjindrich** [comment]
What is the minimal version of linux primary node ?

**Comment by jnoller** [comment]
I'm discussing with the team, but it should be at a minimum of 1.13, also, as I said, you *can not add it to an existing cluster*, we will look at it when we look at GA criteria, but for now, you need a new cluster at, with multiple agent pools (preview only), on a non production system, with Kubernetes 1.13 / 1.14 minimally

**Comment by jjindrich** [comment]
I understand I have to use multiple agent pools, but I expected that I can add now. Ok, understand, closing ticket

**Comment by NithinPrasad-GEP** [comment]
MS Team,

Is this feature now GA? If so can you please provide the documentation.

**Comment by AAATechGuy** [comment]
Why is this closed, shouldn't MS team provide an answer?

**Comment by cpunella** [comment]
Now that the service is in GA, would be possible (now or soon) to update an existing cluster to enable the windows profile section?

**Comment by islamtg** [comment]
I have the same issue there should be a way to add a windows based pod in a pre-existing cluster. whats the point of creating a new cluster when I have a pre-existing one? there should be a way with in the add pod, to give the user parameter and the password and create that new pod. 

is this something expected in the future. I am running the cluster at 1.16.9. I get similar results as the above, which was done on 1.12.x
