### ISSUE TITLE
When adding Windows node pool, need to specify version

### ISSUE THREAD

**Issue by dalehhirt** [Azure/AKS#1006]
**What happened**:
I created an AKS instance with a Windows Node Pool.  The version of the OS is Windows 10 1809 - 10.0.17763.379.  

**What you expected to happen**:
I need to be able to specify the version of the Windows OS, specifically 1803.  I will eventually be able to get the developers to upgrade the OS they build on, but it won't be for months.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (how many worker nodes are in the cluster?)
3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by MikkelHegn** [comment]
We only support Windows Server 2019 (1809): https://docs.microsoft.com/en-us//azure/aks/windows-node-limitations#limitations-for-windows-server-in-kubernetes (the first bullet)
