### ISSUE TITLE
RBAC on AKS: Helm keeps asking for login token on every command

### ISSUE THREAD

**Issue by dploeger** [Azure/AKS#1008]
*This is a cross post with #helm-5788. The guys over there recommended, I'd ask you guys about this, too, because you have the insight in AKS' authentication methods*

**What happened**:

We're on AKS with RBAC enabled. Now when running any helm command that connects to the k8s cluster, I have to reauthenticate. This is the output:

```
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <redacted> to authenticate.
```

Then I can use helm for maybe one or two other commands and the the login message is displayed again.

After opening the page and authenticating, Helm continues without a problem, but it is very tedious like this.

This doesn't happen with kubectl.

This is my debug output from `helm list`:

```
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <redacted> to authenticate.
[debug] Created tunnel using local port: '61806'

[debug] SERVER: "127.0.0.1:61806"

NAME         	REVISION	UPDATED                 	STATUS  	CHART               	APP VERSION	NAMESPACE
(...)
```

And this is the debug output from `kubectl get pods` https://gist.github.com/dploeger/b712d8d7ef0e8e7f79ee47bebcc0ae68

**What you expected to happen**:

helm perhaps only asks once for the authentication token. Kubectl didn't ask at all.

**How to reproduce it (as minimally and precisely as possible)**:

[Install Helm](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/aks/kubernetes-helm.md) on [RBAC-enabled AKS](https://docs.microsoft.com/de-de/azure/aks/azure-ad-integration-cli).

Run `helm list` or anything else that connects to Tiller.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?)

1

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

Java app with Elasticsearch

- Others:

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <redacted> to authenticate.
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

**Comment by dploeger** [comment]
Note: I'm using multiple accounts on Azure. Might be important.

**Comment by dploeger** [comment]
This seemed to be an issue with incompatible kubectl/helm versions. Using kubectl 1.14 together with the recent helm version works. I'll close this issue then.

**Comment by carlossg** [comment]
FWIW I have this issue with Helm v2.13.1 and kubectl v1.15.3 and v1.14.3
Upgrading Helm to 2.14 *seems* to fix the issue

I can reproduce just running 

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
...
$ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
...
$ kubectl version
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ... to authenticate.
```

**Comment by carlossg** [comment]
My workaround is to create a new shell session for helm, copy my `.kube/config` as `.kube/config-helm` and set `KUBECONFIG=.kube/config-helm`
Then I can use helm in that session and `kubectl` in other sessions with no issues
