### ISSUE TITLE
az aks browse open web ui always failed.

### ISSUE THREAD

**Issue by micli** [Azure/AKS#101]
I used "az aks browse" to start Kubernetes web ui but it always failed. 

<img width="750" alt="2017-12-27 10 38 25" src="https://user-images.githubusercontent.com/2059006/34368833-1ac80a60-eaf2-11e7-8a1d-cc809eb48180.png">

If I directly use “Kubectl proxy”, it works fine.

**Comment by slack** [comment]
If you visit `localhost:8001/ui` immediately after `aks browse` does the proxy work? The `browse` command is just a bit of porcelain around `kubectl proxy`...

**Comment by mboersma** [comment]
Under the covers, the commands that `az` runs here are roughly:
```shell
$ kubectl get pods --namespace kube-system --output name \
  --selector k8s-app=kubernetes-dashboard  # print the dashboard pod name
$ kubectl --namespace kube-system port-forward <dashboard-pod-name> 8001:9090
```
@micli do those commands work for you on their own?

**Comment by mboersma** [comment]
This is working in general and we haven't gotten more detail in a few weeks. I'm going to close this, but @micli please re-open if this behavior still exists.

**Comment by paritoshsingh** [comment]
I am facing the same issue.

**Comment by sunnypatel** [comment]
Seeing the same

**Comment by JuneZhao** [comment]
Now the port of dashboard should be 8443 not 9090, someone changed the port
