### ISSUE TITLE
Creation of "jumpbox" VM for RDP into Windows Nodes fails

### ISSUE THREAD

**Issue by brobichaud** [Azure/AKS#1011]
**What happened**:
Following the steps to gain RDP access to Windows nodes on the page below fails. I am unable to RDP into the VM that is created.

https://docs.microsoft.com/en-us/azure/aks/rdp

**What you expected to happen**:
For the RDP connection to the created VM to succeed, so that I can then RDP into the nodes.

**How to reproduce it (as minimally and precisely as possible)**:
Follow steps on referenced page and see that RDP connection to VM fails.

**Anything else we need to know?**:
I was able to successfully RDP into the VM after I enabled inbound access to port 3389 on the Network Security Group that AKS created during cluster creation.

My understanding when there is an NSG assigned to a NIC when is part of a subnet that has it's own NSG that both NSG's need to have the port open. This seems to be validated by the manual change I needed to make, is this correct?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.0
- Size of cluster (how many worker nodes are in the cluster?): 2 F8s_v2 Windows nodes, 1 D1_v2 linux node.
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): I've only got a few small pods deployed, no issues here.
- Others:

**Comment by MikkelHegn** [comment]
Thanks for reporting this, we will get the docs updated.

The NSG is attached to the subnet, so any incoming / outgoing traffic on the subnet would need to be explicitly allowed. Please note that any RP updates (nodepool changes / updates / upgrades) will reset the NSG configuration.

**Comment by MikkelHegn** [comment]
This is now live: https://docs.microsoft.com/en-us//azure/aks/rdp#allow-access-to-the-virtual-machine
