### ISSUE TITLE
Unable to create AKS cluster with only Windows node

### ISSUE THREAD

**Issue by bobrundle** [Azure/AKS#1012]
**What happened**:

Created ASK cluster and added windows node pool.  Cannot delete Linux node pool or create a cluster with only a Windows node pool.  

**What you expected to happen**:

Expected to be able to create a cluster with only Windows agent nodes.  Cannot do it.

**How to reproduce it (as minimally and precisely as possible)**:

$ az aks create -g $env:resourceGroup -n $env:clusterName  --windows-admin-password $env:passwordWin --windows-admin-username $env:userName --location $env:location --generate-ssh-keys --node-count 0 --enable-vmss --network-plugin azure --kubernetes-version 1.14.0 --enable-addons monitoring

This will fail (divide by zero).  Cannot create a windows node pool as default.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.0
- Size of cluster (how many worker nodes are in the cluster?) 2 Windows agent nodes.
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by devkws** [comment]
I've wondered about this as well, it was my assumption that the cluster itself is linux bases and AKS simply supports a windows node pool. Because of this at least 1 linux node must always be present, would be interested to know if the long term goal is a windows only cluster.

**Comment by MikkelHegn** [comment]
This is currently how the service is designed: https://docs.microsoft.com/en-us/azure/aks/windows-node-limitations#aks-limitations-for-windows-server-node-pools - first bullet in that section.

**Comment by jnoller** [comment]
Closing issue
