### ISSUE TITLE
Unable to resolve external DNS

### ISSUE THREAD

**Issue by PixelRobots** [Azure/AKS#1015]
**What happened**:
I have set up a small cluster of one node running the standard size VM. I have a Windows container that runs fine on a VMSS running Docker. My container needs to talk to an external website when it starts. On the VMSS this works fine. On AKS I keep getting this error. The remote name could not be resolved: 'myvault.vault.azure.net' (have changed the name here)

**What you expected to happen**:
I expect DNS to resolve fine every time.

**How to reproduce it (as minimally and precisely as possible)**:
create a new AKS cluster. add windows node pool. deploy my deployment and service.

**Anything else we need to know?**:

this is just a basic newly created cluster. nothing fancy running on it.

**Environment**:
- Kubernetes version (use `kubectl version`):v1.13.5
- Size of cluster (how many worker nodes are in the cluster?)1 windows node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)c# code targeting the .net framework.
- Others: the container is running server core.

**Comment by brunoscota** [comment]
Hi, are you using an existent VNET? or are you creating a new one?

**Comment by PixelRobots** [comment]
Creating a new one. Everything is new, new resource group too.

**Comment by MikkelHegn** [comment]
I cannot reproduce this as a general issue. I would suggest that you open a support ticket through the Azure Portal for further troubleshooting.

**Comment by PixelRobots** [comment]
Thanks, I have just raised the ticket.

**Comment by zhiweiv** [comment]
https://github.com/Azure/aks-engine/issues/189
https://github.com/Azure/AKS/issues/1014

**Comment by PixelRobots** [comment]
It does not look to be the same.

**Comment by MikkelHegn** [comment]
FYI: https://github.com/Azure/AKS/issues/1029

**Comment by PatrickLang** [comment]
A new Windows image is rolled out. Can you try creating a new cluster and see if DNS is working better? Right now we're digging into issues blocking node pool / cluster upgrades with VM scale sets so you'll need a new cluster to get this change.

Windows version 10.0.17763.557 has some fixes that improve reliability of Pod -> Kubernetes service connectivity which also fixes DNS since it's a K8s service.

```
kubectl get node -o wide
NAME                                STATUS   ROLES   AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                    KERNEL-VERSION      CONTAINER-RUNTIME
aks-nodepool1-20293662-vmss000000   Ready    agent   15m     v1.14.0   10.240.0.4    <none>        Ubuntu 16.04.6 LTS          4.15.0-1049-azure   docker://3.0.4
aksnpwin000000                      Ready    agent   7m37s   v1.14.0   10.240.0.35   <none>        Windows Server Datacenter   10.0.17763.557      docker://18.9.2
```

This does not solve the issue where DNS takes several seconds to initialize after a pod starts up.
