### ISSUE TITLE
node-vm-size validation using az aks nodepool add

### ISSUE THREAD

**Issue by asc-adean** [Azure/AKS#1021]
Hello,

For giggles and because I like to break things, I attempted to create a nodepool with an invalid VM size designation (Standard_D6s_v3)

The pool is created but in a failed state, and is unable to be deleted.

A possible resolution would be to do validation on the --node-vm-size before the nodepool is created

How to repeat:
1. Perform the steps to register the az aks nodepool command as listed here:
https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools

2. Create a cluster or use an existing cluster that was created using this method
(there does exist clusters that have `--enable-vmss` but are not in nodepools, those clusters are in a strange state, if you want the ID of one, I can give it to you)

3. Run this command after the cluster is created/use existing cluster:
`az aks nodepool add --resource-group <rg-name> --cluster-name <cluster-name> --name badpool --node-count 1 --node-vm-size Standard_D6s_v3`
at this point you will get an error 
```
Deployment failed. Correlation ID: 4ec80dd2-70b6-4913-9721-431e53fb2cda. Code="InvalidTemplate" Message="Deployment template validation failed: 'The provided value 'Standard_D6s_v3' for the template parameter 'bigpoolVMSize' at line '1' and column '1705' is not valid. The parameter value is not part of the allowed value(s): <insert all valid VM sizes here>
```

4. Try to delete pool in the web console UI or via:
`az aks nodepool delete--resource-group <rg-name> --cluster-name <cluster-name> --name badpool`
You should get the error:
```
Deployment failed. Correlation ID: aeb2c738-8491-485e-9ea9-1d413abdca08. Failed to delete the vmss agentpool:
```

Linked from: https://github.com/MicrosoftDocs/azure-docs/issues/31925

**Comment by jnoller** [comment]
@asc-adean Honestly, this is a fantastic bug, and a key reason we shifted to public user-opt in of preview features.

**Comment by jluk** [comment]
Thanks for report @asc-adean I tried a repro and was able to delete the nodepool. As a result closing this issue, but we will improve the error message kicked back from the false input provided.
