### ISSUE TITLE
Creating a cluster with monitoring workspace requires permission to create resource groups in subscription

### ISSUE THREAD

**Issue by nodeselector** [Azure/AKS#1022]
**What happened**:

Customer creates an AKS cluster with monitoring workspace enabled, but they do not have permissions to create resource groups. The creation process will fail with error message: `ResourceGroupNotFoundResource group "DefaultResourceGroup-xxx" could not be found.`

**What you expected to happen**:

Since the issue is more with a lack of permissions to create the resource group, rather than the resource group not existing, it would be more accurate for this to throw an error related to insufficient permissions.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a user that does not have permissions to create resource groups on Azure
2. Deploy an AKS cluster with monitoring workspace enabled
3. The deployment will fail with  `DefaultResourceGroup-xxx`

**Anything else we need to know?**:

No.

**Environment**:
- Kubernetes version (use `kubectl version`):

Unrelated to K8s version.

- Size of cluster (how many worker nodes are in the cluster?)

Unrelated.

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Unrelated.

- Others:

To work around this you will need to gain permissions to create resource groups or create the monitoring resource group before provisioning the cluster.

**Comment by jluk** [comment]
This may an older issue which was resolved by a discussion with the OMS team many months back, as a result I am going to close this but if this is still occurring for you @nodeselector just ping the issue and I will revisit!
