### ISSUE TITLE
cannot create an external load balancer with mix protocols

### ISSUE THREAD

**Issue by devteng** [Azure/AKS#1026]
**What happened**:
Creating a k8s service in k8s 1.12.8 with UDP+TCP and azure-load-balancer-mixed-protocols: "true" still throws "cannot create an external load balancer with mix protocols"
**What you expected to happen**:
Loadbalancer created with both UDP and TCP ports
**How to reproduce it (as minimally and precisely as possible)**:
Create a k8s Service yaml with the azure-load-balancer-mixed-protocols set to true and define both TCP and UDP

**Anything else we need to know?**:
It was closed as fixed/released fix in:
https://github.com/Azure/AKS/issues/754
https://github.com/kubernetes/kubernetes/pull/74200#issuecomment-485117779
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
5
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
sandbox
- Others:

**Comment by jnoller** [comment]
The last 2 comments on the cited patch note that upstream kubernetes is still Defaulting to tcp only and the udo functionality is incomplete: https://github.com/kubernetes/kubernetes/pull/74200#issuecomment-485836928

**Comment by feiskyer** [comment]
Refer https://github.com/kubernetes/enhancements/issues/1435, the feature is still alpha in upstream
