### ISSUE TITLE
Cluster egress uses unexpected IP

### ISSUE THREAD

**Issue by brobichaud** [Azure/AKS#1027]
**What happened**:
I've deploy an AKS cluster with Windows nodes and I am puzzled by the egress IP address that is used. I need to whitelist this cluster with some of my services hosted elsewhere and the IP address I am seeing trying to access those services is not what I expected. In fact I can't figure out where the egress IP is even defined as there is no visible Public IP resource in my Azure subscription that matches it. I also can look at the "Frontend IP configuration" of the LB used by the cluster and it does not show the egress IP either.

I had been under the impression, based on this article: http://bit.ly/2M9BT36, that I need to deploy a k8s service using a known Public IP as the first service in order to get a "static" IP, one that won't change as I add/remove other services. I did this but the cluster is not using this as the egress IP.

**What you expected to happen**:
For the cluster to use the Public IP of the very first service I deploy as the egress IP.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new AKS cluster with Windows nodes
2. Deploy a simple k8s service with no deployments bound to it using the yaml below
3. Deploy a pod that access some external service where I can see the incoming client IP Address
4. Compare the client IP from step 3 with the IP of the service created in step 2

```
apiVersion: v1
kind: Service
metadata:
  name: cluster-egress-ip
spec:
  loadBalancerIP: [IP_ADDRESS]
  type: LoadBalancer
  ports:
  - port: 443
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.0
- Size of cluster (how many worker nodes are in the cluster?): 2 Windows Standard_F8s_v2 nodes, 1 linux Standard_D1_v2 node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): A mix of HTTP AspNetCore services and .NET Framework worker services (console apps). 19 Pods running on the Windows nodes, none of the linux node.
- Others:

**Comment by seanmck** [comment]
This is a limitation of the basic load balancer. Since it can only point to one backend pool, it points to the Linux-based one. That leaves the Windows nodes to still be SNAT'd to a random public IP from the Azure pool.

This will be resolved by the standard load balancer: #643.
