### ISSUE TITLE
Support for Kubernetes 1.9

### ISSUE THREAD

**Issue by pjbgf** [Azure/AKS#103]
Is there any ETA for when support for Kubernetes 1.9 will be added?

**Comment by AceHack** [comment]
The sooner the better :)  Would love to see windows VMs come along with that too!!

**Comment by Sleepy-GH** [comment]
Very much looking forward to this. Especially the storage improvements for me personally.

**Comment by AceHack** [comment]
Any update?  Thanks.

**Comment by mboersma** [comment]
AKS supports Kubernetes v1.9.0 and v1.9.1 with Linux nodes now, with v1.9.2 coming any day.

**Comment by AceHack** [comment]
Is there no upgrade path?  I get the following

Name     ResourceGroup     MasterVersion    MasterUpgrades    NodePoolVersion    NodePoolUpgrades
-------  ----------------  ---------------  ----------------  -----------------  ------------------
default  rgp-use-arch-aks  1.8.6            None available    1.8.6              None available

**Comment by derekperkins** [comment]
Same here. My cluster is in centralus

**Comment by AceHack** [comment]
@derekperkins I just executed

`az` aks upgrade --name aks-use-arch-dev --resource-group rgp-use-arch-aks --kubernetes-version 1.9.1 --yes

and it worked and upgraded even though

`az` aks get-versions --name aks-use-arch-dev --resource-group rgp-use-arch-aks --output table

said there were no upgrades

**Comment by kryoflux** [comment]
Is it possible to subscribe to an RSS feed or something that announces when new Kubernetes versions are supported in AKS?

**Comment by vyadh** [comment]
Is it possible to subscribe to an RSS feed or something that announces when new Kubernetes versions are supported in AKS?

**Comment by AceHack** [comment]
@derekperkins FYI, I'm getting the following error with any az aks command now after upgrading.

No Kubernetes access profiles found. Cluster provisioning state is "Succeeded".

**Comment by AceHack** [comment]
@mboersma I don't see 1.9.x in the Azure Portal UI, not sure why this was closed before it was there.  I'll try from the command line, but I agree with @vyadh how do I know what's available?

**Comment by AceHack** [comment]
I tried running

`az aks create --name aks-use-arch-dev --resource-group rgp-use-arch-aks --location eastus --kubernetes-version 1.9.1 --node-vm-size Standard_DS12_v2_Promo --node-osdisk-size 300 --node-count 5 --service-principal {GUID} --client-secret {GUID} --admin-username {user} --ssh-key-value "ssh-key"`

It failed with

ERROR: Operation failed with status: 'Bad Request'. Details: The value of parameter orchestratorProfile.OrchestratorVersion is invalid.


I'm really not sure why this is closed, it seems in no way is 1.9 supported currently.  Thanks.

**Comment by derekperkins** [comment]
@AceHack I forced the upgrade the same time as you, and though it didn't report a success originally, when I check my versions now with `az aks get-versions`, it shows me on 1.9.1.

```
Name     ResourceGroup    MasterVersion    MasterUpgrades    NodePoolVersion    NodePoolUpgrades
-------  ---------------  ---------------  ----------------  -----------------  ------------------
default  nozzle           1.9.1            None available    1.9.1              None available
```

**Comment by pjbgf** [comment]
@AceHack it worked for me by creating a cluster with the default 1.7.9. Once it was up and running, I executed the upgrade command to 1.7.9:

`az aks upgrade -n CLUSTER-NAME -g RESOURCE-GROUP --kubernetes-version 1.9.1 -y`

**Comment by AceHack** [comment]
Yes, I did the same starting with 1.8.6 and it failed twice during the upgrade but then finally worked.  I did notice the dashboard is still 1.8.x though.  This seems a bit odd.

**Comment by derekperkins** [comment]
@AceHack The dashboard is on a separate release schedule from the main project. The current dashboard version is 1.8.2, and AKS is on 1.8.1.
https://github.com/kubernetes/dashboard/releases

**Comment by Sleepy-GH** [comment]
Is this only working in specific locations? I just tried creating a new cluster with az aks create <snip> --kubernetes-version 1.9.0 --location westeurope and I get the following error: 
"Operation failed with status: 'Bad Request'. Details: The value of parameter orchestratorProfile.OrchestratorVersion is invalid."

**Comment by seneccamiller** [comment]
FYI, 

I also had success updating to v1.9.1 using the command below as well in the East-US region

az aks upgrade --name myK8sCluster --resource-group myResourceGroup --kubernetes-version 1.9.1 --yes

**Comment by joukojoutomies** [comment]
I tried upgrade from version 1.8.1 to 1.9.1 and it failed. In portal It shows version 1.9.1 and "deployment status failed" (under resource group). Cluster still works and I can add nodes, services, deployments etc...

-Jouni

on win10 CLI (and on web portal bash cli as well) I have:
C:\>az aks show -g DemoGroup -n DemoCluster
{
  "agentPoolProfiles": [
    {
      "count": 2,
      "name": "nodepool1",
      "osType": "Linux",
      "storageProfile": "ManagedDisks",
      "vmSize": "Standard_D1_v2"
    }
  ],
  "dnsPrefix": "XXX",
  "fqdn": "XXX.hcp.eastus.azmk8s.io",
  "id": "/subscriptions/X/X/providers/Microsoft.ContainerService/managedClusters/AKSDemoCluster",
  "kubernetesVersion": "1.9.1",
  "linuxProfile": {
    "adminUsername": "XXX",
    "ssh": {
      "publicKeys": [
        {
          "keyData": "ssh-rsa <key here>"
        }
      ]
    }
  },
  "location": "eastus",
  "name": "DemoCluster",
  "provisioningState": "Failed",
  "resourceGroup": "DemoGroup",
  "servicePrincipalProfile": {
    "clientId": "XXX"
  },
  "type": "Microsoft.ContainerService/ManagedClusters"
}

**Comment by chribsen** [comment]
I was able to upgrade my AKS cluster in `westeurope` using:
```
az aks upgrade -n $CLUSTER_NAME -g $RESOURCE_GROUP -k 1.9.1 -y
```

**Comment by liambarnett** [comment]
I have executed the various above upgrade commands to no avail. Every time I receive this message - 

> Operation failed with status: 'Bad Request'. Details: The selected orchestrator version is not supported

.

I have checked the version with:
`az aks get-versions --name $ClusterName --resource-group $ResourceGroup --output table`

but the version remains the same. 

I have tested with 'East US' and 'West Europe' regions, created a 1.7 and 1.8 cluster and created a cluster via the GUI/console - none of these work!

Is there something I'm missing or have they put a stop to this in the last 48 hours?

**Comment by liambarnett** [comment]
@chribsen  - which region did you use?

@AceHack, @derekperkins - Have you had any luck with this since?

As above, I cannot force the upgrade no matter how I set the initial cluster up.

**Comment by derekperkins** [comment]
@liambarnett I've been running 1.9.1 in centralus for almost 2 weeks without any problems.

**Comment by liambarnett** [comment]
@derekperkins thanks, just tested on centralus but receiving the same message. I'm assuming they've disabled the forced upgrade.

**Comment by przemolb** [comment]
Is there any way I can list available k8s versions ? I used `az aks get-versions` (in westeurope) but it tells me that the newest one is 1.8.7.

**Comment by liambarnett** [comment]
@przemolb I'm not sure this is possible, it will only list available versions to avoid confusion.

**Comment by przemolb** [comment]
@liambarnett hmm, in that case is there any web page with schedule where and when each k8s version will be available ?

**Comment by liambarnett** [comment]
@przemolb This might be what you're after - https://github.com/kubernetes/kubernetes/milestones

**Comment by przemolb** [comment]
@liambarnett I am sorry but I've just realized I asked the wrong question - I meant to ask where (region) and when each k8s version will be available on Azure ?

**Comment by micahmckittrick** [comment]
@mboersma Do you know if people are still able to force update to 1.9? @liambarnett looks like he is not able to even though he is running the same command as others.

**Comment by dmitsh** [comment]
We are planning start rolling out AKS with 1.9 support next week.

**Comment by przemolb** [comment]
In every region ?

**Comment by liambarnett** [comment]
@dmitsh which regions will receive the update first?

**Comment by indrayam** [comment]
Any update on @liambarnett's question?

**Comment by dmitsh** [comment]
We are in the process of gradually rolling out and testing. There were a few issues that we have identified and addressing. I will update this thread as soon as we have the service rolled out (current estimate is early next week)

**Comment by indrayam** [comment]
Thanks @dmitsh

**Comment by a3aanwisse** [comment]
@dmitsh Since early next week has passed... any update?

**Comment by giggio** [comment]
I was able to upgrade to 1.8.7, but after that it would not allow me to upgrade to 1.9.1 or 1.9.2:

> Operation failed with status: 'Bad Request'. Details: The selected orchestrator version is not supported

**Comment by giggio** [comment]
I just tried upgrading from 1.7.9 to 1.9.0, 1.9.1, 1.9.2, and none of them works. I always get
> Operation failed with status: 'Bad Request'. Details: The selected orchestrator version is not supported

**Comment by giggio** [comment]
It does not support incremental upgrades as well. I have just tried. I upgraded to 1.8.7 and then tried to upgrade to 1.9.0 and 1.9.1 and both fail with the same error as before.

**Comment by dmitsh** [comment]
Could you please send error messages?

**Comment by giggio** [comment]
Here is the output:

````bash
~$ az aks upgrade -g $nomeDoGrupoDeRecursos -n $nomeCluster --kubernetes-version 1.9.0 --yes
Operation failed with status: 'Bad Request'. Details: The selected orchestrator version is not supported
````

**Comment by dmitsh** [comment]
To the best of my knowledge, AKS supports 1.9.1 and 1.9.2

You can check by running “az aks get-upgrades” or “az aks get-versions”

**Comment by tanaka-takayoshi** [comment]
1.9 is still not available now?

```
$ az aks get-versions -l centralus  -o table
This command is deprecating and will be removed in future releases. Use 'az aks get-upgrades' instead.
KubernetesVersion    Upgrades
-------------------  -----------------------------------------
1.8.7                None available
1.8.6                1.8.7
1.8.2                1.8.6, 1.8.7
1.8.1                1.8.2, 1.8.6, 1.8.7
1.7.12               1.8.1, 1.8.2, 1.8.6, 1.8.7
1.7.9                1.7.12, 1.8.1, 1.8.2, 1.8.6, 1.8.7
1.7.7                1.7.9, 1.7.12, 1.8.1, 1.8.2, 1.8.6, 1.8.7

$ az aks get-upgrades -g aks-test -n aks-cluster2 -o table
Name     ResourceGroup    MasterVersion    NodePoolVersion    Upgrades
-------  ---------------  ---------------  -----------------  -----------------------------------------
default  aks-test         1.7.7            1.7.7              1.7.9, 1.7.12, 1.8.1, 1.8.2, 1.8.6, 1.8.7
```

**Comment by giggio** [comment]
I just tested it all. Creating a new cluster or updating. 1.9.x is not available.

**Comment by joaocc** [comment]
Same thing in westeurope. No upgrade path from 1.8.7 upwards.

**Comment by mboersma** [comment]
Kubernetes 1.9.x isn't yet available on AKS. As @dmitsh mentioned, we are still testing the necessary changes and will update here when it's rolled out.

**Comment by hibri** [comment]
Would these annotations make it into 1.9? https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L41

**Comment by giggio** [comment]
I just saw that 1.9.* are showing as available. I tried creating a 1.9.2 cluster but the deploy failed.

````
❯ az aks get-versions --location eastus -o table
KubernetesVersion    Upgrades
-------------------  -----------------------------------------
1.9.2                None available
1.9.1                1.9.2
1.8.7                1.9.1, 1.9.2
1.8.6                1.8.7, 1.9.1, 1.9.2
1.8.2                1.8.6, 1.8.7, 1.9.1, 1.9.2
1.8.1                1.8.2, 1.8.6, 1.8.7, 1.9.1, 1.9.2
1.7.12               1.8.1, 1.8.2, 1.8.6, 1.8.7
1.7.9                1.7.12, 1.8.1, 1.8.2, 1.8.6, 1.8.7
1.7.7                1.7.9, 1.7.12, 1.8.1, 1.8.2, 1.8.6, 1.8.7
````

**Comment by dmitsh** [comment]
Yes, we just rolled out new update.
Could you provide error message?

**Comment by giggio** [comment]
It just failed. Maybe you can pull it from the correlation id:

````
❯ az aks create -g $nomeDoGrupoDeRecursos -n $nomeCluster --kubernetes-version 1.9.2
Deployment failed. Correlation ID: 2f7bdd8f-c496-475d-a0a3-5f47c55dc6e9. Timeout while polling for control plane provisioning status
````

**Comment by Trane9991** [comment]
Tried to provision k8s 1.9.2 via terraform. Provision took ~20 minutes and failed with error:

```
Long running operation terminated with status 'Failed': Code="ControlPlaneAddOnsNotReady" Message=""
```

**Comment by Trane9991** [comment]
The same operation for k8s 1.9.1 seems to complete successfully.

**Comment by giggio** [comment]
I was later able to provision a 1.9.2 cluster successfully.

**Comment by przemolb** [comment]
I was able to upgrade existing 1.8.7 cluster to 1.9.2. Unfortunately I lost one node:
`
kubectl get nodes -o wide
NAME                       STATUS                        ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                       KERNEL-VERSION      CONTAINER-RUNTIME
aks-nodepool1-19398553-0   Ready                         agent     4h        v1.9.2    <none>        Debian GNU/Linux 9 (stretch)   4.13.0-1007-azure   docker://1.13.1
aks-nodepool1-19398553-1   Ready                         agent     4h        v1.9.2    <none>        Debian GNU/Linux 9 (stretch)   4.13.0-1007-azure   docker://1.13.1
aks-nodepool1-19398553-2   Ready                         agent     3h        v1.9.2    <none>        Debian GNU/Linux 9 (stretch)   4.13.0-1007-azure   docker://1.13.1
aks-nodepool1-19398553-3   Ready                         agent     3h        v1.9.2    <none>        Debian GNU/Linux 9 (stretch)   4.13.0-1007-azure   docker://1.13.1
aks-nodepool1-19398553-4   NotReady,SchedulingDisabled   agent     25d       v1.8.7    <none>        Debian GNU/Linux 8 (jessie)    4.11.0-1016-azure   docker://1.12.6
aks-nodepool1-19398553-5   Ready                         agent     4h        v1.9.2    <none>        Debian GNU/Linux 9 (stretch)   4.13.0-1007-azure   docker://1.13.1
`
What should I run now to restore it ?

**Comment by dmitsh** [comment]
How many nodes originally were in your cluster? 5 or 6?

**Comment by przemolb** [comment]
Actually 5. You are right - didn't count them correctly ;-)
Can I get rid of the `NotReady` one from the list above (to have clean output of the command) ?

**Comment by dmitsh** [comment]
@przemolb try "kubectl delete node aks-nodepool1-19398553-4". This will deregister already non-existing node.

**Comment by arbourd** [comment]
@dmitsh thanks so much for keeping us in the loop (even though it probably blew up your emails)!

**Comment by andtii** [comment]
Im trying to provision a cluster in WestEurope using the latest version but got the following error: The value of parameter orchestratorProfile.OrchestratorVersion is invalid. Any updates on this issue?
