### ISSUE TITLE
Pod failed mounting xfs format volume

### ISSUE THREAD

**Issue by AVBee** [Azure/AKS#1030]
**What happened**:
Failed pod mounting volume with xfs format when installing mongoDB with helm

**What you expected to happen**:
MongoDB Pod will runs with xfs format volume

**How to reproduce it (as minimally and precisely as possible)**:
1. Create storage class
```
Name:            azuredisk-xfs
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"azuredisk-xfs"},"mountOptions":["dir_mode=0777","file_mode=0777","uid=1000","gid=1000"],"parameters":{"fsType":"xfs","storageaccounttype":"Standard_LRS"},"provisioner":"kubernetes.io/azure-disk"}

Provisioner:           kubernetes.io/azure-disk
Parameters:            fsType=xfs,storageaccounttype=Standard_LRS
AllowVolumeExpansion:  True
MountOptions:
  dir_mode=0777
  file_mode=0777
  uid=1000
  gid=1000
ReclaimPolicy:      Delete
VolumeBindingMode:  Immediate
Events:             <none>
```
2. helm install -f values.yaml stable/mongodb 

**Anything else we need to know?**:

kubectl describe pod
```
Events:
  Type     Reason                  Age                  From                               Message
  ----     ------                  ----                 ----                               -------
  Warning  FailedScheduling        100s (x5 over 113s)  default-scheduler                  pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled               100s                 default-scheduler                  Successfully assigned mongo-test/v1m1x-mongodb-5c8b7b8dc8-hwf7z to aks-nodepool1-29460110-0
  Normal   SuccessfulAttachVolume  74s                  attachdetach-controller            AttachVolume.Attach succeeded for volume "pvc-d783d0e4-85a1-11e9-8a90-369885447933"
  Warning  FailedMount             63s                  kubelet, aks-nodepool1-29460110-0  MountVolume.MountDevice failed for volume "pvc-d783d0e4-85a1-11e9-8a90-369885447933" : azureDisk - mountDevice:FormatAndMount failed with mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m436970985 --scope -- mount -t xfs -o dir_mode=0777,file_mode=0777,uid=1000,gid=1000,defaults /dev/disk/azure/scsi1/lun2 /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m436970985
Output: Running scope as unit run-rb21966413ab449b3a242ae9b0fbc9398.scope.
mount: wrong fs type, bad option, bad superblock on /dev/sde,
       missing codepage or helper program, or other error
```

kubectl describe pvc
```
Name:          v1m1x-mongodb
Namespace:     mongo-test
StorageClass:  azuredisk-xfs
Status:        Bound
Volume:        pvc-d783d0e4-85a1-11e9-8a90-369885447933
Labels:        app=mongodb
               chart=mongodb-5.17.0
               heritage=Tiller
               release=v1m1x
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      10Gi
Access Modes:  RWO
Events:
  Type       Reason                 Age   From                         Message
  ----       ------                 ----  ----                         -------
  Normal     ProvisioningSucceeded  12m   persistentvolume-controller  Successfully provisioned volume pvc-d783d0e4-85a1-11e9-8a90-369885447933 using kubernetes.io/azure-disk
Mounted By:  v1m1x-mongodb-5c8b7b8dc8-hwf7z

```
**Environment**:
- Kubernetes version (use `kubectl version`): v.1.12.7
- Size of cluster (how many worker nodes are in the cluster?) Standard_D4s_v3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by Arvinduppar** [comment]
Hi,
AvBee I reproduced the issue. Then I ran the "dmesg | tail" command  I could see "ioctl error in smb2_get_dfs_refer rc=-5". This link would help you https://www.ckode.dk/linux/switching-from-ubuntu-to-fedora-part-2-cifs-vfs-ioctl-error-in-smb2_get_dfs_refer/ to solve that error. In the the create storage class Annotations:   "mountOptions":["dir_mode=0777","file_mode=0777","uid=1000","gid=1000","iocharset=utf8","vers=1.0"]. I added "iocharset= utf8" and "vers=1.0" and then I ran kubectl get pv,pvc it could see it as bound. It worked me

**Comment by Arvinduppar** [comment]
Hi,
AvBee I reproduced the issue. Then I ran the "dmesg | tail" command I could see "ioctl error in smb2_get_dfs_refer rc=-5". This link would help you https://www.ckode.dk/linux/switching-from-ubuntu-to-fedora-part-2-cifs-vfs-ioctl-error-in-smb2_get_dfs_refer/ to solve that error. In the the create storage class Annotations: "mountOptions":["dir_mode=0777","file_mode=0777","uid=1000","gid=1000","iocharset=utf8","vers=1.0"]. I added "iocharset= utf8" and "vers=1.0" and then I ran kubectl get pv,pvc it could see it as bound. It worked for me.

**Comment by andyzhangx** [comment]
question is does xfs file system supports following mount options?
```
  dir_mode=0777
  file_mode=0777
  uid=1000
  gid=1000
```
I think you may try remove those mount options and then try again.

**Comment by AVBee** [comment]
@Arvinduppar in my case i already bound to PVC but can't be mounted to pod.


> question is does xfs file system supports following mount options?
> 
> ```
>   dir_mode=0777
>   file_mode=0777
>   uid=1000
>   gid=1000
> ```
> 
> I think you may try remove those mount options and then try again.
> 
> @AVBee

That's worked. Seems xfs doesn't support these IDs. 

@andyzhangx thank you
