### ISSUE TITLE
NVIDIA device plugin for GPU support not working on NC Promo VMs

### ISSUE THREAD

**Issue by itssimon** [Azure/AKS#1031]
**What happened**:

I created a new AKS node pool with **Standard_NC6_Promo** VMs with GPU support. I followed the Azure guide on [using GPUs](https://docs.microsoft.com/en-us/azure/aks/gpu-cluster). After installing the NVIDIA device plugin for Kubernetes the nodes still don't have the "nvidia.com/gpu" capacity. I checked the pod logs of the NVIDIA device plugins and they show:

```
2019/06/03 04:16:34 Loading NVML
2019/06/03 04:16:34 Failed to initialize NVML: could not load NVML library.
2019/06/03 04:16:34 If this is a GPU node, did you set the docker default runtime to `nvidia`?
2019/06/03 04:16:34 You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
2019/06/03 04:16:34 You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
```

**What you expected to happen**:

GPU capacity available on GPU-enabled nodes.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the guide linked above.

**Anything else we need to know?**:

It works fine on non-promotional Standard_NC6 VM types.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.0

**Comment by palma21** [comment]
Could you please open a support ticket?

**Comment by jluk** [comment]
@itssimon we made some fixes for promo SKUs, but would like to know if your GPU case is still broken. Can you please comment if it is still occurring and if so, a support ticket #? Otherwise I will close if no answer in a week.

**Comment by itssimon** [comment]
Thanks @jluk. Unfortunately I can't check as I'm no longer on Azure.

**Comment by anirudhgarg** [comment]
Just wanted to mention that I faced the same issue that the GPU is not schedulable for N6 promo SKU

**Comment by anirudhgarg** [comment]
Wanted to add that it works fine for N6 (non promotional)

**Comment by palma21** [comment]
The OP Issue was for NC_promo
If I see correctly you are trying N_promo, is that right?

we can have that one added to the GPU driver list.

**Comment by jluk** [comment]
Closing due to staleness, if issue is recurring please reopen a new issue or follow up with Azure support for an SLA'd response to troubleshoot.
