### ISSUE TITLE
'--node-vm-size' parameter causes error at creating windows node pool

### ISSUE THREAD

**Issue by hiroshi1000** [Azure/AKS#1037]
**What happened**:
CLI fails when trying to add a new windows node pool with '--node-vm-size' parameter.
The error message is like "az: error: unrecognized arguments: --node-vm-size Standard_B4MS".

**What you expected to happen**:
A new window node pool of the designated vm size will be created without error.

**How to reproduce it (as minimally and precisely as possible)**:
Execute a command like below;
az aks nodepool add \
     --resource-group _*your-resource-group-name*_ \
     --cluster-name _*your-cluster-name*_ \
     --os-type Windows \
     --name _*node-pool-name-you-want-to-create*_ \
     --node-vm-size Standard_B4MS \
     --node-count 1 \
     --kubernetes-version 1.14.0

**Anything else we need to know?**: N/A

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
One Linux node pool within the cluster.

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
HTTP microservices.

- Others:
 Client: Azure CLI on both Cloud Shell and macOS Mojave
 azure-cli version: 2.0.64

**Comment by MikkelHegn** [comment]
What's the version of the aks-preview extension you are using? I cannot reproduce the error using 0.4.1.

https://docs.microsoft.com/en-us//azure/aks/windows-container-cli#install-aks-preview-cli-extension

**Comment by hiroshi1000** [comment]
This is the version on my MacBook Pro.
`$ az extension list
[
  {
    "extensionType": "whl",
    "name": "aks-preview",
    "version": "0.4.1"
  }
]
`
This issue happens with CLI on Azure Cloud Shell, as well.

**Comment by MikkelHegn** [comment]
Can you try changing the `--node-vm-size` parameter to use casing similar to what's in this output `az vm list-sizes -l westeurope | jq .[].name` for the size you ant to use. It's probably a casing mismatch in the command. For the size you are using it should be `Standard_B4ms`

**Comment by hiroshi1000** [comment]
I tried as you suggest but unfortunately the result haven't changed.
`az: error: unrecognized arguments: --node-vm-size Standard_B4ms`

The exact name of the VM size was found in the output.
```
$ az vm list-sizes -l westeurope | jq .[].name | grep B4
"Standard_B4ms"
```

**Comment by xizhamsft** [comment]
@hiroshi1000 , could you rerun your az command with --debug and share with me the logs? I can't repro the issue on my side.

**Comment by hiroshi1000** [comment]
@xizhamsft All ritght. I've already done it last night. These are the outputs.

`$ az aks nodepool add     --resource-group ********     --cluster-name ********     --os-type Windows     --name *******     --node-vm-size "Standard_B4ms"     --node-count 1     --kubernetes-version 1.14.0 --debug`
> Command arguments: ['aks', 'nodepool', 'add', '--resource-group', '********', '--cluster-name', '********', '--os-type', 'Windows', '--name', '*******', '--node-vm-size\xa0Standard_B4ms', '--node-count', '1', '--kubernetes-version', '1.14.0', '--debug']
> Event: Cli.PreExecute []
> Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x10a9f6048>, <function OutputProducer.on_global_arguments at 0x10aa80d90>, <function CLIQuery.on_global_arguments at 0x10aab09d8>]
> Event: CommandInvoker.OnPreCommandTableCreate []
> Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'maps', 'monitor', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
> Loaded module 'acr' in 0.004 seconds.
> Loaded module 'acs' in 0.003 seconds.
> Loaded module 'advisor' in 0.001 seconds.
> Event: CommandLoader.OnLoadCommandTable []
> Loaded module 'ams' in 0.008 seconds.
> Loaded module 'appservice' in 0.020 seconds.
> Loaded module 'backup' in 0.002 seconds.
> Event: CommandLoader.OnLoadCommandTable []
> Loaded module 'batch' in 0.008 seconds.
> Loaded module 'batchai' in 0.004 seconds.
> Loaded module 'billing' in 0.001 seconds.
> Loaded module 'botservice' in 0.003 seconds.
> Event: CommandLoader.OnLoadCommandTable []
> Loaded module 'cdn' in 0.003 seconds.
> Loaded module 'cloud' in 0.001 seconds.
> Loaded module 'cognitiveservices' in 0.002 seconds.
> Loaded module 'configure' in 0.002 seconds.
> Loaded module 'consumption' in 0.002 seconds.
> Loaded module 'container' in 0.002 seconds.
> Loaded module 'cosmosdb' in 0.003 seconds.
> Loaded module 'deploymentmanager' in 0.003 seconds.
> Loaded module 'dla' in 0.004 seconds.
> Loaded module 'dls' in 0.003 seconds.
> Loaded module 'dms' in 0.002 seconds.
> Loaded module 'eventgrid' in 0.002 seconds.
> Loaded module 'eventhubs' in 0.003 seconds.
> Loaded module 'extension' in 0.001 seconds.
> Loaded module 'feedback' in 0.001 seconds.
> Loaded module 'find' in 0.001 seconds.
> Loaded module 'hdinsight' in 0.003 seconds.
> Loaded module 'interactive' in 0.000 seconds.
> Loaded module 'iot' in 0.003 seconds.
> Loaded module 'iotcentral' in 0.001 seconds.
> Loaded module 'keyvault' in 0.005 seconds.
> Loaded module 'kusto' in 0.002 seconds.
> Loaded module 'lab' in 0.006 seconds.
> Loaded module 'maps' in 0.002 seconds.
> Loaded module 'monitor' in 0.005 seconds.
> Loaded module 'network' in 0.029 seconds.
> Loaded module 'policyinsights' in 0.002 seconds.
> Loaded module 'privatedns' in 0.005 seconds.
> Loaded module 'profile' in 0.001 seconds.
> Loaded module 'rdbms' in 0.005 seconds.
> Loaded module 'redis' in 0.003 seconds.
> Loaded module 'relay' in 0.003 seconds.
> Loaded module 'reservations' in 0.002 seconds.
> Loaded module 'resource' in 0.006 seconds.
> Loaded module 'role' in 0.005 seconds.
> Loaded module 'search' in 0.002 seconds.
> Loaded module 'security' in 0.003 seconds.
> Loaded module 'servicebus' in 0.005 seconds.
> Loaded module 'servicefabric' in 0.003 seconds.
> Loaded module 'signalr' in 0.001 seconds.
> Loaded module 'sql' in 0.006 seconds.
> Loaded module 'sqlvm' in 0.002 seconds.
> Event: CommandLoader.OnLoadCommandTable []
> Loaded module 'storage' in 0.029 seconds.
> Loaded module 'vm' in 0.014 seconds.
> Loaded all modules in 0.246 seconds. (note: there's always an overhead with the first module loaded)
> Extensions directory: '/Users/hiroshi/.azure/cliextensions'
> Found 1 extensions: ['aks-preview']
> Event: CommandLoader.OnLoadCommandTable []
> Extensions directory: '/Users/hiroshi/.azure/cliextensions'
> Loaded extension 'aks-preview' in 0.003 seconds.
> Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x10ab32840>]
> az_command_data_logger : command args: aks nodepool add --resource-group {} --cluster-name {} --os-type {} --name {} --node-vm-size Standard_B4ms --node-count {} --kubernetes-version {} --debug
> metadata file logging enabled - writing logs to '/Users/hiroshi/.azure/commands'.
> Event: CommandLoader.OnLoadArguments []
> Event: CommandInvoker.OnPostCommandTableCreate [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x10ab51620>, <function register_ids_argument.<locals>.add_ids_arguments at 0x10ab7eea0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x10ab920d0>]
> Event: CommandInvoker.OnCommandTableLoaded []
> Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x10baae158>]
> cli.azure.cli.core.parser : az: error: unrecognized arguments: --node-vm-size Standard_B4ms
> az: error: unrecognized arguments: --node-vm-size Standard_B4ms
> usage: az [-h] [--verbose] [--debug]
>           [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
>           {aks} ...
> az_command_data_logger : exit code: 2
> telemetry.save : Save telemetry record of length 2648 in cache
> telemetry.check : Negative: The /Users/hiroshi/.azure/telemetry.txt was modified at 2019-06-13 01:11:23.543270, which in less than 600.000000 s
> command ran in 0.386 seconds.


`$ cat /Users/hiroshi/.azure/commands/2019-06-13.01-20-23.aks_nodepool_add.3774.log`
> CMD-LOG-LINE-BEGIN 3774 | 2019-06-13 01:20:23,067 | INFO | az_command_data_logger | command args: aks nodepool add --resource-group {} --cluster-name {} --os-type {} --name {} --node-vm-size Standard_B4ms --node-count {} --kubernetes-version {} --debug
> CMD-LOG-LINE-BEGIN 3774 | 2019-06-13 01:20:23,163 | ERROR | cli.azure.cli.core.parser | az: error: unrecognized arguments: --node-vm-size Standard_B4ms
> CMD-LOG-LINE-BEGIN 3774 | 2019-06-13 01:20:23,164 | INFO | az_command_data_logger | exit code: 2

**Comment by xizhamsft** [comment]
@hiroshi1000, this seems to be a bug in az cli because no requests are sent to AKS yet. I noticed that you are using cli version 2.0.64. Could you try updating your CLI and aks-preview extension to the latest version and see if that fixes your problem? If not, could you try using cloudshell from portal and see if you can repro?

**Comment by hiroshi1000** [comment]
@xizhamsft I updated Azure Cli to 2.0.66, aks-preview extension to 0.4.4 on my MacBook Pro and tried to again. Nothing changed. The problem was reproduced.
I also tried the same operations on Cloud Shell with the latest Azure Cli and aks-preview extension, unfortunately, the result was also no change. The same error occurred..

**Comment by xizhamsft** [comment]
@hiroshi1000, sorry for this. Just noticed that you have an extra No-Break space in your node-vm-size parameter. 

From your logs, note the bolded \xa0:
Command arguments: ['aks', 'nodepool', 'add', '--resource-group', '', '--cluster-name', '', '--os-type', 'Windows', '--name', '*******', '--node-vm-size**\xa0**Standard_B4ms', '--node-count', '1', '--kubernetes-version', '1.14.0', '--debug']

That is a No-Break space. Make sure to change to a regular space. Let me know if that helps.

**Comment by MikkelHegn** [comment]
Please let us know if this is still an issue

**Comment by hiroshi1000** [comment]
@xizhamsft @MikkelHegn Thank you for the advice! I checked the command line carefully and I found there is the special character in the line. When I edited the line on VS Code for Mac, it might have been mingled.
