### ISSUE TITLE
Case sensitive issues for resources specifications on Windows node pools vs Linux node pools 

### ISSUE THREAD

**Issue by spboyer** [Azure/AKS#1038]
Create a new AKS cluster with following script, specify windows password for Windows Node pools. CNI must be `azure` and use `vmss`

```console
export GROUP="my-aks-cluster"
export CLUSTER_NAME="aks-demo-cluster"

# password needed for the Windows nodes if we create a Win Node Pool
export PASSWORD_WIN="P@ssw0rd1234"

az group create -l eastus -n $GROUP

#create the aks cluster
az aks create \
    --resource-group $GROUP \
    --name $CLUSTER_NAME \
    --node-count 1 \
    --enable-addons monitoring \
    --kubernetes-version 1.14.0 \
    --generate-ssh-keys \
    --windows-admin-password $PASSWORD_WIN \
    --windows-admin-username azureuser \
    --enable-vmss \
    --network-plugin azure
```
Apply `nginx` image for deployment. 

Notice the `m` in the resources portion.

```console
        resources:
          limits:
            cpu: 1
            memory: 800m
          requests:
            cpu: 1
            memory: 300m
```

Complete file - **people.web.yaml**

```console
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peopleweb
  labels:
    app: peopleweb
spec:
  replicas: 1
  template:
    metadata:
      name: peopleweb
      labels:
        app: peopleweb
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: peopleweb
        image: nginx
        env:
        - name: "SERVICE_URL"
          value: "peoplesvc"
        resources:
          limits:
            cpu: 1
            memory: 800m
          requests:
            cpu: 1
            memory: 300m
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: peopleweb
---
apiVersion: v1
kind: Service
metadata:
  name: peopleweb
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: peopleweb
```

Deployment fails, Error on pod/replica sets states:

```
Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "peopleweb-644f55dd84-fdgzf": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused \"EOF\"": unknown
```

Change the `m` to `M`, re-apply all is well.

### Windows

In the following example, the resources portion has `m`, in either casing of the M/m deployment is successful to a windows node pool.

https://docs.microsoft.com/azure/aks/windows-container-cli#run-the-application

cc: @PatrickLang

**Comment by jnoller** [comment]
@MikkelHegn ^

**Comment by MikkelHegn** [comment]
The sample is wrong, in that memory suffixes should be stated using upper cases: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory.

Opened a doc issue to fix this: https://github.com/MicrosoftDocs/azure-docs/issues/33953

The fact that it works on Windows - well - Windows is not case aware, so... :-) I really have no opinion as to whether this should be fixed to break on Windows in Kubernetes...

**Comment by spboyer** [comment]
@MikkelHegn - we should fix this in AKS for sure. @PatrickLang has some ideas how to catch/fix.

**Comment by MicahMcKittrick-MSFT** [comment]
PR was submitted on the doc

https://github.com/MicrosoftDocs/azure-docs/issues/33953

**Comment by MikkelHegn** [comment]
https://github.com/kubernetes/kubernetes/issues/79950

**Comment by MikkelHegn** [comment]
Awaiting upstream bug being fixed
