### ISSUE TITLE
kubectl stopped working with ***eastus.azmk8s.io: no such host

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#104]
```
PS D:\Kubernetes\kube-resources\ark> kubectl get nodes
Unable to connect to the server: dial tcp: lookup aks-use-ar-rgp-use-arch-aks-774cce-acee7226.hcp.eastus.azmk8s.io: no such host
```

Things were working fine yesterday, this just started!!

**Comment by AceHack** [comment]
`az aks browse --name aks-use-arch-dev --resource-group rgp-use-arch-aks`

still works fine and I can see everything in my cluster

**Comment by AceHack** [comment]
I think this problem happened because of a second cluster I created and deleted with a similar name.  The problem started when I deleted that 2nd cluster.

The 2 clusters were:

--name aks-use-arch-dev --resource-group rgp-use-arch-aks
--name aks-use-arch-dev --resource-group rgp-use-arch-aks9

I deleted
--name aks-use-arch-dev --resource-group rgp-use-arch-aks9

and then
--name aks-use-arch-dev --resource-group rgp-use-arch-aks

kubectl stopped working with the error above

**Comment by seanknox** [comment]
Closing due inactivity. Feel free to re-open if still an issue.

**Comment by toddbu** [comment]
I ran into this issue and it was because I had forgotten that I deleted the AKS cluster. it's not a terribly intuitive error

**Comment by shivarajisnhce** [comment]
az aks get-credentials --name CLUSTER_NAME --resource-group RESORCE_GROUP would solve
