### ISSUE TITLE
DNS and network timeout in AKS

### ISSUE THREAD

**Issue by cwebbtw** [Azure/AKS#1041]
**What happened**:

We are having intermittent problems with our AKS cluster where we are seeing network timeouts to the master when using `kubectl` and DNS failing from inside the pods. (we have 2 clusters running almost identical namespaces and pods but one of the clusters - which has subsequently been rebuilt and is still misbehaving)

An example of some of the strange behaviour we're seeing on this cluster:

_Unable to resolve github.com_

```
hudson.plugins.git.GitException: Command "git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/* --prune" returned status code 128:
stdout: 
stderr: ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.
```

_No route to host when trying to port forward_

```
kubectl port-forward svc/jenkins 8080:8080 -n jenkins-ns
error: error upgrading connection: error dialing backend: dial tcp 10.114.7.66:10250: connect: no route to host
```

_Runscope failures_

We're seeing runscope failures where an independent test is timing out when reaching our service that has been exposed as a service (type: loadbalancer). There are no restarts or errors showing on the pod and thus it feels like network connectivity issues to the cluster.

**What you expected to happen**:

I expect reasonable downtime but this is regularly happening, almost daily, primarily in afternoons (BST) and is happening more regularly in one of our clusters. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?)

```
$ kubectl get nodes
NAME                       STATUS    ROLES     AGE       VERSION
aks-agentpool-42571559-0   Ready     agent     13d       v1.13.5
aks-agentpool-42571559-1   Ready     agent     13d       v1.13.5
aks-agentpool-42571559-2   Ready     agent     13d       v1.13.5
aks-agentpool-42571559-3   Ready     agent     13d       v1.13.5
aks-agentpool-42571559-4   Ready     agent     13d       v1.13.5
aks-agentpool-42571559-5   Ready     agent     13d       v1.13.5
```

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

Very lightweight micronaut microservices and a jenkins CI running the kubernetes plugin.

- Others:

We seem to be having a number of restarts on our system pods and some of them seem to be older than others. We are not doing anything, that we know of, to the system pods.

```
$ kubectl get pods -n kube-system
NAME                                    READY     STATUS    RESTARTS   AGE
azure-cni-networkmonitor-8kcvj          1/1       Running   0          13d
azure-cni-networkmonitor-bsj5t          1/1       Running   1          13d
azure-cni-networkmonitor-dg5rn          1/1       Running   1          13d
azure-cni-networkmonitor-nh82x          1/1       Running   1          13d
azure-cni-networkmonitor-r9dpt          1/1       Running   1          13d
azure-cni-networkmonitor-zjkml          1/1       Running   1          13d
azure-ip-masq-agent-hjppg               1/1       Running   0          13d
azure-ip-masq-agent-lhpjk               1/1       Running   1          13d
azure-ip-masq-agent-pqqdr               1/1       Running   2          13d
azure-ip-masq-agent-qlxmp               1/1       Running   10         13d
azure-ip-masq-agent-s226m               1/1       Running   1          13d
azure-ip-masq-agent-s5b9t               1/1       Running   2          13d
coredns-574b9bb8d9-gb6zj                1/1       Running   0          12d
coredns-574b9bb8d9-nbjpj                1/1       Running   0          12d
coredns-autoscaler-6946b57db6-6wl26     1/1       Running   0          13d
kube-proxy-7j6b9                        1/1       Running   0          3h
kube-proxy-h2b98                        1/1       Running   0          3h
kube-proxy-ht9r8                        1/1       Running   0          3h
kube-proxy-jbb4q                        1/1       Running   0          3h
kube-proxy-mlqr9                        1/1       Running   0          3h
kube-proxy-x5hzz                        1/1       Running   0          3h
kube-svc-redirect-5mx5p                 2/2       Running   0          12d
kube-svc-redirect-8dd4g                 2/2       Running   0          12d
kube-svc-redirect-9hc64                 2/2       Running   0          12d
kube-svc-redirect-lc6hj                 2/2       Running   0          12d
kube-svc-redirect-lw5nx                 2/2       Running   0          12d
kube-svc-redirect-vvxjp                 2/2       Running   0          12d
kubernetes-dashboard-69b6c88658-cw8fq   1/1       Running   0          13d
metrics-server-766dd9f7fd-jwcsn         1/1       Running   0          13d
omsagent-2cp4x                          1/1       Running   0          5d
omsagent-4kqmb                          1/1       Running   0          5d
omsagent-9xvz5                          1/1       Running   0          5d
omsagent-b5mhr                          1/1       Running   0          5d
omsagent-c5mwt                          1/1       Running   0          5d
omsagent-c6lgj                          1/1       Running   0          5d
omsagent-rs-8f5b596c8-8fkgd             1/1       Running   0          5d
tunnelfront-86ddc648c9-k6z29            1/1       Running   0          1d
```

**Comment by jnoller** [comment]
@cwebbtw We do not see wide spread reports of this. Most commonly we see issues like this come up in advanced networking scenarios where custom DNS servers or customization to the CoreDNS configuration is triggering the failure. 

We can’t ask for the data we need to diagnose this on github, could you please open a support ticket in the Azure Portal, that way we can jump into the cluster and diagnose the issue

**Comment by cwebbtw** [comment]
Hey @jnoller, thanks for looking into this for us, the ticket we have created is: 119060526001363

**Comment by jnoller** [comment]
Thanks!

**Comment by lomori** [comment]
We are experiencing the same issue. Could you share how it got resolved?

**Comment by jnoller** [comment]
Please see this comment on next steps and details:

https://github.com/Azure/AKS/issues/1320#issuecomment-566166756

@cwebbtw  @lomori

**Comment by lomori** [comment]
Not sure if that's the same issue. We found out yesterday that even communication inside the cluster is broken. DNS is failing because pods can not contact the DNS service in the first place. No service can be reached from any pod. Internal cluster routing is broken.
