### ISSUE TITLE
[Calico] Typha pods spits out a lot of errors about missing CRD

### ISSUE THREAD

**Issue by ams0** [Azure/AKS#1042]
**What happened**:

On calico-enabled clusters (tried with and without PSP) calico-typha pod in kube-system floods the logs with errors like:

```
2019-06-05 13:23:56.985 [INFO][6] watchercache.go 242: Failed to create watcher ListRoot="/calico/resources/v3/projectcalico.org/bgppeers" error=resource does not exist: BGPPeer with error: the server could not find the requested resource (get BGPPeers.crd.projectcalico.org) performFullResync=true
```

**What you expected to happen**:

Normal level of logging.

**How to reproduce it (as minimally and precisely as possible)**:

Just deploy a calico-enabled cluster (I tried with kubenet but I suppose it can be reproduced on AzureCNI clusters too).

**Anything else we need to know?**:

This fixes it:

```bash
k apply -f - <<EOF
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bgppeers.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: BGPPeer
    plural: bgppeers
    singular: bgppeer
EOF
```
The error in the logs goes away (but still, it logs every 10s because of #925 ).

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.0 and 1.13.5
- Size of cluster (how many worker nodes are in the cluster?): 2 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by sauryadas** [comment]
@feiskyer  is looking into this.

**Comment by feiskyer** [comment]
Confirmed the issue, and it would be fixed in next AKS release.
