### ISSUE TITLE
VMSS scaling created node didn't get updated credential

### ISSUE THREAD

**Issue by karataliu** [Azure/AKS#1043]
1. Create a VMSS cluster
2. Use 'az aks update-credentails' to set new credential
3. Scale VMSS node
4. The new created node still has old credential in '/etc/kuberentes/azure.json'

**Comment by jluk** [comment]
@karataliu could you please give this a retry? We pushed a fix for this and it should be resolved. Closing as a result but please re-open if it is still hitting you.
