### ISSUE TITLE
AKS limited egress preview - additional URLs required

### ISSUE THREAD

**Issue by lenisha** [Azure/AKS#1044]
*What happened**:
Provisioning AKS in custom VNet force tunneled thru FW and need precise list of urls to be whitelisted

**What you expected to happen**:
Expected list of urls posted at https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic to cover everything

**How to reproduce it (as minimally and precisely as possible)**:
Create cluster with firewalled access to internet

Following URLs were used by cluster provisioning in addition to listed in docs:
api.snapcraft.io    :443 :80
*.cdn.mscr.io       :443
ntp.ubuntu.com  :123
*.hcp.eastus2.azmk8s.io   :443 :9000 :22  
*.tun.eastus2.azmk8s.io   :443 :9000 :22

**Comment by sauryadas** [comment]
One customer has reported that docker.io is required as well

The specific error they see in the tunnelfront pod is:
  Warning  Failed     25m                  kubelet, aks-cgprodpool-26424830-0  Failed to pull image "docker.io/deis/hcp-tunnel-front:v1.9.2-v4.0.7": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/deis/hcp-tunnel-front/manifests/v1.9.2-v4.0.7: Get https://auth.docker.io/token?scope=repository%3Adeis%2Fhcp-tunnel-front%3Apull&service=registry.docker.io: read tcp 172.20.44.4:59950->34.232.31.24:443: read: connection reset by peer

**Comment by jnoller** [comment]
Pinned issue. AKS is aware of the URL changes for the egress filtering feature preview.

**Comment by gossion** [comment]
thanks @lenisha for reporting the issue. let us whitelist these endpoints.
@sauryadas , it is wired to see the error `Failed to pull image "docker.io/deis/hcp-tunnel-front:v1.9.2-v4.0.7"`, tunnel-front should be in ACR `aksrepos.azurecr.io` rather than docker.io. which region does customer see the issue? let me try to reproduce and see why this error happened.

**Comment by amandadebler** [comment]
The change to requiring additional ports for Tunnelfront should have been announced in the AKS Changelog. Having only newer clusters appear to be created without problems, but then to have i/o issues turn up once developers tried using them, and previously deployed clusters continue working without problems made this particularly difficult to trace - the Azure app platform team at my company does not have access to the third-party firewall and has to request logs per subnet and per time window from the IT Security team.

**Comment by patpicos** [comment]
Azure firewall Application rule collections do not support UDP and TCP ports, only http/https/mssql.

How do we restrict:
ntp.ubuntu.com    **UDP:123**
*.hcp.<location>.azmk8s.io    HTTPS:443, **TCP:22, TCP:9000**
*.tun.<location>.azmk8s.io    HTTPS:443, **TCP:22, TCP:9000**

**Comment by sauryadas** [comment]
@patpicos  
you cannot restrict 
ntp.ubuntu.com UDP:123
*.hcp..azmk8s.io HTTPS:443, TCP:22, TCP:9000
*.tun..azmk8s.io HTTPS:443, TCP:22, TCP:9000
ntp is required for time sync, and the other 2 to connect to the api server

Feature is GA now.
https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic

**Comment by mkosieradzki** [comment]
> you cannot restrict
ntp.ubuntu.com UDP:123

@sauryadas nope. VMICTimeSync is the answer - https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync -> VMICTimeSync

**Comment by TomGeske** [comment]
We recently published a new version of our egress doc [here](https://docs.microsoft.com/en-us/azure/aks/egress) to cover those questions. 

I'm closing this one for now. Keep commenting if you have further questions.
