### ISSUE TITLE
Azure Aks: Windows Authentication using GMSA

### ISSUE THREAD

**Issue by kkopuru** [Azure/AKS#1048]
We are trying to verify windows authentication using GMSA with AKS.

"https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/"

Since the feature in alpha state, it is disabled by default. 

Did anyone try this with AKS? How to enable feature gates with AKS?

**Comment by andyzhangx** [comment]
it's not possible to enable feature gates on AKS, not supported

**Comment by IsharaPannila** [comment]
What do you mean by feature gates not supported by AKS. Is it only for this feature?
Cant we add feature gates as following?
https://github.com/Azure/aks-engine/blob/master/examples/feature-gates/kubernetes-featuresgates.json

**Comment by andyzhangx** [comment]
> What do you mean by feature gates not supported by AKS. Is it only for this feature?
> Cant we add feature gates as following?
> https://github.com/Azure/aks-engine/blob/master/examples/feature-gates/kubernetes-featuresgates.json

We cannot add any feature gates in AKS, while aks-engine supports feature gates customization.

**Comment by kkopuru** [comment]
Thanks for the confirmation.

Can we use docker compose with AKS? There is way to pass credential spec with Docker Compose, we already tested this Swarm.

**Comment by jnoller** [comment]
Closing as invalid, AKS and AKS-Engine while sharing underlying components do not expose the same functionality. Additionally, Alpha/Beta features within Kubernetes are not supported on AKS until such time as they are GA.

**Comment by MikkelHegn** [comment]
https://docs.microsoft.com/en-us//azure/aks/windows-node-limitations#aks-limitations-for-windows-server-node-pools

> Group managed service accounts (gMSA) support when the Windows Server nodes aren't joined to an Active Directory domain is not currently available in AKS.
The open-source, upstream aks-engine project does currently provide gMSA support if you need to use this feature.
