### ISSUE TITLE
Tunnelfront egress communication to API Servers - Provide IP Range to be whitelisted in Azure Firewall

### ISSUE THREAD

**Issue by neerajkrshukla** [Azure/AKS#1049]
**What happened**:
When Provisioning AKS in custom VNet, the tunnelfront connection (TCP Port 22/9000) to AKS API Server  thru Firewall (Egress Preview) needs precise list/CIDR of IP addresses to be whitelisted as Firewall. 

**What you expected to happen**:
In Firewall network rule collections, we should specifically provide the IP Range of AKS API Servers as URLs can be provided only for application rule collection which provides HTTP/HTTPS support and not TCP traffic to port 22/9000 which is required for tunnel communication with API Server endpoints. Allowing Ports 22/9000 to all IP addresses will be too open and will pose security constraint for enterprise.

**How to reproduce it (as minimally and precisely as possible)**:
Create cluster with firewalled access to internet (using egress preview feature described at https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic) and allow TCP port 22/9000 in Firewall's Network rule collection.

When we create AKS Cluster and restrict egress traffic using firewall and setup UDR to use Azure firewall as next hop, we need to open number of URLs for HTTP/HTTPS communication which is listed at https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic however port 22/9000 is required for communication to AKS API Server endpoint which cannot be opened in Application Rules of Firewall (since Application rules allow only http/https). The URLs/FQDNs are provided in the documentation for AKS API Server endpoints which needs to be opened but we need Public IP address range of these endpoints so that required ports can be only for API Server IP Addresses and not to all networks. (Related Issue raised in Documentation section as well .. see this https://github.com/MicrosoftDocs/azure-docs/issues/32234).

**Comment by jnoller** [comment]
@sauryadas ^ private cluster req

**Comment by amandadebler** [comment]
We have the same requirement, as our firewall is also IP and not FQDN-based. As in likely many large corporate IT departments, my team had absolutely no control over that choice.

A Microsoft-managed Service Endpoint for the AKS masters would be absolutely ideal - those are working well for us for other Azure services (Cosmos DB, Key Vault, SQL..)

**Comment by sauryadas** [comment]
after you create a cluster you can update the network rule to the api server endpoint by getting it through $kubectl get endpoints

**Comment by neerajkrshukla** [comment]
@sauryadas - this can be updated later on with correct IP but I raised a support request for this and support engineer confirmed that the IP assigned is not persistent and may change in updates.this can be problem when we wish to use it for production and also in cases when we are creating clusters first time with firewall already enforced.

Also we are opening port 443 for all communications (when we try restricting to only FQDNs published in documentation, metrics server and dashboard pods were failing) so even we call restricted egress but virtually we are allowing all outbound https traffic.

**Comment by sauryadas** [comment]
it is possible that the api server ip might change. i forgot to mention that.
when we try restricting to only FQDNs published in documentation, metrics server and dashboard pods were failing <- do you have a support case on this?

**Comment by neerajkrshukla** [comment]
the project for which I was working on this is not completed with solution that we will have Ports 22/9000 and 443 open for all egress traffic so I would leave it to admins/maintainers to choose whether to close this. however for community help I can provide inputs here. 

@sauryadas - the support request id is 119061123001789

**Comment by sauryadas** [comment]
@neerajkrshukla i followed up with the case owner and it looks like opening up port 443 fixed your crashing pods. 443 is required for the node pool to take to the api server end point.

Can i close this issue?

**Comment by neerajkrshukla** [comment]
Sure Saurya... you can close this and thanks for your valuable insights and quick turnarounds..
