### ISSUE TITLE
Consider support for Local Persistent Storage PVCs

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#105]
https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume

It would be great to expose both os and temporary (/dev/sdb1) drives and have them labeled accordingly

**Comment by andyzhangx** [comment]
This feature is still in alpha, I don't think we should open the feature gate for this feature in AKS.

**Comment by AceHack** [comment]
Is there any way to let specific AKS clusters to decide to open a feature gate or have two different AKS offerings, one with alpha features and one without them?

**Comment by slack** [comment]
AKS will only support beta and stable Kubernetes features.

There is some demand for alpha and -rc, -beta support, but we won't investigate this until late in the year at the earliest. If we do let folks provision experimental clusters, support would only be best effort.

If you need to dive into deep customization, I'd recommend you look at `acs-engine`.

**Comment by AceHack** [comment]
This is beta now, will you add support?

**Comment by adinunzio84** [comment]
Now stable in K8s 1.14. We'd like to see this feature (os / ephemeral drive distinction) as well.

**Comment by mingtwan** [comment]
any update?

**Comment by andyzhangx** [comment]
beta and stable k8s feature is enabled by default on AKS, so it's already supported on AKS:
https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta/
