### ISSUE TITLE
AKS API server support of standard load balancer (not user deployed services)

### ISSUE THREAD

**Issue by itszakko** [Azure/AKS#1052]
**What happened**:
When using the [Kubernetes Python API](https://github.com/kubernetes-client/python), after approximately 5 minutes of inactivity, the connection stops working. The packets are seemingly dropped on the other end. 

In the case of the Python API, this causes the request to block for 15 minutes until the Linux Kernel forces the socket closed with "Errno 110 Connection timed out". The other side is closing the connection but not sending a TCP `RST`, leaving the socket open on the client.

Under the hood the Python API uses a connection pool that reuses the TCP Connections using the standard HTTP Keep-Alive mechanism.

This causes issues with the out of the box configuration in applications such as [Airflow](https://github.com/apache/airflow) that use the Kubernetes Python API.

I would assume other Kubernetes client libraries would have a similar issue, but haven't investigated them myself.

**What you expected to happen**:
The connection is closed properly by the server instead of packets being dropped. That way clients can fail fast and reestablish the connection.

If this is unavoidable, the exact values of when the control plane starts dropping packets should documented clearly somewhere so the Kubernetes Client Libraries and application developers can adjust their defaults or provide AKS-specific configuration.

**How to reproduce it (as minimally and precisely as possible)**:
Run this inside of the cluster, I'm using a `python:3.7.3-stretch` container.

```python
import time
import logging
from kubernetes import config, client

logging.basicConfig(
    format='%(asctime)s %(levelname)-8s %(message)s',
    level = logging.DEBUG)

config.load_incluster_config()
v1 = client.CoreV1Api()

logging.info('Calling 1st time')
v1.list_namespaced_pod('default')
logging.info('Sleeping 5 minutes')
time.sleep(300)
logging.info('Calling 2nd time')

# this call will timeout after 15 minutes
v1.list_namespaced_pod('default')
logging.info('OK')
```

**Environment**:
- Kubernetes version: v1.12.6
- Size of cluster: 1

**Comment by alanjcastonguay** [comment]
This becomes especially noticeable when using watches, as the connection seems to remain open but stops receiving events. That connection is expected to be idle for many minutes between events. I've noticed it with the python client not inside and outside the cluster, connecting to the public master FQDN.

**Comment by digeler** [comment]
The basic nlb that uses the API has 4 Min idle timeout.
This is going to be changed in near future.
You might want to use init container with your deployment 

Something like this:
initContainers:
        - name: "sysctl"
          image: "busybox:latest"
          resources:
            limits:
              cpu: "10m"
              memory: "8Mi"
            requests:
              cpu: "10m"
              memory: "8Mi"
          securityContext:
            privileged: true
          command:
            - "/bin/sh"
            - "-c"
            - |
              set -o errexit
              set -o xtrace
 
              sysctl -w net.ipv4.tcp_keepalive_time=180
              sysctl -w net.ipv4.tcp_keepalive_intvl=180
              sysctl -w net.ipv4.tcp_keepalive_probes=4

Hope it helps

**Comment by jnoller** [comment]
This is directly related to the use of Azure Basic Load Balancers for AKS clusters. https://github.com/Azure/AKS/issues/643 and is on the public roadmap: https://github.com/Azure/AKS/projects/1

**Comment by ubercow** [comment]
@jnoller Thanks for your reply. Glad to see the team is aware and has plans to remedy it.

I'll follow along at #643

**Comment by jluk** [comment]
Re-opening as this is separate from customers being able to deploy standard load balancers for their own services.

**Comment by asubmani** [comment]
when this becomes GA; would this require a re-deployment of the AKS cluster? I would expect this to be an implicit change.
In case re-deployment is required, would enabling this need new commands in az cli/Terraform?

**Comment by itszakko** [comment]
Hi, is this still being worked on? It's still something we're having to hack around.

**Comment by maganaluis** [comment]
I can confirm this is an issue on AKS, I ran @itszakko job on AWS EKS and there is no timeout. This affects Airflow on K8S and Kubeflow deployments. 

Azure Logs: https://github.com/maganaluis/k8s-api-job/blob/master/azure-aks.log
AWS EKS: https://github.com/maganaluis/k8s-api-job/blob/master/aws-eks.log

**Comment by thomasfrederikhoeck** [comment]
@itszakko is your workaround simply querying it every 3rd minute or so?

@jluk is this fixed with the GA?

**Comment by shooker** [comment]
I believe this is the same issue highlighted here: https://github.com/Azure/AKS/issues/1877

**Comment by thomasfrederikhoeck** [comment]
I believe you are right @shooker

**Comment by thomasfrederikhoeck** [comment]
Do you know if a fix is under-way @shooker ?

**Comment by thomasfrederikhoeck** [comment]
I note that you are the signee @jluk . Do you have any information about any fix for this? 😄

**Comment by thomasfrederikhoeck** [comment]
I think this is fixed now.
