### ISSUE TITLE
AKS Upgrade should ensure that enough IPs are available before upgrading

### ISSUE THREAD

**Issue by LennartHaggkvistHM** [Azure/AKS#1053]
**What happened**:
Cluster got in invalid state after upgrade failed due to too few available IP adresses

**What you expected to happen**:
AKS should not try to upgrade if there is not enough available IPs to create the additional node.

**How to reproduce it (as minimally and precisely as possible)**:
Create subnet with less available IPs that is required for another node.

**Anything else we need to know?**:
Had a support case for this. Was asked to create feedback on it.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.8
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): 
- Others:

**Comment by Senai-T** [comment]
totally understandable, the general consensus is that you should either use basic networking (kubenet) which will have a different CIDR distribution than the VNET they reside in (essentially your nodes and pods won't be on the same CIDR) thus freeing up a lot more address but at the cost of some cloud features or to use advanced networking with some planning that includes extra IP address to be dynamically allocated to a node during the upgrade process.
https://youtu.be/4RgZDu8LQKs

**Comment by jwall2000** [comment]
I think this is feedback / enhancement idea on how an upgrade process could work. Enough available IP addresses for an extra node is maybe a sanity check that could be conducted by the AKS upgrade process as a prerequisite / test before actually starting the upgrade as extra protection and fail the upgrade prematurely without touching the cluster.

**Comment by jnoller** [comment]
@jwall2000 is correct - in fact this is something that has already been patched/fixed in later AKS versions. We double-check available quota, subnet space and more. If you encounter this issue on a new cluster, please reopen this

**Comment by LennartHaggkvistHM** [comment]
@jnoller - what do you mean with "later AKS versions"? Was it fixed but not released to all AKS deployments/clusters or does it actually matter which version of AKS and/or Azure AKS "backend" that is used?

Which version was it fixed in?
