### ISSUE TITLE
Unauthorised access to Kubelet API

### ISSUE THREAD

**Issue by cwebbtw** [Azure/AKS#1054]
**What happened**:

Kubelet API seems to be unauthorised even to pods that have a service account with the cluster role binding `system:kubelet-api-admin`.

This is restricting the use of utilities like *splunk-connect-for-kubernetes*. 

See https://github.com/splunk/splunk-connect-for-kubernetes

**What you expected to happen**:

Expect that pods should be able to authorise with the kubelet API if they have a service account that has an appropriate binding.

**How to reproduce it (as minimally and precisely as possible)**:

Create a pod with a service account that should have access to the kubelet API and on the pod, run a HTTPS request against the node on port 10250.

**Anything else we need to know?**:

*RBAC enabled* - this is important

**Environment**:
Have reproduced this on multiple machines

- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Senai-T** [comment]
is the pod deployed on the kube-system namespace?

**Comment by cwebbtw** [comment]
I wasn't aware that the pod needed to be deployed to the `kube-system` namespace as well as the right role permissions to authorize against the Kubelet API. Can you confirm this is the case?

**Comment by Senai-T** [comment]
typically, that would be the case but at this point it's conjecture as I have never setup Splunk on K8s and i can't in good faith recommend you deploy something to the kube-system namespace without seen your entire infrastructure and running through scenarios. The link in your post recommends using a helm chart to deploy, helm has the necessary permissions to automate all of the process and permissions and its generally "safer" for complex setups. First thing i'd do is ask around on the splunk threads for more specific inputs, as this most likely a splunk issue than AKS one, if that fails then I would definitely open a support ticket with Azure as they can use internal tools to dig deep into the control plane and see whats what.

**Comment by cwebbtw** [comment]
Let's not focus on splunk but moreover the issue that with a pod signed a service account with a role binding mapping a `system:kubelet-api-admin` role, a call to the kubelet API on port 10250 returns 401. Has this method of authorisation been disabled? The port used to be fairly vulnerable to misuse but I can't locate any documentation around this on AKS. The mention of the splunk utility is an example of a project that attempts to obtain data directly from kubelet calls.

**Comment by alanjcastonguay** [comment]
The Datadog agent running in DaemonSet pods also touches the kubelet of the AKS node it's running on; maybe this RBAC model is appropriate for Splunk too? 

https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/manifests/cluster-agent/rbac/rbac-agent.yaml

**Comment by cwebbtw** [comment]
I will look at whether the datadog agent is communicating on port 10250 on AKS and get back to you.

**Comment by LudoNieuw** [comment]
Has this issue been investigated further and what were the results of that investigation?
