### ISSUE TITLE
RBAC on AKS: kubectl keeps asking for login every command

### ISSUE THREAD

**Issue by mschuurmans** [Azure/AKS#1057]
**What happened**:
We're on AKS with RBAC enabled. Executing any kubectl/helm command that connects to the k8s cluster, i have to reauthenticate. Output:

~~~
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXX to authenticate.
~~~
This succeeds but then when i execute the next kubectl command i have to reauthenticate again.

**What you expected to happen**:
Authenticate and use that token for more than one command.

**How to reproduce it (as minimally and precisely as possible)**:

[Get credentials](https://docs.microsoft.com/nl-nl/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials) and then execute any kubectl command.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

~~~
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
~~~

- Size of cluster (how many worker nodes are in the cluster?)
3

**Comment by mschuurmans** [comment]
After digging deeper found that there was a `config.lock`. When removed this issue went away.

**Comment by esunder** [comment]
@mschuurmans what do you mean there was a config.lock? What exactly did you remove?

Thanks!

**Comment by mschuurmans** [comment]
@esunder There was a file in my `~/.kube/` folder called `config.lock` which caused that the config file was not updated correctly after removing it `rm ~/.kube/config.lock` the issue was resolved.

**Comment by akramwaseem** [comment]
I dont see any config lock under .kube folder, but I keep seen this when applying helm permissions or running kubectl commands.
@mschuurmans @esunder
