### ISSUE TITLE
Unresponsive readiness checks and external service endpoints for clusters with over 4 nodes.

### ISSUE THREAD

**Issue by sbrierly** [Azure/AKS#1059]
**What happened**:
New AKS clusters I create (both k8s versions 1.12 & 1.13), I add a service and a deployment with a single replica of a Python flask app running behind gunicorn with a readiness check that simply responds 200 "okay."  If I scale to 1-4 nodes, the service external IP endpoint responds quickly when hitting the HTTP readiness check described above.  Also, I do not observe any readiness check timeouts.  If I scale beyond 4 nodes, 5 or higher, the service external IP endpoint takes many seconds to respond or times out, and I frequently see the readiness probe timing out.  If I scale back down to 4 or less nodes, the slowness goes away and the expected performance returns to the service endpoint and the readiness probe timeouts are no longer observed.

**What you expected to happen**:
To be able to scale above 4 nodes without adding significant deployment breaking network latencies.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a new cluster with the default VM size, no RBAC, etc.
- Add any necessary docker repo keys.
- Deploy a service.
- Deploy a deployment for that service with a single replica of a web app and a readiness probe.  The check interval for us is 15 seconds for this test.
- Hit the readiness probe URL from the external service IP.  Should observe quick single digit millisecond response times.
- Scale to above 4 nodes.
- Observe frequent readiness probe timeouts in the k8s dashboard.
- Hit the readiness probe URL from the external service IP.  Should observe multiple second latencies and timeouts.
- Scale back to 4 nodes or below, and the behavior reverts.

**Anything else we need to know?**:

**Environment**:
- North Europe region
- Kubernetes version (1.12 or 1.13):
- Size of cluster (varies)
- General description of workloads in the cluster (e.g. HTTP microservices Python flask/gunicorn)

EDIT: This seems to be related to the externalTrafficPolicy service setting?  If I set it to Local, the latency goes away, and reappears if I set it to Cluster, the default.

**Comment by jnoller** [comment]
@JunSun17 ^^

**Comment by salmicrosoft** [comment]
Maybe related - we're getting CRITICAL WORKER TIMEOUT in our gunicorn/django app even when it's barely doing anything. This just started coming up with no change. We have another cluster that is identical and it's not problematic. After scaling the nodes to 0 and back to 5 the problem went away for about 30 minutes. After this observation and reading several other threads on gunicorn's github, we're starting to think it has to do with the networking (and our k8s configuration is all out of the box)

Django 2.1.5
gunicorn 19.8.1
gevent 1.2.2
AKS 1.15.7 with 5 Nodes (standard B2's - 2 vcores and 2GB memory)
3 pods/docker containers, each of which has:

    spec:
      containers:
        - name: web-container
          command: ["newrelic-admin"]
          args: [
              "run-program",
              "gunicorn",
              "--limit-request-field_size=16380", # limit also specified in nginx
              "--workers=3", # (2 x vcpu) + 1. vcpu < limit defined in resources
              "-k=gevent",
              "-b=0.0.0.0:8000",
              "ourapp.wsgi",
              "--timeout 60",
              "--log-level=debug",
            ]
          resources:
            requests:
              memory: "200Mi"
              cpu: "250m"
            limits:
              memory: "3000Mi"
              cpu: "2000m"

**Comment by palma21** [comment]
This should not be a wide issue, it's very likely a specific configuration case. It's easier for us to take a look at your specific cluster over a support case. Feel free to drop the ticket number here.
