### ISSUE TITLE
error: You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#106]
I am unable to use kubectl on a cluster I just created, I had just deleted the cluster because of a previous issue, now with the new issue I can't login to a brand new cluster!!

PS D:\Kubernetes\tools>az aks get-credentials --name aks-use-arch-dev --resource-group rgp-use-arch-aks
Merged "aks-use-arch-dev" as current context in C:\Users\astainba\.kube\config
PS D:\Kubernetes\tools> kubectl get all
error: You must be logged in to the server (Unauthorized)
error: You must be logged in to the server (Unauthorized)
error: You must be logged in to the server (Unauthorized)
error: You must be logged in to the server (Unauthorized)
error: You must be logged in to the server (Unauthorized)
error: You must be logged in to the server (Unauthorized)
error: You must be logged in to the server (Unauthorized)
error: You must be logged in to the server (Unauthorized)
error: You must be logged in to the server (Unauthorized)
error: You must be logged in to the server (Unauthorized)
error: You must be logged in to the server (Unauthorized)
error: You must be logged in to the server (Unauthorized)
error: You must be logged in to the server (Unauthorized)

**Comment by AceHack** [comment]
See https://github.com/Azure/AKS/issues/104 for my previous issue

**Comment by AceHack** [comment]
I was able to fix this issue by deleting the C:\Users\astainba\.kube folder and running the above again.

**Comment by SteffiKeranJ** [comment]
How is this same issue fixed in Linux machine?

**Comment by seanknox** [comment]
Closing due inactivity. Feel free to re-open if still an issue.
