### ISSUE TITLE
Multiple Availability Zone Support (Multi-AZ)

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#1060]
Multi-AZ support within AKS tracking issue, in plan for 2019 delivery.

This feature enables a create-time cluster property to choose 1-3 zones for a cluster to be deployed into. The region chosen must support AKS and zones. The feature when turned on offers increased availability of the control plane and worker nodes within AKS. New nodes created will be best effort balanced across zones.

**Comment by jnoller** [comment]
Initial AZ Support for AKS clusters is in public preview: https://docs.microsoft.com/en-us/azure/aks/availability-zones

This issue will remain open until all work in scope is done

**Comment by roger-beathard** [comment]
Is there any plans to for Multi-AZ support for the master nodes?

**Comment by chaos-panda** [comment]
Is there any plan already having this GA?

**Comment by jluk** [comment]
This is expected to GA in Q4CY19. You can also expect 5 more regions to be supported in that same quarter to match the 10 that are available as of today, 9/13/2019.

**Comment by jluk** [comment]
@roger-beathard if you enable zones at cluster creation time, your control plane will also be spread across zones automatically. The best way to address the point of concern which I assume is control plane availability is to work off of the provided SLO defined below. Hope this helps.

https://docs.microsoft.com/en-us/azure/aks/faq#does-aks-offer-a-service-level-agreement

**Comment by alexeldeib** [comment]
>1. Agent nodes are zone aware, manual failover of customer clusters across zones.
>2. AKS offers automatic failover of customer clusters

@jnoller what is manual failover in scenario 1? Customer gets a ping, can click something in portal to manually migrate nodes from Zone 1 to zone 2 during AZ outage? 

@jluk that would seem to indicate AKS uses multi-master H, spread across AZ. Can you confirm that? There are at least two outstanding issues on the subject:

https://github.com/Azure/AKS/issues/852
https://github.com/Azure/AKS/issues/198#issuecomment-408779837

**Comment by jluk** [comment]
@alexeldeib the original post was a bit confusing with outdated information, so simplified a bit.

To help clarify (by exposing some implementation details) - our implementation of AZ support relies on VMSS zones. If a node dies due to zone failures the pods on nodes in that failed zone will get rescheduled by k8s to healthy nodes which reside in the healthy zone, utilizing zones for your cluster ensures the nodes that exist in your fleet are there should that time come. There is no customer effort required to receive the automatic pod rescheduling, other than configuring your pods/node within k8s to schedule properly.

If you have the cluster autoscaler enabled as well, then new nodes will be attempted to be provisioned until you meet the goal state setup for the autoscaler. If a zone is down then node creation attempts will succeed on the healthy zone you have providing you only nodes in healthy zones. More info is over at aka.ms/aks/zones.

**Comment by alexeldeib** [comment]
Thanks for the clarification, what you described is how I would expect the service to work. 

Still curious about the Q for masters :)

**Comment by DreamRivulet** [comment]
Is multi-zone master supported now?

**Comment by marcoboffi** [comment]
> There is no customer effort required to receive the automatic pod rescheduling, other than configuring your pods/node within k8s to schedule properly.

just a clarification..if pod has got some volume mounted (example dynamic pvc with azure disk ZRS), are volumes remounted after pod switch?

Regards

**Comment by jluk** [comment]
This feature is now generally available, please visit aka.ms/aks/zones for more information.

@marcoboffi you will need to specify the pod deployment to request for a volume. Details are in the below kubernetes documentation about persistent volumes and claims.

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#lifecycle-of-a-volume-and-claim

**Comment by DreamRivulet** [comment]
May I know when availability zone will be available in South Africa? Is there an ETA for this ?

**Comment by jluk** [comment]
@DreamRivulet currently Azure doesn't offer Zones in the South Africa region yet, I would advise tuning into the Azure Updates blog for when that would be available or checking in on the general IaaS zones document. https://docs.microsoft.com/en-us/azure/availability-zones/az-overview

When Zones are available for general compute in Azure, you can expect AKS to follow up with support shortly afterwards.

**Comment by jcamu** [comment]
This feature address the issue of worker nodes failure but what about master failure?

Moreover, if i'm not wrong this feature is not available for AKS cluster using internal load balancer with nginx ingress for private network.
So how to ensure HA?

**Comment by AceHack** [comment]
@jluk you did not answer @marcoboffi’s question.  If I provision a stateful set using ZRS with PVC. Can those pods with attached storage switch regions since it's ZRS.  Of course LRS would be unable to do this.  This would be a killer feature over EKS.

**Comment by mohanrao** [comment]
Hi,

With this multi-AZ support does AKS install multiple masters in multiple AZ's?
