### ISSUE TITLE
Support for custom log options

### ISSUE THREAD

**Issue by boarder981** [Azure/AKS#1062]
**What happened**:

Noticed container logs were getting large on my AKS cluster.  Viewed `/etc/docker/daemon.json` on one of the nodes.  It looks like the defaults are:

```
{
  "live-restore": true,
  "log-driver": "json-file",
  "log-opts":  {
     "max-size": "50m",
     "max-file": "5"
  }
}
```

**What you expected to happen**:

I would like the ability to set custom log options during `aks create...` and/or a separate CLI command that would do the same.  If this is currently possible, please let me know.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy an app with verbose logging and watch the log files grow to 50MB, then get rotated out.  Eventually the container logs will grow to 250MB (50MB x 5 files).  You should see the logs under `/var/lib/docker/containers/<container-id>`.  Of course, this may take hours/days/weeks depending on your app.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.7
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster: basic web app testing

**Comment by bitsofinfo** [comment]
would like this as well

**Comment by bitsofinfo** [comment]
not stale

**Comment by san360** [comment]
Any updates?

**Comment by palma21** [comment]
containerLogMaxSize and containerLogMaxFiles will be made available on the December API via #323 

This will work with containerd based clusters. We're studying if this can be done for docker based clusters as well.

**Comment by vishnujanardhanan** [comment]
@bowang-666 @palma21 Hi, is this feature available for docker based clusters? If so which preview feature contains it? can you please help?

az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService')].{Name:name,State:properties.state}"

**Comment by malthe** [comment]
@vishnujanardhanan seems like this would be enabled via "Microsoft.ContainerService/useContainerd".

**Comment by vishnujanardhanan** [comment]
@palma21 Created a cluster with k8s 1.19.7 and still dont find containerLogMaxFiles and containerLogMaxSize in az aks show. api doesnt show either. Should i enable any preview features to achieve this ?

**Comment by m1o1** [comment]
If this feature is added, can the path be configurable too? I'd like to get stdout/stderr logs written to a different drive from the one the container runtime is using for images / writable layer / etc.

**Comment by QaiserAli** [comment]
I'm also looking for this feature as our container logs are overloading the node disk space. It would be nice if we can remove the container logs after a period.

**Comment by vishnujanardhanan** [comment]
@bowang-666 do you have info on when this will be available in beta? We are really struggling with this for a long time.

**Comment by ohadschn** [comment]
For reference, you can find the new properties here:
https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters?tabs=json
>  "containerLogMaxSizeMB": "integer"
>  "containerLogMaxFiles": "integer"
