### ISSUE TITLE
Intermittent / Random node communication issue - iptables conflicts 

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#1068]
AKS Engineering has identified an bug that can cause networking issues with customer cluster that are running the `kube-svc-redirect` deployment and two (2) or more of the following:

* Azure network policy enabled clusters
* Calico CNI enabled clusters 
* Azure Active Directory Pod Identity

Specifically, if customers are running `kube-svc-redirect` and one or more pods that attempt to update iptables rules. Customers may see issues with inter-pod communication and issues accessing NodePorts or other pod endpoints. 

**This issue is random and intermittent**

If you encounter an issue where one pod/deployment in a cluster can not be communicated with, you can see if you are impacted by running the following command on the node:

```
iptables -w -t nat -L "PREROUTING"
```

**If you are impacted you will see duplicate aks-hcp-custom-svc entries**:

Example output:
```
	iptables -w -t nat -L "PREROUTING"
	Chain PREROUTING (policy ACCEPT)
	target     prot opt source               destination         
	aks-hcp-custom-svc  all  --  anywhere             anywhere            
	cali-PREROUTING  all  --  anywhere             anywhere             /* cali:6gwbT8clXdHdC1b1 */
	aad-metadata  all  --  anywhere             anywhere            
	KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */
	aks-hcp-custom-svc  all  --  anywhere             anywhere            
```

In order to fix this issue while AKS rolls out the full fix, run this on the impacted node:

```
iptables -w -t nat -D "PREROUTING" -j aks-hcp-custom-svc
```

AKS engineering is root-causing the issue and preparing a fix.

**Comment by jeremych1000** [comment]
Can we get slightly more information on this? What are some of the symptoms?

Our client has no access to the underlying AKS nodes - how else can we debug this?
