### ISSUE TITLE
Resetting credentials puts cluster in failed mode

### ISSUE THREAD

**Issue by vpopescu** [Azure/AKS#1069]
**What happened**:
I am trying to set up a script to update a cluster with SP credentials that may have changed. When I run "az aks update-credentials" I get:

```
Deployment failed. Correlation ID: 2332f813-ba8f-4080-a4a1-df27dfb64bf6. Operation failed with status: 200. Details: Resource state Failed
```
and the cluster is in failed mode.

**What you expected to happen**:
The cluster should be updated with the new credentials.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a service principal
2. Create a cluster with the created SP principal
3. reset the service principal via 'az ad sp credential reset' (which returns new credentials)
4. Update the cluster with the new credentials via 'az aks update-credentials'
5. Get message above (I am not sure if it's 100% reproducible, may be a timing issue involed?)

**Anything else we need to know?**:

```json
"properties": {
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"CreateRoleAssignmentError\",\"message\":\"\"}]}}"
    },
```

**Environment**:
- Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- az-cli: 2.0.66
- Cluster size: 3 VMs (empty). Nothing running on the nodes, just experimenting with devops script.

**Comment by jnoller** [comment]
Hotfix for this issue is being prepared for all regions.

**Comment by scottymcraig** [comment]
This is still happening.  However, my error is different:

`Deployment failed. Correlation ID: *****. Creating the customer provisioned DNS Zone failed. Details: autorest/azure: Service returned an error. Status=412 Code="PreconditionFailed" Message="The Record set ***** exists already and hence cannot be created again."`

**Comment by oak13** [comment]
> Hotfix for this issue is being prepared for all regions.

Hi, 

Has the hotfix been prepared?

Thank you

**Comment by TomGeske** [comment]
This one should be fixed. 

I'm closing this one for now. Keep commenting if you have further questions.
