### ISSUE TITLE
az aks install-cli installs a kubectl version inappropriate for the AKS server version

### ISSUE THREAD

**Issue by victornoel** [Azure/AKS#1072]
**What happened**:

```
# kubectl get ingresses.extensions
test-ingress                                             test.xxx.com               80, 443   6m9s
# kubectl describe ingresses.extensions 
Error from server (NotFound): the server could not find the requested resource
```

**What you expected to happen**:

That `kubectl describe ingresses.extensions` shows me the ingresses description.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

- It is an AKS cluster created on June, 20.
- I enabled node pools, monitoring, virtual node and AD integration
- I ran the commands while being connected using credentials retrieved with the `--admin` flag.

**Environment**:
- Kubernetes version: 1.12.8
- aks-engine version: 0.35.4

**Comment by victornoel** [comment]
For the record, as someone on Slack recommended, here is the version of kubectl I'm using:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

kubectl was installed with `az aks install-cli`, I am expecting it to install something correct…

**Comment by gun1x** [comment]
I see the same issue on AWS:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.10-gke.5", GitCommit:"5aa3a95d828fe45aab3611dfc4ebdc0341fe1507", GitTreeState:"clean", BuildDate:"2019-05-29T17:25:39Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by victornoel** [comment]
I have updated the title to better reflect the problem.

A workaround is to explicit the version number when calling `az aks install-cli` but I don't consider that a solution because the whole point (at least for me) of using `az aks install-cli` is to get a binary coherent with AKS.
