### ISSUE TITLE
Create AKS Cluster with Dashboard Disabled by default

### ISSUE THREAD

**Issue by rudolphjacksonm** [Azure/AKS#1074]
Hello,

I'd like to propose a new feature for AKS. Currently whenever a cluster is created (either via the Portal, CLI, or Terraform) the dashboard is always enabled. It would be preferable to disable the dashboard via a flag in the CLI. This could then be replicated by the good folks working on the azurerm provider. Something like this would be ideal:

```
az aks create --name 'my-aks-cluster' \
 --resource-group 'my-resource-group' \
 --no-dashboard
```
This matches some of the existing flags like `--no-ssh-key` and `--no-wait`. Alternatively the flag could be `--disable-dashboard`, which would then have a similar wording to `--disable-rbac`.

Either way, this would prevent us from having to then run a separate command after the cluster has already been created to disable the dashboard (see #786)

**Comment by neumanndaniel** [comment]
FWIW. Currently it is already possible to deploy an AKS cluster with the k8s dashboard disabled via Terraform or an ARM template.

-> https://www.danielstechblog.io/disable-the-kubernetes-dashboard-on-azure-kubernetes-service/

**Comment by jluk** [comment]
As mentioned previously you can manually disable the K8s dashboard, however we will be disabling the dashboard by default starting with clusters created on K8s 1.18 or greater.

Read more on the callout here: https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard

**Comment by jluk** [comment]
The K8s dashboard is disabled by default for any new clusters created on 1.18 or higher. Existing clusters upgrading versions will maintain the dashboard, but it can be manually disabled with these docs:

https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard#disable-the-kubernetes-dashboard
