### ISSUE TITLE
Outage in WestEurope?

### ISSUE THREAD

**Issue by MXClyde** [Azure/AKS#108]
Since this morning the AKS cluster is not reachable anymore using kubectl. Error:

_Unable to connect to the server: EOF_

After restart and/or redeployment of the agent node all pods became and remain unreachable.

**Comment by MXClyde** [comment]
Also changed agent count from 1 to 2, to no avail

**Comment by avaranovich** [comment]
same here, this is a result of the maintenance of the underlying VMs, to apply the security path to fix CPU vulnerability. The cluster did not restore with the correct state after reboot.

**Comment by MXClyde** [comment]
Looks like the Hosted Control Plane is down. I already filed a support ticket for it.

**Comment by MXClyde** [comment]
New clusters seem to work fine, so I am currently deleting and re-deploying mine.

**Comment by MXClyde** [comment]
Deleting and redeploying the cluster solved the problem. Not sure about root-cause. CPU-vulnerability patching seems likely.

**Comment by TallOrderDev** [comment]
These both sound like service principle issue. If the problem comes up again, please check that as well.
