### ISSUE TITLE
Validity of kubectl client certificate

### ISSUE THREAD

**Issue by zuehlke-dea** [Azure/AKS#1081]
I have some questions regarding the validity of the client certificates received by the az aks get-credentials command. We saw that we do not need to renew them for a while and so I checked the validity of the certificate with openssl:

Validity
            Not Before: May  3 00:15:52 2019 GMT
            Not After : May  2 00:15:52 2021 GMT

This looks like this certificate is valid for 2 years. Which means that all people which have received such a client certificate are able to access the cluster for 2 years. 

I know that there is a possibility wo use Azure AD, where the user has to login when using kubectl, but this is not required when I get the context with --admin. Some of our team left the company but as they had already admin access we can remove their tokens. 

So I would have the following questions: 

1. Is the assumption right that those certifcates could be used for 2 years to access the AKS?
2. If yes, is there any way to reduce this time? And is their anyway to revoke existing tokens without recreation of the AKS?

**Comment by alanjcastonguay** [comment]
See #397.

**Comment by zuehlke-dea** [comment]
Thank you. The first link was already helpful, but I still have the problem that I could not revoke the clusterAdmin certificates. I tried to use "resetADDprofile" but this does not change the credentials.

**Comment by zuehlke-dea** [comment]
But it seems I found the "solution" https://github.com/Azure/AKS/issues/756

**Comment by alanjcastonguay** [comment]
Yeah, this is a straight duplicate of #756 - close it as such?

**Comment by zuehlke-dea** [comment]
yes it is ok thank you
