### ISSUE TITLE
Windows Authentication  in AKS with or without gMSA ?

### ISSUE THREAD

**Issue by Farzad-Jalali** [Azure/AKS#1082]
Hi, 

I'm using the latest version of AKS and I need to communicate with some of my resource e.g. Microsoft dynamic web services in my network.

unfortunately, some of my other resources's security model are based on the active directory user.

is there any (working) feature that can help me in AKS?

**Comment by georgewen** [comment]
I am also trying to find out the answer, in the docs regarding aks limitation, it says the worker node has to be joined to the domain however it is not mentioned anywhere if it is possible to domain-join a worker node under AKS...

**Comment by JohnOnTheWeb** [comment]
FYI the documentation says that gMSA is not supported for AKS ate this time
and if necessary use ACE.

**Comment by georgewen** [comment]
thanks John,  can you advise what's ACE? @JohnOnTheWeb

**Comment by MikkelHegn** [comment]
ACE (Azure Container Engeine) now AKS-Engine: https://github.com/Azure/aks-engine.

Enables you to easily bootstrap K8 clusters in Azure. gMSAs are not supported in AKS: https://docs.microsoft.com/en-us//azure/aks/windows-node-limitations#aks-limitations-for-windows-server-node-pools

> Group managed service accounts (gMSA) support when the Windows Server nodes aren't joined to an Active Directory domain is not currently available in AKS.
The open-source, upstream aks-engine project does currently provide gMSA support if you need to use this feature.
