### ISSUE TITLE
Can an application be deployed through ARM template?

### ISSUE THREAD

**Issue by zhichuanxun** [Azure/AKS#1083]
**What happened**:

Well, I got a question that whether the application can be deployed through ARM template.

**What you expected to happen**:

 I know there is a "custom script" extension in VM resource that can help to implement an automatic deployment. I wonder if there exists some interface or some trick approaches in AKS(managedClusters) to achieve the function like "kubectl apply -f some.yaml"

**Comment by ams0** [comment]
You can use Terraform kubernetes or helm provider to apply a configuration right after cluster deployment, or have a look at Bedrock: https://github.com/Microsoft/bedrock/

**Comment by zhichuanxun** [comment]
> You can use Terraform kubernetes or helm provider to apply a configuration right after cluster deployment, or have a look at Bedrock: https://github.com/Microsoft/bedrock/

Thanks a lot for your kindly suggestions. However, I would like to know if there is a way to integrate the applying script like "helm install" into the ARM template. So we can publish the arm file into Azure Marketplace which contains not only Azure's resources in IaaS filed but a kubernetes cluster as well

**Comment by jnoller** [comment]
Currently there is not a method to do application deployment as you wish with AKS. We are evaluating options for vendors and partners when using AKS and marketplace. When we have more information is will be linked in the roadmap. https://github.com/Azure/AKS/projects
