### ISSUE TITLE
Ingress controller: Error creating loadbalancer with Public IP Prefix

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/AKS#1084]
**What happened**: I tried deploying the nginx ingress controller helm chart with a specific public ip but the loadbalancer doesn't get provisioned.
The public ip I created is via the Public IP Prefix service, so not the via the Public IP service.

See attachment for error:
[error.txt](https://github.com/Azure/AKS/files/3349074/error.txt)

So it sees the IP but cannot create the LB. Is that because it is a public ip with the standard sku instead of basic?

**What you expected to happen**: For a loadbalancer to be provisioned

**How to reproduce it (as minimally and precisely as possible)**:
Create an AKS cluster
Install helm
Create a public ip prefix and add a public ip
Deploy nginx ingress controller helm chart and set the public ip for the lb

**Environment**:
- Kubernetes version (use `kubectl version`): client 1.14.1, server 1.13.5
- Size of cluster (how many worker nodes are in the cluster?) 3 nodes
- General description of workloads in the cluster: N/A

**Comment by bramvdklinkenberg** [comment]
It works fine when I provision a public ip directly (so not via public ip prefix).

**Comment by seanmck** [comment]
Yes, it is likely due to SKU mismatch. Can you try creating a cluster with the standard LB?

https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard

**Comment by ams0** [comment]
I’m interested in this too. I have a StandardLB-enabled cluster, I have a prefix created in the same RG (MC_*) of AKS with 52.255.212.152/30 range. 

When I specify:
  loadBalancerIP: 52.255.212.152/30

```
  Warning  CreatingLoadBalancerFailed  <invalid>  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service default/azure-load-balancer: user supplied IP Address 52.255.212.152/30 was not found in resource group mc_akschallenge_akschallenge_eastus
```

and if I specify:
  loadBalancerIP: 52.255.212.154

```
  Warning  CreatingLoadBalancerFailed  <invalid> (x3 over <invalid>)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service default/azure-load-balancer: user supplied IP Address 52.255.212.154 was not found in resource group mc_akschallenge_akschallenge_eastus
```

so how to specify a range?

**Comment by xuto2** [comment]
I think this is limitation from k8s Azure cloud provider. Right now the cloud provider always assume the user provided ip is a public ip address in the node resource group. So
1. "52.255.212.152/30" is a public ip prefix but not a IP, cloud provider won't recognize it
2. "52.255.212.154" is a public ip within the prefix range, but you probably didn't create it yet. It needs to be shown in the resource group for k8s Azure cloud provider to validate the existence.

**Comment by xuto2** [comment]
Re: "It works fine when I provision a public ip directly (so not via public ip prefix)."

I bet if you create the public ip from the public ip prefix, then you can assign that public ip to the service.

To create public ip from ip prefix:
https://docs.microsoft.com/en-us/azure/virtual-network/manage-public-ip-address-prefix#create-a-static-public-ip-address-from-a-prefix

**Comment by jluk** [comment]
@bramvdklinkenberg could you try the above advice Tony mentioned? Would that resolve your issue?

**Comment by bramvdklinkenberg** [comment]
Hi @xuto2 and @jluk sorry for the late reply. But that is already how I tried it. So first created the prefix and then the public ip in the prefix. Then deploy the ingress controller with specifying that specific public ip.

**Comment by bramvdklinkenberg** [comment]
@xuto2 and @jluk any update on this? still have the same issue. 

Another question, is there a way of creating the IP address in the same RG as the AKS resource, instead of creating them in the MC_ RG?

**Comment by bramvdklinkenberg** [comment]
Never mind the last question, just need to add an annotation:

```
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "<RG>"
```

**Comment by xuto2** [comment]
@bramvdklinkenberg to figure out the exact reason we will need to look into the cloud controller log. Do you have an AKS cluster that experienced the issue recently?

(Without looking into the logs, one sanity check that you can do is that the public ip prefix where you create public ip from should be in the same subscription and the same region as the load balancer/aks cluster).

**Comment by jluk** [comment]
Closing due to staleness, please reopen a new support request or issue if still occurring.
