### ISSUE TITLE
Bad Request'. Details: Changing property 'servicePrincipalProfile.clientId

### ISSUE THREAD

**Issue by jimbeauh** [Azure/AKS#1085]
I'm following the AKS tutorial and cannot create an AKS cluster. I keep getting the following error message: 

Bad Request'. Details: Changing property 'servicePrincipalProfile.clientId

I've tried the posted solutions I've seen on StackOverflow with no luck.

**Comment by johan-dupreez** [comment]
I had a similar problem and then created a new SPID 

az ad sp create-for-rbac --skip-assignment. 

 

Rgs 

Johan
