### ISSUE TITLE
--authentication-token-webhook is set to false, which is preventing the prometheus to scrape pod metrics over 10250

### ISSUE THREAD

**Issue by djsly** [Azure/AKS#1087]
**What happened**:
I deployed the prometheus-operator chart : https://github.com/helm/charts/tree/master/stable/prometheus-operator

**What you expected to happen**:
My kubelet metrics to be scraped. both `/metrics/cadvisor` and `/metrics` on port secure https port `10250`

**How to reproduce it (as minimally and precisely as possible)**:
`helm install stable/prometheus-operator`

**Anything else we need to know?**:
While we can force the operator to use the non https port `10255`, this is considered a security issue and we should refrain from doing so `exporter-kubelets.https=false`

What we did to test, was to set the following kubelet configuration `--authentication-token-webhook=true` since is seems that AKS doesn't set it, hence we are getting the default value which is `false`.
Luckily, AKS explicitly sets: `--authorization-mode=Webhook` which is also required.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
```
09:14 $ kubectl get nodes
NAME                            STATUS   ROLES   AGE   VERSION
aks-linux-64816677-vmss000000   Ready    agent   12d   v1.14.0
aks-linux-64816677-vmss000001   Ready    agent   12d   v1.14.0
aks-linux-64816677-vmss000002   Ready    agent   12d   v1.14.0
aks-linux-64816677-vmss000003   Ready    agent   12d   v1.14.0
aks-linux-64816677-vmss000004   Ready    agent   12d   v1.14.0
akswin000000                    Ready    agent   12d   v1.14.0
akswin000001                    Ready    agent   12d   v1.14.0
akswin000002                    Ready    agent   12d   v1.14.0
akswin000003                    Ready    agent   12d   v1.14.0
akswin000004                    Ready    agent   12d   v1.14.0
```
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by Korijn** [comment]
Confirmed, observed same problem on my AKS cluster.

**Comment by marcinma** [comment]
Is there a way to enable webhook? or is it one of this solution with "create from scratch" scenario?

**Comment by jnoller** [comment]
We will raise this to engineering to evaluate. This is marked as an enhancement as the current behavior and flags were deployed intentionally with this configuration. However, these values were set some time ago (we will evaluate this one for side effects with other customer workloads and other possible issues). 

This is not a roadmap item as it is not a feature / this thread is the only report / request of this issue from the customer base. As noted, I will raise this up with engineering.

**Comment by frasmarco** [comment]
Hello everybody,
any update on this?

**Comment by Korijn** [comment]
@jnoller to be clear, there are security implications to this issue: it's causing people to communicate between pods over http instead of https, which is a no-no in Kubernetes production grade security as far as I am aware.

**Comment by ankitgoelcmu** [comment]
@jnoller Any update on this issue? `http` is NOT an option here, as this can cause security issue. 
we need a way to set `--authentication-token-webhook=true` for kubelet

**Comment by xxxxavier** [comment]
Is there any way to check the `--authentication-token-webhook`  flag by `kubectl`? I am working on prometheus and get a 400 error to grab metrics from pods. I suspect it is the reason, but couldn't find a way to confirm it.

**Comment by djsly** [comment]
Ssh on a node to verify the kubelet command line as well as the kubelet logs

**Comment by iMacX** [comment]
Hi,

Also getting some 401 errors on Kubelet with prometheus-operator.

From this issue:

https://github.com/coreos/prometheus-operator/issues/976

and based on the troubleshooting docs:
https://github.com/coreos/kube-prometheus#error-retrieving-kubelet-metrics

I have to set those flags as mentioned by @djsly 

--authentication-token-webhook=true
--authorization-mode=Webhook

So, at the end, is it possible to do that on AKS v 1.15.7?

Thank you for the help.

**Comment by jnoller** [comment]
@iMacX  if you use aad, this should already be on, otherwise you can sideload the change like this:

https://github.com/jnoller/kubernaughty/blob/master/tools/enable-webhook

or you can execute that in a priv. daemonset.

**Comment by djsly** [comment]
@jnoller where can I see that when using AAD `--authentication-token-webhook=true` us enabled ?

We have been using AAD from day one when this issue was reported and we weren't told that we could stop. using the non secure port in any AKS releases :(

**Comment by jnoller** [comment]
@djsly You would need to SSH into the node and dump the kubeconfig or use the vmss runcmd tool to dump it. I walk through how to do this here:

https://github.com/jnoller/kubernaughty/blob/master/docs/part3-whats-in-the-box.md#voiding-the-warranty

This is a writeup on how I hijack the nodes:

https://github.com/jnoller/kubernaughty/blob/master/docs/part-4-how-you-kill-a-container-runtime.md#prop

Note, alterations and changes like this may be unsupported and result in cluster downtime if applied incorrectly.

**Comment by djsly** [comment]
thanks, but I was referring to you comment 

>if you use aad, this should already be on

It made believe that I could be using https, hence this ticket could be closed (if we say that this is supported when AAD is enabled)

**Comment by jnoller** [comment]
the ports should be open on AAD clusters. I don't think we should close this until we can confirm that it's enabled for all use-cases and scenarios.

**Comment by djsly** [comment]
perfect, I will verify and revert to usage of non https port if all is good! thanks for letting us know of the development

**Comment by iMacX** [comment]
> @iMacX if you use aad, this should already be on, otherwise you can sideload the change like this:
> 
> https://github.com/jnoller/kubernaughty/blob/master/tools/enable-webhook
> 
> or you can execute that in a priv. daemonset.

Thank you. I just executed your script:

> ClusterStaging_Technical_Resources -n aks-nodepool1-12604619-vmss --instance 0 --command-id RunShellScript -o json --scripts sed -i 's/--authorization-mode=Webhook/--authorization-mode=Webhook --authentication-token-webhook=true/g' /etc/default/kubelet
> **Enable succeeded:** 
> [stdout]
> 
> [stderr]

But what should I do then? Still getting prometheus-operator target down du to 401?

I then try to set Kubelet service monitor to http based on this solution:

https://github.com/coreos/prometheus-operator/issues/926#issuecomment-476437013

It is working but what is supposed to do your script in comparaison to the http solution?

**Comment by iMacX** [comment]
@jnoller Hello, Could you tell me what I'm supposed to do after having executed your script ? Because there are still 401 error if I disable the serviceMonitor https in prom-operator. Thank you

**Comment by jnoller** [comment]
@iMacX  Once you enable the webhook on the cluster, you do not need to futher modify the operator for it to work. Are you using AAD? Did you SSH into the nodes to look at the configuration file?

**Comment by jnoller** [comment]
@iMacX To be clear, after you enable the webhook, using `helm install monitoring stable/prometheus-operator` should work. The default service monitors already take into account the service changes to the scrapeconfig

**Comment by rpocase** [comment]
@jnoller I had to restart my kubelets manually after making that change. I just used a slightly modified version of the enable script to add `systemctl daemon-reload && systemctl restart kubectl`.

**Comment by jnoller** [comment]
@rpocase hrm, that should have been there. Let me test 😩

**Comment by t-bzhan** [comment]
Use a privileged daemon set to login into the node and exec:

> sed -i 's/--authorization-mode=Webhook/--authorization-mode=Webhook --authentication-token-webhook=true/g' /etc/default/kubelet

> service kubelet restart

Fix the issue for me, but it does not work with cluster-autoscaler, the newly added nodes still suffer from the same issue.

Does there stand a chance that we could only perform a one-time configuration and it works for any nodes?

**Comment by neilswinton** [comment]
We're running into this, too.  I really don't view the workarounds as options for production systems. The absence of pod metrics makes it hard to find the root cause of a node using too much CPU on AKS.  This may be an enhancement in a narrow technical sense but when you are trying to run a business on Azure it's a bug.

**Comment by denyo** [comment]
As commented here: https://github.com/coreos/prometheus-operator/issues/926#issuecomment-662414013

In case anyone comes across this issue again with AKS and k8s `1.18.4`.
With the chart `stable/prometheus-operator` in version `9.2.0` removing the suggested change
```diff
- kubelet:
-   serviceMonitor:
-     https: false
``` 
fixes the issue.

So there was no need to patch anything on the kubelets with a fresh cluster.

**Comment by christianbeland** [comment]
> @iMacX if you use aad, this should already be on, otherwise you can sideload the change like this:
> 
> https://github.com/jnoller/kubernaughty/blob/master/tools/enable-webhook
> 
> or you can execute that in a priv. daemonset.

I have an AKS cluster that uses AAD and I can confirm you that HTTPS is NOT on.

**Comment by joelw** [comment]
@christianbeland Which Kubernetes version are you using? With 1.16.10 I found that HTTPS and the webhook authentication were both working correctly.

**Comment by christianbeland** [comment]
Both clusters use 1.15.7

**Comment by djsly** [comment]
on my 1.15.10 cluster with AAD enabled

```
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      4235/kubelet    
tcp        0      0 127.0.0.1:46601         0.0.0.0:*               LISTEN      4235/kubelet 
tcp6       0      0 :::10250                :::*                    LISTEN      4235/kubelet    
tcp6       0      0 :::10255                :::*                    LISTEN      4235/kubelet   
```

I don't have a cluster with no AAD

**Comment by christianbeland** [comment]
1.15.7, AAD Enabled
`
tcp    LISTEN     0      16384    :::10250                :::*                   users:(("kubelet",pid=3724,fd=7))
tcp    LISTEN     0      16384    :::10255                :::*                   users:(("kubelet",pid=3724,fd=24))
`
but prometheus gets a "server returned HTTP status 401 Unauthorized" since /etc/default/kubelet does not have 
`--authentication-token-webhook=true `
