### ISSUE TITLE
AKS support for node labels as part of agentPoolProfile to persist labels through upgrade/scale

### ISSUE THREAD

**Issue by vflopes** [Azure/AKS#1088]
**What happened**: Can't put labels on node

**What you expected to happen**: A documentation or guide explaining how to define labels for nodes trough nodepools

**Anything else we need to know?**: I'm using `az aks` commands to manage and deploy AKS clusters.

**Environment**:
- Kubernetes version: 1.12.8
- Size of cluster (how many worker nodes are in the cluster?): From one to any size (we're using cluster autoscaler)
- General description of workloads in the cluster: Services exposing HTTP APIs

------------

I'm deploying AKS clusters and I want to split the workloads by tiers and to have this behavior I'm using nodeSelectors on my Deployments, but to make this work I need to define which labels will be assigned to new nodes created by the autoscaler. I'm not seeing this feature anywhere (Microsoft/Azure/AKS docs), are there any command or API where I can define the template (and the labels) for new nodes created by the autoscaler?

**Comment by Vitorspk** [comment]
I have the same problem when trying to scale nodes

**Comment by jnoller** [comment]
This is on the roadmap for 2019. Adding to in progress in https://github.com/Azure/AKS/projects

**Comment by MacTynow** [comment]
Hi @jluk (reposting from [terraform azure rm provider](https://github.com/terraform-providers/terraform-provider-azurerm/issues/3907)) , I'm confused because I can see references to custom labels in https://github.com/Azure/aks-engine/blob/master/examples/kubernetes-labels/kubernetes.json as well as https://github.com/Azure/aks-engine/blob/8f5de6d71f67c1b3f618338626f7e86a8ea98727/pkg/api/types.go#L547.

Do you mean that this doesn't work yet or that the behavior is different from using --kubelet-extra-args '--node-labels=foo=bar?

**Comment by jluk** [comment]
@mactynow that would be the AKS Engine project which is separate from AKS. The label functionality you see as part of the agentpool is what we plan to bring into AKS, but until we do you won't have labels reapplied through upgrade/scale.

**Comment by Benjiiim** [comment]
@jluk, would you mind to provide an update on this one? Thanks a lot.

**Comment by jluk** [comment]
Hey @Benjiiim we'll get it before end of the year, that's my best estimate right now as we're wrapping up some important behavior for agent pools wrt quality of servicing and support of older/existing clusters. I should have a better estimate of timing in 4-6 weeks.

**Comment by dazdaz** [comment]
@jluk any update on the timeline for when this will be implemented ?  This feature be useful right now.  Thanks a lot.

**Comment by jluk** [comment]
This is scoping for December, as we'll need to release a new API version.

**Comment by ncole** [comment]
Is this still slated for December?

**Comment by jluk** [comment]
As of today, this is still on plan by end of December. This is subject to change but will update this issue if it does.

**Comment by jayush** [comment]
Thanks @jluk for the update. Will this feature be released as a preview feature or GA feature in December?

**Comment by dstockton** [comment]
@jluk do you have any update, please? Is it still looking like the end of Dec for this?
Many thanks, David

**Comment by jluk** [comment]
Hey folks, thanks for bumping this. Labels support has been delayed a bit, looking at early in the new year for next ETA. We have just closed on setting agent pool tag support to be released by end of year, but rest assured this request for agent pool labels is firmly on the roadmap and will be delivered.

**Comment by michael-burt** [comment]
Can we get an update on this feature?

**Comment by ncole** [comment]
> Can we get an update on this feature?

+1 for this update please

**Comment by ncole** [comment]
I checked the Azure SDK for Go and at the time of commenting it looks like v38.2.0 contains this functionality (possibly earlier versions, but I only checked that version).

**Comment by petegrimsdale** [comment]
@jluk Is there an estimate as to when this capability will be available?

**Comment by jluk** [comment]
This is supported via API now. We are closing on the CLI support and documentation.

This requires operations on the target agentPool via the agentPool API. These can only be set on creation, mutation is not supported in this release.

**Comment by jluk** [comment]
This capability is now shipped and available on the latest CLI build, az v2.2.0.

https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.2.0

**Comment by michael-burt** [comment]
Thanks @jluk you are doing a great job of communicating this stuff and we appreciate it.

**Comment by jluk** [comment]
Thanks a lot for the kind words, @michael-burt glad this is helpful!

**Comment by jcjwent** [comment]
Hello @jluk thanks a lot for releasing this feature. Have been waiting for this.

I am creating my node pools using the [ContainerServices Fluent SDK](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.containerservice.fluent?view=azure-dotnet). The AgentPools.CreateOrUpdate operation uses the AgentPoolInner class documented [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.containerservice.fluent.models.agentpoolinner?view=azure-dotnet). Do you have a suggestion how to add node labels to the node pool added using this operation? The AgentPoolInner class does not seem to have a provision for this.

Hope you can guide me to a solution.
