### ISSUE TITLE
Please update docs to explain how to upgrade minions/worker nodes OS

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#109]
Maybe I just can't find it, but I would really like to find some documentation on the process of upgrading worker nodes underlying OS.

**Comment by seanmck** [comment]
This is covered in the [FAQ](https://docs.microsoft.com/azure/aks/faq). 

OS patches are automatically applied, but you are responsible for performing any required reboots, which you can do manually per node through the portal/CLI, by "upgrading" the cluster to the version you're already on, or by using Kured.
