### ISSUE TITLE
Cluster creation with existing service principal fails with 'not found'

### ISSUE THREAD

**Issue by evenh** [Azure/AKS#1092]
**What happened**:

When creating a RBAC enabled (AAD) AKS cluster with [terraform](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html) using a custom service principal, I often encounter this error
```Service principal clientID: <REDACTED> not found in Active Directory tenant <REDACTED>```.

Using `az ad sp list` I can verify that the expected client ID is present. The cluster creation is happening _after_ modifying AAD successfully and retrieving the generated UUID used for configuring RBAC.

To me it looks like a propagation/timing issue. The Azure Active Directory is not external to the best of my knowledge.

The code responsible for communicating with the Azure APIs

https://github.com/terraform-providers/terraform-provider-azurerm/blob/b42ae8688145ca06d859acf2713fd58246509592/vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2019-02-01/containerservice/containerservices.go#L50

**What you expected to happen**:

That the cluster should successfully be provisioning with the an existing (recently created) service principal and RBAC configuration.

**How to reproduce it (as minimally and precisely as possible)**:

1. Programatically create the server and client configuration as specified in [the official docs](https://docs.microsoft.com/en-us/azure/aks/azure-ad-integration-cli) for RBAC
2. Programatically create a separate service principal for the cluster itself
3. Immediately try to create a new cluster using the credentials from step 1 and 2.

**Anything else we need to know?**:

Related: #1045

**Environment**:
- Kubernetes version: 1.13.5
- Size of cluster: 2 
- General description of workloads in the cluster: Empty cluster with [application-gateway-kubernetes-ingress](https://github.com/Azure/application-gateway-kubernetes-ingress)
- Others: Terraform v0.12.3, AzureAD provider v0.4.0, AzureRM provider v1.31.0

**Comment by AdamGlass** [comment]
try removing this: $HOME/.azure/aksServicePrincipal.json

It's listed in the troubleshooting section here: https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal   .

**Comment by kiall** [comment]
@evenh are steps 1+2 done with terraform? If so, this was an issue in the Terraform Azure Provider until very recently:

https://github.com/terraform-providers/terraform-provider-azuread/issues/4
https://github.com/terraform-providers/terraform-provider-azuread/pull/86

However, the fix should be included in the 0.4.0 azuread provider update...

**Comment by jnoller** [comment]
Closing as resolved per @kiall
