### ISSUE TITLE
Cannot add monitoring add-in via CLI in South Africa North

### ISSUE THREAD

**Issue by johan-dupreez** [Azure/AKS#1093]
My expectation was that according to the article https://azure.microsoft.com/en-us/updates/general-availability-azure-kubernetes-service-in-south-africa-north/?cdn=disable AKS with custom CNI and Windows nodes and agent pools would be supported for aks preview.

I executed the command as follow:
az aks create 
--resource-group K8SE-DevSA-RG-02 
--name Aks-SANorth-Cluster 
--node-count 1 
--enable-addons monitoring 
--windows-admin-username Aks_Win_Us3r 
--windows-admin-password a_Password! 
--network-plugin azure --enable-vmss 
--vnet-subnet-id "/subscriptions/c6af1ccb-24b6-43c6-b4fb-e8d864175c5b/resourceGroups/K8SE-DevSA-RG02/providers/Microsoft.Network/virtualNetworks/K8S-QA-Vnet/subnets/AKS-K8S-10.250.8" 
--docker-bridge-address 172.17.0.1/16 
--dns-service-ip 10.240.23.254 
--service-cidr 10.240.16.0/21 
--generate-ssh-keys

Below was the output
'southafricanorth' Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 452, in default_command_handler
    return op(**command_args)
  File "/Users/JohanDuPreez/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 618, in aks_create
    workspace_resource_id
  File "/Users/JohanDuPreez/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 855, in _handle_addons_args
    cmd, subscription_id, resource_group_name)
  File "/Users/JohanDuPreez/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 930, in _ensure_default_log_analytics_workspace_for_monitoring
    rg_location] if AzureRegionToOmsRegionMap[rg_location] else default_region_name
KeyError: 'southafricanorth'

Is this feature supported in South Africa North as yet and if not when would we could we expect it to be available?

**Comment by MikkelHegn** [comment]
Looks like it's tied to the monitoring add-in. Try rerunning without that requirement. Let me check if this is somethign we need to fix in the cli extension.

**Comment by johan-dupreez** [comment]
Thank you for the feedback. I will attempt the deployment shortly and provide feedback.




kind regards




Johan du Preez









On Mon, Jul 8, 2019 at 3:09 PM +0200, "Mikkel Mork Hegnhoj" <notifications@github.com> wrote:












Looks like it's tied to the monitoring add-in. Try rerunning without that requirement. Let me check if this is somethign we need to fix in the cli extension.

**Comment by johan-dupreez** [comment]
Thank you the built went through successful. Kindly close ticket.

**Comment by MikkelHegn** [comment]
I'll reopen and change the title to reflect the issue with monitoring add-in in southafricanorth.

**Comment by MikkelHegn** [comment]
@keikhara - is this a WI you need to fix?

**Comment by johan-dupreez** [comment]
Thank you Mikkel, yes it would be. Let me know of the status should there be a change and monitoring is allowed. 

Regards

Johan

**Comment by ganga1980** [comment]
@johan-dupreez ,  looks like you are on old version of the CLI. can you please upgrade to latest Azure CLI version and let me know if still this is an issue?

**Comment by ganga1980** [comment]
@@johan-dupreez @MikkelHegn, Investigated. This issue only in AKS-Preview extension since the AKS-Preview modifies the behavior of the Azure CLI. If AKS-Preview removed or the files under **/.azure/cliextensions/aks-preview"** removed no issue.  I will try to work with AKS team to get the fix.

**Comment by johan-dupreez** [comment]
Thank you very much.

**Comment by johan-dupreez** [comment]
Hi in response I am using azure-cli 2.0.59 with aks-preview 0.4.3 and aks-virtual-node 0.2.0.
I perform the update this afternoon and do a test deployment with the --enable-addons monitoring and will let you know what the outcome was.

**Comment by MikkelHegn** [comment]
The non-preview version of the cli does not support Windows at this point. But using the preview-cli to create the cluster, and then add the add-on using the non-preview cli is an option: https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-enable-existing-clusters#enable-using-azure-cli

**Comment by ganga1980** [comment]
@MikkelHegn  @johan-dupreez,   I have made  an PR on the aks-preview CLI to fix this issue. I am waiting for the aks-preview  CLI owners to review to get this merged.

**Comment by MikkelHegn** [comment]
@ganga1980 Can you please ref the PR here for trackability? Thanks.

**Comment by jluk** [comment]
Looks like this one: https://github.com/Azure/azure-cli-extensions/pull/856 asking folks to review

**Comment by jluk** [comment]
@ganga1980 it looks like your PR is now merged, we just need to align it under another version release and update the index files so users can pull the change.

**Comment by ganga1980** [comment]
> @ganga1980 it looks like your PR is now merged, we just need to align it under another version release and update the index files so users can pull the change.

@jluk , I will reach out the AKS dev team to get this released.

**Comment by jluk** [comment]
@ganga1980 is this complete?

**Comment by ganga1980** [comment]
@jluk, yes, this has been merged on 14th Aug. validated latest version of the aks-preview has the fix.

**Comment by jluk** [comment]
Great thanks for confirm, closing.
