### ISSUE TITLE
Getting error " NetworkPlugin cni failed to set up pod "apache-546bf54d7c-hhrb4_default" network: open /run/flannel/subnet.env:"

### ISSUE THREAD

**Issue by rishabhvipul007** [Azure/AKS#1094]
Getting error " NetworkPlugin cni failed to set up pod "apache-546bf54d7c-hhrb4_default" network: open /run/flannel/subnet.env:" , Any help is appreciated.

i am using my default network so i have not used pod network during "kubeadm init"

Thank for your help in advance.
![Getting error during pod creation](https://user-images.githubusercontent.com/50710036/60759480-b0bdea00-a043-11e9-9b38-72358bd99312.PNG)

**Comment by alanjcastonguay** [comment]
`kubeadm` xor AKS - not both. Did you make this in the wrong repository?

**Comment by jnoller** [comment]
Kubeadm is not a component of or supported with AKS
