### ISSUE TITLE
Cannot upgrade nodepool from 1.12.8 to 1.13.5

### ISSUE THREAD

**Issue by chunliu** [Azure/AKS#1096]
**What happened**:
When I tried to upgrade the nodepool from the current version 1.12.8 to 1.13.5, I hit the following error: 
```
Operation failed with status: 'Bad Request'. Details: The value of parameter agentpool.Properties.OrchestratorVersion is invalid. Please see https://aka.ms/aks-naming-rules for more details.
```

**What you expected to happen**:
The nodepool should be upgraded successfully. 

**How to reproduce it (as minimally and precisely as possible)**:
On a cluster with 1 nodepool which is on version 1.12.8, run the following command: 
`az aks nodepool upgrade --resource-group yourresourcegroup --cluster-name yourclustername -n yournodepoolname -k 1.13.5 --no-wait`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?)
1

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
For testing

- Others:

**Comment by local-master** [comment]
Hi @chunliu 

You need to run "az aks upgrade" first then run "az aks nodepool upgrade"

I've faced the problem recently as well.

**Comment by chunliu** [comment]
Thanks, @local-master ! It works. So I guess their doc needs to be upgraded.
