### ISSUE TITLE
Windows Server Containers : Pods running but Container doesn't

### ISSUE THREAD

**Issue by srv-twry** [Azure/AKS#1097]
**What happened**: I am working on deploying a .NET console application as a Windows Server Container on AKS. The application's main role is to monitor an Azure storage queue every 30 seconds, pick a set of entries from the queue if available and do some processing on it. I am also automatically scaling the number of pods up and down depending on the number of entries in the Azure storage queue that the application uses.
 
There seems to be an issue with the windows node pool. Upon fresh creation of the node pool, the application runs fine but after a certain number of pod autoscaling up and down, the pod is shown as running on the cluster however the container inside of it isn't running. Once I delete the node pool and create a fresh one, the issue resolves temporarily and the application starts working. 

**What you expected to happen**: The pods and the containers inside run smoothly.

**How to reproduce it (as minimally and precisely as possible)**:
Basically, I have been using the following steps in order to reproduce this issue:
 
1. Create a fresh windows node pool containing one node.
2. deploy my application on it.
3. Put a large number of entries(50,000+) on the storage queue. As a result, the number of replicas of my application scales up to 15 and slowly scales back down to 1 as it processes those queue entries. I do this same process multiple times so as to create and destroy a large number of pods.
4. After it, if a new pod is created on the node, the pod is shown to be running fine but the container inside of it doesn't run. **It's almost like the pods that were scaled down aren't actually terminating properly and are still using the resources on the node. As a result, the node simply runs out of resources. This is however just a guess.**
5. If I delete the node pool and create a fresh one, the application starts running fine again for some time.

**Anything else we need to know?**: N/A

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?) : 1 windows node.
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) : .NET application using Azure Storage queue.
- Others: N/A

**Comment by MikkelHegn** [comment]
There's a know issue with terminating containers on Windows, which was fixed in this update: https://support.microsoft.com/en-us/help/4497934/windows-10-update-kb4497934

If you create a new cluster in either Australia, US or Europe (currently rolling out to the rest of the regions), you should get a fixed Windows OS on the Windows node pools. Alternately install the patch manually on your Windows node to validate if this will fix the issue.

**Comment by MikkelHegn** [comment]
Roll-out has completed, all regions now have the new Windows version.

**Comment by guhuajun** [comment]
Thanks for sharing!

**Comment by srv-twry** [comment]
@MikkelHegn Thank you for the info.
Unfortunately, my internship period at Microsoft came to an end and hence am unable to verify if it fixed the issue.
You can close the issue as per your wish.
