### ISSUE TITLE
Windows Node compatibility - Host OS + Container OS + AKS Node

### ISSUE THREAD

**Issue by johan-dupreez** [Azure/AKS#1100]
**What happened**: 
We did a build in AKS with a Windows Node pool and when I execute 
kubectl get nodes -o wide the output display 
OS-IMAGE: "Windows Server Datacenter"   
KERNEL VERSION: "10.0.17763.557"

In a previous post of 8 days ago (When adding Windows node pool, need to specify version #1006) 
I note your reply:
"We only support Windows Server 2019 (1809): https://docs.microsoft.com/en-us//azure/aks/windows-node-limitations#limitations-for-windows-server-in-kubernetes"

**What you expected to happen**:
First unknown:
- Which Container OS version should I use to be compatible with the AKS build version?
I have attempted to build the image with "mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019" for my web app that needs both IIS and .Net support.

Second unknown: 
Which Host OS version do I require to build out the images to match both the AKS node OS version and the Container OS version as I get the following error when trying to build the image
"Windows version 10.0.17763-based image is incompatible with a 10.0.17134 host"

**What you expected to happen**: 
I expected to have a Host OS that support a Build for the Container OS and for the container OS to be compatible to the AKS Windows Node OS 

**Environment**:
"orchestratorVersion": "1.12.8"
 "count": 3
"osDiskSizeGb": 100
"osType": "Windows"
"vmSize": "Standard_D2s_v3"
"location": "southafricanorth"
"type": "Microsoft.ContainerService/ManagedClusters"
OS-IMAGE: "Windows Server Datacenter"   
KERNEL VERSION: "10.0.17763.557"

**Comment by MikkelHegn** [comment]
Take a look at these links to understand the relationship between host and container OS compatibility:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility

https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility#matching-container-host-version-with-container-image-versions

https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility#choose-which-container-os-version-to-use

And note that we do not support hyper-v at this point.

**Comment by johan-dupreez** [comment]
Thank you Mikkel. 




kind regards




Johan du Preez









On Fri, Jul 12, 2019 at 12:55 AM +0200, "Mikkel Mork Hegnhoj" <notifications@github.com> wrote:












Take a look at these links to understand the relationship between host and container OS compatibility:

https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility


https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility#matching-container-host-version-with-container-image-versions


https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility#choose-which-container-os-version-to-use


And note that we do not support hyper-v at this point.

**Comment by johan-dupreez** [comment]
Hi, please close the call the articles explained what was needed and the deployment worked as anticipated. Thank you for your assistance.
