### ISSUE TITLE
Error message unclear: 'ManagedClusterAgentPoolProfile.count' must be greater than 1 but should be Parameter 'ManagedClusterAgentPoolProfile.count' must be greater than 0.

### ISSUE THREAD

**Issue by edernucci** [Azure/AKS#1106]
**Describe the bug**
Validation message is **Parameter 'ManagedClusterAgentPoolProfile.count' must be greater than 1** but should be **Parameter 'ManagedClusterAgentPoolProfile.count' must be greater than 0**.

**To Reproduce**
```
$ az aks scale -g desenvolvimento -n desenvolvimento -c 0
validation error: Parameter 'ManagedClusterAgentPoolProfile.count' must be greater than 1.
```

**Expected behavior**
```
$ az aks scale -g desenvolvimento -n desenvolvimento -c 0
validation error: Parameter 'ManagedClusterAgentPoolProfile.count' must be greater than 0.
```

**Environment summary**
```
$ az --version
azure-cli                         2.0.68

command-modules-nspkg               2.0.3
core                              2.0.68
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
front-door                         0.1.8

Python location '/opt/az/bin/python3'
Extensions directory '/home/edernucci/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Jun 28 2019, 06:20:00) 
[GCC 6.3.0 20170516]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by seanmck** [comment]
Moved from CLI repo since I believe this is an RP error message.

**Comment by jluk** [comment]
Thanks for report @edernucci we're on it.

**Comment by xizhamsft** [comment]
ok. Just did some investigation. This error message is not from RP. It is actually from the validation code in python SDK (src\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\v2019_04_01\models\managed_cluster_agent_pool_profile_py3.py). The python SDK is generated from swagger, which has the correct min value (1) and max value. I think the right fix should be blocking 0 count in our code.

**Comment by jluk** [comment]
This has been fixed for both the az aks scale and az aks nodepool scale commands. Thanks for the report!

```
➜  ~ az aks scale -n myakscluster -c 0 -g myresourcegroup        
The behavior of this command has been altered by the following extension: aks-preview
Can't scale down to 0 nodes.
➜  ~ az aks nodepool scale --cluster-name myakscluster -g myresourcegroup -n promo -c 0
Can't scale down to 0 nodes.
```

**Comment by mifurm** [comment]
this issue also happens when you try to disable monitoring agent and one of your nodepools is 0.
So I run this (az aks disable-addons -a monitoring -n aks-prd -g akscluster-rg) and get: validation error: Parameter 'ManagedClusterAgentPoolProfile.count' must be greater than 1.

**Comment by jluk** [comment]
@mifurm thanks for report, what did you do to bring a node pool to size zero? Was it through calling the VMSS API directly?

cc @xizhamsft

**Comment by mifurm** [comment]
> @mifurm thanks for report, what did you do to bring a node pool to size zero? Was it through calling the VMSS API directly?
> 
> cc @xizhamsft
yes!

**Comment by jluk** [comment]
@mifurm it's important to note manual changes to managed IaaS for your AKS clusters are not supported, so scaling to size zero for the pool via VMSS is not a scenario we support today.

However, your ask to improve the error message is still valid and we'll work on getting that reproduced and fixed 👍
