### ISSUE TITLE
Support deleting the first node pool of a cluster

### ISSUE THREAD

**Issue by victornoel** [Azure/AKS#1107]
Currently with AKS, it is impossible to delete the first node poll that was created with a cluster, even if other node pools exist.

There does not seem to be any business requirement for this to be and I suppose it is like this for technical reason.

This issue is to track the resolution of this situation so that customers can delete the first node pool of a cluster and get some feedbacks from the AKS team on the matter.

**Comment by jnoller** [comment]
We do not currently have this on the roadmap short-term. I will label this as a possible future enhancement.

**Comment by init6tech** [comment]
Is this feature added to AKS to delete first node pool from AKS cluster?

**Comment by przemolb** [comment]
Is it tracked somewhere ?

**Comment by schefs** [comment]
@jnoller 
Is there any thoughts on getting this feature developed in the future ? 
Is there any complexity to achieve this capability ?
Right now for changing the default node pool type we have to recreate the cluster, rather then moving all workflow to another node pool with the new vm type desired and delete the first node pool.

Another solution could be the possibility to change the default node pool vm type without cluster recreation.

**Comment by jnoller** [comment]
@schefs  @palma21 can speak to this more - but we will be adding support to allow users to mutate / move the default pool - you will not be able to delete it, but you will be able to migrate/upgrade the default nodepool as desired.

We will not be adding support for complete deletion of the first nodepool at this time

**Comment by schefs** [comment]
@palma21 @jnoller  is there another issue on GitHub referring this feature with more current or active information ?

**Comment by jluk** [comment]
Re-opening to track this specific scenario of deleting the first node-pool by migrating which pool is defined as primary, which as Jesse mentioned is on the backlog.

**Comment by pixxet** [comment]
if the vmss got deleted manually (which is allowed) it's gonna be missing anyway !

**Comment by jluk** [comment]
The operation can be done by calling directly to VMSS APIs outside of AKS as you mention, but it is not a MSFT supported action to take on the cluster. Those operations should leverage what exists in the AKS API. Please take note of the policies defined here carefully.

https://docs.microsoft.com/en-us/azure/aks/support-policies#managed-features-in-aks

**Comment by jluk** [comment]
This is in progress and dependent on the system pool feature described in #1309

**Comment by s-tino** [comment]
Though I would report my experience on this: I faced this same issue, but managed to remove the system nodepool created with the cluster by first creating a new nodepool with system mode. I have done this based on the guidelines in doc:
https://docs.microsoft.com/en-us/azure/aks/use-system-pools

Might be useful to somebody else...

**Comment by jluk** [comment]
That is correct, this can now be completed as a result of completing the system mode feature for node pools. Closing as a result, thanks everyone for participating in this discussion.

**Comment by victornoel** [comment]
glad to see this now possible, thanks!

**Comment by xinity** [comment]
if you plan to use this method, you have to choose between:
- adding another node pool (as a user node pool)
- remove the taints from your single system node pool or else your applications won't schedule on the newly created system node pool.

just saying @jluk @victornoel @simonetino :)
