### ISSUE TITLE
Creating AKS cluster from terraform - error when using example from Docs

### ISSUE THREAD

**Issue by bergmeister** [Azure/AKS#1108]
**What happened**:

I already opened an issue on the docs repo [here](https://github.com/MicrosoftDocs/azure-docs/issues/35143) but since I believe this might be a product bug, I am also opening an issue here.
I followed the following docs on how to create an AKS cluster: https://docs.microsoft.com/en-us/azure/terraform/terraform-create-k8s-cluster-with-tf-and-aks

**What you expected to happen**:

The example should just work.

**How to reproduce it (as minimally and precisely as possible)**:

1. Use terraform `0.12.4` on Windows (latest released version).
2. Follow the linked docs [here]( https://docs.microsoft.com/en-us/azure/terraform/terraform-create-k8s-cluster-with-tf-and-aks) and execute `terraform apply`. You might need to uncomment the `tags` section due to a different, known problem.

It errors out:
```
Error: operationalinsights.WorkspacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=&lt;nil&gt; Code="Conflict" Message="The workspace name 'testLogAnalyticsWorkspaceName' is not unique" Target="name"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): NA
- Size of cluster (how many worker nodes are in the cluster?) NA
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) NA
- Others: Terraform `0.12.4` on Windows (installed via chocolatey)

**Comment by jnoller** [comment]
Closing per documentation comment on https://github.com/MicrosoftDocs/azure-docs/issues/35143

**Comment by bergmeister** [comment]
Ok but as the comment also says, the error message should be clearer and state that 'uniqueness' means uniqueness across the whole of Azure, not just the subscription/tenant.
https://github.com/MicrosoftDocs/azure-docs/issues/35143#issuecomment-514179683
