### ISSUE TITLE
(preview) can't upgrade linux nodepool from 1.14.0 to 1.14.3

### ISSUE THREAD

**Issue by masyanru** [Azure/AKS#1109]
**What happened**:
I tried to upgrade the linux nodepool from the current version 1.14.0 to 1.14.3 and get the following error:

```
az aks nodepool upgrade \                                                                                                                        
--resource-group k8s-mix \
--cluster-name k8s-mix-cluster \
--kubernetes-version 1.14.3 \
--name nodepool1
Deployment failed. Correlation ID: 6e74867e-dfe6-46a2-a033-03fd647e6ee8. Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." 
Details=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n   
 \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n       
 \"message\": \"VM has reported a failure when processing extension 'vmssCSE'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=99\\n[stdout]\\n\\n[stderr]\\n
Connection to k8s.gcr.io 443 port [tcp/https] succeeded!\\n
Connection to gcr.io 443 port [tcp/https] succeeded!\\n
Connection to docker.io 443 port [tcp/https] succeeded!\\n\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"}]
```

I have already run "az aks upgrade --resource-group k8s-mix --name k8s-mix-cluster --kubernetes-version 1.14.3" - everything is ok, then updated the windows nodepool - ok.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubectl version                                                                                                                               11:41
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
kubectl get nodes                                                                                                                               
NAME                                STATUS   ROLES   AGE   VERSION
aks-nodepool1-33766016-vmss000000   Ready    agent   55d   v1.14.0
akswin000001                        Ready    agent   31m   v1.14.3
```

```
az aks nodepool list --resource-group k8s-mix --cluster-name k8s-mix-cluster -o table                                                            
AgentPoolType            Count    MaxPods    Name       OrchestratorVersion    OsDiskSizeGb    OsType    ProvisioningState    ResourceGroup    VmSize
-----------------------  -------  ---------  ---------  ---------------------  --------------  --------  -------------------  ---------------  ---------------
VirtualMachineScaleSets  2        30         nodepool1  1.14.3                 100             Linux     Failed               k8s-mix          Standard_DS2_v2
VirtualMachineScaleSets  1        30         win        1.14.3                 100             Windows   Succeeded            k8s-mix          Standard_D2s_v3
```
"OrchestratorVersion" nodepool list shows 1.14.3 version, but "kubectl get nodes" v1.14.0 for the linux nodepool and it's strange.

**Comment by AGFincom** [comment]
experiencing the same issue, are the nodes supposed to get the update?

with version:

```
NAME                                STATUS   ROLES   AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-agentpool-00000007-vmss000000   Ready    agent   57d     v1.12.7   10.240.0.4    <none>        Ubuntu 16.04.6 LTS   4.15.0-1040-azure   docker://3.0.4
aks-pool12-00000007-vmss000000      Ready    agent   3h12m   v1.13.7   10.240.0.7    <none>        Ubuntu 16.04.6 LTS   4.15.0-1050-azure   docker://3.0.4
```

noticed when new servers are provisioned and\or new pool created they are created with the new version.

since these are managed server in the nodepool (preview feature) we cant access the servers in a straight way (no public IP.. or control)  there should be a way to trigger the rolling upgrade,
is the solution of the dedicated node server - kured works the same?

will notify if kured works.

**Comment by masyanru** [comment]
some new stranger things. ;) 
In azure portal I opened "Virtual machine scale set" and tried to update "Latest Model" from No to Yes. Azure portal returned "The resource operation completed with terminal provisioning state 'Failed'." And you know what's happened next? The linux primary agentpool was disappeared.

kubectl get nodes shows only one k8s node                                                                                                                               
NAME           STATUS   ROLES   AGE     VERSION
akswin000001   Ready    agent   3h31m   v1.14.3

**Comment by djsly** [comment]
the removed 1.14.0 from the list if available version and it broke a bunch of stuff for :)

**Comment by jluk** [comment]
@masyanru please open a support ticket for this issue as we can't troubleshoot this easily via github issues, it is a known problem that for the multiple agent pool preview there may be some split brain versions in a pool. We have scheduled work to reconcile these versions.

@djsly ack on the pain of the speed of supported versions sliding through, I assume you're using Terraform. We have features coming up to help combat this. Thanks for your patience with us.

**Comment by bandarusrinivas** [comment]
is this issue solved in any future versions. I have an AK cluster running on 1.16.9 but the "OrchestratorVersion" sitting behind at 1.14.8. az aks upgrade failing?

az aks nodepool upgrade --name default --resource-group dev_rg-abc5oz2p -k 1.16.9 --cluster-name aaarkpgflyhisbbb
Operation failed with status: 'Bad Request'. Details: Upgrade agent pool version from 1.14.8 to 1.16.9 is not allowed, you can only upgrade one minor version at a time. Please use [az aks get-upgrades] command to get the supported upgrade paths. For more information, please check https://aka.ms/version-skew-policy
