### ISSUE TITLE
AKS deployment fails - following guide for kubernetes-walkthrough-portal

### ISSUE THREAD

**Issue by lodotek** [Azure/AKS#111]
Following the simple instructions here: https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough-portal yet the deployment always fails.
Here is the error:
OPERATION IDC96F850CEBD59F01
TRACKING IDf264152b-946b-4f0b-8bef-fa0435106612
STATUSBadRequest
PROVISIONING STATEFailed
TIMESTAMP1/6/2018, 11:13:36 AM
DURATION4 seconds
TYPEMicrosoft.ContainerService/managedClusters
RESOURCE ID/subscriptions/******************/resourceGroups/akstest010618/providers/Microsoft.ContainerService/managedClusters/akstest010618
STATUSMESSAGE{
  "code": "InternalOperationError",
  "message": ""
}
RESOURCEakstest010618

Please advise

**Comment by JackQuincy** [comment]
That is our message when we do something wrong. I'm looking into this

**Comment by JackQuincy** [comment]
It appears the error came when we try to get a security token to call other azure services. When a sub is enabled for our Resource Provider, our service principal is given permission to make calls to set up the cluster. If the service principal were to be removed or the role assignment that allows our service to make the calls. This could happen. Id unregister, reregister and see if that fixes the problem.

**Comment by JackQuincy** [comment]
@lodotek were you able to register your sub for our provider again?

**Comment by lodotek** [comment]
I'm currently traveling, I might not be able to try again until Friday or
Monday coming up...

**Comment by seanknox** [comment]
Closing due inactivity. Feel free to re-open if still an issue.
