### ISSUE TITLE
How persistent volumes work with fault domains ?

### ISSUE THREAD

**Issue by DBarthe** [Azure/AKS#1115]
Hello ! :)

This is a specific question about the way managed disk / PV works.

A managed disk is supposed to be located in the same fault-domain as the VM it is attached to. 

When a stateful pod is rescheduled to another node, the managed disk is re-attached to the corresponding VM. What happens if they are in different fault-domains ? Will the VM and the disk end up in separated fault-domains ? If not, how the disk is moved between fault domains, is there any obscure data migration behind the scene ?

In case you wonder why I need this, I try to figure out how to properly manage Cassandra clusters inside AKS, so I have to know precisely which pods will fail together. 

Thanks in advance

**Comment by andyzhangx** [comment]
@DBarthe yes, azure disk PV works with fault domain, if the disk re-attached to the VM on another fault domian, DiskRP needs to create a new account to accommodate the disk that would cost around 20s

**Comment by DBarthe** [comment]
Thank @andyzhangx for this information :)

**Comment by jnoller** [comment]
Closing
