### ISSUE TITLE
Error while creating AKS:"code": "ServiceCidrOverlapExistingSubnetsCidr"

### ISSUE THREAD

**Issue by Sayshu** [Azure/AKS#1117]
**What happened**:
I was unable to create an AKS cluster either from Portal or through ARM template using custom Service CIDR which already exists in my VNET.

**What you expected to happen**:
I used to create AKS clusters using pre created Service CIDR subnets in my VNET without any issues, But now i can only create with the expected ServiceCIDR only if i delete it first from my VNET
**How to reproduce it (as minimally and precisely as possible)**:
Create a VNET and required subnets for the AKS cluster
Try to create an AKS cluster using pre existing Kubernetes service address range  from your VNET

**Anything else we need to know?**:
Deleting the pre created service  subnet from my VNET allows me to create the cluster, but the subnet is not visible in my vnet once the cluster is created
**Environment**:
- Kubernetes version (use `kubectl version`):
1.14.3
- Size of cluster (how many worker nodes are in the cluster?)
2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by shanoor** [comment]
I have the same issue, it's a kinda breaking change. The infra as code written for previous successful deployments is not working any more.

**Comment by sesispla** [comment]
+1 same issue here. Infrastructure, as code broke because of VNETs and Subnets, are manually created prior to the AKS Cluster.

**Comment by ChrisRG711** [comment]
I am running into this issue as well from az aks create as well as the portal. is there any workaround at all?

**Comment by liamfoneill** [comment]
+1 On Terraform

**Comment by fethullahmisir** [comment]
+1 On Terraform

**Comment by mikemowgli** [comment]
@Sayshu and all, Azure creates a Service CIDR with default value "10.0.0.0/16". The issue you get is because the subnet you have created upfront overlaps this range. You have two options:
1. attaching the AKS cluster to a subnet outside that 10.0.0.0/16 range
2. defining a custom value for the Service CIDR. In terraform, the setting is: "[service_cidr](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#service_cidr)".

**Comment by mikemowgli** [comment]
@Sayshu , this is strange, since when I had the same issue than you had, I just had to change the range of the subnet to which AKS nodes are attached. Hopefully Microsoft people have an explanation...

**Comment by alonisser** [comment]
This is horrible and broke our automated infra as code process. (ARM templates) can't find out how to fix that

**Comment by sesispla** [comment]
The solution we found is not to create the Subnet, but simply set the service_cidr in Terraform...
