### ISSUE TITLE
Azure monitor + CoreDNS metrics prometheus

### ISSUE THREAD

**Issue by timja** [Azure/AKS#1118]
**What happened**:
Expected coredns metrics in azure monitor after enabling prometheus feature:
https://azure.microsoft.com/en-us/blog/azure-monitor-for-containers-with-prometheus-now-in-preview/
https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-agent-config#overview-of-configurable-prometheus-scraping-settings

**What you expected to happen**:
CoreDNS metrics to be available

**How to reproduce it (as minimally and precisely as possible)**:
https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-agent-config#configure-and-deploy-configmaps
then look for metrics here:
https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-agent-config#review-prometheus-data-usage

**Anything else we need to know?**:
It looks like there's two ways to enable the metrics to be scraped
1. annotation on the pod: `prometheus.io/scrape`
2. adding a configuration entry to point to the service (kubernetes_services)

number 2 isn't ideal as everyone needs to add configuration for it, but it would be in our control, if the prometheus endpoint was exposed on the kube-dns service (but it currently isn't)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
not relevant
- Others:
@keikhara FYI, ran into this when trying out the feature you just released, if there's any workarounds we aren't aware of please feel free to weigh in

**Comment by jnoller** [comment]
@keikhara @vishiy

**Comment by vishiy** [comment]
@jnoller - Can you please track this - "the prometheus endpoint was exposed on the kube-dns service (but it currently isn't"
I will track the issue to collect kube/core-dns metrics from our side , but for us to collect it, it needs to be exposed (which is what the issue above is).

**Comment by jnoller** [comment]
@vishiy The core DNS / DNS metrics are exposed - @weinong enabled them months ago to support the DNS autoscaler. However, AKS runs CoreDNS inside of a deployment named kube-dns, so the naming may not match prometheus expectations

**Comment by vishiy** [comment]
@jnoller @weinong - Can you please advice which end point/port we can get the kube/core dns metrics ?
I see that they are exposed as <pod_ip>:9153/metrics, but the issue is discoverability. There are no pod annotations for this managed pod (so prometheus cannot discover).

**Comment by timja** [comment]
> @vishiy The core DNS / DNS metrics are exposed - @weinong enabled them months ago to support the DNS autoscaler. However, AKS runs CoreDNS inside of a deployment named kube-dns, so the naming may not match prometheus expectations

@jnoller from the current setup released in monitor it either needs the annotation added or exposing the metrics on the service

**Comment by jnoller** [comment]
@timja Yup, @vishiy just mentioned that :)
