### ISSUE TITLE
aks: enable docker insecure registries?

### ISSUE THREAD

**Issue by bitsofinfo** [Azure/AKS#1119]
Are docker insecure registries enabled on AKS clusters? If not how can I do this?

Im following this guide to install jenkins-x on a pre-existing AKS cluster: https://jenkins-x.io/getting-started/install-on-cluster/

and they state this:

```If not using the aws or eks providers, then we need to make sure that insecure Docker registries are enabled. This is so that pipelines can use a Docker registry running inside the Kubernetes cluster (which typically is not public, so no https support). You can modify your pipelines to use other registries later.```

**Comment by jnoller** [comment]
Azure offers Azure Container Registry, however these are not added by default - we are evaluating registry options to provide one by default after current committed work is complete.

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-aks

Marked enhancement for tracking

**Comment by bitsofinfo** [comment]
nothing to do w/ ACR, i'm referring to the ability to tweak this setting in the docker daemon on AKS nodes, and it being obeyed across node scales, and node re-provisioning https://docs.docker.com/registry/insecure/

**Comment by jluk** [comment]
@bitsofinfo are we aligned that the ask is to enable content trust within AKS node pools? Essentially you want to set enable/disable for content trust on a specific node pool then every node upgrade/scale persists this docker check on new nodes.

If so this is a backlogged item and I can update the title/tags, if not please correct me on the ask.

**Comment by bitsofinfo** [comment]
No, please read https://docs.docker.com/registry/insecure/

**Comment by schefs** [comment]
I'm experiencing the same issue trying to connect to a private docker registry of my own inside my vnet, and set it as a mirror registry and as "insecure registry".
All I need to accomplish this is just a the ability to use a custom "daemon.json" docker config file on my aks nodes.
If I'll do it manually, any modification will be deleted on the nexus node pool upgrade or resize.
is there a way to do this so it will persist ?
I'm sure that is what @bitsofinfo was trying to ask for ?

Thank you

**Comment by hqrd** [comment]
Hello,
Is there any news on this ? @jnoller 
Thanks

**Comment by filipepinheiro** [comment]
I had a similar problem, as my registry is also a private internal one.
To solve the problem I recommend that you refer to [https://github.com/coreos/tectonic-docs/blob/master/Documentation/admin/add-registry-cert.md](https://github.com/coreos/tectonic-docs/blob/master/Documentation/admin/add-registry-cert.md), as it can be a nice workaround to make it work (even if you are using self-sign or letsencrypt certs and scale your cluster).

Hope it helps!

Thanks

**Comment by hqrd** [comment]
> I had a similar problem, as my registry is also a private internal one.
> To solve the problem I recommend that you refer to https://github.com/coreos/tectonic-docs/blob/master/Documentation/admin/add-registry-cert.md, as it can be a nice workaround to make it work (even if you are using self-sign or letsencrypt certs and scale your cluster).
> 
> Hope it helps!
> 
> Thanks

Good workaround for self-signed certs indeed, but doesn't solve the non-https repositories unfortunately.

**Comment by bitsofinfo** [comment]
not stale

**Comment by bitsofinfo** [comment]
not stale
