### ISSUE TITLE
Kubernetes node count incorrect and errors when halting nodes via portal/arm and then performing scale-up

### ISSUE THREAD

**Issue by Huge** [Azure/AKS#1120]
**What happened**:
After stopping all worker nodes via the Portal ie. goint to mv_my_rg and opening the virtual machines an clicking Stop on them, then I got the cluster up again doing `az aks scale .. -c 3` which seemed OK and I saw the VMs in the RG. Though, I saw:
```
bash-4.4# aks scale --name aks-cluster --resource-group mv-alfa-forked -c 3  && echo; echo "AKS-forked has 3 nodes"
...
AKS-forked has 3 nodes                                                                                                 
            
bash-4.4# kubectl top nodes
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)                                                     
bash-4.4# kubectl get pods -n cicd-components  --field-selector status.phase=Running                                                                                     
NAME                                   READY   STATUS    RESTARTS   AGE                                                                                                     
cicd-nexus3-5fb9469c8-ndpqf            1/1     Running   0          21m                                                                                                     
cicd-sonar-postgres-755b7bdf78-8pcl5   1/1     Running   0          22m                                                                                                     
cicd-sonarqube-6699575dc9-h466t        1/1     Running   0          19m                                                                                                     

bash-4.4# kubectl top nodes                                                                                                                                                 
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)
```
after an hour or so, though, I'm seeing:
```
 bash-4.4# kubectl top nodes
NAME                       CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
aks-agentpool-19603965-1   260m         13%    1247Mi          58%
aks-agentpool-19603965-2   260m         13%    986Mi           45%
aks-agentpool-19603965-0   <unknown>                           <unknown>               <unknown>               <unknown>    
```
which still is not correct, yet better.

**What you expected to happen**:
Either something about the metrics not being ready or correct info. Definitely having the `kubectl top` functionality working *eventually*.

**How to reproduce it (as minimally and precisely as possible)**:
+ Create a new aks cluster
+  `az aks get-credentials --resource-group your-rg --name your-aks-name --admin`
+ turn off VMs
+ `aks scale --name your-aks-name --resource-group your-rg -c 3` 
+ `kubectl top nodes`

**Anything else we need to know?**:
I think such cluster usage is legitimate as some companies turn their infra down at night. Some do that with their development environments.

**Environment**:
- Kubernetes version (use `kubectl version`): 
- Size of cluster (how many worker nodes are in the cluster?): Tried scaling from 1 to 3, with no difference.
- General description of workloads in the cluster: Jenkins CI

**Comment by jnoller** [comment]
We do not currently support dropping clusters to zero nodes in this way. We understand the cost argument and have been evaluating it. The state drift you mentioned (ARM vs Kubectl) is an issue we are aware of that will need to be resolved as part of this.
