### ISSUE TITLE
VMSS cluster randomly lost network connectivity

### ISSUE THREAD

**Issue by chelnak** [Azure/AKS#1121]
**What happened**:
I have a VMSS enabled cluster that has randomly lost network connectivity. Pods can no longer resolve each other via core DNS and services with external address cannot be reached.

Setting the name server of a pod to 8.8.8.8 (or configuring the dnspolicy) appears to fix name resolution for public services but internal communication does not work... and this obviously does nothing for inbound traffic.

The kube-proxies seem to be failing to create IPTables rules and repeat the following message in the logs.

```
:Not saving endpoints for unknown healthcheck
```

Node logs appear to suggest similar connectivity issues. For example:

```
Jul 22 20:35:46 aks-defaultpool-17163361-vmss000000 python3[1272]: 2019/07/22 20:35:46.113769 ERROR ExtHandler HostGAPlugin: Exception Get API versions: [HttpError] [HTTP Failed] GET http://168.63.129.16:32526/versions -- IOError timed out -- 6 attempts made
```

```
E0722 13:08:46.397461    3580 kubelet_node_status.go:381] Error updating node status, will retry: failed to patch status "{\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"NetworkUnavailable\"},{\"type\"I
```

**What you expected to happen**:
The cluster should remain stable

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?)
Nodepool1: 1 x node
Nodepool2: 2 x node

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Worker services

- Others:

**Comment by chelnak** [comment]
We have made some progress with this issue.

It appears that the network outage occurs when an agent pool template is deployed.

We have observed the following:

1.	The arm template deployment for an agent pool is initiated
2.	The kube-proxy-* pods in the kube-system namespace begin to terminate
3.	You can see that the route tables are being torn down and recreated at the same time
4.	In the activity log, you can see lots of Create or Update Route errors with a status code of 429 (too many requests)

The arm template is using API version **2019-06-01**.

@andyzhangx Is this a bug that the team are familiar with? Is there another API version that we could use?

Thanks!

**Comment by chelnak** [comment]
So I think we have got to the bottom of this.

It looks like the ARM template deployment fails to re add the subnet reference to the route table.

After re associating the missing subnet and rebooting the nodes connectivity was restored.

**Comment by jnoller** [comment]
Please see https://github.com/Azure/AKS/issues/400 - there is a known limitation with user defined routes and ARM, AKS only auto-associates on initial create and if no existing rules on the subnet conflict. If you are doing an update like this via arm you will need to disassociate the UDR first, apply the update and then re-apply the UDR.

**Comment by jluk** [comment]
@chelnak thanks for the debugging, could you confirm that this was occurring on an update done via ARM template to confirm the issue was an expectation of automatic RT association when it is only done on cluster create by the service?

**Comment by chelnak** [comment]
@jluk Yes. The issue is occurring when we reapply (update) a node pool arm template. We can replicate this.

https://github.com/SkillsFundingAgency/das-platform-building-blocks/blob/master/templates/aks-agent-pool.json

@jnoller We haven't added any UDRs above what is deployed along with AKS.

I'm now not 100% sure about my comment here: https://github.com/Azure/AKS/issues/1121#issuecomment-514225583

But the redeployment of the node pool definitely breaks cluster networking and impacts the route table that is created with AKS. (https://github.com/Azure/AKS/issues/1121#issuecomment-514165094)

**Comment by mlushpenko** [comment]
Also had this issue today. Not sure if it's exactly the same, but errors were identical, restarting some nodes helped and then when one pod kept crashing, we drained the node and then on another one it worked just fine. Any suggestions on how to prevent it in the future? 

We are using cilium for network policies, I think it adds some routes, so maybe that is somewhat related.

@chelnak

**Comment by chelnak** [comment]
Couple of interesting things that we learnt here:

We deploy AKS to an existing subnet that is managed as part of another
lifecycle. AKS Is responsible for managing the route table that attaches to
this subnet. However, the virtual network deployments are not in anyway
idempotent. The route table would get removed from the subnet each time we
deployed our virtual network and blow up the cluster.

Cross node communication dies because nothing can resolve due to the fact
that there are no routes.

I wonder if the node your Pod ended up on was the same node that had core
dns running (just a thought).

Interested to know how you get on with this issue.

**Comment by chelnak** [comment]
The unknown health check error is a know issue apparently. It’s iptables
related.

I was told that they had deployed some sort of mitigation for this.. but am
still seeing it in one of the newest versions.

Are all of your clusters in the same resource group? Just curious.

**Comment by mlushpenko** [comment]
Nope, resource group per cluster (and then extra resource groups created by AKS itself). I guess they could be in the same group, but we created a terraform module which creates all of that together.

**Comment by chelnak** [comment]
I was just curious because you mentioned the thing about the activity log.

Did you manage to get the bad node back up?

**Comment by mlushpenko** [comment]
Nope, we cordoned it, drained and then cluster autoscaler removed that node. Hope new nodes won't have similar problems.
