### ISSUE TITLE
Creating a cluster when logged in using a machine identity fails

### ISSUE THREAD

**Issue by cwebbtw** [Azure/AKS#1123]
**What happened**:

When provisioning an AKS cluster from a virtual machine where the currently logged in user type is a user managed identity, an error occurs:

```
Error: Error waiting for completion of Managed Kubernetes Cluster "cpe-demo-cjw-k8s" (Resource Group "cpe-demo-cjw-k8s-rg"): Code="CreateRoleAssignmentError" Message="RoleAssignmentReconciler retry timed out: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailed\" Message=\"The client '565e8efe-af95-4b0c-8641-6e2f0fc4aac8' with object id '565e8efe-af95-4b0c-8641-6e2f0fc4aac8' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/9e6b1432-c830-41fb-9c63-b1de69af46dd/resourceGroups/MC_cpe-demo-cjw-k8s-rg_cpe-demo-cjw-k8s_westeurope/providers/Microsoft.Authorization/roleAssignments/194a3266-434d-420c-abc2-0b33ba02640b' or the scope is invalid. If access was recently granted, please refresh your credentials.\""
```

**What you expected to happen**:

The cluster to be created successfully

**How to reproduce it (as minimally and precisely as possible)**:

1. Assign a user managed identity on a virtual machine where the user managed identity has Owner rights to the subscription.
2. Attempt to create a Kubernetes cluster - we're using the Azure terraform provider.

```
resource "azurerm_kubernetes_cluster" "aks" {
  name                = "aks"
  location            = "westeurope"
  resource_group_name = "aks-resource-group"
  dns_prefix          = "aks"
  kubernetes_version  =  "1.13.5
  agent_pool_profile {
    name            = "nodepool"
    count           = "3"
    vm_size         = "Standard_DS2_v2"
    os_type         = "Linux"
    os_disk_size_gb = 30
  }

  service_principal {
    client_id     = REDACTED
    client_secret = REDACTED
  }
}
```

**Anything else we need to know?**:

We've tested this with a service principal with the exact same permissions, which actually works fine but when using a managed identity, it seems to produce the aforementioned error each time.

The referenced client id in the error, '565e8efe-af95-4b0c-8641-6e2f0fc4aac8', does not actually exist in our AD tenant.

See:

```
~ $ az ad sp show --id 565e8efe-af95-4b0c-8641-6e2f0fc4aac8
{
  "accountEnabled": "True",
  "addIns": [],
  "alternativeNames": [],
  "appDisplayName": "AzureContainerService",
  "appId": "7319c514-987d-4e9b-ac3d-d38c4f427f4c",
  "appOwnerTenantId": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "appRoleAssignmentRequired": false,
  "appRoles": [],
  "applicationTemplateId": null,
  "deletionTimestamp": null,
  "displayName": "AzureContainerService",
  "errorUrl": null,
  "homepage": null,
  "informationalUrls": {
    "marketing": null,
    "privacy": null,
    "support": null,
    "termsOfService": null
  },
  "keyCredentials": [],
  "logoutUrl": null,
  "notificationEmailAddresses": [],
  "oauth2Permissions": [],
  "objectId": "565e8efe-af95-4b0c-8641-6e2f0fc4aac8",
  "objectType": "ServicePrincipal",
  "odata.metadata": "https://graph.windows.net/f55b1f7d-7a7f-49e4-9b90-55218aad89f8/$metadata#directoryObjects/@Element",
  "odata.type": "Microsoft.DirectoryServices.ServicePrincipal",
  "passwordCredentials": [],
  "preferredSingleSignOnMode": null,
  "preferredTokenSigningKeyEndDateTime": null,
  "preferredTokenSigningKeyThumbprint": null,
  "publisherName": "Microsoft Services",
  "replyUrls": [],
  "samlMetadataUrl": null,
  "samlSingleSignOnSettings": null,
  "servicePrincipalNames": [
    "7319c514-987d-4e9b-ac3d-d38c4f427f4c"
  ],
  "servicePrincipalType": "Application",
  "signInAudience": "AzureADMultipleOrgs",
  "tags": [],
  "tokenEncryptionKeyId": null
}
```

**Comment by jnoller** [comment]
MSI is not currently supported: https://github.com/Azure/AKS/issues/993

**Comment by cwebbtw** [comment]
I had a quick read of #993 - that seems to be focused around using a managed identity instead of the service principal block:

```service_principal {

}```

The issue we're currently facing is actually creating an AKS cluster, being logged in as a managed user identity but still using a client id and secret from a service principal.

**Comment by cwebbtw** [comment]
It looks like this is possible via the CLI so this may be an issue to raise against the terraform provider.

```
jenkins@jenkinsdeployer-b92lv:~$ az login --identity
[
  {
    "environmentName": "AzureCloud",
    "id": "<REDACTED>",
    "isDefault": true,
    "name": "<REDACTED>",
    "state": "Enabled",
    "tenantId": "<REDACTED>",
    "user": {
      "assignedIdentityInfo": "MSI",
      "name": "systemAssignedIdentity",
      "type": "servicePrincipal"
    }
  }
]
jenkins@jenkinsdeployer-b92lv:~$ az aks create \
>     --resource-group aks-resource-group \
>     --name myAKSCluster \
>     --node-count 1 \
>     --service-principal <REDACTED> \
>     --client-secret <REDACTED> \
>     --generate-ssh-keys
SSH key files '/home/jenkins/.ssh/id_rsa' and '/home/jenkins/.ssh/id_rsa.pub' have been generated under ~/.ssh to allow SSH access to the VM. If using machines without permanent storage like Azure Cloud Shell without an attached file share, back up your keys to a safe location
 - Running ..
{
  "aadProfile": null,
  "addonProfiles": null,
  "agentPoolProfiles": [
    {
      "availabilityZones": null,
      "count": 1,
      "enableAutoScaling": null,
      "maxCount": null,
      "maxPods": 110,

and so on, indicating a successful creation..
```

**Comment by cwebbtw** [comment]
It seems this issue is related https://github.com/MicrosoftDocs/azure-docs/issues/35586

**Comment by MicahMcKittrick-MSFT** [comment]
Following :)

**Comment by adhodgson1** [comment]
I have been seeing this error and I deploy using ARM templates.  I have managed to (possibly) fix this by setting the API to 2019-06-01, I am not sure what API Terraform is passing in.  I can reproduce the error when using 2019-02-01.  I don't use a managed identity, I log in via the CLI using an SPN.

**Comment by jluk** [comment]
Thanks @cwebbtw and @adhodgson1 for the info and report, this does look to be scoping into a terraform issue if it is not repeatable outside of the TF provider. Is there an Azure Terraform issue opened for it? Happy to help drive a resolution from MSFT side if we can confirm it is a TF isolated issue.

**Comment by jluk** [comment]
We looked into this and want to rule out if it is related to an issue that has now been mitigated in West Europe specifically. @cwebbtw could you retry this with your terraform deployment in West Europe again and let us know your results?

**Comment by cwebbtw** [comment]
Thank you for getting involved in this Justin/Jesse.

I will run deployments in northeurope/westeurope back to back for the next few hours and report back on the success/failure rate.

**Comment by cwebbtw** [comment]
I haven't been able to reproduce this all day in both **westeurope** and **northeurope**. I can confirm that it is over **two** times slower for us to create the same cluster in westeurope though:

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  name                = "aks"
  location            = "westeurope"
  resource_group_name = "aks-resource-group"
  dns_prefix          = "aks"
  kubernetes_version  =  "1.13.5
  agent_pool_profile {
    name            = "nodepool"
    count           = "3"
    vm_size         = "Standard_DS2_v2"
    os_type         = "Linux"
    os_disk_size_gb = 30
  }

  service_principal {
    client_id     = REDACTED
    client_secret = REDACTED
  }
}
```

That being said, the time taken to create the cluster is not a concern of this story.

> that has now been mitigated in West Europe specifically

@jluk Are you able to confirm that a change was made to westeurope?

**Comment by jluk** [comment]
@cwebbtw thanks for rerunning that, we did make a change to west europe so if it is successful now that is great. we can take a look into the latency specifically as well, but I'm going to close this issue for now. If it happens again please feel free to re-open.
