### ISSUE TITLE
AKS Ingress rule for .Net Framework (4.6)

### ISSUE THREAD

**Issue by som-nitjsr** [Azure/AKS#1128]
I have .net Framework(4.6) based Web API service. i am hosting them in azure AKS.

I am using nignix and  written  Ingress Rule  like this.

host: abc.com
    http:
     paths:
      - path: /EmailAPI
        backend:
          serviceName: esolvitemailapi-svc
          servicePort: 80

Now My web api is expecting URl 

http://service/api/controller/action

But i think Ingres in sending the URI as 

http://service/EmailAPI/api/controller/action

and i am getting 404 Error.

what is the best way to handle it.  i don't want to do code change by doing  [RoutePrefix("IdentityAPI/api")]

there are couple of apis and its big solution so it may break.

is there any think i can handle it at configuration level.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by markusdresch** [comment]
less an AKS question than a nginx ingress question. simply add this to your ingress rule metadata:

```
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
```

**Comment by som-nitjsr** [comment]
> less an AKS question than a nginx ingress question. simply add this to your ingress rule metadata:
> 
> ```
>   annotations:
>     nginx.ingress.kubernetes.io/rewrite-target: /
> ```

Thanks i will try it out.

**Comment by som-nitjsr** [comment]
Hi @markusdresch i think this redirecting to the default backend only.
this is my ingress rule by default i wanted my request to go to the front end service but when i call the apis from front end it should go to the respective service.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
 rules:

  - host: abc.com
    http:
     paths:
      - path: /EmailAPI/
        backend:
          serviceName: s1-svc
          servicePort: 80
      - path: /IdentityAPI/
        backend:
          serviceName: s2-svc
          servicePort: 80
      - path: /ProfileAPI
        backend:
          serviceName: s3-svc
          servicePort: 80
      - backend:
          serviceName: front--svc
          servicePort: 80

**Comment by markusdresch** [comment]
so /EmailAPI/ should route to /api/email/ ? or /api/EmailApi/ ? if it's the latter, you simply use `nginx.ingress.kubernetes.io/app-root: /api`. if it's the former, the easiest way would be to create a different ingress rule for every service and use `nginx.ingress.kubernetes.io/rewrite-target: /api/email` etc.
