### ISSUE TITLE
Cannot create an AKS cluster from Portal UI

### ISSUE THREAD

**Issue by michael-burt** [Azure/AKS#1129]
**What happened**:

Same as in issue 453

**What you expected to happen**:

I am trying to create an AKS cluster within a ResourceGroup that I do not own.

**How to reproduce it (as minimally and precisely as possible)**:

My user does not have admin privs on the resource group. I am trying to create an AKS cluster, but it fails with:

```Resource group 'DefaultResourceGroup-EUS' could not be found```

**Anything else we need to know?**:

None

**Environment**:
- Kubernetes version (use `kubectl version`): 

Any version, but I tried on 1.12 and 1.13
- Size of cluster (how many worker nodes are in the cluster?) 

3 nodes

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

I have not even setup the cluster at this point.

- Others:

**Comment by jnoller** [comment]
Users must have access - read/write/etc on the RG per the documentation.

**Comment by michael-burt** [comment]
Can you link those docs? 

It is confusing because I can create the cluster, I just cannot enable monitoring of it and the error message is not helpful

**Comment by BeigeBadger** [comment]
I have just run into the same issue @michael-burt, I guess I'm turning monitoring off...

**Comment by michael-burt** [comment]
Yeah, docs please @jnoller  ??

**Comment by hansharhoff** [comment]
@jnoller Please link the documentation that you refer to. None of us seem to be able to find it.
Also, it seems that the issue is not caused by lack of read/write access inside the resource group, but the lack of rights to CREATE a new missing resource group.

**Comment by michael-burt** [comment]
@hansharhoff , @jnoller is not the most helpful person in the Microsoft organization. I would recommend checking out this thread. @jluk seems to be a much better person to channel these requests through: https://github.com/Azure/AKS/issues/1050

**Comment by jnoller** [comment]
@michael-burt pardon? I would answer this one but I usually get a few hundred or more emails and notifications a day and I am not the foremost expert on internal RG permissions.

Customers must have the owning r/w permissions on the passed in RG and the ability to create new RGs 

Here are details on AAD v2: https://docs.microsoft.com/en-us/azure/aks/managed-aad

The permissions required on the RG are documented here: https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal

**Comment by michael-burt** [comment]
@jnoller sorry to put you on the spot and thanks for the response. We have been waiting about 10 months for the docs you mentioned and multiple times people have reached out for a response. If you are not the expert on RSG permissions maybe don't close the issue and provide no response?
