### ISSUE TITLE
Guarantee OMSAgent schedules successfully on user tainted nodes

### ISSUE THREAD

**Issue by jeffmartinxyz** [Azure/AKS#1130]
**What happened**:

AKS users may apply taints on some of their nodes, and apply tolerations to kube-system Pods to allow them to be continued to be scheduled there. These tolerations persist in all cases, except for OMSAgent.

**What you expected to happen**:

Tolerations should persist on OMSAgent Pods as well.

**How to reproduce it (as minimally and precisely as possible)**:

Taint a node, apply a tolerations to OMSAgent to allow it to be scheduled on the tainted node, wait for a new release of OMSAgent.

**Comment by jluk** [comment]
@jeffmartinxyz as discussed internally this has been triaged. Matching the statement on the public issue, user tolerations set on AKS managed kube-system pods are not guaranteed to persist. However, system pods should be scheduling onto nodes regardless of the user defined taints and we will address the latter part of this. Updating the issue to reflect this.

**Comment by jluk** [comment]
Closing as this should be going out on this week's service rollout.
