### ISSUE TITLE
Windows Node Updates

### ISSUE THREAD

**Issue by sam-cogan** [Azure/AKS#1132]
If you follow the FAQ page here - https://docs.microsoft.com/en-us/azure/aks/faq it indicates that to apply Windows updates to your Windows VM nodes you have to use the AZ AKS nodepool upgrade command, which recreates the nodes with the latest OS image. 

This is fine, except that AZ AKS nodepool upgrade only does this if you specify a kubernetes version newer than the one you have deployed to that node pool. If you use the same version, nothing happens to the nodes. This now means that getting Windows updates is tied to upgrading my version of Kubernetes. It also means that if I am on the latest version of Kubernetes available in AKS, then I can't get Windows updates until a new version is released. This doesn't seem like the right way to do this.

Am I getting this wrong, or are there any plans to make this better?

**Comment by zhiweiv** [comment]
Per https://github.com/MicrosoftDocs/azure-docs/issues/34407, it should be on the way.

**Comment by MikkelHegn** [comment]
Correct - we are working on closing the gap to enable nodepool OS upgrades independent of Kubernetes upgrades. In the meantime, only option is to create new node pools and migrate workloads.

To clarify the upgrade flow, you first need to run a cluster Kubernetes version upgrade, then you will get the new OS versions available for nodepools. Same upgrade constraint existing for cluster upgrades. https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#upgrade-a-node-pool for reference.

**Comment by coreywagehoft** [comment]
> Correct - we are working on closing the gap to enable nodepool OS upgrades independent of Kubernetes upgrades. In the meantime, only option is to create new node pools and migrate workloads.
> 
> To clarify the upgrade flow, you first need to run a cluster Kubernetes version upgrade, then you will get the new OS versions available for nodepools. Same upgrade constraint existing for cluster upgrades. https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#upgrade-a-node-pool for reference.

@MikkelHegn I didn't see independant nodepool OS upgrades on the AKS roadmap here on GitHub.  Will that be added soon, so I can track progress?

**Comment by MikkelHegn** [comment]
Tracking this here: #893

**Comment by MikkelHegn** [comment]
Closing this issue with node image upgrade now in public preview.
