### ISSUE TITLE
deprovision a single device from an enrollment group

### ISSUE THREAD

**Issue by Shreyasnie** [Azure/AKS#1136]
Regarding deprovision a single device from group enrolment we followed steps as described in below link

https://docs.microsoft.com/bs-latn-ba/azure/iot-dps/how-to-unprovision-devices

Devices were getting disabled previously but we tried to disable a device  last week its not working, individual enrolment is getting created for device with same deviceID even though it is disabled device status still shows connected and device is able to communicate with IoT hub.

Attached screenshot reference.
 
![IOT Hub individual enrolment](https://user-images.githubusercontent.com/1092106/62473157-d1ea3580-b7bd-11e9-931e-fe9753291e15.jpg)

**Comment by jnoller** [comment]
This repository is only for AKS (Azure Kubernetes Service) and not other services such as IoT

**Comment by Shreyasnie** [comment]
Sorry My bad
