### ISSUE TITLE
Why ingress only on Linux nodes?

### ISSUE THREAD

**Issue by bobrundle** [Azure/AKS#1140]
I'm setting up an AKS cluster with Windows agent nodes.  The limitations document https://docs.microsoft.com/en-us//azure/aks/windows-node-limitations says to schedule ingress controllers only on Linux nodes.

However I have the cluster completely set up with ingress controllers on the Windows nodes and everything seems to be working fine.

This seems to be more a recommendation than a limitation.  Why is it recommended to run ingress controllers only on Linux nodes?

**Comment by alanjcastonguay** [comment]
I doubt it's anything to do with Ingress and everything to do with Network Connections or availability of a Windows Ingress Controller. Which ingress controller are you running on a Windows node?

**Comment by bobrundle** [comment]
I've written my own ASP.NET Core ingress controller.  As some point I will put it in a Linux container and see if it performs better on the Linux node.  I would prefer not to do that however.  I just have this feeling that keeping everything Windows will simply deployment and a lot of other stuff.  As it is however, I have one Linux agent VM in my cluster that does nothing and that bothers me also.

**Comment by palma21** [comment]
Linux VM is required for k8s and AKS system components that are only available on Linux today.

If you wrote your own windows ingress controller you can totally use it on the windows nodes.
We'd love to see it btw :)

**Comment by jluk** [comment]
@MikkelHegn FYI feedback on Windows documentation.

**Comment by MikkelHegn** [comment]
Thx @bobrundle - This is a recommendation based on available ingress controllers in the eco-system. I'll get the doc updated to reflect this.

**Comment by jluk** [comment]
Closing this question given the action we will take to clarify it can be setup if custom handled.
