### ISSUE TITLE
Expose service on AKS via Istio Ingress - Error 500

### ISSUE THREAD

**Issue by KhoaNPA** [Azure/AKS#1141]
**Bug description**
I tried to expose my services on AKS with Istio Ingress, but I think I misunderstood something when routing services.
When I test my api, it returns 500 error.

![smartid](https://user-images.githubusercontent.com/17474501/62588912-abc5b200-b8f1-11e9-86ca-2831c858aa6c.png)

**I also create issue on Istio github [istio/istio/issues/16069](https://github.com/istio/istio/issues/16069)**
(please visit it for detail, thank you!)

**Comment by jluk** [comment]
Closing due to staleness, please follow up with Azure support for an SLA'd response to troubleshoot if needed.
