### ISSUE TITLE
PodNodeSelector support

### ISSUE THREAD

**Issue by chelnak** [Azure/AKS#1143]
This is more of a question than an issue.

Does AKS support PodNodeSelector configuration?

It would be nice to be able to assign specific namespaces to nodepools.

Thanks
Craig

**Comment by bergerx** [comment]
Seems like "not".

You need the "PodNodeSelector" admission controller to be enabled to use it, but according to https://docs.microsoft.com/en-us/azure/aks/faq#what-kubernetes-admission-controllers-does-aks-support-can-admission-controllers-be-added-or-removed its not one of the enabled admission controllers. Admission controllers are not configurable in AKS, you cant add or remove.

**Comment by chelnak** [comment]
Cheers. Hadn't seen that doc before. 👍 

Hopefully it will come in the future.

**Comment by pierluigilenoci** [comment]
@palma21 is there any hope that it will be activated on AKS?

**Comment by palma21** [comment]
Yes, we can consider it
