### ISSUE TITLE
Applying OS updates to VMSS enabled clusters

### ISSUE THREAD

**Issue by chelnak** [Azure/AKS#1148]
**Describe the request**
It's currently unclear how to apply OS patches to VMSS clusters. The documents recommend using kured however there are multiple comments/articles that suggest it doesn't work as expected.

It would be good to have some clear guidelines for this.

**Explain why AKS Engine needs it**
See above.

E.g 
https://github.com/Azure/AKS/issues/1065
https://github.com/MicrosoftDocs/azure-docs/issues/33657#issuecomment-506042419
https://github.com/Azure/aks-engine/issues/956

**Describe the solution you'd like**
Some guidance on OS patching when using VMSS enabled clusters.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by palma21** [comment]
Same way as VMAS by using:
https://docs.microsoft.com/en-us/azure/aks/node-updates-kured

It does work, those articles refer a docs item that was not using kured but a custom component. And an issue in AKS-engine that presents the correct behavior of both kured and cluster autoscaler

Eg.
2 nodes - patched nightly. Kured will reboot them. 
When it does so CA will scale a 3rd node to keep the needed resources in the cluster. the 3rd node will have the same image used to create the cluster, or from the last AKS upgrade operation.
that 3rd node will be patched nightly too and rebooted by kured.

**Comment by chelnak** [comment]
Nice! Thank you.

**Comment by dariuszbz** [comment]
I'm confused but....
Download clear image
Update
Push your solution to updated image
Tag new version
Update with kubectl
