### ISSUE TITLE
VMExtensionProvisioningError when trying to scale the VMSS

### ISSUE THREAD

**Issue by vijaygos** [Azure/AKS#1149]
**What happened**:
When trying to create new VMs using the cluster autoscaler, we have been seeing the  "VMExtensionProvisioningError" often across different clusters spanning multiple regions and Azure Clouds.

_E0813 17:03:31.948077       1 azure_scale_set.go:164] virtualMachineScaleSetsClient.CreateOrUpdate for scale set "**k8s-gpupoolk80-428****-vmss**" failed: Code="c" Message="**VM has reported a failure when processing extension 'vmssCSE'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=85**\n[stdout]\n\n[stderr]\nConnection to k8s.gcr.io 443 port [tcp/https] succeeded!\nConnection to gcr.io 443 port [tcp/https] succeeded!\nConnection to docker.io 443 port [tcp/https] succeeded!\n\"."
W0813 17:03:31.948197       1 clusterstate.go:255] Disabling scale-up for node group k8s-gpupoolk80-42858893-vmss until 2019-08-13 17:27:42.264897011 +0000 UTC m=+323923.214366349; errorClass=99; errorCode=cloudProviderError_

Someone from Azure/AKS team told us that this was a known issue and can be mitigated by draining all the nodes in the VMSS. We tried this on one of our clusters and that worked. However, this approach is no longer scalable.

**What you expected to happen**:
VMs must be created with no issues

**How to reproduce it (as minimally and precisely as possible)**:
Not clear. It seems to happen all of a sudden. Most common with GPU node pools that require **NVIDIA driver installations on the new VMs being created.**

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.3
- Size of cluster (how many worker nodes are in the cluster?)
No specific size. Happens with clusters with variable sizes.
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.
- Others:

**Comment by jluk** [comment]
@vijaygos do you have a support ticket open for this? If not could you please open one so an engineer can take a closer look?

**Comment by vijaygos** [comment]
I have opened numerous azure tickets in this regard but the issue has simply been floating around. Please let me know if there is anything I can get you here to have this addressed.

**Comment by jluk** [comment]
@vijaygos could you please give your cluster an upgrade and retry the scale? Or start from a new cluster and attempt again? Internally it looks like a few incidents about this occurred multiple weeks back and a fix was already made.

**Comment by vijaygos** [comment]
So, we are looking at upgrading our cluster. But, given that we use AKS engine, bootstraping a new cluster might take time. For now, I have been mitigating these issues by draining all the problem nodes and allowing our autoscaler to scale once again.

**Comment by jluk** [comment]
Thanks @vijaygos given you're running it on engine, feel free to use the issues on their project to keep issue hygiene. I'm going to close this for now, but if you hit the same CSE errors on a regular AKS upgrade please feel free to open another support ticket.

**Comment by vijaygos** [comment]
@jluk, could you please take a look @ #1166 ?
