### ISSUE TITLE
K8s version upgrade process on Windows cluster caused workload downtime

### ISSUE THREAD

**Issue by brobichaud** [Azure/AKS#1151]
**What happened**:
Upgraded the k8s version of the control plane and nodepools and experienced downtime of exposed service workloads running multi-instance pods.

**What you expected to happen**:
Graceful upgrade of k8s version without loss of any services that were hosted on multiple nodes within a nodepool. Following instructions on this page: https://docs.microsoft.com/en-us//azure/aks/use-multiple-node-pools#upgrade-a-node-pool

**How to reproduce it (as minimally and precisely as possible)**:

1. Start with a cluster running k8s v1.14.3 with two nodes pools, the default linux nodepool with one node (Standard_D1_v2), and a Windows nodepool with 2 nodes (Standard_F8s_v2).
2. Upgrade the control plane to v1.14.5 via this command:
     `az aks upgrade -g mygroup -n mycluster -k 1.14.5`
3. Upgrade the default linux nodepool using this command:
     `az aks nodepool upgrade -g mygroup --cluster-name mycluster --name nodepool1 -k 1.14.5`
    After a minute or so all of my Windows workloads tied to services became unavailable (AppInsights started showing availability test failures to back this up)
    The update of k8s also took what seemed like an excessively long time. I didn't actually time it but would guesstimate it was 7-8 minutes to complete.
4. Upgrade the Windows nodepool with this command:
     `az aks nodepool upgrade -g mygroup --cluster-name mycluster --name win2 -k 1.14.5`
    This created a new node and deleted an old one. At the point this first node was finished my workloads came back online. Then it repeated with a node replacing the second old node.
    This process took even longer than the linux nodepool, but since my services remained up during this period it was less concerning. Plus I could see the VM creation and deletion, so that set an expectation in itself of things taking some time.

**Anything else we need to know?**:
In the end all of my workloads came back online but I did not anticipate any loss of service during the upgrade. Each of my workloads has a minimum of two pods each on separate nodes for high-availability. Since the upgrade works on a node at a time I expected no downtime. I also was quite surprised to see that upgrading the linux nodepool had any affect on my Windows workloads.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.3
- Size of cluster (how many worker nodes are in the cluster?): 2 nodepools as described above
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): AspNetCore WebApi's and WebUI's, NetFramework workers
- Others:

**Comment by jluk** [comment]
@brobichaud I believe @MikkelHegn is going to try a repro, but in general the expectation for higher availability is you will need a min of 3 Linux nodes in your default node pool. This is due to critical system pods and their replicas needing proper hosts to run on, if you only allocate one than that single point of failure can cause worker downtime. We do cordon/drain, but if any dependency fails on that single node your workloads will lose proper use of cluster-wide impacting pods like coredns.

Did you discover workload outage when only upgrading the Windows node pool as well, or only during the Linux nodepool upgrade?

**Comment by brobichaud** [comment]
@jluk Ah that would totally explain it. I do have a single linux node in the default nodepool. The service outage I saw was during the linux nodepool upgrade, and then the services started coming back online around the time I started the upgrade of the Windows nodepool. My thinking during the process was that since my Windows services went offline that maybe upgrading the Windows nodepool would somehow "kick" my services back into a working state. But I'd now guess that the timing was coincidental.

I have not seen documented any guidance on how I should be allocating/treating that default linux nodepool. I was actually under the impression it was not being used so I allocated a single very low-end SKU to that VM (Standard_D1_v2).

It would be good to see some strong guidance in that area. Also, it would be good to see some discussion of what that nodepool is used for. It actually sounds like part of the control plane, yet I was under the impression that Microsoft was hosting that and I didn't have to worry/think about it at all. This worries me a bit.

**Comment by jluk** [comment]
Totally agree, to clarify we do manage your control plane for you but there are system pods that need to run on worker nodes on linux hosts to enable some functionality on the side of workers and outside of the control plane which we do manage.

We'll get some documentation updated for this - @MikkelHegn for thoughts on explaining this Linux dependency a bit better on the Windows specific nodes.

**Comment by Plasma** [comment]
I recently scaled Linux nodes to 1 also since I didn’t need them; but reading they are needed for proper availability is surprising

**Comment by MikkelHegn** [comment]
We've added some clarifying text to these docs: https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#create-an-aks-cluster and https://docs.microsoft.com/en-us//azure/aks/windows-container-cli#create-an-aks-cluster
