### ISSUE TITLE
kubectl x509 certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by EmJayBee83** [Azure/AKS#1152]
Starting early this morning I have been unable to successfully connect to new AKS clusters using kubectl. Whenever I try to connect to the cluster (e.g., `kubectl get nodes`) I receive the following error:

`Unable to connect to the server: x509: certificate has expired or is not yet valid`

Info:
Trying to narrow things donw I spun clusters using the AzureRM provider for terraform, manually in the portal and via the cli (following the steps provided in https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough). All exhibit the same behavior.

Clusters were spun in eastus, centralus, and westus regions.

Credentials for the newly spun cluster were pulled using `az aks get-credentials ...`

**Comment by andyzhangx** [comment]
could you try again? it should be recovered now.

**Comment by MikkelHegn** [comment]
I had an issue caused by WSL2 on Windows, where time the was off, due to WSL2 pausing time when the computer sleep, causing new clusters certs to not be valid yet. Ref: https://github.com/microsoft/WSL/issues/4245#issuecomment-510238198

**Comment by EmJayBee83** [comment]
@MIkkelHegn  That was it. The system clock on my deployment VM was off.  Thanks for taking the time to comment on this.
