### ISSUE TITLE
Add NetworkPolicy Support for Kubenet (Basic Network)

### ISSUE THREAD

**Issue by RehanSaeed** [Azure/AKS#1154]
**What happened**:

I tried to use NetworkPolicy with AKS using the Basic network configuration that uses kubenet.

**What you expected to happen**:

I expect this to work but according to the documentation, I have to use the Advanced network configuration that uses the AZURE CNI.

**Comment by ams0** [comment]
It does work out of the box. The combination on the CLI/ARM of `--network-policy calico` and `--network-plugin kubenet` is valid.

**Comment by RehanSaeed** [comment]
According to the [docs](https://docs.microsoft.com/en-us/azure/aks/use-network-policies):

> Network policy only works with the Azure CNI (advanced) option.

The Azure CNI basic option uses kubenet.

**Comment by feiskyer** [comment]
@RehanSaeed Calico Network Policy works with kubenet, while both Azure Network Policy and Calico work for Azure CNI.

/cc @sauryadas We should update the docs that Calico network policy could be used togather with kubenet.

**Comment by sauryadas** [comment]
Its in the backlog

**Comment by RehanSaeed** [comment]
I'm using ARM templates. How do you set the network policy in an ARM template because it's not documented (not that I can find). Also what relation does `--network-policy calico` and `--network-plugin kubenet` have to Basic vs Advanced networking? This is all very confusing.

**Comment by ams0** [comment]
Basic == kubenet
Advanced == AzureCNI

For both, you can either let Azure create the required VNET or bring your own; for both, you can have no kubernetes network policy support or add Calico. For AzureCNI only, you can choose Azure NPM instead of Calico. I hope it helps.

**Comment by RehanSaeed** [comment]
Thanks, that's really helpful.

How does one add Calico Network Policy support via ARM templates. BTW, the docs all show `az` command line examples. For production scenario's it's really important to also have ARM template examples.

**Comment by ams0** [comment]
You can start here: https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate#networkpolicy

**Comment by mathieu-benoit** [comment]
Looks like this one could be closed since the associated (https://docs.microsoft.com/azure/aks/use-network-policies) has been updated, @jluk @sauryadas
