### ISSUE TITLE
Virtual Node Support Init Container

### ISSUE THREAD

**Issue by deepakramesh1985** [Azure/AKS#1155]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jluk** [comment]
@srrengar / @rbitia for this ask.

@deepakramesh1985 could you share some more detail on why this enhancement request for virtual nodes is needed for you?

**Comment by deepakramesh1985** [comment]
Hi @srrengar / @rbitia
We are installing istio as a service mesh on aks cluster. In istio, application pods get injected with proxy containers. The proxy container get started with init container in same application pod .
The init container's work is to provide prerequisites to proxy container.
As we require azure virtual node for auto scaling of cluster, In peak load the application pods will not deploy on virtual node as limitation mentioned in azure documents. Init container deployment does not support on azure container instances.
We need your support to overcome this issue.
Thanks
Deepak R

**Comment by srrengar** [comment]
this is currently not on the roadmap for ACI but we will consider implementing this due to multiple customer asks  - https://github.com/virtual-kubelet/virtual-kubelet/issues/530

#please-close

**Comment by jluk** [comment]
Closing issue to conslidate request with https://github.com/virtual-kubelet/virtual-kubelet/issues/530

**Comment by ptemmer** [comment]
I'm very much interested in this as well

**Comment by jluk** [comment]
Reopening with the owner @dkkapur assigned since 530 is closed and not moving

**Comment by dkkapur** [comment]
This is cool! Heard this request a few times so we're evaluating it from a product design perspective and will have more to share in terms of capabilities and timeline in the coming month. If you've got specific cases you can share that can help ensure the scenario is covered, please do share.

**Comment by macolso** [comment]
Hello! Init container support is currently on the road-map for May.

**Comment by rakelkar** [comment]
Is this supported now? Can you post a pointer to docs here?

**Comment by keithduncan** [comment]
Bump to prevent this issue being closed.
