### ISSUE TITLE
Needed patches still not there

### ISSUE THREAD

**Issue by bdlawrence13** [Azure/AKS#1160]
I saw that 7 days ago someone posted that all regions have been upgraded. However, when I view available versions of AKS in our region (East US), I get the following:
~$ az aks get-upgrades --resource-group xxxxxxxxxx1 --name xxxxxxxxx1-Kubernetes --output table
Name     ResourceGroup    MasterVersion    NodePoolVersion    Upgrades
-------  ---------------  ---------------  -----------------  -------------------------------
default  xxxxxxxxxxx1   1.11.5           1.11.5             1.11.9, 1.11.10, 1.12.7, 1.12.8

Still not seeing version 1.13 or 1.14.

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by qike-ms** [comment]
We do not support upgrade more than 1 minor version. So it's not that later minor versions are not available in the region, but it's not recommended to your cluster. You need to upgrade from 1.11 to 1.12 to be able to upgrade to 1.13 and so on...
