### ISSUE TITLE
Authenticate with ACR from AKS Preview Failing With Error

### ISSUE THREAD

**Issue by coreywagehoft** [Azure/AKS#1164]
**What happened**:
I was attempting to setup the new preview for ACR authentication with AKS using the azure-cli for an existing AKS cluster.

https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration

Based on the documentation I used the following command:
```
az aks update -n <cluster_name> -g <cluster_rg> --enable-acr --acr /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/<acr-resource-group/ContainerRegistry/<acr-name>
```
I am using the resource ID because my ACR is in a different subscription than the AKS cluster.

The following error was returned from the azure-cli
```
Parameter 'registry_name' must have length less than 50.
Traceback (most recent call last):
  File "/home/vscode/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1404, in _ensure_aks_acr
    resource_group_name, registry_name)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/containerregistry/v2019_05_01/operations/_registries_operations.py", line 228, in get
    'registryName': self._serialize.url("registry_name", registry_name, 'str', max_length=50, min_length=5, pattern=r'^[a-zA-Z0-9]*$')
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 592, in url
    data = self.validate(data, name, required=True, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 672, in validate
    raise ValidationError(key, name, value)
msrest.exceptions.ValidationError: Parameter 'registry_name' must have length less than 50.
Parameter 'registry_name' must have length less than 50.
```

**What you expected to happen**:
I expected it to setup the the authentication successfully.

**How to reproduce it (as minimally and precisely as possible)**:
If you run the command above with real information using the entire resource ID it should reproduce the issue.

**Anything else we need to know?**:

**Environment**:
Azure CLI version information:
```
azure-cli                         2.0.71

command-modules-nspkg               2.0.3
core                              2.0.71
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
aks-preview                       0.4.10

Python location '/opt/az/bin/python3'
Extensions directory '/home/vscode/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Aug  8 2019, 03:51:02) 
[GCC 7.4.0]
```

**Comment by jluk** [comment]
@sauryadas or @mlearned it looks like the doc advocates passing the resourceid as the --acr param, but it gets denied by acr name upper limits. Can you verify this doc/cmd is accurate?

**Comment by feiskyer** [comment]
The ACR resource ID is illegal, its format should be `/subscriptions/<subscription-d>/resourceGroups/<resource-group-name>/providers/Microsoft.ContainerRegistry/registries/<name>`.

Since it's not a valid Azure resource ID, the `--acr` thought it's an ACR name, thus the above error is reported.

Could you correct the resource ID and try again?

**Comment by jluk** [comment]
Thanks @feiskyer - Would suggest placing a placeholder value in the doc that has that format instead of "resource-id".

**Comment by coreywagehoft** [comment]
Thanks @feiskyer for giving me the correct format.  The command did not error out with the upper limits error I previously was given.

I did however get a new error.
`Deployment failed. Correlation ID: 962ccad4-bac0-4bca-a813-fd1665c2ae08. Internal server error`

**Comment by feiskyer** [comment]
> Would suggest placing a placeholder value in the doc that has that format instead of "resource-id".

@sauryadas Could you help to update the docs?

>Deployment failed. Correlation ID: 962ccad4-bac0-4bca-a813-fd1665c2ae08. Internal server error

Not sure the reasons for this. @coreywagehoft Could you try again with same commands? If it's still failing, please open a support ticket for it.

**Comment by sauryadas** [comment]
Will make a pr later .. thanks for investigating



Thanks

Saurya

________________________________

**Comment by sauryadas** [comment]
PR https://github.com/MicrosoftDocs/azure-docs/pull/37673
Should be merged tomorrow

**Comment by sauryadas** [comment]
closing this as docs have been merged
