### ISSUE TITLE
Service Principal creation lags behind final validation (ServicePrincipalNotFound)

### ISSUE THREAD

**Issue by stvhwrd** [Azure/AKS#1165]
**What happened**: 

When creating a Kubernetes cluster in the Azure Portal (GUI) and creating a new service principal  with defaults, the final validation fails:

```json
{
    "code": "InvalidTemplateDeployment",
    "message": "The template deployment 'microsoft.aks-20190822092943' is not valid according to the validation procedure. The tracking id is '81f94590-473d-41f8-b415-91d9c5adcf6a'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.",
    "details":
    [
        {
            "code": "ServicePrincipalNotFound",
            "message": "Provisioning of resource(s) for container service stehowa-cluster in resource group stehowa failed. Message: {\n \"code\": \"ServicePrincipalNotFound\",\n \"message\": \"Internal server error\"\n }. Details: "
        }
    ]
}
```

After waiting a few minutes and re-running the validation (with no other changes), it passes successfully.

![image](https://user-images.githubusercontent.com/4117011/63547713-951e7e00-c4e1-11e9-83c3-a845e65b6c62.png)

**What you expected to happen**:

Final validation to succeed on first run.

**How to reproduce it (as minimally and precisely as possible)**:

Create a new Kubernetes cluster via the Azure Portal GUI and use default settings for service principal.

**Anything else we need to know?**: 

Nope!

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.10 (default)
- Size of cluster (how many worker nodes are in the cluster?) 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) N/A
- Others:

**Comment by CyberCastleQWT** [comment]
Hi:

I have the same problem when creating the cluster,
![image](https://user-images.githubusercontent.com/42950596/63616548-c36d8d80-c5b5-11e9-8864-15441f869c29.png)

Greetings

**Comment by sarmadjari** [comment]
I have the same issue when creating AKS cluster through the portal, did few tests with one of Azure Support Engineers and we confirm this issue.

**Comment by stvhwrd** [comment]
I reported the bug from within the Azure portal and received this response from Azure IaaS:

>Unfortunately a known issue – there’s a replication delay in AAD ☹ We’re working with both the AKS RP and AAD graph teams to try to address this issue but we don’t have any quick fix we can do.

**Comment by ahelwer** [comment]
Even worse is that this issue is intermittent - You can run `Test-AzResourceGroupDeployment` until it stops spitting out the `ServicePrincipalNotFound` error, but then you run `New-AzResourceGroupDeployment` and it fails with `ServicePrincipalNotFound`. Please just add a large number of retries in the validation before saying the service principal does not exist!

**Comment by jluk** [comment]
Hey folks, I'm going to close this in favor of issue #1206 as this looks like a duplicate. Please bring all comments into that issue to help consolidate. If you feel like it should be re-opened as a separate issue just comment and I'll revisit.

**Comment by stvhwrd** [comment]
Thanks @jluk 🤙
