### ISSUE TITLE
Provisioning of VM extension 'vmssCSE' has timed out

### ISSUE THREAD

**Issue by vijaygos** [Azure/AKS#1166]
**What happened**:
VMSS status is set to 'failed' with error message - "Provisioning of VM extension 'vmssCSE' has timed out. Extension installation may be taking too long, or extension status could not be obtained." 

As a result of this, SLB does not allow for binding of service (type Load balancer) with a public IP resource. The service status is always Pending:

> NAME...................TYPE..................... CLUSTER-IP.......EXTERNAL-IP......PORT(S) ........................................AGE

> my-service-1---ClusterIP -------10.0.52.61-----`<none>` ---------8125/UDP -------------------57m

> my-service-2---LoadBalancer---10.0.165.41 ---**`<pending>`**----80:31330/TCP,443:30354/TCP ---46m

**What you expected to happen**:
No CSE errors and the service should bind to a given public IP resource with no errors.
**How to reproduce it (as minimally and precisely as possible)**:
No real steps. Happens at random when the cluster attempts to scale and add a new VM

**Anything else we need to know?**:
AKS engine version is 0.28.1
**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.2
- Size of cluster (how many worker nodes are in the cluster?) 31
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others: Azure US Government environment

**Comment by vijaygos** [comment]
@jluk and @CecileRobertMichon could you guys please take a look at this issue? Happy to provide any info on the cluster or even access.

**Comment by jluk** [comment]
@vijaygos could you please open up this issue on the aks-engine project per Cecile's post? I am closing this as a result of her info shared.
