### ISSUE TITLE
Gitlab Runner Pods on Virtual Node not starting

### ISSUE THREAD

**Issue by phpai** [Azure/AKS#1168]
**What happened**:
Pods spawned by gitlab-runner on a virtual node stay in Pending state. After a while they are being deleted.

**What you expected to happen**:
Pods spawned by gitlab-runner on a virtual node start successfully.
Is this a known issue? I haven't found anything in the documentation.

**How to reproduce it (as minimally and precisely as possible)**:
- Enabled virtual nodes following this guide: https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli
- Installed a gitlab-runner (kubernetes executor) and schedule (via tolerations) runner jobs to spawn on the virtual node

**Anything else we need to know?**:
Logs from aci-connector:
```bash
time="2019-08-26T09:21:01Z" level=info msg="Created pod in provider" key=aci-gitlab/runner-jkxebbqx-project-167-concurrent-02kkg9 method=createOrUpdatePod name=runner-jkxebbqx-project-167-concurrent-02kkg9 namespace=my-testspace node=virtual-node-aci-linux operatingSystem=Linux phase=Pending pod=runner-jkxebbqx-project-167-concurrent-02kkg9 provider=azure reason= uid=cf445154-c7e2-11e9-b346-1e78e67e6e9f workerId=10
time="2019-08-26T09:21:03Z" level=warning msg="skipping update of pod [[[[runner-jkxebbqx-project-167-concurrent-02kkg9]]]] as pod updates are not supported" key=aci-gitlab/runner-jkxebbqx-project-167-concurrent-02kkg9 method=syncPodInProvider name=runner-jkxebbqx-project-167-concurrent-02kkg9 namespace=my-testspace node=virtual-node-aci-linux operatingSystem=Linux phase=Pending provider=azure reason= uid=cf445154-c7e2-11e9-b346-1e78e67e6e9f workerId=10
time="2019-08-26T09:21:39Z" level=info msg="Deleted pod from Kubernetes" key=aci-gitlab/runner-jkxebbqx-project-167-concurrent-02kkg9 method=deletePod name=runner-jkxebbqx-project-167-concurrent-02kkg9 namespace=my-testspace node=virtual-node-aci-linux operatingSystem=Linux phase=Succeeded provider=azure reason= uid=cf445154-c7e2-11e9-b346-1e78e67e6e9f workerId=10
```
**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.5
- Virtual Node version: v1.13.1-vk-v0.9.0-1-g7b92d1ee-dev
- Size of cluster (how many worker nodes are in the cluster?): 5 + virtual node
- Others: Gitlab Runner v12.2.0

**Comment by jluk** [comment]
@phpai can you share the pod spec that is deploying the runner?

From this error are there any updates being attempted?
```
time="2019-08-26T09:21:03Z" level=warning msg="skipping update of pod [[[[runner-jkxebbqx-project-167-concurrent-02kkg9]]]] as pod updates are not supported" key=aci-gitlab/runner-jkxebbqx-project-167-concurrent-02kkg9 method=syncPodInProvider name=runner-jkxebbqx-project-167-concurrent-02kkg9 namespace=my-testspace node=virtual-node-aci-linux operatingSystem=Linux phase=Pending provider=azure reason= uid=cf445154-c7e2-11e9-b346-1e78e67e6e9f workerId=10
```

**Comment by RicardoNiepel** [comment]
Cross linking two related GitLab issues:
- https://gitlab.com/gitlab-org/gitlab-runner/issues/4664#note_230497049
- https://gitlab.com/gitlab-org/gitlab-runner/issues/3256#note_135771816

**Comment by sanglt** [comment]
This not going to work because virtual node doesn't allow custom arguments for command. Current gitlab-runner use custom arguments for checking which shell is available.

**Comment by MikkelHegn** [comment]
https://github.com/virtual-kubelet/azure-aci/pull/11 explains the missing support in ACI for this to be supported. Currently, you have to specify both command and argument with Virtual Node.
