### ISSUE TITLE
Login to AKS Node with priv key. Password expired

### ISSUE THREAD

**Issue by martin2176** [Azure/AKS#1170]
Issue:
Trying to login to AKS Agent Node with SSH private key (pub key has been copied to AKS Node during the install). Today (I believe 90 days elapsed) the password less login is not working with the message password expired.
I believe by design this is not the intended behavior. The SSH PAM should be set up to not check password expiration for priv-pub key authentication.
Either password of azureuser should be set by installation to not expire
OR
Password expiration check should be bypassed for key based authentication.

PS: I can reset the password through AZ portal , but that is not the expected behavior with password less key based SSH login.

 ssh azureuser@xx.yy.96.4
Authorized uses only. All activity may be monitored and reported.
You are required to change your password immediately (password aged)
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-1052-azure x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud
8 packages can be updated.
0 updates are security updates.
New release '18.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.
*** System restart required ***
Last login: Tue Aug 27 17:52:36 2019 from 10.20.74.4
WARNING: Your password has expired.
You must change your password now and login again!
Changing password for azureuser.
(current) UNIX password:

**Comment by martin2176** [comment]
The important point here is, when an AKS cluster is built, the nodes are built with a random password which is secure because no one knows what the password is. Once the password expires and the customer is asked to reset the password, it becomes a security concern at that time, because now we have to worry about making sure the password meet guidelines, as well as since the password is a known password we have to safely securely store it which beats the whole point of password less ssh key based login. In my opinion the best password is a random unknown password. Hence I think for security sake , I would like to see the random unknown password is set to never expire.

**Comment by ayushoo7** [comment]
Please resolver I am facing same issue not able to login via azureuser inspite having azure credentials

**Comment by martin2176** [comment]
Workaround you could hit the reset password on the virtual machine from the azure portal. 
Once password is reset, hit the reset ssh key and use the same ssh public key. 
These two steps will enable you to login to the nodes using password less ssh and be able to sudo -i  so that you can become root on the aks nodes

**Comment by ams0** [comment]
A better approach would be use `nsenter` (as in this [article](https://itnext.io/get-a-shell-to-a-kubernetes-node-9b720a15a4fe). You can copy and `chmod +x` this [gist](https://gist.github.com/ams0/775bb279e8ae0811bf9a1c3b14087582) and run:

```
./nsenter-node <node-name>
```
to gain access to the nodes.

**Comment by martin2176** [comment]
I would not recommend the nsenter approach, at least not on the Clusters I would deploy in production :)
The nsenter-node script basically runs hostPID: true and privileged: true because its required for nsenter to join host name space and run privileged containers for the script to run commands on the host.
A properly secured K8S cluster should have pod security policy admission controller which should deny a privileged container and a container from joining host PID namespace. So technically this script should fail if the cluster is properly secured.
(I understand pod security policy is preview on AKS)

**Comment by martin2176** [comment]
ID# | SE017 |  
-- | -- | --
Topic: |  
Requirement: |  
Constraints: |  
Notes: |

**Comment by bbgobie** [comment]
Just experienced this in a prod cluster, pretty frustrating when you go in to try and troubleshoot.

**Comment by andyzhangx** [comment]
this user should already been fixed in recent new AKS cluster, fixed by: https://github.com/Azure/aks-engine/pull/2661
```
:/# chage -l azureuser
Last password change                                    : May 09, 2020
Password expires                                        : never
Password inactive                                       : never
Account expires                                         : never
Minimum number of days between password change          : 0
Maximum number of days between password change          : 99999
Number of days of warning before password expires       : 7
```

**Comment by srihas619** [comment]
We are hitting this issue as well, how can we deploy this fix in our cluster? do we need to contact support or rebuild our cluster or upgrade our cluster?

**Comment by andyzhangx** [comment]
> We are hitting this issue as well, how can we deploy this fix in our cluster? do we need to contact support or rebuild our cluster or upgrade our cluster?

@srihas619 as I tried, password/key in new node won't expire

**Comment by srihas619** [comment]
@andyzhangx but how can this fix be applied to existing nodes in the cluster? new nodes need 30 days anyway to get to this point

**Comment by andyzhangx** [comment]
@srihas619 on old node, run `chage -E -1 -I -1 -m 0 -M 99999`

**Comment by srihas619** [comment]
@andyzhangx is there a sequence of steps to run this command, like from portal, or privileged pod or something else? since we can't login to node via ssh now.

**Comment by andyzhangx** [comment]
> @andyzhangx is there a sequence of steps to run this command, like from portal, or privileged pod or something else? since we can't login to node via ssh now.

@srihas619 try this:
https://github.com/andyzhangx/demo/tree/master/dev#kubectl-enter

**Comment by srihas619** [comment]
@andyzhangx Thank you, it worked on the existing nodes.
however we had to change line LC_CTYPE to LC_ALL to make kubectl-enter work on our MAC client.

for anyone landing here:
- download `kubectl-enter` https://github.com/andyzhangx/demo/tree/master/dev#kubectl-enter. It spins up a pod that can nsenter
- run `chage -E -1 -I -1 -m 0 -M 99999 <your_az_host_username>`
