### ISSUE TITLE
kube-svc-redirect crashing

### ISSUE THREAD

**Issue by gmacquillin** [Azure/AKS#1176]
**What happened**:
kube-svc-redirect crashing

**What you expected to happen**:
kube-svc-redirect not to crash

**How to reproduce it (as minimally and precisely as possible)**:
Run AKS 1.14.6 with kube-proxy with /run/xtables.lock mount

**Anything else we need to know?**:

Upgraded to 1.14.6 from 1.13.7 over the weekend and everything was fine for a few days until kube-svc-redirector starts to crash with the error 
```
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
```

This error has started since a new revision of the kube-proxy daemonset was rolled out with the release time
```
aks.microsoft.com/release-time: seconds:1566952113 nanos:670380866
```
This version includes the mount changes below.
```
Previous revisions
    Mounts:
      /etc/kubernetes/certs from certificates (ro)
      /var/lib/kubelet from kubeconfig (ro)

Currently running and crashing
    Mounts:
      /etc/kubernetes/certs from certificates (ro)
      /run/xtables.lock from iptableslock (rw)
      /var/lib/kubelet from kubeconfig (ro)
```
Looking back as far as I can in the revision history the deployment on 28th is the first I've had with the /run/extables.lock mount

Comparing the logs between kube-svc-redirect and kube-proxy show kube-svc-redirect crashing when kube-proxy is updating iptables. kube-proxy never crashes but after a few hours both apps seem to be completely torn down and brought up again

I've tried rolling back the kube-proxy daemonset but its automatically pushed back to the latests so I've not been able to test if this fixes it

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.6
- Size of cluster (how many worker nodes are in the cluster?) 12
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by MoergJ** [comment]
Same for me, kube-svc-redirect pods keep crashing.
Daemonset's redirector doesn't even have mounts, only azureproxy:
```
Mounts:
      /etc/nginx/certs from azureproxy-certs (ro)
      /etc/nginx/conf.d from azureproxy-configs (ro)
      /etc/nginx/nginx.conf from azureproxy-nginx (ro,path="nginx.conf")
```

**Comment by jnoller** [comment]
engineering is working on a hotfix for this issue, marking as known

**Comment by NN-BT** [comment]
@jnoller  thanks for the response, is there an ETA for the hotfix?

**Comment by gmacquillin** [comment]
We've had new revisions of kube-proxy and kube-svc-redirect daemonsets applied this morning which seems to have fixed the problem. Both have been up without crashing for around 10 hours so far and no sign of the xtables error

Thanks for the fix

**Comment by rivetmichael** [comment]
@gmacquillin  can you give the version of the image that was deployed ? Our is aksrepos.azurecr.io/prod/kube-svc-redirect:v1.0.3 and still seems to be buggy.

**Comment by gmacquillin** [comment]
@rivetmichael Our version of kube-svc-redirect is the same - aksrepos.azurecr.io/prod/kube-svc-redirect:v1.0.3

Has your kube-svc-redirect/kube-proxy been updated? Maybe its rolling out overtime. Our cluster is in UK South

On kube-proxy under annotations the new release time is below. kube-svc-redirect doesn't have that field but I can see the revision change in daemonset history and prometheus
```
aks.microsoft.com/release-time: seconds:1567120643 nanos:621720703
```

**Comment by MoergJ** [comment]
For me, the still failing version is also
`aksrepos.azurecr.io/prod/kube-svc-redirect:v1.0.3`
With release-time
`aks.microsoft.com/release-time: seconds:1567128905 nanos:727484074`
Cluster living in westeurope, looking forward to the fix.

**Comment by rivetmichael** [comment]
`aks.microsoft.com/release-time:  
seconds:1567151801 nanos:852873816` with a cluster in westeurope and still failing, thanks @gmacquillin for the tip about the annotations 👌

**Comment by jorgeperona** [comment]
Hi, our release time is aks.microsoft.com/release-time: seconds:1567126598 nanos:648735775 and redirect version is v1.0.3 and we still have the issue.

Can we force a daemonset update?

What is the patch version or patch release time?

**Comment by rivetmichael** [comment]
@jorgeperona I don't think we can force the update, that part should be managed by Azure

**Comment by jnoller** [comment]
The fix is landing in all regions which is why some are patched and some are not, we release into each region after the previous is validated. It takes over 24 hours for it to land in all regions

**Comment by rivetmichael** [comment]
@jnoller is there a status page or something where we can follow by ourself ?

**Comment by nicolas-marcq** [comment]
Hi,
We are facing the same issue.
What is the procedure to follow to get our cluster back to functional?
Thanks

**Comment by ellispritchard** [comment]
Is this related:

```
kube-system   kube-svc-redirect-qj45x    1/2     CrashLoopBackOff   6          6m9s    10.10.9.66    aks-default-18092711-0   <none>
```

```
 $ kubectl logs kube-svc-redirect-qj45x -n kube-system
Error from server (BadRequest): a container name must be specified for pod kube-svc-redirect-qj45x, choose one of: [redirector azureproxy]
```

Image is `aksrepos.azurecr.io/prod/kube-svc-redirect:v1.0.3`

```
Events:
  Type     Reason     Age                  From                             Message
  ----     ------     ----                 ----                             -------
  Normal   Scheduled  11m                  default-scheduler                Successfully assigned kube-system/kube-svc-redirect-qj45x to aks-default-xxx-0
  Normal   Pulled     11m                  kubelet, aks-default-xxx-0  Container image "aksrepos.azurecr.io/mirror/nginx:1.13.12-alpine" already present on machine
  Normal   Created    11m                  kubelet, aks-default-xxx-0  Created container
  Normal   Started    11m                  kubelet, aks-default-xxx-0  Started container
  Normal   Pulled     9m55s (x5 over 11m)  kubelet, aks-default-xxx-0  Container image "aksrepos.azurecr.io/prod/kube-svc-redirect:v1.0.3" already present on machine
  Normal   Created    9m55s (x5 over 11m)  kubelet, aks-default-xxx-0  Created container
  Normal   Started    9m55s (x5 over 11m)  kubelet, aks-default-xxx-0  Started container
  Warning  BackOff    82s (x48 over 11m)   kubelet, aks-default-xxx-0  Back-off restarting failed container
```

**Comment by jnoller** [comment]
fixed/verified all regions
