### ISSUE TITLE
Log Analytics data missing container image etc.

### ISSUE THREAD

**Issue by artisticcheese** [Azure/AKS#1177]
**What happened**:
Log Analytics data does not contain information about image name, tag etc

**What you expected to happen**:
Log Analytics shall have that data

**How to reproduce it (as minimally and precisely as possible)**:
Upon container start up certain data is not being sent to LogAnalytics

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/13176884/63963993-bdffbf80-ca5b-11e9-93bd-60e3d9b9b8ae.png)

**Environment**:
- Kubernetes version (use `kubectl version`):
1.14.3
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
.NET core microservice
- Others:

**Comment by hameno** [comment]
Same issue here, missing all relevant data needed to filter.

**Comment by bhicks329** [comment]
This is a planned change to container insights (although not well communicated). It’s duplicate information and has been dropped to save on log size.

**Comment by hameno** [comment]
@bhicks329  And where do we get this information now? How do we filter our logs for those informations? I couldn't find any column for that?

**Comment by bhicks329** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-faq#i-dont-see-image-and-name-property-values-populated-when-i-query-the-containerlog-table

**Comment by bhicks329** [comment]
It may seem like a pain at first but when your log analytics workspace costs more than your cluster, it makes sense 😉

**Comment by bragi92** [comment]
@hameno @artisticcheese There is an option to enable the tags again if you haven't looked at this already.

https://docs.microsoft.com/en-us/azure/azure-monitor/faq#option-2
