### ISSUE TITLE
Dashboard does not show cpu/memory metrics after upgrade to version 1.14.6

### ISSUE THREAD

**Issue by mvacha** [Azure/AKS#1178]
**What happened**:
After updating cluster to version 1.14.6 the CPU/memory metrics no longer show up in the Kubernetes dashboard.

This issue has been already reported as #1089, but it is still present in the latest version (1.14.6).

**Solution:**
There are two possible solutions: either install heapster (as suggested in #1089) or update Kubernetes dashboard to the latest version (2.0 beta 4).

**Comment by Eneuman** [comment]
Now that 1.11 and 1.12 is coming to EOL (https://github.com/Azure/AKS/issues/1235) will this be fixed in 1.15?

**Comment by jluk** [comment]
This should be resolved now as the dashboard image used by AKS has been updated, closing as a result but just leave a comment if it is still occurring.
