### ISSUE TITLE
Azure CLI requires Owner on subscription when creating cluster with advanced networking, while Azure Portal does not.

### ISSUE THREAD

**Issue by whut** [Azure/AKS#1180]
**What happened**:
When I create cluster with Azure CLI with `--network-plugin azure` I get:

```
Could not create a role assignment for subnet. Are you an Owner on this subscription?
```

This is basically the same issue as in closed #614. Like noted in comments in that issue, it should not be required to be an Owner on subscription to create AKS cluster.

1. It is not technically mandatory to be Owner on subscription:
   - it is enough to be Owner on the Virtual Network to be able to add Network Contributor rights on the default subnet to the service principal
   - also I believe that "Application administrator" in AAD is enough to create service principals
   - not to mention that in reality not even that full role is needed, only some particular permission
2. When creating cluster from Azure Portal being an Owner on subscription is not required. This means that this is Azure CLI limitation
3. On the other hand this is unrealistic to require Owner on whole subscription just to be able to create AKS cluster.

**What you expected to happen**:

Azure CLI should be able to create AKS cluster with "advanced networking" without requiring Owner on subscription. 

Basically this should work when run under account with is not Owner on subscription:

**How to reproduce it (as minimally and precisely as possible)**:

Run this:

```powershell
        az aks create `
            --name $aksName `
            --resource-group $resourceGroupName `
            --network-plugin azure `
            --vnet-subnet-id $defaultSubnetId
```

**Workaround**

Here is our lengthy workaround:

```powershell
$servicePrincipal = az ad sp create-for-rbac --skip-assignment --name "$aksName-sp"
# Hopefully below is enough to wait for AAD to propagate new service principal, but do not know...
do {
    az ad sp show --id $servicePrincipal.appId | Out-Null
} while ($LASTEXITCODE -ne 0)
az role assignment create --role "Network Contributor" --assignee $servicePrincipal.appId --scope $defaultSubnetId
az aks create `
    --name $aksName `
    --resource-group $resourceGroupName `
    --network-plugin azure `
    --vnet-subnet-id $defaultSubnetId `
    --service-principal $servicePrincipal.appId `
    --client-secret $servicePrincipal.password
```

**Comment by iharrington** [comment]
I added "Network Contributor" role to my Service Principal and I still get the warning/error.

**Comment by griffinator76** [comment]
I am getting the same error trying to update an existing cluster to attach an ACR:
```
az aks update --name nathan1 --resource-group nathan --attach-acr /subscriptions/<id>/resourceGroups/nathan/providers/Microsoft.ContainerRegistry/registries/nathandfdc
```
generates the error
```
Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for ACR. Are you an Owner on this subscription?
```
I have the "global admin" role.

**Comment by AlexanderViken** [comment]
Im having the same issue now as a AAD global administrator and subscription owner... any update?

Waiting for AAD role to propagate[################################ ] 90.0000%Could not create a role assignment for subnet. Are you an Owner on this subscription?
Waiting for AAD role to propagate[################################ ] 90.0000%Could not create a role assignment for ACR. Are you an Owner on this subscription?

when calling with:
`az aks create -g $aksrg -n $aks --attach-acr $registry --network-plugin azure --vnet-subnet-id $akssnid --service-cidr $aks_srv_cidr --dns-service-ip $aks_srv_dns --enable-addons monitoring --workspace-resource-id $logworkspaceid --node-vm-size Standard_A2_v2 --nodepool-name "a2v2node" --network-policy azure --aad-server-app-id $serverApplicationId --aad-server-app-secret $serverApplicationSecret --aad-client-app-id $clientApplicationId --aad-tenant-id $tenantId --generate-ssh-keys --admin-username pciaksadmin`

**Comment by TomGeske** [comment]
Your SP should have Network Contributor permissions for your custom VNET granted prior cluster creation.

**Comment by whut** [comment]
> Your SP should have Network Contributor permissions for your custom VNET granted prior cluster creation.

Yes, this is exactly what the workaround in initial report do:) The point is that Azure CLI should not require Owner. The workaround proves it - I was able to create role assignment without being an Owner on the whole subscription, I just had to be Owner on the vnet.

In short Azure CLI should not check if someone is Owner on subscription, nor even check if someone is Owner on VNet (as I could create some custom permission scheme with different names), instead it should try to create role assignment and report any failures if it is impossible.

**Comment by TomGeske** [comment]
@whut: I've been able to reproduce this. We will investigate and come back.

+@norshtein

**Comment by TomGeske** [comment]
related to #1517

**Comment by TomGeske** [comment]
@whut: We tried to repro today, and it worked fine. Can you retry? 

We used:
```
{
  "azure-cli": "2.11.1",
  "azure-cli-core": "2.11.1",
  "azure-cli-telemetry": "1.0.5",
  "extensions": {
    "aks-preview": "0.4.61",
    "dev-spaces": "1.0.5"
  }
}
```
az aks update -g <cluster-rg>-RG -n <cluster-name> --attach-acr <acr-resource-id>

The user performing az aks update command needs at least [User Access Administrator] role on ACR (https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#user-access-administrator)

One thing we noticed is changing permission on Azure resources doesn't get reflected immediately into az cli because token refreshes only every 60 minutes. We forced refresh by removing .azure/accessTokens.json file.
