### ISSUE TITLE
Network Load Balancer (TCP) poor use case for HTTP routing

### ISSUE THREAD

**Issue by Plasma** [Azure/AKS#1183]
**What happened**:
I created a LoadBalancer service to point to a deployment that had a few replicas of a web server pod (IIS).

This worked fine, but during rolling update, there was a moment where the replica being updated was still serving traffic due to TCP connections by web clients (via their web browser) to that replica. This caused site errors to the end users.

**What you expected to happen**:
This not to happen. Instead, I wish Azure supplied a Http Load Balancer (like Amazon and Google) so that HTTP requests entering the cluster are _properly_ round-robin'd between pods, _and_ when a pod is terminating, eg due to upgrade, that it would not receive any HTTP traffic, because the HTTP load balancer is smarter than the Network Load Balancer, and won't be routing individual HTTP request to terminating pods.

**How to reproduce it (as minimally and precisely as possible)**:
Start a simple hello-world web based deployment, with 3 replicas.

Perform a rolling update. While deploying, keep pressing F5 in web browser. Note you may get a HTTP 500 error as you happen to still be connected to a pod that is being terminated.

**Anything else we need to know?**:
This is a fatal flaw of the LoadBalancer not being HTTP aware. Are Azure planning to provide a native HTTP(s) load balancer so these issues do not occur?

Thank you

**Comment by TomGeske** [comment]
@Plasma: You could use an ingress controller and setup [liveness readiness startup probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
