### ISSUE TITLE
kube-reserved cpu/memory are not set for newly added nodepool

### ISSUE THREAD

**Issue by henrylilei** [Azure/AKS#1185]
**What happened**:
Have a VMSS based Multi nodepool cluster and when adding new nodepool, the kubelet config doesn't have "--kube-reserved=cpu=109m,memory=9543Mi". The main nodepool that created with the cluster has it.

**What you expected to happen**:
1. in the new pool, --kube-reserved=cpu=109m,memory=9543Mi is set inside the /etc/default/kubelet
2. in the main pool, the memory reserved (9543Mi) is a bit too high (was 560Mi in a D14v2 cluster)

**How to reproduce it (as minimally and precisely as possible)**:
Add a new nodepool and check out the kubelet config

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.6
- Size of cluster (how many worker nodes are in the cluster?) 2
- EastAsia/D16s_v3

**Comment by seanmck** [comment]
Thanks for reporting this. We are working on a fix.

**Comment by jluk** [comment]
This fix is being rolled out on this week's release. Closing.

https://github.com/Azure/AKS/releases/tag/2019-10-07
