### ISSUE TITLE
HTTP application routing creates DNS zones for default namespace only

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/AKS#1186]
**What happened**: I was using [the HTTP application routing walkthrough](https://docs.microsoft.com/en-gb/azure/aks/http-application-routing) to get started with it but noticed that traffic was not routed correctly.

When looking at the created DNS zone I noticed that it mentions `external-dns/owner=default`:
![image](https://user-images.githubusercontent.com/4345663/64165843-21b42f00-ce46-11e9-9dd5-c0304da6e3fc.png)

However, the ingress was deployed in `xxx-dev` along with our services:
![image](https://user-images.githubusercontent.com/4345663/64165895-3d1f3a00-ce46-11e9-8227-1131725675e8.png)

Is there a specific annotation that should be included? One would assume it automatically detects the namespace of the ingress and uses that?

**What you expected to happen**:
Successfully consume services for our pods in the deployed namespace.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy ingress to any namespace other than `default`
2. Traffic will not be routed

**Anything else we need to know?**:
- Changing the DNS zone manually to `external-dns/owner=xxx-dev` fixes the problem

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.6
- Size of cluster (how many worker nodes are in the cluster?) 3

**Comment by TomGeske** [comment]
Should be fixed in the meantime. I'm going to close this issue. 

Feel free to keep commenting if you still see this issue.
