### ISSUE TITLE
Deployment fails with "Pod sandbox changed, it will be killed and re-created" on windows nodes

### ISSUE THREAD

**Issue by hallgeirl** [Azure/AKS#1188]
**What happened**:
Newly deployed pods fail with "Pod sandbox changed, it will be killed and re-created.". This happens on at least two of my nodes that I've seen so far. Also, right after the pod is created, the readiness probe fails with: **container 70b25a2888a40baf46aea4dcc8fa2675abc9a23bb797726bdf175c8fabfea7c4 encountered an error during CreateProcess: failure in a Windows system call: The requested virtual machine or container operation is not valid in the current state. (0xc0370105) **

All current pods keep running fine, however! So this seems to be an issue only on new pod deployments.

**What you expected to happen**:
I expect the pods to start.

**How to reproduce it (as minimally and precisely as possible)**:
Not really sure... this just started happening on a cluster that we have had running for a while. I did try restarting the nodes.

**Anything else we need to know?**:
The cluster has run fine for a long time. Then suddenly, yesterday, new deployments started to fail. We run a readiness probe as well on the pods, that report an error as soon as the pod is created. I've attached the full output of kubectl describe pod below.

`
Name:           app-360-e7624062-c985-484d-b127-054f417234b0-3567-649db45b99gct
Namespace:      e7624062-c985-484d-b127-054f417234b0
Priority:       0
Node:           akswinpol000004/10.240.0.97
Start Time:     Wed, 04 Sep 2019 07:42:56 +0200
Labels:         app=app-360-e7624062-c985-484d-b127-054f417234b0-3567
                pod-template-hash=649db45b54
Annotations:    <none>
Status:         Running
IP:
Controlled By:  ReplicaSet/app-360-e7624062-c985-484d-b127-054f417234b0-3567-649db45b54
Containers:
  app-360:
    Container ID:   docker://2b28b9ceed3ac34c754083a279aaf243c8db7e27daff3c22dfd426fe47c1ff22
    Image:          sicoredevcontainers.azurecr.io/360:52578
    Image ID:       docker-pullable://sicoredevcontainers.azurecr.io/360@sha256:49d4e00556fe0c515c365f4f14e4d144536e78960f2687b2dfe6e539fcaa522e
    Port:           81/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    -1073741510
      Started:      Wed, 04 Sep 2019 07:55:10 +0200
      Finished:     Wed, 04 Sep 2019 07:55:14 +0200
    Ready:          False
    Restart Count:  10
    Requests:
      cpu:      200m
    Readiness:  exec [powershell if(test-path 'c:\ContainerConfigured.tag'){return 0}else{throw}] delay=1s timeout=1s period=30s #success=2 #failure=3
    Environment:
      CONFIG_URL:               ******
      CONFIG_USER:              *******
      CONFIG_PASSWORD:          *****
      sicc.instrumentationkey:  *****
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8l9xw (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-8l9xw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-8l9xw
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=windows
                 kubernetes.io/role=agent
Tolerations:     key:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From                      Message
  ----     ------     ----                  ----                      -------
  Normal   Scheduled  13m                   default-scheduler         Successfully assigned e7624062-c985-484d-b127-054f417234b0/app-360-e7624062-c985-484d-b127-054f417234b0-3567-649db45b99gct to akswinpol000004
  Warning  Unhealthy  13m                   kubelet, akswinpol000004  Readiness probe failed: container 70b25a2888a40baf46aea4dcc8fa2675abc9a23bb797726bdf175c8fabfea7c4 encountered an error during CreateProcess: failure in a Windows system call: The requested virtual machine or container operation is not valid in the current state. (0xc0370105) extra info: {"CommandLine":"powershell \"if(test-path 'c:\\ContainerConfigured.tag'){return 0}else{throw}\"","WorkingDirectory":"/","Environment":{"APP_360_E7624062_C985_484D_B127_054F417234B0_3520_PORT":"tcp://10.0.181.201:81","APP_360_E7624062_C985_484D_B127_054F417234B0_3520_PORT_81_TCP":"tcp://10.0.181.201:81","APP_360_E7624062_C985_484D_B127_054F417234B0_3520_PORT_81_TCP_ADDR":"10.0.181.201","APP_360_E7624062_C985_484D_B127_054F417234B0_3520_PORT_81_TCP_PORT":"81","APP_360_E7624062_C985_484D_B127_054F417234B0_3520_PORT_81_TCP_PROTO":"tcp","APP_360_E7624062_C985_484D_B127_054F417234B0_3520_SERVICE_HOST":"10.0.181.201","APP_360_E7624062_C985_484D_B127_054F417234B0_3520_SERVICE_PORT":"81","APP_360_E7624062_C985_484D_B127_054F417234B0_3523_PORT":"tcp://10.0.12.157:81","APP_360_E7624062_C985_484D_B127_054F417234B0_3523_PORT_81_TCP":"tcp://10.0.12.157:81","APP_360_E7624062_C985_484D_B127_054F417234B0_3523_PORT_81_TCP_ADDR":"10.0.12.157","APP_360_E7624062_C985_484D_B127_054F417234B0_3523_PORT_81_TCP_PORT":"81","APP_360_E7624062_C985_484D_B127_054F417234B0_3523_PORT_81_TCP_PROTO":"tcp","APP_360_E7624062_C985_484D_B127_054F417234B0_3523_SERVICE_HOST":"10.0.12.157","APP_360_E7624062_C985_484D_B127_054F417234B0_3523_SERVICE_PORT":"81","APP_360_E7624062_C985_484D_B127_054F417234B0_3533_PORT":"tcp://10.0.32.13:81","APP_360_E7624062_C985_484D_B127_054F417234B0_3533_PORT_81_TCP":"tcp://10.0.32.13:81","APP_360_E7624062_C985_484D_B127_054F417234B0_3533_PORT_81_TCP_ADDR":"10.0.32.13","APP_360_E7624062_C985_484D_B127_054F417234B0_3533_PORT_81_TCP_PORT":"81","APP_360_E7624062_C985_484D_B127_054F417234B0_3533_PORT_81_TCP_PROTO":"tcp","APP_360_E7624062_C985_484D_B127_054F417234B0_3533_SERVICE_HOST":"10.0.32.13","APP_360_E7624062_C985_484D_B127_054F417234B0_3533_SERVICE_PORT":"81","APP_360_E7624062_C985_484D_B127_054F417234B0_3536_PORT":"tcp://10.0.74.12:81","APP_360_E7624062_C985_484D_B127_054F417234B0_3536_PORT_81_TCP":"tcp://10.0.74.12:81","APP_360_E7624062_C985_484D_B127_054F417234B0_3536_PORT_81_TCP_ADDR":"10.0.74.12","APP_360_E7624062_C985_484D_B127_054F417234B0_3536_PORT_81_TCP_PORT":"81","APP_360_E7624062_C985_484D_B127_054F417234B0_3536_PORT_81_TCP_PROTO":"tcp","APP_360_E7624062_C985_484D_B127_054F417234B0_3536_SERVICE_HOST":"10.0.74.12","APP_360_E7624062_C985_484D_B127_054F417234B0_3536_SERVICE_PORT":"81","APP_360_E7624062_C985_484D_B127_054F417234B0_3542_PORT":"tcp://10.0.182.216:81","APP_360_E7624062_C985_484D_B127_054F417234B0_3542_PORT_81_TCP":"tcp://10.0.182.216:81","APP_360_E7624062_C985_484D_B127_054F417234B0_3542_PORT_81_TCP_ADDR":"10.0.182.216","APP_360_E7624062_C985_484D_B127_054F417234B0_3542_PORT_81_TCP_PORT":"81","APP_360_E7624062_C985_484D_B127_054F417234B0_3542_PORT_81_TCP_PROTO":"tcp","APP_360_E7624062_C985_484D_B127_054F417234B0_3542_SERVICE_HOST":"10.0.182.216","APP_360_E7624062_C985_484D_B127_054F417234B0_3542_SERVICE_PORT":"81","APP_360_E7624062_C985_484D_B127_054F417234B0_3559_PORT":"tcp://10.0.174.124:81","APP_360_E7624062_C985_484D_B127_054F417234B0_3559_PORT_81_TCP":"tcp://10.0.174.124:81","APP_360_E7624062_C985_484D_B127_054F417234B0_3559_PORT_81_TCP_ADDR":"10.0.174.124","APP_360_E7624062_C985_484D_B127_054F417234B0_3559_PORT_81_TCP_PORT":"81","APP_360_E7624062_C985_484D_B127_054F417234B0_3559_PORT_81_TCP_PROTO":"tcp","APP_360_E7624062_C985_484D_B127_054F417234B0_3559_SERVICE_HOST":"10.0.174.124","APP_360_E7624062_C985_484D_B127_054F417234B0_3559_SERVICE_PORT":"81","APP_360_E7624062_C985_484D_B127_054F417234B0_3567_PORT":"tcp://10.0.191.58:81","APP_360_E7624062_C985_484D_B127_054F417234B0_3567_PORT_81_TCP":"tcp://10.0.191.58:81","APP_360_E7624062_C985_484D_B127_054F417234B0_3567_PORT_81_TCP_ADDR":"10.0.191.58","APP_360_E7624062_C985_484D_B127_054F417234B0_3567_PORT_81_TCP_PORT":"81","APP_360_E7624062_C985_484D_B127_054F417234B0_3567_PORT_81_TCP_PROTO":"tcp","APP_360_E7624062_C985_484D_B127_054F417234B0_3567_SERVICE_HOST":"10.0.191.58","APP_360_E7624062_C985_484D_B127_054F417234B0_3567_SERVICE_PORT":"81","COMPLUS_NGenProtectedProcess_FeatureEnabled":"0","CONFIG_PASSWORD":"*******","CONFIG_URL":"*******","CONFIG_USER":"*****","KUBERNETES_PORT":"tcp://10.0.0.1:443","KUBERNETES_PORT_443_TCP":"tcp://10.0.0.1:443","KUBERNETES_PORT_443_TCP_ADDR":"10.0.0.1","KUBERNETES_PORT_443_TCP_PORT":"443","KUBERNETES_PORT_443_TCP_PROTO":"tcp","KUBERNETES_SERVICE_HOST":"10.0.0.1","KUBERNETES_SERVICE_PORT":"443","KUBERNETES_SERVICE_PORT_HTTPS":"443","REDISSVC_E7624062_C985_484D_B127_054F417234B0_PORT":"tcp://10.0.205.211:6379","REDISSVC_E7624062_C985_484D_B127_054F417234B0_PORT_6379_TCP":"tcp://10.0.205.211:6379","REDISSVC_E7624062_C985_484D_B127_054F417234B0_PORT_6379_TCP_ADDR":"10.0.205.211","REDISSVC_E7624062_C985_484D_B127_054F417234B0_PORT_6379_TCP_PORT":"6379","REDISSVC_E7624062_C985_484D_B127_054F417234B0_PORT_6379_TCP_PROTO":"tcp","REDISSVC_E7624062_C985_484D_B127_054F417234B0_SERVICE_HOST":"10.0.205.211","REDISSVC_E7624062_C985_484D_B127_054F417234B0_SERVICE_PORT":"6379","ROSLYN_COMPILER_LOCATION":"c:\\\\RoslynCompilers\\\\tools","sicc.instrumentationkey":"******"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
  Normal   Pulling    12m (x4 over 13m)     kubelet, akswinpol000004  Pulling image "sicoredevcontainers.azurecr.io/360:52578"
  Normal   Pulled     12m (x4 over 13m)     kubelet, akswinpol000004  Successfully pulled image "sicoredevcontainers.azurecr.io/360:52578"
  Normal   Created    12m (x4 over 13m)     kubelet, akswinpol000004  Created container app-360
  Normal   Started    12m (x4 over 13m)     kubelet, akswinpol000004  Started container app-360
  Normal   Killing    3m26s (x74 over 13m)  kubelet, akswinpol000004  Pod sandbox changed, it will be killed and re-created.
`

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
- Size of cluster (how many worker nodes are in the cluster?): 3 windows nodes, 2 linux nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): IIS applications on windows nodes, Redis on linux nodes
- Others:

**Comment by blackbaud-brandonstirnaman** [comment]
We've been seeing this in our Australian clusters since yesterday (and opened a Sev-B issue with MS support).. Now seeing it in clusters in EastUS2, CentralUS and in our european regions as of ~3AM eastern today.

**Comment by hallgeirl** [comment]
> We've been seeing this in our Australian clusters since yesterday (and opened a Sev-B issue with MS support).. Now seeing it in clusters in EastUS2, CentralUS and in our european regions as of ~3AM eastern today. Sev-A issue open now but apparently difficult to locate Kubernetes engineers to dig in.
> 
> Pretty much took down most of our services due to aligning with kured rebooting the nodes.

Thanks for confirming that it's not only me! :)

I would love to hear what an eventual support engineer says about this issue, if you get any useful feedback on it...

**Comment by piostelmach** [comment]
Hi,
we have also the same problem, additionally node's show state not ready and few sec show ready. In this time pod are restarted.

aks ver. 1.13.5, cluster on westeurope and northeurope.
kernel version: 4.15.0-1052-azure
container-runtime: docker://3.0.6
os-image: Ubuntu 16.04.6 LTS

**Comment by slynickel** [comment]
Adding a bit more of what we are seeing. We aren't using windows nodes. Not sure if others are seeing that the agent nodes are rebooting nearly every 5-10 minutes. We only have a two node cluster and the issue is limited to just one of the two agent nodes.

Quick command to see if you seeing a lot of reboots (requires linux for the grep bit):
```
$ kubectl get events --field-selector involvedObject.kind=Node --sort-by='{.lastTimestamp}' | grep reboot
56m         Warning   Rebooted                  Node   Node <REDACTED agentName>-1 has been rebooted, boot id: <REDACTED GUID>
51m         Warning   Rebooted                  Node   Node <REDACTED agentName>-1 has been rebooted, boot id: <REDACTED GUID>
46m         Warning   Rebooted                  Node   Node <REDACTED agentName>-1 has been rebooted, boot id: <REDACTED GUID>
41m         Warning   Rebooted                  Node   Node <REDACTED agentName>-1 has been rebooted, boot id: <REDACTED GUID>
36m         Warning   Rebooted                  Node   Node <REDACTED agentName>-1 has been rebooted, boot id: <REDACTED GUID>
31m         Warning   Rebooted                  Node   Node <REDACTED agentName>-1 has been rebooted, boot id: <REDACTED GUID>
26m         Warning   Rebooted                  Node   Node <REDACTED agentName>-1 has been rebooted, boot id: <REDACTED GUID>
21m         Warning   Rebooted                  Node   Node <REDACTED agentName>-1 has been rebooted, boot id: <REDACTED GUID>
15m         Warning   Rebooted                  Node   Node <REDACTED agentName>-1 has been rebooted, boot id: <REDACTED GUID>
11m         Warning   Rebooted                  Node   Node <REDACTED agentName>-1 has been rebooted, boot id: <REDACTED GUID>
6m11s       Warning   Rebooted                  Node   Node <REDACTED agentName>-1 has been rebooted, boot id: <REDACTED GUID>
89s         Warning   Rebooted                  Node   Node <REDACTED agentName>-1 has been rebooted, boot id: <REDACTED GUID>
```

We do use kured but these aren't reboots initiated by kured. We see the same sandbox messages above but those would be expected if the server is rebooting constantly.

AKS Version 1.13.10, Kubectl version 1.13.10, Azure region: centralus, 2 node cluster, linux only. We are experiencing this across multiple separate AKS resources.

**Comment by slynickel** [comment]
I think this can be closed. It was fixed for us per https://github.com/Azure/AKS/issues/1204 the reason all there boots were happening was due to the kernel panic.

**Comment by hallgeirl** [comment]
For us this happened on Windows nodes - the referred issue here is for linux nodes. But could it be that the master node also was affected here, thus crashing everything?

**Comment by hallgeirl** [comment]
I'll close this since I haven't seen this issue since last year.
