### ISSUE TITLE
error: You must be logged in to the server (the server has asked for the client to provide credentials (get pods))

### ISSUE THREAD

**Issue by neilpeterson** [Azure/AKS#119]
I am unable to access new clusters, created in the east region, since yesterday evening. The cluster is successfully deployed, I can 'get credentials', however when running any kubeclt command an error similar to following is thrown.

```
error: You must be logged in to the server (the server has asked for the client to provide credentials (get pods))
```

I have a repro on several new clusters across two subscriptions.

I am able to access a cluster in westeurope.

**Comment by neilpeterson** [comment]
I’ve created a new cluster and it is now working, however a cluster created a few hours ago is still experiencing the issue.

For completeness, 4 clusters created between 8:00pm – 9:00am (across two subscriptions) experienced the issue. Cluster created at 11:00 looks ok.

I will close this issue.

**Comment by neilpeterson** [comment]
Opening this back up, I am continuing to hit this issue.

**Comment by neilpeterson** [comment]
This seems to occur when a cluster name is re-used. If I create a cluster with a name that has not recently been used, everything is ok.

**Comment by bergerx** [comment]
could this be related to #185

**Comment by amanohar** [comment]
@neilpeterson can you share your RG and resource name? 

Regarding: 

> This seems to occur when a cluster name is re-used. 

- Did you delete the cluster (verify that it was deleted) before re creating?
- When you created cluster for the first time was enableRBAC set to `false` and when you created it the second time was it set to `true`?
