### ISSUE TITLE
View Kubernetes Dashboard Button in Azure Portal

### ISSUE THREAD

**Issue by AnassKartit** [Azure/AKS#1193]
**What happened**:
Go to Azure Portal after Creating AKS Cluster

**What you expected to happen**:
A View Kubernetes Dashboard Button that allows you to copy AKS get credentials button appears

**How to reproduce it (as minimally and precisely as possible)**:
sometimes it appears sometime not , the issue is random

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
all versions
- Size of cluster (how many worker nodes are in the cluster?)
all sizes

**Comment by robinmanuelthiel** [comment]
Can you confirm, that this is happening randomly? Normal behavior should be the the "View Kubernetes dashboard" button is only visible on clusters with **no RBAC enabled**.

**Comment by philcarbone** [comment]
How do you get it to show with **RBAC enabled**?

**Comment by robinmanuelthiel** [comment]
@philcarbone You can't. With RBAC enabled, the dashboard is only accessible to those, who have the according to rights to do so.

```bash
kubectl create clusterrolebinding kubernetes-dashboard --clusterrole=cluster-admin --serviceaccount=kube-system:kubernetes-dashboard
```

For more information, see: https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard#start-the-kubernetes-dashboard

**Comment by philcarbone** [comment]
Hi @robinmanuelthiel - I do already have the roles setup and the dashboard working. What I'm looking for is a dummy button that will provide our portal users with the commands to access the portal (should they have access). It can be up to the user to know if they have access or not, I'm just looking for one-stop-shopping here. If someone is looking at an AKS resource, it would still be nice to provide the command to open the dashboard. 

`az aks get-credentials --resource-group *** --name ***`
and
`kubectl port-forward kubernetes-dashboard-*** 8080:8080 -n kube-system`

Which then requires authentication

**Comment by AnassKartit** [comment]
> Can you confirm, that this is happening randomly? Normal behavior should be the the "View Kubernetes dashboard" button is only visible on clusters with **no RBAC enabled**.

sometimes I see it I am looking for the button that will show the command az aks get-credentials --resource-group *** --name *** as @philcarbone mentioned too.

> @philcarbone You can't. With RBAC enabled, the dashboard is only accessible to those, who have the according to rights to do so.
> 
> ```shell
> kubectl create clusterrolebinding kubernetes-dashboard --clusterrole=cluster-admin --serviceaccount=kube-system:kubernetes-dashboard
> ```
> 
> For more information, see: https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard#start-the-kubernetes-dashboard



> Can you confirm, that this is happening randomly? Normal behavior should be the the "View Kubernetes dashboard" button is only visible on clusters with **no RBAC enabled**.

by rbac you mean , controlling access using azure ad?
https://docs.microsoft.com/en-us/azure/aks/azure-ad-rbac
setting rbac to true ?

**Comment by AnassKartit** [comment]
> @philcarbone You can't. With RBAC enabled, the dashboard is only accessible to those, who have the according to rights to do so.
> 
> ```shell
> kubectl create clusterrolebinding kubernetes-dashboard --clusterrole=cluster-admin --serviceaccount=kube-system:kubernetes-dashboard
> ```
> 
> For more information, see: https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard#start-the-kubernetes-dashboard

Yes RBAC is enabled, but showing the button or not is not UI consistent and explained , it is a productivity feature.

**Comment by NirajCricket** [comment]
Hi, I am stuck with similar issue, followed all the docs, and have access enabled, still cannot launch dashboard
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

**Comment by palma21** [comment]
AKS is deprecating the kubernetes dashboard due to many issues and introducing that functionality directly in the azure portal.
https://azure.microsoft.com/en-us/updates/kubernetes-resource-view-is-in-public-preview/

The dashboard is deprecated from 1.18+ (but can still be enabled) and will be removed from 1.19+
https://github.com/Azure/AKS/releases/tag/2020-06-01
https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard
