### ISSUE TITLE
Enable users to install Gatekeeper themselves on AKS without Azure Policy feature

### ISSUE THREAD

**Issue by rayanebel** [Azure/AKS#1195]
**What happened**:

I'm working for a company which want to apply security policies on their Kubernetes clusters by using directly [Gatekeeper](https://github.com/open-policy-agent/gatekeeper) _(aka Open Agent Policiy)_. We tried to deploy Gatekeeper by ourselves and it worked but, when we apply our custom policies, they are ignored and it's not working. 

If I don't make a mistake to work, `Gatekeeper` needs 2 admissions controllers: `ValidatingAdmissionWebhook` and `MutatingAdmissionWebhook` which are enabled by default when an AKS cluster is instancied. So normally, it should works by default.

After a discussion with @ritazh and @craiglpeters on slack, we understand that Azure team encounters implementation problems due to the design of AKS.

We know the existence of Azure AKS Policies which use `Gatekeeper` but it's in private preview and with azure features take some times to be available in GA and we can't ask to our customers to enable a `preview feature` on their production subscription. Moreover, we don't want to depend on a special feature for this tool which should works on every kubernetes clusters.

We also don't want to use directly Azure AKS policies because, we worked with several provider and we want a generic solutions like `Gatekeeper`.

As we work with Azure everyday _(contract with microsoft)_, apply this policies are really important for us and the fact that `Gatekeeper` is not working is very blocking for us.

Do you have start a work to be let the user to deploy and use `Gatekeeper` by themselves ? If yes do you know when it's will be available ?

**Comment by jluk** [comment]
Hey @rayanebel I discussed this a bit with Rita last week. Currently there are some AKS design conflicts to users rolling Gatekeeper themselves into the service, we have some proposed work to enable this requested scenario but our current best estimate is next year to get there.

I'll leave this issue here for ongoing tracking, but hopefully this helps your planning.

**Comment by rayanebel** [comment]
Hello @jluk 
Thanks for your reply. It's really a blocking point for us. Do you plan to have a workaround until the problem is solved at the AKS level ?

Thanks.

**Comment by jluk** [comment]
AFAIK the best option would be to use the AKS-Engine project which enables you to design and configure everything: https://github.com/Azure/aks-engine

@ritazh for any other thoughts though

**Comment by rayanebel** [comment]
Hello @jluk,

In our case we can't use AKS-Engine and we can't ask to our customer to enable a preview feature on their production subscription. Maybe, AKS team can find a temporary workaround to repair the webhooks when tunnelfront pod or the node restart ?

When I discussed with @ritazh she try to think to this workaround while waiting for AKS team to correct the problem.

**Comment by ritazh** [comment]
Until Gatekeeper v3 is fully integrated with AKS as a managed feature, today if you want to deploy and manage OPA Gatekeeper v3 in your AKS cluster without hitting the tunnelfront pod restart issue, you can edit the `kube-system` namespace by adding the following label to the namespace: `kubectl edit ns kube-system`

```yaml 
  labels:
    control-plane: controller-manager
```
This namespace label matches the default namespaceSelector as specified in the `validatingwebhookconfiguration`deployed as part of Gatekeeper. As a result, resources within the `kube-system` namespace (e.g. tunnelfront) will be excluded from admission validation by the Gatekeeper webhook.

Hope this helps.

**Comment by jaygridley** [comment]
I've tried workaround that @ritazh suggested, but still could not get it working.

Logs of gatekeeper are full of 
```
http: TLS handshake error from 10.184.216.46:46684: remote error: tls: bad certificate
```
The IP 10.184.216.46 is the tunnelfront.

I am trying this on AKS 1.15.7 with Gatekeeper v3.1.0-beta.4.

Did anyone involved here got GK working on AKS?

**Comment by sozercan** [comment]
@jaygridley I have tested GK v3.1.0-beta.4 running on AKS.

Are you seeing this only on GK pod?

**Comment by jaygridley** [comment]
@sozercan Yes I do. Also the contraints seem to be ignored.

**Comment by sozercan** [comment]
@jaygridley do you mind opening an Azure support ticket for this from your AKS cluster resource? Please mention in the ticket that it is for the Azure upstream team and note the github issue, and let us know the ticket id and we can take a look at your cluster.

**Comment by dubuc** [comment]
Works for me on AKS 1.15 in China and Gatekeeper v3.1.0-beta.4, didn't have to add the `control-plane: controller-manager`, since the kube-system namespace came already with the following labels:

```  
labels:
    addonmanager.kubernetes.io/mode: Reconcile
    control-plane: "true"
    kubernetes.io/cluster-service: "true"
```

**Comment by sozercan** [comment]
@jaygridley looks like your validating webhook configuration and service was renamed. certificates that gatekeper generates automatically have subject for `CN=gatekeeper-webhook-service.gatekeeper-system.svc`. If service is named differently, they won't match so validating webhook won't work.

If you can reinstall GK with default configuration, it should work as expected.

For diagnosing, you can check your control plane api server logs on AKS: https://docs.microsoft.com/en-us/azure/aks/view-master-logs

**Comment by jaygridley** [comment]
@sozercan That was it! I did not think that the name of the Service has a meaning. Excellent. Working smoothly now.
