### ISSUE TITLE
Stuck at "Creating" when specifying Node Taints for the first NodePool

### ISSUE THREAD

**Issue by henrylilei** [Azure/AKS#1196]
**What happened**:
Created a managed cluster with Rest API, set node taints "key=value:NoSchedule" to the first nodepool, and nodepool is stucked at "Creating".

**What you expected to happen**:
First nodepool successfully created.

**How to reproduce it (as minimally and precisely as possible)**:
```
"agentPoolProfiles": [
      {
        "name": "stateful",
        "count": 3,
        "vmSize": "Standard_D16s_v3",
        "osDiskSizeGB": 512,
        "maxPods": 110,
        "type": "VirtualMachineScaleSets",
        "orchestratorVersion": "1.14.6",
        "osType": "Linux",
        "nodeTaints": [
            "stateful=true:NoSchedule"
        ]
      }
    ]
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.6
- Size of cluster (how many worker nodes are in the cluster?) 3

I understand that taint is making some of the pods unschedulable, so the question is can we make Deployments under kube-system tolerate NoSchedules just like the DaemonSets?

**Comment by jluk** [comment]
Thanks for the report @henrylilei we're looking into this.

**Comment by jluk** [comment]
We have a fix rolling out on this week's release

**Comment by jluk** [comment]
@henrylilei this should be fixed on this release: https://github.com/Azure/AKS/releases/tag/2019-09-30

Please try again and let us know if not resolved and I will revisit. Closing for now.
