### ISSUE TITLE
Add Azure Policy alias for checking kubedashboard enabled status

### ISSUE THREAD

**Issue by tdihp** [Azure/AKS#1197]
**What happened**:
Unable to enforce Azure Policy for checking if kubedashboard is disabled

az provider show --expand "resourceTypes/aliases" --query "resourceTypes[].aliases[].name" --namespace Microsoft.ContainerService

In which I found at the addon level we only have:
•	"Microsoft.ContainerService/managedClusters/addonProfiles"
•	"Microsoft.ContainerService/managedClusters/addonProfiles.azurePolicy.enabled"

So no "Microsoft.ContainerService/managedClusters/addonProfiles.kubeDashboard.enabled" to check the dashboard availability.

**What you expected to happen**:

Having "Microsoft.ContainerService/managedClusters/addonProfiles.kubeDashboard.enabled" in the alias list.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ az provider show --expand "resourceTypes/aliases" --query "resourceTypes[].aliases[].name" --namespace Microsoft.ContainerService | grep addon
  "Microsoft.ContainerService/managedClusters/addonProfiles",
  "Microsoft.ContainerService/managedClusters/addonProfiles.azurePolicy.enabled"
```

**Comment by jluk** [comment]
Closing this as no longer on the roadmap given the kube-dashboard addon is set for deprecation. Details can be found here: 
https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard
