### ISSUE TITLE
aks upgrade get's stuck even when successful

### ISSUE THREAD

**Issue by martin-displayr** [Azure/AKS#1202]
**What happened**:
Kubernetes cluster was upgraded, but the tool that upgraded it didn't exit.

**What you expected to happen**:
The upgrade tool should exit and report success/failure.

**How to reproduce it (as minimally and precisely as possible)**:
I typed in this command:
```
az aks upgrade --resource-group rg_xyz --name xyz --kubernetes-version 1.14.6
```
It says
```
Kubernetes may be unavailable during cluster upgrades.
Are you sure you want to perform this operation? (y/n): y
 - Running ..
```
**Anything else we need to know?**:
This happened last time about a month or so ago upgrading to 1.13.9

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
3

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Running Mediawiki

- Others:

**Comment by martin-displayr** [comment]
az --version

```
azure-cli                         2.0.68

command-modules-nspkg               2.0.2
core                              2.0.68
nspkg                              3.0.4
telemetry                          1.0.3
```

**Comment by jluk** [comment]
@eugenestarchenko and @martin-displayr what's the time lag you see between the provisioningstate being updated and the upgrade command completing? There may be a small polling delay between the two but nothing substantial.

**Comment by martin-displayr** [comment]
@jluk the first time it never completed. I left the console open all day, this was about 6 weeks ago. The more recent time (when I opened the ticket), it closed a bit after the ticket, so maybe 30 minutes in total for that time.

The question is what was it doing between the services being up again and the program exiting. If it is doing housekeeping stuff or whatever, some progress information would be nice. 

Especially as when we are doing these upgrades, there is some downtime, and I want to confidently tell everyone "upgrade is done". Or "another 10 minutes to go", etc.

**Comment by jluk** [comment]
@martin-displayr could you shared the ticket # or open a new one? We'd like to take a look at the specific operation which requires your subID and a timestamp which we should share in a private forum.

**Comment by jluk** [comment]
I'm going to close this issue in favor of a support ticket - I've validated there is no known operation that should cause lag like this so we would need a specific support ticket so we can capture operationIDs from your subscription. Please do submit one if you hit this issue.
