### ISSUE TITLE
Kubernetes API change: User action required - removal of extensions/v1beta1, apps/v1beta1, apps/v1beta2 APIs in 1.16

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#1205]
In the Kubernetes 1.15.0 and 1.14.0 ([release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#deprecations-and-removals)) the upstream team [set final dates](https://groups.google.com/forum/#!topic/kubernetes-dev/je0rjyfTVyc/discussion) for the previously planned removal of the extensions/v1beta1, apps/v1beta1, apps/v1beta2 APIs in Kubernetes 1.16.0: 

- NetworkPolicy resources will no longer be served from extensions/v1beta1 by default in v1.16. 
  - Migrate to the networking.k8s.io/v1 API, available since v1.8. Existing persisted data can be retrieved/updated via the networking.k8s.io/v1 API.
- PodSecurityPolicy resources will no longer be served from extensions/v1beta1 by default in v1.16. 
  - Migrate to the policy/v1beta1 API, available since v1.10. Existing persisted data can be retrieved/updated via the policy/v1beta1 API.
- DaemonSet, Deployment, StatefulSet, and ReplicaSet resources will no longer be served from extensions/v1beta1, apps/v1beta1, or apps/v1beta2 by default in v1.16. 
  - Migrate to the apps/v1 API, available since v1.9. Existing persisted data can be retrieved/updated via the apps/v1 API.

These API removals require users to modify their Kubernetes deployments, CI systems, operators - any caller to those APIs. 

If customers *do not update these APIs* prior to upgrading to 1.16, their workloads will fail after the upgrade is complete.

All replacement APIs are in Kubernetes versions above 1.10 - this means customers can install any supported version of Kubernetes and begin using the updated APIs now.

For all info:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#deprecations-and-removals

**Comment by jluk** [comment]
Also sharing the upstream blog from 7/19 for more information which also notes the planned v1.20 deprecation for Ingress (in the extensions/v1beta1 API group).
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

K8s API deprecation policy below.
https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api

**Comment by pptfz** [comment]
Kubeamd install kubernets1.17.4 helm2.16.3
Helm install stable/nginx-ingress --set controller.hostnetwork =true, rbac.create=true
Error: validation failed: spotted to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

Say You just need change Deployment and StatefuSet apiVersion to apiVersion: apps/v1.
How exactly? 
I followed the helm install command but didn't download the nginx-ingress package, and I don't know where to change it

**Comment by pptfz** [comment]
@coreywagehoft
i have identified the need to change the apiVersion to apps/v1
I implemented the helm fetch stable/nginx-ingress and downloaded a nginx-ingress.tgz package. After unzipping, I modified the apiversion in the deployment. Yaml file
I just don't know how to apply my locally modified files
For example, how do I specify the application of my local files when I perform helm install

Because if it is not specified, helm install will still use the default online warehouse. I want to specify the file that I modify locally

**Comment by coreywagehoft** [comment]
@pptfz Check out the public Helm documentation.  Specifically this link.  It gives you options on how to install a chart from your local machine.

https://helm.sh/docs/intro/using_helm/#more-installation-methods

**Comment by pptfz** [comment]
@coreywagehoft 
Ok, I will have a careful look at this document, thank you very much for your reply, thank you

**Comment by mleneveut** [comment]
I migrated 3 clusters from 1.15.5 to 1.16.7, the 3 are working fine, but on 2 of them when I do a :

```
kubectl get deploy
```

I got a : `Error from server (NotFound): Unable to list "extensions/v1beta1, Resource=deployments": the server could not find the requested resource`

I checked all deployements, daemonSets, ... and all are in apps/v1.

When I do `kubectl api-resources --verbs=list -o name` I see on the 2 clusters having the error : 

```
daemonsets.extensions
deployments.extensions
ingresses.extensions
networkpolicies.extensions
podsecuritypolicies.extensions
```

What could cause this ?

Thanks for your help.

**Comment by palma21** [comment]
Do you happen to have a support ticket on this that we can take a look at? (so we know your cluster details etc.)

**Comment by mleneveut** [comment]
@palma21  Thanks for your answer. Here is the ticket number : 120051122002124

**Comment by mleneveut** [comment]
Seems we had some v1beta1 still deployed, sorry.

get deploy, rs, ds, ... are working on the 3 clusters.

We juste have a strange message on one cluster at the end of : `kubectl api-resources --verbs=list -o name`

````
error: unable to retrieve the complete list of server APIs: apps/v1beta1: the server could not find the requested resource, apps/v1beta2: the server could not find the requested resource
```

However, the *.extensions are not listed any more.
