### ISSUE TITLE
Source IP address does not persist for traffic outside of the local vnet 

### ISSUE THREAD

**Issue by bhicks329** [Azure/AKS#1207]
**What happened**: When performing a http request to any resource outside of the vnet from a pod in the AKS cluster the source IP address is remapped to the node address

**What you expected to happen**: I would expect the source IP address to persist regardless of destination. This is the expectation set in the documentation

**How to reproduce it (as minimally and precisely as possible)**: Perform a curl request from a pod to any resource outside of the immediate vnet

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.6, 1.13.5
- Size of cluster (how many worker nodes are in the cluster?): 4

There is a configmap in kube-system that defines a setting called azure-ip-masq-agent-config that has a setting called 'nonMasqueradeCIDRs'. By default this is set to just the IP addresses local to the vNet. I can confirm that when 0.0.0.0/0 is added into this config map, my peered Azure firewall sees the Pod IP address. I'm fully expecting this to revert at some point soon .

**Comment by bhicks329** [comment]
This also causes issues when reply traffic is not leaving via the load balancer ... for example 
![Ingress Route Problem](https://user-images.githubusercontent.com/21193823/65813351-231a1280-e1cc-11e9-91f4-f1f24ccbfdf1.png)

**Comment by denniszielke** [comment]
Is the order of AppGW and AzFW relevant to you? Since AppGW cannot forward traffic from internal to external having a fixed source ip address on the pods will probably not help you. However if you put the AppGW in front of the AzFw it should work.

**Comment by palma21** [comment]
the ip-masq-agent setting will not revert. That is the correct way to configure ip masq for peered traffic or traffic outside of the vnet. The default behavior is to masq except to the cluster vnet.

Closing as per provided answer. lmk otherwise
