### ISSUE TITLE
Trustworthy JWT Tokens (svc account token vol projection)

### ISSUE THREAD

**Issue by bhicks329** [Azure/AKS#1208]
I've just built a new AKS cluster running 1.14.6 in UK South and I've been testing with Istio 1.3. In this release they are enforcing the use of Trustworthy JWT tokens which require Service Account Token Volume Projection via a feature flag enabled on the API server. 

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection

I believe this was available but disabled by default in 1.12 and then enabled by default in 1.13. Can you please confirm if this is enabled in AKS versions 1.13 and 1.14

Example of the token ..

- name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token

**Comment by dpiessens** [comment]
@bhicks329 Have you been able to get this to work? I have been getting this failure on any pods with an Istio sidecar:

" MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource"

**Comment by bhicks329** [comment]
That is exactly the issue I have.  As soon as the project and aud: fields
are set it fails to mount.

-Ben

From: Dan Piessens <notifications@github.com> <notifications@github.com>
Reply: Azure/AKS
<reply@reply.github.com>
<reply@reply.github.com>
Date: 19 September 2019 at 03:49:46
To: Azure/AKS <aks@noreply.github.com> <aks@noreply.github.com>
CC: Ben Hicks <bhicks329@gmail.com> <bhicks329@gmail.com>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [Azure/AKS] Trustworthy JWT Tokens (#1208)

@bhicks329 <https://github.com/bhicks329> Have you been able to get this to

**Comment by bhicks329** [comment]
Any updates on this please?

**Comment by ekarlso** [comment]
+1

**Comment by armbraggins** [comment]
My understanding of https://istio.io/blog/2019/trustworthy-jwt-sds/ is that the BoundServiceAccountTokenVolume feature is also required to support an aud field, and that's still alpha in 1.13 (https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/)
https://thenewstack.io/no-more-forever-tokens-changes-in-identity-management-for-kubernetes/ says "In Kubernetes 1.15 it will likely be in beta and on by default, and when it goes GA (currently planned for Kubernetes 1.16), you’ll no longer be able to opt out".

But I'd love to be corrected and/or to find out how the feature can be enabled in an AKS cluster.

**Comment by mousiefasil** [comment]
As @armbraggins said it would be nice to know if this features is available in AKS with kubernetes 1.13 and 1.14.

**Comment by gmacquillin** [comment]
Doesn't seem to be enabled from the AKS documentation

https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-install?pivots=client-operating-system-linux

> In addition, the Service Account Token Volume Projection Kubernetes feature (a requirement for SDS) is not enabled in current AKS versions.

**Comment by jluk** [comment]
Thanks for report and consolidation to this issue. 

We're planning on enabling this functionality for users, acknowledging this request as we work on this internally. 

Once we have a reasonable ETA we will share, thanks for your patience.

**Comment by MichaelMcCoyTech** [comment]
Please can we have an update on this Microsoft @jluk.   It is preventing us using Lets Encrypt in our cluster.   Are we likely to have this Kubernetes feature enabled  in January 2020 ?

**Comment by EnricoOr** [comment]
Hi @jluk We would really appreciate some ETA from Microsoft on this since are stuck on istio 1.2.x and the official support for this version ended last week. 
We would like to update istio without a major change in the configuration like disabling SDS.

**Comment by dpiessens** [comment]
@jluk We have compliance requirements that are putting us into a corner between version support and security. We need this issue prioritized and released ASAP... 3+ months is too long to wait in Kubernetes world.

**Comment by libudas** [comment]
@jluk Please can we have date as the Istio world is moving fast and we are stuck with the old version because of this issue

**Comment by bhicks329** [comment]
Just built up a new 1.17 server on AKS - still the same problems however I did notice this entry ...

Warning  FailedMount  45s (x14 over 13m)    kubelet, aks-agentpool-89678198-vmss000001  MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the API server does not have TokenRequest endpoints enabled

TokenRequest is a feature that has been enabled by default since 1.12. It would be really useful to understand what feature flags are disabled against the defaults.

**Comment by jluk** [comment]
Thanks for the patience everyone, our ETA is early Feb to support this. We're actively working on it.

**Comment by JoeJasinski** [comment]
Hi all, I'm getting this error in minikube with k8s 1.17. 

This looks like the same issue. 
```
  Normal   Scheduled    98s                default-scheduler  Successfully assigned istio-system/istio-ingressgateway-677bb49c76-g28dl to minikube
  Warning  FailedMount  33s (x8 over 98s)  kubelet, minikube  MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the API server does not have TokenRequest endpoints enabled
```
I gather from this thread that the "Service Account Token Volume Projection Kubernetes" feature needs to be enabled to do this. How does one go about doing that in minikube? 

Thanks

**Comment by jluk** [comment]
This is set for the AKS service release on 2/10. We'll close this issue once that is rolled globally.

**Comment by desek** [comment]
Will this be added transparently for customers or do we need redeploy AKS instances due to it being a control plane change?

**Comment by jluk** [comment]
No need to redeploy anything, existing clusters will be enabled.

**Comment by simongottschlag** [comment]
@jluk is this feature live?

**Comment by jluk** [comment]
Rolling out now, currently in Australia/Canada sectors. If in those sectors, you can give it a try now.

We will include it on this weeks release notes which are coming by tomorrow. This should be global in the coming 7-10 days. I will close this issue when that completes.

**Comment by jluk** [comment]
An issue was found during rollout, a fix was made and is now re-releasing. This will delay availability by another week, tracking for end of Feb. Will update the issue when completed.

**Comment by ismailbaskin** [comment]
Will there be any action needed for existing clusters?

**Comment by jluk** [comment]
> No need to redeploy anything, existing clusters will be enabled.

@ismailbaskin see above

**Comment by charlesguo404** [comment]
@JoeJasinski 
on minikube just like this
```
minikube start --extra-config=apiserver.service-account-issuer=api --extra-config=apiserver.service-account-signing-key-file=/var/lib/minikube/certs/apiserver.key --extra-config=apiserver.service-account-api-audiences=api
```

**Comment by cylewitruk** [comment]
Is this still slated for "end of Feb", e.g. in the coming days?

**Comment by jluk** [comment]
This has been re-released on this week's AKS release so should be rolling global in the next week.

https://github.com/Azure/AKS/releases/tag/2020-02-24

**Comment by framled** [comment]
> This has been re-released on this week's AKS release so should be rolling global in the next week.
> 
> https://github.com/Azure/AKS/releases/tag/2020-02-24

Do you have some ETA about the global release?

**Comment by dbourcet-wiz** [comment]
Hi @jluk , do you have any news regarding the global release schedule?

**Comment by EnricoOr** [comment]
@dbourcet-wiz i don't know if it is already rolled out everywhere, but i can can confirm that at least on my clusters (west-europe) now it is possibile to use token volume projection. I was able to successfully use sds with last version of istio.

**Comment by jluk** [comment]
Confirming this is rolled globally, closing as a result.

Thanks everyone for the feedback and participation!
