### ISSUE TITLE
horizontal-pod-autoscaler unable to get metrics for resource memory: no metrics returned from resource metrics API

### ISSUE THREAD

**Issue by Vitorspk** [Azure/AKS#1209]
**What happened**:

While checking if the application was running I came across the HPA problem in cluster events.
Not autoscale node problems with HPA metrics

**What you expected to happen**:

For the HPA to successfully acquire metrics on every call.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy new aplication on node

    - kubectl get events

    - kubectl describe hpa -n sre-coders

```
LAST SEEN   TYPE      REASON                         OBJECT                                          MESSAGE
109s        Warning   FailedGetResourceMetric        horizontalpodautoscaler/xxx-hpa    unable to get metrics for resource cpu: no metrics returned from resource metrics API
26m         Warning   FailedComputeMetricsReplicas   horizontalpodautoscaler/xxx-hpa    failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
```

    - kubectl describe hpa xxx-dev-as -n sre-coders

```
kubectl describe hpa xxx-dev-as -n sre-coders
Name:                                                     xxx-dev-as
Namespace:                                                sre-coders
Labels:                                                   applicationRole=app
                                                          costCenter=1024
                                                          createdBy=xxx
                                                          environment=dev
                                                          owner=xxx
                                                          productName=sre-coders
                                                          projectName=xxx
                                                          tier=t0
                                                          version=1.0.0-11
Annotations:                                              kubectl.kubernetes.io/last-applied-configuration:
                                                            {"apiVersion":"autoscaling/v2beta2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"applicationRole":"app","costC...
CreationTimestamp:                                        Fri, 13 Sep 2019 09:35:52 -0300
Reference:                                                Deployment/xxx-dev-deploy
Metrics:                                                  ( current / target )
  resource memory on pods  (as a percentage of request):  4% (39698432) / 90%
  resource cpu on pods  (as a percentage of request):     0% (0) / 90%
Min replicas:                                             1
Max replicas:                                             2
Deployment pods:                                          1 current / 1 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from memory resource utilization (percentage of request)
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
```

**Anything else we need to know?**:

bit old this image?
image: aksrepos.azurecr.io/mirror/metrics-server-amd64:v0.2.1

I think can be upgrade to new version
new version: v0.3.4

**Environment**:
dev, hml, prd

- Kubernetes version (use `kubectl version`):

```
1.12.8
```
- Size of cluster (how many worker nodes are in the cluster?)
```
SKU: Standard_DS3_v2 (10 instances)
SKU: Standard_F8s_v2 (3 instances)
```
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Java, http microservices, java app, ruby, node, php, python
- Others:

- My Workaround to enable HPA and restart metrics:

Disable cluster autoscale to scale nodes to min count 10
```
az aks nodepool update \
--resource-group RSG_AKS_ENGINE_DEV \
--name t0dev \
--cluster-name dev \
--disable-cluster-autoscaler \
--min-count 1 \
--max-count 30
```

```
az aks nodepool scale \
--resource-group RSG_AKS_ENGINE_DEV \
--name t0dev \
--cluster-name dev \
--node-count 10 
```

after scale to node count 10 enable auto scale and return to min count = 1

```
az aks nodepool update \
--resource-group RSG_AKS_ENGINE_DEV \
--name t0dev \
--cluster-name dev \
--enable-cluster-autoscaler \
--min-count 1 \
--max-count 30
```

Deleted metrics server and kube state metrics pods to restart.
Everthing is running now and scale based on HPA metrics.

**Comment by Vitorspk** [comment]
any news about this?

I need to do that on my clusters because the problem still apear

**Comment by SteveCurran** [comment]
Seeing the same problem. Using Kubernetes 1.14.5

**Comment by Vitorspk** [comment]
> Seeing the same problem. Using Kubernetes 1.14.5

this issue change label trial to bug?

**Comment by Vitorspk** [comment]
how this bug still in triage omg

**Comment by yves-vogl** [comment]
Has anyone solved this issue so far?

**Comment by Vitorspk** [comment]
> Has anyone solved this issue so far?

No. still

**Comment by prestonvanloon** [comment]
This comment solved it for me: https://github.com/awslabs/amazon-eks-ami/issues/55#issuecomment-470721555

**Comment by Vitorspk** [comment]
finally ! needs attention :+1:

**Comment by palma21** [comment]
Sorry the delay @Vitorspk, we're currently using metrics-server:v0.3.6. Do you still see this happening with the new image?

**Comment by Vitorspk** [comment]
> Sorry the delay @Vitorspk, we're currently using metrics-server:v0.3.6. Do you still see this happening with the new image?
> 
> 
> 
> 

Not using this anymore.

**Comment by TomGeske** [comment]
Going ahead closing this one. Keep commenting, if needed.

**Comment by nmiodice** [comment]
I am seeing this in `1.16.13` @TomGeske . Any way to resolve?

**Comment by TomGeske** [comment]
@nmiodice: Please, open a new Issue.
