### ISSUE TITLE
AKS Not working with Windows Agent Pool - Pods stuck in Pending

### ISSUE THREAD

**Issue by ironicLemon** [Azure/AKS#121]
Deployment is successful, agent is visible, but pods are stuck in pending

    PS C:\WINDOWS\System32> kubectl get nodes --show-all
    NAME           STATUS    ROLES     AGE       VERSION
    12737aks9000   Ready     <none>    24m       v1.8.2-18+3d35a4c5aec26c

    PS C:\WINDOWS\System32> kubectl get pods --all-namespaces
    NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
    kube-system   heapster-58f795c4cf-l9sj9               0/2       Pending   0          23m
    kube-system   kube-dns-v20-6c8f7f988b-45pcr           0/3       Pending   0          23m
    kube-system   kube-dns-v20-6c8f7f988b-lt4dq           0/3       Pending   0          23m
    kube-system   kubernetes-dashboard-6fc8cf9586-8zxcw   0/1       Pending   0          23m
    kube-system   tunnelfront-6c6dd8798f-dgtkq            0/1       Pending   0          23m

    PS C:\WINDOWS\System32> kubectl -n kube-system describe pods kube-dns-v20-6c8f7f988b-45pcr
    Name:           kube-dns-v20-6c8f7f988b-45pcr
    Namespace:      kube-system
    Node:           <none>
    Labels:         k8s-app=kube-dns
                    kubernetes.io/cluster-service=true
                    pod-template-hash=2749395446
                  version=v20
    Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":  {"kind":"ReplicaSet","namesp
    ace":"kube-system","name":"kube-dns-v20-6c8f7f988b","uid":"313c3e72-f961-11e7-8c6e-0a58...
                scheduler.alpha.kubernetes.io/critical-pod=
    Status:         Pending
    IP:             
    Created By:     ReplicaSet/kube-dns-v20-6c8f7f988b
    Controlled By:  ReplicaSet/kube-dns-v20-6c8f7f988b
    Containers:
      kubedns:
    Image:  gcrio.azureedge.net/google_containers/k8s-dns-kube-dns-amd64:1.14.5
    Ports:  10053/UDP, 10053/TCP
    Args:
      --kubecfg-file=/config/kubeconfig
      --config-dir=/kube-dns-config
      --domain=cluster.local.
      --dns-port=10053
      --v=2
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/healthz-kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8081/readiness delay=30s timeout=5s period=10s #success=1 #failure=3
        Environment:  <none>
        Mounts:
      /config from kubedns-kubecfg (ro)
      /kube-dns-config from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-gdpbn (ro)
      dnsmasq:
        Image:  gcrio.azureedge.net/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.5
    Ports:  53/UDP, 53/TCP
    Args:
      -v=2
      -logtostderr
      -configDir=/kube-dns-config
      -restartDnsmasq=true
      --
      -k
      --cache-size=1000
      --no-resolv
      --server=127.0.0.1#10053
      --server=/in-addr.arpa/127.0.0.1#10053
      --server=/ip6.arpa/127.0.0.1#10053
      --log-facility=-
    Environment:  <none>
    Mounts:
      /kube-dns-config from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-gdpbn (ro)
      healthz:
    Image:  gcrio.azureedge.net/google_containers/exechealthz-amd64:1.2
    Port:   8080/TCP
    Args:
      --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
      --url=/healthz-dnsmasq
      --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1:10053 >/dev/null
      --url=/healthz-kubedns
      --port=8080
      --quiet
    Limits:
      memory:  50Mi
    Requests:
      cpu:        10m
      memory:     50Mi
    Liveness:     http-get http://:8080/healthz-dnsmasq delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-gdpbn (ro)
    Conditions:
      Type           Status
      PodScheduled   False 
    Volumes:
      kube-dns-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-dns
    Optional:  true
      kubedns-kubecfg:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kubedns-kubecfg
    Optional:  false
      kube-dns-token-gdpbn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-dns-token-gdpbn
    Optional:    false
    QoS Class:       Burstable
    Node-Selectors:  beta.kubernetes.io/os=linux
    Tolerations:     CriticalAddonsOnly
                 node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
    Events:
      Type     Reason            Age                From               Message
      ----     ------            ----               ----               -------
      Warning  FailedScheduling  2m (x91 over 27m)  default-scheduler  No nodes are available that match all of the predicates: Match
    NodeSelector (1).

Template deployed with a Linux agent pool deploys into a health state.

Are windows agents supported in the preview, documentation does mention windows agents?

**Comment by sauryadas** [comment]
Windows agents are not supported in the AKS yet. it is in the roadmap and hopefully come after mid 2018. Can you point me to the windows documentation that you are referring to above?

**Comment by ironicLemon** [comment]
![aks](https://user-images.githubusercontent.com/6660681/35182055-70aea804-fdc5-11e7-95b1-da5d5851ffa1.png)
