### ISSUE TITLE
AKS ARM template deployment causes kube-proxy reload on an existing nodes

### ISSUE THREAD

**Issue by IvanovOleg** [Azure/AKS#1211]
**What happened**:
When I run an incremental deployment of the ARM template with an existing cluster it forces existing kube-proxy pods to be rescheduled which is so annoying.

**What you expected to happen**:
Second execution of the ARM doesn't touch existing kube-proxy containers.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a basic AKS cluster from the example in the official github repository. Run deployment again checking the status of the kube-proxy pods.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.14.6
- Size of cluster (how many worker nodes are in the cluster?)
3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
only nginx ingress controller
- Others:

**Comment by palma21** [comment]
This was indeed a bug which was solved a few months ago. Apologies for the delay in response, please do make sure to open a support ticket for any urgent matters. Closing as per fix rolled out. Let us know if you still experience this or have further questions.
