### ISSUE TITLE
Adding a new VMSS agent pool removes any non-AKS route table entries

### ISSUE THREAD

**Issue by jveski** [Azure/AKS#1212]
**What happened**:

Added a new agent pool to a VMSS-based AKS cluster.

**What you expected to happen**:

Manually created entries in the AKS-managed route table to be preserved.

**How to reproduce it (as minimally and precisely as possible)**:

- Create VMSS-based AKS cluster
- Add route to AKS-managed route table
- Create a second agent pool
- Confirm route was removed

**Comment by jveski** [comment]
Creating this to provide visibility to a known issue.

**Comment by jluk** [comment]
Acknowledging it is being worked on and in-flight as part of fixes for the multiple nodepool preview.

**Comment by jluk** [comment]
A fix is actively rolling out for this, will leave open until @jveski can test and ack resolution. The fix is in Canada/Australia thus far, but should be global by Monday at the latest.

**Comment by jluk** [comment]
Note published for fix released: https://github.com/Azure/AKS/releases/tag/2019-09-23

@jveski I'm going to close this issue assuming the fix is good, but if you still hit this problem after Monday please comment and I can reopen.

Thanks!
