### ISSUE TITLE
Static tokens for existing cluster are invalid

### ISSUE THREAD

**Issue by bingosummer** [Azure/AKS#1213]
**What happened**:

I have an existing cluster whose kubeconfig has client certificates and static token. The token's username is `clusterAdmin`

I create the clusterrolebinding for the user `clusterAdmin`, and try to use the token to access the cluster. But it failed.

**What you expected to happen**:

I can use the token to access the cluster.

**How to reproduce it (as minimally and precisely as possible)**:

The issue only happens for existing cluster. New clusters don't have the issue.

**Comment by bingosummer** [comment]
It's a regression issue. AKS team is working on a fix.

**Comment by jnoller** [comment]
#1233
