### ISSUE TITLE
how to sign the user certificate by aks cluster

### ISSUE THREAD

**Issue by venkatmamillapalli** [Azure/AKS#1215]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by Shuanglu** [comment]
this one might help. https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/

**Comment by Shuanglu** [comment]
> **What happened**:
> 
> **What you expected to happen**:
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> **Anything else we need to know?**:
> 
> **Environment**:
> 
> * Kubernetes version (use `kubectl version`):
> * Size of cluster (how many worker nodes are in the cluster?)
> * General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
> * Others:

this one might help. https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/

**Comment by TomGeske** [comment]
Are you referring to TLS certs or something else?
