### ISSUE TITLE
Pods on Virtual Nodes only in Pending state

### ISSUE THREAD

**Issue by leonardoads** [Azure/AKS#1218]
**What happened**:
When a new deployment was created into the virtual node the status of the pod remains in Pending for ever.

**What you expected to happen**:
The status of the pod changed to Running.

**How to reproduce it (as minimally and precisely as possible)**:
Apply a new deployment to the nodename parameter by setting to virtual node name.

**Anything else we need to know?**:
Its possible to see the aci of the pod created at the MC resource group. 
Its possible to see the logs of the pods using kubectl or at the respect ACI.

**Environment**:
- Kubernetes version: v1.12.8
- K8s virtual nodes: v1.13.1-vk-v0.9.0-1-g7b92d1ee-dev
- Size of cluster: 2 nodes Standard D4s v3

**Comment by jluk** [comment]
@leonardoads please open a support ticket for this issue given Virtual Nodes is GA and there are many reasons it is stuck in pending state. Having engineers be able to look at your cluster hands on will be much faster. Closing in favor of that path.
