### ISSUE TITLE
Kubernete 1.14.7 / 1.15.4 support

### ISSUE THREAD

**Issue by djsly** [Azure/AKS#1219]
**What happened**:
New kubernetes version were released with multiple Azure Specific and Windows Specific fixes

**What you expected to happen**:
I should have access to those new releases with AKS

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jluk** [comment]
Tagging these with intention, acknowledge we will be bringing these in. 

These releases came out 3 hours ago and are very new, so AKS and AKS-Engine will be working on testing/validation specific to Azure over the next 2 weeks before release. FYI @jackfrancis

**Comment by djsly** [comment]
Thanks Justin, this was indeed mainly to keep track as we are about to deploy a production cluster using 1.14.6, I wanted to see how long I could delay to get 1.14.7.  :). I’ll follow the issue !

**Comment by jluk** [comment]
FYI this will be releasing on this week's service release

**Comment by djsly** [comment]
Thanks a lot.

**Comment by jluk** [comment]
Closing per this week's release note: https://github.com/Azure/AKS/releases/tag/2019-10-07

It's live in Australia and Canada, but will be live in US + EU by Monday. Thanks @djsly!

**Comment by jluk** [comment]
Hey @djsly it's live in all regions except for US which is rolling today. Should be live by tomorrow.
