### ISSUE TITLE
All upgrades to clusters not using Pod Security Policies will fail upgrading to 1.15 preview

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#1220]
AKS engineering has identified an issue impacting customers **not** currently using Pod Security Policies (PSPs) in all regions. 

Currently, if a cluster **does not** have PSPs enabled, and upgraded to Kubernetes 1.15 (on AKS), any further updates to the cluster will be rejected and require remediation, please contact support if you are in this state.

A hotfix to the service is currently being validated and released to all regions. This issue will be closed when the issue is resolved in all regions globally. We are examining automatic recovery of clusters in this state.

Workload runtime is not affected, however customers will be blocked from all further modifications to the cluster.

Until this fix is deployed, customers are advised to hold off on upgrades to Kubernetes 1.15 unless the enable PSPs on their cluster prior to upgrading to 1.15.

**Comment by cdemiguel** [comment]
hello,
Could this error being not happening always or not?,
When I deploy via ARM template an AKS with nodes windows and linux 1.15 sometimes one node crashes when it updates to 1.15 version and the AKS doesn't create well,
thanks,

**Comment by jluk** [comment]
Closing as this issue is resolved and fixed in the service. If you continue to hit any issues with respect to 1.15 upgrades please open a support ticket.

Thank you.
