### ISSUE TITLE
Preview versus production

### ISSUE THREAD

**Issue by cubed-it** [Azure/AKS#1221]
Currently the Multiple Node Pool Support and Windows Node Support are in public test and have to be activated explicitly.
I have two questions:

1) If I create a new AKS Cluster I can activate Multiple Node Pool Support without first activating the preview for my subscription as described in the documentation. How do I have to understand this? Is the preview implicitly activated? Or is this pretty much out of preview?

2) If I activate these preview features, will the preview cluster and my subscription become a "normal" cluster / subscription with appropriate support etc. after release?

Thanks

**Comment by jluk** [comment]
1. Feature registration occurs at the subscription level and is only done once. Unfortunately there is not an unregister option, but we have the open ask to the ARM team to support it. Was the issue that you were able to use multiple node pools on a sub that did not have the feature registered? If so, that is not intended behavior and we can look into it.

2. If by "after release" you mean "after GA", it depends on the feature. Most of preview features will take an action to go into GA support mode. The usual is a k8s upgrade to capture fixes we land in the upstream project. On rare occasions it will be a cluster rebuild, we try to avoid this but will be captured in preview docs. If your cluster meets the min reqs as stated on a GA document, you'll be supported.

**Comment by cubed-it** [comment]
Thanks for the info. It is currently possible to create a multi node pool cluster via azure portal without activating the preview feature.
A VMSS ist created and everythings runs fine. However I can see the first vmss under pools, but there is also a message that "my cluster is not supported by VMSS" and I cannot click the add button.
Does not look right for me :/

**Comment by tomkerkhove** [comment]
Thanks for the info @jluk! Very interesting.

**Comment by jluk** [comment]
@cubed-it

1) Today you must register the preview feature to use multiple node pools in portal. That feature should go GA before end of this calendar year, we're working on it currently. To separate features a bit, VMSS backed clusters are GA with a single node pool, could you post a screenshot of the confusing UI? I can help track that down.

2) Correct, moving from a VM Availability Set cluster to a VMSS based one requires a rebuild since the underlying Azure Compute resources are different. In the future we'd like to offer a one click migration option, but are focused on bringing the preview features in-flight into GA ASAP.

**Comment by cubed-it** [comment]
Thank you for the explanation.
So if I create a VMSS backed cluster today, I will - with high propability - be able to use node pools as soon as they are GA. However when I use a VM Availability Set, I have to hope for migration feature.

If you create a VMSS backed cluster and select your aks and then "Nodepool (preview)" there is a message like "This cluster is not supported by any VMSS and cannot be used with multiple node pools. To use multiple node pools, create a new cluster with node pools supported by VMSS. Learn more about multiple node pools". This message is a little bit confusing, since it actualy is a VMSS, but I now do understand what it means.

![vmss](https://user-images.githubusercontent.com/11182260/65446673-26f90e00-de35-11e9-8cd0-c9f36330355f.PNG)

**Comment by jluk** [comment]
Correct, for VMSS -> multiple node pools. The only expected action once it goes GA is to do a k8s upgrade. For VMAS -> using multiple node pools, you'll need to rebuild the cluster and leverage your own migration task or wait for us to deliver one.

Thanks for the report on the portal message, I will follow-up on that FYI @jenetlan
