### ISSUE TITLE
Change reboot-sentinel to a different file after AKS upgrades itself and needs a reboot

### ISSUE THREAD

**Issue by henrylilei** [Azure/AKS#1222]
**What happened**:
Without prior knowledge of how AKS kernel upgrade works as stated in [node update guide](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/aks/node-updates-kured.md), we installed Kured to our cluster for a totally different purpose and the recent kernel update to cluster nodes caught us off guard. Our Kured restarted the nodes at a time that it was NOT designed to.

**What you expected to happen**:
Kernel update should not trigger node restart when user installed Kured to cluster with default sentinel path.

**How to reproduce it (as minimally and precisely as possible)**:
Install Kured to cluster and upgrade the kernel automatically with AKS.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.6
- Size of cluster (how many worker nodes are in the cluster?) 20

This issue is more about the user experience as AKS should not assume that the user who installs Kured knows AKS also leverages the same default sentinel file for signaling update. 
 
Thanks!

**Comment by seanmck** [comment]
I'm not sure I understand the issue. Kured is the Kubernetes Reboot Daemon. What other purpose would you have for installing it, if not to perform reboots?

**Comment by henrylilei** [comment]
You are right, it is for reboot but at a different time instead of after update. We modify the kubelet config to better serve our production traffic, e.g. disabling CFS. Once the node is autoscaled and provisioned, the Kured is introduced to restart the node and make sure kubelet config changes take effect. We only want the node to restart just once after they provisioned.

**Comment by alanjcastonguay** [comment]
Kernel package installation on Ubuntu with apt causes creation of the reboot-required sentinel file. https://serverfault.com/questions/92932/how-does-ubuntu-keep-track-of-the-system-restart-required-flag-in-motd

**Comment by seanmck** [comment]
@henrylilei: can you just deploy kured with a non-default value for `--reboot-sentinel`?

**Comment by seanmck** [comment]
Closing pending further clarification on the ask.

**Comment by henrylilei** [comment]
Thanks for the explanation, and I was not aware that this is an 'official' reboot notifier file. Changing sentinel to a different path would solve this issue.
