### ISSUE TITLE
How to check what AKS engine has been used to create existing AKS cluster ?

### ISSUE THREAD

**Issue by przemolb** [Azure/AKS#1223]
Hello,
(I am sorry if this is not right place to ask but I am not sure where I can ask this question ...)

we spin up new AKS clusters from time to time. We also can see that there are new AKS releases with new feature and bug fixes. How can we check what AKS engine has been used to create already existing AKS (with command `az aks create ...`). What version of AKS engine was used to create my cluster which has been created X days/weeks/months ago ?

**Comment by jnoller** [comment]
We do not currently expose the version of aks engine used, however we add the a release note to the existing aks release notes when we merge in a new engine version, you may see this under 'component updates'

**Comment by przemolb** [comment]
Why don't you expose the version of aks engine used to create AKS clusters ? What is a reasoning behind this ?
