### ISSUE TITLE
Can I increase an existing node Capacity

### ISSUE THREAD

**Issue by zirain** [Azure/AKS#1225]
Hey,

some capacity was two small when create node, how can I increase this?

![image](https://user-images.githubusercontent.com/4354057/65317723-f748cc80-dbce-11e9-8f9b-aadcb504fb2a.png)

**Comment by dariuszbz** [comment]
I see two options ...
Open portal find VM scale up .
Rebuild K8s cluster

**Comment by seanmck** [comment]
We do not support VM scale up. The recommended approach is to add a 2nd node pool with the larger VM size and reschedule the apps there.

https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools
