### ISSUE TITLE
`az aks browse` Fails to Show All Nodes

### ISSUE THREAD

**Issue by derekrprice** [Azure/AKS#1226]
**What happened**:
I ran `az aks browse` and only 4 of my 6 nodes appeared in the Nodes tab.

**What you expected to happen**:
I expected to see data about all 6 of my nodes.

**How to reproduce it (as minimally and precisely as possible)**:
Run `az aks browse` with 6 nodes in an AKS cluster.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`
- Size of cluster (how many worker nodes are in the cluster?) 6

**Comment by seanmck** [comment]
@derekrprice can you see them via kubectl?

**Comment by derekrprice** [comment]
Yes. All six nodes appear via kubectl with a Ready status.

Sent from my mobile
Please excuse brevity and typos

**Comment by seanmck** [comment]
Any filters in the dashboard which might be limiting what is shown? Can you look at the logs for dashboard pod and see if anything looks awry?

Ultimately, the dashboard calls the same API as the CLI does, so if there's something missing, it would be a bug in the [dashboard](https://github.com/kubernetes/dashboard).

Closing for now as I don't believe there's anything actionable for AKS here.
