### ISSUE TITLE
Draining a node fails with "Forbidden: node updates may only change labels, taints, or capacity"

### ISSUE THREAD

**Issue by archmangler** [Azure/AKS#1227]
**What happened**:
When attempting to drain a node on an AKS K8s cluster using:

```
kubectl drain ${node_name} --ignore-daemonsets

```

I get the following error:

```
   "The Node \"aks-agentpool-xxxxx-0\" is invalid: []: Forbidden: node updates may only change labels, taints, or capacity (or configSource, if the DynamicKubeletConfig feature gate is enabled)"
```

Is there something extra that needs to be done on AKS nodes to allow draining?

(Context: This is part of an automation script I'm writing to drain a kubernetes node for maintenance operations without downtime, so the draining is definitely a prerequisite here)

**What you expected to happen**:

The node drains all pods.

**How to reproduce it (as minimally and precisely as possible)**:

On an AKS cluster (1.14.6 k8s)

```
kubectl drain ${node_name} --ignore-daemonsets
```

**Environment**:

- Kubernetes version (use `kubectl version`):

AKS (southeastasia)
1.14.6

- Size of cluster (how many worker nodes are in the cluster?)

2 nodes

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

one or two test containers - almost nothing/ brand new cluster

- Others:

**Comment by archmangler** [comment]
Update: I have also tried with the --force flag, but  the failure message is the same:

kubectl drain ${node_name} --ignore-daemonsets --force

**Comment by archmangler** [comment]
Update: 

I have further used the following options with the same error result:

{code}
"kubectl drain --timeout 5m --ignore-daemonsets --force --delete-local-data $nodename 
{code}

**Comment by archmangler** [comment]
Additional information:

- This command is being run through ansible's shell module.
- When run directly in BASH it works

**Comment by palma21** [comment]
My guess is there's something on the ansible module that is causing the problem and trying to change something else, but can't comment what it is, would recommend to raise this there, since on bash it works as expected. 

I also couldn't repro on my side
