### ISSUE TITLE
Azure Monitor extension to AKS does not fetch logs from windows containers

### ISSUE THREAD

**Issue by hallgeirl** [Azure/AKS#1228]
**What happened**:
I enabled the Azure Monitor integration on my AKS cluster that has two node pools - one with Linux nodes, one with Windows nodes. The container logs from pods running in the Linux nodes show up, but the container logs from the pods running on the Windows nodes does not. Performing a "kubectl logs" on the Windows pods does indeed show that there are logs available.

I do see the ContainerInventory 

**What you expected to happen**:
I expected the logs to be indexed and searchable. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new cluster with a Windows node pool, and enable the Azure Monitor integration either through command line:
az aks enable-addons -a monitoring -n foo -g bar --workspace-resource-id "123"
Or through the portal.
2. Enable the Container Monitoring solution in the Log Analytics workspace.
3. Deploy a Windows pod that writes to the container log (stdout/stderr).
4. Observe that there's no logs (at least not for me) from the windows nodes by running a query on the Log Analytics workspace: ContainerLog |  summarize count() by Computer, Name

**Anything else we need to know?**:
I do see the ContainerInventory entity has an entry for my pod:
ContainerInventory | summarize count() by Computer, Name

Showing up as Computer = my windows node name, and Name = the container name.
I also don't see the OMS agent daemon set being deployed on the windows nodes.. not sure if it matters.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15
- Size of cluster (how many worker nodes are in the cluster?) 2 windows, 1 linux
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jnoller** [comment]
@MikkelHegn

**Comment by MikkelHegn** [comment]
This is a current limitation of Azure Monitor in AKS and for some reason we missed getting this documented - I will get that fixed. @keikhara if she knows the road-map for support.

**Comment by hallgeirl** [comment]
Thanks @MikkelHegn for clearing that up.

That said.. I have found a workaround, which may be of use for others. I activated the MicrosoftMonitoringAgent extension on the VM Scale set for the windows pools. I do this now as part of cluster creation. Then I'm getting container logs, and the windows nodes report back to Log Analytics.

I would value some input if it's actually a good idea though, to add extensions to the VMSS that is managed by AKS itself.

**Comment by MikkelHegn** [comment]
You sort of hit it :-)

The reason this does not work today, is because no agent is running on the Windows nodes. Azure Monitoring for containers is a container based agent, and we currently don't have a containerized Windows version.

We don't support changing the VMSS model / or using the VMSS APIs unless specifically directed by us to do so.

**Comment by EldarSagirov** [comment]
Hi @hallgeirl, could you explain how you managed to enable MicrosoftMonitoringAgent  and collect logs? I tried to enable it during cluster creation and then on additional windows node pool, but logs from containers are still not available while other insight's metrics are collected.

**Comment by vishiy** [comment]
@EldarSagirov - I guess you could enable microsoft monitor agent thru azure policy, so all new nodes will get it auto (elastic) ?

**Comment by MikkelHegn** [comment]
Release: https://github.com/Azure/AKS/releases/tag/2020-06-15
