### ISSUE TITLE
Current clusters and node pools

### ISSUE THREAD

**Issue by scott1138** [Azure/AKS#1230]
This is really just a question that I don’t know where else to ask. @jnoller or @jluk, can you tell me if using node pools once the feature goes GA will require a cluster rebuild?  We are considering a rebuild to get VMSS and SLB support but We also want Node Pools and I don’t want to have to rebuild twice in close succession.

Thanks for any help you can provide!

**Comment by jluk** [comment]
Receiving GA support of multiple node pools if already using the preview will only require a k8s upgrade.

**Comment by scott1138** [comment]
We don’t have the pools now, but we’d like to be able to add them later.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jluk** [comment]
@scott1138 if you are using a cluster setup with VMSS and SLB, you'll be able to opt-into the multiple nodepools feature without rebuilding.

**Comment by scott1138** [comment]
Thanks Justin!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
