### ISSUE TITLE
Kubernetes 1.11/1.12 end of life, supported version updates: Upgrade by December 9th, 2019

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#1235]
On Monday, December 9th 2019 (2019-12-09), coinciding with the release of AKS Support for Kubernetes 1.15 GA, AKS will be removing support for Kubernetes versions older than the latest version (N), and two minor versions prior (N-2).

Please note: the date above is AKS specific and not related to any upstream/community dates for Kubernetes 1.15.

We are making this change now to align more closely with the upstream Kubernetes project, and provide a more consistent experience for customers with regards to bug fixes, security patches and component compatibility.

Customers running Kubernetes versions older than Kubernetes 1.13.x must upgrade by Monday, December 9th 2019 to remain in support. After, you’ll be asked to upgrade to a supported version when you open new Azure support requests.

Historically, AKS has supported the current GA release of Kubernetes, as well as the three (3) prior minor versions (N-3). When a new minor version is released, the oldest minor version is removed.

With this change, AKS will move to supporting the current GA Kubernetes release and the two (2) previous minor versions (N-2).

After Monday, December 9th 2019, the supported Kubernetes minor releases will be:

- 1.13.x
- 1.14.x
- 1.15.x

To verify what versions are available in your region:

```
az aks get-upgrades --resource-group myResourceGroup --name myAKSCluster --output table
```

To upgrade your clusters using the Azure CLI:

```
az aks upgrade --resource-group myResourceGroup --name myAKSCluster --kubernetes-version <NEW VERSION>
```

For additional information please see the [AKS Kubernetes support policy](https://docs.microsoft.com/en-us/azure/aks/support-policies) (Note: this document will be updated when the shift5 to N-2 is closer to release.)

**Comment by slynickel** [comment]
Any update on the timeline for this one? 12/9 has passed and it would appear as of 12/11/19 17:30UTC in central US Azure region (I didn't check others) this update still hasn't been applied.

We are looking to use v1.15 once it's out of preview.

```bash
# The portal would appear to support the same thing.
$ az aks get-versions -l centralus -o table
KubernetesVersion    Upgrades
-------------------  ----------------------------------------
1.15.5(preview)      None available
1.15.4(preview)      1.15.5(preview)
1.14.8               1.15.4(preview), 1.15.5(preview)
1.14.7               1.14.8, 1.15.4(preview), 1.15.5(preview)
1.13.12              1.14.7, 1.14.8
1.13.11              1.13.12, 1.14.7, 1.14.8
1.12.8               1.13.11, 1.13.12
1.12.7               1.12.8, 1.13.11, 1.13.12
1.11.10              1.12.7, 1.12.8
1.11.9               1.11.10, 1.12.7, 1.12.8
1.10.13              1.11.9, 1.11.10
1.10.12              1.10.13, 1.11.9, 1.11.10
```

**Comment by jnoller** [comment]
@slynickel  It is shipping to all regions as we speak, and the deadline has passed. Release notes are incoming.

**Comment by jluk** [comment]
@slynickel as Jesse mentioned it should be completed in global release by early Tuesday if you're looking for US/EU regions. It's live in Canada/Australia regions as of this moment.

Release notes noted here: https://github.com/Azure/AKS/releases/tag/2019-12-09

Closing this issue as a result of the release active in some regions, but I'll monitor for confirm from @slynickel that he sees 1.15 available in the region he needs.

**Comment by slynickel** [comment]
@jluk all good to close. My previous comment was to check-in since the deadline around when the version change was supposed to occur had passed by a few days. We had planned a bit around that date so I wanted to find out if it was going to be lot longer.
