### ISSUE TITLE
Nodes provisioned by Cluster Auto Scaler w multiple agent pools get de-provisioned when issuing an reset-aad command

### ISSUE THREAD

**Issue by djsly** [Azure/AKS#1236]
**What happened**:
I got rotated our AKS cluster’s AAD Server App Secret

the command was executed: 

```
az aks update-credentials -g MyResourceGroup -n MyManagedCluster \ 
--reset-aad --aad-server-app-id MyExistingAADServerAppID \ 
--aad-server-app-secret MyNewAADServerAppSecret \ 
--aad-client-app-id MyExistingAADClientAppID \ 
--aad-tenant-id MyAADTenantID
```

which caused all of our nodes to be deleted (the ones that were created by the cluster-auto-scaler)

**What you expected to happen**:
I would have expected that my service wouldn't be affected and that I wouldn't have lost ALL of my nodes.

**How to reproduce it (as minimally and precisely as possible)**:

* Create an AKs cluster with Cluster Auto Scaler enabled
* over provision your cluster to ensure you get new nodes from the cluster auto-scaler
* runt he `az aks update-credentials --reset-aad` command

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of the cluster (how many worker nodes are in the cluster?): 3 initial Linux Nodes + 14 over provisonned nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jluk** [comment]
@djsly thanks for the report, we are looking into this for the root issue and believe we've found a bug in the preview of cluster autoscaler. I will provide updates here for you.

**Comment by djsly** [comment]
Super. Glad you guys found it! This will prevent future outage I’m sure!

**Comment by jluk** [comment]
FYI @djsly we found the problem was actually related to the multiple node pools preview feature. Our fix is being worked on and should rollout with next week's release.

**Comment by jluk** [comment]
Closing in reference of this release note fix: https://github.com/Azure/AKS/releases/tag/2019-09-30

@djsly the release is still rolling out, but if you still hit this issue after Wednesday please tag me and I will look at it again.

**Comment by djsly** [comment]
thanks @jluk , how we can track that the patch is live ?

**Comment by jluk** [comment]
We don't have a public way to track the release today, but it takes about 6-8 days after we cut each weekly release. Currently the fix is live in East US so if that is where you need to run, please try again and let me know how it is working.

**Comment by djsly** [comment]
Super thanks.  

Anything that we need to apply / run normally post upgrade for any feature to work ? 

Also what about base images, we saw that we have a new windows akswin OS image mode in our VMSS. Where can we find the change log for this image?

**Comment by jluk** [comment]
The action depends on the fix required, for this issue you do not need to take any specific action. Future AAD resets should not trigger de-provisioning.

For change logs, unfortunately this isn't captured in a public location yet. You can reference this issue which will capture much of that information, which we are readying to work on soon.
https://github.com/Azure/AKS/issues/995

As a sidenote we are also planning to expose the release flow more easily for folks to consume/follow as well.

**Comment by djsly** [comment]
Super.  Thanks I will follow 995
