### ISSUE TITLE
Self signed certificates used on management API

### ISSUE THREAD

**Issue by richardyoung2** [Azure/AKS#1239]
**What happened**: non-trusted connection to Management API using KubeCTL

**What you expected to happen**: secure connection using a certificate backed by a certificate authority.  

**How to reproduce it (as minimally and precisely as possible)**: connect to management API using KubeCTL

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.5
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) HTTP microservices
- Others: self-signed certificate is used on the management API leading to trust issues.  Therefore this is a feature request to change the management API to use an external CA issued certificate so that the endpoint can be trusted as the chain of trust is verifiable.  External certificate authority is a fundamental part of PKI and not using one in a production context not only undermines PKI, but trust in the platform in general, as well as potentially causing connection problems.

**Comment by jnoller** [comment]
You are correct that per the normal PKI specification dictates use of non self signed certificates for SSL transport. However, the reason we do not currently support fully signed certificates is:

1. Kubernetes requires the ability to self generate and sign certificates
2. Users injecting their own CA is known to be error prone in Kubernetes as a whole

We are aware of the desire to move away from self signed certificates, however this requires work in upstream to make this much more likely to succeed. The official documentation explains a lot of this as well as the requirements well:

https://kubernetes.io/docs/concepts/cluster-administration/certificates/
https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/
https://kubernetes.io/docs/setup/best-practices/certificates/
 
Additionally, this post goes in deeper to the issues around cert management:

https://jvns.ca/blog/2017/08/05/how-kubernetes-certificates-work/
