### ISSUE TITLE
Kubernetes 1.14 clusters with over 500 CronJobs/Jobs see execution failure

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#1241]
AKS Support has identified an issue impacting customer running on **Kubernetes 1.14.x**. This issue manifests for customers with high numbers of CronJobs/Jobs (over 500). When the job count gets high enough **all jobs will fail to be scheduled**. 

- The bug is tracked in upstream Kubernetes: https://github.com/kubernetes/kubernetes/issues/77465
- This issue is fixed in Kubernetes 1.14.7
- **AKS engineering is evaluating timelines for deploying 1.14.7 to all regions**

This bug appears in the controller manager logs:

```
I0926 16:15:11.546961       1 cronjob_controller.go:94] Starting CronJob Manager
E0926 16:15:11.749860       1 cronjob_controller.go:117] expected type *batchv1.JobList, got type *internalversion.List
E0926 16:15:22.548062       1 cronjob_controller.go:117] expected type *batchv1.JobList, got type *internalversion.List
```

Customers can attempt to clean up unused jobs to relieve the symptoms:

In the meantime, cleaning up unused jobs may help relieve the symptoms:

```
# This command deletes all jobs that are succeeded, you need to specify the namespace that you want to delete the jobs in

kubectl delete -n desiredNamespace job $(kubectl get job \
  -o=jsonpath='{.items[?(@.status.succeeded==1)].metadata.name}' \
  -n desiredNamespace)
```

**Note:** If you see output that looks like: `error: resource(s) were provided, but no name, label selector, or --all flag specified` means that there were no jobs to delete in the namespace specified. This means you should if the jobs that are causing problems are in different namespace.

This issue will be updated with release time ETAs.

*Thanks go to @NWassell (Azure Raoid Response) for alerting the teams and initial writeup impact assessment.*

**Comment by palma21** [comment]
Closing this issue as fixed since patch versions <1.14.7 are no longer supported on AKS and all later patches have this fix.
