### ISSUE TITLE
Upgrade failing with error of active upgrade/scale but no sign an active upgrade/scale occurring

### ISSUE THREAD

**Issue by paulgmiller** [Azure/AKS#1245]
**What happened**:
Tryign to upgrade a 1.13.5 cluster

>az aks upgrade --kubernetes-version 1.13.10 --name vienna-test-runners-westus2-01 --resource-group vienna-test-runners-westus2-01 --yes                                           Operation failed with status: 'Conflict'. Details: Updating Kubernetes version and agent node scaling are mutually exclusive operations. Please visit https://aka.ms/aks-pending-upgrade for more details.                                                                                                                                                            

>az aks upgrade --kubernetes-version 1.13.9 --name vienna-test-runners-westus2-01 --resource-group vienna-test-runners-westus2-01 --yes                                            Operation failed with status: 'Conflict'. Details: Updating Kubernetes version and agent node scaling are mutually exclusive operations. Please visit https://aka.ms/aks-pending-upgrade for more details.                                                                                                                                                            

>az aks upgrade --kubernetes-version 1.14.6 --name vienna-test-runners-westus2-01 --resource-group vienna-test-runners-westus2-01 --yes                                            Operation failed with status: 'Conflict'. Details: Updating Kubernetes version and agent node scaling are mutually exclusive operations. Please visit https://aka.ms/aks-pending-upgrade for more details.

**What you expected to happen**:
Upgrade or tell me why you can't upgrade (maybe 1.13.5 is too old the cluster is not a failed or pending state.

**How to reproduce it (as minimally and precisely as possible)**:

![image](https://user-images.githubusercontent.com/1474379/66018436-eed87780-e493-11e9-921c-f55abf1272a4.png)

**Anything else we need to know?**:
This doc in hte error message
**Environment**:
- Kubernetes version (use `kubectl version`):1.13.6
- Size of cluster (how many worker nodes are in the cluster?) 10
- General description of workloads in the cluster: Cron job for tests

**Comment by jluk** [comment]
@paulgmiller the error should be accurate, in that there seems to be an active scale or upgrade operation. Did you submit previous upgrade or scales and can you check the state of the cluster now that some time has elapsed?

Also do you have cluster autoscaler enabled?

**Comment by paulgmiller** [comment]
We run our own autoscaler in this cluster. But it seems pretty bored.  I could disable autoscaler and try again in another hour. 

This cluster hasn't been touched manually in months. (either for scale or upgrade)
I still get the same error this monining.

**Comment by jluk** [comment]
Thanks for the info @paulgmiller, could you open a support ticket so we can get our hands on the cluster? It's possible there's a bug if there is no active upgrade/scale and the error is still returning.
