### ISSUE TITLE
Platform Image Not Available when upgrading cluster

### ISSUE THREAD

**Issue by tbertenshaw** [Azure/AKS#1247]
I have a AKS test cluster built using the cli which has one node pool with 2 nodes and AKS version `1.14.6`.

**What happened**:
After upgrading the cluster via the upgrade option on the nodepool. The cluster version was updated to 1.15.3 in a short period of time (5 minutes). However an hour and a half later the cluster status is still `Upgrading` and `kubectl get nodes` shows both nodes a status of Ready and version still `1.14.6`.  When i look at the containing resource group `MC_`  I can see multiple failed deployments.  (effectively trying again every 5 minutes)  The error is below

`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"NotFound","message":"{\r\n \"error\": {\r\n \"code\": \"PlatformImageNotFound\",\r\n \"message\": \"The platform image 'microsoft-aks:aks:aks-ubuntu-1604-201909:2019.08.21' is not available. Verify that all fields in the storage profile are correct.\",\r\n \"target\": \"imageReference\"\r\n }\r\n}"}]}`

It seems that the base image has been expired from azure. Baring in mind this cluster is 2 weeks old this seems odd. And even if this cluster was months or years old this imples that you may need to tear down a cluster and rebuild if you want to do an operation on the nodes.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aefa
ce6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/a
md64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e
0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd
64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
2 nodes (Standard_D2s_v3)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Test cluster currently no workloads deployed.
- Others:

**Comment by gtxistxgao** [comment]
Hi @tbertenshaw can you try to update VMSS directly with the following commands and try the cluster upgrade again?

`az vmss update --name {VMSS name} --resource-group {MC resource group name} --set VirtualMachineProfile.StorageProfile.ImageReference.version="2019.09.25"`

`az vmss update --name {VMSS name} --resource-group {MC resource group name} --set VirtualMachineProfile.StorageProfile.ImageReference.Sku="aks-ubuntu-1604-201909"`

**Comment by tbertenshaw** [comment]
@gtxistxgao after the above steps. I could upgrade the node pool successfully to 1.15.3.  However the cluster still (whilst potentially working ok) has a red banner when you view it in the portal which says `This container service is in a failed state. Click here to open a support request`  Is it possible to remove this message if it is invalid?

Additionally is this normal procedure now for the VMSS service to retire sku's so regularly?

**Comment by gtxistxgao** [comment]
@tbertenshaw  It's not a regular procedure. There is ongoing issue: https://github.com/Azure/AKS/issues/1250

You can try get and put the same managed cluster using REST api. The state should be back to Succeed.
