### ISSUE TITLE
Could not create a role assignment for monitoring addon.

### ISSUE THREAD

**Issue by git001** [Azure/AKS#1249]
**What happened**:

I create a AKS cluster with the following commandline.

```
az aks create --debug -g tfs-aks-pot-001 -n MyManagedCluster2 --location westeurope --enable-addons monitoring --generate-ssh-keys --service-principal ... --client-secret ...
```
After some runtime I get this warning.

**WARNING: Could not create a role assignment for monitoring addon. Are you an Owner on this subscription?**

The cluster is created but not the monitoring space.

**What you expected to happen**:

I would like to have a monitoring in my AKS cluster

**How to reproduce it (as minimally and precisely as possible)**:

Just run the command below with a user which have no access to AAD with contributer role.

```
az aks create --debug -g tfs-aks-pot-001 -n MyManagedCluster2 --location westeurope --enable-addons monitoring --generate-ssh-keys --service-principal ... --client-secret ...
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): any
- Size of cluster (how many worker nodes are in the cluster?): default 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): not relevant
- Others:
maybe it's similar problem as described in #1022

**Comment by TomGeske** [comment]
@git001: I'm going ahead closing this one as I see a related issue already being closed. Feel free to re-open or continue commenting.
