### ISSUE TITLE
Error on delete an AKS cluster

### ISSUE THREAD

**Issue by wiltonrodrigues** [Azure/AKS#125]
I tried to delete a cluster using  sudo az aks delete --resource-group ErgoDapDev --name dapdev --yes, after 14 minutes, I got a message "Deployment failed. Correlation ID: 8c81903d-0cde-4108-98c6-468612a5b5e3. Timeout while polling for control plane provisioning status". I repeat this operation 8 times and I got the same error. I don't want to delete the resource group. I need to delete only the cluster.

**Comment by george-walker** [comment]
I am having the same issue in west-europe using the azure-cli tool and using azure portal.

I am also seeing the same issue when I az aks create:

`Deployment failed. Correlation ID: 83803127-940c-4fa6-a97f-874c4e5d60ec. Timeout while polling for control plane provisioning status`

**Comment by baluchicken** [comment]
Same for me (west-europe), I also repeated the delete a lot of times, on the portal and also with the cli tool, same result: `Deployment failed. Correlation ID: daf7fc4e-1eda-4550-bc63-7a424912a15a. Timeout while polling for control plane provisioning status`

**Comment by wiltonrodrigues** [comment]
Yes. I'm using West Europe too.

**Comment by george-walker** [comment]
I successfully deleted aks clusters from the Azure Portal but I am still getting errors where running az aks create

`Deployment failed. Correlation ID: 21b2a8d5-2d1c-457f-bf98-191de4317c11. Timeout while polling for control plane provisioning status`

**Comment by craigfitzpatrick** [comment]
I am experiencing a similar error while attempting to delete an AKS cluster from az cli in East US, but without the control plane timeout. I get only a generic error:

`Deployment failed. Correlation ID: b9a25701-b1d3-4bf8-8e67-cbcda23b349c. Internal server error`

From the portal I get the status:

`This container service is in a failed state.`

Presumably as a result of this, I am unable to delete the resource group associated with the cluster.

**Comment by jiandej** [comment]
I am experiencing a same error too, I can't delete the AKS cluster or the resource group related to it.

**Comment by craigfitzpatrick** [comment]
I was finally able to delete the cluster via the Azure portal this evening. I didn't do anything different. It just finally worked.

**Comment by jjcollinge** [comment]
Same here - all other resources from the master resource group are deleted except the failed AKS resource.

**Comment by seanmck** [comment]
Closing out old issues. Please reopen if you are still seeing this.

**Comment by Abhiger** [comment]
Yes I'm experiencing this issue . Not able to delete the AKS cluster in West Europe and its in failed state .

**Comment by markusdresch** [comment]
same here, trying to delete two aks clusters. first aks and its vmss instances are all in "deleting" state, after about 45 min it's in "failed" state. tried in portal and in cli.
