### ISSUE TITLE
AKS clusters created before Sept 20th using VMSS upgrade failure (PlatformImageNotFound)

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#1250]
AKS engineering has identified an issue for customers using AKS + VMSS created before 07:20 UTC on 28 Sep 2019 

**Azure teams are mitigating all impacted clusters and rolling out hot fixes to all regions to resolve this issue.**

- **Scope**: All regions
- **Impacted clusters**: All clusters created before this date using VMSS are impacted. 
- **User action**: Customers running VMSS based clusters created before this date are advised to not *perform any cluster upgrades* until this issue is mitigated
  - These clusters are **currently unable to be upgraded without manual intervention**. 

**Failure message during the cluster upgrade:**

```
"The platform image 'microsoft-aks:aks:aks-ubuntu-1604-201909:2019.08.21' is not available. Verify that all fields in the storage profile are correct."
```
 
**Summary of impact**:
Starting on 07:20 UTC on 28 Sep 2019 customers using Azure Kubernetes Service (AKS) on Virtual Machine Scale Sets may have received failure notifications when attempting to perform any cluster upgrades, such as "The platform image 'microsoft-aks:aks:aks-ubuntu-1604-201909:2019.08.21' is not available. Verify that all fields in the storage profile are correct.".
 
**Preliminary root cause:** 
Engineers determined that a recent service update impacted instances of a the backend service which became unhealthy, preventing requests from completing.

**How to mitigate:** 

Customers who have encountered this failure may run the following command to mitigate. Additionally, if you encounter this issue and are unable to self-mitigate, please file an Azure support request so that support and on-call can repair the cluster.
 
Commands:

```
az vmss update --name {VMSS name} --resource-group {MC resource group name} --set VirtualMachineProfile.StorageProfile.ImageReference.version="2019.09.25"
az vmss update --name {VMSS name} --resource-group {MC resource group name} --set VirtualMachineProfile.StorageProfile.ImageReference.Sku="aks-ubuntu-1604-201909"
```

For example:
```
az vmss update --name aks-nodepool1-22141255-vmss --resource-group MC_weinongw-eus_weinongw-test_eastus --set VirtualMachineProfile.StorageProfile.ImageReference.version="2019.09.25"
az vmss update --name aks-nodepool1-22141255-vmss --resource-group MC_weinongw-eus_weinongw-test_eastus --set VirtualMachineProfile.StorageProfile.ImageReference.Sku="aks-ubuntu-1604-201909"
```
 
After this is complete, you may re-run the same upgrade command, at which point the cluster should return to normal operation.

**Comment by jnoller** [comment]
The AKS and VMSS teams are manually mitigating this issue for all impacted clusters, updated releases with long-term fixes are in flight for all regions (14 regions have been patched) as of this writing.

**Comment by tomasr** [comment]
How can you tell if you have an affected cluster without attempting the operation and having it fail in the first place?

**Comment by jluk** [comment]
Closing issue as all regions have been patched for this.
