### ISSUE TITLE
AKS reports a different nodepool O.S disk size than configured on agent nodes

### ISSUE THREAD

**Issue by archmangler** [Azure/AKS#1252]
**What happened**:

- Even after changing the agentpool os disk sizes manually, AKS platform reports the original size of the disks.
- This results in tools like Terraform reading the wrong size of disks for agent pool nodes.
- and results in general failure of automation for AKS based on Terraform

**Background **

- Our AKS clusters are built using Terraform
- We have a requirement to periodically increase the o.s disk sizes of AKS agentpool nodes
- This must be done without rebuilding the cluster
- We do  this by increasing os disk size on individual nodes
- Terraform state is then updated
- However on consequent applies, AKS reports the wrong os disk (the original os disk size for that agent node pool), resulting in destroy plan for the cluster.

**What you expected to happen**:

- If node pool os disks change, AKS should update itself and report the correct size via it's provider API
- Alternatively, the users should have a tool to force update the osdisk size information for AKS.

**How to reproduce it (as minimally and precisely as possible)**:

1. Make change on cloud infrastructure resource (e.g disk size on vm) 
2. Update the terraform code
3. pull terraform remote state from azure blob storage
4. modify terraform state json file (replace one value)
5. push modified state to remote storage (azure blob storage ,container)
6. pull the remote state again (different file name)
7. grep to check the remote state was actually modified
8. Run init.
9. Run Plan.
10. Run Apply - no changes detected during the apply, but .. 
11. Pull state down after apply and check if the modifications are still there ... State has reverted to pre-modified values!!!

**Anything else we need to know?**:

**Environment**:
- Kubernetes version : ALL
- Size of cluster (how many worker nodes are in the cluster?): 2
- General description of workloads in the cluster: none

**Comment by archmangler** [comment]
Relating issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4511

**Comment by jnoller** [comment]
AKS does not support vertical scale-in place of node resources. If you need to expand the VM size of an existing cluster, add a second node pool and set up the new nodes in the new pool. You can then without any downtime, move the traffic from node pool A, to nodepool B and them completely remove the old node pool.

The reason why those changes do not take effect is that it is unsupported.

**Comment by archmangler** [comment]
This is not viable with existing production enterprise loads deployed before "multiple node pools" preview feature was registered. 

Adding nodepools on existing AKS clusters running enterprise production loads will require business downtime risk we'd rather not face - i.e cluster rebuild.

The agent-pool nodes themselves support os disk expansion in-place very well. Only the platform reports the wrong os disk information. This appears to be a defect we'd like a workaround for, ideally a fix.

Any suggestions of a workaround in this scenario would be much appreciated.
