### ISSUE TITLE
Unable to deploy Virtual kubelet with memory request and limit.

### ISSUE THREAD

**Issue by premsonbaby** [Azure/AKS#1257]
**What happened**:

Unable to deploy Virtual kubelet, with resource -> memory enabled.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  labels:
    name: XXXX
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav
  template:
    metadata:
      labels:
        app: clamav
    spec:
      hostname: clamav
      containers:
      - name: clamav      
        image: docker.io/XXXX/clamav:v1
        ports:
        - containerPort: 3310
          name: "clamav"
        resources:
          requests:
            # memory: "1000Mi"
            cpu: "1000m"
          limits:
            # memory: "2000Mi"
            cpu: "1000m"
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule

if i enable the memory request and limit, deployment happens without any issue but no container created. 

Also HPA gives below message 

kubectl describe hpa clamav

Name:                                                     clamav
Namespace:                                                default
Labels:                                                   <none>
Annotations:                                              <none>
CreationTimestamp:                                        Mon, 07 Oct 2019 09:32:47 +0100
Reference:                                                Deployment/clamav
Metrics:                                                  ( current / target )
  resource memory on pods  (as a percentage of request):  <unknown> / 80%
  resource cpu on pods  (as a percentage of request):     15% (151m) / 80%
Min replicas:                                             1
Max replicas:                                             5
Deployment pods:                                          1 current / 1 desired
Conditions:
  Type            Status  Reason                   Message
  ----            ------  ------                   -------
  AbleToScale     True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive   False   FailedGetResourceMetric  the HPA was unable to compute the replica count: unable to get metrics for resource cpu: no metrics returned from resource metrics API
  ScalingLimited  False   DesiredWithinRange       the desired count is within the acceptable range
Events:
  Type     Reason                   Age                   From                       Message
  ----     ------                   ----                  ----                       -------
  Warning  FailedGetResourceMetric  13m (x248 over 8h)    horizontal-pod-autoscaler  missing request for memory
  Warning  FailedGetResourceMetric  3m4s (x1116 over 8h)  horizontal-pod-autoscaler  unable to get metrics for resource memory: no metrics returned from resource metrics API

**What you expected to happen**:

deployment should work with memory requests and limits enabled.

**How to reproduce it (as minimally and precisely as possible)**:

1. create AKS service using Azure portal
2. try to deploy type deployment, using any linux image, with memory requests and limits enabled.

**Anything else we need to know?**:
Tried all sorts of combinations, based on comments available on internet. 
Initially i thought it's the conversion issue of Mi to 1GB (like 1024 = 1 GB), but its not.   

**Environment**:
- any version available currently in Azure Portal (as on 7/10/2019)

**Comment by premsonbaby** [comment]
The issue i faced because of the values and its Units. 
The units such as M, G, T are based on power of 10 - multiplies of 1000 (1000M). 
The units such as Mi, Gi, Ti are based on power of 2 - multiplies of 1024. (1024Mi)

**Comment by premsonbaby** [comment]
I have the cpu matrix working, but as you can see below its giving warnings and it looks like working intermittently. (HPA was able to increase count of podes from 1 to 2 only once it never happened again)

![image](https://user-images.githubusercontent.com/31508228/66635558-62eaec00-ec07-11e9-94d8-b03a71517b88.png)
  
Also in the management portal why its not showing memory details ? its same for yamal file in the managment portal

![image](https://user-images.githubusercontent.com/31508228/66635181-86f9fd80-ec06-11e9-8e0a-bc63763e3582.png)

**From Kubernetes managment portal**

{
  "kind": "HorizontalPodAutoscaler",
  "apiVersion": "autoscaling/v1",
  "metadata": {
    "name": "clamav",
    "namespace": "default",
    "selfLink": "/apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/clamav",
    "uid": "14cf666d-f77e-421f-b893-cef286416298",
    "resourceVersion": "504771",
    "creationTimestamp": "2019-10-10T09:49:57Z",
    "annotations": {
      "autoscaling.alpha.kubernetes.io/conditions": "[{\"type\":\"AbleToScale\",\"status\":\"True\",\"lastTransitionTime\":\"2019-10-10T09:50:12Z\",\"reason\":\"SucceededGetScale\",\"message\":\"the HPA controller was able to get the target's current scale\"},{\"type\":\"ScalingActive\",\"status\":\"False\",\"lastTransitionTime\":\"2019-10-11T08:07:18Z\",\"reason\":\"FailedGetResourceMetric\",\"message\":\"the HPA was unable to compute the replica count: unable to get metrics for resource cpu: no metrics returned from resource metrics API\"},{\"type\":\"ScalingLimited\",\"status\":\"True\",\"lastTransitionTime\":\"2019-10-11T06:10:14Z\",\"reason\":\"TooFewReplicas\",\"message\":\"the desired replica count is increasing faster than the maximum scale rate\"}]",
      "autoscaling.alpha.kubernetes.io/current-metrics": "[{\"type\":\"Resource\",\"resource\":{\"name\":\"cpu\",\"currentAverageUtilization\":0,\"currentAverageValue\":\"0\"}}]"
    }
  },
  "spec": {
    "scaleTargetRef": {
      "kind": "Deployment",
      "name": "clamav",
      "apiVersion": "extensions/v1beta1"
    },
    "minReplicas": 1,
    "maxReplicas": 10,
    "targetCPUUtilizationPercentage": 50
  },
  "status": {
    "lastScaleTime": "2019-10-10T09:56:18Z",
    "currentReplicas": 1,
    "desiredReplicas": 1,
    "currentCPUUtilizationPercentage": 0
  }
}

**My original yamal file, used for deployment**

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: clamav
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: clamav
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50
  
Is there a bug with CPU utilization metrics? why its not considering memory metrics?  

Kubernetes version : 1.15.3 (it was same behavior for 1.14 )

**Also "the desired replica count is increasing faster than the maximum scale rate"**
discussed here, i have added some comments under this.
 
https://github.com/kubernetes/kubernetes/issues/59888#issuecomment-540974998

**Comment by macolso** [comment]
Hello @premsonbaby - are you still facing this issue?

**Comment by premsonbaby** [comment]
> Hello @premsonbaby - are you still facing this issue?

sorry, because I moved on to another project, I haven't got a chance to test with V 1.16.

**Comment by macolso** [comment]
No worries. @jluk can we close this for now and @premsonbaby  can reopen if he experiences the issue again?
