### ISSUE TITLE
Manual scaling down pods does not work when using multiple nodes in windows node pool.

### ISSUE THREAD

**Issue by SteveCurran** [Azure/AKS#1258]
**What happened**:
Manual scale replicas in deployment when only one windows node exists in the pool will work as expected. Pods are scaled up, and scaled down. When two nodes exist in the node pool then the pods are scaled up but are not scaled down. When scaling down you can see the pods terminating but new ones are created bringing the state of the deployment back to the original scale.

**What you expected to happen**:
I expect scaling down to work when using multiple nodes in a windows node pool.

**How to reproduce it (as minimally and precisely as possible)**:
Create a deployment with one pod, then scale the deployment that will force scheduler to  span two nodes in the pool. In my case the auto-scaling for the node pool was turned on and the node is created by the manual scaling event. Once the extra pods are deployed to new node, scale back to the original one pod. The scheduler will continue to deploy the extra replicas.  

**Anything else we need to know?**:

**Environment**:
- Kubernetes version 14.5:
- Size of cluster Two linux nodes, One windows node (before scale)
- General description of workloads in the cluster: .Net Windows backends, webapp frontend
- Others:

**Comment by SteveCurran** [comment]
UPDATE: If I execute "kubectl scale ..." a second time the pods on the second node terminate.

**Comment by jluk** [comment]
This seems to be resolved, so closing. If not feel free to open a new issue.
