### ISSUE TITLE
Pods reporting incorrect state "running" after manually shutting down  all worker nodes 

### ISSUE THREAD

**Issue by ivanthelad** [Azure/AKS#126]
***behavior** 
After manually shutting down  all worker nodes via azure.portal.com (shutdown). it is observed that the AKS master endpoint incorrectly reports pods as running despite all worker nodes correctly being reported as "NotReady". 
The below output is observed. 

`kubectl  get po
NAME                       READY     STATUS    RESTARTS   AGE
1tomcat-7d957bd99-xwb6l    1/1       Running   0          3d
2tomcat-5d59dddd77-6fsjh   1/1       Running   0          3d
kube-6f46b66ccf-gz8p4      1/1       Running   0          3d

kubectl  get node
NAME                       STATUS     ROLES     AGE       VERSION
aks-nodepool1-14583155-0   NotReady   agent     4d        v1.8.2
aks-nodepool1-14583155-1   NotReady   agent     4d        v1.8.2
aks-nodepool1-14583155-2   NotReady   agent     4d        v1.8.2`

***Reproduce** 
1)Shutdown all worked nodes 
2) once all nodes are shutdown execute a kubectl get pods. Pods show state as "running". This will not change 

***Expected behavior** 
 when a pods node get shut down. this pod should get rescheduled to another node(after 5 mins, see below ). in this scenario since no nodes are available to be rescheduled to, it is expected that the pod stays in "Pending" state.

**Eviction-timeout** 
https://kubernetes.io/docs/reference/generated/kube-controller-manager/
      --pod-eviction-timeout duration                                     The grace period for deleting pods on failed nodes. (default 5m0s)

**Comment by seanknox** [comment]
Closing due inactivity. Feel free to re-open if still an issue.
