### ISSUE TITLE
AKS - pod showing in portal, not using kubectl

### ISSUE THREAD

**Issue by trdavidson** [Azure/AKS#1260]
hi,
  
  
- using a simple jhub deployment  
- recently no longer able to login  
- closer inspection shows pod for username still exists on AKS-portal . 
- however, does not show up using `kubectl get pods --all-namespaces`
  
  
How can i get rid of this pod?

**Comment by jluk** [comment]
@trdavidson (1) what are you unable to login to? (2) could you post a screenshot of the aks portal that is confusing you?

**Comment by jluk** [comment]
Closing this as stale after a month, if you hit this again please comment with requested info. Thanks!
