### ISSUE TITLE
Performance of running Azure Functions on AKS Virtual Nodes

### ISSUE THREAD

**Issue by michaelbpalmer** [Azure/AKS#1266]
I have followed the instructions [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-kubernetes-keda) to set up an Azure Functions instance in a Kubernetes cluster running on a Virtual Node. Everything is working well except for the performance of virtual node creation. In all cases, it is taking the container 60-70 seconds to enter the running state.

My function has an HTTP trigger. When I use Postman to make a request, the container quickly enters the "Creating" state. After a few seconds, it transitions to the "Waiting" state, where it remains for 50-60 seconds. Finally, the container enters the "Running" state.

Is there anything that I can do to improve the performance of this operation? My containers are stored in a premium ACR instance in the same region as my AKS cluster (westus2).

**Environment**:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:52:31Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
1 Standard_F4s_v2 node + Virtual node(s)

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

Azure Functions, running SDK version 1.0.29.

**Comment by michaelbpalmer** [comment]
How do I get traction on this? Is there somewhere else that I should open this?

**Comment by jluk** [comment]
Adding @MikkelHegn who is driving virtual nodes work, @michaelbpalmer my best guess is the delay you are witnessing is incurred by image pull/decompress. What's your image size / base?

AFAIK the premium ACR storage will help with concurrent pulls if making on the order of hundreds simultaneously, but won't increase throughput of individual pulls.

**Comment by MikkelHegn** [comment]
@michaelbpalmer - to narrow this down, what's the comparable spin-up time for the container directly against ACI? https://docs.microsoft.com/en-us/azure/container-instances/container-instances-quickstar

**Comment by michaelbpalmer** [comment]
Sorry for the delay -- I'll try to get results back to you by Monday.

In the interim, one question: Is there any caching done on your end? In other words, do I pay the full image download and container instantiation cost every time the container is spun up on the virtual node? If so, that's really a deal breaker for many of my use cases for Functions + AKS + Virtual Nodes.

**Comment by MikkelHegn** [comment]
If it's a custom container, then yes. What are your requirements for the container to be ready for this to not be a deal breaker?

**Comment by michaelbpalmer** [comment]
All our containers are custom containers. We have two use cases (primary use case listed first):

1. The API is customer facing (called from our WebApp). In that case, we need the response time to be on the order of seconds (the time needed to instantiate the container). Even that is really too long, but we can do some tricks where we "warm up" the API in advance so that the perceived access time is close to the time is takes the function to respond. 

2. We have APIs that are used by our backend pipeline. These APIs can take however long to spin up without issue, since the process is effectively "offline".

Taking a step back, what I would love to have is:

1. A serverless API surface with demand based scaling.
2. Deployed with Kubernetes (using Docker containers).
3. Per second billing for compute AND GPU consumption. Side note: The other issue that I am hitting is that while I can use virtual nodes for CPU compute, I cannot use virtual nodes for GPU compute workloads -- it appears that ACI with virtual networks (needed for AKS integration) are incompatible with ACI GPU instances. Should I open a separate issue for that limitation?

I understand that some of what I am trying to achieve may not be a good fit for Azure Functions w AKS virtual nodes -- if not, please point me in the right direction.

**Comment by MikkelHegn** [comment]
For the first use case it will be hard to meet that target with ACI through VN. You're currently better off with over provisioning VMs in a K8 cluster. And then eventually scale out to VNs (given you can buy yourself time with the over provisioned capacity). Another option would be functions or WebApps (but that would not meet your second requirement).

We are working on bringing both GPUs and Virtual Networks to GA for ACI (and thus benefiting VN).

**Comment by jluk** [comment]
@MikkelHegn is there a way to use both cluster autoscaler and VN together today? That seems to be an important scenario but I'm not positive you can do it today due to toleration assignment forcing pods into VN and never triggering a CA scale event.
