### ISSUE TITLE
Control over VMSS resources creation

### ISSUE THREAD

**Issue by sasanmcp** [Azure/AKS#1268]
When I create a VMSS-backed AKS, Azure creates a bunch of required resources such as DNS, Load Balancer, VMSS, etc. these resources are created in a resource group called MC_**AKS Resource Group**____**AKS Name**__**AKS Location**_ and are assigned random names.

I want to control all these. I want to be able to tell Azure where to put these resources and what to name them. I couldn't find the trace of arm template(s) that trigger all these deployments. where are they? I am creating the AKS using the arm template and there is no mention of these resources in it, either directly or as part of external template call. it must be something that Azure triggers on the backend once you set VMSS enabled.

**Comment by jluk** [comment]
AKS manages these resources on your behalf, so customization of everything through ARM template of the managed IaaS is not exposed. Anything you may need to configure will need to be done from the AKS API. For VMSS for example, that logically maps to the agent pool in an AKS cluster. Within that object you'll see settings that can match-up to the underlying VMSS backing it like availability zones. For resource naming that isn't supported for the VMSS object, but it is supported for the managed resource group name.

Hope this helps.

**Comment by sasanmcp** [comment]
So how? How do you define managed resource group name?

**Comment by jluk** [comment]
It's a create time parameter, documented here:
https://docs.microsoft.com/en-us/azure/aks/faq#can-i-provide-my-own-name-for-the-aks-node-resource-group

Closing this issue with that instruction.
