### ISSUE TITLE
Reserved Instance support for agents

### ISSUE THREAD

**Issue by szdc** [Azure/AKS#127]
Hi,

You mentioned [a month ago](https://github.com/Azure/AKS/issues/49#issuecomment-351463501) that support for RIs with AKS is limited due to the lack of billing support.

That's quite vague - could you clarify this a bit more?  There is obviously billing support for on-demand instances and considering we prepay for RIs, your statement isn't clear.  Is the intention to _never_ support RIs, or is this something we can expect in the near future?

Thanks

**Comment by sauryadas** [comment]
Should be expected in the future but there is no set date for it. Sorry.

**Comment by seanmck** [comment]
Upon further review, RIs should just work with AKS as currently designed because the agent nodes are billed like any other IaaS VM.

**Comment by vyadh** [comment]
That's great to hear. Thanks Sean. :)
