### ISSUE TITLE
kube-svc-redirect huge log volume

### ISSUE THREAD

**Issue by jfcoz** [Azure/AKS#1270]
**What happened**:

kube-svc-redirect is logging a huge amount of useless data. For example on one cluster, 874000 lines by day.

**What you expected to happen**:

Log only important things

**How to reproduce it (as minimally and precisely as possible)**:

Create an AKS cluster

**Anything else we need to know?**:

Already reported here and closed without any investigation : 
- https://github.com/Azure/AKS/issues/732
- https://github.com/Azure/AKS/issues/851

**Environment**:

1.12.8

**Comment by jfcoz** [comment]
Also related to https://github.com/Microsoft/OMS-docker/issues/92

**Comment by yamaszone** [comment]
We are also seeing the same issue. ~20M logs per month being generated. Supper noisy and also pricy for SaaS log management. There seems to be some [mention of future removal](https://github.com/Azure/AKS/issues/732#issuecomment-449149114)  of `kube-svc-redirect`. Its strange that the ticket was closed without actually removing this!

**Comment by yamaszone** [comment]
This was [reported in February](https://github.com/Microsoft/OMS-docker/issues/92) 2018 but no one seems to care!

**Comment by gsirin** [comment]
any news on this?

**Comment by palma21** [comment]
Closing since AKS no longer uses kube-svc-redirect
