### ISSUE TITLE
Cluster scale up --> We do not have sufficient capacity

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/AKS#1272]
**What happened**:
We tried to scale our cluster to 30 nodes but we get the following error:
Provisioning failed. Allocation failed. We do not have sufficient capacity for the requested VM size in this region. Read more about improving likelihood of allocation success at http://aka.ms/allocation-guidance. AllocationFailed

**What you expected to happen**:
My cluster to be scaled to 30 nodes

**How to reproduce it (as minimally and precisely as possible)**:
Scale the cluster via the az cli or portal from 7 to 30 nodes.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.6
- Size of cluster (how many worker nodes are in the cluster?) 30
- VMsize: Standard DS2 v2

**Comment by tomkerkhove** [comment]
I think this is a good case for Azure Support to help you further

**Comment by bramvdklinkenberg** [comment]
I created a support ticket as well, but most of the times I get quicker response via Github :).
I thought maybe there is a resource issue in Azure for weste europe aks clusters.

**Comment by bramvdklinkenberg** [comment]
We tried scaling back to 8 again, waited till the failed machines were removed and scaled back to 30 again. After a couple of tries it finally worked.
