### ISSUE TITLE
Autoscaler causing race condition in route table updates when adding VMSS quickly

### ISSUE THREAD

**Issue by funnybirdman** [Azure/AKS#1273]
**What happened**: 
1. Deployed statefulset requiring 4 new nodes to be added. 
1. Autoscaler added all four nodes simultaneously.
1. The routetable had near simultaneous updates as the instances came online. One of these happened first and succeed. The other three failed.
1. The three remaining calls continued happening constantly while the first was processing.
1. After the first call continued the same issue happened, but this time only three were competing
1. Eventually all routes were updated.

**What you expected to happen**: Either the autoscaler would batch route table updates, or wait for a previous call to finish before proceeding.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create cluster with autoscaler enabled.
1. Deploy pods that require 2+ new nodes to be created.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.10
- Size of cluster (how many worker nodes are in the cluster?): 16 -> 20
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): NA, provisioning time issue
- Others:
aksEngineVersion: v0.40.0-aks

**Comment by palma21** [comment]
Thanks for reporting. Can you also repro this when you scale 3+ VMSS nodes manually or just with CA?

**Comment by funnybirdman** [comment]
We manually rescaled a cluster to immediately fix the problem when it happened again.
Issue has only happened with CA.

**Comment by jluk** [comment]
Closing due to staleness and a vast amount of improvements to CA in recent months, if issue is recurring please reopen a new issue or follow up with Azure support for an SLA'd response to troubleshoot.
