### ISSUE TITLE
AKS not using designated public IP with Standard Load Balancer

### ISSUE THREAD

**Issue by chriskuech** [Azure/AKS#1274]
**What happened**:
We configured our AKS instance (with a default Basic Load Balancer) to leverage an existing Public IP resource.  We redeployed our AKS instance using a Standard Load Balancer, but the redeployment created and uses a new Public IP resource (in the MC_* resource group instead of the resource group containing our AKS resource).

**What you expected to happen**:
Just as when we were using a Basic Load Balancer, the deployment should not have created a new Public IP and the load balancer "Front-end IP Configuration" should have referenced the existing Public IP, just as before.

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure AKS to use an existing Public IP by setting `controller.service.loadBalancerIp` in an nginx ingress controller.
1. Deploy the AKS cluster (using the default Basic Load Balancer and existing referenced Public IP.  Verify that everything works.
1. Observe that AKS does not create a new IP resource.
1. Delete the AKS resource.
1. Deploy a new AKS instance with the same configuration, but using a Standard Load Balancer.
1. Observe that AKS creates and references a new Public IP resource.

**Anything else we need to know?**:
You can contact me internally as well.

**Environment**:
N/A (having provisioning issues, not runtime issues)
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jluk** [comment]
@chriskuech this is the design of SLB, in that we have to explicitly configure the pip. By default AKS will provide you one and make it a managed resource (hence why it lives in MC RG). This is captured in the slb doc below.
https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#limitations

We support bringing your own IP though for this scenario, which is captured here.
https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#optional---provide-your-own-public-ips-or-prefixes-for-egress

Could you follow the BYOIP instructions to see if it meets your requirements?

**Comment by chriskuech** [comment]
We will implement the bring-your-own-IP instructions, but isn't this still a regression as a feature that worked with Basic Load Balancers no longer works with Standard Load Balancers?

**Comment by jluk** [comment]
SLB is a separate feature over BLB so not a regression given the behavior of basic LB did not change and you're able to still use that scenario if needed. 

We had to update the behavior to conform to BLB vs SLB differences.
https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-overview#skus

Thanks for confirming you'll update to the BYOIP scenario, closing as a result.

**Comment by chriskuech** [comment]
We deploy all our resources through ARM templates.  Do you plan to add this support to ARM templates, and if so, do you have a tentative timeline?

**Comment by jluk** [comment]
Yes, SLB can be defined via ARM template using the load balancer SKU property.

https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate#loadbalancersku

You should use 2019-08-01 API which contains the BYO IP capability.

https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate#outboundips

**Comment by easkay-castlight** [comment]
@jluk I would recommend that the [docs for specifying static egress IPs within AKS](https://docs.microsoft.com/en-us/azure/aks/egress) should be updated, as there is no mention of the special cases of standard load balancers compared to basic.

Even just a note with a link explaining that there is a difference would be helpful. Is this something that could be done please?

**Comment by jluk** [comment]
Ack, in-flight @easkay-castlight FYI @zr-msft / @mlearned on priority for updating this egress doc
