### ISSUE TITLE
Create NSG Service Tag for required AKS traffic

### ISSUE THREAD

**Issue by grahamhayes** [Azure/AKS#1275]
**What happened**:

Creating a AKS cluster with a rule to block outbound internet traffic fails. 

**What you expected to happen**:

A NSG Service Tag to be created to allow easy selection of exceptions to the default deny. 

**How to reproduce it (as minimally and precisely as possible)**:

Add an NSG rule that blocks all VNet -> Internet Traffic, and try deploy an AKS cluster.

**Anything else we need to know?**:

Azure Firewall is not an alternative - NSGs should be able to filter the required traffic. 

**Environment**:
- Kubernetes version: 1.14.6 (happens on all versions)
- Size of cluster: 9
- General description of workloads in the cluster: multi tenant business apps.
- Others:

**Comment by cdunford** [comment]
This would be very handy; it would be a start for us if the ServiceTags_Public json file listed the AKS service IPs. They seem to be in there associated with the AzureCloud.region entries, but they are not broken out as AKS.
