### ISSUE TITLE
Calico Horizontal Autoscaler CPU Getting Throttled

### ISSUE THREAD

**Issue by rudolphjacksonm** [Azure/AKS#1279]
**What happened**: We're seeing the calico-typha-horizontal-autoscaler pod constantly hitting the CPU limit that is set, which is `2m`. This seems like the limit isn't set high enough; in the public [Kubernetes repository](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/calico-policy-controller/typha-horizontal-autoscaler-deployment.yaml) the example deployment manifest has the CPU limit and request set to `10m`.

**What you expected to happen**: This pod shouldn't be throttled constantly. As it's a resource managed by AKS it should have enough resources to function without being throttled.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy an AKS cluster with `calico` set as the network policy plugin. Deploy some workloads on it and you should see it consume up to the limit it is allocated:
```
> kubectl top pod -n kube-system calico-typha-horizontal-autoscaler-79d4669c84-s7tcf
NAME                                                  CPU(cores)   MEMORY(bytes)
calico-typha-horizontal-autoscaler-79d4669c84-s7tcf   2m           14Mi
```

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0"} 
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10"}
- Size of cluster (how many worker nodes are in the cluster?) 7 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) HTTP microservices
- Others: We use nginx-ingress and cert-manager for certificates. We have the k8s dashboard disabled. We also use kured for automatically rebooting nodes when patches need to be applied.

**Comment by djsly** [comment]
same here. 

I'm getting a bunch of alerts about this exact same thing.

**Comment by djsly** [comment]
```
resolved: Labels: - alertname = CPUThrottlingHigh - cluster = sly - container_name = autoscaler - namespace = kube-system - pod_name = calico-typha-horizontal-autoscaler-774d89c779-2d9cr - prometheus = monitoring/prometheus-operator-prometheus - severity = warning Annotations: - message = 27% throttling of CPU in namespace kube-system for container autoscaler in pod calico-typha-horizontal-autoscaler-774d89c779-2d9cr. - runbook_url =
```

**Comment by TomGeske** [comment]
@palma21 can you help here?

**Comment by rudolphjacksonm** [comment]
@jnoller is this something you could help with?

**Comment by TheAsteroid** [comment]
Any update on this? We are seeing the same behaviour, with Kubernetes version 1.19.7, throttling between 10% and 25%. We can `kubectl patch` the Deployment to increase the CPU limit, but this seems like a weak solution since AKS could update the Deployment at any time without us knowing.

![image](https://user-images.githubusercontent.com/41196601/115832720-82292300-a413-11eb-97c7-5319c1f95496.png)

**Comment by paulgmiller** [comment]
We probably won't be making any changes in current calico. There is a new
version of calico (3.18) once you go up to kuberentes 1.20. There
deploymetns/daemonsets/autoscalres are controlled by tigera operator so any
resources would be set by them.

**Comment by TheAsteroid** [comment]
Thanks @paulgmiller . I just noticed K8S 1.20 is GA in our region. We'll update in the coming days and verify if the issue is resolved.

**Comment by TheAsteroid** [comment]
We just updated to K8S 1.20.5. For us none of the Calico resources are currently throttling, so that's good. It appears the calico-typha-horizontal-autoscaler got replaced with a fixed number of calico-typha replicas (3) defined in the deployment.
