### ISSUE TITLE
Unable to delete AKS cluster

### ISSUE THREAD

**Issue by joalmeid** [Azure/AKS#128]
I've got several AKS cluster (the limit of 5) that failed provisioning.
Tried removing Resource Groups, but they keep being listed when running az aks list.

Error message is by timout:
Deployment failed. Correlation ID: f90492e0-58f9-40b8-b898-424a0f12704e. Timeout while polling for control plane provisioning status

Resource groups:
jda-aks-cluster, jdacartoaks, carto-cluster, cartok8s, my-aks-cluster

AKS Clusters name:
jdaaksCarto , myCarto, jdaCarto, myCarto, myaksCarto

Subscription:
255588a0-fd77-4e6f-8455-b24faa4e275c

Region:
westeurope

**Comment by george-walker** [comment]
Duplicate of #125
