### ISSUE TITLE
Azure-Network-Policies pods ressources quotas

### ISSUE THREAD

**Issue by kalioz** [Azure/AKS#1280]
**What happened**:

We recently created a cluster with Azure Network Policies enabled (plugin: azure), and installed a certain number (30-40) of network policies. We recently discovered the pods created by the daemonset (azure-npm-XXXX) are using a heavy part of our resources (CPU / memory), with sudden increase we cannot match to any activity on our part (this is a test cluster with only 2 persons using it at the moment).

After looking at the pods specifications, we saw that they didn't have any resources requirement or limits set. Due to the high priority set on the pods, it causes resources starvation on other pods.
The azure-npm image is : mcr.microsoft.com/containernetworking/azure-npm:v1.0.27

**What you expected to happen**:
The pod shouldn't take so much memory and cpu.

**How to reproduce it (as minimally and precisely as possible)**:
install a cluster with network policy installed and create some policies ? 

**Anything else we need to know?**:
I currently stopped the problem by setting rather restrictive resources limits on the pods ( 0.5cpu / 300Mi ram), but the pods restart multiple times each hour due to this.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.6
- Size of cluster (how many worker nodes are in the cluster?): 3 to 6 (upgraded during the week)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): HTTP webserver

Our nodes are Standard_F4S_V2 ( 4 cpu / 8Go memory)

**Relevant Kibana Screenshots**:
Resources for the week : ![image](https://user-images.githubusercontent.com/24780504/67106230-7af3da00-f1ca-11e9-85f3-4be2b2e1bfa7.png)

Resources after having forced a pod restart : 
![image](https://user-images.githubusercontent.com/24780504/67106456-f81f4f00-f1ca-11e9-97b8-ddac5218ebc1.png)

**Comment by palma21** [comment]
Hi @kalioz thanks for reporting. Known issue with the 1.0.27 image. We patched that image (you should be receiving the hotfix soon) and we are rolling out the 1.0.28 image.

**Comment by kalioz** [comment]
Ok thanks ! I'll keep you updated once we receive the patch.

**Comment by maadtechie** [comment]
We're experiencing the same problem with 1.0.28 version of the image on a newly created AKS cluster 1.14.8. One of azure-npm pods  consumes almost 88 G of RAM on Standard_E16s_v3 VM and we haven't added networkpolicies yet.
![image](https://user-images.githubusercontent.com/19853436/70523796-6db0f700-1b4c-11ea-8dd5-58aa19dcc6f6.png)

**Comment by maadtechie** [comment]
We're experiencing the same issue on a newly created AKS cluster (ver 1.14.8) even without networkpolicies. One of azure-npm podes consumes almost 88 Gigs of RAM!
![image](https://user-images.githubusercontent.com/19853436/70523956-cb454380-1b4c-11ea-8ca3-a06fb68f7126.png)

**Comment by kalioz** [comment]
Hi, forgot to keep you updated
So it seems that for us the problem is gone, we are actually on `aksrepos.azurecr.io/mirror/hyperkube-amd64:v1.13.5`.
`kubectl top pods -l component=kube-proxy` : 
```
NAME               CPU(cores)   MEMORY(bytes)
kube-proxy-8lpnz   10m          39Mi
kube-proxy-clhx2   3m           40Mi
kube-proxy-kdw5s   11m          39Mi
kube-proxy-qp859   2m           37Mi
kube-proxy-vgpjw   16m          36Mi
```

@maadtechie you should edit the deployment to add custom resources limits while waiting for a fix

**Comment by palma21** [comment]
Thanks for the update @kalioz 

@maadtechie we are currently on image 1.0.30 (we had 29 in between) do you still see this? That is not expected.

**Comment by jluk** [comment]
Closing due to staleness and latest images being released which should address this.
