### ISSUE TITLE
Pods depolyed to extra nodepool cannot connect to Azure Cache for Redis Service.

### ISSUE THREAD

**Issue by jason-epp** [Azure/AKS#1284]
I have an image based on ubuntu:16.04 that has the redis-cli installed.  
If it is deployed to the default nodepool1, it CAN connect to redis.
     redis-cli -h xxxx.redis.cache.windows.net -p 6379 -a xxxx
     xxxx.redis.cache.windows.net:6379>ping
     PONG

If it is deployed to the one of the extra nodepools, it CAN NOT connect to Redis.  It times out.
     redis-cli -h xxxx.redis.cache.windows.net -p 6379 -a xxxx
    Could not connect to Redis at xxxx.redis.cache.windows.net:6379: Connection timed out
    not connected>
Other trouble shooting to check a connection (nc, telnet, etc) timeout 
The pod does has general connectivity, curl to google.ca works

curl google.ca

\<HTML>
\<HEAD>
\<meta http-equiv="content-type" content="text/html;charset=utf-8">
\<TITLE>301 Moved\</TITLE>
\</HEAD>
\<BODY>
\<H1>301 Moved\</H1>
The document has moved
\<A HREF="http://www.google.ca/"> here \</A>.
\</BODY>
\</HTML>

DETAILS...
vmss enabled cluster with 2 extra nodepools added
Kubernetes version 1.14.6

Azure Cache for Redis - Standard 1G 
Non-SSL enabled while troubleshooting

I have reviewed the NSGs for the nodepools and I find that nodepool1 (default) has a Load balancer entry while the other NSGs do not.
EDIT - the load balancer view is not in the NSG .  If you navigate ...

- Virtual machine scale sets
- aks-nodepool1-xxxx-vmss
- Instances
- aks-nodepool1-xxxx-vmss_0
- Networking
- Load Balancers

You'll see the reference to a load balancer.

I tried to add to add a back end pool that connected to the nodepool, but it failed on validation.

Has anyone encountered this?

**Comment by vaikzs** [comment]
We are facing the exact same issue. Try removing VMSS (multi-node pool extension) feature and have only 1 node pool

**Comment by jason-epp** [comment]
Thank you for your suggestions.  That is what we end up doing to make it work.

**Comment by jason-epp** [comment]
This is still an issue.
Also occurs with event hub/kafka.

nodepools are great, but things like this need to be addressed.

**Comment by palma21** [comment]
I believe you might have added a multiple nodepool to a cluster using Basic load balancer, that is not supported since BLB is not capable to load balance across multiple VMSS.

We added validation to prevent that scenario from happening.
https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#limitations

Looking at both inputs it looks almost certain so I'll close for now, but feel free to comment if that's not the case and I'm happy to re-open.
