### ISSUE TITLE
AKS Clusters deployed with acceleratedNetworkingEnabled: False

### ISSUE THREAD

**Issue by TheMacStack** [Azure/AKS#1286]
**What happened**:
2 out of 6 AKS Clusters (the production ones of course...) deployed on `Standard DS15 v2` Nodes have `acceleratedNetworkingEnabled: False`

**What you expected to happen**:
`acceleratedNetworkingEnabled: True` for all VMs on all clusters

**How to reproduce it (as minimally and precisely as possible)**:
Unknown

**Environment**:
Kubernetes version: 1.13.10
Ranging from 3 to 7 nodes

**Question**:
Anyone can explain how we managed to have accelerated Networking not enabled on certain clusters? From what we can tell this is not optional in AKS, if the Node type supports it it is just on (except when its not as is our case), these clusters are spread across dev/stg/prod envs and are identical configs across envs, somehow though in the Prod env acceleratedNetworking is not enabled.

We are considering to simply enable it for the 2 clusters (node by node) via the cli/pwsh commands but have concerns that if we scale up nodes we will have it enabled on some nodes and not others.

**Comment by palma21** [comment]
CC @CecileRobertMichon @jackfrancis 

@TheMacStack recommend a support ticket, something abnormal happened during deployment for that to happen and it's better we find out and fix it with you

**Comment by jason-epp** [comment]
After reading this case, I reviewed my vms.
Accelerated networking is not enables ion clusters that were recently deployed.
I am having other network/conectivity issues.

Is this related to vmss enabled clusters?
Are you using extra node pools?

**Comment by TheMacStack** [comment]
In our case we are not vmss enabled or using extra node pools, we dont have any preview features enabled I dont think.

**Comment by CecileRobertMichon** [comment]
@TheMacStack do you have nodes of the same size (Standard DS15 v2) that have accelerated networking enabled? I can confirm that accelerated networking is supported on that VM size and should get enabled by default on AKS nodes of that size according to https://github.com/Azure/aks-engine/blob/master/pkg/helpers/helpers.go#L133. Will look out for your support ticket.

**Comment by TheMacStack** [comment]
Hi @CecileRobertMichon yes we have 5 other clusters all on same node type that it is enabled (all in different subscriptions and built a few weeks earlier).

The response on the ticket was that it was something that has been patched and the clusters will need to be rebuilt or manually enable for current + new nodes until we can justify another rebuild.

**Comment by jason-epp** [comment]
Should the Standard_DS12_v2 be part of that list?  I don't see it in the file...
https://github.com/Azure/aks-engine/blob/master/pkg/helpers/helpers.go#L133

Our older non vmss clusters with the DS12_v2 have AN enabled. 
Our newer vmss clusters with the DS12_v2 have AN disabled.

**Comment by karataliu** [comment]
Fix in https://github.com/Azure/aks-engine/pull/2566 , pending aks update

**Comment by andyzhangx** [comment]
I think we should not maintain such a `acceleratedNetworkingEnabled` VM list since it's always changing, we could leave this flag to user, if user set it as true, then user should make sure that VM type supports acceleratedNetworking.

**Comment by BernieWhite** [comment]
I think this is still a valid issue.

**Comment by palma21** [comment]
It shouldn't, the issue that caused OP was solved a few months ago. And the dependency has been removed. If there are any issues you've seen please do open a ticket or a separate issue
