### ISSUE TITLE
Brand new 1.14.7 clusters have broken metrics

### ISSUE THREAD

**Issue by worldspawn** [Azure/AKS#1287]
I just created two new clusters targeting v 1.14.7. Both clusters are unable to collect metrics, no scaling can be performed. `kubetcl top nodes` fails with `error: metrics not available yet`

**What you expected to happen**: 
I expect brand new resources to be working perfectly.

**How to reproduce it (as minimally and precisely as possible)**: 
Create new cluster targeting 1.14.7. Agent pool config used was:

```
agent_pool_profile {
    name            = "default"
    vm_size         = "Standard_D3_v2"
    os_type         = "Linux"
    os_disk_size_gb = 30
    type            = "VirtualMachineScaleSets"
    enable_auto_scaling = true
    min_count       = 1
    max_count       = 5
    vnet_subnet_id = "${azurerm_subnet.subnet.id}"
  }
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.7
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

Theres no workload, the cluster is born broken.

- Others:

**Comment by palma21** [comment]
I'm guessing your cluster is in Australia, sorry for that (and the two problems in a week, although the other one was lower on the stack it's not the experience we want to give). 
The latest metrics server version does not work well in that region. We are hotfixing it right now. will update when done

**Comment by palma21** [comment]
Closing, let me know if anything is not ok

**Comment by worldspawn** [comment]
Thanks @palma21. Everything seems to be working 👍
