### ISSUE TITLE
Unable to enable insights.containers metrics 

### ISSUE THREAD

**Issue by gpictonmg** [Azure/AKS#1289]
Hi there

I have two clusters in one of my subscriptions.  

One was made a few weeks ago and one was made much more recently.

I am unable to to turn on the metrics that show up under insights.containers/nodes or insights.containers/pods on the newer cluster.

I have tried using the cli to enable the roll as outlined here:
https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-update-metrics

Getting the details about each cluster shows them to be essentially the same but the newer cluster has a different networking setting.  I would be surprised if this would be the reason but I have been wrong about this kind of stuff in the past.

Please help!

Thanks

**Comment by gpictonmg** [comment]
Cluster that has insight.containers metrics working version: 1.13.10
Cluster that does not work version: 1.13.11

**Comment by TomGeske** [comment]
@gpictonmg: Did try to [disable](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-optout) and [enable](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-enable-existing-clusters) Container insights?

**Comment by gpictonmg** [comment]
Hi @TomGeske -- sorry I didn't see this get pinged over the summer.

If I remember correctly when I wrote this ticket I had a cluster in a region that didn't support the metrics I was looking for.

I moved the cluster and everything worked out.

Please feel free to close.

Thanks!
