### ISSUE TITLE
az aks nodepool add with cluster autoscaler failing when node taints are specified

### ISSUE THREAD

**Issue by ramakrishnateja** [Azure/AKS#1291]
aks node pool provisioning in failed state after 1 + hr when creating them with node taints and cluster autoscaler enabled.

This is for a cluster with basic kubenet networking and standard load balancer enabled and network policy of calico.

az aks nodepool add --cluster-name $config.name `
         --name $nodePoolToAdd.name `
         --resource-group $config.resourceGroup `
         --enable-cluster-autoscaler `
         --max-count $nodePoolToAdd.max `
         --min-count $nodePoolToAdd.min `
         --node-count $nodePoolToAdd.min `
         --node-osdisk-size $nodePoolToAdd.osDiskSize `
         --node-vm-size $nodePoolToAdd.size `
         --vnet-subnet-id $subnetId `
         --node-taints $nodePoolToAdd.taints `
         --verbose

**Comment by jluk** [comment]
@ramakrishnateja could you open a support ticket for this issue? It is not expected that the nodepool would fail provisioning entirely and we'd need to get our hands on the cluster. Closing this issue in favor of using the support path.

**Comment by ramakrishnateja** [comment]
Hi jluk,
you can replicate this pretty easily using the below arm template. Its not specific to a single cluster. we are able to consistently replicate this

{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "name": {
            "type": "string",
            "metadata": {
                "description": "description"
            }
        },
        "kubernetesVersion": {
            "type": "string",
            "metadata": {
                "description": "description"
            }
        },
        "vnet": {
            "type": "string",
            "metadata": {
                "description": "description"
            }
        },
        "subnet": {
            "type": "string",
            "metadata": {
                "description": "description"
            }
        },
        "clientId": {
            "type": "string",
            "metadata": {
                "description": "description"
            }
        },
        "clientSecret": {
            "type": "securestring",
            "metadata": {
                "description": "description"
            }
        },
        "defaultNodepool": {
            "type": "object",
            "metadata": {
                "description": "description"
            }
        },
        "agentPools": {
            "type": "array",
            "metadata": {
                "description": "description"
            }
        }
    },
    "variables": {
        "subnetId": "[resourceId('Microsoft.Network/virtualNetworks/subnets', parameters('vnet'), parameters('subnet'))]"
    },
    "resources": [
        {
            "name": "[parameters('name')]",
            "type": "Microsoft.ContainerService/managedClusters",
            "apiVersion": "2019-06-01",
            "location": "[resourceGroup().location]",
            "properties": {
                "kubernetesVersion": "[parameters('kubernetesVersion')]",
                "dnsPrefix": "[parameters('name')]",
                "agentPoolProfiles": [
                    {
                        "name": "[parameters('defaultNodepool').name]",
                        "count": "[parameters('defaultNodepool').count]",
                        "vmSize": "[parameters('defaultNodepool').vmSize]",
                        "vnetSubnetID": "[variables('subnetId')]",
                        "osDiskSizeGB": "[parameters('defaultNodepool').osDiskSize]",
                        "osType": "Linux",
                        "enableAutoScaling": true,
                        "minCount": "[parameters('defaultNodepool').minCount]",
                        "maxCount": "[parameters('defaultNodepool').maxCount]",
                        "type": "VirtualMachineScaleSets",
                        "storageProfile": "ManagedDisks"
                    }
                ],
                "servicePrincipalProfile": {
                    "clientId": "[parameters('clientId')]",
                    "secret": "[parameters('clientSecret')]"
                },
                "enableRBAC": true,
                "networkProfile": {
                    "networkPlugin": "kubenet",
                    "networkPolicy": "calico"
                }
            }
        },
        {
            "type": "Microsoft.ContainerService/managedClusters/agentPools",
            "name": "[concat(parameters('name'),'/',parameters('agentPools')[copyIndex()].name)]",
            "apiVersion": "2019-06-01",
            "copy": {
                "name": "agentpoolcopy",
                "count": "[length(parameters('agentPools'))]"
            },
            "dependsOn": [
                "[resourceId('Microsoft.ContainerService/managedClusters',parameters('name'))]"
            ],
            "properties": {
                "count": "[parameters('agentPools')[copyIndex()].count]",
                "vmSize": "[parameters('agentPools')[copyIndex()].vmSize]",
                "osDiskSizeGB": "[parameters('agentPools')[copyIndex()].osDiskSize]",
                "vnetSubnetID": "[variables('subnetId')]",
                "maxCount": "[parameters('agentPools')[copyIndex()].maxCount]",
                "minCount": "[parameters('agentPools')[copyIndex()].minCount]",
                "nodeTaints": "[parameters('agentPools')[copyIndex()].taints]",
                "enableAutoScaling": true,
                "type": "VirtualMachineScaleSets"
            }
        }
    ],
    "outputs": {
    },
    "functions": [
    ]
}

**Comment by jluk** [comment]
@ramakrishnateja I tried a repro with the below test command and had it run successfully. Can you share the error you received? I can try to help diagnose via github, but you'll get the most rapid resolution via support ticket.

```
➜  ~ az aks nodepool add --cluster-name newazcluster -n extra -g myresourcegroup -e --max-count 3 --min-count 1 --node-taints sku=gpu:NoSchedule
```

**Comment by ramakrishnateja** [comment]
@jluk  I would suggest trying out with the arm template i have pasted. If i run the same arm template with out node taints on agentpools its working fine and provisioning quickly

Here is the error i have got 

Deployment failed. Correlation ID: b5b492d4-854d-447e-971b-e0891281f426. Not all nodes reached Ready state. Expected: 0, Actual: 2
command ran in 2733.714 seconds.

**Comment by ramakrishnateja** [comment]
@jluk  Not sure why you closed this bug. as its a clear bug in AKS. it can be replicated with setting the network policy as calico. What if I do not have the support plan in Azure.  How do i address this issue. I am able to  so consistently replicate the issue.

Its so baffling how the issue is closed and asking me to go through support route.

**Comment by jluk** [comment]
@ramakrishnateja the goal was strictly to keep expectations on resolution for github issues. Opening a support ticket will 100% lead to dedicated people to resolve it, github is best effort from product folks who are most often outside of regular working hours answering these and does not guarantee the fastest path to resolution. 

My goal was to ensure you have one source of truth for getting help and trying to improve time to resolution, but we can move to discussing on the new ticket you've opened to track this.
