### ISSUE TITLE
Windows nodepool upgrade did not wait for pods to start - causing downtime

### ISSUE THREAD

**Issue by brobichaud** [Azure/AKS#1293]
**What happened**: Upgrading a Windows nodepool to a new k8s version and Windows version caused downtime of my workloads.

**What you expected to happen**: For the upgrade process to complete without any downtime of my workloads that have multiple replicas.

**How to reproduce it (as minimally and precisely as possible)**: I upgraded the cluster control plane from k8s v1.14.6 to v1.14.7. All went well. I then upgraded the default nodepool (nodepool1) to v1.14.7. All went well. I then proceeded to upgrade the single Windows nodepool in the cluster. It has two Standard_F8s_v2 nodes.

I watched as the VMSS created a 3rd node and brought it into the cluster. I then saw it drain the first node and start to update it. However, it did not seem to wait for the drained pods to start on another node. And after the first node finished updating it drained the second node and started to update it. The problem is that at this point the first set of drained pods had not finished starting, this left workloads that had multiple replicas with NONE in a started state. Downtime ensued.

We have a mix of ServerCore and Windows images (yes big old 11GB images). So on a fresh node it takes a while to get those images pulled and cached locally. If the upgrade process were to wait for the pods to start then I believe all would have been OK, but it did not, which I think is what caused the downtime.

**Anything else we need to know?**: I was running Windows 10.0.17763.557 before the upgrade and now have 10.0.17763.737. All of our workloads that are exposed to other processes have multiple replicas for availability.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.6 to v1.14.7
- Size of cluster (how many worker nodes are in the cluster?) one linux default nodepool with 2 nodes. One Windows nodepool with 2 nodes.
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Mix of AspNetCore and NetFramework web apps and api's and a number of NetFramework worker processes.
- Others:

**Comment by asbjorne** [comment]
I experienced the same behaviour. Our images are about 2 GB in size. In some cases it might take 10 minutes downloading them on a new node. 
I think I've experienced this also just by creating a new node and draining an old one without doing an upgrade.

**Comment by brobichaud** [comment]
This remains an issue for us. We have a workaorund where we manage the upgrade ourselves. We provision a new node and then walk through this process for each node:

1. Cordon a node
2. Wait for all workloads to fully start on a different node
3. Upgrade the cordoned node
4. Uncordon the node

Works well but is very manual. Where all we need is for the AKS upgrade process to wait for all workloads to fully start before moving on.

**Comment by palma21** [comment]
Hi folks, that should be the default behavior of drain in windows and linux, whilst in Linux you perhaps might not notice. Did you have any PodDisruptionBudgets in your deployment?

cc @AbelHu

**Comment by brobichaud** [comment]
In fact we do not have pod disruption budgets. I was unaware of their existence until just recently, but have not yet had an opportunity to implement them. I'm guessing that is the root of what causes this issue. I can close this and circle back if it turns out not to solve the problem or leave it open until I find time to test it. Do you have a preference @palma21?

**Comment by brobichaud** [comment]
We've now applied pod disruption budgets to our sensitive workloads and experimented with a cluster upgrade. Things went much better this time so I believe this issue was due to our lack of understanding. I am closing this issue.

**Comment by palma21** [comment]
Thanks for circling back and confirming @brobichaud!
