### ISSUE TITLE
API REST calls failing for customer, support team not defined for documentation. 

### ISSUE THREAD

**Issue by porrascarlos802018** [Azure/AKS#1294]
Documentation
https://docs.microsoft.com/en-us/rest/api/aks/agentpools/createorupdate#create/update-agent-pool
lacks of additional clarification on if it is supported or not, internally iis not clear if this is supported or not .

is it possible to use the REST API to scale up node pools using automation account runbook? What are the limitations or requirements? 
154428323

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jluk** [comment]
This API is for multiple nodepools, which is in preview. Preview features are supported to the below standard, however the good news is the multiple nodepools feature is entering GA next week so it will be fully supported and open for support tickets if needed. Hope this helps.

https://docs.microsoft.com/en-us/azure/aks/support-policies#preview-features-or-feature-flags
