### ISSUE TITLE
Service feature externalTrafficPolicy: Local is not always preserving the client source IP for a UDP service

### ISSUE THREAD

**Issue by basclaessen** [Azure/AKS#1295]
**What happened:**
For a UDP service of type loadbalancer with the feature externalTrafficPolicy: Local enabled the client source IP is not always preserved. Also the UDP packet is not always routed to a running pod.

**What you expected to happen:**
The client source IP is always preserved when enabling the feature externalTrafficPolicy: Local.
All UDP packets sent to the loadbalancer will be routed to a running pod.

**How to reproduce it (as minimally and precisely as possible):**
On an AKS cluster with at least 2 nodes create a loadbalanced UDP service with the externalTrafficPolicy: Local feature:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: lb-udp-etp-local-service
spec:
  externalTrafficPolicy: Local
  ports:
  - name: auth
    port: 1812
    protocol: UDP
    targetPort: 1812
  selector:
    app: lb-udp-etp-local-pod
  type: LoadBalancer
```
Create a pod that matches the service selector and log UDP packets on port 1812. I used an ubuntu image with tcpdump and executed:
```
 tcpdump udp port 1812
```
Find the external ip address of the service:
```
kubectl get service lb-udp-etp-local-service
```
Send a UDP packet from outside the AKS to the external ip address of the service. I used nc for this:
```
 nc -vnuz [service external ip] 1812
```
Three things can happen:
- The UDP packet will be logged with the ip address of the client
- The UDP packet will be logged with the ip address of an AKS node
- The UDP packet will not be logged at all

**Anything else we need to know?:**
I noticed that the AKS created a health probe and a load balancing rule for the service in the kubernetes-internal loadbalancer.
The load balancing rule was not referencing the health probe though. I think this is causing the behaviour described above.
```
az network lb rule show --resource-group [aks resource group] --subscription [subscription] --lb-name kubernetes-internal --name [load balancer rule prefix]-UDP-1812 --query [backendPort,protocol,probe]
[
  1812,
  "Udp",
  null
]
```
![aks_lb_rules](https://user-images.githubusercontent.com/35045227/67950442-dc17a680-fbe9-11e9-9dea-d80113ed1571.png)
![aks_lb_probes](https://user-images.githubusercontent.com/35045227/67950649-4cbec300-fbea-11e9-845f-5f2aa5934915.png)

When I manually updated the load balancing rule with the health probe the service is working as expected. All UDP packets reach the pod with the ip address of the client.

When all nodes run at least one pod of the service (using a daemon set for example) the service is also working as expected.

I think the kubernetes-internal loadbalancer is randomly targeting nodes because no health probe is defined in the load balancing rule. When no pod is running on a targeted node the packet is dropped or rerouted to another node (and replacing the client ip address with the ip address of the node).

**Environment:**
- Kubernetes version (use kubectl version): v1.14.7
- Size of cluster (how many worker nodes are in the cluster?) one linux nodepool (vmss) with 3 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): microservices
- Others: kubenet, basic loadbalancer

**Comment by feiskyer** [comment]
opened a bug on Kubernetes here: https://github.com/kubernetes/kubernetes/issues/84800. Let's use Kubernetes issue for tracking.

**Comment by basclaessen** [comment]
@feiskyer Thank you for fixing and backporting this issue. We just upgraded the AKS to version 1.15.7 and the health probes are now being attached to the load balancing rules 👍
