### ISSUE TITLE
BROKEN: kube-proxy iptables restore verbose spamming updates to endpoints

### ISSUE THREAD

**Issue by wronda** [Azure/AKS#1296]
**What happened**:

I perform log-collection with Datadog and I've noticed kube-proxy is very verbose when it comes to logging. It appears an iptables restore is ran every 30 seconds outputting the following. What's more is that it's interpreted as an error. 

```

Nov 01 15:32:01.608 | aks-agentpool-22230431-0 | hyperkube-amd64 | I1101 14:32:01.607764 1 bounded_frequency_runner.go:221] sync-runner: ran, next possible in 0s, periodic in 30s
-- | -- | -- | --
  | Nov 01 15:32:01.608 | aks-agentpool-22230431-0 | hyperkube-amd64 | I1101 14:32:01.607715 1 healthcheck.go:235] Not saving endpoints for unknown healthcheck "kube-system/kube-dns"
  | Nov 01 15:32:01.608 | aks-agentpool-22230431-0 | hyperkube-amd64 | I1101 14:32:01.607562 1 healthcheck.go:238] Reporting 1 endpoints for healthcheck "ingress-basic/kissed-crab-nginx-ingress-controller"
  | Nov 01 15:32:01.608 | aks-agentpool-22230431-0 | hyperkube-amd64 | I1101 14:32:01.607557 1 healthcheck.go:235] Not saving endpoints for unknown healthcheck "kube-system/metrics-server"
  | Nov 01 15:32:01.608 | aks-agentpool-22230431-0 | hyperkube-amd64 | I1101 14:32:01.607552 1 healthcheck.go:235] Not saving endpoints for unknown healthcheck "kube-system/tiller-deploy"
  | Nov 01 15:32:01.608 | aks-agentpool-22230431-0 | hyperkube-amd64 | I1101 14:32:01.607547 1 healthcheck.go:235] Not saving endpoints for unknown healthcheck "ingress-basic/kissed-crab-nginx-ingress-default-backend"
  | Nov 01 15:32:01.608 | aks-agentpool-22230431-0 | hyperkube-amd64 | I1101 14:32:01.607541 1 healthcheck.go:235] Not saving endpoints for unknown healthcheck "kube-system/kubernetes-dashboard"
  | Nov 01 15:32:01.608 | aks-agentpool-22230431-0 | hyperkube-amd64 | I1101 14:32:01.607516 1 healthcheck.go:147] Existing healthcheck "ingress-basic/kissed-crab-nginx-ingress-controller" on port 31346
  | Nov 01 15:32:01.582 | aks-agentpool-22230431-0 | hyperkube-amd64 | I1101 14:32:01.579998 1 proxier.go:683] Syncing iptables rules


```

**What you expected to happen**:

Can we control how verbose kube-proxy is or increase the interval at which those rules are checked? for example 1m or 5m? 

**How to reproduce it (as minimally and precisely as possible)**:

Spin up an AKS cluster and observe the logs of the kube-proxy pod. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.6
- Size of cluster (how many worker nodes are in the cluster?) 1 node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jeremypsncf** [comment]
I have the same problem with AKS 1.13.10. Have you a reponse of this problem ?

**Comment by xtrc** [comment]
@jeremypsncf No response yet.

**Comment by JonasDeGendt** [comment]
Also experiencing this, and regardless of the iptables restore, I feel like it's just too verbose in general. On a busy cluster with a lot of services it's outputting insane amounts of info, e.g. `[ Tue Dec 10 09:02:05 UTC 2019 ] INF: Ssh to tunnelEnd is connected with pid: 64405`.

This is easy enough to drop at the ingestion layer in Elasticsearch, but maybe changing the log level should be considered.

**Comment by UnluckyAj** [comment]
> @jeremypsncf No response yet.

have you got any solution?.

**Comment by juan-lee** [comment]
We'll reduce the verbosity of the kube-proxy logs before the end of September.

If you're having issues with the verbosity of the log, you'll want to make sure your pod's readiness probes are configured properly. If readiness for pods are flapping frequently, you're going to see all of these changes in the kube-proxy logs.

**Comment by xxthegonzxx** [comment]
> We'll reduce the verbosity of the kube-proxy logs before the end of September.
> 
> If you're having issues with the verbosity of the log, you'll want to make sure your pod's readiness probes are configured properly. If readiness for pods are flapping frequently, you're going to see all of these changes in the kube-proxy logs.

From my experience I have not seen many pods have readiness issues. Maybe I'm not understanding correctly but if the pods aren't having any issues with readiness/liveness probes and the health checks are reporting back healthy then how is this checking the healthcheck properly? Also, should this be returned as an error? Maybe a warning would suffice?
