### ISSUE TITLE
AKS Docker Hub secrets can not be used on new nodes deployed by autoscaler.

### ISSUE THREAD

**Issue by djendrju87** [Azure/AKS#1298]
**What happened**:

I am dealing with some issues on Kubernetes on Azure (AKS) using Autoscaler and secrets for pulling images from Docker Hub.
I created the secret in my applications namespace while having 3 nodes enabled (initial cluster status).

`kubectl create secret docker-registry mysecret --docker-server=https://index.docker.io/v1/ --docker-username=<docker_id> --docker-password=<docker_password> -n mynamespace`

I deploy my application using the imagePullSecrets option after specifying images URL.

```
imagePullSecrets:
 - name: mysecret
```

After deploying the application I created the autoscaler rule.

`kubectl autoscale deployment mydeployment --cpu-percent=50 --min=1 --max=20 -n mynamespace`

All new pods deployed on initially created cluster nodes pull the image correctly. However at some point when new Kubernetes node is being automatically deployed, all new pods requiring the DockerHub based image can not start on that node.

`Failed to pull image "mydocherhubaccount/myimage:mytag": rpc error: code = Unknown desc = Error response from daemon: pull access denied for mydocherhubaccount/myimage:mytag, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

The cluster was created using the following command.

`az aks create -g myresourcegroup -n mynamespace --location eastus --kubernetes-version 1.15.5 --node-count 3 --node-osdisk-size 100 --node-vm-size Standard_D4_v3 --enable-vmss --enable-cluster-autoscaler --min-count 3 --max-count 5`

**What you expected to happen**:

Pods created on new nodes deployed by autoscaler should be able to retrieve images from Docker Hub using a secret created before.

**How to reproduce it (as minimally and precisely as possible)**:

Create secret for Dockerhub.
Deploy new node with autoscaler.
Try to use secret created before to deploy the image from Docker Hub.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
3, then scaled to 5.
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Python with tasks distributed by Celery.
- Others:

**Comment by whyvez** [comment]
I'm wondering why this ticket was closed. I'm having the exact same issue with AWS EKS. The nodes added by scale-up don't seem to have the required docker secret references in the deployments. Once I regenerate the referenced image pull secret using the `kubectl create secret docker-registry` command the images are downloaded successfully. What am I missing?
