### ISSUE TITLE
typo in latest release link

### ISSUE THREAD

**Issue by xinity** [Azure/AKS#1299]
Hey there,

Thanks a million for the latest release, looking at the changelog, 
see below, perhaps it would be cool to fix it ?

**What happened**:
seems there's a typo somewhere:
https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-rangesa
**What you expected to happen**:
https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jluk** [comment]
Thanks for the callout, we've updated it!
