### ISSUE TITLE
VNet Peering

### ISSUE THREAD

**Issue by shayansarkar** [Azure/AKS#13]
When creating a cluster via az aks, it seems to show up as a single managed container service in my resource group.  If I wanted to expose the Kubernetes services via an App Gateway in a separate virtual networks or peer the Kubernetes services with other virtual networks to access applications running in them, what is the suggested method.

We currently use acs-engine and the kubernetes cluster had a virtual network which could be used to peer with other portions of our infrastructure.  This does not seem to be the case here.

**Comment by slack** [comment]
AKS follows the ACS behavior, there is a second resource group created with a `MC_` prefix. All resources for your cluster live there. You should see the Virtual Network there.
