### ISSUE TITLE
Cluster creation via CLI fails - cluster limit reached (erroneous)

### ISSUE THREAD

**Issue by jim-h-wang** [Azure/AKS#130]
I have 1 cluster running but now when trying to create a second, I get the below error

```
az aks create --resource-group testResourceGroup2 --name testk8sCluster2 --node-count 1 --ssh-key-value ~/.ssh/azure_regnosys_rsa.pub 
Operation failed with status: 'Conflict'. Details: Public preview limit of 5 for managed cluster(AKS) has been reached for subscription 84355674-b5c1-4cd6-a9a8-1224362effe0 in location westeurope. Please try deleting one or more managed cluster resources in this location before trying to create a new cluster or try a different Azure location.
```

Running `az aks list` show many of my previously failed cluster deployments.  I am unable to delete these as I've already deleted the resource group (which did not delete these aks deployments).

I am deploying to westeurope, sub: 84355674-b5c1-4cd6-a9a8-1224362effe0

**Comment by sethtregenna** [comment]
I had the same issue myself but eventually the old objects that I'd presumed deleted did get cleared up. 
How long ago did you delete them?

**Comment by jim-h-wang** [comment]
I deleted the resource groups yesterday morning (London time), so thats about 24 hrs ago now.

**Comment by derekperkins** [comment]
@jim-h-wang did you delete the auto-created resource group? see #3

**Comment by jim-h-wang** [comment]
@derekperkins Those were never created as my deployments failed.  I manually deleted the resource groups I created manually.

**Comment by seanknox** [comment]
Closing due inactivity. Feel free to re-open if still an issue.
