### ISSUE TITLE
User supplied noSchedule taints break calico networking pods

### ISSUE THREAD

**Issue by ramakrishnateja** [Azure/AKS#1301]
please use the arm template to clearly replicate the issue and please do not close this bug with out trying to replicate and asking me to go to resort to support for this.

{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "name": {
            "type": "string",
            "metadata": {
                "description": "description"
            }
        },
        "kubernetesVersion": {
            "type": "string",
            "metadata": {
                "description": "description"
            }
        },
        "vnetResourceGroup": {
            "type": "string",
            "metadata": {
                "description": "description"
            }
        },
        "vnet": {
            "type": "string",
            "metadata": {
                "description": "description"
            }
        },
        "subnet": {
            "type": "string",
            "metadata": {
                "description": "description"
            }
        },
        "clientId": {
            "type": "string",
            "metadata": {
                "description": "description"
            }
        },
        "clientSecret": {
            "type": "securestring",
            "metadata": {
                "description": "description"
            }
        },
        "defaultNodepool": {
            "type": "object",
            "metadata": {
                "description": "description"
            }
        },
        "agentPools": {
            "type": "array",
            "metadata": {
                "description": "description"
            }
        }
    },
    "variables": {
        "subnetId": "[resourceId(parameters('vnetResourceGroup'),'Microsoft.Network/virtualNetworks/subnets',parameters('vnet'),parameters('subnet'))]"
    },
    "resources": [
        {
            "name": "[parameters('name')]",
            "type": "Microsoft.ContainerService/managedClusters",
            "apiVersion": "2019-06-01",
            "location": "[resourceGroup().location]",
            "properties": {
                "kubernetesVersion": "[parameters('kubernetesVersion')]",
                "dnsPrefix": "[parameters('name')]",
                "agentPoolProfiles": [
                    {
                        "name": "[parameters('defaultNodepool').name]",
                        "count": "[parameters('defaultNodepool').count]",
                        "vmSize": "[parameters('defaultNodepool').vmSize]",
                        "vnetSubnetID": "[variables('subnetId')]",
                        "osDiskSizeGB": "[parameters('defaultNodepool').osDiskSize]",
                        "osType": "Linux",
                        "enableAutoScaling": true,
                        "minCount": "[parameters('defaultNodepool').minCount]",
                        "maxCount": "[parameters('defaultNodepool').maxCount]",
                        "type": "VirtualMachineScaleSets",
                        "storageProfile": "ManagedDisks"
                    }
                ],
                "servicePrincipalProfile": {
                    "clientId": "[parameters('clientId')]",
                    "secret": "[parameters('clientSecret')]"
                },
                "enableRBAC": true,
                "networkProfile": {
                    "networkPlugin": "kubenet",
                    "networkPolicy": "calico",
                    "loadBalancerSku": "standard"
                }
            }
        },
        {
            "type": "Microsoft.ContainerService/managedClusters/agentPools",
            "name": "[concat(parameters('name'),'/',parameters('agentPools')[copyIndex()].name)]",
            "apiVersion": "2019-06-01",
            "copy": {
                "name": "agentpoolcopy",
                "count": "[length(parameters('agentPools'))]"
            },
            "dependsOn": [
                "[resourceId('Microsoft.ContainerService/managedClusters',parameters('name'))]"
            ],
            "properties": {
                "count": "[parameters('agentPools')[copyIndex()].count]",
                "vmSize": "[parameters('agentPools')[copyIndex()].vmSize]",
                "osDiskSizeGB": "[parameters('agentPools')[copyIndex()].osDiskSize]",
                "vnetSubnetID": "[variables('subnetId')]",
                "maxCount": "[parameters('agentPools')[copyIndex()].maxCount]",
                "minCount": "[parameters('agentPools')[copyIndex()].minCount]",
                "nodeTaints": "[parameters('agentPools')[copyIndex()].taints]",
                "enableAutoScaling": true,
                "type": "VirtualMachineScaleSets"
            }
        }
    ],
    "outputs": {
    },
    "functions": [
    ]
}

**Comment by ramakrishnateja** [comment]
@jluk  can you please look in to this issue

**Comment by jluk** [comment]
Acknowledging we're working with our support team to diagnose the problem. The latest info should be able to be found through the SR (119110624005588) but I will try to relay the same information here.

**Comment by jluk** [comment]
We believe it is due to a calico daemonset not tolerating all possible taint permutations with noSchedule that could land on a node. The gap caused by this is an inability to use Calico networking with user defined taints which specify noSchedule, you can only use noExecute taints until this gap is resolved.

The work to fix noSchedule scenarios with calico has been logged and this issue will remain open to track that work to resolve.

**Comment by mlushpenko** [comment]
@jluk any way to confirm that we have the same issue? our cluster isn't working right now, we use calico and by isn't working I mean this issue in tunnelfront:
```
root@aks-system-10099729-vmss000000:~# docker logs 9f95c2b27f7d
[ Thu Nov 14 18:03:16 UTC 2019 ] INF: Starting: Every:[5] kubeconfig:[/etc/kubernetes/kubeconfig/kubeconfig] SSH-Server:[aks-dev-cdce5e25.hcp.westeurope.azmk8s.io]
[ Thu Nov 14 18:03:16 UTC 2019 ] INF: Creating tunnel interface
[ Thu Nov 14 18:03:16 UTC 2019 ] INF: device tun0 was already setup
[ Thu Nov 14 18:03:16 UTC 2019 ] INF: ip Configuration:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tun0: <NO-CARRIER,POINTOPOINT,MULTICAST,NOARP,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 500
    link/none
    inet 192.0.2.200 peer 192.0.2.100/32 scope global tun0
       valid_lft forever preferred_lft forever
1947: eth0@if1948: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether b2:4b:44:90:8b:69 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.40.0.231/16 scope global eth0
       valid_lft forever preferred_lft forever
[ Thu Nov 14 18:03:16 UTC 2019 ] INF: ******************
[ Thu Nov 14 18:03:16 UTC 2019 ] INF: iptables were previously configured..
[ Thu Nov 14 18:03:16 UTC 2019 ] INF: current ip tables
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination

Chain INPUT (policy ACCEPT)
num  target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
num  target     prot opt source               destination
1    MASQUERADE  all  --  anywhere             anywhere
2    MASQUERADE  all  --  anywhere             anywhere
Chain INPUT (policy ACCEPT)
num  target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
num  target     prot opt source               destination
1    ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination
[ Thu Nov 14 18:03:16 UTC 2019 ] INF: ****************
[ Thu Nov 14 18:03:16 UTC 2019 ] INF: Attempting to download tunnel-front secret
Unable to connect to the server: dial tcp: lookup aks-dev-cdce5e25.hcp.westeurope.azmk8s.io on 168.63.129.16:53: read udp 10.40.0.231:53599->168.63.129.16:53: i/o timeout
[ Thu Nov 14 18:04:36 UTC 2019 ] WRN: Attempt:[1] - failed:Get secret:[tunnelfront] from kubernetes. will retry
Unable to connect to the server: dial tcp: lookup aks-dev-cdce5e25.hcp.westeurope.azmk8s.io on 168.63.129.16:53: read udp 10.40.0.231:43157->168.63.129.16:53: i/o timeout
[ Thu Nov 14 18:05:59 UTC 2019 ] WRN: Attempt:[2] - failed:Get secret:[tunnelfront] from kubernetes. will retry
Unable to connect to the server: dial tcp: lookup aks-dev-cdce5e25.hcp.westeurope.azmk8s.io on 168.63.129.16:53: read udp 10.40.0.231:33017->168.63.129.16:53: i/o timeout
[ Thu Nov 14 18:07:21 UTC 2019 ] WRN: Attempt:[3] - failed:Get secret:[tunnelfront] from kubernetes. will retry
```

Because of this, `coredns` and `metrics-server` aren't running and therefore the whole cluster.

and we have one node with `nvidia.com/gpu=true:NoSchedule` taint, how could I validate if it's the same issue?

**Comment by jluk** [comment]
@mlushpenko this issue should only affect scheduling of calico pods so I don't believe it impacts tunnelfront, in order to get you the fastest help and resolution possible - could you open a support request to get some hands-on help?

**Comment by mlushpenko** [comment]
Opened ticket `119111822001379` in case you can see the details or help out with troubleshooting :)

**Comment by jluk** [comment]
This issue wrt calico scheduling should be resolved now per release notes: https://github.com/Azure/AKS/releases/tag/2019-11-11
