### ISSUE TITLE
Allow to control upgrade policy for VMSS pools

### ISSUE THREAD

**Issue by invidian** [Azure/AKS#1302]
Currently, when you create AKS cluster with VMSS node pool, the pool has `Upgrade policy: manual` set and it seems there is no way to set that during creation time. Additionally, when changed after creating the cluster, the upgrades won't trigger the cordoning on the node, as [kured](https://github.com/weaveworks/kured) would do. I have a following question:
- if I use Kured, which will reboot the nodes in graceful fashion, will the reboot also upgrade the VMSS instance model?
- if Kured does not work, are there any plans to create some controller, which will make sure that all VMSS instances are up to date and which will coordinate graceful upgrades?

**Comment by jluk** [comment]
Issue #893 may address these questions, could we move this discussion there?

The VMSS model is managed by AKS, so any configs you would need to set should be set through the AKS API so you have the right expectation of the goal state known to AKS.

The issue above should also address the need for kured, once shipped an automated path of using that feature should move towards the described goal of graceful upgrades to the goal state set within AKS.
