### ISSUE TITLE
[Feature] Cluster automatic upgrade for K8s versions

### ISSUE THREAD

**Issue by jluk** [Azure/AKS#1303]
**What happened**: Today, cluster upgrades require manual intervention and explicit setting of the major.minor.patch versions for Kubernetes. This process must be done at semi-regular intervals to stay within the supported window of Kubernetes versions and would benefit from reduced friction.

**What you expected to happen**: User is able to opt-in to using automatic upgrades for a given AKS clusterl. The cluster set for auto-upgrade would be upgraded with a newer Kubernetes version in-line with a setting defined by the user which dictates frequency and what the target version should be.

**Comment by ezYakaEagle442** [comment]
Hi @jluk ,
This is very good news , this will make customer's life easier.
May I suggest that this new feature proposes as well some options to set some upgrade schedule rules , for instance not to perform upgrade/reboot during business hours on production cluster running mission critical apps ? The idea is similar to Kured [PR-66](https://github.com/weaveworks/kured/pull/66) giving new arguments to set a schedule : 
--reboot-days, --start-time, --end-time, and --time-zone.

Thanks,
Steve

**Comment by mikedizzle** [comment]
I came across this issue and saw the announcement in Jan of 2019 (https://azure.microsoft.com/en-us/updates/aks-cluster-auto-upgrade/) that this is being worked on, but the feature isn't even in preview yet, correct?

**Comment by Bessonov** [comment]
activity

**Comment by mikedizzle** [comment]
Unstale!

**Comment by ezYakaEagle442** [comment]
Hi @jluk  any update on this issue please ?

**Comment by ezYakaEagle442** [comment]
Now In Preview : [https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel-preview](https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel-preview)
Thanks !

**Comment by vnekatesharao** [comment]
When can we expect this in General availability (GA) ?

**Comment by seanmck** [comment]
https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel

**Comment by DevOps-zhuang** [comment]
> https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel

it seems the current preview version doesn't support setting the timeslot to enable the upgrade? like, I only want to upgrade during weekend.

**Comment by tantweiler** [comment]
Is there a way to verify to which upgrade channel the cluster has been set?

**Comment by NetForce1** [comment]
> it seems the current preview version doesn't support setting the timeslot to enable the upgrade? like, I only want to upgrade during weekend.
That seems to be covered by this feature: https://docs.microsoft.com/en-us/azure/aks/planned-maintenance

**Comment by asubmani** [comment]
The document page here doesn't have the "preview" keyword in the title.. does it mean this is GA?

https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel

**Comment by mattareddy357** [comment]
is Auto-Upgrade Channel for AKS is GA?
https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel

**Comment by Aaron-ML** [comment]
Adding to the last few comments, I'd love to know when this is expected to be GA if it isn't already.

**Comment by wangyira** [comment]
@palma21 Do you know if this in GA? The [doc](https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel) doesn't have preview in the title.

**Comment by bergmeister** [comment]
Still in preview but not for much longer, see https://github.com/Azure/AKS/issues/1486#issuecomment-882011208

**Comment by palma21** [comment]
GA
