### ISSUE TITLE
CoreDNS - use forward plugin instead of proxy plugin moving forward

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#1304]
AKS will update the coredns images to v1.6.6 on the upcoming releases.
 
The use of the "proxy" plugin in CoreDNS is deprecated in [CoreDNS v1.5.0](https://coredns.io/2019/04/06/coredns-1.5.0-release/)+ in favor of the "forward" plugin. 

AKS asks that all users leveraging the deprecated "proxy" plugin replace it with the "forward" plugin.

AKS will notify customers to use the "forward" plugin to follow resolution of [issue #1443](https://github.com/coredns/coredns/issues/1443) on the CoreDNS project.

After the notification and email was received users have 30 days to update that configuration.

**Comment by mikeeq** [comment]
@palma21 when was the update supposed to take place? We recently updated our cluster to v1.13.12 and CoreDNS is still on v1.2.6.

```
➜ kubectl get nodes -o wide               
NAME                       STATUS   ROLES   AGE   VERSION    INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-agentpool-  Ready    agent   9d    v1.13.12    -    <none>        Ubuntu 16.04.6 LTS   4.15.0-1063-azure   docker://3.0.7
aks-agentpool-   Ready    agent   9d    v1.13.12   -    <none>        Ubuntu 16.04.6 LTS   4.15.0-1063-azure   docker://3.0.7
```

```
➜ kubectl -n kube-system get deployment coredns -o wide
NAME      READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES                                     SELECTOR
coredns   2/2     2            2           9d    coredns      aksrepos.azurecr.io/mirror/coredns:1.2.6   k8s-app=kube-dns,version=v20
```

**Comment by palma21** [comment]
Hi @mikeeq we're planning for a bit after the thanksgiving holidays, we're giving some time for customers to move away from proxy to forward and notifying all of them.

**Comment by RichardNixon52** [comment]
Hi @palma21, any updates on this issue? Is there a rollout date for newer version of CoreDNS?

**Comment by palma21** [comment]
Right now we're looking at the first release of Jan, the number of clusters using deprecated plugins was higher than expected and we're looking to move all to forward. 

Do you have a specific requirement around the next/new version?

**Comment by RichardNixon52** [comment]
We are having issues with import reload, this should be fixed according to this thread https://github.com/Azure/AKS/issues/841 in v1.6.1. 

What version is likely to be applied in the upgrade?

**Comment by palma21** [comment]
Thanks @RichardNixon52  
we'll apply v1.6.2 

We've finished patching all clusters and are just sending the last messages, we're currently in Holiday freeze and we'll proceed with the rollout in Jan. I'll post back here once it starts and finishes

**Comment by RichardNixon52** [comment]
Hi @palma21 
just got a couple of questions, is there a specific Kubernetes version that is required to use v1.6.2 CoreDNS version? 
Is it necessary to recreate the clusters to upgrade the version?

**Comment by RichardNixon52** [comment]
Hi @palma21 
just got a couple of questions, is there a specific Kubernetes version that is required to use v1.6.2 CoreDNS version? 
Is it necessary to recreate the clusters to upgrade the version?

**Comment by RichardNixon52** [comment]
Hi @palma21 
just got a couple of questions, is there a specific Kubernetes version that is required to use v1.6.2 CoreDNS version? 
Is it necessary to recreate the clusters to upgrade the version?

**Comment by palma21** [comment]
Any supported k8s version on AKS. You will not need to do a cluster upgrade, core dns is one of the managed components.

**Comment by rudolphjacksonm** [comment]
Is there a specific date in mind when these updates will go out? We're keen to implement a fix that requires this plugin 👍

**Comment by rudolphjacksonm** [comment]
Hi @palma21 , any news on when the upgrades will roll out to UK South and UK West? All of our clusters are still on v1.2.6, and one of them that was rebuilt recently is on v1.3.1.

**Comment by palma21** [comment]
The rollout is 2/3 complete. We expect to reach all regions in the few couple of days.

We have actually already finished the UK. Can you confirm that you don't have any clusters using the proxy plugin?

**Comment by palma21** [comment]
This is one of my clusters in UK South:
![image](https://user-images.githubusercontent.com/7065724/73743678-fccd2c00-4703-11ea-882d-7a7ebd9157e8.png)

**Comment by RichardNixon52** [comment]
Hi @palma21,

all of our clusters are upgraded to v1.6.6. 
Thanks for keeping us up to date!

**Comment by rudolphjacksonm** [comment]
Updated on our end as well 👍

**Comment by palma21** [comment]
After updating all clusters not using the Proxy Plugin and sending users portal notifications and emails to all users using it, AKS will continue with the 1.6.6 rollout to the rest of the fleet.
