### ISSUE TITLE
Pod stuck in ContainerCreating state because of CNI failure

### ISSUE THREAD

**Issue by uipo78** [Azure/AKS#1307]
**What happened**:
Pod stuck in `ContainerCreating` because `NetworkPlugin cni failed to set up pod "fluentd-fluentd-elasticsearch-98knf_logging" network: unexpected end of JSON input`.

**What you expected to happen**:
Pod starts up successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Not really sure. I don't even know why this is showing up in the first place.

**Anything else we need to know?**:
The full error shown by `kubectl describe`:
```
  Warning  FailedCreatePodSandBox  2m39s (x7780 over 5d17h)  kubelet, aks-akspool-15120912-0  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "c06a7ba68eb772f51f52305d7fa460d115eedbe8fb2765578566431ad9ef9b66" network for pod "fluentd-fluentd-elasticsearch-98knf": NetworkPlugin cni failed to set up pod "fluentd-fluentd-elasticsearch-98knf_logging" network: unexpected end of JSON input
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.6
- Size of cluster (how many worker nodes are in the cluster?) 8
- Other: Every one of my worker nodes is a Linux box.

**Comment by JasonHaley** [comment]
I'm seeing the same thing the past 2 days in my cluster but it only seems to be effecting cronjob pods. Same version of kubernetes 1.14.6

**Comment by wasker** [comment]
I'm observing this in westus2 on k8s 1.16.4:

Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "f030eef484f83a7b1695e9f12e9702c41f51484513dc24005f097a293ae09108" network for pod "xxx-test-6cbd58d499-966pj": networkPlugin cni failed to set up pod "xxx-test-6cbd58d499-966pj_xxx" network: unexpected end of JSON input

**Comment by tamilmani1989** [comment]
@uipo78 

1. what version of cni is this?
2. If possible can you provide all logs start with azure-vnet under /var/log/azure-vnet*.log?
3. subscripiton id, agent VM name where pod creation failed and approximate timestamp of failure

@neaggarwMS

**Comment by uipo78** [comment]
We no longer use Azure, so I can't provide that information.

**Comment by palma21** [comment]
Closing as non-applicable anymore. Thank you for circling back. 
If anyone has this issue please do open a separate issue.
