### ISSUE TITLE
Container Logging Backoff event to Log Analytics during scale down using HPA

### ISSUE THREAD

**Issue by midhun-mohan** [Azure/AKS#1308]
**What happened**:
We are using Horizontal Pod Autoscaler in our AKS cluster and is configured for CPU as  "  targetCPUUtilizationPercentage: 70". 
HPA works perfectly during scale up. 
But during the scale down , it logs event with following data to log Analytics
"""Reason: BackOff
Message: Back-off restarting failed container"""

**What you expected to happen**:
There should not be any events as above as this should be a perfect scale down without impact.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1",
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10",
- Size of cluster (how many worker nodes are in the cluster?) 7 Worker nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) : HTTP Microservices writtn in Go and Java
- Others:

**Comment by immunochomik** [comment]
We are seeing CrashLoopBackOff for omsagent-rs pod in k8s 1.14.8 after scaled down

**Comment by palma21** [comment]
Are these issues still visible. Do they pertain to HPA or Azure monitor for container pods?
