### ISSUE TITLE
AKS supports defining a system-pod node pool to prefer scheduling & consolidate per nodepool constraints

### ISSUE THREAD

**Issue by djsly** [Azure/AKS#1309]
**What happened**:
With the requirement to have a default node pool with AKS, we would like to create a small agent pool dedicated for the workload that AKS deploys. 

**What you expected to happen**:
Right now, even though I can add a taint on the nodes for the default agent pool, I cannot provide extra configuration for the kube-system pods to add tolerations

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jluk** [comment]
@djsly thanks for opening this request, a few questions for folks.

1. Is your intent to dedicate the pool for the system-critical pods and not sched other apps to these nodes? 
1. Is the cost impact of (1) a large issue if true or negligible? FWIW this is a good practice given isolation can help maintain health away from rogue apps without reqs/limits.
1. Is it important for you to be able to move which pool may be dedicated for your system-pods? For example wanting to swap the vm sku of all pools in an existing cluster.
1. Is there a rational name you would prefer to see for a pool assigned for housing these kube-system pods?

**Comment by djsly** [comment]
our intent would be to leverage the default node pool as a static node pool where we could un system-critical pods related to the infra, no application pods/services.

The main driver is that the node pool can be easily created/removed except for that single one. 
When performing VM upgrades, it is often the case where we will have to create a new node pool (windows) to get the latest base image, drain the pods from the old pool, and delete the old agent pool. We can achieve blue/green using a pool lifecycle strategy. 

I would say, that due to the design limitation of the static single linux pool. It sorts of make it a natural fit for the AKS provided pods. For now, we went with `default` as the pool name, in the past before my AKS days, we used to have a dedicated node pool for `infra` I guess both of these names are too generic ;)

**Comment by jluk** [comment]
The related ask for support in Terraform is captured here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/6058

**Comment by jluk** [comment]
This should be available everywhere now for clusters with at least one system pool. Learn more at aka.ms/aks/nodepool/mode thanks for the feedback!

**Comment by djsly** [comment]
@jluk I was reading the Documentation and while we have a Label, 

`System node pool nodes each have the label kubernetes.azure.com/mode: system.` 

Do we know if we have taints ?

**Comment by jluk** [comment]
System mode pools only place labels to support preferred scheduling. This does not include taints to not block customers who may wish to only run one node pool, although isolating the system pods is the recommended approach.

If you want to guarantee system pods isolating to system pools, you can opt in by adding a custom taint which is tolerated by AKS system pods to completely disallows non-system pods to land in the system pool. The taint is `CriticalAddonsOnly=true:NoSchedule`. This is a gap in the docs today but we will be adding that shortly.

**Comment by ToruMakabe** [comment]
@jluk Critical addons such as CoreDNS could be scheduled to non-system node pools with taint "CriticalAddonsOnly=true:NoSchedule" only. So, I patch critical addons with nodeSelecter "kubernetes.azure.com/mode": "system". Is it a supportable configuration? I am concerned about overwriting from AKS control plane after my patching.

**Comment by felipecruz91** [comment]
@jluk I am trying to isolate system pods to run exclusively in the system node pool.

I've created an AKS cluster in ARM template using the API version `2020-03-01` that defines two pools, system pool and user node pool.

After specifying the `CriticalAddonsOnly=true:NoSchedule` taint to the system pool in the ARM template, the cluster was created and system pods like `core-dns`, `oms-agent`, or `metrics-server` among others got created in the user node pool.

![image](https://user-images.githubusercontent.com/15997951/83389288-4139b180-a3f0-11ea-8dec-4380231ac2df.png)

![image](https://user-images.githubusercontent.com/15997951/83388884-84475500-a3ef-11ea-86e1-ba127f85d6c2.png)
