### ISSUE TITLE
Applying Managed identity with ARM template fails on re-deploy

### ISSUE THREAD

**Issue by slavizh** [Azure/AKS#1312]
Hi,
I have ARM template that I am deploying to create new managed cluster. I am specifying the creation of Managed Identity like this in the resource.

```
"identity":{
                "type": "SystemAssigned"
            }
```

Creating the cluster for the first time succeeds and the MI is also created. Re-deploying with the same code fails with message:

Changing property 'identity' is not allowed.

this means that the resource provider does not honor ARM template rules and because of the the resource is not idempotent. I expect this to work when this is GA.

**What happened**:
Failure when I do redeploy with managed identity configured.

**What you expected to happen**:
I expected that re-deploy will succeed 

**How to reproduce it (as minimally and precisely as possible)**:
Described above.

**Anything else we need to know?**:
No.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.8
- Size of cluster (how many worker nodes are in the cluster?) 3 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) N/A
- Others: N/A

**Comment by norshtein** [comment]
Thanks for reporting. We figured out what happened, the issue will be fixed soon.

**Comment by mitchdenny** [comment]
Just wanted to add to this as I'm playing with the managed identity preview. I've found that the following also doesn't work:

1. Scaling the cluster
2. Upgrading the cluster

Here is an example:

```
PS C:\Code\azure-voting-app-redis> az aks upgrade --resource-group sandbox --name sandbox --kubernetes-version 1.15.5   Kubernetes may be unavailable during cluster upgrades.
Are you sure you want to perform this operation? (y/n): y
Operation failed with status: 'Bad Request'. Details: Changing property 'identity' is not allowed.
```

**Comment by williamayerst** [comment]
I am also getting this while running set-azresource on an AKS object when I have modified the api server authorised IP ranges

**Comment by TomGeske** [comment]
This one should be fixed in the meantime. I'm going ahead closing this one. Please, feel free to keep commenting if you have further questions.
