### ISSUE TITLE
Error when MI is used along with agentPools API in ARM template

### ISSUE THREAD

**Issue by slavizh** [Azure/AKS#1315]
When using Managed Identity and you create pools with ARM template and Microsoft.ContainerService/managedClusters/agentPools api you get error like

 "Provisioning of resource(s) for Agent Pool pool3 failed. Error: {\n  \"code\": 
\"InvalidTemplateDeployment\",\n  \"message\": \"Deployment failed with multiple errors: 
'Authorization failed for template resource 'akslz0001-agentpool' of type 
'Microsoft.ManagedIdentity/userAssignedIdentities'. The client 
'fcad0bc1-4a00-4de4-af64-54ce89664eed' with object id 'fcad0bc1-4a00-4de4-af64-54ce89664eed' does 
not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/write' at 
scope '/subscriptions/98301215-05d3-4901-88ad-bc364044a61c/resourceGroups/lz-k8s-1/providers/Micro
soft.ManagedIdentity/userAssignedIdentities/akslz0001-agentpool'.:Authorization failed for 
template resource '232049b4-e7d3-4243-b36b-609ccabf6ee6' of type 
'Microsoft.Authorization/roleAssignments'. The client 'fcad0bc1-4a00-4de4-af64-54ce89664eed' with 
object id '7417758c-ccc7-483f-888c-f53a12c58fda' does not have permission to perform action 
'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/98301215-05d3-4901-88ad-bc364044a61c9/resourceGroups/lz-k8s-1/providers/Microsoft.Authorization/roleAssignments/232049b4-e7d3-4243-b36b-609ccabf6ee6'.'\"\n }"

This error is also generated in Azure activity log when creation is done via Azure CLI ( az aks create -g MyResourceGroup -n cls001 --enable-managed-identity --generate-ssh-keys --debug). There though the error is not stopping the command execution.

**What happened**:
Error is generated when MI and agentPools api is used.

**What you expected to happen**:
Not get error.

**How to reproduce it (as minimally and precisely as possible)**:
Described above

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- Size of cluster (how many worker nodes are in the cluster?) N/A
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) N/A
- Others:

**Comment by slavizh** [comment]
In the resource group for the nodes there is one error about role assignment. I am not sure if it is related. the error is the following:

"statusMessage": "{\"error\":{\"code\":\"PrincipalNotFound\",\"message\":\"Principal 9a9e1bfc789f4673bec92c0d0c188ce2 does not exist in the directory 2e08e47d-98e2-4798-86a2-bbca94b25616.\"}}"

**Comment by slavizh** [comment]
Also I have tested adding additional pool with command :

az aks nodepool add --resource-group myResourceGroup --cluster-name myAKSCluster --name cls001 --node-count 3 --kubernetes-version 1.13.12

I am getting the same errors and this time operation fails even in CLI.

**Comment by jluk** [comment]
@feiskyer do you know who from Thomas' team can help drive this feedback

**Comment by feiskyer** [comment]
@norshtein could you help to take a look?

**Comment by norshtein** [comment]
Thanks for reporting, we found the root cause, the issue will be fixed soon.
