### ISSUE TITLE
Issue creating AKS Cluster with Terraform - Service Principal Invalid

### ISSUE THREAD

**Issue by jmcshane** [Azure/AKS#1316]
**What happened**:

AKS cluster failed to provision with this error:

azurerm_kubernetes_cluster.aks: Error creating Managed Kubernetes Cluster "abc123" (Resource Group "zyx987"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The credentials in ServicePrincipalProfile were invalid. Please see https://aka.ms/aks-sp-help for more details. (Details: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: ae5b4f5b-182e-46f8-bad6-a17a66641101\r\nCorrelation ID: fd735819-1141-4ac8-a015-e266c4b2db98\r\nTimestamp: 2019-11-13 16:49:19Z","error_codes":[7000215],"timestamp":"2019-11-13 16:49:19Z","trace_id":"ae5b4f5b-182e-46f8-bad6-a17a66641101","correlation_id":"fd735819-1141-4ac8-a015-e266c4b2db98","error_uri":"https://login.microsoftonline.com/error?code=7000215\"})"

This failure is intermittent.

**What you expected to happen**:

The cluster provisioning to succeed regularly, rather than failing intermittently.

**How to reproduce it (as minimally and precisely as possible)**:

AKS terraform script:

```
resource "azuread_service_principal" "service_principal" {
  application_id = "${azuread_application.application.application_id}"
}

resource "random_string" "password" {
  length  = 32
  upper   = true
  lower   = true
  number  = true
  special = true
}

resource "azuread_service_principal_password" "service_principal_password" {
  service_principal_id = "${azuread_service_principal.service_principal.id}"
  value                = "${random_string.password.result}"
  end_date_relative    = "8760h"
}

resource "azurerm_kubernetes_cluster" "aks" {
  name                = "${var.name}"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
  dns_prefix          = "${var.dns_prefix}"
  kubernetes_version  = "${var.kubernetes_version}"

  ... Everything else default
  service_principal {
    client_id     = "${azuread_service_principal.service_principal.id}"
    client_secret = "${random_string.password.result}"
  }
  
}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.8
- Size of cluster (how many worker nodes are in the cluster?): 2 Standard 2GB nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Empty cluster provisioning
- Others: Failures occur with both terraform 0.11 and 0.12 30-40% of the time, it seems to be a timing issue because when i put in a sleep it works.

There is an azuread terraform issue tracking this as well: https://github.com/terraform-providers/terraform-provider-azuread/issues/128

**Comment by jmcshane** [comment]
Created as per recommendation in https://github.com/MicrosoftDocs/azure-docs/issues/42742

**Comment by jluk** [comment]
@jmcshane are you seeing this SP error when provisioning without Terraform?

I read the related TF issue and it looks like it gets resolved after adding a sleep, which is a known issue in Active Directory that SP propagation is extremely slow and it's described a bit in issue #1206. It's possible your issues is directly impacted by that.

**Comment by mariojacobo** [comment]
Same issue here. It's happening intermittently. Luckily, we are running terraform inside a Jenkins pipeline and I've added a retry step for this particular stage in case of failure.  Adding a sleep delay may also work, but then you would need a local-exec to add the sleep and a depends_on for AKS to be executed after local-exec.

**Comment by jtackaberry** [comment]
I also routinely hit this.
