### ISSUE TITLE
Clock skew detected in AKS clusters

### ISSUE THREAD

**Issue by AlexDHoffer** [Azure/AKS#1317]
**What happened**: 

- The Prometheus Node Exporter reports that there is clock skew detected. This occurs across multiple clusters hosted in the West US region through Azure.

**What you expected to happen**: 

- Clock skew should be a non-issue with regards to the cluster.

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy an AKS cluster and monitor the clock skew.

**Anything else we need to know?**:

- 3 separate AKS clusters report clock skew. All are hosted in west-us.
- This problem began occurring today. This issue did not arise previously. before.

Here is a picture of the clock skew estimates across the three environments in question:

![image](https://user-images.githubusercontent.com/19369483/68902776-0c813980-06ee-11ea-8ca6-96bf805bcf72.png)

The legend has been omitted for confidentiality reasons.

**We also host the same service set in the west-europe region, and have not seen clock skew impact resources in that region.**

**Environment**:

- Kubernetes version (use `kubectl version`): 1.15.5
- Size of cluster (how many worker nodes are in the cluster?): Each cluster affected has either 4 or 5 nodes
- General description of workloads in the cluster: APIs and microservices including user-facing applications

**Comment by kmoussa** [comment]
I have the same in West Europe regions on two clusters kubernetes version is 1.14.8

**Comment by balajivenkataraman** [comment]
We have the same problem in UK South. Kubernetes cluster 1.14.8 on 3 clusters and all of them report **_"clock skew detected for node(s):"_**

**Comment by jon-walton** [comment]
We're also frequently experiencing this in East Asia, however not on any of our South Central US clusters

**Comment by rpocase** [comment]
Seeing the same problem in east-us (single cluster, 4 nodes in one node pool). This started occurring after upgrading to 1.16.7 (from 1.15.5).

**Comment by robinkb** [comment]
I am seeing the same thing on three separate clusters, all in West Europe. I am only noticing it now after deploying an alerting solution, but it is likely that this has been happening for several months, if not longer.

**Comment by monaka** [comment]
Same here. wus-2, 1.15.10. And I guess this is not caused by AKS but Linux kernel or lower layer.

I'm watching my Linux instances on Azure VM with node_exporter. The issue is causes there also.

**Comment by bdschaap** [comment]
This is happening to our AKS clusters as well but not our on-prem Rancher K8s clusters.

**Comment by palma21** [comment]
We're looking into this with the Azure Linux team in order to improve time sync reliability. I'll post here as soon as we have findings

**Comment by masters3d** [comment]
Are there way any mitigation steps?

**Comment by palma21** [comment]
You can use a Daemon set to change the timesync servers in case that helps.

We found a few cases where the ubuntu default servers might not be reliable across the world so we'll be moving to host sync.

**Comment by djsly** [comment]
Any quick remediation / command to force a resync ? We are currently affected on UKSOUTH

**Comment by ffais** [comment]
I have same problem in WESTEU, maybe this can help troubleshooting process:

`azureuser@aks-nodepool1-vmss0:~$ sudo service systemd-timesyncd status
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
  Drop-In: /lib/systemd/system/systemd-timesyncd.service.d
           └─disable-with-time-daemon.conf
   Active: inactive (dead)
Condition: start condition failed at Mon 2020-11-16 10:56:27 UTC; 18s ago
           ConditionFileIsExecutable=!/usr/sbin/chronyd was not met
     Docs: man:systemd-timesyncd.service(8)
`

**Comment by djsly** [comment]
Can you please share you Vmss Os disk image version ? 

There was a known issue with 2020.10.28 which was patch afterward. You might just need to recreate your agent pool and you should be all set.

**Comment by ffais** [comment]
This is the version actually in use 2020.10.28.

**Comment by djsly** [comment]
Replace your node pool it should fix it

**Comment by xuto2** [comment]
or do a node image upgrade to the latest vhd version 2020.11.11 when it's ready in this week's release.

**Comment by palma21** [comment]
Host-sync and chrony are now used from 2021-03-08 relese
