### ISSUE TITLE
InvalidApiVersionParameter when using Cluster autoscaler and managed identity

### ISSUE THREAD

**Issue by ams0** [Azure/AKS#1318]
**What happened**:

Cluster autoscaler (deployed with helm chart) throws an `InvalidApiVersionParameter` error

**What you expected to happen**:

CA to run fine

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy a 1.15.3 with `--enable-managed-identity` flag
- Retrieve the `principalId` of the MSI created and assign Owner role to the sub (overkill, I know)
- Deploy CA with Helm (3):

```
helm upgrade --install  \
--set cloudProvider=azure \
--set rbac.create=true \
--set azureUseManagedIdentityExtension=true \
--set azureNodeResourceGroup=MC_k8s_playground103_westeurope \
--set azureResourceGroup=k8s \
--set azureClusterName=playground103 \
--set azureTenantID=<tenant> \
--set azureSubscriptionID=<sub> \
--set autoscalingGroups[0].name=base \
--set autoscalingGroups[0].maxSize=5 \
--set autoscalingGroups[0].minSize=1 \
ca stable/cluster-autoscaler
```

CA runs but throws this error in logs:

```
E1115 21:38:51.706775       1 azure_container_service_pool.go:454] Azure client list vm error : compute.VirtualMachinesClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2018-10-01' is invalid. The supported versions are '2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
F1115 21:38:51.706833       1 azure_cloud_provider.go:143] Failed to create Azure Manager: compute.VirtualMachinesClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2018-10-01' is invalid. The supported versions are '2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
```

Could it be related to this [code](https://github.com/kubernetes/autoscaler/blob/8d667b5a5aa4623a2377077e43809bb53c178c77/cluster-autoscaler/cloudprovider/azure/azure_cloud_provider_test.go#L22)?

**Anything else we need to know?**:

Incidentally I notices that the value reported by `az aks show -g k8s -n playground103 -o json --query identity.principalId` for the cluster does *not* coincide with the managed indentiy object created in the MC_* resource group:

```
$ az aks show -g k8s -n playground103 -o tsv --query identity.principalId
d02b274a-72fa-4d59-9b80-9c747808b8c4
```

```
$ az identity list --query [0].principalId -o tsv
f343bd07-3698-4dd9-b0de-ea42d7fd95af
```

is that intended?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.5
- Size of cluster: 3

**Comment by feiskyer** [comment]
@ams0 Thanks for reporting the issue, seems we need to make some updates in CA for compute api-version

**Comment by jluk** [comment]
FYI @marwanad 

As for the SP differences reported I *think* it's due to the preview limitation for MI right now which still requires an SP for add-ons but @feiskyer can correct me.

**Comment by feiskyer** [comment]
> As for the SP differences reported I think it's due to the preview limitation for MI right now which still requires an SP for add-ons but @feiskyer can correct me.

Right, this is due to MI is still under preview.

@ams0 May I know which region are you deploying the CA to? I rechecked the compute API, and found 2018-08-01 is supported on West Europe.

**Comment by ams0** [comment]
yes, was West Europe. Thanks for the link, I understand CA a bit more now (it would be great to have helm examples in that doc too).

**Comment by nilo19** [comment]
Got a different error message using helm and aks version 1.15.7.

```log
Azure client list vm error : azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/c4528d9e-c99a-48bb-b12d-fde2176a43b8/resourceGroups//providers/Microsoft.Compute/virtualMachines?api-version=2018-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
F0225 05:31:43.652668       1 azure_cloud_provider.go:143] Failed to create Azure Manager: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/c4528d9e-c99a-48bb-b12d-fde2176a43b8/resourceGroups//providers/Microsoft.Compute/virtualMachines?api-version=2018-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
```

**Comment by jluk** [comment]
Closing now that MI is GA, if issues are still seen please open a new issue and we can revisit
