### ISSUE TITLE
Changing node vm-size of existing cluster

### ISSUE THREAD

**Issue by RainerAtSpirit** [Azure/AKS#132]
According to https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_create it's posssible to change the `node-vm-size` during creation of a cluster.
```
az aks create --name myK8s --resource-group myRG --node-vm-size=Standard_XXXX 
```

Is it possible to change the node size for an existing cluster as well?

**Comment by sauryadas** [comment]
No changing the agent size is not allowed. In the future we plan to support multiple node pools wherein you can create different pools with different VM sizes.

**Comment by przemolb** [comment]
This is pretty bad design decision to not support it. You cannot really predict future workload. Two days ago I created small cluster with a lot of memory but small number of CPU (many pods which are active from time to time) but today it turned out we need much more CPUs. I scaled it up by adding new nodes but this is not what we want.

**Comment by jasonkenneth** [comment]
When are y'all targeting for multiple node pool support to become available?

**Comment by joaocc** [comment]
Any news on this? Is there any workaround (like manually upgrading a node VM size via Azure Portal)?

**Comment by joaocc** [comment]
[similar to #287)

**Comment by alexvicegrab** [comment]
This is indeed an important issue, as it's difficult to foresee the future load of a cluster, and limiting scaling to horizontal is not ideal.

**Comment by alexvicegrab** [comment]
To be fair, I managed to change the size of a machine by manually upgrading the node in the Azure portal. So far so good, but have not done enough testing to confirm if this is doable in a production environment.

**Comment by alexvicegrab** [comment]
@sauryadas, what problems (if any) can we expect if we manually update the node Sizes (apart from downtime for the apps running on those nodes if we don't use replication)

**Comment by sauryadas** [comment]
Try upgrading and scaling after manual updates and check for issues ...

Thanks
Saurya
________________________________

**Comment by TallOrderDev** [comment]
This seems like a reasonable request for this feature, as if you are still pre prod you will not need/want to run large costly vm's, once load-testing and such starts then you'll want to upgrade to prod size vm. The fact that you have to create another cluster to set the real vm size seems to defeat the purpose os modular and configurable kubernetes.

**Comment by alexvicegrab** [comment]
And manually updating images is error-prone and in my experience (YMMV) resulted in monitoring issues when using tools like Prometheus and Grafana.

**Comment by ekarlso** [comment]
Why does AKS not support this? GKE already supports adding a new node pool as far as I know to the cluster but I dont know if it supports doing it with a different vm type..

**Comment by sauryadas** [comment]
Adding a new node pool with a different vm size is coming in the next couple months . You can’t change the vm size in an existing node pool in gke

Thanks
Saurya
________________________________

**Comment by okke-formsma** [comment]
Please reopen this ticket to signal to the community you are planning to implement this missing feature in the future.

**Comment by sauryadas** [comment]
Thanks .. we will discuss this internally and update this thread.

I think a reasonable solution in the near term would be to add a new agent pool (with a different VM size)to an existing cluster (support planned in the next couple of months) when you want to, for example, move from testing(small vm size like standard d2v2 )to prod (large vm size StandardDSV13 )in the same cluster. Once you deploy the workload in the new agent pool with the large vm size you can scale down/delete the first agent pool that was used for testing

**Comment by alexvicegrab** [comment]
@sauryadas, that would be perfect.

**Comment by HK-Zhang** [comment]
it is disappointed to know the Verticle Scaling is not supported in AKS.

**Comment by sauryadas** [comment]
@HK-Zhang thanks for the feedback. Please see above for a proposed alternative solution. We will also discuss the vertical scaling internally but there is no ETA. FWIW GKE doesnt support vertical scaling Closing this issue for now.

**Comment by Nuke1234** [comment]
Hello! Is there some other thread where i can track the progress on the solution proposed from @sauryadas?

**Comment by edernucci** [comment]
@Nuke1234 unfortunately MS is not giving us any ETA on any AKS issues. This is really frustrating.

**Comment by sauryadas** [comment]
We are hoping to have node pool support by the end of September

Thanks
Saurya
________________________________

**Comment by lmcarreiro** [comment]
> To be fair, I managed to change the size of a machine by manually upgrading the node (changing the VM Size) in the Azure portal. So far so good, but have not done enough testing to confirm if this is doable in a production environment.

@alexvicegrab did you have any issues with this approach? I did the same thing, but didn't upgrade or scale the cluster yet after this change.

**Comment by dmascord** [comment]
Once you scale or upgrade the Kubernetes version, the nodes are reverted to the original size, and you will have to resize again.

**Comment by arkiaconsulting** [comment]
As a side note, in production you might be in an infrastructure as code mode, with some ARM templates. If you manually change the size, your template will be desynchronized from the reality.

**Comment by metacpp** [comment]
@sauryadas is multi-agent pools supported in AKS ?

**Comment by edernucci** [comment]
> We are hoping to have node pool support by the end of September Thanks Saurya
> […](#)
> ________________________________ From: Eder Nucci <notifications@github.com> Sent: Wednesday, August 1, 2018 8:07:48 AM To: Azure/AKS Cc: Saurya Das; Mention Subject: Re: [Azure/AKS] Changing node vm-size of existing cluster (#132) @Nuke1234<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNuke1234&data=02%7C01%7Csaudas%40microsoft.com%7C132cdb35c507492b864908d5f7c08bc3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636687328714155667&sdata=WQ0BEc4174K2%2BJj0%2F4y8sHnZwnsoXVlDAPtQd8ln1vs%3D&reserved=0> unfortunately MS is not giving us any ETA on any AKS issues. This is really frustrating. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAKS%2Fissues%2F132%23issuecomment-409608377&data=02%7C01%7Csaudas%40microsoft.com%7C132cdb35c507492b864908d5f7c08bc3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636687328714155667&sdata=hoJrQW1%2FSycsjS8ixEp7IqZz4bJTL3%2FAFW0vEUqaRuM%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOrMb0ZxmtiIT9tJRv9ryiPmcj2uCFjlks5uMcREgaJpZM4RhQhp&data=02%7C01%7Csaudas%40microsoft.com%7C132cdb35c507492b864908d5f7c08bc3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636687328714165676&sdata=tsdyN%2FB3dblrK%2FKuIZgSyQDMIk9HgM6tT6QlVG7Yh0k%3D&reserved=0>.

Welcome home, November :-)

**Comment by avik-so** [comment]
Any update on this?

**Comment by simonwh** [comment]
Status?

**Comment by trdavidson** [comment]
In summary (for everyone scrolling to the end hoping on some positive message):  
  
currently:
-  **no** Vertical Scaling  
- **no** Additional Node Pools

discussed, planned, promised but never delivered:  
- Additional node pools.

This is frankly kind of insane. This means that you have to predict perfectly what scaling size you want to work with during testing/staging since it will be the same as production.

**Comment by DDebray** [comment]
> In summary (for everyone scrolling to the end hoping on some positive message):
> 
> currently:
> 
> * **no** Vertical Scaling
> * **no** Additional Node Pools
> 
> discussed, planned, promised but never delivered:
> 
> * Additional node pools.
> 
> This is frankly kind of insane. This means that you have to predict perfectly what scaling size you want to work with during testing/staging since it will be the same as production.

This is only parcially correct as far as i know. Correct is: they do not support it as now, but they are working on it atm. There are more informations on #287

**Comment by trdavidson** [comment]
@DDebray - no, read the 'more information' referenced (#287) - the summary holds quite accurately.

**Comment by DDebray** [comment]
Yes, with redards to the current scope of AKS. However they are still working in this new feature according to the feedback hub here: https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/34917127-support-multiple-node-pool

**Comment by jnoller** [comment]
@trdavidson These features are on the roadmap, for 1H 2019 and will be linked/added to the changelog and preview document in the repo. I am sorry we do not meet your needs with this at this time, however:

This repository, all commentary, etc is governed by our Code of conduct. Calling things insane, insinuating the team is not working on this, or doesn't care is inappropriate. Therefore I'm deleting your comments from this thread.

I am also locking this thread as vertical scale up is not supported or planned at this time. VMSS, Node Pools and Availability zones are the recommended horizontal scaling system(s) and will be coming this year.
