### ISSUE TITLE
Availability Zone Support in South Africa.

### ISSUE THREAD

**Issue by DreamRivulet** [Azure/AKS#1327]
Per the documentation: https://docs.microsoft.com/en-us/azure/aks/availability-zones#limitations-and-region-availability, Availability zones for AKS is not available in South Africa yet. 
May I know there is any plan to enable this feature in South Africa? If yes, is there an ETA of this?

**Comment by jluk** [comment]
Copying content from the other issue for others to see, Azure does not have zone support in South Africa. When that is enabled AKS is able to begin work to support this, this document will detail when Azure IaaS has that support.

https://docs.microsoft.com/en-us/azure/availability-zones/az-overview
