### ISSUE TITLE
Feature: az aks install helm

### ISSUE THREAD

**Issue by karok2m** [Azure/AKS#1331]
**Is your feature request related to a problem? Please describe.**
I would like to have option to install and setup Helm through `az cli`, similar to installation of kubect through [az aks install-cli](https://docs.microsoft.com/cli/azure/aks?view=azure-cli-latest#az-aks-install-cli).

**Describe the solution you'd like**
* az cli operation similar to `az aks install-cli` to install Helm.
* An `az cli` operation to setup [SSL/TLS connection between Helm and Tiller](https://v2.helm.sh/docs/using_helm/#using-ssl-between-helm-and-tiller) would also be very useful. Though this step might be unnecessary if you chose to go with Helm 3.

**Describe alternatives you've considered**
Right now the only alternative is to manually install Helm and set up connection to the cluster.

**Comment by palma21** [comment]
@squillace @bridgetkromhout what do you think? 

seems like an interesting idea to simplify UX?

**Comment by soloitguy** [comment]
Is this relevant with the release of Helm 3 and the removal of Tiller?

**Comment by karok2m** [comment]
Setup of connection is not relevant with Helm 3. But installation through `az` is still relevant in my opinion, particularly because a lot of AKS tutorials on docs.microsoft.com reference Helm.

**Comment by karok2m** [comment]
Please note that there is [`az acr helm install-cli`](https://docs.microsoft.com/cli/azure/acr/helm?view=azure-cli-latest#az-acr-helm-install-cli) command now. It also has `--client-version` parameter, so one can install Helm 3 with it. Though currently Helm 3 does not work with `az acr helm` commands.

**Comment by squillace** [comment]
@bridgetkromhout? I think it's a good idea, but customers WILL question whether we "support" helm. But, as we do the same thing with kubectl (`az aks install-cli`), it makes sense here, too. Though I would ONLY install Helm 3. There is no good reason to make Helm 2 easier to install.

**Comment by karok2m** [comment]
@squillace, please note that  [`az acr helm install-cli`](https://docs.microsoft.com/cli/azure/acr/helm?view=azure-cli-latest#az-acr-helm-install-cli) already provides this functionality. So the issue can be close, imho.

**Comment by squillace** [comment]
I think not. But you're right, that the cli doesn't need another implementation of the same thing. But we do need an issue in the AKS docs that point out that they can install it by using that call. @iainfoulds

**Comment by palma21** [comment]
AKS Docs now is @mlearned, @zr-msft, @laurenhughes 

Zach does our helm example already leverage this?

**Comment by palma21** [comment]
Also, seems like the helm subgroup of acr is deprecated, so not sure if helm install-cli will remain there for long.

@SteveLasker could you shed some light?

![image](https://user-images.githubusercontent.com/7065724/89935378-f04ff180-dbc6-11ea-9563-6cecae516c73.png)

**Comment by SteveLasker** [comment]
Hey folks,
Some background:
A few years ago, we experimented with adding Helm (2) to ACR as another type we could persist as we felt it important to support deployment artifacts. Something we're now calling RegOps. 
While we were adding Helm 2 support, we saw the types expand, including CNAB, Singularity, OPA and others. While we did ship the `az acr helm` command subgroup we quickly realized this wouldn't scale. Would we have:
- `az acr cnab ...`
- `az acr singularity ...`
- `az acr opa ...`

This was the incubus of [OCI Artifacts](https://github.com/opencontainers/artifacts) where we inverted the solution from uniquely having the acr cli support every artifact type, to have each CLI incorporate `push/pull/run/deploy` commands across _all_ registries.

So, the deprecation of the az acr helm subgroup isn't meant to imply installing the helm cli isn't a great idea, rather it's not unique to acr. For instance, helm works uniquely on AKS and kubernetes. ACR supports an enormously growing list of services in Azure that support containers. 

We have been considering adding [ORAS](http://github.com/deislabs/oras) support to ACR, as it is more generically associated with acr workloads. Whether that becomes `az acr install-oras` or `az acr artifact push|pull`, we haven't yet decided. We're not eager to re-write ORAS in python, but that's another story...

So, please see this an endorsement that aks should support install of helm, with specific versions. And an explanation why we're depreciating in acr, as we adopted a more generic solution for acr customers. 

We'd also fully support lifting the cli code from `az acr helm` and moving it to the `aks` command group. We could even provide a pointer for customers that use `az acr helm install`.
