### ISSUE TITLE
Persistent Storage Zone Issue

### ISSUE THREAD

**Issue by silencev** [Azure/AKS#1333]
**What happened**:
My AKS cluster was created in 3 different availability zones.
however, when I realize the Azure Disk is not able to cross zones, 
I started to create another node pool with **zone 1 only**
```
az aks nodepool add -g epas-aks-rg --cluster-name XXXX --name prompool1                     --kubernetes-version 1.14.8 --zones 1 --node-vm-size Standard_E2s_v3                     --node-count 3  --node-osdisk-size 100 --os-type Linux
```
When I deploy the StateFulSets with 2 replicas in newly created pool.
Only on replica create the PV in zone 1, another creates the PV in zone 3 or zone 2

```
$ kubectl describe pv | grep zone
                   failure-domain.beta.kubernetes.io/zone=centralus-1
                   failure-domain.beta.kubernetes.io/zone=centralus-2
```

**What you expected to happen**:
All replicas should create the PV in the same Zone (zone 1)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.4.18
- Size of cluster:
  - pool1 - 2 nodes (zone 1, 2 & 3)
  - prompool1 - 3 nodes (zone 1 only)

**Comment by silencev** [comment]
resolve by adding `volumeBindingMode: WaitForFirstConsumer` in StorageClass
https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode

**Comment by andyzhangx** [comment]
To solve the disk creation issue in availability zone cluster, `volumeBindingMode: WaitForFirstConsumer` is already default setting in azure disk storage classes on new AKS clusters.
