### ISSUE TITLE
Support for Spot VMs / VMSS

### ISSUE THREAD

**Issue by desek** [Azure/AKS#1340]
With the deprecation of Low-priority VMs / VMSS a migration to Spot VMs / VMSS is needed.

Refer to the the aks-engine issue for details:
https://github.com/Azure/aks-engine/issues/2391

**Comment by jluk** [comment]
Thanks for opening @desek, I've updated issue #902 which tracks this new development. Closing this as a duplicate so we can use #902 as ongoing discussion/reference.

**Comment by alanjcastonguay** [comment]
@jluk sanity check?  That doesn’t look like the correct issue linked above.

**Comment by jluk** [comment]
Thanks @alanjcastonguay indeed it's #982
