### ISSUE TITLE
Not able to enable cluster autoscale after Aks Provisioning

### ISSUE THREAD

**Issue by partha-sarathi-sarkar** [Azure/AKS#1342]
**What happened**:
I have created a AKS with custom template now i want to enable cluster autoscale but it is not working.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
I have executed commands : **az aks update --enable-cluster-autoscaler --min-count 1 --max-count 3 -g resourcegroupName -n clusterName**

But after executing this its throw error message : **az: error: unrecognized arguments: --enable-cluster-autoscaler --min-count 1 --max-count 3**

**Environment**:
- Kubernetes version (use `kubectl version`):1.13.12
- Size of cluster (how many worker nodes are in the cluster?)1
- Others:
I am not getting any documentation for upgrade autoscale  after provisioning AKS. Kindly let me know how will i enable it

Thank in advance

**Comment by jluk** [comment]
@partha-sarathi-sarkar I'm not able to reproduce that error when enabling or updating, could you share what version of Azure CLI you running by executing `az --version`?

When I try I get success:
```
➜  ~ az aks update -g myresourcegroup -n singlepool --enable-cluster-autoscaler --min 1 --max 3
The behavior of this command has been altered by the following extension: aks-preview
DnsPrefix                          EnablePodSecurityPolicy    EnableRbac    Fqdn                                                             KubernetesVersion    Location    MaxAgentPools    Name        NodeResourceGroup                     ProvisioningState    ResourceGroup
---------------------------------  -------------------------  ------------  ---------------------------------------------------------------  -------------------  ----------  ---------------  ----------  ------------------------------------  -------------------  ---------------
singlepool5  False                      True          singlepool-<redact>.io  1.13.12              eastus      8                singlepool  MC_myresourcegroup_singlepool_eastus  Succeeded            myresourcegroup
```

**Comment by partha-sarathi-sarkar** [comment]
Hu @jluk Below is the version of azure cli
![image](https://user-images.githubusercontent.com/53785505/70444242-9808a300-1abf-11ea-9959-6e8d094e3d9f.png)

**Comment by partha-sarathi-sarkar** [comment]
@jluk Probably i found the issue my aks cluster are not vmss when i provisioned 
After provisioning VMSS i am able to  enable/update autoscaling cluster.

I provisioned AKS from Deploy custom template so there should be option for enabling that , I have checked several time over there but there are no option to Provision AKS with VMSS.

**Comment by jluk** [comment]
Thanks for confirming the issue was not using a VMSS cluster.

For ARM deployments you can set the compute type with the agentpooltype property: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2019-10-01/managedClusters.json#L1528

For Azure CLI the parameter is this:
```
    --vm-set-type 
```
