### ISSUE TITLE
Regular user with RBAC enabled cluster has system:masters role

### ISSUE THREAD

**Issue by tvdvoorde** [Azure/AKS#1343]
When I deploy an AKS cluser with RBAC enabled, but without AAD integration, and give a regular Azure AD user the 'Reader' role, and the "Azure Kubernetes Service Cluster User Role"  on the resource group that holds the AKS cluster, when I than login as that user with ```az login --use-device-code```, and do an ```az aks get-credentials -g <rg> -n <name>```, the certificate in the kubeconfig tells me that the user (name: clusterUser......) has 'system:masters' as the organization, and thus full control in the cluster (which it also has when I execute kubectl commands).
Is this by design? 
( I understand I can do more granual control with AAD integration, but would have expected with just RBAC enabled, and only the "Azure Kubernetes Service Cluster User Role" assignment, I would not have system:masters on the cluster.
Thanks,

**Comment by tadeugr** [comment]
Same issue here.

**What happened**:

When logged in Azure CLI with a Service Principal who only has the Azure Role "Azure Kubernetes Service Cluster **User** Role" associated with an AKS cluster (that is **not** integrated with AD and with RBAC enabled), it is possible to execute `az aks get-credentials` WITHOUT `--admin`. If using the `--admin` parameter, a permission error is raised as expected.

Although the `client-certificate-data` in the `kubeconfig` file has the `CN=masterclient` and `O=system:masters` which allows full admin privilege to Kubernetes without RBAC configured.

**What you expected to happen**:

Users who are able to run `az aks get-credentials` WITHOUT `--admin` parameters should **not** have certificates with `CN=masterclient` nor `O=system:masters` 

For those users, `"authorization.k8s.io/decision":"deny"` should be the default, requiring RBAC configuration.

**How to reproduce it (as minimally and precisely as possible)**:

Make sure you have an existing AKS cluster **not** integrated with AD, RBAC enabled  and with `kube-audit` logging enabled.

Create a SP.

```
az ad sp create-for-rbac \
  --skip-assignment \
  -n "sp-test"
```

Add a role assignment "Azure Kubernetes Service Cluster **User** Role" to the AKS cluster.

In  a completely separated terminal session, `az login` with this SP.

```
APPID="XXXX"
TENANTID="XXXX"
az login --service-principal --username $APPID --tenant $TENANTID
```

Input SP password when prompted.

`az get-credentials` WITHOUT `--admin`

```
az aks get-credentials \
  --subscription "MY-AKS-SUBSCRIPTION" \
  --resource-group MY-AKS-RG \
  --name MY-AKS-CLUSTER \
  --file ./sp-nonadmin.kubeconfig
```

Make sure `kubectl` is using the new `kubeconfig` file.

```
export KUBECONFIG=./sp-nonadmin.kubeconfig
```

Perform any actions that should be allowed only for admins, such as deleting namespaces, or running pods inside kube-system.

```
kubectl -n kube-system run --image=ubuntu:18.04 tmp-app --command -- tail -f /dev/null
```

Wait a few minutes to AKS log this action.

Go to AKS logs and query your action.

```
AzureDiagnostics
| where Category contains "kube-"
| where log_s contains "tmp-app"
| top 100 by TimeGenerated desc
```

You will see the following annotation.

```
{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}
```

For the following user.

```
{"username":"masterclient","groups":["system:masters","system:authenticated"]}
```

Also, if you `base64-decode` the `client-certificate-data` in the kubeconfig file, then use any CRT decoder, you will see the following certificate info.

```
Certificate Information:
Common Name: masterclient
Organization: system:masters
```

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
Client Version: v1.17.3
Server Version: v1.15.10

- Size of cluster (how many worker nodes are in the cluster?)

3

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

No workload at all, I used a brand new cluster to test it.

- Azure CLI version

azure-cli 2.1.0

**Comment by miwithro** [comment]
@norshtein for awareness.  We are working on a feature to remove certificates from the local accounts which will address this issue.   We hope to have it available by early Oct.
