### ISSUE TITLE
Support setting Azure tags per node pool to persist on upgrade/scale for new nodes

### ISSUE THREAD

**Issue by jluk** [Azure/AKS#1344]
This issue tracks the ability to define Azure resource tags in the agentPoolProfile. These tags will be set in the agent pool's model so new nodes brought into the agent pool during upgrade and scale will receive the tags at create time.

**Comment by jluk** [comment]
This capability has been released and is available to be set via ARM template. The CLI capability to set this is inbound and we will leave this issue open until that is complete.

**Comment by jluk** [comment]
This capability is now shipped and available on the latest CLI build, az v2.2.0.

https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.2.0

**Comment by truealex81** [comment]
Hello @jluk,

Could you please point me to the documentation about this feature? In release notes to AZ CLI v2.2 I see:

> Add --nodepool-tags to node pool when creating azure kubernetes cluster
> Add --tags when adding or updating a nodepool to cluster

Unfortunately, I can't find this options in documentation.
I've tried `az aks create ... --nodepool-tags test=test`, `az aks update ... --nodepool-tags test=test`, `az aks nodepool add ...  --nodepool-tags test=test` and similar commands, but its didn't work.

**Comment by jluk** [comment]
Here is the doc: https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#specify-a-taint-label-or-tag-for-a-node-pool
