### ISSUE TITLE
AKS - load-generator busybox - unable to stop/kill it

### ISSUE THREAD

**Issue by amitabh-github** [Azure/AKS#1348]
Kindly help. I am in trouble. There seems to be an issue with load test app.

Followed [this ](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#increase-load)article to load test HPA.

Have done CTRL+c to stop the load run, got a message 'image deleted'. But load never stopped, it keeps growing. It's been 3 hrs, it never stops. Something is running in the background. I am clue less, where and what is running in cluster.

```
NAME            REFERENCE                  TARGETS                          MINPODS   MAXPODS   REPLICAS   AGE
myservice   Deployment/myservice   445569536/500Mi, 16%/70%                   2         10        8          22m

```
Please help me to figure it out.

Thanks.

**Comment by jluk** [comment]
@amitabh-github please check any active pods/services you have deployed that load-testing is not inadvertently deployed elsewhere. if you find any delete those. otherwise it can take some time for scale-down to occur so give it some time to react to decreased load placed.

**Comment by jluk** [comment]
I am going to close this given it's a general k8s question with advice provided above. It seems you have some rogue synthetic traffic being placed on your cluster, please investigate with the advice shared and we can revisit if needed.
