### ISSUE TITLE
Using --attach-acr doesn't work with managed identity enabled

### ISSUE THREAD

**Issue by GeeWee** [Azure/AKS#1349]
**What happened**:
I'm trying to use the preview feature of managed identities, and I wish to deploy containers from an ACR registry. Minimal reproduction.
```bash
# Setup managed identity and add the ACR
az aks create --node-count 1 -g resoureGroup -n k8s-test --enable-managed-identity   
az aks update -n k8s-test -g resourceGroup --attach-acr myRegistryName    

# Now trying to pull images from the container fails, e.g. by kubectl applying a deployment
```

However, when not using managed identities, the following works.

```
az aks create --node-count 1 -g resoureGroup -n k8s-test --attach-acr myRegistryName
# Afterwards applying the same deployment pulls the image successfully.
```
Potentially related to [azure-cli-extensions/#1139](https://github.com/Azure/azure-cli-extensions/issues/1139)

**What you expected to happen**:
I expected to be able to pull images from my ACR, even with managed idenities enabled.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"524c3a1238422529d62f8e49506df658fa9c8b8c", GitTreeState:"clean", BuildDate:"2019-11-14T05:26:24Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster: 1

**Comment by sauryadas** [comment]
@feiskyer I think this was only implemented in the core cli >0.76 but not in the cli-extension. Do we need to manually port fixes in both core cli and cli extension or a new version of CLI extension always builds on the latest core cli version ?

**Comment by feiskyer** [comment]
@sauryadas I think it's not when `--enable-managed-identity` is true. we may need to implement it first in the extension and then port to Azure CLI. 

@norshtein could you work on this?

**Comment by sauryadas** [comment]
@norshtein please create a work item and work on this in this sprint if time permits. otherwise we can include it in the next sprint..

**Comment by tetlika** [comment]
having same issue: when creating AKS with --enable-managed-identity , this does not work: https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration; any info when it will be fixed?

**Comment by tetlika** [comment]
hey, I have tried this way:

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-authentication-managed-identity#3-grant-the-identity-permissions-to-access-other-azure-resources

so basically:

az role assignment create --assignee <servicePrincipalID> --scope <registryID> --role acrpull

and it did the job

**Comment by ThomasManson** [comment]
I am unable to get my AKS cluster to pull images from ACR - looks like the same issue. 
@tetlika I have created the role assignment, but that didn't solve my issue. Can you give me more details about how you solved it? Was this for an ACR task? I am trying run a helm upgrade command, and that fails with an auth issue with ACR

**Comment by tezzigator** [comment]
> 
> 
> hey, I have tried this way:
> 
> https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-authentication-managed-identity#3-grant-the-identity-permissions-to-access-other-azure-resources
> 
> so basically:
> 
> az role assignment create --assignee --scope --role acrpull
> 
> and it did the job

This is actually preferred for me, as I use Terraform to apply my infrastrucure as code, and currently terraform cannot create an AKS cluster with ACR integration on its own, but what you describe is 100% possible with terraform automation and so is preferred.  Can you please give detail on the assignee and the scope?  Was the assignee the MSI of the cluster, or was it the kubelets' identity?  and the scope, was it merely the scope of the ACR registry ResourceID? 

TIA

**Comment by arwkmd** [comment]
Argument --attach-acr doesn't work but you can workaround the problem. Keep in mind that Azure creates two managed identity for AKS cluster: system and user. Use user-assigned managed identity:

```powershell
$kubeletIdentityObjectId = az aks show `
    --resource-group $clusterResourceGroupName `
    --name $kubernetesClusterName `
    --query identityProfile.kubeletidentity.objectId `
    --out tsv
$azureContainerRegistryId = az acr show `
    --resource-group $containerResourceGroupName `
    --name $containerRegistryName `
    --query id `
    --out tsv
az role assignment create `
    --role acrpull `
    --assignee-object-id $kubeletIdentityObjectId `
    --scope $azureContainerRegistryId
```

The code does not work with preview extensions of Azure CLI for AKS.

**Comment by IvanJosipovic** [comment]
> > hey, I have tried this way:
> > https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-authentication-managed-identity#3-grant-the-identity-permissions-to-access-other-azure-resources
> > so basically:
> > az role assignment create --assignee --scope --role acrpull
> > and it did the job
> 
> This is actually preferred for me, as I use Terraform to apply my infrastrucure as code, and currently terraform cannot create an AKS cluster with ACR integration on its own, but what you describe is 100% possible with terraform automation and so is preferred. Can you please give detail on the assignee and the scope? Was the assignee the MSI of the cluster, or was it the kubelets' identity? and the scope, was it merely the scope of the ACR registry ResourceID?
> 
> EDIT: I can confirm this workaround:
> az role assignment create --assignee --scope --role acrpull
> where the scope is the resourceid of the ACR, and the assignee is the clientid of the kubelet's user assigned managed identity that was automatically created (referred to by in the portal by name of "-agentpool" . So do NOT use the MSI of the cluster. use that user managed identity "-agentpool" that was automatically created.
> 
> And it did take about 10 mins for it to correctly propagate for me.

Thanks for your post, the -agentpool was the missing key.

Here is the terraform that worked for me with a Managed Identity AKS cluster:
```
resource "azurerm_role_assignment" "ra" {
  scope                = azurerm_container_registry.acr.id
  role_definition_name = "acrpull"
  principal_id         = azurerm_kubernetes_cluster.aks.kubelet_identity[0].object_id

  depends_on = [
    azurerm_container_registry.acr,
    azurerm_kubernetes_cluster.aks
  ]
}
```

**Comment by TomGeske** [comment]
Fix has been provided as part of CLI experience. I'm going ahead closing this one. Please keep commenting if you have further questions.
