### ISSUE TITLE
[Feature] AKS node pool can be created with a proximity placement group (PPG)

### ISSUE THREAD

**Issue by gravityuser** [Azure/AKS#1351]
VMSS with AKS is recently GA. We'd like the ability to configure the VMSS when using this with AKS. This is currently not supported with AKS. Specifically we would like to use proximity placement groups with VMSS/AKS.

**Comment by salami738** [comment]
we would like it too in our project.

**Comment by sanjeebsarangi** [comment]
We are looking forward to it.

**Comment by gkaleta** [comment]
+1 on this. Specifically for FoundationDB

**Comment by jluk** [comment]
This capability is now in public preview please visit aka.ms/aks/ppg for more information!

**Comment by ohorvath** [comment]
It seems something is wrong with the ARM template validation. I'd like to create the PPG in the same ARM template as the AKS cluster but during the validation part it fails immediately. It should work the same way as it works with VNETs.

**Comment by ohorvath** [comment]
@jluk Could you please confirm how this should work from ARM templates?

**Comment by jluk** [comment]
Hey @ohorvath thanks for the ping, it should pass ARM template validation so let us take a look at this and get back to you

**Comment by jluk** [comment]
This is set to GA in public cloud in Q4 2020

**Comment by jluk** [comment]
Update: this feature is set to GA in public cloud by the end of October.
