### ISSUE TITLE
AKS VNet private IP conflict on different clusters

### ISSUE THREAD

**Issue by guibirow** [Azure/AKS#1353]
**What happened**:

I have two clusters with exact same layout deployed into their own resource groups,
each resource group contains a vnet, with 2 subnets. One subnet host an application gateway and the other subnet host AKS. Both have the exact same network definition with different naming (DEV and PROD).

When I deploy an NGINX ingress into the DEV cluster, setting a fixed private IP as `172.16.1.254` for the load balancer, everything works fine.

When I run the same step into the PROD cluster, the load balancer does not get the IP and fail with message below:

```
Code="PublicIPAddressCannotBeDeleted" 
Message="Public IP address /subscriptions/0000-000-00-000-000/resourceGroups/mc_company-rg-euw-prod_company-aks-euw-prod_westeurope/providers/Microsoft.Network/publicIPAddresses/kubernetes-a9841e56edbb611e9b06322fa6540717 
can not be deleted since it is still allocated to resource /subscriptions/0000-000-00-000-000/resourceGroups/mc_company-rg-euw-prod_company-aks-euw-prod_westeurope/providers/Microsoft.Network/loadBalancers/kubernetes/frontendIPConfigurations/a9841e56edbb611e9b06322fa6540717. 
In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublicip." 
Details=[]
```

If I set the private IP to something different from DEV, `i.e: 172.16.1.253`, it works fine without issues.

**What you expected to happen**:

Given the VNets are different, I would expect to not have IP conflicts, as the networks are not peered or have any relation to each other.

**How to reproduce it (as minimally and precisely as possible)**:
Create two resource groups containing
- 1 VNET(172.16.0.0/22) with 2 subnets(172.16.0.0/23 and 172.16.2.0/23)
- Deploy AKS to one subnet (currently 1.14.8, but same happened on previous versions)
- Deploy App Gateway to other subnet(probably not required) 
- Deploy Nginx-ingress(helm chart stable) as private load balancer and set a private load balancer IP to `172.16.1.254` 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): **1.14.8**
- Size of cluster (how many worker nodes are in the cluster?) **3**
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) **NGINX ingress and a few dot net services.**
- Others:

**Comment by guibirow** [comment]
Closing down the issue, I have deleted the cluster and recreated it and the problem went away.
I still think this is a very strange the issue, but unfortunately I couldn't wait for an investigation to make it work without deleting the cluster.

**Comment by ehashman** [comment]
I suspect this is actually an instance of https://github.com/kubernetes/kubernetes/issues/85565
