### ISSUE TITLE
jx install fails on AKS

### ISSUE THREAD

**Issue by Vaccano** [Azure/AKS#1354]
**What happened**:
1. Created a cluster following this [MS Doc](https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough) (Though I selected 5 nodes not 1)
2. Ran `jx install` from the Azure Cloud Shell (and selected "aks").  
3. It installed several things correctly
4. It tried to run: `helm init --service-account tiller --tiller-namespace kube-system` and failed with this error:

> helm init failed: after 3 attempts, last error: failed to run 'helm init --service-account tiller --tiller-namespace kube-system' command in directory '', output: 'Error: unknown flag: --service-account': exit status 1

NOTE: Running `helm version` shows that it installed helm v3, which does not use tiller.  It looks as if the `jx` (1.3.107) in Azure Cloud Shell does not support helm v3.

**What you expected to happen**:
For Jenkins X to install correctly. 

**How to reproduce it (as minimally and precisely as possible)**:
Follow the steps in "What went wrong".

**Anything else we need to know?**:
This appears to be an issue with jx command line trying to setup tiller even though Helm v3 does not need tiller.

I assume that Azure Cloud Shell needs an updated version of the `jx` command line tool, that support Help v3 (or that it should be pointed at Helm V2).

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.12
- Size of cluster (how many worker nodes are in the cluster?): 5
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Brand new cluster.  Just trying aout 
- Others:
jx: 1.3.107

**Comment by jluk** [comment]
@maertendMSFT could you upgrade the version of jx in cloud shell to latest?
