### ISSUE TITLE
Add Self-signed certificate to AKS to connect to private registry

### ISSUE THREAD

**Issue by prabhu130986** [Azure/AKS#1355]
I'm trying to setup a private docker registry with self-signed certificate. when i try to pull images AKS is giving an error as "Failed to pull image "********": rpc error: code = Unknown desc = Error response from daemon: Get https://*********/v2/: x509: certificate signed by unknown authority"

Is there a way to add the certificate to AKS to trust the private registry

**Comment by cartyc** [comment]
I’ve used this method in the past successfully 

https://github.com/coreos/tectonic-docs/blob/master/Documentation/admin/add-registry-cert.md
