### ISSUE TITLE
How to optimize cluster cost for infrequent batch compute?

### ISSUE THREAD

**Issue by iocuydi** [Azure/AKS#1356]
When using the command 

az aks nodepool delete --cluster-name $mycluster --name $mynode --resource-group $mygroup--no-wait

I get this error:  Operation failed with status: 'Bad Request'. Details: AgentPool APIs supported only for clusters with VMSS agentpools. For more information, please check https://aka.ms/multiagentpoollimitations.

This caused me to accidentally get billed and spend $100 because the nodepool was up for a few days. What's more annoying is I seemingly can't disable or delete a nodepool without deleting the whole cluster. Is there any way to delete nodepools without deleting the whole cluster? Or is there a correct way to use this command?

Thanks!

**Comment by jluk** [comment]
@iocuydi can you verify your cluster is based on VMAS or VMSS? This should be available with a GET on the cluster which will populate a vm-set-type. Copy/pasting the sanitized output from an `az aks show` would help a lot.

**Comment by iocuydi** [comment]
{
  "aadProfile": null,
  "addonProfiles": null,
  "agentPoolProfiles": [
    {
      "availabilityZones": null,
      "count": 2,
      "enableAutoScaling": null,
      "enableNodePublicIp": null,
      "maxCount": null,
      "maxPods": 110,
      "minCount": null,
      "name": "nodepool1",
      "nodeTaints": null,
      "orchestratorVersion": "1.13.12",
      "osDiskSizeGb": 100,
      "osType": "Linux",
      "provisioningState": "Succeeded",
      "scaleSetEvictionPolicy": null,
      "scaleSetPriority": null,
      "type": "VirtualMachineScaleSets",
      "vmSize": "Standard_DS2_v2"
    }
  ],
  "apiServerAccessProfile": null,
  "dnsPrefix": "x",
  "enablePodSecurityPolicy": null,
  "enableRbac": true,
  "fqdn": "x",
  "id": "x",
  "identity": null,
  "kubernetesVersion": "1.13.12",
  "linuxProfile": {
    "adminUsername": "x",
    "ssh": {
      "publicKeys": [
        {
          "keyData": "x"
        }
      ]
    }
  },
  "location": "x",
  "maxAgentPools": 8,
  "name": "x",
  "networkProfile": {
    "dnsServiceIp": "x",
    "dockerBridgeCidr": "x",
    "loadBalancerProfile": {
      "effectiveOutboundIps": [
        {
          "id": "x",
          "resourceGroup": "x"
        }
      ],
      "managedOutboundIps": {
        "count": 1
      },
      "outboundIpPrefixes": null,
      "outboundIps": null
    },
    "loadBalancerSku": "Standard",
    "networkPlugin": "kubenet",
    "networkPolicy": null,
    "podCidr": "x",
    "serviceCidr": "x"
  },
  "nodeResourceGroup": "x",
  "provisioningState": "Succeeded",
  "resourceGroup": "x",
  "servicePrincipalProfile": {
    "clientId": "x"
  },
  "type": "Microsoft.ContainerService/ManagedClusters",
  "windowsProfile": null
}

**Comment by jluk** [comment]
@iocuydi I can't tell what the issue may be, my only other guess was the nodepool being targeted for deletion may have been a different resource unintentionally. Do you have a support ticket we can reference?

**Comment by iocuydi** [comment]
@jluk I recreated the aks cluster with the same command as I had used previously, then used az aks show on that. I had to delete the entire original cluster right after posting the issue because it kept billing me. Is the fact that it is of type VMSS a problem? Should it be VMAS?

**Comment by jluk** [comment]
Only VMSS clusters support the `az aks nodepool` commands, so the error above is expected when trying to operate with the nodepool cmd on a VMAS based cluster.

**Comment by iocuydi** [comment]
@jluk I think I may have accidentally made a VMAS cluster last time. My new one is VMSS. The aks nodepool delete command now returns "Operation failed with status: 'Bad Request'. Details: Primary agentpool cannot be deleted." 

Is there any way to delete this primary nodepool? What I want is to be able to deploy code on kubernetes quickly, but not have to pay hundreds of dollars/month when it isn't running. As it stands now, I'll pay $100+/month even if I only actually use the resource for 30 seconds per month. 

What I would like is if I can create a nodepool for the cluster, run my code on it and serve response to user, then delete the node. As it stands now, the only way to do this would be to create the entire cluster when I need to run the code, then delete the entire cluster after. This takes several minutes.

For context, the reason I'm not using something like container instances is because they don't support some functionality which is crucial to my application (https://github.com/MicrosoftDocs/azure-docs/issues/43947)

**Comment by jluk** [comment]
Got it - that makes more sense.

That error is accurate, as a control plane requires at least one active agentpool. There are system pods that are required to run for your cluster to function. You may find input elsewhere that you can scale the underlying IaaS tied to the cluster down to zero, however this is not a supported scenario in AKS. Doing this sends your cluster out of support and I don't recommend it.

Read your linked issue and I understand your scenario much more now. AKS can serve your purpose, although depending on how often you need compute this may be more than necessary.

To optimize your costs and only scale out on user input - you can do a few things.
1. Scale down to 1 node for the cluster and activate cluster autoscaler. In this manner you'll only pay one VM cost (should be $50 or so a mo for standard SKUs), then create new nodes if more workloads come in that the one node can't support.
1. If your requirements are job-like and that it runs docker containers - does just creating one off VMs as needed with docker in the vhd suffice? Consistently recreating AKS clusters might be overkill if you serve a few hours of compute a month.

**Comment by iocuydi** [comment]
Thanks!! So for AKS at an absolute minimum I'd pay $50/mo to have a cluster just exist for a month and not be used?

I was trying to avoid just having a VM that I create/destroy every time, but may resort to this. Other than slightly long creation/deletion time, can you think of a downside of recreating AKS clusters each time? We these operations fail after a while/would I hit some kind of limit or anything?
 
Container instances seemed like the perfect fit for this if they supported docker.

**Comment by jluk** [comment]
I would agree the use case fits ACI very well. You can recreate AKS clusters as well as needed, if you're okay with that operation flow. You should have no issues in limits there.

What's the need for running docker? Do you need to do image building / use ACR build?

+ @dkkapur from ACI team for thoughts too

**Comment by iocuydi** [comment]
Yep, need docker to build images and push to acr. I'd heard the suggestion of build pipelines on that other thread, but there's a bunch of other stuff that has to happen as well that seemed trickier to do with build pipelines. For now I'm going with creating/destroying the AKS clusters each time. Takes a bit longer but isn't a huge issue. Thanks again for your help!

**Comment by djeeg** [comment]
I'm also looking for an optimal way to run a cluster assuming:
- always leaving the primary agentpool scaled to 1 (to keep AKS supportable)
- primary agentpool could be tainted
- another nodepool with Standard_D4s_v3 instances would run most workloads
- east us region
- guesstimated with pay-as-you-go rates
- per month cost
- excluding other costs (ip, dns, lb, etc)

| VM | VM/m | Disk | Disk/m | Total/m |
| --- | --- | --- | --- | --- |
| Standard_B2s | £23 | Premium 100GB (default) | £15 | £38 |
| Standard_B2s | £23 | Premium 30GB | £4 | £27 |
| Standard_DS1_v2 | £39 | Premium 100GB (default) | £15 | £54 |
| Standard_DS1_v2 | £39 | Premium 30GB | £4 | £43 |
| Standard_DS1_v2 | £39 | Ephemeral OS |  | £39 |
| Standard_DS1_v2 (Spot) | £8 | Ephemeral OS |  | **£8** |

Spot Priority https://github.com/Azure/AKS/issues/982 and Ephemeral OS Disks https://github.com/Azure/AKS/issues/1370 are not currently supported by AKS, though AKS-Engine does seem to support both

Hopefully the primary node pool will allow both of these configurations :crossed_fingers:
