### ISSUE TITLE
Can't create a private cluster with byon and kubenet

### ISSUE THREAD

**Issue by kaluzaaa** [Azure/AKS#1357]
**What happened**:
Cannot create a private cluster with byon and kubenet using az cli
```
az aks create --name k8s-hard-v9 \
--resource-group k8s-hard \
--vnet-subnet-id /subscriptions/6971d276-35b3-4f54-b0c4-1acb7b5ea458/resourceGroups/k8s-hard/providers/Microsoft.Network/virtualNetworks/k8s-hard/subnets/aks \
--load-balancer-sku standard \
--network-plugin kubenet \
--service-principal XXXXXX \
--client-secret XXXXXX \
--skip-subnet-role-assignment \
--enable-private-cluster
The behavior of this command has been altered by the following extension: aks-preview
Deployment failed. Correlation ID: caf2f31c-0664-4fa4-ae71-2c6564905934. Internal server error
The behavior of this command has been altered by the following extension: aks-preview
Deployment failed. Correlation ID: caf2f31c-0664-4fa4-ae71-2c6564905934. Internal server error
```
**Environment**:

az --version
azure-cli                         2.0.77

command-modules-nspkg              2.0.3
core                              2.0.77
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
aks-preview                       0.4.24

**Comment by jluk** [comment]
@sauryadas could you take a look at this?

**Comment by sauryadas** [comment]
@kaluzaaa which region are you trying?

cc @feiskyer

**Comment by kaluzaaa** [comment]
@sauryadas west europe

**Comment by levimm** [comment]
@kaluzaaa I just did a test create with byon in westeurope successfully. Could you try to create again? We had a transient network issue and your cluster is already deleted yesterday.

**Comment by sauryadas** [comment]
@kaluzaaa can you confirm if this is still an issue ?

**Comment by kaluzaaa** [comment]
@sauryadas I checked everything again and everything works fine now. Thanks!
