### ISSUE TITLE
Live cluster monitoring "Node memory utilization %" does not match Non-Live

### ISSUE THREAD

**Issue by Spaceman1861** [Azure/AKS#1358]
**What happened**:
I have recently enabled live monitoring and noticed a difference between the live and none live memory graphs that I cant really explain.
**What you expected to happen**:
I would expect the charts to match each other for the same time period

![image](https://user-images.githubusercontent.com/7098812/71062160-8f962380-21b5-11ea-9b54-13ce2c8ed1c2.png)

**How to reproduce it (as minimally and precisely as possible)**:
Open up the insights tab with both live and non live toggled for cluster

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.15.5
- Size of cluster (how many worker nodes are in the cluster?)
3 x F4
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
HTTP microservices
- Others:

**Comment by jluk** [comment]
@vishiy could you take a look at this?

**Comment by vishiy** [comment]
@jluk - The issue here is our charts is calculating % usage based on allocatable resources, where as live (from metricserver) is based on capacity. So the former will show lower usage where as live will show higher (as seen in the screens above). We are aware of this inconsistency & will be fixing this soon.

**Comment by jluk** [comment]
Thanks @vishiy could you share an ETA or respond on this issue when released? Will mark as known issue.

**Comment by vishiy** [comment]
> Thanks @vishiy could you share an ETA or respond on this issue when released? Will mark as known issue.

Not sure about ETA, yet.
