### ISSUE TITLE
Can't use label selectors with dynamically provisioned disks

### ISSUE THREAD

**Issue by noelbundick** [Azure/AKS#136]
I have existing managed disks that I want to use with my cluster. These are statically provisioned as PVs that I want to use with label selectors (https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector). 

This works great for existing volumes, but when a suitable volume isn't found, I expect the Azure cloud provider to create a dynamically provision a new PV with the specified labels. Instead, I get an error that says "Failed to provision volume with StorageClass "managed-premium": azureDisk - claim.Spec.Selector is not supported for dynamic provisioning on Azure disk"

The upstream bug for this is here: https://github.com/kubernetes/kubernetes/issues/58413

**Comment by andyzhangx** [comment]
I have replied in upstream bug

**Comment by Cherishty** [comment]
Still occurring this issue on kubenetes v1.9.9 with azure file pvc..

**Comment by andyzhangx** [comment]
pls check upstream issue for details: https://github.com/kubernetes/kubernetes/issues/58413
@Cherishty

**Comment by seanmck** [comment]
Closing this since the issue is tracked upstream.
