### ISSUE TITLE
Container creation intermittently takes a long time

### ISSUE THREAD

**Issue by ball-hayden** [Azure/AKS#1362]
**What happened**:

A pod was suck in the "ContainerCreating" state for ~7 minutes.

The events for the pod are as follows:

```
Events:
  Type     Reason                  Age                   From                               Message
  ----     ------                  ----                  ----                               -------
  Warning  FailedScheduling        9m6s (x5 over 9m16s)  default-scheduler                  pod has unbound immediate PersistentVolumeClaims (repeated 4 times)
  Normal   Scheduled               8m58s                 default-scheduler                  Successfully assigned preview/api-pr-424-preview-redis-master-0 to aks-nodepool1-12894496-1
  Normal   SuccessfulAttachVolume  8m15s                 attachdetach-controller            AttachVolume.Attach succeeded for volume "pvc-1efbb96b-2315-11ea-92e1-d2e74dc1f7bb"
  Warning  FailedCreatePodSandBox  34s                   kubelet, aks-nodepool1-12894496-1  Failed create pod sandbox: rpc error: code = Unknown desc = failed to create a sandbox for pod "api-pr-424-preview-redis-master-0": operation timeout: context deadline exceeded
  Warning  FailedSync              20s                   kubelet, aks-nodepool1-12894496-1  error determining status: rpc error: code = Unknown desc = Error: No such container: 29b85720911f857ef70e08b613eb9eccd7c71726b3e1896b86efb30e3d327e74
  Normal   SandboxChanged          17s                   kubelet, aks-nodepool1-12894496-1  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled                  9s                    kubelet, aks-nodepool1-12894496-1  Container image "docker.io/bitnami/redis:5.0.5-debian-9-r104" already present on machine
  Normal   Created                 7s                    kubelet, aks-nodepool1-12894496-1  Created container api-pr-424-preview-redis
  Normal   Started                 6s                    kubelet, aks-nodepool1-12894496-1  Started container api-pr-424-preview-redis
```

**What you expected to happen**:

The container to be scheduled quickly.

**How to reproduce it (as minimally and precisely as possible)**:

Unknown. Intermittent fault after creating a new pod

**Anything else we need to know?**:

The event `FailedCreatePodSandBox: ... operation timeout: context deadline exceeded` appears to be common across occurrences of this issue.

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?)

4

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

Various HTTP and supporting Database etc services.

- Others:

Cluster is using CNI with Azure Network Policies.

**Comment by jnoller** [comment]
See this comment for what is occurring, your worker node OS disks are throttled due to quota 

https://github.com/Azure/AKS/issues/1320#issuecomment-566166756

**Comment by ball-hayden** [comment]
Thank you @jnoller.

Just to clarify is this an indicator that we've done something strange with our cluster config, or is this a general issue in the platform?

**Comment by jnoller** [comment]
It is a common IaaS misconfiguration (mis matched IaaS) largely due to lack of awareness of monitoring for these issues and load testing workloads with non synthetic load.

**Comment by ball-hayden** [comment]
Apologies @jnoller - I'm not following.

Are you saying that our choice of AKS is poor for our workload (which I wouldn't have thought was particularly disk heavy nor abnormal, and is low load in general), or are you saying that something is misconfigured on your end?

Looking at our node graphs we are seeing disk saturation - are you able to recommend a way of diagnosing what is causing this, or am I best opening a support ticket?

**Comment by jnoller** [comment]
@ball-hayden No, the issue is that this is a common pitfall with kubernetes deployments, there are improvements AKS is going to make to make this more obvious, simple and clear. While those changes are ongoing you can follow the guide I posted here:

https://github.com/Azure/AKS/issues/1320#issuecomment-566166756

Specifically, IO paths can be saturated - in this case, the primary OS disk of your worker VMs is exceeding the allowed quotas and being throttled.

**Comment by ball-hayden** [comment]
Thank you - we'll give that a go.

**Comment by ball-hayden** [comment]
We resolved this issue by switching to GKE.
