### ISSUE TITLE
az aks scale not working as expected

### ISSUE THREAD

**Issue by vishnujanardhanan** [Azure/AKS#1366]
**What happened**: az aks scale is not working as expected
No of nodes in cluster - 3
Subnet size - /25

Upgrading the kubernetes version failed due to unavailability of ip address in my subnet. Only option was to scale down the nodes to 2 and upgrade and scale up.

Tried to scale down and ckuster didnt scale down. Then tried deleting the node from portal, but kubectl was still showing 3 nodes. Then tried to scale to normal (node count 3) - this time node count reduced to 2. Able to upgrade the cluster now.

**What you expected to happen**: az aks scale command scales down the nodes

**How to reproduce it (as minimally and precisely as possible)**:Steps with logs included in SR-119122723000290

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.14.8
- Size of cluster (how many worker nodes are in the cluster?):3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.):no apps deployed in cluster yet
- Others:

**Comment by jluk** [comment]
@vishnujanardhanan can you confirm if this support request was resolved?

Given this issue is coming up to 30d old, I am going to close it but if there are additional questions we can continue that on this issue.
