### ISSUE TITLE
Cluster autoscaler not working

### ISSUE THREAD

**Issue by piostelmach** [Azure/AKS#1368]
**What happened**:

After enabled cluster autoscaler, autoscaler not working. Logs from diagnostic:
W1230 11:58:50.752093       1 azure_cache.go:177] FindForInstance: Couldn't find NodeGroup of instance {"azure:///subscriptions/xxx/resourceGroups/mc_xxx/providers/Microsoft.Compute/virtualMachineScaleSets/aks-infra-15047659-vmss/virtualMachines/0"}

Rest of details in SR119123022000925

**Comment by palma21** [comment]
Confirmed an issue with virtual nodes and CA, fixed and rolling out
