### ISSUE TITLE
Switch to using aks-engine provided vhd for Windows nodes

### ISSUE THREAD

**Issue by MikkelHegn** [Azure/AKS#1379]
As part of improving the experience using Windows in AKS, we are switching from a standard Windows Server image in Azure, to a purpose built vhd image for Windows nodes.

Once this change is released, existing node pool cannot be upgraded, and you'll have to create new node pools and migrate your workloads to the new node pool.

**Comment by djsly** [comment]
Once we are on the new Windows VHD logic. Should we expect the same upgrade experience for windows node pool as for the Linux node pool ? 
@MikkelHegn 

Also, do you think that this migration will see the day within the next two AKS release ? :)

**Comment by MikkelHegn** [comment]
#1448 - Release: https://github.com/Azure/AKS/releases/tag/2020-02-10

@djsly yes and we will very soon provide the ability to upgrade OS base (vhd) without having to upgrade the K8 version of a node pool.
