### ISSUE TITLE
Can't upgrade K8S cluster because OperationalInsights is missing

### ISSUE THREAD

**Issue by xXKeyleXx** [Azure/AKS#1380]
**What happened**:
Failed to save Kubernetes service '\*\*\*\*\*'. Error: Unable to get log analytics workspace info. Resource ID: DefaultResourceGroup-WEU/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-\*\*\*\*\*-WEU. Details: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.OperationalInsights/workspaces/DefaultWorkspace-*****-WEU' under resource group 'DefaultResourceGroup-WEU' was not found.". For more details about how to create and use log analytics workspace,  please refer to: https://aka.ms/new-log-analytics

**What you expected to happen**:
The upgrade goes through without the error.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure why it is missing in the first place. Maybe it was deleted by someone 🤷‍♂ 

**Anything else we need to know?**:
Can't add Operational Insights as it is "Coming soon".
I tried to add the cluster to an Log Analytics workspace but that did not help either.

**Environment**:
- Kubernetes version: 1.14.8
- Size of cluster: 2 nodes
- General description of workloads in the cluster : HTTP microservices

**Comment by PickleVirus** [comment]
You need to disable monitoring addon for this cluster at first
az aks disable-addons -a monitoring --resource-group  b2bclouddevkubeclusters --name b2bclouddevrmqhandler

**Comment by xXKeyleXx** [comment]
That fixed it. Thank you!
