### ISSUE TITLE
azure-npm container not running

### ISSUE THREAD

**Issue by andriktr** [Azure/AKS#1381]
Deployed and AKS cluster (kubernetes version : "1.17.0") with network policy enabled (azure plugin used). 
Pods controlled by azure-npm daemonset are not fully up because only 1/2 containers are running. 
There are two containers azure-npm and azure-vnet-telemetry. According the kubectl describe pod something is wrong with azure-npm container image reference. 
 _Normal   Scheduled      27m                    default-scheduler                         Successfully assigned kube-system/azure-npm-284fv to aks-default-37081970-vmss000000
  Normal   Pulling        27m                    kubelet, aks-default-37081970-vmss000000  Pulling image "mcr.microsoft.com/containernetworking/azure-vnet-telemetry:v1.0.30"
  Normal   Pulled         26m                    kubelet, aks-default-37081970-vmss000000  Successfully pulled image "mcr.microsoft.com/containernetworking/azure-vnet-telemetry:v1.0.30"
  Normal   Created        26m                    kubelet, aks-default-37081970-vmss000000  Created container azure-vnet-telemetry
  Normal   Started        26m                    kubelet, aks-default-37081970-vmss000000  Started container azure-vnet-telemetry
  Warning  InspectFailed  24m (x10 over 27m)     kubelet, aks-default-37081970-vmss000000  Failed to apply default image tag "mcr.microsoft.com/containernetworking/": couldn't parse image reference "mcr.microsoft.com/containernetworking/": invalid reference format
  Warning  Failed         2m11s (x114 over 27m)  kubelet, aks-default-37081970-vmss000000  Error: InvalidImageName._ 

It looks that pod template in the  daemonset config is wrong and missing image name as it only contains a general path:
Name:           azure-npm
Selector:       k8s-app=azure-npm
Node-Selector:  beta.kubernetes.io/os=linux
Labels:         addonmanager.kubernetes.io/mode=Reconcile
                app=azure-npm
Annotations:    deprecated.daemonset.template.generation: 1
                kubectl.kubernetes.io/last-applied-configuration:
                  {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app":"azu...
Desired Number of Nodes Scheduled: 3
Current Number of Nodes Scheduled: 3
Number of Nodes Scheduled with Up-to-date Pods: 3
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 3 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           k8s-app=azure-npm
  Annotations:      scheduler.alpha.kubernetes.io/critical-pod:
  Service Account:  azure-npm
  **Containers:
   azure-npm:
    Image:      mcr.microsoft.com/containernetworking/**
    Port:       <none>
    Host Port:  <none>
    Environment:
      HOSTNAME:   (v1:spec.nodeName)
    Mounts:
      /run/xtables.lock from xtables-lock (rw)
      /tmp from tmp (rw)
      /var/log from log (rw)
      /var/run from socket-dir (rw)
   azure-vnet-telemetry:
    Image:        mcr.microsoft.com/containernetworking/azure-vnet-telemetry:v1.0.30
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:
      /tmp from tmp (rw)
      /var/run from socket-dir (rw)
  Volumes:
   log:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log
    HostPathType:  Directory
   xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  File
   tmp:
    Type:          HostPath (bare host directory volume)
    Path:          /tmp
    HostPathType:  Directory
   socket-dir:
    Type:               EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:          <unset>
  Priority Class Name:  system-node-critical
Events:
  Type    Reason            Age   From                  Message
  ----    ------            ----  ----                  -------
  Normal  SuccessfulCreate  51m   daemonset-controller  Created pod: azure-npm-rpjmc
  Normal  SuccessfulCreate  51m   daemonset-controller  Created pod: azure-npm-284fv
  Normal  SuccessfulCreate  51m   daemonset-controller  Created pod: azure-npm-8v9q5

**Comment by nmeisenzahl** [comment]
Same here.

**Comment by Bessonov** [comment]
further activity occurs

**Comment by palma21** [comment]
Do you still see this happening?

**Comment by nmeisenzahl** [comment]
Hi @palma21. I just tested it again with 1.17.7 and it looks good. I did not yet test the 1.18 preview.

**Comment by palma21** [comment]
Thanks @nmeisenzahl! Let us know if you find any issues.

**Comment by jluk** [comment]
Closing for now, but we can revisit if more issues occur on this specifically. cc @aanandr
