### ISSUE TITLE
[Feature] Support user definition of an outboundType for the network profile (skip public IP provision for SLB)

### ISSUE THREAD

**Issue by jluk** [Azure/AKS#1384]
**Current state**: Generally Available

**What happened**: Currently if using SLB with AKS, a public IP is provisioned and setup by AKS as Azure SLB requires a configured PIP for proper egress. Given today, clusters require outbound connectivity to pull cluster components such as system pod images, this is configured on creation by the resource provider.

**What you expected to happen**: To create a cluster without any public IP provisioned on the LB if I have setup my own outbound routes for egress out of my cluster. This may require hops to solutions like Azure Firewall. I should be able to define the outbound type of my cluster to use the load-balancer provisioned with a public IP as it does today, or pass a param to use a user defined route which is successfully created by me (the AKS consumer).

**Comment by jluk** [comment]
Public documentation: https://docs.microsoft.com/en-us/azure/aks/egress-outboundtype

**Comment by jkantharaj** [comment]
Justin, thank you for this feature...hope you will be releasing this as a GA soon...

**Comment by jluk** [comment]
This feature is now generally available.

The current AKS release for week of 2020-06-01 carries the GA changes, this includes support of bring-your-own route table for Kubenet (#400) to enable using an outbound type of UDR with a Kubenet cluster.

**Comment by jluk** [comment]
Closing this issue as complete. AzureCNI is fully supported and Kubenet will be fully supported once issue #400 is completed in release.
