### ISSUE TITLE
AKS: Azure network policies are not always additive 

### ISSUE THREAD

**Issue by aelmanaa** [Azure/AKS#1386]
**What happened**:

For each namespace, I wanted  to implement default rules which are the least permissive. Then whenever needed, we can create new networkpolicies which open up ingress or egress traffic for specific podselectors. While testing this approach, I’ve remarked that in one case, the networkpolicies are additive and in one case they are not. See below (yaml files are in attachment):

[git issue1.zip](https://github.com/Azure/AKS/files/4065085/git.issue1.zip)

_Case A:  they are additive:_

1.	1st create a test namespace: “kubectl create namespace test”
2.	Run pod with label app-name=utils : “kubectl run utils -it --generator=run-pod/v1 -n test --image arunvelsriram/utils bash -l app-name=utils”
3.	Test that egress traffic is allowed inside the pod: “wget www.google.com”  google is reached , OK (as expected)
4.	Apply deny-all policy “kubectl apply -f utils-deny-all.yaml” which denies all traffic for pods with label “app-name=utils” in namespace test. Test again “wget www.google.com”  google not reached. OK (as expected)
5.	Apply allow-egress policy “kubectl apply -f utils-allow-egress.yaml” which allows all egress traffic for pods with label “app-name=utils” in namespace test. Test again “wget www.google.com”  google reached. OK (as expected)

-->	As you notice, both networkpolicies are additive

_Case B:  they are not additive:_

1.	Delete previous networkpolicies: “kubectl delete netpol --all -n test”
2.	Test that egress traffic is allowed inside the pod: “wget www.google.com”  google is reached , OK (as expected)
3.	Apply deny-all policy “kubectl apply -f test-namespace-deny-all.yaml” which denies all traffic for every pod in “test “ namespace. Test again inside utils pod “wget www.google.com”  google not reached. OK (as expected)
4.	Apply allow-egress policy “kubectl apply -f utils-allow-egress.yaml” which allows all egress traffic for pods with label “app-name=utils” in namespace test. Test again inside utils pod “wget www.google.com”  google not reached. NOK . Actually I’m able to run “nslookup www.google.com” but not “wget www.google.com” ; it gets stuck in

`# wget www.google.com
--2019-12-26 10:58:05--  http://www.google.com/
Resolving www.google.com (www.google.com)... 172.217.168.196, 2a00:1450:400e:808::2004
Connecting to www.google.com (www.google.com)|172.217.168.196|:80...
Connecting to www.google.com (www.google.com)|172.217.168.196|:80... failed: Connection timed out.
Connecting to www.google.com (www.google.com)|2a00:1450:400e:808::2004|:80... failed: Cannot assign requested address.Retrying.
`
5.	Delete previous policy “kubectl delete netpol -n test deny-all-test-namespace-policy” . Test again inside utils pods “wget www.google.com”  google reached. OK (as expected)

--> A bit strange. All egress traffic is not blocked as I’m able to run nslookup but http requests are blocked. 

**What you expected to happen**:

I'd expected that networkpolicies are additive. Meaning that in test case B,  "utils" pod should have been able to reach www.google.com (step 4 of caseB)

**How to reproduce it (as minimally and precisely as possible)**:

see above
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Major:"1", Minor:"14", GitVersion:"v1.14.8" ;
- Size of cluster (how many worker nodes are in the cluster?) 3 Nodes ; Linux Standard_D2s_v3

**Comment by aelmanaa** [comment]
throubleshooting Scenario1, case B; I found out something interesting in the iptables:

Run “iptables save” & “ipset -L” on the node hosting my test (utils) pod

- In Ispset ,you'll find out that the pods utils (for instance, IP: 10.130.12.68) is refered in 2 different set. In my case: azure-npm-3863441321 & azure-npm-2377792723

-  you will find ou these sets in ip tables. in my case:


 -A AZURE-NPM -j AZURE-NPM-INGRESS-PORT
-A AZURE-NPM -j AZURE-NPM-EGRESS-PORT
-A AZURE-NPM -j AZURE-NPM-TARGET-SETS
-A AZURE-NPM-EGRESS-PORT -m set --match-set azure-npm-2377792723 src -m set --match-set azure-npm-530439631 dst -m comment --comment "ALLOW-ALL-FROM-app-name:utils-TO-all-namespaces" -j ACCEPT
-A AZURE-NPM-TARGET-SETS -m set --match-set azure-npm-3863441321 dst -m comment --comment DROP-ALL-TO-ns-test -j DROP
-A AZURE-NPM-TARGET-SETS -m set --match-set azure-npm-3863441321 src -m comment --comment DROP-ALL-FROM-ns-test -j DROP
-A AZURE-NPM-TARGET-SETS -m set --match-set azure-npm-2377792723 dst -m comment --comment "DROP-ALL-TO-app-name:utils" -j DROP


--> Chain “azure-npm-2377792723” allows the egress traffic then chain “azure-npm-3863441321” blocks the traffic.  Whi is the pod “10.130.12.68” not  removed from the set azure-npm-2377792723 ?

**Comment by jaer-tsun** [comment]
I believe this has been resolved [here](https://github.com/Azure/azure-container-networking/pull/466).

The bugged behaviour was that the egress all policy was treated as egress to all-namespaces. In that scenario, you're able to reach kubedns but not internet.

e.g. "ALLOW-ALL-FROM-app-name:utils-TO-all-namespaces" -j ACCEPT (reaches kubedns but not internet)
should be "ALLOW-ALL-FROM-app-name:utils" -j ACCEPT (reaches kubedns & internet)
