### ISSUE TITLE
Unable to assign an application security group to a nodepool VMSS

### ISSUE THREAD

**Issue by iverberk** [Azure/AKS#1388]
**What happened**: Trying to associate a nodepool vmss with a custom application security group (ASG) results in the following error:

```
All IPConfigurations on a Network Interface should reference the same set of Application Security Groups. IPConfiguration ipconfig2 references ASG(s) , wheras IPConfiguration /subscriptions/$SUB_ID/resourceGroups/$RG_ID/providers/Microsoft.Compute/virtualMachineScaleSets/aks-ng3-34239724-vmss/updateGroups/894ddb7a-15af-4726-816d-cd5592ce3df4/networkInterfaceConfigurations/aks-ng3-34239724-vmss/ipConfigurations/ipconfig1 references ASG(s) /subscriptions/$SUB_ID/resourceGroups/$RG_ID/providers/Microsoft.Network/applicationSecurityGroups/ng3.
```
**What you expected to happen**: The nodepool vmss would be associated with an ASG so that we can manage the network traffic to/from the vm's.

**How to reproduce it (as minimally and precisely as possible)**: Run the following command:
```
az vmss update -g $RESOURCE_GROUP -n $NODEPOOL_VMSS_NAME --add 'virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].applicationSecurityGroups' id='/subscriptions/$SUB_ID/resourceGroups/$RG_ID/providers/Microsoft.Network/applicationSecurityGroups/$ASG_NAME'
```

**Anything else we need to know?**: Not really, just surprised that doesn't work since vmss should be able to be associated with ASG's and we really need it to manage our network traffic to the vm's.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.8
- Size of cluster (how many worker nodes are in the cluster?) N/A
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) N/A
- Others:

**Comment by iverberk** [comment]
Anyone from Microsoft Azure/AKS available to provide further input on this issue?

**Comment by qwordy** [comment]
Any update?

**Comment by auerl** [comment]
Hi all, Is there any update on this issue?

**Comment by ceesios** [comment]
I just tried this, and the command doesn't fail anymore with az cli 2.18.0. The ASG doesn't work until an upgrade of the AKS nodepool, causing the redeployment of the nodes within the vmss. During the upgrade some nodes worked for a short period. However after the upgrade the asg has been removed from the vmss and it stops working again.

**Comment by sbkg0002** [comment]
Any progress on this?

**Comment by wangyira** [comment]
@miwithro looping you in to take a look

**Comment by miwithro** [comment]
@iverberk I just tested the command against my 1.19.11 cluster and it worked.  Can you at least upgrade your azure cli and try again.

{
  "azure-cli": "2.26.1",
  "azure-cli-core": "2.26.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.23"
  }
}
