### ISSUE TITLE
All environment variables end up in the logs by default regardless of being secrets or not

### ISSUE THREAD

**Issue by akazemis** [Azure/AKS#1389]
Currently in AKS the environment variables containing critical data (including kubernetes secrets) are being submitted to the system logs. (say to the AppInsights). the reason being a parameter named "AZMON_COLLECT_ENV" in the containers' environment variables are assumed True. This would cause some kubernetes secrets appearing in the logs.

So I'm suggesting these options to resolve this security threat:

- Making the "AZMON_COLLECT_ENV" environment variable "False" by default so that it doesn't submit any environment variable by default unless explicitly specified

- Ignoring the environment variables that are being read from Kubernetes secrets (if possible) so that no secret value leaks to the logs.

**What happened**:
Some critical secrets were seen in the logs!

**What you expected to happen**:
No secret revealed outside of the Kubernetes cluster

**How to reproduce it (as minimally and precisely as possible)**:
Assign a secret value to a container's environment variable, and enable logging for your AKS. the secret value ends up in the logs.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tcrossland** [comment]
See also `[log_collection_settings.env_var]` here: https://docs.microsoft.com/en-US/azure/azure-monitor/insights/container-insights-agent-config#data-collection-settings

**Comment by michelefa1988** [comment]
Any update on this? I also have the same problem, secrets in Azure console is quite an issue

**Comment by gopu-gds** [comment]
Any progress on this? All the Kubernetes secrets are shown in plain text in Azure console under Containers Environment Variables in Insights which undermines the meaning of Kubernetes secret. It's quite a security issue.

**Comment by bhicks329** [comment]
I'm not sure this is an AKS issue and using environment variables for storing secrets is bad practice IMHO. Look at using something like keyvault CSI drivers or flex vol to have the secrets mounted directly into the pods.

You can stop environment variables from appearing in the logs by setting AZMON_COLLECT_ENV to false. I do however agree with the original raised issue that this should be false by default.

**Comment by palma21** [comment]
@bhicks329 is correct. You should avoid using secretes in env vars. If you do than set that setting to false in the azure monitor configuration.

Adding the azure monitor team for feedback on the default.

**Comment by vishiy** [comment]
Please look here - https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-agent-config#data-collection-settings , you can control this at cluster level using configmap for quite sometime (like a year +) now.
