### ISSUE TITLE
Unable to connect to newly created AKS cluster

### ISSUE THREAD

**Issue by MatthewHartstonge** [Azure/AKS#139]
1. create cluster using CLI: `az aks create --resource-group aks-res-group-cluster --name mypoc --node-count 1 --generate-ssh-keys`
2. cluster is created
3. get credential: `az aks get-credentials --resource-group=aks-res-group-cluster --name=mypoc`
4. kubectl get nodes fails: `Unable to connect to the server: net/http: TLS handshake timeout`

Region: US East
K8S Version: 1.8.1

Dup of #137 as the problem appears to be ongoing..

**Comment by ramonduraes** [comment]
+1

**Comment by slack** [comment]
Follow along in #137

**Comment by MatthewHartstonge** [comment]
@slack the issue you refer to is closed, hence this open issue. The other option is to manually reopen #137

**Comment by slack** [comment]
Sorry about that. Are you still unable to create clusters?

The latest AKS builds are checking health of clusters before returning from the provisioning process. This build is rolling out this week, should reduce incidents of this error.

**Comment by MatthewHartstonge** [comment]
Running the following command under Cloud Shell generated the following errors
```
az aks create --resource-group aks-res-group-cluster --name mypoc --node-count 1 --generate-ssh-keys
```

East US:
```
Deployment failed. Correlation ID: c0b0d1e6-5d57-460f-84b5-321f506b5636. Azure Container Service is unable to provision an AKS cluster in eastus, due to an operational threshold. Please try again la
ter or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md.
```

Central US:
```
Operation failed with status: 'Bad Request'. Details: The VM size of Agent is not allowed in your subscription in location 'centralus'. Agent VM size 'Standard_DS1_v2' is available in locations: centraluseuap,eastus,eastus2euap,southcentralus,southeastasia,westeurope,westus2.
```
