### ISSUE TITLE
LoadBalancer External-IP stuck on <pending>

### ISSUE THREAD

**Issue by erotavlas** [Azure/AKS#1392]
I was following the .NET turorial on deploying docker container to Azure Kubernetes Service
https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy

However after I run 

`azkubectl apply -f deploy-myMicroservice.yaml`

The service never gets an external IP, it just hangs like this

```

PS D:\docker\.net\mymicroservice> azkubectl get service mymicroservice --watch
NAME             TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
mymicroservice   LoadBalancer   10.108.72.46   <pending>     80:31192/TCP   89m
```

I am using the VIsual Studio Professional Subscription

The only difference between the deployment is that Instead of getting the container from docker hub as instructed in the tutorial I pushed my image to Azure Container Registry and replaced the docker location with the location in Azure.  Other than that my deployment yaml is exactly the same

**Comment by wasker** [comment]
@erotavlas Speaking from experience with troubleshooting issues with ingress in AKS, `kubectl get events --all-namespaces` is very helpful when you're in this state.

**Comment by jason-epp** [comment]
I had similar issue.
Check the type of load balancer and the IP that was deployed.  The default LB type used to be 'basic', it is now type 'standard'.  The default IP type is still 'basic'.  These two have to match (basic & basic, or std & std ).  If you don't explicitly set the SKU for the LB, it will not match the IP type.

**Comment by Danlewis3** [comment]
im getting the same issue at the moment. No changes to system for a while just a new service

**Comment by eltonkevani** [comment]
I am getting the same issue, it is random yesterday was working fine and today, and the day before  yesterday  every-time we create a LB ip is pending . so something tells me something is wrong in azure platform since we have not change the way we create the lb

**Comment by hfgbarrigas** [comment]
Getting the same issue ...

**Comment by eltonkevani** [comment]
what I figure it out is that annotations can get the lb stack.
service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "20" for example was the problem. any value higher that 20 would put the lb in pending ip status forever.
After setting the value 20 it has not failed again

**Comment by hfgbarrigas** [comment]
For me it's pending supposedly because it cannot find the provided USER_IP in the resource group. Which, is untrue:

![image](https://user-images.githubusercontent.com/10131599/77196037-867d6100-6ada-11ea-9824-fd282cbbdba5.png)

![image](https://user-images.githubusercontent.com/10131599/77196116-a57bf300-6ada-11ea-8041-a5e94a1d3b82.png)

![image](https://user-images.githubusercontent.com/10131599/77196152-b3ca0f00-6ada-11ea-907d-f9c453d1d2fa.png)

**Comment by vutkin** [comment]
Hi all, 

Confirm. We have same problem

**Comment by Gerthum** [comment]
Hi Guys - Had the same issue but kubectl get events --all-namespaces confirmed we hit our quota for Public IPs in the subscription

**Comment by ohadschn** [comment]
@wasker great tip! In my case the Load Balancer and Public IP weren't provisioned in the same region: 
`Resource `/subscriptions/XXXX/resourceGroups/FOO/providers/Microsoft.Network/publicIPAddresses/BAR` referenced by resource `/subscriptions/XXXX/resourceGroups/foo-aks/providers/Microsoft.Network/loadBalancers/kubernetes` was not found. Please make sure that the referenced resource exists, and that both resources are in the same region`

**Comment by Pamir** [comment]
Hi,
k describe svc <svc_name> should give the actual results. 

- LoadBalancer SKUs does not match standard/basic issue

- Regions does not match

- service principal does not have rights to create LoadBalancer.
