### ISSUE TITLE
DNS label is reset on the existing public IP after deploying ingress

### ISSUE THREAD

**Issue by wasker** [Azure/AKS#1393]
**What happened**: 
After deploying stable/nginx-ingress with controller.service.loadBalancerIP set to a public IP that I've created with a specific DNS label, DNS label got removed from the IP address entity.

**What you expected to happen**: 
DNS label left intact. I'm using that label as a CNAME in my DNS zone.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new AKS cluster.
1. Create a new public IP address in the MC_xxx resource group. I tried to use existing public IP address that AKS creates, but then ingress setup fails, hence I'm creating a new public IP address.
1. Assign DNS label to the newly created IP address.
1. `helm upgrade nginx stable/nginx-ingress --install --atomic --set controller.service.loadBalancerIP="<newly-created-IP-address>" --set controller.replicaCount=1`

Observe that after helm install succeeds, the DNS label is removed from the IP address I provided.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T17:24:45Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
1 node

**Comment by mathieu-benoit** [comment]
Seems to be related to this https://github.com/Azure/AKS/issues/1376
