### ISSUE TITLE
kube-proxy cannot be scraped for metrics

### ISSUE THREAD

**Issue by robinkb** [Azure/AKS#1395]
**What happened**:

I configured Prometheus to scrape metrics from the kube-proxy pods in my cluster. Unfortunately, kube-proxy only accepts connections to its metrics endpoint from localhost, and Prometheus' requests are denied.

**What you expected to happen**:

Monitoring solutions like Prometheus should be able to scrape the kube-proxy pods for metrics.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy an AKS cluster and attempt to make a request to a kube-proxy pod on `:10249/metrics`.

**Anything else we need to know?**:

According to the [Kubernetes documentation](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/), this behaviour can be adjusted with the `--metrics-bind-address` flag.
The easiest fix would be to accept connections from all addresses, but maybe AKS can be a bit clever and limit requests to the cluster network.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.8

**Comment by arminc** [comment]
I hit the same issue. Besides this, it also uses a different label so the label selector needs to be changed as well. https://github.com/Azure/AKS/issues/1417

**Comment by simongottschlag** [comment]
Any updates regarding this?

**Comment by buildmystartupio** [comment]
Anyone?

**Comment by sbkg0002** [comment]
Any update on this one?

**Comment by monaka** [comment]
I guess it is exposed on AKS 1.16.7.

```
root@aks-ssh-567bd478cc-ph2pp:/# curl -q http://10.240.0.66:10255/metrics 2> /dev/null | head
# HELP apiserver_audit_event_total [ALPHA] Counter of audit events generated and sent to the audit backend.
# TYPE apiserver_audit_event_total counter
apiserver_audit_event_total 0
# HELP apiserver_audit_requests_rejected_total [ALPHA] Counter of apiserver requests rejected due to an error in audit logging backend.
# TYPE apiserver_audit_requests_rejected_total counter
apiserver_audit_requests_rejected_total 0
# HELP apiserver_client_certificate_expiration_seconds [ALPHA] Distribution of the remaining lifetime on the certificate used to authenticate a request.
# TYPE apiserver_client_certificate_expiration_seconds histogram
apiserver_client_certificate_expiration_seconds_bucket{le="0"} 0
apiserver_client_certificate_expiration_seconds_bucket{le="1800"} 0
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"e2d9f8479783020904aba3de7499a49be6c75ebd", GitTreeState:"clean", BuildDate:"2020-04-09T02:31:15Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by arminc** [comment]
@monaka How come you are using port 10255 as it exposes it on port 10249? It seems you are looking at the metrics of kubelet and not kube-proxy.

Regarding the issue here: the metrics are only locally available, it seems it listens to localhost only and can not be accesses from outside. Prometheus can't access it.

**Comment by robinkb** [comment]
Can confirm that the metrics can be scraped in AKS with Kubernetes 1.16.9.

**Comment by jdevalk2** [comment]
This issue is not resolved, on AKS 1.16.9
Nodeshell, netstat -a shows listening on 10249 on localhost, not the Node IP.

**Comment by nebed** [comment]
This issue is also not resolved on AKS 1.16.10
Nodeshell, netstat -a still shows listening on 10249 on localhost, not the Node IP.

**Comment by nebed** [comment]
@robinkb please how did you scrape the metrics? as I still can't

**Comment by MaxHogervorst** [comment]
@nebed did you manage to resolve this? Facing similar issue

**Comment by nebed** [comment]
not yet @MaxHogervorst

**Comment by m1o1** [comment]
yeah I can't scrape kube-proxy either in AKS
