### ISSUE TITLE
Using nodeSelector for AKS kube-system deployments (coredns/metrics/tunnelfront) 

### ISSUE THREAD

**Issue by arminc** [Azure/AKS#1398]
**What happened**:
AKS doesn't allow any changes to the deployments which are created by AKS in the kube-system namespace. Currently, that are coredns, coredns-autoscaler, metrics-server, and tunnelfront.
When creating platforms in an enterprise that are managed by a central team there is a need to control where these pods land. The preference is that these should not land on nodes the team/customer uses but on predefined nodes that are used by the platform team (where more platform managed services run).

It is not possible to do this as there is no option to set the nodeSelector. (Unless I have looked over it, please correct me if I am wrong on this)

**What you expected to happen**:
Option to use nodeSelector to force where the AKS managed deployments land.

**Environment**:
Any AKS cluster.

**Comment by chroth** [comment]
Maybe a solution to this could be to taint the nodes you don't want coredns etc to be scheduled on: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

**Comment by arminc** [comment]
@chroth Thanks for the tip, that might be a way to do this

**Comment by sbkg0002** [comment]
Any news on this issue? We have the same problem.

**Comment by palma21** [comment]
You cannot change kube-system component's manifests.

You can and we recommend you to use 
1) system pools. All system components have soft affinity for system pools. https://docs.microsoft.com/en-us/azure/aks/use-system-pools
2) Taints and tolerations. Namely the criticalAddonsOnly taint which is already tolerated by all non-daemon set system components. Daemon Sets tolerate all.

let is know if you have additional questions
