### ISSUE TITLE
Collecting custom JSON logs not available when using omsagent inside AKS cluster

### ISSUE THREAD

**Issue by pomberer** [Azure/AKS#1407]
When using OMSAgent inside AKS Cluster to collect logs from stdout/stderr it cannot be configured to be using JSON log format.

Especially when using a java based application multiline parsing needs to be implemented when collection a stacktrace for example.

**Comment by derkoe** [comment]
Would be great to see the traces for Java (and other languages) combined into one log entry. Currently reading the stack traces is quite cumbersome.
