### ISSUE TITLE
Allow --admin access via PIM and upon expiry the user can't use the access stored in the .kube config

### ISSUE THREAD

**Issue by kmoussa** [Azure/AKS#1408]
**What happened**: 
   1. user "dev" got assigned Azure Kubernetes Cluster User Role and is eligible to be Azure Kubernetes Cluster Admin if requested through PIM.
   2.  by default they don't have Admin access so if user "dev" tries to use az aks get-credentials --admin it will fail generating the following error message.
3.  user dev requests Azure Kubernetes Cluster Admin through PIM since they are eligible to use it and PIM allows them to use az aks get-credentials --admin for the specific time allowed by PIM and then it expires.
4. After the role assignment is expired, the user dev can still use admin credentials because it's still stored in kube config locally.

**What you expected to happen**:
 After the role assignment is expired, the user needs to request the role again through PIM.

**How to reproduce it (as minimally and precisely as possible)**:
Same steps above.

**Anything else we need to know?**:
No
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?) 3 nodes

**Comment by rudolphjacksonm** [comment]
@kmoussa thanks for raising this, I was about to raise exactly the same issue. We're investigating Azure PIM for locking down access to most of our resources, AKS being the most important out of all of them. I tested this on my end and am seeing the same behavior; it looks like the admin token that's pulled down with `az aks get-credentials ... --admin` persists until expiry. @jnoller is there a way to have this token's expiry match the duration of the role elevation in PIM? I know that's probably vastly more complicated to implement than I'm making it sound here, but in my mind that is the only way I can see the two linking up.

User dev requests admin AKS access via PIM for X hours.
User dev pulls down admin creds using `az aks get-credentials ... --admin`
Token in kubeconfig has set expiry matching X hours and expires at that time

**Comment by kmoussa** [comment]
Any updates on this ?

**Comment by palma21** [comment]
You could use the rotate certs to expire the admin credentials. But would this solve your PIM requirements instead:
https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac

After removing the role and waiting 5min the user no longer has access to cluster admin.

**Comment by vidarw** [comment]
This and related issues should still be a high priority from a security perspective. For larger organizations - it’s not viable to generate new login certs for the cluster every single time a user gets disabled or PIM has been invoked.

**Comment by vidarw** [comment]
Still relevant...
