### ISSUE TITLE
az aks browse now results in ERR_CERT_INVALID on 1.17 cluster

### ISSUE THREAD

**Issue by eox-dev** [Azure/AKS#1409]
```
az aks browse -g <resource_group> -n <aks_name>
```
This was working on a 1.14 I had. Made a 1.17 and now this doesn't seem to work. Just get this error:

![image](https://user-images.githubusercontent.com/59094233/73087092-cb906880-3e86-11ea-903f-e4067011a1a3.png)

Tried incognito, clear browse cache, [reseting the credentials](https://docs.microsoft.com/en-us/azure/aks/update-credentials), and also made sure to [ClusterRoleBinding](https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard#start-the-kubernetes-dashboard).

Not sure what else to do at this point. Perhaps just an issue with 1.17 and I should just revert back.

Just tested some of the other preview builds and having the same issue.

**Comment by ams0** [comment]
Confirmed, however, Firefox lets you go past the certificate. I was able to retrieve the `kubernetes-dashboard-token`, pass it and it did let me in.

**Comment by ztasre** [comment]
put `chorme://flags` into the url bar and enable the `Allow invalid certificates for resources loaded from localhost.` flag

**Comment by bjorn-ali-goransson** [comment]
Yea that's the workaround. But what's the solution?

Why serve over HTTPS if a valid cert isn't used?

**Comment by Afikoman** [comment]
Happening to me too.
We've upgraded the AKS cluster from 1.15.11 to 1.16.10 and the dashboard stopped working with an "Invalid certificate" error.
It can be overcome with chrome flag offered here or using firefox which allows to continue although we're getting an invalid certificate, but both are just workarounds and not really a solution.

Does anyone encountered that and was able to solve this problem? Is there a way to fix it without deploying our own dashboard (from a yaml file)?

**Comment by palma21** [comment]
Please check here: https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard
That's not AKS related. The dashboard after a particular version started using https, and so you need to bypass the certificate unless you're creating one for it.

We recommend you use the Azure Portal instead:
https://azure.microsoft.com/en-us/updates/kubernetes-resource-view-is-in-public-preview/
