### ISSUE TITLE
AKS validates against duplicate taint keys when setting node-taint on agentPoolProfile

### ISSUE THREAD

**Issue by ondrejhlavacek** [Azure/AKS#1412]
**What happened**: If I use multiple taints in a Node Pool ARM template and there is a duplicate key, e. g. 

```
"nodeTaints": [
    "app=app1:NoSchedule",
    "app=app2:NoSchedule"
]
```
the deployment fails with this error message

```
Deployment failed. Correlation ID: ***. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "NodesNotReady",
        "message": "Not all nodes reached Ready state. Expected: 0, Actual: 2"
      }
    ]
  }
}
```

**What you expected to happen**: A sensible error message would be handy.

**How to reproduce it (as minimally and precisely as possible)**: Just set two node taints with the same key.

**Comment by jluk** [comment]
Thanks for the report, agree AKS should capture this validation for duplicate taint keys. Backlogging.
