### ISSUE TITLE
Garbage collection policy for containers and their images

### ISSUE THREAD

**Issue by GarrettGeorge** [Azure/AKS#1415]
**What happened**: Trying to find information about how containers and container images are garbage collected in a managed AKS cluster. When looking here, https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection, I'm not sure which defaults are changed, if any. 

**What you expected to happen**: Get information about garbage collection settings in a managed AKS cluster

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.8
- Size of cluster (how many worker nodes are in the cluster?) 6
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) HTTP microservices

**Comment by kennethgp** [comment]
If you SSH into a node you can run **ps -elf | grep kubelet** to check the configuration flags. In 1.14.8 I see:

--image-gc-high-threshold=85 --image-gc-low-threshold=80
