### ISSUE TITLE
Connecting to database outside the container is failing

### ISSUE THREAD

**Issue by kuttivinoth** [Azure/AKS#1416]
In AKS cluster deployed JBOSS application(image:daggerok/jboss-eap-7.1) and trying to connect MSSQL database  outside of container and it is failing

Connecting to database outside the container is failing

Should be able to connect mssql database hosted in azure

Try object kind of type external name and endpoint

**Comment by jluk** [comment]
@kuttivinoth connection failures could be a lot of different reasons - can you please open a support request to have AKS SRE diagnose the issue? We won't be able to resolve this quickly through Q/A on github, so to favor getting your issue resolved as fast as possible open an SR.

I am going to close this issue in favor of that path as this looks like it is a specific issue on your cluster. If during the SR you discover it is an aks issue, comment here again with details and we can revisit.
