### ISSUE TITLE
How to remove cached images on a node

### ISSUE THREAD

**Issue by ianjirka** [Azure/AKS#1421]
**What happened**: RFC - Some of our older clusters have cached container images from some time ago - these images are flagged as having security vulnerabilities and need to be removed (this is our security policy).  

**What you expected to happen**:
I need some *supported* capability to remove the images.  Any solution is acceptable from deleting the image to reimaging a node, but it is not acceptable to destroy the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a container, undeploy the container and then remove the cached image.

**Anything else we need to know?**:
Researching this, all paths lead to unsupported -
- Configuring Kublet garbage collection is not supported AFAIKT : https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/
- Manipulating (deleting/reimaging) nodes is not supported : https://github.com/MicrosoftDocs/azure-docs/issues/16721
- Manipulating the image cache directly is not supported (can't find link ATM but seems sensible)

Looking for a supported way to achieve this without destroying the cluster.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.6
- Size of cluster (how many worker nodes are in the cluster?): 5
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) : REST services and cronjobs.
- Others:

**Comment by andyzhangx** [comment]
try
```
kubectl apply -f https://raw.githubusercontent.com/andyzhangx/demo/master/dev/docker-image-cleanup.yaml
```

**Comment by ianjirka** [comment]
Thanks @andyzhangx - I'm looking for a statement from the AKS team.  There are a number of approaches that seem to work but aren't supported.  Since these are production clusters, I want to know the supported path for these operations.

**Comment by jnoller** [comment]
@ianjirka @andyzhangx  is part of the AKS product engineering team, his guidance is correct, if customers need to have custom cache/image rules, we recommend using daemonsets to accomplish this, alternatively SSH'ing into the nodes to do this is possible.

**Comment by ianjirka** [comment]
My apologies - and thank you very much.  This is helpful and we'll proceed with this as a solution.  Thanks!

**Comment by SnoWolfT** [comment]
@andyzhangx Thank you for your solution! The docker image which it references to is Linux. May I know whether we have one solution with Windows image?

**Comment by tcz001** [comment]
Hi @andyzhangx thanks for your solution, we are now seeing some vulnerabilities in this image you refered in your repo, do you mind sharing your Dockerfile and scripts to build the image, so that we can address those vuls inside, thanks

**Comment by andyzhangx** [comment]
@tcz001 you could find docker image here: https://hub.docker.com/r/meltwater/docker-cleanup/

**Comment by andyzhangx** [comment]
this tool only works in dockerd, while aks node is using containerd now, not sure whether there is similar tool for containerd
