### ISSUE TITLE
AKS cluster can violate minimum value for node pool (30 pod) with scale down command.

### ISSUE THREAD

**Issue by tatazoe** [Azure/AKS#1422]
**What happened**:
- Creating AKS cluster with "--node-count 1 --max-pods 10" fails due to AKS specification.
    
    Ref : Configure maximum - new clusters
    https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#configure-maximum---new-clusters
    **
    A minimum value for maximum pods per node is enforced to guarantee space for system pods critical to cluster health. 
    The minimum value that can be set for maximum pods per node is 10 if and only if the configuration of each node pool has space for a minimum of 30 pods.
    …
    The minimum value in the table above is strictly enforced by the AKS service. 
    You can not set a maxPods value lower than the minimum shown as doing so can prevent the cluster from starting.

- However, I can scale down to "--node-count 1 --max-pods 10" after cluster is created.

**What you expected to happen**:
Scale down to "--node-count 1 --max-pods 10" should be blocked.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create AKS cluster with "--node-count 3 --max-pods 10"
az aks create -g trial-pod-scale -n podscale --node-count 2 --max-pods 10

2. Scale down to "--node-count 1"
az aks scale -g trial-pod-scale -n podscale --node-count 1

(command results)
az aks scale -g trial-pod-scale -n podscale --node-count 1
{
  "aadProfile": null,
  "addonProfiles": null,
  "agentPoolProfiles": [
    {
      "availabilityZones": null,
      "count": 1,
      "enableAutoScaling": null,
      "maxCount": null,
      "maxPods": 10,
      "minCount": null,
      "name": "nodepool1",
      "orchestratorVersion": "1.14.8",
      "osDiskSizeGb": 100,
      "osType": "Linux",
      "provisioningState": "Succeeded",
       ...
 
**Anything else we need to know?**:
**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.8
- Size of cluster (how many worker nodes are in the cluster?) : 3 -> 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jluk** [comment]
@tatazoe if you do not specify the network plugin in CLI, it defaults to Kubenet. 

However, if I retry this with a `--network-plugin azure` cluster, I was able to reproduce a scale down in CLI which should have been invalidated in CLI. Marking this issue as a bug to close on, let us know if you hit more issues!

Thanks for the feedback!

**Comment by palma21** [comment]
This should be fixed. Let us know if you still experience it
