### ISSUE TITLE
AlwaysPullImages admission controller broken.

### ISSUE THREAD

**Issue by asubmani** [Azure/AKS#1423]
**AlwaysPullImages admission controller is not working as**: It seems the default setting is configured as "IfNotPresent

**The below command should return AlwaysPullImages**:

`kubectl get pod <any pod name> -n <namespace> -o jsonpath="{.spec.containers[0].imagePullPolicy}" `

**How to reproduce it (as minimally and precisely as possible)**:
The `AlwaysPullImages` admission controller is listed as a supported controller in the AKS FAQ below:
[What Kubernetes admission controllers does AKS support](https://docs.microsoft.com/en-us/azure/aks/faq#what-kubernetes-admission-controllers-does-aks-support-can-admission-controllers-be-added-or-removed)

- NamespaceLifecycle
- LimitRanger
- ServiceAccount
- DefaultStorageClass
- DefaultTolerationSeconds
- MutatingAdmissionWebhook
- ValidatingAdmissionWebhook
- ResourceQuota
- DenyEscalatingExec
- AlwaysPullImages

**Anything else we need to know?**:
`AlwaysPullImages` is listed as a recommended Admission controller. Since we have no way of querying kube-apiserver, need to know if this admission controller is enabled. If it is, then this is a bug, if it is not, then it should be enabled. Ideally expose enabling admission controllers in az cli or terraform modules as a cluster update.
**Environment**: I am facing this issue with 1.14.6 and the latest versions. I have tested this with & without VMSSS, System Assigned Managed Identity (Preview), Pod Security Policies. The 
- Kubernetes version (use `kubectl version`):1.15.7
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. demo cluster, only NGINX and a java container hosted, etc.)
- Others: AADPODIDentity is enabled.

**Comment by sauryadas** [comment]
@jnoller would you know?

**Comment by sauryadas** [comment]
DenyEscalatingExec
AlwaysPullImages

The above 2 admission controllers are in fact not enabled. We have now removed them from the doc.

if you need to configure AlwaysPullImages, you should ideally create your own mutating webhook or wait for azure policy to support it.
