### ISSUE TITLE
Support custom UDR tables in AKS with kubenet 

### ISSUE THREAD

**Issue by ivanthelad** [Azure/AKS#1424]
**What happened**:
when deploying a kubenet AKS to a custom VNET it should be possible to tell AKS to use a custom UDR table. AKS current generates its own UDR table. 
**What you expected to happen**:
it should be possible to allow aks to make changes(kubenet routing entries) to an existing UDR  table.

**Comment by jluk** [comment]
Closing this to consolidate with issue #400, let's continue our discussions there.
