### ISSUE TITLE
Enable Prometheus metrics scraping during AKS cluster creation.

### ISSUE THREAD

**Issue by karok2m** [Azure/AKS#1426]
I would like to have the ability to enable cluster-wide scraping of Prometheus metrics when I create an AKS cluster.

I am using management SDKs (.Net Core, `Microsoft.Azure.Management.ContainerService`) to create an AKS cluster. And I can enable log collection via `AddonProfiles`:

```
"addonProfiles": {
  "omsagent": {
    "config": {
      "logAnalyticsWorkspaceResourceID": "/subscriptions/<WorkspaceSubscription>/resourceGroups/<DefaultWorkspaceRG>/providers/Microsoft.OperationalInsights/workspaces/<defaultWorkspaceName>"
    },
    "enabled": true
  }
}
```

This will work similarly for ARM template as well.

It would be useful for me if I can enable cluster-wide scraping of Prometheus metrics directly from this configuration of `omsagent`.

**Comment by saaror** [comment]
@karok2m Currently we don't support enabling cluster-wide Prometheus metrics as the Add-on approach. However you can enable that post cluster creation as documented here. https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-prometheus-integration

We take this as a feedback & consider this scenario as part of planning.

**Comment by karok2m** [comment]
Yes, that is what I am using currently. But I want to be able to do this at cluster creation time, since configuration for enabling the agent is already there.

**Comment by palma21** [comment]
@saaror do you have any updates if this is on the roadmap?

**Comment by saaror** [comment]
We have this in our roadmap but please consider that to enable scrapping of all the Prometheus metrics out of the box will going to have cost implications. That being said we are also working on the cheaper storage solution from LA side so that should offset the cost issue.
