### ISSUE TITLE
Update REST & ARM template reference for AKS API 2020-01-01

### ISSUE THREAD

**Issue by flamingboo** [Azure/AKS#1431]
<!--
I cannot see any documentation for AKS API 2020-01-01.
The latest I have is the 2019-08-01 version:
https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2019-08-01/managedclusters

Is there any link to get the 2020-01-01 version?

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by flamingboo** [comment]
I can only see the 2019-08-01 version as being the latest:
https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2019-08-01/managedclusters

**Comment by jluk** [comment]
@flamingboo we're on track to publish an update to the API reference docs for 2020-02-01 within 2 weeks. This should bring up the ARM template and REST references.

FYI @mlearned @zr-msft

**Comment by jluk** [comment]
This has been updated for 2020-01-01

https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2020-01-01/managedclusters
