### ISSUE TITLE
Azure Portal - broken link to git Changelog

### ISSUE THREAD

**Issue by Kinjara** [Azure/AKS#1434]
Greetings,

On the portal - [Kubernetes Service/Upgrade] has a link named 'view the kubernetes changelog' this refers to  https://go.microsoft.com/fwlink/?linkid=872876

The reference is on:
https://github.com/kubernetes/blob/master/CHANGELOG.md

where it should point to:
https://github.com/kubernetes/blob/master/CHANGELOG/Readme.md

with kind regards,
Sebastian

**Comment by seanmck** [comment]
Thanks for reporting. We will get this fixed.

**Comment by jenetlan** [comment]
Should be fixed now! Thank you for the very clear info in your report, and apologies for the issue!
