### ISSUE TITLE
0/4 nodes are available: 4 Insufficient pods

### ISSUE THREAD

**Issue by Superset1986** [Azure/AKS#1437]
**What happened**:

i upgraded my AKS cluster to  v1.13.11 and now i'm getting "0/4 nodes are available: 4 Insufficient pods" 

**What you expected to happen**:
 I have 4 nodes with "default" deployment so my max pods allocation is 30 pr. node which should give me 120 total. When i count all my running pods i have 96.  

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I noticed that 1 of my nodes only have 8 pods allocated while the others have 30,30,28 
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.11", GitCommit:"25074a190ef2a07d8b0ed38734f2cb373edfb868", GitTreeState:"clean", BuildDate:"2019-09-18T14:34:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (how many worker nodes are in the cluster?)
4 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jluk** [comment]
@superset1986 could you open a support request to resolve this? I don't think we'll be able to troubleshoot this quickly via github, but we're happy to send dedicated AKS SRE to troubleshoot faster. Apologies for the issues upon upgrade.

I'm going to close this in favor of SR, but if you have general questions feel free to open another issue.
