### ISSUE TITLE
Is it possible to have mutiple IPs with a ILB with AKS?

### ISSUE THREAD

**Issue by thovipe** [Azure/AKS#1438]
**What happened**:
We have tried to deploy an internal load balancer with multiple IPs.

**What you expected to happen**:
We need to deploy some web apps with https bind, but diferent with diferent IPs. But the services does not bind, after one load balancer created.

**How to reproduce it (as minimally and precisely as possible)**:
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "subnet"
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: --ip1--
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: ingress
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "subnet"
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: --ip2--
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: ingress

**Anything else we need to know?**:
The IP is provisioned on the Azure ILB, but it does not reach the app.
**Environment**:
AKS
Azure Load Balance SKU - Standard.

- Kubernetes version (use `kubectl version`):
1.15.7

- Size of cluster (how many worker nodes are in the cluster?)
Two node pools, one linux (default) and one Windows
With autoscaler.
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Multipe webapps dotnet fullframework and dotnet core.
- Others:

**Comment by seanmck** [comment]
When you say "does not reach the app", do you mean it doesn't even reach the nginx controller or it doesn't reach the ultimate endpoint? Did you confirm it works before you add the 2nd IP?

**Comment by thovipe** [comment]
One thing I did was to only add the IPs and with that every IP on the ILB reaches the services.
This solves partially the issue, now we would like to isolate the daemonset per "environment". Do you a suggestion?
