### ISSUE TITLE
AKS and nodepools creation became slower since February 2nd

### ISSUE THREAD

**Issue by estambakio-sc** [Azure/AKS#1439]
**What happened**:

After February 2nd I experience longer creation time for AKS and attached nodepools while its CI process was not changed. 

I'm using CircleCI as CI server, and Terraform as executor. No configuration files for both were changed, as well as corresponding binaries or docker images. I'm creating and deleting AKS cluster nearly every workday and have noticed that time to create AKS and its nodepools increased after February ~2nd.

Feb 2nd and before it for a couple of months:
(I provide **last log line of Terraform output** before resource is considered created):
```
# creating AKS with default nodepool
azurerm_kubernetes_cluster.k8s: Still creating... [9m10s elapsed] # <- this time is provided by Terraform and includes only time when Azure created this resource
...
# creating additional nodepool
azurerm_kubernetes_cluster_node_pool.dev: Still creating... [4m0s elapsed]
...
# creating yet another nodepool after some time
azurerm_kubernetes_cluster_node_pool.database: Still creating... [4m10s elapsed]
```

Then numbers increase (and are nearly the same on every run after Feb 2nd, and yesterday and today):
```
azurerm_kubernetes_cluster.k8s: Still creating... [13m20s elapsed]
azurerm_kubernetes_cluster_node_pool.dev: Still creating... [9m10s elapsed]
azurerm_kubernetes_cluster_node_pool.database: Still creating... [9m11s elapsed]
```

**What you expected to happen**:

I expect it shouldn't become slower with no changes on my side.

**How to reproduce it (as minimally and precisely as possible)**:

My setup is very similar to https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster_node_pool.html#example-usage

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?): for daily development I create nodepools with a **single node each** (all in all 3 pools, 1 node each). Nodepools are created with enabled autoscaling (`enable_auto_scaling = true`)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others: Terraform azurerm@1.37.0

**Comment by djsly** [comment]
Could be related to : https://github.com/kubernetes/kubernetes/pull/88094

**Comment by jluk** [comment]
@estambakio-sc are you still reproducing this latent behavior?

**Comment by estambakio-sc** [comment]
@jluk today when I created a test cluster I see these numbers back to 8m/4m/4m values, which probably means this issue is not relevant any more.

**Comment by jluk** [comment]
Thanks for the report and confirm it has resolved
