### ISSUE TITLE
AKS availability in EAST US2 region.

### ISSUE THREAD

**Issue by ogidogi** [Azure/AKS#144]
We are excited by Azure Container Service (AKS) and possibilities it opens. Currently we develop and test AKS solutions in EAST US region while most of our resources run in EAST US2 region.
Please advise us on AKS availability date in EAST US2 region.

**Comment by seanmck** [comment]
We plan to make AKS available in EastUS2 in the next couple of months.

**Comment by rnt** [comment]
Months? :(

**Comment by tomconte** [comment]
eastus2 is online now:

```
az aks get-versions -l eastus2 -o table
KubernetesVersion    Upgrades
-------------------  -------------------------------------------------------------------------
1.10.3               None available
1.9.6                1.10.3
1.9.2                1.9.6, 1.10.3
...
```
