### ISSUE TITLE
GA of K8s 1.16 on AKS

### ISSUE THREAD

**Issue by jluk** [Azure/AKS#1440]
**What happened**:
K8s 1.16 is in preview on AKS. This issue captures the motion of moving 1.16 to a GA state within AKS, implying the deprecation of 1.13 to keep in line with N-2 support policy. The new supported window range will become 1.14, 1.15, and 1.16.

**Comment by djsly** [comment]
@jluk any ETA ?

**Comment by jluk** [comment]
In progress, expected in March.

**Comment by djsly** [comment]
early march, End of march :) hehe, March has over 30  days!

**Comment by jluk** [comment]
The week of March 9th.

https://github.com/Azure/AKS/releases/tag/2020-03-02

**Comment by JuneZhao** [comment]
@jluk Thank you for the notification, do you know when West US 2 will have 1.16 in GA, currently still in preview?
The behavior of this command has been altered by the following extension: aks-preview
KubernetesVersion    Upgrades
-------------------  ----------------------------------------
1.17.0(preview)      None available
1.16.4(preview)      1.17.0(preview)
1.16.1(preview)      1.16.4(preview), 1.17.0(preview)
1.15.7               1.16.1(preview), 1.16.4(preview)
1.15.5               1.15.7, 1.16.1(preview), 1.16.4(preview)
1.14.8               1.15.5, 1.15.7
1.14.7               1.14.8, 1.15.5, 1.15.7
1.13.12              1.14.7, 1.14.8
1.13.11              1.13.12, 1.14.7, 1.14.8

**Comment by jluk** [comment]
Hey June this change is entering the final 2 sectors and should be complete by Thursday.

Thanks for the patience!

**Comment by JuneZhao** [comment]
@jluk  sure will wait for that.

**Comment by jluk** [comment]
This should now be globally available, closing as a result.
