### ISSUE TITLE
[Addon] AppGateway Ingress Controller Managed Addon

### ISSUE THREAD

**Issue by jluk** [Azure/AKS#1441]
**Status**: Public Preview

**Docs**: aka.ms/aks/agic

**What happened**:
Application Gateway offers an ingress controller enabling integration for the service into Kubernetes. This is available as an open-source project that can be user installed today. 
https://github.com/Azure/application-gateway-kubernetes-ingress

This issue covers the capability to have that offering as a managed add-on, installable and usable from the AKS API.

**Comment by poddm** [comment]
Does this include aad-pod-identities?

- https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-new.md#install-aad-pod-identity

**Comment by jluk** [comment]
Yes, this addon should support pod identity if setup on your own. cc @mscatyao 

AKS will be working on offering AAD Pod Identity as a first class managed addon as well, captured in this issue. https://github.com/Azure/AKS/issues/1480

**Comment by JohnGalt1717** [comment]
Please make sure that this is all part of the portal UI as well. As an example the integration with Azure Container Registries exists, but you have to use AZ CLI instead of just clicking on a drop down and adding it.

**Comment by ezYakaEagle442** [comment]
Is it possible to open a port other than 80/443 for listening?
See #159

**Comment by sbkg0002** [comment]
Any word on this?

**Comment by mscatyao** [comment]
Should be going preview soon. Will keep this thread updated when it does go preview.

**Comment by mscatyao** [comment]
AGIC add-on work has been on pause for org mandated focus on fundamentals. Tentative ETA for GA of AGIC add-on is Q4CY20.

**Comment by rafnijs** [comment]
are there any plans to make this AGIC shareable across multiple AKS clusters?

**Comment by ezYakaEagle442** [comment]
@mscatyao are there any plans to make this AGIC shareable across multiple AKS clusters?
Also could you please share the GA ETA ?

**Comment by jinstest1** [comment]
any ETA on the GA of AGIC Addon ? 
Thank you :)
