### ISSUE TITLE
K8s 1.17 GA (& removal of 1.14) - ETA: July 2020

### ISSUE THREAD

**Issue by jluk** [Azure/AKS#1442]
**ETA for GA**: July 2020

**Notice for deprecation of 1.14 issued**: [Release Note 2020-06-01](https://github.com/Azure/AKS/releases/tag/2020-06-01)

**What happened**:
K8s 1.17 is in preview on AKS as of [2020-01-27 release notes](https://github.com/Azure/AKS/releases/tag/2020-01-27). This issue captures the motion of moving 1.17 to a GA state within AKS, implying the deprecation of 1.14 to keep in line with N-2 support policy. The new supported window range will become 1.15, 1.16, and 1.17 when this issue is closed.

**Comment by hallgeirl** [comment]
Is there an estimate available for when 1.17 does reach GA?

Thanks! :-)

**Comment by zhiweiv** [comment]
We are waiting on this too.

**Comment by jluk** [comment]
@hallgeirl we plan to make a 30-day notice announcement in early June to make July the ETA to GA 1.17 and remove 1.14. We will update this ticket once the mentioned 30 day notice has been made.

**Comment by zhiweiv** [comment]
@jluk I have a question, currently aks stays at 1.17.3, will be a newer version available(1.17.5 or higher) before July. We can only upgrade before July due to our release schedule.

**Comment by jluk** [comment]
We will continue updating the patch versions of preview versions, so yes we will have a more up to date 1.17 version before GA.

**Comment by welsh** [comment]
@jluk has there been any major issues with adopting 1.17 or has it been relatively stable while in preview?

**Comment by jluk** [comment]
K8s 1.18 is now in preview and will finish global deployment this week.

We have seen no major issues with 1.17 and plan to bring it to GA in July. 

If able, I would recommend flighting the version on dev/test clusters ahead of time and if on < 1.16 to begin that process asap to handle the announced K8s API deprecations on 1.16.

**Comment by vivekananth** [comment]
Hi,

We are in 1.14.6. Post July release our AKS stop working ?

**Comment by jluk** [comment]
@vivekananth the cluster will continue to function in operations like scale, but if you require Azure support you will need to upgrade the cluster into a supported version. Please reference the below document and FAQ for details:

https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions#faq

Hope this helps.

**Comment by vivekananth** [comment]
Thanks that helps !!!

**Comment by vivekananth** [comment]
Is it possible to subscribe to aks version upgrade alerts through azure portal so we can get to mail box ?

**Comment by jluk** [comment]
This change is now rolling out across all AKS regions and planned to complete in 1 week. You can validate if your region has received the change by running `az aks get-versions -l <region>`.

@vivekananth not yet through the Azure portal, however we are working to expose an emitted event through EventGrid when a new version is available.
