### ISSUE TITLE
Support of OCI container images (built with buildah and podman)

### ISSUE THREAD

**Issue by mathieu-benoit** [Azure/AKS#1446]
**What happened**: 

I'm building an OCI (Open Container Initiative) container image with [buildah](https://buildah.io) and [podman](https://podman.io) and then try do deploy that image on my AKS cluster: `kubectl run date --image mabenoit/date:buildah-1.13.2`.
With `kubectl get pod` then, you will see that your pod has the status `ImagePullBackoff`.
By doing a `kubectl describe` of this pod, you will find in the `Events` section this error:
```
Failed to pull image "mabenoit/date": rpc error: code = Unknown desc = Error response from daemon: mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not ''
```

**What you expected to happen**:

OCI container images running on AKS.

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl run date --image mabenoit/date:buildah-1.13.2`

**Anything else we need to know?**:

After a quick search there is this Moby's issue related to this: https://github.com/moby/moby/issues/39727, and the associated fix is integrated in Azure Moby 3.0.9. This is integrated in AKS-Engine via Moby 3.0.10 with this recent PR (not released yet): https://github.com/Azure/aks-engine/pull/2613. So looks like we need to wait for an AKS-Engine release integrating this and then its integration in AKS to make this working.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.7
- Size of cluster (how many worker nodes are in the cluster?): 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) - 
- Others: Moby 3.0.8, Kernel 4.15.0-1066-azure, Ubuntu 16.04.6 LTS, AKS-Engine v0.45.0-1-aks

**Comment by dariuszbz** [comment]
If it's Oracle something image then it is required nod Oracle something to
host your oci pod.

**Comment by mathieu-benoit** [comment]
Hi @dariuszbz, I just made more clear what the OCI acronym stands for, i.e. Open Container Initiative, not related to Oracle. Thanks for making me clarifying this.

**Comment by seanmck** [comment]
Looks like you're hitting this:

https://github.com/moby/moby/issues/39727

I don't think this fix has rolled into a Moby version that AKS is consuming yet. 

cc @cpuguy83

**Comment by cpuguy83** [comment]
MS Moby 3.0.10 has this fix.

**Comment by mathieu-benoit** [comment]
FYI: I was able to successfuly deployed my OCI container image with AKS-Engine https://github.com/Azure/aks-engine/releases/tag/v0.47.0 which contains MS Moby 3.0.10. Looking forward to see its integration in AKS now. Thanks.

**Comment by mathieu-benoit** [comment]
I just tested and confirmed that with the new AKS release https://github.com/Azure/AKS/releases/tag/2020-03-09 (which has AKS-Engine v0.47.0) this issue is now fixed. Thanks!
