### ISSUE TITLE
ProvisionState stuck in "Updating"  since failure of ARM deployment

### ISSUE THREAD

**Issue by aelmanaa** [Azure/AKS#1447]
Hello,

got a weird issue in west-europe : our devops pipeline started deployment of many ARM tempates (including an AKS template). 
There were no changes in AKS ARM template so I was just expecting to run quickly. However, it broke in the middle with a weird error:

"properties": {
        "statusCode": "InternalServerError",
        "serviceRequestId": "xxxx",
        "statusMessage": "{\"code\":\"EntityStoreOperationError\",\"message\":\"An error has occurred in subscription xxx request: 400 Bad Request.\"}"
    },

since then,  the status of the cluster is stuck in "Updating" . 

any clue what's EntityStoreOperationError?

**Comment by jluk** [comment]
Apologies for the late reply. Please open a support request if this issue is still occurring, our on-call can take a look and help you troubleshoot more quickly and with a better experience than we can on GitHub.
