### ISSUE TITLE
Deployment Failed Correlation ID: da...... Internal server error

### ISSUE THREAD

**Issue by tonybyorick** [Azure/AKS#145]
I'm using azure-cli version 2.0.25 and following steps in the beginners guide [Deploy an Azure Container Service (AKS) cluster](https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough)  and am getting an **internal server error**.  The following two initial steps taken from the guide work okay:

- Enable AKS preview for your Azure subscription
- Create a resource group

Response from `az group create --name dlt01 --location eastus` is:

> bash-4.3# az group create --name dlt01 --location eastus
{
  "id": "/subscriptions/270f562b-d598-4fd1-8af1-9264242c0cd7/resourceGroups/dlt01",
  "location": "eastus",
  "managedBy": null,
  "name": "dlt01",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null
}

However, the next step, "Create AKS cluster" fails with an internal server error.  Below is the create command and the error message:

> bash-4.3# az aks create --resource-group dlt01 --name dlt01Cluster --node-count 1 --generate-ssh-keys
SSH key files '/root/.ssh/id_rsa' and '/root/.ssh/id_rsa.pub' have been generated under ~/.ssh to allow SSH access to the VM. If using machines without permanent storage like Azure Cloud Shell without an attached file share, back up your keys to a safe location
**Deployment failed. Correlation ID: da0262a2-c9be-4334-8f36-0c610c3fc1ef. Internal server error**

Any thoughts as to the best way to resolve this?

**Comment by derekperkins** [comment]
I'm getting that now when trying to create a new cluster :(

**Comment by whereismyjetpack** [comment]
I was having issues in eastus a couple of days ago. Provisioning in centralus worked fine _shrug_

**Comment by whereismyjetpack** [comment]
See also #137 #139 #141

**Comment by derekperkins** [comment]
This is a different issue than those three that is happening on the create command. I've successfully created a number of test clusters before today.

**Comment by derekperkins** [comment]
@whereismyjetpack Good call on using centralus, my cluster started right up.

Logging into the portal looking at the failures, it happend on `Write ManagedClusters`

**Comment by tonybyorick** [comment]
Thanks for that tip!! Using *centralus* instead of *eastus* worked....  The cluster command worked and also the download of credentials and configuration of Kubernetes CLI worked... and now can get a list of my cluster nodes.......  Nice....

> bash-4.3# kubectl get nodes
NAME                       STATUS    ROLES     AGE       VERSION
aks-nodepool1-18875760-0   Ready     agent     10m       v1.7.7

**Comment by sylus** [comment]
Seeing this as well exact same issue, will try central as a workaround.

**Comment by WennderSantos** [comment]
Still happening in eastus.

**Comment by sgibson91** [comment]
I'm now having a similar issue using Central US having switched from West Europe 

https://github.com/alan-turing-institute/the-turing-way/issues/226

**Comment by jnoller** [comment]
@sgibson91 please file a tech support question in the azure portal so we can get on call to take a look. Please link this comment in the ticket so they know we should examine the failure in the region specifically. I’m closing and locking this issue due to being open for over a year, and in many cases the regional issues have been resolved
