### ISSUE TITLE
Ambiguous AKS Node Count and VM size configs which leads to cluster failure 

### ISSUE THREAD

**Issue by majorimi** [Azure/AKS#1450]
When creating a new AKS Service on Azure Portal it creates many other resources. One of them is "Virtual machine scale set". This leads to some serious problems:

- Scaling node count: both AKS and "VM scale set" support Manual and Autoscale. However I can set those settings to different values. It can cause problems when both set to Manual but e.g. "VM scale set" min. instance is 2 and you try to set Node count to 1 in AKS scaling, it will try to scale down for hours without finishing it. Since 2 rules are exclude each other.
- VM size change: if I understood it correctly AKS does not support VM/Node size change. But "VM scale set" has Size tab. Where you can change the included VM size in the scaleset. However "VM scale set" is "linked" to the AKS cluster... Problems with it:
     -  "VM scale set" list different VM sized then AKS Node pools
     - VM size can be changed it shows to change in  "VM scale set" but in AKS blade under Node Pools still shows the old VM/Node size.

**AKS Node Count:**
![image](https://user-images.githubusercontent.com/7632824/74567685-9dc6ad00-4f76-11ea-93e2-76864fda52db.png)

 **"VM scale set" Scale tab:**
![image](https://user-images.githubusercontent.com/7632824/74568005-5987dc80-4f77-11ea-996c-b2985a9d2857.png)

 **"VM scale set" Size tab** to change Node size, which also shows different VM sizes, then AKS:
![image](https://user-images.githubusercontent.com/7632824/74568255-db780580-4f77-11ea-945b-fd607b30938c.png)

More importantly by changing these setting back and fort. So scaling horizontally and vertically multiple times (sorry cannot tell the exact order I was playing with AKS for a few hours) destroys the whole cluster. It means Nodes are unavailable Pods and services are dead, it cannot heal itself even after scaling back to the original VM size, count, etc...
Nothing worked to fix the Node pool, tried to add a new one, Post, services was not deployed (all was 0/1 required instances). Only solution was to delete the whole AKS instance and recreate it.

I think it is big problem. Settings can be ambiguously set which leads to a full AKS service failure.

**Comment by palma21** [comment]
AKS does not support the use the IaaS APIs for the resources under an AKS cluster. Only the AKS APIs

https://docs.microsoft.com/en-us/azure/aks/support-policies#user-customization-of-worker-nodes
https://docs.microsoft.com/en-us/azure/aks/faq#can-i-use-the-virtual-machine-scale-set-apis-to-scale-manually

Hope this helps clarify
