### ISSUE TITLE
Add az aks get-credentials --context argument to aks-preview extension

### ISSUE THREAD

**Issue by michaelsync** [Azure/AKS#1453]
**What happened**:

``--context`` argument òf ``az aks get-credentials`` is not recognized after enabling aks-preview extension. 

**What you expected to happen**:

``--context`` argument òf ``az aks get-credentials`` should be recognized.

**How to reproduce it (as minimally and precisely as possible)**:

* az extension add --name aks-preview
* az aks get-credentials --resource-group ##your-rs-group## --name ##your-cluster-name --context ##your-cluster-alias##
**az: error: unrecognized arguments: --context ##your-cluster-alias**
*  az aks get-credentials --help

> 
> The behavior of this command has been altered by the following extension: aks-preview
> The extension is in preview
> 
> Command
>     az aks get-credentials : Get access credentials for a managed Kubernetes cluster.
> 
> Arguments
>     --name -n           [Required] : Name of the managed cluster.
>     --resource-group -g [Required] : Name of resource group. You can configure the default group
>                                      using `az configure --defaults group=<name>`.
>     --admin -a                     : Get cluster administrator credentials.  Default: cluster user
>                                      credentials.
>     --file -f                      : Kubernetes configuration file to update. Use "-" to print YAML
>                                      to stdout instead.  Default:
>                                      C:\Users\username\.kube\config.
>     --overwrite-existing           : Overwrite any existing cluster entry with the same name.
>     --user -u                      : Get credentials for the user. Only valid when --admin is False.
>                                      Default: cluster user credentials.  Default: clusterUser.

**Anything else we need to know?**:

If you remove the aks-preview extension, ``-context`` will work as expected. I need the preview feature for the private aks. I also need the ``-context`` because we have a few clusters with the same name in a different resource group or different subscription. 

**Environment**:
- Azure CLI 

azure-cli                         2.0.81

command-modules-nspkg              2.0.3
core                              2.0.81
nspkg                              3.0.4
telemetry                          1.0.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\{##user-name##}\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?) - 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) dotnet core 
- Others:

**Comment by jluk** [comment]
Thanks @michaelsync for reporting, I've reproduced this missing command in the preview-cli extension. We'll follow up internally to get this gap closed.

**Comment by sauryadas** [comment]
@feiskyer if anyone on the team is making changes to the cli extension, please assign this ...

**Comment by zqingqing1** [comment]
change is applied, close this ticket.

**Comment by jluk** [comment]
Change is available in preview v0.4.33

https://github.com/Azure/azure-cli-extensions/blob/master/src/aks-preview/HISTORY.md
