### ISSUE TITLE
Route 0.0.0.0 breaks the cluster..?

### ISSUE THREAD

**Issue by Kinjara** [Azure/AKS#1456]
**What happened**:
When extending the route-table with a rule of 0.0.0.0/0 the AKS Cluster started to fail.
**[Kubectl]** 
The common i/o-timeout.

**[NODE LOG validation]** 
When i SSH into the nodes and perform the trace-route (both name and ip) the response is:
1 ask-nodepool1-199.... 0.412 ms 0.360 ms 0.337 ms

**[Pod logs]**
If i remove the rule, and read the logs it states the following:
Starting Telegraph
[agent] Failed to connect to output socket_writer, retrying in 15s, error was 'dail tcp 0.0.0.0:25226: getsockopt: connection refused'.
Telegraph unknown (git: fork 50cd124)
[Inputs.prometheus]: Error in plugin: error making http request to https://.../metrics: Get https://...:10250/metrics: net/http: request canceled (Client.TImeout exceeded while awaiting headers
[Inputs.prometheus]: Error in plugin: error making http request to https://.../metrics: Get https://...:10250/metrics: net/http: request canceled (Client.TImeout exceeded while awaiting headers

**What you expected to happen**:
No effect from the 0.0.0.0/0 rule.
**How to reproduce it (as minimally and precisely as possible)**:
Create an vnet
create an Subnet
create an AKS-Cluster - (az aks create --resource-group $ResourceGroup --name $AKSClusterName --node-count 3 --zones 3 --max-pods 50 --network-plugin kubenet  --service-cidr 10.0.0.0/16  --dns-service-ip 10.0.0.10  --pod-cidr 10.244.0.0/16  --docker-bridge-address 172.17.0.1/16 --vnet-subnet-id $SubnetID --service-principal $AKSClientID  --client-secret $AKSClientSecret --kubernetes-version $AKS_Version --workspace-resource-id $OMSWorkspaceId --enable-addons monitoring  --admin-username $AdminUsername --ssh-key-value $sshKeyValue )

Enjoy the monitoring run ... the data flowing in...
Enable the route on 0.0.0.0/0 ... and see the monitoring turn dark. 

**Anything else we need to know?**:
when comparing the good (no 0.0.0.0-rule) and bad (with 0.0.0.0 rule) - netstat dont show new connections when filtering by the flags tupn, atpn and intu.). The recommended ports (except ubuntu-update servers) are opened up and the default DNS is used.

also the **var/log/messages** logs the intermediate message on:
 _prober.go:116] liveness probe for "Tunnelfront: tunnel-front" failed (failure):_ 
_controller.go:170] failed to update node lease, error: put https://....hcp.westeurope.azmk8s.io:443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/aks-nodepool1?timeout=40s; net/http: request canceled (Client.Timeout exceeded while awaiting headers)._
_controller.go:107] Failed to make webhook authenticator request: Post _https:\\...hcp.westeurope.azmk8s.oi:443/apis/authenticator.k8s.io/v1beta/tokenreviews: read tcp 10....:51360->10.4..:443: use of closed network connection_

**All urls are reachable from the nodes when curling and respond with server certification verification failed - assume good state.**

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.4.
- Size of cluster (how many worker nodes are in the cluster?): 3 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Blanco cluster.
- Others:
I need to route outgoing traffic to the firewall for inspection and logging - otherwise the security officer will have my head... please help.

**Comment by r0bnet** [comment]
We had a similar issue with a FW route in the route table with 0.0.0.0/0. The problem was that after adding that new route i wasn't able to fetch logs anymore with `kubectl logs`.

What solved our problem (at least in this case) was to allow access from the subnet to the master nodes on Port 22, 443 and 9000.
The IP address of the master can simply be obtained by resolving the DNS name for the master that you find in the overview page of your cluster.
In my opinion this solution doesn't really scale because i'm not sure if the IP will change later on.

Also i think there's not much documentation on how to configure AKS with (Azure) FW. I found this https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic#required-ports-and-addresses-for-aks-clusters but i'm not sure if you can add all those rules in this specific way to the Azure FW. I think you need to compromise here.

**Comment by Kinjara** [comment]
hi R0bnet,

Thanks for the reach out - we use an Palo Alto-addon that helps us translate the URLs from the technet you linked to a specific IP. The netwerk team was able to verify that traffic is flowing. Guess have i have to double check with the netwerk team that they check for blocked traffic - not to check for flowing traffic (1 out of 3 ports doesnt make success).

**Comment by bhicks329** [comment]
One thing to be aware of is that if you’re using any sort of SSL inspection
/ interception it will likely break connectivity.

From: Kinjara <notifications@github.com> <notifications@github.com>
Reply: Azure/AKS
<reply@reply.github.com>
<reply@reply.github.com>
Date: 24 February 2020 at 09:42:49
To: Azure/AKS <aks@noreply.github.com> <aks@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  Re: [Azure/AKS] Route 0.0.0.0 breaks the cluster..? (#1456)

hi R0bnet,

**Comment by Kinjara** [comment]
Hi bhicks329,

Thank you, fortunately we already removed that as one of the first steps ...
Same goes for the proxy configuration.

I just hope they networkteam will be able to confirm they did missed that they're blocking traffic from the tun- or hcp-url; that would at least make sense.

**Comment by Kinjara** [comment]
hi everyone,

It was indeed the firewall that intercepted the SSH over port 9000.
so the issue was between the chair and the keyboard :)

Regards,
Sebastian
