### ISSUE TITLE
Autoscale Not Working when adding additional CSE to VMSS

### ISSUE THREAD

**Issue by ncole** [Azure/AKS#1457]
**What happened**:
Using a Custom Extension is preventing autoscaling from working

**What you expected to happen**:
Even using a (script) Custom Extension, VMSS should be scaling nodes.

**How to reproduce it (as minimally and precisely as possible)**:
* Deploy an AKS cluster, where one VMSS autoscales 1-5.
* Apply a K8s deployment with replicas=1
* Scale deployment
VMSS reports an error:
`
Failed to restart virtual machine scale set 'aks-workers-XXXXXXX-vmss'. Error: VM has reported a failure when processing extension 'vmssCSE'. Error message: Enable failed: failed to get configuration: invalid configuration: 'commandToExecute' and 'script' were both specified, but only one is validate at a time" More information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot
`
The custom script in the UI *only* contains a `script` element.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.13.11
- Size of cluster (how many worker nodes are in the cluster?)
3 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Microservices

**Comment by jluk** [comment]
@ncole to clarify, you installed your own custom script extension directly to the VMSS and the scaling from AKS autoscaler failed?

If so, direct manipulation on the VMSS infrastructure isn't supported due to conflicts that can occur from AKS bootstrapping of the infrastructure. The error above points to something like that, but would like to confirm that is the action which was taken.

**Comment by jluk** [comment]
I haven't seen any further details on this question, so closing for now. Feel free to open a support request for a technical issue hit or comment here again and we can revisit. Thanks!
