### ISSUE TITLE
Existing route table is not populated on custom subnet

### ISSUE THREAD

**Issue by r0bnet** [Azure/AKS#1460]
UPDATE 2020-02-22: Please close if this is the same issue as here https://github.com/Azure/AKS/issues/400
---

**What happened**:

Deploying an AKS cluster with the default node pool into custom vnet w/ subnet and attached route table doesn't work as expected. We have a pre-populated route table for the node pool subnet with a route for our Azure FW. This is already attached to the subnet.
After deployment there is an additional route table with the internal AKS routes. Unfortunately that new RT is NOT used anywhere. Still the pre-existing RT is attached to the subnet but not touched / populated by AKS. Not sure if that's the intended behavior. To me this looks like a bug.

There is also a feature request for that: [Allow integrating with pre-existing route table](https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/39405889-allow-integrating-with-pre-existing-route-table)

**What you expected to happen**:

Instead of creating a new route table that is changed but never used AKS should consider the existing RT and change it accordingly. To avoid any route collisions Azure / AKS should validate the route configuration before the deployment happens.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a vnet with a subnet (e.g. 10.0.0.0/16 w/ 10.0.1.0/24)
2. Create a route table and attach it to the subnet (i added at least one custom route)
3. Deploy AKS and put the node pool VMs into that subnet
4. Check if there is a new RT in the nodes RG and check if it is used
5. Existing RT should still be attached to the subnet but not updated

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster
2
- API Version
`2019-10-01`

**Comment by Aedalus** [comment]
Wanted to confirm this was an issue for our team as well. Hoping a fix is developed soon.

**Comment by estambakio-sc** [comment]
We experience this issue too for a while now; as a workaround we ended up patching `route table` and `network security group` in a separate step right after creating a cluster.

**Comment by r0bnet** [comment]
Hey @estambakio-sc yes that's is also our current workaround. But tbh it's still nothing more than that. Would like to get an update on this from official side.

**Comment by jluk** [comment]
Confirming this is a known issue with Kubenet, will close this as a result being a dupe. Please bring the conversation into issue #400 so we can consolidate the asks, that work is in-flight and we can keep updates there.
