### ISSUE TITLE
Feature Request: Disable Windows Defender on Windows nodes

### ISSUE THREAD

**Issue by zhiweiv** [Azure/AKS#1462]
Windows Defender consumes a lot of CPU on Windows nodes. Windows nodes run in isolated vnet without public access, workloads on them are all in containers, I think it is safe to disable Windows Defender to reduce resource consumption. On the other hand, there is no AntiVirus preinstalled on Linux nodes also.

Is this reasonable?

![cpu](https://user-images.githubusercontent.com/22001089/75126434-de4fc480-56f4-11ea-9556-9883635501b9.PNG)

**Comment by 0x53A** [comment]
I also noticed that Windows Defender was running at 40% CPU on a ``Standard_D4s_v3`` node, so it was hogging almost 2 vCPUs.

**Comment by zhiweiv** [comment]
We have cluster autoscaler enabled, it is not feasible to disable it manually. It will be great to have an option to disable it at nodepool level.

**Comment by andyzhangx** [comment]
I would say I also hit this issue on Windows long long time ago...

**Comment by MikkelHegn** [comment]
Investigating... will update once we have more insights.

**Comment by hallgeirl** [comment]
We have the same experiences as @zhiweiv - the antivirus takes a LOT of resources, especially when deploying new pods.

For us, disabling antivirus isn't a good solution - our application temporarily stores files on the local file system (I think it's ASP.NET that does that) before storing permanently to Azure Blob storage. And we have customers with a high demand for security - and that includes scanning for malware before files are stored in permanent storage. 

However, having some control of WHICH folders to scan would be great. Then we can exclude anything else than the upload folders. Would it be possible to have e.g. some annotations on the pods that controls which folders should be included in the malware scan?

**Comment by Oldervoll** [comment]
Experiencing the same issues. Currenly excluding docker folders from windows defender scan to ease the situation a bit. That means that we for example don't scan images we pull to the node, which is not great. Docker documentation on the matter: https://docs.docker.com/engine/security/antivirus/

@zhiweiv We are adding the powershell DSC extension to our windows vm scaleset to make sure that our exclusions are added to new nodes as well. Currently monitoring the performace changes, but it seems to help quite a bit. 

Configuration we are currenly testing:
```
Configuration NodeConfig {

    Import-DscResource -ModuleName PsDesiredStateConfiguration

    Node 'localhost' {
        Script AntivirusExclusion
        {
            GetScript = 
            {
		return @{ 'Result' = "OK" }
            }

            SetScript = 
            {
		Add-MpPreference -ExclusionPath "C:\ProgramData\docker"
		Add-MpPreference -ExclusionPath "C:\Program Files\Docker"
            }

            TestScript = 
            {
		return $false
            }
        }
    }
}
```

**Comment by MikkelHegn** [comment]
We are doing extensive tracing to find the culprit of the excessive CPU usage, and plan to implement the appropriate optimizations in the VHD for AKS. Docker is already excluded and verified by Defender. I'll keep updating with our analysis and once we'll update.

**Comment by frankvdbh** [comment]
@Oldervoll  Can you describe how you added this configuration to the VMSS ? I'm trying the same as we have a workload where exclusions in defender make it 40% faster..

**Comment by Oldervoll** [comment]
@MikkelHegn Do you mean that docker is already excluded as default now? Or are you adding docker to the exclusions in a later version? I can't see any excluded paths on our nodes as default, so are you doing this another way?

**Comment by Oldervoll** [comment]
@frankvdbh We add the DSC extension from our create new cluster automation.

Step 1: Compress an archive, containing the configuration file: [WindowsNodeConfig-0d31f1bc-4701-4272-a853-ee3180d15489.zip](https://github.com/Azure/AKS/files/4358616/WindowsNodeConfig-0d31f1bc-4701-4272-a853-ee3180d15489.zip)

Step 2: Upload the compressed archive somewhere, so that it can be downloaded.

Step 3: Add the extension with settings.
```
az vmss extension set --vmss-name <VmssName> --name DSC --resource-group <ResourceGroupName> --publisher Microsoft.Powershell --settings <DscConfig> --version 2.80
```
DscConfig can be replaced with a json-string, like the nodes under "settings" as explained under Extension Schema here: https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/dsc-windows

Had some issues creating a json-string that the cmdlet accepted, but this is currently working for us:
```
$dscConfig = '{\"configuration\":{\"function\":\"NodeConfig\",\"script\":\"WindowsNodeConfig.ps1\",\"url\":\"<URL to compressed archive>\"},\"wmfVersion\":\"latest\"}'
```

Step 4: Update all instances in the vm scaleset to apply the latest changes:
```
az vmss update-instances --instance-ids * --name <VmssName> --resource-group <ResourceGroupName>
```

**Comment by MikkelHegn** [comment]
@Oldervoll it's whitelisted per default based on a few different scenarios.

**Comment by MikkelHegn** [comment]
Hi all, we have a PR in aks-engine to add exclusions on the binaries we see impact Defender the most https://github.com/Azure/aks-engine/pull/2967

**Comment by MikkelHegn** [comment]
Add this will come to the AKS vhd as soon as we publish an update.

**Comment by MikkelHegn** [comment]
https://github.com/Azure/AKS/releases/tag/2020-04-27
