### ISSUE TITLE
2020-02-11 Windows Update - nodepool support needed

### ISSUE THREAD

**Issue by brobichaud** [Azure/AKS#1465]
**What happened**:
The 2020-02-11 Windows Update has security updates that can cause compatibility issues between container images and host. If the host is not at least at the 2020-02-11 update level then containers running images with that update or later may fail.

**What you expected to happen**:
AKS Windows nodepools created today have an OS version of 10.0.17763.864, and the 2020-02-11 OS update is version 10.0.17763.1039. We need the ability to create nodepools with that version or higher.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new Windows nodepool in an AKS cluster. Note the OS version is 10.0.17763.864.

**Anything else we need to know?**:
I'm not attempting to repro or identify the specific issues here, only point out that Microsoft documents these compatibility issue can happen and the best course of action is to make sure the host OS is updated. The problem is documented here: http://bit.ly/3c8sORm

If [github issue 1454](https://github.com/Azure/AKS/issues/1454) were addressed then this need would go away. Especially if 1454 were implemented in such a way that I could reference any Windows Update version specifically when creating a nodepool, and the AKS team did not need to "bless" or "release" it first.

**Environment**: 
- Kubernetes version (use `kubectl version`): v1.15.7
- Size of cluster (how many worker nodes are in the cluster?): 2 Windows nodes in one nodepool
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Not relevant
- Others:

**Comment by tylfin** [comment]
Just some additional notes for motivation / others running into this issue:

This is impacting my project because we can no longer use the Azure Pipeline product to build our AKS Kubernetes windows images. 

This is specifically due to the update to the [Microsoft-Hosted VMs](https://github.com/actions/virtual-environments/commit/c79083dbd4868708372fdf22333187ebd748eb34). 

Updating to the latest [container image](https://hub.docker.com/_/microsoft-windows-servercore) caused [symptom 2 here](https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t), `Your Windows Server Container in Kubernetes does not reach the "running" state.`

I also noticed that chocolately installations were failing while trying to build on top of the _older_ base image on the newer VM.

E.g., without the ability to update the nodepools we're currently:

- unable to use the latest microsoft container image
- unable to use the Azure Pipeline product (with Microsoft-Hosted VMs, could go self-hosted)

**Comment by jayy-tee** [comment]
Also affected by this.

We have been able to work-around by manually updating the VMSS of the relevant node-pool to a later image. This did unfortunately break (for us at least) older images that are not on the updated container version.

```
az vmss update --resource-group {resource group} --name {vmss}  \
    --set virtualMachineProfile.storageProfile.imageReference.sku=2019-datacenter-core-smalldisk-2002 \
    --set virtualMachineProfile.storageProfile.imageReference.version=17763.1039.200220
```

Further reading that lead to the to the above:
- https://github.com/Azure/aks-engine/issues/2736
- https://www.danielstechblog.io/updating-the-base-image-of-a-vmss-based-aks-cluster/

**Comment by MikkelHegn** [comment]
As we close in on GA'ing this feature (what? :-)), we are getting on a regular cadence of updating the underlaying VHD for Windows node pools, and at the same time provide a way to upgrade the VHDs without having to upgrade the cluster (K8 version). This is the supported way of upgrading node pools in AKS: https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#upgrade-a-node-pool - as we release new VHDs these are validated against the K8 versions and all the other components we run in AKS.

For the specific issue mentioned, this [VHD](https://github.com/Azure/aks-engine/blob/master/vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1075.200227.txt) will soon be available and does not have the issue mentioned.

@tylfin: Regarding the hosted agents, please open an issues here: https://github.com/actions/virtual-environments/issues

**Comment by brobichaud** [comment]
This is great to hear @MikkelHegn. I look forward to the decoupling of OS image from K8s version. In the "upgrading node pools" doc you reference there is a note:

> The node pool OS image version is tied to the Kubernetes version of the cluster. You will only get OS image upgrades, following a cluster upgrade.

Based on what you're saying I assume this constraint and note will go away?

Also, while referencing that upgrade doc, There is also mention of the --control-plane-only option for az aks upgrade. Yet the latest version of AzureCli does not show that as an option (I upgraded my cluster last week and noticed this). Am I missing something?

**Comment by MikkelHegn** [comment]
I do see it in version 2.1.0 of the Azure CLI

![image](https://user-images.githubusercontent.com/12242001/75927566-7189a800-5e21-11ea-8408-33e2d89b79dc.png)

**Comment by MikkelHegn** [comment]
And yes, once the vhd-only option is out, the doc will be updated to reflect this.

**Comment by brobichaud** [comment]
Not to derail this topic, but I'm baffled. I have the same version of AzureCli and do not see that option. Wha? The only obvious delta I see is that I have aks-preview enabled (I don;t think it can be removed can it?). Could that make a difference?

![image](https://user-images.githubusercontent.com/5625540/76000623-d3492100-5eb8-11ea-8de1-5362fee86a7a.png)

**Comment by roycornelissen** [comment]
@jayy-tee thanks, your workaround works for us too. We started having problem with running a 32 bit app in our Windows container. They suddenly started failing silently, which is due to these Host OS / Container OS version mismatches, as described here https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t

With our Azure DevOps build agents, Windows Server Core image updates and AKS moving in such different paces, keeping our cluster running and being able to continue pushing out bugfixes to our software is very hard.

The latest release mentioned here (March 9) https://github.com/Azure/AKS/releases promises an update of the host images, but it doesn't seem to be rolled out yet. At least not in `westeurope`.

**Comment by MikkelHegn** [comment]
@roycornelissen the 03092020 release **did** have an update for the Windows host, even through we didn't get it in to the release notes (our bad). That is the January update of [Windows (973)](https://github.com/Azure/aks-engine/blob/master/vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.973.200213.txt). The release going out this week will bring [version 1075](https://github.com/Azure/aks-engine/blob/master/vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1075.200227.txt).

For the in-compat issue, the mitigation steps for AKS clusters should be:
1. Upgrade your node pool to latest.

1. Upgrade container images to
     
    a. If latest is 973 - rebuild container images off the same version (prior to introducing the breaking change) - however this leaves you without the Feb security patches.

    b. If latest is 1073 (this weeks release) - Upgrade your container images to the same version (or latest)

**Comment by roycornelissen** [comment]
@MikkelHegn thanks! Yeah I noticed that 03092020 also had an updated image. But it was not compatible with the images we were producing (unless we pinned our base images explicitly to 973).

I did the steps you suggested and they work. Host VMSS is now on 1075, and the latest `ltsc2019` image (=1098) works there. So I guess it's a matter of waiting until the update rolls out.

Not sure if I should ask that here, but will this incompatibility occur with every update or was this just an incident with the security patches?

**Comment by MikkelHegn** [comment]
This was an unintended break in compatibility based on a security bulletin. Don't expect this on Windows updates goings forward.

**Comment by roycornelissen** [comment]
Awesome, thanks! Really looking forward to Windows support in AKS hitting GA. It has really helped us to innovate on our legacy software.

**Comment by MikkelHegn** [comment]
@brobichaud - for the derailing topic :-) Are you using PowerShell or PowerShell Core?

**Comment by MikkelHegn** [comment]
@brobichaud - I see it on Azure CLI 2.2.0 on Windows.

**Comment by MikkelHegn** [comment]
A good bet is that your preview extension is outdated.

**Comment by brobichaud** [comment]
Thanks for circling back on this derailment @MikkelHegn.

Hmm, does Azure CLI rely on powershell under the covers? I have PowerShell 5.1 and Powershell 7.0 on my machine. I also just installed AzureCli v2.20 on WIndows and still do not see the option.

I did install the AKS preview extensions very early (as soon as AKS Windows went into preview) and didn't realize I needed to periodically update them, so never have. Is there a doc on how to do that?

**Comment by MikkelHegn** [comment]
There are no dependency on PowerShell, just wanted to check the shell, but that has nothing to do with it (I learned :-))

You'll have to remove and add the extension.
`az extension remove --name aks-preview`
`az extension add --name aks-preview`
From: https://github.com/Azure/AKS/blob/master/previews.md

**Comment by brobichaud** [comment]
> There are no dependency on PowerShell, just wanted to check the shell, but that has nothing to do with it (I learned :-))
> 
> You'll have to remove and add the extension.
> `az extension remove --name aks-preview`
> `az extension add --name aks-preview`
> From: https://github.com/Azure/AKS/blob/master/previews.md

This worked for me, thanks!

**Comment by brobichaud** [comment]
Today I upgraded a cluster to 1.15.10 and created a new Windows nodepool and am getting version 10.0.17763.973 nodes. Based on the AKS changelost from last week I was expecting to get 10.0.17763.1075. I'm trying to get myself out of this incompatible host/container morass but 973 is not new enough.

Any ideas why I am not seeing v1075 nodes on a new nodepool?

https://github.com/Azure/AKS/blob/master/CHANGELOG.md

**Comment by MikkelHegn** [comment]
The 20200316 release got stuck while rolling out, but is now in all regions.

**Comment by brobichaud** [comment]
> The 20200316 release got stuck while rolling out, but is now in all regions.

Now that my cluster is at v1.15.10 is there any way for me to update my nodepool since I can't run a k8s update again? (I'm not yet ready for v1.16.x)

**Comment by brobichaud** [comment]
OK, I see now that I do not need to update the k8s version to get the new Windows OS version on a newly create nodepool. I think I am now good. Thanks @MikkelHegn!

**Comment by MikkelHegn** [comment]
Yeah - that's unfortunately still a requirement. We are working to make it possible to upgrade the VHDs independently. Will keep you updated.

**Comment by MikkelHegn** [comment]
https://github.com/Azure/AKS/issues/893

**Comment by brobichaud** [comment]
> Yeah - that's unfortunately still a requirement. We are working to make it possible to upgrade the VHDs independently. Will keep you updated.

So why was it that I was able to get a new OS version on a nodepool created this morning in the cluster that I upgraded to k8s v1.15.10 two days ago? Did I land in some interim state when I updated my k8s version but the region was in the middle of updating, or something odd like that?

In the end perhaps it isn't all that important, but I am curious as I did not expect it to work this morning.

**Comment by brobichaud** [comment]
@MikkelHegn I noticed this in the AKS release notes from 2020-05-04:

> AKS now allows users to create windows nodepools with the latest windows image without requiring a cluster upgrade.

How does this work? When I create a new Windows nodepool do I just automatically get the latest version or is there some way to specify the version?

**Comment by MikkelHegn** [comment]
Yes, that is how it works, you'll always get latest, without having to upgrade the Control Plane. In a coming release (one or two out) we'll also add the option to upgrade the VHDs of existing node pools. Please note the 2020-05-04 release is still in-flight and not completely rolled out yet.

**Comment by brobichaud** [comment]
@MikkelHegn your "in-flight" comment actually reminds me of a question I've had for a while. Is there any way for me to know what release my cluster is running? Even if its some esoteric incantation of witchcraft...

**Comment by MikkelHegn** [comment]
With the upcoming 2020-04-01 api we plan to expose the latest VHD release and current VHD version on the node pools: https://github.com/Azure/azure-rest-api-specs/commit/cc135140943b5ea151256f6a8fe918cb9d2bd5e5#diff-d1c97c9c9fa74e9c9a36f278eafc974c
