### ISSUE TITLE
Set --balance-similar-node-groups flag to true for proper load balancing across nodepools

### ISSUE THREAD

**Issue by Bessonov** [Azure/AKS#1467]
May I ask why you only enabled those 8 specific flags to be updated?

In our case, we would like to have an evenly balanced cluster across several nodepools aka groups - meaning we would need to set the `--balance-similar-node-groups` flag to true.

Are there any plans to extend the number of adjustable flags?

_Originally posted by @davelosert in https://github.com/Azure/AKS/issues/1055#issuecomment-591315096_

**Comment by Bessonov** [comment]
@marwanad @jluk @davelosert I'm interested in this too and therefore create a new issue, as requested. Thank you!

**Comment by Bessonov** [comment]
https://github.com/Azure/AKS/releases/tag/2020-03-02

> Features
> Added balance-similar-node-groups as an additional parameter users can configure for AKS Managed Cluster Autoscaler (CA)

**Comment by marwanad** [comment]
@Bessonov the release is still rolling out in regions. 

@Bessonov and @davelosert fyi the flag would only work for K8s 1.16+. We are evaluating cherry-picking to 1.15 (and maybe 1.14) but that's dependent on the upstream autoscaler project.

**Comment by Bessonov** [comment]
@marwanad thank you very much for the clarification. We are now at 1.17.0 (preview). Should it be available on 1.17.0 too?

**Comment by flamingboo** [comment]
I CANNOT see balance-similar-node-groups in the latest AKS API 2020-02-01.
 https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2020-02-01/managedclusters

**Comment by marwanad** [comment]
@flamingboo The feature was made available in March and so will be available once the 2020-**03**-01 API is out everywhere.

**Comment by palma21** [comment]
Feature released. Closing. Thanks for the feedback.
