### ISSUE TITLE
Unable to connect to the server: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by droessmj** [Azure/AKS#1468]
**What happened**: Connections from Kubectl throw the following error: `Unable to connect to the server: x509: certificate has expired or is not yet valid`

**What you expected to happen**: No certificate errors. 

**How to reproduce it (as minimally and precisely as possible)**: Freshly deployed cluster using version 1.16.1. 

**Anything else we need to know?**: Browsing to my API server endpoint with both Chrome and Firefox throw certificate errors due to an untrusted CA. Image below shows that the certificate's validity period has passed (currently 8:34AM central). 
![image](https://user-images.githubusercontent.com/6099561/75557175-2f1d3100-5a05-11ea-8ca2-18acfb11ed8f.png)

I've cropped my specific API server endpoint from the above image. 

**Environment**:
- Kubernetes version (use `kubectl version`): 
- Size of cluster (how many worker nodes are in the cluster?) 3 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): None - installing ingress controller and pod identity on a fresh deployment. 
- Others:

**Comment by tomkerkhove** [comment]
Would be nice if this would integrate with Azure Key Vault and certificates are automatically renewed based on the Azure Key Vault events.

- Microsoft.KeyVault.CertificateNearExpiry event - See [Available event types](https://docs.microsoft.com/en-us/azure/event-grid/event-schema-key-vault#available-event-types)
- Runthrough of how to wire things up and react to it - https://docs.microsoft.com/en-us/azure/key-vault/event-grid-tutorial

**Comment by cody-at-coretek** [comment]
I have the same issue!!  Currently working with MSFT support but not making much traction!

**Comment by HarriKwok** [comment]
Are you running AZ CLI v2.2.0?  
Looks like it's azure-cli v2.2.0 that's causing an issue... it works fine with v2.0.0.
was scratching my head all morning...

**Comment by cody-at-coretek** [comment]
I always use whatever az cli is in the MSFT docker image at mcr.microsoft.com/azure-cli:latest

@HarriKwok currently, that *is* 2.2.0!  I'll version pin to 2.0 and see what happens!

```
azure-cli                          2.2.0

command-modules-nspkg              2.0.3
core                               2.2.0
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.9 (default, Nov 15 2019, 03:58:01)
[GCC 8.3.0]

Legal docs and information: aka.ms/AzureCliLegal



Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/clihats
```

**Comment by cody-at-coretek** [comment]
Now I see at this link:

https://github.com/Azure/azure-cli-docker

> ![image](https://user-images.githubusercontent.com/50838504/77342244-4995b200-6d06-11ea-9029-941b3fa7886e.png)


which links to https://hub.docker.com/r/azuresdk/azure-cli-python/

that container is running az cli 2.0.58:

```
docker run -it azuresdk/azure-cli-python
bash-4.4# az --version
azure-cli (2.0.57)

acr (2.1.13)
acs (2.3.16)
advisor (2.0.0)
ams (0.4.0)
appservice (0.2.12)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.7)
billing (0.2.0)
botservice (0.1.5)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.20)
consumption (0.4.2)
container (0.3.13)
core (2.0.57)
cosmosdb (0.2.7)
dla (0.2.3)
dls (0.1.7)
dms (0.1.2)
eventgrid (0.2.1)
eventhubs (0.3.3)
extension (0.2.3)
feedback (2.1.4)
find (0.2.13)
hdinsight (0.3.0)
interactive (0.4.1)
iot (0.3.5)
iotcentral (0.1.5)
keyvault (2.2.10)
kusto (0.1.0)
lab (0.1.5)
maps (0.3.3)
monitor (0.2.9)
network (2.3.1)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.3)
rdbms (0.3.6)
redis (0.3.2)
relay (0.1.3)
reservations (0.4.1)
resource (2.1.9)
role (2.3.1)
search (0.1.1)
security (0.1.0)
servicebus (0.3.3)
servicefabric (0.1.12)
signalr (1.0.0)
sql (2.1.8)
sqlvirtualmachine (0.1.0)
storage (2.3.1)
telemetry (1.0.1)
vm (2.2.14)

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.4 (default, Jan 10 2018, 05:20:21)
[GCC 6.4.0]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by cody-at-coretek** [comment]
I am unable to test az cli v 2.0 as I require arguments that version does not support.

I am becoming more suspect of my local -- is anyone else using a VM or docker container and encountering this issue?  Is the VM/container very long running?

**Comment by chunliu** [comment]
If you are using WSL 2, you would hit this issue when system time went wrong. https://github.com/microsoft/WSL/issues/4245

**Comment by strizzwald** [comment]
I had a similar issue. In my case, the certs created by our AKS cluster had expired. I've resolved this by rotating the certs, here's the documentation on how to do that 

https://docs.microsoft.com/en-us/azure/aks/certificate-rotation

**Comment by edernucci** [comment]
I had the same issue. I think MS should send a urgent e-mail to all aks customers prior march/2019. Maybe @jluk @jnoller can help with this communication.

**Comment by porrascarlos802018** [comment]
+1
https://docs.microsoft.com/en-us/azure/aks/certificate-rotation
reboot nodes, 
rebuild pods , everything back to normal operation.

**Comment by hdiass** [comment]
This should much more announced than it is...

**Comment by TomGeske** [comment]
@droessmj: We use self-signed certificates in AKS. That's most likely the reason why you see the error / warning message.

**Comment by TomGeske** [comment]
@edernucci: we do send communication to subscription owners for expiring cluster CA.  Let me check if we can start another round to resend.

**Comment by edernucci** [comment]
> @edernucci: we do send communication to subscription owners for expiring cluster CA. Let me check if we can start another round to resend.

@TomGeske I'm sorry but I'm the subscription owner and never received a warning about this issue.

**Comment by TomGeske** [comment]
Thank you for your feedback @edernucci. I will make sure we send out notification for impacted clusters again.

**Comment by edernucci** [comment]
Unfortunately there was no new communication, I must apply the procedure in another cluster today. Lucky for me, I am aware of the problem, I am disappointed with this posture from Microsoft.

**Comment by palma21** [comment]
@edernucci We don't send emails automatically every time a cluster expires that might not have been clear. We unfortunately don't have that capability or permission to do. They are sent periodically every few months

What we do have per cluster is AKS Diagnostics on the portal blade that will tell you your cert will expire soon or is expired. We're  also building an azure advisor that you can use to create an alert from the AKS blade as well so you're reminded with say 3 months that it will expire. This last part should land fairly soon this month.
