### ISSUE TITLE
AKS doesn't kill pods when they failed

### ISSUE THREAD

**Issue by patsadow2** [Azure/AKS#1469]
Hello,

I've encounter problem that aks doesn't remove failed pods. I suppose they steal CPU and Memory which is bad. Is there any setting to fix it ?

![image](https://user-images.githubusercontent.com/19226186/75590279-4861c400-5a7d-11ea-9b8f-f745295b1e60.png)

**Comment by seanmck** [comment]
The highlighted pod is killed. Its metadata just hasn't been garbage collected yet. It is not consuming any resources on the node.

https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-lifetime
