### ISSUE TITLE
List supported node-vm-sizes

### ISSUE THREAD

**Issue by sethtregenna** [Azure/AKS#147]
I can see that I'm able to set the --node-vm-size when creating an AKS instance and that it defaults to Standard_D1_v2.

Is there any documentation that lists the host sizes that are available to choose from?
Alternatively is there any way to get this using the cli?

Thanks.

**Comment by mboersma** [comment]
You can get this information directly from the `az` client through tab-completion:
```console
$ az aks create --l eastus -s  # hit [TAB] here, I have to do so twice for some reason...
Display all 156 possibilities? (y or n)
Basic_A0                Standard_D11_v2         Standard_D64_v3         Standard_DS5_v2         Standard_F8
Basic_A1                Standard_D11_v2_Promo   Standard_D64s_v3        Standard_DS5_v2_Promo   Standard_F8s
Basic_A2                Standard_D12            Standard_D8_v3          Standard_E16_v3         Standard_F8s_v2
...
```

**Comment by mboersma** [comment]
Looking at this more closely, I realize that the tab completer is returning *all* Compute VM sizes available in a location. AKS supports its own list of sizes, so it may reject some of those shown by the tab-completion.

I submitted [a PR](https://github.com/Azure/azure-cli/pull/5393) to return just the intersection of these two sets, which should be the sizes actually supported in a given location.

**Comment by mboersma** [comment]
The tab-completion feature only works in `bash`, so there is still a need for external documentation here. Otherwise, users have to find supported VM sizes through trial and error.

**Comment by neilpeterson** [comment]
@mboersma - got it. I will get the documentation work done.

**Comment by shahiddev** [comment]
Related to this it looks like not all available VM sizes are showing in the create experience in the portal. 
Just been responding to a Twitter follower who was about to walk away from trying AKS out because they could only see the more expensive VMs in the portal. 
I confirmed this was the case and then created a A0 cluster from the CLI to verify that I could even though portal didn't show this.

**Comment by slack** [comment]
Updated VM sizes going out to portal in the next deploy (afair).

**Comment by olavt** [comment]
> You can get this information directly from the `az` client through tab-completion:
> 
> ```
> $ az aks create --l eastus -s  # hit [TAB] twice here
> Display all 156 possibilities? (y or n)
> Basic_A0                Standard_D11_v2         Standard_D64_v3         Standard_DS5_v2         Standard_F8
> Basic_A1                Standard_D11_v2_Promo   Standard_D64s_v3        Standard_DS5_v2_Promo   Standard_F8s
> Basic_A2                Standard_D12            Standard_D8_v3          Standard_E16_v3         Standard_F8s_v2
> ...
> ```

I tried hitting TAB twice after the "-s" and it only appended " -" and I got invalid syntax. This was from Azure Cloud Shell (Bash).

**Comment by Benjiiim** [comment]
@neilpeterson, sorry to jump on this one 1y after completion but I can't find the corresponding documentation. Can you point me in the right direction? Thanks

**Comment by lgmorand** [comment]
@neilpeterson still required :-/ especially because new often get supported with new releases but there is no documentation on it.
