### ISSUE TITLE
aks - kuster secrets can't rean from .net 

### ISSUE THREAD

**Issue by dariuszbz** [Azure/AKS#1474]
**What happened**:
i created aks cluster, added windows nod, and pod with iis application. Application reads system environments variable (connection string). I populate the environment variable using yaml file when creating deployment with pods.
When I connect to the pod it self I can read the variables with valus by using cms -> set, or powershell: environment::Getvariables

but I CAN'T get the same set of environment variables from my IIS .net application.

**What you expected to happen**:
IIS .net application reads the same set environment values .

**How to reproduce it (as minimally and precisely as possible)**:
create aks cluster with windows node, create cluster secrets, add pod deployment with env from secrets.
try to read env values  

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by MikkelHegn** [comment]
How are you reading the env. var from within the code? If you are using the IIS image with ServiceMonito, it should pass through process environments: https://github.com/microsoft/IIS.ServiceMonitor

**Comment by dariuszbz** [comment]
If I use set from cmd - I can see all of them. If using .net I can't.

**Comment by MikkelHegn** [comment]
What's the .net code you use to enumerate them? https://docs.microsoft.com/en-us/dotnet/api/system.environmentvariabletarget?view=netframework-4.8 - Process should have them, if not, please consult the ServiceMonitor repo.

**Comment by MikkelHegn** [comment]
Closing as stale
