### ISSUE TITLE
Availability Zones Load Balancer

### ISSUE THREAD

**Issue by timwebster9** [Azure/AKS#1475]
When creating an AKS cluster with availability zones, you need to include a load balancer.  For example with this command from the [docs](https://docs.microsoft.com/en-us/azure/aks/availability-zones):
```
az aks create \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --generate-ssh-keys \
    --vm-set-type VirtualMachineScaleSets \
    --load-balancer-sku standard \
    --node-count 3 \
    --zones 1 2 3
```

This creates a public load balancer.  Is there a way to do this using an internal load balancer, or does the nature of this feature require it to be public?

**Comment by palma21** [comment]
You no longer need to explicitly introduce the load balancer parameter. An LB is still created but purely for outbound connection of the nodes. You can totally use only ILB for Inbound.

You can also restrict the traffic from the nodes only to the required endpoints or even provide your own egress method via UDR.

Ref:
https://aka.ms/aks/egress
https://aka.ms/aks/outbound-type

Let us know if you have further questions
