### ISSUE TITLE
[Egress Breaking Change] Azure MCR has Updated its CDN endpoints

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#1476]
The [Azure Container Registry](https://azure.microsoft.com/en-us/services/container-registry/) team has rolled out changes to their CDN endpoints that have a breaking change impact on AKS clusters which are [Locking down egress traffic](https://aka.ms/aks/egress), that is users using firewalls or network rules to restrict the egress endpoints.

We are working with the ACR team to mitigate this. 

If you are impacted by this change, please add, in addition to the existing endpoints in this [doc](https://aka.ms/aks/egress), the following ones:

 `*.data.mcr.microsoft.com` - HTTPS:443

**Update:** The ACR team has rolled back the changes to allow some more time for AKS users to update their FW/Network rules. The AKS Egress docs are up to date with the new requirements, please make sure your configurations are in accordance to: https://aka.ms/aks/egress

**Comment by kylel** [comment]
would this cause a cluster to be in a failed state after upgrade?

**Comment by palma21** [comment]
Scale and Upgrade operations could fail as the endpoint for retrieving the system images changed. (though we normally cache them in the AKS Image, depending on your versions, etc. you might need to pull some)
Best would be to open a support ticket to ensure the cause, without taking a look at your cluster can't tell for sure if that was indeed the cause.

**Comment by kylel** [comment]
Strange thing is that all the pods etc are still up and running. I just cant access the cluster via kubectl and the portal states it is in a failed state. Will log a support request

**Comment by sauryadas** [comment]
@kylel Can you update your firewall to add *.data.mcr.microsoft.com ? Also what operation did you trigger that led to the failure

**Comment by sauryadas** [comment]
@kylel nvm i see you upgraded

**Comment by kylel** [comment]
> @kylel Can you update your firewall to add *.data.mcr.microsoft.com ? Also what operation did you trigger that led to the failure

Do you mean the aks load balancer?

**Comment by sauryadas** [comment]
> > @kylel Can you update your firewall to add *.data.mcr.microsoft.com ? Also what operation did you trigger that led to the failure
> 
> Do you mean the aks load balancer?

How did you update your lb ?

**Comment by kylel** [comment]
> > > @kylel Can you update your firewall to add *.data.mcr.microsoft.com ? Also what operation did you trigger that led to the failure
> > 
> > 
> > Do you mean the aks load balancer?
> 
> How did you update your lb ?

I did not update it. I was just asking what you meant by adding  *.data.mcr.microsoft.com to my firewall. Which firewall?

**Comment by palma21** [comment]
If you're not using a firewall or restricting egress as per https://aka.ms/aks/egreess than this change won't affect you. 

I added a few more lines to the OP to make it more clear

**Comment by sanjeebsarangi** [comment]
We are seeing this:

`Events:
  Type     Reason                  Age                    From                                          Message
  ----     ------                  ----                   ----                                          -------
  Warning  FailedCreatePodSandBox  45m (x71 over 61m)     kubelet, aks-fastcompute-25023122-vmss000002  Failed create pod sandbox: rpc error: code = Unknown desc = failed pulling image "mcr.microsoft.com/k8s/core/pause:1.2.0": Error response from daemon: Get https://mcr.microsoft.com/v2/: dial tcp: lookup mcr.microsoft.com on 168.63.129.16:53: no such host
  Normal   SandboxChanged          39m                    kubelet, aks-fastcompute-25023122-vmss000002  Pod sandbox changed, it will be killed and re-created.
  Warning  Failed                  38m (x3 over 39m)      kubelet, aks-fastcompute-25023122-vmss000002  Failed to pull image "mcr.microsoft.com/k8s/aad-pod-identity/nmi:1.5.3": rpc error: code = Unknown desc = Error response from daemon: Get https://mcr.microsoft.com/v2/: dial tcp: lookup mcr.microsoft.com on 168.63.129.16:53: no such host
  Warning  Failed                  38m (x3 over 39m)      kubelet, aks-fastcompute-25023122-vmss000002  Error: ErrImagePull
  Warning  Failed                  37m (x7 over 39m)      kubelet, aks-fastcompute-25023122-vmss000002  Error: ImagePullBackOff
  Normal   Pulling                 37m (x4 over 39m)      kubelet, aks-fastcompute-25023122-vmss000002  Pulling image "mcr.microsoft.com/k8s/aad-pod-identity/nmi:1.5.3"
  Normal   BackOff                 3m52s (x157 over 39m)  kubelet, aks-fastcompute-25023122-vmss000002  Back-off pulling image "mcr.microsoft.com/k8s/aad-pod-identity/nmi:1.5.3"`

From within the cluster:

`
$ kubectl exec -it tdqg-node-7gp56 -n querygrid /bin/bash
bash-4.3# nslookup mcr.microsoft.com
Server:		172.21.0.10
Address:	172.21.0.10#53

Non-authoritative answer:
mcr.microsoft.com	canonical name = global.fe.mscr.io.
global.fe.mscr.io	canonical name = mcr-global.trafficmanager.net.
mcr-global.trafficmanager.net	canonical name = rp0310wus2.westus2.cloudapp.azure.com.

bash-4.3# nslookup rp0310wus2.westus2.cloudapp.azure.com
Server:		172.21.0.10
Address:	172.21.0.10#53

** server can't find rp0310wus2.westus2.cloudapp.azure.com: NXDOMAIN

bash-4.3# exit
`

 Outside the cluster:

`
$ nslookup rp0310wus2.westus2.cloudapp.azure.com
Server:		153.65.2.111
Address:	153.65.2.111#53

Non-authoritative answer:
Name:	rp0310wus2.westus2.cloudapp.azure.com
Address: 13.66.140.70
`

**Comment by sanjeebsarangi** [comment]
We still are experiencing the problem. We don't use Azure Firewall for AKS. Can someone please help with steps to add *.data.mcr.microsoft.com?

**Comment by sauryadas** [comment]
Do you have a support ticket?

**Comment by sanjeebsarangi** [comment]
Thank you Surya for replying.

Just created one and here is the ticket# 120031724000864

Thanks,
Sanjeeb

________________________________

**Comment by sauryadas** [comment]
@feiskyer can you assign this to Guoxun to take a look ? i cant seem to find his github id.

**Comment by gossion** [comment]
> nslookup mcr.microsoft.com Server: 172.21.0.10 Address: 172.21.0.10#53 Non-authoritative answer: mcr.microsoft.com canonical name = global.fe.mscr.io. global.fe.mscr.io canonical name = mcr-global.trafficmanager.net. mcr-global.trafficmanager.net canonical name = rp0310wus2.westus2.cloudapp.azure.com. nslookup rp0310wus2.westus2.cloudapp.azure.com Server: 172.21.0.10 Address: 172.21.0.10#53 ** server can't find rp0310wus2.westus2.cloudapp.azure.com: NXDOMAIN

The problem here looks like to be related to the DNS resolve, not CDN change. 

The CDN endpoints metioned above is about egress: if user has his/her AKS behind a firewall or nsg, he/she nee to white list "*.data.mcr.microsoft.com - HTTPS:443" to make sure the egress is not blocked. But the error here is that it failed to solve `mcr.microsoft.com`, which is a different problem.

@sanjeebsarangi , as you already created a support ticket, I believe our support engineer will look at it and involve network team (it is more likely to be VM dns issue: please highlight that it failed to solve mcr.microsoft.com in the VM)

**Comment by francoisdelisle** [comment]
ticket 120051224001187 opened at microsoft,
we are getting error message trying to connect to atlas mongodb
2020-05-12T09:22:35.864+0000 I  NETWORK  [ReplicaSetMonitor-TaskExecutor] Cannot reach any nodes for set PROD-Hornet-shard-0. Please check network connectivity and the status of the set. This has happened for 1 checks in a row.

**Comment by palma21** [comment]
Closing this as these updates have been rolled out in June.
