### ISSUE TITLE
PVC resizing doesn't work as expected

### ISSUE THREAD

**Issue by JoshDaone** [Azure/AKS#1477]
**What happened**:
While resizing the PVC volume capacity, PVC status turns to Resizing and gets a warning event as:

`Warning  VolumeResizeFailed  11m (x21 over 66m)  volume_expand  error expanding volume "elastic-system/elasticsearch-cluster-es-default-0" of plugin "kubernetes.io/azure-disk": compute.DisksClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status= Code="OperationNotAllowed" Message="Cannot resize disk kubernetes-dynamic-pvc-d69e9034-7e4b-49ed-a221-448e8b53803d while it is attached to running VM /subscriptions/<ID>/resourceGroups/<RG_Name>/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-name/virtualMachines/aks-agentpool-name-vmss_0. Resizing a disk of an Azure Virtual Machine requires the virtual machine to be deallocated. Please stop your VM and retry the operation."`

And doc didn't tell much info of this warning. https://docs.microsoft.com/en-us/azure/aks/azure-disks-dynamic-pv

StorageClass info:

```
+ kubectl describe sc managed-premium-retain
Name:            managed-premium-retain
IsDefaultClass:  No
Annotations:     ...
Provisioner:           kubernetes.io/azure-disk
Parameters:            kind=Managed,storageaccounttype=Premium_LRS
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Retain
VolumeBindingMode:     Immediate
Events:                <none>
```
PVC info:
```
+ kubectl describe pvc elasticsearch-data-elasticsearch-cluster-es-default-0 -n elastic-system
Name:          elasticsearch-data-elasticsearch-cluster-es-default-0
Namespace:     elastic-system
StorageClass:  managed-premium-retain
Status:        Bound
Volume:        pvc-d69e9034-7e4b-49ed-a221-448e8b53803d
Labels:        ...
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      100Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    elasticsearch-cluster-es-default-0
Events:        <none>
```

**What you expected to happen**:
The warning event should tell more detailed info of how to proper resize pvc, 
The PVC should be resized as expected.

**How to reproduce it (as minimally and precisely as possible)**:
kubectl patch pvc 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
+ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-27T21:11:27Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?)
6
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Stateful apps

- Others:

**Comment by Morriz** [comment]
bump

**Comment by omenv** [comment]
I have the same issue

**Comment by rpocase** [comment]
I just hit this as well. I upgraded to 1.16.7 last week and believe PVC resizing was working prior to this. In my specific instance where it had worked was with a 4 count statefulset. I was attempted to resize a statefulset with only a single pod in it where it failed.

I ended up having to completely delete the pvc/pv and just get it recreated. Luckily, losing the data in this case wasn't a big issue.

**Comment by axelgMS** [comment]
Azure CRP doesn't allow a Disk size to be modified when it's attached to a running VM.
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/expand-os-disk

so that "error" seems expected to me.


Also we only support modifying a Disk Size to a larger size - to some extent:
https://github.com/andyzhangx/demo/blob/master/linux/azuredisk/azuredisk-sizegrow.md

We don't support reducing the size. This could lead to data loss...

**Comment by vincenzodnp** [comment]
Sorry @axelgMS but does Azure consider a PV bounded to a PVC as a VM "attached disk"?
This completely changes the aim of `allowVolumeExpansion` parameter.
In my case, I'm trying to "expand" a volume.

**Comment by Morriz** [comment]
Any action here? Can we get k8s compliancy in the pvc arena from azure please?

**Comment by TomGeske** [comment]
I think this is related to kubernetes-sigs/azuredisk-csi-driver#273

**Comment by andyzhangx** [comment]
currently we don't support resized "attached" disk, pls follow this guide to resize azure disk: https://github.com/kubernetes/kubernetes/pull/64386

**Comment by guillelb** [comment]
The kubernetes documentation, since v1.15, clearly specifies that **you don't need to delete and recreate a Pod or deployment that is using an existing PVC**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims
![image](https://user-images.githubusercontent.com/26138193/94691373-81bf2280-0331-11eb-9fae-dc24186706cc.png)

Is Azure breaking the K8S specification?
I am using AKS v1.16.13

**Comment by andyzhangx** [comment]
I would say resize for azure disk driver is partially supported, fully support is our goal.

**Comment by iMoses** [comment]
> currently we don't support resize "attached" disk, pls follow this guide to resize azure disk: [kubernetes/kubernetes#64386](https://github.com/kubernetes/kubernetes/pull/64386)

this solution doesn't work in my case...

**Comment by kidlj** [comment]
Does the in preview Azure disk CSI driver support resizing PVC as expected?

https://docs.microsoft.com/en-us/azure/aks/azure-disk-csi

**Comment by andyzhangx** [comment]
> Does the in preview Azure disk CSI driver support resizing PVC as expected?
> 
> https://docs.microsoft.com/en-us/azure/aks/azure-disk-csi

@kidlj no, you can track this issue for any update: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/273

**Comment by daseth** [comment]
Seeing the same issue when trying to expand a PVC in AKS.

Cannot resize disk kubernetes-dynamic-pvc-f19fcb1a-7163-4f65-9780-591b35c2ca39 while it is attached to running VM /subscriptions/mysubscription/resourceGroups/MC_nc-myrg-aks_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-35064155-vmss/virtualMachines/aks-35064155-vmss_10. Resizing a disk of an Azure Virtual Machine requires the virtual machine to be deallocated. Please stop your VM and retry the operation

**Comment by andyzhangx** [comment]
> Seeing the same issue when trying to expand a PVC in AKS.
> 
> Cannot resize disk kubernetes-dynamic-pvc-f19fcb1a-7163-4f65-9780-591b35c2ca39 while it is attached to running VM /subscriptions/mysubscription/resourceGroups/MC_nc-myrg-aks_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-35064155-vmss/virtualMachines/aks-35064155-vmss_10. Resizing a disk of an Azure Virtual Machine requires the virtual machine to be deallocated. Please stop your VM and retry the operation

@daseth pls follow this workaround to expand disk size: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/known-issues/sizegrow.md, we are still working on online disk resize.

**Comment by daseth** [comment]
Worked like a charm. Thanks.

**Comment by palmerabollo** [comment]
Not stale. The workarounds are not valid in some scenarios (for example, operators that reconcile the disk size such as elasticsearch doesn't work well on AKS)

**Comment by sebastienc** [comment]
Hi, we've got a couple of workloads (ES, prometheus, etc..) that got us in the situation of having a disk full which normally we'd have expanded and were required to do it "offline" like described in this ticket. Would really appreciate to have this prioritized and made available.

**Comment by palmerabollo** [comment]
Not stale. Proposed workarounds don't cover many scenarios.

**Comment by LBoraz** [comment]
workarounds not applicable in my case

**Comment by annerajb** [comment]
How can this be done if you modify the pvc class before realizing you need to shut down the pods so it unattached the disk?

**Comment by omenv** [comment]
It is a problem when it comes to a db operator (Mongodb, Postgresql, etc)

**Comment by miwithro** [comment]
@andyzhangx what is the latest status here?

**Comment by andyzhangx** [comment]
there is a private preview in Oct for this storage feature, will update this thread when it's ready in azure disk driver.

**Comment by abhinavbakaya** [comment]
@andyzhangx How can I confirm that the disk is in an unattached state when following your [workaround](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/known-issues/sizegrow.md).
Do I have to see the status of the pv?

**Comment by andyzhangx** [comment]
> @andyzhangx I was able to follow this but I couldn't confirm that the disk goes in an unattached state. I just waited for 5 minutes after deleting pod before proceeding to resize the pvc. How can I confirm that when following your [workaround](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/known-issues/sizegrow.md)? The status of the pv and pvc were always bound.

@abhinavbakaya you could check whether that disk is in vm data disk list by azure cli or portal.

**Comment by veerendra2** [comment]
Any workaround? in my case, I use Strimzi Kafka which I cant scale down.

**Comment by OvervCW** [comment]
For us the offline resizing of PVCs didn't work in some cases (just kept failing with attached volume errors), so we handled it manually using the following steps:

1. Cordon the nodes that the pod is allowed to run on and kill the pod.
2. Detach the persistent volume from the VM it was running in the "Disks" panel on the instance in the Azure portal.
3. Open the disk in the Azure portal and change the size to the desired size.
4. Uncordon the nodes.
5. The pod should now resize the file system on startup and the persistent volume will have been successfully resized.

**Comment by vincenzodnp** [comment]
Sorry @OvervCW thanks for the solution but it's insane!
All the other cloud providers offer PVC resize managed by the CSI module.
Honestly, I'm 😲 that this issue is still Open...it sounds like a "Won't fix"

**Comment by OvervCW** [comment]
@vincenzodnp Oh definitely, it's not a *good* solution, but at least it's something until this problem is fixed :stuck_out_tongue_winking_eye:

**Comment by vincenzodnp** [comment]
> @vincenzodnp Oh definitely. It's not a _good_ solution, but at least it's something until this problem is fixed stuck_out_tongue_winking_eye

Totally @OvervCW ! My comment would like to point the attention to the behavior of the drive that causes important issues in daily ops

**Comment by andyzhangx** [comment]
> Sorry @OvervCW thanks for the solution but it's insane! All the other cloud providers offer PVC resize managed by the CSI module. Honestly, I'm 😲 that this issue is still Open...it sounds like a "Won't fix"

azure disk online resize on AKS would be supported on Jan release(with CSI driver v1.9.0) on canary regions first, check details here:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/273#issuecomment-994388591

**Comment by tmihalac** [comment]
Is this fix also coming to ARO in Jan ? 
In which version ?

**Comment by palmerabollo** [comment]
Not stale.

**Comment by Swaps76** [comment]
I'm having the same issue today on AKS 1.21.7, and I was able to run the expansion no problem prior.

**Comment by andyzhangx** [comment]
https://docs.microsoft.com/en-us/azure/aks/azure-disk-csi#resize-a-persistent-volume-without-downtime

Currently, Azure disk CSI driver supports resizing PVCs without downtime on specific regions. Follow this [link](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/expand-disks#expand-an-azure-managed-disk) to register the disk online resize feature. If your cluster is not in the supported region list, you need to delete application first to detach disk on the node before expanding PVC.
