### ISSUE TITLE
AKS Portal does not show E or D series VM

### ISSUE THREAD

**Issue by zhiweiv** [Azure/AKS#1478]
In AKS Release 2020-01-27:
> New Supported SKUs: Standard_ND40s_v3, Standard_ND40rs_v2, Standard_D_v4, Standard_E_v4 and Standard_NP families

But we are unable to select Ea v4-series in AKS creation, they don't appear in VM list.
![aks](https://user-images.githubusercontent.com/22001089/76192329-8056cd00-621c-11ea-90ec-1dfc34dc4ada.PNG)

We can find them in regular VM creation
![vm](https://user-images.githubusercontent.com/22001089/76192362-94023380-621c-11ea-8dbc-4176831ac44e.PNG)

**Comment by Rzpeg** [comment]
we cannot create an AKS with Standard_D_v4 as well.

**Comment by zhiweiv** [comment]
@jluk

**Comment by jluk** [comment]
Were you both able to complete this from Azure CLI?

Azure Portal requires a refresh of valid images to sync with what SKUs are available in AKS, this will take a few weeks. We will call this out on the release notes to clarify.

cc @palma21

**Comment by zhiweiv** [comment]
CLI works now.

**Comment by Rzpeg** [comment]
@jluk it almost works :)
Deployment failed. Correlation ID: d2e4bd25-11f1-47db-97ea-a8bff1c05e70. VMSSAgentPoolReconciler retry failed: deployment operations failed with error messages: {
  "code": "AllocationFailed",
  "message": "Allocation failed. We do not have sufficient capacity for the requested VM size in this region. Read more about improving likelihood of allocation success at http://aka.ms/allocation-guidance",
  "details": [
   {
    "code": "AllocationFailed",
    "message": "Allocation failed. We do not have sufficient capacity for the requested VM size in this region. Read more about improving likelihood of allocation success at http://aka.ms/allocation-guidance"
   }
  ]
 }

**Comment by jluk** [comment]
@rzpeg thanks for confirming, this should indicate that AKS does support the SKU however due to recent demand influx due to COVID responders in certain regions, allocation may fail if the target SKU is unavailable in the region at that time.

**Comment by Rzpeg** [comment]
@jluk yeah, thought so.
P.S. I am having an issue with a freshly deployed AKS cluster with default settings (RBAC enabled, Simple Networking), can't access the Dashboard. The documentation says that I should be able to open the dashboard after proxying with "az aks browse", in my case, however, the dashboard asks either for a kubeconfig or for an Access Token. The token obtained with "az account get-access-token --query accessToken -o tsv" gives 401. What am I missing?

**Comment by zhiweiv** [comment]
@jluk  Any update?

**Comment by alftio** [comment]
@jluk Please let us know if there is any update about it ?
We have tested it with the next results.
1-V4 SKU VMs are still not shown in the AKS Wizard from the Portal.
2-Creating from CLI works in some situations.
3- Using Terraform worked fine.

Thanks

**Comment by jluk** [comment]
@alftio the CLI should work in every situation - did you hit errors in that client?

@jenetlan as FYI for the portal coverage of these new SKUs

**Comment by alftio** [comment]
@jluk Thanks for the update. We ran the test one more time using CLI and it worked fine when the regions is "eastus2" . Other regions like "canadacentral"  or "westeurope" and different VM v4 sizes (Standard_D4a_v4,Standard_D4as_v4) are still failing.
The portal AKS Wizard is not showing the v4 SKU´s at all.

**Comment by porrascarlos802018** [comment]
Standard_E16ds_v4  doesn't seems to be enabled on eastus for AKS, please advise when we could get them available.

**Comment by palma21** [comment]
AKS does not support SKUs per region, it either supports them or not.

Ea and Da is supported but not in portal. The portal team should be adding it next week.
Ed is not supported.

**Comment by palma21** [comment]
The Da SKU is not available in canada for azure VMs, but it should be for westeurope
https://azure.microsoft.com/en-us/global-infrastructure/services/?products=virtual-machines&regions=canada-central,canada-east,europe-north,europe-west

if you have capacity there and you still have issues, please open a support ticket.

Since this ticket was about Da, Ds, Ea, Es I'm closing. For additional sizes please do open a separate issue.
