### ISSUE TITLE
[Feature Request] Built-in support for Kubernetes Event-driven Autoscaling (KEDA)

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/AKS#1479]
It would be good to have built-in support for [Kubernetes Event-driven Autoscaling (KEDA)](https://github.com/kedacore/keda) for which we can opt-out during creation of AKS cluster.

By doing that, we can easily autoscale workloads on other metrics without having to install about the installation of it.

**Comment by tomkerkhove** [comment]
Keep-Alive: 60 days

**Comment by tomkerkhove** [comment]
Any update on this @jluk @palma21

**Comment by palma21** [comment]
CC @jeffhollan

**Comment by tomkerkhove** [comment]
Any update on this?

**Comment by PixelRobots** [comment]
Any update on this?

**Comment by darthmolen** [comment]
Interested in this too. The current samples out there don't even work currently. (they give api errors)

**Comment by PixelRobots** [comment]
> Interested in this too. The current samples out there don't even work currently. (they give api errors)

Hello, are you able to share some of the examples that no longer work. Will like to see if we can get them sorted.

**Comment by tomkerkhove** [comment]
Yes, happy to help as well

**Comment by chirangaalwis** [comment]
+1 to this feature.

**Comment by chirangaalwis** [comment]
@tomkerkhove @palma21 do we have an ETA for this task?

**Comment by tomkerkhove** [comment]
I don't work for Microsoft so I cannot help on this, but am happy to help work with them to get this done.

**Comment by chirangaalwis** [comment]
@palma21 any update on this?

**Comment by chirangaalwis** [comment]
@jeffhollan @palma21 Any update on this? Does AKS have a planned ETA for this task?

**Comment by nmeisenzahl** [comment]
Hi all. Will this be delivered as an AKS add-on or extension?

**Comment by asubmani** [comment]
> Hi all. Will this be delivered as an AKS add-on or extension?

Maybe I am missing something here, but wouldn't both be ultimately be "managed by MSFT"?  How does it matter if we call it an add-on or an extension?

**Comment by PixelRobots** [comment]
> > Hi all. Will this be delivered as an AKS add-on or extension?
> 
> Maybe I am missing something here, but wouldn't both  ultimately be "managed by MSFT"?  How does it matter if we call it an add-on or an extension?

Check out my blog post about the difference.
https://pixelrobots.co.uk/2022/02/azure-kubernetes-service-aks-addons-and-extensions-who-is-responsible/

**Comment by mosabami** [comment]
will this allow  active connections based scaling for AKS nodes and PODs?

**Comment by jeffhollan** [comment]
@mosabami KEDA only supports pod scaling (horizontal today). That has an indirect influence on node scaling, as if KEDA overscheduled pods on available nodes that will trigger the node autoscaler, but is a related ask in the KEDA community to support node scaling in addition to pod scaling. Unfortunately this is highly vendor specific logic and no extensibility in K8s directly, so a separate ask https://github.com/kedacore/keda/issues/637

**Comment by tomkerkhove** [comment]
For cluster autoscaling, AKS provides Cluster Autoscaler (CA) but there is another issue open on this repo for supporting Karpenter (#2712)

**Comment by mosabami** [comment]
> @mosabami KEDA only supports pod scaling (horizontal today). That has an indirect influence on node scaling, as if KEDA overscheduled pods on available nodes that will trigger the node autoscaler, but is a related ask in the KEDA community to support node scaling in addition to pod scaling. Unfortunately this is highly vendor specific logic and no extensibility in K8s directly, so a separate ask [kedacore/keda#637](https://github.com/kedacore/keda/issues/637)

Thanks @jeffhollan. That answers the question on if it will support only pod scaling or cluster autoscaling as well. The other question was would this support scaling triggered by the event: excessive number of active connections to the pod?

**Comment by tomkerkhove** [comment]
That is not one of the current KEDA scalers but:
- You can build one yourself through external scalers, or
- We do welcome scaler suggestions on gihub.com/kedacore/keda

All supported scalers are available on 
keda.sh/docs/latest/scalers

**Comment by tomkerkhove** [comment]
This is now available in public preview:
- https://azure.microsoft.com/en-us/updates/public-preview-keda-addon-for-aks/
- https://docs.microsoft.com/en-us/azure/aks/keda

**Comment by mosabami** [comment]
thanks for the update @tomkerkhove

**Comment by raghulmsft** [comment]
Hi, I am a PM with the AKS team and have a quick question on KEDA. How do you see yourself best use this feature if it was auto enabled at cluster creation? In the sense, would you want a UI/UX that lets you set up scalers or would you prefer to do that through yaml files directly?

**Comment by PixelRobots** [comment]
> Hi, I am a PM with the AKS team and have a quick question on KEDA. How do you see yourself best use this feature if it was auto enabled at cluster creation? In the sense, would you want a UI/UX that lets you set up scalers or would you prefer to do that through yaml files directly?

I would like to see both. The UI/UX will help people who are getting started. It would also be good to have the visual representation in the portal.

**Comment by mblaschke** [comment]
Is there any target date for GA?

**Comment by tomkerkhove** [comment]
Adding @raorugan  who is the PM of the add-on

**Comment by adamyager** [comment]
> Adding @raorugan who is the PM of the add-on
@raorugan
Do you have any broad estimates on GA? We have this working well in non-prod but will not be brining it to prod until GA.

I am not asking for a date but an estimate. Dec of 2022, Feb-April of 2023, etc.

This is very helpful for planning

**Comment by raorugan** [comment]
We are planning to launch the KEDA add-on for AKS by end of December 2022. Will post more details as we get nearer to the launch date.

**Comment by asubmani** [comment]
> We are planning to launch the KEDA add-on for AKS by end of December 2022. Will post more details as we get nearer to the launch date.

would be nice to have migration guide (if applicable). We have KEDA installed manually in a few clusters and are looking for some high level migration plans.

**Comment by ms-sambell** [comment]
@raorugan  - any news?

**Comment by ppodevlab** [comment]
shouldn't this feature skip the metrics-server installation when bootstraping a cluster with keda enabled?

**Comment by raorugan** [comment]
Hello folks, thanks for your patience , we are heads-down working on completing the last mile of launching the KEDA add-on for AKS to make it enterprise-ready. Will post the GA launch date soon. Stay tuned!!

**Comment by raorugan** [comment]
@ppodevlab - can you provide details on sequence of operations that take place here? Do you mean an existing AKS with KEDA OSS installed and then enabling KEDA add-on for AKS should skip metrics server installation?

**Comment by matsvw** [comment]
Any update regarding the timetable for GA? In a support request with Microsoft I was told that GA would be in Jan/Feb 2023 and we have postponed a feature based on this, but if GA is still far in the future we might have to reconsider this strategy.

**Comment by adamyager** [comment]
> Any update regarding the timetable for GA? In a support request with Microsoft I was told that GA would be in Jan/Feb 2023 and we have postponed a feature based on this, but if GA is still far in the future we might have to reconsider this strategy

@raorugan any update here, we are delaying doing this as we dont have insights into GA release.  Thanks!

**Comment by raorugan** [comment]
Should be out in GA by mid July

**Comment by mblaschke-daimlertruck** [comment]
any updates?

**Comment by EvertonSA** [comment]
any updates?

**Comment by siorellana** [comment]
Hi team.
We need to implement KEDA on our clusters, but as this is still on preview we're delayed on this activity.
Do you know where I can validate the date of the release of this feature to GA?

Regards.

**Comment by tomkerkhove** [comment]
GA is around the corner and should come soon, sit back and wait!

![SoExcitedGIF](https://github.com/Azure/AKS/assets/4345663/703c442b-2eab-40bd-a72f-5cbdef92fce2)

**Comment by EvertonSA** [comment]
YESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS FINALYYYYYYYYYYYYYYYYYYYYYYYYYYYYY PLEASE GIVE US THAT

**Comment by EvertonSA** [comment]
any updates?

**Comment by EvertonSA** [comment]
any updates?

**Comment by mblaschke** [comment]
maybe soon could also mean 2024? 🤔
I guess we better be count on GA in 2024 then in 2023.

**Comment by qpetraroia** [comment]
Hi folks, 

We are very close, please keep an eye out on the [AKS release notes]( https://github.com/Azure/AKS/releases).

Thanks!

**Comment by mhadhbi** [comment]
The following announcement was published and removed from Azure Updates website:
![image](https://github.com/Azure/AKS/assets/1032904/b4601856-8efd-4932-a9b3-98523ca4f4c1)

@raorugan @qpetraroia How might we interpret this?

**Comment by tomkerkhove** [comment]
> Hi folks,
> 
> We are very close, please keep an eye out on the [AKS release notes](https://github.com/Azure/AKS/releases).
> 
> Thanks!

That it's very close?! ;)

**Comment by siorellana** [comment]
Hello team.
Any update on this?

**Comment by EvertonSA** [comment]
any updates?

**Comment by raorugan** [comment]
KEDA Add-on for AKS is now in GA!!!

**Comment by EvertonSA** [comment]
OMG!!! YESS!!

**Comment by nrv-96** [comment]
Yes!!
https://azure.microsoft.com/en-us/updates/ga-kubernetes-eventdriven-autoscaling-keda-addon-for-aks/
https://learn.microsoft.com/en-us/azure/aks/keda-deploy-add-on-cli

**Comment by mblaschke** [comment]
just tried to deploy a cluster with KEDA enabled in CUS and WEU
```
Message: Feature Microsoft.ContainerService/AKS-KedaPreview is not enabled. Please see https://aka.ms/aks/previews for how to enable features. 
```

🤔

**Comment by tomkerkhove** [comment]
Please open a support ticket :)

**Comment by raorugan** [comment]
Can you share the command used to deploy the cluster with KEDA add-on preview tag is no longer needed. Updated docs here - https://learn.microsoft.com/en-us/azure/aks/keda-deploy-add-on-cli#before-you-begin

**Comment by mblaschke** [comment]
It was a normal ARM/bicep deployment using `Microsoft.ContainerService/managedClusters@2023-07-01`, we're not using az cli for deployments.

**Comment by EppO** [comment]
using AZ cli, az aks --enable-keda throws the same error: 
```
(PreviewFeatureNotRegistered) Feature Microsoft.ContainerService/AKS-KedaPreview is not enabled. Please see https://aka.ms/aks/previews for how to enable features.
```
As Keda is now GA, I would expect enabling this preview feature is not required.

**Comment by tomkerkhove** [comment]
AKS add-on is now GA, learn more on https://azure.microsoft.com/en-us/updates/ga-kubernetes-eventdriven-autoscaling-keda-addon-for-aks/

**Comment by eaterm** [comment]
It does not seem to be GA, as there is still a message:

```
PreviewFeatureNotRegistered" Message="Feature Microsoft.ContainerService/AKS-KedaPreview is not enabled. Please see https://aka.ms/aks/previews for how to enable features. 
```

**Comment by tomkerkhove** [comment]
Please make sure to update your Azure CLI instance and file a support ticket if the issue remains.

**Comment by martin-reich** [comment]
Same error for me
`(PreviewFeatureNotRegistered) Feature Microsoft.ContainerService/AKS-KedaPreview is not enabled. Please see https://aka.ms/aks/previews for how to enable features.
Code: PreviewFeatureNotRegistered`

my cli version and installed extensions:
```
az version                                                                                                                                                                              
{
  "azure-cli": "2.54.0",
  "azure-cli-core": "2.54.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
}

```

**Comment by justinmchase** [comment]
This is still failing for me saying it requires the `aks-preview` extension to be installed in the azure cli and I am blocked from installing that extension.
