### ISSUE TITLE
Issue when creating a cluster with a secure client secret.

### ISSUE THREAD

**Issue by IanMoroney** [Azure/AKS#148]
When creating a k8s cluster with a secure password containing special characters, the custom script extension scripts don't handle the secure password and throw an error.

Another example of this is in the azure shell command to create the cluster instead of the gui:

    az aks create -g MyResourceGroup2 -n MyManagedCluster2 -l "EastUS" --generate-ssh-keys --client-
    secret PEWY&6)%9@eYX&cM --service-principal anything

you will get an error right away.

if you provide the same password to the gui and ask it to create the cluster, it will fail on the custom script extension for all nodes.

Microsoft case number 118011817489170.

**Comment by brendandburns** [comment]
We will work on fixing validation in the GUI. Thanks for the report.

**Comment by mboersma** [comment]
When using that same password from the CLI, I didn't get an error right away, but eventually:
```
$ az ad sp create-for-rbac -n "MyAppCLI" --password 'PEWY&6)%9@eYX&cM'
$ az aks create -n MyManagedClusters2 -g maboersm -l "EastUS" --client-secret 'PEWY&6)%9@eYX&cM' --service-principal 'http://MyAppCLI'
Deployment failed. Correlation ID: 1234. Provisioning of resource(s) operation ID 7f00d40b-e16b-4c4d-a0a0-1234 of container service 'MyManagedClusters2' for cluster resource group 'MC_maboersm_MyManagedClusters2_eastus' failed with errors: {
  "code": "VMExtensionProvisioningError",
  "message": "VM has reported a failure when processing extension 'cse1'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=2\n[stdout]\n\n[stderr]\n/bin/sh: 1: Syntax error: \")\" unexpected\n\".",
  "details": [
   {
    "code": "VMExtensionProvisioningError",
    "message": "VM has reported a failure when processing extension 'cse1'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=2\n[stdout]\n\n[stderr]\n/bin/sh: 1: Syntax error: \")\" unexpected\n\"."
   }
  ]
 }
```

I don't see any regex defined in the Swagger or SDKs for the graphrbac service principal secret, and obviously you can create one that includes a parenthesis char. The only problematic special character here seems to be the parenthesis char `)`--I've tried several variations, all of which succeeded. I'll add some AKS-specific validation to the CLI and portal that rejects that.

**Comment by IanMoroney** [comment]
Instead of restricting the input (as many companies have strict password
policies and sometimes the people creating the resources don't have control
over what password is set, or in ideal circumstances, they don't get to see
the password at all) is it possible to encapsulate the password in the
scripts that are using it in quotations so it can accept any password?

Alternatively, implement this fix now but add a work item to a different
milestone to swing back and add support for it later?

**Comment by mboersma** [comment]
Agreed--rejecting `(` and `)` is a band-aid over what is probably an escaping or quoting issue lower down. The real fix needs to happen in the custom script extension processing, I assume, and I'll track that down as well.

**Comment by yevster** [comment]
Shouldn't all characters allowed per [Azure Directory password policy](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-passwords-policy) be supported? Because one could be creating a cluster from CLI using credentials for an account already created.

**Comment by seanknox** [comment]
Closing due inactivity. Feel free to re-open if still an issue.

**Comment by IanMoroney** [comment]
@seanknox was the validation fixed in the GUI?
