### ISSUE TITLE
Cannot update min-count when autoscaling is enabled and node-count is below min-count

### ISSUE THREAD

**Issue by FireDrunk** [Azure/AKS#1481]
**What happened**:
Trying to update --min-count with az aks update
**What you expected to happen**:
--min-count is updated
**How to reproduce it (as minimally and precisely as possible)**:
- Create cluster with --min-count 1 --max-count 3
- Try: az aks update --update-cluster-autoscaler --min-count 2 --max-count 3
**Error:**
```2020-03-09T09:48:33.0927691Z ERROR: Current node count '2' is not in the range of min-count and max-count.```

**Anything else we need to know?**:
There is no easy way to update the min-count unless by disabling the autoscaler first.
It would be nice have an option --force-min-count that issues a scale to the new min-count (which is what we want).

**Environment**:
- Kubernetes version (use `kubectl version`): **1.16.4**
- Size of cluster (how many worker nodes are in the cluster?) **2**
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) **none, empty cluster.**
- Others: **nothing special.**

**Comment by Aaron-ML** [comment]
I'd love for this limitation to be removed, it seems arbitrary from the customer perspective. 

The only solution for this for now is to artificially increase replica count to force scale up, or manually resize the VMSS behind the scenes, and then set min count.

**Comment by marwanad** [comment]
I think the main reason this was put in place is to avoid falling in the misconception that CA would act and scale-up to respect this limit. It would, however, respect this limit in further scaling operations.

We will evaluate the `force-min-count` option or other possibilities.

**Comment by jluk** [comment]
This has been fixed in the latest AKS release, closing as a result.

The latest CLI version 2.6.0 fixes this limitation.
