### ISSUE TITLE
[Addon] Azure Policy add-on for AKS (GA release ongoing)

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#1488]
https://docs.microsoft.com/en-us/azure/governance/policy/concepts/rego-for-aks

Public preview of Azure Policy on AKS uses Gatekeeper v2, with the release of Gatekeeper v3 AKS will renew a new version of Azure Policy to use Gatekeeper v3 and bring with it a new set of improvements and capabilities.

This will require an update of any active install of the Azure Policy addon by disabling and re-enabling the addon.

**Comment by jluk** [comment]
Regional availability tracked here: https://github.com/Azure/AKS/issues/1606

**Comment by jluk** [comment]
This feature is now releasing across all regions as GA. We will be updating the regional availability as it rolls globally.

Announcement: https://azure.microsoft.com/en-us/updates/ga-policy-addon-for-azure-kubernetes-service/

**Comment by ruchikaguptaa** [comment]
The feature is GA in the following regions. This is a live list that will be updated as we continue the rollout.
* West Central US
* Canada Central
* Australia East

**Comment by jluk** [comment]
This has rolled globally in public cloud, closing the issue as a result.
