### ISSUE TITLE
[Feature] Node local DNS

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#1492]
Re-architect azure CNI for more resilient DNS

**Comment by timja** [comment]
Any update on this?

We deployed nodelocaldns and it made a massive difference for us, (https://github.com/Azure/AKS/issues/1326#issuecomment-640626833)

**Comment by jstewart612** [comment]
@palma21 one thing you may want to take back to your folks is the currently proposed nodelocal daemonset is not tolerating itself sufficiently to prevent from inadvertent inability to assign to any nodes with custom taints on them.

I used these tolerations and they resolved that issue for us:
- operator: Exists
  effect: NoExecute
- operator: Exists
  effect: NoSchedule

**Comment by JennyLJY** [comment]
Any updates on this feature? When is the ETA?
@palma21

**Comment by palma21** [comment]
It's currently on the committed items for this semester and under design review. Will have more ideas on the eta by the end of the month.

**Comment by curtdept** [comment]
Hopefully this is higher in the priority list, then would be amazing to have. I get DNS latency bursts constantly.

**Comment by bergerx** [comment]
Any news on the ETA? If there is now a rough timeline for ETA, we may prefer wait a bit more rather than investing engineering time into something which would be obsolete soon after.

**Comment by curtdept** [comment]
@bergerx this will make you happy :)

https://github.com/curtdept/aks_nodelocaldns/blob/main/nodelocaldns.yaml

**Comment by MiyKh** [comment]
My AKS cluster is actually running with kubenet, the DNS service IP is something like 172.17.80.10, but I cant' figure out what is `<node-local-address>` parameter, is it an IP from the service CIDR? pod CIDR?

**Comment by PSanetra** [comment]
@MiyKh the `<node-local-address>` is just some random and not-in-use IP in the `169.254.20.0/16` subnet. It will be used on each node and will not be reachable from outside the node.
See https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/#configuration

> The local listen IP address for NodeLocal DNSCache can be any IP in the 169.254.20.0/16 space or any other IP address that can be guaranteed to not collide with any existing IP. This document uses 169.254.20.10 as an example.

**Comment by MiyKh** [comment]
@PSanetra Thanks for the clarification.The node local dns is deployed into the kube-system namespace but it is deleted by Azure sync system, how can we force AKS to skip deletion on this component?

**Comment by PSanetra** [comment]
@MiyKh interesting. We still have those labels set on the daemonset, but it is not getting deleted. We are running AKS 1.17.11.

**Comment by curtdept** [comment]
> @MiyKh interesting. We still have those labels set on the daemonset, but it is not getting deleted. We are running AKS 1.17.11.

Same here on 1.19

**Comment by MiyKh** [comment]
I have the same behavior than this issue: https://github.com/Azure/AKS/issues/1435

**Comment by curtdept** [comment]
> I have the same behavior than this issue: #1435

What also version?

**Comment by MiyKh** [comment]
> > I have the same behavior than this issue: #1435
> 
> What AKS version?

This is a 1.18.8 cluster with kubenet networking, removing the labels was the solution but I guess, I would still need to redeploy it after cluter upgrade.

**Comment by 4c74356b41** [comment]
@curtdept @palma21 hey folks, do you have any ETA for us? Will this be backported to 1.17.x or not? thanks!

**Comment by djsly** [comment]
Any news on an ETA ?

**Comment by joaguas** [comment]
@4c74356b41 @djsly 
Azure CNI now defaults to transparent mode which uses layer 3 routing which means pod-to-pod no longer relies on conntrack and will not be affected by its race condition. [This should mitigate the 5s delay on DNS lookups](https://docs.microsoft.com/en-us/azure/aks/faq#benefits-of-transparent-mode)

Upgrading a cluster still using bridge mode [will make it use transparent mode instead](https://github.com/Azure/AKS/issues/1954#issuecomment-759306712)

**Comment by djsly** [comment]
@joaguas thanks! I asked a question about querying the status. Wondering how to check if our clusters consumed the update or not yet, since we did performed a few updates.

**Comment by 4c74356b41** [comment]
you can just do `az aks nodepool upgrade --node-image-only`, this would rollout latest os base image with this fix for sure (no kubernetes version upgrade), if you already have it - it will just return success in 30ish seconds

**Comment by djsly** [comment]
ok so the CNI transparent mode is baked in the image. good to know. I will try to know which base image contains the fix then. 

thanks @4c74356b41

**Comment by joaguas** [comment]
Hi @djsly , an easy way will be to get a shell in one of the nodes and check either the interfaces or route tables.
If there's an interface called `azure0` that means it's still using a bridge.

You can also check the route table (`ip route show`). If you see multiple routes for the veth interfaces (azvXXXXXXXX) that means the node is already running the L3 routing (transparent mode)

Thanks for the tip @4c74356b41
