### ISSUE TITLE
[Feature] AKS support for containerd

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#1497]
This issue captures the ability to customize your container runtime to use containerd instead of Moby.

Details here: https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#container-runtime-configuration-preview

**Comment by PrabhuMathi** [comment]
Please advise on below queries:
When this is expected to be in GA? 
What would be the planned default k8s version this will get default? Is it going to be 1.18.8 like ubuntu 18.04 for node pools?
