### ISSUE TITLE
Preview of K8s 1.18 on AKS

### ISSUE THREAD

**Issue by jluk** [Azure/AKS#1499]
K8s 1.18 is in the late stages of the release cycle targeting a release at the end of March. AKS will bring this version into preview initially, following the regular lifecycle of K8s version support in AKS from preview to GA.

https://github.com/kubernetes/sig-release/tree/master/releases/release-1.18

**Comment by zhiweiv** [comment]
@jluk do you have ETA on this?

Thanks

**Comment by jluk** [comment]
This will be releasing this month to make 2 preview versions for AKS (preview 1.17, preview 1.18).

**Comment by jluk** [comment]
This is in the process of releasing and will be available by end of week globally.

**Comment by jluk** [comment]
This has reached preview, so closing this as a duplicate of #1442 which we can use as a tracker for 1.18.
