### ISSUE TITLE
10/31/17 Issue: Groups failing to create and then being recreated

### ISSUE THREAD

**Issue by dsandersAzure** [Azure/AKS#15]
Today, trying to deploy a cluster received an error: 
```
Deployment failed. Correlation ID: 8b0cc0fc-d4b1-42ed-a118-0b3a3843fcaa. getAndWaitForManagedClusterProvisioningState error: <nil>
```
Deleted the resource group in the portal and then checked my Azure subscription later (to make sure I'm not burning any costs) and the resource group was recreated; I had to manually delete the RG again. This has happened every time I tried to create a cluster today - is the service down?

David

**Comment by berndverst** [comment]
You should be able to create AKS in WestUS2 now. See #2

**Comment by dsandersAzure** [comment]
Yeah, this issue appears to be resolved. Closing the case.

**Comment by dsandersAzure** [comment]
I need to reopen this. This morning (11/06) tried to spin up a cluster and this error "No nodes are available that match all of the predicates: NodeNetworkUnavailable (2)." appears when I describe my pods.

So, I kill the cluster and issue an ``az group delete --name *groupname* --yes --no-wait`` and the cluster starts tearing itself down. The *groupname* is successfully deleted and then it starts to delete the autogroup created by the ``az aks create`` command. 

5 minutes later, the original *groupname* re-appears and I have to go to the portal to delete it manually.

Capacity issues or not, I'm not sure AKS is ready for beta as it appears more alpha than beta.

David

**Comment by dsandersAzure** [comment]
Happened again this morning. Here’s the flow:

1. Create a cluster using as aks and wait for it to complete
2. After completion, do some stuff - add a new public IP to the automatic group (so I can assign it to the K8S LB)
3. Tear down the cluster using as group delete
4. Monitor the tear down on portal.azure.com
  A. The group is deleted
  B. The auto created group starts deleting
  C. About half way into the resources being deleted in the auto created group, the original group reappears along with the cluster.
  D. Azure deletes the auto created group successfully *BUT* the original group with the one resource (the cluster) remains and is *not* deleted.
5. I have to manually delete the resource group again.

If you need help on this, I can record a session from start to finish.

David

**Comment by slack** [comment]
@dsandersAzure by completion, did the deployment in the second `MC_` resource group finish successfully?

**Comment by slack** [comment]
Closing stale issue. Feel free to re-open if you continue to see the behavior.
