### ISSUE TITLE
AKS allows creation of NodePools in different Subnets (Kubenet)

### ISSUE THREAD

**Issue by jluk** [Azure/AKS#1500]
This issue captures the support of the scenario to bring your own subnet to a given nodepool on a cluster with Kubenet networking.

This scenario has a dependency on #400 .

**Comment by ezYakaEagle442** [comment]
Hi  @palma21  any update on this issue please ?

**Comment by paulgmiller** [comment]
I have no good reasons why this shouldn't work and is possible through the az cli/api already.  My simplistic run through this didn't expose any problems. So I think we could close this?

**Comment by ams0** [comment]
Confirmed, CLI and Terraform works just fine.

**Comment by paulgmiller** [comment]
@palma21 is telling me there's still issues with custom route table

**Comment by wedaly** [comment]
Tested this manually last week:

1. Create an AKS cluster with network plugin set to kubenet.
2. Create a new subnet in the same vnet, but do not associate it with any route table.
3. Create a new agent pool in the same cluster with the new subnet.

Discovered that AKS does not associate the new subnet with the existing route table until the next PutManagedCluster operation (e.g. a reconcile or upgrade). Until that happens, pods in the new subnet will not be able to communicate with pods on other nodes.

Additionally, if the new subnet is already associated with a route table, then AKS will not associate it with the original subnet's route table. In this case, pods in the new subnet won't be able to communicate with pods on other nodes even after the next PutManagedCluster operation.

**Comment by jayush** [comment]
Is this feature supported now? Can we deploy an AKS cluster with kubenet and with separate subnets for nodepools?

**Comment by nzarhin** [comment]
is this already available?

**Comment by paulgmiller** [comment]
This was never actually behind a preview flag it just had the caveats @wedaly  poined out above. 

However we are not going to fix those caveats as we strongly want people to move to overlay instead

https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay

Please try that out. You can upgrade to it directly and we are trying to default it for all new clusters in 2024.
