### ISSUE TITLE
New agent deployments are leaving old ReplicaSet definitions behind

### ISSUE THREAD

**Issue by cdeptuckUEI** [Azure/AKS#1502]
**What happened**:
New agent deployment are leaving old replicaset definitions behind for system agent deployments (ie. metrics-server, coredns, coredns-autoscaler, etc)

**What you expected to happen**:
New agent deployment should limit its revisionhistory to prevent buildup of unused definitions

**How to reproduce it (as minimally and precisely as possible)**:
Make AKS cluster wait a bit for MS to push agent changes (likely possible force reproduction by creating an older revision cluster and then upgrading it)

**Anything else we need to know?**:
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit

![image](https://user-images.githubusercontent.com/61163180/76459778-08161600-639a-11ea-831c-14865440d48e.png)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.7 and 1.16.4
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by cdeptuckUEI** [comment]
Some of these, especially on older cluster had a default rev limit of max int.... the pain!

**Comment by curtdept** [comment]
Staling out :(

**Comment by palma21** [comment]
Revision limit is now set to 2 after this week's release. Thanks for the report.
