### ISSUE TITLE
no such host error

### ISSUE THREAD

**Issue by santhoshrathode** [Azure/AKS#1504]
I installed default version of AKS version 1.14.8.

Its in private VNet.

When i am using kubectl in CLI I am getting no such host error.
Unable to connect to the server: dial tcp: lookup ***** on 168.63.129.16:53: no such host error.

Any help on this?

**Comment by palma21** [comment]
Are you deploying the AKS nodes to a private vnet or deploying a private cluster? Seems this would benefit from direct help from our support team to guide you thought the steps. Could you open a support ticket via the Azure Portal for that?

I'll close this issue for now, but feel free to open a new one if you have further questions
