### ISSUE TITLE
Bring your own vault

### ISSUE THREAD

**Issue by cforce** [Azure/AKS#1509]
Is there any way to use vm disk encryption (https://aka.ms/aks/byok ) with a key that is provided "unmanaged", so neither a azure vault but a custom manged key vault eg hashicorp vault? It's important for me that keys not managed in any azure / Microsoft accessable service
Key vault could be an on prem or custom VM with HSM Interface.

**Comment by palma21** [comment]
This is not a feature supported by the underlying capability: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption#customer-managed-keys

This would have to be supported by Azure first. User voice is likely the best place for that feedback for azure storage: https://feedback.azure.com/forums/217298-storage

@ramankumarlive is this something that is planned/in the roadmap?
