### ISSUE TITLE
Upgrade failed from 1.8.1 to 1.8.6

### ISSUE THREAD

**Issue by agalisteo** [Azure/AKS#151]
```
az aks upgrade --name myaks --resource-group myresourcegr --kubernetes-version 1.8.6
```
**Deployment failed. Correlation ID: 09312a25-04f3-4e35-8f79-6b2337bb7f19. Operation failed with status: 200. Details: Resource state Failed**

```
az aks show --name myaks --resource-group myresourcegr --output table

Name     Location    ResourceGroup    KubernetesVersion    ProvisioningState    Fqdn
-------  ----------  ---------------  -------------------  -------------------  -----------------------------------------
myaks  westeurope  myresourcegr             1.8.6                Failed               myaks-81cf39b1.hcp.westeurope.azmk8s.io
```
Retrying the upgrade action I get the same error above

**Comment by mcops** [comment]
same error here. Since yesterday evening cluster was gone and in "pending" state. Did upgrade now failed.
I'm definitely switch back to ACS-engine, mich more stable than AKS. I'd notrecommend to use AKS for production!

**Comment by agalisteo** [comment]
Solved, problem with the quotas of my subscription.

**Comment by ElanHasson** [comment]
@agalisteo How did You resolve it?

**Comment by pr0nin** [comment]
@agalisteo any particular quotas you had to change?

**Comment by slack** [comment]
We are also working on bubbling up errors from the underlying ARM deployment. The usual culprit during upgrade is reaching core or core family quotas.

**Comment by pr0nin** [comment]
Using AKS delete and then create with the exact same configuration as before except for Kubernetes version gave me a working cluster. 

For some reason my existing deployment and secrets were preserved.

I'm pretty sure the extra resource group AKS creates were deleted during AKS delete. But the fact that things from the deleted cluster remained makes me unsure if I checked properly.

**Comment by tslavik** [comment]
I got the same error when I was trying to upgrade to 1.8.7
Deployment failed. Correlation ID: ca8aa507-9e3e-453b-9c25-fce40e1622fa. Operation failed with status: 200. Details: Resource state Failed

**Comment by tlycken** [comment]
Got a similar error today:

```
$ az aks upgrade --name k8s-cluster --kubernetes-version 1.9.6
Kubernetes may be unavailable during cluster upgrades.
Are you sure you want to perform this operation? (y/n): y
Deployment failed. Correlation ID: b9acbb37-c0a3-4e39-876c-7856caa5090c. Internal server error
```

EU-West, can send details on resource group etc privately (don't want to post those names in public).

**Comment by tlycken** [comment]
@seanknox Do you have any details to share on this issue? What has changed, that motivates closing this issue?

Not questioning your decision, just asking for info :)
