### ISSUE TITLE
Delete specific node using az aks scale

### ISSUE THREAD

**Issue by sanjeebsarangi** [Azure/AKS#1512]
How to delete specific AKS node using az aks scale? One of the node went to bad state after reboot. I want to take it down and scale it back.

Environment:
- Kubernetes version: 1.14.8
- Size of cluster: 7
- General description of workloads in the cluster: Machine learning

**Comment by vishnujanardhanan** [comment]
@sanjeebsarangi You can cordon, drain the node and kubectl delete node. I guess it is still required to remove the node from portal. Once this is done running az aks scale will spin up the nodes specified.

**Comment by jluk** [comment]
Selectively removing nodes is not supported today in favor of automatic remediation which AKS enables. You can read more about that capability here:
https://docs.microsoft.com/en-us/azure/aks/node-auto-repair

**Comment by sjwaight** [comment]
Related: #2453
