### ISSUE TITLE
Updating AAD enabled cluster using 2020-03-01 api version may fail with Changing property 'aadProfile.managed' is not allowed

### ISSUE THREAD

**Issue by weinong** [Azure/AKS#1519]
**What happened**:
Updating an AAD enabled AKS cluster using 2020-03-01 api version may fail with "Changing property 'aadProfile.managed' is not allowed"

**Workaround**:
* Use api-version 2020-02-01 instead.
* With azure cli extension, downgrade to 0.4.35
```sh
az extension remove -n aks-preview
az extension add -y --source https://azurecliaks.blob.core.windows.net/azure-cli-extension/aks_preview-0.4.35-py2.py3-none-any.whl
```

**Comment by weinong** [comment]
hotfix has applied. issue is mitigated.

**Comment by kevinwedwards** [comment]
@weinong 

We're on hosted agents, which is running:
azure-cli                          2.3.1

Do we need to install aks-preview still?  Should it be a different version?

**Comment by weinong** [comment]
@kevinwedwards the issue has been fixed. you can continue to use your azure cli
