### ISSUE TITLE
Feature request: Support migrating from service principal clusters to managed identity clusters

### ISSUE THREAD

**Issue by marcpascual** [Azure/AKS#1520]
**What happened**: we already built a handful AKS clusters, and we constantly find ourselves rebuilding these clusters whenever there is a new feature or enhancement released

**What you expected to happen**: a supported, _no rebuild required_ migration path from using service principals to managed identity

**Comment by zhiweiv** [comment]
We have same problem, it is painful to rebuild a bunch of existing clusters.

**Comment by djsly** [comment]
Looking forward this to be available!

**Comment by MCKLMT** [comment]
@palma21 Any idea on the GA timeframe?

**Comment by ganrad** [comment]
Same question here.  Can we get a tentative timeframe for when this feature will be GA'ed ? One of our big AKS customers has been waiting on this feature for a while.  Appreciate your inputs.  Thanks.
