### ISSUE TITLE
LoadBalancer are very slow to be up and running ?

### ISSUE THREAD

**Issue by nsteinmetz** [Azure/AKS#1521]
**What happened**:

We spawn a cluster with terraform using 1.44 version of azurerm provider. We then deploy our product in the cluster trhough the use of helm charts. One chart will create a LoadBalancer but it takes between 10 to 20 mn to be up  and running. So our helm chat with a 900s timeout (which works fine on EKS or GKE) fails to be deployed on AKS.

Is there a reason why the loadbalancer is so long to be created ?

If we let the IP come and nginx-ingress-controller pods restart, then platform is up and running but it's out of time.

**What you expected to happen**:

Chart deployment should be deployed within 15mn with the load balancer based on `nginx-ingress` up and running.

**How to reproduce it (as minimally and precisely as possible)**:

* Create a cluster with terrraform using calico as network plugin
* Deploy some app
* Deploy a nginx-ingress controller which will create a LoadBalancer

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14
- Size of cluster : 3 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) : a bunch of all of this - we deploy a data platform :)
- Others: we also use external dns - could have external-dns annotation effects on LB ?

Could there be something on the Standard LB vs Basic LB side ? So far we used BLB.

**Comment by nsteinmetz** [comment]
Testing with new LB

```yaml
resource "azurerm_public_ip" "lb_public_ip" {
  name = "lb_public_ip"
  resource_group_name = var.resource_group_name
  location            = var.location
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_kubernetes_cluster" "k8s" {
  name                = local.cluster_name
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  dns_prefix          = local.dns_prefix
  kubernetes_version  = data.azurerm_kubernetes_service_versions.current.latest_version

  role_based_access_control {
    enabled = true
  }
  linux_profile {
    admin_username = "centos"
    ssh_key {
      key_data = local.ssh_public_key
    }
  }

  agent_pool_profile {
    name            = "agentpool"
    count           = local.agent_count
    vm_size         = local.vm_size
    os_type         = "Linux"
    os_disk_size_gb = 30
    vnet_subnet_id  = azurerm_subnet.aks.id
    max_pods        = 30
    #    storageProfile  = "ManagedDisks"
  }

  service_principal {
    client_id     = var.client_id
    client_secret = var.client_secret
  }

  network_profile {
    network_plugin     = "azure"
    service_cidr       = var.service_cidr
    dns_service_ip     = var.dns_service_ip
    docker_bridge_cidr = "172.17.0.1/16"
    network_policy     = "calico"
    load_balancer_sku  = "Standard"

    load_balancer_profile {
      outbound_ip_address_ids = [ "${azurerm_public_ip.lb_public_ip.id}" ]
    }
  }

  lifecycle {
    ignore_changes = [
      default_node_pool,
      agent_pool_profile
    ]
  }
  tags       = local.tags
  depends_on = [azurerm_private_dns_zone.private]
}
```

It just worked but I have 2 IPs attached to my LB. Need to pass the IP to my LB service declaration now.

**Comment by jluk** [comment]
This time to create an LB is not expected, but we know Standard SKU has better performance on nearly every benchmark. Were you able to move forward successfully on the latest TF deployment using SLB?

**Comment by nsteinmetz** [comment]
Yes I ended up with this:
* I set the LB to be a SLB
* I ask for an IP but I don't tie it with my LB
* For the nginx controler, I pass the `loadbalancer_ip = data.azurerm_public_ip.loadbalancer_public_ip.ip_address` to the template which managed the `vlaues.yml` file for the nginx ingress controller chart. As documented [here](https://docs.microsoft.com/en-us/azure/aks/static-ip).

It's much faster.

```yaml
resource "azurerm_public_ip" "lb_public_ip" {
  name = "${local.cluster_name}_lb_public_ip"
  resource_group_name = azurerm_resource_group.main.name
  location            = var.location
  allocation_method   = "Static"
  sku                 = "Standard"
  depends_on = [azurerm_resource_group.main]
}

data "azurerm_public_ip" "loadbalancer_public_ip" {
  name                = azurerm_public_ip.lb_public_ip.name
  resource_group_name = azurerm_resource_group.main.name
  depends_on = [azurerm_public_ip.lb_public_ip]
}

resource "azurerm_kubernetes_cluster" "k8s" {
  name                = local.cluster_name
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  dns_prefix          = local.dns_prefix
  kubernetes_version  = data.azurerm_kubernetes_service_versions.current.latest_version

  role_based_access_control {
    enabled = true
  }
  linux_profile {
    admin_username = "centos"
    ssh_key {
      key_data = local.ssh_public_key
    }
  }

  agent_pool_profile {
    name            = "agentpool"
    count           = local.agent_count
    vm_size         = local.vm_size
    os_type         = "Linux"
    os_disk_size_gb = 30
    vnet_subnet_id  = azurerm_subnet.aks.id
    max_pods        = 30
  }

  service_principal {
    client_id     = var.client_id
    client_secret = var.client_secret
  }

  network_profile {
    network_plugin     = "azure"
    service_cidr       = var.service_cidr
    dns_service_ip     = var.dns_service_ip
    docker_bridge_cidr = "172.17.0.1/16"
    network_policy     = "calico"
    load_balancer_sku  = "Standard"
  }

  lifecycle {
    ignore_changes = [
      default_node_pool,
      agent_pool_profile
    ]
  }

  tags       = local.tags
  depends_on = [azurerm_private_dns_zone.private]
}```
