### ISSUE TITLE
Pods has limited access to the internet when api server authorized ip ranges is enabled

### ISSUE THREAD

**Issue by piostelmach** [Azure/AKS#1522]
Few days ago I enabled authorized ip ranges (https://docs.microsoft.com/en-US/azure/aks/api-server-authorized-ip-ranges). 
After this, my pods running on virtual node inside AKS has limited access to the internet. 
For example apt-get update inside container return error:
**apt-get update
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 https://packages.microsoft.com/repos/azure-cli bionic InRelease
  Temporary failure resolving 'packages.microsoft.com'
Err:3 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Temporary failure resolving 'security.ubuntu.com'**

When I turn off authorized ip ranges, pods has access to the internet...

Do you know how resolve this problem ?

AKS ver. 1.15.5
SR 120031822000914

**Comment by palma21** [comment]
@MikkelHegn @macolso

**Comment by MikkelHegn** [comment]
There is currently a requirement for ACI hosted pods to have access to the API server for configuring it's proxy with service IPs. You probably do have Internet connectivity, not just DNS as CoreDNS is behind a service, which the proxy needs to configure the route to.

**Comment by MikkelHegn** [comment]
Will update docs with this requirement and limitation on authorized ip ranges.

**Comment by MikkelHegn** [comment]
Doc update is in-flight in a private repo...
