### ISSUE TITLE
AKS and Private Link Resource Not Supported

### ISSUE THREAD

**Issue by derek-andrews-work** [Azure/AKS#1523]
**What happened**:

Setup a private AKS cluster in North Central.
Went to setup a private link endpoint to attach to the cluster as that preview is supposed to be available.
Get to the point to pick a resource, and i am able to pick my cluster, but get a red error saying resource not supported.

**What you expected to happen**:

Private link should attach to the cluster and get me an ip address on the vnet of my choosing.

**How to reproduce it (as minimally and precisely as possible)**:

Build AKS cluster in North Central.
Create private link endpoint to that AKS cluster.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.16.7, although unable to connect as i need a private link
- Size of cluster (how many worker nodes are in the cluster?)
3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
N/A
- Others:
N/A

**Comment by lgmorand** [comment]
you try to a create a brand new cluster with the **--enable-private-cluster**  parameter or you try to add PLS to an **existing** "standard" cluster ? 

https://docs.microsoft.com/en-us/azure/aks/private-clusters#limitations

**Comment by derek-andrews-work** [comment]
This is creating through the UI.  I do choose private cluster when creating.  I then try to create a private link endpoint to Microsoft.ContainerService/managedClusters.  It sees my cluster in the drop down, but when I pick it, it says resource not supported.

Derek Andrews
Assistant Vice President  | Cloud Platform Solutions
Azure Product Owner
p. 414.243.1620 | derek.andrews@usbank.com<mailto:derek.andrews@usbank.com>

**Comment by lgmorand** [comment]
but if you created a private cluster, you already have private endpoint called kube-apiserver, which is present in the adjoined resource-group (MC_blablabla). Why to you want to create a new one ?

**Comment by derek-andrews-work** [comment]
My goal was to have an AKS cluster with a private endpoint on our vnet connected to our express route. 

I thought this worked a different way, but i see what you are saying now.  I thought this worked like other services (say sql), where i would stand that up, then attach an endpoint on the network of my choosing.   So i had hoped i could dedicate a random vnet to aks, then use an endpoint on another vnet.  But it looks like i may need to peer the aks vnet if i want to use a private endpoint.

Thanks!.  closing.

**Comment by lgmorand** [comment]
"But it looks like i may need to peer the aks vnet if i want to use a private endpoint." yes and if you delete this endpoint, pouf, your cluster is dead :)

I MAY say stupid things (I'm and end-user like you) but AKS does not work exactly like the other services but it use the same private link service underlying. The fact that, for now, it has to be specified (private or not) at the creation time, is because this way, at no moment, the public endpoint is created. When you had PLS to a service, it had a private IP but I'm not sure it removes the public one. in the case of AKS, since we want not to expose the api server at all, then it is done at the creation time.

**Comment by ashishvermapu** [comment]
I dont know why this was closed. it doesn't need vnet peering and should work the way you were expecting it to.
