### ISSUE TITLE
Cannot access Dashboard with AAD cluster user

### ISSUE THREAD

**Issue by samrobillard** [Azure/AKS#1525]
**What happened**:
I have a AKS cluster with AAD login enabled. When running az aks browse, I get the following error when selecting my Kube config file:

Internal error (500): Not enough data to create auth info structure

I f I run az aks get-credentials with --admin, I can access the dashboard without any problem.

**What you expected to happen**:
I would expect to open the dashboard with minimum permissions as described in the role kubernetes-dashboard-minimal

**How to reproduce it (as minimally and precisely as possible)**:
Deploy AKS cluster with AAD
az aks get-crendetials and sign-in using AAD account
Run az aks browse
Select your kube config file

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.7
- Size of cluster (how many worker nodes are in the cluster?) 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) No workload at the moment
- Others:

**Comment by rgrwatson85** [comment]
Have you tried doing token authentication by using `az account get-access-token`?

**Comment by samrobillard** [comment]
I re-created my cluster and I don't have to login to the Kubernetes dashboard after running az aks browse and logging in with the device code and my AAD account. I'll keep your command in mind, thank you.
