### ISSUE TITLE
AKS DNS response contains OPT record with data

### ISSUE THREAD

**Issue by t-bzhan** [Azure/AKS#1526]
**What happened**:
It seems that AKS has changed the DNS response format recently, its response will include an OPT record with some arbitrary data sometimes.

![image](https://user-images.githubusercontent.com/61817681/77649792-5e43a580-6fa5-11ea-9f69-66970816d915.png)

![image](https://user-images.githubusercontent.com/61817681/77649858-7e736480-6fa5-11ea-9d82-1dcb37bee82c.png)

I am not sure whether this is a common practice to return OPT record with data in it. We use DnsClient.NET 1.2.0 in AKS, however the library did not handle the case that an OPT record with data  in it and that will cause DNS failure with the recent DNS response format change in AKS. I noticed that some people has the same issues as me. I open this issue mainly to figure out whether this is by design or by configuration error.

You can view more details at these issues:
https://github.com/MichaCo/DnsClient.NET/issues/55
https://github.com/MichaCo/DnsClient.NET/issues/51

**What you expected to happen**:
I am not setting a standard here, but I use to see the result looks like below:
![image](https://user-images.githubusercontent.com/61817681/77650136-f9d51600-6fa5-11ea-8b0f-aca94b251f03.png)

**How to reproduce it (as minimally and precisely as possible)**:
Just run dig command in any container.

**Anything else we need to know?**:
Coredns image version: mcr.azk8s.cn/oss/kubernetes/coredns:1.2.6

**Environment**:
- Kubernetes version (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}

> Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)

> 6

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

> HTTP microservices

- Others:

**Comment by palma21** [comment]
We didn't change anything in that regard, so my recommendations would be to open a support ticket so we can investigate further your cases
