### ISSUE TITLE
item not marked as GA

### ISSUE THREAD

**Issue by porrascarlos802018** [Azure/AKS#1527]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

customer reading this article and mentions,  POD identity is not marked GA. Isnt it GA?
https://github.com/Azure/AKS/blob/master/previews.md#aad-pod-identity

**Comment by tomkerkhove** [comment]
Nope, not yet

**Comment by jluk** [comment]
Pod identity is an associated project, the capability to use it as a managed feature in AKS has yet to preview. You can track the preview status at #1480 .

We will clarify the previews.md document as it is misleading.
