### ISSUE TITLE
kube-svc-redirect CrashLoopBackOff in West Europe

### ISSUE THREAD

**Issue by ondrad1** [Azure/AKS#153]
Today I've created new AKS cluster in WestEU

`kubectl get pods --all-namespaces` gives me:

```NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE
kube-system   heapster-847468cccf-bds67               2/2       Running            0          7m
kube-system   kube-dns-v20-7d697d6c4d-gcs9r           3/3       Running            0          7m
kube-system   kube-dns-v20-7d697d6c4d-z6s6z           3/3       Running            0          7m
kube-system   kube-proxy-4g9qx                        1/1       Running            0          13m
kube-system   kube-proxy-hsqgf                        1/1       Running            0          7m
kube-system   kube-svc-redirect-277qz                 0/1       CrashLoopBackOff   6          7m
kube-system   kube-svc-redirect-z5nj7                 0/1       CrashLoopBackOff   7          13m
kube-system   kubernetes-dashboard-6d9c57c89c-qhpkf   0/1       CrashLoopBackOff   6          13m
kube-system   tunnelfront-844557dd8f-rnbhj            1/1       Running            0          13m
```
`kubectl get node -o wide` gives me:
```
NAME                       STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                      KERNEL-VERSION      CONTAINER-RUNTIME
aks-agentpool-74974926-0   Ready     agent     6m        v1.8.6    <none>        Debian GNU/Linux 8 (jessie)   4.11.0-1016-azure   docker://1.12.6
aks-agentpool-74974926-2   Ready     agent     12m       v1.8.6    <none>        Debian GNU/Linux 8 (jessie)   4.11.0-1016-azure   docker://1.12.6
```

The result is, that the UI is not accessible. 
```
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
error: error upgrading connection: error dialing backend: dial tcp 10.240.0.6:10250: getsockopt: connection timed out
```

Maybe same issues as in #2 and/or #56 .

**Comment by anders-aberg** [comment]
We have the same problem. We first had the problem described in https://github.com/Azure/AKS/issues/152 
So i created a new cluster and it has the problems described in this issue.

**Comment by srudenko** [comment]
The same issue in West Europe region.  I have created 3 clusters in 3 different resource groups and all experience the same issue.

`NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE
kube-system   heapster-847468cccf-424nn               2/2       Running            0          6m
kube-system   kube-dns-v20-7d697d6c4d-4l6hc           3/3       Running            0          6m
kube-system   kube-dns-v20-7d697d6c4d-kwl86           3/3       Running            0          6m
kube-system   kube-proxy-kvxlk                        1/1       Running            0          6m
kube-system   kube-svc-redirect-lwgkt                 0/1       CrashLoopBackOff   6          6m
kube-system   kubernetes-dashboard-5f766f7944-r8rzj   0/1       Error              5          6m
kube-system   tunnelfront-6dc687f66f-pc8rf            1/1       Running            0          6m`

**Comment by neumanndaniel** [comment]
Same for me. It does not matter, if you deploy a new AKS cluster with version 1.7.7 or 1.8.1.

**Comment by brendandburns** [comment]
We are hitting some issues related to capacity in West Europe. We are working to resolve. In the meantime, EastUS and CentralUS should be working correctly.

Apologies!

**Comment by brendandburns** [comment]
This was mitigated around noon (Pacific) yesterday.

**Comment by danielcoman** [comment]
Hi @brendandburns just created a 3 node cluster and the issue is present in West Europe.

**Comment by thecoolpix** [comment]
Hi, is there any progress on this? @brendandburns  wrote it was mitigated, but i created aks cluster in west europe today and the vary same error occured.

**Comment by amanohar** [comment]
@thecoolpix @danielcoman can you share your resource group and resource name and I will look into it,

**Comment by thecoolpix** [comment]
@amanohar Hi, i cant provide names of these resources, but i can confirm it magically start working again without any changes from my side.

**Comment by vsamidurai** [comment]
I'm facing same in issue North Europe

**Comment by Mumrau** [comment]
No update on this? 
This is not the first time I'm having issues getting a proper working cluster.

The most annoying is the azureproxy being down since it looks like it is one of the uttermost importance.
If anyone knows the real purpose of this component, I would be interested into it.
