### ISSUE TITLE
Dns issues "connection timed out; no servers could be reached"

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/AKS#1535]
**What happened**: 
I wanted to test some network policies to restrict traffic within its own namespace. Before I applied the networkpolicies I tried to reach services in the same and other namespaces but ran into some resolving issues. So here some troubleshooting from within a pod in the default namespace.

```
dig kubernetes.default.svc.cluster.local
;; global options: +cmd
;; connection timed out; no servers could be reached
```

This most of the times fails, just once in a while. Specifying the nameserver (dig kube-dns.kube-system.svc.cluster.local @172.20.0.10) doesn't help. 
Same issue for trying to reach other services in other namespaces.

Also going outside the cluster is giving issues:
```
dig google.com
; <<>> DiG 9.11.5-P4-5.1-Debian <<>> google.com
;; global options: +cmd
;; connection timed out; no servers could be reached
```
When I specify one of the vnet custom dns servers it works fine:
```
dig google.com @10.232.1.4
; <<>> DiG 9.11.5-P4-5.1-Debian <<>> google.com @10.232.1.4
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38701
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;google.com.			IN	A
;; ANSWER SECTION:
google.com.		170	IN	A	216.58.208.110
;; Query time: 0 msec
;; SERVER: 10.232.1.4#53(10.232.1.4)
;; WHEN: Tue Mar 31 11:37:41 UTC 2020
;; MSG SIZE  rcvd: 55
```
Further more I found out that a pod can ping another pod when it is on the same node, but it times out when the pod is on a different node.

**What you expected to happen**: For resolving to work correctly
I deployed an AKS cluster which is using an existing vnet/subnet. The vnet has custom dns servers due to connection to on premise stuff. 

**How to reproduce it (as minimally and precisely as possible)**:
Deploy an AKS cluster with k8s version 1.16.7 (See config below)
Deploy a pod in the default namespace and try to connect to services or pods

**Anything else we need to know?**: We have cluster with the same networking configuration on the same vnet (only a different subnet) but works fine.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"20c697423de11d4d5d08c6832a513217ca11a6aa", GitTreeState:"clean", BuildDate:"2020-02-21T10:47:45Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?)
`3 nodes`

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
I only deployed 3 nginx pods (one on each node) and exposed all of them via a service

- Others:
Some terraform config which was used to create the cluster:

```
  default_node_pool {
    name                = "${var.node_pool_name}"
    node_count          = "${var.node_count}"
    min_count           = "${var.min_node_count}"
    max_count           = "${var.max_node_count}"
    vm_size             = "Standard_DS3_v2"
    type                = "VirtualMachineScaleSets"
    enable_auto_scaling = true
    vnet_subnet_id      = "${var.subnet}"
    os_disk_size_gb     = 100
  }

  network_profile {
    network_plugin     = "kubenet"
    network_policy     = "calico"
    load_balancer_sku  = "basic"
    pod_cidr           = "172.19.0.0/16"
    docker_bridge_cidr = "172.18.0.1/16"
    dns_service_ip     = "172.20.0.10"
    service_cidr       = "172.20.0.0/16"
  }
```

**Comment by sbugalski** [comment]
Hi,

At first please follow the Troubleshooting guide, https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by sbugalski** [comment]
Also you should try to deploy cluster with Azure CNI Network plugin, https://docs.microsoft.com/en-us/azure/aks/configure-kubenet

**Comment by bramvdklinkenberg** [comment]
Hi @sbugalski , the issue were some missing route-table rules.
