### ISSUE TITLE
azurefile and azurefile-premium storage classes appear after cluster creation

### ISSUE THREAD

**Issue by aleksandrshvets** [Azure/AKS#1536]
Starting from today there are two new storage classes added on new cluster by default: azurefile and azurefile-premium. It breaks our current setup because we have custom storage class with the same name.  There is no related documentation or release notes. Can someone confirm or deny that it is a new feature? If yes, is it possible to see link on commit?

**Steps:**
1. run aks create with default parameters
2. run kubectl get sc

**Result:**
azurefile           kubernetes.io/azure-file   6m52s
azurefile-premium   kubernetes.io/azure-file   6m52s
default (default)   kubernetes.io/azure-disk   6m52s
managed-premium     kubernetes.io/azure-disk   6m52s

**Expected result:**
default (default)   kubernetes.io/azure-disk   6m52s
managed-premium     kubernetes.io/azure-disk   6m52s

Kubernetes version: 1.15.7

**Comment by tomasr** [comment]
Well, that's going to break our setup as well, for sure. Fun.

**Comment by dancronintix** [comment]
This has also happened across all our clusters and broke some of our backup functionality. 

What is the purpose of these new disks?
Are there any updates to storage classes occurring?
Are you introducing new default class to clusters?

These classes seem to have overwritten existing classes which had mount path specified. This has overridden any previous custom storage classes. We had a storage class named azurefile, because at the time this wasn't used. Is this now used?

**Comment by ntesteca** [comment]
At least, it would be great if the online documentation reflect this change: https://docs.microsoft.com/en-us/azure/aks/concepts-storage#storage-classes because it still only mentions the original two default ones.

**Comment by CptQuint** [comment]
Is there any update on this? Is there a way to leverage these new classes or should I simply be renaming my bespoke 'azurefile' storage class?

**Comment by andyzhangx** [comment]
there are new storage classes updated in prior releases, pls rename your original storage class `azurefile`, `azurefile-premium` if your classes are different, thanks.

**Comment by andyzhangx** [comment]
> At least, it would be great if the online documentation reflects this change: https://docs.microsoft.com/en-us/azure/aks/concepts-storage#storage-classes because it still only mentions the original two default ones.

thanks for reminder, I will update the doc.
