### ISSUE TITLE
AKS support nodeLabels set to empty values

### ISSUE THREAD

**Issue by tomcooperca** [Azure/AKS#1538]
Related to #1088 

**What happened**:
* deployment of an AKS cluster is rejected with a `BadRequest` error due to nodeLabels with an optional prefix

```
{"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'example-rg-1_aks_deployment' is not valid according to the validation procedure. The tracking id is '5f2e1339-8c21-4c94-9607-05edcb09d0c3'. See inner errors for details.","details":[{"code":"BadRequest","message":"Provisioning of resource(s) for container service example-aks-1 in resource group example-rg-1 failed. Message: {\n  \"code\": \"BadRequest\",\n  \"message\": \"Node label 'example.company.com/label-name: ' does not meet syntax and character specifications. Please see https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/ for more details.\"\n }. Details: "}]}}
```

From the [Kubernetes label syntax documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set):

> Valid label keys have two segments: an optional prefix and name, separated by a slash (/). The name segment is required and must be 63 characters or less, beginning and ending with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between. The prefix is optional. If specified, the prefix must be a DNS subdomain: a series of DNS labels separated by dots (.), not longer than 253 characters in total, followed by a slash (/).

**What you expected to happen**:
* deployment of AKS clusters with nodeLabels set with an optional prefix for label names proceeds without errors

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy an AKS cluster via ARM
2. Set the `nodeLabels` field under the `agentPoolProfiles`. For the label name, include an optional organizational prefix (such as `example.company.com/label-name`).

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- Size of cluster (how many worker nodes are in the cluster?) N/A
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) N/A
- Others:

**Comment by bhicks329** [comment]
Are you missing the value for the label? 

Instead of `example.company.com/label-name: `  shouldn't it be `example.company.com/label-name: label-value`

**Comment by tomcooperca** [comment]
The ARM template used to deploy this cluster had the node label values filled in, derived from tags on the resource group:

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": { "..."  },
    "variables": {
        "labels": {
            "example.company.com/LabelOne": "[resourceGroup().tags.One]",
            "example.company.com/LabelTwo": "[resourceGroup().tags.Two]",
            "example.company.com/LabelThree": "[resourceGroup().tags.Three]"
        }
    },
    "resources": [
        {
            "name": "string",
            "type": "Microsoft.ContainerService/managedClusters",
            "apiVersion": "2020-02-01",
            "location": "string",
            "tags": "[resourceGroup().tags]",
            "properties": {
                "kubernetesVersion": "string",
                "dnsPrefix": "string",
                "agentPoolProfiles": [
                    {
                        "...",
                        "tags": "[resourceGroup().tags]",
                        "nodeLabels": "[variables('labels')]",
                        "..."
```

**Comment by jluk** [comment]
Thanks for the discussion, it looks like an empty value is indeed not supported by AKS at the moment and the ask to match the upstream support makes sense.

To be clear though @tomcooperca, these labels for each pool are not mutable and can only be set at pool creation time. Is your end state to have an empty label value for these nodes?

**Comment by tomcooperca** [comment]
Correct, for only one of the labels we are attempting to set, a valid value for us is an empty string. As a workaround, we’ll put in an actual value (such as `”none”`) for that particular business label. Thanks!
