### ISSUE TITLE
AKS API server has wrong certificate SAN's

### ISSUE THREAD

**Issue by andriktr** [Azure/AKS#1540]
Hi,
We have an issue with AKS apiserver certificate. This certificate has X509v3 Subject Alternative Names:

```
  DNS:localhost,  
  DNS:hcp-kubernetes, 
  DNS:kubernetes, 
  DNS:kubernetes.default, 
  DNS:kubernetes.default.svc, 
  DNS:kubernetes.default.svc.cluster.local, 
  DNS:hcp-kubernetes.someuniquevalue.svc.cluster.local, 
  DNS:somouniquevalue1.hcp.westeurope.azmk8s.io, 
  IP Address:192.168.0.2
```
All records are OK except the last one "IP Address:192.168.0.2" normally here should be internal kubernetes service cluster IP address which is our case is 192.168.0.1.

Due to this some pod like nginx ingress controller are crashing with appropriate log message:
`Unexpected error discovering Kubernetes version (attempt 6): Get https://192.168.0.1:443/version?timeout=32s: x509: certificate is valid for 192.168.0.2, not 192.168.0.1`
We have tried to run a certificate rotation procedure however new certificate was also issued with wrong SAN IP address.

Is it save to change the kubernetes service ip address to 192.168.0.2 and or we can fix it in some other way that seems to be tricky due to no access to the API server
Thank you.

**Comment by djsly** [comment]
@andriktr  I wouldn't recommend to to change the IP of the service, it would most probably get reverted back by any operation done on the AKS resource. 

I think that you should most probably need to open a support request with MSFT and have them look at the root cause as to why the certificate doesn't have the expected `192.168.0.1` IP. 

I look at all my clusters and they all have 192.168.0.1...

**Comment by andriktr** [comment]
When you setup aks cluster you define a network cidr which will be used for internal k8s services. We have other clusters where this default kubernetes service has different ip. Actually this is normal k8s service (service type clusterip, but without selector with mapped endpoint where api server’s external ip address is defined). Main question of course is why this wrong ip appeared in the API server and how to fix ot without cluster rebuild. As access to api server is not allowed the only option I see is change service ip with kubectl edit.

**Comment by palma21** [comment]
As @djsly recommended, they way to do that is via a support ticket. We can look into your cluster to see what's different and apply any needed fixes if necessary. 

I'll close this ticket for now
