### ISSUE TITLE
Grant access to resources using Managed Identity before cluster creation

### ISSUE THREAD

**Issue by adhodgson1** [Azure/AKS#1542]
Given a cluster where we generate a long-lived PIP outside the managed cluster resource group to provide stable egress endpoints, how will we grant the managed identity the necessary privileges on the PIP before the cluster is created? We currently generate an SPN, then grant that use on the PIP resource before creating the cluster.

**Comment by andyzhangx** [comment]
cc @norshtein

**Comment by jluk** [comment]
This should be captured by the related issue 1591 above, closing this as a result please send feedback into that issue.
