### ISSUE TITLE
Periodic issues changing Authorized API Server IP address list

### ISSUE THREAD

**Issue by adhodgson1** [Azure/AKS#1543]
We have seen a couple of issues with updating the API server authorized ranges using the Azure CLI. We use the command similar to:

```
az aks update -n <cluster> -g <cluster-rg> --api-server-authorized-ip-ranges <ranges>
```

Where ranges is the full list of ranges we want to be used in this field, including the outbound PIP of the standard load balancer provisioned with AKS (using bring your own PIP).

Issue1: The update takes affect and when we run az aks show it shows us the correct IP addresses, but additions to the list don't take affect for at least a couple of hours. These do get added though to the firewall eventually and service resumes as usual.

Issue 2: The update takes affect without errors but we are unable to see the additions using az aks show and the IPs are not able to connect to the cluster of course. When I have seen this I have waited a couple of hours but the IPs don't show up until I run the command again. In one reported incident the user wasn't able to add these ranges until he re-ordered them in the list.

When changes are made to this field what is the expected timeframe to be able to connect to the cluster from the new IPs?

**Comment by palma21** [comment]
As per the doc the time the rules take to be applied can take up to 3 minutes. Several hours is not expected, nor is the second issue. 

Could you open a support ticket so we may take a look at your cluster?
