### ISSUE TITLE
kubectl logs getting timeout error (dial tcp 10.119.149.66:10250: i/o timeout)

### ISSUE THREAD

**Issue by ravikrddy** [Azure/AKS#1544]
**What happened**: kubectl logs getting timeout

**What you expected to happen**: kubectl logs should gives logs as output

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.7
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) HTTP microservices
- Others:

**Comment by andriktr** [comment]
Hi,
Seems that error comes from node kubelet API  are all your worker nodes in ready status?

**Comment by dragonfly91** [comment]
I'm also facing this error. Any updates on this?

**Comment by palma21** [comment]
Please see: 
https://docs.microsoft.com/en-us/azure/aks/troubleshooting#im-receiving-tcp-timeouts-such-as-dial-tcp-node_ip10250-io-timeout

and

https://docs.microsoft.com/en-us/azure/aks/troubleshooting#im-receiving-tcp-timeouts-when-using-kubectl-or-other-third-party-tools-connecting-to-the-api-server


Those errors means required communications paths are being blocked.

Either node to node communication or node to API communication.

Those links should help you fix it.
