### ISSUE TITLE
[Feature request] AKS API supports to add/update the windows profile on existing cluster

### ISSUE THREAD

**Issue by Shuanglu** [Azure/AKS#1545]
AKS has nodepools feature enabled and it would be great that the AKS can enable API to add/update  windows profile(windows username/credential). This can avoid creating new cluster when there is windows container business requirements

**Comment by MikkelHegn** [comment]
FYI - All new clusters will have a profile today, also if not added by the user at cluster creation time.

**Comment by cpunella** [comment]
@MikkelHegn  Do you know if would be feasible for existing cluster too? we have different clusters up & running, and would be great be able to use windows node there, without recreating it.

**Comment by MikkelHegn** [comment]
@cpunella - this is currently not possible.

**Comment by cpunella** [comment]
Hi there, any news about it?

**Comment by AbelHu** [comment]
All AKS clusters created after May, 2020 should have WindowsProfile by default if network-plugin is set to azure,  load-balancer-sku is set to standard and vm-set-type is set to VirtualMachineScaleSets  in creating the cluster.

**Comment by Krupakarreddin** [comment]
@mikkelhegn This wasnt mentioned in any of the announcements in the Microsoft docs. & moreover its like if the AKS clusters were created before May 2020, its our bad luck?

**Comment by AbelHu** [comment]
@justindavies is AKS Windows PM. I think that it can be added to the roadmap.

**Comment by Krupakarreddin** [comment]
@AbelHu Any  updates here

**Comment by AbelHu** [comment]
@Krupakarreddin How many clusters do you have? Maybe you can file a support ticket so we can help you to add WindowsProfile in your clusters manually as a workaround. You cluster must meet the requirement.
1. network-plugin is set to azure
2. load-balancer-sku is set to standard
3. vm-set-type is set to VirtualMachineScaleSets

**Comment by Krupakarreddin** [comment]
@AbelHu  ThanQ very much. We have around 26 clusters and we meet all the requirements that were mentioned.

**Comment by Krupakarreddin** [comment]
@AbelHu  re-opened the ticket 2203280030002723 for this issue.

**Comment by AbelHu** [comment]
Update: We will add missing WindowsProfile for all old clusters which can support Windows and it will be ready soon.

**Comment by JustLeo** [comment]
Still no updates?

**Comment by AbelHu** [comment]
@JustLeo I think that we can close this task since last year we have backfilled the missing WindowsProfile for all existing clusters without WindowsProfile but supporting Windows agent pools.

**Comment by JustLeo** [comment]
but still not able to edit "adminUsername": "azureuser" from Windows profile without recreating the cluster. 
The option/flag --windows-admin-username is only available when doing "az aks create" but not for "az aks update" commands.

**Comment by AbelHu** [comment]
> but still not able to edit "adminUsername": "azureuser" from Windows profile without recreating the cluster. The option/flag --windows-admin-username is only available when doing "az aks create" but not for "az aks update" commands.

Please file a new feature request for this requirement and assign it to @allyford
