### ISSUE TITLE
Nginx ingress controller annotations are not being applied

### ISSUE THREAD

**Issue by venture27** [Azure/AKS#1546]
**What happened**: Problem when creating an ingress, any annotations in yaml are not applied to .conf in nginx pod. This has been causing problems with whitelisting and now rewriting paths.

Nginx Ingress is installed via helm

`helm install myingress nginx-stable/nginx-ingress `
	--namespace mynamespace `
	--set controller.replicaCount=1 `
	--set controller.nodeSelector."beta\.kubernetes\.io/os"=linux `
	--set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux `
	--set controller.ingressClass=myingress_nginx `
	--set rbac.create=true `
	--set controller.scope.enabled=true `
	--set controller.scope.namespace=mynamespace `
	--set controller.publishService.enabled=true `
	--set controller.service.externalTrafficPolicy="Local"
`

I then apply a manifest to create my ingress.

`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress-proxy-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: myingress_nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/whitelist-source-range: X.X.X.X/32
spec:
  tls:
  - hosts:
    - somedomain.com
    secretName: ie-ignite-tls
  rules:
  - host: somedomain.com
    http:
      paths:
      - backend:
          serviceName: event-api
          servicePort: 80
        path: /bus(/|$)(.*)`

Before I applied the rewrite target and "bus" path, it all worked fine using "path: /" but now I need to specify a certain route.

I have logged into my nginx pod to read the .conf files and the annotations are not being applied in any. Neither the whitelisting or rewriting.

If I alter the global nginx configmap and use a server-snippet it does work and writes the specified snippet into the .conf. Nothing seems to be applied via manifest nginx annotations.

**What you expected to happen**:

I expect the myingress-proxy-nginx-ingress.conf file in the nginx pod to have the applied annotations for rewrite-target and whitelist-source-range.

**How to reproduce it (as minimally and precisely as possible)**:
Install nginx-ingress via helm into aks cluster.
apply ingress manifest with annotations and specific path to rewrite. Inspect nginx pod .conf files.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"150f36044fe31bee3891b5a3fae69c17237e022c", GitTreeState:"clean", BuildDate:"2020-02-21T10:02:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?) 1 linux node pool (2 nodes), 1 windows node pool (2 nodes)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
roughly 5 .net core microservices, 1 rabbitmq service.
- Others:
Helm version - version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

**Comment by alexeldeib** [comment]
You may want to open an issue in https://github.com/kubernetes/ingress-nginx or drop a message in their Slack, as this is not related to AKS.

I'd check the ingress controller logs at the time of configuration change for potential configuration errors.
