### ISSUE TITLE
Setting VMSS name through AKS Engine template

### ISSUE THREAD

**Issue by gball14** [Azure/AKS#1547]
We are trying to bring up many AKS clusters and in each AKS cluster we have an agentpool of type VirtualMachineScaleSets. Is there a way to pass prefix/suffix the VMSS name through AKS ARM template? We found agentPoolProfiles.name property but it ends up as a tag to the VMSS.

![Capture](https://user-images.githubusercontent.com/56672327/78713833-b648a900-78cf-11ea-956c-0d02936bce7c.GIF)

Ideally, I would like to create a VMSS name like below:

![Capture](https://user-images.githubusercontent.com/56672327/78714135-2fe09700-78d0-11ea-8a94-988c2a07a3d4.GIF)

**Comment by jluk** [comment]
@gball14 to my knowledge you cannot pass a custom prefix name to the VMSS in managed AKS, however you can set custom Azure tags on the VMSS resource managed by AKS.

What is your goal in making a prefixed name, if its for policy/auditing can you leverage the VMSS Azure tags instead?

**Comment by gball14** [comment]
I assume once we can set the prefix with cluster name (e.g. ch01), that prefix also propagates to the VM name. All our monitoring at the server side (for services running in k8s in these VMs) use machine name as instance e.g. CPU metrics. Having the cluster name as part of the machinename will help in identifying the clusters easily.

**Comment by jluk** [comment]
Giving the cluster name a prefix won't propagate it to underlying resources, if you have a reference mentioning that please share as that shouldn't be stated.

For VMSS associated to a cluster tracking, please use Azure tags as that metadata can easily be maintained/updated by you or custom policies you need enforced.

**Comment by gball14** [comment]
I looked at this more and aks-engine generates ARM template with the following property:

"windowspoolVMNamePrefix": "3409k8s00",

We are doing some patch operations on the ARM template (for other things) before doing "az deploy". Can I replace this property value to something like "ch01-3409k8s00"? Is this a safe operation?

I noted throughout the ARM template this variable is referenced to derive other properties. So, I feel this is a safe operation except two places where the value is used directly. 

    "primaryScaleSetName": "3409k8s00",
    "provisionScriptParametersCommon": "<other parameters> PRIMARY_SCALE_SET=3409k8s00 <other parameters>"

**Comment by gball14** [comment]
@jluk, did you get a chance to look at my previous response?

**Comment by jluk** [comment]
@gball14 to clarify for myself are you using aks-engine or aks today? 

@jackfrancis FYI on engine prefix naming

**Comment by jackfrancis** [comment]
In order to deal with reduced string size requirements for Windows VM names, aks-engine munges the name for Windows node pools, so tl;dr there's literally no way to get a meaningful node name for Windows nodes. :(

cc @marosset

**Comment by jluk** [comment]
Closing for now as we need information on if this is a direct engine deployment.
