### ISSUE TITLE
aks taints via az cli not reflecting taints properly.

### ISSUE THREAD

**Issue by ernani** [Azure/AKS#1548]
Weird thing here, I've added taints to another nodepool I've just added and it shows up as:

TLDR: Any reason why in my case it shows **foo=bar:Noschedule** and in the doc it shows up as **"foo": "bar:NoSchedule"**

```
az aks nodepool add \
    --resource-group foo \
    --cluster-name bar \
    --name footaint \
    --node-count 1 \
    --node-taints "foo=bar:NoSchedule"
```

But after creating it, the list shows as:

```
...
"nodeTaints": [
    "foo=bar:NoSchedule"
],
...
```

Where as in the doc linked here:
https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#specify-a-taint-label-or-tag-for-a-node-pool

It shows as:

```
...
"nodeTaints":  {
  "foo": "bar:NoSchedule"
},
...
```

_Originally posted by @ernani in https://github.com/Azure/AKS/issues/1402#issuecomment-610508724_

**Comment by zhiweiv** [comment]
It should be --node-taints foo=bar:NoSchedule?

**Comment by jluk** [comment]
@ernani this is a docs error, which we are getting resolved this week. 

thanks for flagging cc @mlearned
