### ISSUE TITLE
Support CIS 5.3.3

### ISSUE THREAD

**Issue by edernucci** [Azure/AKS#1549]
**What happened**:
I have some unmet security requirements.

**What you expected to happen**:
Constant merges from aks-engine to aks.

**How to reproduce it (as minimally and precisely as possible)**:
See https://github.com/Azure/aks-engine/issues/1018

**Comment by jluk** [comment]
This change will be available in the coming 2-3 weeks awaiting a global rollout.

**Comment by edernucci** [comment]
Thanks @jluk!

**Comment by jluk** [comment]
I believe this should be closed now and released globally. We can revisit if you do not see these changes.
