### ISSUE TITLE
Virtual Machine Extension Installation

### ISSUE THREAD

**Issue by darinhoward** [Azure/AKS#155]
Is there is a suggested means for installing (automatically) an Azure extension on a vm created through AKS? 

If this is not possible, is there a suggested way to  install software on a VM created through AKS?

**Comment by andyzhangx** [comment]
I would suggest use [hostpath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath)

**Comment by darinhoward** [comment]
@andyzhangx  can you expand on the hostpath idea?  

I see that it would allow me put files on the node via a pod/container - but the software install process would require a service setup and user account adjustments.  I don't think file system access alone will work.

**Comment by seanknox** [comment]
Closing due inactivity. Feel free to re-open if still an issue.
