### ISSUE TITLE
Does AKS 1.17 support startupProbe?

### ISSUE THREAD

**Issue by nirvanatao** [Azure/AKS#1550]
**What happened**:
 I created an AKS cluster v1.17.3 and deployed a Kafka cluster using bitnami kafka chart into the AKS cluster, I specified **startupProbe** in the Statefulset spec but seems AKS still trying to use the readiness probe to check whether the container is ready
I added the **startupProbe** to the  statefulset using **kubectl edit** and saved without any error and  then retrieved it using **kubectl get -o yaml**, but the **startupProbe** didn't appears in the returned yaml

**What you expected to happen**: When I specify **startupProbe** AKS should use startupProbe to  check whether the container is already startup

**How to reproduce it (as minimally and precisely as possible)**:
Create an AKS Cluster v1.17.3

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"13db51798ca68c34fddd26afb9cb27eab016e488", GitTreeState:"clean", BuildDate:"2020-02-21T11:07:44Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ridhoq** [comment]
I'm seeing the same behavior on 1.16.7

**Comment by Oldervoll** [comment]
Startup probes are in alpha, which means that they are not enabled by default. I can't find the documentation I read, but this is what I wrote about startup probes: 

> Startup probes are in alpha in Kubernetes 1.17, which means that the feature is not enabled by default. It's a bumpy road to enable it, so we found a workaround. When startup probes are enabled by default in Kubernetes (probably in 1.18), we should use startup probe in addition to the readiness probe.

**Comment by nirvanatao** [comment]
Startup probes not enabled in AKS 1.17 by default
