### ISSUE TITLE
AKS B2S with Standard Disk - stop cheating people

### ISSUE THREAD

**Issue by patsadow2** [Azure/AKS#1551]
Hello, 

I've saw a bunch of questions according to "How create standard b2s aks cluster with standard disk NOT PREMIUM people HATE paying for nothing when they just testing/dev.

So the question is is there anyone that can tell people how to do that, create instruction with working links "B2S AKS with Standard DISK!" . Stop just ping pong people they are yours client and stop iritating them. I've spent 3 weeks with cosultant that couldn't say what is the problem.... DRAMATIC

So maybe stop cheating and say "we love money and we dont support standard disk in the cheapest vms"

**Comment by andyzhangx** [comment]
2 core VM size is not suggested on AKS since aks components e.g. kubelet would cost a lot cpu, memory, that would make 2 core VMs very slow
