### ISSUE TITLE
Azure AD and AKS RBAC Built-in Roles Expected Behaviour

### ISSUE THREAD

**Issue by andyadamides** [Azure/AKS#1552]
According to the [documentation][1], *Azure Kubernetes Service Cluster User Role* allows access to Microsoft.ContainerService/managedClusters/listClusterUserCredential/action API call only.

My user is part of an AD group that has `Azure Kubernetes Service Cluster User Role` permissions on the AKS cluster and all the cluster role and cluster role bindings have been applied via `kubectl`. 

I can double check and verify that access to dashboard and permissions work with these steps:

```
 1. az login
 2. az aks get-credentials --resource-group rg --name aks
 3. kubectl proxy
 4. Open web connection
 5. Get prompt on terminal to login via device code flow
 6. Return to web connection on dashboard
 7. I can correctly verify that my permissions apply, 
 i.e. deleting a job does not work and this falls in line with my
    kubectl clusterrole bindings to the Azure AD group.
```

However when I try to use the `az aks browse` command to open the browser automatically like this, i.e. without `kubectl proxy`:

```
 1. az login
 2. az aks get-credentials --resource-group rg --name aks
 3. az aks browse --resource-grouprg --name aks
```

I keep getting the following error:

```
The client 'xxx' with object id 'yyyy' does not have authorization to perform action 
'Microsoft.ContainerService/managedClusters/read' over scope 
'/subscriptions/qqq/resourceGroups/rg/providers/Microsoft.ContainerService/managedClusters/aks' 
or the scope is invalid. If access was recently granted, please refresh your credentials.
```

A `dirty` solution was to apply `Reader` role on the AKS cluster for that AD group - then this issue goes away but why does `az aks browse` require `Microsoft.ContainerService/managedClusters/read` permission and why is that not included in `Azure Kubernetes Service Cluster User Role `? 

  [1]: https://docs.microsoft.com/bs-latn-ba/azure/aks/control-kubeconfig-access#available-cluster-roles-permissions

**Environment**:
- Kubernetes version : v1.15.10
- Size of cluster (how many worker nodes are in the cluster?) 5 nodes
- General description of workloads in the cluster : machine learning

**Comment by palma21** [comment]
Seems like a bug, @weinong @xizhamsft what do you think?

**Comment by weinong** [comment]
@palma21 I think the fix should be adding `Microsoft.ContainerService/managedClusters/read` to `Azure Kubernetes Service Cluster User Role` and `Azure Kubernetes Service Cluster Admin Role`

**Comment by palma21** [comment]
Agreed. Added the ask
