### ISSUE TITLE
[Docs] Update REST & ARM template reference for AKS API 2020-03-01

### ISSUE THREAD

**Issue by flamingboo** [Azure/AKS#1554]
Is there a plan to publish an update to the AKS API reference docs /ARM template to 2020-03-01 or 2020-04-01:

Current version: 2020-02-01

https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2020-02-01/managedclusters
Thanks

**Comment by jluk** [comment]
Thanks for raising @flamingboo yes we plan to update these in the coming week.

**Comment by jluk** [comment]
This has now been updated thanks for the feedback!
