### ISSUE TITLE
Cannot integrat ACR with AKS with --attach-acr

### ISSUE THREAD

**Issue by tezzigator** [Azure/AKS#1555]
Docs at https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration have the directions.  While logged in to latest Win10 (but linux does same thing) AZ CLI as the subscription owner, here is what's happening:
'''
C:>az aks update -n REDACTED-g test --attach-acr REDACTED
Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for ACR. Are you an Owner on this subscription?
'''
My AKS cluster is 1.16.7

**Comment by Pamir** [comment]
Hi @tezzigator 

Is manage identity enabled on your cluster.

Regards

**Comment by tezzigator** [comment]
Yes, it was created to use a system managed identity, not a service
principal

**Comment by mathieu-benoit** [comment]
@tezzigator, which Azure CLI version do you have? The `--attach-acr` feature seems to be implemented/fixed with the [2.3.1](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.3.1) version?

**Comment by tezzigator** [comment]
Im on the latest 2.3.1. cli
Also I tried simply adding the acrpull role to the akscluster for the scope of the registry itself, but apparently that isnt quite enough to get it working, kubectl describe pods shows
```
Failed to pull image "X/X:1.2": rpc error: code = Unknown desc = Error response from daemon: Get https://X/X/manifests/1.2: unauthorized: authentication required
```

**Comment by Pamir** [comment]
To solve your problem very quickly, you can combine imagePullSecret with serviceAccount
https://thorsten-hans.com/3-ways-to-integrate-acr-with-aks

For further investigation could you please share the information below

- Could you please share aks version, and features that enabled
- ACR features and properties.

**Comment by andyzhangx** [comment]
> Docs at https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration have the directions. While logged in to latest Win10 (but linux does same thing) AZ CLI as the subscription owner, here is what's happening:
> '''
> C:>az aks update -n REDACTED-g test --attach-acr REDACTED
> Waiting for AAD role to propagate[################################ ] 90.0000%Could not create a role assignment for ACR. Are you an Owner on this subscription?
> '''
> My AKS cluster is 1.16.7

the error said "Could not create a role assignment for ACR. Are you an Owner on this subscription?", pls make sure your subs has `Owner` role,  `Contributor` role won't work.

And after AKS set up, you could grant your ACR access to AKS node resource group manually in azure portal, that would also work.

**Comment by tezzigator** [comment]
I am doing this as owner of the subscription, so I believe this is problem of [#1349](https://github.com/Azure/AKS/issues/1349)

Here is the workaround which I can confirm works great:
`az role assignment create --assignee --scope --role acrpull`
where the scope is the resourceid of the ACR, and the assignee is the clientid of the kubelet's user assigned managed identity that was automatically created (referred to by in the portal by name of "<clustername>-agentpool" .  So do NOT use the MSI of the cluster. use that user managed identity "<clustername>-agentpool" that was automatically created.

And it did take about 10 mins for it to correctly propogate for me.
