### ISSUE TITLE
AKS with MSI does not assign permissions on custom vnet automatically

### ISSUE THREAD

**Issue by denniszielke** [Azure/AKS#1557]
Created an AKS cluster 1.16.7 with MSI using terraform and used an existing VNET using azure cni.
The VNET is in a different resource group.

The cluster itself seems fine but when trying to create  an internal load balancer 
kubectl apply -f https://raw.githubusercontent.com/denniszielke/container_demos/master/logging/dummy-logger/svc-int-logger.yaml
service/dummy-logger-int-lb created
I am seeing authentication issues that show that the system assigned managed identity does not have permissions on the network.

kubectl describe service/dummy-logger-int-lb
Name:                     dummy-logger-int-lb
Namespace:                default
Labels:                   <none>
Annotations:              service.beta.kubernetes.io/azure-load-balancer-internal: true
Selector:                 app=dummy-logger
Type:                     LoadBalancer
IP:                       10.2.0.107
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  31990/TCP
Endpoints:                
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     32084
Events:
  Type     Reason                  Age                 From                Message
  ----     ------                  ----                ----                -------
  Normal   EnsuringLoadBalancer    33s (x12 over 30m)  service-controller  Ensuring load balancer
  Warning  SyncLoadBalancerFailed  33s (x12 over 30m)  service-controller  Error syncing load balancer: failed to ensure load balancer: network.SubnetsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'SMSI_SERVICE_PRINCIPAL_ID' with object id 'SMSI_SERVICE_PRINCIPAL_ID' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/subnets/read' over scope '/subscriptions/SUBSCRIPTION_ID/resourceGroups/$VNET_GROUP/providers/Microsoft.Network/virtualNetworks/spoke1-kubevnet/subnets/aks-2-subnet' or the scope is invalid. If access was recently granted, please refresh your credentials."

Permissions had to be assigned manually after deployment.
SMSI_SERVICE_PRINCIPAL_ID=$(az aks show --resource-group $KUBE_GROUP --name $KUBE_NAME --query "identity.principalId" -o tsv )
az role assignment create --role "Contributor" --assignee $SMSI_SERVICE_PRINCIPAL_ID -g $VNET_GROUP

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.7

My expectation would be that AKS assigns the required permissions on the VNET automatically during deployment since I cannot expect deployment users to have owner permissions on the VNET to fix the permission afterwards.

**Comment by flamingboo** [comment]
Hit the same issue.
Catch 22 situation here!

**Comment by zhiweiv** [comment]
Same issue too.

**Comment by andriktr** [comment]
+1

**Comment by TomGeske** [comment]
Thanks for reporting. We will investigate and come back as soon as possible.

**Comment by TomGeske** [comment]
We have a section in our [docs ](https://docs.microsoft.com/en-us/azure/aks/use-managed-identity)mentioning this case: 

> _For creating and using your own VNet, static IP address, or attached Azure disk where the resources are outside of the MC_* resource group, use the PrincipalID of the cluster to perform a role assignment. For more information on role assignment, see Delegate access to other Azure resources._

If the custom vnet resides outside of MC_ resource group, you must manually grant needed permission to the system assigned identity associated with the cluster. That’s because AKS resource provider can’t grant any permission outside of MC_ resource group. 

I made PR to our docs to make this note more visible. Hope that helps to clarify.

**Comment by TomGeske** [comment]
I'm going ahead closing this one. Please comment if you think this issue remains unresolved.

**Comment by denniszielke** [comment]
The issue definitely unsolved. It does not seem right to me because it will create a block the deployment process because AKS deployment users have to reach out to their networking team to fix their newly created clusters. I assume more people will run into this when trying out MSI and I am hoping this will get fixed eventually in the product.

**Comment by flamingboo** [comment]
Agree with @denniszielke 
Our AKS is through a CI/CD pipeline and this is kind of a block. Previously with Service Principals, we would have them pre-created and perform the necessary role assignment in order for AKS cluster to  access resources with the right permissions. System-assigned managed identities are automatically created during AKS deployment (through ARM or Terraform), this means any permission adjustments have to be done AFTER cluster creation.
Maybe one solution would be have a user-assigned managed identity (which would be created beforehand) and use it in the AKS deployment.

**Comment by TomGeske** [comment]
We are working on improving this scenario.
- Short term we are working on enabling user assigned MI for cloud provider identity
- Mid-term we consider granting required network permissions similar to --attach-acr through cli and portal experience. 

Let me know what you think and if you have any further feedback.

**Comment by jsco2t** [comment]
@TomGeske 

For the fixes that you do implement - can we make sure solutions which require user action are documented for both `CLI` _and_ `ARM Template` deployment scenarios. 

Thanks!

**Comment by ramirezalfredo** [comment]
I was able to use the `CLI` to assign the Contributor Role to the vNet's Resource Group:
```
spID=$(az resource list -n <my-akscluster> --query [*].identity.principalId --out tsv)
az role assignment create --assignee $spID --role 'Contributor' --scope /subscriptions/<subscription-id>/resourceGroups/<vnet-resource-group>
```
Service type: LoadBalancer works after role assignment:
```
Events:
  Type    Reason                Age    From                Message
  ----    ------                ----   ----                -------
  Normal  EnsuringLoadBalancer  3m11s  service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   2m1s   service-controller  Ensured load balancer
```

**Comment by ams0** [comment]
FWIW, I bumped into this today. I use Terraform (code here: https://github.com/ams0/terraform-templates/blob/80ca9858b09ed44ebb9b23bf3cd866c8d788861d/appgw-wildcard-aks/modules/aks/main.tf#L38) to assign the `SystemAssigned` identity the `Network Contributor` role on the custom vnet (in another RG). The problem is the propagation time of the role: for every run one or both cluster have their `helm_release` resource fail (to install nginx-ingress with ILB); my fix is to either increase the [helm timeout](https://github.com/ams0/terraform-templates/blob/1203ff7d9996351c1e1a89daf52a15468a7a5188/appgw-wildcard-aks/modules/aks/ingress.tf#L36) or use `wait=false`. For example:

```
module.aks_c2.helm_release.nginx-ingress: Creation complete after 6m28s [id=nginx-ingress]
module.aks_c1.helm_release.nginx-ingress: Creation complete after 10m53s [id=nginx-ingress]
```

One cluster taking 4 more minutes to spin up the private IP.

**Comment by TomGeske** [comment]
@ams0 did you try bring your own user assigned: https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#bring-your-own-control-plane-mi-preview?

**Comment by ams0** [comment]
@TomGeske I specifically wanted to avoid creating/managing the identity with Terraform. After all, UserAssigned and SystemAssigned should be equivalent except for the lifecycle.

**Comment by TomGeske** [comment]
It's a chicken and egg problem. You need to assign permissions ahead of cluster creation to an identity that doesn't exist yet.

**Comment by crgarcia12** [comment]
Any news on this? :)

**Comment by flamingboo** [comment]
There is this in preview:
https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#bring-your-own-control-plane-mi-preview

**Comment by crgarcia12** [comment]
so still no solution for this but creating our own MI??

**Comment by 0dragosh** [comment]
Not stale, this is still an issue.

For my cluster with:

```hcl
  identity {
    type = "SystemAssigned"
  }
```

Granted role:

```hcl
resource "azurerm_role_assignment" "assignment" {
  principal_id         = azurerm_kubernetes_cluster.azurerm_kubernetes_cluster.identity[0].principal_id
  role_definition_name = "Network Contributor"
  scope                = "/subscriptions/<sub>/resourcegroups/<rg>/providers/Microsoft.Network/virtualNetworks/<vnet>/subnets/<subnet>"
}
```

The logs of the `aciconnectorlinux-*` pod in `kube-system` say:

```
level=fatal msg="error initializing provider azure: error setting up network profile: error while looking up subnet: api call to https://management.azure.com/subscriptions/<sub>/resourcegroups/<rg>/providers/Microsoft.Network/virtualNetworks/<vnet>/subnets/<subnet>?api-version=2018-08-01: got HTTP response status code 403 error code \"AuthorizationFailed\": The client '$obj_id' with object id '$obj_id' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/subnets/read' over scope '/subscriptions/<sub>/resourcegroups/<rg>/providers/Microsoft.Network/virtualNetworks/<vnet>/subnets/<subnet>' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

$obj_id in the logs of `aciconnectorlinux-*` **IS NOT THE SAME as the cluster** `principal_id`. So it seems I'm granting the role to the wrong service principal.

Even though my cluster has "SystemAssigned" identity, I can still see that ACI connector creates a new Azure AD application with id $obj_id and then tries to use that to read the subnet.

This is very very clearly a bug.

**Comment by matthieugi** [comment]
Hi @0dragosh, I agree with you. 

It is assigning the 'Network Contributor' role to the agentpool managed identity, and not the cluster one. 
I created the cluster through the portal on my side but still hitting the same issue.

`az role assignment list --scope /subscriptions/ea075562-77d6-4d3f-89a0-b6c6f4f339e0/resourcegroups/keolis/providers/Microsoft.Network/virtualNetworks/keolis/subnets/aks-subnet `

And here is the result is :

> [{
>     "canDelegate": null,
>     "condition": null,
>     "conditionVersion": null,
>     "description": null,
>     "id": "/subscriptions/ea075562-77d6-4d3f-89a0-b6c6f4f339e0/resourcegroups/keolis/providers/Microsoft.Network/virtualNetworks/keolis/subnets/aks-subnet/providers/Microsoft.Authorization/roleAssignments/4db9b096-c3ae-4c9b-8542-59336334023b",
>     "name": "4db9b096-c3ae-4c9b-8542-59336334023b",
>     "principalId": "0f3fa9b7-8ea1-4643-897f-840bbb3f43dc",
>     "principalName": "34e6f899-a819-44af-b77f-a0477c629bc3",
>     "principalType": "ServicePrincipal",
>     "resourceGroup": "keolis",
>     "roleDefinitionId": "/subscriptions/ea075562-77d6-4d3f-89a0-b6c6f4f339e0/providers/Microsoft.Authorization/roleDefinitions/4d97b98b-1d4f-4787-a291-c67834d212e7",
>     "roleDefinitionName": "Network Contributor",
>     "scope": "/subscriptions/ea075562-77d6-4d3f-89a0-b6c6f4f339e0/resourcegroups/keolis/providers/Microsoft.Network/virtualNetworks/keolis/subnets/aks-subnet",
>     "type": "Microsoft.Authorization/roleAssignments"
>   }]

And when we expand this identity we get : 

> {
>   "accountEnabled": "True",
>   "addIns": [],
>   "alternativeNames": [
>     "isExplicit=True",
>     "/subscriptions/ea075562-77d6-4d3f-89a0-b6c6f4f339e0/resourcegroups/MC_keolis_aks_westeurope/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-agentpool"
>   ],
>   "appDisplayName": null,
>   "appId": "34e6f899-a819-44af-b77f-a0477c629bc3",
>   "appOwnerTenantId": null,
>   "appRoleAssignmentRequired": false,
>   "appRoles": [],
>   "applicationTemplateId": null,
>   "deletionTimestamp": null,
>   "displayName": "aks-agentpool",
>   "errorUrl": null,
>   "homepage": null,
>   "informationalUrls": null,
>   "keyCredentials": [
>     {
>       "additionalProperties": null,
>       "customKeyIdentifier": "8E7A142F229831BB207134BE7D797CAAEE13C1B7",
>       "endDate": "2021-04-26T13:15:00+00:00",
>       "keyId": "895b7642-6031-4028-8979-157a1fdb9bad",
>       "startDate": "2021-01-26T13:15:00+00:00",
>       "type": "AsymmetricX509Cert",
>       "usage": "Verify",
>       "value": null
>     }
>   ],
>   "logoutUrl": null,
>   "notificationEmailAddresses": [],
>   "oauth2Permissions": [],
>   "objectId": "0f3fa9b7-8ea1-4643-897f-840bbb3f43dc",
>   "objectType": "ServicePrincipal",
>   "odata.metadata": "https://graph.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/$metadata#directoryObjects/@Element",
>   "odata.type": "Microsoft.DirectoryServices.ServicePrincipal",
>   "passwordCredentials": [],
>   "preferredSingleSignOnMode": null,
>   "preferredTokenSigningKeyEndDateTime": null,
>   "preferredTokenSigningKeyThumbprint": null,
>   "publisherName": null,
>   "replyUrls": [],
>   "samlMetadataUrl": null,
>   "samlSingleSignOnSettings": null,
>   "servicePrincipalNames": [
>     "34e6f899-a819-44af-b77f-a0477c629bc3",
>     "https://identity.azure.net/Gkhl6DuB+Fe17AwKWI4TOT6wtojvfG1DL8tns/MBXqI="
>   ],
>   "servicePrincipalType": "ManagedIdentity",
>   "signInAudience": null,
>   "tags": [],
>   "tokenEncryptionKeyId": null
> }
> 

So it seems we are provisionning the wrong managed identity.
@TomGeske can you please have a look at it ?

**Comment by ekhaydarov** [comment]
what has happened? its seems everything is jumbled up. slightly unrelated but managed identities are jumbled up.

```
> az aks pod-identity delete --cluster-name ${CLUSTER_NAME} --namespace ${NAMESPACE} --name data-core -g ${RESOURCE_GROUP}


Operation failed with status: 'Bad Request'. Details: Cluster identity has no assignment permission over identity 'resourceId: /subscriptions/xxx/resourcegroups/xxxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-ns-airflow-core - Please grant at least 'Managed Identity Operator' permission before assigning pod identity.
```

the name trying to be deleted `data-core` is not the same as whats being referenced in the error `aks-ns-airflow-core`.
whats happening here?

**Comment by zok1995** [comment]
The same issue with AKS 1.18.14. I assigned Managed Identity as Owner in VNET RG and I still getting the same error.

**Comment by ToxicWar** [comment]
I went through the same issue yesterday. The @ams0  example works for me (give "Network Contributor" role to MSI in `vnet_subnet_id`)
https://github.com/ams0/terraform-templates/blob/main/appgw-wildcard-aks/terraform/modules/aks/main.tf

```hcl
resource "azurerm_role_assignment" "aks" {
  principal_id         = azurerm_kubernetes_cluster.aks.identity[0].principal_id
  role_definition_name = "Network Contributor"
  scope                = var.vnet_subnet_id # Subnet ID
}
```

Just one important comment: It looks like permissions didn't apply immediately in my case (I already had a cluster and saw the issue in k8s events)
Even after recreating a Service resource, I saw the same permission error.
But after an hour, everything went well (maybe some internal token refreshed).

I recreated my AKS cluster from scratch to check this behavior, and after I create all resources step-by-step and only after this apply Service resource - no issues.

**Comment by kramfs** [comment]
> I went through the same issue yesterday. The @ams0 example works for me (give "Network Contributor" role to MSI in `vnet_subnet_id`)
> https://github.com/ams0/terraform-templates/blob/main/appgw-wildcard-aks/terraform/modules/aks/main.tf
> 
> ```terraform
> resource "azurerm_role_assignment" "aks" {
>   principal_id         = azurerm_kubernetes_cluster.aks.identity[0].principal_id
>   role_definition_name = "Network Contributor"
>   scope                = var.vnet_subnet_id # Subnet ID
> }
> ```
> 
> Just one important comment: It looks like permissions didn't apply immediately in my case (I already had a cluster and saw the issue in k8s events)
> Even after recreating a Service resource, I saw the same permission error.
> But after an hour, everything went well (maybe some internal token refreshed).
> 
> I recreated my AKS cluster from scratch to check this behavior, and after I create all resources step-by-step and only after this apply Service resource - no issues.

In my case, I had to assign the `principal_id` to the `resource group`, this is to satisfy a specific requirement where I need to assign an internal IP to an LB from a different subnet but within the same vNet. Role assignment to the vNet didn't work either, still complaining with some errors hence I went higher up the resource chain. Following the above example from @ams0 it's in a working state so I'm keeping it.

**Comment by vparames86** [comment]
This is a problem. The whole purpose of managed identity is to simplify the authentication between services in azure. I feel the Managed Identity should have atleast access to the resources created by the k8s cluster creation process, in this case the new vnet created when we choose azure cni.
