### ISSUE TITLE
Cannot create SSH tunnel into AKS cluster in westus2 location

### ISSUE THREAD

**Issue by ivansharamok** [Azure/AKS#156]
I got AKS 3-node cluster running in WestUS2 location. When I try to open SSH connection into it I get this message:
```
ssh: connect to host 52.183.101.113 port 22: Resource temporarily unavailable
```

## Create AKS cluster command
To create cluster I used previously generated SSH key (aks_id.pub, aks_id).
```
az aks create --name akscluster -g testgroup -u vmadmin--client-secret 'd632791b-b6e2-470b-8bf7-a8c5152ed41a' --location westus2 --service-principal '22b366f8-1b99-434a-97ba-4679c427a1f9' --ssh-key-value ~/.ssh/aks_id.pub --kubernetes-version 1.8.2
```

## Here is what I tried to SSH into aks master node
I tried a few approaches and environments to establish SSH connection with AKS master/nodes.

### WSL
```bash
ssh -i ~/.ssh/aks_id vmadmin@akscluster-testgroup-3f419f-15b80646.hcp.westus2.azmk8s.io
```
Result:
```
ssh: connect to host akscluster-testgroup-3f419f-15b80646.hcp.westus2.azmk8s.io port 22: Resource temporarily unavailable
```

### PuTTY on Win10
Configured PuTTY connection for host `akscluster-testgroup-3f419f-15b80646.hcp.westus2.azmk8s.io`
Result:
```
Network error: Connection timed out
```

### MacOS
Created SSH config file named `aks-connect-config`.
```
Host master
  HostName akscluster-testgroup-3f419f-15b80646.hcp.westus2.azmk8s.io
  Port 22
  User vmadmin
  IdentityFile ~/.ssh/aks_id
 
Host node01 aks-nodepool1-14792664-0
  HostName 10.240.0.6
  Port 22
  User vmadmin
  ProxyCommand ssh -F ~/.ssh/aks-connect-config -q master -W %h:%p
  IdentityFile ~/.ssh/aks_id
 
Host node02 aks-nodepool1-14792664-1
  HostName 10.240.0.5
  Port 22
  User vmadmin
  ProxyCommand ssh -F ~/.ssh/aks-connect-config -q master -W %h:%p
  IdentityFile ~/.ssh/aks_id

Host node03 aks-nodepool1-14792664-2
  HostName 10.240.0.4
  Port 22
  User vmadmin
  ProxyCommand ssh -F ~/.ssh/aks-connect-config -q master -W %h:%p
  IdentityFile ~/.ssh/aks_id
```
Supplied SSH config to the following command:
```
ssh -F ~/.ssh/aks-connect-config master
```
or
```
ssh -F ~/.ssh/aks-connect-config node01
```
Is there a bug that does not allow SSH connection to be established to AKS cluster in WestUS2 location?
Any tips how to troubleshoot this further?

**Comment by mboersma** [comment]
@ivansharamok are you trying to connect to the Kubernetes master or one of the worker nodes? AKS doesn't allow direct SSH to the master node, since that's the "managed" part of a managed k8s cluster.

**Comment by ivansharamok** [comment]
@mboersma I tried to SSH into master and each of the nodes. If AKS does not allow to SSH into master, does that mean that my ProxyCommand wouldn't work since it references master connection?
If that's the case how would I SSH into an AKS node?

**Comment by slack** [comment]
If you'd like to access nodes, you can drop a service that exposes port 22 on one of the workers. Or connect via a jumpbox you provision on the vnet.

Example: https://github.com/juan-lee/node-ssh-access
