### ISSUE TITLE
Private containers are accessible from outside AKS cluster when Azure CNI is used

### ISSUE THREAD

**Issue by renatodelgaudio** [Azure/AKS#1560]
Not sure whether the following behavior works as per design, or it is a design flawn.

**What happened**:
I have an AKS cluster with Advanced networking configured (Azure CNI plugin is used) deployed on an existing VNET.

**Azure subnet** (where AKS is deployed to) is a private range Class A  (e.g. 10.40.126.0/24)

**AKS Network config**:
Service CIDR (192.168.0.0/16)
DNS service IP: 192.168.0.10
Docker bridge CIDR (172.17.0.1/16)

I have deployed a sample app that it is not supposed to be reachable from outside the cluster ( **service type = ClusterIP**)
e.g.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```

Logging into the running container and inspecting the network interface config (e.g. ifconfig), I've noticed that the IP belongs to the Azure cluster subnet (e.g. 10.40.126.20).
This is not a surprise as [Microsoft doc page](https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni) clearly states that, with Azure CNI plugin, pods consumes IP from the Azure subnet and for this reason the subnet must be sized properly

From a machine, with network connectivity to Azure subnet, I've tried to perform a connection to a service running inside the container by using the subnet IP associated to the pod (e.g. 10.40.126.20) and **I was able to establish the connection successfully**.

**What you expected to happen**:
Since the Kuberentes Service associated to the pod is type = ClusterIP, I was not expecting that the pod was reachable from outside the kuberentes cluster.
It seems that, when Azure CNI plugin is used, regardless of the Service type defined, the pod are never private and they are always visible and reachable on the Azure subnet.

It looks to me that, with Azure CNI plugin, additional steps must be taken, in order to make sure that pod are not accessible from outside the cluster (this is the default behavior when other networking plugin are used in other Kubernetes flavors.  e.g. Bare metal K8s with Flannel plugin)

**How to reproduce it (as minimally and precisely as possible)**:
Simply spin up AKS cluster with advanced networking and deploy a sample app.
The services running within the pod will be accessible on the subnet IP that VNET assign to the POD)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.7
- Size of cluster (how many worker nodes are in the cluster?) 5
- Others:

**Comment by andriktr** [comment]
You are trying to reach out a pod directly by it's IP and not via service.  Pods get IP's from your custom Vnet subnet so it's normal that you can access pod from the device in the same vnet. Services has their own internal subnet which are different and should not overlap with pod IP's. As I  see in your case service CIDR is 192.168.0.0/16 so internal ip of your app service should be from this range and this address will be accessible only internally in your cluster.

**Comment by renatodelgaudio** [comment]
> Pods get IP's from your custom Vnet subnet so it's normal that you can access pod from the device in the same vnet

This is exactly the point that I am trying to make.
Should it be **not** normal that Pods are accessible from outside the cluster if they have not been explicitely exposed with the standard k8s mechanism such as Ingress, Service type LoadBalancer, Service type NodePort.
This is the common behavior with other Kubernetes pods networking plugins, but not with Azure CNI one.

**Comment by andriktr** [comment]
It's normal because it's by design for azure cni networking model. You can have your described scenario by using the kubenet networking model in your AKS cluster 
![image](https://user-images.githubusercontent.com/25537180/79641302-58ee0b00-819f-11ea-9e89-2f924139f343.png)

**Comment by renatodelgaudio** [comment]
Thanks to confirm.

It is clear that with Azure CNI, additional security measures must be taken to ensure the network isolation of pods from the underlying Azure VNET/subnet.

This is all that I wanted to double check with the community.

Thank you.

**Comment by andriktr** [comment]
You probably can close the issue then.
