### ISSUE TITLE
Nodepool stuck in "Scaling" prevents Scaling down thread after workload finishes

### ISSUE THREAD

**Issue by amrragab8080** [Azure/AKS#1561]
**What happened**:
Manually scaling aks nodes through ```az aks nodepool scale``` (requesting 75 nodes) results in partial recruitment of nodes joined to the cluster (71 actual) with remaining having insufficient capacity error. The nodepool **sits in perpetual "Scaling" after an hour.** Even after the workload finishes the scaling thread is blocked when choosing to scale down after workflow is completed with error:

```Operation failed with status: 'Conflict'. Details: Operation is not allowed: Another operation (Scaling) is in progress, please wait for it to finish before starting a new operation. See https://aka.ms/aks-pending-operation for more details```

Only solution is to delete the nodepool entirely or the entire cluster. To which of course incurs unnecessary costs.

**What you expected to happen**:
If partial recruitment is possible than the scaling thread should be unblocked so I can scale down, especially since the workload is complete, an hour later.

**How to reproduce it (as minimally and precisely as possible)**:
1. create a stack node with 1 node
2. manual scale beyond what capacity is possible  - ```az aks nodepool scale```
3. attempt to scale down back down to 1

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.16.7
- Size of cluster (how many worker nodes are in the cluster?)
71
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Argo
- Others:

**Comment by palma21** [comment]
This is a specific case, my recommendation would be to open a support ticket so we can look at your cluster. 

The cluster info and agent VM sku will be helpful in that case for us to take a look

**Comment by palma21** [comment]
Closing for now, waiting for Support Ticket.
