### ISSUE TITLE
Is there a reason for the load balancer idle timeout set to 30 minutes

### ISSUE THREAD

**Issue by adhodgson1** [Azure/AKS#1564]
When deploying new AKS clusters the TCP idle timeout for the outbound traffic flow is set to 30 minutes and this is documented [here.](https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#configure-outbound-ports-and-idle-timeout) However on the linked page discussing how [outbound](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#idletimeout) connections are handled, a 4 minute idle timeout is specified. Is there any reason for the longer timeout on AKS nodes?

**Comment by jluk** [comment]
For typical applications hosted in K8s, the majority of feedback has been the default LB timeout is far too short and causes too many timeouts. As a result AKS has increased the default, but left the property customizable for you if a different timeout is preferred.

https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#configure-outbound-ports-and-idle-timeout

Closing the question as I believe it's answered, but if not we can continue the conversation.
