### ISSUE TITLE
Network policies on Windows containers

### ISSUE THREAD

**Issue by Oldervoll** [Azure/AKS#1566]
According to [this](https://docs.microsoft.com/en-us/azure/aks/use-network-policies) documentation, network policies are only supported for Linux containers in AKS. 

Are there any plans to implement support for network policies on Windows containers in AKS? 

We want to limit traffic mainly across namespaces in our cluster. Is there any way to do that with the current situation?

**Comment by MikkelHegn** [comment]
Yes - we do have plans to bring the support to AKS. We currently have a few dependencies on OS and network policy providers that needs to be fixed before it show up. We hope we're able to provide the feature later this year.

**Comment by bahman616** [comment]
Is there any alternative for windows containers' network policies in AKS?
