### ISSUE TITLE
Fail to attach volume for pod 

### ISSUE THREAD

**Issue by mortzheng** [Azure/AKS#1567]
**What happened**:
Delete pods, pvc and pv to clean up a statefulset service.  After re-create the pod and pvc, the new pod failed to start. The events log says: Unable to mount volumes for pod "build-0_prod(56c4d0b2-5494-4731-bf3a-778ab0123b75)": timeout expired waiting for volumes to attach or mount for pod 

I check disk resource from Azure console and find that the old disk is still in attached (old PV in Kubernetes) and the new created disk (new PV in kubernetes) is in unattached.

**What you expected to happen**:
As i expected, the new PV should be attached for pod successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I attach the event log below:

Warning  FailedMount         2m2s (x15 over 33m)       kubelet, aks-opspool-38996706-vmss000000  Unable to mount volumes for pod "build-0_prod(56c4d0b2-5494-4731-bf3a-778ab0123b75)": timeout expired waiting for volumes to attach or mount for pod "prod"/"build-0". list of unmounted volumes=[home]. list of unattached volumes=[home build-token-j745v]
Warning  FailedAttachVolume  <invalid> (x18 over 34m)  attachdetach-controller                   AttachVolume.Attach failed for volume "pvc-10639e8b-d60a-41e1-a9a4-35d0365df410" : compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="AttachDiskWhileBeingDetached" Message="Cannot attach data disk 'kubernetes-dynamic-pvc-cc145afe-6e65-42d6-a627-fde51f687965' to VM 'aks-opspool-38996706-vmss_0' because the disk is currently being detached or the last detach operation failed. Please wait until the disk is completely detached and then try again or delete/detach the disk explicitly again. Instructions can be found at https://aka.ms/AzureDiskDetached"

**Environment**:
- Kubernetes version (use `kubectl version`):
server verison v1.15.10
client version v1.15.5
- Size of cluster (how many worker nodes are in the cluster?)
3 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
java app
- Others:

**Comment by jluk** [comment]
@mortzheng, this will be difficult to troubleshoot over github. To get you a timely resolution could you please open a support request so we can get an on-call engineer to troubleshoot this with you?

Thanks, closing in favor of an SR as that will be a better xp than back and forth on github.
