### ISSUE TITLE
How to use system pool

### ISSUE THREAD

**Issue by kutsyk-neocles** [Azure/AKS#1568]
I'm creating AKS cluster using ARM script. The goal is to create cluster from 0 with all needed configurations VNs, NGS and AgentPool. Here is mine ManagedCluster ARM template:
```
  {
            "apiVersion": "2020-03-01",
            "name": "[parameters('clusterName')]",
            "type": "Microsoft.ContainerService/managedClusters",
            "location": "[parameters('templateSettings').location]",
            "properties": {
                "kubernetesVersion": "[parameters('kubernetesVersion')]",
                "enableRBAC": true,
                "dnsPrefix": "[parameters('dnsPrefix')]",
                "agentPoolProfiles": [
                    {
                        "name": "nodepool",
                        "count": "[parameters('agentCount')]",
                        "vmSize": "[parameters('agentVMSize')]",
                        "osDiskSizeGB": "[parameters('osDiskSizeGB')]",
                        "vnetSubnetID": "[parameters('vnetSubnetID')]",
                        "maxPods": 110,
                        "minCount": 1,
                        "maxCount": 100,
                        "enableAutoScaling": true,
                        "type": "VirtualMachineScaleSets",
                        "storageProfile": "ManagedDisks"
                    }
                ],
                "servicePrincipalProfile": {
                    "ClientId": "[parameters('servicePrincipalClientId')]",
                    "Secret": "[parameters('servicePrincipalClientSecret')]"
                },
                "networkProfile": {
                    "loadBalancerSku": "standard",
                    "networkPlugin": "kubenet"
                },
                "addonProfiles": {
                    "httpApplicationRouting": {
                        "enabled": true
                    },
                    "omsagent": {
                        "enabled": true,
                        "config": {
                            "logAnalyticsWorkspaceResourceID": "[resourceId('Microsoft.OperationalInsights/workspaces', parameters('workspaceName'))]"
                        }
                    }
                },
                "nodeResourceGroup": "[concat(resourceGroup().name, '-nodes')]"
            }
        }
```

On deployment to Azure I receive this error which is not mentioned anywhere in docs:

```
{
    "error": {
        "code": "InvalidTemplateDeployment",
        "message": "The template deployment 'AksDeployment' is not valid according to the validation procedure. The tracking id is 'b68b569d-**********************'. See inner errors for details.",
        "details": [
            {
                "code": "MustDefineAtLeastOneSystemPool",
                "message": "Provisioning of resource(s) for container service aks-arm-test in resource group rg-arm-test failed. Message: {\n  \"code\": \"MustDefineAtLeastOneSystemPool\",\n  \"message\": \"Must define at least one system pool.\"\n }. Details: "
            }
        ]
    }
}
```

**Comment by ohorvath** [comment]
It seems API version 2020-03-01 introduced agent pool modes, so you need to define at least one of your agentpools as a system. AKS should create the first node pool as a system automatically, or the doc should state that the mode parameter is mandatory and should be set to system on at least one pool.

**Comment by kutsyk-neocles** [comment]
@ohorvath thank you for your response. Didn't get how can I change it on my side? Can you share doc from which you get it with me?

**Comment by ohorvath** [comment]
Just found the feature in the release notes:

https://github.com/Azure/AKS/releases/tag/2020-04-13

And found the param in arm reference for 2020-03-01. 

https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2020-03-01/managedclusters

mode | enum | No | AgentPoolMode represents mode of an agent pool. - System or User

**Comment by kutsyk-neocles** [comment]
I see, thought `No` means it is not required but turns our it is.
So the logic is that if I create the AKS cluster from 0, I have to create a System node pool and later I can add other `user` node pools, but system one should be there by default?

Can I create system node pool under my own load balancer and connect to my own virtual network?
Cause for now it connects to my vn but creates other resources by itself.

**Comment by jluk** [comment]
@ohorvath is correct, at least one system node pool is required in a cluster to provision. The full details are at aka.ms/aks/nodepools/mode please let us know if this is not clear.

You can add additional user node pools after creating the first system pool on cluster create.

**Comment by ohorvath** [comment]
I think the mode parameter should be listed as required in the docs.

**Comment by jluk** [comment]
Agree, we'll make this docs update to be clearer by end of week. The CLI will default az aks create to make a system pool, but this detail from the API can be clarified.

**Comment by hajina** [comment]
I can't find "nodepool" parameter in the https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2020-03-01/managedclusters

**Comment by jluk** [comment]
@hajina it is the mode property of the agentpoolprofile.

```
    "agentPoolProfiles": [
      {
        "count": "integer",
        "vmSize": "string",
        "osDiskSizeGB": "integer",
        "vnetSubnetID": "string",
        "maxPods": "integer",
        "osType": "string",
        "maxCount": "integer",
        "minCount": "integer",
        "enableAutoScaling": "boolean",
        "type": "string",
        "mode": "string",
```

**Comment by hajina** [comment]
I have already tried using a template, including following "AgentPoolProfiles" parameter.
                "agentPoolProfiles": [
                    {
                        "name": "nodepool1",
                        "count": 1,
                        "vmSize": "Standard_B4ms",
                        "osDiskSizeGB": 32,
                        "maxPods": 110,
                        "type": "VirtualMachineScaleSets",
                        "orchestratorVersion": "1.16.7",
                        "mode": "User",
                        "osType": "Linux"
                    }

But I got a error message.
{"code":"MustDefineAtLeastOneSystemPool", "message":"Must define at least one system pool."}

Is it because I didn't have the "minCount": 1, parameter?

**Comment by jluk** [comment]
The error is correct, your cluster must already have on pool with a mode of system. Please double check one exists on the cluster you are deploying more pools into. The mincount parameter is only related to the cluster autoscaler feature and shouldn't impact the above deployment if it is not enabled.

**Comment by hajina** [comment]
Thank you for letting me know the meaning of the "minCount" parameter.

I wondering when this template deploy, isn't system pool deployed automatically?
Do I need to create a system pool manually and define system pool setting in the template?

When I make AKS using Azure CLI, I didn't define system pool. But AKS is deployed successfully.

I tested following.
1. Deploy AKS.
      az aks create --name $AKS_CLUSTER_NAME --resource-group $AKS_RES_GROUP --node-count 1 --kubernetes-version 1.16.7 --node-vm-size Standard_B4ms --generate-ssh-keys --node-osdisk-size 32
2. Make Template-A for the AKS.
3. Edit Tempate-A.
    "servicePrincipalProfile"  add  "secret" parameter.
     Make Tempalte-B.
4. Deploy AKS using the Template-B in the same resource group <-- Success.

5. Edit Tempalte-B.
     change "resources":"name", "dnsPrefix", etc..
     Make Tempalte-C.
6. Deploy AKS using the Template-C in the new resource group <-- fail.
    Got a "Must define at leat one system pool." error message.

**Comment by jluk** [comment]
The CLI defaults az aks create to deploy with one system pool because that is mandatory. Deployment from ARM template relies on API Defaults, it must define the managed cluster and at least one pool with mode = system. At the API as mentioned above, the mode property must be set. So in ARM template you have to explicitly create a pool and set the mode to system.

**Comment by jluk** [comment]
I believe the OP's above questions have been answered, we are updating the system docs to be clearer on API requirements. I will close this issue as a result, for new questions please post new issues. Thanks everyone for the feedback.
