### ISSUE TITLE
Support attach-acr automation through ARM template

### ISSUE THREAD

**Issue by shahga** [Azure/AKS#1569]
ARM template for AKS, as per specs below, does not have a way to attach ACR. 
https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2020-03-01/managedclusters.

Please provide a way to supply ACR ID to ARM template for AKS, so that ACR is attached as part of AKS Cluster creation.

**Comment by jluk** [comment]
@shahga the attach ACR streamlined experience is a client side function, so azure cli has the attach-acr capability automated. Automation through ARM templates will need ACR to be linked and authorized manually. Adding Thomas for vis on this feedback though.

**Comment by shahga** [comment]
In enterprises, attaching AKS to a private ACR is almost always essential, so why not make it part AKS ARM template.  Keeping this separate, introduces ceremonies prone to errors.

**Comment by TomGeske** [comment]
We offer ACR attach experience through CLI and soon in portal. As @jluk mention it is a client-side operation happening outside of the AKS resource provider. We just do a role assignment for ACR to grant access the cluster identity. 

You can perform role assignments in your ARM template. For more details check [here](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-template#add-a-role-assignment.
).

**Comment by TomGeske** [comment]
I'm going ahead closing this one. Feel free to continue commenting.
