### ISSUE TITLE
Support more than 10 AKS node pools

### ISSUE THREAD

**Issue by lewalt000** [Azure/AKS#1570]
**Issue**:
Are there any work-arounds to create more than 10 AKS node pools? Is there a practical reason for the limit of 10? Is it possible to "connect" two AKS clusters if more than 10 node pools are needed?

**Comment by jluk** [comment]
@lewalt000 this is a hard limit today which is driven out of the 1000 node limit for a cluster, each node pool reaching 100 nodes each.

Could you share your scenario for needing more than 10 nodes? 
Is it a matter of needing 10 different SKUs / node pool profiles in a single cluster or needing a higher than 1k node limit? 
Can you use multiple clusters?

**Comment by lewalt000** [comment]
Hi @jluk - Thank you for the quick reply. The scenario is needing more than 10 different SKU / node pool profiles vs higher than 1k node limit.

Is there any possibility to make this configurable so a user could have more than 10 node pools as long as they don't go over the 1000 node cluster limit?

**Comment by Robert-Stam** [comment]
We are running AKS clusters with:
- multiple availability zones (3)
- multiple VM-scalesets (aks nodepools) currently up-to 7
- with the cluster auto-scaler enabled (min=1-max=30 nodes/np)
- using persistent storage / PVC (from multiple AZ, dependent on where the pod is launched the first time)
 - installed Kured for rebooting nodes which need to (for updates)

We run into the issue that Kured is cordoning/draining nodes and the auto-scaler is creating new ones, however not always in the same AZ.
This results in pods that cannot mount it's volume anymore.

As workaround I found this: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#i-have-a-couple-of-pending-pods-but-there-was-no-scale-up
This implies that we add more node-pools, however we cannot add more than 10 ATM.

It would be great if we could (and AKS can check at runtime (or even use the max on the nodepools we specify) if we respect the limit of 1000 nodes in total). 

If we would be able to create 30 nodepools we are fine.

Thanks in advance!

**Comment by ohorvath** [comment]
In our scenario it would be useful to have node pools larger than 100. :) We are provisioning big data clusters with about 400 nodes so we are good with the max limit for the cluster, but we have to manually separate the workload into multiple pools.

**Comment by Robert-Stam** [comment]
> We are running AKS clusters with:
> 
> * multiple availability zones (3)
> * multiple VM-scalesets (aks nodepools) currently up-to 7
> * with the cluster auto-scaler enabled (min=1-max=30 nodes/np)
> * using persistent storage / PVC (from multiple AZ, dependent on where the pod is launched the first time)
> * installed Kured for rebooting nodes which need to, because the sentinel is set (for updates)
> 
> We run into the issue that Kured is cordoning/draining nodes and the auto-scaler is creating new ones, however not always in the same AZ.
> This results in pods that cannot mount it's volume anymore.
> 
> As workaround I found this: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#i-have-a-couple-of-pending-pods-but-there-was-no-scale-up
> This implies that we add more node-pools, however we cannot add more than 10 ATM.
> 
> It would be great if we could (and AKS can check at runtime (or even use the max on the nodepools we specify) if we respect the limit of 1000 nodes in total).
> 
> If we would be able to create 30 nodepools we are fine.
> 
> Thanks in advance!

Is there an alternative way to instruct the cluster auto-scaler to spin up a new node in the correct AZ?

**Comment by Robert-Stam** [comment]
> > We are running AKS clusters with:
> > 
> > * multiple availability zones (3)
> > * multiple VM-scalesets (aks nodepools) currently up-to 7
> > * with the cluster auto-scaler enabled (min=1-max=30 nodes/np)
> > * using persistent storage / PVC (from multiple AZ, dependent on where the pod is launched the first time)
> > * installed Kured for rebooting nodes which need to, because the sentinel is set (for updates)
> > 
> > We run into the issue that Kured is cordoning/draining nodes and the auto-scaler is creating new ones, however not always in the same AZ.
> > This results in pods that cannot mount it's volume anymore.
> > As workaround I found this: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#i-have-a-couple-of-pending-pods-but-there-was-no-scale-up
> > This implies that we add more node-pools, however we cannot add more than 10 ATM.
> > It would be great if we could (and AKS can check at runtime (or even use the max on the nodepools we specify) if we respect the limit of 1000 nodes in total).
> > If we would be able to create 30 nodepools we are fine.
> > Thanks in advance!
> 
> Is there an alternative way to instruct the cluster auto-scaler to spin up a new node in the correct AZ?

@jluk Justin, we figured out that the cluster-autoscaler implementation from Azure doesn't support the zones natively, it just adds a node and doesn't respect any affinities we specify like
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/region
         operator: In
          values:
          - westeurope
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - westeurope-2

Please see https://github.com/kubernetes/autoscaler/blob/73a5cdf928d3b04ac5cbc456a60d5eb084f9cbc1/cluster-autoscaler/cloudprovider/azure/azure_kubernetes_service_pool.go#L135 

Will this support be added?

**Comment by bhicks329** [comment]
I’m also interested in more than 10 nodepools for isolation and automated placement of workloads. The Scenario I’m thinking of is that  you could template out a series of potential nodepools for differing workloads with certain skus in different subnets (for the specific workload type) and all scaled to zero. A developer / engineer would only need to deploy the application with the correct labels to have the relevant nodes auto scaled / created. This could also work for node pool upgrades as well. A new version is assured and released by the central teams and the developers are firmly in control of when they move their workloads.

**Comment by gustavosavio** [comment]
I'm also interested in more than 10 nodepools. Is there anything new about that?

**Comment by Robert-Stam** [comment]
Any new about this one?
We are waiting on it, see here why:
https://github.com/Azure/AKS/issues/1570#issuecomment-619372990

**Comment by guisesterheim** [comment]
My scenario is that we are working with blue-green deployment, and the entire application environment (including AKS) goes up and down at every deployment.
Each AKS should have two node-pools for helping with billing (each company area pays the bills for each node pool).

But if I have 4 environments (already 8 node pools in the same region), I'll have my developers to wait for the oldest environment to be destroyed by blue/green in order to place a new deployment.

Our current workaround is to use a single node-pool for all the areas. But that's causing some misunderstanding on the bills here.

Would love to allow N node pools still respecting those 1000 VMs

**Comment by dintel** [comment]
cluster-autoscaler requires separate node group for each AZ to be able to spin up new nodes in a specific AZ.
Our production environment requires to run pod spread across AZs to maximize availability.
We also use StatefulSets and for cluster-autoscaler to work correctly per AZ node group is required.

**Comment by ms-lolo** [comment]
Hey just checking in here. It looks like the latest versions of Kubernetes support up to 5000 nodes. Does this change the work needed for more than 10 nodepools? Even before the work in this ticket is completed, is it reasonable to think a limit of 50 nodepools might be coming soon with the adoption of new kubernetes versions?

**Comment by romeotheriault** [comment]
10 nodepool limit is also a problem for my company. We need more node types in the cluster. We don't need to use 1000 nodes though. It would be really, really useful for us to be able to create more than 10 nodepools. Currently we're having to do different hacky stuff to work around this limitation.

**Comment by ms-lolo** [comment]
> Updated to 100 node pools, see [Here](https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/container-service-limits.md)

@Simonverge could you tell us how we take advantage of these new limits? I see the documentation has been updated but my portal is still telling me there is a max of 8 (not sure where 8 comes from) pools when I hover over the new node pool button (which is disabled).

Thanks for making this happen!

**Comment by romeotheriault** [comment]
Verified I can create more than 10 nodepools in the Azure console. Thank you!
