### ISSUE TITLE
max pod  25 even when you have --max-pods 150 in any other pool and allows max 150 in primary node pool

### ISSUE THREAD

**Issue by niteenkole** [Azure/AKS#1572]
**What happened**:
 during cluster creation say you have --max-pods 150

when you deploy number of pods in any other then primary pool will not cross 25

primary pool it allows to have max 150 pods per node

**What you expected to happen**:

each node in any pool should be able to create max pool to 150 till you have enough resource 

**How to reproduce it (as minimally and precisely as possible)**:

Create cluster with options --max-pods 150 --nodepool-labels dedicated=edge

create new pool say apppool1 with any D8s_V3  or D4s_V3 or anything...

deploy simple deployment like
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  labels:
    app: busybox
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent

        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']

now try to scale

kubectl scale deployment -n coop-solndesign busybox-deployment --replicas=40

you will see max pods on each node will not cross 25 in other pool.

when primay pool node reach max 150 on each node other pool max pod will be 25 and everything else will go pending.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"20c697423de11d4d5d08c6832a513217ca11a6aa", GitTreeState:"clean", BuildDate:"2020-02-21T10:47:45Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
any size i tested with 3, 6, 9
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
simple app no load at all
- Others:

**Comment by niteenkole** [comment]
[xxxaksnp01@slnxxxd01 ubuntu]$ kubectl get po -n coop-solndesign -o wide |grep -i aks-apppool01-35427162-vmss000000 |wc -l
25
[xxxaksnp01@slnxxxd01 ubuntu]$ kubectl get po -n coop-solndesign -o wide |grep -i aks-apppool01-35427162-vmss000001 |wc -l
20
[xxxaksnp01@slnxxxd01 ubuntu]$ kubectl get po -n coop-solndesign -o wide |grep -i aks-apppool01-35427162-vmss000002 |wc -l
25
[xxxaksnp01@slnxxxd01 ubuntu]$ kubectl get po -n coop-solndesign -o wide |grep -i aks-nodepool1-35427162-vmss000000 |wc -l
146
[xxxaksnp01@slnxxxd01 ubuntu]$ kubectl get po -n coop-solndesign -o wide |grep -i aks-nodepool1-35427162-vmss000003 |wc -l
146
[xxxaksnp01@slnxxxd01 ubuntu]$ kubectl get po -n coop-solndesign -o wide |grep -i aks-nodepool1-35427162-vmss000004 |wc -l
146
[xxxaksnp01@slnxxxd01 ubuntu]$ kubectl get deployment -n coop-solndesign
NAME                 READY     UP-TO-DATE   AVAILABLE   AGE
busybox-deployment   508/600   600          508         4m49s

**Comment by palma21** [comment]
I noticed your initial pool was created with 150. But your second added pool was created with 30 (the default) which is why you see this behavior.

You can specify max-pods per pool at aks nodepool add time.

Lmk if we can assist further

**Comment by niteenkole** [comment]
looks like i used gui for second pool which will default to 30.
