### ISSUE TITLE
Will ZRS PVC pods be able to cross zones?

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#1575]
If I create a statefulset and with a pvc that uses zrs in a multi zone cluster and all nodes in zone 1 go down can the pod get scheduled to a node in zone 2?

**Comment by andyzhangx** [comment]
azure managed disk don't support ZRS, I think you are mentioning azure file, right? As I know, Azure file could be accessed by all VMs in the same region, so it could cross zones.

**Comment by AceHack** [comment]
No I was talking about managed disks, I didn't know they didn't support ZRS :(.  How much slower is Azure file?  It would not be good for something like SQL server correct?

**Comment by andyzhangx** [comment]
azure file is slow in read/write small files(e.g. ~1k size), while if you scenario is big file size(e.g. > 1GB), i think it would be ok, and I know mysql service is based on azure file for your reference.
