### ISSUE TITLE
Support private cluster in Azure China

### ISSUE THREAD

**Issue by nxdxy** [Azure/AKS#1576]
**What happened**: failed to create private cluster in China Azure

**What you expected to happen**: 

**How to reproduce it (as minimally and precisely as possible)**:  
az aks create -n paks -g aks --load-balancer-sku standard --enable-private-cluster --generate-ssh-keys --location chinanorth2
Operation failed with status: 'Bad Request'. Details: Private cluster is not available at this region. Please refer to https://aka.ms/aks/private-cluster for detail

**Comment by nxdxy** [comment]
HI guys，

in release note it states Private clusters in AKS is now generally available in  all regions AKS is in. 

But our test in China north2 and china east2 both failed.

I was told by China Microsoft team that this feature is not avaliable yet in AzureChina, could you help to confirm or add some relevant instructions in the release note? Our customer get confused because the release note states "all regions AKS is in".

thanks

**Comment by jluk** [comment]
@nxdxy thanks for the report, private clusters are not yet available in Azure China or Azure Government. This is an issue in the docs that will be resolved. When we have an ETA on both we will relay here, apologies for the lack of clarity in the GA statements about private clusters. This will be notated better for sovereign clouds in the future.

**Comment by karataliu** [comment]
Private cluster depends on 'private link' feature, which is not ready in Azure China:
https://azure.microsoft.com/en-us/global-infrastructure/services/?products=private-link

**Comment by TomGeske** [comment]
Current ETA is end of August
