### ISSUE TITLE
AKS support for Ubuntu 20.04 LTS (Focal Fossa)

### ISSUE THREAD

**Issue by yaakov-h** [Azure/AKS#1579]
Basically https://github.com/Azure/AKS/issues/1487 but for the latest LTS rather than the now-two-years-old one.

Please tell me this won't likewise take nearly two years to hit preview and then onto GA afterwards?

**Comment by lgmorand** [comment]
You should specify which specific feature of 20.04 you are looking for since they are managed for us

**Comment by yaakov-h** [comment]
tbh I mostly just want support everywhere for ecdsa-sk ssh keys 😅

**Comment by jluk** [comment]
@yaakov-h AKS supports a very broad scope of customers with dependencies on other services to provide compatibility with our OS offering. 

As a result we strive to keep all components up to date and within support (such as moving off of 16.04 prior to EoL), but we provide a conservative approach to how often we force core changes to all customers. As a result this move to 20.04 is not on the roadmap in the near term as we focus on moving from 16.04 to 18.04.

We appreciate the feedback and will keep it in mind on your ask for capabilities in 20.04. If more of these arise feel free to open new issues, but I wanted to share details to provide color on how we approach these decisions.

I will be closing this as a result of not being in the near term roadmap, but we will revisit the discussion for 20.04 when that time comes.

**Comment by alexeldeib** [comment]
we're actually working on this. ETA TBD.

**Comment by alexeldeib** [comment]
aw man, I missed https://github.com/Azure/AKS/issues/2883 opened yesterday. let's use that.
