### ISSUE TITLE
Increase lifetime of AD credentials

### ISSUE THREAD

**Issue by s-spindler** [Azure/AKS#1580]
We activated the AKS AD integration in order to give various teams in our organization restricted access to an AKS cluster. So far everything works ok with the one exception that users need to frequently log in again (prompted on the command line to follow a link and copy a code).
The kube config files have an `expires-in` and `expires-on` field that suggest that the login lifetime is one hour. I'm wondering if this is configurable and if so, where. I was not able to find anything in the official documentation but maybe I checked in the wrong places.

**What happened**:
Frequent log ins required for kubectl to work.

**What you expected to happen**:
Frequency to be configurable.

**How to reproduce it (as minimally and precisely as possible)**:
Create AKS cluster with AD integration. Call `az aks get-credentials` as a user with `Azure Kubernetes Service Cluster User Role`.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.10

**Comment by s-spindler** [comment]
I'm surprised about the chirping cricket response... No one else has this problem or are we just doing something wrong? The way it is it's really annoying.

**Comment by TomGeske** [comment]
@s-spindler: Does your token always expires after one hour? Do you have a valid refresh token in your .kube/config?

**Comment by s-spindler** [comment]
@TomGeske Expiry is always after one hour, yes. There is a refresh token but idk whether or not it's valid. It's not a JWT, that's for sure. Can you tell me how to validate it?

**Comment by TomGeske** [comment]
Sounds like refresh token validation fails.

1. What is your kubectl version? Could you make sure you use latest kubectl? To update use:
   `az aks install-cli`
2. Are you using AKS-managed AAD or our legacy experience?
  `az aks show -n <cluster-name> -g <cluster-rg> --query 'aadProfile.managed'`

**Comment by s-spindler** [comment]
1. I wasn't able to reproduce this with either my (1.15.x) nor an updated (1.18.x) kubectl version. My colleagues reported that they have not faced this issue in some time.
2. The command shows no output.

Closing this issue as no longer relevant. Thanks for the help @TomGeske!
