### ISSUE TITLE
Azurefile mounted volume slow copy vs Microsoft Azure Storage Explorer

### ISSUE THREAD

**Issue by lgarcia11** [Azure/AKS#1581]
I have a 4GB zip file stored in a Standard/Hot file share. Using Microsoft Azure Storage Explorer it takes around 5 minutes to download it but with the file share mounted as a volume inside a container and using python shutil.copy to copy it to a temp directory it takes over 40 minutes. Any ideas why are the copy speeds different?

Used mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=1000
- gid=1000
- mfsymlinks
- nobrl
- cache=none

**Comment by andyzhangx** [comment]
@lgarcia11 Have you tried mount that file share on your VM and do the comparison, I doubt whether that's related to AKS. Azure Storage Explorer may use multi-thread to download data. 
cc @VybavaRamadoss  @gunjanj

**Comment by andyzhangx** [comment]
cc @smfrench, any insight?
