### ISSUE TITLE
v1.17.x-preview Can't delete LoadBalancer service

### ISSUE THREAD

**Issue by oliverholliday** [Azure/AKS#1582]
It seems to be impossible to delete a LoadBalancer service which is bound to an internal subnet. 
k8s reports that the service has been deleted, but it still exists and in the 'describe' output there are events about repairing port and IP allocations.

**How to reproduce it (as minimally and precisely as possible)**:

I created an internal load balancer resource on an AKS 1.17 cluster as per the instructions here:
https://docs.microsoft.com/en-gb/azure/aks/internal-lb

I couldn't complete deleting the service following these instructions:
https://docs.microsoft.com/en-gb/azure/aks/internal-lb#delete-the-load-balancer 

**Anything else we need to know?**:

I upgraded to 1.17 as I read elsewhere that this is the first version which supports correctly cleaning up the AKS loadbalancer resource port mappings and I was having problems with the 1.16.7 Azure loadbalancer still binding all the old external ports and IPs.

**Environment**:
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"260aa4feed9c12e5256e5c69c2b329d768de2f26", GitTreeState:"clean", BuildDate:"2020-04-03T15:19:08Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
1 node

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
nginx-ingress

I appreciate that 1.17 is in preview, I'm just reporting this as it's a bug I experienced.

**Comment by jluk** [comment]
@oliverholliday thanks for reporting this, could you open a support request so we can debug the cluster? While the feature is in preview, we can still field business hour requests to troubleshoot this dev/test cluster.
