### ISSUE TITLE
Seeing user nodepool created on az create

### ISSUE THREAD

**Issue by lgmorand** [Azure/AKS#1583]
**What happened**:

"When you create a new AKS cluster, you automatically create a system node pool with a single node." So I'm expecting to have as least one system pool on all my clusters, especially the new created (using CLI 2.4.0 but with aks preview enabled)

I just created an AKS cluster, and the default nodepool (name nodepool1) is a "user" nodepool when I'm using CLI az aks nodepool show 

> {
  "agentPoolType": "VirtualMachineScaleSets",
  "availabilityZones": null,
  "count": 1,
  "enableAutoScaling": true,
  "enableNodePublicIp": false,
  "id": "/subscriptions/6c9dc160-dca4-47cb-9e76-ed16a4b4edb1/resourcegroups/rg-aks-test/providers/Microsoft.ContainerService/managedClusters/aks-test/agentPools/nodepool1",
  "maxCount": 3,
  "maxPods": 110,
  "minCount": 1,
  **"mode": "User"**,

with kubectl, I don't have the specific label either (kubernetes.azure.com/mode: system).

> apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2020-04-27T14:09:39Z"
  labels:
    agentpool: nodepool1
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: Standard_DS2_v2
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: westeurope
    failure-domain.beta.kubernetes.io/zone: "0"
    kubernetes.azure.com/cluster: MC_rg-aks-test_aks-test_westeurope
    kubernetes.azure.com/role: agent
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: aks-nodepool1-17697912-vmss000000
    kubernetes.io/os: linux
    kubernetes.io/role: agent
    node-role.kubernetes.io/agent: ""
    storageprofile: managed
    storagetier: Premium_LRS

Then if I update the nodepool mode to system, the mode appears in json (CLI) and also as a label with kubectl

> {- Finished ..
  "agentPoolType": "VirtualMachineScaleSets",
  "availabilityZones": null,
  "count": 1,
  "enableAutoScaling": true,
  "enableNodePublicIp": false,
  "id": "/subscriptions/6c9dc160-dca4-47cb-9e76-ed16a4b4edb1/resourcegroups/rg-aks-test/providers/Microsoft.ContainerService/managedClusters/aks-test/agentPools/nodepool1",
  "maxCount": 3,
  "maxPods": 110,
  "minCount": 1,
  **"mode": "System",**

BUT if I try to modify again the mode to user, I get the following error:

> "Operation failed with status: 'Bad Request'. Details: Must define at least one system pool."

**What you expected to happen**:

1- HAving a default system nodepool
2- The error is misguiding. I think it's failing because there no other system nodepool and should warn about it, not that the specified nodepool is not system when it is

**How to reproduce it (as minimally and precisely as possible)**:

create a cluster

**Anything else we need to know?**:

**Environment**:
- Kubernetes version : 1.18.2 (client), 1.15.10 (server)
- Size of cluster :  2 nodepools of 1 node
- CLI 2.4.0
- sandbox cluster

**Comment by jluk** [comment]
@lgmorand could you share the full output of az --version and the full command you ran on create?

I could not repro that issue and am seeing the cluster create with a default of one system pool.

```
➜  ~ az aks show -g myresourcegroup -n systemtest -o jsonc
{
  "aadProfile": null,
  "addonProfiles": null,
  "agentPoolProfiles": [
    {
      "availabilityZones": null,
      "count": 3,
      "enableAutoScaling": null,
      "enableNodePublicIp": false,
      "maxCount": null,
      "maxPods": 110,
      "minCount": null,
      "mode": "System",
      "name": "nodepool1",
      "nodeLabels": {},
      "nodeTaints": null,
      "orchestratorVersion": "1.15.10",
      "osDiskSizeGb": 100,
      "osType": "Linux",
      "provisioningState": "Creating",
      "scaleSetEvictionPolicy": null,
      "scaleSetPriority": null,
      "spotMaxPrice": null,
      "tags": null,
      "type": "VirtualMachineScaleSets",
      "vmSize": "Standard_DS2_v2"
    }
```

**Comment by lgmorand** [comment]
> {
  "azure-cli": "2.4.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.4.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aks-preview": "0.4.43",
    "aro": "0.4.0"
  }
}

**Comment by lgmorand** [comment]
From the same environment, I just ran 

> az aks create -g rg-test -n aks-test-juk --node-count 1

and this time the noodpool is system. I'll try over the next days to rerun the full script to see if something else can cause this behavior

**Comment by jluk** [comment]
Thanks for doing another test, I have also tried reproducing a handful of times but seeing the correct behavior with system pool deployments. I'm going to close this issue for now, but if you hit another repro just comment and we can revisit/reopen this issue as needed.

**Comment by lgmorand** [comment]
sure @jluk . I'll keep the cluster untouched if I can repro

**Comment by lgmorand** [comment]
@jluk just ran the same script (full and long customization). The default nodepool is indeed system now.
that's weird :)
