### ISSUE TITLE
How to make AKS using Template (system pool)

### ISSUE THREAD

**Issue by hajina** [Azure/AKS#1584]
I would like to make AKS using template. but It is failed.
Could you let me know what I change my template?

I tested following. 

0. Deploy AKS using Azure CLI.
az aks create --name $AKS_CLUSTER_NAME --resource-group $AKS_RES_GROUP --node-count 1 --kubernetes-version 1.16.7 --node-vm-size Standard_B4ms --generate-ssh-keys --node-osdisk-size 32

1. Make Template-A for the AKS.

2. Edit Tempate-A.
"servicePrincipalProfile" add "secret" parameter.
"resources": >                 "servicePrincipalProfile": >                    "secret": "$Secret"
Make Tempalte-B.

3. Deploy AKS using the Template-B in the same resource group <-- Success.

4. Edit Tempalte-B.
- "parameters": >        "managedClusters_TemplateAKSTest_name": >            "defaultValue" : another name
- "parameters": >        "publicIPAddresses_$Public IP UUID_externalid": >             "defaultValue" : another resource group name
- "resources": >            "properties": >               "dnsPrefix" : another name
- "resources": >            "properties": >             "agentPoolProfiles": > "mode": "System"
Make Tempalte-C.

5. Deploy AKS using the Template-C in the new resource group <-- fail.
Resource is created in the new resource group.
But I got a error message.
Got a "Must define at leat one system pool." error message.

Could you let me know what I change my template?

> {
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "managedClusters_TemplateAKSTest_name": {
            "defaultValue": "TemplateAKSTest2",
            "type": "String"
        },
        "publicIPAddresses_$Public IP UUID_externalid": {
            "defaultValue": "/subscriptions/$Subscription UUID/resourceGroups/MC_TemplateAKSTest2_TemplateAKSTest2_koreacentral/providers/Microsoft.Network/publicIPAddresses/$Public IP UUID",
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.ContainerService/managedClusters",
            "apiVersion": "2020-03-01",
            "name": "[parameters('managedClusters_TemplateAKSTest_name')]",
            "location": "koreacentral",
            "sku": {
                "name": "Basic",
                "tier": "Free"
            },
            "properties": {
                "kubernetesVersion": "1.16.7",
                "dnsPrefix": "$DNSPrefix",
                "agentPoolProfiles": [
                    {
                        "name": "nodepool1",
                        "count": 1,
                        "vmSize": "Standard_B4ms",
                        "osDiskSizeGB": 32,
                        "maxPods": 110,
                        "type": "VirtualMachineScaleSets",
                        "orchestratorVersion": "1.16.7",
                        "mode": "System",
                        "osType": "Linux"
                    }
                ],
                "linuxProfile": {
                    "adminUsername": "azureuser",
                    "ssh": {
                        "publicKeys": [
                            {
                                "keyData": "ssh-rsa $KEY"
                            }
                        ]
                    }
                },
                "servicePrincipalProfile": {
                    "clientId": "$ClientID",
                    "secret": "$Secret"
                },
                "nodeResourceGroup": "[concat('MC_', parameters('managedClusters_TemplateAKSTest_name'), '_', parameters('managedClusters_TemplateAKSTest_name'), '_koreacentral')]",
                "enableRBAC": true,
                "networkProfile": {
                    "networkPlugin": "kubenet",
                    "loadBalancerSku": "Standard",
                    "loadBalancerProfile": {
                        "managedOutboundIPs": {
                            "count": 1
                        },
                        "effectiveOutboundIPs": [
                            {
                                "id": "[parameters('publicIPAddresses_$Public IP UUID_externalid')]"
                            }
                        ]
                    },
                    "podCidr": "10.244.0.0/16",
                    "serviceCidr": "10.0.0.0/16",
                    "dnsServiceIP": "10.0.0.10",
                    "dockerBridgeCidr": "172.17.0.1/16",
                    "outboundType": "loadBalancer"
                }
            }
        },
        {
            "type": "Microsoft.ContainerService/managedClusters/agentPools",
            "apiVersion": "2020-03-01",
            "name": "[concat(parameters('managedClusters_TemplateAKSTest_name'), '/nodepool1')]",
            "dependsOn": [
                "[resourceId('Microsoft.ContainerService/managedClusters', parameters('managedClusters_TemplateAKSTest_name'))]"
            ],
            "properties": {
                "count": 1,
                "vmSize": "Standard_B4ms",
                "osDiskSizeGB": 32,
                "maxPods": 110,
                "type": "VirtualMachineScaleSets",
                "orchestratorVersion": "1.16.7",
                "mode": "User",
                "osType": "Linux"
            }
        }
    ]
}

**Comment by hajina** [comment]
I changed all "mode" parameter to "system".
Then I created AKS using this Template successully.
Is it updated any other azure template parameter recently?


> 
{
    "resources": [
        {
            "properties": {
                "agentPoolProfiles": [
                    {
                        "name": "nodepool1",
                        "count": 1,
                        "vmSize": "Standard_B4ms",
                        "osDiskSizeGB": 32,
                        "maxPods": 110,
                        "type": "VirtualMachineScaleSets",
                        "orchestratorVersion": "1.16.7",
                        "mode": "System",          <-- System
                        "osType": "Linux"
                    }
                ],
            }
        },
        {
            "properties": {
                "count": 1,
                "vmSize": "Standard_B4ms",
                "osDiskSizeGB": 32,
                "maxPods": 110,
                "type": "VirtualMachineScaleSets",
                "orchestratorVersion": "1.16.7",
                "mode": "User",         <-- System
                "osType": "Linux"
            }
        }
    ]
}

**Comment by hajina** [comment]
But, I created new AKS today,
mode=system parameter is changed.
Is it changed AKS parameter recently?

>  "aadProfile": null,
  "addonProfiles": null,
  "agentPoolProfiles": [
    {
      "availabilityZones": null,
      "count": 1,
      "enableAutoScaling": null,
      "enableNodePublicIp": false,
      "maxCount": null,
      "maxPods": 110,
      "minCount": null,
      "mode": "System",
      "name": "nodepool1",
      "nodeLabels": {},
      "nodeTaints": null,
      "orchestratorVersion": "1.16.7",
      "osDiskSizeGb": 32,
      "osType": "Linux",
      "provisioningState": "Succeeded",
      "scaleSetEvictionPolicy": null,
      "scaleSetPriority": null,
      "spotMaxPrice": null,
      "tags": null,
      "type": "VirtualMachineScaleSets",
      "vmSize": "Standard_B4ms",
      "vnetSubnetId": null
    }

**Comment by jluk** [comment]
Troubleshooting ARM templates is out of scope of this project issue page, please use an azure support ticket if this is still an issue for you. Closing as a result.
