### ISSUE TITLE
Use ServicePrincipal to gain access to underlying K8s Cluster through REST API.

### ISSUE THREAD

**Issue by dbutaciu** [Azure/AKS#1585]
**Scenario**:
User creates an AKS so his account is the admin. He can go now in powershell and:
1.	Az aks get-credentials -g group-name -n cluster-name --admin
2.	Kubectl – to create any resource (like ClusterRoles, Bindings, ServiceAccounts, Secrets, etc.) if needed
This is the setup part.

Now the actual usage of this:
After the first part, I have an app that starts a process that connects to the K8s Cluster and lists all the resources like: pods, namespaces, deamonsets, etc. using K8s REST API, not kubectl. Now this process only needs to have Read permissions over the AKS Cluster and the underlying K8s Cluster.

I was able to use a ServicePrincipal with Azure Kubernetes Service Cluster Admin Role to connect to AAD and use listClusterAdminCredentials which returns a base64 encoded string, from which I can extract the admin token which works for a call like https://dns-name.io/api/v1/pods.

To use OpenID I need an id_token, which doesn't exist for a ServicePrincipal, only for a human user. Is there any way we can provide to the app a ServicePrincipal with the aforementioned Reader permissions (azure AAD + corresponding RBAC)? Or the only way is to create a "reader" ServiceAccount and manually set this token as an input for the app?

**Comment by andyzhangx** [comment]
ServicePrincipal is for access Azure resource, to access k8s cluster, you need kubeclient access, here is an example: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/2734d3e110fa44ab203d42e5c47de3b35b375b0a/pkg/azurefile/azure.go#L37
Also you need assign related service account permissions.

**Comment by andyzhangx** [comment]
close this issue since use kubeclient should be the better way, and already provided an example

**Comment by palma21** [comment]
This should meet your needs. Give it a try and let us know your feedback
https://github.com/Azure/kubelogin#service-principal-login-flow-non-interactive
