### ISSUE TITLE
Securing traffic between Windows Containers

### ISSUE THREAD

**Issue by dineshsharmads** [Azure/AKS#1589]
As Network policies are currently not supported on Windows Containers, is there any other way we can secure traffic between windows containers?

**Comment by dineshsharmads** [comment]
To add some context:

We have a single tenant asp.net monolithic WebApp which is currently hosted on Azure VMs.
Each tenant runs in it's own Resource Group-VM-VNet and is completely isolated from other tenant.
We are looking into moving each tenant in one AKS cluster (production only), which won't be shared with any other application.
Database will be moved to Azure SQL.

Though we are assessing the risk of not having any isolation between the pods due to lack of Network policies, but also want to investigate if there is any other option to improve our security posture in this setup. Even if it is an application level change.

**Comment by MikkelHegn** [comment]
Hi @dineshsharmads - the only thing you can do today is to separate node pools on subnets and setup NSGs to block traffic between node pools - https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#add-a-node-pool-with-a-unique-subnet-preview. We support up to 10 node pools per cluster today.

Another path to explore is to use Virtual Kubelet to run the containers in ACI, however you'll still run in to the same network limitation in terms of what you can and cannot block. For ACI to AKS network connection you can only block using NSGs and ACI hosted containers will all reside on the same subnet, however the individual containers will be hosted in a multitenant secure isolation.

**Comment by MikkelHegn** [comment]
Closing for now, let us know if you have further questions.
