### ISSUE TITLE
az aks browse fails with 'Error from server (NotFound): pods "ubernetes-dashboard" not found'

### ISSUE THREAD

**Issue by jessebenson** [Azure/AKS#159]
After creating a new AKS cluster in East US, I try to use `az aks browse`, but it immediately fails:

```
%> az aks browse -g <resource-group> -n <cluster-name>
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
Error from server (NotFound): pods "ubernetes-dashboard-6d9c57c89c-mvc62" not found
%>
```

I can use kubectl to connect to the dashboard just fine using `kubectl proxy`.  The kubernetes-dashboard pod is running just fine, it looks like azure cli is using the wrong pod name (the string is bring truncated at the start).

```
%> kubectl get pods --namespace kube-system --output name --selector k8s-app=kubernetes-dashboard
pod/kubernetes-dashboard-6d9c57c89c-mvc62
%> kubectl port-forward kubernetes-dashboard-6d9c57c89c-mvc62 8001:9090 --namespace kube-system
Forwarding from 127.0.0.1:8001 -> 9090
Forwarding from [::1]:8001 -> 9090
```

**Comment by mboersma** [comment]
@jessebenson the CLI is assuming the format of the dashboard pod starts with `pods/`, but your command returned with a `pod/` prefix instead, causing this off-by-one parsing error. I'll fix the CLI to be more robust in this case--see Azure/azure-cli#5462.

Out of curiosity, what version of Kubernetes and `kubectl` returns that string? I've only seen the `pods/` prefix before.

**Comment by jessebenson** [comment]
Kubernetes is 1.8.6 but kubectl is older, 1.5.4.  Updating kubectl to 1.9.2 resolved the issue.  Thanks for the explanation!

**Comment by mboersma** [comment]
Great, I'm glad there's a workaround. The change you prompted is a good one regardless since `str(dashboard_pod)[5:].strip()` was a bit fragile.

**Comment by mboersma** [comment]
This more robust behavior should be in the next `az` CLI 2.0.27 in mid-February.

**Comment by TallOrderDev** [comment]
Commenting for others who come upon this. 

Had this issue pop up today, was using Az-cli 2.0.26 

Running `brew upgrade azure-cli` fixed this for me. Brought me up to az-cli 2.0.29
