### ISSUE TITLE
Attaching an ACR to the existing AKS cluster fails

### ISSUE THREAD

**Issue by smuthusa** [Azure/AKS#1590]
**What happened**:
Attaching the ACR to the existing AKS cluster fails. the azure cli fails with insufficient role. I have used service principal identity with the role owner & contributor.
The document says the owner can perform this operation, but does not talk about the scope.
https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Create a service principal with the role owner and contributor with the scope set to the resource group

1. az ad sp create-for-rbac --role=Owner --scopes=/subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/dev-resources
2. az role assignment create --assignee xxxx-xxxx-xxxx-xxxx --role "Owner" --role "Contributor" --scope=/subscriptions//xxxx-xxxx-xxxx-xxxx/resourceGroups/dev-resources
3. login with the above service principal
4. az aks update -n my-aks-cluster -g dev-resources --attach-acr my-acr-registry
Error message received
Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for ACR. Are you an Owner on this subscription?
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.10
- Size of cluster (how many worker nodes are in the cluster?) 8

**Comment by jluk** [comment]
@smuthusa the exact permissions needed are detailed in this document.

Could you retry with these steps and running the example script to use the SP?
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-service-principal#create-a-service-principal

I am going to close this, but if the document above does not work just comment and we can revisit.

**Comment by smuthusa** [comment]
please read the description carefully, I want to attach the ACR to AKS, but the documentation does not have any example of how to attach the ACR to an AKS using  the Service Principal.

**Comment by jluk** [comment]
The documentation explains you must be an owner or admin of the subscription because the --attach-acr command will create a new SP to be used. Is this the point of confusion? We can clarify the doc if so (cc @tomgeske).

Your commands being done create an SP first, but that SP is not used in the az aks create command. It fails on trying to create an SP as it looks like you are not an owner.

I added the documentation that enables setup without that permission, but this is called out on the doc here:
```
To avoid needing an Owner or Azure account administrator role, you can configure a service principal manually or use an existing service principal to authenticate ACR from AKS. For more information, see ACR authentication with service principals or Authenticate from Kubernetes with a pull secret.
```

Hope this helps.
