### ISSUE TITLE
Unable to change metric-resolution of metric-server deployment

### ISSUE THREAD

**Issue by jasperslot** [Azure/AKS#1595]
**What happened**: For monitoring containers cpu/mem actual usage I use the command "kubectl top pods --containers". Unfortunally this has only an update fequency of 60s, I wanted to lower this to for example 30s. To do this I have to change the metric-resolution property of the metric-server, so I tried this by modifying the metric-server deployment, but each time I try it is reverted to the default deployment. How can I change this?

**What you expected to happen**: Change the metric-resolution property to the value I set.

**How to reproduce it (as minimally and precisely as possible)**:
Edit & apply the 'metrics-server' deployment provisioned by AKS by adding "--metric-resolution=30s" tot the metric-server container commands. Like this:
`  containers:
    - name: metrics-server
      image: 'mcr.microsoft.com/oss/kubernetes/metrics-server:v0.3.5'
      command:
        - /metrics-server
        - --metric-resolution=30s
`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15.5
- Size of cluster (how many worker nodes are in the cluster?) 3

**Comment by palma21** [comment]
Hi, thanks for your feedback.

AKS does not support the configuration of system components. To ensure the SLOs and Quality of Service it needs control over the parameters of these components as well as to prevent any incorrect configuration that can compromise the cluster.

We'll take this ask into consideration.

**Comment by Gothic-X** [comment]
+1 on this request. I also need to set the metric-resolution to 30s
