### ISSUE TITLE
Clarification on the SLA for the AKS Control Plane needed

### ISSUE THREAD

**Issue by flamingboo** [Azure/AKS#1599]
We need some clarifications about the AKS SLA (Control Plane) as there seems some confusing information out there:

Before 2020/03, the SLA for the AKS Control Plane was as follows:
"Since AKS is free, no cost is available to reimburse, so AKS has no formal SLA. However, AKS seeks to maintain availability of at least 99.5% for the Kubernetes API server."

Since then, things have changed: 
https://azure.microsoft.com/en-us/support/legal/sla/kubernetes-service/v1_1/

"For customers who have purchased an Azure Kubernetes Service (AKS) Uptime SLA, we guarantee uptime of 99.95% for the Kubernetes API Server for AKS Clusters that use Azure Availability Zone and 99.9% for AKS Clusters that do not use Azure Availability Zone."

Questions:
1. Where can we go to purchase an AKS Uptime SLA???
   If so, does that mean Azure now offers a financially-backed SLA for the AKS API service?
   
2. Can we use AKS - without purchasing that AKS uptime SLA - and Azure still guarantee 99.95% availability (for the  control plane) when configured with Availability Zone?
It is understood that Azure VMs [agent nodes on which the workload run] are paid resources and they are backed by a financial SLA - based on Azure VM SLA.

Can you please shed light on the current and exact SLA offer?

Thanks

**Comment by ilanpillemer** [comment]
Considering the control plane has not now been down for us for over 24 hours, this is a good question. It went down with no warning and it's a ongoing horror story.

**Comment by jluk** [comment]
Hey @flamingboo this is a new capability offered by AKS as of this week. There will be more news to share on this tomorrow, but for now you can reference this document.

https://docs.microsoft.com/en-us/azure/aks/uptime-sla

We also have this issue opened for discussion #1603 - closing this one in favor of the other issue.
