### ISSUE TITLE
dashboard fails to show CPU graphs

### ISSUE THREAD

**Issue by squillace** [Azure/AKS#16]
This could be a point-in-time thing, but at the moment, no CPU graphs are displayed for my AKS cluster.
![aksdashboardwithoutcpu](https://user-images.githubusercontent.com/1422718/32254978-cf7564b6-be61-11e7-995a-dee3ee9ad094.png)

it should look like ACS, but without master information:

![cpuscreens](https://user-images.githubusercontent.com/1422718/32254989-e125c912-be61-11e7-94d9-f50c6ad99a7c.png)

**Comment by slack** [comment]
This has been fixed up.
