### ISSUE TITLE
Must define at least one system pool API 2020-03-01

### ISSUE THREAD

**Issue by adhodgson1** [Azure/AKS#1602]
Given a cluster with either one or many node pools where the Mode property is not set on any of them, with API 2020-03-01 we are getting an error "Must define at least one system pool."

Is this a bug or will I now need to explicitly call out system or user node pools when creating the pools?  If this is the case, if I run this template on an existing cluster where we have no system node pools, will it convert the specified pool to a system pool?

**Comment by adhodgson1** [comment]
Just tried running this on an existing cluster created using the 2020-02-01 template with several node pools but with no Mode property set on any of them.  Set the Mode property to System on the first node pool and ran the template using API 2020-03-01 but it didn't add the "kubernetes.azure.com/mode" node label to the nodes in that pool.  So answer to the last question is that it won't convert existing pools to System but will allow the template to run up in this state.

**Comment by jluk** [comment]
You must specify the mode when making ARM calls to the agentpoolapi with 2020-03-01 or greater, documented here:
https://docs.microsoft.com/en-us/azure/aks/use-system-pools#limitations

You should be able to convert an older pool to a system pool and the labels should be applied. Could you open a support request for the cluster in question so our on-call can take a look? cc @xizhamsft

**Comment by jluk** [comment]
Closing as we need more info, but adding the SR tag and I will revisit once more info comes in just leave a comment.
