### ISSUE TITLE
coredns: corefile config not adapted to custom dns VNET

### ISSUE THREAD

**Issue by aelmanaa** [Azure/AKS#1605]
Hello ,

we have our own dns servers on Azure and onpremise. Hence, we configured the DNS of our VNETs in custom mode, using the following:

1.  First:  Dns server deployed on AZure

1. Second: Dns server deployed onpremise

the order is important. In fact, the onpremise dns server is there only for redundancy. When started, the linux machines  contact the DHCP server in order to get the /etc/resolv.conf . The dns servers, are the same as on the config of the VNET and are treated sequentially by linux machines.
So far, so good.  However, I noticed that onpremise dns server are still getting queries and after investigation:

- Corefile of coredns deployed by AKS is:

```
ApiVersion: v1
data:
 Corefile: |
   .:53 {
       errors
       health
       kubernetes cluster.local in-addr.arpa ip6.arpa {
         pods insecure
         upstream
         fallthrough in-addr.arpa ip6.arpa
       }
       prometheus :9153
       forward . /etc/resolv.conf
       cache 30
       loop
       reload
       loadbalance
       import custom/*.override
   }
   import custom/*.server
kind: ConfigMap
```

-  Since the forwarding policy is not mentioned, coredns treats the dns servers randomly (as specified here: https://coredns.io/plugins/forward/) and that's why our onpremise server is still getting dns queries.

I think AKS corefile is too restrictive.  as workaround I'll have to specify in coredns-custom :

-  all our onprem zones

- all egress fqdn: MI databases, private endpoints, all egress endpoints used by AKS...ETc 

this seem really cumbersome.

**Comment by palma21** [comment]
Hi @aelmanaa, thank you for your feedback. 
Would you happen to have a proposal in mind for the corefile that would address your use case?

**Comment by aelmanaa** [comment]
Hi @palma21 

I was going to suggest to replace 

forward . /etc/resolv.conf

by

forward . /etc/resolv.conf {
policy sequential 
}

but by doing so ,you will impact all AKS users. Some of them prefer to have the load being balanced upon many forwarders.
I'd suggest to let people change the corefile rather than using custom files.  For instance ,in EKS ,one can directly update corefile (https://aws.amazon.com/premiumsupport/knowledge-center/eks-dns-failure/) .

is there any reason why you prevent direct changes to the corefile?

**Comment by aelmanaa** [comment]
Hello ,

what do you think about my answer of August 4th?

**Comment by aidanhl** [comment]
Hello, 

I ran across this issue, as we are also running in to a situation where we would like to modify the base corefile in AKS, and using custom-dns configmap does not work for our needs. Is there any update on being able to do that?


Thanks

**Comment by aelmanaa** [comment]
hello, don't close
