### ISSUE TITLE
VM has reported a failure when processing extension 'vmssCSE'. Error message: "Enable failed: failed to execute command: command terminated with exit status=50

### ISSUE THREAD

**Issue by nidiculageorge** [Azure/AKS#1607]
Can someone help on this issue. We had done some tweaking in the NSG for for AKS in outbound rules

![image](https://user-images.githubusercontent.com/43850474/82009823-fc8ee600-968d-11ea-9a88-8f1a0cd6fcda.png)

Is it because of this we are facing the issue

**Comment by jluk** [comment]
Error 50 can indicate there is no outbound internet and that your network setup is incorrect. Please revisit the NSG rules you have to ensure the cluster can reach outbound internet.

If you need more help please use Azure support with support tickets, we won't be able to diagnose this quickly on github. Closing as a result.
