### ISSUE TITLE
Support to Admission Controllers management

### ISSUE THREAD

**Issue by pjbgf** [Azure/AKS#161]
What's the story around Admission Controllers management? Would users be able to add/remove/configure the admission controllers for their own AKS clusters? Is that something coming for the GA version?

**Comment by slack** [comment]
Our current disposition is to ship with the recommended set of Admission Controllers for each Kubernetes release. Are there specific admission controllers you would like/need to see enabled?

**Comment by pjbgf** [comment]
@slack some of the admission controllers would be:

- ImagePolicyWebhook
- DenyEscalatingExec
- NamespaceExists
- NamespaceLifecycle
- PodSecurityPolicy
- ResourceQuota
- ServiceAccount

Do you mind confirming which ones are currently enabled? Also, would the cluster owners be able to opt-in/opt-out of specific controllers?

**Comment by jungho** [comment]
This would be a huge++.  With ACS today, you can update the manifest then restart the kubelet service.  As we won't have access to the cluster, some means to enable/disable admission controllers would be awesome.

**Comment by williamayerst** [comment]
This would be super-handy for automatic sidecar injection (i.e. for Istio)

**Comment by slack** [comment]
Update on this issue, we have enabled `Initializers`, `MutatingAdmissionWebhook`, and `ValidatingAdmissionWebhook` for 1.9+ clusters in AKS. We haven't opened up admission controller customization yet, but we have unlocked a bunch of scenarios with the above list.

**Comment by kmadel** [comment]
Is the Priority admission controller enabled? https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#priority Useful for overprovisioning cluster autoscaler.

**Comment by andresguisado** [comment]
Kubernetes recommends running the following admission control list:

* For 1.9v: `--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota`

* For 1.10v: same list but using different flag `--enable-admission-plugins=`

Further info [here]
(https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#is-there-a-recommended-set-of-admission-controllers-to-use)

Could we get the admission controllers that  Kubernetes recommends running?

**Comment by shanepeckham** [comment]
Can we enable the PoSecurityPolicy Admission Controller on AKS? From the documentation for 1.11 it says "Pod security policy control is implemented as an optional (but recommended) admission controller."

**Comment by seanmck** [comment]
Pod Security Policy is planned for later this year. Please add other requests to our feedback forum so we can prioritize:

https://aka.ms/aks/feedback

**Comment by andifalk** [comment]
@seanmck "Later this year" (2018) is almost over. Are there any new plans on when pod security policy is available? This is a critical part of securing kubernetes clusters.

> Pod Security Policy is planned for later this year. Please add other requests to our feedback forum so we can prioritize:
> 
> https://aka.ms/aks/feedback
