### ISSUE TITLE
Question regarding version of AKS, aks-engine used

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [Azure/AKS#1610]
**What happened**:
I am interested in knowing what is the relationship between the AKS version (like 2020-05-04) and the underlying `aks-engine` version (like 0.50.2). If my understanding is correct AKS uses `aks-engine` internally. Also I believe that for customers using the managed AKS service, the service gets upgraded behind the scenes without any user input. I also know that we can see the current version of the `aks-engine` used by checking the labels in the node-pools of the cluster.
**What you expected to happen**:
I hoped to see in the release notes of AKS as to which version of `aks-engine` it uses. Is it possible to use a latest version of `aks-engine` in Azure's managed AKS?
**How to reproduce it (as minimally and precisely as possible)**:
Going to the release notes of AKS and aks-engine repos gives no indication as to their link

**Anything else we need to know?**:
None
**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.7
- Size of cluster (how many worker nodes are in the cluster?): 4
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by seanmck** [comment]
The relationship between AKS and AKS-Engine is complex and somewhat fluid, so we have recently chosen not to publish their specific links to avoid creating confusion about what is/isn't supported in either. If you have specific questions about what's supported in AKS for a given release, feel free to open an issue for that.
