### ISSUE TITLE
Worker nodes based on ARM processors

### ISSUE THREAD

**Issue by zhouziyang** [Azure/AKS#1613]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by seanmck** [comment]
If/when ARM64 support is available for standard Azure VMs, we will investigate this. At the moment, this is not actionable so closing.

**Comment by seanmck** [comment]
Time to reopen!

https://azure.microsoft.com/en-us/blog/now-in-preview-azure-virtual-machines-with-ampere-altra-armbased-processors/
