### ISSUE TITLE
AKS deletes standalone gatekeeper V3 validatingwebhookconfiguration and CRDs

### ISSUE THREAD

**Issue by ruchikaguptaa** [Azure/AKS#1617]
**What happened**:
AKS deletes gatekeeper-validating-webhook-configuration validatingwebhookconfiguration and core CRDs configs.config.gatekeeper.sh, constrainttemplates.templates.gatekeeper.sh if you have gatekeeper v3 standalone installed with AKS. This will cause deletion of user created CRDs in turn. This is not an issue if you are using AKS gatekeeper addon.

**What you expected to happen**:
Gatekeeper validatingwebhookconfiguration and CRD are not deleted.

**How to reproduce it (as minimally and precisely as possible)**:
1. If you have an existing cluster with gatekeeper deployed to cluster (using deploy/gatekeeper.yaml or https://github.com/open-policy-agent/gatekeeper/blob/master/chart/gatekeeper-operator/Chart.yaml)

OR

1. Deploy gatekeeper to cluster (using deploy/gatekeeper.yaml or https://github.com/open-policy-agent/gatekeeper/blob/master/chart/gatekeeper-operator/Chart.yaml). 
2. Update AKS cluster control plane.

**Anything else we need to know?**:

**Mitigation**:
For latest version v3.1.0-beta.8 -
1. Redeploy gatekeeper to cluster (using deploy/gatekeeper.yaml or https://github.com/open-policy-agent/gatekeeper/blob/master/chart/gatekeeper-operator/Chart.yaml). This will recreate the missing resources.
2. Redeploy constraints and templates for policies.

For earlier gatekeeper versions - 
1. Manually remove finalizers https://github.com/open-policy-agent/gatekeeper#manually-removing-constraints
2. Redeploy gatekeeper to cluster (using deploy/gatekeeper.yaml or https://github.com/open-policy-agent/gatekeeper/blob/master/chart/gatekeeper-operator/Chart.yaml). This will recreate the missing resources.
3. Redeploy constraints and templates for policies.

**Fix**:
We have a fix that will not delete these resources if you have standalone gatekeeper installation. Once the fix is rolled out, recreate the resources in case they were deleted earlier. Going forward, they won't be deleted.

This is currently rolling out. We will update once the fix is completely rolled out. 

Regions where fix is rolled out:
* Eastus2euap
* West Central US
* Australia East
* Canada central
* UK South
* UK West
* South East Asia
* East Asia
* Australia South East
* Canada East
* West Europe
* North Europe
* Japan East
* Japan West
* West US
* West US 2
* East US 2
* South Central US
* North Central US
* Central US
* East US
* France Central
* France South
* South India
* Central India
* Korea Central
* Korea South
* South Africa North
* South Africa West
* Bazil South
* Germany North
* Germany West Central
* UAE North
* UAE Central
 * Switzerland North
* Switzerland West
* Nrway East
* Norway West

**Comment by porrascarlos802018** [comment]
just a follow up, do we have an ETA?

**Comment by ruchikaguptaa** [comment]
@porrascarlos802018 It should complete by early next week. The region will be updated as rollout completes.

**Comment by ruchikaguptaa** [comment]
The deployment has been completed.
