### ISSUE TITLE
cannot see kube-scheduler.log on aks master node

### ISSUE THREAD

**Issue by boraozkan** [Azure/AKS#1620]
I expand my cluster for troubleshooting nodes and logs by accessing ssh, I follow this doc:
https://docs.microsoft.com/en-us/azure/aks/ssh
**What happened**:
I can only can see kubelet logs on worker nodes so I use Log Analytics workspaces to diagnose into the master node logs thorugh my aks cluster
**What you expected to happen**:
I expect when I run this query and it said no data but `kube-apiserver` can retrieve some data

```
AzureDiagnostics
| where Category == "kube-scheduler"
| project log_s
```

**How to reproduce it (as minimally and precisely as possible)**:

you can login ssh master node and check under /var/log/kube-scheduler.log whether exist

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.18.2
- Size of cluster (how many worker nodes are in the cluster?)1 master 3 workers
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) db application
- Others:

**Comment by TomGeske** [comment]
Just to be sure. Did you turn on kube-scheduler category in your cluster diagnostic settings?

![image](https://user-images.githubusercontent.com/3658893/88528488-f9559600-cffe-11ea-83c7-27b1cc21a8dd.png)

**Comment by boraozkan** [comment]
yes I did, maybe I need to activate or check from cli by ssh to node, is there any way to see where is the directory of this logs in master nodes?
