### ISSUE TITLE
outbound-type userDefinedRouting does not work with system assigned managed identity (e.g. --enable-managed-identity)

### ISSUE THREAD

**Issue by borkod** [Azure/AKS#1622]
I followed the sample instructions for creating cluster egress with a custom UDRs, found [here](https://docs.microsoft.com/en-us/azure/aks/egress-outboundtype).

`az aks create` command as specified in the documentation does not work with `--outbound-type userDefinedRouting` and `--enable-managed-identity`.  It seems you must use the service principal /  client secret form of authentication.

Even after changing the command to use service principal and client secret, it still was failing with an error about a route table being associated with one of the subnets.

In order to resolve the issue I had to:
1. Execute again the [Associate the route table to AKS](https://docs.microsoft.com/en-us/azure/aks/egress-outboundtype#associate-the-route-table-to-aks) command.
2. Execute the `az aks create` command with service principal / client secret set.

If AKS with `--outbound-type userDefinedRouting` should support System assigned managed identities, then this is an issue. If this outbound type option requires service principal, then documentation should specify that as one of the requirements and limitations.

**Comment by jluk** [comment]
@borkod what networking option are you using and what error did you encounter when setting this up?

We are able to do this with Azure CNI and validated it is working.

**Comment by borkod** [comment]
@jluk I followed the instructions in the link exactly, so I was using Azure CNI. The only difference I tried was using system assigned identity. So I executed the aks command as:

```
az aks create -g $RG -n $AKS_NAME -l $LOC \
  --node-count 3 \
  --network-plugin azure --generate-ssh-keys \
  --service-cidr 192.168.0.0/16 \
  --dns-service-ip 192.168.0.10 \
  --docker-bridge-address 172.22.0.1/29 \
  --vnet-subnet-id $SUBNETID \
  --load-balancer-sku standard \
  --outbound-type userDefinedRouting \
  --api-server-authorized-ip-ranges $FWPUBLIC_IP \
  --enable-managed-identity
```

Sorry I didn't manage to copy the exact error, but it stated something along the lines "there is already a route table associated with subnet akssubnet"

When I used the service principal (i.e. I provided the `--service-principal` and `--client-secret`) instead of using `--enable-managed-identity`, it worked as expected.  Were you using the `--enable-managed-identity` flag?

I'll repeat the process again and see if I encounter the same error. If so, I'll come back here and paste the exact error.

**Comment by gtracer** [comment]
I couldn't repro. I ran a setup script using UDR + MSI (pasted part of it below) and it works.

Can you try again and see if you can repro and paste the error you get? Can you also send me your subscription, resource group and aks cluster name to gathirum at microsoft dot com?

 az aks create -g $RG -n $AKSNAME -l $LOC \
   --node-count 3 \
   --network-plugin $PLUGIN \
   --network-policy azure \
   --service-cidr $BASE_ADDRESS.5.0/24 \
   --dns-service-ip $BASE_ADDRESS.5.10 \
   --docker-bridge-address 172.17.0.1/16 \
   --vnet-subnet-id $SUBNETID \
   --enable-managed-identity \
   --load-balancer-sku standard \
   --outbound-type userDefinedRouting

**Comment by borkod** [comment]
Hello,

I repeated the steps again a few times. This time I was able to create the AKS cluster ok. However, when I tried to create the `internal-app` service, the external IP of the service was in `<pending>` state. Looking at the events, The following error showed up:

```
 Warning  SyncLoadBalancerFailed  28s (x4 over 63s)  service-controller  Error syncing load balancer: failed to ensure load balancer: network.SubnetsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '4f7751e8-6fe7-4d46-a10b-fdd6f038fe26' with object id '4f7751e8-6fe7-4d46-a10b-fdd6f038fe26' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/subnets/read' over scope '/subscriptions/***/resourceGroups/idk8s-rg/providers/Microsoft.Network/virtualNetworks/idk8svnet/subnets/idk8ssvcsubnet' or the scope is invalid. If access was recently granted, please refresh your credentials."
```
I then used:
```
az role assignment create --assignee 4f7751e8-6fe7-4d46-a10b-fdd6f038fe26 --scope $VNETID --role Contributor
```
to grant the permission.

That solved the SyncLoadBalancerFailed error.  I proceeded to use kubectl to deploy the example.yaml file. The application seems to deploy fine on the AKS and an external IP gets provisioned for the azure-vote-front service.

I then proceeded to use `azure network firewall nat-rule create` command to add the DNAT rule for the front end service. That succeeded ok.

I then tried to use the public ip to access the service, but seem to get 502 Bad Gateway HTTP error.

When I deploy everything using Service principal, it works fine.

I tried to compare the configurations of azure fw rules, NAT, load balancing, UDRs, etc between the deployment using UDR and service principal, but there doesn't seem to be anything obviously different or wrong.

Are you able to get a working application deployed using managed identity? Do you encounter any permission issues when trying to deploy Kubernetes services and provision an external ip (errors such as the one above)? Do you have to explicitly grant contributor role to the managed system identity on the VNet (that step is not listed in the documentation)?

**Comment by jluk** [comment]
@borkod in the effort to get the help you need, could you open a support ticket for this issue instead of relying on our github troubleshooting? Both features managed identity and outboundtype are now GA and valid for full Azure support.

I think we can get pretty deep into troubleshooting without significant progress on github. I'm going to close this issue for now, but will answer any questions about the support process as needed.
