### ISSUE TITLE
Availability of K8s 1.18 & removal of 1.15 as a supported version upon 1.18 GA

### ISSUE THREAD

**Issue by jluk** [Azure/AKS#1625]
**Current stage of release**: Preview, actively rolling GA as of 9/8. Depending on your region this feature is GA, the status of the issue will change when the GA updates are global.

This issue captures the motion of moving 1.18 to a GA state within AKS, implying the deprecation of 1.15 to keep in line with N-2 support policy. The new supported window range will become 1.16, 1.17, and 1.18 when this issue is closed. This will not be closed until issue #1442 has been closed and the regular notification process has been completed.

Example output from a cluster on 1.16.7. At the moment, AKS has 2 preview versions available (1.17 and 1.18).
```
KubernetesVersion    Upgrades
-------------------  --------------------------------
1.18.2(preview)      None available
1.18.1(preview)      1.18.2(preview)
1.17.3(preview)      1.18.1(preview), 1.18.2(preview)
1.16.7               1.17.3(preview)
1.15.10              1.16.7
1.15.7               1.15.10, 1.16.7
1.14.8               1.15.7, 1.15.10
1.14.7               1.14.8, 1.15.7, 1.15.10
```

**Comment by jluk** [comment]
Globally released as part of https://github.com/Azure/AKS/releases/tag/2020-05-11

**Comment by jluk** [comment]
ETA for GA is August, per AKS supported versions calendar

https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions#aks-kubernetes-release-calendar

**Comment by timdeluxe** [comment]
@jluk @palma21 Can you tell, when it is finally released? We already have nearly mid of september and we need 1.18 urgently, but also don't want to run on a preview.

**Comment by jluk** [comment]
@timdeluxe thanks for the ping, as an update this is actively rolling out now as of 9/8. We had a minor delay due to safe deployment requirements and delays in our publishing pipeline, but it should be globally set as GA mid-next week.

Apologies for the delay, if you need to urgently run on 1.18 you can upgrade now and as the update of version status from preview to GA won't impact any functionality. Our on-call/support teams are prepared to support 1.18 as GA. Hope this helps.

**Comment by valkolaci** [comment]
According to [https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#os-configuration-preview](https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#os-configuration-preview)
"Node pools on a supported Kubernetes version less than 1.18 receive AKS Ubuntu 16.04 as the node image, but will be updated to AKS Ubuntu 18.04 once the node pool Kubernetes version is updated to v1.18 or greater."

I expected the upgrade of the worker nodes to end up with Ubuntu 18.04. This is not the case... Did I misunderstand this, or is this upgrade gone wrong?

```
$ kubectl get node -o wide
NAME                              STATUS   ROLES   AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-worker1-40335534-vmss000004   Ready    agent   6h21m   v1.18.8   10.240.0.35   <none>        Ubuntu 16.04.7 LTS   4.15.0-1092-azure   docker://19.3.12

```

**Comment by jluk** [comment]
Moving this issue to GA and complete as the rollout for 1.18 GA should be global now.

@palma21 can you speak to the question from @valkolaci ?

**Comment by devteng** [comment]
I have the same issue as @valkolaci. I still see Ubuntu 16 as the OS when deploying a new AKS 1.18.6 last week. 

I just saw 1.18.8 as an upgradable version and will try to use aks upgrade and see if it upgrades the OS to Ubuntu 18.

**Comment by devteng** [comment]
AKS upgrade is still in progress on my side, but it looks like the OS is still on Ubuntu 16:
aks-ubuntu18pool-14147194-vmss000006   Ready                      agent   85d   v1.18.8   10.55.6.24    <none>        Ubuntu 16.04.7 LTS   4.15.0-1092-azure   docker://19.3.12
aks-ubuntu18pool-14147194-vmss000008   Ready                      agent   85d   v1.18.8   10.55.7.7     <none>        Ubuntu 16.04.7 LTS   4.15.0-1092-azure   docker://19.3.12
aks-ubuntu18pool-14147194-vmss00001o   Ready,SchedulingDisabled   agent   58d   v1.18.6   10.55.4.15    <none>        Ubuntu 16.04.6 LTS   4.15.0-1092-azure   docker://3.0.10+azure
aks-ubuntu18pool-14147194-vmss00001x   Ready                      agent   57d   v1.18.6   10.55.5.17    <none>        Ubuntu 16.04.6 LTS   4.15.0-1092-azure   docker://3.0.10+azure

**Comment by timdeluxe** [comment]
Yep, OS ist still Ubuntu 16. We recently did upgrade to 1.18.8 and are still with Ubuntu 16.

**Comment by devteng** [comment]
Hi @palma21, would you have any comment on this? Thank you!

**Comment by palma21** [comment]
Yes that is correct, the release had not finished yet (ETA was the 18th) which means the upgrades before wouldn't land on 18.04. We are now about to turn on the feature toggle since the release has finished but want to provide you with an option if you're already in 18.8 (you can still use the preview experience to get 18.04 and that will give you a supported cluster nonetheless).

I'll post here, when both actions above are completed

**Comment by akramwaseem** [comment]
@palma21 -- Saw the announcement yesterday about 18.04 here: https://azure.microsoft.com/en-us/updates/ga-aks-support-for-new-base-image-ubuntu-1804/

I did try to bring up a new cluster with v1.18.6 and it still gives me Ubuntu 16.04.7 LTS
```
NAME                                STATUS   ROLES   AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-nodepool1-14147194-vmss000000   Ready    agent   3m57s   v1.18.6   10.241.8.4    <none>        Ubuntu 16.04.7 LTS   4.15.0-1092-azure   docker://19.3.12
aks-nodepool1-14147194-vmss000001   Ready    agent   2m32s   v1.18.6   10.241.8.35   <none>        Ubuntu 16.04.7 LTS   4.15.0-1092-azure   docker://19.3.12
aks-nodepool1-14147194-vmss000002   Ready    agent   3m57s   v1.18.6   10.241.8.66   <none>        Ubuntu 16.04.7 LTS   4.15.0-1092-azure   docker://19.3.12
```

so, I tried upgrading it to v1.18.8 and I still see 

```
NAME                                STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-nodepool1-14147194-vmss000000   Ready    agent   31m   v1.18.8   10.241.8.4    <none>        Ubuntu 16.04.7 LTS   4.15.0-1092-azure   docker://19.3.12
aks-nodepool1-14147194-vmss000001   Ready    agent   29m   v1.18.8   10.241.8.35   <none>        Ubuntu 16.04.7 LTS   4.15.0-1092-azure   docker://19.3.12
aks-nodepool1-14147194-vmss000002   Ready    agent   31m   v1.18.8   10.241.8.66   <none>        Ubuntu 16.04.7 LTS   4.15.0-1092-azure   docker://19.3.12

```
Can you provide an update please ?

**Comment by palma21** [comment]
This Issue is about k8s 1.18, not 18.04 there's an update on the 18.04 item, it's still rolling it's a bit delayed but should be concluded by end of next week or early the following.

**Comment by valkolaci** [comment]
My question was why the documentation page suggests the two things are connected when apparently they are not...

**Comment by palma21** [comment]
They are totally connected, but the releases are not aligned due to delay on 1804, the documentation should be saying that you only get 18.04 by default on 1.18 clusters which is true, you'll never get it by default on older clusters, and this is the the version you'll get from now on from 1.18+. But that is only after 18.04 GA completes the rollout
