### ISSUE TITLE
cannot update coredns configmap on aks cluster

### ISSUE THREAD

**Issue by boraozkan** [Azure/AKS#1628]
**What happened**:
I want to see logs on coredns as my zookeeper cannot resolve zookeeper cluster hostnames but when I add log to coredns configmaps it erase it and not add this log to configmap
**What you expected to happen**:
to see logs
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.14.8
- Size of cluster (how many worker nodes are in the cluster?)4
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by neumanndaniel** [comment]
Hi,

please take a look at the official docs: https://docs.microsoft.com/en-us/azure/aks/coredns-custom

You cannot change the ConfigMap `coredns`, but you can provide your own configuration via the ConfigMap `coredns-custom` and also override settings.

For overriding settings see also: https://www.danielstechblog.io/configuration-options-for-coredns-in-azure-kubernetes-service/

**Comment by neumanndaniel** [comment]
Don't know if this has been fixed now in AKS for CoreDNS, but you might need to run `kubectl -n kube-system rollout restart deployment coredns` to apply the configuration changes you made in the ConfigMap.

**Comment by boraozkan** [comment]
ok thank you!, it works, here is the `coredns-custom.yaml`

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s-app: kube-dns
  name: coredns-custom
  namespace: kube-system
data:
  Corefile.override: |
        log 
```

And after needs to restart I think( I immediately delete pod and deployment auto-create a new one) and the expected output when you check the logs are there

```
[INFO] 10.240.0.73:44068 - 22506 "AAAA IN 504bf5a1-2d01-476b-9631-999fda8b2be6.oms.opinsights.azure.com.svc.cluster.local. udp 97 false 512" NXDOMAIN qr,aa,rd 190 0.0001857s
[INFO] 10.240.0.73:36429 - 65323 "A IN 504bf5a1-2d01-476b-9631-999fda8b2be6.oms.opinsights.azure.com.bclfwvlgp4jexkldgvm0wvibhh.zx.internal.cloudapp.net. udp 131 false 512" NXDOMAIN qr,rd,ra 272 0.006936617s
[INFO] 10.240.0.73:36429 - 63796 "AAAA IN 504bf5a1-2d01-476b-9631-999fda8b2be6.oms.opinsights.azure.com.bclfwvlgp4jexkldgvm0wvibhh.zx.internal.cloudapp.net. udp 131 false 512" NXDOMAIN qr,rd,ra 272 0.006996517s
[INFO] 10.240.0.11:56389 - 8011 "A IN chi-vizlib-dashboard-sharded1-dashboard03-1-0.ch-test03.svc.cluster.local. udp 91 false 512" NOERROR qr,aa,rd 180 0.000210801s
[INFO] 10.240.0.11:52588 - 36706 "A IN chi-vizlib-dashboard-sharded1-dashboard03-2-0.ch-test03.svc.cluster.local. udp 91 false 512" NOERROR qr,aa,rd 180 0.000147001s
[INFO] 10.240.0.11:35713 - 31322 "A IN chi-vizlib-dashboard-sharded1-dashboard03-3-0.ch-test03.svc.cluster.local. udp 91 false 512" NOERROR qr,aa,rd 180 0.0001216s
[INFO] 10.240.0.13:55222 - 2389 "A IN chi-vizlib-dashboard-sharded1-dashboard03-3-0.ch-test03.svc.cluster.local. udp 91 false 512" NOERROR qr,aa,rd 180 0.0001268s
[INFO] 10.240.0.73:42909 - 43906 "A IN 504bf5a1-2d01-476b-9631-999fda8b2be6.ods.opinsights.azure.com.cluster.local. udp 93 false 512" NXDOMAIN qr,aa,rd 186 0.000260401s
[INFO] 10.240.0.73:42909 - 17288 "AAAA IN 504bf5a1-2d01-476b-9631-999fda8b2be6.ods.opinsights.azure.com.cluster.local. udp 93 false 512" NXDOMAIN qr,aa,rd 186 0.0001556s
```
