### ISSUE TITLE
AMD VM support

### ISSUE THREAD

**Issue by atrauzzi** [Azure/AKS#1630]
Hey there!

Just wanted to note that I'd love to see support for AMD-based VMs in AKS!

**Comment by zhiweiv** [comment]
I guess it is supported already? We have been using E2a_v4 for quite a long time.

**Comment by atrauzzi** [comment]
@zhiweiv - Which region are you using?

**Comment by zhiweiv** [comment]
See https://github.com/Azure/AKS/issues/1478, you can create aks cluster or add node pool by cli.

**Comment by jluk** [comment]
@zhiweiv is correct, this is a portal gap which is discussed on tissue #1478 closing in favor of consolidating to that issue if the gap if E/D series
