### ISSUE TITLE
Cannot access pod logs dial tcp cluster IP:443: connect: connection refused

### ISSUE THREAD

**Issue by Karolwww** [Azure/AKS#1632]
**What happened**:
I cannot access logs of pods located in one cluster node while on first node all logs are accessible
[
![image](https://user-images.githubusercontent.com/31865101/82825482-9d11b100-9eab-11ea-87fc-e910e9d2cecc.png)
](url)
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
›*Environment**:
- Kubernetes version (use `kubectl version`): 1.16.7
- Size of cluster (how many worker nodes are in the cluster?) 2 node cluster
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by palma21** [comment]
Please see:

https://docs.microsoft.com/en-us/azure/aks/troubleshooting#im-receiving-tcp-timeouts-when-using-kubectl-or-other-third-party-tools-connecting-to-the-api-server

and 

https://docs.microsoft.com/en-us/azure/aks/troubleshooting#im-receiving-tcp-timeouts-such-as-dial-tcp-node_ip10250-io-timeout

For your issue.
