### ISSUE TITLE
System Assigned Managed Identity for nodes instead of User Assigned

### ISSUE THREAD

**Issue by muellermatthias** [Azure/AKS#1633]
I'm currently testing the [CSI Secret Store project](https://github.com/Azure/secrets-store-csi-driver-provider-azure) for Azure and I wanted to use manged identity for that.
I provisioned a new cluster, which will automatically assign a User Assigned Identity to the VMSS.
Using the project together with a User Assigned Identity requires you to put the Identity-ID and your secrets in the same code base, which is not great, or you need to dynamically fetch the ID before your deployment, which is not great as well.
I still can use a service principal as an alternative, but I wonder why the AKS uses an User Assigned Identity for my VMSS. A System Assigned Identity should fine as well, right?

**Comment by TomGeske** [comment]
@muellermatthias: Not sure I understand correctly. You can use your own user assigned MI, assign it to your VMSS and configure CSI driver to use it. More details are [here](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/user-assigned-msi-mode.md)

**Comment by muellermatthias** [comment]
@TomGeske Using a user assigned MI works for me. That's not the problem. But using a system-assigned MI would simplify the deployment process a lot.
Are there any plans on supporting system-assigned MIs instead of user-assigned MIs or is this technically not possible?

**Comment by TomGeske** [comment]
Are you talking about a MI enabled cluster or SP cluster? For security reason you may only want to use a MI that has access to your KeyVault. The System-assigned MI on MI enabled clusters has a broad set of permissions used for infrastructure operations like managing your nodes and network. It’s not recommended to use for KeyVault access.

**Comment by muellermatthias** [comment]
@TomGeske I didn't thought about this security issue, which makes the solution I wanted unfortunately quite unsuitable.
Thanks for the time and help.
