### ISSUE TITLE
TTL controller

### ISSUE THREAD

**Issue by SkinyMonkey** [Azure/AKS#1634]
**What happened**:
I checked for the alpha feature TTL Controller for AKS but could not find any news about it.

**What you expected to happen**:
Being able to use TTL's do delete jobs automatically

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.8

**Comment by GangRobinNiu** [comment]
any follow-up on this request? It is a useful feature we want to use too in AKS.

**Comment by palma21** [comment]
We don't support alpha features on AKS. We are considering providing the possibility to create sandbox cluster with alpha features enabled _for testing purposes_. As managed service we rely on stable or mature betas to guarantee our QoS.

We will be happy to consider including it early as soon as it graduates to beta on that k8s version.

I will mark this as feature request assuming the feature graduates to beta within the next semester.

**Comment by tomstockton** [comment]
Is there a recommended alternative method for cleaning up old k8s jobs in the absence of this alpha feature being available on AKS?

**Comment by MattMencel** [comment]
@tomstockton take a look at [cleanup-operator](https://github.com/lwolf/kube-cleanup-operator). It's what I'm using currently and I'm pretty happy with it.

**Comment by maartenmensink** [comment]
Any news on this. The [TTLController ](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/)has reached beta in Kubernetes 1.21 

![image](https://user-images.githubusercontent.com/339653/115027039-7d201d00-9ec3-11eb-9d65-c6707b911864.png)

**Comment by artbegolli** [comment]
definitely interested in this - any ideas whether it'll be available for 1.21?

**Comment by nc-ruth** [comment]
Any news on this?

**Comment by 3schwartz** [comment]
Hi
This feature sounds awesome - could it be added in next release?

**Comment by MarekStrejczek-TomTom** [comment]
Interested in seeing TTL Controller available on AKS.

**Comment by dan-leanix** [comment]
@palma21 Any news on that? It is still not available on AKS running Kubernetes version 1.21.2.

**Comment by zhongyi-zhang** [comment]
+1 to this feature request :)

**Comment by dan-leanix** [comment]
Short update on that. It is available in 1.21.2. Got the confirmation from Azure Support. So, we are currently using it.
