### ISSUE TITLE
Service not accessible after expose using Standard LB with AKS

### ISSUE THREAD

**Issue by blessedwithsins** [Azure/AKS#1641]
I'm having an AKS Cluster with Azure CNI Network Plugin and Standard LB. Whenever I expose my service as type LoadBalancer, it should be accessible via Public IP and exposed port. However, this doesn't work. 

wardaddy@wardaddy-local:~/aks-deploy$ k get deploy,po,svc -o wide
NAME                               READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES         SELECTOR
deployment.apps/nginx-deployment   3/3     3            3           47m   nginx        nginx:1.14.2   app=nginx

NAME                                    READY   STATUS    RESTARTS   AGE   IP            NODE                               NOMINATED NODE   READINESS GATES
pod/nginx-deployment-574b87c764-2hp5x   1/1     Running   0          31m   10.240.0.45   aks-wardaddy-16949223-vmss000001   <none>           <none>
pod/nginx-deployment-574b87c764-fltkt   1/1     Running   0          31m   10.240.0.8    aks-wardaddy-16949223-vmss000000   <none>           <none>
pod/nginx-deployment-574b87c764-qvbwd   1/1     Running   0          31m   10.240.0.74   aks-wardaddy-16949223-vmss000002   <none>           <none>

NAME                TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)        AGE   SELECTOR
service/nginx-svc   LoadBalancer   10.0.192.135   13.89.115.192   80:32151/TCP   14m   app=nginx
wardaddy@wardaddy-local:~/aks-deploy$

wardaddy@wardaddy-local:~/aks-deploy$ az aks show |grep -i loadbalancer
    "loadBalancerProfile": {
    "loadBalancerSku": "Standard",
    "outboundType": "loadBalancer",
wardaddy@wardaddy-local:~/aks-deploy$ 

How can i get it fixed?

**Comment by jluk** [comment]
@blessedwithsins if you are having issues troubleshooting a service, please open a support request. It will be difficult for us to diagnose efficiently on github, but an Azure engineer can certainly help you with this. Closing in favor of SR.

**Comment by blessedwithsins** [comment]
@jluk I'm part of AKS support team. Standard document doesn't correctly depict the scenario and it has been seen multiple times while I configured this with my colleague also.

**Comment by jluk** [comment]
@blessedwithsins follow-up internally with Chirag Pavecha please if you believe it's a product issue.
