### ISSUE TITLE
nodelocaldns aks routing issue

### ISSUE THREAD

**Issue by luigibk** [Azure/AKS#1642]
Hi,
I am trying to install nodelocaldns on AKS 
https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/

I have tried this on Kubernetes 1.16.7 and 1.18.2. The installation itself seems ok  but then dns resolution does not work with the default pod resolv.conf settings whereas it should as far as I understand. It does work only if I point the pod resolver client (e.g. dig) to the link local address.

At the end of the installation, (tried both Ubuntu 16.04 and Ubuntu 18.04) I have a nodelocaldns interface created

```
nodelocaldns: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default
    link/ether 1a:a2:27:b6:2a:5e brd ff:ff:ff:ff:ff:ff
    inet 169.254.20.10/32 brd 169.254.20.10 scope global nodelocaldns
       valid_lft forever preferred_lft forever
    inet 10.0.0.10/32 brd 10.0.0.10 scope global nodelocaldns
       valid_lft forever preferred_lft forever
```

where 10.0.0.10 is the cluster-dns. Also all the iptables entries look ok to me:

```
*raw
:PREROUTING ACCEPT [40133:30257701]
:OUTPUT ACCEPT [5378:1385717]
-A PREROUTING -d 10.0.0.10/32 -p udp -m udp --dport 53 -j NOTRACK
-A PREROUTING -d 10.0.0.10/32 -p tcp -m tcp --dport 53 -j NOTRACK
-A PREROUTING -d 169.254.20.10/32 -p udp -m udp --dport 53 -j NOTRACK
-A PREROUTING -d 169.254.20.10/32 -p tcp -m tcp --dport 53 -j NOTRACK
-A OUTPUT -s 10.0.0.10/32 -p tcp -m tcp --sport 8080 -j NOTRACK
-A OUTPUT -d 10.0.0.10/32 -p tcp -m tcp --dport 8080 -j NOTRACK
-A OUTPUT -d 10.0.0.10/32 -p udp -m udp --dport 53 -j NOTRACK
-A OUTPUT -d 10.0.0.10/32 -p tcp -m tcp --dport 53 -j NOTRACK
-A OUTPUT -s 10.0.0.10/32 -p udp -m udp --sport 53 -j NOTRACK
-A OUTPUT -s 10.0.0.10/32 -p tcp -m tcp --sport 53 -j NOTRACK
-A OUTPUT -s 169.254.20.10/32 -p tcp -m tcp --sport 8080 -j NOTRACK
-A OUTPUT -d 169.254.20.10/32 -p tcp -m tcp --dport 8080 -j NOTRACK
-A OUTPUT -d 169.254.20.10/32 -p udp -m udp --dport 53 -j NOTRACK
-A OUTPUT -d 169.254.20.10/32 -p tcp -m tcp --dport 53 -j NOTRACK
-A OUTPUT -s 169.254.20.10/32 -p udp -m udp --sport 53 -j NOTRACK
-A OUTPUT -s 169.254.20.10/32 -p tcp -m tcp --sport 53 -j NOTRACK

*filter
-A INPUT -d 10.0.0.10/32 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -d 10.0.0.10/32 -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -d 169.254.20.10/32 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -d 169.254.20.10/32 -p tcp -m tcp --dport 53 -j ACCEPT

-A OUTPUT -s 10.0.0.10/32 -p udp -m udp --sport 53 -j ACCEPT
-A OUTPUT -s 10.0.0.10/32 -p tcp -m tcp --sport 53 -j ACCEPT
-A OUTPUT -s 169.254.20.10/32 -p udp -m udp --sport 53 -j ACCEPT
-A OUTPUT -s 169.254.20.10/32 -p tcp -m tcp --sport 53 -j ACCEPT
```

but then resolving hostnames from a pod I get:

```
dnstools# dig +short @169.254.20.10  google.com
216.58.204.238

dnstools# dig +short @10.0.0.10  google.com
;; connection timed out; no servers could be reached

dnstools# dig +short google.com
;; connection timed out; no servers could be reached
```

However Dns resolution work from the host if I use either @10.0.0.10 or @169.254.20.10

From what I can see from the iptables logs I get that packets originating from pods and destined to 10.0.0.10 are forwarded to the azure0 interface

May 30 01:54:34 aks-nodepool-abcdefgh-vmss000000 kernel: [840499.620248] dns-filter-svc:IN=azure0 OUT=azure0 PHYSIN=azv47a212ccbff PHYSOUT=eth0 MAC=12:34:56:78:9a:bc:6a:3d:bc:b9:99:86:08:00 SRC=10.10.2.18 DST=10.0.0.10 LEN=79 TOS=0x00 PREC=0x00 TTL=64 ID=2635 PROTO=UDP SPT=41119 DPT=53 LEN=59

whereas I believe they should only traverse the input chain to the nodelocaldns interface, which is what they do for dns queries to 169.254.10.10. 

```
sudo ip route list table local
local 10.0.0.10 dev nodelocaldns  proto kernel  scope host  src 10.0.0.10 
broadcast 10.10.2.0 dev azure0  proto kernel  scope link  src 10.10.2.4 
local 10.10.2.4 dev azure0  proto kernel  scope host  src 10.10.2.4 
broadcast 10.10.3.255 dev azure0  proto kernel  scope link  src 10.10.2.4 
broadcast 127.0.0.0 dev lo  proto kernel  scope link  src 127.0.0.1 
local 127.0.0.0/8 dev lo  proto kernel  scope host  src 127.0.0.1 
local 127.0.0.1 dev lo  proto kernel  scope host  src 127.0.0.1 
broadcast 127.255.255.255 dev lo  proto kernel  scope link  src 127.0.0.1 
local 169.254.20.10 dev nodelocaldns  proto kernel  scope host  src 169.254.20.10 
```

I suspect this is specific to AKS, but I haven't figured out why.

**Comment by luigibk** [comment]
Update: all of the above issue seems to be related to the Azure CNI plugin.
https://github.com/Azure/azure-container-networking

I have no such problem if I use Calico.

**Comment by saiyan86** [comment]
Hi @luigibk 

Could you please try running this command on the problematic node and see if it works?
```
sudo ebtables -t broute -A BROUTING --ip-dst 169.254.20.10 -p IPv4 -j redirect --redirect-target ACCEPT
```

**Comment by luigibk** [comment]
Hi @saiyan86 

Thanks for getting back to me. Just to be clear, the problem is not just a single node. The entire cluster (i.e. all nodes) is affected. 
I don't have a cluster to test what you suggest at the moment, but I don't think it will work as all the pods are configured to still use the "standard" cluster-dns ip (10.0.0.10), whereas that rule only deals with the local-link address 169.254.20.10.
In fact on the same note I am not keen on the solution you propose in:
https://github.com/feiskyer/kubernetes-handbook/blob/master/examples/nodelocaldns/nodelocaldns-azure-cni.yaml
as that changes the kubelet configuration in a way that makes it hard to fall back to the default (CoreDNS based) configuration. One of the great things of NodeLocalDNS imo is that it can be easily reverted.
By the way, from my experience with knode, I wonder if without rebooting the node, what you do in that initContainer might crash the nmi daemonset (see: https://github.com/juan-lee/knode/issues/4).
I might have a test cluster available soon to test. In that case I'll give you an update as soon as that happens.

**Comment by luigibk** [comment]
Hi @saiyan86 

I have a working implementation and a PR for NodelocalDNS + (a very small) one for Kubernetes:

https://github.com/kubernetes/kubernetes/pull/92440

https://github.com/luigibk/dns/pull/1

the NodelocalDNS one is still only on my fork as it depends on the first one (even if it's not a big problem as it's just a change to the ebtables utility in there).

I have this running on one of our clusters. Looks good so far.

**Comment by timja** [comment]
cc @feiskyer ^^

**Comment by luigibk** [comment]
All PRs merged:

https://github.com/kubernetes/utils/pull/175

https://github.com/kubernetes/dns/pull/390

I am going to close this.
