### ISSUE TITLE
Not able to create HLF consortium on Azure Kubernetes Services when resource group has other resources

### ISSUE THREAD

**Issue by saurabhsawant460** [Azure/AKS#1643]
Hi,
In current Hyperledger Fabric on Azure Kubernetes Service release [2020-05-25 / 2020-05-18], AKS is allowing to create the resources in empty resource group only, while in previous releases, AKS allows to create the resources in empty resource group as well as resource group with resources also.
 
Is there any changes in pre-requisite for deployment of HLF components using AKS ?
Is it mandatory to have empty resource group for every HLF component deployment?

![AKSissue](https://user-images.githubusercontent.com/56384894/83423503-b0db8b00-a448-11ea-85cc-009aff39091b.png)

**Comment by jluk** [comment]
AKS requires the managed resource group to be empty and this has always been a requirement as AKS makes cleanup operations on the MC resource group, this may be an updated validation from the HLF team if that has changed recently. 

Given this repo contains only AKS team members, please route the HLF feedback to their team. Closing as a result.
