### ISSUE TITLE
Security Centre Monitoring Agent not installed in Scale Sets

### ISSUE THREAD

**Issue by bhicks329** [Azure/AKS#1644]
When creating an AKS Cluster with Scale Sets, the monitoring agent relied on by Security Centre is not installed

Following guidance from MS, we have been advised we need to manually click "Fix Now" to install the agents on the nodes. This feels like an anti-pattern for a managed build with auto-scaling nodes.

**Comment by BlueBasher** [comment]
We have experienced the same issue. IMHO there should be more configuration on an AKS nodepool that is set on the underlying VM Scaleset. Being able to specify the monitoring or diagnostic settings should be the minimum configuration you should be able to do.

**Comment by TomGeske** [comment]
+@mayaherskovic

**Comment by mayaherskovic** [comment]
Security Center and AKS are working to improve the current experience and make it more cloud native. ASC recommendation to install “Monitoring Agent” is referring to a security agent for security data collection that Security Center depends on.  
We acknowledge the confusion here and I can share that we are currently working to provide auto provisioning option to save this effort and management from customers.

**Comment by phealy** [comment]
@mayaherskovic @miwithro Could you please provide an update here?

**Comment by mayaherskovic** [comment]
Yes. Azure Defender is working on a new daemonset that will be integrated to AKS as an AKS profile. The new daemonset will replace the need to install Log Analytics agent on AKS nodes and will be supported on all AKS clusters. Targeting to preview this during 2021
