### ISSUE TITLE
AKS v1.16.9 Dashboard Login not working with RBAC (AAD)

### ISSUE THREAD

**Issue by mac8005** [Azure/AKS#1645]
**What happened:**
Created new Cluster with v1.16.9 with RBAC enabled. Created a ClusterRoleBinding to Bind a Azure AD Group to cluster-admin Role.
kubectl get pods works finde after Login with my Azure Account. Trying to access the Kubernetes Dashboard fails at the Login screen. 
Neither the Config Option nor the Token Option works.
Tried to use the access-token from the kube config and also a token which was issued with: `az account get-access-token --query accessToken -o tsv
`
If i try it using the Admin Credentials it is working fine.

**What you expected to happen:**
Kubernetes dashboard is working with RBAC (AAD)

**How to reproduce it (as minimally and precisely as possible):**

Use either az aks browse or kubectl proxy to access dashboard login page.
Once on dashboard login screen, enter a valid authentication token or kube config file. 
Click the login button

**Environment:**

Kubernetes version (use kubectl version): v1.17.0 
Az CLI version: 2.5.1
Size of cluster (how many worker nodes are in the cluster?): 3 nodes

**Comment by jluk** [comment]
@mac8005 as part of the v2.0 dashboard release, you can no longer use the service account unless you pass the bearer token with valid permissions.

Please pass the admin kubeconfig which will work as long as the access tokens are valid, not sure if that's what you tried above.

for Azure AD enabled clusters, you can retrieve your AAD token with the following command as well. Validate you have replaced the resource group and cluster name in the command.

```
## Update <RESOURCE_GROUP and <AKS_NAME> with your input.

kubectl config view -o jsonpath='{.users[?(@.name == "clusterUser_<RESOURCE GROUP>_<AKS_NAME>")].user.auth-provider.config.access-token}'
```

**Comment by mac8005** [comment]
@jluk 
Exactly. I don't want to use service account. I want that the Role Membership of the AAD User defines the permissions and reflects to the actions he can perform in the Dashboards.

Access Dashboard using **Chrome** and **Cluster Admin Credentials Token** works  :white_check_mark:
Access Dashboard using **Chrome** and **AAD User Access-Token from kube config** does not work :x:
Access Dashboard using **Edge** and **AAD User Access-Token from kube config** does not work :x:
Access Dashboard using **Edge** and **AAD User Access-Token accessed with `az account get-access-token --query accessToken -o tsv`** works :white_check_mark:

**Comment by palma21** [comment]
@mac8005 I just tested this and it worked for me. Only difference is that I binded to a user and not a group.

Could you test like this as well or open a support ticket?

Also, this might suit you better moving forward: https://azure.microsoft.com/en-us/updates/kubernetes-resource-view-is-in-public-preview/
