### ISSUE TITLE
Scale up is not triggered leaving pod in pending state forever

### ISSUE THREAD

**Issue by sephriot** [Azure/AKS#1648]
**What happened**:
Pod stuck in pending state forever

**What you expected to happen**:
Cluster autoscaler provision additional nodes (scale up).
Pod is scheduled on one of available nodes.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run AKS spanning across 3 Availablity Zones with cluster autoscaler enabled (min nodes 3, max nodes 50).
2. Create a StatefulSet with a PersistentVolume - 1 Pod (instance) (e.g. Prometheus server running as StatefulSet).
3. Drain node on which Prometheus Server Pod is running.
4. Prometheus Server Pod is stuck in Pending state.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.9
- Size of cluster (how many worker nodes are in the cluster?): 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Prometheus Server running as StatefulSet (literaly any other StatefulSet with Persistent Volume)
- Others: None

**Comment by marwanad** [comment]
@sephriot  can you describe a pod? There should be an event indicating why the pod didn't trigger a scaleup

**Comment by sephriot** [comment]
| Type  | Reason | Age | From | Message |
| ------------- | ------------- | ------------- | ------------- | ------------- | 
| Normal  | NotTriggerScaleUp  | 88s  | cluster-autoscaler  | pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 node(s) had no available volume zone  |
| Warning  | FailedScheduling  | 13s (x3 over 95s)  | default-scheduler  | 0/3 nodes are available: 1 Insufficient cpu, 1 node(s) had volume node affinity conflict, 1 node(s) were unschedulable |

**Comment by marwanad** [comment]
The `NotTriggerScaleUp` mentions why the scheduling predicates failed `1 node(s) had no available volume zone`. This is a `NoVolumeZoneConflict` predicate failure. 

The core logic of CA works by taking a random existing node and assuming any new node in the same group will look exactly the same.  More info [here](https://github.com/kubernetes/autoscaler/blob/d4a6664b389b052293de8f2c0d16839564911e1f/cluster-autoscaler/FAQ.md#i-have-a-couple-of-pending-pods-but-there-was-no-scale-up).

**Comment by marwanad** [comment]
Correct. The limitation is from the cluster-autoscaler core logic. The behaviour with a single nodepool that spans multiple zones is more or less non-deterministic. Having two separate pools should help or multiple single-zone node groups.

**Comment by marwanad** [comment]
Going to close this since question answered. Feel free to re-open if you have other related questions or concerns.
