### ISSUE TITLE
Feature request: Allow using existing user assigned identity in MI-enabled cluster

### ISSUE THREAD

**Issue by northtyphoon** [Azure/AKS#1649]
Currently if I create a new AKS cluster with MI enabled, AKS creates a new user-assigned identity (kubeletidentity) which is used as the identity to do something like  pull images from ACR, set up Pod Identity. 

Typically after the cluster is created, it requires additional steps to grant the new user-assigned identity the appropriate permissions on the desired resources. 

However such permission granting requires high-privileged role-assigned permission which is not feasible for our deployment process.  

I'm asking the feature to use an existing user assigned identity as kubeletidentity.

https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

**Comment by jluk** [comment]
Please look to issue #1591 which enables bringing an existing identity, cc @TomGeske for the need of ACR perms
