### ISSUE TITLE
Managed Identity AKS clusters - intermittent removal of identities on upgrade/scale

### ISSUE THREAD

**Issue by jluk** [Azure/AKS#1650]
The AKS team has uncovered two issues with Managed Identity enabled clusters.
https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

1. During cluster scale for a managed identity enabled AKS cluster, the managed identities that are associated with the underlying nodes are removed intermittently. This is a known bug that will be fixed by AKS as a priority issue.
1. During cluster upgrade for a managed identity enabled AKS cluster, the managed identity will be temporarily removed before being reapplied with an identity. This impacts both AKS and AKS-Engine clusters. This is a known improvement that will be fixed by AKS.

These issues can impact any scenarios which depend on the managed identity through scale and upgrade, such as [AAD Pod Identity](https://github.com/Azure/aad-pod-identity) which will have a known impact.

This is actively under investigation by the AKS team and a fix will be provided with details here when available.

**Comment by elsesiy** [comment]
@jluk Is there any progress/ETA on this? This is a blocking issue during cluster upgrade for us and we need to make some contingency planning if this doesn't get resolved soon, thanks.

**Comment by TomGeske** [comment]
Fix is done and role out will start 6/22. It will take a few days to land in all regions.

**Comment by galvesribeiro** [comment]
@TomGeske will it require any actions from the customer side?

**Comment by TomGeske** [comment]
@galvesribeiro: no fix will be deployed as part of our API.

**Comment by elsesiy** [comment]
@TomGeske Thanks for the update. Can you please provide the deployment schedule?

**Comment by TomGeske** [comment]
@elsesiy:  Which region are you looking for? Rollout is starting today.

**Comment by elsesiy** [comment]
@TomGeske We’re in multiple regions so an overview about all of them would be helpful, thanks

**Comment by deyanp** [comment]
@TomGeske , when will West Europe be done?

**Comment by galvesribeiro** [comment]
@TomGeske Brazil South here.

**Comment by TomGeske** [comment]
I will update you once deployment is complete in all public regions.

**Comment by BartVanBerkel** [comment]
@jluk & @TomGeske 
I have just verified a deployment in West Europe, but I doesn't seem to be working as I would expect. 

When I deploy a fresh cluster, I enable the omsagent and the dashboard. Which will result in 3 assigned identities (e.g. `**-agentpool`, `kubedashboard-**` and `omsagent-**`) on the VMSS. 
If I then execute a `az aks scale` operation, then I'll only have the `**-agentpool` identity assigned to the VMSS. 

note: Also if there are Identities assigned by Pod Identity they are not assigned to the VMSS anymore.

**Comment by TomGeske** [comment]
West Europe isn't deployed yet. It will take a few days to complete.

**Comment by elsesiy** [comment]
@TomGeske It would be really helpful if you can provide the deployment schedule here, is that a problem? I think the transparency will help users to plan accordingly.

**Comment by TomGeske** [comment]
Roll out started on Monday. WestCentralUS, AustraliaEast, CanadaCentral should be ready. The remaining once should be finished beginning next week. Hope that helps.

**Comment by TomGeske** [comment]
Most of the larger regions including West Europe finished deployment.

**Comment by galvesribeiro** [comment]
@TomGeske Brazil South?

**Comment by TomGeske** [comment]
@galvesribeiro:  Brazil South not yet. Takes a few more days.

**Comment by galvesribeiro** [comment]
Ok thanks, looking forward for it.

**Comment by BartVanBerkel** [comment]
> Most of the larger regions including West Europe finished deployment.

@TomGeske Just verified WestEurope, but still the same as in my previous [reply..](https://github.com/Azure/AKS/issues/1650#issuecomment-648664402)

**Comment by TomGeske** [comment]
@BartVanBerkel can you retry? I tested scaling operation with a fresh cluster in West Europe and identities remain assigned.

**Comment by TomGeske** [comment]
@elsesiy: deployment into all regions usually takes ~2 weeks.

**Comment by BartVanBerkel** [comment]
> @BartVanBerkel can you retry? I tested scaling operation with a fresh cluster in West Europe and identities remain assigned.

@TomGeske Looks better now. Thanks!

**Comment by galvesribeiro** [comment]
looking forward to see it on my end

**Comment by TomGeske** [comment]
@galvesribeiro it should be available in all remaining regions by now. 

I'm going ahead closing this issue. Please continue commenting if you have further questions.

**Comment by TomGeske** [comment]
We noticed that issue 2) wasn't properly deployed. I'm re-opening this one until we roll out the fix globally.

> During cluster upgrade for a managed identity enabled AKS cluster, the managed identity will be temporarily removed before being reapplied with an identity. This impacts both AKS and AKS-Engine clusters. This is a known improvement that will be fixed by AKS

**Comment by elsesiy** [comment]
Hi @TomGeske, has the fix been rolled out globally now? I worked on a cluster upgrade in eastus2 on Friday and still encountered the issue. Again what's the ETA for a permanent fix in all regions? 

Thanks!

**Comment by TomGeske** [comment]
Deployment is still pending. I update you once roll out starts.

**Comment by sikovatc** [comment]
Any updates on the roll out? Specifically for EastUS2 and Central US. Thanks!

**Comment by palma21** [comment]
Our release bot was about to close it in a couple of days :)
The release should be everywhere now. Let us know if you experience anything abnormal.
