### ISSUE TITLE
Kubernetes cluster creation fails when there is a NAT gateway associated to the subnet at the time of creation

### ISSUE THREAD

**Issue by parmus** [Azure/AKS#1653]
**What happened**:
Creation of Kubernetes cluster fails is there is a NAT gateway associated to the subnet _at the time of creation_. If the Kubernetes cluster is created first and the NAT gateway added last, everything works just fine.

The exact error message is
```
Failed to associate route table /subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/MC_k8-nat-first-test_kubernetes-cluster-last-api_westeurope/providers/Microsoft.Network/routeTables/aks-agentpool-90702041-routetable to subnet /subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/k8-nat-first-test/providers/Microsoft.Network/virtualNetworks/k8-nat-first-test-network/subnets/k8-nat-first-test-subnet.
```

**What you expected to happen**:
One of two things:
1) The cluster creation should succeed regardless which other components happens to be connected to the same subnet.
2) If this is an illegal configuration, then the API should throw an error message explaining that, _and_ it shouldn't work to add the NAT gateway last.

**How to reproduce it (as minimally and precisely as possible)**:

(Terraform configuration and `api-body.json` provided in https://gist.github.com/parmus/f2b6906e190c34ae98be728f7a8d465c)

1) Create a new resource group with a network, a subnet and a NAT gateway.
   I used the Terraform configuration from the gist.
2) Create a Kubernetes cluster connected to the subnet. I used `az` and the `api-body.json` from the gist. Adjust the subscription ID in `api-body.json` to match yours.
   `az rest -m put -u https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/k8-nat-first-test-01/providers/Microsoft.ContainerService/managedClusters/kubernetes-cluster-last-api?api-version=2020-02-01 --headers Content-Type=application/json --verbose -b @api-body.json`
  Notice that I'm using API version version 2020-02-01, because this is what Terraform uses and the API body is extracted from Terraform, where the issue was first discovered.
3) Wait for async operation to complete. Adjust the URL to the one return in the `Azure-AsyncOperation` from the previous command.
  `az rest -u 'https://management.azure.com/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/providers/Microsoft.ContainerService/locations/westeurope/operations/0066dada-7623-45a0-a851-ddf38b89c4f2?api-version=2017-08-31'`

Once the operation completes, a cluster will have been created, but it's in a failed state. If you inspect the routing table in the cluster's resource group, you'll see that it's not associate to the subnet, just like the error message indicated.

However, it does work if the NAT gateway gets added last:

If you disassociate the NAT gateway from the subnet before step 3, then create the cluster using step 3, and finally reassociate the NAT gateway to the subnet, then everything works just fine. The cluster gets successfully created and the routing table is correctly associated to the subnet.

**Anything else we need to know?**:

- This issue has already been reported as a support request to Azure support and a bug report to the Terraform Azure plugin (https://github.com/terraform-providers/terraform-provider-azurerm/issues/7201).
- Last week there at least was a work-around of sorts to this problem: after creating the cluster, which comes up in a failed state, it was possible to manually associate the routing table to the subnet, and then recover the cluster from the failed state by triggering an upgrade using
  `az aks upgrade --resource-group k8-nat-first-test-01 --name kubernetes-cluster-last --kubernetes-version 1.15.10`
  However this is no longer possible as `az` now reports:
  `Operation failed with status: 'Bad Request'. Details: Downgrading Kubernetes version 1.15.11 to 1.15.10 is not allowed. Available upgrades: 1.16.9,1.16.8. Please see https://aka.ms/aks-supported-k8s-ver for version details.`

**Environment**:
```bash
# az --version
azure-cli                          2.7.0

command-modules-nspkg              2.0.3
core                               2.7.0
nspkg                              3.0.4
telemetry                          1.0.4
```

This problem was originally discovered with Terraform v0.12.26 and `azurerm` v2.12.0, but is also reproducible with pure API calls as shown above.

**Comment by scul859** [comment]
Is this going to be resolved anytime soon? Kinda weird to categorize this as a `feature-request` cause from my POV, this is clearly a bug.

**Comment by johnroach** [comment]
I just came across this bug. Really annoying. Is there any news if this will be picked up?

**Comment by JoniSanchez** [comment]
Hi, I have the same problem when creating an AKS on a network share, the NAT already exists and it is not able to modify the routing table. 

Is there any way to fix this problem with Terraform or can only az cli be used. Can anyone help me?

**Comment by yoelpg** [comment]
HI,

same problems mentioned before :( . Is this issue going to be fixed soon?

**Comment by miwithro** [comment]
As stated above this can work depending on the sequence used.  We are aware of the issue and are looking into it.

**Comment by paulgmiller** [comment]
We think we may have fixed a permissions issue that was blocking this.

Afterwards I was able to do below without an error. Please give it another go  and if you hit an error please share details to reproduce

Nat gateways are still pretty new and untested in aks so be aware.  Thanks,

```
export s="USE YOUR OWN"
export rg="paulbash5"
export l="westcentralus"
export vnet="paulnetG"
export c="bugbashG"

az group create --location $l --name $rg
az configure --defaults group=$rg 
az account set -s $s

#Create nat gateway and put it on our subnet
az network public-ip create   --resource-group $rg --name myPublicIP--sku standard \
az network nat gateway create --resource-group $rg --name natgateway
az network vnet create -g $rg --name $vnet --address-prefixes 10.0.0.0/8 -o none
az network vnet subnet create -g $rg --vnet-name $vnet --name nat --address-prefixes 10.240.0.0/16 -o none
az network vnet subnet update --resource-group $rg \--vnet-name $vnet --name nat  --nat-gateway natgateway


#create cluster
az aks create -n $c -g $rg -l $l --node-count 2 --yes 
 --vnet-subnet-id /subscriptions/$s/resourceGroups/$rg/providers/Microsoft.Network/virtualNetworks/$vnet/subnets/nat 
```

**Comment by nitzanm** [comment]
@paulgmiller unfortunately we are still getting the same issue in production in westeurope:

`
Error: waiting for creation of Managed Kubernetes Cluster "XXX-aks" (Resource Group "XXX-westeurope"): Code="AssociateRouteTableToSubnetError" Message="Failed to associate route table /subscriptions/XXX/resourceGroups/MC_XXX/providers/Microsoft.Network/routeTables/aks-agentpool-28276211-routetable to subnet /subscriptions/XXX/resourceGroups/XXX-westeurope/providers/Microsoft.Network/virtualNetworks/XXX-westeurope/subnets/XXX-westeurope."
`

Any thoughts on what we could try next?

**Comment by palma21** [comment]
Do you happen to have open a support ticket for this? (we'd likely need to take a look at your cluster), did you follow Paul's steps above?

**Comment by paulgmiller** [comment]
Embaressingly we applied permissions on the wrong role. That is fixed and I also found an issue in my script above and have fixed it. (\ before --vnet-name meant nat gatway was never actually applied)

```
#Create nat gateway and put it on our subnet
az network public-ip create   --resource-group $rg --name natpublicip --sku standard 
az network nat gateway create --resource-group $rg --name natgateway --public-ip-addresses /subscriptions/$s/resourceGroups/$rg/providers/Microsoft.Network/publicIPAddresses/natpublicip
az network vnet create -g $rg --name $vnet --address-prefixes 10.0.0.0/8 -o none
az network vnet subnet create -g $rg --vnet-name $vnet --name nat --address-prefixes 10.240.0.0/16 -o none
az network vnet subnet update --resource-group $rg --vnet-name $vnet --name nat  --nat-gateway natgateway


#create cluster
az aks create -n $c -g $rg -l $l --node-count 2 --yes --vnet-subnet-id /subscriptions/$s/resourceGroups/$rg/providers/Microsoft.Network/virtualNetworks/$vnet/subnets/nat 

```

**Comment by nitzanm** [comment]
@paulgmiller This appears to work now! We are running additional testing over the weekend and will get back to you with a more comprehensive answer, but thank you so much for your help!
