### ISSUE TITLE
Upgraded 1.16.9 cluster-autoscaler crash looping

### ISSUE THREAD

**Issue by bambash** [Azure/AKS#1654]
**What happened**:
Cluster was upgraded to 1.16.9 and the cluster autoscaler is now stuck in `Initializing`. After the control plane was updated, new node pools were added and old node pools were removed. The cluster-autoscaler process didn't update its configuration and began crash looping because it could not find the old node pools. The node pools were added and removed using Terraform.

From the logs portal:
```
E0608 14:08:01.703460 1 azure_scale_set.go:587] Failed to get current size for vmss "aks-defaultaz1-31642724-vmss": could not find vmss: aks-defaultaz1-31642724-vmss 
F0608 14:08:01.703523 1 azure_cloud_provider.go:167] Failed to create Azure Manager: could not find vmss: aks-defaultaz1-31642724-vmss 
```

Cluster autoscaler configmap status
```
$ kubectl get cm cluster-autoscaler-status -n kube-system -o yaml
apiVersion: v1
data:
  status: |-
    Cluster-autoscaler status at 2020-06-05 14:53:59.849415192 +0000 UTC:
    Initializing
kind: ConfigMap
```

Pods are stuck pending.

**What you expected to happen**:
Cluster autoscaler configmap status would report healthy. Old nodes would be removed from its configuration. Pod scheduling should trigger CA to scale in additional nodes.

**How to reproduce it (as minimally and precisely as possible)**:
Create a 1.15 cluster, upgrade the cluster to 1.16. Add new node pools and remove old node pools. Trigger a scaling event. Observe logs in log portal and autoscaler configmap.

**Anything else we need to know?**:
The cluster has 4 node pools, including the default. The default node pool has autoscaling disabled. The 3 worker node pools have autoscaling enabled. When the cluster was upgraded, new node pools were created. Old node pools were cordoned, drained, and removed.

**Environment**:
- Kubernetes version (use `kubectl version`):
```$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T23:15:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
4 node pools, each with 1 node.

- Others:

**Comment by bambash** [comment]
Issue was caused by CPU quota limit

**Comment by bambash** [comment]
Re-opening based on new findings. Updated the issue description.

**Comment by marwanad** [comment]
@bambash thanks for reporting (and providing repro)! 

Can you file a support ticket and send the number so we can take a deeper look at the cluster?

**Comment by paulgmiller** [comment]
@bambash  are you willing to share you're clusters fqdn and a timeline sso we can take a closer look at what happened?

**Comment by paulgmiller** [comment]
We figured out the info we needed and believe we have an internal bug 7123721 where this can happen though it should be pretty rare (basically we get a conflict updating these settings and don't retry).

**Comment by bambash** [comment]
hi @paulgmiller - I have a support ticket going currently 120060524006008. Thanks for looking into this!
