### ISSUE TITLE
AGIC error mutating App Gateway config breaks fronted IP.

### ISSUE THREAD

**Issue by Chirs-uS** [Azure/AKS#1655]
Hi. First ever GitHub issue raised so fingers crossed.

## Bug Description
The AGIC is somehow breaking the App Gateway front end private IP configuration. Errors appear in the logs similar to those reported in issues [#510](https://github.com/Azure/application-gateway-kubernetes-ingress/issues/510), [#598](https://github.com/Azure/application-gateway-kubernetes-ingress/issues/598). The resource group AZUR001 is not part of the AKS deployment I am working with and doesn't exist in our Azure subscriptions. 
```
W0604 10:58:46.117767       1 azure.go:44] infrastructure resource group name: rg-sit-aks-nodes is expected to be of format MC_ResourceGroup_ResourceName_Location
I0604 10:58:46.117788       1 configbuilder.go:211] Error while parsing cluster resource ID for tagging: unable to locate AKS resource group (AZUR001)
```
Shortly after, a deployment operation fails..
```
I0604 10:58:46.118982       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
E0604 11:02:16.593378       1 mutate_app_gateway.go:169] Failed applying App Gwy configuration:
{
-- App Gwy config --
}
Ierror: Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=502 -- Original Error: Code="InvalidGatewayHost" Message="Host name resolution failed for 'Microsoft.Network'; cannot fulfill the request."
I0604 11:02:16.593981       1 mutate_app_gateway.go:174] END AppGateway deployment
E0604 11:02:16.594070       1 worker.go:62] Error mutating App Gateway config from k8s event. Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=502 -- Original Error: Code="InvalidGatewayHost" Message="Host name resolution failed for 'Microsoft.Network'; cannot fulfill the request."
```
This is when the AGIC fails to update the App Gateway because it's front end private static IP (partly hidden here) which is still showing in the portal as configured on the App Gateway is somehow in use by another resource or being cleaned up.
```
I0604 11:07:29.657600       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
E0604 11:07:29.790259       1 mutate_app_gateway.go:169] Failed applying App Gwy configuration:
{
-- App Gwy config --  
}
error: network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayFrontendIPStaticPrivateIPAddressNotAvailable" Message="FrontendIpConfiguration /subscriptions/MY_SUBCRIPTION_ID/resourceGroups/MY_RESOURCE_GROUP/providers/Microsoft.Network/applicationGateways/AG-AKS-SIT/frontendIPConfigurations/ILB-AG-AKS-SIT cannot use private IP address *.*.1.10 as it is either allocated to a resource or being cleaned up." Details=[]
I0604 11:07:29.790332       1 mutate_app_gateway.go:174] END AppGateway deployment{
I0604 11:07:29.793651       1 event.go:258] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"ingress-azure-5545f48fcc-fz4mh", UID:"81f65777-a575-11ea-9e32-3a23a89bef0d", APIVersion:"v1", ResourceVersion:"12015189", FieldPath:""}): type: 'Warning' reason: 'FailedApplyingAppGwConfig' Failed applying App Gwy configuration:
{
-- App Gwy config --
}
```
Checking with the azure CLI I discovered that the IP is not configured anymore although it's still showing in the portal as configured on the App Gateway.
```
az network vnet check-ip-address --name MY_AKS_VNET -g MY_RESOURCE_GROUP --ip-address *.*.1.10
{
  "available": false,
  "availableIpAddresses": [
    "*.*.1.5",
    "*.*.1.6",
    "*.*.1.8",
    "*.*.1.9",
    "*.*.1.11"
  ],
  "inUseWithResource": "/subscriptions/ecce6121-65f7-4919-84c1-024e1eb0f84e/resourceGroups/armrg-89a09f5b-e92a-440f-872a-942687c19931/providers/Microsoft.Network/loadBalancers/appgwILB",
  "isPlatformReserved": false
}
```
The IP has been allocated to a resource which is not part of our Azure subscription and only Azure support can free it up so we are able to reconfigure it on our App Gateway.

## To Reproduce
Deploy AGIC release 1.2.0-rc2 and deploy any app that forces AGIC to reconfigure Application Gateway.

This may or may not have been related to [this Azure Service Health issue with ARM](https://app.azure.com/h/DLZG-7C0/cd6b9f) (which occurred on the same day) but it's happened several times over the last month (previously I was installing release 1.0.0 with similar issues) and each time Azure support have to release the IP address for us.

FYI our set up has custom name for our resource groups and the node VMs are in a separate resource group to the App Gateway & AKS cluster service

Thanks & kind regards

**Comment by jluk** [comment]
@Chirs-uS can you please transfer this ticket to the AGIC project (https://github.com/Azure/application-gateway-kubernetes-ingress/issues)? From your writeup it looks like you are self-installing the project (targeting a specific build), self installs of that project are not something AKS can troubleshoot but the AppGateway team can.

AKS only supports the integrated AGIC + AKS managed add-on which has not shipped yet, but we will have news for that option in the coming weeks.

**Comment by Chirs-uS** [comment]
Thanks for pointing that out. Ticket moved.
