### ISSUE TITLE
 default-http-backend:80 (<error: endpoints "default-http-backend" not found>) errorwhen creating any ingress resource

### ISSUE THREAD

**Issue by surya2155** [Azure/AKS#1659]
HI All,

When I am trying to create a ingress resource for my AKS cluster(ingress controller is already created), Ingress resource/rules is creating and I am able to see in the kubectl get ing. But when I do kubectl describe <ing name>, I am seeing a error: Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>). Is this expected?? I can see the desfault backend pod is also running. I am not even able to connect to my application using the ingress controller IP. is it due to this http backened error?? If not any suggestions to make the application connect!! 

AzureUser@testvm:~$ kubectl describe ingress.extensions/hello-world-ingress
Name:             hello-world-ingress
Namespace:        default
Address:          10.240.0.36,10.240.0.67
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  *
              /(.*)   angular-service:80 (10.240.0.47:80,10.240.0.68:80)
Annotations:  kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/rewrite-target: /$2
              nginx.ingress.kubernetes.io/ssl-redirect: false
Events:
  Type    Reason  Age                    From                      Message
  ----    ------  ----                   ----                      -------
  Normal  CREATE  4m49s                  nginx-ingress-controller  Ingress default/hello-world-ingress
  Normal  CREATE  4m49s                  nginx-ingress-controller  Ingress default/hello-world-ingress
  Normal  CREATE  4m49s                  nginx-ingress-controller  Ingress default/hello-world-ingress
  Normal  UPDATE  3m14s (x4 over 4m23s)  nginx-ingress-controller  Ingress default/hello-world-ingress
  Normal  UPDATE  3m14s (x4 over 4m23s)  nginx-ingress-controller  Ingress default/hello-world-ingress
  Normal  UPDATE  3m14s (x4 over 4m23s)  nginx-ingress-controller  Ingress default/hello-world-ingress

AzureUser@testvm:~$ kubectl describe pod/nginx-ingress-default-backend-7c6cd67dbb-df94q
Name:         nginx-ingress-default-backend-7c6cd67dbb-df94q
Namespace:    default
Priority:     0
Node:         aks-agentpool-15065227-vmss000002/10.240.0.67
Start Time:   Mon, 08 Jun 2020 17:05:51 +0000
Labels:       app=nginx-ingress
              app.kubernetes.io/component=default-backend
              pod-template-hash=7c6cd67dbb
              release=nginx-ingress
Annotations:  <none>
Status:       Running
IP:           10.240.0.69
IPs:
  IP:           10.240.0.69
Controlled By:  ReplicaSet/nginx-ingress-default-backend-7c6cd67dbb
Containers:
  nginx-ingress-default-backend:
    Container ID:   docker://5f9d5640c3b747c989b31b601156f226d84efa07ddafbcf84336fdae4778bafb
    Image:          k8s.gcr.io/defaultbackend-amd64:1.5
    Image ID:       docker-pullable://k8s.gcr.io/defaultbackend-amd64@sha256:4dc5e07c8ca4e23bddb3153737d7b8c556e5fb2f29c4558b7cd6e6df99c512c7
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 08 Jun 2020 17:05:53 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8080/healthz delay=30s timeout=5s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/healthz delay=0s timeout=5s period=5s #success=1 #failure=6
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from nginx-ingress-backend-token-8gt4f (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  nginx-ingress-backend-token-8gt4f:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  nginx-ingress-backend-token-8gt4f
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

Service:
AzureUser@testvm:~$ kubectl describe svc angular-service
Name:              angular-service
Namespace:         default
Labels:            <none>
Annotations:       Selector:  app=angular
Type:              ClusterIP
IP:                10.0.92.136
Port:              http  80/TCP
TargetPort:        80/TCP
Endpoints:         10.240.0.47:80,10.240.0.68:80
Session Affinity:  None
Events:            <none>
AzureUser@testvm:~$

When connecting to the controller external IP, it is showing the blank page:(But it is connecting fine when I use service of type loadbalancer before started using ingress)
![image](https://user-images.githubusercontent.com/42170650/84117164-b3447300-aa4e-11ea-878d-4c2c21c4fc52.png)

**Comment by 037g** [comment]
I have the same problem. Were you able to fix this?

**Comment by palma21** [comment]
Have you followed this tutorial https://docs.microsoft.com/en-us/azure/aks/ingress-basic?
