### ISSUE TITLE
OMSAgent is eating up 98% of CPU in cluster node - impacting other pods running in that node

### ISSUE THREAD

**Issue by ItsDevender** [Azure/AKS#1661]
**What happened**:
omsgent is eating up most CPU in almost all nodes. we have 8 nodes (b8ms) AKS cluster. Serving 5 separate env. namespaces running application stacks in those 5 envs. We don't know why OMSagent takes up that much CPU keeping other pods at standstill. Sometime it makes any specific node red making whole cluster red and specifically pods that were running on that node - processes started getting timeouts (connection) and other failures.
Initially it was only 2 node cluster - but as we started creating more env. namespace (dev/test) we started getting node cpu getting >95% - so we started adding more nodes. Right from start omsagent is front runner in eating CPU of cluster.

**What you expected to happen**:
Why do I need omsagent in first place ? its not adding any value to me and why do I need to have it ? having it actually causing more problem than thinking about the value add.

**How to reproduce it (as minimally and precisely as possible)**:
Please spin up a cluster of B8ms of 3 nodes and setup couple of env. stacks. 

**Anything else we need to know?**:
Please let me know whatever you want to know - but please advise

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by vishiy** [comment]
@ItsDevender - It should be 85% of its limits (which is 150millicores). Insights Ux says percentage w.r.t. to limits for the container. 
Are you running any other log collection solution in the same node(s) ?

**Comment by ItsDevender** [comment]
Issue is resolved.

**Comment by andyzhangx** [comment]
> Issue is resolved.

@ItsDevender how is this issue resolved?
