### ISSUE TITLE
kubectl asking for authorization randomly when having a mix of MI and SP-based clusters in kubectl config

### ISSUE THREAD

**Issue by mhsh64** [Azure/AKS#1662]
**What happened**:
Deployed multiple clusters with Managed Identities, we already have SP-based clusters as well. So kubectl config has a mix of credentials for both MI and SP-clusters. The issue is after some time, the MI clusters asks for authorization again. 

You must be logged int o the server (Unauthorized)
when refreshing the credential, it will work again.
**What you expected to happen**:
In a mix environment of MI and SP based clusters, able to run kubectl commands without any re-authentication
**How to reproduce it (as minimally and precisely as possible)**:
having two clusters , one with SP and one with MI. After getting credential with az aks get-credentials , you will have both credentials for both clusters. After some times, the MI clusters asks you again to authenticate. 

**Anything else we need to know?**:
What I did, I cleared the kubectl config from any SP based cluster credential, and just have MI based clusters, I did not find that issue. I guess by adding credentials for a SP-based cluster, the issue happens
**Environment**:
- Kubernetes version (use `kubectl version`): 1.18
- Size of cluster (how many worker nodes are in the cluster?) 10
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by TomGeske** [comment]
@mhsh64: Are you using AAD or client cert authentication?

**Comment by mhsh64** [comment]
@TomGeske Hi, we are using AAD

**Comment by TomGeske** [comment]
Sound like the upstream `kubectl` issue referenced in issue #1669

**Comment by mhsh64** [comment]
Yeah same issue

**Comment by TomGeske** [comment]
@mhsh64: please let me know if you need further help.
