### ISSUE TITLE
Azure NPM agent crashing

### ISSUE THREAD

**Issue by JRolfe-Gen** [Azure/AKS#1664]
NPM module is crashing when a bad configuration is presented. Could you handle the bad configuration gracefully?
There are some undefined ports on two of the ingress rules.
[azure_npm crash.txt](https://github.com/Azure/AKS/files/4761724/azure_npm.crash.txt)

Container image "mcr.microsoft.com/containernetworking/azure-npm:v1.1.2

**Comment by jluk** [comment]
@jrolfe-gen please open a support request for this issue, we will need Azure Networking to contribute on this debugging.

**Comment by jloaiza** [comment]
@JRolfe-Gen I have the same issue, did you open the support request? Have you had any response? 
In my case I'm using the v1.1.4 image.
