### ISSUE TITLE
Metric Server Stops storing metrics when duplicate pods are found

### ISSUE THREAD

**Issue by djsly** [Azure/AKS#1668]
**What happened**:
cannot use `kubectl top` anymore
cannot use HPA as well. 
```
✖ k top node
error: metrics not available yet
```

**What you expected to happen**:
for `kubectl top` to work

**How to reproduce it (as minimally and precisely as possible)**:
once metric-server hits one duplicate pod, it stops storing metrics. 
https://github.com/kubernetes-sigs/metrics-server/issues/316

**Anything else we need to know?**:
Bumping metric-server to version `v0.3.6` should fix the issue. 
I tried but the Haddon-manager running on the control plane keeps reverting my changes...

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"059c666b8d0cce7219d2958e6ecc3198072de9bc", GitTreeState:"clean", BuildDate:"2020-04-03T15:17:29Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
- ~80
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by szwed** [comment]
Same issue with cluster in version v1.16.9 (after upgrade from v1.15.10).

**Comment by djsly** [comment]
@jluk / @seanmck what's the plan now that aks-engine is merged ?  would a new AKS release fix all existing AKS version with a simple empty put ? or will the control plane be updated eventually once the new AKS release gets deployed on all regions ?

**Comment by djsly** [comment]
Fixed in release: https://github.com/Azure/AKS/releases/tag/2020-06-29
