### ISSUE TITLE
access token is not refreshed using the refresh-token for kubectl in Managed Identity aks clusters?

### ISSUE THREAD

**Issue by mhsh64** [Azure/AKS#1669]
**What happened**:
We have deployed AKS cluster with Managed Identity and AAD v2 enabled. 
From command line, after getting az aks get-credentials, authenticated successfully and able to run kubectl commands, based on my cluster roles.
However randomly after minutes or hours, when I run kubectl commands, I am getting:

Error: You must be logged in to the server (Unauthorized)

Any idea why it happens?
I checked my  az account get-access-token and it is valid all the time I have this issue.
When I run az aks get-credentials, and authenticate again, it is fine, but it happens often
**What you expected to happen**:
Able to run kubectl commands successfully after authentication 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
There is no issue for Service Principal based AKS clusters, only this issue observed for MI clusters

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.10
- Size of cluster (how many worker nodes are in the cluster?) 6 
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jon-walton** [comment]
I've also come across this. running `az aks get-credentials ...` gets things working again temporarily

```
kubectl version --client
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
```

```
az --version
azure-cli                          2.8.0 *

command-modules-nspkg              2.0.3
core                               2.8.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
aks-preview                       0.4.55
interactive                        0.4.3
```

**Comment by mhsh64** [comment]
Yeah we still have this issue with no resolution yet.

**Comment by ch-bohlen** [comment]
You can use kubelogin (https://github.com/Azure/kubelogin) to work around this issue.

**Comment by jon-walton** [comment]
I previously tried kubelogin and had the same issue. Today however, things appear to be working... @mhsh64 is it working better for you today too?

It looks like it went GA on Tuesday, perhaps it got fixed? https://azure.microsoft.com/en-us/updates/aksmanaged-azure-active-directory-support-is-now-generally-available/

**Comment by mhsh64** [comment]
@jon-walton 
Hi, good point, yesterday (Tuesday) I had the same issue, today I didn’t pay attention honestly. But I will check it closely from now. 
Did it fix for you?

**Comment by jon-walton** [comment]
I didn't have any trouble today

**Comment by TomGeske** [comment]
Can you update to latest CLI (2.9.1)?

**Comment by jon-walton** [comment]
Oh that might be it. I'm back to working from home and this PC has 2.9.0

**Comment by billpieper** [comment]
I am experiencing this issue and am running CLI 2.9.1.

**Comment by TomGeske** [comment]
@billpieper: can you share your setup?
- kubectl version?
- are you using kubelogin?

**Comment by billpieper** [comment]
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"5737fe2e0b8e92698351a853b0d07f9c39b96736", GitTreeState:"clean", BuildDate:"2020-06-24T19:54:11Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

I am not currently using kubelogin

**Comment by mhsh64** [comment]
I still have the same issue even after upgrading az and kubectl again to the latest version ☹️

**Comment by weinong** [comment]
you probably hit https://github.com/kubernetes/kubernetes/issues/82776
the fix is in 1.19 (not yet released)

this is why kubelogin is promoted as that is released outside kubernetes cadence and we have full control. :)

if this happens on kubelogin, let us know.

**Comment by jon-walton** [comment]
@weinong any plans to make `az aks get-credentiale` write a kubelogin compatible kubeconfig?

**Comment by weinong** [comment]
> @weinong any plans to make `az aks get-credentials` write a kubelogin compatible kubeconfig?

great question. it's almost done. i think it will be available in next couple of weeks. this is one of the PR: https://github.com/Azure/azure-cli/pull/14441

**Comment by TomGeske** [comment]
@mhsh64 and @billpieper: did you get it to work by updating kubectl?

**Comment by mhsh64** [comment]
I already had 1.18.6 and still had the issue
I upgraded now to 1.18.8, I will let you know if it works

**Comment by TomGeske** [comment]
1.18.6 should be fine. We had similar cases, where multiple kubectl versions have been installed on the same machine. Making sure all are updated and downloading again credentials with `az aks get-credenitals` fixed the issue all the time.

Also make sure your `.kube/config` users section has config-mode and environment set.

**Comment by mhsh64** [comment]
@TomGeske Hi I have the same issue
I have the latest kubectl version
I checked the config file, config-mode and environment already set
Any idea? Or sth else I need to do!?

**Comment by TomGeske** [comment]
Please, share you ticket no.

**Comment by mhsh64** [comment]
I haven’t opened a ticket for it, I can do it now. And give you the number ,

**Comment by mhsh64** [comment]
@TomGeske 
Hi 
Here is the number
120081924002169

**Comment by billpieper** [comment]
> @mhsh64 and @billpieper: did you get it to work by updating kubectl?

I got it working by way of using kubelogin

**Comment by TomGeske** [comment]
To use kubelogin follow:

Download kubelogin from [here](https://github.com/Azure/kubelogin) and copy binaries into the same folder as kubectl.

# Run
1. az aks get-credentials -n {cluster-name} -g {rg-name}
2. kubelogin convert-kubeconfig

Your .kube/config should look similar like:
```
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - {server id}
      - --client-id
      - {client-id}
      - --tenant-id
      - {tenant-id}
      command: kubelogin
      env: null
```
3. run kubectl get nodes to authenticate.
