### ISSUE TITLE
Back-off restarting failed container In Azure AKS

### ISSUE THREAD

**Issue by KomalNimje** [Azure/AKS#1672]
Linux container pod, with docker images from Azure Container registry, keeps restarting with restartPolicy as Always. Pod description is as below.

### **kubectl describe pod example-pod**

...

State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 11 Jun 2020 03:27:11 +0000
      Finished:     Thu, 11 Jun 2020 03:27:12 +0000
...
Back-off restarting failed container

### **Expected Result:**

Running

### Actual Result:
 State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 15 Jun 2020 12:14:36 +0530
      Finished:     Mon, 15 Jun 2020 12:14:36 +0530
    Ready:          False

### Kubectl events log:
Type     Reason     Age                  From                                        Message
  ----     ------     ----                 ----                                        -------
  Normal   Scheduled  13m                  default-scheduler                           Successfully assigned default/cpweb-5fd94d4664-hrnjn to aks-agentpool-17573332-vmss000000
  Normal   Pulling    12m (x4 over 13m)    kubelet, aks-agentpool-17573332-vmss000000  Pulling image "example:latest"
  Normal   Pulled     12m (x4 over 13m)    kubelet, aks-agentpool-17573332-vmss000000  Successfully pulled image "example:latest"
  Normal   Created    12m (x4 over 13m)    kubelet, aks-agentpool-17573332-vmss000000  Created container example
  Normal   Started    12m (x4 over 13m)    kubelet, aks-agentpool-17573332-vmss000000  Started container example
  Warning  BackOff    3m9s (x51 over 13m)  kubelet, aks-agentpool-17573332-vmss000000  Back-off restarting failed container

**Comment by andyzhangx** [comment]
pls run `kubectl get po pod-name -o yaml` and `kubectl logs pod-name` to get more details why this pod is crashing, it's more like issue on pod itself
