### ISSUE TITLE
Add CoreDNS readiness probe

### ISSUE THREAD

**Issue by palmerabollo** [Azure/AKS#1676]
**What happened**:

We face DNS resolution failures because DNS requests are sent to coredns pods before they are ready.

The deployment "coredns" in AKS does not have a readiness probe. The coredns-autoscaler creates new replicas when needed:

> I0612 17:57:59.468340 1 k8sclient.go:277] Cluster status: SchedulableNodes[17], SchedulableCores[49]
> I0612 17:57:59.468373 1 k8sclient.go:278] Replicas are not as expected : **updating replicas from 3 to 4**

And AKS uses a service in front of those coredns pods. Since coredns dose not have a readiness probe, some DNS requests are sent to the new replicas before they are ready, causing DNS resolution failures.

This does not happen with aks-engine, where coredns has both a liveness and a readiness probe (see https://github.com/Azure/aks-engine/blob/master/parts/k8s/addons/coredns.yaml#L198-L202). We think it's a bug in AKS.

**What you expected to happen**:

coredns should have a readiness probe to receive traffic only when it is really ready.

**How to reproduce it (as minimally and precisely as possible)**:

- Create an AKS cluster (1.16.9).
- Start making DNS requests.
- Scale up the number of coredns replicas.
- See some DNS resolutions fail.

**Anything else we need to know?**:

There is a support ticket 120061622000996 as welll

**Environment**:
- Kubernetes version: at least 1.16.7, 1.16.9
- Size of cluster: 4-30 nodes
- General description of workloads in the cluster: HTTP microservices

**Comment by palmerabollo** [comment]
This issue might be related https://github.com/coredns/coredns/issues/3403
AKS is currently using mcr.microsoft.com/oss/kubernetes/coredns:1.6.6 (k8s 1.16.9)

**Comment by palma21** [comment]
You're correct, that is an issue. We logged a work item to fix that.

Thanks for raising it
