### ISSUE TITLE
Pull Windows images can take a while, also on autoscale

### ISSUE THREAD

**Issue by bplasmeijer** [Azure/AKS#1677]
**What happened**: Pulling a Windows image can take a while, and if ```autoscale``` is enabled, images need a second ```pull``` time on the newly created window nodes. 

**What you expected to happen**:  Faster pull times or preload images on the node.

**How to reproduce it (as minimally and precisely as possible)**:

If I am using ```initContainers``` feature on my manifest, and when the ```init``` ready at the moment, it will then start pulling the ```deployment``` image. 

**Anything else we need to know?**:

**Environment**: Azure AKS
- Kubernetes version (use `kubectl version`): v1.16.7
- Size of cluster (how many worker nodes are in the cluster?) Standard_D16s_v3
- AutoScale enabled

**Comment by jluk** [comment]
@bplasmeijer this is likely due to the large image sizes required of Windows images, can you share what the image size is?

**Comment by PixelRobots** [comment]
My windows container image is just over 5gb last time I checked. And get the same issue.

**Comment by keikhara** [comment]
what is the container image and version?

**Comment by andyzhangx** [comment]
try use `mcr.microsoft.com/windows/nanoserver:1809` as base image, it only has 300MB

**Comment by PixelRobots** [comment]
Hello,

I wish I could use nanoserver, but my application does not like it.

Below is my slightly redacted docker file:

# Base OS for the container
FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS container_base

# Build Base Image - Full .net core SDK installed

FROM container_base AS build_base
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN `\
    # Retrieve .NET Core SDK
    $dotnet_sdk_version = '3.1.301'; `\
    Invoke-WebRequest -OutFile dotnet_sdk.zip https://dotnetcli.azureedge.net/dotnet/Sdk/$dotnet_sdk_version/dotnet-sdk-$dotnet_sdk_version-win-x64.zip; `\
    $dotnet_sha512 = '99a124d19503036bcedefffb348fa23476e60cdabfcb8e9cddc6545f05f57d8d2cf5bc7ff9b42039387a15328471c5bd47e50c5ea129fbd418a6e0fa9607bb17'; `\
    if ((Get-FileHash dotnet_sdk.zip -Algorithm sha512).Hash -ne $dotnet_sha512) { `\
        Write-Host 'CHECKSUM VERIFICATION FAILED!'; `\
        exit 1; `\
    }; `\
    Expand-Archive dotnet_sdk.zip -DestinationPath 'C:/program files/dotnet'; `\
    Remove-Item -Force dotnet_sdk.zip


USER ContainerAdministrator
ENV PATH="${PATH};C:\\Program Files\\dotnet"

# Create Final Base Image - Empty container image with only .net core runtime installed.
FROM container_base AS final_base
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN $dotnet_version = '3.1.3'; `\
    Invoke-WebRequest -OutFile dotnet.zip https://dotnetcli.azureedge.net/dotnet/Runtime/$dotnet_version/dotnet-runtime-$dotnet_version-win-x64.zip; `\
    $dotnet_sha512 = '62a18838664afd6f08cdb9a90a96a67626743aab1f0de0065eadfd7d1df31681c90f96744ccb5b7e40834c9e3c4952125c8c83625867c500692050cdd113ff50'; `\
    if ((Get-FileHash dotnet.zip -Algorithm sha512).Hash -ne $dotnet_sha512) { `\
        Write-Host 'CHECKSUM VERIFICATION FAILED!'; `\
        exit 1; `\
    }; `\
    `\
    Expand-Archive dotnet.zip -DestinationPath 'C:/program files/dotnet'; `\
    Remove-Item -Force dotnet.zip
USER ContainerAdministrator
ENV PATH="${PATH};C:\\Program Files\\dotnet"
ENV `\
    # Configure web servers to bind to port 80 when present
    ASPNETCORE_URLS=http://+:80 `\
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true



# Compile program into /app/publish on the build image
FROM build_base as build
WORKDIR /src
COPY ["Appname/Appname.csproj", "Appname/"]
COPY ["Appname/nuget.config", "Appname/"]
COPY ["SwiPLcs/SwiPLcs.csproj", "SwiPLcs/"]
RUN ["dotnet", "restore", "Appname/Appname.csproj", "--configfile", "Appname/nuget.config"]
COPY . .
WORKDIR "/src/Appname"
ENV SolutionDir="C:\\src\\"
RUN ["dotnet", "build", "Appname.csproj", "-c", "Release", "-o", "/app/build"]
RUN ["dotnet", "publish", "Appname.csproj", "-c", "Release", "-o", "/app/publish"]

# Copy compiled program to final build container and execute.
FROM final_base AS final
ENV AppConfigConnectionString="Endpoint=url"
ENV ConfigsOnly="false"
ENV RulesOnly="false"

WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Appname.dll"]

Hope it helps

**Comment by bplasmeijer** [comment]
Hi @palma21 

issue related to #1785

**Comment by bplasmeijer** [comment]
Let's wait for #1785
