### ISSUE TITLE
Cluster creation in eastus fails

### ISSUE THREAD

**Issue by jmalobicky** [Azure/AKS#168]
I have tried to create a few clusters over the last hour+ with version 1.8.6. At first the AKS object is created but then the provisioning lists **Failed**. Looking into the Activity Log I am seeing the following error

`"statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"ControlPlaneProvisioningInternalError\",\"message\":\"Timeout while polling for control plane provisioning status\"}]}}"
`

The additional AKS resource group for the managed cluster objects does not seem to being created. I can only assume this is something wrong in Azure land and will have to wait till this is resolved.

Is this happening for anyone else? Is this a known issue in East US?

**Comment by moloh** [comment]
I do observe similar creation issue. Did try to follow https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough-portal and some combinations of cluster and resource names, but to no avail. Resource group however is being created in my case.

**Comment by jmalobicky** [comment]
Seems the deployment is operating now

**Comment by moloh** [comment]
Unfortunately for me, I still have issues with deployment

**Comment by moloh** [comment]
Out of blue cluster deployment started to function for me too

**Comment by slack** [comment]
We are continuing to work on surfacing errors from downstream dependencies. Likely an intermittent issue, but we ended up swallowing the real error.

Thanks for the report. I'm going to close this as a transient issue.
