### ISSUE TITLE
[Feature] Network Policy Calico on Windows AKS

### ISSUE THREAD

**Issue by keikhara** [Azure/AKS#1681]
Azure provides two ways to implement network policy. You choose a network policy option when you create an AKS cluster. The policy option can't be changed after the cluster is created:
- Azure's own implementation, called Azure Network Policies.
- Calico Network Policies, an open-source network and network security solution founded by [Tigera](https://www.tigera.io/).

[Documentation](https://docs.microsoft.com/en-us/azure/aks/use-network-policies) on Calico Network Policy

**Comment by jkantharaj** [comment]
Hi Keiko, We are planning to use AKS/Calico Enterprise Edition combination for Network Policy. We are working with MSFT AKS Blackbelt and MSFT Solutions Architect. We were wondering to get an update on this feature and when is it planned for GA? Is it part of this semester? It would be immensely helpful to understand this for us to plan our implementation...

**Comment by RickardOh** [comment]
We are also very interested in this feature

**Comment by megnath777** [comment]
Hey There, Were are also looking for Network policy for Windows nodes, + 2 please (We have 2 projects with same need) 
 What other options do we have in absence of Calico? 
When I contacted Tigera (Caclio's company) they say they have something specifically for Windows container, but we have to install it in the windows worker Node , is this supported in the AKS worker nodes (I understand making changes in the worker node infrastructure is not actually supported. )

**Comment by keikhara** [comment]
Currently, we are targeting this year for calico. There are many dependencies work which must be done before we can deploy Windows calico. Once we have better dates, we will keep all of you posted.

**Comment by maxfridbe** [comment]
Also interested in this feature as we have dozens of namespaces that need newtwork isolation

**Comment by eNettMattD** [comment]
Is there any update on this @keikhara ?

**Comment by anhlqn** [comment]
Do we have an update for Calico Enterprise?

**Comment by AbelHu** [comment]
> Can this be closed since the feature is generally available (GA) now? Or are there capabilities missing from the GA? https://azure.microsoft.com/en-us/updates/generally-available-support-or-calico-network-policy-for-windows-node-pools/

Windows Calico is still not GA for now but will be soon.

**Comment by jkantharaj** [comment]
You can close it, thank you

**Comment by manali1st** [comment]
@allyford , @AbelHu : any tentative timeline on this for to have GA? we are also interested in having Windows network policy between pods in AKS
