### ISSUE TITLE
nodepool autoscaling not working

### ISSUE THREAD

**Issue by teyou** [Azure/AKS#1682]
**What happened**:
Nodepool auto scaling not working

**What you expected to happen**:
To be able to scale up once it needs to

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new cluster with 2 nodepool (1 for system + 1 for userpool)
<img width="698" alt="2-k8s-nodepools" src="https://user-images.githubusercontent.com/1115155/84844721-924ad600-b07d-11ea-9358-f153ae816689.png">

2. deploy app and scale it up in order to trigger node scale up

> kubectl describe configmap --namespace kube-system cluster-autoscaler-status
<img width="1154" alt="Screenshot 2020-06-17 at 8 30 48 AM" src="https://user-images.githubusercontent.com/1115155/84844750-a2fb4c00-b07d-11ea-8219-435f9522bdf7.png">

**Anything else we need to know?**:

**Environment**:
location : East US
Kubernetes version: 1.18.2 (preview)
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:18:00Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

Size of cluster: 3 worker nodes (2 within system nodepool and 1 within user nodepool)
```
kubectl get nodes
NAME                                STATUS   ROLES   AGE   VERSION
aks-agentpool-45817416-vmss000000   Ready    agent   15h   v1.18.2
aks-agentpool-45817416-vmss000001   Ready    agent   15h   v1.18.2
aks-userpool-45817416-vmss000000    Ready    agent   15h   v1.18.2
```

```
kubectl get pods                 
NAME               READY   STATUS             RESTARTS   AGE
logs-es-hot-0      0/1     Pending            0          11h
logs-es-hot-1      0/1     Pending            0          11h
logs-es-master-0   0/1     CrashLoopBackOff   129        11h
logs-es-warm-0     0/1     Pending            0          11h
logs-es-warm-1     1/1     Running            0          13h
```
Workloads description: 
- It is a new cluster I created to run elastic eck cluster.

**Comment by marwanad** [comment]
It seems like the service principal you're using doesn't have `Microsoft.Network/virtualNetworks/subnets/join/action` permission so its unable to send the scale requests. Can you please ensure your SP has those rights?

Those errors would usually be visible to you on the configmap but a bug from the core upstream project caused this issue and will be fixed in the next CA release.

**Comment by teyou** [comment]
Below is tips from support just in case one of you also encounter the same issue

Use the following command to retreive the SP of the cluster
> $spID=$(az resource list -n <my-akscluster> --query [*].identity.principalId --out tsv)

Verify service principal
> echo $spID

Then use the following command and substitute the correct resource group to assign the 
> az role assignment create --assignee $spID --role 'Contributor' --scope /subscriptions/<subscription-id>/resourceGroups/<vnet-resource-group>

Finally enable nodepool autoscaling, if it’s disabled.

**Comment by marwanad** [comment]
Fix has been merged. Will roll-out with next week's release. 

Feel free to re-open the issue if it comes up again.
