### ISSUE TITLE
Kubelet endpoints are not getting updated after nodes scale up or down

### ISSUE THREAD

**Issue by PrabhuMathi** [Azure/AKS#1684]
**What happened**:

When a node is scaled up or scale down in AKS cluster, kubelet end points are not getting updated with new subnets addresses. 

**What you expected to happen**:

kubelet end points should get updated automatically when new node addresses.

**How to reproduce it (as minimally and precisely as possible)**:
In AKS cluster 1.16.9, scalup a node in vmss instance and validate kubelet end points under kube system namespace. Only the initially created node addresses would be visible in it.

**Anything else we need to know?**:
Test this in AKS version 1.14.8, 1.15.10 and 1.16.9

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.9
- Size of cluster (how many worker nodes are in the cluster?): 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): microservices, java app
- Others:

**Comment by TomGeske** [comment]
@PrabhuMathi: Which IP are you referring to? Node IP?

**Comment by PrabhuMathi** [comment]
> @PrabhuMathi: Which IP are you referring to? Node IP?

Hi @TomGeske it is node IP.
But, did some more analysis on this issue and identified AKS does not create a explicit kubelet service in the cluster. 
This was created by our monitoring setup in Prometheus. We were using old setup and caused this issue. Fixed after updating the monitoring setup pointing to node service. You can ignore this from AKS perspective please.
Thanks,
Prabhu

**Comment by TomGeske** [comment]
@PrabhuMathi: Thanks for your feedback. I'm going ahead closing this issue. If you have further questions, please keep commenting.
