### ISSUE TITLE
kubelet /stats not working on Windows

### ISSUE THREAD

**Issue by zhiweiv** [Azure/AKS#1685]
We encouented same issue with https://github.com/kubernetes/kubernetes/pull/90554, we rely on /stats endpoint to monitor AKS clusters. It is not included in 1.17.6 yet(https://github.com/kubernetes/kubernetes/pull/91103). 

Do we have plan to fix it in AKS asap?

**Comment by andyzhangx** [comment]
I have already ping the approvers, let's wait for the cherry-pick merged first. thanks.

**Comment by keikhara** [comment]
This will be fixed in AKS 1.17.7. Expecting end of this week roll out.

**Comment by zhiweiv** [comment]
Verified fixed in 1.17.7.
