### ISSUE TITLE
az aks create|nodepool add --labels - labels ignored if prefix contains '.'

### ISSUE THREAD

**Issue by mathieu-benoit** [Azure/AKS#1689]
**Describe the bug**
`az aks create|nodepool add --labels`,  labels are ignored if their prefix contains '.'.

**To Reproduce**
- `az aks create --labels test.test/test=test`
- or `az aks nodepool add --labels test.test/test=test`

**Expected behavior**
As described here https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set, prefix in labels could contain '.'. And I don't think this associated regex takes this into account: https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_validators.py#L291

**Environment summary**
Azure CLI 2.5.0 (aks-preview extension not installed)

**Additional context**
FYI, in my case, I would like to set this label to my User nodepool: `kubernetes.azure.com/mode=user` since it's not added for me.

**Comment by seanmck** [comment]
Looks like an RP issue as problem repros in direct REST API calls as well.

**Comment by mathieu-benoit** [comment]
FYI @seanmck: I'm not able to reproduce the issue with Terraform: https://github.com/mathieu-benoit/myakscluster/blob/master/tf/aks.tf#L121

**Comment by gtxistxgao** [comment]
@mathieu-benoit 

Try to reproduce in az cli version 2.10. aks-preview extension not installed. Both ```az aks nodepool add --labels``` and ```az aks create --node-labels``` work well.


~$ az aks nodepool add --resource-group xxx --cluster-name xxxdemo --name nodepool3 **--labels a.b/c=d** -c 1
~$ k get node --show-labels | grep a.b/c=d
aks-nodepool3-xxx-vmss000000   Ready    agent   6m25s   v1.16.10   **a.b/c=d**,agentpool=nodepool3,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS2_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westus2,failure-domain.beta.kubernetes.io/zone=0,kubernetes.azure.com/cluster=MC_xxx_xxxdemo_westus2,kubernetes.azure.com/node-image-version=AKSUbuntu-1604-2020.06.30,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-nodepool3-xxx-vmss000000,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,storageprofile=managed,storagetier=Premium_LRS




~$ az aks create --resource-group xxx --name xxxdemo2 **--nodepool-labels a.b/c=d** -c 1
~$ k get node --show-labels
NAME                                STATUS   ROLES    AGE   VERSION    LABELS
aks-nodepool1-xxx-vmss000000   Ready    <none>   3s    v1.16.10   **a.b/c=d**,agentpool=nodepool1,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS2_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westus2,failure-domain.beta.kubernetes.io/zone=0,kubernetes.azure.com/cluster=MC_xxx_xxxdemo2_westus2,kubernetes.azure.com/mode=system,kubernetes.azure.com/node-image-version=AKSUbuntu-1604-2020.06.30,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-nodepool1-xxx-vmss000000,kubernetes.io/os=linux,storageprofile=managed,storagetier=Premium_LRS
