### ISSUE TITLE
kubectl proxy: "tls: oversized record received"

### ISSUE THREAD

**Issue by matkam** [Azure/AKS#169]
Just after starting a new AKS cluster and upgrading it to version 1.8.7. Trying to connect to http://127.0.0.1:8001/ui via `kubectl proxy` command, I get the following error:
```
Error: 'tls: oversized record received with length 20527'
Trying to reach: 'https://10.244.4.2:9090/'
```

**Comment by rtyler** [comment]
I'm also seeing this after an upgrade to 1.8.7. ☹️

**Comment by sethtregenna** [comment]
I upgraded from 1.8.2 to 1.8.7  due to the cluster failing and being unusable.  I now have this same issue.

**Comment by matkam** [comment]
Thanks @sethtregenna. Removing the "https" from the proxy url resolves the issue.

**Comment by xtophs** [comment]
I had to move to a 1.9 cluster to resolve the issue

**Comment by novaterata** [comment]
This is still an issue in 1.11.5. Removing https does nothing
