### ISSUE TITLE
When I try to build a cluster using cli

### ISSUE THREAD

**Issue by nidiculageorge** [Azure/AKS#1690]
az: error: unrecognized arguments: --node-resource-group rg-seab-uat-aksnode

The parameters where passed correctly

$NodeResourceGroup= 'rg-seab-uat-aksnode'

az aks create `
    --resource-group $ResourceGroupName `
    --name $ClusterName `
    --node-count $NodeCount `
    --enable-addons monitoring `
    --generate-ssh-keys `
    --network-plugin azure `
    --aad-server-app-id $ServerAPPID `
    --aad-server-app-secret $ServerAppSecret `
    --aad-client-app-id $ClientAPPID `
    --aad-tenant-id $TenantID `
    --windows-admin-password  $PASSWORD_WIN `
    --windows-admin-username azureuser `
    --node-vm-size $VmSize `
    --vm-set-type VirtualMachineScaleSets `
    --load-balancer-sku standard `
    --api-server-authorized-ip-ranges $apiserverIP `
    --node-resource-group $NodeResourceGroup `
    --nodepool-name $NodepoolName `
    --enable-cluster-autoscaler `
    --enable-managed-identity `
    --min-count $Mincount `
    --max-count $Maxcount `
    --network-policy azure `
    --vnet-subnet-id $Subnet_ID `
    --service-principal $SP_ID `
    --client-secret $SP_PASSWORD `
    --docker-bridge-address 172.20.0.1/16 `
    --dns-service-ip 10.3.0.10 `
    --service-cidr 10.3.0.0/16 `
    --max-pods 100 `
    --zones 1 2 3 `
    --verbose

**Comment by jluk** [comment]
@nidiculageorge the node RG parameter only exists in the aks-preview CLI extension, ensure that is installed and re-run the cmd with a resource group name that does not exist. Lmk if this does not work for you, but I have reproduced it working on the preview extension.

**Comment by nidiculageorge** [comment]
@jluk :can you please send the command line

**Comment by jluk** [comment]
run `az extension add -n aks-preview` to add the preview module

**Comment by nidiculageorge** [comment]
@jluk Is there anything that we have to apply before deploying the cluster like this

**Comment by jluk** [comment]
no, you should just run the same cmd as before the preview-module just has additional logic for the node rg parameter

**Comment by nidiculageorge** [comment]
Thanks @jluk
