### ISSUE TITLE
az aks disable-addons -a monitoring

### ISSUE THREAD

**Issue by biqas** [Azure/AKS#1691]
Hi I tried to disable the monitoring for an aks cluster with the following command:
az aks disable-addons -a monitoring -g "RECOURCE_GROUP" -n "CLSUTER_NAME" --subscription "MY_SUBSCRIPTION"

this is the result i get:
Operation failed with status: 'Bad Request'. Details: The specified service CIDR 10.0.0.0/16 is conflicted with an existing subnet CIDR

How can I disable monitoring??

**Comment by vishiy** [comment]
@biqas -  You seem to have CIDR collision. any update operation like enable/disable addon will fail if there is a CIDR collision. Looks like you added a new subnet to the VNet which is overlapped ? Please remove the subnet.

**Comment by biqas** [comment]
I have not added any subnet manually.

These are the subnets I have.
![image](https://user-images.githubusercontent.com/5908247/85950482-47726d80-b95d-11ea-930e-475e01607bab.png)

**Comment by palma21** [comment]
Any updates? If this is still a problem it's likely better to open a support ticket so we can take a quicker look into the cluster in question.
