### ISSUE TITLE
"Error syncing load balancer: failed to ensure load balancer: timed out waiting for the condition"

### ISSUE THREAD

**Issue by atrauzzi** [Azure/AKS#1692]
Just encountered this today and all I can say is I'm completely confused as to how a message like this can be helpful in diagnosing any issue.

The language here makes no sense.

**Comment by jluk** [comment]
Indeed this is an unhelpful error, if it's a show-stopper for your cluster can you please open a support request so we can take a look at what happened? We regularly groom error messages so they make sense, so we can definitely visit this one.

Closing in favor of support request as we'll need to investigate a bit into any LB issues.

**Comment by atrauzzi** [comment]
No thanks, convincing any support personnel Microsoft employs even of the context of this discussion would probably waste weeks of back and forth. Azure support is just completely unviable.

I honestly suggest you take this up internally as it's a comically shorter path.

**Comment by jluk** [comment]
I'm sorry you've had a poor experience with some support cases, it's going to be difficult to reproduce your configuration setup to ensure we can address what occurred to your cluster.

We did an investigation and did find these error messages actually stem from upstream Kubernetes, so they aren't AKS specific. We'll be looking into how AKS could catch these errors and improve them as we have done with some other K8s implementation errors.

https://github.com/kubernetes/kubernetes/blob/3a51aaf8b4baff1242ea30b08d599d913fe7a127/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L313

https://github.com/kubernetes/kubernetes/blob/3a51aaf8b4baff1242ea30b08d599d913fe7a127/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L384

**Comment by atrauzzi** [comment]
To be honest, it's 100% of my support cases have never resulted in any helpful outcomes. I usually end up with ISP-grade binder support.

The part in question here is _"timed out waiting for the condition"_. Not what k8s is generating.  I think it'll be up to AKS to leverage _context_ more to put more detail out beyond _"...the condition"_  :thinking: 

Is it telling me to mow my lawn?
