### ISSUE TITLE
Prometheus scrape metrics for kube-proxy

### ISSUE THREAD

**Issue by jakond1** [Azure/AKS#1695]
What Happened:

implementing prometheus matrics scraping of kube-proxy and found that matrics bind address are configured to localhost and thus we promethues exporters are not able to connect nodes.

AFAIK we cannot change the metrics bind address for the kube-proxy please suggest any other alternative

Reference: https://github.com/Azure/AKS/issues/1395

**Comment by davejhahn** [comment]
Same problem for me in 1.16.9, which was supposed to have been fixed in https://github.com/Azure/AKS/issues/1395

**Comment by nebed** [comment]
same problem in 1.16.10 as well
Reference: #1395

**Comment by m1o1** [comment]
Having this issue in 1.17.7 as well

**Comment by MaxHogervorst** [comment]
Same issue in 1.16.13

**Comment by tommyJimmy87** [comment]
any news on this? I have the same issue with 1.16 version

**Comment by nkolchenko** [comment]
Is it going to be fixed at all?  Simple Yes/No will do

**Comment by palma21** [comment]
This was not possible to be changed on the fleet for security concerns on clusters with 1.15 and prior. We'll take a look at this now that 1.15 has been removed.

**Comment by davidbIQ** [comment]
any update on this yet?

**Comment by zhongwutaos** [comment]
I have solved the problem by those commands:
kubectl edit configmaps kube-proxy
change metricsBindAddress: "" to metricsBindAddress: "0.0.0.0"
kubectl delete po -l k8s-app=kube-proxy
and then,you can see kube-proxy listen on *:10249

**Comment by davidbIQ** [comment]
Thanks, I think that worked on older clusters, I think I could do that on the 1.15 cluster.  On the 1.17.11 cluster though it doesn't look to have access to that config map:

```
PS C:\srciq\k8s.development\azure-development\namespaces\monitoring\kube-prometheus-stack> kubectl get configmaps -nkube-system
NAME                                 DATA   AGE
cluster-autoscaler-status            1      18h
coredns                              1      28d
coredns-autoscaler                   1      28d
coredns-custom                       0      28d
extension-apiserver-authentication   6      28d
kubernetes-dashboard-settings        0      17d
tunnelfront-kubecfg                  1      28d
```

**Comment by uvw** [comment]
@palma21 Can you provide any details on how the issue was fixed and when the fix was released, please?

I upgraded an AKS cluster to v1.19.3, and there is no `kube-proxy` config map or any indication of `metricsBindAddress` in the daemon set spec. The metrics `{podIP}/metrics` endpoint does not respond either.
