### ISSUE TITLE
NSG generated by aks does not handle whitelising of internal ips correctly

### ISSUE THREAD

**Issue by landro** [Azure/AKS#1696]
**What happened**:

I created an internal load balancer as described here: https://docs.microsoft.com/en-us/azure/aks/internal-lb#create-an-internal-load-balancer

I set the loadBalancerSourceRanges field on the service in order to whitelist ip src addresses 

However, in the generated NSG, the default rule (65000) will allow any vnet traffic, basically meaning the whitelist is of no use.

**What you expected to happen**:

I expect traffic from ip addresses other than the ones listed in loadBalancerSourceRanges to be denyed

**Environment**:

kubernetes 1.15.10

**Comment by palma21** [comment]
@feiskyer could you help?

**Comment by feiskyer** [comment]
@landro The internal network connectivity is enabled by default, hence I think you need to create the deny rules with higher priority than 65000.

**Comment by landro** [comment]
The NSG (and its rules) is generated (and probably also reconciled?) by AKS, and typically called something like aks-agentpool-123123123-nsg. I therefore don't think it makes sense to manually add a deny rule like you suggest, @feiskyer .

**Comment by landro** [comment]
Please reopen @palma21 - the answer provided does not solve this issue.

**Comment by palma21** [comment]
The nsg aks uses are normally on the NIC level, you can use ones at subnet level to provide this.
`loadBalancerSourceRanges` was designed with the ELB scenario in mind where for ILB the recommendation is NSG.

I think we can make a feature request upstream to support internal CIDRs for `loadBalancerSourceRanges` @feiskyer wdyt?

**Comment by feiskyer** [comment]
> I think we can make a feature request upstream to support internal CIDRs for loadBalancerSourceRanges @feiskyer wdyt?

blocking access from the same subnet may break a lot of customers since the assumption is no restriction by default. I'm not sure why customers couldn't add the default deny rules by themselves since they have more context how the connectivity is restricted?

**Comment by landro** [comment]
Please reopen and remove the answer provided tag.

Would it make sense to add an extra aks-specific annotation to the Service in order to have AKS deny Vnet traffic? 
Regarding your suggestion/comment @feiskyer - I believe it would be really flaky to let customers add random rules to the nsgs manually - that's really really far away from industry standard concepts like infrastructure as code and the likes.

**Comment by feiskyer** [comment]
@landro that makes sense, thanks. We could add a new annotation, and the deny rule would only be added when this annotation is added to the service.

I opened https://github.com/kubernetes-sigs/cloud-provider-azure/issues/374 to track this feature.
