### ISSUE TITLE
can't multi-jump versions for linux nodepool from 1.14.8 to latest version

### ISSUE THREAD

**Issue by bandarusrinivas** [Azure/AKS#1697]
I have an AK cluster running on 1.16.9 but the nodepools "OrchestratorVersion" sitting behind at 1.14.8. I am using Terraform deployment but the nodepools are not getting updated

az aks nodepool upgrade --name default --resource-group dev_rg-abc5oz2p -k 1.16.9 --cluster-name aaarkpgflyhisbbb
Operation failed with status: 'Bad Request'. Details: Upgrade agent pool version from 1.14.8 to 1.16.9 is not allowed, you can only upgrade one minor version at a time. Please use [az aks get-upgrades] command to get the supported upgrade paths. For more information, please check https://aka.ms/version-skew-policy
Note: I tried to upgrade from 1.14.8 to + versions and everytime it complains about "you can only upgrade one minor version at a time." Atleast if know what version is supported i can definitely try. I think this is a bug or let me know how to updrade to latest?

**Comment by jluk** [comment]
You will need to upgrade from a 1.14.x version to a 1.15.x before you can target 1.16. The valid options are 1.15.11 and 1.15.12.

You can retrieve viable target versions by using get-versions command. Please let us know how that works for you.

```
➜  ~ az aks get-versions -l westus
The behavior of this command has been altered by the following extension: aks-preview
KubernetesVersion    Upgrades
-------------------  -------------------------------------------------
1.18.2(preview)      None available
1.18.1(preview)      1.18.2(preview)
1.17.5(preview)      1.18.1(preview), 1.18.2(preview)
1.17.4(preview)      1.17.5(preview), 1.18.1(preview), 1.18.2(preview)
1.16.9               1.17.4(preview), 1.17.5(preview)
1.16.8               1.16.9, 1.17.4(preview), 1.17.5(preview)
1.15.11              1.16.8, 1.16.9
1.15.10              1.15.11, 1.16.8, 1.16.9
1.14.8               1.15.10, 1.15.11
```

**Comment by bandarusrinivas** [comment]
Thanks @jluk , for the future purpose how do i know which version i can able to upgrade , in this case i was on 1.14.8 and wanted to step up to higher. Any Kubectl commands to know eligible nodepool version? Also when when i did upgrade my AKS cluster version why the nodepool are behind?

**Comment by bandarusrinivas** [comment]
update since my previous comment. Upgarde took more than an hour and i am finally able to upgrade nodepool 1.14.8 --> 1.15.11 --> 1.16.9. Thanks. other questioner for my education, how to upgrade nodepool along with AKS cluster version upgrade?

**Comment by jluk** [comment]
Thanks for confirming, the upgrade operation can be checkpoint by clients differently which likely caused portal and cli to show an updated node version but the cli command was still running to completion.

If you use the az aks get-versions command, you can map valid versions from the left table of what version a resource currently is on.

If you run az aks upgrade, meaning you have run a managed cluster upgrade, it will sync all your agentpools to your control plane version. I would recommend running the single cluster upgrade if you don't need multiple pools on different versions.

Hope this helps! Closing as a result.
