### ISSUE TITLE
Accessing Private AKS cluster API via ingress or Azure Application Gateway- API pod missing in kube-system

### ISSUE THREAD

**Issue by naveenkumarsp** [Azure/AKS#1698]
We have deployed a private AKS cluster. Since DNS servers hosted in on-prem servers our local DNS address is unable to forward the API endpoint to Azure private DNS. 

Hence we are thinking to host the API using ingress or Azure ALB using URL re-write with Service account for Integrating the stack with DevOps tools and security scanning tools.

Please provide your thoughts and challenges on above approach. Also suggest any better approach which could meet our purpose. 

Also I was unable to find the API pod in kube-system which we have planned to expose into a cluster IP based service.

**Comment by palma21** [comment]
AKS is a managed service, you don't have visibility into the control plane components.

@TomGeske @feiskyer to help with the on-prem DNS setup

**Comment by TomGeske** [comment]
Did you check [customer forwarder](https://docs.microsoft.com/en-us/azure/aks/private-clusters#hub-and-spoke-with-custom-dns) to forward DNS queries for or API server FQDN?

**Comment by naveenkumarsp** [comment]
Hi tom, Thanks for reviewing. 

As stated above the DNS servers are hosted on-prem.  Our AD team has tried configuring custom forwarder and they stated that its not possible. 

Hence i was looking toward any alternative like exposing API via ingress endpoint through which we can access it in Azure VNET.

**Comment by TomGeske** [comment]
Can you share more details why it's isn't possible to use custom forwarder with on prem DNS? You may see this behavior with other services using private link.

As a temporary workaround you could consider using host file to access your API server.

**Comment by naveenkumarsp** [comment]
The issue is  DNS forwarder was not resolving the private link domain since DNS  server is hosted in On-prem. 

Yes, as a workaround we are thinking to make a host file entry at this time.

**Comment by TomGeske** [comment]
You may want to check [this article](https://github.com/dmauser/PrivateLink/tree/master/DNS-Integration-Scenarios). 

Idea is your on-prem DNS server forwards [certain domains](https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns) (e.g. privatelink.{region}.azmk8s.io) to the forwarder and the forwarder uses your private DNS zone.
