### ISSUE TITLE
Unable to start container for Dotnet core exe on AKS cluster

### ISSUE THREAD

**Issue by NileshGule** [Azure/AKS#1699]
**What happened**:
I have been deploying .Net Core 2.1 containers for project type exe for more than 2 years.
The Kubernetes manifest file contains references to environment variables.
https://github.com/NileshGule/pd-tech-fest-2019/blob/master/k8s/TechTalksConsumer/consumer-deployment.yml

I have also upgraded this code to 3.0 version and it had worked perfectly until 2 weeks ago.
With the latest version of AKS cluster the container is unable to start. It keeps crashing.

I have tried specific versions of Kubernetes like 1.15.10, 1.16.3, and the default version in South East Asia. In all cases the deployment keeps failing with the same error.
<img width="1512" alt="Dot net core exe crash loop backoff" src="https://user-images.githubusercontent.com/1298374/85755747-c9d21600-b740-11ea-8ae0-111ed100b1c4.PNG">

**What you expected to happen**:
Project types of exe should work fine on AKS

**How to reproduce it (as minimally and precisely as possible)**:
Clone the repo https://github.com/NileshGule/pd-tech-fest-2019/

Update the Subscription name in the InitializeAKS.ps1 file to the correct Azure subscription

Execute deployall.ps1 script which deploys all the required manifests to AKS cluster.

**Anything else we need to know?**:
I have tried using ACR as well as DockerHub as container registry options. On earlier occasions both these have worked perfectly fine.
The AKS cluster is created with managed identities.

**Environment**:
- Kubernetes version (use `kubectl version`): client ->1.18.2 , server -> 1.15.10
- Size of cluster : 2
- General description of workloads in the cluster : simple dotnet core app consisting of Producer & consumer for RabbtiMQ
- Others: KEDA is used for autoscaling containers

**Comment by lucasmaj** [comment]
I would think container is starting but you programs is failing. Have you tried

`kubectl logs [container-name-here]`

**Comment by NileshGule** [comment]
> I would think container is starting but you programs is failing. Have you tried
> 
> `kubectl logs [container-name-here]`

Thanks for the suggestion. It did turn out to be an application specific issue. I have been using Helm charts to deploy RabbitMQ on AKS cluster. Something changed in the RabbitMQ and the user ID and password were not getting set which cause the application container failure while trying to connect to the RabbitMQ service.

The issue can be closed
