### ISSUE TITLE
Cluster creation fails in West US 2

### ISSUE THREAD

**Issue by cloudworkshops** [Azure/AKS#17]
C:\Users\walterm\Development>az aks create --resource-group aks --name myK8sCluser --agent-count 1 -s Standard_D2_V2 --location westus2
**Deployment failed. Correlation ID: d6b97aa4-94bd-4738-8ebf-84986c667b0f. getAndWaitForManagedClusterProvisioningState error: <nil>**

**Comment by berndverst** [comment]
Should be resolved. See #2. Please try again

**Comment by slack** [comment]
Closing issue, cluster creation in West US 2 should be working.
