### ISSUE TITLE
Installing the ACI connector fails "Could not find tiller"

### ISSUE THREAD

**Issue by rtyler** [Azure/AKS#170]
From the Azure Cloud Shell:

```
tyler@Azure:~$ az aks install-connector -n kubes -g mygroup --connector-name aci
Merged "kubes" as current context in /tmp/tmpjgx6m3tf
Finished service principal creation[##################################]  100.0000%Deploying the ACI connector for 'Linux' using Helm
Error: could not find tiller
tyler@Azure:~$
```

This is for a 1.8.7 cluster in `eastus`

**Comment by marrobi** [comment]
Helm isn't installed on AKS by default. Try running ```helm init``` first. Looks like an oversight in the CLI command.

**Comment by rtyler** [comment]
@marrobi is this ticket sufficient to get that addressed, or must I file another ticket somewhere else?

**Comment by marrobi** [comment]
Yes should be, I believe the product team review these issues. Looks like @julienstroheker and @mboersma  worked on the initial PR for this feature and may be able to confirm.

**Comment by julienstroheker** [comment]
When we coded the initial `install-connector` feature, AKS came with the tiller deployed per default.

If this changed, I don't know if we want to automatically install the tiller from this cmd line? Maybe just add a warning and ask to install it first ?

**Comment by marrobi** [comment]
The helm not being installed is referenced here #4 . A warning feels like a good option, might also want some error checking for tiller being installed but in a bad state?

**Comment by seanknox** [comment]
As others have mentioned, Tiller is not preinstalled on AKS clusters. We have a feature request to do so.
