### ISSUE TITLE
[Already Patched] AKS patching of MitM attacks via IPv6 rogue router advertisements 

### ISSUE THREAD

**Issue by leonard520** [Azure/AKS#1701]
As mentioned in [issue](https://github.com/kubernetes/kubernetes/issues/91507), we have to upgrade our cluster to version 1.16.11 or above. 
However, in another aspect, due to some breaking change in 1.17.x for CRD, we don't want to upgrade to 1.17.x for now.
Can we support version 1.16.11 or above?

**Comment by jluk** [comment]
The issue linked is actually already patched in all GA versions running in AKS, so this should be covered already. Here is the relevant notice: https://azure.microsoft.com/en-us/updates/cni-security-vulnerability-in-older-aks-clusters-and-mitigation-steps/

Closing as a result of that, but just comment and will revisit.
