### ISSUE TITLE
Disabling Default service account for Namespaces

### ISSUE THREAD

**Issue by dewanymca** [Azure/AKS#1702]
Hi Team

As part of security review, we have been asked to move away from default service account and used custom service account per app. We have app written in .net core and we don't use any of kubernetes functionality calling Api-server to get data or soemthing like that. So what we are planning to do, just create service account with no role and rolebindings. Also disable serviceAccountAutomaticMounts.

Is this an acceptable things. Will it cause any issue in platform, monitoring or any kubernetes related thing?

2nd question: Is there a way we can change default service account role and rolebindings to provide minimum access while provisioning so that we can keep using Defaut account.

Please help.

Thanks
Deepak Sanghi

**Comment by weinong** [comment]
you need to  set `automountServiceAccountToken: false` in your service account.
you can use a mutating webhook to automatically apply this setting (do exclude kube-system ns).
and the same time you can use gatekeeper for enforcement

**Comment by dewanymca** [comment]
Thanks can you please share examples of mutating we hook and gatekeeper

**Comment by palma21** [comment]
@ritazh @sozercan do you know if there's an example upstream for this?

+ @LizMS @jluk for feedback on potential built-in.

**Comment by weinong** [comment]
gatekeeper does not mutate kubernetes resources (yet). it's good for enforcing by denying or auditing the requests.

you will need to write some code for mutating webhook server. [this](https://medium.com/ovni/writing-a-very-basic-kubernetes-mutating-admission-webhook-398dbbcb63ec) is one basic example.
