### ISSUE TITLE
Creating agent pools using agentPoolProfiles object vs resources/Microsoft.ContainerService/managedClusters/agentPools

### ISSUE THREAD

**Issue by adhodgson1** [Azure/AKS#1703]
Which is prefered, and are there any advantages to creating the additional agent profiles using the nested resources section in an ARM template as opposed to the older agentPoolProfiles array? I am looking to have an ARM template which will add node pools to an existing cluster if the cluster already exists.

**Comment by TomGeske** [comment]
agentPoolProfiles array is our current [API](https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters)

By nested resources you refer to [linked templates](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/linked-templates)?

**Comment by adhodgson1** [comment]
According to the documentation here:
https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-overview

You can create a resources section in the Microsoft.ContainerService/managedClusters object.  The example shows the following:

{
  "name": "string",
  "type": "Microsoft.ContainerService/managedClusters",
  "apiVersion": "2020-04-01",
  "location": "string",
  "tags": {},
  "properties": {
[...]
    "agentPoolProfiles": [
      {
[...]
      }
    ],
[...]
  "resources": []
}
If we look at the documentation it refers to the resources section:
Name	Type	Required	Value
resources	array	No	agentPools

**Comment by TomGeske** [comment]
I'm not following. Can you post what you are aiming to do including your ARM template?

Are you referring to the resources array below?

![image](https://user-images.githubusercontent.com/3658893/89766418-69344800-daf8-11ea-8c80-d7a22476e727.png)
src: https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters

**Comment by adhodgson1** [comment]
Yes indeed. So I tested this myself this week and the answer to my question is yes, I can add additional resource pools to an existing cluster using this resources array, so that is what I am now doing with my ARM template.
