### ISSUE TITLE
Question: Can I programmatically get all available Kubernetes versions in a given region using .NET SDK ? 

### ISSUE THREAD

**Issue by karok2m** [Azure/AKS#1705]
I am looking for a programmatic way to get available Kubernetes versions in a given region using .NET SDKs. Something similar to the following Azure CLI command:

```bash
az aks get-versions --location eastus --output table
```

Specifically, I am using `Microsoft.Azure.Management.ContainerService.Fluent.ContainerServiceManagementClient` class to create clusters and get details of existing cluster. I can use any other .NET SDK for this as well.

**Comment by karok2m** [comment]
I also posted the same question on StackOverflow: [Get all available Kubernetes versions in a given Azure region using .NET SDK](https://stackoverflow.com/questions/62696812/get-all-available-kubernetes-versions-in-a-given-azure-region-using-net-sdk)

**Comment by TomGeske** [comment]
@karok2m you can use our REST API to query this,
Did you manage to use the code sample provided @ StackOverflow?

**Comment by karok2m** [comment]
@TomGeske, I ended up using `Microsoft.Azure.Management.Fluent` package and its `IAzure` interface. The code looks something like this:

```
var azure = Azure
    .Configure()
    .Authenticate(azureCredentials)
    .WithSubscription(subscriptionId);

var kubernetesVersions = await azure
    .KubernetesClusters
    .ListKubernetesVersionsAsync(region, cancellationToken);
```

The peculiarity of this call is that it returns much more results than `az aks get-versions`. So I had to find latest patch version of a specific Kubernetes version (`1.16.x`) that I was looking for. But I would have to do this filtering in any case.

**Comment by TomGeske** [comment]
@karok2m seems like ListKubernetesVersionsAsync returns a string list only. You may want to use REST API to query and parse by yourself. 

https://docs.microsoft.com/en-us/rest/api/container-service/container%20service%20client/listorchestrators

**Comment by karok2m** [comment]
@TomGeske, I will close this issue as I managed to get available Kubernetes versions with Fluent APIs, and it can also be done with REST APIs as you suggested.
