### ISSUE TITLE
Security Context-Failed to Create CoreCLR

### ISSUE THREAD

**Issue by dewanymca** [Azure/AKS#1710]
We are trying to put security context at POD and container Level for .net core application. Below is snippet of yaml file which we used to enable securityContext:

***********************************
        securityContext:
          allowPrivilegeEscalation: false # Always use false
          privileged: false # Always use false
          readOnlyRootFilesystem: true # Recommended to use true
          runAsGroup: 3000 # Optional if already specified at pod scope
          runAsNonRoot: true # Optional if already specified at pod scope
          runAsUser: 1000 # Optional if already specified at pod scope
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000 #Always non-zero
        runAsUser: 1000 #Always non-zero
        runAsNonRoot: true 
        supplementalGroups:
          - 4000 # Optional
      terminationGracePeriodSeconds: 120
************************************
 
![image](https://user-images.githubusercontent.com/15336470/86583387-ca6c7700-bfa0-11ea-9ec8-693add7ced2d.png)

After enabling this, POD is failing with error “Failed to Create CoreCLR”.

We are not sure what is the issue. Can you please help how to resolve this?

 

Thanks
Deepak Sanghi

**Comment by palma21** [comment]
That error is specific from dotnet trying to do something and not having access here's the related thread on the dotnet repo with workarounds. From the looks seems like the issue is the read only filesystem.
https://github.com/dotnet/runtime/issues/9336

Closing to allow the conversation to proceed there.
