### ISSUE TITLE
Support of Ultra SSD

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#1712]
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disks-enable-ultra-ssd

**Comment by andyzhangx** [comment]
UltraSSD support on AKS would be ready very soon

**Comment by andyzhangx** [comment]
it's now in Preview now: https://docs.microsoft.com/en-us/azure/aks/use-ultra-disks

**Comment by asubmani** [comment]
@jnoller Will UltraSSD help mitigate this issue https://github.com/Azure/AKS/issues/1373  (cannot reference it any more). 
we are running into this issue sporadically even after using P20 disks for dedicated system nodepools. 
Overall it seems like going to containerd might give us some relief. We are currently using D4asV4 and D8asV4 series as our pod usage is low mem/cpu & stateless.

**Comment by andyzhangx** [comment]
> @jnoller Will UltraSSD help mitigate this issue #1373 (cannot reference it any more).
> we are running into this issue sporadically even after using P20 disks for dedicated system nodepools.
> Overall it seems like going to `containerd` might give us some relief. We are currently using D4asV4 and D8asV4 series as our pod usage is low mem/cpu & stateless.

@asubmani that issue is mainly caused by io throttling on os disk, try use ephemeral os disk to mitigate this issue:
https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#use-ephemeral-os-on-new-clusters

**Comment by asubmani** [comment]
> @asubmani that issue is mainly caused by io throttling on os disk, try use ephemeral os disk to mitigate this issue:
> https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#use-ephemeral-os-on-new-clusters

@andyzhangx At present we increased `os_disk_size` from 128--> 512GB disks to get some relief from this issue. It seems that if we use 512GB for ephemeral OS Disk, we have to choose a VM sku that has 512GB max cache, which puts in in the priciest VM SKU category.

we have approx. 500 pods per cluster. Our workloads are stateless (state is stored in cosmos & service bus; nothing on container OS & no PVC)  Max memory used for top 10 = 1GB, MAX CPU used in top 5 = 1500Mc, we run approx 10-15 pods on avg per node. and use D4as_v4  & D8as_V4 AMD series. 

we can move to Ephemeral but as per doc,  it seems we have to choose a high cpu/mem VM SKU even though we do not need    it.

**Comment by asubmani** [comment]
Overall it looks like we need to move to ephemeral OS, and disable read/write caching on the OS Disk.

**Comment by palma21** [comment]
GA
