### ISSUE TITLE
[Feature Request] make new-pod-scale-up-delay configurable in autoscaler profile

### ISSUE THREAD

**Issue by zhiweiv** [Azure/AKS#1716]
Per https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md

> By default, scale-up is considered up to 10 seconds after pod is marked as unschedulable, and scale-down 10 minutes after a node becomes unneeded. There are multiple flags which can be used to configure these thresholds. For example, in some environments, you may wish to give the k8s scheduler a bit more time to schedule a pod than the CA's scan-interval. One way to do this is by setting --new-pod-scale-up-delay, which causes the CA to ignore unschedulable pods until they are a certain "age", regardless of the scan-interval. If k8s has not scheduled them by the end of that delay, then they may be considered by the CA for a possible scale-up.

That is exactly what we need for job pod pools. It is good to be able configure new-pod-scale-up-delay in AKS  autoscaler profile.

**Comment by zhiweiv** [comment]
@marwanad 
Does AKS plan to implement this in near future? Or just added it to backlog?

**Comment by marwanad** [comment]
@zhiweiv yup it will be added soon. I'll follow-up with an update.

**Comment by TomGeske** [comment]
Current ETA for deployment is end of September 2020.

**Comment by zhiweiv** [comment]
Any update?

**Comment by marwanad** [comment]
@zhiweiv This should be available with the [September API](https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate#autoscalerprofile). CLI support + Docs slated for end of month. Note that the acceptable time unit is seconds so valid values are: 10s, 360s, etc.

**Comment by marwanad** [comment]
This should be now available in CLI 2.12.0, CLI-extensions 0.4.63 and via ARM templates.

Feel free to report back on this thread if you hit issues.

**Comment by zhiweiv** [comment]
It should work now, I can see newPodScaleUpDelay in autoScalerProfile after update.

Will https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler#using-the-autoscaler-profile be update to reflect this change?
