### ISSUE TITLE
Kubectl exec command failing

### ISSUE THREAD

**Issue by nidiculageorge** [Azure/AKS#1717]
Hi Team,

Any idea why this command is failing 

![image](https://user-images.githubusercontent.com/43850474/86898777-c23e4400-c126-11ea-9fa4-1ae04993a8e7.png)

We need to get into a pod and exec a curl command

**Comment by zhiweiv** [comment]
Can you paste the image of this deployment?

**Comment by nidiculageorge** [comment]
@zhiweiv you mean the yaml file

**Comment by zhiweiv** [comment]
Seems arbabu/trojan-wall:v2 is a priavte image, do you know the base image it is using?

**Comment by nidiculageorge** [comment]
@zhiweiv thanks for the promp response.We will check and let know.

Basicall ia m trying to host a hello-world container in our cluster just to call from outside ,to check pods are running fine.Do you have ny yaml file fro tthat .After deployment I am trying to run the exec commnd to check one communication

**Comment by zhiweiv** [comment]
bash does not exist in your image, you can try ash.
`kubectl exec -it test ash`

**Comment by nidiculageorge** [comment]
@zhiweiv you mean

kubectl exec -it <podname> ash -n test

**Comment by zhiweiv** [comment]
Yes, that is an example, you should run kubectl exec -it podname ash -n test.

**Comment by nidiculageorge** [comment]
Great thanks @zhiweiv is there any commnd for curl,as curl is not working for ash,i think wget should work

![image](https://user-images.githubusercontent.com/43850474/86903875-8e1a5180-c12d-11ea-88db-bb45497609cd.png)

**Comment by zhiweiv** [comment]
You can use wget since it is available in your container.

**Comment by nidiculageorge** [comment]
@zhiweiv Just out of curiosity, how did you find out the image and which command can run it it

**Comment by zhiweiv** [comment]
If bash is not available, it is probably an alpine based image, ash is the default shell of alpine linux.

**Comment by nidiculageorge** [comment]
Great thanks for the support
