### ISSUE TITLE
Upgrading the cluster to higher version from Azure portal wont upgrade the Nodepool version

### ISSUE THREAD

**Issue by nidiculageorge** [Azure/AKS#1718]
Hi Team,

When we try to upgrate the cluster from the azure portal ,it wont upgrade the Nodepool version.

Is it a bug. The Nodepool version remains the same.We have only one Nodepool ,and also when checked cannot upgarde to the same version as KUBERNETES VERSION.

**Comment by TomGeske** [comment]
Did you upgrade in Nodepool section?

![image](https://user-images.githubusercontent.com/3658893/88378463-56eca700-cda1-11ea-8a3e-2bf0eaf4c20b.png)

**Comment by nidiculageorge** [comment]
@tomGeske I have tried upgrading it from the Azure portal directly

**Comment by TomGeske** [comment]
@nidiculageorge 

In our portal experience you first need to upgrade the control plane and afterwards upgrade your node pool(s). 

If you want to upgrade everything at once you may want to [consider cli](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-upgrade):

`az aks upgrade --kubernetes-version 1.17.7 --name myManagedCluster --resource-group myResourceGroup`
