### ISSUE TITLE
Readonlyfilesystem container security policy

### ISSUE THREAD

**Issue by dewanymca** [Azure/AKS#1727]
Hi Team

We have been read only file system attribute in container security policy with .net Core app. .Net core stream input request to disk if size is greater than 30kb. And for those request we get read only file system. We understand it’s because of readonlyfilesystem attribute, but does this attribute make full file system including user space. Is there an option to make root file system readonly and user one as writable.

Please help.

Thanks
Deepak Sanghi

**Comment by palma21** [comment]
could you provide a bit more details on what your app is doing and your pod manifest?
