### ISSUE TITLE
AKS cluster with pre-existing IP Address for API server (public and Private)

### ISSUE THREAD

**Issue by asubmani** [Azure/AKS#1729]
**AKS does not allow selecting an existing I.P address for API server (public or private)**:

**Allow:

**provision an AKS cluster using any available method (portal, Terraform, az cli, powershell:

**IT security teams won't allow opening network firewall rules without an I.P Address**:

**AKS 1.16.9**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (N/A)
- regular AKS cluster (Not private) with UDR mode.

**Comment by palma21** [comment]
Hi, thanks for the question.

Not sure I understood it fully. The AKS control plane is managed by MS so you're not able to select a public IP from your control to associate to it. 

When you use private clusters - https://docs.microsoft.com/en-us/azure/aks/private-clusters - The ip comes from your node network and there shouldn't be any firewall rules needed to be open (for the API) you still need the noted rules from here:
https://aka.ms/aks/egress

**Comment by asubmani** [comment]
Thanks @palma21,  we tried private clusters, however ran into the documented restrictions, especially the "UPTIME SLA". Also heard from community that this is not compatible with UDR mode.
We use Azure firewall and have found that allowing "application rule" to `*.hcp.eastus.azmk8s.io,*.tun.eastus.azmk8s.io,aksrepos.azurecr.io`  (among several others) is INSUFFICIENT,  as AZ FW looks for SNI-HEADERS.  So anything that talks to API over the tunnel pod gets rejected (e.g. aad-pod-identity, flux). 

We have explicitly allow 443 to the I.P address of the API servers. *OR* override the `KUBERNETES_SERVICE_HOST` in our deployment yamls to include the API server address.
*or* we deploy to `kube-system` namespace 

https://github.com/Azure/aad-pod-identity/issues/467  is the specific issue we encounter if we don't allow the I.P of the API server.

For now I will revert back to Public API + Authorized I.P ranges and check out private clusters next quarter. 
NOTE: An alternate suggestion is to use the **same public I.P** of a failed/2bmodified AKS cluster. This would help if I want to re-deploy my cluster for changing network policy mode, max pod per node, move from `Loadbalancer` to `UDR`  -- all of which would require a re-creation of the cluster.

Thank you!

**Comment by palma21** [comment]
Private clusters if definitely compatible with UDR. Uptime SLA is something we're working on right now for it.

I think your issue with Pod Identity will be solved with the addon, and great points on those use cases.

Happy to say we're looking at ways to support updates for all (sometimes it might be a bit disruptive, but will allow you to keep the same cluster config).

For max pods in specific, you could in the meantime add a new nodepool with your new max pods and delete the old :)

I'll close this issue for now as we're tracking each individual request, but let us know if something is missing. Thanks for your feedback
