### ISSUE TITLE
kubectl get componentstatus fails for scheduler and controller-manager

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [Azure/AKS#173]
**Problem:**
When running `kubectl get componentstatus` on an aks cluster the health checks for scheduler and controller-manager are failing.

Example output:
```
$ kubectl get componentstatus
NAME                 STATUS      MESSAGE                                                                                        ERROR
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: getsockopt: connection refused
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: getsockopt: connection refused
etcd-0               Healthy     {"health": "true"}
```

**Expected:**
Scheduler and controller-manager health checks will report success when they are healthy.

**Steps to reproduce:**
```
az aks create --name <MY-CLUSTER-NAME> --resource-group <MY-RESOURCE-GROUP>
az aks get-credentials --name <MY-CLUSTER-NAME> --resource-group <MY-RESOURCE-GROUP>
kubectl get componentstatus
```
Then failed health checks will appear.

-------

This appears to be related to: https://github.com/kubernetes/kubernetes/issues/19570

**Comment by slack** [comment]
Will track upstream issue.

**Comment by IanMoroney** [comment]
We're experiencing this issue also and it's preventing us from creating Azure resources through Rancher such as load balancers and public IP addresses.

**Comment by slack** [comment]
@IanMoroney this issue only covers `component status`. Because AKS runs controller-manager, scheduler, and etcd in a different topology than upstream expects (different hosts) the upstream assumptions are incorrect.

This _should_ have no impact on the ability to create lbs, ips, etc.

**Comment by hugohenley** [comment]
Same here, but with Rancher + AWS.

**Comment by kkannan1982** [comment]
Any updated on this... I am waiting for the fix... 2.1.0 still dont have the fix for it.

**Comment by JasonvanBrackel** [comment]
@kkannan1982 We are beholden to upstream work by the AKS team and by the Kubernetes community.  The feature is broken fundamentally in Kubernetes and will not be fixed (see https://github.com/kubernetes/features/issues/553 and https://github.com/kubernetes/kubernetes/issues/19570#issuecomment-354812863).

The replacement for it is still in development https://github.com/kubernetes/kubernetes/issues/18610

So unless AKS wants to write a workaround, or sig-clusterlifecycle changes their mind, we're stuck here for now and you'll need to instrument other methods to check health.

**Comment by Saibamen** [comment]
Any updates?

**Comment by lavanyaanbuatgmaildotcom** [comment]
I am facing the same issue, Any update

**Comment by lowtech81** [comment]
Any updates?

**Comment by jnoller** [comment]
Please see the comment above: https://github.com/Azure/AKS/issues/173#issuecomment-429014619

**Comment by NRDiaz92** [comment]
Hey guys, is there any updates with this?

Has AKS done some workaround or something?

**Comment by acaraion** [comment]
Hey there, any updates on this?

**Comment by jrudley** [comment]
Same issue here
k8s version 1.14.8
kubectl version:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by cayohollanda** [comment]
Any updates??

**Comment by Ziul** [comment]
Any updates? Getting the same error on a local cluster managed by Rancher. The `scheduler` gets healthy sometimes.

`Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}`

```bash
$ k get cs
NAME                 STATUS      MESSAGE                                                                                     ERROR
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused
scheduler            Healthy     ok
etcd-0               Healthy     {"health":"true"}
```

**Comment by kutsyk-neocles** [comment]
Any updates?

**Comment by jmorcar** [comment]
+1 any updates?

**Comment by elvishsu66** [comment]
Looks like lots of people are having the same issue. So let me ask - "do we have updates?"

**Comment by JasonvanBrackel** [comment]
It's not a Rancher issue, it's also not an AKS issue, it's an upstream Kubernetes issue.  You can find out more information here https://github.com/Azure/AKS/issues/173#issuecomment-429014619

**Comment by kubealex** [comment]
still here in 1.18x

**Comment by mitchellmaler** [comment]
I wouldn't expect a change for this issue. Upstream Kubernetes want's to deprecate component status and does not plan on enhancing it. If you need to check for cluster health using other monitoring sources it recommended.

kubernetes/kubernetes#93171 - 'fix component status server address' which is getting recommendation to close due to deprecation talk.
kubernetes/enhancements#553 - Deprecate ComponentStatus
kubernetes/kubeadm#2222 - kubeadm default init and they are looking to 'start printing a warning in kubect get componentstatus that this API object is no longer supported and there are plans to remove it.'

**Comment by KONY128** [comment]
same problem here with kubernetes 1.18x

**Comment by Coresummer** [comment]
same problem here with kubernetes 1.18.6 on Raspi4 Ubuntu20.04 x64

**Comment by palma21** [comment]
As @mitchellmaler correctly stated this capability will be removed and is not being maintained any further upstream.

Let us know on a separate ticket what is your use case and we can look into the best way to support it.

Thank you!

**Comment by manjeetsorout** [comment]
any update?

**Comment by mitchellmaler** [comment]
@manjeetsorout I have already provided an update and @palma21 has close this issue since it is not something to be "fixed" since upstream kubernetes is deprecating component status and going to be removing it.

**Comment by CzarMich** [comment]
From what I can see, The issue could be because of having the controller-manager and scheduler on different nodes than the etcd-0:

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.7", GitCommit:"bfb38f707bc4a8edfcd73472ec3d96b500b8b781", GitTreeState:"clean", BuildDate:"2020-08-12T20:19:28Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}

**Comment by sab24** [comment]
So this feature is deprecated. Why is there no text added to the command's output telling that kubectl get componentstatus is deprecated?

**Comment by CzarMich** [comment]
Hopefully in the next update, something can come up.

**Comment by sumitKash** [comment]
Not sure if it is "Kubectl get cs" command issue or something is actually wrong in setup. 

I am using kubernetes version v1.18.8
```
kubectl get cs
NAME                 STATUS      MESSAGE                                                                                     ERROR
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused
etcd-0               Healthy     {"health":"true"}
```
Or there's a change in kubernetes version 1.18.x? Port 10252/10251 are not in listning state if i check it using netstat command.

```
sudo netstat -tupln | grep 102
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      15067/kubelet
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      15242/kube-proxy
tcp        0      0 127.0.0.1:10257         0.0.0.0:*               LISTEN      14877/kube-controll
tcp        0      0 127.0.0.1:10259         0.0.0.0:*               LISTEN      14841/kube-schedule
tcp6       0      0 :::10250                :::*                    LISTEN      15067/kubelet
tcp6       0      0 :::10256                :::*                    LISTEN      15242/kube-proxy
```
The same thing works on v1.17.4

**Comment by mrSingh007** [comment]
why this issue is closed? what is the fix? facing same problem:
```
scheduler            Unhealthy   Get "http://127.0.0.1:10251/healthz": dial tcp 127.0.0.1:10251: connect: connection refused   
controller-manager   Unhealthy   Get "http://127.0.0.1:10252/healthz": dial tcp 127.0.0.1:10252: connect: connection refused 
```

**Comment by pauloleary57** [comment]
Same here. Using 1.18.8:
[issue.txt](https://github.com/Azure/AKS/files/5365802/issue.txt)

**Comment by pauloleary57** [comment]
Same here. Using 1.18.8:
`$ kubectl get componentstatuses
NAME                 STATUS      MESSAGE                                                                                     ERROR
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused   
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused   
etcd-0               Healthy     {"health": "true"}

**Comment by pauloleary57** [comment]
Same here. Using 1.18.8:
`$ kubectl get componentstatuses`
`NAME                         STATUS       MESSAGE                                                                                                                      ERROR`
`scheduler                   Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused`   
`controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused`   
`etcd-0                        Healthy     {"health": "true"}`

**Comment by pauloleary57** [comment]
Same here. Using 1.18.8.

**Comment by palma21** [comment]
Please see the comment from @mitchellmaler  https://github.com/Azure/AKS/issues/173#issuecomment-664430043
