### ISSUE TITLE
API for Deprecated versions

### ISSUE THREAD

**Issue by ncole** [Azure/AKS#1733]
### Feature Request

Use case (version numbers are aribitrary, but recent):
* Deploy a Kubernetes cluster using 1.15.10
* After some time, 1.15.10 is deprecated because of a bug that is fixed in favor of 1.15.11.
* Clusters can only be made with versions 1.15.11, 1.15.12.

I would like to understand when my deployed 1.15.10 cluster is deprecated.  Either via `ManagedClusterProperties` or using the `UpgradeProfile` of a cluster.

Thanks,
Nate

**Comment by jayush** [comment]
In addition, it would be good to have a queryable way to find list of deprecated K8s versions so that products that are built on top of AKS can trigger auto-upgrades or notify customers of their product to upgrade. For instance when K8s 1.15 is deprecated we would like to do roll out upgrade to 1.16 before K8s 1.15 support is removed.

**Comment by palma21** [comment]
Hi, Thanks for the feedback!

Azure Advisor today already provides you with a recommendation that is possible to alert on as soon as a k8s version is deprecated (you can also automate the alert into automation hooks if you desire).

![image](https://user-images.githubusercontent.com/7065724/87906424-75584880-ca17-11ea-892b-557477ab27fb.png)


We're currently adding the new version signal into Azure Event Grid for easy even-driven consumption.

**Comment by ohorvath** [comment]
To be honest, notification after deprecation is way too late. We still have to provide the patch version in the arm template which can be removed from the api randomly by Microsoft. This behaviour caused production issues for us already. Of course we can query the api for the latest version available but that's also risky. We need time to test against the latest patch versions even it should be ok. Currently there is no way to use older patch versions for 1.16 and 1.17, so if the newest patch version brake something there is no fallback.

**Comment by palma21** [comment]
Understood that's a bit of a different request than the above comments though.

It's a tricky problem because patch versions drop at any time "unannounced". So we try to keep 2 patch versions so that if you're on the latest one at all times you still don't break because that one would just slide to the last patch supported.

Would having an alias that allows you to deploy 1.16 or 1.17 without specifying the patch (defaulting to latest) solve your use case?

**Comment by ohorvath** [comment]
Thanks for your answer. Yes, if we can deploy the latest patch from ARM specifying only the minor version can solve our problems.

**Comment by palma21** [comment]
Ok I created https://github.com/Azure/AKS/issues/1737

To track that.

**Comment by tomkerkhove** [comment]
> Hi, Thanks for the feedback!
> 
> 
> 
> Azure Advisor today already provides you with a recommendation that is possible to alert on as soon as a k8s version is deprecated (you can also automate the alert into automation hooks if you desire).
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/7065724/87906424-75584880-ca17-11ea-892b-557477ab27fb.png)
> 
> 
> 
> 
> 
> We're currently adding the new version signal into Azure Event Grid for easy even-driven consumption. 

If you need feedback on those events, let me know! /cc @jluk

**Comment by ncole** [comment]
To my knowledge, the Advisor doesn't help with tooling that doesn't use the portal.  Ideally the API will provide information that the current cluster's version is deprecated and action needs to be taken.

**Comment by palma21** [comment]
Advisor provides a rest API to get recommendations programmatically as well, but what I meant above is that you can create an alert, on my screenshot I think that's cut, which you can can hook any automation runbook.

For more custom event based driven that's the case for the event grid integration we're working on.


![image](https://user-images.githubusercontent.com/7065724/88102303-2f54cf00-cb54-11ea-8121-3af43bf60a64.png)
![image](https://user-images.githubusercontent.com/7065724/88102363-472c5300-cb54-11ea-9006-30dae57a67a0.png)
![image](https://user-images.githubusercontent.com/7065724/88102417-62975e00-cb54-11ea-9cea-4b981000bf8d.png)

**Comment by tomkerkhove** [comment]
> To my knowledge, the Advisor doesn't help with tooling that doesn't use the portal. Ideally the API will provide information that the current cluster's version is deprecated and action needs to be taken.

Once a cluster version is deprecated (and you are notified by approach above) you can:
1. Use [Pluto](https://github.com/FairwindsOps/pluto) to see if your apps are impacted
2. Add a new node pool with new Kubernetes version
3. Move workloads
4. Remove old node pool

**Comment by ncole** [comment]
Thanks @palma21, I'll dig a bit deeper there.
