### ISSUE TITLE
Support create AKS cluster by specifying only kubernetes minor version

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#1737]
Eg.

`az aks create -n AKS -g AKS -k 1.16`

Allowing to omit the patch version, default to latest patch.

**Comment by jotavar** [comment]
@palma21 can you please confirm this will also be possible via ARM deployment?

**Comment by micya** [comment]
> @palma21 can you please confirm this will also be possible via ARM deployment?

bump, would also like to know on above

**Comment by ohorvath** [comment]
This feature is still not available via ARM. :(

**Comment by konopkap** [comment]
> This feature is still not available via ARM. :(

It's available in opt-in preview according to the [docs](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#kubernetes-version-alias-preview)

**Comment by illrill** [comment]
> This feature is still not available via ARM. :(

I can confirm that `Microsoft.ContainerService/managedClusters` API version `2022-07-01` supports this.
