### ISSUE TITLE
Support for multi-region clusters

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/AKS#1738]
Support for multi-region clusters so that we can use one cluster with node pools across regions.

This would allow us to run workloads in a high available manner given workloads will be moved to alternative node pool if the current one is unavailable due to service outage.

This also provides a single-cluster experience for global platform scale.

In the case of HA, having a "secondary" / "fallback" nodepool which is configured but still unused (and unbilled or at least less) until primary falls away would be a bonus.

An option for data replication can be Azure Cosmos DB with etcd API.

**Comment by 4c74356b41** [comment]
why would it be unbillable? well, unless vms are stopped.

**Comment by tomkerkhove** [comment]
Yes, because they are unallocated

**Comment by 4c74356b41** [comment]
you can do this now with AFD or TM, you cant move disks between regions, so I'm not sure what's the exact benefit you are looking for. I dont think there is any issue with configuring 2 clusters in the same way, given gitops\helm\etc.

**Comment by tomkerkhove** [comment]
I don't want 2 clusters, I just want one cluster with node pools across regions so that my workloads are automatically balanced in case of an incident.

**Comment by iamalexmang** [comment]
I totally support this. As a side note and with no intent comparing to clustering and orchestration technologies, this is a capability supported by Service Fabric clusters and which adds a lot of value to scenarios that can leverage region outages without the need of provisioning two or more clusters and handling application updates in an orchestrated manner - that's what the orchestrator should handle better than my custom scripts.

**Comment by palma21** [comment]
I think @4c74356b41's point is still valid for non HTTP workloads right? 

The reason you don't want 2 clusters is for management simplification? Can you double click a bit on why you wouldn't want 2 clusters?

A different perspective I could provide is that with 2 clusters you get 2 APIs and effectively increase the availability of your control plane by virtue of having 2 independent control planes which could be paid or not.

For handling the application updates across clusters that's definitely something we're looking at but the current recommended approaches are similar to the suggestions above using gitops or similar.

**Comment by tomkerkhove** [comment]
Here is some more input for our needs:
- Our application runs across different geo's but only want to manage one cluster
- Only 5% of our workloads which are exposing services over UDP (so no Azure Traffic Manager nor Azure Front Door)
- If we were to have node pools across regions we can use taints to schedule them in specific geo; if we care at all
- Our single cluster comes with HA out-of-the-box

And I'm happy to pay for the additional overhead on the control plane if that's a worry but I'd rather focus on our workloads than managing clusters in all our regions.

**Comment by IainColledge** [comment]
This would be a fantastic capability to have autoheal and autoscale across two close regions.

I'm currently investigating how to make our DR more cloud native and as we have just put AKS in operational usage then this was the first capability I looked for to have our DR "just work" with no or minimal intervention.

**Comment by tomkerkhove** [comment]
Any thoughts on this @jluk @seanmck?

**Comment by tomkerkhove** [comment]
Bumping, any thoughts @seanmck @palma21 if this is coming?

**Comment by asubmani** [comment]
> you can do this now with AFD or TM, you cant move disks between regions, so I'm not sure what's the exact benefit you are looking for. I dont think there is any issue with configuring 2 clusters in the same way, given gitops\helm\etc.

Having 2 separate clusters increases complexity. If npdepools support this, then we can associate diff NP with Proximity placement groups and control pod workloads by simple concepts like Taints or NodeSelectors.  

The only thing I worry with nodepools across regions is that Node to Master latency would be high and items like Service discovery may not run reliably.

**Comment by asubmani** [comment]
Also AFD and TM are exclusively used for public facing AKS workloads. In my experience, majority of customers use 90% pods in local VNET's and regulate access from business partners to a few services.

**Comment by erir910** [comment]
Is there any cloud provider that provides multi-region clusters? Even GKE does not so far I guess.

**Comment by mslot** [comment]
> Is there any cloud provider that provides multi-region clusters? Even GKE does not so far I guess.

I actually don't know. I have looked into Rancher to control deployment for multiple clusters, but it is expensive.

**Comment by tomkerkhove** [comment]
> Is there any cloud provider that provides multi-region clusters? Even GKE does not so far I guess.

Question is, does that matter? 😉

**Comment by thcp** [comment]
The question here is , wouldn't this be a single point of failure? What if:

- AKS API became non responsive for your cluster ? Loss of access on your cluster with nodepools deployed across X regions?
- What if something goes wrong during an update? wouldn't this compromise the whole cluster?
- What if you get hacked or  any coworker performs an incorrect action that could damage the cluster availability?

In my opinion, while I do like the option of having "one cluster to rule then all" I'm not a fan of having a single point of failure and from a disaster recovery/ Redundancy perspective, having several clusters behind a global load balancer would be more desirable.

**Comment by tomkerkhove** [comment]
That's a matter of choice, I guess, since some people prefer it and others don't and that's fine. Both scenarios have pro's & con's.

> - AKS API became non responsive for your cluster ? Loss of access on your cluster with nodepools deployed across X regions?

That's up to AKS to manage the HA/DR for the control plane, but when using Azure Cosmos DB to manage etcd that should be "fairly easy".

> - What if something goes wrong during an update? wouldn't this compromise the whole cluster?
> - What if you get hacked or any coworker performs an incorrect action that could damage the cluster availability?

Yes, but when using a single cluster you'd be aware of that and know that's a risk you're taking. On the flip side, if you have a lot of smaller clusters you won't have this, but rather have additional overhead instead, which might be less beneficial than a single cluster

**Comment by thcp** [comment]
> Yes, but when using a single cluster you'd be aware of that and know that's a risk you're taking. On the flip side, if you have a lot of smaller clusters you won't have this, but rather have additional overhead instead, which might be less beneficial than a single cluster

Yea, totally agree with you on that point. From a management perspective having a single cluster would be beneficial. In any case, I ( like many of us) would love to have this feature implemented.

**Comment by erir910** [comment]
> > Is there any cloud provider that provides multi-region clusters? Even GKE does not so far I guess.
> 
> Question is, does that matter?

I guess there might be technical reason that no vendor provides it, my primary guess is because CNI plugins usually work on the VPC private IP of the nodes and the traffic between the nodes is not usually encrypted since most CNI plugins assume the entire cluster is on the same private network, also load balancers can't see pods in other VPCs other than the one they were initially created in. I don't see any other technical reason honestly but the CNI reason is enough to make it 10000x harder to support multi-region using the same control plane.

**Comment by mdg215199** [comment]
Couldnt you use m azire frontdoor and also global vnet and global ip (or just ip in multiple regions), which would make a determination if the closest route to aks.  From there, add the region name as part of the cni fqdn in order to attempt to find service pod that is within its region, and if not, find one of the next ones (we know jf two regions are paired, etc in order to find a quick determination for one of the pods... that even if in some scenarios calls a pod that might not be the fastest endpoint in some situations, it would likely be fairly close).  

Anyways, I've not tried global vnet w/ global front door, and it seemed like it was possible, though, likely caveats that could prevent this from working?

**Comment by tomkerkhove** [comment]
Everything is possible, but in that scenario your cluster and app management workload multiplies with the amount of regions that you have.

**Comment by asubmani** [comment]
The main reason(s) why one needs multi-region /multiple clusters are:
Cluster upgrades can go wrong due to various reasons.
AKS requires more frequent upgrades (as upstream K8s evolve faster) and therefore increases the chances of operator/CI/CD induced errors etc. Operating Multiple clusters has been advocated in many books and it makes sense to have them in diff regions if you are going to operate multiple clusters anyway.

**Comment by asubmani** [comment]
heard something on Fleet to solve this. Would love to get more info on this

**Comment by wangyira** [comment]
@shashank can you take a look at this?

**Comment by kbocock-krg** [comment]
If no other cloud provider has this capability and Azure is the first... 💯 + 🥇

**Comment by asubmani** [comment]
> If no other cloud provider has this capability and Azure is the first... 💯 + 🥇
https://www.cncf.io/blog/2020/10/19/how-to-set-up-multi-cluster-load-balancing-with-gke/

**Comment by shashankbarsin** [comment]
We have introduced Azure Kubernetes Fleet Manager recently - https://learn.microsoft.com/en-us/azure/kubernetes-fleet/. This allows for mapping multiple AKS clusters as member clusters to the fleet. Currently we have workload placement and L4 multi-cluster load balancing in preview. We are also working on more capabilities - L7 multi-cluster load balancing (regional and global), backup and restore, multi-cluster mesh and so on that will help spread applications across multiple AKS clusters in multiple regions. So our plan is to leverage the above for global resiliency requirements and that AKS would remain a regional resource.
