### ISSUE TITLE
Please help improve error message accuracy for custom node resource group

### ISSUE THREAD

**Issue by HollyQM** [Azure/AKS#1739]
feedback from customer when customing node resource group with label starts with "_" he faced cluster deployment error and node not showing not ready

the error we saw from kubelet log:
Jul 17 00:04:55 aks-nodepool1-36196007-vmss000000 kubelet[3582]: E0717 00:04:55.892915    3582 kubelet_node_status.go:92] Unable to register node "aks-nodepool1-36196007-vmss000000" with API server: Node "aks-nodepool1-36196007-vmss000000" is invalid: metadata.labels: Invalid value: "_codafication-au-east-staging-2": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

the error customer actually saw from cloud shell:
Deployment failed. Correlation ID: 878d39f8-d4f7-4fba-aa1c-cfcbb35c60a3. All nodes did not reach Ready state. Expected: 1, Actual: 0

customer would like to see the error in kubelet log be accurately reflected on cloud shell portal as well to pinpoint the issue more efficiently.
Please help see if we can improve the accuracy of the error messages reporting from az aks create, thank you!

**Comment by TomGeske** [comment]
@jluk for visibility on this feedback.

**Comment by jluk** [comment]
@hollyqm you mention the node resource group in the first sentence, but the error looks like an invalid label was attempted to be applied to a node and has nothing to do with the node resource group. 

Was this node label applied via the AKS node pool API or was the node label applied via kubectl?

AKS validates API requests to set a node pool, but if the incorrect label was applied via kubectl that isn't a check AKS can validate against at request time.
