### ISSUE TITLE
kubectl - unathorized - cannot connect to server

### ISSUE THREAD

**Issue by gardlt** [Azure/AKS#174]
Just deployed a AKS , cluster in the EAST US region, and am trying to kubectl to get cluster information. But i am getting `Unable to connect to the server: x509: certificate signed by unknown authority` 

i ran the `az aks get-credentials` command again to see if it was a an issue but am getting the same result.

**Comment by jmalobicky** [comment]
I am getting this error on new clusters created in East US. I have existing clusters that seem ok.

**Comment by SRAM85** [comment]
I ran into the same issue after a while. My cluster is deployed in CENTRAL US . 

Unable to connect to the server: x509: certificate signed by unknown authority

az aks get-credentials did not help either.

**Comment by pwsuperstar** [comment]
Got the same problem. Just trying to follow the walkthrough here https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough

I successfully deploy the cluster but cant do anything after that. Always getting the "Unable to connect to the server: x509: certificate signed by unknown authority"

**Comment by rapemer** [comment]
Same error:

Unable to connect to the server: x509: certificate has expired or is not yet valid

**Comment by suonto** [comment]
Encountered this issue today. I debugged the certificates with openssl and concluded that ca was simply invalid. Recreated the cluster and after that `az aks get-credentials` returned valid credentials (and certs). Please fix this.

**Comment by seanknox** [comment]
Believe this has been fixed; please reopen if still an issue.

**Comment by suonto** [comment]
@seanknox can you please share the root cause of this if it has been fixed?

**Comment by asc-adean** [comment]
This is happening again, East US.  Going to try another region.

**Comment by calmbryan** [comment]
East US same issue here: x509: certificate signed by unknown authority
