### ISSUE TITLE
AKS Node Pool Upgrade Strategy

### ISSUE THREAD

**Issue by stmaute** [Azure/AKS#1741]
General question regarding the upgrade strategy of node pools. In the docs I found following description how node pools are upgraded to a new version. This upgrade process makes total sense to me. 

Upgrade a cluster
To minimize disruption to running applications, AKS nodes are carefully cordoned and drained. In this process, the following steps are performed:

1. The Kubernetes scheduler prevents additional pods being scheduled on a node that is to be upgraded.
2. Running pods on the node are scheduled on other nodes in the cluster.
3. A node is created that runs the latest Kubernetes components.
4. When the new node is ready and joined to the cluster, the Kubernetes scheduler begins to run pods on it.
5. The old node is deleted, and the next node in the cluster begins the cordon and drain process.

But in reality the upgrade process looks like this:
1. The Kubernetes scheduler prevents additional pods being scheduled on a node that is to be upgraded. (This is fine)
2. Running pods on the node are scheduled on other nodes in the cluster. (Why don't wait for the new node to be available?)
3. A node is created that runs the latest Kubernetes components. (This node gets deleted after the upgrade process)
4. Even if the node is in state NotReady the upgrade process of the VMs is started.
5. The new spawned node  in step 2 gets cordoned and pods get drained. This causes additional movement of pods which is totally unnecessary.  

Screenshots of the upgrade process:
1. Initail state
![1](https://user-images.githubusercontent.com/17831060/88043416-b05c9800-cb4d-11ea-8c01-f337000af312.PNG)
2. Upgrade process started although the new node is NotReady
![2](https://user-images.githubusercontent.com/17831060/88043520-d124ed80-cb4d-11ea-8d62-fe2f0348cb3f.PNG)
3. During the upgrade process
![3](https://user-images.githubusercontent.com/17831060/88043525-d2eeb100-cb4d-11ea-813e-32307fe3c05d.PNG)
4. Last upgraded node is NotReady and old nodes are still there.
![4](https://user-images.githubusercontent.com/17831060/88043528-d3874780-cb4d-11ea-8885-7c1a993e7621.PNG)

Any idea why there is such a difference between the docs and the real upgrade process?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.8
- Size of cluster (how many worker nodes are in the cluster?): 3 worker nodes

**Comment by yangl900** [comment]
hi @stmaute , your observation is correct. But there is some details I'd like to provide.

Yes, the process did not wait for the new buffer node to be ready. However, the upgrader will drain the to-be-upgraded node, and move the pods to other nodes in the cluster. If any of the pods has a label selector, it will wait for the new buffer node to be ready (which will have exact same label and taints as the to-be-upgraded node). At the drain state we will wait, and as a best practice if you define pod disruption budget, it will wait for the new pods to be ready. If the pods does not have node preference, it can be scheduled to other nodes in the cluster, as long as it has capacity.

After the upgrade process, the buffer node will also be drained and the upgrader will wait for drain complete before it delete the node. Based on this, there should be no disruption to the running application as the document described.

Hope this explains the upgrade process a bit more.

cc: @paulgmiller

**Comment by stmaute** [comment]
hi @yangl900, thank you for the detailed explanation.
You mentioned that when a Pod uses a label selector it will wait or the buffer node to be ready. In our kubernetes deployment files we use a nodeSelector to schedule pods onto specific nodes. From my understanding the drain process should than wait until the buffer node is ready. Or do I miss something here?

**Comment by palma21** [comment]
The issue here is likely that you have more than one node with the label you select, so it's really up to kubernetes scheduler to select which node to go to, both before or after the node is ready. If only this node has that label, kubernetes has no other choice but to wait for it to be ready.

The reason it doesn't artificially wait for the specific buffer node to be ready is to expedite things, unbalancing shouldn't really be a problem as the whole set of nodes should undergo this cordon/drain/reschedule leading towards balance in the whole cluster, always relying on the node selection and resource/HA constraints.

Is the fact that it doesn't wait for node before the scheduler starts to look for candidates a problem for your workloads.
