### ISSUE TITLE
Provide information on deprecated features in new Kubernetes versions based on current workload

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/AKS#1744]
Kubernetes versions are being deprecated every now and then and it would be nice if Azure can help customers migrating off of it.

As of today, Azure Advisors already provides a heads-up on clusters that are deprecated, but it would be nice if it could help customers migrate to newer versions by showing them what features are deprecated based on current running workload.

That way, we have a better understanding of what the impact is and can more easily migrate. 

Until now, you have to use tools like [Pluto](https://github.com/FairwindsOps/pluto) but would be nice to have some sort of built-in guidance around that, based on our workload.

**Comment by palma21** [comment]
Thanks for the feedback. Both AKS Diagnostics and Azure Advisor already provide deprecated API info for a particular cluster. It just doesn't show which specific API it is today. 

Is the ask around the former or the latter?

**Comment by tomkerkhove** [comment]
This is definately helpful:
![image](https://user-images.githubusercontent.com/4345663/88160208-a2bb1700-cc0e-11ea-8bda-3f3718392fbc.png)

But I'd like to go to my cluster > Upgrade and have an overview of the impact if I were to upgrade (mockup):
![image](https://user-images.githubusercontent.com/4345663/88160936-a307e200-cc0f-11ea-9c2b-caf942e7f7e3.png)

**Comment by tomkerkhove** [comment]
Keep-Alive

**Comment by jenetlan** [comment]
Thanks for the feature request! I definitely agree that information would be useful to include. We're looking at some possible updates to the upgrade experience so we'll take this into account. Unfortunately I don't have any dates or concrete plans I can share now, but I'll share an update later on when I have one. Thanks!

**Comment by tomkerkhove** [comment]
Awesome, thank you! I've used Pluto in the past which was great. 

Ideally this shows up in Azure Advisor + Azure Event Grid event.

**Comment by raghulmsft** [comment]
Hi, 

The AKS Portal team has implemented these suggestions during cluster upgrade time in this blade. Check it out and share any feedback you might have. We will update the docs to reflect these changes as well. 
![image](https://user-images.githubusercontent.com/91854828/216707962-50f52385-8123-42e5-8cbc-4b95db009ced.png)

**Comment by dpk09** [comment]
I don't see this feature in portal, that indicates details of deprecated API's

![image](https://user-images.githubusercontent.com/92372155/221576474-470efafd-6774-4154-94c8-a05ffbfc4858.png)
