### ISSUE TITLE
Cannot Create Nodepool with nodelabel on AKS Kubernetes version 1.16.9 & 1.16.10

### ISSUE THREAD

**Issue by nebed** [Azure/AKS#1746]
**What happened**:
When i try to create a VMSS nodepool through Azure CLI and Terraform with following label `node-role.kubernetes.io/apps=telemetry` on kubernetes version 1.16.9 & 1.16.10 Nodepool gets created but remains in **Failed** state and does not get added in k8s.

The following error is returned on CLI in debug mode
```
msrest.http_logger : Response content:
msrest.http_logger : {
  "name": "de62220d-e97e-1641-b864-6aa693230c39",
  "status": "Failed",
  "startTime": "2020-07-17T12:39:54.7549732Z",
  "endTime": "2020-07-17T13:24:23.366457Z",
  "error": {
   "code": "NodesNotReady",
   "message": "Not all nodes reached Ready state. Expected: 2, Actual: 0"
  }
 }
msrest.exceptions : Not all nodes reached Ready state. Expected: 2, Actual: 0
cli.azure.cli.core.util : Deployment failed. Correlation ID: 8a55df34-49ea-4892-a6ee-467b6e4531ce. Not all nodes reached Ready state. Expected: 2, Actual: 0
Deployment failed. Correlation ID: 8a55df34-49ea-4892-a6ee-467b6e4531ce. Not all nodes reached Ready state. Expected: 2, Actual: 0
``` 
The nodepool gets created successfully without labels.

**What you expected to happen**:
Nodepool should be created successfuly and in Ready State and labels should be applied to nodes

**How to reproduce it (as minimally and precisely as possible)**:
Try to create nodepool in AKS cluster with k8s version 1.16.9/1.16.10 using the following command
`az aks nodepool add --cluster-name _cluster_name_ --name _nodepool_name_ --resource-group _rg_name_ --kubernetes-version 1.16.10 --node-vm-size Standard_D3_v2 --node-count 1 --labels node-role.kubernetes.io/apps=telemetry --zones 1 2 --node-taints dedicated=apps:NoSchedule`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version - 1.16.10:
- Size of cluster - 3 Worker Nodes
- General description of workloads in the cluster (e.g. HTTP microservices)
- Others:

**Comment by yunjchoi** [comment]
Hello Uchenna,

In 1.16, Kubernetes has blocked the ability to set `kubernetes.io-` or `k8s.io-`prefixed labels via --node-labels, other than the specifically allowed labels/prefixes documented [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md#proposal). 

AKS is working on blocking the creation of such node pools with disallowed labels, and the change will be released in early Aug. Please try creating the nodepool without the disallowed labels.

**Comment by nebed** [comment]
Hi @yunjchoi Thanks a lot for the information

**Comment by yunjchoi** [comment]
Let us know if you have more questions regarding this issue. We will update this thread and close it once the fix goes live.

**Comment by wereeder** [comment]
I am getting the same error, and not passing any labels to the command to add the nodepool.

Here is the command:
`az aks nodepool add --cluster-name _cluster_name_  --name nodepool --resource-group _rg_name_  --subscription _subscription_id_ --node-count 1 --mode User --node-vm-size Standard_D2_v2 --vnet-subnet-id _subnet_id_
`

I also get the same problem when I create the nodepool through the portal.

The cluster is running kubernetes version 1.16.10

**Comment by palma21** [comment]
@wereeder could you provide the aks create command for that cluster paste the error that you're getting exactly? 

That one seems to be different from this issue where unhallowed labels were being used. So it might warrant it's own issue

**Comment by wereeder** [comment]
Hi @palma21 I have attached the Terraform scripts I used to create the cluster
[terraform.zip](https://github.com/Azure/AKS/files/4971873/terraform.zip)

Here is the exact error I get when running az aks nodepool add:
Deployment failed. Correlation ID: c2fe1f3c-9e9c-41b3-b22a-509a61026a28. Not all nodes reached Ready state. Expected: 1, Actual: 0

**Comment by palma21** [comment]
Yes so your case is definitely different. Could you open a support ticket so we can take a look?

Feel free to post the number here for us to follow up. We can then bring the discussion there so we don't mix with this one.

CC @TomGeske

**Comment by ohorvath** [comment]
Unfortunately not just new AKS cluster creation is affected. If you have AKS 1.15 nodepool labeled with "node-role.kubernetes.io/", the upgrade process will fail. It will terminate all your pods, set your nodes as notready but never can bring in new nodes to replace the old ones. As nodepool labels cannot be changed after cluster creation I don't see any solution to this. What should we do with our AKS 1.15 clusters running in production?

**Comment by palma21** [comment]
As Yun mentioned, k8s does not allow to use such labels on newer versions. Kubelet will reject them and fail. Please create new nodepools with different labels and delete these ones, then you can upgrade to 1.16 Or alternatively upgrade just the control plane and create the new node pools in the new version directly (and with the new labels).
 Also feel free to open a support ticket if you want us to help you out with your specific cluster.

**Comment by palma21** [comment]
@yunjchoi could we have a detector for these labels as well?

**Comment by yunjchoi** [comment]
We have delivered a validation for disallowed labels in 1.16 along with proper error message, hence, closing this issue.
