### ISSUE TITLE
AKS to respect Node Pool Tags Key Name when it is a mixed case

### ISSUE THREAD

**Issue by mohmdnofal** [Azure/AKS#1747]
Hello,

AKS isn't respecting the "key name" when it's in mixed case for the node pool tags i.e. "InternetAccess", the name will always be converted to lowercase. The tag "value" case is respected though, could this be fixed, please? 

Use Case: Firewall only allows VM access to the internet using the tags, the current tags that the firewall use is mixed case i.e. InternetAccess=Proxy SecurityZone=Low

Repro;

$ az aks create \
-g $RG \
-n $AKS_CLUSTER_NAME \
-l $LOCATION \
--node-count 1 \
--tags TEST1=VALUE1 TEST2=VALUE2 \
--nodepool-name testtags \
--nodepool-tags **Test1=Value1 TEST2=VALUE2 test3=value3**

{
  "aadProfile": null,
 ....
 },
  "agentPoolProfiles": [
    {
    ****"tags": {
        "test1": "Value1",**
        "test2": "VALUE2",
        "test3": "value3"
      },****
     ...
    }

**Comment by jluk** [comment]
Acknowledging we are looking into this

**Comment by jluk** [comment]
We are working on a bug fix for this.

**Comment by jluk** [comment]
This bug fix has been completed, ETA for global availability is 8/14.
