### ISSUE TITLE
Ability to shorten the InstanceName value in LogAnalytics Workspace query

### ISSUE THREAD

**Issue by shivabommakanti03** [Azure/AKS#1749]
When I try to remove preceding of the InstanceName in LogAnalytics it does not let me do it. And, in kusto query if I select InstanceName in summarize section I can only exclude anything that is related to InstanceName but not _ResourceID which is common in every InstanceName.

Please find screenshots below
![Screen Shot 2020-07-23 at 2 57 41 PM](https://user-images.githubusercontent.com/53050834/88333033-22231600-ccf5-11ea-97f2-bfe9b4f67a8e.png)

**Comment by vishiy** [comment]
@shivabommakanti03 - Based on your screenshot, you are trying to filter by _ResourceId *after* summarizing by  avg_value, time &  instance name. At that point your data set has only exactly those 3 columns and its values and not _ResourceId. You need to move your filtering before summarize.

**Comment by shivabommakanti03** [comment]
@vishiy Thanks for suggestion and I used my filtering before summarize but I still see my result giving full instance name which I am not expecting to see.

`Perf
| where ObjectName == "K8SContainer" and CounterName  == "cpuUsageNanoCores" and _ResourceId !contains "/subscriptions/xxxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.ContainerService/managedClusters/xxxxxxxx/"
| summarize AvgCPUUsageNanoCores = avg(CounterValue) by bin(TimeGenerated, 30m), InstanceName`

**Comment by vishiy** [comment]
How are you accessing the workspace query ux ? If you come from an AKS cluster, you are querying for that specific cluster resource. If you go to workspace directly in the UX and query you can query for *any* resource sending data to that workspace.

**Comment by shivabommakanti03** [comment]
If you go to workspace directly in the UX and query you can query for any resource sending data to that workspace.

^^ this is my issue.

**Comment by vishiy** [comment]
did that resolve your issue ?
