### ISSUE TITLE
Unable to change default volume class

### ISSUE THREAD

**Issue by sukrit007** [Azure/AKS#175]
I am changing default storage class to: 'managed-premium'.  However,  after some time,  it resets default storage class to 'standard'.

Here are the commands I am using to change default class:

```bash
kubectl patch storageclass default -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
kubectl patch storageclass default -p '{"metadata": {"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"false"}}}'
kubectl patch storageclass managed-premium -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
kubectl patch storageclass managed-premium -p '{"metadata": {"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"}}}'
```

**Comment by slack** [comment]
Right now we are enforcing the storageClass configuration through addon manager. Suggested workaround is to specify the desired `managed-premium` class in your volume definitions.

Is this something that you would like to specify at the time of cluster provision?

**Comment by sukrit007** [comment]
@slack  Thanks for the clarifying that. Yes, we are using the workaround, for now,  however, specifying default at cluster creation time would be ideal as we want to abstract that information in our deployments.

**Comment by seanknox** [comment]
Migrated to our feature feedback forum: https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/35055538-change-default-volume-class
