### ISSUE TITLE
coredns-custom ConfigMap Hosts Plugin with Private IP Sporadically Doesn't Work

### ISSUE THREAD

**Issue by k8s42** [Azure/AKS#1750]
**What happened**:
Followed this Microsoft article to create hosts file entry (using `coredns-custom` ConfigMap file) to resolve standard file storage account endpoints to the respective private IPs (using private endpoints):

https://docs.microsoft.com/en-us/azure/aks/coredns-custom#hosts-plugin

```
hosts {
  10.x.x.1 storageaccont1.file.core.windows.net
  10.x.x.2 storageaccont2.file.core.windows.net
  10.x.x.3 storageaccount3.file.core.windows.net
  fallthrough
}
```
**What you expected to happen**:
Volumes should've mounted to the containers 100% of the time

**How to reproduce it (as minimally and precisely as possible)**:
1. Modify the `coredns-custom` ConfigMap file as follows:
```
hosts {
  10.x.x.1 storageaccont1.file.core.windows.net
  10.x.x.2 storageaccont2.file.core.windows.net
  10.x.x.3 storageaccount3.file.core.windows.net
  fallthrough
}
```
2. Delete the **coredns** pods for the changes to take effect.
3. Run **curl** or **ping** from inside the container to the storage endpoint to ensure it resolves to internal IP.
4. Deploy a container with a PVC created using the PV created from the Azure File storage account. 

**Anything else we need to know?**:s
1. Both AKS cluster and the private endpoints for storage reside under the same VNET i.e. no firewall blocks internally on TCP port 445.
2. The empty share gets created successfully, but container stays stuck in the "Container Creating" status with CIFS mount related errors. 
3. This is a sporadic issue. There are more failures than successes. 
4. With hosts file entries set in  `coredns-custom` ConfigMap file and outbound rule to internet over TCP 445 **allowed**, it works 100% of the time. This tells me that traffic is somehow still going over the public IP during the process. 
5. With hosts file entries set in  `coredns-custom` ConfigMap file and outbound rule to internet over TCP 445 **disallowed**, issue occurs sporadically. This further proves my point in bullet point number 4 above.
6. With hosts file entry set at the AKS node level, issue is not reproducible at all. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.11
- Size of cluster (how many worker nodes are in the cluster?) 3:
- Storage Class Provisioner: azure-file
-CoreDNS Version: 1.6.6

**Comment by TomGeske** [comment]
+@palma21  to help.

**Comment by palma21** [comment]
@andyzhangx could this be related to the needed changes upstream for storage datapath?

**Comment by k8s42** [comment]
@palma21 @andyzhangx, are there any additional CoreDNS (or other) configuration changes needed to get this working?

**Comment by andyzhangx** [comment]
Private endpoint support on azure file driver is only supported in Azure File CSI driver: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/300
Currently it’s only supported on master branch, we are going to publish a new release soon.

For in-tree azure file driver, the mount operation happens on kubelet on agent node, modify HOSTS entry could workaround this issue.
