### ISSUE TITLE
Does AKS support mounting AZ Disks outside of subscription from cluster?

### ISSUE THREAD

**Issue by tigerkeeper5** [Azure/AKS#1760]
**What happened**:
I am trying to mount an Azure Managed Disk in a different subscription from my AKS cluster. I am attaching the disk statically as shown [here](https://docs.microsoft.com/en-us/azure/aks/azure-disk-volume). I can't seem to find any documentation on it, so I am wondering if it is even supported. The following error is received on my pod: 

AttachVolume.Attach failed for volume "volume" : compute.DisksClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group '<resource group>' could not be found."

**What you expected to happen**:
I expected to mount an Azure disk in a different subscription from my AKS cluster. 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.10
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by andyzhangx** [comment]
attach an azure disk from another subs is not even supported by azure disk feature, so it's also not supported by AKS
