### ISSUE TITLE
AKS based RBAC suddenly prompting multiple times to login through AD

### ISSUE THREAD

**Issue by devgibsonsp** [Azure/AKS#1761]
**What happened**:
Setting up a new cluster with RBAC enabled through kubernetes roles. This cluster was setup about a week before the previous instructions were marked legacy. I ran an upgrade on the cluster to get it in line with the following directions
https://docs.microsoft.com/en-us/azure/aks/azure-ad-rbac

This seemed to work fine. I can still define my roles through kubernetes and login through AD. However suddenly for absolutely no reason, and with absolutely no change to anything, I now have to re-login after every single kubectl command.

**What you expected to happen**:
I should not have to re-auth each time I run a kubectl command. It should only need to be done once.

**How to reproduce it (as minimally and precisely as possible)**:
1. Enable RBAC through the following instructions
https://docs.microsoft.com/en-us/azure/aks/azure-ad-rbac

2. Set up a cluster admin role in AKS

3. Run any kubectl command

4. prompt for login and auth.

5. Run another kubectl command.

6. Re-prompt for login

**Anything else we need to know?**:
I basically set this cluster up, verified it worked, then went off to do other tasks for a week. Came back, and now it doesn't work. I am the only one that has been touching this cluster. Nothing has changed between when it worked and when it stopped working.

**Environment**:
- 1.15.12
- 3 nodes
- HTTP microservices

**Comment by TomGeske** [comment]
@devgibsonsp: which kubectl version are you running?

possible related to: #1669

**Comment by devgibsonsp** [comment]
@TomGeske 
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"0158dee45a29c34f79226fb4738ecf0a70ead001", GitTreeState:"clean", BuildDate:"2020-06-23T03:54:52Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

**Comment by devgibsonsp** [comment]
Just to clarify. The the issue that you linked to is not the same behavior. I have no problem running kubectl commands after authenticating. But I MUST authenticate after every single command now.

**Comment by TomGeske** [comment]
Please share your support ticket no. once created.

**Comment by devgibsonsp** [comment]
@TomGeske  120080425002825

**Comment by TomGeske** [comment]
@devgibsonsp: I just looked at your cluster. It is a managed-AAD enabled and requires kubectl > 1.18. 
Please, update your kubectl version by running.

`az aks install-cli`

Let me know if that helps.

**Comment by devgibsonsp** [comment]
@TomGeske 
Is this a new requirement? I just got off a fresh sys ticket 2 weeks ago where I was instructed in order to fix an expired cert issue making the kubernetes dashboard inaccessible to not upgrade past 1.15 (which to me seemed like strange advice given that it was a stable version)

**Comment by devgibsonsp** [comment]
@TomGeske 

I am now using v1.18. This did not seem to resolve the issue
`
C:\Users\devgi>kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)

C:\Users\devgi>kubectl get pods -A
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code E8KTQRJJC to authenticate.
NAMESPACE     NAME                                                     READY   STATUS    RESTARTS   AGE
ingress       mongo-nginx-ingress-controller-574f94cbd6-mb4hq          1/1     Running   0          22d
ingress       mongo-nginx-ingress-default-backend-fdc69bb76-s7srb      1/1     Running   0          22d
ingress       nginx-ingress-controller-685f55ff7c-zdwfz                1/1     Running   0          22d
ingress       nginx-ingress-default-backend-674d599c48-4khts           1/1     Running   0          22d
ingress       private-nginx-ingress-controller-65ff7bcc5c-rk75h        1/1     Running   0          22d
ingress       private-nginx-ingress-default-backend-5f7bc574c7-vpvl4   1/1     Running   0          22d
kube-system   azure-cni-networkmonitor-dhxwt                           1/1     Running   0          22d
kube-system   azure-cni-networkmonitor-qqdjs                           1/1     Running   0          22d
kube-system   azure-cni-networkmonitor-r872m                           1/1     Running   0          22d
kube-system   azure-ip-masq-agent-67rvm                                1/1     Running   0          22d
kube-system   azure-ip-masq-agent-jmvwp                                1/1     Running   0          22d
kube-system   azure-ip-masq-agent-zwcp8                                1/1     Running   0          22d
kube-system   coredns-74dc64cb57-pgkrl                                 1/1     Running   0          46h
kube-system   coredns-74dc64cb57-psncp                                 1/1     Running   0          46h
kube-system   coredns-autoscaler-d5944b569-8z2d7                       1/1     Running   0          46h
kube-system   kube-proxy-2tlg4                                         1/1     Running   0          15d
kube-system   kube-proxy-4zlhd                                         1/1     Running   0          22d
kube-system   kube-proxy-vhmx6                                         1/1     Running   0          22d
kube-system   kubernetes-dashboard-98dcc4c7f-p6vc2                     1/1     Running   0          4d18h
kube-system   metrics-server-689c95f555-q6n96                          1/1     Running   0          4d18h
kube-system   omsagent-9dp7v                                           1/1     Running   2          4d18h
kube-system   omsagent-b75mv                                           1/1     Running   1          4d18h
kube-system   omsagent-kl9z9                                           1/1     Running   2          4d18h
kube-system   omsagent-rs-79698f896f-nqh6t                             1/1     Running   0          4d18h
kube-system   tiller-deploy-8557598fbc-fp9d6                           1/1     Running   0          22d
kube-system   tunnelfront-755b696fcc-6vwdh                             2/2     Running   0          4d18h
stateful      elasticsearch-master-0                                   2/2     Running   0          22d
stateful      elasticsearch-master-1                                   2/2     Running   0          22d
stateful      elasticsearch-master-2                                   2/2     Running   0          22d
stateful      mongodb-6f96879765-hj76r                                 1/1     Running   0          22d
stateful      redis-master-0                                           1/1     Running   0          22d
stateful      redis-slave-0                                            1/1     Running   734        22d
stateful      redis-slave-1                                            1/1     Running   735        22d

C:\Users\devgi>kubectl get pods -A
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code A3YVYUDGV to authenticate.
`

**Comment by weinong** [comment]
1.18.0 has bug. please use 1.18.1+.

**Comment by devgibsonsp** [comment]
@weinong 

Sorry, I was away last week and couldn't follow up. Bumping kubectl to 1.18.1+ does not resolve this issue.

**Comment by TomGeske** [comment]
@devgibsonsp: Did you run `az aks get-credentials` after updating kubectl?

**Comment by devgibsonsp** [comment]
@TomGeske 
Yeah. Same issue

```
C:\Users\devgi>az aks get-credentials --name <my-cluster> --resource-group <my-rg>
Merged "<my-cluster>" as current context in C:\Users\devgi\.kube\config

C:\Users\devgi>kubectl get pods -n kube-system
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <code> to authenticate.
NAME                                   READY   STATUS    RESTARTS   AGE
azure-cni-networkmonitor-dhxwt         1/1     Running   0          28d
azure-cni-networkmonitor-qqdjs         1/1     Running   0          28d
azure-cni-networkmonitor-r872m         1/1     Running   0          28d
azure-ip-masq-agent-67rvm              1/1     Running   0          28d
azure-ip-masq-agent-jmvwp              1/1     Running   0          28d
azure-ip-masq-agent-zwcp8              1/1     Running   0          28d
coredns-74dc64cb57-pgkrl               1/1     Running   0          7d1h
coredns-74dc64cb57-psncp               1/1     Running   0          7d1h
coredns-autoscaler-d5944b569-8z2d7     1/1     Running   0          7d1h
kube-proxy-2tlg4                       1/1     Running   0          21d
kube-proxy-4zlhd                       1/1     Running   0          28d
kube-proxy-vhmx6                       1/1     Running   0          28d
kubernetes-dashboard-98dcc4c7f-p6vc2   1/1     Running   0          9d
metrics-server-689c95f555-q6n96        1/1     Running   0          9d
omsagent-9dp7v                         1/1     Running   2          9d
omsagent-b75mv                         1/1     Running   1          9d
omsagent-kl9z9                         1/1     Running   2          9d
omsagent-rs-79698f896f-nqh6t           1/1     Running   0          9d
tiller-deploy-8557598fbc-fp9d6         1/1     Running   0          27d
tunnelfront-755b696fcc-6vwdh           2/2     Running   0          9d

C:\Users\devgi>kubectl get pods -n kube-system
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <code> to authenticate.
```

**Comment by weinong** [comment]
@devgibsonsp can you delete `C:\Users\devgi\.kube\config` and do `az aks get-credentials` again? from what I can tell, your kubeconfig may have been misconfigured due to older version of kubectl.

**Comment by devgibsonsp** [comment]
@weinong 
Deleted config, refetched credentials. Using 1.18.1. Still being prompted after fetching credentials. Only difference is now I am gettin an unauthorized error on the second try
`error: You must be logged in to the server (Unauthorized)`

**Comment by weinong** [comment]
@devgibsonsp can you send your cluster fqdn to aks-help@service.microsoft.com and reference this github issue? i can work with you offline. :)

**Comment by devgibsonsp** [comment]
@weinong 

So as per your response to my email. The problem does appear to have been due to having multiple different versions of kubectls installed simultaneously. It was resolved by uninstalling them all and reinstalling.

**Comment by palma21** [comment]
Thanks for circling back @devgibsonsp !

Closing, let us know if we can assist further.
