### ISSUE TITLE
Azure AD integration usage with Terraform

### ISSUE THREAD

**Issue by JakubWojtowicz-TomTom** [Azure/AKS#1763]
**What happened**:

I've enabled AAD integration for Kubernetes cluster today in Terraform module and I've noticed it is no longer possible to seamlessly integrate Azure part with Kubernetes/Helm provider.
Deployment of Kubernetes/Helm related resources via Terraform results with "Unauthorized" error.

**What you expected to happen**:

Resources are deployed without errors.

**How to reproduce it (as minimally and precisely as possible)**:

Create AKS cluster via Terraform and use it's outputs to configure Kubernetes provider.
Try to create Kubernetes resource e.g. namespace.

Example provider config:
```
provider "kubernetes" {
  version                = "1.11.3"
  host                   = module.aks.host
  client_certificate     = base64decode(module.aks.client_certificate)
  client_key             = base64decode(module.aks.client_key)
  cluster_ca_certificate = base64decode(module.aks.cluster_ca_certificate)
  load_config_file       = false
}
```

**Anything else we need to know?**:
I've also tried adding username and password to provider configuration. It did not affect the outcome.

**Comment by TomGeske** [comment]
Looks like you are continuing to use client certs for helm deployment? You may also want to look at [kubelogin](https://docs.microsoft.com/en-us/azure/aks/managed-aad#non-interactive-sign-in-with-kubelogin)

**Comment by JakubWojtowicz-TomTom** [comment]
I've taken a look at kubelogin already, however I wouldn't consider it as a feasible solution in this case.
It is an external tool that adds yet another dependency, so far single binary (terraform) was enough to deploy resources.
Moreover if kubelogin would be integrated in Terraform it would require creation of kubeconfig and some local-exec to use kubelogin. 
So far everything was seamlessly integrated in Terraform template, without any external dependencies.
I think if kubelogin was delivered in "terraform friendly" fashion (provider perhaps?) it could be a potential solution.

**Comment by TomGeske** [comment]
Thanks for your feedback.

kubelogin is a kubectl plugin. Terraform Kubernetes provider consumes official K8S Go library (prior to 1.1 release) and client Go library. @weinong: may have some ideas?

For your specific case: once you turn on AAD on your cluster, clients certs won't work anymore except the breaking glass cluster cert.

**Comment by jon-walton** [comment]
@JakubWojtowicz-TomTom here's an excerpt of what we do. The *only* thing using these certs is terraform

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  dns_prefix          = var.dns_prefix
  location            = var.location
  name                = "helloworld"
  resource_group_name = var.resource_group_name
  kubernetes_version  = var.control_plane_version

  private_cluster_enabled = true

  identity {
    type = "SystemAssigned"
  }

  role_based_access_control {
    enabled = true

    azure_active_directory {
      managed = true

      admin_group_object_ids = [
        "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
      ]
    }
  }
}


provider "kubernetes" {
  load_config_file       = false
  host                   = format("https://%s:443", azurerm_kubernetes_cluster.aks.private_fqdn)
  cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.aks.kube_admin_config[0].cluster_ca_certificate)
  client_certificate     = base64decode(azurerm_kubernetes_cluster.aks.kube_admin_config[0].client_certificate)
  client_key             = base64decode(azurerm_kubernetes_cluster.aks.kube_admin_config[0].client_key)
}
```

**Comment by JakubWojtowicz-TomTom** [comment]
@jon-walton Just the right solution I was looking for. Thanks!

Previously I've used kube_config, changing it to kube_admin_config worked like a charm.

**Comment by yves-vogl** [comment]
Hi,

I'd like to reopen this.

Using ```kube_admin_config``` means that the Terraform Kubernetes Provider is acting with cluster-admin privileges.

Now think of a multi-tenant environment in AKS were you hand out a AAD-integrated Azure Service Principal to a tenant.
This service principal has only restricted privileges on a certain namespace.

The tenant now wants to make use of this service principal in Terraform (e.g. in Terraform Cloud) in a non-interactive way.
At first thought you could add kubelogin to your execution environment and call kubelogin by the exec parameter of the Terraform Kubernetes Provider. kubelogin converts a kube-config file and uses the AAD_SERVICE_PRINCIPAL_SECRET environment variable to authenticate.

But as far as I know there's any kube-config created by the Terraform Kubernetes Provider, isn't it?
So a workaround could possibly be to use a local configuration file which needs to be setup before so that it can get converted.

(Mention: @timo-herweg)
