### ISSUE TITLE
Is there a way to expose NGINX Ingress through HTTPS without DNS (Only public IP) in AKS?

### ISSUE THREAD

**Issue by JerrySantana92** [Azure/AKS#1764]
I have the following scenario for a set of Web APIs that I'm exposing:

Azure Front Door (Entry point) -> NGINX Ingress (Public ip) > Services > Pods

I realized that in AKS is not possible to expose services as HTTPS so I had to create the Ingress.
I can use either NGINX or Azure Application Gateway but for cost savings, I preferred NGINX.

I have everything working as expected through HTTP.
I'm trying to complete my work by adding TLS Termination (SSL) at the NGINX level so that the APIs are accessible through HTTPS ONLY.

I just found that I need a DNS to do that but, how come there are other public IPs that are accessible with HTTPS?
Any thoughts?

**Comment by TomGeske** [comment]
Did you follow: https://docs.microsoft.com/en-us/azure/aks/ingress-own-tls? Just try to use your IP instead of DNS. 

You may also want to consider:
- Azure Traffic Manager 
- Azure DNS
