### ISSUE TITLE
AKS Memory RSS & Memory working set

### ISSUE THREAD

**Issue by zaabskr** [Azure/AKS#1766]
**What happened**:
 We are seeing that the spring boot application which is packaged as a docker container encountering memory issues.
The Memory RSS is stable for the application, while the Memory working set is constantly increasing.

**What you expected to happen**:
Why is the Memory working set increasing consistently.
I would like to know how to debug the issue. I dont see any issues (memory leaks) when I run the application as standalone jar.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 16.9
- Size of cluster (how many worker nodes are in the cluster?) 2-10 nodes, 8-24 pods
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
The application has a rest api endpoint which accepts files and saves it to adls2 and sends some information to event hub. We also use app config, keyvault.
- Others:

**Comment by zaabskr** [comment]
We are seeing 137 & 143 when the container is getting restarted

**Comment by zaabskr** [comment]
We ran two rounds of performance testing on the server. Below are the metrics that we collected from the container during run one and run two. We dont see any issue in the memory heap.

**Comment by zaabskr** [comment]
The metrics from inside the container during run one
[run-5-1-during.log](https://github.com/Azure/AKS/files/5052108/run-5-1-during.log)
The metrics from inside the container during run two
[run-5-2-during.log](https://github.com/Azure/AKS/files/5052109/run-5-2-during.log)

We are not able to understand which metric is causing the working set to increase, while the RSS is reported as stable and inline with what is reported from container. 

How do we map this metrics from inside to container to understand what is causing the increase in working set?

**Comment by palma21** [comment]
@vishiy @saaror do you think you can help troubleshoot with Azure monitor?

cc @juan-lee

**Comment by vishiy** [comment]
@zaabskr - RSS indicates whats currently residing in main mem, while the ws is how much memory the process needs in memory to continue working. so ws = memory used - inactive memory. We get these metrics from kubernetes (cAdvisor). From your #1 & #2 captures, looks to me there is some leak ???

**Comment by zaabskr** [comment]
@vishiy Thanks. We dont see from our application java native memory any leaks. We see memory/ active objects increasing from the slabinfo. Would you be able to take a look at the /proc/meminfo & slabinfo attached? We are using alpine linux as the base image. Any recommendations on the base image?

**Comment by zaabskr** [comment]
Closing the issue as we found the answer to the working set memory.
