### ISSUE TITLE
Enable private endpoint over public/internet

### ISSUE THREAD

**Issue by infa-ssaurabh** [Azure/AKS#1768]
**What happened**:
Private endpoint for private AKS cluster doesn't resolve over public/internet.

**What you expected to happen**:
When private endpoint for private AKS cluster resolves over public/internet, we should not make any changes anywhere to access the cluster(like editing host file).

**How to reproduce it (as minimally and precisely as possible)**:
Currently private AKS cluster private endpoint doesn't resolves over public/internet.

**Anything else we need to know?**:
na

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others: All AKS version

**Comment by TomGeske** [comment]
This is currently by design. Can you share more details on your scenario why that would be needed?

**Comment by infa-ssaurabh** [comment]
We can't access the cluster from VM(VMs are only used for automation) and we can't keep editing hosts file for each private cluster we create.

But why this is designed this way? Other Cloud provider such as AWS or GCP allows private endpoint to be resolved over public.

**Comment by TomGeske** [comment]
Are you just asking for DNS becoming available publicly or also for connectivity?

Would still be interested to hear your specific scenario.

**Comment by infa-ssaurabh** [comment]
only dns to be resolve over public/internet.

**Comment by infa-ssaurabh** [comment]
when are we expecting this feature?

**Comment by infa-ssaurabh** [comment]
Any update?

**Comment by feiskyer** [comment]
this is now supported with public DNS https://docs.microsoft.com/en-us/azure/aks/private-clusters#create-a-private-aks-cluster-with-a-public-dns-address
