### ISSUE TITLE
Azure cni error Failed to start network plugin, err:invalid character '\x00' looking for beginning of value.

### ISSUE THREAD

**Issue by zhiweiv** [Azure/AKS#1772]
**What happened**:
Windows nodes become Not Ready occasionally due to cni error
`2020/08/06 09:32:31 [4640] [cni-net] Failed to initialize network manager, err:invalid character '\x00' looking for beginning of value.`

azure-vnet.json was filled with invaild characters. Here is the file I collected from work node:
[azure-vnet.json.zip](https://github.com/Azure/AKS/files/5039075/azure-vnet.json.zip)

azure cni log:
[azure-vnet.log.zip](https://github.com/Azure/AKS/files/5039076/azure-vnet.log.zip)

Similiar issues: https://github.com/Azure/azure-container-networking/issues/306 https://github.com/Azure/azure-container-networking/issues/292. 

**How to reproduce it (as minimally and precisely as possible)**:
It only happen in job pod pools, run high volume of pods and delete them when they completed in Windows nodes.

**Environment**:
- Kubernetes version (use `kubectl version`): 
1.17.7

- Size of cluster (how many worker nodes are in the cluster?): 
10 nodes with auto scale

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
.net framewoker app to to process background tasks

**Comment by palma21** [comment]
CC @AbelHu

**Comment by AbelHu** [comment]
The cni json file is re-written to a binary so it is invalid. It seems like to be a regression issue in azure cni `v1.1.3`. @zhiweiv could you file an issue directly in Azure/azure-container-networking to involve azure cni team for advanced troubleshooting with your environment?

**Comment by zhiweiv** [comment]
Created a duplicate in azure cni repo, https://github.com/Azure/azure-container-networking/issues/642.

**Comment by AbelHu** [comment]
AKS will pick up the fix in the next monthly Windows VHD with the Windows Oct security patch.

**Comment by AbelHu** [comment]
The fix has been picked up by AKS in the RP release 20201019 and will be available in next days.

**Comment by zhiweiv** [comment]
Fixed in https://github.com/Azure/AKS/releases/tag/2020-10-19.
