### ISSUE TITLE
Infinite loop caused by cluster autoscaler and kured 

### ISSUE THREAD

**Issue by easimon** [Azure/AKS#1773]
**What happened**: 

I have an AKS cluster with VMSS autoscaling enabled, and kured to reboot for OS updates. 
These two currently do not match, but do the following:

- cluster runs at minimum allowed node count
- kured detects “reboot required” and starts to drains the node
- not enough capacity on other nodes, so autoscaler adds a "fresh" node (fresh image, no updates applied)
- kured finishes draining and reboots the old, updated node
- updated node remains empty since the new node took over everything
- autoscaler deletes the updated(!) node
- since the new node is a clean image with no updates applied, this repeats as soon as the new node receives the first set of updates requiring a reboot

**What you expected to happen**:

- when autoscaler scales in, it drains and deletes the youngest node instead of the emptiest (or random?) one.

**How to reproduce it (as minimally and precisely as possible)**:

- Create an AKS cluster with VMSS nodepools, activate autoscaling and install kured
- Create workloads to "fill" the nodes in terms of required capacity (mem, CPU), up to a point where draining a node triggers scale-out, and un-cordoning it afterwards triggers scale-in
- Wait for kured detecting "reboot required", and starting the scene described above.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"89d8075525967c7a619641fabcb267358d28bf08", GitTreeState:"clean", BuildDate:"2020-06-23T02:52:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?)

autoscaler set to 3-7, running at 3 nodes most of the time.

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

NodeJS microservices mostly

- Others:

N/A

**Comment by TomGeske** [comment]
@palma21

**Comment by easimon** [comment]
Additional info:

Since the apt autoupdate does not run immediately upon creation of the node (exact schedule is unclear to me), there's also no way to make kured proceed fast enough before scale-in happens -- except I set the scale-in delay to more than a day or so.

Of course I could explicitly set the minimum node number high enough to always have capacity to drain another node, but that somehow invalidates the point of autoscaling, I think.

**Comment by marwanad** [comment]
@easimon 
just to confirm are you using the [VMSS autoscaler] (https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-autoscale-overview) or[ cluster autoscaler](https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler)

**Comment by easimon** [comment]
@marwanad the cluster autoscaler. The vmss autoscaling is off. With vmss autoscaling I could set a scale-in policy (but then not scale out based on pod resource requests) -- and somewhat void the warranty.

**Comment by marwanad** [comment]
@easimon If there are pods that are pending due to kured draining a node and tainting it - CA will add nodes to ensure the workload is schedulable.

The node that kured rebooted then becomes empty and is considered for deletion. 

CA has no insights into kured operations and only acts in response to pending pods or nodes suitable for removal.

I'm not too familiar with kured's internals but does this issue match what you're seeing: https://github.com/weaveworks/kured/issues/93

**Comment by palma21** [comment]
If I may, you might want to consider just automating/runbook of node image upgrade on your own schedule?
https://docs.microsoft.com/en-us/azure/aks/node-image-upgrade

This should make the right behavior w/ CA.

**Comment by easimon** [comment]
If that's considered to be by design, I guess this should at least deserve a warning in either of these pages, or both.

https://docs.microsoft.com/en-us/azure/aks/node-updates-kured
https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler

**Comment by easimon** [comment]
@palma my customer is somewhat hesitant to use preview features in production. Is there a schedule for node image upgrades to become GA?

Or could the current aks images be altered to do an apt upgrade directly on/after boot, so they come up updated, immediately triggering  "reboot required"?

**Comment by easimon** [comment]
> I'm not too familiar with kured's internals but does this issue match what you're seeing: [weaveworks/kured#93](https://github.com/weaveworks/kured/issues/93)

Yes, seems exactly like what I see.

**Comment by palma21** [comment]
Yes, we plan to remove kured from those docs. Node image upgrade is going GA in a couple weeks.

fwiw Node Image upgrade in preview is more supported than kured which has no official support.

Not sure I understood your last question completely, happy to comment if you can elaborate, otherwise if the above answers your question feel free to ignore.

**Comment by easimon** [comment]
The question was targeted towards making kured work (better) with Cluster-Autoscaler. Currently, the AKS Images include a scheduled Auto-Update job... That's what triggers kured in the first place. But this schedule obviously does not run very often, especially new nodes need multiple hours if not days to set the "reboot required" flag. If the auto-upgrade ran closer to node creation, kured could immediately kick in and drain/reboot that node, causing the other upgraded node to fill again (and not be scaled in).

In that case, setting kured to check more often than the cluster autoscaler scale-in delay could make these two work together.

If you do plan to deprecate the use of kured, please do not just delete that page, but put some warning somewhere about the behaviour and that it does not work well with cluster autoscaler.

**Comment by palma21** [comment]
Absolutely, we'll have that in mind. Unfortunately there's not a lot of traction upstream to solve this problem with us, so we'll try to deliver that same experience with node image upgrade and the automatic node image upgrade experience (coming this semester).
