### ISSUE TITLE
Please enable newer SKUs in AKS.

### ISSUE THREAD

**Issue by porrascarlos802018** [Azure/AKS#1774]
Standard_E16ds_v4 is needed , do we have an ETA when could it be made available?

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by ohorvath** [comment]
That would be very useful, the current v3 offering if pretty outdated, the temp disk IOPS is way too low.

**Comment by ohorvath** [comment]
Any update on this? :)

**Comment by palma21** [comment]
<2weeks

**Comment by asubmani** [comment]
@porrascarlos802018 curios to know what kind of workloads you are planning to run on this & what max pod setting you are planning to use? 

My workloads are a mix of jobs/cron jobs and web/api's (all java/spring micro services).. I was dabbling with the idea of using either smaller VM's and scale horizontally vs going for a large VM size that runs 100+ pods.

Was looking for common gotchas on VMSS sku sizinging for generic workloads that typically run at 640MB and 400M cpu

**Comment by alexeldeib** [comment]
Standard_E16ds_v4 has been available for a few weeks or so now. In addition, we dynamically pull the list of SKUs from ARM and Compute now so this shouldn't be an issue in the future. 

Marking as closed.
