### ISSUE TITLE
nodepool autoscaling not working

### ISSUE THREAD

**Issue by Morriz** [Azure/AKS#1779]
Please don't let your stupid bot close issues when they are not resolved. Now I have to start another one about autoscaling not working out of the box.

**What happened**:
started a cluster with autoscaling enabled, letting azure choose the zones
scheduler maxed out nodes (almost all go to or over 100% mem and cpu)

**What you expected to happen**:
autoscaling to work

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.9
- Size of cluster (how many worker nodes are in the cluster?) 4

**Comment by marwanad** [comment]
@Morriz The nodes can be maxed out but do you have pods pending in your cluster? If there are no pending pods, autoscaler doesn't take action.

Can you share the outuput of `k describe configmap --namespace kube-system cluster-autoscaler-status`?

**Comment by Morriz** [comment]
I would expect some sane node resource detection mechanism to be there, that scales when node resources reach mem or cpu thresholds. Is that not the case? Of course the total request of the pods would also be taken into account, so that when either mechanism triggers it scales up the nodes.

**Comment by Morriz** [comment]
btw, that configmap does not exist

**Comment by Morriz** [comment]
I had to switch to manual mode to fix the cluster. That might have removed it. I will turn it back on to see what happens

**Comment by marwanad** [comment]
@Morriz CA operates purely based on a pending pod scheduling basis. It makes sure that your cluster has the exact amount of resources to run the workloads. The trigger action for a scale operation and thus the addition of nodes is a pod that can't be scheduled. If all pods are scheduled and Running, there's no need to take action from CA's point of view.

**Comment by Morriz** [comment]
Here's the output of the current `cluster-autoscaler-status`:
```
Name:         cluster-autoscaler-status
Namespace:    kube-system
Labels:       <none>
Annotations:  cluster-autoscaler.kubernetes.io/last-updated: 2020-08-12 08:18:51.201055029 +0000 UTC

Data
====
status:
----
Cluster-autoscaler status at 2020-08-12 08:18:51.201055029 +0000 UTC:
Cluster-wide:
  Health:      Healthy (ready=6 unready=0 notStarted=0 longNotStarted=0 registered=6 longUnregistered=0)
               LastProbeTime:      2020-08-12 08:18:51.1986468 +0000 UTC m=+84301.109571292
               LastTransitionTime: 2020-08-11 08:54:02.271498981 +0000 UTC m=+12.182423573
  ScaleUp:     NoActivity (ready=6 registered=6)
               LastProbeTime:      2020-08-12 08:18:51.1986468 +0000 UTC m=+84301.109571292
               LastTransitionTime: 2020-08-11 08:54:02.271498981 +0000 UTC m=+12.182423573
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      2020-08-12 08:18:51.1986468 +0000 UTC m=+84301.109571292
               LastTransitionTime: 2020-08-11 08:54:02.271498981 +0000 UTC m=+12.182423573

NodeGroups:
  Name:        aks-agentpool1-37806765-vmss
  Health:      Healthy (ready=6 unready=0 notStarted=0 longNotStarted=0 registered=6 longUnregistered=0 cloudProviderTarget=6 (minSize=6, maxSize=10))
               LastProbeTime:      2020-08-12 08:18:51.1986468 +0000 UTC m=+84301.109571292
               LastTransitionTime: 2020-08-11 08:54:02.271498981 +0000 UTC m=+12.182423573
  ScaleUp:     NoActivity (ready=6 cloudProviderTarget=6)
               LastProbeTime:      2020-08-12 08:18:51.1986468 +0000 UTC m=+84301.109571292
               LastTransitionTime: 2020-08-11 08:54:02.271498981 +0000 UTC m=+12.182423573
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      2020-08-12 08:18:51.1986468 +0000 UTC m=+84301.109571292
               LastTransitionTime: 2020-08-11 08:54:02.271498981 +0000 UTC m=+12.182423573
```
So it seems all is fine, but the system is already at 75% cpu usage, and 72% mem usage.

Is there a way to set thresholds for node autoscaling? And where can I see output of the AKS autoscaler that computes requests?

**Comment by marwanad** [comment]
Again, it's not based on % utilization for scale-up. If there are no pending pods and all pods are scheduled and running, there is nothing to be done.

You can get the CA logs from [here](https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler#retrieve-cluster-autoscaler-logs-and-status). If you want to configure some buffer in your cluster, you can consider [overprovisioning](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler).

**Comment by marwanad** [comment]
Going to make as answer provided but feel free to pop with any follow-ups.
