### ISSUE TITLE
Support specifying k8s configuration context/cluster name with `az aks get-credentials`

### ISSUE THREAD

**Issue by mvaldesdeleon** [Azure/AKS#178]
**Current situation:**

Running `az aks get-credentials` will install the kubernetes configuration context for the specified cluster, using the cluster's name as the both the cluster and context names.

If a cluster or context with the same name already exists, then both entries will be kept, with the last one shadowing the first one.

This means that eventhough the kubernetes configuration file will contain both entries, only one of them will be selectable via `kubectl config` commands.

**Suggested Solution::**

A new parameter could be added to `az aks get-credentials` that allows overriding the internal key to be used when referring to both the cluster and the context in the kubernetes configuration file.

Optionally, `az aks get-credentials` should check for collisions and either warn the user or prompt for a rename.

**Workaround:**

Manually edit the kubernetes configuration file and provide a different name for the duplicated cluster and context, and ensure they are properly linked.

**Comment by gomker** [comment]
Running into same issue doing testing as I destroy and recreate ACS clusters using Ansible. I have to delete the existing configuration before I test.

**Comment by mboersma** [comment]
This behavior was changed last year to require the `--overwrite-existing` argument if the user wants the kubeconfig to be overwritten.  Also see Azure/azure-cli#8681.
