### ISSUE TITLE
Sync all docs.microsoft API references to 2020-07-01

### ISSUE THREAD

**Issue by flamingboo** [Azure/AKS#1780]
The latest version of API and the corresponding ARM template that are published date back 2020/04.
https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2020-04-01/managedclusters

Is there a reason why the latest one (2020/07) is not yet available?
We are planning to deploy an AKS cluster (with the latest features) using ARM template and as such, it would great it to use the latest ARM template using api version 2020/07.

Thank you

**Comment by jluk** [comment]
This is an active item, 2020-07-01 has not been officially published yet but when it is the following references will be updated to sync the versions.

https://docs.microsoft.com/en-us/rest/api/aks/managedclusters
https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable
