### ISSUE TITLE
How can I manage the client AAD application when I use AKS managed AAD?

### ISSUE THREAD

**Issue by qinmaye** [Azure/AKS#1782]
First, I create an AKS cluster by the way that AKS managed AAD

I use a admin group created by myself.
```Azure Cli
# Create an AKS-managed Azure AD cluster
az aks create -g myResourceGroup -n myManagedCluster --enable-aad --aad-admin-group-object-ids
```

After creating the cluster, I want to use keycloak-proxy to visit the dashboard  of the AKS cluster. By I can only see the servicePrincipalProfile client ID.

I check the admin-group and there are no applications under the application.

![image](https://user-images.githubusercontent.com/33417731/89870236-1d60cc00-dbe8-11ea-8891-c0852c29d5c2.png)

so, how can I find and manage the client application to achieve my goal.

If I can't visit the client application, how can I  configure for the keycloak-proxy to visit dashboard?

Thank you very much.

**Comment by TomGeske** [comment]
What do you need to find out? Application ID of your server app should be visible in .kube/config apiserver-id.

**Comment by qinmaye** [comment]
> What do you need to find out? Application ID of your server app should be visible in .kube/config apiserver-id.

Yep, I can get the application ID, but I can't manage the AAD application from Azure portal.

**Comment by qinmaye** [comment]
Thanks for @TomGeske resolving my question.
