### ISSUE TITLE
Lingering "transitioning" pods that should be deleted in AKS w/ k8s v1.18.4

### ISSUE THREAD

**Issue by brobichaud** [Azure/AKS#1783]
**What happened**:
I've deployed a new cluster with k8s v1.18.4. All of my Windows workloads deploy and run fine but when I deploy new versions I am sporadically seeing pods that should be deleted linger for hours in a "transitioning" state. Attempting to manually delete them does nothing. They seem dead, as in they are not responding and console logs do not exist, but they continue to show up in a kubectl get pods command.

**What you expected to happen**:
The pods should be cleaned up as they normally are. New deployments should adds new pods and remove old pods according to the deployment manifests update strategy.

**How to reproduce it (as minimally and precisely as possible)**:
I can't repro it on demand, but I am seeing it often enough that it is clearly not an isolated thing.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.4
- Size of cluster (how many worker nodes are in the cluster?): 2 Standard_D8as_v4 Windows nodes, 2 Standard_F2s_v2 linux nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Mix of DotNetCore and DotNet Api's WebUI's and workers
- Others:

**Comment by brobichaud** [comment]
This continues to be an issue for us. I realize that k8s v1.18.x is in preview but then I also see that AKS intends to GA it on Aug 31. It would be good to get this resolved or understood before then.

**Comment by palma21** [comment]
CC @AbelHu @marosset @craiglpeters

**Comment by brobichaud** [comment]
A little more context. The pods never seem to delete on their own, but we are able to manually delete them using:

`kubectl delete pod --force <podname>`

I am unable to repro this on demand and don't see an obvious pattern, but it continues to occur regularly.

The pods that are replacing them are running fine. None of our deployment manifests have changed in months, only the k8s version has changed (a newly provisioned cluster). We are seeing this on two clusters, both v1.18.4.

**Comment by palma21** [comment]
Thanks @brobichaud  just a couple additional questions.
Did it work as expected in previous k8s versions?
Does it happen only with windows or windows and linux?
Did you happen to try with 1.18.6 as well?

**Comment by brobichaud** [comment]
Yeah we never saw this behavior in our previous clusters running v1.15.10. Those clusters had been running nearly flawlessly for about a year with various versions of k8s. We only run Windows workloads so I am unsure about linux. I haven't tried v1.18.6 yet because it's marked preview, which to me meant even more risky than v1.18.4. We don't generally run preview versions but since I saw you plan to GA by end of month I felt ok with v1.18.4 for our new clusters.

**Comment by brobichaud** [comment]
We've upgraded to k8s v1.18.8 now that it has gone GA in AKS and continue to see this problem.

**Comment by brobichaud** [comment]
Upgrading to k8s v1.18.10 has solved this problem. Closing.
