### ISSUE TITLE
Support for Azure RBAC for k8s Authorization

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#1786]
https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac

**Comment by googol** [comment]
Hi, what's the current plan for GA for this?

**Comment by theherder** [comment]
GA timeline please?

**Comment by schlbra** [comment]
Do we have an estimated timeline for when this feature will be Generally Available? 

Our organization finds this feature extremely useful but we are not able to actually use it in production until it goes GA. We appreciate any updates and efforts related to this feature.

**Comment by aristosvo** [comment]
@palma21 Is there a way to track whether the enablement of this feature for existing clusters is GA? 

For now that's behind a Preview flag, `aadProfile.enableAzureRBAC requires Microsoft.ContainerService/UpdateAzureRBACPreview feature flag.`

**Comment by robinmanuelthiel** [comment]
@palma21 are we sure that this is fully GA? When trying to add `--enable-azure-rbac` to an existing cluster, the CLI asks us to register this **Preview** feature flag:

![image](https://user-images.githubusercontent.com/5874465/119963399-5405a880-bfa8-11eb-992d-00c4f36914a6.png)

**Comment by Imroath** [comment]
In West Europe with latest  az cli 1.24.0 when creating new cluster from scratch it still requires Preview feature flag registration:
![image](https://user-images.githubusercontent.com/26322851/119983927-1a8d6700-bfc1-11eb-82dd-34b0b95cb3dd.png)

**Comment by aristosvo** [comment]
Feature seems released, see also https://github.com/terraform-providers/terraform-provider-azurerm/pull/12029
