### ISSUE TITLE
Open Service Mesh (OSM) Addon

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#1787]
AKS Addon for https://openservicemesh.io/

**Comment by derkoe** [comment]
Seems like this is in Preview now :-)

    These addons are available:
        ingress-appgw             - enable Application Gateway Ingress Controller addon (PREVIEW).

**Comment by tomkerkhove** [comment]
This is actually a different one:
- https://github.com/Azure/application-gateway-kubernetes-ingress
- https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-overview

**Comment by derkoe** [comment]
Sorry copied the wrong line - `az aks create -h` shows:

    These addons are available:
        open-service-mesh         - enable Open Service Mesh addon (PREVIEW).

**Comment by ams0** [comment]
```
az feature register --name AKS-OpenServiceMesh --namespace Microsoft.ContainerService
UnknownError: The feature 'AKS-OpenServiceMesh' does not support registration.
```

When can this be available? Am I missing something (I usually do)?

**Comment by palma21** [comment]
If it were already available it would be announced :) 

We expect to have it soon for folks to try out!

**Comment by DenisBiondic** [comment]
Is this going to support windows nodes / windows container workloads?

**Comment by keikhara** [comment]
@DenisBiondic  yes. I added to our backlog roadmap.

**Comment by ckittel** [comment]
For those looking for docs on this Preview: https://docs.microsoft.com/azure/aks/servicemesh-osm-about

**Comment by JasonWhall** [comment]
Updated link for reference - https://docs.microsoft.com/azure/aks/open-service-mesh-about

**Comment by ardacetinkaya** [comment]
I am getting the following error when I try to enable addon. 
Any help or idea?

> The behavior of this command has been altered by the following extension: aks-preview
(OpenServiceMeshAddonFeatureFlagNotEnabled) OpenServiceMesh addon is not allowed since feature 'Microsoft.ContainerService/AKS-OpenServiceMesh' is not enabled. Please see https://aka.ms/aks/previews for how to enable features.

When I list the addons;
>   {
    "description": "- enable Open Service Mesh addon (PREVIEW).",
    "name": "open-service-mesh"
  }

AKS Cluster Version:  1.20.9

**Comment by ardacetinkaya** [comment]
Is this add-on really GA for AKS? I could not enable it in my cluster, I got the above☝🏻 error when I try as documented.

**Comment by palmerabollo** [comment]
@ardacetinkaya yes, it was [officially announced as GA](https://techcommunity.microsoft.com/t5/apps-on-azure/open-service-mesh-osm-integration-with-azure-kubernetes-service/ba-p/2902151) on Nov 2.

I had to run the following command on my Azure account before creating the AKS cluster:

```
az feature register --namespace Microsoft.ContainerService --name AKS-OpenServiceMesh
```

I agree it shouldn't be needed for a GA feature.

**Comment by ardacetinkaya** [comment]
Thanks a lot @palmerabollo 
It is now done. Time to dig more 😀


To have general info;  when I registered the feature with above ```az feature...``` 👆 It also displayed the following info

> Once the feature 'AKS-OpenServiceMesh' is registered, invoking 'az provider register -n Microsoft.ContainerService' is required to get the change propagated

So I re-registered the provider 
```
az provider register -n Microsoft.ContainerService
```
And then enable Open Service Mesh is done
```
az aks enable-addons --addons open-service-mesh -g <resource_group_name> -n <cluster_name>
```

**Comment by palma21** [comment]
GA - https://docs.microsoft.com/en-us/azure/aks/open-service-mesh-about
