### ISSUE TITLE
Programatically retrieve the Managed Cluster's own Resource Group name

### ISSUE THREAD

**Issue by mvaldesdeleon** [Azure/AKS#179]
**Current Situation:**

When creating a new cluster with `az aks create`, a new Resource Group specific to that cluster is created, and all managed cluster resources are created within this Resource Group.

As part of our standard cluster creation procedure, we would then provision a Public IP address to be used within the cluster. However, current aks limitations force us to provision this Public IP address within the same Resource Group as the managed cluster resources.

We would like to automate the entire process, and this means we would need a way of automatically retrieving the managed cluster's Resource Group name. We've noticed that they seem to follow a general pattern of `MC_[resource-group]_[cluster-name]_[location]`, but we feel there will be additional logic involved as the names get longer, so we would not want to depend on hardcoding this reverse-engineered strings in our scripts.

**Suggested Solution:**

`az aks list` and/or `az aks show` should allow retrieving the name of this Resource Group.

**Comment by slack** [comment]
Great suggestion, I've got a ticket in our backlog for this. Bubbling up toward the top of the pile.

**Comment by andrey-moor** [comment]
@slack any update on this?

**Comment by brantb** [comment]
AKS resources in the Resource Manager API now have a property named `nodeResourceGroup` that seems to contain this information. We've been returning it as the output from our ARM template like this:

```json
"outputs": {
  "nodeResourceGroup": {
    "type": "string",
    "value": "[reference(concat('Microsoft.ContainerService/managedClusters/', 
      parameters('resourceName'))).nodeResourceGroup]"
  }
}
```

**Comment by palma21** [comment]
Added property as noted by brantb
