### ISSUE TITLE
Allow larger Pods allocation limit per node after cluster creation  - is this feature available now?

### ISSUE THREAD

**Issue by ushabapat** [Azure/AKS#1790]
Hi,

I'm looking for option to increase the Pod allocation limit from default 30 to larger number on the existing cluster. Is this feature available now to modify on the existing cluster rather re-creating it.

AKS- 1.17.7
Node- 5 ( Standard   DS4 v2 (8 vcpus, 28 GiB memory)
--

**Comment by paulgmiller** [comment]
You can't change this on an agentpool currently  but you can add a new agentoool with a higher value and delete the old one.
