### ISSUE TITLE
Unable to use existing IP for ingress when cluster is created using that IP for outbound

### ISSUE THREAD

**Issue by QTom01** [Azure/AKS#1791]
**What happened**:
I created an AKS instance using the Azure CLI, and passed an existing PublicIP using `--load-balancer-outbound-ips`. The cluster created with no errors and all seems to be running fine, I can see it has correctly assigned my IP as the outbound IP. 

I then deploy the nginx ingress via helm like so (based on https://docs.microsoft.com/en-us/azure/aks/ingress-static-ip): 
```
kubectl create namespace ingress-basic
helm repo add stable https://kubernetes-charts.storage.googleapis.com/
helm repo update
helm install nginx-ingress stable/nginx-ingress `
    --namespace ingress-basic `
    --set controller.replicaCount=2 `
    --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux `
    --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux `
    --set controller.service.loadBalancerIP=$staticIp `
    --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"=$ipDnsLabel `
    --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-resource-group"=$ipResourceGroup
```

Again this runs successfully, however when I look at the `nginx-ingress-controller` it stays stuck at `<pending>`. When I inspect the events I can see the error:
```
Code="PublicIPReferencedByMultipleIPConfigs" Message="Public ip address /subscriptions/<redacted>/resourceGroups/myResourceGroup/providers/Microsoft.Network/publicIPAddresses/myPublicIp is referenced by multiple ipconfigs in resource /subscriptions/<redacted>/resourceGroups/clusterResourceGroup/providers/Microsoft.Network/loadBalancers/kubernetes." Details=[]
```

So it seems something is preventing the IP from being assigned. If I had to guess it may be that the cluster is trying to create a new Frontend IP configuration, when it already has one for the target IP, rather than just updating the inbound rules?

_However this same setup works fine if I follow a different process:_
- Create cluster without specifying the IP (so it creates a new one)
- Deploy nginx-ingress using my existing IP (which works correctly)
- Manually update the rules in the load balancer to use my existing IP for egress too
- Run `az aks update` and set  `--load-balancer-outbound-ips` to my static IP (otherwise on kubernetes update etc it ends up creating its own again)
- Delete the automatically created IP

At this point the cluster works fine using my static IP for both inbound and outbound traffic.

**What you expected to happen**:
I expect the cluster to successfully create the ingress when it is already using the IP as the outbound IP address.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a cluster with `az aks create` and point to an existing IP using `--load-balancer-outbound-ips`
- Deploy nginx-ingress via helm pointing to the same IP

**Anything else we need to know?**:
My static IP and cluster are in different resource groups. I have given the cluster `Network Contributor` role in the IPs resource group.

**Environment**:
- Kubernetes version: v1.17.9
- Size of cluster: 3 nodes of Standard_B2s
- General description of workloads in the cluster: Newly created cluster with nothing deployed to it

**Comment by TomGeske** [comment]
Are you using the same IP for  --set controller.service.loadBalancerIP=$staticIp ` and --load-balancer-outbound-ips?

**Comment by QTom01** [comment]
The same resource yes, however for controller.service.loadBalancerIP the value is the actual IP address (50.129... etc), and for --load-balacner-outbound-ips the value is the fully qualified azure resource name (/subscriptions/x/resourceGroups/u/providers/Microsoft.Network/publicIPAddresses/z)

**Comment by TomGeske** [comment]
Try to use different IPs for ingress and egress. 

cc: @palma21

**Comment by QTom01** [comment]
I believe it works fine using different ones, but I want to use the same one as we have a pre existing IP that has been whitelisted by our clients already.

**Comment by palma21** [comment]
Will be possible on k8s 1.20

**Comment by xuto2** [comment]
yes it's an issue in k8s cloud provider. Need upstream fix. 
(It worked in the second way because AKS RP has the fix when it config the outbound IP).

**Comment by denniszielke** [comment]
@palma21 : can you link the upstream issue?

**Comment by dennis-benzinger-hybris** [comment]
> Will be possible on k8s 1.20

Any plans to patch this in 1.19 ?

**Comment by denniszielke** [comment]
@dennis-benzinger-hybris : sorry no back port. Can you implement the workaround?

**Comment by dennis-benzinger-hybris** [comment]
I think we'll wait for 1.20 in AKS 😉.
