### ISSUE TITLE
nodepool upgrade onto 1.17.9 fails with "Pre-allocated IPs 276 exceeds IPs available 251 in Subnet"

### ISSUE THREAD

**Issue by omichels** [Azure/AKS#1795]
**What happened**:
$ az aks nodepool upgrade --resource-group elknodepooltestresourcegroup --cluster-name elknodepooltestk8s --name internal --kubernetes-version 1.17.9 

failed with 
'Bad Request'. Details: Pre-allocated IPs 276 exceeds IPs available 251 in Subnet Cidr 10.142.26.0/24

**What you expected to happen**:
k8s upgrade of node pool onto 1.17.9

**How to reproduce it (as minimally and precisely as possible)**:
i have created a new k8s cluster with 2 node pools, then upgraded the control plane from 1.17.7 onto 17.9.
Trying to upgrade the nodepools failed

**Anything else we need to know?**:
We are running 2 clusters (DEV / PROD) and are trying to implement aks nodepools to support rolling k8s upgrades, have created a test cluster first

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.7
- Size of cluster (how many worker nodes are in the cluster?)
2 nodepools with 2 nodes each
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Java Microservices
- Others:

**Comment by omichels** [comment]
control plane was upgraded first onto 1.17.9 and ran successfully

**Comment by omichels** [comment]
created support request in portal with # 120081425000595

**Comment by omichels** [comment]
support found the combination of using a CIDR /24 and max_pods=60 as the culprit.
pool 1 with 2 nodes plus 1 extra node with max_pods=30 results in 93 reserved IPs (3 x 30 +3)
pool 2 with 2 nodes plus 1 exrag node with max_pods=60 results in 183 reserved IPs (3 x 60 +3)
the total of 276 was not available in a CIDR /24 subnet

anyway, there is a bug in validating the preconditions ;-)

**Comment by palma21** [comment]
We'll take a look at the validation math here. @paulgmiller @wenwu449

**Comment by paulgmiller** [comment]
IF the precondition was that you were only upgrading 1 node pool at a time not all of them, then we believe we fixed this in early December 4th and it should be in all public regions now (internal PR  3850566)
