### ISSUE TITLE
AKS Cluster Failed - due to internal error 

### ISSUE THREAD

**Issue by sjwexler52** [Azure/AKS#1798]
Hello,

I've been coming up against a brick wall.  Below is my "az aks" command used to create my cluster.

After about 15 minutes I received this error.   First off what does it mean?  Secondly what do I need to do in order to get this to work?

 az aks create --name AKS-Cluster   --resource-group bdc-rg  --generate-ssh-keys  --node-vm-size Standard_L8s_v2  --node-count 1 --kubernetes-version 1.16.13

Error Message:

"Deployment failed. Correlation ID: 56833296-2c31-4955-b32e-aecc5aab6d3b. We are unable to serve this request due to an internal error, Correlation ID: 96ac19dd-d028-4d20-b698-8e66d35acd7a, Operation ID: 8bfa787e-1c64-4aac-9ef2-193493ad6380, Timestamp: 2020-08-14T00:01:11Z."

I am going to delete the resource group so I do not get charged any extra money.  This is very easy to recreate just issue the command in Powershell and wait about 15 minutes....

Anybody have any clues?   This really sucks....

**Comment by palma21** [comment]
Are you still having this issue?
