### ISSUE TITLE
 Cannot set static egress ip

### ISSUE THREAD

**Issue by SamAmin2** [Azure/AKS#1799]
Hi, 
I have a very simple cluster set up currently. What I need to do is to set a static IP for all my outbound traffic, as I need to provide this ip for whitelisting to counterparties. 
I have tried both of the approaches below, neither worked 
https://docs.microsoft.com/en-us/azure/aks/egress
 https://ritazh.com/whitelist-egress-traffic-from-kubernetes-8a3adefd94b2
 According to these if I have a loadbalancer with a public ip, all outbound traffic will go through that ip. Currently I have a nginx ingress controller setup with a public ip. 
This is what I get if I list all loadbalancers 

kubectl get services    
NAME                            TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                      AGE
fun-chimp-privalgofixengine     ClusterIP      10.0.205.172   <none>          80/TCP                       15m
kubernetes                      ClusterIP      10.0.0.1       <none>          443/TCP                      3d6h
nginx-ingress-controller        LoadBalancer   10.0.155.211   40.**.***.***   80:31175/TCP,443:30307/TCP   26m
nginx-ingress-default-backend   ClusterIP      10.0.191.112   <none>          80/TCP                       26m

As you can see, there's only one external ip, and thats the one I want to user. And yet, any outbound traffic from any of my pods still gets another ip 
curl -s checkip.dyndns.org 
Current IP Address: 51.**.***.***

I've opened a support case, but any tips would be appreciated.
Thanks
Sam

**Comment by TomGeske** [comment]
did you use` --load-balancer-outbound-ips` while [creating the cluster](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create)? 

`az aks create -g MyResourceGroup -n MyManagedCluster --load-balancer-outbound-ips <ip-resource-id-1,ip-resource-id-2>`

**Comment by SamAmin2** [comment]
HI Tom
Thanks for getting back to me.
I think it's some of the documentation out there that's confusing as it mentions that outbound traffic will use one of the inbound load balancer ips.
But I got a very good response from Microsoft support which explained everything, so now I know the ip I see that the system is currently using, will not change unless the cluster is recreated which is fine with me.

Response below:

From the case notes provided It looks like you are having some trouble with a static IP for your egress traffic.   You say you need to set a static IP for all of you out bound traffic.  By default all of your outbound 
traffic will flow through the load balancer that was created with the cluster, which is a separate load balancer than any you would create for a service and it is for egress traffic only.  Although this IP is created 
dynamically it will be static for the life of the cluster.  That is the 51.**.**.** IP you found running the curl -s checkip.dyndns.org command.  You can use this IP for white listing.

Again the IP 51.**.**.** is static for the life of the cluster, however; if you have your own static IP you want to use or if you want to keep the same IP after cluster deletion then you can update the egress IP
by running the following command.

az aks update --resource-group containers.dev.rg --name aks-dev --load-balancer-outbound-ips <publicIpId1>


Here is documentation on how to add your own IP, https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#provide-your-own-outbound-public-ips-or-prefixes.  This documentation is for the 
Basic load balancer SKU, but you run the Standard load balancer SKU, https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#provide-your-own-outbound-public-ips-or-prefixes
