### ISSUE TITLE
Unable to get pod logs

### ISSUE THREAD

**Issue by adhodgson1** [Azure/AKS#18]
Running a new AKS cluster in UKWest.

Running a command to get logs on a crashed pod gives me the error:
kubectl --namespace=kube-lego logs kube-lego-2933009699-p2jlm
Error from server: Get https://aks-agentpool1-17180407-0:10250/containerLogs/kub
e-lego/kube-lego-2933009699-p2jlm/kube-lego: dial tcp 10.240.0.4:10250: getsocko
pt: connection refused

Anyone else seeing similar?  Haven't upgraded the cluster to 1.8 yet.

Andrew.

**Comment by khenidak** [comment]
Hi @adhodgson1 this relates to the capacity issue. Specifically the network FE IP for our load balancer https://github.com/Azure/AKS/issues/2 we are actively working this one out. I recommend you keep an eye on issue #2  we are updating it

**Comment by slack** [comment]
Re-provision in West US 2 should provide a working AKS cluster.
