### ISSUE TITLE
Node stopped responding

### ISSUE THREAD

**Issue by vcorr** [Azure/AKS#180]
Today our cluster's only node went into **NotReady** status and all the pods become unreachable. I was able to revive the pods by adding another node, which took over the work.

kubectl describe nodes gives the following information

NetworkUnavailable   **False**
OutOfDisk                   **Unknown**
MemoryPressure        **Unknown**
DiskPressure               **Unknown**
Ready                          **Unknown**

There are no messages or other hints on what went wrong and according to Azure portal the VM is fine. But it's not responding and nothing runs on it...

Questions:
a) what happened?
b) aren't nodes supposed to be self healing?

**Comment by shahiddev** [comment]
I don't believe nodes are self-healing, k8s will re-create the missing pods when the node goes down but obviously needs more than one node to do that.
If we had node autoscaling in play would be interesting to know if that would have detected the down node and provisioned a new one?

**Comment by vcorr** [comment]
I'm still a little surprised the node went down like that. We have several traditional VMs in Azure and they rarely ever have issues or downtime. This node was only 11 days old.

I was able to bring it back by draining it with
`kubectl drain --force=true --ignore-daemonsets`
Then bring it back to ready status with
`kubectl uncordon`

I then scaled the cluster back to 1 node and now everything is running again, but obviously this would have been terrible in production, this is just a dev cluster.

We are using a B-series (burstable) VM as a node, I wonder if it could be causing the issue?

**Comment by nocon** [comment]
I can confirm I've been seeing similar issues on B series cluster. Usually, one of the nodes would go into NotReady within 24 hours of setup. Switching to DS series seems to have fixed the issue entirely.

**Comment by Trane9991** [comment]
```
  MemoryPressure       Unknown   Tue, 03 Apr 2018 07:18:24 +0300   Tue, 03 Apr 2018 07:19:08 +0300   NodeStatusUnknown          Kubelet stopped posting node status.
  DiskPressure         Unknown   Tue, 03 Apr 2018 07:18:24 +0300   Tue, 03 Apr 2018 07:19:08 +0300   NodeStatusUnknown          Kubelet stopped posting node status.
  Ready                Unknown   Tue, 03 Apr 2018 07:18:24 +0300   Tue, 03 Apr 2018 07:19:08 +0300   NodeStatusUnknown          Kubelet stopped posting node status.
```

Got this after running cluster for couple weeks

**Comment by seb-bartholomew-amcs** [comment]
I have had the same as @nocon using B series based cluster. I noticed credits remaining had drained to zero under metrics overnight (due to odd increase in CPU usage that I'm having a hard time accounting for). Not sure if others have seen this too.
Anyone know if this might cause a node/VM to become unresponsive? And therefore enter this state?

**Comment by jbergstroem** [comment]
I used B-series VM's for gitlab runners that did workloads I assumed were hand in glove for burstable volumes; 90% quiet then a few CI pipelines. The jobs failed in all kind of weird ways and the VM's quickly became unresponsive. Credits were always above 50% remaining but it was just unreliable. After switching to another VM type all issues went away.

Had a solr cluster with very low usage on a k8s setup with B nodes (uptime: 26 days) which also failed today. I'm just going to call it quits.

**Comment by seanknox** [comment]
> We are using a B-series (burstable) VM as a node, I wonder if it could be causing the issue?

This was likely a major factor; your workloads exhausted the node resources. We've also implemented untouchable reserves for Kubernetes components so workloads don't stomp over critical system components.
