### ISSUE TITLE
[Feature] Privileged containers on Windows AKS

### ISSUE THREAD

**Issue by keikhara** [Azure/AKS#1800]
Working with Cosine team to enable privileged containers on Windows AKS.

**Comment by zhiweiv** [comment]
@keikhara 
This is interesting, per https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20190103-windows-node-support.md

> **What will never work**
> Note that some features are plain unsupported while some will not work without underlying OS changes
> 
> Certain Pod functionality
> Privileged containers

Can you share some more details about this feature?

**Comment by immuzz** [comment]
@zhiweiv please look at the proposed Privileged Containers KEP for the details and feel free to leave you concerns in the comments in the KEP so we can look at it in SIG-Windows community.

https://docs.google.com/document/d/12EUtMdWFxhTCfFrqhlBGWV70MkZZPOgxw0X-LTR0VAo/edit#heading=h.kpsimyb2q1sg

**Comment by AbelHu** [comment]
Windows Host Process Containers is supported in AKS 1.23.x with Windows containerd package 1.6. It is available in all global regions and will be available in all sov clouds in next days.
