### ISSUE TITLE
Kubernetes resources view in Portal - private clusters issue

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/AKS#1801]
When I try to open portal resources view, for example `Namespaces (preview)` for my **private** cluster, I get error stating to check connectivity to:
`Target hostname: https://[redacted].portal.[redacted].privatelink.southeastasia.azmk8s.io`

For some strange reason this IP resolves to `10.200.0.102` what has nothing to do with my networks which are using completely different address space (and should not be registered in public DNS).

I went through all the resources and never see a mention of such a DNS name: `[redacted].portal` in private DNS zone: `[redacted].privatelink.southeastasia.azmk8s.io` or any additional private endpoint..

My understanding is that to get connectivity to this cluster I should create new private endpoint for my AKS cluster in a private network reachable via VPN, register this name in the DNS for VPN and this should work.

Which target sub-resource should I use during private endpoint creation? API Server uses `management`.

**Comment by jenetlan** [comment]
Hi! Unfortunately this feature is not yet working for private clusters :( We'll be updating the error message soon to make that restriction clear. We do plan to add in support for private clusters in the future.

**Comment by jenetlan** [comment]
Hi! We've added support for private clusters with the Kubernetes resources view so this should now be resolved. Keep in mind you will need to access the cluster via the private network (ex. from a VM in the same VNet) to access the resources. Let me know if you run into issues!
