### ISSUE TITLE
AKS without Azure LoadBalancer

### ISSUE THREAD

**Issue by kamilzzz** [Azure/AKS#1805]
Right now when creating new AKS cluster (either via ARM template or portal) the Azure Load Balancer is provisioned (and I'm sure it wasn't some time before).
I will be using Application Gateway Ingress Controller so I do not need additional Load Balancer.

Is it somehow configurable to NOT create Azure Load Balancer when deploying new AKS cluster (it's created in the separate resource group, the same where scale sets are located)?

That's how the ARM looks like now:
```
"apiVersion": "2020-04-01",
"type": "Microsoft.ContainerService/managedClusters",
"location": "[parameters('region')]",
"name": "[variables('clusterName')]",
"properties": {
    "kubernetesVersion": "[parameters('kubernetesVersion')]",
    "nodeResourceGroup": "[variables('aksInfraResourceGroupName')]",
    "dnsPrefix": "[variables('dnsPrefix')]",
    "enableRBAC": true,
    "agentPoolProfiles": [
        {
            "name": "default",
            "osDiskSizeGB": "[parameters('aksOsDiskSizeGB')]",
            "count": "[parameters('aksAgentCount')]",
            "vmSize": "[parameters('aksAgentVMSize')]",
            "osType": "[parameters('aksOsType')]",
            "storageProfile": "ManagedDisks",
            "vnetSubnetId": "[resourceId('Microsoft.Network/virtualNetworks/subnets', variables('vnetName'), 'default')]",
            "type": "VirtualMachineScaleSets",
            "mode": "System",
            "availabilityZones": [ "1", "2", "3" ]
        }
    ],
    "addonProfiles": {
        "omsagent": {
            "enabled": true,
            "config": {
                "logAnalyticsWorkspaceResourceID": "[resourceId('Microsoft.OperationalInsights/workspaces', variables('logAnalyticsName'))]"
            }
        }
    },
    "servicePrincipalProfile": {
        "clientId": "[parameters('servicePrincipalClientId')]",
        "Secret": "[parameters('servicePrincipalClientSecret')]"
    },
    "networkProfile": {
        "networkPlugin": "[parameters('networkPlugin')]",
        "serviceCidr": "[parameters('serviceCidr')]",
        "dnsServiceIP": "[parameters('dnsServiceIP')]",
        "dockerBridgeCidr": "[parameters('dockerBridgeCidr')]"
    }
}
```

`networkPlugin` is `azure` and `kubernetesVersion` is `1.17.7`

**Comment by TomGeske** [comment]
By default, AKS will provision a Standard SKU Load Balancer to be set up and used for egress. If you want to customize you can use outboundType: https://docs.microsoft.com/en-us/azure/aks/egress-outboundtype

**Comment by kamilzzz** [comment]
@TomGeske Thanks for response, that's clear.
I'm just wondering when this behavior was introduced because I had a cluster created like a month ago and I'm quite sure it didn't provision additional load balancer then :)

**Comment by TomGeske** [comment]
AFAIK it was included in 2020-04-01 API where we started defaulting VMSS and Standard LB: https://github.com/Azure/AKS/releases/tag/2020-06-01
