### ISSUE TITLE
AAD login stops working when upgraded to AAD V2

### ISSUE THREAD

**Issue by djj0809** [Azure/AKS#1806]
**What happened**:

We have several managed AKS clusters with legacy AAD integration, and as AKS managed AAD is now GA, I upgraded one of our clusters to AAD V2 according to: https://docs.microsoft.com/en-us/azure/aks/managed-aad#upgrading-to-aks-managed-azure-ad-integration

However, after upgrade, when I successfully logged in browser with device login code, kubectl command returned with error:

```
PS C:\Users\jiding> kubectl get pods
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code HCBTEXXXX to authenticate.
error: You must be logged in to the server (Unauthorized)
``` 

in the meantime, other clusters with AAD v1 still work well with AAD login.

Our cluster setting is:
- Managed Identity enabled
- RBAC enabled
- Cluster autoscaling enabled

And upgrade with command like this:
```az aks update -g myResourceGroup -n myManagedCluster --enable-aad --aad-admin-group-object-ids <id> --aad-tenant-id <id>```

**What you expected to happen**:

kubectl command should succeed to execute commands.

**How to reproduce it (as minimally and precisely as possible)**:

Create a new AKS cluster with command:

```
az aks create --name aadtest --resource-group aks-aad-test --aad-admin-group-object-ids XXX --aad-tenant-id XXX --enable-rbac --enable-aad --enable-managed-identity --kubernetes-version 1.17.7 --node-count 1 --node-vm-size Standard_DS2_v2
```

when created, 
```az aks get-credential -n aadtest -g aks-aad-test```

```kubectl get pods``` 

after logged in browser with device code, it says
```
PS C:\Users\jiding> kubectl get pods
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code GBWJPSXXX to authenticate.
error: You must be logged in to the server (Unauthorized)
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"5737fe2e0b8e92698351a853b0d07f9c39b96736", GitTreeState:"clean", BuildDate:"2020-06-24T19:54:11Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
1 node pool with 4 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by mac8005** [comment]
@djj0809 
Hi
We had similar Issues after upgrading from Legacy AAD Integration to AKS Managed AAD Integration. 
Seams that Azure AD Conditional Access Policies were blocking the user login.
At the Moment it's not possible to use the "Azure Kubernetes Service AAD Client" in CA Policies.

**Comment by adhodgson1** [comment]
Look at your Kubectl version, I have this working on Kubectl 1.16.6 but have seen similar issues for users who have Kubectl 1.15.x which have gone after they upgraded. I don't know which is the earliest Kubectl version to get this fix.

**Comment by TomGeske** [comment]
Make sure to upgrade kubectl at least to **1.18.1**.
`az aks install-cli`

**verify kubectl version**
`kubectl version --client`

**download credentials**
`az aks get-credentials --resource-group myResourceGroup --name myManagedCluster`

**Comment by djj0809** [comment]
@TomGeske @adhodgson1 Thanks, I tried and figured out that only 1.18.x fixes this issue.
