### ISSUE TITLE
[Bug] Network Policies worked on NPM v1.1.4 does not work as it is in NPM v1.1.5

### ISSUE THREAD

**Issue by dhananjaya94** [Azure/AKS#1807]
**What happened**:
https://github.com/Azure/azure-container-networking/issues/657

**What you expected to happen**:
Work the network polices as it was in v1.1.4 

**How to reproduce it (as minimally and precisely as possible)**:
https://github.com/Azure/azure-container-networking/issues/657

**Anything else we need to know?**:
In AKS release notes it only mentioned the NPM component version upgrade to v1.1.2 https://github.com/Azure/AKS/releases/tag/2020-05-25. No notes on later upgrades are found release notes. https://github.com/Azure/AKS/releases. But component upgrades have happened upto v1.1.5 which introduced a regression bug to AKS . 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"1da71a35d52fa82847fd61c3db20c4f95d283977", GitTreeState:"clean", BuildDate:"2020-07-15T21:59:26Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
This issue is reproducing in all the AKS clusters we are running at the moment with Azure NPM. 2 clusters with 5 worker nodes each and another 2 clusters with 3 worker nodes each.
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Go and Ballerina
- Others:
N/A

**Comment by dhananjaya-senanayake** [comment]
With Azure NPM v1.1.7 also the same issue occurs.

**Comment by danimal521** [comment]
@aanandr is this a known issue? Please address.

**Comment by phealy** [comment]
We are well past version 1.1.5 at this point in time; is this issue still occurring for you? [You can see the NPM releases here](https://github.com/Azure/azure-container-networking/releases/).
