### ISSUE TITLE
Scaling VMSS to 0 does not remove nodes from AKS in Kubernetes 1.16.13

### ISSUE THREAD

**Issue by brudnyhenry** [Azure/AKS#1808]
**What happened**:

When AKS is in version 1.16.13 and has spot instance pool, scaling spot VMSS to 0 does not remove spot node from Kubernetes.
Instead  the nodes are left in Ready state even though the underlying VM is not present anymore.

**What you expected to happen**:

When scaling VMSS to 0, the nodes in Kubernetes should be removed.
Problem does not exist in AKS with Kubernetes version 1.16.10

**How to reproduce it (as minimally and precisely as possible)**:

Create AKS cluster version 1.16.13 
Add spot instance nodepool. 
Scale Spot instance VMSS to 0
Spot instance nodes in AKS are not removed.

**Anything else we need to know?**:

I have the same setup with Kubernetes 1.16.10 and the problems does not exist there

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.13
- Size of cluster (how many worker nodes are in the cluster?) 0-4

**Comment by yangl900** [comment]
thanks for reporting @brudnyhenry ! This might be a regression in 1.16.13. Do you see the node left there forever or it gets deleted after 10/15min? It could be the VMSS cache not invalidated in cloud provider.

cc: @feiskyer in case there is a known issue

**Comment by brudnyhenry** [comment]
Hi, it stays there forever. VMSS is scaled down to 0, but when I issue `kubectl get nodes` I see the nodes in READY state

**Comment by palma21** [comment]
Just to clarify, did you use az aks scale -c 0 or did you use directly the vmss api/portal/cli?

**Comment by brudnyhenry** [comment]
Hi,
I use Scale schedule and set instance count to 0 for night.
The same schedule works perfectly fine in AKS with Kubernetes 1.16.10 and 1.15.12

**Comment by palma21** [comment]
Sorry to double click a bit more, but when you say scale schedule you mean you mean the VMSS API operation (in portal or CLI)?

**Comment by brudnyhenry** [comment]
Well actually none :) via terraform resource 
https://www.terraform.io/docs/providers/azurerm/r/monitor_autoscale_setting.html

**Comment by palma21** [comment]
That terraform call is for VMSS scale. Not AKS/Kubernetes scale. That is not supported. 
The right parameters for autoscaling an AKS cluster or nodepool would be
https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster_node_pool.html#enable_auto_scaling
