### ISSUE TITLE
Azure AAD integration v2 spams for authentication

### ISSUE THREAD

**Issue by audunsolemdal** [Azure/AKS#1809]
**What happened**:

Activated the AAD integration a couple of weeks ago on two clusters, AKS 1.18.4 and 1.17.7. Works fine, get asked for device code authorization every now and then.

Upgraded AKS from 1.18.4 to 1.18.6
Getting spammed for authentication every hour or so.
Slack thread reporting the same thing (no mention about AKS version):
https://kubernetes.slack.com/archives/C5HJXTT9Q/p1597665437430400

**What you expected to happen**:
Same behaviour as before upgrading version.

**How to reproduce it (as minimally and precisely as possible)**:
Azure AAD integration with AKS 1.18.6

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T19:08:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by TomGeske** [comment]
Sounds like your refresh token doesn't work. What is your config mode in .kube/config? 

cc: @weinong

**Comment by weinong** [comment]
do you happen to use helm v3.2? if so, that version is using a bugged client-go (v1.18.0). upgrade to v3.3 would resolve the issue

**Comment by audunsolemdal** [comment]
I am using helm 3.2. 

Having a hard time explaining so volatile behaviour. My colleague stated that he has had no issues, today I get no prompt, while last week I got about one each hour.

I'll try a helm upgrade.

**Comment by palma21** [comment]
There is some explanation here:

https://github.com/helm/helm/issues/8104
https://github.com/kubernetes/kubernetes/issues/89672#issuecomment-673644657

**Comment by audunsolemdal** [comment]
Thanks, I'll reopen if the issue starts reoccurring.
