### ISSUE TITLE
az aks create with invalid vm size fails validation but doesn't clean up

### ISSUE THREAD

**Issue by shahiddev** [Azure/AKS#181]
az cli version:
azure-cli (2.0.25)

acr (2.0.19)
acs (2.0.24)
advisor (0.1.1)
appservice (0.1.24)
backup (1.0.6)
batch (3.1.8)
batchai (0.1.4)
billing (0.1.7)
cdn (0.0.11)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.25)
cosmosdb (0.1.16)
dla (0.0.17)
dls (0.0.19)
eventgrid (0.1.8)
extension (0.0.7)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.13)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.15)
monitor (0.1.0)
network (2.0.21)
nspkg (3.0.1)
profile (2.0.17)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.21)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.19)
storage (2.0.23)
vm (2.0.24)

**>az aks create -n <name> -g <resourcegroup> -s BASIC_A0 -c 1**
_Deployment failed...'The provided value 'BASIC_A0' for the template parameter 'nodepool1VMSize' at line '1' and column '12863' is not valid._

Correcting the vm size subsequently fails:
**>az aks create -n <name> -g <resourcegroup> -s Standard_A0 -c 1**
_Operation failed with status: 'Bad Request'. Details: Changing property 'agentPoolProfile.vmSize' is not allowed._

This is because the generated resource group (MC_xx) and the container service entry are not removed. 

I would expect the validation to occur before creating resources or if they are created they be rolled back due to failure?

**Comment by irab** [comment]
Same for me.

**Comment by thomasyuan** [comment]
Same here.

**Comment by bramvdklinkenberg** [comment]
same here since yesterday
I had the vm size as a variable in my release pipeline and worked fine. 
I used Standard_D2S_V2 which is avaiable when checking with az vm list-sizes -l westeurope.

**Comment by seanknox** [comment]
Closing due inactivity. Feel free to re-open if still an issue.

**Comment by ramonduraes** [comment]
Operation failed with status: 'Bad Request'. Details: Changing property 'agentPoolProfile.vmSize' is not allowed.

>> az aks create --resource-group akstemp --name aks --node-count 1 --enable-addons monitoring --generate-ssh-keys --node-vm-size Standard_F8s_v2 --location eastus -k "1.11.5"

**Comment by crgarcia12** [comment]
I just got this error. Deleting AKS did not delete the VMScale Set, so i cannot create another one.
Subscription 37e917ff-feb6-438c-abd9-bd4899906ad4
