### ISSUE TITLE
Unable to pull images from ECR.

### ISSUE THREAD

**Issue by kiranbaddi** [Azure/AKS#1811]
I am trying to deploy an application by pulling images from aws ECR. I have created a registry credential secret after completing the docker login to aws ecr.

`kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson`

The secret gets created in the cluster. But I am not able to pull the image from ECR. There is absolutely no documentation that talks about using any other private registry not even dockerhub on AKS documentation. Or maybe it's just hidden from all search engines. Please help.

**Environment**:
- Kubernetes version v1.16.13"
- Size of cluster : 3

**Comment by yangl900** [comment]
hi @kiranbaddi usually if you describe pod, you can get some useful info as why it was not able to pull images. I also suggest try `docker login` with the image pull credentials you have, just to make sure the credential is correct.

**Comment by palma21** [comment]
And can you share what your deployment or pod yaml looks like with the ECR pull secret (regcred) in it?

**Comment by kiranbaddi** [comment]
I have just retested with the Registry credentials. Looks like the `regcred` secret  manifest was not correctly formatted. 
Thank for you all for the support. Apologize for over looking an obvious issue.
