### ISSUE TITLE
[Feature] Emit AKS event through Azure EventGrid 

### ISSUE THREAD

**Issue by jluk** [Azure/AKS#1812]
This issue covers the scenario of AKS integration with EventGrid as an event source. 

The 2 scenarios target an ability to trigger an action based on an AKS event stating there is a new K8s version upgrade available  or a new Node Image version upgrade available for a given cluster. 

As an example, if AKS released a new minor version and your dev/test cluster was on the latest minor/patch, an event will trigger and you can customize an action such as Slack notification or custom Function to trigger a new cluster deployment.

Additional events are under investigation and open to community feedback!

**Comment by tomkerkhove** [comment]
Those who want data-plane events can use Kubernetes Event Grid Bridge - http://k8s-event-grid-bridge.tomkerkhove.be/

**Comment by tomkerkhove** [comment]
This is now available in public preview - https://azure.microsoft.com/en-us/updates/public-preview-event-grid-integration-with-aks/

**Comment by EppO** [comment]
> This is now available in public preview - https://azure.microsoft.com/en-us/updates/public-preview-event-grid-integration-with-aks/

hey @tomkerkhove, just FYI your link is broken.

**Comment by asos-tonygorman** [comment]
Correct link appears to be here: https://azure.microsoft.com/en-us/updates/public-preview-event-grid-integration-with-aks-3/

**Comment by tomkerkhove** [comment]
Yes, sorry about that - The link seems to be pulled a few days later.

Get started: https://docs.microsoft.com/en-us/azure/aks/quickstart-event-grid
Supported events: https://docs.microsoft.com/en-us/azure/event-grid/event-schema-aks?tabs=event-grid-event-schema

**Comment by kaarthis** [comment]
We are currently evaluating newer events from AKS upgrade standpoint as we actively progress towards GA . Let us know if you have suggestions with use cases on these events ?

**Comment by Gordonby** [comment]
@kaarthis - If I create a cluster already on an older version (1.21.7), created the EventGrid link, how _soon/often_ should the **NewKubernetesVersionAvailable** event fire?

**Comment by kaarthis** [comment]
@EppO @jluk  pls see above and comment.

**Comment by kaarthis** [comment]
@Gordonby  : it will fire at the next release of our infrastructure, standard release cycle is weekly refer https://github.com/Azure/AKS/releases - however some exceptions (As in fire) for hotfix deployments (occasional) is possible.

**Comment by kaarthis** [comment]
The GA is available : https://docs.microsoft.com/en-US/Azure/event-grid/event-schema-aks?tabs=event-grid-event-schema

**Comment by kaarthis** [comment]
Closing this will open a new issue for More upgrade related events into Grid. (Enhancements)

**Comment by tomkerkhove** [comment]
> The GA is available : [docs.microsoft.com/en-US/Azure/event-grid/event-schema-aks?tabs=event-grid-event-schema](https://docs.microsoft.com/en-US/Azure/event-grid/event-schema-aks?tabs=event-grid-event-schema)

Awesome, thanks for sharing!
