### ISSUE TITLE
Application with identifier 'xxxxxxxx' was not found in the directory

### ISSUE THREAD

**Issue by rupeshtech** [Azure/AKS#1815]
I am trying to create user assigned managed identity  as described in this article for aks clusted

https://docs.microsoft.com/en-us/azure/aks/use-managed-identity under title **Bring your own control plane MI (Preview)**

while executing step

```
az feature register --name UserAssignedIdentityPreview --namespace Microsoft.ContainerService
```

getting error.  **Application with identifier xxxxxxxx was not found in the directory**

**What happened**:
![image](https://user-images.githubusercontent.com/24852402/90965888-a28f8f00-e4cc-11ea-93c7-66c20a75ff6c.png)

**Comment by yangl900** [comment]
@rupeshtech is the mentioned directory matching the subscription tenant ID? is the subscription new? And are you running the command as the error mentioned service principal?

I have not seen this error before, it looks like the service principal or subscription might be a new one.

**Comment by rupeshtech** [comment]
@yangl900 below is the answer
is the mentioned directory matching the subscription tenant ID? - Yes
is the subscription new? -- relatively new (1 month)
 And are you running the command as the error mentioned service principal? -- Yes

**Comment by TomGeske** [comment]
Can you double check if the issue still exists?

What do you get if you run:

`az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/UserAssignedIdentityPreview')].{Name:name,State:properties.state}"`
