### ISSUE TITLE
Issue in creating a networkpolicy with dns name

### ISSUE THREAD

**Issue by nidiculageorge** [Azure/AKS#1817]
Hi Team ,

I am trying to apply the following network policy

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-squidurl1
  namespace: autozoningns-dev-ibr62
spec:
  podSelector: {}
  egress:
  - to:
    - dnsName: tinyproxy.nonlivetinyproxy.svc.cluster.local
    ports:
    - port: 8080

When trying to apply the yaml i am getting the below error

error: error validating "AllowSquidService1.yml": error validating data: ValidationError(NetworkPolicy.spec.egress[0].to[0]): unknown field "dnsName" in io.k8s.api.n
etworking.v1.NetworkPolicyPeer; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by justinas-b** [comment]
I think it is a feature of Calico Enterprise only
