### ISSUE TITLE
[Agent Baker Request] Add nvme-cli to the base image

### ISSUE THREAD

**Issue by ams0** [Azure/AKS#1818]
**What happened**:

Trying to provision an NVMe disk from a node, I need the `nvme-cli` package to list and prepare the NVMe devices. See this [repo](https://github.com/ams0/aks-nvme-ssd-provisioner) for the script I want to use.

**What you expected to happen**:

Running `nvme list` returns a list of NVMe devices.

**How to reproduce it (as minimally and precisely as possible)**:

Create an AKS cluster, add a pool with NVMe disks (`Standard_L8s_v2` for example). Shell into the node and run

```
apt-get install nvme-cli
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by yangl900** [comment]
@ams0 you can make a PR to https://github.com/Azure/AgentBaker/blob/master/vhdbuilder/packer/install-dependencies.sh, it will be picked up in next VHD release.

@xuto2 please correct me if that's not the right place.

**Comment by ams0** [comment]
thanks @yangl900 , wasn't aware of that repo!
