### ISSUE TITLE
wrong dashboard version on new or upgraded 1.8.1 and 1.8.7 AKS-clusters

### ISSUE THREAD

**Issue by Zenlil** [Azure/AKS#182]
Region: West Europe

When creating a new **1.8.1**-cluster using "az aks create" the kubernetes-dashboard tries to load the "k8s-gcrio.azureedge.net/kubernetes-dashboard-amd64:v**1.7.1**"-image
A new **1.8.7**-cluster (or a 1.8.1 upgraded to a 1.8.7) tries to load the "k8s-gcrio.azureedge.net/kubernetes-dashboard-amd64:v**1.8.1**" images.
This results in a lot of restarts and adding new objects to the cluster results in crashes on the dashboard-pod.

**Comment by seanknox** [comment]
Believe this has been fixed; please reopen if still an issue.
