### ISSUE TITLE
Firewall rules for AKS private clusters

### ISSUE THREAD

**Issue by rlevchenko** [Azure/AKS#1820]
Any guidance for private clusters? I suppose we don't need half of the mentioned app.rules (https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic) since we don't use public API and etc. However, there might be some extra rules we should know about. I'd say the doc should provide info for all possible scenarios not just for the most used. For instance, the doc doesn't include required ports needed for communication between pools + master -> workers. my 2 cents. 

Thanks. (I was able to setup a pr. cluster and it works fine. just want to make sure I've not missed anything important)

**Comment by yangl900** [comment]
hi @rlevchenko , good feedback. Yes, indeed the rules regarding API server endpoints won't apply for private clusters. Any rules mentioning `APIServerIP` is not needed anymore since those traffic will go through private IP. There is no additional rules you need for private clusters though.

cc: @palma21

**Comment by palma21** [comment]
We add a note to the docs to clarify that all the public API server Endpoints, in essence this list, is not needed. The rest is the same.


Destination Endpoint | Protocol | Port | Use
-- | -- | -- | --
*:1194OrServiceTag - AzureCloud.<Region>:1194OrRegional CIDRs - RegionCIDRs:1194OrAPIServerIP:1194 (only known after cluster creation) | UDP | 1194 | For tunneled secure communication between the nodes and the control plane.
*:9000OrServiceTag - AzureCloud.<Region>:9000OrRegional CIDRs - RegionCIDRs:9000OrAPIServerIP:9000 (only known after cluster creation) | TCP | 9000 | For tunneled secure communication between the nodes and the control plane.
APIServerIP:443 (if running pods/deployments that access the API Server) | TCP | 443 | Required if running pods/deployments that access the API Server, those pods/deployments would use the API IP.

Destination FQDN | Port | Use
-- | -- | --
*.hcp.<location>.azmk8s.io | HTTPS:443 | Required for Node <-> API server communication. Replace <location> with the region where your AKS cluster is deployed.

**Comment by palma21** [comment]
Closing as per 
https://github.com/MicrosoftDocs/azure-docs/issues/61470
