### ISSUE TITLE
terminationGracePeriodSeconds default value is 45 second

### ISSUE THREAD

**Issue by ArenHarut** [Azure/AKS#1821]
We have noticed that after applying deployment kubernetes sets terminationGracePeriodSeconds default value to 45 seconds in one of the deployments, all deployments are applied without specifying terminationGracePeriodSeconds parameter and after roll out it should set default value to 30 seconds, but in only one it sets 45 seconds. Cluster is in Azure AKS version 1.15.11 enter image description here. Does any one experience or noticed such behavior. I have tried to search but couldn't find any article related to this.
![image](https://user-images.githubusercontent.com/60018498/91177423-c03f3d00-e6f4-11ea-989a-7a5b39cad9cc.png)

**Comment by ArenHarut** [comment]
https://github.com/Azure/aks-engine/issues/3735

**Comment by palma21** [comment]
We're not doing anything to the default, assuming you don't have any mutationg webhook or changed the yaml of that deployment?

If you want we can take a look at this specific cluster. Are you able to repro this in multiple clusters?
