### ISSUE TITLE
Ability to enable swap on specific node pools

### ISSUE THREAD

**Issue by arsnyder16** [Azure/AKS#1824]
By default kubernetes does not permit swap to be enabled on nodes. There is a large discussion here: https://github.com/kubernetes/kubernetes/issues/53533

Also some feedback here:
https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/36606361-enable-aks-node-memory-swapping
 
From the kuberentes discussion it appears there are workarounds currently. Hopefully it would eventually be supported fully. 
* start kubelet with --fail-swap-on=false
* add swap to your nodes
* containers which do not specify a memory requirement will then by default be able to use all of the machine memory, including swap.

Has this feature been discussed internally for AKS. It would be nice to be able to configure node pools that do support swap, or even more generically to give a way to bootstrap the node setup. 

Currently i am using a dedicated node pool to do machine learning/data analytics. Depending on the data size some of these algorithms can require a lot of memory temporarily. If swap was enabled on those nodes it would be possible to run multiple jobs per node and even require a much smaller VM. Currently its not cost effective to keep a very large vms running when some jobs don't require as much memory.

**Comment by palma21** [comment]
Will be solved by:
https://github.com/Azure/AKS/issues/323 which will allow you to set that param to false.

Closing this one. Let me know if you have any additional questions/comments.
