### ISSUE TITLE
How can I tune local disks mount options on windows nodes?

### ISSUE THREAD

**Issue by Win32Sector** [Azure/AKS#1826]
Hi All

Help me, please.
We have a Kubernetes cluster, where there are Linux nodes and Windows nodes. 
We need to deploy minio(S3 storage) in caching mode on Windows nodes, but it does not work there, 
since the option to mount atime or its analog in Windows must be enabled -
HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v NtfsDisableLastAccessUpdate

minio works well on my windows local machine, on my virtualbox windows virtual machine, but in Azure AKS - it doesn't.
I tried to change NtfsDisableLastAccessUpdate parameter and rebooted windows node, but the changed parameter doesn't help to run minio.

Maybe you can help me run kubernetes windows nodes with tuned mount parameters of local disks if it is possible?

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T19:08:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by andyzhangx** [comment]
hi @Win32Sector do you mean os disk or data disk mount options? current os disk mount options is ignored now, related code is here: https://github.com/kubernetes/utils/blob/5e75c0163111533bca81c92d71ee05d00ff07574/mount/mount_windows.go#L233-L267

**Comment by Win32Sector** [comment]
It was my error.
The working Dockerfile is 

```
FROM mcr.microsoft.com/windows/nanoserver:1809
USER ContainerAdministrator
RUN cmd.exe /k reg.exe add HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v NtfsDisableLastAccessUpdate /t REG_DWORD /d 0 /f
USER ContainerUser
SHELL [ "md", "C:\\app", "C:\\export", "C:\\cache"]
WORKDIR C:\\app
ADD minio.exe C:\\app
EXPOSE 9000
ENTRYPOINT  ["minio.exe"]
```

**Comment by andyzhangx** [comment]
thanks for the confirm
