### ISSUE TITLE
Cant upgrade AKS - pool using older version of Kubernetes

### ISSUE THREAD

**Issue by pofider** [Azure/AKS#1827]
**What happened**:
When I try to upgrade my AKS cluster through azure portal from the current 1.11.3 I get the following error:

> One or more node pools in the cluster are using an older version of Kubernetes. Upgrade those node pools to version 1.13.x or greater before upgrading cluster.

So I try to upgrade the node pool but get error:

> This node pool is using the latest version of Kubernetes supported by the cluster. To upgrade to a later version of Kubernetes, upgrade the cluster control plane first in the 'Upgrade' menu item

It looks I am in the circle.

**What you expected to happen**:

That I can upgrade.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): I use azure portal
- Size of cluster (how many worker nodes are in the cluster?) 1 node

**Comment by yangl900** [comment]
hi @pofider , that seems not expected. I'm not sure how your cluster get into this state, is your control plane on 1.11? it seems portal think it's on 1.13. Were you able to upgrade using Azure CLI? Please share the exact version of control plane and node pool, this might be a bug on portal.

**Comment by pofider** [comment]
@yangl900 Thank you for stepping in.

> Please share the exact version of control plane and node pool,

```
C:\work\pofider\kubernetes>az aks get-upgrades --resource-group jsreport --name jsreport --output table
Name     ResourceGroup    MasterVersion    Upgrades        
-------  ---------------  ---------------  ----------------
default  jsreport         1.11.3           1.15.11, 1.15.12
```

```
C:\work\pofider\kubernetes>az aks nodepool show --cluster-name jsreport --name agentpool --resource-group jsreport
{
  "agentPoolType": "AvailabilitySet",
  "availabilityZones": null,
  "count": 1,
  "enableAutoScaling": null,
  "enableNodePublicIp": null,
  "id": "/subscriptions/xxx/resourcegroups/jsreport/providers/Microsoft.ContainerService/managedClusters/jsreport/agentPools/agentpool",
  "maxCount": null,
  "maxPods": 110,
  "minCount": null,
  "mode": "User",
  "name": "agentpool",
  "nodeLabels": null,
  "nodeTaints": null,
  "orchestratorVersion": "1.11.3",
  "osDiskSizeGb": null,
  "osType": "Linux",
  "provisioningState": "Succeeded",
  "resourceGroup": "jsreport",
  "scaleSetEvictionPolicy": null,
  "scaleSetPriority": null,
  "spotMaxPrice": null,
  "tags": null,
  "type": "Microsoft.ContainerService/managedClusters/agentPools",
  "vmSize": "Standard_B2s",
  "vnetSubnetId": null
}
```

>  Were you able to upgrade using Azure CLI?

I see in the [documentation](https://docs.microsoft.com/en-us/azure/aks/node-image-upgrade) that I can't skip the minor version when upgrading. So I was afraid to try the update as its a production server. Should it be ok to hit cli update from 1.11.3 to 1.15.12 ?

**Comment by DreamRivulet** [comment]
I think the issue should be that if  we upgrade the cluster on the azure portal, it will only upgrade the control plane to supported version, however, as we known, worker nodes are not allowed more than two minor version behind the master, this may be why it complains that:
One or more node pools in the cluster are using an older version of Kubernetes. Upgrade those node pools to version 1.13.x or greater before upgrading cluster.

**Comment by andyzhangx** [comment]
so azure cli works, right?

**Comment by pofider** [comment]
Yes, the cli based worked. I took a risk and triggered the upgrade despite the warnings in the documentation to don't upgrade over two minor versions.

This is now fixed for me, although the problem is probably still there.
Thank you for your comments.

**Comment by palma21** [comment]
Thanks for the report @pofider I'm reopening for Portal investigation if that's ok with you. Let me know if you'd rather me creating a separate issue so you don't get any emails :)

**Comment by syska** [comment]
No sure if this have been fixes or it's just macically working again.
![image](https://user-images.githubusercontent.com/317770/96351911-3e99d900-10bf-11eb-8fe0-3f3667e18952.png)

I raised the issue with AzureSupport on twitter: https://twitter.com/mikaelsyska/status/1316401133053710336

But I will try the upgrade now ...

**Comment by jenetlan** [comment]
Hi! You beat me to it - we did in fact roll out a fix but I was waiting until we verified that it was completely deployed before replying here :) This should now be working as expected, although if you encounter any other errors with this scenario please do let me know. Thank you!

**Comment by IanKnighton** [comment]
Sorry to re-open this, but I seem to be stuck in the same state and I can't get out of it. Not sure if I missed a fix somewhere in this issue or not. 

![Screen Shot 2020-11-09 at 7 49 16 PM](https://user-images.githubusercontent.com/46321154/98621613-ea040b00-22c4-11eb-8049-3677ba091874.png)

I'm having an issue with metrics-server and, from what I've seen so far, I need to start by moving my cluster's off of version 1.16.9 and I can't do that until I can update my nodes.
