### ISSUE TITLE
AZ AKS CREATE not working due to osdiskencryption requirements on v2.11.0 and greater

### ISSUE THREAD

**Issue by LucasCosas** [Azure/AKS#1828]
[

**What happened**:

When creating a cluster using CLI AZ AKS CREATE doesn't work properly giving me an error:

Property id '' at path 'properties.diskEncryptionSetID' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.

The same script worked fine yesterday, and it's a standard script from the azure docs:
https://docs.microsoft.com/en-us/azure/aks/private-clusters#create-a-private-aks-cluster

Script I used:

az aks create \
    --resource-group RG-AML-PRIVATE \
    --name aks-comand \
    --load-balancer-sku standard \
    --enable-private-cluster \
    --network-plugin kubenet \
	--vnet-subnet-id "/subscriptions/884aa121-fb71-4ae3-9c23-031000b6036e/resourceGroups/RG-AML-PRIVATE/providers/Microsoft.Network/virtualNetworks/vnetaks/subnets/default" \
    --docker-bridge-address 172.17.0.1/16 \
    --dns-service-ip 10.1.0.10 \
    --service-cidr 10.1.0.0/24
	

**What you expected to happen**:
Create an AKS cluster as it did one day ago.

**How to reproduce it (as minimally and precisely as possible)**:
Script
az aks create \
    --resource-group RG-AML-PRIVATE \
    --name aks-comand \
    --load-balancer-sku standard \
    --enable-private-cluster \
    --network-plugin kubenet \
	--vnet-subnet-id "/subscriptions/884aa121-fb71-4ae3-9c23-031000b6036e/resourceGroups/RG-AML-PRIVATE/providers/Microsoft.Network/virtualNetworks/vnetaks/subnets/default" \
    --docker-bridge-address 172.17.0.1/16 \
    --dns-service-ip 10.1.0.10 \
    --service-cidr 10.1.0.0/24
	

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by marwanad** [comment]
Thanks for reporting. This is a know issue with CLI and the work around is to use CLI-Extensions for now.

https://github.com/Azure/azure-cli/issues/14915

```
az extension add --name aks-preview
```

**Comment by yangl900** [comment]
Sorry for the inconvenience. We are preparing a CLI hotfix, will keep this updated.

**Comment by andyzhangx** [comment]
already fixed by latest version: https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.11.1
