### ISSUE TITLE
[Feature] Use existing Private DNS zone for Private AKS cluster

### ISSUE THREAD

**Issue by yaoshipu** [Azure/AKS#1829]
Is there any way to use the existing Private DNS zone for the Private AKS cluster?

**Comment by TomGeske** [comment]
It isn't possible today, but we are currently looking into enabling bring your DNS zone for private cluster. We keep you posted.

**Comment by MiyKh** [comment]
Do you have any update on this topic? 
The lack of this feature prevent us from using private cluster at entreprise scale

**Comment by EppO** [comment]
this feature is tracked here: https://github.com/Azure/AKS/issues/2015
looking at the [roadmap](https://github.com/Azure/AKS/projects/1#card-50900163), it was just set in public preview recently, waiting for the docs to get updated to know how to use it.

**Comment by feiskyer** [comment]
@EppO please try

```az aks create -n <private-cluster-name> -g <private-cluster-resource-group> --load-balancer-sku standard --enable-private-cluster --private-dns-zone [none|system|custom private dns zone resource ID]
```

**Comment by feiskyer** [comment]
close since it is already supported.
