### ISSUE TITLE
Ingress ADDRESS is empty

### ISSUE THREAD

**Issue by neildonkin** [Azure/AKS#183]
I have created an ingress controller using this Helm command:

`helm install stable/nginx-ingress`

The ingress controller LoadBalancer service is created successfully with a public IP:

![image](https://user-images.githubusercontent.com/1763776/36145492-6e69b5e2-10a9-11e8-86e4-08b09d711d80.png)

However, when I create an Ingress the ADDRESS column is empty.

![image](https://user-images.githubusercontent.com/1763776/36145550-9e6fd618-10a9-11e8-842e-d778a69ab9f1.png)

![image](https://user-images.githubusercontent.com/1763776/36145410-319a9578-10a9-11e8-9019-75f3c4519898.png)

**Comment by slack** [comment]
Ingress controller should still work, but if you'd like to see the service address for the ingress controller, make sure you tell nginx-ingress to publish the service address:
```
helm upgrade jolly-puma stable/nginx-ingress --set controller.publishService.enabled=true
```

**Comment by silgon** [comment]
I did:

    helm install stable/nginx-ingress --set controller.publishService.enabled=true

Because I couldn't with upgrade. However I still don't see the port. I'm also new with `helm`, so maybe I'm doing something wrong. In my case, I'm trying to deploy [this simple example](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/complete-example).

**Comment by dave-hillier** [comment]
I have this same problem, except this is the 3rd ingress I'm creating. 

NAME                              HOSTS                                                                   ADDRESS        PORTS     AGE
release3                 xxxxxx.westeurope.aksapp.io                          80        1h
release2                 xxxxxx.westeurope.aksapp.io   51.144.73.49   80        16d
release1                 xxxxxx.westeurope.aksapp.io   51.144.73.49   80        19d
