### ISSUE TITLE
Does AKS perform Log Rotation for Windows Containers?

### ISSUE THREAD

**Issue by Julian-Schaefer** [Azure/AKS#1830]
As mentioned in https://github.com/Azure/AKS/issues/823, AKS does configure Log Rotation for **Linux** VMs.

However, does it also configure Log Rotation for **Windows** Containers/Nodes? It seems to me like it doesn't.
Does anybody know how to check if AKS configures Log Rotation for Windows Nodes?

Kubernetes and Docker itself don't configure Log Rotation in any way, as indicated by the docs.

**Comment by keikhara** [comment]
Docker has log rotation for their logs. You can check this here: https://docs.docker.com/config/containers/logging/configure/ 

Also for Kubernetes, you will need to do set using following tool like NSSM: 
https://nssm.cc/usage#File%20rotation%20tab

**Comment by AbelHu** [comment]
For docker: https://github.com/Azure/AgentBaker/blob/master/staging/cse/windows/configfunc.ps1#L93-L97
```
    $dockerConfig = Get-Content $dockerConfigPath | ConvertFrom-Json
    $dockerConfig | Add-Member -Name "log-driver" -Value "json-file" -MemberType NoteProperty
    $logOpts = @{ "max-size" = "50m"; "max-file" = "5" }
    $dockerConfig | Add-Member -Name "log-opts" -Value $logOpts -MemberType NoteProperty
    $dockerConfig = $dockerConfig | ConvertTo-Json -Depth 10
```

For containerd: https://github.com/Azure/AgentBaker/blob/master/staging/cse/windows/containerdfunc.ps1#L31-L34
```
  & "$KubeDir\nssm.exe" set containerd AppRotateFiles 1 | RemoveNulls
  & "$KubeDir\nssm.exe" set containerd AppRotateOnline 1 | RemoveNulls
  & "$KubeDir\nssm.exe" set containerd AppRotateSeconds 86400 | RemoveNulls
  & "$KubeDir\nssm.exe" set containerd AppRotateBytes 10485760 | RemoveNulls
```
