### ISSUE TITLE
Prometheus Histogram +Inf bucket is getting dropped (is in /metrics endpoint but not in Log Analytics)

### ISSUE THREAD

**Issue by dave-read** [Azure/AKS#1831]
**What happened**:
I've enabled Prometheus metrics scrape for a Pod and have implemented a custom prometheus.HistogramVec in golang client in the Pod
```			
requestDurations = prometheus.NewHistogramVec(prometheus.HistogramOpts{
				Name:    "request_duration_ms",
				Help:    "Time (in ms) spent serving HTTP requests.",
				Buckets: []float64{25, 50, 75, 100, 125, 150, 200, 225, 250},
			}, []string{"resource", "size"})
			prometheus.MustRegister(requestDurations)
```
When creating requests where the value is greater than the last bucket e.g. 300 I see the correct total count, sum, and the count in the "+Inf" bucket on the /metrics endpoint:

request_duration_ms_bucket{resource="getBytes",size="5",le="25"} 0
request_duration_ms_bucket{resource="getBytes",size="5",le="50"} 0
request_duration_ms_bucket{resource="getBytes",size="5",le="75"} 0
request_duration_ms_bucket{resource="getBytes",size="5",le="100"} 0
request_duration_ms_bucket{resource="getBytes",size="5",le="125"} 0
request_duration_ms_bucket{resource="getBytes",size="5",le="150"} 0
request_duration_ms_bucket{resource="getBytes",size="5",le="200"} 0
request_duration_ms_bucket{resource="getBytes",size="5",le="225"} 0
request_duration_ms_bucket{resource="getBytes",size="5",le="250"} 0
request_duration_ms_bucket{resource="getBytes",size="5",le="+Inf"} 5
request_duration_ms_sum{resource="getBytes",size="5"} 1500
request_duration_ms_count{resource="getBytes",size="5"} 5

However Log Analytics does not include a row with a "le" tag for "+Inf".  So the count and sum records include the values, but the values are not reflected in any bucket.
```
InsightsMetrics 
| where Namespace == "prometheus"
| where Name == "request_duration_ms"
| extend TagProperties = parsejson(Tags)
| extend Namespace = TagProperties.namespace
| extend PodInstance = tostring(TagProperties.pod_name)
| extend Resource = tostring(TagProperties.resource)
| extend Bucket = tostring(TagProperties.le)
| extend Size = toint(TagProperties.size)
| where Size == 5
| distinct Bucket,Size,Val
```
Generates result:
```
Bucket | Size | Val
-- | -- | --
250 | 5 | 0
225 | 5 | 0
200 | 5 | 0
150 | 5 | 0
125 | 5 | 0
100 | 5 | 0
75 | 5 | 0
50 | 5 | 0
25 | 5 | 0
```

**What you expected to happen**:
The values associated with the automatically provisioned "**+Inf**" bucket should be present in Log Analytics

**How to reproduce it (as minimally and precisely as possible)**:
Create a histogram and generate values larger than the largest explicitly defined bucket.  In this repro case creating 5 requests with value of 300.

**Anything else we need to know?**:
It's possible to work around this by creating an explicit max value as an additional bucket, but that shouldn't be needed as Prometheus and the clients provision and populate the "**+Inf**" bucket.  See:
https://github.com/prometheus/client_golang/blob/master/prometheus/histogram.go#L118
```
	// Buckets defines the buckets into which observations are counted. Each
	// element in the slice is the upper inclusive bound of a bucket. The
	// values must be sorted in strictly increasing order. There is no need
	// to add a highest bucket with +Inf bound, it will be added
	// implicitly. The default value is DefBuckets.
	Buckets []float64
```
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:5
8:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"89d8075525967c7a619641fabcb267358d28bf08", GitTreeState:"clean", BuildDate:"2020-06-23T02:
52:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (how many worker nodes are in the cluster?)
2 nodes in System node pool.  1 to 3 nodes in App node pool
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
REST API implemented as golang server with Gorilla Mux.  Server. 
- Others:
Note: this does not seem to be related to load/stress.  It reproduce with curl client with a handful of requests.

**Comment by vishiy** [comment]
@dave-read - We do not filter on the dimensions. We just dont allow +-Inf as metric values as our store does not support them. Are you still seeing this issue ?

**Comment by miwithro** [comment]
@dave-read are you good now?
