### ISSUE TITLE
New Pods stuck in pending state on a particular node

### ISSUE THREAD

**Issue by skynetrulz** [Azure/AKS#1832]
**What happened**: New Pods stuck in pending state on a particular node

**What you expected to happen**: New Pod should be deployed successfully as the status of the node is showing as ready and existing pods are running on the node.

**How to reproduce it (as minimally and precisely as possible)**: Deploy a DS, the pod which gets assigned to a particular node goes into pending state and no further events.

**Anything else we need to know?**:

From the kubelet logs, found this ( not sure if this is the reason for pods to be on pending state

Aug 27 06:21:21 node-alpha kubelet[31421]: E0827 06:21:21.442258   31421 azure_dd.go:157] Failed to get instance type from Azure cloud provider, nodeName: node-alpha
Aug 27 06:21:31 node-alpha kubelet[31421]: E0827 06:21:31.471941   31421 azure_dd.go:157] Failed to get instance type from Azure cloud provider, nodeName: node-alpha
Aug 27 06:21:41 node-alpha kubelet[31421]: E0827 06:21:41.495055   31421 azure_dd.go:157] Failed to get instance type from Azure cloud provider, nodeName: node-alpha

Aug 27 06:21:20 node-alpha kubelet[31421]: I0827 06:21:20.414920   31421 cloud_request_manager.go:115] Node addresses from cloud provider for node "node-alpha" not collected: Get http://169.254.169.254/metadata/instance?api-version=2019-03-11&format=json: dial tcp 169.254.169.254:80: i/o timeout
Aug 27 06:21:30 node-alpha kubelet[31421]: I0827 06:21:30.419060   31421 cloud_request_manager.go:115] Node addresses from cloud provider for node "node-alpha" not collected: failure of getting instance metadata with response "410 Gone"
Aug 27 06:21:40 node-alpha kubelet[31421]: I0827 06:21:40.423163   31421 cloud_request_manager.go:115] Node addresses from cloud provider for node "node-alpha" not collected: failure of getting instance metadata with response "410 Gone"

**Environment**: AKS 1.17.9
- Kubernetes version (use `kubectl version`): 1.17.9
- Size of cluster (how many worker nodes are in the cluster?) 30
- General description of workloads in the cluster - Fluentd

**Comment by skynetrulz** [comment]
Any updates?

**Comment by Habulinec** [comment]
Same issue here. Already created a customer message, if somebody's interested: 120090424001884.

**Comment by miwithro** [comment]
@skynetrulz      Is this still an issue?

**Comment by justindavies** [comment]
As this hasn’t been updated for a long time I’m closing this issue. Please reopen if this is still occurring
