### ISSUE TITLE
Allow exception for CriticalAddonsOnly taint on system nodepools (or all)

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#1833]
Follow up for #1484. To unblock automation like terraform to tag the first (and system) nodepool as well as allow for taints on all nodepools, AKS will always accept CriticalAddonsOnly

**Comment by deepakkhetwal** [comment]
@palma21  Are we saying, Is it good to go applying - CriticalAddonsOnly taint, without any issues on system node pool?

**Comment by palma21** [comment]
This is the ticket to support it. Right now we block it if the taints are applied to all pools. We'll make an exception for this one so you can apply it to all pools (or just the default one)

**Comment by deepakkhetwal** [comment]
> This is the ticket to support it. Right now we block it if the taints are applied to all pools. We'll make an exception for this one so you can apply it to all pools (or just the default one)

Thank you @palma21 , Is there any ETA, when this would be resolved. Appreciate if this could be resolve sooner.
