### ISSUE TITLE
The "default" storage class sometimes takes some time to be created

### ISSUE THREAD

**Issue by sebgl** [Azure/AKS#1834]
**What happened**: Once in a while, when creating an AKS cluster, the `default` storage class is not available out of the box. It eventually gets created after a while (we observed ~5min). It makes cluster creation automation that relies on it slightly harder to setup, since we need to retry getting it until it finally appears.

You may ask: why do you need to retrieve this storage class in the first place? Because we want to change its `volumeBindingMode` to `WaitForFirstConsumer`. By the way since we cannot edit the default storage class we have to duplicate it, but [that's a different issue](https://github.com/Azure/AKS/issues/1075).

**What you expected to happen**: I would expect the default storage class to be there as soon as I can access the cluster. Which is what seems to happen on other major cloud providers.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a cluster.
2. List the available storage classes: `default` might not be listed yet.

This does not happen all the time, in many cases the storage class appears.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `default` (as of September 1, 2020)
- Size of cluster (how many worker nodes are in the cluster?): 3 nodes

**Comment by andyzhangx** [comment]
FYI. The fix is already rolling out in next week's release, would be fixed on all regions in around 9/20

**Comment by andyzhangx** [comment]
close this issue now since the fix should be ready
