### ISSUE TITLE
Failure of Azure Policy/Gatekeeper leads to problems with the control plane

### ISSUE THREAD

**Issue by AljoschaP** [Azure/AKS#1837]
**What happened**:
A failure of the Azure Policy/Gatekeeper webhook leads to problems with the control plane of k8s. In a complex scenario, e.g. with components who depend on the API-Server, this can cause problems with the running applications inside the cluster and impedes the control of the cluster.

**What you expected to happen**:
A failure of gatekeeper doesn't have an impact on the control plane. 

**How to reproduce it (as minimally and precisely as possible)**:

- Start a cluster
- Activate Azure Policy
- Stop/Delay the gatekeeper webhook (https://github.com/open-policy-agent/gatekeeper#admission-webhook-fail-open-status)
- Try to connect, e.g. with k9s (kubectl works sometimes)
- Optional : Try to use a component which depends on the control plane (e.g. PostgreSQL with Patroni) 

**Anything else we need to know?**:

{"log":"W0903 15:00:46.212663       1 dispatcher.go:128] Failed calling webhook, failing open validation.gatekeeper.sh: failed calling webhook \"validation.gatekeeper.sh\": Post https://gatekeeper-webhook-service.gatekeeper-system.svc:443/v1/admit?timeout=5s: context deadline exceeded\n","stream":"stderr","pod":"kube-apiserver-6dbbcd8c94-qvmqx"}

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.7
- Size of cluster (how many worker nodes are in the cluster?): 22
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): -
- Others: -

**Comment by jluk** [comment]
@AljoschaP can you clarify 2 things here?

1. What did you run when you "Stop/Delay the gatekeeper webhook"?
1. What signal did you find that the control plane is no longer working? The error returned shows the output of the webhook which is acting by design to fail open, but I don't see the issues wrt the control plane not working? Can you confirm kubectl get pods continues to function instead of validating other services are running? You could also provide the AKS cluster output from az aks show to help debug. This will at least validate the control plane is running / healthy.

**Comment by AljoschaP** [comment]
Hey @jluk,

I try :-):

1. It was a behavior we saw when the latency of the network was increased. We didn't run a specific command or tool but maybe you have an idea how to delay/disable the webhook.

2. We couldn't connect to the cluster using k9s. kubectl worked but with high latency. We had a PostgreSQL database with patroni deployed which uses endpoints for leader election. We saw almost the same behavior as [https://github.com/zalando/postgres-operator/issues/872](Link). Restart of tunnelfront couldn't fix it but disabling Azure Policy could.

I hope this helps to better understand the situation. Unfortunately, we have only a few logs of the k8s components but if you need more specific logs I can try to provide them.

Thank you :-)

**Comment by jluk** [comment]
Thanks for the info @AljoschaP do you have an open support ticket number you could share? If not do you mind opening one and sharing the number, I think we're going to need to take a look at your cluster to see what's happening.
