### ISSUE TITLE
az aks update attach-acr command failing with owner rbac requirement

### ISSUE THREAD

**Issue by iamsoorya** [Azure/AKS#1838]
We are trying to automate the end to end AKS deployment. However, below command requires 

az aks update --resource-group rg--prod-1 --name aks-grod-1 --attach-acr /subscriptions/9-6af2/resourceGroups/rg-cprod/providers/Microsoft.ContainerRegistry/registries/azurecr

2020-09-04T09:56:59.4720785Z Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for ACR. Are you an Owner on this subscription?
2020-09-04T09:57:17.6368484Z ##[error]Script failed with exit code: 1
2020-09-04T09:57:17.6471683Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
2020-09-04T09:57:17.9940468Z ##[section]Finishing: Azure CLI - ACR Update

Is this a requirement that subscription level Owner access is reuired for this. In such case we will not put this step in the azure devops pipline as service principle of the pipeline uses only Contributor access. Could you please confirm.  Resource level Owner access may be okay for us. But subscription wide owner access would not be approved by security team for this.

**Comment by TomGeske** [comment]
This error message is misleading. You need User [Access Administrator Permissions](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#user-access-administrator) on resource scope (in this example ACR scope)

@norshtein: can you adjust the error message?

**Comment by iamsoorya** [comment]
Thanks for your Reply. 
1. User Access Administration RBAC at ACR level.
2. Contributor RBAC at sub level.

We do not want to provide Contributor RBAC at the sub level. Would you be able to suggest the correct alternative.

If you are able to provide the exact roles required to make it work, would be very nice.

Even if it custom role, we can create them.
