### ISSUE TITLE
What is the level of Managed Service in your target Architecture? What is the roadmap for GA?

### ISSUE THREAD

**Issue by albuch** [Azure/AKS#184]
In the current preview, the management aspect when it comes to the underlying VMs stops at the automatic update level of the OS. Kernel Updates (e.g. restarts) etc. need to be managed by your subscribers.
What is managed service level that AKS will provide once it reaches GA? Will AKS provide self-healing capabilities on the VM level, e.g. replacing unresponsive nodes?
Is there any roadmap at all that you can share? The official roadmap at https://azure.microsoft.com/en-us/roadmap/azure-container-service-aks-on-azure-stack/ is obviously not helping.

**Comment by dstrebel** [comment]
Probably best to keep an eye on the AKS FAQ, as this will be updated with information.
https://docs.microsoft.com/en-us/azure/aks/faq

**Comment by seanmck** [comment]
Yes, please follow the FAQ. We will also be adding a doc article specifically focused on what is meant by "managed" in the AKS context. Finally, if there are specific requests you have, please add them to our feedback forum so we can prioritize:

https://aka.ms/aks/feedback
