### ISSUE TITLE
Create service failed with error: failed to allocate a serviceIP: range is full

### ISSUE THREAD

**Issue by irvinwang** [Azure/AKS#1843]
**What happened**:
We have an existing AKS cluster. When we run helm install to install more pod/service, following error is reported
<pre>
Error: Internal error occurred: failed to allocate a serviceIP: range is full
</pre>

**What you expected to happen**:
We suspect this error means service CIDR is full. Because the service CIDR only includes 32 IP.
- Is it possible to change the service CIDR for existing cluster? What's the procedure to change this?

- Is there any other way to workaround this issue without recreate the cluster?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
<pre>
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"4a1514f7dbb15bf5047b349d2599d23756ed75b8", GitTreeState:"clean", BuildDate:"2020-07-15T03:33:19Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
</pre>

- Size of cluster (how many worker nodes are in the cluster?)
  - 2 nodes 

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
  - asp.net core, java app

- Others:

**Comment by palma21** [comment]
Unfortunately no, the service range is a fundamental cluster bootstrap piece so you'll need to add an additional cluster in this case
