### ISSUE TITLE
Master(s) and state is not de-provisioned when AKS resource is deleted

### ISSUE THREAD

**Issue by FrodeHus** [Azure/AKS#185]
When running `az aks delete -n <name> -g <group>` the nodes are removed as expected, the resource group is deleted and everything looks like its gone.
Running `kubectl get nodes` yields result of `No resources found.` (which is kind of unexpected as if the cluster was gone, the master shouldn't answer - I expected it to fail).

Then, when I re-created my AKS cluster using the same name and same resource group name, the old state re-appeared when the cluster was back up and running. Old deployments etc showed up and started creating pods on the new nodes.

Deleted the cluster again and when I run `kubectl cluster-info` using the old context of the (supposedly) deleted cluster, I get the unexpected result of:
```
Kubernetes master is running at https://<name>.hcp.westeurope.azmk8s.io:443
Heapster is running at https://<name>.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/kube-system/services/heapster/proxy
KubeDNS is running at https://<name>.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
kubernetes-dashboard is running at https://<name>.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy
```

Is this by design so that you can recover a deleted cluster or a bug?

**Comment by slack** [comment]
Sounds like a bug. We should have deleted the master components after the node resource group was removed. Could you send the subscription and resource group name to jason.hansen@microsoft.com?

**Comment by seanknox** [comment]
Closing due to age; please reopen if still an issue.
