### ISSUE TITLE
tunnelfront logs activity very high

### ISSUE THREAD

**Issue by eligne-pro** [Azure/AKS#1856]
**What happened**: connecting the logs of an AKS into logz.io through fluentd, half of the total log amount is generated by
tunnelfront messages, in info modes, such as:
[ Mon Sep 14 15:14:58 UTC 2020 ] INF: Ssh to tunnelEnd is connected with pid: 25110
Log monitoring is billed based on volume, so having such an heavy traffic costs us twice the necessary price for effective log monitoring.

**What you expected to happen**: I would expect to find a way to decrease the log verbosity of the tunnelfront logger.

**How to reproduce it (as minimally and precisely as possible)**:
Activate log monitoring in Azure for your AKS and filter on messages coming from tunnelfront. You have multiple per minute, all having an INF: level indication;

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"f862ce9a809b9832be36717bfc4efae470f59fbf", GitTreeState:"clean", BuildDate:"2020-08-24T18:41:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)  1 node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) HTTP microservices
- Others:

**Comment by palma21** [comment]
AKS uses this logs to maintain the health of the system or in this case a managed component, does logz.io not allow any sort of filtering or exclusion? Eg. Azure Monitor allows you to not pull logs from kube-system for example.
