### ISSUE TITLE
Support for FeatureFlag to enable OpenID Connect via K8s API

### ISSUE THREAD

**Issue by ekarlso** [Azure/AKS#1857]
**What happened**:
FeatureFlag support request

**What you expected to happen**:
Be able to use k8s api for oidc with in-cluster service accounts 

**How to reproduce it (as minimally and precisely as possible)**:
https://banzaicloud.com/blog/kubernetes-oidc/

**Anything else we need to know?**:
N/A

**Comment by ekarlso** [comment]
Any news on this?

**Comment by TomGeske** [comment]
+@weinong, @miwithro to hear your thoughts.

**Comment by weinong** [comment]
@ekarlso can you elaborate on how you would want to use this feature please?

**Comment by ekarlso** [comment]
Yes if you want to use svc acct tokens to and oidc to verify the tokens for some services it is nice vs having to make Tokenreviewer

**Comment by miwithro** [comment]
@ekarlso this is shipping as part of Azure AD Workload Identity which is Private preview right now, and we will be moving to Public Preview next year.

**Comment by miwithro** [comment]
Dup of #1480 closing.
