### ISSUE TITLE
OutBoundNAT ExceptionList is only populated with the first entry from the list of Address Spaces of the VNET of the cluster

### ISSUE THREAD

**Issue by nboeckmann** [Azure/AKS#1859]
----
I have first logged it with aks-engine and they have already accepted it as a bug - but I'm on AKS, therefor I'm posting it here again (sorry about that!). Here's the reference to my original bug: https://github.com/Azure/aks-engine/issues/3789
----

In situations where there are multiple address ranges defined for a VNET there's only the first CIDR taken into the OutBoundNAT exclusion list on Windows Nodes preventing the network communication with services that are in network ranges that are outside of the first CIDR exposed in pods running on the windows node pool.

Workaround for two CIDR
Have the CIDR that is not used as the node pool range as the first entry as the node pool range is always added as an exclusion

Steps To Reproduce

-     Create a VNET with at least two CIDRs
-     Provision the AKS into the first CIDR with a windows node pool
-     Deploy a pod hosting a website into the windows node pool
-     Provision an Application Gateway into the 2nd range
-     The Application Gateway is not able to reach services (i.e. a website) that is exposed from the windows pod

Expected behavior

-     The Application Gateway is able to reach the service exposed by the windows pod.
-     All CIDRs that are defined in the VNET that the AKS cluster is bound to are added to the ExceptionList of the OutBoundNAT on 

Windows nodes

AKS Engine version
v0.47.0-aks-gomod-a8-aks

Kubernetes version
1.18.6

Additional context
I believe that this assumption that is stated in the code is wrong and therefor it doesn't behave correct.
![grafik](https://user-images.githubusercontent.com/22768290/93328691-59590380-f81c-11ea-88ab-fdf53b9c3ef0.png)
I can unfortunately not find that any longer (I detected the issue a while ago and still had the creation of the issue pending)

**Comment by nboeckmann** [comment]
Hi,

this is a significant issue for me and is preventing me from upgrading my AKS culusters to the latest version. Can at least someone take a look at it and give an ETA on if/when this will be fixed?

Nils

**Comment by nboeckmann** [comment]
Hi,

ping...

Nils

**Comment by nboeckmann** [comment]
Hi,

this is still an issue for me.

Nils

**Comment by palma21** [comment]
Hi @nboeckmann sorry the delay. Please do open a support ticket for any urgent matters.

This is actually fixed in AKS already, I missed this issue to mention in on the release notes. (added it now)
https://github.com/Azure/AKS/releases/tag/2020-10-12

**Comment by nboeckmann** [comment]
Hi @palma21 ,

thank you very much - it was getting more urgent but was nothing critical - otherwise I'd have made a support case.

Nils
