### ISSUE TITLE
Ingress paths do not work

### ISSUE THREAD

**Issue by neildonkin** [Azure/AKS#186]
I've created an nginx ingress controller via helm:

`helm install stable/nginx-ingress`

I created an ingress using the root path "/", which works fine:

![image](https://user-images.githubusercontent.com/1763776/36213916-dfaf9c0c-119f-11e8-8df7-1a8ecacaacaf.png)

However, when I change the path to "/users" as follows I cannot access the service and get a 404:

![image](https://user-images.githubusercontent.com/1763776/36213942-ebec7f12-119f-11e8-9e70-0b67f3481255.png)

NOTE: the ingress and pods are all in the same namespace

**Comment by slack** [comment]
Double check the ingress nginx configuration `/etc/nginx/nginx.conf` to make sure the server/location blocks are what you would expect, including Host + Location.

**Comment by neildonkin** [comment]
Thanks for your quick response, @slack 

Today I have compared the differences in the nginx.conf files using the "/" path, which works fine and the "/users" path which fails with a 404.

The only difference between the working config and the failing config is that the failing config has a location called "/users" with the exact same configuration as the working "/" location.  In addition the failing config has an additional "/" location.  The two config files are identical, otherwise.

I tried configuring the domain to use TLS to see if it was a security issue.  Again, the "/" path works perfectly, but the "/users" path fails as before.

**Comment by neildonkin** [comment]
I wonder if it is related to https://github.com/kubernetes/ingress-nginx/issues/1874

**Comment by neildonkin** [comment]
@slack, can you please change this from a question to a bug?  Fanout ingress is simply not working in the current release of AKS.

**Comment by slack** [comment]
@neildonkin likely this is a problem with nginx-ingress rather than AKS.

**Comment by neildonkin** [comment]
@slack OK.  Do you know of a better alternative ingress I could use?

Thanks

**Comment by neildonkin** [comment]
Do you have any plans to create an AKS ingress controller, similar to Google's "ingress-gce"?

https://github.com/kubernetes/ingress-gce

**Comment by raviada** [comment]
I ran into the same issue. I am not able to get nginx ingress to work.  What are the alternatives to use for a fanout ingress? This is a bummer

**Comment by neildonkin** [comment]
I reached out to @brendandburns on Twitter and he is going to try to reproduce this.

He suggests trying haproxy or trafaek instead of nginx, which I'm going to try this week:

https://twitter.com/brendandburns/status/977394638280581121

Fanout ingress is an essential feature, so hopefully it will be working on AKS when it GAs.

**Comment by mdaguete** [comment]
Hi @neildonkin @raviada 

Take care of path ending in `/` if in ingress yaml you have `- path: /users`. It will match `/users/.*` and not `/users` 

Regards.

**Comment by neildonkin** [comment]
Thanks @mdaguete 

I tried "/users" and "/users/" and neither of them work.

I also tried this with both the nginx the traefik ingress Helm Charts and neither work, so it looks like it must be an issue with AKS.

**Comment by brendandburns** [comment]
I don't think this is likely to be a problem with AKS, as these components work basically entirely on top of the Kubernetes layer which is isolated from AKS.

You could validate that it is AKS vs something else by trying to deploy this on top of `minikube` or some other non-AKS kubernetes.

If it works on a non-AKS kubernetes then it is AKS, otherwise, I think it must be something in your `Ingress` config.

**Comment by derekperkins** [comment]
Ingress works successfully for me on a 1.9.1 cluster. I'm using https://github.com/kubernetes/ingress-nginx

**Comment by neilpeterson** [comment]
Here is a doc that demonstrates NGINX ingress + kube-lego on AKS. Last time I checked, it works well on AKS.

https://docs.microsoft.com/en-us/azure/aks/ingress

**Comment by neildonkin** [comment]
I finally got this to work!

I deleted the traefik ingress helm chart and re-installed it in the `kube-system` namespace, as recommended here: https://github.com/kubernetes/charts/tree/master/stable/traefik

`helm install stable/traefik --name my-ingress --namespace kube-system`

My ingress yaml is as follows:

![image](https://user-images.githubusercontent.com/1763776/37958784-563eb2b2-31a9-11e8-8d08-1adb9366da1d.png)

Note that I didn't need a trailing slash on my path name, but I **did** have to include `ingress.kubernetes.io/rewrite-target: /`

Thanks to everyone for the suggestions

**Comment by nishantjadhavinfosys** [comment]
I have followed all the steps https://docs.microsoft.com/en-us/azure/aks/ingress-internal-ip to setup ingress controller on internal. Also followed all the steps above. Still I am also facing same problem.

**Comment by mdaguete** [comment]
Hi @nishantjadhavinfosys,

Plese read the ingress-ngix doc, https://kubernetes.github.io/ingress-nginx/examples/rewrite/, as the annotation meaning was change in version 0.22.0

Regards.

**Comment by nishantjadhavinfosys** [comment]
> Hi @nishantjadhavinfosys,
> 
> Plese read the ingress-ngix doc, https://kubernetes.github.io/ingress-nginx/examples/rewrite/, as the annotation meaning was change in version 0.22.0
> 
> Regards.

Thanks. I am able to resolve using above link. AKS documentation is not updated. I followed AKS documentation.

**Comment by praveenkadimi** [comment]
I’m also facing same issue...

Can someone share the ingress controller sample  yaml file which helps to resolve above  issue.

**Comment by jnoller** [comment]
@praveenkadimi please stop copying and pasting the same comment to multiple issues. This is effectively spamming and I will have to block you from the tracker.
