### ISSUE TITLE
CoreDNS: how enable Prometheus metrics

### ISSUE THREAD

**Issue by marcoboffi** [Azure/AKS#1861]
**What happened**: Prometheus don't scrape coredns metrics

**What you expected to happen**: _coredns_ deployment contains `prometheus.io/port: "9153"` annotation but it doesn't contain `prometheus.io/scrape: 'true'`. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: How is it possible to enable prometheus metrics? Could be metrics enabled by default in AKS cluster (adding correct annotation?)

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"ba1ce4122d67b0f7399a41afbbd8a7258d22ecb8", GitTreeState:"clean", BuildDate:"2020-04-21T00:13:25Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?): 15
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by marcoboffi** [comment]
See also: https://github.com/Azure/AKS/issues/1364#issuecomment-616737413

**Comment by miwithro** [comment]
We verified the workaround is sticky as posted in #1364

create a patcher file:
spec:
  template:
    metadata:
      annotations:
        prometheus.io/port: "9153"
        prometheus.io/scrape: "true"
then
kubectl patch -n kube-system deploy coredns --patch "$(cat coredns-patcher.yaml)"
