### ISSUE TITLE
Multiple gateways

### ISSUE THREAD

**Issue by chris3081** [Azure/AKS#1862]
Hi folks,

We are in the process of trying to move an k8s cluster to Azure from our on premise kit in this kit we have a number of networks that our pods need to talk to and for this we have been using the SBR metadata plugin to push pods out to different routers that aren't configured as the default gateway for the kube host. I'm wondering if this is possible in Azure? 
![AK](https://user-images.githubusercontent.com/19366891/93416823-f170ee80-f8e9-11ea-9539-bc8317bd785c.png)

Our initial configuration in Azure would be via VPN or in some cases a vnet peering, but in the future we are interested in moving to a express route for some of the deployment so we aren't looking to limit this. I've included a basic diagram to explain what I'm trying to do. Anyone done this before and have a blog or similar explaining how they did it, or could offer some pointers on how to do it?

Chris

**Comment by chris3081** [comment]
Is there nobody in the world that has a need to do this from AKS?

**Comment by palma21** [comment]
+@aanandr 

I'm not sure I completely understood your scenario. You want each pod to be able to communicate through a different NIC?

**Comment by chris3081** [comment]
Hi palma21 a different gateway is what I'm chasing as we have overlapping ip addresses in the sites at this point in time. In our prem we use a slightly modified sbr plugin to cause containers to use a different gateway on the same network.
