### ISSUE TITLE
Excessive CoreDNS instances when running with Virtual Node enabled

### ISSUE THREAD

**Issue by tecoholic** [Azure/AKS#1865]
**What happened**:
I setup a single node AKS system for development with virtual node support. I noticed that there are 5 replicas of CoreDNS running reserving about 25% of CPU (the node is a B2ms machine). Upon checking the coredns-autoscaler configuration

```
--default-params={"ladder":{"coresToReplicas":[[1,2],[512,3],[1024,4],[2048,5]],"nodesToReplicas":[[1,2],[8,3],[16,4],[32,5]]}}
```
It can be seen that the replicas should only be 2 as I have less than 512 cores and less than 8 nodes. But then I realized that I don't have actually less than 512 cores because the virtual node reports 10K cores. Technically CoreDNS is working as expected. It is scaled to 5 replicas as the cores are more than 2048.

**What you expected to happen**:

But, it should be that way. It should only be running 2 instances of coredns. The cores reported by the virtual node shouldn't skew the coredns to scale to 5 replicas while 1 or 2 will do just fine.

**How to reproduce it (as minimally and precisely as possible)**:

Create a AKS cluster with virtual node support

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"f862ce9a809b9832be36717bfc4efae470f59fbf", GitTreeState:"clean", BuildDate:"2020-08-24T18:41:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?) - 1

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by palma21** [comment]
Unfortunately the core number is proxy metric, if all the pods that you can schedule in VN would do DNS queries then just the 2 replicas could not be enough, similarly if you have 100 nodes that amount for all those cores and do no DNS queries, than 2 replicas might actually be fine. We're always working to get more granular ways to scale and have some proposals being explored in kubernetes upstream to be a bit more granular

**Comment by tecoholic** [comment]
Thanks for the update.
