### ISSUE TITLE
AKS to respect mixed case in node labels

### ISSUE THREAD

**Issue by DiegoBallve** [Azure/AKS#1867]
Similarly to #1747, AKS is not respecting character case when defining node labels.

For instance:
$ az aks nodepool add --name authonlypool \
   --resource-group $AKS_RESOURCE_GROUP --cluster-name $AKS_CLUSTER_NAME \
   --enable-cluster-autoscaler --min-count 1 --max-count 6 \
   --labels "poolAvailability=single-zone" \
   --zones "1"

creates a pool with:
    "nodeLabels": {
      "poolavailability": "single-zone"
    },

This used to work in AKS 1.15.x, fails in freshly upgraded AKS 1.18.8.

In both versions the client version is:
$ az version
{
  "azure-cli": "2.11.1",
  "azure-cli-core": "2.11.1",
  "azure-cli-telemetry": "1.0.5",
  "extensions": {}
}

**Comment by zqingqing1** [comment]
I believe the issue is fixed already. I tested with latest change, and it showed expected label for node pool. 
```
{
  "agentPoolType": "VirtualMachineScaleSets",
  "availabilityZones": [
    "1"
  ],
  "count": 3,
  "enableAutoScaling": true,
  "enableNodePublicIp": false,
  "id": "/subscriptions/c1089427-83d3-4286-9f35-5af546a6eb67/resourcegroups/qizhe-westeurope/providers/Microsoft.ContainerService/managedClusters/test-label/agentPools/labelpool2",
  "maxCount": 6,
  "maxPods": 110,
  "minCount": 1,
  "mode": "User",
  "name": "labelpool2",
  "nodeImageVersion": "AKSUbuntu-1804-2020.12.15",
  "nodeLabels": {
    "poolAvailability": "single-zone"
  },
  "nodeTaints": null,
  "orchestratorVersion": "1.18.10",
  "osDiskSizeGb": 128,
  "osDiskType": "Managed",
  "osType": "Linux",
  "powerState": {
    "code": "Running"
  },
  "provisioningState": "Succeeded",
  "proximityPlacementGroupId": null,
  "resourceGroup": "qizhe-westeurope",
  "scaleSetEvictionPolicy": null,
  "scaleSetPriority": null,
  "spotMaxPrice": null,
  "tags": null,
  "type": "Microsoft.ContainerService/managedClusters/agentPools",
  "upgradeSettings": {
    "maxSurge": null
  },
  "vmSize": "Standard_DS2_v2",
  "vnetSubnetId": null
}
```

**Comment by zqingqing1** [comment]
If you still see the issue, you can try to upgrade to latest cli to see if that helps.
