### ISSUE TITLE
Add some way to query which Feature-Flags are enabled 

### ISSUE THREAD

**Issue by evillgenius75** [Azure/AKS#187]
There are workloads that are starting to show up that require certain Kube-api, controller-manager, Scheduler feature flags to be enabled to deploy a specific way. Examples:
Istio with auto side-car injection - aggregated-API flag
RBAC - RBAC Flag
HPA based on customer metrics - aggregated API
Auditing - audit policy flags

Perhaps a cli that can list the different flags enabled on the control plane components that are running on a specific cluster:
```
az aks get feature-flags -n <aks-resource-name> -g <resourceGroup Name>
```

Agin this would just be to query and not change so in selecting possible workloads it is understood if it can be deployed to AKS or not.

**Comment by bucksteamy** [comment]
+1 on this request as I believe it would significantly increase AKS users self sufficiency. From a product perspective, I also believe that it would releave some pressure incurred with maintaining AKS documentation in line with specific AKS Kubernetes versions.

**Comment by seanknox** [comment]
Moved to our feature request forum: https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/35051083-add-way-to-query-which-feature-flags-are-enabled
