### ISSUE TITLE
Windows image in Release 2020-09-21 does not exist

### ISSUE THREAD

**Issue by zhiweiv** [Azure/AKS#1870]
Release 2020-09-21
> Component updates
> AKS Windows image has been updated to 2019-datacenter-core-smalldisk-17763.1397.200904

However https://github.com/Azure/aks-engine/blob/master/vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1397.200904.txt is 404, there are only 2019-datacenter-core-smalldisk-17763.1397.200917.txt and 2019-datacenter-core-smalldisk-17763.1397.200820.txt.

**Comment by zhiweiv** [comment]
@palma21

**Comment by AbelHu** [comment]
Thanks for reporting this, @zhiweiv .
The link is https://github.com/Azure/AgentBaker/blob/master/vhdbuilder/release-notes/AKSWindows/2019/17763.1397.200904.txt.

**Comment by zhiweiv** [comment]
Windows 9B is not included in this image, anyway it is ok close.
