### ISSUE TITLE
Calico Log rules have no effect on AKS

### ISSUE THREAD

**Issue by ShachafGoldstein** [Azure/AKS#1872]
**What happened**: Defining Calico logging rules have no effect and no logs seem to output anywhere 

**What you expected to happen**: Logs to show on stdout/err

**How to reproduce it (as minimally and precisely as possible)**:
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: log
spec:
  selector: all()
  ingress:
  - action: Allow
  - action: Log
    destination:
      selector: all()

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.17.9
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) demo https page
- Others:

**Comment by mtparet** [comment]
Logs are written to journald/syslog by iptables. You can use https://github.com/box/kube-iptables-tailer/ with the chart https://hub.helm.sh/charts/lifen/kube-iptables-tailer to push event about drop on the pods.

**Comment by ShachafGoldstein** [comment]
Closing this, no idea why it didn't log anything before but now it seems to work.
Apologies for the waste of time.

for reference used the daemonset mentioned [here](https://gist.github.com/feiskyer/6e3104d3ca63d7b242ff70e90a133ed1) to retrieve the logs for tests
