### ISSUE TITLE
apply audit policy to control the auditing of kube-audit logs.

### ISSUE THREAD

**Issue by rakesh08** [Azure/AKS#1873]
Currently unable to apply audit policy[1] in AKS to control the kube-audit logs. Since end user can't make any customization to control plane, as it's managed by AKS. Requesting to provide a way for the end user to apply audit policy or control the logging of kube-audit logs. 

[1] https://kubernetes.io/docs/tasks/debug-application-cluster/audit/

**Comment by rakesh08** [comment]
Similar issue was been reported https://github.com/Azure/AKS/issues/946#issuecomment-596982744. It has been closed.

**Comment by miwithro** [comment]
Hello,
  There is already an audit policy applied to the AKS clusters.  There is no need to add one.   You simply just need to query the logs.

https://docs.microsoft.com/en-us/azure/aks/view-master-logs

Here is the applied audit policy:
https://github.com/Azure/aks-engine/blob/24244adcd09afcf452c2e16317999046a240e992/parts/k8s/addons/audit-policy.yaml
