### ISSUE TITLE
AKS Cluster provision failed with kubenet & UDR with existing subnet and security group

### ISSUE THREAD

**Issue by sivamca127** [Azure/AKS#1875]
provider "azurerm" {
		version = "~> 2.15"
		features {}
	}
	
	data "azurerm_resource_group" "aks" {
		name     = var.resource_group
	}
	
	#fetch existing subnet 
	data "azurerm_subnet" "aks" {
		name                 = var.subnetname
		virtual_network_name = var.virtual_network_name
		resource_group_name  = var.vnet_resource_group
	}
	
	resource "azurerm_network_interface" "k8svmnic" {
		name                = "k8svmnic"
		resource_group_name = data.azurerm_resource_group.aks.name
		location            = data.azurerm_resource_group.aks.location
	
		ip_configuration {
			name                          = "internal"
			subnet_id                     = data.azurerm_subnet.aks.id
			private_ip_address_allocation = "Static"
			private_ip_address            = "10.9.56.19"
		}
	}
	
	resource "azurerm_availability_set" "k8svmavset" {
		name                         = "k8svmavset"
		location                     = data.azurerm_resource_group.aks.location
		resource_group_name          = data.azurerm_resource_group.aks.name
		platform_fault_domain_count  = 2
		platform_update_domain_count = 2
		managed                      = true
	}
	
	resource "azurerm_network_security_group" "k8svmnsg" {
		name                  = "k8vm-nsg"
		resource_group_name   = data.azurerm_resource_group.aks.name
		location              = data.azurerm_resource_group.aks.location
	
		security_rule {
			name                            = "allow_kube_tls"
			protocol                        = "Tcp"
			priority                        = 100
			direction                       = "Inbound"
			access                          = "Allow"
			source_address_prefix           = "*"
			destination_address_prefix      = "*"
			source_port_range               = "*"
			destination_port_range          = "443"
			description                     = "Allow kube-apiserver (tls) traffic to master"
		}
		
		security_rule {
			name                            = "allow_ssh"
			protocol                        = "Tcp"
			priority                        = 101
			direction                       = "Inbound"
			access                          = "Allow"
			source_address_prefix           = "*"
			destination_address_prefix      = "*"
			source_port_range               = "*"
			destination_port_range          = "22"
			description                     = "Allow SSH traffic to master"
		}
	}
	
	resource "azurerm_network_interface_security_group_association" "k8svmnicnsg" {
		network_interface_id                = azurerm_network_interface.k8svmnic.id
		network_security_group_id           = azurerm_network_security_group.k8svmnsg.id
	}
	
	
	resource "azurerm_linux_virtual_machine" "k8svm" {
	
		name                            = "k8svm"
		resource_group_name             = data.azurerm_resource_group.aks.name
		location                        = data.azurerm_resource_group.aks.location
		size                            = "Standard_D3_v2"
		admin_username                  = var.admin_username
		disable_password_authentication = true
		availability_set_id             = azurerm_availability_set.k8svmavset.id
		
		network_interface_ids = [
			"${azurerm_network_interface.k8svmnic.id}"
			]
	
		admin_ssh_key {
			username        = var.admin_username
			public_key      = var.ssh_key
		}
	
		os_disk {
			caching              = "ReadWrite"
			storage_account_type = "Standard_LRS"
			disk_size_gb         = 30
		}
	
		source_image_reference {
			publisher = "microsoft-aks"
			offer     = "aks"
			sku       = "aks-engine-ubuntu-1804-202007"
			version   = "2020.07.24"
		}
	
	}
	
	resource "azurerm_managed_disk" "k8svm-disk" {
		name                    = "${azurerm_linux_virtual_machine.k8svm.name}-disk"
		location                = data.azurerm_resource_group.aks.location
		resource_group_name     = data.azurerm_resource_group.aks.name
		storage_account_type    = "Standard_LRS"
		create_option           = "Empty"
		disk_size_gb            = 512
	
	}
	
	resource "azurerm_virtual_machine_data_disk_attachment" "k8svm-disk-attachment" {
		managed_disk_id         = azurerm_managed_disk.k8svm-disk.id
		virtual_machine_id      = azurerm_linux_virtual_machine.k8svm.id
		lun                     = 5
		caching                 = "ReadWrite"
	}
	
	resource "azurerm_route_table" "aks"{
		name                          = "aks" #var.subnetname
		resource_group_name           = data.azurerm_resource_group.aks.name
		location                      = data.azurerm_resource_group.aks.location
		disable_bgp_route_propagation = false
	
		route {
				name                = var.route_name
				address_prefix      = var.route_address_prefix
				next_hop_type       = var.route_next_hop_type
		}
	
		route {
				name                    = "VirtualAppliance"
				address_prefix          = "172.42.2.0/24"
				next_hop_type           = "VirtualAppliance"
				next_hop_in_ip_address  = "10.9.56.19"
		}
	
		route {
				name                    = "default_route"
				address_prefix          = "0.0.0.0/0"
				next_hop_type           = "VirtualAppliance"
				next_hop_in_ip_address  = "10.9.56.19"
		}
	
	}
	resource "azurerm_subnet_route_table_association" "aks" {
		subnet_id      = data.azurerm_subnet.aks.id
		route_table_id = azurerm_route_table.aks.id
	}
	
	resource "azurerm_subnet_network_security_group_association" "aks" {
		subnet_id                 = data.azurerm_subnet.aks.id
		network_security_group_id = var.network_security_group
	}
	resource "null_resource" "previous" {}
	
	resource "time_sleep" "wait_90_seconds" {
		depends_on = [null_resource.previous]
	
		create_duration = "90s"
	}
	
	# This resource will create (at least) 30 seconds after null_resource.previous
	resource "null_resource" "next" {
		depends_on = [time_sleep.wait_90_seconds]
	}
	
	resource "azurerm_public_ip" "aks" {
		name                = "akspip"
		resource_group_name = data.azurerm_resource_group.aks.name
		location            = data.azurerm_resource_group.aks.location
		allocation_method   = "Static"
	}
	
	resource "azurerm_kubernetes_cluster" "aks" {
		name                    = data.azurerm_resource_group.aks.name
		resource_group_name     = data.azurerm_resource_group.aks.name
		location                = data.azurerm_resource_group.aks.location
		dns_prefix              = "akstfelk"   #The dns_prefix must contain between 3 and 45 characters, and can contain only letters, numbers, and hyphens. It must start with a letter and must end with a letter or a number.
		kubernetes_version      = "1.18.8"
		private_cluster_enabled = false
		node_resource_group     = var.node_resource_group
		
		api_server_authorized_ip_ranges = [] #var.api_server_authorized_ip_ranges
		default_node_pool {
			enable_node_public_ip   = false
			name                    = "agentpool" 
			node_count              = var.node_count
			orchestrator_version    = "1.18.8"
			vm_size                 = var.vm_size
			os_disk_size_gb         = var.os_disk_size_gb
			vnet_subnet_id          = data.azurerm_subnet.aks.id
			type                    = "VirtualMachineScaleSets"
		}
	
		linux_profile {
			admin_username = var.admin_username
			ssh_key {
				key_data = var.ssh_key
			}
		}
		service_principal {
			client_id     = var.client_id
			client_secret = var.client_secret
		}
	
		role_based_access_control {
			enabled = true
		}
		network_profile {
			network_plugin     = "kubenet"
			network_policy     = "calico"
			dns_service_ip     = "172.16.1.10"
			service_cidr       = "172.16.0.0/16"
			docker_bridge_cidr = "172.17.0.1/16"
			pod_cidr           = "172.42.0.0/16"
			outbound_type      = "userDefinedRouting"
			load_balancer_sku  = "Standard"
	
	
			# load_balancer_profile {
			#     #managed_outbound_ip_count = 1
			#     outbound_ip_address_ids   = ["${azurerm_public_ip.aks.id}"]
			#     #outbound_ip_prefix_ids    = []
				
			# }
		}
				addon_profile {
				aci_connector_linux {
				enabled = false
			}
	
			azure_policy {
				enabled = false
			}
	
			http_application_routing {
				enabled = false
			}
	
			kube_dashboard {
				enabled = false
			}
	
			oms_agent {
				enabled = false
			}
		}
		depends_on = [azurerm_subnet_route_table_association.aks]
	}

**Comment by sivamca127** [comment]
Can someone help me here?

**Comment by sivamca127** [comment]
seems no one ready to help here?  its been 5 days but no response from the team.

**Comment by TomGeske** [comment]
Your worker nodes need outbound connectivity. userDefinedRouting needs either VirtualAppliance or VirtualNetworkGateway as next hopp. Why do you have **0.0.0.0/0** route to Internet?

**Comment by sivamca127** [comment]
Thank you @TomGeske for your response. As you Said , I've created VirtualAppliance and trying to create unfortunately its not creating load balancer while provision time. 

if i've not added the Root **"0.0.0.0/0"**  then terrofm throwing error like route table must configured default route . so i've added it. I'm going to upload full  code snipped. Please have advise if i'm missing anything.

**Comment by TomGeske** [comment]
According to our [docs](https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic#create-a-udr-with-a-hop-to-azure-firewall) route configuration should look like: 
```
route {
	name                    = "default_route"
	address_prefix          = "0.0.0.0/0"
	next_hop_type           = "VirtualAppliance"
	next_hop_in_ip_address  = "10.9.56.19"
}

route {
	name                    = "Internet"
	address_prefix          = "172.42.2.0/24"
	next_hop_type           = "Internet"
	next_hop_in_ip_address  = "10.9.56.19"
}
```

**Comment by sivamca127** [comment]
@TomGeske , i'll check and update you shortly.

**Comment by sivamca127** [comment]
@TomGeske , i've modified the routes as you suggested and route table related issues are resolved now but outbound connections issues are not still exist. 

Even i'm also struggling a lot with couple of issues with respect to UserDefinedRouting (Custom subnet and Routetable).

Here is error info:

Error: creating Managed Kubernetes Cluster "aks-tf" (Resource Group "aks-tf"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 --
Original Error: Code="InvalidUserDefinedRoutingWithLoadBalancerProfile" Message="UserDefinedRouting and load balancer profile are mutually exclusive. Please refer to http://aka.ms/aks/outboundtype for more details" Target="networkProfile.loadBalancerProfile"

I've tried with&without managed_outbound_Ip_count and outbound_address_ids=[] & [azurerm_public_ip.aks.id]

Here is my code snippet:

              network_profile {
	         network_plugin     = "kubenet"
	          network_policy     = "calico"
	         dns_service_ip     = "172.16.1.10"
	         service_cidr       = "172.16.0.0/16"
	         docker_bridge_cidr = "172.17.0.1/16"
	        pod_cidr           = "172.40.0.0/16"
	       outbound_type      = "userDefinedRouting"
               load_balancer_sku  = "Standard"

               load_balancer_profile {
	             outbound_ip_address_ids = [ "${azurerm_public_ip.aks.id}" ]

               }
              # load_balancer_profile {
              #     managed_outbound_ip_count = 5
              #     #effective_outbound_ips    = [ azurerm_public_ip.aks.id ]
              #     outbound_ip_address_ids   = []
              #     outbound_ip_prefix_ids    = []
              #     outbound_ports_allocated  = 0
	
              # }
              }
I don't find much examples on UDR with detailed information.

much appreciated for any help.

**Comment by Raviteza7796** [comment]
I am also facing similar issue while trying to deploy with ARM Template

**Comment by NBroomfield** [comment]
Any update on this? 

I've been following your documentation on UDR and egress (https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic), but they use an Azure firewall which is too expensive for my needs, I'd like to remove this element, but then I get these same issue with the routing table.

Thanks

**Comment by EPinci** [comment]
@paulgmiller Can you investigate, please?

**Comment by palma21** [comment]
> load_balancer_sku  = "Standard"
> 
>            load_balancer_profile {
>              outbound_ip_address_ids = [ "${azurerm_public_ip.aks.id}" ]



>           network_profile {
>          network_plugin     = "kubenet"
>           network_policy     = "calico"
>          dns_service_ip     = "172.16.1.10"
>          service_cidr       = "172.16.0.0/16"
>          docker_bridge_cidr = "172.17.0.1/16"
>         pod_cidr           = "172.40.0.0/16"
>        outbound_type      = "userDefinedRouting"
>            load_balancer_sku  = "Standard"
> 
>            load_balancer_profile {
>              outbound_ip_address_ids = [ "${azurerm_public_ip.aks.id}" ]
> 
>            }
>           # load_balancer_profile {
>           #     managed_outbound_ip_count = 5
>           #     #effective_outbound_ips    = [ azurerm_public_ip.aks.id ]
>           #     outbound_ip_address_ids   = []
>           #     outbound_ip_prefix_ids    = []
>           #     outbound_ports_allocated  = 0
> 
>           # }
>           }

When you define UDR you can't have any element of LB, as the error indicates they are mutually exclusive, please remove those lines and let us know how it goes.
