### ISSUE TITLE
Support for Azure secret store CSI

### ISSUE THREAD

**Issue by aelmanaa** [Azure/AKS#1876]
Hello,

I see that there are efforts to include AZure file csi & Azure ad pod identity projects in AKS and make them part of GA.
Are there similar plans for AZure secret store csi? https://github.com/Azure/secrets-store-csi-driver-provider-azure

In fact, this project is really important as it allowas to directly fetchs secrets & certificates from Azure keyvault 

thanks

**Comment by tomkerkhove** [comment]
I fully agree!

**Comment by andyzhangx** [comment]
Answer is Yes, will update when there is any progress, it's now in early evaluation stage.

**Comment by ZeroMagic** [comment]
If someone uses SP and needs the feature, look at this issue https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/281, and feel free to add your comments.

**Comment by PixelRobots** [comment]
Looks like this can be done already in preview. 

I did a little blog about it. https://pixelrobots.co.uk/2021/04/azure-key-vault-access-on-azure-kubernetes-service-using-the-new-aks-add-on/

**Comment by miwithro** [comment]
https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver

**Comment by PixelRobots** [comment]
Thanks for the official docs. Really good page.

**Comment by yogeshpatiltr** [comment]
Do you have ETA to release this AKS-AzureKeyVaultSecretsProvider feature to GA(Generally Available)?

**Comment by deepak-malhotra** [comment]
The Helm chart deployments are usually supported earlier than the add-ons . Is there any ETA on support for using CSI via Helm ?

**Comment by andyzhangx** [comment]
@ZeroMagic any rough ETA of secret store CSI driver GA on AKS?

**Comment by ZeroMagic** [comment]
After upstream project GA(https://github.com/kubernetes-sigs/secrets-store-csi-driver/milestone/5), will start the GA work of `AKS-AzureKeyVaultSecretsProvider` feature. The ETA is September/October.

**Comment by rukawata** [comment]
@ZeroMagic When will `AKS-AzureKeyVaultSecretsProvider` be available for `AzureUSGovernment`

**Comment by ZeroMagic** [comment]
> @ZeroMagic When will `AKS-AzureKeyVaultSecretsProvider` be available for `AzureUSGovernment`

@rukawata  It will be the part of GA work.

**Comment by tomkerkhove** [comment]
Add-on for Arc is now in preview: https://techcommunity.microsoft.com/t5/azure-arc-blog/in-preview-azure-key-vault-secrets-provider-extension-for-arc/ba-p/3002160

**Comment by palma21** [comment]
GA
