### ISSUE TITLE
Unable to connect to the server: dial tcp ip:443: i/o timeout

### ISSUE THREAD

**Issue by agalisteo** [Azure/AKS#188]
We are having issues trying to connect to our AKS cluster in east US.

Command ```kubectl get nodes``` getting the error:
```Unable to connect to the server: dial tcp ip:443: i/o timeout```

**Comment by NiPfi** [comment]
I have the same issue. My AKS cluster is in east US.

**Comment by agalisteo** [comment]
@NiPfi We have the same issue, when did you start having this problem?

**Comment by NiPfi** [comment]
@agalisteo I can't say for certain but sometime between yesterday 14. Feb. 17:00 UTC and today 07:00 UTC since it wasn't working when I tried to connect to the cluster this morning.

**Comment by agalisteo** [comment]
@NiPfi What version of kuberntes are you using?

**Comment by NiPfi** [comment]
@agalisteo Kubernetes Version is 1.8.7

**Comment by rzal** [comment]
I'm having the same issue, first we had lost westeurope then centralus.
Running 1.8.6.

`
curl https://****-centr-c36a81-e65c432b.hcp.centralus.azmk8s.io
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.
`

The URL seems respond to the HTTP scheme but only for Nginx to redirect to HTTPs then it times out.
```
* Connected to **-aks-**-aks-centr-c36a81-e65c432b.hcp.centralus.azmk8s.io (52.173.87.155) port 80 (#0)
> GET / HTTP/1.1
> Host: **-aks-**-aks-centr-c36a81-e65c432b.hcp.centralus.azmk8s.io
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.13.5
< Date: Thu, 15 Feb 2018 10:47:35 GMT
< Content-Type: text/html
< Content-Length: 185
< Connection: keep-alive
< Location: https:
```

**Comment by rzal** [comment]
Hi guys, do any of you use ingress controllers? I wonder if there's an ingress data leak from agents to master nodes. Looks like the API IP address responds with NGINX default backend: 
```
curl -v 52.173.87.155
* Rebuilt URL to: 52.173.87.155/
*   Trying 52.173.87.155...
* Connected to 52.173.87.155 (52.173.87.155) port 80 (#0)
> GET / HTTP/1.1
> Host: 52.173.87.155
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Server: nginx/1.13.5
< Date: Thu, 15 Feb 2018 10:58:25 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 21
< Connection: keep-alive
< Strict-Transport-Security: max-age=15724800; includeSubDomains;
< 
* Connection #0 to host 52.173.87.155 left intact
default backend - 404
```

**Comment by NiPfi** [comment]
I am using an nginx-ingrss yes. CURLing the ip does result in a timeout though, not a default backend answering.

**Comment by rzal** [comment]
@NiPfi Thanks, I think that's a clue. 

I'm trying to deploy a new cluster and use a different ingress-class other than `nginx` see if that makes a difference.
```
        args:
        - /nginx-ingress-controller
        - --ingress-class=myown-nginx

```
Well, I would try, but I am getting this for `westeurope`, trying `eastus` 

> Deployment failed. Correlation ID: 63210ba5-224f-44f7-b335-0356e54f5047. Azure Container Service is unable to provision an AKS cluster in westeurope, due to an operational threshold. Please try again later or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md.

**Comment by agalisteo** [comment]
I have two AKS cluster in EAST US
* The first with nginx-ingress, works perfectly.
* second, fresh install, metioned in this issue (failed state)

**Comment by NiPfi** [comment]
It might be worth noting that I deprovisioned my worker VM overnight to save costs since I'm working in a dev environment with the limited VS Pro license

**Comment by craigfitzpatrick** [comment]
I have the same issue in the East US region, although I am running Kubernetes 1.7.7.

Like NiPfi, I have been shutting down my worker VM overnight to save costs in my limited dev environment. However, prior to today I have been able to successfully stop it overnight, restart it the next day, and use AKS.

**Comment by craigfitzpatrick** [comment]
I have the same issue in the East US region, although I am running Kubernetes 1.7.7.

Like NiPfi, I have been shutting down my worker VM overnight to save costs in my limited dev environment. However, prior to today I have been able to successfully stop it overnight, restart it the next day, and use AKS.

**Comment by agalisteo** [comment]
Can you confirm if the services exposed to the outside are accessible despite the error?

**Comment by craigfitzpatrick** [comment]
I didn't have any services deployed at the time I experienced the error.

**Comment by rzal** [comment]
@agalisteo Everything else works. The running pods have not been affected. 
Not sure how the scheduling is currently working though

**Comment by NiPfi** [comment]
@agalisteo The service does in fact not respond in my case

**Comment by craigfitzpatrick** [comment]
I haven't had any trouble today with a replacement cluster I provisioned. I am now shutting down the worker pool VM for the night. We'll see if the problem recurs tomorrow.

**Comment by bacongobbler** [comment]
Just an update that someone else internally saw the same error with their cluster while testing a few things; re-provisioning a new cluster and everything seems fine this morning.

**Comment by agalisteo** [comment]
My East US AKS instance seems to be healthy again.

**Comment by CarlosAmaral** [comment]
I'm running kubernetes on redhat and I'm getting the same problem. It was working fine in the morning and now doesn't connect again.

**Comment by NiPfi** [comment]
My cluster is once again available though it has been reset and I need to redeploy my environment

**Comment by seanknox** [comment]
Closing due to age; please reopen if still an issue.
