### ISSUE TITLE
Feature request: allow host caching mode to be specified for agent pools

### ISSUE THREAD

**Issue by OvervCW** [Azure/AKS#1880]
We have different agent pools within our AKS cluster for different types of workloads and we would like to tune the host disk cache setting for this purpose.

For example, some nodes tend to run workloads that require large Docker pulls and we see that this causes them lock up while the cache is being flushed, and we could solve this problem by changing the host caching mode from `Read/write` to `None`.

While it is currently possible to change the host caching mode of each VMSS after initially creating the agent pools, we've noticed that this setting is reset after Kubernetes upgrades. Furthermore, all nodes need to be rebooted to apply this setting every time it's changed. Therefore we would like to have the ability to specify the host caching mode upon creation of an agent pool in the same way that `osDiskSizeGB` is already configurable per pool.

**Comment by andyzhangx** [comment]
I doubt whether set caching mode could solve os disk throttling issue, could you try https://azure.microsoft.com/en-us/updates/public-preview-ephemeral-os-disk-support-in-aks/, it would help a lot.

**Comment by xuto2** [comment]
agree with Ander's comment above.
