### ISSUE TITLE
Clusters with Calico & other add-ons enabled cannot be upgraded

### ISSUE THREAD

**Issue by jluk** [Azure/AKS#1881]
For any calico CNI cluster created before Jun 2020, the cluster's configuration of calico-typha is having issues being upgraded.

Impact: This issue may block other addon operations, including enable/disable/upgrade. 

Validate if impacted: To check whether you are impacted, get the image version of the `calico-typha` deployment from the `kube-system` namespace. If it's on version `0.3.8`, you are not impacted. If you are on an older version, this issue may affect your cluster.

Mitigation: You can mitigate this by deleting the calico-typha deployment. AKS will install a replacement via automatic remediation in a couple of minutes.

This is a known issue and is currently being addressed.

**Comment by wmayer** [comment]
Suppose with 0.3.8 is meant mcr.microsoft.com/oss/calico/typha:v3.8.0. Is mitigation correct: If CNI is used, Calico version is older than 3.8.0 and e.g. an AKS upgrade is planned, then before the upgrade run e.g.:
`kubectl delete deployment calico-typha -n kube-system` 

After some minutes with (planned) downtime then check Calico version is 3.8.0. If that is the case then proceed e.g. AKS upgrade.

**Comment by robbiezhang** [comment]
The issue is fixed and released to all regions.
