### ISSUE TITLE
Unable to create or update AKS with version 1.18.* and containerd enabled

### ISSUE THREAD

**Issue by laurentgrangeau** [Azure/AKS#1883]
**What happened**:
Trying to create a AKS cluster with this command, and it fails
```bash
az aks create --name mycluster --resource-group myrg -s Standard_D4as_v4 --aks-custom-headers CustomizedUbuntu=aks-ubuntu-1804,ContainerRuntime=containerd,usegen2vm=true --network-plugin azure --network-policy calico -k 1.18.8
```

Here is the error message:
```bash
ValidationError: Pods not in Running status: coredns-8bbb65c89-hrpjk,coredns-autoscaler-5585bf8c9f-nphkd,kube-proxy-9xgzf,kube-proxy-r826n,kube-proxy-xjwkk,metrics-server-5b56df69fd-mbh5t,tunnelfront-84f4864664-tgkkt
```

I have a similar behavior when I updated my previous cluster. All the pods were in state ```Container creating``` (RIP little cluster 😢)

**What you expected to happen**:
I expected to have a running cluster or an upgraded one

**How to reproduce it (as minimally and precisely as possible)**:
Follow the documentation to enable containerd cluster (https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#use-containerd-as-your-container-runtime-preview) and run the command
```bash
az aks create --name mycluster --resource-group myrg -s Standard_D4as_v4 --aks-custom-headers CustomizedUbuntu=aks-ubuntu-1804,ContainerRuntime=containerd,usegen2vm=true --network-plugin azure --network-policy calico -k 1.18.8
```

**Anything else we need to know?**:
No 😄 

**Environment**:
- Kubernetes version (use `kubectl version`):
```bash
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?): 1 node pool with default configuration
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): None (as the cluster has not been deploy or upgraded)
- Others:

**Comment by palma21** [comment]
You beat us @laurentgrangeau :) we found this issue a few weeks back and patched it, it's releasing this week (will be on the release notes this week) and will take about 1.5wks from now to complete everywhere.
