### ISSUE TITLE
Can we add Multiple container registries to AKS cluster

### ISSUE THREAD

**Issue by nidiculageorge** [Azure/AKS#1884]
Can we add multiple container registries to a single AKS cluster

az aks update -n myAKSCluster -g myResourceGroup --attach-acr <acr-name>

**Comment by andyzhangx** [comment]
at least you can assign ACR permission to cluster identity(sp or managed identity), that's the way how it works.

**Comment by nidiculageorge** [comment]
@andyzhangx thanks for the information is it possible to add two diffrent acr two one AKS cluster using the

az aks update -n myAKSCluster -g myResourceGroup --attach-acr <acr-name>

I am not sure about the cluster identity stuff

**Comment by neumanndaniel** [comment]
You can run the command multiple times and specifying a different ACR each time.

```
az aks update -n myAKSCluster -g myResourceGroup --attach-acr acr1
az aks update -n myAKSCluster -g myResourceGroup --attach-acr acr2
```

The parameter name is a bit misleading. The command does an Azure RBAC role assignment of the SP or MI on the specified ACR and grants the AKS cluster permissions to pull container images.
