### ISSUE TITLE
In containerd runtime, what is the alernate to mount unix sock with /var/run/docker.sock for logging

### ISSUE THREAD

**Issue by PrabhuMathi** [Azure/AKS#1885]
**What happened**:
In AKS cluster enabled with containerd as a runtime. In current work we are using /var/run/docker.sock for connecting unix sock for pull logs. Is there any alternate option other than using azure monitor?

**What you expected to happen**:
Expecting a solution without changing current logging solution

**How to reproduce it (as minimally and precisely as possible)**:
Log are not extracted in docker.sock after adding a node pool with containerd as a runtime

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.11
- Size of cluster (how many worker nodes are in the cluster?): 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): nodejs container as a agent for extracting logs
- Others:

**Comment by palma21** [comment]
You're not required to use Azure monitor to use/log from  containerd-based nodepools, most monitoring tools should work with it with just a configuration change, several should work out of the box, Eg. for datadog https://docs.datadoghq.com/integrations/containerd/ 

Containerd sets up logging using the standardized cri logging format which is supported by most could native monitoring tools. Does your monitoring tool not support containerd / CRI logging at all? (nor plan to?)
