### ISSUE TITLE
Allow enabling Feature Gates

### ISSUE THREAD

**Issue by djsly** [Azure/AKS#1887]
**What happened**:
We are interested to use the following
https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/
and
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes

both are not enabled on AKS since they haven't been GA yet, while some Alpha/Beta features are risky, I think some are no brainers and should be provided to the users before GA

**What you expected to happen**:
I would like to be able to enable some features gate with a simple `az aks update` command 

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
I understand the AKS Engine would allow us to have more control, but I think this defeats the purpose of using AKS and having Support/Managed Control plane

**Comment by djsly** [comment]
I had a talk with @palma21 and he told me that a Static / Sandbox cluster feature is being worked on to provide the flexibility to users to test Alpha/Beta feature Gates, 
I think it should be enough and acceptable since enabling Alpha/Beta features on production clusters makes it impossible to support.

**Comment by JasonWhall** [comment]
@djsly / @palma21 - was there a related issue to track the sandbox feature? I would be keen to test this once in preview. If not could this issue be re-opened to track once that work is complete?

**Comment by palma21** [comment]
Duplicate for #2058

**Comment by olsenme** [comment]
> @djsly / @palma21 - was there a related issue to track the sandbox feature? I would be keen to test this once in preview. If not could this issue be re-opened to track once that work is complete?

Could I please get more context as to which alpha features you are looking to enable? If this is still an ask?
