### ISSUE TITLE
Problem with pulling images from private acr

### ISSUE THREAD

**Issue by antst** [Azure/AKS#1889]
I have aks created by terraform, with managed identities.
Googled it all. Tried to attach with aka-preview, tried to attach by granting role in terraform, tried to grant role manually, it is always looks exactly the same in AD, of course. But result is always the same also: 

```
[rpc error: code = Unknown desc = Error response from daemon: manifest for XXX.azurecr.io/IMAGE:latest not found: manifest unknown: manifest tagged by "latest" is not found, rpc error: code = Unknown desc = Error response from daemon: Get https://XXX.azurecr.io/v2/ct-server/manifests/latest: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.]

kubelet, aks-agentpool-15354322-vmss000000  Error: ErrImagePull
```

At the same time, I have no problem with deployment from guthub CI actions (of course they use different auth method)

What else could be here?

**Comment by curtdept** [comment]
@antst did you allow AKS to access ACR? there should be a terraform config for it as well on create.

https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration

**Comment by neumanndaniel** [comment]
As you mentioned you are using managed identities with AKS the TF part should look like this https://github.com/neumanndaniel/terraform/blob/master/modules/aks/main.tf#L134-L138 to grant the agentpool MI the appropriate permissions.

**Comment by miwithro** [comment]
@antst have any of the solutions provided worked for you?
