### ISSUE TITLE
external public IP of outbound traffic from POD in AKS cluster

### ISSUE THREAD

**Issue by maniSbindra** [Azure/AKS#189]
Want to know that how externally visible public ip of network traffic originating from a pod in AKS is allocated. This is in context of IP whitelisting.
Based on what I have initially observed Public IP of the earliest Loadbalancer type active service created in the AKS cluster is the externally visible IP for out bound traffic originating from a pod in the cluster. 
These are the steps I did
* I created a service of type LoadBalancer, and got a public IP say 137.X.Y.Z .
* Then I also created a second service of type LoadBalancer and got public IP say 168.A.B.C, I set this service to load balance traffic to pods running the mysql client. Now if I exec into any of these pods and try to get the externally visible public IP of network traffic originating from this pod (using curl ipinfo.io/ip)  it is the public IP associated with the first LoadBalancer type service I created in the cluster (13.X.Y.Z). 
* I also created a third load balancer type service and got a public IP say 52.P.Q.R.
* After I deleted the first service and then checked the externally visible IP of the Pods outbound traffic, it then became the IP of the service which was created second (168.A.B.C)
* Next I deleted the second service, then checked the externally visible IP of the Pods outbound traffic, it then became the IP of the service which was created third/last (52.P.Q.R).

Request you to please clarify rules associated with assigning IP to outbound traffic originating from a pod in an AKS cluster.

Thanks,
Mani

**Comment by slack** [comment]
Outbound traffic from Pods in your AKS cluster follow Azure conventions documented here: https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections

Before your first Kubernetes service type LoadBalancer is created, traffic leaving your cluster follows scenario 3: https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#defaultsnat 
> The VM is not part of an Azure Load Balancer pool and does not have an Instance Level Public IP (ILPIP) address assigned to it. When the VM creates an outbound flow, Azure translates the private source IP address of the outbound flow to a public source IP address. The public IP address used for this outbound flow is not configurable and does not count against the subscription's public IP resource limit. 

Once you create a Kubernetes service in your cluster, the Azure Load Balancer re-configures the outbound source address, which happens to be the first frontend ip configuration on the load balancer: https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#lb
> When the load-balanced VM creates an outbound flow, Azure translates the private source IP address of the outbound flow to the public IP address of the public Load Balancer frontend.

As you observed, if that first service is removed, the source address is updated to be the next frontend ip configuration in the chain.

**Comment by maniSbindra** [comment]
Thank you.

**Comment by tiborb** [comment]
What about Kubernetes CronJobs? https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
How can I claim the outbound IP address of a cron?

**Comment by slack** [comment]
@tiborb I'm not aware of any way to influence the outbound ip address without using an external service as a proxy.

**Comment by ChrisMcKee** [comment]
At an ACS level this seems related to this request from 2016 https://feedback.azure.com/forums/217313-networking/suggestions/17461057-allow-the-use-of-a-known-outbound-nat-gateway-for 
Asking that Azure finally adds NAT gateways like AWS to give what should be client nodes operating in a private subnet external access via a single outbound IP.

**Comment by bahtiyarkaba** [comment]
@slack I guess "AKS in a vnet" always follows scenario 3, is that true? 
Basically, we have a setup where the AKS cluster is in a VNET and we access the services via Azure Application Gateway (in a subnet of the vnet). Therefore, we don't have public Azure loadbalancer. Instead, we have an internal load balancer whose IP is assigned from the virtual network statically. 
How can we enable whitelisting in this scenario?

**Comment by dwd2019** [comment]
> @slack I guess "AKS in a vnet" always follows scenario 3, is that true?
> Basically, we have a setup where the AKS cluster is in a VNET and we access the services via Azure Application Gateway (in a subnet of the vnet). Therefore, we don't have public Azure loadbalancer. Instead, we have an internal load balancer whose IP is assigned from the virtual network statically.
> How can we enable whitelisting in this scenario?

We are facing similar problems to whitelist our AKS to access other PaaS like Azure AQL or Service Bus. Is there a way yo know this public IP associated to outgoing traffic?
