### ISSUE TITLE
Provisioning issues with OMS agent add-on profile

### ISSUE THREAD

**Issue by ohorvath** [Azure/AKS#1890]
**What happened**:

We are using ARM templates to deploy AKS clusters including conditionally enable omsagent integration. 

> “addonProfiles”: {
>                     “omsagent”: {
>                         “config”: {
>                         “logAnalyticsWorkspaceResourceID”: “[if(empty(parameters(‘analyticsWorkspaceID’)),json(‘null’),parameters(‘analyticsWorkspaceID’))]”
>                         },
>                     “enabled”: “[if(empty(parameters(‘analyticsWorkspaceID’)),bool(‘false’),bool(‘true’))]”
>                     }
> 

We experienced that even we use json('null') here, the analyticsWorkspaceID ends up as an empty string value after provisioning the cluster instead of null. After that point, any attempt to modify the AKS configuration like modifying API whitelists, adding new users to AAD RBAC will fail with this error message:

`Failed to save Kubernetes service ‘env-z9wlk2-dwx-rg-mc’. Error: Property id ‘’ at path ‘properties.addonProfiles.omsagent.config.loganalyticsworkspaceresourceid’ is invalid. Expect fully qualified resource Id that start with ‘/subscriptions/{subscriptionId}’ or ‘/providers/{resourceProviderNamespace}/’.
`

**What you expected to happen**:

There should be a proper way to conditionally enable/disable omsagent using ARM templates, but at least the validation procedure should be the same during provisioning and updating the cluster. 

**How to reproduce it (as minimally and precisely as possible)**:

Use the template segment seen above to provision your AKS cluster. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18
- Size of cluster (how many worker nodes are in the cluster?): 10
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by justindavies** [comment]
Hi there, firstly apologies for takins so long to get back to you.  Are you still seeing this issue?
