### ISSUE TITLE
AKS-Managed Azure AD (AAD) Integration Authentication Issue: v1.19.0

### ISSUE THREAD

**Issue by ronamosa** [Azure/AKS#1891]
**What happened**:

When building an AKS-cluster implementing the new AKS-AAD integration as per https://docs.microsoft.com/en-us/azure/aks/managed-aad using Terraform, when using kubernetes v1.19.0 I get the following error after authenticating with a valid Azure account login:

```sh
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code QWTWL3DQW to authenticate.
error: You must be logged in to the server (Unauthorized)
```

I have retrieved the kubeconfig file via: `az aks get-credentials --name aks-cluster --resource-group aks-cluster-rg --overwrite-existing`

**What you expected to happen**:

When I specify v1.17.1 or v1.18.6 I can authenticate the same way with the same account and I can see my cluster when calling, for example, `kubectl get nodes`.

It is the exact same terraform code for every build, I just change the version, so I expect v1.19.0 to do the same thing and authenticate and show me the cluster information I am querying.

**How to reproduce it (as minimally and precisely as possible)**:

I use a custom module (nothing fancy just caters to my configs)

```terraform
provider "azuread" {
  version = ">= 0.6"
}

data "azuread_group" "aks" {
  name = var.aad_group_name
}

resource "azurerm_kubernetes_cluster" "main" {

  lifecycle {
    ignore_changes = [default_node_pool[0].node_count, windows_profile]
  }

  name                              = var.name
  location                          = var.location
  resource_group_name  = var.resource_group_name
  dns_prefix                      = var.prefix
  kubernetes_version       = var.kubernetes_version
  node_resource_group   = "${var.prefix}-nodepool-rg"
  private_cluster_enabled = var.private_cluster
  api_server_authorized_ip_ranges = var.api_auth_ips

  default_node_pool {
    name                          = substr(var.default_node_pool.name, 0, 12)
    orchestrator_version  = var.kubernetes_version
    node_count                = var.default_node_pool.node_count
    vm_size                     = var.default_node_pool.vm_size
    type                           = "VirtualMachineScaleSets"
    max_pods                 = var.default_node_pool.max_pods
    os_disk_size_gb       = var.default_node_pool.os_disk_size_gb
    vnet_subnet_id         = var.vnet_subnet_id
    enable_auto_scaling = var.default_node_pool.cluster_auto_scaling
    min_count                  = var.default_node_pool.cluster_auto_scaling_min_count
    max_count                 = var.default_node_pool.cluster_auto_scaling_max_count
  }

  identity {
    type = "SystemAssigned"
  }

  role_based_access_control {
    enabled = true

    azure_active_directory {
      managed = true
      admin_group_object_ids = [
        data.azuread_group.aks.id
      ]
    }
  }

  tags = var.tags
  
}
```

But also tested it with this simpler AKS setup (just to rule out a few things with my custom module):

```terraform
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "${var.prefix}-k8s-resources"
  location = var.location
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "${var.prefix}-k8s"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "${var.prefix}-k8s"
  kubernetes_version  = "1.19.0"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_DS2_v2"
  }

  identity {
    type = "SystemAssigned"
  }

  role_based_access_control {
    enabled = true

    azure_active_directory {
      managed = true
      admin_group_object_ids = [
        "AAD_GROUP_OBJECT_ID"
      ]
    }
  }

}
```

After a `terraform apply` and successful build
* I pull down the aks kubeconfig: `az aks get-credentials --name aks-cluster --resource-group aks-cluster-rg --overwrite-existing`
* I will run a `kubectl get nodes` and it will ask me to authenticate
* I authenticate successfully
* It throws  `error: You must be logged in to the server (Unauthorized)`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```sh
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

- az-cli version:

```sh
azure-cli                         2.12.1

core                              2.12.1
telemetry                          1.0.6

Python location '/opt/az/bin/python3'
Extensions directory '/home/darthvaldr/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Sep 28 2020, 08:40:52) 
[GCC 7.5.0]
```
- Size of cluster (how many worker nodes are in the cluster?): 1

- Others: 

* I can override everything and talk to my AKS cluster if I retrieve the admin kubeconfig: `az aks get-credentials --name aks-cluster --resource-group aks-cluster-rg --admin --overwrite-existing`

* I will need to dig out the logs again, but I noticed when running `kubectl get nodes -v=9` on the v1.19.0 setup that the curl GET requests to my API server had no authentication / bearer token headers (and gets a 401 as expected), whereas when I use `--admin` and call the API, I can see Auth headers going to the API (and authenticates).

**Comment by audunsolemdal** [comment]
I already had AAD auth enabled and working in my cluster. AKS upgraded from 1.18.6 to 1.19.0 using ARM template.

The upgrade seems to be successful based on Az activity logs, but I am getting the same issues as the OP.

```
az aks get-credentials --resource-group sdpaks-dev --name sdpaks-dev-k8s --overwrite-existing
❯ k get pods
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code xxx to authenticate.
error: You must be logged in to the server (Unauthorized)
❯ k get pods
error: You must be logged in to the server (Unauthorized)
```

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

Azure CLI version 2.12.2

**Comment by audunsolemdal** [comment]
```
"code": "PropertyChangeNotAllowed","code": "PropertyChangeNotAllowed",
  "message": "Changing property 'aadProfile.managed' from 'true' to 'false' is not allowed.",
  "target": "aadProfile.managed"
```

....

**Comment by neumanndaniel** [comment]
Root cause: https://github.com/kubernetes/kubernetes/issues/95211

**Comment by mac8005** [comment]
Have the same issue and in my case i use the same aad tenant then in v18.1.8.

**Comment by palma21** [comment]
1.18 is not the same issue as this one, this is exclusive an issue in 1.19. For any other version please open a support ticket or another issue if it's reproable in any cluster.

The 1.19 fix has shipped this week.

**Comment by ronamosa** [comment]
Apologies for the late update - but I've re-tested and can confirm AAD and v1.19.0 work as expected (as per above) now. Thanks!
