### ISSUE TITLE
Using Terraform to create an AKS cluster with "SystemAssigned" identity and aci_connector_linux profile enabled does not result in a creation of a virtual node

### ISSUE THREAD

**Issue by borkod** [Azure/AKS#1894]
**What happened**:

Using Terraform to create an AKS cluster with "SystemAssigned" identity and aci_connector_linux profile enabled does not result in a creation of a virtual node (ACI) 

**What you expected to happen**:

I would expect a virtual node to be created.

**How to reproduce it (as minimally and precisely as possible)**:

Terraform code used:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "${var.prefix}-k8s-rg"
  location = var.location
}

resource "azurerm_virtual_network" "example" {
  name                = "${var.prefix}-vnet"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.10.0.0/16"]
}

resource "azurerm_subnet" "example-nodepool" {
  name                 = "default"
  virtual_network_name = azurerm_virtual_network.example.name
  resource_group_name  = azurerm_resource_group.example.name
  address_prefixes     = ["10.10.1.0/24"]
}

resource "azurerm_subnet" "example-aci" {
  name                 = "aci"
  virtual_network_name = azurerm_virtual_network.example.name
  resource_group_name  = azurerm_resource_group.example.name
  address_prefixes     = ["10.10.3.0/24"]

  delegation {
    name = "aciDelegation"
    service_delegation {
      name    = "Microsoft.ContainerInstance/containerGroups"
      actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
    }
  }
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "${var.prefix}-k8s"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "${var.prefix}-k8s"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_DS2_v2"
    vnet_subnet_id = azurerm_subnet.example-nodepool.id
  }

  network_profile {
    network_plugin = "azure"
    network_policy = "azure"
    load_balancer_sku = "standard"
  }

  identity {
    type = "SystemAssigned"
  }

  addon_profile {
    aci_connector_linux {
      enabled = true
      subnet_name = azurerm_subnet.example-aci.name
    }

    azure_policy {
      enabled = false
    }

    http_application_routing {
      enabled = false
    }

    kube_dashboard {
      enabled = true
    }

    oms_agent {
      enabled = false
    }
  }
} 
```

**Anything else we need to know?**:

When I provision an AKS cluster via portal, a virtual node gets provisioned automatically, hence I expected similar behavior when using Terraform. I tried deploying an app to the cluster targeting a virtual node (similar to this tutorial https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-portal) but the app never gets scheduled since no virtual nodes are available.

When provisioning via portal and inspecting the permissions and generated ARM templates, AKS service seems to:

- assign network contributor role to the default node pool subnet to principal ID [reference(parameters('resourceName')).identityProfile.kubeletidentity.objectId]
- assign network contributor tole to the ACI Virtual Node subnet to principal ID [reference(parameters('resourceName')).addonProfiles.aciConnectorLinux.identity.objectId]"

Both "Kubelet Identity" and "ACI Connector Linux Identity" are different than the system assigned identity of the AKS.

I suspect that when using Terraform and "SystemAssigned" identity, AKS service correctly assigns the kubelet identity to the node pool subnet. However, when using Terraform with the ACI addon, AKS service for some reason does not correctly generate or assign the second role assignment on the ACI Virtual Node subnet.

I asked about this issue in Terraform Slack channel. They seem to think this is a AKS configuration issue and pointed me here.

**Comment by yangl900** [comment]
@norshtein have you heard similar report?

**Comment by yangl900** [comment]
@borkod could you grant the addon identity permission to your vnet and see if that works?

words from @norshtein 

Background: for aci connector to normally run, network contributor role at vnet scope is needed for virtual node addon's identity.

In the terraform template provided, the vnet used for aci connector is customer provided so it is not in node resource group. AKS only grant contributor role at scope node resource group to addon's identity, as the vnet is not in node resource group, so it does not inherit the permission. When customer create the cluster using Microsoft-provided client, including Azure poral and Azure CLI, if the vnet is outside of node resource group, the network contributor role permission will be granted after the cluster is created. However, seems for terraform, it doesn't grant the permission so aci-connector can't run correctly.

**Comment by borkod** [comment]
Thank you for the suggestions.

> could you grant the addon identity permission to your vnet and see if that works?

How am I supposed to do that? Terraform script creates an AKS cluster with "SystemAssigned" identity. I don't think these types of identities are visible in AD's app registration. When I look at the export template of the AKS service that gets provisioned, there is an identity for the managed cluster resource and a "kubeletidentity" under "identityProfile".  I can't find any ACI connector identity in the export template. Terraform AKS resource doesn't expose ACI connector identity in its [attributes](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#attributes-reference) neither. I don't see any way to find out the identity of the aci connector.  Or is there another way to retrieve this identity I am not aware of?

> the vnet used for aci connector is customer provided so it is not in node resource group

Isn't this is going to be true in **every case**?  In order to create an AKS you require a VNET that already exists. You specify this VNet when you create AKS service. Then, AKS service creates a **new** resource group for the VMSS nodes.  Therefore, VMSS nodes will **always** be in a different resource group than the vnet resource group.  Am I missing something here? I know there is a feature to specify the resource group for the nodes, but that's currently in preview.

> seems for terraform, it doesn't grant the permission so aci-connector can't run correctly

That seems to be the case. But is this an issue with the way AKS service api's are implemented and how AKS service provisions SystemAssigned identities and assigns roles? Or is in an issue with how terraform AKS provider resource is implemented? Or does the Terraform AKS resource need to expose ACI connector identity as an attribute so that role assignment can be performed using terraform role assignment resource?

Thanks!

**Comment by geertn** [comment]
Regular user, just chipping in here: using an ARM template it's possible to export the identity using the `properties.addonProfiles.aciconnectorlinux.identity.objectId` so I expect it needs to be implemented for the AKS provider. I'm currently using this workaround:

```
data "azuread_service_principal" "aks-aci_identity" {
  display_name = "aciconnectorlinux-${azurerm_kubernetes_cluster.aks.name}"
  depends_on   = [azurerm_kubernetes_cluster.aks]
}

resource "azurerm_role_assignment" "aks-aci-vnet-assignment" {
  scope                = var.vnet_id
  role_definition_name = "Reader"
  principal_id         = data.azuread_service_principal.aks-aci_identity.id
}

resource "azurerm_role_assignment" "aks-aci-subnet-assignment" {
  scope                = var.aci01-subnet_id
  role_definition_name = "Network Contributor"
  principal_id         = data.azuread_service_principal.aks-aci_identity.id
}

```

**Comment by piotrgwiazda** [comment]
I've tried this, but this does not work. No errors anywhere, but the virtual node pool is not created. 

```
resource "azurerm_role_assignment" "vnet_permissions" {
  principal_id         = azurerm_kubernetes_cluster.k8s_cluster.identity[0].principal_id
  scope                = azurerm_virtual_network.this.id
  role_definition_name = "Contributor"
}
```

**Comment by geertn** [comment]
You need this, not the id of the AKS MI

```
data "azuread_service_principal" "aks-aci_identity" {
  display_name = "aciconnectorlinux-${azurerm_kubernetes_cluster.aks.name}"
  depends_on   = [azurerm_kubernetes_cluster.aks]
}
```

**Comment by piotrgwiazda** [comment]
Tried te above with no luck, now trying:
```
data "azurerm_user_assigned_identity" "aks-aci_identity" {
  name = "aciconnectorlinux-${azurerm_kubernetes_cluster.k8s_cluster.name}"
  resource_group_name = azurerm_kubernetes_cluster.k8s_cluster.node_resource_group
}

resource "azurerm_role_assignment" "vnet_permissions_aci" {
  principal_id         = data.azurerm_user_assigned_identity.aks-aci_identity.principal_id
  scope                = azurerm_virtual_network.this.id
  role_definition_name = "Contributor"
}
```

**Comment by FilBot3** [comment]
So, something like this won't work?
* https://gist.github.com/FilBot3/339a98c05f99a407b60c6d35848d700d#file-main-tf-L677-L687

```hcl
resource "azurerm_role_assignment" "aks_pods_to_subnet" {
  # Assign the AKS Kublet Identity the Network Contributor Role so that the
  # Worker nodes can assign IP's to the Pods.
  scope                = azurerm_subnet.coder_pods.id
  role_definition_name = "Network Contributor"
  principal_id         = azurerm_kubernetes_cluster.coder.kubelet_identity[0].object_id

  depends_on = [
    null_resource.wait_for_aks_appgw
  ]
}

I need to use a data resource to pull the information out of AAD for the AKS System Assigned Identity?
```

**Comment by Sviatik** [comment]
> So, something like this won't work?
> 
> * https://gist.github.com/FilBot3/339a98c05f99a407b60c6d35848d700d#file-main-tf-L677-L687
> 
> ```terraform
> resource "azurerm_role_assignment" "aks_pods_to_subnet" {
>   # Assign the AKS Kublet Identity the Network Contributor Role so that the
>   # Worker nodes can assign IP's to the Pods.
>   scope                = azurerm_subnet.coder_pods.id
>   role_definition_name = "Network Contributor"
>   principal_id         = azurerm_kubernetes_cluster.coder.kubelet_identity[0].object_id
> 
>   depends_on = [
>     null_resource.wait_for_aks_appgw
>   ]
> }
> 
> I need to use a data resource to pull the information out of AAD for the AKS System Assigned Identity?
> ```

I just tried and no, It doesn't work.
Looks like ACI create a separate Manage identity which doesn't appear in TF state. 

So currently only one way to pull that id using `data`
