### ISSUE TITLE
Using another AAD tenant than the tenant the AKS cluster is to authenticate with AKS fails with "InvalidAuthenticationTokenTenant".

### ISSUE THREAD

**Issue by ams0** [Azure/AKS#1895]
**What happened**:

Using another AAD tenant than the tenant the AKS cluster is to authenticate with AKS fails with "InvalidAuthenticationTokenTenant". 

**What you expected to happen**:

I used to be able to spin up an AKS cluster in a sub in a tenant, and keep the AAD authentication (users/groups) in another tenant. This seems not be working anymore with the new AAD authentication:

`az aks create ... --enable-aad --aad-tenant-id <tenantB> -aad-admin-group-object-ids <group in tenant B>`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I am aware of https://github.com/Azure/AKS/issues/1891#issuecomment-706133644, at first I tried with 1.19 but the issue is reported for 1.17.11

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.11
- Size of cluster (how many worker nodes are in the cluster?): 2 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

log:

```
$> kgno
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CDWL5UB6F to authenticate.
Error from server (Forbidden): nodes is forbidden: User "alessandro@cookingwithazure.com" cannot list resource "nodes" in API group "" at the cluster scope: request /subscriptions/<sub_in_tenantA>/resourceGroups/k8s/providers/Microsoft.ContainerService/managedClusters/playground2/providers/Microsoft.Authorization/checkaccess failed with status code: 401 and response: {"error":{"code":"InvalidAuthenticationTokenTenant","message":"The access token is from the wrong issuer 'https://sts.windows.net/<tenantB>'. It must match one of the tenants 'https://sts.windows.net/<tenantC>/,https://sts.windows.net/<tenantA>/' associated with this subscription. Please use any authority (URL) from 'https://login.windows.net/<tenantC>,https://login.windows.net/<tenantA>' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later."}}
```

**Comment by palma21** [comment]
Your error seems to indicate that on top of the command you also enabled `--enable-azure-rbac` ?

Managed AAD works across tenant, but Azure RBAC for k8s Authz does not. 
See linked docs issue and the docs page for that.

Could you confirm?

**Comment by ams0** [comment]
it worked with `--enable-managed-identity`, closing
