### ISSUE TITLE
External DNS managed addon

### ISSUE THREAD

**Issue by tkinz27** [Azure/AKS#1897]
ExternalDNS is a very common project to install in a kubernetes cluster for automatically managing DNS entries for ingress objects in the cluster. It would be really nice to not have to install this manually myself.

Be nice if the managed addon could support multiple dns zones too.

**Comment by qpetraroia** [comment]
Hi @tkinz27,

Have you taken a look at [Http Application Routing](https://docs.microsoft.com/en-us/azure/aks/http-application-routing#:~:text=The%20HTTP%20application%20routing%20solution%20makes%20it%20easy,creates%20publicly%20accessible%20DNS%20names%20for%20application%20endpoints.)? You can easily add it to your cluster giving it the following command 

`az aks enable-addons --resource-group myResourceGroup --name myAKSCluster --addons http_application_routing`

 However, it is not currently recommended for production use. If you have any more questions, please feel free to ask.

Thanks!

**Comment by tkinz27** [comment]
I was using the Application Gateway Ingress Controller since http application routing is not suggested for production.

**Comment by palma21** [comment]
Sounds like a nice feature request for App GW ingress controller! 

Mind opening it here as well: 
https://github.com/Azure/application-gateway-kubernetes-ingress

**Comment by tkinz27** [comment]
External DNS works with all ingress controllers though, not just the AGIC. It also works with load balancer services. Why restrict the service to just those specific ingress controllers?

**Comment by palma21** [comment]
Definitely not restricted to those! But it should be part of one of the supported addons to be a supported and managed component, or otherwise it would be just an installer aka the same as a self install.

**Comment by SatyKrish** [comment]
External-DNS can now be installed as AKS add-on using [Web Application Routing solution (preview)](https://docs.microsoft.com/en-us/azure/aks/web-app-routing)

> The add-on deploys two components: an [nginx ingress controller](https://kubernetes.github.io/ingress-nginx/), and [External-DNS](https://github.com/kubernetes-incubator/external-dns) controller.

However, External-DNS controller lacks support for `Azure Private DNS Zone`. This is a must for resolving internal facing ingress endpoint.

**Comment by sabbour** [comment]
The App routing add-on supports public and private DNS zones through external-dns.

**Comment by SatyKrish** [comment]
Private DNS zone integration works. Thanks !
