### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by ramonduraes** [Azure/AKS#19]
I'm trying to create a new AKS. However you are presenting an error below.
az aks create -g rgrdaks -n rdaks --generate-ssh-keys --agent-count 1

Error:
Deployment failed. Correlation ID: 61b0ff88-a742-4718-ab08-7fe0329a9f8e. getAndWaitForManagedClusterProvisioningState error: <nil>

**Comment by alexquintero** [comment]
I am also getting the same error.

**Comment by berndverst** [comment]
@ramonduraes @alexquintero are you seeing this in westus2 or westuk?
I'm also experiencing this in westus2.

**Comment by Aamir-Meman** [comment]
I am experiencing the same issue is any update on it .

**Comment by aumanjoa** [comment]
same issue!

**Comment by berndverst** [comment]
Can you all delete the related resource group, create a new one un WestUS2 and try creating a AKS cluster again? I just successfully did so.

**Comment by aumanjoa** [comment]
Yes worked again for me but this needs to be much more stable

**Comment by ramonduraes** [comment]
Now I have this error. I deleted all items but he did not clear the history.

Public preview limit of 5 for managed cluster(AKS) has been reached for subscription 'abc'  in location westus2. Please try deleting one or more managed cluster resources in this location before trying to create a new cluster or try a different Azure location.

**Comment by somyagarg94** [comment]
I am trying upgrade the default cluster version (1.7.7) to 1.8.2 in WEST US 2.
I am getting the same error: 
Deployment failed. Correlation ID: b37306dd-bf93-4355-8e59-14c02e494c50. getAndWaitForManagedClusterProvisioningState error: <nil>

**Comment by ramonduraes** [comment]
now
Changing property 'servicePrincipalProfile.clientId' is not allowed.

**Comment by slack** [comment]
Sorry this issue became stale. I'm going to close this out as we have shipped a number of fixes since the first few weeks of November.

Thanks for your patience during preview.
