### ISSUE TITLE
West Europe at capacity as of Feb 14, 2018

### ISSUE THREAD

**Issue by slack** [Azure/AKS#190]
Hello all, we are currently at the maximum number of AKS clusters for West Europe. Attempts to create new AKS clusters in this region will receive an error:
> Azure Container Service is unable to provision an AKS cluster in westeurope, due to an operational threshold. Please try again later or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md

The team is building out additional cluster capacity and will update this issue when we are ready for new clusters.

**Comment by kieranross** [comment]
Is this still an issue?

**Comment by slack** [comment]
We built out new clusters on Friday afternoon, time for a few more over the long weekend. We currently have room!

**Comment by cmendible** [comment]
We just created a cluster without issues...

**Comment by slack** [comment]
We've been clear in West Europe for a few days. Closing this bad Larry!

**Comment by Praxiss** [comment]
Cant increase nodes on cluster I have running (using default VM type)
Cant create new cluster in westeurope - presumably capacity issues with default VM type
Created cluster with alternative VM type (A series), but cant upgrade K8s version - says VM type not allowed in my region. Again presumably capacity issues

**Comment by olileger** [comment]
@slack could you please precise whether it's an issue related to the AKS cluster management capacity or related to the underlying VM capacity ?
Thanks
Olivier
