### ISSUE TITLE
No system node pool by default when use az aks create command ; MODE argument missing

### ISSUE THREAD

**Issue by Karadiavinay** [Azure/AKS#1900]
**Where I did the testing**
On Azure portal with below configuration 
```hcl
user@Azure:~$ az version
{
  "azure-cli": "2.13.0",
  "azure-cli-core": "2.13.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.4",
    "aks-preview": "0.4.24"
  }
}
```

**What happened**:
Used below command to create an aks cluster with the assumption that it will create a default system node pool as mention on the Azure Documents [here](https://docs.microsoft.com/en-us/azure/aks/use-system-pools#create-a-new-aks-cluster-with-a-system-node-pool) 
```hcl
#wus = westus2 
az aks create -g test-aks-rg --name test-aks-wus-01 --node-count 1 --generate-ssh-keys
```

**What you expected to happen**:
Got a nodepool with **no mode argument** in description
 `az aks show -g test-aks-rg  -n nodepool1 --name test-aks-wus-01  -o jsonc`

```hcl
   ...
  "agentPoolProfiles": [
    {
      "availabilityZones": null,
      "count": 1,
      "enableAutoScaling": null,
      "enableNodePublicIp": null,
      "maxCount": null,
      "maxPods": 110,
      "minCount": null,
      "name": "nodepool1",
      "nodeTaints": null,
      "orchestratorVersion": "1.17.11",
      "osDiskSizeGb": 128,
      "osType": "Linux",
      "provisioningState": "Succeeded",
      "scaleSetEvictionPolicy": null,
      "scaleSetPriority": null,
      "type": "VirtualMachineScaleSets",
      "vmSize": "Standard_DS2_v2"
    }
],
...
```

**How to reproduce it (as minimally and precisely as possible)**:
Apply same command as describe [here](https://docs.microsoft.com/en-us/azure/aks/use-system-pools#create-a-new-aks-cluster-with-a-system-node-pool)

**Anything else we need to know?**:

**I tried to add Node pool with separate command as below**
```hcl
az aks nodepool add \
    --resource-group test-aks-rg \
    --cluster-name test-aks-wus-01 \
    --name systempool \
    --node-count 1 \
    --node-taints CriticalAddonsOnly=true:NoSchedule \
    --mode System 
```
*Expected response*
A new system node pool should be added to existing aks cluster

*Actual Response = ERROR*
`UnrecognizedArgumentError: unrecognized arguments: --mode System`

**Environment**:
- Kubernetes version (use `kubectl version`):  
```hcl
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean"
, BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean
", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?) `1`

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

- Others:

**Comment by sybrenromer** [comment]
I had the same problem last week and couldn't find anything that could be wrong.

Then I uninstalled the AKS-preview extension from azure-cli and the command worked again.

**Comment by palma21** [comment]
Yes, this usually would mean a too old version of the CLI or CLI extension that is using an older version of the API.

Let us take a note to add the minimum extension version to that doc as well. cc @jluk , @zr-msft
