### ISSUE TITLE
Bring your own identity with ACR pull

### ISSUE THREAD

**Issue by adhodgson1** [Azure/AKS#1901]
Based on [this](https://docs.microsoft.com/en-us/azure/aks/use-managed-identity) webpage, it states that bring your own user identity for the agent pool in AKS for ACR pulls is not currently supported. Is this a planned feature, and if so will it be part of the current BYO user identity that works for the control plane?

**Comment by miwithro** [comment]
We have this feature planned for Nov of this year.  BYO User Identity is planned for this month, and BYO kubelet is Nov.

**Comment by palma21** [comment]
dup from #1955
