### ISSUE TITLE
Is there a version/date for when Docker as a container runtime will be deprecated?

### ISSUE THREAD

**Issue by devteng** [Azure/AKS#1902]
We are using Docker-in-Docker on Kubernetes to build our images and we saw that the default will be set to Containerd for AKS 1.19. Is there a final AKS version that ContainerRuntime=docker will stop working? It takes time for some companies to switch their Docker building workflow over and would be great if there is a timeline.

Also, are there guidance for customer using Docker and AKS to build Docker images to switch over to an alternative? Preferably buildx.

**Comment by palma21** [comment]
After Containerd GA in November all versions v1.19+ will default to containerd, so all new clusters created or upgraded to 1.19+ will only use containerd and not have access to dockerd. 

Kubernetes 1.18 (the latest before 1.19) still has a 6month+ lifecycle as of today. We hope this provides enough time for folks to be able to drop DinD or Docker sockets in favor of solutions like buildx (that, together with acr build is what we recommend indeed)
https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#containerd-limitationsdifferences
