### ISSUE TITLE
Multi nodepool changes for load balancer

### ISSUE THREAD

**Issue by audunsolemdal** [Azure/AKS#1907]
**What happened**:
https://github.com/Azure/AKS/releases/tag/2020-07-27

```
We've added additional validations to prevent the creation of multiple node pool clusters with Basic Load Balancer which isn't supported.
```

```
ValidationError: Operation failed with status: 'Bad Request'. Details: Basic load balancers are not supported with multiple node pools. Create a cluster with standard load balancer selected to use multiple node pools, learn more at aka.ms/aks/nodepools.
```

**What you expected to happen**:

What exactly is the bug here? I've used multiple nodepools with success in the past with the basic sku load balancer.

Now you are causing me a headache because to use multiple nodepools again I have to

A) Have to recreate my prod cluster because load balancer sku cannot be updated
B) Since standard load balancer sku doesn't support my static basic sku PIPs I need to get new PIPs
C) Other teams need to ensure firewall rules are in place for the new IP

And the basic load balancer was the old default...

Is there no way to make you reconsider having this as optional for multiple node pools?

**Environment**:

AKS 1.18.8
API version  2020-09-01

**Comment by zhiweiv** [comment]
Please also see https://github.com/Azure/AKS/issues/1888.

**Comment by palma21** [comment]
Multiple nodepools and BLB were never supported, the fact they were possible of being created was an issue/bug.

The issue is that BLB simply does not support load balancing across multiple VMSS, it only supports 1. The only reason some scenarios still "work" is because the LB traffic would always land on the first vmss and then k8s would route it to the other pools. But this has uncountable edge cases from network polices breaking, to upgrades failing, etc.

**Comment by audunsolemdal** [comment]
Fair enough, I see the issue. 

My use case was typically to create an extra node pool  whenever I needed to (manually) start long running operations (e.g. copy files from blob storage to a PV). In such cases I would typically use another nodepool with VMs of another SKU to get better IOPS.

Also to test new features, e.g. Gen 2 VMs, Ephemeral  OS. A sort of sandbox without the need to route to actual services.

**Comment by palma21** [comment]
Would you be open to migrate to SLB in the near future?
We're planning on providing a feature to simplify that migration soon. That should enabled you to play with multiple nodepools at will (those scenarios make total sense for multiple nodepools)

**Comment by audunsolemdal** [comment]
That would be great, also if you could support upgrade of PIP from basic to to standard SKU.

**Comment by palma21** [comment]
Unfortunately migrating/maintaining the PIP is something that is out of our control, but it's a request I know the LB team is looking at.
