### ISSUE TITLE
Node pools set to 0 do not get upgraded when rolling cluster-wide AKS upgrade

### ISSUE THREAD

**Issue by marcjimz** [Azure/AKS#1908]
**What happened**: Hi all - we're noticing that for node pools set to a scaleset of 0, when we run an upgrade to a later version of Kubernetes that the node pool does not upgrade itself.

**What you expected to happen**: We expect the node pool to upgrade without manual intervention. Instead, we have to scale the node pool up to 1 OR delete the node pool and recreate it to have the proper version

**How to reproduce it (as minimally and precisely as possible)**: Scale a node pool to 0, then upgrade your AKS cluster. We have confirmed this across multiple env.
 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.10
- Size of cluster (how many worker nodes are in the cluster?) 30 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) HTTP microservices, machine learning
- Others:

**Comment by paulgmiller** [comment]
Upgrading a 0 node agentpool _should_ work from mc or agentpool. I'm unable to repro locally with my own cluster. 
Is this vmss or vmas? (I didn't think vmas could scale to zero but you did say "scaleset"). 
Would you be willing to share a clusters fqdn and time of the operation that didn't upgrade it?

**Comment by marcjimz** [comment]
pzi-gxus-n-ailabs-aks-d002-c47a4062.hcp.eastus.azmk8s.io @ 10/13 9PM EST

**Comment by palma21** [comment]
Thanks @marcjimz deleted the comment just to avoid having the FQDN stay here. We're looking into it.

**Comment by paulgmiller** [comment]
Looks like this came in through azure portal we see 4 requests. 1 for the cluster to just update controlplane . Then 3 each agentpool. This might be a problem in the portal calling code. Trying to confirm. If you can confirm the operation was kicked off  from portal that would help.

**Comment by marcjimz** [comment]
@paulgmiller correct, we typically do AZ CLI but this was one done via the portal.

**Comment by marcjimz** [comment]
> Thanks @marcjimz deleted the comment just to avoid having the FQDN stay here. We're looking into it.

Thanks!

**Comment by jenetlan** [comment]
Thanks for the information - we'll look into the portal experience and I'll update here with what we find.

**Comment by paulgmiller** [comment]
So it seems from our instrumentation in the portal you initiated
1) An upgrade of the cluster control plane
2) Upgrades of 3/4 of the agentpools but not the agentpool with 0 nodes. 

Maybe the UI/docs aren't clear that #1 won't upgrade any node pools regardless of size?  There are valid reasons for a customer not to upgrade a nodepool.

**Comment by marcjimz** [comment]
@paulgmiller we can't upgrade the node pool, after selecting upgrade:

![Uploading image.png…]()

**Comment by marcjimz** [comment]
@paulgmiller upgrading  to 1.16 is not an option

![Uploading Screen Shot 2020-10-21 at 6.18.09 PM.png…]()

**Comment by paulgmiller** [comment]
Ack thanks that seems like a bug and we're looking

**Comment by palma21** [comment]
@marcjimz we're not being able to repro in different clusters. Do you mind either capturing a network trace on your browser and/or open a support ticket? (instructions below)

**Comment by jabbera** [comment]
I did an upgrade via arm template from 1.20.2 to 1.20.5 and did not have this issue.

**Comment by paulgmiller** [comment]
Yes this should actually be handled for a couple months now in vmss by
upgrading just the model.
