### ISSUE TITLE
Networking model for AKS 

### ISSUE THREAD

**Issue by sukrit007** [Azure/AKS#191]
What networking model is used to establish inter pod communication?  Does it support encryption (like IPSEC) and is it something that can be configured?

**Comment by dstrebel** [comment]
Currently uses Kubenet, but will have Azure CNI available at some point.

**Comment by bergerx** [comment]
I was reading AKS documentation expecting to find some notes about cluster networking implementation of AKS, but there is none. Is it possible to add some docs about this.
