### ISSUE TITLE
Get cluster-autoscaler elements with kubectl

### ISSUE THREAD

**Issue by alk-rniveau** [Azure/AKS#1910]
**What happened**:

Based on this example https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-aks.yaml, it seems when we enable cluster-autoscaler, some elements are created within the cluster.

Currently, I can only get the config map and watch events. I would like to know if it's possible to get other elements with kubectl (I can't see nothing)

**What you expected to happen**:

Have a vision about pod or other elements which compose the cluster-autoscaler. 

**Environment**:
- Kubernetes version: v1.18.8
- Size of cluster: 10 nodes / 3 nodes pool (test cluster)

**Comment by marwanad** [comment]
@alk-rniveau the deployment you linked is for running your own (unmanaged) cluster-autoscaler in an AKS cluster. In the managed autoscaler case which you enable via `--enable-cluster-autoscaler` in CLI or `enableAutoScaling` in ARM templates - the only applicable resource you can view in your cluster is the configmap that gets created.

**Comment by alk-rniveau** [comment]
Thanks for your answer but here is my issue:

I would like to pause the CA during some periods as we can see here https://github.com/hellofresh/eks-rolling-update/ (yes it's for eks).

Why can't we watch deployment with the managed solution ?

**Comment by marwanad** [comment]
@alk-rniveau it seems that this assumes the existence of cluster autoscaler in your cluster. With the managed solution, the actual autoscaling component .

Some alternatives you can consider:
- Simply disable autoscaler during those periods `az aks nodepool --disable-cluster-autoscaler`
- Use the [autoscaler profile](https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler#using-the-autoscaler-profile) to set a really long value for `scan-interval` in seconds.

I'm interested in your use-case, what's your use case? Are you trying to prevent scale down? If so, we can expose another parameter that allows you to disable scale down completely.

**Comment by alk-rniveau** [comment]
My use case is the following:

Sometime I redeploy many deployments in the same time. This manipulation can cause a useless scaleup node. This is useless because once the burn phase is over (after the deployment), this node is scaled down.

It's not a load from bigger usage of the platform, but just due to the max surge behavior.

**Comment by marwanad** [comment]
@alk-rniveau would setting `new-pod-scale-up` delay overcome that case for you then? This basically says "wait until pods are x age old" before considering a scale-up.

**Comment by alk-rniveau** [comment]
this parameter is not is the doc https://github.com/Azure/AKS/issues/1716.
Sad :( 
Do you know if terraform provider will be updated ? https://github.com/terraform-providers/terraform-provider-azurerm

**Comment by marwanad** [comment]
Following up on the doc update now.

For the Terraform provider, it's better to open up an issue there. The Go SDK for the September API should be available and ready to consume by Terraform.
