### ISSUE TITLE
Multiple nodepool creation/removal

### ISSUE THREAD

**Issue by t3mi** [Azure/AKS#1913]
**What happened**:
During creation/removal of multiple nodepools in parallel there is a probability of the failed deployment with next error from api:
```"The operation was overriden and canceled by a later operation <operation GUID>."```
There is no [limitation](https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#limitations) defined for how multiple nodepools can be added - sequentially or in parallel, except that multiple node pools can be specified at cluster creation time. Besides that API accepts multiple requests for creation of nodepool in the same cluster.

**What you expected to happen**:
All nodepools creation should finish successfully or, in case nodepool creation should happen sequentially, please add appropriate limitation in the docs and place some blocking logic in the API level to not accept requests for additional nodepools until one is in the working queue.

**How to reproduce it (as minimally and precisely as possible)**:
[terraform-provider-azurerm #8906](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8906#issue-722660474)

**Anything else we need to know?**:
It could happen even with addition of 2 nodepools at the same time though the probability to catch the error would be lower in such case.

**Environment**:
- Kubernetes version (use `kubectl version`):
Kubernetes version 1.7.11
- Size of cluster (how many worker nodes are in the cluster?)
Spot node pools VMSS based with counts set to: min=0, max=1

**Comment by yangl900** [comment]
hi @t3mi , thanks for reporting the issue! This is a bug in AKS. We are fixing it and expect release in next a few weeks.

**Comment by thpang** [comment]
@yangl900 any updates on this one?

**Comment by thpang** [comment]
So this is really starting to become an issue, now especially on the create side of things which has not been the case until around 11.09.2020. Is there any progress on this one?

**Comment by yangl900** [comment]
Hi @thpang ,

Sorry for the late. The fix was merged on Nov 2nd and it is part of AKS 20201109 release. It is rolling out right now and will complete in all regions by end of next week.
