### ISSUE TITLE
Feature request : Display number of objects in resource view

### ISSUE THREAD

**Issue by NileshGule** [Azure/AKS#1915]
**What happened**:
The Resource View shows different objects in the AKS cluster example pods, deployments etc.
**What you expected to happen**:
It is better to show the number of objects (object count)
**How to reproduce it (as minimally and precisely as possible)**:
NA

**Anything else we need to know?**:
Attached is the screenshot of the similar feature available in Octant
![Pod numbers](https://user-images.githubusercontent.com/1298374/96748867-b851ff80-13fc-11eb-958d-3de28b448ed1.jpg)

**Comment by palma21** [comment]
Hi @NileshGule thanks for reaching out. I'm not sure I fully understood so allow me to ask a clarification. The Resource view should have a similar UX (pasting my example below (those are all my pods), which it seems is the same octant is doing.

Is the ask about allowing you to specify the number o pods (or other objects) per page? (and pagination)

![image](https://user-images.githubusercontent.com/7065724/97056593-31a53b80-153e-11eb-879a-dc95f0b9df12.png)

**Comment by NileshGule** [comment]
@palma21 Yes, the ask is to display the total number of objects e.g. 33 pods in my case. Pagination would also be good to have. The current resource view UI just lists the objects but there is no indicator of how many objects are there in the list.

**Comment by palma21** [comment]
Gotcha, makes sense. We've added it to the roadmap.

**Comment by phealy** [comment]
@akshaysngupta @mscatyao Could you please provide any update that you might have on this feature request?
