### ISSUE TITLE
Deploy AKS on Azure Dedicated Hosts

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#1916]
Ability to deploy AKS on https://docs.microsoft.com/en-us/azure/aks/use-azure-dedicated-hosts

**Comment by SeryioGonzalez** [comment]
This feature will be requested for high security workloads

**Comment by bogdangrigg** [comment]
This might have been blocked by the lack of VMSS on Dedicated Hosts.
But this was released late last year, so at this point it seems like a simple change.
Would it be possible to get an update on this one?
