### ISSUE TITLE
[Feature] AAD Pod Identity as a managed AKS addon for Windows

### ISSUE THREAD

**Issue by keikhara** [Azure/AKS#1917]
It would be good to have built-in support for AAD Pod Identity for which we can opt-out during creation of AKS cluster on windows node pool. 

By doing that, we could :

Assign Azure AD identities to AKS instance and automatically register them inside the cluster
Browse the Azure portal to see which Azure AD identities are available inside the cluster

**Comment by zhiweiv** [comment]
Any ETA? We have looking for this feature a long time.

**Comment by tomkerkhove** [comment]
It is being tracked on https://github.com/Azure/AKS/issues/1480

**Comment by zhiweiv** [comment]
Seems there is no Windows support mentioned in #1480.

**Comment by tomkerkhove** [comment]
There is no Linux support mentioned as well :D

**Comment by miwithro** [comment]
We are doing a Private Preview right now of Azure AD Workload Identity which works on Windows.  We should be moving this to Public Preview in Q2 2022, and then looking at GA shortly thereafter.

**Comment by miwithro** [comment]
#1480 will work on both Windows and Linux as it is language specific and not OS specific.  Track this through 1480.
