### ISSUE TITLE
Multi-Attach error on rollout

### ISSUE THREAD

**Issue by marcbaque** [Azure/AKS#1919]
**What happened**:
We have a Kubernetes cluster deployed on AKS where a pod uses a PVC on Azure Disks.

The problem is that when we rollout a new image, the newly created pod tries to mount the pvc but it is still attached to the running one so it throws:

`Multi-Attach error for volume "pvc-*****" Volume is already used by pod(s)`

**What you expected to happen**:
It should manage correctly the rollout permitting to mount on the newly created pod.

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup a new deployment that uses a pvc with managed-premium Azure Disk
2. Rollout a new image to the same deployment

**Anything else we need to know?**:
No

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.13
- Size of cluster (how many worker nodes are in the cluster?): 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): HTTP microservices
- Others:

**Comment by andyzhangx** [comment]
that's be design

**Work around**:

When using disk PVC config in deployment, `maxSurge: 0` could make sure there would not be no more than two pods in `Running/ContainerCreating` state when doing rollingUpdate:
```
template:
...
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```

Refer to [Rolling Updates with Kubernetes Deployments](https://tachingchen.com/blog/kubernetes-rolling-update-with-deployment/) for more detailed rollingUpdate config, and you could find `maxSurge: 0` setting example [here](https://github.com/andyzhangx/demo/blob/c3199932c4c00ca1095481e845642a0ec4bda598/linux/azuredisk/attach-stress-test/deployment/deployment-azuredisk1.yaml#L45-L49)
