### ISSUE TITLE
Kube API is down, no network ingress or egress

### ISSUE THREAD

**Issue by logicfox** [Azure/AKS#192]
One of two clusters we run in the West Europe region appears to be down. There's no egress network traffic. kubectl commands and the proxy fail with the following error: `Unable to connect to the server: net/http: TLS handshake timeout`. The problem was spotted around 10:45 AM CET.

**Comment by taigi100** [comment]
Got the same issue.

**Comment by jasonchester** [comment]
was having the same an issue with aks cluster in  **centralus** around 10:15 EST

Issue appears to be resolved at 10:37 EST as I was entering this ticket.

**Comment by logicfox** [comment]
The issue isn't resolved in West Europe. My application on that AKS cluster is still unable to reach /.well-known/openid-configuration endpoint on Azure AD. The same endpoint is reachable on the other cluster.

**Comment by koalalorenzo** [comment]
Same issue here

**Comment by logicfox** [comment]
Any chance this will be looked into? How can we help? The kube-api is not responding, so I cannot get any details out of the cluster. There is no egress out of the network as we don't see any logs being aggregated in Log Analytics.

**Comment by logicfox** [comment]
Looks like they finally fixed that cluster after escalating a support ticket. The attending engineer mentioned that the `etcd` cluster was down.
