### ISSUE TITLE
[Issue when addon AGIC]

### ISSUE THREAD

**Issue by HeShaobo1** [Azure/AKS#1921]
Dear, 

I faced an issue when i need to addon my APPGW to AKS, refer to the article:https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-existing

it seems that the reason is that AKS-IngressApplicationGatewayAddon, you can refer to the issue : 

 [root@agicclient ~]# az aks enable-addons -n myCluster -g agicclient -a ingress-appgw --appgw-id /subscriptions/74e6d0b0-b200-4673-90b4-40aefa9d3e5c/resourceGroups/agicclient/providers/Microsoft.Network/applicationGateways/myApplicationGateway
The behavior of this command has been altered by the following extension: aks-preview
BadRequestError: Operation failed with status: 'Bad Request'. Details: IngressApplicationGateway addon is not allowed since feature 'Microsoft.ContainerService/AKS-IngressApplicationGatewayAddon' is not enabled. Please see https://aka.ms/aks/previews for how to enable features.
[root@agicclient ~]# az extension add --name aks
No matching extensions for 'aks'. Use --debug for more information.

So i checked the AKS-ingress addon, the problem should be :  

[root@agicclient ~]# az feature register --name AKS-IngressApplicationGatewayAddon --namespace microsoft.containerservice
Once the feature 'AKS-IngressApplicationGatewayAddon' is registered, invoking 'az provider register -n microsoft.containerservice' is required to get the change propagated
ResourceNotFoundError: The feature 'AKS-IngressApplicationGatewayAddon' could not be found.

So how can i contine to addoing this AKS-IngressApplicationGatewayAddon?

**Comment by mscatyao** [comment]
Hi @HeShaobo1 - can you confirm that you're using AppGW/AGIC in the public cloud?

**Comment by HeShaobo1** [comment]
HI mscatyao, this is in Azure China Cloud, located in China East/North 2.
