### ISSUE TITLE
Support Kubernetes Dashboard with AAD/RBAC enabled

### ISSUE THREAD

**Issue by markvr** [Azure/AKS#1925]
With reference to: https://github.com/kubernetes/ingress-nginx/issues/5654#issuecomment-674428819

AKS is deprecating use of the native Kubernetes Dashboard in favour of the Azure Portal.  However the native dashboard provides much greater functionality, and is much more familiar to Kubernetes users than the Azure Portal.

The dashboard can be installed manually (note I'm *not* referring to the managed kube-addon, just the native dashboard from upstream), but when configured using an OAuth ingress proxy, login fails, I think because because the token obtained from the proxy is issued by an AAD client that is different to the client used by the API server. 

Please support RBAC logins for the dashboard, the Azure Portal is nowhere near feature complete with the native dashboard, and I doubt it really could be.  The native dashboard is essential to debug and diagnose issues with clusters, e.g. by easily being able to exec into running containers to debug problems with them.

**Comment by weinong** [comment]
Please take a look at https://github.com/weinong/k8s-dashboard-with-aks-aad
