### ISSUE TITLE
Can't view metrics-server logs in log analysis 

### ISSUE THREAD

**Issue by di669** [Azure/AKS#1926]
**What happened**:

Is it possible to collect logs from the metric-server?

I got the Prometheus scrape config from here https://raw.githubusercontent.com/microsoft/Docker-Provider/ci_prod/kubernetes/container-azm-ms-agentconfig.yaml

I followed  https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-prometheus-integration and added 

```
Kubernetes_services = ["https://metrics-server.kube-system.svc.cluster.local/metrics"]
```
and applied to my cluster but I don't see the logs in the log analysis. I also did what was listed here https://github.com/Azure/AKS/issues/990#issuecomment-515796746 but that didn't work either

**What you expected to happen**:
metric_server logs would appear  in Log Analytics 

**How to reproduce it (as minimally and precisely as possible)**:

- Set up aks

- Enabled logging

- Download container-azm-ms-agentconfig.yaml and add in Kubernetes_services = ["https://metrics-server.kube-system.svc.cluster.local/metrics"]. Apply to cluster

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by saaror** [comment]
Are you referring to metric-server logs or metrics? If you are trying to scrape Prometheus metrics it is not going to cover logs, it is going to cover metrics.

**Comment by saaror** [comment]
@di669 are you still looking for help? If not we can close the issue.

**Comment by saaror** [comment]
Closing issue since we didnt receive any response. @di669 feel free to re-open the issue if you need any help.
