### ISSUE TITLE
NSG rule not created for LoadBalancer nginx-ingress-controller service

### ISSUE THREAD

**Issue by ohadschn** [Azure/AKS#1927]
**What happened**:
We installed [nginx-ingress](https://github.com/kubernetes/ingress-nginx), which adds a `nginx-ingress-controller` service of type `LoadBalancer` to the cluster. We can see the service is assigned a proper `EXTERNAL-IP`, but the corresponding NSG rule is not added to the NSG (the one with priority `500` and name like `a412lkjl4affe4e25944b68ae6085f89-TCP-443-Internet`). Looking at the Activity Log, it's not that AKS creates the rule and then it's being deleted/overwritten - AKS simply never creates it.

If I delete the service (`kubectl delete service nginx-ingress-controller`) and recreate it (`kubectl apply -f nginx-ingress-controller.yaml`) suddenly the NSG rule comes back. When I then look at the activity log, I indeed see AKS (via its assigned managed identity) creating the rule.

**What you expected to happen**:
The proper NSG rule should be created without me recreating the `LoadBalancer` service.

**How to reproduce it (as minimally and precisely as possible)**:
I'm not sure, we just deploy and sometimes it happens.

**Anything else we need to know?**:
1. We're provisioning the Public IP ourselves (via an ARM template), and passing its public IP to nginx-ingress via `controller.service.loadBalancerIP`.
1. We are running in an internal MS subscription (specifically we belong to Azure Storage Media & Edge), so _Azure Policy Governance_ periodically scans all NSGs (including the one created by AKS) and adds security rules (Simply Secure V1, with names like `NRMS-Rule-101`). So maybe this somehow confuses AKS, as it seems to consider "outside" rules as "taints" according to https://github.com/Azure/AKS/issues/570#issuecomment-411186514.
1. AKS diagnostics didn't report any issue
1. No error events reported by `kubectl get events --all-namespaces`

**Environment**:
- Kubernetes version (use `kubectl version`):
```json
{
   "Major":"1", 
   "Minor":"18", 
   "GitVersion":"v1.18.8", 
   "GitCommit":"9f2892aab98fe339f3bd70e3c470144299398ace", 
   "GitTreeState":"clean", 
   "BuildDate":"2020-08-14T00:06:38Z", 
   "GoVersion":"go1.13.15", 
   "Compiler":"gc", 
   "Platform":"linux/amd64"
}
```
- Size of cluster: **5 worker nodes**
- General description of workloads in the cluster: **HTTP microservices, ASP.NET Core (on .NET Core), linux**

**Comment by yangl900** [comment]
Hi @ohadschn , I suspect this is because there is another service in your cluster blocked k8s service reconcile loop. You can enable diagnostic settings of your cluster and get the k8s controller manager logs. From there you should be able to see why some times NSG was not updated. If you describe all services in all namespaces, you may be able to find the problematic service, it should have some failure events there.

**Comment by ohadschn** [comment]
Thanks @yangl900, we should have Azure Monitor diagnostics enabled, I'll check the controller manager logs.

As for the blocking service theory:
1. How would a different service exactly block the reconcile loop? Does it run forever? If not, how long does it take to time out?
1. I don't see any failure when I run `kubectl get events --all-namespaces`.
1. `nginx-ingress-controller` is the only `LoadBalancer` service we have.
1. When I recreate the above service the issue is resolved almost immediately, so not sure other services are involved.

**Comment by yangl900** [comment]
You can correlate the logs with code here: https://github.com/kubernetes/kubernetes/blob/4b65f70652849310ccaf443e480a9a3149c3b9dd/staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go#L165

From there you can see if a LB service is reconciled, NSG will be reconciled for sure. Given we don't see NSG reconciliation, likely the controller manager did not reconcile this service at all until you re-create it.
