### ISSUE TITLE
AAD integration with RBAC at GA

### ISSUE THREAD

**Issue by jasonkappel** [Azure/AKS#193]
Will there be AAD integration at GA?

**Comment by dstrebel** [comment]
AAD Authentication is slated for sometime in H1 2018, but not definitive for GA release.

**Comment by Mumrau** [comment]
Are we talking about the fact that the AAD users would be sort of percolated down into the AKS RBAC?

I'm just not sure I understood clearly what @jasonkappel suggested here, because this is a feature we'll be really looking forward to, the ability to give access at creation to the AD entities.

**Comment by DaveAurionix** [comment]
A little related: https://github.com/Azure/AKS/issues/397

**Comment by seanmck** [comment]
RBAC + AAD will be available very soon (within weeks)

**Comment by tomkerkhove** [comment]
It's there - https://docs.microsoft.com/en-us/azure/aks/aad-integration
