### ISSUE TITLE
AKS-managed AAD integration - cannot login

### ISSUE THREAD

**Issue by tkporter** [Azure/AKS#1930]
**What happened**: 

I followed [these instructions](https://docs.microsoft.com/en-us/azure/aks/managed-aad#upgrading-to-aks-managed-azure-ad-integration) to upgrade an existing AKS cluster to use the AKS-managed AAD integration, hoping to use that with RBAC on the cluster. I also followed [these instructions](https://docs.microsoft.com/en-us/azure/aks/azure-ad-rbac) to test out things working with RBAC.

I've created an AAD group that my account is a member of, and I created the appropriate `Role` and `RoleBinding` resources as described in [these instructions for using RBAC+AAD](https://docs.microsoft.com/en-us/azure/aks/azure-ad-rbac). I'm able to access the cluster just fine using the `-admin` kubectl context I got from running `az aks get-credentials ... --admin`. However, once I try to use the non-admin credentials from `az aks get-credentials ... --overwrite-existing` and a subsequent usage of `kubectl`, I'm able to log in using my browser and then in my terminal I'm hit with `error: You must be logged in to the server (Unauthorized)`. I've tried modifying the RoleBinding to apply to both the `Group` my AAD account is a part of and my account directly using `User`, and it doesn't work. Poking around, I found https://github.com/Azure/AKS/issues/478 and https://github.com/MicrosoftDocs/azure-docs/issues/10326, and both say that `Guest` users in AAD have issues, but `Member`s don't. My AAD user account is a `Guest`, so it feels like this may be the issue, but all documentation that previously mentioned that things don't work with `Guest`s seem to have been removed. Is this still the case?

**What you expected to happen**:

I'd expect to be able to run `kubectl` commands on the cluster that the `Role`/`RoleBinding` allows

**How to reproduce it (as minimally and precisely as possible)**:

(I haven't tried these exact steps, but this is essentially what I did)
* use Guest account on AAD
* add Guest account to an AAD group
* create cluster that has AKS-managed AAD integration enabled, set previously created AAD group as admin
* Set up Role/RoleBinding similar to [these instructions](https://docs.microsoft.com/en-us/azure/aks/azure-ad-rbac)
* `az aks get-credentials ... --overwrite-existing` and `kubectl get pods`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-dispatcher", GitCommit:"f5757a1dee5a89cc5e29cd7159076648bf21a02b", GitTreeState:"clean", BuildDate:"2020-02-06T03:31:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"ba1ce4122d67b0f7399a41afbbd8a7258d22ecb8", GitTreeState:"clean", BuildDate:"2020-04-21T00:13:25Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?) 5
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) small services that make http requests
- Others:

**Comment by JasonWhall** [comment]
@tkporter - it may be because AAD login using kubectl is [only valid for 1.18.1+ versions](https://github.com/Azure/AKS/issues/1806#issuecomment-675502889) of the kubectl client. Although this should probably be reflected in the docs...

**Comment by tkporter** [comment]
@JasonWhall that worked, thank you so much! It'd be great to see this added to the docs
