### ISSUE TITLE
Add support for priority based expander in cluster autoscaler

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/AKS#1931]
According to the [documentation](https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler#using-the-autoscaler-profile) AKS currently supports only: `most-pods`, `random`, `least-waste` values for expander.

It would be great to be able to pick `priority` and manually provide `kube-system/cluster-autoscaler-priority-expander` config map as described [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/readme.md).

This would be extremely useful for scenarios involving spot VMs.

**Comment by mkosieradzki** [comment]
The implementation can be done in two phases:
- *Preview*: Unblock the `priority` value
- *GA*: Update the tooling and ARM to automatically generate `cluster-autoscaler-priority-expander` config map

**Comment by marwanad** [comment]
That's in the plans :)

**Comment by 4c74356b41** [comment]
can this distinguish between spot\regular given they have the same SKU?

**Comment by marwanad** [comment]
@4c74356b41 the priority expander operations on nodepool names (via regex or similar) so you can make it fit your needs if your spot pools have different names

**Comment by 4c74356b41** [comment]
i tried it today and it didn't work, do you have a working example?

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    50:
      - spot
```

this didn't work and was scaling all the node pools (one called `agentpool`, other `spot`). I tried other regexes (spo*, ^spot, etc) it didn't work either @marwanad

**Comment by marwanad** [comment]
@4c74356b41 sorry I was unclear when I said "nodepool name". You need the full-name of the underlying VMSS so `aks-spot-vmss` for example.

**Comment by 4c74356b41** [comment]
sorry, still unclear. in the arm api pool name is data, in spot node name is `aks-spot-26893986-vmss000000`, in node labels `agentpool: spot`. none of these really match `aks-spot-xxx-vmss`. I can assume that the pool name from ARM api get appended with `aks-` and `-xxx-vmss` and I should ignore the trailing zeros (node number)? so I need to match `aks-spot*`?

**Comment by 4c74356b41** [comment]
btw, any ideas when az cli will support setting that property? right now it says something like `priority is not a valid option for autoscaler`.

**Comment by marwanad** [comment]
@4c74356b41 The nodegroup name should be `aks-spot-26893986-vmss` in that case, that's what your regex should be. You can use a wildcard on `aks-spot` too if you have spot1, spot2, etc pools.

I'll double check and let you know ETA for CLI.
