### ISSUE TITLE
Add support for price based expander in cluster autoscaler

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/AKS#1932]
This is related to #1931 and this can be used for spot-based scenarios without configuring additional config maps (in such a scenario).

According to the documentation AKS currently supports only: `most-pods`, `random`, `least-waste` values for expander.

It would be great to be able to pick `price` as described [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/pricing.md): however this requires a significant amount of work in `azure cloud provider` for `cluster autoscaler` first starting with providing price list from ARM API: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go#L109.

However #1931 is order of magnitude easier to implement as in minimal implementation it requires only unblocking the `priority` option and updating documentation.

This would be especially useful for scenarios involving spot VMs (but not only).

**Comment by marwanad** [comment]
I briefly looked at that option but the pricing model is tricky in Azure. It's not exposed via the SKU API and from my understanding, there's two APIS: Rate Card API (for pay as you-go) and Billing API (for enterprise customers). 

We also obviously don't want a static list of hardcoded prices in there. I'll keep this thread updated on progress in that space.
