### ISSUE TITLE
How do we use podNodeSelector

### ISSUE THREAD

**Issue by heyitsmemark** [Azure/AKS#1933]
I see in [Release 2020-10-19](https://github.com/Azure/AKS/releases/tag/2020-10-19)  that the podNodeSelector admission controller has been enabled in 1.19.  Is this available yet in the AKS managed service, and if so, how do I use it?

**Comment by xuto2** [comment]
Just create a 1.19 AKS cluster and use it like in any other k8s cluster. 
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#configuration-annotation-format
