### ISSUE TITLE
AGIC not working well after change the subscription to another directory

### ISSUE THREAD

**Issue by yishengcao** [Azure/AKS#1935]
**What happened**:
My service is on AKS over Application Gateway + AGIC. It was created following the guide of "AKS Add-On Greenfield Deployment".
It was working well until we switched the subscription to another directory recently. When we update the pods in the aks cluster, Application Gateway backend pool cannot be automatically update. Therefore, our website always report gateway error.
So, now, every time when we have a new release, I have to manually update the Application Gateway for backend pool to point to the new deployed pods' ipaddresses.

**What you expected to happen**:
After switch the subscription to a new directory, AGIC should still automatically update the Application Gateway whenever there has changes of aks cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Create aks cluster following the "AKS Add-On Greenfield Deployment", add your service in the cluster. 
Re-deploy your services, you will see AGIC handle the AppGateway configuration for you.
Then switch the subscription to a new directory. 
Re-deploy your services, you will see AGIC not working anymore.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.17.9
- Size of cluster (how many worker nodes are in the cluster?)
3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
HTTP microservices, Java app
- Others:

**Comment by akshaysngupta** [comment]
@yishengcao do you any errors in the AGIC logs ?

**Comment by yishengcao** [comment]
No, I didn't see the error logs, but I tried to create exactly the same one into another subscription, and compare with it, I found the Role assignments missing from the error subscription, which switched the directory.
