### ISSUE TITLE
1.18.10 is not available in US region

### ISSUE THREAD

**Issue by ramki88** [Azure/AKS#1936]
**What happened**:

1.18.10 is not available in West & East US regions which was released part of Release 2020-10-26

**Anything else we need to know?**:

1.18.10 is available in West Europe though

**Comment by tomkerkhove** [comment]
It's coming, you just have to wait a while.

As per https://github.com/Azure/AKS/releases/tag/2020-10-26:
> This release is rolling out to all regions - ETA for conclusion 2020-11-11

**Comment by yangl900** [comment]
@ramki88 we have a release freeze for US regions this week, it will resume from next Monday.

**Comment by ramki88** [comment]
@yangl900, thanks for the update..
