### ISSUE TITLE
Failed AKS deployment Status Conflict

### ISSUE THREAD

**Issue by mpk166** [Azure/AKS#1938]
Hi,

I'm trying to deploy a new AKS cluster using the azure portal but I'm getting this Conflict error. I tried deploying it in different region and new resource groups without any success. Not sure if this is related but problems started when wanted to add a IP address to authorized IP ranges to a test cluster which failed. After that I tried to recreate the entire cluster which now resulting in to this error.

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"InternalOperationError\",\r\n        \"message\": \"We are unable to serve this request due to an internal error, Correlation ID: 2ddf3a4f-fcc9-406b-a6f4-42f56f96af05, Operation ID: f2f12f3c-bb07-4e88-8e36-3d6eb3e33dee, Timestamp: 2020-11-03T08:32:35Z.\"\r\n      }\r\n    ]\r\n  }\r\n}"
    }
  ]
}

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"InternalOperationError\",\r\n        \"message\": \"We are unable to serve this request due to an internal error, Correlation ID: 4da3c4f1-7214-4ecc-9aab-4e106797dc00, Operation ID: 81a4d993-8d67-4436-956a-6af4ad5cab25, Timestamp: 2020-11-03T08:54:43Z.\"\r\n      }\r\n    ]\r\n  }\r\n}"
    }
  ]
}

**Comment by yangl900** [comment]
hi @mpk166 , sorry for the inconvenience. We are aware of the issue and a hotfix is rolling out right now. If you uncheck the "virtual node" option, you can get unblocked for now.
