### ISSUE TITLE
Patching and Update Management

### ISSUE THREAD

**Issue by jasonkappel** [Azure/AKS#194]
The currently deployed worker nodes are showing up as missing a series of patches.  Who will be responsible for doing those updates, us or the MS PG?

**Comment by dstrebel** [comment]
Azure automatically applies security patches to the nodes in your cluster on a nightly schedule. However, you are responsible for ensuring that nodes are rebooted as required. You have several options for performing node reboots:

Manually, through the Azure portal or the Azure CLI.
By upgrading your AKS cluster. Cluster upgrades automatically cordon and drain nodes, then bring them back up with the latest Ubuntu image. You can update the OS image on your nodes without changing Kubernetes versions by specifying the current cluster version in az aks upgrade.

Using Kured, an open-source reboot daemon for Kubernetes. Kured runs as a DaemonSet and monitors each node for the presence of a file indicating that a reboot is required. It then orchestrates those reboots across the cluster, following the same cordon and drain process described earlier.

**Comment by pjbgf** [comment]
@dstrebel That seems to cover pretty well the OS Level updates. What would be the recommended approach for security-patching for Kubelet, Docker and Kube-system pods?

**Comment by seanmck** [comment]
For those components, you will need to upgrade your cluster to new Kubernetes patch releases as they become available in AKS. Eventually, we intend to offer auto-upgrade for path releases, but it's not there yet.
