### ISSUE TITLE
Dapr Add-on

### ISSUE THREAD

**Issue by mchmarny** [Azure/AKS#1943]
AKS add on for Dapr (https://dapr.io/)

**Comment by tomkerkhove** [comment]
v1.0 is released - https://github.com/dapr/dapr/releases/tag/v1.0.0

Would be nice to have an official add-on for this.

Congrats @yaron2 & @msfussell with this release!

**Comment by PixelRobots** [comment]
Any update on GA?

**Comment by raghulmsft** [comment]
Here is the documentation to enable dapr on AKS! https://docs.microsoft.com/en-us/azure/aks/dapr
