### ISSUE TITLE
[Feature request] GPU driver customisation or default GPU driver installation

### ISSUE THREAD

**Issue by denniszielke** [Azure/AKS#1946]
We need the ability to customise the GPU driver installer.
In particular we want to provide custom nvidia installer parameters for
--install-compat32-libs 
--compat32-libdir=lib32
--x-module-path=
--kernel-source-path=

Maybe through the ability to bring a custom configmap with parameter values?

The driver installation cannot be updated easily if a driver is already installed. If customisation is not possible it would also help if we could get ab feature flag to a nodepool without installed drivers.

**Comment by phealy** [comment]
If you deploy your cluster onto a node type with GPUs but don't use the GPU VHD image for it, you will get a nodepool with GPUs but no drivers. At that point you can then [manually install the device plugin](https://docs.microsoft.com/en-us/azure/aks/gpu-cluster#:~:text=image-,manually%20install%20the%20nvidia%20device%20plugin,-Warning) and configure it as needed.
