### ISSUE TITLE
[Feature Request] IAM Service Principles to AKS Service Accounts

### ISSUE THREAD

**Issue by dhananjaya-senanayake** [Azure/AKS#1948]
**What happened**:
- AKS have no inbuilt feature to attach IAM service principles to k8s service accounts. 
- Since Azure Pod Identity relies on Instance metadata, its a security vulnerability and its not supported with Azure AKS Support. https://github.com/Azure/aad-pod-identity
- As per the Kubernetes security best practises guideline access to meta data should be limited. https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/#restricting-cloud-metadata-api-access. Only way to protect this is through network polices.

**What you expected to happen**:
- EKS has a cool feature which allows to bind a AWS IAM role to k8s service account https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
- From compliancy and security point of view its required to have that sort of implementation in AKS also.
- Similar implementation for k8s RBAC, https://docs.microsoft.com/en-us/azure/aks/azure-ad-rbac

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
N/A

**Environment**:
N/A

**Comment by miwithro** [comment]
We are introducing a V2 of Pod Identity which is based on OIDC Federation which will deliver this capability.  We will have a Public Preview at the end of Q2 2021.
