### ISSUE TITLE
Expose the ability in AKS API to set tags for resources created as a part of the AKS cluster

### ISSUE THREAD

**Issue by yaronya** [Azure/AKS#1952]
**What happened**:
I'm using `terraform` to deploy my AKS cluster. While doing so, I wish to tag all the resources that are a part of the AKS cluster creation for billing purposes. The created resource group also includes VMSS, Public IP Addresses, Disks and a Load Balancer. It seems that there's no way to tag those nested resources (besides the VMSS) via `terraform` so I opened an [issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8754) for the azurerm terraform provider about it. 
Finally, it turns out the issue is originated by the AKS API itself, as it doesn't expose any means of settings/controlling those nested auto-created resources, specifically setting their tags.

**What you expected to happen**:
I wish that the AKS API will expose a way to controlling/managing the nested resources created as a part of the AKS cluster, specifically allowing to set their tags.

**How to reproduce it (as minimally and precisely as possible)**:
1. Use terraform v0.13.2
2. `terraform apply` the terraform code found [here](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8754#issue-715474321).
3. Load Balancer, Disks and IP Addresses are not created with any specified tags.

**Anything else we need to know?**:
Please see the [detailed answer](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8754#issuecomment-722354577) of the maintainer of the terraform azurerm provider.

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- Size of cluster (how many worker nodes are in the cluster?) N/A
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) N/A
- Others: N/A

**Comment by fkaksa** [comment]
Any news on that? Does somebody find the workaround that can help?

**Comment by 616b2f** [comment]
@miwithro does the closing mean that this is possible now?
