### ISSUE TITLE
Transparent Mode CNI as Default

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#1954]
https://docs.microsoft.com/en-us/azure/aks/faq#what-is-azure-cni-transparent-mode-vs-bridge-mode

**Comment by curtdept** [comment]
Is there a migration path for an existing CNI? Or I am guessing a redeploy?

**Comment by clarenceb** [comment]
Docs are published here (as PR link above is broken): https://docs.microsoft.com/en-us/azure/aks/faq#what-is-azure-cni-transparent-mode-vs-bridge-mode

**Comment by Kenneth-Abrams** [comment]
When will transparent mode become default in Azure CNI in production? An [issue ](https://github.com/Azure/azure-container-networking/issues/713) was raised 2 months ago from a support case of mine involving worker nodes only inheriting 1 DNS server of many configured within a VNET. This resulted in multiple production AKS clusters becoming unhealthy when the singular DNS server went down.

**Comment by palma21** [comment]
No migration required, this is delivered on the next upgrade for either node or k8s version.

It's already the default and only option for CNI. And yes, this is one of the issues this solves!

**Comment by djsly** [comment]
How can we verify ? does the AKS resource's json container the info ?

**Comment by Kenneth-Abrams** [comment]
@djsly if you are running aks with vmss

az vmss run-command invoke -g $ResourcrGroup -n $VmssName --scripts "systemd-resolve --status" --command-id RunShellScript --instance-id 0 --output json

If you are running availability set nodes

Command is az vm run-command
