### ISSUE TITLE
AKS (1.19.0) pending Loadbalancer external IP

### ISSUE THREAD

**Issue by dirien** [Azure/AKS#1956]
Environment summary
Provider (ACI)

Version (v 1.14.3-vk-azure-aci-vv1.3.0)

K8s Master Info (AKS)

Issue Details
Running VK via ACI on a AKS Cluster with the Kubernetes Version 1.19.0 results in pending Loadbalancer für external IP Adress and following error: not a vmss instance.

![image](https://user-images.githubusercontent.com/38325136/98806504-9951f680-2419-11eb-90ac-7f63b504798e.png)

With 1.18. and 1.17 everything works fine and as expected.

Repo Steps
Install a AKS Cluster with version 1.19.0

Install nginx-ingress via eg. HELM

helm install my-release ingress-nginx/ingress-nginx --namespace ingress --create-namespace

Check the loadbalancer svc from the ingress controller

![image](https://user-images.githubusercontent.com/38325136/98806540-a53db880-2419-11eb-98ce-f3e815c3e50a.png)

**Comment by yangl900** [comment]
@feiskyer this looks like a regression from cloud provider? The virtual node should be excluded from LB backend pool.

**Comment by feiskyer** [comment]
this is actually a bug from virtual-kubelet. Label "node.kubernetes.io/exclude-from-external-load-balancers" is required for k8s>=1.19 while virtual-kubelet is still using "alpha.service-controller.kubernetes.io/exclude-balancer". We would fix this in virtual-kubelet.

```
    // labelNodeRoleExcludeBalancer specifies that the node should not be considered as a target
    // for external load-balancers which use nodes as a second hop (e.g. many cloud LBs which only
    // understand nodes). For services that use externalTrafficPolicy=Local, this may mean that
    // any backends on excluded nodes are not reachable by those external load-balancers.
    // Implementations of this exclusion may vary based on provider. This label is honored starting
    // in 1.16 when the ServiceNodeExclusion gate is on.
    labelNodeRoleExcludeBalancer = "node.kubernetes.io/exclude-from-external-load-balancers"
    // labelAlphaNodeRoleExcludeBalancer specifies that the node should be
    // exclude from load balancers created by a cloud provider. This label is deprecated and will
    // be removed in 1.18.
    labelAlphaNodeRoleExcludeBalancer = "alpha.service-controller.kubernetes.io/exclude-balancer"
```

**Comment by feiskyer** [comment]
Fixing by https://github.com/virtual-kubelet/azure-aci/pull/85

**Comment by dirien** [comment]
hi @feiskyer,

Thank you very much!

Short question: How does the rollout on AKS is working? Where can i see that the fix is in place and i can upgrade my cluster?

**Comment by MikkelHegn** [comment]
I think you can add the label to the virtual node manually for now. Will let @feiskyer answer to the upgrade procedure of VN.

**Comment by feiskyer** [comment]
We would rollout the new image next week. Before that, could you use the following command as a workaround?

```
kubectl label nodes virtual-node-aci-linux node.kubernetes.io/exclude-from-external-load-balancers=true
```
