### ISSUE TITLE
[Feature| AAD Pod Identity V2 addon for Windows 

### ISSUE THREAD

**Issue by keikhara** [Azure/AKS#1958]
Support Pod Identity for Windows addon

**Comment by zhiweiv** [comment]
Is this duplicated with https://github.com/Azure/AKS/issues/1917?

**Comment by pdebruin** [comment]
https://github.com/Azure/aad-pod-identity/issues/242

**Comment by miwithro** [comment]
See #1480 dup.  Closing.
