### ISSUE TITLE
Uncleaned Load balancer rules on managed AKS cluster with Azure CNI

### ISSUE THREAD

**Issue by solacens** [Azure/AKS#1959]
**What happened**: Uncleaned Load balancer rules on managed AKS cluster with Azure CNI

**What you expected to happen**: To clean up those rules properly, actually is to sync rules properly which the CNI should be doing.

**How to reproduce it (as minimally and precisely as possible)**: No idea. Some day it got stacked up and I found that I was unable to retrieve new dynamic IP for AKS services due to this issue. 

```
NAME                              TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)
                                                                              AGE
scoped-nginx-ingress-controller   LoadBalancer   10.0.117.240   <pending>     80:31615/TCP,443:30522/TCP,8300:31159/TCP,8305:31117/TCP,8310:31810/TCP,8315:31244/TCP,8320:32061/TCP,8325:32099/TCP,8330:30128/TCP,8335:32052/TCP,8340:32069/TCP,8345:32605/TCP,8350:32336/TCP,8355:30472/TCP   46m
```

In the event when I describe the service, it said

```
  Type     Reason                      Age                From                  Message
  ----     ------                      ----               ----                  -------
  Normal   UpdatedLoadBalancer         3m54s              service-controller    Updated load balancer with new hosts
  Normal   EnsuringLoadBalancer        24s (x8 over 10m)  service-controller    Ensuring load balancer
  Warning  CreateOrUpdateLoadBalancer  23s (x8 over 10m)  azure-cloud-provider  Code="LoadBalancerInboundRuleCountLimitReached" Message="Basic sku load balancer /subscriptions/<redacted>/resourceGroups/mc_qf-aks-dev-rg_qf-aks-dev_eastasia/providers/Microsoft.Network/loadBalancers/kubernetes cannot have more than 250 inbound NAT or load balancing rules combined." Details=[]
  Warning  SyncLoadBalancerFailed      23s (x8 over 10m)  service-controller    Error syncing load balancer: failed to ensure load balancer: timed out waiting for the condition
```

Then I checked the MC_xxxxxxxxx resource group's load balancer, which I found those uncleaned rules.

![1](https://user-images.githubusercontent.com/9146272/98919784-3724ee80-250a-11eb-8760-b345f6f896b1.jpg)
![2](https://user-images.githubusercontent.com/9146272/98919789-38eeb200-250a-11eb-8ac6-0f9d34a03b57.jpg)

**Anything else we need to know?**: 

**Environment**:
- Kubernetes version (use `kubectl version`): `version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"ba1ce4122d67b0f7399a41afbbd8a7258d22ecb8", GitTreeState:"clean", BuildDate:"2020-04-21T00:13:25Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`
- Size of cluster (how many worker nodes are in the cluster?) 2-20, which scales according to our testing workload
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Basically test environment per namespace, each space will creates a scoped nginx ingress controller, which requires a new dynamic public IP.
- Others: None

**Comment by solacens** [comment]
I'm cleaning it with Azure CLI anyway... Which is SUPER SLOW

**Comment by yangl900** [comment]
That's very interesting, thanks for reporting. We had this issue long time ago but haven't seen any report for a while. It's not related to CNI, but some bugs in upstream cloud provider.

to confirm - when you do `kubectl get svc -A`, you don't see those services, do you?

**Comment by yangl900** [comment]
it looks like the cluster does have many services in different namespaces? `kubectl get svc -A` would give you better idea.

You can enable diagnostic settings to get the controller manager logs, and that will give you more detailed info on what it is doing.

Also I would recommend use Standard Loadbalancer. The update is much faster comparing to Basic LB. (a few seconds v.s. minute+)

**Comment by solacens** [comment]
We create FREQUENTLY create and delete namespace, which every namespace will get a scoped nginx ingress controller, which means that the `scoped-nginx-ingress-controller` will exists in every namespace. Correct.

But since it has been delete, we can't find it anymore, and we was expecting that those load balancer rules to be removed

**Comment by solacens** [comment]
Seems my AKS cluster is kinda old and up for an year. Is that new cluster is provisioning `Standard` load balancer instead of the `Basic` one?

**Comment by yangl900** [comment]
Yes, the new clusters created will default to Standard LB. In `az aks show -o json` you should see

```
"loadBalancerSku": "Standard"
```

it is possible the load balancer cleanup is too slow for Basic that you have too many svc in GC and also new svc waiting, it got stuck there, since the cloud provider reconciles services one by one, and cannot process new svc.

**Comment by solacens** [comment]
Thanks, we will try out the new AKS cluster.
