### ISSUE TITLE
Australian region availability

### ISSUE THREAD

**Issue by wyvern8** [Azure/AKS#196]
When can we expect AKS preview to be available in Australia East and Southeast?

**Comment by htuomola** [comment]
Would be very interested in seeing this too (Australia East)

**Comment by shanecorcoran** [comment]
Would also be very interested in this.

**Comment by TimJarvis** [comment]
Does the complete lack of official response on this issue indicate that this will not be coming to an Australian region anytime in the near future?

This will mean that this service cannot be used for most Australian government and/or education applications - in my case this will force me down the AWS or Google Cloud path, not a big deal I guess but a shame for Azure.

**Comment by jrhoward** [comment]
Hmm yes, without any visibility at all I can't even recommend waiting for it

**Comment by wyvern8** [comment]
Yeah, going with KOPs on AWS until EKS, and some  prototyping on GKE.  Telling people not to worry about AKS.

**Comment by wyvern8** [comment]
Yeah, going with KOPs on AWS until EKS, and some  prototyping on GKE.  Telling people not to worry about AKS.

**Comment by machship-mm** [comment]
Can you please reopen this so that we might get an answer from them eventually?

**Comment by TimJarvis** [comment]
Yeah, we just made the decision today to go AWS instead. Shame we would have preferred to go Azure. Incidentally as part of this decision it also means we will go managed postgres instead of SQL Server; Its quite a lot cheaper on AWS. MS have missed out on $15k or so a year (peanuts I know) because they simply won't give a timeline.

**Comment by sjwaight** [comment]
Hopefully some of you made it to Container Camp last week in Melbourne. If not, hang tight is all I can say!

**Comment by machship-mm** [comment]
Hi @sjwaight - can you elaborate at all?

**Comment by neoGeneva** [comment]
Woo! https://azure.microsoft.com/en-us/blog/azure-kubernetes-service-aks-ga-new-regions-new-features-new-productivity/

**Comment by jrhoward** [comment]
do I get point for deploying the first network customised terraformed AKS cluster in AUS

**Comment by jrhoward** [comment]
By the way it is seriously limited by having only one agent pool.

**Comment by jrhoward** [comment]
come on microsoft. MVP is bleeding into one-up-man-ship
