### ISSUE TITLE
AppGW does not work with windows pods in peered network

### ISSUE THREAD

**Issue by skrish24** [Azure/AKS#1960]
When we create an app gw and windows pods inn different VNET then app gw gives 502 error.
This issue is because the peered network CIDR is not present in the CNI config of the windows nodes hence the outbound connectivity fails.

What is the road map for this fix to be completed.

**Comment by akshaysngupta** [comment]
@palma21 can you help with `windows` node connectivity issues with peered VNETs ?

**Comment by VijayRod** [comment]
Looks like https://github.com/Azure/AKS/issues/1953.

**Comment by akshaysngupta** [comment]
@skrish24 are you still facing this issue ? This issue was addressed last year.

**Comment by parallo-mattallford** [comment]
@akshaysngupta, I faced this issue two months ago (May 2021). Microsoft Support SR 2103160060000233

**Comment by skrish24** [comment]
@akshaysngupta I do not think this was fixed last year. This issue still persists

**Comment by CJJ69** [comment]
We are also facing this exact issue.

We created a standard Azure hub spoke topology; with AppGW in hub and spoke workload (AKS cluster) in peered VNet.
AGIC is configuring AppGW OK.
Linux containers work OK.
Windows containers are offline (backend unhealthy)

Manually bodging the AppGW subnet into the ExceptionList of OutBoundNAT endpoint policy (in file C:\k\azurecni\netconf\10-azure.conflist) on each Windows node fixes the issue; until you scale or recreate nodes.

**Comment by EPinci** [comment]
@akshaysngupta, can you address the latest comment of @CJJ69, please?

**Comment by palma21** [comment]
Can folks provide their repro steps if this is reproable or paste the support tickets if you have them?

**Comment by cmendible** [comment]
Hi Team,

Was this one fixed? One of my customers is affected by this limitation.

**Comment by AbelHu** [comment]
@cmendible, it is not fixed. We are working on this and will update it when it is done.

**Comment by allyford** [comment]
#3128  Is currently in development and will allow customers to disable Outbound NAT, resolving issues like this.

**Comment by cmendible** [comment]
Any news on #3128?

**Comment by cmendible** [comment]
@AbelHu it's my understanding that this has not been fixed yet. If that is the case can we reopen?

On the other hand, using the workaround suggested in: https://github.com/Azure/AKS/issues/1960#issuecomment-886551752 is no longer working for one of my customers running AKS & k8s version 1.23.12. Any suggestion?
