### ISSUE TITLE
Azure policy pods don't get scheduled with CriticalAddonsOnly taint

### ISSUE THREAD

**Issue by magooster** [Azure/AKS#1963]
**What happened**:

Deployed a cluster with CriticalAddonsOnly taint on the system nodepool, with Azure Policy enabled.

The azure policy pods get scheduled on a user nodepool. If no other nodepools pods stay Pending...

**What you expected to happen**:

All 'system' pods should run on the system node pool. 

Looks like the Azure policy pod specs don't contain a toleration for the CriticalAddonsOnly taint.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy an AKS cluster with a single nodepool with the CriticalAddonsOnly taint and Azure Policy enabled.

**Anything else we need to know?**:

**Environment**:
- kubernetes version 1.17.11
- 3 nodes basic cluster
- No workloads deployed

**Comment by ckittel** [comment]
To add a little extra context here (and to help those searching for this).  The system node pool [documentation](https://docs.microsoft.com/azure/aks/use-system-pools#system-and-user-node-pools) suggests the following:

> Use the `CriticalAddonsOnly=true:NoSchedule` taint to help prevent application pods from being scheduled on system node pools.

That should (probably) then imply that all first-party AKS addons should tolerate that taint. As the OP pointed out, Azure Policy does not and will not be scheduled on your cluster's system nodepool.

**Comment by RamyasreeChakka** [comment]
@magooster Azure Policy Add-on deploys gatekeeper and azure-policy pods. The gatekeeper pods have the toleration for CriticalAddonsOnly taint. You should see gatekeeper pods deployed to system node pool. The azure-policy pods do not have toleration and so they would be deployed to another pool.

**Comment by ckittel** [comment]
Yeah, that's where the issue comes in.  A customer may have taints on all the other (user) workload nodepools, _in part_ to ensure system addons do not escape the system nodepool. Is it advised that azure-policy pods actively avoid the system nodepool?  If so, we can capture that guidance.

**Comment by magooster** [comment]
> @magooster Azure Policy Add-on deploys gatekeeper and azure-policy pods. The gatekeeper pods have the toleration for CriticalAddonsOnly taint. You should see gatekeeper pods deployed to system node pool. The azure-policy pods do not have toleration and so they would be deployed to another pool.

The system node pool documentation also states the following:

> It's recommended to schedule your application pods on user node pools, and dedicate system node pools to only critical system pods. This prevents rogue application pods from accidentally killing system pods. Enforce this behavior with the CriticalAddonsOnly=true:NoSchedule taint for your system node pools.

I found it strange that only some of the Azure Policy add-on resources were deemed 'critical' for an Azure Policy enabled cluster? I was expecting them to be part of the 'system' and as above could be kept separate from customer deployed applications.

**Comment by RamyasreeChakka** [comment]
Thanks for reporting this issue. We will be fixing this in the upcoming release of the add-on.

**Comment by dhirschfeld** [comment]
Looks like I just ran into this:
```
Events:
  Type     Reason             Age                    From                Message
  ----     ------             ----                   ----                -------
  Warning  FailedScheduling   7h9m                   default-scheduler   0/1 nodes are available: 1 node(s) had taint {CriticalAddonsOnly: true}, that the pod didn't tolerate.
  Warning  FailedScheduling   42s                    default-scheduler   0/2 nodes are available: 2 node(s) had taint {CriticalAddonsOnly: true}, that the pod didn't tolerate.
  Normal   NotTriggerScaleUp  37s (x2197 over 7h7m)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 2 node(s) didn't match node selector, 1 max node group size reached
``` 

Unfortunately, the behaviour of the autoscaler seems to be to spin up my *default*, system node pool to it's max size rather than spinning up any of my user nodes without the taint. Hopefully there's a config I can tweak there to get a more sensible behaviour there :thinking:

> *We will be fixing this in the upcoming release of the add-on.*

I'm currently on 1.20.2. Is there an ETA for the new release?

**Comment by magooster** [comment]
Has the fix been rolled out globally. Looking at a fresh deployment of AKS 1.18.14 (I see that webhook pod has the toleration but not the azure-policy pod)

**Comment by miwithro** [comment]
@RamyasreeChakka
