### ISSUE TITLE
Unable to connect to private AKS cluster

### ISSUE THREAD

**Issue by BhanuPrasadMera** [Azure/AKS#1965]
- Created private AKS cluster
- Tried to connect to the cluster using az commands.
- When trying to create namespace or get resources inside this cluster below attached error is thrown.
![image](https://user-images.githubusercontent.com/40078396/99352159-1ec92100-28c8-11eb-9871-61689da2be94.png)

**Comment by feiskyer** [comment]
@BhanuPrasadMera please refer to https://docs.microsoft.com/en-us/azure/aks/private-clusters#options-for-connecting-to-the-private-cluster
