### ISSUE TITLE
Inability to use a StatefulSet with Azure Kubernetes Cluster Virtual Node

### ISSUE THREAD

**Issue by WilkinJ** [Azure/AKS#1966]
It does not appear to be possible to deploy a Kubernetes statefulset to the Virtual node pool of an Azure Kubernetes Cluster.

The node pool in the cluster we have attempted this with is called "virtual-node-aci-linux", and it has the following version number "v1.14.3-vk-azure-aci-vv1.3.0".

I have been able to deploy a statefulset to a standard Azure auto-scaling node pool, and it scales out as I expect i.e. if the capacity of a node is reached as the set is scaling out, a further node is provisioned at which point the statefulset will continue to scale out.

We want to use Virtual nodes to get around the delay that occurs when an additional node needs to be provisioned as it would in a standard node pool.

**Comment by meshpaul** [comment]
@WilkinJ  did you get your answer on this? I not I suggest a nugde :)

**Comment by feiskyer** [comment]
@WilkinJ please file a support ticket if you still have issues. And also aware that there're a few limitations on virtual node documented [here](https://docs.microsoft.com/en-us/azure/aks/virtual-nodes#known-limitations).
