### ISSUE TITLE
Unable to add tags to AKS cluster from the Azure Portal

### ISSUE THREAD

**Issue by c-n-d** [Azure/AKS#197]
Hi,

Adding tags to an AKS cluster from the Azure Portal results in the following message:

```
Error adding tags
Unknown error occurred.
```

## Steps to Reproduce
1. Visit [https://portal.azure.com](https://portal.azure.com)
1. Navigate to the **Container services (managed)** page
1. Select an existing AKS cluster
1. Select the `Tags` option
1. Provide a tag `Name` and `Value`
1. Click `Save`

### Request
```
curl 'https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.ContainerService/managedClusters<CLUSTER_NAME>?api-version=2017-08-31'
-X PATCH
-H 'x-ms-command-name: Tags.patchTags'
...
```

### Request Data
```
{"tags":{"tagName":"tagValue"}}
```

### Response
```
405: Method Not Allowed
```

**Comment by sburkart80** [comment]
Did you receive any update so far on this topic?

**Comment by wcom939** [comment]
This is a fairly significant problem for me as well, attempting to test hazelcast in AKS and can't because hazelcast discovery relies on tags....

**Comment by mboersma** [comment]
AKS added a PATCH endpoint that allows for updating tags. I verified that this is working in the Azure Portal now.

![screen shot 2018-08-07 at 1 50 05 pm](https://user-images.githubusercontent.com/73019/43798768-d3e7946a-9a48-11e8-9c1d-367d353fc9a3.png)
