### ISSUE TITLE
Portal - System Assigned identity issues

### ISSUE THREAD

**Issue by stevecraig1000** [Azure/AKS#1971]
Created a scripted system assigned identity, then assigned the identity contributor permissions on the Networking resource Group.
Script build a cluster using azure CNI with the system assigned identity in its own resource group, not the same as networking

Build completes as expected. However subsequent Portal changes error with the following;
Failed to save Kubernetes service xxxx Error: the identity ids must not be null or empty for UserAssigned identity type

the same changes can be completed through Azure CLI

version 1.17.13
Four nodes in a cluster
No workloads at present, it is being prepared for workloads

This issue tracker is a best-effort forum for users and customers to suggest features and report bugs.

If you are experiencing a service disruption when creating, upgrading, scaling, or deleting your cluster,
please open a support request with Azure support. Be sure to include your subscription id, resource group,
cluster name, and region. This information should __NOT__ be included in this issue due to its potential
sensitivity.

-->

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by yangl900** [comment]
hi @stevecraig1000 , thanks for reporting this issue. Do you have a correlation ID from the error message for us to look up?
