### ISSUE TITLE
Stopping and starting a cluster after a resize operation leads to detached node in NotReady state  

### ISSUE THREAD

**Issue by Djeramon** [Azure/AKS#1973]
**What happened**:

I created a cluster with powerful nodes to do some initial processing (E8as_v4):

`az aks create --name $aks_name --node-count 1 --node-resource-group $node_resource_group --node-vm-size Standard_E8as_v4 --attach-acr $acr_name --service-principal $sp_appId --client-secret $sp_password`

After the initial processing was complete I moved to a smaller nodepool. First, I created a new nodepool with the following command:

`az aks nodepool add --resource-group $resource_group --cluster-name $aks_name --name main --node-count 1 --mode System -s Standard_E2as_v4`

After this command completed, I removed the existing nodepool (Standard_E8as_v4) using the Azure Portal.

Afterwards, I used the AKS preview functionality to start and stop my cluster. ([Link](https://docs.microsoft.com/en-us/azure/aks/start-stop-cluster))

`az aks stop --name $aks_name--resource-group $resource_group`
`az aks start --name $aks_name--resource-group $resource_group`

After the cluster had restarted, the nodepool is still invisible in the Azure portal, but when I run `kubectl get no` I can see it in the NotReady state. It also shows up in the Azure Portal Insights as NotReady Node.

Output of `kubectl get no`:

```
NAME                             STATUS     ROLES   AGE   VERSION
aks-main-27754109-vmss000000     NotReady   agent   19h   v1.17.13
aks-memopt-27754109-vmss000002   Ready      agent   16m   v1.17.13
```

I can't find a way to remove this node. I deleted the entire cluster and repeated the setup process, but the result is the same. So it is definitely reproducible. 

**What you expected to happen**:

The node should be completely removed and not show up any longer.

**How to reproduce it (as minimally and precisely as possible)**:

Reproduction steps are listed above. I deleted the entire cluster and repeated the setup process, but the result is the same. So it is definitely reproducible. 

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-20T16:22:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?)

Only one. 

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

HTTP microservices, but this shouldn't have an impact on the problem.

**Comment by miwithro** [comment]
@NickKeller

**Comment by danimal521** [comment]
@NickKeller any updates on this?

**Comment by phealy** [comment]
@Djeramon are you still experiencing this issue? I believe this has been fixed in newer AKS releases.
