### ISSUE TITLE
--node-resource-group Service principal clientID: xxx not found in Active Directory tenant xxxx

### ISSUE THREAD

**Issue by V4A001** [Azure/AKS#1974]
**What happened**:
I try to create a AKS cluster with the node-resource-group  in preview. That worked once. I deleted all the app registrations and the AKS cluster + resource group completely. Running the command another time throws error that the service principal clientid is not found.
az extension add -n aks-preview

'latestK8sVersion=$(az aks get-versions -l $location --query 'orchestrators[-1].orchestratorVersion' -o tsv)
echo $latestK8sVersion
echo $aksresourcegroup
az aks create -l $location -n $aks -g $resouregroup --generate-ssh-keys -k $latestK8sVersion --node-resource-group $aksresourcegroup --node-count 1 --node-vm-size Standard_B2s --node-osdisk-size 32 --load-balancer-sku $sku --enable-addons monitoring

The behavior of this command has been altered by the following extension: aks-preview
BadRequestError: Operation failed with status: 'Bad Request'. Details: Service principal clientID: xxx not found in Active Directory tenant xxxx, Please see https://aka.ms/aks-sp-help for more details.
'

**What you expected to happen**:
To create a AKS cluster as I did successfully before.

**How to reproduce it (as minimally and precisely as possible)**:
See azcli script.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)

**Comment by V4A001** [comment]
If I remove the --node-resource-group it throws same error. After I removed the aks-preview it worked. It might have been caused that I manually deleted the resource groups? I suspect that by adding the aks-preview after creating the first cluster might work as the principal is created then already the the old aks.

# az extension add -n aks-preview

**Comment by V4A001** [comment]
Nope, definitely broken now :-(.

**Comment by yangl900** [comment]
Hi @V4A001 , the aks CLI caches your service principal information in a file under ~/.azure/aksServicePrincipal.json. Since you deleted the service principal as well, the next command seems still trying to use the one in the cache (already deleted). That's why you see the message. The CLI can be smarter to create a new SP if the cache is invalid, but you can delete that file to remove the cache.

btw - I highly recommend you start create AKS cluster using managed identities, with which you don't need to worry about service principals, and its credentials, rotate its secrets etc.

**Comment by V4A001** [comment]
@yangl900 ; thank you for your reply. Appreciated. I did not find the .azure folder. If it is under my user account name no such .json is found. The error is thrown on the object id instead of the client id which is given credentials. So that is why I did not find it.

This is the service principle name created on the aks cluster.

`aks_sp=$(az aks list --resource-group $resourcegroup --query="[0].servicePrincipalProfile.clientId" -o tsv)
echo $aks_sp`

If you use the static load balancer of Azure, you need to take care that the resource group name of this instruction is of the resource group where the static ip lives instead that of the resource group of the aks cluster...
https://docs.microsoft.com/en-us/azure/aks/static-ip

And the documentation is not clear enough is above should be executed before you start on a static ip with ingress controller:
https://docs.microsoft.com/en-us/azure/aks/ingress-static-ip

**Comment by V4A001** [comment]
The preview is still broken by the way.
