### ISSUE TITLE
[Feature] Support ContainerD on Windows AKS

### ISSUE THREAD

**Issue by keikhara** [Azure/AKS#1976]
ContainerD will be replacing docker on Windows server 2019. Customers will need to redeploy their applications on a different nodepool with ContainerD support.

**Comment by brobichaud** [comment]
This issue implies that the recently GA'd [containerD support in AKS](https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2020-11-16) applies only to linux nodepools, is that true? In all the references to containerD in AKS docs and release notes nowhere have I seen that this does not apply to Windows. Is this an oversight or a case of the outdated "linux only" mindset?

The one comment I can find that might indicate linux only is "To use containerd as the container runtime you must use AKS Ubuntu 18.04 as your base OS image" [found here](https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#container-runtime-configuration-preview). But it's subtle, as one could read that as meaning "if you're running linux then...". Even the seemingly thorough "Containerd limitations/differences" section on that same page makes no mention of this being linux only.

**Comment by zhiweiv** [comment]
Any ETA?

Sent from my iPhone
________________________________

**Comment by mainred** [comment]
Hi @zhiweiv , we announced the [Windows containerd support public preview](https://azure.microsoft.com/en-us/updates/public-preview-aks-support-for-containerd-for-windows-server-containers/) on May 25. We plan to GA Windows containerd in the third Quater, BUT we need to evaluate the success rate of the feature and feature coverage of our customers first.

**Comment by zhiweiv** [comment]
@mainred 
From the AKS release note

> Windows containerd support on AKS are available in 3 regions (eastus, uksouth, and westcentralus) today.

Do you know when it will be available in southeast asia?

**Comment by mainred** [comment]
@zhiweiv , Windows containerd is available in all Azure public cloud regions now.

**Comment by zhiweiv** [comment]
> We plan to GA Windows containerd in the fourth Quater of this year, BUT we need to evaluate the success rate of the feature and feature coverage of our customers first.

@mainred
Does the ETA of GA remain unchanged? We have running Windows Containerd without problem since preview.

**Comment by zhiweiv** [comment]
Any news?

**Comment by mainred** [comment]
AKS will roll out the release including Windows containerd GA next week, and this change will take two weeks or so to be available in all regions, like Dec 17th for reference, but please wait for our PM @justindavies's official announcement, and thanks for your patience.
