### ISSUE TITLE
Feature Request: Configurable private endpoints for AKS with private link

### ISSUE THREAD

**Issue by denniszielke** [Azure/AKS#1978]
**What happened**:
Deploying AKS with private link in non-routable Subnet.
The issue is that the private link endpoint (in picture below called **AKS1-PE1**) is deployed to the same subnet as the AKS worker nodes. That unfortunately means that the private endpoint cannot be contacted from routeable on prem or peered azure vnets.

**What you expected to happen**:
We would like to connect to the private api server even when the worker nodes are deployed in non-routeable ip space.
We see two possible solutions (see picture):
![akspe2](https://user-images.githubusercontent.com/11569044/99980763-e5515380-2da8-11eb-9ef9-7a7f1edd6fb9.png)

Option 1: Private Link Endpoint (**AKS1-PE2**) can be deployed to another subnet (**AKS-Subnet2**) (different from the worker node subnet) that can be configured to be routable in the private corporate network.
Option 2: It is possible to create another private link Endpoint in another VNET (**AKS1-PE3**). Other services in azure can create multiple private link endpoints in different vnets - AKS should get the same capability.

**Comment by miwithro** [comment]
@ feiskyer

**Comment by feiskyer** [comment]
@denniszielke curious how is node/pod network working since the subnet is not routable?

**Comment by denniszielke** [comment]
@feiskyer : It seems to work when when using azure cni (when using a system node pool in the routable ip space). In our case we are using Istio Ingress/Egress Gateway in the routable part of the subnet to ensure ingress and egress from/to the routable part of the subnet to the nonroutable part.

**Comment by feiskyer** [comment]
@denniszielke Thanks for the updates. It makes sense then routable IP space is required. I think it should also work if you deploy into routable IP space with kubenet plugin (note that a routable is required for Kubernetes to configure routes for each node).

**Comment by miwithro** [comment]
@denniszielke do you need anything else here?

**Comment by denniszielke** [comment]
Still is an issue for a big customer.
Would we consider customers allowing to create an additional private link endpoint for the api server (in a different vnet?). The problem is still that we cannot ensure routing or peering between all private networks. Since other private link enabled service allow customer to create multiple endpoints in different vnets - that looks like the most promissing approach.

**Comment by feiskyer** [comment]
Option 2 has already been supported now.
