### ISSUE TITLE
Deleting namespace deletes the loadbalancer service but public IP is not deleted in AKS

### ISSUE THREAD

**Issue by xeronix** [Azure/AKS#1979]
**What happened**:
Created a K8s cluster in azure AKS.
Created statefulset with N pods, each having 1 loadbalancer service. All objects are in same namespace.
Deleting the namespace deletes the statefulset and loadbalancer service but public IP is not deleted in AKS.
Even explicitly deleting the loadbalancer service sometimes does not delete public IP.

**What you expected to happen**:
Deleting namespace should delete public IP in AKS

**Environment**:
- Kubernetes version (use `kubectl version`):
 kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-20T16:22:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
2 Nodes

**Comment by xeronix** [comment]
Any update on this issue ?

**Comment by seguler** [comment]
This seems like was fixed in 1.16 (https://github.com/kubernetes/kubernetes/issues/80571) 
@feiskyer - thoughts?

**Comment by feiskyer** [comment]
yes, the issue should be fixed by service finalizer feature. If you still see the same issue, please open a support ticket so we could check more details.
