### ISSUE TITLE
1.19.3 with Calico network policy: metrics-server fails to connect to API server

### ISSUE THREAD

**Issue by estambakio-sc** [Azure/AKS#1982]
**What happened**:

In AKS `1.19.3` with `calico` network policy `metrics-server` cannot access API server. In `1.18.8` it works fine.

Reproduces consistently.

**What you expected to happen**:

I expected it to work as it was in `1.18.8`

**How to reproduce it (as minimally and precisely as possible)**:

I'm using Terraform: 

```
terraform {
  required_version = ">= 0.13"
  backend "azurerm" {
  }
}

provider "azurerm" {
  version         = "=2.23.0"
  subscription_id = var.azure_subscription
  features {}
}

resource "azurerm_resource_group" "k8s" {
  name     = "egor"
  location = "westeurope"
}

resource "azurerm_kubernetes_cluster" "k8s" {
  location            = "westeurope"
  name                = "egor"
  resource_group_name = azurerm_resource_group.k8s.name

  kubernetes_version = "1.19.3"

  role_based_access_control {
    enabled = true
  }

  enable_pod_security_policy = true

  dns_prefix = "badaboom"

  network_profile {
    load_balancer_sku = "standard"
    network_plugin    = "kubenet"
    network_policy    = "calico"
  }

  identity {
    type = "SystemAssigned"
  }

  default_node_pool {
    name                = "default"
    vm_size             = "Standard_D4_v3"
    os_disk_size_gb     = "100"
    min_count           = 1
    max_count           = 2
    enable_auto_scaling = true
  }
}
```

This setup with AKS `1.19.3` and `calico` network profile leads to failing `metrics-server`: 
```
% kubectl -n kube-system get pod
NAME                                                  READY   STATUS             RESTARTS   AGE
calico-node-vrtbm                                     1/1     Running            0          58m
calico-typha-deployment-64657d89fd-4n8k2              1/1     Running            0          59m
calico-typha-horizontal-autoscaler-599c7bb664-lchnq   1/1     Running            0          59m
coredns-autoscaler-5b6cbd75d7-bgr96                   1/1     Running            0          59m
coredns-b94d8b788-c5sqd                               1/1     Running            0          57m
kube-proxy-xhbbt                                      1/1     Running            0          58m
kube-state-metrics-6d8cf88456-8nl6q                   1/1     Running            0          52m
metrics-server-77c8679d7d-qccxz                       0/1     CrashLoopBackOff   19         59m
tunnelfront-98589f5c9-8fpkh                           1/1     Running            0          59m
```

Error in its logs is the following:
```
panic: Get https://<dns_prefix>-6cfdbc53.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication: dial tcp: i/o timeout
```

If I remove `network_profile` block then metrics-server starts successfully. But in this case `Ingress` (ingress-nginx) doesn't seem to work properly - requests time out with no errors (but I'm not certain what exactly causes problems with Ingress).

With AKS `1.18.8` this setup works fine (never had such problem while created dozens of clusters). 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.3
- Size of cluster (how many worker nodes are in the cluster?) 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) didn't run any workload because failing metrics-server makes initial setup to fail :) 
- Others:

**Comment by estambakio-sc** [comment]
Update: with the latest `azurerm` terraform provider (2.37.0) it doesn't reproduce any more :) Let's close this one.

**Comment by estambakio-sc** [comment]
After using it for some time something similar happens again on several clusters. When namespace is deleted it hangs in `Terminating` state, `describe ns <name>` shows the following in status: 

```
Discovery failed for some groups, 1 failing: unable to retrieve the
      complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently
      unable to handle the request
```
Reproduces consistently since yesterday in 3 created cluster.

**Comment by estambakio-sc** [comment]
1.19.3 started to break again, reported here: https://github.com/Azure/AKS/issues/1982#issuecomment-738950256

Master is still on 1.19.3, while default config gonna use 1.18.10 (for dev branches).

**Comment by palma21** [comment]
Hi @estambakio-sc we don't have a lot of similar reports, could you create a support ticket and let us know the number so we may follow up with you on your specific cluster(s)?

**Comment by estambakio-sc** [comment]
Today updated to 1.19.7, seems to work fine now. Closing.
