### ISSUE TITLE
Network contributor role is missing when updating from SPN cluster to MSI cluster

### ISSUE THREAD

**Issue by norshtein** [Azure/AKS#1983]
**What happened**:
See https://github.com/MicrosoftDocs/azure-docs/issues/66087#issuecomment-732988837 , if the cluster is using BYO VNet and it is updated from SPN cluster to MSI cluster, the cluster identity will not get network contributor role, we need to fix this in aks-preview extension.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by nidiculageorge** [comment]
@norshtein : hould we manually assign contributer permission to the custom network in another RG

**Comment by norshtein** [comment]
@nidiculageorge , yes, please manually assign "Network Contributor" role to the cluster identity at VNet scope. You can check detailed explanation at  https://github.com/MicrosoftDocs/azure-docs/issues/66087#issuecomment-732988837
