### ISSUE TITLE
Better error message for invalid windows admin password

### ISSUE THREAD

**Issue by MikkelHegn** [Azure/AKS#1985]
**Issue transferred from AKS-Windows repo**

Reported by https://github.com/carlsoncoder on 4/25/2019

Is your feature improvement related to a problem? Please describe.
This is definitely a very minor issue, but it was kind of annoying. When using aks-engine in the past to create my own clusters, I would always use a random GUID for the Windows admin password, and that worked fine. When I try to use that with the az aks create command, I get the following error:

The command failed with an unexpected error. Here is the traceback:

Parameter 'ManagedClusterWindowsProfile.admin_password' must conform to the following pattern: '^(?=.[a-z])(?=.[A-Z])(?=.[!@#$%\^&\\(\)])[a-zA-Z\d!@#$%\^&\*\(\)]{12,123}$'.

Describe the solution you'd like
I'm not a RegEx expert so I really had no idea what specifically this was looking for. I ended up just using the password in the sample documents and changing a few characters. It would be nice if the error message for this specific scenario could be more user friendly, maybe something like "The admin password must be at least 10 characters, with at least one letter, number, and special character", or something like that.

**Reply** from @MikkelHegn on 5/25/2019:

Thank you for the suggestion. We are planning on adding an option to have the service generate a valid win admin password on cluster creation. Then refer to resetting pwd on the VM Scale Set backing the node pool when / of you need node access.

@keikhara to own the issue.

**Comment by AbelHu** [comment]
I think that we can close this issue. AKS has added validation rules for Windows username and password in the server side. It will return below errors
For adminUsername:
```
Invalid adminUsername. Error: ERROR-MSG. Please see https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/createorupdate#virtualmachinescalesetosprofile
```
ERROR-MSG
- Length of username is invalid. Required length: [1, 20]
- Username cannot end in "."
- The value for username is disallowed

For adminPassword:
```
Invalid adminPassword. Error: ERROR-MSG. Please see https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/createorupdate#virtualmachinescalesetosprofile
```
ERROR-MSG
- Length of password is invalid. Required length: [14, 123]. Minimum password length required by AKS for AzSecPack is longer
- Password does not meet the complexity requirement
