### ISSUE TITLE
Increase the length of Windows agent pool name

### ISSUE THREAD

**Issue by mikkelhegn** [Azure/AKS#1986]
**Issue transferred from Windows preview repo**

Opened by https://github.com/toyota790 on 4/11/2019

Is your feature improvement related to a problem? Please describe.
Currently, the Windows agent pool name can not be longer than 6 characters. Would it possible to increase the maximum length for it?

Describe the solution you'd like
Since the current size of the Linux agent pool name is 27 (Example: aks-nodepool1-40488637-vmss
), I think the maximum length of the Windows agent pool name should be able to set more than 6 characters.

Describe alternatives you've considered
We will have our naming convention for each resource due to the management issue. The size of the resource name would be easy to exceed 6 characters. It will be inconvenient if it only supports less or equal than 6 characters.

**Comment by zhiweiv** [comment]
Any update?

**Comment by zhiweiv** [comment]
@keikhara 
Any update on this?
