### ISSUE TITLE
AKS AAD App is not found in AAD Conditional Access Policy exclusion list

### ISSUE THREAD

**Issue by weinong** [Azure/AKS#1987]
**What happened**:
Customers may have [Conditional Access](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/overview) configured on their AAD tenant and are not able to exclude the AKS AAD Server app `6dae42f8-4368-4678-94ff-3960e28e3630`

**What you expected to happen**:
Customers should be able to configure the Conditional Access policy to exclude restriction to AKS AAD Server App.

**Status**:
We are working on onboarding to Conditional Access. Until then, you will need to use Legacy AAD integration with your own AAD apps.

**Comment by smnmtzgr** [comment]
@weinong is there already a plan/roadmap when to fix this?

**Comment by miwithro** [comment]
@smnmtzgr we are actively working on the integration and corresponding documentation.  We are targeting Ignite for the release.

**Comment by mihma** [comment]
I can see it's been made GA but the actual login request comes to Azure Kubernetes Service AAD Client instead of Azure Kubernetes Service AAD Server hence the policy is not applied. Am I missing something?

**Comment by weinong** [comment]
@mihma Login can happen from other client app. So policy should be configured on the server app.
