### ISSUE TITLE
VM wrong cache size

### ISSUE THREAD

**Issue by daguilarv** [Azure/AKS#1988]
**What happened**:

I am trying to use ephemeral os disk storage in several VM Sku´s and getting the following error messages:

 Standard_F2s_v2 has a cache size of 100663296 bytes, but the OS disk requires 32212254720 bytes
 Standard_DS1_v2 has a cache size of 0 bytes, but the OS disk requires 32212254720 bytes

According to Azure documentation https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series and https://docs.microsoft.com/en-us/azure/virtual-machines/fsv2-series those SKUs should support 43 and 32 GiB respectively.

**What you expected to happen**:

Everything should works and VMs should be created with 30GB os ephemeral disk.

**How to reproduce it (as minimally and precisely as possible)**:

Create a aks cluster with Ephemeral os storage and request 30GB os disk size with described SKUs.

**Environment**:
- Kubernetes version 1.18.8:

**Comment by brobichaud** [comment]
Somewhat related, when I try to create a Windows nodepool using:

> --node-osdisk-type Ephemeral --node-osdisk-size 96  --node-vm-size Standard_D4ds_v4

I see this error:

> "BadRequestError: Operation failed with status: 'Bad Request'. Details: The Virtual Machine size Standard_D4ds_v4 does not support Ephemeral OS disk"

Yet **Standard_D4ds_v4** should support up to 100GB of ephemeral osdisk according to the [Ddsv4-series](https://docs.microsoft.com/en-us/azure/virtual-machines/ddv4-ddsv4-series#ddsv4-series) docs.

**Comment by alexeldeib** [comment]
we'll be rolling out some functionality starting this week to improve the VM SKU validation in general. It should also fix this specific issue for arbitrary vm sizes. I'll post back here when that's in most regions so folks here can validate.

**Comment by alexeldeib** [comment]
This should be hitting the last batch of public cloud regions now. It would be great if some folks here could validate this fixes the issue for them, both supporting/not supporting ephemeral OS and also fixing the wrong cache sizes. 

For anyone interested, we're relying on https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list.

**Comment by daguilarv** [comment]
I have just tested and the problem is fixed for my deployment SKUs.

**Comment by brobichaud** [comment]
I can also confirm that it works as expected with Standard_D4ds_v4. Thank you @alexeldeib!

**Comment by alexeldeib** [comment]
thanks for confirming! will mark this as closed.
