### ISSUE TITLE
After upgrade from 1.18.x to 1.19.3 "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

### ISSUE THREAD

**Issue by ciacco85** [Azure/AKS#1989]
This message is received in every build pipeline and azure devspace.
It seems the cluster cannot connect to the docker engine

**Comment by AdamSharif-MSFT** [comment]
Hey Francesco,

I suspect this may be related to the fact that 1.19+ defaults to ContainerD instead of Docker for the CRI:

https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#container-runtime-configuration
https://github.com/Azure/AKS/releases

_"ContainerD is now Generally Available (GA) and the default container runtime for cluster created or upgraded to kubernetes v1.19+."_

**Comment by ciacco85** [comment]
Is it possible to install Docker on the cluster in order to let it work side by side with ContainerD?

**Comment by neumanndaniel** [comment]
From the docs link above:

> While the docker toolset is still present on the nodes, Kubernetes uses containerd as the container runtime. Therefore, since Moby/Docker doesn't manage the Kubernetes-created containers on the nodes, you can't view or interact with your containers using Docker commands (like docker ps) or the Docker API.

**Comment by ciacco85** [comment]
Yeah sorry! Thank you!
I've managed to solve the issue by creating another node targeting 1.18.x and addressing all the stuff related to docker (we use the same cluster to build the docker file with agent pool in a proper namespace and to build the azure dev space) with node selector and labeling

`kubectl label nodes {mynode} nodekind=docker-build
kubectl label nodes {mynode} nodekind=containerd-build`

`nodeSelector:
      nodekind: docker-build`

AFAIK it's sure a workaround, but there's no trouble having nodes with different version.
What do you think about it?

**Comment by palma21** [comment]
There's not problem having nodes in different versions so long as they are within 2 of the control plane. 

That said, and to provide a more lasting solution, I'm guessing you're using the docker socket for build purposes? As a future solution have you looked into for example buildx mentioned on the doc linked above?

**Comment by ciacco85** [comment]
Honestly no, since I've seen that a better solution is a docker in docker build, since with direct socket call is not managed by k8s cluster and may lead to even worse situation.
Thanks to the feedback, I'll evaluate your solution, too
What do you think about these two options?

**Comment by adhodgson1** [comment]
Docker in Docker is not supported either, taken directly from the article above:
"You can no longer access the docker engine, /var/run/docker.sock, or use Docker-in-Docker (DinD)".
