### ISSUE TITLE
Kube ApiServer config flags for AKS API Create/Patch

### ISSUE THREAD

**Issue by Undrium** [Azure/AKS#1993]
This is a feature request; could we get the possibility to alter some flags for the Kubeneretes Apiserver through the AKS API? 

The most obvious flag being **cors-allowed-origins**.  The projects I have read about using AKS goes around this using a proxy, however being able to consume the Kubernetes API immediately through a browser from a fully managed AKS would be groundbreaking. The advantages would be still having a fully supported cluster and not having to route traffic through something else which might cause delays, bottlenecks and adding complexity to networking.

**Comment by yangl900** [comment]
hey @Undrium , thanks for the suggestion. It was the first option when we evaluate the Azure portal dashboard integration options. You probably have noticed that Azure portal today talks to API server directly (via the proxy we built). The reason why we didn't go with cors-allowed-origins is that, your API server SSL cert is signed by a private CA. The browser actually won't accept the API server's SSL cert as is.

**Comment by yangl900** [comment]
Just in case you were not aware, the browser friendly API server endpoint is already provided. These following tabs read from API server directly:

![image](https://user-images.githubusercontent.com/8466897/100686955-3b3b7380-3334-11eb-9ba1-3cf5ad5a825c.png)

**Comment by Undrium** [comment]
@yangl900 Hey, and thanks for the quick reply! I'm aware of the portals neat AKS-dashboard, which we use daily for provisioning and deployments. Our application is running in the browser, though giving status of the pods connected to another component so we are not utilizing it in the same way. We tried using the portal-url but it does not support http2 yet. I am aware of the certificate-issue as well, would be thankful if this was configurable to make it easier for our Chrome-users. 

This is just something so we do not have to put something in between (a proxy app). If there is another solution, we'd greatly appreciate it.

**Comment by Undrium** [comment]
Could we re-open it as it's more of a feature request and the answer-provided tag is more of a workaround which isn't really solving the root problem?
