### ISSUE TITLE
AKS Nodes time sync broken

### ISSUE THREAD

**Issue by 4iter4life** [Azure/AKS#1994]
**What happened**:
We have a AKS cluster with more as 10 Nodes (ubuntu based). Time on all nodes is out of sync.
Similar situation to already closed ticket https://github.com/Azure/AKS/issues/1336

**What you expected to happen**:
Time on all nodes is in sync

**How to reproduce it (as minimally and precisely as possible)**:
connect to a node via ssh.
_____________
$: sudo timedatectl status
  Local time: Mon 2020-11-30 13:48:44 UTC
      Universal time: Mon 2020-11-30 13:48:44 UTC  
      RTC time: Mon 2020-11-30 13:48:44  
      Time zone: Etc/UTC (UTC, +0000)  
      Network time on: yes  
      NTP synchronized: **no**  
      RTC in local TZ: no  
_____________

**Anything else we need to know?**:
Logs/Analyze
_____________
$: sudo systemctl status systemd-timesyncd.service  
● systemd-timesyncd.service - Network Time Synchronization  
   Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendor prese  
  Drop-In: /lib/systemd/system/systemd-timesyncd.service.d  
           └─disable-with-time-daemon.conf  
   Active: inactive (dead)  
Condition: start condition failed at Tue 2020-11-10 11:01:40 UTC; 2 weeks 6 days ago  
     Docs: man:systemd-timesyncd.service(8)  
$: sudo cat /etc/systemd/timesyncd.conf  
...  
[Time]  
#NTP=  
#FallbackNTP=ntp.ubuntu.com  
...
_____________

soo.. NTP is commented out.. i just changed it to
_____________
[Time]
NTP=ntp.ubuntu.com`
$: sudo timedatectl set-ntp true    
$: sudo systemctl restart systemd-timesyncd.service  
$: sudo timedatectl status
      Local time: Mon 2020-11-30 13:08:01 UTC
      Universal time: Mon 2020-11-30 13:08:01 UTC
      RTC time: Mon 2020-11-30 13:08:00
      Time zone: Etc/UTC (UTC, +0000)
      Network time on: yes
      NTP synchronized: **yes**
      RTC in local TZ: no
_____________

**Environment**:
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-20T16:22:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (how many worker nodes are in the cluster?) : 
16 Nodes

**Comment by yangl900** [comment]
hi @4iter4life , thanks for reporting.

I think we are aware of this issue and fixed it on week of Nov 9th. If you add a new agent pool, the issue should be fixed. For existing node pools, or on next upgrade (or node image upgrade), the issue will be fixed too.

It was fixed in this change:

https://github.com/Azure/AgentBaker/pull/427

**Comment by 4iter4life** [comment]
Hi @yangl900,

thx for your response.

I tried to upgrade nodes only, but my nodepool is not defined with a VMSS (vm scale set) so its not possible to update it separatly. 

I will upgrade all our clusters to 1.18.x, hopefully it will upgrade the node images and fix the missconfiguration.

**Comment by xuto2** [comment]
@4iter4life for vm agent pool, you can actually scale down the node count to 0 and then scale back to your desired count, the new vm will have the fix.

**Comment by pietervincken** [comment]
We're experiencing the same issue on multiple of our clusters as well. The timing between nodes is off by up to 6 minutes. One of our development clusters is recreated every night, so it has the latest image (I presume?) and it still has the issue.

**Comment by 4iter4life** [comment]
we upgraded yesturday to v1.18.10 and it looks good now.

**Comment by pietervincken** [comment]
@xuto2 Any chance that that fix hasn't reached our setup yet? Some nodes are only a few days old (way younger than the Nov 9 you've mentioned). As it seems resolved for @4iter4life, should we try to recreate as well?

**Comment by xuto2** [comment]
@pietervincken  Are you using vmss? If so, yes you need to recreate the vmss (not just adding a new vm in the existing vmss, as the bad setting was stored in the vmss once it was created. The only way to get it fixed for vmss is recreating it, node image upgrade or k8s upgrade are just the recommended ways to trigger the recreation)

**Comment by xuto2** [comment]
closing as issue should be resolved now.

**Comment by pietervincken** [comment]
@xuto2 it turned out to be a missing route in our routing table that prevented the nodes from reaching the NTP server. Thank you for the quick responses.
