### ISSUE TITLE
looking for the updated sdk /nugget for aks - to use Ephemeral disk option

### ISSUE THREAD

**Issue by digeler** [Azure/AKS#1995]
**What happened**: Trying to set in c# sdk the ephemeral disk not able to find it.
currently using : "Microsoft.Azure.Management.ContainerService" Version="1.1.0"
official doc:
https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#ephemeral-os

official restapi does not show this rest call : 
https://docs.microsoft.com/en-us/rest/api/aks/agentpools/createorupdate
**What you expected to happen**:
seems like there is no updated sdk for c# ,for aks yet 
**How to reproduce it (as minimally and precisely as possible)**:
just use the latest sdk

**Anything else we need to know?**: no ,just asking when it is going to be released ?

**Comment by digeler** [comment]
Any updates please ?

**Comment by digeler** [comment]
any updates on this ?

**Comment by miwithro** [comment]
@digeler are you still having this issue on the latest SDK release?
