### ISSUE TITLE
How to scale Azure's Kubernetes Service (AKS) based on GPU metrics?

### ISSUE THREAD

**Issue by KarFan-FS** [Azure/AKS#1996]
### Problem
I am trying to implement a Horizontal Pod Autoscaler (HPA) on my AKS cluster. However, I'm unable to retrieve the GPU metrics (auto-generated by Azure) that my HPA requires to scale.

### Example
As a reference, see [this example](https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-scale#autoscale-pods) where the HPA scales based on `targetCPUUtilizationPercentage: 50`. That is, the HPA will deploy more/less pods to achieve a target of an average CPU utilization across all pods. Ideally, I want to achieve the same with the GPU.

### Setup
I have deployed an AKS cluster with Azure Monitor enabled and my node size set to `Standard_NC6_Promo` - Azure's VM option that comes equipped with Nvidia's Tesla K80 GPU. However, in order to utilize the GPU, you must first install the appropriate plugin into your cluster, as explained [here](https://docs.microsoft.com/en-us/azure/aks/gpu-cluster). Once you install this plugin a number of GPU metrics are automatically collected by Azure and logged to a table named "InsightsMetrics" ([see](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-gpu-monitoring)). From what I can read, the metric `containerGpuDutyCycle `will be the most beneficial for monitoring GPU utilization.

### Current Situation
I can successfully see the insight metrics gathered by installed plugin, where one of the metrics is `containerGpuDutyCycle`.

Now how to expose/provide this metric to my HPA?

### Possible Solutions
What I've noticed is that if you navigate to the Metrics tab of your AKS cluster, you cannot retrieve these GPU metrics. I assume this is because these GPU "metrics" are technically logs and not "official" metrics. However, azure does support something called [log-based metrics](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/app-insights-metrics), where the results of log queries can be treated as an "official" metric, but nowhere do I see how to create my own custom log-based metric.

Furthermore, [Kubernetes supports custom and external metrics](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-metrics-apis) through their Metrics API, where metrics can be retrieved from external sources (such as Azure's Application Insights). Azure has an implementation of the Metrics API called [Azure Kubernetes Metrics Adapter](https://github.com/Azure/azure-k8s-metrics-adapter). Perhaps I need to expose the `containerGpuDutyCycle `metric as an external metric using this? If so, how do I reference/expose the metric as external/custom?

### Alternative Solutions
My main concern is exposing the GPU metrics for my HPA. I'm using Azure's Kubernetes Metrics Adapter for now as I assumed it would better integrate into my AKS cluster (same eco-system). However, it's in alpha stage (not production ready). If anyone can solve my problem using an alternative metric adapter (e.g. [Prometheus](https://prometheus.io/)), that would still be very helpful.

Many thanks for any light you can shed on this issue.

**Comment by hbakkerit** [comment]
Having the same issue, curious to learn if there's a way to scale based on those GPU metrics.

**Comment by alexeldeib** [comment]
I'm not an expert in GPU compute, but I think the path you're pursuing w.r.t custom metrics is the right approach so far. That GPU metrics come in as logs is a bit of a wrench there. Have you looked at KEDA (since that's basically the successor to the custom metrics solution you linked)? https://keda.sh/docs/2.0/scalers/azure-log-analytics/ seems quite similar to what you want.

maybe @jsturtevant has some context here since he seems to have touched the metrics adapter a bit.

**Comment by hbakkerit** [comment]
I've found that KEDA also supports Azure Monitor, as opposed to Azure Log Analytics, which in turn supports GPU monitoring on AKS: 
https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-gpu-monitoring
https://keda.sh/docs/2.0/scalers/azure-monitor/

This might be a good route to take as well.

**Comment by KarFan-FS** [comment]
Thanks gents, this looks promising! I've stopped working on this task for now but when I get back to it I'll let you know how I get on!
