### ISSUE TITLE
kubectl is not working on CloudShell?

### ISSUE THREAD

**Issue by MrBRUE** [Azure/AKS#20]
Hi, I am trying to follow your tutorial over at https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough.

I am getting early on some exception like this:
az aks create --resource-group moeKubernetesTst --name myK8sCluster --agent-count 1 --generate-ssh-keys

ERROR shortly thereafter:
Deployment failed. Correlation ID: cc5b9754-49bc-4170-bffd-23ff4f1f1612. unable to create resource group. error: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'c2b660ac-8354-4c31-a1c7-6dcdf8015550' with object id 'c2b660ac-8354-4c31-a1c7-6dcdf8015550' does not have authorization to perform action 'Microsoft.Compute/register/action' over scope '/subscriptions/(...)

Running kubectl would give me this:
kubectl get nodes
Error from server (BadRequest): the server rejected our request for an unknown reason

What's the matter? Thanks!

**Comment by berndverst** [comment]
Did you register the AKS service via
`az provider register -n Microsoft.ContainerService`

and did you first create your resource group in uswest2 or ukwest?
`az group create -n moeKubernetesTst -l ukwest`

It doesn't sound like your AKS was ever created because the resource group you want to use doesn't exist or couldn't be used. You could check the deployment status via `az aks list`.

If AKS was created successfully you'll download the kube config via `az aks get-credentials --resource-group=moeKubernetesTst --name=myK8sCluster`

After that time you can run `kubectl get nodes` etc

**Comment by MrBRUE** [comment]
Hi Bernd, I have done all of that.
Now I decomissioned the RG in ukwest and re-created it in uswest2.
Then I did
`az aks create --resource-group moeKubernetesTst --name moesK8sCluster --agent-count 1 --generate-ssh-keys`

(I changed as well the name of the cluster this time.)

And it says:

> Deployment failed. Correlation ID: 38a4dc73-c1a2-4ecd-99f8-663d1868c3fd.

az aks list returns this:

{
    "id": "/subscriptions/(xxx)/resourcegroups/moeKubernetesTst/providers/Microsoft.ContainerService/managedClusters/moesK8sCluster",
    "location": "westus2",
    "name": "moesK8sCluster",
    "properties": {
      "accessProfiles": null,
      "agentPoolProfiles": [
        {
          "count": 1,
          "name": "agentpool1",
          "osType": "Linux",
          "storageProfile": "ManagedDisks",
          "vmSize": "Standard_D2_v2"
        }
      ],
      "dnsPrefix": "moesK8sClu-moeKubernetesTst-0b7a0e",
      "fqdn": null,
      "kubernetesVersion": "1.7.7",
      "linuxProfile": {
        "adminUsername": "azureuser",
        "ssh": {
          "publicKeys": [
            {
              "keyData": "ssh-rsa (xyz)"
            }
          ]
        }
      },
      "provisioningState": "Failed",
      "servicePrincipalProfile": {
        "clientId": "05ae1a7e-50ae-4a23-9394-2d4810211ec7"
      }
    },
    "resourceGroup": "moeKubernetesTst",
    "type": "Microsoft.ContainerService/ManagedClusters"
  }

**Comment by berndverst** [comment]
@MrBRUE Yes there were deployment problems in USWest2 because of capacity constraints :( 

Try again now? See https://github.com/Azure/AKS/issues/2

**Comment by MrBRUE** [comment]
Hi @berndverst , I am trying it again now and it looks better.

I really had to download the kube config however, should maybe added to the walk-through?

There is still an issue though: `kubectl get nodes` does not work, would return:
`No resources found.`
I am still able to deploy services.

The command from the walk-through here works fine.
`kubectl get service azure-vote-front --watch`

How long does it take to get an external IP? Watching for 5 minutes already.

**Comment by berndverst** [comment]
@MrBRUE the `az aks get-credentials` command actually downloads the kube config. If that didn't work for you it would be great to further look into that (but as a separate Github issue).

If your services deploy successfully and  both `kubectl get pods` and `kubectl get service` work for you then things are working correctly. I'll have to check to see if `kubectl get nodes` is actually expected to work.

In my experience getting an external IP takes up to 10 minutes. 20 minutes is unusual, but I believe there are still some remaining capacity problems (#2) and associated provisioning delays with the AKS service in this current preview phase.

**Comment by MrBRUE** [comment]
Hi, I will try that, Bernd. For now all I can tell you is that there are still no external IPs assigned, so for more than 1 day. I'll try again later and see if it makes a difference, and again in uswest2. Will keep you posted...

**Comment by MrBRUE** [comment]
Created everything from scratch, @berndverst - new Resource Group, new clustername.
`kubectl` get nodes still gives me `No resources found.`

And here we go again:
```
kubectl create -f superduper.yml
deployment "azure-vote-back" created
service "azure-vote-back" created
deployment "azure-vote-front" created
service "azure-vote-front" created
m@Azure:~/clouddrive$ kubectl get service azure-vote-front --watch
NAME               TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
azure-vote-front   LoadBalancer   10.0.114.88   <pending>     80:31407/TCP   11m
```

**Comment by brendandburns** [comment]
@MrBRUE can you try two things, IP address can take up to twenty minutes to show up.

If it still hasn't, please try `kubectl describe services azure-vote-front` and paste what you see into this issue.

Thanks!
--brendan

**Comment by MrBRUE** [comment]
Hi @brendandburns , here is the output:
```
kubectl describe services azure-vote-front
Name:                     azure-vote-front
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 app=azure-vote-front
Type:                     LoadBalancer
IP:                       10.0.114.88
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  31407/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                      Age                 From                Message
  ----     ------                      ----                ----                -------
  Normal   CreatingLoadBalancer        3m (x249 over 20h)  service-controller  Creating load balancer
  Warning  CreatingLoadBalancerFailed  3m (x249 over 20h)  service-controller  Error creating load balancer (will retry): Failed to create load balancer for service default/azure-vote-front: network.SecurityGroupsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="Unknown" Message="Unknown service error"
```

**Comment by MrBRUE** [comment]
Hi @brendandburns and @berndverst do you have any idea what might cause the trouble?
Now this is what I am getting:

```
@Azure:~$ kubectl describe services azure-vote-front
Unable to connect to the server: net/http: TLS handshake timeout
```

**Comment by slack** [comment]
@MrBRUE as we remove feature flags from regions, you will need to re-register your subscription. We are working on handling this for you. For the time being `az provider register --namespace Microsoft.ContainerService` should get you up and running.

Additionally, we have new infrastructure deployed in East US and West Europe, I suggest you use those regions for now.

**Comment by MrBRUE** [comment]
Hi, that still does not seem to be working?

> az aks create --resource-group kuffi2 --name mclust --node-count 1 --generate-ssh-keys Operation failed with status: 'Bad Request'. Details: Required resource provider registrations Microsoft.Compute are missing.

Speaking of which, did you recently as well change agent-count into node-count?
`az: error: unrecognized arguments: --agent-count 1`

**Comment by MrBRUE** [comment]
Yeah @brendandburns it worked now, using as well eastus location and the additional registration made it work for me. Thanks! Great stuff! Will be immensely useful.
