### ISSUE TITLE
az aks upgrade looses labels on nodes

### ISSUE THREAD

**Issue by alktlr** [Azure/AKS#200]
Upgraded aks from 1.7.7 to 1.8.7 which caused deployment to fail because it had defined a nodeSelector. I had to recreate the node labels after the upgrade.

**Comment by t1agob** [comment]
Any news on this one?

**Comment by jnoller** [comment]
Currently it is a known issue that AKS upgrades removes existing labels - See https://github.com/Azure/AKS/issues/468 which has a longer conversation in it. I'm going to close this one out for now.
