### ISSUE TITLE
ACR integration with managed identity doesn't work after upgrade to 1.19.3 

### ISSUE THREAD

**Issue by kmorkans** [Azure/AKS#2000]
**What happened**:

After upgrade to 1.19.3 AKS integration with ACR with managed identity stopped working.
Logs show `403 forbidden` when pulling images.

**How to reproduce it (as minimally and precisely as possible)**:

Upgrade cluster from 1.18.10 to 1.19.3.
Tried to remove created IAM role assignment and recreate with `az aks update -n myAKSCluster -g myResourceGroup --attach-acr <acr-name>` but that didn't help.
Not sure about newly created clusters.

**Comment by yangl900** [comment]
hi @kmorkans 

I have a kubectl plugin to diagnostic this issue https://github.com/yangl900/canipull

you could give a try, it should give you rich information on what is missing.

**Comment by kmorkans** [comment]
Thanks @yangl900 
Seems that issue is related to https://github.com/containerd/containerd/issues/4684
`403 forbidden` followed after that error.
