### ISSUE TITLE
VM has reported a failure when processing extension 'vmssCSE'. Error message: "Enable failed: failed to execute command: command terminated with exit status=52 [stdout] aks-system-123266-vmss000000 Connection to mcr.microsoft.com 443 port [tcp/https] succeeded! [stderr] " 

### ISSUE THREAD

**Issue by megharaikwar** [Azure/AKS#2004]
**What happened**:
I am trying to create an AKS Cluster using Terraform through Azure Devops pipeline. The pipeline is running for around 18 minutes and then erroring out with the error. Every other resources are created but virtual machine scale sets failed.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Create a simple pipeline with terraform init and terraform apply

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.10
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by smynes** [comment]
Same issue here.  Trying to configure a private aks.  Using custom DNS, so we've linked the vnet for our DNS servers to the private DNS zone and our DNs servers are using the Azure specified DNS server , 168.63.129.16, as the forwarder / upstream DNS server.  The vnets in use for the aks and associated acr both have internet access.  The error persists whether we use custom settings for the aks service CIDR/DNS service IP/Docker bridge CIDR or take the defaults.  Multiple cases open with support on this.  Wil update if any progress.

**Comment by yangl900** [comment]
52 means ERR_K8S_API_SERVER_DNS_LOOKUP_FAIL

https://github.com/Azure/AgentBaker/blob/821b8212802c02982a611ea74c4ba46c798f556c/pkg/agent/testdata/AKSUbuntu1604%2BEnablePrivateClusterHostsConfigAgent/line9.sh#L37

That typically means the node was not able to resolve the private DNS name. Was the DNS zone associated to the custom DNS subnet?

AKS also has some improvements on the DNS handling to rollout soon, to avoid the manual attachment. @feiskyer could you comment more?

**Comment by feiskyer** [comment]
For custom DNS, please refer the docs https://docs.microsoft.com/en-us/azure/aks/private-clusters#hub-and-spoke-with-custom-dns. [here](https://github.com/Azure/terraform/tree/master/quickstart/301-aks-private-cluster) is an example of terraform deployment with custom DNS.

**Comment by megharaikwar** [comment]
Thank you @feiskyer  and  @yangl900 for your answers. I am trying to create an azure release pipeline in which I would like to add  this bash script which should run in parallel with the terraform apply so that it can create the virtual link during the cluster provisioning. Do you think its achievable currently to run tasks in parallel in the release pipeline?

**Comment by feiskyer** [comment]
@megharaikwar I'm not sure. I think you can make some test. It should work if the two jobs are running parallelly.

**Comment by etiennejournet** [comment]
Hi,

Same problem here, provisionning private cluster with terraform.
The zone gets created in the k8s resource_group (the custom one for k8s resource) and is properly linked to my vnet. (in about 5' terraform time).
Then for 5 other minutes nothing happens and it fails at 10'.

Any input on that ?

**Comment by megharaikwar** [comment]
I tried using the script for creating the link between private dns and custom dns, solution provided by @feiskyer , thanks a lot. I am using Azure Devops for the release pipeline and ran the terraform and script in parallel and it worked fine. @feiskyer thanks again.

@smynes may be you can try the same thing.

I will close this issue now.
