### ISSUE TITLE
Improve Windows Server cluster monitoring

### ISSUE THREAD

**Issue by toma567** [Azure/AKS#2005]
Currently only pod environments are monitored. It would be nice to have disk storage capacity, memory rss metrics,... for Windows nodes

**Comment by vishiy** [comment]
@toma567 - This is in our backlog. We will look into it as we progress.

**Comment by vishiy** [comment]
We will be starting to work on disk metrics for windows soon.

**Comment by saaror** [comment]
We are already working on it. Windows nodes doesn't support memory RSS. We can provide memory working set. @toma567
