### ISSUE TITLE
Redirect missing in release notes

### ISSUE THREAD

**Issue by timja** [Azure/AKS#2009]
https://aka.ms/aks/transparent-mode doesn't go anywhere, @palma21

**Comment by palma21** [comment]
It's working for me. Timing issue perhaps? The doc was published about the same time as the rel notes so you might have found it a bit before maybe? Lmk if it's still not working for you.

**Comment by zhiweiv** [comment]
Works now, it didn't work at the monment of the release note appear.

**Comment by timja** [comment]
Works now
