### ISSUE TITLE
ACR pull fails because of error  label key and value greater than maximum size (4096 bytes)

### ISSUE THREAD

**Issue by daseth** [Azure/AKS#2010]
**What happened**:
After upgrade to AKS 1.19.3 running containerd 1.4.1 we see this issue when running one of our apps. 
We believe we are hitting this bug: https://github.com/containerd/containerd/issues/4684

**What you expected to happen**:
In older versions of AKS (1.18.8) this very same image worked without issues even with the labels it has on it.
We expect the same image to run without issues on 1.19.3 or to have a workaround to run our image.

**How to reproduce it (as minimally and precisely as possible)**:
The root cause of that seems to be at https://github.com/containerd/containerd/blob/master/pkg/cri/server/image_pull.go#L493 where the layer digest list is placed into a label. With a 39 character key, and 72 characters per digest (including the trailing comma), it appears that this will fail with more than 56 layers.

**Anything else we need to know?**:
We believe this was fixed in v1.4.2 of containerd
https://github.com/containerd/cri/pull/1602
Please validate if this is the case and back port it to AKS 1.19.x

**Environment**:
- Kubernetes version (use `kubectl version`):
 kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:08Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
web frontend for dotnet app
- Others:

**Comment by eriksywu** [comment]
Hi @daseth thanks for providing details. containerd v1.4.3 is on its way soon. I will update this ticket once it's rolled out.

**Comment by eriksywu** [comment]
v1.4.3 has been rolled out to all regions

**Comment by daseth** [comment]
Latest node image running containerd 1.4.3 solves the initial issue. Thank you for helping.
