### ISSUE TITLE
AKS create command fails for pod-managed identities in Azure Kubernetes Service (Preview)

### ISSUE THREAD

**Issue by magooster** [Azure/AKS#2011]
AKS create command fails for pod-managed identities in Azure Kubernetes Service (Preview)

az aks create -g myResourceGroup -n myAKSCluster --enable-managed-identity --enable-pod-identity

The behavior of this command has been altered by the following extension: aks-preview

BadRequestError: Operation failed with status: 'Bad Request'. Details: Network plugin kubenet is not supported to use with PodIdentity addon.

Seems you need to use azure network plugin - so need to add following command option

--network-plugin azure

Is their any option to enable pod-identity add-on with kubenet networking? (It's possible to override if installing via Helm chart or manually.)

**What you expected to happen**:

AKS cluster created with AAD pod identities enabled

**How to reproduce it (as minimally and precisely as possible)**:

az aks create -g myResourceGroup -n myAKSCluster --enable-managed-identity --enable-pod-identity

**Anything else we need to know?**:

N/A

**Comment by miwithro** [comment]
@magooster we already fixed this.  Can you ensure you are running the azure-preview extension version 0.4.68 or later?

**Comment by b-odonoghue** [comment]
@miwithro Are you sure this has been fixed? I don't find any extension called `azure-preview` but I do have the `aks-preview` at .0.5.2 and when I try the command from this issue it still fails.

```
➜  Desktop az aks create -g rg-devops-dev-eastus -n testAKSCluster --enable-managed-identity --enable-pod-identity
The behavior of this command has been altered by the following extension: aks-preview
Operation failed with status: 'Bad Request'. Details: Network plugin kubenet is not supported to use with PodIdentity addon.
➜  Desktop az extension list --output table
Experimental    ExtensionType    Name         Path                                              Preview    Version
--------------  ---------------  -----------  ------------------------------------------------  ---------  ---------
False           whl              aks-preview  /Users/username/.azure/cliextensions/aks-preview  True       0.5.2
```

**Comment by b-odonoghue** [comment]
My apologies I had been running the wrong aks-preview extension version. I needed to be on 0.5.3 or greater for the commands to work along with `--enable-pod-identity-with-kubenet`
