### ISSUE TITLE
Planned Maintenance Window

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#2014]
Support for setting a planned maintenance window for the AKS weekly releases, platform maintenance and any automatic operations like automatic upgrades.  https://docs.microsoft.com/en-us/azure/aks/planned-maintenance

**Comment by sureshgoli25** [comment]
t seems, the maintenance window having no effect on the auto upgrade channel on our test clusters. As we do not see node image upgrades happening during specific day and time in maintenance window. Also, there are no events or logs available to trace back.

**Comment by PixelRobots** [comment]
@sureshgoli25 what upgrade channel have you chosen for your cluster?  Only one will update the node images currently.

**Comment by sureshgoli25** [comment]
Node images. It worked with maintenance window in around 11-Aug. Afterwords, there are no upgrades are happening. Though there are new node images available.

**Comment by PixelRobots** [comment]
Hmm seems strange. Have you disabled and reenabled the auto update and recreated the maintenance window? 

Might be worth a try as it is still in preview and things can change.

**Comment by sureshgoli25** [comment]
Will try that as well and report back next week. As our preferred scheduled is usually Sundays early mornings...

**Comment by palma21** [comment]
It worked on my test just now, but please do open a ticket if you don't see it working as expected. +@qpetraroia

**Comment by Kaarthis** [comment]
We are looking at extending the planned maintenance window into Planned maintenance groups to group your clusters by region and by categories like Test , Dev, Production etc.  Stay tuned for updates here.

**Comment by PixelRobots** [comment]
Nice!  Just need to also be able to update node images and k8s versions automatically in these windows. Not just one or the other like we currently have.

**Comment by vermegi** [comment]
I have a customer asking whether we can add timezone and recureEvery to the config of planned maintenance, similar to how you can configure VM planned maintenance. 
They currently need separate config for summer and winter time in their timezone.

**Comment by philwelz** [comment]
hey @palma21  @Kaarthis-zz we are using this preview feature for 2 AKS clusters (1.22.6, westeurope) and the upgrade channel is `node-image`. The configured maintenance window (Thursday 2-3 am UTC) seems to not have any effect as the cluster just updates nodes during daytime like today.  I will open a ticket later as it is a customer subscription but do you have any advise?

**Comment by kaarthis** [comment]
Typically for Auto upgrade (Upgrader) can take upto 1 day (ideally few hours) from the start of the Window to effect the upgrades this is something we noticed internally and are looking to document it in the Public docs soon. We shall try to improve the accuracy of the upgrader wrt to schedule as best as possible in future.
