### ISSUE TITLE
How is effected AKS by deprecation of docker from k8s

### ISSUE THREAD

**Issue by boraozkan** [Azure/AKS#2016]
**What happened**:
Docker will be deprecated form k8s in v1.20
**What you expected to happen**:
AKS will handle this changing.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
If you’re using a managed Kubernetes service like GKE, EKS, or AKS (which defaults to containerd) you will need to make sure your worker nodes are using a supported container runtime before Docker support is removed in a future version of Kubernetes. If you have node customizations you may need to update them based on your environment and runtime requirements. Please work with your service provider to ensure proper upgrade testing and planning.

https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/
**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by tomkerkhove** [comment]
ContainerD is now the default container runtime: https://github.com/Azure/AKS/releases/tag/2020-11-16

**Comment by seanmck** [comment]
Correct. ContainerD is not only the default but the _only_ container runtime option starting from 1.19, so new and upgraded clusters will get it automatically (for Linux) as of that Kubernetes version. We are also actively working on containerd support for Windows.
