### ISSUE TITLE
Verbose node pool upgrade status logs in portal

### ISSUE THREAD

**Issue by sfc-gh-jkhan** [Azure/AKS#2017]
**What happened**:
Our AKS upgrades (control plane and node pools) are done through the pulumi provisioning tool and not directly with azcli. As such we don't get any status updates or logs on the upgrade during the operation which can sometimes take > 1 hr for node pools.

**What you expected to happen**:
I was looking for more of a detailed log stream telling me what node was now being drained/terminated and if there were any exceptions (kind of like what kubectl drain would give you) directly on the portal. That would help us to see if any of our configs (PDBs on singular pods) were causing drain issues, since at the moment we only get that info after opening support cases when someone looks at the backend for us. Also if these logs stuck around for a while after the operation it would be great.

**How to reproduce it (as minimally and precisely as possible)**:
Perform AKS cluster upgrades through a third-party provisioning tool (such as https://www.pulumi.com/) rather than azcli.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-20T16:22:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by phealy** [comment]
@sfc-gh-jkhan A new portal view was recently released that shows each node in your node pool and what the current status is via the portal. By drilling down you can see what the workloads are on that node and get state/event information for them. This should help you troubleshoot any drain issues during an upgrade. Please let me know if there's any other followup you have on this issue!

![image](https://user-images.githubusercontent.com/3046014/129940292-42eeab85-81dc-4950-9400-ca181ddf110f.png)

![image](https://user-images.githubusercontent.com/3046014/129940333-7c028881-c42f-46d7-81cc-ff4cb61979a5.png)
