### ISSUE TITLE
[FR] Allow distinct users for SSHing on AKS nodes

### ISSUE THREAD

**Issue by djsly** [Azure/AKS#2018]
**What happened**:
AKS allows for a single service user to be configured for SSHing into nodes

**What you expected to happen**:
AKS should allow distinct users to ensure security audit can be pass with success (no one likes when service account are used for SSHing)

**How to reproduce it (as minimally and precisely as possible)**:
Deploy AKS with a linux Profile

CC: @seanmck

**Comment by palma21** [comment]
Would blocking SSH altogether and provide a k8s-native way to access the node work for you?
K8s audit logs would have that as well as potentially azure activity logs.

**Comment by djsly** [comment]
We are currently disabling SSH access from the pod to the nodes to also help reducing the attack surface using NetPols... This is one of the number one best practice you learn when trying to secure a Kubernetes cluster. 

This article recommend doing it at the NSG which is problematic when you are using Azure CNI. (since both the nodes/pods' IPs on in the same CIDR)
https://www.stackrox.com/post/2020/02/azure-kubernetes-aks-security-best-practices-part-2-of-4/ 

I think the requirements from multiple Security Audits are

1. each node access needs to be traceable to a single user. 
2. the node network should be accessible from a centralized location (doable with the tools we have in place -- limit Apiserver IP source, or using private cluster + bastion)

We tried using the Bastion you guys provide with AKS, but that doesn't allow for SSH access using User Keys. only password and doesn't solve the distinct user per node access.

**Comment by palma21** [comment]
Right, let me clarify. We're planning on removing SSH altogether from the base image, and providing a k8s native way to deliver the same functionality, which would be rooted in an exec-style capability. Which in turn would be audited on the k8s side and controllable via RBAC.

It seems to meat both your requirements? What do you think?

**Comment by djsly** [comment]
I think this would work perfectly!

Do you mean an AKS or a K8S native way ? If there is some work being worked on upstream with respect to that, feel free to share.  I would be curious to learn how this would work. e.g would that mean going over the kubelet API for exec ?

**Comment by palma21** [comment]
A bit of both. AKS UX but k8s native way. Happy to share more as we finalize designs!

**Comment by lorenzo-biava** [comment]
The K8S native way seems a nice alternative (indeed it has better authZ/N controls built in), but what if the kubelet/docker/containerd stops responding (or there are some K8S-related failures in the node)?
How would we be able to access the node in such scenario?

PS: is the K8S-native solution you're envisioning also going to support Windows nodes?

If you don't mind the reference to other cloud providers, I think that some kind of Identity Aware SSH proxy made available Azure-wide would probably be a more flexible and robust solution to SSH in every VM (be it K8s or not). That way we could leverage the authZ/N & auditing features of the Azure platform itself.

**Comment by miwithro** [comment]
@djsly what about these options as an alternative to ssh?

https://docs.microsoft.com/en-us/azure/active-directory/devices/howto-vm-sign-in-azure-ad-windows

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/login-using-aad

**Comment by djsly** [comment]
Hey @miwithro , I quickly glanced over the doc and looks good from an high level. 

I definitely have questions on the access requirements and/or the networking requirements. (e.g. private cluster support / private vnet support / etc) 

but this looks good, from what I have been told, the tunnel will also be leveraged to help with the direct node access.

**Comment by djsly** [comment]
@miwithro  could we get more info on the "debugging" pod spec, if you have a manifest to share that would be perfect.

**Comment by djsly** [comment]
@miwithro any issues where we can track that ? is the ssh-over-aad the way to go still ?

**Comment by CocoWang-wql** [comment]
https://github.com/Azure/AKS/issues/2898
The feature is in plan. We will leverage an extension to allow  only users in the aad group to ssh to the node

**Comment by miwithro** [comment]
Track issue in #2898 closing as a duplicate.
