### ISSUE TITLE
[FR] Expose Control Plane maintenance/upgrade work to users over events

### ISSUE THREAD

**Issue by djsly** [Azure/AKS#2019]
**What happened**:
When AKS performs the control plane upgrades, we would like to have visibility to help investigating issues that might arise from them. 

**What you expected to happen**:
know when upgrades are done by regions/cluster

**Anything else we need to know?**:
Maybe we could have a resource Health event ?

CC: @seanmck

**Comment by neumanndaniel** [comment]
@djsly Azure Resource Health for AKS is in preview: https://docs.microsoft.com/en-us/azure/aks/aks-resource-health

> These signals range from auto-resolving issues, **planned updates**, unplanned health events, and unavailability caused by user-initiated actions. 
https://docs.microsoft.com/en-us/azure/aks/aks-resource-health

**Comment by neumanndaniel** [comment]
Being more precisely, I have seen some resource health events on our AKS clusters indicating a planned control plane upgrade/update.

**Comment by seanmck** [comment]
Yes, control plane upgrades are captured in resource health:

![image](https://user-images.githubusercontent.com/11199476/104039839-c0b01000-518b-11eb-8b1c-eb4594ab949a.png)

**Comment by seanmck** [comment]
Let me know if that doesn't cover what you're looking for @djsly.

**Comment by djsly** [comment]
thanks, we will look how we can consume those health event properly since that last time we tried using them with Terraform it was sort of a mess :(
