### ISSUE TITLE
AKS with Web Application Gateway 

### ISSUE THREAD

**Issue by just-olaakinyemi** [Azure/AKS#202]
I have AKS with Web Application Gateway working with Azure Vote App but wouldn't work with my app.

These are the step perform to get the Azure Vote App to work:

1. Created the AKS Cluster with and deployed the app with the annotation to create an Internal loadbalancer
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"

2.  Created the AppGateway with its own VNET. 

3.  Peered the AKS VNET  with the AppGateway VNET

4.  Assigned the Internal loadbalancer IP to the backend of the AppGateway .

That worked fine. 

Replicating the same step for my app did not work. but when i did without the annotation for external load balancer, that worked. 

I will like to get the steps mentioned above work for me, how or what can be done to achieve this.
Also can the VNET CIDR AKS be specified in the template, if so, how.

**Comment by torstenkuhn77** [comment]
https://github.com/Azure/AKS/issues/90 states that AKS right now does not support VNET peering

**Comment by hibri** [comment]
@torstenkuhn77  we plan to run it all in the same Vnet.

**Comment by tslavik** [comment]
OK for right now, but when we will be supported? It could be fine to have it in preview and test it.

**Comment by just-olaakinyemi** [comment]
I had a solution that works for me and i uploaded it to my GitHub and made a YouTube video of it:

https://github.com/kizotheitguy/Azure-AKS-ApplicationGateway-WAF
https://www.youtube.com/watch?v=GkznBbNSq7U

Will see what aks come up with when they fully support this

**Comment by Bougyz** [comment]
I peer the network yet I am getting 502
