### ISSUE TITLE
CoreDNS custom ConfigMap is present and empty preventing it from being managed by Terraform

### ISSUE THREAD

**Issue by djsly** [Azure/AKS#2020]
**What happened**:
On a new AKS cluster, the coredns ConfigMap comes pre created but empty, If we want to manage this resource using the kubernetes provider in Terraform, it complains that the resource already exists (and isn't managed by the provider)

**What you expected to happen**:
not have a empty ConfigMap

**How to reproduce it (as minimally and precisely as possible)**:
install a fresh AKs cluster. look at the configmaps in kube-system namespace

CC: @seanmck

**Comment by neumanndaniel** [comment]
@djsly Temporary workaround is a `terraform import` to bring the already existing custom CoreDNS ConfigMap under TF's management.

But I am with you that the other way around is more straight forward.

**Comment by djsly** [comment]
thanks @neumanndaniel , the problem with this approach is that it works well if you decouple your cluster creation with its provisioning phase. In our case we are tying both phases with the same `terraform apply` command :(

**Comment by Lunik** [comment]
I have tried deleting it by hand and then running `terraform apply` but there is a process which recreate the file automaticaly if missing

**Comment by 0dragosh** [comment]
Also encountering this, please fix it.

**Comment by myhau** [comment]
I've also experienced this problem. `terraform import` feels hacky here and would complicate our infra CI/CD pipeline a lot.

**Comment by ebunassar** [comment]
Same issue here. Makes it nearly impossible to provision and bootstrap a cluster with custom dns entries.

**Comment by vamsee-konda** [comment]
+1 to this issue, please fix.

**Comment by djsly** [comment]
this is how we are working around this issue 

```
# the next two null resources create the coreDNS custom config to allow using custom DNS server for specific domain
# See ref https://docs.microsoft.com/en-us/azure/aks/coredns-custom
resource "null_resource" "coredns-custom" {
  count = length(local.custom_dns) > 0 ? 1 : 0
  triggers = {
    content = local.rendered_coredns_custom_configmap
  }
  provisioner "local-exec" {
    command = "echo \"$kubeconfig\" > kubeconfig_coredns_custom"
    environment = {
      kubeconfig = azurerm_kubernetes_cluster.aks.kube_admin_config_raw
    }
  }
  provisioner "local-exec" {
    command = <<-EOS
      kubectl --kubeconfig kubeconfig_coredns_custom replace -f -<<EOF
      ${local.rendered_coredns_custom_configmap}
      EOF
EOS
  }
  provisioner "local-exec" {
    command = "rm -f kubeconfig_coredns_custom"
  }
}

resource "null_resource" "delete-coredns-custom" {
  count = length(local.custom_dns) == 0 ? 1 : 0
  provisioner "local-exec" {
    command = "echo \"$kubeconfig\" > kubeconfig_coredns_custom"
    environment = {
      kubeconfig = azurerm_kubernetes_cluster.aks.kube_admin_config_raw
    }
  }
  provisioner "local-exec" {
    command    = "kubectl --kubeconfig kubeconfig_coredns_custom -n kube-system delete configmaps/coredns-custom --force=true --grace-period=0 --wait=false"
    on_failure = continue
  }
  provisioner "local-exec" {
    command = "rm -f kubeconfig_coredns_custom"
  }
}

```

**Comment by rbankole** [comment]
any updates on this? hard to bootstrap without custom dns using terraform. thx

**Comment by tsurankov** [comment]
I think I managed this using another terraform provider https://registry.terraform.io/providers/gavinbunney/kubectl/latest
It allows to overwrite existing resources.
Here is the example. A custom CoreDNS configuration is located in the separate file named `Corefile` in the module's folder.
```
locals {
  data = {
    "Corefile" = file("${path.module}/Corefile")
  }
}

resource "kubectl_manifest" "this" {
  yaml_body = yamlencode(
    {
      "apiVersion" = "v1"
      "kind"       = "ConfigMap"
      "metadata" = {
        "name"      = "coredns"
        "namespace" = "kube-system"
        labels = {
          "eks.amazonaws.com/component" = "coredns"
          "k8s-app"                     = "kube-dns"
        }
      }
      "data" = merge(
          local.data,
          var.data
      )  
    }
  )
  force_new = true
}
```

**Comment by darose** [comment]
This is still an issue, and is not stale.  Please do not close.

**Comment by Lunik** [comment]
This is still an issue, and is not stale. Please do not close.

**Comment by bateau84** [comment]
This is still an issue, and is not stale. Please do not close.

**Comment by darose** [comment]
This is still an issue, and is not stale. Please do not close.

**Comment by ChristianGmw** [comment]
Bad bot. Issue still very much alive and not stale.

**Comment by samartzidis** [comment]
You can use the **kubernetes_config_map_v1_data** resource.

**Comment by jstanesic** [comment]
@samartzidis I have tested using kubernetes_config_map_v1_data resource and it works. Terraform no longer complains about preexisting config map and instead modifies it.
