### ISSUE TITLE
Trying to update AKS cluster nodes OS image to latest patch level without upgrading Kubernetes

### ISSUE THREAD

**Issue by jmos5156** [Azure/AKS#2022]
**What happened**:

Trying to upgrade windows node pool os image to latest patch level using this document
https://docs.microsoft.com/en-us/azure/aks/node-image-upgrade

Followed the instructions and got a colleague to do the same. Both resulted in nodes not updated.

Step 1:
`az aks nodepool get-upgrades --nodepool-name <nodepoolname> --cluster-name <clustername> --resource-group <resourcegroup>`

Yields a result of 
```
{
  "id": <Azure id>, 
  "kubernetesVersion": "1.18.10",
  "latestNodeImageVersion": "AKSWindows-2019-17763.1577.201111",
  "name": "default",
  "osType": "Windows",
  "resourceGroup": "<clustername>",
  "type": "Microsoft.ContainerService/managedClusters/agentPools/upgradeProfiles",
  "upgrades": null
}
```

Shows that the latest version available for the cluster is `AKSWindows-2019-17763.1577.201111`

Running `az aks nodepool show --resource-group <resourcegroup> --cluster-name <clustername> --name <nodepoolname> --query nodeImageVersion`

Yields a result of `AKSWindows-2019-17763.1554.201021`

So looking at the versions we can upgrade to `1577` from `1554`.

So upgrading the node-image using this command runs and returns success but does not upgrade the nodes
`az aks nodepool upgrade --resource-group <resourcegroup> --cluster-name <clustername> --name <nodepoolname> --max-surge 33% --node-image-only`

**What you expected to happen**:
Nodes run through an upgrade process similar in nature to a Kubernetes upgrade, resulting in all nodes being brought up to the latest patch levels without needing a full-on AKS upgrade.

**How to reproduce it (as minimally and precisely as possible)**:
See the above steps and associated documentation.

**Anything else we need to know?**:

**Environment**: 
Azure AKS version 1.18.10
Windows 2019 LTSC AKSWindows-2019-17763.1554.201021

- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
3 Node Pools
2 linux each with 2 nodes
1 Windows with 20 workers

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by neumanndaniel** [comment]
> **Note**
> 
> The updated Windows Server image will only be used if a cluster upgrade (control plane upgrade) has been performed prior to upgrading the node pool.

https://docs.microsoft.com/en-us/azure/aks/windows-faq#how-do-i-patch-my-windows-nodes

**Comment by jmos5156** [comment]
Following help from Azure support I have found a resolution.

Both control-plane and node pools were both on Kubernetes version 1.18.10. So We were in a stable and known position.

Running az-cli 2.16.0 with the aks-preview extension enabled produced the errors described above.

Running `az extension remove -n aks-preview`, then following the steps outlined above and in this documentation https://docs.microsoft.com/en-us/azure/aks/node-image-upgrade allowed the cluster node pool (Windows Node Pool only in this case) to have the OS kernel version upgraded to the latest availble.
