### ISSUE TITLE
Node pool scale info doesn't match real scale set size

### ISSUE THREAD

**Issue by ciacco85** [Azure/AKS#2024]
When I scale the number of nodes, the CPU/Memory info doesn't match the real size of the VM, but only the state of when the node was created

1. Add a node with, for example, 2c and 7G of memory
2. Enter inside the scale set of the resource group behind the cluster
3. Change the VM size to 4c / 16G of memory
4. In the node menu, if you scale the count to 1 to 2, the total count is 4c, 14G
4a should be 8c/32G

**Environment**:
- Kubernetes version 1.19.3 with 3 nodes: 2 node with1.19.3 and 1 node with 1.18.10

**Comment by chmill-zz** [comment]
doesn't sound like the scenario you're describing is supported. Rather than manually editing the VMSS the supported method would be to create a new node pool with the desired sku. 

https://docs.microsoft.com/en-us/azure/aks/support-policies#user-customization-of-agent-nodes

> AKS manages the lifecycle and operations of agent nodes on your behalf - modifying the IaaS resources associated with the agent nodes is not supported. An example of an unsupported operation is customizing a node pool virtual machine scale set by manually changing configurations through the virtual machine scale set portal or API.

**Comment by ciacco85** [comment]
Thank you for the explanation. Honestly it's a little bit hidden in the docs, maybe a warning somewhere in the portal should be added. Thank you for your great work with AKS!
