### ISSUE TITLE
[FR] Envelope encryption for secret encryption at rest

### ISSUE THREAD

**Issue by denniszielke** [Azure/AKS#2025]
Feature request:
Basically we want to have the secrets in etcd encrypted with a customer key in AKS using KMS (ideally storing the encryption key in customer Azure KeyVault instance).
https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#encrypting-your-data

**Comment by ngrigoriev** [comment]
@denniseik 

Did you consider https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes (CSI driver)?

**Comment by denniszielke** [comment]
Yes, but csi driver requires us to change how we use secrets in our pods. For some applications that come with existing helm charts the usage of an external vault is not possible. Technical requirements therefore demand the usage of normal kubernetes secrets while complaince requirements demand them to be encrypted.

**Comment by miwithro** [comment]
Dup of #845

**Comment by denniszielke** [comment]
@miwithro I would say they are related but they are not about the same thing. Having the option of using a KMS plugin in one thing but having the ability to explicitly use envelope encryption on secret objects is in additional requirement.

**Comment by CocoWang-wql** [comment]
Hello @pitinga, this feature request is about envelope encryption. Encryption at rest for AKS data in etcd by KMS plugin, we current have the feature in public preview. https://docs.microsoft.com/en-us/azure/aks/use-kms-etcd-encryption
