### ISSUE TITLE
Failed launching agent on Gen2 VM using ARM template

### ISSUE THREAD

**Issue by hyunsooda** [Azure/AKS#2027]
Hello,
How can I use Gen2 VM in AKS? If I want to launch agents in the shell, the solution is [here](https://docs.microsoft.com/en-us/azure/confidential-computing/confidential-nodes-aks-get-started) and working very well. 
I got the error below when I launch Kubernetes agent using a deploy script. Also, I specified the parameter `distro` value with `ubuntu-18.04-gen2` to use Gen2 VM, but it's not working and I found this repository but there is no sample code that demonstrates launching the Gen2 VMs. My goal is to launch DC serise VM(SGX enable). Can I get help? 

```
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "CreateVMSSAgentPoolFailed",
        "message": "VMSSAgentPoolReconciler retry failed: deployment operations failed with error messages: {\n  \"code\": \"BadRequest\",\n  \"message\": \"The selected VM Size 'Standard_DC8_v2' cannot boot Hypervisor Generation '1'. If this was a Create operation please check that the Hypervisor Generation of the Image matches the Hypervisor Generation of the selected VM Size. If this was an Update operation please select a Hypervisor Generation '1' VM Size.\"\n } "
      }
    ]
  }

```

**Comment by palma21** [comment]
Which distro value do you refer? AKS doesn't have a distro value property, could you clarify?
The way to force gen2 to be selected is here: https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#generation-2-virtual-machines-preview 
But this is usually not necessary any more as AKS detects the SKU and chooses the correct image based on the supported generations.
