### ISSUE TITLE
AKS portal does not display same node size as Virtual machine scale set

### ISSUE THREAD

**Issue by yene** [Azure/AKS#2028]
**What happened**:
After changing the agentspool VMSS size to Standard_D4s_v3 I noticed that AKS portal still displays the old node size.

**Comment by neumanndaniel** [comment]
@yene Did you changed the VM size on the VMSS object itself? If yes, that is not supported.

-> https://docs.microsoft.com/en-us/azure/aks/support-policies#user-customization-of-agent-nodes

Supported way would be creating a new nodepool with the correct VM size and remove the old one afterwards.

**Comment by yene** [comment]
Thanks I will test it.
