### ISSUE TITLE
Use a static public IP address for egress traffic with a load balancer for Private AKS Clusters

### ISSUE THREAD

**Issue by dzarate379** [Azure/AKS#2029]
There is documentation that shows how to use a static public IP address for egress traffic with a load balancer in AKS for a public cluster https://docs.microsoft.com/en-us/azure/aks/egress.

Kubernetes clusters are exposed via an internal load balancer hence we only have private IPs and as private, there is no public access to them. 

What we are trying to accomplish is AKS pods accessing private resources within peered networks or on-prem via an express route which does not require public connectivity at any point but IP whitelisting through a firewall between various networks.
Our case scenario

A pod running on AKS attempts an outbound connection to an on-premises service
Traffic is channelled via a perimeter firewall requiring IP whitelisting (whole AKS subnet cannot be whitelisted)
If the firewall allows, a connection is made to the on-premises service over express-route
 
In the above scenario, if we don’t have a fixed private IP for AKS egress, we will not be able to allow this access via perimeter firewall which requires a single private IP (instead of the whole subnet range of AKS cluster). Currently, this traffic is masquerading behind the calling AKS node’s private IP which can change over time and depending on which node the pod is running on. What we want to accomplish, however, is having an internal load balancer that can be used to masquerade all egress traffic from AKS and reading through the documentation, I can see examples of using a public load balancer for this case but no information is provided on if an internal load balancer with a private IP can also be used for the same purpose (I attempted but it didn’t work).

Has this considers before? Are there any previews for such configuration? Or is there a way how to work around this?
Appreciate your time on this question.

**Comment by PixelRobots** [comment]
I have a customer with the same request. Any update would be good.

**Comment by feiskyer** [comment]
Hi, @dzarate379  ELB is required for egress traffic. You couldn't set a public IP address on ILB.

**Comment by TomGeske** [comment]
Wouldn't [outbound type](https://docs.microsoft.com/en-us/azure/aks/egress-outboundtype) w/ user-defined routes address your scenario?

**Comment by PixelRobots** [comment]
For my customer they only want some pods to talk via internal and the rest of the cluster to go over normal egress routes. 

Would UDR work with that?  Or perhaps UDR and separate node pools?

**Comment by TomGeske** [comment]
@PixelRobots: AFAIK it isn't possible today. You could just create a second cluster w/ different egress configuration if you consider a second node pool. 

You may want to check this upstream project: https://github.com/nirmata/kube-static-egress-ip

**Comment by PixelRobots** [comment]
Thanks Tom thought that was the case. I did find that repo. Looks good. Hopefully won't be too long.
