### ISSUE TITLE
AKS Nodepool : Node count falls to 0 while min-count is 1

### ISSUE THREAD

**Issue by guillaumearnould** [Azure/AKS#2030]
Hi,

My autoscale is configured for having minimum 1 node running, but it falls to 0 : 

```
{
    "agentPoolType": "VirtualMachineScaleSets",
    "availabilityZones": null,
    "count": 0,
    "enableAutoScaling": true,
    "enableNodePublicIp": false,
    "id": "{id}",
    "maxCount": 10,
    "maxPods": 110,
    "minCount": 1,
    "mode": "User",
    "name": "{name}",
    "nodeImageVersion": "AKSUbuntu-1604-2020.12.01",
    "nodeLabels": {
      "kubernetes.azure.com/scalesetpriority": "spot"
    },
    "nodeTaints": [
      "kubernetes.azure.com/scalesetpriority=spot:NoSchedule"
    ],
    "orchestratorVersion": "1.16.15",
    "osDiskSizeGb": 128,
    "osDiskType": "Managed",
    "osType": "Linux",
    "powerState": {
      "code": "Running"
    },
    "provisioningState": "Succeeded",
    "proximityPlacementGroupId": null,
    "resourceGroup": "{ressource-group}",
    "scaleSetEvictionPolicy": "Delete",
    "scaleSetPriority": "Spot",
    "spotMaxPrice": -1.0,
    "tags": null,
    "type": "Microsoft.ContainerService/managedClusters/agentPools",
    "upgradeSettings": {
      "maxSurge": null
    },
    "vmSize": "Standard_D16_v3",
    "vnetSubnetId": null
  }
```

Thanks in advance.

**Comment by marwanad** [comment]
@guillaumearnould it seems that you're using Spot instances. Currently, CA operates within the min and max specified counts and respects it those during operations it issues. However, it doesn't interfere to enforce those limits if an external factor causes that the number of nodes to go up or below the maximum count. In your case, it's likely that your Spot node got evicted.

**Comment by guillaumearnould** [comment]
Hi @marwanad, thank you for your answer.

If my Spot node has been evicted, and therefore the node count drops below the min-count, shouldn't the autoscaler automatically create a new one?
Even for Spot instances ?

**Comment by marwanad** [comment]
right, so today it doesn't. This is the same behaviour upstream, the thresholds are respected but it doesn't interfere to enforce them.

Think of it this way as well - if CA interferes to enforce the minimum count when it drops by an external factor - shouldn't it also interfere to enforce the max count? Say you go in and manually add nodes that go over `maxCount`, do you expect CA to delete those nodes to get to the count to respect `maxCount` again? In that case, which nodes will it delete?
That was the reasoning behind this decision to not have CA interfere in those case.

Although, I have evaluated multiple times, changing this behaviour at least for the minimum count case. It's on my backlog but won't get to it until the new year.

**Comment by guillaumearnould** [comment]
Hi @marwanad,

What then do you recommend for the moment?
To monitor and automatically manage it by a script ? (eg: to automatically recreate a node if the node-count drops to 0)

**Comment by marwanad** [comment]
> Hi @marwanad,
> 
> What then do you recommend for the moment?
> To monitor and automatically manage it by a script ? (eg: to automatically recreate a node if the node-count drops to 0)

If there is workload that requires to be scheduled, then it will scale up the node again in the case of eviction since those pods will go into pending state and trigger a scale up. You can have some low priority pods running (similar to how you can configure over-provisioning wit CA)  and have a selector on your Spot nodepool.

**Comment by guillaumearnould** [comment]
Thanks @marwanad
