### ISSUE TITLE
azure-npm daemonset pods request 250m CPU instead of 10m. Is this configurable?

### ISSUE THREAD

**Issue by TheAsteroid** [Azure/AKS#2033]
**What happened**:
The azure-npm daemonsets pods in our (Pulumi-deployed) AKS cluster have the following resource settings:
```
CPU request:    "250m"
Memory request: "300Mi"
CPU limit:      "250m"
Memory limis:   "300Mi"
```

Especially the CPU request is very high, considering we're not in a production cluster. Generally CPU usage of the azure-npm pod is around 1m, so we would like to be able to configure this to a value that is a lot lower, so we have more room to schedule other pods.

![image](https://user-images.githubusercontent.com/41196601/102769259-b1a32280-4382-11eb-8db8-60536c0ec487.png)

**What you expected to happen**:
Based on the default settings [here](https://github.com/Azure/aks-engine/blob/a76a7e840da13d2026cbfcda4a593901988f4612/pkg/api/addons.go#L341) I would expect the following settings:
```
CPU request:    "10m"
Memory request: "20Mi"
CPU limit:      "100m"
Memory limit:   "200Mi"
```

My **main questions** are:
- Is it intended that azure-npm pods request so much CPU?
- Is it possible to configure this in some way? A solution compatible with Pulumi would be great. I've tried finding documentation on how to configure this, but haven't gotten anywhere.

Additionally:
- I see that azure-cni-networkmonitor does not have resource requests and limits configured. Can this be done?
- Can azure-ip-masq-agent resource requests and limits be configured?

**How to reproduce it (as minimally and precisely as possible)**:
- Run  `az aks create --n aks-temp -g aks-temp --network-plugin azure --network-policy azure --kubernetes-version 1.18.8`, assuming resource group `aks-temp` exists.
- Observe the resource requests and limits of azure-npm pods with `kubectl describe pod azure-npm-%postfix% -n kube-system`
- I've also tested this for Kubernetes 1.19.3, the behaviour is the same.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: v1.18.8
- Size of cluster: 4 Standard_DS2_v2 nodes in cluster pool, 2 Standard_E2s_v4 nodes in worker pool
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): HTTP micro-services
- Others: We deploy the AKS cluster using Pulumi.

**Comment by kuznetsov420** [comment]
Similar problem here. We have a huge amount of pods in our cluster, and from time to time we got errors such this:
```
System OOM encountered, victim process: azure-npm, pid: 22434
System OOM encountered, victim process: ipset, pid: 3854
```
Manual editing of `azure-npm`-daemonset's limits didn't help, limits values are resetting to defaults. How to increase limits?

**Comment by TheAsteroid** [comment]
This is not an issue for us anymore, seeing that we moved to Calico. However I'll keep this ticket open for others who are experiencing this issue.

**Comment by miwithro** [comment]
@juan-lee can you look into this?

**Comment by paulgmiller** [comment]
Azure NPM has had some improvements recently to try and address OOMs.
That said we also have a setting on outside that can boost memory limit so
if you're still effected file a support ticket and we'll try and help out.

@miwithro Neha Aggrawal (forget her github handle) is the best person to @
for these though you can throw me on too.
