### ISSUE TITLE
OCI runtime error when adding gpu nodepools

### ISSUE THREAD

**Issue by inohmonton99** [Azure/AKS#2039]
**What happened**:
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "azure-ip-masq-agent-5hcfg": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/8e8c68f2d5b2c862b0f9bdb558f0533faf2e9d591243676a0983b427ecbe3f72/log.json: no such file or directory): fork/exec /usr/bin/nvidia-container-runtime: no such file or directory: unknown

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
az aks nodepool add --resource-group <resgroup> --cluster-name <cluster>^
  --name <ngname> ^
  --node-vm-size standard_nc6s_v3 ^
  --enable-cluster-autoscaler ^
  --node-count 1 ^
  --min-count 0 ^
  --max-count 5

**Anything else we need to know?**:
az version
  "azure-cli": "2.8.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.8.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.10
- Size of cluster (how many worker nodes are in the cluster?) 
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by TomGeske** [comment]
@inohmonton99: Could you try again using latest [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli)?

**Comment by inohmonton99** [comment]
looks good now @TomGeske , thanks for looking into it
