### ISSUE TITLE
NSG of AKS allows 0.0.0.0/0 ssh access

### ISSUE THREAD

**Issue by nmikuni** [Azure/AKS#204]
When create AKS, the default NSG allows ssh from 0.0.0.0/0.
I know it's uses public key authentication, though it's still risky.
Could you please add a  document which warns user about it to "Security and authentication"?
[https://docs.microsoft.com/en-us/azure/aks/]([https://docs.microsoft.com/en-us/azure/aks/])

**Comment by sukrit007** [comment]
Is the ssh access really needed from the web for AKS to function ?  What is the consequence of deleting that rule ?

**Comment by seanknox** [comment]
This is by design. We're working on offering private clusters with no inbound access from the internet.

**Comment by jmcnevin** [comment]
I would really like to see this port closed by default, for a number of reasons:
* Unless you're debugging some sort of node issue, how often will you really need to SSH into a cluster instance?
* Serial console is already available for instances for emergencies.
* It gives my security people heartburn every time someone creates a cluster and forgets to go in and manually blow away this rule.

**Comment by nathanongit** [comment]
+1 to the comment of @jmcnevin.

If it's not possible to have it closed by default, please consider including an explicit statement in the documentation as to the impact of closing it manually.
