### ISSUE TITLE
however the current tenant ****** is not authorized to access linked subscription '109a5e88-712a-48ae-9078-9ca8b3c81345'. while resetting password for admin user

### ISSUE THREAD

**Issue by jinstest1** [Azure/AKS#2040]
$VMSSobject = Get-AzVmss  -ResourceGroupName  "RGPname"
$vmssname = $VMSSobject.Name
Set-AzVmssOSProfile -VirtualMachineScaleSet $VMSSobject -ComputerNamePrefix $VMSSname -AdminUsername $VMSSAdminUsername  -AdminPassword $VMSSAdminPassword
Update-AzVmss -ResourceGroupName  "RGPname" -Name $vmssname -VirtualMachineScaleSet $VMSSobject

is giving the error 

[4:08 PM] Jins Thomas
    
Update-AzVmss : The client has permission to perform action 'Microsoft.Compute/galleries/images/versions/read' on scope '/subscriptions/a****/resourceGroups/****/providers/Microsoft.Compute/virtualMachineScaleSets/*****', however the current tenant '*****' is not
authorized to access linked subscription '109a5e88-712a-48ae-9078-9ca8b3c81345'.
ErrorCode: LinkedAuthorizationFailed
ErrorMessage: The client has permission to perform action 'Microsoft.Compute/galleries/images/versions/read' on scope '/subscriptions/*****/resourceGroups/*****/providers/Microsoft.Compute/virtualMachineScaleSets/*******', however the current tenant '****' is not
authorized to access linked subscription '109a5e88-712a-48ae-9078-9ca8b3c81345'.
ErrorTarget:
StatusCode: 403
ReasonPhrase: Forbidden
OperationID : b7e545c1-316b-4cb2-90cf-f820ff8b65d8
At line:1 char:1
+ Update-AzVmss -ResourceGroupName "MC_S00429DEVEUSRGPGARDN_S00429DEVEU ...
+

-->

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jinstest1** [comment]
please note i am doing this upadte action on AKS VMSS

**Comment by seguler** [comment]
This does not seem to be related in any way to AKS, so I will close the issue. 

Here is a pointer for your issue though: it seems like the identity you used to log on to PowerShell does not seem to have write access to the subscription this VMSS is on. I would check the access controls / role assignments you have on the VMSS to see if you have access. If you still can't figure out the problem, you may follow up with Microsoft Support.
