### ISSUE TITLE
Windows nodes not ready due to PLEG is not healthy

### ISSUE THREAD

**Issue by zhiweiv** [Azure/AKS#2042]
**What happened**:
Windows nodes  become not ready frequently, the error is:
`E0105 01:07:37.904277    4812 kubelet.go:1765] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 7m24.0513035s ago; threshold is 3m0s`

You can find the error in these kubelet logs,
[logs.zip](https://github.com/Azure/AKS/files/5767701/logs.zip)

**How to reproduce it (as minimally and precisely as possible)**:
It is maybe caused by high number of concurrent pod creation/deletion, I didn't find same problem in other AKS clusters which have less pod operation.

Relates issues which also caused by high number of pod creation/deletion:
https://github.com/microsoft/hcsshim/issues/919
https://github.com/Azure/azure-container-networking/issues/762
https://github.com/Azure/azure-container-networking/issues/763

**Environment**:
- Kubernetes version (use `kubectl version`):
1.19.3

- Size of cluster (how many worker nodes are in the cluster?)
3 Linux nodes, 4 Windows nodes.

**Comment by chmill-zz** [comment]
I'd start by checking out the nodes perf metrics at the node(s) hitting this issue. I've seen pleg issues pop up when cpu/mem/disk iops get too hot on the node.

**Comment by zhiweiv** [comment]
Thanks chmill-zz, during the "PLEG is not healthy" period, the metrics api also didn't work. so our monitor didn't show high cpu. However I checked Azure Monitor and found the CPU keep 100% during the period. I will try to find who takes the most CPU.

**Comment by zhiweiv** [comment]
Not sure if https://github.com/Azure/aks-engine/issues/4130 will help on this issue. Will this change merged to AKS?

**Comment by zhiweiv** [comment]
Seems https://github.com/Azure/AgentBaker/pull/511 merged this change, @AbelHu  do you know when will this be available in AKS?

**Comment by AbelHu** [comment]
@zhiweiv We plan to release it  with Windows January security patch. It is expected in AKS RP release 20210118.

**Comment by zhiweiv** [comment]
Seems cni problem can also cause "PLEG is not healthy", in last 24 hours, the cpu is not high, but kublet still report "PLEG is not healthy", we found below issue during the period.
Azure/azure-container-networking#762
Azure/azure-container-networking#763

**Comment by daschott** [comment]
Could be related to #762, however it seems as though the CNI config input is ending unexpectedly, as opposed to being empty:
```
W1229 06:51:20.327836    4276 cni.go:204] Error validating CNI config list {
    "cniVersion":  "0.3.0",
    "name":  "azure",
    "plugins":  [
                    {
                        "type":  "azure-vnet",
                        "mode":  "bridge",
                        "bridge":  "azure0",
                        "capabilities":  {
                                             "portMappings":  true,
                                             "dns":  true
                                         },
                        "ipam":  {
                                     "type":  "azure-vnet-ipam"
                                 },
                        "dns":  {
                                    "Nameservers":  [
                                                        "192.168.200.10",
                                                        "168.63.129.16"
                                                    ],
                                    "Search":  [
                                                   "svc.cluster.local"
                                               ]
                                },
                        "AdditionalArgs":  [
                                               {
                                                   "Name":  "EndpointPolicy",
                                                   "Value":  {
                                                                 "Type":  "OutBoundNAT",
                                                                 "ExceptionList":  [
                                                                                       "10.240.0.0/16",
                                                                                       "10.20.0.0/16"
                                                                                   ]
                                                             }
                                               },
                                               {
                                                   "Name":  "EndpointPolicy",
                                                   "Value":  {
                                                                 "Type":  "ROUTE",
                                                                 "DestinationPrefix":  "192.168.200.0/24",
                                                                 "NeedEncap":  true
                                                             }
                                               },
                                               {
                                                   "Name":  "EndpointPolicy",
                                                   "Value":  {
                                                                 "Type":  "ACL",
                                                                 "Protocols":  "6",
                                                                 "Action":  "Block",
                                                                 "Direction":  "Out",
                                                                 "RemoteAddresses":  "168.63.129.16/32",
                                                                 "RemotePorts":  "80",
                                                                 "Priority":  200,
                                                                 "RuleType":  "Switch"
                                                             }
                                               },
                                               {
                                                   "Name":  "EndpointPolicy",
                                                   "Value":  {
                                                                 "Type":  "ACL",
                                                                 "Action":  "Allow",
                                                                 "Direction":  "In",
                                                                 "Priority":  65500
                                                 : [decoding version info: unexpected end of JSON input]
```
           Is it possible to include Azure CNI config on problematic node as well?

**Comment by zhiweiv** [comment]
Do you mean C:\k\azurecni\netconf\10-azure.conflist? I didn't collect it in previous issues. I will check it next time.

**Comment by zhiweiv** [comment]
Still seeing **PLEG is not healthy** in HIGH cpu usage after update Windows node image to latest, with **Updating kubelet/kube-proxy to run with as high priority processes**.

I guess the only way now is to control pod cpu usage to avoid CPU 100%.

For the azure cni issues, I will trace them in azure cni repo.
