### ISSUE TITLE
Sometimes Pods of any specific node are going to error state with error message "pod sandbox changed it will be killed and re-created"

### ISSUE THREAD

**Issue by SrinuM** [Azure/AKS#2043]
Some of the Pods went into error state with msg "pod sandbox changed it will be killed and re-created" 

Expected: Pods should always be in running state or if any error pods should be killed and recreated 

**How to reproduce it (as minimally and precisely as possible)**: Not sure exactly, we didn't find a specific root cause to reproduce the issue. It is happening suddenly without any reason as per my knoweldege.

**Anything else we need to know?**: ASP.Net MVC application  and we are using windows containers

Why the pods are not getting killed and recreated when in error state?

**Environment**: Production
- Kubernetes version (use `kubectl version`): 1.18.8
- Size of cluster (how many worker nodes are in the cluster?) 3 worker Nodes (All worker nodes are windows nodes)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others: WCF services, Windows servvices, ASP.Net MVC application

Please let us know the root cause of the issue ASAP as it is affecting the production environment.

**Comment by mikepasco** [comment]
@SrinuM we're sorry for the delay in reaching your issue. Can you please confirm if you opened a [Support Request](https://azure.microsoft.com/en-us/support/create-ticket/) and if you are continuing to see this issue?
