### ISSUE TITLE
AKS will roll-back the SSH public key to the key set when aks creating

### ISSUE THREAD

**Issue by yuzsun** [Azure/AKS#2044]
**What happened**: the security concern is that the public key will be roll-back to the key set when aks creating, we may avoid this by not setting ssh key when aks creating, but for existing aks, we can't make changes

**What you expected to happen**: provide an interface to change the SSH key, and make the change still take effect even after AKS update

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by JohnRusk** [comment]
@yuzsun 
> the security concern is that the public key will be roll-back to the key set when aks creating

Do we _know_ that it does roll back?  Or is the user concerned that it _might_ roll back, but they don't know for sure if it really will?

**Comment by yuzsun** [comment]
@JohnRusk yes it does roll back, after updating AKS, the SSH key will be roll-backed as the AKS created.

**Comment by yuzsun** [comment]
@JohnRusk actually after AKS updating, not only the SSH key will be roll back, the VMSS will also be re-imaged, OS Disk will be re-new... looks like all the custom configuration will be lost

**Comment by JohnRusk** [comment]
Wow, that's not right. If user has updated a security credential, it should never be rolled back.

**Comment by tdihp** [comment]
Adding a bit more context here:

User can reset SSH key follow [this article](https://docs.microsoft.com/en-us/azure/aks/ssh#configure-virtual-machine-scale-set-based-aks-clusters-for-ssh-access), however during AKS upgrade, all values of the VMSS will be re-set according to AKS configuration including the SSH pubic key.

SSH key configuration currently is only available at creation time. There are obviously workarounds, such as having a daemonset to watch over the authorized_keys file, however it would be great to be able to update the SSH key setting after creation.

**Comment by JohnRusk** [comment]
I just asked. The team is looking at this issue.

**Comment by yuzsun** [comment]
well done! @JohnRusk 
by the way, may I know more about the "security credential" as mentioned?

**Comment by JohnRusk** [comment]
I just meant the SSH key.

**Comment by shurik-io** [comment]
I've managing a cluster, which got on SSH key on creation time which was correct by then. But I'd like to replace this ssh key. Unfortunately the cluster will be replaced because of this change; I'm using Terraform to manage my AKS clusters. So it would be nice, to be able to change the ssh-key without replacing the whole cluster. A re-deployment of the nodes from a VMSS is totally fine and known by the AKS Upgrade process already. I don't know all details behind the AKS cluster part inside Azure, just from my point of view, this could be a way to go :-)

**Comment by EppO** [comment]
I'm in the same boat. First not having the possibility to add multiple ssh keys at creation is a pain, requires to have a "shared" ssh key with the rest of the team, which is already not a good start. You can change the ssh keys at the VMSS level but it will be overridden by any cluster upgrade so you need to restore them every single time.
There should be a way to change the ssh pub key using the CLI and I wish the terraform provider will then be able to change them without having to re-create the whole cluster.

**Comment by ekarlso** [comment]
Is it so that AKS resets the ssh key you say even using the `az vmss update` method now? I have a nodepool in a semi problematic state that I would like to checke the logs of but AKS seems to be adding back the old ssh key immediately.

**Comment by ekarlso** [comment]
I am running 
```
    az vmss extension set \
      --subscription $AZ_SUBSCRIPTION_ID \
      --resource-group $AKS_NODE_RG \
      --vmss-name $VMSS_NAME \
      --name VMAccessForLinux \
      --publisher Microsoft.OSTCExtensions \
      --version 1.4 \
      --protected-settings "$PAYLOAD"

    az vmss update-instances --instance-ids '*' \
      --subscription $AZ_SUBSCRIPTION_ID \
      --resource-group $AKS_NODE_RG \
      --name $VMSS_NAME
```

**Comment by EppO** [comment]
> I am running
> 
> ```
>     az vmss extension set \
>       --subscription $AZ_SUBSCRIPTION_ID \
>       --resource-group $AKS_NODE_RG \
>       --vmss-name $VMSS_NAME \
>       --name VMAccessForLinux \
>       --publisher Microsoft.OSTCExtensions \
>       --version 1.4 \
>       --protected-settings "$PAYLOAD"
> 
>     az vmss update-instances --instance-ids '*' \
>       --subscription $AZ_SUBSCRIPTION_ID \
>       --resource-group $AKS_NODE_RG \
>       --name $VMSS_NAME
> ```

This will work until you need to upgrade the AKS cluster which will replace the SSH key with the original value used during the AKS cluster creation.

**Comment by CocoWang-wql** [comment]
Update:
We now support updating SSH key on existing AKS cluster and it's public preview.
Doc: 
https://learn.microsoft.com/en-us/azure/aks/node-access#update-ssh-key-on-an-existing-aks-cluster-preview

**Comment by CocoWang-wql** [comment]
https://github.com/Azure/AKS/issues/3190
