### ISSUE TITLE
Enable Azure Monitor without containers logs collection

### ISSUE THREAD

**Issue by BenyErnest** [Azure/AKS#2045]
Hi there:
I would like to enable Azure Monitor for my AKS cluster without collecting container logs because I want to use an alternative solution to Azure Log Analytics, is there a way to do that?
So far I have searched the documentation but I can't find a way to do it, currently my containers are generating a lot of logs and the pricing in Log Analytics are skyrocketing, Azure Monitor provide other good features aside of container logs collection, for that reason I would like to keep it enabled while collect the logs in an alternative solution to Log Analytics, but either I would have to remove the logs from my solutions code or disabled Azure Monitor if I can't find an alternative.
Greets.

**Comment by chmill-zz** [comment]
not familiar with it myself. But i think what you're looking for is possible by adjusting the configmap - https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-agent-config

**Comment by vishiy** [comment]
@BenyErnest - When you say containerlogs are you meaning stdout/stderr logs that gets collected from the monitored containers ? Please clarify.

**Comment by BenyErnest** [comment]
> @BenyErnest - When you say containerlogs are you meaning stdout/stderr logs that gets collected from the monitored containers ? Please clarify.

Yes, usually I check the logs with the live functionality, but don't need to get those logs retained for 30 days in Log Analytics.

**Comment by vishiy** [comment]
You need to disable sttdout & stderr with a config map as described here - https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-agent-config#data-collection-settings

Basically ensure you set the below 2 to false (they default to true) in the config map
[log_collection_settings.stdout] enabled = false
[log_collection_settings.stderr] enabled = false

This will stop collecting stdout/stderr logs, but will continue to collect everything else. 

You can also disable stdout/stderr log collection per namespace (in case you need it ).

**Comment by abelal83** [comment]
You can selectively exclude namespaces too. I wish there was an include namespace option as I only want to collect logs from a few namespaces without constantly updating when new namespaces are created.
