### ISSUE TITLE
Disabling the Uptime SLA?

### ISSUE THREAD

**Issue by roy-work** [Azure/AKS#2046]
After enabling the Uptime SLA feature with `az aks update --uptime-sla`, is there a way to disable/revert that change, and return to the normal SLO cluster type?

**Comment by palma21** [comment]
Sure, something like 

```bash
AKSResourceID=$(az aks show -n <Your AKS Cluster Name> -g <Your AKS Cluster Resource Group> --query id -o tsv)
az resource update --ids $AKSResourceID --set sku.tier="Free"
```
We can add that to the CLI as a disable command to make it easy.
