### ISSUE TITLE
Could not create Application Gateway with AKS custom subnet.

### ISSUE THREAD

**Issue by mytuanZ** [Azure/AKS#2047]
**What happened**: 
I tried to enable the Ingress Controller add-on (preview) for a new AKS cluster using custom subnet with a new Application Gateway instance. This is the tutorial: https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-new 

After running the below command, the k8s cluster was created without Application Gateway. 

`az aks create -n test-k8s -g "infra-k8s-test" --network-plugin azure --enable-managed-identity -a ingress-appgw --appgw-name test-appgw --appgw-subnet-cidr "10.0.12.0/23" --generate-ssh-keys --location southcentralus --service-cidr "10.0.4.0/23" --dns-service-ip  10.0.4.10 --vnet-subnet-id "/subscriptions/efxxxxc9/resourceGroups/infra-test-k8s/providers/Microsoft.Network/virtualNetworks/infra-k8s-test-vnet/subnets/infra-k8s-test-subnet"` 

Logs:
`The behavior of this command has been altered by the following extension: aks-preview `
`Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for virtual network: subscriptions/efxxxxc9/resourceGroups/infra-k8s-test/providers/Microsoft.Network/virtualNetworks/infra-k8s-test-vnet specified in ingressApplicationGateway addon. Are you an Owner on this subscription?`

**What you expected to happen**:
The App Gateway should be created.
**How to reproduce it (as minimally and precisely as possible)**:
`az aks create -n test-k8s -g "infra-k8s-test" --network-plugin azure --enable-managed-identity -a ingress-appgw --appgw-name test-appgw --appgw-subnet-cidr "10.0.12.0/23" --generate-ssh-keys --location southcentralus --service-cidr "10.0.4.0/23" --dns-service-ip  10.0.4.10 --vnet-subnet-id "/subscriptions/efxxxxc9/resourceGroups/infra-test-k8s/providers/Microsoft.Network/virtualNetworks/infra-k8s-test-vnet/subnets/infra-k8s-test-subnet"`

**Anything else we need to know?**:
With default option ( use default VNet 10.0.0.0/8 and default aks-subnet 10.240.0.0/16), Application Gateway can be created.
**Environment**:
- Azure role: Contributor
- Azure Cloud Shell  - bash.

**Comment by mortenlerudjordet** [comment]
This will work if you create the AppGw first.
Also I create a managed user identity first and give it contrib rights on the RG with both vNet and AppGw in them.
This identity is used in az aks create..

```
        az aks create `
            --location $region `
            --subscription "$($Subscription.id)" `
            --name $AksName `
            --resource-group $AKSResourceGroupName `
            --kubernetes-version $KubeVersion `
            --admin-username $AKSadminUserName `
            --enable-managed-identity  `
            --network-plugin azure `
            --node-vm-size $AksNodeVMSize `
            --service-cidr $AksServiceCidr `
            --vm-set-type VirtualMachineScaleSets `
            --enable-cluster-autoscaler `
            --min-count $KubeMinNodeCount `
            --max-count $KubeMaxNodeCount `
            --enable-aad `
            --aad-admin-group-object-ids $AKSadminAADgroupID `
            --tags env=$($env) `
            --ssh-key-value $PubKeyFilePath `
            --enable-addons ingress-appgw `
            --appgw-id $AppGw.id `
            --vnet-subnet-id $AksSubnetID `
            --node-resource-group $AKSNodeResourceGroupName `
            --assign-identity $AksSPid `
            --dns-service-ip $AksDNSip `
            --nodepool-name $AksNodePoolName
```
Note --assign-identity $AksSPid where this is the user managed identity with contrib rights on RG where the stuff AKS needs resides. 
$AppGw.id is the resource id of the pre created AppGw

**Comment by petegrimsdale** [comment]
A similar issue occurs when attempting to use a subnet created within an ARM template.  In this case the add-on is defined within the ManagedCluster resource as:

"ingressApplicationGateway": {
                        "enabled": true,
                        "config": {
                            "applicationGatewayName": "[variables('appGwName')]",
                            "subnetId": "[variables('gwSubnetId')]"
                            
However in all cases this results in a validation error on the template:
"message": "IngressApplicationGateway addon cannot find subnet <subnet reference>

Alternatively if you do not define the subnet resource and use subnetCIDR in the addon properties this works as expected and creates the application gateway and the subnet.

**Comment by miwithro** [comment]
@akshaysngupta, @mscatyao would you be able to assist?

**Comment by akshaysngupta** [comment]
@miwithro will take a look soon.

**Comment by shackit** [comment]
Our company use ARM exclusively. From a customer perspective it would be so good to list the available configuration options for not only this add on but also list all the available add ons and their configuration options. It's just so difficult as a customer to use your features.

**Comment by danimal521** [comment]
@akshaysngupta were you able to look into this one?
