### ISSUE TITLE
How to make pod scheduler prioritize oldest pods?

### ISSUE THREAD

**Issue by wrkgm** [Azure/AKS#2049]
How can I make the pod scheduler prioritize the oldest pods? I.e. whenever there is a free node, the oldest pending pod should get assigned to that node.
**What happened**:
Scheduler picks pods to assign to nodes seemingly at random. Some pods wait for several days, others are assigned within seconds of first appearing.
**What you expected to happen**:
Pick the oldest pod in the queue when there is an open node for assignment.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
There is no priority class set, the cluster is pretty much in it's default state from creation
**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"37c06f456fdb4d25e402b5fbcb72cd6a77a021a9", GitTreeState:"clean", BuildDate:"2020-09-18T21:59:14Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (how many worker nodes are in the cluster?) 20 
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
ML inference

**Comment by miwithro** [comment]
@marwanad can you assist?

**Comment by mikepasco** [comment]
Updated as a feature request. @marwanad can you assist?

**Comment by kaarthis** [comment]
Why are the current best practices not right https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity ? https://learn.microsoft.com/en-us/azure/aks/operator-best-practices-advanced-scheduler

**Comment by justindavies** [comment]
https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/ should be able to cover this use case
