### ISSUE TITLE
Running docker inside Kubernetes with containerd

### ISSUE THREAD

**Issue by Krupakarreddin** [Azure/AKS#2050]
Since K8S v1.11 Runtime was changed from dockerd to containerd. I'm using Jenkins over kubernetes to build docker images using Docker outside of Docker (dood).

When I tried to switch to use the socket file from conatinerd (containerd/containerd.sock was mapped ad /var/run/docker.sock) with the regular docker client a got the following error Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/json: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x00\x04\x00\x00\x00\x00\x00".

Can docker client be used with containerd?

https://stackoverflow.com/questions/53435138/running-docker-inside-kubernetes-with-containerd

**Comment by seanmck** [comment]
See here:

https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#containerd-limitationsdifferences
