### ISSUE TITLE
Confidential compute nodes and Kubernetes upgrades

### ISSUE THREAD

**Issue by mattcollier** [Azure/AKS#2051]
https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#upgrade-an-aks-cluster

We have an application running on a single confidential compute node inside of an AKS cluster.  The application relies on running on the *exact same* Intel CPU forever and always.  The SGX enclave for the CPU has a unique identifier that is used to ensure that this is the case.  We store a payload that is encrypted under a public key that belongs to that *specific* CPU, and therefore that payload can only be decrypted by software operating on that CPU.

The documentation linked above about how a K8S upgrade works indicates that during an upgrade, a new buffer node is provisioned, the old node is cordoned and drained, and the buffer node takes over.  If there is only a single node to begin with, it's unclear to me if the old node is simply deleted after the buffer node comes online, or if the original node is upgraded in places, and then then the new buffer node is deleted.

We have done a number of K8S upgrades so far and it seems that purely by chance our application pods have landed back on the exact same underlying CPU.  Our application could not possibly continue to function if this were not the case.

I am trying to understand exactly how an AKS Kubernetes upgrade works in conjunction with confidential compute nodes.  Is there any special provision made that is not described in the documentation?

Also, unless *by chance* the buffer node lands on the exact same virtualized hardware (exact same Intel CPU), as described above, it is not possible that our application running on the buffer node can service requests because the CPU identifier will not be the same.

How does one go about using SGX in a virtualized context without a tight coupling between applications and specific SGX hardware thus turning Kubernetes Nodes into pets instead of cattle?

**Comment by palma21** [comment]
> If there is only a single node to begin with, it's unclear to me if the old node is simply deleted after the buffer node comes online, or if the original node is upgraded in places, and then then the new buffer node is deleted.

There is always at least one buffer node on any upgrade, the existing node is cordoned/drained to the buffer and then upgraded, and in the end this buffer node(s) is always the deleted  to ensure node balancing in the vmss is the same as before.

> We have done a number of K8S upgrades so far and it seems that purely by chance our application pods have landed back on the exact same underlying CPU. Our application could not possibly continue to function if this were not the case.

To be clear you mean not just node, but CPU here?


> I am trying to understand exactly how an AKS Kubernetes upgrade works in conjunction with confidential compute nodes. Is there any special provision made that is not described in the documentation?

There is nothing special today.

> Also, unless by chance the buffer node lands on the exact same virtualized hardware (exact same Intel CPU), as described above, it is not possible that our application running on the buffer node can service requests because the CPU identifier will not be the same.

> How does one go about using SGX in a virtualized context without a tight coupling between applications and specific SGX hardware thus turning Kubernetes Nodes into pets instead of cattle?

That seems like a sensible question, adding @Pengpeng-Microsoft and @agowdamsft to drive answer/behavior.

**Comment by mattcollier** [comment]
> > We have done a number of K8S upgrades so far and it seems that purely by chance our application pods have landed back on the exact same underlying CPU. Our application could not possibly continue to function if this were not the case.
> 
> To be clear you mean not just node, but CPU here?

Yes, that is correct.  If the CPU identifier and SGX public/private keypair were different after an upgrade, the application running in the SGX would not be able to decrypt the payload referenced in the OP.

**Comment by agowdamsft** [comment]
@mattcollier trying to understand more on your use case. Is your situation more on the sealing key that is bound to the hardware and how you can continue to operate when node affinity is changed? Or are you attaching policies in your application that are binded to the Hardware footprint?.

**Comment by mattcollier** [comment]
@agowdamsft Hello, the sealing key that is bound to the hardware is the issue.

**Comment by agowdamsft** [comment]
@mattcollier at this time to get a hardware affinity Azure Dedicated Host (ADH) is what we recommend but at this time. Although DCSv2 nodes support ADH AKS is not yet integrated.  If you can start an email at acconaks@microsoft.com we can also discuss further on cloud sealing with shared host.
