### ISSUE TITLE
Cluster in failure state after upgrade from 1.18.10 to 1.19.3

### ISSUE THREAD

**Issue by dnauck** [Azure/AKS#2055]
**What happened**:

Upgraded my cluster from 1.18.10 to 1.19.3 via Azure Portal.

After a few minutes the cluster changed into a failed state before a single node was upgraded. All nodes still running 1.18.10 while the cluster version on Azure Portal is 1.19.3. The "diagnose and solve problems" function does not find any issues.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.10
- Size of cluster: 5 nodes

**Comment by chmill-zz** [comment]
I'd start by looking at the Activity log for the cluster to see if the failed operation provided any hints into the failure. Retrying the operation has a chance to work depending on the failure. A support request might be the best route if there isn't anything actionable in the activity log though.
