### ISSUE TITLE
Remove Local Accounts (clusters with no --admin)

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#2063]
https://docs.microsoft.com/en-us/azure/aks/managed-aad#disable-local-accounts-preview

**Comment by ivanthelad** [comment]
Any estimate when this may be available to test in AKS?

**Comment by PixelRobots** [comment]
Hey, it looks like it will be in the az cli aks-preview extension version 0.5.11. 

You will need to add "--disable-local-accounts" to your AKS build script. Looks like it will be for both create and update.

It also seems to allow the option to enable it after also using "--enable-local-accounts"

Hope that helps

**Comment by PixelRobots** [comment]
Just an update. Looking at the pull request this will now be in 0.5.12.  So next release.

**Comment by PixelRobots** [comment]
Hey @ivanthelad you can now test this feature. You can see the steps on my blog https://pixelrobots.co.uk/2021/05/disable-local-user-account-admin-in-azure-kubernetes-service/.

Let us know how your tests go.

**Comment by baptistepattyn** [comment]
@PixelRobots maybe add something to your blogpost so the user knows to upgrade aks-preview extension. Nice blogpost btw :)

**Comment by PixelRobots** [comment]
> @PixelRobots maybe add something to your blogpost so the user knows to upgrade aks-preview extension. Nice blogpost btw :)

Thanks. Updated now.

**Comment by baptistepattyn** [comment]
I am getting a python error telling me it cannot import ManualInterrupt.

![image](https://user-images.githubusercontent.com/48830942/122536404-c6f0c500-d024-11eb-8e0c-0169edbeab1e.png)

All my versions are up to date and the preview is registered

![image](https://user-images.githubusercontent.com/48830942/122536471-da039500-d024-11eb-9d43-040572487146.png)

**Comment by PixelRobots** [comment]
I would remove the preview extension and then add it again. You should get a line below the command saying you are using a preview extension, but it is not showing.

az extension remove -n aks-preview

az extension add -n aks-preview

let me know how you get on.

**Comment by baptistepattyn** [comment]
Thanks I just saw that I was getting errors with other commands too... Was just going to try the remove/add fix.

**Comment by baptistepattyn** [comment]
I believe there is an issue with the 0.5.19 version that is released. Using 0.5.12 I can remove the local accounts but when I use `az extension update -n aks-preview` and the 0.5.19 is installed I get an error...

**Comment by PixelRobots** [comment]
Strange. I have 0.5.19 and it is working. I would look at updating your az cli version or perhaps maybe even a full uninstall and reinstall. I have had that in the past.

**Comment by Krupakarreddin** [comment]
is this feature available in china

**Comment by miwithro** [comment]
@Krupakarreddin not yet.  Adding in @norshtein for awareness.

**Comment by miwithro** [comment]
@Krupakarreddin yes this is available in china.

**Comment by palma21** [comment]
GA
