### ISSUE TITLE
Mount failed with mount failed: exit status 32

### ISSUE THREAD

**Issue by serhii-kuzniechykov** [Azure/AKS#2065]
**What happened**: If you have a mixed node cluster and you deploying some application helm chart with persistent volume without nodeSelector your Linux pod could be scheduled on Windows node.  After you add nodeSelector to existing deployment and reschedule pod to Linux node you get an error with mount:
 

```
Events:
  Type     Reason                  Age   From                     Message
  ----     ------                  ----  ----                     -------
  Normal   Scheduled               112s  default-scheduler        Successfully assigned default/my-release-postgresql-0 to aks-agentpool-43199396-vmss000001
  Normal   SuccessfulAttachVolume  101s  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-d79eb87f-578e-4ee1-aed4-33b13b897af8"
  Warning  FailedMount             95s   kubelet                  MountVolume.MountDevice failed for volume "pvc-d79eb87f-578e-4ee1-aed4-33b13b897af8" : azureDisk - mountDevice:FormatAndMount failed with mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m3309566035 --scope -- mount -t ext4 -o defaults /dev/disk/azure/scsi1/lun1 /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m3309566035
Output: Running scope as unit: run-r202c67e58b3243eba9cd6eebdddb8da3.scope
mount: /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m3309566035: wrong fs type, bad option, bad superblock on /dev/sdd, missing codepage or helper program, or other error.
  Warning  FailedMount  94s  kubelet  MountVolume.MountDevice failed for volume "pvc-d79eb87f-578e-4ee1-aed4-33b13b897af8" : azureDisk - mountDevice:FormatAndMount failed with mount failed: exit status 32
```

**What you expected to happen**: Mount volume in pod succeed 

**Environment**:
- Kubernetes version (use `kubectl version`): Major:"1", Minor:"19", GitVersion:"v1.19.3"
- Size of cluster (how many worker nodes are in the cluster?) - 2 Linux + 2 Windows
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by andyzhangx** [comment]
after pod scheduled to windows node, azure disk would be formatted as NTFS, and then this file system could not be recognized by Linux, I think it's by design, pls remove the disk PVC and try again, thanks.

**Comment by serhii-kuzniechykov** [comment]
Yes, if a disk firstly will be attached to the right node mount will work fine. 
Any plan to automate that in AKS?

**Comment by andyzhangx** [comment]
I think that's expected error since your app helm does not set node label, should be user error IMO.

**Comment by serhii-kuzniechykov** [comment]
Thank you
I think we could close it because it's an expected error.
