### ISSUE TITLE
Autoscaler not working for spot intances

### ISSUE THREAD

**Issue by brunoscota** [Azure/AKS#2066]
**What happened**:
Autoscaler not working in any of my spot clusters where I have this feature enabled. 

**What you expected to happen**:
once Azure deallocate (delete) my spot vm, autoscale should to provision a new vm to keep the pool with the min number of nodes.

**How to reproduce it (as minimally and precisely as possible)**:
Just wait until azure deletes the azure vm.

**Anything else we need to know?**:
All my clusters have the same configuration:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2a313bf59aa0e1c98bbee2aea6ae727d3f6da6fd", GitTreeState:"clean", BuildDate:"2020-09-03T05:20:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
`    {
      name                = "spotpool01"
      count               = 2
      enable_auto_scaling = true
      min_count           = 2
      max_count           = 4
      vm_size             = "Standard_F4s_v2"
      os_type             = "Linux"
      os_disk_size_gb     = 30
      availability_zones  = ["1", "2", "3"]
      priority            = "Spot"
      spot_max_price      = -1
      eviction_policy     = "Delete"
    }`
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Any kind of workload. 
- Others:

My cluster autoscaler status

Name:         cluster-autoscaler-status
Namespace:    kube-system
Labels:       <none>
Annotations:  cluster-autoscaler.kubernetes.io/last-updated: 2021-01-15 21:02:04.772628648 +0000 UTC

Data

status:

Cluster-autoscaler status at 2021-01-15 21:02:04.772628648 +0000 UTC:
Cluster-wide:
  Health:      Healthy (ready=4 unready=0 notStarted=0 longNotStarted=0 registered=4 longUnregistered=0)
               LastProbeTime:      2021-01-15 21:02:04.735976539 +0000 UTC m=+244778.284629733
               LastTransitionTime: 2021-01-15 14:28:03.742464907 +0000 UTC m=+221137.291118001
  ScaleUp:     NoActivity (ready=4 registered=4)
               LastProbeTime:      2021-01-15 21:02:04.735976539 +0000 UTC m=+244778.284629733
               LastTransitionTime: 2021-01-15 14:28:03.742464907 +0000 UTC m=+221137.291118001
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      2021-01-15 21:02:04.735976539 +0000 UTC m=+244778.284629733
               LastTransitionTime: 2021-01-15 14:28:03.742464907 +0000 UTC m=+221137.291118001

NodeGroups:
  Name:        aks-nodepool-36099192-vmss
  Health:      Healthy (ready=1 unready=0 notStarted=0 longNotStarted=0 registered=1 longUnregistered=0 cloudProviderTarget=1 (minSize=1, maxSize=1))
               LastProbeTime:      2021-01-15 21:02:04.735976539 +0000 UTC m=+244778.284629733
               LastTransitionTime: 2021-01-15 14:28:03.742464907 +0000 UTC m=+221137.291118001
  ScaleUp:     NoActivity (ready=1 cloudProviderTarget=1)
               LastProbeTime:      2021-01-15 21:02:04.735976539 +0000 UTC m=+244778.284629733
               LastTransitionTime: 2021-01-15 14:28:03.742464907 +0000 UTC m=+221137.291118001
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      2021-01-15 21:02:04.735976539 +0000 UTC m=+244778.284629733
               LastTransitionTime: 2021-01-15 14:28:03.742464907 +0000 UTC m=+221137.291118001

  Name:        aks-spotnodepool-36099192-vmss
  Health:      Healthy (ready=3 unready=0 notStarted=0 longNotStarted=0 registered=3 longUnregistered=0 cloudProviderTarget=3 (minSize=4, maxSize=6))
               LastProbeTime:      2021-01-15 21:02:04.735976539 +0000 UTC m=+244778.284629733
               LastTransitionTime: 2021-01-15 14:28:03.742464907 +0000 UTC m=+221137.291118001
  ScaleUp:     NoActivity (ready=3 cloudProviderTarget=3)
               LastProbeTime:      2021-01-15 21:02:04.735976539 +0000 UTC m=+244778.284629733
               LastTransitionTime: 2021-01-15 14:28:03.742464907 +0000 UTC m=+221137.291118001
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      2021-01-15 21:02:04.735976539 +0000 UTC m=+244778.284629733
               LastTransitionTime: 2021-01-15 14:28:03.742464907 +0000 UTC m=+221137.291118001

Events:

**Comment by marwanad** [comment]
https://github.com/Azure/AKS/issues/2030#issuecomment-748237360

**Comment by brunoscota** [comment]
Thanks @marwanad , as you mentioned here [#2030 (comment)](https://github.com/Azure/AKS/issues/2030#issuecomment-749229464), should I keep a NodeSelector to keep a minimum workload running on this pool to avoid evict my nodes to zero. And if my workload needs more resources the scale will work again at maximum o my scale max configuration? Is this right ?


and... do you think we will have a new feature to respect the minimum threshold this year?


Thank you.

**Comment by marwanad** [comment]
@brunoscota yup you're correct! I think so - just need to validate a few things with the change. I'll update this thread when the behaviour changes.

**Comment by marwanad** [comment]
@brunoscota fyi - there will be an improvement for that scenario rolling out in two weeks time :) In regards to enforcing the minimum count by autoscaler.

**Comment by brunoscota** [comment]
> @brunoscota fyi - there will be an improvement for that scenario rolling out in two weeks time :) In regards to enforcing the minimum count by autoscaler.

great news!!!! thank you so much!
