### ISSUE TITLE
POD gets evicted due to incorrectly assuming memory pressure

### ISSUE THREAD

**Issue by AurelioBelletti** [Azure/AKS#2067]
**What happened**:
POD gets evicted due to kubelet incorrectly assuming memory pressure. The issue seems to be reported here also: https://github.com/kubernetes/kubernetes/issues/43916

Our POD workload eventually gets evicted because the Linux Kernel buffers and page cache and slabs uses the entire available memory. The catch though is that this memory is reclaimable for applications at any time hence the POD should have never been evicted.

**What you expected to happen**:
PODs are not evicted due to Linux Kernel buffers and page cache since it is reclaimable memory.
An acceptable workaround would be allowing somehow to limit the amount of memory the Kernel can use for buffers/page cache.

**How to reproduce it (as minimally and precisely as possible)**:
Any workload out there has this problem. Simply chart the available memory over an extended period of time (for us it happens in a couple of days) and observe that the available memory keeps decreasing indefinitely up to the point the POD is evicted. 
Another way to monitor is to observe the output of the command "top" in your linux container and confirm that the "buff/cache" value keeps increasing indefinitely whereas the memory for the application running stays relatively constant.

Here is a screenshot of our repro:
![image](https://user-images.githubusercontent.com/75232353/104832239-ae496c80-5844-11eb-923c-64a093943d4d.png)

The red rectangle is the "buff/cache" that keeps increasing indefinitely until the POD is evicted
The green rectangle is the memory used/allocated for the application which remains relatively constant.

**Anything else we need to know?**:
We can repro this fairly easy since each of our PODs is handling high scale traffic (each handles 1.5K RPS)

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
6 nodes of:
beta.kubernetes.io/arch=amd64
beta.kubernetes.io/instance-type=Standard_D96as_v4
beta.kubernetes.io/os=linux

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
High scale service running netcore 3.1. Performance testing now where each POD handles 2K RPS.

- Others:

**Comment by AurelioBelletti** [comment]
It seems to be related with dentry entries. Here is the output of the slabtop:

![image](https://user-images.githubusercontent.com/75232353/105107840-cd771280-5a6d-11eb-8a62-747edd2ec3a1.png)

How can I know what is contributing to the dentry entries? My workload is network I/O heavy and doesn't use much of the filesystem.

**Comment by jveski** [comment]
Closing as a dup of https://github.com/kubernetes/kubernetes/issues/43916 since this isn't AKS-specific.
