### ISSUE TITLE
Ephemeral OS disk: unclear error message

### ISSUE THREAD

**Issue by ams0** [Azure/AKS#2068]
**What happened**:

When trying to create an unsupported combination of VM size and Ephemeral OS disk type I get a `too many 500 error responses`:

```console
~> az aks create -k 1.19.6 -g k8s --network-policy calico --network-plugin kubenet -n eph -s Standard_B4ms --node-osdisk-type Ephemeral --node-osdisk-size 30
ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/12c7e9d6-967e-40c8-8b3e-4659a4ada3ef/resourceGroups/k8s/providers/Microsoft.ContainerService/managedClusters/eph?api-version=2020-11-01 (Caused by ResponseError('too many 500 error responses'))
```

**What you expected to happen**:

To get an error that explains that the combination of VM size and Ephemeral OS disk is not allowed. 

P.S. In fact, according to the documentation of [B-size vm](https://docs.microsoft.com/en-us/azure/virtual-machines/sizes-b-series-burstable), it should be possible to have ephemeral disks on them (they support Premium disks). Can you explain why it's not possible? B-series are great for cost savings.

**Comment by magooster** [comment]
AFAIK: Ephemeral OS disk is only supported on SKUs that support storage caching e.g. [DSv2-series](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series?toc=/azure/virtual-machines/linux/toc.json&bc=/azure/virtual-machines/linux/breadcrumb/toc.json#dsv2-series)

As per your create command, the cluster node OS disk size you specify has to be <= the size of the cache for the VM SKU.

> The sizes for VM cache are available in the Azure documentation in parentheses next to IO throughput ("cache size in GiB").

**Comment by alexeldeib** [comment]
Can you double check the output with `az --debug`? I believe this was due to a bug which led us to return 500 for VMs which supported ephemeral os but had no cache disk. Fix should be rolling out imminently if not already finished.

If it supports ephemeral os it probably uses the temp disk which is a preview CRP feature. We would likely support that in the future but don't today.

**Comment by alexeldeib** [comment]
Thanks for the reminder! I just opened a PR on the AKS side to fix this. It'll probably take a few weeks to roll everywhere.

You'll get an error like this usually for VM sizes with a cache too small for the requested size:
> The virtual machine size %s has a cache size of %d bytes, but the OS disk requires %d bytes. Use a VM size with larger cache or disable ephemeral OS.

When there's no cache disk, it looks like this:
> The virtual machine size %s has a cache size of **0** bytes, but the OS disk requires %d bytes. Use a VM size with larger cache or disable ephemeral OS.

We can make it more clear than that if that's still ambiguous. 

> when in reality you need a vm with a cache disk.

for now. we will eventually enable temp disk for ephemeral OS, same as CRP. depending on their timeline to move it to GA, we can introduce it sooner as a preview feature on the AKS side. We just don't want to say it's stable on our side before it's stable on the underlying infra.

> It would be nice if the docs had some sort of notice stating this.

Have you seen https://aka.ms/aks/ephemeral-os? 4th blurb (after the "Important" bubble): 
> When using ephemeral OS, the OS disk must fit in the VM cache. The sizes for VM cache are available in the Azure documentation in parentheses next to IO throughput ("cache size in GiB").

Let me know if we can make that clearer somehow. I don't think that same comment is in the REST specs, and so it's probably not in the reference docs if you looked at those.

**Comment by AlecDusheck** [comment]
Ah gotcha. Super helpful to know that- I definitely skimmed over that notice. Thanks!

**Comment by alexeldeib** [comment]
This should have been rolled out a while ago, will leave for a day and let this close.

**Comment by AlecDusheck** [comment]
I can confirm the error message is now correct
