### ISSUE TITLE
Overcome Queue Depth/IOPS throttling with RAID/LVM?

### ISSUE THREAD

**Issue by adityasundaramurthy-maersk** [Azure/AKS#2069]
This is a request for information on how to manage Queue Depth/IOPS throttling on AKS clusters. There have been many issues that seem to be caused primarily by IOPS throttling (See #1373, #1320, #1322, #1326). @jnoller has written a detailed explanation of the issue and what triggers it. 

There is also the added problem of network traffic being throttled as Azure treats network IO as disk bound IO due to Linux's device file model (correct me if my understanding of this is wrong!). I have had this issue plaguing clusters with no solution in sight as the workloads are network traffic bound (ETL cron jobs that download data from Azure datalake, process them and put the processed data back in ADL).

However, Azure has already published articles on improving disk IO performance in Linux with software raid (`mdadm`) and instructions on setting it up on Linux VMs ([here](https://docs.microsoft.com/en-us/previous-versions/azure/virtual-machines/linux/optimization), [here](https://docs.microsoft.com/en-us/previous-versions/azure/virtual-machines/linux/configure-raid) and [here](https://docs.microsoft.com/en-us/previous-versions/azure/virtual-machines/linux/configure-lvm)). The RAID option is not mentioned anywhere in the AKS docs. Will RAID on the OS disk with LVM help?

Considering that AKS is now offering Ephemeral OS as a pre-built image that will be managed by Azure, is it not possible to set this up out of the box? Can AKS clusters be created with multiple OS disks and the disk image pre-configured to use striped LVM to improve disk throughput?

**Comment by alexeldeib** [comment]
Azure doesn't support multiple OS disks AFAIK, so RAIDing them isn't an option. RAID'ing data disks is an option, but we're also working towards OS/workload isolation e.g. via https://github.com/Azure/AKS/issues/1753. As you mentioned ephemeral disks also substantially help by raising the iops/throughput cap to the VM limit. 

If you want to provision data disks for a workload after provisioning, you're free to RAID them any way you like.
