### ISSUE TITLE
Keep tags from the resource group that was used to launch the cluster.

### ISSUE THREAD

**Issue by levidehaan** [Azure/AKS#207]
Right now when you launch an AKS cluster into a resource group (where you have billing tags etc..) it creates a new resource group that doesn't inherit the tags from the group that spawned it.

is that going to be fixed in future versions?

**Comment by amanohar** [comment]
@levidehaan, yes we have a work item tracking this change.

**Comment by BrendanThompson** [comment]
Is there any traction on this? In our organisation we have tagging requirements, and in **AKS** current state we cannot deploy it as we are not able to add tags to the resultant resources as part of the ARM deployment.

**Comment by 300481** [comment]
As we have the same problem, i wrote a short bash-script doing that for me.
We use terraform for the deployment. I use two terraform outputs to get the
resource_group names.
https://gist.github.com/300481/e45dc40de46f7548cf3e418ea6d4b407#file-tag-cluster-resources-sh

**Comment by theheatDK** [comment]
A Powershell workaround - https://github.com/Azure/azure-cli/issues/7573#issuecomment-471930995

**Comment by palma21** [comment]
You can now pass tags as you create aks and they will be persisted on the MC resource group.
This is possible via Portal, CLI or ARM

Additionally you can also use Azure Policy to enforce your tags.
