### ISSUE TITLE
AKS Deployment fails with outbound type UDR with error invalid Load balancer Profile

### ISSUE THREAD

**Issue by Raviteza7796** [Azure/AKS#2072]
aks.json

{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "aksClusterName": {
            "type": "string",
            "defaultValue": "aksadcluster",
            "metadata": {
                "description": "The name of the Managed Cluster resource."
            }
        },
        "location": {
            "type": "string",
            "defaultValue": "westus",
            "metadata": {
                "description": "The Azure location of the AKS resource."
            }
        },
        "aksDnsPrefix": {
            "type": "string",
            "defaultValue": "aksadcluster",
            "metadata": {
                "description": "Optional DNS prefix to use with hosted Kubernetes API server FQDN."
            }
        },
        "osDiskSizeGB": {
            "defaultValue": 500,
            "minValue": 0,
            "maxValue": 1023,
            "type": "int",
            "metadata": {
                "description": "Disk size (in GB) to provision for each of the agent pool nodes. This value ranges from 0 to 1023. Specifying 0 will apply the default disk size for that agentVMSize."
            }
        },
        "agentCount": {
            "defaultValue": 3,
            "minValue": 1,
            "maxValue": 50,
            "type": "int",
            "metadata": {
                "description": "The number of agent nodes for the cluster. Production workloads have a recommended minimum of 3."
            }
        },
        "agentVMSize": {
            "defaultValue": "Standard_D3_v2",
            "type": "string",
            "metadata": {
                "description": "The size of the Virtual Machine."
            }
        },
        "existingServicePrincipalClientId": {
            "type": "securestring",
            "metadata": {
                "description": "Client ID (used by cloudprovider)"
            }
        },
        "existingServicePrincipalClientSecret": {
            "type": "securestring",
            "metadata": {
                "description": "The Service Principal Client Secret."
            }
        },
        "osType": {
            "defaultValue": "Linux",
            "allowedValues": [
                "Linux"
            ],
            "type": "string",
            "metadata": {
                "description": "The type of operating system."
            }
        },
        "kubernetesVersion": {
            "defaultValue": "1.18.10",
            "type": "string",
            "metadata": {
                "description": "The version of Kubernetes."
            }
        },
        "enableHttpApplicationRouting": {
            "defaultValue": false,
            "type": "bool",
            "metadata": {
                "description": "boolean flag to turn on and off of http application routing"
            }
        },
        "enableAzurePolicy": {
            "type": "bool",
            "defaultValue": false,
            "metadata": {
                "description": "Boolean flag to turn on and off Azure Policy addon."
            }
        },
        "networkPlugin": {
            "allowedValues": [
                "azure",
                "kubenet"
            ],
            "defaultValue": "azure",
            "type": "string",
            "metadata": {
                "description": "Network plugin used for building Kubernetes network."
            }
        },
        "networkPolicy": {
            "defaultValue": "calico",
            "type": "string",
            "metadata": {
                "description": "Network policy used for defining access policies for communication between pods."
            }
        },
        "maxPods": {
            "defaultValue": 30,
            "type": "int",
            "metadata": {
                "description": "Maximum number of pods that can run on a node."
            }
        },
        "enableRBAC": {
            "defaultValue": true,
            "type": "bool",
            "metadata": {
                "description": "boolean flag to turn on and off of RBAC"
            }
        },
        "vnetName": {
            "type": "string",
            "metadata": {
                "description": "Name of an existing VNET that will contain this AKS deployment."
            }
        },
        "vnetResourceGroup": {
            "type": "string",
            "metadata": {
                "description": "Name of the existing VNET resource group"
            }
        },
        "subnetName": {
            "type": "string",
            "metadata": {
                "description": "Subnet name that will contain the App Service Environment"
            }
        },
        "serviceCidr": {
            "type": "string",
            "defaultValue": "10.0.0.0/16",
            "metadata": {
                "description": "A CIDR notation IP range from which to assign service cluster IPs."
            }
        },
        "dnsServerIp": {
            "type": "string",
            "defaultValue": "10.0.0.10",
            "metadata": {
                "description": "Containers DNS server IP address."
            }
        },
        "dockerBridgeCidr": {
            "type": "string",
            "defaultValue": "172.17.0.1/16",
            "metadata": {
                "description": "A CIDR notation IP for Docker bridge."
            }
        },
        "AAD_ClientAppID": {
            "type": "securestring",
            "metadata": {
                "description": "The Application ID for the Client App Service Principal"
            }
        },
        "AAD_ServerAppID": {
            "type": "securestring",
            "metadata": {
                "description": "The Application ID for the Server App Service Principal"
            }
        },
        "AAD_TenantID": {
            "type": "string",
            "metadata": {
                "description": "The Azure AD Tenant where the cluster will reside"
            }
        },
        "AAD_ServerAppSecret": {
            "type": "securestring",
            "metadata": {
                "description": "The Service Principal Secret for the Server App Service Principal"
            }
        },
        "monitoringResourceGroup": {
            "type": "string",
            "metadata": {
                "description": "The resource group where monitoring resources are contained"
            }
        },
        "lawsName": {
            "type": "string",
            "metadata": {
                "description": "The log analytics workspace in which to save AKS logs for the cluster"
            }
        },
        "nodeResourceGroup": {
            "type": "string",
            "metadata": {
                "description": "The name of the resource group to which the kubernetes nodes will be deployed"
            }
        }
    },
    "variables": {
        "vnet_subnet_id": "[resourceId(parameters('vnetResourceGroup'),'Microsoft.Network/virtualNetworks/subnets',parameters('vnetName'),parameters('subnetName'))]",
        "laws_resource_id": "[resourceId(parameters('monitoringResourceGroup'),'Microsoft.OperationalInsights/workspaces',parameters('lawsName'))]"
    },
    "resources": [
        {
            "type": "Microsoft.ContainerService/managedClusters",
            "apiVersion": "2020-02-01",
            "name": "[parameters('aksClusterName')]",
            "location": "[parameters('location')]",
            "properties": {
                "kubernetesVersion": "[parameters('kubernetesVersion')]",
                "dnsPrefix": "[parameters('aksDnsPrefix')]",
                "agentPoolProfiles": [
                    {
                        "name": "agentpool",
                        "osDiskSizeGB": "[parameters('osDiskSizeGB')]",
                        "count": "[parameters('agentCount')]",
                        "vmSize": "[parameters('agentVMSize')]",
                        "osType": "[parameters('osType')]",
                        "storageProfile": "ManagedDisks",
                        "vnetSubnetID": "[variables('vnet_subnet_id')]",
                        "type": "VirtualMachineScaleSets",
                        "mode": "System",
                        "maxPods": "[parameters('maxPods')]"
                    }
                ],
                "servicePrincipalProfile": {
                    "clientId": "[parameters('existingServicePrincipalClientId')]",
                    "Secret": "[parameters('existingServicePrincipalClientSecret')]"
                },
                "addonProfiles": {
                    "httpApplicationRouting": {
                        "enabled": "[parameters('enableHttpApplicationRouting')]"
                    },
                    "omsagent": {
                        "enabled": true,
                        "config": {
                            "logAnalyticsWorkspaceResourceID": "[variables('laws_resource_id')]"
                        }
                    },
                    "azurePolicy": {
                        "enabled": "[parameters('enableAzurePolicy')]"
                    }
                },
                "nodeResourceGroup": "[parameters('nodeResourceGroup')]",
                "enableRBAC": "[parameters('enableRBAC')]",
                "networkProfile": {
                    "networkPlugin": "[parameters('networkPlugin')]",
                    "networkPolicy": "[parameters('networkPolicy')]",
                    "outboundType": "userDefinedRouting",
                    "serviceCidr": "[parameters('serviceCidr')]",
                    "dnsServiceIP": "[parameters('dnsServerIp')]",
                    "dockerBridgeCidr": "[parameters('dockerBridgeCidr')]"
                },
                "aadProfile": {
                    "clientAppID": "[parameters('AAD_ClientAppID')]",
                    "serverAppID": "[parameters('AAD_ServerAppID')]",
                    "tenantID": "[parameters('AAD_TenantID')]",
                    "serverAppSecret": "[parameters('AAD_ServerAppSecret')]"
                }
            }
        }
    ],
    "outputs": {
        "controlPlaneFQDN": {
            "type": "string",
            "value": "[reference(concat('Microsoft.ContainerService/managedClusters/', parameters('aksClusterName'))).fqdn]"
        }
    }
}

error:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"UnexpectedLoadBalancerProfileForNonStandardLoadBalancerCluster","message":"Load balancer profile should not be specified for cluster without standard load balancer"}]}

**Comment by rmorilha** [comment]
Also facing the same issue with Terraform deployment

**Comment by Raviteza7796** [comment]
Try passing the load balancer sku variable with standard as the assigned value in network profile
loadbalancersku: standard

**Comment by rmorilha** [comment]
@Raviteza7796 I've done it, no luck on deploying the cluster without a public loadbalancer.

**Comment by rmorilha** [comment]
When I specify loadbalancer sku as basic, I get this error from terraform.
However, There is no loadbalancer profile defined. And when I specify loadbalancer sku as standard, it deploys the cluster with Public IP attached to it.

Error: creating Managed Kubernetes Cluster "aks-d-sim" (Resource Group "rg-d-vps-sim-clust"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="UnexpectedLoadBalancerProfileForNonStandardLoadBalancerCluster" Message="Load balancer profile should not be specified for cluster without standard load balancer" Target="networkProfile.loadBalancerProfile"

**Comment by mikepasco** [comment]
@rmorilha we're sorry for the delay in reaching your issue. Can you please confirm if you are still having this issue? If so, can you please try with the latest API version and confirm if the behavior is the same?
