### ISSUE TITLE
[Feature] Support DSR on Windows AKS when Calico is enabled

### ISSUE THREAD

**Issue by keikhara** [Azure/AKS#2073]
DSR (Direct Server Return) will be enabled on AKS Windows as a default. 
https://techcommunity.microsoft.com/t5/networking-blog/direct-server-return-dsr-in-a-nutshell/ba-p/693710
This is required for Calico Network Policy. 
This is only for new cluster create and not with upgrade of k8s version.

**Comment by keikhara** [comment]
new features for calico.

**Comment by darrinthomascecil** [comment]
For what versions of AKS are WinDSR enabled?

**Comment by AbelHu** [comment]
Close it since WinDSR is enabled in AKS Windows by default.
