### ISSUE TITLE
First request is not working in deployed AKS cluster

### ISSUE THREAD

**Issue by connectgirish3** [Azure/AKS#2074]
**What happened**: context : we have around 10 micro services deployed in our aks cluster and one front ene react app. Post any new deployment aks cluster when we try to access the application we are not getting data for the first time in react app and we would need to go back and forth post that we would be able retrieve data from micro services. I don't see any error at container level. I have even introduced readiness and liveliness probe all looks fine. Anybody could help me understand why is that first request from react web app not able to fetch data from aks? 

**What you expected to happen**:first or initial request from react web app should work 

**How to reproduce it (as minimally and precisely as possible)**: I have used default docker file that got created using visual Studio. 

**Anything else we need to know?**:

**Environment**: aks
- Kubernetes version (use `kubectl version`): 1.17.3
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)Dot net core micro services
- Others:

**Comment by miwithro** [comment]
@connectgirish3 How are you exposing the applications within the cluster? What is the network topology that is being leveraged?

**Comment by mikepasco** [comment]
> @connectgirish3 How are you exposing the applications within the cluster? What is the network topology that is being leveraged?

@connectgirish3 please see the question above requesting more feedback and let us know if you are still facing this issue.
