### ISSUE TITLE
Migrate Standard PVC to Premium PVC pod not starting up after restarting it. 

### ISSUE THREAD

**Issue by dzarate379** [Azure/AKS#2075]
The scenario description of the issue is.

- I am working with Azure FileShare PVCs and not Disk PVCs.

- I already have existing PVCs that have been created and are in Use only they are Standard Fileshare PVCs (Standard Storage Account)

- I am migrating these PVCs to premium fileshare ones

- I have the azurefile-premium Storage class and I am able to create the new PVCs successfully.

- However when I restart the pod to mount the new PVCs I get an error and the pod is left in a failed state because it is unable to mount the pvc with an error that says (Host is down).
kubelet, aks-default-00000000-vmss00002d  Error: failed to start container 'mounter': Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting '/var/lib/kubelet/pods/225e12ea-0ad7-4933-8fa7-8dea95fd0016/volumes/kubernetes.io~azure-file/pvc-9d8c8490-c09a-431a-b423-bd7413bdd5cb' to rootfs at '/mnt/sms-syslog-b' caused: lstat /var/lib/docker/overlay2/ec2018b06e1eda9fb3f77bca743cbf4239f9b682aa4b1a764b240cea65f4ee7e/merged/mnt/sms-syslog-b: host is down: unknown

- This error is only cleared when I either restart the node that houses the pod.

- A workaround I have found is to create a new node and cordon the existing node so when the pod is restarted it moves to the new node. with this, I do not get the error at all.

I would prefer not to perform the workaround but instead having the pod restarted with the new Premiun PVC
By executing the above you will be able to reproduce the issue.

Could documentation be created in order to list the steps required to perform such a process?

**Comment by andyzhangx** [comment]
did you change some k8s config in your original PV or pod? in your case, what's the relationship to standard PVC, this issue only happens on Premium PVC?
