### ISSUE TITLE
[Question]Pod security policy deprecation

### ISSUE THREAD

**Issue by mo-saeed** [Azure/AKS#2077]
Hi Guys,

in [here](https://docs.microsoft.com/en-us/azure/aks/use-pod-security-policies) it's written that pod security policy will not be longer available after May 31st but based on Kubernetes up-stream https://github.com/kubernetes/enhancements/issues/5#issuecomment-761709350 PSP will be removed in kubernetes 1.25 so the question is, will PSP in AKS still usable after May 31st and till 1.25 release?

Thanks

**Comment by az-policy-kube** [comment]
@az-policy-kube would you be able to assist?

**Comment by miwithro** [comment]
@mo-saeed we will be pushing the deprecation date to 06.30.2021. So you can continue to use PSP until that date.  After that you will need to use Azure Policy.  I am in the process of updating the document to reflect that date as well.

**Comment by mo-saeed** [comment]
@miwithro Thank you for your reply but that doesn't answer my question, even if AKS deprecates PSP will we still be able to use it in our cluster till it's deprecated in the upstream?

**Comment by miwithro** [comment]
No you will not.

**Comment by pakoAku** [comment]
@miwithro can you clarify on this please:

How do I need to understand this:
06.30.2021 - all running AKS cluster, from all customer with any Kubernetes version will stop support PSP
or
06.30.2021 - all AKS Cluster which will be upgraded to Kubernetes 1.2x or get created after the 06.30.2021 will stop support PSP


I was in a discussion with the Azure Support and I understood it will stop working only after upgrade to specific Kubernetes version or newly created cluster. 
This would give everybody time and control on when to upgrade.

**Comment by miwithro** [comment]
Hello,
  To be more clear.

  After pod security policy (preview) is deprecated, you must disable the feature on any existing clusters using the deprecated feature to perform future cluster upgrades and stay within Azure support.  So in short, they can continue to use as long as they don’t upgrade.

**Comment by pakoAku** [comment]
Thank you for the clarification.

**Comment by miwithro** [comment]
@mo-saeed @pakoAku 

We have updated our guidance around Pod Security Policies:

 Pod security policy (preview), will begin deprecation with Kubernetes version 1.21, with its removal in version 1.25. As Kubernetes Upstream approaches that milestone, the Kubernetes community will be working to document viable alternatives. The previous deprecation announcement was made at the time as there was not a viable option for customers. Now that the Kubernetes community is working on an alternative, there no longer is a pressing need to deprecate ahead of Kubernetes.

https://docs.microsoft.com/en-us/azure/aks/use-pod-security-policies

**Comment by pierluigilenoci** [comment]
FYI https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/ and https://github.com/kubernetes/enhancements/issues/2579

**Comment by pierluigilenoci** [comment]
FYI https://github.com/kubernetes/enhancements/pull/2582
