### ISSUE TITLE
Breaking change in ContainerInsights Log Analytics solution between 1.18 and 1.19

### ISSUE THREAD

**Issue by aristosvo** [Azure/AKS#2078]
**What happened**:
Our Log Analytics Workspace  scheduled query alerts are (mis-)firing because breaking changes in the way image names are saved using the Container Insights solution

**What you expected to happen**:
Our query looked for nginx controller images by specifiing `image == "ingress-nginx/controller@sha256`, but the published image is now `sha256`.
Similar behaviour is also seen for Velero, `image == "velero"` should now be `"velero/velero"`.

Especially the first change is not what you expect.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a cluster with ContainerInsights Log Analytics solution enabled, both version 1.18.x and 1.19.x
- Install ingress-nginx on it
- Query in the connected Log Analytics Workspace:
```
ContainerInventory 
| project Image
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by vishiy** [comment]
@aristosvo can you check the image version for the omsagent container between the two changes ? This looks more like a monitoring addon bug.

**Comment by aristosvo** [comment]
Bugged version: `mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod01112021`
I'll check for a working version..

**Comment by vishiy** [comment]
+ @ganga1980

**Comment by ganga1980** [comment]
Hi, @aristosvo,  can you please share the yaml snippet, how you are specifying the image under spec? and also if possible, can you please run below query on your log analytics and share the results ..

ContainerInventory 
| where TimeGenerated > ago(15d) # try wider time window if you can repro old image 
| summarize count() by bin(TimeGenerated, 1d), Image, ImageTag, Repository

**Comment by aristosvo** [comment]
Hi @ganga1980:

- A cleaned up version of the deployment, part of Helm chart v3.21.0 for `ingress-nginx` v0.43.0
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: ingress
    meta.helm.sh/release-namespace: ingress
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 0.43.0
    helm.sh/chart: ingress-nginx-3.21.0
spec:
  template:
    spec:
      containers:
        image: k8s.gcr.io/ingress-nginx/controller:v0.43.0@sha256:9bba603b99bf25f6d117cf1235b6598c16033ad027b143c90fa5b3cc583c5713
```

I've limited your query a bit:

```
ContainerInventory
| where TimeGenerated > ago(15d) 
| where Repository == "k8s.gcr.io" or Repository == "" or (Repository == "mcr.microsoft.com" and Image == "azuremonitor/containerinsights/ciprod")
| where Image != "defaultbackend-amd64"
| summarize count() by bin(TimeGenerated, 1d), Image, ImageTag, Repository
```
|TimeGenerated [UTC] | Image | ImageTag | Repository | "count_"  |  
|--|--|--|--|--|
| 2/20/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 4505
| 2/20/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 2572
| 2/12/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 10084
| 2/12/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 5760
| 2/6/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 10086
| 2/6/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 5760
| 2/5/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 1056
| 2/5/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 5523
| 2/19/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 5760
| 2/19/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 10082
| 2/15/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 10083
| 2/15/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 5760
| 2/16/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 10084
| 2/16/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 5764
| 2/11/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 10087
| 2/11/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 5772
| 2/14/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 10080
| 2/14/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 5760
| 2/8/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 10086
| 2/8/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 5772
| 2/7/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 10081
| 2/7/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 5760
| 2/13/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 10085
| 2/13/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 5768
| 2/17/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 10082
| 2/17/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 5764
| 2/18/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 10081
| 2/18/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 5760
| 2/5/2021, 12:00:00.000 AM | sha256 | 2807ba84fc0dab039be33de7e9fbe1d9457ef5a7f3616e4b2c084e42a9eca45b | | 1085
| 2/5/2021, 12:00:00.000 AM | ingress-nginx/controller@sha256 | fc4979d8b8443a831c9789b5155cded454cb7de737a8b727bc2ba0106d2eae8b | k8s.gcr.io | 1024
| 2/10/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 10084
| 2/10/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 5764
| 2/9/2021, 12:00:00.000 AM | azuremonitor/containerinsights/ciprod | ciprod01112021 | mcr.microsoft.com | 10081
| 2/9/2021, 12:00:00.000 AM | sha256 | 38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d | | 5760
| 2/5/2021, 12:00:00.000 AM | ingress-nginx/controller" | v0.35.0@sha256:fc4979d8b8443a831c9789b5155cded454cb7de737a8b727bc2ba0106d2eae8b" | k8s.gcr.io | 1
| 2/5/2021, 12:00:00.000 AM | ingress-nginx/controller" | v0.43.0@sha256:9bba603b99bf25f6d117cf1235b6598c16033ad027b143c90fa5b3cc583c5713" | k8s.gcr.io | 2

**Comment by ganga1980** [comment]
Hi, @aristosvo , thanks for the details. When we moved from Docker API to Kubelet API for the container inventory. We have used "image" field under containerStatuses to extract Image, ImageTag and Repo field values in ContainerInventory. As you can see this, the image value is just sha256 value - sha256:38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d.  We have fixed to use **Image from the spec**  i.e. `k8s.gcr.io/ingress-nginx/controller:v0.43.0@sha256:9bba603b99bf25f6d117cf1235b6598c16033ad027b143c90fa5b3cc583c5713` to extract the Image, ImageTag and Repo field values, and this should address your issue. We are working on getting the fix rolled out as part of our Feb agent.
Once the Feb agent rolled out, you should see these 
Repo - k8s.gcr.io
Image - ingress-nginx/controller
ImageTag - v0.43.0
ImageId - sha256:38dca1cbd23197f591e58fc6c949110b53f7a003e15f6d4974d86e7f7a00815d
 
let me know if this address issue. Here is the PR in case if you want to look at it - https://github.com/microsoft/Docker-Provider/pull/505

**Comment by aristosvo** [comment]
@vishiy @ganga1980 Thanks, especially for the detailed and informative follow-ups! Amazing work, I can't imagine how much the changes in K8s (containerD, etc) must have affected you.

Good job 👍

**Comment by ganga1980** [comment]
Hi, @aristosvo , New agent ciprod02232021 which has fix should have been rolled to all of your clusters. please check and this issue should have been resolved. Please confirm.

**Comment by aristosvo** [comment]
Hi @ganga1980! The issue is resolved!

Thanks a lot!

**Comment by aristosvo** [comment]
Hi @ganga1980 The issue is indeed resolved! 

Thanks a lot.
