### ISSUE TITLE
AKS node not visible in Azure Virtual machines.

### ISSUE THREAD

**Issue by vishnugs** [Azure/AKS#2079]
**What happened**: AKS node not visible in Azure Virtual machines.

**What you expected to happen**:AKS node not visible in Azure Virtual machines.

**How to reproduce it (as minimally and precisely as possible)**: C
Create AKS cluster
add scale sets/agent pool

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.3
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

Is there a way to list AKS node in Azure Virtual machines ?

**Comment by brobichaud** [comment]
VM's associated with a VM Scale Set are designed to not show up as VM's in the traditional sense. You can see all VM's associated with a VMSS by looking at the VMSS in the Azure Portal and choosing the Instances tab.

**Comment by andyzhangx** [comment]
answer provided.
