### ISSUE TITLE
Pods with mounted Azure File Share randomly fails to move directory

### ISSUE THREAD

**Issue by jcarnus** [Azure/AKS#2080]
**What happened**:
We have a pods running a Java application that performs some data management on an Azure File Share
We do the following folder moves:
A become B
C become A

Most of the times, this is working, but something the second move (C to A) fails. From a windows point of view, the MoveFileEx Win32 API returns the code ERROR_ACCESS_DENIED. If we retry 1 seconds later, the problems is solved.

**What you expected to happen**:
The second rename folder should work 100% of the times

**How to reproduce it (as minimally and precisely as possible)**:
Have a pod under thoses conditions and run it.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.8
- Size of cluster (how many worker nodes are in the cluster?) 2 machines
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Java applications
- Others:

**Comment by andyzhangx** [comment]
seems it's a azure file side issue
cc @gunjanj @RenaShahMSFT

**Comment by jcarnus** [comment]
Ok, Where can I report it so ?

**Comment by andyzhangx** [comment]
file a support ticket to azure storage team, provide you account and file share name

**Comment by miwithro** [comment]
@gunjanj @RenaShahMSFT any updates?

**Comment by danimal521** [comment]
@jcarnus were you able to file a support ticket? Were you able to resolve this issue?
