### ISSUE TITLE
Restrict inbound traffic to nodes with NSG on subnet

### ISSUE THREAD

**Issue by MCKLMT** [Azure/AKS#2081]
Hi,

My customer would like to restrict the traffic to nodes with a NSG assigned to the subnet hosting the nodes.
However, I'm not able to find in the documentation the rules to add to allow the communication between the master and the nodes. 
Is it explained somewhere?

Thanks

**Comment by jorge-aguas** [comment]
Hi @MCKLMT ,

You can find the necessary connectivity requirements for AKS (general requirements and some specific use cases) [here](https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic)

Please note that the Azure NSG operates at layers 3 and 4 - you will be limited to working with ports as some of the IPs associated with the require FQDNs are subject to change. [service tags](https://docs.microsoft.com/en-us/azure/virtual-network/service-tags-overview) might help in some situations.

**Comment by MCKLMT** [comment]
Hi @joaguas,

My customer wants to assign a NSG to the subnet hosting the nodes. This is a supported scenario. We are not able to find any documentation about this except the egress documentation page which is on egress in particular.

Is there somewhere a list of all ports needed on a new cluster to still get it running and be connected to master? 

Thanks

**Comment by joaguas** [comment]
@MCKLMT , the link above on egress traffic describes what's required between the worker nodes and control plane components, check the "Use" column for individual descriptions.

[Required outbound network rules and FQDNs for AKS clusters](https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic#required-outbound-network-rules-and-fqdns-for-aks-clusters)

As you can see some of those are achievable through service tags, others are FQDNs whose A record is subject to change meaning you'd need to allow ports only (1194/UDP, 443/TCP, etc.)

**Comment by MCKLMT** [comment]
@joaguas Is there a way to improve the documentation by separating the ingress from the egress? It can be useful when the customer wants to accomplish to same goal.

**Comment by miwithro** [comment]
The document that @joaguas linked walks through the egress options for the node to control plane communications.  What you are looking for is a document which walks through the ingress options for AKS worker nodes.   That is not something we have documented as it depends on the needs of the applications deployed within the cluster.  Simply put, if you deploy pods on the AKS worker nodes that need port 443 or 1555 then you would apply an NSG rule to only allow those ports from an Ingress perspective.  Make sense?

**Comment by MCKLMT** [comment]
Thanks this is more clear now. Thanks again @joaguas for the side discussion.
