### ISSUE TITLE
Adjusting the update interval on http_application_routing gets over-written

### ISSUE THREAD

**Issue by IBMRob** [Azure/AKS#2082]
**What happened**:

After enabling http_application_routing I wanted to adjust the polling that the DNS updates use, at the moment its a very slow 3 minutes, we would like to reduce this down to 30 seconds so we don't need to wait as long. 

Updates to the addon-http-application-routing-external-dns deployment get overwritten, preventing us from doing this. 

**What you expected to happen**:

After updating the `interval` argument on the deployment I was expecting the DNS updates to occur quicker. After making the update, a new pod is created but its quickly replaced because the deployment is reset back to the default 3 minute polling. 

**How to reproduce it (as minimally and precisely as possible)**:

Enable http_application_routing as per https://docs.microsoft.com/en-us/azure/aks/http-application-routing#deploy-http-routing-cli
Edit the `addon-http-application-routing-external-dns` deployment and wait a few minutes. The update will be removed. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- ```
- RobsMacbookPro:e2e convery$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T16:06:08Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?): 3 workers each with 4cpu/16GB
- General description of workloads in the cluster: Very light load
- Others:

**Comment by miwithro** [comment]
@paulgmiller

**Comment by robbiezhang** [comment]
AKS doesn't support customization of the parameters for the http application routing components, and http application routing addon  is not recommended for production purpose.
![image](https://user-images.githubusercontent.com/9003737/128233488-40b8a675-2b51-4196-ad27-6c110e54f359.png)

you can deploy your own ingress-controller and external-dns if you need customization.
