### ISSUE TITLE
Allow `http_proxy`, `https_proxy`, and `no_proxy` in CustomNodeConfiguration feature

### ISSUE THREAD

**Issue by faheem556** [Azure/AKS#2083]
The current `CustomNodeConfiguration` configuration feature allows us to change some Linux configuration of the AKS VMSS nodes, however, it doesn't let us change `http_proxy` settings. We have a customer who is using `DaemonSet` with a custom `startup-script` to configure the nodes. Would it be possible to add proxy settings under custom node configuration as well?

https://docs.microsoft.com/en-us/azure/aks/custom-node-configuration

**Comment by miwithro** [comment]
We already have a feature planned for this, which is currently in development.

https://github.com/Azure/AKS/issues/205
