### ISSUE TITLE
[Features] Add a feature to create Public DNS Zones as subdomain of [region].aksapp.io

### ISSUE THREAD

**Issue by danielecazzari** [Azure/AKS#2084]
Having access to a DNS Zone is a very important feature for many AKS applications and not always Private DNS it's the right answer.
AKS has a very nice addon (HTTP application routing) that solves this issue by creating a public DNS zone in the format of [GUID].[region].aksapp.io, but it's only suitable for dev/test environment and it's not practical for an application that leverage Nginx ingress already

It will be useful if AKS could allow the user to create a similar public DNS solution without the need for the add-on and with the possibility to modify [GUID] with a custom name.

**Comment by mikepasco** [comment]
@danimal521 can you please review this?
