### ISSUE TITLE
Enable fast alerting experience on basic metrics for this Azure Kubernetes Services private cluster not working

### ISSUE THREAD

**Issue by andriktr** [Azure/AKS#2085]
Hi, 
I'm trying to enable [How to update Azure Monitor for containers to enable metrics](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-update-metrics) on my private AKS cluster, but seems it's not working as expected. When i trying to enable from portal I receive an error `The role assignment already exists`.  Cluster resource RBAC assignments shows that `Monitoring Metrics Publisher `  permissions assigned accordingly as it described in docs. However metrics are still not available. 

I also have another cluster which is not private and here everything works as expected. 

Any ideas? 

Thanks in advance.

**Comment by miwithro** [comment]
The only piece that does not work in a Private Cluster scenario is the Container Live Data, all other pieces of Azure Monitor for Container works.
https://docs.microsoft.com/en-us/azure/aks/private-clusters

Can you share more details about your deployment?

**Comment by andriktr** [comment]
Hi @miwithro, 
Thank for reply. 
What kind of details you are interested in?
Insights blade for my aks show the following popup about fast alerting:
![image](https://user-images.githubusercontent.com/25537180/106500065-0ed5dc00-64ca-11eb-9289-f80c20c25289.png)
When I try to enable it I receive an error: 
![image](https://user-images.githubusercontent.com/25537180/106500206-37f66c80-64ca-11eb-8a66-25a53b647558.png)

If I look into cluster RBAC assignments i see required permissions assigned on the aks resource:
![image](https://user-images.githubusercontent.com/25537180/106500492-93285f00-64ca-11eb-919f-91f0525c0cb9.png)

As far as I understand I should be able to see the metrics, but they are not available.
This how it should be (my non private cluster): 
![image](https://user-images.githubusercontent.com/25537180/106501351-b7387000-64cb-11eb-9c0f-639dc7e84e35.png)

And this is how it is (my private cluster):
![image](https://user-images.githubusercontent.com/25537180/106501509-ec44c280-64cb-11eb-8915-b7a87e692379.png)

**Comment by miwithro** [comment]
Essentially Fast Alerting requires Live Data which by default Private Clusters don't have access to.   The Role Assignment error is a little misleading there, but it is due to lack of connectivity to Live Data.  You should have been prompted to Enable Live Features after you tried to Enable Fast alerting in the Cluster tab.

![image](https://user-images.githubusercontent.com/50749048/106505439-52165780-6496-11eb-8cb2-7c5d2754861c.png)

**Comment by andriktr** [comment]
But when I set "live on" I see data:
![image](https://user-images.githubusercontent.com/25537180/106509320-26b35d00-64d6-11eb-97ac-ac714af06ede.png)
Doesn't that mean that live data feature is working? 
Live data support public preview for private cluster was announced  in December 2020:
[https://azure.microsoft.com/en-us/updates/azure-monitor-for-containers-support-for-private-clusters/](https://azure.microsoft.com/en-us/updates/azure-monitor-for-containers-support-for-private-clusters/)
Also I don't see any references to live data or limitation for private clusters in docs:
[https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-update-metrics](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-update-metrics)

Thanks.

**Comment by miwithro** [comment]
Yes it is now, after I enabled "Enable live feature".  Updating the AKS Private Cluster document as it has an outdated limitation.   Are you get it working doing the same?

**Comment by andriktr** [comment]
Nope, unfortunately expected metrics are still not visible for me.

**Comment by miwithro** [comment]
Ok. I have a public and a private cluster setup and I see the same under "Metrics" 
![image](https://user-images.githubusercontent.com/50749048/106516110-9872b300-64a4-11eb-8294-66f3b511a181.png)  

I just did a basic deployment of each with Insights enabled and saw no difference in the Metrics.  How did you deploy the private cluster?

**Comment by andriktr** [comment]
I use terraform. Maybe it somehow related to the thing that I assign Monitoring Metrics Publisher to the cluster identity during deployment. This is to skip manual switch ON step of fast alerting via cli or in portal. 
```terraform
resource "azurerm_role_assignment" "aks" {
  scope = azurerm_kubernetes_cluster.aks.id
  role_definition_name = "Monitoring Metrics Publisher"
  principal_id = azurerm_kubernetes_cluster.aks.identity[0].principal_id
}
```

**Comment by miwithro** [comment]
Yes that is most likely the culprit.

**Comment by andriktr** [comment]
Will try another deployment without mentioned block and report back results.
Thanks for advices.

**Comment by aristosvo** [comment]
@andriktr It can also be related with https://github.com/Azure/AKS/issues/1999. What version of Kubernetes are you using? 1.19 seems to break a lot of stuff with regard to monitoring.

**Comment by andriktr** [comment]
Hi @aristosvo, 
Problematic cluster is with version `1.19.3`, but another on ( which is working) is on `1.18.8`, so I believe this could be related to your mentioned issue. Thanks for pointing out.

**Comment by aristosvo** [comment]
@andriktr https://github.com/Azure/AKS/issues/1999 is resolved, maybe this one as well? 🤞

**Comment by andriktr** [comment]
@aristosvo  Thanks for heads up, I need to rise up cluster versions then will report back.

**Comment by andriktr** [comment]
Moving to 19.1.17 fixed the problem.
