### ISSUE TITLE
[Announcement] Incoming Calico release starting from Feb 22 on k8s version 1.20 and above

### ISSUE THREAD

**Issue by weng271190436** [Azure/AKS#2089]
Starting from February 15 2021, AKS clusters using Calico networking policies in all regions will automatically be upgraded from Calico version 3.8.9 to version 3.17.2. This upgrade will cause a breaking change to the default behavior of all-interfaces Host Endpoints. If you are using all-interfaces Host Endpoints and you prefer to keep the default behavior from version 3.8.9, you can find more information on preparing your cluster to preserve this behavior in the [Tigera upgrade guide Host Endpoints section](https://docs.projectcalico.org/maintenance/kubernetes-upgrade#host-endpoints).

If you are not using all-interfaces Host Endpoint, this upgrade won't cause issues, but you will observe the following changes:
- calico-node and typha components is now in calico-system namespace
- kube-controllers is a new component in calico-system namespace
- tigera-operator is a new component in tigera-operator namespace

02/19/2021 Edit:
We are only going to upgrade k8s version 1.20 and above to Calico 3.17.2 starting Feb 22 because it is risky to upgrade all existing clusters to a new Calico version.

**Comment by mattstam** [comment]
For anyone experiencing the networking problems when using Calico with the Kubenet network-plugin on Kubernetes version 1.20+, here is a simple fix:

**First configure the IPPool to use vxlanMode**
Run: `calicoctl patch ippool default-ipv4-ippool -p '{"spec":{"ipipMode": "Never", "vxlanMode": "Always"}}'`

**Then to fix the kube-controllers crashing**
Drain the node the kube-controllers in running on (ie.  `kubectl drain aks-nodepool1-123456789-vmss000000 --ignore-daemonsets`)
Uncordon the node (ie. `kubectl uncordon aks-nodepool1-123456789-vmss000000`)

We are fixing the configuration for new clusters but for existing clusters this will need to be ran.
