### ISSUE TITLE
API server says pod is running event after shutting down node

### ISSUE THREAD

**Issue by writeameer** [Azure/AKS#209]
Hello Everyone,

I've just been testing failure scenarios with AKS. I ran up an AKS cluster with a single node and deployed a nginx pod. I then shut down that only node.

```
$ kubectl get nodes
NAME                       STATUS           AGE       VERSION
aks-nodepool1-54809001-0   NotReady,agent   12d       v1.7.
```

The node is correctly marked as not being ready. When I list my pods, however, it's marked as running on that node whose VM was stopped and deallocated:

$ kubectl get pods

```
$ kubectl get pods -o wide
NAME                        READY     STATUS    RESTARTS   AGE       IP           NODE
my-nginx-1541387465-v892k   1/1       Running   1          1d        10.244.0.3   aks-nodepool1-54809001-0
$
```
While checking the deployment, the cluster thinks the desired count is equal to the current count.

```
$ kubectl get deployment
NAME       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
my-nginx   1         1         1            0           1d
```

Why does K8s thing my pod is running and everything is OK ?

**Comment by jnoller** [comment]
Stale question / how-to, closing
