### ISSUE TITLE
[Features] Please provide functionality through API to force drain node pool

### ISSUE THREAD

**Issue by t3mi** [Azure/AKS#2090]
**What happened**:
In case of small sized node pool or tolerations on it which prevents re-scheduling of the pods configured with pod disruption budget from bigger node pool following error occurs during node pool removal:
```
{
  "code":  "PodDrainFailure",
  "message":  "Node 'aks-vmss-17400673-vmss000001' failed to be drained with error: 'Drain did not complete pods [<pod-name>] within 10m0s'" 
}
```
**What you expected to happen**:
Node pool successfully removed.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy cluster with additional node pool and taints for it. Deploy application with pod disruption budget set inside the nodepool and try to remove the node pool.

**Anything else we need to know?**:
For the reference, there is a flag [`disable-eviction`](https://github.com/kubernetes/kubernetes/pull/85571) for kubectl to force drain a node.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:
[terraform-provider-azurerm#10411](https://github.com/terraform-providers/terraform-provider-azurerm/issues/10411)

**Comment by miwithro** [comment]
@paulgmiller can your team assist?

**Comment by miwithro** [comment]
@marwanad can you assist?

**Comment by paulgmiller** [comment]
@t3mi @miwithro @marwanad  Sorry I missed this. We are considering this option for a specific node pool (I jokingly refering to it as the "--yolo" flag). We're a little concerned that we're giving people a gun to shoot themselves in the foot. Is there a reason you prefer a flag over removing/modifying the PodDisruptionBuget in question? Worry that disable eviction ignoreds every deployment while with a poddisriptionbudget you can be more selective about important services.

**Comment by vapomalov** [comment]
@paulgmiller OP needs it in this case for destroying a cluster with terraform. 
At  least in our case we want to replace one nodepool through another with terraform.

**Comment by t3mi** [comment]
@paulgmiller we are using terraform during deployment and in our CI so during teardown of clusters with nodepools we're having such errors. Instead of adding additional step to gather/remove all PodDisruptionBuget objects and slow CI tests we would prefer for additional flag to be present to force remove nodepools without caring what's inside.

**Comment by vapomalov** [comment]
We opened also an issue at Microsoft Azure support TrackingID #2103170050002008.
Unfortunately while is was on a leave it was closed as "not-an-issue". This feature is implemented by every big cloud provider. 
I am currently reopening the issue.

**Comment by palma21** [comment]
We will consider this feature for nodepool delete to start with.

`aks nodepool delete --force`

**Comment by alvinli222** [comment]
We have done some initial ideation on this feature and will be working to release it in the coming months.

**Comment by digihunch** [comment]
I had to remember to remove PodDisruptionBuget with ALLOWED DISRUPTIONS = 0 before destroy the node group
This feature requested would be very helpful

**Comment by CpuID** [comment]
@palma @qpetraroia @justindavies any ETA on when `aks nodepool delete --force` will be ready...? :)

**Comment by miwithro** [comment]
@kaarthis can you look into this one?

**Comment by kaarthis** [comment]
Yes part of discussion on the Nodepool API. i can look into this and report back.

**Comment by aslafy-z** [comment]
Any news on this one? This issue becomes blocking for us. We want to be able to destroy our dev clusters whatever they state are. Any progress @kaarthis @palma @qpetraroia @justindavies @alvinli222? Thank you

**Comment by oferchen** [comment]
+1

**Comment by alvinli222** [comment]
Hi everyone, this feature we pushed into Public Preview awhile back but there was some bugs that were found. We are actively working on this now and hope to re-release to Public Preview ASAP with an API property flag and also corresponding CLI command. I have communicated this update with the Terraform team as well.

**Comment by landerss1** [comment]
Hi! Any update on this? Without the ability to force drain nodes, the existing feature of being able to start/stop nodepools is not very useful.

**Comment by alvinli222** [comment]
Hi all, this feature is now generally available as Ignore PodDisruptionBudgets for Nodepool Deletes. Please see the following docs for more information: [Link Here](https://learn.microsoft.com/en-us/azure/aks/delete-node-pool?tabs=azure-cli#ignore-poddisruptionbudgets-pdbs-when-removing-an-existing-node-pool)
