### ISSUE TITLE
[Feature] Bring your own CNI/--network-plugin none

### ISSUE THREAD

**Issue by joshmue** [Azure/AKS#2092]
We are currently using Cilium in conjunction with Azure CNI.

When doing this however, there is the problem, that Pods already are started before Cilium is registered/installed inside of the CNI config. This leads to inconsistencies, as these Pods are not managed by Cilium and its network policies, which may be fixed by using some type of workaround: e. g. manually deleting such Pods.
This happens (AFAIK)...
- ...when the cluster is created
- ...potentially on newly created nodes where the cilium agent did not update the CNI config yet

Using workarounds however, is not ideal, of course.

I think the intentions of this issue are sort of similar to #1942. Having read @palma21's comments there, I hope, that the possibility of making Cilium a fully managed part of AKS is considered and implemented some day.

In the meantime, having the option to disable the provisioning of a preconfigured CNI config (preventing Pods to be started before all intended networking plugins are in place), would allow using Cilium or other networking solutions in a much "cleaner" fashion.

Maybe this may be implemented as a third networking profile of some sort: kubenet/AzureCNI/**None** (?)

**Comment by paulgmiller** [comment]
We are still considering BYO network plugin but are trying to figure out how support would work. Do we just not support any network problems? But we do acknowledge this would help cillium, flannel and others by us getting out of the way.

**Comment by joshmue** [comment]
> We are still considering BYO network plugin but are trying to figure out how support would work. Do we just not support any network problems? But we do acknowledge this would help cillium, flannel and others by us getting out of the way.

When being implemented as opt-in feature with known support scope implications, I suppose most customers should be fine with that.

Certainly would have saved us some trouble in the team I'm in. Right now, for us, it's basically a trade-off from use-case perspective: We actually want to have features like...
- ... non-CIDR-based/DNS-based network policies to out-of-cluster locations like Azure database services (AFAIK not easily doable even when incorporating a service mesh with powerful policy tooling)
- ... in-depth networking observability (also integrated into Prometheus etc.)
- ... readiness for multi cluster network policies etc.

But, when attempting to implement these use-cases with Cilium, we found us basically "fighting" with the preconfigured networking, causing related problems - with no known alternative to fulfil the desired feature sets.

So considering this is greatly appreciated.

**Comment by smnmtzgr** [comment]
@mattstam / @paulgmiller any updates available here?

**Comment by kvendingoldo** [comment]
I am really interested in too.

**Comment by mauilion** [comment]
This will be a neat feature!

**Comment by ekarlso** [comment]
+1

**Comment by kvendingoldo** [comment]
any updates here?

**Comment by mattstam** [comment]
Update for folks, this will be an option in the 2022-01-02-preview API.

**Comment by ekarlso** [comment]
@mattstam Hii! When is the ETA ca fro this?

**Comment by smnmtzgr** [comment]
@mattstam what does this mean for AKS-customers? Will this be available as preview-feature soon?

**Comment by ekarlso** [comment]
Gettint any date is usually cricket sounds ;)

**Comment by mattstam** [comment]
@ekarlso, @smnmtzgr the API has not been published yet, but the expectation is that this will be available this February as a preview feature.

**Comment by kvendingoldo** [comment]
We're also waiting as well as @justbert :)

**Comment by ekarlso** [comment]
@mattstam ?

**Comment by mattstam** [comment]
Hello folks!

The documentation around using this feature is in progress. As you may expect, there will be some caveats around network supportability which will be outlined further in the documentation. There is also some recent fixes rolling out which will greatly increase the stability in the stage where nodes do not have a CNI installed yet. For these reasons, I recommend holding off on running production workloads on these clusters temporarily.

To start testing BYO CNI out, you can deploy an ARM template with:

```    
    "resources": [
        {
            "apiVersion": "2022-01-02-preview",
            "type": "Microsoft.ContainerService/managedClusters",
            ...
            "properties": {
                "networkProfile": {
                    "networkPlugin": "none"
                     ...
                },
                ...
            }
        }
    ],
```

The CLI is release is pending, so you will not yet be able to do `az aks create ... --network-plugin none`. That will soon be an option as well, though keep in my you will need to enable `az extension add --name aks-preview` to have this option in the future.

cc @justbert @kvendingoldo @ekarlso

**Comment by mattstam** [comment]
az cli now has the update (if you have aks-preview extension). Simply run `az upgrade` and you will be able to create a BYO CNI clusters from the command line:

```
   --network-plugin                            : The Kubernetes network plugin to use.  Allowed
                                                  values: azure, kubenet, none.
        Specify "azure" for routable pod IPs from VNET, "kubenet" for non-routable pod IPs with an
        overlay network, or "none" for no networking configured.
```

**Comment by smnmtzgr** [comment]
@mattstam thanks for giving us updates and howto-use information. Please inform us also as soon as the docs are updated. Especially I am interested in these things:

- What other features need to be set to "none" or special values when choosing network_pluging=none. E.g. what about IPs? Overlay-IPs/VNET...... or what about network-policies.
- Are you already in exchange with hashicorp to include network_plugin=none into the terraform azurerm-provider?

**Comment by kvendingoldo** [comment]
+1 for this feature in terraform provider

**Comment by mattstam** [comment]
@smnmtzgr Thanks for the feedback! We will try to publish docs as soon as possible. To try and answer some of your questions:

1. Currently, this option is focused on making it easy for you to use an overlay method of your choice. If your use case requires using VNET IPs directly, `--network-plugin=azure` would be recommended. Using the cluster creation time network policies (e.g. `--network-policy=calico`) is not allowed with BYO CNI, but you may set this up manually after CNI install. This area is one of the places we are most looking for feedback during preview. If there are some restrictions AKS has around building your desired networking configuration, please let us know!

2. For IaC compatibility, I don't believe Terraform is currently compatible with our preview APIs. Using Bicep would be an alternative to try.

**Comment by smnmtzgr** [comment]
any updates here? Are the docs already viewable? :)

**Comment by mattstam** [comment]
@smnmtzgr Docs are now up: https://docs.microsoft.com/en-us/azure/aks/use-byo-cni

**Comment by smnmtzgr** [comment]
@mattstam thx. Can you also add another section with "limitations" when using BYO-CNI?
Which AKS-features are not supported anymore? E.g. the feature "private Cluster".

**Comment by justbert** [comment]
While attempting to use the new BYOCNI feature with Cilium, it turns out that the Azure IPAM module is no longer compatible. This is a bit unfortunate, since it would allow us to use some of the advanced capabilities of Cilium while still taking advantage of Azure networking. (Detailed here: https://github.com/cilium/cilium/pull/19379/files#issuecomment-1109947350)
