### ISSUE TITLE
[Feature] Allow nodepool label updates via the AKS API.

### ISSUE THREAD

**Issue by josh-ferrell-sas** [Azure/AKS#2093]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

Allow the end user to update the node labels using the AKS API so deleting and creating a nodepool isn't necessary.

**Comment by mikepasco** [comment]
Closing as this is being tracked under https://github.com/Azure/AKS/issues/1515
