### ISSUE TITLE
Update an AKS cluster to managed identities - BadRequestError after a couple weeks

### ISSUE THREAD

**Issue by ericxw** [Azure/AKS#2094]
**What happened**:
I've been testing with pod-identity provided via Azure Preview with success (EnablePodIdentityPreview) and since my clusters were created with Service Principal, I updated it to use Managed Identity via MigrateToMSIClusterPreview. Everything was working fine and I could assign pod identity using "az aks pod-identity" command. Yesterday found out this no longer works after a couple of weeks and throws the following error:

`BadRequestError: Operation failed with status: 'Bad Request'. Details: Change kubelet identity from ResourceID: ClientID: ObjectID: to ResourceID:/subscriptions/[removed]/resourcegroups/MC_[removed]_canadacentral/providers/Microsoft.ManagedIdentity/userAssignedIdentities/[removed]-agentpool ClientID:[removed] ObjectID:[removed] is not allowed.`

The same exact error is shown when I try to disable Pod Identity or attempt to re-run an update to change to managed identity again.

Running "az aks show" on the cluster shows that "kubeletidentity" matches the one from the error. So I don't understand why it's doing this.

I followed instructions here: https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#update-an-aks-cluster-to-managed-identities-preview. However, I skipped user assigned identity as I saw that the first step to convert to managed identity had created appropriate managed identity(same as the one from the error above). Trying to assign a newly created Managed Identity also fails with exact same error (trying to change from blank to [clustername]-agentpool rather than newly created [clustername]-agentpool2).

The only other thing I can think of is that these clusters had the latest node image before updating to managed identity. Which means the instruction to run "az aks nodepool upgrade --node-image-only" on the node pool in order to finish managed identity conversion didn't actually do anything (I originally had a much older cluster in a sandbox that had older node image which I could see workloads restarting running this command, but ran a test with a new cluster and it did not happen). However, I had disregarded it as Pod Identity was working as expected.

**What you expected to happen**:
Managed Identity should be working correctly and should not cause errors a couple weeks after conversion from service principal and thus Pod Identity creation should also work as expected.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create cluster using Service Principal
2. Convert to Managed Identity using MigrateToMSIClusterPreview feature and skipping user assigned identity (https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#update-an-aks-cluster-to-managed-identities-preview)
3. Set up pod identity and assign pod identity via EnablePodIdentityPreview feature
4. Wait a few weeks, try to assign another pod identity and get the error.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.14 (originally was run on v1.18.8, but forced to upgrade during troubleshooting due to this version no longer being supported)
- Size of cluster: Three clusters - 1, 3, and 5 nodes respectively
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Traefik Ingress controller, Java applications
- Others:
`{
  "azure-cli": "2.18.0",
  "azure-cli-core": "2.18.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.4.73"
  }
}`

**Comment by jozamp** [comment]
We're also seeing this behavior. We were able switch the cluster to system managed identity but when enabling pod-identity we're getting a bad request error, even though the kublet identity reports as proper .

**Comment by ericxw** [comment]
Did you recently just go through the conversion? My three clusters were converted over the past month with at least 1week between each other. The odd thing is that this happened to all three just this week. I was wondering maybe there was an issue with Managed Identity certificate renewal (every 45 days and 90 day expiry) but I'd expect an issue to happen well beyond 1 month.

**Comment by jozamp** [comment]
Yes, we were starting our pod identity experimentation on one of our existing clusters yesterday and got stuck trying to enable pod identity. Maybe something broke in the cli recently, could be why we're both seeing this behavior now with different timings?

**Comment by ericxw** [comment]
I tested creation of a new cluster using Managed Identity from the start and pod identity works there without issues.

Was your cluster already using Managed Identity or using Service principal? The ones I'm having issues with was converted from SP to MI using MigrateToMSIClusterPreview.

**Comment by jozamp** [comment]
Yes, we used "MigrateToMSIClusterPreview" on an existing cluster using SPI, using the same methodology you described.

**Comment by jawhites** [comment]
@palma21 or @jluk can I ask for some eyes on this to help triage?

**Comment by norshtein** [comment]
@ericxw sorry for the inconvenience, this is a bug: for few clusters which has failed PUT managedCluster attempt may hit the issue that cluster can't be updated due to error "ChangeKubeletIdentityNotAllowed". We have fixed the issue for these clusters from our backend. Now you should be able to update your cluster without any issue. Could you please have a try?

The code fix for this issue will be included in next week's release. For any new cluster hitting this issue before the code fix is rolled out, you can open a support ticket or simply delete and re-create the cluster.

**Comment by ericxw** [comment]
This appears to have resolved the issue for me. Thank you!

**Comment by cheslijones** [comment]
I'm running into this issue currently. 

Similar scenario: 
- Existing AKS cluster
- Want to enable Azure Key Vault <-> Azure Kubernetes Service integration
- Want to use Pod identities to accomplish this

Following the steps as they are outlined here:

https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity#register-the-enablepodidentitypreview

Recounting my steps from yesterday from my zsh history...

Looks like I had to do the following first:
```
az feature register --namespace Microsoft.ContainerService -n MigrateToMSIClusterPreview   

az provider register -n Microsoft.ContainerService   
```
Then I could:
```
az aks update -g company-app -n companyppaks --enable-managed-identity  

Operation failed with status: 'Bad Request'. Details: Change kubelet identity from ResourceID: ClientID: ObjectID: to ResourceID:/subscriptions/<GUID>/resourcegroups/MC_company-app_companyppaks_westus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/companyppaks-agentpool ClientID:<GUID> ObjectID:<GUID> is not allowed.
```
Ignoring I try the following:
```
az aks update -g company-app -n companyappaks --enable-pod-identity The behavior of this command has been altered by the following extension: aks-preview
Operation failed with status: 'Bad Request'. Details: Network plugin kubenet is not supported to use with PodIdentity addon.
```
I've also tried:
```
az aks update -g company-app -n companyappaks --network-plugin azure
az: error: unrecognized arguments: --network-plugin azure
usage: az [-h] [--verbose] [--debug] [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH] {aks} ...
```
Thinking I might need to start a new cluster and start over with this enabled from the start.

Also, now my cluster in the Azure Portal says: "The container service is in a failed state." Appears to be related to the Service Principal credentials.

![image](https://user-images.githubusercontent.com/59094233/107800405-98c84500-6d13-11eb-8f3a-372dc3743ba9.png)

**Comment by norshtein** [comment]
Already fixed.
