### ISSUE TITLE
az aks create: error: unpack requires a bytes object of length 4

### ISSUE THREAD

**Issue by diegotroitino** [Azure/AKS#21]
Following [this tutorial](https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-deploy-cluster), when I try to create the Kubernete cluster, I get the error "_az aks create: error: unpack requires an object bytes length 4_"

![image](https://user-images.githubusercontent.com/5686833/32356156-5c26b3ba-c01a-11e7-9649-c348f6f511c1.png)

Running with --debug, this is all output:

> Command arguments ['aks', 'create', '--resource-group', 'catalogoResourceGroup', '--name', 'catalogoCluster', '--agent-count', '1', '--generate-ssh-keys']
> Loading all installed modules as module with name 'aks' not found.
> Installed command modules ['acr', 'acs', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'cdn', 'cloud', 'cognitiveservices', 'component', 'configure', 'consumption', 'container', 'cos
> mosdb', 'dla', 'dls', 'eventgrid', 'extension', 'feedback', 'find', 'interactive', 'iot', 'keyvault', 'lab', 'monitor', 'network', 'profile', 'rdbms', 'redis', 'resource', 'role', 'servicefab
> ric', 'sql', 'storage', 'vm']
> Current cloud config:
> {'endpoints': {'active_directory': 'https://login.microsoftonline.com',
>                'active_directory_data_lake_resource_id': 'https://datalake.azure.net/',
>                'active_directory_graph_resource_id': 'https://graph.windows.net/',
>                'active_directory_resource_id': 'https://management.core.windows.net/',
>                'batch_resource_id': 'https://batch.core.windows.net/',
>                'gallery': 'https://gallery.azure.com/',
>                'management': 'https://management.core.windows.net/',
>                'resource_manager': 'https://management.azure.com/',
>                'sql_management': 'https://management.core.windows.net:8443/',
>                'vm_image_alias_doc': 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json'},
>  'is_active': True,
>  'name': 'AzureCloud',
>  'profile': 'latest',
>  'suffixes': {'azure_datalake_analytics_catalog_and_job_endpoint': 'azuredatalakeanalytics.net',
>               'azure_datalake_store_file_system_endpoint': 'azuredatalakestore.net',
>               'keyvault_dns': '.vault.azure.net',
>               'sql_server_hostname': '.database.windows.net',
>               'storage_endpoint': 'core.windows.net'}}
> Registered application event handler 'CommandTableParams.Loaded' at <function add_id_parameters at 0x03F936A8>
> Registered application event handler 'CommandTable.Loaded' at <function add_id_parameters at 0x03F936A8>
> Loaded module 'acr' in 0.013 seconds.
> Loaded module 'acs' in 0.002 seconds.
> Registered application event handler 'CommandParser.Parsing' at <function deprecate at 0x03FA9BB8>
> Loaded module 'appservice' in 0.005 seconds.
> Loaded module 'backup' in 0.002 seconds.
> Loaded module 'batch' in 0.011 seconds.
> Loaded module 'batchai' in 0.003 seconds.
> Loaded module 'billing' in 0.002 seconds.
> Loaded module 'cdn' in 0.005 seconds.
> Loaded module 'cloud' in 0.001 seconds.
> Loaded module 'cognitiveservices' in 0.002 seconds.
> Loaded module 'component' in 0.001 seconds.
> Loaded module 'configure' in 0.001 seconds.
> Loaded module 'consumption' in 0.003 seconds.
> Loaded module 'container' in 0.002 seconds.
> Registered application event handler 'CommandParser.Parsing' at <function deprecate at 0x04075978>
> Loaded module 'cosmosdb' in 0.004 seconds.
> Loaded module 'dla' in 0.003 seconds.
> Loaded module 'dls' in 0.002 seconds.
> Loaded module 'eventgrid' in 0.002 seconds.
> Loaded module 'extension' in 0.001 seconds.
> Loaded module 'feedback' in 0.003 seconds.
> Loaded module 'find' in 0.001 seconds.
> Loaded module 'interactive' in 0.001 seconds.
> Loaded module 'iot' in 0.002 seconds.
> Loaded module 'keyvault' in 0.003 seconds.
> Loaded module 'lab' in 0.002 seconds.
> Loaded module 'monitor' in 0.003 seconds.
> Loaded module 'network' in 0.010 seconds.
> Loaded module 'profile' in 0.002 seconds.
> Loaded module 'rdbms' in 0.003 seconds.
> Loaded module 'redis' in 0.003 seconds.
> Loaded module 'resource' in 0.003 seconds.
> Loaded module 'role' in 0.002 seconds.
> Loaded module 'servicefabric' in 0.002 seconds.
> Loaded module 'sql' in 0.004 seconds.
> Loaded module 'storage' in 0.012 seconds.
> Loaded module 'vm' in 0.004 seconds.
> Loaded all modules in 0.127 seconds. (note: there's always an overhead with the first module loaded)
> Extensions directory: 'C:\Users\1545 IRON V4\.azure\cliextensions'
> Application event 'CommandTable.Loaded' with event data {'command_table': {'aks create': <azure.cli.core.commands.CliCommand object at 0x03FA6990>}}
> Application event 'CommandParser.Loaded' with event data {'parser': AzCliCommandParser(prog='az', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_hand
> ler='error', add_help=True)}
> Application event 'CommandTableParams.Loaded' with event data {'command_table': {'aks create': <azure.cli.core.commands.CliCommand object at 0x03FA6990>}}
> Application event 'CommandParser.Parsing' with event data {'argv': ['aks', 'create', '--resource-group', 'catalogoResourceGroup', '--name', 'catalogoCluster', '--agent-count', '1', '--generat
> e-ssh-keys']}
> Application event 'CommandParser.Parsed' with event data {'command': 'aks create', 'args': Namespace(_command_package='aks', _jmespath_query=None, _log_verbosity_debug=False, _log_verbosity_v
> erbose=False, _output_format='json', _parser=AzCliCommandParser(prog='az aks create', usage=None, description='Create a managed Kubernetes cluster. :type dns_name_prefix: str', formatter_clas
> s=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True), _validators=[<function validate_linux_host_name at 0x04FE6150>, <function validate_ssh_key  [...]

**Comment by slack** [comment]
We have released az CLI 2.0.23, do you still see the issue?
