### ISSUE TITLE
Cluster is not yet ready when az aks create returns

### ISSUE THREAD

**Issue by DonMartin76** [Azure/AKS#210]
I have had the following issues with fresh deployments of a really small AKS clusters (one node, westeurope):

1. `az aks create` succeeds, and I can retrieve credentials successfully
2. When calling `kubectl get nodes` I see that my worker node is `NotReady`
3. Checking the pod state in `kube-system`, most Kubernetes system pods are not running

I can still deploy things to the cluster, but I usually get into this situation: My own pods manage to get scheduled for pulling prior to e.g. `kube-dns` or `kube-proxy`, and this usually does not work.

We could poll the API and check for the following deployments to be ready until we continue, but that sort of feels wrong: `kube-dns`, `heapster`, `kube-proxy`, `kube-svc-redirect` and `tunnelfront` (whatever that is). Some of those aren't pure upstream Kubernetes things, and thus I suppose they are also subject to change over time. Sometimes the kubernetes components are ready quite fast, but in some cases I had delays of over five minutes between node `Ready` and the components actually being up and running.

So, the short question is: How can I make sure that the cluster is "ready", i.e. the Kubernetes system components are up and running? Checking whether the node is `Ready` is apparently not enough, as I manage to deploy my own containers to a half defunct cluster.

Or: Like with acs-engine, can `az aks create` do this validation prior to returning?

**Comment by amanohar** [comment]
@DonMartin76 AKS is adding a feature that will begin rolling out soon where PUT operation will declar success only when all components of the cluster: the control plane, agents, and control plane add-ons are ready. If any of those are not ready within the lifetime of PUT operation then the create/update will fail.

**Comment by ultimateboy** [comment]
This feature should now be rolled out. Clusters creates should not complete until all service-pods are up and running.
