### ISSUE TITLE
Adding Windows node pool does not work

### ISSUE THREAD

**Issue by r3econ** [Azure/AKS#2101]
<img width="551" alt="gTekv" src="https://user-images.githubusercontent.com/505054/107143288-9c835280-6934-11eb-873d-972decfc275b.png">

I have a cluster that I created via the Azure Portal (not CLI). My pods are failing to use Windows based images. 
I'm getting the following error:
`Windows node pools require a Windows authentication profile.`

From what I found out googling, I'd need to pass  `--windows-admin-password` and `--windows-admin-username` during creating the cluster via CLI.

The cluster is already running and recreating it is not an option.
How can I add a Windows node pool to the existing cluster? Or how can I provide the `--windows-admin-password` and `--windows-admin-username` to the existing cluster?

**Comment by AbelHu** [comment]
@r3econ Please check whether your cluster is using VirtualMachineScaleSets and Azure CNI. If either is not set, AKS will not generate the default WindowsProfile since it does not support Windows agent pools.
https://docs.microsoft.com/en-us/azure/aks/windows-container-cli#create-an-aks-cluster.

**Comment by r3econ** [comment]
I figured it out on my own.
