### ISSUE TITLE
Assigning private ips for outbound traffic in AKS private cluster 

### ISSUE THREAD

**Issue by zycon** [Azure/AKS#2102]
No possible way to create a private outbound load balancer for egress traffic. 
Inbound address of pod's needs to be whitelisted in client firewall, but couldn't find any feasible way unless mentioning the aks cidr range

Either a internal NAT gateway for egress traffic or internal loadbalancer which supports egress traffic

AKS private cluster, and having custom checkpoint firewall which facilitates the site-to-site vpn

**Comment by miwithro** [comment]
For Private outbound use a Private Cluster

https://docs.microsoft.com/en-us/azure/aks/private-clusters
