### ISSUE TITLE
Azure RBAC for Kubernetes Authorization without Managed Azure AD integration

### ISSUE THREAD

**Issue by Tetradeus** [Azure/AKS#2103]
**What happened**:
When we want to create a private cluster with a custom private Dns Zone, it looks like we cannot use Managed Azure AD integration. https://docs.microsoft.com/en-us/azure/aks/private-clusters#configure-private-dns-zone

If we want to use Azure RBAC for Kubernetes Authorization, we are forced to use Managed Azure AD principal.
https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac

Is this only a current preview limitation ? Would we be allowed to use Azure RBAC for Kubernetes Authorization with a non managed Azure AD principal or is there a real limitation ?

**Environment**:
- Kubernetes version 19
- Private Cluster with custom DNS zone
- Non managed azure ad principal

**Comment by miwithro** [comment]
@Tetradeus no this works currently.  You can deploy 1.19, with a private cluster integrated with Azure.

![image](https://user-images.githubusercontent.com/50749048/107383470-07609500-6abf-11eb-8d7f-15b6a3d74838.png)

**Comment by Tetradeus** [comment]
Hi @miwithro , yes it works. 
But when you want to use a custom private Dns zone (not system assigned), you cannot use System assigned managed identity.
I did not really understand why System assigned managed identity is required to use Azure RBAC for Kubernetes Authorization, so I wanted to know if we could allow/enable it without System assigned managed identity.

Thanks.

**Comment by miwithro** [comment]
@Tetradeus this only works with User assigned Managed Identity.

**Comment by Tetradeus** [comment]
All right, so there is no plan to make it works without it ? I was not sure if it was heavily linked behind the scene.

**Comment by miwithro** [comment]
Correct.  The main reason is customers won't know the object id of the system assigned identity before cluster creation, so the permission needed for BYO route table can't be granted before cluster creating, which will cause cluster creation error.
