### ISSUE TITLE
Lifetime of AAD credentials expires after 1 hour on Mac

### ISSUE THREAD

**Issue by pascalnaber** [Azure/AKS#2104]
A couple of team members are using a Mac to connect to our AAD enabled cluster using Managed Identity.
They need to login every hour.
On Windows and Linux it works fine. But not on Mac. We all use kubectl v1.19.3

I'm still not sure if the Mac is the reason for the difference in behavior, but it's the only difference we see.

I've seen this issue, which is the same behavior:
https://github.com/Azure/AKS/issues/1580

Any idea what we could do about this? Increase the expiration time?

**What happened**:
We need to login every hour. But only on a Mac.
Works fine on Windows and Linux.

**What you expected to happen**:
Automatic refresh of credentials

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.3
- Size of cluster (how many worker nodes are in the cluster?) 3 worker nodes

**Comment by miwithro** [comment]
@weinong

**Comment by weinong** [comment]
@pascalnaber are you saying the token didn't get refreshed after an hour such that you had to login again?

**Comment by miwithro** [comment]
@pascalnaber are you still experiencing the issue?  Have you upgraded your kubectl through az aks install-cli

**Comment by pascalnaber** [comment]
Yes, we are still experiencing the issue and ofcourse we are using the latest version of kubectl.
I'm indeed saying the token is not refreshed.

**Comment by weinong** [comment]
@pascalnaber can you add -v=4 after an hour of inactive and share the log?

**Comment by mrmuli** [comment]
I'm facing a similar issue, except I'm on CentOS. I configured an app registration with a service principal and a **Azure Kubernetes Service Cluster User Role** whose token expires every hour. I'd like to alter this lifetime and I'm not sure whether it's the role I need to reconsider? 
My goal is cluster access for an external service.

**Comment by weinong** [comment]
@mrmuli https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes
