### ISSUE TITLE
Kubectl delete node supported?

### ISSUE THREAD

**Issue by MCKLMT** [Azure/AKS#2105]
**What happened**:

When I run the command ```kubectl delete node *** ``` it remove the node from the cluster but the VM is not removed from the VM ScaleSet. Is it by design?

**What you expected to happen**:

The VM should be removed from the ScaleSet.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a cluster with 3 nodes
- Execute the command ```kubectl delete node *** ```
- A node is removed from the cluster
- The VM is still there in the VMSS.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.6
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by tomkerkhove** [comment]
We've seen the same outcome which was not expected. Is this by design @palma21?

**Comment by palma21** [comment]
Correct, that is not supported. The was to remove nodes or touch the infra is through the AKS API (scale in this case).
