### ISSUE TITLE
Windows nodepool update fails because of 10min drain timeout

### ISSUE THREAD

**Issue by brobichaud** [Azure/AKS#2114]
**What happened**:
Using the nodepool upgrade process (az aks nodepool upgrade) fails on a Windows nodepool with an error that the drain did not complete within the 10 minute timeout.

**What you expected to happen**:
For the drain to wait until all pods are successfully drained. Not to bail out after 10 minutes, which is clearly not long enough in all cases. My Windows nodepool hosts a mix of pods that use a variety of Windows base images, including the gargantuan "Windows" image, you know, the 12GB image. This image can take a very long time to pull.

I was watching all of my pods during this process and about 6 minutes after the drain failed all pods were running. I do have pod disruption budgets for all workloads and had no availability issues during this process.

The problem occurred when it got to the last of my 3 nodes in the Windows nodepool. I could see that some of the pods that were moved from the first and second nodes had not yet started (waiting on that huge base image). Because of my PDB's the drain of this last node took a total of 16 minutes, and the upgrade failed after 10 minutes.

**How to reproduce it (as minimally and precisely as possible)**:
1. Have a Windows nodepool with 3 or more nodes.
2. Have a variety of pods running (I had 64 total) using a mix of Windows base images, including the full Windows image.
3. Have a reasonable PDB defined for each deployment.
4. Perform a nodepool upgrade using this command:
`az aks nodepool upgrade --cluster-name mycluster --resource-group mygroup --name mypool --node-image-only`
5. Watch as it walks through draining each node, as it progresses you should notice some pods from the first node taking a long time to start
6. Eventually it times out when it can't drain a node within 10 minutes

**Anything else we need to know?**:
It is probably important to have many pods running so that lots of image pulls are required when push pods to an updated node.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.10
- Size of cluster (how many worker nodes are in the cluster?): 3 nodes of type Standard_D4as_v4
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Mix of NetCore v3 and DotNet v4.8 workloads, some AspNet, some workers, all C# with many native code dependencies
- Others:

**Comment by to-kr** [comment]
We have the same problem. Is there any workaround?

**Comment by brobichaud** [comment]
@to-kr my workaround is to manually upgrade by creating a new nodepool similar to the old, then draining each of the nodes in the old nodepool. If you do this after upgrading the control plane the new nodepool will be the new k8s version. It's completely lame to have to do this manually, but it works seamlessly.

**Comment by paulgmiller** [comment]
<a spirit appears> 

Mind sharing the particular 12 gig image you're pulling so we could try and reproduce? Even 12 gigs should move fairly quickly across the azure internal network and we'd love to make things faster rather than extending timeouts. 

If this is a problem for many windows node pools we could give them a higher timeout but again making it faster is a priority. Also considering making the timeout configurable per nodepool

**Comment by AbelHu** [comment]
@brobichaud @to-kr Could you file a support ticket for your issue and ask CSS to contact me (my alias: abelch)? I think that we can increase the drain timeout for your subscriptions. After it works, I think that we can use a different drain timeout for Windows.

**Comment by brobichaud** [comment]
@paulgmiller The 12GB image is mcr.microsoft.com/windows:1809, and it has actually frown to 15GB.

**Comment by AbelHu** [comment]
> @paulgmiller The 12GB image is mcr.microsoft.com/windows:1809, and it has actually frown to 15GB.

@immuzz The Windows image becomes bigger and bigger and it should also be an issue in disk spaces.

**Comment by brobichaud** [comment]
@AbelHu I am in the process of creating a ticket with support (which for me is painfully slow). Hopefully they will be in touch in the next day or so.

**Comment by weijuans-msft** [comment]
@brobichaud you are right, the current Windows image is 15GB on the disk. It includes the ~8.9GB RMT layer and the latest monthly patch ~6.1GB.  The ratio of the patch layer size vs. the RTM layer size is unusually high. I am not sure what triggered this.

I am curious how you use that Windows image. What scenarios or apps?

For the upcoming new Windows Server 2022 release, we have a new image called "Server" image that will replace this "Windows" image. All container images from Windows Server 2022 release are optimized on the size. You will see that "Server" image is about 6.4GB on the disk.

You can feel free to post Windows container issues here which our team monitors more frequently: https://github.com/microsoft/Windows-Containers/issues.

@AbelHu

**Comment by brobichaud** [comment]
@weijuans-msft we have one very specific workload that requires this base image. It utilizes image and audio processing and relies on some underlying Windows API's that are not available in ServerCore nor nanoserver. We haven't had the resources to do the work to try and extricate ourselves from those API's. Believe me I would love to remove the dependency and get down to ServerCore (or even nanoserver where most of our workloads are). This huge image causes delays and issues in various parts of our devops pipeline.

I did read one public blog post about the new Server image and am most definitely intrigued! As soon as AKS supports Server 2022 we will most definitely migrate to it. Until then I am hesitant to even play with it.

Alas I am also frustrated with he AKS team for their seeming disinterest in trying to bring Windows even close to on-par with Linux. Like why am I still today stuck with 1809 images in AKS? They are 3 years old now. I get the challenges, but you're Microsoft, you ARE Windows and yet AKS is very much Linux first. Frustrating and just pushing people to Linux. </end-of-rant>

**Comment by AbelHu** [comment]
We are planning to use a different drain timeout (30 minutes) for Windows by default.
@brobichaud WS2022 is in our roadmap and will be supported.

**Comment by brobichaud** [comment]
I can confirm that once @AbelHu manually increased the drain timeout to 30 minutes on our two clusters this process now succeeds. We are running k8s v1.20.9 on these clusters and continue to use the very large 15GB Windows base image. The process did take a while as expected, but was seamless and much less error prone than the manual steps we were using before (creating a new nodepool and moving all workloads over to it).

From my perspective once this new 30 minute timeout is the default for new clusters this issue can be closed.

**Comment by AbelHu** [comment]
@brobichaud Thanks for the feedback. AKS has set the default drain timeout to 30 minutes for both Linux and Windows now.
