### ISSUE TITLE
[Feature] Support WS2022 on Windows

### ISSUE THREAD

**Issue by keikhara** [Azure/AKS#2115]
Windows AKS will be supporting the upcoming LTSC OS in addition to Windows Server 2019. 

For guidance on upgrading your nodepool from WS2019 to WS2022, check out this [blog post!](https://techcommunity.microsoft.com/t5/itops-talk-blog/upgrading-your-container-app-from-windows-server-2019-to-2022-on/ba-p/3587990)

**Comment by immuzz** [comment]
Is there any specific feature you're looking for in WS2022? The work is being done right now to enable it with upstream K8s.

**Comment by peter-bertok** [comment]
> Is there any specific feature you're looking for in WS2022?

@immuzz The ability to use gMSA identities for AD domain auth without having to domain-join the hosts is a killer feature of Windows Server 2022. Without it, many types of lift-and-shift V2C migrations are simply out of the question.

**Comment by mikenri** [comment]
> Is there any specific feature you're looking for in WS2022? The work is being done right now to enable it with upstream K8s.

@immuzz 
Another big benefit is a 40% smaller container image. 
Windows container images take a long time to pull because they are so large. 
Reducing image pull time by 40% would really help speed up AKS node updates/upgrades.

**Comment by artisticcheese** [comment]
> > Is there any specific feature you're looking for in WS2022? The work is being done right now to enable it with upstream K8s.
> 
> @immuzz
> Another big benefit is a 40% smaller container image.
> Windows container images take a long time to pull because they are so large.
> Reducing image pull time by 40% would really help speed up AKS node updates/upgrades.

Where do you see 40% savings? I understand it's advertised as such but it looks like 10% savings based on images I have
PS C:\Users\artis> docker images
REPOSITORY                                  TAG                              IMAGE ID       CREATED       SIZE
mcr.microsoft.com/windows/servercore        win10-21h1-preview               1967dbbeedc5   3 weeks ago   5.1GB
mcr.microsoft.com/windows/servercore        ltsc2019                         d1724c2d9a84   4 weeks ago   5.7GB

**Comment by aidapsibr** [comment]
Can anyone clarify why image savings are advertised as 40% when only 10% was seen? Is it just not ready yet, or does that apply to only nano?

**Comment by urbanfly** [comment]
> Can anyone clarify why image savings are advertised as 40% when only 10% was seen? Is it just not ready yet, or does that apply to only nano?

https://devblogs.microsoft.com/dotnet/we-made-windows-server-core-container-images-40-smaller/
https://techcommunity.microsoft.com/t5/containers/making-windows-server-core-containers-40-smaller/ba-p/1058874

**Comment by artisticcheese** [comment]
@urbanfly 
> https://devblogs.microsoft.com/dotnet/we-made-windows-server-core-container-images-40-smaller/ https://techcommunity.microsoft.com/t5/containers/making-windows-server-core-containers-40-smaller/ba-p/1058874

Here is all the sizes of both servercore and Nano server image. There is nowhere close to 40% savings.
Nanoserver image actual grew from 258MB to 295MB
Servercore shrunk from 5.75GB to 4.95GB which is 16%

```
PS C:\Users\Administrator> docker images
REPOSITORY                                 TAG                          IMAGE ID       CREATED       SIZE
mcr.microsoft.com/windows/servercore       ltsc2019                     60d6f56ecebd   12 days ago   5.75GB
mcr.microsoft.com/windows/nanoserver       1809                         1b0690f17ad9   12 days ago   258MB
mcr.microsoft.com/windows/servercore       ltsc2022                     11cbc9e36c7a   2 weeks ago   4.95GB
mcr.microsoft.com/windows/nanoserver       ltsc2022                     5ac089376b5f   2 weeks ago   295MB
```

**Comment by cwilhit** [comment]
You should **not** expect a 40% reduction going from WS2019 server core base image to WS2022 server core base image.

Regarding the Windows image size, we've provided an updated explanation in the windows container docs [here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/whats-new-ws2022-containers#server-core-image-size-reduction) that I hope helps clarify things. The Windows container base images are all composed of two layers: the "RTM layer", which you can think of as a snapshot of the OS at the point in time when it was marked for release to the world, and a "patch layer", which contains all the deltas/changes that need to be applied on top of that layer to the OS binaries/libraries (think of things like cumulative security patches, bug fixes, and the like).

Those blog posts published some time ago highlight the progress we've made in getting that base layer (RTM layer) size reduced. It's good progress and generally a smaller RTM layer _does_ mean a smaller total image, but it only tells part of the story: if you go pull one of the base images on a brand new machine, you have to pull the whole image (the RTM layer and the patch layer). Amidst the excitement of sharing the progress in reducing one of these layers & how .NET layers in with Windows containers, those blogs linked in this thread were not clear enough in providing this important caveat; so we're working on updating them to resolve the confusion.

**Comment by artisticcheese** [comment]
@cwilhit How did we end up with increased nanoserver image size though?

**Comment by cwilhit** [comment]
I'd attribute it to the binaries that compose nanoserver changing a bit from release to release. Compositionally, I do not think there are any noteworthy changes, otherwise we'll blog about it or make notes on our docs. I see where you are leading this though--I take it you would appreciate greater visibility into what's changing from release to release for all the base images?

Our focus generally is geared towards optimizing server core. Take for example the blogs linked above which talks about how .NET framework runtime layers on server core, this is not applicable to nano server, since nano server does not support running .NET framework.

**Comment by bplasmeijer** [comment]
Cannot wait for this feature is released, I need less sized images.

**Comment by rectified95** [comment]
@keikhara What's the status of this effort? This paragraph - https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#windows-os-version-support - seems to suggest that in K8S 1.24 Windows Server 2022 is supported. What's the timeline for pulling it into AKS?

Also, if there's an as yet unsupported way of trying this, I'd really like to use it. Thanks!

**Comment by mikenri** [comment]
The latest update I heard on this from Microsoft Support is that Windows Server 2022 as an option for node pools should be coming in Fall 2022.

**Comment by zhiweiv** [comment]
Any ETA for WS2022 GA?

**Comment by allyford** [comment]
Windows Server 2022 is now GA on AKS. 
Take a look at our documentation for guidance on [upgrading your workloads from Windows Server 2019 to 2022](https://learn.microsoft.com/en-us/azure/aks/upgrade-windows-2019-2022) and [adding new Windows Server 2022 nodepools.](https://learn.microsoft.com/en-us/azure/aks/learn/quick-windows-container-deploy-cli) Windows Server 2019 will remain default for nodepool creation until kubernetes 1.25.
