### ISSUE TITLE
Use chrony + ptp for timesync within the Ubuntu images in AKS

### ISSUE THREAD

**Issue by mabicca** [Azure/AKS#2118]
**What happened**:
We have been getting a few reports from customers about the behavior of NTP in AKS. Most customers that are upgrading from 1.17.x to 1.18.x notice a drastic change in NTP behavior. The changes are expected since Ubuntu changed from ntp.ubuntu.com to the *.ubuntu.pool.ntp.org pools (Open NTP project).

This is a drastic change for environments where NTP access is controlled by firewalls (port 123/UDP > Internet). Before the change, it was possible to simply add 4 IP addresses that are assigned to ntp.ubuntu.com, now that is not possible anymore since the pool of IP's from ntp.org is large and changes dynamically and very often.

**What you expected to happen**:
Able to limit access to external NTP servers as it was before , or avoiding NTP queries to be sent outside of the VM.

**How to reproduce it (as minimally and precisely as possible)**:
Deploying a recent version of AKS, we can simply run a tcpdump to look for requests being sent OR look at syslog and notice the entries "soliciting pool server X.X.X.X" where we can see all the different IPs that are being queried. I am attaching a list which was sanitized and I kept only the string and IP.

**Anything else we need to know?**:
It would be highly recommended to implement chrony + ptp for timesync in these VMs since that is the recommended and reliable way of doing timesync within Azure , without the need to use Internet NTP sources, a good reference to this is here:

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync

**Comment by mabicca** [comment]
Created a gist with the list of IPs here -> https://gist.github.com/mabicca/a5ecd8a10bbb35c5cbd6b194d3ad66dd

**Comment by IulianToader** [comment]
Hi there, is there any traction on this issue?

**Comment by xuto2** [comment]
It's being released and already hit the below regions. Please give it a try  on these regions

westcentralus
ukwest
uksouth
southeastasia
eastasia
canadaeast
canadacentral
australiasoutheast
australiaeast
australiacentral
eastus2euap
centraluseuap

**Comment by mabicca** [comment]
Hi @xuto2 , thanks for the update. Is this going to be rolled out to other regions as well? It does look like it's working now the only thing that would probably be a good idea was to disable the ntp from startup since it still tries to connect a couple of times until systemd realizes ptp is being used and stops it. :)

**Comment by xuto2** [comment]
yes it's following aks service release train so it's probably everywhere at this moment.  This time we did it in a soft way, and yes we plan to stop it from the very beginning.

**Comment by mabicca** [comment]
Alright, thanks for the update :)

**Comment by OthmanAljundi-01** [comment]
If anyone have cases related to the time sync issue

the following resolution will create a deamonset that will install chrony on all nodes and new scaled ones : 
wget https://raw.githubusercontent.com/OthmanAljundi-01/AKS/main/k8s-install-chrony-ds.yml

kubectl apply -f kubectl apply -f k8s-install-chrony-ds.yml

kubectl get ds -A
