### ISSUE TITLE
VMSSAgentPoolReconciler retry failed: does not have enough capacity for 101 IP addresses

### ISSUE THREAD

**Issue by V4A001** [Azure/AKS#2119]
I used the sample to assign a subnet to use managed identities. Now I wanted to upgrade the cluster, but it seems not sufficient ip addresses are present:

I created this subnet and only have 30 containers/ pods running. Any ideas how to fix this?

az network vnet create \
    --resource-group $RESOURCE_GROUP \
    --name $CLUSTER_VNET \
    --address-prefixes 192.168.0.0/16 \
    --subnet-name $CLUSTER_VNET_SUBNET_NAME \
    --subnet-prefix 192.168.1.0/24

**Comment by miwithro** [comment]
@V4A001 as long as your Virtual Network can support it you can change the size of the subnet.  That might be the easiest path.

https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-manage-subnet#change-subnet-settings

**Comment by V4A001** [comment]
I get error that the subnet is in use. I try to change 192.168.1.0/24 to 192.168.0.0/23 (256 to 512)
Adding extra node is not possible for a basic network by the way.

**Comment by mikepasco** [comment]
@V4A001 we're sorry for the delay in reaching your issue. Can you please confirm if you were able to complete the upgrade?

For reference, AKS will introduce an additional node into the nodepool during an upgrade - https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#plan-ip-addressing-for-your-cluster. You will not be able to resize the subnet once the cluster is deployed. If you do not have enough free space in the subnet for an extra node during upgrade, you will need to scale the nodepool down by 1 node to free up space. Once the upgrade is complete, you can revert the scale setting back.
