### ISSUE TITLE
Will the Stop/Start feature be compatible with the cluster autoscaler?

### ISSUE THREAD

**Issue by LoicAG** [Azure/AKS#2120]
Hello, this is a question regarding [the latest release](https://github.com/Azure/AKS/releases/tag/2021-02-08), and more specifically the Stop/Start feature, now GA.

[The documentation for the preview](https://docs.microsoft.com/en-us/azure/aks/start-stop-cluster) mentions that the cluster autoscaler must be stopped; is this still the case, now that the feature is GA?

**Comment by Kraelog** [comment]
Hello!

I would very much like to inquire if/when the issues with CA will be resolved. 

Currently in my environment stopping an AKS cluster works without a problem. 

However, when I start the AKS cluster through an ARM pipeline, the system starts more nodes then specified by the minimum configuration, at which point the cluster autoscaling blocks the extra node and the provisioning state of the cluster goes to "failed". 

Is this something being worked on? 

Thanks!

**Comment by justin-chizer** [comment]
I am having a similar issue. `az aks stop -g <rg> -n <name>` works fine.
But when I run `az aks start -g <rg> -n <name>` the cluster no longer respects the min count for the CA. 

Using AZ CLI version: 2.20.0
AKS version: 1.19.6
Azure Region: westus2
```json
 {
      "availabilityZones": null,
      "count": 0,
      "enableAutoScaling": true,
      "enableNodePublicIp": false,
      "maxCount": 4,
      "maxPods": 110,
      "minCount": 2,
      "mode": "System",
      "name": "system",
      "nodeImageVersion": "AKSUbuntu-1804gen2containerd-2021.02.10",
      "nodeLabels": {},
      "nodeTaints": null,
      "orchestratorVersion": "1.19.6",
      "osDiskSizeGb": 40,
      "osDiskType": "Ephemeral",
      "osType": "Linux",
      "powerState": {
        "code": "Running"
      },
      "provisioningState": "Succeeded",
      "proximityPlacementGroupId": null,
      "scaleSetEvictionPolicy": null,
      "scaleSetPriority": null,
      "spotMaxPrice": null,
      "tags": null,
      "type": "VirtualMachineScaleSets",
      "upgradeSettings": {
        "maxSurge": null
      },
      "vmSize": "Standard_E2as_v4",
      "vnetSubnetId": "/subscriptions/***/resourceGroups/rg-dev-westus2/providers/Microsoft.Network/virtualNetworks/vnet-dev-westus2/subnets/sub-dev-dev3"
    }
```

Did I miss a step?

cc: @palma21

**Comment by palma21** [comment]
Thanks. Should be correct now, it does support CA now. Let us know if you still find any  inconsistency.

**Comment by palma21** [comment]
@justin-chizer your issue seems a different question then OP, can you clarify what you mean by respecting min count? 

Per CA upstream behavior min count is only actionable when CA evaluates if it should scale down. If you start your pool it would come with 0 and CA would scale it up to the needs at the moment respecting the max.
