### ISSUE TITLE
User mode node pools should have the kubernetes.azure.com/mode label

### ISSUE THREAD

**Issue by ankrause** [Azure/AKS#2122]
**What happened**:
Node pool in the "user" mode does not have a label indicating it's running in the user mode. System node pools have the label `kubernetes.azure.com/mode=system`.

**What you expected to happen**:

A node pool under the "user" mode should have the label `kubernetes.azure.com/mode=user`.

According to [this comment](https://github.com/Azure/AKS/issues/1309#issuecomment-617466555) it may be expected that only system node pools apply this label, but it would be helpful to identify "user" node pools by match labels for scenarios that require identifying node pools in the user-space without using node taints to simply avoid scheduling on system pools.

It also doesn't appear to be possible to apply this label manually to user pools as it seems to get nulled out during deployment without erroring, both with an ARM template and a manual node pool add on the CLI.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a basic AKS cluster with a default system pool.
2. Add a node pool with mode "user" (az aks nodepool add --name "usr1" --cluster-name {name} --resource-group {rg} --mode user)
3. Connect to the cluster and describe a node in the user pool.

**Comment by hieumoscow** [comment]
kubernetes.azure.com/mode=user is now one of the labels on user pool nodes. You can verify via `kubectl get nodes --show-labels`
