### ISSUE TITLE
[Feature] Azure Migrate for Windows AKS 

### ISSUE THREAD

**Issue by keikhara** [Azure/AKS#2123]
Azure Migrate is there for customers who wants to convert ASP.NET application onto Windows container, add to ACR, and then deploy to AKS. 
https://docs.microsoft.com/en-us/azure/migrate/tutorial-containerize-aspnet-kubernetes

**Comment by vrapolinario** [comment]
This service continues in Public Preview as we continue to make improvements to the tool and listen to customer feedback. We'll be moving to Generally Available later in this calendar year.

**Comment by palma21** [comment]
@justindavies @vrapolinario any updates?

**Comment by vrapolinario** [comment]
Azure Migrate App Containerization is now on Public Preview and it supports web applications: IIS/.Net Framework for Windows and Java on TomCat for Linux.
More details here: 
- IIS/Windows apps: https://docs.microsoft.com/en-us/azure/migrate/tutorial-app-containerization-aspnet-kubernetes
- Java/Linux apps: https://docs.microsoft.com/en-us/azure/migrate/tutorial-app-containerization-java-kubernetes

Please let us know if you have any feedback on the tool.
