### ISSUE TITLE
Cluster Autoscaler won't scale up if Load balancer is configured to use 64000 ports 

### ISSUE THREAD

**Issue by issacnitin** [Azure/AKS#2124]
**What happened**:
Cluster autoscaling for nodepool fails when Load Balancer is configured to use 64000 ports and 32 ips for a nodepool of 10 nodes and a system pool of 1 node

**What you expected to happen**:
Cluster should auto-scale

**How to reproduce it (as minimally and precisely as possible)**:
Added a node pool for autoscaling to 10 nodes
Added 32 ips with 64000 ports per backend instance using  --load-balancer-managed-outbound-ip-count and  --load-balancer-outbound-ports
Deployed more pods to trigger cluster scaleup

**Anything else we need to know?**:
I have more than enough ips to handle for autoscaled

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.14, 1.19.6
- Size of cluster (how many worker nodes are in the cluster?) 1 system node, 3 user nodes trying to scale up to 6 user nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Cluster for running load testing http servers
- Others:

**Comment by marwanad** [comment]
@issacnitin thanks for reporting. Can you describe one of the pending pods and see the reason for the scale-up failure?

**Comment by issacnitin** [comment]
@marwanad I just figured it's not issue with load balancer. Now when I try to add nodepool, it gives error "Invalid template, zone '' not in location eastus"

So i tried using availability zone(1) and even manual scaling is not happening

**Comment by marwanad** [comment]
@issacnitin so essentially you're unable to create nodepools/nodes in that region? If so, would you be able to open a SR ticket for that?

**Comment by issacnitin** [comment]
@marwanad I realized there's some data center that went down in US, so VMs were unavaliable
