### ISSUE TITLE
Required containers missing from OS image

### ISSUE THREAD

**Issue by justin-sobanski** [Azure/AKS#2126]
**What happened**: Building new private AKS clusters fails because at least one of the required system level containers isn't pre-loaded on the OS image. The zone where this is being built doesn't have access to the internet to pull down the image from mcr.microsoft.com. In particular, mcr.microsoft.com/oss/kubernetes/kube-proxy:v1.18.14 seems to be what is missing.

**What you expected to happen**: Cluster builds normally without access to mcr.microsoft.com

**How to reproduce it (as minimally and precisely as possible)**: Build a new private cluster with version 1.18.14 in a VNET with no internet access.

**Anything else we need to know?**: The same build process worked on version 1.18.14 worked as recently as January 25th. It also works on 1.17.16 which uses a different OS image.

**Environment**:
- Kubernetes version (use `kubectl version`):  1.18.14
- Size of cluster (how many worker nodes are in the cluster?) : 2 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by miwithro** [comment]
@justin-sobanski can you tell me what version of the VHD you are running?  According to the latest release notes it there.

https://github.com/Azure/AgentBaker/blob/master/vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2021.02.10.txt

Can you run  az aks upgrade \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --node-image-only

Then tell me if the problem still persists.

**Comment by justin-sobanski** [comment]
@miwithro I did a clean build of a cluster in the same zone and ran into the same error. The CLI reports the image version as AKSUbuntu-1804-2021.02.10.

I did run that command against a slightly older instance that also had this problem and I didn't see the cluster come fully online, it looks like it ran into the same problem.

**Comment by miwithro** [comment]
@xuto2 can you assist?

**Comment by xuto2** [comment]
ack.

**Comment by xuto2** [comment]
We fixed it. @justin-sobanski  Can you give it a try?

**Comment by justin-sobanski** [comment]
@xuto2 I tried again this morning and it looks like it's working great now. Thanks!
