### ISSUE TITLE
having issues with splunk connector after upgrading AKS version from 1.18 to 1.19 

### ISSUE THREAD

**Issue by gauravguliani** [Azure/AKS#2127]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by miwithro** [comment]
@gauravguliani 1.18 is running Docker under the hood.  1.19 is running containerd under the hood.  I cannot find any reference to Splunk working with containerd.  So they need to provide a connector that works with containerd.

**Comment by gauravguliani** [comment]
Okay i will check that.

**Comment by gauravguliani** [comment]
by changing log format to CRI it worked
