### ISSUE TITLE
The feature 'StartStopPreview' could not be found.

### ISSUE THREAD

**Issue by MCKLMT** [Azure/AKS#2130]
**What happened**:

I follow the documentation to stop an AKS cluster : https://docs.microsoft.com/en-us/azure/aks/start-stop-cluster
When I try to register the "StartStopPreviex" extension I received the error: ```The feature 'StartStopPreview' could not be found.```

**What you expected to happen**:

The extension should be registered successfully.

**How to reproduce it (as minimally and precisely as possible)**:

```
az extension add --name aks-preview
az feature register --namespace "Microsoft.ContainerService" --name "StartStopPreview"
```

**Anything else we need to know?**:

I'm currently on the following version:

```
[
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "aks-preview",
    "path": "/Users/mimott/.azure/cliextensions/aks-preview",
    "preview": true,
    "version": "0.5.0"
  }
]
```

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by davidbarrowsatasos** [comment]
I also have this problem after following the docs here:  https://docs.microsoft.com/en-us/azure/aks/start-stop-cluster

**Comment by joaguas** [comment]
Hi @MCKLMT and @davidbarrowsatasos ,

The start/stop feature is now [GA ](https://github.com/Azure/AKS/releases/tag/2021-02-08)
Using the feature no longer requires the cli aks-preview extension nor registering the preview feature (`az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService')]"` will no longer show this feature available, hence the error you're getting).

`jorge@Azure:~$ az aks show -g cenas -n teste --query powerState
{
  "code": "Running"
}
jorge@Azure:~$ az aks stop -g cenas -n teste
jorge@Azure:~$ az aks show -g cenas -n teste --query powerState
{
  "code": "Stopped"
}
jorge@Azure:~$`

Docs should soon be updated.

**Comment by capusta** [comment]
does the resource provider have to be updated as well ? (for custom role assignments)

```
Error: authorization.RoleDefinitionsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidActionOrNotAction" Message="'Microsoft.ContainerService/managedClusters/stop/action' does not match any of the actions supported by the providers."
```
