### ISSUE TITLE
LoadBalancer sometimes not resolving correct remote IP despite externalTrafficPolicy:Local

### ISSUE THREAD

**Issue by kelvinatph** [Azure/AKS#2131]
**What happened**: We have a Kubernetes Service object in front of our Pods that creates an Azure Load Balancer.  Our pods run an HTTPS service and we log the remote IP of each visitor.  The Service is configured with `externalTrafficPolicy: Local` and we noticed that almost all the time, the correct remote IP is logged; but occasionally, our HTTP service logs the public IP of the Load Balancer instead of the remote IP of the visitor.

**What you expected to happen**: Expected the remote IP of the visitor to be logged (i.e. the pods see packets that have the original source IP of the client over the internet, not the public IP of the load balancer) all the time.

**How to reproduce it (as minimally and precisely as possible)**: Not sure how to reproduce, but I imagine if someone set up a load balancer by creating a Service object in AKS and used it for an extended period of time, they would see this

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"41d24ec9c736cf0bdb0de3549d30c676e98eebaf", GitTreeState:"clean", BuildDate:"2021-01-18T09:12:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
- Size of cluster (how many worker nodes are in the cluster?): ~ 30-60 nodes (autoscaled)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): HTTP microservice
- Others: We are using kubelet networking (non-CNI)

**Comment by kelvinatph** [comment]
To add a bit of info on frequency, over the last 24 hours, we had 4,428,192 http requests; of those, the loadbalancer IP was logged 4966 times, so about 0.1% of the time.

**Comment by feiskyer** [comment]
@kelvinatph does the issue still happen for you? if so, could you open a support ticket for it?

**Comment by feiskyer** [comment]
let's close this issue since there're no updates for a long time. Please open a support ticket if you have the issue again.
