### ISSUE TITLE
Clarification on Ephemeral OS Disk encryption

### ISSUE THREAD

**Issue by magooster** [Azure/AKS#2136]
When creating a cluster with ephemeral disk I  see the following when looking at the OS disk

<img width="1349" alt="Screenshot 2021-02-23 at 10 10 22" src="https://user-images.githubusercontent.com/12111442/108832816-ee2e0d00-75c3-11eb-8005-77d43812ac4e.png">

As I understand from another issue the Storage type is reflecting the storage type of the disk image used to 'seed' the ephemeral disk

Now the disk shows encryption using SSE with PMK, is this actually correct? I thought encryption for local disks was only supported when encryption at host (Preview) was enabled.

**Comment by andyzhangx** [comment]
@ramankumarlive  it looks like Ephemeral OS Disk is already encrypted by SSE+PMK by default from azure portal now, not sure whether it's correct, could you confirm? thanks.
