### ISSUE TITLE
[Feature Request] AKS Managed Service Mesh

### ISSUE THREAD

**Issue by dhananjaya-senanayake** [Azure/AKS#2137]
**What happened**:

A Service Mesh can be used for following scenarios
- Monitoring
- tracing -
- circuit breakers 
- routing
- load balancing
- fault injection
- retries
- timeouts
- mirroring
- access control
- rate limiting, and more

In AKS a service mesh has to be installed and managed by the user.

- [https://docs.microsoft.com/en-us/azure/aks/servicemesh-about](https://docs.microsoft.com/en-us/azure/aks/servicemesh-about)
- [Install Istio in AKS](https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-about)
- [Install Linkerd in AKS](https://docs.microsoft.com/en-us/azure/aks/servicemesh-linkerd-about)
- [Install Consul in AKS](https://docs.microsoft.com/en-us/azure/aks/servicemesh-consul-about)

Existing implementations https://github.com/Azure/AKS/issues/1787

**What you expected to happen**:
AKS Managed Service Mesh as similar to EKS App Mesh(https://aws.amazon.com/blogs/containers/getting-started-with-app-mesh-and-eks/)

When AGIC + Azure Application Gateway + Service Mesh is used, the end users have no option to enforce mTLS for the traffic from the Application Gateway to the backend pods. Ref https://github.com/Azure/application-gateway-kubernetes-ingress/issues/805

Expect to have an AKS managed service mesh Add-on for Linkerd and Istio as well.

Similar Implementations https://github.com/Azure/AKS/issues/1787

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:

**Environment**: N/A
- Kubernetes version (use `kubectl version`): N/A
- Size of cluster (how many worker nodes are in the cluster?) N/A
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) N/A
- Others: N/A

**Comment by tomkerkhove** [comment]
There's an OSM add-on coming, would that help? https://github.com/Azure/AKS/issues/1787

**Comment by dhananjaya-senanayake** [comment]
> There's an OSM add-on coming, would that help? #1787

Any timeline for going on GA and available as a AKS managed add on ?

It is not in GA it seems https://servicemesh.es/

**Comment by miwithro** [comment]
This just went public preview in AKS.

https://docs.microsoft.com/en-us/azure/aks/servicemesh-osm-about?pivots=client-operating-system-linux#tutorial-deploy-an-application-managed-by-open-service-mesh-osm-using-azure-application-gateway-ingress-aks-add-on
