### ISSUE TITLE
How do upgradeChannel and kubernetesVersion interact in an ARM template?

### ISSUE THREAD

**Issue by wsugarman** [Azure/AKS#2138]
I apologize if this has been answered elsewhere. I couldn't find it in the issues page, [Azure Docs](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/aks/upgrade-cluster.md#set-auto-upgrade-channel), or [ARM template documentation](https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters). I

I see that `upgradeChannel` has been added to the ARM template recently in preview, and I was wondering how it interacts with the specified `kubernetesVersion`. More specifically, I have a few questions:

1. What is the default value of `kubernetesVersion` if it is left unspecified?
2. If `upgradeChannel` is specified, does it impact the `kubernetesVersion` that is deployed (either specified or left with the default value)?
    - Eg. Assuming kubernetes 1.19.7 is available and both `"kubernetesVersion": "1.19.6"` and `"upgradeChannel": "patch"` are specified in my template, then what happens? Is `1.19.7` deployed instead? Or is `1.19.6` deployed and then upgraded?
    - Related to (1), but is the behavior any different if the `kubernetesVersion` is not specified in an ARM template?
3. Is there a location where the complete list of supported versions of Kubernetes on AKS are maintained?

**Comment by maartengo** [comment]
Not sure if it answers your question, but about point 3; there are a few API's available to get a list of available upgrades:
https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/getupgradeprofile
https://docs.microsoft.com/en-us/rest/api/aks/agentpools/getupgradeprofile
https://docs.microsoft.com/en-us/rest/api/aks/agentpools/getavailableagentpoolversions

**Comment by xhl873** [comment]
Hi @wsugarman, upgradeChannel is added recently and it's for out new feature auto-upgrade, which is in preview now. The upgrade channel won't influence k8sversion when you create the cluster, if k8sversion left unspecified, it will use the default version of that region. For 2, it will create the cluster 1.19.6, and because you enabled auto-upgrade by setting it to patch channel, later on, it will be upgraded to 1.19.7. Here is the link for different channels: https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel

**Comment by paulgmiller** [comment]
Keep in mind later on might be very soon after or many hours later. There is no guarantee on that.

**Comment by wsugarman** [comment]
Thanks @xhl873!

I think my team will want some interaction between these two fields before we take a dependency on it in production. For example, say we have an ARM template using the above values:

```
{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json",
    "contentVersion": "1.0.0.0",
    ...
    "resources": [
        {
            "type": "Microsoft.ContainerService/managedClusters",
            "properties": {
                "kubernetesVersion": "1.19.6",
                "autoUpgradeProfile": {
                    "upgradeChannel": "patch"
                }
                ...
            }
        }
        ...
    ]
}
```

After this version has been deployed, at some point the cluster will be automatically upgraded to 1.19.7. So if our team wants to make changes to this ARM template, we would need to make sure that we also update the `"kubernetesVersion"` before deploying unrelated changes. That is because if we kept the version the same, the declared version 1.19.6 would be different from the deployed version 1.19.7, and declaring a downgrade will cause an issue as per our offline discussion.

So my ask would be that the `"autoUpgradeProfile"` be considered when determining the `"kubernetesVersion"` that is ultimately deployed. Today, `"autoUpgradeProfile"` [defines a set of Kubernetes versions to which your AKS cluster may be upgraded](https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel). Let `x` be the `"kubernetesVersion"` declared in the ARM template and `y` be the latest version to which an AKS cluster could be upgraded based on the `"upgradeChannel"`. I think their interaction could be extended such either:
1. The latest version `y` is always deployed, as opposed to waiting for an auto-upgrade in existing clusters
    - Eg. For the above ARM template, assuming 1.19.8 is the latest patch for 1.19.*, then 1.19.8 would be deployed
2. The declared version `x` is deployed, unless the existing version is within [`x`, `y`]. In that case, the version is left unchanged.  The auto-upgrader is always relied upon for reaching version `y`
    - Eg. For the above ARM template, assuming 1.19.8 is the latest patch for 1.19.*, no new Kubernetes version would be deployed to an existing cluster if the currently running version is between `1.19.6` and `1.19.8`. Instead, the auto-upgrader will eventually upgrade to `1.19.8` if necessary

Does that some reasonable?

**Comment by paulgmiller** [comment]
This is a great point thanks for bringing it up. I think my prefernce would be #2 but I'll be discussing it with Xiahe and Charlie this week.

**Comment by xhl873** [comment]
I've made the change to allow lower Kubernetes version in input, the changing is rolling out now. It will allow input has lower k8s versions than the current version, in this case, the lower input version will be ignored, after that, you should be able to don't need to upgrade version in ARM template if the version is already upgraded by autoupgrade. If the current version is not target version, autoupgrade will be responsible to drive it to the target version.

**Comment by wsugarman** [comment]
That's great news! Thank you for implementing this so quickly. When will this feature be live in all DCs?

**Comment by palma21** [comment]
Also please refer to this one as something that is likely to help you in the future on ARM templates.
https://github.com/Azure/AKS/issues/1737

This is on the release notes and should be everywhere by end of next week the latest.

**Comment by wsugarman** [comment]
Oh, that'd be great too! Thank you both!
