### ISSUE TITLE
Nodes should use less privileged service principal inside /etc/kubernetes/azure.json

### ISSUE THREAD

**Issue by mblaschke** [Azure/AKS#2142]
**What happened**:
The AKS ServicePrinicpal is used in every node VM inside `/etc/kubernetes/azure.json`. This ServicePrinicpal has at least Contributor permissions on the node ResourceGroup.

If an attacker can breach the container and can access this file on one node he could:
- delete VMs, VMSS, ManagedDisks, LoadBalancers, ...
- manipulate VMSS and the VMS
- access other VMs as this ServicePrinicpal has full permissions to install malicious software

**What you expected to happen**:

Use a less privileged ServicePrinicpal with only read Permissions for Kubelet on the node ResourceGroup and the ACRs.
Add this options into ARM.

Use the AKS service principal only for controller-manager, cloud-provider and autoscaler (and maybe others).

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.7
- Size of cluster (how many worker nodes are in the cluster?) 3

**Comment by miwithro** [comment]
Is there a reason you are using SP's.  It is recommended to upgrade to MSI which would negate this issue all together.

https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#update-an-aks-cluster-to-managed-identities
