### ISSUE TITLE
FailedToUpdateEndpointSlices aks 1.19.7

### ISSUE THREAD

**Issue by doronmak** [Azure/AKS#2144]
Hello, we upgrade from 1.16.5 to 1.19.7 and we got some Warning about the Endpoint Slices.

the error is:
`  
  Warning  FailedToUpdateEndpointSlices  49m (x12 over 4d3h)  endpoint-slice-controller  Error updating Endpoint Slices for Service default/**service name**: failed to update **endpoint name** EndpointSlice for Service **default/service name** Operation cannot be fulfilled on endpointslices.discovery.k8s.io "**endpoint name**: the object has been modified; please apply your changes to the latest version and try again
`
there's a fix?  need to edit the endpoint yamls?
thanks a lot.

**Comment by cforce** [comment]
same/similar issue chart  ingress-nginx-3.24.0 0.44.0 on AKS 1.19.8 https://github.com/kubernetes/ingress-nginx/issues/6972

**Comment by miwithro** [comment]
There is a Kubernetes Issues on this one:

https://github.com/kubernetes/kubernetes/issues/91072

According to that thread.  "I think the best option is what I proposed above (delete slices managed by controller during these transitions) for the EndpointSlice and EndpointSliceMirroring controllers."

**Comment by cforce** [comment]
It seems to happen during nginx autoscale. I don't know how i can can improve here without even changing the original nginx helm chart. So is that a kubernetes/aks or  ngnix  problem?

**Comment by miwithro** [comment]
@cforce I don't know of another way other than changing the original nginx helm?

**Comment by palma21** [comment]
Do you have repro of this, is this still happening?
