### ISSUE TITLE
Provide a way to modify the Audit Policy used by the kube-apiserver in AKS

### ISSUE THREAD

**Issue by carlsoncoder** [Azure/AKS#2145]
**What happened**:
I would like to know if there is a way (and if not, can we add a feature request) to make the Kubernetes audit policy used by managed AKS configurable.

Right now, I don't see any way to configure this.  I found [Issue #1873](https://github.com/Azure/AKS/issues/1873), where user @miwithro noted the following:

*********
Hello,
There is already an audit policy applied to the AKS clusters. There is no need to add one. You simply just need to query the logs.

https://docs.microsoft.com/en-us/azure/aks/view-master-logs

Here is the applied audit policy:
https://github.com/Azure/aks-engine/blob/24244adcd09afcf452c2e16317999046a240e992/parts/k8s/addons/audit-policy.yaml

*********

Based on that policy, it looks like it would use "Request" as the policy for secrets.  Which according to the [docs](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/) it would:

"Request - log event metadata and request body but not response body. This does not apply for non-resource requests."

However, I setup audit log streaming, made a secret, and viewed the log...I did NOT see the request body which would contain my base64 encoded string of the secret, which leads me to believe maybe AKS has updated it's default audit policy?

**What you expected to happen**:

I really just want to see what the full k8s Audit Policy that AKS is using looks like, so I can ensure that Secret objects are NOT being audited with a Request or RequestResponse policy.  Being able to provide my own audit policy at AKS creation time would also be great, but that's definitely secondary to ensure that the secret data is not being stored in audits.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
Kubernetes version - 1.19.7

**Comment by denniszielke** [comment]
It would also be great if we can provide an optional filter that allows to not receive all audit events which are generated by default system service accounts. Most of the time customers are only interested in activities from custom service accounts or actual users (authenticated by aad).
