### ISSUE TITLE
couldn't find key named key1 in storage account

### ISSUE THREAD

**Issue by coderplay** [Azure/AKS#2147]
**What happened**:

I created a `shared-premium` StorageClass with below configuration in a AKS cluster. The only difference between this StorageClass and AKS's built-in `managed-premium` is that mine kind is `Shared`.

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: shared-premium
parameters:
  cachingmode: ReadOnly
  kind: Shared
  storageaccounttype: Premium_LRS
provisioner: kubernetes.io/azure-disk
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

When I create a PVC of above StorageClass, I got errors  like this

```
  Type     Reason                Age               From                         Message
  ----     ------                ----              ----                         -------
  Warning  ProvisioningFailed    12s               persistentvolume-controller  Failed to provision volume with StorageClass "shared-premium": couldn't find key named key1 in storage account:ds9425e7534c7848a1939d0 keys
  Warning  ProvisioningFailed    11s               persistentvolume-controller  Failed to provision volume with StorageClass "shared-premium": couldn't find key named key1 in storage account:dsd62073f448b4442f86084 keys
  Normal   WaitForFirstConsumer  1s (x6 over 30s)  persistentvolume-controller  waiting for first consumer to be created before binding
  Warning  ProvisioningFailed    1s (x2 over 7s)   persistentvolume-controller  Failed to provision volume with StorageClass "shared-premium": couldn't find key named key1 in storage account:dsf27e71fd95d040dcb5ab5 keys
```

From below `az storage account keys list` instruction, I can get a key named `key1` in storage account `ds9425e7534c7848a1939d0`. (I replaced the actual value with XX..)
```
% az storage account keys list -n ds9425e7534c7848a1939d0

[
  {
    "keyName": "key1",
    "permissions": "FULL",
    "value": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  },
  {
    "keyName": "key2",
    "permissions": "FULL",
    "value": "value": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  }
]
```

The [corresponding code](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_blobDiskController.go#L307) shows that it checks the `value` of the key rather than key name.

```go
func (c *BlobDiskController) getStorageAccountKey(SAName string) (string, error) {
...

		if v.Value != nil && *v.Value == "key1" {
...
			c.accounts[SAName].key = *v.Value
			return c.accounts[SAName].key, nil
		}
...

	return "", fmt.Errorf("couldn't find key named key1 in storage account:%s keys", SAName)
}
```
Is it a bug? 

**Anything else we need to know?**:

The issue didn't happen when I changed StorageClass's configuration to `kind: Managed`. If above issue is due to a bug, why it didn't happen to managed disk?

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.18.14
- Size of cluster (how many worker nodes are in the cluster?) 3

**Comment by andyzhangx** [comment]
Hi @coderplay `shared` kind is not supported any more since it can only create blob disk, while aks node is using managed os disk, it cannot attach blob disk.

**Comment by andyzhangx** [comment]
close this issue now since `shared` is not supported on aks.
