### ISSUE TITLE
AKS 1.17.13 UDP load balancing 

### ISSUE THREAD

**Issue by yevhen-kuras** [Azure/AKS#2149]
**What happened**: We are using load balancer service for UDP communication. Also we need stateful UDP datagrams distribution on the backend. So we are using Client IP persistence to achieve this goal. Previously on AKS 1.16.15 UDP packages was sent to the same pod w/o issues. Also we utilized **tcp-idle-timeout** configuration to keep stateful UDP flow for 4 minutes. So we gracefully relied on this timeout to ensure that established UDP flow will exists at least 4 minutes 

After update to Kubernetes 1.17.13 we discovered that UDP flows are not available after 2 minutes(maybe less) if there were no UDP packages.     

I want to know if there are any configuration option on AKS or Azure load balancer to make already established UDP flows available during some desired timeout in the same way as it is possible for TCP using **tcp-idle-timeout**. Please let me know current default UDP flows idle timeout.  Also I will appreciate links to documentation about UDP load balancing in AKS.

**Environment**:
- Kubernetes version: 1.17.13

**Comment by yevhen-kuras** [comment]
After additional investigation I found that UDP flows are dropped after ~35 seconds. Therefore UDP packages are not received on appropriate pod of deployment behind load balancer service.

**Comment by miwithro** [comment]
@paulmiller

**Comment by feiskyer** [comment]
Close since there're no updates for a long time. Feel free to open a support ticket if you have met the issue again.
