### ISSUE TITLE
Upgrading control plane causes api server to be unavailable 

### ISSUE THREAD

**Issue by arsnyder16** [Azure/AKS#2150]
**What happened**:
I have a web service that is running within AKS.
I recently upgraded a cluster from 1.17-1.18 using 
`az aks upgrade --kubernetes-version 1.18.14 --control-plane-only --yes --name {}`

During the upgrade to the api server become unavaialbe for ~5 minutes. My cluster is configured to have uptime sla. 

During this down time my ingress(nginx) and some custom controllers within the cluster are unable to operate properly causing some downtime since they cannot List/Watch resources. 

`E0226 15:22:43.880879 6 reflector.go:123] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:157: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout`
`E0226 15:22:40.609921 7 reflector.go:123] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:156: Failed to list *v1.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout`

**What you expected to happen**:
The api server remains available during an upgrade.

**How to reproduce it (as minimally and precisely as possible)**:
Setup an nginx ingress and upgrade a cluster it will be unable to route to the backends once the api server is down for a period of time

**Anything else we need to know?**:
It would be nice to have more information on how the api server is deployed on the aks side. Is it a single replica deployment? Based on the behavior that is what it seems

**Environment**:
- Kubernetes version (use `kubectl version`): was upgrading from 1.17-1.18 
- Size of cluster (how many worker nodes are in the cluster?) 2 node pools, 2 nodes per pool
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by davefellows** [comment]
Thanks for raising this @arsnyder16, we're looking into what might have caused this. 

> Is it a single replica deployment?
No, uptime SLA clusters have multiple replicas.

Do you mind sharing your cluster details so we can investigate further?

Thanks!

**Comment by arsnyder16** [comment]
closing this was addressed after opening a Microsoft support ticket there  was a bug on the control plane side
