### ISSUE TITLE
South Africa North​ Zone Support

### ISSUE THREAD

**Issue by keikhara** [Azure/AKS#2151]
Waiting for external facing whitelisting from Azure Global before publishing to docs.

**Comment by sebader** [comment]
any update on this now that AZs went GA in SA North? https://azure.microsoft.com/en-us/updates/south-africa-north-availability-zones-now-generally-available/

**Comment by aritraghosh** [comment]
AKS is now [available](https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/?products=kubernetes-service&regions=us-east,us-east-2,us-central,us-north-central,us-south-central,us-west-central,us-west,us-west-2,us-west-3,south-africa-north,south-africa-west) in SA North
