### ISSUE TITLE
Start-Stop of a 1.17 Cluster enabled CSI drivers

### ISSUE THREAD

**Issue by magooster** [Azure/AKS#2152]
**What happened**:

Started a stopped AKS cluster and see a set of CSI storage driver related pods

kubectl -n kube-system get pods | grep csi
csi-azuredisk-node-hv2gv                3/3     Running   0          32m
csi-azuredisk-node-l2jfd                3/3     Running   0          34m
csi-azuredisk-node-sqlrd                3/3     Running   0          34m
csi-azurefile-node-h5jmg                3/3     Running   0          32m
csi-azurefile-node-hrfbw                3/3     Running   0          34m
csi-azurefile-node-p27xz                3/3     Running   0          34m

**What you expected to happen**:

Cluster is started with state as per when stopped

**How to reproduce it (as minimally and precisely as possible)**:

Stop an existing cluster running AKS version 1.17.16 then restart.

**Anything else we need to know?**:

**Environment**:
- 1.17.16
- Feature Testing minimal workloads

I thought CSI drivers could only be added via a preview extension and at cluster creation time? I have not enabled the ContainerService for this extension.

az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/EnableAzureDiskFileCSIDriver')].{Name:name,State:properties.state}"
Name                                                     State
-------------------------------------------------------  -------------
Microsoft.ContainerService/EnableAzureDiskFileCSIDriver  NotRegistered

**Comment by magooster** [comment]
Just tried creating a new cluster (1.18) i'm seeing the same... 

kubectl -n kube-system get pods | grep csi                                                                                                        
csi-azuredisk-node-4dthc              3/3     Running   0          4h14m
csi-azuredisk-node-dv2tk              3/3     Running   0          4h14m
csi-azuredisk-node-r58wt              3/3     Running   0          4h14m
csi-azurefile-node-7r9vj              3/3     Running   0          4h14m
csi-azurefile-node-9nct2              3/3     Running   0          4h14m
csi-azurefile-node-jf9nm              3/3     Running   0          4h14m

az version
{
  "azure-cli": "2.15.1",
  "azure-cli-core": "2.15.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.0"
  }
}

**Comment by GerryWilko** [comment]
I am experiencing exactly the same issue. CSI has been enabled on my cluster with a simple stop and start command.

This has crippled my cluster with these CSI pods eating all my max node count and resources.

**Comment by krs-gofore** [comment]
We don't have CSI registered either and we just upgraded some of our clusters from 1.19.3 to 1.19.6 and suddenly there are CSI pods running.

**Comment by alert101-gof** [comment]
We don't have CSI registered either and we just upgraded some of our clusters from 1.19.3 to 1.19.6 and suddenly there are CSI pods running.

**Comment by GerryWilko** [comment]
I had to ask support to manually disable CSI on my cluster. Seems to be an ongoing issue.

**Comment by l-rossetti** [comment]
Same behavior here. Moreover the resource allocation is HUGE and is blocking new pods deployment: 
Namespace                   Name                                              CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE                                                                                                                                                     
---------                         ----                                                       ------------  ----------  ---------------  -------------  ---                                                                                                                                         
kube-system                 azure-cni-networkmonitor-rndrh               0 (0%)        0 (0%)      0 (0%)           0 (0%)         55d                                                                                                                                                     
kube-system                 azure-ip-masq-agent-w6749              100m (1%)     500m (6%)   50Mi (0%)        250Mi (0%)     55d
kube-system                 csi-azuredisk-node-rcfk4                       30m (0%)      **6 (76%)**     60Mi (0%)        **6Gi (22%)**      **6d22h** 
kube-system                 csi-azurefile-node-mhlqt                       30m (0%)      **4 (51%)**     60Mi (0%)        **4Gi (14%)**      **6d22h**

**Comment by GerryWilko** [comment]
The resource limits are enormous for these pods I really don't understand how anyone could support running these within their cluster without a huge compute expense.

MSFT are currently planning on these being enabled by default for 1.21 if that is to be the case AKS will become a much less attractive proposition.

Perhaps the team could explain the benefits of this CSI system? The documentation just seems to say "enabling the next generation of storage"...

**Comment by ripa1993** [comment]
I think those CSI pods have messed up resource limits and reservations configured.
As a comparison, here https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/csi-azuredisk-node.yaml the default limits are `cpu: 200m`  `memory: 200 Mi`

**Comment by mmisztal1980** [comment]
We are experiencing a similar issue. We are running a v.recently provisioned cluster v 1.17.16 
We've had support remove the CSI pods for us, which worked fine and the limits went back to normal, however:

- our scheduled azure build agent cleanup failed to recreate the pods & volumes, upon examination we've found that a persistent volume binding was in `Pending` state.

```bash
k -n azure-devops get pvc
NAME                                      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
workspace-azure-pipelines-build-agent-0   Pending                                      default        118m
```

Upon closer examination it appears to have been using CSI

```bash
k -n azure-devops describe pvc workspace-azure-pipelines-build-agent-0
Name:          workspace-azure-pipelines-build-agent-0
Namespace:     azure-devops
StorageClass:  default
Status:        Pending
Volume:
Labels:        app=azure-pipelines-build-agent
Annotations:   volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
               volume.kubernetes.io/selected-node: aks-main-19751617-vmss000002
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type    Reason                Age                     From                         Message
  ----    ------                ----                    ----                         -------
  Normal  ExternalProvisioning  3m43s (x464 over 118m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "disk.csi.azure.com" or manually created by system administrator
```

Our agents are supposed to use the `default` storage class, so upon further examination:

```bash
k get sc
NAME                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile                kubernetes.io/azure-file   Delete          Immediate              true                   4d5h
azurefile-csi            file.csi.azure.com         Delete          Immediate              true                   4d5h
azurefile-csi-premium    file.csi.azure.com         Delete          Immediate              true                   4d5h
azurefile-premium        kubernetes.io/azure-file   Delete          Immediate              true                   4d5h
default (default)        disk.csi.azure.com         Delete          WaitForFirstConsumer   true                   4d5h
managed                  kubernetes.io/azure-disk   Delete          WaitForFirstConsumer   true                   4d5h
managed-csi              disk.csi.azure.com         Delete          WaitForFirstConsumer   true                   2d3h
managed-csi-premium      disk.csi.azure.com         Delete          WaitForFirstConsumer   true                   4d5h
managed-premium          kubernetes.io/azure-disk   Delete          WaitForFirstConsumer   true                   4d5h
managed-premium-retain   kubernetes.io/azure-disk   Delete          Immediate              false                  2d5h
```

Additionally I've executed the following and found:

```bash
k get nodes --show-labels=true
NAME                           STATUS   ROLES   AGE    VERSION    LABELS
aks-main-19751617-vmss000000   Ready    agent   4d4h   v1.17.16   agentpool=main,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS3_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westeurope,failure-domain.beta.kubernetes.io/zone=westeurope-1,kubernetes.azure.com/cluster=vabank-k8s-euw-01-cluster-nodes-xyz,kubernetes.azure.com/mode=system,kubernetes.azure.com/node-image-version=AKSUbuntu-1604-2021.02.17,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-main-19751617-vmss000000,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,node.kubernetes.io/instance-type=Standard_DS3_v2,topology.disk.csi.azure.com/zone=westeurope-1,topology.kubernetes.io/region=westeurope,topology.kubernetes.io/zone=westeurope-1
aks-main-19751617-vmss000001   Ready    agent   4d4h   v1.17.16   agentpool=main,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS3_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westeurope,failure-domain.beta.kubernetes.io/zone=westeurope-2,kubernetes.azure.com/cluster=vabank-k8s-euw-01-cluster-nodes-xyz,kubernetes.azure.com/mode=system,kubernetes.azure.com/node-image-version=AKSUbuntu-1604-2021.02.17,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-main-19751617-vmss000001,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,node.kubernetes.io/instance-type=Standard_DS3_v2,topology.disk.csi.azure.com/zone=westeurope-2,topology.kubernetes.io/region=westeurope,topology.kubernetes.io/zone=westeurope-2
aks-main-19751617-vmss000002   Ready    agent   4d4h   v1.17.16   agentpool=main,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS3_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westeurope,failure-domain.beta.kubernetes.io/zone=westeurope-3,kubernetes.azure.com/cluster=vabank-k8s-euw-01-cluster-nodes-xyz,kubernetes.azure.com/mode=system,kubernetes.azure.com/node-image-version=AKSUbuntu-1604-2021.02.17,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-main-19751617-vmss000002,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,node.kubernetes.io/instance-type=Standard_DS3_v2,topology.disk.csi.azure.com/zone=westeurope-3,topology.kubernetes.io/region=westeurope,topology.kubernetes.io/zone=westeurope-3
aks-main-19751617-vmss000003   Ready    agent   4d4h   v1.17.16   agentpool=main,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS3_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westeurope,failure-domain.beta.kubernetes.io/zone=westeurope-1,kubernetes.azure.com/cluster=vabank-k8s-euw-01-cluster-nodes-xyz,kubernetes.azure.com/mode=system,kubernetes.azure.com/node-image-version=AKSUbuntu-1604-2021.02.17,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-main-19751617-vmss000003,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,node.kubernetes.io/instance-type=Standard_DS3_v2,topology.disk.csi.azure.com/zone=westeurope-1,topology.kubernetes.io/region=westeurope,topology.kubernetes.io/zone=westeurope-1
aks-main-19751617-vmss000004   Ready    agent   4d4h   v1.17.16   agentpool=main,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS3_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westeurope,failure-domain.beta.kubernetes.io/zone=westeurope-2,kubernetes.azure.com/cluster=vabank-k8s-euw-01-cluster-nodes-xyz,kubernetes.azure.com/mode=system,kubernetes.azure.com/node-image-version=AKSUbuntu-1604-2021.02.17,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-main-19751617-vmss000004,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,node.kubernetes.io/instance-type=Standard_DS3_v2,topology.disk.csi.azure.com/zone=westeurope-2,topology.kubernetes.io/region=westeurope,topology.kubernetes.io/zone=westeurope-2
aks-main-19751617-vmss000005   Ready    agent   47h    v1.17.16   agentpool=main,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS3_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westeurope,failure-domain.beta.kubernetes.io/zone=westeurope-3,kubernetes.azure.com/cluster=vabank-k8s-euw-01-cluster-nodes-xyz,kubernetes.azure.com/mode=system,kubernetes.azure.com/node-image-version=AKSUbuntu-1604-2021.02.17,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-main-19751617-vmss000005,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,node.kubernetes.io/instance-type=Standard_DS3_v2,topology.disk.csi.azure.com/zone=westeurope-3,topology.kubernetes.io/region=westeurope,topology.kubernetes.io/zone=westeurope-3
aks-main-19751617-vmss000007   Ready    agent   47h    v1.17.16   agentpool=main,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS3_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=westeurope,failure-domain.beta.kubernetes.io/zone=westeurope-2,kubernetes.azure.com/cluster=vabank-k8s-euw-01-cluster-nodes-xyz,kubernetes.azure.com/mode=system,kubernetes.azure.com/node-image-version=AKSUbuntu-1604-2021.02.17,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-main-19751617-vmss000007,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,node.kubernetes.io/instance-type=Standard_DS3_v2,topology.disk.csi.azure.com/zone=westeurope-2,topology.kubernetes.io/region=westeurope,topology.kubernetes.io/zone=westeurope-2
```

Conclusion: The problem runs deeper and clearing the pods up is not the end of it.
Can you guys run similar checks on your clusters?

**Comment by andyzhangx** [comment]
@mmisztal1980 pls run `kubectl delete sc default` and after a few mins, new `default` storage class with `kubernetes.io/azure-disk` provisioner will be created.

**Comment by mmisztal1980** [comment]
@andyzhangx trying it now

**Comment by mmisztal1980** [comment]
@andyzhangx an educated guess it to do the same with the remaining csi storage classes?

**Comment by andyzhangx** [comment]
> @andyzhangx an educated guess it to do the same with the remaining csi storage classes?

just delete those csi storage classes since they are useless

**Comment by mmisztal1980** [comment]
Leaving this for posterity

```bash
k get sc | grep csi | awk '{ system("kubectl delete sc " $1) }'
storageclass.storage.k8s.io "azurefile-csi" deleted
storageclass.storage.k8s.io "azurefile-csi-premium" deleted
storageclass.storage.k8s.io "managed-csi" deleted
storageclass.storage.k8s.io "managed-csi-premium" deleted
```

**Comment by mmisztal1980** [comment]
@andyzhangx I can confirm that the `default` storage class appears to be using the correct provisioner now

```bash
k get sc
NAME                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile                kubernetes.io/azure-file   Delete          Immediate              true                   7d4h
azurefile-premium        kubernetes.io/azure-file   Delete          Immediate              true                   7d4h
default (default)        kubernetes.io/azure-disk   Delete          WaitForFirstConsumer   true                   7d4h
managed                  kubernetes.io/azure-disk   Delete          WaitForFirstConsumer   true                   6d1h
managed-premium          kubernetes.io/azure-disk   Delete          WaitForFirstConsumer   true                   7d4h
managed-premium-retain   kubernetes.io/azure-disk   Delete          Immediate              false                  6d22h
```

**Comment by alert101-gof** [comment]
Would be nice to get an explanation how and why this happened, especially as many didn't have the preview feature registered? Fortunately we only upgraded two development clusters and these were using VMSS. But if we had happened to upgrade a production cluster (which are still using Availability Sets) this could have caused serious issues.

**Comment by nilo19** [comment]
@alert101-gof this is due to a bug we introduced recently. We have hotfixed the bug.
