### ISSUE TITLE
Throttling request took

### ISSUE THREAD

**Issue by SkinyMonkey** [Azure/AKS#2155]
**What happened**:

I programmed a custom controller that sometimes receives the following error when talking with the kube server API endpoints:
"Throttling request took ", followed by a time that can take up to a minute!

Of what i understand the kube server API has a request-per-second limit or it could be Azure that is throttling the number of request.
I can throttle the number of requests made per second to the kube server API but i'd like to know what is this limit' value.

**What you expected to happen**:
No error message

**How to reproduce it (as minimally and precisely as possible)**:

Do approximately 100 request per second and you should see it appear

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.3
- Size of cluster: 3 nodes
- General description of workloads in the cluster: small controller

Thank you for your help!

**Comment by andyzhangx** [comment]
the code is in [client-go](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/b03365535aad360e68346ed9fd12c3dad87f39d6/vendor/k8s.io/client-go/rest/request.go#L590-L597), it would log when api call costs > 50ms
```
        // longThrottleLatency defines threshold for logging requests. All requests being
        // throttled (via the provided rateLimiter) for more than longThrottleLatency will
        // be logged.
        longThrottleLatency = 50 * time.Millisecond
	// extraLongThrottleLatency defines the threshold for logging requests at log level 2.
	extraLongThrottleLatency = 1 * time.Second
        ...
        if latency > longThrottleLatency {
                klog.V(3).Infof("Throttling request took %v, request: %s:%s", latency, r.verb, r.URL().String())
        }
	if latency > extraLongThrottleLatency {
		// If the rate limiter latency is very high, the log message should be printed at a higher log level,
		// but we use a throttled logger to prevent spamming.
		globalThrottledLogger.Infof("Throttling request took %v, request: %s:%s", latency, r.verb, r.URL().String())
	}
```

**Comment by SkinyMonkey** [comment]
While I understand that the client is logging this I fail to understand why the calls to the kubernetes API cost > 50ms.
And mostly, why some requests can take as much as 1 min to resolve.

My guess is that the raate limiter is stacking the requests but i don't get why even then it's too much for the server to handle.
At most, of my understanding, we get maybe 300 requests per second. Which does not seem like much?

**Comment by seguler** [comment]
AKS clusters are defaulted to the free tier and come with limited resources. For free clusters, the current limits for an API server is 50 mutating and 100 non-mutating in-flight requests. We are constantly improving our service and we expect to increase these sometime later this year. 

If you have a need for higher number of in-flight requests, please opt-in for the Uptime SLA / paid tier. Clusters on Uptime SLA have multiple replicas for the API server and come with a total of 600 mutating and 1200 non-mutating in-flight request limits.

W.r.t. to requests taking up to 1-min - what kind of requests are they? How many objects do you have? You may see higher latency depending on what you request and how many objects you have.

**Comment by SkinyMonkey** [comment]
Thank you @seguler That makes sense, I'll check with our op team what's the tier status of the clusters.

The requests are mostly reading requests.
We retrieve an pod in a controller, if it exists we use it, if it doesn't we create it before using it.

I think it can reach as much a 300 concurrent requests at some point and might go further later.
We're can try to mitigate this with a queue.
Are the 50 and 100 limits a per minute limit?
