### ISSUE TITLE
az aks create -with --attach-acr is creating Managed Identity by default 

### ISSUE THREAD

**Issue by fab2903** [Azure/AKS#2157]
**What happened**:  az aks create with --attach-acr is creating Managed Identity by default but it doesn't work properly until you manually add the ArcPull role on the ACR and on the Managed identity itself. (Even as an owner of the subscription).
As a second issue, az aks update to --attach-acr doesn't work either, even as an owner. 

**What you expected to happen**: I expected that if I'm the owner of the subscription that by just adding --attach-acr the cluster would be able to pull images without needing to do some manual interactions. 

**How to reproduce it (as minimally and precisely as possible)**:  
az aks create -n $AKS_NAME -g $RESOURCE_GROUP --generate-ssh-keys --attach-acr $REGISTRY
az aks update -n $AKS_NAME -g $RESOURCE_GROUP --attach-acr $REGISTRY

Both return the output:
Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for ACR. Are 
you an Owner on this subscription?

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others: I'm the owner of the sub and other services like ACI or App Service can pull from the ACR without any issues.

**Comment by feiskyer** [comment]
the issue should have already been fixed.
