### ISSUE TITLE
Add support for custom NTP servers

### ISSUE THREAD

**Issue by EppO** [Azure/AKS#2159]
Currently, AKS uses ntp.ubuntu.com as NTP servers. There are other use cases where using custom NTP servers would make sense:

- When using private AKS clusters, able to use internal NTP servers 
- Use NIST NTP servers or pool.ntp.org

**Comment by gitflo1** [comment]
Hi @EppO .
Currently the private AKS nodes use the official NTP pool servers.
* AKS Kubernetes version 1.18.14
* AKS node SKU: aks-ubuntu-1804-gen2-2021-q1  
* AKS node version: 2021.01.28  

This is from my private AKS node's /etc/ntp.conf file:

```
# Use servers from the NTP Pool Project. Approved by Ubuntu Technical Board
# on 2011-02-08 (LP: #104525). See http://www.pool.ntp.org/join.html for
# more information.
pool 0.ubuntu.pool.ntp.org iburst
pool 1.ubuntu.pool.ntp.org iburst
pool 2.ubuntu.pool.ntp.org iburst
pool 3.ubuntu.pool.ntp.org iburst

# Use Ubuntu's ntp server as a fallback.
pool ntp.ubuntu.com
```

A support for custom NTP server configuration would still be nice 👌

**Comment by palma21** [comment]
we're moving towards Host based clock sync for all our cases. 
Unfortunately it's tricky to support custom NTP servers at it would be a uncontrollable element to our managed nodes, but we hope the above would meet your needs! Let us know otherwise!

**Comment by Klaas-** [comment]
> we're moving towards Host based clock sync for all our cases.
> Unfortunately it's tricky to support custom NTP servers at it would be a uncontrollable element to our managed nodes, but we hope the above would meet your needs! Let us know otherwise!

is there a timeline for that change? We really would like to get rid of ntp :)

**Comment by xuto2** [comment]
@Klaas-  It's already released. Create a new agent pool or cluster, or do a node image upgrade or k8s version upgrade, you will get the change.

**Comment by EppO** [comment]
> we're moving towards Host based clock sync for all our cases.
> Unfortunately it's tricky to support custom NTP servers at it would be a uncontrollable element to our managed nodes, but we hope the above would meet your needs! Let us know otherwise!

My main use case is to get rid of the firewall rule (ntp.ubuntu.com:123) which is a requirement to deploy any AKS private cluster right now. So, if host based clock sync allows me to, I'm all in :)

**Comment by EppO** [comment]
> @Klaas- It's already released. Create a new agent pool or cluster, or do a node image upgrade or k8s version upgrade, you will get the change.

that means the docs could get updated to reflect that change? https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic#azure-global-required-network-rules

**Comment by miwithro** [comment]
yes once the change is completely rolled out we will update the document.

**Comment by gitflo1** [comment]
I just tested the new AKS nodepool images in my private cluster. Nodepool version `AKSUbuntu-1804gen2-2021.03.29`. The ntpd service has been replaced with chronyd. Chronyd uses the following settings:
```
...
# This directive enables kernel synchronisation (every 11 minutes) of the
# real-time clock. Note that it can’t be used along with the 'rtcfile' directive.
rtcsync

# Settings come from: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync
refclock PHC /dev/ptp0 poll 3 dpoll -2 offset 0
makestep 1.0 -1
```

The time should therefore be synced directly from the host. It also worked for me (` sudo chronyc sources`):
```
210 Number of sources = 1
MS Name/IP address Stratum Poll Reach LastRx Last sample
===============================================================================
#* PHC0 0 3 377 12 +2231ns[+4055ns] +/- 3594ns
```
