### ISSUE TITLE
azure-cli 2.0.28 - az aks create fales to create resource groups

### ISSUE THREAD

**Issue by pkelleratwork** [Azure/AKS#216]
azure-cli 2.0.28
macos version 10.13.3

Cannot create resource group from command line - gives error 

```
$ az aks create --resource-group RSG_TEST --name testcluster --ssh-key-value $HOME/.ssh/id_rsa.pub
Resource group 'RSG_TEST' could not be found.
```

I know i can connect via $ az because I was able to successfully run
`$ az ad sp create-for-rbac --skip-assignment`

**Comment by mboersma** [comment]
@pkelleratwork does the `RSG_TEST` group actually exist? What does this command return?
```
$ az group show -n RSG_TEST
```

**Comment by mboersma** [comment]
It sounds like your expectation was that the RG would be created simply by naming it in the `az aks create` command, but that's not intended behavior. You need to `az group create -l <region> -n RSG_TEST` first.

I'm closing this, but please reopen if I'm mistaken and there's more to pursue here.
