### ISSUE TITLE
SyncLoadBalancerFailed Tag value too large when creating several LoadBalancer services with the same IP

### ISSUE THREAD

**Issue by kortatu** [Azure/AKS#2160]
**What happened**:
When creating multiple LoadBalancer services with the same IP (just a preview feature from February 2021), you can't get more than 10/15 (depending on the services names) because you get a `Tag value too large` error:

```Warning  SyncLoadBalancerFailed         5m22s (x7 over 14m)  service-controller    Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {"error":{"code":"InvalidTagValueLength","message":"Tag value too large.  Following tag value 'default/public-ip-07d,default/s-mmv8b,default/s-khwwp,default/s-m2dwz,default/s-vqqwm,default/s-7shb4,default/s-wkxn8,default/s-jtbj4,default/s-28ncs,default/s-lvr87,default/s-qvnjd,default/s-q4c7g,default/s-mchg2,default/s-5rjmj,default/s-wc8v2,default/s-zkgct' exceeded the maximum length. Maximum allowed length for tag value - '256' characters."}}```

It seems that the Public IP in Azure is tagged with the names of the services concatenated.

**What you expected to happen**:
I expected the name of the services not being a limitation on the number of services sharing the same IP as long as ports are available and not conflicting

**How to reproduce it (as minimally and precisely as possible)**:

Create several LoadBalancer services with the same IP, each with different ports and after 10 /15 you start getting errors of SyncLoadBalancerFailed (I attached an example bash script)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-15T02:40:30Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T15:16:40Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

 
- Size of cluster (how many worker nodes are in the cluster?)
3 worker nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

A bunch of HTTP microservices, a small database, a Kafka cluster and a lot of small short-lived containers processing streams (each one with an external facing port)

- Other
I created a bash script for generating several LoadBalancer services. Just change the IP to use and the start/end port sequence

[lb-service-gen.txt](https://github.com/Azure/AKS/files/6088810/lb-service-gen.txt)

**Comment by feiskyer** [comment]
This is known issue from upstream cloud-provider-azure and would be tracked by https://github.com/kubernetes-sigs/cloud-provider-azure/issues/510.
