### ISSUE TITLE
Windows DNS issue

### ISSUE THREAD

**Issue by zhiweiv** [Azure/AKS#2161]
In Release 2021-03-01

> Behavioral Change
> Windows Containers may fail to resolve DNS names in ~1 seconds after it is created successfully and the status is showing running. This may not affect all customers but only those with applications that requires FQDN resolution when starting up the container. The workaround is retry or sleep ~1 seconds. 

As far as I know, it is has been an issue for a long time, see https://github.com/Azure/azure-container-networking/issues/341. Does this release note mean same thing? I am wondering why it is marked as Behavioral Change.

BTW, from my experience it may take more than 1 minute for DNS working when concurrent pod creation, you have to keep retry until it is ok, sleep ~1 seconds is not enough.

**Comment by miwithro** [comment]
@keikhara

**Comment by brobichaud** [comment]
Agreed, I was curious as well as to why this is pointed out as a change when it (or something very similar) has existed for years.

**Comment by AbelHu** [comment]
@zhiweiv @brobichaud Yes, it is still the known issue. We pointed it out in the release notes of 2021-03-01 because AKS tests failed for this issue with 2B/2C and it passed before 2B.

**Comment by zhiweiv** [comment]
Thanks for the information.
