### ISSUE TITLE
StatefulSet is not recreated correctly when node memory limit reached

### ISSUE THREAD

**Issue by MindaugasBudas** [Azure/AKS#2162]
**What happened**:

StatefulSet pod reaches node memory limit and gets recreated with message:

"The node was low on resource: memory. Container X was using xKi, which exceeds its request of xGi."
Pod is started, but it has no network capabilities.

**What you expected to happen**:

Pod is started and is fully functional.

**How to reproduce it**:

Deploy statefulSet with no resource limits and consume memory in pod (stress-ng tool can be used) until pod gets recreated.
Curl any public address inside pod - network is no longer working.

**Environment**:
- Kubernetes version : 1.19.7

**Comment by palma21** [comment]
You queried a public FQDN? Was coredns in the same node that this pod was stressing?

**Comment by MindaugasBudas** [comment]
You queried a public FQDN?  -  Yes.
Was coredns in the same node that this pod was stressing? - No.

2021-04-12, pr, 20:12 Jorge Palma ***@***.***> rašė:

**Comment by EPinci** [comment]
@MindaugasBudas Are you still experiencing the issue?
Have you upgraded you cluster since then?

Thank you.
