### ISSUE TITLE
Just-in-Time Access to Azure Kubernetes Service

### ISSUE THREAD

**Issue by miwithro** [Azure/AKS#2163]
What happened:
Customers would like to be able to configure Just-in-Time access policies for Azure Active Directory enabled AKS clusters.

What you expected to happen:
Customers should be able to configure the Just-in-Time access policy to provide restriction to AKS AAD Users.

Status:
We are working on documenting Just-in-Time Access.

**Comment by annerajb** [comment]
I am confuse.. it says this is GA and done.

But ehh it says that you are still working on it??
If it's done why is there still work left?

**Comment by palma21** [comment]
https://docs.microsoft.com/en-us/azure/aks/managed-aad#configure-just-in-time-cluster-access-with-azure-ad-and-aks
