### ISSUE TITLE
self hosted kubernetes networking on AKS

### ISSUE THREAD

**Issue by monaminor** [Azure/AKS#2167]
i wanted to setup self hosted kubernetes network tool like (flannel and weavenet) on AKS.
even thouh there is kubenet or azure-cni, can i install flannel or weavenet??
i tried to install flannel and weavenet but azure-cni is also there. i am unable to delete azure-cni deployment on aks.

please let me know how to solve this issue.

**Comment by justindavies** [comment]
Hi there, you cannot remove Azure CNI if that is the chosen networking option.  If you are looking for network policy enforcement please take a look at: https://docs.microsoft.com/en-us/azure/aks/use-network-policies for the supported options
