### ISSUE TITLE
Scaling doesn't work when the default nsg is deleted

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/AKS#217]
At the customer I work for we (normally) use a dedicated resource group per subscription to put all the NSG's in. When deploying an ACS or AKS cluster by default it creates a vnet, subnet and a nsg that is connected to the subnet.
But when I create my own NSG, connect it to the subnet and delete the default NSG then scaling doesn't work. I get an error that it cannot find the default NSG. If I just leave the default NSG in the ResourceGroup (eventhough not being used at all) the scaling works fine.
Is this "works as designed"?

**Comment by sauryadas** [comment]
this was by design ... i think you can modify the exisiting NSG... if the solution doesnt work for you please file a feature request in the link below.

https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks
