### ISSUE TITLE
NodePool Start/Stop

### ISSUE THREAD

**Issue by qpetraroia** [Azure/AKS#2170]
Allow users to be able to stop a given nodepool in their AKS cluster.

**Comment by justindavies** [comment]
Public documentation is here: https://docs.microsoft.com/en-us/azure/aks/start-stop-nodepools

**Comment by carvido1** [comment]
Hello.
Is this feature still in preview? We don't have the `PreviewStartStopAgentPool` feature enabled in our subscription and we can stop/start AKS clusters. I believe this is already GA.
