### ISSUE TITLE
Azure Kubernetes Nodes restarts + kubelet logs lost after restart

### ISSUE THREAD

**Issue by Sudharma** [Azure/AKS#2173]
**What happened**: AKS cluster is running with `1.19.7`  version and suddenly Nodepool worker is restarted. I want to investigate what happened. audit logs did not help much hence I wanted to check kubelet logs but I see the logs are present only after restart.! 

**What you expected to happen**: I expect the kubelet logs post restart of node.( If its already there I couldnt find any documentation on it except `journalctl -u kubelet`

**How to reproduce it (as minimally and precisely as possible)**:
you can randomly start any node and check if old kubelet logs are stored.

**Anything else we need to know?**: Any mechanism to see  kubelet logs of old node

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.7
- Size of cluster (how many worker nodes are in the cluster?): 2 Node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by justindavies** [comment]
Hi there, are you saying that the kubelet logs are empty after the restart of the nodepool worker?
