### ISSUE TITLE
ACR Integration requires ACR and AKS Cluster be in same subscription

### ISSUE THREAD

**Issue by brobichaud** [Azure/AKS#2182]
**What happened**:
I tried to enable ACR integration in AKS so that I do not have to create a docker registry secret. I immediately ran into a roadblock in that the ACR must exist in the same subscription as the AKS cluster.

**What you expected to happen**:
The ACR should be supported across subscriptions. We have multiple AKS clusters in different subscriptions (prod vs dev) but have a single ACR that is shared across all clusters and subscriptions.

**How to reproduce it (as minimally and precisely as possible)**:
Create an ACR in subscription A. Create an AKS cluster in subscription B. Attempt to enabled ACR integration in the cluster with the ACR in subscription A using: https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.10
- Size of cluster (how many worker nodes are in the cluster?): 5 nodes, 2 nodepools
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): NetCore v3.1 web and worker workloads as well as DotNet 4.8 workloads.
- Others:

**Comment by miwithro** [comment]
@norshtein can you look into this.

**Comment by EppO** [comment]
> If you are using an ACR that is located in a different subscription from your AKS cluster, use the ACR resource ID when attaching or detaching from an AKS cluster.

It's supported and explained in the docs, you need to use a resource ID as argument (that will include the subscription ID).
Bottom line, what `--attach-acr` basically does under the hood is to create the `AcrPull` role assignment for the identity of the kubelet. 
It could be achieved after AKS creation (need to get the kubelet Identity from the JSON response of the `az aks create` command) this way:
```
az role assignment create --role "AcrPull" --assignee <identityProfile/kubeletidentity/objectId> --scope /subscriptions/<subscriptionID>/resourceGroups/<ResourceGroupName>/providers/Microsoft.ContainerRegistry/registries/<ACRName>
```

**Comment by brobichaud** [comment]
Ahhh, my bad, did not even try that approach as I avoid using the full resource id whenever I can. Thanks for the clarity. I may suggest in the docs that they call this out specifically.
