### ISSUE TITLE
Alerts not triggering

### ISSUE THREAD

**Issue by JoseFMP** [Azure/AKS#2183]
My AKS alerts are not triggering. Set-up an alert to trigger whenever a pod has less 1 instance running. Never triggered. How can I obtain more information to troubleshoot?

According to the signal, it should trigger:

![image](https://user-images.githubusercontent.com/24405049/110752354-bf788d80-8277-11eb-8c2f-a033c03d4a8d.png)

Since the blue line is below the threshold. Right?!

But I get no alerts:

![image](https://user-images.githubusercontent.com/24405049/110752414-d1f2c700-8277-11eb-86ec-0d7f352c7ff2.png)

**Comment by saaror** [comment]
Thanks for looping-in! Ack, we will investigate the issue.

**Comment by qpetraroia** [comment]
Hi @saaror,

Any updates on this issue?

**Comment by qpetraroia** [comment]
Hi @JoseFMP,

I tried to reproduce your bug, but it ended up working just fine for me. Do you still have this issue?
