### ISSUE TITLE
Expired certificate AND unsupported Kubernetes version 1.17.7

### ISSUE THREAD

**Issue by Adolfi** [Azure/AKS#2184]
Hi.
I have an issue with one of my clients clusters.

The **Cluster Certificate** has expired 6 days ago, but when I try to rotate it using [these docs](https://docs.microsoft.com/en-us/azure/aks/certificate-rotation) I get an error saying:
_**"Deployment failed. Correlation ID: e210def7-3aa2-4af1-aa97-480a5725e8dc. Operation failed with status: 200. Details: Resource state Failed"**_
My resource is in a failed state because it is running on Kubernetes version 1.17.7, which is not an officially supported patch according to Microsoft Azure portal.

But, when I try to upgrade my **Kubernetes version** using [these docs](https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster) I get an error saying:
_**"BadRequestError: Operation failed with status: 'Bad Request'. Details: Current Certificates are expired, please rotate certificate. See https://docs.microsoft.com/en-us/azure/aks/certificate-rotation for more information."**_

So it seems these two states takess out each other.
How can I fix this?

**Environment**:
- Kubernetes version: 1.17.7
- Azure CLI version: 2.17.1

**Comment by andyzhangx** [comment]
pls file an Azure ticket, there is a bug in rotate-certs functionality, and hotfix is rolling out.

**Comment by Adolfi** [comment]
Thank you @andyzhangx!
My client has contacted the Azure support and hopefully this will be resolved soon.

I was contacted by Microsoft Azure on Twitter asking me to extend this GitHub page with some screenshots that might be helpful when investigating this.

So, this is how it looks in the Azure portal:
<img width="1398" alt="Screen Shot 2021-03-12 at 06 48 45" src="https://user-images.githubusercontent.com/6122154/110898200-0cec0d80-82ff-11eb-9d19-d2708d44ef6b.png">

When looking at the details:
<img width="1584" alt="Screen Shot 2021-03-12 at 06 49 43" src="https://user-images.githubusercontent.com/6122154/110898239-2725eb80-82ff-11eb-99c5-71d37a8e1ebc.png">

As you can see, both the certificate is expired and the Kubernetes Version is unsupported.

When I try to rotate the certificate, I get this error:
<img width="841" alt="Screen Shot 2021-03-12 at 06 50 39" src="https://user-images.githubusercontent.com/6122154/110898307-4ae93180-82ff-11eb-8c36-09f772d9d06b.png">

When I check for available upgrades I can see that I am currently running 1.17.7, and should be able to upgrade to 1.17.3,1.17.6.1.18.10 or 1.18.14. 
<img width="747" alt="Screen Shot 2021-03-12 at 06 51 50" src="https://user-images.githubusercontent.com/6122154/110898971-8c2e1100-8300-11eb-9e5c-9fdc5e163147.png">

But regardless of which version I choose I get this error:
<img width="1227" alt="Screen Shot 2021-03-12 at 06 58 38" src="https://user-images.githubusercontent.com/6122154/110898907-69036180-8300-11eb-9d01-3eb817a94303.png">

Any help at this point would be much appreciated!

**Comment by andyzhangx** [comment]
confirmed that this rotate-certs issue was resolved on all regions now.

**Comment by Adolfi** [comment]
Thank you!
