### ISSUE TITLE
How to use an "Azure Private DNS Zone" with AKS?

### ISSUE THREAD

**Issue by evmimagina** [Azure/AKS#2185]
Hi,

We would like to use "Azure Private DNS Zone" for registering any service deployed on the AKS, Is there any way we can achieve this?

Many thanks and best regards,

**Comment by miwithro** [comment]
@evmimagina the document below should answer all your questions.

https://docs.microsoft.com/en-us/azure/aks/private-clusters#configure-private-dns-zone

**Comment by evmimagina** [comment]
Hi @miwithro ,

Thanks four your reply. Unfortunatedly the link you provide is for registering the API URL as an internal DNS registry (if I'm not mistaken), the scenario I'm asking is about how could I use an internal Azure DNS Zone for registering kubernetes services (or pods) names.

Regards,

**Comment by miwithro** [comment]
@evmimagina that is not a currently supported scenario.  We are looking into public dns which would support this scenario.

**Comment by evmimagina** [comment]
Hi @miwithro ,

Thanks for your reply. 
In my opinion would be better if the feature is supported on Private DNS Zones first, after all, the goal would be to register services names or other elements within the K8S that would require to use a customized domain name (beyond editing core-dns settings... or using external-dns).

**Comment by miwithro** [comment]
Sorry I got confused on your ask. I deleted my previous response.  

The answer to your question is that you can use external DNS as you mentioned yourself today, and we are looking at offer this as a AKS addon in the future.
   
https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/azure.md
