### ISSUE TITLE
Vulnerable Kubernetes version detected during container scan

### ISSUE THREAD

**Issue by kundan1avaya** [Azure/AKS#2186]
**What happened**:
Scanning report found Vulnerable Kubernetes version
**What you expected to happen**:
It was expected to be latest version and near to client and server
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Target Container = 3d4929******
Container Name = k8s_tunnel-front_tunnelfront-****8b4647-d4hfc_kube-system_258ffc7a-575f-403a-8249-237a15cd89ea_0
Container SHA = 3d4929ecf28dc45bd******3f5ae0243b354a85a24ad7b8a1b56dd7db7******
Result = Vulnerable Kubernetes version detected.

Client Version: version.Info

{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"******2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info

{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"******c9c736cf0bdb0de3549d30c676e98eebaf", GitTreeState:"clean", BuildDate:"2021-01-18T09:12:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by kundan1avaya** [comment]
[podslogs.txt](https://github.com/Azure/AKS/files/6148149/podslogs.txt)
[logs.txt](https://github.com/Azure/AKS/files/6148150/logs.txt)

**Comment by miwithro** [comment]
We are in the process of replacing tunnel-front with Konnectivity service for 1.18 and above clusters going forward. Notice the screenshot from my 1.18.10 AKS cluster in East US2.

![image](https://user-images.githubusercontent.com/50749048/111324468-2ebbfc00-8641-11eb-822c-2a6e63aa7da6.png)
