### ISSUE TITLE
Autoscaler doesn't add Nodes in missing Availability Zones

### ISSUE THREAD

**Issue by antonmatsiuk** [Azure/AKS#2187]
**What happened**:
Auto-scaler for node pools doesn't add new nodes into required availability zones. If a static PV has a constraint on a particular AZ (bound to a ManagedDisk in this AZ) auto-scaler won't trigger node scale-up to add a missing node into required AZ.

**What you expected to happen**:
Auto-scaler adds nodes into a particular AZ if Pod's PV is bound to this AZ 

**How to reproduce it (as minimally and precisely as possible)**:
1. create a test deployment with a static PV bound to a ManagedDisk in a particular AZ, e.g. AZ=3
2. create a Node Pool with auto-scaling enabled and node min_count = 1
3. deploy the test deployment 

**Anything else we need to know?**:
Auto-scaler output: 
```
0/1 nodes are available: 1 node(s) had no available volume zone
pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 node(s) had no available volume zone 
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.14
- Size of cluster (how many worker nodes are in the cluster?): 3
- Location: Germany West Central

**Comment by marwanad** [comment]
There's two limitations with respect to zones here:
1. You can't ask VMSS for a VM in a particular zone.
2. CA picks up a node from a nodepool and assumes all nodes in the same group are going to have the same blueprint with respect to the scheduling properties, resources, labels, taints, zones, etc

Thus, the recommendation is to have a nodepool per AZ and enable the `--balance-similar-node-groups` option to achieve the balancing. 

This is documented at the bottom of [this](https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler#use-the-cluster-autoscaler-with-multiple-node-pools-enabled) section.
