### ISSUE TITLE
Proposal: install havegd in all nodes to prevent low entropy situations

### ISSUE THREAD

**Issue by joaocc** [Azure/AKS#219]
(Not being sure what is the correct place to ask for this feature, I originally posted this here, but then moved it to https://github.com/kubernetes/kubernetes/issues/60751. Please accept my apologies if this is not the correct scope for this)

Nodes can run into low entropy situations.
Currently, one approach to deal with with is to deploy a privileged pod to every node via DaemonSet. Having this installed on the base image would address this.

More info here:
* http://www.irisa.fr/caps/projects/hipsor/
* http://issihosts.com/haveged/

Packages exist for debian:
* https://packages.debian.org/wheezy/haveged
* https://packages.debian.org/sid/haveged

**Comment by mboersma** [comment]
@joaocc thank you! We're tracking feature requests for AKS at our "user voice" forum where they can be voted on and prioritized. I added this there:

https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/35053906-install-havegd-on-nodes-to-prevent-low-entropy-sit
