### ISSUE TITLE
[Feature Request] Convert an existing AKS public cluster to a private cluster

### ISSUE THREAD

**Issue by vavvolo** [Azure/AKS#2190]
Allow converting an existing AKS public cluster to a private cluster without re-creating the cluster

**Comment by VISHWAVASUDEVAN** [comment]
Is this capability available now? Or only option is to rebuilt now

**Comment by miwithro** [comment]
We are bringing a new feature "API server VNET Integration" in the next few months, that will allow you to convert a public cluster to a private cluster. #2729
