### ISSUE TITLE
Mixed protocol support

### ISSUE THREAD

**Issue by lazydino** [Azure/AKS#2193]
I hope I reach the right channel for the answer of this issue mentioned as https://github.com/kubernetes/enhancements/issues/1435 or this [stackoverflow issue](https://stackoverflow.com/questions/65286712/kubernetes-aks-how-to-load-balance-both-tcp-and-udp-ports-for-same-ip-addres). I cannot find any useful info if this is currently supported on Azure as of March 12, 2021.  This enhanced network feature is mentioned on version [1.20](https://sysdig.com/blog/whats-new-kubernetes-1-20/) Is version 1.20 currently deployed on Azure?

I am trying to run [OpenSim](http://opensimulator.org/wiki/Main_Page) server up on AKS. OpenSim region communication requires both TCP and UDP served in the same port, which would not work with my current AKS cluster based on 1.17.

**Comment by TobiasXy** [comment]
I upgraded one cluster to 1.20 preview and it seems the feature is not available. Probably because you would have to set the MixedProtocolLBService feature flag to true, which seems not to be the case for AKS.

**Comment by miwithro** [comment]
@lazydino Mixed protocol support is listed as an Alpha feature.  We have a planned feature to support Alpha clusters which would light up this capability. 

 https://github.com/Azure/AKS/issues/2058
