### ISSUE TITLE
Can I use LVM/RAID in AKS to address IOPS throttling

### ISSUE THREAD

**Issue by adityasundaramurthy-maersk** [Azure/AKS#2196]
**What happened**:
My workloads are I/O heavy and routinely run into IOPS limits, despite using large OS disks and large VMs that have high IOPS limits. This is a follow-up to #2069 

**What you expected to happen**:
Workloads and nodes are not constrained by OS disk IOPS limits.

**How to reproduce it (as minimally and precisely as possible)**:
Run IOPS heavy workloads on AKS clusters with 2TB disks and VM SKU with large IOPS limits. Notice that there are IOPS limits. Azure documentation for Linux VMs recommends using LVM/RAID for higher IOPS ([here](https://docs.microsoft.com/en-us/previous-versions/azure/virtual-machines/linux/optimization#using-software-raid-to-achieve-higher-iops), [here](https://docs.microsoft.com/en-us/previous-versions/azure/virtual-machines/linux/configure-raid) and [here](https://docs.microsoft.com/en-us/previous-versions/azure/virtual-machines/linux/configure-lvm)). However, AKS does not seem to support LVM/RAID yet.

**Anything else we need to know?**:
This is a follow-up to #2069

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19
- Size of cluster (how many worker nodes are in the cluster?): 19
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): IOPS-heavy batch workloads
- Others: N/A

CC: @gkaleta

**Comment by andyzhangx** [comment]
Current disk driver does not support RAID, one workaround is using local disk, e.g. Azure LSv2 VM with NVMe SSD, follow details here: https://github.com/Azure/kubernetes-volume-drivers/tree/master/local

**Comment by alexeldeib** [comment]
Andy's comment is correct, but to address the part about the OS disk specifically, pasting my comment from here: https://github.com/Azure/AKS/issues/2069#issuecomment-812071067

> Azure doesn't support multiple OS disks AFAIK, so RAIDing them isn't an option. RAID'ing data disks is an option, but we're also working towards OS/workload isolation e.g. via #1753. As you mentioned ephemeral disks also substantially help by raising the iops/throughput cap to the VM limit.
>
> If you want to provision data disks for a workload after provisioning, you're free to RAID them any way you like.
