### ISSUE TITLE
Garbage collection on AKS with kubernetes version 1.19+

### ISSUE THREAD

**Issue by kutsyk-neocles** [Azure/AKS#2198]
**What happened**: Nodes disk memory is reachin peaks

**What you expected to happen**: nodes disk memory is not reaching top, but is in general low

**How to reproduce it (as minimally and precisely as possible)**: Use cluster and with a time node disks are becoming full

**Environment**:
- Kubernetes version (use `kubectl version`):  1.19.7
- Size of cluster (how many worker nodes are in the cluster?) : 10
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): HTTP microservices with GQL

**Comment by seguler** [comment]
Can you please share more about what is filling up the disk? You can calculate top level directory sizes and drill down to find the cause of it. `du -sh /`

**Comment by kutsyk-neocles** [comment]
@seguler the command is not finishing to execute and logs me out of node due to high CPU usage. But I can see that nodes disk is full:
![image](https://user-images.githubusercontent.com/61271706/112822684-8d916480-9088-11eb-98e5-b0456a6cc09c.png)

**Comment by kutsyk-neocles** [comment]
Any update on this?

**Comment by miwithro** [comment]
Here is the containerd guidance on garbage collection.

https://github.com/containerd/containerd/blob/main/docs/garbage-collection.md
