### ISSUE TITLE
Allow assigning pod identities on cluster creation

### ISSUE THREAD

**Issue by aelij** [Azure/AKS#2199]
**What happened**:
Trying to create a new AKS cluster in an ARM template with assigned pod identities results in an error:

```json
{
  "code": "PodIdentityAddonUserAssignedIdentitiesNotAllowedInCreation",
  "message": "PodIdentity addon does not support assigning pod identities on creation."
}
```

This unnecessarily complicates initial deployments. We are using BYO managed identity, so why can't this just work?

**What you expected to happen**:
Allow assigning pod identities on cluster creation

**How to reproduce it (as minimally and precisely as possible)**:
ARM template:

```bicep
podIdentityProfile: {
      enabled: true
      userAssignedIdentities: [
        {
          identity: {
            resourceId: resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', managedIdentityName)
          }
          name: identityName
          namespace: servicesNamespace
        }
      ]
    }
```

**Comment by enqueue** [comment]
The current limitation prevents us from using the AKS pod identity add-on, since we rely on ARM templates to provision our resources. Do you plan to address this issue, or can you recommend a workaround that does not involve the use of az CLI or Powershell?

**Comment by jabbera** [comment]
Considering they are doing pod identity v2 and this version will never leave preview I wouldn't hold out hope we are getting a fix to this.

**Comment by benjamincburns** [comment]
The main problem here is that when deploying updates in Complete mode, existing pod identities are removed. I'd be happy to add my identities to the template, but then I can't actually use the template to create the cluster.

**Comment by miwithro** [comment]
@jabbera is correct.  We are working on V2 of Pod Identity which will mitigate the issue above.  We are going to Private Preview of V2 late July, and are working towards announcing a Public Preview/GA date soon.

**Comment by aelij** [comment]
@miwithro Thanks. Can you please make sure that V2 doesn't have this issue?

**Comment by aelij** [comment]
Another thing to watch out for is that `az aks pod-identity add` essentially rewrites the cluster's object, making it non-idempotent. That is, when we deploy AKS via ARM, it writes the object without the pod identities, and then we have to add them again using the CLI. Which creates a period where the cluster has no MI assigned - and that causes service failures.

One way to resolve this would be to make the identities a sub-resources (e.g. `Microsoft.ContainerService/managedClusters/podIdentities`) which can be written to independently of the cluster.

**Comment by andre-lx** [comment]
Hi. Any news on this? And why is this closed? 

Right now, it's impossible to have assigned user assigned identities on arm templates (and terraform) on cluster creation. I already tried a lot of things, and updates works great, after inserting manually with:
```
az aks pod-identity add --cluster-name my-aks-cn --resource-group myrg --namespace myns --name example-pod-identity --identity-resource-id /subscriptions/......
```

But, I need to have this done at once, with the deployment, so I need to insert the pod user identities to the cluster automatically. I also tried to run the command using the `DeploymentScripts` but the deployment scripts are not ready to use `preview aks extersion`.

My config looks like this:

```
    {
      "type": "Microsoft.ContainerService/managedClusters",
      "apiVersion": "2021-02-01",
      "name": "[variables('cluster_name')]",
      "location": "[variables('location')]",
      "dependsOn": [
        "[resourceId('Microsoft.Network/virtualNetworks', variables('vnet_name'))]"
      ],
      "properties": {
....
        "podIdentityProfile": {
        "allowNetworkPluginKubenet": null,
        "enabled": true,
        "userAssignedIdentities": [
            {
            "identity": {
                "clientId": "[reference(resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', 'managed-indentity'), '2018-11-30').clientId]",
                "objectId": "[reference(resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', 'managed-indentity'), '2018-11-30').principalId]",
                "resourceId": "[resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', 'managed-indentity')]"
            },
            "name": "managed-indentity",
            "namespace": "myns"
            }
        ],
        "userAssignedIdentityExceptions": null
        },
....
      },
      "identity": {
        "type": "SystemAssigned"
      }
    },
```

I'm always getting the same issue:

`
        "statusMessage": "{\"error\":{\"code\":\"InvalidTemplateDeployment\",\"message\":\"The template deployment 'deployment_test' is not valid according to the validation procedure. The tracking id is '.....'. See inner errors for details.\",\"details\":[{\"code\":\"PodIdentityAddonUserAssignedIdentitiesNotAllowedInCreation\",\"message\":\"Provisioning of resource(s) for container service cluster-12344 in resource group myrc failed. Message: {\\n  \\\"code\\\": \\\"PodIdentityAddonUserAssignedIdentitiesNotAllowedInCreation\\\",\\n  \\\"message\\\": \\\"PodIdentity addon does not support assigning pod identities on creation.\\\"\\n }. Details: \"}]}}",
`

**Comment by bcho** [comment]
Hi @andre-lx , unfortunately, this is by design that current pod identity addon implementation doesn't support being enabled during the cluster creation, because it depends on the cluster identity, which is only available only after cluster creation. As a workaround, we could assign enable and assign the pod identities after the cluster creation by using az cli. This might need to modify your deployment process.

**Comment by andre-lx** [comment]
Thanks for the quick response @bcho .

I already tried that, following a lot of tutorials and guides, mas maybe I'm missing something. 

After cluster creation, I create the the AzureIdentity, AzureIdentityBinding and do the aadpodidbinding on the deployment labels:
```
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: example-pod-identity
  namespace: example_ns
spec:
  clientID: cabe4sdsadsad-11111-11111-111111-11111asdasdc
  resourceID:/subscriptions/...../resourceGroups/...../providers/Microsoft.ManagedIdentity/userAssignedIdentities/example/pod-identity
  type: 0

---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: example-pod-identity-binding
  namespace: ydata
spec:
  azureIdentity: example-pod-identity
  selector: example-pod-identity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      labels:
        aadpodidbinding: example-pod-identity
```

But this is not working. Well, first, if I run again the template, the AzureIdentity, AzureIdentityBinding got deleted. But that's not hard to fix with some kyverno policy for example that ensures that the resources are always available. 

By the other hand, this only starts to work after run the command:

`
az aks pod-identity add --cluster-name my-aks-cn --resource-group myrg --namespace myns --name example-pod-identity --identity-resource-id /subscriptions/......
`

And this creates the AzureIdentity, AzureIdentityBinding deleting all the available ones. 

It looks like that I'm missing some configuration, or binding. 

Can you give me some help please?

Thanks
