### ISSUE TITLE
AKS regional expansion

### ISSUE THREAD

**Issue by seanknox** [Azure/AKS#22]
Using this to serve as public notice that we're likely going to expand into the following new regions to support AKS:

* East US
* Central US
* Canada East
* Canada Central

**Comment by ramonduraes** [comment]
Perfect !!

**Comment by smithkb** [comment]
Do you have a time frame on expansion?

**Comment by bramvdklinkenberg** [comment]
Any idea when westeurope will have aks available?

**Comment by jorgearteiro** [comment]
At least one Australian Region please.

**Comment by jrthib** [comment]
If you guys have an estimated timeline, that would be great.

**Comment by slack** [comment]
Closing this issue. Please keep an eye on the preview_regions doc at the root of the repo.

West Europe is coming online today, Central US later this week.

**Comment by tanner-bruce** [comment]
@slack is there an ETA on Canada Central or East? We'd love to spin up a couple clusters to test it out.
