### ISSUE TITLE
ETA for Japan availability

### ISSUE THREAD

**Issue by lostllama** [Azure/AKS#220]
Is there an ETA when AKS will be available in Japan?

We've been forced into using [ACS ](https://github.com/Azure/ACS/issues/111) for our project because AKS isn't available and the data (video) we're interacting with isn't suitable for transferring to North America to utilise AKS there. Unfortunately ACS isn't ideal because we can't use a newer version of Kubernetes than 1.7.7 with it. When will AKS be available?

**Comment by seanmck** [comment]
AKS is now available in Japan East.
