### ISSUE TITLE
Unable to access deployement on AKS using external IP, the deployment image is pulled from ACR

### ISSUE THREAD

**Issue by dalavayi** [Azure/AKS#2202]
**What happened**:
When i am deploying an image from AKS, which is stored in ACR, the pods are running fine and the container is created successfully, but i am unable to access the same using External IP. 

**What you expected to happen**:
I tried the same thing where image is being pulled from msr.microsoft.com, then i can access the service from external IP. The same is to be expected when pulling images from ACR. 
I followed the guidance of docs : https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-deploy-application

**How to reproduce it (as minimally and precisely as possible)**:
1.  created a container registry 'myreg' from console
2. created a kubernetes cluster 'mycluster' from console
3. az aks update -n mycluster -g myresource --attach-acr myreg
4. az aks check-acr --name mycluster --resource-group myresource --acr myreg.azurecr.io
output: Your cluster can pull images from myreg.azurecr.io!
5. az acr import --name myreg --source mcr.microsoft.com/oss/bitnami/redis:6.0.8 --image redis:v1
6. az acr import --name myreg --source mcr.microsoft.com/azuredocs/azure-vote-front:v2 --image azure-vote-front:v2
7. in this file : 
     https://github.com/Azure-Samples/azure-voting-app-redis/blob/master/azure-vote-all-in-one-redis.yaml
   I had replaced line 19 with image: myreg.azurecr.io/redis:v1 and line 60 image: myreg.azurecr.io/azure-vote-front:v2. no more changes done
8. kubectl apply -f azure-vote-all-in-one-redis.yaml
9. kubectl get services
The pods are running fine, the external IP is obtained, i then tried http://<EXTERNAL_IP>/ from my browser.

It is getting terminated with connection_timed_out error.

**Anything else we need to know?**:
When i tried the same process without changing line 19, 60. i could access the azure_vote UI from the exteral IP.

**Comment by justindavies** [comment]
Hi there, would you be able to attach the changed file that you are using (post-edits)
