### ISSUE TITLE
UDP packets are partially duplicated after upgrade to 1.19.7

### ISSUE THREAD

**Issue by cubed-it** [Azure/AKS#2204]
**What happened**: UDP packets generated from a Pod on VM 1 are received twice by another Pod on VM 1.

**What you expected to happen**: UDP packets should not be delivered twice.

**How to reproduce it (as minimally and precisely as possible)**: 
Unfortunately, I can't give minimal instructions on how to reproduce it. In the specific case, it was noticed that - after upgrading from AKS 1.18.8 to 1.19.7 - duplicate entries appeared in the logging. 
To capture logs from our ASP.NET-Services we use Graylog with a UDP input.
It is noticeable that only entries appear twice where the creator and recipient VM are the same. A change from UDP to HTTP solves the problem. So it is obvious that something is wrong with the UDP routing in 1.19.7 or after upgrading this specific cluster.

**Anything else we need to know?**: Are there any useful things I can check on the VMs?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.7
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by miwithro** [comment]
@paulgmiller can you get someone to look into this?

**Comment by miwithro** [comment]
@AbelHu can you address this one?

**Comment by AbelHu** [comment]
@cubed-it could you help to file a support ticket so we can investigate it?

1. ssh to the VM1 and run C:\k\debug\startpacketcapture.cmd
2. Reproduce the issue
3. ssh to the VM1 and run C:\k\debug\stoppacketcapture.cmd and then powershell C:\k\debug\collect-windows-logs.ps1
4. Collect the trace and logs to share it with CSS

**Comment by cubed-it** [comment]
@AbelHu I'm sorry, but the cluster has long been updated by several versions and a workaround (we are using http instead of udp now) has been implemented for the problem. I am therefore unfortunately not able to contribute any further on this issue and from my side the issue can be closed.
