### ISSUE TITLE
Unable to attach volume - Timedout waiting for condition

### ISSUE THREAD

**Issue by Baldro** [Azure/AKS#2206]
**What happened**:
On a just created AKS Cluster using k8s 1.18.14, every component that has a Persistent Volume Claim fails to install via helm reporting: `MountVolume.WaitForAttach failed for volume "pvc-e1a55145-07aa-4e86-8094-35a51f02d059" : timed out waiting for the condition`
Below an example while installing Bitnami/RabbitMq Helm.

Looking at the Events List for the given installation we have these in the following order:

1. AttachVolume.Attach succeeded for volume "pvc-e1a55145-07aa-4e86-8094-xxxxxxxxx"
2. Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[configuration data rabbitmq-token-knpwx]: timed out waiting for the condition
3. MountVolume.WaitForAttach failed for volume "pvc-e1a55145-07aa-4e86-8094-xxxxxxx" : timed out waiting for the condition

This is an issue we are facing from some days on.

**What you expected to happen**:

Component successfully installed and volume mount completed correctly

**How to reproduce it (as minimally and precisely as possible)**:

Create an AKS Cluster with k8s 1.18.14, and install Bitnami/RabbitMq helm chart or any other component that need PV.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.14
- Size of cluster (how many worker nodes are in the cluster?): 3 Nodes based on Standard_DS2_v2
- Storage Classes: no changes to the standard classes present in a fresh aks cluster
- General description of workloads in the cluster : No load, is a cluster startup
- Azure Region: west-europe
![aks-issue-pv](https://user-images.githubusercontent.com/7020133/111814003-3cd87980-88da-11eb-9900-2c93f1d6e84c.JPG)
- Agent Pool Availability zone: all nodes in westeurope-1
![image](https://user-images.githubusercontent.com/7020133/111900329-3d842380-8a32-11eb-808c-233442712653.png)

**Comment by miwithro** [comment]
@andyzhangx @feiskyer

**Comment by feiskyer** [comment]
Please open a support ticket with required cluster information.

**Comment by junaid18183** [comment]
I am observing same issue

**Comment by gfrankel97** [comment]
I am having the same issue on the same Kubernetes version

**Comment by alftio** [comment]
Missing the controller for the CSI driver
 
 
KB Article/TSG/Links
-------------------------------
[kubernetes-sigs/azuredisk-csi-driver: Azure Disk CSI Driver (github.com)
](https://github.com/kubernetes-sigs/azuredisk-csi-driver)
[Use Container Storage Interface (CSI) drivers for Azure Disks on Azure Kubernetes Service (AKS) - Azure Kubernetes Service | Microsoft Docs](https://docs.microsoft.com/en-us/azure/aks/azure-disk-csi)

**Comment by steav** [comment]
Same problem with 1.19.13 (not upgrading, just after some nodes scaled + pods moved)
