### ISSUE TITLE
Default azure disk storageClass VolumeBindingMode - WaitForFirstConsumer or Immediate 

### ISSUE THREAD

**Issue by JaroslavMajera** [Azure/AKS#2207]
**What happened**:
Newly created aks default azure disk storageClasses are created with VolumeBindingMode: **WaitForFirstConsumer**. I can't find any documentation that describes default azure disk storagaClass VolumeBindingMode. Is there change from Immediate to WaitForFirstConsumer?

**What you expected to happen**:
Default azure disk storageClasses are created with VolumeBindingMode: Immediate. We have some aks clusters which have been upgraded from aks 1.16 and they have VolumeBindingMode: **Immediate**.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.14

**Comment by Baldro** [comment]
We are facing similar behavior with 1.18.14 in the last days.
We have solved by deleting the default SC and creating it with VolumeBindingMode set to Immediate:

`
kubectl get sc default -o yaml > default-sc.yaml

# Change default sc volume binding mode to Immediate
sed -i 's/WaitForFirstConsumer/Immediate/g' default-sc.yaml

kubectl  delete sc default
kubectl  apply -f default-sc.yaml`

**Comment by JaroslavMajera** [comment]
We know about this workaround, but there is note in docs [AKS reconciles the default storage classes and will overwrite any changes you make to those storage classes.](https://docs.microsoft.com/en-us/azure/aks/concepts-storage#storage-classes)

**Comment by magooster** [comment]
This change was announced here [Release 2021-02-08](https://github.com/Azure/AKS/releases/tag/2021-02-08)

AKS fixed the issue with reconciling of the default storage class a wild back  see [Cannot set a different default storage class](https://github.com/Azure/AKS/issues/118)

**Comment by JaroslavMajera** [comment]
Thank you for info @magooster.

**Comment by magooster** [comment]
One thing to note AKS still uses the deprecated topology labels

failure-domain.beta.kubernetes.io/region 
failure-domain.beta.kubernetes.io/zone

so if your using any affinity rules you need to use those labels in your resource specs.

see [AKS adds/uses deprecated failure-domain.beta.kubernetes.io labels](https://github.com/Azure/AKS/issues/2188)
