### ISSUE TITLE
Is it possible to configure idle timeout for control plane?

### ISSUE THREAD

**Issue by hjarvard** [Azure/AKS#2209]
Hi, I have a software which watches cluster for changes, e. g. pods getting reschedules etc. Release 2020-11-09 enabled control plane to send RST packet for idle connections after fixed 4 min interval.
Can it be configured to a different value or is it implied that client must send send keep alive packets every <4 min?

**Comment by olsenme** [comment]
The 4 min tcp reset is by design. You should use client with keep alive < 4min.
