### ISSUE TITLE
Unable to access DNS when pod condition is not ready

### ISSUE THREAD

**Issue by SteveCurran** [Azure/AKS#2213]
**What happened**:
When trying to make an http request in a container during start up the request is unable to resolve the host until the pod condition is "ready". Any other condition it appears DNS is not available. This is only happening in windows containers. This makes it impossible to use an init container to check whether other services are available.

**What you expected to happen**:
I would expect that start up code or init containers would have DNS access regardless of pod condition, equivalent to linux.

**How to reproduce it (as minimally and precisely as possible)**:
Create init container and try to access google.

**Anything else we need to know?**:

**Environment**: mcr.microsoft.com/windows/servercore:ltsc2019 
- Kubernetes version (use `kubectl version`): 1.18.14
- Size of cluster (how many worker nodes are in the cluster?) 10
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by keikhara** [comment]
@SteveCurran - we are aware of this issue and have raised to Windows container team. 
@immuzz and @mkostersitz on the DNS issue with windows container.

**Comment by mkostersitz** [comment]
@SteveCurran it is a day 1 limitation in Windows containers that DNS resolution is not available until the container is ready. It has been there since 2016. Recent changes in the OS infrastructure seem to have extended the time it takes for the DNS settings to become available in the container. We have investigated and debugged the issue and it is not something that is fixable as it is. We recommend at this point to delay the HTTP request or retry a few times until it succeeds.

**Comment by SteveCurran** [comment]
@mkostersitz thanks for the reply. Is this documented? This is unfortunate. This limitation prevents the use of using init containers to access resources/services for any type of startup configuration or dependency checks. I am assuming this would prevent the use of readiness probes and readiness gates. The container is blind until it has been made available to take requests. This is a serious limitation for customers using windows. It sounds like Microsoft has no plans on fixing this?

**Comment by mkostersitz** [comment]
@SteveCurran we are not looking into changing the behavior for any in market release of Windows Server. We are looking at the overall startup process of Windows Containers for one of the next upcoming releases.  Technically you can still use a Windows Init container you just need to take into account the delay when putting the container together.  
This example will still work it just may take a few seconds longer for the init container to finish
`for ($i=0;$i -le 90) {Start-Sleep -Seconds 1; Resolve-DnsName myServicet;if( $?){Write-Host "Service is ready";break } else { Write-Host "Service is not ready. $Error[0]" }}`

We understand that the situation is not ideal for now but the issue should not be blocking. I also looked at the conformance run and it succeeds for the readiness probe and gate cases.
