### ISSUE TITLE
Panic on sgx-webhook pod with only one confidential compute node

### ISSUE THREAD

**Issue by mattcollier** [Azure/AKS#2219]
Hello Team,

We have been utilizing SGX in some of our AKS clusters for a few months now. We had been using the following command to deploy clusters:
```
az aks create --resource-group nacs-av-sandbox \
              --name sgx-failure-demo \
              --kubernetes-version 1.18.10 \
              --node-count 1 \
              --node-vm-size Standard_DC2s_v2 \
              --aks-custom-headers usegen2vm=true \
              --enable-addon confcom \
              --generate-ssh-keys \
              --nodepool-labels app=foo \
              --output none
```

Although the cluster is provisioned with this command, it is not possible to add workloads.  There are two symptoms that I have identified:

### Panic reported on the `sgx-webhook` pod
https://gist.github.com/mattcollier/e63bc548fd3e44c96e3a15fd77a9c5db

### Issues with `sgx-validate-config` when attempting to start some workloads
related to: https://github.com/Azure/AKS/issues/2214
```
~/bedrock-dev/db-k8s-manager$ kubectl apply -f https://k8s.io/examples/application/shell-demo.yaml
Error from server: error when creating "https://k8s.io/examples/application/shell-demo.yaml": admission webhook "sgx-validate-config.kube-system.svc" denied the request without explanation
```

I now know that `--node-count 1` is not a viable option. I see that at some point a requirement was added that there are at minimum 3 confidential compute nodes (2VCPU Standard_DC2s_v2) in the cluster.  Described in the documentation as "A minimum of six DCsv2 cores..."

https://docs.microsoft.com/en-us/azure/confidential-computing/confidential-nodes-aks-get-started#prerequisites

I then discovered that if I omit the `--node-count 1` parameter in the command above, a cluster will be created that *automatically* provisioned 3 Standard_DC2s_v2 nodes and the `sgx-webhook` pod in the cluster does not report panic.

**Comment by agowdamsft** [comment]
@mattcollier we already have a fix in place that should be rolling out soon. Apologies for the inconvenience, the documented workaround in #2214  should help in the time being while we roll out a fix.

**Comment by mattcollier** [comment]
@agowdamsft thank you for the information.  Can you describe what the behavior will be after the fix is rolled out?

Will an attempt to provision a cluster without the requisite 3 confidential compute nodes fail straight away?

Also, wrt to the 6 confidential compute vCPU requirement described here: https://docs.microsoft.com/en-us/azure/confidential-computing/confidential-nodes-aks-get-started#prerequisites

This breaking change caught me by surprise.  Is there a blog or mailing list I should be following to stay informed about these sorts of changes? Is there any additional reading material related to this new(ish) requirement?

**Comment by agowdamsft** [comment]
@mattcollier thanks for the feedback. As this is an addon service to AKS we try to align with AKS release notes as much as possible . This release that is causing issues missed this communication path. Going forward we will make sure to be on the AKS board and release notes so you can have visibility on upcoming updates.

On the behavior of hotfix, if you have enabled the "confcom" addon on your AKS cluster this hotfix update will be delivered to your cluster automatically. One updated your existing deployments scripts should continue to work without any problems.

**Comment by mattcollier** [comment]
@agowdamsft Thanks for the additional information.

To be clear, a cluster with a single Standard_DC2s_v2, along with the `confcom` add-on is a **valid** configuration.  Is that correct?

**Comment by agowdamsft** [comment]
That is correct. This cluster should receive an update when hotfix is released based on the region it is created.

**Comment by mattcollier** [comment]
@agowdamsft can you provide a timeline for the hotfix deployment?  We are impacted by this in `useast` and `south-central`.  Thank you.

**Comment by agowdamsft** [comment]
@mattcollier hotfix deployments are almost done. south-central received the fix and useast will be done in couple of hours from now. Let me know if you continue to see any issues post 12 noon PST.
