### ISSUE TITLE
After scaling out VMSS outgoing connections are dropped

### ISSUE THREAD

**Issue by kamilzzz** [Azure/AKS#2220]
AKS with 3 node pools in West Europe, each in separate availability zone.
Standard Azure Load Balancer used both for ingress & egress traffic.

Outbound rule's port allocation strategy is set to "Manually choose number of outbound ports" and ports are chosen by "Maximum number of backend instances". 3 public IPs are used as outbound IPs.

![image](https://user-images.githubusercontent.com/32141632/112184679-b97f9680-8bff-11eb-80e1-320a83e8b5f3.png)

During a high load test (~5k RPS/s to API service, and ~10k events from Event Hub processed per second) we had 12 VMs (4 in each VMSS) and everything was working fine (for 2-3 hours) until I added another machine to one of the scale sets - I've increased number of VMs in 1st availability zone from 4 to 5, so overall number of VMs was still below maximum (15) specified in Load Balancer outbound rule definition.

**What happened**:
After ~1 minute in the Application Insights Live Metrics I've seen a lot of timeout exceptions from both Azure Redis & Azure CosmosDB.

Timeouts originated only from VMs in the same availability zone which I've scaled out (in this case 1st availability zone). Workloads on machines in another AZs were working fine.

This was reproduced twice today and we have seen similar behavior last week.

SNAT ports shouldn't be exhausted as each VM has 12k ports available and Load Balancer metrcis show avg usage of SNAT ports per VM is below 2k.

**What you expected to happen**:
Existing connections not to be dropped.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.7
- Size of cluster (how many worker nodes are in the cluster?): 12 (4 in each availability zone)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): .NET, HTTP microservices + Event Hub processor
- Others: nginx-ingress as ingress controllers

**Comment by kamilzzz** [comment]
Some additional informations:
- Azure CNI is used (in transparent mode I guess as it should be default right now), cluster was recreated one week ago
- AKS node image is up to date - AKSUbuntu-1804gen2containerd-2021.03.10
- After executing netstat -ano inside broken pod I can see Send-Q is growing:
![image](https://user-images.githubusercontent.com/32141632/112640143-58df9c00-8e41-11eb-852f-ad43679bb17e.png)
- Pod outbound connectivity is working (I can access Internet using curl)
- Using telnet I can connect to the same redis server

For me it looks like adding node might be breaking ports allocation on load balancer but I guess it shouldn't really work that way when port allocation strategy is changed to custom. So overall, I have no idea where the issue is, but we weren't able to fix that.

Also it seems this behavior is nondeterministic as yesterday we were able to add new node once without breaking connectivity.

**Comment by kamilzzz** [comment]
Looks like load balancer port allocation isn't an issue here as I observed the same behavior when I assigned a public IP per node for my VMSS (https://docs.microsoft.com/pl-pl/azure/aks/use-multiple-node-pools#assign-a-public-ip-per-node-for-your-node-pools)

Now I'm even more confused.

**Comment by palmerabollo** [comment]
@kamilzzz You describe the same issues we have been facing in the last few weeks. In case it's helpful, there is a [known service issue with tracking id 0TW1-9DZ in Azure](https://app.azure.com/h/0TW1-9DZ/4b67c4) that can cause intermittent, brief connectivity issues in your AKS nodes since Mar 9th. The affected regions are Brazil South; Central US; East US; East US 2; North Europe; West Europe; West US; West US 2. We have been told that a fix is already being rolled out.

**Comment by kamilzzz** [comment]
@palmerabollo Thanks for the information. 
Unfortunately link redirects me to the Service Health where I cannot find an issue with tracking id 0TW1-9DZ.

Also Resource Health blade for my cluster says that "There are no known issues affecting this kubernetes cluster."

**Comment by palmerabollo** [comment]
Yes, resource health doesn't say anything about the issue. I see the notice under the global Service Health section, not associated to a specific resource. I'm attaching the screenshots just in case it helps. Good luck, @kamilzzz .

![Screenshot 2021-03-27 at 08 26 38](https://user-images.githubusercontent.com/673420/112713638-8d516780-8ed6-11eb-8a0c-9dacfa36907c.png)
![Screenshot 2021-03-27 at 08 26 50](https://user-images.githubusercontent.com/673420/112713639-8e829480-8ed6-11eb-8a10-759f44ce1930.png)

**Comment by kamilzzz** [comment]
Thanks for the details again.

I'm not sure if I'm impacted by this issue as it states that mounting or unmounting persistent volumes to and from Kubernetes pods may cause intermittent connectivity issues.

I'm not using any PersistentVolume mounts directly, however I'm using KeyVault Secret Store CSI driver to mount Key Vault secrets (https://github.com/Azure/secrets-store-csi-driver-provider-azure)

**Comment by kamilzzz** [comment]
@palmerabollo do you have any update on the 0TW1-9DZ issue?

I would like to retest my case after this issue is fixed but as I said before I cannot see it on my subscription.

**Comment by seguler** [comment]
Yes - the issue was fixed everywhere on March 27th. Closing this issue but feel free to reopen if you continue to see the problem.

**Comment by kamilzzz** [comment]
Confirmed by running multiple load test with cluster autoscaler that issue no longer occurs.
