### ISSUE TITLE
AAD Pod Identity Preview - MIC Controllers Removed

### ISSUE THREAD

**Issue by alexl2012** [Azure/AKS#2221]
Hi,

Please see below issue raised regarding the design change/implementation of AAD Pod Identity. Please can the removal of MIC controllers and the new implementation be reconsidered?

https://github.com/Azure/aad-pod-identity/issues/1017

**Comment by alexl2012** [comment]
Hi , i have noticed that MIC controllers have been removed as Pod Identity has been added to AKS as an Addon.

Please please reconsider this design changes, it comes with some serious limitations which make it a lot less clear and a lot less workable to use.

For example before we had a chart file that lives in the repo and was part of the service that it belonged to, this was created as part of a deployment and we could also be sure of what it was and if any changes were made they were also part of the repo. Now we have a disjointed implementation where by a pipeline task has to assign managed identities to the cluster and then a separate deployment of helm charts applys the binding and other associated files, this is a much less integrated solution and feels regressive from the current model.

Another issue with the new implementation method is that if the cluster is having any other updates or changes we cannot change identities, which means our pipelines will be failing much more frequently as they will add an identity each time and any other changes being made to the cluster or other apps concurrently trying to add identities will have issues and likely fail.

This seems like an extreamly regressive solution and has many drawbacks that didnt previously exist. Please can this decision be reverted and MIC pods reintroduced.

Alternatively please implement this in a way that other cluster updates arent going to prevent changes to the identities being made.

Also i havent tried it yet but id imagine as we continuously deploy our arm templates for AKS this may remove any dynamically added identities causing yet another issue that we will then have to reassign them.

Please reconsider this frankly poor design change.

**Comment by miwithro** [comment]
We made a design decision to use Managed because of the Identity Assignment delay with Standard mode.

https://azure.github.io/aad-pod-identity/docs/configure/pod_identity_in_managed_mode/#why-use-managed-mode

With that being said.  We are working on Pod Identity V2 which is based on OIDC Federation and Service Account Token Volume Projection, so the MIC will not be utilized at all in V2.  We will announce a preview date when we can.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection

**Comment by alexl2012** [comment]
Whilst that does make sense, as the delay was problematic, the alternative is also with some different drawbacks as mentioned above. 

Will there be anything done to help address these in the V2 release? Such as maybe move the identities from the management object into the data object?

**Comment by miwithro** [comment]
We are still working through the design of V2 but the intention is to make the transition from V1 to V2 seemless.  @aramase
