### ISSUE TITLE
Cannot update my aks cluster service-principal

### ISSUE THREAD

**Issue by matteocusinato** [Azure/AKS#2226]
Hi, I'm trying to update the service-principal cluster because it has expired.
I'm following the guide [Update or rotate the credentials for Azure Kubernetes Service (AKS)](https://docs.microsoft.com/en-us/azure/aks/update-credentials#update-aks-cluster-with-new-service-principal-credentials)
I generated the new credentials but when I run the `az aks update-credentials` (with all the params)  command it gives me the following error:
Deployment failed. Correlation ID: 03c0d31a-d044-4ae3-8536-d2036dc7d9ee. AKS encountered an internal error while attempting the requested None operation. AKS will continuously retry the requested operation until successful or a retry timeout is hit. Check back to see if the operation requires resubmission. Correlation ID: a79311ee-d226-4cf7-b5fb-ca57bcbeb81e, Operation ID: c0e8ced6-03ab-4fcc-ba77-bd3db480d577, Timestamp: 2021-03-26T08: 47: 09Z.
<img width="1204" alt="Schermata 2021-03-26 alle 09 58 14" src="https://user-images.githubusercontent.com/19340970/112607994-18b8f300-8e1a-11eb-9cd6-e606d5ef883c.png">

**Environment**:
- Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}

- Size of cluster:
It is a single node cluster in a VM Scale Set

I have tried many times even on different days .. can anyone help me? Thank you

**Comment by miwithro** [comment]
@norshtein please assist.
