### ISSUE TITLE
locations.json is not included in api version later than 2019-08-01

### ISSUE THREAD

**Issue by njuCZ** [Azure/AKS#2230]
in api version early than 2019-08-01, there is a `locations.json` swagger file.  In this swagger file, it defines en endpoint:
`/subscriptions/{subscriptionId}/providers/Microsoft.ContainerService/locations/{location}/orchestrators`

But in later version, this file is missing. So in all generated sdk, this rest api is missing.

May I ask is this rest api deprecated? or just replaced by other rest api?

**Comment by miwithro** [comment]
@thomas1206 can you assist?

**Comment by qpetraroia** [comment]
Hi @njuCZ, 

This API was deprecated because it was actually a part of "ACS". As Azure Container Services moved over to Azure Kubernetes Service, this API was dropped. Thanks for bringing this to our attention, we will work on providing an equivalent to AKS.
