### ISSUE TITLE
AKS service CIDR collapsed with AKS reserved CIDR

### ISSUE THREAD

**Issue by lissff** [Azure/AKS#2234]
**What happened**:
Cluster creation failure with no reason, when AKS service CIDR collapsed with AKS reserved CIDR.

**What you expected to happen**:
It took us days to realize the root cause for AKS creation failure is because of the conflicted CIDR. I know the documentations specified the limitation:
AKS clusters may not use 169.254.0.0/16, 172.30.0.0/16, 172.31.0.0/16, or 192.0.2.0/24 for the Kubernetes service address range, pod address range or cluster virtual network address range.
https://docs.microsoft.com/en-us/azure/aks/configure-kubenet#prerequisites

But can we add some hint in portal or Azure CLI, or more information in the error log that could lead us to the right direction?

**How to reproduce it (as minimally and precisely as possible)**:
Create AKS with service CIDR 172.30.0.0/16,

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by paulgmiller** [comment]
We should validate this. Can you share more about what you're seeing in terms of what you're doing and the error message you get. WIth cli I got the right thing
```
 az aks create -g paultest -n badserivcecidr  --service-cidr 172.30.0.0/16 --network-plugin kubenet
Operation failed with status: 'Bad Request'. Details: NetworkProfile.ServiceCidr 172.30.0.0/16 is invalid. Please choose one that does not overlap 169.254.0.0/16, 172.30.0.0/16, 172.31.0.0/16, 192.0.2.0/24
```

**Comment by lissff** [comment]
@paulgmiller sorry for late response, it is azure cni, and if the subnet /peered network have conflict then apiserver would fail to get started.

**Comment by paulgmiller** [comment]
We don't check peered networks. Can you give me a more concrete example?
