### ISSUE TITLE
Cannot add "spot" confidential computing  node pool to AKS cluster

### ISSUE THREAD

**Issue by osuketh** [Azure/AKS#2235]
**What happened**:
By default, the Spot node pool adds a taint of `kubernetes.azure.com/scalesetpriority=spot:NoSchedule` .
Since custom toleration cannot be set for the daemonset of sgx-plugin,  the sgx-plugin pod is not scheduled for the Spot Confidential node and the SGX driver cannot be used.

**What you expected to happen**:
sgx-plugin daemonset also schedules pods to spot node pool.

**How to reproduce it (as minimally and precisely as possible)**:
```sh
az aks create \
    -g rg-name \
    --name cluster-name \
    -a confcom \
    --node-count 1 \

az aks nodepool add \
     --cluster-name cluster-name \
     --name confcompool \
     -g rg-name \
     --node-vm-size Standard_DC2s_v2 \
     --node-count 1 \
     --priority Spot \
     --eviction-policy Deallocate
```

```
$ kubectl describe ds sgx-plugin -n kube-system
Name:           sgx-plugin
Selector:       app=sgx-plugin
Node-Selector:  <none>
Labels:         addonmanager.kubernetes.io/mode=Reconcile
                app=sgx-plugin
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by agowdamsft** [comment]
Update: This support for spot and confidential computing nodes with addon is being check in and should be rolling out in next 2-3 weeks timeframe. I will promptly update this issue when it hits all regions. Thanks for your patience.
