### ISSUE TITLE
WinDSR enabled by default in 1.20+ can it be disabled?

### ISSUE THREAD

**Issue by SteveCurran** [Azure/AKS#2238]
**What happened**: WinDSR enabled by default in 1.20+ causing nginx and nginx-ingress to no longer work

**What you expected to happen**: Can WinDSR be disabled or added as an "enable-addon" option when creating a cluster?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: Linux/Windows node pools
- Kubernetes version (use `kubectl version`): 1.20.2
- Size of cluster (how many worker nodes are in the cluster?) 4
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by miwithro** [comment]
@paulgmiller

**Comment by keikhara** [comment]
@SteveCurran as for now, we do not allow disabling this. As mention on yammer, please open a case and so we can go thru investigation. @AbelHu

**Comment by AbelHu** [comment]
We are trying to reproduce this issue and investigate it.

**Comment by AbelHu** [comment]
@SteveCurran WinDSR is disabled by default in all regions.

**Comment by SteveCurran** [comment]
@AbelHu can give some clarification on this? So WinDSR is now disabled by default in AKS 1.20+.  How does this affect using Calico with Windows? Is WinDSR still required for Calico with Windows?

**Comment by AbelHu** [comment]
@SteveCurran WinDSR is disabled by default in AKS 1.20+ but it is still enabled if Calico with Windows is used because Calico Windows requires WinDSR.
