### ISSUE TITLE
Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp 10.240.0.4:10250: getsockopt: connection timed out

### ISSUE THREAD

**Issue by mfaizanse** [Azure/AKS#224]
Hi,
I created a new k8s cluster 1.8.7 on AKS today. When I tried to install a helm chart it gave me the following error:
`Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp 10.240.0.4:10250: getsockopt: connection timed out`

What be the issue and how to resolve it?

**Comment by pkelleratwork** [comment]
Ditto - I receive the exact same error when using helm. I commented on issue #232 too.  Thanks for posting this so we can follow.

**Comment by Nirmalyasen** [comment]
Running into the same issue trying to run helm against a 1.9.2 AKS cluster in Azure

helm ls
Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp 10.240.0.4:10250: getsockopt: connection timed out

**Comment by ITSzoran** [comment]
Open port 10250 on worker node using
sudo firewall-cmd --zone=public --add-port=10250/tcp --permanent
sudo firewall-cmd --reload 

i have the some issue and i solve on this way

**Comment by DivineOps** [comment]
+ to ITSzoran's answer:
Worker node means local machine
If you are on Windows, the PowerShell command (run with admin permissions) is:
`netsh advfirewall firewall add rule name="Open Port 10250" dir=in action=allow protocol=TCP localport=10250 `

**Comment by dcfsc** [comment]
We had a AKS node simply stop responding and got this message any time we tried to start the Dashboard. I had to kill the node VM and scale the cluster. Eventually it restarted the Dashboard and this error went away. 
Not quite a firewall issue but something to keep in mind.

**Comment by jnoller** [comment]
Stale issue, work around provided. For future reference errors like: "getsockopt: connection timed out" can be traced back to firewalls/ports/NSG rules, or in the case of AKS, if the API server is down or unreachable (either due to service issues or firewalls/ports/NSG rules)

**Comment by SychevIgor** [comment]
didn't help me
VM dropped, Cluster scaled. This partiacular error goes away, but Dashboard still is not accessible.

aks version 1.14

**Comment by turowicz** [comment]
@SychevIgor @jnoller  same here

**Comment by akazemis** [comment]
still having the same issue, the thing is it was working until it didn't!

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by alexmg** [comment]
I'm also seeing the same issue regularly from an Azure DevOps pipeline run on hosted agents. Looking at the logs from various containers *inside* the cluster I can see they are also failing to connect to the API.

**Comment by maadtechie** [comment]
Having the same issue on AKS from time to time, we've noticed that "tunnelfront" in kube-system namespace restarts and fails liveness probe. Deleting that pode (restarting) helps to solve the problem.

**Comment by jayant12489** [comment]
Hi Please check localy then reply 
Its not firewall-port issue its issue to connectivity with kublet & docker docker doesn't recognized port 10250 means docker doesn't map with this port so wait for updation after again try it...

Thanks
