### ISSUE TITLE
Cannot update authorized ip ranges for cluster with BYO identity

### ISSUE THREAD

**Issue by denniszielke** [Azure/AKS#2241]
**What happened**:
Created a cluster with BYO control plane identity.
When trying to set the authorized ip ranges (via portal or terraform) I get the following error message
"Invalid value for the identities '/subscriptions/xxx-id/resourceGroups/resource-group-name/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name'. The 'UserAssignedIdentities' property keys should only be empty json objects, null or the resource exisiting property."

**What you expected to happen**:
Updating authorized ip ranges should work.

**How to reproduce it (as minimally and precisely as possible)**:
```
az group create -l WestEurope  -n aks-group
id=$(az identity create --name control-plane-id --resource-group aks-group --query id -o tsv)
az aks create -g aks-group -n aks --enable-managed-identity --assign-identity $id --no-ssh-key
```

Update the ranges in portal or terraform - get error message

Update via CLI seems to work:
```
az aks update -n aks -g aks-group --api-server-authorized-ip-ranges 87.120.31.21/32
```

Try to delete the ip ranges from the portal- same error message again.

**Environment**:
- Kubernetes version (use `kubectl version`): Seems not related to Kubernetes version
- Size of cluster (how many worker nodes are in the cluster?): Seems unrelated

**Comment by miwithro** [comment]
@norshtein please investigate.

**Comment by miwithro** [comment]
This command worked for me.  Can you tell me if you are still having this issue?  If so, what CLI version are you running?
