### ISSUE TITLE
Agent pool vmSize doesn't include e v4

### ISSUE THREAD

**Issue by jabbera** [Azure/AKS#2243]
**What happened**:
Bicep is shaming me because Standard_E80ids_v4 isn't listed here: https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters?tabs=json#managedclusteragentpoolprofile-object

Edit: Standard_D16ds_v4 is missing as well.

```

resource highmempool 'Microsoft.ContainerService/managedClusters/agentPools@2021-02-01' = {
  name: '${aks.name}/highmempool'
  properties: {
    vmSize: 'Standard_E80ids_v4'
    vnetSubnetID: nodeSubnetId
    minCount: 0
    count: 0
    maxCount: 10
    osDiskType: 'Ephemeral'
    type: 'VirtualMachineScaleSets'
    mode: 'User'
    enableAutoScaling: true
    nodeTaints: [
      'hub.jupyter.org/dedicated=highmem:NoSchedule'
    ]
    nodeLabels: {
      'hub.jupyter.org/node-purpose': 'user'
    }
  }
}
```

**What you expected to happen**:
Not to be shamed.

**Comment by alexeldeib** [comment]
This is a spec bug, we removed the strict validation RP side to be "whatever your subscription supports". However we can't model that as an enum properly with a dynamic number of values per subscription. I'll PR to update the spec to use a string.

https://github.com/Azure/azure-rest-api-specs/pull/13763

**Comment by alexeldeib** [comment]
@jabbera this was only a spec bug, right? since the enum was already modeled as string, this should work fine in the SDKs even with the spec bug? e.g. in Go, this works

```go
package main

import (
	"fmt"

	"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-12-01/containerservice"
)

func main() {
	size := containerservice.VMSizeTypes("Standard_E80ids_v4")
	fmt.Printf("%#+v\n", size)
}
```

the spec fix is merged but the new SDKs haven't been generated. wasn't sure if this was fine to close or if there were downstream issues.

**Comment by jabbera** [comment]
@alexeldeib fine to close. It's annoying in bicep because it emits a warning in vscode and stderr from console but nothing atrocious.

**Comment by alexeldeib** [comment]
👍 I think the new spec will make bicep happy, but I'm not sure how the project pulls in updates. It won't be able to do static validation against an enum because it's dynamic now, but if you/they want to know the logic we use against Azure APIs I'm happy to share more details.
