### ISSUE TITLE
Error Creating Private AKS Cluster in Portal - vmssCSE (ExitCode 52)

### ISSUE THREAD

**Issue by marinmuso** [Azure/AKS#2244]
**What happened**:

Deployment of private cluster fails with the following message:

```
{
    "status": "Failed",
    "error": {
        "code": "CreateVMSSAgentPoolFailed",
        "message": "AKS encountered an internal error while attempting the requested Creating operation. AKS will continuously retry the requested operation until successful or a retry timeout is hit. Check back to see if the operation requires resubmission. 
    }
}
```

The virtual machine scale set reports that it has failed with the following message:

`
VM has reported a failure when processing extension 'vmssCSE'. Error message: "Enable failed: failed to execute command: command terminated with exit status=52 [stdout] { "ExitCode": "52", "Output": "Wed Mar 31 18:52:17 UTC 2021,aks-agentpool-22943995-vmss000000\nConnection to mcr.microsoft.com 443 port [tcp/https] succeeded!\n● kubelet.service - Kubelet\n Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)\n Active: active (running) since Wed 2021-03-31 18:52:48 UTC; 3min 24s ago\n Main PID: 4702 (kubelet)\n Tasks: 15 (limit: 4915)\n CGroup: /system.slice/kubelet.service\n └─4702 /usr/local/bin/kubelet --enable-server --node-labels=kubernetes.azure.com/role=agent,agentpool=agentpool,storageprofile=managed,storagetier=Premium_LRS,kubernetes.azure.com/cluster=MC_RGP_aks-use-core-dv-prv_eastus,kubernetes.azure.com/mode=system,kubernetes.azure.com/node-image-version=AKSUbuntu-1804gen2containerd-2021.03.17 --v=2 --container-runtime=remote --runtime-request-timeout=15m --container-runtime-endpoint=unix:///run/containerd/containerd.sock --volume-plugin-dir=/etc/kubernetes/volumeplugins --address=0.0.0.0 --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --azure-container-registry-config=/etc/kubernetes/azure.json --cgroups-per-qos=true --client-ca-file=/etc/kubernetes/certs/ca.crt --cloud-config=/etc/kubernetes/azure.json --cloud-provider=azure --cluster-dns=10.0.0.10 --cluster-domain=cluster.local --dynamic-config-dir=/var/lib/kubelet --enforce-node-allocatable=pods --event-qps=0 --eviction-hard=memory.available<750Mi,nodefs.available<10%,nodefs.inodesFree<5% --feature-gates=RotateKubeletServerCertificate=true --image-gc-high-threshold=85 --image-gc-low-threshold=80 --image-pull-progress-deadline=30m --keep-terminated-pod-volumes=false --kube-reserved=cpu=140m,memory=2662Mi --kubeconfig=/var/lib/kubelet/kubeconfig --max-pods=30 --network-plugin=cni --node-status-update-frequency=10s --non-masquerade-cidr=0.0.0.0/0 --pod-infra-container-image=mcr.microsoft.com/oss/kubernetes/pause:1.3.1 --pod-manifest-path=/etc/kubernetes/manifests --pod-max-pids=-1 --protect-kernel-defaults=true --read-only-port=0 --resolv-conf=/run/systemd/resolve/resolv.conf --rotate-certificates=false --streaming-connection-idle-timeout=4h --tls-cert-file=/etc/kubernetes/certs/kubeletserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256 --tls-private-key-file=/etc/kubernetes/certs/kubeletserver.key\n\nMar 31 18:56:12 aks-agentpool-22943995-vmss000000 kubelet[4702]: E0331 18:56:12.177931 4702 kubelet.go:2186] node \"aks-agentpool-22943995-vmss000000\" not found\nMar 31 18:56:12 aks-agentpool-22943995-vmss000000 kubelet[4702]: E0331 18:56:12.278172 4702 kubelet.go:2186] node \"aks-agentpool-22943995-vmss000000\" not found\nMar 31 18:56:12 aks-agentpool-22943995-vmss000000 kubelet[4702]: E0331 18:56:12.378411 ", "Error": "", "ExecDuration": "236" } [stderr] " More information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot
`

**What you expected to happen**:

Private AKS Cluster is successfully provisioned.

**How to reproduce it (as minimally and precisely as possible)**:

1. Log into Azure Portal
2. Search for Kubernetes services
3. Add Kubernetes cluster
-- Select Azure CNI as the Network configuration and use existing Vnet/Subnet
-- Enable private cluster
-- Everything else is default

**Anything else we need to know?**:

Our deployment is in a Vnet that uses custom DNS Servers (which are hosted in a separate Vnet). These two Vnets are peered together.

**Environment**:
- Kubernetes version: 1.19.7
- Size of cluster: 3

**Comment by feiskyer** [comment]
I don't see similar issues recently. Please open a support ticket if you see it again.
