### ISSUE TITLE
AKS cluster enters failure state if the vNet changes resource groups

### ISSUE THREAD

**Issue by nicksc423** [Azure/AKS#2252]
**What happened**:
I am currently unable to update my service principle for my AKS cluster. I am trying to update the credentials by following this guide: https://docs.microsoft.com/en-us/azure/aks/update-credentials

Whenever I run the az aks update-credentials step I get the following error:

Deployment failed. Correlation ID: de7d345a-009b-40f2-95c7-466b9157e481. Category: ClientError; SubCode: InvalidResourceReference; Dependency: Azure Resource Manager; OrginalError Code="InvalidResourceReference" Message="Resource /subscriptions/xxxx/resourceGroups/ICMUS-STAGING/providers/Microsoft.Network/virtualNetworks/ICMUS-STAGING referenced by resource /subscriptions/xxxx/resourceGroups/MC_ICMUS-STAGING-CLUSTER_ICMUS-STAGING-CLUSTER_WESTUS2/providers/Microsoft.Compute/virtualMachineScaleSets/aks-default-41547229-vmss was not found. Please make sure that the referenced resource exists, and that both resources are in the same region." Details=[{"code":"NotFound","message":"Resource /subscriptions/xxxx/resourceGroups/ICMUS-STAGING/providers/Microsoft.Network/virtualNetworks/ICMUS-STAGING not found."}]

I find this error message to be particularly odd

If I go into the Resource Explorer on the portal and navigate to the VMSS referenced in the error message, there is no reference to the missing virtualNetworks. This may be because I moved the VNET to a new resource group. The Resource Explorer in the portal reflects this change, but the CLI is not.

**What you expected to happen**:

I should be able to move my vNet/Subnet to a new resource group without breaking my AKS cluster

**How to reproduce it (as minimally and precisely as possible)**:
Create 2 resource groups.  In one resource group create the vNet & subnet, in the other resource group setup an AKS cluster.  Now move the vNet & subnet into the resource group with the AKS cluster.  Now try to update the service principle attached to the AKS cluster

**Comment by nicksc423** [comment]
I also tried to use the REST API to create a new NodePool in the correct Subnet: https://docs.microsoft.com/en-us/rest/api/aks/agentpools/createorupdate#linuxosconfig

I get the following error:
`{
  "code": "NotFound",
  "message": "Failed to get a VNet: icmus-staging."
}`

This is with setting the vnetSubnetID field to the ID of the vNet that I changed resource groups

**Comment by nicksc423** [comment]
I did a little more investigation and I think I know what happened. When I moved the vNet & associated subnets to a new resource group it looks like it did not update the vnetSubnetID in the default Nodepool/agentPoolProfiles of the cluster but it did update in the VMSS.

If I go to the Resource Explorer and navigate to my cluster I can see that in properties.agentPoolProfiles for my default Nodepool/agentPoolProfiles the vnetSubnetID wasn't updated to point at the resource group that the vnet & subnet were moved to. I recreated the resource group and moved the vNet back and the cluster is in the healthy state again.

**Comment by nicksc423** [comment]
It would be nice to have this noted in the documentation somewhere.  It's not explicitly stated that you cant move the the vNet that a nodepool for an AKS cluster is in here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/move-support-resources#microsoftcontainerservice

(I also wonder if you could just update the vnetSubnetID  and everything would work, since the VMSS works fine despite the cluster being moved into a failed state)

**Comment by justindavies** [comment]
Hi @nicksc423 thanks for bringing this to our attention, and apologies for the delay in us getting to this.  I'll take a look and get back to you

**Comment by qpetraroia** [comment]
Hi @nicksc423

Are you still having these issues?

@justindavies, have you looked into this issue?

**Comment by heoelri** [comment]
> It would be nice to have this noted in the documentation somewhere. It's not explicitly stated that you cant move the the vNet that a nodepool for an AKS cluster is in here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/move-support-resources#microsoftcontainerservice
> 
> (I also wonder if you could just update the vnetSubnetID and everything would work, since the VMSS works fine despite the cluster being moved into a failed state)

I think this is documented here: https://docs.microsoft.com/en-us/azure/aks/faq#can-i-move-my-aks-cluster-or-aks-infrastructure-resources-to-other-resource-groups-or-rename-them

> **Can I move my AKS cluster or AKS infrastructure resources to other resource groups or rename them?**
Moving or renaming your AKS cluster and its associated resources isn't supported.

It would be nice if there would be a flag or tag for resources that do not support moving or renaming, automatically set by for example AKS during deployment, and if ARM would respond with a warning when trying to move these resources or prevent it at all.
