### ISSUE TITLE
Pod Identity Workflow is clunky

### ISSUE THREAD

**Issue by jabbera** [Azure/AKS#2253]
**What happened**: Per this documentation: https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity#assign-permissions-for-the-managed-identity reader needs to be assigned to the VMSS to the AKS managed resource group. I'm trying to this in an ARM template (bicep actually) and the name of that group doesn't seem to be available. This makes the assignment impossible inside the template as far as I can tell. 

**What you expected to happen**: AKS to do this for me. It owns the group no? At least to be able to do this in my template

**How to reproduce it (as minimally and precisely as possible)**: Read the directions.

**Comment by miwithro** [comment]
We are currently working on Pod Identity V2.  We should have something out in preview in the summer time.   V2 is based on OIDC Federation and Service Account Token Volume Projection.
