### ISSUE TITLE
Same IPs for different ingress in different namespaces

### ISSUE THREAD

**Issue by hakrac** [Azure/AKS#2255]
**What happened**:
I am using an AKS cluster with two custom namespaces, each having a deployment, service and an ingress via ingress-nginx.

**What you expected to happen**:
After setup, I noticed that both ingress are using the same External IP, which is not intended. I want to reach each namespace through it's own ingress without interfering with the other.

**How to reproduce it (as minimally and precisely as possible)**:
Install `ingress-nginx` via helm and install the controller into each namespace. Apply the deployments and services to each namespace.

**Anything else we need to know?**:
I am using dynamicly assigned IP addresses.

**Environment**:
- Kubernetes version (use `kubectl version`): Client v1.20.4-dirty; Server v1.18.14
- Size of cluster (how many worker nodes are in the cluster?): 2 Nodes 
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
General setup of two Node.js HTTP webservers in their own namespace

**Comment by EPinci** [comment]
Hey, when using multiple ingress controller, also the ingress objects need to be annotated with the class of the controller you want to attach it to, regardless of namespaces. (see https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/)
Are you annotating the ingress objects?
