### ISSUE TITLE
Make changes to FelixConfiguration on AKS creation

### ISSUE THREAD

**Issue by fooxytv** [Azure/AKS#2258]
Recently moved over to Calico from Azure NPM, I wanted to expose the metrics and needed to set the PrometheusMetricsEnabled to true via the FelixConfiguration file.

Is this flag possible to do in code when creating the AKS cluster?

https://docs.projectcalico.org/reference/felix/configuration
https://github.com/Azure/aks-engine/issues/1520

**Comment by miwithro** [comment]
@SnehaAgrawal-MSFT can you answer this one?

**Comment by phealy** [comment]
When you deploy with `--network-plugin kubenet --network-policy calico`, calico is deployed using the operator. Per the information on the Felix Configuration page, when you're using the operator you can't make configuration file changes directly. Please use the [FelixConfiguration object](https://docs.projectcalico.org/reference/resources/felixconfig) via `calicoctl` or `kubectl` to update your configuration after the cluster is deployed and your prometheus instance is ready.
