### ISSUE TITLE
Question: How to get K8s Connection Config from Deployment?

### ISSUE THREAD

**Issue by RohanNagar** [Azure/AKS#226]
I know that you can get credentials to connect to the K8s cluster using

```bash
az aks get-credentials --resource-group=myResourceGroup --name=myAKSCluster
```

But are there other ways to get the config information, particularly from a .NET Core application? I'm asking because I'm looking to use this Nuget Package: https://github.com/kubernetes-client/csharp to connect to my AKS cluster with and create deployments.

Or, how would you go about getting this information when connecting using the Go client? The same information should apply to this case.

Any pointers would be appreciated.

**Comment by RohanNagar** [comment]
Looks like I can use the `GetAccessProfiles` endpoint from ARM, which should return a base-64 encoded Kubernetes configuration file.

See more here: https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/getaccessprofiles

**Comment by ElanHasson** [comment]
Nice ! I'm using the same library. I was just going to use service account tokens for my pod.

Did you try that route?

**Comment by RohanNagar** [comment]
@ElanHasson Like a service principal token? Is there a way to connect to K8s using that library with just a token?

**Comment by RohanNagar** [comment]
Actually, I found an even better way. Use the `SdkContext` class to authenticate to Azure, create a new `IAzure` object, and use that to get your Kubernetes cluster (`IKubernetesCluster` object). From there, you can get the `UserKubeConfigContext` property and convert that to a string. Then you'll pass that string into the `BuildConfigFromConfigFile()` method in the `KubernetesClientConfiguration` class. After that you're connected!

Example:

```cs
var credentials = SdkContext.AzureCredentialsFactory.FromServicePrincipal(clientId,
                    clientSecret,
                    tenantId, 
                    AzureEnvironment.AzureGlobalCloud);

var azure = Azure.Configure()
                 .Authenticate(credentials)
                 .WithSubscription(subscriptionId);

IKubernetesCluster kubernetesCluster = this.azure.KubernetesClusters.GetByResourceGroup(resourceGroupName, clusterName);

var buffer = kubernetesCluster.UserKubeConfigContent;
var configFile = Encoding.UTF8.GetString(buffer, 0, buffer.Length);

var config = KubernetesClientConfiguration.BuildConfigFromConfigFile(configFile, null, null);
IKubernetes client = new Kubernetes(config);

// Now use your client
```

**Comment by ElanHasson** [comment]
I meant using a service account in Kubernetes. Use that token from there to access the apicontroller in k8s.

**Comment by RohanNagar** [comment]
@ElanHasson that should work too! It might be better suited for a service running inside the cluster.

**Comment by ElanHasson** [comment]
Yeah, my app is running within the cluster.
