### ISSUE TITLE
node pool vms become invalid and autoscale stops working

### ISSUE THREAD

**Issue by Morriz** [Azure/AKS#2262]
We have consistent problems with the autoscaler and want to report a bug report as this is not manageable through separate support requests. The following problems seem to always occur under certain conditions:

**What happened**:

1. when a node pool's version slides out of range of supported patch versions, the vmms instances become invalid (Latest model: no)
2. autoscaler stops working even though memory is maxing out at 93%
3. pods can't be evicted

**What you expected to happen**:

No problems with scaling

**How to reproduce it (as minimally and precisely as possible)**:

Run AKS with standard system node pool (why tf does it not show in the portal what type of node pool it is??), and wait some weeks to see the k8s version slide out of supported range. See that the vms show problems (orange icons), and that the autoscaler does not respond any more.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.7 master, 1.19.3 node pool (1.19.7 not offered)
- Size of cluster (how many worker nodes are in the cluster?) 8

**Comment by marwanad** [comment]
@Morriz What autoscaler are you referring to here? The kubernetes autoscaler or the VMSS autoscaler? The k8s autoscaler doesn't use memory usage as a signal to scale and the only trigger for a scale up is pending pods.

**Comment by Morriz** [comment]
That would be the k8s autoscaler of course. As an AKS user I expect no dealings with lower level infra ;)

Is there an option to enable over provisioning for a k8s cluster? To always have some resources available?

**Comment by marwanad** [comment]
@Morriz appreciate you following the guidance 😄 

You can get [overprovisioning](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler) to work with cluster autoscaler but you'll have to set that one up yourself. Basically the idea is that you have a bunch of low priority pods that are sitting there in your cluster. When the are other "real workload" pending pods, those low pri pods will be pre-empted and go into Pending state forcing another scale-up and keeping that buffer size. You can also configure [cluster-proportional-autoscaler
](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler) to have your buffer size dynamically grow with the number of nodes.

**Comment by marwanad** [comment]
@paulgmiller @gtxistxgao for the latest model issue maybe?

**Comment by Morriz** [comment]
@marwanad we already have an over provisioner chart deployed (see [redkubes/otomi-core/charts/cluster-overprovisioner](https://github.com/redkubes/otomi-core/tree/master/charts/cluster-overprovisioner)).

I was just asking because we could benefit from more finely tuned vmms overprovisioning instead

**Comment by danimal521** [comment]
@marwanad can you please respond to @Morriz question

**Comment by miwithro** [comment]
@Morriz is this still an issue?  We have many multiple enhancements to the CA since April.  

Most notably.

https://github.com/Azure/AKS/releases/tag/2021-07-22

Behavioral Changes
Cluster autoscaler will now enforce the minimum count in cases where the actual count drops below that. For example, Spot eviction or changing the minimum count value from the AKS API. In the past, the autoscaler operated and respected the minimum count but never interfered to enforce it if external factors affect it.
