### ISSUE TITLE
Azure CNI: Support for reserving pod ip address/ specifying ip address pool

### ISSUE THREAD

**Issue by ryanmcafee** [Azure/AKS#2266]
In our Kubernetes production environment, we are deploying an application that will be accessing a database on premise. We have provisioned the Kubernetes cluster with Azure CNI Networking and a /18 cidr. Our security team is wanting to create a firewall rule for a much more narrow cidr range for pci compliance purposes. To my knowledge and research, it's not possible to reserve a ip address or subpool of ip addresses that would be assigned via azure-vnet-ipam, but I know it's a supported feature of Calico CNI. Is there a way to use a smaller ip address pool for a deployment or to reserve a group of ip addresses for a deployment with the azure-vnet-ipam cni provider?

Links to feature documentation in Calico CNI:
https://docs.projectcalico.org/networking/legacy-firewalls
https://docs.projectcalico.org/networking/use-specific-ip

**What happened**: Unable to specify a ip pool that we would like the pod ip for a deployment to be assigned from or specify ip address block to be assigned to deployment.

**What you expected to happen**: Being able to control ip allocation more specifically for a deployment.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.7 with Azure CNI Networking
- Size of cluster (how many worker nodes are in the cluster?) 5
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Microservices, Kube Prometheus Stack, ELK, Nginx Ingress Controller, AAD-Pod-Identity

**Comment by jabbera** [comment]
@ryanmcafee I'm assuming you don't use a dedicated node pool? Something like this: https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#dynamic-allocation-of-ips-and-enhanced-subnet-support-preview

**Comment by ryanmcafee** [comment]
I guess using a 2nd node pool with a smaller subnet size could work after that leaves beta, but preferably we would prefer to not have to deploy an additional node pool unless absolutely necessary.

**Comment by aanandr** [comment]
Hi @ryanmcafee - we quite recently announced a feature that lets you use a separate subnet for Pod IPs. You can also specify a different Pod subnet for every node pool. More info here - https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#dynamic-allocation-of-ips-and-enhanced-subnet-support-preview
This feature is in preview and available only in one region but we plan to expand region coverage in the coming months.

**Comment by palma21** [comment]
Marking as solved for now with the above workarounds and dup for #2189
