### ISSUE TITLE
pod eviction timeout on node failure

### ISSUE THREAD

**Issue by junpark12** [Azure/AKS#227]
Hi.
In the case of node failure, we need to detect it quickly then move pods to another node.
Default values are too high.
How can we change following configuration in AKS?

node-monitor-period
node-monitor-grace-period
node-status-update-frequency
pod-eviction-timeout

thanks.

**Comment by engsabry** [comment]
You can just Edit kube-controller-manager.yaml file ,  default  path
`  /etc/kubernetes/manifests/kube-controller-manager.yaml`
ex:
 vi /etc/kubernetes/manifests/kube-controller-manager.yaml

 
```
  - command:
    - kube-controller-manager
    - --pod-eviction-timeout=10s_

```

**Comment by junpark12** [comment]
@engsabry  thanks for response.
But  i don't see any files under manifests folder.
root@aks-nodepool1-14644054-0:/etc/kubernetes/manifests# ls

**Comment by msabry-dtp** [comment]
@junpark12 oh sorry, If you have kubectl installed, could you try:
 `kubectl get -n kube-system pod | grep kube-controller-manager | cut -f1 -d ' ' | xargs kubectl edit -n kube-system pod`

**Comment by engsabry** [comment]
@junpark12 oh sorry, If you have kubectl installed, could you try:
 

`kubectl get -n kube-system pod | grep kube-controller-manager | cut -f1 -d ' ' | xargs kubectl edit -n kube-system pod`

**Comment by junpark12** [comment]
@engsabry  I can't grep "controller-manager" pod. 
kubectl get -n kube-system pod
NAME                                    READY     STATUS    RESTARTS   AGE
heapster-584cf4954-wdd5j                2/2       Running   2          2d
kube-dns-v20-7d697d6c4d-f5qn9           3/3       Running   0          12m
kube-dns-v20-7d697d6c4d-vghgt           3/3       Running   3          2d
kube-proxy-4hc8n                        1/1       Running   23         55d
kube-proxy-5s2v5                        1/1       Running   23         55d
kube-proxy-lf47t                        1/1       Running   22         55d
kube-svc-redirect-nqbpg                 1/1       Running   24         55d
kube-svc-redirect-r6xxd                 1/1       Running   24         55d
kube-svc-redirect-vh4p8                 1/1       Running   23         55d
kubernetes-dashboard-5f766f7944-jhknl   1/1       Running   2          2d
tunnelfront-5c5f484644-2gqcv            1/1       Running   0          12m

https://github.com/Azure/AKS/issues/114

**Comment by white-cloud** [comment]
Hello @engsabry please may i know how to set up  node-status-update-frequency in kubelet because i can find no config file for kubelet so i was wondering how i can configure this kubelet parameter.

Thank you.
