### ISSUE TITLE
Kubernetes audit policy file - documentation

### ISSUE THREAD

**Issue by kaplik** [Azure/AKS#2272]
**What happened**:
Definition of Kubernetes audit policy is not published.

**What you expected to happen**:
Kubernetes audit policy definition file should be published in AKS documentation.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
In AKS documentation [available here](https://docs.microsoft.com/en-us/azure/aks/view-control-plane-logs#log-categories) is specified

> - The kube-audit category contains all audit log data for every audit event, including get, list, create, update, delete, patch, and post.
> - The kube-audit-admin category is a subset of the kube-audit log category. kube-audit-admin reduces the number of logs significantly by excluding the get and list audit events from the log.

but no exact definition of [kubernetes audit policy](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy) is available.

Ideally the YAML specification of kubernetes audit policy for kube-apiserver should be linked in to AKS documentation.

**Environment**:
not relevant

**Comment by qpetraroia** [comment]
Hi @kaplik,

@zr-msft, can you take a look at this?
