### ISSUE TITLE
AKS health check time before Auto Repair

### ISSUE THREAD

**Issue by Gopinath-Radhakrishnan** [Azure/AKS#2273]
**What happened**:  AKS currently checks the node health within a 10 min timeframe before triggering Auto Repair. 

**What you expected to happen**:  Customer need to have the ability to change the timeframe. Like we should be able to reduce it to 1 min if required"

**How to reproduce it (as minimally and precisely as possible)**:  There was a production outage when one of the server in VMSS was unhealthy due to an Network device failure at Azure and this caused a production outage as the node that failed was an active node receiving traffic plus it had pod having DNS running. 

**Anything else we need to know?**:

**Environment**: Production
- Kubernetes version (use `kubectl version`): 1.18.8
- Size of cluster (how many worker nodes are in the cluster?) AutoScales between 25 to 40 majority of the time. 
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Hosts Mobile App
- Others:

**Comment by Gopinath-Radhakrishnan** [comment]
anyone from Microsoft can help here please?

**Comment by Gopinath-Radhakrishnan** [comment]
anyone from Microsoft can help here please?

**Comment by seguler** [comment]
Hi @Gopinath-Radhakrishnan 

We have a plan to further optimize the 10-min threshold so we could help customers avoid outages like this. 

In the meantime, why was the application still receiving traffic? When the node is not reachable, the node will be taken out of the load balancer backend and the pod should not receive traffic. 

Also, was your pod not automatically scheduled to another node? When a node is in not ready state, after the pod eviction timeout, the pod will be evicted and recreated on a healthy node. Thanks to these two, you shouldn't really care about the 10-min threshold. Could you detail what the issue exactly was and what was observed?
