### ISSUE TITLE
Customize node configuration: add pod-max-pids to avoid PID exhaustion

### ISSUE THREAD

**Issue by tdihp** [Azure/AKS#2276]
**What happened**:

Applications can allocate too many threads, triggering EAGAIN when kubelet/containerd tries to create new thread with pthread_create. We observe PLEG failures and nodes not ready due to some offending application.

**What you expected to happen**:

Add [pod-pid-limits](https://kubernetes.io/docs/concepts/policy/pid-limiting/#pod-pid-limits) as an option for [custom node configuration](https://docs.microsoft.com/en-us/azure/aks/custom-node-configuration). Configure a smaller value for pods should provide safety for node readiness.

**How to reproduce it (as minimally and precisely as possible)**:

Simply add a testing Python pod in 2 steps and wait for around 6 mins to wait for node not ready:

``` bash
kubectl run -it --rm --restart=Never --image=python:3-slim python -- python
```

``` Python
import time

def thread_burst(n=1000, t=600):
    import threading
    
    threads = []
    for i in range(n):
        thread = threading.Thread(target=time.sleep, args=(t,))
        try:
            thread.start()
        except Exception as e:
            print('got exception when starting thread: %s' % e)
            break
        threads.append(thread)
    return threads

def main():
    threads = []
    while True:
        print('bursting threads')
        threads.extend(thread_burst(n=1000))
        time.sleep(10)

main()
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.7

**Comment by tdihp** [comment]
related: #323

**Comment by justindavies** [comment]
A PR has been raised to enable this in the azure cli for the next release, and the documentation will also be updated.  I'll keep this open until this has been completed

**Comment by zacharias33** [comment]
Hi I am experiencing a similar issue on Kubernetes version 1.19.11. The PID space of random node exhausted and my only solution for now is to restart that node. Do we have any updates on this feature?

**Comment by thunter1000** [comment]
Good morning this is also impacting us with Kubernetes version 1.191.11. When the PID space is exhausted this impacts our calico-node pod which impacts everything on the node. Restarting the node does seem to resolve the issue. Has this change been released yet?

**Comment by tdihp** [comment]
For users affected by this, I'd suggest to identify the culprit application causing the exhaustion.

**Comment by tdihp** [comment]
Closing as custom node configuration is now GA with `podMaxPids`
