### ISSUE TITLE
NSG / IP Filter on Master apiserver

### ISSUE THREAD

**Issue by pjbgf** [Azure/AKS#228]
Is it in the backlog to support NSGs on top of the Master apiserver? Or at least an IP filter, which would allow users to block traffic from the internet? If so, any ideas of time lines?

It would be brilliant if the team could share a "macro" roadmap for the product, so the community can see that straight from the github repo what's planned and when.

**Comment by seanmck** [comment]
Yes. Please track here: 

https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/35010421-secure-aks-api-from-public-internet
