### ISSUE TITLE
Cannot allow access to only whitelisted IPs with LoadBalancer

### ISSUE THREAD

**Issue by optionsome** [Azure/AKS#2280]
**What happened**:
If there is a LoadBalancer defined for a kubernetes service, Azure automatically creates and recreates inbound security rules from internet to the load balancer IP.
**What you expected to happen**:
It should be possible to allow traffic from only whitelisted IP addresses to AKS cluster while using the LoadBalancer (or some similar load balancer type). It's possible to delete the inbound security rules created by the LoadBalancer from the cluster's network security group. However, they get recreated periodically.
**How to reproduce it (as minimally and precisely as possible)**:
1. Define a service with LoadBalancer type and some ports. 
2. Cluster's network security group should include some inbound security rules with cryptic names that allow traffic from internet to the defined ports for the load balancer's ip address.
3. Remove those security rules
4. Security rules get recreated at some point again (I'm not quite sure what triggers them to get recreated)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.10
- Size of cluster (how many worker nodes are in the cluster?):
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others: Cluster has a service with LoadBalancer type

**Comment by robincher** [comment]
I support this.

I think we should allow only whitelist ips , instead of Service Tag (Internet) when an ingress controller (of LoadBalancer Type) is created.

**Comment by clarenceb** [comment]
@optionsome, you should be able to achieve this using this https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#restrict-inbound-traffic-to-specific-ip-ranges
