### ISSUE TITLE
[question] support Graceful Node Shutdown 

### ISSUE THREAD

**Issue by ToruMakabe** [Azure/AKS#2282]
I'm considering using a spot node pool, so graceful shutdown before eviction is a concern. Will AKS support [upstream graceful node shutdown feature](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/)?

Or do we have to wait for [the implementation of drainsafe](https://github.com/Azure/AKS/issues/982#issuecomment-715755808)?

**Comment by andyzhangx** [comment]
it's enabled by default in k8s 1.21, so it's not enabled yet on current aks version now: https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/#how-do-i-use-it

**Comment by ToruMakabe** [comment]
@andyzhangx Thanks! I'll consider using this upstream feature. Anyway, the implementation of this feature on AKS will especially care about the eviction of Spot VM preemption (getting from IMDS)? Or just using systemd-inhibit ? Let me know if possible.

**Comment by andyzhangx** [comment]
We just use the upstream enabled feature in k8s 1.21, so it would just use `systemd-inhibit`

**Comment by ToruMakabe** [comment]
@andyzhangx Thanks!
