### ISSUE TITLE
Add RBAC actions for cluster start stop

### ISSUE THREAD

**Issue by VijayRod** [Azure/AKS#2283]
**What happened**: I have an ask from my development team to have the ability to Stop and Start AKS resources at will.  To maintain least privilege model I want to avoid over provisioned access. RBAC role actions for Microsoft.ContainerService/managedClusters do not seem to specifically have cluster start/stop.

**What you expected to happen**: RBAC, for Microsoft.ContainerService/managedClusters, can include specific actions for cluster start/stop, for example Microsoft.ContainerService/managedClusters/start and Microsoft.ContainerService/managedClusters/stop.

**Comment by khetheri** [comment]
I have the same question. I am trying to setup a custom role definition to allow for start/stop of AKS clusters. However, the 'Microsoft.ContainerService/managedClusters/stop/action' is not a valid action in the provider.

**Comment by qpetraroia** [comment]
Hi @khetheri,

We will be looking into it. Thanks!

**Comment by SatyKrish** [comment]
Any update on when you will be adding support for these RBAC actions? We are currently using `Azure Kubernetes Service Contributor Role`, but would like it to be fine grained.

**Comment by mishya02** [comment]
Greetings - Is there an update on this issue?  

We would like an RBAC action to start/stop an AKS cluster.  Which RBAC would you recommend (for the below actions) if cluster start/stop does not have a specific RBAC?  

Microsoft.ContainerService/managedClusters/start 
Microsoft.ContainerService/managedClusters/stop

**Comment by pcgeek86** [comment]
Looks like these permissions might be available now?

![image](https://github.com/Azure/AKS/assets/466713/ede89fd6-2333-4f50-a119-0f7e3c4fbbb3)

**Comment by abubinski** [comment]
@qpetraroia okay if we close this?

**Comment by qpetraroia** [comment]
Thanks everyone,

please give those permissions a try and feel free to bump this thread if there are any other issues.

**Comment by VijayRod** [comment]
Microsoft.ContainerService/managedClusters/start/action
Microsoft.ContainerService/managedClusters/stop/action
