### ISSUE TITLE
Flannel support

### ISSUE THREAD

**Issue by VijayRod** [Azure/AKS#2284]
**What happened**: It would be really helpful if I can get some guidance on setting up flannel on AKS.

**What you expected to happen**: Flannel can be a supported network-policy in AKS.

**How to reproduce it (as minimally and precisely as possible)**: AKS cluster create with flannel has below error.

```
ValidationError: Operation failed with status: 'Bad Request'. Details: NetworkPolicy is not supported (only azure and calico are supported)
```

**Anything else we need to know?**: https://github.com/Azure/AKS/issues/589

**Comment by VijayRod** [comment]
@paulgmiller fyi.

**Comment by paulgmiller** [comment]
Aks is unlikely to support flannel anytime soon. (If we did it would be a
network plugin not a network policy) how ever I'd you have a daemonset to
try and install it (replacing kubernetes conf for instance) I'm curious how
it failed we like to try and remove blockers for installing third party
cnis but cannot support them im anyway at this time

**Comment by joshmue** [comment]
> I'm curious how it failed we like to try and remove blockers for installing third party cnis but cannot support them im anyway at this time

@paulgmiller Does that mean that something like #2092 has a good chance to be implemented? I think this should also should help setting up self-hosted flannel more cleanly.

(Sorry for awkwardly jumping in here just to reference an issue created by myself)

**Comment by paulgmiller** [comment]
https://docs.microsoft.com/en-US/azure/aks/use-byo-cni?tabs=azure-cli 
BYO CNI should allow you to set up flannel with minimal interference from us. 
@mattstam
