### ISSUE TITLE
loadbalancer outbound ip prefix + Nginx ingress + static ip + aks 1.20

### ISSUE THREAD

**Issue by Tetradeus** [Azure/AKS#2288]
**What happened**:
AKS 1.20
Helm nginx/ingress helm-chart-3.29.0 :
  repository = "https://kubernetes.github.io/ingress-nginx"
  chart      = "ingress-nginx"
Values:
  controller.service.loadBalancerIP
  controller.service.annotations."service.beta.kubernetes.io/azure-load-balancer-resource-group"

When creating the nginx ingress, load balancer rules are not created and the service is stuck ensuring load balancer:
Events :
```
Type    Reason                Age    From                Message
----    ------                ----   ----                -------
Normal  EnsuringLoadBalancer  2m56s  service-controller  Ensuring load balancer
Normal  EnsuringLoadBalancer  2m39s  service-controller  Ensuring load balancer
Normal  EnsuringLoadBalancer  42s    service-controller  Ensuring load balancer
❯❯❯ kubectl get services -n ingress-nginx                                                                                                                                                                                           
NAME                                 TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)                      AGE
ingress-nginx-controller             LoadBalancer   10.7.0.204   <pending>     80:30514/TCP,443:30472/TCP   2m58s
ingress-nginx-controller-admission   ClusterIP      10.7.0.33    <none>        443/TCP                      2m58s
``` 

**What you expected to happen**:
Get the load balancer rule created and the external ip assigned to the service.

**How to reproduce it (as minimally and precisely as possible)**:

az aks create --resource-group xxx --name xxx --location northeurope --kubernetes-version 1.20.5 --admin-username azureuser --ssh-key-value /root/.ssh/id_rsa.pub --enable-managed-identity --assign-identity xxx --enable-aad --aad-admin-group-object-ids xxx  --load-balancer-sku standard --outbound-type loadBalancer --load-balancer-outbound-ip-prefixes xxx --network-plugin azure --vnet-subnet-id xxx --docker-bridge-address 172.17.0.1/16 --dns-name-prefix xxx --dns-service-ip 10.7.0.10 --service-cidr 10.7.0.0/24 --network-policy azure --node-count 2  --node-vm-size Standard_D8ds_v4 

**Anything else we need to know?**:

It works with version AKS 1.19.9
It works with version AKS 1.20.5 but with auto assigned ingress ip
It works with version AKS 1.20.5 without --load-balancer-outbound-ip-prefixes 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.5 and 1.20.2
- Others: Helm nginx/ingress helm-chart-3.29.0

**Comment by abarqawi** [comment]
@feiskyer is it similar here ? and what is the fix ?  https://github.com/kubernetes/kubernetes/pull/101739

**Comment by feiskyer** [comment]
it is caused by an upstream bug https://github.com/kubernetes-sigs/cloud-provider-azure/issues/634. We would do a hotfix for it.

**Comment by nilo19** [comment]
hotfix released for all aks supported versions, please update your cluster to solve the issue.

**Comment by Tetradeus** [comment]
I still get the same issue! Maybe not released yet?

**Comment by nilo19** [comment]
@Tetradeus yeah it's being released. I would let you know when it's available.

**Comment by nilo19** [comment]
hotfix released
