### ISSUE TITLE
AKS file share issue after failover to new region

### ISSUE THREAD

**Issue by hadr10** [Azure/AKS#2289]
**What happened**: I am using in AKS cluster static file share and after failover storage account with file share to new region, azure file share stop working

**What you expected to happen**: FIle share working after failover to new region.

**How to reproduce it (as minimally and precisely as possible)**:
Build AKS cluster, i am using 1.19.7 and storage account with file share and try to failover storage account to paired region and then back.

**Anything else we need to know?**:
There is different ip after failover in pod for file share than if you will try ping directly:
PS C:\Git\drc-demo-storageaccount> kubectl exec -it web-655fd79dd8-snclt /bin/sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
//*****.file.core.windows.net/web on /usr/share/nginx/html type cifs (rw,relatime,vers=3.0,cache=strict,username=***,uid=1000,forceuid,gid=1000,forcegid,addr=20.150.# exit

Pinging file.ams23prdstr15a.store.core.windows.net [20.150.122.40] with 32 bytes of data:
Control-C

**Environment**:
- Kubernetes version (use `kubectl version`): PS C:\Git\drc-demo-storageaccount> kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"8ab00ff68a1763b5a506a7073cb8e67b12dfbcd7", GitTreeState:"clean", BuildDate:"2021-03-10T23:40:01Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (how many worker nodes are in the cluster?): 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): nginx pod with index.html in file share
- Others:

**Comment by phealy** [comment]
Did you try deleting and recreating the pod to trigger an unmount and remount of the share?

**Comment by andyzhangx** [comment]
since azure file server IP has changed, the only way to migrate now is as @phealy said `recreating the pod to trigger an unmount and remount of the share`

**Comment by andyzhangx** [comment]
The original issue would be solved by Kernel `5.4.0-1049-azure` (latest node image kernel: `5.4.0-1055-azure`), it has the SMB client fix for an issue in DNS resolution after Azure files storage failover, using private-link (only supported in Azure File CSI driver) would also solve this issue.

**Comment by andyzhangx** [comment]
Update: the complete kernel fix of this issue is still in 5.5 which is in Ubuntu 20.04, smb kernel team are trying to port the kernel fix to 5.4 on Ubuntu 18.04
