### ISSUE TITLE
Networking issue after upgrading to 1.19.9 with Azure CNI

### ISSUE THREAD

**Issue by Larcen** [Azure/AKS#2297]
**What happened**: After upgrading the AKS cluster with Azure CNI to 1.19.9 from 1.18.17, the PODs can not connect to outside its network. After deploying a dnsutils POD to diagnose the problem, we can see the POD IP is 10.0.0.38/16 (wich is fine), but the gateway IP is incorrect (169.254.1.1), so it can't connect to outside its local network or get DNS resolution  (dnsServiceIp: 10.2.0.10)

**What you expected to happen**: The PODs must connect outside its network via the right gateway. Previously the gateway was 10.0.0.1.

**How to reproduce it (as minimally and precisely as possible)**: The problem started after issuing the following command in the Azure Shell: az aks upgrade --resource-group <Resource_Group_Name> --name <AKS_Cluster_Name> --kubernetes-version 1.19.9

**Anything else we need to know?**: Not at this momment.

**Environment**:
- Kubernetes version (use `kubectl version`):

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"6c90dbd9d6bb1ae8a4c0b0778752be06873e7c55", GitTreeState:"clean", BuildDate:"2021-03-22T23:02:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1

- Size of cluster (how many worker nodes are in the cluster?) 3 B2s standar

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
HTTP J2EE microservices

- Others:

**Comment by gjmscc** [comment]
having the exact same issue after upgrading from 1.19.7 to 1.20.5.

**Comment by Larcen** [comment]
Hi again,

After a few hours, the problem was resolved with no intervention. Talking with Azure support, it could be caused by a high memory usage on the nodes while upgrading. They recommend us to limit the memory available for the PODs via deployment configuration, or increase the cluster resources (more nodes or same number of nodes with more memory).

Regarding the new gateway IP (169.254.1.1), it was caused by recent changes in Azure CNI. This gateway is now normal.

https://docs.microsoft.com/en-us/azure/aks/faq#what-is-azure-cni-transparent-mode-vs-bridge-mode

Best regards.

**Comment by Larcen** [comment]
Hi again,

After a few hours, the problem was resolved with no intervention. Talking with Azure support, it could be caused by a high memory usage on the nodes while upgrading. They recommend us to limit the memory available for the PODs via deployment configuration, or increase the cluster resources (more nodes or same number of nodes with more memory).

Regarding the new gateway IP (169.254.1.1), it was caused by recent changes in Azure CNI. This gateway is now normal.

https://docs.microsoft.com/en-us/azure/aks/faq#what-is-azure-cni-transparent-mode-vs-bridge-mode

Best regards.
