### ISSUE TITLE
Dynamic Azure Files walk-through provides error

### ISSUE THREAD

**Issue by b-odonoghue** [Azure/AKS#2298]
**What happened**:
I attempted to follow the dynamic azure file directions listed [here](https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv) though kubelet fails to mount the persistent volume.

**What you expected to happen**:
I expected to follow the directions linked above and have my pod start

**How to reproduce it (as minimally and precisely as possible)**:
* Create a cluster with the terraform code [here](https://github.com/Azure-Terraform/terraform-azurerm-kubernetes)
* Ensure K8s version = 1.18.14
* Attempt dynamic azure file directions above

**Anything else we need to know?**:
I made sure that the worker nodes were updated with the correct cifs-utils and tested with auzre-disk which worked without issue. Even the default azure-file storageClasses give the same errors as below. I am attempting to use `ReadWriteMany` which seems to only be support via azure-files

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.14
- Size of cluster (how many worker nodes are in the cluster?) 2 worker nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) 
- Others:

Here is the error that I am seeing when I describe the pod
```
  Warning  FailedMount  2m34s  kubelet  MountVolume.SetUp failed for volume "pvc-e0bd0def-6128-444f-a228-2a26480a6c64" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/08af5d55-9dbf-44f8-8c00-186cf42b1d58/volumes/kubernetes.io~azure-file/pvc-e0bd0def-6128-444f-a228-2a26480a6c64 --scope -- mount -t cifs -o actimeo=30,cache=strict,dir_mode=0777,file_mode=0777,gid=0,mfsymlinks,uid=0,vers=3.0,<masked> //f130842ab2d6a4c40bb5a58.file.core.windows.net/kubernetes-dynamic-pvc-e0bd0def-6128-444f-a228-2a26480a6c64 /var/lib/kubelet/pods/08af5d55-9dbf-44f8-8c00-186cf42b1d58/volumes/kubernetes.io~azure-file/pvc-e0bd0def-6128-444f-a228-2a26480a6c64
Output: Running scope as unit: run-r84926cef3c184d968527fa765c7dc70b.scope
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```

When I am on the worker nodes inside this pod directory I can clearly see that the `kubernetes.io~azure-file` directory is missing. I have also seen the `kubernetes.io~azure-disk` directory get automatically created when I use the default storageClass.

**Comment by andyzhangx** [comment]
can you follow this guide to check whether manual mount works on that agent node, there could be some network issue between agent node and target azure file service:
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/csi-debug.md#troubleshooting-connection-failure-on-agent-node

**Comment by b-odonoghue** [comment]
Thank you I will give that a try. Though that makes me wonder if I am somehow blocking the mount with my subnet security rules? Is the thing I am trying to mount considered outside my subscription and vnet?

**Comment by b-odonoghue** [comment]
So turns out that by blocking internet outbound access to this particular subnet I am blocking the mount function of azure-files. When i allow internet outbound the samples i linked above work just fine. Perhaps there is a note somewhere about this as a requirement that I have missed.

Though I am wondering if there is a specific service tag I can use instead of simply opening a whole security group to outbound internet access?
