### ISSUE TITLE
"Resource is not supported" when creating a Private Endpoint to AKS via Azure Console

### ISSUE THREAD

**Issue by tullydwyer** [Azure/AKS#2299]
**What happened**:

Hi there,

I get the error "Resource is not supported" when trying to create a private endpoint to a private AKS in the Azure console.

![Screen Shot 2021-04-28 at 2 13 48 pm](https://user-images.githubusercontent.com/7508115/116355066-aaae8400-a83c-11eb-95be-8ec7841f6ff7.png)

**What you expected to happen**:

I expected it to accept AKS as a supported resource as per the list of supported resources table: https://docs.microsoft.com/en-gb/azure/private-link/private-endpoint-overview#private-link-resource

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a private AKS as per: https://docs.microsoft.com/en-us/azure/aks/private-clusters#create-a-private-aks-cluster-with-a-custom-private-dns-zone
2. Try to create a Private Endpoint targeting the AKS resource.

**Anything else we need to know?**:

I know a `kube-apiserver` Private Endpoint is automatically created in the node resource group, however I would like to create and manage a private endpoint manually or via Terraform to follow resource naming conventions, tagging policies, etc.

I saw https://github.com/Azure/AKS/issues/1523 but it seems to be closed without a way to create and manage a private endpoint manually.

load_balancer_sku = "Standard" (https://docs.microsoft.com/en-us/azure/aks/private-clusters#prerequisites)

Am I misunderstanding something key here?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.9
- Size of cluster (how many worker nodes are in the cluster?) 1
- General description of workloads in the cluster: Testing Private Link Access
- Others:

Thanks,

**Comment by miwithro** [comment]
@feiskyer can you please address this?

**Comment by feiskyer** [comment]
This was caused by a known issue from PrivateLink service. Network team is working on the fix.

**Comment by haysjp** [comment]
@feiskyer is there any update on the timeline for this fix?  I have another Azure customer asking.  Is there a different issue/link to track for updates?  Thanks!

**Comment by feiskyer** [comment]
@haysjp it is under rollout, ETA is end of next month.

**Comment by tullydwyer** [comment]
Tested today with a fresh AKS and the issue is not resolved. @feiskyer can you re-open? I think the bot closed prematurely because the `resolution/shipped` tag was added then removed? 
![image](https://user-images.githubusercontent.com/7508115/133173641-19ebec46-06a0-4528-bab7-e6400d1afd39.png)

![Screen Shot 2021-09-14 at 10 13 06 am](https://user-images.githubusercontent.com/7508115/133173784-65873b67-0e3a-42d5-abc8-0b2b8a7014fd.png)

**Comment by feiskyer** [comment]
reopen the issue as the fix is still under rollout

**Comment by tullydwyer** [comment]
Hi all,

I can now create Private Endpoints for AKS via the console.

Some points:
- I have not tested the network connectivity via the endpoint.
- The Private DNS configuration on the Private Endpoint does not work.
  - The Private Endpoint has no FQDN and no DNS records are created.

![image](https://user-images.githubusercontent.com/7508115/135183683-16243be3-50ef-4f05-b386-dfabd3fa16ec.png)

![image](https://user-images.githubusercontent.com/7508115/135183949-f4ca9151-3200-421d-bddb-2e32c7495657.png)
