### ISSUE TITLE
Cluster creation fails to created Nodes

### ISSUE THREAD

**Issue by EIrwin** [Azure/AKS#23]
I used the following [Kubernetes Walkthrough](https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough) as a quickstart to stand up a cluster to federate our cluster from GCP.

Followed the following steps exactly per the documentation.

1. `az provider register -n Microsoft.ContainerService`
2. `az group create --name myResourceGroup --location westus2`
3. `az aks create --resource-group myResourceGroup --name myK8sCluster --agent-count 1 --generate-ssh-keys`
4. `az aks get-credentials --resource-group myResourceGroup --name myK8sCluster`

Everything to this point matches expected state per documentation and general observation.

However, when attempting to list the nodes in the cluster using `kubectl get nodes`, I get the following in both Azure Cloud Shell and locally.

```bash
~$ kubectl get nodes
No resources found.
```

Thinking this may have been an issue with credentials, I ran the following

```bash
 ~$ kubectl get namespaces
NAME          STATUS    AGE
default       Active    19m
kube-public   Active    19m
kube-system   Active    19m
```

To make things a little more confusing, when running `kubectl get all` from Cloud Shell, I get different results than I do from local.

From Cloud Shell
```bash
~$ kubectl get all
No resources found.
```

From Local Terminal
```bash
 ~$ kubectl get all
NAME             CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
svc/kubernetes   10.0.0.1     <none>        443/TCP   27m
```

Very frustrating.

**Comment by EIrwin** [comment]
Could this potentially be related to capacity issues, or Free Trial subscriptions?

**Comment by berndverst** [comment]
@EIrwin, I just created a new cluster (since capacity issues in WestUS2 were resolved -- see #2) and `get nodes` is working for me.

```
kubectl get nodes
NAME                        STATUS    ROLES     AGE       VERSION
aks-agentpool1-18960823-0   Ready     agent     10m       v1.7.7
```

`get all` is also returning the same in Cloud Shell and locally for me (no resources found).

**Comment by slack** [comment]
@EIrwin look for a new resource group prefixed with `MC_` there should be a deployment in that RG which covers the creation of nodes for your AKS cluster. That deployment should have any errors for node creation.

**Comment by EIrwin** [comment]
Deleted cluster and reran the following:

`az aks create --resource-group staging --name staging --agent-count 1 --generate-ssh-keys`

which took forever and failed w/ the following error

`Deployment failed. Correlation ID: 8a30edac-7d3c-4972-ba85-c0208f539dfd. getAndWaitForManagedClusterProvisioningState error: <nil>`

**Comment by slack** [comment]
Sorry this issue got stale, you still having issues?

**Comment by slack** [comment]
Closing this issue due to age.

**Comment by joaocc** [comment]
@EIrwin Did you succeed in federating AKS with another cluster? Thx
