### ISSUE TITLE
Customize node configuration: bad request when running az aks nodepool update

### ISSUE THREAD

**Issue by tvdmeent** [Azure/AKS#2300]
**What happened**:
We are using the CustomNodeConfigPreview option to enable swap on the nodes in a user nodepool. 
That works fine. However, when we try to set a different max-count value on a nodepool we get the following error :
Operation failed with status: 'Bad Request'. Details: CustomKubeletConfig or CustomLinuxOSConfig can not be changed for this operation.

The command used :
az aks nodepool update --resource-group <resource-group> --cluster-name <cluster> --name <pool> --update-cluster-autoscaler --min-count 1 --max-count 4

Next, we tried to pass the configs as well:
az aks nodepool update --resource-group <resource-group> --cluster-name <cluster> --name <pool>--update-cluster-autoscaler --min-count 1 --max-count 4 --kubelet-config ./kubeletconfig.json --linux-os-config ./linuxosconfig.json

This resulted in the error:
unrecognized arguments: --kubelet-config ./kubeletconfig.json --linux-os-config ./linuxosconfig.json

**What you expected to happen**:
We expected to be able to use this command like we could when not using this preview option

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster using this preview option and then issue the aks nodepool update command

**Anything else we need to know?**:
kubeletconfig.json:

{
    "failSwapOn": false
}

linuxosconfig.json:

{
    "transparentHugePageEnabled": "madvise",
    "transparentHugePageDefrag": "defer+madvise",
    "vm.swappiness": 80,
    "swapFileSizeMB": 70000,
    "sysctls": {
    }
}

**Environment**:
- Kubernetes version: 1.20.2
- Size of cluster: 1 system (agentpool), 2 user nodepools, each 1 node active
- General description of workloads in the cluster: workers for processing data
- Others:

**Comment by parbmatthews** [comment]
I'm getting a similar error:

az aks nodepool add --name highmemnp2 --cluster-name somecluster --resource-group somerg --linux-os-config linuxosconfig.json --labels "mem: high" --node-taints "sku=e2asvfour:NoSchedule" --node-count 2 --node-vm-size Standard_E2as_v4

az: error: unrecognized arguments: --linux-os-config linuxosconfig.json

I've followed the steps in the link below:
https://docs.microsoft.com/en-us/azure/aks/custom-node-configuration

I do seem to have the feature installed:
> az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/CustomNodeConfigPreview')].{Name:name,State:properties.state}"
Name                                                State
--------------------------------------------------  ----------
Microsoft.ContainerService/CustomNodeConfigPreview  Registered

**Comment by paulgmiller** [comment]
Do you have the preview cli installe?  Customize the node configuration for
Azure Kubernetes Service (AKS) node pools (preview) - Azure Kubernetes
Service | Microsoft Docs
<https://docs.microsoft.com/en-us/azure/aks/custom-node-configuration#install-aks-preview-cli-extension>
