### ISSUE TITLE
Azure RBAC for Kubernetes namespace scope is always forbidden

### ISSUE THREAD

**Issue by micya** [Azure/AKS#2302]
**What happened**:

After granting AAD user "Azure Kubernetes Service RBAC Reader" on a namespace scope per [documentation](https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac), kubectl get commands on the namespace are still forbidden.

**What you expected to happen**:

User should be able to get pods/resources on the namespace.

**How to reproduce it (as minimally and precisely as possible)**:

Scenario:

- We have a user in AAD user@example.com
- User should be granted writer access on team1 namespace
- User should be granted reader access on team2 namespace

Assign permissions:

``` bash
$ AKS_ID=$(az aks show -n <cluster> -g <rg> --query id -o tsv)

$ az role assignment create --role "Azure Kubernetes Service RBAC Reader" --assignee user@example.com --scope $AKS_ID/namespaces/team1
$ az role assignment create --role "Azure Kubernetes Service RBAC Writer" --assignee user@example.com --scope $AKS_ID/namespaces/team2
```

Test permissions (after logging in with device code):

``` bash
$ kubectl get pods -n team1
Error from server (Forbidden): pods is forbidden: User "user@example.com" cannot list resource "pods" in API group "" in the namespace "team1"

$ kubectl get pods -n team2
Error from server (Forbidden): pods is forbidden: User "user@example.com" cannot list resource "pods" in API group "" in the namespace "team2"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Replicated across multiple versions: 1.17, 1.18, 1.19, 1.20

**Comment by awillows** [comment]
Has the cluster been enabled to support Azure RBAC for Kubernetes, I wasn't sure from your steps if this had been done?

You can confirm with the following and check the enableAzureRbac property:

``` az aks show --name sandbox --resource-group rgAksClusters --query aadProfile
The behavior of this command has been altered by the following extension: aks-preview
{
  "adminGroupObjectIds": [
    "5cc0dc4a-8981-4cdb-87cf-73de547cac92"
  ],
  "clientAppId": null,
  "enableAzureRbac": null,
  "managed": true,
  "serverAppId": null,
  "serverAppSecret": null,
  "tenantId": "xxx988bf-86f1-xxxx-xxxx-2d7cd011db47"
}```

**Comment by micya** [comment]
Looks like it wasn't enabled for some reason. I created a new cluster and verified it works. Thanks!
