### ISSUE TITLE
ImagePullBackOff error backoff for nodes where public node ip enabled

### ISSUE THREAD

**Issue by gaurav-magassian** [Azure/AKS#2305]
I am deploying my services Azure AKS. I am running into an issue where I get a ImagePullBackOff error. Here is some context.

I have 4 node pools 1 with --enable-node-public-ip option and another 3 without the node public-ip enabled option. I am trying to deploy a DaemonSet resource. The container image is hosted on GitHub package registry. The issue is, the nodes that don't have a public IP enabled are successfully able to pull the images whereas, the nodes that have public-ip enabled have an error.

Here is the error:

```
Failed to pull image "docker.pkg.github.com/xyz": rpc error: code = NotFound desc = failed to pull and unpack image "docker.pkg.github.com/xyz"
```

**Comment by dzmitry-lahoda** [comment]
I was able to pull both linux and windows, public gce and private azure registries from cluster with public IP enabled. May be recheck url to registry and acccess rights?

**Comment by gaurav-magassian** [comment]
This was a k8s version issue the older nodepool was 1.17.1 which was running docker and new nodepool was running containerd. We can close this ticket. Thank you
