### ISSUE TITLE
Using Azure Keyvault secrets in parameters

### ISSUE THREAD

**Issue by ams0** [Azure/AKS#231]
I used [this](https://gist.github.com/ams0/c8d593c6043cff1e55a9b356d8a6c0cc) template to deploy an AKS cluster; following the example [here](https://github.com/Azure/acs-engine/tree/master/examples/keyvault-params) I'm referencing my SP stored in a keyvault (created with --enabled-for-deployment true --enabled-for-template-deployment true). Surprisingly, even if undocumented, the deployment succeeds but the cluster is not operational, I suspect because the SP is not retrieved (the SP works, it's the one I use for other other acs-engine clusters). I reckon it's an undocumented feature, but, do you think we can make it work?

**Comment by neumanndaniel** [comment]
"servicePrincipalProfile": {
          "clientId": "[parameters('ServicePrincipalClientID')]",
          "secret": "",
          "keyvaultSecretRef": {
            "vaultID": "[parameters('keyVaultSecretVaultID')]",
            "secretName": "[parameters('keyVaultSecretName')]"
          }
      }

Remove the "secret":"", and it should work without any issues. With the "secret":"", specified you are providing an empty string for the secret.

**Comment by slack** [comment]
@ams0 did removing `"secret": ""` work for you, if not, please re-open the issue!
