### ISSUE TITLE
Recommended disk alert is triggered before image garbage collection

### ISSUE THREAD

**Issue by yene** [Azure/AKS#2312]
**What happened**:
Enabled Recommended alert "Node Disk Usage %: Average disk usage for a node is greater than 80%"
Everytime the disk usage goes over 80%, it triggers the alert. Followed by a resolved alert.

**How to reproduce it (as minimally and precisely as possible)**:
Create AKS cluster. Deploy 200 builds.

**Anything else we need to know?**:
When node disk reaches 80% usage, the image garbage collection starts to remove old images. (image-gc-high-threshold)
Workaround is to change alert to be **greater than 85%.**

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.14
- disk size: 128GB
- Size of cluster (how many worker nodes are in the cluster?) 
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by joaguas** [comment]
Hi @yene ,

Image garbage collection is a natural part of a worker node's lifecycle. AKS nodes use a low threshold of 80% and a high threshold of 85% - it doesn't run before 80% disk usage and it will always run after 85%.

If you have disk alerts at 80% usage these fall  right in between and the behavior you're reporting is expected.

As you mentioned, you can either change the alert % or you can tune the kubelet flags for imageGcLowThreshold and imageGcHighThreshold

https://docs.microsoft.com/en-us/azure/aks/custom-node-configuration#kubelet-custom-configuration

**Comment by yene** [comment]
OK I will follow your advice and change the **"Recommended disk alert"** of 80% to 85%
