### ISSUE TITLE
Cannot change outbound network traffic through UDR unless done at aks creation time

### ISSUE THREAD

**Issue by dcint** [Azure/AKS#2313]
**What you expected to happen**:
Would like to have egres outbound network traffic route through azure firewall. Currently this is only avaiable during creation of cluster. I need to be able to change this on current cluster that has been created with outbound load balancer. 

https://docs.microsoft.com/en-us/azure/aks/egress-outboundtype#limitations

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.9
- Size of cluster (how many worker nodes are in the cluster?)

**Comment by denniszielke** [comment]
Don't understand the ask. You can add a udr to the cluster subnet after creation and force all traffic through the firewall- it works in my environment.
However you should not delete the now unused outbound rule of the load balancer.
