### ISSUE TITLE
AKS created with VMSS has all VMs on the same fault domain

### ISSUE THREAD

**Issue by previ** [Azure/AKS#2316]
**What happened**:
AKS cluster created with node pools based on Virtual Machine Scalability Set, either in single or multiple zones,  have all VMSSs with a parameter of "Fault domain count" equal to 1.
This implies that all VMs of all node pools are created on the same fault domain (typically fault domain "0") on each region, which is an issue in terms of reliability.

**What you expected to happen**:
VMSSs "Fault domain count" value should be set as the maximum supported value (5), or it should be configurable at cluster or node pool creation time.

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster either via az cli or web portal, or Terraform script.

**Anything else we need to know?**:
Quoting from [official VMSS docs](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-manage-fault-domains): _"For the regions that support zonal deployment of virtual machine scale sets and this option is selected, the default value of the fault domain count is 1 for each of the zones. FD=1 in this case implies that the VM instances belonging to the scale set will be spread across many racks on a best effort basis."_
The above sentence seems to state that a single zone node pool is inherently less reliable that an AvailabilitySet-based node pool, because with Availability Sets VMs are spread on up to five fault domains, and the node's fault domain info is available to the kubernetes scheduler via node labels, while this is not the case with VMSS.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.14, 1.19.7.
- Size of cluster (how many worker nodes are in the cluster?) 16, 6
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Microservices, various runtimes
- Others: N/A

**Comment by awillows** [comment]
FD=1 in a zonal deployment is an indicator that instances will be spread across many racks as possible using 'Max Spreading' , it's not the same usage as that in an availability set where it would cause a deployment to a single 'rack'. 

If you review the document below hopefully that will help clarify. You will note that if you specified a FD number it could lead to allocations failures in some cases. For a managed service like AKS that should be avoided hence the reason you see FD=1 is you look at the scale set. 

[https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-use-availability-zones#availability-considerations](url)

**Comment by marcoboffi** [comment]
ok @awillows but on our AKS cluster wihtout zone distribution, _topology.kubernetes.io/zone_ label on vmss node is always and automatically set to **0** ?  
 What is mean of this value?

**Comment by marcoboffi** [comment]
My 16 nodes clusters (with 3 nodepools) shows:
      topology.kubernetes.io/region: westeurope
      topology.kubernetes.io/zone: "0"
for all nodes. _[AKS version 1.19.7]_

I tried to create a dummy aks 1.20.2 but these labels are still this value.

**Comment by awillows** [comment]
Sorry, I misunderstood, as previously explained VMSS with a FD=1 is max spreading as per the documentation. The topology.kubernetes.io/zone=0 for all nodes will be seen when you are not using zones.

**Comment by previ** [comment]
> Sorry, I misunderstood, as previously explained VMSS with a FD=1 is max spreading as per the documentation. The topology.kubernetes.io/zone=0 for all nodes will be seen when you are not using zones.

My understanding is that choosing VMSS, it becomes kind of necessary to deploy AKS on multiple zones.
With AKS deployed on a single zone (no matter the nodepools or the VMs in the pools), there is no way for the Kubernetes scheduler to span replicated pods on nodes belonging to different fault domains. This implies that in case a fault domain of a zone becomes unavailable, all pods of the same kind might be deployed on the same fault domain, translating in a service disruption.

So my conclusion (having  no other details) is:
- keep using AvailabilitySet for single zone clusters
- use VMSS for multiple zone clusters
