### ISSUE TITLE
Public IP is not available to Pods

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Azure/AKS#2318]
**What happened**:

Agones game servers start using internal IP, while public IP is provided

**What you expected to happen**:

These should use public IP

**How to reproduce it (as minimally and precisely as possible)**:

Follow:
1. https://agones.dev/site/docs/installation/creating-cluster/aks/  but use public IP setting
2. https://agones.dev/site/docs/installation/install-agones/yaml/
3. https://agones.dev/site/docs/getting-started/create-gameserver/

Expected: get GameServer shows public IP
Actual: GameServer shows internal IP

Alternative expectation: Public IP of node I get via `kubectl describe node` is provided in response. As per https://kubernetes.io/docs/concepts/architecture/nodes/#addresses

**Anything else we need to know?**:

We have run custom gameserver on windows which logs all networks our Enet netcode can bind to. There was no public IP in list.

Workaround `Yeah, so sadly, the AKS metadata service just flat out will not tell Kubernetes it's public IP. Our solution to get around the problem is to lookup the public IPs using the Azure SDK. It's not super clean or elegant, but hopefully the Azure team will update the metadata service soon.` worked for me. But issues that that workaround also costs much. 

Instead of nice clean TF script, I have to find automatically created RG and create Read role assignment to it and bind public to internal in multiplay service code. Other option, give full read access for some service role to subscription, so it monitors cluster creations (may be create separate subscription gameclusters).

Other possible to try, not sure if that will work well for real time games. As soon as GameServer created, create Load Balancer for each of GameServers. I see that ASK has one Azure LoadBalancer per Cluster. So that all, as I understand, calls to GameServers will go through it. There will be several orders more calls(small UPD packets added fast) and more ports than usual cluster(HTTP CRUD). And LoadBalancer is async created, so additional delay before game. Could have one LoadBalancer with 1000 ports preopened as possible way to try fix async creation.

Other alternative to use some K8S metadata, but `kubectl get pods mynode` does not contain public IP. 

See https://agones.slack.com/archives/C9DF6FD3M/p1619811317054500?thread_ts=1609969760.139200&cid=C9DF6FD3M

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.14
- Size of cluster (how many worker nodes are in the cluster?): 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) : UPD ports, GameServers

**Comment by dzmitry-lahoda** [comment]
weird, i cannot get public ip to internal IP mapping via C# nuget packages... it hides all of these. how UI gets these?

**Comment by mateuushz** [comment]
Yup same issue here. The VMSS instances have a private and public IP attached to it, would be good to showcase the public IP attached.

**Comment by kaboing** [comment]
Yep, getting the public/external IP to trickle down to the nodes is super useful.

**Comment by miwithro** [comment]
@AbelHu @mainred

**Comment by AbelHu** [comment]
@dzmitry-lahoda did you try `az aks create --enable-node-public-ip`?

**Comment by dzmitry-lahoda** [comment]
yes. public ip is created and works. but how I supposed to get it? C# sdk does not have that (REST only, many slow calls) and pod is not provided with that info. so the public IP should be provided or into the POD (as ifaces or label) OR as node properties. for now neither works.

**Comment by dzmitry-lahoda** [comment]
i mean why would i need public IP if I cannot get it easy?

**Comment by AbelHu** [comment]
@palma21 do you have any idea to get the public IPs of VMSS nodes?

**Comment by dzmitry-lahoda** [comment]
I have idea, but GKE does waaaay better. It pushes IP into Pod meta and into Node meta - 2 places.

```csharp
namespace Microsoft.Azure.Management
{
    public sealed record PublicIpConfiguration(IList<IpConfiguration> Value);
    public sealed record IpConfiguration(string Name, string Id, string Etag, Properties Properties);
    public sealed record Properties(string ProvisioningState, string ResourceGuid, string IpAddress, string PublicIPAddressVersion, string PublicIPAllocationMethod, string IdleTimeoutInMinutes, IpConfigurationId IpConfiguration);
    public sealed record IpConfigurationId(string Id);
    public class PasswordAzureCredentialsConfig
    {
        public string ClientId { get; init; } = null!;
        public string ClientSecret { get; init; } = null!;
        public string TenantId { get; init; } = null!;
    }
    public class ManagedCluster
    {
        public string ResourceGroup { get; init; } = null!;
        public string Name { get; init; } = null!;
        /// https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#node_resource_group
        /// TODO: rename in infrastructure (or provide region into here)
        public string NodeResourceGroup => $"mc_{ResourceGroup}_{Name}_westeurope";
    }
    public class AzureManagedClusters
    {
        public IEnumerable<ManagedCluster> ManagedClusters { get; init; } = null!;
    }
    /// https://github.com/Azure/AKS/issues/2318
    public class AzureClient
    {
        private readonly AzureCredentials credentials;
        private readonly AzureManagedClusters clusters;
        private readonly AsyncLazy<IAzure> azure;
        private readonly RestClient rest;
        public AzureClient(IOptions<PasswordAzureCredentialsConfig> config, IOptions<AzureManagedClusters> clusters)
        {
            var credentials = SdkContext.AzureCredentialsFactory.FromServicePrincipal(config.Value.ClientId, config.Value.ClientSecret, config.Value.TenantId, AzureEnvironment.AzureGlobalCloud);
            this.credentials = credentials;
            this.clusters = clusters.Value;
            // later move it into cached singleton with refresh cycle
            this.azure = new AsyncLazy<IAzure>(() => Microsoft.Azure.Management.Fluent.Azure
                        .Configure()
                    .WithLogLevel(HttpLoggingDelegatingHandler.Level.BodyAndHeaders)
                    .Authenticate(credentials)
                    .WithDefaultSubscriptionAsync());
            this.rest = RestClient
    .Configure()
    .WithEnvironment(AzureEnvironment.AzureGlobalCloud)
    .WithCredentials(credentials)
    .Build();
        }
        public async IAsyncEnumerable<Microsoft.Azure.Management.ContainerService.Fluent.IKubernetesCluster> GetClusters()
        {
            foreach (var item in clusters.ManagedClusters)
            {
                yield return await (await azure).KubernetesClusters.GetByResourceGroupAsync(item.ResourceGroup, item.Name);
            }
        }
        // not optimal at all, must be modified for scaling (or wait MS will provide that out of box) https://github.com/Azure/AKS/issues/2318
        public async Task<IReadOnlyDictionary<string, string>> GetIpMaps()
        {
            var azure = await this.azure;
            var map = new Dictionary<string, string>();
            foreach (var managedCluster in clusters.ManagedClusters)
            {
                var vmsss = await azure.VirtualMachineScaleSets.ListByResourceGroupAsync(managedCluster.NodeResourceGroup);
                foreach (var vmss in vmsss)
                {
                    var vms = await vmss.VirtualMachines.ListAsync();
                    foreach (var vm in vms.Where(vm => vm.OSType == Compute.Fluent.Models.OperatingSystemTypes.Windows)) // for now just filter by windows, later if linux will be - tag in terraform (filter by tag)
                    {
                        // will be removed with https://github.com/Azure/azure-libraries-for-net/issues/1185#issuecomment-842185139
                        var url = $"https://management.azure.com/subscriptions/{azure.SubscriptionId}/resourceGroups/{vmss.ResourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmss.Name}/publicipaddresses?api-version=2017-03-30";
                        var request = new HttpRequestMessage(HttpMethod.Get, url);
                        await rest.Credentials.ProcessHttpRequestAsync(request, default);
                        var httpClient = new HttpClient();
                        var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, default);
                        var stream = await response.Content.ReadAsStringAsync();
                        var publicIps = JsonConvert.DeserializeObject<PublicIpConfiguration>(stream);
                        // var vmProperties= azure.GenericResources.GetById(vm.Id); // contains json with ipConfigurations/ipconfig1/publicIPAddresses/pub1
                        // subscriptions/XXXXXX/resourceGroups/MC_rgdz_agones-test_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aksgame/virtualMachines/3/networkInterfaces/aksgame/ipConfigurations/ipconfig1/publicIPAddresses/pub1
                        // but we are okey with shorted check
                        // subscriptions/XXXXXX/resourceGroups/MC_rgdz_agones-test_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aksgame/virtualMachines/3/networkInterfaces/aksgame
                        var ipconfig1 = vm.ListNetworkInterfaces().First();
                        var publicIp = publicIps.Value.Single(x => x.Id.StartsWith(ipconfig1.Id));
                        map[ipconfig1.PrimaryIPConfiguration.PrivateIPAddress] = publicIp.Properties.IpAddress;
                    }
                }
            }
            return map;
        }
    }
}
```

**Comment by dzmitry-lahoda** [comment]
MUST cache because if map to frequently will get `Microsoft.Rest.Azure.CloudException: The server rejected the request because too many requests have been received for this subscription.`

**Comment by dzmitry-lahoda** [comment]
One more expectancy, Node port also kind of should/canbe public if Node has Public IP
![image](https://user-images.githubusercontent.com/757125/119936182-6a543a00-bf91-11eb-9f65-fa5e3c4d38bd.png)

**Comment by WeetA34** [comment]
Hello
AKS 1.18.19 is out.
External-IP is filled with VM public IP.

**Comment by kaboing** [comment]
Confirmed, works for 1.18.19.

**Comment by dzmitry-lahoda** [comment]
1.18 is undeployable now afaik. so close.
