### ISSUE TITLE
Support for dual-stack clusters

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/AKS#2326]
IPv6 is coming to AKS soon (https://github.com/Azure/AKS/issues/460) and dual-stack Kubernetes is in beta in Kubernetes v1.21 ([docs](https://kubernetes.io/docs/concepts/services-networking/dual-stack/)).

Once it GA's, it would be nice to be able to spin up AKS clusters that are using dual-stack as well.

**Comment by danimal521** [comment]
We have committed ipv6 to this semester here: https://github.com/Azure/AKS/issues/460
