### ISSUE TITLE
Can't create new node in AKS after a VNET move from a resource group to another

### ISSUE THREAD

**Issue by fdebuire** [Azure/AKS#2329]
**What happened**:
I successfully moved a Virtual Network from a resource group to a different resource group in the same subscription using the Portal UI.
After the move, AKS is still referencing the old Virtual Network/subnet ID and new nodes can't be created.

**What you expected to happen**:
AKS to use the new subnet ID and nodes can be created as usual.

**How to reproduce it**:
Create a resource group A
Create a VNET and a subnet inside the resource group A
Create a different resource group B
Create an AKS cluster where the default node pool will reference the subnet from the VNET that is in resource group A (https://docs.microsoft.com/en-us/azure/aks/configure-kubenet#bring-your-own-subnet-and-route-table-with-kubenet)
Move the VNET from resource group A to resource group B
Try to add a new node to AKS, it will fail

**Anything else we need to know?**:
`az aks show -g resource_group -n aks_name --query 'agentPoolProfiles[].vnetSubnetId'`
will display the old subnet ID

`az network vnet subnet show --ids old_subnet_id`
results in a 404

**Environment**:
- Kubernetes version: v1.19.7

**Comment by awillows** [comment]
The movement of AKS infrastructure, in this case the vNet, to another resource group currently isn't supported as per the FAQ

[https://docs.microsoft.com/en-us/azure/aks/faq#can-i-move-my-aks-cluster-or-aks-infrastructure-resources-to-other-resource-groups-or-rename-them](url)

**Comment by fdebuire** [comment]
Thanks, I didn't see this FAQ.
In my case the VNet is a custom one, this is not infrastructure created by the deployment of an AKS.
This is not a big deal as the cluster was only for testing purposes but it would be good if the Portal could warn that such a move will break the AKS. Or maybe have a note somewhere in https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/move-limitations/networking-move-limitations.
