### ISSUE TITLE
az aks create - fails for default VM size (westeurope)

### ISSUE THREAD

**Issue by Praxiss** [Azure/AKS#233]
Trying to create a production cluster in westeurope (where we have previously created dev and test environments) but get failures for default VM instance size (Standard_DS1_v2) - stating it is not available in the region. 

Possible to create using a different VM type, but renders previously built environments invalid.

**Comment by alhugot** [comment]
Hi @Praxiss , I have tried different vm, but none seems to work, event though they are listed from the protal. Which one did you use?
Thx
Alex

**Comment by Praxiss** [comment]
Hi

I am trying to create VM’s using the default for a Kubernetes cluster, which is Standard_DS2_V1

Regards

Pete

**Comment by fabiodouek** [comment]
What is the estimated date to get this issue resolved?

**Comment by Praxiss** [comment]
Hi

We have had to proceed to build the kubernetes instance for the production site in the eastus datacentre for now, but given that the audience for the web site is UK – this is not ideal.

We will look to continue with the site hosted on the eastus instance until capacity becomes available in westeurope – I would appreciate it if we could be informed of when this will happen from your team

Regards

Pete

**Comment by mebrein** [comment]
Bump. Microsoft: any updates on this? What's happening?

**Comment by Praxiss** [comment]
I haven’t received any notification that the capacity issues for the D series VM’s have been resolved

Thanks

Pete

**Comment by jalberto** [comment]
1 month and not even an updated timeline, is a really bad signal

**Comment by slack** [comment]
Closing this issue, head on over to #280 for updates, when they are available.

**Comment by sauryadas** [comment]
Please try alternate regions East US, Canada Central and Central US while we fix this issue.

**Comment by lehtiton** [comment]
@sauryadas it's not always that easy...we need to connect data center resouces via l2l gw that is available only in westeurope... Any estimate on this issue to be fixed. This is SO annoying!
