### ISSUE TITLE
Microsoft.ContainerService/managedClusters/stop/action and Microsoft.ContainerService/managedClusters/start/action are not available for RBAC

### ISSUE THREAD

**Issue by slacksach** [Azure/AKS#2331]
**What happened**:
We are attempting to create a Service Principal that can only start/stop an AKS Cluster without having to grant excessive permissions.
At present when the Service Principal attempts to call stop on an AKS Cluster the following RBAC error is generated
`does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/stop/action'`

Normally, we would just assign the Action to the Service Principal and it would be fine, however, this action does not exist

**What you expected to happen**:
We should be able to assign the following actions to the service principal
```
Microsoft.ContainerService/managedClusters/stop/action
Microsoft.ContainerService/managedClusters/start/action
```

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to create a role with permissions to stop/start an AKS cluster

**Comment by slacksach** [comment]
Closed as this issue is already covered

**Comment by rdvansloten** [comment]
> Closed as this issue is already covered

What's the solution to this issue? I can't find a link in this discussion and face the same issue.

**Comment by suraj2410** [comment]
@slacksach did you find any solution to this yet?

We are running into the same issue now and opened a new issue since this was closed without any solution or docs that state it
