### ISSUE TITLE
Unable to create Load Balancer after AKS upgrade to 1.20.5

### ISSUE THREAD

**Issue by smahadevaiah** [Azure/AKS#2332]
**What happened**:
After AKS was upgraded from 1.18.10 --> 1.19.9 --> 1.20.5. We are unable to create a service of type Load Balancer. The external-ip remains in pending state. Upon describing the service we get to see the following

`Warning  SyncLoadBalancerFailed  8s (x6 over 2m44s)  service-controller  Error syncing load balancer: failed to ensure load balancer: instance not found
`
It remains in this state forever.

All existing Load Balancers created prior to cluster upgrade have the following events:

`Warning  UpdateLoadBalancerFailed  20s (x22 over 18m)    service-controller  Error updating load balancer with new hosts map[aks-agentpool-89578836-vmss000000:{} aks-logging-89578836-vmss000000:{} aks-logging-89578836-vmss000001:{} aks-logging-89578836-vmss000002:{} aks-logging-89578836-vmss000003:{} aks-logging-89578836-vmss000004:{} aks-logging-89578836-vmss000005:{} aks-nodepool1-89578836-vmss00003r:{} aks-nodepool1-89578836-vmss00003s:{} aks-nodepool1-89578836-vmss00003t:{} aks-nodepool2-89578836-vmss000002:{} aks-nodepool7-89578836-vmss000000:{}]: instance not found`

Prior to upgrade of the cluster, we could successfully create both External and Internal load balancers.

**What you expected to happen**:
Successful creation of Load Balancer.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.5
- Size of cluster (how many worker nodes are in the cluster?) : 65
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) HTTP microservices
- Others:

**Comment by asubmani** [comment]
@smahadevaiah > Are you creating the LB during ingress controller deployment (Nginx, Traefik etc.)? It may be an issue with API deprecations at Kubernetes level.
e.g. https://github.com/kubernetes/kubernetes/pull/95813

**Comment by feiskyer** [comment]
Please open a support ticket if the problem still exists.

**Comment by NirajCricket** [comment]
HI @feiskyer , I am upgrading to 1.20.5 , till now I have no issues, can u confirm this bug is no longer exists in this version of AKS

**Comment by feiskyer** [comment]
@NirajCricket yes.

**Comment by NirajCricket** [comment]
In AKS we don't have 1.20.6 release , as I see in K8s release, does it mean ver 1.20.5 is impacted by the bug mentioned here?
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md
![image](https://user-images.githubusercontent.com/35249470/124531979-f1c77f80-de52-11eb-82a5-996453a6a7e9.png)

**Comment by NirajCricket** [comment]
submitted a new issue

**Comment by feiskyer** [comment]
you could upgrade to 1.20.7

**Comment by NirajCricket** [comment]
the version upgrade in the portal is showing 1.21 preview, what is recommended strategy n-1? which means 1.20.5?
