### ISSUE TITLE
Unable to load snd-aloop module on Azure's AKS Kernel

### ISSUE THREAD

**Issue by kpeiruza** [Azure/AKS#2335]
**What happened**:

We need to be able to load snd-aloop.ko on AKS Kernels in order to be able to emulate a sound card for Jitsi.

**What you expected to happen**:

Provide "extra-modules" package for Azure Kernel so we can load it.

**How to reproduce it (as minimally and precisely as possible)**:

modprobe snd-aloop

-------------
    root@aks-agentpool-10609346-vmss000001:/# modprobe -v snd-aloop
modprobe: FATAL: Module snd-aloop not found in directory /lib/modules/5.4.0-1046-azure

-------------
No sound drivers available:

Ubuntu 18.04:
root@aks-agentpool-10609346-vmss000001:/# dpkg -L linux-modules-extra-5.4.0-1046-azure | grep -c snd
0

Ubuntu 20.04:

dpkg -L linux-modules-extra-5.4.0-1047-azure | grep -c snd
0

---------------------
    ❯ k get nodes -o wide
NAME STATUS ROLES AGE VERSION INTERNAL-IP EXTERNAL-IP OS-IMAGE KERNEL-VERSION CONTAINER-RUNTIME
aks-agentpool-10609346-vmss000001 Ready agent 41m v1.19.9 10.240.0.115 <none> Ubuntu 18.04.5 LTS 5.4.0-1046-azure containerd://1.4.4+azure

-------------

**Comment by justindavies** [comment]
Hi there Kenneth, unfortunately, we don't have anything on the roadmap regarding being able to add extra modules to the host kernel for AKS.  Modifying the running kernel poses a number of problems from a support perspective as those modules may cause instability (which I admit would be unlikely).  

Whilst technically there would not be an issue with you compiling the module and inserting it into the host kernel, if updates need to be made to the kernel for security or feature issues, you would also need to recompile and redeploy again.  For situations like these, it make be worth looking at externalising the Jitsi part of the architecture outside of AKS onto a VMSS etc.
