### ISSUE TITLE
containerd can't pull multi-arch images from Azure Container Registry

### ISSUE THREAD

**Issue by jkanczler** [Azure/AKS#2337]
**What happened**:

We upgraded our Azure Kubernetes cluster to Kubernetes 1.19.9, and Microsoft offers that version relying on containerd. Our container images are pulled from an Azure Container Registry.

So now, when we would like to deploy images to the cluster, the containerd is failing in case of multi-arch images because of file size validation.

Executing the following command on one of our nodes:
sudo ctr -debug image pull itronicsp.azurecr.io/uiclearcollectionapi:19.02.1314.4515-ci.master

The Azure Container Registry will give a response with a header:
response.header.content-length=2213

And containerd will fail on the file size validation:
ctr: failed commit on ref "manifest-sha256:046e06776a7651104a187cbd8642f912d3de1ce311b535519f8c10cc0f115921": commit failed: "manifest-sha256:046e06776a7651104a187cbd8642f912d3de1ce311b535519f8c10cc0f115921" failed size validation: 2213 != 1737: failed precondition

But if we execute the command with adding -linux to the end:
sudo ctr -debug image pull itronicsp.azurecr.io/uiclearcollectionapi:19.02.1314.4515-ci.master-linux

Then containerd is able to download the image.

But long story short:
The pods that are deployed from multi-arch images will end up in ImagePullBackoff state.

**What you expected to happen**:
The pods that are deployed from multi-arch images should be deployed from Azure Container Registry.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a multi-arch image and push it to Azure Container registry.
2. Try to deploy the image from Azure Container registry to a Kubernetes cluster using containerd.
3. The pod will end up in ImagePullBackoff state

**Anything else we need to know?**:
containerd/containerd#5506

**Comment by jrefi** [comment]
Why are you forcing the switch to containerd? Seems like it is causing nothing but problems... No Docker in Docker... Multiarch broken... I am very angry at AKS right now for this HUGE breaking change to the API.

**Comment by miwithro** [comment]
@jkanczler is this still an ongoing issue?

**Comment by jkanczler** [comment]
@miwithro, we converted our images to single arch images, so it's not a problem anymore. But it can be still an issue for others.

**Comment by northtyphoon** [comment]
@jkanczler do you still have the multi-arch image itronicsp.azurecr.io/uiclearcollectionapi:19.02.1314.4515-ci.master?
