### ISSUE TITLE
Need document about what would happen to the pod running on the virtual node when the add-on is disabled

### ISSUE THREAD

**Issue by naioja** [Azure/AKS#2338]
**What happened**:
Currently there is no document talking about the expected behavior of the pods running on the virtual node when the virtual node add-on is disabled. 

Based on my test, when disabling the add-on, the virtual node status becomes to NotReady. The existing pod will be terminated, but since the node is not available, it gets stuck in the terminating status. A new pod is started because it is a deployment, but the new pod gets stuck in the pending status due to the same reason. 

![image](https://user-images.githubusercontent.com/6505576/118661670-a0eebf80-b7ef-11eb-81d9-88dd7794b6d8.png)

**What you expected to happen**:
Document what user should do to disable the add-on properly. Is there a way to prevent users from disabling the add-on if there are pods running on the virtual node?

**How to reproduce it (as minimally and precisely as possible)**:
Disable the virtual node add-on on a running AKS cluster.

**Comment by miwithro** [comment]
@naioja can you please open a ticket with support?
