### ISSUE TITLE
Could not create AKS cluster (westeurope)

### ISSUE THREAD

**Issue by alexanderknapstein** [Azure/AKS#234]
Hi,

I'm not able to create new AKS cluster in westeurope:

`az group create --name ilKubernetesGroup01 --location westeurope`
`az aks create --resource-group ilKubernetesGroup01 --name ilKube01 --node-count 1 --generate-ssh-keys`

Failed with:

> Deployment failed. Correlation ID: f253419f-65b5-48b8-8cf9-32be75b545da. Timeout while polling for control plane provisioning status

`az aks list` shows:

> [...] "location": "westeurope",
    "name": "ilKube01",
    **"provisioningState": "Failed",**
    "resourceGroup": "ilKubernetesGroup01",
    "servicePrincipalProfile": {
      "additionalProperties": {}, [...]

**Comment by RiddleMan** [comment]
I've experienced the same issue. I can't even delete this cluster.

**Comment by gwlava** [comment]
Same with me in westeurope.  Was working through the Microsoft Tutorial on AKS and was fine until they wanted me to upgrade the cluster to 1.8.2.  This failed with an error about CloudProviderProfile not defined and the cluster was in a Failed state.  Tried to delete the cluster, first time it failed to fully delete, the 2nd resource group with the VM's deleted but the cluster didn't.  2nd time it completed.  Went to recreate with same details and failed with the same error about Control Plane Timeout.  Tried to create another instance with different details and the same error occured.

**Comment by alexanderknapstein** [comment]
Hey @RiddleMan and @gwlava , I just retried it with another VM size and it worked: 

'az aks create --resource-group ilKubernetesGroup01 --name ilKube02 -s Standard_B1ms --node-count 1 --generate-ssh-keys'

that worked for me. In another project, the azure team told me they where out of DS1 VMs in Europe.

**Comment by slack** [comment]
Looks like you are good to go @alexanderknapstein I'll close out this issue. @gwlava @RiddleMan if you could create support tickets for the un-deletable clusters, that'd be great.
