### ISSUE TITLE
[known issue] unexpected VMSS capacity change

### ISSUE THREAD

**Issue by feiskyer** [Azure/AKS#2342]
**What happened**:

Since the VMSS and instances are cached in kube-controller-manager (cloud provider) memory (default TTL is 10 min), if there're some changes on the VMSS capacity (e.g. by autoscaler), then the capacity value would be outdated in memory. However, cloud provider sets `vmss.Sku` when updating network profile, which may cause unexpected capacity change on VMSS.

**Impacted clusters:**

The AKS clusters using internal LB or external LB together with UDR may be impacted by this issue when cloud provider tries to add VMSS into LoadBalancer backend address pool.

**Mitigation:**

Issue could be avoided if there're always an external LB and an internal LB service (if it is used) in the cluster.

**Fixes**:

The issue would be fixed by https://github.com/kubernetes-sigs/cloud-provider-azure/pull/630, but it's not available yet on AKS.

**Comment by axelgMS** [comment]
if I'm right, that Fix is deployed in AKS since mid-June.
Bug 9927172: Cloud provider should not change VMSS capacity on updates to network.

**Comment by feiskyer** [comment]
yes, this has been fixed in AKS.
