### ISSUE TITLE
encountering "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running" error in Docker Build Task when are running Self Hosted Azure DevOps Docker Agent inside the AKS

### ISSUE THREAD

**Issue by hegde89** [Azure/AKS#2343]
**What happened**:
encountering "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running" error in Docker Build Task when are running Self Hosted Azure DevOps Docker Agent inside the AKS, 

**What you expected to happen**:
Docker Build Command should execute 

**How to reproduce it (as minimally and precisely as possible)**:
Create an agent by following this document, and run CI with Docker Build task
[https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops](url)

**Anything else we need to know?**:
same this was working with 1.18.10

**Environment**: Dev/Prod
- Kubernetes version (use `kubectl version`): 1.19.9
- Size of cluster (how many worker nodes are in the cluster?) 01
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by awillows** [comment]
docker build will not function as of 1.19 as the container runtime changed to containerd on AKS. The are alternatives listed in the document below.

[https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#container-runtime-configuration](url)

As a note this change was announced last year via releases [https://github.com/Azure/AKS/releases/tag/2020-06-29](url)

**Comment by hegde89** [comment]
@awillows Thanks for the quick response
