### ISSUE TITLE
tunnel-front using much more than it's requested CPU

### ISSUE THREAD

**Issue by MattJeanes** [Azure/AKS#2344]
**What happened**:
The tunnel-front container is consistently using around 100 millicores in our AKS cluster but it's CPU request is only set to 10 millicores.

We have an alert which flags on containers consistently using more than 150% of their CPU request and this pod is flagging as using 1000%, far above any other pod in our cluster. We have excluded it from the alert as a work-around but I feel the problem should be fixed at the source.

**What you expected to happen**:
I would expect the tunnel-front container to either consume less CPU to match it's request or for the request to be increased to accurately show it's expected usage to avoid unexpected CPU throttling.

**How to reproduce it (as minimally and precisely as possible)**:
- Create an AKS cluster
- Check CPU request for tunnel-front pod
- Check actual CPU usage for tunnel-front pod

**Anything else we need to know?**:
This was previously raised as https://github.com/Azure/AKS/issues/1306 but that was more about memory than CPU

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"54684493f8139456e5d2f963b23cb5003c4d8055", GitTreeState:"clean", BuildDate:"2021-03-22T23:02:59Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
8 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Mostly HTTP microservices on ASP.NET Core
- Others:
Prometheus, Grafana, Keda, Kured, etc

**Comment by MattJeanes** [comment]
It seems that tunnel-front will soon be replaced with konnectivity (#2452) so hopefully this issue can be closed soon

**Comment by danimal521** [comment]
Yes, you are correct we are in the final stages of rolling out konnectivity which will deprecate tunnel-front.
