### ISSUE TITLE
[cluster-autoscaler] failures when scaling to large numbers of nodes or hitting quota limits

### ISSUE THREAD

**Issue by philwinder** [Azure/AKS#2345]
Hi there,

First some context. I've been testing the cluster-autoscaler implementation across a number of vendors and the vendor-specific capability to provision and destroy large numbers of nodes in a short amount of time. This is work for a client that is providing a service that allows users to submit and scale heavy ML workloads without them doing the heavy lifting.

This is quite a long post, and describes my working in full, because there are a range of improvements that could be made, but I don't know how you want to split them up, or if you want to tackle them at all.

I've been speaking with various MS folks and they agreed that writing down my experience was a good first step. Feel free to close this and replace it with smaller actionable issues if you see fit.

# Context

In general, the current open-source cluster-autoscaler implementation attempts to solve provisioning related issues by waiting, backing off, then restarting.

This implementation (in general) doesn't work well when the use case is rapidly spinning up and down large numbers of nodes. Because the more you add, the higher the chances are of one of those nodes not actually starting. Also, all clouds quota implementations are a giant puzzle which usually degrades into just "try it and see which quota fails next".

In summary, node's don't appear most of the time, and when they don't bad things start to happen.

# AKS Debugging Annoyances

For AKS in particular, the fact that you're hiding the cluster-autoscaler pod is more of a hindrance at this point. There are three public sources of information. 1) the portal, not much there other than the max scaling setting. 2) the configmap in the kube-system namespace. And 3) the logs that are only pushed to a log analytics workspace, which then have to be queried.

Of these, 1) doesn't offer any debugging info that is useful so I will disregard that. 2) this repeatedly disappears when the cluster-autoscaler is struggling, and even so, it reports a proprietary status, it's not particularly useful. 3) is the only real source of debugging information but the developer experience of getting access to this is a nightmare. Ignoring the fact that the setup is confusing and complicated, trying to read logs through a SQL-like UI is impossible. Even when you try to export (as CSV! why!) the ordering is messed up when you have a lot of logs which means you have to import them into a spreadsheet tool and resort and re-export or whatever. Just expose the pod logs already!

So I'll try to summarise what I can see in the logs for you, since it's hard to dump the logs. They include sensitive info anyway, so I'd be reluctant to share.

# Experiment

Below I present what happened (in time order).

1. AKS spun up using Terraform with the following settings (abridged):
```
Standard_D2_v4
East US 2
Node pool autoscaling enabled with max count set to 1000
Autoscaler settings:
    balance_similar_node_groups    = true
    expander                       = "random"
    new_pod_scale_up_delay         = "60s"
    scale_down_delay_after_add     = "1m"
    scale_down_unneeded            = "1m"
    scale_down_delay_after_failure = "3m"
    scale_down_delay_after_delete  = "1s"
```

2. K8s job created with a pod anti affinity to prevent pods being scheduled on the same node with a job that runs for 10 min. This was applied at approximately 9:20 BST (times relevant for images) :
```
apiVersion: batch/v1
kind: Job
metadata:
  name: job-scale-cpu
spec:
  parallelism: 1000
  template:
    metadata:
      name: job-scale-cpu
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: job-name
                operator: In
                values:
                - job-scale-cpu
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: busybox
          image: "quay.io/prometheus/busybox"
          command:
          - "/bin/sh"
          args:
          - "-c"
          - "sleep 600"
          resources:
            requests:
              cpu: "1500m"
      restartPolicy: Never
```

3. The cluster autoscaler kicks in and begins to create new nodes.

4. At around 09:40 BST I noticed that the number of nodes had been stable for longer than expected. Note that this doesn't happen all the time, and it happens at different points, randomly. The same happens if you hit a quota limit, I believe (TBC).

The configmap was working at this point but unfortunately I didn't capture an image. I can't quite remember which of the fields in the configmap were saying that the node was stuggling. It was either `unready` or `notStarted`. I'll try and rerun and catch this again.

---

**Edit** I tried this again and in fact the configmap stops updating. Below is two images that show that it took 10 minutes to get an update from the configmap.

First update at 13:03 (image taken 5 min later):

![Screenshot 2021-05-20 at 14 08 27](https://user-images.githubusercontent.com/8793723/118990032-711ff300-b97a-11eb-9ad5-e68bb8eb5d1f.png)

Next update at 13:13:
![Screenshot 2021-05-20 at 14 14 03](https://user-images.githubusercontent.com/8793723/118990137-87c64a00-b97a-11eb-8db5-0704b9b975aa.png)

---

5. Shortly after this the configmap is deleted and reset. Here's the first image:
![Screenshot 2021-05-20 at 09 43 59](https://user-images.githubusercontent.com/8793723/118967935-3a8aae00-b963-11eb-92b7-2f92d8b799ca.png)

I think this is expected because the open source cluster-autoscaler has a setting to restart if it's struggling to start nodes.

6. At this point I checked the Log UI, ran a query and after waiting for a few minutes for the logs to catch up, I confirmed that the cluster-autoscaler had indeed restarted at 09:43:50 BST.

Immediately before it restarted, the logs were just showing the normal cloud refresh loop that happened about once every two minutes and took about a second to complete.

7. But then a few minutes later, this:
![Screenshot 2021-05-20 at 09 44 09](https://user-images.githubusercontent.com/8793723/118968371-c1d82180-b963-11eb-97be-d74aa0345f49.png)

Note that the configmap is now not present at all. So the initialising message has gone, the CM is deleted, but it hasn't been replaced.

It's really hard to track what is happening at this point because I can't see the proprietary code (if it is public, please point me to it, I couldn't find it). But the logs are showing the normal startup procedure, refreshing the pod scheduling list and finally the cloud scheduling list. Then it goes back into the 2 minute cloud refresh routine again.

So I think that the same issues exists, the machine didn't spin up properly (or quotas), and for some reason the configmap doesn't get set.

The cluster-autoscaler is genuinely not doing anything at this point, because one of the machines it requested hasn't started.

There isn't much we can do except wait.

8. 09:58 BST Still nothing...
![Screenshot 2021-05-20 at 09 58 34](https://user-images.githubusercontent.com/8793723/118969129-9c97e300-b964-11eb-8dee-3063167bb8a7.png)

The logs showed that the cluster-autoscaler restarted again at 09:54 and again at 10:04. Again, this is probably expected, I can't recall what the default restart timeout is. Probably 10m!

9. At this point I got bored and had another meeting to go to so I just left it. When I came back...
![Screenshot 2021-05-20 at 10 18 52](https://user-images.githubusercontent.com/8793723/118970816-9145b700-b966-11eb-9e21-aed6842b257c.png)

Life Jim! At around 10:09 the logs do the normal cloud refresh, but this time it says:

```
scale_up.go:456] Best option to resize: aks-default-13330205-vmss
```

The lack of logs around this point prevent me from absolutely confirming what happened. But I don't think that the VM will suddenly just start working. In my experience if they start dead, they stay dead. So I assume that the cluster-autoscaler passed a threshold and continued.

I forget what the setting is called, but I have seen it somewhere. The issue with this is that if you set it too low then it doesn't give genuine laggards time to start and you get into the situation where you provision more than you need. So I'm not sure what the solution is here.

10. Eventually, at about 10:30 BST we get up to about 550 nodes. This is because by then many of the jobs have already completed serially,
![Screenshot 2021-05-20 at 11 14 11](https://user-images.githubusercontent.com/8793723/118970613-56dc1a00-b966-11eb-8651-fcfcf62592f0.png)

# Summary of Experiment

In summary, this experiment was to fan out 1000 jobs that lasted 10 minutes. Ideally that would take 10 minutes to complete, and cost about 1000*10 node-time units.

The experiment started at 0920 BST. But didn't finish until 1115 BST. So about 2 hours. The number of nodes used wasn't 1000, because many of the jobs ran serially. But you can imagine that we will have jobs that take hours and this won't happen.

I accept that at a minimum, it takes 5 minutes (ish) to start and connect a VM. So 15 minutes to complete this is what we should be aiming for.

At the moment then, this represents a rough 10x cost increase. 

We're paying 10x more than we should, because the cluster autoscaler is a) not fast enough and b) not responsive enough to failures. If we were using GPU machines rather than CPU machines (which is the eventual use case) then this is a massive amount of money to be wasting.

# Summary of Issue

Fundamentally this is a cost issue. We're paying 10x more than we should be paying, purely because the CA becomes unresponsive. But there is also a knock on issue with performance; it takes 10x longer than it should do. And you could compare across clouds too, and measure their "scaling performance".  

Apologies for the massive issue, but I thought it would be useful to paint a full picture of what we're trying to do here. I accept that this is a complex issue and needs splitting. Here are some suggestions:

- General AKS improvements
  - Improve the logging UX. Using the log analytics service is a horrible developer experience. Just expose the pod. Or have an "advanced" option to show system pods.
- AKS Autoscaler improvements
  - You know the quotas. You shouldn't be requesting more VMs that the user's quota allows. When you do the above happens when instead it could be as simple as a warning message "only requesting 10 machines because of quota limits" or whatever.
  - Fix that configmap not being created bug, if that's the way you want to continue to do it.
  - Incorporate vendor-specific knowledge into the recovery mechanism. You know that the VM hasn't started, because you have the power to check the status of the machine. Kick it. If you know it has started, but it hasn't connected to the cluster, you know that. Kick it.
- General Autoscaler improvements
  - Improve how failures are handled. You shouldn't need to restart the CA pod when VMs aren't starting. 
  - Improve recovery from failure. When VMs don't start, CA should be quick to spot this, log warning messages, and try to recover.
  - Faster scale-up. I don't really understand why we can't request the full machine allocation straight away. Why do it in batches?
  - Faster scale-down. As above. Why batches? I understand there are worries about eviction of pods but I don't think it's necessary to outright prevent big-bang scale downs.

# Future Work

There are two more things that I want to prove. 
1. ~~That this occurs consistently when quotas are in place, because this would be a good way to recreate.~~ - Done. Quotas do not seem to demonstrate this behaviour. You need a large quota and a large request to see this happening
2. ~~When VM problems/failures do occur, what does CA report the issue as? What does the configmap say? This is tricky, because you need to capture the moment just before the CA restarts.~~ - Done. The ConfigMap doesn't get updated at all.
3. Try with even more machines, to see if that makes it more repeatable. My guess is yes.
4. Come up with the mitigations as a work around. I think tuning the "VM ready" setting, whatever that is called, is probably the best route. You do end up with more nodes than requested, but that's ok if the percentage is small.

# Contact

If you need anything clarifying, I'd be happy to do that. If you'd like to talk, then let me know.

Thanks, Phil

**Comment by marwanad** [comment]
@philwinder 👋  thanks for the write-up. I can speak to some of those and happy to chat further via email and look at your case in more details. Please shoot me an email {my-github-alias}@microsoft.com (cc: @palma21 ). 

Just clarifying some points below and we can chat further into ways where we can improve your case.

> Improve the logging UX. Using the log analytics service is a horrible developer experience. Just expose the pod. Or have an "advanced" option to show system pods.

I totally agree that the logs aren't perfect. We have some [metrics](https://docs.microsoft.com/en-us/azure/aks/view-metrics#available-metrics) exposed and we are planning on adding more specifically related to the cloudprovider calls made to Azure. CA emits events on pods and on the configmap itself which should give some hints on its operations. Obviously, in a large scenario - it might not be the best experience to sift through those because k8s is going to coalesce them. Would love to chat more on how we can improve observability there.

> You know the quotas. You shouldn't be requesting more VMs that the user's quota allows. When you do the above happens when instead it could be as simple as a warning message "only requesting 10 machines because of quota limits" or whatever.

The problem is the part the code that makes up the decision is cloud-provider agnostic so when CA decides on a nodegroup, it has no information on quotas. The decision on the main loop depends on the k8s state in cluster state registry as well as scheduler simulation. So there's two options here:

- We check the quotas in the cloudprovider right before issuing a scale-up. Then, we report failure so this nodegroup backs-off immediately. CA will then try to scale another nodegroup.
- Check the quota in the cloudprovider logic, fulfil a partial scale, then issue a back-off so CA will fulfil the remaining from another pool.

I think this a good point and will look into both of those options.

> Fix that configmap not being created bug, if that's the way you want to continue to do it.
> Improve how failures are handled. You shouldn't need to restart the CA pod when VMs aren't starting.

The latter part isn't true. CA would only restart when there hasn't been activity in the main loop for long or its failing to talk to the apiserver for an extended time. The cloudprovider specific logic rarely blocks the main loop. 

**I highly suspect you were hitting (issue: #3835) on the upstream autoscaler repo**. There was a bug upstream with the bin packing simulations in large cluster cases that would stall the main loop. The recovery mechanism involves restarting CA to attempt to recover. The configmap stalling is also a symptom of that. Affinity rules also make the problem worse with the cost of simulations. There's currently rolling fix in AKS for that. 

Were you using a paid SLA cluster? The apiserver uptime can play a part in that as well.

> Improve recovery from failure. When VMs don't start, CA should be quick to spot this, log warning messages, and try to recover.
> You know that the VM hasn't started, because you have the power to check the status of the machine. Kick it. If you know it has started, but it hasn't connected to the cluster, you know that. Kick it.

That's what happens today in CA. I think you might know that already, when a VM fails to start it counts as unregistered node (the default is a 15 minute time interval - you can control that with --max-node-provision-time). CA then deletes this VM at the start of the loop when the 15 minute duration has elapsed. Those operations are emitted as events on the configmap and the count of those should be on the `nodes_count` metric with unregistered dimension.

> Faster scale-up. I don't really understand why we can't request the full machine allocation straight away. Why do it in batches?

It is done in batches based on the number of pending pods when a cluster snapshot is taken. If your pods come up in laddered fashion, you'll obviously need to send multiple requests to VMSS and VMSS will adjust its goal.

I can see you're already tweaking `--new-pod-scale-up` delay which is one way to address this scenario. 

I believe I covered most of your open questions with the above. Looking forward to chat more.

**Comment by philwinder** [comment]
Hi @marwanad,
Thank you for your reply and insightful comments.

I agree with everything you are saying. 

I just wanted to clarify that there aren't any outstanding questions, as such. They're all recommendations for enhancements. I understand that many of them are difficult.

But the main point I want to make clear is that as it stands, AKS is unsuitable for those with heavy and fast scaling requirements, because of opinions in CA. Of course this is true of other cloud vendors as well, but it is noticeably worse in AKS. So I'd love to help you bring it up to snuff (<- that's a funny old phrase).

You are right that it might be that binpacking bug. I just checked my notes and I used `v1.20.0` in other clouds, and I am indeed using a pod anti affinity (which is a bonafide use case by the way). This might account for differences. You say:

> There's currently rolling fix in AKS for that.

Could you point me to or provide a bit more information about this? Is it available now? Can I manually upgrade CA myself?

But with that said, the issues I see are AFTER an initial scale out. I.e. the first scale out works perfectly fine. Which at least suggests it was able to successfully plan a roll out the first time. After that though, that's when it gets stuck. So I'm not 100% convinced that this is the problem, but I don't have intimate knowledge of the old vs. new code, so I might be wrong.

Thanks again, and I'll send you a DM over email too to connect.

Phil

**Comment by philwinder** [comment]
Clarification regarding quotas. I've just tested again in a region with a really low quota, and with a 1000 node request, it fails pretty quickly with a `cloudProviderError`. And it does not get stuck.

So I think we can consider quotas irrelevant to this discussion, other than attempting to scale over your quota will prevent the scale from happening. I feel like this is fairly obvious anyway, and is unrelated to scaling speed/performance and this "CA is stuck" problem.

**Comment by marwanad** [comment]
Sharing some of the findings here. Starting from the initial run, a scale up was issued at some point to get from 1 -> 147 nodes. As more pods kept spinning up

```
2021-05-20T08:33:00Z   I0520 08:33:16.502510       1 filter_out_schedulable.go:79] Schedulable pods present
2021-05-20T08:33:00Z   I0520 08:33:16.503155       1 klogx.go:86] Pod default/job-scale-cpu-7fkxz is unschedulable
2021-05-20T08:33:00Z   I0520 08:33:16.503184       1 klogx.go:86] Pod default/job-scale-cpu-bsqt6 is unschedulable
2021-05-20T08:33:00Z   I0520 08:33:16.503193       1 klogx.go:86] Pod default/job-scale-cpu-plxm6 is unschedulable
2021-05-20T08:33:00Z   I0520 08:33:16.503202       1 klogx.go:86] Pod default/job-scale-cpu-h9rjr is unschedulable
2021-05-20T08:33:00Z   I0520 08:33:16.503210       1 klogx.go:86] Pod default/job-scale-cpu-8cn2t is unschedulable
**2021-05-20T08:33:00Z   I0520 08:33:16.503218**       1 klogx.go:86] Pod default/job-scale-cpu-jfb7q is unschedulable
2021-05-20T08:34:00Z   I0520 08:34:40.404575       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
2021-05-20T08:34:00Z   I0520 08:34:40.692120       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 287.496535ms
2021-05-20T08:36:00Z   I0520 08:36:40.692311       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
2021-05-20T08:36:00Z   I0520 08:36:40.959053       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 266.693548ms
2021-05-20T08:38:00Z   I0520 08:38:40.999001       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
2021-05-20T08:38:00Z   I0520 08:38:41.933329       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 934.279112ms
2021-05-20T08:40:00Z   I0520 08:40:41.991906       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
2021-05-20T08:40:00Z   I0520 08:40:42.193379       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 201.418862ms
2021-05-20T08:42:00Z   I0520 08:42:42.293761       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
2021-05-20T08:42:00Z   I0520 08:42:42.443750       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 149.935268ms
 ```

You can see the stall at: 0520 08:33:16.503218. This seems like during the binpacking simulation CA was stuck there taking forever to compute the simulations (**cluster autoscaler: issue: #3835**). Eventually, when the liveness threshold is exceeded, the pod gets restarted. 

It did see to struggle again when it started (which also aligns with the symptoms in the issue linked - restarts don't make you recover because you end up in the same simulation loop again):
```
2021-05-20T08:44:02Z   I0520 08:44:02.192443       1 klogx.go:86] Pod default/job-scale-cpu-77fks is unschedulable
2021-05-20T08:44:02Z   I0520 08:44:02.192450       1 klogx.go:86] Pod default/job-scale-cpu-tpj28 is unschedulable
2021-05-20T08:44:02Z   I0520 08:44:02.192457       1 klogx.go:86] Pod default/job-scale-cpu-8sz8b is unschedulable
2021-05-20T08:44:02Z   I0520 08:44:02.192772       1 klogx.go:86] 694 other pods are also unschedulable
2021-05-20T08:44:02Z   I0520 08:44:02.192435       1 klogx.go:86] Pod default/job-scale-cpu-p84vn is unschedulable
......
2021-05-20T08:52:03Z   I0520 08:52:03.906645       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
2021-05-20T08:52:04Z   I0520 08:52:04.193401       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 286.575197ms
2021-05-20T08:54:04Z   I0520 08:54:04.193608       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
2021-05-20T08:54:04Z   I0520 08:54:04.394873       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 201.22982ms
```
And again until it stabilized on the 2021-05-20T09:04:04Z run. You can see from the successful run how long it took to finish the simulation (~ 5 min):
```
2021-05-20T09:05:02Z   I0520 09:05:02.451006       1 klogx.go:86] Pod default/job-scale-cpu-cmpx5 is unschedulable
2021-05-20T09:05:02Z   I0520 09:05:02.451040       1 klogx.go:86] Pod default/job-scale-cpu-5shc7 is unschedulable
2021-05-20T09:05:02Z   I0520 09:05:02.451048       1 klogx.go:86] Pod default/job-scale-cpu-zv7bw is unschedulable
2021-05-20T09:05:02Z   I0520 09:05:02.451056       1 klogx.go:86] Pod default/job-scale-cpu-jblrk is unschedulable
2021-05-20T09:05:02Z   I0520 09:05:02.451255       1 klogx.go:86] 408 other pods are also unschedulable
2021-05-20T09:05:02Z   I0520 09:05:02.451070       1 klogx.go:86] Pod default/job-scale-cpu-p5bzs is unschedulable
2021-05-20T09:05:02Z   I0520 09:05:02.451131       1 klogx.go:86] Pod default/job-scale-cpu-j76lc is unschedulable
2021-05-20T09:05:02Z   I0520 09:05:02.451126       1 klogx.go:86] Pod default/job-scale-cpu-2ztr8 is unschedulable
2021-05-20T09:05:02Z   I0520 09:05:02.451122       1 klogx.go:86] Pod default/job-scale-cpu-jfb7q is unschedulable
2021-05-20T09:05:02Z   I0520 09:05:02.451116       1 klogx.go:86] Pod default/job-scale-cpu-7c2dj is unschedulable
2021-05-20T09:07:02Z   I0520 09:07:02.403826       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
2021-05-20T09:07:02Z   I0520 09:07:02.651861       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 247.982064ms
2021-05-20T09:09:02Z   I0520 09:09:02.894944       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 242.153369ms
2021-05-20T09:09:02Z   I0520 09:09:02.652741       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
2021-05-20T09:10:19Z   I0520 09:10:19.202936       1 scale_up.go:574] Final scale-up plan: [{aks-default-xxx-vmss 146->574 (max: 1000)}]
 ```

This stall seems to be coming from the main CA loop. Obviously, during those restarts and teardowns - the configmap is inaccessible.

We usually call those out on our release notes but missed that one (sorry!). It should be making its way to the rest of the regions next week.

**Comment by philwinder** [comment]
Update: we're working with Marwan offline to isolate the reasons for these issues. Will update here when further testing is complete.
