### ISSUE TITLE
How to differentiate the Normal VMSS and VMSS created through Kubernetes in Azure

### ISSUE THREAD

**Issue by pmanikantasai1996** [Azure/AKS#2346]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by pmanikantasai1996** [comment]
Do we have any way to exempt the AKS-created VMSS from while evaluating the Azure policy of VMSS?

**Comment by awillows** [comment]
Azure Policy allows exclusion of individual resources, resource groups, subscriptions or management groups so you could look at excluding the resource groups used by AKS (start MC_* by default).
