### ISSUE TITLE
Problem with aks clusters' certificates

### ISSUE THREAD

**Issue by raeder1986** [Azure/AKS#2347]
Good day! We have a problem with Azure AKS certificates. We checked all our AKS clusters and get that untill 2049 year our certificates should not expire. But today we get this on one of our clusters:

```
kubectl get pods -A
Unable to connect to the server: x509: certificate has expired or is not yet valid
```

After checking cluster like in instruction https://docs.microsoft.com/en-us/azure/aks/certificate-rotation we got this

```
az aks get-credentials -g XXX-rg -n XXX --file ./kubeconfig --context test > /dev/null
kubectl config --kubeconfig ./kubeconfig view --raw -o jsonpath="{.clusters[?(@.name == 'test')].cluster.certificate-authority-data}" | base64 -d | openssl x509 -text | grep -A2 Validity
        Validity
            Not Before: May 21 10:58:45 2019 GMT
            Not After : May 13 11:08:45 2049 GMT
```
			
Also in our Rancher environment we got for this cluster:

_Cluster health check failed: Failed to communicate with API server: Get "https://XXX:443/api/v1/namespaces/kube-system?timeout=45s": x509: certificate has expired or is not yet valid: current time 2021-05-21T06:04:08Z is after 2021-05-20T11:08:45Z_

At the same time your instruction says:
"AKS clusters created prior to March 2019 have certificates that expire after two years. Any cluster created after March 2019 or any cluster that has its certificates rotated have Cluster CA certificates that expire after 30 years. All other certificates expire after two years. To verify when your cluster was created, use kubectl get nodes to see the Age of your node pools."

So where are the promised 30-year certificates?

**Comment by awillows** [comment]
Cluster certificates are indeed 30 years as confirmed by the command you ran. The article mentions (in the paragraph you quoted) there are other certificates that only last 2 years, one of which is the kubectl client certificate. This can be viewed with a similar command:

```
kubectl config view --raw -o jsonpath="{.users[?(@.name == 'username')].user.client-certificate-data}" | base64 -d | openssl x509 -text | grep -A2 Validity

Validity
            Not Before: Jan 20 08:45:38 2021 GMT
            Not After : Jan 20 08:55:38 2023 GMT
```

If you pull the client certificate again with 'az aks get-credentials' does the problem persist?

**Comment by raeder1986** [comment]
> Cluster certificates are indeed 30 years as confirmed by the command you ran. The article mentions (in the paragraph you quoted) there are other certificates that only last 2 years, one of which is the kubectl client certificate. This can be viewed with a similar command:
> 
> ```
> kubectl config view --raw -o jsonpath="{.users[?(@.name == 'username')].user.client-certificate-data}" | base64 -d | openssl x509 -text | grep -A2 Validity
> 
> Validity
>             Not Before: Jan 20 08:45:38 2021 GMT
>             Not After : Jan 20 08:55:38 2023 GMT
> ```
> 
> If you pull the client certificate again with 'az aks get-credentials' does the problem persist?

Thank you very much! My mistake, I should check updating client's certificate first. I was confused by the error in Rancher, completely similar to the error on the certificate of the entire cluster. However, after a while, Rancher updated the client certificate and started working as if nothing had happened with this cluster.

**Comment by raeder1986** [comment]
At the same time after pulling new client certificate by 'az aks get-credentials', I restored kubectl, but... now I have my worker node status _NotReady_ by _kubectl get nodes_. 
Checking kubelet logs on worker VM gives me such repeated errors
`May 24 12:32:25 aks-rancher-XXX kubelet[11314]: I0524 12:32:25.068633   11314 csi_plugin.go:945] Failed to contact API server when waiting for CSINode publishing: Unauthorized
May 24 12:32:25 aks-rancher-XXX kubelet[11314]: E0524 12:32:25.105866   11314 kubelet.go:2268] node "aks-rancher-XXX" not found
May 24 12:32:25 aks-rancher-XXX kubelet[11314]: E0524 12:32:25.206087   11314 kubelet.go:2268] node "aks-rancher-XXX" not found
May 24 12:32:25 aks-rancher-XXX kubelet[11314]: E0524 12:32:25.306302   11314 kubelet.go:2268] node "aks-rancher-XXX" not found`

If I scale node number in AKS to 2 - the new worker works fine, but this cluster is old and not based on VMss, so I cannot just delete old worker and use new one....

**Comment by justindavies** [comment]
Hi @raeder1986 is this issue still happening on the cluster ?

**Comment by raeder1986** [comment]
> Hi @raeder1986 is this issue still happening on the cluster ?

Yep, previous error I solved only after rotating all certs of cluster like here https://docs.microsoft.com/en-us/azure/aks/certificate-rotation
Now I regular got errors with old-2-years clusters, cluster certificates for them are valid
`kubectl config view --raw -o jsonpath="{.clusters[?(@.name == 'XXX')].cluster.certificate-authority-data}" | base64 -d | openssl x509 -text | grep -A2 Validity
        Validity
            Not Before: Aug 19 08:05:32 2019 GMT
            Not After : Aug 11 08:15:32 2049 GMT`
but... clients certificates are not at the same time:
`kubectl config view --kubeconfig=./kubeconfig-1 --raw -o jsonpath="{.users[?(@.name == 'clusterUser_XXX')].user.client-certificate-data}" | base64 -d |
 openssl x509 -text | grep -A2 Validity
        Validity
            Not Before: Aug 19 08:05:32 2019 GMT
            Not After : Aug 18 08:15:32 2021 GMT`
And no using of `az aks get-credentials` can help, so for me there is one way now - rotate certs by az aks command

**Comment by miwithro** [comment]
@raeder1986 can you open a support case so we can remediate those clusters for you?

**Comment by huitingyeong** [comment]
> > Hi @raeder1986 is this issue still happening on the cluster ?
> 
> Yep, previous error I solved only after rotating all certs of cluster like here https://docs.microsoft.com/en-us/azure/aks/certificate-rotation
> Now I regular got errors with old-2-years clusters, cluster certificates for them are valid
> `kubectl config view --raw -o jsonpath="{.clusters[?(@.name == 'XXX')].cluster.certificate-authority-data}" | base64 -d | openssl x509 -text | grep -A2 Validity Validity Not Before: Aug 19 08:05:32 2019 GMT Not After : Aug 11 08:15:32 2049 GMT`
> but... clients certificates are not at the same time:
> `kubectl config view --kubeconfig=./kubeconfig-1 --raw -o jsonpath="{.users[?(@.name == 'clusterUser_XXX')].user.client-certificate-data}" | base64 -d | openssl x509 -text | grep -A2 Validity Validity Not Before: Aug 19 08:05:32 2019 GMT Not After : Aug 18 08:15:32 2021 GMT`
> And no using of `az aks get-credentials` can help, so for me there is one way now - rotate certs by az aks command

Hi I am facing the exact same issue in my environment. Any suggestions?

**Comment by jmk47912204** [comment]
Exactly !!! We are facing the same issue. So basically what we need to do in-order to avoid or resolve the cluster certificate issue in AKS, Is there a difference between **user client certificate data** and **cluster certificate authority data**? 

Because it's little confusing based on the [Microsoft WIKI](https://docs.microsoft.com/en-us/azure/aks/certificate-rotation)
