### ISSUE TITLE
Default Cluster User is a member of system:masters

### ISSUE THREAD

**Issue by raesene** [Azure/AKS#2348]
**What happened**:

After following the [AKS Quickstart](https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough) I noticed that the initial user provisioned with the cluster is a member of `system:masters` and uses client certificate authentication.

The `system:masters` group is hard-coded into the Kubernetes API server as having full access to the cluster API and it's rights cannot be easily revoked.

This could present a risk to AKS users if the client certificate was stolen or they wanted to rotate the credential when a staff member moves team or leaves the organization. Whilst I know it is possible to rotate the entire CA for a cluster this is, AFAIK, a disruptive operation which could take time for organizations to schedule.

**What you expected to happen**:

A better way of approaching this might be to create a clusterrolebinding to cluster-admin for the initial user and note in docs the process for removing that binding, should cluster users wish to revoke their access. Whilst it would not fully remove their access (they'd still have the rights of the `system:authenticated` group) it would largely allow for the credential's rights to be removed.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the AKS quick start, extract the client certificate from the generated Kubeconfig file and decode to show the group and user name used.

**Environment**:
- Kubernetes version - 1.19.9

**Comment by awillows** [comment]
The use of 'local users' can be blocked with an new feature in progress. 

[https://github.com/Azure/AKS/issues/2063](url)

Today clusters should be built to use Azure AD integration and limit who can use the --admin option with get-credentials or use this with the preview mentioned above. Details below:

[https://docs.microsoft.com/en-us/azure/aks/managed-aad](url)
