### ISSUE TITLE
Getting error when I try to stop/start aks

### ISSUE THREAD

**Issue by MatheusXavier** [Azure/AKS#2349]
I'm following [this guide](https://docs.microsoft.com/en-us/azure/aks/start-stop-cluster) where describe how to stop and start AKS, but when I'm running those commands:
```
az aks stop --name myAKSCluster --resource-group myResourceGroup
az aks start --name myAKSCluster --resource-group myResourceGroup
```
I'm getting the following error:
> Operation failed with status: 'Bad Request'. Details: Client Error: Availability Sets Not Supported

The error message doesn't say much, so I'm not sure what is causing that.

AKS data:
- Kubernetes version: 1.19.9
- Private clusters not enabled

**Comment by awillows** [comment]
If you originally deployed your cluster into an availability set (separate virtual machines) then unfortunately it wouldn't support stop/start. Currently only virtual machine scale set (VMSS) clusters are supported. See limitations on the following document.

[https://docs.microsoft.com/en-us/azure/aks/start-stop-cluster](url)

There is a backlog item in place to allow a conversion at a later date

[https://github.com/Azure/AKS/issues/2325](url)

**Comment by MatheusXavier** [comment]
Thanks for the answer, the cluster is using availability sets so as you describe that is the problem.

![image](https://user-images.githubusercontent.com/49682482/119700268-5e4d6880-be29-11eb-812d-a56e0fc054be.png)
