### ISSUE TITLE
[Feature Request] Allowing naming of VMSS

### ISSUE THREAD

**Issue by cavemandaveman** [Azure/AKS#2352]
**What happened**: When an AKS cluster is created, the VMSS is named `aks-${pool-name}-${random-numbers}-vmss`, even when you specify a custom name for the node pool.

**What you expected to happen**: Either set the VMSS name to the same as the node pool name, or allow specifying the VMSS name separately.

**Comment by justindavies** [comment]
Hi there would you be able to give me an understanding of why you want to change the naming convention?

**Comment by cavemandaveman** [comment]
> Hi there would you be able to give me an understanding of why you want to change the naming convention?

All of my resources have a standard naming convention according to company policy, but AKS resources are the only uncontrollable outliers. Besides policy, one use case is being able to set a variable for the VMSS name in terraform or ansible and then refer to to that variable for any subsequent references or modifications to the VMSS.

**Comment by palma21** [comment]
These are resources created and controlled by AKS, with the AKS naming convention, they shouldn't be seen as resources created by users. Could you clarify which kind of use cases you have to pass your own name? Eg. You mention:

> being able to set a variable for the VMSS name in terraform or ansible and then refer to that variable for any subsequent references or modifications to the VMSS.

but you can't do any direct modifications to the VMSS., you always need to use the AKS nodepool API (which allows you to use the name you provide) or that would render the cluster unsupported.
