### ISSUE TITLE
[Feature] Timezone modify in Windows container

### ISSUE THREAD

**Issue by keikhara** [Azure/AKS#2354]
We've heard many issues on timezone. You can now update this using tzutil and Set-Timezone command. Customer must be in 5B OS and above to run this.

**Comment by keikhara** [comment]
Timezone has been released. Please go to our docs for details.

**Comment by oak13** [comment]
Hi,

Could you explain further the requirement "Customer must be in 5B OS and above to run this.". Would there be documentation update regarding this feature? Thank you.
