### ISSUE TITLE
Azure Files Dynamic - PVC error

### ISSUE THREAD

**Issue by naioja** [Azure/AKS#2355]
**What happened**:
Trying to use Azure Files Dynamic persistent volume claims fails with the following error:

`Warning  ProvisioningFailed  16s (x2 over 2m31s)  persistentvolume-controller  (combined from similar events): Failed to provision volume with StorageClass "azurefile-premium": failed to create share kubernetes-dynamic-pvc-2550c87d-7766-4983-bd82-e80af50133f0 in account fb9e9f6391da24862904b74: storage.FileSharesClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidHeaderValue" Message="The value for one of the HTTP headers is not in the correct format.\nRequestId:be8ad929-601a-001d-1813-53eded000000\nTime:2021-05-27T16:16:58.9630407Z"`

The yaml file used:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-premium
  resources:
    requests:
      storage: 5Gi
```

The current status:
```
❯ k get pvc
NAME           STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS        AGE
my-azurefile   Pending                                      azurefile-premium   23m
```

**What you expected to happen**:
The dynamic provision of the share should fail with a more clear error related to the fact that we impose a 100GB minimum size.

**How to reproduce it (as minimally and precisely as possible)**:
Apply the yaml file attached above.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:15:16Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"6c90dbd9d6bb1ae8a4c0b0778752be06873e7c55", GitTreeState:"clean", BuildDate:"2021-03-22T23:02:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```
- Size of cluster (how many worker nodes are in the cluster?)
Two worker nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Testing Azure Files Storage.

**Comment by andyzhangx** [comment]
the minimum size of premium file is 100GiB, you could provision standard file share with 5GiB size, use `azurefile` storage class.
