### ISSUE TITLE
What k8s versions are currently supported by AKS?

### ISSUE THREAD

**Issue by amalic** [Azure/AKS#2356]
It is really difficult to find out which versions are currently supported by AKS.

Was expecting to quickly find the info here:
https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions

Looking at above website here, I was expecting as very first info which versions are currently supported and not an explanation how versioning works. Such Information might be helpful but should be treated as additional information and should be listed after the list of currently supported k8s versions.

**Comment by qpetraroia** [comment]
Hi @amalic,

Does this [chart ](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions#aks-kubernetes-release-calendar) seem confusing to you? We are always looking at ways to improve our docs!

You can also use this command to get a list of versions with the supported patch versions `az aks get-versions --location eastus --output table`.

**Comment by Porges** [comment]
> Does this [chart ](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions#aks-kubernetes-release-calendar) seem confusing to you? We are always looking at ways to improve our docs!
> 
> You can also use this command to get a list of versions with the supported patch versions `az aks get-versions --location eastus --output table`.

@qpetraroia I’d say that this table should be the first thing on the page, and retitled/relabelled.
