### ISSUE TITLE
Restricting metadata api access

### ISSUE THREAD

**Issue by MCKLMT** [Azure/AKS#2357]
My customer wants to restrict access to metadata api access using network policies.
Is there critical services on the cluster which need this metadata endpoint access?

Thanks

**Comment by MCKLMT** [comment]
@palma21 Could you take the question please?

**Comment by justindavies** [comment]
Mickaël, without access to the metadata API the customer will not be able to use aad pod identity, I'll double check to see if there are other issues that could arise from this

**Comment by MCKLMT** [comment]
Thanks @justindavies this is exactly the question the customer is asking for.

**Comment by MCKLMT** [comment]
Any news @justindavies please? My customer is waiting for this answer to push in production.
