### ISSUE TITLE
Unable to scale up or down: Agent VM size is not available (anymore)

### ISSUE THREAD

**Issue by mebrein** [Azure/AKS#236]
Currently I run a cluster consisting of 2 nodes, Standard_DS1_v2. When I try to scale up or scale down:

"The VM size of Agent is not allowed in your subscription in location 'westeurope'. Agent VM size 'Standard_DS1_v2' is available in locations: centraluseuap,eastus,eastus2,eastus2euap,southcentralus,southeastasia,westus2."

It used to work, but now the VM size isn't available anymore it leave me no option then to throw away the cluster and create a new one. Which leads to downtime, and would be unacceptable in a production situation.

**Comment by shahiddev** [comment]
AKS is in preview so this kind of thing isn't completely unexpected :)

It looks like there is an ongoing issue with AKS at the moment, alongside a capacity issue in westeurope 

Im sure this is all valuable information for the teams involved on the path to GA'ing AKS

**Comment by slack** [comment]
@mebrein hmm, AKS depends on the underlying compute provider in Azure for VM SKU information. Do you still see `Standard_DS1_v2` when running `az vm list-skus -l westeurope`?

**Comment by mebrein** [comment]
I ran the command, in the restrictions column it states NotAvailableForSubscription. So that means this VM is not available (anymore) to my subscription (Visual Studio Enterprise).

**Comment by jalberto** [comment]
I have same problem @slack in my case none of the D* VM are available now

**Comment by kvolkovich-sc** [comment]
Same problem. 

`az vm list-skus -l westeurope` - each of SKUs has field `NotAvailableForSubscription`.

For other locations, everything is OK.

`az vm list-usage --location westeurope -o table` - none of the limits are even close to the maximum.

**Comment by jalberto** [comment]
I have same results as @kvolkovich-sc

**Comment by Zimmergren** [comment]
Specifically for West Europe, Azure is having capacity issues at this time. 
@kvolkovich-sc @jalberto see #280 which is affecting westeurope heavily right now. Good to keep an eye on that thread for updates.

**Comment by jalberto** [comment]
@Zimmergren not only westeurope, I tried 4 different locaiton sin EU with same results, this is a wider problem

**Comment by Zimmergren** [comment]
You're right @jalberto. I've had Azure support confirm there are capacity problems across Europe right now. I am still waiting to hear back on a solution though.

**Comment by slack** [comment]
Closing this issue, to consolidate discussion at #280
