### ISSUE TITLE
sgx plugin on aks + firewall is not working

### ISSUE THREAD

**Issue by israel-gonzalezmedina** [Azure/AKS#2363]
**What happened**:

A simple confidential cluster works very well, only by following:
https://docs.microsoft.com/en-us/azure/confidential-computing/confidential-nodes-aks-get-started

If I create an aks behind a firewall following the documentation from:
https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic#restrict-egress-traffic-using-azure-firewall

The only difference is that I create a cluster with a confidential computation VM with size Standard_DC2s_v2. The error is when
Verifying sgx-plugins pods

kubectl get pods --all-namespaces

kube-system   sgx-plugin-r6mmr                      0/1     Init:CrashLoopBackOff   5          4m54s
kube-system   sgx-webhook-787f99b5dc-qh2d5          0/1     Init:CrashLoopBackOff   4          5m50s

**What you expected to happen**:
the pods will be on running status

**How to reproduce it (as minimally and precisely as possible)**:

- Define a set of environment variables to be used in resource creations.

# Create Resource Group

az group create --name $RG --location $LOC

# Create a virtual network with two subnets to host the AKS cluster and the Azure Firewall. 
# Each will have their own subnet. Let's start with the AKS network.

az network vnet create \
    --resource-group $RG \
    --name $VNET_NAME \
    --location $LOC \
    --address-prefixes 10.42.0.0/16 \
    --subnet-name $AKSSUBNET_NAME \
    --subnet-prefix 10.42.1.0/24

# Dedicated subnet for Azure Firewall (Firewall name cannot be changed)

az network vnet subnet create \
    --resource-group $RG \
    --vnet-name $VNET_NAME \
    --name $FWSUBNET_NAME \
    --address-prefix 10.42.2.0/24    

## Create and set up an Azure Firewall with a UDR    

# Create three standard SKU public IP resource that will be used as the Azure Firewall frontend address.

az network public-ip create -g $RG -n $FWPUBLICIP_NAME -l $LOC --sku "Standard"

# Install Azure Firewall preview CLI extension

az extension add --name azure-firewall

# Deploy Azure Firewall

az network firewall create -g $RG -n $FWNAME -l $LOC --enable-dns-proxy true

# Configure Firewall IP Config

az network firewall ip-config create -g $RG -f $FWNAME -n $FWIPCONFIG_NAME --public-ip-address $FWPUBLICIP_NAME --vnet-name $VNET_NAME

# Capture Firewall IP Address for Later Use

FWPRIVATE_IP=$(az network firewall show -g $RG -n $FWNAME --query "ipConfigurations[0].privateIpAddress" -o tsv)
FWPUBLIC_IP_ID=$(az network firewall show -g $RG -n $FWNAME --query "ipConfigurations[0].publicIpAddress.id" -o tsv)
FWPUBLIC_IP=$(az network public-ip show --ids $FWPUBLIC_IP_ID --query "ipAddress" -o tsv)
or
FWPUBLIC_IP=$(az network public-ip show -g $RG -n $FWPUBLICIP_NAME --query "ipAddress" -o tsv)

# Create UDR and add a route for Azure Firewall

az network route-table create -g $RG -l $LOC --name $FWROUTE_TABLE_NAME
az network route-table route create -g $RG --name $FWROUTE_NAME --route-table-name $FWROUTE_TABLE_NAME \
    --address-prefix 0.0.0.0/0 --next-hop-type VirtualAppliance --next-hop-ip-address $FWPRIVATE_IP 
az network route-table route create -g $RG --name $FWROUTE_NAME_INTERNET --route-table-name $FWROUTE_TABLE_NAME \
    --address-prefix $FWPUBLIC_IP/32 --next-hop-type Internet

# Add FW Network Rules needed for aks

az network firewall network-rule create -g $RG -f $FWNAME --collection-name 'aksfwnr' -n 'apiudp' \
    --protocols 'UDP' --source-addresses '*' --destination-addresses "AzureCloud.$LOC" \
    --destination-ports 1194 --action allow --priority 100
az network firewall network-rule create -g $RG -f $FWNAME --collection-name 'aksfwnr' -n 'apitcp' \
    --protocols 'TCP' --source-addresses '*' --destination-addresses "AzureCloud.$LOC" \
    --destination-ports 9000

az network firewall network-rule create -g $RG -f $FWNAME --collection-name 'aksfwnr' -n 'time' \
    --protocols 'UDP' --source-addresses '*' --destination-fqdns 'ntp.ubuntu.com' --destination-ports 123

az network firewall network-rule create -g $RG -f $FWNAME --collection-name 'aksfwnr' -n 'dnsserver' \
    --protocols 'UDP' --source-addresses '*' --destination-fqdns 10.41.0.10 --destination-ports 53
# Add FW Application Rules

az network firewall application-rule create -g $RG -f $FWNAME --collection-name 'aksfwar' -n 'fqdn' \
    --source-addresses '*' --protocols 'http=80' 'https=443' --fqdn-tags "AzureKubernetesService" \
    --action allow --priority 100

# Inspect the final firewall

az network firewall show -g $RG -n $FWNAME

## Associate the route table to AKS

# Associate route table with next hop to Firewall to the AKS subnet

az network vnet subnet update -g $RG --vnet-name $VNET_NAME --name $AKSSUBNET_NAME --route-table $FWROUTE_TABLE_NAME

## Deploy AKS with outbound type of UDR to the existing network

# Create SP and Assign Permission to Virtual Network

az ad sp create-for-rbac -n "${PREFIX}sp" --skip-assignment

it will return an exit like:
{
  "appId": "xxxxx",
  "displayName": "xxx",
  "name": "xxx",
  "password": "xxxx",
  "tenant": "xxx"
}

Now replace the APPID and PASSWORD below with the service principal appid and service principal password autogenerated by the previous command output. We'll reference the VNET resource ID to grant the permissions to the service principal so AKS can deploy resources into it.

# Assign SP Permission to VNET

az role assignment create --assignee $APPID --scope $VNETID --role "Network Contributor"

## Deploy AKS

# Set the value for the subnet ID

SUBNETID=$(az network vnet subnet show -g $RG --vnet-name $VNET_NAME --name $AKSSUBNET_NAME --query id -o tsv)

# Create aks confidential computing cluster

az aks create -g $RG -n $AKSNAME -l $LOC \
  --node-count 1 --generate-ssh-keys \
  --network-plugin $PLUGIN \
  --outbound-type userDefinedRouting \
  --service-cidr 10.41.0.0/16 \
  --dns-service-ip 10.41.0.10 \
  --docker-bridge-address 172.17.0.1/16 \
  --vnet-subnet-id $SUBNETID \
  --service-principal $APPID \
  --client-secret $PASSWORD \
  --api-server-authorized-ip-ranges $FWPUBLIC_IP/32 \
  --enable-addon confcom

# Add pool node
az aks nodepool add --cluster-name $AKSNAME --resource-group $RG --name confcompool1 --node-vm-size Standard_DC2s_v2 --node-count 1

# Check the node list
az aks nodepool list --cluster-name $AKSNAME --resource-group $RG

# Retrieve your IP address
use any that works
CURRENT_IP=$(dig @resolver1.opendns.com ANY myip.opendns.com +short)
CURRENT_IP=$(curl checkip.amazonaws.com)
CURRENT_IP=$(curl ifconfig.me)
CURRENT_IP=$(curl icanhazip.com)
CURRENT_IP=$(curl ipecho.net/plain)
CURRENT_IP=$(curl ifconfig.co)

# Add to AKS approved list (better add it on the azure console for not to remove others access)
az aks update -g $RG -n $AKSNAME --api-server-authorized-ip-ranges $FWPUBLIC_IP/32,$CURRENT_IP/32

# Use the [az aks get-credentials][az-aks-get-credentials] command to configure kubectl to connect to your newly created Kubernetes cluster.

az aks get-credentials -g $RG -n $AKSNAME

# Verify nodes

kubectl get nodes
NAME                                   STATUS   ROLES   AGE     VERSION
aks-confcompool1-15977364-vmss000000   Ready    agent   6m37s   v1.19.11
aks-nodepool1-15977364-vmss000000      Ready    agent   18m     v1.19.11

# Verify sgx-plugins pods

kubectl get pods --all-namespaces

kube-system   sgx-plugin-8n6bj                      0/1     Init:CrashLoopBackOff   5          5m42s
kube-system   sgx-webhook-787f99b5dc-mwfps          0/1     Init:CrashLoopBackOff   7          18m

logs:
kubectl -n kube-system logs sgx-plugin-8n6bj
Error from server (BadRequest): container "sgx-plugin" in pod "sgx-plugin-8n6bj" is waiting to start: PodInitializing

kubectl -n kube-system logs sgx-webhook-787f99b5dc-mwfps
Error from server (BadRequest): container "sgx-webhook-server" in pod "sgx-webhook-787f99b5dc-mwfps" is waiting to start: PodInitializing
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", GitTreeState:"clean", BuildDate:"2021-05-13T17:14:18Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by israel-gonzalezmedina** [comment]
this is the kubeclt descibe command output:
`Name:         sgx-plugin-8n6bj
Namespace:    kube-system
Priority:     0
Node:         aks-confcompool1-15977364-vmss000000/10.42.1.35
Start Time:   Wed, 02 Jun 2021 12:29:52 -0300
Labels:       app=sgx-plugin
              controller-revision-hash=7684bdd8c8
              pod-template-generation=1
Annotations:  <none>
Status:       Pending
IP:           10.42.1.39
IPs:
  IP:           10.42.1.39
Controlled By:  DaemonSet/sgx-plugin
Init Containers:
  sgx-plugin-init:
    Container ID:  containerd://6edc5d9e5d32f573a3061b56795993e67254216a2f73dfea5d1823c714d1164f
    Image:         mcr.microsoft.com/aks/acc/sgx-plugin:0.4
    Image ID:      sha256:c998684e0e4ee9b4244f4ebeb40824832bd72356b06eaff9eba5c69fe9237d9b
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/sgx_epchook
    Args:
      -register
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Wed, 02 Jun 2021 17:59:02 -0300
      Finished:     Wed, 02 Jun 2021 17:59:12 -0300
    Ready:          False
    Restart Count:  67
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from sgx-plugin-token-fd7bk (ro)
Containers:
  sgx-plugin:
    Container ID:  
    Image:         mcr.microsoft.com/aks/acc/sgx-plugin:0.4
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/sgx_device_plugin
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     250m
      memory:  200Mi
    Requests:
      cpu:     250m
      memory:  100Mi
    Environment:
      KUBERNETES_PORT_443_TCP_ADDR:  aks-cscore-aks-cscore-sgx-r-1c70d1-404ffb38.hcp.westus.azmk8s.io
      KUBERNETES_PORT:               tcp://aks-cscore-aks-cscore-sgx-r-1c70d1-404ffb38.hcp.westus.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://aks-cscore-aks-cscore-sgx-r-1c70d1-404ffb38.hcp.westus.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       aks-cscore-aks-cscore-sgx-r-1c70d1-404ffb38.hcp.westus.azmk8s.io
    Mounts:
      /dev/sgx from sgxdevices (ro)
      /dev/sgx/enclave from sgx-enclave (ro)
      /dev/sgx/provision from sgx-provision (ro)
      /var/lib/kubelet/device-plugins from kubeletsockets (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from sgx-plugin-token-fd7bk (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kubeletsockets:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/device-plugins
    HostPathType:  
  sgxdevices:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/sgx
    HostPathType:  DirectoryOrCreate
  sgx-enclave:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/sgx/enclave
    HostPathType:  CharDevice
  sgx-provision:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/sgx/provision
    HostPathType:  CharDevice
  sgx-plugin-token-fd7bk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  sgx-plugin-token-fd7bk
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     :NoExecute
                 :NoSchedule
                 CriticalAddonsOnly
Events:
  Type     Reason   Age                       From                                           Message
  ----     ------   ----                      ----                                           -------
  Warning  BackOff  2m16s (x1465 over 5h31m)  kubelet, aks-confcompool1-15977364-vmss000000  Back-off restarting failed container
`

**Comment by israel-gonzalezmedina** [comment]
`
kubectl describe daemonset sgx-plugin
Name:           sgx-plugin
Selector:       app=sgx-plugin
Node-Selector:  <none>
Labels:         addonmanager.kubernetes.io/mode=Reconcile
                app=sgx-plugin
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 2
Current Number of Nodes Scheduled: 2
Number of Nodes Scheduled with Up-to-date Pods: 2
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 2 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=sgx-plugin
  Service Account:  sgx-plugin
  Init Containers:
   sgx-plugin-init:
    Image:      mcr.microsoft.com/aks/acc/sgx-plugin:0.4
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/local/bin/sgx_epchook
    Args:
      -register
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:       <none>
  Containers:
   sgx-plugin:
    Image:      mcr.microsoft.com/aks/acc/sgx-plugin:0.4
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/local/bin/sgx_device_plugin
    Limits:
      cpu:     250m
      memory:  200Mi
    Requests:
      cpu:        250m
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /dev/sgx from sgxdevices (ro)
      /dev/sgx/enclave from sgx-enclave (ro)
      /dev/sgx/provision from sgx-provision (ro)
      /var/lib/kubelet/device-plugins from kubeletsockets (rw)
  Volumes:
   kubeletsockets:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/device-plugins
    HostPathType:  
   sgxdevices:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/sgx
    HostPathType:  DirectoryOrCreate
   sgx-enclave:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/sgx/enclave
    HostPathType:  CharDevice
   sgx-provision:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/sgx/provision
    HostPathType:  CharDevice
Events:
  Type    Reason            Age   From                  Message
  ----    ------            ----  ----                  -------
  Normal  SuccessfulCreate  21m   daemonset-controller  Created pod: sgx-plugin-pwkqf
`

**Comment by israel-gonzalezmedina** [comment]
`kubectl describe pod sgx-webhook-787f99b5dc-mwfps
Name:         sgx-webhook-787f99b5dc-mwfps
Namespace:    kube-system
Priority:     0
Node:         aks-nodepool1-15977364-vmss000000/10.42.1.4
Start Time:   Wed, 02 Jun 2021 12:18:04 -0300
Labels:       app=sgx-webhook
              pod-template-hash=787f99b5dc
Annotations:  <none>
Status:       Pending
IP:           10.42.1.11
IPs:
  IP:           10.42.1.11
Controlled By:  ReplicaSet/sgx-webhook-787f99b5dc
Init Containers:
  sgx-webhook-init:
    Container ID:  containerd://2fd7444f43ccacdddd5c1e65af9689a712a5d7a3dc23292cfa1ac03a5d56b330
    Image:         mcr.microsoft.com/aks/acc/sgx-webhook:0.9
    Image ID:      sha256:cb383f958fac2a07cec0f9c934ddc4ee0b328d9be0291f0e712ef0df06b579b3
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/initc
      -label
      kubernetes.azure.com/managedby=aks
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Wed, 02 Jun 2021 18:09:05 -0300
      Finished:     Wed, 02 Jun 2021 18:09:24 -0300
    Ready:          False
    Restart Count:  66
    Environment:
      MUTATE_CONFIG:      sgx-mutate-config
      VALIDATE_CONFIG:    sgx-validate-config
      WEBHOOK_SERVICE:    sgx-webhook
      WEBHOOK_NAMESPACE:  kube-system (v1:metadata.namespace)
    Mounts:
      /etc/webhook/certs from certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from sgx-webhook-token-58x9p (ro)
Containers:
  sgx-webhook-server:
    Container ID:  
    Image:         mcr.microsoft.com/aks/acc/sgx-webhook:0.9
    Image ID:      
    Port:          8443/TCP
    Host Port:     0/TCP
    Command:
      /usr/local/bin/webhook
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     250m
      memory:  200Mi
    Requests:
      cpu:     250m
      memory:  100Mi
    Liveness:  http-get https://:sgx-webhook-api/healthz delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment:
      KUBERNETES_PORT_443_TCP_ADDR:  aks-cscore-aks-cscore-sgx-r-1c70d1-404ffb38.hcp.westus.azmk8s.io
      KUBERNETES_PORT:               tcp://aks-cscore-aks-cscore-sgx-r-1c70d1-404ffb38.hcp.westus.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://aks-cscore-aks-cscore-sgx-r-1c70d1-404ffb38.hcp.westus.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       aks-cscore-aks-cscore-sgx-r-1c70d1-404ffb38.hcp.westus.azmk8s.io
    Mounts:
      /etc/webhook/certs from certs (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from sgx-webhook-token-58x9p (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  certs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  sgx-webhook-token-58x9p:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  sgx-webhook-token-58x9p
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                     From                                        Message
  ----     ------   ----                    ----                                        -------
  Normal   Pulled   50m (x59 over 5h55m)    kubelet, aks-nodepool1-15977364-vmss000000  Container image "mcr.microsoft.com/aks/acc/sgx-webhook:0.9" already present on machine
  Warning  BackOff  34s (x1453 over 5h54m)  kubelet, aks-nodepool1-15977364-vmss000000  Back-off restarting failed container`

**Comment by israel-gonzalezmedina** [comment]
`kubectl describe replicaset sgx-webhook-787f99b5dc
Name:           sgx-webhook-787f99b5dc
Namespace:      kube-system
Selector:       app=sgx-webhook,pod-template-hash=787f99b5dc
Labels:         app=sgx-webhook
                pod-template-hash=787f99b5dc
Annotations:    deployment.kubernetes.io/desired-replicas: 1
                deployment.kubernetes.io/max-replicas: 2
                deployment.kubernetes.io/revision: 1
Controlled By:  Deployment/sgx-webhook
Replicas:       1 current / 1 desired
Pods Status:    0 Running / 1 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=sgx-webhook
                    pod-template-hash=787f99b5dc
  Service Account:  sgx-webhook
  Init Containers:
   sgx-webhook-init:
    Image:      mcr.microsoft.com/aks/acc/sgx-webhook:0.9
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/local/bin/initc
      -label
      kubernetes.azure.com/managedby=aks
    Environment:
      MUTATE_CONFIG:      sgx-mutate-config
      VALIDATE_CONFIG:    sgx-validate-config
      WEBHOOK_SERVICE:    sgx-webhook
      WEBHOOK_NAMESPACE:   (v1:metadata.namespace)
    Mounts:
      /etc/webhook/certs from certs (rw)
  Containers:
   sgx-webhook-server:
    Image:      mcr.microsoft.com/aks/acc/sgx-webhook:0.9
    Port:       8443/TCP
    Host Port:  0/TCP
    Command:
      /usr/local/bin/webhook
    Limits:
      cpu:     250m
      memory:  200Mi
    Requests:
      cpu:        250m
      memory:     100Mi
    Liveness:     http-get https://:sgx-webhook-api/healthz delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/webhook/certs from certs (ro)
  Volumes:
   certs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
Events:         <none>`

**Comment by agowdamsft** [comment]
ack the issue.

**Comment by israel-gonzalezmedina** [comment]
hey @agowdamsft 
Sorry... what does ack the issue means?

**Comment by agowdamsft** [comment]
@israel-gonzalezmedina , I am working on this issue and will update you when I have more details to share here. Also feel free to open a support ticket if you would like to track it that way.

**Comment by agowdamsft** [comment]
During our review and testing we noted the add-on dependency with port 443 for communication. In our testing we found allowing port 443 deploys add-on successfully. I will confirm the next steps the recommendation shortly.

**Comment by israel-gonzalezmedina** [comment]
great.. I myself add some rules for the firewall like access to intel sgx sites like:
az network firewall application-rule create  -g $RG -f $FWNAME  --collection-name "intel" --name "sgxplugin" --protocols http=80 https=443 --source-addresses "*" --action "Allow" --target-fqdns "*download.01.org" "*apt.llvm.org" "*packages.microsoft.com" "*github.com" "*raw.githubusercontent.com" --priority 200

but it didn't work.
thanks

**Comment by agowdamsft** [comment]
Hi @israel-gonzalezmedina we are still doing a root cause analysis to recommend what FQDN should be in the allowed list. We did a test just allowing communication on 443 targeting just the port (no FQDN) and the plugin works. While we investigate, a quick workaround would be to skip adding the addon and just choose confidential computing SKU and mount the volumes in the deployment yaml. jus like the below. This should allow launching confidential containers.  

containers:
      - name: containername
        image: reg:1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev-sgx
          mountPath: /dev/sgx
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev-sgx
        hostPath:
          path: /dev/sgx

**Comment by agowdamsft** [comment]
@israel-gonzalezmedina we have identified the issue and are working to release this fix. When fix is rolled out adding the AKS Cluster API to the FW allowed list as documented here https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic#azure-global-required-fqdn--application-rules. For time being you can either add the kubernetes cluster API IP address or allow 443 traffic as mentioned in the above comments.

**Comment by israel-gonzalezmedina** [comment]
thanks @agowdamsft . I tried the volumen option, because as is a production cluster I can not allow 443 traffic. However, I disabled the confcom addon and tried to deploy the sample job yaml with your considerations and it didn't work. I attached the file in the comment. What am I doing wrong?
`
apiVersion: batch/v1
kind: Job
metadata:
  name: sgx-test
  labels:
    app: sgx-test
spec:
  template:
    metadata:
      labels:
        app: sgx-test
    spec:
      containers:
      - name: sgxtest
        image: oeciteam/sgx-test:1.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            sgx.intel.com/epc: 5Mi # This limit will automatically place the job into a confidential computing node and mount the required driver volumes. Alternatively, you can target deployment to node pools with node selector.
        volumeMounts:
          # sgx plugins
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev-sgx
          mountPath: /dev/sgx
        # sgx security
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL            
      restartPolicy: Never
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev-sgx
        hostPath:
          path: /dev/sgx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - Standard_DC1s_v2
                - Standard_DC2s_v2
                - Standard_DC4s_v2
                - Standard_DC8_v2               
  backoffLimit: 0
`

**Comment by agowdamsft** [comment]
@israel-gonzalezmedina there are 2 workarounds until the fix is released

1. Add the AKS cluster API IP address to the allow list. Firewall logs should report the IP. When the rules are in place remove and add the addon.
2. Don't use the SGX add on and mount the SGX driver volumes directly
   Here is an flask application working deployment

apiVersion: v1 
kind: Pod 
metadata: 
  name: app-sgx 
  labels: 
    app: app-sgx 
spec: 
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
            - Standard_DC1s_v2
  restartPolicy: Never 
  containers: 
  - name: app-sgx 
    image: banne01/convert:flask-sgx-dcap
    volumeMounts: 
    - name: dev-sgx 
      mountPath: /dev/sgx/enclave 
    securityContext: 
      privileged: true 
    ports: 
    - containerPort: 5000 
      name: http 
      protocol: TCP 
  volumes: 
  - name: dev-sgx 
    hostPath: 
      path: /dev/sgx/enclave 
      type: CharDevice

**Comment by agowdamsft** [comment]
Here is the yaml raw file https://raw.githubusercontent.com/agowdamsft/confcontainerscsample/master/test-flask-sample-no-plugin.yml

**Comment by israel-gonzalezmedina** [comment]
I thank you for the answer @agowdamsft 
the yaml you sent me works very well. However, my application stuck at containerCreating. The checking of the events creatingstamp returns
dev         18m         Warning   FailedMount            pod/dispatcher-7fd85b67b7-m6dj9    MountVolume.SetUp failed for volume "pvc-f41b627f-71e1-4708-b1aa-aae7172bba76" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/5ebfd2fe-e2b6-4251-82dd-d61cb11a3154/volumes/kubernetes.io~azure-file/pvc-f41b627f-71e1-4708-b1aa-aae7172bba76 --scope -- mount -t cifs -o actimeo=30,cache=strict,dir_mode=0777,file_mode=0777,gid=0,mfsymlinks,uid=0,vers=3.0,<masked> //ffb60b94ee6a44082a8e1b4.file.core.windows.net/kubernetes-dynamic-pvc-f41b627f-71e1-4708-b1aa-aae7172bba76 /var/lib/kubelet/pods/5ebfd2fe-e2b6-4251-82dd-d61cb11a3154/volumes/kubernetes.io~azure-file/pvc-f41b627f-71e1-4708-b1aa-aae7172bba76
Output: Running scope as unit: run-r1b519a2c564a44b3a21eee87df36116c.scope
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

On the other hand I tested the job from the documentation, removing the limit epc memory part of the yaml. the container was created but with the log error:
oe_create_helloworld_enclave(): result=21 (OE_PLATFORM_ERROR)
2021-06-14T13:59:48.000000Z [(H)ERROR] tid(0x7fee13d94740) | enclave_create with ENCLAVE_TYPE_SGX1 type failed (err=0x1) (oe_result_t=OE_PLATFORM_ERROR) [/source/host/sgx/sgxload.c:oe_sgx_create_enclave:475]
2021-06-14T13:59:48.000000Z [(H)ERROR] tid(0x7fee13d94740) | :OE_PLATFORM_ERROR [/source/host/sgx/create.c:oe_sgx_build_enclave:658]
2021-06-14T13:59:48.000000Z [(H)ERROR] tid(0x7fee13d94740) | :OE_PLATFORM_ERROR [/source/host/sgx/create.c:oe_create_enclave:784]

Hope the above information can help. I will try with adding the AKS cluster API IP address to the allow list.

**Comment by agowdamsft** [comment]
@israel-gonzalezmedina seems like the problem is with this hello world job that is probably taking a dependency on the plugin components. If you have other SGX apps you should try running them.

Also just letting you know the release started this Monday an is in few US regions already. If you were unsuccessful with adding IP to FW and re deploying the plugin you can wait until end to this week for this fix.
