### ISSUE TITLE
AKS Ingress still returning 404 

### ISSUE THREAD

**Issue by gkoudjou** [Azure/AKS#2364]
Hello,

On an AKS cluster, i'm facing an issue similar to this one -> https://github.com/Azure/AKS/issues/635

I have a fresh cluster +
- A service
- A deployment
- An ingress
Everything is working fine.

The Service is of type LoadBalancer and I can access it with the LB IP address.

**What happened**: However, whatever configuration I tried to access the same service through the ingress lead to an 404 on default backend (!?)

**What you expected to happen**: Accessing the service through the ingress as through the LB IP if the service

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: Here is the code of the ingress (i've remoed the annotations related to the pipelines)

> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   annotations:
>     kubectl.kubernetes.io/last-applied-configuration: |
>       <old-configuration>
>     kubernetes.io/ingress.class: addon-http-application-routing
>     nginx.ingress.kubernetes.io/rewrite-target: /$1
>     nginx.ingress.kubernetes.io/ssl-redirect: "false"
>     nginx.ingress.kubernetes.io/use-regex: "true"
>   creationTimestamp: "2021-05-25T05:53:11Z"
>   generation: 7
>   name: ingress-application
>   namespace: application-namespace
>   resourceVersion: "2493319"
>   selfLink: /apis/extensions/v1beta1/namespaces/irokko-api/ingresses/irokko-api
>   uid: bd029db7-f1ed-4b69-a22b-5ddec2f62fbd
> spec:
>   rules:
>   - host: <the dns name of the cluster>
>     http:
>       paths:
>       - backend:
>           serviceName: api-service
>           servicePort: 80
>         path: /(.*)
> status:
>   loadBalancer:
>     ingress:
>     - ip: <generated Ip address>

Here is details about the service 

> $ k get -n application-namespace svc api-service -o wide
> NAME         TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)        AGE   SELECTOR
> api-service   LoadBalancer   10.0.216.159   <LB IP>   80:30651/TCP   8d    app=api

When accessing the service through the ingress, here is the response

> default backend - 404

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.9
- Size of cluster (how many worker nodes are in the cluster?): 2 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) : a simple nodeJS application

Does anyone have any hint please ?

Thanks

**Comment by justindavies** [comment]
Hi @gkoudjou, can you take a look at the backend pod to see what URL is being requested through the ingress controller once the rewrite rules have been applied?  I've been through this before where what I expect to happen in a rule is not what is being passed to the backend service itself.
