### ISSUE TITLE
Microsoft.ContainerService/managedClusters/stop/action and Microsoft.ContainerService/managedClusters/start/action are not available for RBAC

### ISSUE THREAD

**Issue by suraj2410** [Azure/AKS#2368]
What happened:
We are attempting to create a Service Principal that can only start/stop an AKS Cluster without having to grant excessive permissions.
At present when the Service Principal attempts to call stop on an AKS Cluster the following RBAC error is generated
does not have authorization to perform action `Microsoft.ContainerService/managedClusters/stop/action`

Its also not available https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations#microsoftcontainerservice but when someone tries to do it we get the error that the action is not available

Normally, we would just assign the Action to the Service Principal and it would be fine, however, this action does not exist

What you expected to happen:
We should be able to assign the following actions to the service principal

`Microsoft.ContainerService/managedClusters/stop/action`
`Microsoft.ContainerService/managedClusters/start/action`

How to reproduce it (as minimally and precisely as possible):
Attempt to create a role with permissions to stop/start an AKS cluster

**Comment by miwithro** [comment]
@NickKeller can you look into this?

**Comment by suraj2410** [comment]
@NickKeller any updates?

**Comment by danimal521** [comment]
Just following up on this, @NickKeller any updates?

**Comment by danimal521** [comment]
Hey @suraj2410 it appears that it has been corrected here: https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations#microsoftcontainerservice

Are you still not able to create the SP? thanks!

**Comment by suraj2410** [comment]
@danimal521 yup looks good now! 
thank you
