### ISSUE TITLE
Failed to create containerd container 

### ISSUE THREAD

**Issue by motim6026** [Azure/AKS#2369]
**What happened**:
Failed to create container

**What you expected to happen**:
Container with status running
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The output from command kubectl describe pod backgroundjob-bj-76d8fc587d-9mz7p: 
`Warning  Failed     30m                  kubelet            Error: failed to create containerd container: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount003762815: open /var/lib/containerd/tmpmounts/containerd-mount003762815/etc/passwd: no such file or directory
`

**Environment**:
- Kubernetes version (use `kubectl version`):**1.19.9.**
- Size of cluster (how many worker nodes are in the cluster?): **We have 3 nodes.** 
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): **dotnet core 3.1 web api application.** 
- Others:

**Comment by justindavies** [comment]
Would you be able to paste the pod spec here for us?

**Comment by GeroL** [comment]
Hi i have the same problem but on a local test cluster (not AKS). I tried several different helm3 charts, webservices, etc. All fail to deploy with the error above. I made a very minimalistic web api which just returns a test string on a path. I tried .Net 5 and .Net 6 latest preview. I normally use flux2 to manage apps on the cluster via git. I attached a simple manifest file which show this error.
The cluster has 3 nodes  which run ubuntu microk8s. Installing other services like podinfo works good.
[testservice.txt](https://github.com/Azure/AKS/files/6725870/testservice.txt)

**Comment by csiegris** [comment]
@motim6026 @GeroL I'm experiencing this same problem and error message when local Docker installation is configured to work with _Windows_ containers, images are published to ÀCR via `docker build/tag/push` command chain but AKS is actually running _Linux_ nodes. Changing the Docker workflow on local box to _Linux_ containers resolved the problem for me.

**Comment by GeroL** [comment]
@csiegris Thank you! That was the problem. I had my Azure DevOps build pipeline running on a windows image. Switching to Ubuntu solved the problem. I never would have figured this out on my own.

**Comment by helayoty** [comment]
I have the same problem  building my docker image on Mac

**Comment by motim6026** [comment]
Yes I confirm that was the problem in my case, I built the image on win instead of on Linux
