### ISSUE TITLE
Creating AKS cluster in WestEurope region takes more than an hour

### ISSUE THREAD

**Issue by baluchicken** [Azure/AKS#237]
Earlier creating an AKS cluster took 10-20 minutes, but now it takes 60-80 minutes. Is there any log where I can find out what is happening in the background?
It is reproducible by simply creating a new AKS Cluster on the Azure portal.

**Comment by shahiddev** [comment]
Which VM size were you using, seems like the default used by the CLI isn't available but that should have given you an error.
I'm trying to repro at the moment with a standard_b1ms (node count = 1) to see if its a general problem with the region

**Comment by baluchicken** [comment]
I used Standard D4s v3, and node count = 2. One of my cluster is still in creating state, but the other one just crashed after 70 minutes with this issue https://github.com/Azure/AKS/issues/234. I think maybe there is an error with AKS today, because later I also tried with region East US and I got the same behaviour.

**Comment by shahiddev** [comment]
Yep, same thing, tried eastus and its still creating 30mins later. So appears to be an issue beyond WestEurope.

**Comment by mwieczorek** [comment]
I had also problem in westeurope with k8s clusters made with acs-engine (it takes 3-4 time longer than usually, and sometimes I get errors when attaching PVC to nodes)

https://azure.microsoft.com/en-us/status/ is showing that everything is ok...

**Comment by slack** [comment]
Last week we shipped new provisioning code that watches for all components on a cluster to be up and ready before returning from cluster creation. This includes:

* nodes created and registered as Ready
* tunnel up and ready: for logs, exec, attach
* all kubernetes addons running: dashboard, heapster, etc.

This has significantly extended the perceived provisioning time. The benefit, is that when the cluster create returns, all facets of the cluster should be up and working.

**Comment by alexellis** [comment]
+1 I am also experiencing this issue, it appears to be taking an inordinate amount of time with no status updates / progress.

How long should this take with 2 nodes in `eastus`?

Via Azure shell:

```sh
az aks create --resource-group aks-test --name aks-test --node-count 2 --enable-addons monitoring --generate-ssh-keys
 - Running ..
 - Running ..
 - Running ..
 - Running ..
```

**Comment by prisar** [comment]
takes 20 mins in SouthIndia

**Comment by pixelicous** [comment]
east us 2, totally random destroy/creation times, using terraform.. no where can i read logs and understand whats happening behind the hood, @baluchicken specifically asked " Is there any log where I can find out what is happening in the background?" with no answer to his question..

**Comment by mlushpenko** [comment]
Just experienced this in westeurope - didn't maange to create a single cluster in 4 tests. I kinda gave up after waiting for 1 hour. Will try northerneurope
