### ISSUE TITLE
Bring-your-own Application Gateway (AGIC) identity

### ISSUE THREAD

**Issue by aelij** [Azure/AKS#2374]
**What happened**:
When using the AGIC add-on, AKS creates a user-assigned MI in the generated resource group. This makes it harder to assign the required permissions when deploying using ARM.

**What you expected to happen**:
BYO managed identity for AGIC (specified in the ARM template).

**Comment by phealy** [comment]
This is already in the product and just needs a doc update - @aelij, you can see [an example of what parameters to use to specify your own user-assigned identity in this template.](https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.network/aks-application-gateway-ingress-controller/azuredeploy.json#L1797-L1807)

@akshaysngupta, @mscatyao - can we get the docs updated, please?
