### ISSUE TITLE
FIPS-enabled Nodes

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#2379]
Support for nodepools that use FIPS-enabled OS.
https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#add-a-fips-enabled-node-pool-preview

**Comment by timothymeyers** [comment]
@miwithro I see this has been moved to GA, but the docs linked at the top still say it is In Preview. Are the docs just in need of an update?

And is this GA in Azure Government yet?

**Comment by miwithro** [comment]
@timothymeyers yes.  Just updated the doc.  Will be reflected in a few hours.

**Comment by timothymeyers** [comment]
Confirming: GA in Azure Gov regions too?

**Comment by miwithro** [comment]
Yes.
