### ISSUE TITLE
Vulnerability scan

### ISSUE THREAD

**Issue by gkranga** [Azure/AKS#238]
Hi,
   Who will be responsible for running vulnerability scans on the AKS nodes? Can the customer scan the nodes? and if we find vulnerabilities, will MS fix the issues on the nodes?
Thanks
Ranga

**Comment by slack** [comment]
AKS tracks Ubuntu security updates, and applies these patches nightly. AKS will also do a full replace+patch when running `az aks upgrade`.

If you would like to also reboot nodes for kernel upgrades, you can drop `weaveworks/kured` on  your cluster to monitor and orchestrate node reboots.
