### ISSUE TITLE
PodIdentity not supporting GitOps provisioning of binding identity to namespace

### ISSUE THREAD

**Issue by JonasSame** [Azure/AKS#2388]
Hi,
we have previously used the Pod Identity v.1 which could be instrumented fully with YAML once the add-on was enabled for hte cluster. In version 2 this appraoch is not supported and we can't efficiently provision a pod identity to a specific namespace in the cluster. This breaks our GitOps approach and renders podidentity difficult for us to implement in a good way for our GitOps enabled multi-tenant cluster. We hope that this is considered and remediated before the podidentity goes GA.

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by fdebuire** [comment]
@JonasSame 
see https://github.com/Azure/aad-pod-identity/issues/1017 and https://github.com/Azure/AKS/issues/2221

**Comment by miwithro** [comment]
the az aks pod-identity add command supports the namespace and will give back the selector. You could run that in a script and then use the selector in the pod.
