### ISSUE TITLE
ProvisioningState: Failed

### ISSUE THREAD

**Issue by przemolb** [Azure/AKS#239]
Hello,
just recently I scaled our AKS cluster up to 3 nodes and I am not sure if this is related but my cluser went into ProvisioningState: Failed.
```
az aks show -n kclusterp -g kclusterp -o table
Name       Location    ResourceGroup    KubernetesVersion    ProvisioningState    Fqdn
---------  ----------  ---------------  -------------------  -------------------  ------------------------------------------------------------
kclusterp  westeurope  kclusterp        1.8.7                Failed               kclusterp-kclusterp-somewhere
```
Any hint how I could investigate it ?

**Comment by shahiddev** [comment]
Can you check what vm size you're using, if it's standard_d1_v2 this vm size isn't available in West Europe at the moment so trying to scale the cluster will likely fail. Check issue posted today regarding capacity issues.

**Comment by przemolb** [comment]
It is Standard_E2_v3

**Comment by scriptonist** [comment]
:+1 , My cluster was running fine after scaling up to two nodes, but now this happened, ` "provisioningState": "Failed",` My VM is of type `Standard_D1_v2` running in `eastus`.

**Comment by przemolb** [comment]
So actually if the `ProvisioningState` is `Failed` because of lack of resources (particular VM sizes) does my cluster will stay in this state (weeks, moths, ...) until MS add to Azure additional resources ?

**Comment by przemolb** [comment]
I have just managed to fix the `ProvisioningState` - just scaled (`az aks scale ...`) to the current/existing number of nodes.

**Comment by sauryadas** [comment]
closing this as this is an old issue. if you still see the issue please file a support ticket with azure
