### ISSUE TITLE
Azure Defender Support for VMSS-backed Clusters

### ISSUE THREAD

**Issue by rudolphjacksonm** [Azure/AKS#2392]
**What happened**: This is more a question around why VMSS-backed AKS clusters are not supported for Azure Defender host-level logs. As per the documentation (emphasis mine):

> Host-level threat detection for your Linux AKS nodes is available if you enable Azure Defender for servers and its Log Analytics agent. **However, if your cluster is deployed on a virtual machine scale set, the Log Analytics agent is not currently supported.** [link](https://docs.microsoft.com/en-us/azure/security-center/defender-for-kubernetes-introduction)

**What you expected to happen**: VMSS is the default configuration for AKS clusters. I would expect that since this is the default, we would be able to enable Azure Defender and get host-level threat detection. As stated in the docs, this is not currently supported, which alludes to the possibility of it being supported in future. My questions are as follows:

1. When will this be supported?
2. Seeing as VMSS is the default configuration and host-level threat detection isn't supported, does this mean host-level threat detection is not supported at all within AKS? Or is it only supported if we revert back to using Availability Sets?
3. Is there some other way of enabling this using Azure Defender at present?
4. Finally, the Log Analytics agents--from what I understand--gather application logs. Is there a way to disable this? We don't want our application logs to be ingested by Log Analytics if possible. If this feature were to be supported soon, we would only enable Log Analytics so we could get host-level threat detection. We wouldn't want our logs (which may contain sensitive data) being ingested into Log Analytics.

**How to reproduce it (as minimally and precisely as possible)**: N/A

**Anything else we need to know?**: N/A

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by miwithro** [comment]
Use the new Microsoft Defender for Containers daemonset, with Host Level protection and it no longer requires Log Analytics.
