### ISSUE TITLE
liveness-probe logs output to stderr on CSI storage drivers

### ISSUE THREAD

**Issue by alexangas** [Azure/AKS#2396]
**What happened**:
Logs contain many repeated lines output to **_stderr_** of:

```
connection.go:153] Connecting to unix:///csi/csi.sock
```

Due to the output of stderr, our logging solution is filling up with these messages.

**What you expected to happen**:
This appears to be an information level message. If true, the output is expected to go to stdout, some lower logging level, or not at all.

**How to reproduce it (as minimally and precisely as possible)**:
1. Provision a new AKS 1.21 cluster with CSI storage enabled, as [documented here](https://docs.microsoft.com/en-us/azure/aks/csi-storage-drivers).
2. (May be optional:) Deploy a pod that makes use of the Azure CSI storage drivers.
3. Review the logs output by container "liveness-probe" in a pod "csi-azuredisk-node" or "csi-azurefile-node" in the "kube-system" namespace. Observe the above log message output to stderr.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"ca992926ba9f76abd853859a64b5b04a1b562362", GitTreeState:"clean", BuildDate:"2021-05-19T22:29:12Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}`
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Solr
- Others: Using a custom storage class for azuredisk with provisioner `disk.csi.azure.com` (but not for azurefile).

**Comment by andyzhangx** [comment]
thanks for reporting, we will upgrade to csi driver v1.4 which has fixed this issue:
https://github.com/kubernetes-csi/livenessprobe/blame/v2.3.0/vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go

in original v2.2.0 liveness probe container, that log level is 2, and in v2.3.0, it would be changed to 5
The rollout of csi driver v1.4 on AKS would be in July, stay tuned.
