### ISSUE TITLE
kubernetes secret created through csi driver is not identified by azure file share

### ISSUE THREAD

**Issue by aadeepaj** [Azure/AKS#2398]
**What happened**:
- Created a kubernetes secret using values fetched from keyvault in default namespace. 
          secretObjects:                            
              - secretName: fileshare-secret
                type: Opaque
                data:
                  - objectName: fileshare-access-key                
                    key: azurestorageaccountkey
                  - objectName: fileshare-access-name1
                    key: azurestorageaccountname
- Deployed a pod referring to the secret  and connecting to azure file share
         volumes:
          - name: secrets-store-inline
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: kv-secret-provider
          - name: azure-fileshare
            azureFile:
              secretName: fileshare-secret
              shareName: angaksfileshare
              readOnly: false
- The azure file share mounting errored out 'Couldn't get secret default/fileshare-secret'

**What you expected to happen**:

- Expected the azure share mount to happen

**How to reproduce it (as minimally and precisely as possible)**:
Have provided the snippets above.

**Anything else we need to know?**:
- Able to see that the secret is generated and also able to assign it to environment variables.
- If the secret is created manually, the azure file share connection succeeds.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.7
- Size of cluster (how many worker nodes are in the cluster?) : 1

**Comment by andyzhangx** [comment]
so is there a secret `default/fileshare-secret` created by secret store driver?

**Comment by miwithro** [comment]
@aadeepaj are you able to verify if there is a secret present default/fileshare-secret?  Also have you ran through the troubleshooting steps here? https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/

**Comment by aadeepaj** [comment]
Thank you for checking on this, my issue was I was trying to connect with wrong credentials. The functionality works fine!
