### ISSUE TITLE
Error creating cluster

### ISSUE THREAD

**Issue by ekarlso** [Azure/AKS#24]
Hi, I'm trying to create a cluster and getting the following error at the moment.

kubectl get pods --namespace=kube-system 
NAME                                    READY     STATUS             RESTARTS   AGE
heapster-553147743-zpkqz                2/2       Running            0          58s
kube-dns-v20-1654923623-35mc5           2/3       Running            0          57s
kube-dns-v20-1654923623-n0kmv           2/3       Running            0          57s
kube-proxy-9tkqg                        1/1       Running            0          57s
kube-proxy-x6x56                        1/1       Running            0          57s
kube-svc-redirect-90dkw                 0/1       Error              3          57s
kube-svc-redirect-lt301                 0/1       CrashLoopBackOff   2          57s
kubernetes-dashboard-3427906134-cvnph   1/1       Running            0          57s
tunnelfront-c7rrn                       0/1       Error              2          57s
tunnelfront-rk54n                       0/1       CrashLoopBackOff   1          57s

Error for the kube-svc
Error from server: Get https://aks-agentpool1-39835177-0:10250/containerLogs/kube-system/kube-svc-redirect-90dkw/redirector: dial tcp 10.240.0.4:10250: getsockopt: connection refused

Also when trying to install istio

NAME                             READY     STATUS    RESTARTS   AGE
istio-ca-367485603-20049         1/1       Running   0          1m
istio-egress-3571786535-1bj8w    1/1       Running   0          1m
istio-ingress-2270755287-j5t5n   1/1       Running   0          1m
istio-mixer-1505455116-mllwx     2/2       Running   0          1m
istio-pilot-2278433625-fb4k3     0/1       Error     1          1m

**Comment by ekarlso** [comment]
This is in ukwest

**Comment by bacongobbler** [comment]
I'm going to close this as a duplicate ticket as #2. That way we can continue to track discussion all in one ticket related to capacity issues. Thank you for the report!
