### ISSUE TITLE
West Europe and East US on Tuesday, March 13, 2018

### ISSUE THREAD

**Issue by slack** [Azure/AKS#240]
We are currently hitting the ceiling for our in-region AKS clusters in West Europe and East US. We are working to make more room and will update this issue once we have restored service.

Regions with room:
* Canada Central
* Canada East
* Central US

As of Wednesday, March 14th around noon, we added more room for AKS clusters in East US and West Europe.

**Comment by mooperd** [comment]
+1

**Comment by jmalobicky** [comment]
Using `centralus` does not work. I keep getting the following error

```
"statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"ControlPlaneProvisioningInternalError\",\"message\":\"Internal server error\"}]}}"
```

**Comment by ivoleitao** [comment]
I'm also having this problem in west europe. I'm unable to provision a AKS cluster and it not related with quota issues

**Comment by angrox** [comment]
I am having the same problem: AKS Cluster in west-europe is in state "Creating" since 1 day (support is already informed, told me to deploy in another region :-D)

**Comment by atoolchain** [comment]
Also problems in "canadaeast", after given up on "westeurope"

"Deployment failed. Correlation ID: 8979c400-b864-470a-a91e-0c80132a4ea6. Operation failed with status: 200. Details: Resource state Failed"

**Comment by rzal** [comment]
I had a problem that I couldn't delete failed AKS cluster for days, finally I managed it via the Cloud Shell in Azure portal => Powershell 

Very handy to force delete stuck stuff.

`Remove-AzureRmResourceGroup -Name "abc" -force
`

**Comment by johnkeithwood** [comment]
Same for me in East US and Central US regions... I can't get a cluster to provision to success, and the failed ones won't delete.

**Comment by previ** [comment]
same.

**Comment by glav** [comment]
So I recently tried twice to create an AKS instance and it failed both times with an Internal error of "ControlPlaneProvisioningInternalError".
Contacted support, they pointed me to this thread and asked that I try again, which I just did, and it worked. It was all in EastUS.
So, don't know if anything has been changed or I got in via pure luck.

**Comment by previ** [comment]
This morning I tried to create a cluster on westeurope but got:
"The VM size of Agent is not allowed in your subscription in location 'westeurope'. Agent VM size 'Standard_D2_v2' is available in locations: australiaeast,australiasoutheast,canadacentral,canadaeast,centralus,centraluseuap,eastus,eastus2euap,japaneast,japanwest,koreasouth,southcentralus,southeastasia,southindia,uksouth,westindia,westus,westus2. (Code: BadRequest)"

**Comment by Jollym** [comment]
FYI

i had luck with "Standard_D2s_v3" this morning. (NOTE: Naming convention changed between "D2s_v3" and DS2_v2 (the 's' moved)


But I had a new type of error yesterday.

az aks create --resource-group $CLUSTERNAME --name $CLUSTERNAME --node-count 5 --node-vm-size Standard_D2s_v3 --generate-ssh-keys

Deployment failed. Correlation ID: fa6a38ba-44ff-411a-a0d1-dfeeabf20348. The access token expiry UTC time '3/14/2018 5:45:50 PM' is earlier than current UTC time '3/14/2018 5:46:14 PM'.

So you might want to increase the timeout on that token. Also no sure if that deployment ended up getting half baked or not.

**Comment by slack** [comment]
Updated the main issue text. AKS in East US and West Europe is no longer returning "Capacity over-constrained errors" as of Wednesday afternoon (Pacific).

Issues with specific VM SKUs are likely related to per-subscription core/compute quotas.

I'm going to go ahead and close this issue out for the specific AKS capacity event.

**Comment by ronaldmiranda** [comment]
This is happening again, im using westus2 today 26/09/2019
