### ISSUE TITLE
Scale nodepool to zero is (most likely) blocked by calico-typha pod

### ISSUE THREAD

**Issue by ErikLundJensen** [Azure/AKS#2401]
**What happened**:

Given I have provisioned an AKS cluster with CNI Calico enabled  
and added a nodepool with mode=User   
and chosen Autoscaler with min=0 nodes.
Then node count can't scale to zero.

**What you expected to happen**:

I expect the nodes to be removed from the pool when no non-system related pods are running.

**How to reproduce it**:

Create an AKS cluster (1.20) with CNI Calico enabled.  
Add nodepool with mode=User and enable autoscale min=0 max=2  
Add a deployment with a nodeSelector that matches the new nodepool.  
Ensure that the autoscaler increases the count of nodes to 1.  
Delete the deployment and thereby the pod running on the new node.  
Notice, that the autoscaler never scales to zero.

**Anything else we need to know?**:

Looking at the pods running on the node I do notice that the pod "calico-typha-575f657968-lcmqb" does not
have the annotation ```cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'```
All pods except calico-typha-575f657968-lcmqb are daemon pods and should not block scale down:

```
Non-terminated Pods:          (4 in total)
  Namespace                   Name                             CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                             ------------  ----------  ---------------  -------------  ---
  calico-system               calico-node-l2sjb                0 (0%)        0 (0%)      0 (0%)           0 (0%)         <invalid>
  calico-system               calico-typha-575f657968-lcmqb    0 (0%)        0 (0%)      0 (0%)           0 (0%)         <invalid>
  kube-system                 azure-ip-masq-agent-tbz22        100m (5%)     500m (26%)  50Mi (0%)        250Mi (4%)     <invalid>
  kube-system                 kube-proxy-54qmr                 100m (5%)     0 (0%)      0 (0%)           0 (0%)         <invalid>
```

The AKS engine does set the safe-to-evict in the template: https://raw.githubusercontent.com/Azure/aks-engine/1.20GA/pkg/engine/templates_generated.go
however, the running pod does not have that annotation.

It looks like the Tigera Opeartor removes the annotations:
https://github.com/tigera/operator/blob/8a23510192ce85f8641643a163e5af73d8935f25/pkg/controller/migration/convert/core.go#L247

I expect the Azure AKS managed Tigera Operator to be configured to support scale to 0 nodes.

**Environment**:
- Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"6b3f9b283463c1d5a2455df301182805e65c7145", GitTreeState:"clean", BuildDate:"2021-05-19T22:28:47Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
2 node in default nodepool
1 node in added nodepool

- General description of workloads in the cluster
Sandbox cluster running Azure CNI Calico

**Comment by ErikLundJensen** [comment]
Note, that autoscaling down from 2 or more nodes to 1 works fine. Maybe the error is more related to scale to zero than to "safe-to-envict".

**Comment by justindavies** [comment]
@qpetraroia let's have a chat about this

**Comment by gregjhogan** [comment]
does anyone have a workaround? I tried to manually scale to zero with `az aks scale` when the autoscaler is enabled but I get the error `Cannot scale cluster autoscaler enabled node pool.`

**Comment by gregjhogan** [comment]
> does anyone have a workaround? I tried to manually scale to zero with `az aks scale` when the autoscaler is enabled but I get the error `Cannot scale cluster autoscaler enabled node pool.`

seems like `kubectl drain <node-name> --force=true` worked
