### ISSUE TITLE
Is there a way to really control the egress traffic from the aks

### ISSUE THREAD

**Issue by israel-gonzalezmedina** [Azure/AKS#2402]
**What happened**:
I need to deploy two pods in a AKS with curl request to a server that returns the source IP like:
apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  labels:
    app: busybox-curl
spec:
  containers:
    - name: test-container
      image: zhaoxy8/busyboxplus
      command: [ "/bin/sh", "-c", "for counter in $(seq 1 255000); do curl -s checkip.dyndns.org; echo  ; sleep 10 ; done" ]
  restartPolicy: Always

I need to find a architecture and configuration that make it possible that each container registers a different IP in the response.
 
**What you expected to happen**:
For each container, I need to receive a different IP in the response from the server checkip.dyndns.org. Also, I need to control that IPs because it will be used in a whitelist
**How to reproduce it (as minimally and precisely as possible)**:
For that, this is what I've tested

-I test to create an AKS with a basic load balancer and add two static IPs connecting them to different services, each one linked to the static IP like 
https://docs.microsoft.com/en-us/azure/aks/egress  . 
One container was connected to one service.  That didn't work. the IP address registered by the checkip.dyndns.org is one of them. The documentation says that it will be randomly assigned but I need to actually control the egress traffic.

- I test to create an AKS with a standard load balancer behind a firewall like the documentation
https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic
I created a new IP and add it to the firewall. then I create two services and create a new nat rule in the firewall connecting the services with the new IP, same as the documentation. Also, create a SNAT rule on the route table connecting the new IP to the internet. That didn't work either 

**Anything else we need to know?**:
I have no real solution or demanding on this. I just need a way to do that. Its possible to user a different architecture / configuration or kubernet architecture..
**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by israel-gonzalezmedina** [comment]
I found that adding node pools with the option --enable-node-public-ip creates an outgoing IP for every pod deployed on any of its nodes. I can control where the pod is been deployed using labels and node selector.. However, this can be a kinda waste of resource if I need more IPs than processing.. Imagine I need 10 Ip for a simple server.. I will need 10 VM, each one in a different pool to cover the requirements. 
The problem in here lays in the need to controls what pod sends by where IP. If no control were needed, I can go with a nat gateway that redirect the outgoing traffic via 16 IPs. But this is not the case.

**Comment by danimal521** [comment]
@israel-gonzalezmedina can you please provide more topology info like: are you using CNI or Kubenet, any UDRs? Thanks!

**Comment by israel-gonzalezmedina** [comment]
thanks for the response @danimal521 
I am using now azure CNI, but I have no requirements for one or another

**Comment by robbiezhang** [comment]
@israel-gonzalezmedina , did you try to use the Standard Load Balancer? You can configure your cluster with your own public IP or prefixes as well.
https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#configure-the-public-standard-load-balancer

**Comment by miwithro** [comment]
We are about to officially support NAT Gateway which could be leveraged here as well.
