### ISSUE TITLE
Continuous TLS Handshake error - AKS loadbalancer

### ISSUE THREAD

**Issue by kalyanteja19** [Azure/AKS#2405]
**What happened**:
We have exposed grafana service as loadbalancer using below YAML file. But we could see lot of TLS handshake errors on grafana pod for every 5 secs. It seems these are health check logs.

apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: grafana-service
  namespace: xxxx-grafana
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    nodePort: 31114
    port: 443
    protocol: TCP
    targetPort: 42300
  selector:
    app: grafana
  type: LoadBalancer

We are running grafana with container port 42300

Error logs:
2021/06/25 05:04:05 http: TLS handshake error from xxxx.xxx.xxx.162:13983: EOF
2021/06/25 05:04:05 http: TLS handshake error from xxxx.xxx.xxx.132:28305: EOF
2021/06/25 05:04:05 http: TLS handshake error from xxx.xxx.xxx.0:53997: EOF
2021/06/25 05:04:05 http: TLS handshake error from xxxx.xxx.xxx.36:55522: EOF
2021/06/25 05:04:10 http: TLS handshake error from xxxx.xxx.xxx.5:62195: EOF
2021/06/25 05:04:11 http: TLS handshake error from xxxx.xxx.xxx.225:12161: EOF
2021/06/25 05:04:11 http: TLS handshake error from xxx.xxx.xxx.0:47008: EOF
2021/06/25 05:04:16 http: TLS handshake error from xxxx.xxx.xxx.5:55196: EOF
2021/06/25 05:04:17 http: TLS handshake error from xxxx.xxx.xxx.132:1236: EOF

**What you expected to happen**:
Service and functionality is fine, but we could see unwanted logs with TLS handshake errors. We want the errors to be removed.

**How to reproduce it (as minimally and precisely as possible)**:

Run the grafana application with https protocol and on different port as 42300. Then expose the grafana service as loadbalancer with the above YAML file.

**Anything else we need to know?**:
No, all details provided.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.17
- Size of cluster (how many worker nodes are in the cluster?): 8
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) : Java
- Others: No

**Comment by kalyanteja19** [comment]
Hi Team, Any update on this request? Please.

**Comment by miwithro** [comment]
The below seems to be related.

https://github.com/grafana/grafana/issues/17758

**Comment by kalyanteja19** [comment]
Here, TLS handshake errors are from AKS Node IPs. These are Health checks from AKS nodes. Hence, please suggest on this issue

**Comment by kalyanteja19** [comment]
Hi team,

any update on this request?

**Comment by kalyanteja19** [comment]
Hi team,

any update on this request?

**Comment by kalyanteja19** [comment]
Hi team,

any update on this request?

**Comment by kalyanteja19** [comment]
Hi team,

Updated please

**Comment by kalyanteja19** [comment]
Hi team,

any update on this request?

**Comment by kalyanteja19** [comment]
Hi team,

any update on this request?

**Comment by kalyanteja19** [comment]
Hi team,

any update on this request?
