### ISSUE TITLE
AKS Auto Repair Does Not Kick In

### ISSUE THREAD

**Issue by chirangaalwis** [Azure/AKS#2406]
**What happened**:
When conducting Gremlin based chaos testing against a sample Azure Kubernetes Service (AKS) cluster, we executed a scenario in which [one of nodes of the Kubernetes cluster user Pod node pool was shutdown](https://app.gremlin.com/scenarios/recommended/kubernetes-correctness-shutdown-a-node/hosts) to observe the behaviour.

<img width="1084" alt="Screenshot 2021-06-25 at 22 51 28" src="https://user-images.githubusercontent.com/9444555/123464048-f053b700-d609-11eb-99b9-e12a2bb88e5b.png">

<img width="931" alt="Screenshot 2021-06-25 at 22 52 05" src="https://user-images.githubusercontent.com/9444555/123464068-f9dd1f00-d609-11eb-9678-613c815e9c16.png">

<img width="1413" alt="Screenshot 2021-06-25 at 22 50 52" src="https://user-images.githubusercontent.com/9444555/123464096-05304a80-d60a-11eb-8e43-6d548a02cba9.png">

We allowed the state to remain for more than 10 mins but, no auto repair of the underlying Azure VM kicked in as suggested in the official [documentation](https://docs.microsoft.com/en-us/azure/aks/node-auto-repair#how-automatic-repair-works).

<img width="535" alt="Screenshot 2021-06-25 at 22 50 05" src="https://user-images.githubusercontent.com/9444555/123464517-8ab3fa80-d60a-11eb-83a8-11012bfd98f0.png">

<img width="1420" alt="Screenshot 2021-06-25 at 22 49 45" src="https://user-images.githubusercontent.com/9444555/123464527-8ee01800-d60a-11eb-9d79-3bf271a3cad3.png">

<img width="1437" alt="Screenshot 2021-06-25 at 22 49 15" src="https://user-images.githubusercontent.com/9444555/123464540-930c3580-d60a-11eb-83aa-d25bb4c63b64.png">

**What you expected to happen**:
AKS documentation suggests that [auto repair of unhealthy Kubernetes Nodes kick in after 10 mins](https://docs.microsoft.com/en-us/azure/aks/node-auto-repair#how-automatic-repair-works).

**How to reproduce it (as minimally and precisely as possible)**:
[Use Gremlin Chaos based Kubernetes Node shut down against a user Pod node](https://app.gremlin.com/scenarios/recommended/kubernetes-correctness-shutdown-a-node/hosts).

**Note**:
Conducted based on [this](https://tammybutow.medium.com/site-reliability-engineering-for-kubernetes-b52877c70fb7) informative blog.

**Environment**:
- Kubernetes version (use `kubectl version`): Server version is `v1.18.19`
- Size of cluster (how many worker nodes are in the cluster?): 2 at the given time
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): JVM based deployments, [Azure CSI Driver for Key Vault](https://github.com/Azure/secrets-store-csi-driver-provider-azure)

**Comment by justindavies** [comment]
Hi there @chirangaalwis how was the node shut down for this experience to? Was it a VM power operation directly, or does gremlin manage to mess with the node to make it seem as a node failure?

**Comment by chirangaalwis** [comment]
@justindavies Gremlin does a [graceful shutdown of the VM node](https://www.gremlin.com/docs/infrastructure-layer/attacks/shutdown/#linux).

**Comment by danimal521** [comment]
@gambtho this is still an issue in v1.20.7 (just confirmed), can you take a look / provide information on this.

**Comment by paulgmiller** [comment]
@juan-lee  @marwanad  can correct me but if the vm is intentionaly power down we don;t mess with it. There's even an upcomign autoscaler mode that will dellocate vms rather than delete them. Now if your vm is not ready but powered on we will try some remediations. So maybe we need to clairfiy the docs.

**Comment by chirangaalwis** [comment]
@paulgmiller yes better to mention it in documentation.

Does AKS determine how the particular VM was shut down (whether it was gracefully shut down or not) before taking any remediation action? How does it do this?

Appreciate if details of this process are elaborated.

**Comment by chirangaalwis** [comment]
Not stale, waiting for feedback.

**Comment by chirangaalwis** [comment]
Not stale, waiting for feedback.

**Comment by chirangaalwis** [comment]
Not stale, waiting for feedback.

**Comment by chirangaalwis** [comment]
Pending reply for https://github.com/Azure/AKS/issues/2406#issuecomment-896499685.
