### ISSUE TITLE
How to perform AKS upgrade for a private cluster from 1.18.14 to 1.19.11 which is having istio as a service mesh

### ISSUE THREAD

**Issue by vowne** [Azure/AKS#2407]
We are planning to upgrade our Private production cluster to 1.19.11 version and  before the upgrade, would like to clarify few items for safer side as this is for producton enviroment

**Current Setup Details.**

-  Its a private cluster and AZURE CNI enabled
-  We are using Istio 1.7.3 as service mesh

**Planned Upgradation process**

- As Istio version 1.7.3 is not supported for AKS 1.19.11, we need to upgrade Istio as well.
- looking for minimal down time and safer proces.

**Items to clarify**

- Since we need to do istio upgrade also, which need to be perform first, Istio or AKS upgrade?

- What is the best safest way to upgrade AKS cluster which is using Azure CNI, and is there any helping document regards to this?

- What are the extra considerations need to be taken for Istio upograde in AKS cluster. Couldnt find any relevant documents related to this anywhere.

**Comment by miwithro** [comment]
@vowne Please ensure you read through our AKS Upgrade document.

https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster

Regarding the timing of Istio I recommend you upgrade Istio first.  Very functionality, and then perform the AKS upgrade.  Just to be clear what AKS version are you on currently?

**Comment by miwithro** [comment]
@vowne upgrade Istio then AKS.
