### ISSUE TITLE
calico-node containers show as unready (0/1) - K8's version 1.20.7

### ISSUE THREAD

**Issue by bkarakasdevops** [Azure/AKS#2409]
**What happened**: _After upgrading Kubernetes cluster from 1.19.9 to 1.20.7, one of the calico-node container(daemonset) in calico-system namespace shows as unready(0/1). Upon checking the logs of the pod; "readiness probe failed" with no additional information. The issue is discussed with Tigera Engineers and they have referenced [this github issue](https://github.com/tigera/operator/issues/1324) which they resolved by this [merge](https://github.com/tigera/operator/pull/1325)._

_Currently, "tigera-operator-xxxxxxxxxx-xxxxx" pod in tigera-operator namespace is using "mcr.microsoft.com/oss/tigera/operator:v1.17.1" image version and we believe that if the image version updated to v1.17.4 which would increase "timeoutSeconds" from 1 sec to 5 sec, so then the readinessProbe failure hopefully resolved._

**What you expected to happen**: _All containers to be in ready state._

**How to reproduce it (as minimally and precisely as possible)**: _We were able to reproduce the issue twice by creating a new AKS Cluster at 1.19.9 Then upgrading it to 1.20.7 During the update the calico-node readiness probe fails._

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
**1.20.7**
- Size of cluster (how many worker nodes are in the cluster?)
**There are 3 worker nodes in the cluster.**
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
**HTTP microservices**
- Others: _Node pools version is also 1.20.7_

**Comment by nununoisy** [comment]
Have you tried the solution in https://github.com/projectcalico/calico/issues/4525?

**Comment by bkarakasdevops** [comment]
> Have you tried the solution in [projectcalico/calico#4525](https://github.com/projectcalico/calico/issues/4525)?

Thank you for reply.
That is different issue than we are having currently.

**Comment by KannappanSomu** [comment]
mitigation mentioned here helped me to resolve aks calico nodes

https://github.com/projectcalico/calico/issues/4611

**Comment by bkarakasdevops** [comment]
> mitigation mentioned here helped me to resolve aks calico nodes
> 
> [projectcalico/calico#4611](https://github.com/projectcalico/calico/issues/4611)

Thank you for the reply.

I have seen projectcalico/calico#4611 issue before I post my issue here. I also double checked the mitigation steps again, but  looks like it is not the same case. ipv4 addresses are matching and I don't see the error in the logs for the failed pod as you posted there.

**Comment by nununoisy** [comment]
Out of curiosity, do you see an image pull error for `calico/pod2daemon-flexvol:v3.19.0` in the logs?

**Comment by bkarakasdevops** [comment]
> Out of curiosity, do you see an image pull error for `calico/pod2daemon-flexvol:v3.19.0` in the logs?

Yes, I see it in failed calico-node pod as;

`Failed to pull image "mcr.microsoft.comoss/calico/pod2daemon-flexvol:v3.19.0": rpc error: code = Unknown desc = failed to pull and unpack image "mcr.microsoft.comoss/calico/pod2daemon-flexvol:v3.19.0": failed to resolve reference "mcr.microsoft.comoss/calico/pod2daemon-flexvol:v3.19.0": failed to do request: Head https://mcr.microsoft.comoss/v2/calico/pod2daemon-flexvol/manifests/v3.19.0: dial tcp: lookup mcr.microsoft.comoss on <ipaddress>:<port>: no such host`

**Comment by palma21** [comment]
Sorry for the delay, this should now be fixed everywhere with the latest calico components. Let us know if you still have issues.
