### ISSUE TITLE
Unable to delete AKS cluster which is in a creating state

### ISSUE THREAD

**Issue by pmichiels** [Azure/AKS#241]
How do I now delete the cluster that is in a state of : az aks list --> "provisioningState": "Creating".  It has been in this state for almost 24 hours.  When I try to delete it I get: "Operation failed with status: 'Conflict'. Details:"

**Comment by atoolchain** [comment]
same problem, stuck in creating.

**Comment by pmichiels** [comment]
Tried the following PowerShell command:
`remove-AzurermResourceGroup -name myResourceGroup -pre`
This operation failed with status 'Conflict'.

**Comment by rzal** [comment]
`Remove-AzureRmResourceGroup -Name "abc" -force`

Try this one.

**Comment by agolomoodysaada** [comment]
After many hours (the next day), the state of my cluster was marked as failed, and then I was able to remove it. It shouldn't take that long to detect failure.

**Comment by pmichiels** [comment]
@rzal - I got the same error message with `-force`. 

Not sure how long we should wait for it to fail? It has been 2 days so far.

**Comment by mohanramanujam** [comment]
could not delete the hanging AKS cluster from bash then tried using this command referenced above but still not luck. See command and error

Remove-AzureRmResourceGroup -Name "myAKSResourceGroup" -force
Remove-AzureRmResourceGroup : Long running operation failed with status 'Conflict'.
At line:1 char:1
+ Remove-AzureRmResourceGroup -Name "myAKSResourceGroup" -force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Remove-AzureRmResourceGroup], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.RemoveAzureResourceGroupCmdlet

**Comment by pmichiels** [comment]
I have not seen an answer to this yet. The cluster has been in creating state for 6 days now!

**Comment by odauby** [comment]
Had the same issue, solved with azure-cli.
AKS cluster in 'Creating' state for days (weeks actually), not deletable from the Portal:
```
bash-4.3# az aks list
Name              Location    ResourceGroup     KubernetesVersion    ProvisioningState
----------------  ----------  ----------------  -------------------  -------------------
sl-m3-kubernetes  westeurope  sl-m3-kubernetes  1.8.7                Creating
```
Deletion command (looks like verbosity is quite minimal) :
```
bash-4.3# az aks delete --resource-group sl-m3-kubernetes --name sl-m3-kubernetes --verbose
Are you sure you want to perform this operation? (y/n): y

```
Looks like AKS cluster is got for good this time:
```
bash-4.3# az aks list

bash-4.3# 

```

**Comment by sauryadas** [comment]
if you are still seeing issues please file a support ticket. Old issue i am going to close this.
