### ISSUE TITLE
When will AKS support IPv4/IPv6 dual-stack

### ISSUE THREAD

**Issue by smithago** [Azure/AKS#2410]
Looks like k8s support is in beta https://kubernetes.io/docs/concepts/services-networking/dual-stack/

We are internal customer and to support private link on our app every team needs to go build a proxy to do this.

I see this feature is in backlog. Can we get a rough timeline on when this will be supported?

**Comment by aanandr** [comment]
This is in our roadmap but i dont have clear timelines for its availability yet. It will most probably come only next semester.

**Comment by palma21** [comment]
Dup for #460
