### ISSUE TITLE
Unable to delete cluster after using pod dedicated subnet

### ISSUE THREAD

**Issue by jabbera** [Azure/AKS#2412]
Hi! I attempted to try out the PodSubnetPreview. After running into some issues I tried to delete my cluster and rollback to my previous configuration. The managed resource group was deleted as usual but the cluster continues to exist with the error: "This container service is in a failed state." It's locking my subnet dedicated to pods so I can't reclaim my peered address space to roll back because of the delegation. Support has been unable to "re-sync" my cluster as it keeps failing. The result of this is I cannot deploy to production because I cannot get my lower environment running again! While I get your disclaimer to not run previews in production, not being able to rebuild my dev environment without struggling with support for over a week is really turning me off to trying previews in the future. 

Sorry to spam a support ticket here but I don't know what else to do. I'm late on my project and can do nothing until I can get my vnet reclaimed! I'm desperate. Please help! Ticket: 2106220040006618

**Comment by phealy** [comment]
Ticket was closed via support; automation was added in the meantime to both make issues of this type less frequent and faster for support to resolve.
