### ISSUE TITLE
When will AKS support A100s for the nodepools?

### ISSUE THREAD

**Issue by akaanirban** [Azure/AKS#2413]
The general availability of A100 has been announced recently with the `Standard_ND96asr_v4` vm size. 

I am also able to use these as VMs in `southcentralus` and `westus` . 

However, are there any recent plans to bring them to AKS? If so , then can we get a rough idea about the timeline?

On trying to create a nodepool with Standard_ND96asr_v4 VMs I get the following error: 
```
>>> az aks nodepool add --resource-group $RESOURCE_GROUP --cluster-name $AKS_CLUSTER_NAME --name test --node-vm-size Standard_ND96asr_v4 --node-count 1 

Operation failed with status: 'Bad Request'. Details: The VM SKUs chosen for agentpool(s) `AgentPoolProfile:test` are restricted by AKS. This is typically due to small CPU/Memory. Please see https://aka.ms/aks/restricted-skus for more details
```

**Comment by justindavies** [comment]
Hi there, I wish I could give you a concrete date.  This is definitely in our backlog and we are working to get the A100's onboarded.
