### ISSUE TITLE
Preserve source IP when exposing TCP or UDP services behind the ingress controller

### ISSUE THREAD

**Issue by Bananenbieger1234** [Azure/AKS#2415]
Hi!
There is this resolved issue (https://github.com/Azure/AKS/issues/607) which did not answer the question of how to preserve source IP when exposing TCP or UDP services behind an ingress controller in Azure AKS.
Does anybody know how to solve this issue with NGINX Ingress Controller?

Thanks for your help!

I have the following setup:
- AKS 1.19.11
- NGINX Ingress via Helm (v.0.45.0)

Here is the question from @cristiklein which was not answered - so I decided to open a new issue for that.

>> Hi @JunSun17 , this doesn't appear to be working for TCP forwarding. Is this possible? Does this need a separate ticket?
>> 
>> https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/
>
>@JamesBewley Did you find a way to preserve the source IP when exposing TCP or UDP services behind the ingress controller?
> _Originally posted by @cristiklein in https://github.com/Azure/AKS/issues/607#issuecomment-535486559_

**Comment by JamesBewley** [comment]
The source address gets set to that of the ingress controller and that is all my applications ever see.

The easy fix for http traffic was to set the x-forwarded header which the application will then be able to parse to determine the source.

Obviously a little more complicated for TCP traffic and I guess would need something like DNAT to preserve the source IP.  Not sure how feasible this is in a kubernetes environment?

**Comment by Bananenbieger1234** [comment]
Thanks for your reply @JamesBewley.

I want to restrict database access based on client ip. The only way I see right now is to bypass NGINX for that. 

@cristiklein gave me a hint to expose the TCP services directly via service of type loadbalancer which means I need another public IP for that.

If this is the only way to do it - I am okay with that and I'll close the issue. I just want to know if it is possible via NGINX Ingress Controller or not.

**Comment by Bananenbieger1234** [comment]
We fixed this by setting the PROXY param when [exposing TCP services via NGINX](https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/).

`<namespace/service name>:<service port>::PROXY`

We additionally set `proxy-real-ip-cidr` to the address range where our nginx pod is running.

In our case we also needed to enable proxy-protocol-networks for our backend tcp service ([mariadb](https://mariadb.com/kb/en/proxy-protocol-support/)) to make this work.
