### ISSUE TITLE
Azure Kubernetes Service RBAC Reader role contains a write action

### ISSUE THREAD

**Issue by aelij** [Azure/AKS#2416]
**What happened**:
The built-in role "Azure Kubernetes Service RBAC Reader" contains the write action "Microsoft.Resources/deployments/write".

**What you expected to happen**:
Reader roles should not have write actions.

**Comment by justindavies** [comment]
@miwithro  for when you are back, any ideas why this is?

**Comment by palma21** [comment]
@Anumita, @shashankbarsin

**Comment by aelij** [comment]
Additionally, shouldn't this role also have the `Microsoft.ContainerService/managedClusters/listClusterUserCredential/action` action? Otherwise a user would not able to run `az aks get-credentials`.

**Comment by miwithro** [comment]
@thomas1206 @Anumita @Shashank3036 can you address?

**Comment by Anumita** [comment]
Hey @aelij , The action "Microsoft.Resources/deployments/write" does not affect the k8s resources. Only data actions affect the k8s resources via Azure RBAC i.e the permissions mentioned in the dataactions field. So it will not affect the Azure RBAC you set for the k8s resources in the cluster. The action "Microsoft.Resources/deployments/write" is usually added for built-in roles.

**Comment by aelij** [comment]
@Anumita I understand it's usually added for built-in roles but if you look at other "reader" roles you'll see no write actions. IMO it should be removed.

Also please refer to my second question:

> shouldn't this role also have the Microsoft.ContainerService/managedClusters/listClusterUserCredential/action action? Otherwise a user would not able to run az aks get-credentials.

**Comment by Anumita** [comment]
@aelij , I agree. I will follow up that internally on removing that action. Referring to the second question, this is by design. All the Azure Kubernetes RBAC Reader/Writer/Admin roles (e.g  "Azure Kubernetes Service RBAC Reader") are mainly used for talking to api-server only (aka data action). The control plane roles are separate.

**Comment by Rob19999** [comment]
I agree. Our security officer is making a issues of this now because there are write permission on a reader rol. With this story I can explain it but it should be removed or explained in the Official Microsoft documentation. Thanks for helping resolve this issue in advance.

**Comment by miwithro** [comment]
@Rob19999 we are working to see what "Write" permissions we can remove without breaking things.  Will follow up on this thread once we have a plan.

**Comment by fschmied** [comment]
@miwithro @Anumita Any news about this? We've also noticed this issue and are reflecting whether to create a custom role that excludes `Microsoft.Resources/deployments/write`. What might break if `Microsoft.Resources/deployments/write` were removed?

**Comment by dgindin** [comment]
**@miwithro @Anumita** Pinging this thread to see if there has been any updates/progress on this issue. While it is possible to create a custom role that excludes the `Microsoft.Resources/Deployments/write` permission, adding a management group its AssignableScopes is currently only supported in preview:

https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles

**Comment by pralaydesai1** [comment]
+1 for have it fix in built-in role given Azure recommends to use built-in IAM roles vs custom ones. I heard there is progress on it so looking forward to have it fix.

**Comment by aelij** [comment]
Seems like the role has been updated, closing
