### ISSUE TITLE
cannot add a new node pool with k8s version 1.19.7 via the azure portal, only options available are 1.18.19 and 1.18.17

### ISSUE THREAD

**Issue by giordyb** [Azure/AKS#2419]
**What happened**:
When creating a new node pool from the azure portal on a cluster version 1.19.7 the only versions available are 1.18.19 and 1.18.17, not the version that the cluster is running.
I was able to create a node pool with the correct version a few months ago but now it's not working anymore.

**What you expected to happen**:
to be able to create a new node pool with the actual cluster version

**How to reproduce it (as minimally and precisely as possible)**:
try to create a new node pool

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.7
- Size of cluster (how many worker nodes are in the cluster?) 6
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by justindavies** [comment]
Hi there, if you are only seeing 1.18, then I think there is something wrong.  Would you be able to open a support request please ?

**Comment by giordyb** [comment]
> Hi there, if you are only seeing 1.18, then I think there is something wrong. Would you be able to open a support request please ?

Hi @justindavies,

I'd gladly open a SR but I'm on the basic support plan...that's why I opened an issue here.
