### ISSUE TITLE
Why aren't there automatic intermediate Kubernetes upgrades?

### ISSUE THREAD

**Issue by ropinheiro** [Azure/AKS#2422]
**What happened**:

I tried to upgrade from a deprecated Kubernetes v1.18 version to a v1.20 version.

It didn't allowed me to do it. First I had to upgrade to a currently valid v1.18 version, then to a v.19, and finally to a v1.20.

**What you expected to happen**:

Azure taking care of all the "domino" upgrades required to reach the version I wanted, following the upgrade table.

**Comment by justindavies** [comment]
Hi there, our concern with carrying out the jumps over major versions is that once the upgrade has happened, we cannot downgrade it.  So if there has been a workload issue, or a deprecated API you are using from one release to another you will end up with a broken cluster.
