### ISSUE TITLE
Azure Policy addon doesn't send/download data after changing the AKS cluster to use ManagedIdentity from SP

### ISSUE THREAD

**Issue by robbiezhang** [Azure/AKS#2424]
**What happened**:
After a ServicePrincipal cluster is converted to use ManagedIdentity for authentication, the Azure Policy addon will stop sending/downloading data from the Azure Policy data plane service.
This issue only applies to the SP cluster which already enabled the Azure Policy addon, and is converted to use ManagedIdentity for authentication.

The workaround is to disable and re-enable the Azure policy addon after the convertion.

**What you expected to happen**:
The Azure policy addon should continue to send/downloading data from the Azure Policy data plane service after converting from SP to MI.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a AKS cluster using ServicePrincipal
2. Enable the Azure Policy addon
3. Convert the cluster to use ManagedIdentity
4. Assign a policy to the cluster
5. The policy will never get downloaded to the cluster as a GateKeeper contraints CRD.

**Anything else we need to know?**:
It's a code bug in AKS.

**Environment**:
- Kubernetes version (use `kubectl version`): any
- Size of cluster (how many worker nodes are in the cluster?) any
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by justindavies** [comment]
@miwithro FYI
