### ISSUE TITLE
metrics-server not working on fresh 1.20.7

### ISSUE THREAD

**Issue by Morriz** [Azure/AKS#2425]
Hi, I just installed a fresh cluster at version 1.20.7, but see no metrics. The metrics-server only shows errors:

```
metrics-server not working after cluster auto-upgrade to 1.20.5
```
(repeated for every pod it scans)

This does repair itself and then metrics go offline again.

The cluster was created with the following cli call:
```
az aks create -n 'otomi-aks-dev' -g 'otomi-aks-dev' --zones 1 2 --load-balancer-outbound-ips $ingress_ip_id,$ingress_ip_id --enable-cluster-autoscaler --network-plugin 'azure' --network-policy 'calico' --nodepool-name 'agentpool1' --kubernetes-version '1.20.7'  --max-count '7' --max-pods '42' --min-count '2' --node-osdisk-size '200' --node-vm-size 'Standard_D3_v2'    
```

With the ingress ip created up front. The install showed no errors. Note that I specifically wanted to install a 1.20.6+ cluster because of the new upstream feature allowing to use one static ip address for both ingress and egress. See discussions around the needs for that here:
- https://github.com/Azure/AKS/issues/1791
- https://github.com/Azure/AKS/issues/2301

A similar report about missing metrics was found in #2384.

**Comment by Morriz** [comment]
The metrics came back later. Glitchy?

**Comment by mikepasco** [comment]
Hi @Morriz we're sorry for the delay in reaching your issue. Can you please confirm if you are still facing this issue?

**Comment by Morriz** [comment]
not an issue anymore
