### ISSUE TITLE
[1.20+ AKS Cluster] headless service returining the IPs of NON ready pods

### ISSUE THREAD

**Issue by yazbekhe** [Azure/AKS#2426]
**What happened**: when resolving headless service with core-dns it returns the IPs of pods that are not ready yet

**What you expected to happen**: it should return only the IPs of the ready pods

**How to reproduce it (as minimally and precisely as possible)**:
the manifests i have used for testing are attached 
[svc.txt](https://github.com/Azure/AKS/files/6761588/svc.txt)
[nginx.txt](https://github.com/Azure/AKS/files/6761590/nginx.txt)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.7 also i tested with 1.20.5
- Size of cluster (how many worker nodes are in the cluster?) 1 nodes (test cluster)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by yazbekhe** [comment]
kubernetes upstream says that the fix is released in 1.8.4 while aks installs 1.8.3

**Comment by robbiezhang** [comment]
probably cause by this issue:
https://github.com/coredns/coredns/issues/4594

**Comment by robbiezhang** [comment]
reopen as the change is not yet adopted in AKS.

**Comment by bgood57** [comment]
Does anyone have a workaround for this until it's incorporated into AKS?  Or a way to use a different version of CoreDNS that won't get forced back to 1.8.3 with this bug in it?  Thanks!

**Comment by yazbekhe** [comment]
simply update the deployment of core dns to use the newer version

**Comment by bgood57** [comment]
@yazbekhe  That's what we thought too. When we do that, it starts 1.8.4, but then AKS (1.20.7) removes that deployment and forces it back to 1.8.3.

**Comment by yazbekhe** [comment]
@bgood57 the workaround i have used is: i have deployed a layer7 proxy "envoy" in front of the service where i can configure a probe

**Comment by djsly** [comment]
Are we expecting CoreDNS 1.8.4 to be pushed automatically soon ?

**Comment by miwithro** [comment]
@robbiezhang who is tracking this one closely.

**Comment by djsly** [comment]
thanks @miwithro , a soonish upgrade would be nice to have, we started causing failures for our clients each time we deploy/upgrade our software stack...

**Comment by robbiezhang** [comment]
1.8.6 is rolled out to all the regions.

**Comment by djsly** [comment]
confirmed! thanks a lot @robbiezhang , took some time but I'm sure this will be stable now!
