### ISSUE TITLE
upgrading AKS to ver 1.20.5 ---any know issues

### ISSUE THREAD

**Issue by NirajCricket** [Azure/AKS#2428]
In AKS we don't have 1.20.6 release , as I see in K8s release, does it mean ver 1.20.5 is impacted by the bug mentioned here?
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md
image
![image](https://user-images.githubusercontent.com/35249470/124532700-65b65780-de54-11eb-9bf6-10e2b19138f0.png)

**Comment by justindavies** [comment]
This has been hotfixed into all available releases
