### ISSUE TITLE
[Request] Upgrade channel - being able to have patch and node images

### ISSUE THREAD

**Issue by lgmorand** [Azure/AKS#2429]
Currently, the [auto-upgrade channel](https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel) makes you to choose between either an upgrade of k8s or an update of the node image.

It seems they are handled separatly which means you have to choose between having:
- the cluster up to date
- the node + aks layer up to date

A cluster upgrade (version) may create new nodes and thus provide the last version of node image (if I'm not wrong) but if there is no new patch for k8s version, then the node-image will never be updated, which is not good because node-image is the best way to ensure node security and "aks" layer being up to date

Request : having a channel mode to have patch + node-image and having both of them triggering an update when available.

ps: I didn't update the existing features as they are GA already #1486 and #1303

**Comment by qpetraroia** [comment]
Hello!

Thanks for this feature request, our team will look into it.

**Comment by siegenthalerroger** [comment]
I can concur that I would prefer to have the ability to have a patch auto-upgrade of k8s, but having the node-image updated as soon as possible. Currently this is not possible (despite some of the documentation's wording making it seem like it). This is definitely required functionality IMO.

**Comment by palma21** [comment]
So you would like to have your node image updated every week and your patch version + node image every month correct? (keeping in might they are cumulative)

**Comment by lgmorand** [comment]
Hi Jorge, yes that's it.

Basically, customer just want their cluster be updated as soon as possible, whether on the OS part or the kubernetes version. On the second one, customers seem only confident with automated patch version.  BTW I never heard for automated minor version upgrade need yet

**Comment by vrdse** [comment]
+1
The requested described in the issue is exactly what I'm looking for and was expecting when I read about the new feature.

**Comment by asubmani** [comment]
### SCENARIO: Currently running 1.20.3

1) AKS releases 1.20.7 in my region that has "Patch" updates enabled for auto-node image updates.
        1.1) the cluster automatically gets updated from 1.20.3 --> 1.20.7 (*how long* since it 1.20.7 shows in `az aks get-versions --location` ??) 
        1.2 **EXPECTATION** :  Get the latest OS Image available when the patch version was upgraded e.g. `AKSUbuntu-1804gen2containerd-2022.01.19` (Not clear how long we need to wait for auto-update to kick in)
2)  AKS has a new release and a new Node Image e.g `AKSUbuntu-1804gen2containerd-2022.01.24`. No updates to Kubernetes minor versions. (i.e. latest version for 1.20 series is still 1.20.7)
       2.1) **EXPECTATION**:  The cluster will get the new image `AKSUbuntu-1804gen2containerd-2022.01.24`
          2.1.1)  If above is true, how long should one wait before expecting "Auto-update" to kick in? How often does nodeImage feature check and initate action?  HINT: `az aks nodepool get-upgrades` does show that `AKSUbuntu-1804gen2containerd-2022.01.24` is available for my cluster.
         2.2.2) Based on this issue, it seems node image for same AKS version **WON'T** be updated if one chooses "patch" version auto-upgrade channel.

Would prefer to choose between:

-  K8s versions only (any one auto upgrade channel)
-  K8 version *and* node image
-  Node Image only.

**Comment by asubmani** [comment]
UPDATE: I changed my `"upgradeChannel"` to  `"node-image"` and I haven't recieved the new `AKSUbuntu-1804gen2containerd-2022.01.24` images yet.

1. Does the node-image work on *new* images that are release AFTER you configure  `"upgradeChannel": "node-image"`
2. If the node-images will pick up latest available, what is the polling interval? Is there an API call to forcibly trigeer an evaluation?  (I know I can upgrade manually, but trying to understand when node-image will auto update and when it won't)

**Comment by asubmani** [comment]
After changing to `"upgradeChannel": "patch"'  TO `"upgradeChannel": "node-image"`, it took me <48 hrs to get the 2022.01.24 images.  previous image was the 01.19

As of now I will keep it as "node-image" updates only, and change to patch when ever there is a new patch version released.

**Comment by lgmorand** [comment]
My fellas, news are good. PG is already working on it so we should see something displayed in the roadmap very soon.

**Comment by ondrejhlavacek** [comment]
Adding this to my wishlist. I see no reason to delay any kind of Kubernetes patch version upgrades and node image upgrades. We handle Kubernetes minor version upgrades manually, but everything else should be upgraded automatically.

The Kubernetes patch versions are pretty quick and a cluster after a few weeks is running an unsupported Kubernetes versions. We had some incidents in the past when instead of solving the actual root cause we had to upgrade Kubernetes patch version first and then deal with the incident. Pretty annoying if you ask me.

**Comment by timown** [comment]
> My fellas, news are good. PG is already working on it so we should see something displayed in the roadmap very soon.

hey @lgmorand, was it added to the roadmap? couldn't find anything

**Comment by lgmorand** [comment]
@kaarthis awesome, that'd perfectly match the need of my customers. any card in the roadmap board ? I didn't find it.

 this way I could watch update during the monthly call :)

**Comment by kaarthis** [comment]
https://github.com/Azure/AKS/issues/2181

**Comment by lgmorand** [comment]
Hi @kaarthis 

That's great because we can now update the OS image before a new image is available but regarding the first need, it does not seem the need is filled. How can we ensure to get:
- a node image upgrade automatically if a component needs to be updated (i.e. ContainerD)
- a kubernetes patch upgrade as soon as patch is available ?

From what I understand, we still have the same issue to choose between "k8s" & "AKS" components upgrade. Am I right ?

**Comment by ArunSuryaPrakash** [comment]
Do we have any update on this issue ?

**Comment by amirschw** [comment]
I saw in the [release notes](https://github.com/Azure/AKS/releases/tag/2023-02-26) from today that it's now in preview:

[Node OS auto-upgrade channel](https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-node-image) for automatically applying OS security patches promptly

**Comment by kaarthis** [comment]
With nodeOSUpgrade Channel release you can do this. https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-node-image
