### ISSUE TITLE
AKS cannot access ACR when in different subscriptions when using SPN

### ISSUE THREAD

**Issue by vladbarosan** [Azure/AKS#243]
Following the steps here : https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-deploy-cluster#configure-acr-authentication will not work if the ACR is in another
subscription although the SP has been given the scope on the correct resource. ( also to mention that the instructions are wrong, you need Contributor access for some reason, not Reader )

Any ideas why is that ? is kind of blocker to need a registry in each subscription.

**Comment by slack** [comment]
Thanks for the docs feedback. /cc @neilpeterson 
Reader access should work. /cc @SteveLas

**Comment by mnadeau2** [comment]
What is the status on this issue ? having the same problem. AKS in subscription A, ACR in subscription B. Role assignment is visible in the ACR permission, but it doesnt pull the image. Any workaround ?

**Comment by andyzhangx** [comment]
There is an [upstream fix](https://github.com/kubernetes/kubernetes/pull/66429) would also solve this issue, it's in cherry picking to older k8s versions now.

**Comment by jnoller** [comment]
This issue was merged into k8s 1.9, marking closed.

**Comment by JohnGalt1717** [comment]
Is there documentation on how to make this happen? Az still won't let you do it between subscriptions that I can find based on the docs.

**Comment by jasonbrome** [comment]
> Is there documentation on how to make this happen? Az still won't let you do it between subscriptions that I can find based on the docs.

I am able to do this by specifying an ACR resource ID instead of just the container name.  This is now documented in [Authenticate with Azure Container Registry from Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration)

> Alternatively, you can specify the ACR name using an ACR resource ID, which has the following format:
> 
> `/subscriptions/\<subscription-id\>/resourceGroups/\<resource-group-name\>/providers/Microsoft.ContainerRegistry/registries/\<name\>`

e.g.

> `az aks create -n myAKSCluster -g myResourceGroup --generate-ssh-keys --attach-acr /subscriptions/<subscription-id>/resourceGroups/myContainerRegistryResourceGroup/providers/Microsoft.ContainerRegistry/registries/myContainerRegistry`
