### ISSUE TITLE
AKS cluster Availability-Zone awareness check

### ISSUE THREAD

**Issue by mumrau** [Azure/AKS#2432]
Hello,

We are using multiple AKS clusters that we created using `terraform`. These clusters have been upgraded all the way until `1.18.17`, but it shouldn't matter much. I am _confident_ that only one of my AKS is not zone-aware, but I need more than confidence.

My problem is that I cannot figure out whether my cluster control plane is `zone aware` as defined in https://docs.microsoft.com/en-us/azure/aks/availability-zones#create-an-aks-cluster-across-availability-zones. Neither the Azure portal or the Az cli provides me with that information. I find that very disturbing that the information isn't captured in a payload that is rendered somewhere.

As stated, let me quote:
```If you don't define any zones for the default agent pool when you create an AKS cluster, control plane components are not guaranteed to spread across availability zones. You can add additional node pools using the az aks nodepool add command and specify --zones for new nodes, but it will not change how the control plane has been spread across zones. Availability zone settings can only be defined at cluster or node pool create-time.```
I have since then modified my node pools for various reason, deleted some, re-created others, I do now have a multi-zone nodePool, but according to what is said, I am not resilient to a zone failure. The concept of `defaultNodePool` seems a little odd now that the nodepools definitino has slighty changed and the taints like `System` or `User` seem to be the new Azure way of dealing with stuff.

My question, or my feature request is the following: How do I make _sure_ that a cluster control plan is distributed accross zones _or_ is not. I need a straightforward answer from a trustable source in order to adjust my company's disaster plan.

Thanks!

**Comment by justindavies** [comment]
@palma21 does nodepool going AZ aware trigger the control plane too?

**Comment by mumrau** [comment]
@justindavies The documentation states that it does _not_.

Which is part of the issue, if the only trace of the AZ-awareness for the control plane resides in the `defaultNodePool`, the fact that this `defaultNodePool` is clearly mutable, and can be deleted as long as _another_ `nodePool` is tainted with `System` pool, the information is then completely lost.

**Comment by mumrau** [comment]
It is _not_ stale, no answer, no explanation, no workaround has been given.
This is not acceptable, that a parameter of this critcial importance is not verifiable whatsoever. This is critical for company policy in regards of availability and disaster recovery strategies. 

Please, bump this up. It has been `Under investigation` for 2 months, without giving any sort of feedback.

**Comment by seguler** [comment]
You do not change the availability zones of your control plane by changing the nodepools as it is written in the doc:

_You can add additional node pools using the az aks nodepool add command and specify --zones for new nodes, but it will not change how the control plane has been spread across zones._

If you want to make sure that your control plane is zone resilient, you need to create the cluster with the desired zone setting. Based on your description, your cluster's control plane is not zone resilient.

**Comment by rouke-broersma** [comment]
> You do not change the availability zones of your control plane by changing the nodepools as it is written in the doc:
> 
> _You can add additional node pools using the az aks nodepool add command and specify --zones for new nodes, but it will not change how the control plane has been spread across zones._
> 
> If you want to make sure that your control plane is zone resilient, you need to create the cluster with the desired zone setting. Based on your description, your cluster's control plane is not zone resilient. 

That doesn't fully answer the question though. The question is how can we figure out after the fact of our control plane is zone aware? Our clusters might be years old and have gone through any number of node pool changes. It would be great if we could query the current distribution of the control plane.

**Comment by maartengo** [comment]
@seguler could you reopen this issue? I think there is no clear answer to the question 'How do I make sure that a cluster control plan is distributed accross zones or is not'.

My team and I would also like a way to check this. Otherwise we would have to either raise support tickets for all of our clusters, or recreate all of them.

**Comment by mumrau** [comment]
If I may add @maartengo , the microsoft support team have rather elusive answers.... It took me dozens of messages to get a half-clear half-convincing answer....

I still find that a top tier availability configuration like this can be ignored rather shocking.

**Comment by seguler** [comment]
Unfortunately, there is no way to check if an existing cluster is AZ enabled or not. It does make sense to provide this visibility to customers, however, we do have a roadmap item to convert all non-AZ enabled clusters to AZ enabled clusters for every region where multiple AZs are available. In my opinion, this will eliminate the need for your ask (a way to identify whether your cluster is AZ enabled or not), because it will be AZ enabled as long as it is in such a region. Does this make sense? 

I am trying to identify the timelines for this. When I know it concretely, I can share it here.
