### ISSUE TITLE
Need assistance on PureLB (standalone service LB controller) on AKS cluster - getting issues when tried to deploy on AKS 

### ISSUE THREAD

**Issue by pavandamarapati** [Azure/AKS#2434]
We are trying to install a stand alone service loadbalancer controller. The reason is that this controller communicates with our NVA and is required to setup services on our NVA (Acnodal EPIC) The stand alone service load balancer controller is called purelb. Docs are at https://www.purelb.io  opensource version is at https://gitlab.com/purelb/purelb The version we are installing is a little bit different but that doesn’t matter for this purpose.

AKS has a Cloud Controller that responds to Service API updates creating an Azure ALB and providing an address. Our customer would like to select between the Azure ALB or a Service Load Balancer provisioned by PureLB/EPIC
Security issues should be reported to secure@microsoft.com and not via this public issue tracker.

****What we tried:**** 
We tried a number of approaches to achieve these results. 
a. It’s not possible to add an authorization controller to AKS so that was a non-starter. 
b. An admission controller in AKS would operate after the Azure ALB is created; we could block the IP address returned in the service API update with  rego policy but the AKS ALB would still be created 
c. We attempted to see if we could set a policy on the Azure ALB resource. We hoped that there would be enough information passed by the cloud controller to the Azure API's for a Azure policy to identify an annotation or label on the ALB request. As tags are used throughout Azure, we though we could add a tag to the service, that would pass through to the Azure policy system and we could apply policy controls, unfortunately not. (we had a read of the cloud controller source) All we can do is block all requests to the Azure ALB.

We did find a workaround but its not acceptable for production use. We added the following annotations to the service: metadata: annotations: purelb.io/service-group: bloomtest-samplehttp service.beta.kubernetes.io/azure-load-balancer-internal: "true" service.beta.kubernetes.io/azure-load-balancer-internal-subnet: none The annotation to use an internal load balancer with an non existant vnet results in the cloud controller silently failing, specifically it never updates the service api with the IP address. The purelb loadbalancer controller only answers requests with the specific annotation shown above so in this case, purelb updates the service API and triggers the rest of the activation procedure. The reason this is not acceptable is that we are concerned that the Azure behavior could change, this would cause all of the customers loadbalancers to be incorrectly setup resulting in a significant outage. The ideal solution is for the Cloud controller to pass through an annotation, perhaps a tag, so the Azure policy engine can drop a request that is not for an Azure ALB

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19
- Size of cluster (how many worker nodes are in the cluster?) 3+

**Comment by palma21** [comment]
This seems like a feature request to the upstream cloud controller manager.
https://github.com/kubernetes-sigs/cloud-provider-azure

**Comment by feiskyer** [comment]
Filed https://github.com/kubernetes-sigs/cloud-provider-azure/issues/917 for tracking in cloud provider.
