### ISSUE TITLE
Provide a feature toggle to disable all storage related resources in v1.21+

### ISSUE THREAD

**Issue by scoof** [Azure/AKS#2437]
**What happened**: When upgrading to 1.21 (preview), CSI drivers are installed with new storageclasses. This clashes with our defaults, and we don't want it.

**What you expected to happen**: I expected a toggle that would allow me to disable the addon CSI drivers

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade to v1.21

**Anything else we need to know?**: Installing the CSI DaemonSets by default increases the security exposure for clusters that do not require persistent storage. The platform-provided storageclasses also makes it much harder to customize the installation, since one is actually named *Default* which will confuse users on clusters that don't use it as default. Your defaults are not our defaults, please don't assume that it's the case.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21

**Comment by justindavies** [comment]
Hi there, CSI is going to be the storage interface moving forward for the Kubernetes community, and as stated here:
https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-csi-migration-beta/#what-is-the-timeline-status

"We expect to complete this project including the full switch to “on-by-default” migration by Kubernetes v1.21."

Is the issue that the Default storageclass in 1.21 is different from that in previous versions or that it is named "Default" ?

**Comment by scoof** [comment]
The issue is that it's not a given that you even need storage in a cluster. The issue is that the driver is not configurable enough in the current form. The issue is that the default storageclass may not be the defaults that we want, and the hoops you need to jump through to change it are very convenient.

I read the "on-by-default" to be about migration. Not necessarily whether or not you force the driver on people. 

And even given that "on-by-default" is about the driver, it also implies that there's a way to change the default, and there's currently no way to turn it off.

**Comment by scoof** [comment]
Just to be clear: we were already running CSI drivers in a different configuration, and your addon installation stomped all over that

**Comment by andyzhangx** [comment]
cc @palma21

**Comment by axelgMS** [comment]
CRI 249064194

**Comment by palma21** [comment]
From 1.21 and further versions onward CSI will be the only option, at GA it will have migration enabled to avoid clashes but CSI will be the only storage solution supported on AKS in the future. We will announce before in-tree is deprecated.

You are completely free to specify you own default storage classes an not use our own, they are just there for commodity if case you didn't.

**Comment by scoof** [comment]
> > The issue is that the default storageclass may not be the defaults that we want, and the hoops you need to jump through to change it are very inconvenient.
> 
> Could you clarify which hoops you refer to aside from removing the default from the default SC and adding to the one of your choice? Is this what you refer?

To modify it, we would need to import it into our Terraform state, which is a manual operation. And even *if* we modify it to not be the default, it will still be named default and exist to confuse our users, since there is no way to permanently remove it.

> We don't provide a way to turn off the storage drivers in the same way the in-tree ones were never possible to "turn-off", the only change here is the way the are delivered changed.

The difference between the in-tree drivers and CSI is that it is now technically feasible to provide this ability to disable the driver completely.

> Similarly AKS also doesn't allow you to turn off other key addons like coredns and others as they are part of the managed service.

TBH, I think you should provide a feature toggle for coredns as well. I just don't have the need to disable coredns right now.

> You mentioned:
> 
> > The issue is that the driver is not configurable enough in the current form.
> 
> We happy to look into your use case, what things are you missing that you'd like to configure?

* We will run some clusters without need for PVCs at all (and I think we'll have 0 clusters with a need for azurefile CSI in the first year). Having the CSI pods running in those clusters is a security liability.
* We would like to run the CSI driver using a much more constrained identity than the node identity. Andy has already provided the means to do so in the Helm Chart.
* We would like to enable fsGroup support. Doing so requires a single value while deploying the helm chart, while doing it for the addon-version of the CSI driver requires us to deploy a standalone CSIDriver resource, which is just as much work as deploying the full driver in the way that we really want to.
* We have to restrict what storageclasses the users can use to prevent them from using the ones you provide. That is more work than just deploying the CSI helm chart and the correct storageclasses. We don't like the idea of modifying the classes you provide, since the naming would not be ideal, and if we delete them, you recreate them.
* I haven't managed to get snapshots working in the addon-version of the CSI azuredisk driver. Additionally, I haven't been able to export logs from the hidden controller pods, so I don't know why. I know this is preview, so I expect that to be fixed before GA.

Convenient defaults are fine, but you need to design for the cases where the defaults are not ideal for the consumer.

**Comment by palma21** [comment]
> To modify it, we would need to import it into our Terraform state, which is a manual operation. And even if we modify it to not be the default, it will still be named default and exist to confuse our users, since there is no way to permanently remove it.

Would it help if we change the name from default to something else that wouldn't confuse your users?

> The difference between the in-tree drivers and CSI is that it is now technically feasible to provide this ability to disable the driver completely.

We can consider that, hard to support as an opt in, but would you like it as an opt-out all the same? It has a few harder to support edge cases as some higher level features rely on storage and would need to be blocked in these clusters.

> TBH, I think you should provide a feature toggle for coredns as well. I just don't have the need to disable coredns right now.
A little bit harder, since working DNS is less of an option as the use of storage but point taken.

**Comment by scoof** [comment]
> > To modify it, we would need to import it into our Terraform state, which is a manual operation. And even if we modify it to not be the default, it will still be named default and exist to confuse our users, since there is no way to permanently remove it.
> 
> Would it help if we change the name from default to something else that wouldn't confuse your users?

It would help, but having the option to remove them entirely (also without removing the CSI addons) would be better.

> > The difference between the in-tree drivers and CSI is that it is now technically feasible to provide this ability to disable the driver completely.
> 
> We can consider that, hard to support as an opt in, but would you like it as an opt-out all the same?

Definitely. It wouldn't really matter to us if it's one way or another, since we would encode the choice in our HCL.

> > TBH, I think you should provide a feature toggle for coredns as well. I just don't have the need to disable coredns right now.
>
> A little bit harder, since working DNS is less of an option as the use of storage but point taken.

Coredns may not provide the featureset that we require. But that is a discussion for another time.

**Comment by scoof** [comment]
Any news on this? We're stuck on 1.20 until this gets implemented.

**Comment by carsv** [comment]
Ping.. Guys, this is approaching half a year also..

**Comment by justindavies** [comment]
Thanks for pinging on this, I'll pick this back up to see what we can do.  @scoof as Jorge said it is unlikely we would provide the ability to remove the drivers.  Is the blocking issue from 1.20 the ability to rename the SCs ?

**Comment by scoof** [comment]
> Thanks for pinging on this, I'll pick this back up to see what we can do. @scoof as Jorge said it is unlikely we would provide the ability to remove the drivers. Is the blocking issue from 1.20 the ability to rename the SCs ?

The blocking issue is both that there are clusters where we don't require storage, and we consider it a security issue to install software that exposes more attack surface, when it's not needed, as well as the fact that your installation is running under the node identity, which gives it way more privileges than it needs. That is also a security issue.

The SCs is not blocking as such, but it's quite a hassle to keep around SCs that you don't want users to use.

**Comment by jpflueger** [comment]
One of our customers has a slightly different use case for disabling specifically the azurefile CSI driver. On a smaller node size like `Standard_D2ds_v4` we are trying to save as much memory as possible. With the kubelet reservation taking up 1.8 GiB and the hard eviction limit of 750 MiB, we're already down to 5.45 GiB of usable memory before the memory requested by add-on daemonsets. In order to save every MiB we can, we'd prefer an option to either disable the azurefile CSI driver or configure the installation of it such that we can disable the daemonset on specific node pools using anti-affinity rules or tolerations.

Initially my thought was to check for an addon profile that I could use in the ARM template to configure the driver but I don't see it available. That seems like the right place to be able to configure it because there are already addon profiles for pod identity and the keyvault secrets provider.

**Comment by andyzhangx** [comment]
> One of our customers has a slightly different use case for disabling specifically the azurefile CSI driver. On a smaller node size like `Standard_D2ds_v4` we are trying to save as much memory as possible. With the kubelet reservation taking up 1.8 GiB and the hard eviction limit of 750 MiB, we're already down to 5.45 GiB of usable memory before the memory requested by add-on daemonsets. In order to save every MiB we can, we'd prefer an option to either disable the azurefile CSI driver or configure the installation of it such that we can disable the daemonset on specific node pools using anti-affinity rules or tolerations.
> 
> Initially my thought was to check for an addon profile that I could use in the ARM template to configure the driver but I don't see it available. That seems like the right place to be able to configure it because there are already addon profiles for pod identity and the keyvault secrets provider.

@jpflueger we are working on disabling azure disk, file drivers, and you could select which csi driver to disable, and in your case, you could only disable azure file csi driver, and then install open source azure file csi driver manually, and configure anything you want on that csi driver.

**Comment by ThiraviamR** [comment]
Is there any manual scripts available to disable the default csi drivers and files with AKS 1.21? Else when this toggle functionality will be available for general public

**Comment by scoof** [comment]
Kubernetes 1.20 is now deprecated, and it's still not possible to run 1.21 without a forced installation of the CSI drivers.
This is incredibly bad customer service.

**Comment by Skeen** [comment]
Any timeline for this?

**Comment by andyzhangx** [comment]
> Any timeline for this?

@Skeen we will roll out a preview feature for disabling csi drivers this month.

**Comment by andyzhangx** [comment]
> Any news on when this will be available?

@scoof This feature is actually already rolled out. And we are still working on updating the AKS doc. You could try this **Preivew** feature by:
```
az extension update --name aks-preview
az aks update -n $CLUSTER_NAME -g $RG_NAME --disable-disk-driver --disable-file-driver --disable-snapshot-controller 
```

**Comment by andyzhangx** [comment]
disabling CSI driver feature is already in public preview, follow guide here: https://docs.microsoft.com/en-us/azure/aks/csi-storage-drivers#disable-csi-storage-drivers-on-an-existing-cluster
