### ISSUE TITLE
[Feature] CIS Benchmark for Windows

### ISSUE THREAD

**Issue by keikhara** [Azure/AKS#2438]
Running assessment for CIS Benchmark on Windows 2019

**Comment by navjotsagoo** [comment]
Does this mean that once this feature is complete, by default the Windows OS images that are used to provision Windows node pools in AKS will be provisioned using Windows OS that meets the CIS benchmark as available in Azure? https://azuremarketplace.microsoft.com/en-us/marketplace/apps/center-for-internet-security-inc.cis-win-2019-stig?ref=website

**Comment by charleswool** [comment]
The Windows Sever 2019 is being depracted on AKS, please refer to the latest assessment against CIS Windows benchmark 2022: https://learn.microsoft.com/en-us/azure/aks/cis-windows
