### ISSUE TITLE
1.8.7 to 1.9.2 upgrade failed

### ISSUE THREAD

**Issue by rtyler** [Azure/AKS#244]
My cluster seems have failed to upgrade from 1.8.7 to 1.9.2, and while the cluster now shows itself in a 'Failed' `ProvisioningState`, I can still access applications running on the cluster.

```
tyler@Azure:~$ az aks list
Name            Location    ResourceGroup    KubernetesVersion    ProvisioningState    Fqdn
--------------  ----------  ---------------  -------------------  -------------------  --------------------------------------------------------
spyglass-kubes  eastus      spyglass         1.9.2                Failed               REDACTED.eastus.azmk8s.io
tyler@Azure:~$
```

`kubectl get pods --all-namespaces` also shows that all the pods are in a proper `Running` state, so I'm not sure what the heck is going on here :)

**Comment by jasonchester** [comment]
Same situation here after upgrade from 1.8.7 to 1.9.2. 

```
00:49 $ az aks show -g rgdev01 -n dev01kube01 -o table
Name         Location    ResourceGroup    KubernetesVersion    ProvisioningState    Fqdn
-----------  ----------  ---------------  -------------------  -------------------  --------------------------------------------
dev01kube01  centralus   rgdev01          1.9.2                Failed               dev01kube01-fe8451de.hcp.centralus.azmk8s.io
```
```
00:54 $ kubectl get node -o wide
NAME                         STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                      KERNEL-VERSION      CONTAINER-RUNTIME
aks-dev01pool01-22709369-0   Ready     agent     16d       v1.8.7    <none>        Debian GNU/Linux 8 (jessie)   4.13.0-1011-azure   docker://1.12.6
aks-dev01pool01-22709369-1   Ready     agent     16d       v1.8.7    <none>        Debian GNU/Linux 8 (jessie)   4.13.0-1011-azure   docker://1.12.6```

**Comment by mactr0n** [comment]
Sam problem here.

**Comment by hibri** [comment]
Same here. Using Terraform and seeing a ControlPlaneNotReady error message

**Comment by slack** [comment]
Check for failed deployments on the `MC_` resource group holding your nodes. As we do a node to node replacement, one of those operations may have failed.

**Comment by mactr0n** [comment]
There are no failed deployments. The status of all deployments is "Succeeded".

**Comment by rtyler** [comment]
@slack Just a heads up, I can confirm that there are no failed ARM deployments in the MC_* resource group for this AKS cluster.

The most recent Deployment event is from February however, so I do not see an event which may correspond to my upgrade attempt.

**Comment by hibri** [comment]
One of our clusters is in a failed state. Happy to send details privately @slack 
```bash

Name                     Location    ResourceGroup                   KubernetesVersion    ProvisioningState    Fqdn
-----------------------  ----------  ------------------------------  -------------------  -------------------  -------------------------------------------------------------------
<redacted>  westeurope  <redacted>  1.9.2                Failed               <redacted>

```

```bash
› kubectl get nodes
NAME                      STATUS    ROLES     AGE       VERSION
aks-pool0001-27034702-0   Ready     agent     9d        v1.8.7
aks-pool0001-27034702-1   Ready     agent     8d        v1.8.7
aks-pool0001-27034702-2   Ready     agent     8d        v1.8.7
aks-pool0001-27034702-3   Ready     agent     8d        v1.8.7
aks-pool0001-27034702-4   Ready     agent     8d        v1.8.7
aks-pool0001-27034702-5   Ready     agent     8d        v1.8.7
aks-pool0001-27034702-6   Ready     agent     8d        v1.8.7
```

**Comment by polys** [comment]
Had the exact same issue last week when trying to upgrade a v1.8.7 cluster to v1.9.2. I tried 3 or 4 times hoping to get out of the 'failed' provisioning state but all attempts were unsuccessful.

I then [manually drained](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/) and restarted every single node and tried the upgrade again. This time it worked perfectly and was much faster than my previous failed attempts.

**Comment by rtyler** [comment]
Re-running the upgrade this morning allowed the upgrade to complete properly, thanks for fixing whoever-did-that-at-Microsoft :+1: :smile:
