### ISSUE TITLE
Unable to Delete Cluster due to public IP address

### ISSUE THREAD

**Issue by hasandogu** [Azure/AKS#2443]
Hi there,

**What happened**:

We have an AKS cluster that we would like to delete but couldn't achieve that through portal or CLI.

I have found a similar issue and followed the steps as we were also using ACI service for virtual nodes: https://github.com/Azure/AKS/issues/1427

Although we followed to remove everything related with ACI, we still cannot delete the cluster

The latest error we got is related with a Public IP but we cannot remove it as `az network public-ip list` just returns an empty array for us. This is the only cluster in our subscription and

Deployment failed. Correlation ID: 871568da-ad93-411b-b411-b51acf637ce3. ResourceGroupReconciler retry failed: Category: ClientError; SubCode: PublicIPAddressCannotBeDeleted; Dependency: Azure Resource Manager; OrginalError: Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=409 -- Original Error: Code="ResourceGroupDeletionBlocked" Message="Deletion of resource group 'MC_orderinbox-west-us_orderinbox_westus' failed as resources with identifiers 'Microsoft.Network/networkProfiles/vk-c4b98b20d03efaa88fc2e1be48a3f4f1b61e8b18f611e80986276441e7636a1d,Microsoft.Network/publicIPAddresses/8ad1680b-d7d6-4db9-8904-6fe1407f9be2' could not be deleted. The provisioning state of the resource group will be rolled back. The tracking Id is '3c98ddde-17e0-4332-90b6-62ec7bd914a4'. Please check audit logs for more details." Details=[{"AdditionalInfo":null,"Code":null,"Details":null,"Message":"{\"error\":{\"code\":\"NetworkProfileAlreadyInUseWithContainerNics\",\"message\":\"Network profile /subscriptions/1336b84d-ed25-401f-a604-e133340014d4/resourceGroups/MC_orderinbox-west-us_orderinbox_westus/providers/Microsoft.Network/networkProfiles/vk-c4b98b20d03efaa88fc2e1be48a3f4f1b61e8b18f611e80986276441e7636a1d is already in use with container nics a3ecdc52-dc68-42f4-87a0-e923c79c2bc5_eth0,5f174c69-61f6-480a-bea3-1b3d117378e8_eth0,dc1225a9-2ec6-4a24-81b1-855166d657ac_eth0; cannot update or delete\",\"details\":[]}}","Target":"/subscriptions/1336b84d-ed25-401f-a604-e133340014d4/resourceGroups/MC_orderinbox-west-us_orderinbox_westus/providers/Microsoft.Network/networkProfiles/vk-c4b98b20d03efaa88fc2e1be48a3f4f1b61e8b18f611e80986276441e7636a1d"},{"AdditionalInfo":null,"Code":null,"Details":null,"Message":"{\"error\":{\"code\":\"PublicIPAddressCannotBeDeleted\",\"message\":\"Public IP address /subscriptions/1336b84d-ed25-401f-a604-e133340014d4/resourceGroups/MC_orderinbox-west-us_orderinbox_westus/providers/Microsoft.Network/publicIPAddresses/8ad1680b-d7d6-4db9-8904-6fe1407f9be2 can not be deleted since it is still allocated to resource /subscriptions/1336b84d-ed25-401f-a604-e133340014d4/resourceGroups/MC_orderinbox-west-us_orderinbox_westus/providers/Microsoft.Network/loadBalancers/kubernetes/frontendIPConfigurations/8ad1680b-d7d6-4db9-8904-6fe1407f9be2. In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublicip.\",\"details\":[]}}","Target":"/subscriptions/1336b84d-ed25-401f-a604-e133340014d4/resourceGroups/MC_orderinbox-west-us_orderinbox_westus/providers/Microsoft.Network/publicIPAddresses/8ad1680b-d7d6-4db9-8904-6fe1407f9be2"}]; AKSTeam: RP

We ran the script provided here also without success: https://github.com/Azure/AKS/issues/1427#issuecomment-584704864

BadRequestError: (NetworkProfileAlreadyInUseWithContainerNics) Network profile /subscriptions/1336b84d-ed25-401f-a604-e133340014d4/resourceGroups/MC_orderinbox-west-us_orderinbox_westus/providers/Microsoft.Network/networkProfiles/vk-c4b98b20d03efaa88fc2e1be48a3f4f1b61e8b18f611e80986276441e7636a1d is already in use with container nics a3ecdc52-dc68-42f4-87a0-e923c79c2bc5_eth0,5f174c69-61f6-480a-bea3-1b3d117378e8_eth0,dc1225a9-2ec6-4a24-81b1-855166d657ac_eth0; cannot update or delete

BadRequestError: (SubnetMissingRequiredDelegation) Subnet /subscriptions/1336b84d-ed25-401f-a604-e133340014d4/resourceGroups/orderinbox-west-us/providers/Microsoft.Network/virtualNetworks/orderinbox-west-us-vnet/subnets/virtual-node-aci requires any of the following delegation(s) [Microsoft.ContainerInstance/containerGroups] to reference service association link /subscriptions/1336b84d-ed25-401f-a604-e133340014d4/resourceGroups/orderinbox-west-us/providers/Microsoft.Network/virtualNetworks/orderinbox-west-us-vnet/subnets/virtual-node-aci/serviceAssociationLinks/acisal.

**What you expected to happen**:
We expect the AKS cluster to be deleted smoothly.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Any guidance on this would be truly appreciated. Many thanks in advance.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"5a7170d3bbf1731483f4844c2222c70501717341", GitTreeState:"clean", BuildDate:"2021-05-25T17:36:45Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
1

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Media processing

- Others:

**Comment by qpetraroia** [comment]
Hi @hasandogu,

Are you still trying to delete your cluster? If so, please open a support ticket and we can get this resolved as soon as possible. Thank you!

**Comment by hasandogu** [comment]
Yes, we are still trying. I am not sure if this issue really requires the
purchase technical support plan though. This is not something that is
caused by us since the instructions we are provided simply do not work for
this instance, as what cannot be deleted is not within our control (ACI
subnet).

**Comment by palma21** [comment]
No, tickets do not require a paid plan, you should have the free plan option to open them.

Have you followed?
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-vnet#clean-up-resources
https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli#remove-virtual-nodes
