### ISSUE TITLE
Starting with AKS 1.20 when a AKS cluster is created, it adds cluster tags on the UDR  resource

### ISSUE THREAD

**Issue by flbla** [Azure/AKS#2444]
**What happened**:
Starting with AKS 1.20 when a node is created, it adds cluster tags on the UDR (userDefinedRouting) resource. 

**What you expected to happen**:
No tags should be added (as it was with previous version of AKS)

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster AKS 1.20 or 1.21 with userDefinedRouting and check the UDR tags, cluster tags will be added on it.

Could you please add a feature to disable it?

**Anything else we need to know?**:
I didn't find this changed in the CHANGELOG neither in the release note.

**Comment by Shuanglu** [comment]
should be related with this feature 
https://kubernetes-sigs.github.io/cloud-provider-azure/topics/tagging-resources/  
https://github.com/kubernetes/kubernetes/commit/b33715711ed4d77f540bb031cc004d6694a8a361#diff-625b77ef1678b3dbb9c92d4a1a4f95a3857c262a30681c758c3833f0460192e3

**Comment by palma21** [comment]
It was a feature coming with 1.20, it's not on the notes because it's still missing a few adds to the experience, should be there soon.

You mention you'd like to have it disabled, this is just propagating the tag from the managed AKS resource to all its dependent resources, if no tag is there, there's no propagation.

Could you clarify more your use case?

**Comment by flbla** [comment]
Our UDR resources already have tags, for eg ENVIRONMENT (highercase).
The problem is, on our clusters with also have tag environment (but with lowercase).
Due to this nodes were not able to use the UDR and stayed in "not ready" state, trying infinitely to create the tag "environment" which already exist in capital letter.

Furthermore, in a near future we would like to create more than one cluster in a subnet, but in our cluster tags we have a tag "cluster name" and other tags which are different between clusters.

**Comment by flbla** [comment]
I tested with 2 clusters 1.21 in the same subnet using the same UDR.
I have no problem on clusters, but the tags on the UDR are continuously updating with tags of cluster 1 then with cluster 2, then with 1, etc.. 
I don't know if there is other impacts

**Comment by palma21** [comment]
AKS should only be tagging route tables of kubenet clusters, but you say:
> Furthermore, in a near future we would like to create more than one cluster in a subnet,

Which is [not supported](https://docs.microsoft.com/en-us/azure/aks/configure-kubenet#prerequisites) with kubenet.

Are you saying they are propagating the tags to Route Tables when you're using Azure CNI?

**Comment by flbla** [comment]
we use Kubenet
it's not supported, but it works, just need to have different CIDR for pod

**Comment by miwithro** [comment]
@flbla  can you expand more on your ask?
