### ISSUE TITLE
Provisioning state not shown in the portal for cluster nodepools, instead power state is shown

### ISSUE THREAD

**Issue by porrascarlos802018** [Azure/AKS#2446]
please revert back and show the provisioning status for the nodepool , under the portal and add clarification on what status means and what are the possible status shown. 

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by porrascarlos802018** [comment]
Reference ID : 249828860

**Comment by chandraneel** [comment]
Thanks a lot for bringing this to our attention.
We are actively working on resolving this, will keep this updated as we make progress.

**Comment by haugerbr** [comment]
@porrascarlos802018 we have started to release the change. If you would like to use it before it is fully released, you can use https://preview.portal.azure.com

**Comment by chandraneel** [comment]
The fix is now deployed in all regions, hence closing the issue
