### ISSUE TITLE
AKS- Dynamic Provisioning not working for statefulsets using Azure file as storage class for replicas greater than 1

### ISSUE THREAD

**Issue by kethasid** [Azure/AKS#2447]
-->

**What happened**:

We are trying to implement Azure file for our PV in aks cluster. We are trying to deploy a statefulset with 6 replicas,
We created a storage class for azure file and also PV which points to the storage account in azure. 
When the statefulset gets deployed the first pod runs fine but the the next one goes into pending state. 
Issue is that the second PVC is unable to get the secret for the storage account. 
This means that we would need to manual create PV for each replica containing the secret or remove the secret from the storage account. For storage class with no secret associated scaling of the statefulset works fine. 

**What you expected to happen**:

Dynamically provision PV for azure file 

**How to reproduce it (as minimally and precisely as possible)**:

Try to implement the manifest provided by @andyzhangx in the issue https://github.com/Azure/AKS/issues/1906
In this manifest the replica count is 1. Would recommend to increase the replica count and see if the PV get dynamically provisioned 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18
- Size of cluster (how many worker nodes are in the cluster?) 8
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
trying to deploy elasticsearch on aks cluster. Elasticsearch recommends use of statefulsets 

Below is the screesnshot where it shows the error for the 2nd PVC 

![image](https://user-images.githubusercontent.com/49861388/125949447-b96918b4-5281-4759-b06e-f95f1e9d90da.png)

**Comment by andyzhangx** [comment]
the error shows you don't have listKeys permission to one storage account.

**Comment by kethasid** [comment]
@andyzhangx . Question is how come the 1st PVC is bounded to the PV ? 
any suggestions as to how it will get resolved

**Comment by andyzhangx** [comment]
you have a predefined `pv-azurefile` pv, and 1st PVC is bound to that pv directly, and for the second PVC, azure file driver needs to create a new PV(file share)

**Comment by kethasid** [comment]
@andyzhangx So to resolve this the Service principal needs to have the role of Microsoft.Storage/storageAccounts/listKeys/action and then it would be able to create infinite no of PV for each of the replica. Correct me if I'm wrong

**Comment by andyzhangx** [comment]
> @andyzhangx So to resolve this the Service principal needs to have the role of Microsoft.Storage/storageAccounts/listKeys/action and then it would be able to create infinite no of PV for each of the replica. Correct me if I'm wrong

also need write permission of that storage account since it needs to create file share inside that storage account

**Comment by kethasid** [comment]
> > @andyzhangx So to resolve this the Service principal needs to have the role of Microsoft.Storage/storageAccounts/listKeys/action and then it would be able to create infinite no of PV for each of the replica. Correct me if I'm wrong
> 
> also need write permission of that storage account since it needs to create file share inside that storage account

@andyzhangx Thank you so much for your inputs. Will try to implement the same
