### ISSUE TITLE
az aks stop not in command group

### ISSUE THREAD

**Issue by hron84** [Azure/AKS#2459]
**What happened**:
I trying to follow the official Microsoft documentation for [stopping an AKS cluster](https://docs.microsoft.com/en-us/azure/aks/start-stop-cluster). However azure cli says:

```
[hron@SFE1414 h2 ] $ az aks stop --name chat-aks --resource-group chat
az aks: 'stop' is not in the 'az aks' command group. See 'az aks --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
```
When I tried to use `aks-preview` extension, azure cli complained it cannot load the `aks-preview` extension.

**What you expected to happen**:

Successfully stop an AKS cluster

**How to reproduce it (as minimally and precisely as possible)**:

* Use Ubuntu 20.04
* Issue `apt-get install azure-cli`
* Do `az login`
* Try to stop an AKS cluster following the official documentation here: https://docs.microsoft.com/en-us/azure/aks/start-stop-cluster

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): AKS cluster is installed from an `1.18.19` template.
- Size of cluster (how many worker nodes are in the cluster?): 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Empty cluster
- Others: N/A

**Comment by qpetraroia** [comment]
Hi @hron84,

Glad to take a look at this. Can we get what version of the CLI you are running?
