### ISSUE TITLE
Enable Azure Site recovery for AKS or HA always on sync AKS clusters across regions.

### ISSUE THREAD

**Issue by porrascarlos802018** [Azure/AKS#2462]
Enable Azure Site recovery for AKS or HA always on sync AKS clusters across regions.

we currently have this recommendation, https://docs.microsoft.com/en-us/azure/aks/operator-best-practices-multi-region , but do we have any alternative way to have two clusters in sync across regions?

can Azure site and recovery be enabled for AKS?
https://azure.microsoft.com/en-us/services/site-recovery/#overview 

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by Kaarthis** [comment]
https://docs.microsoft.com/en-us/azure/aks/operator-best-practices-storage
