### ISSUE TITLE
Error : Microsoft.ContainerService/AutoUpgradePreview is not enabled

### ISSUE THREAD

**Issue by om3171991** [Azure/AKS#2463]
Hey Team,

We are getting the below error message while setting auto-upgrade for AKS:

➜  Library az provider register --namespace Microsoft.ContainerService                                                                             

➜  Library az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/AutoUpgradePreview')].{Name:name,State:properties.state}"
Name                                           State
---------------------------------------------  ----------
Microsoft.ContainerService/AutoUpgradePreview  Registered

➜  Library az aks update  --subscription XXXXXX -g XXXX --name XXXXX --auto-upgrade-channel stable                            
The behavior of this command has been altered by the following extension: aks-preview
(BadRequest) Feature Microsoft.ContainerService/AutoUpgradePreview is not enabled. Please see https://aka.ms/aks/previews for how to enable features.

➜  Library az --version
azure-cli                         2.25.0 *

core                              2.25.0 *
telemetry                          1.0.6

Extensions:
aks-preview                       0.5.25

Python location '/usr/local/Cellar/azure-cli/2.25.0/libexec/bin/python'
Extensions directory '/Users/shubham.g/.azure/cliextensions'

Python (Darwin) 3.8.10 (default, May  4 2021, 03:05:50) 
[Clang 12.0.0 (clang-1200.0.32.29)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by jodrisb** [comment]
I am experiencing the exact same issue
[deployer@5a992cc941d7 ~]$ az --version
azure-cli                         2.25.0 *

core                              2.25.0 *
telemetry                          1.0.6

Extensions:
aks-preview                       0.5.24
azure-firewall                    0.12.0

Python location '/usr/bin/python3'
Extensions directory '/home/deployer/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Nov 16 2020, 16:55:22)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by phealy** [comment]
Is this issue still occurring? If so, please open a service request so support can look at your subscription.

**Comment by phealy** [comment]
In addition, please upgrade your Azure CLI client to 2.30.0 before trying again. Auto upgrade support was made GA and thus no longer requires the preview flag, but your Azure CLI versions are from when it was still in preview. This can cause incompatibilities.

**Comment by om3171991** [comment]
@phealy - We are still getting this error without upgrading azure CLI. We will give 1 shot after upgrading.
