### ISSUE TITLE
ARM template deployment of node pools does more than it should

### ISSUE THREAD

**Issue by dsabsay** [Azure/AKS#2467]
**What happened**:

I'm trying as much as possible to use a set of ARM templates (with some extra templating on top) as declarative "infra-as-code".

I created a new node pool for cluster (via an ARM template following instructions [here](https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#manage-node-pools-using-a-resource-manager-template). I then drained and deleted all nodes in the cluster's original node pool. After that, I deleted the node pool via the Portal (on the AKS page).

I then looked at the "Export template" blade and copied the changes into my own templates. I updated my own templates until a `what-if` predicted _no change_ to the AKS or underlying resources. However, when I deploy the updated template, it places the cluster and the node pool into an "Updating" state for about 30 seconds to 1 minute. A bit odd in itself, but nothing seems to change, and I gather this is just the way ARM works (it sends "create" and "update" actions out even when nothing changes). It quickly transitions to "Succeeded" state and all is good.

The problem is, the template is stuck waiting for the node pool deployment to finish. After about 10 minutes, the deployment fails (only the node pool has an error). The error is:

```
operation discarded: current goalstate is not associated with the ongoing operation : operation: <some hash> - goalstate: <some other hash>
```

**What you expected to happen**:

Ideally, neither the cluster nor the node pool should enter an "Updating" state at all. `what-if` shows that nothing will change.

If that's just how ARM works, that's fine. But the deployment definitely should not be failing. Once the node pool goes back to "Succeeded" provisioning state (after changing nothing), the deployment should call it done.

**How to reproduce it (as minimally and precisely as possible)**:
I described things above, but I can provide more details if necessary.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by hieumoscow** [comment]
Thanks for notifying the issue, would be best if you can either provide the arm template or raise a support ticket for the team to check backend logs.
