### ISSUE TITLE
setting loadBalancerIP does not work with latest version kubernetes 1.9.2

### ISSUE THREAD

**Issue by patelmaulik** [Azure/AKS#247]
static IP setting is not working currently.
I have to resort to the workaround of querying the IP and changing it's DNS name to the predefined one.
Could you please confirm this bug with AKS ?

**Comment by feiskyer** [comment]
@patelmaulik Could you share the yaml of your kubernetes service?

**Comment by slack** [comment]
Rollout this week for AKS includes 1.9.6 support, which should fix this regression. Should be available in all Azure regions by Friday.
