### ISSUE TITLE
Migration to csi disk provisioner for custom storage classes

### ISSUE THREAD

**Issue by flo-02-mu** [Azure/AKS#2470]
**What happened**:
With the AKS version 1.21.2 the default storage provisioner has switched to CSI. All PVCs using the default storage class are automatically migrated to use the CSI disk provisioner. Custom storage classes that have been created prior to the cluster upgrade seem to remain on the azure-disk provisioner.

**What you expected to happen**:
It would be nice to have a way of migrating existing custom storage classes (e.g. via an annotation or via a CLI command). The documentation says nothing about the migration. The only way I currently see would be creating a new storageclass on the latest cluster version and migrate all PVCs towards it, which is a big effort.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a custom storageclass in AKS 1.20.x
2. Create a PVC using the custom storage class
3. Upgrade the cluster to AKS 1.21.x
4. Desribe the custom storageclass

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.2

**Comment by miwithro** [comment]
@andyzhangx

**Comment by andyzhangx** [comment]
the only way to do the migration is delete custom storage classes, and then create new storage class with csi disk provisioner, it's better leave this operation to AKS user since it would delete some customer data. And existing custom storage classes with in-tree disk provisioner still works.

**Comment by zhiweiv** [comment]
If delete existing storage class, recreate a new one with same name and csi provisioner, will the already provisioned pv/pvc work without any problem?

**Comment by andyzhangx** [comment]
> If delete existing storage class, recreate a new one with same name and csi provisioner, will the already provisioned pv/pvc work without any problem?

@zhiweiv yes, it would work, in-tree driver parameters are compatible with csi driver. Mainly we want user to do such migration manually since it requires deleting existing storage classes. 
@miwithro what do you think?

**Comment by andyzhangx** [comment]
storage class migration doc provided: https://docs.microsoft.com/en-us/azure/aks/csi-storage-drivers#migrating-custom-in-tree-storage-classes-to-csi
