### ISSUE TITLE
OMS agent on windows is created with securityContext.privileged: true

### ISSUE THREAD

**Issue by dvdvorle** [Azure/AKS#2471]
**What happened**:
When creating a new AKS cluster with Azure Monitor integration enabled, the daemonset omsagent-win will have securityContext.privileged set to true. This results in:

> Failed to create pod sandbox: rpc error: code = Unknown desc = failed to
>  create a sandbox for pod "omsagent-win-flhcw": Error response from daemon:
>  Windows does not support privileged mode

**What you expected to happen**:
When creating a new AKS cluster with Azure Monitor integration enabled, the daemonset omsagent-win will have securityContext.privileged set to **false**.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new cluster in the portal; add a user pool with windows nodes; enable Container Monitoring

**Anything else we need to know?**:
Manually editing the daemonset doesn't help, since it gets periodically (magically?) overwritten
**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.1
- Size of cluster (how many worker nodes are in the cluster?) 3 linux, 1 windows
- General description of workloads in the cluster: default
- Others: -

**Comment by robbiezhang** [comment]
It was caused by a bug fix in k8s 1.21. AKS is aware of the issue, and rolling out a hotfix.
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#bug-or-regression-3
Fix privileged config of Pod Sandbox which was previously ignored. (#96877, @xeniumlee)

**Comment by dvdvorle** [comment]
Ah thanks! I thought I checked all changelogs/issue lists, missed that one.
