### ISSUE TITLE
Private Endpoint for private AKS cluster does not update private DNS zone

### ISSUE THREAD

**Issue by sebader** [Azure/AKS#2476]
**What happened**:

As @feiskyer stated [here](https://github.com/Azure/AKS/issues/1978#issuecomment-771277641) it is supported to create additional private endpoints on a private AKS cluster. I tried that in Terraform and indeed the Private Endpoint gets created, it gets an private IP address from a subnet that is not the node-subnet. So far so good. 

However, the private DNS zone that I referenced when creating the private endpoint, did not get updated with an entry for the private IP address. I had to manually add the entry and now resolution works as expected.

**What you expected to happen**:

When creating the Private Endpoint with a referenced private DNS zone, an A record should have been created, as it does for other Azure services.

**How to reproduce it (as minimally and precisely as possible)**:

```
resource "azurerm_kubernetes_cluster" "stamp" {
  name                = "${local.prefix}-${local.location_short}-aks"
  location            = azurerm_resource_group.stamp.location
  resource_group_name = azurerm_resource_group.stamp.name
...

  private_cluster_enabled = true
  private_dns_zone_id     = "System"
}

# Create a private DNS zone which will look like fb5881da-5672-4a7a-94b5-0edacf296f80.privatelink.eastus2.azmk8s.io (extracted from a private cluster FDQN like abc.fb5881da-5672-4a7a-94b5-0edacf296f80.privatelink.eastus2.azmk8s.io)
resource "azurerm_private_dns_zone" "aks" {
  name                = regex("^(.+?)\\.(.+)$", azurerm_kubernetes_cluster.stamp.private_fqdn)[1]
  resource_group_name = "test-rg"
}

resource "azurerm_private_endpoint" "aks" {
  name                = "${local.prefix}-${local.location_short}-built-agent-aks-pe"
  location            = "westeurope"
  resource_group_name = "test-rg"
  subnet_id           = "${data.azurerm_virtual_network.buildagent.id}/subnets/aks-pe-snet"

private_dns_zone_group {
     name                 = "privatednsaks"
     private_dns_zone_ids = [azurerm_private_dns_zone.aks.id]
 }

  private_service_connection {
    name                           = "aks-privateserviceconnection"
    private_connection_resource_id = azurerm_kubernetes_cluster.stamp.id
    is_manual_connection           = false
    subresource_names              = ["management"]
  }
}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.7

**Comment by feiskyer** [comment]
This is caused by a known limitation from PrivateLink side. AKS doesn't have permission to update the private DNS zone and customer needs to update it manually as a workaround.

**Comment by sebader** [comment]
thanks @feiskyer A couple of follow up question then:
- Is it a stable workaround or can the private IP address change over the lifetime of an AKS cluster?
- Why does AKS require additional permissions compared to other services such as Storage or KeyVault? Why cant AKS use the same mechanism to update the private DNS zone?

**Comment by feiskyer** [comment]
- the ip should not change unless the PE is deleted and recreated
- I'm not sure about other services, but AKS RP has a very limited permissions to customer resources

**Comment by sebader** [comment]
Other RPs use a built-in account called "Azure Traffic Manager and DNS" to update the private DNS Zones. See here for an example with Container Registry
![image](https://user-images.githubusercontent.com/11445087/128854709-bfb3aad8-70f4-4e91-8ba1-417090b9a27f.png)
