### ISSUE TITLE
Swagger has incorrect casing for containerLogMaxSizeMb

### ISSUE THREAD

**Issue by jquincy-manticore** [Azure/AKS#2479]
**What happened**:
I tried to use the --kubelet-config preview flag and set the containerLogMaxSizeMb size to be 50,  The change didn't make it to the nodes.  This was because the swagger at https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2021-05-01/managedClusters.json#L4549 has containerLogMaxSizeMB. 
**What you expected to happen**:
The kubelet to be updated with the proper value
**How to reproduce it (as minimally and precisely as possible)**:
use a kubeletconfig file with contents
{
    "containerLogMaxSizeMB": 50,
    "containerLogMaxFiles": 5
}
the container log max size won't be recognized by the service due to the incorrect casing.  And won't make it to the kubelet or throw an error on node pool creation.

**Comment by justindavies** [comment]
Thanks for raising this, I’ll get this updated in the cli

**Comment by justindavies** [comment]
Fixed in the CLI: https://github.com/Azure/azure-cli-extensions/commit/cc860fcc385634fb8d503240f41922832d082ba8
