### ISSUE TITLE
az disk update LinkedAuthorizationFailed

### ISSUE THREAD

**Issue by castleadmin** [Azure/AKS#2481]
**What happened**:
`az disk update` throws a `LinkedAuthorizationFailed` error when updating the SKU.

Background:
Currently, there is no direct way to set the AKS VM disk SKU (https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/35056588-allow-selecting-disk-type-when-creating-aks-cluste). However, when an AvailabilitySet is used instead of a VMSS then the disk SKU can be set after the cluster creation. Due to an image reference to an external subscription inside the disk resource the `az disk update` command currently fails with an `LinkedAuthorizationFailed` error. Changing the disk SKU is possible without errors when the Azure portal is used.

Currently I'm using the following workaround to update the disk SKU:
```
#!/bin/bash
resourceGroupName="some-namespace"
sku="StandardSSD_LRS"

echo "Starting VM disk type update script"
vmIds=$(az vm list --resource-group "$resourceGroupName" --query "[].id" --output tsv)

echo "VM ids:"
for vmId in $vmIds
do
  echo "$vmId"
done

for vmId in $vmIds
do
  echo "---"
  echo "Checking VM $vmId"

  vmName="$(az vm get-instance-view --ids "$vmId" --query "name" --output tsv)"
  echo "VM name $vmName"
  vmDiskId=$(az vm get-instance-view --ids "$vmId" --query "storageProfile.osDisk.managedDisk.id" --output tsv)
  echo "VM disk $vmDiskId"
  vmDiskSku=$(az disk show --ids "$vmDiskId" --query "sku.name" --output tsv)
  echo "VM disk SKU $vmDiskSku"

  if [ $vmDiskSku = "$sku" ]
  then
    echo "VM disk SKU doesn't need to be changed"
    continue
  fi

  echo "Drain node"
  kubectl drain "$vmName" --ignore-daemonsets --delete-emptydir-data
  echo "Deallocate VM"
  az vm deallocate --id "$vmId"
  echo "Updating VM disk SKU"
  # --remove creationData.galleryImageReference is a hack to avoid the LinkedAuthorizationFailed error
  # The galleryImageReference isn't removed by this command
  az disk update --ids "$vmDiskId" --sku "$sku" --remove creationData.galleryImageReference
  echo "Start VM"
  az vm start --id "$vmId"
  echo "Uncordon node"
  kubectl uncordon "$vmName"
done
echo "---"
echo "Done"
```

**What you expected to happen**:
Using `az disk update` should be possible if external images are referenced.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an AKS cluster with a VM AvailabilitySet
2. Run the script above without ` --remove creationData.galleryImageReference`

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.7

**Comment by miwithro** [comment]
@andyzhangx

**Comment by andyzhangx** [comment]
Allow selecting disk type when creating AKS cluster
There is no way to select disk type (Standard or Premium) when creating an AKS cluster via Portal or Azure CLI, by default Node OS disk type is derived from the selected VM size.

To be more specific, I want a node StandardB2s with Standard disk. If I create a plain VM, I can select such configuration. If I create an AKS cluster with StandardB2s node, I can stop the node and change the disk type to Standard, but I cannot select Standard_B2s + Standard disk while creating AKS cluster.

**Comment by andyzhangx** [comment]
that's a new feature request, use workaround `az disk update` could change the disk sku for a while; and after scale down & up or aks version upgrade, existing changes will be gone.

**Comment by andyzhangx** [comment]
pls file an issue in https://github.com/Azure/azure-cli if you still have such issue. change vm sku directly is not supported from AKS  perspective.
