### ISSUE TITLE
tigera-operator should have a priorityClass defined similar to Calico workloads

### ISSUE THREAD

**Issue by lorenzo-biava** [Azure/AKS#2482]
**What happened**:

Observed a new addon being deployed by AKS in the tigera-operator namespace.
It's not showing any PriorityClass and being related to the deployment of Calico workloads it looks to be a somehow critical component as well.

**What you expected to happen**:

The tigera-operator/tigera-operator deployment should have a PriorityClass defined, to avoid any issues on the networking stack/network policies/etc. in case it gets evicted over time.

**How to reproduce it (as minimally and precisely as possible)**:

It just comes up with a new AKS cluster with azure-networking + calico (it's present in v1.20.7; EASTUS; created since 2020-08-09 - at least)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.7
- Size of cluster (how many worker nodes are in the cluster?) N/A
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) N/A
- Others: N/A

**Comment by qpetraroia** [comment]
@mattstam Hey Matt, any update on this?

**Comment by mattstam** [comment]
Looking into this though most likely going to separate it out from Calico v3.20.0 update rollout

**Comment by mattstam** [comment]
Should be everywhere by now, can close issue.
