### ISSUE TITLE
Kubelet User Assigned Managed Identity arm template behavior 

### ISSUE THREAD

**Issue by digeler** [Azure/AKS#2488]
am trying to utilize the following :
My own control plane Mi 
My own Kubelet Mi 

Using the cli it works ok :

az aks create   --resource-group testddcluster --name testddcluster --enable-managed-identity --assign-identity "/subscriptions/a9f4e502-9188-4e9c-857f-532dd66f5d0c/resourceGroups/PolyTstUseShellService/providers/Microsoft.ManagedIdentity/userAssignedIdentities/PolyTstUseShellServiceMi" --assign-kubelet-identity "/subscriptions/a9f4e502-9188-4e9c-857f-532dd66f5d0c/resourceGroups/PolyTstUseShellService/providers/Microsoft.ManagedIdentity/userAssignedIdentities/PolyTstUseShellServiceMi"

trying to use the template I always get the kubelet identity with the not the correct one :

"identityProfile": {
    "kubeletidentity": {
      "clientId": "a3272cbe-7d62-4c3e-9af6-585e3f95e186",
      "objectId": "a366e567-6cd5-4e64-a0f8-1ca116ab9aad",
      "resourceId": "/subscriptions/a9f4e502-9188-4e9c-857f-532dd66f5d0c/resourcegroups/MC_PolyEngShellService_PolyEngShellServiceKs_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/PolyEngShellServiceKs-agentpool"
    }
this needs to be : PolyTstUseShellServiceMi instead of  PolyEngShellServiceKs-agentpool 
Instead of the correct one I need :

"identityProfile": {
    "kubeletidentity": {
      "clientId": "5bf30440-9ba3-4e4c-a5d3-7cfa1bda6da1",
      "objectId": "259934ad-6372-43d7-a57a-4b4c2185450a",
      "resourceId": "/subscriptions/a9f4e502-9188-4e9c-857f-532dd66f5d0c/resourceGroups/PolyTstUseShellService/providers/Microsoft.ManagedIdentity/userAssignedIdentities/PolyTstUseShellServiceMi"
    }

template : 
  "properties": {
                "kubernetesVersion": "[parameters('k8sClusterVersion')]",
                "dnsPrefix": "[resourceGroup().name]",
                "enableRBAC": true,               
                "sku": {
                    "name": "Basic",
                    "tier": "Free"
                },
                "agentPoolProfiles": [
                    {
                        "name": "nodepool",
                        "count": 2,
                        "vmSize": "Standard_A4_v2",
                        "osDiskSizeGB": 300,
                        "osDiskType": "Managed",
                        "maxPods": 110,
                        "osType": "Linux",
                        "enableAutoScaling": false,
                        "type": "VirtualMachineScaleSets",
                        "mode": "System",
                        "orchestratorVersion": "[parameters('k8sClusterVersion')]"
                    }
                ],
                 "servicePrincipalProfile": {
                 "clientId": "msi"},

    
                 "identityProfile": {
                    "kubeletidentity": {
                      "resourceId": "[resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', variables('userAssignedManagedIdentityName'))]",
                      "clientId": "f6c2ce3c-e4ed-4cbc-a949-f71c7bcaf7d1",
                      "objectId": "5be006dd-6fc8-4b55-99ab-2538499ba737"
                    }
                }
               
            },

looking at the resource explorer after i did it with the cli it looks the same as above  : 
"properties": {
    "provisioningState": "Creating",
    "kubernetesVersion": "1.20.7",
    "dnsPrefix": "PolyEngShellService",
    "fqdn": "polyengshellservice-b5bcd1da.hcp.eastus.azmk8s.io",
    "agentPoolProfiles": [
      {
        "name": "nodepool",
        "count": 2,
        "vmSize": "Standard_A4_v2",
        "osDiskSizeGB": 300,
        "maxPods": 110,
        "type": "VirtualMachineScaleSets",
        "enableAutoScaling": false,
        "provisioningState": "Failed",
        "orchestratorVersion": "1.20.7",
        "nodeLabels": {},
        "mode": "System",
        "osType": "Linux"
      }
    ],
    "servicePrincipalProfile": {
      "clientId": "msi"
    },
    "nodeResourceGroup": "MC_PolyEngShellService_PolyEngShellServiceKs_eastus",
    "enableRBAC": true,
    "networkProfile": {
      "networkPlugin": "kubenet",
      "loadBalancerSku": "standard",
      "loadBalancerProfile": {
        "managedOutboundIPs": {
          "count": 1
        },
        "effectiveOutboundIPs": [
          {
            "id": "/subscriptions/a9f4e502-9188-4e9c-857f-532dd66f5d0c/resourceGroups/MC_PolyEngShellService_PolyEngShellServiceKs_eastus/providers/Microsoft.Network/publicIPAddresses/6790da0c-c20c-4b45-8642-c27316e2180f"
          }
        ]
      },
      "podCidr": "10.244.0.0/16",
      "serviceCidr": "10.0.0.0/16",
      "dnsServiceIP": "10.0.0.10",
      "dockerBridgeCidr": "172.17.0.1/16",
      "outboundType": "loadBalancer"
    },
    "maxAgentPools": 100,
    "identityProfile": {
      "kubeletidentity": {
        "resourceId": "/subscriptions/a9f4e502-9188-4e9c-857f-532dd66f5d0c/resourcegroups/MC_PolyEngShellService_PolyEngShellServiceKs_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/PolyEngShellServiceKs-agentpool",
        "clientId": "1515f254-cb8e-47a9-94d0-4b6e576618b8",
        "objectId": "6cbb621e-1c55-4b36-881e-17db2ef7d579"
      }
    }
  },
Any help with a sample or understanding why my template is not working as expected appreciated.
is this even supported.

**Comment by jabbera** [comment]
I use kubelet identity via bicep, but I use a different identity then the cluster id. Have you tried allocating a second identity. There may be some arbitrary restriction where they can't be the same?

**Comment by digeler** [comment]
thanks all ,issue is resolved here is the updated template : 
  "resources": [
        {
            "apiVersion": "2021-03-01",
            "type": "Microsoft.ContainerService/managedClusters",
            "name": "[variables('aksClsuterName')]",
            "location": "[variables('location')]",
            "identity": {
                "type": "UserAssigned",
                "userAssignedIdentities": {
                    "[resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', variables('userAssignedManagedIdentityName'))]": {}
                }
            },
            "properties": {
                "kubernetesVersion": "[parameters('k8sClusterVersion')]",
                "dnsPrefix": "[resourceGroup().name]",
                "enableRBAC": true,               
                "sku": {
                    "name": "Basic",
                    "tier": "Free"
                },
                  "identityProfile": {
                    "kubeletidentity": {
                      "resourceId": "[resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', variables('userAssignedManagedIdentityName'))]",
                      "clientId": "[
                                    reference(
                                        resourceId(
                                            'Microsoft.ManagedIdentity/userAssignedIdentities', 
                                            variables('userAssignedManagedIdentityName')), 
                                        '2018-11-30',
                                        'Full')
                                    .properties
                                    .clientId]",
                      "objectId": "[
                                    reference(
                                        resourceId(
                                            'Microsoft.ManagedIdentity/userAssignedIdentities', 
                                            variables('userAssignedManagedIdentityName')), 
                                        '2018-11-30',
                                        'Full')
                                    .properties
                                    .principalId]"
                    }
