### ISSUE TITLE
Dashboard and svc-redirect pods crash after deployment of AKS

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/AKS#249]
Since yesterday I have an issue with deploying AKS clusters. 

NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE
kube-system   heapster-510583900-nlslz                2/2       Running            0          10m
kube-system   kube-dns-v20-2253765213-xmkw8           3/3       Running            0          10m
kube-system   kube-dns-v20-2253765213-ztrcl           3/3       Running            0          10m
kube-system   kube-proxy-nrx4l                        1/1       Running            0          10m
kube-system   kube-svc-redirect-3ghmt                 0/1       CrashLoopBackOff   6          10m
kube-system   kubernetes-dashboard-2898242510-bm4b7   0/1       CrashLoopBackOff   6          10m
kube-system   tunnelfront-1871430006-9r736            1/1       Running            0          10m

I have tried it with serveral versions of Kubernetes, only in West Europe though.

**Comment by bramvdklinkenberg** [comment]
Seems to be working again.

**Comment by e96wic** [comment]
What did you do to fix this? I experience similar issues.

**Comment by bramvdklinkenberg** [comment]
Threw away the cluster and created a new one. But maybe restarting your agents will works as well.
