### ISSUE TITLE
secrets-store-csi-driver add-on default tolerations

### ISSUE THREAD

**Issue by jobbnas** [Azure/AKS#2492]
In my cluster with 3 node pools (one system, two user pools). 
We are currently using Secrets Store CSI Driver add-on ( https://docs.microsoft.com/en-us/azure/aks/csi-storage-drivers) , which is default starting with version 1.21.

Seems like secrets-store-csi-driver daemonsets are not subjected to the same standard add-on :NoExecute op=Exists and :Schedule op=Exists and CriticalAddonsOnly op=Exists tolerations. That means that this add-on won't for instance be scheduled on the system node pool which has the CriticalAddonsOnly taint.

Should Secrets Store CSI Driver as deployed as an add-on -- be more permissive in its tolerations?

- Kubernetes version: 1.21.1

**Comment by andyzhangx** [comment]
the fix is already rolling out, should be ready in next week.

**Comment by andyzhangx** [comment]
the fix should be rolled out on all regions now.
