### ISSUE TITLE
AKS autoscaler issue

### ISSUE THREAD

**Issue by azureatemecloud01** [Azure/AKS#2498]
**What happened**:
- Autoscaler not working ax expected in any of my spot clusters where I have this feature enabled.

**What you expected to happen**:
- AKS Cluster autoscaler should to manage node scale-out based on pods resources requests.
- Including scaling scenario from 0 to n nodes

**How to reproduce it (as minimally and precisely as possible)**:
- Use of spot VMs
- Region : France Central 
- AKS : version 1.18.17

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Versions : 1.18.17

-----------------------------------------------------------------------------------------------------------------------------------

- Size of cluster (how many worker nodes are in the cluster?):
3 nodepools : 

 default_node_pool {
   name                                                   = "default"
   node_count                                        = var.init-system-nodes
   min_count                                          = var.min-system-nodes
   max_count                                          = var.max-system-nodes
   enable_auto_scaling                           = true
   vm_size                                               = var.system-nodes-size
   vnet_subnet_id                                    = azurerm_subnet.internal.id
   type                                                    = "VirtualMachineScaleSets"
   availability_zones                                = var.system_availability_zones
   only_critical_addons_enabled             = true
   os_disk_size_gb                                   = 40
  }

resource "azurerm_kubernetes_cluster_node_pool" "perm-pool" {
  name                                          = "permanent"
  kubernetes_cluster_id               = azurerm_kubernetes_cluster.aks-cluster.id
  vm_size                                      = var.perm-nodes-size
  vnet_subnet_id                          = azurerm_subnet.internal.id
  node_count                               = var.init-perm-nodes #0
  min_count                                 = var.min-perm-nodes #0
  max_count                                = var.max-perm-nodes #3
  os_disk_size_gb                        = 30
  enable_auto_scaling                 = true
  orchestrator_version                 = var.aks_version
  availability_zones                      = var.nodes_availability_zones
  max_pods                                  = "40"
  node_labels = {
    "kubernetes.azure.com/scalesetpriority"     = "on-demand"
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "spot-pool" {
  name                                          = "dynamicpool"
  kubernetes_cluster_id                = azurerm_kubernetes_cluster.aks-cluster.id
  vm_size                                       = var.spot-nodes-size
  vnet_subnet_id                           = azurerm_subnet.internal.id
  node_count                                = var.init-spot-nodes #0
  min_count                                  = var.min-spot-nodes #0
  max_count                                   = var.max-spot-nodes #3
  os_disk_size_gb                           = 30
  enable_auto_scaling                    = true
  orchestrator_version                    = var.aks_version
  availability_zones                         = var.nodes_availability_zones
  priority                                         = "Spot"   #To be managed using variables
  eviction_policy                             = "Deallocate"
  spot_max_price                            = -1 #is possible for testing
  max_pods                                     = "40"
  node_labels = {
    "kubernetes.azure.com/scalesetpriority"     = "spot"
  }
  node_taints = [
    "kubernetes.azure.com/scalesetpriority=spot:NoSchedule"
  ]

-----------------------------------------------------------------------------------------------------------------------------------

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.):

- Logs : 
From my side, on an operational perspective, there’s no relevant log helping us to pinpoint a misconfiguration.  

a) On the configmap : kubectl get configmap -n kube-system cluster-autoscaler-status -o yaml
b) By activating diagnostic setting and then checking Log analytics (which is not an funny part) 

AzureDiagnostics
  | where Category == "cluster-autoscaler"

-----------------------------------------------------------------------------------------------------------------------------------

- Cluster autoscaler profiles : 

a) default setup : 
b) customized setup :

Parameter					     Custom Value	
scan_interval						5s
skip_nodes_with_local_storage		false
balance_similar_node_groups			true
skip_nodes_with_system_pods		false
scale_down_unneeded				1m
scale_down_delay_after_add			1m
scale_down_delay_after_delete		1m

**Comment by marwanad** [comment]
What do the Pending pod events say?
