### ISSUE TITLE
AKS portal expecting networking.k8s.io/v1beta1 instead of v1

### ISSUE THREAD

**Issue by porrascarlos802018** [Azure/AKS#2499]
Portal yaml Editor expecting networking.k8s.io/v1beta1 instead of v1
kindly update once this has been fixed.
254262678

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by chandraneel** [comment]
Ack, we are looking into this and will update soon.
