### ISSUE TITLE
Cannot create aks cluster

### ISSUE THREAD

**Issue by Erikvdv** [Azure/AKS#25]
When following the tutorial it results in:
The VM size of Agent is not allowed in your subscription in location 'westus2'. Agent VM size 'Standard_D2_v2' is available in locations: centraluseuap,eastus,eastus2,eastus2euap,southcentralus,southeastasia,westeurope.

when calling
az aks create --resource-group myResourceGroup --name myK8sCluster --agent-count 1 --generate-ssh-keys

**Comment by dsandersAzure** [comment]
Hi @Erikvdv , Azure Container Services is only currently available in westus2 and one of the UK datacentres, so you'll need to choose a machine size that's available in westus2 - see [Azure resources by region](https://azure.microsoft.com/en-ca/regions/services/) which shows the D series is not available in westus2, although Dv2 is.

Hope this helps,
David

**Comment by dsandersAzure** [comment]
@Erikvdv, Sorry, I just re-read your comment and realize this is the default machine size that says it's unavailable - whoops! I always use ``--agent-vm-size Standard_A2`` because I'm cheap :) Sorry I didn't read your original comment more closely.

**Comment by Erikvdv** [comment]
Ah, I get it, I thought this command was creating a management cluster. btw Standar_A2 is also not available so I chose Standard_B1s
