### ISSUE TITLE
Failed to deploy the nginx-ingress controller with RBAC enabled (ClusterRole not allowed)

### ISSUE THREAD

**Issue by ccojocar** [Azure/AKS#250]
Failed to deploy the [nginx-ingress](https://github.com/kubernetes/charts/tree/master/stable/nginx-ingress) with RBAC enabled on AKS (__Kubernetes Version: 1.9.2__).

`
Error: release nginx-ingress failed: clusterroles.rbac.authorization.k8s.io "nginx-ingress" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["ingresses"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["ingresses"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["ingresses"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["patch"]} PolicyRule{Resources:["ingresses/status"], APIGroups:["extensions"], Verbs:["update"]}] user=&{system:serviceaccount:kube-system:default 0d76ed79-26ac-11e8-b28c-0a58ac1f040f [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]`

Please find attached the cluster info dump: 
[cluster-info-dump.txt](https://github.com/Azure/AKS/files/1819310/cluster-info-dump.txt)

cc @vglafirov @brndkfr @ikoblik

**Comment by andyzhangx** [comment]
@cosmincojocar then you need to set RBAC role and rolebindings before deployment. Could you follow example [here](https://github.com/kubernetes/kubernetes/issues/59543) and provide solution in this issue? I think acs-engine would also has this same issue.

**Comment by cosmincojocar** [comment]
@andyzhangx The Role and RoleBinding definitions are part of the Helm chart. They are created before the deployment. The chat installation works perfectly fine on an unmanaged ACS.

You can reproduce the issue by enabling the RBAC in the `nginx-ingress` chart values before installation.

Please could you investigate it and provide a resolutions?

**Comment by slack** [comment]
AKS does not yet support creating clusters with RBAC enabled. We are actively working on RBAC support for AKS and expect it to become available in the next two months.

**Comment by jnoller** [comment]
RBAC and AAD have been supported for some time on create, closing as stale
