### ISSUE TITLE
Pod autoscaling doesn't make sense if load is not distributed automatically.

### ISSUE THREAD

**Issue by Ayushri-wipro** [Azure/AKS#2505]
The pod scaling happen based on target cpu utilization but it doesn't distribute the load. I tried to create an echo server in the k8s pod which echos back(within a loop) when triggered from client side. This echo happens immediately when triggered but the scaling happens very late which shows that load is not distributed. This doesn't make sense.

**Comment by tomkerkhove** [comment]
Can you add a bit more information about your scenario please?

**Comment by Ayushri-wipro** [comment]
Hi,
In my case, I created a docker image with ncat listen command and a bash file which echo a message in a while loop(for 10k or 1million iteration) and deployed it to AKS. I tried to trigger it from my system using ncat <IP> <Port>.
In my hpa.yaml file I gave the targetcpuutilization param as 30%.

I wanted to test the scaling and load distribution while scaling for this connection. I receive the echo from server immediately after running ncat <IP> <Port> at client side but pod scaling happens very late(after 80 - 90 mins). which also shows that load didn't get distributed accross the newly created the pods.
after sometime I am also getting Ncat Timeout with error "Ncat: assertion failed: count <= INT_MAX QUITTING." This also shows that load is not distributed accross newly created pods and only single pod is handling it so it got timedout and the pod status become CrashLoopBackOff.

Is my understanding correct? How the load distribution is happening while scaling, where can I check in AKS?

**Comment by tomkerkhove** [comment]
Autoscaling is one thing, making your app compatible with it is another.

You'll need to make sure that:
- Your connections are not sticky and don't have long-running connections
- Don't connect directly but use a Kubernetes Service in front (ie `LoadBalancer`)

In terms of:
> I wanted to test the scaling and load distribution while scaling for this connection. I receive the echo from server immediately after running ncat at client side but pod scaling happens very late(after 80 - 90 mins).

Scaling late might be fine because it must mean that it was not using enough CPU to trigger a scaling action, so why add more instances then?

What did you expect to happen? Scale on traffic volume instead?

> I have no experience with `ncat` so can't give good guidance for those apps.

**Comment by Ayushri-wipro** [comment]
I am using Loadbalancer service to create an external IP which I am using at the client side.
Yes, I want to scale it based on traffic received on the already serving pod if its capacity is about to over that the scaling should happen to distribute the load. 
Also How can I check if the load is getting distributed across the newly created pods? and when it scales, if the upcoming new requests are served by the newly created pods?

If the long runnning connection doesn't work then is there a way to notify the client to disconnect and reconnect again?

**Comment by tomkerkhove** [comment]
You won't cut it with an HPA since it doesn't have notion of your traffic volume.

You'll need to find a way to measure the # of requests across pods and scale based on that through Prometheus or some other provider. I think KEDA might be better to help here.

**Comment by tomkerkhove** [comment]
> If the long runnning connection doesn't work then, is there a way to notify the client to disconnect and reconnect again?

No, Kubernetes randomly kills. The only thing you can do is hook in to the SIGTERM signal and close all connections in your app then.

**Comment by Ayushri-wipro** [comment]
I need to try and check KEDA and hook into the SIGTERM signal and close all connections.
Thank you for your suggestions.

I have few more issues:
1. I am not able to stop AKS, tried command az aks stop --name <> --resource-group <>   
I am using it for testing purposes which is costing a lot if the services are created and running. How to stop when not using without deleting.

2. I created pod along with loadbalancer service for it(via one yaml file). if i want to edit it(for exa. to change the container image), I try to edit the same yaml file keeping everything else same. Is this a correct way? Or I shall remove the service part  from yaml file while editing?
Because I always get events like Terminating the container(the one with prev configs) and then backoff issue(while starting it again with new configs). So I had to delete the previous one and create new again everytime.

**Comment by joaguas** [comment]
Besides KEDA, you may also want to consider using AGIC - you expose application gateway metrics to azure's metrics adapter and use it as a source for a custom k8s metric which you can then base your hpa on. (currently beta) https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-autoscale-pods

As for your other issues:
1 - What does cli return on the az aks stop command?

2 - You can either edit the object directly (ie kubectl edit deployment xx) or you can change the .yaml file and apply it again - k8s will only consider changes from .yaml and existing resources - if no changes are made on Service, this object is skipped. If your pod is part of a parent controller (rs, ss, deploy) changes should be made there and which will propagate them to pods (allowing for also other features too). Better to refer to k8s docs for a more comprehensive read: https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/#in-place-updates-of-resources

**Comment by tomkerkhove** [comment]
> Besides KEDA, you may also want to consider using AGIC - you expose application gateway metrics to azure's metrics adapter and use it as a source for a custom k8s metric which you can then base your hpa on. (currently beta) [docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-autoscale-pods](https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-autoscale-pods)

Actually I'd recommend not to do that since Azure Kubernetes Metric Adapter is no longer being maintained in favor of KEDA. You can easily pull the Application Gateway metrics and scale on that with the KEDA Azure Monitor scaler (https://keda.sh/docs/latest/scalers/azure-monitor/)

**Comment by Ayushri-wipro** [comment]
for az aks stop command, I am getting below error-

Unable to load extension 'aks-preview'. Use --debug for more information.
az aks: 'stop' is not in the 'az aks' command group. See 'az aks --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview

**Comment by palma21** [comment]
The IPs are not removed because your services still want/need them, stop will just remove the agent node cost which is the highest. If you delete your service spec and then stop your cluster then you'd remove both.

The CLI error above was because you were missing the CLI extension.

I think Tom already captured most things on the scaling feedback. If you have questions that are tangent or orthogonal to the scaling topic please do open a different issue and we're happy to answer them there,
