### ISSUE TITLE
Update action on kubernetes cluster objects is not allowed through azure portal

### ISSUE THREAD

**Issue by Krupakarreddin** [Azure/AKS#2506]
Update action on kubernetes cluster objects is not allowed through azure portal even after being assigned to Azure RBAC roles and Kubernetes RBAC roles

**Comment by Kaarthis** [comment]
What roles via RBAC has been assigned here - could you elaborate the steps done ?

**Comment by phealy** [comment]
@Krupakarreddin if you're still experiencing this issue, please open a service request. This will allow a support engineer to review your IAM roles and see what's happening.

**Comment by Krupakarreddin** [comment]
resolved
