### ISSUE TITLE
Expose node pool cordonDrainTimeoutInMinutes via the API

### ISSUE THREAD

**Issue by SteveLeach-Keytree** [Azure/AKS#2508]
**What happened**:

I have an AKS 1.18 cluster that I am trying to upgrade to 1.19, with a Deployment of 4 pods that take quite a long time to start up as they load large amounts of data. I have set a pod disruption budget to ensure that 2 nodes are always running. During the upgrade the cluster provisions new nodes, deletes some of the old pods,  but then times out before the new pods have fully started and it can delete the remaining old pods. 

It looks like the cordon/drain timeout is hard-coded to 20 minutes, which in most situation should be ample, but in my case is insufficient. It would be incredibly helpful if this could be made configurable.

We manage the cluster with the terraform azurerm provider, so if it can be configured via the API then they can update the provider so that we can configure it with TF.

**What you expected to happen**:

I can configure the cordon/drain timeout.

**How to reproduce it (as minimally and precisely as possible)**:

Create a deployment with multiple pods that pause for 20+ minutes before reporting "ready" status, and with a pod disruption budget requiring some pods to always be available. Try to upgrade the node pool to a new AKS version.

**Anything else we need to know?**:

See https://github.com/Azure/aks-engine/pull/1276 
and https://github.com/hashicorp/terraform-provider-azurerm/issues/13066

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18 -> 1.19
- Size of cluster (how many worker nodes are in the cluster?) 4
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Java services
- Others:

**Comment by uvw** [comment]
We experienced the same issue just yesterday (2021-11-09) while upgrading from 1.19.3 to 1.20.9. The only difference from the reporter is that we used Azure CLI to upgrade the cluster.

**Comment by paulgmiller** [comment]
So we've been relunctant to make this configurable becuase its really hard to know when your upgrade is stuck on a pdb when the drain timeout is really high. However we're pretty close to shipping eventing on nodes that would give custoemrs clues when an upgrade is stuck on a particular pod. After that we're open to making this configurable. 

Something htat would be helpful for us we probably still want a max you can set it to. What values are you looking to set it to.
