### ISSUE TITLE
Pod is not able to access apiserver when AKS configured with firewall

### ISSUE THREAD

**Issue by mjaow** [Azure/AKS#2510]
I follow the guide https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic to create AKS protected with firewall.  I succeed in all steps, but when I tried to deploy a pod (which will access apiserver to do something) into cluster, it crashed with error following. I've already exposed apiserverPublicIP:443 and *:1194 (udp) and *:9000(tcp). Although I can access apiserver with kubectl, but it still failed to access apiserver from pod

2021-08-20T20:26:34.657Z        ERROR   controller-runtime.manager      Failed to get API Group-Resources       {"error": "Get \"https://10.41.0.1:443/api?timeout=32s\": dial tcp 10.41.0.1:443: i/o timeout"}
sigs.k8s.io/controller-runtime/pkg/manager.New
        /home/vsts/work/1/s/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/manager/manager.go:278
main.main
        /home/vsts/work/1/s/gopath/src/github.com/Azure/ClusterConfigurationAgent/ExtensionOperator/main.go:68
runtime.main
        /home/vsts/work/1/go/src/runtime/proc.go:204
2021-08-20T20:26:34.657Z        ERROR   setup   unable to start manager {"error": "Get \"https://10.41.0.1:443/api?timeout=32s\": dial tcp 10.41.0.1:443: i/o timeout"}
main.main
        /home/vsts/work/1/s/gopath/src/github.com/Azure/ClusterConfigurationAgent/ExtensionOperator/main.go:77
runtime.main
        /home/vsts/work/1/go/src/runtime/proc.go:204

**Comment by joaguas** [comment]
@mjaow with a private clusterthe API's fqdn resolves to that private ip from cluster's subnet meaning that even if you have an UDR with 0.0.0.0/0 set to hop through your FW, this private traffic will still be routed locally as there's the VNET's inherited advertised subnet(s) range(s). 

This traffic should not be hitting your FW unless you're very explicitly routing 10.41.0.1/32 (or some mask smaller than subnet's range) through your FW.



If your nodes are in a 'Ready' status it means nodes can connect to the api (which is what we care about on a L3-4 perspective)

With that said here's what you may want to check:
- If you're doing intra-vnet forward and filtering through a firewall, make sure that you're allowing the whole subnet as source.
- Check for any NSGs blocking traffic (inbound or outbound) between nodes and api (intra vnet - allowed by default)

If your nodes are 'Ready', no NSG rules blocking traffic, traffic not going through FW or not dropped there:
- Check for any calico/azure network policies that may be blocking this.
