### ISSUE TITLE
2 Separate Node Pools. Autoscaling Enabled. But No Scaling Occurs on Specific Node Pool

### ISSUE THREAD

**Issue by usrlocalang** [Azure/AKS#2514]
**AKS FailedScheduling**:

**Would have expected it to Scale up a node in the specific Node Pool that had insufficient CPU. **:

**Create an additional Node Pool with GPU's taint. Create a pod with no taints and give it more memory than what is currently on any of the existing default pool machines. Shouldn't it scale up another node in the default node pool so it can schedule the pod on that node in the default node pool. It should not schedule it on the GPU Node pool due to the taint. **:

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.20.7
- Size of cluster (how many worker nodes are in the cluster?): 5
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.). RAY ML Application
- Others: Autoscaling has been enabled on both the nodepools. Default and GPU Node Pool. 
Describe Pod msg: "0/5 nodes are available: 2 Insufficient cpu, 3 node(s) had taint {sku: gpu}, that the pod didn't tolerate."

**Comment by joaguas** [comment]
other than what @marwanad already mentioned (make sure pod is not requesting more cpu time than what the node can provide) you can also check the cluster autoscaler events or issues: `kubectl -n kube-system describe cm cluster-autoscaler-status` . If you enable diagnostic settings you can also logs from the autoscaler pod itself:
`AzureDiagnostics 
| where Category == "cluster-autoscaler"
| where ResourceId == "yourAksClusterResourceIdHere" 
| project TimeGenerated, log_s`
