### ISSUE TITLE
Update service principal skipping passwordCredentials[0].endDate (legacy AAD)

### ISSUE THREAD

**Issue by dev-samples** [Azure/AKS#2519]
I have some 1.18 AKS clusters running "legacy" AD (meaning client and server AAD applications and Service principals).

I have followed the guides here:

https://docs.microsoft.com/en-us/azure/aks/update-credentials#reset-the-existing-service-principal-credential
https://docs.microsoft.com/en-us/azure/aks/update-credentials#update-aks-cluster-with-new-service-principal-credentials
https://docs.microsoft.com/en-us/azure/aks/update-credentials#update-aks-cluster-with-new-aad-application-credentials

To reset passwords/renew using below commands:

```
SP_ID=$(az aks show --resource-group $CLUSTER --name $CLUSTER --query servicePrincipalProfile.clientId -o tsv)
SP_SECRET=$(az ad sp credential reset --name "$SP_ID" --query password -o tsv)

az aks update-credentials \
    --resource-group $CLUSTER \
    --name $CLUSTER \
    --reset-service-principal \
    --service-principal "$SP_ID" \
    --client-secret "$SP_SECRET"

CLIENT_APP_ID=$(az aks show --resource-group $CLUSTER --name $CLUSTER --query aadProfile | jq -r .clientAppId)
SERVER_APP_ID=$(az aks show --resource-group $CLUSTER --name $CLUSTER --query aadProfile | jq -r .serverAppId)
SERVER_APP_SECRET=$(az ad sp credential reset --name "$SERVER_APP_ID" --query password -o tsv)

az aks update-credentials \
    --resource-group $CLUSTER \
    --name $CLUSTER \
    --reset-aad \
    --aad-server-app-id $SERVER_APP_ID \
    --aad-server-app-secret $SERVER_APP_SECRET \
    --aad-client-app-id $CLIENT_APP_ID
```

But when I try to verify the new **endDates** I still see the old ones under **passwordCredentials**:

```
$ az ad sp show --id $CLIENT_APP_ID | jq -r '.passwordCredentials[0].endDate'
2021-10-09T12:01:04.127509+00:00
$ az ad sp credential list --id $CLIENT_APP_ID | jq -r '.[0].endDate'
2022-08-26T13:19:36.903564+00:00

$ az ad sp show --id $SERVER_APP_ID | jq -r '.passwordCredentials[0].endDate'
2021-09-29T11:42:36.771052+00:00
az ad sp credential list --id $SERVER_APP_ID | jq -r '.[0].endDate'
2022-08-27T08:11:13.143132+00:00

$ az ad sp show --id $SP_CLIENT_ID | jq -r '.passwordCredentials[0].endDate'
2021-10-09T12:01:04.127509+00:00
$ az ad sp credential list --id $SP_CLIENT_ID | jq -r '.[0].endDate'
2022-08-26T13:19:36.903564+00:00
```

More info:

```
$ az ad sp show --id $SERVER_APP_ID | jq
{
....
  "odata.type": "Microsoft.DirectoryServices.ServicePrincipal",
  "passwordCredentials": [
    {
      "additionalProperties": null,
      "customKeyIdentifier": null,
      "endDate": "2021-09-29T11:42:36.771052+00:00",
      "keyId": "xxx",
      "startDate": "2020-09-29T11:42:36.998641+00:00",
      "value": null
    }
  ],
...
}

```

How do I renew those dates?

**Comment by miwithro** [comment]
Hello @dev-samples a few things aks first.

1. AKS 1.18 is no longer in support, are you working on an upgrade?
2. Legacy AAD is being deprecated, why not use Managed AAD?
3. Service Principals are being deprecated, why not use Managed Identities?

**Comment by dev-samples** [comment]
Yes moving to managed ID but not for this cluster since managed ID requires a re-deploy which is not an option short term.

**Comment by miwithro** [comment]
@dev-samples.  No you can update an existing cluster to Managed Identity without a redeploy.

https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#update-an-aks-cluster-to-managed-identities

**Comment by dev-samples** [comment]
Interesting I will take a look at that. Was told MI required a redeploy.

Also I am still curious on how to renew/update the enddate in the passwordCredentials section below:


{
....
  "odata.type": "Microsoft.DirectoryServices.ServicePrincipal",
  "passwordCredentials": [
    {
      "additionalProperties": null,
      "customKeyIdentifier": null,
      "endDate": "2021-09-29T11:42:36.771052+00:00",
      "keyId": "xxx",
      "startDate": "2020-09-29T11:42:36.998641+00:00",
      "value": null
    }
  ],

**Comment by miwithro** [comment]
@dev-samples we added the migration capability early summer time.
