### ISSUE TITLE
Can I use AKS with a docker image registry other then Azure Container Registry (ACR)?

### ISSUE THREAD

**Issue by deejbee** [Azure/AKS#252]
Is this possible?

**Comment by neilpeterson** [comment]
Yes, totally possible. The sample in this doc uses Docker Hub. Any others should work without issue. 

https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough

If you are experiencing an issue, please provide details and we can attempt to help.

**Comment by andyzhangx** [comment]
@deejbee if you are pulling images from **private** registry from docker hub, you need to set credentials at first, here is an example: [Pull an Image from a Private Registry](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry)

**Comment by ultimateboy** [comment]
Absolutely. Closing this issue as the provided links describe how to accomplish this.

**Comment by andyzhangx** [comment]
@jalberto could you provide a helm example? in a helm chart, if it's going to pull an image from private registry, it should be set credential somewhere by parameters.

**Comment by jalberto** [comment]
@andyzhangx  I am thinking in "private" helm chart, deployed to more than one name space or cluster.

To populate each name space in each cluster with the correct secrets and keep that in-sync is not ideal.

The only option seems to be to use ACR with correct SP access, but this will also be problematic with ACR in different subscription

**Comment by rodriguezsergio** [comment]
Is this possible yet? I've been looking everywhere for a straight forward solution and thought I had something with the following but it does not work.

```
# truncated terraform
resource "azurerm_resource_group" "k8s-astra" {
[...]
}

resource "azurerm_kubernetes_cluster" "k8s" {
[...]
}

resource "azurerm_kubernetes_cluster_node_pool" "k8s-worker" {
  kubernetes_cluster_id = azurerm_kubernetes_cluster.k8s.id
  [...]
}

resource "azurerm_virtual_machine_scale_set_extension" "example" {
  [...]

  settings = jsonencode({
    "commandToExecute" = <<-EOT
   heredoc contents
EOT
  })
}
```
I then went and did the following:

```sh
az vmss scale --name $NAME  --new-capacity 0 --resource-group $R_GROUP_NAME --no-wait --subscription $SUB_ID
az vmss scale --name $NAME  --new-capacity 3 --resource-group $R_GROUP_NAME --no-wait --subscription $SUB_ID
```

The new nodes spun up, but did *NOT* join the kubernetes cluster. So clearly I messed up some AKS cloud-init joining functionality.

**Comment by ultimateboy** [comment]
@rodriguezsergio it has always been possible to use registries beyond ACR with an AKS cluster if access and credentials are handled. I do not see anything in your comment about a registry. Please open a new issue as this issue does not seem related.

**Comment by rodriguezsergio** [comment]
https://github.com/Azure/AKS/issues/1748 opened
