### ISSUE TITLE
K8s 1.21 ISS value is a double-quoted twice string

### ISSUE THREAD

**Issue by ToxicWar** [Azure/AKS#2523]
**What happened**:

With AKS cluster upgrade to k8s 1.21+ I found new behavior for service account authentication. Due to this change, the issuer is different from the **_kubernetes/serviceaccount_** issuer that default tokens are created with, so validation with Kubenetes’ default issuer will fail. 

So, integration with Vault (via k8s auth plugin) now returns the `claim "iss" is invalid` error.

I followed the latest documentation to add the `issuer` parameter like described here:
https://www.vaultproject.io/docs/platform/k8s/csi#setting-issuer-for-kubernetes-authentication

But I found that the `iss` parameter is double-quoted twice string - `"\"aks-cluster-edf1.hcp.southeastasia.azmk8s.io\""`

```
{
	"aud": ["\"aks-cluster-edf1.hcp.southeastasia.azmk8s.io\""],
	"exp": 1630403475,
	"iat": 1630399875,
	"iss": "\"aks-cluster-edf1.hcp.southeastasia.azmk8s.io\"",
	"kubernetes.io": {
		"namespace": "default",
		"serviceaccount": {
			"name": "default",
			"uid": "b4e68f25-74be-430f-b04c-e39052c3a87f"
		}
	},
	"nbf": 1630399875,
	"sub": "system:serviceaccount:default:default"
}
```

So, to fix the Vault k8s auth plugin I need to pass the same error in the `issuer` parameter on the configuration step.

**What you expected to happen**:

I expect that the `iss` parameter will be a correct string - `aks-cluster-edf1.hcp.southeastasia.azmk8s.io`

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl proxy --port=8007 &
curl --silent http://127.0.0.1:8007/api/v1/namespaces/default/serviceaccounts/default/token \
  -H "Content-Type: application/json" \
  -X POST \
  -d '{"apiVersion": "authentication.k8s.io/v1", "kind": "TokenRequest"}' \
  | jq -r '.status.token' \
  | cut -d. -f2 \
  | base64 -d
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.21.2

**Comment by ToxicWar** [comment]
AKS cluster k8s v1.21.2 created from scratch
```
{
	"aud": ["https://aks-test-996e85a3.hcp.southeastasia.azmk8s.io"],
	"exp": 1630661174,
	"iat": 1630657574,
	"iss": "https://aks-test-996e85a3.hcp.southeastasia.azmk8s.io",
	"kubernetes.io": {
		"namespace": "default",
		"serviceaccount": {
			"name": "default",
			"uid": "6b26ac3e-b705-4aa3-9409-4c428ba41b83"
		}
	},
	"nbf": 1630657574,
	"sub": "system:serviceaccount:default:default"
}
```

AKS cluster k8s v1.18.14

```
{
	"aud": ["\"aks-test-7a908409.hcp.southeastasia.azmk8s.io\""],
	"exp": 1630661709,
	"iat": 1630658109,
	"iss": "\"aks-test-7a908409.hcp.southeastasia.azmk8s.io\"",
	"kubernetes.io": {
		"namespace": "default",
		"serviceaccount": {
			"name": "default",
			"uid": "9da363a9-0343-4895-9e26-0c2bd3056f1c"
		}
	},
	"nbf": 1630658109,
	"sub": "system:serviceaccount:default:default"
}
```

**Comment by hieumoscow** [comment]
Thanks @ToxicWar for the sync call, this is related to the Vault issue https://github.com/banzaicloud/bank-vaults/issues/1346. Current workaround is to put `disable_iss_validation: true`.
I am expecting that the next version of the vault plugin would be able to adapt to the new OIDC https value in **iss** field.

**Comment by bcho** [comment]
Hi @hieumoscow one thing to confirm, does `disable_iss_validation: false` work for the 1.21 cluster?

**Comment by hieumoscow** [comment]
Yes @bcho it does. We can close this issue new until the Vault team address this in their plugin. @ToxicWar feel free to open it back again if there are further issues
