### ISSUE TITLE
Custom Policy support for AKS

### ISSUE THREAD

**Issue by miwithro** [Azure/AKS#2525]
Add Azure Policy Custom Policy support (REGO) to AKS.

**Comment by palma21** [comment]
https://azure.microsoft.com/en-us/updates/custom-aks-policy-support-now-public-preview/

**Comment by Krupakarreddin** [comment]
@miwithro  Currently i was unable to create custom azure policy for AKS which require access to state data.For example to create a policy for uniqueingresshostnames in AKS cluster ,it is impossible to know if an ingress's hostname is unique among all ingresses unless a rule has access to all other ingresses. To make such rules possible, we need to enable syncing of data into OPA. Kubernetes data can be replicated into OPA via the sync config resource.
One more example would be uniqueservicesselector(to enforce a requirement where services must have globally unique selectors.)
 Currently config cant be edited for azure policy addon

**Comment by miwithro** [comment]
@Krupakarreddin we are working on external data source as well which would answer your state question.  Adding in @nehakulkarni123 who can provide some ETA's potentially.

**Comment by edkirillov** [comment]
Hi, is there any timeline for making the custom policy feature GA?
