### ISSUE TITLE
Please support Windows Server 2022 in AKS

### ISSUE THREAD

**Issue by peter-bertok** [Azure/AKS#2528]
Windows Server 2022 RTM is now available, and most of its new features are focused on containerisation.

In particular, the ability to use gMSA without having to domain-join the hosts is something that many organisations have been waiting for to enable migrations of on-prem legacy apps to containers.

Ideally, instead of simply "Windows", AKS should provide multiple image options, including "2019", "2022", "2022 Core", etc...

E.g.: It should be possible to deploy a 2022 Core smalldisk image with ephemeral storage to reduce the costs of Kubernetes clusters. For orgs using VM Reservations and AHUB, the cost of storage can dominate the infrastructure cost, and this is one way of bringing it down even further...

**Comment by justindavies** [comment]
Hi Peter, I'm the PM for Windows on AKS - we are working on supporting 2022, and gMSAv2 will be in public preview shortly.  Please get in touch if you want to be included on the current private preview for gMSA

**Comment by peter-bertok** [comment]
> Please get in touch if you want to be included on the current private preview for gMSA

@justindavies What's the best way to do that?

**Comment by Confusedfish** [comment]
Is there any update on the progress to spring server 2022? I cannot see anything on the roadmap.

**Comment by allyford** [comment]
We announced WS2022 public preview at Build!

https://docs.microsoft.com/en-us/azure/aks/learn/quick-windows-container-deploy-cli#add-a-windows-server-2022-node-pool-preview

**Comment by allyford** [comment]
Closing this duplicated issue - see Windows Server 2022 support #2115
