### ISSUE TITLE
Zone balancing lost during cluster update

### ISSUE THREAD

**Issue by pierluigilenoci** [Azure/AKS#2529]
**What happened**:

Premise: we have several node-pools with taint so that the pods are separated on the nodes according to internal criteria (ex: infrastructure pods only on system nodes, production pods on production node pools separate from development ones, etc). Node polls have a minimum size of 3 nodes, one for each zone, some applications are configured to always be present in each zone because they have a disc (PVC) attached. The disc is obviously linked/blocked to the zone. 

During the cluster upgrade, a node pool with only three nodes was upgraded by not maintaining at least one node in all zones and therefore some applications were unavailable in some zones for several minutes. 

**What you expected to happen**:

I expect that during the update if the nodes are distributed over several zones and the minimum number of nodes is sufficient to cover all the zones, the cluster will never leave a zone without at least one node.

**How to reproduce it (as minimally and precisely as possible)**:

Create a node pool on three zones with three nodes minimum, install an application (eg a Redis Cluster) on the three zones and update the cluster. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```shell
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"bd9d9ae2719e67a582f48c5dc2f81e87fe1deb8a", GitTreeState:"clean", BuildDate:"2021-08-16T22:02:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?): 19 (with autoscaling)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): basically everything... node microservices, Java app, ML, caching databases... 
- Others:

**Comment by justindavies** [comment]
Hi there, have you made any changes to the surge configuration for upgrades?  @paulgmiller for reference

**Comment by pierluigilenoci** [comment]
@justindavies we haven't changed anything to the surge configuration from the default configuration. 

The cluster updates one node at a time, the problem is that it does not properly choose the AZ of the nodes it creates in order to keep the node pools balanced in the AZ. 

Here is an example of what can happen: 

1) Initial situation: 3 nodes in 3 different AZ (west-europe 1, 2 and 3), all works fine.
2) Update starts: a node in zone 1 is created and a node in zone 2 is drained (So 2 nodes in AZ 1, 1 node in AZ 3). Pods that have a PVC in zone 2 cannot be scheduled because they do not meet all conditions. This is already bad.
3) Worst case scenario after point 2: if a node in zone 2 is created and the node in zone 3 is drained (So 2 nodes in AZ1, 1 node in AZ2). At this exact moment, the "zone 2" pods have not yet started and the pods of "zone 3" are terminating. So "zone 2" and "zone 3" pods with a PVC are all "not ready".

**Comment by pierluigilenoci** [comment]
@msftbot ❤️ 

![giphy2](https://user-images.githubusercontent.com/36044817/132512333-799b5792-6562-46e3-a755-76fbb17476df.gif)

**Comment by pierluigilenoci** [comment]
@justindavies @paulgmiller any feedback?

**Comment by paulgmiller** [comment]
Have you considered surging in 3 nodes with max surge? That's not garunteed to be balanced but is much more likely.

You can also set a poddisruptionbudget to make sure not more than one one replica is taken down at once.

**Comment by pierluigilenoci** [comment]
@paulgmiller as soon as I can I try to do it and see what happens.

**Comment by pierluigilenoci** [comment]
@phealy thanks a lot.

I will try to test the proposed solution.
