### ISSUE TITLE
GPU Multi Instance Support

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#2539]
Support for GPU partitioning

**Comment by heoelri** [comment]
@palma21 / @justindavies is there any documentation available for this preview?

**Comment by porrascarlos802018** [comment]
@palma21  Could this feature enable users of HPA to use these metrics and scale number of replicas depending on utilization of the GPU?

**Comment by justindavies** [comment]
@porrascarlos802018 The feature is for partitioning the GPU in the A100 instance rather than the ability to use the metrics for scaling.  You would be able to run a Daemonset on the nodes to run nvidia-smi etc to feed the utilisation into Keda etc and make scaling decisions based on that

**Comment by justindavies** [comment]
@heoelri I pushed the documentation earlier today and it should be on the main Azure documentation site later today

**Comment by porrascarlos802018** [comment]
ack thank you!

**Comment by alexeldeib** [comment]
@justindavies shall we close this out?

**Comment by justindavies** [comment]
We need to keep it open until GA to track the public roadmap

**Comment by justindavies** [comment]
The feature is now GA
