### ISSUE TITLE
Unable to create PIM assignments for AKS Azure Roles scoped to namespaces for AD groups

### ISSUE THREAD

**Issue by SnoWolfT** [Azure/AKS#2542]
**What happened**:
We started using the normal PIM approach and onboarded our resources for Azure Resources PIM. The issue is, We cant use the Azure AD Roles for Namespaces Binding using PIM as they won’t show up.

Can you help us out with this ?

MS Document:
https://docs.microsoft.com/en-us/azure/aks/managed-aad#configure-just-in-time-cluster-access-with-azure-ad-and-aks 

**What you expected to happen**:
Need to use the Azure AD Roles for Namespaces Binding using PIM

**How to reproduce it (as minimally and precisely as possible)**:
As MS Document, this feature seems not be supported yet. There is no place to select the Namespaces. The permission is granted for the whole AKS cluster.
https://docs.microsoft.com/en-us/azure/aks/managed-aad#configure-just-in-time-cluster-access-with-azure-ad-and-aks 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by miwithro** [comment]
Hello,
  The process to segment at the namespace level is to RBAC enable your cluster.  Then set a group membership at the namespace level.   Associate that group with PIM.

https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac

To help out I will add this guidance to the above documentation.
