### ISSUE TITLE
add support for maximum-dead-containers-per-container

### ISSUE THREAD

**Issue by smartpcr** [Azure/AKS#2544]
**What happened**:
dead docker images are not immediately cleared

**What you expected to happen**:
have a way to clear dead images from disk using `maximum-dead-containers-per-container`

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.6
- Size of cluster (how many worker nodes are in the cluster?) 5

**Comment by allyford** [comment]
maximum-dead-containers-per-container is a deprecated parameter from [kubernetes](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/). Closing this issue as we will not be adding this parameter. Kubernetes recommends using --eviction-hard or --eviction-soft instead. Please update the issue if you'd like our team to consider these eviction parameters instead.

![image](https://github.com/user-attachments/assets/e73ddbe0-934a-4564-b6b0-86406c3ce802)
