### ISSUE TITLE
Disabling Local Admin Account after the fact doesn't remove the Admin access

### ISSUE THREAD

**Issue by djsly** [Azure/AKS#2545]
**What happened**:
We have a cluster with Admin Local Account enabled, we can fetch the Kubeconfig Admin file and issue command ClusterAdmin since there static Certs is not revoked and the ClusterRoileBinding for this local account is still present. 

**What you expected to happen**:
When you disable the Local Admin Account, the access of previously fetch admin kubeconfig should be revoked.

**How to reproduce it (as minimally and precisely as possible)**:
Create an AKS cluster with local Admin account enabled, fetch the kubeconfig admin and disable the local admin account using the CLI.
Try to make 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- 1.20

**Comment by miwithro** [comment]
@djsly we are working on this one already.  @norshtein for awareness.  This should be mitigated this month.

**Comment by djsly** [comment]
Thanks @miwithro , do you know what the solution will involve ? touching the Binding only or also looking at disabling the Client Certs ?

**Comment by miwithro** [comment]
removing the client certs and replacing them with tokens.

**Comment by djsly** [comment]
@justindavies / @miwithro  wouldn't it be best to keep the issue open till it's available ? or else, how to dp we track the progress ? Thanks

**Comment by miwithro** [comment]
Yes, can you re-open it?

**Comment by djsly** [comment]
@miwithro i think you will need to remove the label "answer-provided"

**Comment by djsly** [comment]
I tried reopening but I couldn't

**Comment by miwithro** [comment]
Got it.  I removed the answer-provided tag.

**Comment by djsly** [comment]
@miwithro now that Disable Local admin account is GA, was this feature in for GA or it will come later ?

**Comment by miwithro** [comment]
Hey @djsly for clusters that had local accounts and then removed local accounts, the certs are still valid until the CA is recycled to revoke those certificates.
