### ISSUE TITLE
Basic load balancers are not supported with multiple node pools

### ISSUE THREAD

**Issue by Alexey-Tsarev** [Azure/AKS#2546]
Hi, I faced with the
> Basic load balancers are not supported with multiple node pools
error message during last days.

Let me explain, I deployed an AKS cluster with the "Basic" load balancer and TWO node pools using Terraform. But I was not able to deploy it because of initial error (I tried DAYS in a row).
But today, my colleague was able and did it. I was surprised very much!
Let me demo this:
1)
<img width="821" alt="Screenshot at Sep 14 19-02-03" src="https://user-images.githubusercontent.com/5929124/133282941-3212309b-78e7-4634-83a7-8a9f5a6068f8.png">
2)
<img width="874" alt="Screenshot at Sep 14 19-05-10" src="https://user-images.githubusercontent.com/5929124/133283202-29c83166-ff91-4b1b-a828-7d055c959b58.png">

But yesterday (and days ago) I had another situation (I was not able to add a new node pool):
3)
<img width="802" alt="Screenshot at Sep 14 19-27-45" src="https://user-images.githubusercontent.com/5929124/133287138-af11b230-f3d3-41b2-a416-8e214901e85e.png">

So, can you please explain, is an AKS configuration with 2 node pools and Basic load-balancer possible or not?

I see the options:
1) Yes (1)(2)
2) No, currently it's not possible (3). Because doc
https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#limitations
> The AKS cluster must use the Standard SKU load balancer to use multiple node pools, the feature is not supported with Basic SKU load balancers.
3) "Sometimes" it's possible and not, because the following bug is still in the progress (1)(2)(3)
https://github.com/Azure/AKS/blob/master/CHANGELOG.md (Release 2020-07-27)
> We've added additional validations to prevent the creation of multiple node pool clusters with Basic Load Balancer which isn't supported.

Please explain which configuration is correct?

**Comment by denniszielke** [comment]
It is not supported and Basic LB + NodePools should not be deployable (it actually has a couple of issues).
Can you share your terraform template?
