### ISSUE TITLE
Unable to uninstall Azure PSP, argument no longer available in az-cli

### ISSUE THREAD

**Issue by brconnell4** [Azure/AKS#2550]
**What happened**:
When attempting to uninstall Azure Pod Security Policies to utilize Azure Policies instead, the argument for `--enable-pod-security-policy` is no longer available on az cli 2.28.0. I am unsure when the argument was removed, but this prevents end users from uninstalling the preview for Azure Pod Security Policies. When attempting to enable Policies for the cluster resource in Azure the following error is received:

"PodSecurityPolicy is not supported with azure policy addon. Please see https://aka.ms/aks/azpodpolicy for how to enable this feature."

Recommended command to run from Azure documentation via https://docs.microsoft.com/en-us/azure/aks/use-azure-policy:

`az aks update \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --enable-pod-security-policy`

**What you expected to happen**:

Preferred option: 
When enabling Azure Policy from the web ui, an indication that Azure PSP add-on will be removed should be done. After accepting it should uninstall the Add-on and enable Azure Policy

Or

Deprecating arguments from the cli is fine, but in place of this the arguments should be moved to a different resource to call on with defined parameters.

**How to reproduce it (as minimally and precisely as possible)**:

Create a Kubernetes Resource in Azure
You will need to enable Azure Pod Security Policies add-on from preview. 
Use the latest version of az-cli 
perform command to uninstall the add-on
Argument is not found, verify valid arguments with  `az aks update --help`

**Anything else we need to know?**:

How to fix: 

The only way I was able to fix this without deleting the cluster resource was by spinning up a clean ubuntu container, use the pip installer to install a version of the cli that the argument was available on and then run the commands to unintstall the add-on. Spinning up a container is most likely not needed, but I ran into some directory conflicts when dealing with it locally and didn't want to deal with the nuances.

Specific steps to fix: 
Create an ubuntu container in docker (I am sure other images would work just fine) 
run `pip3 install azure-cli==2.0.48`
Run the following command: `az aks update --subscription mySubscription --resource-group myRG --name myResource --disable-pod-security-policy`

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.5

**Comment by miwithro** [comment]
@brconnell4 --disable-pod-security-policy exists in the aks-preview extension not in the az cli.  

az extension add --name aks-preview.

From here you can run az aks update --disable-pod-security-policy and then update your cluster to add azure policy.
