### ISSUE TITLE
Recreation of failed cluster nodes

### ISSUE THREAD

**Issue by lmarszal** [Azure/AKS#256]
I've got AKS with 3 nodes. Today I've noticed that one node is down (it was operating previously):
```
λ  kubectl get no
NAME                  STATUS     ROLES     AGE       VERSION
aks-nodepool1-XXX-0   Ready      agent     1d        v1.9.2
aks-nodepool1-XXX-1   NotReady   agent     1d        v1.9.2
aks-nodepool1-XXX-3   Ready      agent     1d        v1.9.2
```
This was an obvious problem, as some of my pods had no resources to operate and were in `Pending` state.
There was nothing meaningful in `kubectl describe no aks-nodepool1-XXX-1` though: [kubectl describe.txt](https://github.com/Azure/AKS/files/1824415/kubectl.describe.txt)

What I did was:
1. Delete `aks-nodepool1-XXX-1` machine manually from azure portal (machine, disk, nic)
1. Issue a command to scale cluster back to 3 machines: `λ  az aks scale -n clustername -g cluster_resource_group --node-count 3`

Just wondering: should cluster detect such situations automatically and recreate failed nodes, or should I automate this in some way on my own?

**Comment by seniorquico** [comment]
We also had a node fail just a few days ago in one of our AKS clusters, and it never recovered from the NotReady status. We decided to leave the system as-is and open an Azure technical support request. We're hoping to get someone to provide this exact type of guidance on how best to proceed. I'll share what I can when I hear back.

**Comment by marcusschiesser** [comment]
We have the same problem -  nodes are all in _NotReady_ state - scaling up/down doesn't work - Nodes are running on AKS 1.9.2  - Azure support isn't helpful

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
