### ISSUE TITLE
Trusted Launch Support in AKS

### ISSUE THREAD

**Issue by miwithro** [Azure/AKS#2562]
[AKS Trusted Launch Public Preview](https://learn.microsoft.com/en-us/azure/aks/use-trusted-launch)  GA is estimated for end of Aug 2024.

**Comment by miwithro** [comment]
https://learn.microsoft.com/en-us/azure/aks/use-trusted-launch

**Comment by allyford** [comment]
New issue for tracking Trusted Launch for Windows node pools. See #4369

**Comment by allyford** [comment]
This feature is targeting GA this month!

**Comment by allyford** [comment]
Trusted Launch is now generally available. See [AKS documentation](https://learn.microsoft.com/azure/aks/use-trusted-launch) for more information.
