### ISSUE TITLE
AKS default for --node-osdisk-type parameter

### ISSUE THREAD

**Issue by normander** [Azure/AKS#2565]
I've created a lot of AKS clusters in many different regions and I saw that this parameter has a different default for westeurope("Managed") , Azure china("Ephemeral").

Can someone help me with investigating why?

**Comment by miwithro** [comment]
@andyzhangx @feiskyer have we set the default on sovereign clouds to match Public?

**Comment by andyzhangx** [comment]
@alexeldeib is the feature owner, would you comment on this issue? Thanks.
