### ISSUE TITLE
Azure RBAC for Kubernetes Authorization does not expire when user loses authorization in Azure RBAC

### ISSUE THREAD

**Issue by y3sy** [Azure/AKS#2566]
**What happened**:
kubectl was able to read AKS objects after RBAC role assignment was removed. This continued for more than 1,5 hours after which I stopped monitoring.

**What you expected to happen**:
kubectl should be denied access to AKS cluster quickly after RBAC role assignment is removed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create AAD group with the command `az ad group create --display-name myAKSAdminGroup --mail-nickname myAKSAdminGroup`
2. Add current user to AAD group.
2. Create AKS cluster with the command `az aks create -g MyResourceGroup -n MyManagedCluster --enable-aad --enable-azure-rbac`
3. Assign role `Azure Kubernetes Service RBAC Reader` to the AAD group with the scope of the newly created AKS cluster.
4. Get credentials with `az aks get-credentials -g MyResourceGroup -n MyManagedCluster`
5. Remove role assignment `Azure Kubernetes Service RBAC Reader` from the AAD user or group.
6. Observe `kubectl get nodes` returns a list of nodes.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"0b17c6315e806a66d507e77760a5d60ab5cccfd8", GitTreeState:"clean", BuildDate:"2021-08-30T01:42:22Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}`
```
- Size of cluster (how many worker nodes are in the cluster?)
3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
HTTP microservices, Django web application, NGINX Ingress Controller
- Others:

**Comment by miwithro** [comment]
@y3sy the user credential would be active for up to 60 minutes but that is dependent on the AAD configuration.  That is the default, but can be tuned to time out the user on a more frequent basis.
