### ISSUE TITLE
max pods limit minum to 4

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Azure/AKS#2572]
## use case

1. i wan run gameservers on nodes
2. i know limit to pods per node is 4 for 2 core VM
3. i want to set that limit
Actual: azure minimum is 10
Expected: reduce min limit of max pods to 4

### google

use gke

### big vms

6 core VM so can set big limit like 12 - to pricey and not always available globally on scale

### static policy

does not handles well less than core game

### limits

too quantized, lead game lags (or there is able to set CPU limits so quants of time are spread in second). other form of scheduling?

### no limits

slow games because of overallocation

## references

https://agones.slack.com/archives/C9DGM5DS8/p1632905727156800?thread_ts=1630296837.026000&cid=C9DGM5DS8
```
│ Error: creating/updating Managed Kubernetes Cluster Node Pool "win" (Resource Group "aom-testdevstaging-eu-west-1"): containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InsufficientMaxPods" Message="The AgentPoolProfile 'win' has an invalid maxPods, the maxPods(4) should be larger than 10. Please refer to aka.ms/aks-min-max-pod for more detail." Target="agentPoolProfile.kubernetesConfig.kubeletConfig.maxPods"
```

https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#maximum-pods-per-node

**Comment by justindavies** [comment]
We set the minimum max-pods to be 10 to be able to accomodate system pods: https://docs.microsoft.com/en-gb/azure/aks/configure-azure-cni#maximum-pods-per-node.  Is there a reason you cannot accomplish the same thing with cpu requests on your workloads? In this case, setting the cpu request to 500m ?

**Comment by dzmitry-lahoda** [comment]
windows does not hosts system pods afaik. so for windows it can be 4 or 8, may be. hm, may be. but for sure not my limits. 
> The default quota period is 100ms. The minimum resolution of CPU quota is 1ms
limits will lags to games.

need to read more about requests.

**Comment by dzmitry-lahoda** [comment]
probably this would be similar to `requests` on cpu. not sure how far different it will be.

**Comment by phealy** [comment]
@dzmitry-lahoda - a recommended pattern would be to properly set requests and limits on your pods so that they schedule appropriately, rather than cutting down the number of max pods, as system pods may be scheduled on your nodes. As as example, if you want each game server to have 1 CPU dedicated, set requests: cpu: 1 and Kubernetes will make sure that workload is scheduled appropriately.

Please keep in mind that there is some overhead for OS and K8s daemons, so you can't schedule two pods with requests: cpu: 2 onto a 4 CPU node.

**Comment by dzmitry-lahoda** [comment]
>  limits on your pods 

it is not option for game servers, limits is not option because of how k8s quietuses time over the limit
