### ISSUE TITLE
AKS managed identities have insufficient roles when enabling addons with a Contributor service principal

### ISSUE THREAD

**Issue by oliviergaumond** [Azure/AKS#2573]
## What happened
Creating an AKS cluster and enabling addons (AGIC ingress or OMS Agent) with a user with a contributor role leads to managed identities with incomplete role assignments. The managed identities are created but insufficient roles are assigned, leading to errors later when trying to use those resources.

Depending on the exact steps used to create the dependent resources the outcome can differ (see repo steps).  When all dependent resources are created in the AKS managed resource group, permissions are fine. If the dependent resources are pre-existing in a separate resource group, permissions are missing.

## What you expected to happen
Without the permission to assign roles we cannot expect Azure to create the proper permissions. So I don't think this is a bug in itself. However, I think the tooling should output some warnings that the full configuration was not applied.

## How to reproduce it (as minimally and precisely as possible)
Here are different scenarios with different outcome

### AKS + App Gateway greenfield (working scenario)
**Important:** The steps need to be run with a user/service principal with Contributor role on the subscription without Microsoft.Authorization/roleAssignments/write permission

Follow the steps in [this tutorial](https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-new) to create an AKS cluster integrated with App Gateway. 

The App-Gateway is created by the `az aks create` command and will be created under the AKS managed resource group. A managed identity `ingressapplicationgateway-mycluster` is created with Contributor role on the managed resource group.

Everything is good.

### AKS + App Gateway browfield (non-working scenario)
**Important:** The steps need to be run with a user/service principal with Contributor role on the subscription without Microsoft.Authorization/roleAssignments/write permissions

Follow the steps in [this tutorial](https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-existing) to create an AKS cluster with a pre-existing App Gateway. The pre-existing App Gateway is in the same resource group as the AKS cluster resource.

The `ingressapplicationgateway-mycluster`  managed identity is still created with Contributor role on the managed resource group. However, this is not sufficient as the App Gateway is in `myResourceGroup` and the managed identity doesn't have any permissions on it.

This leads to errors in the AGIC pod when we try to create a new ingress
```
Code="ErrorApplicationGatewayForbidden" Message="Unexpected status code '403' while performing a GET on Application Gateway. 
You can use 'az role assignment create --role Reader --scope /subscriptions/***/resourceGroups/*** --assignee ***; az role assignment create --role Contributor --scope /subscriptions/***/resourceGroups/***/providers/Microsoft.Network/applicationGateways/*** --assignee ***' to assign permissions. 
AGIC Identity needs atleast has 'Contributor' access to Application Gateway '***' and 'Reader' access to Application Gateway's Resource Group '***'."
```

If we execute the same procedure using a user/service principal with Owner role, then everything works and a Contributor role to  `myResourceGroup`  is automatically assigned to the managed identity.

**Expected behavior**: as mentionned above if the resources are created with Contributor role, the behavior is probably good, otherwise it will be a privilege escalation issue. However, I would expect some kind of warning.
For example when using `az aks update -n myAKSCluster -g myResourceGroup --attach-acr <acr-resource-id` with similar rights we get this error message:
`Could not create a role assignment for ACR. Are you an Owner on this subscription?`

## Anything else we need to know?
Let me know if you want me to provide more details or screenshots of the results in the Azure Portal.

## Environment
- Kubernetes version (use `kubectl version`): 
1.20.9
- Size of cluster (how many worker nodes are in the cluster?): 1
- General description of workloads in the cluster : default cluster created with `az aks create`

**Comment by Kaarthis** [comment]
I reproed with a Contributor role without Microsoft.Authorization Write permission and the Ingress got created following the Tutorial steps as mentioned. https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-existing.  I guess there is some configuration miss or steps missed on your end ? What is the Kubernetes version you are using here

**Comment by oliviergaumond** [comment]
It was Kubernetes version 1.20.9. The Ingress Controller does get created as well as the `ingressapplicationgateway-mycluster` managed identity. However, you can see this managed identity has access to the managed resource group `MC_myResourceGroup_myCluster_canadacentral` but not `myResourceGroup` where the Application Gateway is.  

![image](https://user-images.githubusercontent.com/88553114/136672776-91fd33b7-1a78-4fa8-81aa-6a0a76bf0af0.png)

Here are the complete repro steps (everything is exactly as in the tutorial except the two first commands to create and use the service principal with contributor role)
```
#Create a user with contributor role
az ad sp create-for-rbac --name spn-contributor --role Contributor

#login with that user
az login --service-principal --username <clientId> --password <password> --tenant <tenant>

#create resource group
az group create --name myResourceGroup --location canadacentral

#create AKS
az aks create -n myCluster -g myResourceGroup --network-plugin azure --enable-managed-identity

#create app gateway
az network public-ip create -n myPublicIp -g MyResourceGroup --allocation-method Static --sku Standard
az network vnet create -n myVnet -g myResourceGroup --address-prefix 11.0.0.0/8 --subnet-name mySubnet --subnet-prefix 11.1.0.0/16 
az network application-gateway create -n myApplicationGateway -l canadacentral -g myResourceGroup --sku Standard_v2 --public-ip-address myPublicIp --vnet-name myVnet --subnet mySubnet

#Enable AGIC
appgwId=$(az network application-gateway show -n myApplicationGateway -g myResourceGroup -o tsv --query "id") 
az aks enable-addons -n myCluster -g myResourceGroup -a ingress-appgw --appgw-id $appgwId

#peer the vNets
nodeResourceGroup=$(az aks show -n myCluster -g myResourceGroup -o tsv --query "nodeResourceGroup")
aksVnetName=$(az network vnet list -g $nodeResourceGroup -o tsv --query "[0].name")

aksVnetId=$(az network vnet show -n $aksVnetName -g $nodeResourceGroup -o tsv --query "id")
az network vnet peering create -n AppGWtoAKSVnetPeering -g myResourceGroup --vnet-name myVnet --remote-vnet $aksVnetId --allow-vnet-access

appGWVnetId=$(az network vnet show -n myVnet -g myResourceGroup -o tsv --query "id")
az network vnet peering create -n AKStoAppGWVnetPeering -g $nodeResourceGroup --vnet-name $aksVnetName --remote-vnet $appGWVnetId --allow-vnet-access

#deploy sample app
az aks get-credentials -n myCluster -g myResourceGroup
kubectl apply -f https://raw.githubusercontent.com/Azure/application-gateway-kubernetes-ingress/master/docs/examples/aspnetapp.yaml

#check ingress
kubectl get ingress
```

You will see that the ingress is created but without any address assigned to it
![image](https://user-images.githubusercontent.com/88553114/136672825-07bda27b-ca08-454b-a7c4-e253ba16b5ce.png)

You can also check the logs of the ingress controller pod
```
kubectl get pods -n kube-system
kubectl -n kube-system logs ingress-appgw-deployment-74794dfc45-96z5d
```

You will see a bunch of errors such as 
```
E1009 20:20:20.019614       1 client.go:170] Code="ErrorApplicationGatewayForbidden" Message="Unexpected status code '403' while performing a GET on Application Gateway. You can use 'az role assignment create --role Reader --scope /subscriptions/***edited***/resourceGroups/myResourceGroup --assignee ***edited***; az role assignment create --role Contributor --scope /subscriptions/***edited***/resourceGroups/myResourceGroup/providers/Microsoft.Network/applicationGateways/myApplicationGateway --assignee ***edited***' to assign permissions. AGIC Identity needs atleast has 'Contributor' access to Application Gateway 'myApplicationGateway' and 'Reader' access to Application Gateway's Resource Group 'myResourceGroup'." InnerError="network.ApplicationGatewaysClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '08932110-490e-4556-99b3-75df3160c7d8' with object id '08932110-490e-4556-99b3-75df3160c7d8' does not have authorization to perform action 'Microsoft.Network/applicationGateways/read' over scope '/subscriptions/***edited***/resourceGroups/myResourceGroup/providers/Microsoft.Network/applicationGateways/myApplicationGateway' or the scope is invalid. If access was recently granted, please refresh your credentials.""
I1009 20:20:20.019659       1 retry.go:33] Retrying in 10s
```

**Comment by oliviergaumond** [comment]
Not sure about the last comment about the support case. I thought it was acknowledged that something needs to be fixed in code.

**Comment by miwithro** [comment]
@mscatyao is there a work item to address this?

**Comment by miwithro** [comment]
@robbiezhang is this a configuration update on the AGIC addon?

**Comment by oliviergaumond** [comment]
Bumping this again, as I don't think this is related to a support case
