### ISSUE TITLE
Assigning node taints to system nodepool not working anymore, failing with `SystemPoolHasRestrictedTaint`

### ISSUE THREAD

**Issue by nbusseneau** [Azure/AKS#2578]
Hello 😄

**What happened**: Creating system nodepools with node taints is not working since 2021-09-28, failing with the following error:

```console
(SystemPoolHasRestrictedTaint) Operation failed due to insufficient nodes for system pod scheduling. Placing custom taints on system pool is not supported(except 'CriticalAddonsOnly' taint or taint effect is 'PreferNoSchedule'). Please refer to https://aka.ms/aks/system-taints for detail
```

**What you expected to happen**: System nodepool is created with the node taint applied.

**How to reproduce it (as minimally and precisely as possible)**: Using the CLI:

```sh
az group create --name foo --location westeurope
az aks create --resource-group foo --name bar
az aks nodepool add --name nodepool2 --resource-group foo --cluster-name bar \
  --mode system --node-taints foo=bar:NoSchedule
```

**Anything else we need to know?**:

We recommend users to apply taint `node.cilium.io/agent-not-ready=true:NoSchedule` to nodepools when using [cilium/cilium](https://github.com/cilium/cilium) (CNI plugin) to prevent application pods from being managed by the default AKS CNI plugin.

- Rationale: if users want to use Cilium, there's a concurrency issue where application pods might be managed by Cilium or by the default CNI plugin. Thanks to the node taint, the application pods will not run until Cilium is deployed and removes the taint. A more detailed explanation can be found in https://github.com/cilium/cilium/issues/16602.
- Caveat: it is not possible to apply node taints to the initial nodepool of AKS clusters at creation time (see #1402).
- Solution: as of writing, [Cilium documentation](https://docs.cilium.io/en/v1.10/gettingstarted/k8s-install-default/#create-the-cluster) recommended the users to create a cluster, then add a secondary system nodepool with the taint applied, then delete the initial nodepool.

We test this behaviour in our AKS CI, via an automated GitHub Actions workflow using the Azure CLI (see source command lines [here](https://github.com/cilium/cilium/blob/44a2409c72f5d555b318b6fe8d04067fd02c6402/.github/workflows/conformance-aks.yaml#L190-L229)).

- This was working until 2021-09-28 around 20:00 CEST: https://github.com/cilium/cilium/actions/runs/1283753297
- This stopped working with the error mentioned above soon after (here around 21:45 CEST): https://github.com/cilium/cilium/actions/runs/1284063464

Thanks!

**Comment by palma21** [comment]
AKS System pools only allow 1 taint `CriticalAddonsOnly=true:NoSchedule` or soft taints.
https://docs.microsoft.com/en-us/azure/aks/use-system-pools#system-and-user-node-pools

**AKS User pools support any taint.**

You can still any any taint manually via kubectl in a per node / temporary basis, but not to the node pool model/permanently.

**Comment by nbusseneau** [comment]
@palma21 Thanks for your answer.

> AKS System pools only allow 1 taint CriticalAddonsOnly=true:NoSchedule or soft taints

Does that mean that when it was working (before 2021-09-28), this was actually not intended and should never have been working in the first place?

If that is indeed the case, do you have any recommendation on pod management by third-party CNI plugins?

> so that behavior is by design per the documentation.

Nit: I might have missed where this is specified, but I don't see where in the documentation it is specified that system nodepools can only use `CriticalAddonsOnly=true:NoSchedule` or soft taints => I would suggest clarifying this in the list of system nodepools restrictions.

> > caveat: it is not possible to apply node taints to the initial nodepool of AKS clusters at creation time
>
> This is possible now, that linked issue is not just waiting for update taints to be supported.

Oh, is it? I don't see `--node-taints` in the [`az aks create` documentation](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_create), and it does not seem to work with CLI version 2.28.0. Am I missing something?

**Comment by nbusseneau** [comment]
Re-open please.
