### ISSUE TITLE
Creating AKS cluster with a network address (.0) for DNS Service IP is allowed and doesn't return a validation error

### ISSUE THREAD

**Issue by andbaraks** [Azure/AKS#2579]
**What happened**: You will be allowed to create an AKS cluster with network address (.0) for DNS Service IP.
![image](https://user-images.githubusercontent.com/68290745/135635486-8976320e-7514-43da-b070-6e32ca546925.png)
![image](https://user-images.githubusercontent.com/68290745/135635850-ba3ebfa6-17c9-4968-8fa9-d5d33de9ee5b.png)

Creating a cluster that has the value of a network address (.0) for DNS Service IP will lead to at least the following issues:
- kube-dns service not existing
- DNS resolution will not work from inside the pods
- metrics-server will crash

For example:
![image](https://user-images.githubusercontent.com/68290745/135636216-1eeabfc2-8ea7-4cdc-b8c1-a39d13d9a588.png)

**What you expected to happen**: Get a validation error and not allow the AKS cluster creation

**How to reproduce it (as minimally and precisely as possible)**: Create an AKS cluster with parameter --dns-service-ip a.b.c.0/xy
For example the first screenshot above.

**Anything else we need to know?**: N/A

**Environment**: N/A
- Kubernetes version (use `kubectl version`): Not relevant
- Size of cluster (how many worker nodes are in the cluster?): Not relevant
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Not relevant
- Others: N/A

**Comment by phealy** [comment]
A validation check has been added for this case:

![image](https://user-images.githubusercontent.com/3046014/141662586-1db05847-d348-4ea1-b5d2-c07c7b1105d4.png)

Please let us know if you're still seeing the issue!
