### ISSUE TITLE
Error creating multiple ingress controller with helm in the same AKS cluster

### ISSUE THREAD

**Issue by SwagataChaudhuri** [Azure/AKS#2580]
# Error creating multiple ingress controller with helm in the same AKS cluster

## Steps to reproduce the error

1. Create the first ingress controller using the command as given in the tutorial [Microsoft Docs](https://docs.microsoft.com/en-us/azure/aks/ingress-basic)

   ```bash
   helm install ingress-nginx ingress-nginx/ingress-nginx --create-namespace --namespace ingress-basic
   ```
   
2. Create the second ingress controller with a different name and namespace

   ```bash
   helm install ingress-nginx-new ingress-nginx/ingress-nginx --create-namespace --namespace ingress-basic-new
   ```

   Error:

   ```bash
   Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "ingress-nginx-new": current value is "ingress-nginx"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "ingress-basic-new": current value is "ingress-basic"
   ```

3. Create the second ingress controller with a different name, namespace and class name

   ```bash
   helm install ingress-nginx-new ingress-nginx/ingress-nginx --namespace ingress-basic-new --set controller.ingressClass="nginx-devices"
   ```

   Error:

   ```bash
   Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "ingress-nginx-new": current value is "ingress-nginx"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "ingress-basic-new": current value is "ingress-basic"
   ```

---

**Comment by sossickd** [comment]
Can you check to see what version of the ingress-nginx/ingress-nginx helm chart you are using, as of 4.0.x controller.ingressClass was replaced by controller.ingressClassResource.name. Try running the following of the second helm deployment.

```
helm install ingress-nginx-new ingress-nginx/ingress-nginx --namespace ingress-basic-new --set controller.ingressClassResource.name="nginx-devices"
```

Also if you are running two nginx deployments you want to specify a different controller.ingressClassResource.controllerValue otherwise this can cause a conflict.

https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml 
(Lines 98 - 102)

**Comment by PixelRobots** [comment]
There is a known issue with the newest version of nginx-ingress controller.

"Ingress controller now (starting from v1.0.0) mandates cluster scoped access to IngressClass. This leads to problems when updating old Ingress controller to newest version, as described here. We plan to fix it in v1.0.4 (promise!!), see this."

https://github.com/kubernetes/ingress-nginx/releases

when installing it via helm use the version number --version 3.39.0 and it will install the none v1 version and you will be able to do what you need. Then when v1.04 comes out do some testing.

**Comment by Kaarthis** [comment]
@phillipgibson  do you happen to know who can help here , does seem pertaining to upstream ?

**Comment by phealy** [comment]
[The appropriate parameter to deploy the second `ingressClass` is `controller.ingressClassResource.name`](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L96-L102) which you can override with `--set controller.ingressClassResource.name="nginx-devices"`. This changed in the helm chart version 4, which is when they started using the 1.0.x series of `ingress-nginx`.
