### ISSUE TITLE
Release Notes for 2021.09.28 and 2021.10.19 image missing?

### ISSUE THREAD

**Issue by Schnitzel** [Azure/AKS#2582]
Running `az aks nodepool get-upgrades` I get an image with `AKSUbuntu-1804containerd-2021.09.28` back:

```
 az aks nodepool get-upgrades \
    --subscription "xxx-xxx-xxx-xxx-xxx" \
    --resource-group xxx-cluster \
    --cluster-name xxx \
    --nodepool-name workers
{
  "id": "/subscriptions/xxx-xxx-xxx-xxx-xxx/resourcegroups/xxx-cluster/providers/Microsoft.ContainerService/managedClusters/xxx/agentPools/workers/upgradeProfiles/default",
  "kubernetesVersion": "1.20.9",
  "latestNodeImageVersion": "AKSUbuntu-1804containerd-2021.09.28",
  "name": "default",
  "osType": "Linux",
  "resourceGroup": "xxxx-cluster",
  "type": "Microsoft.ContainerService/managedClusters/agentPools/upgradeProfiles",
  "upgrades": null
}
```

But I can't find any release notes for this release here: https://github.com/Azure/AKS/tree/master/vhd-notes/aks-ubuntu/AKSUbuntu-1804

Can this be provided? As it makes it really hard to know which version of packages are installed without any release notes.
Thanks!

**Comment by Kaarthis** [comment]
Yeah i am am unable to locate that ubuntu release notes tagging few colleagues to see if they can provide answers @miwithro @justindavies

**Comment by Schnitzel** [comment]
this is happening again for `2021.10.19`:
```
❯ az aks nodepool get-upgrades \
    --subscription "xxxx" \
    --resource-group xxxx-cluster \
    --cluster-name xxx \
    --nodepool-name workers
{
  "id": "/subscriptions/xxxx/resourcegroups/xxxx-cluster/providers/Microsoft.ContainerService/managedClusters/xxxx/agentPools/workers/upgradeProfiles/default",
  "kubernetesVersion": "1.20.9",
  "latestNodeImageVersion": "AKSUbuntu-1804containerd-2021.10.19",
  "name": "default",
  "osType": "Linux",
  "resourceGroup": "xxxx-cluster",
  "type": "Microsoft.ContainerService/managedClusters/agentPools/upgradeProfiles",
  "upgrades": null
}
```

there are no release notes here: https://github.com/Azure/AKS/tree/master/vhd-notes/aks-ubuntu/AKSUbuntu-1804

**Comment by miwithro** [comment]
Thanks for reporting this @Schnitzel for the 9/28 VHD that was a hotfix release and we need to account for those on the release notes.   For the 10/19 we haven't cut a Release Notes for that release yet.

**Comment by miwithro** [comment]
@Schnitzel the latest release notes are out.
