### ISSUE TITLE
How to assign Azure Pod Identity on local kubernetes(k8s) cluster (while developing)

### ISSUE THREAD

**Issue by rupeshtech** [Azure/AKS#2585]
I am developing an application which uses Pod Identity to connect to Azure Sql Database.

After deploying it on Azure Kubernetes Service (**AKS**), POD(application) connects to Azure Sql using PodIdentity (Managed Identity).

**How can I assign the same identity to POD while running on my local k8s cluster?**

My deployment yaml looks like 
```apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
  labels:
    app: xxx
spec:
  selector:
    matchLabels:
     appName: xxx
  replicas: 1
  template:
    metadata:
      labels:
        appName: xxx
        aadpodidbinding: samplepodidentity
    spec:
      containers:
      - name: xxx
        image: xxx
        env:
        - name: xxx
          value: "xxx"
        - name: UpdateDbTraceEndpoint
          value: "xxx"
        ports:
        - containerPort: 80
```

**Comment by rupeshtech** [comment]
**Update:---------------------------**

I tried the the [standard walk thru][1] but still it is giving error. 

 [![enter image description here][2]][2]

**According to me MIC is not working on local K8s cluster**. How can I get it working?

  [1]: https://azure.github.io/aad-pod-identity/docs/demo/standard_walkthrough/
  [2]: https://i.stack.imgur.com/CD23V.png

**Comment by miwithro** [comment]
@aramase can you assist?
