### ISSUE TITLE
Nodepool does not scale up when it has min of 0 to X

### ISSUE THREAD

**Issue by Shaybs** [Azure/AKS#2586]
Hi,

We've got some taints and labels on our nodepool which means that only certain pods will run on some nodepools. For our development system, we do not need one node that is up all the time. So we have set the minimum to 0 and maximum to 15. However, the nodepool does not scale after a deployment has been created and the pod gets stuck in provisioning and the nodepool does not scale up.

Shuaib

**Comment by marwanad** [comment]
@Shaybs can you paste the events on the pending pods? Autoscaler logs? It should tell you clearly why a scale up wasn't triggered.

Also, how are you setting those labels and taints? Through the AKS API?

**Comment by marwanad** [comment]
@Shaybs are you modifying taints on node objects directly? If so, this isn't supported in autoscaler. All nodes in a nodegroup are assumed to be similar as far as label and taints go. A random node is picked to be a blueprint of the nodepool and that becomes the basis of the scaling decision. If a node doesn't exist, the information is obtained from the AKS API properties.

**Comment by Shaybs** [comment]
@marwanad Yes, we modify the taints by deleting the taint after the disk has been attached

**Comment by marwanad** [comment]
@Shaybs right - that won't work as clarified in the comment above.
