### ISSUE TITLE
Get-AzAksCluster should reflect attributes shown from az aks show

### ISSUE THREAD

**Issue by petegrimsdale** [Azure/AKS#2590]
**What happened**:  Running Get-AzAksCluster does not expose the same attributes as az aks show which limits the use when using automations and using this to check cluster state - for example powerState to check if a cluster has been stopped

**What you expected to happen**:
The attributes available in the json object from az aks show should be available in the PSKubernetesCluster object

**How to reproduce it (as minimally and precisely as possible)**:
Compare az aks show output with Get-AzAksCluster output

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.9
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others: Powershell module Az.aks version 2.4.0

**Comment by phealy** [comment]
While I agree that `Get-AzAksCluster` doesn't return everything you get from `az aks show`, there is an easy to get all the data you want. `Get-AzResource` returns the full JSON output from ARM given the resource ID, including all properties.

```powershell
> $ResourceId = (Get-AzAksCluster -ResourceGroupName pahealy-ipv6docs -Name aksipv6-bicep).Id
> $Cluster = Get-AzResource -ResourceId $ResourceId
> $Cluster.Properties

provisioningState        : Succeeded
powerState               : @{code=Running}
kubernetesVersion        : 1.22.2
currentKubernetesVersion : 1.22.2
dnsPrefix                : aksipv6-bicep
fqdn                     : aksipv6-bicep-d9728a8a.hcp.centraluseuap.azmk8s.io
azurePortalFQDN          : aksipv6-bicep-d9728a8a.portal.hcp.centraluseuap.azmk8s.io
agentPoolProfiles        : {@{name=nodepool0; count=3; vmSize=Standard_B2ms; osDiskSizeGB=128; osDiskType=Managed; kubeletDiskType=OS; maxPods=110; type=VirtualMachineScaleSets; provisioningState=Succeeded; powerState=; orchestratorVersion=1.22.2; mode=System; osType=Linux;
                           osSKU=Ubuntu; nodeImageVersion=AKSUbuntu-1804gen2containerd-2021.12.07; enableFIPS=False}}
servicePrincipalProfile  : @{clientId=msi}
nodeResourceGroup        : MC_pahealy-ipv6docs_aksipv6-bicep_centraluseuap
enableRBAC               : True
networkProfile           : @{networkPlugin=kubenet; loadBalancerSku=Standard; loadBalancerProfile=; podCidr=10.244.0.0/16; serviceCidr=10.0.0.0/16; dnsServiceIP=10.0.0.10; dockerBridgeCidr=172.17.0.1/16; outboundType=loadBalancer; podCidrs=System.Object[];
                           serviceCidrs=System.Object[]; ipFamilies=System.Object[]}
maxAgentPools            : 100
identityProfile          : @{kubeletidentity=}
oidcIssuerProfile        : @{enabled=False}
```

Does this meet your needs?

**Comment by petegrimsdale** [comment]
@phealy The key item that I was needing to get access too was the powerstate of the cluster.  If you check under agentPoolProfiles for example:
agentPoolProfiles        : {@{name=cache; count=0; vmSize=Standard_D4s_v4; osDiskSizeGB=128; osDiskType=Managed; kubeletDiskType=OS; vnetSubnetID=/subscriptions/################/resourceGroups/rg-aks/providers/Microsoft.Network/virtualNetworks/rtc-aks-vnet/subnets/aks-subnet; maxPods=30; 
                           type=VirtualMachineScaleSets; availabilityZones=System.Object[]; enableAutoScaling=False; provisioningState=Succeeded; powerState=;
                           
powerState is not populated for the cluster so cannot be retrieved to be used in automation checks when checking the cluster status following stop or start actions.  For az cli az aks show returns:
      "powerState": {
        "code": "Stopped"
      },
      "provisioningState": "Succeeded"

**Comment by phealy** [comment]
powerState for the whole cluster is there as a top level property:

```powershell
❯ $ResourceId = (Get-AzAksCluster -ResourceGroupName pahealy-ipv6docs -Name aksipv6-bicep).Id
❯ $Cluster = Get-AzResource -ResourceId $ResourceId
❯ $Cluster.Properties.powerState.code
Running
```

The `powerState` attribute in `agentPoolProfiles` isn't currently used; to stop a nodepool, scale it to 0.

**Comment by petegrimsdale** [comment]
@phealy - thanks for that I missed that.  Great work around !
