### ISSUE TITLE
Customize node configuration: Creating nodepools with custom config makes it impossible to update

### ISSUE THREAD

**Issue by hulvei3** [Azure/AKS#2591]
**What happened**:
When adding a new node-pool on AKS cluster with enabled preview for "CustomNodeConfigPreview", you cannot adjust sizing (didn't check other things) on the pool after creation.
Both cli and portal comes with 

> "(CustomKubeletConfigOrCustomLinuxOSConfigCanNotBeChanged) CustomKubeletConfig or CustomLinuxOSConfig can not be changed for this operation"

**What you expected to happen**:
The node-pool would be resized as normal (alternatively requiring the same config at each update)

**How to reproduce it (as minimally and precisely as possible)**:
- Create a AKS cluster
- Create additional nodepool with custom kinux config like this:
```
az aks nodepool add --name v4m16p30 --cluster-name test-cluster --resource-group test-cluster --enable-cluster-autoscaler --max-pods 30 --min-count 0 --max-count 5 --mode user --kubelet-config ./kubeletconfig.json
```
and `kubeletconfig.json`
```
{
  "cpuCfsQuota": false
}
```
Try adjusting pool size both from portal or cli with `az aks nodepool update --name test-cluster --cluster-name test-cluster --resource-group test-cluster --min-count 1 --max-count 5 --update-cluster-autoscaler` (with out without the config json)

**Anything else we need to know?**:
Running az-cli v2.28.0 with aks-preview v0.5.29

This is really just a duplicate of #2300, but since it was locked and closed with "fix-released" and the fact that this doesn't work as expected I'm forced to create this.

**Environment**:
- Kubernetes version: 1.19.11
- Size of cluster: 2
- General description of workloads in the cluster: testing this on sandbox cluster without any load
- Others:

**Comment by alexeldeib** [comment]
Can you clarify if this still repros? We had a few comparison issues on update which should have been resolved. I haven't had a chance to repro this myself yet but perused the corresponding code/tests and have a hunch this was fixed since the issue was opened. 

If not, let us know and I can take a closer look.
