### ISSUE TITLE
Bring-your-own OMS Agent identity

### ISSUE THREAD

**Issue by Harshith-Bhaskar** [Azure/AKS#2599]
**What happened:**
When using the OMSagent add-on, AKS creates a user-assigned MI in the generated resource group. This makes it harder to assign the required permissions as this identity requires Monitoring Metrics Publisher role to send AKS metrics to Azure Monitor.

**What you expected to happen:**
BYO managed identity for OMSagent2, so that we can have an identity created with necessary roles attached and can be used while creating AKS cluster

**Comment by rootik** [comment]
@Harshith-Bhaskar you can automate OMS agent role assignment with the following code.
Put it after AKS resource definition in the same Bicep module, if you are using Bicep.
```
resource omsAgentRoleAssignment 'Microsoft.Authorization/roleAssignments@2020-10-01-preview' = {
  name: guid(resourceGroup().name, 'omAgentMsi', roleDefinitionId)
  scope: aks
  properties: {
    principalType: 'ServicePrincipal'
    principalId: aks.properties.addonProfiles.omsagent.identity.objectId
    roleDefinitionId: resourceId('Microsoft.Authorization/roleDefinitions', roleDefinitionId)
  }
}
```
Where `aks` is a symbolic name of AKS cluster resource definition,
`roleDefinitionId` is a role definition GUID, e.g. `Monitoring Metrics Publisher` role's GUID, which is `3913510d-42f4-4e42-8a64-420c390055eb`.
You might need to adjust the role assignment name/GUID generation params so it'd be unique in your particular case.

**Comment by vdiec** [comment]
Hi @Harshith-Bhaskar, this feature is now available in public preview https://azure.microsoft.com/en-us/updates/public-preview-use-managed-identitybased-authentication-to-enable-azure-monitor-container-insights/
