### ISSUE TITLE
AKS node temporary disk still in use after unmounting

### ISSUE THREAD

**Issue by jhatcher1** [Azure/AKS#2602]
**What happened**:
I am trying to create a ZFS pool on the temporary storage disk attached to each node in the cluster. Our workloads use this ZFS pool via `hostPath` volumes for temporary storage. I am using a privileged daemonset to run a setup script on the host, as recommended by this article: https://docs.microsoft.com/en-us/azure/aks/support-policies#user-customization-of-agent-nodes

The script does the following:
* Install ZFS
* Unmount the temporary storage disk from `/mnt`
* Create the ZFS pool

When the script attempts to create the ZFS pool, I get the following error, despite the temporary disk being unmounted:
```
$ zpool create -f mypool sdb
/dev/sdb is in use and contains a unknown filesystem.
```
Running `lsof -w | grep sdb1`, where `/dev/sdb` is the temporary disk, shows a `jbd2` process which I suspect is using the disk. If I remove the temporary disk from `/etc/fstab` and reboot the node, this process does not show up, and I can create the ZFS pool successfully.

**What you expected to happen**:
Ideally, the daemonset wouldn't need to reboot each new AKS node after it starts for the first time. I'd expect it to be able to unmount the temporary disk and immediately create a ZFS pool on the disk.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new AKS cluster
2. kubectl apply the following file:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: temporary-storage-setup-script
  namespace: default
data:
  run_on_host.sh: |
    #!/bin/bash

    # Copy and run the temporary storage setup script on the host
    cp /tmp/temporary_storage_setup.sh /host

    /usr/bin/nsenter -m/proc/1/ns/mnt -- \
      sh -c 'chmod u+x /tmp/install/temporary_storage_setup.sh && /tmp/install/temporary_storage_setup.sh'

    sleep infinity

  temporary_storage_setup.sh: |
    #!/bin/bash
    set -x

    pool_name="mypool"

    # Install zfs
    sudo apt-get update -y && sudo apt-get install -y zfsutils-linux

    # The temporary storage disk is mounted by default to /mnt, so unmount it and clear it from fstab.
    umount /mnt
    sed -iE 's@^.*/dev/disk/cloud/azure_resource-part.*$@@g' /etc/fstab
    echo "Unmounted temporary storage disk"

    # Get the temporary storage disk name
    disk="$(sudo realpath "$(sudo find /dev/disk/cloud -name azure_resource)" | grep -oE "sd[a-z]")"
    if [ "$?" -ne 0 ]
    then
        echo "No temporary disk found, exiting"
        exit 1
    fi

    # Create the zfs pool
    zpool create -f "$pool_name" "$disk"
    if [ "$?" -ne 0 ]
    then
        echo "Failed to create the ZFS pool"
        lsof -w | grep "$(basename "$disk")1"
        lsblk
        exit 1

        # echo "Failed to create ZFS pool "$pool_name", rebooting so the disk will not be in use"
        # reboot
    fi

    echo "Success"

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: temporary-storage-setup
spec:
  selector:
    matchLabels:
      job: temporary-storage-setup
  template:
    metadata:
      labels:
        job: temporary-storage-setup
    spec:
      hostPID: true
      restartPolicy: Always

      containers:
      - image: mcr.microsoft.com/aks/fundamental/base-ubuntu:v0.0.11
        name: temporary-storage-setup

        securityContext:
          privileged: true

        command: ['/bin/bash', '-c', '/tmp/run_on_host.sh']

        volumeMounts:
        - name: temporary-storage-setup-script
          mountPath: /tmp
        - name: host-mount
          mountPath: /host

      volumes:
      - name: temporary-storage-setup-script
        configMap:
          name: temporary-storage-setup-script
          defaultMode: 0755
      - name: host-mount
        hostPath:
          path: /tmp/install
```
3. Check the logs from one of the daemonset pods. It should show:
```
+ zpool create -f mypool sdb
/dev/sdb is in use and contains a unknown filesystem.
```
and the results of `lsof -w` and `lsblk` for troubleshooting.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: v1.21.2
- Size of cluster: 1 x D8s_v3
- General description of workloads in the cluster: HTTP microservices, Python app

**Comment by phealy** [comment]
I've been unable to reproduce this issue with provisioing a cluster using `az aks create --name zfs2 -s Standard_D8ds_v4 --node-count 1 --node-osdisk-type Managed`:

```
+ umount /mnt
+ sed -iE 's@^.*/dev/disk/cloud/azure_resource-part.*$@@g' /etc/fstab
+ echo 'Unmounted temporary storage disk'
Unmounted temporary storage disk
++ grep -oE 'sd[a-z]'
+++ sudo find /dev/disk/cloud -name azure_resource
sudo: unable to resolve host temporary-storage-setup-fh8cd
++ sudo realpath /dev/disk/cloud/azure_resource
sudo: unable to resolve host temporary-storage-setup-fh8cd
+ disk=sdb
+ '[' 0 -ne 0 ']'
+ zpool create -f mypool sdb
Success
+ '[' 0 -ne 0 ']'
+ echo Success
```

I suggest putting a sync in after the umount to make sure the kernel has finished flushing the caches to disk. That's the most likely reason for jbd2 to stay running, and you don't have any waits.

**Comment by jhatcher1** [comment]
Hi @phealy , thanks for your reply.

I'm also unable to reproduce this issue using `az aks create --name zfs2 -s Standard_D8ds_v4 --node-count 1 --node-osdisk-type Managed`

If I create the cluster through the Azure console (as I did originally, I forgot to mention this), I can consistently reproduce the issue, even if I add a sync after the unmount. Here's a screenshot of the configuration I did:
![Screen Shot 2021-11-11 at 11 47 22 AM](https://user-images.githubusercontent.com/52168365/141344289-d2008152-cf14-4d4b-9f91-ec1ae4107d8d.png)

I immediately clicked "Review + Create" after filling in the above configuration.

**Comment by phealy** [comment]
OK, that told me what I needed. When you deploy a standard configuration via the portal, one of the things it includes is [Azure Monitor](https://docs.microsoft.com/en-us/azure/aks/monitor-aks). You can turn that off on the Integrations tab by setting container monitoring to false.

Review page:
![image](https://user-images.githubusercontent.com/3046014/141349978-7a44f3f9-06c8-4e17-b45c-0a305d034497.png)

Azure Monitor installs an OMS agent daemonset which has a number of hostpath mounts - some of which are under /mnt, in case you've placed your docker installation on the temporary disk (an old way of doing things, not supported now that we have ephemeral OS disks). Because of that, that OMS agent pod has a lock on /mnt.

```shell
kubectl -n kube-system describe pod omsagent-zrnmd
<snip>
Volumes:
  containerlog-path-2:
    Type:          HostPath (bare host directory volume)
    Path:          /mnt/docker
    HostPathType:
  containerlog-path-3:
    Type:          HostPath (bare host directory volume)
    Path:          /mnt/containers
    HostPathType:
<snip>
```

Not installing the Azure Monitor addon or deleting the omsagent pods after the `umount` allows the umount to finish and ZFS to provision.

**Comment by phealy** [comment]
If this doesn't fix your problem, please let me know and I'll continue to investigate!

**Comment by jhatcher1** [comment]
Thanks @phealy , we were able to fix our problem with your guidance. Our solution was to add a step in the script to stop the omsagent pod, before creating the zfs pool, and after running `umount /mnt`.
```
# Stop the omsagent pod to free /mnt
omsagent_pod="$(crictl get pods | grep -E 'omsagent-[a-z0-9]{5}' | awk '{ print $1 }')" || true
if [ -n "$omsagent_pod" ]
then
    crictl stopp "$omsagent_pod"
fi
```
