### ISSUE TITLE
Cluster in North Europe region running images from mcr.azk8s.cn registry

### ISSUE THREAD

**Issue by hairmare** [Azure/AKS#2607]
**What happened**:

I noticed that a AKS cluster running in North Europe was using images from the `mcr.azk8s.cn` registry.

**What you expected to happen**:

I would expect for a cluster that is not in china to only use images from `mcr.microsoft.com`.

**How to reproduce it (as minimally and precisely as possible)**:

Install aks, wait for a bit and check image sources. 
```
kubectl get pods -n kube-system -oyaml | grep cn
      image: mcr.azk8s.cn/oss/kubernetes/ip-masq-agent:v2.5.0.7
      image: mcr.azk8s.cn/oss/kubernetes/ip-masq-agent:v2.5.0.7
      image: mcr.azk8s.cn/oss/kubernetes/ip-masq-agent:v2.5.0.7
      image: mcr.azk8s.cn/oss/kubernetes/autoscaler/cluster-proportional-autoscaler:1.8.3
      image: mcr.azk8s.cn/oss/kubernetes/coredns:1.8.3
      image: mcr.azk8s.cn/oss/kubernetes/coredns:1.8.3
      image: mcr.azk8s.cn/oss/kubernetes-csi/azuredisk-csi:v1.7.0.1
      image: mcr.azk8s.cn/oss/kubernetes-csi/azuredisk-csi:v1.7.0.1
      image: mcr.azk8s.cn/oss/kubernetes-csi/livenessprobe:v2.4.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/csi-node-driver-registrar:v2.3.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/azuredisk-csi:v1.7.0.1
      image: mcr.azk8s.cn/oss/kubernetes-csi/csi-node-driver-registrar:v2.3.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/azuredisk-csi:v1.7.0.1
      image: mcr.azk8s.cn/oss/kubernetes-csi/livenessprobe:v2.4.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/csi-node-driver-registrar:v2.3.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/azuredisk-csi:v1.7.0.1
      image: mcr.azk8s.cn/oss/kubernetes-csi/livenessprobe:v2.4.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/azuredisk-csi:v1.7.0.1
      image: mcr.azk8s.cn/oss/kubernetes-csi/livenessprobe:v2.4.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/azurefile-csi:v1.6.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/livenessprobe:v2.4.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/csi-node-driver-registrar:v2.3.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/azurefile-csi:v1.6.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/csi-node-driver-registrar:v2.3.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/azurefile-csi:v1.6.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/azurefile-csi:v1.6.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/azurefile-csi:v1.6.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/livenessprobe:v2.4.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/csi-node-driver-registrar:v2.3.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/azurefile-csi:v1.6.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/livenessprobe:v2.4.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/azurefile-csi:v1.6.0
      image: mcr.azk8s.cn/oss/kubernetes-csi/livenessprobe:v2.4.0
      image: mcr.azk8s.cn/oss/kubernetes/metrics-scraper:v1.0.4
      image: mcr.azk8s.cn/oss/kubernetes/kube-proxy:v1.21.2-hotfix.20210830.1
      image: mcr.azk8s.cn/oss/kubernetes/kube-proxy:v1.21.2-hotfix.20210830.1
      image: mcr.azk8s.cn/oss/kubernetes/kube-proxy:v1.21.2-hotfix.20210830.1
      image: mcr.azk8s.cn/oss/kubernetes/kube-proxy:v1.21.2-hotfix.20210830.1
      image: mcr.azk8s.cn/oss/kubernetes/kube-proxy:v1.21.2-hotfix.20210830.1
      image: mcr.azk8s.cn/oss/kubernetes/kube-proxy:v1.21.2-hotfix.20210830.1
      image: mcr.azk8s.cn/oss/kubernetes/dashboard:v2.0.1
      image: mcr.azk8s.cn/oss/kubernetes/metrics-server:v0.4.4
      image: mcr.azk8s.cn/aks/hcp/hcp-tunnel-front:master.210906.1
```
**Anything else we need to know?**:
I noticed this thanks to falco which contains an [allowlist](https://github.com/falcosecurity/falco/blob/f7893fbd14e2a2c919eaf896a05144bf0763cadb/rules/falco_rules.yaml#L2836) of containers that get to use the k8s api.

I hope that traffic to `mcr.azk8s.cn` wont get billed as non regional traffic in some way.

**Environment**:
- Kubernetes version: Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"0b17c6315e806a66d507e77760a5d60ab5cccfd8", GitTreeState:"clean", BuildDate:"2021-08-30T01:42:22Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster: 7
- General description of workloads in the cluster: various static and python apps + infra components like falco
- Others:

**Comment by phealy** [comment]
@hairmare can you please confirm whether the fix Ace referred to has fixed the issue for you?

**Comment by hairmare** [comment]
The affected cluster is still running images from `mcr.azk8s.cn`. I checked to see if `kubectl -n kube-system rollout restart daemonset csi-azuredisk-node` fixes the issue but the new pods use the cn registry as well. 

Do we need to upgrade the cluster to get the fix?

**Comment by phealy** [comment]
I'd try a [node image upgrade](https://docs.microsoft.com/en-us/azure/aks/node-image-upgrade), which will restart things but will get the newest kubelet/cri versions.

**Comment by hairmare** [comment]
@phealy We tried to "node image upgrade" as per the docs but are failing to do so.

First we tried running upgrade with `--node-image-only`:
```bash
az aks upgrade \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --node-image-only
```
it returned `the following arguments are required: --kubernetes-version/-k`.

After adding `--kubernetes-version 1.21.2`  it complains about `unrecognized arguments: --node-image-only`.

After `--help` we decided to try a nodepool upgrade:
```bash
az aks nodepool upgrade \
  --cluster-name myAKSCluster \
  --resource-group myResourceGroup \
  --name default \
  --kubernetes-version 1.21.2
```

I also checked for a cli update to no avail:
```
$ az --version
azure-cli                         2.30.0

core                              2.30.0
telemetry                          1.0.6

Extensions:
aks-preview                       0.4.10
log-analytics                      0.1.3

Python location '/usr/bin/python3.6'
Extensions directory '/home/lucasb/.azure/cliextensions'

Python (Linux) 3.6.15 (default, Sep  5 2021, 00:00:00) 
[GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

Do you have an ideas what we could try next to force the nodepool update?

**Comment by phealy** [comment]
`--node-image-upgrade` is an argument to `az aks nodepool upgrade`, not `az aks upgrade`. An upgrade command like this should work:  `az aks nodepool upgrade --node-image-only --cluster-name <clusterName> --name <nodepoolName>`

**Comment by phealy** [comment]
OK, I would try removing or updating your `aks-preview` extension, as version 0.4.10 is from 2019-08-22.

`az extension remove -n aks-preview`
`az extension updating -n aks-preview`
