### ISSUE TITLE
omsagent high memory consumption

### ISSUE THREAD

**Issue by MrImpossibru** [Azure/AKS#2609]
Hello,

Is it ok to have a memory consumption of omsagent like 300mb per pod for an empty cluster?
Why do we have a ReplicaSet and a ScaleSet with the same pod at the same time?
~~Now I see a new omsagent-prometeus pod which adds 100mb of memory consumption on each node. Is it possible to turn off prometeus feature because I don't use it?~~

Link to the issue on the Docker-Provider repo - https://github.com/microsoft/Docker-Provider/issues/624 https://github.com/microsoft/Docker-Provider/issues/694
https://github.com/microsoft/Docker-Provider/issues/797

Thanks.

**Comment by MasterKolka** [comment]
@seguler @vishiy @saaror Are there any updates?

**Comment by EderRoger** [comment]
@seguler  @MasterKolka Any updates on this issue? Thanks

**Comment by MrImpossibru** [comment]
Up

**Comment by MrImpossibru** [comment]
up

**Comment by MrImpossibru** [comment]
Up

**Comment by MrImpossibru** [comment]
Up
