### ISSUE TITLE
AKS Windows Node pool Change Time zone issue

### ISSUE THREAD

**Issue by akshay10505** [Azure/AKS#2617]
**What happened**:
We deployed web application in window's node pool. We want to change time zone with normal image builder. It's not happening.
**What you expected to happen**:
Want to set IST time zone for Windows Node pool. 
**How to reproduce it (as minimally and precisely as possible)**:
Publish code with Docker file provided by Default by Microsoft in Visual Studio . There is no option there to change timezone for Windows Node pool.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use ``kubectl versionkubectl version`): 1.20.9
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by miwithro** [comment]
@AbelHu

**Comment by AbelHu** [comment]
@akshay10505 @miwithro AKS does not support setting timezone in agent nodes. You can set timezone in your containers. This is guidance to set timezone in windows containers. https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/virtual-time-zone
