### ISSUE TITLE
Memory management issue on Windows Node pool AKS  

### ISSUE THREAD

**Issue by akshay10505** [Azure/AKS#2618]
**What happened**:
In windows node pool CPU utilization is getting scaled automatically but for Memory once memory is occupied it is not getting scaled down.
**What you expected to happen**:
Memory management issue  
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by miwithro** [comment]
@justindavies

**Comment by palma21** [comment]
Are you referring to cluster autoscaler or horizontal pod autoscaler?
