### ISSUE TITLE
Newest 1.21.2 AKS and changed tags on outbound public ips

### ISSUE THREAD

**Issue by MichalKoziorowski-TomTom** [Azure/AKS#2619]
**What happened**:
Previously, outbound public ips in node group had `type=aks-slb-managed-outbound-ip` tag set. 
Newest deployments have `aks-managed-type=aks-slb-managed-outbound-ip` tag set. 

I suppose it can be related to https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2021-10-15 - `Add aks-managed-cluster-rg and aks-managed-cluster-name tags to the node resource group` changes.

**What you expected to happen**:
Tags in node resource group resources shouldn't change that much in same major AKS version (1.21.x). 

**Environment**:
- Kubernetes version : 1.21.2, using linux nodes.

**Comment by miwithro** [comment]
@MichalKoziorowski-TomTom yes this is correct.  Changing the tag from a too general keyword to “aks-managed-“ prefix has been well discussed, and we have already got lots of customer feedback because of the too general keyword.

We should have communicated the Behavioral change earlier to customers.  That was an error on our side.

**Comment by MichalKoziorowski-TomTom** [comment]
Would it be possible to not have such changes in "not preview" or "stable" versions of AKS? Or at least not in same AKS patch level, like 1.21.2, but rather waiting for next 1.21.x one? Such changes are quite scary.

We are seeing more strange things, but not related to "Add aks-managed-cluster-rg and aks-managed-cluster-name tags to the node resource group" coming with latest deployments. Is it in any way possible that behaviour of Service annotation "service.alpha.kubernetes.io/tolerate-unready-endpoints" changed? It's really strange that something that worked with 1.21.2 just suddenly stopped to work after 2021-10-15 AKS release, and none of changes in our code and helm charts were performed.

**Comment by MichalKoziorowski-TomTom** [comment]
Thanks

**Comment by kbhalaki** [comment]
I actually see the same output when I run:
`az network public-ip list --resource-group ` 

but my cluster version is at 1.20.7.

**Comment by MichalKoziorowski-TomTom** [comment]
@kbhalaki Try something like:
  REGION_AKS_OUTBOUND_IPS=$(az network public-ip list \
    --subscription "${SUBSCRIPTION_ID}" \
    --query "[?tags.type=='aks-slb-managed-outbound-ip' || tags.\"aks-managed-type\"=='aks-slb-managed-outbound-ip'].ipAddress" |
     jq -cr '. | map(. + "/32")')
  AKS_OUTBOUND_IPS=$(jq -c \
    --argjson aksoutboundips "${AKS_OUTBOUND_IPS}" \
    --argjson regionaksoutboundips "${REGION_AKS_OUTBOUND_IPS}" \
    -n '$aksoutboundips + $regionaksoutboundips | unique')

**Comment by kbhalaki** [comment]
@MichalKoziorowski-TomTom  isnt this change only from cluster 1.21.2? Why am I seeing in 1.20.7?

**Comment by MichalKoziorowski-TomTom** [comment]
@kbhalaki I have no idea, but I suppose MSFT could push that change to all AKS versions.

**Comment by naioja** [comment]
@kbhalaki that's the case all clusters that are being provisioned new regardless of the version they will get the new tags.
