### ISSUE TITLE
[Feature Request] New Azure Policies for Kubernetes - Jan 2022

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#2621]
Please comment with any built-in policy requests and use cases on the comments below.

**Comment by philwelz** [comment]
Hey,

idea for a policy:

- Block Labels `control-plane` & `admission.gatekeeper.sh/ignore` on namespaces - with these Labels users could exclude namespaces on purpose from all constraints defined in the cluster

**Comment by miwithro** [comment]
@karataliu @fseldow add the policy recommendations from @philwelz to our list.

**Comment by matt-garner-nw** [comment]
- Deny use of Depricated API's
- Deny use of Default Service Account
- Require containers to use latest tag
- Require containers to be tagged
- Require containers to have limits set

**Comment by matt-garner-nw** [comment]
Thanks @philwelz is there a policy to deny using latest tag?

**Comment by MarkTopping** [comment]
Thanks for asking Palma21.

A few quick ideas for additional policies that might be useful (or would be in my company's situation) 

- require Services to be of a given type (i.e. ClusterIP to prevent teams from creating LoadBalancer types)
- require certain labels to be present (i.e I'd like to enforce aadpodidbinding, & an env label)
- require containers to have probes
- require certain annotations (say for ingress class, or seccomp profile)
- deny secret creation in certain namespaces
- require ingress resource to contain spec.tls

**Comment by philwelz** [comment]
@MarkTopping 

* require Services to be of a given type (i.e. ClusterIP to prevent teams from creating LoadBalancer types)
  * you can block at least allow only internal LBs = https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/LoadbalancerNoPublicIPs.json
* require certain labels to be present (i.e I'd like to enforce aadpodidbinding, & an env label)
  * https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/PodEnforceLabels.json

**Comment by philwelz** [comment]
> Thanks @philwelz is there a policy to deny using latest tag?

not built-in yet

**Comment by MarkTopping** [comment]
> @MarkTopping
> 
> * require Services to be of a given type (i.e. ClusterIP to prevent teams from creating LoadBalancer types)
>   
>   * you can at least allow only internal LBs = https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/LoadbalancerNoPublicIPs.json
> * require certain labels to be present (i.e I'd like to enforce aadpodidbinding, & an env label)
>   
>   * https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/PodEnforceLabels.json

Hey. Yeah I'm aware of the first of those (and have that in place).... but I'd somehow missed the second one which on re-inspection I now see. thank you!

**Comment by philwelz** [comment]
> > @MarkTopping
> > 
> > * require Services to be of a given type (i.e. ClusterIP to prevent teams from creating LoadBalancer types)
> >   
> >   * you can at least allow only internal LBs = https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/LoadbalancerNoPublicIPs.json
> > * require certain labels to be present (i.e I'd like to enforce aadpodidbinding, & an env label)
> >   
> >   * https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/PodEnforceLabels.json
> 
> Hey. Yeah I'm aware of the first of those (and have that in place).... but I'd somehow missed the second one which on re-inspection I now see. thank you!

i also thought about a block all types of `LoadBalancer` kind of policy  🤝

**Comment by nlighten** [comment]
> > Thanks @philwelz is there a policy to deny using latest tag?
> 
> not built-in yet

Guess this is already possible by setting the allowedContainerImagesRegex to for example `^.+azurecr.io/.+:(?:(?!latest).)+$` in allowed images build-in policy https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/ContainerAllowedImages.json

**Comment by miwithro** [comment]
Thanks all.  I have added the above the backlog and we will evaluate them this month.

**Comment by philwelz** [comment]
hey @miwithro is there any outcome of the evaluation?

**Comment by miwithro** [comment]
@MarkTopping @fseldow we are evaluating "deny secret creation in certain namespaces" what is the use case you are trying to achieve here?  What we are trying to figure out is if this should be a built-in AKS policy or a custom policy that fits specific use cases.

**Comment by nlighten** [comment]
> @miwithro So in my case we typically don't want to be using Kubernetes Secrets. We much prefer that all secrets are stored somewhere else like in Azure Key Vault for example. However, in some cases we don't have full control over the workload being deployed and sometimes Secrets are required - this would typically apply only when deploying a third party workload rather than something built in-house (like an Ingress Controller for example).
> 
> So in my setup, knowing that in-house software should not be using Secrets because the developers should be making use of a Vault instead I'd like to have a control in Azure Policy which blocks Secrets from being created in all Namespaces which development/product teams have control of. Obviously we can (and will) also use specific RBAC controls to limit their capabilities, but this restriction feels better aligned to Azure Policies if it were to be controlled in a single place. In reality we'd likely use both Azure Policy and RBAC controls if both were available to give us a little extra coverage. But as we 'shift left' it feels likely we'd end up giving someone admin permissions on a Namespace at some point in time - and restricting Secret creation would then fall back on Azure Policy controls to enforce cluster security standards.
> 
> Hopefully that clarifies... please feel free to ask any further questions

Just a suggestion, but perhaps this could be more generic by allowing a list of `Kinds` as parameter that will be blocked so that the policy is not limited to `Secrets`? This would make this policy similar to the 'Not allowed resource types' policy that exists for ARM resources. Of course it should be possible to exclude namespaces from evaluation.

**Comment by miwithro** [comment]
@fseldow
