### ISSUE TITLE
Should create the same verison with AKS while enabling Virtual Node..

### ISSUE THREAD

**Issue by DanielWangZhanggui** [Azure/AKS#2622]
**What happened**:
While enabling Virtual Node Addon on an AKS cluster, it creates a latest kublet version which may not be compatible with AKS version
**What you expected to happen**:
We can choose the version while using it. At least, it should create the same verison with AKS by default.

**How to reproduce it (as minimally and precisely as possible)**:
enable virtual-node add on 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by mikkelhegn** [comment]
> "..it creates a latest kublet version which may not be compatible with AKS version"

Virtual Node only has one version, which is supported by the AKS service team. Can you provide more details on the version numbers you're referring to? The Virtual Kubelet, used by Virtual Node, implements the K8s client library here: https://github.com/virtual-kubelet/azure-aci/blob/master/cmd/virtual-kubelet/main.go#L37.
