### ISSUE TITLE
AuthorizationFailed while exposing a load balancer

### ISSUE THREAD

**Issue by vadmeste** [Azure/AKS#2625]
**What happened**:
An intermitent issue while exposing a load balancer using an automation script.

Below is the output of ` kubectl describe svc nginx-ingress-ingress-nginx-controller -n extensions`

```
$ kubectl describe svc nginx-ingress-ingress-nginx-controller -n extensions
Name:                     nginx-ingress-ingress-nginx-controller
Namespace:                extensions
Labels:                   app.kubernetes.io/component=controller
                          app.kubernetes.io/instance=nginx-ingress
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=ingress-nginx
                          app.kubernetes.io/version=1.0.4
                          helm.sh/chart=ingress-nginx-4.0.6
Annotations:              meta.helm.sh/release-name: nginx-ingress
                          meta.helm.sh/release-namespace: extensions
                          service.beta.kubernetes.io/azure-dns-label-name: xxxxxxx
Selector:                 app.kubernetes.io/component=controller,app.kubernetes.io/instance=nginx-ingress,app.kubernetes.io/name=ingress-nginx
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.0.113.52
IPs:                      10.0.113.52
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  30249/TCP
Endpoints:                10.244.0.8:80
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  32283/TCP
Endpoints:                10.244.0.8:443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                  Age                From                  Message
  ----     ------                  ----               ----                  -------
  Normal   EnsuringLoadBalancer    35s (x4 over 70s)  service-controller    Ensuring load balancer
  Warning  ListLoadBalancers       35s (x4 over 70s)  azure-cloud-provider  Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: {"error":{"code":"AuthorizationFailed","message":"The client '2de0e200-fd7e-4686-8dfe-52cb56aaf350' with object id '2de0e200-fd7e-4686-8dfe-52cb56aaf350' does not have authorization to perform action 'Microsoft.Network/loadBalancers/read' over scope '/subscriptions/xx-xx-xx-xx-xx/resourceGroups/mc_xxx-test-aks-managedapp_xxxaks_francecentral/providers/Microsoft.Network' or the scope is invalid. If access was recently granted, please refresh your credentials."}}
  Warning  SyncLoadBalancerFailed  35s (x4 over 70s)  service-controller    Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: {"error":{"code":"AuthorizationFailed","message":"The client '2de0e200-fd7e-4686-8dfe-52cb56aaf350' with object id '2de0e200-fd7e-4686-8dfe-52cb56aaf350' does not have authorization to perform action 'Microsoft.Network/loadBalancers/read' over scope '/subscriptions/xx-xx-xx-xx-xx/resourceGroups/mc_xxx-test-aks-managedapp_xxxaks_francecentral/providers/Microsoft.Network' or the scope is invalid. If access was recently granted, please refresh your credentials."}}
```

My template which creates the AKS cluster:

```json
    {
      "comments": "*** AKS cluster with custom-named nodeResourceGroup and system assigned managed identity ***",
      "type": "Microsoft.ContainerService/managedClusters",
      "apiVersion": "2021-08-01",
      "location": "[parameters('location')]",
      "name": "[variables('aksName')]",
      "identity": {
              "type": "SystemAssigned"
      },
      "properties": {
        "kubernetesVersion": "1.21.2",
        "dnsPrefix": "[variables('aksName')]",
        "agentPoolProfiles": [
          {
            "name": "pool",
            "count": "[parameters('nodeCount')]",
            "vmSize": "[parameters('nodeSize')]",
            "osType": "Linux",
            "storageProfile": "ManagedDisks",
            "type": "VirtualMachineScaleSets",
            "mode": "System"
          }
        ],
        "networkProfile": {
          "loadBalancerSku": "standard",
          "outboundType": "loadBalancer"
        }
      }
    },
```

I create the load balancer using this:
```
/usr/local/bin/kubectl create namespace extensions
/usr/local/bin/helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
/usr/local/bin/helm install nginx-ingress ingress-nginx/ingress-nginx --namespace extensions --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"=something
```

**What you expected to happen**:
Creating a load balancer is always successful

**How to reproduce it (as minimally and precisely as possible)**:
I will do that if needed, but it might not happen in normal configuration as I am developing an Azure managed application.

**Anything else we need to know?**:
- I am using an automation script and this issue doesn't always happen
- 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"881d4a5a3c0f4036c714cfb601b377c4c72de543", GitTreeState:"clean", BuildDate:"2021-10-21T05:13:01Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Nothing much
- Others:

**Comment by phealy** [comment]
I'm assuming, since you referenced automation, that you're connecting and deploying this application immediately after cluster provisioning. This can happen due to AAD replication delays, where the new cluster managed identity takes a few minutes to show up. This should automatically rectify in a few minutes, as replication will complete and the access will appear.

There are two main ways to deal with this:
1. Switch to using a [user-assigned managed identity](https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#bring-your-own-control-plane-mi) - because you provision this before the cluster provisioning starts, it lets AAD replication occur while the cluster build is in progress and makes it more likely to have completed by the time the cluster build is complete.
2. Put a wait into your pipeline to wait for the LoadBalancer service to have a value in the status.loadBalancer field so that you don't continue until everything is in a ready state.

**Comment by vadmeste** [comment]
> 2\. Put a wait into your pipeline to wait for the LoadBalancer service to have a value in the status.loadBalancer field so that you don't continue until everything is in a ready state.

As per my testing, the load balancer never gets a public IP when AuthorizationFailed shows up even after waiting for one hour. Also removing the load balancer doesn't work, kubectl delete svc never quits as well.

**Comment by phealy** [comment]
If you have a cluster in this state (or can get one to this state), please open a service request. It sounds like it might not be the usual replication delay, but a problem with assigning permissions, and support will need the ability to access logs that opening a request brings.

**Comment by pabelanger** [comment]
Also seeing this, it isn't 100% but every so often it does happen. Can't seem to recover the cluster and we have to delete / reprovision.

**Comment by chadwickalex** [comment]
Occasionally happens when I re-use the same resource names and destroy then immediately recreate the resources using terraform. Where the clientid referenced by the AuthorizationFailed error message doesn't match any extant identities.

I workaround this issue by appending some random ints to resource names now. Specifically the resource group and cluster names.

**Comment by nicksc423** [comment]
I'm currently running into this issue.  There seems to be some mismatch between the SystemAssigned Identity created by AKS and the Identity that nginx-ingress/azure-cloud-provider is using, they have totally different client & object IDs.  When I make an AKS with a SystemAssigned Identity it shows up in my Azure Dashboard which not what you see in the nginx-ingress svc events.

You can also query the objectID in nginx-ingress svc events the using the Azure rest API
`az rest --method POST --url 'https://graph.microsoft.com/v1.0/directoryObjects/getByIds' --headers 'Content-Type=application/json'  --body '{"ids":["<object-id>"]}'`
shows that this is not the SystemAssigned Identity that gets created when I create my AKS cluster, but some different Identity entirely.
