### ISSUE TITLE
Does AKS support Android Emulator Container?

### ISSUE THREAD

**Issue by bhargavmodi** [Azure/AKS#2628]
**What happened**:
It is required to create a jenkins pipeline for Android projects. In order to run the android test cases, it is required to start the Android emulator and execute in it through gradle script. Luckily, Google has published Android Emulator images(i.e. https://github.com/google/android-emulator-container-scripts/blob/master/REGISTRY.MD) which can be leveraged for this purpose. 

But, with it comes the hardware requirement to be full-filled in order to run the emulator. The below is the requirement link which states that the Linux based KVM (Kernel based Virtual Machine) must be accessible in order to run the Android Emulator.
https://github.com/google/android-emulator-container-scripts/blob/master/REGISTRY.MD#requirements-and-recommendations 

**What you expected to happen**:
The KVM should be accessible in AKS cluster where the jekins pipeline is running. Also there should be documentation on enabling the nested virtualisation by accessing the KVM.

**Comment by seanmck** [comment]
No, KVM is not supported with AKS. The best alternative is Azure Pipelines:

https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops
