### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by spacecat** [Azure/AKS#263]
Fairly new to Docker and AKS so stupid question maybe.

Is it possible to run MongoDB in a container on AKS?

**Comment by ultimateboy** [comment]
Absolutely. There's nothing preventing this. You should be able to use the mongodb helm chart: https://github.com/kubernetes/charts/tree/master/stable/mongodb-replicaset

But even better would be to review CosmosDB https://azure.microsoft.com/en-us/services/cosmos-db/?v=17.45a

You can use CosmosDB with the Kubernetes Service Catalog and the Meta Azure Service Broker. See https://github.com/Azure/meta-azure-service-broker/blob/master/docs/azure-cosmos-db.md for more details on this.
