### ISSUE TITLE
Largest possible ephemeral temp disk for Standard_NC4as_T4_v3 differs from documented size

### ISSUE THREAD

**Issue by OvervCW** [Azure/AKS#2635]
**What happened**:

I tried to create a node pool with `Standard_NC4as_T4_v3` instances using ephemeral OS disks. Since these instances don't have an OS cache, I expect to be able to [use their temp disk for this purpose](https://azure.microsoft.com/en-us/updates/ephemeral-os-disks-for-azure-vms-for-additional-vm-sizes-is-now-generally-available/) instead.

According to the [NCas T4 v3 documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/nct4-v3-series) these instances should have a temp disk of 180 GiB, so I tried to create a node pool with that OS disk size:

```
az aks nodepool add --cluster-name xxx --name xxx --resource-group xxx --node-vm-size Standard_NC4as_T4_v3 --node-count 1 --priority Spot --spot-max-price -1 --min-count 1 --max-count 1 --enable-cluster-autoscaler --node-osdisk-type Ephemeral --node-osdisk-size 180
```

However, this immediately returns the following error message:

```
(VMCacheSizeTooSmall) The virtual machine size Standard_NC4as_T4_v3 has a cache size of 154619000000 bytes, but the OS disk requires 193273528320 bytes. Use a VM size with larger cache or disable ephemeral OS.
```

This seems to suggest that the actual maximum temp disk size is 144 GiB.

Is this a mistake in the documentation or did I miss something?

**What you expected to happen**:

For the node pool to be created with the 180 GiB os disk size.

**How to reproduce it (as minimally and precisely as possible)**:

Create an AKS cluster and run the command above to add a node pool to it.

**Anything else we need to know?**:

N/A

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.7
- Size of cluster (how many worker nodes are in the cluster?) N/A
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): N/A
- Others: N/A

**Comment by phealy** [comment]
Some VM sizes have a maximum cached disk size that is lower than the total temp disk size, as you've discovered. This is not an AKS limitation; it is based on Azure Compute. You can find the exact maximum disk size allowed for a given SKU by using Azure CLI or the [Compute Resource SKUs list API](https://docs.microsoft.com/en-us/rest/api/compute/resource-skus/list) - the capability name you're looking for is `CachedDiskBytes`.

```shell
$ az vm list-skus --all -s "Standard_NC4as_T4_v3" -l westus2 --query "[0].capabilities[?name=='CachedDiskBytes'].value" -o tsv
154619000000
```

**Comment by OvervCW** [comment]
@phealy Will that limit be added to the documentation at some point in the same way that the maximum cache size is documented for the [Fsv2-series](https://docs.microsoft.com/en-us/azure/virtual-machines/fsv2-series), for example?

**Comment by phealy** [comment]
@OvervCW Currently AKS only supports ephemeral disk on cache, not on temp. You are correct that the docs are wrong; I've submitted a request to the owning team for them to update them as appropriate. Thanks!

**Comment by OvervCW** [comment]
> @OvervCW Currently AKS only supports ephemeral disk on cache, not on temp. You are correct that the docs are wrong; I've submitted a request to the owning team for them to update them as appropriate. Thanks!

According to the [update blog](https://azure.microsoft.com/en-us/updates/ephemeral-os-disks-for-azure-vms-for-additional-vm-sizes-is-now-generally-available/) ephemeral disks are supported on temp disks now and we can confirm that this works in practice.
