### ISSUE TITLE
Support multiple private endpoints for AKS for both API (kubectl) and Portal Access

### ISSUE THREAD

**Issue by JamesDLD** [Azure/AKS#2638]
**What happened**: The portal view of following panels is not accessible when browsing through a second private link.
-  Namespaces
- Workloads
- Services and ingresses
- Storage
- Configuration

**What you expected to happen**: 
When using a second private link it would have been great if the portal access that calls an url like "https://xxxxx-priv.portal.hcp.westeurope.azmk8s.io" had it's DNS automatically recorded in an [Azure Private DNS zone](https://docs.microsoft.com/en-us/azure/aks/private-clusters?source=docs&WT.mc_id=AZ-MVP-5003548#configure-private-dns-zone).

This is working perfectly for the kubectl access that uses the Azure DNS Private Zone **privatelink.<region>.azmk8s.io**.

**How to reproduce it (as minimally and precisely as possible)**: Create a private Azure AKS Cluster with it's Private DNS Zone.
Add a new private link with your preferred tools, ARM Template, Bicep, Terraform.

**Anything else we need to know?**: Diagram available here https://github.com/Azure/AKS/issues/1978

**Comment by chandraneel** [comment]
Portal uses the FQDN for the proxy endpoint, i would expect the private link feature to handle the mapping for the FQDN to the internal IPs in the private DNS zones. Will work with product team and get back here.

**Comment by rouke-broersma** [comment]
@JamesDLD this is actually already possibly, simply register a private dns zone for portal.hcp.westeurope.azmk8s.io with your vnet and create a dns record pointing to the api server private endpoint. You don't need a separate endpoint for the portal and kubectl. Don't know why the portal uses a different fqdn because they go to the exact same endpoint.

**Comment by SeWieland** [comment]
I can confirm that this works perfectly fine. I created a private DNS zone and added the private enpoint FQDN as CNAME to the subdomain shown in the portal as missing.

I would really like to be able to create the entries automatically through terraform though, I have no idea how to retrieve that subdomain...

**Comment by JamesDLD** [comment]
Hi, having one private endpoint works, what's not working is having more than one. This is a special but usefull scenarios when the platform is being accessed by clients located in virtual networks that are not peered and sometime with IP overlapping. 
A diagram of this scenario is available here https://github.com/Azure/AKS/issues/1978

**Comment by rouke-broersma** [comment]
@JamesDLD nope, we have that exact scenario and it works perfectly fine. Simply create a new dns entry for the portal fqdn in the dns for those users, and create the new private endpoint in their virtual network.

If you're unsure how to create the extra private endpoints see these articles:

- https://broersma.dev/azure-aks-private-clusters/
- https://broersma.dev/approve-private-endpoint-connections/

@SeWieland the url is available in a property on the AKS object with the name portalfqdn.

**Comment by JamesDLD** [comment]
Thank you @rouke-broersma for the information, I need to re test it then. I did it on Nov 2021 and it was not supported and confirmed by the Microsoft support.

**Comment by JamesDLD** [comment]
As mentioned by @rouke-broersma it's now supported! Thank you.
