### ISSUE TITLE
tunnelfront constantly restart due liveness probe failed: cannot change locale (en_US.UTF-8)

### ISSUE THREAD

**Issue by rafavvf** [Azure/AKS#2639]
**What happened**:
I tried to upgrade my aks cluster version from 1.18 to 1.21, but I have an error with pod "tunnelfront", it was restarting constantly, when I describe the pod, this show me this: "Liveness probe failed: /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)"

**What you expected to happen**:
I want to re deploy the pod, but it was in a production environment, I fear to this action causes interruption to my cluster.

**Anything else we need to know?**:
With other upgrades this didn't happen, this is the only one what have this error.

**Environment**:
- Kubernetes version: 1.21.1
- Size of cluster: 6 nodes

**Comment by phealy** [comment]
As this is affecting a production cluster, please [open a support request via the Azure Portal.](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-a-resource-menu)

**Comment by VSAfbol** [comment]
I am seeing exact same issue. Also noticed that I get an error while trying to get to the live logs of the pod.

**Comment by jamesdunlop3** [comment]
We are seeing the exact same issue 1.21.1 and 6 Nodes.

**Comment by Dkaivalya** [comment]
Having the same problem where tunnelfront,metrics-server and autoscaler pods are continuesly resarting .

**Comment by qike-ms** [comment]
This is likely a Firewall configuration issue on your firewall. Make sure the IP of your API server is allowed. You can try:

ssh -p 9000 -o StrictHostKeyChecking=no -vvv user@<your api server name>
If it returns permission denied, then it's not Firewall issue, but if it returns connection reset, it is.
