### ISSUE TITLE
AzureML can't attach a PrivateAKS cluster using a Public DNS zone

### ISSUE THREAD

**Issue by fethidilmi** [Azure/AKS#2640]
**What happened**:
We have an issue with attaching a Private AKS cluster (using a public dns zone), as an inference cluster to a private AzureML cluster.

**What you expected to happen**:
We want to be able to attach a Private AKS cluster (using a public dns zone), as an inference cluster to a private AzureML cluster.

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy a private AKS cluster using a public dns zone (Azure CNI).
- Deploy a private AzureML cluster with a private endpoint (with private dns zones for ***.azureml.ms** and ***.notebooks.azure.net** to hold records for this private endpoint) attached to the vnet that's hosting the AzureML cluster.
- Attach the private AKS cluster to AzureML as an inference cluster.
- Experience an error due to a timeout error.

**Comment by phealy** [comment]
Please see the (Azure ML documentation for attaching an AKS cluster](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-attach-kubernetes?tabs=python#limitations), specifically the limitations section:

> [Using a public fully qualified domain name (FQDN) with a private AKS cluster is not supported with Azure Machine learning.](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-attach-kubernetes?tabs=python#:~:text=Using%20a%20public%20fully%20qualified%20domain%20name%20(FQDN)%20with%20a%20private%20AKS%20cluster%20is%20not%20supported%20with%20Azure%20Machine%20learning.)

As far as I'm aware this is not an AKS limitation but an Azure ML limitation, so the AKS team cannot do anything to enable this functionality.
