### ISSUE TITLE
Feature request: Add AKS availability zone for Switzerland 

### ISSUE THREAD

**Issue by davidrigaudetatfr** [Azure/AKS#2647]
**What happened**: it's an ER

**What you expected to happen**: Make this feature available

**How to reproduce it (as minimally and precisely as possible)**: N/A

**Anything else we need to know?**: for Etat FR, we can consume services only in  Switzerland !

**Environment**: 
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by TomGeske** [comment]
Switzerland region doesn't have availability zone yet. We are working on it and it is planned to become available in the future.
