### ISSUE TITLE
DR for AKS in UAE regions

### ISSUE THREAD

**Issue by xunil123** [Azure/AKS#2650]
**What happened**: 
We are looking for DR for AKS in UAE region. 

**What you expected to happen**: 
As of now Availability zones are not available for AKS in UAE region and Microsoft suggesting us to use the Velero as a backup solution. Our production cluster is in UAE north and we configured Velero namespace backup in the same cluster. But in a DR scenario how can we use those namespace backups to restore the namespaces in other region.

**How to reproduce it (as minimally and precisely as possible)**: 
1. One cluster in each region (UAE-North & UAE-Central)
2. Configure Velero backup in UAE-North region and take the backup of the namespace
3. Restore those backups in UAE-Central region.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by andyzhangx** [comment]
pls file issue to https://github.com/vmware-tanzu/velero/issues since it's a velero product issue, thanks.

**Comment by keikhara** [comment]
Hello @xunil123, I understand you are waiting for Availability Zone to be ready in UAE. We will inform to the customers when this will be ready. As for namespace backup/restore. AKS should not be considered different with other k8s customers. I would expect this to be the same. 
https://documentation.suse.com/suse-caasp/4.2/html/caasp-admin/_backup_and_restore_with_velero.html?fbclid=IwAR0_w_JkUejgHvRHOvvabfFAzStOIn_xRvc99ub3uNR5hCGLslUuhl3urXg#_backup
For detail questions about Velero, please go to Velero,
