### ISSUE TITLE
Specify the requested agent pool node number when  turning Cluster Auto Scaler off

### ISSUE THREAD

**Issue by William-LP** [Azure/AKS#2656]
Hello !

In the  [2021-09-30's release note](https://github.com/Azure/AKS/releases/tag/2021-09-30) it says :
> Behavioral Changes
> When turning Cluster Auto Scaler off, you can now specify the requested agent pool node number.

Out of this changelog I haven't been able to find out anything documenting this new behavior.

So I have fired-up a cluster to try this out, with `--enable-cluster-autoscaler --min-count 1 --max-count 5`  and then tried to disable cluster autoscaler while specifying the request number of node in my pool :

`az aks nodepool update -g my-rg --cluster-name my-cluster  -n default --disable-cluster-autoscaler --node-count 2`

Unfortunately this command fails while I specified the `--node-count` parameter.

Can you enlight me about this change and how am I supposed to use it ?

I'm running `1.21.2` kubernetes version.

**Comment by TomGeske** [comment]
@marwanad, @justindavies can you help sharing how to use `--disable-cluster-autoscaler` and specify requested agent pool node number?
