### ISSUE TITLE
Be able to register AKS for HCI from one of Switzerland regions

### ISSUE THREAD

**Issue by davidrigaudetatfr** [Azure/AKS#2657]
**What happened**: We can't register AKS for HCI in Switzerland North or West

**What you expected to happen**: be able to register AKS for HCI from Switzerland North or West

**How to reproduce it (as minimally and precisely as possible)**: During the registration phase of AKS in the HCI 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by TomGeske** [comment]
Please, open an issue in [aks-hci repo](https://github.com/Azure/aks-hci/issues)
