### ISSUE TITLE
Rotating certificates in an AKS cluster results in the windows-gmsa-webhook-controller-manager failure to start

### ISSUE THREAD

**Issue by israelvaldez** [Azure/AKS#2658]
**What happened**:
After we rotated the kubernetes certificates of our Azure Cluster the windows-gmsa-webhook-controller-manager pod stopped working.

**What you expected to happen**:
The windows-gmsa-webhook-controller-manager should continue working after certificate rotations

**How to reproduce it (as minimally and precisely as possible)**:
Create an AKS cluster with gMSA turned on : 
  - Create an AKS cluster
  - Follow the steps from https://docs.microsoft.com/en-us/azure/aks/use-group-managed-service-accounts#register-the-akswindowsgmsapreview-preview-feature to enable the feature
  - Follow the steps on https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/gmsa-aks-ps-module to setup gMSA on the AKS cluster
  - Rotate the AKS cluster certificates using the instructions from: https://docs.microsoft.com/en-us/azure/aks/certificate-rotation

**Anything else we need to know?**:
Next is the log that shows up if you do a kubectl logs on the failed gMSA webhook pod:

time="2021-11-10T21:36:00Z" level=info msg="starting webhook server at port 443"
panic: tls: failed to find any PEM data in certificate input
goroutine 1 [running]:
main.main()
  /go/src/sigs.k8s.io/windows-gmsa/admission-webhook/main.go:28 +0x185
![image](https://user-images.githubusercontent.com/38796159/142226909-68bbb38f-6c44-4b4b-8b88-a17ea77bd9dc.png)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.9
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by andyzhangx** [comment]
could you provide your subs id? thanks.

**Comment by israelvaldez** [comment]
@andyzhangx I sent you an email with it

**Comment by andyzhangx** [comment]
thanks, we have identified it's a bug, and would be fixed in next month's release. (due to the holiday season, there is no more release this month, thanks for understanding)

**Comment by andyzhangx** [comment]
this issue is fixed in v20211202 release and with one more week, it would be rolled out to all regions.
