### ISSUE TITLE
Request for CoreDNS upgrade to 1.8.5 to support wildcard RR pairs

### ISSUE THREAD

**Issue by theharrisonchow** [Azure/AKS#2668]
**What happened**: There is a bug on CoreDNS 1.8.4 and lower which restricts the use of wildcard RR pairs on coreDNS file plugin. There are no alternative if we want to serve wildcard records via coreDNS as there are no plugin customizations available.

1.8.5 Release information: https://coredns.io/2021/09/10/coredns-1.8.5-release/

Specific Wildcard RR Pair fix: https://github.com/coredns/coredns/pull/4828

**What you expected to happen**: Allow for wildcard RR pairs in coreDNS within AKS.

**How to reproduce it (as minimally and precisely as possible)**: 

Example here:  *abc.bcd.wildcard.com does not resolve*, whereas, cde.wildcard.com resolves
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  db.wildcard.com: |
    $ORIGIN wildcard.com.
    @  3600 IN  SOA sns.dns.icann.org. noc.dns.icann.org. (
      2020080302 ;
      7200       ;
      3600       ;
      1209600    ;
      3600       ;
    )
    *.bcd                   IN  A  10.0.0.1 #  abc.bcd.wildcard.com does not resolve
    cde                     IN  A  10.0.0.2 #  this resolves
  wildcard.com.server: |
    wildcard.com:53 {
      errors
      health
      # issue in coreDNS CNAME Resolution for wildcards to be fixed in 1.8.5 coredns https://coredns.io/2021/09/10/coredns-1.8.5-release/
      # Temporary workaround is to manually serve all records :(
      file /etc/coredns/custom/db.wildcard.com wildcard.com
      # Fall back to use subnet dns server
      forward . /etc/resolv.conf
      cache 30
    }
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20, v1.21
- Size of cluster (how many worker nodes are in the cluster?): 10
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Basic cluster with network tools pods

**Comment by qpetraroia** [comment]
Hey @theharrisonchow,

We never had CoreDNS version 1.8.4. If you are using a cluster version >= 1.20, you are using CoreDNS version 1.8.6. May I ask how are you exactly stuck here? 

Thanks,
Quentin

**Comment by theharrisonchow** [comment]
Confirmed issue no longer exists after rebooting cluster. Strange, will close for now.
