### ISSUE TITLE
OSM add-on config to support sidecar resources

### ISSUE THREAD

**Issue by SatyKrish** [Azure/AKS#2676]
**What happened**:
AKS with OSM add-on enabled creates `envoy`  sidecar container without resources request/limit. This can cause inefficient pod scheduling on AKS nodes.

```sh
# Installed OSM meshconfig without sidecar resources
$ kubectl get meshconfig osm-mesh-config -n kube-system -o jsonpath='{.spec.sidecar.resources}{"\n"}'
{}
```

**What you expected to happen**:
OSM add-on config should have default resources request/limits or have support for user to configure request/limits for sidecar container.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy AKS cluster using below OSM add-on config.

```json
# OSM add-on config used in ARM template
"openServiceMesh": {
      "enabled": true,
      "config": {
          "egress": "true",
          "permissive_traffic_policy_mode": "true"
      }
    }
```

**Anything else we need to know?**:
As a workaround, I'm patching `meshconfig` using the command below.

```sh
$ kubectl patch meshconfig osm-mesh-config -n kube-system -p '{"spec":{"sidecar":{"resources":{"limits":{"cpu":"1","memory":"512M"},"requests":{"cpu":".5","memory":"128M"}}}}}'  --type=merge
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.2
- Size of cluster (how many worker nodes are in the cluster?): 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Http microservices
- Others:

**Comment by keithmattix** [comment]
@SatyKrish thank you for filing this issue. To clarify, would being able to use `kubectl apply` be an effective workflow for you? Or are you specifically asking for the configuration to be surfaced during install? The former may allow the mesh config to plug into your existing deployment pipelines.
