### ISSUE TITLE
Persistent Volumes on Azure Files suddenly failing

### ISSUE THREAD

**Issue by tomasr** [Azure/AKS#2678]
**What happened**:
We have an AKS cluster that's been running for > 2 years. Currently running 1.21.2. We run a lot of pods, each with 2 Azure File volumes mounted. This has been running without problems until the last week.

Now what we see is pods suddenly lose access to all their Azure File mounted volumes, and trying to access the volumes report:
```
$ cd /data
$ ls
ls: reading directory '.': Host is down
```
So connectivity is getting lost, and it's not getting reset. It takes destroying the pod and forcing a new one to get created to re-establish connectivity. In the cases we've observed this happening, it's with pods that have been running for over 30d.

We're still technically using the older 'azurefiles' storage provider (since there's been 0 guidance so far on how to migrate those over to CSI), so not sure if that is relevant.

**What you expected to happen**:

Connectivity should be re-established automatically.

What I'm hoping to get, if possible, is some guidance for how to even troubleshoot the issue. Are there any logs or other information I could gathered to understand what's going on.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.2
- Size of cluster (how many worker nodes are in the cluster?) 4
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Java applications running HTTP and other TCP-based protocols
- Others:

**Comment by andyzhangx** [comment]
I think you could file an azure support ticket to azure file team, mainly it's due to connection issue between agent node and azure file server: https://docs.microsoft.com/en-us/azure/storage/files/storage-troubleshoot-linux-file-connection-problems#mount-error112-host-is-down-because-of-a-reconnection-time-out

**Comment by tomasr** [comment]
I get that I could open a support ticket. But seeing how I haven't had much luck lately with them being able to do anything (much less troubleshoot issues like this), I'd rather not waste my time.

What would be really helpful, though, would be to know if there's at least some way to monitor the situation. Are there any metrics related to the PVCs or Pods that would reveal this condition so that we can build some auto-pod-restart to handle it?

**Comment by tomasr** [comment]
Just for anyone interested: This seems to now be happening at least once a day, with half of our pods going down due to this error.

As far as I've been able to see, there seems to be absolutely no way to monitor the issue, since there doesn't appear to be any metrics tied to the azure-file PV system (and the status of PVs/PVCs don't get affected).

Why the azure-file volume system doesn't seem to have any way to recover from this seems pretty bad.

I'm starting to suspect this issue started after we did our last cluster upgrade (k8s version), and so now I'm sitting here wondering if this is somehow related to the move to the CSI-based storage drivers....

**Comment by andyzhangx** [comment]
@tomasr would you file azure ticket to azure file team? azure file driver only deals with mount and unmount, mainly it's due to connection issue between agent node and azure file server

**Comment by tomasr** [comment]
@andyzhangx It might very well be the case that there's something odd on the storage side. But frankly, it just seems like the "mount and unmount" code is just not as robust as it should be. It should not just completely lose connectivity and then neither have a metric you can track to detect the condition and correct it, or, even better, auto-recover from this condition on its own.

Because if this is the best we can hope for, we might as well start looking for alternatives.

I'm not trying to be snarky. It's just really frustrating that Microsoft keeps pushing changes on the Kubernetes side and simply not care what has been broken by those changes. And the move to CSI drivers has been so poorly documented, with zero migration guidance provided, that I can't but seriously consider that it might be the source of the issues we're seeing.

**Comment by jagguli** [comment]
Hi we are still experiencing this, we were advised to use the hard mount option, but there is no easy way to do that in the inline volume config . Also I suspect the workaround is not going to help as we put health checks on our pods to restart if it times out. but that lead to outages. I also grinding the support  channels to make M$ actually solve the problem for me for the $$$$ they charge .

**Comment by andyzhangx** [comment]
`Host is down` error could be due to azure file account migration, in the migration process, azure file server IP could be changed, and original smb mount would hit `Host is down` error, workaround is delete original pod, and smb remount would happen with new azure file server IP.  This issue is actually Linux SMB kernel client bug, the smb kernel client should detect the smb server ip change, and corresponding smb kernel client fix is still in the backport process.

**Comment by jagguli** [comment]
well obviously "workaround is delete original pod, and smb remount would happen with new azure file server IP." is not working for us. I set this workaround in a k8s liveness probe and that only exacerbated the issue further.

**Comment by jagguli** [comment]
This was working fine .. we ony had a few files on it with very low usage, but critical files. Hence I'm a bit fucking annoyed, pardon my french.

**Comment by jagguli** [comment]
I 've been provided these mount opts for inline `azureFile` volumes hope this hold. I hate waking up to customers reporting outages
```
mountOptions:

  - dir_mode=0777

  - file_mode=0777

  - sec=ntlmv2

  - cache=strict

  - hard
 ```

**Comment by jagguli** [comment]
absolute waste of time, `azureFile` does not support mountOptions? 

https://github.com/kubernetes/examples/blob/master/staging/volumes/azure_file/README.md

**Comment by andyzhangx** [comment]
@jagguli PV/PVC would support mountOptions. Would `hard` mount option help solve this issue?

```
hard
The program accessing a file on the cifs mounted file system will hang when the server crashes.
```

**Comment by jagguli** [comment]
I had to reimplement as a PVC and was able to stabilise it so far.

It's just sad that this is not documented anywhere in aks docs .

**Comment by andyzhangx** [comment]
> I had to reimplement as a PVC and was able to stabilise it so far.
> 
> It's just sad that this is not documented anywhere in aks docs .

@jagguli it's documented in k8s docs: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options
inline volume of different k8s drivers does not support mount options.

**Comment by jagguli** [comment]
Good but obviously if special mount options are  required for a production workload it should be noted as so. I wouldn't need to contact support and a week of emails to get to the bottom of it, and reimplement something that was configured as per official documentation.

**Comment by jagguli** [comment]
>  smb kernel client fix is still in the backport process.

do you have a link to the issue/target version etc ...

**Comment by andyzhangx** [comment]
Azure file CSI driver supports `mountOptions`:
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/a4449543786489e0aa7303138c431d6fd538a38a/deploy/example/nginx-pod-azurefile-inline-volume.yaml#L21-L26

**Comment by nakazonot** [comment]
I have the same problem.
The system has been in operation for about 3 years, but this problem started to occur from last month.
Did the specification change that changes the IP in Azure Files?
All I did here was to enable "Large file shares".

**Comment by andyzhangx** [comment]
cc @RenaShahMSFT

**Comment by nakazonot** [comment]
@andyzhangx
I heard from support that the IP of Azure Files is undergoing a change.
Can we conclude that CSI driver is required to use AKS and Azure Files together?
I'm having to reboot several times a day in a non-CSI environment.

**Comment by andyzhangx** [comment]
> @andyzhangx I heard from support that the IP of Azure Files is undergoing a change. Can we conclude that CSI driver is required to use AKS and Azure Files together? I'm having to reboot several times a day in a non-CSI environment.

@nakazonot this is not related to CSI driver itself, ip change is handled automatically by smb kernel driver, it should be fixed in linux kernel 5.5, while current AKS is still on kernel 5.4

**Comment by nakazonot** [comment]
@andyzhangx Thanks!
When will the kernel 5.5 be available?
Is the only way to support it in the current state is to move to CSI drivers?
Wouldn't it be better to have an official Azure guide?

**Comment by andyzhangx** [comment]
> @andyzhangx Thanks! When will the kernel 5.5 be available? Is the only way to support it in the current state is to move to CSI drivers? I think it would be better to guide you in Azure official.

@nakazonot no clear ETA yet for kernel 5.5 availability, and smb kernel team are trying to port those fixes to 5.4
And unfortunately move to CSI drivers won't solve the issue.

**Comment by jagguli** [comment]
> @andyzhangx Do you have a link to this issue/change in the linux kernel for future reference?

I got this from azure support:

Recently, we hit some bugs on the Linux SMB kernel client which essentially blocks the Azure files account migration scenario.

Below are the list of bugs that affect this scenario (in that order):

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4e456b30f78c429b183db420e23b26cde7e03a78
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=506c1da44fee32ba1d3a70413289ad58c772bba6
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4ac0536f8874a903a72bddc57eb88db774261e3a
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7be3248f313930ff3d3436d4e9ddbe9fccc1f541
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=869da64d071142d4ed562a3e909deb18e4e72c4e

**Comment by brysk** [comment]
> @andyzhangx Wouldn't an NFS mount with a CSI driver solve the problem?

@andyzhangx We started to see "Host is down" issues in our cluster and are wondering whether migration to NFS 4.1 would solve the problem.

@tomasr Do you use NFS mount or CIFS?

Does anybody know if Azure Files NFS is free from these disconnection issues?

**Comment by andyzhangx** [comment]
> > @andyzhangx Wouldn't an NFS mount with a CSI driver solve the problem?
> 
> @nakazax We started to see "Host is down" issues in our cluster and are wondering whether migration to NFS 4.1 would solve the problem.
> 
> @tomasr Do you use NFS mount or CIFS?
> 
> Does anybody know if Azure Files NFS is free from these disconnection issues?

@brysk Azure NFS accounts will not migrate. So IP will not change with Azure Files NFS.

**Comment by sebastianhutter** [comment]
We are experiencing the same issue. Every now and then we can't write to the Azure Storage Account.

```
2022-03-23 12:10:28.467  WARN 1 --- [t Price Thread4] c.g.mbp.price.service.StorageService     : Error writing file /azure/231: Host is down
```
(log message from two weeks ago, but we still experience the issues)

Did anyone of you had luck with migrating to NFS4 or any other approach?
