### ISSUE TITLE
Node label value shifted to another Node automatically

### ISSUE THREAD

**Issue by vigneshsolution** [Azure/AKS#2679]
**What happened**:
While we performed "Node image" upgrade on one of the Node Pools(having 3 worker nodes), we have noticed that end of the image upgrade activity , the label value set on Node1(lets say "allownginx=true") moved to Node3 automatically(which is not supposed to be happened)
Note: These worker nodes are configured using VMSS.

**What you expected to happen**:
Even after the Node image upgrade activity, label values should remain same in all the Nodes within the NodePool.
(lets say "allownginx=true" in Node1)

**How to reproduce it (as minimally and precisely as possible)**:
Create AKS cluster with one Node Pool(let it be in system mode), ensure worker nodes are configured using VMSS. Add few custom labels to Node1 alone. Perform node image upgrade activity and verify whether labels on node1 remains same.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.7
- Size of cluster (how many worker nodes are in the cluster?) 3worker nodes(1 node pool in system mode)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Microservices
- Others:

**Comment by allyford** [comment]
Hi @vigneshsolution,
Thanks for your feedback! During an upgrade, we guarantee at the end that you should have the same number of labels on an agentpool, but not necessarily on the same node (as nodes should be identical). Could you provide a bit more detail on your use case and need to persist the label on one node through upgrade?
