### ISSUE TITLE
Support of custom audit policy to control the auditing of kube-audit logs

### ISSUE THREAD

**Issue by Alexander-Bartosh** [Azure/AKS#2684]
**I would like to be able to change audit policy for my AKS cluster**:
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy

Is it possible to change the audit policy now ? 
If no, Is there any plan to provide this functionality ? 

Currently I have to disable the audit because it generates a lot of not needed data

**Comment by palma21** [comment]
You have 2 types of audit log configs on AKS
<https://docs.microsoft.com/en-us/azure/aks/monitor-aks-reference>

Standard audit and audit-admin that excludes get and list events and removes a large portion of these.

What kind of config would you be looking for?
