### ISSUE TITLE
AKS 1.20.9 - nodes network timeouts

### ISSUE THREAD

**Issue by Nilubkal** [Azure/AKS#2685]
**What happened**:
Since a month or so we are noticing an arbitrary slowness in pod's response time when they are scheduled on different nodes.

Example: 

We have a 2 pod `statefullset` deployment which runs a `JAVA app`.  
Both the pods are serving the same requests. Since its a sts they tend to stick to the same nodes when scheduled. After a couple of days one of the pods doubles his response time, whiteout any changes being made insight of the pods. This is observed **on various AKS clusters in different regions**. The only mitigation that we found so far is rescheduling the slow pod on another node in the cluster and then it starts to respond fast again. We achieve this by cordoning the "problematic node" and restarting the pod. 
Since a couple of days we see the same behavior with a different JAVA app in the cluster.
Recently we were witnessing the same behavior with an `nginx` ingress deployment , one of the pods scheduled on a particular node was having huge network timeouts , so when re-scheduled on a different node it was working better ( this was observed only in one AKS cluster  in contrast with the JAVA deployment ).  
The worker nodes are part of a availability set -  vmss vms 

**Environment**:

```bash
Client Version: version.Info {Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

Server Version:  version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"454b5b515582f8ac8419435dc9c230fc97fb844b", GitTreeState:"clean", BuildDate:"2021-11-01T19:59:05Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

```
- 30 nodes
-  Java apps + HTTP microservices

**Comment by jeffmhastings** [comment]
We have also seen reports of periodic connection timeouts and increased latency between nodes in a cluster running AKS 1.20.9. The first evidence of these issues was on 11/22, and it has been affecting our workloads since that time.

It would be great if someone from AKS could comment on the issue. I'd be more than happy to provide any diagnostic information.

I can say that the node image being used in the environment experiencing this issue is `AKSUbuntu-1804gen2containerd-2021.08.21`, though it's unclear to me if upgrading the node image would resolve issue or not without understanding the root cause.

**Comment by phealy** [comment]
Good day all - can you please open a service request on this issue? We can't request cluster information via GitHub issues but there's not much to troubleshoot this particular issue that we can do without it.

As far as the Java app goes - is it happening on all pods on a node, or just the one? Is it possible that this could be an app problem (memory leak, handle leak, etc.)? As rescheduling the pod terminates the application and namespaces and gives you a brand new pod, this would fix any leaks that you might be experiencing. We can certainly investigate a network issue, but I haven't heard of this problem before.

**Comment by Nilubkal** [comment]
> Good day all - can you please open a service request on this issue? We can't request cluster information via GitHub issues but there's not much to troubleshoot this particular issue that we can do without it.
> 
> As far as the Java app goes - is it happening on all pods on a node, or just the one? Is it possible that this could be an app problem (memory leak, handle leak, etc.)? As rescheduling the pod terminates the application and namespaces and gives you a brand new pod, this would fix any leaks that you might be experiencing. We can certainly investigate a network issue, but I haven't heard of this problem before.

There is a service request opened already and under investigation. The stage that we are at right now is exactly exploring the behavior of the app scheduled on the "problematic" nodes. In terms of memory leaks and resource consumption everything looks ok. The main issue is that we are witnessing the same behavior on other clusters/nodes with different apps ( still JAVA ).
