### ISSUE TITLE
Aks built-in roles

### ISSUE THREAD

**Issue by William-LP** [Azure/AKS#2686]
**What happened**:

I have created an aks cluster running kubernetes 1.21.2 with thoses options : 
```
Kubernetes RBAC --> enable
AKS-managed AAD --> enable
Local accounts  --> disabled
```

When I run the `az aks get-credentials --resource-group <resource-group> --name <cluster-name> --admin` it fails as expected. So far it's looking good.

I still want someone to be admin, so I give a user following privileges :

```
Azure Kubernetes Service Cluster User Role
Azure Kubernetes Service RBAC Cluster Admin
```

I followed the following steps to try out my user is a cluster admin :

- `az login` and input my user's credentials to login
- `az aks get-credentials --resource-group <resource-group> --name <cluster-name>` to download the `clusterUser_kubeconfig`
- `kubectl get pods -A` to list pods in all namespaces
- it prompts me something like `To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DKXXXXX8T to authenticate.`
- I login using my user's credential again and allow the k8s application to connect to my user.
- `kubectl get pods -A` fails : `Error from server (Forbidden): pods is forbidden: User "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" cannot list resource "pods" in API group "" at the cluster scope`

According to what I have read so far, it should be working as my user is `Azure Kubernetes Service RBAC Cluster Admin`. Could someone enlighten me what I've missed or misunderstood ?

**Comment by miwithro** [comment]
@William-LP If you intend to use K8RBAC with AAD and disable local you must do the next logical step from the document below to configure the Role Bindings in the cluster to allow the user to logon.

https://docs.microsoft.com/en-us/azure/aks/azure-ad-rbac?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Faks%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json

A simpler approach is to enable Azure RBAC on the cluster and then the configuration you used above would work.

[az aks update](https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac#integrate-azure-rbac-into-an-existing-cluster)
