### ISSUE TITLE
Azuredisk-csi daemonset pod Failed to connect to csi-proxy v1beta with error: open \\.\\pipe\\csi-proxy-filesystem-v1beta1: The system cannot find the file specified.

### ISSUE THREAD

**Issue by woshizhicainiaoluguo** [Azure/AKS#2693]
**What happened**:
I deployed a azure-disk-csi in my cluster and it works well in the windows machine,
however when I added a new windows machine,the daemonset pod csi-azuredisk-node-win was crashloop wrong.
I create the same folder, put the csi-proxy in the correct path, but it not works in the new windows machine.

**What you expected to happen**:
the daemonset pod could work normally
**How to reproduce it (as minimally and precisely as possible)**:
I'm not sure

**Anything else we need to know?**:
attach the error log ,the problem is likely this issue,          

https://github.com/Azure/AKS/issues/2568

but i'm not sure they are exactly same, 
And if I also need to create ticket to let you handle it  in the backend ? It's too much trouble...
restart machine and pod seems not work, and I still have a well work windows machines in our cluster
need your help, thankyou .

[root@apaas-master0004 ~]# kubectl -n kube-system logs -f csi-azuredisk-node-win-gb47m
error: a container name must be specified for pod csi-azuredisk-node-win-gb47m, choose one of: [liveness-probe node-driver-registrar azuredisk]
[root@apaas-master0004 ~]# kubectl -n kube-system logs -f csi-azuredisk-node-win-gb47m -c azuredisk
I1209 06:54:43.024439    1644 main.go:108] set up prometheus server on [::]:29605
I1209 06:54:44.769243    1644 azuredisk.go:136] 
DRIVER INFORMATION:

Build Date: "2021-10-11T02:23:46Z"
Compiler: gc
Driver Name: disk.csi.azure.com
Driver Version: v1.8.0
Git Commit: 933715c5a3bd0476bdb3cda4bdf10715d4b48ae3
Go Version: go1.16
Platform: windows/amd64
Topology Key: topology.disk.csi.azure.com/zone

Streaming logs below:
I1209 06:54:44.769243    1644 azuredisk.go:139] driver userAgent: disk.csi.azure.com/v1.8.0 gc/go1.16 (amd64-windows)
I1209 06:54:44.782262    1644 azure_disk_utils.go:137] reading cloud config from secret kube-system/azure-cloud-provider
I1209 06:54:44.809750    1644 azure_auth.go:234] Using AZUREPUBLICCLOUD environment
I1209 06:54:44.810283    1644 azure_auth.go:119] azure: using client_id+client_secret to retrieve access token
I1209 06:54:44.810357    1644 azure_diskclient.go:67] Azure DisksClient using API version: 2021-04-01
I1209 06:54:44.810600    1644 azure.go:902] attach/detach disk operation rate limit QPS: 6.000000, Bucket: 10
E1209 06:54:44.810738    1644 safe_mounter_windows.go:396] failed to connect to csi-proxy v1beta with error: open \\.\\pipe\\csi-proxy-filesystem-v1beta1: The system cannot find the file specified.
F1209 06:54:44.810937    1644 azuredisk.go:175] Failed to get safe mounter. Error: open \\.\\pipe\\csi-proxy-filesystem-v1beta1: The system cannot find the file specified.
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc0000d8001, 0xc00032e000, 0xac, 0x18b)
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/klog/v2/klog.go:1026 +0xbf
k8s.io/klog/v2.(*loggingT).output(0x36a2c40, 0xc000000003, 0x0, 0x0, 0xc000211650, 0x0, 0x2e4bfd8, 0xc, 0xaf, 0x0)
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/klog/v2/klog.go:975 +0x1fb
k8s.io/klog/v2.(*loggingT).printf(0x36a2c40, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x27c2454, 0x25, 0xc000314430, 0x1, ...)
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/klog/v2/klog.go:753 +0x1a5
k8s.io/klog/v2.Fatalf(...)
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/klog/v2/klog.go:1514
sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.(*Driver).Run(0xc000188000, 0xc0000b606b, 0x18, 0x0, 0x0, 0x1)
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk/azuredisk.go:175 +0x698
main.handle()
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:94 +0x188
main.main()
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:73 +0xb5

goroutine 5 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x36a2c40)
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/klog/v2/klog.go:1169 +0x92
created by k8s.io/klog/v2.init.0
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/klog/v2/klog.go:420 +0xe5

goroutine 53 [IO wait]:
internal/poll.runtime_pollWait(0x21c528f3718, 0x72, 0x29d4700)
        /usr/local/go/src/runtime/netpoll.go:222 +0x65
internal/poll.(*pollDesc).wait(0xc0005981b8, 0x72, 0x360a700, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.execIO(0xc000598018, 0xc00021fb30, 0xf0, 0xc0005b4000, 0x20)
        /usr/local/go/src/internal/poll/fd_windows.go:175 +0x113
internal/poll.(*FD).acceptOne(0xc000598000, 0x1d0, 0xc0005b4000, 0x2, 0x2, 0xc000598018, 0xc0000a61a0, 0x21c2d241348, 0xc000033000, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:810 +0x9c
internal/poll.(*FD).Accept(0xc000598000, 0xc00021fce0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/internal/poll/fd_windows.go:844 +0x168
net.(*netFD).accept(0xc000598000, 0x30, 0x30, 0x21c2d241348)
        /usr/local/go/src/net/fd_windows.go:139 +0x85
net.(*TCPListener).accept(0xc0004ae000, 0xc00021fd78, 0xdbe8ff, 0x30)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x39
net.(*TCPListener).Accept(0xc0004ae000, 0x2642c20, 0xc000590900, 0x24d36c0, 0x367cb30)
        /usr/local/go/src/net/tcpsock.go:261 +0x6b
net/http.(*Server).Serve(0xc00014e0e0, 0x2a04df0, 0xc0004ae000, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2981 +0x29c
net/http.Serve(...)
        /usr/local/go/src/net/http/server.go:2529
main.serveMetrics(0x2a04df0, 0xc0004ae000, 0xe125e0, 0xc0004fad80)
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:120 +0xcc
main.serve.func1(0x2a04df0, 0xc0004ae000, 0x286ba70, 0xc0000441b0, 0xa)
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:111 +0x82
created by main.serve
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:109 +0x189

goroutine 70 [IO wait]:
internal/poll.runtime_pollWait(0x21c528f3630, 0x72, 0x29d4700)
        /usr/local/go/src/runtime/netpoll.go:222 +0x65
internal/poll.(*pollDesc).wait(0xc00013dd38, 0x72, 0x360a700, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.execIO(0xc00013db98, 0x286b2e0, 0xc00016b601, 0xc00016b6e0, 0xc0005c22c0)
        /usr/local/go/src/internal/poll/fd_windows.go:175 +0x113
internal/poll.(*FD).Read(0xc00013db80, 0xc00036ea80, 0x999, 0x999, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:441 +0x2f6
net.(*netFD).Read(0xc00013db80, 0xc00036ea80, 0x999, 0x999, 0x994, 0xc00036ea80, 0x5)
        /usr/local/go/src/net/fd_posix.go:55 +0x56
net.(*conn).Read(0xc000206090, 0xc00036ea80, 0x999, 0x999, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:183 +0x98
crypto/tls.(*atLeastReader).Read(0xc0004ae150, 0xc00036ea80, 0x999, 0x999, 0x994, 0xc000600000, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:776 +0x6a
bytes.(*Buffer).ReadFrom(0xc0003d0978, 0x29d0420, 0xc0004ae150, 0xdbbc6c, 0x252d960, 0x270be40)
        /usr/local/go/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc0003d0700, 0x21c526f4098, 0xc000206090, 0x5, 0xc000206090, 0x400)
        /usr/local/go/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0003d0700, 0x0, 0x0, 0x1)
        /usr/local/go/src/crypto/tls/conn.go:605 +0x12d
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc0003d0700, 0xc0005ce000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1276 +0x173
bufio.(*Reader).Read(0xc00046c300, 0xc00014e498, 0x9, 0x9, 0x129a2cb, 0xc00016bc78, 0xdb736b)
        /usr/local/go/src/bufio/bufio.go:227 +0x238
io.ReadAtLeast(0x29d0280, 0xc00046c300, 0xc00014e498, 0x9, 0x9, 0x9, 0xc00020c1f0, 0xe9e6e85cfbd400, 0xc00020c1f0)
        /usr/local/go/src/io/io.go:328 +0x8e
io.ReadFull(...)
        /usr/local/go/src/io/io.go:347
golang.org/x/net/http2.readFrameHeader(0xc00014e498, 0x9, 0x9, 0x29d0280, 0xc00046c300, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/golang.org/x/net/http2/frame.go:237 +0x8e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00014e460, 0xc0000d03c0, 0x0, 0x0, 0x0)
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/golang.org/x/net/http2/frame.go:492 +0xa8
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00016bfa8, 0x0, 0x0)
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/golang.org/x/net/http2/transport.go:1819 +0xe7
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000584780)
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/golang.org/x/net/http2/transport.go:1741 +0x76
created by golang.org/x/net/http2.(*Transport).newClientConn
        /root/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/golang.org/x/net/http2/transport.go:705 +0x6c5

**Environment**:
kubernetes 1.22.1
3 master linux machines ,2 worker linux machines, 1 worker windows machine and 1 newly added worker windows machine
windows machine is Standard_D8s_v3
Driver Version: v1.8.0

**Comment by andyzhangx** [comment]
@woshizhicainiaoluguo is it on AKS? if not, you need to set up csi-proxy service on Windows node.

**Comment by andyzhangx** [comment]
csi-proxy service should run on AKS nodes automatically, if it's not aks node, below is the manual way to start up csi-proxy on Windows
```console
> cd c:\k
Invoke-WebRequest https://acs-mirror.azureedge.net/csi-proxy/v1.0.2/binaries/csi-proxy-v1.0.2.tar.gz -OutFile csi-proxy.tar.gz;
tar -xvf csi-proxy.tar.gz
copy .\bin\csi-proxy.exe .
sc.exe create csiproxy binPath= "c:\k\csi-proxy.exe -windows-service -log_file=c:\k\csi-proxy.log -logtostderr=false"
sc.exe failure csiproxy reset= 0 actions= restart/10000
sc.exe start csiproxy
```
