### ISSUE TITLE
Ephemeral OS disk option does not work for GPU VM sizes

### ISSUE THREAD

**Issue by jpc** [Azure/AKS#2694]
According to documentation the AKS nodes should keep the whole OS on an ephemeral disk by default (which is both larger and much faster than the network disk):
https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#ephemeral-os

Unfortunately I cannot get it to work for a GPU nodepool (I am working in `westeurope`):

```
# az aks nodepool add --resource-group $PROJECT_NAME --cluster-name $PROJECT_NAME --name gpunp --node-vm-size Standard_NC6 --node-taints sku=gpu:NoSchedule --node-osdisk-type Ephemeral --aks-custom-headers UseGPUDedicatedVHD=true --enable-cluster-autoscaler --node-count 1 --min-count 0 --max-count 2
The behavior of this command has been altered by the following extension: aks-preview
(VMSizeDoesNotSupportEphemeralOS) The Virtual Machine size Standard_NC6 does not support Ephemeral OS disk.
Code: VMSizeDoesNotSupportEphemeralOS
Message: The Virtual Machine size Standard_NC6 does not support Ephemeral OS disk.

# az aks nodepool add --resource-group $PROJECT_NAME --cluster-name $PROJECT_NAME --name gpunp --node-vm-size Standard_NC6s_v2 --node-taints sku=gpu:NoSchedule --node-osdisk-type Ephemeral --aks-custom-headers UseGPUDedicatedVHD=true --enable-cluster-autoscaler --node-count 1 --min-count 0 --max-count 2
The behavior of this command has been altered by the following extension: aks-preview
(VMCacheSizeTooSmall) The virtual machine size Standard_NC6s_v2 has a cache size of 0 bytes, but the OS disk requires 137438953472 bytes. Use a VM size with larger cache or disable ephemeral OS.
Code: VMCacheSizeTooSmall
Message: The virtual machine size Standard_NC6s_v2 has a cache size of 0 bytes, but the OS disk requires 137438953472 bytes. Use a VM size with larger cache or disable ephemeral OS.
```

I've also tried some other VM sizes, without any luck. Both these VM sizes have an ephemeral disk at `/dev/sda` that is big enough and sits completely unused.

This is especially important for GPU VMs since many GPU workload containers are huge (several GB) which means that pulling and uncompressing images would greatly benefit from a fast locally attached SSD.

**Comment by jpc** [comment]
Let me just add that I've checked the VM sizes using code from this comment https://github.com/MicrosoftDocs/azure-docs/issues/61944#issuecomment-732102562 and the `Standard_NC6s_v2` does show up with `EphemeralOSDiskSupported == True`.

The `Standard_NC6` does not have the `EphemeralOSDiskSupported` flag despite having a perfectly capable 340GB ephemeral disk.

**Comment by alexeldeib** [comment]
See the discussion here: https://github.com/Azure/AKS/issues/2672

Particularly my previous comments https://github.com/Azure/AKS/issues/2068#issuecomment-775497175 and https://github.com/Azure/AKS/issues/2672#issuecomment-981128018

would you be okay to close this as a dupe of #2672 while we work on ephemeral os on temp disk? currently, AKS only support ephemeral os on cache disk, since ephemeral os on temp disk only recently GA'd. we're already working on it but it's likely to slip into january.

**Comment by alexeldeib** [comment]
btw, if you want to use `az vm list-skus` to verify what I said, the corresponding capability names for cache disk and temp disk are CachedDiskBytes and MaxResourceVolumeMB, respectively.

**Comment by jpc** [comment]
Hey, yes, it is the same issue. Thanks for looking into that. I will watch the #2672 instead
