### ISSUE TITLE
Tainted nodepool with min count 0 not scaling up nodes when a pod with toleration is scheduled.

### ISSUE THREAD

**Issue by sanjeebSubedi** [Azure/AKS#2695]
I have one default nodepool and I created a new tainted nodepool using this command 

![image](https://user-images.githubusercontent.com/51266822/145563294-47f5e707-8f52-4dc4-bb88-97922e84b2a7.png)

and scheduled a pod with the following yaml file.

![image](https://user-images.githubusercontent.com/51266822/145563907-445ae86a-0a02-474a-aa2d-06319452b821.png)

When I first create the nodepool the node count is 1 and the pod is scheduled as expected (pod is scheduled on the tainted nodepool). But once the autoscaler scales min count to 0, then the pod is scheduled on the default nodepool and not on the tainted nodepool. I donot think this is the expected behaviour.

**Comment by marwanad** [comment]
@sanjeebSubedi I think you're mixing your expectation of tolerations and selectors.

A toleration doesn't mean "schedule this pod on the tainted pool". It simply means - this pod may be scheduled on a tainted pool. The same pod will run just fine on the default nodepool which is untainted and hence why it got scaled up and the Kubernetes scheduler ran that just fine.

If you want the behaviour you specified, you need to use selectors.

**Comment by sanjeebSubedi** [comment]
@marwanad thank you for your prompt respose!
