### ISSUE TITLE
VM wrong cache size 

### ISSUE THREAD

**Issue by quyet-nguyen** [Azure/AKS#2699]
I'm setting up a new AKS cluster in SEA region and get hit with wrong cache size while trying to create Ephemeral node pool
Both Standard_D4d_v5 and Standard_D4ds_v5 report cache size of 0 bytes.

**Comment by phealy** [comment]
This is correct; neither of those VMs have a cache disk. They only have a temporary disk. While regular Azure VMs do support running an ephemeral OS disk [on the temp disk by using the `DiffDiskPlacement` option](https://docs.microsoft.com/en-us/azure/virtual-machines/ephemeral-os-disks#ephemeral-os-disks-can-now-be-stored-on-tempresource-disks), that feature is not yet available in AKS and thus these VMs cannot be deployed with ephemeral OS disk at this time.

When you're looking at the VM tables in Azure, they need to show a cache size to support ephemeral OS disk in AKS at this time. Compare the [Standard_D8s_v3](https://docs.microsoft.com/en-us/azure/virtual-machines/dv3-dsv3-series#:~:text=16-,16000/128%20(200),-16000/400), which shows a cache size of 200GB (the number in parentheses in the Max cached and temp storage throughput column).

Please see #2672 for further updates on when `DiffDiskPlacement` will be available in AKS.
