### ISSUE TITLE
Cluster autoscaler fail to scale up with the stable instance-type node selector

### ISSUE THREAD

**Issue by oscar60310** [Azure/AKS#2700]
**What happened**:
The pods with node selector "node.kubernetes.io/instance-type" don't trigger autoscaler scale-up, but pods with node selector "beta.kubernetes.io/instance-type" do.

Pods with `node.kubernetes.io/instance-type=Standard_E2s_v3` node selector:
```
│ Events:                                                                                                                                      │
│   Type     Reason             Age   From                Message                                                                              │
│   ----     ------             ----  ----                -------                                                                              │
│   Warning  FailedScheduling   17s   default-scheduler   0/3 nodes are available: 3 node(s) didn't match Pod's node affinity.                 
│   Warning  FailedScheduling   17s   default-scheduler   0/3 nodes are available: 3 node(s) didn't match Pod's node affinity.                
│   Normal   NotTriggerScaleUp  14s   cluster-autoscaler  pod didn't trigger scale-up: 2 node(s) didn't match Pod's node affinity
```
Pods with `beta.kubernetes.io/instance-type=Standard_E2s_v3` node selector:
```
│ Events:                                                                                                                                      │
│   Type     Reason            Age   From                Message                                                                               │
│   ----     ------            ----  ----                -------                                                                               │
│   Warning  FailedScheduling  17s   default-scheduler   0/3 nodes are available: 3 node(s) didn't match Pod's node affinity.                  
│   Warning  FailedScheduling  17s   default-scheduler   0/3 nodes are available: 3 node(s) didn't match Pod's node affinity.                  
│   Normal   TriggeredScaleUp  7s    cluster-autoscaler  pod triggered scale-up: [{aks-xxxxxxx-12531210-vmss 0->1 (max: 5)}]
```

**What you expected to happen**:
The beta node label is deprecated since Kubernetes [1.17](https://kubernetes.io/docs/reference/labels-annotations-taints/#beta-kubernetes-io-instance-type-deprecated), and the nodes created by node pools have the new label "node.kubernetes.io/instance-type". So I think autoscaler should recognize the new one.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a node pool in user mode with instance type "Standard_E2s_v3".
2. Set the node pool to Autoscale with range 0 ~ 5.
3. Deploy a pod with node selector node.kubernetes.io/instance-type=Standard_E2s_v3 and check the behavior.
4. Deploy a pod with node selector beta.kubernetes.io/instance-type=Standard_E2s_v3 and check the behavior.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.7

**Comment by marwanad** [comment]
@oscar60310 Fix released a week ago or so. Please reopen if you're still hitting the issue.

**Comment by oscar60310** [comment]
Hi @marwanad this issue has been resolved in our clusters, thanks!
