### ISSUE TITLE
A similar issue occurs when attempting to use a subnet created within an ARM template.  In this case the add-on is defined within the ManagedCluster resource as:

### ISSUE THREAD

**Issue by Naveen080** [Azure/AKS#2701]
A similar issue occurs when attempting to use a subnet created within an ARM template.  In this case the add-on is defined within the ManagedCluster resource as:

"ingressApplicationGateway": {
                        "enabled": true,
                        "config": {
                            "applicationGatewayName": "[variables('appGwName')]",
                            "subnetId": "[variables('gwSubnetId')]"
                            
However in all cases this results in a validation error on the template:
"message": "IngressApplicationGateway addon cannot find subnet <subnet reference>

Alternatively if you do not define the subnet resource and use subnetCIDR in the addon properties this works as expected and creates the application gateway and the subnet.

_Originally posted by @petegrimsdale in https://github.com/Azure/AKS/issues/2047#issuecomment-804919859_

**Comment by phealy** [comment]
Could you please provide an example ARM template? I suspect you may be running into a problem with template ordering, where the subnet is not properly being created before the AKS resource is validated. Do you have a `dependsOn` in your AKS resource for the subnet?
