### ISSUE TITLE
Use Azure Policy to deploy an OPA constraint with enforcementAction: warn

### ISSUE THREAD

**Issue by ThomasEhling** [Azure/AKS#2703]
**What happened**: When deploying an OPA constraint with an azurePolicy of effect "audit", the enforcementAction field is overwritten to "dryrun".

**What you expected to happen**: The constraintTemplate and constraint are deployed with the field "enforcementAction" set to "warn"

**How to reproduce it (as minimally and precisely as possible)**:
   - Create an azure policy with effect "Audit" to deply an OPA constraintTemplate and constraint.
   - Write an easy "violation" block in the constraintTemplate rego.
   - Set the field "spec.enforcementAction: warn" in the constraint
   - Save and assign the Azure policy to an AKS cluster
   - Wait for 20-30min for the policy to be applied
   - Run: "kubectl get constraints" to check that the constraint is here
   - Trigger the violation rule set in the template --> No warning !
   - Run "kubectl get <YOUR_CONSTRAINT_ID> -o yaml"
   - See that in the Status.violations list, all items have "enforcementAction: dryrun"

**Anything else we need to know?**: Our Final goal is to rise a warning whenever an ingress is deployed without some specific fields.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```shell
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"d062c7ef8a88e89e5f28f1c1146bd707d00d4881", GitTreeState:"clean", BuildDate:"2021-11-01T16:41:06Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) None,  ony Azure Hello wold app: mcr.microsoft.com/azuredocs/aks-helloworld:v1
- Others: x

**Comment by ThomasEhling** [comment]
If I disable the Azure policy add-on and install my own gatekeeper my rule is working and the warning are shown:
![image](https://user-images.githubusercontent.com/30614868/146203467-c8ae09e6-1871-4d5d-9a8f-dd3252d07adc.png)

**Comment by alftio** [comment]
@miwithro Please help.

**Comment by nehakulkarni123** [comment]
Hi @ThomasEhling, this behavior is by design as we do not currently support enforcementAction = 'warn'. The supported enforcementActions are 'deny' and 'dryrun' - which correspond as following to the policy effects we have:

policy effect = audit --> enforcementAction = dryrun

policy effect = deny --> enforcementAction = deny

To achieve your goal of getting a warning whenever an ingress is deployed without some specific fields, you can update the policy effect parameter to 'deny'.

**Comment by ThomasEhling** [comment]
Hi @nehakulkarni123 !
Thank you for answering.

To be honest, we suspected from the start that this was a feature request.

Sure, we've tried and managed to deploy with "deny" and "dryrun", but that's not the same as "warn".

Our business model is PaaS, so we think it's really important to be able to notify our client without denying them the ability to deploy their resources.

The feature request is really just to consider the "spec.enforcementAction: warn" field in the constraint.
Maybe keep the defaults and override it if specified in the constraint.

It should be easy to implement and valuable to the community.

Do not hesitate to contact me if necessary.

**Comment by nehakulkarni123** [comment]
Thanks @ThomasEhling for the feedback.

**Comment by nehakulkarni123** [comment]
Hi [ThomasEhling](https://github.com/ThomasEhling)-- our team is currently investigating a feature related to your question, and we'd love to share our thinkings-- if interested, can you please email us at policypm@microsoft.com so I can set up some time to discuss? Thanks!
