### ISSUE TITLE
Release Announcement contains wrong date about Kubernetes 1.19 removal

### ISSUE THREAD

**Issue by amarkevich** [Azure/AKS#2704]
**What happened**:

Release Announcement [1] contains wrong date: 
`Kubernetes 1.19 will be removed on 2021-01-31.`

1. https://github.com/Azure/AKS/releases

**What you expected to happen**:

`Kubernetes 1.19 will be removed on 2022-01-31.`

2. https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar

**Comment by andyzhangx** [comment]
fixed: https://github.com/Azure/AKS/releases/tag/2021-12-09

**Comment by amarkevich** [comment]
should be fixed in other releases:
https://github.com/Azure/AKS/releases/tag/2022-01-06
https://github.com/Azure/AKS/releases/tag/2022-01-13

**Comment by miwithro** [comment]
resolved.  Thanks.
