### ISSUE TITLE
Enable SMB 3.1.1 multichannel on AKSUbuntu-1804containerd

### ISSUE THREAD

**Issue by datwelk** [Azure/AKS#2706]
**What happened**:
An AKS node running AKSUbuntu-1804containerd-2021.07.25 with 5.4.0-1055-azure kernel uses SMB version 3.0.

**What you expected to happen**:
If an Azure File Storage account has SMB multichannel enabled, I expect the AKS cluster nodes to also use SMB 3.1.1, which is a minimum requirement from the server side to use the SMB multichannel functionality (see: [here](https://docs.microsoft.com/en-gb/azure/storage/files/storage-files-smb-multichannel-performance#limitations)) 

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
How do I enable SMB multichannel on Linux AKS node clients?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19
- Size of cluster (how many worker nodes are in the cluster?): N/A
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): microservices
- Others: N/A

**Comment by datwelk** [comment]
Kubernetes Volume docs specifically mention only SMB 2.1 and 3.0: https://kubernetes.io/docs/concepts/storage/volumes/#azurefile. 

This could explain why 3.0 is used. Does SMB 3.1.1 require the azureFile CSI driver over the 'in-tree plugin'?

**Comment by andyzhangx** [comment]
if you are using Azure File CSI driver on aks 1.21+, it's already using `vers=3.1.1`

**Comment by andyzhangx** [comment]
it seems `Linux version 5.4.0-1063-azure` does not support `-o multichannel` mount options:
```
[914489.007018] CIFS: Attempting to mount //xxx.file.core.windows.net/pvc-359e202c-9bb3-4217-b022-480a863af014
[914489.007054] CIFS: Unknown mount option "multichannel"
[914493.542743] IPv6: ADDRCONF(NETDEV_CHANGE): azv784e8f3bb062: link becomes ready
[914493.542777] IPv6: ADDRCONF(NETDEV_CHANGE): azv784e8f3bb06: link becomes ready
[914493.543530] eth0: renamed from azv784e8f3bb062
[914505.124755] CIFS: Attempting to mount //xxx.file.core.windows.net/pvc-359e202c-9bb3-4217-b022-480a863af014
[914505.124802] CIFS: Unknown mount option "multichannel"
```

**Comment by datwelk** [comment]
It seems this was added to the linux 5.5 kernel [[source](https://wiki.samba.org/index.php/LinuxCIFSKernel#5.5_kernel_.28module_version_2.24.2C_released_January_26th.2C_2020._61_changesets.29)]

Would it be possible to double check this with the team responsible for the Azure linux kernel, and ask when the changes from 5.5 will be incorporated?

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/1571141/146739805-7e9c44f1-fb5d-4a2e-af8e-1ea3cea5c908.png">

**Comment by andyzhangx** [comment]
5.5+ will come only with 20.04, we will support 20.04 in near future, thanks.
