### ISSUE TITLE
AKS nodes fail to start new containers/processes after approximately 400-500 containers because containerd uses default value of TasksMax=512

### ISSUE THREAD

**Issue by sandersaares** [Azure/AKS#2709]
**What happened**: After deploying approximately 400-500 containers to an AKS node, the node becomes unstable and is not able to start new containers or additional processes in existing containers.

**What you expected to happen**: Nodes can start as many containers as CPU/RAM limits permit.

**How to reproduce it (as minimally and precisely as possible)**:

Deployment template: [app.yml.txt](https://github.com/Azure/AKS/files/7762375/app.yml.txt)

1. Set up a new AKS cluster. Suggested settings for easy repro:
    * Single 3x D32 nodepool (shared by system and user).
    * Kubernetes 1.22.2
    * Azure CNI
    * Max pods per node 250
2. Deploy attached YAML from above (modified AKS quick start example).
    * This deploys 90 replicas, each with 10 containers (total 900 containers).
3. Observe that pods started correctly (containers per node = `900/3=300`).
4. Modify `replicas: 90` in YAML to `replicas: 200`.
    * Total 2000 containers, 666 per node.
5. Deploy YAML.
6. Observe that container creation fails after approximately 400-450 containers per node is reached.
7. Observe that starting new processes in containers (with `kubectl exec`) also typically fails in this state.

Typical error messages as seen in "describe pod" output: 

* Error: failed to create containerd task: ttrpc: closed: unknown
* Failed to inspect image "mcr.microsoft.com/azuredocs/azure-vote-front:v1": rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: connection refused"
* Failed to inspect image "mcr.microsoft.com/azuredocs/azure-vote-front:v1": rpc error: code = Unknown desc = server is not initialized yet

Typical error message in "exec" output: error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "ad388a37c6df5f2289c1db3bb3e5e46d88756e25138fa83622afc69015f9cdda": OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: process_linux.go:99: starting setns process caused: fork/exec /proc/self/exe: resource temporarily unavailable: unknown

**Anything else we need to know?**:

Node image version: AKSUbuntu-1804gen2containerd-2021.12.07

The root cause of the problem appears to be that systemd enforces a limit of 512 "tasks" per service by default, which limits containerd to starting 512 child processes.

![image](https://user-images.githubusercontent.com/9914262/147087647-77f954db-0526-41c5-bb6a-5611bc2db21f.png)

If you modify `/etc/systemd/system/containerd.service` to add `TasksMax=1000000` to `[Service]` then the problem is fixed and the full capacity of the node can be utilized.

![image](https://user-images.githubusercontent.com/9914262/147086990-2ddff945-82ae-4bc7-84ce-d7e362fe63ff.png)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.2
- Size of cluster (how many worker nodes are in the cluster?): 3x D32
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): quick start "azure vote app" with multiple containers per pod

**Comment by alexeldeib** [comment]
note that there is some other pid accounting work we still need to do (e.g. kube-reserved and raise default node pid_max)
