### ISSUE TITLE
UDR outbound type cluster has working egress path automatically, why?

### ISSUE THREAD

**Issue by jack4it** [Azure/AKS#2710]
**What happened**:

Created a cluster with `UDR` outbound type and `kubenet` and `calico` network policy. It by default, automatically has a successful egress path. A simple command `curl ifconfig.me` returned a good Azure public IP which is not created by me.

**What you expected to happen**:

Egress should fail until I set the `0.0.0.0/0` route pointing to an NVA

**How to reproduce it (as minimally and precisely as possible)**:

Simply create a cluster with the above config

**Anything else we need to know?**:

After adding `0.0.0.0/0` route, it did force the egress through the NVA.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21
- Size of cluster (how many worker nodes are in the cluster?): 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by phealy** [comment]
Azure route tables do not override routes unless they have an equal or more specific prefix. If you don't have a route for 0.0.0.0/0 in the route table (which a newly created UDR cluster will not have, as the RT is empty), Azure routing falls back to the [default public outbound behavior](https://docs.microsoft.com/en-us/azure/virtual-network/ip-services/default-outbound-access).

If you want the cluster to be using your NVA by default, you need to use bring-your-own-subnet (doc links: [kubenet](https://docs.microsoft.com/en-us/azure/aks/configure-kubenet#bring-your-own-subnet-and-route-table-with-kubenet), [Azure CNI](https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#deployment-parameters)).

**Comment by jack4it** [comment]
thx @phealy for the response. In this case, the cluster did use bring-ur-own-subnet, which triggered the confusion. A subnet we created before creating the cluster and it doesn't have route/NVA set up. But still have successful egress. So it's weired to me
