### ISSUE TITLE
BYO Private DNS vNet Link

### ISSUE THREAD

**Issue by mohamedsaif** [Azure/AKS#2711]
**What happened**:
With BYO private DNS when creating private AKS, the provider creates vNET link between AKS vnet and the central private DNS which:
1. Is duplicate incase of using custom DNS servers and already the existing private DNS zone linked with the hub vnet (which includes DNS server(s) configured with forwarders)
2. Require AKS MI to have elevated "Network Contributor" at the vnet level compared to only subnet scope

**What you expected to happen**:
I suggest that BYO private DNS would assume that any needed vnet linking already in place so no association would be made by the AKS provider using the AKS MI

**How to reproduce it (as minimally and precisely as possible)**:
Create private AKS with --private-dns-zone $AKS_PRIVATE_DNS_ID pointing to existing private DNS zone

**Anything else we need to know?**:

**Environment**:
az version: 2.29.0

**Comment by miwithro** [comment]
@mohamedsaif you can do this today with --private-dns-zone.  It has to be in a specific format though to work with AKS.  If the customer needs something outside of the below format it will not work.

"CUSTOM_PRIVATE_DNS_ZONE_RESOURCE_ID", which requires you to create a Private DNS Zone in this format for Azure global cloud: privatelink.<region>.azmk8s.io or <subzone>.privatelink.
