### ISSUE TITLE
Can existing static IP addresses be assigned?

### ISSUE THREAD

**Issue by LoungeFlyZ** [Azure/AKS#272]
We have a number of static IP address already allocated in another resource group.  It looks like these need to be in the MC_ resource group in order for services to be able to use them.

Will moving the static IP addresses into the MC_ resource group be enough in order for these to be picked up?

**Comment by shahiddev** [comment]
That should do it but be aware of #247 if you're using 1.9.2

**Comment by slack** [comment]
Resource move should work, be sure to test in a non-production environment first!

**Comment by LoungeFlyZ** [comment]
Thanks @slack ! that is great news.

**Comment by LoungeFlyZ** [comment]
hey @slack would one be crazy to use a separate Azure LB that is separate from AKS's provisioned one that "owns" the static IPs and just port forwards to the IPs assigned to the AKS LB?  

The reason is there seems to be some magic in the AKS LB config to pick up the IP address ... and i'm worried it will complicate our setup.  It also seems "managed" and i'm really worried about something going wrong, that resource group being deleted and then our static IPs are gone (really really bad!).

Asking here in the hope that others might find it helpful in the future.
