### ISSUE TITLE
can not create multiple nodepools simultaneously via terraform

### ISSUE THREAD

**Issue by yuzsun** [Azure/AKS#2720]
**What happened**:  We are configuring AKS Cluster and Node Pools with Terraform azurerm provider. If we create multiple pools simultaneously (Terraform has a concurrency level of 10 per default), we often get error messages from Azure for one or more pools. The failing pools have status “Failed” in the Azure GUI, but I don’t see any failure logs in the troubleshooting tab. It seems that the pool itself is configured, but the scale set could not be created. Following is an actual error message I get from Azure during pool creation:
 
│ Error: waiting for completion of Managed Kubernetes Cluster Node Pool "basis" (Resource Group "dlp-runnerpool-labcluster-iac-sandbox-rg"): Code="ReconcileVMSSAgentPoolFailed" Message="We are unable to serve this request due to an internal error, Correlation ID: xxxxxxxxxxxxxxx, Operation ID: xxxxxxxxxxxxxxxxxxx, Timestamp: 2021-12-14T07:12:51Z."
 
To work around the issue, I have to remove the pool manually in the Azure GUI and re-run Terraform apply with the exact same configuration. I repeat this process until all pools are up. That means it is not a configuration issue but it seems to be an issue with pool-creation in Azure. Our cluster configuration has +/- 20 pools on one cluster.

I have to mention that the problem is not always exactly the same. Sometimes all pools are created without errors, sometimes we got 1 pool failing and sometimes we have several pools that fail during creation. Seems to be a timing or concurrency issue during pool creation.

**What you expected to happen**: successfully created multiple pools simultaneously (Terraform has a concurrency level of 10 per default), or know a specific limit that how many nodepools we can create simultaneously at one time.

**How to reproduce it (as minimally and precisely as possible)**: created multiple pools simultaneously (Terraform has a concurrency level of 10 per default)

**Anything else we need to know?**: From the cluster backend logs, we could see there are “RetryableError”  during node provisioning in the AKS RP. However, in CRP, there were errors calling NRP, the subnet was in updating status when provisioning nodepool. This may be because when provisioning the nodepool, other nodepools in the cluster were also using the same subnet. Thus the subnet was in updating status, and the nodepool failed to provision. Looks this is a synchronize issue among AKS, CNP and NRP.
 
We also raised SR 2112160040002997 for the issue.

**Environment**:
- Kubernetes version (use `kubectl version`):  1.21.2 
- Size of cluster (how many worker nodes are in the cluster?) 19+ nodepool

**Comment by phealy** [comment]
(please note that I do see you already have a support request open - the SR tag just sets the issue to the proper state. thanks!)
