### ISSUE TITLE
Is it possible to change PV permissions after used?

### ISSUE THREAD

**Issue by 64J0** [Azure/AKS#2723]
**What happened**:

I have created a PV using a StorageClass with the following configuration:

```yaml
mountOptions:
  - dir_mode=0544
  - file_mode=0544
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload
```

But now I want to change the `dir_mode` and `file_mode` but it's not possible apparently. I'm trying to apply a configuration with this format:

```yaml
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload
```

**What you expected to happen**:

To change the Azure File permissions to 0777 when I tried to submit the changes.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by andyzhangx** [comment]
you could run `kubectl edit pv pv-name` and change mountOptions directly, and depends on the azure file driver you are using, if it's in-tree driver, you could simply restart pod, remount would happen with new mountOptions; and if it's csi driver, you need to delete all pods that using this PV and then start pods, remount would happen with new mountOptions

**Comment by 64J0** [comment]
Ok, thanks for the answer @andyzhangx
