### ISSUE TITLE
Issues experience using CSI storage drivers  while using storage class managed-premium and everything works as expected, however when thei changes to managed-csi-premium, containers start crashing

### ISSUE THREAD

**Issue by saavilad** [Azure/AKS#2724]
**What happened**:
they are using storage class managed-premium and everything works as expected, however when he changes to managed-csi-premium, containers start crashing

**What you expected to happen**:
change storage class an keep the containers working

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Issues experience using CSI storage drivers

they are using storage class managed-premium and everything works as expected, however when he changes to managed-csi-premium, containers start crashing

 

Current cluster version: 1.20.9

they are following steps to install the driver
 
We’ve followed Microsoft procedures to install CSI drivers on a existing cluster:  https://docs.microsoft.com/en-us/azure/aks/csi-storage-drivers#install-csi-storage-drivers-on-an-existing-cluster-with-version--121

 

 

They are using Helm now to modify the storage class yaml
Install CSI storage drivers on a new cluster with version < 1.21

https://docs.microsoft.com/en-us/azure/aks/csi-storage-drivers#install-csi-storage-drivers-on-a-new-cluster-with-version--121
**Environment**:
- Kubernetes version (use `kubectl version`): <html>
<body>

1.20.9
--

</body>
</html>
- Size of cluster (how many worker nodes are in the cluster?) 
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others: AKS

**Comment by andyzhangx** [comment]
changes to storage class won't affect existing PV, pod or driver, I think that's a coincidence. If driver pod is crashing, pls provide driver pod events and logs, follow by: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/csi-debug.md
