### ISSUE TITLE
For better Infiniband support singlePlacementGroup=true needs to be settable in VMSS

### ISSUE THREAD

**Issue by dgruber** [Azure/AKS#2725]
**What happened**:

Infiniband connection does not work reliable on medium sized clusters. Infiniband works very well on 
AKS node pools with a size up to 3 nodes (HB120v3). Within the VMSS configuration singlePlacementGroup=false
is set to support up 1000 nodes for AKS. But this setting is in conflict with HPC recommendation for
getting Infiniband correctly working on the nodes. See https://docs.microsoft.com/en-us/azure/virtual-machines/sizes-hpc

"Virtual machine scale sets - In a virtual machine scale set, ensure that you limit the deployment to a single placement group for InfiniBand communication within the scale set. For example, in a Resource Manager template, set the singlePlacementGroup property to true. Note that the maximum scale set size that can be spun up with singlePlacementGroup=true is capped at 100 VMs by default."

Default tcp/ip network works fine.

**What you expected to happen**:

Infiniband should work correctly, i.e. all nodes within the VMSS should be able to communicate via IB and not just
subsets with each other.

**How to reproduce it (as minimally and precisely as possible)**:

Create AKS cluster and check singlePlacementGroup parameter.

**Anything else we need to know?**:

There should be a parameter or at least a AKS customer header allowing to set singlePlacementGroup=true of a VMSS within AKS.

We use the Go API "github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-10-01/containerservice"

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.21.7 
- Size of cluster (how many worker nodes are in the cluster?) 8 x HB 120 v3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others: We installed the Mellanox IB driver on all nodes.

**Comment by palma21** [comment]
SPG is now on automatically on for infiniband-capable SKUs

**Comment by dgruber** [comment]
Good day for HPC on Kubernetes :) Thank you very much! 

We tested it with the feature flag and we got great results with up to 19GB/sec throughput and 2 microseconds of latency measured between 6 containers on 6 different hosts in an AKS cluster. We have not seen any IB connection problem anymore.
