### ISSUE TITLE
Azure Defender Security Profile metadata lost during deployment

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS#2740]
**What happened**:
Using a Bicep/Arm deployment  to deploy a new AKS cluster, including the properties.securityProfile to enable Azure Defender.
This can be confirmed by inspecting the az deployment group what-if output;
![image](https://user-images.githubusercontent.com/17914476/150088989-a25ded83-c374-42ba-9367-b556a40faa28.png)

The deployment succeeds, and the Microsoft Defender for Containers is indeed enabled. 
(This is not through Defender environment policy, as I've explicitly disabled that.)

However when I check the AKS metadata with `az aks show`, i can see that the securityProfile is null.
![image](https://user-images.githubusercontent.com/17914476/150090158-9d5e7fbe-41a7-4bf7-9a49-93faf4a149ff.png)

**What you expected to happen**:
The securityProfile metadata to persist, to be consistent with the what-if output

**How to reproduce it (as minimally and precisely as possible)**:
Clone the [gb-defender branch](https://github.com/Azure/Aks-Construction/tree/gb-defender), then run 
```bash
az deployment group create -g dfndr -f bicep/main.bicep -p .github/workflows_dep/regressionparams/defender.json
```

**Anything else we need to know?**:
No problems are reported during deployment.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by miwithro** [comment]
@mayaherskovic

**Comment by mayaherskovic** [comment]
@nawolfin

**Comment by tzachiabo** [comment]
Hi @Gordonby,

Thanks for reaching us, and sorry for the late response

It is not possible to install the security profile on the aks cluster's creation phase,
Installing the security profile on a new cluster must be done in two separate steps:
	1) Creating the new aks cluster
	2) Updating that cluster to contain security profile
	
We have future plans to support the installation of SecurityProfile on the aks cluster creation phase.

Thanks
Zahi

**Comment by Gordonby** [comment]
Thanks @tzachiabo 

I think most people will install Defender via policy, however the fact that the defender properties are in the arm metadata (but not used) makes it inconsistent with how many would expect it to work.

Do you know when we can expect installation of the securityprofile on cluster creation?
