### ISSUE TITLE
Preserve private endpoint when stop and starts an AKS cluster

### ISSUE THREAD

**Issue by arcezd** [Azure/AKS#2745]
**What happened**:
We need to stop and start our Development aks cluster daily, just to avoid costs when it's not in use, this cluster is a private cluster, so we are accessing the Kubernetes API Server through a private endpoint.
We have a third-party network virtual appliance firewall solution deployed at our tenant to inspect/allow/block traffic between vnets or even on-premise to Azure.

According to the private endpoints documentation (and our tests), we need to register every private endpoint IP to the Azure Route Table to force the traffic to pass through the firewall.
[Use Azure Firewall to inspect traffic destined to a private endpoint](https://docs.microsoft.com/en-us/azure/private-link/inspect-traffic-with-azure-firewall)

We know that according to the Documentation: [Stop and Start an Azure Kubernetes Service (AKS) cluster](https://docs.microsoft.com/en-us/azure/aks/start-stop-cluster):
- **The customer provisioned PrivateEndpoints linked to private cluster need to be deleted and recreated again when you start a stopped AKS cluster.**

So any workaround or any chance to create a feature request to preserve the private endpoint and don't need to recreate it every time we need to stop and start the cluster?

**What you expected to happen**:
We expect any option to preserve the IP of the private endpoint when we stop and starts the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy an AKS with a private endpoint, and stop and start the cluster.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
4 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by olsenme** [comment]
@phealy

**Comment by asaf-upstream** [comment]
Any updates on this?
It will help our cause as well

**Comment by arcezd** [comment]
Any chance we got any response here? This is starting to be a major problem for our non-production workloads

**Comment by kethahel99** [comment]
Hello! Please can you provide an update on this? It is a much needed feature

**Comment by kethahel99** [comment]
@andyzhangx , @djdongjin , @raghulmsft, @Azure apologies, but is anyone working on/considering this request?

**Comment by teeroddesigns** [comment]
This also caused us several hours of work to retrace and reconfigure things

**Comment by joeybdub** [comment]
Would be good to understand if there is a potential workaround on this. Seeing disruption with endpoint connectivity on private AKS using calico!

**Comment by asaf-upstream** [comment]
@joeybdub We are using a python cron script that checks and update the vpn entry every 24h to workaround this.... sadly could not find a better solution.

**Comment by joeybdub** [comment]
Thanks @asaf-upstream could you elaborate more on what the python script is doing?

**Comment by asaf-upstream** [comment]
@joeybdub sure, we 1st get the new nic name and then new private ip(
https://learn.microsoft.com/en-us/cli/azure/network/private-endpoint?view=azure-cli-latest
https://learn.microsoft.com/en-us/cli/azure/network/nic/ip-config?view=azure-cli-latest#az-network-nic-ip-config-list
):

```
nic_id=az network nic ip-config list -g MyResourceGroup
az network nic ip-config list--nic-name $nic_id -g MyResourceGroup
```

2nd part will use the vpn's product api's endpoints to update the ip entry of the resource..

Hope that helps.

**Comment by asaf-upstream** [comment]
@joeybdub our network plugin is Kubenet, not sure how much a difference does it make if you see the same behavior..

**Comment by joeybdub** [comment]
Thanks @asaf-upstream

**Comment by maartengo** [comment]
The need to recreate the private endpoint is the main reason why we don't stop our AKS clusters. We could of course put effort into creating our own version of the reconfiguration script, but I would much rather have a supported/built-in solution from Microsoft.

My use cases:
* Saving costs for customers who only use their clusters during working hours
* Saving costs for our own development environments by only turning the clusters on when something needs to be developed (sort of a JIT cluster provisioning).

**Comment by levimm** [comment]
you can use private cluster with APIServer Vnet Integration. The private ip will be reserved during stop/start.
https://learn.microsoft.com/en-us/azure/aks/api-server-vnet-integration#deploy-a-private-cluster

**Comment by rouke-broersma** [comment]
> you can use private cluster with APIServer Vnet Integration. The private ip will be reserved during stop/start.
> https://learn.microsoft.com/en-us/azure/aks/api-server-vnet-integration#deploy-a-private-cluster 

We connect from remote vnets without line of sight so that doesn't solve our problem.

**Comment by orenzp** [comment]
Just open a ticket about it to Azure support to see if they have something planned to solve this issue.

**Comment by kethahel99** [comment]
> > you can use private cluster with APIServer Vnet Integration. The private ip will be reserved during stop/start.
> > https://learn.microsoft.com/en-us/azure/aks/api-server-vnet-integration#deploy-a-private-cluster 
> 
> We connect from remote vnets without line of sight so that doesn't solve our problem. 

Maube you can try UDR when ingressing to vnet\local FW from remote (I'm guessing peered?) vnet?
Like e.g.
Source address (remote) 10.34.0.0/24
Next hop = firewall IP in local vnet
Hop type = network virtual appliance (firewall) 
Then in the firewall you allow traffic from thst source cidr to the aks api server private IP?

**Comment by rouke-broersma** [comment]
> > > you can use private cluster with APIServer Vnet Integration. The private ip will be reserved during stop/start.
> > > https://learn.microsoft.com/en-us/azure/aks/api-server-vnet-integration#deploy-a-private-cluster 
> > 
> > We connect from remote vnets without line of sight so that doesn't solve our problem. 
> 
> Maube you can try UDR when ingressing to vnet\local FW from remote (I'm guessing peered?) vnet?
> Like e.g.
> Source address (remote) 10.34.0.0/24
> Next hop = firewall IP in local vnet
> Hop type = network virtual appliance (firewall) 
> Then in the firewall you allow traffic from thst source cidr to the aks api server private IP?

Nope, no peering. **No line of sight.** You can create private endpoints to any vnet anywhere in azure, totally disconnected networks.

**Comment by dtu-ruth** [comment]
What is the status of this issue?

**Comment by amar-mandai** [comment]
Whats the status of this issue?
 
Due to this, start and stop feature is almost unusable in case of private clusters.

**Comment by victormartinsantiago** [comment]
Any updates on this issue? Having to re-provision the private endpoint every time the cluster stops, is a pain in the ass

**Comment by levimm** [comment]
From AKS perspective, we have to recreate the private endpoint during stop/start in order to build the private connection. Right now, we don't have any future plan on private v1 cluster (implemented by private link).
