### ISSUE TITLE
References to deleted nodepool scalesets causing cluster health to show as degraded across multiple clusters - started on 1/13/22

### ISSUE THREAD

**Issue by frachel** [Azure/AKS#2747]
AKS: 1.21.2

Just recently 5 of our clusters started getting the following in the "Resource Health"

```
"At Friday, January 21, 2022, 6:32:54 AM EST, the Azure monitoring system received the following information regarding your Azure Kubernetes Service (AKS):
We were unable to retrieve the list of running nodes due to service principal authorization failures."
```

We are using managed identities, so this didn't make much sense. 

I opened a support ticket and what the MS support person found was that in all of our clusters showing this error he was seeing on his end the following type of error (obviously the resource and VMSS name differ for each cluster)

```
"The Resource 'Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-37471166-vmss' under resource group 'MC_pecb-rg_pecb-aks_eastus' was not found"
```

When these AKS clusters were originally created (year ago or so) it used the default "nodepool1" nodepool. However, since then we've come up with a different nodepool strategy and on new clusters we start with different nodepool names.

On existing clusters we created new nodepools with our naming standards, and then deleted the original "nodepool1" nodepool. Therefore, in the above error, "nodepool1" one was deleted, which obviously deleted the "aks-nodepool1-37471166-vmss" scaleset, but something is clearly still referencing it.

The commonality with all our clusters getting this error is that we deleted a nodepool (either via the portal or the cli) but something on the backend is still holding a reference to it.

This started on 1/13/22 on 5 clusters.. no issues before that, and they've been running for probably a year or more.

**Comment by frachel** [comment]
Update: doing an "aks upgrade" to the *same* version seems to fix the health alerts (i assume that even though nothing actually gets upgraded, the process probably does some "re-evaluation" and sync/cleanup of config settings on the backend?).

**Comment by phealy** [comment]
That triggers a reconcile of the cluster, yes. An easier way is just to use `az resource update --id <clusterResourceId>` - that will trigger the same action (basically it does a GET on the cluster object then just PUTs it back; this triggers a reconciliation).

When you deleted the nodepool, did you do so via `az aks nodepool delete`/the portal node pool screen, or did the VMSS get directly removed via `az vmss delete`?

**Comment by frachel** [comment]
The nodepools were deleted either via the portal nodepool screen or the "az aks nodepool delete", nobody every does anything to the VMSS directly.

**Comment by kipusoep** [comment]
We have the same issue; created a new nodepool with a different naming strategy and removed the default nodepool. I think that was approx. 4 months ago.
And yes, for us it also started on the 13th of January: January 13, 2022 15:53 UTC

**Comment by chmill-zz** [comment]
We're aware of the false positive message from resource health regarding the missing node pools. A fix is rolling out now and shouldn't take any action on your part

**Comment by chmill-zz** [comment]
Fix has been rolled out globally
