### ISSUE TITLE
[Question] Support for nvidia gpu operator?

### ISSUE THREAD

**Issue by padrian2s** [Azure/AKS#2748]
Hi AKS team,
Is there any plan to support NVIDIA GPU Operator on AKS? GPU partitioning is one of the sweet spot in MLOps. The project itself has a lot of traction (30+ releases over the last two years) and the latest version is 1.9.

**Comment by olsenme** [comment]
@palma21

**Comment by alexeldeib** [comment]
you should be able to use the operator on AKS, if you have issues feel free to share them here. 

we've considered potentially including it as an add-on but don't have anything committed there yet.

**Comment by evberrypi** [comment]
Curious if there is any update on this issue?

**Comment by allyford** [comment]
GPU Operator can be used with AKS by skipping the automatic gpu driver installation. See our [documentation for more details](https://learn.microsoft.com/en-us/azure/aks/gpu-cluster#:~:text=Use%20NVIDIA%20GPU%20Operator%20with%20AKS)
