### ISSUE TITLE
Is there plan to support blue/green deployment?

### ISSUE THREAD

**Issue by jacwu** [Azure/AKS#275]
It will great to support blue/green deployment in AKS, is there plan for it?

**Comment by ultimateboy** [comment]
Can you provide more details on what you are looking for? AKS is basically just upstream kubernetes, which has various ways of supporting blue/green style deployments.

See https://www.ianlewis.org/en/bluegreen-deployments-kubernetes for one walkthrough of an approach.

**Comment by jacwu** [comment]
Thanks, the post looks solve the problem. Is there a plan to integrate the blue/green deployment into AKS portal?
1. Create a new green deployment.
2. Keep blue deployment (production version) without any change, let user have chance to perform test on green deployment version.
3. After the test, the user can click a button on portal and make the new green deployment as production version (some workflow similar to the post above)

**Comment by slack** [comment]
No current plans to integrate blue/green into the portal experience. Thanks for reaching out, going to close out this issue.
