### ISSUE TITLE
Allow node pools to scale over 1000 nodes

### ISSUE THREAD

**Issue by gdippolito** [Azure/AKS#2755]
**What happened**:
  
I would like to scale a node pool over 1000 nodes or alternatively to have more than 1000 nodes over multiple node pools in the same cluster. 

**What you expected to happen**:

To be able to scale to at least 2000 nodes :) 

I didn't see this issue tracked anywhere. Let me know if you need more details from us (e.g subscription, resource group, etc)

**How to reproduce it (as minimally and precisely as possible)**:

Creating a node pool with over 1000 nodes and expect it to scale over 1000. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.3
- Size of cluster (how many worker nodes are in the cluster?): 1000
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Machine learning (inference)
- Others: using Sku Nc4T4 v3

**Comment by pavneeta** [comment]
We are currently working on supporting >1000 Nodes per cluster - moving this to feature request.

**Comment by IvanJosipovic** [comment]
@pavneeta, should this be re-opened?

**Comment by gdippolito** [comment]
Just realised that this feature is now in progress. Exciting! 

Would you know roughly when it will be available to Preview and GA?

**Comment by pavneeta** [comment]
Azure Kubernetes Service has now increased the node limit per cluster by 5x to 5,000 nodes across all node pools. you can learn more about this limit increase below:

- [Running at scale best practices](https://learn.microsoft.com/en-us/azure/aks/operator-best-practices-run-at-scale)
- [AKS Service Quota limits](https://learn.microsoft.com/en-us/azure/aks/quotas-skus-regions)
