### ISSUE TITLE
Add AKSHTTPCustomFeatures header support to Swagger

### ISSUE THREAD

**Issue by sossickd** [Azure/AKS#2757]
There are a number of issues that have been closed as duplicates of issue [6793](https://github.com/hashicorp/terraform-provider-azurerm/issues/6793) on the `terraform-provider-azurerm` project requesting support for custom headers to be passed to AKS.

Although the issue [6793](https://github.com/hashicorp/terraform-provider-azurerm/issues/6793) is still `Open` it has a [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/14178) that had a preposed solution for the issue that was `Closed` with the `status` `wont-fix`

@tombuildsstuff closing comment in [PR 14178](https://github.com/hashicorp/terraform-provider-azurerm/pull/14178#issuecomment-968789798) was as follows:

"Thanks for this PR.

Taking a look through here unfortunately this isn't something we can ship in Terraform at this time for a number of reasons.

The primary one here is that these are sourced from an Environment Variable and thus aren't defined in the config - however even if we were to move these to schema fields, at this point in time these can only be set in/parsed from the HTTP Headers for the request/response.

Whilst this approach works insofar as it sends the headers, due to the volatility of the Azure API's there's no guarantee this won't change behaviourally between different versions of the Azure API - and since this isn't provided in the Azure SDK (or the Swagger which supports it) - in practice it'd be hard for us to detect that this functionality has changed.

In order to support this functionality (and implement #6793) we'd need these `Headers to be added to the Swagger for the AKS API` - at which point this'll become available in the Azure SDK (and any other tooling which uses it). Whilst that may seem like a small distinction - that means this functionality becomes covered by the ARM Deprecation policy - meaning that changes have to go through a deprecation policy such that external tooling can rely on it. `In order to get that added I'd suggest opening an issue on the AKS Repository where someone from the AKS Team should be able to get that added to the next version of the Swagger, which'd allow us to support this functionality.`

As such whilst I'd like to thank you for this contribution, until this information is exposed in the Azure Swagger (such that there's a compatibility guarantee) I'm going to have to close this PR for the moment.

Thanks!"

Can i request the Headers to be added to Swagger for the AKS API 

FYI the header that i requested a [feature](https://github.com/hashicorp/terraform-provider-azurerm/issues/15137) for is `--aks-custom-headers WindowsContainerRuntime=containerd` when creating a Windows node pool

```console
az aks nodepool add \
    --resource-group myResourceGroup \
    --cluster-name myAKSCluster \
    --os-type Windows \
    --name npwcd \
    --node-vm-size Standard_D4s_v3 \
    --kubernetes-version 1.20.5 \
    --aks-custom-headers WindowsContainerRuntime=containerd \
    --node-count 1
``

**Comment by tombuildsstuff** [comment]
Opened a PR on the Swagger repository to add support for this, FWIW: https://github.com/Azure/azure-rest-api-specs/pull/18232

**Comment by palma21** [comment]
We're no longer shipping any feature that is not on deprecation path using headers.
