### ISSUE TITLE
Cluster dashboard unavailable due to illegal character in generated config

### ISSUE THREAD

**Issue by ronpal** [Azure/AKS#276]
We have done a number of successful updates with $kubectl apply -f <file.yaml> and subsequent «az aks browse -n <clustername> -g <resourcegroup>» commands. At one point the latter command started to fail with the following error, and we have not been able to recover since. This has happened before, and was resolved by re-provisioning the entire cluster and starting over. 

```$ az aks browse --resource-group KubernetesProd --name ProdCluster   

Merged "ProdCluster" as current context in /var/folders/dz/bm52mj7j0yz6j3vrb8k14qs1qxfhm_/T/tmp1t22yz48
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
error: invalid resource name "kubernetes-dashboard-2898242510-kldr1\npods/kubernetes-dashboard-2898242510-mj70d\npods/kubernetes-dashboard-2898242510-r9n9g": [may not contain '/']
 ```
The referred file resembles the config files that kubectl uses. 

Could this be a problem with the CLI? I'm running on OSX with azure-cli version 2.0.26.

**Comment by ronpal** [comment]
Any suggestions for temporarily circumventing the problem would be appreciated as well. This is a bit of an obstacle in our project.

**Comment by shahiddev** [comment]
Can you just try kubectl proxy and then go to 
http://127.0.0.1:8001/ui 
instead?

**Comment by jalberto** [comment]
@shahiddev check #286
