### ISSUE TITLE
Azure Disk CSI Storage Class is LRS by default

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/AKS#2765]
**What happened**:

Azure Disk CSI Storage Class is LRS by default

**What you expected to happen**:

AKS should also include a Storage Class with ZRS support for Azure Disk as this is now [supported](https://docs.microsoft.com/en-us/azure/aks/availability-zones#azure-disk-availability-zone-support).

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.4
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by andyzhangx** [comment]
since ZRS disk is not supported on every region, we don't want to add a built-in ZRS storage class
