### ISSUE TITLE
Support for setting scale-in policy for underlying scaleset in AKS clusters

### ISSUE THREAD

**Issue by stigok** [Azure/AKS#2767]
We would like to be able to configure the scale-in policy for the underlying virtual machine scale sets used for node pools in AKS. The setting needs to be exposed so that we in turn can configure it with Terraform as described in https://github.com/hashicorp/terraform-provider-azurerm/issues/11068. We are able to configure it manually through the Azure portal, but it is infeasible due to the large amount of clusters we have and our policy to keep this configured in IaaC, i.e. Terraform.

The default setting gives us an unnecessary extra node restart.
> Default – Balance across availability zones and fault domain, then delete virtual machine with highest instance ID

Maybe even a default setting of `OldestVM` would make more sense for Kubernetes clusters, but I may be missing the bigger picture there.

> When using upgrade_settings.max_surge now, new nodes spawn to offload the upgrading node(s), but they are deprovisioned again when the old node is updated. This gives us an additional node outage when only one is strictly needed.
- https://github.com/hashicorp/terraform-provider-azurerm/issues/11068

Possibly related issues:
- https://github.com/Azure/AKS/issues/2164

**Comment by olsenme** [comment]
@miwithro

**Comment by rouke-broersma** [comment]
@stigok in our experience the vmss scale-in policy is actually not used for scaling-in a aks cluster. The cluster autoscaler appears to delete specific nodes from kubernetes (in essence kubectl delete node) which in turn causes the aks vmss manager to remove that vm from the scale set. We could not actually find this behavior documented anywhere but it is what we observed from logs.

**Comment by stigok** [comment]
> @stigok in our experience the vmss scale-in policy is actually not used for scaling-in a aks cluster. The cluster autoscaler appears to delete specific nodes from kubernetes (in essence kubectl delete node) which in turn causes the aks vmss manager to remove that vm from the scale set. We could not actually find this behavior documented anywhere but it is what we observed from logs.

Interesting. I seem to recall that after I configured this setting on the node pool's VM scaleset, it actually behaved as expected. This would also make architectural sense in my head, that the node auto-scaler just forwards the node count requests to the VM scaleset. I hope you are wrong, and that this can be fixed.

Have you tried changing the scale-in policy for your own scalesets?

**Comment by rouke-broersma** [comment]
As a rule we do not touch kubernetes managed resources so we have not. I only know that we have seen in the logs rows with deleting node xxx and seeing that specific node being deleted by the scale set afterwards.
