### ISSUE TITLE
no subjectAltName in kubelet certificate

### ISSUE THREAD

**Issue by dhduvall** [Azure/AKS#2770]
**What happened**:

Our Datadog agent is logging (perhaps excessively, but that's their issue) the following (split into multiple lines for readability):
```
2022-02-05 00:15:54 UTC | CORE | WARN | (pkg/collector/python/datadog_agent.go:124 in LogMessage) | - |
    (warnings.py:109) | /opt/datadog-agent/embedded/lib/python3.8/site-packages/urllib3/connection.py:460:
    SubjectAltNameWarning: Certificate for aks-services-29597630-vmss000002 has no `subjectAltName`,
    falling back to check for a `commonName` for now. This feature is being removed by major browsers and
    deprecated by RFC 2818. (See https://github.com/urllib3/urllib3/issues/497 for details.)
```

**What you expected to happen**:

The log shouldn't show up because the certificate should have the appropriate subjectAltName. In this case, it seems to be using the bare hostname `aks-services-29597630-vmss000002`, which is already the subject.

**How to reproduce it (as minimally and precisely as possible)**:

On a node:
```
# openssl x509 -noout -text -in /etc/kubernetes/certs/kubeletserver.crt -certopt no_sigdump,no_pubkey
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            0e:4e:e7:19:fe:8c:5c:23:93:5f:64:35:f6:19:5d:48:bd:90:5e:09
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = aks-services-29597630-vmss000002
        Validity
            Not Before: Jan  1 00:10:34 2022 GMT
            Not After : Dec 27 00:10:34 2041 GMT
        Subject: CN = aks-services-29597630-vmss000002
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                82:20:F5:62:96:4A:60:B1:23:49:22:34:0E:3E:81:5F:DD:C1:4E:39
            X509v3 Authority Key Identifier:
                keyid:82:20:F5:62:96:4A:60:B1:23:49:22:34:0E:3E:81:5F:DD:C1:4E:39

            X509v3 Basic Constraints: critical
                CA:TRUE
```

Compare this to the API server certificate:
```
# openssl x509 -noout -text -in /etc/kubernetes/certs/apiserver.crt -certopt no_sigdump,no_pubkey
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            c0:34:1e:4b:38:d4:77:bc:65:8c:90:e2:c5:fd:56:04
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = ca
        Validity
            Not Before: Dec 31 22:49:02 2021 GMT
            Not After : Dec 31 22:59:02 2023 GMT
        Subject: CN = apiserver
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Authority Key Identifier:
                keyid:7F:16:DD:92:4F:CC:2F:79:70:69:4B:88:C2:47:F9:9A:F1:44:45:15

            X509v3 Subject Alternative Name:
                DNS:localhost, DNS:hcp-kubernetes, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, DNS:hcp-kubernetes.5fdcbbca5d6362000121cf58.svc.cluster.local, DNS:coros-stage-cluster-0d0c7314.hcp.centralus.azmk8s.io, IP Address:10.0.0.1
```

You can also verify from a container by running
```
$ curl -svk https://aks-services-29597630-vmss000002:10250
```
and noting the decoded server certificate in the output.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.1

**Comment by olsenme** [comment]
@miwithro

**Comment by brownoxford** [comment]
I'm seeing this issue with DD as well. The official response I got back from DD support was that this was a known issue related to https://github.com/urllib3/urllib3/issues/497 and that the current workaround was to suppress the warning messages via one of the following methods:
* The first option if you don't doesn’t mind essentially disabling TLS is to set the environment variable DD_KUBELET_TLS_VERIFY=false , or datadog.kubelet.tlsVerify: false if they use our [helm chart](https://github.com/DataDog/helm-charts/blob/f7bd53c3b2a0f86e6d30f4a9a6374e6b9c5d9775/charts/datadog/values.yaml#L170-L185) to disable the TLS verification.
* The other, and probably more preferred option, is that you can add this environment variable to their Helm Configuration or Agent DaemonSet, which bypasses the PYTHONWARNINGS message [warnings — Warning control — Python 3.10.2 documentation](https://docs.python.org/3/library/warnings.html#the-warnings-filter).
**Note** this would still print the warn message after restarting the agent container, but only once
```yaml
env:
  - name: PYTHONWARNINGS
    value: "module"
```

My preference would be to have the generated certificates comply with RFC2818 if possible.

**Comment by dhduvall** [comment]
Thanks for sharing that!

I'm sort of surprised that it works, though (and it does seem to). The default behavior of the `warnings` module already is to print the message once. The difference between `default` and `module` is that the latter ignores the line number for duplication detection. And on top of that, `urllib3` sets it up that specific warning class (`SubjectAltNameWarning`) to have the `default` behavior. I tried setting `PYTHONWARNINGS` to `default`, too, and it still seems to suppress duplicates. Setting it to `always` is the same as not setting it at all.

I wrote a little test program to experiment and got different results: the unset behavior was as expected, with no duplicates, but `always` also gave deduplicated results. I'm not sure what I did to make that program different from what's going on in the agent, but as I look through the agent code, it does a remarkable amount of Python plumbing in the Go code, so I'll hypothesize that the differences are somewhere there and leave it at that.

I would be inclined to narrow `PYTHONWARNINGS` a bit to `default:Certificate for aks-::urllib3.connection` so that if there are other hosts with this problem, they'd stand out, but I'm not convinced that they wouldn't get de-duplicated, too.

**Comment by brownoxford** [comment]
This may have something to do with DD using an embedded version of the urllib3 module, not too sure. I spent some time trying to narrow it down as well, and ended up with `module:Certificate for` because I couldn't get the last module bit working, does `urllib3.connections` actually work for you (I gave up when `urllib3` didn't work here?

**Comment by dhduvall** [comment]
It did work for me; that slot needs to contain the full module name. There's some commentary about how broken this (compared to the documentation, at least) is at https://nedbatchelder.com/blog/201810/why_warnings_is_mysterious.html. I'll add to that the message slot is supposed to be a regex, too, but that also doesn't work.

**Comment by dhduvall** [comment]
I've been running with `PYTHONWARNINGS=default` for almost a day, and it's reduced the message count, but it's still pretty high. I don't have a full 24 hours yet, but I'm seeing a drop-off of about 1k/hr to about 170/hr. So I think I'm going to switch to `ignore` and scope that as tightly as I can.

**Comment by jchenship** [comment]
but `aks-services-29597630-vmss000002` is only in the common name, not in the subject alt name ? common name is deprecated , and a certificate should always have a subject alt name

**Comment by agronholm** [comment]
But there was no answer or resolution provided? Has this actually been fixed?

**Comment by nijave** [comment]
@miwithro why was the answer label added? This is still a problem with no resolution

**Comment by miwithro** [comment]
Sorry updated wrong issue.

**Comment by CocoWang-wql** [comment]
Update: we finish the code change to add the subjectAltName in node cert. 
The change will be released in next AgentBaker and all regions which take about 3 weeks. The ETA is 20th Nov.

**Comment by nijave** [comment]
> Update: we finish the code change to add the subjectAltName in node cert. The change will be released in next AgentBaker and all regions which take about 3 weeks. The ETA is 20th Nov.

What versions of k8s/AKS is this available for?

**Comment by CocoWang-wql** [comment]
Hello @nijave , upgrading aks is not needed. You can use 'az aks upgrade -g <> -n <> --node-image-only' to upgrade the node image version.
