### ISSUE TITLE
Which logs to check for my application issue debugging if two pods are running for same deployment?

### ISSUE THREAD

**Issue by imvjsai** [Azure/AKS#2771]
Hi Team,

I am running my application in two pods for same one deployment by giving replica set as '2' in Yaml file. For debugging purpose I would need logs for my application. As I can see two pods are running I can get two log files from each one of the pod. So, I would like to understand which log I have to take and which is more accurate? Please help me understand.

Thanks a lot in advance!

Kind Regards,
Vijay

**Comment by alexeldeib** [comment]
you need both logs. they are two independent instances of the same application. both logs will be useful. for example if you put a kubernetes service in front of your replicas, requests would be distributed between both replicas.

**Comment by imvjsai** [comment]
Thanks very much Alex for your response. I understood now. :)
