### ISSUE TITLE
Security Profile property initiates unnecessary AKS-AzureDefender feature validation 

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS#2774]
**What happened**:
Using bicep (arm) to create an AKS cluster. The mere presence of the securityProfile causes the RP to reject the deployment if the Defender for Containers preview is not enabled.

Bicep;
![image](https://user-images.githubusercontent.com/17914476/152965463-9607ac3e-0812-4d70-9cc3-f4c99db26319.png)

Error;
> ERROR: ***"error":***"code":"InvalidTemplateDeployment","message":"The template deployment 'main' is not valid according to the validation procedure. The tracking id is '68eb4738-5746-4250-9d23-510385bcb03e'. See inner errors for details.","details":[***"code":"AzureDefenderFeatureFlagNotEnabled","message":"Provisioning of resource(s) for container service aks-AksStan in resource group AksBicepAcc-Ci-BasicCluster failed. Message: ***\n  \"code\": \"AzureDefenderFeatureFlagNotEnabled\",\n  \"message\": \"AzureDefender installation is not allowed since feature 'Microsoft.ContainerService/AKS-AzureDefender' is not enabled. Please see https://aka.ms/aks/previews for how to enable features.\"\n ***. Details: "***]***

**What you expected to happen**:
If AzureDefender is not enabled in the bicep ( enabled: false ), then i don't expect the deployment to fail for subscriptions that do not have Azure Defender enabled.

**How to reproduce it (as minimally and precisely as possible)**:
In a subscription that does not use the **Microsoft.ContainerService/AKS-AzureDefender** - deploy an AKS cluster with these properties set;

```bicep
    securityProfile: {
      azureDefender: {
        enabled: false
      }
    }
```

**Comment by CocoWang-wql** [comment]
Hello @Gordonby 
The AKS cluster will be enabled defender automatically if your subscription is registered MS defender.
Pls search defender in portal - choose your subscription - check whether the AKS service turns on. If yes, pls close it and have another try.
![image](https://user-images.githubusercontent.com/45681473/165247964-280c59e9-94b9-41e8-afe9-3406f83adcc6.png)

**Comment by Gordonby** [comment]
@CocoWang-wql - This issue is about the AKS RP, not the portal or how defender works.
