### ISSUE TITLE
Nodepool Snapshot

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#2778]
https://docs.microsoft.com/en-us/azure/aks/node-pool-snapshot

**Comment by heoelri** [comment]
@palma21 / @justindavies the docs say that: 

> Your node pool image version will be the same contained in the snapshot and will remain the same throughout every scale operation. 

Does that mean that the image used when scaling out a node pool is the (latest) snapshot? Or does it mean that new nodes will come up with the node image version used for the node pool (and basically ignore the snapshot)?

Our scenario is that node image upgrade is scheduled once a week (given the promised release cycle of new images). On top of that will UnattendedUpgrade automatically install additional updates (and kured when used will take care of pending reboots). we want to avoid that in pools with a lot of scale operations continiously come up with "old" images requiring updates + reboots multiple times a week.
