### ISSUE TITLE
AKS addon ingress-appgw still shows in Preview

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/AKS#2779]
**What happened**:
```
➜  ~ az aks addon list-available -o table | grep ingress-appgw
ingress-appgw                    - enable Application Gateway Ingress Controller addon (PREVIEW).
➜  ~ az extension list -o table
Experimental    ExtensionType    Name         Path                                              Preview    Version
--------------  ---------------  -----------  ------------------------------------------------  ---------  ---------
False           whl              aks-preview  /Users/thfalgou/.azure/cliextensions/aks-preview  True       0.5.48
```

**What you expected to happen**:
According to https://github.com/Azure/AKS/issues/1441 this addon is GA, but is still showing up as (PREVIEW).  

**How to reproduce it (as minimally and precisely as possible)**:
* Go to shell.azure.com
* Run `az aks addon list-available -o table | grep ingress-appgw`
* See that the addon show (PREVIEW)

**Environment**:
* Confirmed on shell.azure.com and latest Azure CLI

**Comment by miwithro** [comment]
@akshaysngupta
