### ISSUE TITLE
Enable OIDC issuer command fails.

### ISSUE THREAD

**Issue by monubamb100** [Azure/AKS#2781]
az aks create -n m4 -g akrt --enable-oidc-issuer

Argument '--enable-oidc-issuer' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The behavior of this command has been altered by the following extension: aks-preview
(PropertyChangeNotAllowed) Changing property 'linuxProfile.ssh.publicKeys.keyData' is not allowed.
Code: PropertyChangeNotAllowed
Message: Changing property 'linuxProfile.ssh.publicKeys.keyData' is not allowed.
Target: linuxProfile.ssh.publicKeys.keyData

{
  "azure-cli": "2.32.0",
  "azure-cli-core": "2.32.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.50",
    "aro": "1.0.0",
    "connectedk8s": "1.2.0",
    "containerapp": "0.2.0",
    "cosmosdb-preview": "0.11.0",
    "dev-spaces": "1.0.6",
    "k8s-configuration": "1.3.0",
    "k8s-extension": "1.0.3"
  }
}

**Comment by miwithro** [comment]
@monubamb100 what is your cluster version.  This only works on 1.20+
