### ISSUE TITLE
aks-secrets-store-csi-driver - secrets store container fails to start on AKSUbuntu-1804gen2containerd-2022.01.24

### ISSUE THREAD

**Issue by cxtuttle** [Azure/AKS#2782]
**What happened**:

On a node with AKSUbuntu-1804gen2containerd-2022.01.24

kubectl logs aks-secrets-store-csi-driver-AABBCC -n kube-system secrets-store
I0211 00:18:58.906348       1 exporter.go:35] "initializing metrics backend" backend="prometheus"
I0211 00:18:58.990014       1 secrets-store.go:41] "Initializing Secrets Store CSI Driver" driver="secrets-store.csi.k8s.io" version="v1.0.0" buildTime="2021-10-14-21:40"
I0211 00:18:58.990756       1 mount_linux.go:192] Detected OS without systemd
I0211 00:18:58.991012       1 server.go:120] "Listening for connections" address="//csi/csi.sock"
I0211 00:18:58.991128       1 main.go:178] starting manager
I0211 00:18:58.991295       1 shared_informer.go:270] caches populated
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x137f4c5]

goroutine 49 [running]:
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).RESTMapping.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/client/apiutil/dynamicrestmapper.go:255 +0x45
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).checkAndReload.func1(0x28, 0x38)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/client/apiutil/dynamicrestmapper.go:155 +0x91
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).checkAndReload(0xc00007c1e0, {0x1afd7c0, 0xc0003a6200}, 0xc00039cfe0)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/client/apiutil/dynamicrestmapper.go:156 +0x9c
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).RESTMapping(0xc00007c1e0, {{0x190d7f0, 0x0}, {0x158e2c6, 0xc00039d088}}, {0xc0004cf020, 0x1, 0x1})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/client/apiutil/dynamicrestmapper.go:253 +0x168
sigs.k8s.io/controller-runtime/pkg/cache/internal.createStructuredListWatch({{0x190d7f0, 0x1a}, {0x18f1386, 0x2}, {0x158e2c6, 0x1c}}, 0xc000102410)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/cache/internal/informers_map.go:250 +0x14d
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).addInformerToMap(0xc000102410, {{0x190d7f0, 0x1a}, {0x18f1386, 0x2}, {0x158e2c6, 0x1c}}, {0x1b1b6e0, 0x0})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/cache/internal/informers_map.go:213 +0x19a
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).Get(0x2, {0x1b2bbb0, 0xc000111980}, {{0x190d7f0, 0x1a}, {0x18f1386, 0x2}, {0x158e2c6, 0x1c}}, {0x1b1b6e0, ...})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/cache/internal/informers_map.go:185 +0xf6
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*InformersMap).Get(0xc0002f0150, {0x1b2bbb0, 0xc000111980}, {{0x190d7f0, 0x1a}, {0x18f1386, 0x2}, {0x158e2c6, 0x1c}}, {0x1b1b6e0, ...})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/cache/internal/deleg_map.go:105 +0x279
sigs.k8s.io/controller-runtime/pkg/cache.(*informerCache).List(0xc000096030, {0x1b2bbb0, 0xc000111980}, {0x1b5b7a0, 0xc0002f0150}, {0xc00038d960, 0x1, 0x1})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/cache/informer_cache.go:79 +0xe5
sigs.k8s.io/secrets-store-csi-driver/controllers.(*SecretProviderClassPodStatusReconciler).Patcher(0xc00041db00, {0x1b2bbb0, 0xc000111980})
        /go/src/sigs.k8s.io/secrets-store-csi-driver/controllers/secretproviderclasspodstatus_controller.go:114 +0x38a
sigs.k8s.io/secrets-store-csi-driver/controllers.(*SecretProviderClassPodStatusReconciler).RunPatcher(0x0, {0x1b2bbb0, 0xc000111980})
        /go/src/sigs.k8s.io/secrets-store-csi-driver/controllers/secretproviderclasspodstatus_controller.go:98 +0x12c
main.main.func4()
        /go/src/sigs.k8s.io/secrets-store-csi-driver/cmd/secrets-store-csi-driver/main.go:186 +0x25
created by main.main
        /go/src/sigs.k8s.io/secrets-store-csi-driver/cmd/secrets-store-csi-driver/main.go:185 +0xeaf

**What you expected to happen**:

Node with AKSUbuntu-1804gen2containerd-2022.01.07

I0210 20:48:16.913912       1 mount_linux.go:192] Detected OS without systemd
I0210 20:48:16.914073       1 server.go:120] "Listening for connections" address="//csi/csi.sock"
I0210 20:48:16.914151       1 reconciler.go:130] "starting rotation reconciler" rotationPollInterval="5m0s"
I0210 20:48:16.914224       1 reflector.go:219] Starting reflector *v1.Secret (5s) from pkg/mod/k8s.io/client-go@v0.22.0/tools/cache/reflector.go:167
I0210 20:48:16.914238       1 reflector.go:255] Listing and watching *v1.Secret from pkg/mod/k8s.io/client-go@v0.22.0/tools/cache/reflector.go:167
I0210 20:48:17.114766       1 shared_informer.go:270] caches populated
I0210 20:48:17.142274       1 request.go:597] Waited for 87.87283ms due to client-side throttling, not priority and fairness, request: GET:https://askname.hcp.eastus2.azmk8s.io:443/apis/secrets-store.csi.x-k8s.io/v1?timeout=32s
I0210 20:48:17.195257       1 request.go:597] Waited for 140.84915ms due to client-side throttling, not priority and fairness, request:
....
I0210 20:48:17.644934       1 reflector.go:219] Starting reflector *v1.SecretProviderClassPodStatus (10h52m51.665433924s) from pkg/mod/k8s.io/client-go@v0.22.0/tools/cache/reflector.go:167
I0210 20:48:17.644952       1 reflector.go:255] Listing and watching *v1.SecretProviderClassPodStatus from pkg/mod/k8s.io/client-go@v0.22.0/tools/cache/reflector.go:167
I0210 20:48:17.746061       1 shared_informer.go:270] caches populated
I0210 20:48:17.746251       1 shared_informer.go:270] caches populated
I0210 20:48:58.600838       1 server.go:150] "request" method="/csi.v1.Identity/Probe" req="{}" deadline="2.998420397s"
I0210 20:48:58.600886       1 server.go:154] "response" method="/csi.v1.Identity/Probe" deadline="2.998420397s" duration="1.283107ms" status.code="OK" status.message=""

**How to reproduce it (as minimally and precisely as possible)**:

Have an AKS Cluster with:

 "addonProfiles": {
            "azureKeyvaultSecretsProvider": {
                "enabled": true,
                "config": {
                    "enableSecretRotation": "false",
                    "rotationPollInterval": "2m"
                }
}

**Anything else we need to know?**:

I upgraded the working node to the latest node image and it also started to fail.  Now I need to figure out how to downgrade a node.

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.22.4
- Size of cluster (how many worker nodes are in the cluster?) 5
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by cxtuttle** [comment]
Looking at this some more.  The issue still exists but is not related to the node image.  It seems only a single POD will run at a time.  The docs suggest it should run on all VMs,  but if that is so than something is broken.

`kubectl get pods -n kube-system -l 'app in (secrets-store-csi-driver, secrets-store-provider-azure)' -o wide
NAME                                     READY   STATUS             RESTARTS          AGE     IP              NODE                                  NOMINATED NODE   READINESS GATES
aks-secrets-store-csi-driver-A       2/3     CrashLoopBackOff   708 (3m44s ago)   2d17h   10.97.103.231   aks-userpool1-A-vmss000002     <none>           <none>
aks-secrets-store-csi-driver-B       3/3     Running            0                 2d17h   10.97.103.228   aks-defaultpool-B-vmss000000   <none>           <none>
aks-secrets-store-csi-driver-C       2/3     CrashLoopBackOff   708 (3m3s ago)    2d17h   10.97.103.229   aks-userpool1-C-vmss000000     <none>           <none>
aks-secrets-store-csi-driver-D       2/3     CrashLoopBackOff   707 (2m53s ago)   2d17h   10.97.103.230   aks-userpool1-D-vmss000001     <none>           <none>
aks-secrets-store-csi-driver-E       2/3     CrashLoopBackOff   707 (4m33s ago)   2d17h   10.97.103.232   aks-userpool2-E-vmss000000     <none>           <none>
aks-secrets-store-provider-azure-A   1/1     Running            0                 2d17h   10.97.103.230   aks-userpool1-A-vmss000001     <none>           <none>
aks-secrets-store-provider-azure-B   1/1     Running            0                 2d19h   10.97.103.228   aks-defaultpool-B-vmss000000   <none>           <none>
aks-secrets-store-provider-azure-C   1/1     Running            0                 2d17h   10.97.103.231   aks-userpool1-C-vmss000002     <none>           <none>
aks-secrets-store-provider-azure-D   1/1     Running            0                 2d17h   10.97.103.229   aks-userpool1-D-vmss000000     <none>           <none>
aks-secrets-store-provider-azure-E   1/1     Running            0                 2d17h   10.97.103.232   aks-userpool2-E-vmss000000     <none>           <none>`

**Comment by miwithro** [comment]
@ZeroMagic can you look into this one?

**Comment by ZeroMagic** [comment]
@cxtuttle could you try the following solution? 
1. Disable the addon using `az aks disable-addons` command.
2. Follow the guidance to install upstream version. https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/
3. Verify if it is running well.

If it works, I will plan to upgrade the managed version in AKS. 
If not, I think it is the bug. Then need to fix it in upstream firstly.

**Comment by cxtuttle** [comment]
Ok,  I went and did a couple of things.

1)  Upgraded AKS to latest 1.22.6  --  2 of 5 pods came up running in 2 different pools,  but the other 3 failed to start with same issue.
2) Upgrade to latest Nodepool image -- No change
3) disabled the addon,  but also had to kubectl delete csidriver.   I than followed the manual steps and helm installed the csidriver.   Everything seems to be running correctly across all pods.

I'm still a little ways away from testing the CSI driver.  I need to now get a managed identity on each underlying VMSS,  which doesn't seem to be possible to assign.  I'm going to try setting the kubelet managed identity through Terraform and see if that gets onto each node.

**Comment by ZeroMagic** [comment]
Looks good. The latest version is working for you. I will plan to upgrade the addon version recently.

**Comment by jhatcher1** [comment]
Hello! We've also encountered this issue when installing secrets-store-csi-driver-provider using the Azure CLI. We're following these instructions: https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver

Installing the upstream version via helm chart works fine, but we would prefer to use the managed version if possible. Is there a timeline for when the managed version will be fixed? Thanks!

**Comment by miwithro** [comment]
@jhatcher1 are you still unable to install csi secret store?

**Comment by jhatcher1** [comment]
Hi @miwithro , yes I just tried re-enabling the azure-keyvault-secrets-provider with the Azure CLI, and the pods immediately enter CrashLoopBackOff with the same stack trace.

```
aks-secrets-store-csi-driver-4pl74       1/3     CrashLoopBackOff   10 (39s ago)   6m40s
aks-secrets-store-csi-driver-6k86k       1/3     CrashLoopBackOff   10 (46s ago)   6m40s
aks-secrets-store-csi-driver-8v68g       1/3     CrashLoopBackOff   10 (39s ago)   6m40s
aks-secrets-store-csi-driver-b8624       1/3     CrashLoopBackOff   10 (45s ago)   6m40s
aks-secrets-store-csi-driver-kppgb       2/3     CrashLoopBackOff   11 (45s ago)   6m40s
aks-secrets-store-csi-driver-lndv6       1/3     CrashLoopBackOff   10 (39s ago)   6m40s
aks-secrets-store-csi-driver-p5swk       1/3     CrashLoopBackOff   10 (46s ago)   6m40s
aks-secrets-store-csi-driver-q4ppx       1/3     CrashLoopBackOff   10 (38s ago)   6m40s
aks-secrets-store-csi-driver-q9v9g       1/3     CrashLoopBackOff   10 (39s ago)   6m40s
aks-secrets-store-csi-driver-qgnbk       1/3     CrashLoopBackOff   10 (39s ago)   6m40s
aks-secrets-store-csi-driver-qhkwk       1/3     CrashLoopBackOff   10 (45s ago)   6m40s
aks-secrets-store-csi-driver-wkxn9       1/3     CrashLoopBackOff   10 (45s ago)   6m40s
aks-secrets-store-csi-driver-zf8vz       1/3     CrashLoopBackOff   10 (43s ago)   6m40s
aks-secrets-store-csi-driver-zn7vj       1/3     CrashLoopBackOff   10 (39s ago)   6m40s
```

**Comment by miwithro** [comment]
@jhatcher1 we just rolled out a fix. Can you try again.
