### ISSUE TITLE
Azure AKS(1.21.7) --> title":"Linux Node(s) are Not Ready","details":"At least 1 node in your cluster is not ready, and heartbeat is not updating.

### ISSUE THREAD

**Issue by zohebs341** [Azure/AKS#2785]
We are using Azure AKS for our production workloads and for the past 2 days, we are experiencing one issue with cluster nodes.
As cluster nodes are getting removed from AKS cluster and it's adding new nodes.

Error from Azure Portal:

title":"Linux Node(s) are Not Ready","details":"At least 1 node in your cluster is not ready, and heartbeat is not updating.
We are trying to recover your node(s)","currentHealthStatus":"Available","previousHealthStatus":"Available","type":"Downtime","cause":"PlatformInitiated"}

Region: UAE North
AKS Version: 1.21.7
Node Details:
Ubuntu 18.04.6 LTS 5.4.0-1067-azure containerd://1.4.9+azure

Can someone look into this urgently, as node drain is evicting our production pods. It's the 4th time, we have experienced this in the last two days.

**Comment by zohebs341** [comment]
Hi Team,

Can someone look into this issue, as it's impacting our production workloads. What is the point of having managed nodes, if it's behaving abnormally? Is there a fix required from Microsoft for this at the node level or is it something different issue?

Again after one week, we have experienced a similar issue. 

Linux Nodes are not ready(Unplanned) ---- Error from resource health

**Comment by allyford** [comment]
@zohebs341 - Are you still having this issue? The issue tagged above #2787 only applies to Windows nodes and was resolved.
