### ISSUE TITLE
Windows nodes may not be ready after upgrading to 1.22.x before AKS RP release v20220210 is available in all regions (Current plan: 2/25/2022)

### ISSUE THREAD

**Issue by AbelHu** [Azure/AKS#2787]
**What happened**:
All Windows nodes are not ready if you upgrade the cluster to 1.22.x. 

**What you expected to happen**:
Please do not upgrade to 1.22.x before AKS RP release v20220210 is available in all regions (Current plan: 2/25/2022)
It may be caused by that `--dynamic-config-dir` in kubeletConfig is not supported by 1.22.x.  If you hit the issue, please ask AKS on-call to follow the TSG to mitigate it.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.x -> 1.22.x
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by zohebs341** [comment]
@AbelHu Thanks for posting. Could you please assist on the below issue, as it seems similar to the issue which you posted.

I've created an issue, but no response yet. It is impacting our production workload.

Github Issue - https://github.com/Azure/AKS/issues/2785

We are using Azure AKS for our production workloads and for the past 2 days, we are experiencing one issue with cluster nodes.
As cluster nodes are getting removed from AKS cluster and it's adding new nodes.

Error from Azure Portal:

title":"Linux Node(s) are Not Ready","details":"At least 1 node in your cluster is not ready, and heartbeat is not updating.
We are trying to recover your node(s)","currentHealthStatus":"Available","previousHealthStatus":"Available","type":"Downtime","cause":"PlatformInitiated"}

Region: UAE North
AKS Version: 1.21.7
Node Details:
Ubuntu 18.04.6 LTS 5.4.0-1067-azure containerd://1.4.9+azure

As node drain is evicting our production pods. It's the 4th time, we have experienced this in the past few days.

**Comment by AbelHu** [comment]
@zohebs341 It seems like to be different issue since it occurs in Linux nodes. Suggest you to file a support ticket to get the help.

**Comment by AbelHu** [comment]
Update: The fix is available in all global regions. BTW: New AKS Windows VHD 17763.2565.220211 with Windows security patch in Feb, 2022 (2022.02B) is also available in all global regions.

**Comment by AbelHu** [comment]
The fix is available in all regions now.
