### ISSUE TITLE
Upgrade channel blocks deployment

### ISSUE THREAD

**Issue by aelij** [Azure/AKS#2790]
**What happened**:
We tried upgrade a cluster with a `node-image` upgrade channel from 1.21.2 to 1.21.7 and got an error:

> To enabled Auto Upgrade, agentpools and cluster kubernetes versions must be at least (lowest supported minor version - 1) for rapid and stable channel or supported for patch and node-image channel.

**What you expected to happen**:
As 1.21.7 is a supported version, we expected the upgrade to go through. We had to turn off the upgrade channel, upgrade the cluster and then turn it back on, which makes deploying using Bicep very difficult.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Comment by vsabella** [comment]
We are also experiencing this issue and opened a support ticket.

Their resolution was the same - disable, upgrade, re-enable, but as we have to do this across 60+ Kubernetes clusters it is tedious to do so.

**Comment by rehan2908** [comment]
is there any update

**Comment by stack-mriso** [comment]
Do we have an update on this? We are having the same issue.

**Comment by paulgmiller** [comment]
We can repro a case where an upgrade channel was set same time as an upgrade requested and are looking at fixing that bug.

But we haven't yet found an example where autoupgrade channel was unchanged and it blocked an upgrade. If anyone with has a datetime of a recent repro that would help.
