### ISSUE TITLE
Pod security context fsGroup setting causes mounting timeouts

### ISSUE THREAD

**Issue by george-zubrienko** [Azure/AKS#2791]
**What happened**: 

This is a follow-up from case ID 2202030050001805 (self-resolved). Story is as follows:

We had an AKS cluster created with 1.19.11 base version hosting Airflow 2.2.3 installed from an official helm chart. The deployment model we used was 2 PVs: one to host pipeline definitions, other to host task log data, which is a common practice with Airflow. PVs were ReadWriteMany, `azurefile` storage class volumes, provisioned from respective PVCs. Everything worked fine. Over time cluster was upgraded to 1.21.7 without any issues.

February 2, 2022, we re-created the cluster to update AZs and machines used by default pool, using 1.21.7 as a base version this time. Several hours later, task pods Airflow launches started timing out when mounting `logs` volume. There were no errors reported from fileshares, CSI driver or anything.

We tried:

- Enabling LFS
- Re-creating PVs from 'azurefile-csi` storage class PVCs
- Provisioning bigger capacity

Nothing helped, and it didn't seem that we were IOPS-throttled based on reported metrics. Then I noticed a certain pattern - first few hours after PV is created everything is fine, then mounting time goes up and eventually starts timing out. I suspected this is related to number of logfiles stored on fileshare gradually increasing, so I tried to remove some of them using cronjob and that helped. Then I started digging and found several issues in kubernetes repo referencing `fsGroup` problems on Azure-provisioned clusters. Our pods had the following security context set:

```
securityContext:
  runAsUser: 50000
  fsGroup: 0
```

The way `fsGroup` works is, per k8s docs, it `chowns` everything into respective group - which corresponds with the issue we were seeing: since chown done on per-file basis, the more files are there, the more time it takes to `chown` everything before a volume is mounted. Hence the timeout. I've updated pods security context to this:

```
securityContext:
  runAsUser: 50000
  runAsGroup: 0
```

And after that, the problem was gone.

**What you expected to happen**:

I'd ideally expect one of the following:

- setting `fsGroup` doesn't cause mounting timeouts on PVs that host a lot of files
- group ownership is only updated if there is mismatch, like described [here](https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/). However, in that blob they refer to a pod security context. Would be nice to have that behaviour as a default, without the need to update pod SC.

**How to reproduce it (as minimally and precisely as possible)**:

1. Provision a fresh AKS cluster v1.21.7.
2. Create a PVC from `azurefile-csi` class.
3. Create a pod template that uses, for example, busy box image and runs a shell script like this:
```
for i in {1..64}
do
 echo "test" >> /my/fileshare/mount/path/$POD_NAME.log
 sleep 1
done
```
Also set pod security context like this:
```
securityContext:
  runAsUser: 12345
  fsGroup: 0
```

4. Run 100 pods every 5 mins and observe mount time. It will start timing out eventually.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.7
- Size of cluster (how many worker nodes are in the cluster?): ~0->20, autoscaling cluster
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Airflow 2.2.3 with Kubernetes Executor
- Others: ingress controller (nginx) and cert-manager 1.6.1

**Comment by andyzhangx** [comment]
try set `fsGroupChangePolicy: "OnRootMismatch"` in pod securityContext, it may also solve the issue:

 - OnRootMismatch: Only change permissions and ownership if permission and ownership of root directory does not match with expected permissions of the volume. This could help shorten the time it takes to change ownership and permission of a volume.

refer to [Configure volume permission and ownership change policy for Pods](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods)

**Comment by george-zubrienko** [comment]
We did that, but there is an issue with it - k8s sdk used by airflow (and many other apps so far) doesn't support it yet. So we can only upgrade components that do not rely on sdk use for launching pods, which unfortunately doesn't include workers. That's why we ended with runAsGroup instead.
Even though this will be resolved in the future, I still think using fsGroup should not cause issues as the one we encountered - can the provisioned be configured differently? And why this was never an issue in 1.19.11?

**Comment by andyzhangx** [comment]
actually for smb mount, gid, uid is only determined during mount, so if you set folloiwing mountOptions in your storage class or PV config, will that solve this issue?
```yaml
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=50000
  - gid=0
```
