### ISSUE TITLE
Cluster auto scaler not supporting Standard_HBxxx type nodes after update from 1.21 to 1.22

### ISSUE THREAD

**Issue by hterik** [Azure/AKS#2799]
**What happened:**

Create AKS cluster on v1.22.6
Create Nodepool with vm_size=Standard_HB120rs_v3.
Start pod demanding this node pool.
Nodes never start up

Using query     `AzureDiagnostics  | where Category == "cluster-autoscaler"` show following log: 
`E0219 12:52:11.365374 1 static_autoscaler.go:304] Failed to get node infos for groups: instance type "Standard_HB120rs_v3" not supported`

**What you expected to happen:**
Node pool scale up when pods are created.

**Anything else we need to know?:**

This was working before on v1.21

I found this commit in upstream autoscaler, which looks relevant, _adding_, support in 1.22 https://github.com/kubernetes/autoscaler/pull/4166/files,  which got released in https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.22.0 Aug 2021. So it's strange to see that it went from working to not working.

**Environment:**
kubectl version: 
`Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"299916054187763fc9be625667430fa45690357b", GitTreeState:"clean", BuildDate:"2022-01-30T03:25:00Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}`

Autoscaler version: In Diagnostic logs i see this `I0221 06:51:20.218040 1 main.go:415] Cluster Autoscaler 1.22.5 `

**Comment by nilo19** [comment]
cc @marwanad

**Comment by marwanad** [comment]
@hterik hey sorry for the delay - this should be fixed now. Let us know if you're still hitting the issue.
