### ISSUE TITLE
VM SKU availability in West Europe

### ISSUE THREAD

**Issue by slack** [Azure/AKS#280]
West Europe is under pressure for certain classes of VM SKUs. Expect limited availability for AKS clusters that are provisioned with Dv1, DSv1, Dv2 and DSv2 SKUs.

AKS clusters created with Av1, Av2, H, GS or LS series should experience fewer provision errors.

**Comment by sdktr** [comment]
That makes sense! Any hints on how to query for the available agent flavors? The available options, not their available capacity at first (the latter would be awesome of course)

**Comment by idelix** [comment]
Tried with Basic_A1 and Standard_A1_v2 unfortunately didn't worked anyway got the support ticket open so guess will wait until its fixed.

**Comment by YRollHid** [comment]
For testing purpose you can choose other region like "**canadaeast**" that is working fine...

**Comment by lehtiton** [comment]
Unfortunately we have to stick with westeurope since our service is using l2l GW that is provisioned to that subscription. Is there any WM size that would be available within westeurope right now? I have been testing with a few ones with no success.

**Comment by sdktr** [comment]
Any news on this one? I understand this service is not GA, but an Azure region being 'out-of-stock' is bad news, even for the preview..

**Comment by Zimmergren** [comment]
Since this is related to #279 I'll add my thoughts here. 

- Any Av1 and Av2 sizes for West Europe I've tried immediately fails. v1 and v2 alike.
- A2, A4, A8 has been tried multiple times.

I'll second @lehtiton question to know if there's _any_ available options, or _all_ of WEU for node sizes are currently considered in a broken state/under pressure?

**Comment by joakimhew** [comment]
Cannot create clusters with F-Series sizes either. Provisioning seems to be completely broken for West Europe?

**Comment by chryswoods** [comment]
I tried all sizes and could not build anything. Talked with MS support and they said it is broken for westeurope now. They are working to bring additional regions in Europe but there is no solution now. I needed it for next week, so was told to use another region (now in eastus which works fine).

**Comment by holmesb** [comment]
Premier Support just told me West Europe problem is due to lack of capacity.

**Comment by arjanschaaf** [comment]
running into similar problems

**Comment by slack** [comment]
@joakimhew @Zimmergren the SKU restrictions are coming from the underlying platform, not AKS. Sadly, I don't have clear line of sight into specific subscriptions. Azure support may be able to work with capacity group for clear guidance on a per-sub basis.

**Comment by lehtiton** [comment]
That command shows me the following VM sizes available:
disks             westeurope   Standard_LRS                                                                                   Standard
disks             westeurope   Premium_LRS                                                                                    Premium
snapshots         westeurope   Standard_LRS                                                                                   Standard
snapshots         westeurope   Premium_LRS                                                                                    Premium
snapshots         westeurope   Standard_ZRS                                                                                   Standard

Where can I see that what is the difference to for example Standard_D2_v3 if I just pick some of those available for running my cluster?

**Comment by Zimmergren** [comment]
@lehtiton the output of your command actually shows that the list is empty (no available VM's for that region). This is (reduced output for brevity) what it would look like, including the VM size names (example used: East US):

```
tobiaszimmergren@ZIMMERWIN:~$ az vm list-skus -l eastus -o table | grep -v "NotAvailableForSubscription"
ResourceType      Locations    Name                    Capabilities                       Tier      Size           Restrictions
----------------  -----------  ----------------------  ---------------------------------  --------  -------------  ---------------------------
availabilitySets  eastus       Classic                 MaximumPlatformFaultDomainCount=3
availabilitySets  eastus       Aligned                 MaximumPlatformFaultDomainCount=3
disks             eastus       Standard_LRS                                               Standard
disks             eastus       Premium_LRS                                                Premium
snapshots         eastus       Standard_LRS                                               Standard
snapshots         eastus       Premium_LRS                                                Premium
virtualMachines   eastus       Standard_B1ms           LowPriorityCapable=False           Standard  B1ms
virtualMachines   eastus       Standard_B1s            LowPriorityCapable=False           Standard  B1s
virtualMachines   eastus       Standard_B2ms           LowPriorityCapable=False           Standard  B2ms
virtualMachines   eastus       Standard_B2s            LowPriorityCapable=False           Standard  B2s
virtualMachines   eastus       Standard_B4ms           LowPriorityCapable=False           Standard  B4ms
virtualMachines   eastus       Standard_B8ms           LowPriorityCapable=False           Standard  B8ms
virtualMachines   eastus       Standard_DS1_v2         LowPriorityCapable=True            Standard  DS1_v2
virtualMachines   eastus       Standard_DS2_v2         LowPriorityCapable=True            Standard  DS2_v2
virtualMachines   eastus       Standard_DS3_v2         LowPriorityCapable=True            Standard  DS3_v2
virtualMachines   eastus       Standard_DS4_v2         LowPriorityCapable=True            Standard  DS4_v2
virtualMachines   eastus       Standard_DS5_v2         LowPriorityCapable=True            Standard  DS5_v2
virtualMachines   eastus       Standard_DS11-1_v2      LowPriorityCapable=True            Standard  DS11-1_v2
virtualMachines   eastus       Standard_DS11_v2        LowPriorityCapable=True            Standard  DS11_v2
virtualMachines   eastus       Standard_DS12-1_v2      LowPriorityCapable=True            Standard  DS12-1_v2
virtualMachines   eastus       Standard_DS12-2_v2      LowPriorityCapable=True            Standard  DS12-2_v2
```

**Comment by lehtiton** [comment]
@Zimmergren aa, you are right :-( , thanks!

**Comment by leoakinin** [comment]
@idelix this is an output from the last AKS deployment (was executed just an hour ago):
List of available regions for the resource type is 'eastus,westeurope,centralus,canadacentral,canadaeast'.

I'm afraid this list https://github.com/Azure/AKS/blob/master/preview_regions.md is not an actual one.

**Comment by jalberto** [comment]
Right now locations not working for me (not only fo rAKS but just to dpeloy a VM):
- westeurope
- francesouth
- francecentral

AKS will not deploy with any VM size in westeurope, I already have a critical ticket in azure (as this is affecting my production cluster) but not news yet.

**Comment by joakimhew** [comment]
@slack I get that it's the underlying platform. However, we're able to provision virtual machines with the same vm size in the resource group that we're trying with AKS.

This is the debug output from the command `az aks create --name temp-cluster -g ecto-dev --kubernetes-version 1.8.7 --location westeurope --node-vm-size 'Standard_D2_v3' --node-count 1`


msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/XXXXXXXX-33a7-XXXX-8047-7c1406a5de96/resourceGroups/ecto-dev/providers/Microsoft.ContainerService/managedClusters/temp-cluster?api-version=2017-08-31'
msrest.http_logger : Request method: 'PUT'
msrest.http_logger : Request headers:
msrest.http_logger :     'User-Agent': 'python/3.6.4 (Darwin-17.4.0-x86_64-i386-64bit) requests/2.18.4 msrest/0.4.27 msrest_azure/0.4.22 azure-mgmt-containerservice/3.0.1 Azure-SDK-For-Python AZURECLI/2.0.29'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Authorization': '*****'
msrest.http_logger :     'x-ms-client-request-id': 'XXXXXXXX-38aa-XXXX-beab-9801a79fb695'
msrest.http_logger :     'CommandName': 'aks create'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Content-Length': '918'
msrest.http_logger : Request body:
msrest.http_logger : {"location": "westeurope", "properties": {"dnsPrefix": "temp-clust-ecto-dev-9c83e6", "kubernetesVersion": "1.8.7", "agentPoolProfiles": [{"name": "nodepool1", "count": 1, "vmSize": "Standard_D2_v3", "dnsPrefix": "temp-clust-ecto-dev-9c83e6", "storageProfile": "ManagedDisks", "osType": "Linux"}], "linuxProfile": {"adminUsername": "ADMIN_USERNAME", "ssh": {"publicKeys": [{"keyData": "SSH_KEY_HERE"}]}}, "servicePrincipalProfile": {"clientId": "XXXXXXXX-5398-XXXX-a1b1-XXXXXXXXXXXX", "secret": "XXXXXXXX-54f7-XXXX-83d3-XXXXXXXXXXXX"}}}
msrest.http_logger : Response status: 400
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Length': '471'
msrest.http_logger :     'Content-Type': 'application/json'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-correlation-request-id': 'XXXXXXXX-974a-XXXX-bebc-XXXXXXXXXXXX'
msrest.http_logger :     'x-ms-request-id': 'XXXXXXXX-9740-XXXX-acec-XXXXXXXXXXXX'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'Server': 'nginx'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger :     'x-ms-routing-request-id': 'WESTEUROPE:20180405T082312Z:XXXXXXXX-974a-XXXX-bebc-XXXXXXXXXXXX'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Thu, 05 Apr 2018 08:23:12 GMT'
msrest.http_logger : Response content:
msrest.http_logger : b'{\n  "code": "BadRequest",\n  "message": "The VM size of Agent is not allowed in your subscription in location \'westeurope\'. Agent VM size \'Standard_D2_v3\' is available in locations: australiaeast,australiasoutheast,brazilsouth,canadacentral,canadaeast,centralindia,centralus,centraluseuap,eastasia,eastus,eastus2euap,japaneast,japanwest,koreacentral,koreasouth,northcentralus,northeurope,southcentralus,southindia,uksouth,ukwest,westcentralus,westindia,westus,westus2."\n }'
msrest.exceptions : Operation failed with status: 'Bad Request'. Details: The VM size of Agent is not allowed in your subscription in location 'westeurope'. Agent VM size 'Standard_D2_v3' is available in locations: australiaeast,australiasoutheast,brazilsouth,canadacentral,canadaeast,centralindia,centralus,centraluseuap,eastasia,eastus,eastus2euap,japaneast,japanwest,koreacentral,koreasouth,northcentralus,northeurope,southcentralus,southindia,uksouth,ukwest,westcentralus,westindia,westus,westus2.

**Comment by DonMartin76** [comment]
We're seeing exactly the same behaviour as @joakimhew - we are able to create "naked" VMs on `westeurope` using `az vm create`, but an `az aks create` fails with exactly that error message: "The VM size of Agent is not allowed in your subscription in location 'westeurope'. Agent VM size 'Standard_DS2_v2_Promo' is available in locations: ..."

**Comment by bscaspar** [comment]
Hey everyone,
We're aware of these issues and are prioritizing identifying the root cause and mitigating this ASAP. As you've noted, VM creation is possible in West Europe, if you can create a VM of a certain SKU you should be able to create an AKS cluster, so this is not currently a SKU availability issue. Unfortunately I can't provide you with more information at this point since we are still investigating, I'll be updating this thread with more information as we make progress on troubleshooting. 

For those with questions about other regions, the preview regions doc is up to date: [https://github.com/Azure/AKS/blob/master/preview_regions.md](https://github.com/Azure/AKS/blob/master/preview_regions.md)
And you can also see the regions that are available on the Azure products by region site: [https://azure.microsoft.com/en-us/global-infrastructure/services/](https://azure.microsoft.com/en-us/global-infrastructure/services/)

**Comment by sergiomcalzada** [comment]
Same problem here. I became crazy trying to imagine what was happening. Waiting for news.

PS: Good work with az aks :D

**Comment by ironstine** [comment]
Thanks for the update @bscaspar really looking forward to getting this resolved.

FYI - I'm also getting this same issue in westeurope when attempting to upgrade my cluster to 1.9.6 using: az aks upgrade.

**Comment by joaocc** [comment]
upgrading an existing cluster in WestEurope returns this:
```
Operation failed with status: 'Bad Request'. Details: The VM size of Agent is not allowed in your subscription in location 'westeurope'. Agent VM size 'Standard_DS2_v2' is available in locations: australiaeast,australiasoutheast,brazilsouth,canadacentral,canadaeast,centralindia,centralus,centraluseuap,eastasia,eastus,eastus2,eastus2euap,japaneast,koreacentral,koreasouth,northcentralus,northeurope,southcentralus,southindia,uksouth,ukwest,westcentralus,westindia,westus,westus2.
```

**Comment by bscaspar** [comment]
Update on this - multiple engineers from the AKS team continue to investigate and have identified what they believe is a possible root cause and are working to determine mitigation options. They continue to dedicate their full attention to getting this resolved as soon as possible. As a reminder, a workaround option is to deploy in a different region, please see available regions here: [https://github.com/Azure/AKS/blob/master/preview_regions.md](https://github.com/Azure/AKS/blob/master/preview_regions.md)

**Comment by sauryadas** [comment]
We have rolled out a fix and West Europe is ready for deployments. We are seeing create times around 30 mins. Thanks all for your patience. Please let us know if you see issues.

**Comment by markmcnaughton** [comment]
Thanks for the update, I am still having an issue creating an AKS cluster in westeurope

Using --node-vm-size Standard_D3_V2 or Standard_DS3_V2

I see:
Deployment failed. Correlation ID: ------ Provisioning of resource(s) for container service XXXXXXXX in resource group XXXXXX failed. Message: Deployment template validation failed: 'The provided value 'Standard_D3_V2' for the template parameter 'nodepool1VMSize' at line '1' and column '12726' is not valid. The parameter value is not part of the allowed value(s): 'Standard_A0,Standard_A1,Standard_A10,Standard_A11,Standard_A1_v2,Standard_A2,Standard_A2_v2,Standard_A2m_v2,Standard_A3,Standard_A4,Standard_A4_v2,Standard_A4m_v2,Standard_A5,Standard_A6,Standard_A7,Standard_A8,Standard_A8_v2,Standard_A8m_v2,Standard_A9,Standard_B1ms,Standard_B1s,Standard_B2ms,Standard_B2s,Standard_B4ms,Standard_B8ms,Standard_D1,Standard_D11,Standard_D11_v2,Standard_D11_v2_Promo,Standard_D12,Standard_D12_v2,Standard_D12_v2_Promo,Standard_D13,Standard_D13_v2,Standard_D13_v2_Promo,Standard_D14,Standard_D14_v2,Standard_D14_v2_Promo,Standard_D15_v2,Standard_D16_v3,Standard_D16s_v3,Standard_D1_v2,Standard_D2,Standard_D2_v2,Standard_D2_v2_Promo,Standard_D2_v3,Standard_D2s_v3,Standard_D3,Standard_D32_v3,Standard_D32s_v3,Standard_D3_v2,Standard_D3_v2_Promo,Standard_D4,Standard_D4_v2,Standard_D4_v2_Promo,Standard_D4_v3,Standard_D4s_v3,Standard_D5_v2,Standard_D5_v2_Promo,Standard_D64_v3,Standard_D64s_v3,Standard_D8_v3,Standard_D8s_v3,Standard_DS1,Standard_DS11,Standard_DS11_v2,Standard_DS11_v2_Promo,Standard_DS12,Standard_DS12_v2,Standard_DS12_v2_Promo,Standard_DS13,Standard_DS13-2_v2,Standard_DS13-4_v2,Standard_DS13_v2,Standard_DS13_v2_Promo,Standard_DS14,Standard_DS14-4_v2,Standard_DS14-8_v2,Standard_DS14_v2,Standard_DS14_v2_Promo,Standard_DS15_v2,Standard_DS1_v2,Standard_DS2,Standard_DS2_v2,Standard_DS2_v2_Promo,Standard_DS3,Standard_DS3_v2,Standard_DS3_v2_Promo,Standard_DS4,Standard_DS4_v2,Standard_DS4_v2_Promo,Standard_DS5_v2,Standard_DS5_v2_Promo,Standard_E16_v3,Standard_E16s_v3,Standard_E2_v3,Standard_E2s_v3,Standard_E32-16s_v3,Standard_E32-8s_v3,Standard_E32_v3,Standard_E32s_v3,Standard_E4_v3,Standard_E4s_v3,Standard_E64-16s_v3,Standard_E64-32s_v3,Standard_E64_v3,Standard_E64s_v3,Standard_E8_v3,Standard_E8s_v3,Standard_F1,Standard_F16,Standard_F16s,Standard_F16s_v2,Standard_F1s,Standard_F2,Standard_F2s,Standard_F2s_v2,Standard_F32s_v2,Standard_F4,Standard_F4s,Standard_F4s_v2,Standard_F64s_v2,Standard_F72s_v2,Standard_F8,Standard_F8s,Standard_F8s_v2,Standard_G1,Standard_G2,Standard_G3,Standard_G4,Standard_G5,Standard_GS1,Standard_GS2,Standard_GS3,Standard_GS4,Standard_GS4-4,Standard_GS4-8,Standard_GS5,Standard_GS5-16,Standard_GS5-8,Standard_H16,Standard_H16m,Standard_H16mr,Standard_H16r,Standard_H8,Standard_H8m,Standard_L16s,Standard_L32s,Standard_L4s,Standard_L8s,Standard_M128-32ms,Standard_M128-64ms,Standard_M128ms,Standard_M128s,Standard_M64-16ms,Standard_M64-32ms,Standard_M64ms,Standard_M64s,Standard_NC12,Standard_NC12s_v2,Standard_NC12s_v3,Standard_NC24,Standard_NC24r,Standard_NC24rs_v2,Standard_NC24rs_v3,Standard_NC24s_v2,Standard_NC24s_v3,Standard_NC6,Standard_NC6s_v2,Standard_NC6s_v3,Standard_ND12s,Standard_ND24rs,Standard_ND24s,Standard_ND6s,Standard_NV12,Standard_NV24,Standard_NV6'.'.. Details:

**Comment by sauryadas** [comment]
Can you use the following for size Standard_D3_v2 ... note that its small v not capital...

**Comment by markmcnaughton** [comment]
It looks like that was it. pebkac. Thanks so much, it's been creating for a while, but it definitely would have failed by now.

**Comment by shahiddev** [comment]
Thanks @sauryadas for the update
I managed to create a single node standard_b1ms in West Europe just now

**Comment by joaocc** [comment]
Working (sort of fine). On one of the clusters (2 nodes), the upgrade was successful, but only 1 node was reported by aks, even though the other one existed. After removing the pending node, everything looks fine.

**Comment by idelix** [comment]
Works for me as well was able to create aks on single Standard D2s v3 node in WE

**Comment by Zimmergren** [comment]
Thanks for the updates @bscaspar and @sauryadas. 
Verified this morning in West Europe: 
- Cluster with 5 nodes: Standard_A4m_v2.
- Cluster with 3 nodes: Standard_A4.
- Scaling existing A4-cluster from 1 to 3 nodes successfully.

All operations are successful.

_Questions:_ 
You say creation-times of around 30 minutes. Will this persist, and is it only for creation? Scaling nodes up and down in the existing clusters took no more than a couple of moments, while the creation indeed took quite some time.

**Comment by ironstine** [comment]
Confirming upgrade to 1.9.6 was successful, thanks for fixing.

**Comment by DonMartin76** [comment]
Can also confirm `az aks create` was successful this morning. Thanks!

**Comment by jalberto** [comment]
@sauryadas can you give us any detail about the root issue?

**Comment by sabbour** [comment]
You can check what VM SKUs are available for your subscription/region using the below:

```
declare region=westeurope
az vm list-skus -l $region --query '[?resourceType==`virtualMachines` && restrictions==`[]`]' -o table
```

If the output is empty, this means you have no availability to deploy in this region.
Other wise, you get an output similar to this:

```
ResourceType     Name                    Tier      Size
---------------  ----------------------  --------  -------------
virtualMachines  Standard_B1ms           Standard  B1ms
virtualMachines  Standard_B1s            Standard  B1s
virtualMachines  Standard_B2ms           Standard  B2ms
virtualMachines  Standard_B2s            Standard  B2s
virtualMachines  Standard_B4ms           Standard  B4ms
virtualMachines  Standard_B8ms           Standard  B8ms
```

**Comment by sdktr** [comment]
Works for me as well! Deployment time took up to an hour in my case, using 2 Ds_v3 VM. Curious where that time goes into and what the target deployment time is for GA?

**Comment by alanraison** [comment]
I am having this issue today:
```
Operation failed with status: 'Bad Request'. Details: The VM size of Agent is not allowed in your subscription in location 'westeurope'. Agent VM size 'Standard_DS1_v2' is available in locations: australiaeast,australiasoutheast,canadacentral,canadaeast,centralindia,centralus,centraluseuap,eastus,eastus2euap,japanwest,koreasouth,southcentralus,southeastasia,southindia,ukwest,westindia,westus,westus2.
```

**Comment by bscaspar** [comment]
According to the error message, your subscription is not able to create Standard_DS1_V2 SKU VMs in West Europe. If you would like to deploy with that SKU in West Europe, you will need to open a free subscription support request to request access to that region.

**Comment by shahiddev** [comment]
@alanraison I'm guessing you used the aks create command without specifying the vm size ? - if so, it defaults to Standard_DS1_V2 but that sku does not appear to be available in West Europe for some of us.
Change the V2 to V3 and hopefully that works

**Comment by markslater** [comment]
Has this issue resurfaced?  Right now, I get:

```
mark@Azure:~$ az vm list-skus -l westeurope -o table | grep -v "NotAvailableForSubscription"
ResourceType      Locations    Name                    Capabilities                                                           Tier      Size           Restrictions                                         Zones
----------------  -----------  ----------------------  ---------------------------------------------------------------------  --------  -------------  --------------------------------------------------------------  -------
availabilitySets  westeurope   Classic                 MaximumPlatformFaultDomainCount=3
availabilitySets  westeurope   Aligned                 MaximumPlatformFaultDomainCount=3
disks             westeurope   Standard_LRS                                                                                   Standard
disks             westeurope   Premium_LRS                                                                                    Premium
snapshots         westeurope   Standard_LRS                                                                                   Standard
snapshots         westeurope   Premium_LRS                                                                                    Premium
snapshots         westeurope   Standard_ZRS                                                                                   Standard
mark@Azure:~$
```
If I understand correctly, the dearth of `virtualMachine` resources means I can't currently run `az aks create` in this region.

**Comment by sauryadas** [comment]
you can ignore the results of that command. it needs to be fixed. Is your az aks create command failing?

**Comment by markslater** [comment]
Yes:
```
Operation failed with status: 'Bad Request'. Details: The VM size of Agent is not allowed in your subscription in location 'westeurope'. Agent VM size 'Standard_DS1_v2' is available in locations: australiaeast,australiasoutheast,canadacentral,canadaeast,centralindia,centralus,centraluseuap,eastus,eastus2euap,japanwest,koreasouth,northcentralus,southcentralus,southeastasia,southindia,ukwest,westindia,westus,westus2.
```
I guess that message is a bit misleading because:
```
mark@Azure:~$ az aks create -n foo -g azurus --location ukwest
The provided location 'ukwest' is not available for resource type 'Microsoft.ContainerService/managedClusters'. List of available regions for the resource type is 'eastus,westeurope,centralus,canadacentral,canadaeast'.
mark@Azure:~$
```
However, for now, I've had success with `--location eastus`

**Comment by dasuma** [comment]
by commando dont work, i created in portal and form worked
