### ISSUE TITLE
oidc token generated from AAD flow doesn't work when used from an external app

### ISSUE THREAD

**Issue by ashu8912** [Azure/AKS#2804]
**What happened**:
I have an AKS cluster with AAD configured in the AD app registrations I have an application, My aks cluster has an app that can handle oidc authentication when I go through the oidc flow of my app I do get a token but i am not able to access the cluster resources with that token, I tried the azure shell login and the token I get from there works but the token i receive from the oidc flow of AAD app doesn't work
**What you expected to happen**:
My app generated token should allow me to access the cluster resources
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"64f59d5ed82b0e695c8c8e8df54854c0f736bc55", GitTreeState:"clean", BuildDate:"2022-01-30T02:57:07Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miwithro** [comment]
@ashu8912 Did you create a role assignment with the client id of the app registration associated with the token?

https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac#create-role-assignments-for-users-to-access-cluster

**Comment by ashu8912** [comment]
@miwithro I created a clusterrole and clusterrolebinding in the cluster that grants necessary rights to my azure ad group, will it not work with that??

**Comment by miwithro** [comment]
@ashu8912 for this to work you need to enable OIDC Issuer and build a trust between the cluster and AAD.  Then the flow will work end to end.   https://azure.github.io/azure-workload-identity/docs/installation.html
