### ISSUE TITLE
Please consider cosign for image verification

### ISSUE THREAD

**Issue by derek-burdick** [Azure/AKS#2806]
**Anything else we need to know?**:
CoSign appears to have more broad support than other signing solutions. The beauty of cosign is that the signature can move from registry to registry and stays consistent. Please consider solution to validate signed containers using cosign.
https://github.com/sigstore/cosign

**Comment by miwithro** [comment]
@derek-burdick We have Notary V2 we are working on for this.

https://github.com/Azure/notation-azure-kv/blob/main/docs/nv2-sign-verify-aks.md

**Comment by derek-burdick** [comment]
From the perspective of creating and distributing containers, and consuming them, cosign capabilities more closely matches what my customers want, who are primarily using private ACR and GCR registries. The kubernetes projects seem to be moving towards Cosign, along with a number of the ecosystems.
