### ISSUE TITLE
BuiltIn Azure Policy K8sAzureBlockHostNamespace misses parameter "excludedContainers"

### ISSUE THREAD

**Issue by Bananenbieger1234** [Azure/AKS#2808]
**What happened**:

I would like to have a parameter "excludedContainers" for the azure policy 47a1ee2f-2a2a-4576-bf2a-e0e36709c2b8 (Kubernetes cluster containers should not share host process ID or host IPC namespace) like other policies already have.

**What you expected to happen**:
Parameter "excludedContainers" works.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.4
- Size of cluster (how many worker nodes are in the cluster?): 4
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): HTTP microservices
- Others:

**Comment by miwithro** [comment]
@fseldow

**Comment by fseldow** [comment]
Instead of excludedContainers that is based on container name, Plan to introduce imageExemption for this feature request. Because name-based exclusion is easily bypassed.

**Comment by Bananenbieger1234** [comment]
You mean to exclude based on docker-image?
Like `...azurecr.io/prometheus/node-exporter:v1.2.2` ? If yes, I think it would be good to do this by ignoring image tag and digest (just image name), otherwise you may have problems during version upgrades.

So, exclude `...azurecr.io/prometheus/node-exporter` for example.

**Comment by miwithro** [comment]
@Bananenbieger1234 that is correct.

**Comment by fseldow** [comment]
@Bananenbieger1234 it will be prefix. Below is an example constraintTemplate with desciption
https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/containerlimits/template.yaml

For example it will be ...azurecr.io/prometheus/node-exporter*
