### ISSUE TITLE
Nodepool stop or start delete nodes in scaleDownMode "Deallocate"

### ISSUE THREAD

**Issue by alk-jozog** [Azure/AKS#2810]
**What happened**:
We use 2 preview features on some nodepools:
* scale down mode "deallocate" https://docs.microsoft.com/en-us/azure/aks/scale-down-mode
* nodepool stop/start https://docs.microsoft.com/en-us/azure/aks/start-stop-nodepools

When starting or stopping the nodepool, existing VMSS instances (running or deallocated) are deleted.

**What you expected to happen**:
Stopping nodepool should deallocate running VMSS instances instead of deleting them.
Starting nodepool should not affect VMSS instances and let autoscaler start existing instances or create new ones if needed.

**How to reproduce it (as minimally and precisely as possible)**:
* Create a nodepool with scaledown mode set to "deallocate" and autoscaler (min nodes = 0) enabled.
* Run `az aks nodepool stop` or `az aks nodepool start`

**Anything else we need to know?**:
Azure Support has confirmed the issue and advised to open an issue here as we're using preview features.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.7
- Size of cluster (how many worker nodes are in the cluster?): varies from 0 to ~5
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): ephemeral test environnements
- Others:

**Comment by wangyira** [comment]
@qpetraroia can you take a look?
