### ISSUE TITLE
[Feature Request] LoadBalancer SKU annotation

### ISSUE THREAD

**Issue by philwelz** [Azure/AKS#2811]
As we of today can configure the SKU of the LoadBalancer via [Cloud Controller Config](https://kubernetes-sigs.github.io/cloud-provider-azure/topics/loadbalancer/#loadbalancer-skus) it would be great if we can just use an annotation.

This would be also helpful as the Cloud Controller Config will be setting the SKU globally for all LoadBalancers in that specific Cluster. There could be use cases that we only need one LoadBalancer with the `Standard` SKU as we for example need an SLA for this specific LoadBalancer. The default should stay `basic`.

Proposal:
```
service.beta.kubernetes.io/azure-load-balancer-sku: basic
service.beta.kubernetes.io/azure-load-balancer-sku: standard
```

**Comment by philwelz** [comment]
Could you maybe take a look at this idea @palma21 ?

**Comment by philwelz** [comment]
@phealy can you maybe take a look ?

**Comment by feiskyer** [comment]
This is not possible as a single VMSS/VM could only be added to 1 external LB

**Comment by philwelz** [comment]
@feiskyer ok and why i can't use a Standard LB with an SLA for this 1 external LoadBalancer? Therefore i would need the annotation.
