### ISSUE TITLE
http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused

### ISSUE THREAD

**Issue by gsriramit** [Azure/AKS#2812]
**What happened**:
My setup has a 2 node AKS cluster that has outbound configured with Azure Firewall. The pods are configured with AAD Pod Identity to be able to access the key vault to fetch secrets and certificates. I have configured the firewall with the necessary rules to allow outbound access to Azure resources. Access to the key vault is configured through the Secrets Store CSI driver. When the pod are deployed, when in the "container creating" phase, the kubelet throws the following error

  Warning  FailedMount  14s (x7 over 46s)  kubelet            MountVolume.SetUp failed for volume "secrets-store01-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/ubuntu-deployment-55f6774b-cdz8p, err: rpc error: code = Unknown desc = failed to mount objects, error: **failed to get keyvault client: failed to get authorizer for keyvault client: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused**

The secret store integration from AKS works seamlessly in a Load Balancer outbound mode. I am trying to figure out if this is due to 
insufficient access rules in the firewall for the pods to complete an outbound https request to the key vault successfully. Or, is this related to connections/ports not configured on the loopback?

**What you expected to happen**:
Https requests from the pod to the key vault should be completed successfully and the certificate should be mounted

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an AKS cluster with UDR as the outbound type
2. Create a Keyvault and load a certificate
3. Configure the AAD pod identity and Secrets-Store-CSI driver in the cluster
4. Deploy a test workload deployment (as simple as an ubuntu minimal image) that uses the pod MI to access the KV

**Anything else we need to know?**:
Log output from the workload pod that stays in the container creating mode

srvadmin@DESKTOP-LP3ON48:/mnt/c/DevApplications/KubernetesPlayground/aks-azfirewall-tls$ kubectl describe pod ubuntu-deployment-55f6774b-cdz8p
Name:           ubuntu-deployment-55f6774b-cdz8p
Namespace:      default
Priority:       0
Node:           aks-nodepool1-15872125-vmss000001/10.42.1.35
Start Time:     Fri, 25 Feb 2022 13:13:50 +0530
Labels:         app=curlpod
                pod-template-hash=55f6774b
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/ubuntu-deployment-55f6774b
Containers:
  workload-egress:
    Container ID:
    Image:         ubuntu
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      while true; do sleep 1; done
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /mnt/secrets-store from secrets-store01-inline (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zqg8r (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  secrets-store01-inline:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            secrets-store.csi.k8s.io
    FSType:
    ReadOnly:          true
    VolumeAttributes:      secretProviderClass=class-firewallrootca-cert
  kube-api-access-zqg8r:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    46s                default-scheduler  Successfully assigned default/ubuntu-deployment-55f6774b-cdz8p to aks-nodepool1-15872125-vmss000001
  Warning  FailedMount  14s (x7 over 46s)  kubelet            MountVolume.SetUp failed for volume "secrets-store01-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/ubuntu-deployment-55f6774b-cdz8p, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get authorizer for keyvault client: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused

View of the pods in the default namespace
![image](https://user-images.githubusercontent.com/13979783/155700573-0ad5ac45-f948-4751-b3e6-e513be70d9b3.png)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.9
- Size of cluster (how many worker nodes are in the cluster?) 2 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Infra design test is the purpose, so a minimal test workload 
- Others:

Any help is much appreciated

**Comment by diaa-abushaqra** [comment]
I have the same problem. Why isn't the issue getting attention?

**Comment by trevonmckay** [comment]
I am also receiving this error from my AKS cluster
```
failed
  to get keyvault client: failed to get authorizer for keyvault client: Get
  "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp
  127.0.0.1:2579: connect: connection refused
```

**Comment by gsriramit** [comment]
@diaa-abushaqra @trevonmckay 
I am not sure if there is a certain fix for the issue and I do not see the AKS team responding to this either :(

@Azure/aks-leads
Folks, any comments or updates on this issue would help!!

**Comment by winterrobert** [comment]
I ran into the same problem on AKS with csi-secrets-store-provider-azure 1.2.0 and Kubernetes 1.22.

**Comment by GarinKartes** [comment]
im having this issue on 1.21.7

**Comment by hacker1db** [comment]
I am having issues with this as well. Thanks

**Comment by georgewfisher** [comment]
First open bash on a pod and run the following to try to get the MSI token for your pod:
`curl -v "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://vault.azure.net" -H "Metadata: true"`

In my case, I got back:
`{"error":"invalid_request","error_description":"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"}`

For me what worked was:
1. Using the correct configuration for my SecretProviderClass for user defined managed identity: https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access#use-a-user-assigned-managed-identity
2. Including `userAssignedIdentityID: <client-id>` in my SecretProviderClass config
