### ISSUE TITLE
Issue with ingress rules and SSL certificates while using Wildcard certificate

### ISSUE THREAD

**Issue by TDTcloudteam** [Azure/AKS#2813]
1. Purchased Azure App service certificate - Type of Wildcard domain
2. Mapped this Trusted SSL with Application gateway and the backend pool is of AKS(Ingress LB)
3. Communication on port 80 is successful but when on SSL(443) it is failing with the below error

Error:
The Common Name (CN) of the backend server certificate does not match the host header entered in the health probe configuration (v2 SKU) or the FQDN in the backend pool (v1 SKU). Verify if the hostname matches with the CN of the backend server certificate. To learn more visit - https://aka.ms/backendcertcnmismatch.

Steps Executed:
1.Trusted SSL is also mapped with AKS backend
2. Ingress LByaml file 
apiVersion: [networking.k8s.io/v1](http://networking.k8s.io/v1)
kind: Ingress
metadata:
  name: hello-world-ingress
  annotations:
    [kubernetes.io/ingress.class](http://kubernetes.io/ingress.class): nginx
    [nginx.ingress.kubernetes.io/ssl-redirect](http://nginx.ingress.kubernetes.io/ssl-redirect): "false"
    [nginx.ingress.kubernetes.io/use-regex](http://nginx.ingress.kubernetes.io/use-regex): "true"
    [nginx.ingress.kubernetes.io/proxy-body-size](http://nginx.ingress.kubernetes.io/proxy-body-size): 16m
spec:
  tls:
  - hosts:
    - '*.test.com'
    secretName: aks-ingress-tls
  rules:
  - host: test.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginxservice
            port:
              number: 80

**Comment by palma21** [comment]
your wildcard cert is matches what's on hosts in the spec above?
