### ISSUE TITLE
Http Proxy Preview Feature: Standard_D*as_v5 VM sizes ignore proxy options

### ISSUE THREAD

**Issue by pcallewaert** [Azure/AKS#2814]
**What happened**:
I've tried to deploy a new kubernetes cluster with `Standard_D4as_v5` and `Standard_D2as_v5` VM sizes. However, in the logs I could see no connections on the HTTP proxy, but instead the VM's tried to connect directly to the NVA (the cluster is configured with `userDefinedRouting` to route the traffic to our NVA)
(It seems the first connection is to `mcr.microsoft.com`, after this the kubernetes cluster went to the `Failed` state)

Using `Standard_D4as_v4` or `Standard_B2s` VM sizes worked like expected.

The AKS cluster was configured properly:

```json
"httpProxyConfig": {
      "httpProxy": "http://<redacted>/",
      "httpsProxy": "http://<redacted>/",
      "noProxy": [
        "10.99.0.0/20",
        "10.0.0.0/16",
        "localhost",
        "127.0.0.1",
        "168.63.129.16",
        "169.254.169.254",
        "konnectivity",
        "<redacted>.privatelink.westeurope.azmk8s.io"
      ],
      "trustedCa": null
    },
```

**What you expected to happen**:

That all VM sizes would work the same, or some documentation which VM sizes are working and which aren't.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy AKS cluster with the http proxy feature with `Standard_D2as_v5` VM size in the default node pool.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Both `1.21.9` and `1.22.6`
- Size of cluster (how many worker nodes are in the cluster?): Created cluster with 1 node pool with autoscaling 1-3.
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): None
- Others: Was deployed with terraform, but I confirmed if the config was OK with `az aks list`

**Comment by miwithro** [comment]
@alexeldeib

**Comment by alexeldeib** [comment]
@pcallewaert there should be no distinction between VM sizes in this logic. You've verified the same behavior on new clusters in same region of the alternate VM sizes? I know you said it works as expected with other sizes, but I wanted to verify brand new clusters with same configuration etc created now exhibit this "unique" behavior for v5 skus.

**Comment by pcallewaert** [comment]
Hi @alexeldeib, the setup was created every time from scratch with the same terraform code, the only change was the size of the node pools. I tried first with the v5 sizes and was hitting this problem every time. After changing the VM Size to a v4 size the creation of the kubernetes was successful.

**Comment by alexeldeib** [comment]
believe we figured this one out, there was a race in early VM provisioning which would trigger more or less frequently based on sku. we fixed the race in https://github.com/Azure/AgentBaker/pull/1926 which was in 20220703 AKS RP release which should be completed a while ago per https://releases.aks.azure.com/webpage/index.html

can you try this again and see if you can repro? otherwise think we can close this out.

**Comment by alexeldeib** [comment]
should be fixed now
