### ISSUE TITLE
Question - Specifying Nvidia Driver Version for GPU Nodes in AKS

### ISSUE THREAD

**Issue by robincher** [Azure/AKS#2817]
Hi,

This is more of a question rather than bug/feature request

```
Technical Details:
- AKS Version: 1.22.4
- GPU Node VM Type: Standard_NC6s_v2
```
Currently we have a few GPU-optimised node in Azure Kubernetes Service, and manage to enable the gpu device plugin successful as describe [here](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/aks/gpu-cluster.md#confirm-that-gpus-are-schedulable) by implementing it manually with its Daemonset

My question is , is there anyway we can specific the nvidia driver version, as we need to fix our driver version **430.30** due legacy requirements. 

Or if there are any release/tag that support the Nvidia driver **430.30** version. I am unable to find any information or any documents on it.

This is the device plugin release that we are using now:

```image: mcr.microsoft.com/oss/nvidia/k8s-device-plugin:1.1 ```

Thanks!
Robin

**Comment by alexeldeib** [comment]
you can force a specific version by uninstalling the existing version via daemonset and forcing something else: ` /usr/bin/nvidia-uninstall --silent`

note that you're probably on your own for gpu driver support if you go that route
