### ISSUE TITLE
Node Reports ErrorCreatingNNC with podsubnetpreview enabled.

### ISSUE THREAD

**Issue by g0pinath** [Azure/AKS#2818]
**What happened**:
When deploying an AKS cluster via terraform, the cluster gets created however the helm charts started to fail as the pods got stuck on containercreating status. All of the pods logged the below erorr via kubectl describe pods

 Warning  FailedCreatePodSandBox  0s (x4 over 38s)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "2f3ddbcc07cca4c348f5f1fb45cf458d0b670566248360182cc829e1c15fed63": Post "http://localhost:10090/network/requestipconfig": dial tcp 127.0.0.1:10090: connect: connection refused

While inspecting the nodes their status reported as ready but describe showed the below error.

  Type     Reason                   Age                From                    Message
  ----     ------                   ----               ----                    -------
  Normal   NodeHasSufficientMemory  17m (x7 over 17m)  kubelet                 Node aks-syspool-18711223-vmss000000 status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    17m (x7 over 17m)  kubelet                 Node aks-syspool-18711223-vmss000000 status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     17m (x7 over 17m)  kubelet                 Node aks-syspool-18711223-vmss000000 status is now: NodeHasSufficientPID
  Normal   Starting                 16m                kube-proxy              Starting kube-proxy.
  Normal   NodeReady                16m                kubelet                 Node aks-syspool-18711223-vmss000000 status is now: NodeReady
  Normal   CreatedNNC               16m (x4 over 17m)  dnc-rc/node-reconciler  Created NodeNetworkConfig aks-syspool-18711223-vmss000000
  Warning  ErrorCreatingNNC         16m (x3 over 17m)  dnc-rc/node-reconciler  Error creating NodeNetworkConfig aks-syspool-18711223-vmss000000, err = nodenetworkconfigs.acn.azure.com "aks-syspool-18711223-vmss000000" already exists
  Normal   Starting                 3m10s              kube-proxy              Starting kube-proxy.

I tried kubectl debug (https://zigmax.net/aks-ssh-to-an-aks-node-with-kubectl/) and I couldnt even connect to the node.

This worked fine on Feb 22nd and I am not sure what changed. Noticed that disabling the podsubnetpreview feature fixed this, although this worked on Feb 22nd.

The nodes-subnet has a route table associated with default route sending to internet. The pods-subnet has 4000+ available IPs and I can repro the issue even with 3 nodes - one node per pool.

Use the attached to repro the issue.
[aks-issue.zip](https://github.com/Azure/AKS/files/8160816/aks-issue.zip)

**Comment by flyingcamilo** [comment]
Hey @g0pinath! Just wondering: Have you already solved it? Have the same issue here.

**Comment by TomasKohout** [comment]
Hi guys,

we have the same issue. azure-cns is unable to start and fails on [this](https://github.com/Azure/azure-container-networking/blob/041939115337d2b070663a133fc7604f015f57b5/cns/service/main.go#L1067) error message.

**Comment by g0pinath** [comment]
> Hey @g0pinath! Just wondering: Have you already solved it? Have the same issue here.

@flyingcamilo - not yet, there has been no updates on this issue.

**Comment by paulgmiller** [comment]
As noted in https://github.com/Azure/AKS/issues/3132 the already exist warnings are fine and will be removed in current rollout. 

But seems like you still couldn't connect. If this is still an issue please raise a support ticket
