### ISSUE TITLE
HTTP application routing - external-dns version 0.10.1 fails to update dns zone on k8s 1.22.6

### ISSUE THREAD

**Issue by AndreasLudviksen** [Azure/AKS#2819]
**What happened**:
We have enabled the feature 'HTTP application routing' for our dev AKS cluster.
It was working okay until we upgraded k8s to 1.22.6.
After the upgrade the 'external-dns' pod reports the following issue:
```
time="2022-03-01T11:12:50Z" level=error msg="azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/****-***-***-***-***/resourceGroups/***/providers/Microsoft.Network/dnsZones?api-version=2018-05-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post \"http://dummy\": dial tcp: lookup dummy on 10.10.0.10:53: no such host'"
```

When I manually overwrite the deployment to use external-dns version 0.10.2, the problem disappears, and the feature works.
Problem is it gets configured back to 0.10.1 in a matter of seconds/minutes.

There is a similar issue on kubernetes-sigs/external-dns [here](https://github.com/kubernetes-sigs/external-dns/issues/2383)

**What you expected to happen**:
Expect the external-dns to be able to update the dns zone for 'HTTP application routing'.

**How to reproduce it (as minimally and precisely as possible)**:
Enable feature in an AKS Cluster with k8s 1.22.6 installed.

**Comment by Skyere** [comment]
I have the same issue(

**Comment by nerddtvg** [comment]
While my error was slightly different, I found that it was because RBAC was enabled by default on a new 1.22 cluster (not sure if this was Azure or Terraform) and I had deployed the template without the RBAC service account resources.

```plain
time="2022-05-11T20:44:43Z" level=info msg="Using inCluster-config based on serviceaccount-token"
time="2022-05-11T20:44:43Z" level=info msg="Created Kubernetes client https://10.0.0.1:443"
time="2022-05-11T20:45:43Z" level=fatal msg="failed to sync *v1.Endpoints: context deadline exceeded"
```

Redeployed with: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/azure.md#manifest-for-clusters-with-rbac-enabled-cluster-access

**Comment by adalfa** [comment]
Hello to all,

in the documentation
https://docs.microsoft.com/en-us/azure/aks/http-application-routing

in the limitation


Limitations
HTTP application routing doesn't currently work with AKS versions 1.22.6+


is this issue related to the note?

thanks

**Comment by catmanjan** [comment]
I too noticed this limitation note, I am running 1.23.8, does it the + include 1.23 or is it only the 1.22 versions?

**Comment by DavidMtbg** [comment]
So is this how HTTP Application Routing dies? Because East US region doesn't allow provisioning <1.22.11 at this point. 🤷🏻

**Comment by adalfa** [comment]
I think, given the attention of @Azure/aks-leads, the feature is definitely dead

**Comment by palma21** [comment]
> Hello to all,
> 
> in the documentation https://docs.microsoft.com/en-us/azure/aks/http-application-routing
> 
> in the limitation
> 
> Limitations HTTP application routing doesn't currently work with AKS versions 1.22.6+
> 
> is this issue related to the note?
> 
> thanks

yes, very much so. This feature never made GA and is deprecated in favor of https://learn.microsoft.com/en-us/azure/aks/web-app-routing 

We'll take action to note this directly on the docs while this feature goes through deprecation.

**Comment by sabbour** [comment]
Updating docs. https://github.com/MicrosoftDocs/azure-docs-pr/pull/230282
