### ISSUE TITLE
How to use encrypted volume in AKS ?

### ISSUE THREAD

**Issue by sukrit007** [Azure/AKS#282]
I need to use encrypted volume for stateful sets using managed disks.  How can we enable that in IAAS VM created by AKS for para-virtual volumes created in k8s?

**Comment by andyzhangx** [comment]
If VM is encrypted already, when adding a data disk to VM, it will be encrypted also, see detailed doc:
https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption#disk-encryption-deployment-scenarios-and-user-experiences

**Comment by sukrit007** [comment]
@andyzhangx  How would you ensure that VM encrypted by aks is encrypted?  I am not seeing any option to pass to ```az aks create``` for creating encrypted VM.

**Comment by andyzhangx** [comment]
It's not supported by aks now, you need to run `az vm encryption enable` to encrypt every node after k8s cluster set up following above link

**Comment by neumanndaniel** [comment]
AKS is using Managed Disks for the agent nodes and Managed Disks are encrypted by default with Storage Service Encryption.

https://azure.microsoft.com/en-us/blog/azure-managed-disks-sse/

**Comment by sukrit007** [comment]
@neumanndaniel  thanks for that information.  That was helpful.   For what we need, storage service encryption will suffice.
