### ISSUE TITLE
Windows Nodes Don't Currently Support Out of Memory Eviction (OOMKILL)

### ISSUE THREAD

**Issue by ojfw20** [Azure/AKS#2820]
**What happened**: Pods fail to start on a Windows nodepool after resource demands increase past node capacity. Pods on a Windows node also start paging to disk when the node runs out of memory.

**What you expected to happen**: OOMKill feature triggers scheduling of pods on a node with free memory, allowing pods to start as expected.

**How to reproduce it (as minimally and precisely as possible)**: Overallocate a Windows node with pods, trigger pods to request more memory than the node can provide.

**Anything else we need to know?**: We have been informed that OOMKill is not support on Windows nodes. This seems to be a gaping hole in the feasibility of using Windows nodepools for any sort of elastic scalability. We would like to see OOMKill supported on Windows nodepools.

https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#kubelet-compatibility agrees, and states that: 

- The (Windows) kubelet does not take OOM eviction actions

- Eviction by using --enforce-node-allocable is not implemented

- Eviction by using --eviction-hard and --eviction-soft are not implemented

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.7
- Size of cluster (how many worker nodes are in the cluster?): 4 Windows Nodes, 2 Linux Nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.):

**Comment by ojfw20** [comment]
Hi! Any update on this?

**Comment by AbelHu** [comment]
I think that this needs upstream support. cc @allyford

**Comment by ojfw20** [comment]
bump @allyford

**Comment by AbelHu** [comment]
Reference https://github.com/kubernetes/kubernetes/issues/119184

**Comment by allyford** [comment]
> Reference [kubernetes/kubernetes#119184](https://github.com/kubernetes/kubernetes/issues/119184)

Based on the update here, creating a separate feature request specifically for adding the new kubelet parameters from upstream into AKS. See #4068

**Comment by allyford** [comment]
Closing this issue. Upstream investigations of node conditions that lead to evictions can be found here: https://github.com/kubernetes/kubernetes/issues/119184

Now that upstream has supported memory based eviction for windows, using #4068 for tracking
