### ISSUE TITLE
Auto upgrade and spot node incompatible

### ISSUE THREAD

**Issue by rogelioamancisidor** [Azure/AKS#2822]
I enabled the auto-upgrade channel in my cluster with
```
az aks update --resource-group myResourceGroup --name myAKSCluster --auto-upgrade-channel stable
```
together with a maintenance window
```
az aks maintenanceconfiguration add -g MyResourceGroup --cluster-name myAKSCluster --name default --weekday Monday  --start-hour 1
```
When I try to deploy a spot node
```
az aks nodepool add --resource-group myResourceGroup --cluster-name myAKSCluster --priority Spot
```
I get this error message `(BadRequest) Enabled Auto Upgrade on cluster with spot pool is not allowed. And Spot pool cannot be added for Auto Upgrade enabled cluster.`

Is the auto-upgrade function incompatible with spot price nodes?

**kubernetes version:** 1.21.9

**Comment by EPinci** [comment]
This is blocking me as well.
@palma21 @miwithro can you help route this issue?

**Comment by miwithro** [comment]
@kaarthis please investigate.

**Comment by paulgmiller** [comment]
See #2134. Once spot pool upgrade is supported this will no longer block.

**Comment by kaarthis** [comment]
Resolving this as we enabled Upgrades for Spot nodepools recently : https://docs.microsoft.com/en-us/azure/aks/spot-node-pool
