### ISSUE TITLE
Run shell script during AKS node pool or when new pool is created

### ISSUE THREAD

**Issue by PRAVEEN-PYDIMARRI** [Azure/AKS#2828]
I would like to run shell script or custom data via AKS node pool from terraform script.
I have successfully ran custom data or shell script via terraform VMSS. So in the same way would like to know how to run the shell script during provisioning of AKS node pool.Much appreciated your help.

**Comment by PRAVEEN-PYDIMARRI** [comment]
Any update please. I need this to be done ASAP as I have been looking for this since a month but no proper solution. Need to show the solution to customer.

**Comment by NissesSenap** [comment]
Create a DS with way to much access and have it run on your nodes. You can store your bash script In a configmap and if it needs updated you can easily do that. 

Depending on what you are trying to there are a number of operators that solves these kind of issues.

**Comment by PRAVEEN-PYDIMARRI** [comment]
I would like to install newrelic infra agent in each and every node when its created automatically during scale up of instance .I need to achieve through terraform script. Please help me to find a solution for this.Through terraform I need to run this automation so that when ever ASK is created and when new instance spin up newrelic agent installation should be done automatically and it should show the metrics in newrelic dashboard. I have achieved this through VMSS via terraform script but the same wanted to implement for ASK node pool.

**Comment by NissesSenap** [comment]
Well that's not that hard, https://github.com/XenitAB/terraform-modules/tree/main/modules/kubernetes/new-relic
We do some special things in there and the helm chart probably needs an update.

We will deprecate our usage of new relic soon (we went with grafana cloud) so don't use the module for new relic config.

**Comment by PRAVEEN-PYDIMARRI** [comment]
Thanks for the links.So the above terraform script will install newrelic infra agent in all the nodes automatically and even in the case of new node is created from AKS node pool?

**Comment by PRAVEEN-PYDIMARRI** [comment]
Getting the below error when I run the terraform newrelic script. I want to connect to AKS cluster in azure and run the new relic installation from each node when its created. Please provide the solution for the same or help me to understand.

kubernetes_namespace.this: Creating...
╷
│ Error: Post "http://localhost/api/v1/namespaces": dial tcp [::1]:80: connect: connection refused
│ 
│   with kubernetes_namespace.this,
│   on main.tf line 21, in resource "kubernetes_namespace" "this":
│   21: resource "kubernetes_namespace" "this" {
│

**Comment by PRAVEEN-PYDIMARRI** [comment]
This is resolved by myself via DaemonSet and Config maps. Closing this issue.
