### ISSUE TITLE
Cluster autoscaler is not aware that the nodepool have agentpool label when the nodepool size is 0

### ISSUE THREAD

**Issue by kaancfidan** [Azure/AKS#2832]
**What happened**:
Cluster autoscaler does not trigger scale-up for GPU-enabled nodepools when the nodepool size is 0.

**What you expected to happen**:
Cluster autoscaler should trigger scale-up.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a GPU-enabled nodepool (e.g. with name `gpu`) with min count of 0.
- Deploy an `nvidia-device-plugin` DaemonSet that targets the nodepool.
- Try to deploy a Pod that has a `nvidia/gpu: 1` request.
- Observe that cluster autoscaler does not trigger scale-up
- Push the VMSS to scale up manually from Azure portal
- Observe that the future Pods trigger scale up properly
- Change the nodepool config and recreate it
- Observe that the problem repeats until manually pushed to scale of 1 at least once

**Anything else we need to know?**:
I suspect this might be related to the cluster autoscaler's cache about nodepools labels and properties. Since the min count is 0, nvidia-device-plugin DaemonSet never schedules on any nodes and the autoscaler is not aware that this nodepool has `nvidia/gpu`.

See the event log from such a Pod in our production below. 

Between the 16 hours of `NotTriggerScaleUp` and the scheduling events I have scaled the underlying VMSS manually from the Azure portal to 1, this was one of 3 Pods that could not be scheduled. One of the pods got scheduled to the manually triggered node, then the cluster autoscaler stepped in and autoscaled the nodepool to 3.

```
Events:
  Type     Reason                  Age                   From                     Message
  ----     ------                  ----                  ----                     -------
  Warning  FailedScheduling        45m (x63 over 109m)   default-scheduler        0/10 nodes are available: 10 node(s) didn't match Pod's node affinity/selector.
  Warning  FailedScheduling        12m (x6 over 17m)     default-scheduler        0/10 nodes are available: 10 node(s) didn't match Pod's node affinity/selector.
  Warning  FailedScheduling        12m                   default-scheduler        0/11 nodes are available: 1 Insufficient nvidia.com/gpu, 10 node(s) didn't match Pod's node affinity/selector.
  Normal   Scheduled               12m                   default-scheduler        Successfully assigned [REDACTED] to aks-traingpu-40740009-vmss000009
  Normal   NotTriggerScaleUp       12m (x5881 over 16h)  cluster-autoscaler       pod didn't trigger scale-up: 5 node(s) didn't match Pod's node affinity/selector
  Warning  FailedAttachVolume      8m15s (x2 over 10m)   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-[REDACTED]" : Attach timeout for volume /subscriptions/[REDACTED]/resourceGroups/[REDACTED]/providers/Microsoft.Compute/disks/pvc-[REDACTED]
  Warning  FailedMount             7m57s (x2 over 10m)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[workdir], unattached volumes=[podmetadata workdir kube-api-access-db8wf]: timed out waiting for the condition
  Normal   SuccessfulAttachVolume  7m30s                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-[REDACTED]"
  Normal   Pulling                 6m1s                  kubelet                  Pulling image "quay.io/argoproj/argoexec:v3.1.11"
  Normal   Pulled                  5m52s                 kubelet                  Successfully pulled image "quay.io/argoproj/argoexec:v3.1.11" in 8.767754279s
  Normal   Created                 5m46s                 kubelet                  Created container wait
  Normal   Started                 5m46s                 kubelet                  Started container wait
  Normal   Pulling                 5m46s                 kubelet                  Pulling image "[REDACTED]/trainer:0.12.0"
  Normal   Pulled                  38s                   kubelet                  Successfully pulled image "[REDACTED]/trainer:0.12.0" in 5m8.245605391s
  Normal   Created                 13s                   kubelet                  Created container main
  Normal   Started                 13s                   kubelet                  Started container main
```

**Comment by marwanad** [comment]
@kaancfidan Do your pods have a label selector on `accelerator` label by any chance?

**Comment by kaancfidan** [comment]
We have multiple nodepools with different GPUs (training and inference purposes). I need to specify the nodepool directly so using `kubernetes.azure.com/accelerator=nvidia` might not work for us.

We have only experienced this with GPU nodepools though, we have similar CPU-only jobs that run on nodepools with min scale = 0. Is it just a coincidence that it happened to GPUs? I suspect agentpool label would affect all of them.

**Comment by marwanad** [comment]
@kaancfidan are those new clusters? The `poolName` tag replacement, I believe only affects newly created clusters or ones that ran an upgrade recently. 

Can you test the mitigation by adding the VMSS tag mentioned above? If that fixes it, then it's indeed the case. I don't think it's related to GPUs (at least for now).

**Comment by kaancfidan** [comment]
> @kaancfidan are those new clusters? The `poolName` tag replacement, I believe only affects newly created clusters or ones that ran an upgrade recently.

These are not new clusters (2 and 3 years old), but we did upgrade Kubernetes versions recently.

> Can you test the mitigation by adding the VMSS tag mentioned above? If that fixes it, then it's indeed the case. I don't think it's related to GPUs (at least for now).

I will try it.

**Comment by kaancfidan** [comment]
We have experienced the same issue with a CPU nodepool today. So your agentpool guess seems to fit better. We will be trying the proposed workaround shortly.

**Comment by marwanad** [comment]
@kaancfidan the fix will be under-way and will be called out in the next release notes.
