### ISSUE TITLE
Support CSI blob driver as a built in storageClass in AKS 

### ISSUE THREAD

**Issue by ivanthelad** [Azure/AKS#2836]
Is there plans to support CSI blob driver as a built in storage class in AKS ?
https://github.com/kubernetes-sigs/blob-csi-driver 

From what I see this is not on the roadmap

**Comment by andyzhangx** [comment]
it's in our roadmap, still in the design stage.

**Comment by olsenme** [comment]
Hey @ivanthelad could I please understand your use case a little more?

**Comment by olsenme** [comment]
Are you currently experiencing any challenges using the instructions here: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/install-driver-on-aks.md?

**Comment by ivanthelad** [comment]
no issue with instructions. the ask is more about having the installed components be supported by AKS. the driver requires escalated privileges  on the cluster and customers would appreciate having this as a  supported bundled component. 
Today they have to take care of keeping the software up to date https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/install-blob-csi-driver.md

**Comment by saurabh0501** [comment]
Hi @ivanthelad, we are planning to release the blob csi driver for public preview next month. With this preview, you will be able to use the Azure Blob CSI driver as a managed addon in AKS with built in storage classes for NFS and Blobfuse.

**Comment by andyzhangx** [comment]
managed blob csi driver is already preview, follow guide here: https://docs.microsoft.com/en-us/azure/aks/azure-blob-csi
