### ISSUE TITLE
Unable to attach or mount volumes - timed out waiting for the condition

### ISSUE THREAD

**Issue by rdauncey53** [Azure/AKS#2840]
**What happened**:
When trying to deploy their AKS clusters, several of our teams have reported failures to mount persistent volumes, with the following symptomatic events in the descriptions of the pods that failed to deploy:

```
Warning  FailedMount  4m51s (x25 over 95m)  kubelet MountVolume.MountDevice failed for volume "<persistent volume id>" : rpc error: code = DeadlineExceeded desc = context deadline exceeded  
 
Warning  FailedMount  20s (x38 over 77m)    kubelet  (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[<list of unmounted volumes>], unattached volumes=[<list of unattached volumes>]: timed out waiting for the condition 
```

(The values in <> brackets have been removed for simplicity & security)
This is usually fixed by restarting the cluster, but this is not a very satisfactory solution.

**What you expected to happen**:
All volumes mount as expected, and pods spin up correctly.

**How to reproduce it (as minimally and precisely as possible)**:
We cannot work out how to reproduce this bug, as it just seems to happen randomly on our clusters, and we cannot see any differences between clusters that are running fine and clusters that are broken.

**Environment**:
This has happened in a number of cases, but in the most recent case we had:
- Kubernetes version (use `kubectl version`): 1.21.9
- Size of cluster (how many worker nodes are in the cluster?): 5

**Comment by andyzhangx** [comment]
what's the volume type? are there lots of files inside that volume? it's better provide kubelet logs on that agent node for troubleshooting.

**Comment by rdauncey53** [comment]
It is a persistent volume using the default StorageClass, which uses Azure StandardSSD storage (unclear if that answers your question on volume type), with a size of 50Gi. 

The volume acts as the local storage for a Prometheus pod, so files are added as Prometheus scrapes data. When the volume is initially created, which is the point at which it is failing, there are no files in there. 

Apologies I can't give more logs for this, we don't have a running cluster with this issue on it, and we haven't been able to reproduce it - as I said above, it just seems to happen randomly, and restarting the cluster seems to fix it.

**Comment by rdauncey53** [comment]
Okay, I've managed to get some kubelet logs. Not sure how much this will help, because these don't seem to give much more info than the ones above but:
```
E0315 11:37:47.258921    3443 kubelet.go:1720] "Unable to attach or mount volumes for pod; skipping pod" err="unmounted volumes=[<prometheus database>], unattached volumes=[<list of volumes>]: timed out waiting for the condition" pod="<prometheus pod>"
E0315 11:37:47.258978    3443 pod_workers.go:918] "Error syncing pod, skipping" err="unmounted volumes=[<prometheus database>], unattached volumes=[<list of volumes>]: timed out waiting for the condition" pod="<prometheus pod>" podUID=<UID>
E0315 11:37:47.261103    3443 kubelet.go:1720] "Unable to attach or mount volumes for pod; skipping pod" err="unmounted volumes=[<prometheus database>], unattached volumes=[<list of volumes>]: timed out waiting for the condition" pod="<prometheus pod>"
E0315 11:37:47.261142    3443 pod_workers.go:918] "Error syncing pod, skipping" err="unmounted volumes=[<prometheus database>], unattached volumes=[<list of volumes>]: timed out waiting for the condition" pod="<prometheus pod>" podUID=<UID>
E0315 11:37:47.917787    3443 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"<pod id>\" found, but error not a directory occurred when trying to remove the volumes dir" numErrs=7
```

**Comment by rdauncey53** [comment]
Have been in touch with Azure support, who have said this issue will be fixed in the Azure Disk CSI driver v1.15 release.

**Comment by Ropes** [comment]
Thank you for posting the resolution in v1.15 @rdauncey53 !

You've saved the internet from another search of despair.
![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

**Comment by rdauncey53** [comment]
@Ropes If it is any help, we also found a weird workaround in the mean time, which was temporarily scaling the cluster out (using kubectl access and azcli):
* Run `kubectl get nodes -o wide` to get the number of nodes
* Run `az aks scale -g <resource_group> --name <cluster_name> --node-count <current node count + 1> --nodepool-name <nodepool name>`
* Check if the failing pods have now come up
* Run `az aks scale -g <resource_group> --name <cluster_name> --node-count <original node count> --nodepool-name <nodepool name>` to scale back
 
The root issue is a time out condition, so any command that restarts that timer (which is presumably what happens with the scaling out) often seems to fix the issue.
