### ISSUE TITLE
Upgrade cloud-provider-azure (cloud-node-manager) to 1.23.5 or later

### ISSUE THREAD

**Issue by vsabella** [Azure/AKS#2844]
cloud-provider-azure recently added support for AppProtocol based health-checks and extended service annotations for controlling the health checks of LoadBalancer resources. 

We are looking to increase reliability of our ingress controller by migrating the health check to HTTP instead of TCP to mitigate another issue where [non-ready nodes are added to the load balancer](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1195)

[https://github.com/kubernetes-sigs/cloud-provider-azure/releases/tag/v1.23.4](https://github.com/kubernetes-sigs/cloud-provider-azure/releases/tag/v1.23.4)

Is there a plan to upgrade to the latest cloud-provider-azure?

**Comment by zhiweiv** [comment]
In my AKS, the cloud-node-manager is already 1.23.5

**Comment by feiskyer** [comment]
close since it is already upgraded
