### ISSUE TITLE
Commas are no longer allowed in resource tags of K8S clusters and child resources after upgrading to 1.20.9

### ISSUE THREAD

**Issue by yichungyu** [Azure/AKS#2845]
**What happened**:
After upgrading their K8S from 1.19.11 to 1.20.9, my customer began encountering issues with their child load balancer resources within their cluster. After creating a support request with Azure and working with the support engineer, they discovered that the issue is caused by the load balancer using commas in its tags, which became a forbidden character after the K8S upgrade.

**What you expected to happen**:
My customer did not expect commas to become forbidden post K8S upgrade. It is difficult for them to remove commas from their resource tags because they rely on a specific tag format to work with their business logic

**How to reproduce it (as minimally and precisely as possible)**:
- On a resource within a K8S cluster, reate a new tag or update an existing tag with commas in its content

**Anything else we need to know?**:
The customers wish to submit a feature request to avoid the negative effects of the recently-introduced resource tag enforcement 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.9
- Size of cluster (how many worker nodes are in the cluster?): N/A
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by palma21** [comment]
Can you explain what you mean by blocking commas? Do you have an error message example or scenario to repro this?
