### ISSUE TITLE
AKS Cluster schedules a pod in a node with unavailable HD slots 

### ISSUE THREAD

**Issue by Superzer0** [Azure/AKS#2847]
**What happened**:

AKS Cluster schedules a pod in a node with unavailable HD slots although there are other nodes with where available slots and due to that pod hangs on 'ContainerCreating' with the following error in 'describe':
 
Error:
 
```
Events:
  Type     Reason              Age                  From                     Message
  ----     ------              ----                 ----                     -------
  Normal   Scheduled           2m46s                default-scheduler        Successfully assigned ***redacted**** to ***redacted**** 
  Warning  FailedMount         43s                  kubelet                  Unable to attach or mount volumes: unmounted volumes=[natsfile[], unattached volumes=[kube-api-access-lj4rk natsfile[]: timed out waiting for the condition
  Warning  FailedAttachVolume  33s (x9 over 2m46s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-***redacted****" : rpc error: code = Unknown desc = Attach volume "/subscriptions/***redacted****" to instance "aks-agentpool-***redacted****" failed with Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: {
  "error": {
    "code": "OperationNotAllowed",
    "message": "The maximum number of data disks allowed to be attached to a VM of this size is 4.",
    "target": "dataDisks"
  }
}

```
We are using disk.csi.azure.com dynamic provisioner with SKU:StandardSSD_LRS and reclaimPolicy:Delete, volumeBindingMode: WaitForFirstConsumer
We currently have 12 nodes x 4 HD slots in each = 48 slots available. 32 PVCs are being used and still have 16 slots left when the mentioned error occurred. However, AKS still chooses a node that is not able to handle the pod.
 
**What you expected to happen**:
AKS scheduler to schedule the pod with PVC to a node that has disk slots capacity.

We have opened a ticket to Microsoft, but we got information that this behaviour is expected in AKS.
We would like to have more traction on this issue to see if this is really AKS normal behaviour and we need our configuration tuned or a bug in the AKS scheduler.
(TrackingID#2203070050001547)

**How to reproduce it (as minimally and precisely as possible)**:
It happens nondeterministically, but having a cluster with 30% available would yield the aforementioned error each time dynamically provisioned persistent volume is requested by PVC. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.4
- Size of the cluster (how many worker nodes are in the cluster?) 12 - Standard_A2m_v2, northeurope 
- General description of workloads in the cluster: Http microservices

**Comment by Superzer0** [comment]
FYI @mkarbowy @kaluzaaa

**Comment by Superzer0** [comment]
Hi, any updates?

**Comment by andyzhangx** [comment]
could you check if you change to`volumeBindingMode: Immediate` setting, will the same issue happen? Thanks.

**Comment by Superzer0** [comment]
Hi @andyzhangx, we have tried the setting you mentioned but that did not help.

**Comment by andyzhangx** [comment]
@Superzer0 I tried with this [example](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/statefulset.yaml) scheduling10 replicas on two `Standard_A2m_v2` nodes, while I could not repro, is there any other way to repro this issue?

**Comment by Superzer0** [comment]
@andyzhangx we are in parallel investigating it with MS support and seems like it is caused by https://github.com/kubernetes-sigs/cloud-provider-azure/issues/1155. Reimage of the nodes was proposed. Will follow up with a solution/workaround here. 
Thanks!

**Comment by Superzer0** [comment]
For anyone that encounters this problem. 
The rootcause was "ghost disks" that were not visible for the K8S scheduler (no PVC or PV)  but were attached to the VMs. The resolution was to drain each node and detach manually any disks that were left. 
After draining a node, the following query should not return any attached disks. 
```
az vmss show -g ... -n "..." --instance-id <ID> --query "storageProfile.dataDisks[].{name: name, lun: lun}"
``` 
MS support states that the "ghost disks" were created due to an in-tree disk driver issue.
