### ISSUE TITLE
Cannot impersonate AAD user

### ISSUE THREAD

**Issue by MarcoSong2016** [Azure/AKS#2848]
**What happened**:
kubectl auth can not impersonate user

**What you expected to happen**:
Should return yes/no, instead of error message

**How to reproduce it (as minimally and precisely as possible)**:
Enabled AKS managed AAD in cluster, and I have admin permission

When I run
```
kubectl auth can-i get pods -n dev 
```
it returns **yes**, which means I have permission

But when I try to impersonate myself or a teammate

```
kubectl auth can-i get pods -n dev --as myname@mydomain.com
```
It returns

    no - Azure does not have opinion for this non AAD user. 
    If you are an AAD user, please set Extra:oid parameter for impersonated user in the kubeconfig

**Anything else we need to know?**:

**Environment**:  
- Kubernetes version (use `kubectl version`): 1.21.2
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by miwithro** [comment]
@MarcoSong2016 why the issue with the error message along with the "No" this provides users with information on why, which is important.

**Comment by MarcoSong2016** [comment]
@miwithro the point is that I impersonated the user with an AAD user, the error message told me it's not
