### ISSUE TITLE
az aks create --nodepool-labels improperly documented

### ISSUE THREAD

**Issue by jesse-pingthings** [Azure/AKS#2851]
**What happened**:
I navigated to https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create to learn how I could set node labels when creating a new cluster. I discovered the following documentation:
> --nodepool-labels
> Space-separated labels: key[=value] [key[=value] ...]. See https://aka.ms/node-labels for syntax of labels.

I then ran
```
az aks create ... \
--nodepool-labels "pingthings.io/role-compute=true pingthings.io/role-core=true pingthings.io/role-db=true pingthings.io/role-storage=true"
```
This gave me an error for not taking the `k=v` form.

I then tried
```
az aks create ... \
    --nodepool-labels "pingthings.io/role-compute=true" \
    --nodepool-labels  "pingthings.io/role-core=true" \
    --nodepool-labels  "pingthings.io/role-db=true" \
    --nodepool-labels "pingthings.io/role-storage=true"
```
This only set the last label on the list on my nodes.

To get the behavior I expect I found I needed to separate my `k=v` pairs in the `argv` to `az aks create` like so:
```
az aks create ... \
    --nodepool-labels \
      "pingthings.io/role-compute=true" \
      "pingthings.io/role-core=true" \
      "pingthings.io/role-db=true" \
      "pingthings.io/role-storage=true"
```

**Comment by jesse-pingthings** [comment]
Hi @erik-ha-msft,

Yes, that's the behavior I'm experiencing too. When the quotes are dropped, then the node labels aren't space separated, but `argv` separated, which contradicts the documentation.

**Comment by allyford** [comment]
Hi @jesse-pingthings ,
Thanks for your feedback! @erik-ha-msft's AKS Create example above matches the az aks create [documentation](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#:~:text=Global%20Parameters-,az%20aks%20create,-Edit) where quotations are not used. Was there a section in the documentation that recommended adding quotes? If so, please provide the link so that we can resolve that contradiction.

**Comment by jesse-pingthings** [comment]
I had written a function based on the documentation that would turn a token list into a space separated string, but then promptly scrapped it because I experience `az aks create ... --nodepool-labels` taking a token list.

(recalling from memory, this snippet is untested) That function looked something like:
```
space_separate() {
  local r
  r=
  for kv; do
    case "$kv" in
      *' '*) echo "invalid space character in node pool label" >&2 ; return 1 ;;
    esac
    r="${r}${r:+}${kv}"
  done
  printf "%s\n" "$r"
}
```

The broken code is:
`az aks create ... --nodepool-labels "$(space_separate "$@")"`

When I write my script with the observed behavior, it looks like:
`az aks create ... --nodepool-labels "$@"`

I'm generally paranoid about spaces expanding into tokens, so I tend to over-quote my shell scripts.

**Comment by jesse-pingthings** [comment]
> Was there a section in the documentation that recommended adding quotes? If so, please provide the link so that we can resolve that contradiction.

Here are the field splitting rules I'm referring to:
https://pubs.opengroup.org/onlinepubs/7908799/xcu/chap2.html#tag_001_006_005
> After parameter expansion, command substitution, and arithmetic expansion the shell will scan the results of expansions and substitutions that did not occur in double-quotes for field splitting and multiple fields can result.

> The shell will treat each character of the `IFS` as a delimiter and use the delimiters to split the results of parameter expansion and command substitution into fields.

**Comment by jesse-pingthings** [comment]
How do I clear the `resolution/answer-provided` label on this ticket? I'm worried people might see this label and assume the issue has been resolved, or that the answer provided was satisfactory.

**Comment by allyford** [comment]
Hi @jesse-pingthings 
Though you have identified that the quotation usage causes an error, there is no guidance in the AKS documentation that instructs users to utilize the quotations. When following the documentation as written (as Erik demonstrated), there is no error produced. I have provided your feedback to our documentation team, so they are aware of the error that occurred. If you do identify a contradiction within the AKS documentation, please point us to the error and we will resolve it.
