### ISSUE TITLE
AKS Node Kernel Version - 5.4.0-1070-azure - Pods not able to connect to other pods running with kernel - 5.4.0-1067-azure

### ISSUE THREAD

**Issue by zohebs341** [Azure/AKS#2853]
Hi,

We are using Azure AKS 1.21.7 version.

Pod running on node with Kernel version 5.4.0-1070-azure is not able to connect the pods which are in different AKS Node(Kernel Version 5.4.0-1067-azure.

Pod running under same 5.4.0-1067-azure kernel version are working.

**Comment by alexeldeib** [comment]
I'd suggest a support case, this issue requires far more detail to debug. we're also several kernel versions ahead of both of those now.
