### ISSUE TITLE
AKS upgrade triggers serious persistent volume mounting bug

### ISSUE THREAD

**Issue by aolmosj** [Azure/AKS#2855]
**What happened**:

After upgrading AKS 1.20.15 to 1.21.9, with no previous configuration changes, I noticed some hours later that a pod was actually mounting an Azure disk from another pod, and viceversa.

I mean, pod A had a pvc A which links to PV A, and this PV links to an Azure DIsk A (10 GB size). On the other hand, pod B had a pvc B which links to PV B, and this PV links to an Azure DIsk B (60 GB size). Although I validated that this was the actual situation and double checked that there was no Statefulset/PVC/PV misconfiguration, Pod A was actually mounting Azure Disk B (60 GB) and Pod B was mounting Azure disk A (10 GB).

I checked with Grafana ( persistent volume size dashboard) when this issue started, and it was at the same time of upgrading the node pool.

The final solution was just to stop and start both statefulsets. I have to insist... I did not change anything in the whole cluster, I just upgraded and then when I noticed the issue I restarted both statefulsets to try to solve the problem.

**What you expected to happen**:

Well, I just expected that after the cluster upgrade every pvc should use their related Azure disk.

**How to reproduce it**:

The only relevant matter was that this happened after/while upgrading the node pool. First of all I upgraded the control plane with
```
az aks upgrade \
    --resource-group  *** \
    --name ***\
    --control-plane-only \
    --kubernetes-version 1.21.9
```

And then I run this for every node pool:

```
az aks nodepool upgrade \
    --resource-group *** \
    --cluster-name *** \
    --name *** \
    --kubernetes-version 1.21.9 \
    --no-wait
```

**Environment**:
- Kubernetes version: 1.21.9
- Size of cluster: node pool (3 nodes) + node pool (0 nodes) + spot node pool (1 node)

**Comment by andyzhangx** [comment]
pls file an azure support ticket, and also provide disk driver logs on the agent node(pointing out which volume has the wrong links): https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed
