### ISSUE TITLE
proxy does not work

### ISSUE THREAD

**Issue by r-moiseev** [Azure/AKS#286]
Created cluster in EastUs. kubectl works fine, then i installed helm and helm is ton working properly
```
 helm ls                          
Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp 10.240.0.5:10250: getsockopt: connection timed out
```
but tiller seems to be deployed and running

I think there is same issue with dashboard 
```
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
error: error upgrading connection: error dialing backend: dial tcp 10.240.0.5:10250: getsockopt: connection timed out
```

**Comment by Zimmergren** [comment]
Possibly related to #224.

In issue #232 there's also some [comments](https://github.com/Azure/AKS/issues/232#issuecomment-374631011) about helm and AKS causing the timeout issue you describe.

**Comment by shahiddev** [comment]
Temporary workaround: in the url that is opened in the browser about 1/2 way across in the url it says **https** - if you change that to **http** it should work.
![image](https://user-images.githubusercontent.com/11890711/38555679-f0d3e7aa-3cbe-11e8-9530-90d00b524f07.png)

**Comment by jalberto** [comment]
Thanks @shahiddev, that workaround works.

Still a bug, as I expect `kubcetl` command works well with AKS

**Comment by r-moiseev** [comment]
Thanks but therr is also bug with helm

**Comment by mboersma** [comment]
@r-moiseev if `helm` is still misbehaving for you, could you send details with subscription ID, resource group name, cluster name, and Azure region to aks-help@service.microsoft.com so we can investigate? Thanks!

**Comment by lalo** [comment]
@r-moiseev and for anybody else hitting: this seems to be a bug with helm and a way to get around it is to kill the tiller pod.

So its:

- kubectl get pods --all-namespaces
- identify tiller-deploy pod and copy the name
- kubectl delete pods _tiller-deploy-name_
- another tiller pod should spawn and it should work now

**Comment by MaurGi** [comment]
you can use:

`az aks browse --resource-group $rg --name $name --listen-port 8001`
