### ISSUE TITLE
Timeline for ACI virtual node volume mounting Azure Files share support for General-purpose V2

### ISSUE THREAD

**Issue by samssann** [Azure/AKS#2864]
The AKS virtual node configuration [documentation](https://docs.microsoft.com/en-us/azure/aks/virtual-nodes) states that: _"Volume mounting Azure Files share support General-purpose V1"_. General-purpose V1 is [considered a legacy storage account](https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview#legacy-storage-account-types). When can we expect to use Standard general-purpose v2 storage account with virtual nodes?

**Comment by andyzhangx** [comment]
CSI driver does not run on ACI node, it's an ACI feature, could you take a look @circy9

**Comment by VybavaRamadoss** [comment]
Tagging @peterpogorski @sarabdua to investigate why this is blocked in Virtual Nodes

**Comment by VybavaRamadoss** [comment]
@peterpogorski can you provide an update?

**Comment by peterpogorski** [comment]
Azure File Volume V2 is supported via Virtual Nodes and via ACI. We will update the documentation to make it clear that it is supported.

**Comment by AlphaNoodleS** [comment]
After discussing with Matt and Peter, updates made in the document to reflect V2 support and PR is open.

**Comment by samssann** [comment]
So you can now use V2 Storage Accounts with virtual nodes?

**Comment by MGoedtel** [comment]
@samssann - Yes, you can use V2 storage accounts with virtual nodes. The article has been updated to reflect this change and it goes live on 10/12 or 10/13 the latest. Thanks.
