### ISSUE TITLE
Cannot create nodepool with node-restriction.kubernetes.io/ prefix label

### ISSUE THREAD

**Issue by kthompson23** [Azure/AKS#2866]
I am trying to create a nodepool with a label prefix of `node-restriction.kubernetes.io/`. The Kubernetes [Assigning Pods to Nodes](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-isolation-restriction) documentation recommends this prefix when assigning pods to nodes.

**What happened**:

Attempting to create a nodepool with a label `node-restriction.kubernetes.io/mvis=true"` results in a bad request error.

> Error: creating/updating Managed Kubernetes Cluster Node Pool "mvis" (Resource Group "Aks-Prod5-RG"): containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="For Kubernetes version greater than or equal to 1.16, node label keys in the 'kubernetes.io' or 'k8s.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io). For more information, please check https://aka.ms/aks-node-labels-116." Target="node-restriction.kubernetes.io/mvis=true"

**What you expected to happen**:

I expect the nodepool to contain nodes with a label prefixed with `node-restriction.kubernetes.io/`.

**How to reproduce it (as minimally and precisely as possible)**:

```
az aks nodepool add --cluster-name storis-aks-dev6 --name labeltest --resource-group Aks-Dev6-RG --node-count 2 --labels node-restriction.kubernetes.io/mvis=true

The behavior of this command has been altered by the following extension: aks-preview
Operation failed with status: 'Bad Request'. Details: For Kubernetes version greater than or equal to 1.16, node label keys in the 'kubernetes.io' or 'k8s.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io). For more information, please check https://aka.ms/aks-node-labels-116.
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 1.20.15
- AZ version:
`
{
  "azure-cli": "2.34.1",
  "azure-cli-core": "2.34.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.4.60"
  }
}`

**Comment by allyford** [comment]
Hi @kthompson23, 
Thank you for your feedback! Unfortunately, as you have identified in the AKS documentation, as of Kubernetes 1.16 only a defined subset of labels with the kubernetes.io prefix can be applied by the kubelet to nodes. We recognize and have noted that this contradicts the recommendation in the Kubernetes documentation.

The Kubernetes [Assigning Pods to Nodes](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-isolation-restriction) documentation also lists a few other methods to assign pods to nodes (nodeSelector, Affinity & anti-affinity). Do these other methods accomplish your goal?

If not, please provide additional information on you use case for the node isolation/restriction label.

**Comment by kthompson23** [comment]
@allyford I was able to accomplish what I needed using different labels. Is this something that will be changed in a future version of AKS?
