### ISSUE TITLE
Helm upgrade command failed due to long execution time

### ISSUE THREAD

**Issue by kelvin-ko** [Azure/AKS#2869]
**What happened**:
We ran the following helm upgrade with Newrelic daemonset on multiple AKS clusters, for some fo the clusters, it took more than 5 hours to complete, while for some clusters it took only less than 1 hour. The clusters that we have are all running 1.21.9 and have identical configurations and similar no. of nodes.

echo "helm install newrelic..."
helm upgrade --install --atomic --wait --timeout $TIMEOUT newrelic-bundle newrelic/nri-bundle \
--set global.licenseKey=$NEWRELIC_KEY \
--set global.cluster=$CLUSTER_NAME \
--namespace=ns-newrelic-monitor \
--set newrelic-infrastructure.privileged=false \
--set ksm.enabled=true \
--set kubeEvents.enabled=true \
--set prometheus.enabled=true \
--version=$NEWRELIC_BUNDLE_VERSION

These are the events logs we identified during the issue.

Warning  FailedScheduling   8m1s                    default-scheduler   0/26 nodes are available: 1 Insufficient cpu, 25 node(s) didn't match Pod's node affinity/selector.

Warning  FailedScheduling   7m59s                   default-scheduler   0/26 nodes are available: 1 Insufficient cpu, 25 node(s) didn't match Pod's node affinity/selector.

Normal   NotTriggerScaleUp  2m52s (x31 over 7m53s)  cluster-autoscaler  pod didn't trigger scale-up: 1 node(s) didn't match Pod's node affinity/selector.

**What you expected to happen**:
The helm upgrade to be finished within an hour

**How to reproduce it (as minimally and precisely as possible)**:
Execute the same helm upgrade command can sometimes reproduce

**Anything else we need to know?**:
This helm chart is to upgrade a Newelic daemonset running the AKS cluster.

**Environment**:
- Kubernetes version (use `kubectl version`):
- 1.21.9
- 
- Size of cluster (how many worker nodes are in the cluster?)
- 30-40 nodes
- 
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Java app, microservices.

- Others:
The concern is if we want to have the Helm chart execution time to be more consistent

**Comment by shashankbarsin** [comment]
@kelvin-ko apologies for the late response on this issue. Can you let us know if you are still facing this issue on a cluster [in the supported versions](https://learn.microsoft.com/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar), currently 1.23 being the minimum version
