### ISSUE TITLE
Mount volume failed due to wrong namespace when looking for secret key

### ISSUE THREAD

**Issue by trungp** [Azure/AKS#2871]
**What happened**:

I can not start container due to mounting AzureFile issue, I have created all resources in namespaces named "uat", but the error message show that it's looking for the secret key at "default" namespace. 

reason: FailedMount
message: >-
  MountVolume.MountDevice failed for volume
  "azure-file-share" : fetching NodeStageSecretRef
  default/azure-storage-file-share-secret-key failed: kubernetes.io/csi: failed
  to find the secret azure-storage-file-share-secret-key in the namespace
  default with error: secrets "azure-storage-file-share-secret-key" not found

**What you expected to happen**: the container in "uat" namespace should looking for secret in "uat" namespace.

**How to reproduce it (as minimally and precisely as possible)**:
It happens at version 1.22.6, but not happen at version 1.21.9 and 1.20.x

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.22.6
- Size of cluster (how many worker nodes are in the cluster?): testing with 2 nodes, linux, Standard_B2s, API Availability enabled 99.95%
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Java Springboot application, base on the image openjdk:8-jdk-alpine.

**Comment by andyzhangx** [comment]
could you add `secretNamespace: uat` in azure file PV, this is related to https://github.com/kubernetes/kubernetes/pull/108000, we are still rolling out the fix.
BTW, from 1.22, it's recommended to use CSI driver PV, follow guide here: https://docs.microsoft.com/en-us/azure/aks/azure-files-volume#mount-file-share-as-a-persistent-volume

**Comment by trungp** [comment]
> could you add `secretNamespace: uat` in azure file PV, this is related to [kubernetes/kubernetes#108000](https://github.com/kubernetes/kubernetes/pull/108000), we are still rolling out the fix. BTW, from 1.22, it's recommended to use CSI driver PV which does not have such issue, follow guide here: https://docs.microsoft.com/en-us/azure/aks/azure-files-volume#mount-file-share-as-a-persistent-volume

It's resolved with this workaround. Thanks @andyzhangx . Anyway, I will check your guideline and switch to CSI driver.
