### ISSUE TITLE
Failure mounting Azure default storage class backed PVC - "could not format"

### ISSUE THREAD

**Issue by amsoedal** [Azure/AKS#2872]
**What happened**:

When mounting an Azure disk, we get the following failure: 
```
involvedObject:
  kind: Pod
  namespace: default
  name: insights-postgresql-0
  uid: 1751b81b-f22b-4de3-9455-0bb21cc95d4a
  apiVersion: v1
  resourceVersion: '4912'
reason: FailedMount
message: >-
  MountVolume.MountDevice failed for volume
  "pvc-70f0e65e-2de2-417d-ab85-9f29770f232d" : rpc error: code = Internal desc =
  could not format "/dev/disk/azure/scsi1/lun0"(lun: "0"), and mount it at
  "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-70f0e65e-2de2-417d-ab85-9f29770f232d/globalmount"
source:
  component: kubelet
  host: aks-user-25366036-vmss000002
firstTimestamp: '2022-03-25T01:27:11Z'
lastTimestamp: '2022-03-25T08:47:12Z'
count: 222
type: Warning
```

**What you expected to happen**:

We expect the disk to mount successfully. 

**How to reproduce it (as minimally and precisely as possible)**:
This happens at deployment time. 

**Anything else we need to know?**:
Node size: standard_d4ds_v4
Node image version: AKSUbuntu-1804gen2containerd-2022.03.21
Container runtime version: containerd://1.4.12+azure-3

Logs from the kube-system/csi-azuredisks-node pod show: 
```
I0328 12:25:48.841452       1 utils.go:77] GRPC call: /csi.v1.Node/NodeStageVolume
I0328 12:25:48.841478       1 utils.go:78] GRPC request: {"publish_context":{"LUN":"1"},"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-xxx/globalmount","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":1}},"volume_context":{"csi.storage.k8s.io/pv/name":"pvc-xxx","csi.storage.k8s.io/pvc/name":"insights-kxi-sp-checkpoint-pvc","csi.storage.k8s.io/pvc/namespace":"default","requestedsizegib":"20","skuname":"StandardSSD_LRS","storage.kubernetes.io/csiProvisionerIdentity":"1648171035528-8081-disk.csi.azure.com"},"volume_id":"/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Compute/disks/pvc-xxx"}
I0328 12:25:48.847746       1 azure_common_linux.go:177] azureDisk - found /dev/disk/azure/scsi1/lun1 by sdd under /dev/disk/azure/scsi1/
I0328 12:25:48.847772       1 nodeserver.go:118] NodeStageVolume: perf optimization is disabled for /dev/disk/azure/scsi1/lun1. perfProfile none accountType StandardSSD_LRS
I0328 12:25:48.848314       1 nodeserver.go:159] NodeStageVolume: formatting /dev/disk/azure/scsi1/lun1 and mounting at /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-xxx/globalmount with mount options([])
I0328 12:25:48.848330       1 mount_linux.go:487] Attempting to determine if disk "/dev/disk/azure/scsi1/lun1" is formatted using blkid with args: ([-p -s TYPE -s PTTYPE -o export /dev/disk/azure/scsi1/lun1])
I0328 12:25:48.849314       1 mount_linux.go:490] Output: "DEVNAME=/dev/disk/azure/scsi1/lun1\nTYPE=LVM2_member\n"
W0328 12:25:48.849332       1 mount_linux.go:464] Configured to mount disk /dev/disk/azure/scsi1/lun1 as LVM2_member but current format is ext4, things might break
I0328 12:25:48.849335       1 mount_linux.go:376] Checking for issues with fsck on disk: /dev/disk/azure/scsi1/lun1
I0328 12:25:48.850601       1 mount_linux.go:477] Attempting to mount disk /dev/disk/azure/scsi1/lun1 in ext4 format at /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-xxx/globalmount
I0328 12:25:48.850628       1 mount_linux.go:183] Mounting cmd (mount) with arguments (-t ext4 -o defaults /dev/disk/azure/scsi1/lun1 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-xxx/globalmount)
E0328 12:25:48.852385       1 mount_linux.go:195] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/disk/azure/scsi1/lun1 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-xxx/globalmount
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-xxx/globalmount: /dev/sdd already mounted or mount point busy.

E0328 12:25:48.852718       1 utils.go:82] GRPC error: rpc error: code = Internal desc = could not format "/dev/disk/azure/scsi1/lun1"(lun: "1"), and mount it at "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-xxx/globalmount"
```
**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.9
- Size of cluster (how many worker nodes are in the cluster?): 3 system and 3 user nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): HTTP microservices
- Others:

**Comment by olsenme** [comment]
@andyzhangx

**Comment by andyzhangx** [comment]
@amsoedal so you are setting `fsType: LVM2_member` which is not supported: `Configured to mount disk /dev/disk/azure/scsi1/lun1 as LVM2_member but current format is ext4, things might break`

**Comment by amsoedal** [comment]
@andyzhangx no, we haven't set up anything -- just relying on the AKS defaults. Would it be worth trying to update the node images?

**Comment by andyzhangx** [comment]
does this example work in your node pool? https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/statefulset.yaml

**Comment by amsoedal** [comment]
Hey Andy, it worked. A couple notes -- this statefulset seems to be relying on the "managed-csi" storage class and not the "default" storage class that our resources are falling back on. Also my colleague let me know apparently this "could not format" issue only causes intermittent failures (i.e. 2-3 out of 80 pods will randomly fail, but then succeed on restart).

**Comment by zvenczel-kx** [comment]
Hi Andy,
Thanks you very much for the quick turnaround!

It seems to me that if a certain amount of storage is requested failures increase dramatically. I was trying to deploy the suggested statefulset like this:

- one at a time - all is fine
- 10 at a time - all is fine
- 20 at a time - all is fine
- 40 at a time - ~half had failed (with the very same, above mentioned failure)

![failed-pods-image](https://user-images.githubusercontent.com/90027208/160878847-9a679915-3de2-4aa3-a458-eb0ab098b2db.png)

I was deploying the following to reproduce: 
[statefulset.yaml.txt](https://github.com/Azure/AKS/files/8382096/statefulset.yaml.txt)

**Comment by andyzhangx** [comment]
@zvenczel-kx the failure you hit is the same as `could not format` error? pls follow this guide to provide azure disk logs on the node: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

**Comment by amsoedal** [comment]
@andyzhangx, the original logs on this issue were actually provided by @zvenczel-kx originally (he is my colleague), so he is indeed running into the same 'could not format' error when he has a large # of pods. Do you want him to grab the logs again?

**Comment by andyzhangx** [comment]
well, it's better if you could provide full logs of the driver, that may help

**Comment by andyzhangx** [comment]
@zvenczel-kx thanks for the confirm. Do you have example how ceph could leverage azure disk provisioner? I am interested in that part, thanks.

**Comment by rzal** [comment]
Unsub

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
