### ISSUE TITLE
Standard_NC12_Promo not supported anymore?

### ISSUE THREAD

**Issue by Anselmatus** [Azure/AKS#2876]
**What happened**:
I wanted to create a new node pool with VM SKU "Standard_NC12_Promo" in West Europe.
I have sufficient quota for this SKU.
The deployment failed with the following error message:
`Message: The VM SKU 'Standard_NC12_Promo' chosen for agentpool(s) 'tomofast' used for create operation is not supported by AKS.`

**What you expected to happen**:
I would expect the deployment to be successful as the previous one were couple of days ago.

**How to reproduce it (as minimally and precisely as possible)**:
`az aks nodepool add --resource-group yourResourceGroup --cluster-name yourCluster --name nodepoolName--node-count 1 --node-vm-size Standard_NC12_Promo --max-pods 25`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): ubuntu20.04 shipped one
- Size of cluster (how many worker nodes are in the cluster?): 5 nodepools containing 2 or 3 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): machine learning
- Others:

**Comment by marwanad** [comment]
https://docs.microsoft.com/en-us/azure/virtual-machines/n-series-migration

**Comment by Anselmatus** [comment]
Yes, I heard about it. The first end-of-life schedule was 31st August 2022.
However, since the EOL is postponed to 31st August **2023**, I'm not sure to understand why AKS is already deprecating this SKU.

Plus, I found the move pretty unpleasant especially without any noticed from the Microsoft team (I've checked the recent release notes and didn't found any mention of this early deprecation).

I guess this is how Azure wants to manage it's _slow_ transition to new SKUs.

![image](https://user-images.githubusercontent.com/9394024/160895218-4860d1cf-9750-46e9-9c4e-d4bb598d5740.png)

**Comment by Anselmatus** [comment]
After testing again the deployment, it seems to be working fine again for some reason.
I've asked why to the support engineer I was talking to. He answers me the following:

> I have checked with my team and seems that they rolled back the promo block, but we still wouldn't suggest using it for any prod work. Promo skus are not suggested for any real workloads.

Glad to be able to use those SKU again.
Sad to see that, we are lacking information and transparency here, again.
