### ISSUE TITLE
aks-secrets-store-csi-driver goes to CrashLoopBackoff after cluster install

### ISSUE THREAD

**Issue by placated** [Azure/AKS#2879]
**What happened**:

When I deploy the CSI driver for key vault integration the daemonset will enter CrashLoopBackoff on some nodes

$ kk logs aks-secrets-store-csi-driver-jxprx -n kube-system secrets-store
I0401 02:26:08.989023       1 exporter.go:35] "initializing metrics backend" backend="prometheus"
I0401 02:26:09.038384       1 secrets-store.go:41] "Initializing Secrets Store CSI Driver" driver="secrets-store.csi.k8s.io" version="v1.0.0" buildTime="2021-10-14-21:40"
I0401 02:26:09.038389       1 main.go:178] starting manager
I0401 02:26:09.038520       1 mount_linux.go:192] Detected OS without systemd
I0401 02:26:09.038566       1 shared_informer.go:270] caches populated
I0401 02:26:09.038769       1 server.go:120] "Listening for connections" address="//csi/csi.sock"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x137f4c5]

goroutine 39 [running]:
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).RESTMapping.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/client/apiutil/dynamicrestmapper.go:255 +0x45
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).checkAndReload.func1(0x28, 0x38)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/client/apiutil/dynamicrestmapper.go:155 +0x91
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).checkAndReload(0xc000480f50, {0x1afd7c0, 0xc00004c400}, 0xc000656fe0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/client/apiutil/dynamicrestmapper.go:156 +0x9c
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).RESTMapping(0xc000480f50, {{0x190d7f0, 0x0}, {0x158e2c6, 0xc000657088}}, {0xc00027a4d0, 0x1, 0x1})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/client/apiutil/dynamicrestmapper.go:253 +0x168
sigs.k8s.io/controller-runtime/pkg/cache/internal.createStructuredListWatch({{0x190d7f0, 0x1a}, {0x18f1386, 0x2}, {0x158e2c6, 0x1c}}, 0xc0004ac9c0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/cache/internal/informers_map.go:250 +0x14d
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).addInformerToMap(0xc0004ac9c0, {{0x190d7f0, 0x1a}, {0x18f1386, 0x2}, {0x158e2c6, 0x1c}}, {0x1b1b6e0, 0x0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/cache/internal/informers_map.go:213 +0x19a
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).Get(0x2, {0x1b2bbb0, 0xc00068a380}, {{0x190d7f0, 0x1a}, {0x18f1386, 0x2}, {0x158e2c6, 0x1c}}, {0x1b1b6e0, ...})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/cache/internal/informers_map.go:185 +0xf6
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*InformersMap).Get(0xc000432b60, {0x1b2bbb0, 0xc00068a380}, {{0x190d7f0, 0x1a}, {0x18f1386, 0x2}, {0x158e2c6, 0x1c}}, {0x1b1b6e0, ...})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/cache/internal/deleg_map.go:105 +0x279
sigs.k8s.io/controller-runtime/pkg/cache.(*informerCache).List(0xc00011a828, {0x1b2bbb0, 0xc00068a380}, {0x1b5b7a0, 0xc000432b60}, {0xc0003ca1e0, 0x1, 0x1})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/cache/informer_cache.go:79 +0xe5
sigs.k8s.io/secrets-store-csi-driver/controllers.(*SecretProviderClassPodStatusReconciler).Patcher(0xc0004360c0, {0x1b2bbb0, 0xc00068a380})
	/go/src/sigs.k8s.io/secrets-store-csi-driver/controllers/secretproviderclasspodstatus_controller.go:114 +0x38a
sigs.k8s.io/secrets-store-csi-driver/controllers.(*SecretProviderClassPodStatusReconciler).RunPatcher(0x0, {0x1b2bbb0, 0xc00068a380})
	/go/src/sigs.k8s.io/secrets-store-csi-driver/controllers/secretproviderclasspodstatus_controller.go:98 +0x12c
main.main.func4()
	/go/src/sigs.k8s.io/secrets-store-csi-driver/cmd/secrets-store-csi-driver/main.go:186 +0x25
created by main.main
	/go/src/sigs.k8s.io/secrets-store-csi-driver/cmd/secrets-store-csi-driver/main.go:185 +0xeaf
*[master][~/Work_Cloud/terraform/hipass-aks-tf/misc/keyvault]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"56709e92afa973c26fad3d4a44723fefa51481b7", GitTreeState:"clean", BuildDate:"2022-03-10T07:59:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

**What you expected to happen**:

Daemonset would run successfully on all nodes; CSI driver integration would work sucessfully

**How to reproduce it (as minimally and precisely as possible)**:

I can reproduce by deploying the CSI driver via the portal checkbox, with `az cli` or with Terraform

**Anything else we need to know?**:

If I scale cluster down to 1 node it will work fine but if I scale additional nodes some of the csi driver pods will go into CrashLoopBackOff

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"56709e92afa973c26fad3d4a44723fefa51481b7", GitTreeState:"clean", BuildDate:"2022-03-10T07:59:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)

3

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

Blank cluster currently

- Others:

Node image version: AKSUbuntu-1804containerd-2022.03.20
K8s version: 1.21.9
Kubernetes RBAC: Enabled
AKS-managed AAD: Enabled

**Comment by norbertkeri** [comment]
We are also experiencing this, the description from placated is accurate.

**Comment by miwithro** [comment]
@norbertkeri we rolled out a fix for this.  Are you still experiencing the problem?

**Comment by norbertkeri** [comment]
I no longer work on the project, but I'll ping folk who are still on it.
