### ISSUE TITLE
Deployment that causes a node pool upgrade fails because of that node pool upgrade

### ISSUE THREAD

**Issue by fschmied** [Azure/AKS#2880]
**What happened**:
I created a Bicep deployment for an AKS cluster with two node pools (`nodepool1` (System) and `win01` (User)) and applied it to an existing cluster using Azure PowerShell 7.3.2.

The deployment's purpose primarily was to change the `properties.kubernetesVersion` property of the `Microsoft.ContainerService/managedClusters` resource from 1.21.9 to 1.22.6. It did not explicitly specify the `orchestratorVersion` property of the `agentPoolProfiles`, and the existing cluster didn't specify that property, either.

In addition, the deployment also included the `enableAutoScaling` property of `win01` as `false`, which was not previously specified.

All other properties and settings in the deployment were exactly as the existing resource's status quo.

As expected, the deployment initiated a cluster upgrade including node pool upgrades. However, it then failed with the message:
```
New-AzDeployment: 11:55:11 - The deployment 'main' failed with error(s). Showing 1 out of 1 error(s).
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details. (Code: DeploymentFailed)
 - {
  "code": "OperationNotAllowed",
  "message": "Operation is not allowed: Another operation (nodepool1 - Upgrading) is in progress, please wait for it to finish before starting a new operation. See https://aka.ms/aks-pending-operation for more details"
} (Code:Conflict)
```

(I can provide the correlation ID if needed.)

The cluster and node pool upgrades completed successfully, but the deployment was marked as failed.

**What you expected to happen**:
I expected the deployment to initiate a cluster upgrade including node pool upgrades, wait for the upgrades to happen, then succeed.

(I expected it to also change the `enableAutoScaling` property of `win01` to be explicitly set to `false`, but this is likely irrelevant, as the message relates to the other node pool.)

**How to reproduce it (as minimally and precisely as possible)**:
I cannot reproduce the problem. For a second cluster that was set up the same way, an equivalent deployment succeeded.

**Anything else we need to know?**:
I suspect a race condition where the upgrade caused by the deployment may cause the same deployment to be rejected.

**Environment**:
- Kubernetes version (use `kubectl version`): before: 1.21.9, after: 1.22.6
- Size of cluster (how many worker nodes are in the cluster?) 1 Windows worker node (and 1 Linux system node)

**Comment by fschmied** [comment]
@kaarthis Please check this issue so it doesn't go stale. Thank you :) .

**Comment by fschmied** [comment]
Not stale.

**Comment by kaarthis** [comment]
Since we are now in 1.24 version is it reproducible for the latter K8s versions too ?

**Comment by GersonDias** [comment]
having same problem here :/

**Comment by fschmied** [comment]
> Since we are now in 1.24 version is it reproducible for the latter K8s versions too ?

@kaarthis Difficult to say. On the one hand, we're not on Kubernetes 1.24 yet. On the other hand, this is probably a race condition, so it's hard to say for sure if the problem still exists. But as @GersonDias reported having the same problem 18 hours ago, I would guess that yes, it is.

Why do you think that newer Kubernetes versions might fix it? This seems to be an ARM/AKS API issue, not a Kubernetes one?

**Comment by GersonDias** [comment]
My aks cluster was in 1.23.8

**Comment by NoamTD** [comment]
I have also experienced this issue with an aks cluster whose version is 1.24

**Comment by qpetraroia** [comment]
@kaarthis for viz

**Comment by remcoros** [comment]
Any update?

**Comment by fschmied** [comment]
Not completed.

**Comment by fschmied** [comment]
Please reopen.
