### ISSUE TITLE
hostPath volume persistence

### ISSUE THREAD

**Issue by tomasfreund** [Azure/AKS#2884]
We're using promtail to collect logs from containers, it runs as a DaemonSet and mounts `/var/log/pods` to read container logs, tails them and ships them to Loki for storage.
Promtail also needs to store offsets to begin reading the files where it last finished after container (or node) restart.
The common way to do this is to mount a `hostPath` volume and store the offsets there (single yaml file) - it is done this way in the [helm chart](https://github.com/grafana/helm-charts/blob/main/charts/promtail/templates/daemonset.yaml#L125) - `/run/promtail` node path is used.

The issue with this is that this directory seems to be deleted on node reboot (mentioned in #461) but the logs seem to persist after the reboot. This causes promtail to start reading all log files from offset 0 which causes a lot of traffic and also a lot of errors because it is now trying to send outdated logs and duplicates to Loki.

My question - is there is a directory on the node that will persist after reboots or node upgrades in the same way logs do? It does not have to be 100% reliable - we are only storing the log offsets, not actual data.

**Comment by alexeldeib** [comment]
isn't /run a tmpfs? meaning it would always get cleared on reboot regardless of anything AKS does? 

write to a different directory?

**Comment by alexeldeib** [comment]
#461 is about upgrade, a simple reboot should not delete files. memory-based filesystems don't count :)

**Comment by tomasfreund** [comment]
Ok, that makes sense, I managed to track down why someone changed the default volume path form promtail here: https://github.com/grafana/loki/issues/416
It seems that the positions file used to be stored in `/var/log` before the change and because that makes more sense for our setup, we will move it there.
Thanks for the answer
