### ISSUE TITLE
Ownership of /etc/cni/net.d/10-azure.conflist changed between v1.19 and v1.22?

### ISSUE THREAD

**Issue by tspearconquest** [Azure/AKS#2888]
**What happened**:
We upgraded 2 clusters from v1.19 to v1.22. On both, after reaching v1.22, we tried to start up our linkerd deployments which use linkerd-cni. This runs as a daemonset. linkerd-cni mounts `/etc/cni/net.d` from the nodes as a `hostPath` volume.

The linkerd-cni pod runs as root, but we have set `privileged: false` in the container's `securityContext`. It tries to add its configuration to the end of `10-azure.conflist` in the mounted volume. One of our clusters is on v1.18 and this setup works well there. It also worked on v1.19 before we upgraded the 2 clusters.

However, on v1.22, linkerd-cni does not start because it gets a permission denied error on the `10-azure.conflist` file.

We spun up a pod in each of the v1.22 clusters, with the same `hostPath` volume defined, and same `securityContext`, and launched a root shell in the container. When we did, we found that the ownership of `/etc/cni/net.d` directory and its parents is root, but the file `10-azure.conflist` is owned by UID `1001` and permissions are `0600`.

So next we did the same on the v1.18 cluster and found the directory permissions and ownership match the v1.22 clusters, but the file is owned by root.

After that, we edited the daemonsets on the v1.22 clusters to set `privileged: true` and watched linkerd-cni start up properly.

**What you expected to happen**:
We expected linkerd-cni to start properly on v1.22 as it did with v1.18 and v1.19, without requiring `privileged: true` in the daemonset manifest.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy linkerd-cni and use `kubectl edit` to edit the daemonset manifest to set `privileged: false` in the container's `securityContext`, and add the below `entrypoint` in the container:

```
command:
- /bin/sh
- -c
- sleep 1800
```

Then exec a shell in the redeployed pod and check the output of `cat /etc/cni/net.d/10-azure.conflist` - it fails for us
Then exit the shell, edit the daemonset manifest and set `privileged: true` in the container's `securityContext`
Wait for the pods to be redeployed, and then exec another shell and check the output of `cat /etc/cni/net.d/10-azure.conflist` again - it succeeds for us

**Anything else we need to know?**:
This is a regression from working functionality. I have been unable to find anything mentioning this change or the reason behind it, and we would really like not to have to run these pods `privileged`

**Environment**:
- Kubernetes version (use `kubectl version`): v1.22.6
- Size of cluster (how many worker nodes are in the cluster?) 2 in 1 of the v1.22 clusters and 7 in the other. 2 in the v1.18 cluster
- Others:

**Comment by alexeldeib** [comment]
@paulgmiller fyi

this was due to a change in upstream build artifacts and a bug around setting permissions during download of those artifacts.

seems we managed to make linkerd unhappy because the config file is root, and istio unhappy because the binaries _aren't_ owned by root. 

would simply chmod 644'ing these files work for you?

**Comment by alexeldeib** [comment]
I see. I'm inclined not to make any changes without a repro if things are working fine for you now, since changing these values was exactly what caused issues :/ 

If you (or anyone else) are able to repro, feel free to circle back. But I think I'd mark this closed for now?
