### ISSUE TITLE
Node failure testing causes nodes to be in NotReady

### ISSUE THREAD

**Issue by jay-wilson** [Azure/AKS#289]
I have used the following to create the resource group and aks cluster
`az group create --name myresourcegroup --location centralus` 

`az aks create --resource-group myresourcegroup  --name aks-mycluster  --node-count 3 --kubernetes-version  1.8.7 --node-vm-size Standard_D1_v2 --generate-ssh-keys`

```
k get nodes
NAME                       STATUS    ROLES     AGE       VERSION
aks-nodepool1-12842854-0   Ready     agent     1h        v1.8.7
aks-nodepool1-12842854-1   Ready     agent     1h        v1.8.7
aks-nodepool1-12842854-2   Ready     agent     1h        v1.8.7
```

To test one of the node failure scenario, I ssh to a particular node and did a reboot. Subsequently the node is in a NotReady state for several hours. I dont think azure kubernetes cluster is able to figure out that a node is down and bring up another node or recover the same
```
k get nodes
NAME                       STATUS     ROLES     AGE       VERSION
aks-nodepool1-12842854-0   Ready      agent     4h        v1.8.7
aks-nodepool1-12842854-1   Ready      agent     4h        v1.8.7
aks-nodepool1-12842854-2   NotReady   agent     4h        v1.8.7
```

Any way to recover the node? (What may have happened?)
Anyway to continue with my node failure testing without running into this issue.

**Comment by seniorquico** [comment]
We had a node fail just a few days ago in one of our AKS clusters, and it never recovered from the NotReady status. Sounds like the same in #256.

We decided to leave the system as-is and open an Azure technical support request. We're hoping to get someone to provide this exact type of guidance on how best to proceed. I'll share what I can when I hear back from someone.

**Comment by baracoder** [comment]
@seniorquico did you get any response about this issue?

**Comment by shahiddev** [comment]
I have a couple of clusters that I use for demos and I've configured vm autoshutdown on the worker nodes. I've not had any issues with the cluster and nodes coming online.  
This was before and since GA (currently have one 1.9.6 cluster and one 1.10.x cluster).

**Comment by sauryadas** [comment]
@baracoder @seniorquico if you are still seeing this issue please let me know. I am closing this issue as it seems to be working fine.
