### ISSUE TITLE
[Private Clusters] Custom subnet for K8S API private endpoint

### ISSUE THREAD

**Issue by EppO** [Azure/AKS#2892]
### Summary

When creating a private AKS cluster, a private endpoint `kube-apiserver` is created in the Infrastructure resource group automatically. There is no settings available to decide what subnet this private endpoint should use, it will use the worker nodes subnet. 

### Current situation

Today, the `--vnet-subnet-id` option of `az aks create` command specifies where the nodes, the pods and `kube-apiserver`  private endpoint will be deployed. A first step to loosen this restriction is being address by "Dynamic allocation of IPs and enhanced subnet support" currently in preview, that introduces the `--pod-subnet-id` parameter.

If we read correctly this [documentation](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks), Azure recommends to have a dedicated subnet for private links/endpoints. But It can't be done today for `kube-apiserver`.

### Feature request

We need a way to pass a subnet Id parameter to the `az aks create` command that will be use to decide where the `kube-apiserver` private endpoint will get created. If omitted, it should default to the worker node subnet.

**Comment by rouke-broersma** [comment]
You can also simply create a new private endpoint for your aks cluster in the subnet you want it in and ignore the private endpoint that is managed by AKS.

**Comment by EppO** [comment]
Thanks for the hint how to do it manually. However, I think the feature request stands. It would be neat to have it from the get-go during the AKS provisioning without having the NIC of the private endpoint created automatically in the nodes subnet that you don't use.

**Comment by EppO** [comment]
@phealy: could you consider this feature request please?

**Comment by EppO** [comment]
ping
