### ISSUE TITLE
Metrics-server deployment doesn't let me change the memory resource limit

### ISSUE THREAD

**Issue by devneutz** [Azure/AKS#2893]
**What happened**:
On a relatively small cluster with 2 nodes we wanted to scale down the memory resource limit of the metrics-server. The default value of 2000Mi seemed unreasonable since we are barely using 3% of it.

Trying to set the resource limit by using kubectl like this:

`kubectl set resources deployment metrics-server --limits=memory=200Mi -n kube-system`

This initially worked fine. But after a few seconds, the deployment was reset back to the initial value of 2000Mi.

What am I missing? How is the resource limit managed for the metrics-server deployment? I couldn't find any configuration or an addon-resizer which would explain that behaviour.

**What you expected to happen**:
Resource limit set to the limit specified within the kubectl command.

**How to reproduce it (as minimally and precisely as possible)**:
A standard managed cluster will deploy metrics-server as part of the azure kubernetes service.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.6
- Size of cluster: 2 worker nodes

**Comment by thiDucTran** [comment]
https://learn.microsoft.com/en-us/azure/aks/use-metrics-server-vertical-pod-autoscaler#manually-configure-metrics-server-resource-usage ?
