### ISSUE TITLE
[HTTP-PROXY FEATURE] Date of Global Availability

### ISSUE THREAD

**Issue by infra-cai** [Azure/AKS#2894]
**What happened**:

I need to know if you have a date of global availability for the feature Http-Proxy because we need to use it in production environement at the end of this year.

Thanks for you help.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by miwithro** [comment]
This will be GA by the end of May 2022.
