### ISSUE TITLE
Feature Request: Ability to configure which subnet the AKS PrivateEndpoint is deployed to separate from default NodePool

### ISSUE THREAD

**Issue by justbert** [Azure/AKS#2895]
While trying to re-architect the platform we are building to take advantage of subnet isolation to more securely isolate resources. Currently, the API server's PrivateEndpoint uses an IP from the subnet in which the IPs of the Nodes in the default NodePool are allocated. 

Since the API server is a resource that is generally accessible to our Developer community compared to the Nodes, we would like a harder network separation. As such, it would be great if a subnet could be specified separately from the default NodePools subnet.

Currently, it is possible to instantiate an AKS cluster with the default NodePool in the subnet where the API servers PrivateEndpoint should reside then replace the default NodePool with a new system typed NodePool in the subnet where it should reside. This, however, is a bit unwieldy and does require some extra work.

1. Create cluster using az cli / terraform with default NodePool in subnet where API server should reside.
1. Create new system nodepool with az cli / terraform in the system subnet.
1. If using Terraform remove the azurerm_kubernetes_cluster and azurerm_kubernetes_cluster_node_pool from the state.
1. If using Terraform: Update the default_node_pool configuration to have the same name as the new system nodepool created.
1. Delete the default nodepool using the CLI.
1. If using Terraform: Import the AKS cluster into the azurerm_kubernetes_cluster resource.

**Comment by rouke-broersma** [comment]
@justbert you can also simply create a new private endpoint for your aks cluster in the subnet you want it in and ignore the private endpoint that is managed by AKS.
