### ISSUE TITLE
Ubuntu 22.04

### ISSUE THREAD

**Issue by miwithro** [Azure/AKS#2897]
Adding support for Ubuntu 20.04 on AKS.

**Comment by PixelRobots** [comment]
https://github.com/Azure/AKS/issues/2883

**Comment by alexeldeib** [comment]
@miwithro we've got a few existing issues for this, how about we close this as dupe? already closed a few others. 

2883 is tagged as a feature request.

**Comment by miwithro** [comment]
closing duplicate to #2883

**Comment by jabbera** [comment]
This looks like it will fix the issue I'm fighting with daily: https://github.com/Azure/AKS/issues/2911. Is this going into preview any time soon? Any way I can get in a private preview?

**Comment by miwithro** [comment]
@jabbera we are working on a Public Preview date.  Follow this issue for updates.

**Comment by jabbera** [comment]
Thanks!

**Comment by joejulian** [comment]
This ticket was on the project board before it was closed as a duplicate of #2883, but #2883 is not. Should it be?

**Comment by jabbera** [comment]
@miwithro Any way you can provide me a preview date? I'm currently struggling with support to get out of order UDP delivery enabled on my network so I can use NFS 3 instead but nothing seems to be easy:-)

**Comment by miwithro** [comment]
@jabbera we are looking at Sept as the release date corresponding with the Release of 1.25

cc @justindavies

**Comment by jabbera** [comment]
Oof. Thanks for the info!

**Comment by miwithro** [comment]
@cpressland correct we decided to go with 22.04 instead of 20.04.  We are targeting AKS 1.25 for the release of 22.04.

**Comment by EppO** [comment]
> @cpressland correct we decided to go with 22.04 instead of 20.04. We are targeting AKS 1.25 for the release of 22.04.

that means AKS 1.25 will use cgroups v2, right?

**Comment by alexeldeib** [comment]
^yes!

**Comment by alexeldeib** [comment]
gah I keep forgetting there's a dupe because one's 20.04 and 22.04 -_-

**Comment by alexeldeib** [comment]
for posterity updated https://github.com/Azure/AKS/issues/2897 to clarify we will move directly to 22.04
