### ISSUE TITLE
AKS: some services are not reachable from specific windows node

### ISSUE THREAD

**Issue by perosb** [Azure/AKS#2899]
**What happened**:
pod is unable to communicate with service

**What you expected to happen**:
the service should respond

**How to reproduce it (as minimally and precisely as possible)**:
no clue how to reproduce, it has happened a couple of times.

**Anything else we need to know?**:

The pod gets no response from service.
```
$ kubectl describe svc xdbrefdata
Name:              xdbrefdata
Namespace:         prd01
Labels:            <none>
Annotations:       <none>
Selector:          app=xdbrefdata
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.187.128.253
IPs:               10.187.128.253
Port:              <unset>  80/TCP
TargetPort:        80/TCP
Endpoints:         10.187.0.170:80,10.187.0.57:80
Session Affinity:  None
Events:            <none>
```
Making the same call to each individual pod behind the service works.
```
PS C:\inetpub\wwwroot> curl.exe xdbrefdata
curl: (7) Failed to connect to xdbrefdata port 80: Timed out

PS C:\inetpub\wwwroot> curl.exe 10.187.128.253
curl: (7) Failed to connect to 10.187.128.253 port 80: Timed out
```
The same service works from another pod in the same replicaset.
```
PS C:\inetpub\wwwroot> curl.exe -sI 10.187.0.170
HTTP/1.1 200 OK
```
```
PS C:\inetpub\wwwroot> curl.exe -sI 10.187.0.57
HTTP/1.1 200 OK
```

It's the same behaviour with other pods on the same windows node.

Other services are reachable:
```
PS C:\inetpub\wwwroot> curl.exe -sI xdbcollection
HTTP/1.1 200 OK
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"5963a7a5570a1b8c977c31ced503cb20f0ef6e8c", GitTreeState:"clean", BuildDate:"2022-03-10T07:59:42Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

```
System Info:
  Machine ID:                 akswp01000000
  System UUID:                A33DAF46-3E7A-49FB-987D-97F180F3BAAC
  Boot ID:                    
  Kernel Version:             10.0.17763.2686
  OS Image:                   Windows Server 2019 Datacenter
  Operating System:           windows
  Architecture:               amd64
  Container Runtime Version:  containerd://1.6.1+azure
  Kubelet Version:            v1.22.6
  Kube-Proxy Version:         v1.22.6

```

- Size of cluster (how many worker nodes are in the cluster?)
    2 linux, 3 windows
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
    HTTP services (dotnet/core)

**Comment by perosb** [comment]
I manually edited the service selector to something bogus, and then changed back again and the communication works.

**Comment by perosb** [comment]
This happened again today for other services on Windows. Same solution.

**Comment by perosb** [comment]
Again the same but against the kubedns

.10 is the Service IP
.130 is the pod IP
![image](https://user-images.githubusercontent.com/982752/168089168-e36294bd-223e-44f8-aa44-f3834970dd24.png)

And confirmed same workaround works again, bogus change on the kube-dns service makes it works.
Right now AKS is not production ready for our workloads.
![image](https://user-images.githubusercontent.com/982752/168089525-32c0303b-780d-4570-8555-f950d032acd7.png)

Yesterday someone else confirmed the same issue.

**Comment by cburne-oshyn** [comment]
Yes, same symptoms happened to me, however I solved by restarting the Windows Kube node.  I have only had this issue with Kube Nodes, not with linux nodes.  I will try @perosb's solution next time it occurs as it's less disruptive than restarting the entire node.

I also agree with @perosb that I'm unable to trust this for production workloads.

**Comment by bala-one** [comment]
We had the same exact issue happened to us after a deployment. We killed the pod and recreated to solve the issue. I agree with @perosb its risky not knowing this issue until something fails.

**Comment by adoprog** [comment]
We do have similar issues from time to time. It is always Windows node that has issues.

**Comment by cburne-oshyn** [comment]
What is the least impactful remediation you've found to work?  Because I have restarted the node and it requires cordoning so all pods have to go to another node while it restarts.  If there was a less disruptive mechanism to fix, it would be better.

**Comment by bala-one** [comment]
We cordon the node having to restarted and scale up the number of pods, that will get started in the new node. Eventually kill the  node that had issue. Scale down the pods after the process. We were successful with the least impact in production.

**Comment by perosb** [comment]
> What is the least impactful remediation you've found to work? Because I have restarted the node and it requires cordoning so all pods have to go to another node while it restarts. If there was a less disruptive mechanism to fix, it would be better.

Editing the service is quick and easy for us. https://github.com/Azure/AKS/issues/2899#issuecomment-1099115322
In our case we just changed the selector but might work with something else less intrusive.

**Comment by perosb** [comment]
> This looks similar to something that we've been discussing in sig-windows: https://app.slack.com/client/T09NY5SBT/C0SJ4AFB7/thread/C0SJ4AFB7-1654723929.652899
> 
> when this happens can you run `get-content c:\k\kubeproxy.err.log | sls <ip of service>` on the node affected? Want to see if the service ever gets created on the node.

Just happening now....

```
I0620 03:33:18.895141    4056 service.go:419] "Adding new service port" portName="be-dev01/xdbrefdata" servicePort="10.185.128.116:80/TCP"
I0620 03:33:18.910388    4056 proxier.go:766] "Service cleanup" serviceInfo="10.185.128.116:80/TCP"
I0620 03:33:46.460254    4056 proxier.go:766] "Service cleanup" serviceInfo="10.185.128.116:80/TCP"
I0620 03:36:41.916008    4056 proxier.go:766] "Service cleanup" serviceInfo="10.185.128.116:80/TCP"
I0620 03:41:03.155321    4056 proxier.go:766] "Service cleanup" serviceInfo="10.185.128.116:80/TCP"
I0620 03:41:03.155418    4056 proxier.go:766] "Service cleanup" serviceInfo="10.185.128.116:80/TCP"
I0620 03:41:03.220507    4056 hnsV2.go:284] "Hns loadbalancer policy resource" loadBalancer=&{Id:e2a093a0-e992-4b0e-9c4e-70f125aaa323 HostComputeEndpoints:[c4ca688b-f76e-4c80-8a26-2476e7f6b001] SourceVIP: FrontendVIPs:[10.185.128.116] PortMappings:[{Protocol:6 InternalPort:80 ExternalPort:80 DistributionType:0 Flags:0}] SchemaVersion:{Major:2 Minor:0} Flags:1}
I0620 03:41:03.221032    4056 proxier.go:1233] "Hns LoadBalancer resource created for cluster ip resources" clusterIP="10.185.128.116" hnsID="e2a093a0-e992-4b0e-9c4e-70f125aaa323"
I0620 03:41:03.221139    4056 proxier.go:1325] "Policy successfully applied for service" serviceInfo="10.185.128.116:80/TCP"
I0620 03:53:52.910879    4056 proxier.go:766] "Service cleanup" serviceInfo="10.185.128.116:80/TCP"
I0620 03:53:52.929249    4056 proxier.go:766] "Service cleanup" serviceInfo="10.185.128.116:80/TCP"
I0620 03:55:07.626915    4056 proxier.go:766] "Service cleanup" serviceInfo="10.185.128.116:80/TCP"
I0620 03:55:07.627630    4056 proxier.go:766] "Service cleanup" serviceInfo="10.185.128.116:80/TCP"
I0620 03:55:19.597745    4056 proxier.go:766] "Service cleanup" serviceInfo="10.185.128.116:80/TCP"
I0620 03:59:12.834548    4056 proxier.go:766] "Service cleanup" serviceInfo="10.185.128.116:80/TCP"
I0620 04:04:13.944584    4056 proxier.go:766] "Service cleanup" serviceInfo="10.185.128.116:80/TCP"
I0620 04:04:13.945306    4056 proxier.go:766] "Service cleanup" serviceInfo="10.185.128.116:80/TCP"
I0620 04:04:14.039984    4056 hnsV2.go:205] "Found existing Hns loadbalancer policy resource" policies={Id:e2a093a0-e992-4b0e-9c4e-70f125aaa323 HostComputeEndpoints:[c4ca688b-f76e-4c80-8a26-2476e7f6b001] SourceVIP: FrontendVIPs:[10.185.128.116] PortMappings:[{Protocol:6 InternalPort:80 ExternalPort:80 DistributionType:0 Flags:0}] SchemaVersion:{Major:2 Minor:0} Flags:1}
I0620 04:04:14.039984    4056 proxier.go:1233] "Hns LoadBalancer resource created for cluster ip resources" clusterIP="10.185.128.116" hnsID="e2a093a0-e992-4b0e-9c4e-70f125aaa323"
I0620 04:04:14.039984    4056 proxier.go:1325] "Policy successfully applied for service" serviceInfo="10.185.128.116:80/TCP"

```

**Comment by jsturtevant** [comment]
It looks like the policy should have been applied to the node at the end of the logs there (`I0620 04:04:14.039984`).  It looks like it was applied, then some endpoints might have changed and cleaned things up then re-applied.  

If you run `hnsdiag list all` do you see the `10.185.128.116` as a vip under the loadbalancers? and do you see the endpoints it points to under the endpoints section?

**Comment by adoprog** [comment]
Just in case this helps investigation - for us it happens more often when we start or restart multiple pods simultaneously.
We have 6 pods in a namespace, 4 Windows and 2 Linux (Solr, MS SQL).

By "start" I mean setting number of replicas from 0 to 1 for all of them simultaneously.
By "restart" I mean 'kubectl delete --all pods --force --namespace $Namespace'

Very often Windows pods would lose connection to either SQL or Solr.

**Comment by perosb** [comment]
"Unfortunately" the app team made new deployments last night which seem to have resolved this again. Need to wait for next occurance.

**Comment by perosb** [comment]
Looks like the same as in original post.

**Comment by jayunit100** [comment]
sounds like we need an upstream k/k issue for this?

**Comment by jsturtevant** [comment]
this looks similar to https://github.com/kubernetes/kubernetes/issues/110674

**Comment by perosb** [comment]
As I understand it there is a workaround in https://github.com/Azure/AKS/releases/tag/2022-08-21 that will try restart HNS service if it crashed. https://github.com/Azure/AgentBaker/pull/2085

**Comment by perosb** [comment]
This is really sad that this is still happening. It basically makes AKS dead in the water for Windows containers.
No resolution after 5 months doesn't look good. Running a public issue tracker takes some effort from MS that clearly isn't there!

**Comment by perosb** [comment]
:man_shrugging:

**Comment by picoseconddillo** [comment]
@perosb Check out the new build of AKS as it's released to various regions.  We've run into a similar set of issues on 105,000 Windows nodes over the past 9 months.  We've run the new binary referenced in this commit in our test environments and it's been great so far: https://github.com/Azure/AgentBaker/commit/0b2dfacca0f9d953eacbf9cafadb7b6ae16e5ea5

In our test environments we dropped down from 22.3 to 0.14 node failures per day.  We've run into this bug a lot more than others due to how many Windows container we schedule (190 million so far this year).  I'm excited to see if production lines up with our test environments next week. That new binary is only on 2022 currently, it should be in 2019 in November. 
 Hopefully it helps you!
