### ISSUE TITLE
AKS managed images have outdated packages

### ISSUE THREAD

**Issue by akamienski** [Azure/AKS#2901]
AKS managed images have outdated packages, as listed by 3rd party monitoring tool, that uses Common Vulnerabilities and Exposures standards. It detected almost 500 vulnerabilties, which means that AKS managed images are unsecure to use on production at this point.
[image_vurn_aks_issues.xlsx](https://github.com/Azure/AKS/files/8494703/image_vurn_aks_issues.xlsx)

**Comment by akamienski** [comment]
Hello,

1. I already did that, and was told to open a ticket here.
3. I did read that, but the issue wasn't described there.
5. Haven't found ticket with similar issues.

**Comment by miwithro** [comment]
@akamienski AKS patches CVE's that have a vendor fix every week.  You are running a VHD from 12.04.2022 which is 4 months old.  We have released 12 patched VHD's since then.  Please run az aks update -n <> -g <> --node-image-only to upgrade to a patched VHD.

**Comment by akamienski** [comment]
Hello,

I've got the same recommendation from MS support, but I was getting an error while running this command (unrecognized arguments: --node-images-only), so I run other command, suggested from MS support which looks like this:
![issue1](https://user-images.githubusercontent.com/27349174/165271814-f3e99bd3-47d7-4f29-b342-925f7b0f1f09.png)

That command didn't change anything when I last run it (which was two weeks ago), but I run it again today, and will get back to you tomorrow with result, once I'll receive a vulnerability report.

**Comment by CocoWang-wql** [comment]
Feel free to check the image version and ensure it's latest one.
![image](https://user-images.githubusercontent.com/45681473/165274290-c3a53aeb-d3dd-4697-a45a-0bbb48393340.png)

**Comment by akamienski** [comment]
Hello,

this is the version that is showed in Azure AKS correct. I checked report from today and this time it actually decreased amount of alerts very significantly, but first time I run it, it had not made any impact at all. Do you have any idea why was that the case?

**Comment by CocoWang-wql** [comment]
The image 2022.04.05 was released recently. Maybe the first time you running upgrade, the image version was not the latest one. Also it's recommended to check the image version after upgrade command and make sure the image was updated. Please contact the support and there might exist logs about the node image upgrade and the version for first time.
