### ISSUE TITLE
Authorized IP ranges bug in the Azure Portal

### ISSUE THREAD

**Issue by seenu433** [Azure/AKS#2902]
When trying to set Authorized IP ranges in the Azure Portal, a space between the comma separated list seems to cause the update to fail. This is not the same behavior as the CLI. When this is updated using the CLI and you view the configuration in the portal, it seems to have removed the spaces.

The Portal UI should either be clearer that spaces are not accepted or remove them as part of the input/form submission.

**Comment by raghulmsft** [comment]
@seenu433 : Thanks for sharing it with us. I am a PM with the AKS portal team and have passed it along to our dev leads to look into it!

**Comment by raghulmsft** [comment]
This issue has bee fixed!
