### ISSUE TITLE
Azure Key Vault CSI Driver Add-on don't rotate secrets

### ISSUE THREAD

**Issue by mohamedsaif** [Azure/AKS#2910]
**What happened**:
Enabled AKS CSI add on with secret rotation enabled and configured to 2 mins.
Secrets are not rotated no matter how long the wait.

To validate that my setup is correct, I've installed on a separate cluster AKV CSI driver via Helm (while enabling auto rotation) and used exactly the same user assigned identity, key vault, deployment, secret setup and actually secret rotation is working fine with the following observations (with helm installation):

- Mounted volume is updated and read by the application successfully with the new value within the window of rotation
- Noticed rotation kubernetes events in the running pod (for both the volume and synced secrets)

This led me to assume there is a misconfiguration with the CSI add-on.

This is the add-on profile:
```bash
az aks show -g $AKS_RG -n $AKS_NAME --query 'addonProfiles.azureKeyvaultSecretsProvider'
```
```json
{
  "config": {
    "enableSecretRotation": "true",
    "rotationPollInterval": "2m"
  },
  "enabled": true,
  "identity": {
    "clientId": "GUID",
    "objectId": "GUID",
    "resourceId": "/subscriptions/SUBSCRIPTION/resourcegroups/MC_RG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azurekeyvaultsecretsprovider-CLUSTER-NAME"
  }
}
```

**What you expected to happen**:
AKS Add-on CSI provider should rotate secrets within the window of rotation when configured.

**How to reproduce it (as minimally and precisely as possible)**:
I've created detailed repo of the steps and yaml configuration used (for both AKS add-on and Helm installation methods) that can be found here: 

[https://github.com/mohamedsaif/akv-secret-csi](https://github.com/mohamedsaif/akv-secret-csi)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (1.22.6)

**Comment by victorpachas** [comment]
I have the same error, i tried to configure the rotate of secret with Azure Key Vault Provider for Secrets Store CSI Driver, but it does not work.

**Comment by ZeroMagic** [comment]
Here is the workaround. https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/939#issuecomment-1105103273

The fix in AKS is being rolled out now.

**Comment by ppanyukov** [comment]
@ZeroMagic do you know what we need to do to apply the fix to the existing clusters? Will it happen automatically or we need to actually do something ourselves?

**Comment by ZeroMagic** [comment]
Ops, the fix is still ongoing. Open it again.
If someone still get the error, please use the above workaround.

**Comment by tringuyen-yw** [comment]
This issue is also mentioned upstream with temporary workaround 
[Failed to get service account token attrs -- failed to fetch token (forbidden)](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/939#issuecomment-1105103273)

**Comment by ovie91** [comment]
Hey I'm running AKS cluster in version 1.23.5 and issue is still there.

Key is mounted but are not being rotated.

Workaround is working.

**Comment by miwithro** [comment]
@ovie91 what region is your cluster in?  The fix is in most regions as of right now, and will be in all regions by tomorrow.

**Comment by ovie91** [comment]
> @ovie91 what region is your cluster in? The fix is in most regions as of right now, and will be in all regions by tomorrow.

westeurope

**Comment by miwithro** [comment]
@ovie91 westeurope will be deployed tomorrow.
