### ISSUE TITLE
Image Cleaner (Eraser) enabled on AKS cluster 

### ISSUE THREAD

**Issue by CocoWang-wql** [Azure/AKS#2912]
With Image Cleaner, we could detect & remove all the unused & vulnerable images stored on AKS nodes.
https://docs.microsoft.com/en-us/azure/aks/image-cleaner?tabs=azure-cli

**Comment by littleccguy** [comment]
Hello,
At work, we redeploy images to our cluster daily.  There seems to be a lot of stale images left around.  I tried to get this working on my cluster, but I cannot enable it.  All other [steps in the doc](https://learn.microsoft.com/en-us/azure/aks/image-cleaner?tabs=azure-cli) worked fine up to the point of enabling.  The response back was
`unrecognized arguments: --enable-image-cleaner`

**Comment by miwithro** [comment]
@littleccguy how are you trying to deploy image cleaner- terraform, cli etc.

If you are using cli you need to have the updated aks-preview API loaded

**Comment by CocoWang-wql** [comment]
Pls use 'az --version' to check the version and ensure you have aks-preview 0.5.96 or later CLI extension installed.
Also run the below command to ensure 'ImageCleaner' is 'registered'
```
az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/EnableImageCleanerPreview')].{Name:name,State:properties.state}"
```

**Comment by littleccguy** [comment]
Thank Coco,

At what level is aks-preview installed?  Subscription, resource group, or cluster?

 

Mark

**Comment by CocoWang-wql** [comment]
It's on your client (local, azure bash, jump box, etc). 
The detailed steps are: 
1) Check whether you have installed aks-preview extension
az extension list  
2) Remove the extension if you installed
az extension remove -n aks-preview
3) Install the latest version
az extension add -n aks-preview

**Comment by littleccguy** [comment]
Thank you @CocoWang-wql.  I got it installed and the interval set.  Is there anyway to know/set what time of day this would run?

**Comment by CocoWang-wql** [comment]
Hello @littleccguy , sorry for the delay as the message is buried. The first time of running is the installation time. The second running time is installation time + scan interval time. You can control both installation time and interval  to set the desired running time.

**Comment by littleccguy** [comment]
Thank you

**Comment by mdaslamansari** [comment]
What is its expected GA timeframe?

**Comment by CocoWang-wql** [comment]
[Image Cleaner](https://learn.microsoft.com/en-us/azure/aks/image-cleaner) is GA on 20th August.

**Comment by tommychoy** [comment]
@CocoWang-wql. Image Cleaner is now GA, but it is still required to install the aks-preview extension to enable it?

**Comment by CocoWang-wql** [comment]
We don't need the 'aks-preview extension' anymore. Did you meet any error when enabling image cleaner without aks-preview extension? @tommychoy

**Comment by tommychoy** [comment]
@CocoWang-wql , just re-ran the command in cloud shell, the aks-preview extension requirements does not pop-up anymore. Thanks.
