### ISSUE TITLE
Incorrect link to documentation page in Portal for CSI add-on

### ISSUE THREAD

**Issue by naioja** [Azure/AKS#2914]
**What happened**:
In the Portal experience for enabling the CSI driver add-on for AKS the link provided on the mouse hover tooltip is pointing to a documentation page not relevant for the CSI driver.

![image](https://user-images.githubusercontent.com/6505576/165513235-172845ad-6848-4cac-b66f-b71cefd190a2.png)

**What you expected to happen**:
The Learn more link points to : https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-use-gitops-connected-cluster#apply-configuration-from-a-private-git-repository

whereas it should point to : https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver

**How to reproduce it (as minimally and precisely as possible)**:
Login to the Portal to any AKS service, go to the Configuration blade, and hover over the Learn more tool tip for CSI driver add-on.

**Comment by raghulmsft** [comment]
@naioja : Thanks for reporting it! I am a PM with the AKS portal team and will get this fixed right away!

**Comment by raghulmsft** [comment]
Thanks for sharing it with us! We have updated the links now:)

**Comment by CocoWang-wql** [comment]
Hello @raghulmsft, can you pls help to check this issue?~

**Comment by raghulmsft** [comment]
The links were updated in June!
