### ISSUE TITLE
Can we use VMs without temporary storage in AKS?

### ISSUE THREAD

**Issue by polys** [Azure/AKS#2917]
Please, could you clarify whether VMs without temporary storage (e.g. D2s_v5, D4s_v4, etc.) are appropriate for AKS node pools?

**Comment by polys** [comment]
Can I please ask for a response?
Or at least a pointer to some documentation out there...

**Comment by andyzhangx** [comment]
@polys Yes, AKS supports such VM size without temp disk. What's the motivation why you want to use such vm size without temp  disk?

**Comment by polys** [comment]
Many thanks for the response @andyzhangx

Well, I could see that those VMs sizes are available to use but not sure if they're actually ok to use with system (K8s/AKS) workloads. I know my workloads don't explicitly use it but is something under-the-hood making use of them?

My motivation is purely around cost and waste... I know the price difference is quite small but if those temp disks aren't actually used by anything, why would I get them?

**Comment by andyzhangx** [comment]
@polys AKS won't use those temp disks by default, so it's ok use use with system (K8s/AKS) workloads
