### ISSUE TITLE
"az aks upgrade" deleted my private registry secret

### ISSUE THREAD

**Issue by neildonkin** [Azure/AKS#292]
I just upgraded to v1.9.6 using the `az aks upgrade` command in Azure Cloud Shell and my private registry secret was deleted.  My pods could not re-start until I manually re-created the secret and deleted the pods to force them to be re-created.

I'm using the West Europe region.

**Comment by mboersma** [comment]
@neildonkin sorry! We haven't heard of `upgrade` causing any issues like this, so I'm not sure what's going on.

Could you send details with subscription ID, resource group name, Azure region, and cluster name to aks-help@service.microsoft.com so we can investigate?
