### ISSUE TITLE
Creating node pool with "--vnet-subnet-id" parameter referencing the managed subnet returns error "The Agentpool <existing-nodepool-name> does not have subnet defined."

### ISSUE THREAD

**Issue by andbaraks** [Azure/AKS#2927]
**What happened**:
Creating node pool with "--vnet-subnet-id" parameter referencing the managed subnet returns error "The Agentpool <existing-nodepool-name> does not have subnet defined."

For example:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/68290745/166682396-c23aed11-1ecd-41bf-9162-8ca39e4b0e0e.png">

This is reproducible if the AKS cluster has a managed VNET so:
-if the AKS cluster was created from CLI without "--vnet-subnet-id" parameter
-if the AKS cluster was created from Azure Portal with Kubenet network plugin
*there may be other scenarios that I didn't discover

**What you expected to happen**:
Be able to create a node pool while referencing the managed subnet.

Also the error doesn't make sense and is confusing.

**How to reproduce it (as minimally and precisely as possible)**:
1 - Create the AKS cluster without "--vnet-subnet-id". For example: az aks create -g cluster-rg -n cluster

2 - After the AKS cluster gets created, go to the infrastructure resource group, check the default VNET/subnet that got created and run this to get the VNET/subnet resource ID: az network vnet subnet show -g <infrastructure-rg> -n aks-subnet --vnet-name aks-vnet-12345678 -o tsv --query id

3- Create a new node pool with "--vnet-subnet-id". For example: az aks nodepool add -g cluster-rg --cluster-name cluster -n newnp --vnet-subnet-id <VNET-subnet-ID>

**Anything else we need to know?**: N/A

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"07959215dd83b4ae6317b33c824f845abd578642", GitTreeState:"clean", BuildDate:"2022-03-30T18:28:25Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (how many worker nodes are in the cluster?): Not relevant
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Not relevant
- Others: N/A

**Comment by tyler-lloyd** [comment]
Expected behavior. Closing issue.
