### ISSUE TITLE
AKS Excessive Logs generation from OMS Agent

### ISSUE THREAD

**Issue by villanub** [Azure/AKS#293]
Following this document: https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-monitor results in an 8 GB per day log being generated by the AKS cluster and the OMS agent, this seems to be an issue as this amount of log generation is excessive. This is just on the default deployment of AKS with no additional containers running besides the OMS.

**Comment by seniorquico** [comment]
Just to add another data point for those looking...

We recently setup several small AKS clusters on the latest available version of K8s to test OMS and other logging agents. The cluster had 4 Standard_A1_v2 nodes. We deployed two DaemonSets to the cluster using Helm/Tiller: the OMS agent and an ASP.NET Core web site that just sat idle.

We found that OMS ingested 1GB of log data per day (that's with essentially nothing coming from the ASP.NET Core site). That's not quite as bad as what you encountered. However, we also observed that the OMS agents ran away with around 600MB of RAM each after a couple of days.

**Comment by Zimmergren** [comment]
I've also noticed the OMS replicas spending about 500+ MB of ram, pretty consistently after they started processing. 

Are there any neat capabilities to configure what to log? Inclusion/exclusion patterns, queries, filters?

**Comment by nyuen** [comment]
I'm having the same issue here on both the Ram consumption from the OMS Agent and the ingested data

**Comment by vishiy** [comment]
hi now with aks health agent does not collect logs from kube-system namespace by default. have u tried the newer versions thru out of the box monitoring in aks?

**Comment by erewok** [comment]
Hello, I'd like to be able to get logs from an ingress-controller which has been deployed into the `kube-system` namespace. Is there anyway to enable to logs in that namespace for particular deployments, etc.?

**Comment by erewok** [comment]
I did the following:

```kubectl describe deployments omsagent-rs -n kube-system
Pod Template:
  Labels:           rsName=omsagent-rs
  Annotations:      agentVersion=1.6.0-42
                    dockerProviderVersion=2.0.0-3
  Service Account:  omsagent
    Environment:
      DISABLE_KUBE_SYSTEM_LOG_COLLECTION:  true
```

Is there any way to enable log-collection for a particular set of deployments in `kube-system`? I imagine ingress controllers are one place where people are going to want to search logs. Is the only answer that we should deploy the controller in another namespace?

**Comment by vishiy** [comment]
@erewok - currently there is no way to collect logs selectively inside 'kube-system' namespace. its turned off for kube-system namespace. For the future, we are looking into exposing that as a setting in the Ux to easily control.

**Comment by erewok** [comment]
okay, thanks for the help. I'll try to solve this problem in some other way.

**Comment by dewnull** [comment]
Is there away to exclude pods or namespaces from Log Analytics?

**Comment by peterwy01** [comment]
Would be great to have more flexibility, what exactly is logged with the OMS-Agent.

**Comment by jamoham** [comment]
I see that this issue has been closed. Is the feature to include/exclude pods/containers available now?

**Comment by Mandur** [comment]
Hello, 
we are facing a similar issue, is there a solution to exclude pods from log gathering now?

**Comment by vishiy** [comment]
This has just started to be rolled out this week. I see the roll-out complete in AUS as of 8:00 AM PST 6/26/2019. All other Azure regions will be rolled out by the end of the week/beginning of next week.
The agent version that has this feature is ciprod06142019.

You can find the documentation here : https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-agent-config
