### ISSUE TITLE
Attaching of volume with a lot of inodes takes more than 1h

### ISSUE THREAD

**Issue by joggeli34** [Azure/AKS#2933]
**What happened**:

We restarted a pod on a new node during. This pod has a azure-disk attached with a size of 64GB.
The new container stayed in "containercreating" state for more than 1h and the event occurred multiple time:
```
Unable to attach or mount volumes: unmounted volumes=[storage], unattached volumes=[storage kube-api-access-5mdv5 tmp config]: timed out waiting for the condition
``` 
after about 1.5h, the container suddenly started without a problem.

Due to the fact, that we have another pod with a similar azure-disk of 64GB which didn't suffer from that delay, I assume that it could be related to the amount of inodes used on the disk.
The disk with the problem has arround 1.5M of inodes while the other only has a few hundreds.

Also on the other clusters we have, we notice that the disks with a lot of inodes are using along time to connect.

**What you expected to happen**:

The disk should connect in a reasonable a amount of time (max some minutes)

**How to reproduce it (as minimally and precisely as possible)**:

Create a stateful set with a disk and add a lot of inodes.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.23.5
- Size of cluster (how many worker nodes are in the cluster?):  3
- Availability zones: 3

**Comment by andyzhangx** [comment]
would you provide driver logs on the node for identifying the issue, follow by: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

**Comment by joggeli34** [comment]
[csi-azuredisk-node-hqmk9.log](https://github.com/Azure/AKS/files/8639146/csi-azuredisk-node-hqmk9.log)

I restarted the pod today at 08:06, then it took about 40min untill it was up and running again. So it is even reproducible when only recreating the pod on the same node.

**Comment by joggeli34** [comment]
yes, it is this disk "pvc-xxxxxxxx-4849-4ad7-ba09-79f87c8ac2d3". So the mount with the driver seems do be fast. But then somehow it took until 08:43 to begin with the start of the container. 
Does kubernetes somehow have to index the files on the disk and this is slow because it is only a Standard_SSD?

**Comment by andyzhangx** [comment]
> yes, it is this disk "pvc-xxxxxxxx-4849-4ad7-ba09-79f87c8ac2d3". So the mount with the driver seems do be fast. But then somehow it took until 08:43 to begin with the start of the container. Does kubernetes somehow have to index the files on the disk and this is slow because it is only a Standard_SSD?

@joggeli34 after mount, that's your pod application behavior, so it's slow after mount, some reference: https://serverfault.com/questions/735435/will-a-large-number-of-used-inodes-cause-a-server-to-run-slowly, I think you need to try Premium_SSD with a bigger size.

**Comment by joggeli34** [comment]
Actually, it takes this much time before it starts the container. So it is not inside our application logic. It is kubernetes that has the event `Unable to attach or mount volumes`.
I don't know why the attach has something to do with the amount of inodes on the disk.

**Comment by joggeli34** [comment]
Thanks a lot, this solved the problem for me.
