### ISSUE TITLE
AKS Node - Latest Image -  AKSUbuntu-1804gen2containerd-2022.04.19 - Vulnerabilities

### ISSUE THREAD

**Issue by zohebs341** [Azure/AKS#2941]
Hi Team,

This is w.r.t vulnerabilities in AKS Node Latest Image. We are using the Azure AKS 1.21.7 version with the latest Node image.

When we scanned AKS Nodes using Prisma Aqua & Sysdig tools, I noticed a lot of vulnerabilities with High/Medium/Low, etc.

How Microsoft will handle this use case? Microsoft should fix vulnerabilities for the packages which are having fixes available.

I've attached a report which is captured by using the Sysdig security product.
[aks-agentpool-19172867-vmss00004B_CHM_os_vulnerabilities_hasFix.csv](https://github.com/Azure/AKS/files/8653202/aks-agentpool-19172867-vmss00004B_CHM_os_vulnerabilities_hasFix.csv)

**Comment by CocoWang-wql** [comment]
"AKS patches CVE’s that have a vendor fix every week. The AKS images will get automatically updated inside of 30 days and it recommended that customer apply an updated Node Image on a regular cadence to ensure that latest patched images and OS patches are all applied and current."
For updating to latest image, please run   "_az aks update -g <> -n <> --node-image-only_" and then validate the CVE’s again. They should not be over 30 days old.”
Once a CVE is released by Ubuntu, AKS will consume the patch on the next VHD release.

**Comment by zohebs341** [comment]
@CocoWang-wql Thanks for your response. The reason behind raising this issue is, Vendor(Ubuntu) has already released fixes but in Azure AKS Latest Image those fixes are not available. Microsoft Security team has to look into it.

Again I am attaching an excel sheet that contains available fixes for Critical/High/Medium Vulnerabilities.

Request you to please go through the excel sheet.
[aks-agentpool-19172867-vmss00004B_CHM_os_vulnerabilities_hasFix.csv](https://github.com/Azure/AKS/files/8684145/aks-agentpool-19172867-vmss00004B_CHM_os_vulnerabilities_hasFix.csv)

**Comment by CocoWang-wql** [comment]
Let me take the first vulnerability as an example: package name: networkd-dispatcher; package version:1.7-0ubuntu3.3
It was fixed in the image version 2020.5.10
![image](https://user-images.githubusercontent.com/45681473/168221040-2230cb6c-f885-4b74-9092-17a66335892a.png)
https://github.com/Azure/AgentBaker/blob/master/vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2022.05.10.txt

So it's suggested to upgrade the node images once the desired version is releases by AKS.
For the released image version, pls feel free to refer the AKS release notes: 
https://github.com/Azure/AKS/releases

**Comment by zohebs341** [comment]
@CocoWang-wql Thank you. I will upgrade to the latest(this month)release and will keep you posted.

**Comment by zohebs341** [comment]
@CocoWang-wql It's not yet reflected in Azure Portal, as I've tried upgrading to the latest Image. I've attached screenshot FYR.

The node image is automatically updated when upgrading the node pool to a new Kubernetes version, but the node pool can be manually updated to the latest image outside of a Kubernetes version upgrade.[Learn more](https://go.microsoft.com/fwlink/?linkid=2167742)
Current version
AKSUbuntu-1804gen2containerd-2022.04.19
Latest version
AKSUbuntu-1804gen2containerd-2022.04.27

<img width="960" alt="image" src="https://user-images.githubusercontent.com/62261716/168234830-49d1d5e5-0e57-4609-8628-d4930f02cbbe.png">

**Comment by zohebs341** [comment]
Will upgrade to latest version and will scan again

**Comment by zohebs341** [comment]
@CocoWang-wql Latest Image(May release) not yet reflected in Azure Portal. Do we need to wait for a few days for this image - AKSUbuntu/gen1/1804/2022.05.10 ???

<img width="960" alt="image" src="https://user-images.githubusercontent.com/62261716/168239323-b67799cb-92fd-4d65-9e81-e2a1faca3446.png">

**Comment by CocoWang-wql** [comment]
2022.05.10 has not released by AKS yet. We may need to wait for more days.
Once the image is released, it would be contained in AKS release notes:
https://github.com/Azure/AKS/releases
