### ISSUE TITLE
pod-identity feature bug

### ISSUE THREAD

**Issue by alkarp** [Azure/AKS#2943]
**What happened**:

azure managed identity (name: app1-managed-identity) was deleted before the corresponding k8s pod-identity resource (app1-pod-identity). now when attempt to create **any** pod-identity associated to **any** unrelated azure managed identity get the following error message:

```
Operation failed with status: 'Bad Request'. Details: Cluster identity has no assignment permission over identity 'resourceId: /subscriptions/87be077a-ca98-471d-922f-6ff4e8dd799d/resourcegroups/rg-name/providers/Microsoft.ManagedIdentity/userAssignedIdentities/app1-managed-identity - clientId: 466925d4-fa53-482d-b925-b429dff9f77b - objectId: 012720c4-65d8-4239-8403-b8ae30d140fb'. Please grant
at least 'Managed Identity Operator' permission before assigning pod identity.
```

when attempt to delete the subject pod identity via az cli, it completes with no error. however when create a pod-identity with the same name:

`Operation failed with status: 'Bad Request'. Details: Found pod identities use different identities with the same name 'da-hercules-ohlcv-writer-pod-identity' in namespace 'data-analytics'. Please update the pod identity name.`

when query a list of pod-identities with az cli  `az aks pod-identity list` the identity is show as provisioning state failed:

```
 {
        'bindingSelector': null,
        'identity': {
          'clientId': '466925d4-fa53-482d-b925-b429dff9f77b',
          'objectId': '012720c4-65d8-4239-8403-b8ae30d140fb',
          'resourceId': '/subscriptions/87be077a-ca98-471d-922f-6ff4e8dd799d/resourcegroups/rg-name/providers/Microsoft.ManagedIdentity/userAssignedIdentities/app1-managed-identity'
        },
        'name': 'app1-pod-identity',
        'namespace': 'ns1',
        'provisioningInfo': null,
        'provisioningState': 'Failed'
      }
```

**What you expected to happen**:
pod-identity created

**How to reproduce it (as minimally and precisely as possible)**:
1. create managed identity
2. create pod-identity associated with the managed identity
3. delete managed identity
4. attempt to delete pod-identity or create a new one with a different name associated with a different managed identity

**Anything else we need to know?**:
the problem looks identical to #2203. tagging @bcho and @jotavar, hoping you guys can shed some light on how it was handled.
i have also got a support case open that did not yield a solution yet TrackingID#2205060050001624.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.22.6
- Size of cluster (how many worker nodes are in the cluster?): 25
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): mixed
- Others:

**Comment by bcho** [comment]
Hi,

could you try delete the failed pod identity first?

```
$ az pod-identity delete -n app1-managed-identity --cluster-name {clusterName} -g {resourceGroup} --subscription {subscriptionID}
```

**Comment by alkarp** [comment]
hi @bcho i've attempted to delete the original pod-identity. it takes a few minutes and completes with no errors. this doesn't change the described situation. the AzureIdentity and AzureIdentityBinding resources do not exist anymore, so can't update their client and object ids.

**Comment by bcho** [comment]
@alkarp do you mean you no longer see any pod identities with the name `app1-managed-identity` from the managed cluster properties (we can check with `az aks get -n {clusterName}`) ? And with that, you still unable to perform any update operations?

**Comment by alkarp** [comment]
@bcho the identity is shown in the `az aks show output` below, the provisioning state is Failed:

```
      {
        "bindingSelector": null,
        "identity": {
          "clientId": "466925d4-fa53-482d-b925-b429dff9f77b",
          "objectId": "012720c4-65d8-4239-8403-b8ae30d140fb",
          "resourceId": "/subscriptions/87be077a-ca98-471d-922f-6ff4e8dd799d/resourcegroups/rg-name/providers/Microsoft.ManagedIdentity/userAssignedIdentities/app1-managed-identity"
        },
        "name": "app1-pod-identity",
        "namespace": "data-analytics",
        "provisioningInfo": null,
        "provisioningState": "Failed"
      }
```

do you happen to have any records \ access to the case from the previously mentioned case? it looks very similar and potentially was cleared from the MS end?

**Comment by bcho** [comment]
Hi @alkarp could you file a support case from portal for your cluster? I can take a look with that in our end. I am not sure if it's the same issue as the one you mentioned.

**Comment by alkarp** [comment]
> And with that, you still unable to perform any update operations?

yes, that's correct. I've attempted to delete (there is no update operation in az cli), which spins for a few minutes and completes with no errors. I've attempted to create a new identity with a different name attached to a different managed identity, which fails with the error mentioned earlier.

**Comment by alkarp** [comment]
@bcho the case with MS is #2205060050001624.

**Comment by bcho** [comment]
Thanks for providing the case number. I will check in our end. In the meanwhile, could you please rerun the delete command with `--debug`:

```
$ az pod-identity delete -n app1-managed-identity --cluster-name {clusterName} -g {resourceGroup} --subscription {subscriptionID} --debug
```

And capture the output logs and send it to your support case? I need these information to help troubleshooting.

**Comment by alkarp** [comment]
@bcho thanks, it has been done on Mon, 9 May, 19:26 BST.

**Comment by bcho** [comment]
Hey @alkarp , I reviewed your support ticket internally, seems like your issue was due to other reasons. Let's follow up in that channel. I will close this issue for now. Let me know if you have any concerns.
