### ISSUE TITLE
az aks nodepool add no longer support --min-count 0

### ISSUE THREAD

**Issue by BartVB** [Azure/AKS#2946]
**What happened**:
I issued something like:

```shell
az aks nodepool add \
    --resource-group $AKS_GROUP \
    --cluster-name $AKS_NAME \
    --name appsv8 \
    --mode User \
    --min-count 0 \
    --node-vm-size Standard_D8as_v4 \
    --enable-cluster-autoscaler
```
Which resulted in this error:
`--min-count must be in the range [1,100]`

**What you expected to happen**:
New node pool which would scale to 0 depending on demand. That's what we have been using for months now.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.21.7
- `az-cli` version: 2.36.0

**Comment by seanslma** [comment]
I believe this limitation just does not make sense. 

The min node count should not be limited to the current node count.

Here is the info from the Web UI `Node Count Range` in the `scale node pool`:

Set the minimum and maximum node counts for this node pool. **You cannot set a lower minimum than the current node count in this node pool**. If you want to set a lower minimum node count, you will need to manually scale down the cluster first.

And this is the error when I use `update` with `--min-count 0`:
```
az aks nodepool update --resource-group <resource-group-name> --cluster-name <cluster-name> --name <nodepool-name> --enable-cluster-autoscaler --min-count 0 --max-count 8
The behavior of this command has been altered by the following extension: aks-preview
--min-count must be in the range [1,100]
```

**Comment by allyford** [comment]
Hi @BartVB,
"Every AKS cluster must contain at least one system node pool with at least one node" per our [AKS documentation.](https://learn.microsoft.com/en-us/azure/aks/use-system-pools?tabs=azure-cli) Scaling to zero nodepools is not supported which is why there is a minimum of 1 nodepool. 

If you'd like to stop the cluster, you can use [the az aks stop command.](https://learn.microsoft.com/en-us/azure/aks/start-stop-cluster?tabs=azure-cli)

**Comment by BartVB** [comment]
True, but I was creating a User nodepool, not a System nodepool.

AFAIK it should be possible to have a system nodepool with several nodes plus one or more empty user nodepools.
