### ISSUE TITLE
What happened to AKSUbuntu-1804gen2containerd-2022.04.19?

### ISSUE THREAD

**Issue by HarleyB123** [Azure/AKS#2947]
**What happened**:

I am looking at my node pool image version (`AKSUbuntu-1804gen2containerd-2022.04.19`) and comparing it to the Azure release notes, I can not see the image version in the release notes or in [this](https://github.com/Azure/AKS/tree/master/vhd-notes/aks-ubuntu/AKSUbuntu-1804) folder. Was the image version pulled or is there something I'm missing? 😄  

**What you expected to happen**:

Expect to see a file called `2022.04.19` in this repository [here](https://github.com/Azure/AKS/tree/master/vhd-notes/aks-ubuntu/AKSUbuntu-1804)

**Comment by CocoWang-wql** [comment]
Hello @HarleyB123, confirmed with our internal engineer, there was recently a bug that made it look like we had. It's recommended to upgrade your node images with the command: 
az aks update -g <> -n <> --node-image-only

**Comment by HarleyB123** [comment]
Good to know, thanks @CocoWang-wql !
