### ISSUE TITLE
Portal overview of Kubernetes services is missing certain fields

### ISSUE THREAD

**Issue by naioja** [Azure/AKS#2948]
**What happened**:
In the Portal view of the Kubernetes Service there's a filed missing stating the status of an AKS cluster started/running or stopped.
![image](https://user-images.githubusercontent.com/6505576/167825403-b0a03198-b9b7-47fd-bab2-13e5e79b86c6.png)

**What you expected to happen**:
For Virtual Machine we can have more detailed displayed information as shown below:
![image](https://user-images.githubusercontent.com/6505576/167825298-071a2b85-6b7a-4d8c-8f99-c26a04ca1393.png)

**How to reproduce it (as minimally and precisely as possible)**:
Just go to the Portal overview of the Kubernetes Services and compare the available fields to the same overview but for Virtual Machines.

**Comment by raghulmsft** [comment]
@naioja : Thanks for sharing this! I am a PM with the AKS portal team and will pass it on to see how we can surface additional information like VM does.

**Comment by naioja** [comment]
up

**Comment by shashankbarsin** [comment]
@raghulmsft, @chandraneel any updates on this?

**Comment by chandraneel** [comment]
We added a bunch of fields to the view, and we are not done. We are aware of status being one of the important columns and we are actively working on it. Hopefully will be resolved soon. 

![image](https://user-images.githubusercontent.com/5324911/216736838-544fc94a-5bbd-4fbc-afd1-5b6395c9c447.png)

**Comment by chandraneel** [comment]
There are lot of columns supported in the view now
![Image](https://github.com/user-attachments/assets/4775c693-39f9-42bf-a930-035516cffce1)
