### ISSUE TITLE
AKS should forbid user to delete the kubelet identity in use.

### ISSUE THREAD

**Issue by gsxmax** [Azure/AKS#2951]
**What happened**:
Deleted the Kubelet identity by mistake (agentpool MSI) and then ACR auth is failing because Kubelet identity is still pointing to the deleted MSI. We may need to upgrade the image of nodes or add a new nodepool to force refresh the Identity, if the node image is already the latest version and cluster do not support multiple nodepool, this mitigation would not work.

**What you expected to happen**:
Add checking logic to forbid user to delete the kubelet identity used by AKS cluster under MC resource group. 

**How to reproduce it (as minimally and precisely as possible)**:

- Integrate AKS with ACR
- Delete the Kubelet identity from portal or CLI(agent pool MSI from MC_ RG) 
- Run a reconcile recreated the identity.
- When pulling image from ACR we could still see the old identity. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Any version with MSI.

**Comment by CocoWang-wql** [comment]
Hello @gsxmax, we have a feature named "Node resource group lockdown"  which is in plan.  With that feature enabled, users would not deleted resources in MC resource group.
Meanwhile, it's recommended to leverage customized policy and prevent identity in MC group to be deleted.
