### ISSUE TITLE
Feature Request: Arc cluster peering with managed AKS cluster

### ISSUE THREAD

**Issue by colincmac** [Azure/AKS#2953]
### Feature Request

Enabling Azure Arc on an external cluster allows Azure management of the cluster, but does not support extending the external cluster into Azure cloud. It would be beneficial to integrate with a multi-cluster peering tool, such as [Liqo](https://doc.liqo.io/), to easily burst external K8s workloads into a managed AKS cluster. 

Arc is often used during cloud migrations, where there is existing on-prem infrastructure. Enabling Arc to natively peer with managed AKS would greatly reduce the effort of using and migrating on-prem workloads to the cloud. It could also use the existing connectivity that the Arc agents provide to enable more secure peering.

**Comment by raghulmsft** [comment]
@colincmac : Thanks for the feedback! I am a PM with AKS team and reached out to the Arc in AKS team for their feedback. Will keep you posted as we have updates.

**Comment by palma21** [comment]
+ @shashankbarsin

**Comment by colincmac** [comment]
If it helps, I have a demo of an AKS ARC cluster using an AKS Managed cluster as a LIQO virtual node and can demo it MSFT internally. @palma21 @shashankbarsin

**Comment by shashankbarsin** [comment]
Fleet provides way to schedule workloads across multiple clusters today. Don't have many upvotes on this ask as of now, so closing for now, open to revisiting this later if there are more asks for this.
