### ISSUE TITLE
 Security alert for k8s_tunnel-front_tunnelfront

### ISSUE THREAD

**Issue by danilina-wsib** [Azure/AKS#296]
Hi,

We installed a security monitoring solution on our AKS cluster, it it generated several security alerts like this:
Container name: k8s_tunnel-front_tunnelfront-5bdc8f9bb8-pdlw9_kube-system_93fc9a11-3a96-11e8-9b03-0a58ac1f0e9c_0
Actions
No actions performed
Details
File below /etc opened for writing (user=root command=cp /tmp/tunnel_end/publicKey /etc/authorized_keys/apiserver parent=run-tunnel-fron pcmdline=run-tunnel-fron /lib/tunnel-front/run-tunnel-front.sh file=/etc/authorized_keys/apiserver program=cp gparent=<NA> ggparent=<NA> gggparent=<NA>)

This looks like an AKS rotating k8s API keys. Can someone from AKS confirm this?

Thank you,
Alexei Daniline

**Comment by rite2nikhil** [comment]
Yes that is correct, the keys get rotated
