### ISSUE TITLE
AKS doing contributor role assignment

### ISSUE THREAD

**Issue by AmudaPalani** [Azure/AKS#2961]
In my tenant, I have a policy blocking role assignment of contributor role. When I create an AKS cluster from Azure portal, AKS is trying to do a contributor role assignment and that conflicts with policy and i am getting an error. Why is AKS trying to do a contributor role assignment? What resource is it trying to assign contributor role?

**Comment by zweckj** [comment]
That's probably the role assignment to AKS's service principal. That SP get Contributor on the node resource group to be able to create the required resources (VMSSs, Load Balancers, IPs, Disks).

**Comment by ChrisRomp** [comment]
I'm working with @AmudaPalani and confirmed that AKS is assigning its managed identity the Contributor role to the Resource Group for the node pool VM Scale Set. I've asked if their org is able to grant a policy exception here, otherwise we will try to find some workaround.
