### ISSUE TITLE
EnableOIDCIssuerPreview feature flag to be recommend for production use

### ISSUE THREAD

**Issue by prmahajan** [Azure/AKS#2969]
My team is planning to use Azure AD Workload Identity which requires to register the EnableOIDCIssuerPreview feature flag. This feature is in preview and not recommended for production. 

Can you please provide some tentative timeline for the flag to be recommended for production?

**Comment by CocoWang-wql** [comment]
Hello @prmahajan, the tentative GA time for Workload identity is the end of this year. Neither public preview nor preview preview are recommended for production environment.
