### ISSUE TITLE
K8s 1.24 upstream changes to beta APIs

### ISSUE THREAD

**Issue by qpetraroia** [Azure/AKS#2970]
### Hello everyone,

This is an announcement stating how AKS will handle the new upstream changes to beta APIs in K8s 1.24

**We will keep the existing behavior of having beta APIs turned on by default, there is no action needed from you**. While AKS does follow upstream behavior, we believe that beta APIs are fundamental to exploration of the Kubernetes landscape. AKS is a place for developers to try all types of feature gates as there is not a single solution that fits everyone's needs. If you have any questions or concerns, please feel free to drop a question below and we will respond as soon as possible.

Thanks,
Azure Kubernetes Service

**Comment by rouke-broersma** [comment]
@raghulmsft from a customer perspective I would expect that AKS follows the beta APIs from upstream AKS and thus I would expect to find the beta APIs on the kubernetes docs. At most I would expect a page for AKS which links through to the kubernetes docs, not a carbon copy of the docs that might/will run outdated.
