### ISSUE TITLE
Pods with PVCs stuck at PodInitializing indefinitely with errors in the events

### ISSUE THREAD

**Issue by tspearconquest** [Azure/AKS#2971]
**What happened**:
Redeployed Prometheus. Our Prometheus instance has a PVC for its db
The instance would not come up.
It was like [this](https://github.com/Azure/AKS/issues/1663)

**What you expected to happen**:
PVC attach to the node and Prometheus start

**How to reproduce it (as minimally and precisely as possible)**:
Restart the prometheus pod

**Anything else we need to know?**: kube-prometheus-stack is what our prometheus deployment is based off of

**Environment**:
- Kubernetes version (use `kubectl version`): v1.22.6
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) prometheus, opa gatekeeper, fluentd .... This is our monitoring cluster so it doesn't run much.
- Others:

**Comment by andyzhangx** [comment]
what's the pvc volume type and config? pls provide more details about pod events.

**Comment by tspearconquest** [comment]
Good morning.

This had affected our monitoring cluster which is 2 nodes and its primary purpose is to run Prometheus, Grafana, and Thanos.

We have a PVC on Grafana and a PVC on Prometheus, and 2 PVCs for different parts of the Thanos stack. This only affected the PVC for our Prometheus pod.

Fixed last night by taking the following steps:
- Scale the statefulset to 0 or delete the Prometheus statefulset
- Set the PV reclaim policy to `Retain` for the affected PV
- Output the `yaml` of the PVC and PV to a file
- Delete the PVC and PV with kubectl. The underlying managed disk is retained even though the PV is deleted from the cluster.
- Reapply of PV and PVC resources again by kubectl from the backups taken earlier
- Reboot the nodes
- Scale up the statefulset to 1 or redeploy it

After I did all steps above, the Prometheus pod started again without any issues.

Since the pod is running now for several hours, I don't have the events to share anymore because we don't yet have the Log Analytics setup.

PV YAML:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/migrated-to: disk.csi.azure.com
    pv.kubernetes.io/provisioned-by: kubernetes.io/azure-disk
    volumehelper.VolumeDynamicallyCreatedByKey: azure-disk-dynamic-provisioner
  creationTimestamp: "2022-05-20T01:21:07Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/disk-csi-azure-com
  labels:
    failure-domain.beta.kubernetes.io/region: eastus2
  name: pvc-b666160f-826d-4a3a-81d8-c11641403a11
spec:
  accessModes:
  - ReadWriteOnce
  azureDisk:
    cachingMode: ReadOnly
    diskName: kubernetes-dynamic-pvc-b666160f-826d-4a3a-81d8-c11641403a11
    diskURI: /subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-b666160f-826d-4a3a-81d8-c11641403a11
    fsType: ""
    kind: Managed
    readOnly: false
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: prometheus-thanos-deploy-kube-prometh-prometheus-db-prometheus-thanos-deploy-kube-prometh-prometheus-0
    namespace: mon
    resourceVersion: "145468475"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - eastus2
  persistentVolumeReclaimPolicy: Delete
  storageClassName: managed-premium
  volumeMode: Filesystem
status:
  phase: Bound
```

PVC YAML:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2022-05-20T01:22:24Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: prometheus-thanos-deploy-kube-prometh-prometheus-db-prometheus-thanos-deploy-kube-prometh-prometheus-0
  namespace: mon
  resourceVersion: "145468757"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-premium
  volumeMode: Filesystem
  volumeName: pvc-b666160f-826d-4a3a-81d8-c11641403a11
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
```

**Comment by andyzhangx** [comment]
I just checked the controller logs, disk attach/detach work well, it could be due to slow disk mount. 
Does you disk pv has lots of files? if yes, set `fsGroupChangePolicy: "OnRootMismatch"` in pod `securityContext` may solve the issue, details: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods

Pls also provide both azure disk driver logs (follow guide [here](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed)) and the kubelet logs on that agent node for RCA.

**Comment by tspearconquest** [comment]
Thanks for checking.

We rebooted the node and did an image upgrade, so the pod logs from the csi driver pods dont have any info related anymore in my view and I think it won't be able to be found at this point anymore.

The PV has only 34 files:
```
$ kubectl exec -it po/prometheus-thanos-deploy-kube-prometh-prometheus-0 -n mon -c prometheus -- /bin/find /prometheus
/prometheus
/prometheus/01G3KB829QA91PVJD37CPE3KRR
/prometheus/01G3KB829QA91PVJD37CPE3KRR/index
/prometheus/01G3KB829QA91PVJD37CPE3KRR/meta.json
/prometheus/01G3KB829QA91PVJD37CPE3KRR/tombstones
/prometheus/01G3KB829QA91PVJD37CPE3KRR/chunks
/prometheus/01G3KB829QA91PVJD37CPE3KRR/chunks/000001
/prometheus/queries.active
/prometheus/thanos.shipper.json
/prometheus/chunks_head
/prometheus/chunks_head/000797
/prometheus/chunks_head/000796
/prometheus/01G3KRZGSV615HJK844T0QPGA5
/prometheus/01G3KRZGSV615HJK844T0QPGA5/index
/prometheus/01G3KRZGSV615HJK844T0QPGA5/meta.json
/prometheus/01G3KRZGSV615HJK844T0QPGA5/tombstones
/prometheus/01G3KRZGSV615HJK844T0QPGA5/chunks
/prometheus/01G3KRZGSV615HJK844T0QPGA5/chunks/000001
/prometheus/lock
/prometheus/01G3KJ3SHYCZNG65THBX295CJM
/prometheus/01G3KJ3SHYCZNG65THBX295CJM/index
/prometheus/01G3KJ3SHYCZNG65THBX295CJM/meta.json
/prometheus/01G3KJ3SHYCZNG65THBX295CJM/tombstones
/prometheus/01G3KJ3SHYCZNG65THBX295CJM/chunks
/prometheus/01G3KJ3SHYCZNG65THBX295CJM/chunks/000001
/prometheus/thanos
/prometheus/thanos/upload
/prometheus/wal
/prometheus/wal/checkpoint.00005956
/prometheus/wal/checkpoint.00005956/00000000
/prometheus/wal/00005959
/prometheus/wal/00005957
/prometheus/wal/00005960
/prometheus/wal/00005958
```

**Comment by andyzhangx** [comment]
then it's not the large file num issue, I will close this issue, and pls provide logs if repro, thanks.
