### ISSUE TITLE
azure-keyvault-secrets-provider addon CPU throttling

### ISSUE THREAD

**Issue by jemag** [Azure/AKS#2972]
**What happened**:

Containers `node-driver-registrar` from  `aks-secrets-store-csi-driver` daemonset often has its CPU throttled.

Throttling evaluated with: 
```promql
[sum by(container, pod, namespace) (increase(container_cpu_cfs_throttled_periods_total{container!=""}[5m])) / sum by(container, pod, namespace) (increase(container_cpu_cfs_periods_total[5m])) > (25 / 100)]
```
**What you expected to happen**:

Rare CPU throttling

**How to reproduce it (as minimally and precisely as possible)**:
Run azure-keyvault-secrets-provider addon on AKS 1.22.4. with nodes `Standard_DS3_v2`

**Anything else we need to know?**:

It seems currently the CPU limit set for that container is only 100m. Is there any particular reason for having such a low CPU limit?

If not, is there a possiblity to either:
Increase the CPU limit 
or 
Allow users to modify it

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.4
- Size of cluster (how many worker nodes are in the cluster?) 13
- General description of workloads in the cluster : mostly java applications

**Comment by ZeroMagic** [comment]
@jemag  100m is enough for many scenarios. If you need more quota, please ask support to contact us. We need your subscription and cluster information to increase the quota.

**Comment by jemag** [comment]
I mainly created the issue because I thought others might benefit from it, given that low CPU limits often result in throttling without much advantages. If you believe that it is not somewhat common for other clients then feel free to close the issue.

It would not be practical to ask support to increase the CPU limit of a single container every time we create a cluster. At this point, it would probably make more sense to just go back to the helm chart and remove the addon.

**Comment by ZeroMagic** [comment]
How many CPU limits do you use now in the helm chart scenario?

**Comment by apaarshrm39** [comment]
These secrets-store-csi provider throttling errors were the reason why I silenced the cpu throttling alert in alertmanager totally.

**Comment by ZeroMagic** [comment]
@jemag @apaarshrm39 
There were some lessons from other CSI Drivers. It was hard to find a reasonable value for node-driver-registrar. So after the assessment, we decide to remove the CPU limit. The new change will be contained in the next release.

**Comment by djsly** [comment]
THANKS !!!
