### ISSUE TITLE
Should we enable company's network ip range via AKS authorized range or network security group?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/AKS#2974]
Team,

We need to allow only our organization's ip range to access our AKS environment. Should we use "AKS authorized ranges feature" or "network security group inbound security rule".

We want to disable our AKS environment's accessibility over public internet.

Please suggest. Thank you.

Regards,
Tanul

**Comment by CocoWang-wql** [comment]
Hello @smartaquarius10, the NSG(net work security group) and authorized IP range are different fuctions. Authorized IP range is used for restricting traffic to API server, while NSG is used to limit the traffic to AKS subnet(worker nodes, applications running on the aks node.). It depeneds on which function you need. Meanwhile, once you set the NSG or authorized IP range, pls allowlist all the IP range which would connect to the AKS subnet or API server.

[AKS authorized IP range](https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges)
[AKS NSG](https://docs.microsoft.com/en-us/azure/aks/concepts-network#network-security-groups)
