### ISSUE TITLE
Slow AKS Creation and Deletion - Averages over 30 Min for simple setups

### ISSUE THREAD

**Issue by byteknacker** [Azure/AKS#2980]
I am using the newest version of AKS and Kubernetes inside. It takes now over 34 minutes to set up one AKS cluster using Terraform. 

Terraform Code for AKS:

  default_node_pool {
    name                = "akspool${var.tag_environment}"
    node_count          = 3
    max_count           = 15
    min_count           = 2
    vm_size             = "Standard_D4s_v3"
    os_disk_size_gb     = 100
    enable_auto_scaling = true
    vnet_subnet_id      = module.vnet_aks_spoke.vnet_subnets[0]
  }

As you can see, it is not a large cluster for the default node pool size. Is it possible to increase the speed of spin up and down of an AKS cluster? It makes my development cycle vastly slower with this.

**Comment by byteknacker** [comment]
I just reapplied the very same Terraform code with the creation of an AKS today and it went through within 8 minutes. I conclude that this is a flaky behaviour and may have resulted from Azure platform-dependent availability/stability issues. As this can affect our production apps, I would like to stress the importance of AKS being stable when you continuously delete and recreate it.

**Comment by byteknacker** [comment]
Just a heads up, I think this was a temporary AKS availability issue on the platform level. Now, I do not have this problem. However, if that appears randomly again, it can be a problem for us.

**Comment by TeamDman** [comment]
Can confirm, deletion took 6m30s, still waiting on creation 23m50s later...

**Comment by byteknacker** [comment]
It sometimes happens, this kind of slow creation and deletion. I am guessing it is another platform issue or availability issue on Azure and has nothing to do with our TF code.

**Comment by flavio-neves** [comment]
Only 30 minutes?

Here, creation takes more than 2h.

![image](https://user-images.githubusercontent.com/35963484/191265429-cfa66922-5bf3-4425-8d46-e8bf8ec7db5e.png)

AzureRM version 3,23

**Comment by flavio-neves** [comment]
Same logic, but over CLI, takes less than 20 minutes.

**Comment by TeamDman** [comment]
Pretty sure this is still relevant.

**Comment by pierluca** [comment]
We're observing the same thing over the past few days. The exact same Terraform code that used to provision AKS in a matter of minutes now takes hours and sometimes the creation outright fails.

**Comment by TeamDman** [comment]
Will be creating more clusters in the near future, will comment back with my observations

**Comment by R3DRUN3** [comment]
The same thing randomly happens to me as well.
Today creation is exceeding 40 minutes !!

*Kubernetes version*: **1.24.6**
*Region*: **westeurope**
*Node sizes*: **Standard_D4s_v3**
*Node number*: **3**

Of course this is a big problem...never experienced something like this with other public cloud providers.

**Comment by vinicius-r-rosa** [comment]
Created a first cluster using Terraform and it was pretty fast. Created a second one and took exact 35 minutes: "azurerm_kubernetes_cluster.default: Creation complete after 35m47s"
