### ISSUE TITLE
az aks command invoke uses Helm 3.5.4 and fails for compiled charts past Helm 3.7.0

### ISSUE THREAD

**Issue by Greigg** [Azure/AKS#2981]
**What happened**:
Installing a chart using az aks command invoke does not work when the chart is compiled with helm using a version greater than 3.7.0. This is because the helm has changed their mediatype from application/tar+gz to application/vnd.cncf.helm.chart.content.v1.tar+gzip.

**What you expected to happen**:
The chart to be installed.

**How to reproduce it (as minimally and precisely as possible)**:
Compile a chart using a version of helm greater than 3.7.0, then using az aks command invoke try to install the chart.

**Anything else we need to know?**:
Upgrading to latest version of AKS does not solve the problem.
https://github.com/helm/helm/issues/10176 this is the link for the fix of helm.

**Comment by squillace** [comment]
yep, we should be able to. Lessee what we can do. @palma21 you have thotz?

**Comment by nreisbeck** [comment]
It appears that the `helm version` has been updated to `v3.9.2`

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/10735102/199074395-a964c056-d29e-432c-a151-03e3e8561645.png">

But somewhat more concerning is that the `kubectl` version isn't being upgraded and is generating version skew warnings.

AKS Version: `v1.24.6`

**Comment by qpetraroia** [comment]
Hi @Greigg and @nreisbeck,

We are looking into this and will be shipping a fix soon.

Thanks,
Quentin

**Comment by nreisbeck** [comment]
> Hi @Greigg and @nreisbeck,
> 
> We are looking into this and will be shipping a fix soon.
> 
> Thanks,
> Quentin

Thanks for the update @qpetraroia

**Comment by qpetraroia** [comment]
Hi @Greigg and @nreisbeck,

The fix is now out. Can you give it a try? 

Thanks
