### ISSUE TITLE
Upgrade Groups

### ISSUE THREAD

**Issue by kaarthis** [Azure/AKS#2984]
Why?
Need the ability to inject dependencies by environment when rolling upgrades to cluster , esp for Auto Upgrades. 

Customers will be able to choose environment and link them by a dependency model with this feature and more importantly group clusters together by upgrade channel & env.

**Comment by jvargh** [comment]
1. Upgrade groups should have a workflow mechanism for 3rd party components 
- Looking for a pre-, post- hook mechanism to inject custom steps for 3rd party install/upgrade 
- Compare to Cloud Services which has a bootstrapping mechanism to install 3rd party components 
- Async mechanism to run applications that return pass/fail to move on 

2. Upgrade groups should be able to specify clusters by subscription, region, cluster name 

3. Upgrade groups should have selection rules. For e.g., select all clusters in subscription, OR all clusters in eastus sub OR certain clusters in eastus, that allow independent selection to make it a group 

4. Upgrade schedule based on planned maintenance  
- can be controlled by calendar selection of day/time/timezones 
- should be unique for each Upgrade group 

5. Upgrade groups should be able to go in a sequence  
- Should be based on dependencies so clusters in groupA go before clusters in groupB 
- If groupA is not done then groupB should not happen e.g., check if groupA is on 1.22 then start groupB 
- allow pause on groupA to validate application before starting groupB

**Comment by jvargh-msft** [comment]
1. Upgrade groups should have a workflow mechanism for 3rd party components 
- Looking for a pre-, post- hook mechanism to inject custom steps for 3rd party install/upgrade 
- Compare to Cloud Services which has a bootstrapping mechanism to install 3rd party components 
- Async mechanism to run applications that return pass/fail to move on 

2. Upgrade groups should be able to specify clusters by subscription, region, cluster name 

3. Upgrade groups should have selection rules. For e.g., select all clusters in subscription, OR all clusters in eastus sub OR certain clusters in eastus, that allow independent selection to make it a group 

4. Upgrade schedule based on planned maintenance  
- can be controlled by calendar selection of day/time/timezones 
- should be unique for each Upgrade group 

5. Upgrade groups should be able to go in a sequence  
- Should be based on dependencies so clusters in groupA go before clusters in groupB 
- If groupA is not done then groupB should not happen e.g., check if groupA is on 1.22 then start groupB 
- allow pause on groupA to validate application before starting groupB

**Comment by kaarthis** [comment]
What third party components are you referering pls elaborate @jvargh-msft with usecases

**Comment by jvargh** [comment]
@kaarthis 3rd party tools as Velero and Dynatrace primarily
User case: When new 3rd party installers available and need to be installed post-AKS upgrade then the workflow should account for this activity

**Comment by havronl** [comment]
The goal is to replicate something like Cloud Services Bootstrapper where the customer can install 3rd party apps or make adjustments through automation to all clusters.   As mentioned above right now it is to install DynaTrace or maybe even splunk for example.  The bootstrapper follows this config through installs and upgrades.  Having this service makes upgrades transparent for all config and any apps installed in the base cluster

**Comment by siegenthalerroger** [comment]
Honestly I need this feature just for the ability to ensure that certain clusters are guaranteed to have the updates applied before some other cluster (QA before Production).

**Comment by kaarthis** [comment]
This is actively being worked on by the PG.

**Comment by wasker** [comment]
@kaarthis Will this work across Azure tenants? We have test in one tenant and staging/prod in another tenant for compliance reasons.

**Comment by kaarthis** [comment]
@shashankbarsin to comment on above.

**Comment by siegenthalerroger** [comment]
This is still relevant
