### ISSUE TITLE
Upgrade with Metrics

### ISSUE THREAD

**Issue by kaarthis** [Azure/AKS#2985]
Help choose key metrics to preserve or guarantee when hitting upgrade eg: Pod health i.e No. of Pods, other SLOs for Pod etc.

**Comment by austonli** [comment]
Hi @kaarthis , can you please clarify which metrics you are referring to when discussing the upgrade?

**Comment by kaarthis** [comment]
We decided to deprioritize this in favor of Blue green nodepool upgrades at the start.

**Comment by kaarthis** [comment]
This has put back to roadmap and the team is actively planning and discussing details like API, proposals etc

**Comment by swgriffith** [comment]
Work is now in progress on the initial phase of this capability.
