### ISSUE TITLE
[Question] which cluster-autoscaler version is AKS using?

### ISSUE THREAD

**Issue by NissesSenap** [Azure/AKS#2990]
Having issues with the cluster-autoscaler and trying to open an issue upstream.
But I'm unable to provide them with the version since I can't see which version I'm using.

I guess one way could be to look through the logs but It would be nice to see in the portal or at least the documentation.

But for now using kubernetes 1.22 which version of the cluster-autoscaler is in use?

**Comment by NissesSenap** [comment]
Relates to: https://github.com/kubernetes/autoscaler/issues/4923

**Comment by raghulmsft** [comment]
@NissesSenap Thanks for sharing this with us. I am a PM with the AKS portal team and will look into this and get back to you!

**Comment by gandhipr** [comment]
Pertaining to CA logs - currently, we don't print Cluster Autoscaler version in CA logs. Thanks for sharing and we'll add the CA version log line.

**Comment by NissesSenap** [comment]
Just a thought it's probably not worth having on each row @gandhipr. I think documenting a query that can be used to gather the version would be a good workaround after you have added the version at the initial startup.

**Comment by gandhipr** [comment]
Planning on getting one at the start-up, not for all the rows.
using some sort of string matching will help us getting the version.

**Comment by palma21** [comment]
Seems we're diverging a bit from the actual issue though, if you have any issues with the AKS-managed autoscaler you can just open a support ticket and we'll take it from there. 
Having it done in upstream won't automatically fix it in AKS for example.

**Comment by NissesSenap** [comment]
@palma21 the upstream issue is already solved. But it's a good thing showing the version of the auto scaler no matter what. That is why I created two issues. 
The other issues are linked to this issue as well. You will see that if you look at the history of this issue.
