### ISSUE TITLE
revoke client token prior to azure AAD integration

### ISSUE THREAD

**Issue by agarwalarjun123** [Azure/AKS#2992]
how can we revoke client token prior to azure AAD integration? for eg. if an employee leaves the organization removing the role does not invalidate the client credentials in .kube/config.

**Comment by rouke-broersma** [comment]
@agarwalarjun123 you need to rotate your cluster certificates to revoke client credentials if you're not using azure ad integration: https://docs.microsoft.com/en-us/azure/aks/certificate-rotation

Note that this causes your cluster to be unavailable for 15-30 minutes.

**Comment by agarwalarjun123** [comment]
@rouke-broersma  will it revoke only user client credentials or all types of service principals granted access over the resource.

**Comment by rouke-broersma** [comment]
It rotates the kubernetes cluster CA so it invalidates any client credentials created from the cluster CA (eg kubectl client certificate but also kubelet certificate for node <-> API server communication).

What kind of service principals are you talking about?

**Comment by agarwalarjun123** [comment]
I am talking about azure active directory service principals, will those keep working or do we need to refresh credentials for those as well?

**Comment by rouke-broersma** [comment]
Those are not related to aks so there's not reason they would use client credentials generated from the aks cluster ca.
