### ISSUE TITLE
[Question] Microsoft.Network/PublicIPAddresses depency on private clusters

### ISSUE THREAD

**Issue by rogerfn** [Azure/AKS#2993]
Trying to create a private AKS cluster using the following

```
az aks create \
    --resource-group ResourceGroupName \
    --name AKSName \
    --node-count 1 \
    --enable-private-cluster \
    --network-plugin kubenet \
    --network-policy calico \
    --service-cidr 10.0.240.0/20 \
    --dns-service-ip 10.0.240.10 \
    --pod-cidr 10.111.240.0/20 \
    --docker-bridge-address 172.199.240.1/20 \
    --vnet-subnet-id $SUBNET_ID \
    --service-principal service-principal-id \
    --client-secret cleint-secret
```
My company has a NoPublicIP policy in place and when I execute that command I get

`(ReconcileStandardLoadBalancerError) Resource request failed due to RequestDisallowedByPolicy. Please see https://aka.ms/aks-requestdisallowedbypolicy for more details. The detailed error message: outboundReconciler retry failed: Category: ClientError; Code: Unspecified; SubCode: RequestDisallowedByPolicy; Message: ; InnerMessage: ; Dependency: Microsoft.Network/PublicIPAddresses; OrginalError: Code="RequestDisallowedByPolicy" Message="Resource '3948f47b-56e2-4068-928b-3bf7163110fd' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"NoPublicIP\",\"id\":\"/providers/Microsoft.Management/managementGroups/Sasol-Root-Group/providers/Microsoft.Authorization/policyAssignments/065da12054304761a0b0f416\"},\"policyDefinition\":{\"name\":\"NoPublicIP\",\"id\":\"/providers/Microsoft.Management/managementGroups/Sasol-Root-Group/providers/Microsoft.Authorization/policyDefinitions/cc084c3f-f72b-41dc-992c-772f05644310\"}}]'." Target="3948f47b-56e2-4068-928b-3bf7163110fd" AdditionalInfo=[{"info":{"evaluationDetails":{"evaluatedExpressions":[]},"policyAssignmentDisplayName":"NoPublicIP","policyAssignmentId":"/providers/Microsoft.Management/managementGroups/Sasol-Root-Group/providers/Microsoft.Authorization/policyAssignments/065da12054304761a0b0f416","policyAssignmentName":"065da12054304761a0b0f416","policyAssignmentScope":"/providers/Microsoft.Management/managementGroups/Sasol-Root-Group","policyDefinitionDisplayName":"NoPublicIP","policyDefinitionEffect":"deny","policyDefinitionId":"/providers/Microsoft.Management/managementGroups/Sasol-Root-Group/providers/Microsoft.Authorization/policyDefinitions/cc084c3f-f72b-41dc-992c-772f05644310","policyDefinitionName":"cc084c3f-f72b-41dc-992c-772f05644310"},"type":"PolicyViolation"}]; AKSTeam: Networking, Retriable: false
Code: ReconcileStandardLoadBalancerError`

Does it make sense that the creation has a dependency Microsoft.Network/PublicIPAddresses even if I ask for a private cluster? any work arounds?

Cheers

**Comment by joaguas** [comment]
Hi @rogerfn ,

The 'private' in private cluster refers to the cluster's API which is exposed via a private ip on the vnet/subnet of your choice versus being exposed over a public ip in 'regular' clusters.

All AKS clusters (private or not) still require internet access for several purposes (pulling images for core/system pods, installing components, etc.); the way this internet access is done by default is by creating a Standard Load Balancer and a public IP which will serve as the internet-bound egress path of the worker nodes.

You can choose to provide your own internet routing capabilities (ie: route the traffic through your firewall for instance) and that load balancer and public ip would not be provisioned. This is referred to as User Defined Routing and is one of AKS's outbound types (loadbalancer is the default one) - just remember you need to ensure your firewall/appliance/etc. allows internet access for AKS requirements.

user defined routing (UDR): https://docs.microsoft.com/en-us/azure/aks/egress-outboundtype 
AKS traffic requirements/restrictions and an example of UDR+Azure Firewall: https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic
