### ISSUE TITLE
[feature request] enable OverProvisioning for AKS

### ISSUE THREAD

**Issue by ririal** [Azure/AKS#2994]
"OverProvisioning" of VMSS as AKS worker node is false.

$ az vmss show --name aks-agentpool-xxxxxxxx-vmss --resource-group MC_XXXX | grep -i overprovision
"doNotRunExtensionsOnOverprovisionedVMs": false,
"overprovision": false,

https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-design-overview#overprovisioning

Please consider enabling this parameter to improve the nodepool creation, 
because it sometime takes a long time to create the node when occurring the instance trouble.

**Comment by CocoWang-wql** [comment]
Hello @ririal, do you consider this upstream auto-scaler overprovisioning feature?
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler

**Comment by ririal** [comment]
Thank you for giving me this information.
Can this be used for AKS?

Also, default setting of overprovisioning is true on Azure Scale sets.
But, it of AKS scale set is purposely false, so I hope it sets true.

https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-design-overview#overprovisioning
---
Scale sets currently default to "overprovisioning" VMs.
---

**Comment by CocoWang-wql** [comment]
Hello @ririal , currently AKS does not support this feature. We are looking into this part and will update in AKS roadmap if the featue is in plan.

**Comment by ririal** [comment]
Hello @CocoWang-wql ,I appreciate your help.
