### ISSUE TITLE
Does microsoft managed namespace "gatekeeper-system" cause high log analytics traffic and therefore costs?

### ISSUE THREAD

**Issue by ipg-informatik** [Azure/AKS#2995]
We have already tried to clarify the case with three azure tickets. Unfortunately without a satisfactory answer. Therefore we try it over this way.

We have multiple aks clusters with enabled azure monitor. Also we have the azure policy add-on enabled. We were wondering about the high log analytics traffic and then checked what was causing this traffic. With the workbook "data usage" (aks cluster - insights - workbook "data usage" - by namespace) we saw that the most traffic was caused by the namespace "gatekeeper-system". This namespace is managed by microsoft and is used for azure policy. Microsoft has confirmed that the exclusion [1] of the namespace "gatekeeper-system" does not affect the azure policies. It's used only for the pod logs. 

So far so good, but we are surprised that microsoft simply stores their own logs on the customer's log analytics workspace and thus causes them high costs. We found no reference in the documentation that the microsoft namespace 'gatekeeper-system' is not excluded by default.

- Can you confirm the facts?
- Can you confirm that these logs are charged to the customer?
- What is microsofts position on the customer having to pay for microsofts own logs?

[1] https://docs.microsoft.com/en-gb/azure/azure-monitor/containers/container-insights-agent-config 

Regards

**Comment by ritazh** [comment]
The gatekeeper pod logs could be useful to users if they want to see detailed violation information. @robbiezhang do you recall what was the rationale to not exclude gatekeeper logs by default? Do we want users to opt-in for more logs instead of opt-out to exclude? @miwithro thoughts?

**Comment by ipg-informatik** [comment]
Hi @ritazh, Your suggestion with the opt-in for extended logs would be good. Depending on the cluster, the gatekeeper logs cause up to 90% of the total log volume for us. Regards

**Comment by robbiezhang** [comment]
As I know, the Azure monitor doesn't exclude any logs from any namespace on AKS. @ganga1980 to correct me if I'm wrong.

Ganga, is there a doc about how to configure the log collection settings on AKS?
https://docs.microsoft.com/en-gb/azure/azure-monitor/containers/container-insights-agent-config

**Comment by saaror** [comment]
So by default AzMon exclude kube-system namespace. We should also exclude "gatekeeper-system". But for now you can exclude "gatekeeper-system" via config-map as documented here. https://docs.microsoft.com/en-gb/azure/azure-monitor/containers/container-insights-agent-config

**Comment by vdiec** [comment]
Hi @ipg-informatik , we are working on this, and it's expected to be available by the end of October. I'll ping here with more details once it's available.

**Comment by vdiec** [comment]
Hi @ipg-informatik , this fix has been rolled out. You can see more details in our release notes https://github.com/microsoft/Docker-Provider/blob/ci_prod/ReleaseNotes.md#10052022--
