### ISSUE TITLE
How to downgrade azure k8s version?

### ISSUE THREAD

**Issue by andyafene** [Azure/AKS#2997]
Currently I'm using aks and on version 1.23 Kubernetes has and I'd like to downgrade it to 1.21.
How can I do it ? Please

**Comment by andbaraks** [comment]
Hello @andyafene! 

As per https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#faq "Downgrades are not supported."

The suggestions we can give are:
-recreate the AKS cluster with the desired Kubernetes version

-create a new node pool with another Kubernetes version, but the control plane will still be in 1.23 Kubernetes version.

I hope you will find this helpful.
