### ISSUE TITLE
An additional resource group is created when deploying AKS

### ISSUE THREAD

**Issue by OguzPastirmaci** [Azure/AKS#3]
When deploying an AKS cluster, an additional resource group is created.

The resource group that I created and deployed AKS to:

```
az resource list -g oguzp-aks
Name       ResourceGroup    Location    Type                                        Status
---------  ---------------  ----------  ------------------------------------------  --------
oguzp-aks  oguzp-aks        westus2     Microsoft.ContainerService/managedClusters
```

The resource group that was created automatically:

```
az resource list -g MC_oguzp-aks_oguzp-aks_westus2
Name                                                                 ResourceGroup                   Location    Type                                          Status
-------------------------------------------------------------------  ------------------------------  ----------  --------------------------------------------  --------
agentpool1-availabilitySet-14710316                                  MC_oguzp-aks_oguzp-aks_westus2  westus2     Microsoft.Compute/availabilitySets
aks-agentpool1-14710316-0_OsDisk_1_fff6a42716dd4dc0a1032afc1cb67091  MC_OGUZP-AKS_OGUZP-AKS_WESTUS2  westus2     Microsoft.Compute/disks
aks-agentpool1-14710316-1_OsDisk_1_ff41571a0143470bbfc3b62653df5c2c  MC_OGUZP-AKS_OGUZP-AKS_WESTUS2  westus2     Microsoft.Compute/disks
aks-agentpool1-14710316-2_OsDisk_1_eec530dff34d4bdf80bbac8e74f5e07d  MC_OGUZP-AKS_OGUZP-AKS_WESTUS2  westus2     Microsoft.Compute/disks
aks-agentpool1-14710316-0                                            MC_oguzp-aks_oguzp-aks_westus2  westus2     Microsoft.Compute/virtualMachines
aks-agentpool1-14710316-0/cse0                                       MC_oguzp-aks_oguzp-aks_westus2  westus2     Microsoft.Compute/virtualMachines/extensions
aks-agentpool1-14710316-0/OmsAgentForLinux                           MC_OGUZP-AKS_OGUZP-AKS_WESTUS2  westus2     Microsoft.Compute/virtualMachines/extensions
aks-agentpool1-14710316-1                                            MC_oguzp-aks_oguzp-aks_westus2  westus2     Microsoft.Compute/virtualMachines
aks-agentpool1-14710316-1/cse1                                       MC_oguzp-aks_oguzp-aks_westus2  westus2     Microsoft.Compute/virtualMachines/extensions
aks-agentpool1-14710316-1/OmsAgentForLinux                           MC_OGUZP-AKS_OGUZP-AKS_WESTUS2  westus2     Microsoft.Compute/virtualMachines/extensions
aks-agentpool1-14710316-2                                            MC_oguzp-aks_oguzp-aks_westus2  westus2     Microsoft.Compute/virtualMachines
aks-agentpool1-14710316-2/cse2                                       MC_oguzp-aks_oguzp-aks_westus2  westus2     Microsoft.Compute/virtualMachines/extensions
aks-agentpool1-14710316-2/OmsAgentForLinux                           MC_OGUZP-AKS_OGUZP-AKS_WESTUS2  westus2     Microsoft.Compute/virtualMachines/extensions
aks-agentpool1-14710316-nic-0                                        MC_oguzp-aks_oguzp-aks_westus2  westus2     Microsoft.Network/networkInterfaces
aks-agentpool1-14710316-nic-1                                        MC_oguzp-aks_oguzp-aks_westus2  westus2     Microsoft.Network/networkInterfaces
aks-agentpool1-14710316-nic-2                                        MC_oguzp-aks_oguzp-aks_westus2  westus2     Microsoft.Network/networkInterfaces
aks-agentpool-14710316-nsg                                           MC_oguzp-aks_oguzp-aks_westus2  westus2     Microsoft.Network/networkSecurityGroups
aks-agentpool-14710316-routetable                                    MC_oguzp-aks_oguzp-aks_westus2  westus2     Microsoft.Network/routeTables
aks-vnet-14710316                                                    MC_oguzp-aks_oguzp-aks_westus2  westus2     Microsoft.Network/virtualNetworks
```

**Comment by anhowe** [comment]
@OguzPastirmaci this is by design.  This second resource group is the "cluster resource group" and is used to represent and hold the lifecycle of resources underneath it.  What is the impact you are seeing by having the second resource group?

**Comment by OguzPastirmaci** [comment]
I guess there isn't a significant impact but it's just the fact that the experience is different than ACS before. I created an ACS cluster and didn't have a second resource group so I wasn't expecting a second resource group that I don't have any control over the naming etc.

Would that mean that I won't be able to deploy an AKS cluster if I have access rights only to a resource group in a subscription and not the subscription itself?

**Comment by rspaulino** [comment]
@anhowe I agree with @OguzPastirmaci  too, for testing and dev is probably Ok but on production on a large company you want to have control over the resources that you have maybe even tag some resources for billing or department tracking. 

Others Azure manage services don't behave this way like manage disk, SQL server, etc so I wonder want change that Microsoft decide to take this route.

**Comment by SenthuranSivananthan** [comment]
The impact that I see with my customer are:

1. Resource Groups are created with billing tags for charge back.  The new cluster RG doesn't contain this information.

2.  Users don't have Owner permissions on the subscription, therefore the newly created RG is not visible to the user that created the cluster.  This means, get-credential fails with read permissions.  Error:

The client '[email address]' with object id '[guid]' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/read' over scope '/subscriptions/[guid]/resourceGroups/aks-test1/providers/Microsoft.ContainerService/managedClusters/app1'.

Ideally, we can specify the cluster resource group so that the permissions and tags can be pre-created.

**Comment by seanknox** [comment]
> Resource Groups are created with billing tags for charge back. The new cluster RG doesn't contain this information.

Sorry if this is obtuse, but can you just add the tags?

> Customer has a naming convention for the RGs. The new RGs don't conform with their standards.

Is there an operational impact with this?

> Users don't have Owner permissions on the subscription, therefore the newly created RG is not visible to the user that created the cluster.

Haven't seen this before. The sub that created the managed cluster should be an owner of the node pool agent group (e.g. `MC_cluster_name`...). 

cc @sgoings @slack in case I'm missing something.

**Comment by SenthuranSivananthan** [comment]
Yes, the tags can be added via script so it won't be too big of a workaround.  Would be nice if there's a way to override it w/ another switch (i.e. --cluster-resource-group).

No operationally impact with the RG name.  It just deviates from the norm that they've defined.

**Comment by anhowe** [comment]
@SenthuranSivananthan great idea on the custom creation, I'll submit a feature request for this.

**Comment by evillgenius75** [comment]
I think the bigger issue is around Service Principals. Many times the user deploying will not have the rights on a subscription or be able to create a SP that has Subscription level scope. Many times SPs are handed out by Central IT admin, or security teams in Large orgs and those are also scoped to just the RG needed, not the entire subscription.  I think MSI is the answer to all of this, but this is something I have heard from the preview users of ACS RPv2 which also creates another RG for resources and it is not liked by those that have already set governance models on their subscriptions

**Comment by SenthuranSivananthan** [comment]
@evillgenius75, SPs also have a lifecycle and the secrets are regenerated based on security policies so we need to enable the ability to change SPs & secrets as well.  We can take this one in another thread later.

**Comment by weinong** [comment]
Regarding SP's scope, you will not need to apply anything at all. The RP will give contributor role to just the RG we create. This change will roll out in a week or two.

**Comment by ElectricWarr** [comment]
It's been almost two weeks, can anyone confirm if/when this change will be applied?

**Comment by marrobi** [comment]
I think being able to specify a custom name would be a good solution as suggested by @anhowe . Most organizations I work with use naming conventions for resource groups, such as AppName-EnvironmentName-Infra etc.

**Comment by smoerboegen** [comment]
I need to create a public ip within the same resource-group, is there a way to fetch the resource-group name that a certain cluster is using? And yes, it would be very nice to be able to specify the cluster resource-group explicitly.

**Comment by george-walker** [comment]
@smoerboegen I was trying to solve the same issue

**Comment by slack** [comment]
@smoerboegen we do not include the node resource group in the managedCluster API, but that would be a great addition. I'll add that feature to our backlog.

**Comment by rwaal** [comment]
I currently work at a client that has a strict naming convention for resource groups. So the ability to control the name of the cluster resource group is a must-have. 

Additionally, it would nice to be able to specify to have all AKS cluster resources in one single resource group. So the AKS cluster, as well as all other cluster resource, such as the VMs and network resources.

**Comment by derekperkins** [comment]
I also don't understand why the resources are put into a separate group. If I'm concerned that the AKS managed objects are going to clutter my namespace, then I can choose an empty resource group. Is the worry that people are going to edit/delete resources that AKS is relying on, then blame AKS?

**Comment by Addisco** [comment]
I just had the issue that the name of the additional resource group got too long. 
I deployed the AKS cluster in a group which name is 35 chars long, the name of the cluster resource is 36 chars long - resulting in 86 chars (including the `MC_` prefix and `_<regionname>` suffix) for the resource group name. As a result the deployment of the availability set fails with the following error:

```
The entity name 'resourceGroupName' is invalid according to its validation rule: ^[^_\W][\w-._]{0,79}(?<![-.])$.
```

Nevertheless, the `MC_*` resource group was created.

**Comment by dmiyamasu** [comment]
This _enhancement request_ is preventing us from making the migration from ACS to AKS.
Please take into consideration when prioritizing the backlog.

**Comment by mallikharjunrao** [comment]
Hi, 

Facing the similar issue. Azure creating the additional resource group. And when i am trying to get the credentails  getting the below exception on both the actual resourse group and the azure create resource group. Kindly do the needful.

```
$az acs kubernetes get-credentials --resource-group=devops --name=zoom-k8s
The Resource 'Microsoft.ContainerService/containerServices/speedkit-k8s' under resource group 'devops' was not found.
```

```
$ az acs kubernetes get-credentials --resource-group=MC_devops_speedkit-k8s_westeurope --name=zoom-k8s
The Resource 'Microsoft.ContainerService/containerServices/speedkit-k8s' under resource group 'MC_devops_speedkit-k8s_westeurope' was not found.
```

**Comment by slack** [comment]
@mallikharjunrao makes sure you use the `aks` sub command when pulling credentials for an AKS cluster. From the output, looks like you are runing `az acs ...`

**Comment by slack** [comment]
@gugu91 we do not yet have plans to remove or hide the second resource group, it is something we are investigating. However, for folks who do need to safely acquire the additional resource group, we have added a new property `nodeResourceGroup` to the `2018-03-31` API:

```
$ az resource show --api-version 2018-03-31 \
  --namespace Microsoft.ContainerService \
  --resource-type managedClusters \
  -g <RESOURCEGROUP> -n <RESOURCENAME> -o json \
| jq .properties.nodeResourceGroup
"MC_foo-aks-centralus_foo-aks-centralus_centralus"
$
```

**Comment by gugu91** [comment]
@slack Thanks for the prompt response. I am inferring though that this should be used as a last resort. What is the suggested way of retrieving info about the autogenerated resource group? Can I simply use kubectl in order to, for example, retrieve the public IP of a load balancer?

**Comment by leonardocastanodiaz** [comment]
I am facing the same issue with the RG and naming conventions, somebody has found a workaround?
Many thanks

**Comment by fdc-r-wysspeter** [comment]
Same issue here, please add the possibility to set the name of the node ressource group when creating the aks cluster.

**Comment by abouquet** [comment]
@slack , Ressources Group are part of a RBAC strategy in my company and are strictly managed (naming convention, access...) 
I think you should be able at least to specify the node ressource group at AKS cluster creation as stated by @smoerboegen , not only beeing able to retrieve the generated name as you've suggested.

Hope it will be improved quickly in order to be able to use this new service widely :)

**Comment by maadtechie** [comment]
I've added AKS cluster in existing resource group and existing vnet, than I noticed that i have two NEW resource groups:
1. MC_ExistingResourceGroupName_k8s_westeurope.  
2. DefaultResourceGroup-WEU.  (this group is empty)
After reading this thread I understand why first resource group was created, but why does k8s cluster needs two new resource groups? Can I delete the second one, which is empty??

**Comment by rdtechie** [comment]
I agree with @NathanNZ . Some customers of mine are looking to AKS with interest, but the fact that they don't control the naming of the resources is holding them back. The answer to the question if this is a operational issue is no, not really. But, these customers use strict naming policies and their operational teams are used to use these names to search something in the portal/command line. It would be nice if we can influence the naming by use of a ARM template or whatsoever.

**Comment by SamirFarhat** [comment]
Hi,

Can we at least specify tags on the RG crated automatically, any update ?

**Comment by mmisztal1980** [comment]
I'd apreciate na update on this. We have a strict naming policy in our company and we'd like to have the option to create all of the resources in the resource group of our choosing.

**Comment by GSTZ** [comment]
Does the Azure SDK for .NET provide the way to get the auto-generated resource group name?If yes, how?

**Comment by bwalding** [comment]
This is problematic from the security perspective - I don't want to grant the engineering team the ability to create arbitrary resource groups - as they inevitably can't follow naming conventions / forget about resources running etc.  

So I have them locked into pre-created and correctly named resource groups - right up until AKS goes and creates new resource groups that the user can't access and manage.  It would be ok if the user never needed to touch this new RG, but since they need access to those RGs to debug their solutions, they need to raise requests for us to unlock new RGs that AKS is creating.

**Comment by andreujuanc** [comment]
Being able to set a custom name for both RGs it's a must.

**Comment by piotr-napadlek** [comment]
Yep, when I want to use preexisting public IP address to assign it to a load balancer inside aks, I need to create it in the aks node resource group, which brings much more complexity to my deployment process. Would appreciate some control over resource group being created.

**Comment by andreujuanc** [comment]
Or, do the opposite, hide everything from us (the way it should actually be), but still give us the option of connecting to subnets, etc.

**Comment by wy193777** [comment]
Wasting the whole day on how to bind public ip to an AKS created RG. And find this thread.

**Comment by turowicz** [comment]
The `MC_` prefix is really screwing with my OCD. I need all my resource groups be named in a specific way: `{prefix}-{location}-{environment}-{project}` lowercase.

**Comment by marrobi** [comment]
I vary rarely look inside the MC_ resource group now, and work with AKS on a daily basis. How about if it was hidden by default using RBAC maybe, but could be revealed for troubleshooting process? Or is the RG name used by other processes within your subscription? Thinking aloud here.

**Comment by atrauzzi** [comment]
I've always been a fan of this one: https://feedback.azure.com/forums/281804-azure-resource-manager/suggestions/8618338-nested-resource-groups

Allow nesting and rename of resource groups.  Would probably solve zillions of customer gripes for Azure.

**Comment by jeliasson** [comment]
We're almost one year in this issue. Any solution?

**Comment by billtr** [comment]
Totally agreed that this is a big problem in many ways including security, standard, access and control.  In  an enterprise environment where you have a fixed set of subscriptions for people to use, typical users only have resource-group level contributor permission.  From the customer perspective, we need the ability to have control over the creation of this second resource group manually or automatically.  For AKS, it needs the ability to allow people to create new or use existing resource group that users create at deployment time, just like any other Azure services.

**Comment by mkosieradzki** [comment]
IMO it looks like a workaround for lack of VMSS support. I have a hunch that MC_ resource groups will go away as soon as they switch to VMSS in AKS. MC_ group contains all the resources that are usually managed by the VMSS.

But I might be wrong...

**Comment by NathanNZ** [comment]
https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/35496043-please-create-all-the-kubernetes-related-resources

Looks like there is an active uservoice issue relating to this - worth taking the time and voting. Only would take a few people to get it to the front page.

**Comment by skyflyer** [comment]
Would it be OK to manually move resources from the auto-generated resource group to my chosen resource group? Is it even possible?

e.g., to move ContainerInsights and LogAnalytics workspace from `MC_...` group to my group? Would that even work, or would I need to reconfigure the AKS integration somehow to point it to the new resource IDs? (or are resource IDs preserved when moving them from one resource group to another)?

**Comment by MagicMarty** [comment]
> Would it be OK to manually move resources from the auto-generated resource group to my chosen resource group? Is it even possible?
> 
> e.g., to move ContainerInsights and LogAnalytics workspace from `MC_...` group to my group? Would that even work, or would I need to reconfigure the AKS integration somehow to point it to the new resource IDs? (or are resource IDs preserved when moving them from one resource group to another)?

I have tried this scenario and you are able to move resources. Then AKS cluster status on Azure shows as Failed. When logged into the cluster all nodes looks healthy anyway, but still cluster status stays as Failed. Antoher issue, if you scale, new resources will get created to the same MC_ resource group :)

**Comment by pascalgn** [comment]
Related issue: AKS cannot be used when certain resource group policies are in place: https://github.com/Azure/azure-cli/issues/7573

**Comment by erick-thompson** [comment]
Has there been any movement on this? It is extremely annoying and breaks a resource group based security policy.

**Comment by jerrybowman** [comment]
Last week, I could run this command to get he node resource group.  Now it doesn't return anything and apparently the nodeResoureGroup is no longer in the JSON.

` az aks show --query nodeResourceGroup --name carechain-demo --resource-group CareChainApp-demo-rg --output tsv
`

**Comment by rubell** [comment]
It is a big problem for us. Even if we ignore inability to enforce the company's naming conventions, developers do not have subscription level access and not able to create clusters when needed and unable to create (and debug) ARM templates.

**Comment by 1arrow** [comment]
Any traction here, this is a big deciding factor for me to use AKS vs Kubespray

**Comment by maciej-sawicki-codilime** [comment]
This is also a huge problem for us.

**Comment by sowsan** [comment]
can't we just hide the MC_ resource group by default and turn it on for visibilty only if there is a need ? Look like modifying any of the resource in MC_ will impact the SLO of the AKS. So I personally think its best to keep it invisible by default.

**Comment by jfcoz** [comment]
When having access only to the AKS initial RG, using Azure File for dynamic provisionning is impossible due to missing right on the created RG : 
```
# az storage account create --resource-group MC_RG_... --name ...
error retrieving default location: The client ... with object id ... does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/.../resourcegroups/MC_RG_...'.
```
https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv#create-a-storage-account

**Comment by andremarques023** [comment]
This would be a blocker for some customers adopting AKS in production. **The issue was opened on 25 Oct 2017**.

**Comment by vitalybibikov** [comment]
Also a probem, and still no solution

**Comment by jnoller** [comment]
We have planned improvements for this in 2019 however there are additional security features and mutli-az, vmss, etc in front of RG management improvements.

**Comment by sugun999** [comment]
This is blocker for us using AKS.
We are unable to create AKS cluster when resource group policy is enabled. As per the policy, it requires tags(for example, cost center) to be applied for MC_..... resource group which gets created automatically by the AKS. 

Please treat this as high priority issue.

**Comment by minhtrieu-aemo** [comment]
We also having problems,
- breaks our naming standard
- breaks our tagging policy which is used for billing
- breaks our security policy (vendor cant deploy because they cant create resource group)

**Comment by jluk** [comment]
We're looking into this as Jesse mentioned above. The initial scope will be to apply tags/custom name for the resource group only. From there we'll start looking into additional requirements.

**Comment by aefox** [comment]
Hello,

I'd like to add a new scenario on top of the other ones already mentioned which also apply for our customer. We're using terraform to create all of our resources and while all of them are described in the tf files the MC_* one is not. Which is really unfortunate because right now terraform does not list or control all the aks cluster resources.

**Comment by pniederlag** [comment]
Starting to user azure I found this to really be an an unwanted and unexpected behaviour. It's even more frustrating to see a bunch of people already have pinpointed this issue with good arguments and nothing has been done to close this bug. Is azure really ready for production use?

**Comment by asubmani** [comment]
MC_ resource groups also contain resources like Public IP/LB that may be spun from inside the AKS cluster. e.g. an Ingress service. It will also contain NSG per network card for each node. These NSG's are also fully managed by AKS. So any restrictions that you are planning to impose once you get your RBAC has to allow the AKS SPN to have contributor rights to the resource group (whenever the AKS team releases this capability)

**Comment by nyuen** [comment]
the new release (https://github.com/Azure/AKS/releases/tag/2019-04-15) seems to address the issue but I can't find any option in the API or the AZ AKS preview CLI: Customers may now provide custom Resource Group names.

what's the recommended solution to leverage custom RG names in the latest release?

@mcklmt

**Comment by DenisBiondic** [comment]
Most probably the change is in Azure REST API, the tooling needs to catch up first

**Comment by jnoller** [comment]
@nyuen - @denisbiondic is correct, we release AKS changes weekly as a faster rate than the CLI or docs can ship. We will have docs and the needed azure cli changes by end of week

**Comment by seanmck** [comment]
It's now available in v0.3.2 of the preview CLI and doc'd here:

https://docs.microsoft.com/en-us/azure/aks/faq?view=azure-cli-latest#can-i-provide-my-own-name-for-the-aks-infrastructure-resource-group

**Comment by RehanSaeed** [comment]
Is this availible in ARM templates?

**Comment by jnoller** [comment]
@RehanSaeed Yes

**Comment by RehanSaeed** [comment]
The docs are not updated then showing how to do it:

https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2019-02-01/managedclusters

**Comment by jnoller** [comment]
@RehanSaeed See the comment 3 above yours https://github.com/Azure/AKS/issues/3#issuecomment-486663839

**Comment by seanmck** [comment]
Yes. We just changed the existing nodeResourceGroup property to be writeable at cluster create time.

https://docs.microsoft.com/rest/api/aks/managedclusters/createorupdate

**Comment by tomko80** [comment]
@seanmck so is the nodeResourceGroup property also available in the Azure cli? How do I go and change this for an existing k8 setup?

**Comment by pascalgn** [comment]
@tomko80 This is not supported, as per the FAQ https://docs.microsoft.com/en-us/azure/aks/faq?view=azure-cli-latest#can-i-provide-my-own-name-for-the-aks-infrastructure-resource-group
>The following scenarios are not supported:
>You cannot change the MC_ resource group name after the cluster has been created.


@seanmck I could not find the nodeResourceGroup property in the docs for the request body (https://docs.microsoft.com/en-gb/rest/api/aks/managedclusters/createorupdate#request-body), only in the response objects, is this correct?

**Comment by jnoller** [comment]
Update: AKS Shipped custom RG pass-in to the create calls. This functionality is in the `aks-preview` CLI (pass in the `--node-resource-group` argument) and will graduate to the main CLI shortly. 

Example command:
`az aks create -l eastus --name CustomRG --node-resource-group HamBaconSwiss --resource-group coreDNS --generate-ssh-keys`

Portal view:

![Screen Shot 2019-05-08 at 1 50 21 PM](https://user-images.githubusercontent.com/51528/57404059-4f3ee380-7198-11e9-8c47-7e411732bde7.png)

**Comment by MarcosMMartinez** [comment]
@jnoller When we eventually move towards supplying pre-created RGs, hopefully we can also add a flag to **_skip_** the **Contributor** role assignment to the cluster SP if the customer has set the permissions already, prior to the creation of the AKS cluster. 


**Background:** I have a customer leveraging Azure Policy which rejects requests assigning the generic **Contributor** role to the SP of the cluster for the MC_ RG.

**Comment by karyjac** [comment]
@jnoller is there anything else I need to enable in order to try it?
So far I get:

C:\WINDOWS\system32>az extension add --name aks-preview
Extension 'aks-preview' is already installed.

C:\WINDOWS\system32>az aks create -l eastus --name CustomRGCluster --node-resource-group HamBaconSwiss --resource-group HamNodes --generate-ssh-keys
az: error: unrecognized arguments: --node-resource-group HamBaconSwiss
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {aks} ...

**Comment by jnoller** [comment]
@karyjac I suspect you need to update the preview CLI:

`az extension update --name aks-preview`

**Comment by karyjac** [comment]
Thanks @jnoller that solved it, but unfortunately I'm still not able to create:
Operation failed with status: 'Bad Request'. Details: Service principal clientID: b7b88fe8-31fe-4622-870e-f72cefab7b5d not found in Active Directory tenant 72f988bf-86f1-41af-91ab-2d7cd011db47, Please see https://aka.ms/aks-sp-help for more details.

Last time I saw this error it was a problem with Internal subscriptions only :(

**Comment by jnoller** [comment]
@karyjac Not sure, let's take the employee discussion to the internal mailing lists - this is all customer facing so I want to make sure we don't confused this with internal subscription issues :)

**Comment by karyjac** [comment]
Sure thing, Thanks @jnoller

**Comment by jerrybowman** [comment]
So I tried the new option to specify the node resource group. It works, so the name can be specified to meet within my organizations naming standards. But the resource group can't exist. It is still created and deleted by aks when the cluster is created or deleted. Doesn't this still mean that the user creating the cluster must still have privileges to create resource groups? Wouldn't eventually you want to have the resource group provided and aks just uses it as already created?

**Comment by jerrybowman** [comment]
Ah, I just saw this in the release notes:
Customers may now provide custom Resource Group names.

This means that users are no longer locked into the MC_* resource name
group. On cluster creation you may pass in a custom RG and AKS will
inherit that RG, permissions and attach AKS resources to the customer
provided resource group.

* **Currently, you must pass in a new RG (resource group) must be new, and
can not be a pre-existing RG. We are working on support for pre-existing
RGs.**

**Comment by jnoller** [comment]
This is in the aks-preview CLI

Tag inheritance and passing in pre-existing RGs will be further enhancements

**Comment by ahsan3216** [comment]
Hi - I believe there is no way to provide node-resource-group in ansible `azure_rm_aks` module as well. It is failing when there is resource policy defined to add mandatory tags. Any workarounds?

**Comment by spaelling** [comment]
> 
> 
> This is in the aks-preview CLI
> 
> Tag inheritance and passing in pre-existing RGs will be further enhancements

When will we see this? It is fairly annoying having to disable a policy that enforces certain tags on an entire subscription just to create the AKS cluster.
If the resource group is completely empty and has no conflicting tags it should be ok.

**Comment by jluk** [comment]
We recently released functionality that will pass tags set on your AKS RG through to the underlying IaaS RG which the service creates. Could you try a deployment with the policy enforced tags on the AKS RG at cluster create time to see if it passes your policy setting?

A quick write-up on this release was included here:
https://github.com/Azure/AKS/releases/tag/2019-07-01

**Comment by spaelling** [comment]
> 
> 
> We recently released functionality that will pass tags set on your AKS RG through to the underlying IaaS RG which the service creates. Could you try a deployment with the policy enforced tags on the AKS RG at cluster create time to see if it passes your policy setting?
> 
> A quick write-up on this release was included here:
> https://github.com/Azure/AKS/releases/tag/2019-07-01

I just did that today. Both the AKS RG and the node RG should have the same tags, so that part did not work. I did the deployment using an ARM template, does it only work with `az aks create` (preview version i presume)?

**Comment by jluk** [comment]
It should work with ARM template, could you share a few things to help us debug?

1. the snippet for the tags on the template
2. examples of the policies being applied
3. exact error returned upon deployment

**Comment by spaelling** [comment]
> 
> 
> It should work with ARM template, could you share a few things to help us debug?
> 
>     1. the snippet for the tags on the template
> 
>     2. examples of the policies being applied
> 
>     3. exact error returned upon deployment

It works when tagging the AKS cluster itself during creation, those tags do carry-over. Tags on the resource group does nothing.

> We recently released functionality that will pass tags set on your AKS RG through to the underlying IaaS RG which the service creates.

**Comment by jluk** [comment]
Could you please share a repro with an example policy? I'm not 100% clear on which resources are not being passed and if your policy is an append. If a resource can't be created because an error is kicked back the enforce handling needs to be looked at, which we can do if we can get repro details.

An alternative option is you can open a support ticket on this with details for us to gather details in a more private forum.

**Comment by spaelling** [comment]
> 
> 
> Could you please share a repro with an example policy? I'm not 100% clear on which resources are not being passed and if your policy is an append. If a resource can't be created because an error is kicked back the enforce handling needs to be looked at, which we can do if we can get repro details.
> 
> An alternative option is you can open a support ticket on this with details for us to gather details in a more private forum.

The policy effect is 

```
      "then": {
        "effect": "deny"
      }
```

could that be the reason? It does append tags from the cluster itself, so it works fine for me.

**Comment by palma21** [comment]
Hi,

I also could not repro, on the API I find the node_resource_group name I provided. 

Could you provide repro steps or open a ticket with us?

 ```
   "loadBalancerSku": "standard",
    "networkPlugin": "azure",
    "networkPolicy": null,
    "podCidr": null,
    "serviceCidr": "10.0.0.0/16"
  },
  "nodeResourceGroup": "infra-aksmgmt-demo1",
  "provisioningState": "Succeeded",
  "resourceGroup": "aksmgmt-demo-rg",
```

**Comment by nubesoltech** [comment]
I'm fairly new to AKS/Azure.  The MCS resource groups continue to be created when creating an AKS cluster.  If I'm migrating to a new subscription, do I have to account for both AKS resource groups?  The one I created and one that Azure created.

**Comment by jluk** [comment]
This issue has gotten quite broad and has lost a lot of useful context given how old it is, so I am closing this in favor of new issues to be more concise.

* (Original ask) Remove the MC_RG required of clusters, which is visible to users: #1231 
* Passing tags or naming a new RG for the MC_RG are features which should work, please open support tickets or new issues w questions if you have problems with those.
* If you have other questions, please open a new issue or use the referenced one above.

@nubesoltech if migrating yes you need to account for both of the resource groups.

**Comment by dariuszbz** [comment]
Hello All,

I have the same problem. Customer policy enforces new RG with tags. The node RG is not created and I'm getting an error: "Resource 'DefaultResourceGroup-EUS2' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Enforce ....."

my az cli:

    az aks create --resource-group $rg `
                  --name  $ClusterName `
                  --enable-vmss `
                  --dns-name-prefix $ClusterName.ToLower() `
                  --node-count 2 `
                  --node-vm-size $AKS_MasterNodesSize `
                  --node-resource-group $rgNode `
                  --enable-addons monitoring `
                  --kubernetes-version $AKS_Version `
                  --service-principal $global:rbac.appId `
                  --client-secret $global:rbac.password `
                  --generate-ssh-keys `
                  --windows-admin-password $Password_Win `
                  --windows-admin-username $User_Win `
                  --network-plugin azure `
                  --location $ClusterLocation `
                  --tags "Billing-01=LM"

**Comment by mkosieradzki** [comment]
@dariuszbz nope. The error you are having is coming from creation of OMS workspace. Just add `--workspace-resource-id` and point it out to your existing OMS and you should be fine. It might also come from network creation... so you should also point out a: `--vnet-subnet-id` to an existing subnet.

**Comment by dariuszbz** [comment]
I found it ... I created "default" group manually. I run the command again
and all worked as expected.
Funny: no resources were created in "default" group. So .... "Lazy
development" I think but can't believe .

**Comment by naren-dremio** [comment]
Does anything break if I move the resources under MC_ RG to the RG where the AKS resource is present?

**Comment by jeliasson** [comment]
> Does anything break if I move the resources under MC_ RG to the RG where the AKS resource is present?

Yes, and you can’t and shouldn’t.
https://docs.microsoft.com/en-us/azure/aks/faq#why-are-two-resource-groups-created-with-aks

**Comment by SamirFarhat** [comment]
@naren-dremio you can create a new cluster and customize the RG names

**Comment by TheAzureGuy007** [comment]
> I think the bigger issue is around Service Principals. Many times the user deploying will not have the rights on a subscription or be able to create a SP that has Subscription level scope. Many times SPs are handed out by Central IT admin, or security teams in Large orgs and those are also scoped to just the RG needed, not the entire subscription. I think MSI is the answer to all of this, but this is something I have heard from the preview users of ACS RPv2 which also creates another RG for resources and it is not liked by those that have already set governance models on their subscriptions

This existence of MC_RG becomes even more problemetic if you are using your cluster in Kubernetes Multitenancy mode , where the disks which will spin by variuos cxs will start lying in this MC_ RG and How one can maintain cxs secondary resources like DB, storage etc. which are connected to AKS cluster, in multi shared cluster env ?

**Comment by bhicks329** [comment]
@TheAzureGuy007 - You can put your disks up in any RG you want. You just have to make sure the AKS cluster principles have contributor access to the disks.

https://docs.microsoft.com/en-gb/azure/aks/azure-disk-volume#mount-disk-as-volume

**Comment by pniederlag** [comment]
> @TheAzureGuy007 - You can put your disks up in any RG you want. You just have to make sure the AKS cluster principles have contributor access to the disks.
> 
> https://docs.microsoft.com/en-gb/azure/aks/azure-disk-volume#mount-disk-as-volume

that's great news, wish I had knewn that erlier, will give it a try

**Comment by emacdona** [comment]
My problem with this is that I'm not the Subscription Owner. The Subscription Owner has created a Resource Group for me, and I am free to create resources within that group. I am able to create an AKS cluster in that group, however I can't see any resources it uses (VMs, Disks, etc) because I don't have access to the resource group it creates them in. While I can still use the cluster, I can't do things like backup up the Azure Disks backing the K8s Persistent Volumes.

Is there a way for my Subscription Owner to give me access to all Resource Groups that are created by Azure infrastructure on behalf of actions I take? Like is there a role he could assign me to to fix this problem?

**Comment by pniederlag** [comment]
@emaconda 
 
> Is there a way for my Subscription Owner to give me access to all Resource Groups that are created by Azure infrastructure on behalf of actions I take? Like is there a role he could assign me to to fix this problem?

Our Owners just added a "Contributor"-Role to the scope of the "MC-*" Resource-Group. With that role I can even access the Storage-Accounts inside.

**Comment by atrauzzi** [comment]
#1231 was deleted, any reason why? Where does the thread pick up at this point?

Why can't the resources simply be in the same resource group in which the AKS service was provisioned?
