### ISSUE TITLE
Custom service-cluster-ip-range

### ISSUE THREAD

**Issue by jaq316** [Azure/AKS#300]
Are there any plans to introduce the ability to customise the ip range of services inside the cluster? 

We are experiencing issues when trying to route to a on-prem 10.x.x.x address over site-to-site VPN set up between Azure and our datacenter. I'm suspecting that this is caused by the fact that the services are also assigned ip addresses in that same range. 

Having the ability to change the services ip range would greatly improve our ability to fault find.

Are there any workarounds for this?

**Comment by sachinar** [comment]
@jaq316 you are looking for this #[27](https://github.com/Azure/AKS/issues/27)

**Comment by jaq316** [comment]
Thanks @sachinar

**Comment by valorl** [comment]
Not the perfect solution and I haven't tested it fully yet, but it should be possible to shrink the address space of the VNET that AKS creates. The VNET is `10.0.0.0/8` but the subnet is only `/16` so you can try shrinking the VNET so that it would only have the address space of the subnet.
