### ISSUE TITLE
The azure-keyvault-secrets-provider doesn't work on AKS Windows Server 2022 nodepools

### ISSUE THREAD

**Issue by ShiqianTao** [Azure/AKS#3001]
**What happened**:
Users enabled ```azure-keyvault-secrets-provider``` addon for AKS cluster but it doesn't work on AKS Windows Server 2022 nodepools.

**How to reproduce it (as minimally and precisely as possible)**:
```az aks create -n myAKSCluster -g myResourceGroup --enable-addons azure-keyvault-secrets-provider --enable-managed-identity```
```az aks enable-addons --addons azure-keyvault-secrets-provider --name myAKSCluster --resource-group myResourceGroup```
The addon doesn't work on AKS Windows Server 2022 nodepools.

**Anything else we need to know?**:
It is by design since ```azure-keyvault-secrets-provider``` addon is not supported in Windows Server 2022 for now. It is still in progress and will be supported in the future.

**Comment by andyzhangx** [comment]
what do you mean "does not work"? is the driver pod crashing?

**Comment by ZeroMagic** [comment]
Ref: https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/931

**Comment by ShiqianTao** [comment]
The issue was fixed. Close this issue.
