### ISSUE TITLE
Flux extension installation fails on AKS clusters with windows nodepool(s)

### ISSUE THREAD

**Issue by CosminSontu** [Azure/AKS#3002]
**What happened**:
When installing flux configuration in an AKS cluster with a windows node pool, the flux plugin installation failed
**What you expected to happen**:
Flux plugin installation to succeed and flux configuration applied to the cluster.
**How to reproduce it (as minimally and precisely as possible)**:
Add a flux configuration to an AKS cluster with a windows nodepool

**Anything else we need to know?**:
Some kubernetes objects: deployments  (fluxconfig-agent and fluxconfig-controller) and job (flux-delete-fluxconfig) from flux k8s definitions/charts are lacking the _nodeSelector: kubernetes/io: linux_ annotation (or affinity),
the cluster allocates them on windows node pool causing the failure of flux plugin installation.
**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.6
- Size of cluster (how many worker nodes are in the cluster?) 1 system linux nodepool with 1 node; 1 user windows nodepool with 1 node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): empty cluster, just flux-system namespace with some pods not being able to pull their images due to mismatch of os (image os!=node os) 
Sample event from cluster:
_Failed to pull image "mcr.microsoft.com/azurek8sflux/fluent-bit:1.2.0": rpc error: code = Unknown desc = no matching manifest for windows/amd64 10.0.17763 in the manifest list entries_
- Others: ...
f I _kubectl edit_ the aforementioned objects and apply the nodeSelector annotation, pods get their images and start running fine (on linux nodepool). 
Unfortunately Azure API statuses remain in fail mode
( 'Microsoft.Flux' extension is installed but not in a succeeded state on the cluster. Unable to proceed with Flux v2 configuration install. )
and Flux Configurations cannot be applied to the cluster

**Comment by umeshbhatms** [comment]
Is there any update on this?

**Comment by oleksandrtroshyn** [comment]
I am also looking forward to be able to set node affinity with flux2

**Comment by bavneetsingh16** [comment]
We have added nodeSelectors for all controller deployments and also for the delete job. Please upgrade the flux extension version(to most recent version - 1.6.3; at least to 1.6.1 for it to work)

**Comment by kaarthis** [comment]
Closing per above answer from @bavneetsingh16
