### ISSUE TITLE
Kubernetes Version 1.24

### ISSUE THREAD

**Issue by miwithro** [Azure/AKS#3003]

**Comment by qpetraroia** [comment]
Kubernetes version 1.24 will go GA on July 31st 2022.

**Comment by martinstenhoff** [comment]
Are there issues with this release as I can't see 1.24 GA available in any regions atm? And I can't see there's an AKS release note ( https://github.com/Azure/AKS/releases) for a release that would enable 1.24 GA.

**Comment by martinstenhoff** [comment]
@justindavies 

Is there an updated timeline for when 1.24 GA will be available? I can't see anything in the release notes for the 2022-07-31 release that 1.24 will go GA as part of that.

**Comment by justindavies** [comment]
1.24 GA is rolling out at the moment and will be in this week's release notes (currently cooking those)

**Comment by jayamahendran** [comment]
AKS K8s 1.24 is not in GA yet. As per release calendar it suppose to be in Jul-22. Can you please suggest when it will moved to GA

$ az aks get-versions --location eastus2 --output table
KubernetesVersion    Upgrades
-------------------  ------------------------
1.24.0(preview)      None available
1.23.8               1.24.0(preview)
1.23.5               1.23.8, 1.24.0(preview)
1.22.11              1.23.5, 1.23.8
1.22.6               1.22.11, 1.23.5, 1.23.8
1.21.14              1.22.6, 1.22.11
1.21.9               1.21.14, 1.22.6, 1.22.11

**Comment by wangyira** [comment]
@qpetraroia can you help take a look at this?
