### ISSUE TITLE
Missing Ubuntu Image version when verifying upgrade

### ISSUE THREAD

**Issue by jdiazquiroga** [Azure/AKS#3005]
Hello

I just ran the command to verify image versions to upgrade my cluster 

az aks nodepool get-upgrades --resource-group xxxxx --cluster-name xxxxx --nodepool-name xxxxx

In the result I get this 

{
  "id": "/subscriptions/xxxxxxxx",
  "kubernetesVersion": "1.22.4",
  "latestNodeImageVersion": "AKSUbuntu-1804gen2containerd-2022.05.16",
  "name": "default",
  "osType": "Linux",
  "resourceGroup": "xxxxxx",
  "type": "Microsoft.ContainerService/managedClusters/agentPools/upgradeProfiles",
  "upgrades": null
}

However I cannot find version AKSUbuntu-1804gen2containerd-2022.05.16 here: https://github.com/Azure/AKS/tree/master/vhd-notes/aks-ubuntu/AKSUbuntu-1804

How can I know it is a valid version?

**Comment by CocoWang-wql** [comment]
Hello @jdiazquiroga  can you pls run the get-upgrades command again. Seems the 2022.05.16 image was recalled and I get 2022.05.24 version from my side.
