### ISSUE TITLE
Integration of AKS with K8S Descheduler

### ISSUE THREAD

**Issue by ranikamadurawe** [Azure/AKS#3006]
## Description
Integration of AKS with K8S-Descheduler for more robust descheduling and pod/node management

## Resources
https://github.com/kubernetes-sigs/descheduler

**Comment by ilyatovbin-pp** [comment]
just noticed we've been paying a couple thousand bucks a month more for no reason. nodes are extremely under utilized and there's no rescheduling or binpacking of any kind. this is problematic in small environments with intermittent scaleups. We'll be installing Descheduler immediately but if something like this could be implemented out of the box it cold be great.

**Comment by paulgmiller** [comment]
Does autoscaler not get you much the sam thing? It should scaledown underutilized nodes draining pods off before it reclaims them?

**Comment by 4c74356b41** [comment]
> Does autoscaler not get you much the sam thing? It should scaledown underutilized nodes draining pods off before it reclaims them?

I dont think it does. I've deleted 4 nodes manually and it doesn't scale up (because there is still plenty resources available)
