### ISSUE TITLE
Longer or configurable drains timeout for during Kubernetes version or node image upgrades

### ISSUE THREAD

**Issue by ondrejhlavacek** [Azure/AKS#3008]
**What happened**:  The Kubernetes version or node image upgrade does not finish successfully when there is a long running non-terminable pod. The node pool is then in a failed state. 

I have tried autoupgrade channels, manual az cli commands or just upgrading in the UI. They all show the same symtpoms.

We have a long running workload in a pod that we're not able to reschedule during runtime to another node. The pod has very long `terminationGracePeriodSeconds` (up to 24 hours but can be more) and the state cannot be stopped and resumed somewhere else. It's a IO/CPU/memory intensive stateful data science workload (encapsulated in a pod) and we want to wait for it to finish. We have configured all possible parameters so when we drain the node this pod does not get evicted and the drain just waits until the pod finishes. Autoscaling for example works perfectly fine, security upgrades using Kured also respect these long running pods, but `az aks [nodepool] upgrade` does not. 

**What you expected to happen**: Configurable or significantly longer drain timeout (it's 30 minutes now it seems - https://github.com/Azure/AKS/issues/2114#issuecomment-920500258).

**How to reproduce it (as minimally and precisely as possible)**: Have any non-terminable pod running during upgrades.

**Comment by paulgmiller** [comment]
We're considering this though we would probably set a max 24 hours is reasonable but beyond that its easy to get stuck. (luckily we're shipping a abort operation now)

I did find several that customers ask for this but then ask for this but don't realize they need to handle the first termination signal and abandon this when they relalize they need to change code.

**Comment by ondrejhlavacek** [comment]
24 hrs is reasonable. Thanks for considering!

**Comment by BenjaminHerbert** [comment]
We are also suffering from this issue. For our ECK installation, we are frequently running into this issue for nodepool upgrades. Volume attachment takes quite some time for each pod and this frequently fails the nodepool upgrades.

**Comment by paulgmiller** [comment]
Trying to get something into an upcoming preview api.

**Comment by ondrejhlavacek** [comment]
Any update here?

**Comment by BenjaminHerbert** [comment]
@paulgmiller & @kaarthis: Could you reopen this issue? This is a problem we run into at each upgrade (node-image upgrade as well).

**Comment by BenjaminHerbert** [comment]
Could you reopen this issue, @ondrejhlavacek ?

**Comment by ondrejhlavacek** [comment]
@BenjaminHerbert I don't think I can 😔
