### ISSUE TITLE
Custom VNet for AKS cluster

### ISSUE THREAD

**Issue by sachinar** [Azure/AKS#301]
Hi Team,

we need custom Vnet for AKS cluster,
Currently we are unable to create aks cluster in existing VNet.

When this feature will be available for AKS.?
We have to create VPN connection for AKS cluster But the IP range for AKS VNet is 10.0.0.0/8.

This range is very huge & we have resources in this Vnet.

**Comment by jalberto** [comment]
@sachinar you are looking for this #27

**Comment by sachinar** [comment]
@jalberto  Yes same issue.
