### ISSUE TITLE
Auto scaler unable to scale down pools

### ISSUE THREAD

**Issue by jabbera** [Azure/AKS#3011]
**What happened**:

Starting 6/10 2:43 AM pools no longer scale down. The auto scaler produces the following logs and nodes don't scale down.

Ticket id: 2206130040004566 for anyone interested. Ironically we can't find any evidence this maintenance feature is in use.

```
6/10/2022, 2:43:04.000 AM
"message": "Operation 'ForceDelete' is not allowed on resource 'aks-e80ids-18112100-vmss' since it manages updates using maintenance control."
6/10/2022, 2:43:04.000 AM
E0610 02:43:04.552773 1 scale_down.go:1178] Problem with empty node deletion in nodegroup aks-e80ids-18112100-vmss: Operation 'ForceDelete' is not allowed on resource 'aks-e80ids-18112100-vmss' since it manages updates using maintenance control.
```

**What you expected to happen**: Node should scale down

**How to reproduce it (as minimally and precisely as possible)**: Unknown

**Anything else we need to know?**: impacts 1.22.6 and 1.23.5

**Environment**: AKS Linux
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?) 6 now, should be 0 for this pool.
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): No workload
- Others:

**Comment by seanslma** [comment]
We got the same issue on version 1.23.5. 

I suppose the time this problem first happened is the same. 

We noticed the issue when one of our apps, which runs daily, first failed in the midnight of 6/11.

**Comment by jabbera** [comment]
@seanslma  My rep seems to think it's related to the use of planned maintenance. Are you using this feature: https://docs.microsoft.com/en-us/azure/aks/planned-maintenance

**Comment by seanslma** [comment]
@jabbera Sorry for the late reply. 

No, I do not have a ticket number. 

We have not used the planned maintenance preview feature.

**Comment by seanslma** [comment]
@jabbera Thanks for letting me know. Hopefully there is a new release soon with the bug being fixed.
