### ISSUE TITLE
Dynamic allocation of IPs without using dedicated pod subnet

### ISSUE THREAD

**Issue by stijndehaes** [Azure/AKS#3013]
**What happened**:

We were trying to use the [Dynamic allocation of IPs](https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#dynamic-allocation-of-ips-and-enhanced-subnet-support). Looking ath the documentation it looks like you need to use a dedicated pod ip. 
I tried to set the pod-subnet to the same as the node subnet but we were not allowed to do that.

**What you expected to happen**:
I would like to be able to use the same subnet for nodes and pods but still be able to use the `Dynamic allocation of IPs` support.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the guide here but use the same subnet for the `--vnet-subnet-id` and `--pod-subnet-id` flag

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.6
- Size of cluster (how many worker nodes are in the cluster?): NA
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) NA
- Others: NA

**Comment by paulgmiller** [comment]
@phealy 

I hear your ask but the to be dynamic the podsubnet has to be delegated to a paricular use (aks  in this instance_ and can't share with resources like compute. So it's unlikely we'll be doing this in the near future. 

Is it hard for you to get another subnet for pods?  (vnet fragmentation?)

Do your pod ips need to be addressable from other resources on your vnet or only other pods in the cluster. If the later we're looking at a new scalable overlay that might meet your needs.

**Comment by stijndehaes** [comment]
@paulgmiller the reason I was asking for this was more for a migration use case. We had a cluster running in a relatively big subnet. To start using this feature, we wanted to use that big subnet for the pods and an smaller one for the nodes.
But this limitation stopped us from doing that, also we needed to create a new cluster and migrate everything over. This all of a sudden was a 2 step process to do without downtime:
- create new cluster with nodes in new small subnet, and pods using that same subnet (hoping you have enough IP's in that smaller one), migrate all running processes over
- delete the old cluster after migration is done
- Create new cluster with nodes in new small subnet, pods in big subnet, migrate everything over
- delete temporary cluster

If we could have run pods and nodes in same subnet using this feature the migration would have been to only create one new cluster. If we could change the network mode in a running cluster (I believe this is impossible according to docs), we wouldn't have needed to recreate the cluster.

We have done the migration with downtime, this is possible at the moment since no critical infra was moved yet. But it won't be possible in the future, so I wanted to drop this as a feature request. If new features pop up we would love to use them without having to do multiple migrations to a new cluster :)

**Comment by paulgmiller** [comment]
Ack I hear you. We're looking at allowing allowing you to change the network mode (one way) and the add new podsubnet agentpools but that still isn't helpful in freeing your large nodepool subnet without creating a second large podsubnet since subnets aren't resizable.

**Comment by paulgmiller** [comment]
@stijndehaes  when it GA's would you consider moving to the overlay network if we gave you an inplace upgrae path that didn't lose connectivity? https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay

You'd still have to create a new agentpool to free your old subnet but you can do it after your migrated at your leisure. 

Or do you need pod ips to be in vnet?

**Comment by stijndehaes** [comment]
@paulgmiller I would definitely consider moving to this. Not losing connectivity makes the upgrade that much easier for us. Otherwise we would either: need to introduce downtime, or migrate to a new cluster. 

Creating a new agent pool is now problem.

Pods ips do not need to be in the vnet at the moment.

**Comment by paulgmiller** [comment]
Going to close this as we don't see for see a way to have podsubent and nodesubnet be the same in the medium future. Going to have someone reach out to @stijndehaes to see if he's still interested in upgrade to overlay path which is closer now.

**Comment by paulgmiller** [comment]
closing we don't see for see a way to have podsubent and nodesubnet be the same in the medium future
