### ISSUE TITLE
Persistent volume mount timeout

### ISSUE THREAD

**Issue by devkws** [Azure/AKS#302]
My pods always receive a mount timeout when using persistent volumes. 
The claim is bound but when a pod that uses it spins up I receive a mount timeout. I’ve tried different vm sizes per another issue, this does not help. Recently been using 3x Standard_DS3_v2. Same problem. 
I should also mention I’m in Canada central Datacenter.

**Comment by devkws** [comment]
I should also add it’s a clean 1.8.7 setup.

**Comment by andyzhangx** [comment]
@devkws pls provide following info:
 - `kubectl describe po POD-NAME`
 - kubelet logs, could follow by: https://github.com/andyzhangx/Demo/tree/master/debug#q-how-to-get-k8s-kubelet-logs-on-linux-agent

**Comment by devkws** [comment]
i recreated the cluster and immediately upgraded to 1.9.6, same issue.


pod describe
`Name:           redis-app-0
Namespace:      blah
Node:           aks-agentpool-15629614-1/10.240.0.4
Start Time:     Wed, 18 Apr 2018 14:18:37 +0000
Labels:         app=redis
                appCluster=redis-cluster
                controller-revision-hash=redis-app-fdfd5d75c
                statefulset.kubernetes.io/pod-name=redis-app-0
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  StatefulSet/redis-app
Containers:
  redis:
    Container ID:  
    Image:         redis:4.0.9
    Image ID:      
    Ports:         6379/TCP, 16379/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      redis-server
    Args:
      /etc/redis/redis.conf
      --protected-mode
      no
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /etc/redis from redis-conf (rw)
      /var/lib/redis from redis-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-qmpjj (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  redis-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  redis-data-redis-app-0
    ReadOnly:   false
  redis-conf:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      redis-conf
    Optional:  false
  default-token-qmpjj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-qmpjj
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age              From                               Message
  ----     ------                 ----             ----                               -------
  Normal   Scheduled              5m               default-scheduler                  Successfully assigned redis-app-0 to aks-agentpool-15629614-1
  Normal   SuccessfulMountVolume  5m               kubelet, aks-agentpool-15629614-1  MountVolume.SetUp succeeded for volume "redis-conf"
  Normal   SuccessfulMountVolume  5m               kubelet, aks-agentpool-15629614-1  MountVolume.SetUp succeeded for volume "default-token-qmpjj"
  Warning  FailedMount            1m (x2 over 3m)  kubelet, aks-agentpool-15629614-1  Unable to mount volumes for pod "redis-app-0_newsdesk(630216d3-4313-11e8-971b-0a58ac1f08a0)": timeout expired waiting for volumes to attach/mount for pod "newsdesk"/"redis-app-0". list of unattached/unmounted volumes=[redis-data]
  Warning  FailedMount            1m               kubelet, aks-agentpool-15629614-1  MountVolume.SetUp failed for volume "nfs-vol1" : exit status 32
`


kubelet logs
`Flag --non-masquerade-cidr has been deprecated, will be removed in a future version
Flag --keep-terminated-pod-volumes has been deprecated, will be removed in a future version
Flag --non-masquerade-cidr has been deprecated, will be removed in a future version
I0418 13:41:36.874296    7473 server.go:182] Version: v1.9.6
I0418 13:41:36.874392    7473 feature_gate.go:226] feature gates: &{{} map[Accelerators:true]}
I0418 13:41:37.720117    7473 mount_linux.go:193] Detected OS without systemd
I0418 13:41:37.720142    7473 server.go:142] Running kubelet in containerized mode (experimental)
W0418 13:41:37.720399    7473 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
I0418 13:41:37.730800    7473 azure.go:249] azure: using client_id+client_secret to retrieve access token
I0418 13:41:38.149723    7473 server.go:305] Successfully initialized cloud provider: "azure" from the config file: "/etc/kubernetes/azure.json"
I0418 13:41:38.149793    7473 server.go:541] cloud provider determined current node name to be aks-agentpool-15629614-1
I0418 13:41:38.165803    7473 manager.go:151] cAdvisor running in container: "/sys/fs/cgroup/cpu,cpuacct"
I0418 13:41:38.195079    7473 fs.go:139] Filesystem UUIDs: map[75604357-9029-4b6f-8c13-6201b689c664:/dev/sda1 a4e98fe5-5020-4dc7-b668-94a2c2193466:/dev/sdb1]
I0418 13:41:38.195108    7473 fs.go:140] Filesystem partitions: map[tmpfs:{mountpoint:/sys/fs/cgroup major:0 minor:48 fsType:tmpfs blockSize:0} /dev/sda1:{mountpoint:/var/lib/docker/overlay2 major:8 minor:1 fsType:ext4 blockSize:0} /dev/sdb1:{mountpoint:/rootfs/mnt major:8 minor:17 fsType:ext4 blockSize:0} shm:{mountpoint:/rootfs/var/lib/docker/containers/830e85aafebd2030a2cd9e90d6b2d0615e13222d2ad8d8791ff1419ddb1dee43/shm major:0 minor:46 fsType:tmpfs blockSize:0}]
I0418 13:41:38.197742    7473 manager.go:225] Machine: {NumCores:4 CpuFrequency:2294690 MemoryCapacity:14683791360 HugePages:[{PageSize:1048576 NumPages:0} {PageSize:2048 NumPages:0}] MachineID:91f302fc97074b5e9d545dd4c6a8e966 SystemUUID:FC165976-E0BF-884C-B1F4-0AE5C36545B7 BootID:782d0e5e-c7a0-4603-8e65-8d280d4daf35 Filesystems:[{Device:overlay DeviceMajor:0 DeviceMinor:45 Capacity:31158935552 Type:vfs Inodes:3840000 HasInodes:true} {Device:tmpfs DeviceMajor:0 DeviceMinor:48 Capacity:7341895680 Type:vfs Inodes:1792455 HasInodes:true} {Device:/dev/sda1 DeviceMajor:8 DeviceMinor:1 Capacity:31158935552 Type:vfs Inodes:3840000 HasInodes:true} {Device:/dev/sdb1 DeviceMajor:8 DeviceMinor:17 Capacity:29457707008 Type:vfs Inodes:1835008 HasInodes:true} {Device:shm DeviceMajor:0 DeviceMinor:46 Capacity:67108864 Type:vfs Inodes:1792455 HasInodes:true}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:32212254720 Scheduler:none} 8:16:{Name:sdb Major:8 Minor:16 Size:30064771072 Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:00:0d:3a:f3:ef:03 Speed:40000 Mtu:1500}] Topology:[{Id:0 Memory:14683791360 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2} {Size:52428800 Type:Unified Level:3}]} {Id:1 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2} {Size:52428800 Type:Unified Level:3}]} {Id:2 Threads:[2] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2} {Size:52428800 Type:Unified Level:3}]} {Id:3 Threads:[3] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2} {Size:52428800 Type:Unified Level:3}]}] Caches:[]}] CloudProvider:Azure InstanceType:Unknown InstanceID:FC165976-E0BF-884C-B1F4-0AE5C36545B7}
I0418 13:41:38.198569    7473 manager.go:231] Version: {KernelVersion:4.13.0-1011-azure ContainerOsVersion:Debian GNU/Linux 9 (stretch) DockerVersion:1.13.1 DockerAPIVersion:1.26 CadvisorVersion: CadvisorRevision:}
I0418 13:41:38.199128    7473 server.go:428] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
I0418 13:41:38.200301    7473 container_manager_linux.go:242] container manager verified user specified cgroup-root exists: /
I0418 13:41:38.200321    7473 container_manager_linux.go:247] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>}]} ExperimentalQOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s}
I0418 13:41:38.200409    7473 container_manager_linux.go:266] Creating device plugin manager: false
I0418 13:41:38.200495    7473 server.go:541] cloud provider determined current node name to be aks-agentpool-15629614-1
I0418 13:41:38.200506    7473 server.go:693] Using root directory: /var/lib/kubelet
I0418 13:41:38.200565    7473 kubelet.go:406] cloud provider determined current node name to be aks-agentpool-15629614-1
I0418 13:41:38.200581    7473 kubelet.go:291] Adding manifest path: /etc/kubernetes/manifests
I0418 13:41:38.200600    7473 file.go:52] Watching path "/etc/kubernetes/manifests"
I0418 13:41:38.200610    7473 kubelet.go:316] Watching apiserver
I0418 13:41:38.209053    7473 kubelet.go:577] Hairpin mode set to "promiscuous-bridge"
I0418 13:41:38.222643    7473 plugins.go:190] Loaded network plugin "kubenet"
I0418 13:41:38.222703    7473 client.go:80] Connecting to docker on unix:///var/run/docker.sock
I0418 13:41:38.222739    7473 client.go:109] Start docker client with request timeout=2m0s
W0418 13:41:38.225772    7473 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
I0418 13:41:38.231262    7473 plugins.go:190] Loaded network plugin "kubenet"
I0418 13:41:38.231336    7473 docker_service.go:232] Docker cri networking managed by kubenet
`

**Comment by andyzhangx** [comment]
Your kubelet logs are not complete, could you provide complete kubelet logs from `aks-agentpool-15629614-1`? How do you create pvc `redis-data-redis-app-0`, is it azure disk? could you also provide the config?

**Comment by devkws** [comment]
I'm sorry, I thought the kubelet logs were complete, I followed the instruction but I guess something went wrong. There is a strong possibility that the issue is with my yaml files, but the pvc bind fine. i updated the class to managed-premium to see if there was an issue with default, same result.

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-redis-app-0
  labels:
    type: redis-nfs-claim
    app: redis
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      path: nfsshare1
      app: redis
      podindex: "0"


apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol1
  labels:
    path: nfsshare1
    type: redis-nfs
    app: redis
    podindex: "0"
spec:
  storageClassName: managed-premium
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.1
    path: "/data/store/share/n1"

**Comment by andyzhangx** [comment]
so you are using nfs volume, while `managed-premium` is azuredisk volume, pls follow this guide config your nfs volume, it should work in AKS, I have tried before:
https://github.com/andyzhangx/demo/tree/master/linux/nfs

**Comment by devkws** [comment]
You are correct, your demo really helped. Thank you.
