### ISSUE TITLE
AKS 1.21 EOL for create flow

### ISSUE THREAD

**Issue by nikhilMS123** [Azure/AKS#3020]
1.Is there a way to identify the exact date of expiration of any Kubernetes version?
We are currently using AKS 1.21 which is having its EOL in JULY 2022 and currently we are in phase of upgrading our AKS version from 1.21 to 1.22. Can we know the exact date after which the creation of AKS cluster with 1.21 versions will stop working?
2.Also if the dates mentioned here (https://kubernetes.io/releases/) is correct, can we have it extended for our project by any means so that our instance creation with 1.21 will not fail.

For context, we have a PAAS Service which provisions AKS Clusters on demand. (apart from other services). since we are currently on 1.21 we wanted to confirm/getexception to support AKS set up post June.

We area already working on moving to the latest version, this Issue is to get clarity on the dates/exception process

**Comment by raghulmsft** [comment]
Thanks for sharing! I'll work with the team and provide an update.
