### ISSUE TITLE
Azure Files with DIND on AKS

### ISSUE THREAD

**Issue by BenH-Puregym** [Azure/AKS#3021]
I'm wanting to use Azure File for storing docker image cache found in `/var/lib/docker` , when mounting it using premium disk it works fine but when i use Azure File it throws an error:

`##[error]failed to register layer: Error processing tar file(exit status 1): link /bin/gunzip /bin/uncompress: operation not supported `

**Comment by andyzhangx** [comment]
should be a known issue: https://github.com/Azure/AKS/issues/2360#issuecomment-864998388

**Comment by BenH-Puregym** [comment]
yes I've seen this one but it's closed without any resolution

**Comment by BenH-Puregym** [comment]
how can it not be supported, there's a storage class for AzureFile and it's documented here: https://kubernetes.io/docs/concepts/storage/storage-classes/

**Comment by andyzhangx** [comment]
@BenH-Puregym I think you could try azure file NFS

**Comment by BenH-Puregym** [comment]
do you have an example? azure disks won't work multi-nodes and I can only think you're suggesting to create an NFS server and then use the NFS storage class but your message is unclear.

**Comment by andyzhangx** [comment]
> do you have an example? azure disks won't work multi-nodes and I can only think you're suggesting to create an NFS server and then use the NFS storage class but your message is unclear.

@BenH-Puregym sorry for the confusion, here is an example using azure file nfs share: https://docs.microsoft.com/en-us/azure/aks/azure-files-csi#nfs-file-shares, nfs should supports symlink well, not sure whether it would solve the DIND issue, anyway, it's worth a try.

**Comment by BenH-Puregym** [comment]
this provides two additional issues:
We need a service endpoint which we can't do because we have storage accounts in different regions requiring to talk to the subnet which is a limitation. 

it only works on 1 container, when deploying multiple containers the docker daemon fails to start
`failed to start daemon: error while opening volume store metadata database: timeout`

**Comment by BenH-Puregym** [comment]
@andyzhangx any update on this issue?

the problem with this not working is because AKS now uses containerD we cannot use Docker-outside-of-Docker and so have to install docker and cache from the pod level (DIND). We don't have any option to get caching for a node pool which has multiple nodes since azure file doesn't work and azure disk is tied to one node.

**Comment by andyzhangx** [comment]
> @andyzhangx any update on this issue?
> 
> the problem with this not working is because AKS now uses containerD we cannot use Docker-outside-of-Docker and so have to install docker and cache from the pod level (DIND). We don't have any option to get caching for a node pool which has multiple nodes since azure file doesn't work and azure disk is tied to one node.

@BenH-Puregym docker is not supported on AKS, are you still exploring DIND solution on azure file?
