### ISSUE TITLE
Defender for Containers not getting enabled plus default LAW created 

### ISSUE THREAD

**Issue by mezzofix** [Azure/AKS#3025]
**What happened**:
Creating an AKS cluster using az cli and the parameters --enable-defender --defender-config <path-to-JSON-file> where path-to-JSON-file points to a file with reference to an already present Log Analytics workspace in the subscription  {"logAnalyticsWorkspaceResourceID": "/subscriptions/xxxxx/resourceGroups/xxx-rsg-xxxx/providers/Microsoft.OperationalInsights/workspaces/xxxxxxxx"} results in:

a)	Defender for Containers plan not being enabled
b)	Creation of a default Log Analytics workspace 

**What you expected to happen**:

a)	Defender for Containers plan gets enabled at cluster creation time 
b)	No default Log Analytics workspace is created but instead the one that exists is used by Defender as a data pipeline to send data from the cluster to Defender for Cloud as described in https://docs.microsoft.com/en-us/azure/defender-for-cloud/defender-for-containers-enable?tabs=k8s-deploy-cli%2Ck8s-deploy-asc%2Ck8s-verify-asc%2Ck8s-remove-arc%2Caks-removeprofile-api&pivots=defender-for-container-aks#how-can-i-use-my-existing-log-analytics-workspace

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version 1.22.6

**Comment by mezzofix** [comment]
anyone ?

**Comment by miwithro** [comment]
@mezzofix This is not quite out yet, you can simply turn on Defender at the subscription level above the cluster/

**Comment by mayaherskovic** [comment]
For item a:
Creating an AKS cluster using az cli will not enable the plan, but only install the required DaemonSet on the cluster.  
The Defender for Containers plan needs to be enabled, on a subscription level, explicitly via Defender for Cloud portal or API. 
For item b:
This is shouldn't have happened. Adding @elSagie and @orparnes to look into this

**Comment by orparnes** [comment]
As for "logAnalyticsWorkspaceResourceI**d**" parameter, please use "logAnalyticsWorkspaceResourceI**d**" instead of "logAnalyticsWorkspaceResourceI**D**". We recently also updated it in the documentation.
