### ISSUE TITLE
Creation of a private AKS Cluster creates a Public IP Address.

### ISSUE THREAD

**Issue by Kronos11** [Azure/AKS#3028]
**What happened**:
in the docs it mentions that creation of a private AKS Cluster should not create a public IP Address.
**What you expected to happen**:
Creation of a private AKS Cluster creates a public IP Address resource.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the docs here to create a private cluster: https://docs.microsoft.com/en-us/azure/aks/private-clusters

**Anything else we need to know?**:
My company does not allow Public IP Address resources, therefore when I try and create a private AKS Cluster the policy prevents it from creating.
![Screen Shot 2022-06-23 at 11 44 11 AM](https://user-images.githubusercontent.com/286274/175375387-dff8dcbe-0a2d-458f-a74f-96a02a497432.png)

**Environment**:
N/A

**Comment by mezzofix** [comment]
You have to set **outboundType** to **userDefinedRouting** wen creating the cluster. Be default it is set to **loadBalancer** and will result in creation of a Azure Load Balancer with Public IP assgined to it for egress.

**Comment by neumanndaniel** [comment]
@mezzofix Already mentioned the solution. From your screenshots this is the public IP used by the load balancer to provide outbound internet. This is the standard provisioning behavior when you don't provide the `outboundType`.

**Comment by Kronos11** [comment]
thank you for the explanation, it wasn't very clear in the docs when searching for 'Public IP' for example.
Might be worth a quick update on the docs.
