### ISSUE TITLE
Remove api-resources gatekeeper  or gatekeeper-system namespace completely from Cluster

### ISSUE THREAD

**Issue by csph143** [Azure/AKS#3033]
Hi,

I am trying to remove gatekeeper api from cluster.
Removed namespace gatekeeper-system  , CRD which are related to gatekeeper.

kubectl delete crd  configs.config.gatekeeper.sh constraintpodstatuses.status.gatekeeper.sh constrainttemplatepodstatuses.status.gatekeeper.sh constrainttemplates.templates.gatekeeper.sh

kubectl delete namespace gatekeeper-system

Still it will create AUTOMATICALLY? 
How to remove completely.

Please help me.

**Comment by mezzofix** [comment]
Did you remove the Azure Policy add-on on your cluster? https://docs.microsoft.com/en-us/azure/governance/policy/concepts/policy-for-kubernetes#remove-the-add-on If not, then I can imagine that Azure will re-deploy the Azure policy / gatekeeper components.

**Comment by csph143** [comment]
Ok thanks .. I have removed add-on and now its removed gatekeeper permanently.. thanks :)

**Comment by csph143** [comment]
It works thanks
