### ISSUE TITLE
[BUG]aks 1.21.x does not support zone-redundant LB frontendip while creating k8s svc with azure internal lb

### ISSUE THREAD

**Issue by singvey999** [Azure/AKS#3035]
**Describe the bug**
Region：  China CN3
aks 1.21.9 does not support zone-redundant LB frontendip while creating k8s svc with azure internal lb
aks 1.22.6 support zone-redundant LB frontendip while creating k8s svc with azure internal lb
We need to have the aks 1.21.9 support zone-redundant LB frontendip while creating k8s svc with azure internal lb

**To Reproduce**
1. Run command '...'
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: internal-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: internal-app
EOF

2. See error
![图片](https://user-images.githubusercontent.com/19383328/176158436-9106a0e5-034f-41c1-a776-9fd854c25cc8.png)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 -  CLI Version: kubectl version is 1.24.2
 - Kubernetes version : k8s version is 1.21.9

**Additional context**

**Comment by singvey999** [comment]
Dear All,
Any update on this issue?

**Comment by alexander-vie** [comment]
I think we face the same issue with AKS 1.22.14 and existing ALB frontend configurations. kubectl describe of services with private loadbalancer IPs produce these messages permanently:
`HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {
  "error": {
    "code": "ResourceAvailabilityZonesCannotBeModified",
    "message": "Resource /subscriptions/xxx/resourceGroups/xxxx_westeurope/providers/Microsoft.Network/loadBalancers/kubernetes-internal/frontendIPConfigurations/xxxx has an existing availability zone constraint 1, 2, 3 and the request has availability zone constraint , which do not match. Zones cannot be added/updated/removed once the resource is created. The resource cannot be updated from regional to zonal or vice-versa.",
    "details": []`
along with a similar message at "UpdateLoadBalancerFailed"
We stumbled over these messages recently and I guess they came with AKS 1.22.x

**Comment by kaarthis** [comment]
Please let us know if the problem persists with a newer Kubernetes version. Happy to take a look the supported versions are 1.25, 1.26 and 1.27 presently.
