### ISSUE TITLE
AKS v.1.8.7 issue

### ISSUE THREAD

**Issue by JuneZhao** [Azure/AKS#304]
Apr 16 01:06:04 52.170.22.51 logger: <11>1 2018-04-16T01:06:04Z [] 11041 - - E0416 01:06:04.270203 11041 remote_runtime.go:262] ListContainers with filter &ContainerFilter{Id:,State:&ContainerStateValue{State:CONTAINER_RUNNING,},PodSandboxId:,LabelSelector:map[string]string{},} from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Apr 16 01:06:04 52.170.22.51 logger: <11>1 2018-04-16T01:06:04Z [] 11041 - - E0416 01:06:04.274943 11041 kuberuntime_container.go:353] getKubeletContainers failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Apr 16 01:06:04 52.170.22.51 logger: <11>1 2018-04-16T01:06:04Z [] 11041 - - E0416 01:06:04.275448 11041 kubelet_pods.go:991] Error listing containers: &status.statusError{Code:4, Message:"context deadline exceeded", Details:[]*any.Any(nil)}
Apr 16 01:06:04 52.170.22.51 logger: <11>1 2018-04-16T01:06:04Z [] 11041 - - E0416 01:06:04.276996 11041 kubelet.go:1915] Failed cleaning pods: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Apr 16 01:06:04 52.170.22.51 logger: <11>1 2018-04-16T01:06:04Z [] 11041 - - I0416 01:06:04.277802 11041 kubelet.go:1779] skipping pod synchronization - [container runtime is down]
Apr 16 01:06:04 52.170.22.51 logger: <11>1 2018-04-16T01:06:04Z [] 11041 - - E0416 01:06:04.499863 11041 remote_runtime.go:262] ListContainers with filter &ContainerFilter{Id:,State:nil,PodSandboxId:,LabelSelector:map[string]string{},} from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Apr 16 01:06:04 52.170.22.51 logger: <11>1 2018-04-16T01:06:04Z [] 11041 - - E0416 01:06:04.500933 11041 kuberuntime_container.go:353] getKubeletContainers failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Apr 16 01:06:04 52.170.22.51 logger: <11>1 2018-04-16T01:06:04Z [] 11041 - - E0416 01:06:04.501005 11041 generic.go:196] GenericPLEG: Unable to retrieve pods: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Apr 16 01:06:04 52.170.22.51 logger: <11>1 2018-04-16T01:06:04Z [] 7578 - - I0416 01:06:04.518608 7578 kubelet_node_status.go:503] Using Node Hostname from cloudprovider: "aks-nodepool1-95384353-2"
Apr 16 01:06:04 52.170.22.51 logger: <11>1 2018-04-16T01:06:04Z [] 11041 - - I0416 01:06:04.512877 11041 fsHandler.go:131] du and find on following dirs took 4.644803553s: [/var/lib/docker/overlay2/50bd575aaa51336b13c3a4d2c6d15fb96212504fd2e1872250558d90653f8023/diff /var/lib/docker/containers/6f52a1f8dea85c58b4356137bb890216cdf5708c330b3966cbac038e95b3e67c]
Apr 16 01:06:04 52.170.22.51 logger: <11>1 2018-04-16T01:06:04Z [] 11041 - - I0416 01:06:04.520491 11041 fsHandler.go:131] du and find on following dirs took 4.754902769s: [/var/lib/docker/overlay2/530baa562681a6873f09b6ec2caa8513633cac3cfccfa64b4a332c428f3302ce/diff /var/lib/docker/containers/26e74fd9567e3a0ca09991b7d9cdc1078ef2b97b73d8b136bf3c05cd8d06d67a]
Apr 16 01:06:04 52.170.22.51 logger: <11>1 2018-04-16T01:06:04Z [] 11041 - - W0416 01:06:04.647869 11041 conversion.go:110] Could not get instant cpu stats: time delta unexpectedly small
Apr 16 01:06:04 52.170.22.51 logger: <11>1 2018-04-16T01:06:04Z [] 11041 - - I0416 01:06:04.651303 11041 server.go:779] GET /stats/summary/: (1m54.501639251s) 200 [[Go-http-client/1.1] 10.244.0.5:43512]
Apr 16 01:06:04 52.170.22.51 logger: <11>1 2018-04-16T01:06:04Z [] 7601 - - I0416 01:06:04.652734 7601 kubelet_node_status.go:503] Using Node Hostname from cloudprovider: "aks-nodepool1-95384353-0"
Apr 16 01:06:04 52.170.22.51 logger: <11>1 2018-04-16T01:06:04Z [] 11041 - - I0416 01:06:04.655823 11041 kubelet_node_status.go:503] Using Node Hostname from cloudprovider: "aks-nodepool1-95384353-3"
Apr 16 01:06:05 52.170.22.51 logger: <11>1 2018-04-16T01:06:05Z [] 7578 - - I0416 01:06:05.024395 7578 server.go:779] GET /stats/summary/: (8.597174ms) 200 [[Go-http-client/1.1] 10.244.0.5:49750]
Apr 16 01:06:05 52.170.22.51 logger: <11>1 2018-04-16T01:06:05Z [] 7601 - - I0416 01:06:05.038239 7601 server.go:779] GET /stats/summary/: (31.285689ms) 200 [[Go-http-client/1.1] 10.244.0.5:40394]
Apr 16 01:06:09 52.170.22.51 logger: <11>1 2018-04-16T01:06:09Z [] 11041 - - I0416 01:06:09.281980 11041 kuberuntime_container.go:567] Killing container "docker://309f40a906b52b7a06d7aa6187679a01d460bcaa87ad518376b2cb3245351f0a" with 30 second grace period
Apr 16 01:06:09 52.170.22.51 logger: <11>1 2018-04-16T01:06:09Z [] 11041 - - I0416 01:06:09.298512 11041 kubelet.go:1853] SyncLoop (DELETE, "api"): "datasys-9f994bcd-htcdg_default(f30719eb-40b3-11e8-8079-0a58ac1f11f3)"
Apr 16 01:06:09 52.170.22.51 logger: <11>1 2018-04-16T01:06:09Z [] 11041 - - I0416 01:06:09.298614 11041 kubelet.go:1853] SyncLoop (DELETE, "api"): "datasys-9f994bcd-llgmb_default(f2fb6521-40b3-11e8-8079-0a58ac1f11f3)"
Apr 16 01:06:10 52.170.22.51 logger: <11>1 2018-04-16T01:06:10Z [] 11041 - - I0416 01:06:10.536183 11041 kuberuntime_container.go:567] Killing container "docker://ff1e7def7d8fd16896b5273421470910624882c94d6b8e1b32ff1b4ff0db1171" with 30 second grace period
Apr 16 01:06:10 52.170.22.51 logger: <11>1 2018-04-16T01:06:10Z [] 11041 - - I0416 01:06:10.536719 11041 kuberuntime_container.go:567] Killing container "docker://fe21741cccaeaa7f7789b3e0d335547dde7169127da86d796eecb7b3aaefe904" with 30 second grace period
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.548084 11041 kubelet.go:1871] SyncLoop (PLEG): "datasys-9f994bcd-llgmb_default(f2fb6521-40b3-11e8-8079-0a58ac1f11f3)", event: &pleg.PodLifecycleEvent{ID:"f2fb6521-40b3-11e8-8079-0a58ac1f11f3", Type:"ContainerDied", Data:"fe21741cccaeaa7f7789b3e0d335547dde7169127da86d796eecb7b3aaefe904"}
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.548464 11041 kubelet.go:1871] SyncLoop (PLEG): "datasys-9f994bcd-llgmb_default(f2fb6521-40b3-11e8-8079-0a58ac1f11f3)", event: &pleg.PodLifecycleEvent{ID:"f2fb6521-40b3-11e8-8079-0a58ac1f11f3", Type:"ContainerDied", Data:"3d5cd9f5046c963bf50dd09f7aab6661a0844567cbaffc51386b0454c7863c27"}
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - W0416 01:06:11.548602 11041 pod_container_deletor.go:77] Container "3d5cd9f5046c963bf50dd09f7aab6661a0844567cbaffc51386b0454c7863c27" not found in pod's containers
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.571052 11041 kubelet.go:1871] SyncLoop (PLEG): "datasys-9f994bcd-htcdg_default(f30719eb-40b3-11e8-8079-0a58ac1f11f3)", event: &pleg.PodLifecycleEvent{ID:"f30719eb-40b3-11e8-8079-0a58ac1f11f3", Type:"ContainerDied", Data:"ff1e7def7d8fd16896b5273421470910624882c94d6b8e1b32ff1b4ff0db1171"}
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.571945 11041 kubelet.go:1871] SyncLoop (PLEG): "datasys-9f994bcd-htcdg_default(f30719eb-40b3-11e8-8079-0a58ac1f11f3)", event: &pleg.PodLifecycleEvent{ID:"f30719eb-40b3-11e8-8079-0a58ac1f11f3", Type:"ContainerDied", Data:"26e74fd9567e3a0ca09991b7d9cdc1078ef2b97b73d8b136bf3c05cd8d06d67a"}
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - W0416 01:06:11.572565 11041 pod_container_deletor.go:77] Container "26e74fd9567e3a0ca09991b7d9cdc1078ef2b97b73d8b136bf3c05cd8d06d67a" not found in pod's containers
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.699192 11041 reconciler.go:186] operationExecutor.UnmountVolume started for volume "azure" (UniqueName: "kubernetes.io/azure-file/f2fb6521-40b3-11e8-8079-0a58ac1f11f3-azure") pod "f2fb6521-40b3-11e8-8079-0a58ac1f11f3" (UID: "f2fb6521-40b3-11e8-8079-0a58ac1f11f3")
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.699270 11041 reconciler.go:186] operationExecutor.UnmountVolume started for volume "default-token-lmkpt" (UniqueName: "kubernetes.io/secret/f30719eb-40b3-11e8-8079-0a58ac1f11f3-default-token-lmkpt") pod "f30719eb-40b3-11e8-8079-0a58ac1f11f3" (UID: "f30719eb-40b3-11e8-8079-0a58ac1f11f3")
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.699310 11041 reconciler.go:186] operationExecutor.UnmountVolume started for volume "default-token-lmkpt" (UniqueName: "kubernetes.io/secret/f2fb6521-40b3-11e8-8079-0a58ac1f11f3-default-token-lmkpt") pod "f2fb6521-40b3-11e8-8079-0a58ac1f11f3" (UID: "f2fb6521-40b3-11e8-8079-0a58ac1f11f3")
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.699368 11041 reconciler.go:186] operationExecutor.UnmountVolume started for volume "azure" (UniqueName: "kubernetes.io/azure-file/f30719eb-40b3-11e8-8079-0a58ac1f11f3-azure") pod "f30719eb-40b3-11e8-8079-0a58ac1f11f3" (UID: "f30719eb-40b3-11e8-8079-0a58ac1f11f3")

My AKS cluster v1.8.7 has below issue 
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.718012 11041 operation_generator.go:535] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/f2fb6521-40b3-11e8-8079-0a58ac1f11f3-default-token-lmkpt" (OuterVolumeSpecName: "default-token-lmkpt") pod "f2fb6521-40b3-11e8-8079-0a58ac1f11f3" (UID: "f2fb6521-40b3-11e8-8079-0a58ac1f11f3"). InnerVolumeSpecName "default-token-lmkpt". PluginName "kubernetes.io/secret", VolumeGidValue ""
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.718362 11041 operation_generator.go:535] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/f30719eb-40b3-11e8-8079-0a58ac1f11f3-default-token-lmkpt" (OuterVolumeSpecName: "default-token-lmkpt") pod "f30719eb-40b3-11e8-8079-0a58ac1f11f3" (UID: "f30719eb-40b3-11e8-8079-0a58ac1f11f3"). InnerVolumeSpecName "default-token-lmkpt". PluginName "kubernetes.io/secret", VolumeGidValue ""
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.755209 11041 operation_generator.go:535] UnmountVolume.TearDown succeeded for volume "kubernetes.io/azure-file/f30719eb-40b3-11e8-8079-0a58ac1f11f3-azure" (OuterVolumeSpecName: "azure") pod "f30719eb-40b3-11e8-8079-0a58ac1f11f3" (UID: "f30719eb-40b3-11e8-8079-0a58ac1f11f3"). InnerVolumeSpecName "azure". PluginName "kubernetes.io/azure-file", VolumeGidValue "" 
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.759209 11041 operation_generator.go:535] UnmountVolume.TearDown succeeded for volume "kubernetes.io/azure-file/f2fb6521-40b3-11e8-8079-0a58ac1f11f3-azure" (OuterVolumeSpecName: "azure") pod "f2fb6521-40b3-11e8-8079-0a58ac1f11f3" (UID: "f2fb6521-40b3-11e8-8079-0a58ac1f11f3"). InnerVolumeSpecName "azure". PluginName "kubernetes.io/azure-file", VolumeGidValue ""
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.799654 11041 reconciler.go:290] Volume detached for volume "default-token-lmkpt" (UniqueName: "kubernetes.io/secret/f2fb6521-40b3-11e8-8079-0a58ac1f11f3-default-token-lmkpt") on node "aks-nodepool1-95384353-3" DevicePath ""
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.799790 11041 reconciler.go:290] Volume detached for volume "azure" (UniqueName: "kubernetes.io/azure-file/f30719eb-40b3-11e8-8079-0a58ac1f11f3-azure") on node "aks-nodepool1-95384353-3" DevicePath ""
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.799839 11041 reconciler.go:290] Volume detached for volume "azure" (UniqueName: "kubernetes.io/azure-file/f2fb6521-40b3-11e8-8079-0a58ac1f11f3-azure") on node "aks-nodepool1-95384353-3" DevicePath ""
Apr 16 01:06:11 52.170.22.51 logger: <11>1 2018-04-16T01:06:11Z [] 11041 - - I0416 01:06:11.799864 11041 reconciler.go:290] Volume detached for volume "default-token-lmkpt" (UniqueName: "kubernetes.io/secret/f30719eb-40b3-11e8-8079-0a58ac1f11f3-default-token-lmkpt") on node "aks-nodepool1-95384353-3" DevicePath "" 

- kubectl get nodes
Unable to connect to the server: dial tcp 104.196.96.28:443: i/o timeout

- kubectl get pods
Unable to connect to the server: dial tcp 104.196.96.28:443: i/o timeout

Any reason, the service deployed are not accissble.

**Comment by andyzhangx** [comment]
The provided logs are kubelet logs?
your api-server is down, could you run `docker ps -a` and then get api-server logs, could follow by: https://github.com/andyzhangx/demo/tree/master/debug#q-how-to-get-k8s-component-logs-on-master

and you may also check system load average by run `top`, if `load average` is bigger than 2, it means high load.

**Comment by JuneZhao** [comment]
@andyzhangx, this is AKS cluster which means I dont have access the master node, how would I docker ps -a?

**Comment by andyzhangx** [comment]
ah, you are right, then you may file an issue to AKS support...

**Comment by slack** [comment]
Closing as this should be a support ticket.
