### ISSUE TITLE
Create or Update Managed Cluster

### ISSUE THREAD

**Issue by csph143** [Azure/AKS#3042]
Hi All,

We are managing production cluster, on Mon Jun 27 2022 AKS cluster all Linux nodes got upgraded from 2022.03.02 to 2022.06.08, without knowing us. Due to this all nodes got rebooted and it disturb our entire operation.
See linked attachment for your reference.

Can I know how it happened? (manual or some background operation)
Is there any way to avoid in future?
What precaution we can take, so that we will aware when something happened?
Please help me.
![image](https://user-images.githubusercontent.com/28288762/176422983-b1f051ae-58d1-4643-ac86-18de31afdc41.png)

AKSUbuntu-1804gen2containerd-2022.03.02 upgraded to AKSUbuntu-1804gen2containerd-2022.06.08

**Comment by allyford** [comment]
Duplicate issue, see #3041
