### ISSUE TITLE
AKS not creating AGIC[BUG]

### ISSUE THREAD

**Issue by WaitingForGuacamole** [Azure/AKS#3043]
**Describe the bug**
I'm attempting to create an AKS cluster, with AKS creating the AGIC, using a name I specify, in a subnet that's already created in my VNet. It's never created, giving me a message saying that the gateway could take up to 15 minutes to create. Several days later it's still not created.

**To Reproduce**
My AKS definition in Terraform includes:

```
  network_profile {
    network_plugin     = "azure"
    network_policy     = "azure"
    docker_bridge_cidr = var.kubernetes_docker_bridge_cidr
    service_cidr       = var.kubernetes_service_cidr
    dns_service_ip     = var.kubernetes_dns_service_ip
    load_balancer_sku  = var.load_balancer_sku

    load_balancer_profile {
      managed_outbound_ip_count = 1
    }
  }

  identity {
    type         = "UserAssigned"
    identity_ids = [var.managed_identity_id]
  }

  auto_scaler_profile {
    expander = "least-waste"
  }

  linux_profile {
    admin_username = var.vm_admin_username

    ssh_key {
      key_data = module.vm_key_pair.pair_key_pub_value_openssh
    }
  }

  # Subnet exists, App GW does not, I want AKS to create the AGIC for me
  ingress_application_gateway {
    subnet_id    = var.application_gateway_subnet_id
    gateway_name = "appgw-${local.project_environment}"
  }

  azure_active_directory_role_based_access_control {
    managed            = true
    azure_rbac_enabled = true
  }

  microsoft_defender {
    log_analytics_workspace_id = var.log_analytics_workspace_id
  }

  oms_agent {
    log_analytics_workspace_id = var.log_analytics_workspace_id
  }
```

**Expected behavior**
AGIC is created.

**Screenshots**
![AGIC fail](https://user-images.githubusercontent.com/11178016/176535517-9c75a1ae-e18b-45fc-81fb-05b8027a91d8.png)

**Environment (please complete the following information):**
 -  CLI Version => 2.37.0
 - Kubernetes version 1.23.5

**Additional context**
Applied steps at https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-install-existing to see if that would jump-start things. It didn't. Probably because it doesn't exist.

EDIT: Changed title to remove Terraform, as the portal gives you no way of linking an existing subnet to the App Gateway, which I need - this is a subnet in a virtual network spoke, attached to a VWAN/Secure Virtual Hub.

**Comment by WaitingForGuacamole** [comment]
Additional detail. I unchecked and saved the AGIC option in the portal. I then recreated in Terraform using just the subnet ID. Same result, so it's not the name.

**Comment by JackStromberg** [comment]
Hello @waitgingforguacamole -- can you please open a support request so we can investigate the specific deployment? Deployment into a peered virtual network is fully supported, whether that peering is to VWAN or another Virtual Network.

One item that may be a factor however is if you are advertising the default route through virtual wan, that may be affecting communication to Application Gateway's control plane.  Be sure to have a [route table on the subnet](https://learn.microsoft.com/azure/application-gateway/configuration-infrastructure#supported-user-defined-routes) that Application Gateway will deploy to that allows outbound traffic to the internet.  Alternatively, you can try enabling the new [private application gateway preview feature](https://learn.microsoft.com/azure/application-gateway/application-gateway-private-deployment?tabs=portal) on your subscription (even if the intent is public internet ingress), which eliminates the need for inbound/outbound communication to the control plane publicly).

Hope this helps!
Jack

**Comment by sabbour** [comment]
Closing as per this.

> Hello @WaitingForGuacamole -- can you please open a support request so we can investigate the specific deployment? Deployment into a peered virtual network is fully supported, whether that peering is to VWAN or another Virtual Network.

If this is still an issue, please open a support request to investigate further.
