### ISSUE TITLE
AKS ingress-nginx can't provision a LoadBalancer public IP(y.y.y.y) which is a static IP configured

### ISSUE THREAD

**Issue by Sanghamitra-PERSONAL** [Azure/AKS#3046]
**What happened:**
I reinstalled the **ingress-nginx** Helm chart in  AKS cluster but it's forever stuck in pending state:
`ingress-nginx-controller             LoadBalancer   a.a.a.a   <pending>     80:30924/TCP,443:31680/TCP   16m`

The above issue is because : 
`Warning  SyncLoadBalancerFailed  3m16s (x9 over 18m)  service-controller  Error syncing load balancer: failed to ensure load balancer: findMatchedPIPByLoadBalancerIP: cannot find public IP with IP address y.y.y.y in resource group rg1

**Environment:**
AKS Kubernetes version (use kubectl version): 1.23.5

**What you expected to happen:**
I expect this service  LoadBalancer to get the static public IP which I have assigned.

**Is this issue because of the current Azure issue going on ?** 

<img width="829" alt="image" src="https://user-images.githubusercontent.com/78498010/176656915-3b7bf99d-f381-4250-b4bf-2f627e6d38f7.png">

**Comment by antoineozenne** [comment]
Same issue for us.

**Comment by sabbour** [comment]
Are you still facing this issue?

**Comment by FlorentATo** [comment]
I faced the same issue when reinstalling the [nginx ingress controller](https://kubernetes.github.io/ingress-nginx/) on the default AKS ingress public IP.

When configuring the ingress controller, you have to specify the resource group where the loadbalancer is located, using the annotation `service.beta.kubernetes.io/azure-load-balancer-resource-group` ([ref.](https://learn.microsoft.com/en-us/azure/aks/load-balancer-standard#customizations-via-kubernetes-annotations))

By default, this loadbalancer is located in the **Infrastructure** resource group of the cluster (prefixed with `MC_`). However, the default public IP (defined at the cluster creation) is in the cluster's resource group, not the cluster's infrastructure resource group.

Fix: Move the default public IP of the cluster into the cluster's infrastructure resource group.

**Comment by CocoWang-wql** [comment]
Add an annotation here:
AKS supports attaching the public IP in the non-infrastructure resource groups.  We need to add an annotation:
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: <resource group name>

Reference: https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/aks/static-ip.md#create-a-service-using-the-static-ip-address
