### ISSUE TITLE
[BUG] Cannot configure nf_conntrack_max via Customize node configuration 

### ISSUE THREAD

**Issue by ivanthelad** [Azure/AKS#3051]
**Describe the bug**
Setting the nf_conntrack_max via the custom [node configuration](https://docs.microsoft.com/en-us/azure/aks/custom-node-configuration#socket-and-network-tuning) has no effect and is not applied to file 
 /proc/sys/net/netfilter/nf_conntrack_max. 

Whats observed is the value "netNetfilterNfConntrackMax" is applied to the cloud init setup under the file /etc/sysctl.d/999-sysctl-aks.conf on each node but seems to get overwritten by the kubelet/kube proxy with the value (**32768* Cores**). 

**To Reproduce**
1. Run command '...'
2. See error

**Expected behavior**
**Create Cluster .**
`az aks create --name $NAME --resource-group $RESOURCE_GROUP --linux-os-config ./linux.os.json  --kubelet-config ./kublet.json`

**./kublet.json**
`{

    "sysctls": {
     "netCoreSomaxconn": 163849,
     "netIpv4TcpTwReuse": true,
     "netIpv4IpLocalPortRange": "32000 60000",
     "netNetfilterNfConntrackMax": 1048576

    }
   }
`
**./linux.os.json**  
`
{
 "cpuManagerPolicy": "static",
 "cpuCfsQuota": true,
 "cpuCfsQuotaPeriod": "200ms",
 "imageGcHighThreshold": 90,
 "imageGcLowThreshold": 70,
 "topologyManagerPolicy": "best-effort",
 "allowedUnsafeSysctls": [
  "kernel.msg*",
  "net.*",
  "net.netfilter.nf_conntrack_max"
],
 "failSwapOn": false
}
`
Verify change 
`
kubectl debug node/NODE_NAME-it --image=mcr.microsoft.com/dotnet/runtime-deps:6.0 -- bash
chroot /host
cat /proc/sys/net/netfilter/nf_conntrack_max
`

**Environment 
❯ az --version
azure-cli                         2.37.0

core                              2.37.0
telemetry                          1.0.6

Extensions:
connectedk8s                       1.2.8
azure-devops                      0.25.0
k8s-extension                      1.2.3
aks-preview                       0.5.76
resource-graph                     2.1.0
application-insights              0.1.16
appservice-kube                    0.1.6
k8s-configuration                  1.5.1
customlocation                     0.1.3

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/ivan/.azure/cliextensions'

Python (Linux) 3.10.4 (main, May 23 2022, 14:03:08) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Additional context**
setting nf_conntrack_max via sysctls on pod securitycontext spec has no effect as setting is not namespaced

**Comment by ivanthelad** [comment]
Workaround is to deploy a daemonset to configure this . 
 
`apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: conntrack-modifier
  name: conntrack-modifier
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: conntrack-modifier
      tier: node
  template:
    metadata:
      labels:
        component: conntrack-modifier
        tier: node
    spec:
      containers:
      - name: conntrack-modifier
        image: alpine
        imagePullPolicy: IfNotPresent
        command:
          - nsenter
          - --target
          - "1"
          - --mount
          - --uts
          - --ipc
          - --net
          - --pid
          - --
          - sh
          - -c
          - |
            echo "<value>" > /proc/sys/net/netfilter/nf_conntrack_max
        resources:
          requests:
            cpu: 10m
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirst
      hostPID: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      restartPolicy: Always
  updateStrategy:
    type: OnDelete
`

**Comment by rouke-broersma** [comment]
@wangyira hi sorry but why did you mark this as resolved? The api is broken, it does not actually apply the setting.

**Comment by n-pedersen** [comment]
This issue should not be closed, it's still an issue.

**Comment by maartengo** [comment]
This issue is still relevant, and not yet resolved

**Comment by n-pedersen** [comment]
Hi,
It's not resolved.

**Comment by ivanthelad** [comment]
@phealy this issue has not been resolved right? customers still need to use a custom daemonset to set maxconn

**Comment by phealy** [comment]
@n-pedersen @maartengo @ivanthelad This should have been resolved around the middle of August. What behavior are you seeing now? If you look at your kube-proxy DaemonSet, you should see an initcontainer that sets the value appropriately on startup.

**Comment by rouke-broersma** [comment]
I think we might be mistakingly thinking this issue is the same as https://github.com/Azure/AKS/issues/3160 which has not been resolved.

**Comment by ivanthelad** [comment]
> ad practice

@phealy  this is just a followup as the item is still open. we have not retested this again.  
@rouke-broersma  this issue is nothing related to bicep but more a configuration been overwriten by the kublet

**Comment by alexeldeib** [comment]
https://github.com/Azure/AKS/issues/3160#issuecomment-1274781494 as ref

**Comment by alexeldeib** [comment]
kube proxy issue should be fixed
