### ISSUE TITLE
Azure File CSI Driver will not dynamically allocate persistent volume in existing storage account when using private end point

### ISSUE THREAD

**Issue by kkizer** [Azure/AKS#3052]
**What happened**:
The [Azure File CSI driver](https://github.com/kubernetes-sigs/azurefile-csi-driver) is not able to dynamically allocate a persistent volume given the following set up:
- Existing storage account only allows access using a private end point. NO public access to the storage account because our corporate security policies forbid public access: storage accounts may only be accessed using private end points on our private VNET.
- The AKS cluster's management service principal is NOT granted RBAC access to the storage account. In our environment the same service principal is used for multiple clusters so we cannot grant access to the storage account. That would allow applications access to data for different applications.
- The Kubernetes Storage Class is configured with parameters that specify Kubernetes secrets that contain the access key for the storage account.

When the File CSI driver attempts to allocate the persistent volume, it fails with a 403 error:
```
  Type     Reason                Age               From                                                                                               Message
  ----     ------                ----              ----                                                                                               -------
  Warning  ProvisioningFailed    19s               file.csi.azure.com_csi-azurefile-controller-858ff9bcff-nzk57_230e4679-85fb-40a3-a02f-36c9129ce516  failed to provision volume with StorageClass "azurefile-csi-elb": rpc error: code = Internal desc = storage: service returned error: StatusCode=403, ErrorCode=403 This request is not authorized to perform this operation., ErrorMessage=no response body was available for error status code, RequestInitiated=Wed, 08 Jun 2022 19:22:11 GMT, RequestId=96bce511-301a-002a-606d-7b77e7000000, API Version=, QueryParameterName=, QueryParameterValue=
```

**What you expected to happen**:

1. A new file share should have been created in the storage account.
2. Persistent volume claim should have been satisfied allowing the test application to run.
3. When persistent volume claim is released, the dynamically allocated file share should be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a storage account with a private end point. Do NOT allow public access. The only network access is via the private end point.
2. Create an AKS cluster at the latest GA release.
3. Create a secret in the cluster that contains the storage account's access key. Sample app expects a secret named azure-secret in the default namespace. See [Option#2: bring your own storage account (only for SMB protocol)](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-bring-your-own-storage-account-only-for-smb-protocol).
4. Create the StorageClass using the attached YAML file.
5. Create the sample StatefulSet using the attached YAML file.

**Anything else we need to know?**:
We were told that this behavior is "working as designed""

> When using secrets (storage account name & key), means that the data plane API will be used to create azure file share, and when storage account public access is not allowed, data plane API would not work, only management API would work, which is the case when you don’t provide secret, that is using management API.
>
> This would be by design since providing secret means the driver should use data plane API, and it’s blocked by network access policy.

However, this scenario should be supported.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.23.5
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.). No workload since it is a test cluster. Only the sample application was deployed
- Others:

Kevin Kizer
Lead Engineer
MetLife
[statefulset-nginx.zip](https://github.com/Azure/AKS/files/9028673/statefulset-nginx.zip)

**Comment by andyzhangx** [comment]
yes, data plane API(using account key directly) is still blocked when using advanced networking in azure file account, while using management API works. Wil check with azure file team, whether support data plane API in advanced networking is in their plan, stay tuned.

**Comment by andyzhangx** [comment]
azure file team's response:
By design, when a customer puts a network restriction in place, data plane APIs are restricted, inclusive of legacy management APIs exposed via data plane. If the customer doesn’t want this configuration, they have the option not to. We must respect and uphold the user’s network configuration, and we can’t and won’t make hidden exceptions for the legacy management APIs.

**Comment by andyzhangx** [comment]
let me know if you have any question.

**Comment by kkizer** [comment]
I do not find this acceptable. We HAVE allowed access to the storage account via the private end point. Access to all networks should not be required. I have already dealt with MSFT support and opened a support ticket with them. They agree that this is a valid scenario and should be supported.
