### ISSUE TITLE
Support Third Party Certificates or a real certificate at azmk8s.io

### ISSUE THREAD

**Issue by IanMoroney** [Azure/AKS#306]
Feature request:

Our Kubernetes clusters are being flagged by our security software for having self-signed certificates and blocking the clusters.

Please allow us to either use our own certificate, or have a valid certificate on azmk8s.io just like you do for azurewebsites.net

**Comment by hibri** [comment]
This hit us as well. Out of interest @IanMoroney what security software was flagging this up?

**Comment by sdktr** [comment]
Having the same issue, OpenDNS kicks in for every new cluster created

**Comment by jnoller** [comment]
Closing as solved/stale
