### ISSUE TITLE
[Question] How to use the newer one of multiple versions of a pre-pulled containerd image?

### ISSUE THREAD

**Issue by kaiffeetasse** [Azure/AKS#3065]
**Describe scenario**
We have an AKS cluster with the following configuration:

Kubernetes version: 1.24.0
Node image version: AKSUbuntu-1804gen2containerd-2022.06.22

Network profile
Type (plugin): Azure CNI
Network policy: Calico

tl;dr: We want to use Calico v3.23.1.

We want to encrypt our in-cluster pod traffic by enabling Calico Wireguard. However, due to [this bug](https://github.com/projectcalico/calico/issues/5125) in Calico we temporarily disabled Wireguard in our cluster. This bug now seems to be [fixed](https://github.com/projectcalico/calico/pull/5607) in [Calico Release v3.22.1](https://github.com/projectcalico/calico/releases/tag/v3.22.1) ([Release notes](https://projectcalico.docs.tigera.io/archive/v3.22/release-notes/)) and therefore we would like to upgrade Calico to the newest available version in Azure, which will include this fix. Currently, according to the [AKS release notes](https://github.com/Azure/AKS/releases), all Calico components in the [Ubuntu 18.04 image](https://github.com/Azure/AKS/blob/2022-06-26.1/vhd-notes/aks-ubuntu/AKSUbuntu-1804/2022.06.22.txt) are provided in the following 2 versions:

- v3.21.4
- v3.23.1

If we now create a new AKS cluster with the above config, Calico is automatically deployed in version v3.21.4. 

**Question**
How can we use the newer one of the two versions provided by Azure (v3.23.1)?

**Comment by Cloud5000** [comment]
Bug is already fixed in v3.21.5. We would even prefer this patch over minor version upgrade.

**Comment by 2b33rs** [comment]
I'm having the same problem, are there any updates on this?
