### ISSUE TITLE
how to get redhat based nodepools in AKS

### ISSUE THREAD

**Issue by vivuu1989** [Azure/AKS#3066]
In Aks,the nodepools are coming with Ubuntu based images by-default, whereas our applications are using the base image is based on debian. 

So we are planning to use the nodepools provisioned with the redhat based images as these are licensed os images. So will this possible to use redhat based nodepools in AKS cluster for both system and user pools.

**Comment by andyzhangx** [comment]
that's Azure OpenShift: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/openshift-get-started, we don't support adding a new RedHat nodepool on AKS
