### ISSUE TITLE
[Question] Upgrade to 1.23.6

### ISSUE THREAD

**Issue by clglavan** [Azure/AKS#3071]
**Describe scenario**
Hello, we are experiencing issues related to scheduling as described in :
https://github.com/kubernetes/kubernetes/issues/107679
https://github.com/kubernetes/kubernetes/issues/106884

The fix seems to be in 1.23.6 - https://github.com/kubernetes/kubernetes/issues/106884#issuecomment-1118804570

**Question**

In AKS we see only 1.23.5, is 1.23.6 on the roadmap?

**Comment by clglavan** [comment]
From what I can read in 
```
> az aks get-versions --location eastus --output table

KubernetesVersion    Upgrades
-------------------  -----------------------
1.24.0(preview)      None available
1.23.5               1.24.0(preview)
1.23.3               1.23.5, 1.24.0(preview)
1.22.6               1.23.3, 1.23.5
1.22.4               1.22.6, 1.23.3, 1.23.5
1.21.9               1.22.4, 1.22.6
1.21.7               1.21.9, 1.22.4, 1.22.6
```
I understand that the next update is 1.24.0, is there a way to go to 1.23.6 instead?

**Comment by joaguas** [comment]
hi @clglavan 

AKS latest release is deprecating 1.23.3 and introducing 1.23.8.
You can check AKS release notes at https://github.com/Azure/AKS/releases and keep track of release by version at https://releases.aks.azure.com/webpage/index.html#tabversion

**Comment by clglavan** [comment]
Thank you very much for the explanation and links!
