### ISSUE TITLE
Azure file aks with Wordpress+mariadb helm crashing

### ISSUE THREAD

**Issue by ojordano** [Azure/AKS#3073]
**What happened**:

I have an AKS cluster running; trying to deploy wordpress+mariadb using helm chart  with persistence volume from Azure file. But the mariadb pod is failing with CrashLoopBackOff status.

The error returned from log is : 

**[Warning] InnoDB**: Retry attempts for writing partial data failed.
**[ERROR] InnoDB**: Write to file ./ibdata1 failed at offset 0, 1048576 bytes should have been written, only 0 were written. Operating system error number 22. Check that your OS and file system support files of this size. Check also that the disk is not full or a disk quota exceeded.
**[ERROR] InnoDB**: Error number 22 means 'Invalid argument'
**[ERROR] InnoDB**: Could not set the file size of './ibdata1'. Probably out of disk space
**[ERROR] InnoDB**: Database creation was aborted with error Generic error. You may need to delete the ibdata1 file before trying to start up again.
**[ERROR] Plugin** 'InnoDB' init function returned error.
**[ERROR] Plugin** 'InnoDB' registration as a STORAGE ENGINE failed.
**[ERROR] Unknown/unsupported storage engine**: InnoDB
**[ERROR]** Aborting

**Anything else we need to know?**:

I created storage class and claim following below micorsoft documentation:

https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv
 
**Environment**:
- Kubernetes version : 1.22.6

Any help is appreciated. thanks

**Comment by andyzhangx** [comment]
@ojordano could you use azure disk for mariadb, and use azure file nfs for wordpress pod would also help: https://docs.microsoft.com/en-us/azure/aks/azure-files-csi#create-nfs-file-share-storage-class

**Comment by ojordano** [comment]
@andyzhangx , Hello, thank you for your feedback.

For my own information, just want to know why Azure file can not work for mariadb pod...

Structurized data purpose ???

**Comment by andyzhangx** [comment]
I think that's related to smb protocol, not Unix compatible.

**Comment by ojordano** [comment]
> I think that's related to smb protocol, not Unix compatible.

Ok fine, thank for your kind support

**Comment by andyzhangx** [comment]
https://github.com/Azure/AKS/issues/223#issuecomment-1378546429
for the wordpress like scenario, pls try with azurefile-csi-nfs storage class on AKS, the wordpress application could be set up within 5min, below are the commands:
```
kubectl apply -f https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/storageclass-azurefile-nfs.yaml
helm install --set persistence.storageClass="azurefile-csi-nfs" stable/wordpress --generate-name
```
