### ISSUE TITLE
How to obtain the token controller public key (sa.pub) of an AKS cluster?

### ISSUE THREAD

**Issue by Ziphone** [Azure/AKS#3076]
**Describe scenario**
I have a workload that needs to do signature validation of service account tokens from a certain AKS cluster. The workload needs the sa.pub of the AKS cluster as the workload does not have access to the AKS API server (and the TokenReview API).

By sa.pub I mean the public key of the token controller [1], also referred here [2].

**Question**
How do I retrieve the sa.pub of an AKS cluster? And is there any rotation policy for the public key of the token controller?

1 - Kubernetes Token Controller - https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#token-controller
2 - Kubernetes PKI - https://kubernetes.io/docs/setup/best-practices/certificates/

**Comment by wangyira** [comment]
@miwithro @CocoWang-wql

**Comment by Ziphone** [comment]
Closing the issue as the OIDC Issuer feature is now in GA.
