### ISSUE TITLE
Kubelet log in to ACR by using AKS service principal  

### ISSUE THREAD

**Issue by andresguisado** [Azure/AKS#308]
An AKS cluster and ACR have been created by the same service principal and kubelet is able to log in successfully to ACR to pull a container image which is ok.

However, just curious,  Could anybody please explain the workflow of how kubelet has access to this service principal to log in to ACR?

Thank you!

**Comment by andyzhangx** [comment]
related code is under here:
https://github.com/kubernetes/kubernetes/blob/5dde701b876d1d0915314c3ed146e986c4327f7e/pkg/credentialprovider/azure/azure_credentials.go#L159-L162

It's using service principle to set `DockerConfigEntry`
