### ISSUE TITLE
az aks create: Operation failed with status: 200. Details: Resource state Failed

### ISSUE THREAD

**Issue by Zimmergren** [Azure/AKS#309]
Today I've noticed another glitch when creating a new AKS cluster in WEU. 

I create a new cluster using Standard_A4m_v2 machines like this:
```
az aks create -g rg-weu-testaks-a4mv2 -n rg-weu-testakscluster-a4mv2 --kubernetes-version "1.9.6" --node-vm-size Standard_A4m_v2
```

I end up having this issue:
```
Deployment failed. Correlation ID: 474be2bb-e421-472e-a013-dc4f3d901c4a. Operation failed with status: 200. Details: Resource state Failed
```

I have not opened a support ticket for it, as it would cost me quite some credits to keep my nodes running for a cluster that is broken from start.

**Comment by dhrp** [comment]
Colleagues of mine and I are having trouble with creating clusters as well Europe West. Using UI

**Comment by Zimmergren** [comment]
@dhrp since the last two days I've seen major issues with creating new resources, and with scaling existing clusters in WEU. Both from the UI, APIs, and CLI.

**Comment by aevitas** [comment]
@Zimmergren Same here, I am currently unable to access the k8s API altogether, let alone create any additional resources.

**Comment by HaikoHertes** [comment]
Same over here. I'm not able to create a AKS cluster with 3x B1ms VMs via ARM. Tried it 3 times...

I get:

AzureContainerService
Error code
InvalidTemplateDeployment
Message
The template deployment 'IDENTIFIER' is not valid according to the validation procedure. The tracking id is 'IDENTIFIER'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.

**Comment by ThorstenHans** [comment]
@Zimmergren we ran into the same issues by the beginning of last week. Issues were luckily gone by Friday evening :D had to spin up an AKS on Saturday for GlobalAzure.

Tried it also today with `az aks create ...` works like a charme

**Comment by Zimmergren** [comment]
Yep @ThorstenHans, looks like all issues on my end have vanished since a couple of days as well. I've stood up quite a few new clusters since without problems. As long as I target the latest version during creation, issues doesn't seem to appear.

**Comment by aidancbrady** [comment]
Just ran into this issue while trying to create a cluster in East US. Seems to happen sporadically.

**Comment by mboersma** [comment]
I'm not aware of a general issue like this since AKS was made generally available. @Zimmergren if you still see problems like this, could you please send details and subscription ID, Azure region, resource group name, and cluster name to aks-help@service.microsoft.com?

**Comment by joergkrause** [comment]
If one comes by this just an experience that might help others: After creating it takes up to 20 mins until all services are available. In that time the above error occurs (not "creating" or something, but really "failed"). After waiting a significant amount of time and trying to re-connect it works as expected.
