### ISSUE TITLE
Helm upgrade getting failed when added the containerResource Metrics to the HPA configuration

### ISSUE THREAD

**Issue by vivuu1989** [Azure/AKS#3090]
we are using HPA api version  **"apps/v1"** and deployment api version is **"apps/v1"**.

Our AKS version 1.22.6 and we have added the HPA metrics for the "**containerResource**" recently in addition to the pod metrics as given below. But after that when we tried for the helm upgrade for the releases, the releases getting failed with an error saying that 

    "UPGRADE FAILED: cannot patch "my-app" with kind HorizontalPodAutoscaler: HorizontalPodAutoscaler.autoscaling "my-app" is invalid: spec.metrics[0].containerResource: Required value: must populate information for the given metric source (only allowed when HPAContainerMetrics feature is enabled)"

HPA property added

 

    {{- if eq .Values.hpa.targetResource "pod" }}
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: {{ .Values.hpa.autoscale.cpuAverageUtilization | default "50" }}
      {{- end }}
      {{- if eq .Values.hpa.targetResource "container" }}
      metrics:
      - type: ContainerResource
        containerResource:
          name: cpu
          container: {{ $.Release.Name }}
          target:
            type: Utilization
            averageUtilization: {{ .Values.hpa.autoscale.cpuAverageUtilization | default "50" }}
      {{- end }}

So when we searched over internet to get succeed the Helm release upgrade,  we need to recreate the cluster by enabling the feature "HPAContainerMetrics".
Its strange that we cant directly enable this feature in existing AKS cluster. 

Any guidance on this?

**Comment by vivuu1989** [comment]
Any help on this ?

**Comment by sanglt** [comment]
This metric is from HPAContainerMetrics, which is still alpha feature: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features

I don't think AKS allow to use Alpha features yet. You can monitor to https://github.com/Azure/AKS/issues/2058 issue.

In the mean time, you need to change your HPA metric to Resource, not ContainerResource.
