### ISSUE TITLE
[Question] Issues removing built-in storage classes

### ISSUE THREAD

**Issue by audunsolemdal** [Azure/AKS#3098]
**Describe scenario**

AKS version: 1.22.11

I am trying to remove storageclasses that come out of the box on my AKS clusters, and rather use ones I have created myself. However, once I delete them, they quickly come back.
The clusters are created through Terraform with the azurerm_aks_cluster resource.

```
kind: StorageClass
metadata:
  creationTimestamp: "2022-07-21T06:50:11Z"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: azurefile-csi
  resourceVersion: "117671571"
  uid: a265721e-bd44-4656-bc42-411a1ece396f
mountOptions:
- mfsymlinks
- actimeo=30
parameters:
  skuName: Standard_LRS
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Question**
I noticed the label `addonmanager.kubernetes.io/mode: EnsureExists` and I am not sure where this originates from. Is this expected default behavior from AKS clusters, or is this terraform specific? How would I go about getting rid of them permanently?

**Comment by andyzhangx** [comment]
@audunsolemdal you could delete the built-in sc and create one immediately, and `addonmanager.kubernetes.io/mode: EnsureExists` only ensures sc exists.

**Comment by audunsolemdal** [comment]
What if I want to get rid of the storage class permanently, not possible?

**Comment by andyzhangx** [comment]
> What if I want to get rid of the storage class permanently, not possible?
> 
> I have created custom storage classes with other names already. My understanding is that the label ensures a storage class with the exact name "azurefile-csi" exists. I have about 8 built-in storage classes which I would like to delete permanently

@audunsolemdal the only way to get rid of built-in storage classes is disabling the csi driver
