### ISSUE TITLE
Question: What is the SSH key used for on managed AKS?

### ISSUE THREAD

**Issue by adhodgson1** [Azure/AKS#31]
Hi all,

I realise that on ACS the SSH key is used to login to the VMS themselves and perform operations on the VMS.  However with managed AKS what is the SSH key used for?  If it is used to log into the agents, what operations is it safe to perform on the agent hosts?

Thanks.
Andrew.

**Comment by mboersma** [comment]
@adhodgson1 as you guessed, the `--ssh-key-value` is used for authentication for secure shells on AKS node VMs, just as in ACS.

As far as what operations are safe on agent VMs once logged in...you could certainly cause yourself problems by stopping essential systemd services like `docker` or `kubelet`, but routine maintenance tasks are probably fine. Sorry I can't be more specific there--we may need to create some documentation clarifying what maintenance and troubleshooting operations are expected and safe for users to perform.

**Comment by slack** [comment]
Closing this issue, let me know if you have further questions!
