### ISSUE TITLE
Adding an AKS node pool with the new A10 GPU [Question] 

### ISSUE THREAD

**Issue by rogelioamancisidor** [Azure/AKS#3104]
**Describe scenario**
I am trying to add a node pool that uses the new (1/3 of) A10 GPU in `west europe`. I use this command

    az aks nodepool add --resource-group myrscgrp --cluster-name mycluster --name a10gpu --node-count 1 --node-vm-size standard_nv12ads_a10_v5 --mode user

**Question**
I get this error message

    (ReconcileVMSSAgentPoolFailed) We are unable to serve this request due to an internal error, Correlation ID: c699b28b-de69-410d-a11f-dc18cd8668b2, Operation ID: c9357124-3b50-41a8-af19-973b2639ebbf, Timestamp: 2022-07-27T07:01:17Z.
    Code: ReconcileVMSSAgentPoolFailed
    Message: We are unable to serve this request due to an internal error, Correlation ID: c699b28b-de69-410d-a11f-dc18cd8668b2, 
    Operation ID: c9357124-3b50-41a8-af19-973b2639ebbf, Timestamp: 2022-07-27T07:01:17Z.
    
I can add node pools with any other types of VMs. The above error only happens with the new A10 GPU.

Do I need to take care of something in particular to add nodes with the A10 GPU, or why am I getting the above error message?

**Comment by alexeldeib** [comment]
we unblocked this, but note that AKS does not currently install GRID drivers, only CUDA drivers, so you would need to do that your own right now. something we are looking at in the future.

**Comment by rogelioamancisidor** [comment]
@alexeldeib  where do I find the instructions to install GRID drivers? I tried to ping into the SKU using
```
kubectl exec --stdin --tty container_name -- /bin/bash
```
and then followed this instructions [link](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/n-series-driver-setup) but it did not work.

**Comment by alexeldeib** [comment]
we install the drivers now, would mark this as resolved. 

the steps you shared sound reasonable, but without details/an error, hard to debug :)

**Comment by rogelioamancisidor** [comment]
@alexeldeib  Do I need to create the DaemonSet again? or your solution only works using the AKS GPU image?
