### ISSUE TITLE
[Feedback] An unsupported scenario for the custom CA in-preview feature while using the custom proxy.

### ISSUE THREAD

**Issue by RolandlinAKS** [Azure/AKS#3106]
**Describe your scenario**
I have a concern about bellow custom CA in-preview feature:
https://docs.microsoft.com/en-us/azure/aks/custom-certificate-authority
There is a scenario that customer already has an existing AKS cluster with the UDR. The default traffic will be routed to a custom proxy, which will have the TLS offloading. In this scenario, customer needs to make the AKS nodes recognize the custom proxy certificate. Custom CA is saved in AKS cluster as a k8s secret.
Now, customer would like to create a new AKS node in the existing cluster. Sometimes, the k8s binary is not included in the node image, thus a download is required with below command for example:
curl -fsSL https://acs-mirror.azureedge.net/kubernetes/v1.22.4-hotfix.20220201/binaries/kubernetes-node-linux-amd64.tar.gz -o /tmp/kubernetes-node-linux-amd64.tar.gz
This curl command is failed with below error:
curl: (60) SSL certificate problem: unable to get local issuer certificate
This problem is caused due to the mismatching TLS proxy certificate. Since the VMSS instance is cloud-init and install k8s components with CSE before the AKS node is ready. We cannot define the custom CA before the AKS node is successfully created.

**Feedback**
In my mentioned scenario, the node creation is failed every time customer would like to create a new AKS node. AKS will get stuck in a 'updating' status for several hours long until it reaches the max retry and RP reset the cluster status as 'failed'. The workaround is to change the custom CA in the 'failed' nodes, and reconcile the node pool. However, this workaround is time-consuming and cannot compatible with the cluster autoscaler.
Do we have any solution for this problem?

**Comment by alexeldeib** [comment]
we're working on a fix for this. TLS trust will be established before any network connections and we won't rely on a k8s secret. it will take some time still. cc @utheman

**Comment by RolandlinAKS** [comment]
Thank you @alexeldeib for reviewing this issue.
