### ISSUE TITLE
[BUG] ACR integration : 401 Unauthorized after 1 year working

### ISSUE THREAD

**Issue by SchroterQuentin** [Azure/AKS#3109]
**Describe the bug**
After using the ACR integration into AKS since 1 year now, it seems that the authentication isn't working anymore and I can't detach / attach the ACR because of this issue 

```sh
$ az aks update -n xxxxx -g yyyyyy --attach-acr zzzzzz
AAD role propagation done[############################################]  100.0000%Operation failed with status: 'Bad Request'. Details: The specified service CIDR 10.2.0.0/16 is conflicted with an existing subnet CIDR 10.2.0.0/16
```

```sh
$ az aks update -n xxxxx -g yyyyyy --detach-acr zzzzzz
AAD role propagation done[############################################]  100.0000%Operation failed with status: 'Bad Request'. Details: The specified service CIDR 10.2.0.0/16 is conflicted with an existing subnet CIDR 10.2.0.0/16
```

**To Reproduce**
Create an AKS cluster as explained here https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-new.md then add the acr as explained here https://docs.microsoft.com/fr-fr/azure/aks/cluster-container-registry-integration?tabs=azure-cli then wait one year ^^

**Expected behavior**
I was expecting that the integration is able to renew authentication stuff without the need to detach & re-attach acr. And if needed, not being blocked by an error.

**Environment (please complete the following information):**
 -  azure-cli 2.21.0
 - Kubernetes version 1.21.1
 - Kubectl version 

> Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"10428892c761e8ca8908e71146eea4751feb545b", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:11Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
It's a real problem because I can't update my application anymore ...

```sh
$ az aks check-acr --name xxxxxx -g yyyyyyy --acr zzzzz.azurecr.io
Merged "aks7e44" as current context in /var/folders/zp/ljdjs9w90sqb4pycc43t7xsm0000gn/T/tmpp7x5p7bx
Error attaching, falling back to logs: unable to upgrade connection: container canipull-1e8827ba-42aa-4f56-83cc-fd5418bf345a not found in pod canipull-1e8827ba-42aa-4f56-83cc-fd5418bf345a_default
[2022-07-29T09:25:39Z] Checking host name resolution (datmuseum.azurecr.io): SUCCEEDED
[2022-07-29T09:25:39Z] Canonical name for ACR (datmuseum.azurecr.io): r0625weu-5.westeurope.cloudapp.azure.com.
[2022-07-29T09:25:39Z] ACR location: westeurope
[2022-07-29T09:25:39Z] Loading azure.json file from /etc/kubernetes/azure.json
[2022-07-29T09:25:39Z] The cluster uses service principal.
[2022-07-29T09:25:39Z] Validating service principal credential: FAILED
[2022-07-29T09:25:39Z] Sign in to AAD failed with: failed to refresh ARM access token: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS7000222: The provided client secret keys for app '***************************' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds.\r\nTrace ID: 6125b5e0-63af-4a9f-a5c3-89f460344000\r\nCorrelation ID: bf7b2160-87f8-4318-bb79-e1b953e5eeda\r\nTimestamp: 2022-07-29 09:25:39Z","error_codes":[7000222],"timestamp":"2022-07-29 09:25:39Z","trace_id":"6125b5e0-63af-4a9f-a5c3-89f460344000","correlation_id":"bf7b2160-87f8-4318-bb79-e1b953e5eeda","error_uri":"https://login.microsoftonline.com/error?code=7000222"} Endpoint https://login.microsoftonline.com/******************************/oauth2/token?api-version=1.0
```

**Comment by mezzofix** [comment]
It looks like the cluster got deployed with a Service Principal rather than a Managed Identity. AKS clusters created with a service principal have a one-year expiration time (more in -> https://docs.microsoft.com/en-us/azure/aks/update-credentials). To create a kubernetes cluster with custom control plane identity and kubelet identity (the later one is used for ACR integration) you have to explicitly define it at creation time. With a Managed Identity you don't have to take care of the expiry, Microsoft handles this for you in the background.

**Comment by SchroterQuentin** [comment]
Well, my cluster didn't have an expired service principal but I reset the credentials as you suggest. It doesn't solve the problem because the problem is with the service principal used to get images of the ACR.
I found the actual ServicePrincipal that had the expired secret and regenerate a new one but it doesn't solve the problem neither. So i delete the old secret and I before I renew the AKS service principal I did have the following response from the check-acr :

> Sign in to AAD failed with: failed to refresh ARM access token: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '************'.\r\nTrace ID: 4dbc5460-7409-4b26-8535-977db6773400\r\nCorrelation ID: fb15127c-61c8-442a-b4db-eba9d17c9903\r\nTimestamp: 2022-07-29 13:13:58Z","error_codes":[7000215],"timestamp":"2022-07-29 13:13:58Z","trace_id":"4dbc5460-7409-4b26-8535-977db6773400","correlation_id":"fb15127c-61c8-442a-b4db-eba9d17c9903","error_uri":"https://login.microsoftonline.com/error?code=7000215"} Endpoint https://login.microsoftonline.com/***************/oauth2/token?api-version=1.0

And after renewing the AKS service principal I can't even run the check-acr anymore 

```sh
az aks check-acr --name xxxxxxxxx -g yyyyyyyy --acr zzzzzzzzzzzz
Merged "xxxxxxx" as current context in /var/folders/zp/ljdjs9w90sqb4pycc43t7xsm0000gn/T/tmpog6gjlfn
error: timed out waiting for the condition
Failed to check the ACR: Command '['kubectl', 'run', '--kubeconfig', '/var/folders/zp/ljdjs9w90sqb4pycc43t7xsm0000gn/T/tmpog6gjlfn', '--rm', '--quiet', '--image', 'mcr.microsoft.com/aks/canipull:0.0.2-alpha', '--overrides', '{"spec": {"restartPolicy": "Never", "hostNetwork": true, "containers": [{"securityContext": {"runAsUser": 0}, "name": "canipull-184926d5-5f92-4057-bf21-77e931ce3c9a", "image": "mcr.microsoft.com/aks/canipull:0.0.2-alpha", "args": ["-v6", "datmuseum.azurecr.io"], "stdin": true, "stdinOnce": true, "tty": true, "volumeMounts": [{"name": "azurejson", "mountPath": "/etc/kubernetes"}, {"name": "sslcerts", "mountPath": "/etc/ssl/certs"}]}], "tolerations": [{"key": "CriticalAddonsOnly", "operator": "Exists"}, {"effect": "NoExecute", "operator": "Exists"}], "volumes": [{"name": "azurejson", "hostPath": {"path": "/etc/kubernetes"}}, {"name": "sslcerts", "hostPath": {"path": "/etc/ssl/certs"}}]}}', '-it', 'canipull-184926d5-5f92-4057-bf21-77e931ce3c9a']' returned non-zero exit status 1.
```

**Comment by SchroterQuentin** [comment]
Well, finally it was all because of my vnet configuration. My postgresql subnet was the same as the kubernetes internal CIDR.
No solution provided from Azure, because even if the tutorial is from the Azure engineer teams, this architecture is not "supported" by Azure ...
Need to recreate a new database and migrate all the data to it because Azure Postgresql can't be moved after creation.
