### ISSUE TITLE
[Question] Why does AKS support multiple patch versions?

### ISSUE THREAD

**Issue by OvervCW** [Azure/AKS#3110]
When I create a new Kubernetes cluster, I get the following version choices:

<kbd>![image](https://user-images.githubusercontent.com/60606100/181791321-03a38413-d401-4685-b7f4-59ae4495796b.png)</kbd>

It makes sense that you may want to pick a specific minor version (1.21.x, 1.22.x, 1.23.x) in case of breaking changes, but why are there also different patch choices available? Why would someone want to create a cluster with version 1.22.6 rather than 1.22.11? And why specifically those choices? Why not 1.22.7 and 1.22.12, for example?

**Comment by raghulmsft** [comment]
Hi, I'm a PM with the AKS team and will get back to you with an answer soon!

**Comment by palma21** [comment]
I love your style, but in practice most of our users struggle to keep up with the upgrades and the constant flow of patch releases. So we support 2 at every given time to allow for time to upgrade while keeping support, and also to give more time for creates with that patch for scripts and automation (min 2 months).

We definitely don't think anyone would go to the portal and select the older patch, but from the service overall the above is why we keep/support 2.
