### ISSUE TITLE
[Feature] Don't detach NSG before deleting a managed subnet

### ISSUE THREAD

**Issue by weisdd** [Azure/AKS#3111]
**Is your feature request related to a problem? Please describe.**

We have an enforcing policy that blocks attempts to either create a subnet without an NSG reference or to detach the NSG from the subnet:

<details>
  <summary>Policy definition</summary>
  
```json
   "policyRule": {
      "if": {
        "anyOf": [
          {
            "allOf": [
              {
                "equals": "Microsoft.Network/virtualNetworks/subnets",
                "field": "type"
              },
              {
                "not": {
                  "equals": "AzureBastionSubnet",
                  "field": "name"
                }
              },
              {
                "not": {
                  "equals": "GatewaySubnet",
                  "field": "name"
                }
              },
              {
                "not": {
                  "exists": "true",
                  "field": "Microsoft.Network/virtualNetworks/subnets/networkSecurityGroup"
                }
              }
            ]
          }
        ]
      },
      "then": {
        "effect": "deny"
      }
    }
```
</details>

When we create an AKS-cluster without a reference to our own subnet, Azure automatically creates a vnet and a subnet with an NSG attached. It all goes just fine.
But when we delete the cluster, Azure backend tries to detach an NSG before deleting the subnet. And that step fails due to the policy violation.
As a consequence, users have to manually delete a VMSS, then the subnet, and only after that the process of cluster removal becomes unblocked. - It negatively impacts UX.

**Describe the solution you'd like**

I know for fact that nowadays Azure allows users to delete a subnet without the need to detach an NSG first.
Ideally, I'd like Azure backend not to make that detach call prior to subnet deletion since it's not mandatory.

**Describe alternatives you've considered**

- Manual removal of some managed resources like described above;
- Usage of non-managed subnets => a user might not have enough permissions and will be forced to wait till someone does the central provisioning.

**Additional context**

- Tested with both Azure portal and terraform;
- Some time ago, Azure did not allow users to delete a subnet without detaching an NSG or UDR first. This limitation was lifted at certain point, got confirmation from technical support about that: 
- Example of the error:
`Error: waiting for the deletion of Cluster: (Managed Cluster Name “example-aks1" / Resource Group “example-resources”): Code=“DissociateRouteTableOrNetworkSecurityGroupFromSubnetError” Message=“Failed to dissociate route table or network security group from subnet. Error detail: Category: ClientError; Code: Unspecified; SubCode: FailedUpdateSubnet; Message: ; InnerMessage: ; Dependency: ; OrginalError: please manually dissociate route table and/or network security group from subnet /subscriptions/[REDACTED]/resourceGroups/MC_example-resources_example-aks1_westeurope/providers/Microsoft.Network/virtualNetworks/aks-vnet-37875945/subnets/aks-subnet then try to delete managed cluster. Error: Category: ClientError; Code: Unspecified; SubCode: RequestDisallowedByPolicy; Message: ; InnerMessage: ; Dependency: Microsoft.Network/virtualNetworks/subnets; OrginalError: Code=\\“RequestDisallowedByPolicy\\” Message=\\“Resource ‘aks-subnet’ was disallowed by policy. [...]`
- Example of terraform code assuming the policy is deployed:
```hcl
provider ‘azurerm’ {
  features {}
}
resource ‘azurerm_resource_group’ ‘example’ {
  name     = ‘example-resources’
  location = ‘West Europe’
}
resource ‘azurerm_kubernetes_cluster’ ‘example’ {
  name                = ‘example-aks1’
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = ‘exampleaks1’
  default_node_pool {
    name       = ‘default’
    node_count = 1
    vm_size    = ‘Standard_D2_v2’
  }
  identity {
    type = ‘SystemAssigned’
  }
  tags = {
    Environment = ‘Production’
  }
}
```

**Comment by kaarthis** [comment]
Under evaluation for Managed Vnet. We shall get back to you here by May with timelines.

**Comment by phealy** [comment]
@weisdd The current plan is to still detach the NSG before deleting the subnet (it handles some useful edge cases for us, so we don't want to remove it), but to make the deletion best-effort - if it does fail due to policy or some other reason, we'll proceed with cleaning everything up and deleting the node resource group. We'll log the error on our side for support but not return a failure state to you unless we're actually unable to delete everything.

I believe this should meet your needs - can you please confirm?

**Comment by weisdd** [comment]
@phealy that sounds like a nice solution, can't wait to see it go live :) Is there any ETA that I can potentially share with my fellow engineers?
Thanks!

**Comment by phealy** [comment]
"soon (TM)" - it depends on release timing but I would guess 3 to 6 weeks.
