### ISSUE TITLE
[Question] Is there a replacement for `Service.Spec.loadBalancerIP`

### ISSUE THREAD

**Issue by pinkfloydx33** [Azure/AKS#3122]
**Describe scenario**
We currently have a few services of type `LoadBalancer` where we preallocate an Azure static, public IP address and map the address via the `spec.loadBalancerIP` field. 

**Question**
`Service.spec.loadBalancerIP` [was deprecated in k8s 1.24](https://github.com/kubernetes/kubernetes/pull/107235). From the [Change Log](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#deprecation):
> Deprecated `Service.Spec.LoadBalancerIP`. This field was under-specified and its meaning varies across implementations. As of Kubernetes v1.24, users are encouraged to use implementation-specific annotations when available. This field may be removed in a future API version. ([#107235](https://github.com/kubernetes/kubernetes/pull/107235), @&#8203;uablrek)

The [AKS changelog](https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2022-07-31) makes no note of actions to take due to this deprecation. 

While I understand that deprecation does not mean removal *just yet*, is there/will there be an alternative annotation for mapping an Azure public static IP address to the load balancer? 

It's been suggested [in the linked, closed PR](https://github.com/kubernetes/enhancements/pull/1992) that the field was under-spec'd, likely unused by cloud providers, and should really be an annotation. However the AKS [docs for external load balancer](https://docs.microsoft.com/en-us/azure/aks/static-ip#create-a-service-using-the-static-ip-address) have you specify the field, and no alternative annotation is [listed here](https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/) . 

The [docs for internal load balancers](https://docs.microsoft.com/en-us/azure/aks/internal-lb#specify-an-ip-address) also have you use the field. 

As an aside, if this *does* turn into an annotation it'd be nice if we could specify *either* the IP address itself (as we currently do)  *or* the name of the public IP address resource. Obviously the latter would only apply to external LBs and the former as the only option for internal LBs

**Comment by ankitrgupta1** [comment]
Has there been any update on this? I can't see any documents getting updated related to the change, for any method to be used in place of loadbalanacerip yet. 1.24.3 is already GA and available for upgrade.

**Comment by rouke-broersma** [comment]
@olsenme Seems you've recently edited the changelog. Could you get someone to take a look at this?

**Comment by pinkfloydx33** [comment]
It's be really great to have an answer on this one.... Anyone?

**Comment by rouke-broersma** [comment]
Any update on this since 1.25 just went GA?

**Comment by rouke-broersma** [comment]
@pinkfloydx33 I've been searching far and wide what the implication of this deprecation is, looks like it is a very soft deprecation as no cloud provider has an alternative yet. The only implementation of an annotation I've seen is metallb.

https://github.com/kubernetes/kubernetes/pull/107235#issuecomment-1265093420 

I have a feeling we won't have to do anything for a very long time, and at some point the new annotation will be introduced alongside the loadBalancerIp field.

It seems like the annotation has been introduced in-tree, however it's not clear to me if this made it into AKS 1.25 or not: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2428

**Comment by PSanetra** [comment]
@rouke-broersma the change seems to be available in the following releases:
- [1.26.0](https://github.com/kubernetes-sigs/cloud-provider-azure/releases/tag/v1.26.0)
- [1.25.3](https://github.com/kubernetes-sigs/cloud-provider-azure/releases/tag/v1.25.3)
- [1.24.9](https://github.com/kubernetes-sigs/cloud-provider-azure/releases/tag/v1.24.9)

**Comment by rouke-broersma** [comment]
> @rouke-broersma the change seems to be available in the following releases:
> - [1.26.0](https://github.com/kubernetes-sigs/cloud-provider-azure/releases/tag/v1.26.0)
> - [1.25.3](https://github.com/kubernetes-sigs/cloud-provider-azure/releases/tag/v1.25.3)
> - [1.24.9](https://github.com/kubernetes-sigs/cloud-provider-azure/releases/tag/v1.24.9)

If those version numbers for the azure cloud provider correspond to kubernetes versions then I don't think the annotation has been released yet on azure.

**Comment by feiskyer** [comment]
Those versions have already been updated in AKS, hence the new annotations have already been supported.

**Comment by rouke-broersma** [comment]
@feiskyer are the aks docs also going to be updated?

**Comment by pinkfloydx33** [comment]
The cloud provider docs (linked in OP) also need to be updated though I'm not sure if that's sourced from this repo or not

**Comment by lzhecheng** [comment]
cloud-provider-azure doc has been updated: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/3019
There's another PR to update azure-docs under review.
