### ISSUE TITLE
[Feature] Disable OutboundNAT on Windows

### ISSUE THREAD

**Issue by allyford** [Azure/AKS#3128]
Allow customers to [disable OutboundNAT](https://learn.microsoft.com/en-us/azure/aks/nat-gateway#:~:text=identity%20%24IDENTITY_ID-,Disable%20OutboundNAT%20for%20Windows,-Windows%20OutboundNAT%20can) when creating WS2019 and WS2022 nodepools. 

Windows enables OutboundNAT by default. OutboundNAT can be configured in Azure CNI.

**Comment by vamsivellanki** [comment]
May we know when this feature will be GA?

**Comment by DenisBiondic** [comment]
"Your clusters must have a Managed NAT Gateway (which may increase the overall cost)."

Is the NAT Gateway really required for this to work?

**Comment by DenisBiondic** [comment]
and to add on to the previous question: how does using NAT Gateway even make sense here, as the NAT Gateway can only to public Internet? OutboundNAT issues on Windows nodes are usually only a problem in internal networking scenarios.

**Comment by ShiqianTao** [comment]
> "Your clusters must have a Managed NAT Gateway (which may increase the overall cost)."
> Is the NAT Gateway really required for this to work?

Hi @DenisBiondic . Yes. It requires NAT Gateway to handle the pod's direct outbound communication.

**Comment by ShiqianTao** [comment]
> and to add on to the previous question: how does using NAT Gateway even make sense here, as the NAT Gateway can only to public Internet? OutboundNAT issues on Windows nodes are usually only a problem in internal networking scenarios.

Hi @DenisBiondic . NAT Gateway is more powerful than Load Balancer (also more expensive), it can handle many scenarios. The Windows OutboundNAT is used to translate pods IPs to Windows node host IP, and there is only one primary IP (host IP) on Network Interface per Windows node, according to "[Secondary IP configurations of a network interface don't provide outbound communication](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#constraints)", it means the Azure Load Balancer cannot support Windows pod's outbound communication directly. So, after windows nodes disabled OutboundNAT, the AKS cluster requires NAT Gateway to support Windows pods' outbound communication.

**Comment by cmendible** [comment]
FSI customers uses egress lockdown and public IP's are generally forbidden. How does a NAT Gateway fits into such scenario?

**Comment by MNouman9** [comment]
We are looking to use this feature in production with private AKS cluster. We have Windows nodepool in our cluster which are essential for our production environment.
Can you please provide a tentative time when this feature will be in GA?

**Comment by allyford** [comment]
Windows Disable Outbound NAT is now available for preview in Windows Server 2019 and Windows Server 2022 nodepools. GA is tentatively planned for Q1 2024.

**Comment by DenisBiondic** [comment]
thx for the update @allyford. Can you please explain if this feature works:
- in public cluster scenarios, without NAT Gateway, with simple Standard Load Balancer as the outbound type
- in private cluster scenarios, without NAT Gateway, with internal LB

**Comment by allyford** [comment]
This feature is now Generally Available!
