### ISSUE TITLE
az aks browse times out

### ISSUE THREAD

**Issue by lkt82** [Azure/AKS#313]
Hey 

When i try to use az aks browse the dashbord works for a few sekunds and the times out.

The location is Canada East

Message from az aks

E0419 13:28:30.137763   17512 portforward.go:271] error creating error stream for port 8001 -> 9090: Timeout occured

**Comment by devkws** [comment]
I am having the same issue, you basically need to continuously be using and clicking links on the dashboard or else it times out and you must ctrl-c and re-run az aks browse

**Comment by TallOrderDev** [comment]
I think this is fine default functionality, but if we could add a flag to browse, that'd be great. When debugging on AKS it's a pain to rerun over and over, specially if your timeout was to go read the docs, you come back and it's all down, destroying your workflow.

**Comment by goarano** [comment]
I disagree, it is not a fine default funcionality. Either the tool needs to exit with an error code when the timeout occurs, this way one could wrap it in a script that automatically restarts the tunnel, or it should just keep connected as long as the command runs.
Please fix this

**Comment by devkws** [comment]
I agree with @goarano this is not fine. It just seems buggy, and broken as is.

**Comment by hafizramly** [comment]
Having this issue all the time after leaving the page idle for couple of minutes. Any plans for getting this enhanced ?

**Comment by sshorkey** [comment]
Also agree with @goarano. This is my biggest gripe with AKS (otherwise an awesome product).

**Comment by jnoller** [comment]
Duplicate of #68, #779 and #232
