### ISSUE TITLE
Dynamic IP allocation throws errors on new cluster

### ISSUE THREAD

**Issue by aidacloud** [Azure/AKS#3132]
**Describe the bug**
In a brand-new cluster deployed with Terraform latest providers, ACN nnc-reconciler is publishing warnings and errors.

`Error creating NodeNetworkConfig aks-system-36203820-vmss000000, err = nodenetworkconfigs.acn.azure.com "aks-system-36203820-vmss000000" already exists`

`publishCreateOrUpdateNC error: Operation cannot be fulfilled on nodenetworkconfigs.acn.azure.com "aks-system-36203820-vmss000001": the object has been modified; please apply your changes to the latest version and try again`

`Failed to upsert NC {guid}, err = JsonError:[Code:Unknown Status, Text:Put "http://azure-dnc-primary:9000/... lookup azure-dnc-primary on 172.30.0.10:53: no such host, HTTPStatus:202]`

I'm not sure where 172.30.0.10 is coming from here as there are no services on that IP range.

**To Reproduce**
1. Create a vnet (10. address space)
2. Create a subnet for nodes in same vnet
3. Create a subnet for pods in same vnet
4. Create a linux only cluster, specify node subnet as vnet-subnet-id and pod subnet for pob-subnet-id
  a. specify 172.16.0.0/16 for services cide
  b. specify 172.17.0.0/16 for docker bridge cidr
  c. specify 172.16.0.10 for DNS service IP
6. Create a non-default linux node pool for non-critical add-ons. Specify node subnet as vnet-subnet-id and pod subnet for pob-subnet-id.

**Expected behavior**
No warnings or errors persisting.

**Screenshots**
![image](https://user-images.githubusercontent.com/110570187/184043173-e53c6558-5f19-4fbd-ad21-fcad6997de6f.png)
![image](https://user-images.githubusercontent.com/110570187/184043204-c63ddbbe-2e0b-4ed2-b25f-0c21ad32d240.png)

**Environment (please complete the following information):**
 - Kubernetes version: 1.23.8
 - Terraform version: 1.26
 - Terraform AzureRM provider: 3.17.0

**Additional context**
Both system (default nodepool) and linux1 (additional nodepool) are emitting the same warnings.

**Comment by paulgmiller** [comment]
This already exists message is perfectly normal and we're removing them in the release currently rolling out so they should be gone in <1 week. @thatmattlong  can double check me.
