### ISSUE TITLE
increase windows pod disk space

### ISSUE THREAD

**Issue by AndreasDeCrinis** [Azure/AKS#3133]
**Describe scenario**
We are currently facing the issue, that the default 20GB pod disk space for windows containers are not enough for our build to run through.
``` 
PS: C:\ Get-PSDrive C

Name           Used (GB)     Free (GB) Provider      Root
----           ---------     --------- --------      ----
C                   0.31         19.57 FileSystem    C:\

```

**Question**
Unfortunately, I havent found a way how to increase the pods available disk space. On our onprem environment I can modify the docker service parameters and add `--storage-opt 50G`. How am I supposed to do that with AKS?

**Comment by zhiweiv** [comment]
https://github.com/kubernetes/kubernetes/pull/109702#issuecomment-1255319067

**Comment by Aprilllllll** [comment]
The relevant request(https://github.com/kubernetes/kubernetes/pull/109702#issuecomment-1255319067) has been closed, reopening this for tracking.
