### ISSUE TITLE
[Question] Please upgrade virtual-kubelet

### ISSUE THREAD

**Issue by ewfian** [Azure/AKS#3135]
The [azure-aci v1.4.2](https://github.com/virtual-kubelet/azure-aci/releases/tag/v1.4.2) was released on Jan 04, 2022, Please upgrade the default version

**Comment by wangyira** [comment]
@helayoty could you help with this?

**Comment by helayoty** [comment]
@ewfian , thanks for reaching out. A new version fro virtual-kubelet/azure-aci (v1.4.5) has been deployed and is available on AKS.

**Comment by ewfian** [comment]
> @ewfian, thanks for reaching out. A new version from virtual-kubelet/[azure-aci](https://github.com/virtual-kubelet/azure-aci/releases/tag/v1.4.5) (v1.4.5) has been deployed and is available on AKS.

Thank you for help
