### ISSUE TITLE
Quality tool - RMS error fluctuation

### ISSUE THREAD

**Issue by ralucadianasambra** [Azure/AKS#314]
Hi,

I am evaluating a D415 camera with your Depth Quality Tool. It looks like the error is fluctuating (see image) instead of just increasing with d^2. I was wondering what the cause is and if there is any chance to keep the values around the lower limit.
![d415 rms](https://user-images.githubusercontent.com/11428755/39001326-56453222-43f6-11e8-93c2-96a076366a3f.png)

Best,
Raluca

**Comment by slack** [comment]
Thanks for opening an issue, but I don't think this is the repository you are looking for.

**Comment by ralucadianasambra** [comment]
Thanks for your reply. I knew it was a long shot, but though I'd give it a try. Do you happen to know whom I could ask about it?
