### ISSUE TITLE
[Question] OSM add-on How does an version upgrade look like?

### ISSUE THREAD

**Issue by tcz91** [Azure/AKS#3141]
**Describe scenario**
Enabling OSM add-on via terraform [open_service_mesh_enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#open_service_mesh_enabled) flag seems to deploy latest feasible OSM version - for our AKS cluster it is v1.2.0 (checked with OSM client).

**Question**
Since the OSM add-on is neither an normal app-deployment, nor helm-chart, .... how does the upgrade process look like? In the official [AKS OSM sites](https://docs.microsoft.com/en-us/azure/aks/open-service-mesh-about) I didn't find any information regarding this. The same is for using Azure-CLI or Bicep. We would prefer some kind of built-in version upgrade with as-code-config (which btw seems heavily to miss as well, see also [here](https://github.com/Azure/AKS/issues/2837)) instead of using [OSM client](https://release-v1-2.docs.openservicemesh.io/docs/guides/upgrade/#how-to-upgrade-osm) or trying patches via kubectl - then it would be only an half add-on...

Having OSM as "fully managed service mesh" would be the only reason for us to switch. Otherwise it has no advantages over using for example linkerd. Thats also the reason why we don't want to deploy OSM as configurable helm chart.

**Comment by marlowp** [comment]
Is there any update on this issue?

I also can't find any supported way to upgrade the OSM version when using the OSM AKS addon. The [instructions in the official documentation](https://release-v1-2.docs.openservicemesh.io/docs/guides/upgrade/) won't work as mentioned [here](https://github.com/openservicemesh/osm/issues/5067#issuecomment-1235629514). As the author has stated there is no mention in Microsoft's official docs of how to upgrade. I'm slightly surprised that the addon has come out of Public Preview without a supported method for upgrading it.

At the moment the workaround seems to be to uninstall the addon and then reinstall it which isn't ideal.
