### ISSUE TITLE
AKS cluster info must output identity used by Web Routing Add-on

### ISSUE THREAD

**Issue by SatyKrish** [Azure/AKS#3144]
**Describe the bug**
AKS cluster output doesn't output the identity associated with `Web Application Routing` add-on.

**To Reproduce**
1. Run command 'az aks show -g <my-resource-group> -n <my-aks-cluster-name> --query ingressProfile'
2. See the output of `webAppRouting` section

**Expected behavior**
Identity used by Web Routing Addon should be displayed in cluster output, so that we can query the identity.clientId for assigning Azure Key Vault access policy using automation.

**Environment (please complete the following information):**
 - Azure CLI Version - 2.39.0
 - Kubernetes version - 1.24.0
 - AKS-Preview CLI Extension Version - 0.5.92

**Additional context**
AKS documentation only contains manual approach for retrieving Client ID, which doesn't help for automation.
https://docs.microsoft.com/en-us/azure/aks/web-app-routing#grant-permissions-for-web-application-routing

**Comment by sabbour** [comment]
This is on the roadmap.

**Comment by CocoWang-wql** [comment]
We are working on it and the ETA is about the end of March.

**Comment by sabbour** [comment]
This has been implemented.
