### ISSUE TITLE
Limits on APP Gateway Path and host based routing.

### ISSUE THREAD

**Issue by apoorvkapil** [Azure/AKS#3145]
**Describe scenario**
I have an AKS Cluster running an API management solution which is exposing multiple Enterprise APIs of different Internal Teams (Logically differentiated Deployments). The number of teams could be 500. **_I want to expose those API via a common app gateway URL while giving each team a unique Path or Host._** This could be done via **Path based or Host based routing in AGIC**. However we are stuck with the limit that MS has on Application gateway Listeners and max number of Path (**Maximum path-based rules per URL map**) as referred in the [this link](https://github.com/MicrosoftDocs/azure-docs/blob/main/includes/application-gateway-limits.md) of APP gateway Limits. We have tested that most Limits applies to AGIC as well. e.g Max number of listeners can be 100 active listeners , Max number of Paths per listener is also restricted to 100 paths per listener.

**Question**
What's the roadmap to lift/scale up these limitations in case of AGIC.
Do we have any other solution to achieve the above goal ?

**E.g.** Each team will be assigned a Deployment in our AKS Cluster. We will be assigning them a unique path to their segregated Deployment like host.com/team1/*  routing to **Deployment of team1**, host.com/team2/* to **Deployment of team2** and so on. We are stuck when the team100 is onboarded, as it will hit the limits on APP gateway.

**Comment by mtwelve** [comment]
Facing a similar issue due to the limits of App Gateway.

Any news on if they'll ever be a version 3 SKU or increases to the current limits?

Really don't want to have to move away from using the AGIC.

**Comment by flavioeb-ciandt** [comment]
I'm facing the same issue and I'd need to increase the number of max paths. Is there a solution? Or is this a configuration that I can change somewhere?

**Comment by rugland** [comment]
Also facing the same issue. 

The 100 urlmap rules seems arbitrary? Any news on getting this higher. This is essentially forcing us to either move to nginx as our ingress controller or use subdomains/scale out the number of clusters way before the cluster is anywhere near saturated.

**Comment by apoorvkapil** [comment]
It appears that Microsoft hasn't yet provided a solution for this. Consequently, we've decided to utilize a different ingress controller and set up our users' routes on it, then expose them via the app gateway.

**Comment by qpetraroia** [comment]
Application Gateway for Containers has introduced higher limits on listeners, backends, and increased flexibility on routing (based on path, header, etc). Consider taking a look at Application Gateway for Containers to exceed the limitations currently in place by AGIC. 

https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/overview

**Comment by epime** [comment]
Sure, it's been doubled. But it still far too low. 

I can create a 1000 node AKS cluster, but I can only have 200 ingresses. In a scenario where you need an ingress per customer this is very low. So it forces us to still use NGINX as ingress.
