### ISSUE TITLE
[Feature] Allow usage of strict zone balancing

### ISSUE THREAD

**Issue by ricoberger** [Azure/AKS#3146]
**Is your feature request related to a problem? Please describe.**

We created a new node pool in one of our cluster (Germany West Central, Zone 1, 2 and 3) and all new nodes where only created in zone 1 and 2. This caused some problems:

- PVCs from the old node pool could not be mounted on a node of the new node pool (because there wasn't a node in zone 3)
- Topology spread constraints could not be full filled

**Describe the solution you'd like**

Currently AKS uses best effort zone balancing:

> When deciding what zone a new node should belong to, a given AKS node pool will use a [best effort zone balancing offered by underlying Azure Virtual Machine Scale Sets.

It would be nice, if this is can be set to **strict zone balancing**, to ensure that the nodes are always evenly distributed across the selected availability zones.

**Describe alternatives you've considered**

An other option we considered is to manually set the `zoneBalance` property of the created virtual machine scale set for a node pool, but we did not tested it yet.

**Comment by rouke-broersma** [comment]
Using mixed-zone nodepools with persistent storage is not recommended. Rather create a nodepool per-zone and use `--balance-similar-node-groups` to balance nodes per zone. https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler#use-the-cluster-autoscaler-with-multiple-node-pools-enabled

**Comment by ricoberger** [comment]
Hi @rouke-broersma, thanks for your feedback. We are using one nodepool per zone now, so that the issue is fixed for us and can be closed from our side.
