### ISSUE TITLE
Can you pull and use docker images from other registries rather than using ACR (Azure container registry)

### ISSUE THREAD

**Issue by xtianus79** [Azure/AKS#3149]
This issue (closed) asked a similar question. 
https://github.com/Azure/AKS/issues/252

I still can't find a clear message on how to do this. Also, the reason why I am asking is that some images are just public images that have HELM or Docker compose already built in. Trying to then place those into an ACR seems counter intuitive but perhaps there is a reason. 

For example, if I want to pull an image from Docker Hub that already exists or from HELM why do I need to go through the situation of pulling and pushing into ACR? 

Is there a clear way to simply using Docker or HELM without ACR?

**Comment by sanglt** [comment]
Yes you can use any docker registry for AKS. Our company use mixed between DockerHub and our private GitLab registry.

To use a private registry, you need to setup a authentication like this guide: [Pull an Image from a Private Registry](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)

**Comment by carvido1** [comment]
Hello @xtianus79 .

The reason of having the helm chart or docker container images in a private container registry is about security and trust.
When you push these images to your private container registry means you trust these images. This usually comes also with a container image scan with trivy for instance.

In addition, Azure has created [built-in policies for AKS](https://docs.microsoft.com/en-us/azure/aks/policy-reference) that you can use to enforce a policy called [Kubernetes cluster containers should only use allowed pull policy](https://portal.azure.com/#blade/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2F50c83470-d2f0-4dda-a716-1938a4825f62) to pull only allowed images.

Now, to reply to your question. You can use the [az acr import](https://docs.microsoft.com/es-es/cli/azure/acr?view=azure-cli-latest#az-acr-import) command which requires docker/podman to be installed. In addition you have to be [logged in](https://docs.microsoft.com/es-es/cli/azure/acr?view=azure-cli-latest#az-acr-login) to the container registry before the import.

BR

**Comment by vieenodp** [comment]
Even if I use the external certificate signed by digicert for my docker registry which is hosted on AKS cluster itself , AKS nodes still throws "x509: certificate signed by unknown authority" In short the claim that you can use any docker registry with AKS is false.

**Comment by vieenodp** [comment]
> 

The issue is not about the secret its about the AKS do not trust the certificate of non ACR registries except probably few public like dockerhub

**Comment by carvido1** [comment]
Hello @vieenodp 

Something is that a docker registry can be used in your AKS cluster and another thing is that the container registry used has certificates that are trusted by your AKS cluster(kubelet in this case).

The message `x509: certificate signed by unknown authority` gives context to the problem you are experiencing. Have you tried to spin a pod and curl the container registry and see if you get the same message ? 

Best regards.

**Comment by vieenodp** [comment]
@carvido1  its failing, output shown below. I am using external digicert certificate on docker registry. 

curl -v https://registry.xyz.com 
.
.
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by carvido1** [comment]
Hello there.

There is a preview feature to add a custom [CA authority to your kubernetes clusters](https://learn.microsoft.com/en-us/azure/aks/custom-certificate-authority).

@xtianus79 maybe you can give a try on this. You can add the CA and the intermediate to the setup.

BR.
