### ISSUE TITLE
[Feature] - Specify Node Image Version

### ISSUE THREAD

**Issue by hbuckle** [Azure/AKS#3151]
**Is your feature request related to a problem? Please describe.**

We upgraded the node image version in our staging environment, however when our pipeline got to the production environment a newer node image version had been released and the environments ended up different

**Describe the solution you'd like**

Ability to specify the desired image version as part of the [upgrade](https://docs.microsoft.com/en-us/rest/api/aks/agent-pools/upgrade-node-image-version?tabs=HTTP) command

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by blanchardma** [comment]
In a declarative way with Terraform could it from my point of view look like the following simplified example:
```
resource "azurerm_kubernetes_cluster_node_pool" "example_1" {
  name = "example1"

  source_image_reference = {
    publisher = "microsoft-aks"
    offer     = "aks"
    sku       = "aks-engine-ubuntu-2004-202301"
    version   = "2023.03.06"
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "example_2" {
  name = "example2"
  
  source_image_id = "/Subscriptions/123456789-1234-1234-1234-12345678912/Providers/Microsoft.Compute/Locations/westus/Publishers/microsoft-aks/ArtifactTypes/VMImage/Offers/aks/Skus/aks-engine-ubuntu-2004-202301/Versions/2023.03.06"
}
```
If it’s then also possible to roll it back to a previous source image version like request with #2744 it would be even better.

**Comment by Al77056** [comment]
Related to the original request, it would be very helpful to specify the node image version during the creation of a node pool. We need reproducibility when it comes to production environments, and prefers all cluster are running the same node version when they were created / upgraded.

**Comment by palma21** [comment]
This request was already made in the past and rejected since specifying specific images would break operations more often sine image versions are related to service versions on validation and functionality.

Upgrade groups solves the specific scenario above.

Another more manual option if you want options to go back to for example, can be accomplished with nodepool snapshot (that snapshots the full nodepool config and version)

**Comment by nbjohnson** [comment]
@palma21 We would greatly appreciate a feature like this as we have a similar use case, having our test and production clusters on the same node image version. Currently we would like to update our test cluster to the latest node image version, test for a little while, then update our production clusters to match the tested image. However currently if images are rolling out on a weekly basis we may not be able to update our production cluster to match before a new node image version is rolled out. I feel like this is a good feature to have available for stability testing and am curious why it would be rejected at the outset

**Comment by sjwaight** [comment]
@nbjohnson, @blanchardma - it's worth noting that you can now use Azure Kubernetes Fleet Manager Update Runs (and Auto-upgrades) with Consistent Node Image configured so it is applied across all your clusters in every region. See [our docs for more information](https://learn.microsoft.com/en-us/azure/kubernetes-fleet/concepts-update-orchestration).
