### ISSUE TITLE
[BUG] Init/Priveleged DaemonSet Pods will not deploy onto Spot nodepools

### ISSUE THREAD

**Issue by MattGarner-N** [Azure/AKS#3153]
**Describe the bug**
Init/Priveleged DaemonSet will not deploy onto Spot nodepools. Using this example it will not deploy onto any node pool that is spot:
http://hypernephelist.com/2021/03/23/kubernetes-containerd-certificate.html

**To Reproduce**
1. Deploy the daemonset in the link above and it will not deploy onto spot node pools.

**Expected behavior**
The DaemonSet should deploy a pod onto each node, including spot nodes.

**Environment (please complete the following information):**
 - Kubernetes version [1.24.3]

**Additional context**
Works fine on system/user node pools (linux) as long as it's not spot.

**Comment by alexeldeib** [comment]
spot nodes have a default taint and require a toleration. have you added that? check out https://docs.microsoft.com/en-us/azure/aks/spot-node-pool#verify-the-spot-node-pool (scroll down a bit)

**Comment by AllenWen-at-Azure** [comment]
Close the issue, the question has been answered in https://github.com/Azure/AKS/issues/3153#issuecomment-1242108660
