### ISSUE TITLE
[Question] Azure AKS Extension and Flux 2 version mapping

### ISSUE THREAD

**Issue by dschniepp** [Azure/AKS#3154]
**Describe scenario**
According to the result of `az k8s-extension show -g rg-xxx -c aks-xxx -n flux --cluster-type managedClusters` the extensions version for flux is `1.5.1`.

<details>
<description>Result</description>

```json
{
  'aksAssignedIdentity': {
    'principalId': 'xxx',
    'tenantId': null,
    'type': null
  },
  'autoUpgradeMinorVersion': true,
  'configurationProtectedSettings': {},
  'configurationSettings': {
    'helm-controller.enabled': 'true',
    'image-automation-controller.enabled': 'true',
    'image-reflector-controller.enabled': 'true',
    'kustomize-controller.enabled': 'true',
    'notification-controller.enabled': 'true',
    'source-controller.enabled': 'true'
  },
  'customLocationSettings': null,
  'errorInfo': null,
  'extensionType': 'microsoft.flux',
  'id': '/subscriptions/xxx/resourceGroups/rg-xxx/providers/Microsoft.ContainerService/managedClusters/aks-xxx/providers/Microsoft.KubernetesConfiguration/extensions/flux',
  'identity': null,
  'name': 'flux',
  'packageUri': null,
  'provisioningState': 'Succeeded',
  'releaseTrain': 'Stable',
  'resourceGroup': 'rg-xxx',
  'scope': {
    'cluster': {
      'releaseNamespace': 'flux-system'
    },
    'namespace': null
  },
  'statuses': [],
  'systemData': {
    'createdAt': '2022-07-20T14:25:52.788801+00:00',
    'createdBy': null,
    'createdByType': null,
    'lastModifiedAt': '2022-08-15T12:59:27.081100+00:00',
    'lastModifiedBy': null,
    'lastModifiedByType': null
  },
  'type': 'Microsoft.KubernetesConfiguration/extensions',
  'version': '1.5.1'
}
```
</details>

**Question**
Where can I find a mapping between the Azure AKS Extension and the Flux 2 version? In the extension I see version `1.5.1` but flux2 doesn't have any 1.5.1 [release](https://github.com/fluxcd/flux2/releases). As I would like to switch to a fixed version instead of going with `'autoUpgradeMinorVersion': true`.

---

Daniel Schniepp daniel.schniepp@mercedes-benz.com, Mercedes-Benz Mobility AG on behalf of Mercedes-Benz Tech Innovation GmbH.

**Comment by sabbour** [comment]
Tagging @mayurigupta13 and @bavneetsingh16

**Comment by mayurigupta13** [comment]
Please check the link here - https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/extensions-release#flux-gitops

**Comment by dschniepp** [comment]
Thanks :)
