### ISSUE TITLE
AKS - Migration of PVC/PV from custom storgae class to new one

### ISSUE THREAD

**Issue by zohebs341** [Azure/AKS#3155]
**Describe scenario**
We are using Azure AKS 1.21.x version and alot of data is residing in PVCs. And the provisioner of these PVCs is kubernetes.io/azure-disk. I want to migrate PVCs from this provisioner to new storage class with provisioner CSI. So that I can use snapshot features with CSI provisioner.

I can create new storage class with csi provisioner and update my statefulset to use it. But it will create a new PVC, which I don't want. As app needs old data/pvc to function.

**Question**
Is there any feasible way to achieve it. Basically I don't want to use storage class of provisioner kubernetes.io/azure-disk. As I got depreciated and I'm looking for best possible ways to migrate PVCs to new storage class.

**Comment by andyzhangx** [comment]
@zohebs341 
follow this guide to do the azure disk migration: https://docs.microsoft.com/en-us/azure/aks/csi-storage-drivers#migrate-in-tree-persistent-volumes

**Comment by zohebs341** [comment]
@andyzhangx Thanks for sharing details.

However if I tried moving/migrating LRS PVC of kubernetes io/azure-disk provisioner to CSI provisioner of ZRS storage class. PVC/PV got created under ZRS storage class.

But pod is not coming up. As the source PVC is from No AZ nodepool.

So the only option is migrate k8s/azure -disk to CSI lrs.

Convert csi-lrs to csi-zrs and then deploy in multi AZs nodepool.

**Comment by andyzhangx** [comment]
> @andyzhangx Thanks for sharing details.
> 
> However if I tried moving/migrating LRS PVC of kubernetes io/azure-disk provisioner to CSI provisioner of ZRS storage class. PVC/PV got created under ZRS storage class.
> 
> But pod is not coming up. As the source PVC is from No AZ nodepool.
> 
> So the only option is migrate k8s/azure -disk to CSI lrs.
> 
> Convert csi-lrs to csi-zrs and then deploy in multi AZs nodepool.

@zohebs341 correct, k8s config change won't change the existing disk, the only way to convert lrs disk to zrs disk is using azure api derectly.

**Comment by zohebs341** [comment]
I mean to say, Dynamic Provisioning of PVC is not happening. If I am using existing PVC. (Which I've converted from kubernetes.io/azure-disk to CSI storage class)

**Comment by zohebs341** [comment]
In a case where statefulset is having 3 replicas/3 PVC. In tree storage migration is fine. But the converted PVCs(CSI), we should be able to utilize. As there is a lot of data in it.

**Comment by zohebs341** [comment]
My Statefulset is having 3 replicas and I am using existing PVC, which I've converted from in-tree to CSI.

Pod-1 came up with existing PVC, but Pod-2 is also trying to use the same existing PVC and failing with Multi-Attach Error.

Events:
  Type     Reason              Age                  From                     Message
  ----     ------              ----                 ----                     -------
  Normal   Scheduled           12m                  default-scheduler        Successfully assigned rabbitmq/rabbitmq-1 to aks-agentpool-10440409-vmss000005
  Warning  FailedAttachVolume  12m                  attachdetach-controller  Multi-Attach error for volume "pv-rabbimtq-0" Volume is already used by pod(s) rabbitmq-0


Values.yaml:

persistence:
  ## @param persistence.enabled Enable RabbitMQ data persistence using PVC
  ##
  enabled: true
  ## @param persistence.storageClass PVC Storage Class for RabbitMQ data volume
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: ""
  ## @param persistence.selector Selector to match an existing Persistent Volume
  ## selector:
  ##   matchLabels:
  ##     app: my-app
  ##
  selector: {}
  ## @param persistence.accessModes PVC Access Modes for RabbitMQ data volume
  ##
  accessModes:
    - ReadWriteOnce
  ## @param persistence.existingClaim Provide an existing PersistentVolumeClaims
  ## The value is evaluated as a template
  ## So, for example, the name can depend on .Release or .Chart
  ##
  existingClaim: pvc-rabbitmq-0

**Comment by zohebs341** [comment]
@andyzhangx Appreciate your inputs on this?

**Comment by andyzhangx** [comment]
@zohebs341 azure disk pvc is ReadWriteOnce, one disk pvc can only be attached to one node, for pod 2, you need to use other disk pvc.

**Comment by zohebs341** [comment]
@andyzhangx Yes exactly. But I am using existing converted PVCs in values.yaml. Once the first pod is up with PVC-0, the second pod should come up with PVC-1. But still, it is referring to the first pod PVC.

Dynamic provisioning of PVC is not working, if I use existing PVC. Instead, it is just trying to add the same PVC to all 3 pods and failing.

As in any values.yaml, there will be an option of "replicas" where we will be defining value. And in existing pvc option is there. How to tell k8s, that I mean 3 copies of that existing PVC being defined.

**Comment by andyzhangx** [comment]
I think you could use `volumeClaimTemplates` in statefulset, and then create the pvc in advance, the naming rule of `volumeClaimTemplates` PVC  is `volumeClaimTemplates.metadata.name-statefulsetname-num`
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/statefulset.yaml#L34-L43

**Comment by zohebs341** [comment]
@andyzhangx Great stuff and it worked for statefulset, I will explore how we can achieve it with helm chart(values.yaml).

A small addition to your comment, whatever the name we are providing in claim templates. It should match with volumemounts.

Thank you once again for your excellency.

**Comment by zohebs341** [comment]
@andyzhangx It's just creating new PVCs with whatever the name we are providing in volumeclaimtemplates.

When I exec into the pod and validated data, it's empty pvc/new PVC. But the PVC which I've updated in volumeclaimtemplate was having data. It means, it's not referring to it and just created a new PVC dynamically with that name.

**Comment by andyzhangx** [comment]
@zohebs341 you should create PV, and then create PVC with naming like `volumeClaimTemplates.metadata.name-statefulsetname-num`, bound PVC to PV first, and then scale statefulset replica num
