### ISSUE TITLE
Planned Maintenance for Weekly Release

### ISSUE THREAD

**Issue by kaarthis** [Azure/AKS#3156]
This is very specific for only the AKS weekly releases and will provide integration with MRP.

**Comment by pinkfloydx33** [comment]
We're having a bit of difficulty figuring out how this differs from "Planned Maintenance"? Does [this](https://learn.microsoft.com/en-us/azure/aks/aks-planned-maintenance-weekly-releases) not include the same sort of updates that [this](https://learn.microsoft.com/en-us/azure/aks/planned-maintenance) does? 

The latter says it updates control-plane, node-images, etc. So doesn't control-plane update include the weekly AKS releases? How does that then differ from [auto-upgrade](https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-cluster)?

**Comment by marcindulak** [comment]
An older issue asking for similar clarifications https://github.com/Azure/AKS/issues/2962

**Comment by leiningger** [comment]
Currently wondering the same as well
