### ISSUE TITLE
Azure Key Vault Provider for Secrets Store CSI Driver Instructions Not Working - How to Fix?

### ISSUE THREAD

**Issue by jeffreywstevens** [Azure/AKS#3158]
The instructions say an identity within the node azureKeyvaultSecretsProvider will get created after the cluster is create enabling the Secrets CSI driver.
![image](https://user-images.githubusercontent.com/637945/187037118-bb39fc0a-7b78-4d33-9c1d-7e3cf19fa73e.png)

The identity is null in my case after the cluster gets created.
![image](https://user-images.githubusercontent.com/637945/187037251-c6105724-7fc5-42bd-a78e-7c5ab861dfee.png)

**Question**
How do I fix this?

**Comment by jeffreywstevens** [comment]
I ran the command to enable the CSI driver for an existing cluster (same one I created), and now the identity is there in the JSON.

However, I did get a warning:
**"Could not find service principal or user assigned MSI for roleassignment"**

**Comment by andyzhangx** [comment]
@ZeroMagic
