### ISSUE TITLE
[BUG] Unable to create an interactive shell on a linux node - unable to investigate node problems

### ISSUE THREAD

**Issue by BenjaminHerbert** [Azure/AKS#3161]
**Describe the bug**
I want to create an interactive shell on a linux node. I am following [this guide](https://docs.microsoft.com/en-us/azure/aks/node-access#create-an-interactive-shell-connection-to-a-linux-node).

I am running this command: 
`kubectl debug node/aks-xxx-yyy-vmss000000 -it --image=mcr.microsoft.com/dotnet/runtime-deps:6.0`

The debug pod does not start and the following messages are shown:
```
Creating debugging pod node-debugger-aks-xxx-yyy-vmss000000-gssdj with container debugger on node aks-xxx-25036223-vmss000000.
Warning: container debugger: rpc error: code = Unknown desc = failed to pull and unpack image "mcr.microsoft.com/dotnet/runtime-deps:6.0": failed to resolve reference "mcr.microsoft.com/dotnet/runtime-deps:6.0": failed to do request: Head "https://mcr.microsoft.com/v2/dotnet/runtime-deps/manifests/6.0": dial tcp: lookup mcr.microsoft.com on [::1]:53: read udp [::1]:49811->[::1]:53: read: connection refused
```

**To Reproduce**
1. Run command `kubectl debug node/aks-xxx-yyy-vmss000000 -it --image=mcr.microsoft.com/dotnet/runtime-deps:6.0`
2. See error

**Expected behavior**
A debug pod should start. This would be helpful, to investigate problems on the node.

**Environment (please complete the following information):**
-  Client Version: v1.25.0
- Server Version: v1.23.8

**Additional context**
Eventually, this is relevant: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1988119

**Comment by cubed-it** [comment]
I observe a similar issue. At first I thought our ACR was the source, but I could also generate the same message in two AKS systems against Docker Hub.

```
Failed to pull image "docker.io/alpine:3.13": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/alpine:3.13": failed to resolve reference "docker.io/library/alpine:3.13": failed to do request: Head "https://registry-1.docker.io/v2/library/alpine/manifests/3.13": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:45344->[::1]:53: read: connection refused
```

**Comment by saloyiana** [comment]
Facing same issue

**Comment by miwithro** [comment]
I was able to run the command without issue.

kubectl debug node/aks-nodepool1-xxxxxxxxx-vmss000000 -it --image=mcr.microsoft.com/dotnet/run
time-deps:6.0

Is this still an ongoing issue?  I see from a command above a reboot resolved the problem.
