### ISSUE TITLE
Release notes contain wrong link to container image description

### ISSUE THREAD

**Issue by amarkevich** [Azure/AKS#3163]
Release 2022-08-14 https://github.com/Azure/AKS/releases/tag/2022-08-14
points to    https://github.com/Azure/AKS/blob/AKS/vhd-notes/aks-ubuntu/AKSUbuntu-1804/2022.08.10.txt
right link is https://github.com/Azure/AKS/blob/master/vhd-notes/aks-ubuntu/AKSUbuntu-1804/2022.08.10.txt

**Comment by alexeldeib** [comment]
@miwithro @justindavies mind fixing this?
