### ISSUE TITLE
Failed to load logs: Internal error occurred: Authorization error (user=masterclient, verb=get, resource=nodes, subresource=proxy)[BUG]

### ISSUE THREAD

**Issue by zoroglucihat** [Azure/AKS#3167]
Suddenly this happened when i create deployment and statefulset. And also pods are waiting pending status

Failed to load logs: Internal error occurred: Authorization error (user=masterclient, verb=get, resource=nodes, subresource=proxy)[BUG]

**Comment by BenjaminHerbert** [comment]
For us, this issue did resolve after we fixed the node DNS problems, please see https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1988119 for possible workarounds. :crossed_fingers:

**Comment by n3wt0n** [comment]
We are still seeing this error, in our production ALS cluster. 
Even on new nodes, which accordingly to the linked thread should not happen.

Also tried the workarounds, including this:
```
kubectl get no -o json | jq -r '.items[].spec.providerID' | cut -c 9- | az vmss run-command invoke --ids @- \
  --command-id RunShellScript \
  --scripts 'grep nameserver /etc/resolv.conf || { dhclient -x; dhclient -i eth0; sleep 10; pkill dhclient; grep nameserver /etc/resolv.conf; }'
 ```
but no luck.

What I do when a Pod goes in `ImagePullBackOff` and the ` stream logs failed Internal error occurred: Authorization error (user=masterclient, verb=get, resource=nodes, subresource=proxy)` log is displayed for the containers on the same node is cordon / drain the node (which in turns create a new one) and everything works for a while...

but a day or 2 after, the same happens again

**Comment by n3wt0n** [comment]
Also, seems like the pods on the nodes in which this is happening are not able to report their CPU / Memory usage

![image](https://user-images.githubusercontent.com/13121206/189034332-d43d22f7-c2e7-4c5e-a9ab-25ac40427cad.png)

the pods marked in yellow are the ones where the problem is at the moment

**Comment by AllenWen-at-Azure** [comment]
Hi @n3wt0n do you still find such error in your cluster?
