### ISSUE TITLE
All  new node pools should inherit --enable-encryption-at-host configuration from AKS cluster 

### ISSUE THREAD

**Issue by ivanthelad** [Azure/AKS#3168]
When a AKS cluster is configured with --enable-encryption-at-host then all additional node pools added to the cluster should inherit this configuration. Today this is not the case.  all new nodepools do not get this configuration

**Comment by andyzhangx** [comment]
hi, `enable-encryption-at-host` is a node pool property, so other node pool won't inherit, also there is vm sku limitation with `enable-encryption-at-host` feature, so it's appropiate to inherit this property if specific vm sku does not support enable-encryption-at-host
