### ISSUE TITLE
kubectl config set-credentials

### ISSUE THREAD

**Issue by YvonneArnoldus** [Azure/AKS#317]
Is it possible to use `kubectl config set-credentials kubernetes-admin --username=xxx --password=xxx` to connect to AKS?

I can connect fine after `az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKSCLUSTER_NAME`.

But I'm trying to see if I can do an automatic deploy to AKS using BitBucket, which can not do `az login`.

I tried using the service principal appId as username and the service principal password as password but then the connection is forcefully closed.

**Comment by jnoller** [comment]
Closing as stale
