### ISSUE TITLE
[Question] HTTP Proxy being automatically injected into Pods

### ISSUE THREAD

**Issue by brunomiguel-teixeira** [Azure/AKS#3174]
**Describe scenario**
We are recently testing the HTTP Proxy Support added for AKS (https://docs.microsoft.com/en-us/azure/aks/http-proxy). 
We deployed an AKS cluster with the HTTP_PROXY, HTTPS_PROXY & NO_PROXY defined (the values are not relevant here).

**Question**
As per the documentation, it was our understanding that these HTTP Proxy settings (http_proxy, https_proxy, no_proxy etc) were intended for node bootstrapping operations for subnets behind corporates firewalls etc.

From the docs
`Previously, in environments requiring internet access to be routed through HTTP proxies, this was a problem. Nodes had no way of bootstrapping the configuration, environment variables, and certificates necessary to access internet services.`

It seems, though, that these HTTP Proxy settings are also being injected into ANY created pod. They seem to be added via the **aks-webhook-admission-controller** mutation webhook.

AKS itself automatically populates the no_proxy fields with common values (kconnectivity, 127.0.0.1, etc). However, it does not populate with the ".cluster.local" (& similar). This, due to the injection of http proxy into the pods, is effectively sending all k8s traffic via http proxy for deployed clients.

This feels a lot like intended behaviour. Is this automatic injection intended? It does not feel clear in the documentation this "additional behaviour".  Can we get some clarification on this behavior?

**Comment by alexeldeib** [comment]
The webhook is intentional, the fact that it causes so many issues with k8s native traffic is not. part of the issue is we don't know in advance all the namespace/service names end users will pick up. 

> However, it does not populate with the ".cluster.local" (& similar)

Including cluster.local would work for in-cluster FQDN, but not for `$service.$ns` and similar for pods. We could change the webhook to inject _all_ namespace/service names, but doing pod names wouldn't be scalable IMO, so something will break. 

I'm totally open to suggestions on how this should work, if anyone has better ideas.

**Comment by dhirschfeld** [comment]
With terraform they suggest putting the nodepool subnet in the `NO_PROXY` variable which IIUC would mean any internal communication would bypass the proxy.

![image](https://user-images.githubusercontent.com/107382673/190115893-c60163c8-5a07-4ff7-8035-9b7d620b554f.png)

**Comment by brunomiguel-teixeira** [comment]
Hi @dhirschfeld 

Actually AKS itself populates the no_proxy fields with specific cluster deployment values. `kconnectivity, 127.0.0.1, SUBNET_CIDR` are all injected.

The thing is that even if you place subnet cidr in the no_proxy section, it will not be honored because clients rarely use IPs. Any client connecting via domain name (ex: my-awesome-service.default.svc.cluster.local) will go through the proxy, even if the resolved IP is indeed in the no_proxy field. Only if the specific (or suffix) is in the no_proxy fields, are the proxy fields ignored and a direct connection is attempted.

So adding subnet cidrs to the no_proxy is not a valid generic approach.

Is there any possibility of this behaviour (the envvar pod injection) being toggleable?

Cheers.

**Comment by brunomiguel-teixeira** [comment]
Hi @alexeldeib 

>  you can fully opt out of all env var injection per pod using this annotation (need to doc this): kubernetes.azure.com/no-http-proxy-vars: "true"

Just gave it a sanity check and it does indeed work as expected. It beats just injecting empty envvars which can cause odd behaviour for some clients. We will be leveraging this toggle. Thanks a lot.

You can close this issue, or keep it open until this annotation its documented.

Cheers,

**Comment by alexeldeib** [comment]
still pending a doc update -_-
