### ISSUE TITLE
[BUG] Cluster jammed to ReconcilingClusterETCDCertificates state

### ISSUE THREAD

**Issue by VMM-Mtech** [Azure/AKS#3178]
**Describe the bug**
Our cluster shows Status as "ReconcilingClusterETCDCertificates (Running)". It has one node pool, which state is Succeeded/Running, but all nodes are "Not ready". 

**Environment (please complete the following information):**
 - Kubernetes version 1.22.6

**Additional context**
We suspect that this is somehow related to https://app.azure.com/h/2TWN-VT0/6d038e.

We can't restart the nodes or stop/start the cluster, "OperationNotAllowed" is thrown.

Any ideas what we could do? Our services have been down at least for hours because of this...

**Comment by benchwang** [comment]
Sorry for the inconvenience. I'm dev from aks team. Would you share your subscription id, resource group name and cluster name? I will check and fix the Status. The fix won't impact your cluster. I'll check log and update back of the cause.

**Comment by VMM-Mtech** [comment]
Do you have a Microsoft email account where I could send those?

**Comment by VMM-Mtech** [comment]
Sorry for the late update. With the help from @benchwang our cluster was recovered.
