### ISSUE TITLE
[BUG] Autoscaler stuck in infinite loop

### ISSUE THREAD

**Issue by tomasgiden** [Azure/AKS#3179]
**Describe the bug**
We are running jobs on GPU instances. For that we have set up multiple GPU enabled node groups. To save cost we have set up a few different ones as spot instances (called gpu1*) and 1 node group as you go with pay as you go instances (called gpu00). I have set up the expander to work with priority and configured the priority to prioritize the spot instances first and the pay as you go instance below that:

apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    10:
      - .\*gpu0.\*
    20:
      - .\*gpu1.\*

Here is the sequence which is happening:

1. New job is created
2. Custer autoscaler realizes it needs a new node for it
3. Cluster autoscaler sees that the node groups gpu10, gpu13 and gpu14 has the highest priority and decided (by random) to use gpu10
4. gpu10 nodegroup fails to scale because of capacity restrictions _(I read that as no available spot instance)_
5. Cluster autoscaler disables scaling of gpu10 for 5 minutes _(this is good and as expected)_
6. Cluster autoscaler sees that the node groups gpu13 and gpu14 has the highest priority and decided to use gpu13
7. "azure_scale_set.go" says it fails to update the capacity for gpu13 because of OverconstrainedAllocationRequest
8. gpu13 is NOT disabled
9. Cluster autoscaler sees that the node groups gpu13 and gpu14 has the highest priority and decided (by random) to use gpu13
10. "azure_scale_set.go" again says it fails to update the capacity for gpu13 because of OverconstrainedAllocationRequest
11. Repeat infinitely from step 6 but sometimes with gpu14 chosen by random

The gpu13 node group is using Standard_NC12s_v3 and gpu14 is using Standard_NC6s_v3. The reason why we get OverconstrainedAllocationRequest for these node groups is not the question. But I am expecting the cluster autoscaler to disable these node groups for a little while (just as with gpu10) and realize there are no high priority node groups left and then fall back to gpu00. But it never does.

Attaching a log from one iteration in the infinite loop (step 3-9 above) for the cluster autoscaler.
[log.txt](https://github.com/Azure/AKS/files/9488938/log.txt)

**Environment (please complete the following information):**

 - Kubernetes version 1.24.0

**Comment by AllenWen-at-Azure** [comment]
Hi @tomasgiden do you still find such issue in your cluster with higher version than 1.24?
