### ISSUE TITLE
[Getting this error when running kubectl exec error: unable to upgrade connection: Authorization error (user=masterclient, verb=create, resource=nodes, subresource=proxy)]

### ISSUE THREAD

**Issue by deepak1185** [Azure/AKS#3180]
**Describe the bug**
Getting this error when running kubectl exec error: unable to upgrade connection: Authorization error (user=masterclient, verb=create, resource=nodes, subresource=proxy)] when running the belwo command

kubectl exec -it -n nginx-ingress nginx-ingress-controller-64bf68d79b-4sdwg -- /nginx-ingress-controller --version

**To Reproduce**
1. kubectl exec -it -n nginx-ingress nginx-ingress-controller-64bf68d79b-4sdwg -- /nginx-ingress-controller --version
2. Unable to use a TTY - input is not a terminal or the right kind of file
error: unable to upgrade connection: Authorization error (user=masterclient, verb=create, resource=nodes, subresource=proxy)

**Expected behavior**
give the nginx version in the inside the POD

**Screenshots**

**Environment (please complete the following information):**
 - Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.19", GitCommit:"ea947be6fad5815bceb695a65a988759a30cda91", GitTreeState:"clean", BuildDate:"2021-05-25T01:16:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.18) exceeds the supported minor version skew of +/-1

**Additional context**
Its the Azure AKS cluster using the local RBAC, all other clusters with same configuration are fine except this one

**Comment by n3wt0n** [comment]
Related to #3167

**Comment by AllenWen-at-Azure** [comment]
Hi @deepak1185 do you still experience such error in your cluster?
