### ISSUE TITLE
[BUG] Container Insights does not support the "Resource-level" access with underlying Log Analytics workspace

### ISSUE THREAD

**Issue by stephaneey** [Azure/AKS#3184]
**Describe the bug**
When enabling Container Insights, logs are ingested into a Log Analytics workspace. This workspace's access control mode is set to _Use resource or workspace permissions_. Despites of this, users that don't have direct workspace permissions cannot access Container Insights, which clearly states:

`You do not have required permissions to access Container Insights for this cluster. Please check with your administrator regarding access to Azure Log Analytics workspace xxx`

The users is being granted the _Azure Kubernetes Service Cluster User Role_. Any resource-level role does not work. 

**To Reproduce**
1. Create a log analytics workspace with resource-level access mode
2. Create a cluster with Azure AD authentication with Kubernetes RBAC (it seems that none of the options work anyway)
3. Enable Container Insights
4. Give users some permissions over the cluster  but not in the underlying workspace
5. Let a user access container insights ==> forbidden

**Expected behavior**
Users should have a limited access to the underlying log analytics workspace through their resource-level permissions.

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes version: 1.23.8

**Comment by tvdvoorde** [comment]
Can confirm this problem - we observed it as well. We had to implement a custom role on the LAW to make Container Insights work, but not expose every table in LAW

**Comment by vdiec** [comment]
Hi @stephaneey @tvdvoorde , we have added a story for this. I'll message back with more details once it's rolled out. Thank you!

**Comment by deagraw** [comment]
This is currently being worked on, the current ETA we have for this work is end of next month.

**Comment by vdiec** [comment]
Hi @stephaneey @tvdvoorde, the current eta for this to be publicly available is the end of August. Please reach out to askcoin@microsoft.com if you would like to try a private flight.

**Comment by vdiec** [comment]
Hi @stephaneey @tvdvoorde , this feature has been rolled out! If you do not have resource-level query access, you will see a warning warner with a link to [documentation](https://learn.microsoft.com/en-us/azure/azure-monitor/faq#why-do-i-see-info-banner--you-do-not-have-the-right-cluster-permissions-which-will-restrict-your-access-to-container-insights-features--please-reach-out-to-your-cluster-admin-to-get-the-right-permission--).
