### ISSUE TITLE
[Question] How are kube-system images built and maintained (for ARM migration)

### ISSUE THREAD

**Issue by asubmani** [Azure/AKS#3188]
**Describe scenario**
Would like to get guidelines on image building and maintenance from various PG's within AKS practice. (omsagent, aadpodidentity, gitops addon etc.)

**Question**
How are the various product groups that have code in `kube-system`  building and maintaining their images.
I ask this as we are testing the newly released ARM architecture VM's and all of the MS released pods are running fine e.g.
  - omsagent
  - coredns
  - konnectivity-agent
  - aadpodidentity
However 3rd party  pods like "sumologic, appdynamics" are in `CrashLoopBackOff` state.  

MSFT's Dockerfile + build parameters for building images from scratch would be nice to look at if they are shared publicly.

**Comment by alexeldeib** [comment]
we build multiarch docker images for both amd64 and arm arch. the actual pipelines are not unfortunately public. but it's relatively easy with tools like buildx - https://docs.docker.com/build/buildx/multiplatform-images/
