### ISSUE TITLE
Set default AKS version to 1.9.x

### ISSUE THREAD

**Issue by ThorstenHans** [Azure/AKS#319]
When creating a new AKS cluster using `az aks create` it still spins up a cluster with `1.8.1`. Would be nice to have `1.9.x`

**Comment by slack** [comment]
Couple of comments.

1. Make sure you are using a recent version of `az` CLI. We moved the default from CLI to service-side a few releases ago (should be 1.8.11 as of Tuesday)
2. Next week, we are bumping the version to 1.9.6
3. If using these commands in automation, I'd recommend you pin to your desired k8s version, so you control when and how you get version bumps.

**Comment by markwaldkat** [comment]
WIll it also be possible to choose 1.9.6 in the Azure portal when creating a new AKS cluster?

**Comment by ThorstenHans** [comment]
@slack 

Wouldn't it make sense to put a `default` flag in the response of `az aks get-versions`.

Help for `az aks create` tells that values can be used according to `get-versions` but it doesn't say `1.x.x` is the default version
