### ISSUE TITLE
[BUG] Deleting Flux extension fails on AKS with Windows node pool

### ISSUE THREAD

**Issue by nweseloh** [Azure/AKS#3191]
**Describe the bug**
In an AKS cluster with a Windows node pool, the command `az k8s-extension delete -g RESOURCEGROUP -c CLUSTERNAME -n flux -t managedClusters --yes`  fails to delete the flux extension.

The command creates a 'delete-fluxconfig' job in kubernetes, which in turn creates a pod that is scheduled on a Windows node, where it fails to start (because it would require to run on a Linux node).

**Solution** 
Add a node selector for 'linux' OS to the 'delete-fluxconfig' job spec:
```
nodeSelector:
  kubernetes.io/os: linux

```
**To Reproduce**
1. have an AKS with a Windows node pool
2. Run commannd `az k8s-extension create -g RESOURCEGROUP -c CLUSTERNAME -n flux -t managedClusters --yes`   to create the flux extension
3. Run commannd `az k8s-extension delete -g RESOURCEGROUP -c CLUSTERNAME -n flux -t managedClusters --yes`   to delete the flux extension
4. See that the flux extension is not deleted

**Expected behavior**
The flux extension should be deleted.

**Environment (please complete the following information):**
 -  CLI Version 2.39.0
 - Kubernetes version 1.24.3

**Comment by wangyira** [comment]
@allyford, @AbelHu can you help with this?

**Comment by AbelHu** [comment]
Thanks for reporting the issue, @wangyira. We have notified the owner of the flux extension.
