### ISSUE TITLE
[Feedback] Improve patch notes for breaking changes

### ISSUE THREAD

**Issue by corstuur** [Azure/AKS#3199]
**Describe your scenario**
On 09-09-2022 we upgraded an AKS cluster to 1.24.3. After this we noticed that all our applications that were using a loadbalancer IP were broken and we could no longer access websites running on the clusters. It cost us a lot of time to figure out what the problem was. We looked at the patch notes but we could not find anything that was related to our situation or that could cause a problem like this. After a long troubleshooting session we found out that the problem was due to a change related to "appProtocol" support and that we had to add a option to our helm release to fix the health check for the AKS loadbalancer.

The problem was that the health check for the loadbalancer ip's were not working anymore. For details see #2903 and specifically the comment made by @feiskyer 

**Feedback**
If there is a big change like this then there should be something in the patch notes. It is really bad that we could only find the solution in a github issue and not in the patch notes.

**Comment by feiskyer** [comment]
Release notes would be added by https://github.com/Azure/AKS/pull/3215.
