### ISSUE TITLE
Cluster no longer accepting connections

### ISSUE THREAD

**Issue by blackbaud-brandonstirnaman** [Azure/AKS#32]
I've had a 1.7 cluster sitting there for a few days, we've been connecting to it semi-regularly but its not running any pods that weren't included by default except for Tiller.

Today we went to start doing some helm work with it and kubectl commands return `Unable to connect to the server: net/http: TLS handshake timeout`. Part of playing in Preview-land for sure but where I would normally hop on my ACS nodes and debug further, I'm not sure the correct method of debugging this for AKS.

Thoughts?

**Comment by blackbaud-brandonstirnaman** [comment]
Brand new cluster experiencing same issue in westus2.

Creation command was:

```az aks create --resource-group <rg> --name <name> --agent-count 1 --agent-vm-size Standard_D4_v2 --generate-ssh-keys --service-principal <sp> --client-secret <secret> -k 1.8.1```

**Comment by espiatsundiogroup** [comment]
I have same issue. 
I've had a 1.8 cluster, on yesterday was working fine, but today it's impossible to connect. I obtain same error than @blackbaud-brandonstirnaman "Unable to connect to the server: net/http: TLS handshake timeout. "

**Comment by ankurkhemani** [comment]
I am having similar issue.

**Comment by Guillaume-Mayer** [comment]
`az aks create` and `az aks browse` worked for me, but not `az aks scale`.

**Comment by bramvdklinkenberg** [comment]
same error here with multiple clusters in different regions

**Comment by qmfrederik** [comment]
I'm seeing the same issue and the response I'm getting so far is to re-create the AKS cluster:
https://stackoverflow.com/questions/47207651/unable-to-connect-aks-cluster-connection-time-out

**Comment by bramvdklinkenberg** [comment]
I created a support request and got a response that they know about the issue and the microsoft product team is working on it to solve it.

**Comment by mistertown** [comment]
I had the same issue - working fine on 8/11, not working on 9/11.  This is in ukwest.

Recreated the cluster from scratch on 9/11 (running through the demo at https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough) and it's still running successfully today.

**Comment by wified** [comment]
Just dont try upgrading your nodes. Was working fine up until i requested an upgrade to 1.8.2 yesterday. Now its not working, have also tried recreating in westus2 but it seems worse there.

**Comment by artisticcheese** [comment]
Microsoft knows about it and yet status is "green checkbox" on their status page (https://azure.microsoft.com/en-us/status/)

**Comment by adhodgson1** [comment]
I had same experience in UK West, created cluster on 08/11 and it was working, not working on 10/11.  Re-created it and it was working on 10/11, not working on 13/11.  Have deleted now and will leave it be for the time being as I have other work that needs completing.

**Comment by slack** [comment]
Thanks for your patience through our preview. We have found and fixed a number of bugs around scale and upgrade. I'm going to close out this issue, please open new issues if problems pop up again.
