### ISSUE TITLE
AKS 1.22.11 - Scaling down specific pods - Statefulsets [Question]

### ISSUE THREAD

**Issue by zohebs341** [Azure/AKS#3200]
**Describe scenario**
We are running mongodb statefulset in production and using Azure AKS 1.22.x version.

Scenario is like, mongodb is having 2 replicas and I'm trying to take snapshot of existing PVC by scaling down replica to 1 from replicas:2

It will terminate pod-2 and will become 1/1, I will take snapshot and will create ZRS volume with same PVC name and will scale back to replicas:2. Till here, no problem.

Now how can I scale down pod-1, if statefulset replicas is 2. As for statefulsets, pod termination happens from down to top.

**Question**

Is there a way to scale down pod-1 in above use case? Pod-2 should be up. It's like one by one, I'm scaling and Bringing up.

**Comment by carvido1** [comment]
Hello @zohebs341 .

Have you tried to create 2 statefulsets with a label to point the service to them?
This way you can control each one in an independent way.

This is the unique way I'm thinking to resolve your problem without service disruption, considering you always need a replica working.
BR

**Comment by zohebs341** [comment]
@carvido1 Thanks for your response Carlos. For a statefulset with 2 replicas, I feel like it's not possible to bring down specific pod.

Actually I'm using bitnami helm chart for mongodb deployment, which will create 2-3 statefulsets for different purposes.

As mongodb work's in a clustered way, I've to maintain two replicas for that statefulset and cannot make it different statefulset with one -one replica as you suggested.



,
