### ISSUE TITLE
Detect API Breaking changes before Upgrade

### ISSUE THREAD

**Issue by kaarthis** [Azure/AKS#3203]
Understand if customers use deprecated API calls. Fast fail on upgrade and potentially pause Auto upgrades especially if deprecated API calls are noticed.

**Comment by ezYakaEagle442** [comment]
@kaarthis would this rely on [https://github.com/doitintl/kube-no-trouble](https://github.com/doitintl/kube-no-trouble) ?

**Comment by denniszielke** [comment]
@kaarthis : will this also be available as API that can be executed before an upgrade. Most customers do not use the portal so having an API for your IaC pipeline would be great.

**Comment by lgmorand** [comment]
+1 with Dennis. Lot of customers are asking for it. An API (or cli command, i.e: az aks upgrade --dry-run) would be awesome.

**Comment by wasker** [comment]
I'm more concerned with how to learn about incompat issues when AKS cluster is configured to auto-upgrade.

**Comment by ivanthelad** [comment]
@kaarthis will there be a "--dry-run" api.

**Comment by PixelRobots** [comment]
Hey @kaarthis do we have a docs page on this? I could not find any changes in the git history.

**Comment by clarenceb** [comment]
> Hey @kaarthis do we have a docs page on this? I could not find any changes in the git history.

See: https://learn.microsoft.com/en-us/azure/aks/upgrade-cluster?tabs=azure-cli#stop-cluster-upgrades-automatically-on-api-breaking-changes-preview

**Comment by tgolly** [comment]
+1 here too.  As a customer I would love this.  I had a problem recently with the upgrade to Kubernetes v1.26, I was repeatedly getting this error on upgrade attempts:

> usage has been detected on API autoscaling.horizontalpodautoscalers.v2beta2.watch, and was recently seen at: 2023-08-29 17:48:42 +0000 UTC, which will be removed in 1.26

When all my HPA resources were at .v1.  None at .v2beta2.

It took me a while to track down the problem with the help of Azure support, but in the end it was not a HPA resource itself, but a `managedField` reference inside a .v1 HPA resource.

A dry-run tool that not only told you which deprecated APIs were being hit, but also which resources contained references to deprecated APIs (inc. `managedFields`) would be _magnificent_.

**Comment by tsivachi** [comment]
Would breaking API changes cover identifying deprecations with addons like KEDA or its all about K8S deprecated API? 

The documentation started covering breaking changes for addons here: https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-components-breaking-changes-by-version

So wondering if the breaking API changes feature will list AKS addon changes and stop cluster upgrades

**Comment by samrui** [comment]
> +1 here too. As a customer I would love this. I had a problem recently with the upgrade to Kubernetes v1.26, I was repeatedly getting this error on upgrade attempts:
> 
> > usage has been detected on API autoscaling.horizontalpodautoscalers.v2beta2.watch, and was recently seen at: 2023-08-29 17:48:42 +0000 UTC, which will be removed in 1.26
> 
> When all my HPA resources were at .v1. None at .v2beta2.
> 
> It took me a while to track down the problem with the help of Azure support, but in the end it was not a HPA resource itself, but a `managedField` reference inside a .v1 HPA resource.
> 
> A dry-run tool that not only told you which deprecated APIs were being hit, but also which resources contained references to deprecated APIs (inc. `managedFields`) would be _magnificent_.

hi, golly,  I have the same issue. How do you find the real resource which includes "autoscaling.horizontalpodautoscalers.v2beta2.watch" ?

**Comment by tgolly** [comment]
@samrui  Azure support helped me find it in the end.  

But since then I've been running this Helm plugin on my services before performing upgrades:

https://github.com/helm/helm-mapkubeapis

It displays on screen any deprecated APIs in use and fixes them.  

You could run this in your non-prod environment and it will tell you where the problem is.

**Comment by yavuzakyuz** [comment]
Hi @tgolly, are you sure about mapkubeapis is able to show the managedField reference to .v2beta2. ? 
It doesn't seem to find them, as I've ran it then recieved the same error.

**Comment by tgolly** [comment]
Hi @yavuzakyuz, I thought it did.  

I ran it before doing a heap of cluster upgrades a couple of months ago and it solved the problem for me.

**Comment by kaarthis** [comment]
thanks @tgolly for confirming. @yavuzakyuz if you see it in portal (diagnostic blade ](https://learn.microsoft.com/en-us/azure/aks/stop-cluster-upgrade-api-breaking-changes#remove-usage-of-deprecated-apis-recommended) then it should be flagged on upgrade operation too.
