### ISSUE TITLE
Deleting Kubernetes secret when scale down the deployment - Secrets Store CSI Driver

### ISSUE THREAD

**Issue by esquare666** [Azure/AKS#3204]
**Describe scenario**
We have deployed AKS and enabled with --enable-addons azure-keyvault-secrets-provider. We have created a SecretProviderClass, use the secretObjects field to define the desired state of the Kubernetes secret. All working fine.

**Question**
As per the document (https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver), When all the pods that consume the secret are deleted, the Kubernetes secret is also deleted.

Is that mean secrets will be deleted only deleting the deploy (lets say kubectl delete <deploy>) or the secrets will delete if we scale down the deployment (kubectl scale --replicas=0 deploy/**)?

**Comment by wangyira** [comment]
@miwithro could you help answer this?

**Comment by esquare666** [comment]
Any updates would be greatly appreciated.

**Comment by ZeroMagic** [comment]
> the secrets will delete if we scale down the deployment (kubectl scale --replicas=0 deploy/**)

@esquare666 This one is right.
