### ISSUE TITLE
[BUG] Privileged Access Group feature not updating access rights timely using AKS API

### ISSUE THREAD

**Issue by geertn** [Azure/AKS#3211]
**Describe the bug**
Using Managed AAD (https://docs.microsoft.com/en-us/azure/aks/managed-aad) in combination with functionality of Privileged Access Groups (https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/groups-features) only works properly when using the Azure Portal to see the Kubernetes resources (Workloads/Namespaces/...). When using the AKS API (e.g. using kubectl) the group activation is not activated/deactivated in time. 

**To Reproduce**

1. Setup a Privileged Access Group and assign this group rights on AKS (e.g. "Azure Kubernetes Service Cluster User Role" on the cluster & "Azure Kubernetes Service RBAC Writer" on a namespace.
2. Use PIM to activate membership of the group
3. Test access to AKS 
- Using the portal (AKS->Kubernetes resources->Workloads/Namespaces/...) this works quickly
- Using the AKS API (eg. `kubectl get pods -n test-ns`) access doesn't work for a long time (maybe an hour or more)
4. Deactivate membership of the group
- Using the portal (AKS->Kubernetes resources->Workloads/Namespaces/...) access gets revoked quickly
- Using the AKS API (eg. `kubectl get pods -n test-ns`) access is still possible for a long time (maybe an hour or more)

It's my observation that when upgrading the API to a paid SLA this resets the cache/ticket and it starts working immediately. However once upgraded the same behavior is shown again.

**Expected behavior**
1. I expect that access to the resources through the portal and AKS API show similar behavior with regards to activating Group Membership using Privileged Access Groups
2. I expect that when deactivating membership of a group that my access rights are revoked within 5 minutes
3. I expect that when activating membership of a group that my access rights are activated within 5 minutes

**Environment (please complete the following information):**
```
kubectl version --short
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.24.3

kubelogin version 
git hash: v0.0.20/872ed59b23e06c3a0eb950cb67e7bd2b0e9d48d7
Go version: go1.18.5
Build time: 2022-08-09T18:30:45Z
Platform: linux/amd64

AKS version 1.24.3
local accounts disabled
AKS Managed AAD enabled
```

**Comment by geertn** [comment]
After more testing it seems that the seemingly different behavior of the portal interface and the AKS API interface is due to caching of access rights to various resources.

After deactivating the Group Membership it is possible to repeatedly execute a command for a long time. Eg:
`k delete pod nginx -n test`

However if I don't execute "k get pods -A" for a while it seems the cache is invalidated and the command becomes unavailable.

**Comment by wangyira** [comment]
@miwithro could you take a look at this?

**Comment by geertn** [comment]
We have worked around this (use PIM for Privilege Escalation instead of Privileged Access Group). Closing this issue since I expect this to be hard to solve and given the lack of responses I don't think this stands any chance of being picked up any time soon.
