### ISSUE TITLE
All external / egress traffic is blocked

### ISSUE THREAD

**Issue by derekperkins** [Azure/AKS#322]
I'm unable to even ping any websites from inside my cluster. This is the default NSG that was set up in the cluster resource group, but I'm unable to make any changes. What do I need to do in order to allow pods to make external connections?

![image](https://user-images.githubusercontent.com/3588778/39215570-9357bee0-47d5-11e8-906b-d38e6e9f6c7a.png)

**Comment by derekperkins** [comment]
I'm reading through #189 and wondering if I'm maybe hitting SNAT exhaustion. There is near zero traffic on this test cluster, so I would be surprised if that were the case. I have 1 load balancer with 2 public ips in my 3 node cluster: 1 for my ingress controller and 1 that exposes my database. 

If I'm understanding correctly, that should allow me 2,048 connections per node[1]. With my current setup, there should be no more than 3-4 active outbound connections per node.

I'm very confused about how to debug this any further and would appreciate any help in getting this figured out.

[1] https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#snatexhaust

**Comment by baracoder** [comment]
I had a similar problem today: Pods could not initiate connections anywhere. Then I have checked with another pod and it worked without any problem. Restarting the pods "solved" it, but I have no idea if it will happen again or what to look for.
Running `v1.9.6` here.
