### ISSUE TITLE
[Question] Gateway API support

### ISSUE THREAD

**Issue by dmeytin** [Azure/AKS#3224]
**AKS support of Gateway API**
Gateway API allows better segregation of concerns between Cloud Providers (Azure), Kubernetes administrators (SRE team) and service owners (SWE team). In addition, Gateway class allows to define multi-cluster Gateways that are capable to load balance between Kubernetes clusters at specific route granularity. Additional features are native support of canary and blue-green deployment strategies and better traceability.

**Question**
When should we expect Gateway API support on AKS with all features mentioned in the description?

The roadmap video could be found here: https://www.youtube.com/watch?v=aJqr8E4bQbc

**Comment by tomkerkhove** [comment]
You might want to check https://github.com/Azure/AKS/issues/3198

**Comment by qpetraroia** [comment]
Closing this issue. Please continue the conversation here https://github.com/Azure/AKS/issues/3198
