### ISSUE TITLE
AKS 1.23.8-  PV in terminating State - statefulset [Question] #3169Question]

### ISSUE THREAD

**Issue by zohebs341** [Azure/AKS#3226]
**Describe scenario**
Workloads are running in Azure AKS 1.23.8 and it's statefulsets which are having PVCs/PVs attached.

Accidentally PVs got deleted and it's in terminating State and the reclaim policy is retain.

PVCs are still in bound state and PVs in terminating State.

**Question**

As reclaim policy is retain, as PVs got deleted. Hopefully still it will work as in backend the PV will be available.

My question is, how about if pods got restarted? Will it crash? Or is they a way to recover that PV which is in terminating State.

**Comment by andyzhangx** [comment]
as I know, as long as pod is not deleted, pv won't be deleted. And you cannot recover that PV, just copy the PV config, delete pod, let pv get deleted, and then recreate pv with same config.
