### ISSUE TITLE
The Cluster is in a failed state.

### ISSUE THREAD

**Issue by nickkotchauri** [Azure/AKS#3231]
The Cluster is in a failed state, But everything is OK. 
Cannot upgrade version. thanks
![Screenshot from 2022-09-27 13-15-25](https://user-images.githubusercontent.com/59885287/192486618-229699e4-3c6e-49bf-95a5-4634c784a9dd.png)

**Comment by andbaraks** [comment]
Hello @nickkotchauri! There may be other reasons for the cluster to get into failed state except the insights you posted. I would recommend you to open a support request so a support engineer will look closely into your cluster and clarify why it got into failed state. Thank you!

**Comment by CocoWang-wql** [comment]
Hello @nickkotchauri , is there any error message when you try to upgrade the cluster?
