### ISSUE TITLE
Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data config]: timed out waiting for the condition

### ISSUE THREAD

**Issue by ojordano** [Azure/AKS#3241]
Hello all;

I actually have an AKS running in Azure and have some application attached with disk automatically provisionned while launching helm charts.

I tried to backup one application disks, including a mariadb pv in case i need to restore if any issue.

Now, i have restored the backup to a disk and trying to deploy it as a PV volume disk attached to the AKS in a test namespace to see if it is working.

But unfortunately the pods are giving this error :

`FailedMount          pod/name-test-mariadb-0                                       Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data config]: timed out waiting for the condition`

Below the pv and pvc applied : 

<pre>
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: test
  name: pv-restore
spec:
  capacity:
    storage: 8Gi
  csi:
    driver: disk.csi.azure.com
    volumeHandle: /subscriptions/id/resourceGroups/rg_name/providers/Microsoft.Compute/disks/backup_disk_name
    volumeAttributes:
      csi.storage.k8s.io/pv/name: pv-restore
      csi.storage.k8s.io/pvc/name: pvc-name
      csi.storage.k8s.io/pvc/namespace: test
      requestedsizegib: '8'
      skuname: StandardSSD_LRS
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: test
  name: pvc-name
spec:
  storageClassName: default
  volumeName: pv-restore
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
</pre>

Can you please help on this??

@andyzhangx

**Comment by andyzhangx** [comment]
so is that disk already attached to the agent node? follow this guide to create static pv/pvc: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/e2e_usage.md#azuredisk-static-provisioninguse-an-existing-azure-disk, and also make sure the cluster identity has write access to the disk

**Comment by andyzhangx** [comment]
> When i do a get volumeattachment , i can see the disk but the **ATTACHED** state is false

@ojordano could you file an azure ticket to check why disk attach failed? pls check whether cluster identity has write access to the disk first, thanks.

**Comment by ojordano** [comment]
Hello @andyzhangx 
tried the creation with example link shared.

The pod have the same error : 

`Warning  FailedMount         86s (x2 over 5m58s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data config]: timed out waiting for the condition`

The volume attachment state too is false : 

<pre>
NAME                  ATTACHER               PV                     NODE               ATTACHED          AGE
csi-                 disk.csi.azure.com     pv-name         aks-nodepool1            false                3m12s
</pre>

**Comment by andyzhangx** [comment]
pls file a support ticket with any subsid or cluster info, without those info, we cannot tell what's going wrong
