### ISSUE TITLE
[BUG] Regression Windows issue in k8s v1.24. Please do not upgrade your Windows clusters to k8s v1.24

### ISSUE THREAD

**Issue by AbelHu** [Azure/AKS#3246]
**Describe the bug**
Please see more details in https://github.com/kubernetes/kubernetes/issues/112836

**To Reproduce**

1. Create a Kubernetes cluster v1.24 or higher with Windows nodes.
2. Create a Kubernetes Service with type "LoadBalancer" on Windows.
3. Delete one or more pods of the Service.
4. Observe stale load balancing rule left behind referencing endpoint that was already deleted.

**Expected behavior**
It should work

**Environment (please complete the following information):**
 - Kubernetes version: k8s 1.24

**Additional context**
We are waiting the fix from upstream and will block all AKS Windows customers to upgrade to v1.24

**Comment by Kevin-Li-Webjet** [comment]
Thanks, @AbelHu , we were blocked for upgrade by this

**Comment by AbelHu** [comment]
@Kevin-Li-Webjet  We are working on the hotfixes with the fix https://github.com/kubernetes/kubernetes/pull/112839. After the hotfixes are available in all regions, we will unblock you to upgrade to v1.24.

**Comment by AbelHu** [comment]
We have published new AKS RP hotfix releases which contain the new v1.24 packages with the fix https://github.com/kubernetes/kubernetes/pull/112839. Please upgrade your cluster to v1.24.6 or create new Windows agent pools to get the fix if your clusters are in v1.24 and have been impacted by this issue.

**Comment by AbelHu** [comment]
Fixed it
