### ISSUE TITLE
[BUG] ImageCleaner bicep template needs interval specified

### ISSUE THREAD

**Issue by chitturs** [Azure/AKS#3248]
**Describe the bug**
ARM deployment fails if the interval is not specified. https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/aks/image-cleaner.md needs to add that the default is not actually in effect. We need to add a value there.

**To Reproduce**
1. Deploy a bicep template for an AKS cluster with imageCleaner setting.

**Expected behavior**
Default of 1 week should apply if nothing is specified in bicep. Alternately, fix the document to reflect the actual behavior.

**Screenshots**

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22]
 - Kubernetes version 1.24.3
 - CLI Extension version [e.g. 1.7.5] if applicable
 - Browser [e.g. chrome, safari] is applicable

**Additional context**

**Comment by sozercan** [comment]
@jiashun0011

**Comment by CocoWang-wql** [comment]
Made the statement clearer as 'cli parameter' in the doc. Thanks for the feedback.
