### ISSUE TITLE
[BUG] Unable to deploy new AKS cluster with windows nodes using bicep, since docker is no longer supported 

### ISSUE THREAD

**Issue by spdr870** [Azure/AKS#3249]
**Describe the bug**
Bicep deployment fails when creating a aks cluster with a windows node pool. Windows nodepools no longer support docker (since kubernetes version 1.24). It is not possible to deploy a new nodepool using Bicep because setting the customheader is not possible.

Since bicep is a layer above ARM, it probably also fails when using plain ARM.

**To Reproduce**
Deploy a AKS cluster using Bicep, with the follwing windows nodepool. Notice the error that the custom header is not supported. Without aksCustomHeaders you will the error that docker is no longer supported.
```
      {
        name: 'akswin1'
        orchestratorVersion: 1.24.3
        count: 2
        mode: 'User'
        osType: 'Windows'
        type: 'VirtualMachineScaleSets'
        vmSize: windowsPoolVmSize
        enableFIPS:   false
        osDiskSizeGB: 128
        aksCustomHeaders: 'WindowsContainerRuntime=containerd'
      }
```

**Expected behavior**
Since containerd is the default, the cluster should deploy without error. The validation seems incorrect to me.

**Environment (please complete the following information):**
 - Bicep version 0.11.1 
 - CLI Version 2.38.0
 - Kubernetes version 1.24.3

**Additional context**
Upgrading an existing cluster works fine. The workaround is to deploy an older version of kubernetes first. This will default to containerd. Then upgrade to 1.24.3. This only works until version 1.23 is supported.

**Comment by AbelHu** [comment]
Currently AKS only supports k8s versions v1.27+. Reference https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar. The default Windows container runtime is containerd so users do not need to use custom header.
