### ISSUE TITLE
Upgrade to Kubernetes v1.9.6 makes cluster unavailable.

### ISSUE THREAD

**Issue by slack** [Azure/AKS#325]
Wednesday April 25th, 2018

We currently have a bug in all regions that impacts customers who upgrade from 1.8.x to v1.9.6. Clusters will receive an invalid admission controller configuration and all apiservers will fail to start. This results in our favorite `TLS handshake timeout`.

We are deploying a hotfix now, but advise customers running 1.8.x to not upgrade to 1.9.6 until this issue is closed.

Customers creating 1.9.x clusters or upgrading from 1.9.x to 1.9.6 are not impacted.

Update: Friday April 27, 2018 Hotfix was pushed and cluster upgrade functionality has been restored. All impacted clusters have been fixed.

**Comment by Cisien** [comment]
What is the ETA for this issue to be resolved in the Central US region?

**Comment by rdtsai** [comment]
We are experiencing `TLS handshake timeout` just now. What is the ETA on completing rolling out the fix?

**Comment by slack** [comment]
Status update (from ticket description): Friday April 27, 2018 Hotfix was pushed and cluster upgrade functionality has been restored. All impacted clusters have been fixed.

@FernandoMorais VM extension timeouts are unrelated, could you open a support request?
