### ISSUE TITLE
Display K8s Resources on Azure Portal for Private AKS

### ISSUE THREAD

**Issue by byteknacker** [Azure/AKS#3254]
**Is your feature request related to a problem? Please describe.**
On the Azure Portal page for AKS, I cannot see any resources such as workload, namespace, services, ingress etc., because my AKS is private. Right now, it says that "Private clusters require that the browser is running on a machine that has access to the AKS cluster's Azure Virtual Network." Having this display capability reduces the need for me to provision Kubernetes Dashboard. I wish this to be part of the offering, even for private AKS. 

**Describe the solution you'd like**
It would be great if you made AKS such that I can see all the resources, even for a private AKS, just as I can with a public AKS. As far as I am concerned, this is not something I, as a user, have control over. 

**Describe alternatives you've considered**
If I have to configure DNS resolution for my private AKS, please add some documentation and guide so I can do it myself.

**Comment by liamfoneill** [comment]
You need to either use a jump box inside the azure aks vnet (or one peered to it) or if your own machine can connect to Azure via hybrid networking (vpn, expressroute) and the vpn gateway vnet is peered with the aks vnet you can also access it that way.

**Comment by byteknacker** [comment]
Ok sweet, I just managed to do that. I just have to connect my VPN Gateway locally and then the Azure Portal displays all the information. Consider this closed then.

**Comment by chandraneel** [comment]
Closing per the above comment, portal works when the browser is with in the vnet.
