### ISSUE TITLE
[BUG] Creating agent pool with invalid `nodePublicIPPrefixID` returns HTTP 500

### ISSUE THREAD

**Issue by nojnhuh** [Azure/AKS#3257]
**Describe the bug**
A request to create an agent pool with a `nodePublicIPPrefixID` that is well-formed but does not exist results in a HTTP 500 response where a 4xx status code would be more appropriate. HTTP 500 triggers retry logic in the Go SDK which is not effective in resolving this particular issue.

**To Reproduce**
1. Create an AKS cluster using a public IP prefix ID in the correct format but for a resource that doesn't exist:
    ````
    az aks create --enable-node-public-ip --node-public-ip-prefix-id subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/akstest/providers/Microsoft.Network/publicipprefixes/does-not-exist -g akstest -n akstest --node-count 1 -x --debug
    ````
2. Output shows `cli.azure.cli.core.sdk.policies: Response status: 500`

**Expected behavior**
The response code should be HTTP 4xx.

**Screenshots**

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22]
 ```
% az version
Azure-cli    Azure-cli-core    Azure-cli-telemetry
-----------  ----------------  ---------------------
2.40.0       2.40.0            1.0.8
```
 - Kubernetes version [e.g. 1.24.3]
 - CLI Extension version [e.g. 1.7.5] if applicable
 ```
% az extension list
Experimental    ExtensionType    Name             Path                                             Preview    Version
--------------  ---------------  ---------------  -----------------------------------------------  ---------  ---------
False           whl              dev-spaces       /Users/jon/.azure/cliextensions/dev-spaces       False      1.0.6
False           whl              connectedk8s     /Users/jon/.azure/cliextensions/connectedk8s     True       0.3.5
False           whl              k8s-extension    /Users/jon/.azure/cliextensions/k8s-extension    False      0.1PP.8
False           whl              deploy-to-azure  /Users/jon/.azure/cliextensions/deploy-to-azure  True       0.2.0
```
 - Browser [e.g. chrome, safari] is applicable

**Additional context**

**Comment by matthchr** [comment]
Probably not but this has been stuck for a long time let me poke on it internally.

**Comment by nojnhuh** [comment]
I can see from the command I put in the description that this has been fixed, presumably for a while. I see `Response status: 400` in the PUT. Thanks for following up!
