### ISSUE TITLE
[Feature] Fleet level AAD workload identity federation

### ISSUE THREAD

**Issue by shashankbarsin** [Azure/AKS#3267]

**Comment by sjwaight** [comment]
Fleet will utilize features being shipped elsewhere in Azure to drive the capability.

**Comment by Richard87** [comment]
@sjwaight is there a diefferent github issue we can follow?

**Comment by sjwaight** [comment]
Hi @Richard87 at this stage there isn't. Once I have further details I will update here. Note this capability is still a goal but will not be delivered directly by the fleet team.

**Comment by sql-dr-watson** [comment]
Any update on this issue and the related work on AAD side?

**Comment by sjwaight** [comment]
At this stage no updates. Once there's further information to share, we'll update our roadmap.
