### ISSUE TITLE
PodSecurityPolicy ignored in AKS cluster

### ISSUE THREAD

**Issue by rgreil** [Azure/AKS#327]
I've defined a PodSecurityPolicy which sets

>  runAsUser:
>    rule: MustRunAsNonRoot

Output from kubectl get psp

>  NAME               DATA      CAPS      SELINUX    RUNASUSER          FSGROUP    SUPGROUP   READONLYROOTFS   VOLUMES
> pod-policy-draft   false     []        RunAsAny   MustRunAsNonRoot   RunAsAny   RunAsAny   false            [*]

Kubernetes in AKS still allows containers with root user:

> kubectl exec -it pod-sample-9b5b4d4bc-4tvnq -- sh
> whoami
> root

kubernetesVersion: 1.9.6

**Comment by kmadel** [comment]
I don't believe the PodSecurityPolicy admission controller is enabled in the API server - and if that is the case the policies will just be ignored.

**Comment by rgreil** [comment]
I was under the impression, that PodSecurityPolicy is available after GA but it's still not working. Is there any information when this will be available in AKS?

**Comment by denniszielke** [comment]
Support for PodSecurityPolicy is still on the roadmap. You can look up the currently supported admission controllers here https://docs.microsoft.com/en-us/azure/aks/faq#what-kubernetes-admission-controllers-does-aks-support-can-this-be-configured

**Comment by weinong** [comment]
please post feature request to https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks
