### ISSUE TITLE
[BUG] ImageCleaner (Preview) Crashes due to OOMKILL

### ISSUE THREAD

**Issue by tshaiman** [Azure/AKS#3274]
**Describe the bug**
we deployed the new AKS Preview for ImageCleaner but it crashes due to OOMKILL and we don't have API to increase Memory

**To Reproduce**
1. install ImageCleaner on large cluster with many stale images and many nodes
2. you will see that the eraser-controller-manager Pod can be in CrashLoopBack State due to Out Of Memory

**Expected behavior**
- Either let user Specify Requests / Limit as in all K8s resources , or set a higher value rather then 20M

**Screenshots**
![image](https://user-images.githubusercontent.com/512709/195849008-53b95d62-57ba-4fcd-aacf-d3551fea297e.png)
![image](https://user-images.githubusercontent.com/512709/195849047-0972aa09-ad7a-4228-85c7-b7136732dcf0.png)

**Environment (please complete the following information):**
 -  CLI Version: 2.4.0
 - Kubernetes version : 1.23.5
 - Az AKS-Preview Extension Version : 0.5.104

**Additional context**
when we try to manually change the Requests/Limit of the deployment , values keep getting back to the defaults.
we understand this is managed Add-On but if users will not be able to configure it , it will keep crashing - thus will be unreliable.

**Comment by sozercan** [comment]
@jiashun0011

**Comment by CocoWang-wql** [comment]
We are doing some investigation and mitigating it. Will update here soon

**Comment by tshaiman** [comment]
@CocoWang-wql  : please note that release a product to the community or to internal 1P customer that crashes quite often is effecting our credibility as company.  please see if you can push this fix sooner.

**Comment by CocoWang-wql** [comment]
Hello @tshaiman , due to the holiday season, we do not release any changes this time.  The fix should be contained in v2023-01-08 release.
