### ISSUE TITLE
[Question] How to tie AKS release versions to the release notes

### ISSUE THREAD

**Issue by anhlqn** [Azure/AKS#3281]
**Describe scenario**
How to properly review and perform monthly AKS upgrades.

**Question**
Our procedure is to upgrade our AKS clusters to the latest patch version monthly. Since it's not the first time that upgrading to the latest patch version breaks some of our apps, we want to review the release notes instead of just upgrading and waiting for something to break. The challenge here is how to tie an AKS version to the release notes.

For example, if we want to upgrade from AKS v1.23.5 to the latest patch v1.23.12, there isn't a clear indication of what has been released between 1.23.5 and 1.23.12 on https://github.com/Azure/AKS/releases. The only hint is to search the page for 1.23.12 and assume that any changes before the release date that mentions 1.23.12 were changes between 1.23.5 and 1.23.12. 

> New Kubernetes patch versions released. Kubernetes 1.22.15, 1.23.12 and 1.24.6.

Example of 1.23.8

> Kubernetes patch versions 1.21.14, 1.22.11, and 1.23.8 are now available; Kubernetes patch versions 1.21.7, 1.22.4, and 1.23.3 are deprecated and removed. Learn more about Kubernetes version support policy followed by AKS [here](https://docs.microsoft.com/azure/aks/supported-kubernetes-versions?tabs=azure-cli#kubernetes-version-support-policy).

However, this doesn't always work because we couldn't find one for 1.23.5, and we aren't sure if this is the right approach.

Could someone help us understand the AKS release cycle?

Thanks,

**Comment by olsenme** [comment]
Have you tried https://releases.aks.azure.com/webpage/index.html?

**Comment by anhlqn** [comment]
> Have you tried https://releases.aks.azure.com/webpage/index.html?

Thanks, but that's the same as the link in my original post https://github.com/Azure/AKS/releases.

**Comment by qpetraroia** [comment]
Hi @anhlqn,

Would it help to include the official kubernetes patch notes in our docs going forward?
