### ISSUE TITLE
[Feature] Workload Identity MutatingWebhookConfiguration failurePolicy

### ISSUE THREAD

**Issue by jkroepke** [Azure/AKS#3286]
**Is your feature request related to a problem? Please describe.**
In some rare condition, pods are not mutated by the azure-wi-webhook-webhook-service, because the failurePolicy is set to Ignore by default.

**Describe the solution you'd like**
Set the failurePolicy to fail by default. This garantuees that pods with mentioned annotations get mutated. Otherwise, the pod misses the injected environment variables and failed to start. A manual recreation of the pod is required to solve the issue.

**Describe alternatives you've considered**
Manual patching the MutatingWebhookConfiguration results into in a revert

**Additional context**
N/A

**Comment by CocoWang-wql** [comment]
Thanks for reporting it. The issue was fixed and we set the failure policy as 'fail'~
