### ISSUE TITLE
SNAT allocated ports reset during scaling operation

### ISSUE THREAD

**Issue by dloftus98** [Azure/AKS#3288]
**Describe the bug**
We scaled a node pool and or SNAT port allocation settings were reset.  We have a support tracking number: 2210170040007066 that we are not getting any traction on.

**To Reproduce**
Scale up a node in the node pool and observe the allocated SNAT port graph.  A screenshot is included in our support case.

**Expected behavior**
SNAT settings are carried through to new nodes and existing nodes are not set back to the default 1000.

**Screenshots**
Included in our support case.

**Environment (please complete the following information):**
AKS 1.23.5

**Additional context**

**Comment by dloftus98** [comment]
Looks like this was an issue 2 years ago as well:
https://github.com/Azure/AKS/issues/1673

**Comment by VijayRod** [comment]
Is the below command being used to configure the Kubernetes LB outbound ports value?

https://learn.microsoft.com/en-us/azure/aks/load-balancer-standard#configure-the-allocated-outbound-ports

```
az aks update \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --load-balancer-managed-outbound-ip-count 7 \
    --load-balancer-outbound-ports 4000
```

**Comment by dloftus98** [comment]
> Is the below command being used to configure the Kubernetes LB outbound ports value?
> 
> https://learn.microsoft.com/en-us/azure/aks/load-balancer-standard#configure-the-allocated-outbound-ports
> 
> ```
> az aks update \
>     --resource-group myResourceGroup \
>     --name myAKSCluster \
>     --load-balancer-managed-outbound-ip-count 7 \
>     --load-balancer-outbound-ports 4000
> ```

Our Azure support eventually did get back to us explaining that the above command is the ONLY acceptable way to configure the LB.  We were using the portal to make the changes.  We suggested that there should be some warning that this would not work.
