### ISSUE TITLE
NSG Lock 

### ISSUE THREAD

**Issue by mdaguete** [Azure/AKS#329]
Hi,

One of our requeriments is to allow traffic on from our offices, we've configured aks nsg to allow this and disallow the other traffic, but every night an "allow all" rule is "magically" added. Then we lock the nsg.  Now the following message appears on aks:

```
  Warning  LoadBalancerUpdateFailed  30m (x1007 over 9d)  service-controller  
  Error updating load balancer with new hosts [aks-nodepool1-XXXXX-2 aks-nodepool1-XXXXX-0 aks-nodepool1-XXXXX-1]:
   network.SecurityGroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: 
   autorest/azure: Service returned an error. Status=409 Code="ScopeLocked"
    Message="The scope '/subscriptions/XXXXXXX_westeurope/providers/Microsoft.Network/networkSecurityGroups/aks-agentpool-XXXXXX-nsg'
     cannot perform write operation because following scope(s) are locked: 
     '/subscriptions/XXXXX_westeurope/providers/Microsoft.Network/networkSecurityGroups/aks-agentpool-XXXXX-nsg'. 
     Please remove the lock and try again."
```
All seems to work ok. But If we scale the pods behind a LoadBalancer with public IP the new pods do not receive traffic before we remove the lock.

Any idea to lock the nsg and to allow traffic for new pods ?

Thanks. Regards.

**Comment by slack** [comment]
The network security group which wraps the agent nodes is managed by the Kubernetes cloud-provider, as such, it expects to be able to modify the NSG based on cluster events. Service creation, etc. As such, there is no support for locking the NSG while at the same time allowing K8S to dynamically apply updates.

**Comment by feiskyer** [comment]
loadBalancerSourceRanges is for such case, see https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/

**Comment by jnoller** [comment]
Closing as stale
