### ISSUE TITLE
How to clean stale images from containerd environment in AKS?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/AKS#3290]
Team,

As far as I know AKS now use containerd in the backend. There are lot of stale/unused images left in the container environment of our AKS nodes.

Is there any reliable, Microsoft suggested and production ready procedure to remove those old and vulnerable images.

Kindly suggest. Thank you.

Kind Regards,
Tanul

**Comment by smartaquarius10** [comment]
Can we update these values in existing node pool of VMAS cluster

https://learn.microsoft.com/en-us/azure/aks/custom-node-configuration

**Comment by smartaquarius10** [comment]
@miwithro , Dear Michael, 
Trust you're doing well. 

As per [this announcement in kubecon](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-kubernetes-service-kubecon-na-2022-announcements/ba-p/3660682#:~:text=Public%20preview%20of%20Image%20Cleaner%20on%20AKS), is this image cleaner project production ready. Is it suggested to deploy in prod environment as it is still in preview mode.

**Comment by CocoWang-wql** [comment]
Hello @smartaquarius10, thanks for the info. The tentative GA time of ImageCleaner is end of Jan. We are waiting for the upstream stable API version. For preview feature, it's not recommended to use it in prod env~

**Comment by smartaquarius10** [comment]
@CocoWang-wql, Hey.. Thank you so much for the update. No worries. Will wait till January. Once you get any update, please let me know.

Thanks a lot for the help. Take care. Have a nice day ahead 😄
