### ISSUE TITLE
Setting resource lock on a resource in MC_ resource group prevents nodepool from scaling down

### ISSUE THREAD

**Issue by MaryamTavakkoli** [Azure/AKS#3291]
**Describe the bug**
We aim to add a Delete lock to the MC_ resource group. If the lock is set to the RG directly, it would be inherited to the all underlying resources in that RG by default. As a workaround, we set the lock to one of the resources under MC_ resource group and as a result the RG itself is also locked. This is accepted behavior, however, while there is no lock on VMSS, it still does not allow scale down of node pool. 

**To Reproduce**
1. Set Delete lock on any resource under MC_ RG, for example Load balancer
2. See that lock is inherited to MC_ RG but not to the VMSS
3. Try to scale down user nodepool from 2 nodes to 1
4. See error:

```
Failed to scale node pool 'userpool' in Kubernetes service 'xxx'. Error: Resource group 'MC_xxx_xxx_eastus' under subscription: 'xxx' is locked, please remove lock and retry. Please see http://aka.ms/azure-lock-resources
```

**Expected behavior**
There is no reason specified for this behavior in Azure documentation.

**Comment by mykolaichuk** [comment]
I have the same issue. Is there any doc about how to treat resource locks against AKS properly? For example, overcoming the accidental removal of public IPs is crucial. But when we apply resource lock on at least one resource in the MC_RG resource group, on the AKS overview blade we see a message like this 'The infrastructure resource group 'RG-...-Resources' is locked or contains locked resources, which may cause actions taken on the cluster to fail. Edit locks'.

**Comment by TobiasXy** [comment]
Not a solution for the actual problem here, but rather a workaround for public IP addresses specifically:
I recently moved all the public IPs into a dedicated IP resource group to have better control over them myself.


It comes down to:

1. Move public IPs to the new resource group (lets call it "cluster-ips")
2. Make sure the cluster has the "Network Contributor" permissions for the new "cluster-ips" resource group.
3. In all Kubernetes services of type LoadBalancer that use an IP from the cluster-ips rg, add the annotation `service.beta.kubernetes.io/azure-load-balancer-resource-group: cluster-ips`
This is just a tl;dr. For a better and more detailed explanation check this: https://learn.microsoft.com/en-us/azure/aks/static-ip

**Comment by mykolaichuk** [comment]
> Not a solution for the actual problem here, but rather a workaround for public IP addresses specifically: I recently moved all the public IPs into a dedicated IP resource group to have better control over them myself.
> 
> It comes down to:
> 
> 1. Move public IPs to the new resource group (lets call it "cluster-ips")
> 2. Make sure the cluster has the "Network Contributor" permission for the new "cluster-ips" resource group.
> 3. In all Kubernetes services of type LoadBalancer that use an IP from the cluster-ips rg, add the annotation `service.beta.kubernetes.io/azure-load-balancer-resource-group: cluster-ips`
> 
> This is just a tl;dr. For a better and more detailed explanation check this: https://learn.microsoft.com/en-us/azure/aks/static-ip

Hi @TobiasXy 

Thanks for sharing your workaround! It's nice and so simple!

**Comment by 1kmilo** [comment]
Hi,
Is there an ETA to fix this bug?
Thanks

**Comment by mosabami** [comment]
this is the fix the product group will most likely go with: https://github.com/Azure/AKS/issues/3395. currently in development.

**Comment by FlorentATo** [comment]
@mosabami Do we have a release date for the fix ? I ran into that issue again today (we use locks on public IPs).

**Comment by justindavies** [comment]
We released managed node group here: https://learn.microsoft.com/en-us/azure/aks/cluster-configuration#fully-managed-resource-group-preview
