### ISSUE TITLE
test cluster deployment failed

### ISSUE THREAD

**Issue by marekr** [Azure/AKS#330]
Just blindly following the instructions to mess around

az aks create --resource-group myResourceGroup --name myAKSCluster --node-count 1 --generate-ssh-ke
ys

[KDeployment failed. Correlation ID: dafbe713-0ee2-4a5c-a477-8b513fb5b015. Internal error in disk manager.

**Comment by sauryadas** [comment]
there is a storage issue right now which is being investigated and is most likely the issue. apologies

**Comment by slack** [comment]
Issue janitor! This storage issue was closed out.
