### ISSUE TITLE
[Question] Portal uses special DNS entry for private clusters

### ISSUE THREAD

**Issue by hbuckle** [Azure/AKS#3302]
**Describe scenario**

Cluster deployed using standard private cluster mode

A second private endpoint is created in the virtual network where our VPN exits

This private endpoint is reachable from developer laptops via VPN

**Question**

When the cluster is deployed using private link, the API server address is `mycluster.privatelink.uksouth.azmk8s.io`

We have our internal VPN and DNS configured so this resolves to the 2nd private endpoint and is reachable from developer laptops, and this works fine for kubectl

When accessing the cluster in the Azure portal, the portal tries to access the API server using a different DNS record which looks like `some-random-number-priv.portal.hcp.uksouth.azmk8s.io`, which fails as it resolves to the 1st private endpoint

Is there a reason for the portal using this special record, and not simply using `mycluster.privatelink.uksouth.azmk8s.io`?
We have to create a private DNS zone to override `some-random-number-priv.portal.hcp.uksouth.azmk8s.io` for every cluster we create

**Comment by sabbour** [comment]
Tagging @raghulmsft.

**Comment by wangyira** [comment]
@Azure/aks-portal

**Comment by nanunna** [comment]
Since api-server instances use self-signed certificates and do not allow CORS requests, a proxy is required and *.portal.* host name is basically that.
