### ISSUE TITLE
Consolidate Upgrade Logs

### ISSUE THREAD

**Issue by kaarthis** [Azure/AKS#3306]
Provide a way to consolidate multiple upgrade log look ups via an API that can be extended to first class portal and CLI experience. 
Log sources may include - Activity logs, Kubevents, Container insights etc. However only the choicest of log information i.e what is deemed critical for upgrade shall be consolidated to preserve infra cost and utility.

**Comment by vdiec** [comment]
Hi @kaarthis, I'm from the Azure Monitor container insights team. We'd like to understand more about the customer needs and requirements. Please reach out to me, @ganga1980 and @saaror
