### ISSUE TITLE
[BUG] Update security config on attached disks

### ISSUE THREAD

**Issue by tasb** [Azure/AKS#3307]
**Describe the bug**
On behalf of a pen test performed on our infrastructure, we got the recommendation to disable public access on node's attached disks.

We looked into this policy to change this configuration: [Configure managed disks to disable public network access](https://www.azadvertizer.net/azpolicyadvertizer/8426280e-b5be-43d9-979e-653d12a08638.html?desc=compareJson&left=https%3A%2F%2Fwww.azadvertizer.net%2Fazpolicyadvertizerjson%2F8426280e-b5be-43d9-979e-653d12a08638_1.0.0.json&right=https%3A%2F%2Fwww.azadvertizer.net%2Fazpolicyadvertizerjson%2F8426280e-b5be-43d9-979e-653d12a08638_2.0.0.json).

On VMs not managed by AKS it works properly but on VMs managed by AKS we got the following error:

![image](https://user-images.githubusercontent.com/415105/199931355-176aefcb-263e-42ce-9a6d-e84fdfae5a85.png)

I already took a look on other `current tenant ****** is not authorized to access linked subscription '109a5e88-712a-48ae-9078-9ca8b3c81345'` open issues but none is related with this since we are not trying to change VMSS neither VMs.

This happen on AKS without autoscalling.

 **To Reproduce**
You can try to change manually the configuration on attached disks managed by AKS or deploy Azure Policy described above.

**Expected behavior**
Since it's a security configuration and will not cause any impact on VMs, the user should be able to change it or have a property to config on cluster creation.

**Screenshots**
![image](https://user-images.githubusercontent.com/415105/199931735-876c724b-5daf-4b30-9959-01217b9d2681.png)

**Environment (please complete the following information):**
 - Using Azure Policies directly on our subscription
 - Kubernetes version: 1.23.12

**Comment by andyzhangx** [comment]
`networkAccessPolicy` is a property of azure data disk, are you able to set `networkAccessPolicy: DenyAll` in azure disk csi driver storage class, and then create disk pvc using that storage class?

**Comment by tasb** [comment]
What I'v reported is not related with PVC resources but with the managed disks of the nodes itself.

**Comment by tasb** [comment]
The issue changed state but the provided answer don't fix what was reported
