### ISSUE TITLE
[BUG] Stopping AKS with Scale-down Mode 'deallocate' doesn't remove node taints anymore

### ISSUE THREAD

**Issue by Cloud5000** [Azure/AKS#3313]
**Describe the bug**
When stopping AKS with Scale-down Mode 'deallocate' the following taints are still present on nodes after restart:

- kubernetes.azure.com/scalesetpriority=spot:NoSchedule
- node.kubernetes.io/unreachable:NoSchedule
- node.cloudprovider.kubernetes.io/shutdown:NoSchedule
- node.kubernetes.io/unreachable:NoExecute

The cluster stays in that state. No new nodes are scheduled.

We use Spot Instances, so the related taint is not a problem for us.

The problem exists since the beginning of November.

**To Reproduce**
1. Create AKS with some nodes and Scale-down Mode 'deallocate'
2. Stop AKS
3. Start AKS

**Expected behavior**
Node taints are removed after restart when using Scale-down Mode 'deallocate'.

**Environment (please complete the following information):**
 - Kubernetes version 1.24.6
 - Spot Instances
 - Region 'Europe West'

**Comment by anson627** [comment]
@Cloud5000 is this issue consistently reproducible? this might be due to race condition btw AKS RP and cloud provider
