### ISSUE TITLE
Azure CNI powered by Cilium

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#3318]
https://learn.microsoft.com/en-us/azure/aks/azure-cni-powered-by-cilium

GA release set for May 23 2023

**Comment by EppO** [comment]
>> Can I use CiliumNetworkPolicy custom resources instead of Kubernetes NetworkPolicy resources?

> CiliumNetworkPolicy custom resources aren't officially supported. We recommend that customers use Kubernetes NetworkPolicy resources to configure network policies.

Is there any technical reasons for that limitation? Kubernetes NetworkPolicy lacks DNS based network policies, they are very handy for remote out-of-cluster flows scenarios

**Comment by AndreasLudviksen** [comment]
Is this feature available on Linux-nodes in a mixed cluster with Linux and Windows nodepools?

I know the documentation says 'Available only for Linux and not for Windows' - but not sure if it means you wont get eBPF on Windows-nodes yet, or that the feature cannot be enabled at all in a mixed cluster.

**Comment by ebc92** [comment]
> CiliumNetworkPolicy custom resources aren't officially supported. We recommend that customers use Kubernetes NetworkPolicy resources to configure network policies.

Is there any planned support for using CiliumNetworkPolicy with Azure CNI powered by Cilium in the future?

It would be great to be able to leverage CiliumNetworkPolicy for DNS-based network policies without having to resort to BYO CNI.

**Comment by kaarthis** [comment]
Thanks for the feedback - CiliumNetworkPolicy for DNS-based network policies without having to resort to BYO CNI should be its own Feature request and tracked here : #3450

**Comment by akselleirv** [comment]
Hello @kaarthis,
I’m also very interested in the Hubble, cluster mesh and service mesh features of Cilium. Should this also be added as separate feature requests?

**Comment by hcjbh** [comment]
Hi @palma21,
Any plan when Azure CNI powered by Cilium could be promoted to GA ? 
Thanks

**Comment by rafaribe** [comment]
> Hi @palma21, Any plan when Azure CNI powered by Cilium could be promoted to GA ? Thanks

Very interested to know this as well. Having a lot of issues upgrading clusters with BYOCNI so a bit of Microsoft Support would be awesome.

**Comment by rgarcia89** [comment]
It looks like this will only be part of cilium enterprise https://isovalent.com/blog/post/isovalent-cilium-enterprise-microsoft-azure-marketplace/ so we will have to go with BYOCNI

**Comment by jkroepke** [comment]
Is it GA now? In docs, they removed "preview"

https://github.com/MicrosoftDocs/azure-docs/commit/37f9f2469dc6a801fb24482dba4b95a1b2d8766b

**Comment by EppO** [comment]
It was announced GA: https://azure.microsoft.com/en-gb/updates/azure-cni-powered-by-cilium/

**Comment by palma21** [comment]
That limitation in AKS exists not due to that issue per se, but due to what that issue requires to make it work (that option is/was not set in AKS Cilium clusters). We had to validate these options on multiple scenarios and at scale and finding the best path to enable it. This limitation is being removed next week

**Comment by illrill** [comment]
Two features I'd really like to see supported by Azure CNI Powered by Cilium:

- DNS-based egress rules ([toFQDN](https://docs.cilium.io/en/stable/security/dns/)) using `CiliumNetworkPolicy`
- Hubble
