### ISSUE TITLE
Cannot set the timezone of the AKS cluster

### ISSUE THREAD

**Issue by CharlesCara** [Azure/AKS#332]
I have set up an AKS cluster (Kubernetes 1.8) in the WestEurope location, which I am going to run cronjobs on.  The cluster's timezone is UTC and cronjobs run to this schedule.  

Is there any way of setting the cluster's timezone to London/UK so that cronjobs can be set in local time which changes between summer time (BST) and winter time (GMT)?

**Comment by slack** [comment]
There is no option for setting cluster timezone from UTC.
