### ISSUE TITLE
[BUG] Mismatch between Github Releases and Version Tracker

### ISSUE THREAD

**Issue by HarleyB123** [Azure/AKS#3325]
**Describe the bug**
The latest version in the AKS release schedule does not match the Github releases in this repository.

**To Reproduce**
1. Go to https://releases.aks.azure.com/
2. See the latest version (`v20221030`)
3. Go to the Github Releases
4. See that the title of the release and the tag are incorrect - https://github.com/Azure/AKS/releases (`Release 2022-10-31`)

**Expected behavior**
The title and tag of the Github release should match the releases page in Azure.

**Comment by wangyira** [comment]
@kaarthis, could you take a look at this issue?

**Comment by sabbour** [comment]
This was probably a one off.
/close
