### ISSUE TITLE
[Feature] Sustainability: Service to route to Pod in the same AZ or Node as the caller

### ISSUE THREAD

**Issue by HoussemDellai** [Azure/AKS#3329]
This is not an issue but rather a feature suggest to make AKS 'green'

Make the Service smarter to redirect traffic to a Pod in the same Availability Zone or even better in the same Node as the caller.
If we have, for example, Frontend Deployment calling Backend Deployment with 3 replicas for example, then AKS will likely span the 3 pods across 3 AZs and 3 VMs. That is good for HA but bad for sustainability because that is more work for network across AZs and thus more expensive.

**Comment by joaguas** [comment]
https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/

wouldn't this accomplish what you're aiming for @HoussemDellai ?

**Comment by yelghali** [comment]
> https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/
> 
> wouldn't this accomplish what you're aiming for @HoussemDellai ?

hello @joaguas  @HoussemDellai, yes I think customers can use Service Traffic policy (for redirecting to a local node) or Toplogy Aware Hints (to redirect traffic to services in the same zone) : https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/

@HoussemDellai , I think this could be added as a pattern (to complement putting node servers closer together) : https://learn.microsoft.com/en-us/azure/aks/concepts-sustainable-software-engineering#design-patterns-and-practices
