### ISSUE TITLE
(Minor) Deployment name not correct after doing "az aks create"?

### ISSUE THREAD

**Issue by mathieu-benoit** [Azure/AKS#333]
Minor feedback. After doing an `az aks create -g $RG...`,  one deployment entry appears on the resource group $RG which is fine. But the name of this deployment is `Microsoft.EmptyWorkflow`. You could run this `az group deployment list -g $RG` to check.

Again minor feedback for sure, but is it relevant to change this name and having a Guid, etc. instead? Or is it made on purpose?

**Comment by jnoller** [comment]
Stale issue, closing
