### ISSUE TITLE
[BUG] Upgrating from 1.23.8/12 to 1.24.xx needs additional svc annotation for the health probe

### ISSUE THREAD

**Issue by anksos** [Azure/AKS#3331]
**Describe the bug**
While you update between 1.23 version is not impacting at all your ingress controller svc, when you upgrade from 1.23 to 1.24 the ingress controller service due to a missing annotation 
`service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz`

**To Reproduce**
1. Update from 1.23.8 to 1.23.12
2. Check Health probe of the ingress svc works
3. Upgrade from 1.23.12 to 1.24 
4. Check Health probe of the ingress svc doesn't work
5. Annotate the svc `kubectl annotate svc/ingress-nginx-controller service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path=/healthz` 
6. Check Health probe of the ingress svc works again

**Expected behavior**
Upgrade should be working without breaking the ingress svc and manually to have to annotate the right health probe api.

**Screenshots**

**Environment:**
 -  Azure CLI Version [2.42] 
 - Kubectl Version [1.22]
 - Kubernetes version [1.23.12, 1.24.8, 1.24.12]

**Comment by carvido1** [comment]
Hello.

How have you installed the ingress-nginx ingress controller?

BR

**Comment by anksos** [comment]
> Hello.
> 
> How have you installed the ingress-nginx ingress controller? According to [azure documentation the annotation you mentioned is required](https://learn.microsoft.com/en-us/azure/aks/ingress-basic?tabs=azure-cli) for the ingress-nginx helm chart.
> 
> BR

Yes, of course is not on a new implemenation but upgrading from existing, and if you see here it was mentioned that exists that issue: https://learn.microsoft.com/en-us/answers/questions/1008699/aks-124-ingress-not-exposed.html 

In my case there is already a svc on 1.23 on the ingress-nginx-controller after upgrade you cannot access it until you run the annotate command on the svc again. I am just adding the article with the helm because it is mentioned specifically the needed annotation.

anksos

**Comment by joaguas** [comment]
hi @anksos 

can you confirm whether your target service uses `appProtocol` ?
this should be only case where the probe path annotations is required (starting with 1.24) as was announced in the release notes a while back: https://github.com/Azure/AKS/releases/tag/2022-09-11

**Comment by anksos** [comment]
> 
hey @joaguas 

I don't see the service using `appProtocol`

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"aks-customservice","namespace":"default"},"spec":{"ports":[{"port":80}],"selector":{"app":"aks-customservice"},"type":"ClusterIP"}}
  creationTimestamp: "2022-11-23T10:20:23Z"
  name: aks-customservice
  namespace: default
  resourceVersion: "8757"
  uid: xxxxxx-xxxxx-xxxxx-xxxxxx-xxxxxxxxxxxxx
spec:
  clusterIP: 10.0.x.x
  clusterIPs:
  - 10.0.x.x
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: aks-customservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by anksos** [comment]
> hi @anksos
> 
> can you confirm whether your target service uses `appProtocol` ? this should be only case where the probe path annotations is required (starting with 1.24) as was announced in the release notes a while back: https://github.com/Azure/AKS/releases/tag/2022-09-11

Hi @joaguas 

yes it uses appProtocol. Any recommendation there?
