### ISSUE TITLE
Pods can not get the status of other pods

### ISSUE THREAD

**Issue by charalamm** [Azure/AKS#3338]
**Describe scenario**
We have an Azure Kubernetes Service that is running some computation tasks using [prefect](https://github.com/PrefectHQ/prefect). The AKS uses a NAT Gateway for outbound traffic and has the following terraform configuration
```
# Kubernetes cluster
resource "azurerm_kubernetes_cluster" "akscluster" {
  name                              = "${var.deploymentname}-aks"
  location                          = var.location
  resource_group_name   = azurerm_resource_group.resourcegroup.name
  sku_tier                          = "Free"
  dns_prefix                      = "${var.deploymentname}-akscluster"
  api_server_authorized_ip_ranges   = toset([azurerm_public_ip_prefix.aks_pub_ip_prefix.ip_prefix,])
  role_based_access_control_enabled = true
  kubernetes_version                = "1.24.6"
  default_node_pool {
    name                = "corepool"
    enable_auto_scaling = true
    min_count           = 2
    max_count           = 100
    vm_size             = var.corepoolvm
    vnet_subnet_id      = azurerm_subnet.worksubnet.id # A subnet that is already created and associated with a NAT Gateway
  }
  identity {
    type = "SystemAssigned"
  }
  auto_scaler_profile {
    scale_down_delay_after_add    = "3m"
    scale_down_unneeded           = "3m"
    skip_nodes_with_local_storage = false
  }
  network_profile {
    network_plugin    = "azure"
    network_policy    = "calico"
    load_balancer_sku = "standard"
    outbound_type     = "userAssignedNATGateway"
    nat_gateway_profile {
      idle_timeout_in_minutes   = 4
      managed_outbound_ip_count = 4 # These are the number of IPs in a prefix that is associated with the subnets used in AKS
    }
  }
}
```

Running the computational tasks creates some "job" pods that are creating and monitoring some "task" pods that are doing the actual computations. The "job" pods are making requests to the Kubernetes API to get info about the "task" pods status, but they frequently can not connect and the following errors are produced:

```
HTTP response headers: HTTPHeaderDict({'Audit-Id': '<Audit-Id>', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 15 Nov 2022 09:28:31 GMT', 'Content-Length': '252'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Get \"https://10.3.2.43:10250/containerLogs/prefect-zone/<job-name>/<pod-name>\": EOF","code":500}
```

or

```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.0.0.1', port=443): Max retries exceeded with url: /apis/batch/v1/namespaces/<namespace>/jobs/<pod-id>a/status (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc06aa70760>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

On the other hand, the same requests seem to work when executing them manually from within the pods.

This behavior appears to happen when there is a lot of load in the cluster (still under 10% CPU and 20% RAM).
We have tried to add more nodes, looked into [troubleshoot-cluster-connection-issues-api-server](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/troubleshoot-cluster-connection-issues-api-server) and search on how to create more `kube-apiserver` instances without any luck.

**Question**
Is there something we could try to fix this problem? Is there any resources that we should read and might help us?

Thanks!

**Comment by charalamm** [comment]
My guess is that azure does not scale the Kubernetes API as fast enough and some requests get dropped. Could that be the case? If yes, is there something my team could do about it?

**Comment by justindavies** [comment]
Can you let us know how often you are querying the k8s API for this information?  Unless you are doing this a lot over many pods, you shouldn't be throttled
