### ISSUE TITLE
[Question] Whether using the service principal assigned a custom role breaks Azure best practice or not?

### ISSUE THREAD

**Issue by steven-zou** [Azure/AKS#3339]
**Describe scenario**

Calling AKS API to provision or manage the AKS clusters.

**Question**

Whether using the service principal assigned a custom role breaks MS's best practice or not? We got some messages that using a custom role is against MS's best practice, is that true? Any documents talking about such best practices?

Thanks.

**Comment by steven-zou** [comment]
Any comments here?

**Comment by steven-zou** [comment]
up

**Comment by justindavies** [comment]
@miwithro ?
