### ISSUE TITLE
[Question] When will dual stack be supported for Azure CNI?

### ISSUE THREAD

**Issue by austintackaberry** [Azure/AKS#3341]
**Describe scenario**
Seems like dual stack is supported for kubenet CNI but not Azure CNI.

**Question**
Follow up - is dual stack supported for BYO-CNI?

**Comment by dileepyavan** [comment]
Any update regarding the timeline on when this will be available, thanks!

**Comment by paulgmiller** [comment]
Tried to answer this somewhat over on https://github.com/Azure/AKS/issues/2732
