### ISSUE TITLE
[BUG] Dynamic allocation of IPs not configurable with BYOCNI

### ISSUE THREAD

**Issue by illrill** [Azure/AKS#3351]
**Describe the bug**
I'm trying to leverage [BYOCNI](https://learn.microsoft.com/en-us/azure/aks/use-byo-cni?tabs=azure-cli) together with the with the [Dynamic allocation of IPs and enhanced subnet support](https://learn.microsoft.com/en-us/azure/aks/configure-azure-cni#dynamic-allocation-of-ips-and-enhanced-subnet-support) network mode. However, `--pod-subnet-id` (Dynamic allocation of IPs) does not seem to be allowed together with `--network-plugin none` (BYOCNI), despite that the error message itself indicates it should be allowed.

```
(InvalidParameter) Can only specify a pod subnet when using network plugin Azure or None
Code: InvalidParameter
Message: Can only specify a pod subnet when using network plugin Azure or None
```

**To Reproduce**
```
az aks create -l westeurope -g rj -n illrill-aks-cluster --kubernetes-version 1.23.12 --network-plugin none \
--vnet-subnet-id /subscriptions/<redacted>/resourceGroups/rj/providers/Microsoft.Network/virtualNetworks/vnet/subnets/aks \
--pod-subnet-id /subscriptions/<redacted>/resourceGroups/rj/providers/Microsoft.Network/virtualNetworks/vnet/subnets/aks-pods
```

**Expected behavior**
Should be able to use `--pod-subnet-id` with `--network-plugin none`

**Environment (please complete the following information):**
 -  CLI Version `2.40.0`
 - Kubernetes version `1.23.12`

**Additional context**
Same result when using ARM template API version `2022-09-01` of `Microsoft.ContainerService/managedClusters`.

**Comment by amitmavgupta** [comment]
Isn't this feature applicable or available just for Azure CNI?

https://learn.microsoft.com/en-us/azure/aks/configure-azure-cni-dynamic-ip-allocation

**Comment by illrill** [comment]
Indeed it is. A year ago when this issue was created, all these new networking options were a bit unclearly documented. The (incorrect) error message `Can only specify a pod subnet when using network plugin Azure or None` led me to believe this was a path one could take.
