### ISSUE TITLE
Email received to rebuild cluster with RBAC enabled, in order "to be in a supported configuration"

### ISSUE THREAD

**Issue by AlexGoris-KasparSolutions** [Azure/AKS#3354]
**Describe scenario**
I received an email from Azure with the following subject:
> Action recommended: Rebuild your Azure Kubernetes Service cluster with RBAC enabled to be in a supported configuration

I'm concerned about the "to be in a supported configuration" part of that subject.

The body of the email states:
>You're receiving this email because you're running an Azure Kubernetes Service (AKS) cluster that is non-RBAC enabled. 
We noticed from our backend that your AKS clusters are running with non-RBAC enabled. For clusters with non-RBAC, many security features such as auto cert-rotation, TLS bootstrap, and Konnectivity can't be leveraged.

But mentions nowhere that my current configuration (non-RBAC enabled) would not be supported anymore, or a timeline around that statement.

**Question**
How should I interpret the subject line of that email?
If I don't need the mentioned features ("such as auto cert-rotation, TLS bootstrap and Konnectivity"), am I fine keeping my non-RBAC cluster as is? Or will I not be able to upgrade to a future version, or will the service stop working altogether at some point?

**Comment by justindavies** [comment]
@miwithro Can you comment on this?

**Comment by CocoWang-wql** [comment]
Hello @AlexGoris-KasparSolutions, in the furture we will not support non-RBAC clusters. May I know your concern about not migrating to RBAC?
