### ISSUE TITLE
[BUG] Azure Kubernetes Service (AKS) node image upgrade issue

### ISSUE THREAD

**Issue by mezzofix** [Azure/AKS#3355]
**Describe the bug**

Node image version not properly returned when executing/checking with az,kubectl, and Azure portal. 

**To Reproduce**

I’ve followed https://learn.microsoft.com/en-us/azure/aks/node-image-upgrade to upgrade node images in all node pools. 

I have two node pools (systempool and usernodepool) as per MSFT recommendations https://learn.microsoft.com/en-us/azure/aks/use-system-pools?tabs=azure-cli 

Executed `az aks upgrade --resource-group foo --name bar --node-image-only`

It immediately returned a JSON  to the terminal, no errors. 

![Details](https://user-images.githubusercontent.com/57439630/203294374-a099f29e-d8e2-4b60-b04d-059254889ca1.png)

As seen on the screenshot, for both node pools the available image version and the current image version is the same (current image version == latest image version). 

However, if I run  `kubectl get nodes -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.metadata.labels.kubernetes\.azure\.com\/node-image-version}{"\n"}{end}' ` you can clearly see (last line on the screen shot), that kubectl returns a completely different image version for both nodes (the ones that I was upgrading from). 

The Azure portal also reflects the old image versions:

![Portal](https://user-images.githubusercontent.com/57439630/203295416-5b759721-093f-4fc3-801b-6f38ddc3d290.png)

I connected to both nodes to check if they are pending for reboot but `/var/run/reboot-required` was not present. 

What am I missing ?

**Expected behavior**

Image versions gets properly returned when executing/checking with az, kubectl and in Azure portal. 

**Screenshots**

**Environment (please complete the following information):**
{
  "azure-cli": "2.37.0",
  "azure-cli-core": "2.37.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.76"
  }
}

Kubernetes version: 1.22.6

**Comment by mezzofix** [comment]
hello ??

**Comment by carvido1** [comment]
Hello @mezzofix 

Which command are you executing to upgrade the nodepools image ?
The command you provided `az aks upgrade --resource-group foo --name bar --node-image-only` is not the same as this one [az aks nodepool upgrade](https://learn.microsoft.com/es-es/cli/azure/aks/nodepool?view=azure-cli-latest#az-aks-nodepool-upgrade).

As additional check, have you checked that the nodes can restart? You can do that with `kubectl get nodes -o wide` as well as checking the logs from your applications. It can be the case that you have a pod disruption budget and your node can't be restarted.

BR
