### ISSUE TITLE
Extension integration in terraform for AKS

### ISSUE THREAD

**Issue by PrabhuMathi** [Azure/AKS#3356]
**Describe scenario**
Looking for an option to enabled extensions like Flux and ML in terraform and pass the flux configuration in terraform. I believe this is available for BIAC and not sure for terraform.

**Question**
Is there any plan to rollout for terraform as well? or is it available already and I'm missing it?

**Comment by justindavies** [comment]
We don't have anything in the roadmap to pass in add-on configuration in the way you are looking for.  @olsenme - correct me if I'm wrong here

**Comment by sabbour** [comment]
@PrabhuMathi does this address your need? https://github.com/hashicorp/terraform-provider-azurerm/issues/15011#issuecomment-1227659088

**Comment by prabhumathiyalagan** [comment]
> hashicorp/terraform-provider-azurerm#15011 (comment)

This is updating all AKS properties and not only the flux properties and disabling multi cluster option is not working with this.
