### ISSUE TITLE
[Question] Where can I find AKSUbuntu images like aks-ubuntu-containerd-22.04

### ISSUE THREAD

**Issue by fals** [Azure/AKS#3358]
**Describe scenario**
I'm trying to create a VMMSet using the [azure-sdk-for-go](https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/main/sdk/resourcemanager/compute/vmscaleset/main.go#L167), but I can't find the proper information about these images anywhere `aks-ubuntu-containerd-22.04`, `aks-ubuntu-containerd-22.04-gen2` and `aks-ubuntu-arm64-containerd-22.04-gen2`

I could find information about old images SKUs.

For containerd images I found here:
`az vm image list-skus -l centralus -f aks-aez -p microsoft-aks -o table`

For docker images I found here:
`az vm image list-skus -l centralus -f aks -p microsoft-aks -o table`

**Question**
Where can I find the Publisher, Offer and Sku for the images `aks-ubuntu-containerd-22.04`, `aks-ubuntu-containerd-22.04-gen2` and `aks-ubuntu-arm64-containerd-22.04-gen2`?

**Comment by fals** [comment]
> Hello @fals!
> 
> Ubuntu 22.04 version is by default on AKS cluster with Kubernetes version 1.25.
> 
> Please see: https://azure.microsoft.com/en-us/updates/generally-available-aks-support-for-ubuntu-2204/
> 
> Please take in consideration that Kubernetes version 1.25 is still in preview. We recommend you to follow https://github.com/Azure/AKS/releases for more news.
> 
> Please let me know if any further clarification is required.
> 
> Best regards, Andrei

Thank you for you reply,  but it doesn't answer my question. I want to know why or where those images are publicly available. All other cloud providers have those images open to public to create whatever they want.

**Comment by sabbour** [comment]
@fals can you elaborate on your use case here?

**Comment by fals** [comment]
> @fals can you elaborate on your use case here?

Azure AKS is the only managed k8s that has private images. Also, with the new AKS hybrid solution would be more than welcome to have those images publicly available to allow customizing it. Running scripts during startup are not the best case, it takes a lot of time for nodes to join the cluster, which is inviable if rapid scaling up is required.

**Comment by justindavies** [comment]
@fals - those images are made available to update your AKS clusters, and we do not support customising the node images outside of modifications after node readiness through a DaemonSet etc.  We would like to understand what it is you want to modify on the node image so we can see how we can help
