### ISSUE TITLE
heapster pods does not restart 

### ISSUE THREAD

**Issue by foadfbf** [Azure/AKS#336]
I set up a k8s cluster on AKS with kubernetes version 1.8.7 the cluster went into inconsistent state because the pod containing the heapster cannot restart and I see the following error:

 Warning  FailedKillPod  56m (x3704 over 1d)  kubelet, aks-nodepool1-10371536-3  error killing pod: [failed to "KillContainer" for "heapster" with KillContainerError: "rpc error: code = Unknown desc = Error response from daemon: Cannot stop container cae4b8ca81a0fb5a426d1df838d84d25bc5dcd99642f6c77a50dd44ed2710030: Cannot kill container cae4b8ca81a0fb5a426d1df838d84d25bc5dcd99642f6c77a50dd44ed2710030: rpc error: code = 14 desc = grpc: the connection is unavailable"
, failed to "KillContainer" for "heapster-nanny" with KillContainerError: "rpc error: code = Unknown desc = Error response from daemon: Cannot stop container 6e17866efc1db62f6fcb7784c7189949755b7c5e2dafcd3a4fd296bedc130952: Cannot kill container 6e17866efc1db62f6fcb7784c7189949755b7c5e2dafcd3a4fd296bedc130952: rpc error: code = 14 desc = grpc: the connection is unavailable"
, failed to "KillPodSandbox" for "87621092-4920-11e8-8844-0a58ac1f0c79" with KillPodSandboxError: "rpc error: code = Unknown desc = Error response from daemon: Cannot stop container 7085ef452c9d5e25b2729d080ea0e35931b1d18fcb40f6234caa65a2a08d7e54: Cannot kill container 7085ef452c9d5e25b2729d080ea0e35931b1d18fcb40f6234caa65a2a08d7e54: rpc error: code = 14 desc = grpc: the connection is unavailable"
]
  Normal  Killing  11m (x7752 over 1d)  kubelet, aks-nodepool1-10371536-3  Killing container with id docker://heapster-nanny:Need to kill Pod
  Normal  Killing  1m (x7788 over 1d)   kubelet, aks-nodepool1-10371536-3  Killing container with id docker://heapster:Need to kill Pod

logs from the heapster pod shows that the network is unreachanble

1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:30: Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.0.0.1:443: connect: network is unreachable
E0430 07:56:48.444508       1 reflector.go:190] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: Failed to list *v1.Namespace: Get https://10.0.0.1:443/api/v1/namespaces?resourceVersion=0: dial tcp 10.0.0.1:443: connect: network is unreachable

force delete the heapster pod does not work. this has caused most of other services in the cluster to go down or restart very often and cannot use the cluster. 

Regards,
Foad

**Comment by sauryadas** [comment]
looks like an old issue we have fixed .. if you are still seeing an issue please file a support ticker.
