### ISSUE TITLE
[BUG] Azure Policy:  x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by mllab-nl** [Azure/AKS#3360]
**Describe the bug**
AzureDiagnostics is full of errors about  x509: certificate signed by unknown authority. 
They look very strange since gatekeeper TLS certificates are not rotated   

This quey has ~500 hits per week
`AzureDiagnostics | where log_s contains "failed to call webhook: Post \"https://gatekeeper-webhook-service.gatekeeper-system.svc:443/v1/admitlabel?timeout=3s\": x509: certificate signed by unknown authority"
`
**To Reproduce**
1. Enable Policy plug-in on the cluster. 
2. Assign a policy **without enforcement.** https://learn.microsoft.com/en-us/azure/governance/policy/concepts/policy-for-kubernetes
3. Check the logs
4. The reconciled gatekeeper-webhook-server-cert in namespace gatekeeper-system is valid and is not issued recently 
![image](https://user-images.githubusercontent.com/29844962/204269354-087da90e-b434-4ee2-ac87-da74f8ce2a79.png)

**Expected behavior**
Installing Policy add-on should not add a lot of errors 

**Environment (please complete the following information):**
Gatekeeper image: 
mcr.microsoft.com/oss/open-policy-agent/gatekeeper:v3.8.1
AKS: 1.24.6
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", 
GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"6c23b67c202a4cfa7c76c3e1b370bd5f0e654f30", GitTreeState:"clean", BuildDate:"2022-11-09T17:13:23Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by justindavies** [comment]
@miwithro any ideas?

**Comment by charleswool** [comment]
The error was caused by a gatekeeper validating webhook missing the CA bundle, the issue has been fixed
