### ISSUE TITLE
[Feature] Upgrade Nvidia drivers used in GPU machine to 515.x or above

### ISSUE THREAD

**Issue by gdippolito** [Azure/AKS#3364]
**Is your feature request related to a problem? Please describe.**
We are having problems running one our applications with Nvidia drivers 510. 

From our testing in an Azure VM our application runs fine with both 470 and 515 but not with 510. 

**Describe the solution you'd like**
We would like Azure AKS to consider moving to Nvidia Driver 515.x or above.

**Describe alternatives you've considered**

Since we are not able to provide a different base image we are not able to change the driver version we use in AKS. Would it be possible to make it configurable? 

**Additional context**

On 510 our application crashes with this exception:
![image](https://user-images.githubusercontent.com/18577894/204777153-b7828e92-c452-4ebb-af66-4750825d2984.png)

Looking at `dmesg` we can see the following logs thrown:
```
[  549.998327] NVRM: Xid (PCI:0001:00:00): 119, pid=3355, Timeout waiting for RPC from GSP! Expected function 76.
[  549.998706] NVRM: Xid (PCI:0001:00:00): 119, pid=3355, Timeout waiting for RPC from GSP! Expected function 10.
[  549.998807] NVRM: Xid (PCI:0001:00:00): 119, pid=3355, Timeout waiting for RPC from GSP! Expected function 10.
[  568.100520] NVRM: Xid (PCI:0001:00:00): 119, pid=3355, Timeout waiting for RPC from GSP! Expected function 76.
[  568.100928] NVRM: Xid (PCI:0001:00:00): 119, pid=3355, Timeout waiting for RPC from GSP! Expected function 10.
```

It looks like the issue is similar to https://github.com/NVIDIA/open-gpu-kernel-modules/issues/272 which was fixed in the next release of the nvidia driver `515.65`

**Comment by digitalandrei** [comment]
Hello. Any news here? :) We would really like to get 525 drivers or be able to select driver version via Nvidia's operator.

**Comment by chiragjn** [comment]
It seems like A10 has been upgraded to 535.x with GSP disabled while T4 and A100 machines have 525.x with GSP enabled

**Comment by gdippolito** [comment]
I think this has been fixed since AKS is running Nvidia drivers 535.x
