### ISSUE TITLE
AKS forcefully re-deploying kubernetes dashboard?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/AKS#3368]
Team,

The version of my AKS in 1.23.8 and node pool is of type Availability set. AKS is automatically creating Kubernetes dashboard again and again even after deleting all the objects multiple times. I have also checked the addons and it is already false for kube dashboard 

![image](https://user-images.githubusercontent.com/7824529/205091987-b51b6bbc-9a62-44ec-af4c-3ae94b626004.png)

![image](https://user-images.githubusercontent.com/7824529/205093896-13d06277-27ce-4e44-9128-04ce6cfc9385.png)

Kindly suggest the procedure to delete it permanently. 

Kind Regards,
Tanul

**Comment by lgmorand** [comment]
is it an upgraded cluster ? it should be present for any newly created cluster

**Comment by smartaquarius10** [comment]
@lgmorand , Upgraded cluster means.. Didn't get. On 1st November we have upgraded our cluster from 1.23.5 to 1.23.8.

**Comment by lgmorand** [comment]
an old cluster which has been upgraded up to 1.23.X 

normally, since AKS 1.19, there is no dashboard enabled by default (https://github.com/azure-deprecation/dashboard/issues/121)

**Comment by smartaquarius10** [comment]
@lgmorand ,  yes I can open the dashboard.. It has dashboard metrics scrapper as well. Its secrets, roles cluster roles etc...

Yesterday, I have deleted them manually one by one. But the moment them AKS recreated them.. Is there any way to delete all this... We don't need this at all. We have other observability tools already available.

**Comment by smartaquarius10** [comment]
Even though the addon is disabled, I have even tried running **az aks addon disable** but getting this error

`however, it does not have permission to perform action 'Microsoft.Network/virtualNetworks/subnets/join/action' on the linked scope(s) `

I don't have VNET level access. But I genuinely don't know why disable any addon on AKS need VNET related permissions. Its really a mess.

I have requested a team to run this command who has VNET level privileges, and they are getting this error:

![image](https://user-images.githubusercontent.com/7824529/205291196-a1b42fef-0617-4e55-8001-250e069260bc.png)

**Comment by lgmorand** [comment]
"I genuinely don't know why disable any addon on AKS need VNET related permissions" that's a good question indeed :D 

open a ticket in Azure portal. Only support will be able to act on your cluster.

**Comment by smartaquarius10** [comment]
@lgmorand, yup. I was looking on azure portal and I think from there we can't remove these addon's.. I don't know how to remove these addons without VNET level access.  

@CocoWang-wql , Hey.. trust you're doing well. Could you please guide something on this.. Would be grateful.

**Comment by lgmorand** [comment]
@smartaquarius10 on azure portal > support > create ticket

PM won't be able to help you from here. it's still useful to open an issue because it could help them to fix it for the future but for your specific cluster, the support ticket is the way to go ;)

**Comment by CocoWang-wql** [comment]
Hello @smartaquarius10 I tested it in my 1.22.11 cluster and meet the same issue. Let me loop the dashboard PM @qpetraroia to see whether he has any idea. 

![image](https://user-images.githubusercontent.com/45681473/205300494-23a9504b-0ae3-4302-98e0-218414a73f2f.png)

**Comment by smartaquarius10** [comment]
@lgmorand , Hmm. Actually I have to ask a separate team to raise a support ticket. Now its very late here in India. Will ask the team to raise a request on Monday.

@CocoWang-wql , Sure. Thank you so much. Will wait for your reply.. On Monday, I'll try with some other person as well. Maybe he can be able to run `az aks addon disable command`. 

I have admin rights on AKS but just because of subnet level access unable to run this command. 😢

**Comment by smartaquarius10** [comment]
@Igmorand, @CocoWang-wql , Hey it worked. Another person of the team ran this command `az aks disable-addons` and it worked.. 

But vnet access is still a concern which needs to be addressed.

Please let me know if I close this issue or not? Thank you so very much once again @CocoWang-wql @lgmorand . 

Happy weekend. Take care 😄

**Comment by smartaquarius10** [comment]
Should I close the issue @CocoWang-wql @lgmorand

**Comment by lgmorand** [comment]
I'm just a user like you, I can't answer on that sorry :'(

**Comment by CocoWang-wql** [comment]
Hello @smartaquarius10 , for the vnet permission, that's because `disable addon` will trigger aks update, during that process, it will check the user permission and reports the insufficient permission error.

**Comment by smartaquarius10** [comment]
@CocoWang-wql , Oh ok that's the reason. Yup I don't have access to update aks as well. Got it.. Thank you so much.

Closing the issue.. Have a great weekend 😄
