### ISSUE TITLE
[BUG] Azure CNI Powered by Cilium: Changing property 'networkProfile.ebpfDataplane' is not allowed

### ISSUE THREAD

**Issue by EppO** [Azure/AKS#3369]
**Describe the bug**
When using [Cilium](https://learn.microsoft.com/en-us/azure/aks/azure-cni-powered-by-cilium), any changes on the AKS cluster after successful provisioning throws that error:
```
Changing property 'networkProfile.ebpfDataplane' is not allowed
```

**To Reproduce**
1. Create AKS cluster with cilium
```
az aks create -n <clusterName> -g <resourceGroupName> -l <location> \
  --max-pods 250 \
  --node-count 2 \
  --network-plugin azure \
  --vnet-subnet-id /subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Network/virtualNetworks/<vnetName>/subnets/nodesubnet \
  --pod-subnet-id /subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Network/virtualNetworks/<vnetName>/subnets/podsubnet \
  --enable-cilium-dataplane

```
2. Change something on your AKS cluster like add AGIC or setup log Analytics (Container Insights)
3. See error: 
```
[Failed to save Kubernetes service](https://portal.azure.com/#)
Failed to save Kubernetes service '<clusterName>'. Error: Changing property 'networkProfile.ebpfDataplane' is not allowed.
```

**Expected behavior**
I expect to be able to change any settings on the AKS cluster after a successful provisioning with Cilium dataplane

**Screenshots**

**Environment (please complete the following information):**
 -  CLI Version and CLI Extension version:
```
az version
{
  "azure-cli": "2.42.0",
  "azure-cli-core": "2.42.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "aks-preview": "0.5.117"
  }
}
```
 - Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-11T02:45:44Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"6c23b67c202a4cfa7c76c3e1b370bd5f0e654f30", GitTreeState:"clean", BuildDate:"2022-11-09T17:13:23Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Microsoft.ContainerService/CiliumDataplanePreview is registered

**Comment by EppO** [comment]
After investigation, looks like only the portal is affected by this, doing the changes via the CLI (along with the correct version of aks-preview extension) is working fine.

**Comment by wedaly** [comment]
thank you for reporting this! Confirmed that this is a bug in the AKS validation logic. This impacts any client using an API version without the networkProfile.ebpfDataplane field (introduced in 20220902preview). I am working on a fix.

**Comment by wedaly** [comment]
The fix was merged this morning and is scheduled for the next AKS release.

**Comment by wedaly** [comment]
The fix should now be deployed to all public regions. Thanks again for reporting this!
