### ISSUE TITLE
No swap limit support

### ISSUE THREAD

**Issue by Flask** [Azure/AKS#337]
Hello guys

We ran into a couple of issues in AKS which were related to docker. 
It seems that docker on Ubuntu 16.04 does not out of the box supports [memory limits and swap limits](https://github.com/moby/moby/issues/4250). 

Would be nice, if there is a config flag to bootstrap the nodes already with a grub configured, although it's possible to ssh into every node, change it by hand and reboot the agent. Unfortunately that does not apply if you scale your cluster.

Regards
F

**Comment by weinong** [comment]
please post feature request to https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks

**Comment by maganvill** [comment]
Related: I wrote a AKS feature request [here](https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/36606361-enable-aks-node-memory-swapping) to enable swap at control-plane
