### ISSUE TITLE
[Question] - How to detect AKS in helm charts ?

### ISSUE THREAD

**Issue by zioproto** [Azure/AKS#3375]
I need to extend an existing Helm chart, that needs to autodetect the target cluster is an AKS one.
Example
https://github.com/istio/istio/blob/fbb25467e9df6dc61fac0a3f6e43d9fac67909cc/manifests/charts/ztunnel/templates/daemonset.yaml#L117-L119

For GKE and EKS this is done using Helm Capabilities:
 
```
{{- if not (.Capabilities.KubeVersion.GitVersion | contains "-eks") }}
 ```

Because in GKE and EKS doing `kubectl version` returns a `GitVersion` object that has a string suffix `-eks` or `-gke`
 
In AKS the string is just the Kubernetes SemVer.

```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5db3654b1af9cc321ccd1371280a3ee4b124ba1e", GitTreeState:"clean", BuildDate:"2022-11-09T17:12:29Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```

In the above example I have GitVersion:"v1.25.2"

In GKE the version would be like: `1.21.3-gke.210`
in EKS the version would be like: `v1.18.9-eks-d1db3c`

**Question:**

How to detect the cluster is AKS from the Helm capabilities ?
https://helm.sh/docs/chart_template_guide/builtin_objects/

One possible idea is to be consistent with the other Cloud Providers is to add to the `GitVersion` a `-aks` suffix

** Related issues **

* This is blocking Istio Ambient ztunnel helm chart to be compatible with AKS: https://github.com/istio/istio/issues/41917

** Related Stackoverflow questions **

* https://stackoverflow.com/questions/54415189/how-do-i-detect-kubernetes-cluster-provider-eks-aks-in-helm-charts

**Comment by justindavies** [comment]
@shashankbarsin any ideas on this?

**Comment by eddycharly** [comment]
Funky :)

**Comment by evgenymo** [comment]
@justindavies 
Any updates on this?

**Comment by evgenymo** [comment]
@zioproto Completed how?

**Comment by zioproto** [comment]
@evgenymo I closed the issue as completed because my original problem with Istio Ambient is now actually solved: https://github.com/istio/istio/issues/41917

However, you are right, this issue is not specifically related to Istio Ambient and there is no solution yet.

Are you blocked by this issue as well for developing an Helm chart ?
If who is following this issue would be so kind to comment which Helm chart they are working on, this would help to prioritise this problem with the product team.

Thank you

**Comment by evgenymo** [comment]
@zioproto 

Thanks for the clarification, i managed to find a way to identify AKS via other means but i still find it strange that:
- AKS is the only one that breaks this standard compared to other cloud providers as mentioned in this thread
- We didn't get a response from aks-leads for a long time
