### ISSUE TITLE
Strategies to re-create a new AKS cluster following the existing cluster?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/AKS#3376]
Hello,

In the year 2018, for lower environment, we have created the AKS cluster with availability sets node pool having B2s size Vm and azure cni for networking with the /24 subnet.  

Now, we have to migrate it to the new AKS with VMSS and D2s size. 

Problems

-  Shortage of ip in subnet due to which we can’t create a new one in parallel with the existing one. 
- we haven’t used terraform before and created via azure portal only due to which we don’t have any snapshot of existing infrastructure configuration 

Can anyone suggest some strategies following which we can create the new one and slowly decommission the existing one. 

Some monolithic to microservice approach has to be applied and for a start our approach could be:

- Downscale the existing one to 4 nodes and create an new AKS with 4 nodes of D2s size
- Other than this, I think the moment we create nginx/kong in it with the existing public ip address and url then automatically data will start flowing in the new one. 

It doesn’t seems to be that easy as we have azure monitor, container insights etc. and many other things connected with the existing cluster. 

Can anyone suggest the possible strategies and what things should we remember in such a situation. 

Kind Regards,
Tanul

**Comment by vdiec** [comment]
Adding @kaarthis to provide more details

**Comment by qpetraroia** [comment]
Tagging @sabbour for viz. 

Hi @smartaquarius10,

Thanks for reaching out, this is a very interesting problem. As of right now, open-source tools such as https://github.com/WoozyMasta/kube-dump may help you.

The AKS team will also look into this going forward. Thanks.

**Comment by smartaquarius10** [comment]
@qpetraroia , Thanks for sharing. One more query, is there any tool available to completely delete all the resources from a namespace and then delete that namespace as well.
