### ISSUE TITLE
[Question] when would IPv6 support calico network policies?

### ISSUE THREAD

**Issue by UXabre** [Azure/AKS#3377]
**Describe scenario**
Currently it seems there's no way to filter data or apply network policies when IPv6 is enabled on a cluster. We'd very much like to have this as to have network seggregation possibilities in place as i don't want pods from one namespace to talk to another namespacd for instance.

Also, AFAICT calico already supports IPv6 policies? So is this disabled as a Just-in-case scenario?

**Question**
When would calico support be introduced to an IPv6 enabled cluster?
Or, when would IPv6 be regarded for GA?

**Comment by paulgmiller** [comment]
This is un clear but we are prtty close to cilium support for dualstack.

**Comment by UXabre** [comment]
To be honest, I'm not married to calico and anything that can help me enforce network policies in a dual stack environment sounds good to me! If cillium supports this, then fine by me (any pointer to get me started with cillium in aks are more than appreciated)

**Comment by paulgmiller** [comment]
@UXabre cilium is likely to have ipv6 support very soon. I'll check with someone to get docs updated.

**Comment by UXabre** [comment]
Ok, great, I'll see to check it out, would be good news! :-)
