### ISSUE TITLE
After Upgrading the cluster to 1.24.3 not able to do kubectl commands.[BUG]

### ISSUE THREAD

**Issue by teocrispy91** [Azure/AKS#3379]
**Describe the bug**
I Just upgraded the cluster from 1.23.12 to 1.24.3 and then when i do kubectl get ns  i get errors when i did kubectl version i found no server being listed there and client version being 1.22.5 . Since 1.22.5 is depcreated i upgraded kubectl to 1.25 version removed kube config , cache everything and restarted still the issue persists. Only time i am able to login is when i do az-aks get credentilas with --admin tag why admin tag is necessary and why not it's not working even after upgrading kubectl 

I am attaching an image for error refrence 
**To Reproduce**
1. Run command '...'
2. See error

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help 
<img width="452" alt="kubectlerr" src="https://user-images.githubusercontent.com/66721568/205923854-84d6373c-029d-4109-943a-30ed222cb0d3.PNG">
explain your problem.

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22]
 - Kubernetes version [e.g. 1.24.3]
 - CLI Extension version [e.g. 1.7.5] if applicable
 - Browser [e.g. chrome, safari] is applicable

**Additional context**

**Comment by carvido1** [comment]
Hello @teocrispy91 .

Have you tried the solution suggested? 

BR
