### ISSUE TITLE
No Kubernetes access profiles found. Cluster provisioning state is "Succeeded".

### ISSUE THREAD

**Issue by neutrongenious** [Azure/AKS#338]
while using powershell on windows
az aks get-credentials
throwing error: No Kubernetes access profiles found. Cluster provisioning state is "Succeeded".

same works fine in bash.

**Comment by smithc** [comment]
I ran into the same issue a little while back, and I believe it was solved with a simple az cli update.  I would check to see if you're running the latest version, and try updating if possible.

**Comment by neutrongenious** [comment]
Worked :)
