### ISSUE TITLE
[BUG] AKS cluster with Cilium  (Azure CNI) fails to sync gitrepo source using gitops (flux v2)

### ISSUE THREAD

**Issue by rkramcharan** [Azure/AKS#3380]
AKS cluster with Cilium (Azure CNI) fails to sync gitrepo source using gitops (flux v2).  Inspecting logs it looks like pods are unable to resolve FDQN for service / pod and it times out.

network policies allow all traffics across pods.

Kustomize source controller has the following error:
{"level":"error","ts":"2022-12-06T17:12:15.947Z","msg":"Reconciliation failed after 7m55.039255492s, next try in 5m0s","controller":"kustomization","controllerGroup":"kustomize.toolkit.fluxcd.io","controllerKind":"Kustomization","Kustomization":{"name":"infra","namespace":"engagement-flux-config"},"namespace":"engagement-flux-config","name":"infra","reconcileID":"0011e563-8ef0-403f-a42d-61d18fc565f2","revision":"gitopsync/314d4307944864bd1a640030f7440e41a8f48e92","error":"failed to download artifact, error: GET http://source-controller.flux-system.svc.cluster.local./gitrepository/engagement-flux-config/engagement-apps/314d4307944864bd1a640030f7440e41a8f48e92.tar.gz giving up after 10 attempt(s): Get \"http://source-controller.flux-system.svc.cluster.local./gitrepository/engagement-flux-config/engagement-apps/314d4307944864bd1a640030f7440e41a8f48e92.tar.gz\": dial tcp 10.0.247.134:80: i/o timeout"}
{"level":"error","ts":"2022-12-06T17:13:00.952Z","msg":"unable to record event","name":"infra","namespace":"engagement-flux-config","reconciler kind":"Kustomization","error":"POST http://notification-controller.flux-system.svc.cluster.local./ giving up after 5 attempt(s): Post \"http://notification-controller.flux-system.svc.cluster.local./\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}

**Comment by justindavies** [comment]
Is this the only time you see the communication issue, or is this for other services in the cluster too?
