### ISSUE TITLE
[Feedback] Release notes is not up-to-date

### ISSUE THREAD

**Issue by guy-microsoft** [Azure/AKS#3381]
**Describe your scenario**
Updating VMSS updated the OS image to an image not appearing in release notes.

**Feedback**
![image](https://user-images.githubusercontent.com/50947884/206393959-9add3856-5104-4375-a5f7-ff86c81aaddb.png)
In addition, note that "Current version" after the update is newer than "Latest version".

**Comment by marcindulak** [comment]
This still seems to be partly an issue. The latest 18.04 image release as of today is https://github.com/Azure/AKS/releases/tag/2023-02-05 and it includes [AKSUbuntu-1804-2023.01.26](https://github.com/Azure/AKS/blob/2023-02-05/vhd-notes/aks-ubuntu/AKSUbuntu-1804/2023.01.26.txt) (which appears mistakenly empty), however the Azure portal UI reports `AKSUbuntu-1804gen2containerd-2023.01.20`.

Are these two types of images different? There was a question about it https://github.com/Azure/AKS/issues/2947, without a clear answer yet.

<img width="482" alt="Screenshot 2023-02-13 at 21 02 53" src="https://user-images.githubusercontent.com/3178318/218563186-482902c2-0d5f-4b5c-b52a-8603574b7445.png">

![Screenshot from 2023-02-13 21-07-20](https://user-images.githubusercontent.com/3178318/218565223-d3f97ea6-b5bd-4836-b354-f37ee9f76f9a.png)
