### ISSUE TITLE
Use the method of load balancing+ingress to configure the domain name based 7-tier load balancing (1. test. com/, 2. test. com/) instead of (1. test. com/test1, 1. test. com/test2)

### ISSUE THREAD

**Issue by qingfengfenga** [Azure/AKS#3382]
**Describe scenario**

I created an AKS cluster

Version v1.23.12

Use here（ https://kubernetes.github.io/ingress-nginx/deploy/#azure ）The supplied yaml file (https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.2.1/deploy/static/provider/cloud/deploy.yaml ）

Because my region cannot access the original image, I have modified the image address here.

Like other issues, the service automatically creates a new public IP address in the load balancer created by AKS. Here, I manually modify the EXTERNAL-IP parameter to make the service use the default public IP address.

```
$ kubectl -n ingress-nginx get svc,deploy,job -o wide
NAME                                         TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                      AGE   SELECTOR
service/ingress-nginx-controller             LoadBalancer   10.0.218.192   xxx.xxx.xxx.xxx   80:31210/TCP,443:30127/TCP   22h   app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx
service/ingress-nginx-controller-admission   ClusterIP      10.0.219.114   <none>          443/TCP                      22h   app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES                              SELECTOR
deployment.apps/ingress-nginx-controller   1/1     1            1           22h   controller   docker.io/dyrnq/controller:v1.2.1   app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx

NAME                                       COMPLETIONS   DURATION   AGE   CONTAINERS   IMAGES                                        SELECTOR
job.batch/ingress-nginx-admission-create   1/1           3s         22h   create       docker.io/dyrnq/kube-webhook-certgen:v1.1.1   controller-uid=29d1f9ec-ee01-431b-a0fa-33ecd9b7c388
job.batch/ingress-nginx-admission-patch    1/1           4s         22h   patch        docker.io/dyrnq/kube-webhook-certgen:v1.1.1   controller-uid=eb88c8fb-dfab-4062-a11b-ef8b7921529c
```

Then I started referring to this document（ https://docs.azure.cn/zh-cn/aks/ingress-basic?tabs=azure -Cli) for testing

![image](https://user-images.githubusercontent.com/41416092/206410091-d8574926-cf84-4aca-bb0f-8733daa0277b.png)

![image](https://user-images.githubusercontent.com/41416092/206410159-4274b295-b3c0-4133-8c66-eb0714d0540c.png)

I also tested the domain name and SSL certificate

![image](https://user-images.githubusercontent.com/41416092/206410625-f347f86b-665d-4e2b-baba-a0e6a7318b1d.png)

Everything went as expected

However, when I want to do load balancing based on domain names, the problem arises

use the method of load balancing+ingress to configure the domain name based 7-tier load balancing (1. test. com/, 2. test. com/) instead of (1. test. com/test1, 1. test. com/test2)

MinioUI
![image](https://user-images.githubusercontent.com/41416092/206415368-a75cf045-996c-4f52-895f-e3604a02c220.png)

![image](https://user-images.githubusercontent.com/41416092/206411806-419657a2-2810-4ca3-ab2e-5ee4b25a97f4.png)

Nginx App
![image](https://user-images.githubusercontent.com/41416092/206415745-f2bf3f88-8577-4d82-ad37-8d00b1130ab6.png)

![image](https://user-images.githubusercontent.com/41416092/206411807-b5fa8d2c-3865-406d-abe8-2ab9cf47d32c.png)

**Question**
My question is whether Azure AKS has something like 'aws load balancer controller'（ https://github.com/kubernetes-sigs/aws-load-balancer-controller ）To implement (1. test. com, 2. test. com) without using the application gateway

（https://learn.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-existing?toc=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Faks%2Ftoc.json&bc=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json）

I'm using AKS for the first time. I don't know whether there is a problem with my configuration or whether AKS doesn't support this function. If there are relevant documents, please tell me the URL. Thank you！

**Comment by carvido1** [comment]
Hello @qingfengfenga .

To understand in a better way your problem, could you provide the ingress resources for the domains 1.test.com and 2.test.com? 

If you want to balance the requests based on subdomains, you can create independent ingress resources for each domain pointing to the same or different deployments. The loadbalancing effect can be tunbed using the [session affinity annotations](https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#session-affinity) on the ingress resource. To get real loadbalancing, you need to have more than 1 pod per application. From the screenshots you provided you have only 1 pod for the ingress-nginx controller.

BR

**Comment by qingfengfenga** [comment]
I have obtained support in the following third-party documents, thank you！

https://stacksimplify.com/azure-aks/ingress-domain-baed-routing-using-externaldns-and-aks/

![image](https://user-images.githubusercontent.com/41416092/207760423-ed9b49ed-16bd-4676-82ef-eeced7d1ea12.png)
