### ISSUE TITLE
[BUG] AKS cluster can't recover after dev subscription re-enabled after hitting limit in previous month

### ISSUE THREAD

**Issue by kamilon** [Azure/AKS#3385]
**Describe the bug**
My developer subscription with a spending limit was disabled for hitting the limit. After the subscription reset and became re-enabled the AKS cluster has not been able to get the node pool healthy. I've even tried creating another pool. I'm able to use and create other resource types.

**To Reproduce**
1. Deploy AKS cluster in spending limited subscription
2. Hit spending limit
3. Wait for subscription spending limit to reset
4. Repro

**Expected behavior**
AKS either automatically or manually is able to be brought back to a healthy state after the subscription was re-enabled. I can't start or stop the AKS cluster, start, stop or restart the host pool or anything.

**Screenshots**

**Environment (please complete the following information):**
 - CLI Version N\A
 - Kubernetes version 1.22.1
 - Browser Edge/Chrome

**Additional context**
The message I get is:
Failed to scale node pool 'xxx' in Kubernetes service 'xxx'. Error: autorest/azure: Service returned an error. Status=409 Code="SubscriptionNotRegistered" Message="Subscription is not registered."

**Comment by kamilon** [comment]
This has been sitting a while so I want to make sure it is known that this is still an issue. Assistance would be appreciated.

**Comment by justindavies** [comment]
Can you let us know what errors you are seeing when trying to bring this cluster back up?

**Comment by justindavies** [comment]
Would you be able to check in your subscription via the portal that the ContainerService provider is registered on your subscription?  It sounds like the registration has dropped off when your subscription was paused.

**Comment by kamilon** [comment]
I just confirmed it is registered.

**Comment by kamilon** [comment]
How do I escalate this issue? It's been months with no progress.

**Comment by AllenWen-at-Azure** [comment]
Hi @kamilon are you still seeing this issue? If it is the case, please file a support ticket, support engineers need your environment information to further investigate the issue.

**Comment by sjwaight** [comment]
Given no response from original reporter to request in September I am moving to close. @kamilon if this is still an issue please let us know.
