### ISSUE TITLE
Upgrading AKS from 1.19.x to 1.22.x per out of support notice advice

### ISSUE THREAD

**Issue by noahjd** [Azure/AKS#3386]
We have an AKS cluster is that is running 1.19.7 and we are needing to get this to 1.23.x to get back in support. However, through the azure portal/CLI we do not have the option to upgrade via the safe path, e.g. 1.19.7 => 1.20.x => 1.21.x => 1.22.x => 1.23.x. 

Our only option currently is to go directly to 1.22.x which I do not feel comfortable with. Is it generally safe to do this on AKS? this is not even recommended by Kubernetes to do. Just looking for some feedback perhaps if someone has ran into this and performed the upgrades in a similar fashion. Thanks.

**Comment by carvido1** [comment]
Hello.

According to AKS documentation skipping multiple minor versions can only be done when a [AKS cluster is out of support](https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#can-i-skip-multiple-aks-versions-during-cluster-upgrade). Also take into consideration that Azure does not guarantee the functionality of the cluster and they advise to recreate the AKS cluster if you are significantly out of date.

They point to the official [Kubernetes documentation about version skew policy](https://kubernetes.io/releases/version-skew-policy/). In this documentation you can find information about the different kubernetes components and the support between them with different versions.

Hope this helps you to make a decision about your cluster.
BR
