### ISSUE TITLE
CreatingLoadBalancerFailed

### ISSUE THREAD

**Issue by neutrongenious** [Azure/AKS#339]
i have provisioned new aks cluster. when i try to describe kubernetes service i can see following error:

  Warning  CreatingLoadBalancerFailed  3m (x88 over 6h)  service-controller  Error creating load balancer (will retry): Error getting LB for service default/kubernetes: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/*******************/resourceGroups/MC_akscluster-we_akscluster-we_westeurope/providers/Microsoft.Network/loadBalancers/kubernetes?api-version=2017-03-01: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '401'

**Comment by neutrongenious** [comment]
Duplicate of #357

**Comment by nphmuller** [comment]
Think it’s a different issue. Error message differs.

**Comment by slack** [comment]
`adal: Refresh request failed. Status Code = '401'` usually indicates that one of the following things has happened:
1. Service principal has been deleted
2. Service principal password has been changed
3. Service principal password has expired

AKS doesn't support SP rotation today, so you can reset the password (and the expiration) by running `az ad app update --id <servicePrincipalID> --pasword <oldPassword>`

**Comment by neutrongenious** [comment]
yup that did the trick.

**Comment by cnorburn** [comment]
Hey @slack, what do you recommend for an accidentally deleted SP?

**Comment by C123R** [comment]
Bumped into similar issue but not  with deleting the Service principal but it was expired.

As a quick workaround created new Key using Azure Portal and updated all the AKS nodes manually(/etc/kubernetes/azure.json) with new client secret and restarted one by one,moreover master node was not updated with new client_secret(obviously). Hence newly scaled up nodes were coming up with the expired client secret!!(Issue)

**30.01.2019** Got response from Azure Support that they are adding new option in azure cli to update the service principal.

**31.01.2019** Just upgraded my Azure CLI to check for the new feature, luckily it's there and updated my Test cluster and its works!

`az aks update-credentials --reset-service-principal --service-principal <client-id> --client-secret <secret>`

**Note:** the client-id and client-secret should be created by you

It basically update /etc/kubernetes/azure.json file on all the nodes and then reboot it one by one!

Tried with scale up as well and it works!

**Comment by newparul** [comment]
Error creating load balancer (will retry): failed to ensure load balancer for service default/hello-world: timed out waiting for the condition


getting this error while creating load balancer service in kubernetes cluster. have attached SP to the subnet both as contributer and subnet contributer but nothing helped...

**Comment by gsandi** [comment]
There is change in the command that C123R has posted. Here is the latest command 
`az aks update-credentials -g MyResourceGroup -n MyManagedCluster --reset-service-principal --service-principal MyNewServicePrincipalID --client-secret MyNewServicePrincipalSecret `

https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-update-credentials
