### ISSUE TITLE
[Question] How is the node working set Kubernetes metric calculated on Windows node?

### ISSUE THREAD

**Issue by fschmied** [Azure/AKS#3390]
**Describe scenario**
I have an Azure Kubernetes Services cluster that also includes a Windows node pool. For nodes in that node pool, Kubernetes tooling, such as `kubectl top nodes`, will provide a node working set metric (via the `metrics.k8s.io` API), rendered as a `MEMORY(bytes)` column. I've noticed that the number presented there matches neither of these:

* the sum of all Pod working sets (as reported by, e.g., `kubectl top pods`),
* the sum of all process working sets queried on the node itself (as reported by `Get-Process` and the result items' `WorkingSet64` or `PrivateMemorySize64` properties),
* the used memory reported on the node (as calculated from the `WIN32_OperatingSystem` WMI object's `TotalVisibleMemorySize` and `FreePhysicalMemory` properties).

**Question**
Can you tell me how the node working set metric is generated on a Windows node and what exactly it includes? This is important so we can interpret it for operating the Kubernetes cluster and know what it should be compared to (`Allocatable`? `Capacity`? something else?). A pointer to documentation would be great, as long as it applies to Windows nodes.

(Note: I've also posted this question here, with some more detail, but haven't got an answer yet: https://serverfault.com/questions/1117244/what-does-the-memorybytes-value-mean-in-kubectl-top-nodes-on-windows-aks-nod .)

**Comment by justindavies** [comment]
@marosset - can you help here?  I'll get the docs updated if that's needed too

**Comment by olsenme** [comment]
@marosset?

**Comment by marosset** [comment]
I can look into this in a few days (after K8s 1.27 code freeze)

**Comment by AbelHu** [comment]
Reference: https://github.com/kubernetes/kubernetes/issues/112111

**Comment by fschmied** [comment]
Thanks for the reference, so it's really an upstream issue. I'm closing this issue here.
