### ISSUE TITLE
[Feature] allow configuration of `--ignore-daemonsets-utilization`

### ISSUE THREAD

**Issue by peter-edb** [Azure/AKS#3399]
**Is your feature request related to a problem? Please describe.**

Based on my current understanding, testing and response from MS support AKS doesn't allow users to configure `--ignore-daemonsets-utilization` when doing calculations to scale down which in some cases can result in cluster never scaling down.

**Describe the solution you'd like**

If I have made a mistake and it is available, some steps or doco to enable it, otherwise allow users to configure `--ignore-daemonsets-utilization` in AKS as it has been available in Kubernetes since 2018, and the [aks-engine repo](https://github.com/Azure/aks-engine/blob/master/examples/addons/cluster-autoscaler/README.md) seems to suggest it is available

**Describe alternatives you've considered**

* Raising a support case with Azure in case I was missing something
* Tuning `scaleDownUtilizationThreshold`
* Tuning requests and limits in deployments
* Using larger VMs in the node pools

However, I feel ignoring daemonsets is cleaner

**Additional context**

* MS Case number: 2211290030000373
* [add flag to ignore daemonsets when calculating resource utilization of a node](https://github.com/kubernetes/autoscaler/pull/1407)

**Comment by peter-edb** [comment]
I had a go just in case it is available as per the AKS engine doco

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/95204098/207746082-2a406537-ebb9-4342-81e1-3abf6a3df5d5.png">

**Comment by techtenk** [comment]
+1 I was also looking for this today

**Comment by faroukellouze** [comment]
+1

**Comment by teck-kcheema** [comment]
+1

**Comment by teck-kcheema** [comment]
+1

**Comment by mruoss** [comment]
+1
For anybody interested if this flag has been included silently (not the case as of today): Here's the list of supported settings: https://learn.microsoft.com/en-us/azure/aks/cluster-autoscaler#use-the-cluster-autoscaler-profile

**Comment by kevinkrp93** [comment]
Currently working to expose this flag

**Comment by peter-edb** [comment]
This is awesome news! Thanks @kevinkrp93

**Comment by peter-edb** [comment]
Hi @kevinkrp93 , @justindavies I was wondering how this is coming along, do you have any updates?

**Comment by SaradaSastri** [comment]
When will this feature "ignore-daemonsets-utilization" be GA?

**Comment by kevinkrp93** [comment]
Will be GA end of May/ Early June

**Comment by SaradaSastri** [comment]
https://learn.microsoft.com/en-us/azure/aks/cluster-autoscaler?tabs=azure-cli
This is still in Preview. When will it be GA?

**Comment by rouke-broersma** [comment]
This is GA now

**Comment by kevinkrp93** [comment]
GA now
