### ISSUE TITLE
Error in kubernetes-dashboard

### ISSUE THREAD

**Issue by ziXet** [Azure/AKS#34]
I just fired up a new AKS (West US2) from Azure portal with one agent node. API works fine but kubernetes-dashboard is not working. getting the following error when I open http://localhost:8001/ui/

Error: 'dial tcp 10.244.0.4:9090: getsockopt: connection refused'
Trying to reach: 'http://10.244.0.4:9090/'

**Comment by relferreira** [comment]
I'm having the same issue with UK West

**Comment by eivim** [comment]
AKS (preview) has capacity problems in both regions. Microsoft is probably working on it.

**Comment by Naninani** [comment]
Location: westus2
k8s version 1.8.1
SKU: Standard_E32s_v3

`kubectl -n kube-system get po
NAME                                    READY     STATUS             RESTARTS   AGE
heapster-58f795c4cf-5qfnx               2/2       Running            0          59m
kube-dns-v20-6c8f7f988b-28wcm           3/3       Running            0          59m
kube-dns-v20-6c8f7f988b-zslft           3/3       Running            0          59m
kube-proxy-h8f4p                        1/1       Running            0          59m
kube-proxy-km8db                        1/1       Running            0          59m
kube-proxy-x982b                        1/1       Running            0          59m
kube-svc-redirect-pc5zs                 0/1       CrashLoopBackOff   16         59m
kube-svc-redirect-sscj8                 0/1       CrashLoopBackOff   15         59m
kube-svc-redirect-x8d2v                 0/1       CrashLoopBackOff   16         59m
kubernetes-dashboard-6fc8cf9586-csq8s   0/1       CrashLoopBackOff   14         59m
tunnelfront-g4qcv                       0/1       CrashLoopBackOff   16         59m
tunnelfront-nv992                       0/1       CrashLoopBackOff   16         59m
tunnelfront-w2jbx                       0/1       CrashLoopBackOff   15         59m
`

`kubectl get events -n kube-system
LAST SEEN   FIRST SEEN   COUNT     NAME                                                     KIND      SUBOBJECT                       TYPE      REASON       SOURCE                               MESSAGE
2m          1h           267       kube-svc-redirect-pc5zs.14f5d4384d7b1e7d                 Pod                                       Warning   FailedSync   kubelet, aks-agentpool1-38036297-2   Error syncing pod
32m         1h           131       kube-svc-redirect-pc5zs.14f5d43c8bee5b47                 Pod       spec.containers{redirector}     Warning   BackOff      kubelet, aks-agentpool1-38036297-2   Back-off restarting failed container
17m         1h           193       kube-svc-redirect-sscj8.14f5d43a92eaa244                 Pod       spec.containers{redirector}     Warning   BackOff      kubelet, aks-agentpool1-38036297-0   Back-off restarting failed container
2m          1h           257       kube-svc-redirect-sscj8.14f5d43a92ed9e55                 Pod                                       Warning   FailedSync   kubelet, aks-agentpool1-38036297-0   Error syncing pod
7m          1h           250       kube-svc-redirect-x8d2v.14f5d43839ba6c58                 Pod       spec.containers{redirector}     Warning   BackOff      kubelet, aks-agentpool1-38036297-1   Back-off restarting failed container
2m          1h           273       kube-svc-redirect-x8d2v.14f5d43839bc688b                 Pod                                       Warning   FailedSync   kubelet, aks-agentpool1-38036297-1   Error syncing pod
59m         1h           4         kubernetes-dashboard-6fc8cf9586-csq8s.14f5d43cc73455a1   Pod       spec.containers{main}           Normal    Created      kubelet, aks-agentpool1-38036297-1   Created container
59m         1h           4         kubernetes-dashboard-6fc8cf9586-csq8s.14f5d43cda1ac8bf   Pod       spec.containers{main}           Normal    Started      kubelet, aks-agentpool1-38036297-1   Started container
1m          1h           7         kubernetes-dashboard-6fc8cf9586-csq8s.14f5d444af28a9a8   Pod       spec.containers{main}           Warning   Unhealthy    kubelet, aks-agentpool1-38036297-1   Liveness probe failed: Get http://10.244.2.5:9090/: dial tcp 10.244.2.5:9090: getsockopt: connection refused
59m         1h           3         kubernetes-dashboard-6fc8cf9586-csq8s.14f5d4465cc141a2   Pod       spec.containers{main}           Normal    Pulled       kubelet, aks-agentpool1-38036297-1   Container image "gcrio.azureedge.net/google_containers/kubernetes-dashboard-amd64:v1.7.1" already present on machine
56m         1h           13        kubernetes-dashboard-6fc8cf9586-csq8s.14f5d44e228e9ca1   Pod       spec.containers{main}           Warning   BackOff      kubelet, aks-agentpool1-38036297-1   Back-off restarting failed container
6m          1h           221       kubernetes-dashboard-6fc8cf9586-csq8s.14f5d44e22904d6f   Pod                                       Warning   FailedSync   kubelet, aks-agentpool1-38036297-1   Error syncing pod
2m          1h           263       tunnelfront-g4qcv.14f5d43a6c73fbf5                       Pod       spec.containers{tunnel-front}   Warning   BackOff      kubelet, aks-agentpool1-38036297-2   Back-off restarting failed container
7m          1h           242       tunnelfront-g4qcv.14f5d43a6c768465                       Pod                                       Warning   FailedSync   kubelet, aks-agentpool1-38036297-2   Error syncing pod
16m         1h           198       tunnelfront-nv992.14f5d4383adcbdea                       Pod       spec.containers{tunnel-front}   Warning   BackOff      kubelet, aks-agentpool1-38036297-1   Back-off restarting failed container
1m          1h           265       tunnelfront-nv992.14f5d4383addcbd5                       Pod                                       Warning   FailedSync   kubelet, aks-agentpool1-38036297-1   Error syncing pod
2m          1h           256       tunnelfront-w2jbx.14f5d43f0b4eba3b                       Pod       spec.containers{tunnel-front}   Warning   BackOff      kubelet, aks-agentpool1-38036297-0   Back-off restarting failed container
11m         1h           212       tunnelfront-w2jbx.14f5d43f0b50c92f                       Pod                                       Warning   FailedSync   kubelet, aks-agentpool1-38036297-0   Error syncing pod`

**Comment by jespernohr** [comment]
deployment successful in eastus

![image](https://user-images.githubusercontent.com/11901812/32745135-0faebd34-c8b2-11e7-80bd-9cfd2119935a.png)

**Comment by khenidak** [comment]
Hi @ziXet thanks for reporting this clusters created on EastUS, or the new capacity regions (starting Monday 13th) supports kubectl proxy commands followed by pointing your browser to localhost:8001/ui

**Comment by slack** [comment]
This should be out in East US now and all new regions (coming soon). Please re-open if this pops up again.
