### ISSUE TITLE
Error setting Azure Tags for "container service (managed)" object - via Portal or Runbook

### ISSUE THREAD

**Issue by davidcyr** [Azure/AKS#340]
I have created an AKS cluster, and am working on tagging various resources within the cluster.

Today I noticed that when I try to add Azure-level tags to the "container service (managed)" object in the main resource group (i.e. the Resource Group I own and control, not the one that AKS creates to manage resources), I get an error.

When I try via the Portal, I get the message "Could not save the tags: Tag assignment failed, please correct any errors and try again. "  Tagging other resources seems to be working via the portal, but not this one.

When I try via a PowerShell runbook using code like <<Set-AzureRmResourceGroup -Tag $tags -Name $AKS_Resource_Group_Name>>, I get:
"Set-AzureRmResource : 405: Method Not Allowed"

**Comment by sburkart80** [comment]
Hi David,

same for me, where you able to get an answer yet?

BR
Sven

**Comment by jnoller** [comment]
Setting custom tags/RGs is on the AKS roadmap and not currently supported.
