### ISSUE TITLE
[Question] Azure Gov AKS release notes

### ISSUE THREAD

**Issue by anwarchk** [Azure/AKS#3400]
**Describe scenario**

As an Azure Gov customer, I would like to be kept in the loop for AKS features rolled out to the environment so that I can plan on making use of those capabilities.

**Question**
Is there a release note or roadmap for AzureGov AKS.

**Comment by carvido1** [comment]
Hello @anwarchk 

There is a [release tracker for AKS](https://releases.aks.azure.com/#tabus) that includes the release version to the Azure Gov Regions. It includes the release order sequence.

BR

**Comment by justindavies** [comment]
Hi there, the release notes will call out all features that are going to be rolled out, the only difference is that the Gov / Sovereign cloud deployments will usually land 2 weeks after the release notes.
