### ISSUE TITLE
[BUG] Known OS bug in AKSUbuntu-1804gen2containerd-2022.12.06

### ISSUE THREAD

**Issue by wurst-case-scenario** [Azure/AKS#3401]
Since we updated the node pools of our AKS cluster to Kubernetes 1.24.6 and the latest image AKSUbuntu-1804gen2containerd-2022.12.06 we get following error in all our applications:
`java.io.IOException: Duplicate accept detected. This is a known OS bug. Please consider reporting that you are affected: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1924298`

see [Ubuntu - Bug #1924298 accept returns duplicate endpoints under load](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1924298)

**Comment by wurst-case-scenario** [comment]
Same problem occurs in newer image AKSUbuntu-1804gen2containerd-2022.12.13

**Comment by wurst-case-scenario** [comment]
Same problem occurs in newer image AKSUbuntu-1804gen2containerd-2022.12.19

**Comment by justindavies** [comment]
Is this issue still occurring on later image updates?

**Comment by wurst-case-scenario** [comment]
It's still occuring in AKSUbuntu-1804gen2containerd-2023.01.10

**Comment by miwithro** [comment]
@wurst-case-scenario unfortunately this issue is still not fixed upstream.
