### ISSUE TITLE
Severe memory leak in hcsshim - please update containerd to 1.6.13 in Windows images

### ISSUE THREAD

**Issue by fschmied** [Azure/AKS#3405]
We're facing a severe memory leak related to command probes in hcsshim on Windows nodes in our AKS cluster: https://github.com/microsoft/hcsshim/issues/1574 . Note that it surfaces both in our workloads and in system pods.

The issue is already fixed and the fix is included in containerd 1.6.13 (https://github.com/containerd/containerd/releases/tag/v1.6.13). Please update to that version in the next AKS release's Windows node images.

**Comment by JCDeist** [comment]
This issue is causing multiple of our nodes to crash on a regular basis. Please get this updated in the next image.

**Comment by fschmied** [comment]
Unfortunately, the 2023-01-08 release didn't update the containerD version, see https://github.com/Azure/AKS/releases/tag/2023-01-08. (Or did they even [regress to Docker](https://github.com/Azure/AKS/issues/3423)?)

Not sure if anyone from the AKS team has seen this feature request yet, we might need to go via Azure Support. @JCDeist Have you perchance opened an support ticket already?

**Comment by regan-starrez** [comment]
@fschmied - @JCDeist and I have a ticket sitting with Microsoft currently, they've states that the fix should be rolling out in the latest AKSImages. We're still waiting on a response with validation to confirm that this is the case.

**Comment by fschmied** [comment]
@regan-starrez Okay, cool, thanks for the information!

**Comment by regan-starrez** [comment]
@fschmied - We've received confirmation this fix is out in the 20230115 release - https://github.com/Azure/AKS/releases/tag/2023-01-15

**Comment by fschmied** [comment]
Indeed, thanks for sharing!

**Comment by fschmied** [comment]
It's a pity that the AKS team doesn't react on such issues on Github :( .
