### ISSUE TITLE
[Question] Which workload identity version is used in which release?

### ISSUE THREAD

**Issue by jack4it** [Azure/AKS#3412]
**Describe scenario**

We want to know which workload identity version is baked into which AKS release. Do we have that version mapping information documented somewhere?

**Question**

E.g., the lastest [v0.15.0](https://github.com/Azure/azure-workload-identity/releases/tag/v0.15.0) release of workload identity has an important bug fix we wanted to know when it will be included in AKS release. Is the release [v20221204](https://github.com/Azure/AKS/releases/tag/2022-12-04) having it or still the older `v0.14.0`?

Thanks!

**Comment by CocoWang-wql** [comment]
Hello @jack4it , it is contained in v2023-01-22. You can refer to[ AKS release notes](https://github.com/Azure/AKS/releases/tag/2023-01-22) for details.  Thanks
