### ISSUE TITLE
[Question] Upgrade to Managed Identity for Availability Set AKS

### ISSUE THREAD

**Issue by K31D** [Azure/AKS#3415]
**Describe scenario**
AKS Cluster created with Availability Sets instead of Scale Sets for node pools

**Question**
Is the [documentation ](https://learn.microsoft.com/en-us/azure/aks/use-managed-identity#update-an-aks-cluster-to-use-a-managed-identity) for upgrading AKS from service principal to managed identity valid also for AKS cluster created in the beginning with Availability Sets node pool instead of Scale Sets ?

**Comment by sabbour** [comment]
Tagging @miwithro

**Comment by CocoWang-wql** [comment]
Hello @K31D , yes, VMAS (virtual machine availability sets) is supported.
(If it's not supported, we will mention it in doc-limitations).

After we run the `az aks update -g <RGName> -n <AKSName> --enable-managed-identity` command,  we need to reiamge nodes.
For VMAS cluster, we have two methods for reimage:
	* Scale down and scale up the Node VMs.  
	New created VMs would use new VHD image but not the previous issue image.
	* Upgrade AKS cluster
