### ISSUE TITLE
[Feature] Configure app routing ingress with Private Internal Load Balancer during cluster create

### ISSUE THREAD

**Issue by LefeWareSolutions** [Azure/AKS#3416]
**Is your feature request related to a problem? Please describe.**
I am working with a large client of the Azure platform who has shown significant interest in leveraging the Web Application Routing addon for AKS once its out of preview as a way of simplifying ingress deployments. As part of their security requirements they are required to use a private internal load balancer for all AKS clusters. Reading through the documentation I did not see any options to support this. 

**Describe the solution you'd like**
Would it be possible to support a private internal load balancer with the AKS Web Application Routing? 

**Describe alternatives you've considered**
The client currently doing manual configuration of NGINX ingress controllers via Helm charts

**Additional context**
Maybe this is already possible somehow and I am just unaware how to do  so? Any guidance would be greatly appreciated

**Comment by sabbour** [comment]
This is on the roadmap.

**Comment by LefeWareSolutions** [comment]
@sabbour do you have expected delivery date? Q1, Q2? Also will this be part of the GA release?

**Comment by denniszielke** [comment]
It seems you can change the annotations on an existing deployment and turn the load balancer to use private ip but I have a lot of customers who do not allow public ip via policy. It would be great if the addon could be activated with private ip from the start.

**Comment by sabbour** [comment]
That's the plan. We'll allow the installation of the add-on with external, internal, or both setups from the start.

**Comment by dmeytin** [comment]
+1 for this feature

**Comment by hkarshad** [comment]
+1 for this feature

**Comment by coolhome** [comment]
+1

I thought this was supported because of this documentation for web application routing - https://learn.microsoft.com/en-us/azure/aks/app-routing?tabs=default%2Cdeploy-app-default

```
Next steps
[Configure custom ingress configurations](https://learn.microsoft.com/en-us/azure/aks/app-routing-configuration) shows how to create Ingresses with a **private load balancer**, configure SSL certificate integration with Azure Key Vault, and DNS management with Azure DNS.
```

**Comment by haithamshahin333** [comment]
Hi Team,

+1 to this, any status on private ILB for the add-on?

**Comment by rickijen** [comment]
+1, please add ILB support.

**Comment by frasmarco** [comment]
+1

**Comment by HakjunMIN** [comment]
Oh. Please. +1

**Comment by ageorgousakis** [comment]
+1
Is there are any workaround to change the nginx use a private IP?

**Comment by HakjunMIN** [comment]
@ageorgousakis 

For workaound this is not perfect but decent working way here until official feature is released.

```bash
kubectl annotate --overwrite svc nginx -n app-routing-system  service.beta.kubernetes.io/azure-load-balancer-internal="true"  service.beta.kubernetes.io/azure-load-balancer-internal-subnet=<your-ilb-subnet> service.beta.kubernetes.io/azure-pls-create="true"  
```

**Comment by ageorgousakis** [comment]
@HakjunMIN Thanks for the tip. 

I tried it but I didn't see any effect. The annotations created in the service but the external IP remains the public IP I had before. Do I need to do something else after this command? Also the <your-ilb-subnet> is the name of the subnet AKS my Azure CNI takes IPs, or another?

**Comment by ageorgousakis** [comment]
I found the problem. The AKS principal ID didn't have Network Contributor permission in the vNet's subnet.

Thanks @HakjunMIN

**Comment by asashiho** [comment]
+1❤

**Comment by CrisNevares** [comment]
+1 for this feature

**Comment by sabbour** [comment]
An update for everyone, this is now possible.
https://learn.microsoft.com/en-us/azure/aks/app-routing-nginx-configuration

**Comment by adamzeyinsurity** [comment]
> An update for everyone, this is now possible. I'll keep this open until configuration during add-on installation is released. https://learn.microsoft.com/en-us/azure/aks/app-routing-nginx-configuration

The documentation doesn't actually specify how to accomplish this, it only mentions adding an additional internal load balancer, not how to use an internal load balancer instead of a public one. We can't have any public resources for security reasons.

**Comment by chanster** [comment]
> Documentation: https://learn.microsoft.com/en-us/azure/aks/create-nginx-ingress-private-controller Configuration during 

This still does not offer defaulting to an internal LB on deployment. This just adds an internal ingress but the public ingress is still created. We currently have to update the annotations after enabling this add-on. We see no options via GUI, azure CLI, or Terraform to set additional options for initial deployment.

**Comment by NickTrevor** [comment]
+1

**Comment by sabbour** [comment]
Defaulting during add-on enablement is now possible. Documentation is being published.
Configuration via the CLI is coming with the next CLI release.

**Comment by sabbour** [comment]
This is now possible: https://learn.microsoft.com/en-us/azure/aks/app-routing-nginx-configuration?tabs=bicep#control-the-default-nginx-ingress-controller-configuration

**Comment by thehedhly** [comment]
Hey @sabbour,  Is it possible that a configuration step might be missing from the provided setup guide/documentation for "Internal" Ingress ?
Context: https://github.com/Azure/AKS/issues/4487

**Comment by chanster** [comment]
If setting `defaultIngressControllerType` to something other than `AnnotationControlled`, does it ignore all annotations?

Say we want to change the subnet it is created in with an annotation:
```yaml
metadata
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "SUBNET_NAME"
```
I don't see the ability to set the subnet on creation. Is the expectation that if we need more customization we should set `defaultIngressControllerType` to `None` and create the resource manually?

**Comment by dstarkowski** [comment]
@sabbour 
How about all the other configuration options?

    service.beta.kubernetes.io/azure-load-balancer-internal-subnet
    service.beta.kubernetes.io/azure-load-balancer-ipv4
    service.beta.kubernetes.io/azure-pls-...

**Comment by thehedhly** [comment]
@dstarkowski  
# Options 1
I think you should go with **defaultIngressControllerType** set to "**None**" as it does not create a default Nginx ingress controller and then create BYO internal NGINX ingress controller with a private IP address ..etc as described here:
```yaml
apiVersion: approuting.kubernetes.azure.com/v1alpha1
kind: NginxIngressController
metadata:
  name: nginx-internal
spec:
  ingressClassName: nginx-internal
  controllerNamePrefix: nginx-internal
  loadBalancerAnnotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "<subnet>"
    service.beta.kubernetes.io/azure-load-balancer-ipv4: "<ipv4 address>"
    # service.beta.kubernetes.io/azure-pls-...
```

# Options 2:
However, I'm not entirely sure whether this will work, depends on how editing the default NginxIngressController custom resource is handled, but imo it worth trying ..
 
Set the **defaultIngressControllerType** to "**AnnotationControlled**" then edit the default NginxIngressController custom resource.



Source: https://learn.microsoft.com/en-us/azure/aks/app-routing-nginx-configuration?tabs=bicep#control-the-default-nginx-ingress-controller-configuration

**Comment by dstarkowski** [comment]
Thanks, @thehedhly

Since `AnnotationControlled` is the default value, Option 2 is what we've already been doing.
The hope was that this issue will allow us to automate those steps in one place (Bicep).

`None` is seems like the way forward for future deployments.
