### ISSUE TITLE
Uncordoning a node makes node unschedulable

### ISSUE THREAD

**Issue by rfum** [Azure/AKS#342]
One of my nodes, has memory stress and this made the node state to NotReady. I had PodDistruptionBudget defined for some of my deployments. I've decided to move my pods from this node to other healthy nodes. I've did `kubectl drain <node-name>`  to move my pods as I've described in PDB.My pods scheduled as it has to be. From now, I've managed to find which of my deployments are creating memory spikes and I've did some tricks to prevent these spikes. After this, I've uncordoned the individual node with `kubectl uncordon <node-name>` .Even though , the node is in Ready state but pods cannot be scheduled on this node. I've restarted the node everything went fine. So this one seems like a bug from my vision. Anyone ever faced a situation like this ?

**Comment by slack** [comment]
Curious. Are you able to reproduce? If so, seeing `describe node` output would be great.

**Comment by slack** [comment]
I understand that restarting the node allowed new work to schedule.

If you cordon and uncordon the nodes, does the unschedulable behavior return?

If so, please re-open this issue and add output from `kubectl describe node`!
