### ISSUE TITLE
[BUG] Accelerated networking is being disabled

### ISSUE THREAD

**Issue by dmichel1** [Azure/AKS#3420]
**Describe the bug**

Accelerated networking (AN) is being disabled on the VMSS of the node group after node OS updates.

We have 40+ clusters spread around a number of regions. Each cluster contains 1-2 node groups. Each of those node groups start with AN enabled and over time AN eventually gets disabled.

I've been trying to grok the activity logs and I believe this can be tied back to when a node groups OS happens. Screenshots attached.

We don't have any automation on our side interacting with the VMSS directly. Even if we did, all the VMSS would lose the AN setting around the same time. What I've been observing is AN slowly being disabled across all our node groups over many days/weeks.

**To Reproduce**
1. Create a cluster and a node group with an instance type sku that supports AN.
2. Wait some amount of time for the OS update to happen.
3. AN is disabled.

**Expected behavior**

AN stays enabled.

**Screenshots**

<img width="1754" alt="Screen Shot 2023-01-10 at 4 24 36 PM" src="https://user-images.githubusercontent.com/677960/211843100-97f7eb9f-2fa3-4528-94ae-7ca54361dcda.png">

<img width="1888" alt="Screen Shot 2023-01-10 at 1 15 13 PM" src="https://user-images.githubusercontent.com/677960/211843138-dcc81855-46df-4dd7-abca-301667600b1d.png">

**Environment (please complete the following information):**
 - Kubernetes version - 1.22.11

**Additional context**

Here's an internal ticket tracking this issue, #2212210040005513. The ticket contains cluster and VMSS ids.

**Comment by justindavies** [comment]
@dmichel1 is this still happening ?

**Comment by dmichel1** [comment]
@justindavies still happening but getting closer to a resolution. There's more info on the attached ticket.

**Comment by dmichel1** [comment]
Fixed was rolled out. AN is now enabled.
