### ISSUE TITLE
AKS label deprecation dates

### ISSUE THREAD

**Issue by ondrejhlavacek** [Azure/AKS#3426]
**Describe scenario**
I am interested in which AKS/K8s version will these labels be deprecated - https://learn.microsoft.com/en-us/azure/aks/use-labels#deprecated-labels. In AKS release notes there is a generic information for each minor version 1.24+ and the documentation does not provide any further information.

**Question**
What AKS version will deprecate the `agentpool` label? As this label is not a reserved label, can I set it using an ARM template?

**Comment by qpetraroia** [comment]
Hi @ondrejhlavacek,

Thanks for letting us know that you would like more information regarding the label deprecation dates. You can take a look at our [release calendar](https://learn.microsoft.com/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar) to see when new k8s versions are coming out as new k8s versions are tied to deprecations. 

Regarding your question, it seems that the agentpool label was deprecated in 1.24. Did you have any more questions?
