### ISSUE TITLE
Update Azure Policy namespace exclusion behavior

### ISSUE THREAD

**Issue by charleswool** [Azure/AKS#3429]
We will rollout few changes to update Azure Policy’s namespace exclusion behavior. No action required.

**Comment by mateuszdrab** [comment]
Adding a short summary of the issue for other customers who might share the same concerns

Currently, we mark critical namespaces with the control-plane=true label which gatekeeper excludes from enforcement to ensure cluster stability. This allows any user with access to any namespace to simply append the label and bypass GK. There is no policy deployed by default to prevent such label from being applied.

The product team will mitigate the issue with the following steps:
1. Removal of excluded labels on namespaces: aks-periscope, control-plane, and calico-system
2. The change is projected to arrive with the latest Gatekeeper v3.10, it will be added in the release notes so customers have the option to upgrade to this version.
3. The latest GK will come together with AKS 1.26 preview and the rollout will begin then as older versions become unsupported.
