### ISSUE TITLE
--generate-ssh-keys can overwrite users own id_rsa key

### ISSUE THREAD

**Issue by absoludity** [Azure/AKS#343]
The command:
> az aks create --resource-group myResourceGroup --name myAKSCluster --node-count 1 --generate-ssh-keys

when run from the az cli docker container, writes (and overwrites) `/root/.ssh/id_rsa` and `/root/.ssh/id_rsa.pub` which can be destructive (overwriting peoples' personal keys) if they've followed the instructions at:

https://docs.microsoft.com/en-us/cli/azure/run-azure-cli-docker

to

> docker run -it -v ${HOME}:/root microsoft/azure-cli

**Comment by mboersma** [comment]
@absoludity this is core `az` CLI behavior (not just AKS) that was changed a while ago. Now in this case you should get the following error message:
```
Public SSH key file 'id_rsa.pub' already exists in the directory: '/Users/matt/.ssh'.
New SSH key files will not be generated.
```

**Comment by absoludity** [comment]
Great, thanks @mboersma - that's a much safer default behaviour :)
