### ISSUE TITLE
[Feature] AKS backup and restore

### ISSUE THREAD

**Issue by slawekww** [Azure/AKS#3430]
**Is your feature request related to a problem? Please describe.**
For Disaster Recovery, AKS cluster should be backup and restore in consistent way including:
* kubernetes manifests (opt-in as system manifests may differ and applications may be managed by GitOps)
* volumes created by Azure CNI drivers
* access to PaaS services used by AKS (ACR, Private Endpoints, etc)

Once AKS is backup, it should be possible to restore it:
* as new AKS instance in the same Azure subscription and region as backup instance
* as new AKS instance in the same Azure subscription as backup instance and paired region for backup instance
* as new AKS instance in the same Azure subscription as backup instance and different region (non-paired)
* as new AKS instance in another Azure subscription and the same region as backup instance
* as new AKS instance in another Azure subscription and paired region for backup instance
* as new AKS instance in another Azure subscription and different region (non-paired)

Assumed that all resources in Azure resource group for restoration are available (VNET, VM quotas) and AKS is restored based on backup to serve application as on backup cluster.

**Describe the solution you'd like**
The main bottle-neck is now volume restoration created by Azure CSI drivers across Azure regions: create Azure snapshots which can be restored in any Azure region at any Azure subscription by Azure CSI drivers. 

Kubernetes manifests restoration may be optional as GitOps approach should help with it already.

Access to PaaS services used by AKS does not sounds critical as Infrastructure as Code approach may help in this.
Anyway all ACR attached to AKS may be accessible on restored cluster without attaching ACRs again.

**Describe alternatives you've considered**
Backup **content of CSI volumes** in consistent way and restore them on any cluster if Azure snapshots are not possible to handle it.

**Additional context**
It would allow Business Units to create consistent and supported by Microsoft Disaster Recovery strategies.

**Comment by olsenme** [comment]
@saurabh0501
