### ISSUE TITLE
Please support ssh-ed25519 keys

### ISSUE THREAD

**Issue by kellervater** [Azure/AKS#3434]
I tried to use my ed25519 public key to create a new VM. It doesn't work, since Azure in general doesn't support these keys. See: https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/ed25519-ssh-keys
But I honestly don't get why this isn't supported.

Another issue here: The input field error for `SSH Public Key` is also misleading. It says: "Multiline SSH key must begin with '---- BEGIN SSH2 PUBLIC KEY ----' and end with '---- END SSH2 PUBLIC KEY ----'."

**Describe the solution you'd like**
I'd like to be able to use ed25519 public keys and/or a non-misleading error message, when another/wrong key is being used.

**Describe alternatives you've considered**
I need to create a separate rsa key for my client machine. This is kinda tedious since we agreed to use ed25519 in our company.
BUT.. I'm also not sure if we could circumvent this issue by modifying the `authorized_keys` file ourselve.

**Additional context**
There have been issues here which addressed this exact issue but went stale and ultimately have been closed:
https://github.com/Azure/AKS/issues/2850
https://github.com/Azure/AKS/issues/1172

**Comment by CocoWang-wql** [comment]
Hello @ppoetz , can you pls open a ticket to Azure VM team about this design.

**Comment by bbaassssiiee** [comment]
https://medium.com/risan/upgrade-your-ssh-key-to-ed25519-c6e8d60d3c54
