### ISSUE TITLE
[BUG] Failed (automated) node-image upgrade leaves node cordoned

### ISSUE THREAD

**Issue by BenjaminHerbert** [Azure/AKS#3439]
**Describe the bug**
We [enabled automatic upgrades with node-image channel](https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-cluster#using-auto-upgrade) on a cluster. Due to a restrictive PDB, one nodepool could not upgrade _in time_, the nodepool went into _Failed_ state.

One of the nodes stayed **cordoned**.

**To Reproduce**
The exact steps are unclear.

**Expected behavior**
After a failed upgrade, I expect all nodes to be available, as before the upgrade started.

**Screenshots**
-

**Environment (please complete the following information):**
 -  CLI Version - not applicable
 - Kubernetes version 1.23.12

**Additional context**
-

**Comment by kaarthis** [comment]
This does not seem like the current behavior and , so would like to understand more but there are no clear repro steps so suggest opening a case with Support - so we can closely look at this cluster / case .

**Comment by BenjaminHerbert** [comment]
@kaarthis It happened again yesterday, after I tried to reconcile a failed node-image upgrade. I have opened the case: 2302210050002164.
