### ISSUE TITLE
Tiller on AKS 1.9.2 is old how to upgrade the version of tiller

### ISSUE THREAD

**Issue by JuneZhao** [Azure/AKS#344]
I failed to get release on with below command on my aks cluster
helm get release
june@Azure:~$ helm get release
Error: incompatible versions client[v2.9.0] server[v2.8.2]

How can I upgrade the tiller in AKS cluster to make it compatible
june@Azure:~$ helm version
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

**Comment by sonicos** [comment]
helm init --upgrade

**Comment by JuneZhao** [comment]
@sonicos  thank you this will upgrade the tiller pod right?

**Comment by williamayerst** [comment]
Yes, it should do both client and server. `helm reset` will remove the tiller deployment from the cluster.
