### ISSUE TITLE
[BUG] Calico is not installed when network policy is set to 'Calico' (capitalized)

### ISSUE THREAD

**Issue by VijayRod** [Azure/AKS#3444]
**Describe the bug**

Calico is not installed when network policy is set to 'Calico' (capitalized), but it works as expected when set to 'calico' (all lower case).

**To Reproduce**

1. Run command az aks create with --network-policy Calico.
2. Calico pods are not deployed to cluster.

**Additional context**

--network-plugin kubenet --network-policy Calico. Success cluster create operation. No calico pods.
kube-system   coredns-autoscaler-5655d66f64-pgzck   1/1     Running   2 (9s ago)    2m57s
kube-system   metrics-server-58df99c858-dqvqw       1/2     Error     2 (37s ago)   2m56s
kube-system   metrics-server-58df99c858-l4zvf       1/2     Error     2 (37s ago)   2m56s

--network-plugin azure --network-policy Calico. Success cluster create operation. No calico pods.
kube-system   coredns-autoscaler-5655d66f64-624c9   1/1     Running   0          2m15s
kube-system   metrics-server-5f8d84558d-t2lpp       2/2     Running   0          79s
kube-system   metrics-server-5f8d84558d-xxqwh       1/2     Running   0          79s

--network-plugin kubenet --network-policy calico. Success cluster create operation.
calico-system     calico-kube-controllers-7c9666c4c6-scvgz   1/1     Running   1 (2m24s ago)   2m53s
calico-system     calico-node-5c7rq                          1/1     Running   0               2m53s
calico-system     calico-node-gs99f                          1/1     Running   0               2m53s
calico-system     calico-node-tccs7                          1/1     Running   0               2m53s
calico-system     calico-typha-55d76f6d76-94rrf              1/1     Running   0               2m53s
calico-system     calico-typha-55d76f6d76-zw8lf              1/1     Running   0               2m46s
kube-system       coredns-autoscaler-5655d66f64-w4hd4        1/1     Running   0               4m26s
kube-system       metrics-server-5f8d84558d-qj7t7            2/2     Running   0               2m22s
kube-system       metrics-server-5f8d84558d-tkqnd            2/2     Running   0               2m22s
tigera-operator   tigera-operator-795d5b9975-752lr           1/1     Running   0               4m24s

**Comment by wedaly** [comment]
We are actively working on a fix for this issue. Currently expect the fix to reach all public cloud regions by mid-February.
