### ISSUE TITLE
Does disabling CSI drivers impacts connectivity between azure key vault and AKS?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/AKS#3448]
Team,

We are not using any persistent volume or any kind of storage etc. If we execute the command listed on [this link](https://learn.microsoft.com/en-us/azure/aks/csi-storage-drivers#disable-csi-storage-drivers-on-a-new-or-existing-cluster) 

`az aks update -n myAKSCluster -g myResourceGroup --disable-disk-driver --disable-file-driver --disable-blob-driver --disable-snapshot-controller`

Does this impact the connectivity of azure key vault and AKS cluster. [As per this link](https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-driver), csi drivers are also used here in key vault connectivity.

The csi drivers mentioned on both the links are different or they have some connection between each other. Please suggest?

Kind Regards,
Tanul

**Comment by sabbour** [comment]
Azure Key Vault uses the [Secret Store CSI driver](https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master) which is enabled via a different flag.
