### ISSUE TITLE
Unable to specify --horizontal-pod-autoscaler-cpu-initialization-period and --horizontal-pod-autoscaler-initial-readiness-delay on a HPA object in AKS

### ISSUE THREAD

**Issue by harinarayanan-muthukumar** [Azure/AKS#3451]
Our applications are very heavy during start up and consumes huge CPU when it boots or restarts which makes us not being able to apply native simple HPA's to our deployments.  Whats happening is every pod creation / restart increases the CPU , which in turn triggers HPA that adds one more pod , which again throttles the CPU .. so on and so forth . 

I was looking at adding --horizontal-pod-autoscaler-cpu-initialization-period and --horizontal-pod-autoscaler-initial-readiness-delay to my workloads HPA setting  to see if this is something I can do to stabilize this but looks like there is no way to specify these flags on the actual YAML's . 

Many document says this is controlled on the cluster level by a global setting and I am unsure if its possible to edit those with an hosted k8s like AKS . 

Do let me know if there is some other way of handling this situation or would this be a limitation with AKS ? Another option which I am yet to review is to use a Custom pod autoscaler

**Comment by sabbour** [comment]
I believe the HPA is configured at a cluster level. These cannot be changed at an individual HPA object.

**Comment by animalis007** [comment]
We are having this issue as well and would like to be able to edit --horizontal-pod-autoscaler-cpu-initialization-period.
