### ISSUE TITLE
All AKS nodes coming up with the same machineID

### ISSUE THREAD

**Issue by brian1917** [Azure/AKS#3452]
**Describe the bug**
AKS clusters are coming online with duplicate machineIDs for all nodes.

**To Reproduce**
1. Create a new AKS cluster with at least two nodes
2. Run `kubectl get nodes -o yaml | grep machineID` and observe output like 
```
machineID: de1dd9ede40041b7bceb409b0a3b12cb
machineID: de1dd9ede40041b7bceb409b0a3b12cb
```
It seems all AKS cluster nodes (even on different clusters) have the same machineIDs.

**Expected behavior**
Unique machineIDs on each node.

**Environment (please complete the following information):**
 - Kubernetes version 1.24.9

**Comment by AllenWen-at-Azure** [comment]
Close this issue as it was answered in https://github.com/Azure/AKS/issues/3452#issuecomment-1456036477
