### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by girish-venkitaraman** [Azure/AKS#3455]
We upgraded the AKS recently from 1.24.3 to 1.25.2 version. AKS upgrade completed successfully and PODS are healthy, but services inside PODS are not running. When I tried to start up the services, I was getting AKV (application Key Vault) issue and we resolved the AKV issue, but now still services are not able to connect to Application Insights and I am getting RBAC permission error.

**Comment by sabbour** [comment]
@girish-venkitaraman how are the pods authenticating to those services? Are they using Workload Identity?
