### ISSUE TITLE
[BUG] BYO Kubelet Identity does not appear on nodes in VMAS

### ISSUE THREAD

**Issue by alexadams-ms** [Azure/AKS#3456]
**Describe the bug**
In VMAS, when using Bring-Your-Own Kubelet MSI, the Kubelet MSI does not appear on the Node VMs and must be added manually. 

Because the MSI is missing from the new nodes, it causes cascading failures, such as AAD-Pod-Identity being unable to find the MSI (because it's missing from the node VM). 

**To Reproduce**
1) Create two User-Assigned MSIs.
2) Give both MSIs relevant role assignments (I gave them both Owner over the whole subscription to ensure that they would have everything necessary)
3) Create AKS cluster using VMAS with User-Assigned MSI for Cluster and User-Assigned MSI for Kubelet.
`az aks create --resource-group myResourceGroup --name myClusterName --vm-set-type AvailabilitySet --enable-managed-identity --assign-identity <myClusterMsi> --assign-kubelet-identity <myKubeletMsi>`
4) Check the Node VMs to see what managed identities are assigned.

**Expected behavior**
The newly created node VMs should have the Kubelet MSI assigned to them.

**Actual Behavior**
The newly created node VMs do not have the Kubelet MSI assigned to them.

**Screenshots**
The newly created Node VM does not have the Kubelet MSI assigned: 
![image](https://user-images.githubusercontent.com/104788468/217094773-df1aa17f-bf1b-428a-91a2-b18226d45793.png)

**Environment (please complete the following information):**
 - Kubernetes version - 1.23.12, 1.24.6

**Additional context**
This is causing problems because it prevents AADPodIdentity from working correctly. 

I can manually assign the MSIs to the VMs, however, if I attempt to scale the node pool or upgrade the kubernetes version, new node VMs will be created which will again not have the proper MSI assigned. So I will have to continue to manually assign the MSIs. 

If you do not bring your own kubelet MSI, instead bring only Cluster MSI, a Kubelet MSI will be auto-generated for you. This auto-generated MSI will behave properly. However, this is not an option for us, because we need to have the MSI have the correct role assignments BEFORE assigning it to the cluster to avoid downtime (which is impossible if the MSI is auto-generated during assignment). 

(In my case I am actually migrating existing cluster from SP -> MSI, which is why I need to do it this way, but to simplify reproduction steps I have left that part out.)

**Comment by CocoWang-wql** [comment]
Tracking the issue~

**Comment by CocoWang-wql** [comment]
The fix is rolling out with v2023.07.16.
![image](https://github.com/Azure/AKS/assets/45681473/e32eae15-db7d-4a7b-af28-3892777f1168)
It works in my test env now.
