### ISSUE TITLE
Unable to run helm chart in AKS, fails with Error: no available release name found

### ISSUE THREAD

**Issue by ErickWendel** [Azure/AKS#346]
As per the intructions in https://docs.microsoft.com/en-us/azure/aks/kubernetes-helm, the call to run a helm chart fails.

```
$ kubectl version --short
Client Version: v1.10.1
Server Version: v1.8.11
 

$ brew install kubernetes-helm 
 
$ helm init
$HELM_HOME has been configured at /Users/erickwendel/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈

$ helm install stable/nginx-ingress --name  nginx
Error: Get http://localhost:8080/version: dial tcp [::1]:8080: connect: connection refused

$ helm get release

Error: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)release%!C(MISSING)OWNER%!D(MISSING)TILLER: dial tcp [::1]:8080: connect: connection refused

$ helm reset
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp [::1]:8080: connect: connection refused

```

To test reasons, I run in another terminal 

```
az aks browse --resource-group $RESOURCE --name $CLUSTER_NAME

Merged "k8s-cluster" as current context in /var/folders/w0/tmhy86g10cb8k2883jbs63tm0000gn/T/tmp058ithfu
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
Forwarding from 127.0.0.1:8001 -> 9090
Forwarding from [::1]:8001 -> 9090
```

But I cant't run kubectl on port `8080` (that helm needs)
So, I try to run standalone kubectl
```
$ kubectl proxy --port=8080
Starting to serve on 127.0.0.1:8080
```
But the same problem continues 😢 
```
$ helm get release

Error: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)release%!C(MISSING)OWNER%!D(MISSING)TILLER: dial tcp [::1]:8080: connect: connection refused
```

**Comment by colemickens** [comment]
Are you running those from the same session? `helm` is clearly trying to connect to localhost, instead of to the AKS cluster.

Is `KUBECONFIG` the same for both invoking `kubectl` and `helm` in your examples? Or do you rely on the contents of `~/.kube/config` ?

**Comment by colemickens** [comment]
Also, out of curiosity, and because it might be relevant... what exactly *is* going on with your KUBECONFIG?

For example, when you did `az aks browse` it pulled a(nother) copy of your creds and merged it into `KUBECONFIG`... which apparently was: `/var/folders/w0/tmhy86g10cb8k2883jbs63tm0000gn/T/tmp058ithfu`. Can you explain what that is, or ensure it's not related?

**Comment by lorsabyan** [comment]
The solution provided in [this](https://github.com/kubernetes/helm/issues/3055#issuecomment-385439879) comment helped me.
```
kubectl delete deployment tiller-deploy --namespace kube-system
helm init --upgrade --service-account default
```

**Comment by AronT-TLV** [comment]
I had the same problem. I created a brand new cluster and followed the instructions in the doco:
```
helm init
helm repo update
helm list
<get error>
helm install stable/<x>
<get error>
```
This used to work fine without having to apply the above fix. I think the error in the doco is that instead of `helm init` you need to do `helm init  --service-account default` first time?

**Comment by neilpeterson** [comment]
I believe this will be fixed in helm v2.9.1. In the interim, I will have the AKS doc updated with the workaround. I will not be able to get this published until Monday morning.

Thanks

**Comment by AronT-TLV** [comment]
That would be great, thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nguyenhuuloc304** [comment]
I encountered the same issue. then I tried following 
```
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
```
with the 
`kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'`
I got the message "Error from server (BadRequest): invalid character 's' looking for beginning of object key string"

and then I tried following commands
```
$ kubectl create serviceaccount --namespace kube-system tiller
$ kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
$ helm init --service-account tiller
```
I got the message: 
`failed: clusterroles.rbac.authorization.k8s.io .... [clusterroles.rbac.authorization.k8s.io "cluster-admin" not found]`

Please help me!...
Below is my information:
helm version
```
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
minikube version
`minikube version: v0.25.0`

The strange is I was using Helm to install stable/nginx-ingress on May 9 and successfully, then I deleted Kubernetes (for practice), then re-install Kubernetes today and install stable/nginx-ingress again .... Ops got above error.

Thank you so much for your support in advance

**Comment by neilpeterson** [comment]
@nguyenhuuloc304 recently, the stable [NGINX chart was updated](https://github.com/kubernetes/charts/commit/c60086ec0b260996281d337d67f2361f826f7029#diff-ca9df7f2da6d1aba35009fa5756eedf8) so that by default it expects an RBAC enabled cluster. AKS clusters are not RBAC enabled and I believe the default configuration for minikube is also not RBAC enabled.

Try this command to install the NGINX ingress controller

```
helm install stable/nginx-ingress --set rbac.create=false --set rbac.createRole=false --set rbac.createClusterRole=false
```

**Comment by nguyenhuuloc304** [comment]
@neilpeterson I tried your command and it worked well. Thank you so much. My boss was very happy when I fixed this issue. 👍

**Comment by novaterata** [comment]
@neilpeterson helm 2.9.1 was released, when will AKS start using this version of helm?

**Comment by neilpeterson** [comment]
@novaterata - helm is not installed in an AKS cluster by default / nor is an AKS cluster bound to one version of helm. So, if you update the helm client locally, and then run `helm init --upgrade`, this should upgrade the tiller deployment to 2.9.1.

**Comment by novaterata** [comment]
OK, I still had to do the "workaround" with service account, so I thought
we were waiting for something to not have to do that. I guess I'm just
confused.

**Comment by neilpeterson** [comment]
@novaterata - can you share the output of `helm version`?

**Comment by novaterata** [comment]
@neilpeterson 
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

**Comment by novaterata** [comment]
I just tried removing the workaround of deleting tiller and specificying service account default and I still got the connection refused message

**Comment by AntonChernysh** [comment]
@bramvdklinkenberg I don't see this setting in tilled-deploy

**Comment by bramvdklinkenberg** [comment]
it's under spec.template.spec.automountServiceAccountToken (with a helm init on minikube and an aks cluster on azure)

**Comment by AntonChernysh** [comment]
I mean there's nothing like that, I'm "grep -ing".
Have you ever managed to create secondary ingress controller (nginx) in AKS? I'm having a weird issues here. I suspect new ingress controller can't access some services..

**Comment by bramvdklinkenberg** [comment]
@AntonChernysh haven't tried it yet

**Comment by tanzwud** [comment]
Remove tiller and service role if any. Apply service role https://docs.helm.sh/using_helm/#role-based-access-control. Init with correct service role.

**Comment by jnoller** [comment]
Closing issue as stale / resolved
