### ISSUE TITLE
[Question] Why does AzRBAC role "Azure Kubernetes Service Cluster Admin" allow you to run a command but not see its output?

### ISSUE THREAD

**Issue by alkerMSFT** [Azure/AKS#3462]
### Scenario + Problem
I have a cluster which I've configured with Azure RBAC enabled. I'm trying to build some cluster automations that leverage the AKS ARM [`RunCommand`](https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/run-command) API. This API works by returning HTTP 204 with a [`CommandResults`](https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/get-command-result) URI that can be polled to get results from the command execution.

My automation runs in the context of a service principle to which I've granted RBAC role 'Azure Kubernetes Service Cluster Admin'. This gives it permission to run a command, which is working correctly.

However, it seems like we've split permissions so that:
- `RunCommand` requires `Microsoft.ContainerService/managedClusters/runCommand/action`
- `CommandResults` requires `Microsoft.ContainerService/managedclusters/commandResults/read`

The role 'Azure Kubernetes Service Cluster Admin' doesn't grant the second permission. So, I'm in a position where I can submit a command through the service principle but get 403 when following the `CommandResults` URI that was returned.

### Questions
Couple questions:
1. Why does the RBAC role allow submitting the command but not reading the results? It feels like both should be granted in tandem.
2. I couldn't find any built-in role to achieve what I'm looking for. Am I stuck making a custom role to fully use the RunCommand API?

Edit to add: Granting 'Contributor' role to the service principle did make it work. But that's not a great solution; way too permissive.

Thanks!

**Comment by mloskot** [comment]
Why not convert this to a Discussions thread? It would be very helpful if those questions are addressed.

**Comment by haitch** [comment]
fixed, pending rollout.
