### ISSUE TITLE
Ingress not working in AKS version 1.24.6 due to health probe change and conflicting server snippet configuration

### ISSUE THREAD

**Issue by vijaykumarv7** [Azure/AKS#3467]
**Describe scenario**
I recently updated my AKS cluster to version 1.24.6 and noticed that my ingress has stopped working. Upon further investigation, I discovered that the health probe has changed from TCP to HTTP/HTTPS.

I added the healthz annotation to my ingress configuration, but it didn't resolve the issue. I also tried adding a location /healthz to allow all traffic, but this also had no effect.

After some more digging, I realized that the problem was with the server snippet in the ingress-nginx ConfigMap that only allowed traffic from Azure Front Door. Removing the server snippet resolved the issue, but I cannot remove it as it creates a security vulnerability.

Steps to Reproduce
Update AKS cluster to version 1.24.6
Observe that ingress is not working
Check health probe and realize it has changed from TCP to HTTP/HTTPS
Add healthz annotation to ingress configuration
Observe that ingress is still not working
Try adding location /healthz to allow all traffic
Observe that ingress is still not working

Expected Behavior
Ingress should be functioning properly after updating the AKS cluster and adding the healthz annotation.

Actual Behavior
Ingress is still not working and traffic is not being allowed through due to a conflicting server snippet configuration.

Environment
AKS version: 1.24.6

**Question**
Additional Context
Removing the server snippet in the ingress-nginx ConfigMap resolves the issue, but it creates a security vulnerability. Is there a way to resolve this issue without removing the server snippet?

**Comment by sabbour** [comment]
@vijaykumarv7 which version of ingress-nginx are you using and how was it installed?
Can you also share the snippet in question?
