### ISSUE TITLE
Issue while upgrading the azure aks cluster from 1.23.8 to 1.24.6 and getting error - CustomPrivateDNSZoneMissingPermissionError

### ISSUE THREAD

**Issue by bpraveenkumargoud** [Azure/AKS#3470]
**scenario**
I was trying to upgrade the AKS cluster using C#/Pulumi to upgrade the aks cluster version from 1.23.8 to 1.24.6.
Getting below error
![image](https://user-images.githubusercontent.com/105823103/217876510-7e82b007-24f7-4413-be40-cdbadb314712.png)

I have tried assigning PrivateDNSZonecontributor, contributor, Networkcontributor permissions for the aksmanaged identity. but no luck. 

**Question**
Did any one got above issues? any suggestions/ideas in resolving the issue is appreciated.

**Comment by miwithro** [comment]
@feiskyer

**Comment by feiskyer** [comment]
Could you follow the docs https://learn.microsoft.com/en-us/azure/aks/private-clusters#configure-private-dns-zone and assign the permissions?

> you need a user assigned identity or service principal with at least the [Private DNS Zone Contributor](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#dns-zone-contributor) and [Network Contributor](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#network-contributor) roles.
> If the private DNS zone is in a different subscription than the AKS cluster, you need to register the Azure provider Microsoft.ContainerServices in both subscriptions.

**Comment by feiskyer** [comment]
This is already answered.
