### ISSUE TITLE
[BUG] Kubelogin is not converting the config for azurecli in ubuntu v0.0.26

### ISSUE THREAD

**Issue by zheng-wang-hexad** [Azure/AKS#3477]
**Describe the bug**
Kubelogin is not able to convert the kubeconfig to azurecli format

**To Reproduce**
1. az login
2. az aks get-credentials -g "abc" -n "def"
3. kubelogin convert-kubeconfig -l azurecli

**Expected behavior**
the file should contain:
      - --login
      - azurecli
      command: kubelogin
      env: null
      provideClusterInfo: false

**Actual Config after running the command
- name: clusterUser_rc-a-aks-1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - --client-id
      - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - --tenant-id
      - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - --login
      - devicecode
      command: kubelogin
      env: null
      provideClusterInfo: false

**Environment (please complete the following information):**
 -  az version 2.0.81
 - kubelogin version 
git hash: v0.0.26/584497114d74eca24f55f078befb11d8955bb0ba
Go version: go1.19.5
Build time: 2023-02-09T03:16:12Z
Platform: linux/amd64

**Comment by CocoWang-wql** [comment]
@haitch can you pls help to check this issue~?

**Comment by weinong** [comment]
did you set $KUBECONFIG environment variable? try to unset that and try again?

**Comment by weinong** [comment]
didn't hear back from you. closing
