### ISSUE TITLE
Not able to upgrade aks cluster nodepool to 1.24.9  from azure cli from portal [BUG]

### ISSUE THREAD

**Issue by teocrispy91** [Azure/AKS#3485]
**Describe the bug**
Not able to upgrade aks nodepool from 1.24.6 to 1.24.9 from azure cli portal . My control Plane got upgraded. But as soon as i try to upgrade the nodepool i am getting the below mentioned error. I am able to upgrade the same with vscode azure cli without any issues.

**To Reproduce**
az aks upgrade --resource-group test --name testcluster --kubernetes-version 1.24.9 --control-plane-only
az aks nodepool upgrade --cluster-name testcluster --name testwin --resource-group test --kubernetes-version 1.24.9

Control plane upgrades sucessfully without any issues. but as soon as i run the second command to upgrade nodepool it fails with the below error
My azure cli version is 2.45.0
2. See error
Attribute error agent pool has no attribute kubernetes_version(screenshot attached)

**Expected behavior**
nodeppol get upgraded successfully

**Screenshots**
![testclust](https://user-images.githubusercontent.com/66721568/220038804-2268f67b-76ca-4b5c-959a-755d206f2a1d.png)

**Comment by carvido1** [comment]
Hello @teocrispy91.
Can you check the current nodepool k8s version?

```bash
az aks nodepool show --cluster-name testcluster --name testwin --resource-group test
```

Old clusters using nodepool without VMSS can get an upgrade using the command `az aks nodepool upgrade`.
If you have upgraded the controlplane only, maybe you can use the command without the option `--control-plane-only` to get the cluster upgraded, like:

```bash
az aks upgrade --resource-group test --name testcluster --kubernetes-version 1.24.9
```

Is it possible for you to try this ?

Best regards.

**Comment by teocrispy91** [comment]
@carvido1 az aks upgrade --resource-group test --name testcluster --kubernetes-version 1.24.9 --control-plane-only
az aks upgrade --resource-group test --name testcluster --kubernetes-version 1.24.9
Both these commands are working 
But why suddenly like one by one upgrade of nodepool stopped working with this command az aks nodepool upgrade --cluster-name testcluster --name testwin --resource-group test --kubernetes-version 1.24.9
I was trying to upgrade from 1.24.6 to 1.24.9

**Comment by carvido1** [comment]
Hello @teocrispy91 

As I mentioned there are two kind of AKS clusters when it comes to nodepools defined by the `vm-set-type` argument when calling the az client.
* availabilitySet: this option allows you to scale horizontally the nodes, but you won't be allowed to change the SKU or add extra nodepools to your AKS cluster 
* VMSS (virtual machine scale sets): with this nodepool type you can add extra system or user nodepool. This type comes with autoscaling options.

Which one are you running ? Can you send more info about the number of nodepools you have? Can you check if these nodepools have any application running on them with a selector and a podDisruptionBudget is preventing the cluster to get upgraded ? ... There are many factors that can lead the nodepool upgrade to fail, I think you need to provide more insights to get help.

In addition, as I'm not azure or microsoft employee but I have used AKS for some years, my recommendation is that you create a support ticket with them. Azure has basic support included on your subscription.

BR

**Comment by teocrispy91** [comment]
we are using the type vmss

**Comment by slzmruepp** [comment]
This is a duplicate see here [#25530](https://github.com/Azure/azure-cli/pull/25539) It is fixed but still in the dev branch of az-cli and not yet released.

**Comment by mruepp** [comment]
This can be closed. https://github.com/Azure/azure-cli/pull/25539 is merged. Please close this issue

**Comment by AllenWen-at-Azure** [comment]
Close the issue as confirmed in https://github.com/Azure/AKS/issues/3485#issuecomment-2329474061
