### ISSUE TITLE
[Feature]  Convert all clusters with non-AZ enabled control planes to be AZ enabled

### ISSUE THREAD

**Issue by seumasdunlop** [Azure/AKS#3493]
As discussed in #2432 and and [documented](https://learn.microsoft.com/en-us/azure/aks/availability-zones#create-an-aks-cluster-across-availability-zones), if a cluster is created without availability zones defined then the control plane will not be formed redundantly across AZs.  It is impossible to change this and impossible to view the current state which is problematic for old clusters where the history hasn't been documented.

The final comment in #2432 before it was closed states:
> we do have a roadmap item to convert all non-AZ enabled clusters to AZ enabled clusters for every region where multiple AZs are available

I can't find a public issue for this work so Azure support suggested creating one, hence this issue.

**Is your feature request related to a problem? Please describe.**
We have clusters that (probably) weren't created using AZs that we want to update so the control plane uses AZs.  Currently that means rebuilding the cluster which is a lot of work for us.  It would be great if it happened magically in the background.

**Describe the solution you'd like**
As described in #2432, "convert all non-AZ enabled clusters to AZ enabled clusters for every region where multiple AZs are available".

**Describe alternatives you've considered**
Rebuilding the clusters.

**Comment by steeling** [comment]
The work item in the [last comment](https://github.com/Azure/AKS/issues/2432#issuecomment-1061245709) was actually completed.  [Per the docs](https://learn.microsoft.com/en-us/azure/aks/availability-zones#create-an-aks-cluster-across-availability-zones):

> The availability zones that the managed control plane components are deployed into are not controlled by this parameter. They are automatically spread across all availability zones (if present) in the region during cluster deployment.

So as long as the region your cluster is in supports AZ's your control plane will be spread across AZ's. Hope that helps!
