### ISSUE TITLE
[BUG] Missing requests/limits for AKS core components on worker nodes

### ISSUE THREAD

**Issue by slawekww** [Azure/AKS#3496]
**Describe the bug**
Run https://github.com/Azure/kube-advisor on AKS 1.24.6
to verify CPU/Memory requests/limits set for k8s workloads.

The following components provided and maintain by AKS on **worker** nodes have no requests/limits set:
* calico-kube-controllers
* calico-node
* calico-typha
* cloud-node-manager
* csi-azuredisk-node
* csi-azurefile-node
* kube-proxy
* tigera-operator

**To Reproduce**
1. https://github.com/Azure/kube-advisor#running-in-a-kubernetes-cluster-with-rbac-enabled
2. See output on AKS cluster

**Expected behavior**
All AKS managed workloads on worker nodes should have limits/request set and have guidelines to update them by AKS administrators.

**Screenshots**
[kube-advisory.log](https://github.com/Azure/AKS/files/10847639/kube-advisory.log)

**Environment (please complete the following information):**
 -  CLI Version: 2.44.1
 - Kubernetes version: AKS 1.24.6
 - CLI Extension version: n/a
 - Browser: n/a

**Additional context**
Cost of worker node is under customers and it should be clear and precise way to control AKS managed workloads.

**Comment by marcindulak** [comment]
Discussed previously in https://github.com/Azure/AKS/issues/2125#issuecomment-1285092648

**Comment by slawekww** [comment]
@marcindulak Thanks! 
Discussion is about OOMKill for AKS core components.

Once they would have Guaranteed QoS class https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed
it would not be issue with OOMKill as they would requests=limits the expected resources.

AKS administrators should have possibility to update requests/limits for those AKS core components.
In case of avoiding OOMKill, use Guaranteed QoS class.
In case of cost optimization, set values which are acceptable by customers - we need to know minimum values for requests CPU/memory for AKS core components.
