### ISSUE TITLE
[BUG] Cannot change user-assigned MSI

### ISSUE THREAD

**Issue by alexadams-ms** [Azure/AKS#3498]
**Describe the bug**
We accidentally assigned the wrong User-Assigned MSI to a cluster. We are unable to change the MSI to the correct one.

**To Reproduce**
1. Create a user-assigned MSI.
2. Assign the User-Assigned MSI to an AKS cluster (`az aks update --resource-group myResourceGroup --name myCluster--enable-managed-identity --assign-identity myFirstMsiResourceId`)
3. See that the Cluster is now using the correct identity. 
```
  "identity": {
    "principalId": null,
    "tenantId": null,
    "type": "UserAssigned",
    "userAssignedIdentities": {
      "myFirstMsiResourceId": {
        "clientId": "clientIdOfMyFirstResourceId",
        "principalId": "principalIdOfMyFirstResourceId"
      }
    }
  },
```
4. Create another user-assigned MSI.
5. Attempt to change the MSI of the cluster to the second MSI. (`az aks update --resource-group myResourceGroup --name myCluster --enable-managed-identity --assign-identity mySeccondMsiResourceId`)
6. Notice that the cluster is still using the first MSI.
```
  "identity": {
    "principalId": null,
    "tenantId": null,
    "type": "UserAssigned",
    "userAssignedIdentities": {
      "myFirstMsiResourceId": {
        "clientId": "clientIdOfMyFirstResourceId",
        "principalId": "principalIdOfMyFirstResourceId"
      }
    }
  },
```

**Expected behavior**
Expected that the cluster will now be using the second Identity. 
If this is an intentional limitation, I would expect an error message of some kind ("I'm sorry Dave, I'm afraid I can't do that") rather than just failing silently.

**Screenshots**

**Environment (please complete the following information):**
 - azure-cli version 2.40
 - Kubernetes version 1.25.5

**Additional context**
We have tested this by including `--assign-kubelet-identity` flag with no effect. We have also tried removing `--enable-managed-identity` flag but that gives us an error.

**Comment by alexadams-ms** [comment]
For now, we found a workaround by switching to System-Assigned MSI, then switching back to User-Assigned MSI.
1. Switch to system-assigned MSI
`az aks update --resource-group myResourceGroup --name myCluster --enable-managed-identity `
2. Switch back to the desired User-Assigned MSI.
`az aks update --resource-group myResourceGroup --name myCluster --enable-managed-identity --assign-identity mySeccondMsiResourceId"`

**Comment by CocoWang-wql** [comment]
Thanks for the feedback. Currently, it's not supported for updating existing control plane identity. We hope to make it supported with CLI version 2.49.0.
