### ISSUE TITLE
[BUG] Portal rendering of cluster configuration for disableLocalAccounts is incorrect

### ISSUE THREAD

**Issue by wsmelton** [Azure/AKS#3499]
**Describe the bug**
Setting the `disableLocalAccounts` to false on an AKS Cluster when we have the AAD profile configured is still showing checked.

**To Reproduce**
1. Deploy an AKS cluster with below configuration included:

```bicep
aadProfile: {
      managed: true
      enableAzureRBAC: true
      tenantID: '00000000-0000-0000-0000-00000000000'
    }
    // AAD enabled, no local accounts allowed
    disableLocalAccounts: false
```

3. Not via the Portal that the `Kubernetes local accounts` is still checked
4. Export ARM template, see the disableLocalAccounts is set to false
5. Run `Get-AzAksCluster` and pull the same property observe set to false as well.

**Expected behavior**
Portal properly shows the configuration of the cluster

**Screenshots**

![image](https://user-images.githubusercontent.com/11204251/222229308-10d0e941-12f2-49ea-9bb2-d1df7fed1896.png)

![image](https://user-images.githubusercontent.com/11204251/222231105-903b9216-1483-43de-9de7-b9e640f9c18f.png)

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22]
 - Kubernetes version: **1.24.9**
 - CLI Extension version [e.g. 1.7.5] if applicable
 - Browser: **Edge (110.0.1587.57)**

**Additional context**

**Comment by sabbour** [comment]
@raghulmsft please take a look.

**Comment by wplam** [comment]
Hi Shawn, just want to make sure in the config screenshot you posted, in regard to your comment, when disableLocalAccounts is set to false, we expect local accounts to be allowed. It seems from your comment that you expect local accounts to not be allowed. Just want to clear up this misunderstanding in case that is the issue you are running into.

**Comment by wsmelton** [comment]
Okay, may be my mistake then.
