### ISSUE TITLE
[BUG] Changelog mentions you need JDK15 to run on AKS 1.25.x 

### ISSUE THREAD

**Issue by floriankoch** [Azure/AKS#3504]
**Describe the bug**
The Changelog https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2023-02-26
 says you need a least JDK15 - this is wrong - cgroupsv2 has been backported to openjdk 11.0.16 and  openjdk8u372

https://bugs.openjdk.org/browse/JDK-8283559?jql=project%20%3D%20JDK%20AND%20status%20in%20(Resolved%2C%20Closed)%20AND%20fixVersion%20%3D%2011.0.16%20ORDER%20BY%20created%20DESC

**Comment by floriankoch** [comment]
Can you please clarify this?

**Comment by saparicio** [comment]
In AKS release docs it's mentioned that cgroups v2 is available in JDK15 
![image](https://user-images.githubusercontent.com/1216001/229346928-d298c098-254f-4f3b-880d-18c6f1e3a912.png)

But this was backported to JDK 11.016 
![image](https://user-images.githubusercontent.com/1216001/229346973-6ccb10ab-cb55-4bd7-adbe-9d9c70e6eac8.png)

**Comment by floriankoch** [comment]
Can be closed
