### ISSUE TITLE
Workload Identity ClusterRole removed [BUG]

### ISSUE THREAD

**Issue by hbuckle** [Azure/AKS#3505]
**Describe the bug**

We have observed starting today that the `azure-wi-webhook-manager-role` ClusterRole, installed by the azure-workload-identity/workload-identity-webhook helm chart has disappeared from all of our UK South clusters.

v20230226 has been rolled out to UK South, is there anything in this release that could cause this?

We don't see the same issue on West Europe clusters.

We are installing workload identity ourselves using the helm chart (v0.15.0)

**To Reproduce**
1. Run command
  kubectl get ClusterRole/azure-wi-webhook-manager-role
2. See error
  Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "azure-wi-webhook-manager-role" not found

**Environment (please complete the following information):**
 - Kubernetes version [1.24.9]

**Comment by hbuckle** [comment]
We have reinstalled the helm chart for workload identity and that has re-created the ClusterRole, but we don't see any reason how it was removed in the first place.

**Comment by swang-cc** [comment]
Since EST 6PM all my eastus AKS have suffered the same issue.
clusterrolebinding got deleted for no reason - clusterrolebinding.rbac.authorization.k8s.io/azure-wi-webhook-manager-rolebinding

**Comment by hbuckle** [comment]
Looks like #3510 is the cause

**Comment by karataliu** [comment]
Thanks for reporting the issue.

AKS side is deploying the fix, ETA is ~1 day.

This issue will impact open source version of workload-identity.

Please reinstall workload-identity helm release or use [AKS integrated workload identity](https://aka.ms/aks/wi) as a fix.

**Comment by karataliu** [comment]
This is fixed, see more discussion here: fixed, see more discussion here: https://github.com/Azure/azure-workload-identity/issues/777
