### ISSUE TITLE
How to run NCCL collective tests efficiently on NDv4 via AKS?

### ISSUE THREAD

**Issue by garvct** [Azure/AKS#3507]
**Describe scenario**
NCCL collective communication is critical for some large transformer based deep learning training modules running on NDv4 (A100).
I have been successful running NCCL allreduce test on 2 NDv4 VM's (16 A100) on AKS, the pods see all 8 IB devices, 8 A100 GPU's and RDMA Sharp plugin is found  but the NCCL allreduce performance is terrible (~4 GB/s, should be ~186 GB/s).
If I run the identical container on SLURM+enroot+pyxis, I can get 186 GB/s on 2 NDv4 VM's. The HOST OS used in the SLURM+enroot_pyxis is ubunt-hpc 20.04, in AKS I am using the Ubuntu host OS image (I believe 18.04).

The primary difference I see causing the slow NCCL allreduce performance in AKS is GPU direct RDMA (GDRDMA) is not enabled in the AKS run, but is enabled in the SLURM+enroot_pyxis run.

I can see the nvidia_peermem kernel modules load in my SLURM+enroot+pyxis environment, but they do not exist in the AKS ubuntu host OS?

hpcadmin@nslm27u2004-hpc-pg0-1:~/aks-nvidia-gpu$ lsmod | grep peer
nvidia_peermem         16384  0
ib_core               434176  9 rdma_cm,ib_ipoib,nvidia_peermem,iw_cm,ib_umad,rdma_ucm,ib_uverbs,mlx5_ib,ib_cm
nvidia              39137280  284 nvidia_uvm,nvidia_peermem,gdrdrv,nvidia_modeset

**Question**
How can I enable nvidia_peermem kernel module on AKS ubuntu host OS?
Are there any examples of running NCCL allreduce optimally on multi-node NDv4 on AKS?

**Comment by MartinForReal** [comment]
@garvct please refer to https://techcommunity.microsoft.com/t5/azure-high-performance-computing/deploy-ndm-v4-a100-kubernetes-cluster/ba-p/3838871
