### ISSUE TITLE
OMS Agent image pull Error.

### ISSUE THREAD

**Issue by YvonneArnoldus** [Azure/AKS#351]
Hi,

I followed the steps in https://docs.microsoft.com/en-us/azure/monitoring/monitoring-container-health to install the container health preview.

The deploy of the pod went without a problem but pod is not starting cause of the flowing error:

`Events:
  Type     Reason                 Age                From                               Message
  ----     ------                 ----               ----                               -------
  Normal   SuccessfulMountVolume  38m                kubelet, aks-nodepool1-19586064-0  MountVolume.SetUp succeeded for volume "host-log"
  Normal   SuccessfulMountVolume  38m                kubelet, aks-nodepool1-19586064-0  MountVolume.SetUp succeeded for volume "container-hostname"
  Normal   SuccessfulMountVolume  38m                kubelet, aks-nodepool1-19586064-0  MountVolume.SetUp succeeded for volume "containerlog-path"
  Normal   SuccessfulMountVolume  38m                kubelet, aks-nodepool1-19586064-0  MountVolume.SetUp succeeded for volume "docker-sock"
  Normal   SuccessfulMountVolume  38m                kubelet, aks-nodepool1-19586064-0  MountVolume.SetUp succeeded for volume "omsagent-secret"
  Normal   SuccessfulMountVolume  38m                kubelet, aks-nodepool1-19586064-0  MountVolume.SetUp succeeded for volume "default-token-mbkwg"
  Normal   Pulling                29m (x2 over 38m)  kubelet, aks-nodepool1-19586064-0  pulling image "dockerio.azureedge.net/microsoft/oms:ciprod04202018"
  Warning  Failed                 19m (x2 over 33m)  kubelet, aks-nodepool1-19586064-0  Failed to pull image "dockerio.azureedge.net/microsoft/oms:ciprod04202018": rpc error: code = Canceled desc = context canceled
  Warning  Failed                 19m (x2 over 33m)  kubelet, aks-nodepool1-19586064-0  Error: ErrImagePull`

**Comment by slack** [comment]
Looks like the VM was unable to pull the container image in time. Related to #245

**Comment by slack** [comment]
Going to close this issue in favor of the issue tracking image pull timeouts.
