### ISSUE TITLE
[BUG] AKS workload identity clean up all clusterrole/clusterrolebindings

### ISSUE THREAD

**Issue by karataliu** [Azure/AKS#3510]
**Describe the bug**
Install script will uninstall all clusterrole/clusterrolebindings

https://github.com/Azure/azure-workload-identity/issues/777

**To Reproduce**
Install opensource workload identity

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22]
 - Kubernetes version [e.g. 1.24.3]
 - CLI Extension version [e.g. 1.7.5] if applicable
 - Browser [e.g. chrome, safari] is applicable

**Additional context**

**Comment by karataliu** [comment]
AKS side is deploying the fix, ETA is ~1 day.

This issue will impact open source version of workload-identity.

Please reinstall workload-identity helm release or use [AKS integrated workload identity](https://aka.ms/aks/wi) as a fix.

**Comment by hbuckle** [comment]
@karataliu - does the cleanup script run more than once? We have seen the ClusterRole disappear again after re-installing the helm chart.

**Comment by hbuckle** [comment]
@karataliu - can you confirm was this introduced in v20230226? Has the rollout of that release to other regions been paused?

**Comment by karataliu** [comment]
@hbuckle 

1. cleanup script will trigger if there is an update to cluster.
2. introduced in v20230226, all ongoing rollout includes the fix now.

**Comment by karataliu** [comment]
fixed, see more discussion here: https://github.com/Azure/azure-workload-identity/issues/777
