### ISSUE TITLE
1.27 version

### ISSUE THREAD

**Issue by kaarthis** [Azure/AKS#3518]
K8s version 1.27 preview just after the upstream launch.

**Comment by EraYaN** [comment]
This is not actually released yet even tough the documentation implies it should have been released in May.

**Comment by kaarthis** [comment]
Corrected doc as we released it this week

**Comment by slawekww** [comment]
When GA for AKS 1.27 is planned?

**Comment by EvertonSA** [comment]
will 1.27 be GA by end of July?

**Comment by stevehipwell** [comment]
The CLI suggests it's already GA but we're getting API errors due to it still being in preview and the docs are as vague and useless as ever.

`az aks get-versions --location eastus --output table`

**Comment by EvertonSA** [comment]
help aks, I need to plan

**Comment by EvertonSA** [comment]
![image](https://github.com/Azure/AKS/assets/30481051/95877f93-648a-4bc7-b821-74ad577ded3c)

**Comment by stevehipwell** [comment]
I'm still seeing v1.27 as preview in the UI for `westeurope`, the CLI doesn't flag it as preview.

**Comment by jthin** [comment]
@EvertonSA You can follow v1.27 status with the [AKS release tracker](https://releases.aks.azure.com/webpage/index.html#tabeuro).

From the Azure portal, I can see **East US** and **West Central US** for AKS 1.27 GA. UK South seems to have v20230730 release but I still see the *(preview)* suffix.

![image](https://github.com/Azure/AKS/assets/13431974/e3077647-0c5b-46f0-ae15-552decdf8f68)

**Comment by abubinski** [comment]
@kaarthis can I close this?
