### ISSUE TITLE
Delete specific nodes via ARM call

### ISSUE THREAD

**Issue by kaarthis** [Azure/AKS#3520]
Node API to delete specific nodes that are unhealthy by customers.

**Comment by alvinli222** [comment]
This feature is available with the latest preview CLI. Docs update soon.

`az aks nodepool delete-machines --resource-group MyResourceGroup --cluster-name myAKSCluster --name agentpool --machine-names [vmName1] [vmName2], ... [vmNameN]`

**Comment by alvinli222** [comment]
Hi all this feature is now generally available. Please note in the GA version, there is no drain on the nodes and it simply deletes the underlying VM directly.
