### ISSUE TITLE
[Question] Confirmation about the CIDR ranges when using Azure CNI

### ISSUE THREAD

**Issue by Linhagupta** [Azure/AKS#3527]
**Describe scenario**
We are trying to setup multiple AKS clusters across different VNETs using Azure CNI. Following the doc here https://learn.microsoft.com/en-us/azure/aks/configure-azure-cni. There are 3 different ranges that we are talking about -
1. Virtual network subnet CIDR
2. Kubernetes service CIDR
3. Docker CIDR
The recommendation says to ensure there's no overlap of address space in the network. 

Trying to get more clarity around the scope and applicability of these CIDR ranges, seems like this 
1. Subnet CIDR - Pod IPs & Node IPs - Traffic originating from PODs will see source address as POD IP within the same vnet else Node IP across the vnet. Traffic to the POD IPs and Node IPs are allowed from the peered vnets.
2. Service CIDR - Cluster IPs, they are limited to just the AKS cluster subnet. CIDR range can be reused across different AKS clusters. 
3. Docker CIDR - essentially to support Docker Build, CIDR range can be reused across different AKS clusters

Details around our deployment model -
1. We are setting up different AKS clusters, which are peered with different vnets. Like below
       AKS_vnet_A <=> HOST_SERVICE_vnet_A
       AKS_vnet_B <=> HOST_SERVICE_vnet_B
       ..
2. There's no communication need between the AKS clusters. 
3. We assign external-IPs (got within the AKS Subnet) for all the services running within the AKS cluster to allow peered inbound requests.
4. Our network does not have any overlap with the default CIDR that are used by Service CIDR and Docker CIDR

**Question**
Essentially ensuring just the AKS vnet subnet CIDR is unique and does not overlap across the network must suffice in this scenario Or Should we bother about ensuring the uniqueness of Service CIDR range & Docker CIDR as well (we plan to keep the later two default)?

**Comment by Linhagupta** [comment]
With Docker CIDR getting officially deprecated, we are just left with K8s Service CIDR for clarification here.

**Comment by bh-garo-yeriazarian** [comment]
Also interested in getting feedback on the CIDR ranges and improve the documentation.
