### ISSUE TITLE
[Feature] Support for changing scheduler configuration 

### ISSUE THREAD

**Issue by EppO** [Azure/AKS#3532]
**Is your feature request related to a problem? Please describe.**
When trying to trigger down scaling of under utilized nodes, default kubernetes scheduler strategy `LeastAllocated` makes it difficult to achieve. 

**Describe the solution you'd like**
Allow the AKS admin to change the `KubeSchedulerConfiguration`'s default settings like described here: https://kubernetes.io/docs/reference/scheduling/config/ 

**Describe alternatives you've considered**
I tried to use [descheduler](https://github.com/kubernetes-sigs/descheduler) but it fell short for the same reason. 

**Additional context**
The `MostAllocated` strategy scores the nodes based on the utilization of resources, favoring the ones with higher allocation, maximizing usage of busiest nodes allowing the autoscaler to downscale under utilized nodes.
The `RequestedToCapacityRatio` strategy allows the users to specify the resources along with weights for each resource to score nodes based on the request to capacity ratio. This allows users to bin pack extended resources by using appropriate parameters to improve the utilization of scarce resources in large clusters. It favors nodes according to a configured function of the allocated resources

**Comment by EppO** [comment]
> @EppO was there any workaround for this feature?

No, there is still no way to configure the scheduler config in AKS. I'm more interested about Karpenter support #2712 which provides better scheduling/autoprovisioning capabilities though.

**Comment by hydracz** [comment]
we are facing the same issue there, when using cluster autoscaler, the default one doesn't works very well because new coming pod are get allocated to all the node with less utilization , this cause a waste of resource. 

can we expect to support add support for `MostAllocated` in some newer release? other wise we have to use a DIY kubernetes on Azure VM instead

**Comment by sravanakinapally** [comment]
Are there any plans to expose `KubeSchedulerConfiguration` changes or the ability to modify the AKS cluster?

**Comment by varora24** [comment]
We have added support for scheduler configuration to our roadmap as planned/committed.
Linking the open feature and closing this issue - https://github.com/Azure/AKS/issues/4203
