### ISSUE TITLE
HPAScaleToZero - Reply in Locked Thread

### ISSUE THREAD

**Issue by antoinne85** [Azure/AKS#3533]
@olsenme I’m replying here because the thread where you asked is currently locked. This is in reference to #1240. (Obviously feel free to unlock that thread and ask me to move this or to pick up the conversation here, really whatever works for you.)

Yes. I haven’t been following the discourse on this feature lately in the official K8S channels, as it’s been taking a really long time for the feature to make its way through the K8S contribution process.

We would _love_ to have scale to zero in our clusters and have been delaying adding Keda to the cluster, mostly because we’ve had more important needs to address, but partly because we secretly hoped the “official” way would eventually make its way through the dev cycle and land.

So, short story, yes. If this was available we’d take advantage of it for sure.

**Comment by machine424** [comment]
Hello,

If you don't/cannot wait for it to go GA, I developed https://github.com/machine424/kube-hpa-scale-to-zero
