### ISSUE TITLE
[Feedback] Release 2023-03-05 - confusing statement on token credential

### ISSUE THREAD

**Issue by wsmelton** [Azure/AKS#3540]
**Describe your scenario**
Please review [release 2023-03-05](https://github.com/Azure/AKS/releases/tag/2023-03-05) more closely and provide further detail or background on behavior changes.

**Feedback**
> the token credential will gradually be rotated. it shall not incur any impact since kubeconfig has the client certificate. should you see any issue, call az aks get-credentials again.

What is this supposed to be referring to under Behavior Changes section?

- Token credential for who/what?
- What drives this change that may cause issues for us? (e.g., when upgrading the cluster, rotating the certificate, 😖 😕 )
- Is there an issue that goes into more detail on why this behavior change came about?
- What version(s) of Kubernetes or kubectl will be affected?

**Comment by andyzhangx** [comment]
@miwithro
