### ISSUE TITLE
Internal load balancer is not honoring label exclude-from-external-load-balancers=true

### ISSUE THREAD

**Issue by egzonzeneli** [Azure/AKS#3545]
**What happened**:
Updated node pools with label `node.kubernetes.io/exclude-from-external-load-balancers=true`, i still can see all VMSS (node pools) at backend pools of LB. 

**What you expected to happen**:
The backend pool of LB should not list node pools (VMSS) that are tagged with label `exclude-from-external-load-balancers=true`

**How to reproduce it (as minimally and precisely as possible)**:
- Create an aks cluster with two node pools. 
- Create an ingress controller with services that has annotations `service.beta.kubernetes.io/azure-load-balancer-internal: "true"`
- Update nodepool by adding label 
```cli
az aks nodepool update \
    --resource-group myResourceGroup \
    --cluster-name myAKSCluster \
    --name labelnp \
    --labels node.kubernetes.io/exclude-from-external-load-balancers=true \
    --no-wait
```

**Environment**:
- Kubernetes version (use `kubectl version`):
1.24.6
- Size of cluster (how many worker nodes are in the cluster?) 40

**Comment by egzonzeneli** [comment]
I just applied to another cluster it seems is working, but when i go to azure portal, load balancers `kubernetes-internal` and then to  backend pools, all the node pools that i've updated with label `node.kubernetes.io/exclude-from-external-load-balancers=true` are showed with a warning message: `Backend pool 'kubernetes' was added to Virtual machine scale set '{node-pool-name}-vmss'. Upgrade all the instances of '{node-pool-name}-vmss' for this change to work`. 

I went ahead and upgraded to the last model then the warning has been removed but guess what is showing under backend pool again ... returning to the first issue :S

**Comment by mykolaichuk** [comment]
We have a similar issue. We have a standard Load Balancer and 3 node pools behind it. 2 node pools have exclude-from-external-load-balancers=true label, however it seems like all node pools are quired by LB health probes.
![image](https://user-images.githubusercontent.com/7926159/227128216-0fb7409a-cc39-4771-a4cd-bb4b47d64491.png)
![image](https://user-images.githubusercontent.com/7926159/227129414-c57456df-c176-442d-ba09-42385bf63b77.png)

We have the same setup on other clusters, but this label is respected there. Why does it work like that?

**Comment by kingli-crypto** [comment]
I got in touch with MS, in response they updated document to say this is not supported in AKS.

https://github.com/kubernetes-sigs/cloud-provider-azure/pull/3971

**Comment by feiskyer** [comment]
document published https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/#limitations.
