### ISSUE TITLE
[Question]  Is there a way to prevent AKS Node Pool NSGs from being created?

### ISSUE THREAD

**Issue by jim-mclean** [Azure/AKS#3547]
**Describe scenario**

We're deploying AKS with a customer provided VNet that has some very specific NSG configuration.  Even though we've got the subnet on lock AKS still creates a Network Security Group and assigns it to the Node Pool NICs (i.e. NSG named aks-agentpool-21885213-nsg).

This is posing an issue for our organization as we have very specific requirements re: NSG configurations and without the ability to either tailor the security rules on this generated NSG or disable it entirely we're running into Azure Policy violations.

**Question**

Is there a way to prevent AKS Node Pool NSGs from being created?  Failing that is there a way to tailor the security rules created?  We'd need full control to setup those rules as stated we have very specific requirements that enforced via Azure Policy.

**Comment by jim-mclean** [comment]
This there more detail I could provide?  Doesn't seem like a support issue so I'm not sure how to proceed otherwise.

**Comment by PixelRobots** [comment]
Hello,

It might be good to look at https://learn.microsoft.com/en-us/azure/aks/use-node-public-ips#allow-host-port-connections-and-add-node-pools-to-application-security-groups-preview

I believe it might fit your use case.

Let me know how you get on.

Thanks

Richard

**Comment by AlluNanda** [comment]
@Jim Mclean , If you find answers, please share your learning. we have the same issue now.
