### ISSUE TITLE
Timed out waiting for external-attacher of disk.csi.azure.com CSI driver to attach volume 

### ISSUE THREAD

**Issue by vince-duloup** [Azure/AKS#3550]
**Describe the bug**
Persistent volumes could not be mounted with the following symptomatic events in the pods/nodes. This issue affected 3 clusters in one region (east-us) in a certain period of time ~(2023-03-16T04:35:06Z - 2023- 03-16T04:56:07Z)

**Cluster 1**
` lastTimestamp: "2023-03-16T04:35:06Z"
  message: 'AttachVolume.Attach failed for volume "pvc-1fa755a6-0144-4ee0-8cec-b2cbf46c4a0d"
	: timed out waiting for external-attacher of disk.csi.azure.com CSI driver to
	attach volume /subscriptions/***/resourceGroups/mc_k8s_night-test-linkerd-aks_eastus/providers/Microsoft.Compute/disks/pvc-1fa755a6-0144-4ee0-8cec-b2cbf46c4a0d'
`

**Cluster 2**
`  lastTimestamp: "2023-03-16T04:43:53Z"
  message: 'AttachVolume.Attach failed for volume "pvc-88192d0c-6a49-4fce-b667-794e0fdb0cd6"
	: timed out waiting for external-attacher of disk.csi.azure.com CSI driver to
	attach volume /subscriptions/***/resourceGroups/mc_k8s_night-test-regular-aks_eastus/providers/Microsoft.Compute/disks/pvc-88192d0c-6a49-4fce-b667-794e0fdb0cd6'
`

` lastTimestamp: "2023-03-16T04:43:56Z"
  message: 'AttachVolume.Attach failed for volume "pvc-f6f88a42-2f39-4fe6-b2e2-9b4008aedeed"
	: timed out waiting for external-attacher of disk.csi.azure.com CSI driver to
	attach volume /subscriptions/***/resourceGroups/mc_k8s_night-test-regular-aks_eastus/providers/Microsoft.Compute/disks/pvc-f6f88a42-2f39-4fe6-b2e2-9b4008aedeed'
`

`  lastTimestamp: "2023-03-16T04:43:06Z"
  message: 'AttachVolume.Attach failed for volume "pvc-08b8e882-5032-4c65-9305-0fd0fcca9aea"
	: timed out waiting for external-attacher of disk.csi.azure.com CSI driver to
	attach volume /subscriptions/***/resourceGroups/mc_k8s_night-test-regular-
`

`  lastTimestamp: "2023-03-16T04:43:06Z"
  message: 'AttachVolume.Attach failed for volume "pvc-8989c8ad-9900-445d-aabb-59e52be446d2"
	: timed out waiting for external-attacher of disk.csi.azure.com CSI driver to
	attach volume /subscriptions/***/resourceGroups/mc_k8s_night-test-regular-aks_eastus/providers/Microsoft.Compute/disks/pvc-8989c8ad-9900-445d-aabb-59e52be446d2'
`

**Cluster 3**
`  lastTimestamp: "2023-03-16T04:54:07Z"
  message: 'MountVolume.MountDevice failed for volume "pvc-c8de4ca0-01ed-4203-91a0-9a117e7f8730"
	: rpc error: code = DeadlineExceeded desc = context deadline exceeded'
`

` lastTimestamp: "2023-03-16T04:55:56Z"
  message: 'MountVolume.MountDevice failed for volume "pvc-1287aff8-0999-4d0c-872f-8cede5a39c17"
	: rpc error: code = DeadlineExceeded desc = context deadline exceeded'
`

`  lastTimestamp: "2023-03-16T04:54:08Z"
  message: 'MountVolume.MountDevice failed for volume "pvc-0c77e63e-1eef-4b8d-a4b7-97bc9da77cdd"
	: rpc error: code = DeadlineExceeded desc = context deadline exceeded'
`

` lastTimestamp: "2023-03-16T04:56:07Z"
  message: 'MountVolume.MountDevice failed for volume "pvc-75db01bc-d17a-4cac-96c9-02db05ff4063"
	: rpc error: code = DeadlineExceeded desc = context deadline exceeded'
`

**To Reproduce**
We cannot reproduce this issue, as it just seems to happen randomly in our clusters. Our test clusters are provisioned every night, ~1-2 times per week we face issues like this.

**Expected behavior**
All volumes mount as expected, and pods spin up correctly.

**Environment (please complete the following information):**
Size of cluster (how many worker nodes are in the cluster?): 3

**nodeInfo:**
```
  	architecture: amd64
  	bootID: 6e8af6d4-2839-4701-85f6-9c5939f39a8c
  	containerRuntimeVersion: containerd://1.6.17+azure-1
  	kernelVersion: 5.4.0-1103-azure
  	kubeProxyVersion: v1.24.9
  	kubeletVersion: v1.24.9
  	machineID: 3d141534692e468ca0da40bca6ccfaff
  	operatingSystem: linux
  	osImage: Ubuntu 18.04.6 LTS
  	systemUUID: 2fa7ab2e-1bc5-4f01-9ca3-26ba80a28469

```
**storage class:**

```
apiVersion: v1
items:
- allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
	creationTimestamp: "2023-03-16T04:08:08Z"
	labels:
  	addonmanager.kubernetes.io/mode: EnsureExists
  	kubernetes.io/cluster-service: "true"
	name: tests-csi
	resourceVersion: "1357"
	uid: d548bcf3-0dbc-4cbd-b929-5440b363bb0c
  parameters:
	skuname: Premium_LRS
  provisioner: disk.csi.azure.com
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
```

**Comment by andyzhangx** [comment]
ok, thanks for the confirm.
