### ISSUE TITLE
[Feature] Support setting seccompDefault

### ISSUE THREAD

**Issue by jemag** [Azure/AKS#3552]
**Is your feature request related to a problem? Please describe.**
I would like to be able to change the default seccomp profile from `Unconfined` to `RuntimeDefault`

**Describe the solution you'd like**
Allow setting `seccompDefault`, see https://kubernetes.io/blog/2021/08/25/seccomp-default/#seccompdefault-to-the-rescue

**Describe alternatives you've considered**
Set it manually for every workload

**Comment by james-callahan** [comment]
FYI the feature flag should be on by default in Kubernetes 1.27. https://github.com/kubernetes/enhancements/issues/2413

**Comment by allyford** [comment]
See #3722
Closing as duplicate
