### ISSUE TITLE
Controller stopped responding, many etcd database space errors

### ISSUE THREAD

**Issue by murraypete** [Azure/AKS#356]
We just had a previously happy West Europe 1.9.2 cluster controller stop responding to calls - literally working fine, then not. Looking in the logs seems like etcd has overrun its storage quota on all nodes, the following message was logged a few hundred times immediately before/after comms were lost:
 
```
etcdserver:mvcc:database space exceeded
```
Could be a red herring due to the controller failing, though I see no other examples going back a week or so - just from when the issue started today.

Connections to the controller hostname get through TLS handshake then hang. Pods aren't able to communicate with the controller internally. Seems to be well and truly down.

Support ticket raised, will update with findings as/when they arrive. Anyone seen similar on AKS previously?

**Comment by markrendle** [comment]
I've just heard from one of my customers who has run into this problem, meaning their cluster is currently inoperable and their only resort is Azure Support, with a 24-hour turnaround.

According to the `etcd` docs, the space either needs compacting manually, or `etcd` needs to be started with the `--auto-compaction` flag.

It would be useful to know whether this is an anomalous issue in the West Europe DC, or a systemic issue with AKS generally in its current form.

**Comment by ir-mw** [comment]
We are suddenly facing the same issue on an AKS cluster version 1.9.6 in Azure region west-europe. Cluster had been running fine for about a month before. Support ticket raised.

**Comment by aamuz** [comment]
We are having the same issue in West Europe. Any updates? Is support ticket the only option here?

**Comment by jnoller** [comment]
This has been resolved, closing as stale.
