### ISSUE TITLE
[BUG] Azure Kubernetes Service (AKS) Key Management Service (KMS) etcd encryption creates failed cluster.

### ISSUE THREAD

**Issue by ameddin73** [Azure/AKS#3575]
**Describe the bug**
When creating an AKS cluster with KMS etcd encryption as per [this documentation](https://learn.microsoft.com/en-us/azure/aks/use-kms-etcd-encryption), the following error is encountered:

```shell
Code="AzureKeyVaultKmsValidateIdentityPermissionCustomerError" Message="The identity does not have keys encrypt/decrypt permission on key vault "<My Key Vault URL>"
```

**To Reproduce**
Clone and follow the README in this repository: https://github.com/ameddin73/aks-cmk-repro.

**Expected behavior**
AKS cluster should be successfully created, and Terraform should finish with: 
```shell
Apply complete! Resources: 11 added, 0 changed, 0 destroyed.
```
**Screenshots**
![Screenshot 2023-03-29 at 10 22 52 AM](https://user-images.githubusercontent.com/6893820/228618641-2a1b5ce8-f71e-4b7a-9dd9-9dd3e7e8e341.png)

**Environment (please complete the following information):**
 -  CLI Version `2.46.0`
 - Kubernetes version `1.24.9`
 - Terraform Version `~>1.3.9`
 - Azure Terraform Provider Version `3.41.0`

**Additional context**
Related issue: https://github.com/MicrosoftDocs/azure-docs/issues/98954.

**Comment by prdev89** [comment]
+1

**Comment by bessalahAmar** [comment]
Can you please try again with a key as bellow ( with type RSA and with the listed  key_opts  ) :

```
resource "azurerm_key_vault_key" "repro_cluster_etcd" {
  name         = "${var.prefix}-cmk-etcd"
  key_vault_id = azurerm_key_vault.repro_cluster_cmk.id
  key_type     = "RSA"
  key_size     = 2048
  key_opts = [
    "sign",
    "verify",
    "encrypt",
    "decrypt",
    "wrapKey",
    "unwrapKey"
  ]
}
```

I believe the root cause of your issue was due to not adding the encrypt,decrypt operation on the key.

**Comment by nathanblair** [comment]
Is this to say that Azure K8s KMS does not support EC-type keys? I've been looking for documentation to support one way or the other but have not found any.

**Comment by ameddin73** [comment]
This seems to have been resolved.

**Comment by bessalahAmar** [comment]
@nathanblair ,
the issue was not related to the type of key, it was due to the missing encrypt/decrypt key_opts

**Comment by nathanblair** [comment]
There is a failure in assigning those key-opts with an EC key, though.

I had to start on another endeavor but I will try to get back with the error message it gives when following the documentation but using an EC key instead of an RSA one.
