### ISSUE TITLE
[Question] Can you comment on 1.26 GA availability?

### ISSUE THREAD

**Issue by yuvallevy2** [Azure/AKS#3587]
https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli
I browsed into the UI and saw 1.26 still marked as preview. What is the updated ETA?

Thanks in advance

**Comment by misterjoshua** [comment]
I'm looking for the same. I'd be happy enough to hear whether or not 1.26 will be coming this month.

FYI #3517 appears to be tracking 1.26, and that issue seems to be represented in the public roadmap here: https://github.com/Azure/AKS/projects/1#card-88407027

**Comment by yuvallevy2** [comment]
Ok, document was updated to indicate April, I guess this answers the q, closing
