### ISSUE TITLE
[Question] Live Resize Persistent Volume of StatefulSets

### ISSUE THREAD

**Issue by PowerSurj** [Azure/AKS#3589]
**Describe the bug**
Live Resize Persistent Volume of StatefulSets

**To Reproduce**
1. Helm Deploy a release with StatefulSet with the PVC size of 4Gb
2. Helm Upgrade a release with increased PVC size to 8Gb

During upgrade receiving an error:
```
##[error]Error: UPGRADE FAILED: cannot patch "my-release" with kind StatefulSet: StatefulSet.apps "my-release" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

Persistent Volume Live Resize works if i upgrade PVC API object directly.

**Expected behavior**
Since AKS now supports Live resize of the Persistent Volumes.
https://azure.microsoft.com/en-us/updates/ga-online-live-resize-of-persistent-volumes/
I'd like to see PVC storage size upgrades to be supported in StatefulSets.

**Environment (please complete the following information):**
 - Kubernetes version 1.25.5

**Comment by andyzhangx** [comment]
@PowerSurj per the error msg, that's a limitation of statefulset upgrade:
```
##[error]Error: UPGRADE FAILED: cannot patch "my-release" with kind StatefulSet: StatefulSet.apps "my-release" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

**Comment by PowerSurj** [comment]
> @PowerSurj per the error msg, that's a limitation of statefulset upgrade:
> 
> ```
> ##[error]Error: UPGRADE FAILED: cannot patch "my-release" with kind StatefulSet: StatefulSet.apps "my-release" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
> ```

and would it be a gross anti-pattern for Azure to tweak their Statefulsets to operate slightly differently, allowing them to benefit from platform capabilities?

**Comment by andyzhangx** [comment]
@PowerSurj you could resize statefulset pvc by following command:

```
kubectl patch pvc pvc-azuredisk --type merge --patch '{"spec": {"resources": {"requests": {"storage": "8Gi"}}}}'
```

https://learn.microsoft.com/en-us/azure/aks/azure-disk-csi#resize-a-persistent-volume-without-downtime

that's a limitation of k8s statefulset, not AKS issue.
