### ISSUE TITLE
[Question] Can we upgrade a node pool to a snapshot with a previous node image version (rollback os image)?

### ISSUE THREAD

**Issue by ericsuhong** [Azure/AKS#3595]
This AKS [documentation](https://learn.microsoft.com/en-us/azure/aks/node-pool-snapshot#upgrading-a-node-pool-to-a-snapshot) says that you can only upgrade a node pool to a snapshot only when K8s version and node image version are **more recent**.

However, I was able to run **az aks nodepool upgrade --snapshot-id** command to roll back to a previous node-image version from 202303.22.0 to 202303.06.0:

Before nodepool output:
````
{
"creationData": null
"nodeImageVersion": "AKSCBLMariner-V2gen2-202303.22.0",
}
````

After nodepool output:
````
{
"creationData": {
  "sourceResourceId": [resourceId of snapshot that contains pervious os image version]
}
"nodeImageVersion": "AKSCBLMariner-V2gen2-202303.06.0"
}
````

My question is, is this expected that I can use **az aks nodepool upgrade --snapshot-id** command to roll back node os image?

We are currently debating whether we should rely on this command for implementing OS roll back feature, so a clarification from AKS team is critical.

**Comment by pavneeta** [comment]
@ericsuhong  is your goal to rollback to a specific version of the node image or always to the previous version only? Also, why do you wish to rollback in the first place?

**Comment by ericsuhong** [comment]
@pavneeta @kaarthis 

1. Our goal is to have an ability to rollback to the previous version (which is supposed to be the last known good version). However, it would be ideal if AKS supports a generic solution of allowing customers to specify exactly which node image version they want to run node pools with. It would solve other related issue where nodepools can be created with different OS versions depending on the timing of creation and OS release: https://github.com/Azure/AKS/issues/3419

2. All platform level upgrade must have a roll-back capability because you cannot 100% guarantee that new images will always be correct. Some issues are discovered few weeks after the release, and we wait until AKS to fix the issue, release hotfix image, and rollout node pool changes. Our organization has a very strict reliability requirement, and the biggest problem right now is that there is simply NO way to roll back OS image upgrades because AKS always pin down to the latest OS version.

**Comment by zioproto** [comment]
@palma21 ☝️

**Comment by zioproto** [comment]
Related feature request: 

Specify Node Image Version: https://github.com/Azure/AKS/issues/3151

**Comment by ericsuhong** [comment]
@zioproto Any update on this topic?

**Comment by zioproto** [comment]
@ericsuhong from the docs:
> You can upgrade a node pool to a snapshot configuration so long as the snapshot kubernetes version and node image version are more recent than the versions in the current node pool.

https://learn.microsoft.com/en-us/azure/aks/node-pool-snapshot

**Comment by ericsuhong** [comment]
@zioproto Yes, but that requires us to create snapshot for every OS updates that we perform. From technical perspective, I can't easily understand why AKS doesn't provide a command line to create a nodepool from previous OS SKUs.

**Comment by zioproto** [comment]
> @zioproto Yes, but that requires us to create snapshot for every OS updates that we perform. From technical perspective, I can't easily understand why AKS doesn't provide a command line to create a nodepool from previous OS SKUs.

Please comment on this issue: https://github.com/Azure/AKS/issues/3419
If I understand correctly that one is the feature you are looking for.

**Comment by ericsuhong** [comment]
No, the request is related but a little different. I am asking AKS team whether it is possible to specify previous OS SKU version as part of **az aks nodepool add** operation.

**Comment by zioproto** [comment]
> is exactly what we are looking for.

Please add a comment to https://github.com/Azure/AKS/issues/3419 to show your interest in that feature. Thank you

**Comment by palma21** [comment]
> Ability to specify an image ID (image pre-built by Azure) when creating a nodepool so that all nodes in this nodepool contain the same patch-level, even if new nodes are added after the nodepool was created. 

This is already true, new nodes added to a nodepool will always use the same image.

Also for other nodepools if you want to create them with the same image, you'll want to use the nodepool snapshot from the first one. (so you get both the image and nodepool version that works with it)

**Comment by palma21** [comment]
For the cases of purely upgrade consistency, you can use upgrade groups that do not require you to take snapshots. 

To the question on why, AKS manages the control plane, addons and nodes. All versions are validated to work for the service specific version and can introduce differences on either side that risk incompatibility if not validated. That would reduce operation success if you use an image with a version of the service that it wasn't built for and vice versa.

**Comment by ericsuhong** [comment]
> > Ability to specify an image ID (image pre-built by Azure) when creating a nodepool so that all nodes in this nodepool contain the same patch-level, even if new nodes are added after the nodepool was created.
> 
> This is already true, new nodes added to a nodepool will always use the same image.
> 
> Also for other nodepools if you want to create them with the same image, you'll want to use the nodepool snapshot from the first one. (so you get both the image and nodepool version that works with it)

I don't think this is the case. We cannot specify image IDs to the node pool, and can only specify SKU types. It will always try to fetch the latest OS images available, and while nodepool image upgrades are progressing, if another latest node image is available, new nodes will start picking up different versions (more latest ones), causing OS image version drift.
