### ISSUE TITLE
Service Public IP stops working

### ISSUE THREAD

**Issue by pjbgf** [Azure/AKS#360]
I have a Kubernet service of type LoadBalancer. It has a LoadBalancer Ingress IP that was working and providing me a way to access the service publicly through that IP.

A few hours after the service was provisioned, the public IP stopped working. No errors or failed states can be found. However, I can no longer access the end point through the public IP. 
The pods are working and can be accessed by other pods or from my local machine by using `kubectl port-forward`. 

Once that state is reached, even if I delete the service and re-create it with `kubectl expose po/pod-name --type LoadBalancer`, the Public IP assigned is never accessible externally.
Are there any recommendations on investigating/recovering from such states?

**Comment by slack** [comment]
Could you provide output from `kubectl describe service,ep` in the impacted namespace? I'm curious about any events associated with the service or endpoints.

Are you able to verify the status of the Azure LB (named kubernetes) in the `MC_` resource group?

**Comment by pjbgf** [comment]
@slack, I had deleted the given service and created it again before I saw your reply. Now that specific service simply does not acquire an IP, here's the EP events related to that:

```
  Type     Reason                      Age                 From                Message
  ----     ------                      ----                ----                -------
  Warning  CreatingLoadBalancerFailed  44m (x696 over 2d)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service default/aqua-web: timed out waiting for the condition
  Normal   EnsuringLoadBalancer        4m (x704 over 2d)   service-controller  Ensuring load balancer
```

Checking the Azure LB status through the portal, I see no errors. I have now configured for it to push logs onto OMS, once I get something I will share that here.

**Comment by omgsarge** [comment]
We too had this, our externally accessible NGINX suddenly just stopped responding, traffic was getting lost somewhere en-route to the cluster itself and no amount of clearing it down and re-deploying made any difference. Even tried simplest possible echo-container exposed over ELB, still the same result.

As we have been using AKS for a while now we have had to get pretty good at scripting our entire estate out so that we can continuously re-create new ones when they break, as we get plagued massively with TLS Handshake/Timeout errors where the masters get corrupted/faulted very often - creating a brand new cluster and re-deploying via our CD pipeline.... everything works fine.

**Comment by MuthuvelkumarS** [comment]
@pjbgf, 
We too face same issue. Do you have any update on this? Recreating brand new cluster / resource group didn't help us.

**Comment by pjbgf** [comment]
@MuthuvelkumarS I never heard anything else back from MS. In the end, I re-provisioned the cluster and the issue was gone.

**Comment by callumevans** [comment]
We've run into this twice in a week. Only solution we've found is to spit out a new cluster.

Seems like it _might_ be tied to our ingress rules or controllers. If we misconfigure them or do something specific that either Azure or Kubernetes doesn't like. However, we can nuke everything in the cluster, leaving a pod and a load balancer, and traffic still doesn't get through.

**Comment by shm007g** [comment]
I got this in AKS and it really hurts me when i'am re-test AKS. I don't know what happend when my domain name can't reach service. Then I know it. I manually edit svc and get load-balancer a new external IP, then my AKS work again.

**Comment by Raistlix** [comment]
@shm007g I'm assuming your making the edits within the Kubernetes portal. What type of edit to the service?

**Comment by shm007g** [comment]
`kubectl edit svc ${name}`  to edit svc type from `LoadBalancer` to `NordPort`, then change it back, see if service will load again. But it doesn't work.

Then i search the statement `external ip invalid`. So, i ping my external IP, which i timeout.  Reason Found !!

Then I edit svc again, delete the static external ip i put with key `LoadBalancerIP`. It load quickly to another reachable external IP.

**Comment by stigok** [comment]
Same problem in West Europe. Running a v1.10.7 cluster. Deleting and creating a new LoadBalancer does not work. Restarting the Node VMs does not work. The load balancer is not receiving traffic on the provisioned public IP address. `port-forward` to the service works grand!

Worked fine one day, the next - poof. Azure status reads all green and dandy. Have to create a new cluster too.

**Comment by khushalpatel1981** [comment]
We are also facing the same problem here. Nothing in the cluster could be accessed through the LB Any Help???

**Comment by tauqirghani** [comment]
Same issue. The public address points to microsoft but does not get resolved.
tchaudhr-MBP13:Kubernetes tauqir$ traceroute 40.76.87.26
traceroute to 40.76.87.26 (40.76.87.26), 64 hops max, 52 byte packets
 1  192.168.1.1 (192.168.1.1)  2.843 ms  0.923 ms  0.787 ms
 2  10.74.96.1 (10.74.96.1)  9.727 ms  9.248 ms  9.009 ms
 3  ip68-4-12-134.oc.oc.cox.net (68.4.12.134)  15.354 ms  12.360 ms  9.791 ms
 4  100.120.104.2 (100.120.104.2)  11.497 ms  24.130 ms  19.365 ms
 5  68.1.1.61 (68.1.1.61)  12.263 ms  15.925 ms  12.121 ms
 6  ae60-0.lax-96cbe-1a.ntwk.msn.net (104.44.12.204)  12.149 ms  12.121 ms  14.139 ms
 7  be-73-0.ibr02.lax03.ntwk.msn.net (198.206.164.233)  74.179 ms  80.741 ms  78.904 ms
 8  be-3-0.ibr01.sn4.ntwk.msn.net (104.44.4.5)  74.004 ms  77.593 ms  89.005 ms
 9  be-1-0.ibr02.sn4.ntwk.msn.net (104.44.4.204)  76.850 ms  73.883 ms  77.714 ms
10  be-6-0.ibr01.atb.ntwk.msn.net (104.44.4.46)  78.028 ms  75.021 ms  75.206 ms
11  be-1-0.ibr02.atb.ntwk.msn.net (104.44.4.39)  81.207 ms  76.855 ms  75.098 ms
12  be-3-0.ibr02.bn6.ntwk.msn.net (104.44.16.45)  75.140 ms
    be-4-0.ibr01.bn6.ntwk.msn.net (104.44.16.43)  73.978 ms
    be-3-0.ibr02.bn6.ntwk.msn.net (104.44.16.45)  75.148 ms
13  be-4-0.ibr03.bn6.ntwk.msn.net (104.44.7.182)  73.800 ms
    be-3-0.ibr04.bn6.ntwk.msn.net (104.44.7.176)  77.075 ms  76.937 ms
14  be-2-0.ibr03.bl7.ntwk.msn.net (104.44.7.75)  76.619 ms  74.665 ms
    be-2-0.ibr04.bl7.ntwk.msn.net (104.44.7.77)  73.332 ms
15  ae141-0.icr01.bl20.ntwk.msn.net (104.44.21.210)  73.818 ms
    ae162-0.icr02.bl7.ntwk.msn.net (104.44.21.216)  77.157 ms
    ae163-0.icr02.bl20.ntwk.msn.net (104.44.21.220)  76.101 ms
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *

**Comment by herrbpl** [comment]
And of course, we are having same issue as well.

**Comment by herrbpl** [comment]
Apparently, when public IP changes for load balancer, things are not changed in node nat services. There will be old Public IP address.

It can be verified that kubeproxy does not update public ip address for cluster using 
iptables -v -L -t nat

**Comment by herrbpl** [comment]
Or you can look it from iptables-save output.

Problem is, something keeps changing public ip back to old values even when you try to override it with iptables. Somewhere is kubernetes config that overrides that.

**Comment by dmitrios** [comment]
Same here: the only way to restore AKS LB is to restart all cluster nodes.

**Comment by librannk** [comment]
any update on this ?? ...how do you restart all the cluster nodes ? and is there any permanent fix for the same?

**Comment by klingerf** [comment]
I just encountered this issue as well on a 1.12.7 AKS cluster. Everything was working fine when I setup the cluster, but after a few hours all external IPs stopped responding.

**Comment by jeffmartinxyz** [comment]
@slack @jnoller could this issue be related to https://github.com/kubernetes/kubernetes/issues/61005 ?

**Comment by waltherg** [comment]
I have the exact same issue in the West Europe zone. Including the weird traceroute behaviour for the assigned public IP address.

**Comment by ubreddy** [comment]
Restart the kube-proxy pods on each node by deleting the pods. It seems to refresh the data.

**Comment by chpspiir** [comment]
Same exact situation here. Tried restarting kube-proxy, but it didn't fix the issue

**Comment by Torbik** [comment]
Met the same issue. External IP for Nginx Ingress stopped working. IP was accessible from the cluster pods but not outside. Thanks to @shm007g fixed it by removing external IP from the services:

`kubectl patch svc nginx-ingress-controller -p '{"status": {"loadBalancer": {"ingress": []}}}'`

After saving, Kube pulled the same IP back and IP became accessible
