### ISSUE TITLE
[BUG] Containers can lose access to the GPU

### ISSUE THREAD

**Issue by OvervCW** [Azure/AKS#3601]
**Describe the bug**
There is currently a [known issue](https://github.com/NVIDIA/nvidia-docker/issues/1671) where containers can lose access to the GPU after a while and the only solution is to recreate the pod.

There are several possible workarounds:

* [Comment 1](https://github.com/NVIDIA/nvidia-docker/issues/1671#issuecomment-1330466432)
* [Comment 2](https://github.com/NVIDIA/nvidia-docker/issues/1671#issuecomment-1419720602)

However, all of these workarounds require a level of access that is not feasible on Azure AKS (like changing container daemon settings). Would it be possible for you to integrate these workarounds in the VM images?

**Comment by palma21** [comment]
We're working on it

**Comment by alexeldeib** [comment]
https://github.com/Azure/AKS/issues/3680#issuecomment-1585298045

will be fixed in 202306.07.0 VM image from AKS.

Ensure you deploy nvidia device plugin with PASS_DEVICE_SPECS set to true via env or CLI.

**Comment by alexeldeib** [comment]
think this is good...let me know if not
