### ISSUE TITLE
Is it possible to make AKS without public IP?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/AKS#3608]
Hello,

We currently have an old cluster with Basic internal load balancer and 1 VMAS node pool. The only purpose of having it is not having any public ip. 

Now, we need to create a new cluster with standard load balancer, multiple VMSS node pools. But, our organization do not allow us to have any public ip or jump server  or auzre VM(for ado self-hosted agents) due to which we are unable to make private AKS as well.

Is it possible to have new cluster with Standard sku load balancer of internal type(by just adding the annotation), without any public ip. If yes, will it be possible to deploy apps on it via azure devops and git actions. Or, should we choose Basic LB again for this but, then we can't have multiple node pools. 

I read something related to [UDR here](https://github.com/MicrosoftDocs/azure-docs/issues/47461#issuecomment-600415447) but, I don't know what it is and if it can help in this situation or not. 

Kind Regards,
Tanul

**Comment by kamilzzz** [comment]
@smartaquarius10 
> I read something related to https://github.com/MicrosoftDocs/azure-docs/issues/47461#issuecomment-600415447 but, I don't know what it is and if it can help in this situation or not.

It should help I believe. If you choose to create AKS with UDR as outbound type then load balancer won't be created for you. That is for the cluster egress traffic.
For ingress traffic it does not matter as with any outbound type you anyway control what kind of load balancer is used for your service of type LoadBalancer via annotations.

As for the deploying apps, that is where AKS API server comes into play. By default AKS API server is available via public address (but it doesn't create any PIP in cluster RG, it is MS managed). Depending on your requirements this may be fine or not. If you cannot use publicly routable AKS API server, your options are to either deploy private endpoint for AKS API server or use API Server VNET integration as @ralph089 pointed out, but looks like that is still in preview.

**Comment by smartaquarius10** [comment]
@kamilzzz But in UDR is it mandatory to have Azure firewall. We have express route connected to Azure from On-Prem. Can't this be enough or should we need the Firewall

**Comment by kamilzzz** [comment]
Azure Firewall is not needed per se, but in UDR outboundType it is expected you will have route table with 0.0.0.0/0 pointing to some component which will allow Internet egress (AKS requires Internet egress). Instead of Azure Firewall you can use any NVA or maybe even route egress through on-premise site (probably not the best idea, though).
