### ISSUE TITLE
Advanced DNS not working

### ISSUE THREAD

**Issue by neutrongenious** [Azure/AKS#361]
i have tried party-clippy tutorial as explained: https://docs.microsoft.com/en-us/azure/aks/http-application-routing 

DNS entry is not created as expected. i have tried investigating and issued logs command, which returned following error:

```
kubectl logs -f deploy/addon-http-application-routing-external-dns -n kube-system
Error from server: Get https://aks-agentpool-38494388-0:10250/containerLogs/kube-system/addon-http-application-routing-external-dns-7464fdb989-f8f7g/addon-http-application-routing-external-dns?follow=true: dial tcp 10.35.104.6:10250: getsockopt: connection timed out
```

**Comment by neutrongenious** [comment]
@slack any help?

**Comment by slack** [comment]
Connection errors to `10250` fetching logs indicates an issue with apiserver to node communication. Can you grab the output of:
```
kubectl -n kube-system get po -o wide -l component=tunnel

kubectl -n kube-system get po -o wide -l component=tunnel -l component=kube-svc-redirect
```

You can restart the tunnel component with `kubectl -n kube-system delete po -l component=tunnel` and it should restart automatically.

**Comment by neutrongenious** [comment]
also tried
**kubectl exec -it party-clippy-7cc79c475d-ng76j -- /bin/bash**
Error from server: error dialing backend: dial tcp 10.35.104.68:10250: getsockopt: connection timed out

**kubectl logs party-clippy-7cc79c475d-5d547**
Error from server: Get https://aks-agentpool-38494388-2:10250/containerLogs/default/party-clippy-7cc79c475d-5d547/party-clippy: dial tcp 10.35.104.68:10250: getsockopt: connection timed out

**Comment by neutrongenious** [comment]
@slack any news?

**Comment by neutrongenious** [comment]
This is a blocker in our utilization of AKS.

**Comment by slack** [comment]
Not sure what is going on. Can you open an Azure support request?

**Comment by neutrongenious** [comment]
case opened: 118051518185555

**Comment by bergerx** [comment]
seems like similar issue with #232

**Comment by rite2nikhil** [comment]
Closing this issue, please reopen if this still exists
