### ISSUE TITLE
Can we connect to the web app via internet if AKS is created inside Site-2-Site VPN Vnet?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/AKS#3610]
Hello,

If we create an AKS cluster inside a VNET which is configured to have site-2-site vpn connectivity with the on-premises network then how to reach to the microservices and websites hosted inside kubernetes.

Are those microservices accessible over internet or do we need to be on company network to access our microservices?

Kind Regards,
Tanul

**Comment by PixelRobots** [comment]
Hello,

That all depends on how you are accessing your pods. If you are accessing them via teh pod IP on the subnet then you can just use that. If you are using an ingresss controller, which you should be, then you can either configure it to use an internal Azure loadbalancer, or a public one. 

If you use an internal one the loadbalancer will get an IP address on the same vnet, you can then configure your internal DNS to point the site addresses to the internal lodbalancer IP.

If you use a public loadbalancer then you will get a public IP address and then you can configure your public DNS to use this IP.

You can check more about installing an ingress controller at https://learn.microsoft.com/en-us/azure/aks/ingress-basic?tabs=azure-cli

To create an ingress controller with an internal loadbalancer then check out this link. https://learn.microsoft.com/en-us/azure/aks/ingress-basic?tabs=azure-cli#create-an-ingress-controller-using-an-internal-ip-address

Hope that helps. If you have any questions let me know.

Thanks

Richard
