### ISSUE TITLE
[BUG] az aks command invoke does not work with aks vnet integration

### ISSUE THREAD

**Issue by tg123** [Azure/AKS#3615]
**Describe the bug**

az aks command invoke cannot reach the api server if vnet integration enabled

**To Reproduce**
1. Create a private aks cluster with vnet integration enabled
2. Run command

```
az aks command invoke   --resource-group group --name aks   --command "kubectl get pods -n kube-system"
```

3. See error

```

(GatewayTimeout) The gateway did not receive a response from 'Microsoft.ContainerService' within the specified time period.
Code: GatewayTimeout
Message: The gateway did not receive a response from 'Microsoft.ContainerService' within the specified time period
```

**Expected behavior**

**Screenshots**
N/A

**Environment (please complete the following information):**
 -  CLI Version  2.47.0
 - Kubernetes version 1.24.10
 - CLI Extension version [e.g. 1.7.5] N/A
 - Browser [e.g. chrome, safari] N/A

**Additional context**
N/A

**Comment by EppO** [comment]
There is something wrong with your environment, I'm also using VNet integration on a private AKS clusters (along with Azure CNI Powered by Cilium) and it works as expected from my laptop that doesn't have direct access to the AKS Kubernetes API. Are you sure you have direct access to https://management.azure.com?

**Comment by haitch** [comment]
@tg123 can you attach --debug and capture the operation Id, correlation Id and the approximate time.
