### ISSUE TITLE
[Known Issue][Calico+hostPort on Windows] Windows Nodes cannot access pod's local PortMappings

### ISSUE THREAD

**Issue by AbelHu** [Azure/AKS#3620]
**Describe the bug**
When node attempts to access its own local hostPort mapped to pod, traffic will never reach container networking stack but instead be dropped by TCP/IP stack.

**To Reproduce**
Reference: https://github.com/Azure/azure-container-networking/issues/1863
This will happen when Calico is enabled with using hostPort

**Expected behavior**
Expect traffic to be routed from TCP/IP stack to container networking stack.

**Environment (please complete the following information):**
This issue exists in both WS2022 and WS2019. It needs the fixes from both Azure CNI and Windows OS. 

**Additional context**
**NOTE**: The fix in Windows OS will only be done in WS2022. Please add your comments if you need the fix to be backported to WS2019.

**Comment by daschott** [comment]
The fix is tracked by MSFT as Bug 44061820.
