### ISSUE TITLE
[BUG] Error: failed to create containerd task: failed to create shim task: hcs::CreateComputeSystem : The requested operation for attach namespace failed.: unknown on windows node

### ISSUE THREAD

**Issue by teocrispy91** [Azure/AKS#3627]
**Describe the bug**
On windows node in aks the pods are going into crashloopback while describing the pod . I get the following error 

[BUG] Error: failed to create containerd task: failed to create shim task: hcs::CreateComputeSystem : The requested operation for attach namespace failed.: unknown 

**Environment (please complete the following information):**
 -  Cluster version -1.24.9
 - Containerd- 1.6.14
 - Image Version - windowsserver2019.17763.4010.23

**Comment by ThomsonSibiMukkada** [comment]
Hi Teo,

I am also experiencing the same issue. This problem could be due to a mismatch between the base image and the AKS Windows version. To resolve this issue, you can change the base image in your Dockerfile. I can provide you with a link to help you find the correct base images.

https://hub.docker.com/_/microsoft-dotnet-sdk
https://github.com/dotnet/msbuild/issues/7946

**Comment by allyford** [comment]
@teocrispy91 - Please file a [support ticket](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportrequest) for the above bug.

**Comment by vimalavadaparthi** [comment]
Hello,
I'm facing an issue where i'm getting this error "Error: failed to create containerd task: failed to create shim task: hcs::CreateComputeSystem otel-collector: The requested operation for attach namespace failed.: unknown
" in eks while trying to deploy splunk-otel on windows nodes "Windows Server 2019 Datacenter" where the kubernetes version of eks cluster is "1.31" & the repository: quay.io/signalfx/splunk-otel-collector-windows, tag: 0.141.0 where i mentioned in splunk otel values.yaml file. Please do provide me the solution for this
