### ISSUE TITLE
[Feature] Upgrade AGIC addon to 1.7.2

### ISSUE THREAD

**Issue by EppO** [Azure/AKS#3628]
**Is your feature request related to a problem? Please describe.**
AKS AGIC add-on is falling behind, using 1.5.3 while latest version is 1.7.2

**Describe the solution you'd like**
Upgrade AGIC add-on to 1.7.2

**Describe alternatives you've considered**
Installing AGIC add-on with helm but manage add-ons vs helm releases is easier.

**Comment by christiaanderidder** [comment]
+1 Because of added support for rule priorities: https://github.com/Azure/application-gateway-kubernetes-ingress/pull/1343

**Comment by arsenvlad** [comment]
Seeing that https://github.com/Azure/AKS/releases/tag/2023-06-25 says "Upgrade AGIC addon to version 1.7.1 for K8S >= 1.27".
