### ISSUE TITLE
[Question] Can cluster autoscaler account for gpu type + count / instance series /  well known labels like `node.kubernetes.io/instance-type` ?

### ISSUE THREAD

**Issue by chiragjn** [Azure/AKS#3629]
**Describe scenario**
I have configured multiple nodepools (one for M60 GPU, one for T4 GPU, ...) on AKS all with min count 0 and cluster autoscaler enabled. 

**Question**
1. Given a set of resource requirements, GPU type (M60, T4, V100, ...) and count in `resources.limits` (e.g. `nvidia.com.gpu: 4`), can the cluster autoscaler scale up one of the fitting nodepools?
2. Is there any ability to give instance series (like `NC` covering all `Standard_NC*`) or instance type (`node.kubernetes.io/instance-type`) and have the cluster autoscaler take that into account and scale up one of the fitting nodepool?

To put it bluntly, I am looking for an automatic node provisioning system that can be triggered with node-selector or affinity terms - equivalent to AWS Karpenter for EKS or GCP Node Auto Provisioning for GKE.

**Comment by chiragjn** [comment]
For people landing here, there is some relevant discussion here: https://learn.microsoft.com/en-us/answers/questions/435223/how-to-use-cluster-autoscaler-with-nodeselector-no

**Comment by alexeldeib** [comment]
@jpalma fun one which @marwanad also asked me for. I mostly suggest using node feature discovery today, but if AKS supported this better out of the box it would play better with cluster autoscaler, especially scale from zero. 

https://github.com/kubernetes-sigs/node-feature-discovery

**Comment by kevinkrp93** [comment]
@chiragjn - Have you tried taints and tolerations to scale specific node pools for specific pods?
https://learn.microsoft.com/en-us/azure/aks/operator-best-practices-advanced-scheduler#provide-dedicated-nodes-using-taints-and-tolerations

**Comment by chiragjn** [comment]
> @chiragjn - Have you tried taints and tolerations to scale specific node pools for specific pods?
https://learn.microsoft.com/en-us/azure/aks/operator-best-practices-advanced-scheduler#provide-dedicated-nodes-using-taints-and-tolerations

Yes, currently we are using this, however, I would prefer not to set up different taints manually for different nodepools and rather have the cluster autoscaler take decisions based on well-known labels that contain VM SKU, Nvidia accelerator name, etc

**Comment by chiragjn** [comment]
I am closing this because https://github.com/Azure/karpenter-provider-azure is a thing now and is probably the right solution for this
