### ISSUE TITLE
Exempt Azure policy for AD Users in specific AD group?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/AKS#3630]
Hello,

Is it possible to bypass Azure policy for specific AD users or AD groups while creating objects in Azure kubernetes.

Regards,
Tanul

**Comment by CocoWang-wql** [comment]
@fseldow for checking this issue

**Comment by fseldow** [comment]
Hi @smartaquarius10, do you have an example on which policy you are referring?
Is it one control plane policy that monitoring AKS property (like enforcing feature private cluster enable), or one data plane policy that monitoring kubernetes resource like pod

**Comment by smartaquarius10** [comment]
@fseldow , for example, pick non root azure policy. It will not allow the deployment of root privilege pods. 

But, if administrator wants to debug something then s/he might need to deploy any kind of pod in the cluster. In such cases Azure policy will not allow anyone to deploy the root pods in cluster. You can check [this link ](https://learn.microsoft.com/en-us/azure/aks/node-access#:~:text=Copy-,kubectl,-debug%20node/aks) where microsoft suggest the possible way to connect to AKS nodes via root privileges. Here, Azure policy will not allow us to connect to the nodes via this method.

So how to create this segregation. Is it possible if we create two different AD groups in which one have access to anything but other cannot bypass the policy restrictions.

**Comment by fseldow** [comment]
Sorry @smartaquarius10 currently it does not support this scenario. we may need to bring to internal discussion to evaluate. cc @charleswool 
A workaround to use node access is set policy parameter imageExclusion with value ["mcr.microsoft.com/dotnet/runtime-deps:*"]

**Comment by nehakulkarni123** [comment]
Hi @smartaquarius10, this scenario is not supported via Azure Policy today but a related effort is in our backlog. For more information & dialogue on the subject, feel free to reach out to policypm@microsoft.com-- we'd be happy to chat more!
