### ISSUE TITLE
[Question] How to set default topology spread constraints for a AKS cluster

### ISSUE THREAD

**Issue by iluoy** [Azure/AKS#3636]
**Describe scenario**
I want to set default topology spread constraints for a AKS cluster(https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#cluster-level-default-constraints) so that I don't need to add topologySpreadConstraints on each pod template.

**Question**
How to apply KubeSchedulerConfiguration to AKS cluster? Or is there any way to change kube-scheduler configurations?

**Comment by fredzach** [comment]
Possible duplicate of #3056, although that is raised as a feature request (suggesting that the answer to this question is: you cannot).
