### ISSUE TITLE
AKS with advanced DNS - specific domain/subdomain - Feature request

### ISSUE THREAD

**Issue by neutrongenious** [Azure/AKS#364]
**Feature request**
it would be great if AKS creation portal/template allows us to:
- select already created Azure DNS rather than creating it's own on fly
or allows to customize domain name.

**Comment by northtyphoon** [comment]
Our service is running on our own custom domain. As the ingress rule must use the special aks domain as the host, I don't see how to set up the tls on our own custom domain.
