### ISSUE TITLE
Network Observability Basic Metrics

### ISSUE THREAD

**Issue by chasewilson** [Azure/AKS#3643]
AKS Network Observability includes capabilities defined by <TBD>

[Public Preview](https://azure.microsoft.com/en-us/updates/network-observability-add-on/)  will include:
- Basic Metrics logging
- Capture capabilities

**Comment by VincentS** [comment]
Any update when this will go GA ?

**Comment by Khushbu-Parekh** [comment]
Since this will be OOB Metrics when Manged Prometheus is enabled on AKS cluster. Customers do not have to follow any process to enable it
