### ISSUE TITLE
[Question] How do I programmatically connect to an AKS cluster and create a K8 clientset in Golang?

### ISSUE THREAD

**Issue by suranamudit-procyon** [Azure/AKS#3648]
**Describe scenario**

I am trying to fetch all the namespaces present in an AKS cluster programmatically using Golang for which I need to create a Kubernetes clientset for that particular AKS cluster, so that I can list the namespace as follows:

`k8ClientSet.CoreV1().Namespaces().List(context.Background(), metav1.ListOptions{})
`

I will need to this from outside the cluster so kube-config cannot be used and I will not be able to use the Kubelogin exec plugin since it requires it to be installed on the host system which is not possible. Even, the azure auth plugin has been deprecated.

**Question**

As of now, I am trying to use this API provided by Azure - https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/run-command?tabs=HTTP which I do not think is the best approach, but that's all I have got so far.

Pls help in creating a K8 clientset for an AKS cluster and share code sample, if possible.

**Comment by andyzhangx** [comment]
if you cannot use the kube-config, how can you connect to the aks cluster?

**Comment by suranamudit-procyon** [comment]
I meant that we cannot use the kube-config file directly, I had to do that via code.
I got this solution from Azure QnA forum and it worked!

```
import (
    "context"
    "fmt"
    "os"

    "github.com/Azure/azure-sdk-for-go/profiles/latest/containerservice/mgmt/containerservice"
    "github.com/Azure/go-autorest/autorest"
    "github.com/Azure/go-autorest/autorest/azure/auth"
    "k8s.io/client-go/kubernetes"
    "k8s.io/client-go/rest"
)

func main() {
    // Get the AKS cluster credentials using Azure Active Directory authentication
    authorizer, err := auth.NewAuthorizerFromEnvironment()
    if err != nil {
        panic(err.Error())
    }
    subscriptionID := "<your-subscription-id>"
    resourceGroupName := "<your-resource-group-name>"
    clusterName := "<your-aks-cluster-name>"
    client := containerservice.NewManagedClustersClient(subscriptionID)
    client.Authorizer = authorizer
    credentials, err := client.ListClusterAdminCredentials(context.Background(), resourceGroupName, clusterName)
    if err != nil {
        panic(err.Error())
    }
    kubeconfig := string(credentials.Kubeconfigs[0].Value)

    // Create a Kubernetes clientset
    config, err := rest.InClusterConfig()
    if err != nil {
        config, err = clientcmd.NewClientConfigFromBytes([]byte(kubeconfig)).ClientConfig()
        if err != nil {
            panic(err.Error())
        }
    }
    clientset, err := kubernetes.NewForConfig(config)
    if err != nil {
        panic(err.Error())
    }

    // <span class=" active-doc-0" data-doc-items="0">List all the namespaces present in the AKS cluster[1](#doc-pos=0)</span>
    namespaces, err := clientset.CoreV1().Namespaces().List(context.Background(), metav1.ListOptions{})
    if err != nil {
        panic(err.Error())
    }

    // Print the name of each namespace
    for _, ns := range namespaces.Items {
        fmt.Println(ns.Name)
    }
}
```
