### ISSUE TITLE
Istio AKS addon

### ISSUE THREAD

**Issue by miwithro** [Azure/AKS#3649]
Currently in public preview: https://learn.microsoft.com/azure/aks/istio-deploy-addon

Tentatively targeting early October for GA of this add-on

**Comment by adamyager** [comment]
> Istio add on @shashank to add details.

I am sure you all love these questions early on, but they are important in planning for the end customer.
Is there any expectation this will be GA in this Calendar year? Maybe by October?

**Comment by huangyingting** [comment]
@Azure/aks-pm is there any updates so far for GA date?

**Comment by shashankbarsin** [comment]
@huangyingting tentatively targeting early Oct for GA of the addon

**Comment by Vegoo89** [comment]
Hello. I would like to provide my own static IP for ingress gateway load balancer, but parameter is missing. Are there any plans to add it?

**Comment by mdaslamansari** [comment]
> @huangyingting tentatively targeting early Oct for GA of the addon

Is it still on track? Any tentative date?

**Comment by workwithprashant** [comment]
We are at end of October month. Is there ETA for GA release?

**Comment by joshbsemperis** [comment]
We are at the end of November. Is there an ETA for GA Release? @miwithro

**Comment by mdaslamansari** [comment]
Any latest updates on it? Please also advise the migration path for those who are using ISTIO open source to migrate to this managed addon...

**Comment by Vegoo89** [comment]
There are still issues that - in my opinion - prevents this from going GA.

As example, below issue involving support for node tolerations has been opened for months now:
https://github.com/Azure/AKS/issues/3882

**Comment by shashankbarsin** [comment]
@mdaslamansari - migration from OSS Istio to managed addon Istio is on our backlog, but we are planning to pick up that work only after the GA of the addon (which helps new installations). There are challenges associated with such a migration, specifically on how we handle istio ingresses and CAs in such a migration. Once those details are finalized and we have a clear ETA on the migration, will share an update.

**Comment by shashankbarsin** [comment]
@Vegoo89 - we are looking into the addon scheduling bug you shared. Will get back with an update soon
