### ISSUE TITLE
[Question] Cross Subscription Support for Trusted Access and Azure ML Extension

### ISSUE THREAD

**Issue by MarkusDressel** [Azure/AKS#3651]
**Describe scenario**
We have one subscription (A) for our Azure ML workspaces. Data Scientists can perform their model training there. When it comes to deployment, we have AKS in a separate subscription (B) operated by another team. We would use the Azure ML extension with trusted access (disabled local admin accounts) to smoothly deploy a model from Azure ML in subscription A in our Azure Kubernetes Cluster in Subscription B. Since both are azure services, we would like to avoid to setup up an Azure ARC just for this purpose

Currently, it is clearly mentioned that cross-sub connectivity is not supported. We have also tested it and the role binding fails with the error that the two subscription ids are not the same.

**Question**
Do you have cross-subscription support for trsuted access in combination with the Azure ML extension on your internal roadmap and if so, any rough timeline?

**Comment by CocoWang-wql** [comment]
Hello @MarkusDressel  thanks for the feedback. We do have cross subscription in plan and the ETA is about August or Sept.
