### ISSUE TITLE
[Question] How to reduce image pull and extraction times with AKS?

### ISSUE THREAD

**Issue by JoostvDoorn** [Azure/AKS#3652]
**Describe scenario**
We use AKS and our workloads use relatively large container images, some are 10GB+. Mostly related to dependencies such as CUDA+Pytorch that are very large etc. This causes pull times+extraction times of these containers to be relatively high. Where it seems mostly due to the extraction time and disk performance of the associated VM. We encounter a lot of cold starts where the image isn't aren't pulled to the node yet because we don't want to keep relatively expensive node types like A100 running idle. It takes now about 10 minutes to schedule a node with these images including the time for the auto scaler. One idea we have is to reduce image pull times is by pre-populating the most common images in /var/lib/docker inside of the VM image of the scale set used by AKS, but custom images are not supported by AKS see #1942

**Question**
How to reduce image pull and extraction times with AKS?

**Comment by hex1848** [comment]
I've also experienced A100's taking 8-10 minutes to provision.  We have auto scaling turned on based requests per second on our inference server - 10 minutes is a long time to get new instances spun up to help with the load.

**Comment by olsenme** [comment]
Have you tried multiple sizes?

**Comment by JoostvDoorn** [comment]
> Have you tried multiple sizes?

If the container image is smaller it will be indeed faster, but unfortunately due to the nature of the dependencies it's difficult to get to a very minimal size that would significantly reduce the time to pull and extract the container.
