### ISSUE TITLE
[Question] Do ARM nodes work for Azure CNI Overlay? 

### ISSUE THREAD

**Issue by brammulders** [Azure/AKS#3654]
**Describe scenario**
After numerous tries with CNI Overlay in combination with ARM nodes in multiple regions ( Standard_D2pls_v5 + Standard_D4pls_v5), I have concluded it seems that these SKU types do not work (well) with CNI Overlay.

When I have multiple nodes pod to pod communication across different nodes seemst to not be working and traffic is routed to outside of the cluster.

How to replicate this issue:
Create a CNI Overlay cluster with node sku "Standard_D4pls_v5" in region WestEurope.
Scale to 3 nodes. You will notice that the "Metrics-server" does not become healthy due to traffic issues.

Thanks in advance.

**Question**
Do ARM nodes work for Azure CNI Overlay?

**Comment by olsenme** [comment]
How many pods per node? @phealy

**Comment by jmasengeshomsft** [comment]
> **Describe scenario** After numerous tries with CNI Overlay in combination with ARM nodes in multiple regions ( Standard_D2pls_v5 + Standard_D4pls_v5), I have concluded it seems that these SKU types do not work (well) with CNI Overlay.
> 
> When I have multiple nodes pod to pod communication across different nodes seemst to not be working and traffic is routed to outside of the cluster.
> 
> How to replicate this issue: Create a CNI Overlay cluster with node sku "Standard_D4pls_v5" in region WestEurope. Scale to 3 nodes. You will notice that the "Metrics-server" does not become healthy due to traffic issues.
> 
> Thanks in advance.
> 
> **Question** Do ARM nodes work for Azure CNI Overlay?

Do you have NSGs on the node's subnet? Maybe its related to these rules: https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay?tabs=kubectl#network-security-groups
