### ISSUE TITLE
[BUG] nmi pods vulnerabilities 

### ISSUE THREAD

**Issue by sspanda123** [Azure/AKS#3659]
Case Update:
===================
POD -- aad-pod-identity-nmi
IMAGE -- mcr.microsoft.com/oss/azure/aad-pod-identity/nmi:v1.8.14
CVE names: 
>> HostPath volumes present many security risks, and it is a best practice to avoid the use of HostPaths when possible. When a HostPath volume must be used, it should be scoped to only the required file or directory, and mounted as ReadOnly. Please refer to the Kubernetes documentation on how to configure a hostpath: https://kubernetes.io/docs/concepts/storage/volumes/#hostpath .

>> Do not set any capabilities for your pod apiVersion: v1 kind: Pod metadata:  name: example spec:  containers:  securityContext:   capabilities:    add: [] #This should be empty Do not add SYS_ADMIN, NET_ADMIN or ALL
Either set the pod security context to spec.securityContext.runAsNonRoot=true or set securityContext.runAsNonRoot=true on each container in the pod.
- Version:             1.25.5

**Comment by sozercan** [comment]
@sspanda123 these are not CVEs but application configurations. These are minimum runtime requirements for AAD Pod Identity/NMI, it is working as expected. If you have a policy warning against these configurations, you'll need to exempt Pod Identity from this policy.

Also, as mentioned in the [announcement](https://github.com/Azure/aad-pod-identity#-announcement), AAD Pod Identity is deprecated and OSS project will be archived in September. We _strongly recommend_ moving to [Azure Workload Identity in AKS](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview), which is a GA feature now.
