### ISSUE TITLE
Enable Accelerated Networking for AKS nodes

### ISSUE THREAD

**Issue by sabbour** [Azure/AKS#366]
**Feature request:**

Please enable [Accelerated Networking](https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli) for nodes on supported VM configurations. Accelerated Networking is a feature that can be enabled on NICs.

**Comment by seanmck** [comment]
You can upvote and track this enhancement here:

https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/34893970-enable-accelerated-networking

**Comment by SychevIgor** [comment]
As it was mentioned 

"AKS Team (Product Manager, Microsoft Azure) responded  ·  November 13, 2018
This is now enabled automatically in AKS for supported VM SKUs."
