### ISSUE TITLE
How to integrate RBAC enabled AKS with any CI/CD environment?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/AKS#3665]
Hello,

After enabling RBAC, AKS expect kubelogin to connect with anything and it doesn't allow creation of service connections as well.

How to create a create service connection with any CI/CD tool. For example, this is the output with Azure devops while selecting Azure subscription as authentication method.

![image](https://github.com/Azure/AKS/assets/7824529/25b5165f-c23b-4f38-a9d6-b1c44b09077e)

**Comment by olsenme** [comment]
https://learn.microsoft.com/en-us/answers/questions/1286813/how-to-integrate-rbac-enabled-aks-with-any-ci-cd-e

**Comment by smartaquarius10** [comment]
@olsenme This is me.
