### ISSUE TITLE
Updating old cluster (kubernetes version 1.14) from legacy Azure AD to new Azure AD method [Question]

### ISSUE THREAD

**Issue by JRobertEdwards** [Azure/AKS#3667]
Hi, 

I currently have a number of old services running on kubernetes version 1.14 that are using legacy Azure AD.

I would like to know what the potential impact could be on such an old version of kubernetes updating it to the new Azure AD method. The UI suggests the new method but I can't see any potential issues from the Azure docs regarding the update.
These docs: https://learn.microsoft.com/en-us/azure/aks/managed-azure-ad#enable-aks-managed-azure-ad-integration-on-your-aks-cluster do mention a minimum kubectl version but there's no mention of a minimum kubernetes version / compatibility issues.

Thanks,
Josh

**Comment by olsenme** [comment]
@miwithro

**Comment by JRobertEdwards** [comment]
Closed due to timeline stretching too far. New clusters were created at the latest available version.
