### ISSUE TITLE
What is the latest audit policy applied in AKS?

### ISSUE THREAD

**Issue by d4rk-d4nph3** [Azure/AKS#3671]
AKS diagnostic logs provides kube-audit which logs everything and kube-audit-admin which is a subset of kube-audit. Where can I find the latest audit policy used in AKS to generate kube-audit?

I found https://github.com/Azure/aks-engine/blob/24244adcd09afcf452c2e16317999046a240e992/parts/k8s/addons/audit-policy.yaml (last commit: May 29, 2020) to be the audit policy but in https://github.com/Azure/AKS/issues/2145, @miwithro had commented (in June 10, 2021) that the audit policy was changed. Maybe it has again changed (maybe multiple times even).

So, what is the current audit policy?

**Comment by olsenme** [comment]
@miwithro
