### ISSUE TITLE
[Feature]  --os-sku AzureLinux CBLMariner does not currently support FIPS enabled

### ISSUE THREAD

**Issue by jrudley** [Azure/AKS#3675]
**Is your feature request related to a problem? Please describe.**
Cannot set os sku to AzureLinux when --enable-fips-image is passed into azure cli

**Describe the solution you'd like**
Provision AzureLinux with --enable-fips-image

**Describe alternatives you've considered**
not using AzureLinux.

**Additional context**
![image](https://github.com/Azure/AKS/assets/1934411/7c6c091a-7b04-4ae3-9fce-3ff6067f4f58)

I am in GCC High.

**Comment by suhuruli** [comment]
ACK @jrudley - thank you for filing this. This is something we are aware of and working on.

**Comment by jrudley** [comment]
Yes, but does this work with azurelinux cbl mariner nodes?

**Comment by suhuruli** [comment]
Yes - those docs are for all Linux nodepools (Ubuntu and Azure Linux). Just verified it myself for a quick sanity check: 

`az aks create -g suhuruli -n suhuruli-fips --os-sku AzureLinux --enable-fips-image`

```
PS C:\Users\suhuruli> az aks show --resource-group suhuruli --name suhuruli-fips --query="agentPoolProfiles[].{Name:name enableFips:enableFips}" -o table
The behavior of this command has been altered by the following extension: aks-preview
Name       EnableFips
---------  ------------
nodepool1  True
```

**Comment by jrudley** [comment]
Great, thanks. I will verify in gcc high once I get back from traveling.
