### ISSUE TITLE
API Server certificate not valid

### ISSUE THREAD

**Issue by neutrongenious** [Azure/AKS#368]
a quick check on API SSl cert shows it's not properly issued:

Certificate not valid

Common name: apiserver
SANs: hcp-kubernetes, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, hcp-kubernetes.5af5668fb2a7b20001af13b3.svc.cluster.local, XYZ****.hcp.westeurope.azmk8s.io, 10.0.0.1
Valid from May 11, 2018 to May 10, 2020
Serial Number: 6a9b23aaa78d2edcebcd83929440bd87
Signature Algorithm: sha256WithRSAEncryption
Issuer: ca

**Comment by slack** [comment]
AKS creates a self-signed certificate for every cluster. What tool are you using to validate the certificate?

**Comment by wonderb0lt** [comment]
I am using curl from within the cluster, [using this command from SO](https://stackoverflow.com/a/30739416/660848) with adding the CA file that is mounted in a pod. Previously, the command succeeded, but now it fails with this error message:

```
}root@ubuntu-549c9cfcb7-jv4lk:/# curl -v -sS -H "Authorization: Bearer $KUBE_TOKEN" --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://kubernetes.default.svc
* Rebuilt URL to: https://kubernetes.default.svc/
*   Trying 10.0.0.1...
* TCP_NODELAY set
* Connected to kubernetes.default.svc (10.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: O=system:masters; CN=client
*  start date: Jun 13 11:42:39 2018 GMT
*  expire date: Jun 12 11:42:39 2020 GMT
*  subjectAltName does not match kubernetes.default.svc
* SSL: no alternative certificate subject name matches target host name 'kubernetes.default.svc'
* stopped the pause stream!
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (51) SSL: no alternative certificate subject name matches target host name 'kubernetes.default.svc'
```

AFAIK, the API server is not reachable via the URL "apiserver" within the cluster. And even if so, "kubernetes.default.svc" should be supported as a hostname.

**Comment by wonderb0lt** [comment]
However, it turns out, this is a problem with just one out of our three AKS instances. Unfortunately, I can't give a definite answer when that defective cluster has been created.

**Comment by love2dishtech** [comment]
Is there an option to provide a trusted CA certificate for API server?

**Comment by jnoller** [comment]
Closing issue as stale / the certs should be valid
