### ISSUE TITLE
GPU becomes unavailable

### ISSUE THREAD

**Issue by rogelioamancisidor** [Azure/AKS#3680]
I send several jobs from a bash file, e.g.

    run my_code.py --some_params
    run my_code.py --other_params
    ....
to a nodepool running a A100 GPU. The first job uses the GPU. I can see that the GPU is used in wandb and also because I ping the VM and confirmed that the GPU is available using tensorflow. However, when the second run starts the GPU is unavailable. Again, I confirmed that in wandb and I ping the VM.

Why is happening this? I have never experienced this before. 

**UPDATE** I ping the VM and running `nvidia-smi` returns
    
    Failed to initialize NVML: Unknown Error
    
I found this [link](https://github.com/NVIDIA/nvidia-docker/issues/1730) and this other one [link](https://github.com/NVIDIA/nvidia-docker/issues/1671)

**Comment by olsenme** [comment]
What sku are you using?

**Comment by rogelioamancisidor** [comment]
I happend with both `standard_nc24ads_a100_v4` and `standard_nc6s_v3`. But now is working fine again.

**Comment by rogelioamancisidor** [comment]
@alexeldeib I used the same `nvidia-device-plugin-ds.yaml` file that I had, which is the same as in [here](https://learn.microsoft.com/en-us/azure/aks/gpu-cluster) but adding `PASS_DEVICE_SPECS` equal `true` at the same level as in the deployment in your link.  However, running `nvidia-smi` outptus

    Failed to initialize NVML: Unknown Error

**Comment by rogelioamancisidor** [comment]
@alexeldeib  I guess I can simply add `PASS_DEVICE_SPECS` in the nvidia device pluging given in the AKS [tutorial](https://learn.microsoft.com/en-us/azure/aks/gpu-cluster) and set it to `true`, right? or should I use the one you linked? BTW when is the 202306.07.0 VM released? because the GPU in my jobs still becomes unavailable.

**Comment by wjhhuizi** [comment]
Found the same issue:

When the container started on the NC24s_v3 node, most of the time the `nvidia-smi` will works fine, however after a while if I'm lucky enough, I will get the `Failed to initialize NVML: Unknown Error` output from running `nvidia-smi` command again.

Input
``` python
import torch
print("CUDA Version used in Python: " + torch.version.cuda)
print("CUDA Device is Available: " + str(torch.cuda.is_available()))
```
Output:
```
CUDA Version used in Python: 11.7
CUDA Device is Available: False
```

When this happens, the GPU would be kept unavailable until I restart the Pod.

This is a super annoying issue which causing our ML workflow broken... Please do some investigation into this issue.

**Comment by wjhhuizi** [comment]
> will be fixed in 202306.07.0 VM image from AKS.
> 
> Ensure you deploy nvidia device plugin with `PASS_DEVICE_SPECS` set to `true` via env or CLI.
> 
> [NVIDIA/nvidia-docker#966 (comment)](https://github.com/NVIDIA/nvidia-docker/issues/966#issuecomment-610928514) [NVIDIA/nvidia-docker#1671 (comment)](https://github.com/NVIDIA/nvidia-docker/issues/1671#issuecomment-1330466432)
> 
> this deployment (can disable privileged for most scenarios) works fine: https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/main/deployments/static/nvidia-device-plugin-compat-with-cpumanager.yml
> 
> AKS preview GPU dedicated VHD needs an additional tweak with TBD ETA, probably in the next few weeks.

So can you please give a little more information on the Root cause? Was so curios since this problem bothered us for several month...

**Comment by alexeldeib** [comment]
take a peek at these links

https://github.com/NVIDIA/nvidia-container-toolkit/issues/48
https://github.com/NVIDIA/nvidia-docker/issues/966#issuecomment-610928514
https://github.com/NVIDIA/nvidia-docker/issues/1671#issuecomment-1330466432

it's an issue with systemd as the cgroup manager, we applied the char device fix mentioned in the first link via udev rules

**Comment by rogelioamancisidor** [comment]
@alexeldeib The problem is back (well I am not sure if it actually disappeared). As mentioned before, I set `PASS_DEVICE_SPECS` to `True` in the nvidia device pluging given in the AKS tutorial. I'll use the script that you posted and see if that helps. BTW, I dont need to upgrade the node image, as it is a nodepool deployed after 202306.07.0.

**Comment by rogelioamancisidor** [comment]
@wjhhuizi  did you solve the problem by following the above solution? I have deployed the suggested nvidia device plugin (after delinting the previous one), updated  the VM image in both the agentpool node and the gpu node, but the problem isnt solved! Very frustrating

**Comment by justindavies** [comment]
Can you let me know if you are still seeing this issue?

**Comment by rogelioamancisidor** [comment]
I started using the AKS GPU image instead of the device plugin as the solution posted here never worked for me.
