### ISSUE TITLE
[Question] fips_enabled and end of ubuntu 1804 support

### ISSUE THREAD

**Issue by adamutils** [Azure/AKS#3689]
**Describe scenario**
Ubuntu 18.04 LTS end of support ends at 31th of May 2023.
If I execute command
az aks nodepool get-upgrades     --nodepool-name poolname --cluster-name someclustername     --resource-group some resourcegroup
I'm seeing latest available image version 1804gen2fips
{
  "id": "/subscriptions/somesubscription/resourcegroups/someresourcegroup/providers/Microsoft.ContainerService/managedClusters/someclustername/agentPools/systempool/upgradeProfiles/default",
  "kubernetesVersion": "1.25.6",
  "latestNodeImageVersion": "AKSUbuntu-1804gen2fipscontainerd-202305.15.0",
  "name": "default",
  "osType": "Linux",
  "resourceGroup": "someresourcegroup",
  "type": "Microsoft.ContainerService/managedClusters/agentPools/upgradeProfiles",
  "upgrades": null
}

**Question**
What about customers that have fips enabled?
When image AKSUbuntu-2204gen2fips is going to be available?

**Comment by thecmdradama** [comment]
Coming here to ask the same thing. Have just upgraded our Non-Prod cluster to 1.26.3 and was wondering why it was still using the Ubuntu 18.04 gen2 fips image.

**Comment by olsenme** [comment]
@allyford , @justindavies

**Comment by alexeldeib** [comment]
AKS has access to ESM from Canonical and uses this to support both FIPS and base 18.04 Ubuntu beyond EOL.

We're working to upgrade fips to 20.04 (22.04 not yet certified).

**Comment by chengliangli0918** [comment]
@alexeldeib I think we can close this. 
AKS uses ESM from Canonical to support FIPS 18.04 beyond EOL. And for 1.27+ AKS FIPS nodes, Ubuntu 20.04 FIPS OS will be used (Ubuntu 22.04 is not FIPS certified yet)
