### ISSUE TITLE
Detected the use of APIs that have a deprecation warning for a previous, current, or future Kubernetes version

### ISSUE THREAD

**Issue by rakesh-vishwabrahmana** [Azure/AKS#3693]
**Describe scenario**
I have upgraded my cluster version to **1.25.5** from **1.24.10**. I see there is an Kubernetes API Deprecations issue in Diagnose and solve problems which says _"Detected the use of APIs that have a deprecation warning for a previous, current, or future Kubernetes version"_

User Agents - argocd-application-controller/v0.0.0 (linux/amd64) kubernetes/$Format
kubectl/v1.27.2 (linux/amd64) kubernetes/****

**Question**
I have a resources calling the ApiGroup **podsecuritypolicies**, how to migrate to new ApiGroup?

Thanks

**Comment by sabbour** [comment]
The v1.25 release will remove `PodSecurityPolicy`, which was deprecated with Kubernetes 1.21 and will not graduate to stable. See: https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/

We recommend you migrate to [Pod Security Admission](https://learn.microsoft.com/en-us/azure/aks/use-psa).
