### ISSUE TITLE
AKS Preview API Deprecations

### ISSUE THREAD

**Issue by alvinli222** [Azure/AKS#3696]
Hi everyone, we have begun the process of deprecating old APIs. Here is the current status of API deprecations:

| API version                   | Deprecation Date |
|--------------------------|----------------|
| 2018-08-01-preview    |  June 1, 2023 |
| 2021-11-01-preview    |  July 1, 2023 |
| 2022-01-02-preview    |  Sept 1, 2023 | 
| 2022-02-02-preview    |  August 1, 2023 | 
| 2022-03-02-preview    |  Sept 1, 2023 | 
| 2022-04-02-preview    |  Sept 1, 2023 | 
| 2022-05-02-preview    |  Sept 1, 2023 |
| 2022-06-02-preview    |  Sept 1, 2023 |

Recommendation Actions:

- To avoid errors from the retired API, please move to a [newer version](https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/allversions) of the AKS API. 
- If you're consuming this API via one or more SDKs, updating to a [newer version](https://azure.github.io/azure-sdk/releases/latest/index.html?search=containerservice) of the SDK will also update the API.
- You may be consuming this API through a tool such as Terraform or az cli:
**For az cli:** update the CLI itself and the `aks-preview` extension (if used) to the latest version by running `az upgrade` and `az extension update --name "aks-preview"`.
**For Terraform:** Update to the latest version of Terraform AzureRM. To determine what version of the API a particular Terraform release is using, check the [Terraform release notes](https://learn.microsoft.com/en-us/azure/developer/terraform/provider-version-history-azurerm) or git log [this file](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/containers/client/client.go).
**For other tools:** Update the version of the tool to the latest version.
- If you're not sure what client or tool you're using which could be using this API version, check [activity logs](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log) using the following command:
```
API_VERSION=2022-04-02-preview
az monitor activity-log list --offset 30d --max-events 10000 --namespace microsoft.containerservice --query "[?eventName.value == 'EndRequest' && contains(not_null(httpRequest.uri,''), '${API_VERSION}')]"
```

**Comment by BogdanGeorge** [comment]
Hello, we received an email from Azure that we are using 2022-05-02-preview API which was retired since 1 September 2023. 
In order to understand what tools are using this depregated api i check the activity logs by following your proposal:

`az monitor activity-log list --offset 30d --max-events 10000 --namespace microsoft.containerservice --query "[?eventName.value == 'EndRequest' && contains(not_null(httpRequest.uri,''), '${2022-05-02-preview}')]"`

All the event logs that I get are similar and have the following properties
    "id": "/subscriptions/{GUID}/resourceGroups/{resource-group-name}/providers/Microsoft.ContainerService/managedClusters/{k8sClusterName}/trustedAccessRoleBindings/defender-cloudposture/events/8b809343-d6e3-4807-ad2d-96619311ca22/ticks/638295760225138752",
    "level": "Informational",
    "operationId": "{GUID}",
    "operationName": {
      "localizedValue": "Create or update trusted access role bindings for managed cluster",
      "value": "Microsoft.ContainerService/managedClusters/trustedAccessRoleBindings/write"
    },
	"httpRequest": {
      "clientIpAddress": "{IP-ADDRESS}",
      "clientRequestId": "{GUID}",
      "method": "PUT",
      "uri": "https://management.azure.com/subscriptions/{GUID}/resourceGroups/{resource-group-name}/providers/Microsoft.ContainerService/managedClusters/{k8sClusterName}/trustedAccessRoleBindings/defender-cloudposture?api-version=2022-05-02-preview"
    },
    "properties": {
      "entity": "/subscriptions/{GUID}/resourceGroups/{resource-group-name}/providers/Microsoft.ContainerService/managedClusters/{k8sClusterName}/trustedAccessRoleBindings/defender-cloudposture",
      "eventCategory": "Administrative",
      "hierarchy": ""
      "message": "Microsoft.ContainerService/managedClusters/trustedAccessRoleBindings/write",
      "serviceRequestId": null,
      "statusCode": "OK"
    },

Does anyone have an ideea of why we get this error and how to fix it ?

**Comment by matthchr** [comment]
@BogdanGeorge your best bet is probably to examine the `identity` section of the `az monitor` log and determine who issued it, then use that to determine what is issuing those commands and get them to update to a newer API version.

We're working on getting userAgent exposed as well in `az monitor` for future deprecations to make that process easier (identity + useragent should help you to track down who is issuing these cmds).

**Comment by matthchr** [comment]
> @BogdanGeorge your best bet is probably to examine the `identity` section of the `az monitor` log and determine who issued it, then use that to determine what is issuing those commands and get them to update to a newer API version.
> 
> We're working on getting userAgent exposed as well in `az monitor` for future deprecations to make that process easier (identity + useragent should help you to track down who is issuing these cmds).

Turns out this is being used by the defender team, so you can't fix it. We're engaging with them now. The API won't be removed until they've migrated. If that's your only usage of that API version you should be good.

**Comment by tzachiabo** [comment]
Those requests are indeed coming from our side (defender)
I am working on migration to a newer API version, ETA ~5d
