### ISSUE TITLE
Cannot make work the OMS tutorial

### ISSUE THREAD

**Issue by Guillaume-Mayer** [Azure/AKS#37]
I followed the step of the tutorial:
https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-monitor
but nothing appears in the monitor solution.

I am in West US 2

Does someone completed it ?

**Comment by sauryadas** [comment]
@keikhara ?

**Comment by Guillaume-Mayer** [comment]
I finally could make it work, it gives nothing but errors at the beginning, but after some time, it begins showing data, maybe it was because of problems in westus2, or because I didn't wait enough.

**Comment by slack** [comment]
@Guillaume-Mayer do you happen to have any of the error messages or logs that might shed light on the issue?

How quickly after provisioning did you install OMS?

**Comment by Guillaume-Mayer** [comment]
@slack It's seems to work fine now, I guess I was to impatient the first time, when waiting like 10 minutes maybe, data begins to appear.

**Comment by slack** [comment]
Ok great. I'll close this issue out. Ping again if you have trouble in the future. Thanks!
