### ISSUE TITLE
[Question] How to avoid Ingress request and corresponding egress traffic(response) to go to firewall

### ISSUE THREAD

**Issue by dw511214992** [Azure/AKS#3700]
**Describe scenario**
I'm creating aks and web application by follow the [document](https://learn.microsoft.com/en-us/azure/aks/limit-egress-traffic). The documents describes:
1. Deploy a AKS with outbound type `UserDefinedRouting`, and all outbound traffic are flowing to firewall by adding a route to the route table
![image](https://github.com/Azure/AKS/assets/40835867/6025f3f7-6b1a-4ab8-ae90-b2c6d0f6b114)
`10.2.0.4` is the internal ip of firewall.

2. Deploy a web application in the AKS and configure a NAT in firewall to solve asymmetric issue.

In our service, we cannot use NAT in firewall. We deploy a kubernetes service with type loadbalancer. we want to request the web application by the loadbalance service's public ip. To avoid the response traffic flows to firewall, I add a new route to route response traffic to the internet.
![image](https://github.com/Azure/AKS/assets/40835867/99ff76e6-4ed6-43b4-b1f4-8bd4b2db47e5)
`20.8.138.38/32` is the public ip of the loadbalancer.

However, it seems the asymmetric mtric issue still exists and I cannot get response from my web application. When I change the firewall related route's next hop type to Internet, I can get response from my web.

**Question**
How to configure the route table to make my web application's response not flow to firewall?

**Comment by dw511214992** [comment]
Hi @abarqawi Yes, I know this solution can make me access my web application by using firewall public ip successlly. However, because of our service's special requirement, we need to make the request traffic to web application and response traffic __not__ flow into the firewall. Is there any idea about it?
Thanks

**Comment by wangyira** [comment]
@chasewilson , could you help take a look
