### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by anoopks12** [Azure/AKS#3701]
**Describe scenario**
I have installed Azure managed keda into AKS cluster using Azure cli following the documentation.
https://learn.microsoft.com/en-us/azure/aks/keda-deploy-add-on-cli
The version of the keda installed is 2.9.3
Kubernetes version is 1.24.10

**Question**
I would like to update the keda version to 2.10.0(due to bug fixes available in this version). Is it possible to do do via azure cli without updating the kubernetes version.

**Comment by carvido1** [comment]
Hello there @anoopks12 .

You can upgrade Keda using kubectl, you can edit the manifest yourself.
BR
