### ISSUE TITLE
[BUG] AKS autoscaler is not respecting `skip-nodes-with-local-storage` flag

### ISSUE THREAD

**Issue by urbantz-technical-support** [Azure/AKS#3704]
**Describe the bug**
We set the default cluster-autoscaler profile but the system is not respecting `skip-nodes-with-local-storage` flag. This means is not considering nodes for scale down if they contain pods with local-storage such as emptyDir.

We suspect this happened to use ever since the k8s 1.26 upgrade. Date correlate for us on all our clusters.

**To Reproduce**
1. Deploy standard cluster manually set to 3 nodes
2. Deploy pods with emptyDir on all nodes
3. Enable autoscaling with a minimum replica count of 1
4. See how azure is refusing to scale done the nodes

**Expected behavior**
We expect azure to correctly configure the cluster open source autoscaler based on the azure api. 

**Screenshots**
![Captura desde 2023-06-09 12-45-18](https://github.com/Azure/AKS/assets/98543028/76a09dfb-42ee-4a95-9862-1c7d4a79e013)
![Captura desde 2023-06-09 13-24-05](https://github.com/Azure/AKS/assets/98543028/f161a65b-ac2d-4e1f-94ca-20a10205b22b)

**Environment (please complete the following information):**
 - CLI Version 2.49.0
 - Kubernetes version 1.26.3

**Additional context**

Links to absolutely desperate attempts to make azure support team understand the difference between local storage and a persistence storage. Support request ID:
 * 2306090050001760
 * 2305050050002701

**Comment by cjdmax** [comment]
I seem to have the same issue on AKS 1.25.6, despite using `az aks update [...] --cluster-autoscaler-profile scale-down-utilization-threshold=0.7 skip-nodes-with-local-storage=false skip-nodes-with-system-pods=false scale-down-unneeded-time=5m expander=least-waste`

**Comment by olsenme** [comment]
@justindavies

**Comment by kevinkrp93** [comment]
@urbantz-technical-support @cjdmax 
Please use the following annotation on the pod 
"cluster-autoscaler.kubernetes.io/safe-to-evict-local-volumes": "volume-1,volume-2,.." or "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node.

**Comment by kevinkrp93** [comment]
The bug was fixed from 1.26.4 onwards.
