### ISSUE TITLE
[BUG] Issues from the roadmap get stale and auto-closed

### ISSUE THREAD

**Issue by marcindulak** [Azure/AKS#3708]
**Describe the bug**

Several issues present on the roadmap (even in "development") acquire a "stale" tag and get auto-closed, examples:
https://github.com/Azure/AKS/issues/3515
https://github.com/Azure/AKS/issues/3520
https://github.com/Azure/AKS/issues/3522
https://github.com/Azure/AKS/issues/3523

Additionally, the bot writes about the issue "It will be closed if no further activity occurs within 15 days of this comment.", but instead it closes the issue after about a week.

**Comment by qpetraroia** [comment]
@palma21, thoughts on creating a specific label for "roadmap" which does not automatically add the stale tag after 15 days?

**Comment by marcindulak** [comment]
Issue about issues getting stale got stale

**Comment by marcindulak** [comment]
Has this been adressed?

**Comment by marcindulak** [comment]
It appears not addressed yet.

Here are the recent issues present on the roadmap that were closed by the bot

https://github.com/Azure/AKS/issues/3324
https://github.com/Azure/AKS/issues/3645
https://github.com/Azure/AKS/issues/3776
https://github.com/Azure/AKS/issues/4098

Tagging involved people, @qpetraroia @kaarthis @olsenme @miwithro

**Comment by marcindulak** [comment]
:eyes:

**Comment by marcindulak** [comment]
These two issues from the roadmap are about to be closed by the bot

https://github.com/Azure/AKS/issues/3522
https://github.com/Azure/AKS/issues/3643

It may be a question of lacking tags.

Please, if anyone is managing this repo, please have a look @kaarthis @chasewilson

**Comment by marcindulak** [comment]
@aritraghosh - I see you are recently active on the [Azure Kubernetes Service Roadmap (Public)](https://github.com/orgs/Azure/projects/685) by managing issues. Maybe you are able to contact someone to find out a solution how to prevent active issues on the roadmap from being auto-closed?
