### ISSUE TITLE
Process for updating K8S SPN

### ISSUE THREAD

**Issue by williamayerst** [Azure/AKS#371]
We need to rotate SPN keys every year in line with security policy, however it is not clear what the defined process is for this, as updating via a ResourceGroup deployment to the 'K8S' RG does not appear to reflect those changes in the SPN used by the service. 

Any service which will provision cloud infrastructure such as a Loadbalancer ingress type sits on 'pending' forever. The only way around this appears to be a full redeployment.

**Comment by slack** [comment]
Sadly, we don't support service principal update in AKS today.

We are working toward using user assigned MSI (EMSI) to replace the use of SP all together.

**Comment by andyzhangx** [comment]
JUST FYI. In acs-engine or ACS service, the update SPN process is simple, update the SPN in `/etc/kubenetes/azure.json` and restart kubelet.

**Comment by williamayerst** [comment]
So to be clear, a single AKS cluster for now, unless you come up with an enhancement, is limited in lifespan to the same as the SPN creds used to create it?

**Comment by holmesb** [comment]
> unless you come up with an enhancement, AKS is limited in lifespan to the same as the SPN creds used to create it?
I'm hopeful the lack of response to this question indicates everyones' AKS clusters will not break upon SPN pw expiry.  But confirmation would be appreciated!

**Comment by choovick** [comment]
Expired keys are really tough to detect. I have a cluster that been running for couple of months and my service principal secret have expired last week.

* 1st - after cluster upgrade backend pool on loadbalancer was empty. So no traffic was routed to ingress services. Had to fix it manually in the Portal.
* 2nd - creating new LoadBalancer based services will fail with:

```text
Events:
  Type     Reason                      Age                From                Message
  ----     ------                      ----               ----                -------
  Warning  CreatingLoadBalancerFailed  48s                service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service default/test: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxx/resourceGroups/MC_xxx-aks_xxx-aks_eastus/providers/Microsoft.Network/loadBalancers?api-version=2017-09-01: StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: b441ab58-709c-40ba-9885-99e990601c00\r\nCorrelation ID: 00bd11fa-8e6a-4e2e-952b-5362260b5cb4\r\nTimestamp: 2018-12-11 13:46:24Z","error_codes":[70002,50012],"timestamp":"2018-12-11 13:46:24Z","trace_id":"b441ab58-709c-40ba-9885-99e990601c00","correlation_id":"00bd11fa-8e6a-4e2e-952b-5362260b5cb4"}
```

I did confirm that Service Principle secret was expired in `/etc/kubenetes/azure.json` on worker node.

Also `az ad sp create-for-rbac` command creates service principal with key that expires after a year. So until EMSI is available there is no way to **update keys on PROD cluster**? In that case we at least should update docs and tooling to **ensure that service principal keys we are creating do not expire**.

So now, i'm going to have recreate my pre-production cluster...

**Comment by andyzhangx** [comment]
cc @weinong

**Comment by weinong** [comment]
We are actively working on the reset API. I hope to share result as early as next week. Sorry for the inconvenience!

**Comment by choovick** [comment]
@weinong Thanks for update, thought we had to wait for EMSI which will result in our automation changes... Can't wait to try reset api once ready. Please keep us posted!

**Comment by BaloMueller** [comment]
The clientsecret on our **production** cluster expired! So my only chance is to spin up a whole new cluster?! Omg...

**Comment by BaloMueller** [comment]
Thank you @choovick 

I already tried that yesterday. Created a new Clientsecret for the aadClientId in `/etc/kubernetes/azure.json`, set this new value in the json -> Restarted kubelet, but the persistent 
volumes still can't be mounted. 

Fortunately I was able to set the Backend Pool for the Loadbalancer manually. So we can use the cluster till the weekend to switch to a new one.

Will it be possible to mount the persistent volumes in the new cluster? If yes, what do we have to do?

**Comment by choovick** [comment]
We don't have state in the cluster, as we use external services for that. You'll have to describe your PVs to get K8S events related to mounting issues. Could be something else completely.

**Comment by andyzhangx** [comment]
@BaloMueller persistent volumes mount is controlled by controller-manager on master node, so `/etc/kubenetes/azure.json` on master nodes should also be updated, otherwise pv volume mount won't work.

**Comment by BaloMueller** [comment]
@andyzhangx as mentioned in my post before, I updated my aadClientesecret in /etc/kubernetes/azure.json on all nodes and restartet kubelet service. The PV still cant be mounted

**Comment by andyzhangx** [comment]
@BaloMueller That's the correct behavior, `/etc/kubernetes/azure.json`  on master node should also be updated.

**Comment by BaloMueller** [comment]
I did that, but it doesn't help!

I'm seeing the following error: 

> Unable to mount volumes for pod "es-data-0_default(853ccc1e-feed-11e8-8262-0a58ac1f047d)": timeout expired waiting for volumes to attach or mount for pod "default"/"es-data-0". list of unmounted volumes=[storage]. list of unattached volumes=[storage default-token-fv9db]
(combined from similar events): AttachVolume.Attach failed for volume "pvc-dc0da1b5-4a33-11e8-a6db-0a58ac1f0c0e" : failed to get azure instance id for node "aks-agentpool1-75642350-0" (azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/712aed80-8eec-4b16-8abf-4455246df58e/resourceGroups/MC_rapitag-container_rapitag-backend_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool1-75642350-0?%!!(MISSING)e(MISSING)xpand=instanceView&api-version=2017-12-01: StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: 8e90e5b1-9acf-4e89-9219-d0045e9b9c00\r\nCorrelation ID: eee78649-c0b1-42e9-bfc6-c1dd673495f7\r\nTimestamp: 2018-12-14 15:16:24Z","error_codes":[70002,50012],"timestamp":"2018-12-14 15:16:24Z","trace_id":"8e90e5b1-9acf-4e89-9219-d0045e9b9c00","correlation_id":"eee78649-c0b1-42e9-bfc6-c1dd673495f7"})

**Comment by choovick** [comment]
@BaloMueller what do you mean you did that? If your are using AKS - you don't have access to `master` nodes, only worker nodes. Master nodes do not exist in your subscriptions or account. Kubeclt talk to `master` nodes that are located under `azmk8s.io` domain. That's why I mentioned contacting support to update these files and restart components on `Masters`

**Comment by BaloMueller** [comment]
Ah! Sorry I misunderstood and thought I could update all servers by myself. 
I will open a support ticket. Thank you for your help!

**Comment by alanjcastonguay** [comment]
Rotation of the AKS Service Principal was added to "az aks update-credentials" in azure-cli version 2.0.56: https://docs.microsoft.com/en-us/azure/aks/update-credentials
