### ISSUE TITLE
[BUG] - Review Guidance https://github.com/Azure/AKS/blob/master/examples/cgroups/README.md

### ISSUE THREAD

**Issue by karianna** [Azure/AKS#3716]
The advice in https://github.com/Azure/AKS/blob/master/examples/cgroups/README.md is no longer correct.

Java as of 1.8.0_362 and 11.0.18 has full CGroupsv2 support and customers do not need to move to Java 15+ or revert to CGroupsv1.

**Comment by karianna** [comment]
@brunoborges is preparing a PR to resolve

**Comment by justindavies** [comment]
I've merged the PR
