### ISSUE TITLE
Sticky Sessions for Internal Loadbalancer

### ISSUE THREAD

**Issue by andtii** [Azure/AKS#372]
Im using nginx ingress - https://docs.microsoft.com/en-us/azure/aks/ingress
and internal load balancer https://docs.microsoft.com/en-us/azure/aks/internal-lb

I need to use sticky sessions to support .net core SignalR. How do i configure this?

**Comment by slack** [comment]
Look at `Sticky Session` docs in nginx-ingress:

* https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/affinity/cookie
