### ISSUE TITLE
Upgrade to Azure CNI Overlay from Azure CNI

### ISSUE THREAD

**Issue by chasewilson** [Azure/AKS#3720]
Azure CNI has been GA'd and Upgrade Capabilities are being added over time. Azure CNI can now be upgraded using Azure CLI with `az aks update`

**Comment by Gordonby** [comment]
It doesn't appear possible to downgrade the Overlay change.
Are there plans to support this, or document the fact that a downgrade is not possible?

ref my testing: https://github.com/Gordonby/Snippets/blob/master/AKS/OverlayNoOverlay.md

**Comment by denniszielke** [comment]
@chasewilson it is unfortunate that you cannot upgrade a cluster that has network policy turned on (probably a lot of customers will not be able to use that migration path). Will we also bring an option to deactivate network policy?

**Comment by giovantan** [comment]
I am using azurerm 3.80.0 and Terraform v1.5.3, and am trying to upgrade the AKS cluster from Azure CNI to Azure CNI overlay. However, when i add in `network_plugin_mode = "overlay"`, the Terraform plan shows me it will add the new plugin mode, but when i apply, it still remains as Azure CNI. I have checked with Azure Support on this, and they said that they did not receive any API call to change the network plugin mode. 

Does this have something to do with network policy being enabled? Any advice would be greatly appreciated!

**Comment by chasewilson** [comment]
If network Policy is enabled, it won't begin the migration process. I'm not positive on how this information is surfaced in TF, so I'm sorry if there is a lack of clarity there. We are currently working on enabling Policy disablement and aiming to have it out soon. 

@wedaly @tyler-lloyd feel free to correct me if I'm wrong or incomplete in my info here.

**Comment by PixelRobots** [comment]
Hello @giovantan Currently if you have network policies enabled you cannot change from azure CNI to Azure CNI overlay. Currently there are a few limitations which you can find in the documentation. https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay?tabs=kubectl#upgrade-an-existing-cluster-to-cni-overlay

Hopefully soon you will be able to disable network policies. check out this git issue. https://github.com/Azure/AKS/issues/3845.

**Comment by giovantan** [comment]
Thanks @chasewilson and @PixelRobots for the confirmation! :)
