### ISSUE TITLE
Private Link Service Integration

### ISSUE THREAD

**Issue by chasewilson** [Azure/AKS#3721]
Private Link Service Integration is in public preview and headed for GA next month

**Comment by denniszielke** [comment]
@chasewilson will this also support to put the PLS into a resource group that is NOT "MC_"? Reason for this is that NodeResourceGroup lockdown will not work if we cannot put the PLS in another RG. According to cloud provider docs that requires something with a file, but we need something like an annotion.

**Comment by CiucurDaniel** [comment]
@denniszielke I think we are looking for the same things. I'm also interested to deploy the PLS in a different RG. I opened an issue here at the docs 
https://github.com/kubernetes-sigs/cloud-provider-azure/issues/4608

**Comment by denniszielke** [comment]
@chasewilson thx! That helps us a lot!

**Comment by chasewilson** [comment]
Feature has been GA'd. Closing Issue
