### ISSUE TITLE
[Feature] Fleet: Kubernetes resource propagation - pick N, topology spread, affinity, anti-affinity

### ISSUE THREAD

**Issue by shashankbarsin** [Azure/AKS#3725]
# Feature Status: Preview
- Azure public doc: https://learn.microsoft.com/en-us/azure/kubernetes-fleet/resource-propagation
- OSS public doc: https://github.com/Azure/fleet/tree/main/docs/howtos
- Kubernetes API: https://github.com/Azure/fleet/blob/main/apis/placement/v1beta1/clusterresourceplacement_types.go

# Feature Description
Kubernetes Fleet Manager (Fleet) allows customers to propagate k8s objects from hub cluster to member clusters to easily distribute workload across clusters ([link](https://learn.microsoft.com/en-us/azure/kubernetes-fleet/architectural-overview#kubernetes-resource-propagation)).

However, customers can only select all member clusters by names or labels as the destinations.

This feature enables customers to pick N out of all member clusters with matching names/labels based on criteria like cluster topology spread constraints, cluster affinity, cluster anti-affinity, similar with existing Kubernetes concepts:
- https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
- https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity

**Comment by circy9** [comment]
This feature is generally available now. See: https://learn.microsoft.com/en-us/azure/kubernetes-fleet/concepts-resource-propagation
