### ISSUE TITLE
[BUG] 1.25.6 cgroup configuration creating problems for running workloads

### ISSUE THREAD

**Issue by Aaron-ML** [Azure/AKS#3729]
**Describe the bug**
Earlier this month we upgraded a few of our development and staging clusters to 1.25.6 and had no issues with any services. 

Yesterday we upgraded our production cluster and noticed the cgroup settings are different, and it's causing Java to be unable to pull container memory settings.  We are unable to find any differences in our settings to explain this.

**To Reproduce**
Upgrade a cluster to 1.25.6 and compare it to one that has been updated a few weeks ago. 

- Run a Java service with container aware settings

**Newly upgraded cluster** 

```
[0.000s][trace][os,container] OSContainer::init: Initializing Container Support
[0.000s][debug][os,container] Detected optional pids controller entry in /proc/cgroups
[0.001s][trace][os,container] No relevant cgroup controllers mounted.
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

~ $ cat /proc/self/cgroup
10:freezer:/
8:cpuacct:/
0::/
```

**Previously upgraded cluster**
```
NOTE: Picked up JDK_JAVA_OPTIONS: -Xlog:os+container=trace -XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=50.0 -XX:+UseG1GC
[0.000s][trace][os,container] OSContainer::init: Initializing Container Support
[0.000s][debug][os,container] Detected optional pids controller entry in /proc/cgroups
[0.000s][debug][os,container] Detected cgroups v2 unified hierarchy
[0.001s][trace][os,container] Path to /cpu.max is /sys/fs/cgroup//cpu.max
[0.001s][trace][os,container] Raw value for CPU quota is: max
[0.001s][trace][os,container] CPU Quota is: -1
[0.001s][trace][os,container] Path to /cpu.max is /sys/fs/cgroup//cpu.max
[0.001s][trace][os,container] CPU Period is: 100000
[0.001s][trace][os,container] OSContainer::active_processor_count: 8
[0.001s][trace][os,container] total physical memory: 33665449984
[0.001s][trace][os,container] Path to /memory.max is /sys/fs/cgroup//memory.max
[0.001s][trace][os,container] Raw value for memory limit is: 536870912
[0.001s][trace][os,container] Memory Limit is: 536870912
[0.001s][trace][os,container] CgroupSubsystem::active_processor_count (cached): 8
[0.012s][trace][os,container] CgroupSubsystem::active_processor_count (cached): 8
[0.015s][trace][os,container] Path to /memory.current is /sys/fs/cgroup//memory.current
[0.015s][trace][os,container] Memory Usage is: 226570240
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

/ $ cat /proc/self/cgroup
0::/
```

**Expected behavior**
It appears that java is unable to detect cgroup settings and there are differences across the newly upgraded clusters cgroup configuration. I suspect the cgroupv1 references in the new cluster are causing issues. 

**Screenshots**

**Environment (please complete the following information):**
- Kubernetes v.1.25.6
- OS: Ubuntu 22.04.2 LTS
- Kernel: 5.15.0-1039-azure
- Container Runtime: containerd://1.7.1+azure-1

**Additional context**
Seems related to #3443

**Comment by Aaron-ML** [comment]
I'm happy to escalate to the Java team, however I'm unsure why the latest upgraded cluster is different from the rest. 

We've explored creating new nodepools and nodes and haven't had any luck.


https://github.com/casparcwang/jdk/blob/master/src/hotspot/os/linux/cgroupSubsystem_linux.cpp#LL135C2-L135C2

>    * Conversely, for cgroups v2 (unified hierarchy), cpu, cpuacct, cpuset, memory
>    * controllers must have hierarchy ID 0 and the unified controller mounted.

non working cluster just upgraded:
```
/sys/fs/cgroup $ cat /proc/cgroups
#subsys_name    hierarchy    num_cgroups    enabled
cpuset        0    296    1
cpu           0    296    1
cpuacct       8    1    1
blkio         0    296    1
memory        0    296    1
devices       0    296    1
freezer       10    1    1
net_cls       0    296    1
perf_event    0    296    1
net_prio      0    296    1
hugetlb       0    296    1
pids          0    296    1
rdma          0    296    1
misc          0    296    1
```
working clusters:
/sys/fs/cgroup $ cat /proc/cgroups
```
#subsys_name    hierarchy    num_cgroups    enabled
cpuset        0    1266    1
cpu           0    1266    1
cpuacct       0    1266    1
blkio         0    1266    1
memory        0    1266    1
devices       0    1266    1
freezer       0    1266    1
net_cls       0    1266    1
perf_event    0    1266    1
net_prio      0    1266    1
hugetlb       0    1266    1
pids          0    1266    1
rdma          0    1266    1
misc          0    1266    1
```

**Comment by justin-chizer** [comment]
@DennisLee-DennisLee and @aritraghosh is this something you can take a look at please?

**Comment by seguler** [comment]
You might have missed my message on the other thread. We are aware of this known issue. You need to upgrade to Java that supports cgroup v2 - documented [here](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/aks-memory-saturation-after-upgrade).

**Comment by Aaron-ML** [comment]
> You might have missed my message on the other thread. We are aware of this known issue. You need to upgrade to Java that supports cgroup v2 - documented [here](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/aks-memory-saturation-after-upgrade).

We are currently on the latest Java 17 release and it supports cgroupsv2. 

The issue is the cluster we recently upgraded doesn't seem to have cgroups setup in a way that can be read from. Seems to be a weird case that we cannot replicate.

**Comment by Aaron-ML** [comment]
We ended up finding out our security scanning software was mounting cgroupv1 with a daemonset causing a weird hybrid mode breaking our services. Sorry for the false alarm, definitely an odd one.

**Comment by MKruger777** [comment]
Thanks Aaron-ML, this was exactly what we experienced as well. 👍
