### ISSUE TITLE
Private endpoint policies on aks subnet

### ISSUE THREAD

**Issue by asifkd012020** [Azure/AKS#3732]
**Describe scenario**
We have a private aks cluster in its own subnet and we use kubenet.
The private endpoint for cluster api does not honour the nsg rules.

**Question**
Can I enable private endpoint policies on aks subnet?
Is it supported scenario for aks?

**Comment by wangyira** [comment]
From our [doc](https://learn.microsoft.com/en-us/azure/aks/private-clusters?tabs=azure-portal#hub-and-spoke-with-custom-dns), 

> If you're using [bring your own route table with kubenet](https://learn.microsoft.com/en-us/azure/aks/configure-kubenet#bring-your-own-subnet-and-route-table-with-kubenet) and bring your own DNS with private clusters, the cluster creation will fail. You need to associate the [RouteTable](https://learn.microsoft.com/en-us/azure/aks/configure-kubenet#bring-your-own-subnet-and-route-table-with-kubenet) in the node resource group to the subnet after the cluster creation failed to make the creation successful.

cc @chasewilson

**Comment by asifkd012020** [comment]
It works with private endpoint policies however BYO subnet and nsg rules are required for intra subnet, podcir and service cidr
