### ISSUE TITLE
[Question] What is the format of the AKS autoscaler configmap "kube-system:cluster-autoscaler-status"

### ISSUE THREAD

**Issue by siyuZL** [Azure/AKS#3733]
**Describe scenario**
I'm using AKS with autoscaler and analyze the autoscaler status.

**Question**
Now I'm using the AKS(1.25.6) and the important part I need is like this:

`Name:        aks-worker-17816125-vmss`
`Health:      Healthy (ready=0 unready=0 (resourceUnready=0) notStarted=1 longNotStarted=0 registered=1 longUnregistered=0 cloudProviderTarget=1 (minSize=1, maxSize=3))`

1. Is this information in exact related 2 lines?
2. Is there any different about this configmap for different AKS version?

**Comment by abarqawi** [comment]
Hi @siyuZL  yes you can do with following :

kubectl get configmap -n kube-system cluster-autoscaler-status -o yaml

reference : [](https://learn.microsoft.com/en-us/azure/aks/cluster-autoscaler#retrieve-cluster-autoscaler-logs-and-status-updates )

**Comment by alexeldeib** [comment]
It's from oss autoscaler, but I don't know how well documented the format is. There are some comments about it in the faq https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md

**Comment by kevinkrp93** [comment]
@siyuZL  The output format is a very long string
