### ISSUE TITLE
[Feedback] dockerBridgeCidr is still all over the AKS documentation.

### ISSUE THREAD

**Issue by Ryangr0** [Azure/AKS#3738]
I'm working on using bicep templates to scaffold infra fast. In my `aksCluster.bicep` The following key exists: "dockerBridgeCidr". The error is as follows: 
```
The property "dockerBridgeCidr" is not allowed on objects of type "ContainerServiceNetworkProfile". Permissible properties include "ipFamilies", "kubeProxyConfig", "natGatewayProfile", "networkDataplane", "networkMode", "networkPluginMode", "podCidrs", "serviceCidrs". If this is an inaccuracy in the documentation, please report it to the Bicep Team.
```

I finally found this issue: #3534 on google which gave me the info I was looking for. I would have definitely expected to find that here instead: https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/change-log/managedclusters but to my shock the entire april release changelog isn't even on that page. The rest of the ("up to date") documentation is littered with "dockerBridgeCidr" so you're constantly put on the wrong track and there is no mention I could find of this being deprecated except in this one github issue which has even been closed.

**Comment by dyu1208** [comment]
The removed property has been mentioned in the April changelong:  https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/change-log/managedclusters#2023-04-01
