### ISSUE TITLE
[Feature] AKS node with Ephemeral disk support for CMK

### ISSUE THREAD

**Issue by sonetolg1** [Azure/AKS#3744]
we have to use ephemeral disks due to the performance issues we have with managed disk. and we would like to utilize CMK feature for better security. Currently AKS with ephemeral  disks does not support CMK in spite of VMs with ephemeral  disks are supported. 

Could you please provide any estimate when the CMK will be supported for ephemeral disks in AKS?

**Comment by andyzhangx** [comment]
we are already working on this, and the doc for this preview feature will be ready very soon.

**Comment by andyzhangx** [comment]
this preview feature is already supported now: https://learn.microsoft.com/en-us/azure/aks/azure-disk-customer-managed-keys#register-customer-managed-key-preview-feature
