### ISSUE TITLE
External load balancer not configuring same ip / different ports properly (port mapping)

### ISSUE THREAD

**Issue by jdevalk2** [Azure/AKS#375]
Using kubernetes 1.9.6 on AKS in east US.

Deploying a 3 broker Kafka cluster to kubernetes, the first idea was to have 3 public IP's mapped to each of the 3 individual brokers. This worked the configuration can be found below.

In this first configuration we created one kubernetes loadbalancer service per Kafka broker pod. So 3 loadbalancer definitions in total.

The second attempt which focused on using less IP's, tried to use a single external IP with port mapping, so instead of having a separate external IP for each broker we use the same IP with 3 different target ports mapped to the individual Kafka broker pods.

In this second configuration we still had one kubernetes loadbalancer service per broker pod, still 3 total. They were now referencing the same single LoadBalancerIP, but differed by target port.

The result is when Azure AKS applies configuration, Azure AKS adjusts the Azure load balancer and it does not set the IP routing configuration correctly. 

It could still be kubernetes network magic with IP tables (could be) though practical test showed the connection from 1.2.3.4:9095 and 1.2.3.4:9096 the TCP connection is rejected.  
1.2.3.4:9094 Seems to work OK for the first broker.

Looking inside the Azure Internal Resource Group created by kubernetes, to the LoadBalancer called "kubernetes". Which is where the loadbalancer config seems to be made. 

I am expecting to see 3 rules like 
External IP: 1.2.3.4 Source port: 9094 Target port: 9092  (Selector: Kafka-0 pod)
External IP: 1.2.3.4 Source port: 9095 Target port: 9092 (Selector: Kafka-1 pod)
External IP: 1.2.3.4 Source port: 9096 Target port: 9092 (Selector: Kafka-2 pod)

9094..9096 are broker ports exposed to the outside world
9092 is the port that the pods are running the service under.

What is produced in the loadbalancer is, only 1 single rule:
External IP: 1.2.3.4 Source port: 9094: Target port: 9094 

Missing rules for port 9095 and 9096. 

Following is the YAML config for port mapping option (not working)
The YAML config for IP mapping option follows (below) Which is working with 3 separate public ip's.
Note Kafka cluster is configured in StatefulSet, using configmap and persistent volume, according to best setup practices.

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-0-svc
spec:
  loadBalancerIP: 1.2.3.4
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:  
  - name: kafka-0-svc-port
    port: 9094
    targetPort: nameOfPortOnPod
  selector:
    app: kafka
    statefulset.kubernetes.io/pod-name: "kafka-0"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1-svc
spec:
  loadBalancerIP: 1.2.3.4
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:  
  - name: kafka-1-svc-port
    port: 9095
    targetPort: nameOfPortOnPod
  selector:
    app: kafka
    statefulset.kubernetes.io/pod-name: "kafka-1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2-svc
spec:
  loadBalancerIP: 1.2.3.4
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:  
  - name: kafka-2-svc-port
    port: 9096
    targetPort: nameOfPortOnPod
  selector:
    app: kafka
    statefulset.kubernetes.io/pod-name: "kafka-2"
---

# The following with 3 IP's works:

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-0-svc
spec:
  loadBalancerIP: 1.2.3.4
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 9094
    name: outside
    targetPort: 9092
  selector:
    app: kafka
    statefulset.kubernetes.io/pod-name: "kafka-0"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1-svc
spec:
  loadBalancerIP: 3.4.5.6
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 9094
    name: outside
    targetPort: 9092
  selector:
    app: kafka
    statefulset.kubernetes.io/pod-name: "kafka-1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2-svc
spec:
  loadBalancerIP: 7.8.9.0
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 9094
    name: outside
    targetPort: 9092
  selector:
    app: kafka
    statefulset.kubernetes.io/pod-name: "kafka-2"
---

**Comment by jnoller** [comment]
User solved
