### ISSUE TITLE
AKS Cluster Access Token Rotation

### ISSUE THREAD

**Issue by bcho** [Azure/AKS#3753]
Hi everyone,

As part of implementing security best practices and ensuring service health, AKS is gradually rolling out a process to rotate the access token in the cluster kubeconfig credentials. It is important to note that the default behavior of this process will not impact existing access to the cluster, as the kubeconfig returned by AKS will still contain valid credentials after the rotation is completed. [Related release note can be found here](https://github.com/Azure/AKS/releases/tag/2023-05-14).

In the event that you have any applications or processes relying on the token directly within the kubeconfig, you can utilize the `az aks get-credentials` command to retrieve the latest token.

**Comment by Aaron-ML** [comment]
This is interesting, ended up invalidating all of my kubecontexts for kubectl.

**Comment by bcho** [comment]
Hi @Aaron-ML may I know if your kubeconfig is using tokens only? Or contains both certificates and tokens? Kubeconfig retrieved by the az command should still be valid after the rotation.

**Comment by andyzhangx** [comment]
> Hi @Aaron-ML may I know if your kubeconfig is using tokens only? Or contains both certificates and tokens? Kubeconfig retrieved by the az command should still be valid after the rotation.

@bcho what's the frequency of access token rotation? there are users that don't want to rotate this access token, they want this token be valid forever, is there any way to disable this rotation for specific subscriptions?

**Comment by bcho** [comment]
> they want this token be valid forever

I would like to know more about the use cases here. Having a static token around might not be a good idea to enforce best security practices. AKS side is working on a new feature to address such usage. These examples would be helpful to guide us.

 > is there any way to disable this rotation for specific subscriptions

Currently AKS doesn't provide a way to disable this.

**Comment by evazhang0129** [comment]
There is scenario that some system use static config file. If rotate, the system will fail.
I would like to know the rotate period? For customer, how to get notice in advance.
Thanks very much.

**Comment by evazhang0129** [comment]
There is scenario that some system use static config file. If rotate, the system will fail.
I would like to know the rotate period? For customer, how to get notice in advance.
Thanks very much.

**Comment by bcho** [comment]
> There is scenario that some system use static config file. If rotate, the system will fail. I would like to know the rotate period. For customer, how to get notice in advance. Thanks very much.

Hi, AKS side is working on a feature to provide notices before the rotation for future rotate events.

**Comment by chicago7** [comment]
There is a scenario in which some systems use static config files. If rotated, the system will fail.
We would like to know the rotation period. For customers, How to get notice in advance? Thanks.
