### ISSUE TITLE
[Question] cgroup v2 on AzureLinux nodes?

### ISSUE THREAD

**Issue by jackmtrayport** [Azure/AKS#3754]
Cluster version: 1.25.6

- Nodes running Ubuntu (22.04.2 LTS, 5.15.0-1036-azure, containerd://1.6.18+azure-1) are using cgroup v2.
- Nodes running AzureLinux (CBL-Mariner/Linux, 5.15.112.1-2.cm2, containerd://1.6.18) are using cgroup v1.

This means that if we want to run clusters with a mix of node OS versions, our apps must detect the cgroup version in use and act accordingly. Is there a plan to make Azure Linux use cgroup v2 by default? If not, can we opt-in somehow?

**Comment by svonliebenstein** [comment]
Briefly looked into it and apparently cgroups v2 can be enabled on Mariner since https://github.com/microsoft/CBL-Mariner/releases/tag/2.0.20230126-2.0 "Toolkit: CGroupsV2 Toggle Optionality for Mariner 2.0 Images".

Don't have experience with the new Azure Linux nodes yet, but maybe this can be enabled somehow?

**Comment by aritraghosh** [comment]
This will be default in AzureLinux in 1.27

**Comment by suhuruli** [comment]
@aritraghosh is correct in that our thinking is to have cgroupsv2 in Azure Linux starting in 1.27.

**Comment by suhuruli** [comment]
Hi everyone - just a note on this issue that as of AKS 1.29, Azure Linux nodes will be using _cgroupsv2_ as the default. Much of the upstream memory accounting issues listed [here](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/aks-increased-memory-usage-cgroup-v2) that occurred are resolved in Kubernetes and hence the switch to using it as the default. 

The guidance is still to sanity test workloads during the preview period of AKS 1.29 and provide feedback/issues as needed.
