### ISSUE TITLE
Azure CNI overlay feedback?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/AKS#3756]
Hello,

Is anyone using Azure cni overlay in production environment. If yes, can someone provide the feedback. Are there any issues coming regarding performance or connectivity or any bad experiences etc in comparison to Azure cni. 

We are creating a new AKS with disabled autoscaler. We will not use windows machines and just wanted to know if overlay approach is healthy, same performance as that of azure cni and has no bugs so that we can go ahead.

Thank you

**Comment by smartaquarius10** [comment]
@phealy hope you are doing well. If possible, could you share some experience on this. Does the network performance with overlay and without overlay azure cni is exactly same. Or, still there is a marginal difference where only azure cni is better than azure cni with overlay approach.

**Comment by smartaquarius10** [comment]
@chasewilson, @Gordonby

Any suggestion on this.

**Comment by qpetraroia** [comment]
Hello!

Azure CNI Overlay is GA, so it's used in production by many customers. Regarding performance, you can read our blog post [here](https://azure.microsoft.com/en-us/blog/announcing-the-general-availability-of-azure-cni-overlay-in-azure-kubernetes-service/#:~:text=Azure%20CNI%20Overlay%20showed%20a%20significant%20performance%20improvement,in%20performance%20degradation%2C%20especially%20as%20the%20cluster%20grows.).


Thanks!
