### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by kamilpi** [Azure/AKS#3762]
**Describe scenario**
I would like to use this preview feature: https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-node-image

My steps:

- `az feature register --namespace "Microsoft.ContainerService" --name "NodeOsUpgradeChannelPreview"`
- `az aks maintenanceconfiguration add -g myRG --cluster-name myAKS -n aksManagedNodeOSUpgradeSchedule --schedule-type Weekly --day-of-week Monday --interval-weeks 1 --duration 8 --utc-offset +01:00 --start-date 2023-07-11 --start-time 01:00`
- `az aks update --resource-group myRG --name myAKS  --node-os-upgrade-channel NodeImage`

**Question**
How can I check the execution of this? I did it before and I did not see any changes with the node polls images version.
I know that it is a preview feature so how can I track this to confirm all with logs?
Did I miss something?

**Comment by carvido1** [comment]
Hello there @kamilpi.

According to azure the cadence of node images updates is in a weekly basis.

```text
AKS updates the nodes with a newly patched VHD containing security fixes and bug fixes on a weekly cadence. The update to the new VHD is disruptive, following maintenance windows and surge settings. No extra VHD cost is incurred when choosing this option. If you use this channel, Linux [unattended upgrades](https://help.ubuntu.com/community/AutomaticSecurityUpdates) are disabled by default.
```

Once you have the feature enabled and the nodepool updated with that option, you need to check the Node Image version from that nodepool (available in the AKS cluster nodepools blade in the Portal, select the nodepool you enabled the feature). If the node image changes in < 14 days, it means the feature works.

BR
