### ISSUE TITLE
[Feature] Azure DNS private zone support in App Routing add-on

### ISSUE THREAD

**Issue by sabbour** [Azure/AKS#3765]
Ability to on-board Azure DNS private zones for use in the App Routing add-on.

**Comment by SatyKrish** [comment]
When will this be available?

**Comment by biggles007** [comment]
This is showing as in Public Preview, the documentation suggests it's supported, but there are no examples/documentation that says how it can be consumed and the portal only allows for public DNS zones.

To align with this feature, will the ingress controller deploy (or have an option to) an internal load balancer only? We would like to deploy a private cluster, with no public IP, hence the requirement for Private DNS Zone integration.

**Comment by sabbour** [comment]
Docs updated: https://learn.microsoft.com/en-us/azure/aks/create-nginx-ingress-private-controller
