### ISSUE TITLE
[Question] Storage Class is already migrated to CSI but deprecated label 'failure-domain.beta.kubernetes.io/region' still exists in PV

### ISSUE THREAD

**Issue by angelo-mora** [Azure/AKS#3767]
We are encountering error in upgrading AKS version to 1.26.3 from 1.25.
![error1](https://github.com/Azure/AKS/assets/123621116/26579504-e8f0-4346-801f-78c0b4ee4cdc)

According to resolution from the error log, we should migrate to CSI storage but we are already migrated to CSI, but the deprecated label 'failure-domain.beta.kubernetes.io/region' is still present on our old PVs.

What actions should we take to update these PVs or proceed with the upgrading of our AKS version.

**Comment by mllab-nl** [comment]
My question would be: 
**What actions should we take to update these PVs**
I do not want to delay the problem, but would prefer to solve it NOW

**Comment by andyzhangx** [comment]
follow this guide to create new PV and new PVCs: https://learn.microsoft.com/en-us/azure/aks/csi-migrate-in-tree-volumes#migrate-disk-volumes

**Comment by andyzhangx** [comment]
only migrating storage class is not enough, the pv is still using in-tree driver and deprecated labels, we have csi migration logic in k8s that would make in-tree pv work but that does not mean everything is migrated to csi volume, pls follow doc to do the full migration, thanks.

**Comment by AllenWen-at-Azure** [comment]
@mllab-nl, unfortunately updating the existing PV/PVC to algin with CSI storage driver doesn't work. As Andy mentioned, we suggest to conduct the migration by creating new PV/PVC, please follow the best practice in [ https://learn.microsoft.com/en-us/azure/aks/csi-migrate-in-tree-volumes#migrate-disk-volumes](https://learn.microsoft.com/en-us/azure/aks/csi-migrate-in-tree-volumes#migrate-disk-volumes)
