### ISSUE TITLE
Get time when last started/stopped the AKS?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/AKS#3769]
Hello,

I am creating an automation script to start and stop non-prod AKS in odd hours, weekends or public holiday.

As far as I know, if AKS stopped or started within last 30 minutes then it is not a recommended approach to again fire a start/stop event on it. Is it possible to check when did start/stop event fire on AKS.

Kind Regards,
Tanul

**Comment by aritraghosh** [comment]
@smartaquarius10  Right now, the best way to get the start/stop time is through the Activity Log. This will have the information for the last 90 days. We are working on other ways to display this information.

**Comment by smartaquarius10** [comment]
@aritraghosh if possible could you please share the command/query for the same

**Comment by aritraghosh** [comment]
https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log?tabs=powershell
