### ISSUE TITLE
TLS handshake error occurred in registry when a deployment failed

### ISSUE THREAD

**Issue by rioriost** [Azure/AKS#377]
Using latest AKS, kubernetes 1.9.6 and kubectl 1.10.2.

I set up a registry on RHEL 7.5 with docker-distribution package, formerly docker-registry and configured it with TLS certification files from letsencrypt.

```
$ cat /etc/docker-distribution/registry/config.yml 
version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker-distribution/registry/htpasswd    

http:
    addr: :5000
    tls:
      certificate: /etc/letsencrypt/live/xxxx.xx/cert.pem
      key: /etc/letsencrypt/live/xxxx.xx/privkey.pem
```

I confirmed it worked well with docker clients on Linux and macOS as following steps.

```
$ docker login -u username -p password server:5000
$ docker pull nginx
$ docker tag nginx server:5000/nginx
$ docker push server:5000/nginx
```

And I confirmed my AKS cluster was working and able to pull and run the images from ACR according to a document [Authenticate with Azure Container Registry from Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-aks)

But it didn't work with my private registry mentioned above and got error messages as followings.
```
May 18 13:12:24 www registry: 2018/05/18 13:12:24 http: TLS handshake error from 52.176.58.213:49088: EOF
May 18 13:12:24 www registry: 2018/05/18 13:12:24 http: TLS handshake error from 52.176.58.213:49089: EOF
May 18 13:12:27 www registry: 2018/05/18 13:12:27 http: TLS handshake error from 52.176.58.213:41922: EOF
......
```

I guess AKS can't handle the certificate issued by letsencrypt.
Any ideas?

**Comment by sauryadas** [comment]
In general we believe that lets encrypt doesnt work on Azure ... try this documentation https://github.com/digeler/letsencrypt-application-routing-aks

if not use your own .tld and root domain.
