### ISSUE TITLE
desire expiration time for the admin kubeconfig file

### ISSUE THREAD

**Issue by YingZhongyuan** [Azure/AKS#3774]
**Is your feature request related to a problem? Please describe.**
As checked with azure support team, AKS admin kubeconfig can keep two years after getting with "az aks get-credentials --admin ..." command, which downloads a [legacy (non-Azure AD) cluster admin certificate into the user's .kube/config. It may cause unexpected leak. It is not secure for AKS, anyone can make change on AKS with the admin kubeconfig

**Describe the solution you'd like**
we want to set expiration time for AKS admin kubeconfig.

**Describe alternatives you've considered**

**Additional context**

**Comment by alexeldeib** [comment]
AFAIK, this is not possible as long as we provide any x509 certs because Kubernetes doesn't support any form of revocation without cert rotation: https://github.com/kubernetes/kubernetes/issues/18982

You _can_ trigger cert rotation, or just use AAD. Otherwise the expiry time is simply the cert expiry time.

**Comment by tdihp** [comment]
If the ask is on generating clientcert based kubeconfig (like az aks get-credential), I've made scripts for that: https://github.com/tdihp/myakshack/tree/main/workarounds/clientcert-user-by-csr

**Comment by phealy** [comment]
As Ace said earlier, there's no way to revoke the certs in Kubernetes, and we don't provide an option to generate them with shorter durations. The best way to have short duration tokens for AKS is to [enable managed Azure Active Directory authentication](https://learn.microsoft.com/en-us/azure/aks/managed-azure-ad) and [disable the local admin account](https://learn.microsoft.com/en-us/azure/aks/manage-local-accounts-managed-azure-ad).
