### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by RuTpasswd** [Azure/AKS#3777]
**Scenario**

I have an existing disk attached to VM running influx db engine. The engine is writing data to this attached disk. Currently, we moved to AKS and i want to attach the existing disk to be used by my new influx db deployed on AKS. 

**Question**
My question is to be able to attach this disk. I tried to the existing disk by creating a pv and pvc manually with yaml file. but always bring attachment issues. "error: "AttachVolume.Attach failed for volume"

**Comment by andyzhangx** [comment]
what's your pv and pvc config? and what's the pv name?
