### ISSUE TITLE
How to raise limit of pods (110) per node ?

### ISSUE THREAD

**Issue by przemolb** [Azure/AKS#378]
Hello,

I am using very, very small pods on our AKS cluster (testing purposes) and yesterday I hit the limit of pods per node - I guess this is 110 at the moment. I still have plenty of memory and CPU available but cannot run more pods.
Is there any way I can raise the limit ?

**Comment by przemolb** [comment]
I've just changed value in /etc/default/kubelet file and restarted service.

**Comment by AaronFriel** [comment]
That unfortunately doesn't allocate more IP addresses to the node. If you try running more than pods than the 30 pods each node is provisioned with, the Azure CNI networking option will run out of secondary IPs.

**Comment by przemolb** [comment]
Oops ! I was able to run more than 110 nodes ...
