### ISSUE TITLE
[BUG] KEDA (preview) has not PodPriorityClass

### ISSUE THREAD

**Issue by kratkyzobak** [Azure/AKS#3780]
**Describe the bug**
When enabling KEDA as managed extension to AKS (currently in preview), pods does not have any PriorityClass assigned.

**Environment:**
- Kubernetes version 1.26.3 with KEDA extension enables (currently 2.10.0 version installed)

**Additional context**
As KEDA is used to take control of horizontal scaling, it should not be victim of pod preemtion or scheduled as last component so priority class should be set.

**Comment by qpetraroia** [comment]
Hi @kratkyzobak, 

What scaler are you using?

**Comment by kratkyzobak** [comment]
@qpetraroia this is not scaler dependent

When you run `kubectl --namespace kube-system get pods -o custom-columns=NAME:.metadata.name,PRIORITY:.spec.priorityClassName,VALUE:.spec.priority` on any AKS with KEDA addon, you will see, that `keda-operator-*` pods does not have any priorityClass specified unlike others which are either system-node-critical or system-cluster-critical. Since there is no possibility to modify this using managed addon, you will end with KEDA operator running with zero priority. This is not good as operator should handle up/down scaling of other resources. In critical moments, there is possibility that `keda-operator-*` pods will not be running due to some workload with any priority will take precedence.

![image](https://github.com/Azure/AKS/assets/20162433/acc3d6b0-6000-4cd0-a628-956fab95c8a6)

**Comment by v-shenoy** [comment]
Hi, @kratkyzobak. Thanks for bringing this to our notice. We'll take a look into it.

**Comment by v-shenoy** [comment]
Fix for this has been merged. Should be out in the next AKS release. 
cc: @qpetraroia
