### ISSUE TITLE
Question - AKS Internal Load Balancer, Web App & Private DNS Zone?

### ISSUE THREAD

**Issue by omgsarge** [Azure/AKS#379]
Quick question around support or sanity of the following?

I am planning on using public web apps for API gateways, with downstream services hosted privately within AKS. I am planning on using the VNET Integration feature for web apps to grant them access to the private network that AKS will reside in.

What I would like is for upstream teams to be able to create private AKS services exposed over an internal load balancer, and for the upstream web apps to be able to reference these by DNS, instead of the ILB IP Address.

Is it possible to combine an Azure Private DNS Zone, with AKS inside a Virtual network to create this kind of setup? If not would there be a decent alternative to requiring the web apps to need to work off the knowledge of IP addresses of the load balancers?

 Cheers!

**Comment by nphmuller** [comment]
Sounds to me like you should expose your k8s services over an internal load balancer (Which is in the aks docs). 

After that you can make manually at the dns entry pointing to the private ip of the service. Or you could look into ExternalDNS to automate to creation of the DNS entries.

Please note that there are some bugs which prevent this from working correctly atm, but the aks team noted them as fixed and they're rolling out over the coming week.

Sounds like the exact solution we're going for atm, so I hoped I saved you some time with this. :)

**Comment by omgsarge** [comment]
Excellent, this is exactly how I envisaged it working and it does create a pretty great setup for teams to drop services into our cluster and give out DNS addresses (we use ExternalDNS already but for public DNS, I was hoping ExternalDNS would be usable for the same kind of setup for Private DNS zone).

Out of interest, is there a link to the trackers for the bugs which would prevent this right now?

Thanks very much!

**Comment by nphmuller** [comment]
We haven't tested it for Private DNS Zone yet, only public. But I see why private zones wouldn't work.

I'll look up the specific issues later, but from the top of my head:
- Service Principal doesn't have access to VLAN. Documentation issue solved by manually giving the SP rights to the VLAN.
- AKS tries to create the internal load balancer in the incorrect VLAN (not the one specified, but the one incorrectly created by AKS).

**Comment by Mumrau** [comment]
I'm facing the same issue as @nphmuller , AKS fails to create the Internal Load Balancer due to a wrong newtorking configuration, while it's been specified at creation with subnets to use, which belongs to the desired vnet.

**Comment by bramvdklinkenberg** [comment]
The issue with the internal LB not connecting to the custom vnet has been fixed. But only with newly deployed clusters. So you have to delete your cluster en redeploy it.

**Comment by strtdusty** [comment]
This seems like it would compliment your solution and update the dns zone automatically.  We are looking at doing the same once the internal dns zones are GA
https://github.com/kubernetes-incubator/external-dns

**Comment by omgsarge** [comment]
Cool! Yes we are using external dns for our public zone, planned on using
it for private zone too which should be a pretty slick setup!

**Comment by seanmck** [comment]
It doesn't look like there's any more action required here, so closing.
