### ISSUE TITLE
[Feature] Add possibility to define extension provider in Istio add-on

### ISSUE THREAD

**Issue by ddx3r** [Azure/AKS#3791]
**Is your feature request related to a problem? Please describe.**

I would like to be able to define an extension provider in Istio mesh config, so I can configure the external authorization feature in authorization policies.

**Describe the solution you'd like**

possibility to edit the resource with mesh config or way to add extension providers to mesh config.

**Comment by shashankbarsin** [comment]
It's now possible to edit meshconfig - https://learn.microsoft.com/en-us/azure/aks/istio-meshconfig
