### ISSUE TITLE
[BUG] Eraser AKS Add On Tolerations Missing

### ISSUE THREAD

**Issue by sarahecraddock** [Azure/AKS#3799]
**Describe the bug**
When deploying the Eraser AKS add on in a cluster where the node pools have taints applied, the eraser controller gets stuck in pending due to the correct tolerations not being applied to allow it to be scheduled.

**To Reproduce**
1. Deploy an AKS cluster with system node pool and one or more user node pools with taints applied to all user node pools
2. Enable Eraser
3. Eraser controller fails to schedule

**Expected behavior**
Eraser pods have the correct tolerations applied to allow them to be scheduled on the required node pools. This should apply to both the controller and the worker pods.

**Screenshots**
![image](https://github.com/Azure/AKS/assets/61050444/c1b07bcf-3a32-4c7e-b535-edaf509667da)
![image](https://github.com/Azure/AKS/assets/61050444/ec51fd57-2cfa-49cf-bafd-a92a5d651071)

**Environment (please complete the following information):**
 -  CLI Version: NA
 - Kubernetes version: 1.26.3
 - CLI Extension version: NA
 - Browser: NA

**Additional context**
[Previous issue](https://github.com/Azure/eraser/issues/785) raised with the Eraser team, but they have indicated that this is an issue with the AKS add on not Eraser.

**Comment by sarahecraddock** [comment]
@jiashun0011 Tagging you for continuity, as Sertac had tagged you on the previous issue I had raised.

**Comment by CocoWang-wql** [comment]
Hello @sarahecraddock  we are investigating it and will update once it is fixed. Thanks for the feedback.

**Comment by jiashun0011** [comment]
Hey @sarahecraddock, we created a workitem for this issue and will fix it asap.

**Comment by sarahecraddock** [comment]
Thank you!

**Comment by CocoWang-wql** [comment]
Close this one as the issue was fixed.
