### ISSUE TITLE
[BUG] AKS update schedule being ignored when using the node image only update channel

### ISSUE THREAD

**Issue by rrychen** [Azure/AKS#3809]
Description
We are attempting to use the Planned Maintenance preview feature so we can line up AKS patching with our normal monthly patch cycle. We initially selected the "Stable Kubernetes" version channel and the schedule worked as expected. However, we discovered that if there is no new stable Kubernetes version, then the update stops immedaitely and wont update the node images. Given that node images update rather more often that the stable kubernetes version we elected to swap the update channel to "Node Image only" and update the Kubernetes version manually as required. As soon as the change of channel happened it immediately updated the node images to the latest version - quite outside the scheduled patch window. 

Initially we thought this might be a one-off because of the change of channel. This month however, the node images were updated yesterday morning (19th July) well outside the scheduled time of next Tuesday morning (25th July). I am aware that this is a preview feature, but this seems like a fairly big deficiency. This appears to have happened to all our clusters - I'm attempting to find out exactly when the images in those other clusters were updated now.

Reproduction
Set the cluster auto-update channel to "Node Image" only
Set a planned maintenance schedule  to a point the far future - a month or more
Check if the node image gets updated outside of the set schedule

Expected Behaviour 
Patching happens when the schedule says it should

Environment 
 -  CLI Version: 2.50.0
 - Kubernetes version: 1.25.6
 - CLI Extension version: aks-preview 1.0.8

**Comment by rouke-broersma** [comment]
@rrychen are you using the `default` maintenance schedule name? That schedule does not apply to node image updates, only to weekly kubernetes control plane (not nodes!!!) updates.

**Comment by rrychen** [comment]
Thanks for that. I have reset the schedule with the new name. I will say though that the need for the different names is not clear in the available documentation. The doco seems only to refer to "default" or "aksManagedAutoUpgradeSchedule" neither of which really suggests "aksManagedNodeOSUpgradeSchedule" is an option for the node OS update type. 

I wont be able to check the results until next month when the schedule is supposed to trigger the update.

Thanks for the help

**Comment by aritraghosh** [comment]
@rrychen  Is this good to close?

**Comment by rrychen** [comment]
If we can hold it until the 15th that would be good, thats when the next scheduled mode image update is. So far it appears as if the changing the name of the schedule has worked, but we will know for certain then.


Robert Rychen

Senior System Engineer

University IT  •  M463, Perth WA 6009 Australia

T +61 8 6488 1746  •  E ***@***.***

[http://static.weboffice.uwa.edu.au/visualid/graphics/email/uwa-crest-sig-pad.gif]<http://www.uwa.edu.au/university-campaigns-resources/emailsig-resources/uwa-logo/>

[http://static.weboffice.uwa.edu.au/visualid/graphics/email/esig-fb-pad.gif]<http://www.uwa.edu.au/university-campaigns-resources/emailsig-resources/facebook>[http://static.weboffice.uwa.edu.au/visualid/graphics/email/esig-larry-pad.gif]<http://www.uwa.edu.au/university-campaigns-resources/emailsig-resources/twitter>[http://static.weboffice.uwa.edu.au/visualid/graphics/email/esig-youtube-pad.gif]<http://www.uwa.edu.au/university-campaigns-resources/emailsig-resources/youtube>

[http://static.weboffice.uwa.edu.au/visualid/graphics/email/uwa-email-campaign.gif]<http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/campaign>

________________________________

**Comment by kaarthis** [comment]
Closing this as we have GAed the full suite of planned maintenances as of Aug 21 incl Default, nodeosupgrade and Autoupgrade configurations possible separately.

**Comment by kaarthis** [comment]
https://learn.microsoft.com/en-us/azure/aks/planned-maintenance
