### ISSUE TITLE
KEDA Addon

### ISSUE THREAD

**Issue by qpetraroia** [Azure/AKS#3816]
The Kubernetes Event-driven Autoscaling (KEDA) is a single-purpose and lightweight component that strives to make application autoscaling simple and is a CNCF Incubation project.

It applies event-driven autoscaling to scale your application to meet demand in a sustainable and cost-efficient manner with scale-to-zero.

The KEDA add-on makes it even easier by deploying a managed KEDA installation, providing you with [a rich catalog of 50+ KEDA scalers](https://keda.sh/docs/scalers/) that you can scale your applications with on your Azure Kubernetes Services (AKS) cluster.

**Comment by mblaschke** [comment]
isn't that a duplicate of #1479?

**Comment by dpaardenkooper** [comment]
We see that KEDA is now graduated on the CNCF. Is there a time stamp that KEDA plugin will go GA?

**Comment by tomkerkhove** [comment]
See https://github.com/Azure/AKS/issues/1479:

> GA is around the corner and should come soon, sit back and wait!

**Comment by tomkerkhove** [comment]
@qpetraroia I think we can close this one?
