### ISSUE TITLE
[Feature] 100% uptime with VMSS UpdateInstances

### ISSUE THREAD

**Issue by piyushdatazip** [Azure/AKS#3818]
**Is your feature request related to a problem? Please describe.**
After changing VMSS SKU, updating instances takes time upto 5-6 mins. this results into a downtime for services which results into bad UX experience. Plus updating Instance SKU do not reflect into the System labels of Kubernetes Node and Pod details, labels such as `beta.kubernetes.io/instance-type`

**Describe the solution you'd like**
Instead of changing SKU for each running instance behind the scenes, new Node/Instance should be spawned with targeted SKU, as soon as new Node is ready, Pods should be spawned on to this new Node, and after Pod runs successfully, our previous Instance should be turned down.

This results into only 3-4 seconds of downtime, Safer approach as well incase due to some internal Azure issue new Node could not be spawned our previous Instance is still up and running

**Describe alternatives you've considered**
It could be done manually by creating a new instance and turning down the last one. But turning down requires InstanceID which GO SDK doesn't have, I need to use graph APIs to get the instanceIDs, basically increasing steps to do the deed.
As user of Azure I expect this to be a must behaviour since other Cloud Providers do the same.

**Additional context**

**Comment by piyushdatazip** [comment]
hi @sabbour I wanted to grab your attention onto this feature. So tagging you here.

**Comment by phealy** [comment]
@piyushdatazip are you making direct changes on the VMSS resource? Please note from the [AKS support policy](https://learn.microsoft.com/en-us/azure/aks/support-policies#shared-responsibility):

> Any modification made directly to the agent nodes using any one of the IaaS APIs renders the cluster unsupportable.

The AKS supported method of doing this is to create a new node pool on the new SKU and then delete the old one; this results in the new nodes being online and the short failover duration you requested.

**Comment by piyushdatazip** [comment]
> @piyushdatazip are you making direct changes on the VMSS resource?

Yes @phealy  I am updating the VMSS SKU directly, I'll try implementing what you've suggested. Thank you!
