### ISSUE TITLE
ILB not connected to the custom vnet

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/AKS#382]
I have an AKS cluster deployed with a custom VNET. When I deploy the voting app icm with an internal load balancer it creates a load balancer but it is not connected to the custom vnet, but instead it is connected to a vnet (10.0.0.0/8) in the MC resource group. 
I would expect (and like to see) that the ILB will be automatically connected to the custom vnet.

**Comment by AdamPaternostro** [comment]
The ILB generates the following error: Error creating load balancer (will retry): failed to ensure load balancer for service default/config: timed out waiting for the condition

**Comment by DDebray** [comment]
I think this is a duplicate of https://github.com/Azure/AKS/issues/221 . I had a similar issue and the support told me that they release the fix any day now.

**Comment by bramvdklinkenberg** [comment]
See https://github.com/Azure/AKS/issues/221
