### ISSUE TITLE
Upgrade of K8s Version does too many node deployments and drains[BUG]

### ISSUE THREAD

**Issue by BenHesketh21** [Azure/AKS#3820]
**Describe the bug**
When we upgrade K8s versions on any of our clusters, AKS brings up new nodes with the new version and drains the nodes as you would expect, however when the last nodes of the old version are deleted, when you would expect the upgrade to finish, for each node pool AKS deploys one more node and drains the oldest node with the new version and then finishes. 

**To Reproduce**
1. Upgrade an AKS cluster the standard way through the Azure Portal

**Expected behavior**
Stop upgrading when all the nodes match the new version

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes version: latest upgrade was from 1.24.10 -> 1.25.6

**Comment by carvido1** [comment]
Hello there @BenHesketh21 .

Can you add more context to this issue? Like:

* Do you use autoscaling for nodepools ?
* Which are your max surge values for each nodepool ?
* Do you have tolerations on your pods/deployments ?

To replicate the issue and validate the bug more details are required, my recommendation is to provide the AKS configuration as well as the different manifests that you have deployed.

Best regards.

**Comment by kevinharing** [comment]
I noticed this as well. At least on the system node pool. We use 3 nodes minimum with auto-scaling to 10. After replacing the 3 nodes, it will spin up the 4th node and a little later spin it down again. The complete workload already runs on those 3 nodes at that time. I have the max surge set to the default for this specific node pool.

**Comment by kaarthis** [comment]
This issue was fixed recently tagging @wenjungaogaogao to confirm this . This should not happen for subsequent upgrades recently , let us know if the problem persists.
