### ISSUE TITLE
[BUG] All completed pod are suddenly cleaned by AKS.

### ISSUE THREAD

**Issue by pockyhe** [Azure/AKS#3823]
**Describe the bug**
We are monitoring our AKS and find all completed pod will be suddenly cleaned by AKS. We thought the high memory caused it and upgraded high memory SKU. However, it happened again. I want to know which threshold will cause this happen.

**To Reproduce**
1. Run command '...'
2. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/Azure/AKS/assets/64390829/9d6d3d73-a591-46b1-a0b3-32785e5f663b)

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22]
 - Kubernetes version [e.g. 1.24.3]
 - CLI Extension version [e.g. 1.7.5] if applicable
 - Browser [e.g. chrome, safari] is applicable
AKS version is 1.26.0

**Additional context**

**Comment by justindavies** [comment]
Is this a Job?  And have you set ttlSecondsAfterFinished in the pod spec?

**Comment by pockyhe** [comment]
They are not Job, and I didn't set ttlSecondsAfterFinished. if ttlSecondsAfterFinished enables, pod will be clean after TTL. However, my situation is that all completed pods in all namepsaces are cleaned at the same time
