### ISSUE TITLE
[BUG] Eraser / Image Cleaner pods terminate with status `OutOfCpu`

### ISSUE THREAD

**Issue by heoelri** [Azure/AKS#3824]
**Describe the bug**
We've the Image Cleaner enabled on AKS cluster with two node pools and some of our eraser pods are running out of cpu resources (Status: `OutOfCpu`).

**To Reproduce**
1. Run command `kubectl get pods -n kube-system`
2. See error

```text
eraser-aks-systempool-18093041-vmss000000-xwd8n        0/3     Completed   0                  7h56m
eraser-aks-systempool-18093041-vmss000005-9mvml        0/3     OutOfcpu    0                  7h56m
eraser-aks-workloadpool-41010482-vmss000000-mbpjm      0/3     Completed   0                  7h56m
eraser-aks-workloadpool-41010482-vmss000007-k8fxr      0/3     Completed   0                  7h56m
eraser-controller-manager-6cf4b7cf48-748vz             1/1     Running     0                  12d
```
The `imageCleaner` addon is enabled via the `securityProfile` configuration in bicep:

```bicep
    securityProfile: {
      imageCleaner: { 
        enabled: true
        intervalHours: 24
      }
      workloadIdentity: {
        enabled: true
      }
    }
```

**Expected behavior**
As a managed addon that does not offer additional configuration options I'd expect the imagecleaner to work as expected.

Is it possible to adjust either the cpu request? If not is the only alternative to ensure that enough cpu (request for the `trivy-scanner` container in the eraser pod is set to `500m`) is available? If yes, what's the recommended approach to do that? 

**Screenshots / Logs**

```console
kubectl get nodes              

NAME                                   STATUS   ROLES   AGE     VERSION
aks-systempool-18093041-vmss000000     Ready    agent   12d     v1.26.3
aks-systempool-18093041-vmss000005     Ready    agent   12d     v1.26.3
aks-systempool-18093041-vmss00000a     Ready    agent   7h10m   v1.26.3
aks-workloadpool-41010482-vmss000000   Ready    agent   12d     v1.26.3
aks-workloadpool-41010482-vmss000007   Ready    agent   12d     v1.26.3
```

```console
kubectl top nodes

NAME                                   CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
aks-systempool-18093041-vmss000000     289m         7%     5273Mi          103%      
aks-systempool-18093041-vmss000005     287m         7%     4825Mi          94%       
aks-systempool-18093041-vmss00000a     193m         5%     4483Mi          88%       
aks-workloadpool-41010482-vmss000000   233m         6%     6005Mi          117%      
aks-workloadpool-41010482-vmss000007   173m         4%     4406Mi          86%  
```

**Environment (please complete the following information):**
 - CLI Version: 2.50.0
 - Kubernetes version: 1.26.3

**Additional context**

No additional context.

**Comment by heoelri** [comment]
Adjusting the `eraser-manager-config` configmap reducing the cpu request for the `scanner` container solves the issue temporarily but question is if a) this is getting overriden by the AKS addon as part of for example an upgrade b) if this is the recommended approach. What other, recommended, options do we have to ensure that the requested `500m` cpu are available on each node when the eraser pods are getting scheduled?

**Comment by justindavies** [comment]
@miwithro

**Comment by kaarthis** [comment]
Closing this issue as there are no further follow ups to the resolution provided above.
