### ISSUE TITLE
[Feedback/Issue] Network observability feature has very high CPU requests

### ISSUE THREAD

**Issue by audunsolemdal** [Azure/AKS#3826]
**Describe your scenario**
I ran the `az aks upgrade (..) --enable-network-observability` command to test the network observability plugin in my dev-cluster

I notice that the kappie-agent daemonset has only set limits to 500m cpu and memory: 300mi. No requests are set. This leads to cpu requests being == limit of cpu. This is way too high IMO. My kappie-agent pods are currently running at 0% of cpu requests while essentially hijacking 25% of my node VMs CPU.

**Feedback**

Either set default cpu requests for the kappie-agent DS  or provide an option to disable network observability via CLI.

**Comment by vakalapa** [comment]
Thank you for the feedback, we will reduce it the CPU to lower amount.
