### ISSUE TITLE
AKS 1.27.1 Core Dns Autoscaler Pod Using Deprecated Annotations seccomp.security.alpha.kubernetes.io/pod

### ISSUE THREAD

**Issue by MageshSrinivasulu** [Azure/AKS#3829]
Kubernetes 1.27 has deprecation and the following annotations `seccomp.security.alpha.kubernetes.io/pod` and `container.seccomp.security.alpha.kubernetes.io` should not be used https://kubernetes.io/blog/2023/03/17/upcoming-changes-in-kubernetes-v1-27/#support-for-deprecated-seccomp-annotations. 

But the core DNS cluster autoscaler pods that are getting deployed as part of AKS are still using it. Is it expected?

![image](https://github.com/Azure/AKS/assets/79187874/81266f75-c188-493f-a527-18a616f3ce1e)

![image](https://github.com/Azure/AKS/assets/79187874/39389d20-c23d-4b18-aab1-4bf727f29f88)

**Comment by robbiezhang** [comment]
@MageshSrinivasulu , thanks for reporting this issue. AKS set the securityContext on the managed system pods as well.

```
  securityContext:
    seccompProfile:
      type: RuntimeDefault

```

This annotation is just for backward compatible. It doesn't have any impact or side effect on 1.27.
