### ISSUE TITLE
[Question] Syslog collection with Container Insights

### ISSUE THREAD

**Issue by hakabo** [Azure/AKS#3830]
**Describe scenario**
I attempted to try out the "Syslog collection with Container Insights" preview [feature ](https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-syslog)by enabling it via the portal. 

**Question**
The deployment failed (RequestDisallowedByPolicy) due to us having enabled the "Azure Kubernetes Service Clusters should have local authentication methods disabled" policy.   
I do not see this has a requirement and we wouldn't want to disable this policy either. Is this expected?

**Comment by ganga1980** [comment]
Hi, @hakabo,  We are discussing about this issue with ARM and AKS team on how to address this. issue here, Portal uses the ARM template (which uses Partial PUT) which doesn't have required fields which Policy expecting. As work around, can you try using the azure CLI - https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-syslog#using-azure-cli-commands

**Comment by ganga1980** [comment]
Hi, @hakabo - We are rolling out the Portal fix and tentative ETA should be by end of this month.

**Comment by vdiec** [comment]
Hi @hakabo - the fix has been rolled out! Thanks
