### ISSUE TITLE
[BUG] AKS allowing cluster downgrade to prior version, but per documentation downgrade is not supported 

### ISSUE THREAD

**Issue by tsivachi** [Azure/AKS#3831]
**Describe the bug**
Looks like Azure is letting downgrade for control plane to happen for one prior version that’s available. This also leaves existing node pool on a higher version than control plane which is another side effect observed

**To Reproduce**
The AKS cluster had been created using terraform and pipelines.
Initial value of Kubernetes version while creating AKS cluster : 1.25.6

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/ts6388/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/ts6388/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/ts6388/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

Cluster version | Kubernetes version change attempted via tf variables | Control plane version update Successful | Failure if returned any during tf apply | Node pool version updated?? | Node pool version after pipeline run
-- | -- | -- | -- | -- | --
1.25.6 | 1.24 | No | Code="BadRequest"   Message="Downgrading is not allowed because the minor version of   specified kubernetes version 1.24 is lower than minor version of current   kubernetes version 1.25.6." | No | 1.25.6
1.25.6 | 1.25.5 | Yes |   | No | 1.25.6
1.25.5 | 1.24.10 | Yes |   | No | 1.25.6

</body>

</html>

Sharing output of AKS cluster versions post downgrade below via az commands and it can be observed that control plane is at lower version than nodepool's

$az aks show --name aksjskp-eastus2-dev-app-aks --resource-group aksjskp-eastus2-dev-app-rg | grep -i version
WARNING: The behavior of this command has been altered by the following extension: aks-preview
      "currentOrchestratorVersion": "1.25.6",
      "nodeImageVersion": "AKSUbuntu-2204gen2containerd-202307.04.0",
      "orchestratorVersion": "1.24.10",
  "currentKubernetesVersion": "1.25.6",
  "kubernetesVersion": "1.24.10",
      "version": "v1"

```bash
$ az aks show --name aksjskp-eastus2-dev-app-aks --resource-group aksjskp-eastus2-dev-app-rg -o table
The behavior of this command has been altered by the following extension: aks-preview
Name                          Location    ResourceGroup               KubernetesVersion    CurrentKubernetesVersion    ProvisioningState
---------------------------  ----------  --------------------------  -------------------  --------------------------  -------------------
aksjskp-eastus2-dev-app-aks  eastus2     aksjskp-eastus2-dev-app-rg  1.24.10              1.25.6                      Succeeded
```

**Expected behavior**
AKS should have rejected downgrade to prior available version as it does while attempting 1.25.6 to 1.24 

**Environment (please complete the following information):**
 -  CLI Version 
  -  "azure-cli": "2.50.0",
      "azure-cli-core": "2.50.0",
 - Kubernetes version 1.25.6

**Additional context**
AKS PG had investigated this case and shared the below. Opening up this bug for tracking purpose

"
No it didn't actually downgrade, it's just we silently allowed the input instead of rejecting it with bad request.
Actually the orchestrator version is maintained at 1.25.6 which we can confirm. 

We are evaluating how we can address this with an upfront message / error on validation to ensure no confusion comes up in future. "

**Comment by palma21** [comment]
Per your last output it's actually not downgraded. It's still in 1.25.6. Current is what's there, Kubernetes version is the write property that you PUT. 
Can you confirm with kubectl --version what the server is?

Edit: See that you actually already had that response, we've added validation to properly reject. Thanks!

**Comment by kaarthis** [comment]
Closing per @palma21 comment above and since there is no follow up.
