### ISSUE TITLE
[Feature] AKS Node Pool auto scale up options

### ISSUE THREAD

**Issue by joedborg** [Azure/AKS#3834]
**Is your feature request related to a problem? Please describe.**
AKS's nodepool autoscaler doesn't have any scale up parameters.

**Describe the solution you'd like**
I'd like scale up variables added, such as pre-emptive scale up thresholds, amount of nodes to add per scale up event etc.

**Describe alternatives you've considered**
Leveraging some of K8s' pod priority to fake scale up thresholds.

**Additional context**
None.

**Comment by olsenme** [comment]
Which specific settings are you referring to that we don't have listed in [cluster autoscaler profile](https://learn.microsoft.com/en-us/azure/aks/cluster-autoscaler#change-the-cluster-autoscaler-settings)
