### ISSUE TITLE
AKS flux extension installation with azure ad rbac enabled failed - unauthorized

### ISSUE THREAD

**Issue by jakubramut** [Azure/AKS#3835]
I created an AKS cluster with an authentication option (Azure AD authentication with Azure RBAC enabled). When I try to install the flux extension I receive an error:
```
The extension operation failed with the following error:  Request failed to https://management.azure.com/subscriptions/***/resourceGroups/***/providers/Microsoft.ContainerService/managedclusters/***/extensionaddons/flux?api-version=2021-03-01. Error code: Unauthorized. Reason: Unauthorized.{"error":{"code":"InvalidAuthenticationToken","message":"The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant."}}.
```
The cluster has a custom managed identity assigned to the kubelet.
Tried to configure it with a terraform or manually with az cli but same error. Me (az cli) and the sp (terraform) and kubelet managed identity have necessary roles: **Contributor** and **Azure Kubernetes Service RBAC Cluster Admin**.

What could be wrong, does the extension support installation on azure ad rbac enabled cluster?

**Comment by jakubramut** [comment]
It works - I agree but only when I use a built-in managed identity for kubelet.
When I try to create a mui upfront, assign into kubelet then during the installation I faced an issue. 
I did it based on the description from: https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-use-gitops-flux2?tabs=azure-cli#using-kubelet-identity-as-authentication-method-for-aks-clusters.
I tried to enable gitops extension through the CLI (by me) or via pipeline (with a dedicated SP).

**Comment by Blinq-SanderBlom** [comment]
Hi! 

Is there any progress on this issue? 

We are facing the same problem when we try to deploy the extension with either Terraform or az-cli. You can reproduce this by deploying an AKS cluster and then run: `az k8s-extension create -n "flux" -t managedclusters -g kube -c democluster --extension-type microsoft.flux --subscription SubscriptionIdHere`. I have owner access on the subscription and also assigned the `Azure Kubernetes Service RBAC Cluster Admin` and `Azure Kubernetes Service Cluster Admin Role` to myself on the cluster
