### ISSUE TITLE
[BUG] Random control plane connection issues

### ISSUE THREAD

**Issue by SeWieland** [Azure/AKS#3838]
**Describe the bug**

I am am currently getting more and more "connection refused" errors whenever using kubectl against my private AKS.
The issues started to occure sometimes and are now happening every few requests, making it impossible to deploy our applications.

**To Reproduce**

Running the following command _multiple times_ produced _different outputs_:
`curl -v 'https://private-aks-random.example.privatelink.westeurope.azmk8s.io:443'`

**Expected behavior**
Some output like:

```log
* Rebuilt URL to: https://private-aks-random.example.privatelink.westeurope.azmk8s.io:443/
*   Trying 172.16.186.132...
* TCP_NODELAY set
* Connected to private-aks-random.example.privatelink.westeurope.azmk8s.io (172.16.186.132) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
```
=> CURL established a connection

**Actual behavior**

After a few requests (all successfully connecting) the following output can be seen

```log
* Rebuilt URL to: https://private-aks-random.example.privatelink.westeurope.azmk8s.io:443/
*   Trying 172.16.186.132...
* TCP_NODELAY set
* connect to 172.16.186.132 port 443 failed: Connection refused
* Failed to connect to private-aks-random.example.privatelink.westeurope.azmk8s.io port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to private-aks-random.example.privatelink.westeurope.azmk8s.io port 443: Connection refused
```

**Environment (please complete the following information):**
 - Kubernetes version 1.26.6

**Additional context**
AKS pricing tier: standard.
The VM used to connect to the AKS is running in the same VNET.

Note.. Also the "kube-system/konnectivity-agent" pods produces logs like `"error dialing backend" err="dial tcp 172.16.186.137:19100: connect: connection refused" dialID=9170277598760106307` but I have no idea if this is related or not at all.

**Comment by kaarthis** [comment]
@merooney  @aritraghosh  any updates on the above please ?

**Comment by SeWieland** [comment]
In the end it turned out to be a networking issue inside the VNET we were deploying into.
There was some sort of virtual appliance added inside the route table that we were not expecting which was obviously dropping connections.
Double-check your networking setup if you are experiencing similar issues!
