### ISSUE TITLE
Cluster Auto-upgrade Channel for LTS

### ISSUE THREAD

**Issue by dmealo** [Azure/AKS#3839]
When [Kubernetes LTS](https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#long-term-support-lts) (currently 1.27) is available, will there be a matching upgrade channel for Cluster Auto-upgrade? Or which one will this be? Will it replace Stable? Those seem like different targets though.

**Comment by haitch** [comment]
LTS disable Rapid/Stable channel, NodeImage and Patch channel are allowed in LTS phase.

**Comment by dmealo** [comment]
Thanks for the closure. It looks like Patch channel is automatically applied when enabling LTS - based on the LTS [docs](https://learn.microsoft.com/en-us/azure/aks/long-term-support#after-enabling-lts-my-clusters-autoupgradechannel-has-changed-to-patch-channel) now updated since this issue was raised.
