### ISSUE TITLE
[BUG] Unable to add Dapr extension to AKS cluster

### ISSUE THREAD

**Issue by tj-cappelletti** [Azure/AKS#3842]
We've deployed an AKS cluster using the Bicep that comes from the [AKS Landing Zone Accelerator](https://github.com/Azure/AKS-Landing-Zone-Accelerator) into the West US 2 region. We need to add Dapr to the cluster so we are following the instructions [here](https://learn.microsoft.com/en-us/azure/aks/dapr). We've consistently been unable to add this extension despite recreating the cluster several times and trying different versions of Kubernetes. The most recent attempt has the extension trying to create for over 12 hours and when you use the CLI to query for the status the `provisioningState` simply says `Creating`. When you use `kubectl` to list the deployments, there is no entry for Dapr.

**To Reproduce**
1. Deploy an AKS cluster using the Bicep in the [AKS Landing Zone Accelerator](https://github.com/Azure/AKS-Landing-Zone-Accelerator)
2. Use this command to install the Dapr extension, as per the doc [Dapr extension for Azure Kubernetes Service (AKS) and Arc-enabled Kubernetes](https://learn.microsoft.com/en-us/azure/aks/dapr)
```shell
az k8s-extension create --cluster-type managedClusters \
--cluster-name name-of-cluster \
--resource-group name-of-rg \
--name dapr \
--extension-type Microsoft.Dapr
```
3. Wait 15 minutes and run this command:
```shell
az k8s-extension list --cluster-type managedClusters --cluster-name name-of-cluster -g name-of-rg
```
The output should show that the extension is still creating. Then run:
```shell
kubectl get deployments --all-namespaces=true
```
You will see that a Dapr deployment has yet to start. We've let the extension "create" for over 12 hours and yielded no meaningful information.

**Expected behavior**
The extension should install successfully in under 10 minutes based on testing in other situations

**Screenshots**
Ran this command at 9:40am EST:
```shell
az k8s-extension list --cluster-type managedClusters --cluster-name name-of-cluster -g name-of-rg
```
Status of the extension output:
```json
[
  {
    "aksAssignedIdentity": {
      "principalId": "00000000-0000-0000-0000-000000000000",
      "tenantId": null,
      "type": null
    },
    "autoUpgradeMinorVersion": true,
    "configurationProtectedSettings": {},
    "configurationSettings": {},
    "currentVersion": "1.11.2",
    "customLocationSettings": null,
    "errorInfo": null,
    "extensionType": "microsoft.dapr",
    "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/name-of-rg/providers/Microsoft.ContainerService/managedClusters/name-of-cluster/providers/Microsoft.KubernetesConfiguration/extensions/dapr",
    "identity": null,
    "isSystemExtension": false,
    "name": "dapr",
    "packageUri": null,
    "plan": null,
    "provisioningState": "Creating",
    "releaseTrain": "Stable",
    "resourceGroup": "name-of-rg",
    "scope": {
      "cluster": {
        "releaseNamespace": "dapr-system"
      },
      "namespace": null
    },
    "statuses": [],
    "systemData": {
      "createdAt": "2023-08-08T22:14:24.823827+00:00",
      "createdBy": null,
      "createdByType": null,
      "lastModifiedAt": "2023-08-08T22:14:24.823827+00:00",
      "lastModifiedBy": null,
      "lastModifiedByType": null
    },
    "type": "Microsoft.KubernetesConfiguration/extensions",
    "version": null
  }
]
```

**Environment (please complete the following information):**
 -  CLI and Extension Versions:
 ```json
{
  "azure-cli": "2.51.0",
  "azure-cli-core": "2.51.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "k8s-extension": "1.4.2"
  }
}
```
 - Kubernetes version: 1.27.3 and 1.26.3

**Additional context**
During our testing to try and reproduce this issue, a common theme to reproduce this seems to be a cluster that has Azure AD authentication with Azure RBAC will result in the extension never getting installed. It's hard to rule definitively since the cluster is being deployed via the AKS landing zone accelerator.

**Comment by qpetraroia** [comment]
hi @tj-cappelletti, 

Have you opened a [support ticket](https://support.microsoft.com/en-us/topic/contact-microsoft-azure-support-2315e669-8b1f-493b-5fb1-d88a8736ffe4#:~:text=Get%20answers%20in%20Azure%20forums.%201%20Connect%20with,3%20Check%20the%20status%C2%A0of%20Azure.%20Search%20Azure%20documentation.)? The Dapr team should be able to help here.

**Comment by kaarthis** [comment]
Closing as no response from author for more than 3 weeks.  Please open Support ticket if problem persists.
