### ISSUE TITLE
[BUG] Failed to update node pool with PremiumV2_LRS volume

### ISSUE THREAD

**Issue by stevehipwell** [Azure/AKS#3844]
**Describe the bug**
We have a cluster with 3 node pools which had a failed node upgrade using the new maintenance pattern. The node pools all have a node with an attached PremiumV2_LRS disk (via the managed Azure Disk CSI). The automated node upgrade maintenance errored out and did not run again. The first node pool to upgrade succeeded in the AKS console but was shown as erroring in the VMSS console, the second node pool failed in AKS and the third didn't even start.

The following error seems to be the first error we experience which is followed by VMs ending up in a failed state.

> Failed to update node pool
Failed to update the node pool 'system3' in the Kubernetes service 'my-cluster'. Error: Code="BadRequest" Message="Attaching data disk(s) with 'PremiumV2_LRS' storage account type requires the VMSS to be stopped (deallocated) first. (This is a temporary limitation of the management mode optimized for fast disk Attach/Detach.)"

After manually running the node pool upgrade again (new VMs have been released since the failure) I'm left with numerous broken VMs with disks attached that can't be cleaned up. Effectively this has broken the whole cluster. Also the AKS console, VMSS console and kubectl all disagree about the state of the system.

**To Reproduce**
It looks like this is reproducible, although you'd need to wait for a new VM version to test it, as we now have a second cluster with the same issue caused by a manual node upgrade. This cluster was opted in for node upgrades via the old cluster upgrade channel (the first cluster was using the new node channel) but hasn't had any that either succeeded or failed for about a month.

**Expected behavior**
Node upgrades should work correctly, everything we're doing is as described in the documentation.

**Screenshots**
n/a

**Environment (please complete the following information):**
 -  CLI Version n/a
 - Kubernetes version v1.26.3
 - CLI Extension version n/a
 - Browser n/a

**Additional context**

**Comment by Tolsto** [comment]
We are seeing the same issue after upgrading to 1.25. It also happens with a new VMSS that was created after the upgrade. We run into the error when trying to scale it up for the first time.

**Comment by stevehipwell** [comment]
I believe there is a fix for this but I don't have any information on the timeframe.

**Comment by andyzhangx** [comment]
this issue should be fixed in the backend, pls try again, thanks.
