### ISSUE TITLE
[BUG] documentation about flux extension is outdated

### ISSUE THREAD

**Issue by sleepy-manul** [Azure/AKS#3847]
**Describe the bug**
According to https://learn.microsoft.com/en-gb/azure/azure-arc/kubernetes/extensions-release (retrieved today), the newest version of the flux extension for AKS clusters is "1.7.0". However, I believe this is not the current state. I successfully set up an AKS cluster with the flux extension and the "Auto Upgrade Minor Version" setting to true. After successful creation of the cluster, the flux version is shown as "1.7.5"

**To Reproduce**
See above

**Expected behavior**
https://learn.microsoft.com/en-gb/azure/azure-arc/kubernetes/extensions-release having up-to-date release notes and information about the available versions of the flux extension.

**Screenshots**
![image](https://github.com/Azure/AKS/assets/6627519/074c2fbd-ae56-4213-a63d-561958eee6ef)
![image](https://github.com/Azure/AKS/assets/6627519/bf852b49-312f-4e53-8ea6-585939f351d4)

**Environment (please complete the following information):**
- Azure Region West Europe
- Kubernetes 1.25.11

**Additional context**
N/A

**Comment by allyford** [comment]
Hi @sleepy-manul,
Thanks for bringing this to our attention. For Azure documentation updates, please create an issue on the [Azure docs github](https://github.com/MicrosoftDocs/azure-docs/issues).
