### ISSUE TITLE
[Feature] Migration from Kubenet to Azure CNI Overlay

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#3848]
**Is your feature request related to a problem? Please describe.**
Today you cannot migrate Kubenet to Azure CNI overlay. A new cluster is required.

**Describe the solution you'd like**
Allow cluster/nodepool migration from Kubenet to Azure CNI Overlay.
https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay

**Comment by rgarcia89** [comment]
Looking very forward to this one

**Comment by jbla9028** [comment]
Hello, Does MS happen to have any availability timeline for private/public preview of this feature? we have a lot of cluster operations happening that this would accelerate and trying to see if there's any ETA at all that can be shared. Thank you very much.

**Comment by PixelRobots** [comment]
> Hello, Does MS happen to have any availability timeline for private/public preview of this feature? we have a lot of cluster operations happening that this would accelerate and trying to see if there's any ETA at all that can be shared. Thank you very much.

You can currently do this, but it has some limitations.

The cluster is on Kubernetes version 1.22+.
Doesn't use the dynamic pod IP allocation feature.
Doesn't have network policies enabled.
Doesn't use any Windows node pools with docker as the container runtime.

https://portal.azure.com/#@aimmsprod.onmicrosoft.com/resource/subscriptions/ff882bc1-208c-44a7-910f-985f4ff418fe/resourceGroups/rg-managedservices/providers/microsoft.insights/scheduledqueryrules/aks-aimms-prod%20-%20End%202%20End%20health%20alert/ViewAlertRuleHistory

If you are using network policies, something seems to be in the works to allow you to switch them off and then you can hopefully migrate.

**Comment by monotek** [comment]
> You can currently do this, but it has some limitations.
> 
>  Doesn't use the dynamic pod IP allocation feature. 
> Doesn't have network policies enabled. 
> 

As far as i know these are azure cni but not kubenet feature?
Sure you don't mix that up?

**Comment by jbla9028** [comment]
> > Hello, Does MS happen to have any availability timeline for private/public preview of this feature? we have a lot of cluster operations happening that this would accelerate and trying to see if there's any ETA at all that can be shared. Thank you very much.
> 
> You can currently do this, but it has some limitations.
> 
> The cluster is on Kubernetes version 1.22+. Doesn't use the dynamic pod IP allocation feature. Doesn't have network policies enabled. Doesn't use any Windows node pools with docker as the container runtime.
> 
> https://portal.azure.com/#@aimmsprod.onmicrosoft.com/resource/subscriptions/ff882bc1-208c-44a7-910f-985f4ff418fe/resourceGroups/rg-managedservices/providers/microsoft.insights/scheduledqueryrules/aks-aimms-prod%20-%20End%202%20End%20health%20alert/ViewAlertRuleHistory
> 
> If you are using network policies, something seems to be in the works to allow you to switch them off and then you can hopefully migrate.

We are looking at Kubenet -> Azure CNI overlay.

**Comment by Flasheh** [comment]
I noticed this one in the latest AKS release notes 🤞 

> Preview Features
> - Cluster network settings can be updated to enable Kubenet -> CNI Overlay migration - available in the [CLI](https://github.com/Azure/azure-cli-extensions/pull/6936)

**Comment by rgarcia89** [comment]
Not sure is working already. But at least for me using with calico for policy and kubenet as plugin it isn't.

```
(BadRequest) Upgrading to Azure CNI Overlay from Kubenet is not supported when using networkPolicy=calico.
Code: BadRequest
Message: Upgrading to Azure CNI Overlay from Kubenet is not supported when using networkPolicy=calico.
Target: networkProfile.networkPluginMode

```

**Comment by PixelRobots** [comment]
You will need to disable networking policies first. You can't currently do this, but it is coming in preview soonish I believe.

**Comment by rgarcia89** [comment]
@PixelRobots has anyone been able to disable the calico network policies in order to perform the migration so far?

**Comment by PixelRobots** [comment]
Nope, we are still waiting on this issue. https://github.com/Azure/AKS/issues/3845

Hopefully soon!

**Comment by veronikaBu** [comment]
I'll also be very interested in this new feature.

**Comment by tyler-lloyd** [comment]
FYI this feature is now generally available (GA) as of the 2024-01-23 release of AKS. https://github.com/Azure/AKS/releases/tag/2024-01-23

**Comment by rgarcia89** [comment]
@tyler-lloyd unfortunately still nothing in regards to `networkPolicy=calico` enabled clusters.

**Comment by amitmavgupta** [comment]
@fok666 

Can anyone clarify if this feature in GA still requires aks-preview extension and Microsoft.ContainerService AzureOverlayPreview feature flag, as pointed out in the Docs?

> No, these are not required anymore. You can refer to this in case if it helps ( this was updated post the feature went GA)- https://isovalent.com/blog/post/upgrade-cilium-in-azure/#h-scenario-5-kubenet-to-azure-cni-powered-by-cilium

**Comment by ricoberger** [comment]
Hi, I tried to migrate our clusters from Kubenet to Azure CNI Overlay via the command mentioned in the [documentation](https://learn.microsoft.com/en-gb/azure/aks/azure-cni-overlay?tabs=kubectl#kubenet-cluster-upgrade):

```sh
az aks update --name $clusterName --resource-group $resourceGroup --network-plugin azure --network-plugin-mode overlay
```

While this is working perfectly fine for "newly" created clusters, the command fails for old clusters with the following error message:

```
(NetworkProfileCIDROverlapVNET) NetworkProfile CIDR 10.244.0.0/16 overlaps with reserved VNET CIDR 10.0.0.0/8
Code: NetworkProfileCIDROverlapVNET
Message: NetworkProfile CIDR 10.244.0.0/16 overlaps with reserved VNET CIDR 10.0.0.0/8
Target: networkProfile.podCIDR
```

I think the problem exists for all clusters, which were created before [Release 2022-02-24](https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2022-02-24), where the VNET address was changed from 10.0.0.0/8 to 10.240.0.0/16.

Is there a way to update these old clusters (where the VNET address is 10.0.0.0/8) or do we have to update the VNET address first to be able to update from Kubenet to Azure CNI Overlay?

**Comment by ricoberger** [comment]
Hi @chasewilson do you have some input for us on the issue mentioned in my last comment?

**Comment by amitmavgupta** [comment]
@ricoberger Please see- the last paragraph in the below mentioned article. It doesn't seem like you can do that.

https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay?tabs=kubectl#azure-cni-cluster-upgrade

**Comment by monotek** [comment]
But some of the Azure AKS POs told us at Kubecon Paris that this would be a rather little change and it should be fixed soonish. 
Thats the reason we ask about the current state.

**Comment by amitmavgupta** [comment]
@monotek in that case deleted my comment above so that there is no confusion.
