### ISSUE TITLE
[Question] AKS GMSA non domain joined host

### ISSUE THREAD

**Issue by sjokoladefoged** [Azure/AKS#3849]
Wanting to leverage GMSA using non domain joined hosts.
Can't seem to get it to work. Looking at the logs of CCG, when the host is domain joined everything works, credentials are fetched from keyvault, log on succeeds and the GMSA is working. 

Taking the host out of the domain and the following error occurs:

Container Credential Guard failed to fetch gmsa credentials for xxx using plugin {CCC2A336-D7F3-4818-A213-272B7924213E}. Error reason: The attempted logon is invalid. This is either due to a bad username or authentication information.

I tried creating a test environment with everything in the same vnet and I get the same behaviour

Kubernetes version: 1.25.11
Node image versoin: AKSWindows-2022-containerd-20348.1906.230808

Does anyone have a suggestion as to what it could be?

**Comment by srinivas-kujala** [comment]
Do we have any resolution for the above issue?

**Comment by srinivas-kujala** [comment]
> Wanting to leverage GMSA using non domain joined hosts. Can't seem to get it to work. Looking at the logs of CCG, when the host is domain joined everything works, credentials are fetched from keyvault, log on succeeds and the GMSA is working.
> 
> Taking the host out of the domain and the following error occurs:
> 
> Container Credential Guard failed to fetch gmsa credentials for xxx using plugin {CCC2A336-D7F3-4818-A213-272B7924213E}. Error reason: The attempted logon is invalid. This is either due to a bad username or authentication information.
> 
> I tried creating a test environment with everything in the same vnet and I get the same behaviour
> 
> Kubernetes version: 1.25.11 Node image versoin: AKSWindows-2022-containerd-20348.1906.230808
> 
> Does anyone have a suggestion as to what it could be?

I'm facing same issue on kubernetes version 1.29.5 as well. Do we have any resolution or troubleshooting steps for this?
