### ISSUE TITLE
[BUG] Pod never starts due to volume not attaching? mounting? 

### ISSUE THREAD

**Issue by roy-work** [Azure/AKS#3865]
**Describe the bug**
This is going to be extremely similar to #3681, with the note that the cluster is not undergoing upgrade, so control plane version == node version. Since that was the resolution to #3681, and cannot apply here, this is sort of reopening that same issue. I do not know if the root cause is related, or not.

A pod of ours is stuck:
```
NAME                                      READY   STATUS                   RESTARTS         AGE   IP             NODE                       NOMINATED NODE   READINESS GATES
aptly-0                                   0/1     Init:0/2                 0                50m   <none>         aks-nodepool1-34304298-2   <none>           <none>
```

We've seen this numerous times with this pod: this pod has an Azure Disk volume, and mounting that volume inexplicably takes a long time — often, hours.

We've filed internal issues with Azure and gotten nowhere useful, often because by the time support finally looks at the issue, several hours have passed and the pod is running. Without an active crime scene, support seems unable to make headway on this. Needless to say, taking hours for a pod to start is unacceptable.

The pod's `describe` output:

```
Events:
  Type     Reason       Age                 From               Message
  ----     ------       ----                ----               -------
  Normal   Scheduled    52m                 default-scheduler  Successfully assigned aptly/aptly-0 to aks-nodepool1-34304298-2
  Warning  FailedMount  50m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[private-key aptly-ssh-host-keys nginx dotssh temp init-config aptly-ssh-client-keys datadir internal-crt]: timed out waiting for the condition
  Warning  FailedMount  48m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[dotssh nginx internal-crt private-key aptly-ssh-host-keys datadir temp init-config aptly-ssh-client-keys]: timed out waiting for the condition
  Warning  FailedMount  45m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[init-config aptly-ssh-host-keys internal-crt dotssh private-key aptly-ssh-client-keys nginx datadir temp]: timed out waiting for the condition
  Warning  FailedMount  43m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[aptly-ssh-client-keys nginx datadir temp private-key init-config aptly-ssh-host-keys dotssh internal-crt]: timed out waiting for the condition
  Warning  FailedMount  41m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[internal-crt nginx dotssh private-key aptly-ssh-host-keys aptly-ssh-client-keys temp init-config datadir]: timed out waiting for the condition
  Warning  FailedMount  39m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[private-key internal-crt aptly-ssh-client-keys nginx datadir aptly-ssh-host-keys dotssh temp init-config]: timed out waiting for the condition
  Warning  FailedMount  36m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[temp dotssh aptly-ssh-client-keys aptly-ssh-host-keys nginx datadir private-key init-config internal-crt]: timed out waiting for the condition
  Warning  FailedMount  34m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[internal-crt temp private-key aptly-ssh-client-keys dotssh datadir init-config aptly-ssh-host-keys nginx]: timed out waiting for the condition
  Warning  FailedMount  32m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[datadir aptly-ssh-client-keys init-config temp aptly-ssh-host-keys dotssh private-key nginx internal-crt]: timed out waiting for the condition
  Warning  FailedMount  46s (x14 over 30m)  kubelet            (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[aptly-ssh-client-keys nginx dotssh datadir private-key init-config temp internal-crt aptly-ssh-host-keys]: timed out waiting for the condition
```
(K8s's event make is damn near impossible to tell what the problematic volume is, but it's easy enough to surmise in my case. The rest are CMs/secrets, none of which have seen any changes. The last event, which only implicates `volumes=[datadir]` is the key one; `datadir`, as the name suggests, is the PVC at play here.)

The `get node -o yaml` for the node this pod is running on reports the volume is attached and in use:
```
  volumesAttached:
  - devicePath: ""
    name: kubernetes.io/csi/disk.csi.azure.com^/subscriptions/<snip>/resourceGroups/mc_<snip>_westus2/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-<snip>
  volumesInUse:
  - kubernetes.io/csi/disk.csi.azure.com^/subscriptions/<snip>/resourceGroups/mc_<snip>_westus2/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-<snip>
  ```

On the previous bug, the logs to `csi-azuredisk-node` were requested. Like last time, there are no logs worth speaking of.
<details>
<summary>The logs, anyways. There's nothing here.</summary>

```
Defaulted container "liveness-probe" out of: liveness-probe, node-driver-registrar, azuredisk
I0711 04:15:57.236168       1 main.go:149] calling CSI driver to discover driver name
I0711 04:15:57.335608       1 main.go:155] CSI driver name: "disk.csi.azure.com"
I0711 04:15:57.335640       1 main.go:183] ServeMux listening at "0.0.0.0:29603"
```

</details>

The kubelet's logs are similarly useless, not containing really any more information than what is present in the events:
```
E0821 19:28:55.695072    1552 kubelet.go:1712] "Unable to attach or mount volumes for pod; skipping pod" err="unmounted volumes=[datadir], unattached volumes=[init-config nginx internal-crt datadir temp aptly-ssh-host-keys private-key aptly-ssh-client-keys dotssh]: timed out waiting for the condition" pod="aptly/aptly-0"
E0821 19:28:55.695123    1552 pod_workers.go:965] "Error syncing pod, skipping" err="unmounted volumes=[datadir], unattached volumes=[init-config nginx internal-crt datadir temp aptly-ssh-host-keys private-key aptly-ssh-client-keys dotssh]: timed out waiting for the condition" pod="aptly/aptly-0" podUID=76b54e9e-ae1a-4023-ad7a-839977504f46
```

**To Reproduce**
We're unclear on why this particular pod is affected. We use Azure Disks elsewhere, and those pods tend to work alright. This particular pod _always_ exhibits this behavior.

**Expected behavior**
An Azure Disk should take no more than 60s to unmount & remount to the needed VM.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - CLI Version [e.g. 3.22]: N/A
 - Kubernetes version [e.g. 1.24.3]: v1.24.10
 - CLI Extension version [e.g. 1.7.5] if applicable: N/A
 - Browser [e.g. chrome, safari] is applicable: N/A

**Additional context**

The pod started on its own, with no modifications from us, after 70m.

**Comment by andyzhangx** [comment]
from the disk attach logs, the disk attach usually takes less than 20s, the slow mount could be due to fsGroup change when your disk has lots of files and folders, check below recommendation:

```
I0822 07:06:39.805982       1 azure_metrics.go:115] "Observed Request Latency" latency_seconds=17.390070398 request="azuredisk_csi_driver_controller_unpublish_volume" resource_group="mc_akscorp_akscorp_westus2" subscription_id="xxx" source="disk.csi.azure.com" volumeid="/subscriptions/xxx/resourceGroups/mc_akscorp_akscorp_westus2/providers/Microsoft.Compute/disks/pvc-982ca374-7b41-4f53-8b6a-19c6d7079c7e" node="aks-nodepool1-34304298-0" result_code="succeeded"
```


- fsGroup setting
option#1: set fsGroupChangePolicy: "OnRootMismatch" in pod securityContext(supported from k8s 1.20):
OnRootMismatch: Only change permissions and ownership if permission and ownership of root directory does not match with expected permissions of the volume. This could help shorten the time it takes to change ownership and permission of a volume.

refer to [Configure volume permission and ownership change policy for Pods](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods)

option#2: Set uid in runAsUser and gid in fsGroup for pod: [security context for a Pod](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
e.g. Following setting will set pod run as root, make it accessible to any file:
```
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    runAsUser: 0
    fsGroup: 0
```

Note: Since gid & uid is mounted as 0(root) by default, if set as non-root(e.g. 1000), k8s will use chown to change all dir/files under that disk, this is a time consuming job, which would make mount device very slow, in this issue: [Timeout expired waiting for volumes to attach](https://github.com/kubernetes/kubernetes/issues/67014#issuecomment-413546283), it costs about 10 min for chown operation complete.
