### ISSUE TITLE
[BUG] [Istio Add-on] Removal of Internal Ingress Gateway does not also remove kubernetes-internal load balancer

### ISSUE THREAD

**Issue by dxlusby** [Azure/AKS#3867]
When the Istio service mesh is enabled and the internal ingress gateway is enabled, a kubernetes-internal load balancer is created in the managed resource group as a result.  When the ingress gateway is subsequently disabled (leaving no other k8s services of types that would generate a kubernetes-internal ALB), AKS does not delete the kubernetes-internal load balancer.  Upon re-enabling the internal ingress gateway, the existing kubernetes-internal load balancer is re-used, with an additional FrontendIpConfiguration for the newly enabled ingress gateway's configuration.  The previous FrontendIpConfiguration, from the first ingress gateway enable operation is now orphaned configuration.

**To Reproduce**
```powershell
az login --use-device-code

$RESOURCE_GROUP = "aks-istio-addon"
$LOCATION = "West US"
$CLUSTER = "aks"

az group create --name ${RESOURCE_GROUP} --location ${LOCATION}

az aks create `
--resource-group ${RESOURCE_GROUP} `
--name ${CLUSTER} `
--enable-asm `
--generate-ssh-keys

az aks mesh enable-ingress-gateway --resource-group $RESOURCE_GROUP --name $CLUSTER --ingress-gateway-type internal

az aks mesh disable-ingress-gateway --resource-group $RESOURCE_GROUP --name $CLUSTER --ingress-gateway-type internal
```

**Expected behavior**
When the last service requiring the Azure 'kubernetes-internal' ILB is deleted, it should be deleted.

**Screenshots**

###  After Enabling Internal Ingress Gateway (First Enable)
>![image](https://github.com/Azure/AKS/assets/8630843/987b6dce-feee-4be1-bce2-c53399971665)
![image](https://github.com/Azure/AKS/assets/8630843/f9c5f066-3235-4840-8b80-205c81fc2502)

### After Disabling Internal Ingress Gateway
> ![image](https://github.com/Azure/AKS/assets/8630843/93743da1-1f6d-4ef7-8990-1068530976ae)
![image](https://github.com/Azure/AKS/assets/8630843/db035680-85b0-4dfe-9288-52031cfee63b)

### After Enabling Internal Ingress Gateway (Second Enable)
> ![image](https://github.com/Azure/AKS/assets/8630843/5119371e-558c-4a4c-a048-3daa9d4adbf5)
![image](https://github.com/Azure/AKS/assets/8630843/6241b570-5cea-4da0-8732-1b17cc6ffbd4)

**Environment (please complete the following information):**
Azure CLI versions:  
```json
{
  "azure-cli": "2.51.0",
  "azure-cli-core": "2.51.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "aks-preview": "0.5.152"
  }
}
```
K8s Version: 1.26.6

**Comment by kaarthis** [comment]
Request a response on the topic @biefy

**Comment by biefy** [comment]
This was fixed recently.
