### ISSUE TITLE
[BUG] Image Cleaner requires enabling EnableImageCleanerPreview feature

### ISSUE THREAD

**Issue by daalse** [Azure/AKS#3875]
**Describe the bug**
Image Cleaner is in GA, however when you try to enable it in an existing cluster it says that it is not allowed to enable since feature flag  "Microsoft.ContainerService/EnableImageCleanerPreview" is not registered

**To Reproduce**
1. Run command 
 az aks update -n XXXX -g XXXX --enable-image-cleaner --image-cleaner-interval-hours 168

2. See error
(ImageCleanerFeatureFlagNotEnabled) ImageCleaner is not allowed to enable since feature flag "Microsoft.ContainerService/EnableImageCleanerPreview" is not registered. Please see https://aka.ms/aks/image-cleaner for how to register the feature flag.
Code: ImageCleanerFeatureFlagNotEnabled
Message: ImageCleaner is not allowed to enable since feature flag "Microsoft.ContainerService/EnableImageCleanerPreview" is not registered. Please see https://aka.ms/aks/image-cleaner for how to register the feature flag.

**Expected behavior**
Since Image Cleaner is in GA, it should not be necessary to enable the feature flag.

**Screenshots**

**Environment (please complete the following information):**
 -  CLI Version

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
load                               0.3.1
ml                                2.19.1
ssh                                2.0.1

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/t-daniel/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Feb  8 2023, 03:39:52) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

 - Kubernetes version 1.26.3

**Additional context**

**Comment by kevinharing** [comment]
You probably need to wait for v20230820 to be rolled out to your region. S[ee release tracker](https://releases.aks.azure.com/webpage/index.html#tabversion).
