### ISSUE TITLE
[BUG] AKS Stop is not waiting for termination grace period

### ISSUE THREAD

**Issue by justin-sto** [Azure/AKS#3884]
**Describe the bug**
I am currently facing a weird issue on multiple clusters, that are running on spot machines and are being on a nightly shutdown schedule. For each of the clusters, some of the same pods, are stuck in terminating state, after the cluster has been restarted. As this happens each night, the pods are adding up quickly.
If I manually cordon the node and wait a bit, this does not appear, but if I shut it down, using the API, the azure cli or the Azure portal, the pod is being stuck in terminating state after the cluster is started again.
It seems like the pod is not being able to terminate in time, before the spot machine that the pod is running on, is gone.

**To Reproduce**
1. Configure a pod with the default terminationgraceperiod of 30s and a preStop Hook command: pkill -15 SERVICE
2. Either run az aks stop --name myAKSCluster --resource-group myResourceGroup OR by manually stopping the cluster, using the azure portal OR using api with POST https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/managedClusters/{resourceName}/stop?api-version=2023-07-01

**Expected behavior**
Node should be existing until pod has been terminated successfully, so that is not being stuck in terminating state.

**Environment (please complete the following information):**
 -  CLI Version: 2.51.0
 - Kubernetes version: 1.26.6

**Additional context**

**Comment by justin-sto** [comment]
Upon further inspection, the issue is not specific to spot machines, instead, it appears on normal machines as well.
It looks like all machines are being terminated **before** the default grace-period of 30 seconds is over.

**Comment by boliu83** [comment]
you observation is correct.  there is no wait on pod deletion during stop cluster operation.  workaround to the issue is to scaledown deployment to 0 before stopping the cluster.

**Comment by justin-sto** [comment]
@boliu83 I think, that should not be the case. Even if I stop the machines, they should not be evicted without waiting for the termination grace period. The question also is, how to automate this. As I would need to scaledown, before the shutdown and after the reboot, I would need to wait for the system to be responsive (which differs each time), to be then able to scale the deployment. This is also no longer possible, using the api, since Kubernetes 1.26 according to the documentation by microsoft.

Would highly appreciate any ideas or opinions on that

**Comment by boliu83** [comment]
> @boliu83 I think, that should not be the case. Even if I stop the machines, they should not be evicted without waiting for the termination grace period. The question also is, how to automate this. As I would need to scaledown, before the shutdown and after the reboot, I would need to wait for the system to be responsive (which differs each time), to be then able to scale the deployment. This is also no longer possible, using the api, since Kubernetes 1.26 according to the documentation by microsoft.
> 
> Would highly appreciate any ideas or opinions on that

one easy way to automate your goal is to use 2 loops.  1st loop run 'kubectl cordon' on all nodes to disable scheduling on all worker nodes.  2nd loop deletes all pods (assuming there is no PDB in the system to block the delete).  once these are done (or reach certain timeout) you can stop the AKS cluster.

**Comment by justin-sto** [comment]
Thanks for your help @boliu83 

The issue has been fixed by the Microsoft support in the meantime. In our case, the issue was due to duplicate values inside our deployment and a currently open issue on the kubernetes GitHub, that you can find below:
https://github.com/kubernetes/kubernetes/issues/118261

This bug causes issues with the garbage collection after a cluster restart, which is causing the pod to not be properly terminated, the next time the cluster starts.

Best regards

Justin

**Comment by boliu83** [comment]
thanks for letting me @justin-sto .  I have to admit that I thought the pods stuck in Terminating was just because they were not given enough time to shutdown properly.    and the bug itself is very interesting too
