### ISSUE TITLE
Breaking Change in Windows containerd v1.7 with Kubernetes v1.28+

### ISSUE THREAD

**Issue by AbelHu** [Azure/AKS#3885]
Kubernetes v1.28 will be preview on AKS soon. Windows containerd v1.7 will be used with k8s v1.28+ on AKS Windows nodes.
Windows Host Process (HPC) containers is GA in Windows containerd v1.7 and it has some breaking changes. Please see more details in https://github.com/kubernetes/enhancements/tree/master/keps/sig-windows/1981-windows-privileged-container-support#container-mounts

Below are two known issues with HPC in Windows containerd v1.7 and they may not be fixed (by design).
- https://github.com/microsoft/Windows-Containers/issues/366
- https://github.com/microsoft/Windows-Containers/issues/371

**Comment by AbelHu** [comment]
Symlinks is used in Windows containerd v1.6 but Bind Mounts is used in Windows containerd v1.7+.

In v1.6:

Additional volumes mounts specified for hostProcess containers will be mounted to c:\C\{container-id}\{mount-destination}
ex: a volume with a mountPath of /var/run/secrets/token for a container with id 1234 can be accessed at c:\C\1235\var\run\secrets\token 

In v1.7:

Additional volume mounts specified for hostProcess containers will be mounted at their requested location and can be access the same way as volume mounts in Linux or regular Windows Server containers.
ex: a volume with a mountPath of /var/run/secrets/token for containers will be mounted at c:\var\run\secrets\token for containers.

**Comment by fschmied** [comment]
Just in case readers aren't aware: In general, there is a [backwards compatibility feature](https://github.com/kubernetes/enhancements/tree/master/keps/sig-windows/1981-windows-privileged-container-support#compatibility) in place for volume mounts with v1.7:

> Backwards compatibility with volume mount paths has been added into containerd v1.7. This means that existing workloads that used $CONTAINER_SANDBOX_MOUNT_POINT to access volume mounts will work without updates.

(That doesn't fix the known issues referenced above, though.)
