### ISSUE TITLE
[BUG] node-problem-detector config outdated

### ISSUE THREAD

**Issue by mdnix** [Azure/AKS#3889]
**Describe the bug**
I am interested in the OOMKilling events produced by the node-problem-detector, which is installed on AKS nodes. However, the node-problem-detector is using an outdated pattern to evaluate the oom-killer event from /dev/kmsg.

**To Reproduce**
To test out the event, I created a Pod that starts a stress process exceeding the defined memory limit of 200Mi.

```yaml
kubectl apply -f - << EOF
apiVersion: v1
kind: Pod
metadata:
  name: oom-provoke
spec:
  containers:
  - name: oom-provoke
    image: polinux/stress
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "350M", "--vm-hang", "1"]
EOF
```

Unfortunately, the OOMKilling event was not emitted via the Kubernetes Event API by the node-problem-detector.

To further investigate, I started a debug Pod on the node where the oom-provoke Pod ran.

```bash
kubectl apply -f - << EOF
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: debug-node
  name: debug-node
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: ubuntu
    name: ubuntu
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_ADMIN
      runAsUser: 0
    volumeMounts:
    - mountPath: /host
      name: node-volume
      readOnly: true
  hostIPC: true
  hostNetwork: true
  hostPID: true
  nodeName: aks-default-43896515-vmss000000
  restartPolicy: Never
  serviceAccount: default
  serviceAccountName: default
  volumes:
  - hostPath:
      path: /
      type: ""
    name: node-volume
EOF
```
After the Pod started, I exec'd into it and looked at /dev/kmsg via the dmesg command. Upon doing so, I observed that the oom-killer was invoked.

```bash
[ 4324.587600] Memory cgroup out of memory: Killed process 110151 (stress) total-vm:359184kB, anon-rss:203740kB, file-rss:288kB, shmem-rss:0kB, UID:0 pgtables:436kB oom_score_adj:997
```

Now, when looking at the node-problem-detector rule designed to observe this, I noticed that the pattern is outdated. I think it's incompatible with newer kernels. There was even an issue regarding this: [GitHub Issue](https://github.com/kubernetes/node-problem-detector/pull/481/files). The config has been fixed for a while, but I suspect that the Node Images have not been updated with this new config. Could that be the case? Can you please align the node-problem-detector configs with the newest ones? The currently used config employs the old pattern, which doesn't match:

```bash
root@aks-default-43896515-vmss000000:/# cat /etc/node-problem-detector.d/system-log-monitor/kernel-monitor.json 
{
        "plugin": "kmsg",
        "logPath": "/dev/kmsg",
        "lookback": "5m",
        "bufferSize": 10,
        "source": "kernel-monitor",
        "metricsReporting": true,
        "conditions": [
                {
                        "type": "KernelDeadlock",
                        "reason": "KernelHasNoDeadlock",
                        "message": "kernel has no deadlock"
                },
                {
                        "type": "ReadonlyFilesystem",
                        "reason": "FilesystemIsNotReadOnly",
                        "message": "Filesystem is not read-only"
                }
        ],
        "rules": [
                {
                        "type": "temporary",
                        "reason": "OOMKilling",
                        "pattern": "Kill process \\d+ (.+) score \\d+ or sacrifice child\\nKilled process \\d+ (.+) total-vm:\\d+kB, anon-rss:\\d+kB, file-rss:\\d+kB.*"
                },
...ommited...
```

**Expected behavior**
I want to be able to observe the OOMKilling Event via ```kubectl get events```

**Environment (please complete the following information):**
 - Node Image Version: AKSUbuntu-2204gen2containerd-202308.10.0
 - Kubernetes version: 1.26.6

**Comment by shanalily** [comment]
Thanks for reporting the bug. The npd config update should be released in the public cloud within the next 2 weeks.

**Comment by mdnix** [comment]
Do you have any information about the expected rollout date for West Europe?

**Comment by aritraghosh** [comment]
This should have been rolled out to all regions. Let us know if otherwise
