### ISSUE TITLE
Increase secondary IP address count on each node and increase node pod limit.

### ISSUE THREAD

**Issue by AaronFriel** [Azure/AKS#389]
Currently, pods are allocated with 30 secondary IP addresses on their virtual NIC, which are utilized by the Azure VNET CNI plugin to allocate those to pods directly.

Increasing this to 100 should work fine for nodes, and is closer to the expected pod limit for Kubernetes. It will greatly improve the scalability of clusters when using lightweight micro-services where resource usage per container might be quite small, and the number of services in the cluster quite high.

**Comment by dstrebel** [comment]
Currently you can increase the default pod count if you deploy through an ARM template. The reason for the restriction is due to the VNET limitation of IP addresses (4000). If defaulting to 100 then the cluster will only be able to scale to 40 nodes., thus the reason of the limitation. There is work being done to hopefully increase the ip address limit of VNETs in the future.

**Comment by AaronFriel** [comment]
Is there a way to deploy AKS (not `acs-engine`) using an ARM template?

**Comment by scotta01** [comment]
> @dstrebel Currently you can increase the default pod count if you deploy through an ARM template. The reason for the restriction is due to the VNET limitation of IP addresses (4000)

With basic networking, unless something has changed, the underlying infrastructure still provisions a vNET so surely the same vNet IP addressing limitations would still apply yet the default limit is 100?

Aside from that, as per the [documentation](https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#azure-resource-manager-virtual-networking-limits), this was updated back in April to 16K. Will AKS soon be revising this quota default for Advanced Networking from 30 back to 100?

**Comment by jnoller** [comment]
Closing as stale
