### ISSUE TITLE
Node Soak Duration for Upgrades

### ISSUE THREAD

**Issue by kaarthis** [Azure/AKS#3899]
Provide a mechanism to stagger node upgrades via a SOAK Node duration in mins feature at Agentpool level. This helps to validate application health and readiness for customers.

GA planned for 1/2/2024

**Comment by ohads-MSFT** [comment]
@kaarthis Is this the feature mentioned here? https://learn.microsoft.com/en-us/azure/aks/upgrade-aks-cluster?tabs=azure-cli#set-node-soak-time-value-preview

If so, could you please provide more details about it? The CLI docs state:
https://learn.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest#az-aks-nodepool-add(aks-preview)-optional-parameters
> The amount of time (in minutes) to wait after draining a node and before reimaging it and moving on to next node.

So it's just a simple timer? Ideally, the soaking mechanism would be the "opposite" of the drain timeout value - namely, a timeout for the new pods to be `ready`. 

If I understand the docs correctly, and considering an outage we just had relating to an AKS upgrade, I believe that if for whatever reason pods aren't ready in the new version (in our case, missing ACR images) - the upgrade would obliviously continue to the next node, until all pods in the cluster are down. 

If I'm right, it's somewhat of an absurd situation, where we closely monitor graceful shut down, yet remain completely blind to startup issues. Arguably, the latter are far more important (if only for the simple reason that a machine could die abruptly at any point in time, so pods should never rely on graceful shutdown) ...

**Comment by asubmani** [comment]
Requesting some clarity on what you mean by "stagger" here. Would the "soak time" mean that:

1. New nodes/node pool created
2. Old one (the one you upgraded) gets cordoned?
3. Old nodepool gets drained
4. Soak time begins <whats the max value? would need 1 business week>
5. After Soak time is over, old nodepool starts getting deleted and new nodepool remains

An ideal situation would be be that except the last phase (5)-- where the old NP starts getting deleted; the nodepool upgrade operation can be cancelled and rolled back.

Is this how the node soak time would work? Waiting for more specific documentation on what happes during the soak time?

**Comment by ohads-MSFT** [comment]
@asubmani IMHO you are missing the key part
6. Are the new pods validated to be at the `ready` state before soaking can be completed?

Otherwise, the soaking is far less useful (time based only) - if you ask me the whole point of soaking is that the new pods are actually working before decommissioning the old ones...

**Comment by asubmani** [comment]
> @asubmani IMHO you are missing the key part 6. Are the new pods validated to be at the `ready` state before soaking can be completed?
> 
> Otherwise, the soaking is far less useful (time based only) - if you ask me the whole point of soaking is that the new pods are actually working before decommissioning the old ones...

Not sure what you mean by decommissioning old pods. Consider the recent cgroups v2 scenario:
1) Upgrade an AKS nodepool from 1.24 --- 1.25  (pods start crashing)
2) Soak time will let us revert the upgrade and we will be back to 1.24 nodePool (my expectation)

if the pods are unstable that they can't handle a restart that is a seperate issue and should be solved by those who wrote the app that runs in the pod. 
Soaktime is mostly for infrastructure rollack as today there is no way to roll back an inplace upgrade and staging nodepools manually can be a lot of work.

**Comment by ohads-MSFT** [comment]
> 1. Upgrade an AKS nodepool from 1.24 --- 1.25  (pods start crashing)
> 2. Soak time will let us revert the upgrade and we will be back to 1.24 nodePool (my expectation)

What do you mean "let us revert the upgrade"? 
You mean you would manually track the update and then manually stop it?
What happens when the upgrade is automatic (during some maintenance window)?
There is no reason why (2) can't happen automatically, simply wait for the `ready` state on the restarted pods...

**Comment by kaarthis** [comment]
@ohads-MSFT Soak timer (duration) is something you can set basically think of it is the transition time after a node is upgraded before the SYSTEM moves to the subsequent node - The period of time is important here as the main purpose is to give the evicted pods that were moved to other available nodes (incl surge nodes) from the 'Upgrading node' ample / sufficient time to get READY. does that help ? This is different from 'Drain time out' which helps to provide sufficient time for long running pods before the DRAIN call is given in the NODE.

**Comment by ohads-MSFT** [comment]
> the main purpose is to give the evicted pods that were moved to other available nodes (incl surge nodes) from the 'Upgrading node' ample / sufficient time to get READY. 

Just to be 100% sure we are on the same page:
1. Are we talking about this feature? https://learn.microsoft.com/en-us/azure/aks/upgrade-aks-cluster?tabs=azure-cli#set-node-soak-time-value-preview
2. When you say the moved pods are READY, you mean that AKS monitors their Kubernetes `status` (of type `PodStatus`), specifically verifying that its `phase` field is `Running` and its `PodConditions` of `Ready` is `true` (per https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions)?
3. If we don't define any soak time (default behavior when node soak duration isn't enabled), then AKS upgrades don't wait at all for the moved pods to be `Running` / `Ready` (per the definition in the previous bullet)?

**Comment by kaarthis** [comment]
1. Yes
2. AKS does not monitor but it gives the CX / Operator elbow room by way of setting a high enough SOAK value for the Pods rescheduled out as a result of 'Node upgrade' to become ready.
3. Just to be clear AKS will not verify the ready status of the Pods here , the SOAK duration is just a first layer of control to self serve this piece. However we have a sophisticated feature called 'Upgrade based on metrics' that would perhaps utilize prom metrics to make smart choices for proceed with upgrade or not - Stay tuned for that in late H1 CY24.

**Comment by asubmani** [comment]
> What do you mean "let us revert the upgrade"? You mean you would manually track the update and then manually stop it? What happens when the upgrade is automatic (during some maintenance window)? There is no reason why (2) can't happen automatically, simply wait for the `ready` state on the restarted pods...

Reversal will happen only within the soak time.  Consider example of 10 node user nodepool

aks nodeoool upgrade <nodepool name> --soak-time 7d.  

in this case, I expect AKS to keep the upgraded nodepool (nodeos image update, k8s minior version upgrade, patch update etc.)  for upto 7d. After 7 d you lose the option to rever your nodePool to previous version.

I will leave it to tje AKS team to clarofy what they mean by soak time here. The wordings so far "soak time for nodepool" imply that the upgrade will be a blue-green style similar to how GKE does.

https://cloud.google.com/kubernetes-engine/docs/concepts/node-pool-upgrade-strategies#blue-green-upgrade-strategy

Pod upgrades are generic K8s constructs and are same for GKE, AKS or any K8s cluster with similar k8s version

**Comment by ohads-MSFT** [comment]
Just to follow up here, it seems that what I wanted here was Pod Disruption Budgets (PDBs): https://kubernetes.io/docs/tasks/run-application/configure-pdb/

They consider readiness and will prevent pod eviction when below a certain availability threshold. This perfectly explains why node drain watch/timeout was prioritized during AKS upgrades - PDBs would prevent pod evictions, which would in turn prevent/time-out node drains.

I still think the soak time could be used to check the readiness of the moved pods, but I conceded it's less of a priority when taking PDBs into account.

**Comment by zioproto** [comment]
@kaarthis this is now GA:
https://azure.microsoft.com/en-gb/updates/generally-available-node-soak-duration-for-upgrades/

should we close this GitHub issue ? Thanks

**Comment by kaarthis** [comment]
Ty closing this . It is indeed GA.
