### ISSUE TITLE
AKS container Clouster deployemnt is failing in WestUS2 region with Operational Threshol error.

### ISSUE THREAD

**Issue by krishnamay** [Azure/AKS#39]
Hi,

I had a running ASK cluster in westus2 region and it was working fine . Today I checked that it is in failed state. I tried troubleshooting with no luck and deleted that and provisioned another one. But every time I am getting Operation Threshold error while launching a new AKS cluster. 

Everything is good and correct at my end. Please verify and update if there is a backend problem from Azure in westus2.

This is urgent for me.

Thanks,

**Comment by benc-uk** [comment]
There is an outage and capacity issues in westus2, see the announcement here in GitHub https://github.com/Azure/AKS/blob/master/annoucements/service_outage_2017-11-09.md

**Comment by sauryadas** [comment]
@krishnamay We rolled out AKS in east us . Please deploy in east us.
