### ISSUE TITLE
Annotations not working with nginx ingress

### ISSUE THREAD

**Issue by prachi1902** [Azure/AKS#3903]
We tried multiple annotations to rewrite the url in backend but it is not working.
Not sure there is some problem with nginx ingress installation or what.
[ingress.txt](https://github.com/Azure/AKS/files/12606460/ingress.txt)
 Can someone help on this?

**Comment by sabbour** [comment]
Is this using the application routing add-on? Please check these docs: https://learn.microsoft.com/en-us/azure/aks/app-routing-nginx-configuration#url-rewriting
