### ISSUE TITLE
Failed to provide a cluster in a working state (WestEurope)

### ISSUE THREAD

**Issue by Mumrau** [Azure/AKS#391]
Hello,

Since the middle of the previous week, Azure fails to provide a cluster in working state, I'm in Western Europe.

As referenced in #387 , `heapster` pods are delivered under CrashLoopBack state.
But I still can access the cluster thourgh kubectl.
Nevertheless, as soon as I deploy any resource inside (like a basic api that just replies to http requests), my `tunnelfront` pod ends up in the same, and I cannot access my resources from outside (even tho the `LoadBalancer` provides an external IP).

The kubectl describe over the `tunnelfront` returns the following :
> Warning  Unhealthy  9m (x183 over 1h)   kubelet, aks-b2ms-96472827-0  Liveness probe failed:
  Warning  BackOff    4m (x133 over 56m)  kubelet, aks-b2ms-96472827-0  Back-off restarting failed container

If someone could clarify, by the way, the role of the `tunnelfront` service under AKS, that would be great knowledge to me.
On the other hand, I would still like to know something about Azure strategy overt that problem, because provisionning Clusters that are already in a Failed State is well... Interesting.

EDIT: I tried using different versions of k8s, different vm_sizes, and the results are quite random...
`kube-svc` ends up failing from time to time, same for `k8s-dashboard`, `azure-proxy` too, just noticed.

**Comment by zBurrito** [comment]
Hello

I think we have the same issue. When you deploy a new AKS cluster do you also receive this azure error?
![image](https://user-images.githubusercontent.com/26899585/40728443-681c16b0-642a-11e8-9f81-7469bc077e7c.png)

**Comment by Mumrau** [comment]
I am personnalyy using the REST API, which is the philosophy of our global
solution, I couldn't really tell.

**Comment by lmiroslaw** [comment]
After deployment of the aks cluster in West Europe and connecting to the cluster, kubectl shows nothing

**Comment by rolanddb** [comment]
I just spun up a cluster in westeurope and have the same experience.

tunnel-front Pod is crashing:
`Events:
  Type     Reason     Age                From                               Message
  ----     ------     ----               ----                               -------
  Warning  Unhealthy  5m (x248 over 1h)  kubelet, aks-nodepool1-16122850-0  Liveness probe failed:
  Warning  BackOff    9s (x204 over 1h)  kubelet, aks-nodepool1-16122850-0  Back-off restarting failed container`

The cluster is pretty much unusable in this state.

**Comment by Mumrau** [comment]
Well I guess we could consider the issue as resolved, AKS clusters seems to be in a decent state.
Closing.
