### ISSUE TITLE
[BUG] updating api-server-authorized-ip-ranges reports AAD role propagation error

### ISSUE THREAD

**Issue by chouclee** [Azure/AKS#3911]
**Describe the bug**

**To Reproduce**
1. Run command 
```
az aks update --name $CLUSTER_NAME --resource-group $RESOURCE_GROUP --api-server-authorized-ip-ranges $newAuthorizedIps
```

3. See error
```
Waiting for AAD role to propagate[### ] 10.0000%
Waiting for AAD role to propagate[####### ] 20.0000%
Waiting for AAD role to propagate[########## ] 30.0000%
Waiting for AAD role to propagate[############## ] 40.0000%
Waiting for AAD role to propagate[################## ] 50.0000%
Waiting for AAD role to propagate[##################### ] 60.0000%
Waiting for AAD role to propagate[######################### ] 70.0000%
Waiting for AAD role to propagate[############################ ] 80.0000%
Waiting for AAD role to propagate[################################ ] 90.0000%WARNING: Could not create a role assignment for subnet. Are you an Owner on this subscription?
```
The update was completed but taking ~6mins in order to wait for `AAD role to propagate`.

**Expected behavior**
Why updating authorized ip list has anything to do with AAD role propagation? I think that one is only required for cluster creation?

**Screenshots**
<img width="1306" alt="Screenshot 2023-09-18 at 1 57 32 PM" src="https://github.com/Azure/AKS/assets/3389485/591de161-cf55-49f4-977e-fac0a1c481c7">

**Environment (please complete the following information):**
 -  CLI Version 2.52.0

**Additional context**

**Comment by nunoalima** [comment]
Any updates here?

We're facing the same issue using both a user-assigned managed identity with `Contributor` rights over the AKS cluster and a regular AAD User account, also a `Contributor`.

What should be a relatively quick command is also taking over 6 minutes:
`az aks update --resource-group $AKS_RG --name $AKS_NAME --api-server-authorized-ip-ranges $IP`

**Azure CLI**
Using `azure/login@v1`
![image](https://github.com/Azure/AKS/assets/89026428/890ad698-0382-4242-8553-09d4a7de4160)
Same outcome running locally using Azure CLI `2.54.0` and `2.55.0`.

**Logs**
![image](https://github.com/Azure/AKS/assets/89026428/020febad-768f-4e7c-9745-d377b8bb8567)

**Comment by MO2k4** [comment]
i am also facing this issue, is there any update on this? as this is really annoying 

@AllenWen-at-Azure sorry for tagging you directly, but since i saw you on some other tickets, could u maybe have a look into this as well?

**Comment by AllenWen-at-Azure** [comment]
Hi @norshtein , could you please help check is this the same issue you fixed in https://github.com/Azure/azure-cli/issues/18528?

**Comment by AllenWen-at-Azure** [comment]
Hi @chouclee are you still facing this issue?

**Comment by MO2k4** [comment]
@AllenWen-at-Azure this issue is still there
