### ISSUE TITLE
I cant see all nodes. after scaling. This happened for both prod and non-prod aks

### ISSUE THREAD

**Issue by sankansm23** [Azure/AKS#3914]
<img width="1061" alt="image" src="https://github.com/Azure/AKS/assets/86053694/2f1fbe0e-4c45-4ce8-b2a5-d17005e61036">

As you see above in screenshot node count shows as 4 but running only shows 3. when i did kubectl get nodes, i see only 3. 
How can i fix this ?

**Comment by aritraghosh** [comment]
@sankansm23  Thank you for the feedback. Is this a transient issue or does it remain at 3
