### ISSUE TITLE
"SecurityPatch" channel for automatic upgrades of node images doing nothing

### ISSUE THREAD

**Issue by adejongh** [Azure/AKS#3918]
We followed the instructions here:  https://learn.microsoft.com/en-gb/azure/aks/auto-upgrade-node-image
We enabled the "SecurityPatch" channel, but none of our nodes were ever updated (since 29 August).  There is no real way to figure out *why* it is not working either.

Commands we ran:
```
# Required for maintenance window?
az extension add --upgrade -n aks-preview

az aks maintenanceconfiguration add -g our-group --cluster-name our-cluster \
-n aksManagedAutoUpgradeSchedule \
--schedule-type RelativeMonthly --interval-months 1 --week-index Second --day-of-week Friday \
--duration 4 --utc-offset +02:00 --start-time 01:00

az aks maintenanceconfiguration add -g our-group --cluster-name our-cluster \
-n aksManagedNodeOSUpgradeSchedule \
--schedule-type Daily --interval-days 1 \
--duration 4 --utc-offset +02:00 --start-time 01:00

az aks update --resource-group our-group --name our-cluster --auto-upgrade-channel patch

az feature register --namespace "Microsoft.ContainerService" --name "NodeOsUpgradeChannelPreview"
# Wait until it shows as 'registered'
az feature show --namespace "Microsoft.ContainerService" --name "NodeOsUpgradeChannelPreview"
az provider register --namespace Microsoft.ContainerService
az aks update --resource-group our-group --name our-cluster --node-os-upgrade-channel SecurityPatch
```

From the above we expected node os updates to happen whenever they are available for our cluster region.

**Environment**
 -  CLI Version:  "azure-cli": "2.52.0", "azure-cli-core": "2.52.0", "aks-preview": "0.5.152" (extensions)
 - Kubernetes version:  1.26.6 (the patch upgrades are indeed working)
 - CLI Extension version:  assuming this is "aks-preview": "0.5.152"

**Additional context**
This is an "old" AKS cluster, with "Azure AD authentication with Kubernetes RBAC v1 (Legacy)"

**Comment by adejongh** [comment]
I've changed the same cluster to now use the "NodeImage" channel, and that is doing nothing either.
I've used the same configuration on another cluster, and that is not updating either.
I am not sure if we're doing something wrong, and whether this is not supposed to work...

**Comment by mkurukun** [comment]
im facing the same issue , We have configured Node OS image auto upgrades using a Maintenance window , but it isnt doing anything

**Comment by mpeuster** [comment]
Any update on this one?

It looks we are facing a similar issue. We have our cluster configured with node os auto update set to `NodeImage`. Cluster update is set to `patch`. We defined a maintenance window `aksManagedNodeOSUpgradeSchedule`. 

However, the upgrade is never triggered (nothing in the activity log either). Portal/CLI clearly show that there is a new node image available. Manually updating the node pool works.

We found now way to debug why the auto upgrade seems to be never triggered.

**Comment by Klodjangogo** [comment]
I am facing the same issue with AKS version 1.25.6 . I have set these options :

```
{
  "nodeOsUpgradeChannel": "NodeImage",
  "upgradeChannel": "none"
}
```

and a maintenance window (maintenance_window_node_os) to happen on every Sunday ( I have tested last week too ) but nothing happens . 

```
[
  {
    "id": "/subscriptions/xxx/aksManagedNodeOSUpgradeSchedule",
    "maintenanceWindow": {
      "durationHours": 6,
      "notAllowedDates": null,
      "schedule": {
        "absoluteMonthly": null,
        "daily": null,
        "relativeMonthly": null,
        "weekly": {
          "dayOfWeek": "Sunday",
          "intervalWeeks": 1
        }
      },
      "startDate": "2023-11-18",
      "startTime": "18:00",
      "utcOffset": "+00:00"
    },
    "name": "aksManagedNodeOSUpgradeSchedule",
    "notAllowedTime": null,
    "resourceGroup": "xxxx",
    "systemData": null,
    "timeInWeek": null,
    "type": null
  }
]
```

Is there a way to check why does not it start or maybe what is the issue that it is not triggered ( AKS version etc).

**Comment by mpeuster** [comment]
I tried with various AKS versions now. The lates being `1.27.3` using:

```json
{
  "nodeOsUpgradeChannel": "NodeImage",
  "upgradeChannel": "patch"
}
```

And maintenance windows (tried various settings, weekly, daily etc.):

```json
[
  {
    "id": "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.ContainerService/managedClusters/xxxx/maintenanceConfigurations/aksManagedAutoUpgradeSchedule",
    "maintenanceWindow": {
      "durationHours": 4,
      "notAllowedDates": null,
      "schedule": {
        "absoluteMonthly": null,
        "daily": null,
        "relativeMonthly": null,
        "weekly": {
          "dayOfWeek": "Wednesday",
          "intervalWeeks": 1
        }
      },
      "startDate": "2023-09-15",
      "startTime": "02:00",
      "utcOffset": "+00:00"
    },
    "name": "aksManagedAutoUpgradeSchedule",
    "notAllowedTime": null,
    "resourceGroup": "xxxx",
    "systemData": null,
    "timeInWeek": null,
    "type": null
  },
  {
    "id": "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.ContainerService/managedClusters/xxxx/maintenanceConfigurations/aksManagedNodeOSUpgradeSchedule",
    "maintenanceWindow": {
      "durationHours": 4,
      "notAllowedDates": [
        {
          "end": "2024-01-05",
          "start": "2023-12-20"
        }
      ],
      "schedule": {
        "absoluteMonthly": null,
        "daily": {
          "intervalDays": 1
        },
        "relativeMonthly": null,
        "weekly": null
      },
      "startDate": "2023-11-17",
      "startTime": "02:00",
      "utcOffset": "+00:00"
    },
    "name": "aksManagedNodeOSUpgradeSchedule",
    "notAllowedTime": null,
    "resourceGroup": "xxxx",
    "systemData": null,
    "timeInWeek": null,
    "type": null
  }
]
```

It seems the node update simply does not get triggered, there is nothing in the activity logs.

The node images of my pools are still at:

`AKSUbuntu-2204gen2containerd-202310.04.0`

even though it is shown that

`AKSUbuntu-2204gen2containerd-202310.31.0`

would be available.

Any suggestion to further troubleshoot this is welcome.

**Comment by adejongh** [comment]
So this appears to be a somewhat common problem - any ideas on how to get this working?

**Comment by xsoheilalizadeh** [comment]
We have the same problem using following channel on 1.26.6 and no node image upgrade happened since we enabled it.

```json
"autoUpgradeProfile": {
         "upgradeChannel": "node-image",
         "nodeOSUpgradeChannel": "NodeImage"
   }
```

This should be treated critically since we miss security patches for the nodes. 
@sabbour

**Comment by PhiRie** [comment]
Same here we are on the AKS version 1.27.3 and set the upgrade channel via terraform. I checked if the upgrade channel was correctly set via az aks show command and got the following response:

```json
{
  "nodeOsUpgradeChannel": "NodeImage",
  "upgradeChannel": "node-image"
}
```

I tried to set the upgradeChannel addtionally to "node-image" but it makes no difference if its set to none or node-image. There is a new node image version available but the upgrade is never triggered. 

```json
{
  "id": "hidden",
  "kubernetesVersion": "1.27.3",
  "latestNodeImageVersion": "AKSUbuntu-2204gen2containerd-202312.06.0",
  "name": "default",
  "osType": "Linux",
  "resourceGroup": "hidden",
  "type": "Microsoft.ContainerService/managedClusters/agentPools/upgradeProfiles",
  "upgrades": null
}
```

We have multiple clusters running and implemented the feature once on the 13. September for one of the clusters with a older k8s version and it runs once successfully but we are now facing the same issues on all of our clusters.

We are able to manually trigger the node os upgrade on the clusters as a workaround but we also don't find any information why the upgrade channel isn't working and the node images are not upgraded. 

Also tried to find some hint with the activity logs but there was no issue related to the upgrade so far. Used the following command. Perhaps someone else could test and see if there are any log related to the issue:

`az monitor activity-log list --namespace Microsoft.ContainerService  --offset 01d -g <resource group> -o json | jq 'map(select(.status.value == "Failed")) | .[] | {eventT
imestamp, operationName, status, properties}'`

Think a offset of about 7 days would be the best to use because as mentioned in microsoft docs the upgrade should at least run once a week if no further maintenance windows are set.

**Comment by yewmsft** [comment]
@adejongh It is hard to tell without the cluster information. I sent you an email to ask for details.

**Comment by adejongh** [comment]
> @adejongh It is hard to tell without the cluster information. I sent you an email to ask for details.

We're running in North Europe.  I have also provided more details directly in the email.

**Comment by mpeuster** [comment]
@yewmsft They are all in west europe.

**Comment by yewmsft** [comment]
A few discoveries:
1. NodeImage channel or SecurityPatch channel is not supported on AvailabilitySet (vmas) agent pool. We have has pushed a release which will block vmas clusters from transitioning to these 2 channels. For existing vmas clusters that are already on these 2 channels, the corresponding operation will NOT happen. Because node image upgrade operation does not exist for vmas agent pools to begin with. 
2. For VirtualMachineScaleSet (vmss), there is an known issue happened in westeurope region during the holidays, which caused auto upgrade stop triggering in westeurope region. This issue has been resolved on 1/21/2024. Cluster auto upgrader should resume this week, based on the maintenance window you have specified.

**Comment by yewmsft** [comment]
@xsoheilalizadeh, @PhiRie, @Klodjangogo, @mkurukun, @mpeuster, Please check my above comments. 
If your cluster does not fall into that 2 categories, please let me know.

**Comment by xsoheilalizadeh** [comment]
I can confirm that today we received the automatic node image update.

**Comment by Jordanbird96** [comment]
Still no automatic node image update for us. @yewmsft 

Location: Uk South

{
  "nodeOsUpgradeChannel": "NodeImage",
  "upgradeChannel": "none"
}

"maintenanceWindow": {
      "durationHours": 4,
      "notAllowedDates": null,
      "schedule": {
        "absoluteMonthly": null,
        "daily": {
          "intervalDays": 1
        },
        "relativeMonthly": null,
        "weekly": null
      },
      "startDate": "2023-11-22",
      "startTime": "09:00",
      "utcOffset": "+00:00"
    },
    "name": "aksManagedNodeOSUpgradeSchedule",
    "notAllowedTime": null,
    "resourceGroup": "**-***-*******-**",
    "systemData": null,
    "timeInWeek": null,
    "type": null

**Comment by mpeuster** [comment]
I can confirm as well that all our clusters have received the update in the meantime.
