### ISSUE TITLE
ACI-Connector can not create the route

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/AKS#392]
While scaling the ACI in https://github.com/rbitia/aci-demos I might have discovered an issue with ACI Connector. The pods get into the pending state ….

and after running kubectl get events I get:
Could not create route fc55f84c-5ec0-11e8-b126-0a58ac1f0c18 10.244.2.0/24 for node virtual-kubelet-myaciconnector-linux after 67.391124ms: instance not found
1m          1m           1         virtual-kubelet-myaciconnector-linux.15315d56d30ac47e                            Node                                                                         Warning   FailedToCreateRoute     route_controller                    Could not create route fc55f84c-5ec0-11e8-b126-0a58ac1f0c18 10.244.2.0/24 for node virtual-kubelet-myaciconnector-linux after 80.285384ms: instance not found
1m          1m           1         virtual-kubelet-myaciconnector-linux.15315d56e120bc0d                            Node                                                                         Warning   FailedToCreateRoute     route_controller                    Could not create route fc55f84c-5ec0-11e8-b126-0a58ac1f0c18 10.244.2.0/24 for node virtual-kubelet-myaciconnector-linux after 236.274552ms: instance not found
1m          1m           16        virtual-kubelet-myaciconnector-linux.15315d56e843bfa8                            Node                                                                         Warning   FailedToCreateRoute     route_controller                    (combined from similar events): Could not create route fc55f84c-5ec0-11e8-b126-0a58ac1f0c18 10.244.2.0/24 for node virtual-kubelet-myaciconnector-linux after 106.745435ms: instance not found

**Do you know how to solve this problem?**

**Comment by lmiroslaw** [comment]
A great workaround. Will test it asap.

**Comment by lmiroslaw** [comment]
Unfortunately, the problem still persist. Maybe it is related to virtual-kubelet, see https://github.com/virtual-kubelet/virtual-kubelet/issues/222

**Comment by sauryadas** [comment]
@rbitia can you please take a look? also request that this be moved to the vk repo
