### ISSUE TITLE
[BUG] AKS Operations failing because the AKS LB Frontend IP configuration got "1-" appended in front of the name

### ISSUE THREAD

**Issue by AndreiBarbu95** [Azure/AKS#3925]
**Describe the bug**
Operations at AKS level are failing with error like below. When checking the Frontend IP configuration, it was concluded it gets a "1-" in front of the name.

_Resource /subscriptions/[subscription-id]/resourceGroups/[infra-rg-name]/providers/Microsoft.Network/loadBalancers/kubernetes/frontendIPConfigurations/9f77a12f-91bf-43d8-8749-c4990da27eea referenced by resource /subscriptions/[subscription-id]/resourceGroups/[infra-rg-name]/providers/Microsoft.Network/loadBalancers/kubernetes/outboundRules/aksOutboundRule was not found. Please make sure that the referenced resource exists, and that both resources are in the same region_

**To Reproduce**
N/A

**Expected behavior**
Avoid having the "1-" in front of the Frontend IP configuration name and perform the operations properly.

**Mitigation steps**
IMPORTANT!: These steps worked in a specific scenario, but before applying them, you may want to confirm them with support or wait for the hotfix.

-Go to Azure portal, AKS Infrastructure resource group ->Kubernetes load balancer named "kubernetes"-> Frontend IP configuration.
-In your portal, you will find that one of your configuration names was changed to 1-[IPName] (1-9f77a12f-91bf-43d8-8749-c4990da27eea). And this is the reason why we met this issue.
-Delete this frontend IP configuration, and then create a new configuration with previous name, in our example “9f77a12f-91bf-43d8-8749-c4990da27eea” and choose your previous public IP address.
-After that, go to Outbound Rules, and link existing aksOutboundRule with the new created frontend IP configuration.
-After that, reconcile the cluster with "az aks update -g [aks-rg] -n [aks-name]".

**Status**
AKS team is aware of the issue and a hotfix is ongoing.

**Comment by feiskyer** [comment]
A hotfix has rolled out and fixed this issue.

**Comment by emmanuelgeorge86** [comment]
We are still seeing this frontend IP issues in few of our AKS clusters. Seems to be hotfix is not rolled out in north Europe and West europe. can this be confirmed?
