### ISSUE TITLE
OSsku in-place migration (Linux only) [Feature]

### ISSUE THREAD

**Issue by oaljoundi** [Azure/AKS#3927]
The OSsku in-place migration feature allows the user to trigger a node image upgrade between one Linux SKU (i.e. Ubuntu) to another (i.e. Azure Linux) on an existing nodepool. Today, traditional OSsku migration involves creating a new node, cordoning and draining existing nodes, and then deleting existing nodes. This can involve a large surge of core count as new nodes are added, as well as manual intervention to cordon and drain.

This feature is available for public preview and can be deployed via ARM template and CLI (via AKS preview extension). Once GA, it will be available via Terraform as well. 

Link to docs: https://learn.microsoft.com/en-us/azure/azure-linux/tutorial-azure-linux-migration?tabs=azure-cli#in-place-os-sku-migration-preview

**Comment by aizuddin85** [comment]
Do we have any tentative timeline for GA?

**Comment by oaljoundi** [comment]
Hi @aizuddin85, we're aiming for GA in the next 4(ish) weeks, depending on when core CLI and Terraform support lands. Thanks!

**Comment by aizuddin85** [comment]
> Hi @aizuddin85, we're aiming for GA in the next 4(ish) weeks, depending on when core CLI and Terraform support lands. Thanks! 

I heard from PG that this feature got green light for rolled out and left with TF work. Do you have ETA for this to be fully GA?

**Comment by Bj3MaS** [comment]
any news on this ?

**Comment by aizuddin85** [comment]
> any news on this ?

I got ETA mid-July from AKS Product team. Im eagerly waiting this since March.

**Comment by allyford** [comment]
We're on track for a mid-July release. Stay tuned for an announcement coming soon!

**Comment by kipusoep** [comment]
For anyone visiting this and trying to do an in-place OS sku update; you need to enable the OSSKUMigrationPreview feature `az feature register --namespace Microsoft.ContainerService --name OSSKUMigrationPreview` and use `az provider register -n Microsoft.ContainerService` when it's registered.

**Comment by aizuddin85** [comment]
> For anyone visiting this and trying to do an in-place OS sku update; you need to enable the OSSKUMigrationPreview feature `az feature register --namespace Microsoft.ContainerService --name OSSKUMigrationPreview` and use `az provider register -n Microsoft.ContainerService` when it's registered.

I reckon its already GA as public preview section was removed from the docs. We still need to enable it like this? Thats weird.

**Comment by kipusoep** [comment]
It's not, because I got an error that it's not supported when trying to migrate using ARM template deployment.

**Comment by suhuruli** [comment]
Hi @kipsusoep and @aizuddin85 - the preview documentation was removed due to the rollout having started so I would track https://releases.aks.azure.com/ to see where [v20240716](https://github.com/Azure/AKS/releases/tag/2024-07-16) is available and in those regions you don't need the preview flag. In other regions, you may still need it while the rollout happens.

**Comment by kipusoep** [comment]
Ah thanks for clearing that up @suhuruli. It seems West Europe is still on v20240627.

**Comment by suhuruli** [comment]
No worries @kipusoep, it's a valid concern that we need to address when we ship GA documentation. There is always a period of time between the time we merge the GA documentation and the rollout completing. Perhaps we should leave the preview documentation until rollout is majority completed.

**Comment by Bj3MaS** [comment]
Tried to migrate on a production cluster, it does not take into account for surge. During upgrade it cordon all the nodes and drained them in parallell. Is there an extra flag i need to set?

Was following this doc https://learn.microsoft.com/en-us/azure/azure-linux/tutorial-azure-linux-migration?tabs=azure-cli

**Comment by suhuruli** [comment]
Hi @Bj3MaS, tried repro-ing this and had some difficulty. I noticed the surge capacity respected during the upgrade process. Do you have the output of `kubectl get events` by any chance? For reference, here is the output from a cluster I just tried which shows with `max-surge-capacity` set to 1 on a nodepool with 3 nodes, the cordon and draining happened node-by-node and surge capacity was respected. Look forward to hearing back so we can help you with this issue. 

```bash
0s          Warning   ContainerdStart           node/aks-nodepool1-41088331-vmss000006   Starting containerd container runtime...
0s          Warning   ContainerdStart           node/aks-nodepool1-41088331-vmss000006   Starting containerd container runtime...
0s          Normal    Surge                     node/aks-nodepool1-41088331-vmss000006   Created a surge node aks-nodepool1-41088331-vmss000006 for agentpool nodepool1
0s          Normal    Drain                     node/aks-nodepool1-41088331-vmss000000   Draining node: aks-nodepool1-41088331-vmss000000
0s          Normal    NodeReady                 node/aks-nodepool1-41088331-vmss000000   Node aks-nodepool1-41088331-vmss000000 status is now: NodeReady
0s          Normal    RegisteredNode            node/aks-nodepool1-41088331-vmss000000   Node aks-nodepool1-41088331-vmss000000 event: Registered Node aks-nodepool1-41088331-vmss000000 in Controller
0s          Normal    Starting                  node/aks-nodepool1-41088331-vmss000000
0s          Warning   ContainerdStart           node/aks-nodepool1-41088331-vmss000000   Starting containerd container runtime...
0s          Warning   ContainerdStart           node/aks-nodepool1-41088331-vmss000000   Starting containerd container runtime...
0s          Normal    Upgrade                   node/aks-nodepool1-41088331-vmss000000   Successfully reimaged node: aks-nodepool1-41088331-vmss000000
0s          Normal    Upgrade                   node/aks-nodepool1-41088331-vmss000000   Successfully upgraded node: aks-nodepool1-41088331-vmss000000
0s          Normal    Drain                     node/aks-nodepool1-41088331-vmss000001   Draining node: aks-nodepool1-41088331-vmss000001
0s          Normal    NodeReady                 node/aks-nodepool1-41088331-vmss000001   Node aks-nodepool1-41088331-vmss000001 status is now: NodeReady
0s          Normal    RegisteredNode            node/aks-nodepool1-41088331-vmss000001   Node aks-nodepool1-41088331-vmss000001 event: Registered Node aks-nodepool1-41088331-vmss000001 in Controller
0s          Normal    Starting                  node/aks-nodepool1-41088331-vmss000001
0s          Warning   ContainerdStart           node/aks-nodepool1-41088331-vmss000001   Starting containerd container runtime...
0s          Warning   ContainerdStart           node/aks-nodepool1-41088331-vmss000001   Starting containerd container runtime...
0s          Normal    Upgrade                   node/aks-nodepool1-41088331-vmss000001   Successfully reimaged node: aks-nodepool1-41088331-vmss000001
0s          Normal    Upgrade                   node/aks-nodepool1-41088331-vmss000001   Successfully upgraded node: aks-nodepool1-41088331-vmss000001
0s          Normal    Drain                     node/aks-nodepool1-41088331-vmss000002   Draining node: aks-nodepool1-41088331-vmss000002
0s          Normal    NodeReady                 node/aks-nodepool1-41088331-vmss000002   Node aks-nodepool1-41088331-vmss000002 status is now: NodeReady
0s          Normal    RegisteredNode            node/aks-nodepool1-41088331-vmss000002   Node aks-nodepool1-41088331-vmss000002 event: Registered Node aks-nodepool1-41088331-vmss000002 in Controller
0s          Normal    Starting                  node/aks-nodepool1-41088331-vmss000002
```

**Comment by suhuruli** [comment]
Hey @Bj3MaS - checking in to see if you can provide the info requested. We are definitely interested in addressing this issue if we get some more details since this would be erroneous behavior!
