### ISSUE TITLE
[Question] Does AKS support updating to user-assigned MI cluster+kubelet MI from SP-based cluster in one update command

### ISSUE THREAD

**Issue by srxmsft** [Azure/AKS#3938]
**Describe scenario**
We have service principal based AKS and want to migrate to user-assigned cluster MI + user-assigned kubelet MI in one update command.

**Question**
In the AKS MI documentation [https://learn.microsoft.com/en-us/azure/aks/use-managed-identity] and "the Pre-created kubelet identity limitations", it says it only works with a user-assigned MI managed cluster.
And in the later example "Update an existing cluster using kubelet identity", it also confirm if the cluster is in cluster MI mode first.

Does AKS support updating to user-assigned-cluster-mi + user-assigned-kubelet-mi from SP-based cluster with one command below?
Is this scenario tested and no downtime expected (except node draining)?
az aks update \
    --resource-group myResourceGroup \
    --name myManagedCluster \
    --enable-managed-identity \
    --assign-identity <identity-resource-id> \
    --assign-kubelet-identity <kubelet-identity-resource-id>

**Comment by srxmsft** [comment]
anyone can help?

**Comment by PixelRobots** [comment]
> anyone can help? 

Hello. 

Have you checked this docs page?  https://learn.microsoft.com/en-us/azure/aks/use-managed-identity#enable-managed-identities-on-an-existing-aks-cluster

If you have tried that are you getting any errors?
