### ISSUE TITLE
Failed to setup network for sandbox Failed to create endpoint: TransparentEndpointClient Error : operation not supported

### ISSUE THREAD

**Issue by andriktr** [Azure/AKS#3939]
After node restart pods not starting and hangs in Unknows status kubelet drops the following messages:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "0bc75e4c9f785c657c13bf1ad27a6e8f652ec01c8b48042acf2a27067edfa2e7": plugin type="azure-vnet" failed (add): Failed to create endpoint: TransparentEndpointClient Error : operation not supported
```
Here is how the pods looks like (all daemonsets): 

<img width="981" alt="image" src="https://github.com/Azure/AKS/assets/25537180/8f993a56-1295-4340-a76c-b30a32f8b018">

Pods which I tried to recreate are stuck in ContainerCreating status. 

Noticed that problematic node has newer kernel version: 
<img width="1188" alt="image" src="https://github.com/Azure/AKS/assets/25537180/ac28a692-c1f3-42e5-a346-5bca6158ef6c">

Restarting node, kubelet service or azure-cns pods does not helps. 

Any thoughts?

**Comment by andriktr** [comment]
Seems issue is related to the following https://github.com/Azure/azure-container-networking/issues/2156

**Comment by rmovieira** [comment]
Same here! Some deploys have worked, but some other don't

**Comment by bartoszpyrek** [comment]
Same issue also exists in the kernel version 6.2.0-1015-azure.

**Comment by arpanD93** [comment]
For me the error was -  **[(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox]**

I was running AKS - 1.26.3 and Azure CNI.

After restarting the cluster from portal, this issue got resolved.

**Comment by yauhen-vastraknutau-epam** [comment]
Same issue with AKS 1.26.10 and Azure CNI

**Comment by andriktr** [comment]
For me node re-image solved the issue https://learn.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-reimage

**Comment by melkamar** [comment]
I have encountered the same issue. Pod scheduled on a particular node (which had a kernel version `6.x`) kept crashing and the whole cluster was wonky.

The solution to the problem was to upgrade the VMSS to the latest scale set model ([stackoverflow](https://stackoverflow.com/a/70678183/428173)). After upgrading to latest, the kernel version changed to `5.15.0-1057-azure` and all works OK now.

**Comment by tamilmani1989** [comment]
CNI with fix has been released several months back. You may need to upgrade your VMSS to get new CNI for clusters using nodesubnet.
Issue tracked in CNI side - https://github.com/Azure/azure-container-networking/issues/2156

**Comment by AllenWen-at-Azure** [comment]
Closing the issue per comment from @tamilmani1989
