### ISSUE TITLE
Network Observability add-on for an existing AKS cluster

### ISSUE THREAD

**Issue by outifaout** [Azure/AKS#3942]
Hi everyone,
I tried to set up the network observability add-on using the cli command : az aks update \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --enable-network-observability

but it doesn't seem to work, no change noticed, the add-on has not been enabled and the cluster is not shown in the managed Grafana Kubernetes/Networking dashboard.

Anyone has experienced this ?

**Comment by abarqawi** [comment]
@outifaout did you complete the steps as per this article https://learn.microsoft.com/en-us/azure/aks/network-observability-managed-cli?tabs=non-cilium#create-azure-monitor-resource
and linked the grafana to AKS?

https://learn.microsoft.com/en-us/azure/aks/network-observability-managed-cli?tabs=non-cilium#azure-managed-prometheus-and-grafana

**Comment by outifaout** [comment]
@abarqawi Yes I did..
