### ISSUE TITLE
Azure CNI Overlay Dualstack Support (Linux)

### ISSUE THREAD

**Issue by chasewilson** [Azure/AKS#3943]
Azure CNI Overlay supports Dualstack Networking allowing for scalability and IPv6 Traffic to and from cluster

Estimated GA Date: 03/19/2024
[Documentation Link](https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay)

**Comment by JSnow38** [comment]
Hi @chasewilson,

We were doing some testing with the Dualstack CNI Overlay and noticed it is only available in certain regions (available in EUS2, but not CUS).  is there a chart that shows availability while it's in preview?

Thanks!

Jeff
