### ISSUE TITLE
VPA with "in-place" patch of resource allocation for pods

### ISSUE THREAD

**Issue by aevlogiev** [Azure/AKS#3950]
With kubernetes 1.27 they introduces In-place Resource Resize for Kubernetes Pods (alpha) and released feature: InPlacePodVerticalScaling - https://kubernetes.io/blog/2023/05/12/in-place-pod-resize-alpha/

Is there work already done/started on VPA addon for aks ? - https://learn.microsoft.com/en-us/azure/aks/vertical-pod-autoscaler

Currently, Auto is equivalent to Recreate, and also is the default mode. Once restart free ("in-place") update of pod requests is available, it may be used as the preferred update mechanism by the Auto mode.

This feature will drastically improve the overall capability if VPA is able to use the in-place feature that was introduced in 1.27 and maintain 0 downtime as pods are no longer restarted to apply.

**Comment by carlosbustillordguez** [comment]
Any update on this? Would be nice to have enabled the InPlacePodVerticalScaling feature gate in AKS v1.27+. Thanks!

**Comment by andreyolv** [comment]
ANy update? Very interesting feature

**Comment by andreyolv** [comment]
Any update? Very interesting feature

**Comment by michal-poliwka** [comment]
Hi, any update on this? Is InPlacePodVerticalScaling  available in aks?

**Comment by bplasmeijer** [comment]
We should have InPlacePodVerticalScaling on Linux and Windows workloads.

https://github.com/kubernetes/enhancements/issues/1287
[The New In-Place Kubernetes Pod Resource Resizing Feature: A Deep Dive](https://medium.com/@seifeddinerajhi/the-new-in-place-kubernetes-pod-resource-resizing-feature-a-deep-dive-11b0ece334ef#:~:text=In-place%20pod%20resource%20resizing%20is%20a%20new%20feature%20in,efficiency%20without%20causing%20any%20downtime.)

cc: @palma21 / @justindavies

**Comment by palma21** [comment]
We will, as it turns Beta and enabled by default, which right now IIRC is slated for 1.30 (?)

**Comment by iamandycohen** [comment]
This would be a huge benefit for us; in cost savings and in resiliency.  Our application is bursty.

**Comment by bplasmeijer** [comment]
> We will, as it turns Beta and enabled by default, which right now IIRC is slated for 1.30 (?) it should be alpha before that.

Could Microsoft provide assistance in this regard @palma21 @justindavies?

**Comment by satrox28** [comment]
Hi, do you have any update?.

Is it available now?

**Comment by gerbil** [comment]
Any updates? Status?

**Comment by aevlogiev** [comment]
I will give an update:
Current state of InPlacePodVerticalScaling is alpha enabled:false
With Kubernetes 1.32 they did some tweaks for:
Version skew strategy update for InPlacePodVerticalScaling for beta graduation.
Here you can read the state of the feature still its in 1.27 release alpha: https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/
The feature haven't yet met Aks requirements = Beta enabled:true
In Kubernetes prerelease [Kubernetes v1.32.0-rc.1](https://github.com/kubernetes/kubernetes/releases/tag/v1.32.0-rc.1) is announced tor graduation. Therefore this feature won't be available at least by 1.33 GA version or a patch of 1.32 when it comes to GA version.

IMPORTANT: They dropped InPlacePodVerticalScaling for windows

Hope that helps see you in few months. :)

**Comment by AndreiDoroftei** [comment]
Hi @aevlogiev !
FEATURE STATE: Kubernetes v1.33 [beta] (enabled by default: true)

When do you think it will become available for AKS? Any premonition? 😄

**Comment by aevlogiev** [comment]
> Hi [@aevlogiev](https://github.com/aevlogiev) ! FEATURE STATE: Kubernetes v1.33 [beta] (enabled by default: true)
> 
> When do you think it will become available for AKS? Any premonition? 😄

Well we are at upstream release on aks for 1.33 from last month. It should go preview this month, so Live will be although stated in their article that preview and GA will be this month, I assume that within couple of weeks we need to have 1.33 aks.
So hold tight :).

**Comment by AndreiDoroftei** [comment]
It is available. We already use it in our clusters.

**Comment by AAFAYZ** [comment]
@AndreiDoroftei I tested last week. Pod spec is still not supporting the value and there are no other Microsoft documents which confirms the in place upgrade is rolled out. And here is an AKS Roadmap: https://github.com/Azure/AKS/issues/5072 which says they are not doing it. How are you saying it that it is available without any relevant reference links?

**Comment by dtiwari3011** [comment]
@AAFAYZ You can use this [document](https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/) to test on AKS 1.33.1. The command for patch is bit different for in place patch
```
kubectl patch pod resize-demo --subresource resize --patch \
  '{"spec":{"containers":[{"name":"pause", "resources":{"requests":{"cpu":"800m"}, "limits":{"cpu":"800m"}}}]}}'
```
I have tested this in AKS 1.33.1 and I can confirm that it works

**Comment by AAFAYZ** [comment]
@dtiwari3011 The one you have pasted is manual patching of the new resource request and limits and Kubernetes is restarting the container without an user restarting the pod, but that's not the use case. VPA will be restarting the containers instead of recreating the pods which is not mentioned right now for AKS. Hope you can understand now

**Comment by dtiwari3011** [comment]
@AAFAYZ You are correct. VPA project is still in progress and it doesn't support yet. However, you can create your in place controller by yourself using the same feature of AKS.

**Comment by AndreiDoroftei** [comment]
As for our clusters, we are using [Kube Startup CPU Boost](https://github.com/google/kube-startup-cpu-boost) and it does work.

**Comment by AAFAYZ** [comment]
Thanks for the confirmation @dtiwari3011, @AndreiDoroftei thats wonderful
