### ISSUE TITLE
StatefulSets Lost Volumes 

### ISSUE THREAD

**Issue by p8952** [Azure/AKS#396]
Looks like the issue first occurred  at `2018-05-26T08:08 UTC` in `West Europe` region.

Pods created by my StatefulSets are reporting: `AttachVolume.Attach failed for volume "pvc-e67cec88-4c55-11e8-8024-0a58ac1f001f" : failed to get azure instance id for node "aks-agentpool-37033213-0"
Error syncing pod`

StatefulSets are reporting: `Error creating load balancer (will retry): Error getting LB for service default/couchdb: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/e6f9d9e5-8fe9-4698-967e-2365e43755b1/resourceGroups/MC_Kubernetes-Production_Kubernetes-Production_westeurope/providers/Microsoft.Network/loadBalancers/kubernetes?api-version=2017-03-01: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '401'`

**Comment by p8952** [comment]
@andyzhangx Yes, but one generated manually as per an older version of this document: https://github.com/MicrosoftDocs/azure-docs/blob/64800109813d108ebc61b0f0e41bb166cbf544fa/articles/aks/kubernetes-walkthrough-portal.md

The credentials were working when the cluster was setup (Successfully provisioned a LB & storage), but appeared to stop working at `2018-05-26T08:08`.

Interestingly my new cluster which the Azure Portal automatically generated a Service Principle for does not have a `Password` configured under `Azure Active Directory` -> `App Registrations` -> `<DISPLAY NAME>` -> `Settings` -> `Keys`?

This is where I was previously generating the Service Principle Client Secret.

**Comment by p8952** [comment]
Is there any more information I can provide the issue before I remove this cluster?

**Comment by andyzhangx** [comment]
this is a credential invalid issue, you may remove the cluster now.

**Comment by p8952** [comment]
Do you know why the credentials would have become invalid? Or how to update them in the future should the issue re-occur on a different cluster?

**Comment by andyzhangx** [comment]
@p8952 could you find that service principal on azure portal, every service principal should have expiration time.

**Comment by p8952** [comment]
![screenshot-portal azure com-2018 06 06-16-27-11](https://user-images.githubusercontent.com/2962587/41048393-84477c40-69a6-11e8-968c-1a86687d527e.png)

`Password` is the original Service Principle Client Secret, `Password2` is one I created while debugging during the incident.

**Comment by jnoller** [comment]
Closing as stale
