### ISSUE TITLE
[BUG] Custom Resources filter based on namespace selected under Workloads

### ISSUE THREAD

**Issue by mbendtsen** [Azure/AKS#3962]
**Describe the bug**

**To Reproduce**
1. Go to Workloads
2. Select a namespace
3. Go to Custom Resources
4. Click on a resource

**Expected behavior**
Because there are no namespace selector in this view, I would not have thought that it would filter on the selected namespace from under Workloads. It took me some time to realize that the data was filtered. 

**Screenshots**
![image](https://github.com/Azure/AKS/assets/338354/be4dfd1b-6906-40c8-b1e5-1681e39fe8b1)
![image](https://github.com/Azure/AKS/assets/338354/f4ddc63f-2a2a-4a2a-bcd2-a034382388f5)
![image](https://github.com/Azure/AKS/assets/338354/a6bfc76a-adea-4163-be2a-7ae24faaf640)

**Environment (please complete the following information):**
 - Kubernetes version 1.26.3
 - Browser: Edge 118.0.2088.57

**Additional context**

**Comment by chandraneel** [comment]
taking a look

**Comment by chandraneel** [comment]
The filtering is now fixed, to reflect in the namespace dropdown in the view.
![Image](https://github.com/user-attachments/assets/3a5d3e41-5eb8-4ea1-a48c-da6fa0a9867d)
