### ISSUE TITLE
Outbound-type migration

### ISSUE THREAD

**Issue by chasewilson** [Azure/AKS#3963]
You can now update existing clusters to new outbound types

Expected GA: January 31 2024

**Comment by implodingduck** [comment]
Is there any update on this feature going GA?

**Comment by scottstout** [comment]
@chasewilson any update on forecasted GA date?

**Comment by chasewilson** [comment]
Aiming for ver soon. Hopefully this month. Next at the latest

**Comment by scottstout** [comment]
There is a blog post indicating that this feature is GA. Is that right? Why is the ticket still open? https://azure.microsoft.com/en-in/updates/generally-available-outbound-type-migration-in-aks/
