### ISSUE TITLE
[BUG] AKS node with Ubuntu 22.04.3 or Azure Linux (CBL-Mariner/Linux [Kernel-5.15.131.1-2.cm2]) is super slow when the CPU-intensive Pods run. Also both the POD and node CPU goes 95% constantly.

### ISSUE THREAD

**Issue by PremSahooESL** [Azure/AKS#3969]
**Describe the bug**
AKS node OS with Ubuntu 22.04.3 is super slow when the CPU-intensive Pods run. Also both the POD and node CPU goes 95% constantly.

**To Reproduce**
CPU-intensive pods tested with node OS Ubuntu 22.04.3 or Azure Linux (CBL-Mariner/Linux [Kernel-5.15.131.1-2.cm2]) is super slow.
CPU-intensive pods tested with node OS Ubuntu 22.04.2 or Ubuntu 18.04.x. pretty much faster.

**Expected behavior**
Same CPU-intensive pods were much faster when scheduled on AKS node with Ubuntu 22.04.2 or Ubuntu 18.04.x

**Environment (please complete the following information):**
 - Kubernetes version [1.25.6, 1.26.6]

**Additional context**

**Comment by PremSahooESL** [comment]
Is there a way to choose AKS Node OS as Ubuntu 22.04.2 explicitly on AKS version 1.25.x or 1.26.x?

**Comment by ravisolu** [comment]
Any update on this ?

**Comment by PremSahooESL** [comment]
Looks, This performance issue has been resolved on the AKS version 1.28.x afterwards.
