### ISSUE TITLE
[BUG] az aks nodepool add: 'AzureLinux' is not a valid

### ISSUE THREAD

**Issue by prathyushmr2** [Azure/AKS#3970]
**Describe the bug**
az aks nodepool add: 'AzureLinux' is not a valid value for '--os-sku'. Allowed values: Ubuntu, CBLMariner, Mariner, Windows2019, Windows2022

**Comment by daalse** [comment]
Can you check what az cli version you are using?
I have 'AzureLinux' option with az cli version 2.51.0

**Comment by michaelgregson** [comment]
Seeing the same issuse:

`az aks nodepool add: 'AzureLinux' is not a valid value for '--os-sku'. Allowed values: Ubuntu, CBLMariner, Mariner, Windows2019, Windows2022.`

Cli Version information, on OSX 14.0

`az --version
azure-cli                         2.53.1

core                              2.53.1
telemetry                          1.1.0

Extensions:
aks-preview                      0.5.128

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/bin/python'
Extensions directory '/Users/Redacted/.azure/cliextensions'

Python (Darwin) 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.0.40.1)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.`

**Comment by michaelgregson** [comment]
And, the output of that pointed me in the correct direction. The aks-preview extension required updating.

`az extension update --name aks-preview`

Hope this helps

**Comment by AllenWen-at-Azure** [comment]
Close this issue as it was answered in https://github.com/Azure/AKS/issues/3970#issuecomment-1786974243.
