### ISSUE TITLE
[BUG] Azure portal saying all pools are Windows

### ISSUE THREAD

**Issue by jabbera** [Azure/AKS#3971]
**Describe the bug**
Azure Portal is saying all of my pools across 2 clusters are windows even though they are Linux (we don't have any windows pools)

**To Reproduce**
1. Create AKS cluster with Linux node pools. 
2. See windows as the type in the portal

**Expected behavior**
Type should say linux

**Screenshots**
<img width="716" alt="image" src="https://github.com/Azure/AKS/assets/301208/4676b098-1e6a-4979-9a66-fd1086f0edf8">

Export of arm template:
```
{
  "name": "gurobi",
  <SNIP>
  "osType": "Linux",
  "osSKU": "Mariner",
  "enableFIPS": false
}
```

**Comment by aritraghosh** [comment]
@jabbera  Thanks for reporting the issue. Could you create a support case with details, It is a little strange that the node count shows up as 0

**Comment by jabbera** [comment]
Will do but that's a pool we scale up/down manually.
