### ISSUE TITLE
[Question] 1.19.13 to 1.25.6 upgrade !

### ISSUE THREAD

**Issue by julyfirst** [Azure/AKS#3977]
Hello, I'm a subscriber to Azure.
I'm currently using Kubernetes service, but the certificate is expired, so x509 error occurs, but if I update Kubernetes version, will the certificate be updated as well?
And Kubernetes version is 1.19.13. When I tried to upgrade through the Azure homepage, only the update to version 1.25.6 is supported, but wouldn't there be a problem if I skip the intermediate version and upgrade to version 1.25.6 immediately?
Thank you.

**Comment by CocoWang-wql** [comment]
Hello @julyfirst,  1.upgrade will not help to rotate the cert, you need to[ rotate it manually](https://learn.microsoft.com/en-us/azure/aks/certificate-rotation#check-certificate-expiration-dates) (make sure the error is about cert expired). 2.Version 1.19 is old and not supported any more, thus you need to skip-upgrade to the minimun supported version. You'd better chech the [upgrade best practice](https://learn.microsoft.com/en-us/azure/architecture/operator-guides/aks/aks-upgrade-practices#pre-upgrade-considerations) to reduce the influence.

**Comment by julyfirst** [comment]
@CocoWang-wql 
Thanks for the reply but
I have already migrated to a higher version and am using it without any problems.

**Comment by CocoWang-wql** [comment]
Good to know that! Thanks for the update~ I will close this issue and pls let me know in case any more conern.
