### ISSUE TITLE
Bump Azure CNS to a version that has at least 0.26.4 client.go version

### ISSUE THREAD

**Issue by SSvilen** [Azure/AKS#3991]
We use prometheus adapter and due [this bug](https://github.com/kubernetes/kubernetes/issues/118361) installing kubernetes 1.27 breaks anzure cns. 

As far as I can tell, version [1.15.11](https://github.com/Azure/azure-container-networking/blob/v1.5.11/go.mod#L48) is the earliest version that has that library not with version 0.26.3 (0.28.0)

**Comment by philwelz** [comment]
Hey, with the 4 latest node images you will get azure-cns v1.4.51 (client.go v0.26.10) and v1.5.15 (client.go v0.28.0). So please upgrade to one of those images.

- [202401.17.1](https://raw.githubusercontent.com/Azure/AgentBaker/master/vhdbuilder/release-notes/AKSUbuntu/gen1/2204containerd/202401.17.1.txt)
- [202401.09.0](https://raw.githubusercontent.com/Azure/AgentBaker/master/vhdbuilder/release-notes/AKSUbuntu/gen1/2204containerd/202401.09.0.txt)
- [202401.03.0](https://raw.githubusercontent.com/Azure/AgentBaker/master/vhdbuilder/release-notes/AKSUbuntu/gen1/2204containerd/202401.03.0.txt)
- [202312.06.0](https://raw.githubusercontent.com/Azure/AgentBaker/master/vhdbuilder/release-notes/AKSUbuntu/gen1/2204containerd/202312.06.0.txt)

I will close the issues. Feel free to re-open if the answer is not satisfying.

**Comment by SSvilen** [comment]
@philwelz yeah, thanks. We do update them on biweekly basis, so the issue is long gone. Forgot to close this issue
