### ISSUE TITLE
How to remove cached images on a node from Azure container registry

### ISSUE THREAD

**Issue by alejandromiller21** [Azure/AKS#4001]
**Describe scenario**
I'd like to remove older images from my AKS Cluster in order to keep it clean. I push my Docker images to my Azure container registries, and then pull in AKS version 1.27.3 from Azure. As I tried to enable Image Cleaner, the only watched Microsoft images were removed, not those in the container repositories:

Command used:
az aks update \
  --resource-group myResourceGroup \
  --name myManagedCluster \
  --enable-image-cleaner

**Question**
What can I do to keep my AKS clean of old images?

**Comment by PixelRobots** [comment]
Hello, quick question, are you wanting the images to be removed from the container registry also? Or are you just noticing that older non-used images that are from your container registry are not removed from your nodes?

**Comment by alejandromiller21** [comment]
Hi @PixelRobots, What is the best way to remove older non-used images pulled from my ACR in my AKS nodes?

**Comment by alejandromiller21** [comment]
Thanks! Thanks! I'm not sure what I'm doing wrong... suppose I need to remove all unnecessary images from my repository, such as myacr and all its containers, such as app1 and app2?

For me, the following example does not work:

apiVersion: eraser.sh/v1alpha1
kind: ImageList
metadata:
  name: imagelist
spec:
  images:
    - myacr.azurecr.io/*

**Comment by PixelRobots** [comment]
For the images have you just tried "*"

I don't think it can do all of them in a repo. It's all, including public repos, or a set list you give it.

**Comment by sebader** [comment]
I just asked the related question here https://github.com/eraser-dev/eraser/issues/977

**Comment by CocoWang-wql** [comment]
Hello @alejandromiller21, pls let me know whether it works expected or you have any other concern. Thanks
