### ISSUE TITLE
Installation of extension on AKS communicates with .dp.kubernetesconfiguration.azure.com. [BUG]

### ISSUE THREAD

**Issue by cloud-az** [Azure/AKS#4004]
**Describe the bug**
During the upgrade to Cilium Enterprise on [AKS with Azure CNI Overlay empowered with Cilium](https://learn.microsoft.com/en-us/azure/aks/azure-cni-powered-by-cilium) the extension pods communicate with the endpoint [<region>.dp.kubernetesconfiguration.azure.com](https://westeurope.privatelink.dp.kubernetesconfiguration.azure.com/). Despite this endpoint is  typically associated with Azure ARC enabled Kubernetes clusters [Azure ARC enabled Kubernetes](https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/network-requirements?tabs=azure-cloud) clusters.

**To Reproduce**
Upgrade to Isovalent Enterprise. 

**Expected behavior**
No need to call the endpoint for Azure ARC enabled kubernetes.

**Screenshots**
![image](https://github.com/Azure/AKS/assets/130577660/ebfcfb65-0903-458e-a595-3b8f9122d4ae)

**Environment (please complete the following information):**
 - AKS version 1.26.6 - Linux nodes
 - Azure CNI overlay + Cilium data platform

**Comment by philwelz** [comment]
ARC enabled Kubernetes and AKS Cluster extensions using `<region>.dp.kubernetesconfiguration.azure.com` to fetch information:

> This address is used to fetch configuration information from the Cluster Extensions service and report extension status to the service.

You can find this also in the docs section [Outbound network and FQDN rules for AKS ](https://learn.microsoft.com/en-us/azure/aks/outbound-rules-control-egress#required-fqdn--application-rules-4)

Im closing the issue. Feel free to re-open if the answer is not satisfying.

**Comment by cloud-az** [comment]
@philwelz Why does AKS Clusters use the same endpoint as ARC enabled Kubernetes for extensions? this causes us issues.

**Comment by philwelz** [comment]
hi @cloud-az i dont know any details but when im guessing it doesnt make sence do create two different implementations for extensions. So they just using the same.

**Comment by erwinkramer** [comment]
@philwelz it is a design flaw IMO. Consider a team configuring `Azure Arc Private Link Scope`, then putting a private endpoint on that APLS, then registering all the required DNS configs for that private endpoint. Then you're done, normal AKS now points to an APLS for `.dp.kubernetesconfiguration.azure.com` requests (for instance for extensions - like @cloud-az  pointed out. Totally not what anyone would expect.
