### ISSUE TITLE
[Feature] App Routing addon - Allow select global configuration of nginx ingress controller through the NginxIngressController CRD

### ISSUE THREAD

**Issue by sabbour** [Azure/AKS#4005]
While today users can override some nginx ingress configuration on individual ingress object through [annotations](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations), some users would like to configure settings such as the default backend, custom errors, SSL redirects, default SSL certificate, etc. at the ingress controller level.

We should offer a way to configure a selection of common configurations from the [nginx configuration ConfigMap](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/) through the NginxIngressController object.

Support:
- [custom-http-errors](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#custom-http-errors)
- [force-ssl-redirect](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#force-ssl-redirect)
- [--default-ssl-certificate CLI argument](https://kubernetes.github.io/ingress-nginx/user-guide/cli-arguments/)
- [--default-backend-service CLI argument](https://kubernetes.github.io/ingress-nginx/user-guide/cli-arguments/) - check if we need to provide a `/healthz` endpoint

**Comment by OliverMKing** [comment]
Also should provide an option for removing http as an option from App Routing.

**Comment by sabbour** [comment]
Related:
https://github.com/Azure/aks-app-routing-operator/pull/173
https://github.com/Azure/aks-app-routing-operator/pull/166
https://github.com/Azure/aks-app-routing-operator/pull/174

**Comment by sabbour** [comment]
Going out with K8s 1.30

**Comment by sabbour** [comment]
Shipped https://learn.microsoft.com/en-us/azure/aks/app-routing-nginx-configuration#configuration-of-the-nginx-ingress-controller
