### ISSUE TITLE
[Feature request] Adding data disks to AKS nodes

### ISSUE THREAD

**Issue by ams0** [Azure/AKS#401]
It could be possible to add data disks to nodes in AKS at provisioning time? Pretty much like 

```
        "diskSizesGB": [30, 30],
```
in acs-engine, or the option `--data-disk-sizes-gb` for the `az vm create` command. I'm playing around with OpenEBS, and it's easy to setup distributed storage on separated partitions, but it'll be easier if I have those disks mounted at boot (now I need to manually create/attach managed disks, and ssh into each node).

**Comment by zBurrito** [comment]
That would be great

**Comment by andyzhangx** [comment]
I think customer wants daemonset with volumeClaimTemplates support just like [statefulset](https://github.com/andyzhangx/demo/blob/master/linux/azuredisk/attach-stress-test/statefulset/statefulset-azuredisk1.yaml), while daemonset only supports one PVC(centralizing storage) now, does not support volumeClaimTemplates.
Per my knowledge, k8s level don’t have a solution. This is a feature request for AKS level.

**Comment by ams0** [comment]
Bumping this up, also because I'm looking into https://github.com/gluster/gluster-kubernetes and while I can (sort of) get it to run in acs-engine, it will be great to have volumes in AKS nodes that I could use for a hyper-converged storage.

**Comment by sauryadas** [comment]
@ams0 i am closing this here. Please create a feature request in the below link . Thanks 

https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks
