### ISSUE TITLE
[Question] Backup AKS PVs with Azure Backup for AKS with User Assigned Identity

### ISSUE THREAD

**Issue by DaDucCH** [Azure/AKS#4015]
**Describe scenario**
I'd like to use Azure Backup to backup a volume on my AKS cluster with a User Assigned Identity (not System Managed).

**Question**
According to this documentation it is not possible to do so: https://learn.microsoft.com/en-us/azure/backup/azure-kubernetes-service-cluster-backup-concept
Is this planned to become available or are you facing some technical issues there?
What would you see as the alternative if it would not become available?

**Comment by johgoe** [comment]
It seems to be working also with User-Assigned Managed Identities in our configuration. Can somebody please confirm it offically?

**Comment by AllenWen-at-Azure** [comment]
Hi @DaDucCH ,

As you can find in the document -  https://learn.microsoft.com/en-us/azure/backup/azure-kubernetes-service-cluster-backup-concept

> Azure Backup for AKS supports AKS clusters using either System Identity or User Identity, for backup operations. Although clusters using Service Principle aren't supported, you can [update such AKS cluster to use a Managed System Identity](https://learn.microsoft.com/en-us/azure/aks/use-managed-identity#enable-managed-identities-on-an-existing-aks-cluster).
