### ISSUE TITLE
[BUG] Autoscaler failed to scale up for spot nodepool due to remediator.aks.microsoft.com/unschedulable taint

### ISSUE THREAD

**Issue by OvervCW** [Azure/AKS#4016]
This is a request to reopen #2976 since it appears to still be reproducible today.

We are running an AKS cluster with Kubernetes version 1.27.3 and we have a spot node pool that's currently at 0 instances and fails to scale up:

>cluster-autoscaler  pod didn't trigger scale-up: 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) had untolerated taint {xxx: yyy}, 1 node(s) had untolerated taint {remediator.kubernetes.azure.com/unschedulable: }, 1 node(s) had untolerated taint {zzz: www}

This cluster has existed since before the original issue and I'm not sure how to check the version of the cluster autoscaler, but I assume that it was updated as part of the recent Kubernetes version update.

**Comment by kevinkrp93** [comment]
Had fixed this issue in the earlier version. Will take a look and update.

**Comment by BW256ab** [comment]
We are also experiencing this issue

**Comment by kevinkrp93** [comment]
fix rolled out
