### ISSUE TITLE
[Question] Is it safe to delete the "-windows" daemonsets (with 0 desired pods) if only Linux nodes will ever be used?

### ISSUE THREAD

**Issue by HummingMind** [Azure/AKS#4020]
**Describe scenario**
By default, AKS creates some daemonsets for Windows nodes. But I only use Linux nodes.

![image](https://github.com/Azure/AKS/assets/87399963/e80dd9fa-22b2-44d2-b3b1-079d4c2086fb)

**Question**
Is it safe to delete the "-windows" daemonsets if only Linux nodes will ever be used? Or will this break any potential upgrade scripts, etc?

I couldn't find anything in the documentation on this.
Thank you!

**Comment by andyzhangx** [comment]
those windows daemonsets are managed by AKS, so if you delete those daemonsets, AKS will reconcile it back after a few minutes, those windows daemonsets won't use any resource since pod num is zero.
