### ISSUE TITLE
[BUG] Upgrading AKS versions takes several hours and ends in a failed upgrade. 

### ISSUE THREAD

**Issue by ImIOImI** [Azure/AKS#4022]
**Describe the bug**
I've upgraded 3 clusters over the last week from version 1.26.10 to 1.27.7 to 1.28.3 using the azure aks UI. Every upgrade took about three hours and ended with the message "The cluster is currently in Failed state. Upgrade is disabled." The control plane always shows the version I've upgraded to and my nodes are all on the latest version with the latest image. Everything _looks_ fine after every upgrade. I then run the `az resource update...` command and the cluster's failed state is resolved

**To Reproduce**
On Azure UI navigate to `Kubernetes services`, select a cluster, click on kubernetes version in the Overview, click on Upgrade Version, select a version, then click save. Watch cluster to confirm the new version is rolled out to all nodes, wait about 3 more hours for the upgrade to fail, then run:

```
az resource update \
  --name ssp-use-prd \
  --namespace Microsoft.ContainerService \
  --resource-group <resource group> \
  --resource-type ManagedClusters \
  --subscription "<subscription id>" 
```

Wait for that to complete and confirm the cluster is in a non-failed state.

**Expected behavior**
I should be able to upgrade versions and after the control plane and nodes are rolled over to the new version (which takes about 10-30 minutes) the process should be able to recognize that its done a good job and report the upgrade as successful. 

**Environment (please complete the following information):**
 -  CLI Version [2.54.0]
 - Kubernetes version [1.26.10, 1.27.7, 1.28.3]
 - CLI Extension version [0.5.139] (aks-preview)
 - Browser [chrome]

**Comment by ImIOImI** [comment]
I'm not sure if this has been fixed, yet.

**Comment by kaarthis** [comment]
Can you share more info on why the failure - looking at activity logs and kubectl upgrade events may give you more details. Unless the core issue is fixed its hard for upgrades to succeed.

**Comment by ImIOImI** [comment]
> Can you share more info on why the failure - looking at activity logs and kubectl upgrade events may give you more details. Unless the core issue is fixed its hard for upgrades to succeed.

The logs for this are long gone, but the problem was that the cluster upgraded in a reasonable amount of time, but it took Azure an incredibly long time to realize the cluster was upgraded. If there were any core issues (that we're already resolved way ahead of time) those issues didn't persist through the process. 

I suspect I'll be testing this again when I start upgrading to 1.29 soon.

**Comment by AalimahG** [comment]
I had the same problem when upgrading a cluster from 1.28.3 to 1.29.4. The cluster remains in an "upgrading" state for a few hours before switching to "failed". The az resource update command updates the state to "succeeded". We should be able to upgrade without having to run this command immediately afterwards.
