### ISSUE TITLE
[Question] Why do we need AKS Image Cleaner if Kubelet itself perform garbage collection

### ISSUE THREAD

**Issue by pawarsum12** [Azure/AKS#4026]
To clean stable images AKS suggest to use Image cleaner (based on Eraser), however garbage collections is part of Kubelet. 
https://kubernetes.io/docs/concepts/architecture/garbage-collection/#containers-images

"The [kubelet](https://kubernetes.io/docs/reference/generated/kubelet) performs garbage collection on unused images every two minutes and on unused containers every minute. You should avoid using external garbage collection tools, as these can break the kubelet behavior and remove containers that should exist."

Please help me understand the use case where Image cleaner can be useful?

**Comment by PixelRobots** [comment]
In AKS the Kubelet is configured to run garbage collection based on percentage of disk usage. if the disk usage is below 80% it will never run garbage collection. If it is over 85% then it will always run. These values are [configurable if needed.](https://learn.microsoft.com/azure/aks/custom-node-configuration?tabs=linux-node-pools#kubelet-custom-configuration). 

Image cleaner will work before garbage collection kicks in and will remove any images that are not used and have CVE's. You can also configure image cleaner with a list of images you would like cleaned, but this is done via a manifest file.

So, the use case is to clean up vulnerable images that are not being used before the disk space hist 85% and garbage collection kicks inn.

Does this help answer your question at all?

**Comment by pawarsum12** [comment]
Make sense !! Closing this issue
