### ISSUE TITLE
[Question] Where is the documentation for node auto provision

### ISSUE THREAD

**Issue by jabbera** [Azure/AKS#4030]
**Describe scenario**
The following link: https://aka.ms/aks/nap found here https://azure.microsoft.com/en-us/updates/public-preview-node-autoprovision-support-in-aks/ doesn't seem to link to the feature and it seems nowhere to be found.

**Question**
Where is the documentation?

**Comment by PixelRobots** [comment]
Looks like it is still being published. #2442

**Comment by PixelRobots** [comment]
Looks like the docs are now working.

**Comment by jabbera** [comment]
Thanks! Looks amazing once some of the restrictions are removed.
