### ISSUE TITLE
[BUG] App Routing with DNS Zone does not always manage to update DNS entries

### ISSUE THREAD

**Issue by mymro** [Azure/AKS#4036]
**Describe the bug**
when enabling App Routing with a DNS Zone as described in the [Documentation](https://learn.microsoft.com/en-us/azure/aks/app-routing?tabs=default%2Cdeploy-app-default) you get the following error in the logs of the deployed DNS Pod and no DNS entries are created.

`
time="2023-12-15T11:07:21Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailed\" Message=\"The client '<Client-ID>' with object id '<Object-ID>' does not have authorization to perform action 'Microsoft.Network/dnsZones/read' over scope '/subscriptions/<Subscription-ID>/resourceGroups/<RG-ID>/providers/Microsoft.Network' or the scope is invalid. If access was recently granted, please refresh your credentials.\""
`

If you wait long enough the call sometimes succeeds.

**To Reproduce**
1. Deploy AKS with the App Routing add-on
2. Set the DNS Zone for the add-on
3. wait for the error

**Expected behavior**
DNS Entries are created in the DNS Zone

**Partial Fix**
When giving the managed identity "DNS Zone Contributor" on the whole RG then it sometimes works, but the error message is still there from time to time

**Environment:**
 - Kubernetes version 1.27.7
 - azure-cli                         2.55.0
 - core                              2.55.0
 - telemetry                          1.1.0
Extensions:
 - account                            0.2.5
 - aks-preview                      0.5.173

Dependencies:
 - msal                            1.24.0b2
 - azure-mgmt-resource             23.1.0b2

**Comment by sabbour** [comment]
Are you still facing this issue with the latest CLI version?

**Comment by sabbour** [comment]
Closing. If this is still an issue, please re-open or open a support request to investigate further. Thank you.
