### ISSUE TITLE
[BUG] nodepool update with --enable-artifact-streaming fails

### ISSUE THREAD

**Issue by serol-uipath** [Azure/AKS#4043]
**Describe the bug**

We are trying to modify an existing node pool to `--enable-artifact-streaming` but command fails.

**To Reproduce**

1. Try to update nodepool
```sh
az aks nodepool update --cluster-name clusterName --resource-group resourceGroup \
 --name nodePoolName --enable-artifact-streaming
```
```
Argument '--enable-artifact-streaming' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The behavior of this command has been altered by the following extension: aks-preview
(InternalOperationError) Internal server error
Code: InternalOperationError
Message: Internal server error
```

2. Query artifactStreamingProfile for the node group
```sh
az aks nodepool show --cluster-name clusterName --resource-group resourceGroup \
  --name nodePoolName  |  grep artifactStreamingProfile
```
```
"artifactStreamingProfile": null,
```

**Expected behavior**
Artifact streaming is enabled and `artifactStreamingProfile` returns `enabled: true`

**Screenshots**

**Environment (please complete the following information):**
 - azure-cli: 2.55.0
 - kubernetes version: 1.26.10
 - Node version: AKSUbuntu-2204containerd-202312.06.0

**Additional context**

**Comment by PixelRobots** [comment]
I think it might not be available in all regions which is why you are getting an error. I saw this pull request in the aks-preview cli. https://github.com/Azure/azure-cli-extensions/pull/7054 where they are removing the artifact streaming from the update command.

Maybe @northtyphoon knows more about this.

**Comment by allyford** [comment]
@serol-uipath - Artifact Streaming now supports nodepool update in all regions.
