### ISSUE TITLE
pod hang on terminating even after deployment has been deleted

### ISSUE THREAD

**Issue by joaocc** [Azure/AKS#405]
```
$ kubectl describe pod skn-h1 -n d21k
Name:                      skn-h1-5fc6b9b97-l5dw4
Namespace:                 d21k
Node:                      aks-nodepool1-17150731-1/10.240.0.5
Start Time:                Sun, 03 Jun 2018 17:54:07 +0100
Labels:                    pod-template-hash=197265653
                           service=skn-h1--svc
Annotations:               <none>
Status:                    Terminating (expires Mon, 04 Jun 2018 17:49:52 +0100)
Termination Grace Period:  30s
IP:                        10.244.0.238
Controlled By:             ReplicaSet/skn-h1-5fc6b9b97
Containers:
  web:
    Container ID:   docker://e271f7109960e758436ff397b2321e1abbdfaae8a6b4de2cfb524e77ce7a5117
    Image:          dkreg0000x.azurecr.io/image-name-xxxxxxxxxxx:2dev-apache
    Image ID:       docker-pullable://dkreg0000x.azurecr.io/image-name-xxxxxxxxxxx@sha256:c5e5578f7fab0d10c99ffded396791538eba4c1d57f9f45597bff768c91eac4d
    Port:           80/TCP
    State:          Terminated
      Exit Code:    0
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  0
    Environment Variables from:
      skn-h1--config-main  ConfigMap  Optional: false
    Mounts:
      /app from skn--live--disk (rw)
      /data/ffffile from skn--live--share (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lp8wk (ro)
  devops:
    Container ID:  docker://80ea2d613534363ec33f9bac55b5a129b69aaf63c92f8e0b3d4bfb99030aa31e
    Image:         ez123/ops-base:alpine37
    Image ID:      docker-pullable://ez123/ops-base@sha256:17c987318c2ced83d59746ddd0e3db6b5cbab22b0ee7bc4fbb44f14a1a3a672f
    Port:          <none>
    Command:
      /bin/bash
    Args:
      -c
      while true; do date -u; sleep 900; done
    State:          Terminated
      Exit Code:    0
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /mnt/_bak from skn--live--share (rw)
      /mnt/live-ffffiles from skn--live--share (rw)
      /mnt/live-fffroot from skn--live--disk (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lp8wk (ro)
  sftp:
    Container ID:  docker://cb2da9213bc5d12ade9ed6777211d8536869a7591902226cf45f3e4a0bc78745
    Image:         ez123/sftp:alpine-3.7
    Image ID:      docker-pullable://ez123/sftp@sha256:9484fc52895118845e98bf0aec40a38d7300989df8ba0a8aa5a4fe98fb82ab58
    Port:          22/TCP
    Command:
      /bin/bash
      -c
      bash /entrypoint $SKN_SFTP_USER:$SKN_SFTP_PASS:33:33
    State:          Terminated
      Exit Code:    0
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  0
    Environment:
      SKN_SFTP_USER:  <set to the key 'sftp-user' in secret 'skn-h1--sftp--secrets'>  Optional: false
      SKN_SFTP_PASS:  <set to the key 'sftp-pass' in secret 'skn-h1--sftp--secrets'>  Optional: false
    Mounts:
      /home/deployer/_bak from skn--live--share (rw)
      /home/deployer/live-ffffile from skn--live--share (rw)
      /home/deployer/live-fffroot from skn--live--disk (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lp8wk (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  skn--live--disk:
    Type:         AzureDisk (an Azure Data Disk mount on the host and bind mount to the pod)
    DiskName:     d21k--skn-h1.live
    DiskURI:      /subscriptions/577b71d4-e214-4896-9fd0-6145ab5af314/resourceGroups/hsz-nl-ams--aks1712devx/providers/Microsoft.Compute/disks/d21k--skn-h1.live
    Kind:         Managed
    FSType:       ext4
    CachingMode:  ReadWrite
    ReadOnly:     false
  skn--live--share:
    Type:        AzureFile (an Azure File Service mount on the host and bind mount to the pod)
    SecretName:  azfiles--hsz0aks1712devx0skn
    ShareName:   skn-h1-live
    ReadOnly:    false
  default-token-lp8wk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lp8wk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason   Age   From                               Message
  ----    ------   ----  ----                               -------
  Normal  Killing  37m   kubelet, aks-nodepool1-17150731-1  Killing container with id docker://sftp:Need to kill Pod
  Normal  Killing  37m   kubelet, aks-nodepool1-17150731-1  Killing container with id docker://web:Need to kill Pod
  Normal  Killing  36m   kubelet, aks-nodepool1-17150731-1  Killing container with id docker://devops:Need to kill Pod

```

**Comment by sauryadas** [comment]
can you force delete the pod?
```kubectl delete pod NAME --grace-period=0 --force```

**Comment by joaocc** [comment]
Tried it. didn't work. Anyway, this happened 5 days ago. The node was restarted, so no longer can do any testing. 
Thanks

**Comment by alexandruradovici** [comment]
I am experiencing the same issue, several pods in Terminating status for more than 10 days. Running
````
kubectl delete pod NAME --grace-period=0 --force
````
displays the following message:
> warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.

While pods disappear from the resource list, there is still a possibility that they are running on the nodes. Any idea on how to check if they still run?

**Comment by alexandruradovici** [comment]
is there any update on this? Any pod that we try to stop hangs up in Terminate state.

**Comment by sauryadas** [comment]
can you send your cluster details to aks-help@service.microsoft.com

**Comment by Novitoll** [comment]
+1 And it happens not only with deleting Deployment, but on RollingUpdate of Deployment with new pods. And please dont suggest to do `--force --grace-period=0` -- it is not the way you want to do in PROD. 
AKS GA should be GA :)

**Comment by stigok** [comment]
Same issue in AKS 10.0.6 in Northern Europe. Lost a Node for uknown reasons during the weekend, redeployed all the VM's in turn, but the pod is still `Terminating` for 3 days now.

**Comment by mrdfuse** [comment]
Same on AKS 10.0.6 in West Europe. Retrieving the kubelet logs didn't work btw, just got an empty output when doing `journalctl -u kubelet -o cat`

**Comment by filipmnowak** [comment]
sometimes it happens that dockerd will report existence of the container, but it is not really there - docker's state seems to be inconsistent.

That is the situation which k8s can interpret as inability to terminate the Pod for longer periods of time.

it might be related to following issue: https://github.com/moby/moby/issues/31768

in our case what is helping is on-demand restart of dockerd when such issue is detected. to avoid restart of all of the Pods, you may want to set [keep-alive](https://docs.docker.com/config/containers/live-restore/) option for Docker, which is allowing it to preserve containers between the restarts.

**Comment by davetuner** [comment]
We are having the same issue using azure-file storage classes and it seems to have gotten worse since we upgraded to 1.11.3

**Comment by Nilubkal** [comment]
Hello is there any development on this issue, i can confirm that on AKS v 1.11.5 and the Docker info from the nodes is : 
Client:
 Version:           3.0.1
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        021bf39d
 Built:             Tue Oct 16 21:05:20 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.1
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       09f5e9d
  Built:            Tue Oct 16 20:55:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false
containers are "freezeing" and only cordoning the  node and restarting docker helps.

**Comment by Nilubkal** [comment]
Unfortunately that’s still the case with moby 3.0.1. I have seen that moby 3.0.2 was released, i tried with upgrading it on all our nodes but again the same issue appeared.

**Comment by palma21** [comment]
Most of the issues above have been individually rooted to upstream bugs already solved, long disk detach times and others. 

If you still have an issue make sure to open a support ticket and we will follow up directly, if you think it's widespread please open a new ticket with the specifics of you case and following:
https://github.com/Azure/AKS#bug-reports-
