### ISSUE TITLE
[BUG] First pull from ACR fails with 401 Unauthorized, second attempt works

### ISSUE THREAD

**Issue by hariwe** [Azure/AKS#4052]
**Describe the bug**
My AKS is using a managed identity and the kubelet identity has the ACRPull Role on a private ACR.
When I'm deploying a new pod, I noticed that the first pull of the image from the private ACR always fails and then the second attempt works. This is not dependent on the image and happens with every image.
As soon as the pull worked for one image, pulls for other images from this ACR work instantly on the same node. This lasts for about 30 minutes. After the ~30 mins, restarting (deleting) a pod shows the same error again, first pull fails, next attempt works.

This is how a kubectl describe looks like when it's happening:

```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  73s                default-scheduler  Successfully assigned default/debugpod-d87b48b5c-7gjlz to aks-default-25596659-vmss000000
  Warning  Failed     43s                kubelet            Failed to pull image "xxx.azurecr.io/debugcontainer:latest": failed to pull and unpack image "xxx.azurecr.io/debugcontainer:latest": failed to resolve reference "xxx.azurecr.io/debugcontainer:latest": failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://xxx.azurecr.io/oauth2/token?scope=repository%3Adebugcontainer%3Apull&service=xxx.azurecr.io: 401 Unauthorized
  Warning  Failed     43s                kubelet            Error: ErrImagePull
  Normal   BackOff    43s                kubelet            Back-off pulling image "xxx.azurecr.io/debugcontainer:latest"
  Warning  Failed     43s                kubelet            Error: ImagePullBackOff
  Normal   Pulling    32s (x2 over 73s)  kubelet            Pulling image "xxx.azurecr.io/debugcontainer:latest"
  Normal   Pulled     31s                kubelet            Successfully pulled image "xxx.azurecr.io/debugcontainer:latest" in 745ms (745ms including waiting)
  Normal   Created    31s                kubelet            Created container debugpod
  Normal   Started    31s                kubelet            Started container debugpod
```

I also executed `az aks check-acr` multiple times to validate the connection to the ACR and this always shows a successful result:

```
[2024-01-09T14:37:49Z] Checking host name resolution (xxx.azurecr.io): SUCCEEDED
[2024-01-09T14:37:49Z] Canonical name for ACR (xxx.azurecr.io): xxx.privatelink.azurecr.io.
[2024-01-09T14:37:49Z] Checking managed identity...
[2024-01-09T14:37:49Z] Kubelet managed identity client ID: xxxxx-xxxxx-xxxxx-xxxxx-xxxxx
[2024-01-09T14:37:49Z] Validating managed identity existance: SUCCEEDED
[2024-01-09T14:37:49Z] Validating image pull permission: SUCCEEDED
[2024-01-09T14:37:49Z]
Your cluster can pull images from xxx.azurecr.io!
```

Note: I replaced the actual ACR name with xxx.azurecr.io 

**Environment (please complete the following information):**
 -  CLI Version [1.28]
 - Kubernetes version [1.28.3]

**Comment by hariwe** [comment]
I was able to solve it, by executing `az aks update --detach-acr` and afterwards attaching it again with `az aks update --attach-acr`.
Now every pull works instantly from the ACR.
Initially I assigned the ACRPull Role manually to the managed identity and didn't use the az attach-acr command.
Is the `az aks update --attach-acr` command doing something else beside the role assignment?

**Comment by hariwe** [comment]
Unfortunately the issue appears now again. I also checked the network connectivity to the ACR directly from the Kubernetes nodes, by executing a nslookup to check if the privatelink ip from the ACR is correctly resolved, followed by a telnet to this IP and port 443. This was always working fine, so I assume it cannot be a networking issue.

**Comment by bravebeaver** [comment]
can you please post the detailed error message from for the 401? totally agree with your debugging steps to rule out network.

here is some [doc](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/cannot-pull-image-from-acr-to-aks-cluster) that possibly helps if the detailed error message matches

**Comment by hariwe** [comment]
The detailed error message is in the kubectl describe output it posted:

`Failed to pull image "xxx.azurecr.io/debugcontainer:latest": failed to pull and unpack image "xxx.azurecr.io/debugcontainer:latest": failed to resolve reference "xxx.azurecr.io/debugcontainer:latest": failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://xxx.azurecr.io/oauth2/token?scope=repository%3Adebugcontainer%3Apull&service=xxx.azurecr.io: 401 Unauthorized`

I already had a look at the documentation you posted, but it does not mention this exact error message.

**Comment by hariwe** [comment]
I just found following errors from azure_credentials in journactl directly on the Kubernetes nodes:
```
Jan 15 08:19:31 aks-default-25596659-vmss000000 kubelet[2992]: E0115 08:19:31.654268    2992 azure_credentials.go:315] failed to perform token exchange: Www-Authenticate: failed to reach auth url https://xxx.azurecr.io/oauth2/exchange: Www-Authenticate: failed to reach auth url https://xxx.azurecr.io/oauth2/exchange
Jan 15 08:19:31 aks-default-25596659-vmss000000 kubelet[2992]: E0115 08:19:31.654316    2992 azure_credentials.go:235] error getting credentials from ACR for xxx.azurecr.io Www-Authenticate: failed to reach auth url https://xxx.azurecr.io/debugcontainer:latest\""
```

However, trying to reach the mentioned oauth2/exchange URL directly on the node with curl works perfectly fine all the time.

**Comment by hariwe** [comment]
It was actually a networking issue, more specifically a routing issue.
So nothing related to AKS actually.

**Comment by hemenkapadia** [comment]
@hariwe - we are facing similar behavior but for very large images (>10 GB). What was the resolution ?

**Comment by eperaza** [comment]
im also having this issue with image larger >10 gb... any one solved it?

**Comment by torbendury** [comment]
@hariwe would you mind shedding a bit of light on your solution? I am facing a similar issue with a cluster of mine and can't really understand the possible solution, since the commands seems to do nothing else than deleting and adding the IAM permission.

**Comment by olegbzk** [comment]
I encountered the same error. The error message is confusing because it suggests an authentication issue (401), but the root cause was actually a wrong image name.

**Comment by vazul** [comment]
We have faced the same issue.
The problem was that the repository image had more than one tags, and a tag is deleted via "az acr repository delete --image [repo]:[tag]"... wich is deleted the tag and the underlying layers and digest. So we had an image tag, pointing to a digest, that no longer extisted.
So yes, the error message is misleading, the problem in our case was not authorization related. The image is deleted, and a dangling tag remained.
