### ISSUE TITLE
Security Patch Channel for Linux streams 

### ISSUE THREAD

**Issue by kaarthis** [Azure/AKS#4054]
Introducing Security Patch (GA) for linux incl Ubuntu and AZ linux.  This will have an ability to live patch and reduce no. of reimages / disruptions seen today in https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-node-os-image

**Comment by PixelRobots** [comment]
Do you have any mor information you can share on this?

**Comment by EppO** [comment]
docs still state that 

> SecurityPatch This channel is in preview and requires enabling the feature flag NodeOsUpgradeChannelPreview.

Is it really GA? I didn't see any official announcements on the [Azure Updates Blog](https://azure.microsoft.com/en-us/updates/).

**Comment by kaarthis** [comment]
ONly the nodeOSUpgrade channel is GAed but securitypatch is coming soon https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-node-os-image

**Comment by kaarthis** [comment]
Will be fully GAed with the release of 2.61 CLI - https://github.com/Azure/azure-cli/milestone/142

**Comment by kaarthis** [comment]
Note : We have live patching enabled here meaning unless we detect kernel related packages that require reboot there wont be a reimage done.
