### ISSUE TITLE
Problem pulling image from mcr.microsoft.com

### ISSUE THREAD

**Issue by OldScratchy** [Azure/AKS#4055]
So, I have an AKS Cluster with ACR attached. I'm trying to connect to one of the nodes (win) with this guide as reference → https://learn.microsoft.com/en-us/azure/aks/node-access

When I run

`kubectl debug node/[name_of_the_node] -it --image=mcr.microsoft.com/cbl-mariner/busybox:2.0`

I get this error:

_Warning: container debugger: rpc error: code = NotFound desc = failed to pull and unpack image "mcr.microsoft.com/cbl-mariner/busybox:2.0": no match for platform in manifest: not found_

I tried importing to the ACR the image using _az acr import_ but when I try again with de image from my ACR, I get:

_Warning: container debugger: [rpc error: code = NotFound desc = failed to pull and unpack image "[name_of_the_acr]/cbl-mariner/busybox:2.0": no match for platform in manifest: not found, rpc error: code = Unknown desc = failed to pull and unpack image "[name_of_the_acr]/cbl-mariner/busybox:2.0": failed to resolve reference "[name_of_the_acr]/cbl-mariner/busybox:2.0": failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized]_

I work with no problems with the images that are currently in my ACR, except for this one.

How can I solve this? Is there any other way to access the cluster nodes?

**Comment by andyzhangx** [comment]
the first `rpc error` matters, it means the image does not match your node os:
```
rpc error: code = NotFound desc = failed to pull and unpack image "[name_of_the_acr]/cbl-mariner/busybox:2.0": no match for platform in manifest: not found
```

the second `rpc error` is expected since if pull image with your node identity failed, then it would always try to use anonymous token and returns 401 error finally.

**Comment by OldScratchy** [comment]
@andyzhangx Thank you for your reply. My second question would be which image should I use? I couldn't find it on the documentation.

**Comment by PixelRobots** [comment]
@OldScratchy what type of node pools do you have? Is it just a system node pool and a windows node pool? 

Do you have a Taint on the system node pool to only allow critical add-ons only?

**Comment by OldScratchy** [comment]
@PixelRobots You mean https://hub.docker.com/_/busybox ? Shouldn't be a Win based image? I need to access a Windows Node (Node Pool).

**Comment by PixelRobots** [comment]
You can run kubectl debug directly onto the windows nodes. You need to proxy via the Linux ones. 

Check out this docs page. https://learn.microsoft.com/en-us/azure/aks/node-access#windows-server-proxy-connection
