### ISSUE TITLE
Azure Entra ID Workload Identity Environmental variables are not available to CronJobs in AKS

### ISSUE THREAD

**Issue by sarveswarreddy** [Azure/AKS#4059]
**Describe the bug**
I have setup a user assigned managed identity and linked it to service account in AKS using federated credentials. I deployed a test pod using the service account, and I am able to use below environmental variables to login to azure.

AZURE_CLIENT_ID
AZURE_TENANT_ID
AZURE_FEDERATED_TOKEN_FILE

az login --federated-token "$(cat $AZURE_FEDERATED_TOKEN_FILE)" --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID

When I used the service account to create a CronJob in AKS, these environmental variables are not available at all.

By the way, I have set below label and set **automountServiceAccountToken: true** to both Pod and CronJob.

**labels:
    azure.workload.identity/use: "true"**

**Expected behavior**
I expect these environmental variables to be also available for CronJob so I can use them in a script to login to Azure and access other Azure services.

**Screenshots**
![image](https://github.com/Azure/AKS/assets/47114874/de80a2fd-f8a4-417d-9693-5379753a22b7)

**Environment (please complete the following information):**
 -  CLI Version 2.56.0
 - Kubernetes version v1.27.7

**Comment by sarveswarreddy** [comment]
Hello @PixelRobots, here is the Cronjob manifest.

I am using below command in the script to login to Azure
```az login --federated-token "$(cat $AZURE_FEDERATED_TOKEN_FILE)" --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID```

```apiVersion: batch/v1
kind: CronJob
metadata:
  name: setmaxsize-cronjob
  labels:
    azure.workload.identity/use: "true"
spec:
  schedule: "0 9 * * 1"
  jobTemplate:
    spec:
      backoffLimit: 5
      ttlSecondsAfterFinished: 240
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: az-db-admin
          containers:
            - name: azure-cli
              image: bitnami/azure-cli:2.56.0
              imagePullPolicy: IfNotPresent
              command: ["/scripts/setmaxsize.sh"]
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
          volumes:
            - name: scripts
              configMap:
                name: setmaxsize-cronjob
                defaultMode: 0755
          nodeSelector:
            kubernetes.io/os: linux

**Comment by PixelRobots** [comment]
Thanks. I will do some testing and see what is going wrong.  I think just from looking at the above that maybe the jobs pod is not getting the label. 

I will let you know.

**Comment by sarveswarreddy** [comment]
@PixelRobots You are brilliant, I already tried what you just mentioned, I got the variables to the pod now. It's the issue with missing labels on the jobs pod!

**Comment by PixelRobots** [comment]
Awesome news. Glad it's working. Any other issues let us know.
