### ISSUE TITLE
Patch version availability (1.27.8+)

### ISSUE THREAD

**Issue by mekaan** [Azure/AKS#4062]
**Stateful sets are getting in the `Succeeded` pod phase.**
This happens quite frequently when pods are evicted. Which shouldn't happened. This [bug has been introduced](https://github.com/kubernetes/kubernetes/issues/118310) in the `1.27` minor version. Since the `1.26` K8s version is reaching the End of Life phase soon, we were testing for upgrading to `1.27` and hit this bug.
This bug is resolved with [this PR](https://github.com/kubernetes/kubernetes/pull/121389) in the [`1.27.8` patch](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md#bug-or-regression) of K8s. 

**Request**
We need the `1.27.8` K8s patch version available for AKS. Currently, `1.27.7` is the latest available patch release.

**Possible alternatives**
This bug fix is also in the [`1.28.4` release](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md#bug-or-regression). We can also use this patch but currently the `1.28.3` K8s patch release is available in AKS for that minor version.

**Comment by angelo291196** [comment]
When will patch versions 1.27.8 and 1.28.4 be available for AKS? I experimented a similar issue with statefulsets Pods going in Completed state after being evicted

**Comment by kaarthis** [comment]
AKS patch versions 1.27.9 and 1.28.5 are now available with 1.27.9 used as the default version for new clusters. This is as of Feb release - https://github.com/Azure/AKS/releases
