### ISSUE TITLE
[Feature] Add possibility to choose Windows Server version for new nodepool in Azure Portal

### ISSUE THREAD

**Issue by den4md** [Azure/AKS#4064]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't add new windows node pool to AKS cluster in Azure Portal. My team is currently using Windows Server Core 2019 as base image for our software solution. Migration to 2022 is planned to be done later. In Azure Portal there is no option to choose between 2019 and 2022 version - by default it is set to 2022. Windows Server 2022 can't run containers based on Windows Server 2019 image. So each time I need to create new windows nodepool, I have to do this through complex `az aks nodepool add` command.

**Describe the solution you'd like**
Currently there is a possibility to choose between "Azure Linux", "Ubuntu Linux" and "Windows" (which is basically Windows 2022) for "OS SKU" field while creating new nodepool in Azure Portal.
![Azure Portal OS SKU selection](https://github.com/Azure/AKS/assets/50938720/db34d7b7-e1f1-42b9-95f5-ffcd7b1d8c64)

I think "Windows" option could be splitted to "Windows 2019" and "Windows 2022" to enhance user's experience.

**Additional context**
I understand that windows 2019 will be deprecated on 1 March 2026. Until then, this way of creating windows node pool is inconvenient.
If this repo is wrong place to post feature request for Azure Portal, please point me in the right direction.

**Comment by sfmsft** [comment]
Hello @den4md 

Our team is looking into addressing this. Thank you for the feedback!

AKS Portal Team

**Comment by sfmsft** [comment]
@den4md The requested changes are now live in the Portal:

![image](https://github.com/Azure/AKS/assets/126097783/b64bd6d9-281e-4b13-acc7-eef76a9bfbc6)

I will now mark this item as closed. Thanks again for your feedback!
**AKS Portal Team**
