### ISSUE TITLE
[Question] An old version of workload-identity is deployed every minute

### ISSUE THREAD

**Issue by Sebastian-Materna** [Azure/AKS#4065]
**Describe scenario**
We observe some cpu throttling of some pods of the deployment `azure-wi-webhook-controller-manager`.  This feature is needed for authentication for some pods against Azure, which is working. But we were confused about the alert of cpu throttling. After some investigation I found out, that the used Helm chart is probably old:

```
helm -n kube-system list
NAME                            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                                                   APP VERSION
aks-managed-workload-identity   kube-system     83950           2024-01-16 15:07:32.897672207 +0000 UTC deployed        workload-identity-addon-0.1.0-cfc7ee36234c30080db90f30ac4669c98e1fed27
```
So `workload-identity-addon-0.1.0` is used with an image `mcr.microsoft.com/oss/azure/workload-identity/webhook:v1.1.0`. I checked at Github the repository https://github.com/Azure/azure-workload-identity, which is using v.1.2.0 and also described in the installation manual https://azure.github.io/azure-workload-identity/docs/installation/mutating-admission-webhook.html#helm-3-recommended. 

After checking the Helm releases:

```
helm -n kube-system history aks-managed-workload-identity
REVISION        UPDATED                         STATUS          CHART                                                                   APP VERSION     DESCRIPTION
83940           Tue Jan 16 14:56:37 2024        superseded      workload-identity-addon-0.1.0-cfc7ee36234c30080db90f30ac4669c98e1fed27                  Upgrade complete
83941           Tue Jan 16 14:57:45 2024        deployed        workload-identity-addon-0.1.0-cfc7ee36234c30080db90f30ac4669c98e1fed27                  Upgrade complete
```

I see, that the helm upgrade command is triggered every minute and I don't know why? I can't find any information about this. There are no addons installed:

```
 az aks addon list --name xxx --resource-group xxx -otable
-------------------------------  ---------
http_application_routing         False
monitoring                       False
virtual-node                     False
kube-dashboard                   False
azure-policy                     False
ingress-appgw                    False
confcom                          False
open-service-mesh                False
azure-keyvault-secrets-provider  False
gitops                           False
web_application_routing          False
```

We are using Kubernetes v1.27.7.

**Question**
What is the process of triggering Helm upgrade every minute? And how we can update the cpu resource of the deployment?
Thank you for your help.

**Comment by PixelRobots** [comment]
Hello,

From my understanding the helm upgrade is triggered to ensure the managed workload identity installation is always reconciled with the settings Azure needs to manage it. So, if you manually made a change, it would revert them on the next helm upgrade (every minute in this case).

If you want to change the cpu requests or limits, you will need to install the open source one. this way you are in control of the settings.

If the CPU is throttling it might be wise to open a support ticket so the support team, can take a further look to see if there is another issue on your nodes that are causing the cpu throttle.

Hope that helps.
