### ISSUE TITLE
Failed to save container service ''. Error: Cidr is invalid

### ISSUE THREAD

**Issue by hunterfries** [Azure/AKS#407]
Attempting to upgrade a cluster and receiving the following error from the Azure : Failed to save container service ''. Cidr is invalid

**Comment by hunterfries** [comment]
From the portal with advanced networking. Was attempting to add a node to cluster, not upgrade.

**Comment by nphmuller** [comment]
Exactly the same for me. Adding node through Azure cli did work as a workaround.

**Comment by ronnytag233** [comment]
it is happening to me when I try to scale up the nodes from the UI.
