### ISSUE TITLE
[Feedback] HTTPS in istio ingress gateway will not work unless gateway and certificate secret both are created in aks-istio-ingress namespace.

### ISSUE THREAD

**Issue by pratiksharma-dev** [Azure/AKS#4073]
**Describe your scenario**
We faced this issue for enabling secure gateways for a customer: [Istio / Secure Gateways](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fistio.io%2Flatest%2Fdocs%2Ftasks%2Ftraffic-management%2Fingress%2Fsecure-ingress%2F&data=05%7C02%7CPratik.Sharma%40microsoft.com%7C527889334e014046527908dc1b7d05e5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638415470987761175%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wEhqf1tNDWb%2BPkKxjsfxwy%2BDU2%2FNl1Kv7tu8aN1BOiI%3D&reserved=0). The challenge is OSS istio only has istio-system namespace and all the docs for secure gateways use istio-system. If general guidance for OSS istio is followed, HTTPS will not work with AKS addon since we have 3 namespaces for istio viz. aks-istio-system, aks-istio-ingress and aks-istio-egress. The limitation is that it will only work when istio ingress gateway and certificate secret are both created in aks-istio-ingress namespace. This is not mentioned in the documentation anywhere and it was only through trial and error that we were able to make it work. The article in our learn pages here: [Azure Kubernetes Service (AKS) external or internal ingresses for Istio service mesh add-on (preview) - Azure Kubernetes Service | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Faks%2Fistio-deploy-ingress&data=05%7C02%7CPratik.Sharma%40microsoft.com%7C527889334e014046527908dc1b7d05e5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638415470987768732%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9OD818WOqWB%2BlKYxLBhMkb2bS66bBwRiwhILh312eYw%3D&reserved=0), only mentions HTTP scenario and doesn’t mention HTTPS scenario. We should have proper documentation for this, if needed I have documented step by step instructions to setup Istio addon with HTTP(s) here: [pratiksharma-dev/aks-istio-addon-setup (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpratiksharma-dev%2Faks-istio-addon-setup&data=05%7C02%7CPratik.Sharma%40microsoft.com%7C527889334e014046527908dc1b7d05e5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638415470987774712%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mGdmQx6Y0ViCxXfbX1t8khIm8NtrkW%2BAxF06ozoyGnk%3D&reserved=0)

**Feedback**
This scenario should be well documented so that customers can get proper guidance while enabling secure gateways in Istio addon

**Comment by ttsang1801** [comment]
I encountered the same issue with this, it took me 4 days to resolve it. After identifying the problem, I came across this thread. Tested with Istio from OSS and had no issues, so it seems to be a problem with the Istio add-on only. This should be reported as a bug ticket.
