### ISSUE TITLE
[Feature] No way to set static IP on the ingress LB created by Istio addon

### ISSUE THREAD

**Issue by pratiksharma-dev** [Azure/AKS#4074]
**Is your feature request related to a problem? Please describe.**
Setting static IP is required for any DNS mapping from custom domain or traffic manager so that the IP is not lost when the cluster is recreated, or addon / ingress is destroyed. We have this functionality today for any LB based k8s service using annotations: service.beta.kubernetes.io/azure-load-balancer-ipv4. If this annotation is applied on the LB created by the addon, there is a reconciliation that runs, and the annotations gets removed.

**Describe the solution you'd like**
There should be a way to set the static IP / custom dns fqdn for the LB when enabling istio ingress via Az CLI / Az PowerShell / ARM / Bicep / REST

**Describe alternatives you've considered**
No way currently to set this. After cluster / ingress is recreated, the A record mapping needs to be updated for the new IP.

**Comment by npcxiao** [comment]
#3757 
#3987

**Comment by npcxiao** [comment]
Related to #3757 and #3987

**Comment by deuxailes** [comment]
Any update on this?

**Comment by nshankar13** [comment]
@deuxailes we are currently looking into this. Closing this thread and moving the discussion here: https://github.com/Azure/AKS/issues/3757
