### ISSUE TITLE
[BUG] Cert-manager and letsencrypt does not work with Istio addon

### ISSUE THREAD

**Issue by pratiksharma-dev** [Azure/AKS#4075]
**Describe the bug**
When creating ClusterIssuer, the http01 solver is not working with istio ingress class. Kindly check cluster issuer manifest here for reference: [aks-istio-addon-setup/cluster-issuer.yaml at main · pratiksharma-dev/aks-istio-addon-setup (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpratiksharma-dev%2Faks-istio-addon-setup%2Fblob%2Fmain%2Fcluster-issuer.yaml&data=05%7C02%7CPratik.Sharma%40microsoft.com%7C527889334e014046527908dc1b7d05e5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638415470987780588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JzSUQ01lbdcBHyonK6E1cokT4Au4GOnLzh5OMgmMmcs%3D&reserved=0). When I checked in my cluster there was no CRD present for istio ingress class. Even when I installed the CRD, I couldn't get letsencrypt http01 solver to work with istio. This works fine with OSS istio. At the end I used Gateway API and httproute to band aid this situation and make http01 solver work as shown here: [aks-istio-addon-setup/gateway-api.yaml at main · pratiksharma-dev/aks-istio-addon-setup (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpratiksharma-dev%2Faks-istio-addon-setup%2Fblob%2Fmain%2Fgateway-api.yaml&data=05%7C02%7CPratik.Sharma%40microsoft.com%7C527889334e014046527908dc1b7d05e5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638415470987786659%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cvExcCLCY8CWmmQBJ4Bcqh1Xp9r0vgyc8%2BoWSC4%2FvnQ%3D&reserved=0). But with this, I cannot use the istio ingress features and must stick to Gateway API.

**To Reproduce**
Install cert-manager as described here: https://github.com/pratiksharma-dev/aks-istio-addon-setup/blob/main/README.md#setup-cert-manager
Create ClusterIssuer and Certificate as shown here: 
https://github.com/pratiksharma-dev/aks-istio-addon-setup/blob/main/cluster-issuer.yaml
https://github.com/pratiksharma-dev/aks-istio-addon-setup/blob/main/create-certificate.yaml

**Expected behavior**
The http01 solver should be able to verify the challenge and the certificate should be in ready state

**Screenshots**
![image](https://github.com/Azure/AKS/assets/11813857/8b9c103b-57e2-4b39-8137-e36b9c05a235)

**Environment (please complete the following information):**
 -  CLI Version 2.55
 - Kubernetes version 1.26.10
 - CLI Extension version aks-preview: 0.5.173, k8s-extension: 1.5.2, k8s-configuration: 1.7.0

**Additional context**

**Comment by alixmacdonald10** [comment]
Any update on this? I am having similar issues.

**Comment by Joerg-L** [comment]
Any news on this topic?

**Comment by deveshdama** [comment]
we are looking into this, will update soon.

**Comment by alixmacdonald10** [comment]
It may help some people on this thread but in the end I removed the AKS managed Istio add on and installed it myself via helm and it works.

**Comment by deveshdama** [comment]
we've identified the issue, the auto generated k8s ingress is not materialized as expected by cert-manager. We are working on the solution.

**Comment by shashankbarsin** [comment]
@pratiksharma-dev - Kubernetes Ingress API isn't supported as part of Istio addon. In fact, in OSS Istio there's a push to add all new ingress capabilities under Kubernetes Gateway API support under Istio. Because there's a possibility that K8s Ingress support under Istio may be deprecated in future, it'd be hard to add support for that under addon and then cause breaking change for any user who takes a dependency on the same. We are currently working on Istio Gateway API support (there are multiple things to address - health probe fixes, support for canary upgrade,...) and tentatively this should be out in CY2024Q4 or may slip to CY2025Q1.

**Comment by deveshdama** [comment]
@pratiksharma-dev - we've made changes to allow for kubernetes ingress as part of Istio addon. Here is an [example walkthrough](https://github.com/Azure/AKS/tree/master/examples/istio-based-service-mesh/security/cert-manager-letsencrypt) for the cert-manager let's encrypt integration.

**Comment by caffeinism** [comment]
> @pratiksharma-dev - we've made changes to allow for kubernetes ingress as part of Istio addon. Here is an [example walkthrough](https://github.com/Azure/AKS/tree/master/examples/istio-based-service-mesh/security/cert-manager-letsencrypt) for the cert-manager let's encrypt integration.

What revision does this apply to?

**Comment by deveshdama** [comment]
this applies to all revisions `asm-1-21` and above.
