### ISSUE TITLE
[BUG] Missmatch of pre-pulled images and cluster version of CNS makes new node slow

### ISSUE THREAD

**Issue by perosb** [Azure/AKS#4082]
**Describe the bug**
Our  AKS cluster v1.28.3 uses windows2022 image version `AKSWindows-2022-containerd-20348.2227.240110`

This node image has cns v1.5.15 pre-pulled, however, the v1.28.3 cluster uses cns v1.5.11.
This adds 5m to node startup times.

```
Normal  Pulling    9m3s   kubelet            Pulling image "mcr.microsoft.com/containernetworking/azure-cns:v1.5.11"
Normal  Pulled     3m30s  kubelet            Successfully pulled image "mcr.microsoft.com/containernetworking/azure-cns:v1.5.11" in 5m32.963s (5m32.963s including waiting)
```

**Expected behavior**
Starting up system pods should be fast, using pre-pulled images.
Possibly the node image should have CNS versions n-1 versions pulled.

**Comment by AbelHu** [comment]
v1.5.11 was removed in https://github.com/Azure/AgentBaker/pull/3805 when v1.5.17 was introduced. CNS win image is ~1.7GB. Based on the VHD size limitation, we have to remove some old big images when new images are introduced. 
I think that the issue that it takes a long time to pull the images will be addressed by the artifacts streaming feature which is on AKS roadmap.
