### ISSUE TITLE
mmu094 

### ISSUE THREAD

**Issue by mmu100** [Azure/AKS#4089]
Add-AppxProvisionedPackage : error C00CE014: App manifest validation error: The app manifest must be valid as per
schema: Line 20, Column 6, Note: The schema for MaxVersionTested specified does not recognize XML fields with
namespace "http://schemas.microsoft.com/appx/manifest/desktop/windows10/6". Please ensure that you have the correct
MaxVersionTested specified. Reason: Element
'{http://schemas.microsoft.com/appx/manifest/desktop/windows10/6}RegistryWriteVirtualization' is unexpected according
to content model of parent element '{http://schemas.microsoft.com/appx/manifest/foundation/windows10}Properties'.
At line:1 char:4
+ &{ Add-AppxProvisionedPackage -Online -PackagePath .\MSTeams-x64.msix ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AppxProvisionedPackage], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddAppxProvisionedPackageCommand

**Comment by PixelRobots** [comment]
Hey @mmu100 are you sure this is the correct repo for this issue?

**Comment by mmu100** [comment]
> @Azure/aks-pm issue needs labels
>
