### ISSUE TITLE
Changing property 'networkProfile.networkPlugin' is not allowed. during scale up

### ISSUE THREAD

**Issue by neutrongenious** [Azure/AKS#409]
I can see this issue when I try to scale my k8.
`
az aks scale -c 2 -n akscluster -g akscluster
Operation failed with status: 'Bad Request'. Details: Changing property 'networkProfile.networkPlugin' is not allowed.
`
tried powershell and bash. same issue on both.

i can scale my cluster fine with AZ portal.

**Comment by JackQuincy** [comment]
@neutrongenious can you post the results of `az --version` just trying to see if this might be related to a new version of the aks component in the az cli.

**Comment by neutrongenious** [comment]
azure-cli (2.0.33)

acr (2.0.25)
acs (2.0.33)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.33)
backup (1.1.1)
batch (3.2.2)
batchai (0.2.3)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.13)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.15)
consumption (0.3.1)
container (0.1.24)
core (2.0.33)
cosmosdb (0.1.21)
dla (0.1.0)
dls (0.0.21)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.0.14)
feedback (2.1.1)
find (0.2.9)
interactive (0.3.21)
iot (0.1.20)
keyvault (2.0.22)
lab (0.0.22)
maps (0.1.0)
monitor (0.1.7)
network (2.1.2)
nspkg (3.0.2)
profile (2.0.25)
rdbms (0.2.3)
redis (0.2.13)
reservations (0.1.2)
resource (2.0.29)
role (2.0.24)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.26)
storage (2.0.33)
vm (2.0.32)

**Comment by JackQuincy** [comment]
Can you run the command again but add a --debug on the end? That should add all the http calls that are made etc. Can you leave here the networkProfile returned on the get at the first and what is sent up in the request body of the put? Although we pull all the secret secrets from the get response I would still be careful about putting the full bodies here. I think this is related to another bug we are tracking internally and I'm just trying to figure it out.

**Comment by JackQuincy** [comment]
Or you can email me the whole output at jaquincy@microsoft.com if you don't want to try to parse the logs

**Comment by JunSun17** [comment]
@neutrongenious It might be related to the CLI support be=tween different version of models. The new version is released around one week ago, can you install the new one and give it a try?

**Comment by HBO2** [comment]
Thx, it worked.

With kind regards,

Bert van Houten
________________________________

**Comment by mboersma** [comment]
This should have been fixed in recent CLI builds. I'm going to close this, but @neutrongenious please re-open if this is still ongoing.
