### ISSUE TITLE
[Question] What is the log format generated by AKS Resource logs

### ISSUE THREAD

**Issue by ultralegendary** [Azure/AKS#4092]
**Describe scenario**
I have configured a diagnostic settings in the AKS cluster to write data to the Storage account. Below are the categorey of Resource log files that are generated in the storage account.
<img width="887" alt="Screenshot 2024-02-12 at 8 27 06 PM" src="https://github.com/Azure/AKS/assets/67859954/b434a12b-5870-4416-9701-6e2eecf5aa92">

**Question**
We are building integration to pull data of AKS from the storage storage account and further process them. We observed that in some containers, `properties.log` field is JSON formate and in other containers, `propertices.log` field is String.
So we wanted to know the schema reference for each log category generated in the storage account.
Below links contain the information of table and its column which I found on the Microsoft documentation.
- AKSAudit - https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/aksaudit?source=recommendations
- AKSAuditAdmin - https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/aksauditadmin?source=recommendations
- AKSControlPlane - https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/akscontrolplane?source=recommendations

But when we look in the storage account data, this columns in the documentation doesnt even match the column in the containers.
Below is an example log from `insights-logs-kube-schedule` container.
```json
{
  "category": "cloud-controller-manager",
  "operationName": "Microsoft.ContainerService/managedClusters/diagnosticLogs/Read",
  "properties": {
    "containerID": "62741557cdb5a386028406b6172ceafd5d62276f264248b0f75d4595059f80b2",
    "pod": "cloud-controller-manager-646665444f-7d7z2",
    "stream": "stderr",
    "log": "I0126 01:00:00.753636       1 leaderelection.go:352] lock is held by cloud-controller-manager-646665444f-flndn_6289ed80-70dd-446b-931a-dc3f1dffe719 and has not yet expired\n"
  },
  "resourceId": "<Resource ID>",
  "time": "2024-01-26T01:00:00.753853298Z"
}
```
Some of the fields like `operationName`, `properties` are not even present in the schema reference of `AKSControlPlane` table.

This is currently a blocker for us. If you have reference to all Category of Resource Logs generated by kubernetes service, Kindly update or share them. This will help us with continuing our implementation.

**Comment by aritraghosh** [comment]
@ultralegendary  What is the destination table in the diagnostic settings? If it is AzureDiagnostics, these tables (AKSAudit, AKSAuditAdmin, AKSControlPlane) will not be populated. Check [here](https://learn.microsoft.com/en-us/azure/aks/monitor-aks#aks-control-planeresource-logs)

**Comment by ultralegendary** [comment]
@aritraghosh The destination is Storage account. And we Select all the Log Categories. I dont understand on the part `destination table` As I dont see any configuration of table in this settings

**Comment by aritraghosh** [comment]
Apologies, the destination table only applies to logs sent to Log Analytics workspace. For other destinations, the Resource specific tables are not populated and there is no fixed schema. Take a look [here](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/azurediagnostics)
