### ISSUE TITLE
Node Pool in AKS [Question]

### ISSUE THREAD

**Issue by ritesh-makerble** [Azure/AKS#4095]
**Question**
I want to use spot instance in my nodepool, Can I specify different `vm_size` for one nodepool?

**Comment by philwelz** [comment]
Hi, by default you can have one only `vm_size` per nodepool as the nodepool ist based on [VMSS](https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview). The system nodepool should never be spot, so you can create the system node pool with standard vms and your workload nodepool with spot instances as described [here](https://learn.microsoft.com/en-us/azure/aks/spot-node-pool).

Does this answer your question?

**Comment by ritesh-makerble** [comment]
@philwelz 
 Can I have different vm family node in same nodepool. Like `"Standard_D8as_v5", "Standard_D8s_v3", "Standard_D8s_v4"` in one nodepool

**Comment by philwelz** [comment]
> @philwelz Can I have different vm family node in same nodepool. Like `"Standard_D8as_v5", "Standard_D8s_v3", "Standard_D8s_v4"` in one nodepool

No. 

It will be possible with [Node autoprovisioning](https://learn.microsoft.com/en-us/azure/aks/node-autoprovision?tabs=azure-cli) that is based on [Karpenter](https://karpenter.sh/). But this public preview at the momement.
