### ISSUE TITLE
hostPath volumes behave erratically

### ISSUE THREAD

**Issue by joaocc** [Azure/AKS#410]
We are trying to use a hostPath volume for some persistence on redis cache. 
The idea is to map it to some folder inside /mnt. Since our nodes are quite stable, this is not critical.

The first time, we added a container it worked fine.
We then changed somethings and after re-aplying the definitions, we started getting this message
```
MountVolume.SetUp failed for volume "redis-data" : hostPath type check failed: /mnt/skn-h1--redis-data/ is not a directory
```
but, on the host, we see this:
```
$ ls -la /mnt/
total 36
drwxr-xr-x  5 root             root  4096 Jun  5 17:03 .
drwxr-xr-x 23 root             root  4096 May 22 06:45 ..
-r--r--r--  1 root             root   639 Apr 30 08:53 DATALOSS_WARNING_README.txt
drwx------  2 root             root 16384 Apr 30 08:53 lost+found
drwxr-xr-x  2 root             root  4096 Jun  5 17:00 skn-h1--redis-data

$ ls -la /mnt/skn-h1--redis-data/
total 8
drwxr-xr-x 2 root root 4096 Jun  5 17:09 .
drwxr-xr-x 5 root root 4096 Jun  5 17:03 ..
-rw-r--r-- 1 root root    0 Jun  5 17:00 .i-am-here
```

On a sister pod/container that is deployment the 1st time, things are working. However, once we remove a pod and kubernetes restarts another one, then we start getting the same message.

Any ideas?

**Comment by derekperkins** [comment]
Are you still running your container as root or did the security context get changed?

**Comment by joaocc** [comment]
I didn't specify any particular settings for the container

**Comment by derekperkins** [comment]
Try adding security context to your pod spec and see if that helps.

```
    spec:
      securityContext:
        runAsUser: 0
```

**Comment by joaocc** [comment]
Hi. I believe that doing that will affect all containers, which is not suitable, as other containers run as other uids (apache for instance). I am switching to have the persistence in an azureFile. 
I can still test some stuff if it helps, but I would like to understand the logic for the fact that this works after the initial deployment, but not after a pod delete/recreate.

**Comment by joaocc** [comment]
Pls disregard the prev comment. I just found out I can set the securityContext for a single container. Will try it.
My comment on needing to understand it still holds... Otherwise it's difficult to have trust in the setup :)
Thx

**Comment by derekperkins** [comment]
Is it possible the container started setting the user?

Also, if you're running Apache and many other containers in the same pod as Redis, you probably need to rethink your architecture.

**Comment by joaocc** [comment]
Not sure I understand what you are asking. The apache container is based on the php7.x images, which do initialization as root, and then start the web server as 33:33. However, when it launches, the mount should already have happened, so not sure what does this have to do with the mount.

The comment on redis, this is a 32mb redis, with lightweight usage, for a single website which runs on apache. It fits to what we are trying to do.

But the fundamental question still remains - why does this work the 1st time I apply a deployment configuration, but then it starts failing whenever a pod is restarted, and why is the message saying the folder is not a folder :)?

**Comment by derekperkins** [comment]
> why does this work the 1st time I apply a deployment configuration, but then it starts failing whenever a pod is restarted

I think you have a configuration problem. We use `hostPath` for persistence and restart / update source images often and have never had this problem. Are you sure that when you redeploy that it is being deployed to the same node?

**Comment by joaocc** [comment]
Pretty sure... I only have 1 node in the cluster :)
The 1st time I deploy the configs, the target folder is created on the host, and whenever files are written inside the container, they appear on the host and vice versa. If I then delete the pod, the next one launched by k8s will start exhibiting that error.
This is what puzzles me. If it never mounted the folder, I could understand it.

**Comment by derekperkins** [comment]
That is weird. It feels like a permissions issue since the directory is there, but why it wouldn't work on a pod restart is bizarre. Sorry I can't be more helpful.

**Comment by derekperkins** [comment]
I'm personally waiting for AKS to add 1.10 support so I can use local PVCs instead of hostPath.

**Comment by andyzhangx** [comment]
@joaocc what's your k8s version? your issue is similar to https://github.com/kubernetes/kubernetes/issues/61801, which is fixed in v1.9.7

**Comment by andyzhangx** [comment]
remove `type: DirectoryOrCreate` in config may work

**Comment by joaocc** [comment]
Thx!
It's 1.9.6, which is believe is the latest available in AKS. 
Regarding the "type", I needed that (so the directory is created if not existing).

**Comment by derekperkins** [comment]
That's funny, I actually did hit this exact same issue 4-5 months ago and ended up removing `DirectoryOrCreate`, thinking maybe I was using it incorrectly. Thanks for the clarification @andyzhangx
