### ISSUE TITLE
[Feature] Cluster Upgrade Readiness tool

### ISSUE THREAD

**Issue by nscriptdotgo** [Azure/AKS#4100]
**Is your feature request related to a problem? Please describe.**
Currently, for customers that are severely behind on their cluster version in AKS, it's a pain to upgrade. 
The cluster admin must manually search and read through the deprecation documentation and find the api groups that have been deprecated, while also accounting for other potential issues related with AKS (node image upgrades and such).

**Describe the solution you'd like**
I would like to have a cluster upgrade readiness tool in the portal that can be used to scan the cluster and create a checklist of what needs to be addressed to upgrade from version 1 to version 2 (which can be one or more minor versions ahead). In the portal it possible to upgrade several minor versions up, but is not generally not recommended in the Kubernetes docs without a lot of work.

**Describe alternatives you've considered**
Alternatives would be either manually going through all the apigroups and updating them or migrating to a new cluster. Migrating can be a pain if you have a lot of workloads. 

**Additional context**
It would be nice for such a tool to accept the current version as input and letting the user select the desired version to upgrade to, then generating the checklist. This tool should be able to be ran multiple times as the cluster admin addresses issues until no issues are found.

Thanks

**Comment by kaarthis** [comment]
We are actually working on a preflight check that should simulate what you are asking without really running the PUT (upgrade). Let us keep you posted #2986
