### ISSUE TITLE
[Question] Zone availability for dual-stack feature

### ISSUE THREAD

**Issue by JoeyC-Dev** [Azure/AKS#4107]
**Describe scenario**
It looks like dual-stack is not available for southeastasia.

```
2c2d4a84d354:/# az aks create -l eastus -g myRG -n aks-dual --network-plugin azure --network-plugin-mode overlay --ip-families ipv4,ipv6
The behavior of this command has been altered by the following extension: aks-preview
^CLong-running operation wait cancelled.  
```
```
2c2d4a84d354:/# az aks create -l southeastasia -g myRG -n aks-dual-2 --network-plugin azure --network-plugin-mode overlay --ip-families ipv4,ipv6
The behavior of this command has been altered by the following extension: aks-preview
(UnsupportedDualStackNetworkPlugin) Network plugin type Azure CNI Overlay is not supported for dual-stack clusters.
Code: UnsupportedDualStackNetworkPlugin
Message: Network plugin type Azure CNI Overlay is not supported for dual-stack clusters.
Target: networkProfile.networkPlugin
```
```
2c2d4a84d354:/# az aks create -l japaneast -g myRG -n aks-dual-3 --network-plugin azure --network-plugin-mode overlay --ip-families ipv4,ipv6
The behavior of this command has been altered by the following extension: aks-preview
^CLong-running operation wait cancelled.  
```

**Question**
I don't see any zone availability info about this feature in document here: https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay  
This command cannot be executed in southeast asia.  
  
**So the question is:** Is this bug or intended?

**Comment by philwelz** [comment]
Perhaps this is a limitation as dual stack is still preview. Maybe @chasewilson can tell more about the region availability of the dual stack feature.

**Comment by amitmavgupta** [comment]
@JoeyC-Dev you can try this in eastus2. I tried it in eastus2 and its working fine in that region.

**Comment by JoeyC-Dev** [comment]
> @JoeyC-Dev you can try this in eastus2. I tried it in eastus2 and its working fine in that region.

The point of this issue is not I want to deploy it somewhere. I am asking the availability of this feature.  
I understand that this is a preview feature. But giving the available regions for this feature will be much helpful.

**Comment by amitmavgupta** [comment]
@JoeyC-Dev Completely agree.
