### ISSUE TITLE
[Question] Release notes for 20240207, how to be notified about version deprecations

### ISSUE THREAD

**Issue by celloza** [Azure/AKS#4108]
This morning our deployment pipelines stopped working, stating that

> Message="Version 1.26.6 is not supported in this region.

According to the [documentation](https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar), 1.26 is EOL by March 2024, but Platform support is until 1.30 is GA, but there is no mention of minor versions.

[AKS Release Status](https://releases.aks.azure.com/#tabeuro) shows that AKS v20240207 is deployed to UKSouth (which is why I'm assuming we're seeing the issue in UKS, and not UKW), but there are no release notes on https://github.com/Azure/AKS/releases to show if this release is responsible for removing 1.26.6 support.

So, how should we know when minor versions cannot be used anymore?

**Comment by PixelRobots** [comment]
Have you looked at https://learn.microsoft.com/en-us/azure/event-grid/event-schema-aks?tabs=event-grid-event-schema

It could be a good way to get notified. Where I work out monitoring solution does this for us by checking the rest API for available versions in a region.

**Comment by kaarthis** [comment]
1.30 preview is planned for April currently and GA likely in May 2024. We are working to show patch deprecations and releases in Release tracker this year. 
On 1.26 deprecation it will come in one of the end march releases and therefore you can catch it in those release notes.
