### ISSUE TITLE
Autoscale Nodes

### ISSUE THREAD

**Issue by SusanKocerka** [Azure/AKS#411]
Hello,

is there a way to autoscale the nodes in AKS? It would be nice to implement scalesets or something like this or did I miss some information about node scaling?

**Comment by feiskyer** [comment]
See https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/README.md#aks-or-acs-deployment

**Comment by tomkerkhove** [comment]
+1 for this and would be great to have this in [Azure Monitor Autoscale](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-autoscale-get-started).

**Comment by jakidomi** [comment]
+1

**Comment by tomkerkhove** [comment]
Feature requests have moved to UserVoice. I've created a request for Azure Monitor Autoscale support - https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/34897312-support-for-azure-monitor-autoscale

@feiskyer CLuster Autoscaler is great but I like to have all my autoscaling configured next to my other Azure resources such as App Plans, API Management, etc. Monitor also has other features which are nice.

Not saying it should be one or the other, having both would be ideal so everybody can pick what they want.

**Comment by abizake** [comment]
The support of Cluster Autoscaler in the control plane which is missing in the AKS forces to still use ACS(which also indirectly forces to manage the master nodes ) over AKS in various scenarios.

**Comment by liuxiaopiao** [comment]
I am confused that currently can we use  https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/README.md#aks-or-acs-deployment to auto scale in AKS?  Do we need to run the cluster autoscaler in  the control plane? @JackQuincy, could you please give me a hand on this? thanks a lot

**Comment by relferreira** [comment]
I'm a little confused too!
It is not recommended to follow this tutorial?
https://docs.microsoft.com/en-us/azure/aks/autoscaler

**Comment by seanmck** [comment]
We are working on enabling the cluster autoscaler as an add-on to the control plane.

**Comment by sauryadas** [comment]
Please file feature requests and enhancements in the link below.
https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks

this feature will roll out by the end of the month

**Comment by avik-so** [comment]
Where can we find this feature?

**Comment by tomkerkhove** [comment]
Here - ["Cluster Autoscaler on Azure Kubernetes Service (AKS) - Preview](https://docs.microsoft.com/en-us/azure/aks/autoscaler)

**Comment by avik-so** [comment]
Ah, thanks.  I thought they were going to add it to the portal.
