### ISSUE TITLE
[Feature] Allow configuration of AKS nodepool scale set model upgrades via Terraform to avoid service failure on new cluster initialisation

### ISSUE THREAD

**Issue by johnswarbrick-napier** [Azure/AKS#4114]
**Is your feature request related to a problem? Please describe.**
We are provisioning AKS clusters using Terraform.

But the nodepool instances provisioned by AKS do not have automatic scale set model updates enabled.

Therefore we encounter a problem where none of the nodes are accessible to the load balancer, displaying error:

`Backend pool 'kubernetes' was added to Virtual machine scale set 'aks-agentpool-41496140-vmss'. Upgrade all the instances of 'aks-agentpool-41496140-vmss' for this change to work`

Instead we have to do a manual model update to restore service.

Unfortunately there is no method in the AKS Terraform provider for enabling automatic scale set model updates (afaik), so it just defaults to manual:

![image](https://github.com/Azure/AKS/assets/105818625/ea55aaac-a8f2-45b1-8e72-28e071e250cf)

**Describe the solution you'd like**
The AKS Terraform provider should supply an option to define the automatic scale set model update policy.

When the load balancer is provisioned, then the nodepool models should immediately update and then be accessible to the load balancer in the backend pool.

Similar to how the Azure Terraform provider `azurerm_virtual_machine_scale_set` exposes those options:

```
resource "azurerm_virtual_machine_scale_set" "example" {
  name                = "mytestscaleset-1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  # automatic rolling upgrade
  upgrade_policy_mode  = "Automatic"
}
```

Ref: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_scale_set#upgrade_policy_mode

> upgrade_policy_mode - (Required) Specifies the mode of an upgrade to virtual machines in the scale set. Possible values, Rolling, Manual, or Automatic. When choosing Rolling, you will need to set a health probe.

**Comment by philwelz** [comment]
This is uncommon. Can you please share your terraform code?

Normally you dont have and NEVER should interfere with the VMSS as it is managed by the AKS cluster.

To upgrade the VMSS you should use the [os image update ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#node_os_channel_upgrade)options described [here](https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-node-os-image).
