### ISSUE TITLE
[BUG] Updating Loadbalancer source ranges not working properly

### ISSUE THREAD

**Issue by lovelinuxalot** [Azure/AKS#4121]
**Describe the bug**
When a AKS Service of type Loadbalancer is created with `service.beta.kubernetes.io/azure-deny-all-except-load-balancer-source-ranges: "true"` annotation and providing `spec.loadBalancerSourceRanges` ranges, adds for the first time ranges to the NSG above DENY rules. Later updates to this list will append the new rules below DENY rules

**To Reproduce**
1. Create a Kubernetes service of type `Loadbalancer` with the following configurations:
    - The service should have `service.beta.kubernetes.io/azure-deny-all-except-load-balancer-source-ranges: "true"` annotation.
    - Add a set of IP ranges to the `spec.loadBalancerSourceRanges` 
2. Ensure the NSG is created and the rules are applied for the provided IP ranges.
3. Update the service `spec.loadBalancerSourceRanges` with a set of new IPs.
4. Check the NSGs again. The new IP range rules are appended below the DENY rules

**Expected behavior**
The added IP range rules should be updated in the NSG above the DENY rules. A solution could be to set the last values for deny rules

**Screenshots**
<img width="1294" alt="Screenshot 2024-02-26 at 18 26 39" src="https://github.com/Azure/AKS/assets/37541310/48fae763-42b6-41dd-9a77-9621ece7bb19">

**Environment (please complete the following information):**
 - Kubernetes version [1.28.3]

**Additional context**

**Comment by chasewilson** [comment]
@feiskyer

**Comment by feiskyer** [comment]
Fixed by https://github.com/kubernetes-sigs/cloud-provider-azure/pull/5763
