### ISSUE TITLE
[BUG] Using an alias for node pool Kubernetes version fails if AKS cluster isn't on the latest patch

### ISSUE THREAD

**Issue by stevehipwell** [Azure/AKS#4128]
**Describe the bug**
When using an alias to create a new AKS node pool the operation fails if the cluster isn't at the latest patch version. This is an important pattern given that we define a cluster with an alias version and keep them up to date using automatic upgrades to bump the patch version.

**To Reproduce**
1. Create an AKS cluster not on the latest patch version (e.g. `1.28.3`)
2. Add a node pool using an alias version (e.g. `1.28`)

**Expected behavior**
I'd expect the node pool to be created successfully with the same version as the cluster (the cluster `currentKubernetesVersion` value).

**Screenshots**
n/a

**Environment (please complete the following information):**
 -  CLI Version: n/a
 - Kubernetes version: 1.28
 - CLI Extension version: n/a
 - Browser: Chrome

**Additional context**

**Comment by qpetraroia** [comment]
Hi @stevehipwell,

What region is your AKS cluster in?

**Comment by paulgmiller** [comment]
Doesn't repro in 1.30

> % az aks nodepool add  -g paultest --cluster-name  upgradefun -n alias -k 1.30
The behavior of this command has been altered by the following extension: aks-preview
 / Running ..

**Comment by stevehipwell** [comment]
@paulgmiller AFAIK this has been fixed.

**Comment by paulgmiller** [comment]
Great closing this out thanks for reporting it! We're trying to get better at triaging our github issues.
