### ISSUE TITLE
Istio and Azure CNI powered by Cilium

### ISSUE THREAD

**Issue by varun-vijayagopal** [Azure/AKS#4129]
**Describe scenario**
We are using AKS with Istio and recently our cluster has grown big and started seeing API connection errors.
We are suing Azure npm and recently came to know that if cluster is bigger than 250 nodes, it is recommended to use Azure CNI powered by Cilium 

**Question**
Does Azure CNI powered by Cilium  works well istio and service mesh . Saw some documents with this limitations
https://www.tigera.io/blog/exploring-aks-networking-options/
https://github.com/Azure/AKS/issues/3318

Is using Cilium better than using Calico ? Is there any case study done why cilium is recommended. We use Istio for all our networking and want to make sure we are going the right route.

**Comment by shashankbarsin** [comment]
Istio addon works with Azure CNI Cilium. We had this limitation in our initial public preview, but since then we have addressed that issue before announcing GA of the Istio addon. @varun-vijayagopal please let us know if you run into any issue and we can discuss the same.
