### ISSUE TITLE
get-credentials api RBAC model update

### ISSUE THREAD

**Issue by weinong** [Azure/AKS#413]
## Background

Currently there are two APIs to get AKS cluster credential: 
One is `GET /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP{/providers/Microsoft.ContainerService/managedClusters/${AKS_RESOURCE_NAME}/accessProfiles/${roleName}?api-version=2017-08-31` 
and the other is 
`POST /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP{/providers/Microsoft.ContainerService/managedClusters/${AKS_RESOURCE_NAME}/accessProfiles/${roleName}/listCredential?api-version=2017-08-31`.

The former is not conforming to Azure RBAC policy such that `Reader` role will be able to call it.

## What’s changed?
The former API’s authorization model is now mapped to `Microsoft.ContainerService/managedClusters/accessProfiles/listCredential/action`.
Users with `Reader` role will be rejected with error message like below.

```
The client '669ec17d-f1eb-47e3-b76e-2fe060c2a943' with object id '669ec17d-f1eb-47e3-b76e-2fe060c2a943' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/accessProfiles/listCredential/action' over scope '/subscriptions/my-sub-id/resourceGroups/my-resource-group/providers/Microsoft.ContainerService/managedClusters/my-aks/accessProfiles/clusterUser'.
```

**Comment by wmeints** [comment]
Is there a workaround for this problem. I run into this exact issue when running `az aks get-credentials` and I need this command to get into my cluster.

**Comment by weinong** [comment]
@wmeints will you be able to ask subscription admin to give you contributor access?

**Comment by MarluanEspiritusanto** [comment]
I have this error:

`Starting Azure Container Service / Kubernetes Service Deployment
Delete Kubernetes management config file /var/lib/jenkins/workspace/hello-world/kubeconfig-300833223531956089
ERROR: ERROR: Status code 403, {"error":{"code":"AuthorizationFailed","message":"The client '7912b768-a178-4996-b6e6-38912a9b90da' with object id '7912b768-a178-4996-b6e6-38912a9b90da' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/accessProfiles/listCredential/action' over scope '/subscriptions/4e601d44-4d18-4e49-9500-1793e668f9e0/resourcegroups/SystemBackend_Resource/providers/Microsoft.ContainerService/managedClusters/aksa5ru5sgbdaum2/accessProfiles/clusterAdmin'."}}
com.microsoft.azure.CloudException: Status code 403, {"error":{"code":"AuthorizationFailed","message":"The client '7912b768-a178-4996-b6e6-38912a9b90da' with object id '7912b768-a178-4996-b6e6-38912a9b90da' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/accessProfiles/listCredential/action' over scope '/subscriptions/4e601d44-4d18-4e49-9500-1793e668f9e0/resourcegroups/SystemBackend_Resource/providers/Microsoft.ContainerService/managedClusters/aksa5ru5sgbdaum2/accessProfiles/clusterAdmin'."}}: The client '7912b768-a178-4996-b6e6-38912a9b90da' with object id '7912b768-a178-4996-b6e6-38912a9b90da' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/accessProfiles/listCredential/action' over scope '/subscriptions/4e601d44-4d18-4e49-9500-1793e668f9e0/resourcegroups/SystemBackend_Resource/providers/Microsoft.ContainerService/managedClusters/aksa5ru5sgbdaum2/accessProfiles/clusterAdmin'.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)`

Im trying to deploy to Kubernetes

**Comment by AceHack** [comment]
I just created a new cluster and I am owner of the subscription and I cannot connect and get this error.  Any suggestions?

**Comment by AceHack** [comment]
The client 'xxx@xxx.com' with object id 'xxx' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/accessProfiles/listCredential/action' over scope '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ContainerService/managedClusters/xxx/accessProfiles/clusterUser'.

**Comment by brbarnett** [comment]
I have a workaround. Create a custom role in your Azure tenant with two specific permissions (please see the gist here).

Create via Azure CLI: `az role definition create --role-definition /path/to/AKSClusterConfigurationReader.json`

Definition reference: https://gist.github.com/brbarnett/6e5d13a1c9961833e48bf8ddd95019e8

**Comment by swgriffith** [comment]
@brbarnett .....literally just hit this and you saved me. Thanks!

**Comment by rtargosz** [comment]
We recently had this issue with the same message and found that it was caused by the user being logged in with a different subscription (we have 2). Using az login --subscription <id> resolved the problem for us.

**Comment by brbarnett** [comment]
@weinong can you re-open this? Giving out `Contributor` access to every user isn't a good solution.

**Comment by theheatDK** [comment]
@weinong can you re-open this? Giving out Contributor access to every user isn't a good solution.

**Comment by weinong** [comment]
Hi folks, please take a look at https://medium.com/@weinong/azure-kubernetes-service-built-in-roles-8083b90e7ba

You dont need to give `Contributor` role out anymore.

**Comment by theheatDK** [comment]
Thanks @weinong 💯

**Comment by jonathonmg** [comment]
Similar to what @rtargosz said except that specifying --subscription in the login command did not work for me. However specifying --subscription for the aks get-credentials command did solve the exception.
