### ISSUE TITLE
[Question] Azure Kubernetes Service cost analysis

### ISSUE THREAD

**Issue by kajetanm-dnv** [Azure/AKS#4130]
We are interested with our team to use AKS Cost Analysis add-on based on OpenCost project.
At this moment it is in preview state. Few questions regarding future development of this feature:

- When it is expected to be in general availability?
- Is it considered to have more filtration options in future? (right now there is cluster, assets and namespace view)
- What about tagging (azure tag) options for namespace (to separate resources per tenant for example)?
- It would be helpful to pick kubernetes labels and use it for filtration as well. Do you take that into account?

**Comment by pranaypathik** [comment]
I am interested in answers to above questions as well
