### ISSUE TITLE
[BUG] AKS 1.28 cluster autoscaler ignores upcoming nodes causing overprovision during scale up

### ISSUE THREAD

**Issue by boliu83** [Azure/AKS#4136]
**Describe the bug**
In AKS 1.28, cluster autoscaler doesn't take upcoming nodes (nodes have been created but not ready yet) into consideration during scale up, causing overprovision during scale up. 

**To Reproduce**
1. make sure autoscaler is enabled on nodepool and current size of nodepool hasn't reached its max size 
2. create a few pods with enough resource requests to trigger scale up
3. CA scales up nodepool every 10-20 seconds until the new nodes become ready and pendings pods are scheduled, or reach nodepool max size.

**Expected behavior**
CA should take upcoming nodes into consideration and stop creating new nodes if the pending pods can be scheduled on the upcoming nodes once they are ready. 

**Screenshots**
see the below screenshot. 6 new nodes were created by CA after one pending pod created. 
![image](https://github.com/Azure/AKS/assets/7767774/b7168474-a184-4a99-9d96-d8870bca9f02)

**Environment (please complete the following information):**

 - Kubernetes version 1.28.3 & 1.28.5

**Comment by MichalKoziorowski-TomTom** [comment]
I definitely see same issue :)

**Comment by bondido** [comment]
And it's probably not just the kubernetes version issue, as our clusters with 1.28.3 had been scaling OK for two weeks after creation until autoscaler "broke" ~22.02.2024

**Comment by boliu83** [comment]
yes, last time I tested scaling up in 1.28.3 & 1.28.5 clusters, and this issue was found in both clusters.

**Comment by kevinharing** [comment]
Experiencing the same issue here on version 1.28.5. Costly bug as my auto-scaling node pool scales to maximum... (100 nodes in this case).

**Comment by dunefro** [comment]
We are also facing the same issue, where cluster autoscaler is trying to bring a lot of instances until the pod gets scheduled on one of them post which it starts to scale down the instances. We are using this configuration for cluster autoscaler
```json
        "autoScalerProfile": {
            "balance-similar-node-groups": "false",
            "expander": "random",
            "max-empty-bulk-delete": "10",
            "max-graceful-termination-sec": "180",
            "max-node-provision-time": "5m",
            "max-total-unready-percentage": "45",
            "new-pod-scale-up-delay": "10s",
            "ok-total-unready-count": "0",
            "scale-down-delay-after-add": "2m",
            "scale-down-delay-after-delete": "30s",
            "scale-down-delay-after-failure": "3m",
            "scale-down-unneeded-time": "1m",
            "scale-down-unready-time": "2m",
            "scale-down-utilization-threshold": "0.3",
            "scan-interval": "10s",
            "skip-nodes-with-local-storage": "true",
            "skip-nodes-with-system-pods": "true"
        }
```

**Comment by kevinkrp93** [comment]
We are rolling out the fix.

**Comment by jeffwmiles** [comment]
That's great to hear, thanks @kevinkrp93. Is there any visibility to this kind of rollout? Is it tracked on the AKS Release Status page, or if it is out of band is there anything we can identify in our cluster to see the fix has been applied?

**Comment by bondido** [comment]
> We are rolling out the fix.

@kevinkrp93 , is it also going to fix #4126 ?

**Comment by rkettelerij** [comment]
We're facing the same issue. Projected costs for this month has skyrocketed since lot's of nodes are being started during scale up without any workload being scheduled. So we're also interested to here about this:

> That's great to hear, thanks @kevinkrp93. Is there any visibility to this kind of rollout? Is it tracked on the AKS Release Status page, or if it is out of band is there anything we can identify in our cluster to see the fix has been applied?

**Comment by xec-abailey** [comment]
Hit this as well, single pod requested a scale up then the autoscaler targeted 5 nodes, then ultimately 7 nodes. It never did reach 7 and eventually settled for 5... wild behavior but thanks for being on top of it!

**Comment by kevinkrp93** [comment]
@rkettelerij - which region is you cluster in ?

**Comment by rkettelerij** [comment]
> @rkettelerij - which region is you cluster in ?

West Europe.

**Comment by aydosman** [comment]
@kevinkrp93 - How would we know the fix has been applied? I’ve checked the releases tracker and see no active branches. Thanks in advance.

**Comment by rkettelerij** [comment]
@kevinkrp93 any update on the roll out?

**Comment by xec-abailey** [comment]
> @kevinkrp93 any update on the roll out?

We aren't seeing the weird scaling behavior anymore, didn't hear anything definitive on the fix being rolled out but I assume it is

**Comment by kevinkrp93** [comment]
The fix should be fully rolled out now. Comment on this thread if you are unable to see it.

**Comment by bondido** [comment]
Is this over-provisioning issue still occurring?

**Comment by xec-abailey** [comment]
> Is this over-provisioning issue still occurring?

No, looks fixed
