### ISSUE TITLE
[Question] Azure FrontDoor & AKS traffic routing issues

### ISSUE THREAD

**Issue by eokorieFA** [Azure/AKS#4138]
**Describe scenario**
I am trying to route internet traffic to an AKS cluster via Azure FrontDoor.  I am currently using Azure FrontDoor standard and not Premium as we will be using Akamai handle the WAF and other bits.  The AKS cluster has been set up with an Ingress NGINX controller, which I have confirmed to be working.  SSL Termination is not required so making call via port 80 is fine for the being.  FrontDoor has been setup to use the AKS url *.cloudapp.azure.com (just-an-example.uksouth.cloudapp.azure.com) as the host name and the origin host header.  Everything has been configured using Terraform.

**Question**
With all the above configured, I am getting 504 errors.  Any ideas why?  Am I missing a configuration step somewhere?  Does the cluster need a certificate?  Am I missing a configuration on FrontDoor?  Any help is appreciated as I am stuck with this... 

Thanks,

Emmanuel

**Comment by eokorieFA** [comment]
Any movement on this issue?

**Comment by kamilzzz** [comment]
If you are fine with terminating TLS at the edge you do not need a certificate for the ingress controller.

Did you verify you can access your cluster via `*.cloudapp.azure.com` FQDN, I assume this is FQDN assigned to your PIP used by ingress controller, right?

From high level, your setup should generally work. Unless something is misconfigured here and there...

**Comment by eokorieFA** [comment]
I completely forgot about this thread.  I went back throught my code and reviewed the network security group configuration.  As it was initially locked down to only allow Cloudflare IPs, i added the Azure FrontDoor service tag and this allow things to work as expected.
