### ISSUE TITLE
[Question]OOM behavior is different on AKS 1.28.5 and AKS 1.27.9 (and old version)

### ISSUE THREAD

**Issue by hellozwinger** [Azure/AKS#4154]
**What I observed:**
In AKS 1.27.9 (and old version), when I tried to allocate a large memory (bigger than the configuration of "resources-->limites-->memory"), the process for allocation is killed, but the pod is NOT killed.
In AKS 1.28.5, when I try to do the same operation, the pod is killed and a new pod is launched.

**Question:**
What cause this behavior change? 
How could I keep the behavior of AKS 1.27.9 on  AKS 1.28.5 cluster?

**Following are my test:**

My pod yaml has such configuration:
        resources:
          limits:
            memory: "460M"
            cpu: 300m
          requests:
            memory: "400M"
            cpu: 150m

And I composed a simple C program to malloc memory, this is to trigger the OOM.
The C program is put at the end of this document.

**On AKS 1.27.9 and older version**, the behavior is as following:
1/ Login a pod, allocate 100M memory for 4 times (totally 400M), and the pod is OK.
2/ Then allocate another 100M memory, I found one of **the old processes which allocate 100M is killed, and the new process is UP. And the pod is not killed.**

In node description, the info is as following:
      Warning  OOMKilling  35s   kernel-monitor, aks-appnodepool-yyyyy-vmss000002  Memory cgroup out of memory: Killed process 908201 (YYY) total-vm:106928kB, anon-rss:102288kB, file-rss:1432kB, shmem-rss:0kB, UID:0 pgtables:256kB oom_score_adj:945
**Only one process is killed.**

**On AKS 1.28.5** the behavior is as following:
1/ Login a pod, allocate 100M memory for 4 times (totally 400M), and the pod is OK.
2/ Then allocate another 100M memory, and then **this pod is killed**, and a new pod is launched.

The info for pod is:
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
    ....
    Mounts:
      /dev/shm from dshm (rw)  <--- in old AKS version, no such mount info.
  
The info for the node is:
      Warning  OOMKilling  2m    kernel-monitor, aks-nodepool1-xxxxx-vmss0000rx  Memory cgroup out of memory: Killed process 3365543 (ZZZ) total-vm:106924kB, anon-rss:10048kB, file-rss:1340kB, shmem-rss:0kB, UID:0 pgtables:76kB oom_score_adj:973
**Not only the above one info, all processes in the pod are killed.**

====== C program for test =============
The C program is as following, and in a pod, I execute following to allocat memory:
"nohup ./a.out 100 &"    //  this is to allocat 100M memory, and this is not released.
Command "ps -efaux" can be used to check this.

`#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

int main(int argc,char*argv[])
{
    int a = atoi(argv[1] );
    printf("%d M is to be allocated",a);
    int size = 1024*1024*a;
    int *ptr = (int*) malloc(size);    // it should be pointer, but the star is missing after upload here.
    memset(ptr, 0, size);
    while (1==1) {
       sleep(10);
    }
}`

**Comment by pauska** [comment]
This is a change in Kubernetes 1.28, the OOM killer is now cgroups v2 aware and will kill the container instead of just the process.

Search the [changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md) for OOM and you'll find it.

I don't know if you can modify this behavior in AKS.

**Comment by hellozwinger** [comment]
@aritraghosh  @allyford  
Hi, 
Just want to check with you about this issue, is this fixed or is there a way for me to configure the AKS before upgrading?

So far, we are running on AKS1.27, as I mentioned previously, our service is bind to current default behavior, that is:
If the overload is higher in a pod, some threads are killed, but the main process and other thread is running, our system is desinged to accept this way; but the system could not accept the pod is killed.

With higher version of AKS, eg: 1.28, the pod will be killed when it is overload. And this is caused by changing the default setting of OOM mechanism. 

In the future, we have to upgrade to AKS 1.28 or higher version since the AKS 1.27 will be retired, then our system/service will be affeced, this is unacceptable.

I think the following are acceptable:

During the upgrade, please provide a chance for us to configure the setting for OMM behavior (kill thread, kill pod), and this setting is applied to the AKS for all related node pool, including the case when we applied auto scale up/down, the same setting should be effective to all newly created nodes.

If AKS1.28 could not provide this, it is also acceptable to provide this in higher version.
We may upgrade to AKS1.28 and then to higher version continuously, although our servcie will be affected for longger time, but this is acceptable.

Do you think this is reasonable?

Long for your reply!

Thanks!

Weiguo

**Comment by hellozwinger** [comment]
@aritraghosh  @allyford  
Hi, 
Just want to check with you about this issue, is this fixed or is there a way for me to configure the AKS before upgrading?

So far, we are running on AKS1.27, as I mentioned previously, our service is bind to current default behavior, that is:
If the overload is higher in a pod, some threads are killed, but the main process and other thread is running, our system is desinged to accept this way; but the system could not accept the pod is killed.

With higher version of AKS, eg: 1.28, the pod will be killed when it is overload. And this is caused by changing the default setting of OOM mechanism. I do NOT think the default behavior should be changed, and it is OK provide an easy way to change it during the upgrade.

**In the future, we have to upgrade to AKS 1.28 or higher version since the AKS 1.27 will be retired, then our system/service will be affeced, this is unacceptable.**

**I think the following are acceptable:**

During the upgrade, please provide a chance for us to configure the setting for OMM behavior (kill thread, kill pod), and this setting is applied to the AKS for all related node pool, including the case when we applied auto scale up/down, the same setting should be effective to all newly created nodes.

If AKS1.28 could not provide this, it is also acceptable to provide this in higher version.
We may upgrade to AKS1.28 and then to higher version continuously, although our servcie will be affected for longger time, but this is acceptable.

Do you think this is reasonable?

Long for your reply!

Thanks!

Weiguo
