### ISSUE TITLE
[BUG] Using Standard_B2ats_v2 as VM in node pool results in Kubelet failing with invalid capacity 0 on image filesystem

### ISSUE THREAD

**Issue by vikasra** [Azure/AKS#4156]
**Describe the bug**
1. Creat a user pool with Standard_B2ats_v2 sku (not this SKU does not have temporary storage)
2. Attempt to deploy a pod
3. Node fails to start - kubectl describe node shows that Kubelet is continuously restarting with the following error even though this is a hello world example where enough space is present on OS Disk. Cannot debug as kubelet is not started on the node

 Normal   Starting                 33s                  kubelet                        Starting kubelet.
 Warning  InvalidDiskCapacity      33s          kubelet                        invalid capacity 0 on image filesystem
 Normal   Starting                 31s                  kubelet                        Starting kubelet

**To Reproduce**
1. Provision machine pool:

az aks nodepool add --resource-group <rg> --cluster-name <cluster name> --name testnodepool --node-count 1 --node-vm-size Standard_B2ats_v2

2. Attempt to deploy any pod
3. See error above

**Expected behavior**
Pod can be installed and can rely on persistent volume claims for any additional storage needs. If kubelet has a temporary disk dependency, should be a way to attach a mount as part of machine pool creation. 

**Screenshots**

**Environment (please complete the following information):**

azure-cli: "2.58.0
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.9
Browser: Edge

**Additional context**

**Comment by AllenWen-at-Azure** [comment]
Hi @vikasra, in my cluster, when I add one Standard_B2ats_v2 node, the kubelet failed to start. when describing the node, I can find the allocatable resources are like 
``` 
Capacity:
  cpu:                2
  ephemeral-storage:  129886128Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             915288Ki
  pods:               110
Allocatable:
  cpu:                1900m
  ephemeral-storage:  129886128Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             0
  pods:               110
```

So, there is no memory available which causes kubelet failed to start. 
You need to choose another VM SKU which has more memory. Actually, the [AKS doc](https://learn.microsoft.com/en-us/azure/aks/quotas-skus-regions#restricted-vm-sizes) also suggest not to use B-series VM.

**Comment by vikasra** [comment]
Thank you! The docs were a little ambiguous, they mentioned 4GB for system pools but implied less was needed for user pools. Will use a larger VM.
