### ISSUE TITLE
Net/http:  TLS handshake timeout (Underlying MS-Azure Infrastructure and possible Alarms)

### ISSUE THREAD

**Issue by necevil** [Azure/AKS#416]
Hey guys,
So this is in relation to attempting to find the best possible workaround options for the intermittently occurring  'Unable to connect Net/http: TLS handshake timeout' issue which I am documenting over here: https://stackoverflow.com/questions/50726534/unable-to-connect-net-http-tls-handshake-timeout-why-cant-kubectl-connect

Obviously AKS is in preview, but personally I do plan to use it to host our production site (Ghost blog, very low resource utilization with all content offloaded to CDN, therefore very easy to re-create).  I understand that I will probably end up re-creating.

My goal is to find ways to mitigate this issue to make the problem easier / faster to mitigate thereby making it more realistic to move more production oriented apps / Clusters to Azure AKS.

Azure AKS DevOps Infrastructure (MS's not our Cluster's)
-------
I am functioning on the current Hypotheses that I would like to confirm (or disprove) with Azure DevOps:

1. There are multiple Azure AKS Management Servers which each have a sub-regional responsibility to provide management functionality to some number of customer Clusters based on some criteria (This is True, see my StackOverFlow post).
2. The infrastructure that hosts the Azure AKS Management Servers themselves (NOT my / our / customer Cluster nodes) decides on which Management Server handles which customer Cluster based on the NODE SIZE of that new Cluster (Need Feedback on this)
3. The Azure AKS Management Server infrastructure is running on Service Fabric based resources (Unrelated really just curious)

Re-Alarms
---------
As mentioned in that StackOverflow Question / Answer I noticed that the resource utilization on my Cluster fluctuated (dropped at least 5-10%, see StackOverflow for charts) while it was experiencing the TLS handshake issue.  This made me think that we can probably alarm for the issue off of our Metrics as an AKS Customer with a little bit of work (see SOF for metric charts: https://stackoverflow.com/questions/50726534/unable-to-connect-net-http-tls-handshake-timeout-why-cant-kubectl-connect).

My question to Azure support on this is:
>Does MS Azure support / DevOps currently have any Alarms in place regarding this issue (on AZURE's infrastructure) or are instances of this problem detected (and then addressed) based on Customer Help Tickets that are posted to Support via the Web Console?

**Comment by nphmuller** [comment]
I think I'm having this issue too since today. Many of my pods keep being restarted, because the liveness probe keeps failing. And the reason it keeps failing is because request times out:
`Warning  Unhealthy    8m (x39 over 1h)  kubelet, aks-agentpool-10516367-0  Liveness probe failed: Get http://10.50.48.14:8080/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`.

Also had the message `Net/http: TLS handshake timeout` a couple of times when running kubectl commands.

**Comment by jnoller** [comment]
Closing as stale
