### ISSUE TITLE
Catalog controller crashing on 1.9.6 

### ISSUE THREAD

**Issue by amazaheri** [Azure/AKS#417]
Liveness probe failed: HTTP probe failed with statuscode: 500
Back-off restarting failed container

I had this along with OSBA on my older cluster running just fine but had to re-provision and now its failing on 1.9.6

**Comment by sauryadas** [comment]
Can you redeploy SVC with helm chart and if it still doesnt redeploy a cluster? I tried it on my 1.9.6 cluster and wasnt able to repro.
<img width="1328" alt="screen shot 2018-06-08 at 4 01 07 pm" src="https://user-images.githubusercontent.com/15387759/41184501-81d896ac-6b35-11e8-83fe-d7da5193e555.png">

**Comment by sauryadas** [comment]
Need more Info ... is rbac enabled ?

**Comment by amazaheri** [comment]
rbac is disabled

**Comment by amazaheri** [comment]
So you are asking to delete the chart and install it again?

**Comment by sauryadas** [comment]
Yes and observe if it takes time to start and then it goes back from running state to crashloopbackoff state .. please paste the logs as well

Thanks
Saurya
________________________________

**Comment by amazaheri** [comment]
irvinemtcs-MacBook-Pro:~ amazaheri$ helm status catalog
LAST DEPLOYED: Fri Jun  8 20:54:00 2018
NAMESPACE: catalog
STATUS: DEPLOYED

RESOURCES:
==> v1/Secret
NAME                            TYPE    DATA  AGE
catalog-catalog-apiserver-cert  Opaque  2     34s

==> v1/Service
NAME                       TYPE      CLUSTER-IP   EXTERNAL-IP  PORT(S)        AGE
catalog-catalog-apiserver  NodePort  10.0.146.43  <none>       443:30443/TCP  34s

==> v1beta1/Deployment
NAME                                DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
catalog-catalog-apiserver           1        1        1           1          34s
catalog-catalog-controller-manager  1        1        1           1          34s

==> v1beta1/APIService
NAME                           AGE
v1beta1.servicecatalog.k8s.io  34s

==> v1/ServiceAccount
NAME                                SECRETS  AGE
service-catalog-apiserver           1        34s
service-catalog-controller-manager  1        34s

==> v1/Pod(related)
NAME                                                 READY  STATUS   RESTARTS  AGE
catalog-catalog-apiserver-8d85b8b48-s7rzh            2/2    Running  0         33s
catalog-catalog-controller-manager-689696c447-75p66  1/1    Running  0         33s

**Comment by amazaheri** [comment]
Readiness probe failed: Get https://10.244.2.11:8444/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
kubelet aks-agentpool-32181145-1
spec.containers{controller-manager}
8
2018-06-09T03:56 UTC
2018-06-09T04:00 UTC
warning
Liveness probe failed: Get https://10.244.2.11:8444/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
kubelet aks-agentpool-32181145-1
spec.containers{controller-manager}
5
2018-06-09T03:56 UTC
2018-06-09T03:57 UTC
Killing container with id docker://controller-manager:Container failed liveness probe.. Container will be killed and recreated.
kubelet aks-agentpool-32181145-1
spec.containers{controller-manager}
2
2018-06-09T03:56 UTC

**Comment by neilpeterson** [comment]
I am seeing this issue both on a new 1.9.6 cluster and a new 1.8.7 cluster.

**Comment by sauryadas** [comment]
adding @carolynvs as well

**Comment by carolynvs** [comment]
As a workaround for now, please uninstall service catalog, and reinstall it at --version 0.1.17.

**Comment by carolynvs** [comment]
UPDATE: The v0.1.17 just takes longer to hit this problem. The current workaround is to edit the service catalog controller-manager deployment and remove the readiness and liveliness probes completely.

**Comment by amazaheri** [comment]
That resolved the issue, I tried the Wordpress helm with MySql but it failed. Digging the logs

**Comment by carolynvs** [comment]
@amazaheri Thanks for reporting back! If you find out any more information on that failure with mysql, I'd appreciate the help tracking this down. 👍

**Comment by carolynvs** [comment]
`CreateContainerConfigError` implies that there is a problem with the definition of the container that is preventing k8s from creating it, for example it can't create the PV. That is a separate problem from this issue however. I suggest running kubectl describe on the wordpress pod, and look for the problem in the Events section.

**Comment by jeremyrickard** [comment]
The `CreateContainerConfigError` can also be a normal state while provisioning of everything is occurring. For example, the pod will depend on a secret created via the binding. The binding cannot be created until the instance is provisioned. As @carolynvs suggests, using `kubectl describe` on the pod and giving us back the info would be the best way to troubleshoot that.

**Comment by amazaheri** [comment]
Thank you both, I think somehow during the SQL Provisioning things went south. 

  Type     Reason                 Age                From                               Message
  ----     ------                 ----               ----                               -------
  Normal   Scheduled              5m                 default-scheduler                  Successfully assigned wordpress-wordpress-694d54d794-xtzbt to aks-agentpool-32181145-1
  Normal   SuccessfulMountVolume  5m                 kubelet, aks-agentpool-32181145-1  MountVolume.SetUp succeeded for volume "default-token-k8dp4"
  Normal   SuccessfulMountVolume  5m                 kubelet, aks-agentpool-32181145-1  MountVolume.SetUp succeeded for volume "pvc-d7e18b94-6dd1-11e8-8cc2-0a58ac1f162a"
  Normal   Pulled                 3m (x12 over 5m)   kubelet, aks-agentpool-32181145-1  Container image "bitnami/wordpress:4.9.4-r0" already present on machine
  Warning  Failed                 56s (x23 over 5m)  kubelet, aks-agentpool-32181145-1  Error: secrets "wordpress-wordpress-mysql-secret" not found

**Comment by cradle77** [comment]
I've tried the workaround to remove the readiness and liveliness probes, but apparently I can't deploy anything: for example, helm install azure/wordpress never completes.

if I do
`kubectl describe serviceinstance whatever`
this is what I get:
```Status:
  Async Op In Progress:  false
  Conditions:
    Last Transition Time:         2018-06-12T20:06:57Z
    Message:                      The instance references a ClusterServiceClass that does not exist. References a non-existent ClusterServiceClass {ClassExternalName:"azure-mysql-5-7"} or there is more than one (found: 0)
    Reason:                       ReferencesNonexistentServiceClass
    Status:                       False
    Type:                         Ready
  Deprovision Status:             NotRequired
  Observed Generation:            1
  Orphan Mitigation In Progress:  false
  Provision Status:
  Reconciled Generation:          0
Events:
  Type     Reason                             Age                From                                Message
  ----     ------                             ----               ----                                -------
  Warning  ReferencesNonexistentServiceClass  21s (x15 over 1m)  service-catalog-controller-manager  References a non-existent ClusterServiceClass {ClassExternalName:"azure-mysql-5-7"} or there is more than one (found: 0)```

What could I be missing?

**Comment by jeremyrickard** [comment]
Hi @cradle77 the error you're getting indicates that `azure-mysql-5-7` doesn't exist as a service class. Could you do the following?

```console
kubectl get clusterservicebrokers
kubectl get clusterserviceclasses -o=custom-columns=NAME:.metadata.name,EXTERNAL\ NAME:.spec.externalName
```

That should list out what broker and service classes are available. The error you got above indicates that service catalog went to provision an instance, however it couldn't find the class it expected from your request. This might happen if the broker is not registered. You could try removing OSBA (helm delete --purge osba) and re-install it. By default, service catalog installs with an embedded etcd. When you did the work around, it's possible etcd came back up w/ no data so svc cat didn't know about the broker any longer or the catalog didn't get populated.

**Comment by cradle77** [comment]
That was it @jeremyrickard, I had to reinstall osba. Thank you!

**Comment by jeremyrickard** [comment]
@cradle77 great .....well not great that you had to :( but great that it worked :)

We're soon have some more documentation published with some instructions / best practices for running both Service Catalog and Open Service Broker for Azure in a more production like capacity. Keep an eye on https://github.com/Azure/open-service-broker-azure for more info

**Comment by amazaheri** [comment]
I see this issue very frequently which is like time race 

PersistentVolumeClaim is not bound: "osba-redis" (repeated 3 times)
Unable to mount volumes for pod "osba-redis-c555f5c6-6nj4s_osba(9214bbb0-6f34-11e8-8cc2-0a58ac1f162a)": timeout expired waiting for volumes to attach/mount for pod "osba"/"osba-redis-c555f5c6-6nj4s". list of unattached/unmounted volumes=[redis-data] 

So far OSBA not happy :(

**Comment by jeremyrickard** [comment]
@amazaheri if you'd like to use an external Redis (we are going to be recommending that for production usage..we'll have a document PR'ed today using etcd-operator and Redis Cache if you'd like to beta test that for us!), I'd recommend using Azure Redis Cache. Pretty easy to create:

On my mac:
$ export REDIS_CACHE_NAME=osba-redis-$(uuidgen)
$ az redis create --name $REDIS_CACHE_NAME -g osba -l eastus --sku Basic --vm-size C0
<some time passes>
$ az redis show --name $REDIS_CACHE_NAME -g osba -o table
<repeat until provisioning completes>
$ az redis list-keys --name $REDIS_CACHE_NAME -g osba -o table

Using the last two az commands, you can get the hostname + primary access key for the cache and then you can run the OSBA helm install like so:

$ export REDIS_HOSTNAME=<Redis Host>
$ export REDIS_PASSWORD=<Redis PrimaryKey>
$ helm install azure/open-service-broker-azure --name osba --namespace osba \
      --set azure.subscriptionId=$AZURE_SUBSCRIPTION_ID \
      --set azure.tenantId=$AZURE_TENANT_ID \
      --set azure.clientId=$AZURE_CLIENT_ID \
      --set azure.clientSecret=$AZURE_CLIENT_SECRET \
      --set redis.embedded=false \
      --set redis.host=$REDIS_HOSTNAME \
      --set redis.redisPassword=$REDIS_PASSWORD

This will start up OSBA w/ the external Redis, so you shouldn't encounter that issue. 

Note that this is a Basic Redis Cache, so it's not HA (we recommend standard or premium for prod use)

**Comment by amazaheri** [comment]
time="2018-06-13T18:44:17Z" level=info msg="Open Service Broker for Azure starting" commit=ab4f237 version=v0.11.0
time="2018-06-13T18:44:17Z" level=info msg="Setting log level" logLevel=INFO
time="2018-06-13T18:44:17Z" level=info msg="Sensitive instance and binding details will be encrypted" encryptionScheme=AES256
time="2018-06-13T18:44:17Z" level=info msg="API server is listening" address="http://0.0.0.0:8080"
time="2018-06-13T18:44:17Z" level=fatal msg="async engine stopped: error sending heartbeat for worker d66659f3-55e9-4b51-8599-ac7760348eab: dial tcp: lookup osba-redis-6232fc2d-f694-4337-ac50-9af5d28de0c7 on 10.0.0.10:53: server misbehaving"

**Comment by amazaheri** [comment]
Thanks that did the trick like Service Catalog I had to remove readinessprobe from deployment. I see the same challenge with Wordpress Pod though and not sure if this is my cluster or a known issue.

PersistentVolumeClaim is not bound: "wordpress1-wordpress" (repeated 3 times)
Unable to mount volumes for pod "wordpress1-wordpress-69f9fd6588-wcmcb_wordpress1(76211193-6f3a-11e8-8cc2-0a58ac1f162a)": timeout expired waiting for volumes to attach/mount for pod "wordpress1"/"wordpress1-wordpress-69f9fd6588-wcmcb". list of unattached/unmounted volumes=[wordpress-data]

**Comment by amazaheri** [comment]
time="2018-06-13T20:39:05Z" level=error msg="error executing job; not submitting any follow-up tasks" error="error executing provisioning step \"preProvision\" for instance \"620d166c-6f49-11e8-9812-fa024bc3d741\": error executing provisioning step: error determining server name availability: mysql.CheckNameAvailabilityClient#Execute: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailed\" Message=\"The client 'a9cf1ce6-3ca0-4b20-89ea-3c3d6422e0af' with object id 'a9cf1ce6-3ca0-4b20-89ea-3c3d6422e0af' does not have authorization to perform action 'Microsoft.DBforMySQL/checkNameAvailability/action' over scope '/subscriptions/b326f01f-b5a4-4e7d-948f-f13b4f678ac7'.\"" job=executeProvisioningStep taskID=929d37a4-c8be-4ca2-9e1c-da835242438d
time="2018-06-14T00:52:46Z" level=error msg="error executing job; not submitting any follow-up tasks" error="error executing deprovisioning step \"deleteARMDeployment\" for instance \"620d166c-6f49-11e8-9812-fa024bc3d741\": error executing deprovisioning step: error deleting ARM deployment: error deleting deployment \"\" from resource group \"wordpress\": resources.DeploymentsClient#Delete: Invalid input: autorest/validation: validation failed: parameter=deploymentName constraint=MinLength value=\"\" details: value length must be greater than or equal to 1" job=executeDeprovisioningStep taskID=677b7071-c893-4403-b604-daa440c2895f
time="2018-06-14T01:59:39Z" level=error msg="error executing job; not submitting any follow-up tasks" error="error executing provisioning step \"preProvision\" for instance \"2e061701-6f76-11e8-9812-fa024bc3d741\": error executing provisioning step: error determining server name availability: mysql.CheckNameAvailabilityClient#Execute: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailed\" Message=\"The client '**a9cf1ce6-3ca0-4b20-89ea-3c3d6422e0af**' with object id 'a9cf1ce6-3ca0-4b20-89ea-3c3d6422e0af' does not have authorization to perform action 'Microsoft.DBforMySQL/checkNameAvailability/action' over scope '/subscriptions/b326f01f-b5a4-4e7d-948f-f13b4f678ac7'.\"" job=executeProvisioningStep taskID=aea07672-ac3a-4d9b-b0fd-6dfd995cc71d

**Comment by amazaheri** [comment]
This could be the cause I see intermittently
