### ISSUE TITLE
[BUG] remounting between nodes takes long time

### ISSUE THREAD

**Issue by pawellrus** [Azure/AKS#4170]
**Describe the bug**
PV remounting between nodes takes about 10-15 minutes. During that period newly sheduled pods throw multi-attach error.

**To Reproduce**
1. Run some maintenance operation with node pool that requires node re-creation
2. Wait

**Expected behavior**
Pod should be rescheduled and get up wtihin couple of minutes

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes version 1.27.7

**Comment by PixelRobots** [comment]
Hey, are you using availability zones for your node pools? If so, you might want to look at using ZRS disks to help speed up disk mounting. 

You can check more information out at this [link](https://techcommunity.microsoft.com/t5/fasttrack-for-azure/a-practical-guide-to-zone-redundant-aks-clusters-and-storage/ba-p/4036254)

**Comment by pawellrus** [comment]
@PixelRobots , yep I have node pool stretched over several zones. All persistent volumes are of StandardSSD_ZRS class.

**Comment by PixelRobots** [comment]
Ok then that sounds like something is wrong. Can you log a ticket with support so they can have a look at your cluster and configuration?

**Comment by pawellrus** [comment]
@PixelRobots if it's the only option then I could do it.

**Comment by PixelRobots** [comment]
It would be the quickest. If you have issues with support or something let us know here.

**Comment by andyzhangx** [comment]
@pawellrus what do you mean by `node re-creation`? it takes a few minutes for node becoming NotReady, and thus pod rescheduling happen, that would also take time.

**Comment by pawellrus** [comment]
@andyzhangx I mean that after node is created and it's status is READY, pods with PV still cannot schedule on that node because their PV's are still bound to old node. It happens during operations that require nodepool recreation.
