### ISSUE TITLE
[BUG] - Node Failure with GuestOSCrashWithBugCheck Error

### ISSUE THREAD

**Issue by claudiogodoy99** [Azure/AKS#4177]
**Describe the bug**
While attempting to create a node through the webhook webhook.brs.azure-automation.net/webhooks, a node **GuestOSCrashWithBugCheck** failure occurred . The node entered an unhealthy state, restarted twice, and then resumed operation.

**To Reproduce**
The problem is intermittent

**Expected behavior**
no node failure while creating nodes.

**Details**

Error Details:
StartTime: 2024-03-22T06:06:28.8386993Z
AvailabilityState: Down
RCAEngineCategory: Unplanned
RCALevel1: ContainerFault
RCALevel2: GuestOSCrashWithBugCheck
RCALevel3: HyperVEvent:18590(**MSVM_GUEST_CRASH_REPORT); BugCheckCode:(0x1(APC_INDEX_MISMATCH))**
Health: Unhealthy

**Environment:**
  - Kubernetes version 1.27.3
  - OS Distro aks-ubuntu-containerd-22.04-gen2

**Comment by AllenWen-at-Azure** [comment]
Hi @claudiogodoy99 could you please provide detail steps to reproduce the issue? I understand it might be a intermittent issue, but a clearer steps could help us to investigate the issue.
