### ISSUE TITLE
AGIC Add-on no longer present on networking page

### ISSUE THREAD

**Issue by jmajoor** [Azure/AKS#4183]
**Describe the bug**
The AKS networking page used to have an option to enabled the AGIC add-on.
This option is no longer present on this page, though the documentation still refers to it.

**To Reproduce**
Navigate to an AKS networking page.
Try to add AGIC or try to navigate to your gateway from this page.

**Expected behavior**
An option to enabled AGIC if not enabled.
A link to AGIC if enabled.

**Environment (please complete the following information):**
-  Azure Portal / AKS
 - Kubernetes version 1.28.3
 - Browser Edge

**Comment by JoeyC-Dev** [comment]
> This option is no longer present on this page, though the documentation still refers to it.

It is being removed: https://github.com/MicrosoftDocs/azure-docs/pull/120733

**Comment by jmajoor** [comment]
Are there plans to bring this back to the portal on some other page (maybe specific to add-ons).
I found it convenient to be able to setup a cluster with AGIC enabled through the portal and you could easily navigate from your cluster to the gateway definitions and modify it.

**Comment by JackStromberg** [comment]
The option has been added back as part of the new networking blade experience.
![image](https://github.com/Azure/AKS/assets/15022563/0802158d-bcb7-4c8f-9726-4e6def813fb3)

Apologies for the inconvenience.
