### ISSUE TITLE
Using Azure Container Service

### ISSUE THREAD

**Issue by solankigithub** [Azure/AKS#419]
Hello,
I have a docker image that i would like to deploy on Azure Container Service.
When i click on "pricing", it opens the link of pricing for AKS.

AKS is currently showing as "Preview" version. Also, ACS will be decommissioned and will be transitioned to AKS soon.
What should we use now? ACS or AKS (for production application). If ACS then how can i get the pricing for ACS ?

Thanks

**Comment by dstrebel** [comment]
I would recommend AKS at this point, as ACS will be decommissioned. You'll also save on cost as you don't pay for or manage the masters in AKS. Just to note ACS cost you pay for whatever virtual machine node types you deploy. So if you run 3 x masters and 3 x worker nodes, then you pay for 6 VMs.

**Comment by sauryadas** [comment]
In AKS you get a list of new features like custom vnet, integrated monitoring/logging, AAD integration, simple upgrades. I recommend moving to AKS. 

Closing this issue. LMK if you have any other questions.
