### ISSUE TITLE
[Question] AKS with Managed Identity attach to ACR on a different Microsoft Entra tenant

### ISSUE THREAD

**Issue by AdelRefaat** [Azure/AKS#4190]
**Describe scenario**
The AKS cluster is in Tenant A and the Azure container registry is in Tenant B.
The AKS cluster is configured with Managed Identity

**Question**
How can I attach AKS Cluster on Tenant A to ACR on tenant B, when AKS is using Managed Identity
As per doc here https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/managed-identities-faq 
"managed identities don't currently support cross-directory scenarios"

I have tried 
`az aks update -g <ResourceGroup> -n <Name> --attach-acr /subscriptions/<SubscriptionId>/resourceGroups/<AcrResourceGroup>/providers/Microsoft.ContainerRegistry/registries/<AcrName> --debug`

I am getting back 
"Could not create a role assignment for ACR. Are you an Owner on this subscription?"

The debug log is all about:
Principal xyz does not exist in the directory abc. Check that you have the correct principal ID.

What may be the way to attach ACR in this case?

Knowing that there is a documentation for AKS Cluster with Service Principle here
https://learn.microsoft.com/en-us/azure/container-registry/authenticate-aks-cross-tenant?source=recommendations

**Comment by philwelz** [comment]
Hey, i would not recommend using AKS with Service Principal bcs its more the old way and some newer feature require AKS with managed identity (System or User). Furthermore u have to rotate your secrets and this is kinda cumbersome.

For your specific scenario i would see this 3 options, as cross-directory scenarios are not supported (as u already mentioned).

1. Enable Anonymous pull on the ACR (but the ACR should be private in that case and allow only connections from the internal network)
2. Use Access Keys and Pull secrets inside AKS
3. Use[ connected registry ](https://learn.microsoft.com/en-us/azure/container-registry/quickstart-connected-registry-cli)feature and replicate the repos to a registry in the correct tenant

Maybe there are more options but his is it for now :)

**Comment by AdelRefaat** [comment]
Probably at least `az aks update —attach-acr ` should fail with a **better** descriptive error message in this case of cross-directory with Managed Identity AKS
