### ISSUE TITLE
Windows host process default path is showing as c:\ instead of c:\hpc on AKS cluster version 1.28.5

### ISSUE THREAD

**Issue by anilkumar1619** [Azure/AKS#4196]
Hello Team,

I am trying to deploy windows host process for containers by following below document and when checked, I noticed the default exec path in the container is showing as c:\ instead of c:\hpc.

https://learn.microsoft.com/en-us/azure/aks/use-windows-hpc

This is working as expected in 1.27.x whereas it is incorrect in 1.28.5. In 1.28.x container, $env.CONTAINER_SANDBOX_MOUNT_POINT is set to c:\hpc but while connecting it is by default taking to c:\

As per below Github issues and the document it says C:\hpc is the right path.

https://github.com/Azure/AKS/issues/3885

https://github.com/kubernetes/enhancements/tree/master/keps/sig-windows/1981-windows-privileged-container-support#container-mounts

![image](https://github.com/Azure/AKS/assets/84578520/69d8b08b-63c7-4f46-8b85-686c6253d81a)

Below are the screenshots for reference.

Left, 1.27.9, default working folder is expected C:\C:{container-id} which is correct.
Right, 1.28.5, default working folder is supposed to be C:\hpc but it turns out to be C:\ instead.
<img width="843" alt="image" src="https://github.com/Azure/AKS/assets/84578520/8c0eb2a6-de52-475b-ab47-22b9f65ac8d2">

Kindly check and assist if this is expected or not.

**Comment by AbelHu** [comment]
Workaround: Switch the working directory to `$env:CONTAINER_SANDBOX_MOUNT_POINT` before running the commands
Will be fixed in https://github.com/containerd/containerd/pull/10069

**Comment by AbelHu** [comment]
The fix https://github.com/containerd/containerd/pull/10069 is included in Windows containerd v1.7.17 which is being rolled out in AKS RP release v20240609. You can track the release progress in https://releases.aks.azure.com/webpage/index.html#tabversion.
