### ISSUE TITLE
[BUG] Managed CSI Blob Driver doesn't clean all resources after being uninstalled

### ISSUE THREAD

**Issue by Vegoo89** [Azure/AKS#4199]
**Describe the bug**
After Blob CSI is uninstalled, it doesn't clean all resources from the cluster (e.g. service account and clusterrole), so if I try to bring my own CSI and install it via helm chart, it fails.

**To Reproduce**
1. Enable Blob CSI on the AKS Cluster
2. Disable Blob CSI on the AKS Cluster
3. Try to install Blob CSI using Helm

**Expected behavior**
After disabling the managed Blob CSI, Helm chart installation should work

**Screenshots**
None

**Environment (please complete the following information):**
 -  CLI not used
 - Kubernetes version 1.29.2

**Additional context**
None

**Comment by andyzhangx** [comment]
@Vegoo89 thanks for reporting this issue. May I know why do you want to use open source blob csi driver instead of managed one?

**Comment by Vegoo89** [comment]
We are using 1.24 which provides workload identity integration with static provisioning without storage key usage. AKS currently supports 1.23 in Kubernetes 1.29.2 version.

**Comment by mkemmerz** [comment]
> We are using 1.24 which provides workload identity integration with static provisioning without storage key usage. AKS currently supports 1.23 in Kubernetes 1.29.2 version.

Did you get it to run on AKS 1.29.2? For us it didn't work. The releases are a bit confusing. blob-csi-driver has it mentioned in the 1.24.0 but AKS says it is supported since the last release. Nevertheless, we will just wait for the AKS with 1.24.0  blob-csi-driver.

**Comment by Vegoo89** [comment]
> > We are using 1.24 which provides workload identity integration with static provisioning without storage key usage. AKS currently supports 1.23 in Kubernetes 1.29.2 version.
> 
> Did you get the Workload identity to work for the Blob Csi Driver on AKS 1.29.2? For us it didn't work. The releases are a bit confusing. blob-csi-driver has it mentioned in the 1.24.0 but AKS says it is supported since the last release which only uses the 1.23.3. Nevertheless, we will just wait for the AKS with 1.24.0 blob-csi-driver.

Yes, that is why I installed my own CSI Driver using Helm chart. With managed one (1.23.x) currently it doesn't work.

**Comment by AllenWen-at-Azure** [comment]
Hi @Vegoo89 have you upgrade your cluster to use the managed Blob CSI driver? It was upgraded to 1.24.1 in this [release](https://github.com/Azure/AKS/releases/tag/2024-04-28),
