### ISSUE TITLE
azure cli aks get-credentials => save to file dos not work

### ISSUE THREAD

**Issue by aumanjoa** [Azure/AKS#42]
hi

I try to save the credentials for my kuberneties  pod into a file with this command

`az aks get-credentials --resource-group=chronas-k8s --name=myK8sCluster --file myk8sclusterConfig`

and get this error:

> [Errno 2] No such file or directory: ''
> Traceback (most recent call last):
>   File "/usr/local/Cellar/azure-cli/2.0.20/libexec/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
>     cmd_result = APPLICATION.execute(args)
>   File "/usr/local/Cellar/azure-cli/2.0.20/libexec/lib/python3.6/site-packages/azure/cli/core/application.py", line 212, in execute
>     result = expanded_arg.func(params)
>   File "/usr/local/Cellar/azure-cli/2.0.20/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in __call__
>     return self.handler(*args, **kwargs)
>   File "/usr/local/Cellar/azure-cli/2.0.20/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 620, in _execute_command
>     reraise(*sys.exc_info())
>   File "/usr/local/Cellar/azure-cli/2.0.20/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/usr/local/Cellar/azure-cli/2.0.20/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 602, in _execute_command
>     result = op(client, **kwargs) if client else op(**kwargs)
>   File "/usr/local/Cellar/azure-cli/2.0.20/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1275, in aks_get_credentials
>     os.makedirs(directory)
>   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 220, in makedirs
>     mkdir(name, mode)
> FileNotFoundError: [Errno 2] No such file or directory: ''

this is happening from cloud cli in the portal and on my local mac

**Comment by mboersma** [comment]
@aumanjoa nice find, should be a simple fix. As a workaround, you should be able to give a fully-qualified path to the `--file` argument:
```
$ az aks get-credentials --resource-group=chronas-k8s --name=myK8sCluster \
  --file $HOME/.azure/myk8sclusterConfig
$ # or
$ az aks get-credentials --resource-group=chronas-k8s --name=myK8sCluster \
  -f ./myk8sclusterConfig
```

**Comment by aumanjoa** [comment]
@mboersma thanks the workaround works.

**Comment by mboersma** [comment]
This will be in the next CLI release--2.0.22 I believe.
