### ISSUE TITLE
[Feedback] The oms_agent addon is not required anymore for Azure Monitor Agent (AMA) container insights for latest AKS versions

### ISSUE THREAD

**Issue by v-asen** [Azure/AKS#4208]
**Describe your scenario**
This documentation page describes the addon 'oms_agent' for AKS.

https://learn.microsoft.com/en-us/azure/azure-monitor/containers/kubernetes-monitoring-enable?tabs=terraform#enable-container-insights

However, it only deploys the ama deployment (ama-logs-rs), which seems to use the new Azure Monitor Agent (AMA), and not the depricated Log Analytics Agent (OMS).

**Feedback**
The oms_agent addon is not required anymore for Azure Monitor Agent (AMA) container insights for AKS. The documentation page linked here shows only to deploy the AMA deployment (ama-logs-rs), which uses the new Azure Monitor Agent. The oms_agent addon is related to the deprecated Log Analytics Agent (OMS), and it will also be retired once the Log Analytics agent is deprecated.

For AKS, if we are setting up container insights on a new cluster (specifically using the latest versions example 1.27 or 29) or migrating from the legacy OMS agent, one should use the Azure Monitor Agent.

The legacy OMS agent is only needed if you have specific dependencies on it or are running workloads that have not yet been tested or certified to work with the AMA.

**Comment by vdiec** [comment]
@v-asen thank you for the feedback! The oms_agent addon not being used. This is simply a field name in API. We plan to fix this with the upcoming API release. I will update this thread once the fix is implemented.

**Comment by bongi23** [comment]
So, if we use the oms_agent block in a terraform template we are deploying the new AMA agents, is this correct?

**Comment by vdiec** [comment]
@bongi23 yes, that is correct

**Comment by summahto** [comment]
I had a question here :

For existing AKS clusters specify to add the following to the AKS cluster terraform :

```
oms_agent {
    log_analytics_workspace_id = var.workspace_resource_id
    msi_auth_for_monitoring_enabled = true
  }
```

So , I did add this along with the DCR and DCRA. But what I am unable to understand `msi_auth_for_monitoring_enabled = true`  , which Managed Identity will be used to send the Container Insights ? Does it need to be assigned the role of `Monitoring Metrics Publisher` ?

**Comment by vdiec** [comment]
Tagging @ganga1980
