### ISSUE TITLE
AKS Cluster fails to provision agents with DNS fallback due to timeout in docker pull command.

### ISSUE THREAD

**Issue by lfshr** [Azure/AKS#421]
Hi guys,

Trying to spin out an AKS cluster in West Europe which is failing. Chased the logs and found this line in the "cluster-provision.log" file

How to Recreate:

1. Create a VNET with the primary DNS server being an unreachable address and the secondary DNS server being a valid address.
2. Create a Kubernetes Cluster with Advanced Networking that connects to the VNET
3. The VNET creation will end up in an endless loop and timeout after an hour

This scenario SHOULD work, but does not due to an infinite loop due to timeout.

You will find the line that causes the issue in the addon script for the nodes:
```
timeout 60 docker pull k8s-gcrio.azureedge.net/hyperkube-amd64:v1.9.6
```

This only gives the docker pull 60 seconds to do it's stuff, which is fine if the DNS resolution happens quickly, but not when the primary DNS server times out.

Here's the output from `time` when run manually:
```
$ time docker pull k8s-gcrio.azureedge.net/hyperkube-amd64:v1.9.6
v1.9.6: Pulling from hyperkube-amd64
d0c199d1a37e: Pull complete
9eea4969cc0f: Pull complete
e25b982f4e4f: Pull complete
39668194e1b9: Pull complete
259521fecfa9: Pull complete
7c5dab2ec3a4: Pull complete
a369eb40f60e: Pull complete
c7add3571bb3: Pull complete
Digest: sha256:ef1169d8ed08a69fb31a9aaafdceced4200dc9bea0ec03751f3638ae28646f51
Status: Downloaded newer image for k8s-gcrio.azureedge.net/hyperkube-amd64:v1.9.6

real    1m52.802s
user    0m0.025s
sys     0m0.015s
```

Can this timeout please be removed or increased?

Liam

**Comment by lfshr** [comment]
Sorry. I searched for the issue but couldn't find anything related. Just found #391. This appears to be related.

**Comment by lfshr** [comment]
Also, running this command manually caused the provisioning of agent0 to complete. 

![image](https://user-images.githubusercontent.com/893739/41238388-afaae0c6-6d8d-11e8-966a-e2b914e4ae1f.png)

**Comment by sauryadas** [comment]
Can you delete this cluster and try to create another cluster? possibly an isolated issue.

**Comment by lfshr** [comment]
Hi @sauryadas 

The cluster spin-out failed multiple times before I could be bothered exposing a public IP and SSHing to the box.
60s seems an insanely short timeout period for this action. Especially considering the docker-engine seems to think for around 40 seconds before even starting the pull.
I would also expect any isolation such as this to be as granular as a single agent machine. All 3 machines fail to build. It does only seems to be a problem in West Europe. Canada East seems to spin out ok. I shall spin out a cluster in Canada tomorrow morning (GMT) and have a look at the logs. I suspect that the docker daemon is quicker to respond and it's getting far enough for docker to be killed and restarted & pick up where it left off. Killing docker every 60 seconds doesn't feel like the "right" solution in my gut though 😢

**Comment by lfshr** [comment]
Hi @sauryadas 

Spun out a cluster in Canada East and that hit the same problem. The cluster goes into an endless loop until Docker can respond and download a 1GB image in less than a minute. It causes our cluster spinouts to range from 10 minutes to over and hour (and subsequent timeout failure). I believe if you increase this timeout limit to something more leanient (say 5 minutes) you will see a pretty good time decrease in the cluster spinouts and they would also be more stable. 

Same story here, a manual "docker pull" caused the agent script to continue without issue.

**Comment by lfshr** [comment]
@sauryadas any updates on this? I've updated the OP to include details to reproduce the issue.

**Comment by sauryadas** [comment]
@JunSun17 Can you take a look and recommend if we should increase the timeout?

**Comment by ccanuel** [comment]
I'm coming in from issue 391. I don't see the relation but I'm willing to play the game.

How can i replicate the DNS timeout to confirm that this is my issue and not something else?

**Comment by lfshr** [comment]
@ccanuel see OP.

**Comment by ccanuel** [comment]
OK confirmed-ish

recycling the dns pods worked

**Comment by JunSun17** [comment]
@jackfrancis @CecileRobertMichon if take longer than 60s to download, can we increase the timeout value?

**Comment by jackfrancis** [comment]
There are some downsides to increasing the timeout: for example, we degrade our ability to "fail fast" when there is a real problem with sourcing the image.

40 seconds seems a long time to wait for DNS resolution. Perhaps we should consider reconfiguring the DNS layer to step through its configured resolvers more quickly, like after 5 seconds, for example.

**Comment by lfshr** [comment]
@jackfrancis is there a specific reason you're killing the docker executable and not trusting it's ability to error handle?

**Comment by jackfrancis** [comment]
@lfshr do you mean why are we wrapping it inside a `timeout` call?

The answer to that, if that's why you're asking, is to enforce per-command time limits in the event of transient, as-yet-unidentified errata, particularly in the OS layer. Those time limits are aids towards achieving the trade-off of "do a best effort" plus "fail fast" that we are aiming to achieve by paving the application layer at runtime.

**Comment by jnoller** [comment]
closing as stale
