### ISSUE TITLE
[BUG] calico-kube-controllers Liveness and Readiness probe failed on Kubernetes version 1.28.5

### ISSUE THREAD

**Issue by win5923** [Azure/AKS#4212]
**Describe the bug**
```
event message:
Liveness probe failed: command "/usr/bin/check-status -l" timed out
Readiness probe failed: command "/usr/bin/check-status -r" timed out
```
pod logs have no error messages.

**Screenshots**
![image](https://github.com/Azure/AKS/assets/56353753/fe59acbb-a0a5-45d9-a9cd-f63d9fe2cbd1)

**Environment (please complete the following information):**
 - Kubernetes version 1.28.5
- mcr.microsoft.com/oss/calico/node version 3.24.6

**Comment by JoeyC-Dev** [comment]
I created a new AKS with 1.28.5 and check the `mcr.microsoft.com/oss/calico/node` `and mcr.microsoft.com/oss/calico/kube-controllers` are exactly `3.24.6`.  
![image](https://github.com/Azure/AKS/assets/142381267/97f9696d-f876-428e-bac7-9e6be1b387e1)

This first error popped after 12 mins of AKS creation:
```
KubeEvents
| where Namespace == "calico-system"
| where Message contains "check-status"
```

![image](https://github.com/Azure/AKS/assets/142381267/4ed2d6a7-8cb5-47d1-aaa7-57f19c4a39ee)
Container log won't give you anything:
![image](https://github.com/Azure/AKS/assets/142381267/bcfe7b55-54e9-4bcf-9579-c0c9d82fe9d3)
Checked the syslog, basically "timeout"
```
cat syslog | grep check-status
Apr 15 04:28:44 aks-agentpool-34739312-vmss000001 kubelet[2784]: E0415 04:28:44.075497    2784 remote_runtime.go:496] "ExecSync cmd from runtime service failed" err="rpc error: code = DeadlineExceeded desc = context deadline exceeded" containerID="02cb51467976c311b30c8f62b8d35f5e90f5d4857805acd9c5d8a451297947f7" cmd=["/usr/bin/check-status","-l"]
Apr 15 04:28:44 aks-agentpool-34739312-vmss000001 kubelet[2784]: I0415 04:28:44.075547    2784 prober.go:107] "Probe failed" probeType="Liveness" pod="calico-system/calico-kube-controllers-b889487db-ptwld" podUID="c20ed2ff-72a9-4685-8eea-528c7d47ce8b" containerName="calico-kube-controllers" probeResult="failure" output="command \"/usr/bin/check-status -l\" timed out"
Apr 15 04:43:54 aks-agentpool-34739312-vmss000001 kubelet[2784]: E0415 04:43:54.076051    2784 remote_runtime.go:496] "ExecSync cmd from runtime service failed" err="rpc error: code = DeadlineExceeded desc = context deadline exceeded" containerID="02cb51467976c311b30c8f62b8d35f5e90f5d4857805acd9c5d8a451297947f7" cmd=["/usr/bin/check-status","-l"]
Apr 15 04:43:54 aks-agentpool-34739312-vmss000001 kubelet[2784]: I0415 04:43:54.076099    2784 prober.go:107] "Probe failed" probeType="Liveness" pod="calico-system/calico-kube-controllers-b889487db-ptwld" podUID="c20ed2ff-72a9-4685-8eea-528c7d47ce8b" containerName="calico-kube-controllers" probeResult="failure" output="command \"/usr/bin/check-status -l\" timed out"
```
Don't think anything wrong on `calico-node`:
![image](https://github.com/Azure/AKS/assets/142381267/15628fdf-700a-408f-b53a-bb208786a241)

If executing below, you only get "Ready":
```
for i in {1..100} ; do kubectl exec calico-kube-controllers-b889487db-ptwld -n calico-system -- /usr/bin/check-status -l ; done
```
There is a possibility that the `timeoutSeconds: 10` is being set to a small value so the according events popped. But it does not look normal for the target to take more than 10s to respond. 
Maybe this is a bug. But I am not PG so I don't know.

**Comment by asakth22** [comment]
We're experiencing a similar problem on all of our AKS clusters. 
The Kubernetes & Calico version is 1.29.0 & v3.26.3 respectively.

**Comment by DevonK3** [comment]
We are experiencing the same issue as well.

**Comment by aydosman** [comment]
We are being affected by this issue too, observed on multiple clusters

example
Kubernetes version: 1.27.9
Architecture: amd64
Operating System: Linux
Ubuntu Version: 2204gen2containerd-202403.25.0
Image: mcr.microsoft.com/oss/calico/kube-controllers:v3.24.6

**Comment by Tadcas** [comment]
The same issue with 1.29.2 and 1.29.4 AKS versions.
Both uses mcr.microsoft.com/oss/calico/kube-controllers:v3.26.3 image.
Node image version: AKSUbuntu-2204gen2containerd-202403.25.0

**Comment by Farfaday** [comment]
Hi,
could that be the same issue as in https://github.com/Azure/AKS/issues/4219#issuecomment-2067051969 ?

**Comment by Icybiubiubiu** [comment]
@Tadcas 

I have compared the probe rules between image version 202403.25.0 and 202405.27.0.  they are configured with same probe rules:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/binglin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/binglin/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/binglin/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/binglin/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link=blue vlink="#96607D" style='tab-interval:.5in;word-wrap:
break-word'>



  | 之前探针配置/previous conf in 202403.25.0
-- | --
Calico-kube-controller | Liveness:       exec [/usr/bin/check-status -l]   delay=10s timeout=10s period=10s #success=1 #failure=6       Readiness:      exec [/usr/bin/check-status -r]   delay=0s timeout=10s period=10s #success=1 #failure=3
最新image里探针配置/conf in 202405.27.0
 
Calico-node | 之前探针配置/ previous conf in 202403.25.0
Liveness:       http-get http://localhost:9099/liveness   delay=0s timeout=10s period=10s #success=1 #failure=3       Readiness:      exec [/bin/calico-node -felix-ready]   delay=0s timeout=5s period=10s #success=1 #failure=3
最新image里探针配置/ conf in 202405.27.0
 




</body>

</html>
