### ISSUE TITLE
Will Cross Region Restore for AKS be available for Germany West Central

### ISSUE THREAD

**Issue by VikasPullagura-MSFT** [Azure/AKS#4217]
**Describe scenario**
Will Cross Region Restore for AKS be available for Germany West Central

**Question**
Currently the Azure Backup Vault does not support vault tier backup for an AKS cluster created in Germany West Central. This means that a backup and subsequent restore to Germany North as a paired region is not possible.
Will this feature be available in the future ? If so, when will it be available ?
If there are no plans to make it available, what options are there for a cross region disaster recovery for an AKS cluster in Germany ?

**Comment by JoeyC-Dev** [comment]
This question should not be under AKS scope if it comes backup for AKS (it will be under backup team if submitting service request). It is suggested to submit feature request to backup team because not sure if AKS PG will deal this. 

Try: https://feedback.azure.com/

**Comment by sjwaight** [comment]
Cross Region Restore for AKS will be available for Germany West Central in due course as the service rolls out to more regions.
