### ISSUE TITLE
[Question] Public network in Portal Public network access

### ISSUE THREAD

**Issue by jkroepke** [Azure/AKS#4220]
**Describe scenario**
Today, I found this new toggle on our Portal:

![Bildschirmfoto 2024-04-18 um 11 06 04](https://github.com/Azure/AKS/assets/1560587/8daa244e-8f57-4002-bc65-799a31b68022)

**Question**

What is this? Whats the different between Public network access and public access to API server?

I can't find nothing inside documentation.

**Comment by rouke-broersma** [comment]
The helptext seems to suggest that disabling public network access would disable the ARM endpoints as well as the kubernetes api server endpoint. This seems to suggest that you can then no longer execute certain actions through Bicep/Arm template and/or ARM API (cluster start/stop, manage node pool) unless you run the api calls from within an environment that has line of sight within the vnet. Clarification of this option would be great.

**Comment by JoeyC-Dev** [comment]
It does block my `kubectl` requests
```bash
joey [ ~ ]$ kubectl get node
E0507 08:43:12.651086    6055 memcache.go:265] couldn't get current server API group list: unknown
E0507 08:43:12.724378    6055 memcache.go:265] couldn't get current server API group list: unknown
E0507 08:43:12.797868    6055 memcache.go:265] couldn't get current server API group list: unknown
E0507 08:43:12.871379    6055 memcache.go:265] couldn't get current server API group list: unknown
E0507 08:43:12.944857    6055 memcache.go:265] couldn't get current server API group list: unknown
Error from server (Forbidden): unknown
```

But does not look like that it will block the new node pool actions via Azure portal:
![image](https://github.com/Azure/AKS/assets/142381267/6480be81-9138-468b-a417-f532c4915a42)
Tried `az-cli` but same:
```bash
Joey [ ~ ]$ az aks nodepool add -n another --cluster-name aks -g rG
 | Running ..
```
![image](https://github.com/Azure/AKS/assets/142381267/09ff0d31-9836-49a5-a8d6-a933d9628269)

It did not block stop cluster action too:
![image](https://github.com/Azure/AKS/assets/142381267/db5118ba-7449-4585-bd23-b7a3eb4c6cae)


Is this feature still under development, or am I understanding it wrong?

**Comment by dsanchor** [comment]
Same doubt. What is this "public network access" about?

**Comment by jkroepke** [comment]
Thanks for the info.

**Comment by jkroepke** [comment]
Thanks for the info.

**Comment by jkroepke** [comment]
Thanks for the info, bot

**Comment by jkroepke** [comment]
Thanks for the info, bot
