### ISSUE TITLE
[Question] Why is Version 1.73.3 patches not supported anymore

### ISSUE THREAD

**Issue by fadarboye** [Azure/AKS#4226]
**Describe scenario**
#  Why is Version 1.73.3 patches not supported anymore

**Question**
I notice cluster version `1.73.3` patches are not supported, is there a reason for this even does the End life of the version 1.27 is still in July.

**Comment by philwelz** [comment]
I think you are referring to  `1.27.3` or?  Currently patch levels `1.27.7` and `1.27.9` are supported. You can check this for your region with:

`az aks get-versions -o table --location westeurope`

Generally AKS trying that users are running the latest patch versions that include fixes for security vulnerabilities or major bugs to ensure full support. This is documented [here](https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#kubernetes-versions). 

I hope this answers your questions.
