### ISSUE TITLE
Could not find dashboard pod - After cluster creation

### ISSUE THREAD

**Issue by ErickWendel** [Azure/AKS#423]
Today I saw my cluster, and when I run `kubectl get pods` some pods has a `Unknown` Status, so I try to delete all pods to automatic recriation. In another forums, I found a solution to delete some kube-system namespace pods and try again. I do, the status of pods was fix, but the pods termination never clean form `get pods` list. I'm deleting my old cluster and recreating, but when I try, the Kubectl Server not is ok, following steps below

 ```sh
az aks create -g k8s-curso --name k8s-cluster\                      
    --dns-name-prefix k8s-cluster  --node-count 2 --node-vm-size Standard_A2

az aks get-credentials --resource-group k8s-curso --name k8s-cluster

az aks browse --resource-group k8s-curso --name k8s-cluster

Merged "k8s-cluster" as current context in /tmp/tmpynizckv9
The connection to the server k8s-cluster-b7c0ea14.hcp.eastus.azmk8s.io:443 was refused - did you specify the right host or port?
Could not find dashboard pod: Command '['kubectl', 'get', 'pods', '--kubeconfig', '/tmp/tmpynizckv9', '--namespace', 'kube-system', '--output', 'name', '--selector', 'k8s-app=kubernetes-dashboard']' returned non-zero exit status 1.

```
My kubectl version is 

```sh
kubectl version --short
Client Version: v1.10.4
The connection to the server k8s-cluster-b7c0ea14.hcp.eastus.azmk8s.io:443 was refused - did you specify the right host or port?
```
Linux Mint
x86_64

**Comment by sauryadas** [comment]
Can you please try a size with >4gb RAM?  Like A3 or D2V2

**Comment by ErickWendel** [comment]
that's a strange behavior. I'm try now on MacBook (the same cluster that I recreate) and works fine, only Linux that thing happens

**Comment by sauryadas** [comment]
Closing as this is resolved. Let me know if you see further issues
