### ISSUE TITLE
Setting a default container registry and disabling access to hub.docker.com

### ISSUE THREAD

**Issue by hibri** [Azure/AKS#424]
Hi,
Is there a way in K8S or AKS to set a default container registry to an ACR that has been pre-created. From a security perspective I want to restrict the cluster to only images hosted on a specific ACR. 

Are there plans to add VNet Service Endpoints to ACR?

**Comment by andresguisado** [comment]
Related to https://github.com/Azure/AKS/issues/316

**Comment by seanmck** [comment]
Duplicate of #316. 

Also, please file feature requests at https://aka.ms/aks/feedback so we can prioritize them.
