### ISSUE TITLE
Cluster showing error  Multi-factor Authentication 

### ISSUE THREAD

**Issue by fadarboye** [Azure/AKS#4241]
**Describe your scenario**

I noticed Cluster showing is throwing alert error  Multi-factor Authentication - China - investigating. 

Is this already a known issue or a bug?

![Screenshot 2024-04-25 090531](https://github.com/Azure/AKS/assets/130584349/8588ec8f-176e-40f7-a4ed-5164615b9d3e)

**Comment by JoeyC-Dev** [comment]
This error is not related to AKS at all. 
If you clicked the [link](https://app.azure.com/h/FTMK-LZZ/606ce8), you will find out this is an Entra thing. Not AKS thing.
