### ISSUE TITLE
[BUG] "null collection frequency" if setting log analytics workspace ID during AKS creation

### ISSUE THREAD

**Issue by JoeyC-Dev** [Azure/AKS#4245]
**Describe the bug**
If binding existing log analytics workspace for container insight during AKS creation, the collection frequency will be present as `null`.

**To Reproduce**
```
location=switzerlandnorth
rG=my-ci-bug-10575
aks=my-ci-bug-10575
logAnalyticsWorkspace=my-aks-law-10575

# Basic set-up
az group create -n ${rG} -l ${location} -o none

az monitor log-analytics workspace create -n ${logAnalyticsWorkspace} -g ${rG}
logAnalyticsWorkspace_resId=$(az resource show -n ${logAnalyticsWorkspace} -g ${rG} --namespace Microsoft.OperationalInsights --resource-type workspaces --query id -o tsv)

# Wait 15 seconds for logAnalyticsWorkspace being provisioned.
sleep 15; az aks create -n ${aks} -g ${rG} --node-vm-size Standard_A4_v2 --node-count 2 \
-a monitoring --workspace-resource-id ${logAnalyticsWorkspace_resId} --enable-syslog \
--no-ssh-key

# Clean resource
az group delete -n ${rG}
```

**Expected behavior**
The value for "collection frequency" and "Namespace Filtering" should be present. 

**Screenshots**
The screenshot is based on the result of the above script.
![image](https://github.com/Azure/AKS/assets/142381267/81a3d62c-efea-4300-a5e6-8516270ac1b4)
![image](https://github.com/Azure/AKS/assets/142381267/03729ec7-991c-4a2e-a80d-90077406de45)

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22]: 2.59.0
 - Kubernetes version [e.g. 1.24.3]: 1.28.5
 - CLI Extension version [e.g. 1.7.5] if applicable: N/A
 - Browser [e.g. chrome, safari] is applicable: Cloud Shell

**Additional context**
Not sure if I should submit this to `azure-cli` repo. It's hard for me to scope the root cause.

**Comment by vdiec** [comment]
@JoeyC-Dev this issue has been fixed and will be rolled out by the end of the week!
