### ISSUE TITLE
Nodes are at NotReady State due to Network Plugin CNI (Azure CNI)

### ISSUE THREAD

**Issue by vishnoisuresh** [Azure/AKS#425]
Hi Guys, 

Initially, I had 3 Nodes Cluster then I scaled it down to 1. Next day When I tried to scale up the cluster with Nodes 4.  Added nodes are in **NotReady State** due to cni config uninitialised.

Here is the information

`AKS Version = v1.9.6   `

> **Kubectl get nodes** 

```
aks-agentpool-30381032-0   Ready      agent     6d        v1.9.6
aks-agentpool-30381032-1   NotReady   agent     22h       v1.9.6
aks-agentpool-30381032-2   NotReady   agent     22h       v1.9.6
aks-agentpool-30381032-3   NotReady   agent     1h        v1.9.6
```
    

> **kubectl describe nodes aks-agentpool-30381032-1**

Here are conditions from above command 

Conditions:
```
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------

  NetworkUnavailable   False   Tue, 12 Jun 2018 12:21:34 +0200   Tue, 12 Jun 2018 12:21:34 +0200   RouteCreated                 RouteController created a route
  OutOfDisk            False   Wed, 13 Jun 2018 10:57:39 +0200   Tue, 12 Jun 2018 12:21:16 +0200   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure       False   Wed, 13 Jun 2018 10:57:39 +0200   Tue, 12 Jun 2018 12:21:16 +0200   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Wed, 13 Jun 2018 10:57:39 +0200   Tue, 12 Jun 2018 12:21:16 +0200   KubeletHasNoDiskPressure     kubelet has no disk pressure
  Ready                False   Wed, 13 Jun 2018 10:57:39 +0200   Tue, 12 Jun 2018 12:21:16 +0200   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized


```

After that I **sshed** into the new nodes and found out there are neither **configuration file** `/etc/cni/net.d` nor  **log file** `/var/log/azure-vnet.log`

How can I debug it? 
Thanks

**Comment by vishnoisuresh** [comment]
**Additional** Information.

In Scaled nodes (NotReady State) there are no following binaries at `/opt/cni/bin`

- azure-vnet 
-  azure-vnet-ipam

**Comment by jackfrancis** [comment]
Hi @vishnoisuresh, did your scale up operation (`az aks scale` etc...) to 4 nodes succeed? The symptom you are describing suggests a cluster node that wasn't successfully installed, so I would expect you would have received an error response from the scale attempt.

**Comment by mboersma** [comment]
@vishnoisuresh it sounds like the new cluster didn't exhibit this behavior, and the old one isn't around to look at. I'm going to close this, but if you see it again could you please send details with subscription ID, resource group name, cluster name, and Azure region to aks-help@service.microsoft.com so we can investigate further?
