### ISSUE TITLE
Error: "powershell is not recognized as internal or external command" in windows2022 node pool OS (AKS)

### ISSUE THREAD

**Issue by mefarazahmad** [Azure/AKS#4250]
**Describe the bug**
When using node pool OS as Windows2022 and docker image mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2022, getting "powershell is not recognized as internal or external command" but when changes to windows2019 as node pool OS and image as "mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019" it works

**To Reproduce**
1. I am first building the image using command
`az acr build --image devops/windows:v0.0.1 --registry registryName --platform windows .`
Use below docker file

```
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2022

RUN powershell  -Command Set-ExecutionPolicy Bypass -Scope Process -Force; `
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

RUN powershell  -Command "Install-PackageProvider -Name NuGet -Force -Scope AllUsers"

RUN powershell  -Command "Install-Module -Name SqlServer -Force -Scope AllUsers"

RUN Setx /M PATH "\"C:\Program Files\Microsoft SQL Server\160\DAC\bin";$env:PATH\""

WORKDIR /azp/

COPY ./start.ps1 ./

CMD powershell .\start.ps1
```
and then using terraform module to create windows pods using the image build from above step

**Expected behavior**
Kubernetes pods must run without any errors.

**Screenshots**
<img width="752" alt="image" src="https://github.com/Azure/AKS/assets/147005938/16e27a24-0f01-4cf6-8623-48e88d8801c8">
<img width="932" alt="image" src="https://github.com/Azure/AKS/assets/147005938/d9f745ce-222d-482b-8699-23f0b5bd417a">

**Environment (please complete the following information):**
 - Kubernetes version 1.28.5

**Comment by AbelHu** [comment]
@mefarazahmad Please check the $env:path and powershell version and share the results of both ws2019 and ws2022 environments. 
```powershell
echo $PSVersionTable.PSVersion
echo $env:PATH
```
