### ISSUE TITLE
[Question] PERF: Why cpuUsageNanoCores values of K8SContainers doesn't add up to the value of K8SNode?

### ISSUE THREAD

**Issue by maxkt** [Azure/AKS#4253]
**Describe scenario**
We own a system that executes and evaluates code in different languages (C#, C, C++, Java and 10+ more) in real time. This system is hosted in a set of Linux-based node pools in AKS in Azure.

Average CPU consumption of the working system is 20-30% with occasional spikes up to 75-90% that last seconds or dozens of seconds. But lately we often have situations when all nodes in a given node pool are under 100% CPU load that lasts 10, 30, sometimes 60 minutes. The spikes start roughly at the same time on all nodes in the pool.

When I look into Perf logs for the cpuUsageNanoCores, I see that the distribution of containers-main CPU consumers stays mostly the same (microsoft-defender-low-level-collector, ama-logs and node-driver-registrar are always on top followed by our own container) even during the 100% CPU spikes.

But the cpuUsageNanoCores value K8SNode is actually 100% loaded during the spikes. But the cpuUsageNanoCores  values of K8SContainers  don't add up. 

![image](https://github.com/Azure/AKS/assets/123380548/b287a024-d126-4927-91ca-44bab0684948)

**Question**
Why cpuUsageNanoCores values of K8SContainers doesn't add up to the value of K8SNode?
How do I debug 100% CPU spikes within my cluster if PERF table seems to be hiding the main CPU consumer? It doesn't show the consumer that actually constitutes the spike.

**Comment by maxkt** [comment]
Will there be any response regarding this ticket?

**Comment by maxkt** [comment]
A comment to postpone deletion of this ticket.

**Comment by ysabih2** [comment]
Commenting to prevent the issue from being closed.

**Comment by ganga1980** [comment]
@ysabih2 - cpuUsageNanoCores value K8SNode is all of the up node including containers and non-containerized processes where as the  cpuUsageNanoCores value K8SContainer is just for the containers.  The value of cpuUsageNanoCores value K8SNode  will be higher than cpuUsageNanoCores value K8SContainer since it constitutes the processes running on the node. You would need to look at the processes on the node to figure out what processes on the node contributing to high CPU usage.

**Comment by maxkt** [comment]
> How do I debug 100% CPU spikes within my cluster if PERF table seems to be hiding the main CPU consumer? It doesn't show the consumer that actually constitutes the spike.

Thanks for your response.
I'd like to clarify some things.

So how do we look at the processes on a node using AKS logging capabilities? Is there a log or metric being tracked for this? How do we see historical data for it?

Or is it only possible via accessing VMSS directly or checking VMSS logs - all outside of AKS context.

**Comment by ysabih2** [comment]
Commenting to keep issue from being closed. The question in https://github.com/Azure/AKS/issues/4253#issuecomment-2222935793 is still not answered.

**Comment by maxkt** [comment]
A comment to postpone deletion of this ticket.
