### ISSUE TITLE
[BUG] New Nodepools don't report any node level metrics in Prometheus/Grafana

### ISSUE THREAD

**Issue by McGregsen** [Azure/AKS#4257]
**Describe the bug**
When adding a new nodepool to an existing aks cluster the new nodes don't report any node level metrics to the connected prometheus/grafana instance (Grafana and Prometheus managed by azure).

Existing nodes in other nodepools as well as newly created nodes in existing nodepools (autoscaling) continue to report metrics.

When connecting directly to an affected node we see that the node-exporter binary is missing which seems to be connected to the AKSLinuxExtension (Compute.AKS.Linux.AKSNode) not being installed for the new vmss belonging to the new nodepool.

Quickly scanning the install log for the node does not show any obvious errors but also does not mention the AKSLinuxExtension extension. Other extensions (e.g. AKSLinuxBilling) are installed correctly.

**To Reproduce**
1. create a new nodepool in an existing cluster using az aks add nodepool ....
2. check grafana dashboard to see if node metrics are present for nodes from the new nodepool

**Environment (please complete the following information):**
 - Kubernetes version 1.29.2
 - VM Image: AKSUbuntu-2204gen2containerd-202404.09.0
 - VM SKU: Standard_E8ads_v5

**Comment by McGregsen** [comment]
Hello,
thanks for your reply.

No I don't think it is a timing issue. The nodepool was created >2 days ago. We also temporarily set the scrape interval for node metrics fairly low to see immediate results. When creating new nodes in an existing nodepools they show up within minutes.

Also when connecting directly to any of the prometheus pods running on the affected nodes through port forwarding and looking at the discovered targets we see that the node exporter is being reported as down which is understandable because the node-exporter binary is missing due to the extension not being installed.

**Comment by aritraghosh** [comment]
@McGregsen Thanks for reporting the issue, we can investigate if/why the node exporter binary is missing. If you are still experiencing the issue, can you create a support case with the cluster details. Please share the support case for us to track

**Comment by McGregsen** [comment]
@aritraghosh 
Thanks for your reply. We have opened a support case (2405060050003168). The responsible engineer (from the vmss/vm team) has already involved somebdoy from the aks team. So I am waiting to hear back from them.

**Comment by McGregsen** [comment]
The issue has been solved with the help of support.
