### ISSUE TITLE
Missing ClusterRole

### ISSUE THREAD

**Issue by ChingizMard** [Azure/AKS#426]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
```
kubectl version --client --short
Client Version: v1.9.2
```

**What happened**:
I was performing the `istio0.8` installation with RBAC enabled but it failed with the following error:
```
ruleResolutionErrors=[clusterroles.rbac.authorization.k8s.io "cluster-admin" not found]
```
If I run `kubectl get clusterroles --all-namespaces` nothing is there.

**What you expected to happen**:
I was expecting cluster to have these roles by default, since that is what this [link](https://docs.microsoft.com/en-us/azure/aks/intro-kubernetes#identity-and-security-management ) states.

**How to reproduce it** (as minimally and precisely as possible):
Inside your cluster run:
```
$ helm install install/kubernetes/helm/istio --name istio --namespace istio-system
```

I am pretty sure any helm installation that requires RBAC will fail.

**Comment by Vlatombe** [comment]
Create the cluster with `--enable-rbac`. It's not on by default.

**Comment by andrew-dinunzio** [comment]
Is there an option to enable RBAC from the Portal? I ran into this issue too assuming it'd be enabled by default.

**Comment by ChingizMard** [comment]
That did help, but from the link I have mentioned I made an assumption it was enabled be default. This [link](https://docs.microsoft.com/en-us/azure/aks/faq#does-aks-support-kubernetes-role-based-access-control-rbac) says that is not even supported. Getting the documentation up to date, would be nice in my opinion.
