### ISSUE TITLE
[Feedback] Ubuntu vulnerability USN-6742-2, USN-6754-1 and USN-6737-1

### ISSUE THREAD

**Issue by JohnTangZX** [Azure/AKS#4273]
**Describe your scenario**
The vulnerability USN-6742-2, USN-6754-1 and USN-6737-1 are affecting ubuntu 22.04, the latest node image AKSUbuntu-2204gen2containerd-202404.16.0 does not include the fix.

[USN-6737-1: GNU C Library vulnerability | Ubuntu security notices | Ubuntu](https://ubuntu.com/security/notices/USN-6737-1)

[USN-6742-2: Linux kernel vulnerabilities | Ubuntu security notices | Ubuntu](https://ubuntu.com/security/notices/USN-6742-2)

[USN-6754-1: nghttp2 vulnerabilities | Ubuntu security notices | Ubuntu](https://ubuntu.com/security/notices/USN-6754-1)

**Feedback**
Please provide the node image which includes the fixes as soon as possible. The applications pods are in risk!

**Comment by JoeyC-Dev** [comment]
It looks like they are being addressed in the latest version of image:
https://github.com/Azure/AgentBaker/blob/master/vhdbuilder/release-notes/AKSUbuntu/gen2/2204containerd/202405.20.0.txt
