### ISSUE TITLE
[BUG] Azure Blob cannot mount folder to AKS pod

### ISSUE THREAD

**Issue by win5923** [Azure/AKS#4274]
**Describe the bug**
When using PVC (Persistent Volume Claim) to bind Azure Blob, I noticed that only files in the current directory are mounted into the pod, while folders are not.

**Expected behavior**
The data inside the folder should also be mountable into the pod.

**Screenshots**
Azure blob:
![image](https://github.com/Azure/AKS/assets/56353753/0a717a3e-faca-4a12-a715-4a1085364eea)

pod:
![image](https://github.com/Azure/AKS/assets/56353753/b19745f3-6b06-440b-80da-99e8d6a32b6a)

**Environment (please complete the following information):**
 - Kubernetes version: 1.28.5

**Additional context**
azure storage account information:
![image](https://github.com/Azure/AKS/assets/56353753/81e9759b-a29c-4c65-ae4c-88e44ff8c8c2)

**Comment by andyzhangx** [comment]
https://learn.microsoft.com/en-us/azure/aks/azure-csi-blob-storage-provision?tabs=mount-nfs%2Csecret#before-you-begin

To support an [Azure DataLake Gen2 storage account](https://learn.microsoft.com/en-us/azure/storage/blobs/upgrade-to-data-lake-storage-gen2-how-to) when using blobfuse mount, you'll need to do the following:

To create an ADLS account using the driver in dynamic provisioning, specify isHnsEnabled: "true" in the storage class parameters.
To enable blobfuse access to an ADLS account in static provisioning, specify the mount option --use-adls=true in the persistent volume.
If you are going to enable a storage account with Hierarchical Namespace, existing persistent volumes should be remounted with --use-adls=true mount option.

**Comment by win5923** [comment]
Thank you, the issue has been resolved.
