### ISSUE TITLE
Ingress Controller with Private IP

### ISSUE THREAD

**Issue by VincentSurelle** [Azure/AKS#428]
Hi,

I'm facing issues configuring my AKS cluster's communications

For now I have :
 - Application Gateway (WAF) as Front-End
 - API Management for common auth...etc... (Receiving requests from App Gateway)
 - AKS Cluster (Will receive requests from API Management)

I tried three ways : 

|Documentation|Issue|
|---------------|------|
|https://docs.microsoft.com/en-us/azure/aks/http-application-routing|I don't want my containers to be exposed on public network. Have to set multiple IPs in my API Management service|
|https://docs.microsoft.com/en-us/azure/aks/internal-lb|I must create one private IP/container. Have to set multiple IPs in my API Management service|
|https://docs.microsoft.com/en-us/azure/aks/ingress| **Not far from best one**. But it only allow public IP. I only want private IP|

As I said. The last one is the better approach for me. But it lacks an private IP option. Any idea how can I do it ?

Thanks ?

**Comment by markusdresch** [comment]
add
```
   annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```
to your service metadata, keeping the LoadBalancer option. best to delete the service and recreate it with this annotation, as editing the service doesn't seem to update the ip. you'll end up with a private ip that can be accessed by the application gateway.

**Comment by Mumrau** [comment]
The last one is most likely the better approach by far. I'm personally using this a public static ip.

I never tried setting it up with a private IP, but the way I selected the IP was during helm installation of nginx-ingress, in which I passed --set controller.service.loadBalancerIP=my-ip-in-the-k8s-resource-group.
It might work out if you try this with a private IP that would be in the subnet in which AKS is located.

The above answer would work but wouldn't lock the IP, which I assume is a behavior you would enjoy.

(Another hackish way would be to do public IP and then secure it with network security group but definitely doesn't look that great.)

**Comment by VincentSurelle** [comment]
Thanks for your answers 👍 

@markusdresch I tried this way. But I only want one IP, not one per services (More Thant 50 to deploy). And as seen in #422 it's not possible.

@Mumrau Sadly, I does not work even with an IP in the subnet. It says that the IP can't be found. That's all I can get.

**Comment by Mumrau** [comment]
The IP needs to be in the MC_k8s_clusterName (the syntax might be wrong but you got me) by the way, I was tricked for a while with that.
Try that and it might hopefully work.
(What does the nginx ingress describe log shows by the way?)

**Comment by VincentSurelle** [comment]
Ok so I just tried the following :

- Creating a LoadBalancer in the ressource group MC_mycluster_westeurope with a Private IP
- Install ingress controller with the following command (IP is the on from LoadBalancer) `helm install stable/nginx-ingress --namespace kube-system --set rbac.create=false --set rbac.createRole=false --set rbac.createClusterRole=false --set controller.service.loadBalancerIP=10.240.0.6`

What I get is `Error creating load balancer (will retry): failed to ensure load balancer for service kube-system/coiling-umbrellabird-nginx-ingress-controller: user supplied IP Address 10.240.0.6 was not found`

My AKS VNET is configured like : 
10.0.0.0/8
And his subnet is :
10.240.0.0/16

**Comment by Mumrau** [comment]
The LoadBalancer creation doesn't seem necessary as kubernetes will create his own named "kubernetes" for me.
I tried on my side too, and the thing is I can only bind it to a IP Azure Resource, and you cannot create Private IP Resource, I sadly believe your way isn't doable.
I just noticed tho, that the loadbalancer itself has a private IP adress which I do believe you could use. Maybe you could use this and this alone. 
This kinda is my last resort :/

**Comment by VincentSurelle** [comment]
@Mumrau Thanks for trying 👍 

I just got something better ! 😄 

With this command : `helm install stable/nginx-ingress --namespace kube-system --set rbac.create=false --set rbac.createRole=false --set rbac.createClusterRole=false --set controller.service.externalIPs={"10.240.0.6"}`
I can now get my private IP without errors.....almost
It also create a public IP. For now only public IP works. But I think I'm not far from what I want :)
![capture d ecran 2018-06-15 a 11 48 21](https://user-images.githubusercontent.com/1504027/41462159-34fbd170-7092-11e8-9fc4-09fc643bd53c.png)

**Comment by Mumrau** [comment]
Oh that's true I like the idea of having external IPs without creating a load balancer resource.
It will most likely create a public ip alongside that, which you can just decide to totally ignore.

**Comment by VincentSurelle** [comment]
When trying to curl the private IP it says : `Failed to connect to 10.240.0.6 port 80: No route to host`. When I try to curl public I have the `404 - default backend` which is great.
I think I need to do something with the route table to get this in private ip. But my knowledge as coming to limits with this one.

**Comment by markusdresch** [comment]
you don't need that for every service, only for the ingress. azure web application gateway will see the private loadbalancer ip for your ingress.

**Comment by VincentSurelle** [comment]
Hi everyone ! 😃

I finally found the way to do what I wanted !

Finally it's a mix between this : https://docs.microsoft.com/en-us/azure/aks/internal-lb and this https://docs.microsoft.com/en-us/azure/aks/ingress

So finally the command to launch was : 

`helm install stable/nginx-ingress --namespace kube-system --name general-ingress --set rbac.create=false --set rbac.createRole=false --set rbac.createClusterRole=false --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"='"true"' --set controller.service.loadBalancerIP="10.240.0.60"`

This disabled the public IP creation and built a Internal-Loabalancer directly connected to the IngressController.

Now I just have only one IP to use with my API Magement solution fronting the Loadbalancer.

Thanks to all ! 👍

**Comment by sherpc** [comment]
@VincentSurelle , thank you very much for this solution. By the way, for me your command is failed, cause kubernetes set annotation about balancer-internal with quotes, like `"true"`, and controller doesn't recognize it.

My final command is `helm install stable/nginx-ingress -f ingress-values.yaml --namespace kube-system --name general-ingress` with `cat ingress-values.yaml`:

```
rbac:
  create: false
  createRole: false
  createClusterRole: false
controller:
  service:
    loadBalancerIP: 10.240.0.62
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```

**Comment by RossJayJones** [comment]
Apologies for the noob question, but I assume that the controller.service.loadBalancerIP value provided needs to be an available IP address on that subnet. Is that correct?

**Comment by RossJayJones** [comment]
Ok never mind. From https://docs.microsoft.com/en-us/azure/aks/internal-lb

_The specified IP address must reside in the same subnet as the AKS cluster and must not already be assigned to a resource._

So that answers it :)

**Comment by RossJayJones** [comment]
I am getting stuck when with trying to allocate the private IP

`Error creating load balancer (will retry): failed to ensure load balancer for service kube-system/loitering-emu-nginx-ingress-controller: user supplied IP Address 10.51.16.125 was not found in resource group <resource group name>`

Should I somehow be creating this IP before running this command?

**Comment by Mumrau** [comment]
@RossJayJones yes you need to create the IP Azure Resource and put it inside the resource groupe where your vms (nodes) are (usually MC_clustername_location (or something like that)).

**Comment by msdotnetclr** [comment]
@RossJayJones did you solve the problem? I am trying to do the same with the following command:

```bash
helm install stable/nginx-ingress --namespace kube-system --name my-ingress --set rbac.create=false --set rbac.createRole=false --set rbac.createClusterRole=false --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"='"true"' --set controller.service.loadBalancerIP="10.201.102.253"
```

and ended up getting "CreatingLoadBalancerFailed" state with message "Error creating load balancer (will retry): failed to ensure load balancer for service kube-system/my-ingress-nginx-ingress-controller: user supplied IP Address 10.201.102.253 was not found in resource group MC_RG_AKS_01_SRZ-AKS-01_eastus".

**Comment by abhiramani-iptiq** [comment]
@msdotnetclr  i am running into same issue where no LB get created.what command did you run to get above error message?

**Comment by Martin-Aulich** [comment]
> 
> 
> Hi everyone ! 😃
> 
> I finally found the way to do what I wanted !
> 
> Finally it's a mix between this : https://docs.microsoft.com/en-us/azure/aks/internal-lb and this https://docs.microsoft.com/en-us/azure/aks/ingress
> 
> So finally the command to launch was :
> 
> `helm install stable/nginx-ingress --namespace kube-system --name general-ingress --set rbac.create=false --set rbac.createRole=false --set rbac.createClusterRole=false --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"='"true"' --set controller.service.loadBalancerIP="10.240.0.60"`
> 
> This disabled the public IP creation and built a Internal-Loabalancer directly connected to the IngressController.
> 
> Now I just have only one IP to use with my API Magement solution fronting the Loadbalancer.
> 
> Thanks to all ! 👍

Hi, may I ask how your pods communicate to services outside of your vnet? Afaik AKS/K8S uses the public IP of a LoadBalancer as the source IP for connections made outside the cluster and this scenario only uses an internal LB. Do you need a second LB with a public IP or do you have a clue how to solve this?

Many thanks in advance, I'm currently wrapping my head around an AKS setup that fulfils the strict security guidelines of my company...

Cheers,
Martin

**Comment by chetanku** [comment]
> Hi everyone ! 😃
> 
> I finally found the way to do what I wanted !
> 
> Finally it's a mix between this : https://docs.microsoft.com/en-us/azure/aks/internal-lb and this https://docs.microsoft.com/en-us/azure/aks/ingress
> 
> So finally the command to launch was :
> 
> `helm install stable/nginx-ingress --namespace kube-system --name general-ingress --set rbac.create=false --set rbac.createRole=false --set rbac.createClusterRole=false --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"='"true"' --set controller.service.loadBalancerIP="10.240.0.60"`
> 
> This disabled the public IP creation and built a Internal-Loabalancer directly connected to the IngressController.
> 
> Now I just have only one IP to use with my API Magement solution fronting the Loadbalancer.
> 
> Thanks to all ! 👍

Hey with this, can you access your applications outside the pods? I am trying to restrict my website in internal network so we cant' access the application from the internet. Also, can we assign DNS to the private ip?

**Comment by markusdresch** [comment]
@chetanku yes, without `service.beta.kubernetes.io/azure-load-balancer-internal: "true"`annotation AKS generates a public IP and assigns it to the ingress service. with the annotation it generates an internal IP instead, so you can route to it through some other virtual network in azure, for example to use it as a backend to application gateway.

**Comment by chetanku** [comment]
@markusdresch  thank you. So once I get an internal ip, it will be accessible only in my vnet. how can i assign a dns to it?

**Comment by umeshpawaros** [comment]
Adding --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"='"true"' to below helm install command will create a internal load balancer and it will pick available IP from the private VNET from azure portal which used while creating aks cluster.

helm install stable/nginx-ingress --namespace ingress-basic --set controller.replicaCount=1 --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux 

So, final command will look like

helm install stable/nginx-ingress --namespace ingress-basic --set controller.replicaCount=1 --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux  --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"='"true"'

**Comment by idhruvs** [comment]
Update for whoever comes here searching for a resolution:
The following command worked for me:

`helm install stable/nginx-ingress --namespace kube-system --name eic-dev-team1 --set rbac.create=false --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"="true"`

PS: I had tried all the different commands mentioned in this thread and found out that the key is to set the annotation correctly.

PPS: I have run this command from a terminal on Windows machine.

**Comment by ShineSmile** [comment]
> Finally I got it with this ingress-values.yaml file called with :
> helm install stable/nginx-ingress --namespace kube-system --set controller.replicaCount=2 -f ingress-values.yaml
> 
> ```
> rbac:
>   create: false
>   createRole: false
>   createClusterRole: false
> controller:
>   service:
>     type: LoadBalancer
>     loadBalancerIP: 10.0.2.200
>     annotations:
>       service.beta.kubernetes.io/azure-load-balancer-internal: "true"
>   ports:
>   - port: 80
>   selector:
>     app: internal-app
> ```

Thanks for your scripts. 
In my case, I should delete rbac section to make sure aks have privilages to create load balancer in azure.
