### ISSUE TITLE
[Question] How to enable oidc with microsoft entra ID on aks and how to register an app for the same

### ISSUE THREAD

**Issue by ashu8912** [Azure/AKS#4285]
**Question**
I have an AKS cluster and a MicrosoftEntraID app I want my app as the oidc provider for my AKS cluster, How do i achieve it, I remember with AzureAD we could use the --enable-oidc-provider arg but I don't see docs for the same with Microsoft EntraID

**Comment by JoeyC-Dev** [comment]
Not exactly sure what you are referring to. Is it Microsoft Entra Workload ID: https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview

**Comment by ashu8912** [comment]
This is my usecase I have a EntraID app registered which is capable of generating oidc tokens, I want to use these tokens to allow users to access my AKS cluster, How do i let my AKS cluster enable as well as allow this app to generate oidc tokens which can be used by AKS to authenticate.

**Comment by oleksandr-shalbanov-fntext** [comment]
@ashu8912, were you able to find a solution for your case? Has the same problem here :(
