### ISSUE TITLE
[Question] How to renew disk csi driver credentials

### ISSUE THREAD

**Issue by sprayzcs** [Azure/AKS#4287]
**Describe scenario**

Yesterday we ran into an issue with the csi disk driver. It looks like the AccessToken has expired and has not been renewed. How can you trigger a renewal of the token? I tried restarting the driver (`kubectl rollout restart ds csi-azuredisk-node`), but it didn't help either. I had to restart the vmss of the AKS cluster to resolve the issue.

The error message:

```
Warning [namespace]: AttachVolume.Attach failed for volume "pvc-4eb0c15d-d2a3-426b-b3ad-499a79b17e48" : rpc error: code = NotFound desc = Volume not found, failed with error: GET http://localhost:7788/subscriptions/<subscription>/resourceGroups/<node resource group>/providers/Microsoft.Compute/disks/pvc-4eb0c15d-d2a3-426b-b3ad-499a79b17e48
--------------------------------------------------------------------------------
RESPONSE 401: 401 Unauthorized
ERROR CODE: ExpiredAuthenticationToken
--------------------------------------------------------------------------------
{
  "error": {
    "code": "ExpiredAuthenticationToken",
    "message": "The access token expiry UTC time '5/14/2024 5:35:57 AM' is earlier than current UTC time '5/14/2024 10:57:24 AM'."
  }
}
--------------------------------------------------------------------------------
```

The AKS cluster is running on version `1.29.2` and the csi disk driver is running on version `1.30.1`

**Question**

How to force a renewal of the csi driver access token?

**Comment by jkroepke** [comment]
Facing the same issue: https://github.com/vmware-tanzu/velero/issues/7796

It seems like the csi driver is not refreshing the token.

**Comment by christianjedroCDT** [comment]
This is actually breaking all of our PVCs right now

**Comment by andyzhangx** [comment]
we are fixing this issue in the backend, if you want to make it faster, just email me the aks cluster fqdn, I would fix it asap, thanks for the inconvenience.

**Comment by spbean75** [comment]
Is this issue solved? I am getting the same thing when my statefulset starts up and tries to mount a pv.                        
Warning  FailedAttachVolume  2m6s  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-7575b5d2-a100-4bfd-b89c-716580f39d02" : rpc error: code = NotFound desc = Volume not found, failed with error: GET http://localhost:7788/subscriptions/edited/resourceGroups/edited/providers/Microsoft.Compute/disks/pvc-<edited>
--------------------------------------------------------------------------------
RESPONSE 401: 401 Unauthorized
ERROR CODE: ExpiredAuthenticationToken

**Comment by andyzhangx** [comment]
the fix is rolling out,  if you want to make it faster, just email me the aks cluster fqdn, I would fix it asap, thanks for the inconvenience.

**Comment by romainourgorry** [comment]
Hello @andyzhangx,
I have the same, I just sent you an email to unblock me please
Cheers

**Comment by scheibling** [comment]
Sent you an email as well @andyzhangx, thanks, we appreciate you!

**Comment by orahbeeni** [comment]
Hi @andyzhangx 
I have mailed you as well.

**Comment by vibhor13** [comment]
Hi @andyzhangx , have mailed you . Thanks .

**Comment by andyzhangx** [comment]
the fix has been rolled out to all public regions, it may still take one day to reconcile the driver version in a few clusters to take effect, close this comment now, sorry for any inconvenience.
