### ISSUE TITLE
default storage ins't setup correctly for dynamic provisioning.

### ISSUE THREAD

**Issue by depohmel** [Azure/AKS#43]
I've deployed an AKS cluster in EastUS. 
And installed https://kubeapps.com/charts/stable/redis .

PVC is not getting bound.  
![image](https://user-images.githubusercontent.com/1631779/32917190-3ea57d80-cad3-11e7-82f2-d81842715492.png)

Based on 
![image](https://user-images.githubusercontent.com/1631779/32917231-5dfc0348-cad3-11e7-99f8-6d28f0abbd16.png)

even that cluster have 2 storageClasses: default and  managed-premium

You can not create PVC without spec.storageClassName. 

Right now PVC must have spec.storageClassName: default to provision PV.

**Comment by depohmel** [comment]
Based on  https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class
something isn't correct with  DefaultStorageClass admission plugin.

**Comment by blackbaud-brandonstirnaman** [comment]
Ugh. I just popped on and searched and didn't find someone logging this.. the fix included in my bug:
https://github.com/Azure/AKS/issues/48

**Comment by slack** [comment]
This was merged and deployed a few weeks ago, details in #48
