### ISSUE TITLE
AKS Cluster dont get public IP and couldnt scale

### ISSUE THREAD

**Issue by borstibacon** [Azure/AKS#430]
Hi together,

i´m new at AKS and interested to get in touch with the Service.
So sorry for maybe asking stupid questions.

When trying the quickstart tutorial (https://docs.microsoft.com/de-de/azure/aks/kubernetes-walkthrough-portal in the German Version) the provided Azure Voting Service (Manifest from the tutorial) dont get an public IP Adress. Status <pending> for more than one day.

Futhermore i cant scale the cluster over the prortal function. It throw following error: 
"SCALE NOT Failed to save container service 'AKSTest'. Error: Cidr is invalid"
When trying this over the Azure CLI, the scaling process runs, but the new node dont reach a ready status.

I recognized, that this is a issue when using the advanced networking option. 

More information about the Cluster: buildup yesterday
Version: 1.9.6, new Service Principal, 1 node from DS1 v2
Network: http enabled, network option "advanced", created new vnet and subnet, standard configuration of Kubernetes Service and Docker Bridge IP range 
monitoring enabled, created defualt log analytics workspace

Does anyone already get the same error and fixed it?

Regards

**Comment by sauryadas** [comment]
A fix for this was rolled out
Can you please try again?

**Comment by borstibacon** [comment]
Scaling works fine! Great. Thanks!

Do you have an idea for the public IP issue?

**Comment by sauryadas** [comment]
Can you delete all apps deployed and redeploy them ? You should get a public Ip . Let me know if that is not the case

Thanks
Saurya
________________________________

**Comment by borstibacon** [comment]
Hi!
Thank you for answering. 

I deleted the deployed apps with kubectl delete -f <service> and recreated with kubectl create -f <service>. 
After 15 minutes no external IP. Its still pending.

For another test i deployed a new AKS over the Portal:
new RG, V 1.9.6, Std DS1 v2, 1 Node, 
HTTP yes, advanced network config with new vnet and subnet, std docker bridge and kubernetes service,
Monitoring yes with ne LA/OMS workspace

Try again to deploy the service from the tutorial. 
No external IP.

Maybe I do something essential wrong....
But when I´m deploy the Cluster over the Portal, only with basic network configuration, it works fine. 
Do I have to change something in the .yaml? Change the name of the type from "LoadBalancer" to something else?

Thank you!

**Comment by StianOvrevage** [comment]
Similar to https://github.com/Azure/AKS/issues/443 ?

**Comment by sauryadas** [comment]
Question: Does your cluster SPN have contributor access to your subnet resource in the custom VNET

**Comment by borstibacon** [comment]
Sorry for answering that late. I was afk for holidays.

Thanks to @StianOvrevage  for the link.
I created the cluster again and than it worked fine!

Also thanks @sauryadas 
The SPN has the needed rights. So it seems that it was another problem. 

Thank to all for the support.
