### ISSUE TITLE
[Question] The next LTS release version

### ISSUE THREAD

**Issue by JoeyC-Dev** [Azure/AKS#4305]
**Describe scenario**
In the release note of ["2024-04-11"](https://github.com/Azure/AKS/releases/tag/2024-04-11), there is a statement: 
> Kubernetes version 1.32 is the next [Long Term Support Version](https://learn.microsoft.com/azure/aks/long-term-support) after 1.27. Customers will get a minimum 6 months of overlap between 1.27 LTS and 1.32 LTS versions to plan upgrades.
![image](https://github.com/Azure/AKS/assets/142381267/9fc724fc-a031-4dde-a382-f97798c6d36e)

But I found this commit which edit the next version out of the document: https://github.com/MicrosoftDocs/azure-docs/commit/47905f7467652d39d7c25d1fb1a2b68e29a4ff38#diff-6531fe675592d16a692f70921e85bc7c39c15bac596083fa34df81d9ba9f78b1R128

**Question**
Is the statement in the release note wrong? If so, can you please edit that part out of the release note so it won't cause misunderstanding?

**Comment by haitch** [comment]
We will announce the next version pretty soon.

**Comment by hariscats** [comment]
Any updates (now that 1.27 is just about to hit EOL)?

**Comment by haitch** [comment]
we called 1.30 as next LTS version, this is published here: https://github.com/Azure/AKS/releases/tag/2024-07-16
