### ISSUE TITLE
[BUG] Cluster is not starting due to plicy issue

### ISSUE THREAD

**Issue by manuexcd** [Azure/AKS#4308]
**Describe the bug**
Cluster is not starting due to plicy issue.

**To Reproduce**
1. Run command 'az aks update --name cluster-name'
2. (RequestDisallowedByPolicy) Preflight validation check for resource(s) for container service hic-aks-cls-dev-001 in resource group MC_hic-rsg-dev-001_hic-aks-cls-dev-001_westeurope failed. Message: Resource 'aks-hicaksdev001-22880171-vmss' was disallowed by policy.
3. I have checked the policy and when checking the assignment, I get an error.

**Expected behavior**
Cluster starting.

**Screenshots**
![image](https://github.com/Azure/AKS/assets/11410616/5d135509-8e8f-45b8-8500-9caf66f30c99)

**Environment (please complete the following information):**
 - Kubernetes version 1.27.7

**Additional context**
It happens in all suscriptions.

**Comment by JoeyC-Dev** [comment]
It is best for you to open a support ticket, as this is a highly non-reproducible issue outside your environment.
![image](https://github.com/Azure/AKS/assets/142381267/f393b6ea-bf0a-4ded-bcfa-83437b84ae63)

**Comment by AllenWen-at-Azure** [comment]
Hi @manuexcd did you file support ticket and get help from Microsoft support engineer? Does the issue still exist?
