### ISSUE TITLE
[Feedback] lstat /var/lib/kubelet/pods/9c7edeed-db1a-47d8-bf56-2295553a7b79/volumes/kubernetes.io~csi/pvc-d6e6360a-f58c-4079-bd7a-afc7ed5a657f/mount: host is down

### ISSUE THREAD

**Issue by mloskot** [Azure/AKS#4310]
**Describe your scenario**

I have been running a few AKS clusters for two years now. The clusters are dynamically provisioned with Persistent Volumes (PV) from Azure Files shares, from dedicated Azure Storage Account per cluster. 

Recently, in one of the clusters running Kubernetes 1.27.3 a few pods mysteriously lost connectivity with some PV-s mounted from the Azure Files shares.

The cause of the issue remains unknown. I can confirm that **no changes** to manifests of Kubernetes resources and no changes to Azure resources occurred prior to the loss of the PV-s connectivity.

Below, I collect all the information I managed gather:

### Pods

Each of the affected pods run single Linux container and Azure Files-based PV is mounted as `/mnt/data`.
After connecting to the container shell, commands like `ls /mnt` returned `/mnt/data: host is down`.

Attempt to delete pod in order to let its deployment recreate it led to Kubernetes `Warning` failure like this:

```
Error: failed to generate container "ca2bbfbd63..." spec: failed to generate spec: 
   failed to stat /var/lib/kubelet/pods/af93f940-b911-4b17-87d5-859dcd72b3ef/volumes/kubernetes.io~csi/example-pv-data/mount:
   stat  /var/lib/kubelet/pods/af93f940-b911-4b17-87d5-859dcd72b3ef/volumes/kubernetes.io~csi/example-pv-data/mount: 
   host is down
```

### `csi-azurefile-node-xxxxx` logs

[azurefile.log](https://github.com/Azure/AKS/files/15438273/azurefile.log) contains the CSI driver controller logs with plenty of `host is down` lines.

```
DRIVER INFORMATION:
-------------------
Build Date: "2024-04-20T03:14:57Z"
Compiler: gc
Driver Name: file.csi.azure.com
Driver Version: v1.28.10
Git Commit: 4d3b87a73534d96103abf642ce2ca54835aff766
Go Version: go1.22.1
Platform: linux/amd64
```

I also noticed, that version of 1.28.10 is later than 1.28.7 documented in the Azure docs
- https://github.com/MicrosoftDocs/azure-docs/issues/122703

so I suspect there have been updates to the driver - relevant to this issue or not.

### Azure Files share

The shares corresponding to the corrupted PV-s are fine. The data files remain accessible and readable.

### Solution

I managed to solve the problem with a workaround, that is, by requesting the Azure Storage to provision new Azure Files share. Then, I copied the data from the disconnected shares to the newly provisioned shares. Finally, I switched my pods to mount PV-s from the newly provisioned shares.

### Kubernetes version

My clusters run 1.27.3 but I noticed lowest 1.27 available is 1.27.7

![image](https://github.com/Azure/AKS/assets/80741/09341d94-a85c-4d35-9263-2a7c9fd10dd9)

Is it possible Kubernetes 1.27.3 or CSI drivers it uses are out of date and prone to such errors? 
However, I am planning to upgrade my clusters soon.

### References

I have found numerous resources on the `host is down` and Azure Files connectivity issues:

- failed to generate container https://containersolutions.github.io/runbooks/posts/kubernetes/create-container-error/
- https://github.com/kubernetes-csi/csi-driver-smb/issues/64
- https://github.com/kubernetes-csi/csi-driver-smb/issues/164
- https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/files/connectivity/files-troubleshoot-smb-connectivity?tabs=linux
- https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/storage/fail-to-mount-azure-file-share

Unfortunately, I failed to match any of those reports or troubleshooting guide to my problem in order to determine the cause of it.

**Feedback**

I'm posting my report above as a call for comments on what could possibly be the cause of the problem, how to investigate it, and how to avoid it in future. Is this an issue with configuration on my side? Is it possible it's an accident due to some Azure data movements/network updates that occurred behind the scene that fatally confused the Linux driver responsible for the network shares connectivity?

**Comment by mloskot** [comment]
Don't stale

**Comment by seifrajhi** [comment]
Hello @mloskot , I am facing the same issue currently, have you managed to solve it ?

**Comment by chlynott** [comment]
@seifrajhi we experienced this issue as well, upgrading the AKS version resolved the issue. The Kernel version on the node needs to be 5.15.0-1068 or higher, as that has the fix. Upgrading AKS will also deploy the newer kernel version.

**Comment by mloskot** [comment]
@seifrajhi What I did was 
1. Trigger provisioning of new Azure Files share, with new PVC
2. Used Azure Storage browser or Azure Storage Explorer to manually copy my data from the AF share giving "host is down" to the newly provisioned AF share.
3. Pointed my pods to mount the PV from the new AF share.
4. Deleted the AF share that was giving "host is down"

I also opened support ticket with Microsoft, but they were unable to diagnose the problem due to lack of logs from my infrastructure. Below, I copy answer from the support team:

```text
Where pods were unable to connect to Azure file share.
When attempting to connect from the pod, they received a "Host is Down" error.
Subsequently, you have created a new Azure file share and successfully connected it to new pods.

Unfortunately, not able to find any issue from his side and the Azure file was deleted and subsequently recreated,
which has prevented us from identifying any issues with the Azure file share.

I am currently unable to retrieve node kubelet logs older than 30 days from my end.
Could you please attempt to access and provide these logs from your side?
I will analyze the logs once you provide them.

Answer to the additional questions customer asked:

Q: Should I expect any issues if I statically provision [1] multiple pods with the same pre-existing Azure Files share for read-only access?

A: When it comes to provisioning storage volumes for multiple pods in Azure Kubernetes Service (AKS), you have a couple of options;

If you have a pre-existing Azure Files share, you can attach it to multiple pods.
This is supported, but it’s essential to ensure that your pods only require read-only access to the shared storage.

If your pods need read-write access, consider dynamic provisioning instead.

If read-only access suffices, using the existing share with static provisioning should work well. Otherwise, opt for dynamic provisioning with a PVC.
```

So, next time the "host is down" happens, it is important to keep the broken AF share and contact Microsoft support immediately.
