### ISSUE TITLE
[BUG] PV Stuck in Terminating AKS1.28 CSI Drivers 

### ISSUE THREAD

**Issue by EoinMan** [Azure/AKS#4316]
**Describe the bug**

On Upgrade of AKS to 1.28 we are seeing an issue with PV

1) Helm install of charts 
2) PODs, PV, PVC created bound 
3) Helm uninstall 
4) Everything gets deleted
5) PV Stuck in terminating state -- Error :: Warning  VolumeFailedDelete  30s   persistentvolume-controller  error getting deleter volume plugin for volume 'dev2n5-persistence-pv': no deletable volume plugin matched 

**To Reproduce**

1) Helm install of charts 
2) PODs, PV, PVC created bound 
3) Helm uninstall 
4) Everything gets deleted
5) PV Stuck in terminating state

**Expected behavior**
PV gets deleted too

**Screenshots**

**Environment (please complete the following information):**
 -  CLI Version [2.60
 - Kubernetes version 1.28

**Additional context**

Issue not seen on AKS 1.27*

**Comment by EoinMan** [comment]
Thank you this ticket being taken 

Just wondering have you seen anything 

Or need any more examples ? 

Thank you

**Comment by andyzhangx** [comment]
duplicated as https://github.com/kubernetes-sigs/blob-csi-driver/issues/1375
