### ISSUE TITLE
Support for Event Grid events

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/AKS#432]
Provide support for Event Grid events so that it provides integration points

First events that come to my mind:
- Deployment Created
- Deployment Succeeded
- Cluster Scaling Initiated
- Pod Scaling Initiated
- Pod Starting
- Pod Failed
- ...

**Comment by tomkerkhove** [comment]
Just FYI @banisadr

**Comment by seanmck** [comment]
Please add this to the feedback forum so we can prioritize it:

https://aka.ms/aks/feedback

**Comment by tomkerkhove** [comment]
Done - https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/35019439-support-for-event-grid-events
