### ISSUE TITLE
[BUG] Gateway API with ASM creates and invalid container configuration

### ISSUE THREAD

**Issue by arnaud-tincelin** [Azure/AKS#4322]
**Describe the bug**

In an AKS cluster with ASM enabled (istio), deploying a `kind: Gateway` resource will result in an invalid the istio proxy deployment as the container uses an invalid image name for the container.

**To Reproduce**

1. Deploy AKS with ASM

    ```sh
    az aks create --resource-group $RESOURCE_GROUP --name $AKS_NAME --location $LOCATION \
      --network-plugin azure --network-plugin-mode overlay --network-dataplane cilium \
      --enable-oidc-issuer --enable-workload-identity \
      --vnet-subnet-id $NODE_SUBNET_ID \
      --enable-asm \
      -o none
    ```

1. Deploy the Gateway

    ```sh
    kubectl apply -f - <<EOF
    apiVersion: gateway.networking.k8s.io/v1
    kind: Gateway
    metadata:
      name: ingress
      labels:
        istio.io/rev: asm-1-21
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz/ready"
        service.beta.kubernetes.io/port_80_health-probe_protocol: http
        service.beta.kubernetes.io/port_80_health-probe_port: "15021"
    spec:
      gatewayClassName: istio
      listeners:
        - name: http
          protocol: HTTP
          port: 80
          allowedRoutes:
            namespaces:
              from: All
    EOF
    ```

1. Wait for the `ingress-istio` deployment to be created. The underlying container should not be able to start because it uses 
`image: mcr.microsoft.com/oss/istio/mcr.microsoft.com/oss/istio/proxyv2:1.21.2-distroless:1.21.2-distroless`
            
**Expected behavior**
The pod uses image `mcr.microsoft.com/oss/istio/proxyv2:1.21.2-distroless` and starts normally

**Screenshots**

![image](https://github.com/Azure/AKS/assets/25585350/a5a13a56-e6ce-4c6d-b45e-3ad640c7d534)

**Environment (please complete the following information):**
 -  CLI Version 2.59.0
 - Kubernetes version 1.28.9
 - ASM 1.20 or 1.21

**Additional context**

Workaround to make it work: manually deploy a pod with the correct configuration:
 - Fix image: `image: mcr.microsoft.com/oss/istio/proxyv2:1.21.2-distroless`
 - Setup labels so that it can be used by the service
   ```yaml
   labels:
     gateway.networking.k8s.io/gateway-name: ingress
  ```

**Comment by shashankbarsin** [comment]
@arnaud-tincelin - Gateway API is **not yet** supported under the Istio addon. There are currently a few gaps on health probes and upgrades that need to be addressed for the Istio Gateway API implementation on Azure. We are currently designing for this and a _best case tentative ETA_ is somewhere around August/September this year. We'll keep you posted on a more definitive ETA as we get closer to shipping this

**Comment by arnaud-tincelin** [comment]
thanks for the reply @shashankbarsin. I am looking forward to this feature.
Since the feature "works" with the workaround I provided, may be you could open it as a preview?

**Comment by bt701** [comment]
@shashankbarsin @arnaud-tincelin do we know if this was enabled? Lots of other tools are now using the gateway API, so it's making it a bit tricky to pick through whats supported and not.

I don't think the image name issue exists, but unsure if the label is required?

**Comment by geowalrus4gh** [comment]
These limitations prevents us from using istio service mesh with AKS.
