### ISSUE TITLE
[Feedback] Document Application Gateway For Containers ALB Controller supported annotations

### ISSUE THREAD

**Issue by bongi23** [Azure/AKS#4323]
**Describe your scenario**
In my company, we are using Application Gateway For Containers and ALB Controller to configure our AKS Ingress. We followed Azure tutorials ([one](https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/quickstart-deploy-application-gateway-for-containers-alb-controller?tabs=install-helm-windows) and [two](https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/quickstart-create-application-gateway-for-containers-byo-deployment?tabs=existing-vnet-subnet)) to deploy all the needed components. We choose the "bring your own deployment" strategy because we wanted a deterministic name for both the load balancer and the associated frontend.

After completing the deployment we followed the tutorials to set-up [SSL Offloading](https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/how-to-ssl-offloading-ingress-api?tabs=alb-managed) and [URL Redirect](https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/how-to-url-redirect-ingress-api?tabs=alb-managed). We noticed in the documentation it is used the annotation `alb.networking.azure.io/alb-name` to bind the Ingress with the Application Gateway for Containers. But we discovered this annotation makes sense only for the ALB Controller managed deployment strategy and not for the bring your own deployment one.

After ***a lot*** of trial and errors I randomly discovered that there exists the annotation `alb.networking.azure.io/alb-id` that binds an existing Application Gateway for containers with an ingress. It seems this annotation is not documented.

**Feedback**
Having a full documentation of what k8s annotations are supported would have saved me at least 1 day of work...

**Comment by PixelRobots** [comment]
Hey @JackStromberg is this something your team could look into?

**Comment by JackStromberg** [comment]
AGC has a total of 4 annotations with no intent to add additional like what AGIC had.  All feature configurations are intended to be defined in custom resources where possible.

The four annotations are:
alb.networking.azure.io/alb-namespace  <- only used to reference ApplicationLoadBalancer CR
alb.networking.azure.io/alb-name <- only used to reference ApplicationLoadBalancer CR
alb.networking.azure.io/alb-id <- only used in BYO strategy to reference existing AGC resource
alb.networking.azure.io/alb-ingress-extension <- only used when referencing an IngressExtension CR

As you follow documentation, we have tried to consistently document the article in either the context of BYO or Managed with the proper annotations to achieve the desired outcome.  Prior referenced docs also try to preselect the tabs so you don't context switch between BYO and Managed as well (i.e. this article links to a preselected BYO set of tabs in the how-to guides to keep the same intent: https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/quickstart-create-application-gateway-for-containers-byo-deploymen).

Do you have more details on the intent to mix and match managed with BYO?  It's not intended to mix those strategies.

Jack

**Comment by bongi23** [comment]
Hi Jack,

For some reasons tab preselect haven't worked for me. Now I see there is the possibility to switch between BYO and managed examples. Thank you!

Andrea.
