### ISSUE TITLE
Unable to install this add on AKS v1. 27.3

### ISSUE THREAD

**Issue by vivuu1989** [Azure/AKS#4329]
ques using Azure AKS v1. 27.3 private cluster and usin azure cli 2.3(.0.

When we are trying with the az aks command to install the cost analysys addon, the command syntax getting failed stating that the argument is wrong.. 

Any guidance please

**Comment by PixelRobots** [comment]
Hi, can you please share with us the commands you are using to enable the feature?

Also, can you confirm you cluster is on the standard or premium tier as the free tier is not supported.
