### ISSUE TITLE
Improved built-in support for application/pod alerts

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/AKS#433]
Would be great to have built-in support for alerts on an application/pod level.

This is already possible today via the `Number of pods by phase` metric but this is hidden in Azure Monitor.

Would be great to just have a metric `Failing Pods` that splits by pod.

Portal Experience:
![image](https://user-images.githubusercontent.com/4345663/41403159-7f438cce-6fc4-11e8-958d-22be892d00cc.png)

**Comment by sauryadas** [comment]
Thanks for the feedback . We will look into this feature request .

@keikhara Should this ask be a part of container monitoring?

**Comment by keikhara** [comment]
@sauryadas  This is something we are looking at and will be coming in few weeks time.

**Comment by tomkerkhove** [comment]
@jnoller can you elaborate why it got closed please?

**Comment by jnoller** [comment]
The issue is almost a year old, @keikhara ack'ed and noted it would come into the release of Azure Insights for Containers last year. I am working on cleaning up all 300+ stale issues on this repo to post a public roadmap

**Comment by vishiy** [comment]
@jnoller, @tomkerkhove  - We will have 'pod count' metric with the following dimensions very soon -
* controllerName
* namespace
* node
* phase 

We are working on making these metrics alertable as well. Is that what you are asking for ? Unfortunately we dont have pod names (yet) as it will cause increased cardinality issues. We plan to get there as well....

**Comment by tomkerkhove** [comment]
That will certainly be a great addition, thank you @vishiy!

In an **ideal** scenario we also have the name of the pod/deployment but we already have namespace which will work for now! Looking forward to having that one!

**Comment by PixelRobots** [comment]
Any further update on this? Will be good to alert when pods are in a failed state etc.

**Comment by jnoller** [comment]
@PixelRobots No, no updates. We will post here when we get the work completed

**Comment by DSalvigni** [comment]
Is there any news regarding this improvement??

**Comment by afrikaans** [comment]
Still no update on this one

**Comment by vishiy** [comment]
This is available for quite some time now, under 'Metrics' --> namespace=insights.container/pods;metric=podCount; split by (controllerName/Kubernetes namespace/node/phase)

![image](https://user-images.githubusercontent.com/10353076/64295201-9316df00-cf25-11e9-935c-adbe2f55a931.png)
