### ISSUE TITLE
How to enable backup for AKS 

### ISSUE THREAD

**Issue by vivuu1989** [Azure/AKS#4330]
We are using AKS Version V1. 27.3 private cluster and planning to introduce the best possible backup system  for Aks. We found that velero has wide features, but it's not ms supported. 

How we can have velero backup enabled on aks cluster

**Comment by JoeyC-Dev** [comment]
Have you tried: https://learn.microsoft.com/en-us/azure/aks/hybrid/backup-workload-cluster
