### ISSUE TITLE
AKS with istio service mesh

### ISSUE THREAD

**Issue by vivuu1989** [Azure/AKS#4331]
We are using aks version v1. 27.3 private cluster and currently we are using istio opensource version of 1.18.2. It seems now Microsoft is officially supports istio service mesh we are planning to enable this in our cluster. 

But going through the documents, we couldn't find the steps needed to enable the service mesh

**Comment by JoeyC-Dev** [comment]
Do you mean: https://learn.microsoft.com/en-us/azure/aks/istio-deploy-addon

**Comment by nshankar13** [comment]
@vivuu1989 @biefy tested this and validated that Istio add-on works on private clusters.
