### ISSUE TITLE
Network Policies in AKS

### ISSUE THREAD

**Issue by sharnath** [Azure/AKS#435]
We have hardened network policy requirements for certain group of K8S pods. Can I install AKS on multiple VNETs and attach it to a namescape? OR Does AKS support advanced network policies?

Example -  Stateful pods should not have an outbound connection, Some communication pods can make internet connections, some pods allow a peer to peer communication for replication across the region. 

How do we support these requirements with AKS?

**Comment by sauryadas** [comment]
How do you plan to apply network policies? An AKS cluster can be deployed in a single VNET/subnet only. Network policy support is planned  with Calico. You can use kube-router  today if you wish.

**Comment by sauryadas** [comment]
Couple of months hopefully

Thanks
Saurya
________________________________

**Comment by mjhoffman65** [comment]
Any update to the timeframe for Calico support with AKS?  It is our preferred network policy implementation

**Comment by sauryadas** [comment]
targeting q3 cy 2018

**Comment by sauryadas** [comment]
Yes the support is with advanced networking

Thanks
Saurya
________________________________

**Comment by suonto** [comment]
@sauryadas I'm using kubenet - calico, but it seems that NetworkPolicies have no effect. Are they supposed to work already?

**Comment by MCKLMT** [comment]
Could we have a clear status on this feature please?
It is possible to restrict the traffic between different namespaces on AKS? This blog post explains how to setup that with kube -router but you are telling it is not working yet with calico, correct? 
https://carlos.mendible.com/2018/07/19/at-last-network-policies-in-aks-with-kube-router/

Thanks

**Comment by suonto** [comment]
@MCKLMT just to be precise, currently AKS does not support calico network policy with kubenet (even though the docs say so). If you do not add it, the cluster creation command (arms template) outputs calico as the policy. However, it does not seem to be true, since any network policies I've created do not have any effect. But I guess it's coming...

**Comment by MCKLMT** [comment]
@sauryadas Could you give us more details about the support of network policies on AKS please?

**Comment by sauryadas** [comment]
@MCKLMT Need another 4-6 weeks for the network policy integration with Calico. Will post an update when it is ready

**Comment by MCKLMT** [comment]
And what about kube-router?

**Comment by sauryadas** [comment]
I believe kube-router should work but we havent tested it extensively.

**Comment by MCKLMT** [comment]
Some guys reported that the network policies on kube-router are not working properly.
@sauryadas Could you confirm that kube-router works as expected?

**Comment by dberuben** [comment]
@sauryadas Any update ?

**Comment by sauryadas** [comment]
End of Nov.. Apologies for the delay.

**Comment by gonarys** [comment]
@sauryadas We are at the end of the month. Any update ?

**Comment by flamingboo** [comment]
@sauryadas network policies still planned for end of nov? or any new dates?

**Comment by azurewraith** [comment]
@sauryadas -- we're now into December, any updates on the ETA for this?

**Comment by bramvdklinkenberg** [comment]
would be (more than) nice to see this in AKS before the end of the year.

**Comment by yves-vogl** [comment]
@sauryadas Can you give a feedback about the current state of implementation? We think to postpone implementing kube-router for isolation in favour of the officially supported feature.

**Comment by seanmck** [comment]
The feature is basically complete, but as we entering a holiday release freeze, it may not roll out until early January.

**Comment by badalk** [comment]
@seanmck thats not a good news :(. May we know whether this would be based on calico / kube-router?

Regards
Badal

**Comment by yves-vogl** [comment]
Hallo @seanmck,
thanks for your feedback. And also thanks for the great work you guys do.
I wish you happy holidays and will look eagerly forward to January.

@badalk Do you really think so? For me these are great news as it means that there's progress and open communication. @sauryadas has already given an answer to your question: it will be based on Calico and can be used with Advanced Networking.

**Comment by badalk** [comment]
@yves-vogl I did not mean that its a bad news for the community. In my context it is, as we have a release planned before holidays and was expecting this to be available anytime soon. 
@sauryadas and @seanmck my intent was not to put down the effort you guys put in in making aks and azure in general a better cloud platform. and I equally appreciate what you guys do

Have a great holiday all

**Comment by seanmck** [comment]
@badalk No worries. We certainly understand that it is frustrating when dates aren't hit. We will get this out as soon as we can.

**Comment by youenchene** [comment]
@seanmck any details on AKS update deployment strategy over the different regions?

**Comment by IgorRogDevPro** [comment]
@seanmck Sorry for possibly a stupid question, but are you looking forward to making calicoctl tool available for end users of AKS? I guess yes, since the users have access to K8S API in K8S, but would like to double check nevertheless.
Happy holidays!

**Comment by bcastilho90** [comment]
Hi there! Happy holidays! 

Any updates on when it will be available? So looking forward to have this available in AKS.

Thanks

**Comment by badalk** [comment]
> Some guys reported that the network policies on kube-router are not working properly.
> @sauryadas Could you confirm that kube-router works as expected?

I am facing the same issue, kube router deployed as daemonset does no seem to work very well with standard network policies. I am able to deny all traffic but If I allow traffic from other pods, it does not work

**Comment by erewok** [comment]
@seanmck, I too would like to know the status of the Calico rollout for AKS. We're planning to work on some projects that require Network Policies, and I'm not sure if I should shuffle our schedule around to delay these. 

I notice that the [roadmap page](https://azure.microsoft.com/en-us/updates/?product=kubernetes-service) lists this feature as "In Development" as of January 28th, but from your note above, I assumed it would be released around this time. 

Does "In Development" mean we can enable it with a feature flag (so we can continue our own development that relies on this) or does it mean that it will be released shortly?

**Comment by mbrancato** [comment]
For anyone watching, it looks like Calico is available **today** in 1.12.4, which you should see as an available version now in AKS. It is a preview feature and unsupported. This is mentioned in the new change log document: https://github.com/Azure/AKS/blob/master/CHANGELOG.md

I previously asked if it would support Azure CNI implying existing clusters https://github.com/Azure/AKS/issues/435#issuecomment-408881651, it doesn't look like that support exists yet. New clusters only with the Calico CNI.

**Comment by sauryadas** [comment]
And here is the official documentation 
https://docs.microsoft.com/en-us/azure/aks/use-network-policies

**Comment by bobhenkel** [comment]
How long will this be in preview? Looking at when it will be in a release state and ready for production use.

Thanks!

**Comment by feiskyer** [comment]
Already supported and preview flag removed, see the documentation at https://docs.microsoft.com/en-us/azure/aks/use-network-policies.

**Comment by sauryadas** [comment]
https://azure.microsoft.com/en-us/updates/user-defined-network-policy-in-azure-kubernetes-service-aks-is-now-available/
