### ISSUE TITLE
[Feature] Support global configurations of Istio resource demands in AKS Add-On

### ISSUE THREAD

**Issue by CelebrateVC** [Azure/AKS#4362]
**Is your feature request related to a problem? Please describe.**
By Default the resource demands of the Istio sidecar are a lot:
```yaml
requests:
  cpu: 100m
  memory: 128Mi
limits:
  cpu: "2"
  memory: 1Gi
```
per pod running the sidecar. It also could run afoul of a LimitRange `maxLimitRequestRatio` given the side car's ratio is 20x. Not to mention ResourceQuotas.

**Describe the solution you'd like**
It would be helpful to have some solution to control this default globally across the mesh.  

**Describe alternatives you've considered**
there are 3 places where this ratio can be see
* `IstioOperator`'s `.spec.values.global.proxy.resources`
   * Blocked by admission controller currently
* Helm Chart values `global.proxy.resources`
   * Because this is a plugin - helm is controlled by MSFT so we cannot set it here. 
* Pod level annotation `sidecar.istio.io/proxyCPULimit: XXXm`
   * my team enables developer self-service, this is our only option currently, however, it is not scalable to consult individual teams to add an annotation, and some canned solutions don't allow pod annotations

**Additional context**
OSM's blade had an `edit configuration` button, maybe this is the best path forward - opening up the values.yaml of the helm deployment to alteration 
![](https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/media/tutorial-arc-enabled-open-service-mesh/osm-portal-configuration.jpg)

**Comment by shashankbarsin** [comment]
@CelebrateVC - CPU/memory requests/limits defaults are currently common across all users of the addon based on the values we found to be the best default for most users. Can you create an Azure support request along with the values you are looking for [here](https://learn.microsoft.com/azure/aks/aks-support-help#create-an-azure-support-request) and we will follow up with you.

**Comment by dedo1911** [comment]
> [@CelebrateVC](https://github.com/CelebrateVC) - CPU/memory requests/limits defaults are currently common across all users of the addon based on the values we found to be the best default for most users. Can you create an Azure support request along with the values you are looking for [here](https://learn.microsoft.com/azure/aks/aks-support-help#create-an-azure-support-request) and we will follow up with you.

What really makes you think that a setting that works for someone, will work for everyone else?
Is this Microsoft, or a joke?
Please keep this issue open untill a proper configuration setting has been provided.
Applying Isitio configurations also gets reverted back because for some reason AKS keeps applying Helm values every 5 minutes - is etcd even fine with something like this?
![Image](https://github.com/user-attachments/assets/1dd29840-b801-40ab-873b-64fe9231546e)

Never heard of pushing new Helm values only when something changes?
