### ISSUE TITLE
HTTP Application Routing doesn't update DNS

### ISSUE THREAD

**Issue by FrodeHus** [Azure/AKS#437]
Using a RBAC-enabled AKS cluster with HTTP Application Routing enabled, no DNS records are created when adding annotation `kubernetes.io/ingress.class: addon-http-application-routing`.

This is because the nginx-ingress controller doesn't update the ingress status with the loadbalancer IP so that the external-dns service can pick it up.

If I kill the nginx-ingress controller pod, it will successfully pick up the ingress and update it accordingly and in turn trigger a DNS record creation as expected. This only works when the controller is starting - after its done starting up, it will go back to not updating new ingresses.

**Comment by carloreggiani** [comment]
I'm trying to install (by helm) Eclipse Che 6.6.2 on a "brand new" AKS cluster in the same configuration: I'm getting big problem with websocker communication with the workspaces. Could be the same source of problem related to nginx-ingress service?
I discovered thet the nginx-ingress service not start correctly after first cluster creation (https://github.com/MicrosoftDocs/azure-docs/issues/10192#issuecomment-397972884): I have to reboot agent machines to complete the nginx-ingress configuration.

**Comment by carloreggiani** [comment]
Here the error message in my Services -->addon-http-application-routing-nginx-ingress details (kubernetes dashboard):

`Error updating load balancer with new hosts [aks-agentpool-70456257-2 aks-agentpool-70456257-0 aks-agentpool-70456257-1]: [ensure(kube-system/addon-http-application-routing-nginx-ingress): lb(kubernetes) - failed to ensure host in pool: "network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"LinkedAuthorizationFailed\" Message=\"The client '66e46ae9-61bd-4420-84db-965260dc35e9' with object id '66e46ae9-61bd-4420-84db-965260dc35e9' has permission to perform action 'Microsoft.Network/networkInterfaces/write' on scope '/subscriptions/xxxxxxxx-aaaa-ssss-eeee-rrrrrrrrrrrrr/resourceGroups/MC_RG-yyy-MMMM-WE_k8svpncad_westeurope/providers/Microsoft.Network/networkInterfaces/aks-agentpool-70456257-nic-2'; however, it does not have permission to perform action 'Microsoft.Network/virtualNetworks/subnets/join/action' on the linked scope(s) '/subscriptions/xxxxxxxx-aaaa-ssss-eeee-rrrrrrrrrrrrr/resourceGroups/RG-yyy-MMMM-WE/providers/Microsoft.Network/virtualNetworks/VNet-yyy-MMMM-WE/subnets/SubNet-216'.\"", ensure(kube-system/addon-http-application-routing-nginx-ingress): lb(kubernetes) - failed to ensure host in pool: "network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"LinkedAuthorizationFailed\" Message=\"The client '66e46ae9-61bd-4420-84db-965260dc35e9' with object id '66e46ae9-61bd-4420-84db-965260dc35e9' has permission to perform action 'Microsoft.Network/networkInterfaces/write' on scope '/subscriptions/xxxxxxxx-aaaa-ssss-eeee-rrrrrrrrrrrrr/resourceGroups/MC_RG-yyy-MMMM-WE_k8svpncad_westeurope/providers/Microsoft.Network/networkInterfaces/aks-agentpool-70456257-nic-1'; however, it does not have permission to perform action 'Microsoft.Network/virtualNetworks/subnets/join/action' on the linked scope(s) '/subscriptions/xxxxxxxx-aaaa-ssss-eeee-rrrrrrrrrrrrr/resourceGroups/RG-yyy-MMMM-WE/providers/Microsoft.Network/virtualNetworks/VNet-yyy-MMMM-WE/subnets/SubNet-216'.\"", ensure(kube-system/addon-http-application-routing-nginx-ingress): lb(kubernetes) - failed to ensure host in pool: "network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"LinkedAuthorizationFailed\" Message=\"The client '66e46ae9-61bd-4420-84db-965260dc35e9' with object id '66e46ae9-61bd-4420-84db-965260dc35e9' has permission to perform action 'Microsoft.Network/networkInterfaces/write' on scope '/subscriptions/xxxxxxxx-aaaa-ssss-eeee-rrrrrrrrrrrrr/resourceGroups/MC_RG-yyy-MMMM-WE_k8svpncad_westeurope/providers/Microsoft.Network/networkInterfaces/aks-agentpool-70456257-nic-0'; however, it does not have permission to perform action 'Microsoft.Network/virtualNetworks/subnets/join/action' on the linked scope(s) '/subscriptions/xxxxxxxx-aaaa-ssss-eeee-rrrrrrrrrrrrr/resourceGroups/RG-yyy-MMMM-WE/providers/Microsoft.Network/virtualNetworks/VNet-yyy-MMMM-WE/subnets/SubNet-216'.\""] `

**Comment by carloreggiani** [comment]
I resolved yesterday the "it does not have permission to perform action 'Microsoft.Network/virtualNetworks/subnets/join/action' on the linked scope(s)" error thanks to https://github.com/Azure/AKS/issues/357 for LoadBalancer services.
Hope to solve also Ecplise Che ingress problem: I'll try next week.

**Comment by dave-hillier** [comment]
I have the same problem --Ingresses created 16 days ago work, today not

This isnt from today, but its all the log contains
```
time="2018-06-30T07:43:58Z" level=info msg="config: &{Master: KubeConfig: Sources:[service ingress] Namespace: AnnotationFilter:kubernetes.io/ingress.class=addon-http-application-routing FQDNTemplate: Compatibility: PublishInternal:false Provider:azure GoogleProject: DomainFilter:[xxxxxxxx.westeurope.aksapp.io] AWSZoneType: AzureConfigFile:/etc/kubernetes/azure.json AzureResourceGroup:MC_rezlynx-dev-2-rg_rezlynx-dev-2_westeurope CloudflareProxied:false InfobloxGridHost: InfobloxWapiPort:443 InfobloxWapiUsername:admin InfobloxWapiPassword: InfobloxWapiVersion:2.3.1 InfobloxSSLVerify:true InMemoryZones:[] Policy:sync Registry:txt TXTOwnerID:default TXTPrefix: Interval:3m0s Once:false DryRun:false LogFormat:text MetricsAddress::7979 LogLevel:info}" 
time="2018-06-30T07:43:58Z" level=info msg="Connected to cluster at https://10.18.0.1:443" 
time="2018-06-30T08:23:32Z" level=error msg="the server could not find the requested resource (get services)" 
time="2018-06-30T08:41:58Z" level=error msg="an error on the server ("<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.13.5</center>\r\n</body>\r\n</html>") has prevented the request from succeeding (get ingresses.extensions)" 
```

**Comment by yaakov-h** [comment]
After upgrading from Kubernetes 1.9 to 1.10 - which also spins up new nodes, drops the old ones, and thus recreates every single pod - HAR seems to be working again. My Ingresses now have IP addresses and DNS records are being created as expected.

**Comment by cmendible** [comment]
I'm also had trouble on July with a cluster with both RBAC and HTTP Application Routing enabled. K8s version is: 1.10.5

Running:

```
kubectl logs -f deploy/addon-http-application-routing-external-dns -n kube-system
```

showed a token related issue:

```
time="2018-07-18T22:00:39Z" level=error msg="azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxxx/resourceGroups/MC_akscfm_akscfm_westeurope/providers/Microsoft.Network/dnsZones?api-version=2016-04-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/xxxxxxx/oauth2/token?api-version=1.0: dial tcp: i/o timeout'"
```

Hope it helps...

**Comment by dave-hillier** [comment]
This has occurred again... I'm guessing this means I need to update my cluster

**Comment by rafalkasa** [comment]
Sometimes `addon-http-application-routing` stop updating the external-dns because of some errors or another issue with ingress-controller.

The solution that I have been found was to restart Pods in the `namespace=kube-system` order:

1. addon-http-application-routing-external-dns
2. addon-http-application-routing-default-http-backend
3. addon-http-application-routing-nginx-ingress-controller

For me, everything started working again and addon started updating DNS and assigns the external IP address.

**Comment by adamsem** [comment]
This is only a temporary solution, will failed again in some time. Are you using same vnet for AKS and other Rg?

**Comment by prochnowc** [comment]
This hits me also. We have automatic deploy/undeploy of a cluster for each pull request. After a few days external DNS updates silently stop working.

**Comment by jnoller** [comment]
@prochnowc I can not ask for the needed information here to help root-cause the issue. If you are still impacted by this please file and Azure technical support ticket, with the subscription ID, symptoms and link to this issue.

**Comment by dave-hillier** [comment]
@jnoller the first sentence of your response doesn't make sense. You can't ask?!? Why are you only asking the last person of a thread with eight others?

This is a pretty underwhelming response. It seems like when you internally upgrade the cluster, it breaks application routing. I stopped using the feature because of this unreliability; it seemed to break within 2 weeks.

**Comment by prochnowc** [comment]
New kubernetes version has been rolled out for AKS. I upgraded our cluster to 1.12.5 and now everything seems to work.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.

The original issue is almost a year old, and in order to properly diagnose this we need technical support ticket raised or we need a new issue filed here with generally applicable re-creation steps that expose the issue outside your specific production system/cluster/subscription (as we can not ask for that information here).
