### ISSUE TITLE
Aks cluster experiencing downtime while doing a aks version upgrade.

### ISSUE THREAD

**Issue by saksham99del** [Azure/AKS#4377]
**Describe scenario**
We are trying to upgrade our aks cluster from version 1.28 to 1.29.We had setup a readiness probe and updated our rolling update property 'maxUnavailable' to 1.But still as soon as our node pool starts upgrading we experience a downtime that says 503 service temporarily unavailable.We can see that our pods are getting terminated and new pods are being created during the time of upgrade and we have specified 'agentpool' to be our usernodepool.We also tried setting 'maxUnavailable' to 0 but to no avail.

**Question**
How can we avoid downtime in our application during aks cluster version upgrade?

**Comment by PixelRobots** [comment]
Are you also using pod disruption budgets?

**Comment by saksham99del** [comment]
Yes,We also tried testing with PDBs and there was no downtime experienced.Wondering if there is any way to ensure zero downtime without using pdbs?

**Comment by PixelRobots** [comment]
Pdbs are the way to go. But you also need to make sure your workload is spread over different nodes and also ensure your application is gracefully shutting down.
