### ISSUE TITLE
[Question] Azure Workload Identity add-on version upgrade

### ISSUE THREAD

**Issue by mikec-greene** [Azure/AKS#4381]
**Describe scenario**
We are currently running AKS 1.29.4 and can see that the image used by `azure-wi-webhook-controller-manager` is `mcr.microsoft.com/oss/azure/workload-identity/webhook:v1.2.2`

We are currently blocked from using Istio with native sidecar mode because of this issue, which has been resolved in workload-identity v1.3.0: https://github.com/Azure/azure-workload-identity/issues/1312

**Question**
Is it possible to get an ETA of when the add-on will be upgraded to v1.3.0?
Is there a way to specify the version used when enabling the add-on?

Many thanks

**Comment by shashankbarsin** [comment]
this gets addressed 1.3.0 release of azure workload identity. It's a part of [v20240627 release](https://github.com/Azure/AKS/releases/tag/2024-06-27) which is currently rolling out. It's progress can be monitored on [AKS-Release-Tracker](https://releases.aks.azure.com/).
