### ISSUE TITLE
Not able to add a new agent pool to existing managed cluster

### ISSUE THREAD

**Issue by krishkalai** [Azure/AKS#4383]
**Describe scenario**
Trying to add a new additional node pool to an existing managed cluster using Bicep template, but getting the below exception.
API version used: Microsoft.ContainerService/managedClusters@2023-07-02-preview

Error message:
"Preflight validation check for resource(s) for container service xxxxxx in resource group xxxxxx failed. Message: A new agent pool was introduced. Adding agent pools to an existing cluster is not allowed through managed cluster operations. For agent pool specific change, please use per agent pool operations: https://aka.ms/agent-pool-rest-api. Details: (Code: BadRequest)"

**Question**
Is this an expected outcome or do we need to move to a different API version?

**Comment by PixelRobots** [comment]
Hi. Can you share your bicep please?

Also it is best to keep the API as up to date as possible. But this does mean more work with keeping the bicep up to date also. 

Have you looked at the Azure verified modules?
