### ISSUE TITLE
[Question] Roles missing after upgrade to k8s 1.29 

### ISSUE THREAD

**Issue by Ismael-Pep** [Azure/AKS#4398]
**Describe scenario**
Hi!
We are upgrading from AKS  v1.28.5 to v1.29.4
We have multiple clusters and we noticed that the role field is empty in v1.29.4 when using `kubectl get nodes`
The missing labels are: 
  kubernetes.io/role 
  agentnode-role.kubernetes.io/agent
I haven´t found any reference to this roles in the 1.29 changelog https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.29.md and I only find errors or issues with this labels between the versions 1.15 and 1.16 
**Question**
¿Is this the expected behavior?
¿Wouldn´t this be a breaking change for those clients who could be using those labels?

**Comment by JoeyC-Dev** [comment]
Looks like they are in deprecated list long time ago:
https://learn.microsoft.com/en-us/azure/aks/use-labels#deprecated-labels

**Comment by Ismael-Pep** [comment]
Thanks you for the clarification!
