### ISSUE TITLE
TLS error after upgrade of Kubernetes version

### ISSUE THREAD

**Issue by ormico** [Azure/AKS#44]
I've had an aks cluster up for a few days, working my way through different tutorials.
Most things have been ok, until I ran the following
`PS> az aks upgrade -n xTestCluster -g xTestResourceGroup -k 1.8.1`
As soon as this finished, all kubectl commands now return "Unable to connect to the server: net/http: TLS handshake timeout"
running 
`PS> az aks show --name xTestCluster --resource-group xTestResourceGroup --output table`
says the upgrade succeeded.

I did notice that I put in 1.8.1 instead of 1.8.2 but I still would have expected it to work.

I ran az aks upgrade again passing in 1.8.2 but after that succeeded I still cannot connect.

I tried running get-credentials again, but that didn't help.
`PS> az aks get-credentials --resource-group=xTestResourceGroup --name=xTestCluster`

The website container I deployed earlier in my tests is still running, so the cluster is still up.

1. What is wrong with my cluster?
2. Is there any way to recover it other than deleting and starting over?
3. Are there any other tests I can run?

**Comment by sauryadas** [comment]
Was able to reproduce this. Thanks for reporting. We will take a look and get back

**Comment by slack** [comment]
We have found and fixed the bug, should be rolling out to production over the next few days.

**Comment by Plasma** [comment]
I also had this happen to me just now. This also seemed to take down my pods and the web app I had running stopped being accessible.

**Comment by kahootali** [comment]
Having the same issue but I didn't upgrade to 1.8.2, I am at kubernetes 1.8.1. 
Actually, I have two clusters, One East US and other Central US,
When I try kubectl get po in Ease US cluster I get following error
`Unable to connect to the server: net/http: TLS handshake timeout`
The central US worked fine till yesterday but today it is also giving same error.

**Comment by BaloMueller** [comment]
Same problem here! Any estimates when this problem will be solved?

**Comment by amanohar** [comment]
@kahootali regarding:
>The central US worked fine till yesterday but today it is also giving same error.
Can you share the resource group and resource name of the cluster experiencing this issue?

@BaloMueller, was the cluster accessible after create at first? Can you describe the symptom? Can you share the resource group and resource name of the cluster experiencing this issue?

**Comment by kahootali** [comment]
@amanohar I was previously working on Central US and this is the info about it,
`Resource Group: connect-container-istio2 Name: concnt-istio`
They are still showing the same error

But then I moved to West Europe on Wednesday 29 Nov, and it was working fine but today it has also stopped working...
`Resource Group: connectcontainers-aks-we  Name: connectcontainers-aks-we`

Both of these are giving same error
`Unable to connect to the server: net/http: TLS handshake timeout`

**Comment by BaloMueller** [comment]
@amanohar I had a Kubernetes Cluster running in West EU for a couple of days. Then made an upgrade to 1.8.2. After the successful upgrade, I wasn't able to connect to the kubernetes cluster using kubectl any more
`$ kubectl get pods
Unable to connect to the server: net/http: TLS handshake timeout`
And it is still not working.

**Comment by bramvdklinkenberg** [comment]
I had a 1.7.7 AKS cluster and tried to upgrade tot 1.8.1 but got thte error:
Deployment failed. Correlation ID: ebbb42af-2a6e-47d5-bc09-7d9eb1f22893. Operation failed with status: 200. Details: Resource state Failed.
When I do a get-versions I see that master and nodes have version 1.8.1 though.

So I tried upgrading to 1.8.2, but again got the same deployment failed error. Again with a get-versions it says version 1.8.2 voor masters and nodes, but when I do a list I see provisioning state is failed.

I can also not connect to the cluster, I get the error "Unable to connect to the server: net/http: TLS handshake timeout".

**Comment by patelrit** [comment]
I just created couple of clusters in eastus - one via CLI and another via web console.
Getting the TLS error when trying to get nodes

$ kubectl get nodes
Unable to connect to the server: net/http: TLS handshake timeout
