### ISSUE TITLE
Should I recreate my cluster now that AKS is GA?

### ISSUE THREAD

**Issue by derekperkins** [Azure/AKS#440]
There have been a few issues during the beta period where the only resolution was to recreate the cluster. I'm not currently having any problems with my cluster, but where we haven't promoted it to production yet, it would be easier for me to recreate it now. I would prefer to just let it keep running, but I also don't want to run into something down the road that isn't supported because I was an early adopter.

**Comment by necevil** [comment]
@derekperkins my thinking on this is that probably at least some of the issues you have been dealing with are related to the TLS Handshake problem that many of us have experienced (https://stackoverflow.com/questions/50726534/unable-to-connect-net-http-tls-handshake-timeout-why-cant-kubectl-connect).

I don't know what your application looks like, but from my perspective making it somewhat portable / re-produceable is a huge part of the advantage a managed Kubernetes environment like AKS provides.

Given that I have seen at least one post talking about similar issues over on GCP (https://stackoverflow.com/questions/47481022/tls-handshake-timeout-with-kubernetes-in-gke?rq=1) I have tried to fully document the commands and steps necessary to re-produce my cluster in addition to looking at ways to script the pieces that are time consuming.

That being said if your cluster is working with more complex authorization / IAM relationships that need to be created I would for sure try to figure out if creation / authorization of those service principals can be saved into a 'oh sh*t' script as a last resort.

Personally I am more worried about the steps necessary to Harden a cluster that's being used in production as mentioned over here: https://github.com/Azure/AKS/issues/367

Obviously any steps taken there would be required on subsequent Cluster re-deployment(s) that may or may not be required in the future.  The security configuration of a cluster moving to production does seem like a good community project to contribute to but I haven't dived too far into it as of yet.

Probably more than 0.02 cents from me but I have been considering how to handle this issue on my side over the last few days so figured I would chime in.

**Comment by sauryadas** [comment]
No you should not need to if you arent seeing any problems. It would be good to keep upgrading tot he latest kubernetes versions supported though.

**Comment by derekperkins** [comment]
Thanks. Upgrading to 1.10.3 now.
