### ISSUE TITLE
[BUG] Spot Instance backed Nodepools with EvictionPolicy set to Delete, now Stopping Instances instead of Deleting on Preemption

### ISSUE THREAD

**Issue by nebed** [Azure/AKS#4400]
**Describe the bug**
This started 2 days ago, when spot instances are preempted, even though the EvicitonPolicy is set to Delete, the backing instance in the VMSS is stopped not deleted, as a result, it lingers in the cluster in NotReady state and does not get removed for hours.
Also running the `kubectl delete node node_name` command does not delete the node in the vmss, so I assume this would be related.

**To Reproduce**
1. Configure Spot Instance backed nodepool in AKS with EvictionPolicy set to Delete
2. Wait for a node to be preempted
3. Check the node state - NotReady
4. Check the VMSS resource and view the state of the instance that was preempted it should be in the Stopped state

**Expected behavior**
When a Spot instance is preempted it should be drained and deleted, as has been the behavior for a long time.

**Screenshots**

**Environment (please complete the following information):**
 -  CLI Version: v1.27.4
 - Kubernetes version: v1.28.9

**Additional context**

**Comment by nebed** [comment]
fixed now

**Comment by nebed** [comment]
Microsoft ADO ticket: 77030.

**Comment by raneshiv** [comment]
> Microsoft ADO

Hi @nebed , Can you please post the link of mentioned Microsoft ticket. I want to check the resolution of the issue.

**Comment by nebed** [comment]
Hi @raneshiv this was an internal support ticket on Microsoft's side, it just got sent to me by an Azure support engineer

**Comment by raneshiv** [comment]
Hi @nebed , Can you please provide the detailed resolution provided by Microsoft.

**Comment by nebed** [comment]
@raneshiv They did not provide any, I will push for it today. but the issue just went away.

**Comment by camposdelima** [comment]
I saw the same thing start to happen in an AKS cluster about three weeks ago :')
