### ISSUE TITLE
Gatekeeper config file edit. 

### ISSUE THREAD

**Issue by barucijah** [Azure/AKS#4401]
**Describe scenario**
We have enabled the azure-policy plugin, which installs Gatekeeper to the cluster automatically. Our goal was to add a policy to enforce resource quotas in each namespace. We used the ResourceQuotas policy template from [this blog post](https://nunoadrego.com/posts/opa-gatekeeper-in-the-admission-controllers-world/). However, despite defining ResourceQuotas for all namespaces, we encountered errors across all namespaces.
Upon further investigation, I discovered that the Gatekeeper config file lacks the definition of ResourceQuotas in the syncOnly parameters, similar to what is described [here](https://github.com/nunoadrego/gatekeeper/blob/main/required-resourcequota/sync.yaml). I tried to locate a way to edit this config file, but since it is installed by the azure-policy addon, I couldn't find where to update it.

**Question**
Could this misconfigured config file be the main cause of my issue?
How can I edit the config file of the Gatekeeper? Is it hardcoded?
If yes, I would like to add Namespaces and ResourceQuotas in the syncOnly parameter.

**Comment by miwithro** [comment]
@fseldow @charleswool

**Comment by charleswool** [comment]
Due to performance and security concerns, syncing data is limited to builtins only right now unfortunately. We're eventually planning on opening it up to custom but no timeline for that.
