### ISSUE TITLE
[Question] AKS is masking the IP of calls to the NodeIP

### ISSUE THREAD

**Issue by martinjt** [Azure/AKS#4402]
**Describe scenario**
In the default OpenTelemetry Collector installs, the opentelemtry recommends using a DaemonSet with ports bound to the Node IP address. The pods for applications sending telemetry are then set to send their data to the NodeIP address on the relevant ports.

In this scenario, the telemetry makes it to the OpenTelemetry Collector, however, the inbound IP address is not that of the Pod.

Instead of using the Pod's IP, it seems to use an IP of perhaps some kind of proxy/NAT instead.

This causes issues with a specific component called the K8sattributesprocessor.  This component reads the inbound connection data and extracts the IP Address. It uses this IP address to get more information about the Pod. This isn't possible because the IP Address isn't exposed.

**Question**
This scenario works in all other clouds, but doesn't in AKS. I have done some research, and it has been suggested that this could be to do with the IP Masq service. However, I've reconfigured this to use `0.0.0.0/0` as the non-masquerade. I'm wondering whether this is some kind of invisible NAT that I'm seeing.

This is a very weird thing to happen in K8s, and seems non-standard. Can you explain what is causing the behaviour, and potentially how to rectify it?

**Comment by PixelRobots** [comment]
Maybe @paulgmiller might be able to help here.
