### ISSUE TITLE
[Feature] Allow CAS priority expander immediately fall back to other nodepool if the spot node cannot be created

### ISSUE THREAD

**Issue by JoeyC-Dev** [Azure/AKS#4405]
**Is your feature request related to a problem? Please describe.**
We have two spot nodepool that being set with different price and size, and want to make the fallback if one spot nodepool is not available.
For example: if the price is not available, we want to use another nodepool which did not use Spot feature to immediately deploy jobs.

However, after testing, it looks like no matter how I configure CAS, it will take 20 mins for failover.

![image](https://github.com/user-attachments/assets/47b3ed01-415b-4ab0-a849-228054e03f85)

![image](https://github.com/user-attachments/assets/d5c632f3-b981-4fdc-a1a2-646c2475126b)

AKS CAS profile: 
`scan-interval=10s,scale-down-delay-after-add=1m,scale-down-unneeded-time=1m,scale-down-unready-time=5m,expander=priority`

CAS priority expander profile:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    10: 
      - caspoolgood
    50: 
      - caspoolbad
```

Nodepools:
```bash
# Remeber to change the price by yourself
az aks nodepool add --cluster-name ${aks} -g ${rG} \
    -n caspoolbad --mode User \
    --node-vm-size Standard_D2as_v4\
    --node-count 0 --no-wait -o none \
    --max-count 1 --min-count 0 \
    --enable-cluster-autoscaler \
    --labels test=testing \
    --priority Spot --spot-max-price 0.01

az aks nodepool add --cluster-name ${aks} -g ${rG} \
    -n caspoolgood --mode User \
    --node-vm-size Standard_D2as_v4\
    --node-count 0 --no-wait -o none \
    --max-count 1 --min-count 0 \
    --enable-cluster-autoscaler \
    --labels test=testing \
    --priority Spot --spot-max-price 0.02
```

Then deploy a Pod:
```bash
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    test: testing
  tolerations:
    - key: kubernetes.azure.com/scalesetpriority
      operator: Exists
EOF
```

**Describe the solution you'd like**
Immediately fallback if receive preemption-like message while creating spot nodes. 

**Describe alternatives you've considered**
Support `price` for CAS expander.

**Additional context**
This feature (requirement) is related to cost saving.

**Comment by kevinkrp93** [comment]
@JoeyC-Dev - Please check for errors on the provisioning side (VMSS). Also I see that there is a autoscaler warning, which is most likely due to a failure. The nodepools are also in failed state. 

FYI - for such small nodepools increase ok-total-unready-node on the profile as well as unready percentage

**Comment by JoeyC-Dev** [comment]
Hi @kevinkrp93 
Thank you for the reply, bit you did not get the point.
The whole purpose of failed status is to create a bad nodepool that cannot be used to create any VM due to price issue (refer to the 1st nodepool in the priority list). That failed state is being intentionally created to simulate the situation of the first nodepool cannot be created. It turns out of it will eventually turn the 1st nodepool in the back-off status then can create another VM in the 2nd nodepol.
The point of this feature request is: if CAS cannot create VM in 1st nodepool no matter not (like price issue), it should fallback immediately instead of waiting for backoff.

Kindly review my reply. Thanks.

**Comment by JoeyC-Dev** [comment]
After reattempting my own lab, I realized that I did not prevent VM from being created in the correct way. Close this issue first. 
(I don't know if I will remember to launch the demo later because price only being changed likely monthly if I strictly try to reproduce the price not enough case.)

**Comment by veldpworld** [comment]
hi @JoeyC-Dev 

I want to do the similar use case, i need to schedule more workload on spot if available and it can fallback on ondeman if spotpool is not able to add nodes.


Aks supporting this cluster autoscaler with priority expander. Not sure this configmap is effective?  also it seems control plane only manage the cluster autoscaler deployment and its not there inthe cluster. 


https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/readme.md

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    10: 
      -  ondemandpool
    50: 
      -  spotpool
     ```
