### ISSUE TITLE
AKS-created SP lack permissions to create LoadBalancer

### ISSUE THREAD

**Issue by mbrancato** [Azure/AKS#441]
We created an AKS cluster (post GA) and it created a Service Principle named like `<clustername>SP-<datetime>`. When I deploy a service, the LoadBalancer cannot be created because of permission failures of the SP.

The important output of `kubectl describe service xxxx` below:
```
Type     Reason                      Age              From                Message
----     ------                      ----             ----                -------
Normal   EnsuringLoadBalancer        2m (x6 over 5m)  service-controller  Ensuring load balancer
Warning  CreatingLoadBalancerFailed  2m (x6 over 5m)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service default/servicename: network.SubnetsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '85axxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' with object id '85axxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/subnets/read' over scope '/subscriptions/b8xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/resource-group-name/providers/Microsoft.Network/virtualNetworks/vnet-name/subnets/subnet-name'."
```

I'm a bit confused if the LoadBalancer is created in the `MC_*` "hidden" resource group or in the main resource group where the AKS resource exists.

**Comment by sauryadas** [comment]
did you use adv networking?

**Comment by mbrancato** [comment]
Yes. It was placed in an existing VNET. Does the SP need credentials to in the resource group where the original VNET is?

**Comment by sauryadas** [comment]
Yes it does ..

Thanks
Saurya
________________________________

**Comment by mbrancato** [comment]
Thanks. I did confirm adding Contributor right to the parent RG fixes the issue.  I haven't yet confirmed if this needs access to the RG where the VNET resource lives, or just the RG where the AKS resource is created. The docs seem to describe this, I must have missed it.

https://docs.microsoft.com/en-us/azure/aks/networking-overview#advanced-networking-prerequisites

**Comment by torosent** [comment]
The problem is reproduced by the following flow:

1. Create AKS cluster from the portal with a generated (New) Service Principal.
2. Advanced Networking: Click on Create a new VNET.

The new VNET is created in the AKS resource group and not in the MC resource group. The SP doesn't have permissions to the AKS resource group. It only has permissions to the MC resource group.
We have to add it manually to the AKS resource group.

**Comment by weinong** [comment]
this has been improved from the portal to create role assignment to the subnet.
