### ISSUE TITLE
[BUG] csi-azuredisk-node is OOMing causing all pods with PV to `Pending` forever

### ISSUE THREAD

**Issue by grzesuav** [Azure/AKS#4421]
**Describe the bug**
When on node multiple pods with PV's are scheduled around the same time, `azuredisk` container is `OOMing` constantly, making any volume attach-detach operation to fail. It happen several time already.
First time it was for ~10 PV being requested to mount at once, second time for `20`.

<img width="870" alt="image" src="https://github.com/user-attachments/assets/71ca4d51-cd8c-48ac-9342-aba4aa12d242">

Kubelet logs re memory
```
OOMKilling
Memory cgroup out of memory: Killed process 26928 (azurediskplugin) 
total-vm:1273100kB, 
anon-rss:19188kB, 
file-rss:31140kB, 
shmem-rss:0kB, 
UID:0 
pgtables:204kB 
oom_score_adj:-997
```
container spec from daemonset
```json
"resources": {
  "limits": {
    "memory": "200Mi"
   },
}
```        

Kubelet logs re: failed mount
```
Operation for "{volumeName:kubernetes.io/csi/disk.csi.azure.com^/subscriptions/xxx/resourceGroups/yyy-node/providers/Microsoft.Compute/disks/pvc-zzzz podName: nodeName:}" failed. 
No retries permitted until 2024-07-19 07:31:57.673368269 +0000 UTC m=+157356.608790197 (durationBeforeRetry 2m2s). 
Error: MountVolume.MountDevice failed for volume "pvc-zzz" 
(UniqueName: "kubernetes.io/csi/disk.csi.azure.com^/subscriptions/xxx/resourceGroups/yyy-node/providers/Microsoft.Compute/disks/pvc-zzz") pod "name" (UID: "uid") : 
rpc error: code = Unavailable 
desc = connection error: 
desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins/disk.csi.azure.com/csi.sock: connect: connection refused"
```        

Node is `Standard_E32ads_v5` - https://learn.microsoft.com/en-us/azure/virtual-machines/easv5-eadsv5-series
**To Reproduce**
Hard to reproduce, condition which need to be met is scheduling big number (~20) pods with PV's in the same time

**Expected behavior**
It works, do not restarts, volumes are mounted, pods starting.

**Screenshots**
Done

**Environment (please complete the following information):**
 - Kubernetes version [e.g. 1.27.x]

**Additional context**
There is no easy way with csi driver to lower the number of supported disk (it is 32 for the given instance type) for scheduler

**Comment by andyzhangx** [comment]
addressed by https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/2416#issuecomment-2238654949

**Comment by grzesuav** [comment]
@andyzhangx the issue is not addressed, in my case container was using over 1GB, increasing limit to 600MB is hardly a solution
