### ISSUE TITLE
[BUG] ContainerD deadlock present in 1.7.15, fixed in 1.7.17 or newer

### ISSUE THREAD

**Issue by ben-childs-docusign** [Azure/AKS#4426]
**Describe the bug**

We are seeing our AKS nodes running 1,29.5 go into a not ready state and looking at logs it appears that containerd is hanging and becoming non responsive.

There are 2 deadlock bugs fixed in containerd 1.7.16 and 1.7.17
https://github.com/containerd/ttrpc/pull/168
https://github.com/containerd/nri/pull/79

When can we expect containerd to be upgraded to 1.7.17 or newer to address these deadlock issues?

**To Reproduce**

We are seeing this issue most reliably when we enable istio native sidecars [https://learn.microsoft.com/en-us/azure/aks/istio-native-sidecar] on our test cluster where we have a large number of cron jobs running to execute various tests. This is blocking us from adopting istio native sidecars in any production environments.

**Expected behavior**

Our cluster nodes remain in a ready state

**Screenshots**

![unnamed](https://github.com/user-attachments/assets/3aa40503-3201-4b5d-9398-0fa380fc7fe3)

**Environment (please complete the following information):**
 -  CLI Version : N/A
 - Kubernetes version: 1.29.5
 - CLI Extension version [e.g. 1.7.5] if applicable: N/A
 - Browser [e.g. chrome, safari] is applicable: N/A

**Additional context**

**Comment by UtheMan** [comment]
We are working on bumping the containerd version to `.20` patch version. It will be available with one of the upcoming node image versions. I will update in this thread once the roll out starts.

**Comment by ben-childs-docusign** [comment]
Thank you we are testing the fixes now. FYI we also tested the azure linux image which has containerd 1.6.20 and that also has a deadlock bug fixed in 1.6.25 
https://github.com/containerd/containerd/pull/9210

@UtheMan should I open a separate ticket to get that upgraded? This would block us from using Azure Linux in our clusters.

**Comment by ben-childs-docusign** [comment]
@UtheMan 

Unfortunately it looks like the fips image was not updated and we use Fips in our clusters. Is it possible to also update the fips image?

I don't see any way to re-open this issue could you help with that?
