### ISSUE TITLE
no public IP being provided

### ISSUE THREAD

**Issue by nigel-dewar** [Azure/AKS#443]
Hi There,

I followed this tutorial here from Jessica Deen
https://www.youtube.com/watch?v=HMIxLaisKiI&t=421s

exactly and successfully build and deploy to AKS

Problem is my deployed services do not get an external IP so I cant use them>???.  At first it did get an external IP, but I had to delete the deployment a couple of times from kubers as it couldnt pull the image ( I had the image address wrong ), but now it can pull the image, but now it wont automatically assign a public IP

![image](https://user-images.githubusercontent.com/9402456/41530115-802666a4-7332-11e8-871d-33240275ba60.png)

As far as I can see I have done everything right

My kubectl run looks like so

![image](https://user-images.githubusercontent.com/9402456/41530141-9d97bc38-7332-11e8-9e47-20546ef9137e.png)

And the expose looks like so

![image](https://user-images.githubusercontent.com/9402456/41530149-a70cb624-7332-11e8-8a00-335c3ee8f29c.png)

Any ideas?

**Comment by nigel-dewar** [comment]
Update on this. Finally after along time an IP wa assigned,  http://40.114.64.229/ but when clicking on it, it does not load me .net core app

I get this site cant be reached.

Is there something special with port mappings one must do with a .net core 2.0 app?  I created this app .net core app fresh by the way through visual studio. ( zero changes ). So it should just run

**Comment by StianOvrevage** [comment]
I might be experiencing the same problem.

Exposing a service using LoadBalancer results in the external ip stuck in <pending> for now 42 minutes and counting.

This started happening after setting up a new cluster with RBAC enabled.

```
root@MonsterPC:~# kubectl describe svc  kube-prometheus-grafana
Name:                     kube-prometheus-grafana
Labels:                   app=kube-prometheus-grafana
                          chart=grafana-0.0.35
                          heritage=Tiller
                          release=kube-prometheus
Annotations:              <none>
Selector:                 app=kube-prometheus-grafana
Type:                     LoadBalancer
IP:                       10.0.114.163
Port:                     http  80/TCP
TargetPort:               3000/TCP
NodePort:                 http  32412/TCP
Endpoints:                10.244.1.13:3000
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason  Age   From                Message
  ----    ------  ----  ----                -------
  Normal  Type    34m   service-controller  ClusterIP -> LoadBalancer
```

```
root@MonsterPC:~# kubectl get svc -w
NAME                                  TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
kube-prometheus-grafana               LoadBalancer   10.0.114.163   <pending>     80:32412/TCP        42m
```

**Comment by nigel-dewar** [comment]
One of my deployments actually worked and I got an external IP that started working. God knows what I did however. it was 15 mins after I left it and come back to it, before it was working then it decided to start working. weird

**Comment by StianOvrevage** [comment]
We re-created a cluster with a different name and then it worked again. A member of our team mentioned that AKS had a history of not cleaning up properly when destroying clusters so that re-creating a cluster with the same name some times resulted in an inconsistent state.

**Comment by nigel-dewar** [comment]
Awesome. Thanks for the heads up on this.

On 20 Jun 2018 9:01 PM, Stian Øvrevåge <notifications@github.com> wrote:

We re-created a cluster with a different name and then it worked again. A member of our team mentioned that AKS had a history of not cleaning up properly when destroying clusters so that re-creating a cluster with the same name some times resulted in an inconsistent state.

**Comment by LoungeFlyZ** [comment]
I am experiencing this with a LB that has had a pending IP for 24+hours.  The strange thing is that the IP Address _has_ been allocated and i can see it in the Azure portal, and it is hooked up to the LB etc... But in `kubectl get svc` i see "<pending>" on it.

**Comment by weinong** [comment]
Do you guys still have repro recently? Can you send details like subscriptionID, resource group, resource name and region to aks-help@service.microsoft.com for us to take a look?

**Comment by jnoller** [comment]
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
