### ISSUE TITLE
[Question] How to remove AKS's metrics-server

### ISSUE THREAD

**Issue by asparagusbeef** [Azure/AKS#4436]
Just disable prometheus-adapter and use metrics-server instead. They serve the same purpose, since AKS already provides metrics-server by default, don't use prometheus adapter.

_Originally posted by @rouke-broersma in https://github.com/Azure/AKS/issues/3631#issuecomment-1529498389_

---

I don't think that's the correct response, because there are other use cases for disabling the metrics-server. Perhpas for the specific premetheous use-case it doesn't make sense, but for example, for use with KEDA, according to the [Docs](https://learn.microsoft.com/en-us/azure/aks/keda-about) "Only one metric server is allowed in the Kubernetes cluster. Because of that the KEDA add-on should be the only metrics server inside the cluster."

And I do see HPA misbehaving, and then goes back to normal for a minute when I delete metrics-server, then starts misbehaving again the moment the metric-server starts. 

I tried running this
```
kubectl delete service/metrics-server -n  kube-system
kubectl delete deployment.apps/metrics-server  -n  kube-system
kubectl delete apiservices.apiregistration.k8s.io v1beta1.metrics.k8s.io
kubectl delete clusterroles.rbac.authorization.k8s.io system:aggregated-metrics-reader
kubectl delete clusterroles.rbac.authorization.k8s.io system:metrics-server 
kubectl delete clusterrolebinding metrics-server:system:auth-delegator
kubectl delete clusterrolebinding system:metrics-server          
kubectl delete rolebinding metrics-server-auth-reader -n kube-system 
kubectl delete serviceaccount metrics-server -n kube-system
```

From here https://github.com/prometheus-operator/kube-prometheus/issues/926

Which didn't work.

So... How should I remove the AKS default metrics-server?

**Comment by rouke-broersma** [comment]
If that is the case I suggest you open a support ticket with azure, because both components are provided by the same team and as such they should work together nicely.

**Comment by JoeyC-Dev** [comment]
> Only one metric server is allowed in the Kubernetes cluster. Because of that the KEDA add-on should be the only metrics server inside the cluster.

That statement is not accurate, this should be "external metric server", not "metric server".
![image](https://github.com/user-attachments/assets/cdce94d5-1b75-48af-beb7-c7fa6a154535)

Src: https://keda.sh/docs/2.14/faq/#can-i-run-multiple-metric-servers-serving-external-metrics-in-the-same-cluster

Or it is already against itself, like below:
![image](https://github.com/user-attachments/assets/6a2859f7-9fc2-43a5-85a6-735e296d38a9)

If you check the official document, you will find out three different types of metrics:
![image](https://github.com/user-attachments/assets/7e061691-f402-48bc-bbbe-012c06fda3e4)
Src: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-metrics-apis
