### ISSUE TITLE
[BUG] Unreadable AGIC document

### ISSUE THREAD

**Issue by JoeyC-Dev** [Azure/AKS#4438]
**Describe the bug**
The issue is literal, as the screenshots below:
![image](https://github.com/user-attachments/assets/732ce0e8-04ae-48d1-ba80-b70e9b5d092d)
![image](https://github.com/user-attachments/assets/caa0a503-0ad5-4afb-ae79-8685f1ff6b85)

Example: https://azure.github.io/application-gateway-kubernetes-ingress/setup/install/

**Additional context**
I try to ask in AGIC repo, but the issue is not being solved for a long time: 
https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1619

**Comment by sabbour** [comment]
This is not an issue on Microsoft Docs. You rightfully opened an issue on the AGIC repo.

**Comment by JackStromberg** [comment]
This will be fixed shortly.
https://github.com/Azure/application-gateway-kubernetes-ingress/pull/1642

**Comment by JoeyC-Dev** [comment]
@JackStromberg still does not look right after 2 weeks:
![image](https://github.com/user-attachments/assets/93ac48eb-8f0c-4f61-9de5-8353cbad8825)

**Comment by JackStromberg** [comment]
The change is live now.

Cheers!
