### ISSUE TITLE
Contributor permissions for cluster service principal on resource group containing VNet overly broad

### ISSUE THREAD

**Issue by amandadebler** [Azure/AKS#444]
Our security team will not let us use AKS with an internal load balancer right now because they find the "Contributor" permissions level on the VNet resource group for the cluster Service Principal object to be too broad.

Is there a more specific set of permissions we could use? Possibly one set at the time of cluster/service creation, and another for ongoing operations?

Ideally, we would have been able to use private (VNet) addresses in place of public ones on a load balancer and kept the rest of the cluster under local IP addresses, not connected to our network, but that does not appear to be Microsoft's plan for AKS.

**Comment by sauryadas** [comment]
The AKS cluster SPN requires contributor level access on the VNET RG to be able to create resources like LB's IP addresses and NSG's in the VNET required for publicly accessible apps deployed in the cluster. Private ip address only support is planned in the next quarter.

**Comment by noelbundick** [comment]
@amandadebler I've been able to successfully create an internal load balancer with the more-limited `Network Contributor` on just the subnet (not even the entire VNET). Specifically, this role contains the `Microsoft.Network/virtualNetworks/subnets/write` and `Microsoft.network/virtualNetworks/subnets/join/action` permissions, which are used when Kubernetes creates the ILB in the subnet, modifies NSG entries, and joins the compute nodes to the load balancer.

I haven't fully tested every possible scenario in the cloud provider to see if this is too limited for other operations, but this should get you up and running with ILB in a security-constrained environment

**Comment by palma21** [comment]
https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal#networking
