### ISSUE TITLE
Kubernetes Services of type ExternalName not working/resolving

### ISSUE THREAD

**Issue by wombat** [Azure/AKS#445]
Currently in the latest AKS (1.9.6) cluster version 1.14.8 of DNS is installed which has a critical bug where it does not resolve the names of Kubernetes Services of type ExternalName - I tried to upgrade it to 1.14.10 but some controller undoes the changes.
Any hints on how to solve this or when DNS is updated?

**Comment by weinong** [comment]
I'm closing this comment. Let's follow the issue I open in acs-engine.
