### ISSUE TITLE
How to deploy a windows node into cluster

### ISSUE THREAD

**Issue by Cherishty** [Azure/AKS#446]
Hi team, when deploying aks following the quick start doc in https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough-portal, I find the generated template shows that the os-type only contains 'Linux' .
Can aks support to deploy a windows worker node in cluster. if so, how to do it?

Best Regards!

**Comment by sauryadas** [comment]
Not yet. No ETA though. Please use acs-engine for windows node pools.
