### ISSUE TITLE
[Question] What is the difference of availability zone settings between AKS and nodepool?

### ISSUE THREAD

**Issue by JoeyC-Dev** [Azure/AKS#4463]
**Describe scenario**
Trying to enable availability zone but being confused by Azure portal.

I found two availability zone settings:
![image](https://github.com/user-attachments/assets/a5229096-991e-4686-ad6f-31329789a979)
![image](https://github.com/user-attachments/assets/7fe2abc4-b6a5-47c1-b84b-e264fb17ea64)

Initially, I thought the availability zone in the 1st tab is referring to the availability zone setting for control plane. But after checking `az-cli` command, I don't see any specific parameter for settings availability zone for control plane.
The only thing I found in `az aks create` is as below:
![image](https://github.com/user-attachments/assets/ccce9371-6de9-4bf7-bf65-1ae80251d349)

And this is talking about the default agent pool settings.

Then I did the following thing in Azure portal:
1. In the "Basic" tab, I set the zone as "1":
![image](https://github.com/user-attachments/assets/e2a7619e-e9f8-4397-ba87-a1dfdc7248e0)
2. In the agent pool settings, I set the zone as "2":
![image](https://github.com/user-attachments/assets/642541d7-9233-4270-b01b-9b8405abc894)
3. Directly click on "Review+Create", get the final detail as below:
![image](https://github.com/user-attachments/assets/7af7a51e-bc4f-4754-9cdb-361d7c8418c4)
4. Click on "view automation template", and only can see zone settings with "2", the "1" never appears.
![image](https://github.com/user-attachments/assets/e452a1ad-0fb5-445b-9a0a-2a3864170004)
![image](https://github.com/user-attachments/assets/df582ec1-b2b8-4070-a861-747b94b030b5)

So at the time I am pretty convinced that these two configurations are duplicated settings and can mislead users. Not sure if should report as bug.

**Question**
1. Does availability zone settings for AKS control plane exist?
5. If the answer to question 1 is no, then what the availability zone setting in the 1st tab is referring to? Isn't it duplicated with the setting in nodepool tab?

**Comment by aritraghosh** [comment]
The first one is for the Control Plane and the second one is for nodes. The description for Control Plane neeeds to be changed, please file a support case or request for the same
