### ISSUE TITLE
Observations on StorageClasses and PVs created in the GA release of AKS

### ISSUE THREAD

**Issue by patrickmslatteryvt** [Azure/AKS#447]
Observations on StorageClasses and PVs created in the GA release of AKS:

* The OS disks on the worker nodes are 30GB by default and use premium SSDs but have a **120 IOPS** and **25 MB/s** limit.

* There are two storage classes defined by default: **default** and **managed-premium**. The default is using **Standard_LRS** while the **managed-premium** disk is using **Premium_LRS** as one might expect from the naming.

* A PV created in the **default** StorageClass is listed as using **Standard (HDD)** as expected but has an **IOPS limit of 500** (which is far beyond what a single standard spinning HDD can do) and a throughput limit of **60 MB/s**.

* A PV created in the **managed-premium** StorageClass is listed as using **Premium (SSD)** as expected but has an **IOPS limit of 120** and a throughput limit of **25 MB/s**.

These figures would indicate to me that the IOPS and throughput limits for the PVs are reversed and should be **500 IOPS for the SSD** backed StorageClass and **120 IOPS for the HDD** backed StorageClass.

**Comment by noelbundick** [comment]
These are actually correct. Premium Disk IOPS vary based on the size of the provisioned disk - this link might help explain the figures
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disk-scalability-targets

Azure Storage is a managed storage service and operates on various arrays of underlying storage, so it's able to give you more reliability & performance than you could get with a single spinning disk. Each write is replicated 3 times within a region (or more if you've chosen RA-GRS, etc)

You'll see in the linked doc that Premium Disks start to far exceed Standard Disks at the 512GB mark, scaling up to 7500 IOPS and 250MB/s throughput per disk - and you can attach multiple

**Comment by patrickmslatteryvt** [comment]
Wow, those are some real low ball numbers for SSD storage, if I was using Google Cloud I'd get 960 IOPS on a 32GB SSD.
https://cloud.google.com/compute/docs/disks/performance#ssd-pd-performance

**Comment by derekperkins** [comment]
@patrickmslatteryvt I haven't found them to be that different in practice, despite my initial concerns that Google markets their disks at much higher performance. That testing is mostly on > 10 TB disks, where I had to RAID disks on Azure.

**Comment by jalberto** [comment]
one more observation: #295

**Comment by joaocc** [comment]
Hi,
Any guidelines on how to use the new StandardSSD_LRS in AKS?
Is it simply a matter of creating a new StorageClass or do we need to wait for a specific kubernetes version?
Thx

**Comment by andyzhangx** [comment]
@joaocc 
new managed disk types [`StandardSSD_LRS`](https://aka.ms/StandardSSDBlog), `UltraSSD_LRS` are available from `v1.13.0`

all possible `skuname` values are `Standard_LRS`, `StandardSSD_LRS`, `Premium_LRS`, `UltraSSD_LRS`
> Note: `UltraSSD_LRS` is still in Preview, it's only avaiable in certain region and supports Availablity Zone only, while AKS does not support Availablity Zone yet, details about UltraSSD_LRS: [Ultra SSD (preview) Managed Disks for Azure Virtual Machine workloads](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disks-ultra-ssd)

Below are the performance of standard disk and premium disk, perf changes for different size:
[Azure Standard Disk Scalability and Performance Targets](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/standard-storage?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json#scalability-and-performance-targets)

[Azure Premium Disk Scalability and Performance Targets](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/premium-storage#premium-storage-disk-limits)

close the issue now since it's already resolved, let me know if you have any question.

**Comment by andyzhangx** [comment]
To support UltraSSD, need to specify UltraSSD capability in VM set up, AKS team are working on that.

**Comment by xamox** [comment]
> To support UltraSSD, need to specify UltraSSD capability in VM set up, AKS team are working on that.
@andyzhangx
 
Is this a link to that documentation (i.e. how to enable it)?
I came across this article: https://nedinthecloud.com/2019/09/02/using-ultra-ssd-storage-with-azure-kubernetes-service/
I know it's a bit dated, do the Ultra Disk still suffer from the random zonality as described in that article?

**Comment by andyzhangx** [comment]
> > To support UltraSSD, need to specify UltraSSD capability in VM set up, AKS team are working on that.
> > @andyzhangx
> 
> Is this a link to that documentation (i.e. how to enable it)?
> I came across this article: https://nedinthecloud.com/2019/09/02/using-ultra-ssd-storage-with-azure-kubernetes-service/
> I know it's a bit dated, do the Ultra Disk still suffer from the random zonality as described in that article?

@xamox UltraSSD support requires availability zone support: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-enable-ultra-ssd#ga-scope-and-limitations
We are working on integrating UltraSSD feature with AKS, it's going to release very soon, stay tuned.
