### ISSUE TITLE
[BREAKING CHANGE] KEDA 2.15 and KEDA 2.14 introduces multiple breaking changes in AKS v1.30+

### ISSUE THREAD

**Issue by qpetraroia** [Azure/AKS#4471]
AKS will be upgrading the KEDA addon to KEDA 2.15 on AKS clusters with K8s versions >=1.31. The AKS team has added KEDA 2.14 to AKS v1.30.

KEDA 2.15 and KEDA 2.14 will introduce multiple breaking changes. The breaking changes are listed below:

- **KEDA 2.15**: The removal of [Pod Identity support](https://github.com/kedacore/keda/issues/5035](https://github.com/kedacore/keda/issues/5035)). If you use pod identity, we recommend you move over to [workload identity for your authentication](https://learn.microsoft.com//azure/aks/keda-workload-identity). 

-  **KEDA 2.14**: The removal of [Azure Data Explorer 'metadata.clientSecret' as it was not safe for managing secrets](https://github.com/kedacore/keda/issues/4514). Please use `clientSecretFromEnv` instead.

- **KEDA 2.14**: Removal of the [deprecated metricName from trigger metadata section](https://github.com/kedacore/keda/issues/4240).  The two impacted Azure Scalers are Azure Blob Scaler and Azure Log Analytics Scaler. If you are using `metricName` today, please move `metricName` outside of trigger metadata section  to`trigger.name` in the trigger section to optionally name your trigger.

      An example before KEDA 2.14/2.15

      triggers:
      - type: any-type
        metadata:
          metricName: "my-custom-name"
    
      
      An example after KEDA 2.14/2.15

      triggers:
      - type: any-type
        name: "my-custom-name"
        metadata:

**Comment by ztoth123** [comment]
The impacted Azure Scaler is **Azure Monitor** instead of the other 2 as `metricName` is only used by that, right?

**Comment by qpetraroia** [comment]
Hi @ztoth123, 

Nope! Azure Monitor is safe. This is because Azure Monitor use of metricName refers to the Azure metric name and not the name for the HPA metric. 

I have checked with the upstream KEDA maintainers and the only impacted Azure scalers are Azure Blob Scaler and Azure Log Analytics Scaler.

**Comment by ztoth123** [comment]
Thanks for the answer, I see now that the `metricName` is deprecated and it is mentioned e.g in this doc: https://keda.sh/docs/2.10/scalers/azure-log-analytics/
"`metricName` - Name to assign to the metric. (Optional, if not set KEDA will generate a name based on the workspaceId. DEPRECATED: This parameter is deprecated as of KEDA v2.10 and will be removed in version 2.12)"
