### ISSUE TITLE
Tunnelfront continuously restarts in all clusters provisioned before GA

### ISSUE THREAD

**Issue by gugu91** [Azure/AKS#449]
We have a number of cluster that were provisioned before GA in which the tunnelfront pod is continuously restarting. 

It's not possible to access logs from kubectl.
Describe returns the following interesting line:
`Warning  Unhealthy  5m (x3448 over 1d)   kubelet, aks-agentpool-20405555-1  Liveness probe failed:`

Logs from OMS agent that seem relevant are:
`Permission denied (publickey).\r\n | 2018-06-19T09:32:07.026 | deis/hcp-tunnel-front |`

`Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)\n | 2018-06-19T09:32:06.952 | `

`[ 09:32:06 ] INF: Ssh to tunnelend is not connected.. attempting to connect\n | 2018-06-19T09:32:06.952 | deis/hcp-tunnel-front
`

Has anyone experienced this?

Thank you!

**Comment by serbrech** [comment]
Yes, same thing experienced here since Monday.
deleting the tunnelfront pod solved the issue for us.

**Comment by angrox** [comment]
@serbrech Does killing the pod resolve the issue completely for you?

**Comment by gugu91** [comment]
@angrox Long story short, reprovision the cluster if it was provisioned before GA. You can otherwise try to delete the tunnelfront but the problem might present again.

**Comment by sauryadas** [comment]
do you still see the issue?

**Comment by angrox** [comment]
@sauryadas Sadly yes. I had the issue of crashing tunnelfront today in a newly deployed AKS Cluster, 1.10.3

**Comment by sauryadas** [comment]
@rite2nikhil can you please take a look?

**Comment by rite2nikhil** [comment]
Can you folks send me your resource id (subid, resource group, resource name) to nbhatia@microsoft.com

**Comment by rite2nikhil** [comment]
Also please post the tunnelfront logs after ssh onto the node and the use docker logs <tunnelfront container id>

**Comment by akolodkin** [comment]
We have same problem with tunnelfront.  

docker logs

[ 15:41:58 ] INF: Ssh to tunnelend is not connected.. attempting to connect
Permission denied (publickey).
[ 15:41:58 ] WRN: Was not able to establish connection to tunnelend
[ 15:41:58 ] INF: going to sleep for:[5] Seconds
[ 15:42:04 ] INF: Tunnel front and end both server.version == local.version, no rotation needed
[ 15:42:04 ] INF: ssh-agent is already running with pid: 219
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
[ 15:42:04 ] INF: Ssh to tunnelend is not connected.. attempting to connect
Permission denied (publickey).
[ 15:42:04 ] WRN: Was not able to establish connection to tunnelend
[ 15:42:04 ] INF: going to sleep for:[5] Seconds
[ 15:42:09 ] INF: Tunnel front and end both server.version == local.version, no rotation needed
[ 15:42:09 ] INF: ssh-agent is already running with pid: 219
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
[ 15:42:09 ] INF: Ssh to tunnelend is not connected.. attempting to connect
Permission denied (publickey).
[ 15:42:09 ] WRN: Was not able to establish connection to tunnelend
[ 15:42:09 ] INF: going to sleep for:[5] Seconds
[ 15:42:15 ] INF: Tunnel front and end both server.version == local.version, no rotation needed
[ 15:42:15 ] INF: ssh-agent is already running with pid: 219
[ 15:42:15 ] INF: Ssh to tunnelend is not connected.. attempting to connect
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
Permission denied (publickey).
[ 15:42:15 ] WRN: Was not able to establish connection to tunnelend
[ 15:42:15 ] INF: going to sleep for:[5] Seconds

**Comment by akolodkin** [comment]
any recommendations on resolving this issue, tunnelfront sometimes is getting up and works, next day it will crash into a loop... we cannot proxy, or tunnel into pods

**Comment by akolodkin** [comment]
just an update from our side, we update image from docker.io/deis/hcp-tunnel-front:v1.9.2-v4.0.3 to docker.io/deis/hcp-tunnel-front:v1.9.2-v4.0.4 and it seems like this resolved issue for now.

**Comment by sauryadas** [comment]
thanks. will close it .

**Comment by gugu91** [comment]
@sauryadas Reading this thread is not very transparent what the official guidelines are from MS in order to solve the issues. Looks a bit odd to close the issue without it, especially considering I got an email this morning from MS support stating that the investigation is still happening and the root cause has not been identified.

**Comment by maetthu** [comment]
@gugu91 In a newly provisioned 1.10.5 cluster (which includes hcp-tunnel-front:v1.9.2-v4.0.4), the issue seems to be resolved - at least I didn't see any tunnelfront crashes so far, but it has been only a couple of days since creating the cluster with only moderate test workload. In 1.10.3, tunnelfront was crashing right away though, so it does seem fine now.

**Comment by gugu91** [comment]
@maetthu We have been dealing with this for quite a long time, and we have applied different fixes which always turned out to be mitigations after a certain period of time. Considering this is not a minor issue, and I imagine everyone is planning to use AKS in production systems with significant economical impact in case of downtime, I think there needs to be an official guideline from Microsoft. I am quite surprised that the issue got closed 4 days ago and today MS support is stating the issue has not been resolved yet. We have also to keep in mind that this is not a free product and is supposed to be GA and not a preview.

**Comment by gugu91** [comment]
@maetthu sorry, didn't mean to undermine your feedback, just stressing I would like an official guideline from MS.

**Comment by rite2nikhil** [comment]
Folks thanks for all the feedback. 

Firstly what it means when tunnel-front is in crashloopbackoff is beacause of readiness probes failing. The readiness probe validates a healthy tunnel which allows k8s functionality like logs exec

So because of any external reason e.g network, the connection can be broken. With a recent tunnel front version 4.4 as @maetthu pointed out we have made it more resilient to external failures. We will be patching the current clusters as well.

Please let me know if there are specific clusters you would like to expedite existing cluster facing this issue by sending subscription resource group and resource info to aks-gh-feedback@services.microsoft.com

**Comment by bramvdklinkenberg** [comment]
We had simular issues and upgraded our aks cluster from 1.9.6 to 1.10.5 and that has the newest version of tunnelfront with (I guess) the neccessary fixes.

**Comment by monst3rr** [comment]
We are facing the same issue for a week now. Recreated whole cluster problem still exists

**Comment by monst3rr** [comment]
> We had simular issues and upgraded our aks cluster from 1.9.6 to 1.10.5 and that has the newest version of tunnelfront with (I guess) the neccessary fixes.

I applied this, it worked for a day only and tunnel front again went to ErrImagePull state.
