### ISSUE TITLE
[Question] With which release was the fix for the `WireServing` vulnerability rolled out and does it require action from cluster owners?

### ISSUE THREAD

**Issue by BeckerMax** [Azure/AKS#4497]
**Describe scenario**
The `WireServing` privilege escalation vulnerability has been publicly disclosed: https://cloud.google.com/blog/topics/threat-intelligence/escalating-privileges-azure-kubernetes-services/

The article mentions:

> Microsoft has fixed the underlying issue.

**Question**
1. With which AKS release has the `WireServing` vulnerability [1] been fixed? Is it https://github.com/Azure/AKS/releases/tag/2024-07-16 which notes:

> Updated iptables rules in clusters with Azure Network Policy Manager to block pod access to wireserver.

2. Does the fix also require updating the K8s version of an AKS cluster or has the fix been rolled out by Azure independently of any AKS K8s version?

Thanks.

[1] https://cloud.google.com/blog/topics/threat-intelligence/escalating-privileges-azure-kubernetes-services/?hl=en

**Comment by JoeyC-Dev** [comment]
1. Yes: https://github.com/Azure/AKS/issues/4503
2. No customer intervention is needed.

**Comment by BeckerMax** [comment]
Thanks a lot for the prompt response
