### ISSUE TITLE
aks provision failed twice East US region

### ISSUE THREAD

**Issue by JuneZhao** [Azure/AKS#45]
AKS fail with below error on East US  region twice
...@Azure:~$ az aks create -g pnp-dd-compute-eastus -n pnp-dd-aks --kubernetes-version 1.8.1 --node-count 12 --generate-ssh-keys --node-vm-size Standad_F8s_v2 -l eastus --service-principal="my_appid" --client-secret="my_secret"

Exception in thread AzureOperationPoller(da199b3d-5c73-409e-86e3-4bf20ce1cb9c):
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_operation.py", line 377, in _start
    self._poll(update_cmd)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_operation.py", line 464, in _poll
    raise OperationFailed("Operation failed or cancelled")
msrestazure.azure_operation.OperationFailed: Operation failed or cancelled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/az/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_operation.py", line 388, in _start
    self._exception = CloudError(self._response)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 148, in __init__
    self._build_error_data(response)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 164, in _build_error_data
    self.error = self.deserializer('CloudErrorRoot', response).error
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 992, in __call__
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1143, in deserialize_data
    return self(obj_type, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 998, in __call__
    return self._instantiate_model(response, d_attrs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1090, in _instantiate_model
    response_obj = response(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 59, in __init__
    self.message = kwargs.get('message')
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 105, in message
    value = eval(value)
  File "<string>", line 1, in <module>
NameError: name 'resources' is not defined

{
  "id": null,
  "location": null,
  "name": "7531be55-df3a-194f-8ab6-3430676f0d47",
  "properties": null,
  "tags": null,
  "type": null
}

**Comment by amanohar** [comment]
@JuneZhao you provided size `Standad_F8s_v2` for your agent pool which is not in the list of allowed VM sizes. 

In some cases detailed error information is not being returned. We are working on fixing this. Can you try again with one of the size listed below?

Here is the list of allowed list of sizes:

>Standard_A0,Standard_A1,Standard_A10,Standard_A11,Standard_A1_v2,Standard_A2,Standard_A2_v2,Standard_A2m_v2,Standard_A3,Standard_A4,Standard_A4_v2,Standard_A4m_v2,Standard_A5,Standard_A6,Standard_A7,Standard_A8,Standard_A8_v2,Standard_A8m_v2,Standard_A9,Standard_B1ms,Standard_B1s,Standard_B2ms,Standard_B2s,Standard_B4ms,Standard_B8ms,Standard_D1,Standard_D11,Standard_D11_v2,Standard_D11_v2_Promo,Standard_D12,Standard_D12_v2,Standard_D12_v2_Promo,Standard_D13,Standard_D13_v2,Standard_D13_v2_Promo,Standard_D14,Standard_D14_v2,Standard_D14_v2_Promo,Standard_D15_v2,Standard_D16_v3,Standard_D16s_v3,Standard_D1_v2,Standard_D2,Standard_D2_v2,Standard_D2_v2_Promo,Standard_D2_v3,Standard_D2s_v3,Standard_D3,Standard_D32_v3,Standard_D32s_v3,Standard_D3_v2,Standard_D3_v2_Promo,Standard_D4,Standard_D4_v2,Standard_D4_v2_Promo,Standard_D4_v3,Standard_D4s_v3,Standard_D5_v2,Standard_D5_v2_Promo,Standard_D64_v3,Standard_D64s_v3,Standard_D8_v3,Standard_D8s_v3,Standard_DS1,Standard_DS11,Standard_DS11_v2,Standard_DS11_v2_Promo,Standard_DS12,Standard_DS12_v2,Standard_DS12_v2_Promo,Standard_DS13,Standard_DS13-2_v2,Standard_DS13-4_v2,Standard_DS13_v2,Standard_DS13_v2_Promo,Standard_DS14,Standard_DS14-4_v2,Standard_DS14-8_v2,Standard_DS14_v2,Standard_DS14_v2_Promo,Standard_DS15_v2,Standard_DS1_v2,Standard_DS2,Standard_DS2_v2,Standard_DS2_v2_Promo,Standard_DS3,Standard_DS3_v2,Standard_DS3_v2_Promo,Standard_DS4,Standard_DS4_v2,Standard_DS4_v2_Promo,Standard_DS5_v2,Standard_DS5_v2_Promo,Standard_E16_v3,Standard_E16s_v3,Standard_E2_v3,Standard_E2s_v3,Standard_E32-16s_v3,Standard_E32-8s_v3,Standard_E32_v3,Standard_E32s_v3,Standard_E4_v3,Standard_E4s_v3,Standard_E64-16s_v3,Standard_E64-32s_v3,Standard_E64_v3,Standard_E64s_v3,Standard_E8_v3,Standard_E8s_v3,Standard_F1,Standard_F16,Standard_F16s,Standard_F16s_v2,Standard_F1s,Standard_F2,Standard_F2s,Standard_F2s_v2,Standard_F32s_v2,Standard_F4,Standard_F4s,Standard_F4s_v2,Standard_F64s_v2,Standard_F72s_v2,Standard_F8,Standard_F8s,Standard_F8s_v2,Standard_G1,Standard_G2,Standard_G3,Standard_G4,Standard_G5,Standard_GS1,Standard_GS2,Standard_GS3,Standard_GS4,Standard_GS4-4,Standard_GS4-8,Standard_GS5,Standard_GS5-16,Standard_GS5-8,Standard_H16,Standard_H16m,Standard_H16mr,Standard_H16r,Standard_H8,Standard_H8m,Standard_L16s,Standard_L32s,Standard_L4s,Standard_L8s,Standard_M128ms,Standard_M128s,Standard_M64-16ms,Standard_M64-32ms,Standard_M64ms,Standard_M64s,Standard_NC12,Standard_NC12s_v2,Standard_NC24,Standard_NC24r,Standard_NC24rs_v2,Standard_NC24s_v2,Standard_NC6,Standard_NC6s_v2,Standard_ND12s,Standard_ND24rs,Standard_ND24s,Standard_ND6s,Standard_NV12,Standard_NV24,Standard_NV6

**Comment by JuneZhao** [comment]
@amanohar  Thank you better add  the information for the output if the size is not applicable

**Comment by amanohar** [comment]
The fix has been merged and should roll out soon. Please reopen if you still see this issue in a week.
