### ISSUE TITLE
[BUG] multiple metrics-server and konnectivity-agent pods on a single node

### ISSUE THREAD

**Issue by yene** [Azure/AKS#4515]
**Describe the bug**
Multiple replicas of metircs-server, konnectivity-agent, coredns, ama-metrics on a single node cluster.
That makes 4 extra pods.

**To Reproduce**
1. create AKS 1.29.7 with a single node, with configuration for development
2. log into and kubectl get pods -A

**Expected behavior**
Each deployment having one pod out.

**Screenshots**
![image](https://github.com/user-attachments/assets/ff5486e6-28b9-49ee-8e93-5fb9b223d0ac)

**Environment (please complete the following information):**
 - Kubernetes version 1.29.7

**Additional context**

**Comment by AllenWen-at-Azure** [comment]
Hi @yene as you can find in [the AKS document](https://learn.microsoft.com/en-us/azure/aks/use-system-pools?tabs=azure-cli), _Every AKS cluster must contain at least one system node pool with at least two nodes._
