### ISSUE TITLE
[Question] Missing release notes for v20240827

### ISSUE THREAD

**Issue by sdodson** [Azure/AKS#4526]
**Describe scenario**
The [AKS Release Status page](https://releases.aks.azure.com/webpage/index.html#tabversion) lists some regions at [v20240827](https://github.com/Azure/AKS/releases) but there's no tag or release notes for that.

**Question**
Can the tag/release notes be populated for [v20240827](https://github.com/Azure/AKS/releases)?
@shashankbarsin @qpetraroia tagging you as the last two to have published a release.

**Comment by PixelRobots** [comment]
There is an active pull request waiting to be merged for this release. https://github.com/Azure/AKS/pull/4517

You should be able to view that for most changes. 

Hopefully it will be published soon.

**Comment by PixelRobots** [comment]
This has been released now. https://github.com/Azure/AKS/releases/tag/2024-08-27
