### ISSUE TITLE
[BUG] Preflight requires `servicePrincipalProfile` which is an optional field

### ISSUE THREAD

**Issue by ms-henglu** [Azure/AKS#4528]
**Describe the bug**
When I call the validateResources API on the managed cluster, I got the below error:

Request:
```
POST https://management.azure.com/providers/Microsoft.Resources/validateResources?api-version=2020-10-01

{
    "location": "westus",
    "provider": "Microsoft.ContainerService",
    "resources": [
        {
            "apiVersion": "2024-06-02-preview",
            "name": "iwwqfggi",
            "properties": {
                "agentPoolProfiles": [
                    {
                        "count": 1,
                        "mode": "System",
                        "name": "default",
                        "vmSize": "Standard_DS2_v2"
                    }
                ],
                "dnsPrefix": "acctestheng96"
            }
        }
    ],
    "scope": "/subscriptions/xxx/resourceGroups/ryumkjti",
    "type": "managedClusters"
}

```

Response
```
{
    "error": {
        "code": "ResourceValidationFailed",
        "details": [
            {
                "code": "InvalidParameter",
                "message": "Preflight validation check for resource(s) for container service iwwqfggi in resource group ryumkjti failed. Message: Required parameter servicePrincipalProfile is missing (null)..
Details: "
            }
        ],
        "message": "Resource validation failed, correlation id: '1e08b940-28c1-64de-599a-2f4e715bbb4c', see details for more information."
    }
}
```

**To Reproduce**
1. Run above request

**Expected behavior**
The servicePrincipalProfile should be an optional field because I use the managed identity.

**Screenshots**

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22]
 - Kubernetes version [e.g. 1.24.3]
 - CLI Extension version [e.g. 1.7.5] if applicable
 - Browser [e.g. chrome, safari] is applicable

**Additional context**

**Comment by skuchipudi295** [comment]
managedCluster.Properties.OrchestratorProfile = &hcpProfiles.OrchestratorProfile{
		KubernetesConfig: &v1.KubernetesConfig{
			UseManagedIdentity: true
       }
}

I dont see this property set in the request body

**Comment by ms-henglu** [comment]
Thanks @skuchipudi295 ! My bad, I forgot to add the identity to the request body.
