### ISSUE TITLE
Cannot create an AKS cluster from Portal UI

### ISSUE THREAD

**Issue by Vlatombe** [Azure/AKS#453]
All my attempts fail with the following error (with variants depending on the region I select).

`ResourceGroupNotFoundResource group 'DefaultResourceGroup-WEU' could not be found.`

Creating an AKS cluster from the CLI works just fine.

**Comment by Vlatombe** [comment]
This is related to the Monitoring feature. If I disable it, then the validation passes and I'm able to create a cluster.

**Comment by mboersma** [comment]
@Vlatombe I've created AKS clusters in the portal with monitoring enabled and didn't see this problem. Maybe something's been fixed since then?

If not, could you send details with subscription ID, resource group name, Azure region, and cluster name to aks-help@service.microsoft.com so we can investigate further?

**Comment by Vlatombe** [comment]
Closing the ticket without resolution is not a good way to handle support. Especially since it wasn't updated at all since I created the ticket.

Nothing has changed, I still get the same error message whenever I enable the Monitoring upon creation.

I don't have full admin access in the account I work with. I only have owner access to specific resource groups, and I can't create new ones. My understanding is that the wizard tries to do something related to Monitoring in the resource group `DefaultResourceGroup-WEU`, which doesn't exist. As I don't have the privilege to create resource groups, it just stops there with this non meaningful error message.

**Comment by danielvdende** [comment]
Having exactly the same problem

**Comment by anderl80** [comment]
Same problem here

**Comment by sbischoff-ai** [comment]
Same problem here. This issue is **not** resolved.

**Comment by jnoller** [comment]
Please file a support issue so we can escalate to on-call, these are the only reports of any issues and it can not be reproduced by engineering.
