### ISSUE TITLE
[Feature] Option to specify static IP for Load Balancer IP

### ISSUE THREAD

**Issue by gigabytte** [Azure/AKS#4532]
Ability to specify a static IP for the ingress gateway loadbalancer IP like we can from Istio OSS helm chart install. Link to Istio gateway chart values: https://github.com/istio/istio/blob/833fe1e8d884a3b59117d13734f0a409df11c295/manifests/charts/gateway/values.yaml#L59

This would allow for more confidence when using other ALB products in front of Istio. Currently IP is dynamic and could change and result in outage. (ie. Using Azure App Gateway for WAF functions publicly facing and setting Istio as backend target with a static IP)

Link to similar stackoverflow post https://stackoverflow.com/questions/76261634/azure-aks-static-ip-address-for-aks-istio-ingressgateway-external

**Comment by nshankar13** [comment]
@gigabytte This has been implemented and should be out by the next AKS release. The ETA for this is end of September latest. We will provide an update one this is has rolled out. Thanks.

**Comment by gigabytte** [comment]
Thanks for the quick reply @nshankar13 .. closing
