### ISSUE TITLE
[BUG] Nodes with Ubuntu2204 ImageFamily are not able to join the cluster

### ISSUE THREAD

**Issue by CCOLLOT** [Azure/AKS#4545]
**Describe the bug**
Nodes running the latest image from the Ubuntu 2204 imageFamily are not joining the cluster. I'm running on AKS with k8s version 1.28.9.

**Investigation**
After ssh-ing into the node, I concluded that:
- Ubuntu2204 Family is not working as of 13.09.2024 (/CommunityGalleries/AKSUbuntu-38d80f77-467a-481f-a8d4-09b6d4220bd2/images/2204gen2containerd/versions/202409.13.0).
- The failure is related to missing variables when invoking the following script during node initialization:
`/opt/azure/containers/ensure_imds_restriction.sh` .

Content of the service file for kubelet: 
```bash
Environment="PRIMARY_NIC_IP=10.117.0.121"
Environment="ENABLE_IMDS_RESTRICTION="
Environment="INSERT_IMDS_RESTRICTION_RULE_TO_MANGLE_TABLE="
```

Switching from Ubuntu2204 to AzureLinux solved the issue

**To Reproduce**
1. Run AKS (all my clusters run the same 1.28.9 version)
2. I am running NAP to provision nodes (probably not related?)
3. Try adding a node using the mentioned Ubuntu2204 image

**Comment by CCOLLOT** [comment]
West Europe

**Comment by norshtein** [comment]
There is an error in that vhd, which was fixed in this PR https://github.com/Azure/AgentBaker/pull/4944

**Comment by norshtein** [comment]
@CCOLLOT may I know how do you update the node image to `/CommunityGalleries/AKSUbuntu-38d80f77-467a-481f-a8d4-09b6d4220bd2/images/2204gen2containerd/versions/202409.13.0` ?

**Comment by CCOLLOT** [comment]
This environment's nodes were being automatically updated by Node Auto Provisoning (karpenter) to the latest version of the image of the Ubuntu2204 imageFamily.

**Comment by norshtein** [comment]
I see, the issue in karpenter was fixed by https://github.com/Azure/karpenter-provider-azure/pull/484 in 0.5.4 release , should recover now.  CC @tallaxes
