### ISSUE TITLE
Multiple EOL libraries used in AKS 1.30 system containers

### ISSUE THREAD

**Issue by neeleshizme** [Azure/AKS#4546]
Describe scenario
I have noticed that several components/container running in AKS 1.30 are utilizing libraries that have reached their end of life. Below are the details of the EOL libraries identified:

1.	Multiple containers under aks still flagging after updated aks to 1.30 version. 
mcr.microsoft.com/azuremonitor/containerinsights/ciprod
mcr.microsoft.com/oss/kubernetes-csi/azuredisk-csi
mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi
mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager
mcr.microsoft.com/oss/azure/secrets-store/provider-azure
mcr.microsoft.com/oss/kubernetes-csi/blob-csi
mcr.microsoft.com/oss/azure/aad-pod-identity/nmi
mcr.microsoft.com/oss/kubernetes/coredns
mcr.microsoft.com/azuremonitor/containerinsights/ciprod/prometheus-collector/images
mcr.microsoft.com/oss/azure/workload-identity/webhook
mcr.microsoft.com/oss/azure/aad-pod-identity/mic
mcr.microsoft.com/azure-policy/policy-kubernetes-addon-prod
mcr.microsoft.com/azuredefender/stable/pod-collector
mcr.microsoft.com/azuredefender/stable/low-level-collector
mcr.microsoft.com/oss/kedacore/keda
mcr.microsoft.com/oss/kedacore/keda-metrics-apiserver

Library: Active Directory Authentication Library (ADAL) 0.9.23
EOL Date: March 31, 2023
Details: ADAL 0.9.23 has been deprecated, and it is recommended to move to the Microsoft Authentication Library (MSAL).
Reference: https://github.com/azure-deprecation/dashboard/issues/60

2.	Kubernetes related binary on Aks node like 
a.	/usr/bin/kubelogin
b.	/usr/local/bin/kubectl
c.	/usr/local/bin/kubelet

Question:
What are there plans to update these libraries to supported versions soon?
```[tasklist]
### Tasks
- [ ] fluent bit EOL base image upgrade in latest aks version
```

**Comment by AllenWen-at-Azure** [comment]
Please check out the time line at https://github.com/Azure/AKS/issues/4576

**Comment by neeleshizme** [comment]
> Please check out the time line at #4576

Thanks @AllenWen-at-Azure for the ETA, would you be also able to help with ETA's for remaining container images as well?

**Comment by AllenWen-at-Azure** [comment]
@neeleshizme we are working on the ETA for KEDA and Azure Defender. 
Could you please share the full scan results for below 2 Azure Defender images? 

- mcr.microsoft.com/azuredefender/stable/pod-collector
- mcr.microsoft.com/azuredefender/stable/low-level-collector

**Comment by neeleshizme** [comment]
> [@neeleshizme](https://github.com/neeleshizme) we are working on the ETA for KEDA and Azure Defender. Could you please share the full scan results for below 2 Azure Defender images?
> 
> * mcr.microsoft.com/azuredefender/stable/pod-collector
> * mcr.microsoft.com/azuredefender/stable/low-level-collector

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jharnee/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jharnee/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


CONTAINER_IMAGE.Name | HOSTED_TECHNOLOGY.detectedByFilePaths | HOSTED_TECHNOLOGY.version | CONTAINER.Name | KUBERNETES_CLUSTER.version
-- | -- | -- | -- | --
mcr.microsoft.com/azuredefender/stable/low-level-collector@sha256:78930da7daf10b6aa71e2fd639ff4d80cbc6791300a31679b6165fb4e2bb4188 | /opt/microsoft/azuredefender/LowLevelCollector.so | 0.9.20 | microsoft-defender-low-level-collector | 1.28.9
mcr.microsoft.com/azuredefender/stable/pod-collector@sha256:f6e471e49b6f17bec1a9db19441a2b33ad94c1c1e1c00cb806ffa35465a6cbe9 | /usr/bin/app | 0.9.20 | microsoft-defender-pod-collector | 1.29.7



</body>

</html>
