### ISSUE TITLE
Default subnet size in the portal must be larger than 256 for new VNETs 

### ISSUE THREAD

**Issue by emrekenci** [Azure/AKS#456]
When you choose to create a new VNET while provisioning a new AKS cluster with in the portal, the default subnet IP range is for 255 addresses. Ex: 172.16.0.0/24

Unless you change it to a larger number, the deployment fails with error:

"Pre-allocated IPs 310 exceeds IPs available in Subnet 251"

This can be prevented by making the subnet larger. Ex: 172.16.0.0/23

This happens when I create a cluster with 10 nodes. A cluster deployment with 1 node doesn't fail with 255 address subnet.

Perhaps the required subnet size can be auto calcualated according to the number of nodes.

**Comment by jnoller** [comment]
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.

**Comment by leodotcloud** [comment]
Solution: Set `"networkPlugin": "kubenet"` instead of `azure`.
Reference: https://github.com/rancher/rancher/issues/22616#issuecomment-536903129
