### ISSUE TITLE
[service-mesh] [BUG] - Proxy Containers are not spinning up, Gatekeeper policy is preventing that the containers are with restricted capabilities

### ISSUE THREAD

**Issue by KarthikDev** [Azure/AKS#4564]
**Describe the bug**
Post installation of istio add-on, when a namespace is labelled for service mesh, then none of the deployments are spinning up when i looked at events in the namespace i can see the container is trying to spin up with capabilities which are restricted by gatekeeper policy definitions.

**To Reproduce**
1. Enable istio for a namespace
2. Ensure Azure policy has the following policy enabled for your aks cluster.  "Kubernetes cluster containers should only use allowed capabilities"
3. Create a new deployment.

**Expected behavior**
Pods should spin up with sidecar proxy container.

**Comment by biefy** [comment]
This will be resolved with #4184.

**Comment by nshankar13** [comment]
@KarthikDev we will close this as this will be resolved the Istio-CNI feature once added, as linked in above comment.
