### ISSUE TITLE
AKS node pool Autoscaling not working properly

### ISSUE THREAD

**Issue by shawnz88** [Azure/AKS#4566]
**Describe the bug**
Default autoscaling profile for node pool not scaling down nodes properly.

I have a v1.30.3 AKS cluster with a single node pool that's configured for autoscaling with default profile. Min is set to 2 and max is set to 10 for number of nodes. Currently 6 nodes are running.

The CPU utilization for each node is equal or less than 11%. Memory utilization for each node is: 60%, 58%, 48%, 41%, 33%, 28%.

**Expected behavior**
The default scale-down utilization is 50%. So node3, node4, node5 and node6 should have been scaled down and the cluster should have 2 or 3 nodes running instead of 6.

**Screenshots**
![image](https://github.com/user-attachments/assets/ae7c6f31-9dde-4957-9db6-2ef9a3cdefaf)
![image](https://github.com/user-attachments/assets/35750086-2e89-447d-8cab-08af175c2f9f)

**Environment (please complete the following information):**
 - Kubernetes version [1.30.3]

**Comment by Sagarsinghinfra360** [comment]
Hi @shawnz88 were you able to determine the cause of this issue? I am experiencing the same problem with my AKS node pools and would appreciate any insights you might have.

**Comment by Sagarsinghinfra360** [comment]
Hi @shawnz88 were you able to determine the cause of this issue? I am experiencing the same problem with my AKS node pools and would appreciate any insights you might have.
