### ISSUE TITLE
[BUG] Unable to use ephemeral OS with VM SKU Standard_E2pds_v6

### ISSUE THREAD

**Issue by jkroepke** [Azure/AKS#4597]
**Describe the bug**
I would like to setup an Node Pool with Azure Cobalt 100 CPUs, using VM SKU `Standard_E2pds_v6`. 

According to https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/memory-optimized/epdsv6-series?tabs=sizestoragelocal, ephemeral OS disk is supported and 110GB local disk is availible at minimum.

**To Reproduce**
I created a VM SKU Standard_E2pds_v6 node pool via Terraform, but I'm getting this error back:

{
  "code": "VMCannotFitEphemeralOSDisk",
  "details": null,
  "message": "The virtual machine size Standard_E2pds_v6 has a cache size of 0 bytes and temporary disk size of 0 bytes, but the OS disk requires 80530636800 bytes. Use a VM size with larger cache, larger temp disk, or disable ephemeral OS.",
  "subcode": ""
}

**Expected behavior**
It should work, like with other SKUs

**Screenshots**
N/A

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22] N/A
 - Kubernetes version [e.g. 1.24.3] 1.30.1

**Additional context**
Standard_E2pds_v6 is GA for some weeks. I guess some manually configured list somewhere needs to be updated.

**Comment by jack4it** [comment]
seeing the same issue with `D` series as well

**Comment by jkroepke** [comment]
Looks resolved.
