### ISSUE TITLE
AKS support IPv6 address.

### ISSUE THREAD

**Issue by ganrad** [Azure/AKS#460]
Have a question on AKS Adv. Networking (Azure CNI) -  Does AKS (1.9.6) support IPv6 addresses ?  Is it possible to configure IPV6 addresses for cluster n/w with Adv. Networking option (Azure CNI) in AKS ?  Per AKS docs, with Adv. networking option, the cluster nodes and the cluster n/w (Pods) share the same IP address space.  The docs also state that there is a cap on the no. of IP addresses (4096) when using Azure CNI.  Would appreciate if an AKS expert could clarify and provide more detailed information on the above.  Thanks.

**Comment by sauryadas** [comment]
Ipv6 addresses are not supported yet. On the roadmap. the limit of ip addressed in a custom vnet has increased to 16k

**Comment by phealy** [comment]
IPv6 Kubenet support is in public preview and available in all public regions: https://aka.ms/aks/ipv6
