### ISSUE TITLE
Node systemd logging not logging to /var/log/journal on initial start-up 

### ISSUE THREAD

**Issue by datwiz** [Azure/AKS#462]
The node system logging facility changes from initial boot vs subsequent OS restart.

Use case: using a fluentd daemonset with the systemd plugin to collect host log messages, such as kubelet log messages.

Actual behaviour:
On initial node start up, journald does not persist log messages to /var/log/journal and syncs to syslog
On node reboot, journald creates and logs to /var/log/journal and no longer syncs to syslog, per the config settings in /etc/systemd/journald.conf:
```
Storage=persistent
SystemMaxUse=1G
RuntimeMaxUse=1G
ForwardToSyslog=no
```

Expected behaviour:
On node initial startup journald logs per the defined configuration.

Work-around: reboot a new node once it's entered the cluster.  (Could also possibly define 2 sources in the fluentd input config.)

For my use case, log collection, I'm not fussed on which journald approach is used, I just would like a consistent approach.

**Comment by datwiz** [comment]
Update on work-around:
Restart journald service as opposed to rebooting the node.
`sudo systemctl restart systemd-journald`

**Comment by jackfrancis** [comment]
This change will make its way into AKS in the next 1-2 weeks:

https://github.com/Azure/acs-engine/pull/3348

Thanks so much for reporting and fixing!!
