### ISSUE TITLE
AKS Scaling failed

### ISSUE THREAD

**Issue by hholle** [Azure/AKS#463]
Hi,

I tried to scale a cluster today (West Europe) but it failed... any Ideas?

Deployment failed. Correlation ID: 7516b023-b19c-435c-9750-09254873ec4b. Provisioning of resource(s) for container service ********Cluster1 in resource group ******failed. Message: The value of deployment parameter 'kubernetesACIConnectorEnabled' is null. Please specify the value or use the parameter reference. See https://aka.ms/arm-deploy/#parameter-file for details.. Details:

Best

Henrik

**Comment by sauryadas** [comment]
if this is not resolved, please file a support ticket with details so we can debug.

**Comment by sauryadas** [comment]
closing this since i havent heard back
