### ISSUE TITLE
stable/prometheus helm chart has RBAC issues in AKS

### ISSUE THREAD

**Issue by jalberto** [Azure/AKS#464]
k8s 1.9.6 AKS GA

details: https://github.com/kubernetes/charts/issues/6268

**Comment by jnoller** [comment]
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
