### ISSUE TITLE
[BUG] Quatar is not europe

### ISSUE THREAD

**Issue by jkroepke** [Azure/AKS#4642]
**Describe the bug**
On the AKS Release tracker, I saw that Qatar is categorized as Europe. This is not true.

https://releases.aks.azure.com/#tabeuro

![Image](https://github.com/user-attachments/assets/fa8b34aa-5a04-402f-9f4b-bd3035a04e9f)

**Comment by AllenWen-at-Azure** [comment]
Fixed it in AKS release checker.
![Image](https://github.com/user-attachments/assets/549450cd-318f-4f54-abbd-a15fda762613)
