### ISSUE TITLE
Enable RBAC Fails -AKS Deployment - Adavnced Networking

### ISSUE THREAD

**Issue by jdogg89** [Azure/AKS#465]
I am trying to create an AKS deployment with Advanced Networking enabled along with Azure AD RBAC enabled. The cluster creates successfully but upon creation I see ""enableRbac": false" shows up. I used the instructions on the advanced networking documentation page and the page for enabling RBAC through AAD on a cluster: https://docs.microsoft.com/en-us/azure/aks/aad-integration. 

Here is the CLI input command. What needs to change to have both Advanced Networking and AAD RBAC enabled?

az aks create --resource-group Infra --name aksDev --network-plugin azure --vnet-subnet-id /subscriptions/ /resourceGroups/InfraDev/providers/Microsoft.Network/virtualNetworks/DevVnet01/subnets/DevSub02 --docker-bridge-address x.x.x.x/x --dns-service-ip x.x.x.x --service-cidr x.x.x.x/x
--generate-ssh-keys --enable-rbac \
  --aad-server-app-id \
  --aad-server-app-secret \
  --aad-client-app-id \
  --aad-tenant-id

**Comment by amanohar** [comment]
@jdogg89 I couldn't find any cluster in resource group `Infra` but did find several creates in `InfraDev`. All clusters created on June 21st or before didn't have AAD or RBAC enabled. However, I see that creates after June 21st are showing AAD enabled. Are you still running into this issue?

**Comment by jdogg89** [comment]
Thanks for checking. Rbac is enabling now, not sure why this was failing
initially. incident can be closed.
