### ISSUE TITLE
New K8S 1.10 cluster does not recognize GPU

### ISSUE THREAD

**Issue by JakobStruye** [Azure/AKS#466]
When deploying a new cluster using K8S 1.10.3 and a GPU size (e.g. NC6), the resulting K8S node does not recognize its GPU support.
Specifically, `kubectl describe node <node-name>` will not list anything GPU-related in the Capacity and Allocatable sections.
When instead deploying with K8S 1.9.6 and afterwards upgrading to 1.10.3, the node does have "alpha.kubernetes.io/nvidia-gpu" as allocatable resource.

I suspect this is due to "alpha.kubernetes.io/nvidia-gpu" being deprecated, removed and replaced by " nvidia.com/gpu" starting from 1.10: https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

**Comment by saykumar** [comment]
We have this too. Tried both `nvidia.com/gpu` and `alpha.kubernetes.io/nvidia-gpu` ... Pod stays on pending with a message about insufficient resources.

**Comment by sauryadas** [comment]
@mboersma can you please take a look at this?

**Comment by mboersma** [comment]
I can reproduce the problem as described. I'm guessing @JakobStruye is on the right track with the annotation change. I'll get this fixed.

**Comment by mboersma** [comment]
As a temporary workaround, this command seems to properly enable GPU support on an AKS 1.10.3 cluster:

```console
kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v1.10/nvidia-device-plugin.yml
```

**Comment by seanmck** [comment]
See the troubleshooting section here:

https://docs.microsoft.com/en-us/azure/aks/gpu-cluster
