### ISSUE TITLE
Node labels removed after 1.10.3 upgrade

### ISSUE THREAD

**Issue by derekperkins** [Azure/AKS#468]
After upgrading to 1.10.3, the node labels I had previously applied were all removed. Is that expected moving forwards?

**Comment by sauryadas** [comment]
This is expected as we are standing up new nodes and not doing an in place upgrade.

**Comment by derekperkins** [comment]
That may be expected from the engineering side, but certainly not from the user perspective. I have labels and taints carefully applied to nodes to make sure that my pods are running where I need them to be. If this is expected behavior, then almost every single cluster upgrade is going to cause a large percentage of my pods to either come back as unschedulable or running in locations that may be incorrect. The larger the cluster, the more impossible of a task a cluster upgrade becomes. Node names are being persisted, and so should labels + taints.

**Comment by sauryadas** [comment]
Complete agree ... i have added a WI to track fixing this issue

**Comment by sauryadas** [comment]
Can you please add this to the user voice?
https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks
We plan to track enhancements and feature requests on the forum. Thanks.

**Comment by derekperkins** [comment]
@sauryadas I understand that you are trying to move feature requests to UserVoice, but I disagree that this is an enhancement / feature request. This is a bug in the upgrade process.

**Comment by sauryadas** [comment]
Fair point @derekperkins .. will mark it as an open bug

**Comment by advishnuprasad** [comment]
Completely agree with @derekperkins. We are running AKS in production. After the upgrade, all the pods became 'pending' status. So it's more of a bug than a feature.

**Comment by mattfarina** [comment]
Need this bug fixed, too.

**Comment by gonarys** [comment]
Any update ??

**Comment by Sethu2488** [comment]
Any update??

**Comment by Sethu2488** [comment]
Is there any workaround for the node not be available post upgrading.

**Comment by gochist** [comment]
+1

**Comment by SamirFarhat** [comment]
1 year since this bug has been discovered. We will soon wish it a happy birthday. It's annoying that this has not be fixed specially with the recent Kubernetes vulnerability where all AKS deployment should be upgraded.

**Comment by jluk** [comment]
Thanks all for your patience, we've got a little more help on the team now and an active investigation going on into this. Apologies for the delay and this experience. We found the issues and are working on a proper resolution, we should have a solid ETA for fix within a week.

**Comment by martin2176** [comment]
any update on this?
I can not propose taint and toleration for a multitenant environment because of this bug I am going to hit during an upgrade.

**Comment by sauryadas** [comment]
Yes we are working on fixing both labels and taints ..... we will provide an update soon..

**Comment by martin2176** [comment]
the issue #363 tracked https://github.com/Azure/AKS/issues/363 have a direct impact.
Even if you guys resolve the upgrade issue with taints, #363 issue will make the feature unusable.
Both issues have to be resolved to make use of taint & tolerations

**Comment by jluk** [comment]
We are actively working on a fix for the node label/taint issue. Given this impacts both AKS-Engine and AKS release processes our best ETA is 4-6 weeks to get this released. Thanks for your patience on this, we'll update on this issue when completed.

Thanks @martin2176 we're looking into this issue as well, will try to get updates onto that open issue.

**Comment by jluk** [comment]
@derekperkins can you please retest this? We have made a fix and it has reached all regions to persist labels and annotations through upgrade.

We are actively working through the related taints/tolerations issue, but taints should also eventually be persisted through upgrade once that work is complete as well.

**Comment by advishnuprasad** [comment]
@jluk I have tested this by upgrading my cluster to 1.12.6. The labels are persisted in the new version. Thank you for the fix.

**Comment by jnoller** [comment]
Marking as fixed!

**Comment by jluk** [comment]
Thanks for confirm @advishnuprasad hope this helps!

**Comment by jnoller** [comment]
Closing issue; labels and annotations are now preserved.
