### ISSUE TITLE
[Document Enhancement Proposal] : Improving Azure CLI Documentation for Managing Multiple Scale Rules in Azure Container Apps

### ISSUE THREAD

**Issue by v-asen** [Azure/AKS#4687]
#### Overview

The current documentation for Azure CLI's `az containerapp update` command lacks clarity on the behavior of scaling rules management. Users face challenges when adding multiple scaling rules to an Azure Container App because every execution of the update command overwrites the existing scale section, leading to unintended loss of previously configured rules. This proposal outlines enhancements to the documentation to provide clear, actionable guidance for managing multiple scaling rules effectively using YAML configurations.

#### Enhancement Details

**Objective:**  
Enhance the Azure CLI documentation to include detailed instructions on:

1.  **Limitations**: Explicitly state the behavior of `az containerapp update` regarding the overwriting of scale rules.
2.  **Solution**: Introduce a YAML-based workflow for managing multiple scale rules.
3.  **Examples**: Provide a comprehensive example demonstrating how to export, modify, and reapply configurations to add or update multiple scaling rules.

**Key Additions to Documentation**:

-   Highlight the overwrite behavior of the `--scale-rule-*` options.
-   Introduce the `az containerapp show` command as a method to export the current configuration to YAML.
-   Provide a step-by-step guide for editing the YAML to add multiple scaling rules.
-   Include a command example for reapplying the updated YAML configuration.

#### Steps to Implement 

When working with Azure Container Apps, the  `az containerapp update`  command has a limitation where it replaces the  `scale`  section entirely with each execution. This behavior can make it tricky to manage multiple scaling rules, as adding a new rule through this command will overwrite any previously configured rules.

To address this, you can manage scaling rules effectively by using a YAML configuration file. Start by exporting the current configuration of your Azure Container App to a YAML file. This ensures that none of the existing settings or rules are lost.

```bash
az containerapp show -n sample-app -g arkorg --output yaml > containerapp-config.yaml

```

![enter image description here](https://i.imgur.com/41s7DyE.png)

Open the exported  `containerapp-config.yaml`  and locate the  `scale`  section. Modify this section to include all the scaling rules you need.

```bash
scale:
  minReplicas: 1
  maxReplicas: 10
  rules:
    - name: cron-rule
      custom:
        type: cron
        metadata:
          start: "0 0 * * *"
          end: "0 1 * * *"
          timezone: "UTC"
          desiredReplicas: "2"
    - name: memory-rule
      custom:
        type: memory
        metadata:
          type: "Utilization"
          value: "75"

```

and do  `az containerapp update -n sample-app -g arkorg --yaml containerapp-config.yaml`

![enter image description here](https://i.imgur.com/zyY6zhc.png)

![enter image description here](https://i.imgur.com/JY2dj3n.png)

At this time, Azure CLI does not support appending scale rules directly via individual commands. Every execution of  `az containerapp update`  replaces the existing  `scale`  section entirely. For now, managing scale rules through a YAML file is the most reliable approach.

#### Documentation Enhancement Justification

1.  **Clarity for Users**: Current documentation assumes users are aware of the overwrite behavior, leading to unintended configuration loss. Explicitly stating this behavior will prevent errors.

2.  **Support Cost Reduction**: Clear documentation reduces the frequency of support tickets related to scaling rule mismanagement.

#### Conclusion

Enhancing the Azure CLI documentation to address limitations in the `az containerapp update` command will provide users with a more robust understanding of how to manage scaling rules in Azure Container Apps. By incorporating YAML-based examples, troubleshooting tips, and explicit behavioral explanations, users will be better equipped to achieve their scaling goals effectively and efficiently. This proposal, if implemented, will significantly improve the usability and reliability of Azure's scaling rule management process

**Comment by sjwaight** [comment]
Hi @v-asen thanks for the detailed feedback. This repository is for feedback on Azure Kubernetes Service and not Azure Container Apps which is a different team. I'd recommend looking at the [Learn page for Container Apps Scaling](https://learn.microsoft.com/en-us/azure/container-apps/scale-app?pivots=azure-cli) and then you click on the edit icon (little pencil) in top right to open that page in edit mode on GitHub (it takes you to: https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/container-apps/scale-app.md). Hope this helps!
