### ISSUE TITLE
aks browse does not work from dockerized microsoft/azure-cli

### ISSUE THREAD

**Issue by remmeier** [Azure/AKS#469]
The following error is given:

`ERROR: Can not find kubectl executable in PATH`

It would be useful to have a kubectl bundled for a least the most important commands working or not rely on kubectl for those.

**Comment by remmeier** [comment]
note that using the az aks install-cli is not to practical as the data is gone again after the container stopped again and volume mapping the user bin directory causes further issues.

**Comment by sauryadas** [comment]
thanks for the feedback. we will add it on the roadmap. can you use cloudshell?

**Comment by seanmck** [comment]
This is expected as the `browse` command opens an SSH tunnel to port-forward from the browser. You can't do that from within the container. You will need to use the native CLI for this command.

**Comment by remmeier** [comment]
obviously one has to open that port, works perfectly fine once the docker image is fixed.

**Comment by remmeier** [comment]
you also need to change binding to 0.0.0.0, by default it binds to 127.0.0.1 and it cannot be accessed from outside the container.

**Comment by alcohol** [comment]
It would be great if one could also override the host/ip that the browse command binds to. In some scenarios (e.g. in a docker container), it would be preferable to bind to `0.0.0.0` instead of `127.0.0.1`.
