### ISSUE TITLE
portal monitoring options dont allow specifying workspace resource group

### ISSUE THREAD

**Issue by marekr** [Azure/AKS#470]
The portal's tab/step for the monitoring setup autosuggests a new workspace name. Thats fine, but if you go to create your own using the provided link, you can't choose the resource group name in the blade that opens, just name and region.

The result is names like DefaultResourceGroup-WEU for the resource group which you can't choose :/

If you create a Log Analytics resource ahead of time/separately, it lets you choose it but yea.

**Comment by jnoller** [comment]
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
