### ISSUE TITLE
No proactive confirmation on cluster deletion in portal

### ISSUE THREAD

**Issue by marekr** [Azure/AKS#471]
Many other resources ask you to type the resource name before deletion occurs. Even Apps in App service have it individually.

The kubernetes service in the portal can be deleted by a simple click :/

I would think a kubernetes cluster is serious enough to warrant some extra proactive confirmation.

**Comment by jnoller** [comment]
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.

**Comment by marekr** [comment]
Not fixed.
![image](https://user-images.githubusercontent.com/1838013/55515548-db5d6880-5638-11e9-8b05-afb393e2d374.png)

**Comment by jnoller** [comment]
Cleaned up the issue, made it explicit and assigned it the correct label https://github.com/Azure/AKS/issues/897
