### ISSUE TITLE
[Feature] Application Gateway for Containers Web Application Firewall (WAF)

### ISSUE THREAD

**Issue by jack1902** [Azure/AKS#4714]
**Is your feature request related to a problem? Please describe.**
When using Application Gateway for Containers, it would be great to enable WAF functionality like you can with the Application Gateway resource within Azure.

**Describe the solution you'd like**
The ability to use GatewayAPI within AKS, whilst being able to use WAF functionality

**Describe alternatives you've considered**
Some mental routing whereby internet traffic comes in through an AppGateway which has WAF functionality in one VNET, peered to another VNET which has a private Application Gateway for containers resource. I really don't want to have to do this as it adds alot of complexity to something that is supposed to be "simpler" compared to convention ingress (all the issues API Gateway is supposed to assist with)

**Additional context**
About 7 months ago a [comment on reddit](https://www.reddit.com/r/kubernetes/comments/1cz73wk/comment/l5irhg9/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) was posed around this, but nothing since

Relates to: https://github.com/Azure/AKS/issues/4713

Ok, can see it here in private preview as of last month https://azure.microsoft.com/en-us/updates/?id=468587

**Comment by JackStromberg** [comment]
As linked above, it's in private preview. For feature requests on Application Gateway for Containers, please use Azure feedback: https://feedback.azure.com/d365community/forum/8ae9bf04-8326-ec11-b6e6-000d3a4f0789?&c=69637543-1829-ee11-bdf4-000d3a1ab360

#please-close

**Comment by JackStromberg** [comment]
Web Application Firewall is generally available for Application Gateway for Containers now, for those that stumble across this :)
https://azure.microsoft.com/en-us/updates/?id=525419
