### ISSUE TITLE
[Question] Application Gateway for Containers Gateway API Support level

### ISSUE THREAD

**Issue by jack1902** [Azure/AKS#4716]
**Describe scenario**
Reading the Gateway API documentation around `httproutefilters` which are part of `httproutes`, i'm seeing there is a mention around "support levels" within an integrator. I'm trying to understand if Application Gateway for Containers implements `core`, `extended` or `custom`.

I'm hoping to be able to swap `ingress-nginx` over to gateway api such that two inbound paths such as `/api/somepath` or `/myapp/somepath` and send it to the backend as `/somepath` (paths are not exact here, but essentially i already do this within `ingress-nginx` via annotations `nginx.ingress.kubernetes.io/rewrite-target`)

**Question**
What support level is implemented for [HTTPRouteFilters](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRouteFilter)? I'm hoping for `extended` since i really want to be able to rewrite paths before they are sent to an upstream

**Comment by JackStromberg** [comment]
Check out this guide on URL rewrite; it has the steps on how to configure the filter to rewrite the path prior to sending it to the backend.
https://learn.microsoft.com/azure/application-gateway/for-containers/how-to-url-rewrite-gateway-api?tabs=alb-managed
