### ISSUE TITLE
Service not creating LoadBalancer

### ISSUE THREAD

**Issue by rafaelmluz** [Azure/AKS#472]
I have AKS - version 1.10.3 configured in my environment.

The yaml file creates the service called "svc-test", but is not creating loadbalancer.
See the error below.

apiVersion: v1
kind: Service
metadata:
  name: svc-test
  namespace: MY-NAMESPACE
spec:
  type: LoadBalancer
  loadBalancerIP: MY-IP-STATIC
  ports:
  - port: 80
    name: http
    targetPort: 8080
  - port: 443
    name: https
    targetPort: 8443
  selector:
    app: web
status:
  loadBalancer:
    ingress:
    - ip: MY-IP-STATIC

Normal   EnsuringLoadBalancer        25s (x6 over 3m)  service-controller  Ensuring load balancer
Warning  CreatingLoadBalancerFailed  24s (x6 over 3m)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service XXX: timed out waiting for the condition

PublicIP is within a resource group, along with the other resources in the cluster.

Has anyone had this problem?

**Comment by azzlack** [comment]
I have the same issue, are you deploying into an existing vnet?

**Comment by davidcyr** [comment]
I believe I'm having the same issue (not using an existing vnet, letting the AKS creation create a 10.0.0.0/8). I am trying to deploy a simple sample app (azure-vote.yaml) and the LoadBalancer service is just stuck in <pending> for the EXTERNAL-IP (in the kubectl get service). The 'Describe' shows the 'Ensuring load balancer' from 41m ago. I've deleted and recreated the AKS cluster in hopes the second incarnation of the cluster would work, but I have the same symptom.

**Comment by scotta01** [comment]
You need to ensure that the Cluster SPN has contributor access to the vNet you are deploying into. If you use basic networking this should already be done. If using Advanced networking it creates the vNet in the same resource group as the AKS service by default.

**Comment by rafaelmluz** [comment]
Resolved.
I re-created the Cluster and did not have the problem anymore.
