### ISSUE TITLE
AAD enabled cluster setup issue

### ISSUE THREAD

**Issue by bergerx** [Azure/AKS#479]
Recently I setup an aks cluster following https://docs.microsoft.com/en-us/azure/aks/aad-integration and passed an invalid `--aad-tenant-id` value by mistake (I passed `AAD-TENANT-ID` string as the value :( ). The cluster is setup and I installed our products with `--admin` kubeconfig and just realised the mistake when I issued an `az aks get-credentials` without `--admin` and checked my command history after `kubectl` commands are failed with below output.

```
$ kubectl get ns
E0626 09:27:22.863500   99656 azure.go:126] Failed to acquire a token: acquiring a new fresh token: initialing the device code authentication: autorest/adal/devicetoken: Error occurred while handling response from the Device Endpoint: Error HTTP status != 200
E0626 09:27:22.948121   99656 azure.go:126] Failed to acquire a token: acquiring a new fresh token: initialing the device code authentication: autorest/adal/devicetoken: Error occurred while handling response from the Device Endpoint: Error HTTP status != 200
E0626 09:27:23.061091   99656 azure.go:126] Failed to acquire a token: acquiring a new fresh token: initialing the device code authentication: autorest/adal/devicetoken: Error occurred while handling response from the Device Endpoint: Error HTTP status != 200
error: the server doesn't have a resource type "ns"
```

I'd expect the creation process to fail if invalid parameters are passed as value to the creation parameters. Or at least be able to update the parameters after the fact.

**Comment by bergerx** [comment]
Also created "Ability to change AAD related parameters on a running cluster #480"

**Comment by jnoller** [comment]
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
