### ISSUE TITLE
Set default storage class on cluster

### ISSUE THREAD

**Issue by blackbaud-brandonstirnaman** [Azure/AKS#48]
Any PersistentVolumeClaims that don't specific a storageClass will fail on a default AKS deployment because no storage classes are marked as default.

This command would fix that:
```
kubectl patch storageclass default -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'```

**Comment by depohmel** [comment]
This patch worked. 
Thanks @blackbaud-brandonstirnaman

**Comment by andyzhangx** [comment]
I also got this issue when I run `helm install stable/wordpress`, when would this issue be fixed?

**Comment by slack** [comment]
The bug was merged in build `v2017120401` and should have deployed shortly after that. Issuing an `az aks upgrade` for clusters provisioned before that date should automatically apply the update.
