### ISSUE TITLE
Ability to change AAD related parameters on a running cluster

### ISSUE THREAD

**Issue by bergerx** [Azure/AKS#480]
For AAD enabled AKS clusters created followed by https://docs.microsoft.com/en-us/azure/aks/aad-integration, is it possible to change below parameters after the cluster is created:

```
  --aad-server-app-id 7ee598bb-0000-0000-0000-83692e2d717e \
  --aad-server-app-secret wHYomLe2i1mHR2B3/d4sFrooHwADZccKwfoQwK2QHg= \
  --aad-client-app-id 7ee598bb-0000-0000-0000-83692e2d717e \
  --aad-tenant-id 72f988bf-0000-0000-0000-2d7cd011db47
```

We want to move the cluster login to a different AAD under another Azure subscription in a few weeks without losing the cluster state and the data kept within.

Is it possible to change the aad related parameters on a running cluster?

**Comment by sauryadas** [comment]
Changing AAD credentials for an existing cluster is not supported at this time.

**Comment by sauryadas** [comment]
Closing this issue for now. Will revisit this in the future.

**Comment by ArWeder** [comment]
@sauryadas Let's say the _server-app-secret_ expired, and we want to update it. There is no way to do it ?
