### ISSUE TITLE
Error getting logs from pods in kube-system namespace

### ISSUE THREAD

**Issue by ducas** [Azure/AKS#481]
When trying to get logs for a pod running in kube-system namespace I get an error. Eg -

    $ kubectl logs cluster-autoscaler-[identifier] -n kube-system
    error: You must be logged in to the server (the server has asked for the client to provide credentials ( pods/log cluster-autoscaler-[identifier]))

This was working up to a point today... While I was testing out the cluster autoscaler I received a connection error (which I've lost the message for) and since then I've been getting this. It's recently been upgraded to v1.10.

**Comment by ams0** [comment]
Exactly the same error, also testing the cluster-autoscaler, happened after the first 1->2 scale operation. Seems related to https://github.com/kubernetes/kubernetes/issues/63128 but how to renew certs in AKS?

**Comment by sakthi-vetrivel** [comment]
I'm also having the same issue when using the cluster-autoscaler on AKS. After the nodes scale, seem to lose authorization to communicate with kube-apiserver.

**Comment by sauryadas** [comment]
@shrutir25 need to investigate this . we have a cluster with this error if you want to debug

**Comment by jnoller** [comment]
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
