### ISSUE TITLE
aks create with service principal gives "ERROR: Directory permission is needed for the current user to register the application"

### ISSUE THREAD

**Issue by pwsuperstar** [Azure/AKS#483]
I'm trying to create an AKS resource with a service principal with the contributor role. 

Users are allowed to create app registrations in the subscription, so i dont know what other permissions that needs to be granted to the service principal? And how those permissions should be added to the service principal? 

![image](https://user-images.githubusercontent.com/21296226/41981216-aacf1976-7a28-11e8-8914-47ba9a39581b.png)

Commands used are:
az login --service-principal -u serviceUser -p servicePassword --tenant mytenant
az aks create -g resourceGroupName --name k8name --location westeurope --generate-ssh-keys --no-wait

Error message from aks create:
ERROR: Directory permission is needed for the current user to register the application. For how to configure, please refer 'https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal'. Original error: Insufficient privileges to complete the operation.

**Comment by shahiddev** [comment]
How did you create the service principal? Is it scoped to a resource group or subscription?

**Comment by liliankasem** [comment]
Having the exact same issue, the SP I created is scoped to the subscription

**Comment by wat-izz** [comment]
:+1:

**Comment by jnoller** [comment]
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
