### ISSUE TITLE
Services wtih type loadbalancer stuck on pending

### ISSUE THREAD

**Issue by Grigsuv** [Azure/AKS#486]
I've created test cluster for first time,everything works fine,then when I created new one in another location and with advanced networking,but type of  loadbalancer services get stuck on pending but i use the same configuration files(yaml). What can I do?

**Comment by ducas** [comment]
Start with:
    kubectl get events

Then try looking at the activity log on the resource group that contains the VMs. If you created a public load balancer service then it should be trying to create an ELB names kubernetes and a public IP in the resource group. If it was internal just an ILB named kubernetes-internal (or similar).

Similar thing happened to me and I found it was because either the service principle didn’t have authorization to create something or I hit the public IP address limit for my subscription.

**Comment by Grigsuv** [comment]
kubectl get events 

1m          3h           44        api         Service               Normal    EnsuringLoadBalancer   service-controller   Ensuring load balancer

I*n activity log only this operation ` Get Managed Cluster AccessProfile by List Crednetial

**Comment by Grigsuv** [comment]
Is there any solution?

**Comment by IanMoroney** [comment]
Depending on the number of public IP addresses you have in your load balancer, you may be hitting the public IP address limit (10 by default in the LB).
You can raise a support request to get the load balancer limit increased from 10 to 30. Public IP addresses should then automatically provision without you needing to recreate the services.

**Comment by IanMoroney** [comment]
To confirm this, search the kube-controller-manager log for events similar to:
`External error while updating load balancer: network.LoadBalancersClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LoadBalancerFrontendIPConfigurationCountLimitReached" Message="A load balancer cannot have more than 10 FrontendIPConfigurations." Details=[].`

**Comment by Grigsuv** [comment]
@sauryadas  this way?

`apiVersion: v1
kind: Service
metadata:
  name: osrm
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP 
      port: 5412
      targetPort: 3500
  selector:
    app: osrm
---

**Comment by Grigsuv** [comment]
I tried to add service principles as contributer to my cluster,I get endpoints but there is no response from server

**Comment by sauryadas** [comment]
do you see logs similar to what ian points out above?

**Comment by Grigsuv** [comment]
I had similar logs before adding service principles

**Comment by pcnayak** [comment]
How do you add a SP to an existing AKS cluster?

**Comment by jnoller** [comment]
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
