### ISSUE TITLE
Node goes down momentarily when deploying

### ISSUE THREAD

**Issue by vcorr** [Azure/AKS#488]
We have started to experience a node going down (NotReady) for about a 1 minute every time we issue helm upgrade on a deployment. 

kubectl describe lists the following warning
`Failed to update Node Allocatable Limits "": failed to set supported cgroup subsystems for cgroup : Failed to set config for supported subsystems : failed to write 2000171008 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/memory.limit_in_bytes: invalid argument`

After about a minute the node is back to ready state and the upgrade is successful, though with a delay.

The node is of type Standard_B1ms, which I believe is no longer supported as a node type - could this be the reason for this behaviour?

**Comment by CecileRobertMichon** [comment]
Hi @vcorr, this is a known issue that has been fixed already. You can try to a) upgrade your cluster to apply the fix or b) apply the following mitigation steps on each node: 1.	Add “--cgroups-per-qos=true --enforce-node-allocatable=pods” (without quota) to KUBELET_CONFIG lines in /etc/default/kubelet, 
2.	restart kubelet service by “systemctl restart kubelet”.

**Comment by vcorr** [comment]
Thanks for the info!, we ended up creating a new cluster with bigger VM size and I assume the issue won't return as the nodes are now brand new.
