### ISSUE TITLE
Client IP not preserved with Advanced Networking and externalTrafficPolicy: Local

### ISSUE THREAD

**Issue by tkubica12** [Azure/AKS#495]
**Expected behavior**
When Service of type NodePort or LoadBalancer is deployed with externalTrafficPolicy: Local, Service does respond only on nodes that run selected Pods and directs traffic only to local instances while not doing source NAT so client IP is preserved.

**Using Advanced Networking (Azure CNI)**
Service correctly responds only on nodes with Pod deployed and route traffic only locally within a node. But it still does source NAT so client IP is replaced with Node IP.

**Using Standard Networking**
Service does local routing only + does not do source NAT so client IP is preserved.

Tested with 1.9.6 and 1.10.3

**Comment by JunSun17** [comment]
This is dupe of #607, it has been fixed now.
