### ISSUE TITLE
LoadBalancer IPs list order changed

### ISSUE THREAD

**Issue by jalberto** [Azure/AKS#497]
rel: #487 

So my Load balancer IPs was yesterday:
1. x.x.x.x
2. y.y.y.y

Today it is:
1. y.y.y.y
2. x.x.x.x

Meaning every service that I whitelisted with x.x.x.x is now not working

**Comment by rite2nikhil** [comment]
Can you please send your cluster info (subscription id, resource group, resource id) to aks-gh-feedback@service.microsoft.com

**Comment by jnoller** [comment]
Closing as solved/fixed/stale.
