### ISSUE TITLE
Not all agents are in Ready state in UK West

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/AKS#5]
Not all of the agents are being provisioned properly.

The VM is running and the Custom Script extension is in provision succeeded status.

Correlation ID:  20bbfe25-8d91-45e0-9e1d-7f0bebd60d77

```bash
az group create --name test-aks --location ukwest
az aks create -n myApp -g test-aks -c 5 -s Standard_D2_v2
az aks get-credentials --name myApp -g test-aks
kubectl get nodes
```
```
NAME                        STATUS           AGE       VERSION
aks-agentpool1-24428535-0   Ready,agent      12m       v1.7.7
aks-agentpool1-24428535-1   Ready,agent      12m       v1.7.7
aks-agentpool1-24428535-2   Ready,agent      12m       v1.7.7
aks-agentpool1-24428535-3   Ready,agent      12m       v1.7.7
aks-agentpool1-24428535-4   NotReady,agent   9m        v1.7.7
```

Some of the pods are in NodeLost status and I believe these are tied to the agent that is in NotReady.
```
kubectl get pods --all-namespaces
```

```
NAMESPACE     NAME                                    READY     STATUS     RESTARTS   AGE
kube-system   heapster-3596479800-q79t7               2/2       Running    0          10m
kube-system   kube-dns-v20-1654923623-0s07h           3/3       Running    0          10m
kube-system   kube-dns-v20-1654923623-q73v1           3/3       Running    0          10m
kube-system   kube-proxy-6fv8p                        1/1       Running    0          10m
kube-system   kube-proxy-fzl9f                        1/1       Running    0          10m
kube-system   kube-proxy-lvt7w                        1/1       Running    0          10m
kube-system   kube-proxy-lzbbq                        1/1       Running    0          10m
kube-system   kube-proxy-v9mqk                        0/1       NodeLost   0          8m
kube-system   kube-svc-redirect-0nb76                 1/1       Running    0          10m
kube-system   kube-svc-redirect-4cvm9                 1/1       Running    0          10m
kube-system   kube-svc-redirect-cqh4p                 1/1       Running    0          10m
kube-system   kube-svc-redirect-h8r24                 0/1       NodeLost   0          8m
kube-system   kube-svc-redirect-ss5bn                 1/1       Running    0          10m
kube-system   kubernetes-dashboard-3427906134-fjsfw   1/1       Running    0          10m
kube-system   tunnelfront-2j5md                       1/1       Running    0          10m
kube-system   tunnelfront-2pscj                       0/1       NodeLost   0          8m
kube-system   tunnelfront-7ds8w                       1/1       Running    0          10m
kube-system   tunnelfront-rzwp5                       1/1       Running    1          10m
kube-system   tunnelfront-sc6gg                       1/1       Running    0          10m
```
Dashboard info:

![image](https://user-images.githubusercontent.com/16688027/32033613-67c82946-b9db-11e7-9305-fd1e84dc952e.png)

![image](https://user-images.githubusercontent.com/16688027/32033630-8a5ad184-b9db-11e7-9eda-4b8ee04d47ef.png)

**Comment by seanknox** [comment]
Can you open an ICM ticket for this? Want to make sure this gets full review from the AKS team.

**Comment by SenthuranSivananthan** [comment]
Thanks Sean.  I've created the case and asked for it to be routed to AKS team.

**Comment by colemickens** [comment]
:( Kubelet really probably shouldn't be getting stuck here. This isn't first time I've seen this. I suspect an upstream bug in kubelet since it's not retrying. (Maybe already be affected by the external cloud provider work ongoing).

**Comment by SenthuranSivananthan** [comment]
Short term fix is to reboot the VMs that are in NotReady status.

**Comment by khenidak** [comment]
@SenthuranSivananthan - can you please post kubelet logs here?

**Comment by SenthuranSivananthan** [comment]
@khenidak, [kubelet.log](https://github.com/Azure/AKS/files/1423874/kubelet.log)
attached.

**Comment by khenidak** [comment]
Thanks.. to keep you informed. a couple of things i noticed

1. hyperkube was downloaded twice
2. Kubelet was in fact able to connect to master (judging by the fact that you have kube-system/* containers running). 
3. The failure seems to be happening against azure own resource manager endpoint. the node is consistently fails to connect to ARM until it restarts. this is where i will be focusing on.  There could be a number of factors involved (I will assume that RG/NSG/Node Config is standard deployment? no customization made?)

A simple exercise to conduct is, instead of restarting the node let us restart kubelet.

```
#on a failed node
sudo systemctl restart kubelet
```

Wait until loads up again.

**Comment by SenthuranSivananthan** [comment]
1.  Yes it’s the standard deployment through CLI. No customizations and I have full ownership of the subscription.  

2. I’ll build a new cluster and test right now. Post back soon on results with just restarting kubelet.

**Comment by SenthuranSivananthan** [comment]
@khenidak ```sudo systemctl restart kubelet``` worked.  The node is now in Ready status.

**Comment by davideicardi** [comment]
Some problem here. After a scale operation (`az aks scale`) from 2 to 3, the new node appears as `NotReady`. After a manual reboot of the VM it is now `Ready`.
Error message is exactly the same: `failed to get external ID from cloud provider`

**Comment by slack** [comment]
Closing this issue, please open new issues if you continue to see problems.

**Comment by ajinkyarajput** [comment]
Still get this error in westeurope. First, all nodes are in "Ready" state, then some of them in "NotReady".
