### ISSUE TITLE
Unable to connect to pods via kubectl

### ISSUE THREAD

**Issue by Remper** [Azure/AKS#50]
I have an issue similar to #14 – cluster is up, pods are deployed (although had to do this multiple times due to image pull errors) but kubectl can't access pods via proxy, cp or exec:

```
remper@Azure:~$ az aks get-credentials --resource-group rs-frame-cluster --name frame-cluster
Merged "frame-cluster" as current context in /home/remper/.kube/config
remper@Azure:~$ kubectl get pods
NAME                                 READY     STATUS    RESTARTS   AGE
flink-jobmanager-870122904-t6mmf     1/1       Running   0          36m
flink-taskmanager-3831602672-8wffh   1/1       Running   0          36m
flink-taskmanager-3831602672-dfkt7   1/1       Running   0          36m
remper@Azure:~$ kubectl exec -it flink-jobmanager-870122904-t6mmf -- /bin/bash
Error from server: error dialing backend: dial tcp 10.240.0.4:10250: getsockopt: connection timed out
```

Everything was working perfectly yesterday.
Is it a known issue? Will it be fixed?

**Comment by frankbuckley** [comment]
What do you see from `kubectl get pods --all-namespace`?

Every attempt I have made to create a cluster today ends up with something like:

	$ kubectl get pods --all-namespace
	NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE
	kube-system   heapster-58f795c4cf-6n6zf               2/2       Running            0          12m
	kube-system   kube-dns-v20-6c8f7f988b-jmmbb           3/3       Running            0          12m
	kube-system   kube-dns-v20-6c8f7f988b-ppw7s           3/3       Running            0          12m
	kube-system   kube-proxy-j8kr5                        1/1       Running            0          11m
	kube-system   kube-svc-redirect-56j8m                 0/1       CrashLoopBackOff   6          11m
	kube-system   kubernetes-dashboard-6fc8cf9586-n5gfm   0/1       CrashLoopBackOff   6          12m
	kube-system   tunnelfront-d7b8c8b45-hdzlc             1/1       Running            0          12m

And then:

	$ az aks browse --resource-group xxxx-5 --name xxxx-5-1
	Merged "xxxx-5-1" as current context in C:\Users\xxxx\AppData\Local\Temp\tmp5qi2xs6n
	Proxy running on http://127.0.0.1:8001/
	Press CTRL+C to close the tunnel...
	error: error upgrading connection: error dialing backend: dial tcp 10.240.0.4:10250: getsockopt: connection timed out

**Comment by Remper** [comment]
It finally started working for me. Not sure if it is luck or the underlying issue has been resolved.

@frankbuckley the current output (with proxy/exec/cp working) is:
```
NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE
default       flink-jobmanager-870122904-xb6q1        1/1       Running            0          19m
default       flink-taskmanager-3831602672-233d6      1/1       Running            0          19m
default       flink-taskmanager-3831602672-zx8df      1/1       Running            0          19m
kube-system   heapster-2888171832-km65c               2/2       Running            0          42m
kube-system   kube-dns-v20-1654923623-s66n1           3/3       Running            0          42m
kube-system   kube-dns-v20-1654923623-zx7qz           3/3       Running            0          42m
kube-system   kube-proxy-4rjps                        1/1       Running            0          42m
kube-system   kube-proxy-ngrcl                        1/1       Running            0          42m
kube-system   kube-svc-redirect-5gp2m                 0/1       CrashLoopBackOff   12         42m
kube-system   kube-svc-redirect-5nh0v                 1/1       Running            16         42m
kube-system   kubernetes-dashboard-1672970692-kpdw7   0/1       Error              12         42m
kube-system   tunnelfront-743380097-cw3x8             1/1       Running            0          42m
```

**Comment by frankbuckley** [comment]
@Remper Can you `az aks browse` reliably?

**Comment by frankbuckley** [comment]
Seems to be working OK today.

	$ kubectl get pods --all-namespaces
	NAMESPACE     NAME                                                      READY     STATUS    RESTARTS   AGE
	default       ingress-1-nginx-ingress-controller-6879787bb8-7qfl7       1/1       Running   0          3m
	default       ingress-1-nginx-ingress-default-backend-6d7bdd987-6jljd   1/1       Running   0          21m
	kube-system   heapster-75667786bb-cbrzg                                 2/2       Running   0          27m
	kube-system   kube-dns-v20-6c8f7f988b-brz9j                             3/3       Running   0          28m
	kube-system   kube-dns-v20-6c8f7f988b-mwm5l                             3/3       Running   0          28m
	kube-system   kube-proxy-prrsz                                          1/1       Running   0          28m
	kube-system   kube-svc-redirect-z2shw                                   1/1       Running   0          28m
	kube-system   kubernetes-dashboard-6fc8cf9586-lhcm7                     1/1       Running   0          28m
	kube-system   tiller-deploy-5b9d65c7f-pdvqj                             1/1       Running   0          22m
	kube-system   tunnelfront-7669c6dc8c-67rbm                              1/1       Running   0          28m

**Comment by philipz** [comment]
@fadykhoury I got these error messages.

$ az aks browse -g aks -n aks
Merged "aks" as current context in /tmp/tmpkeyxr6gh
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
error: error upgrading connection: error dialing backend: dial tcp 10.240.0.6:10250: getsockopt: connection timed out

**Comment by sgoings** [comment]
There have been a bunch of fixes rolling out to prod to fix this + related issues over the last month or so. Feel free to open another issue if something crops up again!
