### ISSUE TITLE
Azure network plugin: pod can't access itself via its service IP

### ISSUE THREAD

**Issue by jim-minter** [Azure/AKS#500]
With the azure network plugin, a pod listening on a TCP port (say 8080), and a service fronting that pod:

1. The pod CAN connect back to itself via localhost:8080
2. The pod CAN connect back to itself via \<pod-ip>:8080
3. The pod CAN NOT connect back to itself via \<service-ip>:8080

Point 3 is a problem: this should be possible.

Other notes:

The node itself, as well as other pods in the system CAN connect correctly to \<service-ip>:8080.
Point 3 works correctly with the kubenet network plugin, it is the azure network plugin that is at fault.

**Comment by jim-minter** [comment]
@khenidak @ritazh fyi - this prevents us from using the azure network plugin.

**Comment by jim-minter** [comment]
@pweil- @kargakis @mjudeikis fyi

**Comment by jim-minter** [comment]
https://github.com/Azure/azure-container-networking/issues/91 and https://github.com/Azure/azure-container-networking/issues/167 look pretty similar to this.

**Comment by sharmasushant** [comment]
ack! we will look.

**Comment by sharmasushant** [comment]
Change to address this got merged: https://github.com/Azure/azure-container-networking/pull/248

**Comment by jnoller** [comment]
closing as stale.
