### ISSUE TITLE
Service can´t be reach

### ISSUE THREAD

**Issue by mobius127** [Azure/AKS#502]
Hi there,

I´m using AKS 1.10.3 version.

I have an mvc application running normally, but when I deploy an api rest service, when I try to access via HTTP, the result is 404.

This is MVC deploy config:
`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerapp-deployment
  labels:
    app: dockerapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerapp
  template:
    metadata:
      labels:
        app: dockerapp
    spec:
      containers:
      - name: dockerapp
        image: [ACR]/dockerapp:20180702105618
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: [secret]
---
apiVersion: v1
kind: Service
metadata:
  name: dockerapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dockerapp
`

And Rest service deploy config:
`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerservice-deployment
  labels:
    app: dockerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerservice
  template:
    metadata:
      labels:
        app: dockerservice
    spec:
      containers:
      - name: dockerservice
        image: [ACR]/dockerservice:20180705071355
        ports:
        - containerPort: 6379
      imagePullSecrets:
      - name: [secret]
---
apiVersion: v1
kind: Service
metadata:
  name: dockerservice
spec:
  type: LoadBalancer
  ports:
  - port: 6379
  selector:
    app: dockerservice
`

![image](https://user-images.githubusercontent.com/16031601/42318250-b4d56872-804e-11e8-9b29-7f6eefb04b9e.png)

![image](https://user-images.githubusercontent.com/16031601/42318434-50f0c17a-804f-11e8-9932-360866ff969f.png)

Anyone can help?

**Comment by rite2nikhil** [comment]
Please check your NSG rules if it is blocking the requests on this port. Please re-open if this still repros
