### ISSUE TITLE
Ingress stops getting Endpoint with Advance networking & HTTP application routing

### ISSUE THREAD

**Issue by dave-hillier** [Azure/AKS#508]
I've got a cluster created around ~19 days (at least that's my oldest ingress). At some point it stopped assigning Endpoints to my ingresses. 

I created a new cluster with the same setup and applied the same charts. They work.

I was able to reproduce this using the [party-clippy](https://docs.microsoft.com/en-us/azure/aks/http-application-routing) example.

I note that my old cluster's DNS zone has a GUID name with dashes. The new one does not have dashes -- I'm guessing this is some change that has been deployed that has broken old clusters.

Manually adding the DNS entries momentarily worked, until the extension removed them.

**Comment by yaakov-h** [comment]
Possibly related to #437.

**Comment by dave-hillier** [comment]
I upgraded the cluster to 1.10.3 and now these ingresses have endpoints assigned.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
