### ISSUE TITLE
az interactive doesn't know much about aks

### ISSUE THREAD

**Issue by mlda065** [Azure/AKS#513]
`az interactive` seems unaware of a lot of options.

* `az aks create --d` doesn't have a prompt for `--disable-rbac`. I think that flag is ignored by the AKS backend anyway, but `az` error messages claim it's an option.
* `az install-connector --resource-group $AZ_RG --name ` doesn't give you a prompt for the list of AKS clusters in that resource group (or the list of all clusters)
* `az install-connector --l` doesn't give `--location` as a prompt. This means that it seems like there's no way to specify location. I kept getting error messages about how the location must be `southeastasia`, but when I try to create a new cluster, `southeastasia` is not a region. This is really confusing. Once I figured out that there is indeed a `--location` argument, it made a lot more sense.

**Comment by sauryadas** [comment]
@yugangw-msft  can you please address these issues?

**Comment by yugangw-msft** [comment]
@sauryadas , can you please confirm `az install-connector` and `az aks create --disable-rbac` are indeed azure cli commands/flags. I can't find them in the latest cli

**Comment by sauryadas** [comment]
@yugangw-msft  @mboersma can confirm that these are indeed azure cli commands. 

@mlda065 --network-plugin does not support calico yet

**Comment by mlda065** [comment]
I didn't expect calico to work.

When I saw `--network-plugin` as an option, I was surprised. `az interactive` didn't tell me what the options are, and that doesn't sound like it matches anything in the Portal. So I assumed it was for Calico, Flannel, Weave etc.

The lack of prompt for that is not a huge issue. I'm just letting you know.

**Comment by mboersma** [comment]
@yugangw-msft  in the current `az` CLI `az aks install-connector --location` and `az aks create --disable-rbac` are valid options.`--debug

There *is* interactive tab-completion for the `--disable-rbac` argument, but it probably collides with `--debug`, `--dns-name-prefix`, `--dns-service-ip`, and `--docker-bridge-address` so it's behaving badly. There isn't tab-completion support for the `az aks install-connector` command options, but we can add that. Ditto for `--network-plugin` prompting.

**Comment by mlda065** [comment]
I can confirm that there is now a prompt for `--disable-rbac`. Great!

**Comment by mboersma** [comment]
I think we've updated and fixed everything described here except the `az aks install-connector` tab completion. I created an issue to track fixing that at Azure/azure-cli#6978.
