### ISSUE TITLE
update image and status is always pending

### ISSUE THREAD

**Issue by dasuma** [Azure/AKS#516]
hi

i was update my images for my services AKS but today dont working 

![image](https://user-images.githubusercontent.com/7833341/42525198-2a52eaba-8438-11e8-8d06-d2faa00566db.png)

the state always is pending 

any solution?

**Comment by sauryadas** [comment]
We have no understanding of what you are running in that container. Have you tried looking at the logs? kubectl logs pod?

**Comment by mboersma** [comment]
@dasuma it's hard to know from that information whether this is an AKS or Kubernetes issue, or if it's application-specific. Could you send logs and details with subscription ID, resource group name, Azure region, and cluster name to aks-help@service.microsoft.com so we can investigate further?
