### ISSUE TITLE
Cluster lost one of the nodes and does not recover

### ISSUE THREAD

**Issue by katerinapsperm** [Azure/AKS#519]
AKS, kubernetes version 1.9.6
3 nodes Standard F4s_v2 series
We used the cluster almost 2 month. What was going on with the cluster by the end of the 2nd month:

1. At first cluster lost heapster, its pod coutinued with 'CrashLoopBackOff'
2. One of the nodes reported DiskPressure with the following warning in 'Events': 
`Warning  ImageGCFailed  4m (x3491 over 12d)  kubelet, aks-nodepool1-38432401-1  (combined from similar events): wanted to free 2622756454 bytes, but freed 0 bytes space with errors in image deletion: rpc error: code = Unknown desc = Error response from daemon: conflict: unable to delete da86e6ba6ca1 (cannot be forced) - image is being used by running container ed7ff6e6a44e`

We could not ssh into the nodes to check kubelet logs as a new pod with ssh tunnel could nod be started, stuck in 'ContainerCreating' state. By the way all the services that has already been set up in the cluster ran fine.
Despite the facts all the nodes were in 'Ready' state.

3. In few days another node (not the one experiencing disk pressure) reported 'NotReady' state, has nothing in 'Events' and is not recovering after that. The cluster is gone.
Logs from that node:
![image](https://user-images.githubusercontent.com/20163288/42557592-9db42874-84f7-11e8-9c4a-4e6fb98a323f.png)

The state of all the pods:
![image](https://user-images.githubusercontent.com/20163288/42557457-48bcf634-84f7-11e8-9a88-2540dc39713b.png)
 
This is not the first time when we are losing one of the nodes. Always pretty much the same symptoms. In addition its important to say that we do not allocate too many pods and those do not request too many resources, everything is under reasonable limits of the VMs series type. 

Please tell me if i can provide more information on the issue.

**Comment by qike-ms** [comment]
Please email aks-gh-feedback@microsoft.com with the following info:
1. subscriptionID
2. resource group
3. cluster name

**Comment by katerinapsperm** [comment]
aks-gh-feedback@microsoft.com - Recipient address rejected, may be some other e-mail to contact?

**Comment by katerinapsperm** [comment]
ping

**Comment by rite2nikhil** [comment]
@katerinapsperm  Please send the info @ aks-help@service.microsoft.com

**Comment by katerinapsperm** [comment]
@rite2nikhil send, thanks!

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
