### ISSUE TITLE
Start/Stop Cluster - Support zero node clusters

### ISSUE THREAD

**Issue by bacongobbler** [Azure/AKS#52]
As a user of AKS, I would like to scale the node count in the node pool down to zero. This will allow me to "shut down" all operations running in the cluster without having to purge the cluster of any configuration. It would also be useful as a "hard reset" tool for all the nodes running in the cluster.

Currently when I try this, I see the following error message:

```
$ az aks scale -c 0
Parameter 'ContainerServiceAgentPoolProfile.count' must be greater than 1.
```

**Comment by Plasma** [comment]
This would be great for dev/test/staging environments.

**Comment by mboersma** [comment]
I see the use case here, but business reasons might make this a bad idea for us. A 0-node AKS clusters uses Azure resources for the control plane but charges the customer nothing. AKS provides great value for users, but I don’t think 0-node clusters are economically feasible. I’d love to be argued out of this point of view, however.

**Comment by bacongobbler** [comment]
Completely agree from the economical business perspective. Closing this. :)

**Comment by sdktr** [comment]
maybe the control plane resources / manager 'nodes' of AKS could be shut down when the said scale of 0 workers is requested? If all that's left to keep is the statefull part of the cluster data then only a small storage fee for which the customer could be billed a storage account for is left?

If you have any other tips for easy dev/test/study k8s setups that can be paused or quickly backuped/restored based on AKS I'm all ears.

**Comment by sherland** [comment]
This is "even more" relevant when you introduce node pools (as noted in #79 'az aks scale' should be able to scale #of linux and windows nodes)

Being able to easily add/remove capacity on different kinds of nodes for load balancing++ would be a great feature.

**Comment by mboersma** [comment]
Good points. I didn't mean to close the door on this *forever*, just to set expectations that this isn't something we plan to implement for the GA release of AKS.

**Comment by msdotnetclr** [comment]
For my test cluster, I just use scripts to turn the only worker node off for off-hours and turn it on when needed. It isn't as nice as scaling to 0 nodes, but effectively I am doing the same thing.

**Comment by sdktr** [comment]
Thanks for sharing! Without you mentioning it, I'd assume that aks would auto remidiate as if the node was failed (eg start a new one).
Where do you launch these scripts from? Just your own workstation of some fancy azure automation?

**Comment by msdotnetclr** [comment]
@sdktr I am using Azure automation. Just follow this: https://docs.microsoft.com/en-us/azure/automation/automation-solution-vm-management

I hope Microsoft allows scaling down to zero, it would be much easier...

**Comment by levidehaan** [comment]
At my clients company we have a Very strict security policy that doesn't allow the creation of resource groups. So we need to Pre-Create the AKS clusters with all the diff VM sizes and scale them to 0 to be scaled up later by clients in the company who want to use AKS. 

Right now I have a script to shut down the node after the creation of a cluster, and that keeps it to no or very low cost until we actually need it.

if we could scale to 0 that would solve a lot of issues, and also we could be more secure knowing our workaround might not be "fixed" later down the road.

**Comment by barryit** [comment]
Do other cloud vendors (AWS or Google) provide this capability?

**Comment by ablekh** [comment]
@barryit Not sure about AWS, but GCP / GKE does, indeed, provide this capability.

**Comment by ptemmer** [comment]
+1
We're moving from GKE to AKS, and were using that feature for our different development clusters

**Comment by AceHack** [comment]
Would really like this feature for ACI

**Comment by albertocsm** [comment]
+1

**Comment by xenalite** [comment]
Seems there is an easy solution - just charge a customer for the control plane.

**Comment by yves-vogl** [comment]
@levidehaan No offense, but maybe the fix for this would be to make the security guys read "Phoenix Project" and probably teach them that IT alignment is meant bidirectional in 2018.

**Comment by ablekh** [comment]
@mboersma Given the feedback above and recent industry trends, perhaps, you (Azure/Microsoft) could reconsider your stance on this issue. After all, if Digital Ocean can offer their managed K8s product (now GA) with the control plane being free of charge, I'm pretty sure that Microsoft can afford that as well. ;-)

**Comment by giggio** [comment]
This is also important now that Virtual Nodes are GA. I'd love to be able to create clusters that use virtual nodes only, which will allow me to forget about scaling nodes and leave it all to k8s.

**Comment by zeroX-tj** [comment]
We also have the issue that we would like a second node pool for jobs. So when there is no work the pool should be scaled down to 0. We used it like this on GCP.

I understand that this can't be allowed for clusters with only 1 nodepool. But this essential for the setup I have. Using ACI is also not an option since these machines are limited in memory.

**Comment by michael-burt** [comment]
I would really like to see this feature. It is already supported on GKE and EKS and we use it extensively there. The only workaround I have come up with at AKS is to delete the node pool and then rebuild it when I need to use it again... luckily I already had to write this functionality because AKS (unlike EKS and GKE) also does not support vertically scaling the node pools.

I think you guys should really reconsider your stance and aim for feature parity with the other providers.

**Comment by jnoller** [comment]
We are evaluating options for scaling to zero after we complete the committed roadmap items listed here: https://github.com/Azure/AKS/projects/1 when we have further line of sight on how and when, we will add this card to the roadmap linked for tracking.

**Comment by michael-burt** [comment]
Thanks. I am glad to see API server ingress and multi-AZ support on there.

**Comment by mlushpenko** [comment]
We are using another hack right now - for clusters with multiple node pools, we shutdown the first node and add [protection](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-instance-protection) from scaling down to that node due to this [behaviour]( https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#if-i-have-stopped-deallocated-a-vm-is-that-vm-started-as-part-of-an-autoscale-operation). Shutting down of the first node is needed because we can't have a node pool of size zero.

So, considering people are already coming up with hacks to make it work and Azure still pays for control plain, why not make it easier for everyone and promote Azure as a good competitor to GKE 
instead of giving reasons why it's not possible?

Sorry if I sound blunt, but it's happening already, you may as well make good use of it.

**Comment by duckie** [comment]
Yes @mlushpenko, agree 100% with you, this is a real pain for service providers that would like to leverage AKS but gets roasted by customers because of this specific issue.

**Comment by dror-weiss** [comment]
@xenalite , I agree, but with a very logical change. 

If the node count is at least 1 the masters should cost nothing just like the current offering, but when the nodes count is set to zero the customer should pay for keeping the masters alive.

For our use case, this is the optimal solution. We use GPU-based node (expensive VMs), and forcing us to pay for the control plane will cost much less than keeping a single node in the air and not pay for the control plane.

**Comment by nirp123** [comment]
**+1**

**Comment by kaancfidan** [comment]
We need this functionality in our use-case too. 

We are currently running multiple node pools in AKS and one of those contains GPU instances (NCv3) and they are quite costly. The GPU workload is only expected during work hours and I would like to be able to scale it down to 0 (while keeping the scales of the other nodepools non-zero) during night and scale it up again using a cronjob before work hours.

Maybe you could limit the "default" node pool to have non-zero node count and let the others be scaled down to zero?

**Comment by mlushpenko** [comment]
@kaancfidan my previous comment was hidden as maintainers found it disturbing, so not sure if you can see it. I'll put "constructive part" of my post here, I think you can use it, for now, to achieve what you want.


> We are using another hack right now - for clusters with multiple node pools, we shutdown the first node and add [protection](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-instance-protection) from scaling down to that node due to this [behaviour]( https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#if-i-have-stopped-deallocated-a-vm-is-that-vm-started-as-part-of-an-autoscale-operation). Shutting down of the first node is needed because we can't have a node pool of size zero.

So, what we are doing manually for a single node per node pool, you could put in a cron job.

**Comment by kaancfidan** [comment]
> @kaancfidan my previous comment was hidden as maintainers found it disturbing, so not sure if you can see it. I'll put "constructive part" of my post here, I think you can use it, for now, to achieve what you want.
> 
> > We are using another hack right now - for clusters with multiple node pools, we shutdown the first node and add [protection](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-instance-protection) from scaling down to that node due to this [behaviour](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#if-i-have-stopped-deallocated-a-vm-is-that-vm-started-as-part-of-an-autoscale-operation). Shutting down of the first node is needed because we can't have a node pool of size zero.
> 
> So, what we are doing manually for a single node per node pool, you could put in a cron job.

@mlushpenko Thanks for the pointer. Although I do not like to manually manage node status in a k8s environment, this might be a good workaround for the time being.

**Comment by mlushpenko** [comment]
@kaancfidan our prod cluster has 4 node pools, 3 of them with this hack and autoscaling enabled, works well so far, but we have less than 10 nodes in total and running it in production for a bit more than a month, so can't say too much about stability.

**Comment by sekikatsu36** [comment]
I contacted MS support desk with this question. They told me that the number of nodes couldn't be set to zero yet and requested feedback from the request site.

So I made the following post:
https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/39377356-support-zero-node-clusters

I link it to this issue. I look forward to supporting zero-node clusters.

**Comment by ondrejhlavacek** [comment]
I understand the business view so I like the idea that there would need to be running at least a minimum required nodes in the default node pool. All other node pools should be able to have the minimum count set to 0 as mentioned here https://github.com/Azure/AKS/issues/52#issuecomment-567841535. 

Our use case is very similar, we launch hosted Jupyter notebooks on demand (using very expensive nodes) and I don't like paying for one when there's no running Jupyter notebook. And we can't even charge the customer and have to pay this out of our pocket. 

All other resources are in other node pools (including default) and I'm okay paying $50/mo for one or two simple nodes to run the required cluster pods.

**Comment by mikepw** [comment]
I have a use case for a JIT vm that would reduce deploy time if the cluster could remain at zero until the instance(s) are needed.

**Comment by palma21** [comment]
AKS currently supports scaling to 0 every pool except the system pool, which can be kept at a minimum. All other user pools can scale to zero. This month we'll also support autoscaling from and to 0.

By August 2020 AKS will allow as well the capability to stop/start the cluster which will stop/start all it's nodes in a supported manner.

We believe these should meet most the use cases of this issue, but let us know!

I've seen a few asks around virtual nodes in 0 node clusters. Today virtual nodes required an actual node to run the aci pod, but the ACI is working on this scenario. It probably might make sense to keep that one in its own item.

**Comment by rogelioamancisidor** [comment]
@palma21  is this supported in kubernetes 1.17.7? I can see that when I add a new nodepool I can set it to `user`, but the parameter --min-count cannot be set to 0

**Comment by palma21** [comment]
are you using the extension CLI or main CLI? And could you share the versions?

**Comment by rogelioamancisidor** [comment]
it should be the main CLI, and the version is azure-cli 2.5.1. Should I update it to 2.9.1?

**Comment by palma21** [comment]
You'll need to use the latest CLI extension (aks-preview) until the next main CLI is released when this is GA.

Let me know how that goes.

I didn't answer in my previous reply but this should work for any supported kuberntes version on AKS.

**Comment by rogelioamancisidor** [comment]
ok. I have added the extension `aks-preview` now. Then I tried to add a new nodepool like like this `az aks nodepool add --resource-group mygrpname --cluster-name myclustername --name myname --node-vm-size Standard_NV6_Promo --min-count 0 --max-count 1 --node-count 1 --enable-cluster-autoscaler --mode user` and got the error message `agentPoolProfile.minCount is invalid`

**Comment by palma21** [comment]
sorry I missed the parameter you placed there. You added --min-count and I read --count

--min-count will set it for the autoscaler. You can scale to 0 not autoscale to 0.

As I mentioned above
> AKS currently supports scaling to 0 every pool except the system pool, which can be kept at a minimum. All other user pools can scale to zero. **This month we'll also support autoscaling from and to 0.**

Autoscaler doesn't support autoscale to and from 0 today in Azure yet, because there are a lot of edge cases upstream and we chose to instead of supporting it with those edge cases, to actually fix those before claiming it is supported.
eg. of one is the case where you have pods using label selectors and affinity and you are at 0 nodes and the CA restarts, it will loose the template and won't know that pool is candidate to scale anymore.

We are fixing all those cases in the upstream code so we can support scale to 0 with no caveats. The ETA for that is this month as per above.

Bear with us just a little longer :)

**Comment by spygi** [comment]
@palma21 thanks for the updates. Just to double check, stopping the cluster will incur 0 costs for the users right ( not even for the system nodes)? And if you were to start it again that would be faster than creating it from scratch I assume?

**Comment by DreamRivulet** [comment]
@palma21   May i know whether scaling to 0 is supported in cluster autoscaler now ?

**Comment by palma21** [comment]
@spygi Yes, the only nominal can be the OS disks (storage) which also won't exist if you use ephemeral. Or the Public IP costs if you are maintaining them (or not using UDR). No costs for VM compute/cores.

Updates for CA on #1565

I'll rename this to start/stop to reflect the current discussion and allow each individual point to be addressed on its respective issues.

**Comment by ryedin** [comment]
is this GA yet? 

CLI v 2.11.1 -> `Operation failed with status: 'Bad Request'. Details: The value of parameter agentPoolProfile.count is invalid.` when attempting to scale to 0

**Comment by palma21** [comment]
https://docs.microsoft.com/en-us/azure/aks/start-stop-cluster
