### ISSUE TITLE
AKS failed to provision in WestUS, works (sometime) for CentralUS, any known issues?

### ISSUE THREAD

**Issue by joelsjolly** [Azure/AKS#523]
Deployment error when trying to deploy WestUS
{ "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "ControlPlaneNotReady", "message": "{\n \"error\": {\n \"code\": \"ControlPlaneNotReady\",\n \"message\": \"Pods not in Running status: etcd-5b4769fb144af80001251fff-0001,kube-addon-manager-7d5c696668-qs97v\"\n },\n \"category\": \"InternalError\"\n }" } ] } }

**Comment by qike-ms** [comment]
This meant it timed out while waiting for all control plane pods to be ready. Try to use az aks to interact with the cluster. If it works, it's fine. If not, please delete the cluster and retry creation.

**Comment by mboersma** [comment]
There isn't any service outage or provisioning problem specific to WestUS that we know of. I'm going to close this issue since it's a month old, but please re-open if problems continue.
