### ISSUE TITLE
Slow Response Time

### ISSUE THREAD

**Issue by maganuk** [Azure/AKS#524]
I deployed two Kubernetes clusters, one on Google Cloud (1 vCPU, 4GB Memory) with 2 nodes and the other cluster on Azure Container Service (B2MS) with 2 nodes. 

I deployed the same container on both clusters. The app connects to a Azure SQL database, and both clusters are in Europe. 

The response time on the Google Cloud cluster is extremely swift (80-100ms), whereas the same endpoint on azure has a response time of 2-3 seconds (sometimes more). They are both configured using the same yaml file. Am I doing something wrong?

**Comment by vdice** [comment]
We believe we've identified the issue and have a fix intended for rollout this week.  (See https://github.com/Azure/AKS/issues/522) 

Pre-existing clusters will need manual patching, however.  cc @rite2nikhil @khenidak
