### ISSUE TITLE
Unable to change VM Size after cluster creation

### ISSUE THREAD

**Issue by edernucci** [Azure/AKS#529]
After creating the cluster we realized that we would need a VM with higher RAM capacity. The need was solved by resizing the VM using Azure CLI. After this change we noticed that Azure has classified our cluster as faulty and does not allow us any more changes (like upgrading kubernetes).

Changing the size of one or more VMs is a basic need and it is not acceptable to have to re-create the cluster so that it can be updated.

In GKE (implementation of Google managed Kubernetes) the solution to this was the creation of pools of VMs, where we can choose the amount of pool VMs and the size of the VMs of this pool.

It would be important to us that the Azure solution would respond in the same or similar way, at the very least allowing the size of the VMs to be changed manually.

**Comment by qike-ms** [comment]
We are working on supporting multiple agent pool.

**Comment by edernucci** [comment]
@qike-ms Nice to hear! Do we have an ETA?

**Comment by seanmck** [comment]
Should be within the next couple of months. You can track the feature here:

https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/34917127-support-multiple-node-pool

**Comment by jageshmaharjan** [comment]
Still not yet? I could not change the VM size still.
```
Requested operation cannot be performed because the VM size Standard_D2_v3 does not support the storage account type Premium_LRS of disk
```

**Comment by qike-ms** [comment]
You can add a new node pool with new VM size, then cordon and drain old
node pool
