### ISSUE TITLE
AKS: Timeout while polling for control plane provisioning status.

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/AKS#53]
I cannot deploy AKS clusters in Westeurope, all of the deployments fail with the error: Timeout while polling for control plane provisioning status.

**Comment by DaveAurionix** [comment]
I get the same error when deleting a cluster too (still westeurope).  Have raised a support request with Microsoft.

**Comment by bramvdklinkenberg** [comment]
I raised a support call as well. Got feedback that more people have the same the issue and they are investigating it

**Comment by azzlack** [comment]
Yep, we have the same issue as of 16.00 CET

**Comment by azzlack** [comment]
Worked for me just now.
Used the command `az aks create --resource-group Hub --name bkhub-cluster --node-count 1 --node-vm-size Standard_D1_v2 --dns-name-prefix bkhub --kubernetes-version=1.8.1 --generate-ssh-keys`

**Comment by bramvdklinkenberg** [comment]
works again

**Comment by bottydim** [comment]
I have the same issue, westeurope again. Deployment failed. Correlation ID: a9e84e85-a25b-4140-b3c6-d35d1b359504. Timeout while polling for control plane provisioning status. 

Cannot create, neither delete.

**Comment by TallOrderDev** [comment]
Having this issue today as well.

**Comment by ThijsBorst** [comment]
Also having this issue today

**Comment by bramvdklinkenberg** [comment]
having issues since friday again with rolling out aks clusters

**Comment by leonardocastanodiaz** [comment]
Same issue in EASTUS, I was using terreform and the creation process ended after an hour with an error that says 

`: azure#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
`
