### ISSUE TITLE
portal node status has stopped working

### ISSUE THREAD

**Issue by marekr** [Azure/AKS#530]
Overall 7 days
![image](https://user-images.githubusercontent.com/1838013/42725222-27a95e66-874e-11e8-94e8-e181b8d3c841.png)

And then last day

![image](https://user-images.githubusercontent.com/1838013/42725217-1a1daaae-874e-11e8-9c9d-40e0a0aa221e.png)

I have noticed the cluster connectivity is weirdly intermittent for kubectl, but I haven't touched anything that should affect that.
The nodes are running though.

**Comment by marekr** [comment]
Updated to 1.10.5 from 1.10.3 just for the hell of it (not expecting ndoe status to change)

And it's gone from working to being intermittent from time of upgrade when it was blank for the last 2 days.

![image](https://user-images.githubusercontent.com/1838013/42816540-322a94b6-8999-11e8-8e74-dc40565d70f9.png)

**Comment by sauryadas** [comment]
Thanks for the feedback. There are some issues with rendering the portal graph. We are looking to fix this. 

If kubectl get nodes is returning nodes in ready state and you are able to deploy pods that should suffice. you can also check the overall health of nodes and pods if you have azure monitoring enabled.

cc @jenetlan  FYI

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
