### ISSUE TITLE
AKS RBAC - Debugging 

### ISSUE THREAD

**Issue by iandvt** [Azure/AKS#535]
I've followed the on-boarding instructions for [Integrate Azure Active Directory with AKS](https://docs.microsoft.com/en-us/azure/aks/aad-integration) with partial success. Any advice on how to triage the Azure CLI AAD callback coming back with the the following error?

Unable to connect to the server: acquiring a token for authorization header: acquiring a new fresh token: waiting for device code authentication to complete: autorest/adal/devicetoken: Error while retrieving OAuth token: Unknown Error

<img width="830" alt="screen shot 2018-07-16 at 4 52 22 pm" src="https://user-images.githubusercontent.com/25870869/42789185-b1215ab0-8918-11e8-9295-29c344c2f7e9.png">

**Comment by dstrebel** [comment]
Typically this means that it doesn't have permission... Did you click on the "Grant Permissions" in the portal UI when setting up the app registration? It's not totally clear from the documentation and can easily be missed.

**Comment by iandvt** [comment]
For a sanity test - I deleted my AKS cluster, my resource group, my AAD Applications, and went through this entire process again. Unfortunately, I hit the exact same error. 

What would be the next course of action for me? Is this worth opening up a Azure Ticket?

**Comment by weinong** [comment]
closing the issue as there has no response. please reopen if the issue persists.

**Comment by sowsan** [comment]
Any idea how to fix this ? I'm hitting the same issue in multiple environments. Opened another issue here https://github.com/Azure/AKS/issues/638

**Comment by przemolb** [comment]
@borstibacon where does the documentation say that it has to be the "native" mode ?

**Comment by przemolb** [comment]
@borstibacon I found it in the picture ... We have the same problem and I don't remember what type did we use. Is there any way I can check it now ?

**Comment by AndyWu7623** [comment]
@przemolb you can found it under Azure Active Directory > App registration and check "Application Type"

**Comment by borstibacon** [comment]
@przemolb 
Actually you need 2 app registrations: one native and one webapp/api. 
Follow the documentation, this works well:

https://docs.microsoft.com/en-us/azure/aks/aad-integration?view=azure-cli-latest

**Comment by przemolb** [comment]
@borstibacon According to the documentation the server is `Web app/API` and the client is `Native`. We made a mistake and did both `Web app/API`.

**Comment by yves-vogl** [comment]
Other than in the documenation I was able to use Guest Users (Azure B2B Collaboration). In my case the Guest Users were member of a local group. So maybe you just cannot give role bindings to Guest Users directly.

**Comment by TheAzureGuy007** [comment]
**Quick Fix:** is to go to aad client manifest file and changed the value of property "allowPublicClient": true, from null
