### ISSUE TITLE
AKS with AAD authentication in service

### ISSUE THREAD

**Issue by programmersommer** [Azure/AKS#539]
I have deployed AKS with nginx-ingress. Everything is working fine except one thing.
My docker service has AAD authentication. Just to clarify - I mean just authentication. I am not talking about AAD access to Kubernetes. 
My AKS ingress is using LetsEncrypt for SSL certificate creation. More or less everything is done based on this article: [HTTPS Ingress on Azure Kubernetes Service (AKS)](https://docs.microsoft.com/en-us/azure/aks/ingress).

In my Azure account in Active Directory App Registration I have reply URL set to
https://mycustomname-ingress.westeurope.cloudapp.azure.com/signin-oidc
(sure, there is something else instead of mycustomname, -that's just an example)

But when I am trying to login I receive: "AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx'."
That is probably because of URL contains "redirect_uri=http%3A%2F%2Fmycustomname-ingress.westeurope.cloudapp.azure.com". HTTP - not HTTPS. If change reply URL in AAD to http scheme, then would be another exception: "Correlation failed".

I have tried different ingress options, and also have published [topic on SO](https://stackoverflow.com/questions/51258599/kubernetes-and-aad-authentication).

**How to reproduce it (as minimally and precisely as possible)**: You can create ASP.NET Core application with AAD authentication, publish it to docker container and deploy to ACS. Deploy AKS and ingress. And try to login by Kubernetes URL.

**Environment**:
- Kubernetes version: 1.9
- Size of cluster (how many worker nodes are in the cluster?): 3
- General description of workloads in the cluster: ASP.NET Core app
- Others: I have tried different Kubernetes versions

**Comment by felipecrestani** [comment]
@programmersommer any update on this? I have the same issue.

**Comment by felipecrestani** [comment]
I solved using nginx.ingress.kubernetes.io/proxy-buffer-size: "32k" in the ingress yml.

**Comment by programmersommer** [comment]
@felipecrestani that doesn't work in my case. Can you please provide some more details?

**Comment by felipecrestani** [comment]
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: datamanageringress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    **nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"**
spec:
  tls:
  - hosts:
    - customer.neogrid.com
    secretName: aks-ingress-tls
  rules:
  - host: customer.***.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cmddatamanagerservice
          servicePort: 80

**Comment by programmersommer** [comment]
In my case that is probably OAuth issue. As I know from helpdesk it is not yet supported and team is working on it now.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.

**Comment by programmersommer** [comment]
For those, who might be interested. Problem wasn't solved. I have decided not to use nginx as ingress. Instead I am using now Load balancer. Soon it would be possible to use Azure Application Gateway Ingress Controller
