### ISSUE TITLE
Unable to configure aggregation layer & kube controller manager [AKS]

### ISSUE THREAD

**Issue by mfaizanse** [Azure/AKS#54]
Hi,
I am trying to setup horizontal pod autoscaling using custom-metrics. For [support of custom metrics](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-custom-metrics) in kuberenetes 1.8.1, we need to [enable the aggregation layer](https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/), setting the following flags in kube-apiserver:
```
--requestheader-client-ca-file=<path to aggregator CA cert>
--requestheader-allowed-names=aggregator
--requestheader-extra-headers-prefix=X-Remote-Extra-
--requestheader-group-headers=X-Remote-Group
--requestheader-username-headers=X-Remote-User
--proxy-client-cert-file=<path to aggregator proxy cert>
--proxy-client-key-file=<path to aggregator proxy key>
```

One of the possible way to set these flags was by editing the yaml of kube-apiserver-xxx pod but when I run:
kubectl get po -n kube-system
I get no pod for kube-apiserver neither for kube controller manager.

What is the possible way to set these flags in aks? 

I also deployed prometheus adapter for custom metrics but the pod logs showed me the following error:
`panic: cluster doesn't provide requestheader-client-ca-file`
You can see the exact requirements in configuration section in this [link](https://github.com/kubeless/kubeless/tree/master/manifests/autoscaling). 

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tgarlot** [comment]
Hi,

Having a similar question to activate RBAC (not sure if it's activate by default...) : How to configure the api server without having access to a master node? 

thanks

**Comment by slack** [comment]
Aggregated API support was merged just before Kubecon. Should be available for clusters created after v2017120402, or any cluster that has been upgraded since then!

@tgarlot as AKS is a managed offering, we don't support arbitrary modification of api-server flags.

**Comment by derekperkins** [comment]
@mfaizanse Were you able to get HPA working with custom metrics on AKS?

**Comment by mfaizanse** [comment]
@derekperkins At time time, I didn't get it working but now as @slack is mentioning that aggregated API support is merged, so it should be working now but I haven't tried it again yet.
