### ISSUE TITLE
Change default VM size to 2 CPU cores at least in azure portal of creating AKS cluster page

### ISSUE THREAD

**Issue by andyzhangx** [Azure/AKS#541]
**What happened**:
As I could see in azure portal, when creating an AKS cluster, the default VM size is `Standard DS1 v2 (1 vcpus, 3.5 GB memory)`,  actually according to my [investigation](https://github.com/Azure/AKS/issues/166), VM size with 1 core would have issue, the system is very slow, could you change default VM size to 2 CPU cores at least, e.g. `Standard D2s v3 (2 vcpus, 8 GB memory)`

Moreover, I think we should remove all VM size with 1 CPU core in AKS support list.

@slack 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by AaronFriel** [comment]
I don't think 1-cpu nodes should be forbidden, it's easy to imagine they could be useful as a non-primary node pool.

**Comment by zqingqing1** [comment]
Can you put your suggestion in the voice link [https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks] to see how people is thinking about this?
