### ISSUE TITLE
Allow Secrets to be stored inside Key Vault

### ISSUE THREAD

**Issue by uday31in** [Azure/AKS#543]
Allow Following properties to be stored inside KV.
```
"aadProfile": {
					"serverAppID": "[parameters('serverAppID')]",
					"ServerAppSecret": "[parameters('ServerAppSecret')]",
					"clientAppID": "[parameters('clientAppID')]",
					"tenantID": "[parameters('tenantID')]"
				},
"servicePrincipalProfile": {
					"ClientId": "[parameters('servicePrincipalClientId')]",
					"Secret":  "[parameters('servicePrincipalClientSecret')]"
                }
```

Using KV ref- deployment fails with following error despite spec allows it at least for servicePrincipalProfile.secret

https://github.com/Azure/azure-resource-manager-schemas/blob/9f722c074baa6c54d272f292f56ffce5f1d464b4/schemas/2018-03-31/Microsoft.ContainerService.json#L197 

 "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "NodesNotReady",
        "message": ""
      }
    ]
  }

**Comment by weinong** [comment]
AKS does not support `keyVaultSecretRef`. It's a bug in AKS swagger.

That being said, passing secure value in Keyvault in template deployment should work. Have you tried that?
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-keyvault-parameter

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
