### ISSUE TITLE
Redeploy tunnelfront after NodeLost

### ISSUE THREAD

**Issue by mbrancato** [Azure/AKS#544]
I've been able to reproduce (not by choice) a couple times where a high load (memory pressure) on a node will cause a NodeLost scenario. I can recover the node and cluster, but the cluster sometimes (maybe 2 out of 3, I'm not *trying* to discover this) will never function correctly again because `tunnelfront` will continue to fail liveness probes. 

In some cases, deleting the pod will fix it when the pod is recreated. But often it does not, and I'm unsure of the cause. I think the liveness probe times out after 12 minutes, and we've seen this happen several times giving plenty of time for the recovery to occur.

I think there needs to be a way to redeploy the `tunnelfront` on both ends. I've found exactly one way to fix this issue: rebuild the cluster.

Symptoms of `tunnelfront` being down include `kubectl logs` and `kubectl exec` do not work.

**Comment by rite2nikhil** [comment]
Can you please send your sub id, resource group, cluster name to aks-gh-feedback@service.microsoft.com

I can take a look

**Comment by duncanhealy** [comment]
I have experienced this in AKS 1.10.3 (fixed by upgrading to version 1.10.5)

Nodes went down similarly with high memory load in 1.10.5 but Tunnelfront was fine

**Comment by mbrancato** [comment]
I haven't had this issue in some time. I'm not sure the cause, but I can't duplicate so I will close this.
