### ISSUE TITLE
Lets encrypt not working with aks built in ingress "http-01 self check failed for domain"

### ISSUE THREAD

**Issue by digeler** [Azure/AKS#547]
**What happened**:
trying to pull certificate from acme without success getting : http-01 self check failed for domain

**What you expected to happen**:
Certificate to be issued automatically 

**How to reproduce it (as minimally and precisely as possible)**:
1. Create aks cluster latest version with ingress enabled.
2. follow this guide but skip the ingress part : https://docs.microsoft.com/en-us/azure/aks/ingress
3. do describe for your cert you will get : 

order:
        challenges:
        - authzURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/sU-CDor6V4A2hUNfYw2z3Gy8GO8Wquvfn3ytFfBafe8
          domain: dinor-aks-ingress.eastus.cloudapp.azure.com
          http01:
            ingress: ""
            ingressClass: nginx
          key: Ru7pdomoJOdJpa9i_WoMoBQj0Fb5KsWv_1HWJ-c5btQ.HFMuLxSwBvaSORgxvoHtr15c9n0SztWia3vJeq3Zcuk
          token: Ru7pdomoJOdJpa9i_WoMoBQj0Fb5KsWv_1HWJ-c5btQ
          type: http-01
          url: https://acme-staging-v02.api.letsencrypt.org/acme/challenge/sU-CDor6V4A2hUNfYw2z3Gy8GO8Wquvfn3ytFfBafe8/150697087
          wildcard: false
        url: https://acme-staging-v02.api.letsencrypt.org/acme/order/6495063/4378848
    conditions:
    - lastTransitionTime: 2018-07-20T09:11:16Z
      message: http-01 self check failed for domain "dinor-aks-ingress.eastus.cloudapp.azure.com"
      reason: ValidateError
      status: "False"
      type: Ready
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Anything else we need to know?**:

all the details below 

**Environment**:
NAME                       STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-agentpool-29387319-0   Ready     agent     1h        v1.10.5   <none>        Ubuntu 16.04.4 LTS   4.15.0-1013-azure   docker://1.13.1
aks-agentpool-29387319-1   Ready     agent     1h        v1.10.5   <none>        Ubuntu 16.04.4 LTS   4.15.0-1013-azure   docker://1.13.1

- Kubernetes version (use `kubectl version`):1.11.1
- Size of cluster (how many worker nodes are in the cluster?)2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) : only the builtin ingress.
- Others:

ingress description  : 
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  creationTimestamp: 2018-07-20T08:09:43Z
  generateName: addon-http-application-routing-nginx-ingress-controller-86c64d8967-
  labels:
    app: addon-http-application-routing-nginx-ingress
    pod-template-hash: "4272084523"
  name: addon-http-application-routing-nginx-ingress-controller-86njwgg
  namespace: kube-system
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: addon-http-application-routing-nginx-ingress-controller-86c64d8967
    uid: 42827d9d-8bf4-11e8-9bcb-8eda67e25ab2
  resourceVersion: "3817"
  selfLink: /api/v1/namespaces/kube-system/pods/addon-http-application-routing-nginx-ingress-controller-86njwgg
  uid: 4284316c-8bf4-11e8-9bcb-8eda67e25ab2
spec:
  containers:
  - args:
    - /nginx-ingress-controller
    - --ingress-class=addon-http-application-routing
    - --default-backend-service=$(POD_NAMESPACE)/addon-http-application-routing-default-http-backend
    - --configmap=$(POD_NAMESPACE)/addon-http-application-routing-nginx-configuration
    - --tcp-services-configmap=$(POD_NAMESPACE)/addon-http-application-routing-tcp-services
    - --udp-services-configmap=$(POD_NAMESPACE)/addon-http-application-routing-udp-services
    - --annotations-prefix=nginx.ingress.kubernetes.io
    - --publish-service=$(POD_NAMESPACE)/addon-http-application-routing-nginx-ingress
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: quayio.azureedge.net/kubernetes-ingress-controller/nginx-ingress-controller:0.13.0
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 10254
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: addon-http-application-routing-nginx-ingress-controller
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 10254
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: addon-http-application-routing-nginx-ingress-serviceaccounmhvks
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: aks-agentpool-29387319-1
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: addon-http-application-routing-nginx-ingress-serviceaccount
  serviceAccountName: addon-http-application-routing-nginx-ingress-serviceaccount
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: addon-http-application-routing-nginx-ingress-serviceaccounmhvks
    secret:
      defaultMode: 420
      secretName: addon-http-application-routing-nginx-ingress-serviceaccounmhvks
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-07-20T08:10:03Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-07-20T08:12:57Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-07-20T08:09:59Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://a2dac425684d77556c34434e7450e84686ffb33354deb169a69431865eacc37a
    image: quayio.azureedge.net/kubernetes-ingress-controller/nginx-ingress-controller:0.13.0
    imageID: docker-pullable://quayio.azureedge.net/kubernetes-ingress-controller/nginx-ingress-controller@sha256:8f3a3bf373e64d8b29e502faf58dd1b212ceb2a69627ccc1add5b9aca24e273b
    lastState:
      terminated:
        containerID: docker://92919f33180482537d661c55a806b37a0a9fef87c7a71067b17cb433cb0c8706
        exitCode: 143
        finishedAt: 2018-07-20T08:11:48Z
        reason: Error
        startedAt: 2018-07-20T08:11:09Z
    name: addon-http-application-routing-nginx-ingress-controller
    ready: true
    restartCount: 1
    state:
      running:
        startedAt: 2018-07-20T08:12:31Z
  hostIP: 10.240.0.4
  phase: Running
  podIP: 10.244.1.2
  qosClass: BestEffort
  startTime: 2018-07-20T08:10:03Z

certificate yaml : 
apiVersion: v1
items:
- apiVersion: certmanager.k8s.io/v1alpha1
  kind: Certificate
  metadata:
    clusterName: ""
    creationTimestamp: 2018-07-20T08:49:44Z
    generation: 1
    name: tls-secret
    namespace: default
    resourceVersion: "7385"
    selfLink: /apis/certmanager.k8s.io/v1alpha1/namespaces/default/certificates/tls-secret
    uid: d92a79b7-8bf9-11e8-9bcb-8eda67e25ab2
  spec:
    acme:
      config:
      - domains:
        - dinor-aks-ingress.eastus.cloudapp.azure.com
        http01:
          ingress: ""
          ingressClass: nginx
    commonName: ""
    dnsNames:
    - dinor-aks-ingress.eastus.cloudapp.azure.com
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt-staging
    secretName: tls-secret
  status:
    acme:
      order:
        challenges:
        - authzURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/sU-CDor6V4A2hUNfYw2z3Gy8GO8Wquvfn3ytFfBafe8
          domain: dinor-aks-ingress.eastus.cloudapp.azure.com
          http01:
            ingress: ""
            ingressClass: nginx
          key: Ru7pdomoJOdJpa9i_WoMoBQj0Fb5KsWv_1HWJ-c5btQ.HFMuLxSwBvaSORgxvoHtr15c9n0SztWia3vJeq3Zcuk
          token: Ru7pdomoJOdJpa9i_WoMoBQj0Fb5KsWv_1HWJ-c5btQ
          type: http-01
          url: https://acme-staging-v02.api.letsencrypt.org/acme/challenge/sU-CDor6V4A2hUNfYw2z3Gy8GO8Wquvfn3ytFfBafe8/150697087
          wildcard: false
        url: https://acme-staging-v02.api.letsencrypt.org/acme/order/6495063/4378848
    conditions:
    - lastTransitionTime: 2018-07-20T09:11:16Z
      message: http-01 self check failed for domain "dinor-aks-ingress.eastus.cloudapp.azure.com"
      reason: ValidateError
      status: "False"
      type: Ready
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

certmanager log  : 
I0720 09:04:13.557682       1 ingress.go:33] Looking up Ingresses for selector certmanager.k8s.io/acme-http-domain=1872892092,certmanager.k8s.io/acme-http-token=1309937331
I0720 09:04:13.557717       1 helpers.go:188] Found status change for Certificate "tls-secret" condition "Ready": "False" -> "False"; setting lastTransitionTime to 2018-07-20 09:04:13.55771309 +0000 UTC m=+2704.316999882
I0720 09:04:13.557743       1 sync.go:261] Error preparing issuer for certificate default/tls-secret: http-01 self check failed for domain "dinor-aks-ingress.eastus.cloudapp.azure.com"
E0720 09:04:13.557759       1 sync.go:182] [default/tls-secret] Error getting certificate 'tls-secret': secret "tls-secret" not found
E0720 09:04:13.581317       1 controller.go:186] certificates controller: Re-queuing item "default/tls-secret" due to error processing: http-01 self check failed for domain "dinor-aks-ingress.eastus.cloudapp.azure.com"
I0720 09:05:13.581635       1 controller.go:177] certificates controller: syncing item 'default/tls-secret'
I0720 09:05:13.581731       1 sync.go:259] Preparing certificate default/tls-secret with issuer
I0720 09:05:13.581738       1 acme.go:162] getting private key (letsencrypt-staging->tls.key) for acme issuer default/letsencrypt-staging
I0720 09:05:13.582090       1 logger.go:27] Calling GetOrder
I0720 09:05:13.704726       1 logger.go:52] Calling GetAuthorization
I0720 09:05:13.802228       1 logger.go:72] Calling HTTP01ChallengeResponse
I0720 09:05:13.802267       1 prepare.go:263] Cleaning up old/expired challenges for Certificate default/tls-secret
I0720 09:05:13.802280       1 logger.go:47] Calling GetChallenge
I0720 09:05:13.949395       1 http.go:122] wrong status code '404'
I0720 09:05:13.949583       1 ingress.go:33] Looking up Ingresses for selector certmanager.k8s.io/acme-http-domain=1872892092,certmanager.k8s.io/acme-http-token=1309937331
I0720 09:05:13.949617       1 helpers.go:188] Found status change for Certificate "tls-secret" condition "Ready": "False" -> "False"; setting lastTransitionTime to 2018-07-20 09:05:13.949612847 +0000 UTC m=+2764.708899639
I0720 09:05:13.949645       1 sync.go:261] Error preparing issuer for certificate default/tls-secret: http-01 self check failed for domain "dinor-aks-ingress.eastus.cloudapp.azure.com"
E0720 09:05:13.949660       1 sync.go:182] [default/tls-secret] Error getting certificate 'tls-secret': secret "tls-secret" not found
E0720 09:05:13.972285       1 controller.go:186] certificates controller: Re-queuing item "default/tls-secret" due to error processing: http-01 self check failed for domain "dinor-aks-ingress.eastus.cloudapp.azure.com"
I0720 09:06:13.972604       1 controller.go:177] certificates controller: syncing item 'default/tls-secret'
I0720 09:06:13.972708       1 sync.go:259] Preparing certificate default/tls-secret with issuer
I0720 09:06:13.972715       1 acme.go:162] getting private key (letsencrypt-staging->tls.key) for acme issuer default/letsencrypt-staging
I0720 09:06:13.973928       1 logger.go:27] Calling GetOrder
I0720 09:06:14.223623       1 logger.go:52] Calling GetAuthorization
I0720 09:06:14.321125       1 logger.go:72] Calling HTTP01ChallengeResponse
I0720 09:06:14.321170       1 prepare.go:263] Cleaning up old/expired challenges for Certificate default/tls-secret
I0720 09:06:14.321183       1 logger.go:47] Calling GetChallenge
I0720 09:06:14.468967       1 http.go:122] wrong status code '404'
I0720 09:06:14.469067       1 ingress.go:33] Looking up Ingresses for selector certmanager.k8s.io/acme-http-domain=1872892092,certmanager.k8s.io/acme-http-token=1309937331
I0720 09:06:14.469112       1 helpers.go:188] Found status change for Certificate "tls-secret" condition "Ready": "False" -> "False"; setting lastTransitionTime to 2018-07-20 09:06:14.469107385 +0000 UTC m=+2825.228394177
I0720 09:06:14.469127       1 sync.go:261] Error preparing issuer for certificate default/tls-secret: http-01 self check failed for domain "dinor-aks-ingress.eastus.cloudapp.azure.com"
E0720 09:06:14.469141       1 sync.go:182] [default/tls-secret] Error getting certificate 'tls-secret': secret "tls-secret" not found
E0720 09:06:14.493507       1 controller.go:186] certificates controller: Re-queuing item "default/tls-secret" due to error processing: http-01 self check failed for domain "dinor-aks-ingress.eastus.cloudapp.azure.com"

help appriciated.

**Comment by weinong** [comment]
Quoting @brendandburns from internal thread

> Let's encrypt doesn't work for the azure.com domain you need to use your own .tld and root domain.
> 
> We should probably add that to the docs if it's not already there.
> 
> --brendan

**Comment by weinong** [comment]
assign to @sauryadas for doc update

**Comment by sauryadas** [comment]
@iainfoulds Can you please update the docs to indicate the let's encrypt doesn't work for azure.com domain ?

**Comment by iosif-koidis** [comment]
I tried with an azure.com domain following this guide https://docs.microsoft.com/en-us/azure/aks/ingress reading the comment above I tried with a custom domain name of mine but still the only thing I get is 

 Conditions:
    Last Transition Time:  2018-07-26T06:53:15Z
    Message:               http-01 self check failed for domain "domain-deducted"
    Reason:                ValidateError
    Status:                False
    Type:                  Ready
Events:
  Type    Reason       Age   From          Message
  ----    ------       ----  ----          -------
  Normal  CreateOrder  29m   cert-manager  Created new ACME order, attempting validation...

Do you have any recommendations? 

Thank you in advance

**Comment by digeler** [comment]
i managed to fix the issue here is the full guide : 
https://github.com/digeler/letsencrypt-application-routing-aks

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
