### ISSUE TITLE
Deployment fails when Role Assignment already exists

### ISSUE THREAD

**Issue by amandadebler** [Azure/AKS#548]
**What happened**: Cluster creation failed because Role Assignment failed; RoleAssignmentExists

**What you expected to happen**: Cluster creation to succeed, with perhaps a warning about the existing Role Assignment; choose another Role Assignment identifier if the default one is already in use

**How to reproduce it (as minimally and precisely as possible)**:
1) Create cluster named ClusterA in ResourceGroupA, using vnet VNetA and SubnetA, with ServicePrincipalA
2) Delete ClusterA; wait until fully removed
3) Repeat 1

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.5
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Not that far along
- Others:

I was able to create a cluster with the exact same settings after I deleted the Contributor RoleAssignment for that service principal from the Users section of the target subnet.

**Comment by khenidak** [comment]
@weinong FYI

There is a an on going bug with CLI that it attempts to re-assign roles. Until we can get this fixed. Please try using arm template deployments. Apologies.

**Comment by weinong** [comment]
Yes, it's a cli bug.

@khenidak @amandadebler i think we can have option to skip the role assignment to the subnet as some customers may want to a narrower role or even custom role. Thoughts?

**Comment by amandadebler** [comment]
@weinong We would *love* to have the option to skip the role assignment, because right now, I can't create a cluster unless I'm an *Owner* of the Resource Group that the vnet (and subnet) is in, and our security team is really not happy about that.

**Comment by amandadebler** [comment]
@khenidak I encountered this error when using the Portal, not the CLI.

**Comment by weinong** [comment]
for the time being, can you use ARM template to deploy?

**Comment by rsnj** [comment]
I'm having the same issue. I've tried to create a new (from scratch) AKS cluster in both the Azure Portal and via the JSON ARM templates. It fails every time with the FailedRoleAssignmentCreation error.

**Comment by yungezz** [comment]
i met same error when using az cli and portal to create a brand new aks cluster, with default new service principal.

**Comment by StephanX** [comment]
Hitting this as well.  Created a cluster, deleted the cluster and associated resources, and attempted to re-create using the Virtual Network.

> "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",

**Comment by weinong** [comment]
@yungezz you hit the issue during an outage in one of our dependent service. It should be OK now.

**Comment by bdelville** [comment]
Experiencing this too :

> {"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidTemplateDeployment\",\r\n \"message\": \"The template deployment failed with error: 'Authorization failed for template resource '[.......]' of type 'Microsoft.Network/virtualNetworks/subnets/providers/roleAssignments'. The client '[.......]' with object id '[.......]' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '[.......].'.\"\r\n }\r\n}"}]}

**Comment by yungezz** [comment]
@weinong  confirmed it's  resolved.

**Comment by weinong** [comment]
the fix in Portal has been deployed. Please refresh your browser and give it a try again. Thanks for reporting!

**Comment by jdogg89** [comment]
This seems to still be an issue: 
Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for subnet. Are you an Owner on this subscription?
Deployment failed. Correlation ID: xxxxxxxxxxxxxxxxx. Provisioning of resource(s) for container service aksInfraDev in resource group InfraDev failed. Message: Operation results in exceeding quota limits of Core. Maximum allowed: 10, Current in use: 6, Additional requested: 6. Please read more about quota increase at http://aka.ms/corequotaincrease.. Details:

**Comment by asc-adean** [comment]
I am getting the same issue.  App Registration SP is Owner of resource group
`Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for subnet. Are you an Owner on this subscription?`

**Comment by bhaskar-chenchu** [comment]
Trying to create new AKS cluster with custom VNET using "/azure-quickstart-templates/101-aks-advanced networking" template.  Keep failing with error# 

{   code: DeploymentFailed,   message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.,   details: [     {       code: Conflict,       message: {\r\n  \error\: {\r\n    \code\: \RoleAssignmentExists\,\r\n    \message\: \The role assignment already exists.\\r\n  }\r\n}     }   ] }

-- Keep tyring multiple times, but no luck.  

Requesting support to fix it.

**Comment by poochwashere** [comment]
> Experiencing this too :
> 
> > {"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n "error": {\r\n "code": "InvalidTemplateDeployment",\r\n "message": "The template deployment failed with error: 'Authorization failed for template resource '[.......]' of type 'Microsoft.Network/virtualNetworks/subnets/providers/roleAssignments'. The client '[.......]' with object id '[.......]' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '[.......].'."\r\n }\r\n}"}]}

I think you need ownership permissions on the RG to perform this role assignment.

**Comment by eliasericsson** [comment]
I have the same experience as well, using the 101-template with advanced networking. The issue presents itself if the role is already assigned to the subnet. If the role is removed before deploying the template it does works.

So the incremental mode for applying the role assignment doesn't seem to work properly.

**Comment by ferantivero** [comment]
here using ARM template to assign my aks cluster the ACR reader role and when I execute it more than once, it fails with code RoleAssignmentExists.

BTW, it seems to be upstream based on my understanding.

**Comment by sanghamanvir13** [comment]
Can anyone suggest what is the available fix for this? I am trying to do the role assignment from ARM template and getting this error for incremental deployments: RoleAssignmentExists
