### ISSUE TITLE
Deploying Container Health agent during AKS cluster creation with ARM fails

### ISSUE THREAD

**Issue by tomasr** [Azure/AKS#553]
Currently testing out an ARM template to provision an AKS cluster. I wanted to include the Log Analytics Container Health solution as part of the template, based on the instructions [here](https://docs.microsoft.com/en-us/azure/monitoring/monitoring-container-health?toc=%2Fen-us%2Fazure%2Faks%2FTOC.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json). However, I'm running into some unexpected problems.

The template basically deploys:

* An OMS Log Analytics Workspace
* The Container Health solution into the workspace
* An AKS cluster with the omsagent addon profile included.

First execution of the template always fails with the following error:

```text
Resource Microsoft.ContainerService/managedClusters 'dev-k-eastus-2' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse-agent-0'. Error message: \"Enable failed: failed to execute command: command terminated
with exit status=31\n[stdout]\n\n[stderr]\n\".",
        "details": [
          {
            "code": "VMExtensionProvisioningError",
            "message": "VM has reported a failure when processing extension 'cse-agent-0'. Error message: \"Enable failed: failed to execute command: command terminated
with exit status=31\n[stdout]\n\n[stderr]\n\"."
          }
        ]
      }
    ]
  }
}
```
Once I re-run the ARM template, the deployment succeeds.

But not quite. After this happens, seems like the master for the cluster get stuck in a weird state. Any attempts to connect to the cluster using `kubectl` will fail, even after a couple of hours of the cluster having being created.

I'm sure I'm screwing something in my template (I suspect it's some sort of timing issue), but I also don't think that ending up with unresponsive masters should be the right outcome.

```text
Unable to connect to the server: net/http: TLS handshake timeout
```
Environment:
* Kubernetes version: 1.10.5
* Size of cluster: 1
* Workloads: none

**Comment by weinong** [comment]
I believe your observations are the result of many dimensions. However, I don't think container health solution dependency would impact AKS creation. Can you retry it again? 

Also, can you guy send details like subscriptionID, resource group, resource name and region to aks-help@service.microsoft.com for us to take a look?

**Comment by tomasr** [comment]
I tried it 3 different times, with the same result each time. Unfortunately, I had to delete the failed cluster.

Happy to share privately the ARM template that was triggering the issue, though, if you're interested.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
