### ISSUE TITLE
How to upgrade AKS cluster to GA?

### ISSUE THREAD

**Issue by mkfsn** [Azure/AKS#555]
I have created some AKS clusters and as AKS has gone to GA, how do I migrate/upgrade my existing clusters?

Does it mean that I need to create further clusters and then move my services to the newly created cluster? Or I only need to upgrade my existing cluster to a specific version of kubernetes e.g. `1.9.9`?

**Comment by seanmck** [comment]
There is no notion of upgrading to GA. Simply continue upgrading to new Kubernetes versions as they are released and you should receive the new capabilities of the service.
