### ISSUE TITLE
Terraform: Unable to Assign Static IP to a Service Load Balancer

### ISSUE THREAD

**Issue by ipalazzi** [Azure/AKS#557]
**What happened**:

I'm building a AKS cluster with Terraform. I'm able to create the Cluster (azurerm_kubernetes_cluster), adding a Replication Controller (kubernetes_replication_controller) and creating a Service (kubernetes_service).

The Service exposes a Load Balancer in order to make it public.

I'm trying to assign a previously created Azure Public IP to this Service but it fails.

To be more precise, the ``terraform plan`` goes well, with something like this:

```
kubernetes_service.service-name
      spec.0.load_balancer_ip: "" => "x.x.x.x"

Plan: 0 to add, 1 to change, 0 to destroy.
```

But the ``terraform apply`` returns this error:

```
* kubernetes_service.service-name: Failed to update service: jsonpatch replace operation does not apply: doc is missing key: /spec/loadBalancerIP
```

**What you expected to happen**:

I was expecting to be able to associate my static IP to a K8S Service Load Balancer.

**Environment**:
- Kubernetes version: 1.10.5
- Size of cluster: 1 node

**Comment by weinong** [comment]
This is not related to AKS. Can you please ask this question in Terraform repo?

**Comment by ashleydavis** [comment]
@ipalazzi Did you find a solution or log an issue with Terraform? I'm getting this same problem!

**Comment by ipalazzi** [comment]
Actually, I didn't.

At the time I posted the issue, it wasn't possible to do so. What I did instead was using another approach, that is creating Kubernetes services/ingresses using the related Public Load Balancer created by Kubernetes itself.

Hope this helps.
