### ISSUE TITLE
Use existing AKS loadbalance ip address to create nginx-ingress

### ISSUE THREAD

**Issue by rnkhouse** [Azure/AKS#558]
**What happened**:

I am trying to use existing AKS loadbalance ip address to create `nginx-ingress` or any service.  I don't want service to create a new external IP address every time.

>helm install stable/nginx-ingress --set controller.service.loadBalancerIP="xx.xx.xx.xx"

It's creating a new IP address.

>kubectl get svc
>default       nginx-nginx-ingress-controller           LoadBalancer   10.242.17.128    yy.yy.yy.yy   80:31003/TCP,443:32288/TCP              15m

**What you expected to happen**:

Run nginx-ingress controller on existing loadbalance IP address.

**How to reproduce it (as minimally and precisely as possible)**:

Just run above command after creating AKS and provide loadbalance ip address.

**Environment**:
- Kubernetes version:

    Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
    Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (how many worker nodes are in the cluster?): 3

**Comment by tomasr** [comment]
Are you creating the service on an IP Address that is already bound to another service, and that's how it got associated with the load balancer?

**Comment by rnkhouse** [comment]
Nvm. `nginx-ingress` is already running under `kube-system` context (addon-http-application-routing-nginx-ingress-controller).

**Comment by rnkhouse** [comment]
@tomasr No. It's not associated with any other service.

**Comment by palma21** [comment]
Possible today:
https://docs.microsoft.com/en-us/azure/aks/ingress-basic
or
https://docs.microsoft.com/en-us/azure/aks/ingress-internal-ip
