### ISSUE TITLE
'az aks create' command needs to fail faster

### ISSUE THREAD

**Issue by BenniG123** [Azure/AKS#559]
**What happened**:
I tried unsuccessfully to create an AKS resource 2 days ago using default command line options via az on powershell (az aks create ….).  I tried 10 times maybe.  Every single time, the command seemed to be accepted (Running...) and then after 20-30 minutes, the command would fail with a variety of error messages (Cluster create failed - 200, Incorrect number of nodes for this region, and a couple others.)

**What you expected to happen**:
If my parameters aren't going to succeed, hours of my time could have been saved by a quick preliminary check from the az aks create tool.  Any kind of error or suggestion message about what correct parameters should look like would be helpful.

**How to reproduce it (as minimally and precisely as possible)**:
az aks create -g MyResourceGroup -n MyManagedCluster --generate-ssh-keys --node_count=1 --location=westus  <-- (afaik this combination isn't allowed)

**Comment by weinong** [comment]
why would this combination fail?

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
