### ISSUE TITLE
IP list for NSG on AKS cluster 

### ISSUE THREAD

**Issue by JuneZhao** [Azure/AKS#560]
By default, the AKS service creates a NSG with rules 100 (allow_kube_tls) and 101 (allow_ssh). Our information security department mandates that we need to restrict access to the cluster so we need to understand if these rules can be deleted or if they are needed by AKS to do cluster management. If they are indeed needed, we need to restrict them to the minimum required IPs instead of all/all.

**Comment by JuneZhao** [comment]
@rite2nikhil @khenidak

**Comment by amandadebler** [comment]
We have the same requirement, as well as stricter outbound rules - where can we find the IP ranges for Azure Container Registry for each region, or will this be available as a Service Endpoint soon? The Service Endpoint was originally planned for Spring 2018: https://github.com/Azure/acr/blob/master/docs/acr-roadmap.md#performance--scalability

**Comment by stdistef** [comment]
So for **outbound** NSG rules, there is a concept of _Service Tags_. https://docs.microsoft.com/en-us/azure/virtual-network/security-overview#service-tags
One Tag is called **Internet**:
Internet (Resource Manager) (INTERNET for classic): This tag denotes the IP address space that is outside the virtual network and reachable by the public Internet. The address range includes the Azure owned public IP address space found here:
https://www.microsoft.com/en-us/download/details.aspx?id=41653

**Comment by seanmck** [comment]
Yes, you can remove those entries in the NSG. The first one (allow_kube_tls) is a historical artifact that we intend to remove from new deployments. The second (allow_ssh) will obviously prevent you from SSHing to the agent nodes, but you should generally not need to do that anyway.
