### ISSUE TITLE
Internal apiserver calls blocked by Istio-- only on AKS

### ISSUE THREAD

**Issue by krancour** [Azure/AKS#561]
Cross posting: https://github.com/knative/serving/issues/1730

**Comment by jeremyrickard** [comment]
This is also happening on my clusters.

**Comment by krancour** [comment]
Another datapoint: Using [these instructions](https://medium.com/@weinong/azure-kubernetes-service-control-plane-logs-f8ffa449fd), I've been unable to find any apiserver log entries that appear to relate to this.

**Comment by sauryadas** [comment]
We are working on enabling cluster autoscaler in the next 2 weeks. Havent had a chance to try out knative serving autoscaling yet. For any feature requests/enhancements please use user voice ..

https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks

**Comment by palma21** [comment]
Fixed
