### ISSUE TITLE
Network profile configuration needs empty ids in 2 ranges?

### ISSUE THREAD

**Issue by Mumrau** [Azure/AKS#562]
Hello,

I'm having a question about networkProfile configuration in AKS.
Let's pretend I have this configuration alongside a subnet that resides in 10.10.0.0/16:
```json
"networkProfile": {
    	"networkPlugin": "azure",
    	"serviceCidr": "10.100.0.0/16",
    	"dockerBridgeCidr": "172.17.0.1/16",
    	"dnsServiceIP": "10.100.0.10"
    }
```
Does this implies that I need my VNET (the one containing the subnet) needs to be "free" on `10.100.0.0/16`, and thus have no subnet over this range, or does this simply implies that the network that resides inside the cluster will use `10.100.0.0/16` entirely privately without repercussion in the VNET?

These kind of considerations are not thoroughly documented and it makes it pretty hard to comprehend fully the implications, quite a few times I got an unstable cluster that still was considered "running" due to network configuration that should have raised errors or warnings.

Thanks in advance,

Regards.

**Comment by neumanndaniel** [comment]
From the Azure docs:

> Kubernetes service address range | **This range should not be used by any network element on or connected to this VNet.** Service address CIDR must be smaller than /12.

That means you have to make sure that no one uses 10.100.0.0/16 in your entire on-premises and Azure network, when you would like connect your AKS via VNET peering, ExpressRoute or VPN to other resources.

But it does not require to create a second subnet in the VNET with CIDR 10.100.0.0/16. The K8s service network is used internally in the K8s cluster.

-> https://docs.microsoft.com/en-us/azure/aks/networking-overview#plan-ip-addressing-for-your-cluster

HTH

**Comment by Mumrau** [comment]
Thanks for you reply, your words made it clearer.

Le ven. 27 juil. 2018 à 15:02, Daniel Neumann <notifications@github.com> a
écrit :
