### ISSUE TITLE
Custom VNET - Nginx Ingress Controller & Cert Manager not receiving events from API Server

### ISSUE THREAD

**Issue by C123R** [Azure/AKS#563]
Nginx ingress controller and Cert manager is not receiving events from API Server.

To give you brief overview, we have recently created new AKS Cluster hosted on custom VNET. AKS cluster was created using Terraform and due to known terraform issue #400 with custom VNET, subnet association with route table was made as workaround mentioned in issue.

We have analyse the issue further and somehow it related to the Github Issue #408. 

For us, the problem looks very similar. It seems like the Ingress Controller and Cert Manager is not able to get the events from API Server.

By default, the Kubernetes Ingress controller connects to the API server using the environment variable KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT.
```
root@nginx-ingress-controller-76b85ffd8f-5mw4q:/# env | grep KUBERNETES_SERVICE
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_HOST=10.0.0.1
```
As per our understanding, In AKS Azure Proxy is responsible for node to API Server communication where the AKS master url is set as upstream endpoint:
```

/ # hostname
azureproxy-7bb5c9d7fb-nnmjx
/ # cat /etc/nginx/conf.d/default.conf
upstream endpoint {
    server XXXXXXXX.westeurope.azmk8s.io:443;
}
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
server {
        listen                  443;
        server_name             _;
```

**1. Reverting the changes in Azure Proxy configuration.**

We also tried to revert the changes in azure proxy configuration which were made recently as mentioned in #408 

The first different setting is the "proxy_read_timeout" which was previously set to one day (1d) and is now set to 30min.

The second is a new config that was not there before. As a test, we have changed these changes on the new cluster.

```
# mitigate HTTPoxy Vulnerability
        # https://www.nginx.com/blog/mitigating-the-httpoxy-vulnerability-with-nginx/
        proxy_set_header Proxy  "";
```
With above changes, we started seeing events in ingress controller and cert manager but it failed again after a while.

**2. Regarding 10.0.0.1 endpoint**

To test if we are also facing the same issue (as described in the Github Issue), we've configured the Nginx Ingress controller to connect directly to the external URL by passing kubeconfig as argument for nginx controller ("-kubeconfig = ..." arg.) as well for the cert-manager. 

And it works well, we can see (CRETE/UPDATE/DELETE) events inside cert manager/ingress controller. We have this workaround implemented and we are not facing any issues as of now.

**How to reproduce it (as minimally and precisely as possible)**:

By disabling kubeconfig as arguement for the nginx controller.

**Anything else we need to know?**:
As i mentioned above the custom VNET and a workaround  for the route table association. One more important point, if we create AKS cluster using azure portal(with advance networking) its not creating route table at all, moreover thats not the case from Terraform..looks like its terrafomr issue but might help for investigation.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"
```

**Comment by rite2nikhil** [comment]
Please perform a update operation on your cluster (upgrade [same k8s version]/scale [to same # on nodes]) and the bounce kube-system/azureproxy pod should help you get the patch to fix this issue.
