### ISSUE TITLE
RBAC inadvertently enabled while upgrading cluster from 1.8.x>1.9.9

### ISSUE THREAD

**Issue by MXClyde** [Azure/AKS#566]
**What happened**:

- Cluster running without RBAC on 1.8.x (1.8.6 if I recall correctly) was upgraded to 1.9.9 using the Azure Portal
- During the upgrade RBAC was inadvertently enabled.
- As a result, the nginx load balancer, Kubernetes Dashboard and running commands like "kubectl logs" all failed with permissions errors.
- Subsequently upgrading to 1.10.5 didn't fix the problem
- Manually adding clusterrolebindings with cluster-admin cluster role to the relevant users and service accounts restored normal functioning of the cluster.

**What you expected to happen**:

- Upgrades execute without enabling RBAC inadvertently. 
- This brought down our production workloads for a while (due to unavailability of the load balancer and initial inability to restore the situation without full rights on the cluster)

**How to reproduce it (as minimally and precisely as possible)**:

My assumption is that upgrading a cluster from 1.8.x to 1.9.9 will suffice to reproduce, have not tried this myself yet.

**Anything else we need to know?**:

- Support ticket has been filled under ID #118072818676651.
- I would like RBAC disabled on this cluster again. How can this be done?

**Environment**:
- Kubernetes version (use `kubectl version`): upgrade 1.8.x to 1.9.9
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Java app

**Comment by derekperkins** [comment]
I had the same experience and ended up recreating my cluster. It was very frustrating.

**Comment by weinong** [comment]
It's a known issue for some old clusters. All new clusters since GA will not have this. That being said, we can see if we can fix your clusters. Can you guys send details like subscriptionID, resource group, resource name and region to aks-help@service.microsoft.com for us to take a look?

**Comment by MXClyde** [comment]
My cluster was indeed pre-GA and it has already been fixed through Support. I think this issue can be closed?
