### ISSUE TITLE
Reverse proxy in front of API server address ?

### ISSUE THREAD

**Issue by lukasmrtvy** [Azure/AKS#567]
Hello,
What exactly means this AKS API endpoint: my-custom-aks-somestring.hcp.westeurope.azmk8s.io ? 
Is it some kind of internal ingress (on managed server) controller which is not listed on agents ? 
I am able to use Proxy Verb to access service from this URL like: `https://my-custom-aks-somestring.hcp.westeurope.azmk8s.io/api/v1/namespaces/my-namespace/services/myservice:port/proxy/`

Problem is when I want to use HAProxy to do TCP proxy with SSL passtrough to this API endpoint URL 
It shows: "default backend - 404" from backend.

Example of haproxy config:
```
frontend k8s-f
        bind 172.20.131.7:443
        mode tcp
        default_backend k8s-b

backend k8s-b
        mode tcp
        server server1 my-custom-aks-somestring.hcp.westeurope.azmk8s.io:443
```

Any idea how to do it?

Or do I need to setup custom ingress controller on agents? 
Thanks

EDIT:
seems that if I add  172.20.131.7 my-custom-aks-somestring.hcp.westeurope.azmk8s.io to hosts it is working

**Comment by JackQuincy** [comment]
For AKS we host the control plane on our servers. The *.azmk8s.io is the endpoint we stand up to allow communication. We also stand up a tunnel from the control plane into the vnet. so you should be able to use standard k8s service discovery for the kubernetes service and just call that. reopen the issue if that doesn't work
