### ISSUE TITLE
AKS API server address with Private IP address ?

### ISSUE THREAD

**Issue by lukasmrtvy** [Azure/AKS#572]
There is currently no option to set private IP for API server address.
What else, is not even possible to use NSG to control FW rules to allow/deny traffic for this endpoint.
Although is possible to put AKS in VNET, API server address is still reachable from public internet.
Any workaround ?

**Comment by seanmck** [comment]
This is not available today but is something we intend to enable. Please add a feedback entry at https://aka.ms/aks/feedback.

**Comment by stdistef** [comment]
https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/35010421-secure-aks-api-from-public-internet
