### ISSUE TITLE
High latency on pod-to-pod communication using Servicetype LoadBalancer

### ISSUE THREAD

**Issue by saschak094** [Azure/AKS#574]
**What happened**:
We have a deployment that communicates in three layers, meaning traffic from pod-to-pods. When we expose the service via ClusterIP the latency of the application stack is low, but when we expose the service via LoadBalancer the latency is high (dealing with seconds for request that should be done in 10ms).  Additionally an ``` apt update``` or ```apt install``` takes an enormous amount of time.  

**What you expected to happen**:
I would expect the communication inside the cluster from pod-to-pod to have no latency or low latency. 

**How to reproduce it (as minimally and precisely as possible)**:
It only reproducible on our cluster, we tested with an additional cluster with kubernetes version 1.10.5 and there it works fine.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 
```bash
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster: 6 nodes

Next action plan: 
- [ ] We are going to try upgrade our pre-prod environment to the latest kubernetes relase and verify if that has any impact. 

Adding case number for Microsoft support 118073118690661

**Comment by digeler** [comment]
any updates after the upgrade ? ,are you still facing the same ?

**Comment by saschak094** [comment]
Did the upgrade to version 1.10.6, but the issue still persists

**Comment by rite2nikhil** [comment]
Can you please share your cluster info (sub id, resource group, resource id) @  aks-gh-feedback@service.microsoft.com

**Comment by saschak094** [comment]
@digeler should have all that information

**Comment by digeler** [comment]
Nikhil ,i emailed you the details.

**Comment by digeler** [comment]
we looked at the network traces we are not seeing any external traffic from the pods.

**Comment by digeler** [comment]
Hi Nikhil , any updates on this one ?
what else do we need here ?

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
