### ISSUE TITLE
[Azure] [AKS] Cluster not Scaling up with error "Node group agentpool is not ready for scaleup"

### ISSUE THREAD

**Issue by abizake** [Azure/AKS#575]
Failed to scale up: failed to increase node group size: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PropertyChangeNotAllowed" Message="Changing property 'enableRBAC' is not allowed."

Additional info 
There are currently 2 nodes in the cluster.
I created the Cluster Auto Scaler with Min=3 and Max =5
I also scaled the pods because of which there is one pods unscheduled.

Kubernetes Version : 1.10.5
Cluster Autoscaler version : V1.2.2
Cloud Provider :- Azure (AKS)

Please Advise.

**Comment by abizake** [comment]
Also tried the latest version of AKS(1.10.6) and Cluster Auto Scaler (1.3.1).
Still facing the issue.
logs :-
containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="" Message=""
W0801 16:02:23.327898       1 clusterstate.go:223] Disabling scale-up for node group agentpool until 2018-08-01 16:07:23.327890748 +0000 UTC m=+1003.285999979
E0801 16:02:23.327976       1 static_autoscaler.go:283] Failed to scale up: failed to increase node group size: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="" Message=""

**Comment by iMartyn** [comment]
I also have this error (400 with no message) with 1.10.6 and 1.3.1.

I am getting some poor help from Azure support, but nothing so far that fixes it.

**Comment by Imransysg** [comment]
I am also facing the same issue..
kubernetes 1.10.6 and cluster-autoscaler:v1.2.2

**Comment by iMartyn** [comment]
@Imransysg https://github.com/kubernetes/autoscaler/issues/1105#issuecomment-410578049
known issue, fix "soon"

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
