### ISSUE TITLE
az aks create silently fails - no error message/ notification.

### ISSUE THREAD

**Issue by SnehaJosephSTS** [Azure/AKS#578]
**What happened**: 
Running the following az aks create command from my linux machine **silently fails**
az aks create   --name myAKSCluster     --resource-group myResourceGroup     --node-count 1     --generate-ssh-keys     --service-principal <appId>     --client-secret <password>

No AKS cluster created; no error message shown.

**What you expected to happen**:
Creation of a kubernetes cluster/ appropriate error message

**How to reproduce it (as minimally and precisely as possible)**:
-Configure a resource group in West Europe. 
-Get Service principal id using "az ad ap create-for-rbac" command
- Run the az aks create command as above

**Anything else we need to know?**: I have experienced this issue with the East Europe region too. 

**Environment**:
- Kubernetes version : None specified in the command. Azure hence deploy the latest supported version (i assume)
- Size of cluster : 1
- General description of workloads in the cluster : NA
- Others:

**Comment by weinong** [comment]
what is your azure cli version? have you tried to add `--debug`?

**Comment by Zenlil** [comment]
We got this once, and when we tried using the Portal we got the error that our reserved compute-quota(?) was full (i.e couldn't create enough VMs)

**Comment by jnoller** [comment]
As of the March releases of AKS, we now pre-flight check quota on all operations and throw a clear user error on the CLI and in the portal. Closing as fixed.
