### ISSUE TITLE
Submitting spark job to AKS cluster results in 'Error: Could not find or load main class SparkPi

### ISSUE THREAD

**Issue by creasewp** [Azure/AKS#579]
**What happened**:
Trying to follow the instructions here: https://docs.microsoft.com/en-us/azure/aks/spark-job
to run a spark job in my AKS cluster. I am able to submit the job to spark, and the driver pod is created, however it always reports an error: Error: **Could not find or load main class SparkPi**
I have tried storing the JAR in azure blob storage and embedding in the docker container and using local:/// as mentioned in the article mentioned above.

My first thought was that I hadn't built the JAR correctly... however, I am able to submit the same jar file to my local spark instance without any issue.

**What you expected to happen**:
The spark job to execute properly

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
1.10.3 (also upgraded to 1.10.6, same issue)
- Size of cluster (how many worker nodes are in the cluster?)
1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
None
- Others:

**Comment by lenadroid** [comment]
I'll try it with the newest AKS version and write back!

**Comment by lenadroid** [comment]
in the meantime, hey @creasewp - if you follow [this](https://github.com/lenadroid/show-episode-recommender) tutorial, do you run into class not found issue?

You can test it with pre-built Spark docker image with dependencies: `lenadroid/spark:recommendations-first-season`

The full command:
```
export KEYWORD="tyrion"
```

and 

```
$SPARK_HOME/bin/spark-submit  \
--master k8s://http://127.0.0.1:8001  \
--name got-recommender  \
--deploy-mode cluster  \
--class org.apache.spark.examples.GoTEpisodeRecommender  \
--conf spark.executor.instances=2  \
--conf spark.kubernetes.container.image=lenadroid/spark:recommendations-first-season \
local:///opt/spark/jars/GoTEpisodeRecommender-assembly-0.1.0.jar $KEYWORD
```

**Comment by creasewp** [comment]
@lenadroid your tutorial does appear to work... but I noticed a few differences
1) you embedded the JAR in a different directory in the spark docker image
2) you built the JAR on linux - I was doing it on windows
I will make a few tweaks and see if I can determine if either of those are the difference...

**Comment by creasewp** [comment]
@lenadroid 
So I was able to take the JAR file from your tutorial and upload to blob storage and reference it from there. However, my JAR file still doesn't work. I have been trying to make my project look more like yours... but haven't found the magic bullet. So I went back to your project and tried to change the object name from GoTEpisodeRecommender to HelloWorld... and I get the same error about being unable to find the class. I can't find anything that tells SBT what the main class should be... any idea what I'm missing here?
Thx,

**Comment by lenadroid** [comment]
I tried to go through the docs steps and was able to run a job.

Things to keep in mind:
- Make sure your SparkPi.scala file exists and is located exactly under `sparkpi/src/main/scala/org/apache/spark/examples/SparkPi.scala`. Compare that the directory structure is the same.
- Check that package name inside SparkPi.scala is `package org.apache.spark.examples` 
- Make sure that access policy for your file in Azure storage is set to Public Access is equal to either Blob or Container.
- Make sure you run spark submit with correct class parameter ``
```
./bin/spark-submit 
   --master k8s://http://127.0.0.1:8001
   --deploy-mode cluster
   --name spark-pi
   --class org.apache.spark.examples.SparkPi
   --conf spark.executor.instances=3
   --conf spark.kubernetes.container.image=lenadroid/spark:spark-2.3.0 
   https://<your-storage-account>.blob.core.windows.net/<your-container>/<your-jar>.jar
```
- Try using my pre-built Spark 2.3.0 image `lenadroid/spark:spark-2.3.0 ` if you think there might be something wrong with your image.


In general, if you want to change the main class for Spark job to run, you need to change the `--class` parameter to point to the right package name of your Scala object. For example, if you added another Scala file called NewObject.scala with an object called `NewObject` in the same directory as existing SparkPi.scala file, then your class parameter would be `--class org.apache.spark.examples.NewObject`. Some things that matter are: directory path to scala file, name of the scala file, name of the object in the scala file, name of the package in the scala file.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
