### ISSUE TITLE
Azure SP with multi-subscription access fails to pull ACR images from other subscription

### ISSUE THREAD

**Issue by sjdweb** [Azure/AKS#582]
`Service principal` has access to `subscription 1` and `subscription 2` with **Contributor** role.

`Subscription 1` has:
- container registry
- AKS cluster 1
Both in their own resource groups.

`cluster 1` can pull from container registry fine with service principal out of the box.

`Subscription 2` has:
- AKS cluster 2

`cluster 2` **cannot** pull from container registry (`rpc error: code = Unknown desc. Error response from daemon:  authentication required`)

**Comment by JackQuincy** [comment]
This is a known issue. It has been fixed upstream. Here is the upstream PR https;//github.com/kubernetes/kubernetes/pullreuest/66429 . That has been cherry picked into the 1.10 and 1.11 branches so the next versions we update to should have the fix.

**Comment by andyzhangx** [comment]
**Fix**
 - PR [fix acr could not be listed in sp issue](https://github.com/kubernetes/kubernetes/pull/66429)

| k8s version | fixed version |
| ---- | ---- |
| v1.9 | in cherry-pick |
| v1.10 | 1.10.7 |
| v1.11 | 1.11.2 |
| v1.12 | 1.12.0 |

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
