### ISSUE TITLE
tunnel front pod port explanation

### ISSUE THREAD

**Issue by JuneZhao** [Azure/AKS#583]
I noticed on tunnelfront pod there are some ports definition which i am not sure what is for

tunnel_front_listen_port=2222 #if you change that make sure that the changes are reflected in Dockerfile of tunnel-front
tunnel_end_reverse_port=9090
hcpServerPort="9000"

I noticed that inside the container this is the process:

root       295  0.0  0.1  47352  3728 ?        Ss   01:29   0:01 ssh -i /tmp/tunnel_front/privateKey -oServerAliveInterval=1 -oServerAliveCountMax=5 -oControlPath=no -oControlMaster=no -oExitOnForwardFailure=yes -fNnT -C -R 9090:localhost:2222 cluster@xxx.hcp.ea

Any explanation on how this works?

**Comment by JackQuincy** [comment]
this is used for the AKS hosted control plane to be able to talk to the nodes. It is setting up a tunnel from where we are hosting the control plane into this vnet so that "kubectl logs", "kubectl exec" and other functions can work.
