### ISSUE TITLE
support for networkpolicy

### ISSUE THREAD

**Issue by gurvindersingh** [Azure/AKS#584]
**What happened**:
On creating networkpolicy to block network traffic among pods/namespaces does not work.
**What you expected to happen**:
I expect AKS to support standard kubernetes network policy to filter/block network traffic among pods.
**How to reproduce it (as minimally and precisely as possible)**:
Create a namespace, deploy networkpolicy to block all traffic in it. Deploy an nginx pod and connect to it using another pod with curl e.g. alpine. If AKS support networkpolicy curl should hang but currently it gets the reply back from nginx.

**Anything else we need to know?**:
I am using AZURE Vnet networking plugin.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.6
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Web services
- Others:

**Comment by sauryadas** [comment]
Network policy support is coming in the next couple of months. We will make a blog announcement .. closing this issue
