### ISSUE TITLE
why does it take so long to create AKS cluster

### ISSUE THREAD

**Issue by smartpcr** [Azure/AKS#585]
It took at least 20 min (sometimes over 30 min), while GKE and EKS took < 2 min.

**Comment by jskulavik** [comment]
There are many variables that contribute to provisioning times of AKS clusters including VM size, networking, and security configurations to name a few.  We are continually improving the overall performance of AKS however, and appreciate the feedback.

**Comment by CodeSwimBikeRun** [comment]
what is the recommended vm size, that would optimize speed of creation? We use Terraform, and it never completes before terraform errors out.

**Comment by rmetzler** [comment]
@jskulavik I don't know how you do this all, but I think the faster clouds have pools of unassigned resources which don't need to be instantiated but can just assigned to tenants.
