### ISSUE TITLE
Kubernetes lost nodes and fall back to default configuration

### ISSUE THREAD

**Issue by lorsabyan** [Azure/AKS#586]
**What happened**: Without any action Kubernetes lost nodes and all configurations. After nodes manual restart Dashboard and other stuff came back, but not my services/deployments.

**What you expected to happen**: Manages service should not behave like this.

**How to reproduce it (as minimally and precisely as possible)**: I guess by stopping nodes (VMs)

**Anything else we need to know?**: I have created the Kubernates service when it was in Preview and did some manual configurations (RBAC, ingress controller and etc...) because of AKS issues.

**Environment**:
- Kubernetes version:
```json
{
  "clientVersion": {
    "major": "1",
    "minor": "10",
    "gitVersion": "v1.10.3",
    "gitCommit": "2bba0127d85d5a46ab4b778548be28623b32d0b0",
    "gitTreeState": "clean",
    "buildDate": "2018-05-21T09:17:39Z",
    "goVersion": "go1.9.3",
    "compiler": "gc",
    "platform": "windows/amd64"
  },
  "serverVersion": {
    "major": "1",
    "minor": "9",
    "gitVersion": "v1.9.6",
    "gitCommit": "9f8ebd171479bec0ada837d7ee641dec2f8c6dd1",
    "gitTreeState": "clean",
    "buildDate": "2018-03-21T15:13:31Z",
    "goVersion": "go1.9.3",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```
- Size of cluster: 3 nodes
- General description of workloads in the cluster: HTTP microservices, C# asp.net core

**Comment by jskulavik** [comment]
Hi @lorsabyan,

Could we get a little more information please?  

Did you restart the nodes after noticing they were down?

Did you preform an upgrade after the preview closed and we went to GA?

**Comment by lorsabyan** [comment]
Hi @jskulavik,

Thanks for response!

First I noticed that Dashboard is not available, then noticed that pods, deployments are missing with `kubectl get ...` commands. After that I've checked nodes with `kubectl get nodes` command. After the VMs restart from Azure Portal `kubectl get nodes` listed nodes and some pods started from `kube-system` namespace.

After I've changed VM's size and dashboard again went down, but  `kubectl get nodes` still listed nodes.

I didn't upgraded Kubernates after the setup.

**Comment by jskulavik** [comment]
Okay, thank you @lorsabyan.  

Are you able to access the dashboard now?  

Were you able to get your services back up?  

We have made **a lot** of improvements since preview and you should not see nodes failing like this moving forward.

**Comment by lorsabyan** [comment]
Thanks @jskulavik,

Actually, to save a time, I have created ASK instance from scratch and the setup process was smooth.

I'm closing this issue and will reopen in case of further problems.
