### ISSUE TITLE
Helm commands seem to break AKS clusters using Custom Vnet + Kubenet

### ISSUE THREAD

**Issue by knee-berts** [Azure/AKS#588]
**What happened**:
Helm commands (helm list or something simple) hang/timeout and then we lost the ability to execute any kubectl logs, exec, create, or applys. kubectl gets remain functional. Deleting the tiller pod restores all the lost functionality but returns to malfunctioning once a another helm command is issued.

**What you expected to happen**:
Helm list to list helm releases.
**How to reproduce it (as minimally and precisely as possible)**:
```
az aks create --resource-group $group --name $aksName /
    --node-count 2  /
    -s Standard_DS2_v2 /
    --enable-addons monitoring /
    --workspace-resource-id $oms_workspace_id /
    --vnet-subnet-id $subnetID /
    -k 1.10.6 /
    --network-plugin kubenet /
    --service-principal $servicePrincipal /
    --client-secret $servicePrincipalSecret /
    --ssh-key-value $sshKeyPath

cat <<EOF | kubectl create -f -
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
EOF

helm init --service-account tiller

helm install <anything>

helm list
```
**Anything else we need to know?**:

56m         56m          2         entitlements-test-blue-7cd5f58649-7vwls.1548a862f99fa620   Pod                                                 Warning   NetworkNotReady           kubelet, aks-nodepool1-17927362-1      network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]

**Environment**:
- Kubernetes version (use `kubectl version`):
clientVersion:
  buildDate: 2018-07-18T11:37:06Z
  compiler: gc
  gitCommit: b1b29978270dc22fecc592ac55d903350454310a
  gitTreeState: clean
  gitVersion: v1.11.1
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-07-26T10:04:08Z
  compiler: gc
  gitCommit: a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e
  gitTreeState: clean
  gitVersion: v1.10.6
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
- Size of cluster (how many worker nodes are in the cluster?)
2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
vanilla apache:8 
- Others:

**Comment by is-daimonos** [comment]
hello there, we are using aks with a custom vnet integration + network plugin kubenet and the same errors occur when we used a helm command over the cluster.

We create another cluster using Azure Cni and all is ok.

¿Can you help us? we need to use kubenet network plugins.

**Comment by is-daimonos** [comment]
@knee-berts  Just add to your az aks command "--enable-addons http_application_routing"  and helm command will being ok.

Example of minimalist az aks command version

az aks create --resource-group debug-aks --name DebugAks1 --node-count 2 \
-s Standard_DS2_v2 \
--vnet-subnet-id $subnetID \
-k 1.11.5 \
--network-plugin kubenet \
--enable-addons http_application_routing \
--service-principal $servicePrincipal \
--client-secret $servicePrincipalSecret \
--ssh-key-value /Users/user/.ssh/id_rsa.pub


Remember to add to your Vnet the routing table that aks creating during the provisioning of cluster

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
