### ISSUE TITLE
Question: Which CNI plugins are supported

### ISSUE THREAD

**Issue by eosfor** [Azure/AKS#589]
Hello colleagues, few questions in this regard.

First, which CNI plugins are officially supported in Azure. As far as i understand kubenet and azure-cni can be used, as they are options in AKS/acs-engine. Is this a correct statement?

Second - which CNIs can be used, like calico, flannel etc. Which can be safely used, and which cannot be used safely.

Thanks in advance

**Comment by CecileRobertMichon** [comment]
Hi @eosfor, AKS uses the kubenet network plugin by default. If you choose "advanced networking" when you create your cluster, in which case the cluster will use Azure CNI (https://docs.microsoft.com/en-us/azure/aks/networking-overview) 

In acs-engine, the following network plugins are available to choose from and configure in the "kubernetesConfig" of your apimodel:

- "azure" (default), which provides an Azure native networking experience (Azure CNI) 
- "kubenet" for k8s software networking implementation. 
- "flannel" for using CoreOS Flannel 
- "cilium" for using the default Cilium CNI IPAM

**Comment by guesslin** [comment]
Hi @CecileRobertMichon, does this mean AKS can only use `kubenet` and `Azure CNI` for the CNI plugin. Other CNI like cilium can't be use with AKS cluster. I can only use cilium with ACS cluster?

Thanks in advance

**Comment by kthompsonpros** [comment]
> Hi @CecileRobertMichon, does this mean AKS can only use `kubenet` and `Azure CNI` for the CNI plugin. Other CNI like cilium can't be use with AKS cluster. I can only use cilium with ACS cluster?
> 
> Thanks in advance

Can we get a confirmation on this? I too would like to verify if that is the case. Thank you.

**Comment by jnoller** [comment]
That is correct, only the options (Kubenet, CNI and Calico) documented here are supported in AKS. We do not have current roadmap items to add Cillium or other support. https://docs.microsoft.com/en-us/azure/aks/use-network-policies

**Comment by tgraf** [comment]
For those finding this issue looking on how to run Cilium on AKS. Cilium has added chaining support to run on top of `Azure CNI`. The guide & documentation can be found here:
https://docs.cilium.io/en/latest/gettingstarted/k8s-install-aks/
