### ISSUE TITLE
How to scale the Kubernetes nodes (not just pods) with AKS

### ISSUE THREAD

**Issue by dhirenrouterabbit** [Azure/AKS#59]
I was checking auto-scale mode but that is not going bring down my cost. I discovered a mechanism called "Cluster Autoscaler" which some provider is supporting using which we can autoscale the nodes too. 

Is there anyway, I can add that configuration to my existing AKS?

**Comment by dhirenrouterabbit** [comment]
Basically, [this](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md) answers my question. Is it supported?

**Comment by Plasma** [comment]
Surprised by this lack of support, without auto-scale of the nodes I can't have variable workloads.

**Comment by antoinne85** [comment]
@dhirenrouterabbit A cursory look through the repository you linked suggests that it does support multiple cloud providers (they call out AWS and GCE specifically). I did a search for [`azure`](https://github.com/kubernetes/autoscaler/search?utf8=%E2%9C%93&q=azure&type=) in the repository as well.

There is a [`cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go`](https://github.com/kubernetes/autoscaler/blob/819687760ec2d118622b3a9fda10a9b2f208712a/cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go) file that suggests Azure might be supported.

That file has seen a "reasonable" amount of [activity](https://github.com/kubernetes/autoscaler/commits/819687760ec2d118622b3a9fda10a9b2f208712a/cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go) (including recently), though strangely it was removed and re-added all within the last month, so it's hard to speculate as to how far along it is, though I imagine they wouldn't include it in the `master` branch if it were not production-ready.

I'm not using the library myself, so I can't guarantee it.

**Comment by AceHack** [comment]
@antoinne85 I wonder if that was for ACS

**Comment by slack** [comment]
Existing cluster autoscaler fiddles with the IaaS directly (Virtual Machine Scale Sets or Availability Set). Start of 2018 we will work on updating the in-cluster scaling to call out to AKS to scale cluster nodes.

**Comment by stijnbrouwers** [comment]
@slack Hi, is there an update on this feature? I would like it if AKS supported the autoscaling of nodes :-)

**Comment by dhirenrouterabbit** [comment]
Is this already implemented and available
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/README.md

**Comment by vorkos** [comment]
@dhirenrouterabbit "Kubernetes v1.10.X and Cluster autoscaler v1.2+ are required to run on Azure." but I see an only v1.8.x k8s version on aks available for now.

**Comment by alexsandro-xpt** [comment]
When we will have Kubernetes v1.10X at AKS?

**Comment by derekperkins** [comment]
It's already available - 1.10.3

**Comment by ablekh** [comment]
@alexsandro-xpt Kubernetes 1.10.x is already available in certain Azure regions. I have recently upgraded my cluster to 1.10.3 (`eastus` zone). To find out what K8s upgrades are available, follow this step: https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-upgrade-cluster#get-cluster-versions.

**Comment by seanmck** [comment]
This is available now in preview form.

https://docs.microsoft.com/en-us/azure/aks/autoscaler

We're working on making it a cluster add-on that runs in the control plane.

**Comment by avik-so** [comment]
"We're working on making it a cluster add-on that runs in the control plane."

Where can I find information about the control panel add-on?

**Comment by RehanSaeed** [comment]
Any idea when this will come out of preview and be baked into the product? Also, will we be able to use an ARM template to turn this on?

**Comment by jnoller** [comment]
Cluster autoscaler is in preview, attached to VMSS, you can see info here:

https://github.com/Azure/AKS/blob/master/CHANGELOG.md
https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler#create-an-aks-cluster-and-enable-the-cluster-autoscaler

You can self-opt-in to test it out. From public preview to GA of the feature(s) it is roughly 4 weeks to allow for further testing and bug fixes. This means it would track to next month.

**Comment by ToddBowman** [comment]
My AKS clusters don't use VMSS.  Can I use the new autoscaler?  Can I change my cluster to VMSS?

**Comment by jnoller** [comment]
@ToddBowman Not at this time, VMSS and the autoscaler are in preview, and the autoscaler is tied to VMSS. Given this is a preview feature attached to VMSS, we do not recommend using it in production or applying it to production systems. We are looking at upgrade scenarios for when VMSS is GA

**Comment by timwebster9** [comment]
> Also, will we be able to use an ARM template to turn this on?

Am also wondering about this....

**Comment by jnoller** [comment]
yes, ARM will be supported at GA
