### ISSUE TITLE
One node and its pods cannot access the DNS

### ISSUE THREAD

**Issue by pallad1um** [Azure/AKS#592]
**What happened**:
I have created a cluster in AKS, 2 nodes. I have 4 services deployed, and having issues with the internal name resolution. The DN resolution of the services works fine in pods deployed in one of the nodes (say node-0), but fails in pods deployed in the other node (node-1).

```
$ kubectl get pods -o wide
NAME                                         READY     STATUS    RESTARTS   AGE       IP            NODE
cloud-starter-deployment-6994758f69-wpznp    1/1       Running   0          1h        10.244.0.12   aks-default-24673730-1
navigation-deployment-6f8b5c4859-wnjml         1/1       Running   0          1h        10.244.1.12   aks-default-24673730-0
state-service-deployment-67d59df745-nh5qn    1/1       Running   0          2h        10.244.1.11   aks-default-24673730-0
skeleton-deployment-ccf557fbf-lx8rr         1/1       Running   0          1h        10.244.0.18   aks-default-24673730-1

$ kubectl get svc -o wide
NAME                    TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE       SELECTOR
cloud-starter-service   LoadBalancer   10.0.93.182    10.200.0.20   80:30296/TCP   3h        app=cloud-starter
kubernetes              ClusterIP      10.0.0.1       <none>        443/TCP        1d        <none>
navigation-service      LoadBalancer   10.0.99.82     10.200.0.50   80:30322/TCP   3h        app=navigation
skeleton-service        LoadBalancer   10.0.48.190    13.81.31.70   80:31361/TCP   1h        app=skeleton
state-service-service   LoadBalancer   10.0.178.229   10.200.0.10   80:31732/TCP   3h        app=state-service

$ kubectl exec -it navigation-deployment-6f8b5c4859-wnjml -- sh
/ # nslookup state-service-service
nslookup: can't resolve '(null)': Name does not resolve

Name:      state-service-service
Address 1: 10.0.178.229 state-service-service.default.svc.cluster.local

$ kubectl exec -it skeleton-deployment-ccf557fbf-lx8rr -- sh
/ # nslookup state-service-service
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'state-service-service': Try again
```
I followed the troubleshooting steps found here (https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/), to no avail. 

I have recreated the cluster from scratch, same result.

**What you expected to happen**:
Service domain name resolution works in each pod/node at the same way. 

**How to reproduce it (as minimally and precisely as possible)**:
- Create a 2 nodes cluster in AKS, programmatically, 
- Deploy a few services, log into the pods, and try nslookups on services

**Anything else we need to know?**:
Both the DNS pods run on one node, the one where pods can resolve services (node-0):
```
$ kubectl get pods --namespace=kube-system -o wide
NAME                                    READY     STATUS    RESTARTS   AGE       IP           NODE
...
kube-dns-v20-55645bfd65-fb5gm           3/3       Running   0          1d        10.244.1.5   aks-default-24673730-0
kube-dns-v20-55645bfd65-zwtkc           3/3       Running   0          1d        10.244.1.4   aks-default-24673730-0
```
The pods where dns works can connect to the DNS:
```
# nc -vz 10.0.0.10 53
10.0.0.10 (10.0.0.10:53) open
```
The pods where dns does NOT works can NOT connect to the DNS:
```
# nc -vz 10.0.0.10 53
<hangs>
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
HTTP Microservices in Docker containers
- Others:

**Comment by jskulavik** [comment]
Hi @pallad1um,

Would you please create an issue with Azure support, directing it to AKS and provide a link to this issue?  When doing so, please provide your cluster info (sub id, resource group, resource id).  

Thank you

**Comment by habnux** [comment]
Hello @pallad1um 

I ran into the same problem. Did you hear anything from Azure?

**Comment by pallad1um** [comment]
We don't have access to support currently, if you could post here some
pointers that'd be awesome

**Comment by habnux** [comment]
> Hello @habnux
> 
> Any updates on the support ticket? Thanks!

Hi @teh-username,
We finally deleted the AKS because they couldn't figure out why it didn't work. 
Maybe it was our special V-Net setup, but after 3 weeks debugging, we stopped it.

**Comment by pallad1um** [comment]
We seem to have solved this problem by adding a private DNS zone resource to the RG (https://docs.microsoft.com/en-us/azure/dns/private-dns-getstarted-cli). Admittedly we did some other minor changes, but seemingly unrelated to this problem. We create our cluster with Terraform and it's now behaving as expected, so didn't investigate further. Let us know if this helps!

**Comment by teh-username** [comment]
> Hi @teh-username,
> We finally deleted the AKS because they couldn't figure out why it didn't work.
> Maybe it was our special V-Net setup, but after 3 weeks debugging, we stopped it.

I see, thanks for the reply @habnux !


> We seem to have solved this problem by adding a private DNS zone resource to the RG (https://docs.microsoft.com/en-us/azure/dns/private-dns-getstarted-cli). Admittedly we did some other minor changes, but seemingly unrelated to this problem. We create our cluster with Terraform and it's now behaving as expected, so didn't investigate further. Let us know if this helps!

Thanks for the hint @pallad1um ! I'll try this one.

**Comment by mavencode01** [comment]
I had a similar issue, removing the node and adding it back to the cluster seems to have fixed the DNS issue for me.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.

**Comment by alexeyzimarev** [comment]
DNS issues are really annoying. We have a seven nodes cluster and out of the blue all pods most access to DNS. Upgrading the cluster to 1.13.5 solved the issue but I suspect that it is caused by the API/master nodes upgrade. So it is just a matter of time for this issue to appear again.
