### ISSUE TITLE
Error from server (NotAcceptable): unknown (get nodes)

### ISSUE THREAD

**Issue by snpdev** [Azure/AKS#598]
**What happened**: From Azure Shell
```
michael@Azure:~$ kubectl get nodes
No resources found.
Error from server (NotAcceptable): unknown (get nodes)
```
**What you expected to happen**: 
`kubectl get nodes` would output list of nodes.

**How to reproduce it (as minimally and precisely as possible)**: 
See CLI example above

**Anything else we need to know?**:
AKS was installed using DevOps project. It appears that kubectl client is v1.11.0, server version is v1.8.7.

There is discussion on how to fix this issue at **https://github.com/kubernetes/kubernetes/issues/65575**, but solutions described in this issue may not apply to AKS.

**Environment**:
- Kubernetes version (use `kubectl version`):
```michael@Azure:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) .NET Core DevOps project
- Others: Using an MSDN developer instance of Azure.

**Comment by snpdev** [comment]
Some follow-up information. I installed kubectl v.1.8.7 on my Windows 10 laptop from:
```curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.8.7/bin/windows/amd64/kubectl.exe```

From a cmd prompt on my laptop, I am able to run kubectl commands against the cluster, e.g.
```
C:\WINDOWS\system32>kubectl get nodes
NAME                       STATUS    ROLES     AGE       VERSION
aks-agentpool-19493756-0   Ready     agent     2d        v1.8.7
aks-agentpool-19493756-1   Ready     agent     2d        v1.8.7
```
Now, the questions is... can I downgrade the version of kubectl that runs in Azure Shell?

Or, would I be better off upgrading my AKS cluster to a 1.9.x branch?  Available versions are:

```
C:\WINDOWS\system32>az aks get-upgrades --name k8sdemo --resource-group k8sdemo --output table
Name     ResourceGroup    MasterVersion    NodePoolVersion    Upgrades
-------  ---------------  ---------------  -----------------  --------------------------------------------------
default  k8sdemo          1.8.7            1.8.7              1.8.10, 1.8.11, 1.8.14, 1.9.1, 1.9.2, 1.9.6, 1.9.9
```

**Comment by jskulavik** [comment]
Hi @snpdev,

We would suggest that you upgrade your server version.  That is almost always recommended as k8s (and therefore AKS) moves so quickly it becomes difficult to track down issues like this between minor releases.  Upgrade your server and let us know if that resolves your issue.

**Comment by snpdev** [comment]
Thanks @jskulavik,

I just started the cluster upgrade to 1.9.9 from the CLI. It will take a while, so I'll follow up again on Monday.

I should point out that the DevOps Project installer only provides two version options as of today: 1.7.12 and 1.8.7. If I had a 1.9.x option, I would have selected that to begin with. You may want to pass on this tidbit to the DevOps Project team. 

![image](https://user-images.githubusercontent.com/1825479/44010508-ebf12b16-9e80-11e8-865f-218b6438c7ed.png)

**Comment by jskulavik** [comment]
Thank you for that DevOps feedback!  I will pass along that info to the team.

**Comment by snpdev** [comment]
After upgrading the cluster to 1.9.9, the problem is resolved.

Thanks @jskulavik

**Comment by jskulavik** [comment]
Glad to hear @snpdev!  Thank you for the feedback.
