### ISSUE TITLE
RBAC disabled by default when creating AKS cluster from Portal

### ISSUE THREAD

**Issue by prydonius** [Azure/AKS#603]
The Azure Portal default RBAC setting doesn't match the `az aks` default where RBAC is enabled.

![screen shot 2018-08-13 at 3 05 42 pm](https://user-images.githubusercontent.com/1544861/44112190-4888f852-9fb9-11e8-9caa-a8cfad5da30d.png)

**Comment by dennisameling** [comment]
Just to add a bit to this:

- The Portal is indeed not consistent with the `az aks` command, as the Portal doesn't enable RBAC by default and `az aks` does. This is also mentioned in the AKS [FAQ](https://docs.microsoft.com/nl-nl/azure/aks/faq#does-aks-support-kubernetes-role-based-access-control-rbac).
- Existing AKS clusters without RBAC cannot be updated for RBAC use ([source](https://docs.microsoft.com/en-us/azure/aks/aad-integration))
- GCS has [enabled](https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control) RBAC on all clusters running Kubernetes version 1.6 or later.
- Amazon EKS also has [enabled](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html) RBAC by default: 

> When an Amazon EKS cluster is created, the IAM entity (user or role) that creates the cluster is added to the Kubernetes RBAC authorization table as the administrator (with system:master permissions).

Would be great to have more consistency among cloud providers here. Especially for beginning Kubernetes admins this might be something you'd overlook, while we can pretty much consider RBAC the de facto standard for Kubernetes deployments now.

**Comment by kkmsft** [comment]
The latest I checked, the portal has been updated with RBAC enabled as default.
@prydonius - are you still seeing an issue here ?

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
