### ISSUE TITLE
K8S Dashboard loads slowly, tiller unresponsive once istio 1.0.0 installed

### ISSUE THREAD

**Issue by BernhardRode** [Azure/AKS#605]
**What happened**:
K8S Dashboard loads slowly, tiller unresponsive once istio 1.0.0 installed.
**What you expected to happen**:
K8S Dashboard and helm should still be usable after Istio installation.
**How to reproduce it (as minimally and precisely as possible)**:
* Create AKS cluster
* Setup clusterrole 
* Setup Istio - https://istio.io/docs/setup/kubernetes/quick-start/
* Deploy some service
**Anything else we need to know?**:
Istio issue - https://github.com/istio/istio/issues/7675
**Environment**:
- Kubernetes version (use `kubectl version`):
v1.11.1
- Size of cluster (how many worker nodes are in the cluster?)
6 x Standard Standard_D2_v2
- General description of workloads in the cluster
HTTP microservices

**Comment by mboersma** [comment]
We identified a problem with a read timeout value that is fixed now in AKS. New clusters should not see this problem when installing Istio. For any existing clusters that see this problem, please open a support ticket directly with Azure support, or email aks-help@service.microsoft.com with details so we can patch up your cluster.

**Comment by ChrisPei** [comment]
same issues

**Comment by ChrisPei** [comment]
I found that kube-dashboard can't start kubernetes-dashboard-key-holder-kube-system  when istio has been installed.

kube-dashbaord always stuck here:

> 2018/08/16 03:38:58 Using in-cluster config to connect to apiserver
> 2018/08/16 03:38:58 Starting overwatch
> 2018/08/16 03:38:58 Using service account token for csrf signing
> 2018/08/16 03:38:58 No request provided. Skipping authorization

But when I delete istio, kube-dashboard pod will continue immediately:

> 2018/08/16 04:00:08 Starting overwatch
> 2018/08/16 04:00:08 Using in-cluster config to connect to apiserver
> 2018/08/16 04:00:08 Using service account token for csrf signing
> 2018/08/16 04:00:08 No request provided. Skipping authorization
> 2018/08/16 04:00:40 Successful initial request to the apiserver, version: v1.11.1
> 2018/08/16 04:00:40 Generating JWE encryption key
> 2018/08/16 04:00:40 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
> 2018/08/16 04:00:40 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
> 2018/08/16 04:00:45 Initializing JWE encryption key from synchronized object

**Comment by BernhardRode** [comment]
I've received a mail from microsoft tonight.

Please have a look at this:
https://github.com/istio/istio/issues/7675#issuecomment-413786413

If my tests pass, this ticket may be closed from my side.

**Comment by ChrisPei** [comment]
@BernhardRode I'm still waiting the reply from microsoft. Hope that is the right way to resolve this issues.

**Comment by BernhardRode** [comment]
So after some hours the issue is back ... dashboard and helm are not usable anymore.

**Comment by BernhardRode** [comment]
The issue seems to be fixed in istio 1.0-release branch. So with the next upcoming release, we should be fine.

https://github.com/istio/istio/issues/7675

**Comment by rsnj** [comment]
I am still experiencing this issue with the nightly Istio release. Looks like it may be an issue with the AKS Api Server.
https://github.com/istio/istio/issues/7675#issuecomment-415526554

**Comment by BernhardRode** [comment]
I think we can close the issue and watch the changes in #620.
