### ISSUE TITLE
How to set FQDN for AKS cluster?

### ISSUE THREAD

**Issue by ablekh** [Azure/AKS#611]
I'm trying to set up JupyterHub on AKS. For the ingress part, I plan to use [this method](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/advanced.md#ingress-and-automatic-https-with-kube-lego--lets-encrypt), however I forgot how to set FQDN for the cluster first (`hostname` in instructions). I have done it before once, but that cluster got corrupted, so I have to configure a new one. Your quick help will be much appreciated.

**Comment by tomasr** [comment]
I use [external-dns](https://github.com/kubernetes-incubator/external-dns) to set up external names when using ingress or loadBalancer services. Has worked pretty well so far.

**Comment by ablekh** [comment]
@tomasr I appreciate your advice. As I understand, `external-dns` is more targeted toward setting FQDNs managed by external DNS providers. In my case above, I was just trying to figure out how to set the FQDN for a particular AKS cluster's ingress (with an application being JupyterHub). Anyway, I recalled how I did it initially and I'm sharing relevant script below, hoping that it will be useful to other people.

```
#!/bin/bash

# Public IP address
IP="<PUBLIC_IP_OF_THE_K8S_CLUSTER_ON_AKS>"

# Name to associate with public IP address
DNSNAME="<DESIRED_FQDN_PREFIX>" // FQDN will then be DNSNAME.ZONE.cloudapp.azure.com

# Get resource group and public ip name
RESOURCEGROUP=$(az network public-ip list --query "[?ipAddress!=null]|[?contains(ipAddress, '$IP')].[resourceGroup]" --output tsv)
PIPNAME=$(az network public-ip list --query "[?ipAddress!=null]|[?contains(ipAddress, '$IP')].[name]" --output tsv)

# Update public ip address with dns name
az network public-ip update --resource-group $RESOURCEGROUP --name  $PIPNAME --dns-name $DNSNAME
```
Please let me know, if you have any comments about this approach.

**Comment by tomasr** [comment]
Ahh, you were referring to simply ensuring that the public ip associated with the load balancer has a DNS name. Yes, that seems fine to me.

I still prefer to use external-dns for my scenario (it makes managing stuff a lot simpler).

**Comment by ablekh** [comment]
Yes, that's what I was referring to. However, it's a bit tricky in my case due to using a JupyterHub Helm chart, which can set ingress and related things (e.g., TLS termination) declaratively. I will take time to explore `external-dns` to see, if it can work well for my JupyterHub case. I also plan to use Azure Files for persistence, so, seeing that you have experience with that (looked briefly at your blog), I might have some questions for you, if you don't mind. :-) Thanks again!

**Comment by ablekh** [comment]
@tomasr Good to know. Thank you for all your help. Will be in touch. :-)

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
