### ISSUE TITLE
 tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by ayanguha** [Azure/AKS#612]
**What happened**:
- kubectl can get pods and services, but not able to access dashboard. 

**What you expected to happen**:
Kube Dashboard shows up in browser

**How to reproduce it (as minimally and precisely as possible)**:

> az aks browse --resource-group RGXX --name XXX

```
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
error: error upgrading connection: error sending request: Post https://REDACTED-REDACTED-5f6b46-561ac7e0.hcp.REDACTED.azmk8s.io:443/api/v1/namespaces/kube-system/pods/kubernetes-dashboard-REDACTED/portforward: tls: **first record does not look like a TLS handshake**

```
Same error with from 

`kubectl port-forward kubernetes-dashboard-68f8cc4d8c-n6rq4 8001:9090 --namespace kube-system`

**Environment**:

- Kubernetes version (use `kubectl version`):
kubectl version

```
> Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
> Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9", GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean", BuildDate:"2018-06-29T01:07:01Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
