### ISSUE TITLE
Default TLS Rule

### ISSUE THREAD

**Issue by moomzni** [Azure/AKS#613]
When a new cluster is provisioned a default NSG rule entitled `Allow_Kube_TLS` is created which to my understanding serves no purpose given Master -> Agent communication happens via alternative means.

In a scenario where you wish to whitelist access to your cluster using the `loadbalancersourceranges` nginx ingress annotation this rule is quite problematic as it basically allows blanket access to your cluster from the internet (which is obviously bad).

This rule should be removed if it is not actually needed.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
