### ISSUE TITLE
Warning, when provisioning AKS with custom subnet.

### ISSUE THREAD

**Issue by Nuke1234** [Azure/AKS#614]
Hello!

Getting some new wired output when trying to provisoning  an AKS.

'''

Waiting for AAD role to propagate[###                                 ]  10.0000%
Waiting for AAD role to propagate[#######                             ]  20.0000%
Waiting for AAD role to propagate[##########                          ]  30.0000%
Waiting for AAD role to propagate[##############                      ]  40.0000%
Waiting for AAD role to propagate[##################                  ]  50.0000%
Waiting for AAD role to propagate[#####################               ]  60.0000%
Waiting for AAD role to propagate[#########################           ]  70.0000%
Waiting for AAD role to propagate[############################        ]  80.0000%
Waiting for AAD role to propagate[################################    ]  90.0000%WARNING: Could not create a role assignment for subnet. Are you an Owner on this subscription?
'''

This warning indicates that i have to be owner of the subscription when i want to provision a cluster properly. Is this right?

**Comment by jskulavik** [comment]
Hi @Nuke1234,

In order for AKS to securely manage and provision your clusters you should be owner or administrator of the subscription under which you are creating your AKS cluster.

**Comment by Nuke1234** [comment]
You should really re-think how the direction in which you are developing the AKS. To make every service principal who provisions AKS administrator or owner of the subscription is not acceptable.

**Comment by jskulavik** [comment]
Thank you for the feedback @Nuke1234.  _Contributor_ role should work as well.  Does your service principal have that role?

**Comment by Nuke1234** [comment]
No, it has only access to the resource group where the aks and the vnets are provisioned in and to the log analytics workspace. That should be enough.

**Comment by jdogg89** [comment]
I'm having the exact same issue. I'm a subscription owner and having the same issue: 

Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for subnet. Are you an Owner on this subscription?
Deployment failed. Correlation ID: xxxxxxxxxx. Provisioning of resource(s) for container service aksInfraDev in resource group InfraDev failed. Message: Operation results in exceeding quota limits of Core. Maximum allowed: 10, Current in use: 6, Additional requested: 6. Please read more about quota increase at http://aka.ms/corequotaincrease.. Details:

**Comment by sdktr** [comment]
Having the same issue. 
```
Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for subnet. Are you an Owner on this subscription?
```
Not sure about whos role it is complaining though? Does this error mean that the SPN can't claim the right permissions?

 I see the SPN getting created, and I end up with a working AKS cluster as well, but that seems to be unable to instruct the vnet to get the right Service-IPs delegated..

Using AZ CLI:
```
az aks create --resource-group RGROUP \
--name AKSCLUSTER2 \
--vnet-subnet-id /bla/resourceGroups/RGROUP/providers/Microsoft.Network/virtualNetworks/my-vnet/subnets/AKSCLUSTER2-subnet --network-plugin azure \
--docker-bridge-address 169.254.0.1/16 \
--dns-service-ip 172.21.6.10 \
--service-cidr 172.21.6.0/24 \
--kubernetes-version 1.10.6 \
--no-ssh-key \
--no-wait \
--node-count 2 \
--node-vm-size Standard_D2s_v3 \
--max-pods 60 \
--aad-server-app-id 1111 \
--aad-server-app-secret 2222 \
--aad-client-app-id 3333\
--aad-tenant-id 44444 \
--enable-addons monitoring
```

**Comment by DenisBiondic** [comment]
I agree. I am having the same issue, and only way to bypass this error is to manually assign the cluster SP to the subnet as Network Contributor (this is what the command is trying to do under the hood). It is not enough to assign the SP at subscription / resource group or VNET, I had to explicitly set it on the subnet itself.

In the end, I don't get how can I assign the SP as network contributor through the portal, but under same account (my account) with azure cli it does not work @jskulavik ?

**Comment by jdogg89** [comment]
I'll comment on this a bit later, talking to the AKS team it's not a common
problem but it comes up

**Comment by bramvdklinkenberg** [comment]
Same issue here. We don't give SP's rights on subscription level, only on Resource Groups.
I gave the SP contributor rights on the RG of the cluster and the RG of the custom vnet but that doesn't help. Will try if being owner on the RG of the custom vnet makes any difference.

**Comment by bramvdklinkenberg** [comment]
I gave the SP owner rights on the resource group where the custom vnet is in and then it works with role propagation.

**Comment by caleno** [comment]
Worked when I got User Access Administrator on the resource group used to set up AKS.

**Comment by whut** [comment]
Shoudn't it be enough for the `az aks create` command to add Network Contributor rights on the subnet, in this case Owner is needed only on the Resource Group, not on the whole Subscription. Requiring owner on whole subscription is unrealistic requirement.

**Comment by ecoffman** [comment]
Any word on this?

**Comment by jpushpanathan** [comment]
When I tried creating aks cluster using kubenet plugin and custom vNet I got the above mentioned error : Could not create a role assignment for subnet. Are you an Owner on this subscription?
Deployment failed. Correlation ID: xxxxxx-xxx-xx-xx-xx. All nodes did not reach Ready state. Expected: 2, Actual: 0
The service principle has  roleassignment permissions on the ResourceGroup on which the AKS is created. However it doesn't have permissions on the ResourceGroup of the vNet.  

1. Do i need to grant 'roleassignment' permissions for the service principle on the ResourceGroup of the vNET?
2. Do I need to give the service principle Network Contributor rights on the subnet

Can you please clarify which one is required?

**Comment by AlexanderViken** [comment]
Im haveing the same issue now... any update?

Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for subnet. Are you an Owner on this subscription?
Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for ACR. Are you an Owner on this subscription?

when calling with az aks create -g $aksrg -n $aks --attach-acr $registry --network-plugin azure --vnet-subnet-id $akssnid --service-cidr $aks_srv_cidr --dns-service-ip $aks_srv_dns --enable-addons monitoring --workspace-resource-id $logworkspaceid --node-vm-size Standard_A2_v2 --nodepool-name 
"a2v2node" --network-policy azure --aad-server-app-id $serverApplicationId --aad-server-app-secret $serverApplicationSecret --aad-client-app-id $clientApplicationId --aad-tenant-id $tenantId --generate-ssh-keys --admin-username pciaksadmin

**Comment by bas-velthuizen** [comment]
I have exactly the same issue. Is there any news on this?

> Waiting for AAD role to propagate[################################    ]  90.0000%
> Could not create a role assignment for subnet. Are you an Owner on this subscription?

**Comment by pixxet** [comment]
same here !

`Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for ACR. Are you an Owner on this subscription?
`

**Comment by oomichi** [comment]
I faced the same issue before, and I've solved my case.
In my case, the root issue is due to too small range of subnet(192.168.1.0/26) which was specifed as `--vnet-subnet-id` of `az aks create` command. And the command just shows `Could not create a role assignment for subnet. Are you an Owner on this subscription?` instead of showing the root issue.
I've made the subnet range bigger, then an AKS cluster creation succeeded, but still the message `Could not create a role assignment for subnet. Are you an Owner on this subscription?` is shown.

**Comment by nigel-dewar** [comment]
I have same issue - Waiting for AAD role to propagate[################################ ] 90.0000%Could not create a role assignment for ACR. Are you an Owner on this subscription?

**Comment by Mexicoder** [comment]
I am also experiencing this. any updates?

**Comment by RoyKimYYZ** [comment]
I'm having same issue. Creating private cluster.

**Comment by katatohuk** [comment]
Any updates on this issue ?

**Comment by sanjaypatel2003** [comment]
AKS deployment
 
All nodes did not reach Ready state. Expected: 3, Actual: 0
cli.azure.cli.core.util : Deployment failed. Correlation ID: 5b7da5a0-e272-4fa3-8ae8-0fed5bef763d. All nodes did not reach Ready state. Expected: 3, Actual: 0
Deployment failed. Correlation ID: 5b7da5a0-e272-4fa3-8ae8-0fed5bef763d. All nodes did not reach Ready state. Expected: 3, Actual: 0
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fce0c648e18>]

**Comment by TomBolton** [comment]
Having similar issues.
