### ISSUE TITLE
AKS RBAC V2.0 API

### ISSUE THREAD

**Issue by lukasmrtvy** [Azure/AKS#617]
Afaik RBAC needs to use Microsoft Graph API v1 ( https://docs.microsoft.com/en-us/azure/aks/aad-integration ), but when comes to step `7. Select Done, choose Microsoft Graph from the list of APIs, then select Grant Permissions. This step will fail if the current account is not a tenant admin.`, there is a slight problem with phrase `tenant admin`.

Will It be possible to use for example v2 oauth2 API to create application without need of tenant admin permission? I am able to integrate openid from AAD without any of these permissions and I can leverage group claims from JWT token.

Thanks

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
