### ISSUE TITLE
NGINX ingress controller with HPA results termination loop

### ISSUE THREAD

**Issue by etoriet** [Azure/AKS#618]
**What happened**:

I created AKS cluster with HTTP Application Routing. I installed some web app with deployment, service and ingress. I confirmed I can access that web app from outside the cluster via something.aksapp.io domain. I checked kube-system namespace and found that single addon-http-application-routing-nginx-ingress-controller pod runs. I thought that pod is SPOF. So I wrote HorizontalPodAutoscaler setting to modify num of replicas and apply it.

```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  namespace: kube-system
  name: nginx-ingress
spec:
  maxReplicas: 2
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: addon-http-application-routing-nginx-ingress-controller
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
```

I checked kube-system namespace and saw that new pod is repeatedly created and terminated. New pod is sent SIGTERM after some seconds from created.

**What you expected to happen**:

New pod should not be sent SIGTERM.

**How to reproduce it (as minimally and precisely as possible)**:

Please see above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster: 6
- General description of workloads in the cluster: HTTP microservices
- Others:

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
