### ISSUE TITLE
Unable to communicate with newly created cluster

### ISSUE THREAD

**Issue by ncdc** [Azure/AKS#62]
I ran this:

```bash
$ az aks create -g andy-heptio -n andy -l eastus -c 1
```

It created my cluster. I then did:

```bash
$ az aks get-credentials -g andy-heptio -n andy -a -f ./aks.kubeconfig
$ export KUBECONFIG=`pwd`/aks.kubeconfig
$ kubectl get nodes
Unable to connect to the server: net/http: TLS handshake timeout
```

Attempts to `curl` the public DNS entry also just hang.

**Comment by jmalobicky** [comment]
I am getting this same error with
`kubectl get ns`

Response - `Unable to connect to the server: net/http: TLS handshake timeout`

**Comment by jmalobicky** [comment]
I was able to deploy into `centralus` as a test. I did not get an error connecting with `kubectl`

**Comment by ncdc** [comment]
I just tested again and now my cluster is accessible. It says my node is only 4 minutes old (?!?).

**Comment by jmalobicky** [comment]
I have an open support ticket with Azure. Seems that eastus and westeurope gave me issues - where centralus worked. I cannot use centralus as my other services are available there.

I will give eastus a try again later. Thanks @ncdc for the heads up.

**Comment by jmalobicky** [comment]
Looks like `eastus` is working for me as well now

**Comment by hanzenok** [comment]
Hi everyone,

Having same issue today on westeurope. And when I try to create a new cluster in this location, it gives an error:
Deployment failed. Correlation ID: <id>. Azure Container Service is unable to provision an AKS cluster in westeurope, due to an operational threshold. Please try again later or use an alternate location. For more details please refer to: https://github.com/Azure/AKS/blob/master/preview_regions.md.

**Comment by amanohar** [comment]
@hanzenok this should be resolved now. Please try again and let us know if you are still experiencing this issue.

**Comment by hanzenok** [comment]
@amanohar cluster creation is now working on westeurope. Thank you.

_PS:_ the nodes are not there (when i do `kubectl get nodes` the response is `No resources found.`). I don't know whether there is an issue with the cluster not provisioning nodes correctly or it's just an error from my side

**Comment by slack** [comment]
Closing out this issue, clusters should be provisioning successfully.

**Comment by alexvicegrab** [comment]
Getting the operational threshold issue once again.

**Comment by slack** [comment]
We are bumping up against our provisioned limit in West Europe as of afternoon of Feb 14 (Pacific).

**Comment by alexvicegrab** [comment]
I have a similar issue. Can't create in West Europe - "thresholding"
