### ISSUE TITLE
Error deleting load balancer (will retry): timed out waiting for the condition

### ISSUE THREAD

**Issue by yuwzho** [Azure/AKS#621]
**What happened**:

* I add a `lock` to my AKS resource group to prevent deleting resources
* I create a service with type `loadbalancer`  to expose a pod named `abc`. 
     - AKS works properly to creating an Azure Public IP and associate to Azure LoadBalancer.
* I execute `kubectl delete svc abc`
     - At this time, kubectl returns deleted successfully, I can no longer touch the service abc.
     - Azure LoadBalancer and Azure Public IP successfully unassociate.
     - Azure Public IP failed to be deleted due to the lock.
* I recreate the service name `abc`.
     - The event log hangs with message `Error deleting load balancer (will retry): timed out waiting for the condition`.
     - Nothing happen on the Azure LoadBalancer resource and nothing happen to the existing Azure Public IP or creating a new one.

**What you expected to happen**:
From code logic, it seems nothing wrong. But from user's perspective, I wonder if there is a command to delete all the event log when deleting the service. Then the new created service can go properly without suffer the previous error.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a lock to resource group to prevent delete
1. Create a service
1. Delete the service
1. Recreate the service

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by andyzhangx** [comment]
azure `lock` means user cannot delete any azure resource under that resource group, while k8s would delete azure resource when you delete a service, then you will get that error. I think this behavior should be expected.

**Comment by yuwzho** [comment]
@andyzhangx Yes, as I mentioned, this behavior is expected from the code logic. But from user's perspective, the previous deletion failed should have no effect on creation new pip and associate to LB. So I wonder whether there is a way to skip the state check for previous resource, but start a "new session" for the new same-name resource.

**Comment by alanblythe** [comment]
I have found this issue to be difficult as well. Also in Azure btw. I don't have direct control over DNS and need to be able to ensure that IP addresses aren't lost. 
I'm currently figuring out how to get past this issue. I changed an IP address on an Ingress and the service is stuck in a pending state trying to delete the load balancer, I assume the old IP address.
This was after I deleted the ingress and recreated.
I'm curious if there is a way to purge this resource when deleted so I can start fresh as yuwzho mentioned.

**Comment by palma21** [comment]
Have you removed the lock and deleted the service? Or deleted the IP or LB manually?
Alternatively create the IP manually and specify it at svc manifest, so the lb will pick this new IP

And to avoid this, place the IPs in a different RG than the cluster, so you can leave a lock in the cluster RG but not on the IP RG.
Define the IPs on the svc manifest using annotations as per:
https://github.com/kubernetes/cloud-provider-azure/blob/master/docs/azure-loadbalancer.md

**Comment by yuwzho** [comment]
I don't think this is a solution for this issue, since as a user I must clearly knows what's the Azure resources' behavior when I wanna manage the K8S resources. That's is all because the new created k8s resources goes to check previous one's log, which doesn't make sense. For instance, when you create an Azure resource A, and put it in a poor condition then delete it, after that you wanna create another A, it founds the previous A is in a poor condition and prevent you creating a new one. They are totally two isolated items.
