### ISSUE TITLE
Data disks with scaleset VM.

### ISSUE THREAD

**Issue by raihanchdy** [Azure/AKS#622]
I have multiple data disks attached to scaleset Vm's. I changed the tag of disk to a different name and observed that randomly one attached data disk is getting deleted while terminating scaleset VM.

I am concerned about my data and this is strange behavior, not sure by taking whose permission, azure itself deleting data disks.

**Comment by raihanchdy** [comment]
Hi,


I attach data disks using azure cli.


I found that If disks tagging is modified after disk attachment to the VM and then delete VM, then it deletes the data disks. But changing disk tagging before disk attachment to the VM and then deleting VM does not delete data disks.



Thanks,

Raihan


________________________________

**Comment by andyzhangx** [comment]
![image](https://user-images.githubusercontent.com/4178417/44775528-6f011f00-aba8-11e8-8d92-025fea30517f.png)

disk deleted after vmss VM deleted, this should be expected, it's not related to disk tags.

**Comment by raihanchdy** [comment]
Hi,


I can show u the live scenario where I am deleting vm's but additional data disks are not getting deleted.


This does not make any sense like deleting vm's will also delete data disks where I store my data.Then azure is not safe to keep data.


As I told you that disks are getting deleted only after changing tag. Did so many times that testing and can show you live scenario.Assuming its and azure bug.


Thanks,

Raihan




________________________________

**Comment by andyzhangx** [comment]
as I know, only vmss vm will delete data disk when deleting vm, I don't know why. Normal VM won't have that behavior, I think you could file a vmss  related support ticket and get answer.

**Comment by andyzhangx** [comment]
Hi @raihanchdy I have reported this issue to internal vmss group, let's their repsonce. Thanks for your info, that's helpful, I am not aware of this issue before.

**Comment by andyzhangx** [comment]
Hi @raihanchdy, I tried a few times and did not repro this issue any more.
chose this issue now, let me know if you have any question.
