### ISSUE TITLE
az aks get-credentials incorrectly merges config

### ISSUE THREAD

**Issue by blacksails** [Azure/AKS#623]
**What happened**:

Ran `az aks get-credentials` on new cluster with same name as old, created duplicate enties in the kubeconfig, which rendered it invalid. 

**What you expected to happen**:

I would expect that the tool could not incorrectly merge the config file

**How to reproduce it (as minimally and precisely as possible)**:

- create a cluster and run `az aks get-credentials -g <group> -n <name>`
- delete cluster and do the above again
- run `kubectl get nodes`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.2
- Size of cluster (how many worker nodes are in the cluster?) not relevant
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) not relevant
- Others:

**Comment by marrobi** [comment]
Yup, seen this a few times myself.  Thanks @blacksails I should have reported it.

**Comment by mathieu-benoit** [comment]
Got the same issue with old/deleted cluster. Looks like it should be handled by the Azure CLI itself?
https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py
Workaround: edit manually the .jube/config file by removing the old entries.

**Comment by mkyc** [comment]
Setting up and tearing down aks clusters almost everyday I see it often.

**Comment by StianOvrevage** [comment]
Just got hit by this one.
