### ISSUE TITLE
AKS working node gets automatically restarted

### ISSUE THREAD

**Issue by ypfedotov** [Azure/AKS#624]
Hello,

My virtual machine used as a working node in an AKS cluster is automatically restarted several times a day via the service principal. How can I find out the reason for this and disable this behavior?

I have a cluster with a single node (Standard B2s (2 vcpus, 4 GB memory)), Kubernetes v1.10.6.

Activity log of the VM has records similar to the following:

Restart Virtual Machine | Succeeded | 3 h ago | Tue Aug 28 2018 16:15:56 GMT+0300 (Moscow Standard Time) | Free Trial | (service principal id)

Resource Health tab reports the following:

08/28/2018 | 2 health event(s) |   | 2 health event(s)
-- | -- | -- | --
  | 2 health event(s)
16:13 - 16:16 | This virtual machine is rebooting as requested by an authorized user or process. It will be back online after the reboot completes. |   | This virtual machine is rebooting as requested by an authorized user or process. It will be back online after the reboot completes.
  | This virtual machine is rebooting as requested by an authorized user or process. It will be back online after the reboot completes.
12:16 - 12:19 | This virtual machine is rebooting as requested by an authorized user or process. It will be back online after the reboot completes. |   | This virtual machine is rebooting as requested by an authorized user or process. It will be back online after the reboot completes.
  | This virtual machine is rebooting as requested by an authorized user or process. It will be back online after the reboot completes.
08/27/2018 | 2 health event(s), 7 health annotation(s) |   | 2 health event(s), 7 health annotation(s)
  | 2 health event(s), 7 health annotation(s)
13:59 | The configuration of this virtual machine is being updated as requested by an authorized user or process |   | The configuration of this virtual machine is being updated as requested by an authorized user or process
  | The configuration of this virtual machine is being updated as requested by an authorized user or process
13:52 | The configuration of this virtual machine is being updated as requested by an authorized user or process |   | The configuration of this virtual machine is being updated as requested by an authorized user or process
  | The configuration of this virtual machine is being updated as requested by an authorized user or process
13:35 - 13:36 | The configuration of this virtual machine is being updated as requested by an authorized user or process |   | The configuration of this virtual machine is being updated as requested by an authorized user or process
  | The configuration of this virtual machine is being updated as requested by an authorized user or process
13:25 | This virtual machine is starting as requested by an authorized user or process. It will be online shortly. |   | This virtual machine is starting as requested by an authorized user or process. It will be online shortly.
  | This virtual machine is starting as requested by an authorized user or process. It will be online shortly.
13:25 | Hardware resources have been assigned to the virtual machine and it will be online shortly |   | Hardware resources have been assigned to the virtual machine and it will be online shortly
  | Hardware resources have been assigned to the virtual machine and it will be online shortly
13:22 | This virtual machine is stopping and deallocating as requested by an authorized user or process |   | This virtual machine is stopping and deallocating as requested by an authorized user or process
  | This virtual machine is stopping and deallocating as requested by an authorized user or process
12:57 | We're sorry, your virtual machine isn't available because an unexpected failure on the host server |   | We're sorry, your virtual machine isn't available because an unexpected failure on the host server
  | We're sorry, your virtual machine isn't available because an unexpected failure on the host server
12:57 | This virtual machine is rebooting as requested by an authorized user or process. It will be back online after the reboot completes. |   | This virtual machine is rebooting as requested by an authorized user or process. It will be back online after the reboot completes.
  | This virtual machine is rebooting as requested by an authorized user or process. It will be back online after the reboot completes.

The stop-start actions at 13:22 - 13:25 have been initiated by me, all the others have been initiated automatically.

**Comment by andyzhangx** [comment]
what does `automatically` mean? what's the `EVENT INITIATED BY` value of `Activity log of the VM`? is it by service principal?

**Comment by notenbrood** [comment]
@andyzhangx 
I believe I encountered the same issue, and can provide a more accurate history of what happened in hopes of allowing the AKS team to reproduce the issue.

I'm also running a single node cluster to evaluate the AKS offering. I created a few deployments, deploying some pods without assigning resource limits. One of the containers started using an increasing amount of memory until the host went out of memory. Kubernetes of course started evicting the pod, only to reschedule it to the same node again, at which point the pod can start again until it consumes so much memory that the same cycle happens again. So far, this is all expected behaviour.

However, we noticed that the Virtual Machine that runs the single AKS node kept restarting during this crash looping behaviour:
[Activity log of virtual machine](https://i.imgur.com/zfxZETw.png)

You can see that the VM is being restarted by the azure-cli. It seems as if there's a policy that will automatically restart the VM when it comes under memory pressure.. but I'm not sure this is desired behaviour for an AKS node, as if you would have sufficient resources and nodes in the pool this pod would just get rescheduled to a different node, and I don't think we should make the assumption that Kubernetes can always reschedule that single pod in time before it exceeds that memory limit that it will cause Azure to reboot the VM.

Worst part about this is that the rebooting of the node VM seems to have caused networking issues as well, as no kubectl commands that redirect to the node itself could be executed anymore (although this issue seems to have repaired itself over the past few days). This is kind of worrisome, as according to kubectl describe node, for kubernetes the node was completely healthy.

**Comment by brobichaud** [comment]
I am seeing similar behaviour on my k8s 1.10.9 cluster with Windows v1803 nodes. I've been unable to pin down why it happens and when, but I see the same long list of Health Events in the VMs Activity Log.

![image](https://user-images.githubusercontent.com/5625540/50190059-9822f800-02dc-11e9-9b05-9ebd4ce99eb9.png)

And here's the details from one of the events:

> {
>     "channels": "Admin, Operation",
>     "correlationId": "3783ceef-3c72-4d8d-848d-d0f9dd63dfc5",
>     "description": "",
>     "eventDataId": "59a1b14f-a2b8-4e63-80cb-f326dff5f94c",
>     "eventName": {
>         "value": "",
>         "localizedValue": ""
>     },
>     "category": {
>         "value": "ResourceHealth",
>         "localizedValue": "Resource Health"
>     },
>     "eventTimestamp": "2018-12-18T22:11:55.501Z",
>     "id": "/subscriptions/{{omitted}}/resourceGroups/live-kube4/providers/Microsoft.Compute/virtualMachines/20269k8s9000/events/59a1b14f-a2b8-4e63-80cb-f326dff5f94c/ticks/636807679155010000",
>     "level": "Informational",
>     "operationId": "",
>     "operationName": {
>         "value": "Microsoft.Resourcehealth/healthevent/InProgress/action",
>         "localizedValue": "Health Event InProgress"
>     },
>     "resourceGroupName": "live-kube4",
>     "resourceProviderName": {
>         "value": "Microsoft.Resourcehealth/healthevent/action",
>         "localizedValue": "Microsoft.Resourcehealth/healthevent/action"
>     },
>     "resourceType": {
>         "value": "Microsoft.Compute/virtualMachines",
>         "localizedValue": "Microsoft.Compute/virtualMachines"
>     },
>     "resourceId": "/subscriptions/{{omitted}}/resourceGroups/live-kube4/providers/Microsoft.Compute/virtualMachines/20269k8s9000",
>     "status": {
>         "value": "Updated",
>         "localizedValue": "Updated"
>     },
>     "subStatus": {
>         "value": "",
>         "localizedValue": ""
>     },
>     "submissionTimestamp": "2018-12-18T22:16:54.7037638Z",
>     "subscriptionId": "{{omitted}}",
>     "properties": {
>         "title": "A reboot was triggered from inside the virtual machine. This could be due to a virtual machine operating system failure or as requested by an authorized user or process. The virtual machine will be back online after the reboot completes.",
>         "details": "",
>         "currentHealthStatus": null,
>         "previousHealthStatus": null,
>         "type": "Downtime",
>         "cause": "UserInitiated"
>     },
>     "relatedEvents": []
> }

**Comment by dcvtruong** [comment]
Looks like this issue is unsolved and it it closed, why?

**Comment by jnoller** [comment]
@dcvtruong Because this is known / behavior for worker nodes we detect are hard failing. More than likely the actual cause of the failure (not the reboot) is this: https://github.com/Azure/AKS/issues/1373

the linked issue requires use modification of the worker nodes to resolve.
