### ISSUE TITLE
AKS VM Disk Encryption

### ISSUE THREAD

**Issue by kHRISl33t** [Azure/AKS#629]
**What happened**:

I wanted to encrypt a VM under AKS, but it failed in OS Disk Encryption.

I got these messages during the encryption:
(using: `az vm encryption show --resource-group resource-group --name VMname`)

```
"progressMessage": "Encryption succeeded for data volumes"
```
```
"progressMessage": "Attempt #7 to unmount /oldroot failed with error: Command umount /oldroot failed with return code 32\nstdout:\n\nstderr:\numount: /oldroot: target is busy\n        (In some cases useful info about processes that\n         use the device is found by lsof(8) or fuser(1).)\n, stack trace: Traceback (most recent call last):\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/main/oscrypto/ubuntu_1604/Ubuntu1604EncryptionStateMachine.py\", line 170, in start_encryption\n    self.retry_unmount_oldroot()\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/transitions/transitions/core.py\", line 222, in trigger\n    return self.machine.process(f)\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/transitions/transitions/core.py\", line 526, in process\n    return trigger()\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/transitions/transitions/core.py\", line 247, in _trigger\n    if t.execute(event):\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/transitions/transitions/core.py\", line 145, in execute\n    machine.callback(func, event_data)\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/transitions/transitions/core.py\", line 518, in callback\n    func(*event_data.args, **event_data.kwargs)\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/main/oscrypto/ubuntu_1604/Ubuntu1604EncryptionStateMachine.py\", line 114, in on_enter_state\n    super(Ubuntu1604EncryptionStateMachine, self).on_enter_state()\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/main/oscrypto/OSEncryptionStateMachine.py\", line 65, in on_enter_state\n    self.state_objs[self.state].enter()\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/main/oscrypto/ubuntu_1604/encryptstates/UnmountOldrootState.py\", line 134, in enter\n    self.command_executor.Execute('umount /oldroot', True)\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/main/CommandExecutor.py\", line 73, in Execute\n    raise Exception(msg)\nException: Command umount /oldroot failed with return code 32\nstdout:\n\nstderr:\numount: /oldroot: target is busy\n        (In some cases useful info about processes that\n         use the device is found by lsof(8) or fuser(1).)\n\n"
```
```
"progressMessage": "Failed to encrypt OS volume with error: Attempt #11 to unmount /oldroot failed with error: Could not unmount /oldroot in 10 attempts, stack trace: Traceback (most recent call last):\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/main/oscrypto/ubuntu_1604/Ubuntu1604EncryptionStateMachine.py\", line 168, in start_encryption\n    raise Exception(\"Could not unmount /oldroot in 10 attempts\")\nException: Could not unmount/oldroot in 10 attempts\n, stack trace: Traceback (most recent call last):\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/main/handle.py\", line 1619, in daemon_encrypt\n    os_encryption.start_encryption()\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/main/oscrypto/ubuntu_1604/Ubuntu1604EncryptionStateMachine.py\", line 185, in start_encryption\n    raise Exception(message)\nException: Attempt #11 to unmount /oldroot failed with error: Could not unmount /oldroot in 10 attempts, stack trace: Traceback (most recent call last):\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/main/oscrypto/ubuntu_1604/Ubuntu1604EncryptionStateMachine.py\", line 168, in start_encryption\n    raise Exception(\"Could not unmount /oldroot in 10 attempts\")\nException: Could not unmount /oldroot in 10 attempts\n\n, machine state: unmount_oldroot"
```

and after some time it shows `"osDisk": "Unknown"` and if I run `kubectl get nodes` the VM is in NotReady state (restart did not help to get it back on).

My VM is a Standard DS2 v2 (2 vcpus, 7 GB memory), so memory should be enough for this.

**What you expected to happen**:

It should encrypt my VM and `az vm encryption show --resource-group resource-group --name VMname` should show `VMRestartPending`

**How to reproduce it (as minimally and precisely as possible)**:

I ran these commands in the exact same order (from cluster creation to encryption):

```
$ az aks create \
  --name test-cluster \
  --resource-group test-cluster \
  --location westeurope \
  --node-count 3 \
  --node-vm-size Standard_DS2_v2
  --kubernetes-version 1.11.2 \
  --debug

$ az aks get-credentials --resource-group test-cluster --name test-cluster

$ az provider register -n Microsoft.KeyVault

$ az keyvault create \
    --name mynode-keyvault \
    --resource-group MC_test-cluster_test-cluster_westeurope \
    --location westeurope \
    --enabled-for-disk-encryption True

$ az keyvault key create --vault-name mynode-keyvault --name mynode-keyvault-key --protection software

# save appId and password 
$ az ad sp create-for-rbac

$ az keyvault set-policy --name mynode-keyvault --spn appId \
  --key-permissions wrapKey \
  --secret-permissions set

$ az vm encryption enable \
    --resource-group MC_test-cluster_test-cluster_westeurope \
    --name nodename \
    --aad-client-id appId \
    --aad-client-secret password \
    --disk-encryption-keyvault mynode-keyvault \
    --key-encryption-key mynode-keyvault-key \
    --volume-type all
```

**Anything else we need to know?**:

**Environment**: AKS
- Kubernetes version (use `kubectl version`):  Kubernetes 1.11.2
- Size of cluster (how many worker nodes are in the cluster?) 3 with Standard DS2 v2 (2 vcpus, 7 GB memory)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) istio & node.js
- Others:

**Comment by andyzhangx** [comment]
I think you should open an azure support ticket to vm encryption group, it's not related to AKS itself since you hit error when do `az vm encryption enable` command

**Comment by andyzhangx** [comment]
UI is cheating you in disk encrypted item, sometimes it shows encrypted even it failed finally. anyway, you could open a ticket no matter it failed inside or in portal.

**Comment by kHRISl33t** [comment]
Okay, thanks. Will try it again.
Will update this issue if I have a solution.

**Comment by kHRISl33t** [comment]
According to the answer of Azure support: 

```
Regret to say that currently Encryption for AKS agent node is not possible.
```

**Comment by jrx-sjg** [comment]
Have anyone finally be able to encrypt data disk? I used the method above, but I couldn't do it work because dinamics pv are not "mappeable" on fstab

**Comment by kHRISl33t** [comment]
> Have anyone finally be able to encrypt data disk? I used the method above, but I couldn't do it work because dinamics pv are not "mappeable" on fstab

Data Disk encryption should work if you specify `--volume-type Data` .
The problem for me was the OS Disk encryption. I had to encrypt both Data and OS disk.
Did not had to work on Azure since December, so I don't know what's the status.

**Comment by jnoller** [comment]
Currently all data at rest is encrypted at rest in Azure DCs, however user requested disk encryption for AKS nodes is not supported. We have this on the roadmap. 

Marking as roadmap and known-issue

**Comment by aelij** [comment]
As an alternative to Azure Disk Encryption, you could use a new feature (now in preview) - [Server-side encryption of Azure managed disks](https://azure.microsoft.com/en-us/blog/preview-server-side-encryption-with-customer-managed-keys-for-azure-managed-disks/), which encrypts the disks at the storage level and supports any OS.

**Comment by andyzhangx** [comment]
We already added SSE+CMK support on data disk in k8s v1.17.0: https://github.com/kubernetes/kubernetes/pull/84605, os disk encryption support would also be on that version

**Comment by Benjiiim** [comment]
1.17.0 is now in preview in AKS. Should we consider SSE + CMK the best option or is there any reason to wait for the support of ADE?

**Comment by andyzhangx** [comment]
SSE+CMK feature is already supported on AKS in some regions now, here is the draft dev doc: https://github.com/andyzhangx/demo/tree/master/aks/byok

**Comment by andyzhangx** [comment]
BTW, we won't support ADE on AKS, it's not in the roadmap

**Comment by aelij** [comment]
AFAIK SSE+CMK does not encrypt the premium disk [blob cache](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/premium-storage-performance#disk-caching), nor the ephemeral drive, so ADE remains the only comprehensive disk encryption solution.

**Comment by kHRISl33t** [comment]
> SSE+CMK feature is already supported on AKS in some regions now, here is the draft dev doc: https://github.com/andyzhangx/demo/tree/master/aks/byok

should I close the issue? Since the above seems to solve my original problem.

**Comment by andyzhangx** [comment]
BYOK(SSE+CMK) is available now: https://aka.ms/aks/byok
