### ISSUE TITLE
Dashboard permission mapping from RBAC

### ISSUE THREAD

**Issue by suonto** [Azure/AKS#630]
**What happened**: This is a feature request. Dashboard is using serviceaccount, but it could use [login-view](https://github.com/kubernetes/dashboard/wiki/Access-control#login-view).

**What you expected to happen**: I'd like to automatically map user RBAC privileges for dashboard instead of using  a service account. Login view already does this. Without this, it is not an option to grant non-admins access to dashboard and they will be very sad. With mapping, it's ok to expose dashboard with an internal ingress entry and developers are forced to admire AKS awesomeness.

**Environment**:
- Kubernetes version: 1.11.0
- Dashboard image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
