### ISSUE TITLE
What is the recomended policy for updating kubernetes-dashboard on AKS?

### ISSUE THREAD

**Issue by joaocc** [Azure/AKS#631]
What is the recommended way to upgrade kubernetes-dashboard on AKS on existing clusters?
Shall we wait for it to updates to be automagically deployed on kubernetes version upgrades?
Shall we manually upgrade it via the standard kubernetes mechanism https://github.com/kubernetes/dashboard/?
Thx

**Comment by jnoller** [comment]
The dashboard and its versions are managed by the AKS team. Users do not have control over the kubernetes dashboard version at this time. Closing as stale
