### ISSUE TITLE
AKS /etc/kubernetes/azure.json invalid JSON

### ISSUE THREAD

**Issue by mariojacobo** [Azure/AKS#633]
**What happened**:
AKS has invalid JSON boolean values  in /etc/kubernetes/azure.json. This breaks functionality with a variety of 3rd party images, such as Hexadite InitContainers (see https://github.com/Hexadite/acs-keyvault-agent/issues/13)

**What you expected to happen**:
The JSON should be vaild 

**How to reproduce it (as minimally and precisely as possible)**:
See https://github.com/Hexadite/acs-keyvault-agent 

**Anything else we need to know?**:

Fix:

Wrong:
"cloudProviderBackoff": True,
"cloudProviderRatelimit": True,

Correct:
"cloudProviderBackoff": true,
"cloudProviderRatelimit": true,

**Environment**: 
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by PashaPash** [comment]
@mariojacobo should be fixed by https://github.com/Azure/acs-engine/pull/3774

**Comment by mariojacobo** [comment]
Thank you. looks good now, just checked with a new cluster

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
