### ISSUE TITLE
AD RBAC Integration issue with AKS

### ISSUE THREAD

**Issue by sansow** [Azure/AKS#638]
Following the documentation [here](https://docs.microsoft.com/en-us/azure/aks/aad-integration) to enable the rbac. After running the get-credentials by login to az using the account given permission to k8s cluster getting below error after the authentication. 

kubectl get node
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code A6VCX8SHF to authenticate.

**E0905 19:28:21.243559    1104 azure.go:126] Failed to acquire a token: acquiring a new fresh token: waiting for device code authentication to complete: autorest/adal/devicetoken: Error while retrieving OAuth token: Unknown Error
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code AEUHVMF4D to authenticate.
E0905 19:28:53.294255    1104 round_trippers.go:169] CancelRequest not implemented**

Any idea how to fix the error?

Kubernetes version
1.10.7

**Comment by sowsan** [comment]
Any comments ?

**Comment by jnoller** [comment]
Hi @sansow - Thanks for bringing this up - as we can not debug specific customer cluster issues on github please file an Azure technical support ticket so we can get the needed SubID/etc information to diagnose.
