### ISSUE TITLE
Generate Client certificate for authentication

### ISSUE THREAD

**Issue by tgarlot** [Azure/AKS#64]
Hi,

I would like to use client certificate (https://kubernetes.io/docs/admin/authentication/#x509-client-certs). Except if I missed something, I do not see how to do it without getting the cluster private key which is on the master... And we do not have access to it anymore...

So any solution for that?

**Comment by slack** [comment]
We don't supoprt client-certificate based authentication at the moment. We do have Azure Active Directory integration on the roadmap, which would let your users `kubectl login`, auth through AAD and arrive in cluster with a concrete user identity.
