### ISSUE TITLE
Get cluster name from DownwardAPI and pass it like env variable to pods?

### ISSUE THREAD

**Issue by lukasmrtvy** [Azure/AKS#640]
Is possible to somehow get a cluster name to pass this like ENV variable directly to pods ?
For example https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api
I want to use this info to determine instance of AKS. 
Super useful information for tools/sidecars like logstash, fluentd, etc.. 
Thanks

**Comment by ahaeber** [comment]
Currently not possible in Kubernetes. This is not AKS specific but a limitation in Kubernetes and the Downward API itself. See https://github.com/kubernetes/kubernetes/issues/65885

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
