### ISSUE TITLE
Assigning New VNet to a Existing AKS Cluster

### ISSUE THREAD

**Issue by jkriba** [Azure/AKS#641]
**What happened**:
Want to assign a New VNet to an existing AKS Cluster

**What you expected to happen**:
We should be able to assign / apply a VNet post creating a AKS cluster or which has been already created

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a AKS cluster without advanced networking
2. Deploy the AKS cluster and get it up and working
3. Create a New VNet 
4. There is now way you can assign this VNet to the ASK cluster we have already created

**Environment**:
- Kubernetes version : 1.11.2
- Size of cluster : 2
- General description of workloads in the : HTTP microservices
- Others: We have Ingress Controller in it

**Comment by seanmck** [comment]
This is a significant new feature ask. Please file a request in our feedback forum:
https://aka.ms/aks/feedback
