### ISSUE TITLE
Frequent problems with timeouts, solved by restarting the tunnelfront pod

### ISSUE THREAD

**Issue by mrdfuse** [Azure/AKS#642]
**What happened**:
We often get different kind of timeout exceptions when interacting with an AKS cluster (we have this on all our clusters), doing stuff like kubectl logs, or creating pods, or .. The pods themselves keep running well once they are created.

Example:
```
F0910 10:46:37.182478 4856 helpers.go:119] Error from server: Get
 
https://aks-nodepool1-29932867-1:10250/containerLogs/test/xxxxxxxxxxx-5fbfbb4ff7-nhzhv/xxxxxxxxxx?follow=true
: dial tcp 10.240.0.5:10250: getsockopt: connection timed out
```
I have created several tickets with Azure Support, and I always get the advice to look at the tunnelfront's health. Which is always ok, no errors in the logs. But even then it seems that these issues are always resolved by killing the tunnelfront pod and letting the deployment create a new one.

**What you expected to happen**:
I suppose this happens when something on the master's infrastructure changes, and the existing tunnelfront pod doesn't notice this correctly. I expect the tunnelfront pod to keep working correctly when something on the master's side changes.

**How to reproduce it (as minimally and precisely as possible)**:
Can't reproduce it, happens randomly on any AKS cluster.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.6
- Size of cluster (how many worker nodes are in the cluster?) from 3 to 6
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Java and nodejs apps, Tiller
- Others:

**Comment by Novitoll** [comment]
+1

**Comment by Strandedpirate** [comment]
This has been a major issue for more than a year. The official response from support is to delete the tunnelfront pod and it will get re-created.

`
kubectl -n kube-system delete po tunnelfron-xxx
`

You may be good for five minutes after then and have to repeat the process.

**Comment by mrdfuse** [comment]
Yeah we have noticed that, I was hoping that the Azure guys come up with a decent explanation or solution but so far the problem doesn't seem to get acknowledged at all. For me AKS is not GA ready at all.

**Comment by jskulavik** [comment]
We are very actively working to address this issue and apologize for the problems you are encountering.  We have several remediation fixes rolling out in the coming days that directly target this issue.  

Thank you for your understanding and for the feedback, it is tremendously valued.

**Comment by mrdfuse** [comment]
Hi @jskulavik, thanks for the reply, it's good to hear you are working on it. Would be nice if Azure Support would also tell us this instead of just advising to recreate tunnelpod (or sometimes not even that and give up when we report problems). Let's hope the upcoming fixes resolve the issue and thank you for the hard work.

**Comment by strtdusty** [comment]
This issue is crippling our clusters.  We are lacking any visibility into the issue, the timing of any remediation or method of application.  Our cluster is effectively a mess with communication issues everywhere.  The very brief acknowledgement that this issue is known by support doesn't give me enough information.  Should I not be looking at any issues that seem to stem from communication problems until this is fixed?

**Comment by mrdfuse** [comment]
@jskulavik any updates on this issue?

**Comment by jskulavik** [comment]
Hi @mrdfuse,

We are actively working to address this issue.  If you are experiencing continued problems after applying the workaround mentioned [in #663](https://github.com/Azure/AKS/issues/663) please file an Azure support request for further assistance.

**Comment by tomasaschan** [comment]
@jskulavik The issue you linked to for the workaround links back here without any further info. Did you mean to link somewhere else?

**Comment by jskulavik** [comment]
Thank you for the check @tomasaschan.  I did indeed mean to link these related issues together as they had significant overlap and common issues.  Over the last several months we've aimed to address these issues via direct support requests for AKS.

**Comment by tomasaschan** [comment]
@jskulavik That still doesn't explain this phrasing:

> the workaround mentioned in #663 

There's no mention of a workaround in #663 (that I can find). What are you referring to?

**Comment by jskulavik** [comment]
All apologies, the workaround, which has been deployed worldwide for several months now, is in [#676](https://github.com/Azure/AKS/issues/676#issue-366430459).

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.

**Comment by mrdfuse** [comment]
Still seeing this issue from time to time on several clusters. It's not possible to recreate, it happens randomly. Not on the latest latest version now, 1.11.7.

**Comment by earwax** [comment]
We still experience this problem on 1.11.9.

**Comment by dstockton** [comment]
Me too! 👎

**Comment by andreygolev** [comment]
Same there

**Comment by bHacklv** [comment]
issue is not fixed.

**Comment by rivetmichael** [comment]
same with 1.13.5

**Comment by levilugato** [comment]
same problem hear 1.13.5, randomly we receive 504 gateway timeout , we have an aplication gateway in front of our internal load balancer and using Isitio Ingress

**Comment by athulase** [comment]
Same issue here. Receiving time out error, if the application is running for long time. If application runs for short amount time, it return perfectly and gracefully.

**Comment by alexsandro-xpt** [comment]
I'm using Nginx Ingress, no problem here.

**Comment by levilugato** [comment]
@athulase @rivetmichael 
What Ingress are using ?

**Comment by diepes** [comment]
Looking at tunnelfront container in kube-system namespace is see it has request: cpu: 10m,
but looking at kubectl top node it uses 88m cpu.

Maybe it is just deployed with the wrong cpu requirements, should probably be cpu: 100m

**Comment by smira** [comment]
> Maybe it is just deployed with the wrong cpu requirements, should probably be cpu: 100m

this seems to help with random timeouts on many AKS clusters in different regions. I wonder if it's just a bug?

**Comment by jskii** [comment]
> Looking at tunnelfront container in kube-system namespace is see it has request: cpu: 10m,
> but looking at kubectl top node it uses 88m cpu.
> 
> Maybe it is just deployed with the wrong cpu requirements, should probably be cpu: 100m
> 
> kubectl patch deployment tunnelfront -p ‘{“spec”:{“template”:{“spec”:{“containers”:[{“name”: “tunnel-front”,”resources”:{“requests”:{“cpu”:”100m”}}}]}} }}’

This should not matter or be needed, since it doesn't appear tunnelfront has a limit set on usage, only a request, meaning it can use more CPU if it needs it.

https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/#what-if-you-specify-a-container-s-request-but-not-its-limit

**Comment by smira** [comment]
ah, so probably it only helps as it leads to tunnelfront restart

**Comment by epa095** [comment]
> > Looking at tunnelfront container in kube-system namespace is see it has request: cpu: 10m,
> > but looking at kubectl top node it uses 88m cpu.
> > Maybe it is just deployed with the wrong cpu requirements, should probably be cpu: 100m
> > kubectl patch deployment tunnelfront -p ‘{“spec”:{“template”:{“spec”:{“containers”:[{“name”: “tunnel-front”,”resources”:{“requests”:{“cpu”:”100m”}}}]}} }}’
> 
> This should not matter or be needed, since it doesn't appear tunnelfront has a limit set on usage, only a request, meaning it can use more CPU if it needs it.
> 
> https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/#what-if-you-specify-a-container-s-request-but-not-its-limit

It can use more CPU if needed **and if there is cpu available**. In a high-load situation it is not guaranteed more than requested, so it should definitely request at least what it needs to have to operate properly in a high-load situation.

**Comment by jnoller** [comment]
If you are seeing tunnel front failures and other errors in your worker node logs, this will be due to IO pressure and contention on your OS disk. Each disk size for the OS has a set cap of IOPS which is a hard quota. If a VM has an IOPS max higher than the disk the disk limit takes precedence.

Look in the portal at host level metrics. More than likely the OS disks are saturated leading to docker PLEG error, socket read errors and more.

It will look like a network failure given everything on Linux is a file including the sockets the daemons are writing to.

**Comment by guo897654050** [comment]
similarity，so how to solve this problem
