### ISSUE TITLE
GA support of Standard Load Balancer support for user deployed services (was: Be able to configure Load Balancer SKU)

### ISSUE THREAD

**Issue by tgarlot** [Azure/AKS#643]
It is now possible to select the SKU of the load balancer to be used (https://github.com/kubernetes/kubernetes/pull/61884). This is a "cluster-level" configuration.

How can we set it (either via portal or azure CLI) so that the LB gets the Standard and not Basic SKU ? Looks like it's not available...yet.

thanks

**Comment by mtparet** [comment]
We hit the same issue. We need to give our outbound IP for whitelisting but we have multiple frontend IPs (and we are going to create more) and without a loadbalancer standard we cannot manage the outbound IP...

**Comment by rncwnd79** [comment]
I too made an upgrade to kubernetes 1.11.2 on our dev aks to change the internal load balancer sku to standard. But there is no option in the portal. Also the arm template reference and the aks docs lack any info on this topic...

We have currently the problem that lb basic sku only allows 10 frontend ip configurations resulting in max. 9 lb rules max.

**Comment by tomasr** [comment]
@rncwnd79 Note that the 10 frontend ip configuration limit for basic load balancer is a quota you can open a support ticket to get raised. It's the `Frontend IP Configurations per Load Balancer` quota. 

So you might be able to do this in the mean time, while standard LB support is added.

**Comment by rncwnd79** [comment]
@tomasr thanks for the hint! Didn't think about that.

**Comment by UncleTawnos** [comment]
@mtparet from my experience I strongly advise reducing number of public ip configurations and just go for ingress controllers (if your scenario allows you to do so). Large public LB can get seriously screwed while experiencing master split brains (like probes do not match rules) and recovering from it takes time (as multiple of LB reconfigurations has to happen). Avoid if you can.

**Comment by rewt** [comment]
Is there a plan to implement standard SKU as option for internal-loadbalancer YAML declaration as specified here?  https://docs.microsoft.com/en-us/azure/aks/internal-lb

**Comment by piotr-napadlek** [comment]
Hey is there any plan for an improvement here? We have a dev-environment cluster where multiple developers deploy their ingresses so we reach more than 20 frontend ip configurations with ~40 rules and the load balancer is awfully slow - just deploying a service lasts more than 5 mins and destroying it even more. Not sure if having standard load balancer would solve the issue, but the fact that I need to wait 15mins just to get 2 load balancing rules ready is really annoying.

**Comment by amuraru** [comment]
I see https://github.com/kubernetes/kubernetes/pull/61884 being merged in upstream.
Do you have any ETA when this will be made available in AKS?

**Comment by kevinjqiu** [comment]
Can we get some answers from the AKS people?  The pull request was merged almost a year ago, and this issue has been open for half a year!

**Comment by jnoller** [comment]
@kevinjqiu SLB support will land in first half 2019

**Comment by datadot** [comment]
@jnoller is a preview available for this?

**Comment by jnoller** [comment]
@datadot Not yet, but soon - it will be posted in the previews.md file and AKS release page.

**Comment by vaustral** [comment]
While this is going on and making our lives all easier, any recommendation that you may have to control the egress endpoint without having to rebuild the cluster, this is for vendor white listing of services.

**Comment by will-beta** [comment]
It will also land soon in Azure China?

**Comment by jnoller** [comment]
@will-beta When it exits preview and enters GA but we do not commit to exact dates.

**Comment by jnoller** [comment]
Updating to reflect status on roadmap. This issue tracks SLB support for customer workloads and the Master API servers (SLB in front)

**Comment by pixelicous** [comment]
> @kevinjqiu SLB support will land in first half 2019

Hi, we passed the half year mark for this, i am used to MS and dates not being friends, but still, this is such a basic functionality, cant work with global vnet peering and SLB

**Comment by jnoller** [comment]
We understand, and SLB support is coming in several weeks.

**Comment by vaustral** [comment]
I think we all get it about dates, most people here go through the same motions - but is there is an alternative to manage egress IP's until this is sorted?  I have a project i'm delaying because of an unsuitable way to manage this on AKS... and i'm not sure i can wait another 2 months.

**Comment by jnoller** [comment]
@vaustral There is not an alternative

**Comment by vaustral** [comment]
@jnoller  bummer...worth an ask, i didn't think so, but miracles happen :)

**Comment by pixelicous** [comment]
@vaustral you have a solution, i am in the same boat, but i am not going to wait, from 10years of experience you are going to wait a very long time to get it, and when you do, it will miss features or support that will take another year to solve.. going to shift this load to eks

**Comment by jnoller** [comment]
I understand you are upset @pixelicous, and the AKS team is _painfully_ aware of the problems with Basic Load Balancers, and we are also aware that getting SLBs in place has slipped and that they have critical capabilities we, and customers need.

That said, this repository is not for venting. Please keep the comments on-topic, not personal, etc. We have a code of conduct in place and we will remove comments that are in violation.

**Comment by pixelicous** [comment]
@jnoller Actually came back to edit and add a thank you for the prompt response :) Sorry not upset and it wasn't a vent but expressed my opinion on the subject, on top of it i also provided a viable solution for somebody, even if it is just a workaround. With today's current stack of technologies it is very easy to copy your IAAC between cloud providers to be able to support your customers, until your main provider supports your need.

**Comment by will-beta** [comment]
@pixelicous @vaustral In our senario, as a workaround, we setup a VM with socat in the VNet to relay traffic to the Basic Load Balancer. Hope this helps!

**Comment by will-beta** [comment]
@pixelicous @vaustral Azure Application Gateway also helps!

**Comment by pixelicous** [comment]
@will-beta Thanks for your comments

**Comment by jluk** [comment]
SLB support has landed in public preview. Documentation is below, please review limitations to see if your scenarios are covered currently. We'll be making more improvements through preview.

aka.ms/aks/slb

**Comment by alanjcastonguay** [comment]
Is this preview covering Standard Load Balancer for Service objects or API-Server or both? https://aka.ms/aks/slb implies only the former while #1052 was about the latter.

**Comment by jluk** [comment]
This issue is about service objects, defer to @jnoller if the control plane use of SLB should be captured in a separate issue.

**Comment by wouterhund** [comment]
Could #1052 be re-opened if this still hasn't been resolved? We're still running into connection timeouts daily.

**Comment by jluk** [comment]
@wouterhund just re-opened to track it in that separate issue, working on getting the timelines for when that issue will be resolved.

**Comment by jluk** [comment]
Closing as SLB is now GA as noted in release.

https://github.com/Azure/AKS/releases/tag/2019-09-09
