### ISSUE TITLE
Is there a way to create Encrypted Communication between POD's inside the Kub Cluster

### ISSUE THREAD

**Issue by jkriba** [Azure/AKS#645]
**What happened**:
Communication internal to the PODs and Microservices are happening with Port 80.

**What you expected to happen**:
The communication between Micro-services inside the Kub cluster should be encrypted.

**How to reproduce it (as minimally and precisely as possible)**:
Create a Kub cluster with more than 1 PODS and associated microservices. They by default with interact using port 80

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.11.2
- Size of cluster (how many worker nodes are in the cluster?):2
- General description of workloads in the cluster HTTPS microservices
- Others:

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.

**Comment by inverted360** [comment]
@jnoller a follow up on this - is pod to pod encryption with TLS 1.2+ supported in AKS? I cannot find a Microsoft docs on this or how to require encryption-in-transit inside a cluster.
