### ISSUE TITLE
Inconsistent azure cli

### ISSUE THREAD

**Issue by raihanchdy** [Azure/AKS#647]
Hi,

Sometimes azure cli throws out the error as "The request is being throttled." with no exit status. This is very tough to do automation with such behavior.

Can understand that due to some reasons its being throttled but there be should be some exit status to handle in scripts while doing automation.

**Comment by raihanchdy** [comment]
Hello Team,

Why don't you come with answer.Very poor response from azure team.

**Comment by DenisBiondic** [comment]
Why don’t you ask the right guys: https://github.com/Azure/azure-cli
