### ISSUE TITLE
Upgrading AKS version removes all volume claims and leaves Azure disks with undecipherable names

### ISSUE THREAD

**Issue by Shahar-Levy** [Azure/AKS#648]
**What happened**: To fix an issue with unavailable nodes, an AKS engineer instructed us to upgrade our cluster (1.9.9 --> 1.10.6). When we upgraded our cluster, the volume claims that were being made were disconnected. The data disks in Azure were still available to be connected, but since Azure's naming scheme for data disks is different from the Kubernetes/helm namings, it became impossible to reconnect the right disk to each node.

**What you expected to happen**: I expected to not lose my connection between my disks and nodes.

**How to reproduce it (as minimally and precisely as possible)**: Host an app and a database in an AKS cluster. (we installed the wordpress helm chart that has a MariaDB). Upgrade a cluster that hosts an app and a database. The disks will detach from the nodes hosting the DB.

**Anything else we need to know?**: I realize that this issue can be avoided by setting up for persistence. We helm installed a database and had not yet set up for persistence and I believe this is still a bug, as upgrading versions of kubernetes should not remove my data disks from my nodes.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.9 --> 1.10.6
- Size of cluster (how many worker nodes are in the cluster?): 5
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Ionic, Wordpress, MariaDB
- Others: Microsoft ticket 118091218993960

**Comment by alexsandro-xpt** [comment]
Some news?

**Comment by Shahar-Levy** [comment]
The Microsoft engineer I had contacted was unable to reproduce this bug. This is how the bug was caused in my cluster.

**Comment by alexsandro-xpt** [comment]
Sad, I was upgrade my cluster to 1.11.3 and my Rabbit MQ installed via Helm and POD get a CrashLoopbackOff after upgrade, so I take his log saying something like can't no find path who that have an erlangCookie.

I don't know if was error mount point or whatever....

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
