### ISSUE TITLE
Authn/Authz does not work with Azure AD-enabled AKS in North Europe 

### ISSUE THREAD

**Issue by logicfox** [Azure/AKS#649]
**What happened**:
Authn/Authz does not work in Azure AD enabled AKS clusters created in North Europe region, but works as expected with the same app registration in clusters created in West Europe.

**What you expected to happen**:
Users should be able to use `kubectl login` with AAD-enabled clusters in all regions.

**How to reproduce it (as minimally and precisely as possible)**:
Create an AKS cluster with AAD authentication enabled, each in North Europe and West Europe with the same app registration. Pre-req: Ensure that the app registration has the correct permissions.

**Anything else we need to know?**:
Azure support suggested that we use AKS 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.1 and 1.11.2
- Size of cluster (how many worker nodes are in the cluster?): default (3 nodes, Standard_DS2_v2)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Mixed workloads
- Others:

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
