### ISSUE TITLE
az aks browse should allow user to specify listening port.

### ISSUE THREAD

**Issue by asridharan** [Azure/AKS#650]
**What happened**:
Tried launching the Kubernetes dashboard through `az aks browse` which resulted in the command failing because port 8001 was occupied by another process on my system.

In the end I ended up using `kubectl proxy --port ` to setup a tunnel to the kubernetes cluster and accessing the dashboard through the Kubernetes URI.

**What you expected to happen**:
Kubernetes dashboard should have been launched successfully

**How to reproduce it (as minimally and precisely as possible)**:
* Use windows 10.
* Run a TCP server on port 8001
* Run `az aks browse` command and it will fail.

**Anything else we need to know?**:
This problem is specifically in Windows 10. Haven't tried it on other OS.

**Environment**:
- Kubernetes version (use `kubectl version`):
```bash
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```
- Size of cluster (how many worker nodes are in the cluster?)
4
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by tomasr** [comment]
This is already supported with the `--listen-port` parameter:

```bash
az aks browse -g $rg -n $cluster --listen-port 9032
```

Does this not work for you?

**Comment by asridharan** [comment]
This is the help that I see:
```
az aks browse --help

Command
    az aks browse: Show the dashboard for a Kubernetes cluster in a web browser.

Arguments
    --name -n           [Required]: Name of the managed cluster.
    --resource-group -g [Required]: Name of resource group. You can configure the default group
                                    using `az configure --defaults group=<name>`.
    --disable-browser             : Don't launch a web browser after establishing port-forwarding.
        Add this argument when launching a web browser manually, or for automated testing.

Global Arguments
    --debug                       : Increase logging verbosity to show all debug logs.
    --help -h                     : Show this help message and exit.
    --output -o                   : Output format.  Allowed values: json, jsonc, table, tsv.
                                    Default: json.
    --query                       : JMESPath query string. See http://jmespath.org/ for more
                                    information and examples.
    --verbose                     : Increase logging verbosity. Use --debug for full debug logs.
```

This is my Azure CLI version:
```{bash}
 az --version
azure-cli (2.0.37)
```
I don't see the --listen-port option mentioned in the health.

**Comment by tomasr** [comment]
Upgrade the Azure CLI. That version is oooold :smile:. 2.0.45 is the current one, and certainly has that option.
