### ISSUE TITLE
Pod allocation update existing clusters

### ISSUE THREAD

**Issue by IvanKirianov** [Azure/AKS#651]
**What happened**: Can't change\update current allocation pod count on existing AKS cluster.

**What you expected to happen**: Have ability to extend\update default value (30 pods per node) on existing cluster with advanced network

**How to reproduce it (as minimally and precisely as possible)**: Currently this is default settings according to following documentation: https://docs.microsoft.com/en-us/azure/aks/networking-overview#maximum-pods-per-node  

**Environment**:
- AKS 1.11.2
- This statement right for any AKS cluster and any version

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
