### ISSUE TITLE
Australia Southeast region availability

### ISSUE THREAD

**Issue by machship-mm** [Azure/AKS#653]
**What happened**:
AKS not yet available in Australia Southeast region

**What you expected to happen**:
AKS *available* in Australia Southeast region

**How to reproduce it (as minimally and precisely as possible)**:
Go to the portal, cannot create AKS cluster in Aus SE region as Azure has not yet provided it

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

We need a timeline on the availability of AKS in the Australia Southeast region. I also feel that it would be great for the community to have an explanation as to what kinds of challenges exist in Azure that stop services such as AKS from being available universally - particularly, what was the reason to omit Australia Southeast from the planned rollout when Australia East was added?

**Comment by seanmck** [comment]
Australia Southeast is the next region we plan to enable. It should go live sometime in early January.

**Comment by dmcconnell86** [comment]
Hi @seanmck, any update on the release date for AKS Australia Southeast?

**Comment by voltaire-ilustrisimo-webjet** [comment]
Hi @seanmck, has there been any update on this? We have several clients waiting to use AKS in Australia Southeast.

**Comment by dmcconnell-m** [comment]
Hi All,

AKS Aus South East was released on Tuesday and is now available

**Comment by mathieu-benoit** [comment]
https://azure.microsoft.com/en-us/updates/general-availability-azure-kubernetes-service-in-australia-southeast/
