### ISSUE TITLE
Unable to create AKS Cluster via AZ CLI with --vnet-subnet-id parameter

### ISSUE THREAD

**Issue by easkerov** [Azure/AKS#654]
**What happened**: I am trying to create AKS cluster with `az aks create` command and `--vnet-subnet-id` parameter:

```
az aks create   --resource-group aks-rbac-rg \
                --name aks-demo-cluster \
                --ssh-key-value "<SSH Public Key>" \
                --aad-server-app-id <aad-server-app-id> \
                --aad-server-app-secret <aad-server-app-secret> \
                --aad-client-app-id <aad-client-app-id> \
                --aad-tenant-id <aad-tenant-id> \
                --vnet-subnet-id "/subscriptions/5c529f34-44c6-4042-9bd6-854992ed861f/resourceGroups/aks-rbac-rg/providers/Microsoft.Network/virtualNetworks/aks-vnet/subnets/aks-subnet" \
                --node-count 1 \
                --node-vm-size Standard_B2s\
                --kubernetes-version 1.11.2 \
                --location eastus \
                --no-wait
```
Execution  of this command gives me an error: 

`**Waiting for AAD role to propagate[################################    ]  90.0000% Could not create a role assignment for subnet. Are you an Owner on this subscription?**`

If I remove `--vnet-subnet-id` parameter AKS cluster will be created successfully, but I need to define my own predefined subnet within VNet 

**What you expected to happen**: Successful execution `az aks create` command with `--vnet-subnet-id` parameter and AKS cluster creation.

**How to reproduce it (as minimally and precisely as possible)**:

Execute `az aks create` command with set of parameters above.

**Anything else we need to know?**: User account I am using for cluster creation has Owner permissions to subscription and Global administrator AD role. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.2
- Size of cluster (how many worker nodes are in the cluster?): 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Java app
- Others:

**Comment by lehtope1** [comment]
Also facing this issue. However, when deploying the cluster from the portal & with a predefined subnet ID, the deployment goes through successfully.

**Comment by easkerov** [comment]
@lehtope1 Indeed, deployment from Portal works fine for me. Executing az cli throws an error above.

**Comment by simon-michaud** [comment]
Same here, I really need a custom VNet and automation via scripts

**Comment by sdktr** [comment]
Same problem here!

**Comment by bapetc** [comment]
Same here!

**Comment by novaterata** [comment]
You are missing '--network-plugin azure'

**Comment by easkerov** [comment]
@novaterata Thanks, indeed, according to doc: "Use the az aks create command with the --network-plugin azure argument to create a cluster with advanced networking. Update the --vnet-subnet-id value with the subnet ID"
https://docs.microsoft.com/ru-ru/azure/aks/networking-overview

But this is not clear from cli documentation: https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create

I have not tried yet, apparently but this should work.

**Comment by asc-adean** [comment]
The error is occurring even with `--network-plugin azure` but the cluster appears to successfully create anyway.  Perhaps a benign error message?

**Comment by anschoewe** [comment]
I have the same problem.  It doesn't work my the 'kubenet' network plugin and Azure AD integration.

az aks create \
    --resource-group "$resourceGroup" \
    --name "$k8Name" \
    --node-count 1 \
    --node-vm-size Standard_DS2_v2 \
    --enable-addons monitoring \
    --kubernetes-version 1.12.6 \
    --generate-ssh-keys \
    --aad-server-app-id "$serverAppId" \
	--aad-server-app-secret "$serverAppSecret" \
	--aad-client-app-id "$clientAppId" \
	--aad-tenant-id "$tenantId" \
    --network-plugin kubenet \
    --service-cidr 10.0.0.0/16 \
    --dns-service-ip 10.0.0.10 \
    --pod-cidr 192.168.0.0/16 \
    --docker-bridge-address 172.17.0.1/16 \
    --vnet-subnet-id "$subnetId"

**Comment by anschoewe** [comment]
I solved my own problem.  Earlier I was creating AKS clusters using the '--service-principal' argument (and not AAD arguments).  But, when I switched to to use ADD, I remove the '--service-principal' argument, thinking it wasn't used anymore.

From this other [issue](https://github.com/Azure/AKS/issues/117), I learned that if you leave '--service-principal' the Azure CLI tool will use a previous service principal if it finds one in the ~/.azure/aksServicePrincipal.json local file.  I had this file and it referenced a deleted service account.  Upon deleting the file, I was able to create my AKS cluster with the above arguments (and using a VNET I created). When you don't specify a '--service-principal' and you also don't have a ~/.azure/aksServicePrincipal.json file, Azure will auto-generate a service principal -which is totally separate from the Azure Active Directory service principal you'd use for RBAC in AKS.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
