### ISSUE TITLE
Create AKS cluster using Azure portal - validation failed

### ISSUE THREAD

**Issue by kvolkovich-sc** [Azure/AKS#655]
I go through AKS creation wizard, at the last step (Review + create) I have error message "Validation failed".

![screen shot 2018-09-21 at 12 56 08 pm](https://user-images.githubusercontent.com/24652543/45874518-c8baca80-bd9d-11e8-969f-2f5a1f230f9f.png)

All parameters, except resource group, are defaults.

I press "Previous" button, then return back to the last step and validation finished succeed.

I tried several times. All are with same result.

**Comment by qike-ms** [comment]
Need your subscription id and cluster name. Please send such information to aks-help@serivce.microsoft.com

**Comment by kvolkovich-sc** [comment]
Tried now - `Validation passed`.
