### ISSUE TITLE
Error when creating cluster with CLI: "The request did not have a provided subscription. All requests must have an associated subscription Id."

### ISSUE THREAD

**Issue by rolanddb** [Azure/AKS#656]
**What happened**:
Tried to create new AKS cluster with Azure CLI.
`az aks create --subscription <my subscription id> <--other args>`

This leads to an error: `The request did not have a provided subscription. All requests must have an associated subscription Id.`

This happens both on my laptop and in the Cloud Shell.

I have created an AKS cluster using the AZ CLI before and it worked fine.

**What you expected to happen**:
Cluster will be created

**How to reproduce it (as minimally and precisely as possible)**:
Use CLI as above to create a cluster.

**Anything else we need to know?**:

**Environment**:
- az cli version 2.0.45
- Region: west europe

**Comment by ConnorDickson** [comment]
I had this problem and the issue was that the --vnet-subnet-id was incorrect. It needs to start with "/subscriptions/" so it could be an issue with the <--other args> you mention
