### ISSUE TITLE
Feature Request: Backing up Persistent Volumes/Azure Disks Natively

### ISSUE THREAD

**Issue by damienwebdev** [Azure/AKS#658]
**What happened**:
Generally speaking, if I need a persistent volume via an AzureDisk, I have to run a DIY backup strategy which involves manually creating snapshots of the relevant disk and storing them in Azure. This is error-prone and highly end-implementation dependent.

**What you expected to happen**:
An out-of-the-box strategy for backing up AKS disks used as persistent volumes in AKS. This may be beyond the scope of AKS as this may be a general feature that would be super-valuable to individuals running their own VMs with attached disks.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an Azure Disk. 
2. Attach the Azure Disk as a PersistentVolume in the cluster
2. Think about disaster recovery. 
3. See no pre-built way to backup the disk (outside of a DIY snapshot).

**Comment by spacecat** [comment]
+1

Yes, it would be very nice and less error prone to have like a managed backup and restore service or feature for this.

**Comment by garethmorris78** [comment]
+1
Keeping persistent storage backup within the K8s fabric, rather than having to use another method  "outside" the cluster would be ideal.  There are other service providers that either integrate with opensource persistent storage backup solutions or looking at their own K8s snapshot controllers. 

The ability to use something like the  Azure Backup Service would be a good start however.

**Comment by rosskukulinski** [comment]
I recommend taking a look at [Heptio Ark](https://github.com/heptio/ark) which includes native Azure support for snapshotting PV/PVCs.

Full-disclosure: I'm the Product Manager for Heptio Ark :)

**Comment by andyzhangx** [comment]
I am working on azure disk CSI driver which would support azure disk [snapshot functionality](https://kubernetes.io/docs/concepts/storage/volume-snapshots/), the target k8s version could be next k8s release: `v1.14`. So as @rosskukulinski suggested, [Heptio Ark](https://github.com/heptio/ark) is now the only product that supports snapshotting azure disk PV/PVCs.
BTW, I found https://github.com/heptio/ark/tree/release-0.9/pkg/cloudprovider/azure only contains azure disk snapshot code, it does not have azure file, I have interest to contribute to azure file snapshot functionality, the snapshot code should be quite similar between CSI and Heptio Ark.

**Comment by rosskukulinski** [comment]
@andyzhangx interesting! I didn't know about Azure Files.  I think we'd be open to taking a PR for that capability!  Please feel free to open an issue against Ark and I'll bring the Ark team up to speed.

**Comment by rosskukulinski** [comment]
I should note that non-native Snapshotting of Azure Files could be supported through Ark's [Restic integration](https://blog.heptio.com/ark-v0-9-alpha-now-with-restic-14ad6b402ab3).

**Comment by andyzhangx** [comment]
@rosskukulinski Thanks, I still filed an issue there: https://github.com/heptio/ark/issues/1046, do you know where is the code of backup/retore azure file in Ark's Restic integration?

**Comment by rosskukulinski** [comment]
@andyzhangx I don't believe there's any azure-specific code for the Restic integration - it's just file-level backup/restore for the PV/PVC.  https://github.com/heptio/ark/blob/master/docs/restic.md has more information.

**Comment by andyzhangx** [comment]
Update this thread:
We have implemented azure disk CSI driver, it's now in alpha stage, we will implement snapshot feature for beta stage which is around June, here is the issue for tracking: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/25
BTW, only CSI driver would support snapshot/restore volume feature, original built-in azure disk feature won't support that since it's determined by k8s community.

**Comment by jeremych1000** [comment]
@andyzhangx Great! To confirm, is this Azure Snapshot --> Azure Managed Disk --> Kubernetes Persistent Volume (that I can then reference in helm charts, etc.)?

I tried following that link but could only do Azure Snapshot --> Azure Managed Disk --> Mount as volume in K8 YAML (i.e. direct mount, and nothing shows in `kubectl get pv` as its not a persistent volume). 

Or am I confused?

**Comment by jeremych1000** [comment]
@andyzhangx How would you then go and use the attached disk in kubernetes resources? It doesn't show up in PV nor PVCs.

Is the only way to manually add a volume mount of type AzureDisk, like this? https://github.com/kubernetes/examples/blob/master/staging/volumes/azure_disk/static-provisioning/managed-disk/pod-uses-existing-managed-disk.yaml#L18-L23

**Comment by andyzhangx** [comment]
> Is the only way to manually add a volume mount of type AzureDisk, like this? https://github.com/kubernetes/examples/blob/master/staging/volumes/azure_disk/static-provisioning/managed-disk/pod-uses-existing-managed-disk.yaml#L18-L23

@jeremych1000 correct, before that, you need to create a new disk from that snapshot

**Comment by thomassampson** [comment]
This would sure be a valuable feature!! 👍👍👍

**Comment by jeremych1000** [comment]
Velero now supports Azure Managed Disks - so that might be a better solution now.

**Comment by andyzhangx** [comment]
Azure disk CSI driver already supports snapshot functionality: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/snapshot

**Comment by damienwebdev** [comment]
@andyzhangx have any docs about how one could simply apply this with incremental backups for a volume in a container? I think that's the particular use-case that I'm shooting for with this issue. 

While I can create my own backup system with the CSI driver, I'd like to have a well-supported and MSFT documented solution that can be applied broadly as opposed to one-off solutions defined by the various community-created articles.

**Comment by miwithro** [comment]
@andyzhangx

**Comment by wangyira** [comment]
Hi @andyzhangx, are you able to link the doc for this? Thanks!

> @andyzhangx have any docs about how one could simply apply this to achieve regular incremental backups for a volume in a container? I think that's the particular use-case that I'm shooting for with this issue.
> 
> While I can create my own backup system with the CSI driver, I'd like to have a well-supported and MSFT documented solution that can be applied broadly as opposed to one-off solutions defined by the various community-created articles.

**Comment by miwithro** [comment]
Hey @wangyira here is the document for backups.

https://docs.microsoft.com/en-us/azure/aks/azure-disks-dynamic-pv#back-up-a-persistent-volume
