### ISSUE TITLE
Missing double-quote escaping at /etc/kubernetes/azure.json

### ISSUE THREAD

**Issue by kvolkovich-sc** [Azure/AKS#659]
Hello, Azure guys!

I use Terraform to automate AKS cluster creation.

I use [azuread_service_principal_password](https://www.terraform.io/docs/providers/azurerm/r/azuread_service_principal_password.html) to create a service principal password.

```
resource "random_string" "service_principal_password" {
  length           = 16
  special          = true
  override_special = "/@\" "
}
```

Everything worked normally, but after September 18 2018 cluster creation started to fail.

I spent some time and found that `"` is not escaped in generate `/etc/kubernetes/azure.json` at worker nodes:

```
{
    ...
    "aadClientSecret": "PwEV@QG7/PYt"re9",
    ...
}
```

It must be `\"`, not `"`.

According to [this](https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-sspr-policy#password-policies-that-only-apply-to-cloud-user-accounts), the `"` is a valid character of service principal password.

Also I noticed that `"` character is `“` [here](https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-sspr-policy).

I found it strange because there is no such character at common `QWERTY` keyboard layout.

---

![azad-1](https://user-images.githubusercontent.com/24652543/45982950-672b8200-c063-11e8-889b-36f189edcfda.png)

---

[Here](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements) you can see right `"`.

---

![azad-2](https://user-images.githubusercontent.com/24652543/45982960-70b4ea00-c063-11e8-912d-3acfcf4ca88b.png)

---

Looks like documentation content processed by some automated typographer. It's not good for technical documentation.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
