### ISSUE TITLE
tiller  pod shows status of ImagePullBackOff in AKS

### ISSUE THREAD

**Issue by ramakrishnateja** [Azure/AKS#66]
I have created an AKS cluster and been able to do deployments. I planned to use Helm and installed helm locally and initially tried to do a client only initialization as per the documentation but figured out that helm is not pre-installed in the cluster. 

To verify I ran kubectl -n kube-system get po
NAME                                    READY     STATUS    RESTARTS   AGE
heapster-75667786bb-mvq8x               2/2       Running   0          25s
kube-dns-v20-6c8f7f988b-49d89           3/3       Running   0          1m
kube-dns-v20-6c8f7f988b-v9b4r           2/3       Running   0          1m
kube-proxy-9ck7v                        1/1       Running   0          1m
kube-proxy-jkpfw                        1/1       Running   0          1m
kube-proxy-rmczw                        1/1       Running   0          1m
kube-svc-redirect-hwz6t                 1/1       Running   0          1m
kube-svc-redirect-vhcr5                 1/1       Running   0          1m
kube-svc-redirect-vrqtw                 1/1       Running   0          1m
kubernetes-dashboard-6fc8cf9586-zd2sj   1/1       Running   0          1m
tunnelfront-7bc747fc55-mshg2            1/1       Running   0          1m

So i ran helm init not when i ran the same above command the status of the tiller pod shows as ImagePullBackoff.  

![image](https://user-images.githubusercontent.com/6781607/33737899-a7ff28f6-db65-11e7-80ff-ab4ca18c28e6.png)

NAME                                    READY     STATUS             RESTARTS   AGE
heapster-75667786bb-mvq8x               2/2       Running            0          25m
kube-dns-v20-6c8f7f988b-49d89           3/3       Running            0          26m
kube-dns-v20-6c8f7f988b-v9b4r           3/3       Running            0          26m
kube-proxy-9ck7v                        1/1       Running            0          26m
kube-proxy-jkpfw                        1/1       Running            0          26m
kube-proxy-rmczw                        1/1       Running            0          26m
kube-svc-redirect-hwz6t                 1/1       Running            0          26m
kube-svc-redirect-vhcr5                 1/1       Running            0          26m
kube-svc-redirect-vrqtw                 1/1       Running            0          26m
kubernetes-dashboard-6fc8cf9586-zd2sj   1/1       Running            0          26m
tiller-deploy-5b9675c8d-hcf6r           0/1       ImagePullBackOff   0          0s
tunnelfront-7bc747fc55-mshg2            1/1       Running            0          26m

**Comment by ramakrishnateja** [comment]
I ran 
kubectl describe pod tiller-deploy-5b9675c8d-hcf6r -n kube-system 
and i see that the authentication failed while trying to pull the image. Here are the events details

![image](https://user-images.githubusercontent.com/6781607/33738626-cb8fe646-db67-11e7-959c-a096d4eeea5c.png)

**Comment by sgoings** [comment]
It's strange to me that `helm init` at one point was trying to grab `gcr.io/kubernetes-helm/tiller:v2.6`. I don't see that exact path in existence at: https://console.cloud.google.com/gcr/images/kubernetes-helm/GLOBAL/tiller?gcrImageListsize=200

If you delete all-things-helm+tiller from this cluster, grab helm fresh from https://github.com/kubernetes/helm/releases/tag/v2.6.0 and run `helm init` with no params... do you see the behavior again?

With helm 2.7.0 I see a successful stock install of tiller:

```
Successfully pulled image "gcr.io/kubernetes-helm/tiller:v2.7.0"
```

**Comment by ramakrishnateja** [comment]
Hi @sgoings  I tried with helm 2.7.2 version . previously helm 2.6.0 was installed in my machine and I was seeing the issue with the older version. Once I upgraded helm to 2.7.2 its working fine.

Thanks
