### ISSUE TITLE
No deployment/pods of tiller after installing tiller

### ISSUE THREAD

**Issue by saurabhbh21** [Azure/AKS#661]
I installed tilled with RBAC in AKS cluster with Kubernetes 1.9.9 in centralus server having VM- D4_v3. But there is no pods or deployment, I could see with respect to tiller in the cluster (I've installed in kube-system namespace). 
I've uninstalled several times and reinstalled again but things doesn't seems working. I've installed nginx-ingress from MS official documentation. I got succeeding msg. When I check with **Helm list**, it says deployed, but couldn't find deployment/pod in cluster.

 Below, I'm adding tiller version command and its output. Please suggest the fix:

**helm --tiller-namespace kube-system  version**
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
