### ISSUE TITLE
Security center critical finding for AKS VM encryption

### ISSUE THREAD

**Issue by piizei** [Azure/AKS#662]
Security center is finding a critical problem with AKS nodes. 'Apply disk encryption on your virtual machines'. 
Due dynamic nature of the nodes, manual intervention is not feasible. 
Please apply VM disk encryption of the nodes by default in creation.

If this is not seen as priority by MS, then the warning level on Security Center should be lowered.

Envs: AKS orchestrator 1.8.2, AKS orchestrator 1.9.6

**Comment by filipmnowak** [comment]
> 
> 
> I have looped azure disk encryption team, in current stage, I would suggest remove this alert in security center.

Hello @andyzhangx, why do you think that security alert should not apply also to AKS?
I would like to understand what makes AKS so special, that danger and requirements you identified for other disks/VMs run by your customers, are not obligatory for your own, managed offering?

I would prefer to see AKS team encrypting disks under the k8s Nodes too.

Thank you,
F.

**Comment by andyzhangx** [comment]
@filipmnowak I just tried disk encryption on the AKS node manually, encryption failed, and VM is down

**Comment by filipmnowak** [comment]
> 
> 
> @filipmnowak I just tried disk encryption on the AKS node manually, encryption failed, and VM is down

@andyzhangx, thank you for checking. Shouldn't that be viewed as AKS bug? It would be useful to have k8s managed service following Azure's own security scan findings (especially if they are critical)

**Comment by flamingboo** [comment]
@andyz   So this issue is still pending? we cannot do encryption of AKS nodes (Ubuntu 16.04.5).
Is there a plan to fix this? We cannot go into Production without enabling encryption.

**Comment by jnoller** [comment]
Closing, duplicate of #629
