### ISSUE TITLE
Issues with kubectl {exec,logs,port-forward} after rebooting any node on newly created clusters

### ISSUE THREAD

**Issue by gandro** [Azure/AKS#663]
**What happened**:
Some Kubernetes client functions (such as `kubectl logs`, `kubectl exec` or `kubectl port-forward`) time out after rebooting a node on a newly created Kubernetes cluster. These operations time out for any pod on any node.

The issues disappear roughly 15-20min after the node restart. The cluster starts to behaves normally afterwards (until the a node is rebooted again).

**What you expected to happen**:
- Rebooting a node should not cause kubectl exec/logs/port-forward to be unavailable for 15-20mins after both the nodes and the pods are marked as ready.
- Rebooting a node should not affect kubectl exec/logs/port-forward on pods running on a different node.

**How to reproduce it (as minimally and precisely as possible)**:

Show available nodes:
```
$ kubectl get nodes
NAME                       STATUS    ROLES     AGE       VERSION
aks-nodepool1-97916568-0   Ready     agent     38m       v1.10.7
aks-nodepool1-97916568-1   Ready     agent     38m       v1.10.7
```

Show the logs of an arbitrary pod to show that these functions work before the reboot:
```
$ # we are using kube-proxy just as an arbitrary example
$ kubectl get pods -o wide -n kube-system -l component=kube-proxy
NAME               READY     STATUS    RESTARTS   AGE       IP           NODE
kube-proxy-g549m   1/1       Running   1          38m       10.240.0.4   aks-nodepool1-97916568-0
kube-proxy-v664w   1/1       Running   1          38m       10.240.0.5   aks-nodepool1-97916568-1
$ kubectl exec -n kube-system kube-proxy-g549m echo hello
hello
$ kubectl exec -n kube-system kube-proxy-v664w echo hello
hello
```

Reboot a node.
```
$ az vm restart -g $RG -n aks-nodepool1-97916568-0
 - Running ..
```

The nodes reboot properly: Show that the node and all pods properly become ready.
```
$ kubectl describe node aks-nodepool1-97916568-0 | tail -5
  Warning  Rebooted                 1m                 kubelet, aks-nodepool1-97916568-0     Node aks-nodepool1-97916568-0 has been rebooted, boot id: 609ef82c-be45-44d2-935d-72faed54f721
  Normal   NodeNotReady             1m                 kubelet, aks-nodepool1-97916568-0     Node aks-nodepool1-97916568-0 status is now: NodeNotReady
  Normal   NodeAllocatableEnforced  1m                 kubelet, aks-nodepool1-97916568-0     Updated Node Allocatable limit across pods
  Normal   Starting                 59s                kube-proxy, aks-nodepool1-97916568-0  Starting kube-proxy.
  Normal   NodeReady                56s                kubelet, aks-nodepool1-97916568-0     Node aks-nodepool1-97916568-0 status is now: NodeReady
$ kubectl get pods -o wide -n kube-system -l component=kube-proxy 
NAME               READY     STATUS    RESTARTS   AGE       IP           NODE
kube-proxy-g549m   1/1       Running   2          43m       10.240.0.4   aks-nodepool1-97916568-0
kube-proxy-v664w   1/1       Running   1          43m       10.240.0.5   aks-nodepool1-97916568-1
```

Now operations on both pods are unavailable (timeout):
```
$ kubectl exec -n kube-system kube-proxy-g549m echo hello
Error from server: error dialing backend: dial tcp 10.240.0.4:10250: getsockopt: connection timed out
$ kubectl logs -n kube-system --tail=1 kube-proxy-g549m
Error from server: Get https://aks-nodepool1-97916568-0:10250/containerLogs/kube-system/kube-proxy-g549m/kube-proxy?tailLines=1: dial tcp 10.240.0.4:10250: getsockopt: connection timed out
$ kubectl port-forward -n kube-system kube-proxy-v664w 8080:8080
error: error upgrading connection: error dialing backend: dial tcp 10.240.0.5:10250: getsockopt: connection timed out
$ kubectl logs -n kube-system --tail=1 kube-proxy-v664w
<stuck without timeout error>
```

**Anything else we need to know?**:
This only seems to happen on newly created clusters (less than a day old), but it happens reproducibly on any new cluster.

**Environment**:
- Kubernetes version): v1.10.7 (server) v1.11.0 (kubectl client)
- ACS engine version (according to tag on node): 18c0f2387b81c5f41a9d33da2f32e165c4c6af75
- Azure location: westeurope
- Machine size: Standard D8s v3
- Size of cluster (how many worker nodes are in the cluster?): 1-3 nodes.
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.):  No workload. Happens on newly created clusters without any custom pods.

**Comment by jskulavik** [comment]
Hi @gandro,

Thank you for the detailed information and overall feedback.  This is a known issue that we are currently working to remedy.  See #642.

**Comment by jskulavik** [comment]
Hi @koman,

If you are still experiencing issues, please file an Azure support request and we will track down the issue.  Thank you.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
