### ISSUE TITLE
Default nginx ingress configuration doesn't work

### ISSUE THREAD

**Issue by atrauzzi** [Azure/AKS#669]
I'm not sure if this is as a result of very sparse guidance or if it's because the resources are deployed (as pets) to `kube-system`.

I need a breakdown of what Azure puts in my kubernetes cluster by default and how it maps to all the questions I was asked when provisioning the resource.  It's just far too confusing right now to come to an understanding of what I need to do.

I'm trying to get spinnaker working, I have a `spinnaker` namespace, a bunch of spinnaker services, but every time I try to configure ingress, I just get 404.

**Comment by tomasr** [comment]
Are you deploying nginx-ingress yourself, or are you using the HTTP application routing add-on?

If the former, I've had good experience using it, and it works fine, but your ingress definition definitely needs to be correct. I've also noticed that sometimes changes to the ingress definition can take a couple of minutes to go into effect.

Usually, the best way to troubleshoot issues with nginx-ingress is to just grab the logs of your nginx-controller pod.

**Comment by yossaa** [comment]
And you can always check what's in your nginx.conf if you want to troubleshoot some ingress annotations:
`kubectl exec -n kube-system -it addon-http-application-routing-nginx-ingress-controller-XXX cat /etc/nginx/nginx.conf`

**Comment by atrauzzi** [comment]
K, I'll look into this.
