### ISSUE TITLE
Cluster state is inconsistent after a failed scale up

### ISSUE THREAD

**Issue by jzbruno** [Azure/AKS#671]
Hello,

I am opening an Azure support ticket to find the cause of the failure. This ticket is about how to fix the state of the cluster without re-provisioning.

- How do we get the cluster back to a good state?
- How do we get the node count back to a consistent state? The cluster has a value of 6 for agentPoolProfiles.count but the actual count is 5.
- How do we find more information about what happened without opening a support ticket?

**What happened**:

A failure occurred when scaling up our cluster with no error messages. Now the provisioningState is set to Failed. The cluster is in a good functioning state, the scale up just failed.

**What you expected to happen**:

- I would expect the node count to match the actual count until the cluster has been successfully scaled.
- I would expect an error message to be emitted either in the Azure portal or from the Azure CLI.

**How to reproduce it (as minimally and precisely as possible)**:

The most consistent way to reproduce is to create a cluster with a node type that you have a low quota for CPUs. Then try to scale up past the number of CPUs allowed by the quota.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version: client = v1.11.3, server = v1.10.6
- Size of cluster: 5 nodes
- General description of workloads: microservices

**Comment by yossaa** [comment]
I would try to scale down using az cli:
az aks scale --node-count 5 --name XXX

**Comment by jzbruno** [comment]
Thanks. That does work to reset the state and node count. Closing this.
