### ISSUE TITLE
http-application-routing and web sockets?

### ISSUE THREAD

**Issue by Sliverb** [Azure/AKS#672]
Hi folks,

We’re trying to use the http-application-routing add-on with our kubernetes cluster with websockets. Anything http/https works great, but when it comes to websockets (which requires a special flag in nginx), it’s not clear how we can do this with http-application-routing, despite reading the available documentation (https://docs.microsoft.com/en-us/azure/aks/http-application-routing). Specifically, our end-goal is to have secure web sockets for our cluster working, with the convenience of the magic that happens under http-application-routing.

In NGINX, we can define the following annotation to declare websocket services, which conducts the correct handshake upgrade from HTTP to websocket  (https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/websocket).

```
  annotations:
    nginx.org/websocket-services: "ws-svc"
```

Is there any way we can leverage websockets with the http-application-routing add-on as well?

Thank you,

**What happened**:

Websockets do not seem to work.

**What you expected to happen**:

Websockets should work.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: client = v1.9.0, server = v1.10.3
- Size of cluster: 1 node
- General description of workloads: microservices

**Comment by Sliverb** [comment]
@DenisBiondic Thanks!! We will try that

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
