### ISSUE TITLE
Pod failing: NetworkPlugin cni: No available addresses

### ISSUE THREAD

**Issue by stigok** [Azure/AKS#673]
**What happened**: Pod stuck in Creating due to errors with networking

**What you expected to happen**: Eventually coming up

**How to reproduce it (as minimally and precisely as possible)**: Unsure

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.6
- Size of cluster (how many worker nodes are in the cluster?): 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): HTTP, Python, Node.js, Kafka
- Others:

A Stateful Set replica failing to deploy after a rolling update due to "No addresses available".  

- Scaling the sts down to 0 replicas then up again did not work.
- Deleting the sts and re-creating made it work again

```
Warning  FailedCreatePodSandBox  3m (x103 over 6m)  kubelet, aks-agentpool-16627148-2  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "ehubtokafka-1_mynamespace" network: netplugin failed but error parsing its diagnostic message "{\n    \"cniVersion\": \"0.3.0\",\n    \"interfaces\": [\n        {\n            \"name\": \"eth0\"\n        }\n    ],\n    \"dns\": {}\n}{\n    \"code\": 100,\n    \"msg\": \"Failed to allocate address: Failed to delegate: Failed to allocate address: No available addresses\"\n}": invalid character '{' after top-level value
```

**Comment by stigok** [comment]
Related:
- https://github.com/Azure/azure-container-networking/issues/176

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
