### ISSUE TITLE
Azure AKS: Maximal nodes per cluster for different VM Size/NodeSize 

### ISSUE THREAD

**Issue by dhirajnitk** [Azure/AKS#675]
**What happened**:

I notice that  while creating an AKS Cluster; choosing a random VM Type for given region, shows  me  different Node count limit in Azure Portal which is mostly less than 10.

**What you expected to happen**:

[Kubernetes Service limits](https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#kubernetes-service-limits) describe  **Max nodes per cluster** to be 100. 
if AKS has predefined limits of Node count for certain VM type in region then how I can fetch that  limit from Rest Api/CLI/SDK.

**How to reproduce it (as minimally and precisely as possible)**:
Choose a  random region, alter the node Size and you will see a limit on node count.

@stigok @sauryadas

**Comment by sauryadas** [comment]
Yup.. This is not an AKS limitation but an Azure limitation. This is based upon core quota's that you have for a subscription in specific regions. You can request additional quota by placing a request here
https://docs.microsoft.com/en-us/azure/azure-supportability/resource-manager-core-quotas-request

**Comment by dhirajnitk** [comment]
Thanks, but should I not be getting default maximum limit of  100 nodes for cluster as default settings.
How I can programmatically fetch those azure defined limits  with the help of Api.
