### ISSUE TITLE
HTTP application addon in CrashLoopBackOff in existing clusters 

### ISSUE THREAD

**Issue by sauryadas** [Azure/AKS#677]
**What happened**:
HTTP application addon is in CrashLoopBackOff in existing clusters 

**What you expected to happen**:
HTTP application addon to conitnue running

**How to reproduce it (as minimally and precisely as possible)**:
Regression bug , hotfix is out .

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jeffmartinxyz** [comment]
@sauryadas has this regression been addressed?

**Comment by sauryadas** [comment]
@jeffmartinxyz are you still seeing this issue? sorry this is an old bug and i am havent had any recent feedback on this.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
