### ISSUE TITLE
LoadBalancer with sessionAffinity: None is sticky, not random

### ISSUE THREAD

**Issue by novaterata** [Azure/AKS#682]
Our team has noticed that our LoadBalancer with the default sessionAffinity of "None" is not random. All requests are going to the same pod for a specific client machine

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
