### ISSUE TITLE
Question: How to switch kube-proxy to ipvs and use round-robin load balancer?

### ISSUE THREAD

**Issue by novaterata** [Azure/AKS#683]
The default load balancer is not working for me I and would like to switch to the new ipvs round-robin load balancer. I've seen documents like: https://kubernetes.io/blog/2018/07/09/ipvs-based-in-cluster-load-balancing-deep-dive/ but I don't understand where  `--proxy-mode=ipvs` is supposed to go. All documentation seems to assume I know where that goes, so I'm assuming it's something you enter when setting up k8s from scratch. How do I configure the kube-proxy in my AKS cluster?

**Comment by novaterata** [comment]
@slack Is this supported currently?

**Comment by 4c74356b41** [comment]
@novaterata is this supported?

**Comment by markl11** [comment]
Here's an example that I found:

https://github.com/Azure/aks-engine/blob/master/examples/ipvs/kubernetes-msi.json

**Comment by cloudoutloud** [comment]
> Here's an example that I found:
> 
> https://github.com/Azure/aks-engine/blob/master/examples/ipvs/kubernetes-msi.json

How would you enable this in AKS managed master node?
