### ISSUE TITLE
ComputeManagementClient  has no  support  for  proxy

### ISSUE THREAD

**Issue by dhirajnitk** [Azure/AKS#684]
**What happened**:
ComputeManagementClient Class in C# has constructors  with httpClient  
 eg. `ComputeManagementClient(SubscriptionCloudCredentials, HttpClient) `but ComputeManagementClientImpl.java in java sdk hasn't defined any constructors to support HttpClient.

How is it possible to support proxy in  ComputeManagementClientImpl?

@sauryadas

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
