### ISSUE TITLE
No pods are started after upgrade from 1.11.2 to 1.11.3

### ISSUE THREAD

**Issue by christofferjerrebo** [Azure/AKS#685]
**What happened**:

We upgraded our cluster from 1.11.2 to 1.11.3. After the upgrade, no pods are started.
```
~ $ kubectl get po --all-namespaces
No resources found.
```
We have existing Deployments, for example `aks-ssh`.
```
~ $ kubectl get deploy
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
aks-ssh   1         0         0            0           19h
```
We have raised a support request with Azure support, but have not yet received any reply.

**What you expected to happen**:

AKS would upgrade the cluster with minimal disruption, as described in https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster

**How to reproduce it (as minimally and precisely as possible)**:

Not sure.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.3
- Size of cluster (how many worker nodes are in the cluster?): 4
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Machine Learning, Build server
- Others:

**Comment by MarkTopping** [comment]
@christofferjerrebo Did you get a resolution to this? I was going to upgrade my clusters but this issue has given me reason to pause
