### ISSUE TITLE
What is the responsible disclosure procedure for AKS?

### ISSUE THREAD

**Issue by rtyler** [Azure/AKS#69]
I'm not clear on what the appropriate process is here.

**Comment by mboersma** [comment]
@rtyler Microsoft's general guidance on reporting vulnerabilities is [here](https://technet.microsoft.com/en-us/security/ff852094.aspx). *tl:dr* please email secure@microsoft.com, and thank you!

**Comment by rtyler** [comment]
Thanks, I wasn't sure if this were handled different with public preview services, or whether going through the "normal channels" would result in a long bureaucratic slog to get the AKS team information

**Comment by slack** [comment]
@rtyler if you aren't seeing the response times you'd like, please reach out to me directly jason.hansen@microsoft.com
