### ISSUE TITLE
Nodes disappeared in kubernetes but az aks and Azure Portal shows the nodes!

### ISSUE THREAD

**Issue by anishnagaraj** [Azure/AKS#690]
All the nodes in my cluster disappeared. 
`kubernetes get nodes ` shows 

> No resources found

but when I use az aks list, it shows 1 for node count:

```
    "agentPoolProfiles": [
      {
        "count": 1,
```
On the Portal though I see 

> 2 Cores

This happened on 10th October 2018 but was spotted around  18:00 PM CET the same day.   I would create a ticket with Azure Support but also wanted to know if anyone else has experienced something similar during this time. The location is 'westeurope'

**Comment by weinong** [comment]
It probably means the kubelet didn’t report status. Need to look at kubelet log.

**Comment by jluk** [comment]
Given it has been about 5 months, closing this issue. Please open a new one if node count continues to not be reported appropriately via azure clients.
