### ISSUE TITLE
Node with 8G ram Single pod with 6.5G memory limit "insufficient memory"

### ISSUE THREAD

**Issue by novaterata** [Azure/AKS#691]
I'm running 1.11.3
Each node in my cluster has 8G of ram.
Other than the built-in pods I am only running a single pod with a memory limit of 6.5G yet I am getting "insufficient memory" as the reason the pod is Pending.
There is absolutely sufficient memory. The math doesn't come close to adding up.
Is there something I'm missing?

**Comment by andyzhangx** [comment]
could you ssh to that node to check which process consumes the most of memory?

**Comment by novaterata** [comment]
I'm meeting with support soon to go over this, I'll suggest that

**Comment by novaterata** [comment]
I didn't get around to SSHing into the node, but I did notice that when I describe the nodes they claim to only have 6Gi of memory Allocatable. Which is weird because I used to be able to allocate much higher. I'll try SSH tomorrow to see what is taking up that 2G

**Comment by dstrebel** [comment]
20% of resources is reserved for critical Kubernetes services.

**Comment by novaterata** [comment]
@dstrebel thanks, I've been talking with support, and they told me that too, but I'm seeing closer to 25% and the bigger issue for me is that I can't use the dashboard to figure out what I can use. I can barely get 5Gi on an 8Gi and 11Gi on a 16Gi. I'll close this and replace with a more specific issue I guess.

**Comment by solita-kattelus** [comment]
I'm seeing this same problem. We have nodes with clearly have enough memory but still scheduling says that insufficient memory. Is there any fix for this. Or general why this is not open issue but closed if no solution available?
