### ISSUE TITLE
all kube-proxy pods restarted at once

### ISSUE THREAD

**Issue by strtdusty** [Azure/AKS#692]
**What happened**:
I noticed that all pods on our node 0 were in an error state, but the node reported ready.  Looking at the pods in kube-system I saw that all kube-proxy pods were terminating and had a life of ~11 minutes.  My assumption is that something on the Microsoft side was being updated/upgraded.
![6a038b34](https://user-images.githubusercontent.com/1013039/47044889-3c09ef00-d146-11e8-82ac-9307e24ff8cb.PNG)

**What you expected to happen**:
1. A max of one kube-proxy should have been down.
2. The node should have been cordoned and drained before applying this update

**How to reproduce it (as minimally and precisely as possible)**:
Not sure what was causing the update so I can't be sure

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.2 (US West)
- Size of cluster (how many worker nodes are in the cluster?) 4
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)  Microservices
- Others:

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
