### ISSUE TITLE
AKS doesn't allow me to choose VM in 4 regions

### ISSUE THREAD

**Issue by dhirajnitk** [Azure/AKS#693]
**What happened**:
AKS doesn't allow me to choose VM in 4 regions: UK South , Canada East, Australia East,  West US 2

**What you expected to happen**:
I am using azure rest api for usages with https://management.azure.com/subscriptions/id/providers/Microsoft.Compute/locations/region/usages?api-version=2017-12-01 which shows me sufficient available resources in these 4 regions.
 But while creating an AKS cluster in these 4 regions via azure portal, I see no VM's available. why  cant we get the same result from rest api.

@sauryadas

**Comment by weinong** [comment]
Open a support request for those VM sizes in these regions.

**Comment by dhirajnitk** [comment]
Rest usage api shows me those VMS but I don't see them in aks portal.
I wanted rest API to match the behaviour

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
