### ISSUE TITLE
Can't use a reference for the vnetSubnetId in ARM template

### ISSUE THREAD

**Issue by thmanderson** [Azure/AKS#695]
**What happened**:
When deploying an AKS cluster using an ARM template, I had the agentPoolProfiles property set up as follows:

`"agentPoolProfiles": [ `
`  { `
`    "name": "agentpool", `
`    "count": "[parameters('agentCount')]", `
`    "vmSize": "[parameters('agentVMSize')]", `
`    "osType": "Linux", `
`    "dnsPrefix": "[variables('agentsEndpointDNSNamePrefix')]", `
`    "osDiskSizeGB": "[parameters('agentOsDiskSizeGB')]", `
`    "vnetSubnetID": "[reference(concat('Microsoft.Network/virtualNetworks/',variables('vnetName'))).subnets[0].id]" `
`  } `
` ] `

I've used this exact same template previously, without issue. The template also includes a resource for the vnet with the name specified. If I try to deploy a new cluster, I get the following error:

`Message: {
  "code": "InvalidParameter",
  "message": "The value of parameter agentPoolProfile.vnetSubnetID is invalid.",
  "target": "agentPoolProfile.vnetSubnetID"
 }`

If I try to re-deploy a cluster that was set up successfully with this exact same template last week, I get the following error:

`Message: {
  "code": "PropertyChangeNotAllowed",
  "message": "Changing property 'agentPoolProfile.vnetSubnetID' is not allowed.",
  "target": "agentPoolProfile.vnetSubnetID"
 }`

This has happened on my own subscription, deploying with PowerShell, and on my company subscription, deploying through VSTS. If I manually get the vnetSubnetId and paste that into the template instead, it runs without any issues.

**What you expected to happen**:

As has worked for me before, I expected it to deploy/re-deploy the cluster, getting the vnetSubnetId at runtime from the vnet resource.

**How to reproduce it (as minimally and precisely as possible)**:

As far as I can tell, just by using a reference function in the vnetSubnetId property in agentPoolProfiles.

**Anything else we need to know?**:

**Environment**:
N/A, doesn't seem to affect it.

**Comment by abhirupguha** [comment]
Hope you already got the solution, incase you didnt, this should be what you must be looking for ->
"vnetSubnetID":"[resourceId('Microsoft.Network/virtualNetworks/subnets', parameters('vnet_name'), parameters('subnets_name'))]"

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
