### ISSUE TITLE
Unable to connect to the server: Method Not Allowed

### ISSUE THREAD

**Issue by nazneen84** [Azure/AKS#696]
**What happened**:

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"XXXXXXXXXX", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: Method Not Allowed

My AKS version is 1.11.3. The activity log shows that my upgrade succeeded from 1.9.X to 1.10.X to 1.11.3. What am I missing/ how do I troubleshoot?

**What you expected to happen**:

Show my pods

**How to reproduce it (as minimally and precisely as possible)**:

I have a high sierra MAC OS. I can't think of specific dependencies that would affect this

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): mentioned it already
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) None
- Others:

**Comment by weinong** [comment]
Try download the kubeconfig again. And add -v 7 to see more traces.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
