### ISSUE TITLE
How to map AKS POD service external IP with DNS for resolve external IP address with FQDN 

### ISSUE THREAD

**Issue by sam0104** [Azure/AKS#697]
How to map AKS POD service external IP with DNS for resolve external IP address with FQDN 

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by seanmck** [comment]
There are several ways to do this. Fastest way on AKS is via http app routing:
https://docs.microsoft.com/en-us/azure/aks/http-application-routing
