### ISSUE TITLE
Support adding more disk to existing cluster nodes (including autoscale)

### ISSUE THREAD

**Issue by DBarthe** [Azure/AKS#698]
Hello,

How to increase the disk size of existing kubernetes nodes ?

What to do if the node disks are full, or if I need higher IOPS ?

Could it be possible to stop the nodes, add disk or increase existing one, then restart and configure k8s to use the new or extended disk ?

Thanks in advance

**Comment by agolomoodysaada** [comment]
related: https://github.com/Azure/AKS/issues/287

**Comment by weinong** [comment]
When creating AKS you can specify the disk size. 

After created, you can stop the vm and resize or add the disk

**Comment by agolomoodysaada** [comment]
@weinong , yes but that doesn't work with autoscaling

**Comment by mleneveut** [comment]
What I did to increase my node's disk size (need to stop the VM first) : 

```
$disk = Get-AzureRmDisk -ResourceGroupName 'MC_xxx_northeurope' -DiskName 'aks-nodepool1-xxx_OsDisk_1_xxx'
$disk.DiskSizeGB = 60
Update-AzureRmDisk -ResourceGroupName 'MC_xxx_northeurope' -DiskName 'aks-nodepool1-xxx_OsDisk_1_xxx' -Disk $disk
```

(start the VM)

**Comment by agolomoodysaada** [comment]
@mleneveut , that works until you scale your cluster and down and provision new VMs in the same cluster

**Comment by jnoller** [comment]
clarified title to reflect the feature request, marked as enhancement request.

**Comment by agolomoodysaada** [comment]
This would probably be solved via NodePool support
