### ISSUE TITLE
Istio on AKS - Automatic sidecar injection - Pods in Pending state

### ISSUE THREAD

**Issue by sreenivasmr** [Azure/AKS#699]
**What happened**:

I have installed Istio on my AKS instance asp per documentation here https://istio.io/docs/setup/kubernetes/sidecar-injection/#automatic-sidecar-injection 

NAME= testswagger-b646f54d7-2rgcc
READY= **_0/2_**                         
STATUS= _**Pending**_   
RESTARTS= 0          
AGE= 55m   
IP= <none>   
NODE= <none>   
NOMINATED NODE= <none>

**What you expected to happen**:

Pods to have sidecars injected automatically on deploy / creation and running successfully.

NAME= testswagger-b646f54d7-2rgcc
READY= **_2/2_**                         
STATUS= _**Running**_   
RESTARTS= 0          
AGE= 55m   
IP= <none>   
NODE= <none>   
NOMINATED NODE= <none>

**How to reproduce it (as minimally and precisely as possible)**:

* Setup an AKS environment.
* Install Istio using helm https://istio.io/docs/setup/kubernetes/helm-install/
* Use sidecar with Automatic sidecar injection --> https://istio.io/docs/setup/kubernetes/sidecar-injection/
* Enable Istio injection on your namespace using the command -->  kubectl label namespace your-namespace-name istio-injection=enabled 
* Redeploy your micro service. Expectation is to get the sidecar automatically provisioned.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

$kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)

4 VMs

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

dotnet core http micro services

- Others:

**Comment by anicoll** [comment]
Something that helped me with auto-injection was
`$ kubectl label namespace default istio-injection=enabled`

you need to enable it per namespace and then re-create your pods.

**Comment by dtzar** [comment]
This is definitely working in general @sreenivasmr 
Did you get things resolved?

If not, to further troubleshoot I'd grab the logs from the `istio-sidecar-injector`* pod

**Comment by sreenivasmr** [comment]
Yep. Thanks. I got it working.
    On Monday, March 18, 2019, 4:15:28 PM PDT, David Tesar <notifications@github.com> wrote:  
 
 
This is definitely working in general @sreenivasmr
Did you get things resolved?

If not, to further troubleshoot I'd grab the logs from the istio-sidecar-injector* pod

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
