### ISSUE TITLE
AKS node connection to OMS in other subscription

### ISSUE THREAD

**Issue by borstibacon** [Azure/AKS#700]
Hi,

while deploying AKS i recognized, that the nodes are not connected automatically to the configured central OMS workspace in antoher subscription. After deployment AKS creates an own Default-OMS workspace for the nodes and connected them.

When deploying AKS within the same subscription, where the OMS is placed in, the nodes connected to this OMS automatically.

I used the same ARM-template for the deployment.
After the nodes connected to the wring workspace, I could connect them manually to the central workspace. But this should be possible automatically while build up the cluster.

What could cause this problem?
Thanks!

BR

Borsti

**Comment by weinong** [comment]
What is your template like?

**Comment by borstibacon** [comment]
Hi,

@weinong 
Thank you for your response.
Sorry for my late answer, I was sick for some days.

In the meantime I´ve resolved the problem. 
There is an policy on subscription level "auto provisioning" which was activated and wrong configured.
For this there are two options:

deactivate this option and AKS will use the OMS workspace from you deployment paramters.

or

activate this option and set the related OMS workspace in the configuration. 
Dont use the "default workspace" option, because in this case aks will be connected to an default created oms within the subscription.

BR 

Borsti
