### ISSUE TITLE
Log and alert denied connection attempts to the public K8s API

### ISSUE THREAD

**Issue by borstibacon** [Azure/AKS#701]
Hi,

I´m looking for a solution to log and alert many denied connection attempts to the public K8s API.

I´ve already  konfigured the K8S service by following this description:
https://www.danielstechblog.io/sending-logs-from-the-azure-kubernetes-service-master-endpoint-to-log-analytics/

What I´m now looking for is a solution, to get only the logs regarding connection attempts to the public API and creates alerts when a lot of connection attempts where denied.

Does anyone done already something like this?

BR

Borsti

**Comment by weinong** [comment]
Can you log this feature request at https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks

**Comment by borstibacon** [comment]
Hi,

yes i can do.

BR

Borsti
