### ISSUE TITLE
az vm list-skus returns no VM for a region

### ISSUE THREAD

**Issue by ArundathiGV** [Azure/AKS#702]
az vm list-skus -l eastus2 returns  me no VM for my subscription. 

But with azure aks portal I get many VM's for same region. Why is  such inconsistency with the api.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
