### ISSUE TITLE
How do I get the Kubernetes events from Azure portal

### ISSUE THREAD

**Issue by DanielWangZhanggui** [Azure/AKS#703]
**What happened**:
- Created an AKS cluster
> no way to collect events from Kubernetes and trigger Alerts based on the events (like pod/node scale )

**What you expected to happen**:

> show the events information and configure alerts

**How to reproduce it (as minimally and precisely as possible)**:
- Create an AKS cluster

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by seanmck** [comment]
This is not available today. Please submit a feedback request at https://aka.ms/aks/feedback.
