### ISSUE TITLE
POD fails during cluster scaling

### ISSUE THREAD

**Issue by andig** [Azure/AKS#704]
I'm reproducibly seeing above error in the cluster autoscaler log files:

	I1026 09:20:18.456765       1 static_autoscaler.go:258] No unschedulable pods
	I1026 09:20:18.576563       1 scale_down.go:643] No candidates for scale down
	E1026 09:20:25.423590       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	E1026 09:20:25.424396       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	E1026 09:20:25.424613       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	E1026 09:20:25.425720       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	W1026 09:20:25.425852       1 reflector.go:341] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:212: watch of *v1.Node ended with: very short watch: k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:212: Unexpected watch close - watch lasted less than a second and no items received
	E1026 09:20:25.425922       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	E1026 09:20:25.426055       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	E1026 09:20:25.426171       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	E1026 09:20:25.426273       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	E1026 09:20:25.436682       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	E1026 09:20:25.437003       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	E1026 09:20:25.437134       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	E1026 09:20:25.437351       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	E1026 09:20:25.437428       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	E1026 09:20:25.437571       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	E1026 09:20:25.437670       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	E1026 09:20:25.437902       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3147, ErrCode=NO_ERROR, debug=""
	W1026 09:20:25.457845       1 reflector.go:341] k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1.Service ended with: very short watch: k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130: Unexpected watch close - watch lasted less than a second and no items received
	W1026 09:20:25.457899       1 reflector.go:341] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:293: watch of *v1beta1.DaemonSet ended with: very short watch: k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:293: Unexpected watch close - watch lasted less than a second and no items received
	W1026 09:20:25.457958       1 reflector.go:341] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:174: watch of *v1.Pod ended with: very short watch: k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:174: Unexpected watch close - watch lasted less than a second and no items received
	W1026 09:20:25.458722       1 reflector.go:341] k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1.StorageClass ended with: very short watch: k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130: Unexpected watch close - watch lasted less than a second and no items received
	W1026 09:20:25.459685       1 reflector.go:341] k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1.Pod ended with: very short watch: k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130: Unexpected watch close - watch lasted less than a second and no items received
	W1026 09:20:25.652833       1 reflector.go:341] k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1.ReplicationController ended with: too old resource version: 281755 (284135)
	W1026 09:20:25.655559       1 reflector.go:341] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:266: watch of *v1beta1.PodDisruptionBudget ended with: too old resource version: 281765 (284138)
	W1026 09:20:25.656280       1 reflector.go:341] k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1.PersistentVolume ended with: too old resource version: 281748 (284133)
	W1026 09:20:25.671053       1 reflector.go:341] k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1beta1.StatefulSet ended with: too old resource version: 281769 (284139)
	W1026 09:20:25.671167       1 reflector.go:341] k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1beta1.PodDisruptionBudget ended with: too old resource version: 281765 (284138)
	W1026 09:20:25.693355       1 reflector.go:341] k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130: watch of *v1.PersistentVolumeClaim ended with: too old resource version: 281748 (284134)
	I1026 09:20:26.455502       1 reflector.go:240] Listing and watching *v1.Node from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:212
	I1026 09:20:26.458890       1 reflector.go:240] Listing and watching *v1beta1.DaemonSet from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:293
	I1026 09:20:26.459199       1 reflector.go:240] Listing and watching *v1.Service from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130
	I1026 09:20:26.459266       1 reflector.go:240] Listing and watching *v1.StorageClass from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130
	I1026 09:20:26.459574       1 reflector.go:240] Listing and watching *v1.Pod from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:174
	I1026 09:20:26.459803       1 reflector.go:240] Listing and watching *v1.Pod from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130
	I1026 09:20:26.653271       1 reflector.go:240] Listing and watching *v1.ReplicationController from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130
	I1026 09:20:26.655681       1 reflector.go:240] Listing and watching *v1beta1.PodDisruptionBudget from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:266
	I1026 09:20:26.656535       1 reflector.go:240] Listing and watching *v1.PersistentVolume from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130
	I1026 09:20:26.671326       1 reflector.go:240] Listing and watching *v1beta1.PodDisruptionBudget from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130
	I1026 09:20:26.671472       1 reflector.go:240] Listing and watching *v1beta1.StatefulSet from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130
	I1026 09:20:26.693762       1 reflector.go:240] Listing and watching *v1.PersistentVolumeClaim from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:130
	I1026 09:20:28.736725       1 utils.go:503] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
	I1026 09:20:28.736875       1 static_autoscaler.go:258] No unschedulable pods
	I1026 09:20:28.865323       1 scale_down.go:643] No candidates for scale down
	I1026 09:20:38.955677       1 azure_manager.go:261] Refreshed ASG list, next refresh after 2018-10-26 09:21:38.955668636 +0000 UTC m=+2863.900159080
	I1026 09:20:39.131065       1 utils.go:503] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
	I1026 09:20:39.131178       1 static_autoscaler.go:258] No unschedulable pods
	I1026 09:20:39.265120       1 scale_down.go:643] No candidates for scale down
	I1026 09:20:49.484940       1 static_autoscaler.go:160] 2 unregistered nodes present

The error happens whenever cluster scaling operation happens- independently if its triggered by the auto scaler or manually using azure cli. This includes scale *out* scaling especially which should not lead to resource shortage.

Workaround for https://github.com/Azure/AKS/issues/676 has already been applied and has taken care of that class of errors.

**Comment by andig** [comment]
The same errors are found in other PODs, e.g. kube-dns:

````
E1026 09:36:59.396177       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=5, ErrCode=NO_ERROR, debug=""
E1026 09:36:59.396585       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=5, ErrCode=NO_ERROR, debug=""
````

**Comment by weinong** [comment]
@andig did you see this error before the workaround is applied?

**Comment by weinong** [comment]
I think I know what’s going on. I will update here when we have the fix. Thanks!

________________________________

**Comment by andig** [comment]
Thank you. Don‘t think I‘ve seen it before the fix but would need to downgrade to be really sure.

**Comment by andig** [comment]
@weinong any more insights whats going on on this one?

**Comment by weinong** [comment]
Unnecessary api server restart causes it. I’ll update when we have a fix.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by andig** [comment]
This is a real problem, not only cosmetic in the autoscaler log files. This breaks running PODs like e.g. the gitlab runner. Error from the gitlab runner log:

    ERROR: Job failed (system failure): error dialing backend: dial tcp: lookup aks-nodepool1-23147715-0 on 172.30.0.10:53: server misbehaving

Which means that with *every* single scaling operation the running workloads break. Very ugly!

**Comment by andig** [comment]
Is this related to https://github.com/kubernetes/kubernetes/pull/70353 with api server restart as root cause?

**Comment by weinong** [comment]
@andig it's not rolled out yet. I will update when it's done

**Comment by andig** [comment]
For 2 weeks now this has been fixed in western europe, at least for me. The support ticket is closed, not sure what else is missing. Closing this one as wfm.

**Comment by dcvtruong** [comment]
@weinong,  Is there a fix or a workaround?

I'm getting this issue in all the pod in kube-system namespace.  Running AKS v1.11.5.

		E0129 19:23:22.538296       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=7, ErrCode=NO_ERROR, debug=""
		E0129 19:23:22.541618       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=7, ErrCode=NO_ERROR, debug=""

**Comment by weinong** [comment]
@dcvtruong it typically means the API server is not up/restarting. What region is it? Have you enabled api server log to see if it was restarting?

**Comment by weinong** [comment]
@dcvtruong for LB IP stuck in pending, `kubectl get events` should tell you the reason. possibly due to quota limit. Also, I'd recommend to enable control plane logs.
https://docs.microsoft.com/en-us/azure/aks/view-master-logs

how often do you see the watch error?

**Comment by dcvtruong** [comment]
@weinong The quota limit for public ip or static public ip is at 1% and 5% usage.  When I deploy an app like prometheus the error is reported in dns pod.
