### ISSUE TITLE
Load Balancer Service with Static IP Address is Stuck in DeletingLoadBalancer event

### ISSUE THREAD

**Issue by xinyi-joffre** [Azure/AKS#705]
**What happened:**

When deleting and recreating working Load Balancer services with a static IP address, one of our public IPs got stuck in pending. The other three static IP addresses are still deploying fine.

When running `kubectl describe svc <service name>`, there are none of the usual events, such as EnsuringLoadBalancer.

When querying `kubectl get events`, I see that this service has been emitting the DeletingLoadBalancer event for 7 hours.

| LAST SEEN  | FIRST SEEN | COUNT | NAME | KIND | SUBOBJECT | TYPE  | REASON | SOURCE | MESSAGE
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| 7s | 7h  | 110 | service-name.1561188030677ac1 | Service | | Normal | DeletingLoadBalancer | service-controller | Deleting load balancer

Deleting the service and redeploying again still does not fix the issue. Deleting the load balancer and redeploying again also does not fix the issue. Only this service name is broken--it seems to be something with the service controller itself getting stuck. I cannot do anything to get this service out of the stuck state.

**What you expected to happen:**
When I recreate a Load Balancer service with Static IP Address, it creates a service with the External IP set correctly each time.

**How to reproduce it (as minimally and precisely as possible):**
Create multiple load balancer services and delete all of them and recreate again. If one of them is stuck in pending state with no EnsureLoadBalancer events, then it has been reproduced.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.3
- Size of cluster (how many worker nodes are in the cluster?): 3 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.); HTTP microservices

**Comment by weinong** [comment]
https://docs.microsoft.com/en-us/azure/aks/view-master-logs
Can you try to see the controller manager log?

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
