### ISSUE TITLE
Cluster autoscaler can't scale down

### ISSUE THREAD

**Issue by andig** [Azure/AKS#706]
**What happened**:

Deployed cluster autoscaler with min 1, max 2 nodes and had it scale to 2. Expected CA to scale down to single node again.

**What you expected to happen**:

CA fails to scale down due to azure-deployed PODs:

	I1026 16:42:44.427991       1 static_autoscaler.go:258] No unschedulable pods
	I1026 16:42:44.520073       1 scale_down.go:453] Finding additional 2 candidates for scale down.
	I1026 16:42:44.520150       1 cluster.go:81] Fast evaluation: aks-agentpool-36611692-0 for removal
	I1026 16:42:44.520183       1 cluster.go:95] Fast evaluation: node aks-agentpool-36611692-0 cannot be removed: non-daemonset, non-mirrored, non-pdb-assignedkube-system pod present: metrics-server-76f76c6bfd-slfp4
	I1026 16:42:44.520206       1 cluster.go:81] Fast evaluation: aks-agentpool-36611692-1 for removal
	I1026 16:42:44.520235       1 cluster.go:95] Fast evaluation: node aks-agentpool-36611692-1 cannot be removed: non-daemonset, non-mirrored, non-pdb-assignedkube-system pod present: heapster-5f8d5688-lbnqk
	I1026 16:42:44.520267       1 scale_down.go:490] 2 nodes found to be unremovable in simulation, will re-check them at 2018-10-26 16:47:44.328975143 +0000 UTC m=+29629.273465487
	I1026 16:42:44.587911       1 scale_down.go:643] No candidates for scale down

or:

    I1030 12:56:42.712108       1 cluster.go:95] Fast evaluation: node aks-nodepool1-23147715-0 cannot be removed: non-daemonset, non-mirrored, non-pdb-assignedkube-system pod present: kube-dns-v20-668899dbdc-27zx4

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

      Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
      Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?): 1-2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): gitlab runner

Would it make sense to apply default PDB to the azure-distributed PODs?

**Comment by kjanshair** [comment]
Same issue with v1.10.8. I can only see this on node-1 which was supposed to remove from the cluster:
`kubectl get all -o wide --all-namespaces | grep aks-agentpool-41320097-1`
```
kube-system   pod/azure-cni-networkmonitor-qbmzg          1/1     Running   0          12s   xxx-xxx-xxx-x   aks-agentpool-41320097-1
kube-system   pod/kube-proxy-rlhvq                        1/1     Running   0          1d    xxx-xxx-xxx-x   aks-agentpool-41320097-1
kube-system   pod/kube-svc-redirect-5sz5w                 2/2     Running   0          1d    xxx-xxx-xxx-x   aks-agentpool-41320097-1
```

**Comment by kjanshair** [comment]
Same issue with v1.10.8. I can only see this on aks-agentpool-xxxxx-1 which was supposed to remove from the cluster:
`kubectl get all -o wide --all-namespaces | grep aks-agentpool-xxxxx-1`
```
kube-system   pod/azure-cni-networkmonitor-qbmzg          1/1     Running   0          12s   xxx-xxx-xxx-x   aks-agentpool-xxxxx-1
kube-system   pod/kube-proxy-rlhvq                        1/1     Running   0          1d    xxx-xxx-xxx-x   aks-agentpool-xxxxx-1
kube-system   pod/kube-svc-redirect-5sz5w                 2/2     Running   0          1d    xxx-xxx-xxx-x   aks-agentpool-xxxxx-1
```

**Comment by andig** [comment]
Another error from the gitlab runner:

    ERROR: Job failed (system failure): error dialing backend: dial tcp: lookup aks-nodepool1-23147715-0 on 172.30.0.10:53: server misbehaving

Looks as if cluster-internal communication is broken during scaling?

**Comment by andig** [comment]
For time being I've created a number of PDBs but would appreciate a comment if this is exepected to work with the system pods:

	kubectl create -f autoscaler/kube-dns-pdb.yml
	kubectl create -f autoscaler/kubernetes-dashboard-pdb.yml
	kubectl create -f autoscaler/heapster-pdb.yml
	kubectl create -f autoscaler/metrics-server-pdb.yml
	kubectl create -f autoscaler/tunnelfront-pdb.yml

**Comment by markusdresch** [comment]
I've got the same problem with AKS K8s v1.12.6 and k8s.gcr.io/cluster-autoscaler:v1.12.3

Any news on this?

**Comment by markusdresch** [comment]
ok now it's scaling in. i added PDBs for all single-pod kube-system instances with a minAvailable: 0 spec.

**Comment by andig** [comment]
@markusdresch I ended doing the same but I'm unsure that is entirely correct. Using 0 minimum you might end with a node without those services available at all?

**Comment by markusdresch** [comment]
if i understand it correctly, since those are single pods without controller, they aren't movable without diruption, ie termination and recreation, since k8s can't know whether replication is allowed or not. you shouldn't end up without those services, but you may have a small interruption until the pods are recreated.
