### ISSUE TITLE
AKS does not create Loadbalancer and it is returning status 500

### ISSUE THREAD

**Issue by ErickWendel** [Azure/AKS#707]
**What happened**:
Hi Guys. I have a problem to create external Loadbalancer using AKS. I run that repository https://github.com/giantswarm/kubernetes-prometheus to create a prometheus, grafana and alert manager on my cluster. After that, I deleted this services using `kubectl delete -f file`.
When I tried to create another service (kibana), the loadbalancer is only pending and with the following message: 

```bash
Warning  CreatingLoadBalancerFailed  6s (x6 over 2m)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service default/kibana: timed out waiting for the condition
```

Today I tried again with these commands: `kubectl run nginx --image=nginx --replicas=1` and `kubectl expose deploy nginx --name nginx --type LoadBalancer  --port 80` and my Loadbalancer is only pending with the following message below:

```bash
kdesc svc nginx

Name:                     nginx

Namespace:                default

Labels:                   run=nginx

Annotations:              <none>

Selector:                 run=nginx

Type:                     LoadBalancer

IP:                       10.0.25.73

Port:                     <unset>  80/TCP

TargetPort:               80/TCP

NodePort:                 <unset>  31788/TCP

Endpoints:                10.244.0.18:80

Session Affinity:         None

External Traffic Policy:  Cluster

Events:

  Type     Reason                      Age               From                Message

  ----     ------                      ----              ----                -------

  Warning  CreatingLoadBalancerFailed  2m                service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service default/nginx: network.LoadBalancersClient#List: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: Service returned an error. Status=500 Code="InternalServerError" Message="Encountered internal server error. Diagnostic information: timestamp '20181029T191220Z', subscription id 'fed2ac5e-be3e-4270-93ca-**', tracking id 'f131b1a9-b1a5-45f9-a0a7-**', request correlation id 'f131b1a9-b1a5-45f9-a0a7-**'."

  Normal   EnsuringLoadBalancer        48s (x5 over 2m)  service-controller  Ensuring load balancer


  Warning  CreatingLoadBalancerFailed  38s               service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service default/nginx: network.LoadBalancersClient#List: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: Service returned an error. Status=500 Code="InternalServerError" Message="Encountered internal server error. Diagnostic information: timestamp '20181029T191429Z', subscription id 'fed2ac5e-be3e-4270-93ca-52d7a2d66c34', tracking id 'dd6e08f0-7d58-4e4e-bfe4-**', request correlation id 'dd6e08f0-7d58-4e4e-bfe4-**'."
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: v1.11.3
Server Version: v1.9.11

- Size of cluster (how many worker nodes are in the cluster?)
3 with default VM

**Comment by tomasr** [comment]
One way I've found to troubleshoot these things is to go out to the Azure Portal, and query the Activity Logs on the cluster resource group (i.e. the `MC_xxxxxx` one).

Often this error means the ARM operation that the cluster tries to do to add the load balancer configuration is failing. For example, it could be failing because you have no more available IP addresses or front-end IP configurations available for your load balancer.

**Comment by ErickWendel** [comment]
Awesome! I'll  check :D

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
