### ISSUE TITLE
Allow having ingress' public ip in different resource group

### ISSUE THREAD

**Issue by 0x7f** [Azure/AKS#708]
FEATURE REQUEST

**What happened**: 

I have a working AKS cluster and create an ingress according to this [document](https://docs.microsoft.com/en-us/azure/aks/ingress-static-ip). It describes how to set up the ingress with a static public ip. The static public ip must be located in the same generated resource group as the other AKS resources. This fact is also stated in the [official documentation](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer) and can also be found in other github issues, e.g. this [one](https://github.com/Azure/AKS/issues/428#issuecomment-407326546). I searched this github project for similar issues, but did not find an explicit feature request for this to change.

**What you expected to happen**:

I understand why it has to be this way and I am also able to work with it by automating it via terraform, because the `kubernetes_cluster` resource exports the generated resource group name as [`node_resource_group`](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#node_resource_group). But I would keep my public ips in another resource group, esp. to avoid that when I delete and recreate the cluster, the public ip in the resource group is not accidentally deleted as well. It would be great if I can keep the public ip resource in another resource group and still reference it.

I can image that instead of writing the ip that I configure the resource id as the `loadBalancerIP` or have an additional label in the service where I can put the resource id. An alternative would be to change the AKS side to not just search the current resource group for the IP, but search e.g. the whole subscription.

**How to reproduce it (as minimally and precisely as possible)**:
Create an AKS cluster with ingress and reference a public ip that is located in a different resource group.

**Anything else we need to know?**:
Guess not.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.11
- Size of cluster (how many worker nodes are in the cluster?) 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) HTTP microservices with nginx-ingress
- Others:

**Comment by omerlh** [comment]
I can confirm that following this [article](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/aks/static-ip.md) allowed me to achieve exactly that - having the IPs defined in a different resource group. Please notice that it require higher Kubernetes version - 1.10 - than what you're using.

**Comment by 0x7f** [comment]
@omerlh thank you very much. That is exactly what I'm looking for. I was searching with different terms and did not find any useful resources. When searching for `azure-load-balancer-resource-group` I find various examples on how to do that :)

**Comment by mariojacobo** [comment]
@omerlh  - how do you manage to achieve this ? The article in question refers to services of type "LoadBalancer", but this does not work for ingresses (nginx). I would assume that the annotation needs to be added to the Nginx ingress service declaration, however that did not work. AKS still complains that the IP is not in the MC* resource group. 

My setup is: NGINX ingress > Service (type ClusterIP) > Deployments > Replicas > PODS.  With this, the Public IP still needs to be in the same RG, so not sure how you managed to get around this. or perhaps you are using just plain HTTP with service type LoadBalancer, which indeed works.

**Comment by omerlh** [comment]
No, this has to be nginx settings. If you use the chart, you can configure the controller using the following settings:
```yaml
controller:
  service:
    loadBalancerIP: <>
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: <rg name>
```
Of course, nginx service has to be of type load balancer - but I guess you already did that.
