### ISSUE TITLE
azure-disk StorageClass missing allowVolumeExpansion: true 

### ISSUE THREAD

**Issue by garethmorris78** [Azure/AKS#709]
**What happened**: Unable to resize persistent volumes due to storage classes for default and managed-premium not having the allowVolumeExpansion: true 

**What you expected to happen**: I was able to resize as per 
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims

**How to reproduce it (as minimally and precisely as possible)**: Try and resize a PVC and it does not work. 

**Anything else we need to know?**:  

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) web apps
- Others:

**Comment by wiegandf** [comment]
Why would you want this to be default? Just create your own storage class.

What is a bit more annoying is that the default storage class is always overwritten and thus it seems to be impossible to set your own default storage class.

**Comment by mtparet** [comment]
We have the same issue, we have statefulset created with managed-premium class storage and it seems we cannot easily expand the disks... (too bad for an ELK stack growing)
I was initially following the comment left by @andyzhangx on this issue https://github.com/kubernetes/kubernetes/issues/68427#issuecomment-451742005

**Comment by sharkymcdongles** [comment]
Even if this is included in the SC the expansion feature doesn't work. You have to completely delete the deployment that mounts the volume and wait for it to become unattached before issuing the expansion. If you do it first then delete it doesn't work. There's no way to do this live.

**Comment by andyzhangx** [comment]
@sharkymcdongles actually you don't need to delete the deployment, you could set the replica to 0, and then resize, it's true that you can not resize an azure disk on live since it's restricted by azure disk RP. Here are the details about azure disk resize usage: https://github.com/andyzhangx/demo/blob/master/linux/azuredisk/azuredisk-sizegrow.md

**Comment by sharkymcdongles** [comment]
That is really splitting hairs. Fact of the matter is other providers you
can edit the request within k8s live and then the pvc is resized. No
replicas 0 or deployment deleting or editing. Even open source options like
rook support such functionality. Not sure why Azure wants to do something
so critical so poorly. Resizing pvcs should not require this much manual
work under any circumstances. Imagine having to do this for production
databases. A nightmare. This doesn't even touch on the complete failure
that is azure attach detach.

**Comment by guitmz** [comment]
running kubernetes 1.12.6 and I cannot append `allowVolumeExpansion: "true"` to the `managed-premium` storage class manually, any feedback on that?

`kubectl edit storageclass managed-premium`

the error returned is just the standard one like syntax error: `error: Edit cancelled, no valid changes were saved.`. I have tried adding quotes to `true` and also tried without them.

**Comment by andyzhangx** [comment]
@guitmz the `managed-premium` storage class is immutable in AKS, you need to define a new one.

**Comment by guitmz** [comment]
@andyzhangx 🤦‍♂️ this doesnt look nice.. anyway in this case, it should contain  `allowVolumeExpansion: "true"` by default or a huge note in the documentation (if there isnt any already) about this.. imagine discovering this and having to migrate all your data after months of uptime... not cool

**Comment by omnipresentminded** [comment]
We are needing this ability as well, we really don't want to take our replicas down to 0 in a production environment.

**Comment by arianitu** [comment]
I'm having the same issue. It sucks to learn about this after the fact. I want new instances added to have more disk space, but can't 

For people trying to expand their cluster size, the best way imo would be to do it like this:

1. Scale your StatefulSet by N. Wait for new node to become live
2. Scale down your node by 1
3. Edit the PVC to grow it 
4. Scale it up by 1.

**Comment by mtparet** [comment]
I asked the support and they said that I could edit the `default` and `managed-premium` classes to add `AllowVolumeExpansion: true`.

I did it and the setting seems correctly persisted! :tada:

**Comment by marrobi** [comment]
Just hit this today, would be nice if ```AllowVolumeExpansion: true``` was in the pre provisioned storage classes.

**Comment by agronholm** [comment]
Indeed. Sure, you can edit the storage classes and add that but why is it not the default when it works?

**Comment by afdezl** [comment]
This seems to be enabled by default now in AKS for both `managed-premium` and `default` -- `version 1.15.10`

**Comment by sharkymcdongles** [comment]
> This seems to be enabled by default now in AKS for both `managed-premium` and `default` -- `version 1.15.10`

Only took 2 years. Typical Azure turnaround time for these clowns.

**Comment by agronholm** [comment]
> Only took 2 years. Typical Azure turnaround time for these clowns.

I just recently created a cluster on GCS and it wasn't enabled by default there either, so...
