### ISSUE TITLE
`CancelRequest not implemented` error when logging in with Azure AD enabled cluster

### ISSUE THREAD

**Issue by nphmuller** [Azure/AKS#710]
When kubectl requests a login on a Azure AD enabled cluster the following error is printed if you wait a bit:
`E1031 17:48:17.963825    3397 round_trippers.go:169] CancelRequest not implemented by *azure.azureRoundTripper`

If you log in after the error is printed, everything still works as expected.

__Repro__
- Follow the steps described here: https://docs.microsoft.com/en-us/azure/aks/aad-integration
- When running: `kubectl get nodes` the following message is printed:
`To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXX to authenticate.`
- Wait a bit.
- The error message above is printed.
- Log in and everything still works as expected.

**Comment by janbrunrasmussen** [comment]
Any updates on this? We are seeing the same thing! @sauryadas?

**Comment by omerlh** [comment]
I'm experiencing the same issue on a cluster deployed with ACS engine latest version

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
