### ISSUE TITLE
Kuberentes 1.12.x support?

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#713]
Do you have an expected date to support 1.12.x?  Also is there a place to go and find these supported versions and roadmap on when newer version will be supported?

Thanks.

**Comment by tomasr** [comment]
Kubernetes releases go first through [acs-engine](https://github.com/Azure/acs-engine/) before going into AKS.

I believe support for `1.12.2` was included in `acs-engine 0.25.0` a [few days](https://github.com/Azure/acs-engine/releases/tag/v0.25.0) ago, so it's.... coming. I have no inside information, but either it will come before the holidays, or will have to wait until January or so.

**Comment by jnoller** [comment]
The ACS-Engine and AKS teams are working to update the Kubernetes version to 1.12.x - however there is a known security issue with 1.12.2. 

We are waiting a 1.12.3 update/release from upstream, additionally there is an issue with Azure CNI we are working to address before rolling this out. We hope to have resolution and rollout proceed before the turn of the year, pending the needed fixes.

/cc @jackfrancis

**Comment by jnoller** [comment]
See issue: https://github.com/Azure/aks-engine/issues/73

**Comment by timja** [comment]
@jnoller any more news? Seems that issue was fixed late December, its been another month since then

**Comment by kvolkovich-sc** [comment]
@timja, It already added to some regions 
![screen shot 2019-01-25 at 6 39 59 pm](https://user-images.githubusercontent.com/24652543/51755827-a4b32100-20d0-11e9-828b-9c16621490a4.png)

**Comment by jnoller** [comment]
@kvolkovich-sc @timja I'm not sure who runs that twitter bot, but it's not accurate (at all). All 1.12 releases have been backed out from all regions due to additional regressions found causing service instability. We will update all 1.12 related bugs when we are able to get 1.12 out and ensure service stability
