### ISSUE TITLE
timeout expired waiting for volumes to attach/mount for pod

### ISSUE THREAD

**Issue by andres-carrilloAdapt2** [Azure/AKS#716]
**What happened**:
I have an elasticsearch pod with a PVC as azure-disk
when i first deploy my helm chart, it works. everything is connected and pods are running.
i am testing the persistent storage, so i want to delete the pod and see if my data is being persisted. 
here is my yaml files: 

`                                  
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
     name: mongo-disk
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-data
  annotations:
    storageClassName: mongo-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mongo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mongo
    spec:
      containers:
      - image: mongo:3
        name: mongo
        resources: {}
        volumeMounts:
        - name: logdb
          mountPath: /data/db
      volumes:
      - name: logdb
        persistentVolumeClaim:
          claimName: mongo-data
status: {}

**What you expected to happen**:
i expect the pod to run after i delete it
the error i get is: Unable to mount volumes for pod "elasticsearch-5568686bcc-tfl77_default(d518f9b7-e449-11e8-aa99-424ef1a659b9)": timeout expired waiting for volumes to attach/mount for pod "default"/"elasticsearch-5568686bcc-tfl77". list of unattached/unmounted volumes=[logstorage]

**Anything else we need to know?**:
There is nothing else in the logs 
**Environment**:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.11", GitCommit:"1bfeeb6f212135a22dc787b73e1980e5bccef13d", GitTreeState:"clean", BuildDate:"2018-09-28T21:35:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster 1
graylog deployment, elastic search and mongo have their own pvc and it connects at startup, but upon deleting the pod, the above error is shown and it wont start again
- Others:

**Comment by andyzhangx** [comment]
Hi @andres-carrilloAdapt2 , is the pod recovered now? Is it in running state? It takes minutes from one pvc disk detached and attached if you delete that pod of `Deployment`.

**Comment by andyzhangx** [comment]
I will close this issue now, let me know if you have any related issue.
