### ISSUE TITLE
User provided vnet/subnet with kubenet networking plugin missing route table/nsg association

### ISSUE THREAD

**Issue by juan-lee** [Azure/AKS#718]
**Symptoms**
AKS clusters with user provided vnet/subnet and kubenet network plugin won't be able to route intra-cluster network traffic between agent nodes.

**Root Cause**
The route table and network security group created as part of the MC_ resource group aren't associated with the user provided subnet.

**Workaround**
The workaround has been nicely summarized by @serbrech [here](https://github.com/serbrech/AKS-vnet-kubenet). If you already have a cluster in this state, you can run the azure cli command below.
``` bash
az network vnet subnet update \
-g <user_provided_vnet_resource_group> \
--route-table <route_table_from_mc_resource_group> \
--network-security-group <nsg_from_mc_resource_group> \
--ids <user_provided_vnet_subnet_id>
```

**Comment by juan-lee** [comment]
Related issues
#400 
#588

**Comment by chaholl** [comment]
@juan-lee The command you've posted doesn't work. Since the route-table and NSG are in a different resource group it fails with an error like:

`The Resource 'Microsoft.Network/routeTables/aks-agentpool-29481309-routetable' under resource group 'USER_PROVIDED_VNET_RG' was not found.`

**Comment by juan-lee** [comment]
> @juan-lee The command you've posted doesn't work. Since the route-table and NSG are in a different resource group it fails with an error like:
> 
> `The Resource 'Microsoft.Network/routeTables/aks-agentpool-29481309-routetable' under resource group 'USER_PROVIDED_VNET_RG' was not found.`

The route-table and NSG being in a different resource group shouldn't be a problem. I know folks have used the steps in https://github.com/serbrech/AKS-vnet-kubenet to make the associations.

**Comment by allenstecat** [comment]
Ws this issue fixed @juan-lee

**Comment by JunSun17** [comment]
@allenstecat We are working on a fix to do automated route table association to subnet in the custom vnet kubenet networking case. The fix is expected to be released in 2 weeks.

**Comment by brusMX** [comment]
Having this issue as well. Tagging @jcorioland for visibility. @juan-lee @JunSun17 can you please let us know when this is solved?

**Comment by JunSun17** [comment]
The fix have been rolled out and route table should be automatically associated when you create a new cluster.

Please note, in the kubenet case, the NSG has been applied to all VM nics already, therefore, it is not necessary to associate it with the subnet.

**Comment by jcorioland** [comment]
@JunSun17 thanks for the follow-up. Is the fix deployed yet? Just tried a deployment in West Europe and UK West, using custom VNET + Kubenet without running my customer scripts to link the NSG and Route Table, but the route table has not been associated to the subnet:

![image](https://user-images.githubusercontent.com/4435138/56413128-be56a580-6286-11e9-949f-20febbe503dc.png)

Thanks!
Julien
