### ISSUE TITLE
Sometimes exponentialBackOffOnError leads to longer mount times

### ISSUE THREAD

**Issue by tahmmee** [Azure/AKS#719]
**What happened**:
Created a Pod which mounted 5 disks and monitored the attachment of the disks to VM 
`az vm show... --query storageProfile.dataDisks -o table` 

It only took about 30s for all of the disks to be attached to the vm.  But I noticed kubelet logs had already been looking for each of the disks and so the last ones to mount went into fairly high backoff (1m4s)
```bash
Nov 12 21:21:12 aks-agentpool-38464279-0 kubelet[3501]: E1112 21:21:12.595970    3501 nestedpendingoperations.go:267] 
Operation for "\"kubernetes.io/azure-disk//subscriptions/..."" failed.
No retries permitted until 2018-11-12 21:22:16.595939421 +0000 UTC m=+59822.661305484
(durationBeforeRetry 1m4s). Error: "Volume not attached according to node status for volume \"pvc-acc51c36-e6c0-11e8-8fcc-062ea35501ea\" ..."
```

The interesting part about this was I queried aks the same time message was generated and the result showed that the disk was actually attached.  But since controller thought otherwise it went into backoff and I lost about 50s till the next retry.  

My guess is that kubelet got some cached data or that it's just printing the logs a bit late.  Or maybe it was a very close race between my query and the attach-detach controller.

**What you expected to happen**:
Understandably, 5 disks is a lot, but If possible, would be nice to be event drive via a watcher on the Azure VM for some event that the disk is attached.  After such an event, VerifyAttach should run.  Or disable/customize the backoff.  Although it seems to be always enabled if I'm understanding this correctly in regard to [pending operations](https://github.com/kubernetes/kubernetes/blob/954996e231074dc7429f7be1256a579bedd8344c/pkg/volume/util/operationexecutor/operation_executor.go#L159)

**How to reproduce it (as minimally and precisely as possible)**:
Use case is very similar to a stateful set with 5 disks.   My specific use case involved a couchbase cluster via [autonomous operator](https://www.couchbase.com/products/cloud/kubernetes) with persistent volumes.

**Environment**:
```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster 
5 node cluster, 4 worker nodes
Standard DS2 v2 (2 vcpus, 7 GB memory)

- General description of workloads in the cluster
[Couchbase operator](https://www.couchbase.com/products/cloud/kubernetes), 3 node cluster with persisted volumes.  No load, just cluster creation.

**Comment by andyzhangx** [comment]
hi @tahmmee Thanks for the info. In latest master branch, I have refactored the attach/detach retry mechanism, switch to use k8s attach-detach controller to do the retry, below are related PRs:
https://github.com/kubernetes/kubernetes/pull/70568

Moreover, there is a dirty vm cache issue(https://github.com/kubernetes/kubernetes/pull/71495) which could lead to disk mount failure forever.

**Comment by tahmmee** [comment]
Thanks @andyzhangx , which k8s release is this merged into?  Or is there a way to run from master branch in AKS?

**Comment by andyzhangx** [comment]
@tahmmee You cannot try master branch on AKS, and you could try new versions on acs-engine,
 below are the fixed version:
| k8s version | fixed version |
| ---- | ---- |
| v1.9 | issue introduced in v1.9.2, no cherry-pick fix allowed|
| v1.10 | in cherry-pick |
| v1.11 | 1.11.6 |
| v1.12 | 1.12.4 |
| v1.13 | no such issue |

all details: https://github.com/andyzhangx/demo/blob/master/issues/azuredisk-issues.md#14-azure-disk-attachdetach-failure-mount-issue-io-error

Is it ok to close this issue?

**Comment by tahmmee** [comment]
Verified with 13.10 that we no longer encounter high retryDurations (ie 1-2mins), the highest was 8s.
