### ISSUE TITLE
Azure Germany?

### ISSUE THREAD

**Issue by benkoller** [Azure/AKS#72]
Good morning.

Albeit not being a technical issue it'd be terrific if the preview-release of AKS in the Azure Germany sovereign cloud could be expedited. Its a major selling point.

Feel free to give this issue the boot if you want to preserve the pristine technicality of reported issues.

**Comment by sauryadas** [comment]
we are currently focused on AKS GA ... roll out of AKS is the roadmap and is planned in the second half of 2018

**Comment by slack** [comment]
I'm going to close this specific issue, keep an eye on the regions/availability doc in the repo for updates.
