### ISSUE TITLE
`No such file or directory` when creating any file after cluster scaling down

### ISSUE THREAD

**Issue by OJezu** [Azure/AKS#720]
**What happened**:

After scaling down our AKS, we are unable to create files in most pods running on all remaining nodes. Tries to "touch" or "mkdir" print out `No such file or directory`, no matter the effective user.

Files can be created inside mounted directories, but all directories that are part of root file system itself cannot have new files created.

**What you expected to happen**:
`kubectl exec test-debian-778677b654-8cgnt -- bash -c "touch /root/test_file_creation; ls -l /root"`
  should print out:
```
total 0
-rw-r--r-- 1 root root 0 Nov 13 15:28 test_file_creation
```

we are receiving:
```
touch: cannot touch '/root/test_file_creation': No such file or directory
total 0
```

instead

**How to reproduce it (as minimally and precisely as possible)**:
Scale down AKS cluster from 9 to 3 nodes, try creating files:
`kubectl exec POD -- bash -c "touch /root/test_file_creation; ls -l /root"`

**Anything else we need to know?**:

Scaling up again does not fix old nodes, but pods in newly created node do not fail on file creation.
Pods created after scaling down has been completed also are afflicted, as long as they are created on afflicted node.

I've drained remaining nodes, and restarted them. After node restart and uncordoning, files can be created just fine.

**Environment**:
- Kubernetes version (use `kubectl version`):
server: v1.11.3
client: v1.12.2
- Size of cluster (how many worker nodes are in the cluster?)
Rescaled from 9 to 3, DS2_v2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
HTTP services
- Others:

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
