### ISSUE TITLE
OMS agent problem after node restart

### ISSUE THREAD

**Issue by rncwnd79** [Azure/AKS#721]
**What happened**:
OMS agents show connection error after node restart.

**What you expected to happen**:
OMS agent connections are fine always! After node restart OMS connection should be automatically reestablished.

**How to reproduce it (as minimally and precisely as possible)**:
Restart aks node. Check OMS connection in log analytics.

**Anything else we need to know?**:
We had to restart the nodes because after deploying new versions of our microservices http requests to them failed. Rollback didn't solve the problem.
After restarting one of the nodes, suddenly all of our microservices running on all nodes started to work again. But two out of three OMS agents lost connection.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.6
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) HTTP microservices
- Others: Standard F4s_v2 with accelerated networking turned on

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
