### ISSUE TITLE
Cluster is unresponsive when adding more nodes

### ISSUE THREAD

**Issue by yarinm** [Azure/AKS#724]
**What happened**:
Added two more nodes to my AKS cluster, it took about 15 minutes for them to add. During that time for several minutes the kubernetes API was unresponsive. 

kubectl was getting timed out:
`Unable to connect to the server: net/http: TLS handshake timeout`

**What you expected to happen**:
Cluster should work properly during scaling

**How to reproduce it (as minimally and precisely as possible)**:
I guess reproducing these steps should do it.

**Environment**: West europe
- Kubernetes version (use `kubectl version`):
`
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
`
- Size of cluster (how many worker nodes are in the cluster?) 6 -> 8 nodes

**Comment by andig** [comment]
Looks like https://github.com/Azure/AKS/issues/704. Suspecting https://github.com/kubernetes/kubernetes/pull/70353 as root cause (unable to communicate with API server). I have an open support ticket and will update #704 once resolved.

**Comment by andig** [comment]
#704 has been closed with MS providing a fix

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
