### ISSUE TITLE
OSBA installation issue

### ISSUE THREAD

**Issue by badalk** [Azure/AKS#725]
**What happened**:
Getting error during helm install azure/open-service-broker-azure
**What you expected to happen**:
Installation to succeed
**How to reproduce it (as minimally and precisely as possible)**:
I have created a script based on the steps documented on https://docs.microsoft.com/en-us/azure/aks/integrate-azure. 
I am calling this script in a Jenkinsfile.
Everything is successfully executed except the last stpe to install azure/open-service-broker-azure

I get this error: 
```
Install the Open Service Broker for Azure using the Helm chart
Error: validation failed: unable to recognize "": no matches for kind "ClusterServiceBroker" in version "servicecatalog.k8s.io/v1beta1"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): **1.11.4**
- Size of cluster (how many worker nodes are in the cluster?): **2**
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
**there is nothing installed. This is infrastructure automation script**
- Others:
here is the script:
```
helm init --upgrade

echo "Adding google service catalog repo"
helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com

echo "Install Service Catalog"
helm install svc-cat/catalog --name catalog --namespace catalog --set controllerManager.healthcheck.enabled=false --wait

echo "Add Open Service Broker for Azure Helm repository"
helm repo add azure https://kubernetescharts.blob.core.windows.net/azure

echo "Updating the repo"
helm repo update

echo "Install the Open Service Broker for Azure using the Helm chart"
helm install azure/open-service-broker-azure --name osba --namespace osba \
    --set azure.subscriptionId=${subscriptionId} \
    --set azure.tenantId=${tenantId} \
    --set azure.clientId=${clientId} \
    --set azure.clientSecret=${clientSecret} --wait

```
parameters are passed to the script from jenkinsfile, which is used in the last command

Regards
Badal

**Comment by rh072005** [comment]
I'm also seeing this issue with a similar setup. I've been able to repro it with 1.11.4 and 1.11.5.
It was previously working with a 1.11.2 cluster, as far as I can see the version of Kubernetes is the only difference but can't be sure given the currently available versions.

**Comment by badalk** [comment]
I got it resolved by disabling healthprobes for apiserver and for control manager. at least it appears to be resolved for now

```
helm install svc-cat/catalog --name catalog --namespace catalog \
   --set apiserver.storage.etcd.persistence.enabled=true \
   --set apiserver.healthcheck.enabled=false \
   --set controllerManager.healthcheck.enabled=false \
   --set apiserver.verbosity=2 \
   --set controllerManager.verbosity=2
```

**Comment by HeyHugo** [comment]
I'm having the same issue.

>Error: validation failed: unable to recognize "": no matches for kind "ClusterServiceBroker" in version "servicecatalog.k8s.io/v1beta1"

**Comment by HeyHugo** [comment]
After running `helm repo update` the command works for me 🎉
ping @Peter-Slump

**Comment by Azadehkhojandi** [comment]
````
C:\WINDOWS\system32>kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
````
I'm getting same error - I have ran `helm repo update` but no luck!

```
C:\WINDOWS\system32>helm install azure/open-service-broker-azure --name osba --namespace osba --set azure.subscriptionId="xxxx" --set azure.tenantId="xxxx" --set azure.clientId="xxxx" --set azure.clientSecret="xxxx"
Error: validation failed: unable to recognize "": no matches for kind "ClusterServiceBroker" in version "servicecatalog.k8s.io/v1beta1"
````

**Comment by fredgate** [comment]
I have same problem as @badalk with a script executing same commands.
It fails the first time with same message, but succeeds the second time. I feel like it's because the pods of the chart `svc-cat/catalog` are not completly up and ready. However this chart is intsalled with th eoption `--wait``
