### ISSUE TITLE
AKS deployment incompatibility

### ISSUE THREAD

**Issue by PaulCharlton** [Azure/AKS#726]
Deployment failed. Correlation ID: c99c0bdb-ebbe-40fd-9804-11ba6523e2ae. Specified api-version 2016-03-30 does not meet the minimum required api-version 2016-09-01 to set this property acceleratedNetworking.

is this a known issue?
(happens in multiple azure regions, intermittently) -> 

======================

az aks create --subscription {{hidden}} --resource-group staging_ci_small_001 --name staging-ci-small-001 --node-count 1 --kubernetes-version 1.10.8 --node-vm-size Standard_D4_v3 --admin-username {{hidden}} --node-osdisk-size 60 --service-principal bab1cd18-bb20-401d-841e-3330131af34e --client-secret {{hidden}} --location northeurope --ssh-key-value deployments/secrets/staging-ci-small-001-id-rsa.pub 

==> Deployment failed. Correlation ID: c99c0bdb-ebbe-40fd-9804-11ba6523e2ae. Specified api-version 2016-03-30 does not meet the minimum required api-version 2016-09-01 to set this property acceleratedNetworking.

======================== 
az --version

azure-cli (2.0.50)  acr (2.1.8) acs (2.3.11) advisor (2.0.0) ams (0.3.0) appservice (0.2.6) backup (1.2.1) batch (3.4.1) batchai (0.4.4) billing (0.2.0) botservice (0.1.1) cdn (0.2.0) cloud (2.1.0) cognitiveservices (0.2.3) command-modules-nspkg (2.0.2) configure (2.0.19) consumption (0.4.0) container (0.3.8) core (2.0.50) cosmosdb (0.2.3) dla (0.2.3) dls (0.1.4) dms (0.1.1) eventgrid (0.2.0) eventhubs (0.3.1) extension (0.2.3) feedback (2.1.4) find (0.2.12) hdinsight (0.1.0) interactive (0.4.0) iot (0.3.4) iotcentral (0.1.3) keyvault (2.2.6) lab (0.1.3) maps (0.3.2) monitor (0.2.6) network (2.2.8) nspkg (3.0.3) policyinsights (0.1.0) profile (2.1.2) rdbms (0.3.4) redis (0.3.2) relay (0.1.2) reservations (0.4.0) resource (2.1.6) role (2.1.9) search (0.1.1) servicebus (0.3.2) servicefabric (0.1.7) signalr (1.0.0) sql (2.1.5) storage (2.2.4) telemetry (1.0.0) vm (2.2.7)  Python location '/opt/az/bin/python3' Extensions directory '/home/circleci/.azure/cliextensions'  Python (Linux) 3.6.5 (default, Nov 1 2018, 22:30:01)  [GCC 4.9.2]  Legal docs and information: aka.ms/AzureCliLegal

**Comment by seanmck** [comment]
@jackfrancis Ideas?

**Comment by PaulCharlton** [comment]
@jackfrancis I see this frequently -- we have a CI pipeline that creates dozens of clusters per day, and the incidence rate has been over 10% for the past few weeks, and over multiple azure regions (westus2, northeurope, eastus)

Just saw it again this morning.

**Comment by jackfrancis** [comment]
@PaulCharlton thanks for sharing. Is VM SKU `Standard_D4_v3` a common configuration property across all builds?

**Comment by PaulCharlton** [comment]
@jackfrancis yes, our CI builds are using `Standard_D4_v3`

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
