### ISSUE TITLE
Timeout while polling for control plane provisioning status

### ISSUE THREAD

**Issue by abramz** [Azure/AKS#73]
I get this error when attempting to scale the cluster from 6 nodes to 3 nodes. Everything still functions correctly but there are still 6 VMs & the provisioning state is `failed`.

Any additional attempts to scale the cluster fail with this error.

Command to create cluster:
```sh
az aks create \
  -n k8s-cluster \
  -g container-rg \
  -l westus2 \
  -k 1.8.1 \
  -c 6 \
  -s Standard_D2_v2 \
  -u azureuser \
  --generate-ssh-keys
```

Command to scale cluster:
```
az aks scale -n k8s-cluster -g container-rg -c 3
```

Error:
```
Deployment failed. Correlation ID: 60a3f3b6-2ecc-4532-a334-782f06bbc69d. 
Timeout while polling for control plane provisioning status
```

**Comment by sgoings** [comment]
When did you happen to create this cluster?

**Comment by abramz** [comment]
@sgoings, I created the cluster on Dec 3rd around 3PM PST.

**Comment by sgoings** [comment]
Hey @abramz I took a look at all the logs and events from when you first created the cluster and then had some scaling failures. I've got a little 3-step challenge for you, if you choose to accept it, as I'm honing in on how your cluster might have gotten into its current state:

1. Try a scale down again. Success/Fail?
2. Try an upgrade to 1.8.2. Success/Fail?
3. Try a scale down again. Success/Fail?

My hunch at this point is that 1 will fail, but 2 will succeed and therefore set you up for a successful 3. But I'll await the actual results!

**Comment by abramz** [comment]
Thanks @sgoings 

Unexpected, but scaling down actually succeeded today. I went ahead and upgraded the cluster anyways and scaled from 3 to 2 then 2 back to 3 nodes just to see what happens and that succeeded as well.

Seems like it may have just been a temporary issue.
