### ISSUE TITLE
 Unable to connect to tiller on AKS from within cluster. Clone of #459

### ISSUE THREAD

**Issue by thiDucTran** [Azure/AKS#730]
**What happened**: Still a noob in AKS but I think this issue is clone of #459
`$ helm version`
`Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}`
`Error: forwarding ports: error upgrading connection: Upgrade request required`

**What you expected to happen**: Once Tiller is installed, running `helm version` should show you both the client and server version.

Trying to follow this guide https://docs.microsoft.com/en-us/azure/aks/ingress-tls and getting this error:

`helm install stable/nginx-ingress --namespace kube-system --set controller.replicaCount=2 --set rbac.create=false`

`Error: forwarding ports: error upgrading connection: Upgrade request required `

Running `kubectl -n kube-system port-forward tiller-deploy-7f4974b9c8-z7xc7 44134:44134` also produce error : `error: error upgrading connection: Upgrade request required`

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4", GitCommit:"bf9a868e8ea3d3a8fa53cbb22f566771b3f8068b", GitTreeState:"clean", BuildDate:"2018-10-25T19:06:30Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
`
- Size of cluster (how many worker nodes are in the cluster?) 3

- Result of `kubectl get deployments --namespace kube-system`:

>NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
heapster               1         1         1            1           19h
kube-dns-v20           2         2         2            2           19h
kubernetes-dashboard   1         1         1            1           19h
metrics-server         1         1         1            1           19h
omsagent-rs            1         1         1            1           19h
tiller-deploy          1         1         1            1           37m
tunnelfront            1         1         1            1           19h

- Result of `kubectl get pods --namespace kube-system`

>NAME                                    READY   STATUS    RESTARTS   AGE
azure-cni-networkmonitor-dgt96          1/1     Running   0          18h
azure-cni-networkmonitor-hrvz5          1/1     Running   0          18h
azure-cni-networkmonitor-x279c          1/1     Running   0          18h
heapster-7b74498c4b-bknf2               2/2     Running   0          18h
kube-dns-v20-54f74f4458-77h6x           3/3     Running   0          19h
kube-dns-v20-54f74f4458-xp6ht           3/3     Running   0          19h
kube-proxy-d44cc                        1/1     Running   0          18h
kube-proxy-dsnsn                        1/1     Running   0          18h
kube-proxy-j6kjb                        1/1     Running   0          18h
kube-svc-redirect-56mxz                 2/2     Running   0          18h
kube-svc-redirect-bmdkb                 2/2     Running   0          18h
kube-svc-redirect-kq7tn                 2/2     Running   0          18h
kubernetes-dashboard-5845b66748-bjxcx   1/1     Running   1          19h
metrics-server-84f475c77b-xhlk4         1/1     Running   1          19h
omsagent-4w7k9                          1/1     Running   1          18h
omsagent-cstbb                          1/1     Running   1          18h
omsagent-pqqkd                          1/1     Running   1          18h
omsagent-rs-769cdc4878-l8dss            1/1     Running   1          19h
tiller-deploy-7f4974b9c8-z7xc7          1/1     Running   0          37m
tunnelfront-c4d5dd566-z48pf             1/1     Running   0          19h`

**Comment by Turil** [comment]
Why did you close this issue? What was the resolution? I am having the same problem on a fresh AKS cluster.

**Comment by thiDucTran** [comment]
> @thiDucTran - Why did you close this issue? What was the resolution? I am having the same problem on a fresh AKS cluster.

i recreated my cluster with RBAC enabled
