### ISSUE TITLE
Unable to create Rolebinding through REST API call

### ISSUE THREAD

**Issue by ajinkya599** [Azure/AKS#735]
**What happened**:
Unable to create rolebinding using REST API call when using clusterAdmin credentials. The same works when using kubectl command

**What you expected to happen**:
To be able to create the RoleBinding using the REST API as I am using the clusterAdmin credentials.
Further, I don't understand why the same call works fine when done using kubectl command.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an AKS cluster
2. Run `az aks get-credentials` with `--admin` to fetch the credentials. After this I was able to successfully run kubectl commands.
3. Created namespace n1 using kubectl.
4. Created a service account in namespace n1 using kubectl command.
5. Created roleBinding to assign cluster-admin role to SA on default namespace using the following command - 
`kubectl create rolebinding aj-rb-1 --clusterrole=cluster-admin --serviceaccount=n1:aj-sa-n1 --namespace=default`.
This worked fine
6. But when I tried creating the roleBinding using REST API, it resulted in the error - 
`rolebindings.rbac.authorization.k8s.io is forbidden: User "clusterAdmin" cannot create rolebindings.rbac.authorization.k8s.io in the namespace "default"`

REST API call-
```
POST https://ajdns-xxxxxxxx.hcp.centralus.azmk8s.io:443/apis/rbac.authorization.k8s.io/v1/namespaces/default/rolebindings


REQUEST HEADERS:

Accept:application/json, */*
Content-Type:application/json
Authorization:Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


REQUEST BODY:

{
    "kind": "RoleBinding",
    "apiVersion": "rbac.authorization.k8s.io/v1",
    "metadata": {
        "name": "aj-rb-2",
        "creationTimestamp": null
    },
    "subjects": [
        {
            "kind": "ServiceAccount",
            "name": "aj-sa-n1",
            "namespace": "n1"
        }
    ],
    "roleRef": {
        "apiGroup": "rbac.authorization.k8s.io",
        "kind": "ClusterRole",
        "name": "cluster-admin"
    }
}
```

REST API RESPONSE -

```
{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "rolebindings.rbac.authorization.k8s.io is forbidden: User \"clusterAdmin\" cannot create rolebindings.rbac.authorization.k8s.io in the namespace \"default\"",
    "reason": "Forbidden",
    "details": {
        "group": "rbac.authorization.k8s.io",
        "kind": "rolebindings"
    },
    "code": 403
}
```

**Anything else we need to know?**:
I created the API call using the output of `kubectl create rolebinding aj-rb-1 --clusterrole=cluster-admin --serviceaccount=n1:aj-sa-n1 --namespace=default --v=8`

`kubectl auth can-i create rolebinding` returns yes while calling the same API using Postman returns `allowed: false`

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4", GitCommit:"bf9a868e8ea3d3a8fa53cbb22f566771b3f8068b", GitTreeState:"clean", BuildDate:"2018-10-25T19:06:30Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by ajinkya599** [comment]
**Update**: I noticed that this is happening when RBAC is enabled. All the REST API calls are failing when the clusterAdmin token is used.
While for a cluster on which RBAC is disabled I am able to perform all the operations using the clusterAdmin token.

Also, the kubectl commands start giving the same error (User "clusterAdmin" cannot create rolebindings.rbac.authorization.k8s.io in the namespace "default") when I remove the client-certificate-data and client-key-data from the .kube/config file.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
