### ISSUE TITLE
Failed to pull image "foo.azurecr.io/image:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://foo.azurecr.io/v2/: EOF

### ISSUE THREAD

**Issue by deepforu47** [Azure/AKS#736]
**What happened**:
AKS not able to pull images from ACR in other subscription despite of all the permissions.
**What you expected to happen**:
It should pull the images and start pod/container successfully.
**How to reproduce it (as minimally and precisely as possible)**:
ACR and AKS in different subscription.

**Environment**:
- Kubernetes version :  v1.10.8
- Size of cluster : 1

**Comment by andyzhangx** [comment]
Have you assigned ACR access to the Service Principle in AKS?
 - Use following command to check whether the target ACR is listed
```
az login --service-principal -u <aadClientId> -p <aadClientSecret> -t <tenantId>
az acr list
```
details:
https://github.com/andyzhangx/demo/blob/master/issues/acr-issues.md#pull-image-error-after-granting-sp-access-to-azure-container-registry

**Comment by ac-astuartkregor** [comment]
@deepforu47 We found that because the registry and cluster were in different subscriptions, we weren't able to give the cluster Reader access to the registry and instead had to create a service principal in the registry's subscription and create a corresponding image pull secret in kubernetes.

I would expect there is a way to allow cross-subscription access but I believe the problem you're running into is the subscriptions being separated.

**Comment by andyzhangx** [comment]
@ac-astuartkregor I enabled the k8s feature of `pull image failed from a cross-subscription Azure Container Registry by service principal`. If you could grant your k8s cluster sp reader access to the resource group where your ACR is, it should work. You could find details here:
https://github.com/andyzhangx/demo/blob/master/issues/acr-issues.md#pull-image-error-after-granting-sp-access-to-azure-container-registry
It lists the supported k8s versions for cross-subs pull image.

**Comment by ac-astuartkregor** [comment]
@andyzhangx That's good to know, thanks. Since we were at an early stage when we found the problem, we solved the issue by putting the cluster and registry in the same subscription.

**Comment by deepforu47** [comment]
Hello Guys,
just to update, actually it was on network level. We have typo in network rules between two subscription which caused this.Thanks all for your prompt response. Appreciate!!

**Comment by andyzhangx** [comment]
Good to know, that proves that my `pull image from cross-subs acr` feature works well.

**Comment by Jyoti492** [comment]
@andyzhangx  Does the solution you mention only work if you grant access to the registry's resource group and not just the registry itself?

**Comment by Jyoti492** [comment]
> > @andyzhangx Does the solution you mention only work if you grant access to the registry's resource group and not just the registry itself?
> 
> @Jyoti492 I tried that before, access to the registry's resource group works while grant access to the registry itself not works, not sure why...

thats strange because our resource group level access is handled by other team... do we need k8s secret as well to pull cross subscription ? because only some of our images fail with this error but others are getting pulled successfully without any k8s secret and RG level access

**Comment by Jyoti492** [comment]
@andyzhangx I even added the Reader access to the RG where the ACR is still it fails with same issue

**Comment by andyzhangx** [comment]
> @andyzhangx I even added the Reader access to the RG where the ACR is still it fails with same issue

@Jyoti492 what's your k8s version? are you using managed identity or service principal?
