### ISSUE TITLE
az aks create doesn't honor service CIDR nor DNS service IP

### ISSUE THREAD

**Issue by gvilarino** [Azure/AKS#737]
**What happened**:

I ran `az aks create` with custom service CIDR (10.130.0.0/16) and DNS service IP (10.130.0.10) but it was created with:

```
...
"dnsServiceIp": "10.0.0.10",
...
"serviceCidr": "10.0.0.0/16"
...
```

**What you expected to happen**:

That the CLI would actually honor my settings.

**How to reproduce it (as minimally and precisely as possible)**:

```
az group create --name some-testing-rg --location eastus

az aks create --name realtime-aks \
  --dns-service-ip 10.130.0.10 \
  --location eastus \
  --node-vm-size Standard_B2s \
  --resource-group some-testing-rg \
  --service-cidr 10.130.0.0/16
```

**Anything else we need to know?**:

[Official documentation](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create) says this works

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
HTTP microservices
- Others:
az CLI version: `azure-cli (2.0.50)`

**Comment by gvilarino** [comment]
It also doesn't work if I try to create through portal and specify the same CIDR and IPs

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
