### ISSUE TITLE
Docker version deployed?

### ISSUE THREAD

**Issue by flamingboo** [Azure/AKS#739]
I have just deployed a cluster with version 1.11.5 and the docker version shown now is 3.0.1!
is this the moby runtime version??

]# kubectl get nodes -o wide
NAME                        STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-tfnodepool-50829582-0   Ready     agent     37m       v1.11.5   <none>        Ubuntu 16.04.5 LTS   4.15.0-1032-azure   docker://3.0.1
aks-tfnodepool-50829582-1   Ready     agent     37m       v1.11.5   <none>        Ubuntu 16.04.5 LTS   4.15.0-1030-azure   docker://3.0.1
aks-tfnodepool-50829582-2   Ready     agent     37m       v1.11.5   <none>        Ubuntu 16.04.5 LTS   4.15.0-1030-azure   docker://3.0.1

To which version (17.0X, 18.0X) that 3.0.1 corresponds?
Thx

-->

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by angrox** [comment]
Upgrading a Cluster from 1.11.4 to 1.11.5 does not change the docker version or the entire runtime - it is still 1.13.1

**Comment by jnoller** [comment]
@flamingboo You are correct, the new docker runtime version being shown (I assume you're using ACS/AKS-Engine and not AKS) is for Moby which we are working on rolling out first via ACS-Engine and then to AKS. This will resolve a number of long standing issues pertaining to ACS-Engine and AKS tied to the older Docker version.

**Comment by derekperkins** [comment]
> We have now enabled Moby for all users. It is roughly in line with Docker Engine 18.06, though you will see it listed as version 3.0.1, an internal Azure build number. 
It took me about 30 minutes to track down the answer to your question here
https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/34917076-increase-kubernetes-node-docker-version-to-17-05-x

@jnoller it would be very helpful to have these Azure internal versions mapped to public releases.

**Comment by jnoller** [comment]
Yep it’s already under way. The problem with moby is that they do not have actual releases and versions - there is no 1:1 to docker CE so any direct comparison isn’t great
