### ISSUE TITLE
connection timed out error Trying to execute kubectl log or kubectl exec -it on pods

### ISSUE THREAD

**Issue by ramakrishnateja** [Azure/AKS#74]
Set up a AKS cluster
and check if everything looks fine
kubectl cluster-info

![image](https://user-images.githubusercontent.com/6781607/33898978-0e2805aa-df38-11e7-980d-ba0f567f8264.png)

Now try to create a simple pod 

kubectl run kubia --image=luksa/kubia --port=8080 --generator=run/v1

now try checking if the pod is created by running  kubectl get pods
![image](https://user-images.githubusercontent.com/6781607/33899054-42e2f1ba-df38-11e7-9570-b529af28ae44.png)

Pod is running. 

now if we try to run kubectl  logs <PodName> it throws and exception after timing out.
![image](https://user-images.githubusercontent.com/6781607/33899090-6597ebde-df38-11e7-8996-a4658fcf46aa.png)

Same issue when trying to run kubectl exec -it <PodName> sh on a pod. but describe works just fine. I am seeing the issue only for the past few days and it was working previously.

**Comment by debben** [comment]
What is the status of the pods running in kube-system? I experienced the same issue while trying to debug #56. Once the kube-svc-redirect pod started working, I was able to get logs again.

**Comment by ramakrishnateja** [comment]
Hi @debben  I set up a new cluster today and tried running the same steps and I am able to access the logs. If i face the same issue again I would try to check the status of the pods running in kube-system namespace  and see if kube-svc-redirect pod is running or having an issue.  This is the status of the pods currently and I don't see the issue any more

![image](https://user-images.githubusercontent.com/6781607/33955329-240bc8a8-e009-11e7-9676-db1391794a09.png)

**Comment by gonarys** [comment]
I had this problem and it turned out that I had a resource that used the subnet dedicated to AKS. you have to check this and if so, remove the resource.
