### ISSUE TITLE
Error in Container Insight

### ISSUE THREAD

**Issue by mapoitras** [Azure/AKS#741]
I turn on Logging however when I try to look at logs, I get the error:

Kube API Response
pods "spring-music-7cbf545857-c6fcl" is forbidden: User "clusterUser" cannot get pods/log in the namespace "default"

I assume this is related to RBAC however I can't find any information as to what I need to do to fix this.  There is no documentation.

**Comment by strategywise** [comment]
I just ran into this as well with our cluster. Can't see where to grant this user access to see the logs.

**Comment by Shuanglu** [comment]
> I just ran into this as well with our cluster. Can't see where to grant this user access to see the logs.

pls try below.

https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-live-logs#kubernetes-rbac-authorization

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
