### ISSUE TITLE
pods and nodes unable to access apiserver

### ISSUE THREAD

**Issue by rubbish** [Azure/AKS#742]
**What happened**:

On one of our AKS clusters, we see an issue where pods and our nodes are unable to connect to the kubernetes apiserver, however, I'm able to access it outside of the cluster and on a VM in the same Azure vnet. The apiserver url it is using is the Azure public apiserver url: https://my-cluster.hcp.centralus.azmk8s.io:443. That url is what is being given to all pods as the `KUBERNETES_SERVICE_HOST` env variable. When using the `kubernetes.default.svc.cluster.local` internal DNS hostname, the nginx proxy times out.

When I kill all `kube-svc-redirect` pods and they get recreated, then all pods can connect.

The odd part is that this happens a little under every 3 hours. I have a blackbox probe in prometheus checking every minute.

In our other AKS clusters, we don't see this happening and the same workloads are deployed on them.

**What you expected to happen**:

No connectivity lost to the apiserver.

**How to reproduce it (as minimally and precisely as possible)**:

Not quite sure.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.5
- Size of cluster (how many worker nodes are in the cluster?): 9
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): microservices and ELK.
- Others:

**Comment by mpluhar** [comment]
How long has your cluster been up for? 

Have a look at your POD deployments. Our clusters have actually environment variables for the API server, which bypasses the kube-svc-redirect service.

**Comment by seanmck** [comment]
We're planning some changes that will result in the removal of kube-svc-redirect, so I'm going to close this. If you need assistance for your specific environment, please file a support ticket.

**Comment by gralfca** [comment]
How are we supposed to access the api server from the pods if the standard urls are not available ?
