### ISSUE TITLE
Significant Connectivity Drops between AKS clusters and an Azure Database for MySQL

### ISSUE THREAD

**Issue by damienwebdev** [Azure/AKS#743]
**Region**
South Central US

**What happened**:
I have a cluster with 8 FSv2 VMs in it. Each of these has a pod that connects:

1. Via the AKS cluster VNET  
2. Over SSL 

to an Azure Database for MySQL instance. Intermittently, I will get significant amounts of dropped connections between my AKS cluster and the Azure Database for MySQL instance. These come in distinct "peaks" of network connection issues where all VMs in a cluster are unable to access the underlying Azure Database for MySQL instance.

**What you expected to happen**:
I expected to have my cluster successfully connect to the Azure Database for MySQL instance within the bounds of the Azure SLA (99.99%)

**How to reproduce it (as minimally and precisely as possible)**:
1. Make an `AKS` cluster in South Central
2. Try and connect to an `Azure Database for MySQL` instance in South Central
3. Do this consistently for a month
4. See that there are certain times where connections drop for 2-5 minutes multiple times over the course of some days. 

**Anything else we need to know?**:
I'm aware of the constraints posed by [High Availability in Azure Database for MySQL](https://docs.microsoft.com/en-us/azure/mysql/concepts-high-availability). That is not the issue here. 

Here's a graph of failed connections to the instance over the past month.
<img width="867" alt="screen shot 2018-12-04 at 6 52 30 pm" src="https://user-images.githubusercontent.com/9029654/49481151-91ce4f80-f7f7-11e8-9d26-b58d9576e8ba.png">

I have another custom built NON-AKS cluster in South Central that doesn't use containers, but just raw Ubuntu 16.04 VMs. This cluster's "failed connections" graph looks like:

<img width="882" alt="screen shot 2018-12-04 at 7 08 40 pm" src="https://user-images.githubusercontent.com/9029654/49481256-0e612e00-f7f8-11e8-907b-ba77dbfb5888.png">
 

**Environment**:
- Kubernetes version (use `kubectl version`): **v1.10.4**
- Size of cluster (how many worker nodes are in the cluster?) **8 FSv2 VMs**
- General description of workloads in the cluster: `php7.2-apache` web servers

cc: @jnoller

**Comment by jnoller** [comment]
@damienwebdev I'm working on line of sight for investigation today, I believe multiple users are seeing issues like this and I am collecting more information.

**Comment by damienwebdev** [comment]
@juan-lee 

Is it possible to SSH onto the VMs in an AKS cluster? 

Additionally, I'd imagine I would have to re-do this each time I scale up/down a new node in the cluster. Currently, the nodes I have in my cluster are auto-scaled via the node-autoscaler, so making sure that each node maintains these settings seems infeasible.

**Comment by juan-lee** [comment]
> @juan-lee
> 
> Is it possible to SSH onto the VMs in an AKS cluster?
> 
> Additionally, I'd imagine I would have to re-do this each time I scale up/down a new node in the cluster. Currently, the nodes I have in my cluster are auto-scaled via the node-autoscaler, so making sure that each node maintains these settings seems infeasible.

Here are instructions for SSH https://docs.microsoft.com/en-us/azure/aks/ssh

Yes, you would have to do that, but we can make these settings default if you see success.

**Comment by juan-lee** [comment]
@damienwebdev any update on your issue?

**Comment by damienwebdev** [comment]
@juan-lee I applied these settings to a few of the VMs in my node pool. I'll keep this issue updated over the next few days as I monitor connection failures across the node pool.

Currently, I'm running against 4 VMs:

* 2 with the:
```
sudo bash -c "echo 120 > /proc/sys/net/ipv4/tcp_keepalive_time"
sudo bash -c "echo 30 > /proc/sys/net/ipv4/tcp_keepalive_intvl"
sudo bash -c "echo 8 > /proc/sys/net/ipv4/tcp_keepalive_probes"
```

* 2 without

**Comment by juan-lee** [comment]
@damienwebdev FYI - that won't be persistent. If the vm reboots the settings will reset. You'll want to add the following to /etc/sysct.conf

net.ipv4.tcp_keepalive_time=120
net.ipv4.tcp_keepalive_intvl=30
net.ipv4.tcp_keepalive_probes=8

**Comment by damienwebdev** [comment]
@juan-lee just to make sure, you meant `/etc/sysctl.conf` right?

**Comment by juan-lee** [comment]
> @juan-lee just to make sure, you meant `/etc/sysctl.conf` right?

ugh, typo. Yes. Thanks for pointing that out.

**Comment by damienwebdev** [comment]
@juan-lee After reviewing logs of the past 24 hours, the changes don't appear to have made a difference. Connections aren't persistent (they close after each request), but I'm still seeing the failed connections in my metrics and logs.

And, I'm not sure if this is what you anticipated, but the nodes in the AKS cluster with the changes:

```
net.ipv4.tcp_keepalive_time=120
net.ipv4.tcp_keepalive_intvl=30
net.ipv4.tcp_keepalive_probes=8
```

experienced about 4x more failed connections than the others

**Comment by juan-lee** [comment]
> @juan-lee Gonna chime in here with a little bit more info. After reviewing in aggregate over the past three days, it appears that it's realistically only about **2x more errors** with the changes, than those from stock nodes.

@damienwebdev sorry for the delay, I've also seen the same w/ those settings in my recent testing. Is it possible to capture a tcpdump that I can analyze or even a minimal repro setup?

**Comment by damienwebdev** [comment]
@juan-lee closing. This ended up being a result of https://github.com/Azure/acs-engine/issues/3503. Since upgrading to v1.12.5, this issue has disappeared. I'll keep monitoring, but mark this as closed unless something else changes.

@jnoller thanks for your help as well!

**Comment by erewok** [comment]
We have an AKS cluster on 1.12.6 and we started seeing this issue this morning. I reached out to support for help, but also wanted to comment here in case others are seeing this problem as well.

**Comment by juan-lee** [comment]
@erewok you are seeing a missing InternalIP for your node? @feiskyer shouldn't the fix for missing InternalIP be in 1.12.6?

**Comment by erewok** [comment]
No, I'm not see a missing InternalIP for any of my nodes. 

I *am seeing* consistent connectivity issues from one deployment (6 pods total) in AKS to a hosted Postgresql database via service endpoints. No other application connects to this Postgresql server and the application in question has been able to connect successively for the past few weeks. Starting this morning, for some reason, connections to the database have been getting dropped throughout the day. This is in line with the original issue at the top, so I figured it would be relevant to post it here: googling the issue brings this up. 

In addition, I reviewed this morning and came to the conclusion that the database itself is under-utilized. This was confirmed by Azure support, who also stated that no errors are present in the logs for the database. 

It seems to be purely an issue with AKS and/or Azure networking.

**Comment by feiskyer** [comment]
> @feiskyer shouldn't the fix for missing InternalIP be in 1.12.6?

The node IP issue is fixed since v1.12.1 (v1.12.3 or later is preferred because of other fixes).

**Comment by feiskyer** [comment]
> It seems to be purely an issue with AKS and/or Azure networking.

@erewok Have you tried to analyze where are the packets dropped?

**Comment by erewok** [comment]
@feiskyer, I haven't. Unfortunately, I wouldn't know how to begin.

**Comment by erewok** [comment]
Follow-up: according to our support rep, this was an issue with our database which somehow spontaneously changed logging settings (we have a team of 1 doing infra and he was actually out when the db settings changed, so nobody has any idea about this...). Once the logging settings were set back to default, we stopped seeing the dropped connections. It does not appear to be an issue with AKS, as a result.
