### ISSUE TITLE
Docker Socket permission change after upgrade to 1.11.5

### ISSUE THREAD

**Issue by mpluhar** [Azure/AKS#744]
**What happened**:

After upgrading the cluster from 1.11.3 to 1.11.5 we cannot longer access the docker.socket we expose to pods running in the cluster. Error message is "Permission denied"

**What you expected to happen**:

Socket  can we used as before the upgrade

**How to reproduce it (as minimally and precisely as possible)**:

Upgrade to 1.11.5 and run non privileged pod that has access to the docker socket

**Anything else we need to know?**:

It also appears that docker has been replaced with Moby in this version of AKS. We assume that the permissions have been changed on the socket or group membership has changed.

**Environment**:
- Kubernetes version (use `kubectl version`):

mpluhar@sputnik:~/nn/yy/src/tcd-temp/secret/common/wildcard$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)

4 nodes 

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

Jenkins, .NET Core

- Others:

**Comment by mpluhar** [comment]
So when using docker the gid of the docker group is 999 (AKS version 1.11.3). When using moby, the gid of the docker group is 117.

**Comment by brendandburns** [comment]
@jackfrancis 

Does docker group always get a fixed GID? I'd expect it to be semi-random....

**Comment by jackfrancis** [comment]
@cpuguy83 for any words of wisdom on docker.socket permission denied post-moby introduction

@brendandburns did an audit of the code and I don't see any group ID or user ID enforcement for docker, I'd deduce it arrives via `apt-get install moby-engine`. I'd also expect it to be random, though possibly the repo definition has a say in that? (@cpuguy83 may also have a remark on that)

**Comment by mpluhar** [comment]
I had a look at  the debian postinstall script and it does "addgroup --system docker". So random as well.

**Comment by khenidak** [comment]
i tested another machine. Docker group has a `gid` of `999`. I could not confirm that this is the enforced on all installs. Depending on the `gid` of a system component is not be the best approach. 

I strongly recommend adding a well known user to docker group on VMs where you expect your pod to run and use `runAs` security context to run your pods with.

Meanwhile I will try to confirm if `999` is fixed id.

**Comment by cpuguy83** [comment]
Also as far as security here, there is no added security layer by running as non-root in this case because you already have access to the docker socket which is privileged.

However, I would recommend not bind-mounting the host docker socket and instead actually run your own docker instance if you really want Docker.

**Comment by cpuguy83** [comment]
The id is just generated by groupadd (or was it addgroup... one starts low and hoes high, the other starts high and goes low)... but this is only for new installs.

For upgrades, containers which are bind mounting the docker socket must be restarted because the bind mount is broken when docker(or moby) restarts. This is necessary for dockerd to be able to listen on the Unix socket again.

Note that bind mounts are bound to an inode, if the inode changed then the bind is effectively broken.

**Comment by jnoller** [comment]
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
