### ISSUE TITLE
Unable to create virtual node in public preview

### ISSUE THREAD

**Issue by gabrielmcf** [Azure/AKS#746]
**What happened**:

Tried to create virtual node after public preview release. Used this link: https://docs.microsoft.com/pt-br/azure/aks/virtual-nodes-cli

I had a cluster created with advanced networking and tried to create the virtual node in the same subnet. The extension was successfully added but the add-on could not be enabled and returned the following error:

```
The behavior of this command has been altered by the following extension: aks-virtual-node
'logAnalyticsWorkspaceResourceID'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/home/gabriel/.azure/cliextensions/aks-virtual-node/azext_aksvirtualnode/commands.py", line 47, in enable_addon_override
    _ensure_container_insights_for_monitoring(cmd, instance.addon_profiles['omsagent'])
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 1838, in _ensure_container_insights_for_monitoring
    workspace_resource_id = addon.config['logAnalyticsWorkspaceResourceID']
KeyError: 'logAnalyticsWorkspaceResourceID' 
```
**What you expected to happen**:

A virtual node to be created

**How to reproduce it (as minimally and precisely as possible)**:

Create an AKS with advanced networking. Try to follow this link https://docs.microsoft.com/pt-br/azure/aks/virtual-nodes-cli jumping direct to the Enable virtual nodes section.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.3
- Size of cluster (how many worker nodes are in the cluster?): 10
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) around 30 workers pods
- Others:

**Comment by samkreter** [comment]
Hey @gabrielmcf, I'm having trouble reproducing this issue. How did you initially create the cluster and what commands / settings did you use? (Azure CLI, Portal, Resource Manager). Also was their any other addons that you added to the cluster such as monitoring?

**Comment by samkreter** [comment]
@gabrielmcf I'm still having trouble reproducing this issue. Can you verify that you are using version 0.2.0 of the virtual node extension by running 
```sh
     az extension list
```

the output should look like

```sh
[
  {
    "extensionType": "whl",
    "name": "aks-virtual-node",
    "version": "0.2.0"
  }
]
```

**Comment by samkreter** [comment]
Also, could you provide the resource Id of your AKS cluster so I can see the configuration it is using.

**Comment by AceHack** [comment]
Just followed same guide, worked great!

**Comment by gabrielmcf** [comment]
@samkreter, thank you for your time! The output looks exactly the same you posted. The aks-virtual-node extension is indeed the 0.2.0 version. Isn't the resource ID kind of sensitive to post in the issue? Do you think it's better to open a ticket?

**Comment by gabrielmcf** [comment]
I've tried using the `--workspace-resource-id` option but it gave me the exact same error.

**Comment by srrengar** [comment]
hi @gabrielmcf this issue is fixed in a newer version of Azure CLI as mentioned here - https://github.com/virtual-kubelet/virtual-kubelet/issues/455#issuecomment-474047367

Can you try updating it and try again? https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

**Comment by srrengar** [comment]
@jnoller can we close this one
