### ISSUE TITLE
Node was not restarted automatically when status NotReady

### ISSUE THREAD

**Issue by tohta** [Azure/AKS#749]
Hi Team.

We have a AKS cluster in production environment, few days ago, one of the cluster node turned into NotReady status and all pods on that node changed their status from Running to Unknown.

However, the node was not restarted nor recovered automatically.
Is this a designed behavior?  (self-healing)

**What happened**:
AKS node was not restarted automatically when it got status `NotReady`

**What you expected to happen**:
AKS node should be restarted automatically without any user operation.

**How to reproduce it (as minimally and precisely as possible)**:
N/A.
We've encountered this problem with reason unknown.

**Anything else we need to know?**:
Any workaround for this issue would be very helpful if this is designed.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.2
- Size of cluster: It was 3 when we encountered this problem, then we added 4 more nodes.
- General description of workloads in the cluster: Web apps written in Java
- Here is the output of `kubectl describe node` (snipped)

```
Conditions:
  Type             Status    LastHeartbeatTime                 LastTransitionTime                Reason                    Message
  ----             ------    -----------------                 ------------------                ------                    -------
  OutOfDisk        Unknown   Fri, 23 Nov 2018 07:52:31 +0900   Fri, 23 Nov 2018 07:53:15 +0900   NodeStatusUnknown         Kubelet stopped posting node status.
  MemoryPressure   Unknown   Fri, 23 Nov 2018 07:52:31 +0900   Fri, 23 Nov 2018 07:53:15 +0900   NodeStatusUnknown         Kubelet stopped posting node status.
  DiskPressure     Unknown   Fri, 23 Nov 2018 07:52:31 +0900   Fri, 23 Nov 2018 07:53:15 +0900   NodeStatusUnknown         Kubelet stopped posting node status.
  PIDPressure      False     Fri, 23 Nov 2018 07:52:31 +0900   Mon, 01 Oct 2018 14:53:16 +0900   KubeletHasSufficientPID   kubelet has sufficient PID available
  Ready            Unknown   Fri, 23 Nov 2018 07:52:31 +0900   Fri, 23 Nov 2018 07:53:15 +0900   NodeStatusUnknown         Kubelet stopped posting node status.
```

Thanks in advance.

**Comment by jnoller** [comment]
Hello @tohta - we can not debug or root-cause specific cluster issues via this (github) channel. Can you please open a support ticket so that our engineers can securely access the cluster logs and identify the root-cause.
