### ISSUE TITLE
Cannot manage eastus clusters: TLS handshake timeout

### ISSUE THREAD

**Issue by frankbuckley** [Azure/AKS#75]
As of today, we cannot connect to two AKS clusters in eastus:

    $ kubectl get pods
    Unable to connect to the server: net/http: TLS handshake timeout

**Comment by sgoings** [comment]
Could you provide your subscription ID?

**Comment by frankbuckley** [comment]
e8a6c806-7813-4cb4-b339-0e27ad9ac3d2

**Comment by frankbuckley** [comment]
Fixed: working again today. Thanks.
