### ISSUE TITLE
az aks browse should allow user to specify listening address

### ISSUE THREAD

**Issue by jfcoz** [Azure/AKS#751]
**What happened**:

`az aks browse` listen on 127.0.0.1:8001. This is useless when using the azure-cli docker image like https://docs.microsoft.com/en-us/cli/azure/run-azure-cli-docker?view=azure-cli-latest

**What you expected to happen**:

Add an option to specify listen address to 0.0.0.0 (or anything else), so the port can be forwarded by Docker like : 
```
docker run -it -p 127.0.0.1:8001:8001 microsoft/azure-cli:latest
```

**Comment by jfcoz** [comment]
Same as https://github.com/Azure/azure-cli/issues/7914

**Comment by jnoller** [comment]
Thanks @jfcoz - Since this is a CLI feature request I will close this issue so we track it on the cli repo directly
