### ISSUE TITLE
 DNS: Intermittent “temporary failure in name resolution” , “connection refused,” “read timeout,” “connection aborted,” and “failed to establish a new connection: try again.”

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#753]
The AKS team is aware of a potential performance issue in kube-dns under load. This can result in intermittent errors that resemble:

 “temporary failure in name resolution” , “connection refused,” “read timeout,” “connection aborted,” and “failed to establish a new connection: try again.”

Resolution for this is a two-part fix:

- Expose the kube-dns metrics required planned to rollout to all regions the week of December 10th
- Enable the kube-dns autoscaler, which will enable the kube-dns component to scale appropriately for customer workloads

The kube-dns metric will be automatically enabled for:

- All new AKS clusters
- Existing clusters that perform and update or upgrade
- Existing cluster that use auto scale or perform a node addition.

It will not impact your cluster’s functionality (or resolve the issue)

In January 2019 we will roll out the kube-dns autoscaler to all clusters and regions which will resolve the intermittent DNS errors related to kube-dns performance.

**Comment by aadlani** [comment]
This is exactly what we are facing for a few weeks now. Is there anything we can do to mitigate the disruption in the meantime?

**Comment by rubenclopez** [comment]
Any updates on this topic? I just finished spinning up a new AKS cluster in uswest and I'm having the same issue. My hope was to spin up a production environment as well, but I do not feel comfortable using AKS if this issue persists or there is no solution.

Please advise.

**Comment by jnoller** [comment]
@rubenclopez  the auto scaler is in production in all regions, please open an Azure Technical Support ticket so our engineers can jump in and diagnose. I can not ask for your subscription data here on github as it would expose sensitive data.
