### ISSUE TITLE
kubectl: Why I cannot see on which node is a specific pod deployed?

### ISSUE THREAD

**Issue by Aracki** [Azure/AKS#755]
`kubectl get pods -o wide` for all the pods deployed I am getting: `NOMINATED NODE: <none>`. <br>

AFAIK on Azure Portal there is no way to inspect any K8s components.
The only way I succeed to get nodes info is through Kubernetes Dashboard.

Is there a way to get this info without Dashboard?

**Environment**:
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:38Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- 3 worker nodes

**Comment by doug-fish** [comment]
Kubectl will let you do this. Try
kubectl get pods --output=custom-columns=Name:.metadata.name,NodeName:.spec.nodeName  
kubectl get pods -o json
kubectl describe pods
kubectl get pods --help # will give a pretty good description of various command line options
