### ISSUE TITLE
Azure aks autoscaler - node labeling

### ISSUE THREAD

**Issue by gonarys** [Azure/AKS#758]
I have a set of specific worker nodes to scale and I have corresponding node selector on azure.

I get

I1213 15:19:47.330052       1 scale_up.go:59] Pod dev-xxxxxx/xxxxxxx-699d6c7c69-wsmqh is unschedulable
I1213 15:19:47.633071       1 scale_up.go:152] Scale-up predicate failed: GeneralPredicates predicate mismatch, cannot put dev-xxxx/xxxxx-deployment-7b7ff7cfd8-2nlrc on template-node-for-agentpool-5453182444030819628, reason: node(s) didn't match node selector

I'm not sure what should I do to configure autoscaler to put labels on the nodes (azure aks autoscale). How I do it?

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
