### ISSUE TITLE
kube-dns IP collision

### ISSUE THREAD

**Issue by moomzni** [Azure/AKS#762]
**What happened**: When deploying a new cluster Heapster asserted the IP address that was specified as our 'dnsServiceIP' and rendered the cluster inoperable as the kube-dns service was never started.

**What you expected to happen**: The kube-dns service IP is reserved to prevent possible collisions from occurring.

**How to reproduce it (as minimally and precisely as possible)**: At the moment we have experienced the issue twice in testing by deleting and re-creating clusters.  I would expect it would be easier to simulate the collision on a smaller subnet range  .

**Anything else we need to know?**: We are running AKS with advanced networking and the ip space for the service range was a /24.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.5
- Size of cluster (how many worker nodes are in the cluster?): 2 Node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): At this point no services had been deployed
- Others: Deployed via ARM template

**Comment by jnoller** [comment]
Last month we shipped mandatory pre-flight checks to ensure no DNS IP conflicts. Marking Fixed.
