### ISSUE TITLE
After upgrade to AKS 1.11.5 container runtime still on 1.13.1

### ISSUE THREAD

**Issue by borstibacon** [Azure/AKS#763]
**What happened**:
After upgrading clusters from 1.11.2 or 1.11.3 to 1.11.5 container runtime is still 1.13.1.
**What you expected to happen**:
Updated container runtime to 3.0.1.

**Anything else we need to know?**:
In some clusters the nodes are still running docker 1.13.1 after upgrading the cluster to 1.11.5. The clusters were on K8s verions 1.11.2 and 1.11.3.
In a lot of other cluster there is running the current version 3.0.1 after upgrading to 1.11.5.

**Environment**: AKS
- Kubernetes version (use `kubectl version`): 1.11.5
- Size of cluster (how many worker nodes are in the cluster?) between 3 and 5 nodes per cluster

- Others:
Is there any option central way to update the container-runtime on these nodes? 
Login to every node is a big effort i want to avoid. 

Thanks!

BR, 

Borsti

**Comment by seanmck** [comment]
Are these GPU-based VMs?

**Comment by borstibacon** [comment]
@seanmck 

No, normal D and E series.

**Comment by seanmck** [comment]
And all of these clusters have been upgraded in the last couple of weeks?

**Comment by borstibacon** [comment]
@seanmck 
Sorry for late response.

Yes, all these clusters are upgraded in the week before ive startet the thread.

**Comment by borstibacon** [comment]
Today I´ve tried some steps:

-upgrade cluster again
-restart nodes to get the newest kernel version
-upgrading again
 
didnt solved the problem.

Scaling down and up changed the kernel version again and the container-runtime to the newest version.
But not to the "first" node, which still run the old docker version.

Is there maybe a way to force a scaling just for this last node?

**Comment by seanmck** [comment]
@jackfrancis any ideas on this?

**Comment by jackfrancis** [comment]
I cannot repro this behavior on aks-engine:

```
Cluster create on old version:

azureuser@k8s-agentpool1-15264207-0:~$ grep 'azure-vnet-ipam version' /var/log/azure-vnet-ipam.log 
2019/01/11 21:22:30 [cni-ipam] Plugin azure-vnet-ipam version v1.0.7.
2019/01/11 21:22:31 [cni-ipam] Plugin azure-vnet-ipam version v1.0.7.
2019/01/11 21:22:31 [cni-ipam] Plugin azure-vnet-ipam version v1.0.7.
2019/01/11 21:22:31 [cni-ipam] Plugin azure-vnet-ipam version v1.0.7.
2019/01/11 21:22:31 [cni-ipam] Plugin azure-vnet-ipam version v1.0.7.
2019/01/11 21:23:41 [cni-ipam] Plugin azure-vnet-ipam version v1.0.7.
2019/01/11 21:23:42 [cni-ipam] Plugin azure-vnet-ipam version v1.0.7.

$ kubectl get nodes -o wide
NAME                        STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
k8s-agentpool1-15264207-0   Ready     agent     21m       v1.8.15   <none>        Ubuntu 16.04.4 LTS   4.15.0-1013-azure   docker://1.13.1
k8s-agentpool1-15264207-1   Ready     agent     16m       v1.8.15   <none>        Ubuntu 16.04.4 LTS   4.15.0-1013-azure   docker://1.13.1
k8s-master-15264207-0       Ready     master    22m       v1.8.15   <none>        Ubuntu 16.04.4 LTS   4.15.0-1013-azure   docker://1.13.1

After upgrade to modern version:

azureuser@k8s-agentpool1-15264207-2:~$ grep 'azure-vnet-ipam version' /var/log/azure-vnet-ipam.log
2019/01/11 21:57:19 [cni-ipam] Plugin azure-vnet-ipam version v1.0.15.
2019/01/11 21:57:25 [cni-ipam] Plugin azure-vnet-ipam version v1.0.15.
2019/01/11 21:57:26 [cni-ipam] Plugin azure-vnet-ipam version v1.0.15.
2019/01/11 21:57:26 [cni-ipam] Plugin azure-vnet-ipam version v1.0.15.

$ kubectl get nodes -o wide
NAME                        STATUS                     ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
k8s-agentpool1-15264207-0   Ready                      agent     23s       v1.9.11   <none>        Ubuntu 16.04.5 LTS   4.15.0-1036-azure   docker://3.0.1
k8s-agentpool1-15264207-1   Ready,SchedulingDisabled   agent     37m       v1.8.15   <none>        Ubuntu 16.04.4 LTS   4.15.0-1013-azure   docker://1.13.1
k8s-agentpool1-15264207-2   Ready                      agent     8m        v1.9.11   <none>        Ubuntu 16.04.5 LTS   4.15.0-1036-azure   docker://3.0.1
k8s-master-15264207-0       Ready                      master    43m       v1.9.11   <none>        Ubuntu 16.04.5 LTS   4.15.0-1036-azure   docker://3.0.1
```

**Comment by borstibacon** [comment]
After upgrading to a newer AKS version, the nodes where patched to moby container runtime.
