### ISSUE TITLE
Container log messages containing backslash characters are corrupted (by OMS Agent?)

### ISSUE THREAD

**Issue by DaveAurionix** [Azure/AKS#767]
**What happened**:
Log messages containing backslash characters written to stdout and stderr from Docker containers on AKS seem to be corrupted when retrieving them from the ContainerLogs table in Container Insights.  Specifically, a sequence of `\"` is replaced with simply `"`.  This is creating unparsable JSON logs, such as those from ModSecurity in NGINX on an AKS cluster.

**What you expected to happen**:
Log messages written to stdout and stderr can be retrieved from Log Analytics / Container Insights exactly as they are written, meaning a `\"` sequence can be read back as `\"`.

**How to reproduce it (as minimally and precisely as possible)**:
Write out `" test \""` from any docker container, allow the OMS Agent pod to send it to Container Insights, then query the data back from Log Analytics.  The data will show `test ""` instead.

**Anything else we need to know?**:
It's worth noting that even the parse_json function in Log Analytics cannot parse the log messages on Log Analytics' servers, suggesting that the problem might be occurring before the logs are sent into Log Analytics, rather than when they are read back out.  A guess would be a bug in the OMS Agent.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.4
- Size of cluster (how many worker nodes are in the cluster?) 4
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) .NET Core HTTP microservices, NGINX-Ingress reverse proxy.
- Others:

**Comment by chadccollins** [comment]
I am having exactly this issue. Thank you for reporting it.

**Comment by lukenny** [comment]
+1

**Comment by r-dilip** [comment]
The fix for the issue will be rolled out in our next agent update.

**Comment by DaveAurionix** [comment]
@r-dilip Do you think this issue can be closed now?  The fix has been working perfectly for us for a while now (I didn't realise this was still open to be honest).  Thank you for addressing it.
