### ISSUE TITLE
Websockets with http-application-routing disconnects on dynamic update

### ISSUE THREAD

**Issue by bredr** [Azure/AKS#768]
**What happened**:
Dynamic updates in the ingress controller immediately emptying the socket pool in nginx causing any long running connections, such as websockets to die. In our system the dynamic update check runs frequently, even without changes, it appears to restart nginx killing the connections.

**What you expected to happen**:
 The argument `--sort-backends=true` is required to fix this in the nginx part of the deployment manifest - this blog https://danielfm.me/posts/painless-nginx-ingress.html demonstrates this fix.

**How to reproduce it (as minimally and precisely as possible)**:
Create a websocket service which is connected through an ingress path with the addon ingress controller. Every time a dynamic update runs the websocket will drop.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.5
- Size of cluster (how many worker nodes are in the cluster?) : ~10
- General description of workloads in the cluster: http and grpc microservices
- Others:

[update-addon-http-application-routing-nginx-ingress-controller-deployment.yaml.txt](https://github.com/Azure/AKS/files/2702419/update-addon-http-application-routing-nginx-ingress-controller-deployment.yaml.txt)

**Comment by dstrebel** [comment]
I typically recommend just setting up a Ingress Controller on the cluster and not enabling "http-application-routing", as there's a lot of limitations to it. The goal with HTTP Application ROuting was for users to get setup quickly with Ingress, but not really for production deployments due to the limitations of the configuration.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
