### ISSUE TITLE
[Feature request] Disable the "Scale" tab in the AKS UI when the cluster-autoscaler is installed

### ISSUE THREAD

**Issue by patrickmslatteryvt** [Azure/AKS#769]
**Feature request**: Disable the "Scale" tab in the AKS UI when the cluster-autoscaler is installed

According to the page [Cluster Autoscaler on Azure Kubernetes Service (AKS) - Preview](https://docs.microsoft.com/en-us/azure/aks/autoscaler)
```
When cluster autoscaler is used, avoid manually scaling the number of nodes. The cluster autoscaler may not be able to determine the correct amount of compute resources required and conflict with the number of nodes that you manually define.
```

Can you please disable the "Scale" tab in the AKS UI when the cluster-autoscaler is installed.

**Comment by jluk** [comment]
@patrickmslatteryvt closing as I believe this is addressed, but I have a few flags on my sub so it may not match yours. Closing for now but please re-open if not and I will take a follow-up action.
