### ISSUE TITLE
Error scaling cluster: nodes not added to cluster and lost connectivity to the cluster

### ISSUE THREAD

**Issue by ahaeber** [Azure/AKS#77]
We tried to increase node-count (from 1 to 3) for a cluster using az aks:
`az aks scale -g groupname -n clustername -c 3`
After some time the command finished and we could see in Azure that two new virtual machines had been created. However, the nodes never came up in Kubernetes (we waited approx 1 hour and tried to restart the VMs).

After that scale command it got difficult to control the cluster. Commands like `az aks browse` failed and for some users `kubectl` also failed. A common error message seen is:
> Unable to connect to the server: net/http: TLS handshake timeout

We have found some related issues to this problem without seeing any solutions (except re-creating the cluster):
#75 #14 #26 

One weird detail here is that for some `kubectl` worked but for others it stopped working. We found that the `API server address` for the cluster was changed in Azure after the scaling command. In the initial deployment it was clustername-123abc.hcp.westeurope.azmk8s.io and after the scale command it now shows as clustername-4321def.hcp.westeurope.azmk8s.io. The kubectl problem resolves if we use the previous API server address, but when you use `az aks get-credentials` then you get the new one which does not work.

It seems to be a bug that the API server address changes due to scaling the cluster.

**Comment by neilpeterson** [comment]
I am seeing this same issue.

**Comment by slack** [comment]
@ahaeber could you send the subscription, resource group and cluster names to jason.hansen@microsoft.com Kubernetes endpoints should not change on scale.

As far as repairing a cluster after scale, issuing a `az aks upgrade` with the same `kubernetes-version` re-applies the latest configuration which can cause the api-server to wake up.

**Comment by slack** [comment]
As far as new nodes not registering with Kubernetes, it may be due to an expired service principal.

Double check the service principal password used for the AKS cluster has not expired. I don't think you can get this from the cli, but via the Portal: `Home > App registrations > client_id > Settings > Keys`

![cloudapp annotation 2017-12-20 at 5 38 02 pm png](https://user-images.githubusercontent.com/28873/34236480-9f34c252-e5ac-11e7-8ed1-ed6a983f2679.png)

If it is expired, reset the password to the same value with:
```
az ad sp reset-credentials -n <SPName> --password ...`

**Comment by slack** [comment]
If the password is not expired, attach a public ip address to one of the nodes and check the kubelet logs. Errors connecting back to the master infrastructure should be there.

**Comment by chetanku** [comment]
Any leads on this? I am facing the same issue

**Comment by chetanku** [comment]
nevermind, I had to wait for sometime(10 mins) before I see the nodes in kubectl get nodes

**Comment by fox1t** [comment]
Hi, same issue here. I just created a cluster using AKS in westeurope reagion and i am unable to connect to it.
`kubectl get no`

`Unable to connect to the server: net/http: TLS handshake timeout`

Are someone looking actively into this?

**Comment by a-zen** [comment]
I'm having the same issue. Doing `az aks upgrade` didn't help. 
I connect to one of the new nodes and looked at the logfiles. It seems the new nodes can not connect to the AKS:

`
Jan 25 17:32:04 aks-nodepool1-36120635-2 docker[7371]: E0125 17:32:04.629807    7946 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://myk8sclust-myresourcegroup-c09a93-27c06a7b.hcp.westeurope.azmk8s.io:443/api/v1/services?resourceVersion=0: net/http: TLS handshake timeout
`

I also tried to manually connect to the master from the node and retrieved the same error.
The name resolution is working fine, but it seems something is blocking the https request
to the Kubernetes API.

**Comment by nikparmar** [comment]
Hey guys any update this?

**Comment by qiangli** [comment]
Hitting same issue. Portal reports correct number of nodes but kubectl always reports the wrong old count.  It behaves like kubectl and portal are using different data store/cache which are out of sync and rerunning scale with the same node count does not update the value. Tried a number of different "solutions", this is what "worked":  rescale down to a different node count and up again  to force a change for kubectl to report the correct number of nodes.

**Comment by seanknox** [comment]
Closing due inactivity. Feel free to re-open if still an issue.

**Comment by ilanpillemer** [comment]
I still have the issue:

- az aks, and portal says I should have 5 nodes.
- kubectl get nodes, and all kube stuff shows I only have 4

**Comment by jbrozena22** [comment]
Same issue here. Portal says I have 2, kubectl shows I only have 1. This is on Kubernetes version 1.11.5. The workaround of upgrading to the same version of kubernetes did not work.

This should be re-opened.

**Comment by ilanpillemer** [comment]
Yes it should.

**Comment by bjorn-ali-goransson** [comment]
@slack We had this (?) issue some time ago on our production cluster, it was an expired SP who was the culprit. How come an upgrade is even allowed without checking the SP validity beforehand?

I mentioned this to support but they just said we should check it beforehand. Outrageous if you ask me!

Note to others, with an expired SP your VMs will be created but not added to the cluster successfully, please go to your Azure Portal and open the real resource group for the AKS resources. Open the Load Balancer and select Backend Pools. There you should have your VMs registered. If it's empty then there's your problem.

You can try scaling down to 1 node and then up again, then the new machines will be added - IF and only if your SP is correct. The first node will still be missing though. Delete the resources for the first VM manually and rescale to recreate it...

If you want, you can add them manually but this will probably require restarting of kube-proxy and whatnot so best just to recreate them one more time.
