### ISSUE TITLE
Can't change AKS Dashboard Deployment

### ISSUE THREAD

**Issue by AlexandreRzc** [Azure/AKS#771]
**What happened**:

I try to change CPU/Memory limit of Kubernetes Dashboard via Edit in the dashboard
or exporting the deployment to yaml file and applying after modification. 
But the new configuration is always rollbacked to the original configuration

**What you expected to happen**:

I expect the deployment to be updated

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4", GitCommit:"bf9a868e8ea3d3a8fa53cbb22f566771b3f8068b", GitTreeState:"clean", BuildDate:"2018-10-25T19:06:30Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?) : 

20 nodes

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

microservices

- Others:

**Comment by dstrebel** [comment]
The dashboard config is set to reconcile, so any changes made to it are reverted. What's the use case for changing the configuration?Are you having issues with the dashboard with the set config?

**Comment by AlexandreRzc** [comment]
Hi 
We have a 20 nodes cluster with thousands pods  deployed and we experience slowness and sometime dashboard going oom and restart.  A coworker suggested that the memory could be the cause  and we tried to increase it but couldn't because of the reconcile as you say
The pods are in the same namespace, so there is a lot of paging : I wonder if it's related to this issue ?
[#3052](https://github.com/kubernetes/dashboard/issues/3052)

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
