### ISSUE TITLE
Can't install virtual nodes addon

### ISSUE THREAD

**Issue by phatcher** [Azure/AKS#773]
**What happened**:
Can't install virtual addon.  Following instructions at [virtual nodes cli](https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-clil) and entering

`az extension add --source https://aksvnodeextension.blob.core.windows.net/aks-virtual-node/aks_virtual_node-0.2.0-py2.py3-none-any.whl`

The command never returns (>30 mins) and there are no warnings/errors

**What you expected to happen**: Extension to install or an error message

**How to reproduce it (as minimally and precisely as possible)**:
1. Authenticate
2. Run command as above

**Anything else we need to know?**:

**Environment**: NA

**Comment by jeremyrickard** [comment]
@phatcher Checking again to see if you're still having this issue? Seems like perhaps there was an issue actually installing the extension.

**Comment by srrengar** [comment]
@jnoller adding the extension isn't required anymore, can we close this?
