### ISSUE TITLE
in-cluster api watch events hangs after some time

### ISSUE THREAD

**Issue by mouradmourafiq** [Azure/AKS#774]
**What happened**:

Starting a watch monitor appears to stop after some time.

**What you expected to happen**:

It should work as expected, both for short and long running api requests.

**How to reproduce it (as minimally and precisely as possible)**:

```python
from kubernetes import client, config
from kubernetes import watch

config.load_incluster_config()
w = watch.Watch()

api_client = client.api_client.ApiClient(configuration=k8s_config)
for event in w.stream(api_client.list_namespaced_pod):
    print(event)
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster: 8 nodes
- General description of workloads in the cluster: machine learning

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
