### ISSUE TITLE
Nodes failing despite adding new ones

### ISSUE THREAD

**Issue by vcorr** [Azure/AKS#776]
We are experiencing several issues with a cluster that has worked fine for months.

Today, all 3 nodes were in NotReady state. I tried to scale up the cluster and for a while I did get some functioning nodes. But after half an hour or so the NotReady status started appearing again and now scaling seems to take forever with no change for the nodes.

kubectl describe is able to show the following errors in the nodes

Node 1
```
failed to get image stats: rpc error: code = DeadlineExceeded desc = context deadline exceeded
rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

Node 2
```
KubeletNotReady              container runtime is down,PLEG is not healthy: pleg was last seen active 1h56m24.276794343s ago; threshold is 3m0s
rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

We are running on the latest v1.11.5

Any pointers on how to fix this? At the moment this cluster is not usable at all.

**Comment by alftio** [comment]
- Check the nodes status and that the VM extensions are loaded succesfully.
- SSH to the Node and make sure that the Docker and Kubelet are up and running.
- Get the Docker and Kubelet logs.
If the error persist please open a ticket with the Azure AKS team for furhter investigation about the nodes updates (Kernel, region and other small components) and status.

**Comment by jnoller** [comment]
@vcorr As @alftio noted, please file a technical support ticket via the Azure portal for support to dig into the cluster(s) impacted by the issue. We can not send/receive the needed subscription data via GitHub to debug specific cluster issues.
