### ISSUE TITLE
Dashboard and metrics keep crashing / Advanced networking

### ISSUE THREAD

**Issue by Saternia** [Azure/AKS#778]
We created a new AKS cluster using the advanced networking option
Everything succeeded and the standard kube-system pods were spooled up
We however noticed the 6 of the pods keep crashing:
![image](https://user-images.githubusercontent.com/43027233/50964756-c90bdc80-14d8-11e9-81e6-eb3e7bd90b4c.png)

We had a look at the logs we could get to and found this:
![image](https://user-images.githubusercontent.com/43027233/50964785-d45f0800-14d8-11e9-9d79-bf32121b302b.png)

Any ideas on how we fix this.
This issue only occurs when we use the advanced network option

**Comment by jnoller** [comment]
Hi @Saternia - please file an Azure technical support ticket in the Azure portal for this issue (especially if you can recreate this on newly made clusters). We can not ask for the needed account info and data to examine the crashing cluster via GitHub.
