### ISSUE TITLE
AKS Vnet + Load Balancer

### ISSUE THREAD

**Issue by Novitoll** [Azure/AKS#78]
I'd like to have 2 extra resources created by AKS
- Azure Public IP
- Azure Load Balancer on top of Azure Public IP for SSL offloading

- I will create Ingress myself and would like to link Azure LB with AKS Ingress

Also, could not find the online community of AKS like some Slack group, there is nothing interesting in https://blogs.msdn.microsoft.com/azuredev/ I guess, so have to ask such as questions as Github Issues.

**Comment by evillgenius75** [comment]
When you create a service in K8s of type LoadBalancer it will automatically create an Azure LB with a Front end Public IP that has all of the needed LB rules for the service exposed as well as create the needed NSG rules to allow the traffic to the nodes.

**Comment by evillgenius75** [comment]
If you want to use an Ingress such as Nginx in AKS, just make sure it’s service manifest used LoadBalancer type and not ClusterIP. It will create the LB for you with a Public IP that goes to the ingress. All other services can be exposed via ClusterIP Service type and create an Ingress rule for them to reference the Ingress Controller.

**Comment by slack** [comment]
@Novitoll if you are using Helm take a look at `nginx-ingress` <https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/README.md>

We also have a `sig-azure` channel on the Kubernetes slack <http://slack.k8s.io/>.
