### ISSUE TITLE
Inconsistent Naming for SubnetName in AciConnectorLinux (Virtual Nodes)

### ISSUE THREAD

**Issue by patst** [Azure/AKS#783]
**What happened**:
I created a AKS cluster and enabled the Virtual Nodes preview feature. Then I checked the automation script in Azure Portal.  (Or just type `az aks list`)

The `addonProfiles` part looks like this:

```
"addonProfiles": {
  "aciConnectorLinux": {
    "enabled": true,
    "config": {
      "SubnetName": "test-aks-aci-subnet"
    }
  }
}
```
**What you expected to happen**:

The property name **S**ubnetName starts with an uppercase. I would expect it to start with a lower case like every other property name.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the tutorial: https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli

**Comment by srrengar** [comment]
thanks for catching this, we will roll out a fix soon

**Comment by jlpedrosa** [comment]
Hi @srrengar 

I was wondering what would be the fix that will be applied. Will you introduce a new API version of the API with the correct casing? Will you make the API that accepts camel and pascal casing?

What I am trying to figure out is how I can make software that can run agains the current version and the version after the fix.

**Comment by srrengar** [comment]
We will make sure it is backwards compatible so no need to change what you are currently using

**Comment by jlpedrosa** [comment]
Thanks  @srrengar   for the feedback, this should unblock the fix of terraform AKS in azure provider.

**Comment by jluk** [comment]
@jlpedrosa closing this since it looks like the TF issue referenced has been fixed.
