### ISSUE TITLE
AKS keeps creating new public ip even if a static public ip is specified at spec.loadBalancerIp

### ISSUE THREAD

**Issue by yhvicey** [Azure/AKS#784]
**What happened**:
AKS keeps creating new public ip even if a static public ip is specified at `spec.loadBalancerIp`.

**What you expected to happen**:
AKS should use the public ip I specified.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new aks cluster
1. Create a public static ip address in resource group created by AKS
1. Deploy a service with `spec.type=LoadBalancer` and `spec.loadBalancerIp=<ip address in last step>`
1. AKS will create a load balancer but it won't use the existing ip address but create a new one.

**Environment**:
- Kubernetes version: 1.11.5
- Size of cluster: 2 nodes (D8s v3)

**Comment by saykumar** [comment]
We haven't tested on 1.11, but on 1.10, it does work for us with `spec.loadBalancerIP`.

We also add the annotation `service.beta.kubernetes.io/azure-load-balancer-resource-group` to refer to an IP in another resource group.

**Comment by mpluhar** [comment]
Cool, good to know.

**Comment by yhvicey** [comment]
It's because i'm used `Ip` instead of `IP`. Using `spec.loadBalancerIP` solved the issue. Thx @saykumar !
