### ISSUE TITLE
Editing deployment does not scale nodes down

### ISSUE THREAD

**Issue by JakeLunn** [Azure/AKS#788]
**What happened**:
After updating the cluster-autoscaler deployment to decrease the min-node value, the autoscaler did not decrease the current number of nodes. 

**What you expected to happen**:

After a period of time, number of nodes to decrease to 2. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy cluster autoscaler with min-nodes set to current number of nodes (my case: 3)
2. Edit deployment via kubectl -n kube-system edit deployment cluster-autoscaler
3. Update min nodes to 2

**Environment**:
- Kubernetes version
Client: 1.10.11, Server: 1.11.5

- Size of cluster (how many worker nodes are in the cluster?)
3 nodes, d12 v2 Promo

There were 0 events in the event log for the auto-scaler after waiting multiple days after editing the deployment.

There were 2 pods deployed to the cluster, each one with requests for 2vcpus - but they were at CPU 0% because they're currently not being pointed to by any environments.  The d12 V2s have 4vcpus each so it shouldn't have taken up too much.

**Comment by MarcosMMartinez** [comment]
I think you need to go through AKS Resource Provider to low the min nodes: https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler#change-the-cluster-autoscaler-settings

**Comment by feiskyer** [comment]
@JakeLunn This is not how cluster-autoscaler works. See https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-scale-down-work for understanding the details.
