### ISSUE TITLE
Oops, I deleted the AKS cluster from azure portal (DR planning scenario)

### ISSUE THREAD

**Issue by misterjoshua** [Azure/AKS#791]
**What happened**:
An administrator in the azure portal deleted the AKS cluster. Or: An administrator brutally mangled a `kubectl delete` command and everything is gone.

**What you expected to happen**:
Be able to restore a backup of the managed control plane's configuration data to bring the cluster back to life.

**How to reproduce it (as minimally and precisely as possible)**:
Create an AKS cluster in the azure portal, add a selection of pods, then delete the AKS cluster from the portal.

**Anything else we need to know?**:
This is a hypothetical situation for DR planning. I was directed here by Azure technical chat because they mentioned there may not be any documentation for how this is done.

Given that as users, we don't have access to the master node(s), we can't do disk snapshots or anything like that. I was unsure how the AKS team suggested we perform disaster recovery in the event that an administrator deletes the container service.

**Environment**:
*Kubernetes version (use `kubectl version`):*
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

*Size of cluster (how many worker nodes are in the cluster?)*
2 at the moment

*General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)*
HTTP microservices

**Comment by sideeksh** [comment]
Hi @misterjoshua - Microsoft does not have a first-party solution to your problem but you can see our latest guidance at https://docs.microsoft.com/en-us/azure/aks/operator-best-practices-multi-region. I am currently determining the need for AKS BCDR and would love to dig deeper into your needs. Can you email me at sideeksh@microsoft.com with a couple of times that work for you this/next week? Thanks!

Siddharth

**Comment by misterjoshua** [comment]
Hi @sideeksh. Thanks for getting back to me. Sorry for the delay. I've been on sick leave. I sent you an email just now.
