### ISSUE TITLE
Installing Cert-Manager failed with: "is forbidden" when using AKS with disabled rbac

### ISSUE THREAD

**Issue by thorstenwitt** [Azure/AKS#796]
**What happened**:
I want to install the cert-manager in my aks-cluster with helm.
But always get that error:

```
release queenly - mastiff failed: clusterroles.rbac.authorization.k8s.io "queenly-mastiff-webhook-ca-sync"
is forbidden: attempt to grant extra privileges: [PolicyRule {
        Resources: ["secrets"],
        ResourceNames: ["queenly-mastiff-webhook-ca"],
        APIGroups: [""],
        Verbs: ["get"]
    }
    PolicyRule {
        Resources: ["validatingwebhookconfigurations"],
        ResourceNames: ["queenly-mastiff-webhook"],
        APIGroups: ["admissionregistration.k8s.io"],
        Verbs: ["get"]
    }
    PolicyRule {
        Resources: ["validatingwebhookconfigurations"],
        ResourceNames: ["queenly-mastiff-webhook"],
        APIGroups: ["admissionregistration.k8s.io"],
        Verbs: ["update"]
    }
    PolicyRule {
        Resources: ["mutatingwebhookconfigurations"],
        ResourceNames: ["queenly-mastiff-webhook"],
        APIGroups: ["admissionregistration.k8s.io"],
        Verbs: ["get"]
    }
    PolicyRule {
        Resources: ["mutatingwebhookconfigurations"],
        ResourceNames: ["queenly-mastiff-webhook"],
        APIGroups: ["admissionregistration.k8s.io"],
        Verbs: ["update"]
    }
    PolicyRule {
        Resources: ["apiservices"],
        ResourceNames: ["v1beta1.admission.certmanager.k8s.io"],
        APIGroups: ["apiregistration.k8s.io"],
        Verbs: ["get"]
    }
    PolicyRule {
        Resources: ["apiservices"],
        ResourceNames: ["v1beta1.admission.certmanager.k8s.io"],
        APIGroups: ["apiregistration.k8s.io"],
        Verbs: ["update"]
    }
] user = & {
    system: serviceaccount: kube - system: default ef944f44 - 1 fe9 - 11e9 - 83 f4 - f28e18b4cf9d[system: serviceaccounts system: serviceaccounts: kube - system system: authenticated] map[]
}
ownerrules = [] ruleResolutionErrors = [
    [clusterroles.rbac.authorization.k8s.io "cluster-admin"
        not found, clusterroles.rbac.authorization.k8s.io "system:discovery"
        not found
    ]
]
```

**What you expected to happen**:
Successfull deployment

**How to reproduce it (as minimally and precisely as possible)**:
Via Azure Cli:
```
az aks create \
    --resource-group mycluster-group \
    --name mycluster \
    --node-count 3 \
   --disable-rbac 

az aks get-credentials

helm init --wait
helm repo update
kubectl create clusterrolebinding add-on-cluster-admin \
                --clusterrole=cluster-admin \
                --serviceaccount=kube-system:default

helm install stable/cert-manager \
        --namespace mynamespace \
        --set ingressShim.defaultIssuerName=letsencrypt-prod \
        --set ingressShim.defaultIssuerKind=ClusterIssuer \
        --set rbac.create=false \
        --set createCustomResource=true \
        --set serviceAccount.create=false

```

**Anything else we need to know?**:
It has already worked.

**Environment**:
- Kubernetes version Client: 1.9.11, 1.13.2
- Size of cluster 3
- General description of workloads in the cluster : Java App with Ingress Controller
- Others: -

**Comment by kingdonb** [comment]
agreed, I just tried to upgrade from v0.4.1 to v0.6.0 and got a similar message including:

```
ruleResolutionErrors=[[clusterroles.rbac.authorization.k8s.io "system:discovery" not found, clusterroles.rbac.authorization.k8s.io "cluster-admin" not found]]
```

Upgrading my helm tiller pod to the latest v2.12.3 changed the error to this:

```
Error: UPGRADE FAILED: no ConfigMap with the name "cert-manager-webhook-ca-sync" found
```

The full command that I am using,

```
helm upgrade cert-manager stable/cert-manager \
  --set ingressShim.defaultIssuerName=letsencrypt-prod \
  --set ingressShim.defaultIssuerKind=ClusterIssuer
```

Adding "`--set rbac.create=false`" I thought would solved it for me.  I wound up needing to read this: https://docs.cert-manager.io/en/latest/admin/upgrading/upgrading-0.4-0.5.html

and this: https://docs.cert-manager.io/en/latest/admin/upgrading/upgrading-0.5-0.6.html

finally this: https://docs.cert-manager.io/en/latest/admin/upgrading/index.html

I think I understand the problem now, but I may have done something wrong or in the wrong order, as I see I do have the configmap named `cert-manager-webhook-ca-sync` in my kube-system namespace, where cert-manager is installed, but it still can't be found:

```
Error: UPGRADE FAILED: no ConfigMap with the name "cert-manager-webhook-ca-sync" found
```

**Comment by kingdonb** [comment]
Looks like my issue is reported here: https://github.com/jetstack/cert-manager/issues/1270

Perhaps I should have installed cert-manager in its own namespace...

**Comment by kingdonb** [comment]
Seems like there were some very important notes on this page:

https://docs.cert-manager.io/en/latest/admin/upgrading/upgrading-0.5-0.6.html

**Comment by kingdonb** [comment]
I think from re-reading your notes, you already thought of all that.  After reading the upgrade notes carefully, I am stuck at exactly what problem your first report describes.

Installing v0.5.0 is also not possible from what I can tell.  Same issue.

**Comment by kingdonb** [comment]
It looks to me that the webhook chart is not honoring the rbac.create=false flag

**Comment by kingdonb** [comment]
I was able to manually edit charts/webhook/values.yaml to add

```
rbac:
  create: false
```

and editing `charts/webhook/templates/rbac.yaml` (to wrap the whole file in a conditional) and `charts/webhook/templates/ca-sync.yaml` to similarly wrap the blocks that were attempting to create RBAC resources in this conditional `{{- if .Values.rbac.create -}}`, which made it possible to install v0.6.0 otherwise normally:

```
{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:

...
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "webhook.fullname" . }}-ca-sync
  labels:
    app: {{ include "webhook.name" . }}
    chart: {{ include "webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "webhook.fullname" . }}-ca-sync
subjects:
  - name: {{ include "webhook.fullname" . }}-ca-sync
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
{{- end -}}
```

I'd call this a bug in the new webhook sub-chart.  Maybe the rbac.create value can be passed down in a global section so that it can be honored?  I think that's how I've seen this kind of chart-to-chart communication done before.  My change to make it work is a kludge, since rbac.create is set to false manually in the sub-chart, directly in values.yaml.  But nobody knows you're a dog on the internet...

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
