### ISSUE TITLE
Automatically Reboot Nodes for Security Fixes

### ISSUE THREAD

**Issue by RehanSaeed** [Azure/AKS#797]
The docs suggest using [kured](https://github.com/weaveworks/kured) to reboot nodes that require it for security fixes. It would be nice if this was an option we can turn on at the Azure level to automatically do this one node at a time without having to install and manage a third party component.

**Comment by jluk** [comment]
This should be addressed in issue #893, closing as a result. Once that capability has shipped, a future capability is being investigated to make that automatic whenever a new vhd can be pulled.
