### ISSUE TITLE
AKS with RBAC unable to view Full Dashboard with Azure AD

### ISSUE THREAD

**Issue by Sudharma** [Azure/AKS#798]
I have RBAC enabled AKS cluster with proper Azure AD integration. The things are working fine at control plane. However to access dashboard, I create an access token `az account get-access-token --query accessToken -o tsv` and I start `kubectl-proxy`.

Expected behaviour : The members of Azure AD group should be able to have full permission on the dashboard with the token. This was working fine before( Cluster was almost a month old). Now I have a new cluster.

Actual Behaviour : The dashboard is forbidding access to the cluster admins.I can see the dashboard with minimal access privileges.

Actually I would like to know that when the cluster is RBAC enabled with proper Azure AD integration, does granting a `cluster-admin` access to `kubernetes-dashboard` service account makes its unsecure? Or I understand from documents that the with the dashboard URL anyone could access the Cluster.

Clarifications

I have proper ClusterRoleBinding for the AzureAD group.( with cluster-admin Role)
When I elevate the ClusterRoleBinding `kubernetes-dashboard` service account to `cluster-admin` the dashboard works.(This is quite obvious but making it explicit)

**Comment by chaholl** [comment]
I'm also seeing this issue across 12 AKS clusters. 
However, in my experience, it isn't specifically related to Azure AD users- any credentials passed to the dashboard are ignored, whether as a bearer token on the login page, a` kubeconfig` file on the login page or an `authorization` header with a bearer token. In each case the `kubernetes-dashboard` service account is used

**Comment by chaholl** [comment]
Thanks for the tip @omerlh 

In my case I see the same problem when using a K8S generated service account. So the token looks like this:
```{
  "iss": "kubernetes/serviceaccount",
  "kubernetes.io/serviceaccount/namespace": "kube-system",
  "kubernetes.io/serviceaccount/secret.name": "vsts-deploy-token-srxzs",
  "kubernetes.io/serviceaccount/service-account.name": "vsts-deploy",
  "kubernetes.io/serviceaccount/service-account.uid": "6d9589b9-d2ef-11e8-bf6a-da8ad80a69e2",
  "sub": "system:serviceaccount:kube-system:vsts-deploy"
}
```

**Comment by omerlh** [comment]
Kubernetes service account is a different problem I think. The authentication does not go through the openid connect integration as much as I know.

**Comment by chaholl** [comment]
Agreed. I think it's a general problem with the dashboard. I notice that it's automatically updated in AKS so maybe 1.10.1 or something in it's config has changed over the past week

**Comment by omerlh** [comment]
I think there are 2 separate problems here, and the one with AAD tokens is a lot harder to fix. I'm waiting for more than a month to hear from Azure about it :)

**Comment by Sudharma** [comment]
well I smell something has got changed on the Access token validation from Azure side since it was working well before, at least I can assure it :). However I am not sure if the problem could be with serviceAccount since the dashboard with minimal Role is working right with the token. Correct me if I am wrong

**Comment by omerlh** [comment]
I did not tested it recently, but as long the expected aud has not changed, I'm not sure it is fixed...

**Comment by Sudharma** [comment]
I just changed the status and the description for proper understanding. I guess previously it was mis leading! I am able to see the dashboard with least privileges.

**Comment by mattpetrick** [comment]
we can reproduce this regression in AKS dashboard access. user's AAD token on login are not being honored by dashboard. instead the default dashboard service account with its default min privileges is being used by dashboard. log file:

> 2019/02/20 02:02:07 Getting application global configuration
2019/02/20 02:02:07 Application configuration {"serverTime":1550628127853}
2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Incoming HTTP/1.1 GET /api/v1/systembanner request from X.X.X.X:35182: {}
2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Incoming HTTP/1.1 GET /api/v1/settings/global request from X.X.X.X:35150: {}
2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Outcoming response to X.X.X.X:35182 with 200 status code
2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Incoming HTTP/1.1 GET /api/v1/login/status request from X.X.X.X:35190: {}
2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Outcoming response to X.X.X.X:35190 with 200 status code
2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Incoming HTTP/1.1 GET /api/v1/rbac/status request from X.X.X.X:35182: {}
2019/02/20 02:02:08 Cannot find settings config map: configmaps "kubernetes-dashboard-settings" not found
2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Incoming HTTP/1.1 GET /api/v1/login/skippable request from X.X.X.X:35190: {}
2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Outcoming response to X.X.X.X:35190 with 200 status code
2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Incoming HTTP/1.1 GET /api/v1/login/modes request from X.X.X.X:35192: {}
2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Outcoming response to X.X.X.X:35192 with 200 status code
2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Outcoming response to X.X.X.X:35182 with 200 status code
2019/02/20 02:02:08 Cannot restore settings config map: configmaps is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot create configmaps in the namespace "kube-system"
2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Outcoming response to X.X.X.X:35150 with 200 status code
2019/02/20 02:02:12 [2019-02-20T02:02:12Z] Incoming HTTP/1.1 GET /api/v1/csrftoken/login request from X.X.X.X:35182: { contents hidden }
2019/02/20 02:02:12 [2019-02-20T02:02:12Z] Outcoming response to X.X.X.X:35182 with 200 status code
2019/02/20 02:02:12 [2019-02-20T02:02:12Z] Incoming HTTP/1.1 POST /api/v1/login request from X.X.X.X:35182: { contents hidden }
2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Outcoming response to X.X.X.X:35182 with 200 status code
2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Incoming HTTP/1.1 GET /api/v1/login/status request from X.X.X.X:35182: {}
2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Outcoming response to X.X.X.X:35182 with 200 status code
2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Incoming HTTP/1.1 GET /api/v1/csrftoken/token request from X.X.X.X:35182: {}
2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Outcoming response to X.X.X.X:35182 with 200 status code
2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Incoming HTTP/1.1 POST /api/v1/token/refresh request from X.X.X.X:35182: { contents hidden }
2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Outcoming response to X.X.X.X:35182 with 200 status code
2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Incoming HTTP/1.1 GET /api/v1/login/status request from X.X.X.X:35182: {}
2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Outcoming response to X.X.X.X:35182 with 200 status code
2019/02/20 02:02:14 [2019-02-20T02:02:14Z] Incoming HTTP/1.1 GET /api/v1/csrftoken/token request from X.X.X.X:35182: {}
2019/02/20 02:02:14 [2019-02-20T02:02:14Z] Outcoming response to X.X.X.X:35182 with 200 status code
2019/02/20 02:02:14 [2019-02-20T02:02:14Z] Incoming HTTP/1.1 POST /api/v1/token/refresh request from X.X.X.X:35182: { contents hidden }
2019/02/20 02:02:14 [2019-02-20T02:02:14Z] Outcoming response to X.X.X.X:35182 with 200 status code
2019/02/20 02:02:14 [2019-02-20T02:02:14Z] Incoming HTTP/1.1 GET /api/v1/overview/default?filterBy=&itemsPerPage=10&name=&page=1&sortBy=d,creationTimestamp request from X.X.X.X:35182: {}
2019/02/20 02:02:14 Getting config category
2019/02/20 02:02:14 Non-critical error occurred during resource retrieval: configmaps is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list configmaps in the namespace "default"
2019/02/20 02:02:14 Non-critical error occurred during resource retrieval: secrets is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list secrets in the namespace "default"
2019/02/20 02:02:14 Non-critical error occurred during resource retrieval: persistentvolumeclaims is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list persistentvolumeclaims in the namespace "default"
20

**Comment by Sudharma** [comment]
> we can reproduce this regression in AKS dashboard access. user's AAD token on login are not being honored by dashboard. instead the default dashboard service account with its default min privileges is being used by dashboard. log file:
> 
> > 2019/02/20 02:02:07 Getting application global configuration
> > 2019/02/20 02:02:07 Application configuration {"serverTime":1550628127853}
> > 2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Incoming HTTP/1.1 GET /api/v1/systembanner request from X.X.X.X:35182: {}
> > 2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Incoming HTTP/1.1 GET /api/v1/settings/global request from X.X.X.X:35150: {}
> > 2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Outcoming response to X.X.X.X:35182 with 200 status code
> > 2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Incoming HTTP/1.1 GET /api/v1/login/status request from X.X.X.X:35190: {}
> > 2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Outcoming response to X.X.X.X:35190 with 200 status code
> > 2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Incoming HTTP/1.1 GET /api/v1/rbac/status request from X.X.X.X:35182: {}
> > 2019/02/20 02:02:08 Cannot find settings config map: configmaps "kubernetes-dashboard-settings" not found
> > 2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Incoming HTTP/1.1 GET /api/v1/login/skippable request from X.X.X.X:35190: {}
> > 2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Outcoming response to X.X.X.X:35190 with 200 status code
> > 2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Incoming HTTP/1.1 GET /api/v1/login/modes request from X.X.X.X:35192: {}
> > 2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Outcoming response to X.X.X.X:35192 with 200 status code
> > 2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Outcoming response to X.X.X.X:35182 with 200 status code
> > 2019/02/20 02:02:08 Cannot restore settings config map: configmaps is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot create configmaps in the namespace "kube-system"
> > 2019/02/20 02:02:08 [2019-02-20T02:02:08Z] Outcoming response to X.X.X.X:35150 with 200 status code
> > 2019/02/20 02:02:12 [2019-02-20T02:02:12Z] Incoming HTTP/1.1 GET /api/v1/csrftoken/login request from X.X.X.X:35182: { contents hidden }
> > 2019/02/20 02:02:12 [2019-02-20T02:02:12Z] Outcoming response to X.X.X.X:35182 with 200 status code
> > 2019/02/20 02:02:12 [2019-02-20T02:02:12Z] Incoming HTTP/1.1 POST /api/v1/login request from X.X.X.X:35182: { contents hidden }
> > 2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Outcoming response to X.X.X.X:35182 with 200 status code
> > 2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Incoming HTTP/1.1 GET /api/v1/login/status request from X.X.X.X:35182: {}
> > 2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Outcoming response to X.X.X.X:35182 with 200 status code
> > 2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Incoming HTTP/1.1 GET /api/v1/csrftoken/token request from X.X.X.X:35182: {}
> > 2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Outcoming response to X.X.X.X:35182 with 200 status code
> > 2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Incoming HTTP/1.1 POST /api/v1/token/refresh request from X.X.X.X:35182: { contents hidden }
> > 2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Outcoming response to X.X.X.X:35182 with 200 status code
> > 2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Incoming HTTP/1.1 GET /api/v1/login/status request from X.X.X.X:35182: {}
> > 2019/02/20 02:02:13 [2019-02-20T02:02:13Z] Outcoming response to X.X.X.X:35182 with 200 status code
> > 2019/02/20 02:02:14 [2019-02-20T02:02:14Z] Incoming HTTP/1.1 GET /api/v1/csrftoken/token request from X.X.X.X:35182: {}
> > 2019/02/20 02:02:14 [2019-02-20T02:02:14Z] Outcoming response to X.X.X.X:35182 with 200 status code
> > 2019/02/20 02:02:14 [2019-02-20T02:02:14Z] Incoming HTTP/1.1 POST /api/v1/token/refresh request from X.X.X.X:35182: { contents hidden }
> > 2019/02/20 02:02:14 [2019-02-20T02:02:14Z] Outcoming response to X.X.X.X:35182 with 200 status code
> > 2019/02/20 02:02:14 [2019-02-20T02:02:14Z] Incoming HTTP/1.1 GET /api/v1/overview/default?filterBy=&itemsPerPage=10&name=&page=1&sortBy=d,creationTimestamp request from X.X.X.X:35182: {}
> > 2019/02/20 02:02:14 Getting config category
> > 2019/02/20 02:02:14 Non-critical error occurred during resource retrieval: configmaps is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list configmaps in the namespace "default"
> > 2019/02/20 02:02:14 Non-critical error occurred during resource retrieval: secrets is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list secrets in the namespace "default"
> > 2019/02/20 02:02:14 Non-critical error occurred during resource retrieval: persistentvolumeclaims is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list persistentvolumeclaims in the namespace "default"
> > 20

Thank you very much for the confirmation. happy that it is legit and could be fixed.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
