### ISSUE TITLE
cluster goes into a failed state the rolling upgrade will exceed resource quotas

### ISSUE THREAD

**Issue by jon-walton** [Azure/AKS#799]
**What happened**:

I upgraded a 2 node AKS cluster in our dev subscription. The upgrade failed and the cluster went into a failed state. The failure message was ```azurerm_kubernetes_cluster.aks: Error waiting for completion of Managed Kubernetes Cluster "myCluster" (Resource Group "myRG"): Code="InternalOperationError" Message=""```

**What you expected to happen**:

The upgrade process to check resource quotas before starting the upgrade. If it receives a quota exceeded error during the upgrade, give useful feedback to the user

**How to reproduce it (as minimally and precisely as possible)**:

- Create a subscription with a quota of 10vcpu
- Create an AKS cluster with 2 nodes of Standard_D4_v3 (using a total of 8vcpu)
- Do an upgrade.
- The upgrade will fail with ```azurerm_kubernetes_cluster.aks: Error waiting for completion of Managed Kubernetes Cluster "myCluster" (Resource Group "myRG"): Code="InternalOperationError" Message=""```

The failure is most likely due to the rolling upgrade exceeding the resource quota

The cluster is now in a failed state (although kubernetes itself continues to work)

- Increase cpu quota
- Use the az cli

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.5 -> 1.12.4
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) empty cluster
- Others:

**Comment by jluk** [comment]
@jon-walton did you get around this issue? We're working through improving our error messages, some should already be updated to point to documentation like [here](https://docs.microsoft.com/en-us/azure/aks/troubleshooting#im-receiving-errors-that-my-cluster-is-in-failed-state-and-upgrading-or-scaling-will-not-work-until-it-is-fixed).

**Comment by jon-walton** [comment]
Yes I got around it by increasing the compute quota. If there's now a clear error message saying the upgrade failed due to insufficient quota, feel free to close this issue
