### ISSUE TITLE
volume mounting and data fetch mechanism

### ISSUE THREAD

**Issue by unacao** [Azure/AKS#805]
When we use either the [PVC dynamic](https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv) method or the [AzureFile static](https://docs.microsoft.com/en-us/azure/aks/azure-files-volume) method to mount data into multiple pods with ReadOnlyMany mode, e.g. under /mnt/azure/ directory, does the data in the storage account get downloaded into the physical node? If so, when does it happen? Is there any cache for data downloaded on the node to save pods on the same node from extra downloading?

**Comment by andyzhangx** [comment]
there is `cache=strict` by default in azure file mount options, which will do the caching for data download

**Comment by unacao** [comment]
When is data downloading triggered? Is it lazy downloading, i.e. only triggered when it is accessed?

**Comment by jnoller** [comment]
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
