### ISSUE TITLE
CoreDNS issue in 1.12.4

### ISSUE THREAD

**Issue by timwebster9** [Azure/AKS#808]
We recently rebuilt a cluster using k8s 1.12.4, and we had to revert it as there appeared to be a problem with DNS.

Addresses outside the cluster were only being resolved intermittently.  DNS records for these addresses are managed by Consul.  Running `dig` directly against the Consul server from inside a container works 100% of the time, so that rules out Consul being a problem.  We also don't have this issue in 1.11.5 with kube-dns.   In fact, I just rebuilt the cluster with v1.11.5 and DNS works perfectly.

The AKS cluster is in a private VNET and the Consul server is listed in the DNS server section of the VNET config.

We had to scrap the cluster because it wasn't usable, but we are going to try and reproduce in a different environment.  I have some logs from coredns, but nothing much except a bunch of NXDOMAIN errors, without any explanation why. 

Any suggestions on how to further troubleshoot welcome.

Here is output from a dig command run 3 times in quick succession from inside a container in the cluster, and as you can see each result is different.

This one worked:
```
root@div-pfe-pr-418-cf886bc44-44jtn:/opt/app# dig probate-submit-service-aat.service.core-compute-aat.internal
; <<>> DiG 9.10.3-P4-Debian <<>> probate-submit-service-aat.service.core-compute-aat.internal
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 146
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;probate-submit-service-aat.service.core-compute-aat.internal. IN A
;; ANSWER SECTION:
probate-submit-service-aat.service.core-compute-aat.internal. 0 IN A 10.96.140.11
;; Query time: 19 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Mon Feb 04 11:45:43 UTC 2019
;; MSG SIZE  rcvd: 165
```

This one returned no answer:
```
root@div-pfe-pr-418-cf886bc44-44jtn:/opt/app# dig probate-submit-service-aat.service.core-compute-aat.internal
; <<>> DiG 9.10.3-P4-Debian <<>> probate-submit-service-aat.service.core-compute-aat.internal
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 25491
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;probate-submit-service-aat.service.core-compute-aat.internal. IN A
;; AUTHORITY SECTION:
.                       11      IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2019020400 1800 900 604800 86400
;; Query time: 1 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Mon Feb 04 11:45:46 UTC 2019
;; MSG SIZE  rcvd: 164
```

This one worked but also returned a bunch of stuff in the authority and additional sections:
```
root@div-pfe-pr-418-cf886bc44-44jtn:/opt/app# dig probate-submit-service-aat.service.core-compute-aat.internal
; <<>> DiG 9.10.3-P4-Debian <<>> probate-submit-service-aat.service.core-compute-aat.internal
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4296
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 13, ADDITIONAL: 14
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;probate-submit-service-aat.service.core-compute-aat.internal. IN A
;; ANSWER SECTION:
probate-submit-service-aat.service.core-compute-aat.internal. 0 IN A 10.96.140.11
;; AUTHORITY SECTION:
.                       0       IN      NS      f.root-servers.net.
.                       0       IN      NS      g.root-servers.net.
.                       0       IN      NS      j.root-servers.net.
.                       0       IN      NS      c.root-servers.net.
.                       0       IN      NS      a.root-servers.net.
.                       0       IN      NS      k.root-servers.net.
.                       0       IN      NS      m.root-servers.net.
.                       0       IN      NS      l.root-servers.net.
.                       0       IN      NS      e.root-servers.net.
.                       0       IN      NS      d.root-servers.net.
.                       0       IN      NS      b.root-servers.net.
.                       0       IN      NS      h.root-servers.net.
.                       0       IN      NS      i.root-servers.net.
;; ADDITIONAL SECTION:
m.root-servers.net.     0       IN      A       202.12.27.33
h.root-servers.net.     0       IN      A       198.97.190.53
b.root-servers.net.     0       IN      A       199.9.14.201
a.root-servers.net.     0       IN      A       198.41.0.4
e.root-servers.net.     0       IN      A       192.203.230.10
l.root-servers.net.     0       IN      A       199.7.83.42
f.root-servers.net.     0       IN      A       192.5.5.241
d.root-servers.net.     0       IN      A       199.7.91.13
g.root-servers.net.     0       IN      A       192.112.36.4
i.root-servers.net.     0       IN      A       192.36.148.17
k.root-servers.net.     0       IN      A       193.0.14.129
c.root-servers.net.     0       IN      A       192.33.4.12
j.root-servers.net.     0       IN      A       192.58.128.30
;; Query time: 25 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Mon Feb 04 11:45:48 UTC 2019
;; MSG SIZE  rcvd: 1010
```

**Comment by RotemEmergi** [comment]
Hi ! 

We upgrade our aks cluster from 1.11.5 to the 1.12.4 version  yesterday and we getting a randomly timeout (error 110) to azure redies .
We are using the name server of the redis to connect from our code . 

The aks and the redis is in the some region .

Best Regards

**Comment by lkt82** [comment]
Hi 
We upgraded from 1.11.5 to the 1.12.4 and the coredns pods just rebooted forever. 
Fortunately this was on test cluster and not production!

Best Regards

**Comment by dberuben** [comment]
I opened a ticket on azure support, i have the same issue on my prod cluster but not in my sandbox cluster, upgraded from 1.11.5 to the 1.12.4

<img width="1025" alt="screen shot 2019-02-05 at 8 54 29 am" src="https://user-images.githubusercontent.com/12519394/52277993-f99e3500-2923-11e9-873a-1343e8e4d1b1.png">

**Comment by timwebster9** [comment]
The cause of this appears to be the fact that we have multiple DNS servers on our VNET.  The default CoreDNS config uses the loadbalance plugin to randomly distribute queries to the nameservers.  If a query is served by the 'wrong' nameserver, you get NXDOMAIN and it doesn't re-try the other nameservers.

This wasn't an issue pre-CoreDNS.  The recently released [hotfix](https://github.com/Azure/AKS/releases/tag/2019-02-07) doesn't seem to address this either.

I understand that workarounds involving using only a single nameserver on the VNET with forwarding configured can fix this, but at the end of the day this breaks our environment.

Will the previous behaviour be supported going forward, or do customers with this configuration need to reconfigure their infrastructure?

**Comment by theharleyquin** [comment]
Adding to the thread. I have also ran across the same issues (MS Case 119022524002730). In a few different vnets that I have tried in, they all have multiple DNS Servers, 2 private and 1 Azure DNS. When I added in the custom configmap, coredns pods are in a constant spin.

**Comment by robbiezhang** [comment]
@timwebster9, @theharleyquin, you can setup the sub-domains in the CoreDNS custom config map, so that the DNS resolution will be sent to the right nameserver.
https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configuration-equivalent-to-kube-dns

**Comment by robbiezhang** [comment]
@timwebster9 @theharleyquin you can also enable coredns log by adding this?

```yaml
apiVersion: v1
data:
  log.override: |
    log
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
  name: coredns-custom
  namespace: kube-system
```

**Comment by dbilleci-lightstream** [comment]
Why is the "known issue" label removed? We're running into this now and found this thread.  The fact that DNS just doesn't work out of the box seems like a huge issue.

What is the fix?  Right now, our pods are failing to resolve things like `.hcp.eastus2.azmk8s.io:443`, and `security.ubuntu.com` - I can't believe we're supposed to have to have "custom" config maps in order to resolve those names?

We do have private DNS enabled on our subnets, and we're in private subnets.

If there is extra work required to get "ubuntu.com" to resolve for AKS.. there needs to be clear documentation on how to properly get it working.

**Comment by aublightstream** [comment]
I have updated an impacted cluster from 1.12.4 to 1.12.5 and to 1.12.6 and found the problem persists across all three versions.

**Comment by jnoller** [comment]
@dbilleci-lightstream  @aublightstream You should not need anything beyond a default AKS cluster for basic cluster DNS. These are well-tested out of the box, and the root-cause of this issue and thread have all been resolved.

It sounds like your issue is specific to your cluster or network configuration, in order to diagnose this please file an Azure technical support request so our on-call staff can diagnose the cluster and see if there is a worker-master communications issue, port/NSG/url blocking or whitelisting, etc.

**Comment by samirageb** [comment]
@jnoller So does this issue only apply to kube-dns, core-dns, or resolved externally?

**Comment by jnoller** [comment]
@samirageb Which issue? The main issue has been resolved.

**Comment by samirageb** [comment]
@jnoller It's hard to know what the main issue was tbh. Seems like it was linked to 1.12.4 and CoreDNS not starting successfully?

**Comment by jnoller** [comment]
@samirageb Yup, just confirming- the original issue was a conflict from when we released 1.12 and the CoreDNS change. There was a bug where existing clusters could end up with both kube-dns and CoreDNS running at once. This was mitigated by on-call engineering - if users see both running, please file a support ticket so it can be examined.

Then, there were follow up issues where users were attempting to perform the same customization(s) on CoreDNS as they did on kube-dns - however kube-dns and coreDNS do not support the same file syntax, order of operations/loading, etc. AKS **added** the ability to customize CoreDNS via a new config map, and that is now documented here:

https://docs.microsoft.com/en-us/azure/aks/coredns-custom

**Comment by samirageb** [comment]
Thanks for the clarification!

**Comment by hdiass** [comment]
Is it safe to upgrade now from `v.1.11.10` to `v1.12.8` without any dns disruption (no custom kube-dns configs) ?
