### ISSUE TITLE
Unable to get cluster profile with API version 2018-08-01-preview

### ISSUE THREAD

**Issue by Hong-Revo** [Azure/AKS#809]
I'm unable to get the cluster profile via the REST API, when I use the 2018-08-01-preview API version. Specifically, the call
```
POST .../accessProfiles/clusterUser/listCredential?api-version=2018-08-01-preview
```
results in a 404 error: `Could not find role name: clusterUser in subscription:
35975484-5360-4e67-bf76-14fcb0ab5b9d, resourceGroup: deployresgrp,
managed cluster resource: hongakstest.`

When I switch back to the previous API version (2018-03-31), it works and I get the kubeconfig.

The cluster in question:
Subscription ID `35975484-5360-4e67-bf76-14fcb0ab5b9d`
resource group `deployresgrp`
resource `hongakstest`

**Comment by jnoller** [comment]
This should be resolved with the hotfix now rolling out globally. Please see: https://github.com/Azure/AKS/releases/tag/2019-02-07

**Comment by Hong-Revo** [comment]
@jnoller Thanks. I see from your link that that API call is going to be deprecated; will there still be a way to get the kubeconfig via REST?

**Comment by weinong** [comment]
https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/listclusteradmincredentials
https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/listclusterusercredentials

**Comment by jnoller** [comment]
Hotfix rolled out
