### ISSUE TITLE
Can't create External IP

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#81]
I'm in EastUS and no matter what I try I get the following error, tried with many different tests.

 
Error creating load balancer (will retry): Failed to ensure load balancer for service wordpress/wordpress-wordpress: [ensure(wordpress/wordpress-wordpress): lb(kubernetes) - failed to ensure host in pool: "compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/virtualMachines/aci-connector-0' under resource group 'MC_rgp-use-arch-dev_aks-use-arch-dev_eastus' was not found.\"", ensure(wordpress/wordpress-wordpress): lb(kubernetes) - failed to ensure host in pool: "compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/virtualMachines/aci-connector-1' under resource group 'MC_rgp-use-arch-dev_aks-use-arch-dev_eastus' was not found.\""]

**Comment by AceHack** [comment]
Okay I fixed this by removing aci-connector.  Is there a way to tag something to stay away from aci or taint the aci pool?  Will things like this be supported with ACI in the future?

**Comment by slack** [comment]
The connector supports deployment with a node taint:
* https://github.com/virtual-kubelet/virtual-kubelet/blob/master/charts/virtual-kubelet/templates/deployment.yaml#L28

You should be able to update the chart with a taint of your choosing to manage pod scheduling.

**Comment by AceHack** [comment]
@slack How is virtual-kubelet the same as aci-connector from Microsoft?  These are two different projects it looks like.

**Comment by evillgenius75** [comment]
I believe there is an Open PR for this on ACI-Connector and it also effects Virtual Kubelet
https://github.com/Azure/aci-connector-k8s/issues/48

**Comment by slack** [comment]
@AceHack aci-connector is going away in favor of a new cross-company collaboration, latest versions of `az` cli install the virtual kubelet which is functionally the same as the old `aci-connector` but written in go.

@evillgenius75 referenced the correct issue (thanks!).
