### ISSUE TITLE
CoreDNS don't want to start in 1.12.4

### ISSUE THREAD

**Issue by jakubfijalkowski** [Azure/AKS#810]
**What happened**:

After upgrading our 1-node AKS cluster (with Azure networking) from 1.11.5 to 1.12.4, CoreDNS services won't start. All of the `coredns` pods are created and terminated right after, with a single pod working for a couple of minutes and then terminating. Autoscaler set the replica set size to two, so the cluster tries to achieve that but fails. DNS service works (as kube-dns is still running) without that but that's still a problem.

**What you expected to happen**:

CoreDNS should start.

**How to reproduce it (as minimally and precisely as possible)**:

I couldn't reproduce it with new cluster. When upgrading empty cluster everything works. I assume this has something to do with the already-existing workload but I am unable to narrow it down.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.4
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?): 1 Standard_D4s_v3
- General description of workloads in the cluster: some really small .NET Core apps (with virtually no traffic - it's our test-test env) + Jenkins build farm (with Jenkins Kubernetes plugin)
- Others:

Most of the time `kubectl get pods -n kube-system` looks something like this (these are from our cluster):
```
coredns-5bc8b8686f-742lx                1/1     Terminating         0          39s
coredns-676886fbfd-cs295                1/1     Running             0          70s
coredns-75b67d97f9-mkz8j                1/1     Terminating         0          20s
coredns-7fc4d5b5ff-2txsh                1/1     Running             0          4s
coredns-7fc4d5b5ff-kcn9r                0/1     ContainerCreating   0          4s
coredns-8dc8fd555-6tvkx                 1/1     Terminating         0          33s
coredns-989b685c-pndmw                  0/1     Terminating         0          26s
coredns-autoscaler-589dd89ffd-595tl     1/1     Running             0          93m
```

`coredns` pods write virtually no logs:
```
.:53
2019/02/06 09:20:16 [INFO] CoreDNS-1.2.2
2019/02/06 09:20:16 [INFO] linux/amd64, go1.11, eb51e8b
CoreDNS-1.2.2
linux/amd64, go1.11, eb51e8b
2019/02/06 09:20:16 [INFO] plugin/reload: Running configuration MD5 = 2e2180a5eeb3ebf92a5100ab081a6381
```

with autoscaler doing the same:
```
I0206 07:47:33.300363       1 autoscaler.go:49] Scaling Namespace: kube-system, Target: deployment/coredns
I0206 07:47:33.654906       1 plugin.go:50] Set control mode to ladder
I0206 07:47:33.654930       1 ladder_controller.go:72] Detected ConfigMap version change (old:  new: 6544984) - rebuilding lookup entries
I0206 07:47:33.654938       1 ladder_controller.go:73] Params from apiserver: 
{"coresToReplicas":[[1,2],[512,3],[1024,4],[2048,5]],"nodesToReplicas":[[1,2],[8,3],[16,4],[32,5]]}
```

Configmaps for both autoscaler and workload pods weren't changed and are as follows:
```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n      pods insecure\n      upstream\n      fallthrough in-addr.arpa ip6.arpa\n    }\n    prometheus :9153\n    proxy . /etc/resolv.conf\n    cache 30\n    loop\n    reload\n    loadbalance\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"kube-dns","kubernetes.io/cluster-service":"true"},"name":"coredns","namespace":"kube-system"}}
  creationTimestamp: "2019-02-06T07:43:47Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
  name: coredns
  namespace: kube-system
  resourceVersion: "6544895"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: efdd690f-29e2-11e9-8d22-ae2a1cc63ca6
```
```
apiVersion: v1
data:
  ladder: '{"coresToReplicas":[[1,2],[512,3],[1024,4],[2048,5]],"nodesToReplicas":[[1,2],[8,3],[16,4],[32,5]]}'
kind: ConfigMap
metadata:
  creationTimestamp: "2019-02-06T07:43:55Z"
  name: coredns-autoscaler
  namespace: kube-system
  resourceVersion: "6544984"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns-autoscaler
  uid: f4c83d53-29e2-11e9-8d22-ae2a1cc63ca6
```

**Issue info**:

I think this is the same problem as in [#808 (comment)](https://github.com/Azure/AKS/issues/808#issuecomment-460646425), but different than #808 (issue), so I'm opening another one.

**Comment by jakubfijalkowski** [comment]
I've checked why these pods get killed in the first place (cause they are terminated by K8s), they receive normal SIGTERM after deleting pod:
```
2019/02/06 10:46:33 [INFO] SIGTERM: Shutting down servers then terminating
```
I've checked replicasets for `coredns` and we are at almost 4k `coredns-ID` ReplicaSets, 3h after the upgrade. Most of them are "dead" (i.e. scaled to 0) hence the pod killing spree. The deployment keeps scaling the replica set down and creating the new one but I don't see why does that happen.

**Comment by jakubfijalkowski** [comment]
Okay, I "solved" this. Forcing the autoscaler to re-set the deployment replicas solved the problem. Everything is back at normal after simple `kubectl scale --replicas 1 deployments/coredns`.

Eh... :(

**Comment by jveski** [comment]
Thanks for reporting this issue. I've been investigating the root cause and thought I would follow up and share some findings.

k8s 1.12 adds a new field to the `SecurityProfile` type (security context's `procMount`) [(source)](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#changelog-since-v1121), so any resources with a `Container` (deployments, replica sets, etc.) will not be equal when created against 1.11 vs 1.12 apiservers (because 1.11 will not set the new field's default value). Since the deployment controller uses pod template equality to identify the candidate (new) replicaset during rollout [(source)](https://github.com/kubernetes/kubernetes/blob/bbfc3be51b4b8fc0fe20e4b863fe53f9c12678d5/pkg/controller/deployment/util/deployment_util.go#L635), a deployment created against a 1.11 apiserver will never be properly associated with candidate replica sets created against a 1.12 apiserver.

This results in strange behavior from the deployment controller: tight loop creation of candidate replica sets with old replica sets scaled to 0, which is why you see the coredns pods terminate soon after starting.

The issue affects a small subset of clusters upgraded to 1.12 since it only occurs when addon manager creates the coredns deployment on the 1.11 apiserver and the deployment's rollout hasn't finished before apiserver is upgraded to 1.12.

That said, we have a fix and will be rolling it out over the next few days. Thanks again for reporting this, and I'm glad you found a workaround.
