### ISSUE TITLE
kube-dns pods remaining after upgrade to 1.12.4

### ISSUE THREAD

**Issue by mleneveut** [Azure/AKS#812]
**What happened**:
Upgrades AKS cluster from 1.11.5 to 1.12.4. New coredns pods have been created, but the old kube-dns pods stil remain in the cluster.

**What you expected to happen**:
kube-dns and kube-dns-autoscaler deployments should have been deleted as they are replaced by coredns.

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade a cluster from 1.11.5 to 1.12.4 (I am in North Europe)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.4
- Size of cluster (how many worker nodes are in the cluster?) 3 x D2 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:
North Europe

**Comment by jnoller** [comment]
This should be resolved with the hotfix release rolling out to all regions as we speak:

https://github.com/Azure/AKS/releases/tag/2019-02-07

**Comment by jnoller** [comment]
Hotfix rolled out.

**Comment by Fydon** [comment]
@jnoller I also previously updated from 1.11.5 to 1.12.4. I've now upgraded to 1.12.5 and still have coredns, coredns-autoscaler, kube-dns-v20 and kube-dns-autoscaler deployments, with their associated pods. Are there manual steps that I should be performing to migrate from kube-dns to coredns?

Following [these steps](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/) I still see kube-dns as the DNS in use.

**Comment by jakubfijalkowski** [comment]
@Fydon Scaling `kube-dns-v20` and `kube-dns-autoscaler` deployments to 0 and then deleting them (provided that you have `coredns` side-by-side the `kube-dns`) worked for me.

**Comment by Fydon** [comment]
@jakubfijalkowski Thank you. I see now that DNS is being resolved by `kube-dns.kube-system.svc.cluster.local` where the select for the `kube-dns` service is `"k8s-app": "kube-dns"` and the `coredns` deployment has a label of `"k8s-app": "kube-dns"`. When scaling down `kube-dns-v20` and `kube-dns-autoscaler` `coredns` resolves all DNS.

**Comment by Thubo** [comment]
I documented what we did to cleanup after upgrading from 1.11.5 to 1.12.5 here: https://github.com/Azure/aks-engine/issues/398#issuecomment-467890973

(Basically what @Fydon described)
