### ISSUE TITLE
Deployment in cluster loses some network functionality

### ISSUE THREAD

**Issue by FrikkinLazer** [Azure/AKS#819]
**What happened**:
All containers in one of my containers lose internet connectivity. I can bash into the running container though, but anything that requires an internet connection fails (eg 'apt-get update'). It is also no longer possible to connect to another container through a load balancer running in the same cluster. Other containers running in a different deployment can still make connections through the load balancer successfully. If I increase the replica count on the deployment, the newly created container in that deployment works correctly.

**What you expected to happen**:

Containers should be able to connect to the internet, as well as another container behind a load balance in the same cluster indefinitely.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure how to reproduce, other than leaving the deployment until they start failing.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
3 worker nodes.
- General description of workloads:
An API behind a load balancer, and a few deployments that all make calls to that API.

Please let me know what commands I should run, or logs I should gather next time this problem occurs, I cannot leave the cluster in this state for long periods of time.

**Comment by jnoller** [comment]
Hi @FrikkinLazer  - Thanks for bringing this up - as we can not debug specific customer cluster issues on github please file an Azure technical support ticket so we can get the needed SubID/etc information to diagnose. Issues like this are not generally applicable or recreate-able outside of a users environment so this will accelerate RCA
