### ISSUE TITLE
CockroachDB failure using helm

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#82]
I'm pretty new to K8s and I'm trying to get CockroachDB helm chart working.

I keep getting the following error.

PersistentVolumeClaim is not bound: "datadir-punk-dingo-cockroachdb-0" (repeated 3 times) 

Any suggestions would be very welcome.

https://github.com/kubernetes/charts/tree/master/stable/cockroachdb

**Comment by AceHack** [comment]
After waiting for about 10 minutes everything is now healthy and working.

**Comment by AceHack** [comment]
Okay I see the storage it created in the MC_* resource group, I understand now.

Thanks.

**Comment by slack** [comment]
Yep, your data should be backed by a managed disk in that MC_ resource group. The lifecycle of the PV, in this case, is set by the `volumeClaimTemplates` in the Cockroach DB StatefulSet template.
