### ISSUE TITLE
Does Azure AKS rotate logs?

### ISSUE THREAD

**Issue by RehanSaeed** [Azure/AKS#823]
As indicated by the Kubernetes [docs](https://kubernetes.io/docs/concepts/cluster-administration/logging/) rotating logs is something you have to do yourself. However, does Azure AKS handle this for you?

The default setup for Docker's logging driver means that it continues to write logs to file until the disk runs out of space.

**Comment by rashmipankaj** [comment]
Any update on this?

**Comment by yvan** [comment]
?

**Comment by ToruMakabe** [comment]
@RehanSaeed The following is /etc/docker/daemon.json on my AKS node. So it should be rotated.

```
{
  "live-restore": true,
  "log-driver": "json-file",
  "log-opts":  {
     "max-size": "50m",
     "max-file": "5"
  }
}
```

**Comment by vishnujanardhanan** [comment]
@jnoller @ToruMakabe So if I wanted the files to roll over after 100m, would AKS pick up if i change this file and restart the node?

**Comment by kennethgp** [comment]
The change would apply but it is not persistent as node can be replaced on scale or upgrade operations. Here is enhancement request for storing custom configuration at cluster level, specifying it at cluster creation:  https://github.com/Azure/AKS/issues/1062

**Comment by TomGeske** [comment]
@juan-lee can you help to answer?

**Comment by palma21** [comment]
This has both answers already provided above by @ToruMakabe and @kennethgp which are correct.
