### ISSUE TITLE
AKS Load Balancer routing failed unexpectedly

### ISSUE THREAD

**Issue by matthewhartstonge** [Azure/AKS#825]
**What happened**: 
All routing/connectivity via the Azure Load Balancer to our AKS cluster dropped off unexpectedly around 11:00AM NZDT.

**What you expected to happen**: 
- Not have Azure Loadbalancer connectivity loss.
- Not have to upgrade K8s to rotate hosts, forcing a routing re-sync .

**How to reproduce it (as minimally and precisely as possible)**: 
Kubernetes 1.11.5, 3 node cluster.

**Anything else we need to know?**:
- We noticed that the Azure Load Balancer was updated twice around 6 hours ago (5:00AM NZDT).
- Upgrading to a newer version of Kubernetes (`1.11.7`) resolved routing issues. I suspect this forced the ALB to resync and correct its routing due to host rotation ...

**Environment**:
- Kubernetes version (use `kubectl version`):
Was 1.11.5, but just used Azure Portal to upgrade to:
```
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?) 
3

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
HTTP microservices

- Others:

**Comment by piotr-napadlek** [comment]
How have you debugged it? We've presumably lost connectivity between the cluster and the LoadBalancer on one of our clusters yesterday. It seemed that the pods are ready and I can connect to services with kubectl proxy, but we couldn't get any response when hitting on kubernetes load balancer ip created by the service. Version 1.12.4.

**Comment by matthewhartstonge** [comment]
That's exactly what we found.

We are proxied via Cloudflare which started returning `503`s when it started playing up every now and then, then all of a sudden it just dropped out and were getting `HTTP 523 Origin is unreachable`.

We had a poke around, services were up, we could access deployments and kube-dashboard using kube-proxy, but anything through the load balancer wasn't responding.

Initially I thought it was an issue with the ingress controller - as sometimes requests were logging saying IP unreachable, but I thought it wasn't able to reach the internal pod, but now I'm wondering if it was the internal IP of the loadbalancer itself.

The only thing we can assume is that in releasing the new version of Kube/the patches for `runc` did something funky and triggered an automated Azure Load balancer update that caused this issue.

**Comment by piotr-napadlek** [comment]
We've just destroyed the whole cluster along with the `kubernetes` load balancer - which of course isn't an option for production but since that was a dev env we could afford it. Deploying it again solved the issue, but meanwhile we're facing another issue with AKS not cleaning up LB resources (worth another issue). I wish it gets stable before we go live.

**Comment by darthchudi** [comment]
Having a similar issue where the `load balancer` services randomly become unavailable for hours and become available after some time. Having to destroy your cluster or restart all your nodes is ridiculous. We're currently in dev and I can't imagine this happening in production.

**Comment by jnoller** [comment]
@darthchudi you are correct this should not be happening, could you please file an azure support ticket so we can dig into the failure(s) and escalate to engineering on call as needed

**Comment by darthchudi** [comment]
Alright, will do. Thanks for the reply @jnoller

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.

**Comment by cdunford** [comment]
@darthchudi - did you end up opening a Microsoft support case for this issue? If so, was anything discovered? We are experiencing similar symptoms.
