### ISSUE TITLE
Autoscaling is not working for Pods in AKS kubernetes ser 1.11.5

### ISSUE THREAD

**Issue by Brijak0** [Azure/AKS#827]
**What happened**:
Azure AKS service failed to auto scale my pods according to the diffined specification:
I have used the following def

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hyposafewebapi
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hyposafewebapi
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 200Mi
  - type: Pods
    pods:
      metricName: memory
      targetAverageValue: 200Mi   

What I see from the following command : kubectl describe hpa is

Name:                                                  hyposafewebapi
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"hyposafewebapi","namespace":"default"},"spec"...
CreationTimestamp:                                     Wed, 13 Feb 2019 11:27:20 +0100
Reference:                                             Deployment/hyposafewebapi
Metrics:                                               ( current / target )
  resource memory on pods:                             <unknown> / 200Mi
  "memory" on pods:                                    <unknown> / 200Mi
  resource cpu on pods  (as a percentage of request):  <unknown> / 50%
Min replicas:                                          2
Max replicas:                                          10
Conditions:
  Type           Status  Reason               Message
  ----           ------  ------               -------
  AbleToScale    True    SucceededGetScale    the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetPodsMetric  the HPA was unable to compute the replica count: unable to get metric memory: unable to fetch metrics from custom metrics API: the server could not find the requested resource (get pods.custom.metrics.k8s.io *)
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Warning  FailedGetResourceMetric       11m (x3 over 12m)  horizontal-pod-autoscaler  unable to get metrics for resource memory: no metrics returned from resource metrics API
  Warning  FailedComputeMetricsReplicas  11m (x3 over 12m)  horizontal-pod-autoscaler  failed to get memory utilization: unable to get metrics for resource memory: no metrics returned from resource metrics API
  Warning  FailedComputeMetricsReplicas  6m (x10 over 10m)  horizontal-pod-autoscaler  failed to get pods metric value: unable to get metric memory: unable to fetch metrics from custom metrics API: the server could not find the requested resource (get pods.custom.metrics.k8s.io *)
  Warning  FailedGetPodsMetric           2m (x18 over 10m)  horizontal-pod-autoscaler  unable to get metric memory: unable to fetch metrics from custom metrics API: the server could not find the requested resource (get pods.custom.metrics.k8s.io *)

and in the log of the metris-server I have seen the following:
 I0213 10:27:50.660774       1 reststorage.go:93] No metrics for pod default/hyposafewebapi-85cd5554b4-dxktf
I0213 10:27:50.660794       1 reststorage.go:93] No metrics for pod default/hyposafewebapi-85cd5554b4-gnmzg
I0213 10:28:20.739967       1 reststorage.go:93] No metrics for pod default/hyposafewebapi-85cd5554b4-dxktf
I0213 10:28:20.739990       1 reststorage.go:93] No metrics for pod default/hyposafewebapi-85cd5554b4-gnmzg
I0213 10:28:50.815901       1 reststorage.go:93] No metrics for pod default/hyposafewebapi-85cd5554b4-gnmzg
I0213 10:28:50.815918       1 reststorage.go:93] No metrics for pod default/hyposafewebapi-85cd5554b4-dxktf 

**What you expected to happen**:
That the metrics could be read by the autoscaler and if needed it would scale accordingly. I'm I missing something in configuration of the cluster and my services? note I have added a resource request level to my deployment of the containers:
resources:
          requests:
            memory: "700Mi"
            cpu: "250m"

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
3 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
The cluster is running ASP .net core services API and IDP services
- Others:

**Comment by jnoller** [comment]
Quick note: the Cluster Autoscaler is still in preview, and not generally available or supported by Microsoft. Please see () for preview feature updates. That said, our technical support teams will try to assist you (best-effort) and examine the versions of the Autoscaler, settings and other changes that could be triggering the issue.

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse

**Comment by mleneveut** [comment]
@Brijak0 Do you have CPU and memory request/limit configured on your deployment ? It fixes the HPA not seeing the current CPU of the pod for me.

**Comment by Brijak0** [comment]
@mleneveut  Yes, thanks and it works now. 👍
