### ISSUE TITLE
AKS Cluster Upgrade failed to create Daemonsets (FluentD/Prometheus)

### ISSUE THREAD

**Issue by bhaskar-chenchu** [Azure/AKS#828]
**What happened**:

Upgradation of AKS platform from current version 1.12.4 to 1.12.5 , led to delete FluentD DaemonSet Pods and didn't spin-up in the new Nodes. 

Understand that,it's expected behaviour as per DS.  

Requesting support to mitigate this issue in future upgrades.

**What you expected to happen**:

Create new DaemonSets along with new Nodes. 

**How to reproduce it (as minimally and precisely as possible)**:

Any K8s version upgrade with Daemonsets will reproduce behaviour. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): **1.12.5**
- Size of cluster (how many worker nodes are in the cluster?) # **6**
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) # Spring Boot & Angular based MS (10 Services)
- Others:

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
