### ISSUE TITLE
Upgrade to 1.8.2 failed

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#83]
Deployment failed. Correlation ID: b75ffee4-f9e7-4d58-9f52-dec1be52362e. Operation failed with status: 200. Details: Resource state Failed

Was on 1.8.1 and upgraded to 1.8.2

Had cockroachdb and azure wordpress installed though helm before upgrade

**Comment by AceHack** [comment]
I can't access browse anymore either

**Comment by AceHack** [comment]
Oh I also had OMS integrated and working before upgrade.

**Comment by dmitsh** [comment]
Could you provide more details?
 - region
 - resource group name

**Comment by AceHack** [comment]
I deleted the cluster and started over because it completely hung up my testing.  It was eastus and the resource group name was rgp-use-arch-dev or rgp-use-arch-aks, I don't remember which one now.

I also had the OBSA and ACI connector installed too, I just installed pretty much everything in the Azure AKS documentation and then also a bunch of helm charts, then tried to upgrade and it failed.

**Comment by dmitsh** [comment]
I can see some log traces, but not all of it.
I would like to reproduce this scenario. Could you share your deployment files?

**Comment by dmitsh** [comment]
In general, upgrade might fail because of intermittent issues such as resource allocation, etc.
The upgrade operation is designed to be idempotent, so if it fails, it could be re-tried.

**Comment by AceHack** [comment]
I retried it several times and it failed every time.  I was running helm charts for the most part so there were no deployment files really, just a bunch of helm command lines.  Also I followed the AKS guide fully and deployed everything from that including like OBSA and Azure Wordpress, etc...

**Comment by argoneus** [comment]
I also experienced this error, attempting to upgrade from 1.7.7 to 1.8.4.

`Deployment failed. Correlation ID: a9e96d31-7e23-4f75-8d44-52be31e5b05e. Operation failed with status: 200. Details: Resource state Failed`

Location is eastus.

**Comment by msdotnetclr** [comment]
Experiencing this issue, too.
```bash
~$ az aks upgrade -g RG_AKS_PRESTO -n presto -k 1.8.2
Kubernetes may be unavailable during cluster upgrades.
Are you sure you want to perform this operation? (y/n): y
Deployment failed. Correlation ID: 67975290-12cb-4c35-9adc-ccd4c836b23c. Operation failed with status: 200. Details: Resource state Failed
$ az aks get-versions -g RG_AKS_PRESTO -n presto
{
  "id": "/subscriptions/1b9b4d90-6fcc-447d-9952-acd4aeebf764/resourcegroups/RG_AKS_PRESTO/providers/Microsoft.ContainerService/managedClusters/presto/upgradeprofiles/default",
  "name": "default",
  "properties": {
    "agentPoolProfiles": [
      {
        "kubernetesVersion": "1.8.2",
        "name": null,
        "osType": "Linux",
        "upgrades": [
          "1.8.2"
        ]
      }
    ],
    "controlPlaneProfile": {
      "kubernetesVersion": "1.8.2",
      "name": null,
      "osType": "Linux",
      "upgrades": [
        "1.8.2"
      ]
    }
  },
  "resourceGroup": "RG_AKS_PRESTO",
  "type": "Microsoft.ContainerService/managedClusters/upgradeprofiles"
}
```

**Comment by AceHack** [comment]
@argoneus I don't think 1.8.4 is available, I only see 1.8.2.

**Comment by argoneus** [comment]
@AceHack thanks! I was able to upgrade to 1.8.2 without issues.

**Comment by dmitsh** [comment]
Still troubleshooting. Did you add a subnet to resource group?

**Comment by AceHack** [comment]
@dmitsh No, I had not manually done any changes to the resource group.

**Comment by msdotnetclr** [comment]
@dmitsh I did change the subnet so it does not use up the entire 10.0.0.0/8 block, so I could add a new gateway subnet for VPN connectivity. Do you think it could be the reason of the upgrade failure?

I later faced a problem that I could not scale the cluster because there was a failed upgrade. I had to delete the cluster and recreate it with version 1.8.2, and re-did the vnet changes since then.

**Comment by dmitsh** [comment]
@msdotnetclr Right, that was the reason. In general, if a user manually changes something in the underlying resource group (the resource group that has been automatically created during cluster deployment), the consequences are unknown. This also invalidates SLA.

**Comment by AceHack** [comment]
@dmitsh FYI I had not made any manual changes when mine had failed.  What about adding adding dns alias to dynamic IP? Is that that supported? I.e. cloudapp addresses?

**Comment by dmitsh** [comment]
@AceHack I'm having difficulties accessing the logs for December 18th, the date you reported upgrade failure. Have you tried to create another cluster and upgrade it?

**Comment by AceHack** [comment]
@dmitsh Yes, I created another cluster and upgraded it just fine but I just upgraded a fresh cluster with no other software installed.  One weird thing I was experiencing when the failure happened was I had installed virtual-kubelet i.e. aci connector and it had caused problems creating a load balancer, the external IP just said pending forever.  I tried the upgrade with this failure in place.

**Comment by dmitsh** [comment]
@AceHack During upgrade operation we are adding and removing VMs to/from the vnet. If the vnet is in an unhealthy state (as in your case), the upgrade will fail.

**Comment by seanknox** [comment]
Closing due inactivity. Feel free to re-open if still an issue.
