### ISSUE TITLE
Meterics server version 

### ISSUE THREAD

**Issue by Brijak0** [Azure/AKS#831]
**What happened**:
I wanted to update the meterics server on my Azure AKS cluster to a version 0.3.1, but AKS keeps overwritting the version with an older version 0.2.1 - why?

**What you expected to happen**:
An update of the meterics server.
**How to reproduce it (as minimally and precisely as possible)**:
Create a AKS cluster try to deploy an update the meteric server. Note using the kubectl create commands fails, you will need to use apply, even though meterics server specifies usage of the create command.   

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`): 1.11.5
- Size of cluster (how many worker nodes are in the cluster?) 3 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others: Own developed asp .netcore services

**Comment by jnoller** [comment]
The Kubernetes API server, CoreDNS/Kube-dns, metric server, etc are managed components. Specifically the AKS team pins to specific versions to ensure quality and supportability across the fleet. Users can not mutate the versions of these components as that would render the cluster unsupportable.

Generally to get a new version of these components, you can upgrade to newer AKS releases (Such as the kubernetes 1.12.x upgrade). We use the addon manager behind the scenes to consistent restore the known, working version(s) of these components.

If you require this level of control and customization, we recommend you use the aks-engine project (https://github.com/Azure/aks-engine) as AKS is a managed service and as such, we limit the number of customizations available.
