### ISSUE TITLE
Unable to automatically remove completed Kubernetes Jobs in AKS

### ISSUE THREAD

**Issue by guptayuvraj** [Azure/AKS#833]
**What happened**: As per Kubernetes documentation, they have added support to automatically delete a completed Kubernetes job by adding ttlSecondsAfterFinished variable in the Kubernetes Job yaml file. (https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/). However, upon using AKS and adding the variable in my yaml file, I am unable to see the observed behaviour of the job getting deleted in Kubernetes.

**What you expected to happen**: The job should have been deleted from the Kubernetes cluster after running kubectl get all command.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a yaml file to deploy Kubernetes Job.
2. Add variable of ttlSecondsAfterFinished under spec with a specified value.
3. Deploy/Run the kubernetes job.
4. After the value specified in ttlSecondsAfterFinished, the Kubernetes job should be deleted from the Kubernetes cluster after running kubectl get all command or kubectl get jobs command.

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?) 
1 Node

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Basic Python Job

**Comment by benclapp** [comment]
According to the [feature gate docs](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/), this feature is alpha and disabled by default in all Kubernetes clusters, AKS or otherwise.

**Comment by guptayuvraj** [comment]
@benclapp Is there a way I can enable it in AKS?

**Comment by jnoller** [comment]
@guptayuvraj Alpha features are not supported on AKS at this time. Enabling this could destabilize your cluster, and technical support will be unable to diagnose and root-cause issues related to this. We do not recommend Alpha feature usage on AKS at this time.
