### ISSUE TITLE
Kubernetes upgrade to 1.12.5 leads to cluster troubles

### ISSUE THREAD

**Issue by MXClyde** [Azure/AKS#837]
**What happened**:

After upgrade to k8s 1.12.5, cluster lost ability to update load balancers in Azure and connectivity between nodes/pods. Root cause seems to be incorrect provisioning of the service principle to the new nodes.

Sample error on upgrading LB:

azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxx-xxx-xx/resourceGroups/MC_mx-esg-gapp-cluster_mx-esg-gapp-cluster_westeurope/providers/Microsoft.Network/loadBalancers?api-version=2017-09-01: StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 47587c82-xxxx-4c66-9031-daff16fd6300\r\nCorrelation ID: 3e8xxx7c-6a9c-4d11-a62d-0ffd017743cd\r\nTimestamp: 2019-02-18 20:11:42Z","error_codes":[7000215],"timestamp":"2019-02-18 20:11:42Z","trace_id":"47587c82-xxx3-4c66-9031-daff16fd6300","correlation_id":"3exxxxxxc-6a9c-4d11-a62d-0ffd017743cd"}

Example connectivity issues (example from metrics server, but many pods show this):

E0218 20:13:15.442827       1 summary.go:97] error while getting metrics summary from Kubelet aks-nodepool1-20071812-2(10.240.0.6:10255): Get http://10.240.0.6:10255/stats/summary/: dial tcp 10.240.0.6:10255: getsockopt: connection timed out

**What you expected to happen**:

Upgrade without glitches.

**How to reproduce it (as minimally and precisely as possible)**:

Just upgrade to 1.12.5.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.5
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Java
- Others:

**Comment by przemolb** [comment]
I have similar issue.

**Comment by jnoller** [comment]
Please file a support ticket in the azure portal so we can get on call engineering to take a look, we can not ask for the subscription and cluster information needed on github

**Comment by MXClyde** [comment]
Support ticket is #119021825003223

**Comment by joaocc** [comment]
We are also facing a similar issue when upgrading from 1.11.5 to 1.11.7 on our dev cluster.

Besides this error, we also stopped being  able to access the Azure Container Registry service (which was running fine under the prev version).

**Comment by andyzhangx** [comment]
@joaocc about the `Azure Container Registry`, pls make sure your current service principal of AKS could access ACR, you could check by:
https://github.com/andyzhangx/demo/blob/master/issues/acr-issues.md#how-to-check-whether-current-service-principal-could-access-acr

**Comment by joaocc** [comment]
@andyzhangx It was working flawlessly before the upgrade.
It seems to be related to ServicePrincipal credentials having expired, as per Azure Support indications
Thx

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
