### ISSUE TITLE
Only one GPU visible on larger NC machine sizes

### ISSUE THREAD

**Issue by jberezanski-mdg** [Azure/AKS#839]
**What happened**:

After creating an AKS cluster with larger NC VM sizes (NC12, NC24), only one GPU is visible and usable on each node. `kubectl` shows 1 as the amount of available `nvidia.com/gpu` resources. This happens on all NC generations (first, v2 and v3), making it pointless to use NC machines larger than NC6 in AKS.

**What you expected to happen**:

Each node should expose the [correct number of GPUs](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-gpu) (NC12 - 2 GPUs, NC24 - 4 GPUs), so that the same amount of GPU-enabled pods can be scheduled to the node (or a single pod may request more than one GPU).

(Just to be clear, I'm not asking for a way of sharing/dividing a single GPU between multiple pods.)

**How to reproduce it (as minimally and precisely as possible)**:

```powershell
# (PowerShell)
# assume an existing resource group named "test-rg" in the East US location
# create an AKS cluster with one NC12s v2 node
$aks = New-AzAks -ResourceGroupName test-rg -Name test-aks -KubernetesVersion '1.11.7' -NodeCount 1 -NodeVmSize Standard_NC12s_v2 -SshKeyValue (Get-Content -Path .\${Env:UserName}.pub.txt)
$aks | Import-AzAksCredential
# for Kubernetes 1.12:
# kubectl create namespace gpu-resources
# notepad .\nvidia-device-plugin-ds.yaml
# kubectl apply -f .\nvidia-device-plugin-ds.yaml

# view available resources
kubectl describe nodes
<#
output - note only one gpu resource:

(...)
Addresses:
  Hostname:    aks-default-39075687-0
  InternalIP:  10.240.0.4
Capacity:
 attachable-volumes-azure-disk:  48
 cpu:                            12
 ephemeral-storage:              30428648Ki
 hugepages-1Gi:                  0
 hugepages-2Mi:                  0
 memory:                         115515408Ki
 nvidia.com/gpu:                 1
 pods:                           110
Allocatable:
 attachable-volumes-azure-disk:  48
 cpu:                            11901m
 ephemeral-storage:              28043041951
 hugepages-1Gi:                  0
 hugepages-2Mi:                  0
 memory:                         106647568Ki
 nvidia.com/gpu:                 1
 pods:                           110
(...)
#>

# ssh to the node (https://docs.microsoft.com/en-us/azure/aks/ssh)

# deploy a temporary pod to use as jump host
kubectl run -it --rm aks-ssh --image=debian

# in a new PowerShell console, copy ssh private key to the jump host pod
$sshPod = kubectl get pods | Select-Object -Skip 1 | Select-String -Pattern '^aks-ssh[^\s]+' | ForEach-Object { $_.Matches[0].Groups[0].Value }
kubectl cp "./${Env:UserName}.pk.txt" "${sshPod}:/id_rsa"

# back to the previous console, in the jump host pod:
apt-get update && apt-get install openssh-client -y
chmod 0600 id_rsa
ssh -i id_rsa azureuser@10.240.0.4    # the InternalIP obtained earlier

# only one GPU is visible:
azureuser@aks-default-39075687-0:~$ /usr/local/nvidia/bin/nvidia-smi -L
GPU 0: Tesla P100-PCIE-16GB (UUID: GPU-6592cdde-e1e0-b92a-ef31-4570dced058e)
```

**Anything else we need to know?**:
The correct number of GPUs is visible when creating a Linux Data Science VM of the same size:

```PowerShell
$rgloc = @{ ResourceGroupName = 'test-rg'; Location = 'eastus' }
$subnetConfig = New-AzVirtualNetworkSubnetConfig -Name test-subnet -AddressPrefix '10.0.0.0/24'
$vnet = New-AzVirtualNetwork -Name test-vnet -AddressPrefix '10.0.0.0/16' -Subnet $subnetConfig @rgloc
$pip = New-AzPublicIpAddress -Name test-vm-ip -AllocationMethod Dynamic @rgloc
$nic = New-AzNetworkInterface -Name test-vm-nic -SubnetId $vnet.Subnets[0].Id -PublicIpAddressId $PIP.Id @rgloc
Get-AzMarketplaceTerms -Publisher microsoft-ads -Product linux-data-science-vm-ubuntu -Name linuxdsvmubuntu | Set-AzMarketplaceTerms -Accept
$vm = New-AzVMConfig -VMName test-vm -VMSize Standard_NC12s_v2
$vm = Set-AzVMOperatingSystem -VM $vm -Linux -ComputerName test-vm -Credential (Get-Credential -Credential vmadmin)
$vm = Add-AzVMNetworkInterface -VM $vm -Id $nic.Id
$vm = Set-AzVMSourceImage -VM $vm -PublisherName microsoft-ads -Offer linux-data-science-vm-ubuntu -Skus linuxdsvmubuntu -Version '19.01.03'
$vm = Set-AzVMPlan -VM $vm -Publisher microsoft-ads -Product linux-data-science-vm-ubuntu -Name linuxdsvmubuntu
New-AzVM -VM $vm @rgloc

ssh ('vmadmin@{0}' -f (Get-AzPublicIpAddress -Name test-vm-ip -ResourceGroupName $rgloc.ResourceGroupName).IpAddress)

# two GPUs are visible, as expected:
vmadmin@test-vm:~$ nvidia-smi -L
GPU 0: Tesla P100-PCIE-16GB (UUID: GPU-ba1c2f4a-bda2-e408-d5b4-f2f36ba28e78)
GPU 1: Tesla P100-PCIE-16GB (UUID: GPU-ff44166c-b629-9059-386c-e42671c81342)
```

**Environment**:
- Kubernetes version (use `kubectl version`): tested on server (AKS) version 1.11.7 and 1.12.5
- Size of cluster (how many worker nodes are in the cluster?): tested on 1 and 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): machine learning (deploying Machine Learning Service webservices)

**Comment by msalvaris** [comment]
@jberezanski-mdg Did you manage to get around this issue?

**Comment by jberezanski-mdg** [comment]
No, I have not. Right now I'm planning to use single-GPU nodes only. Fortunately, in my workload a single request is easily handled by just one GPU core. (I'm not happy that I need to provision a new node for each additional instance of my service, however.)

**Comment by brendandburns** [comment]
@msalvaris if you get a chance, can you run:

`lspci | grep -i vga` 

and

`dmesg | NVRM`

on the machine and see what it reports? 

Thanks!

**Comment by jberezanski-mdg** [comment]
```
azureuser@aks-default-20518994-0:~$ lspci | grep -i vga
0000:00:08.0 VGA compatible controller: Microsoft Corporation Hyper-V virtual VGA
azureuser@aks-default-20518994-0:~$ dmesg | grep NVRM
[  168.816928] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  396.26  Mon Apr 30 18:01:39 PDT 2018 (using threaded interrupts)
```

**Comment by jberezanski-mdg** [comment]
On a Linux Data Science NC6s_v2 VM, where two GPUs are visible (as they should), the output differs only in the minor version of the driver:
```
vmadmin@test3-vm:~$ lspci | grep -i vga
0000:00:08.0 VGA compatible controller: Microsoft Corporation Hyper-V virtual VGA
vmadmin@test3-vm:~$ dmesg | grep NVRM
[   20.588149] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  396.44  Wed Jul 11 16:51:49 PDT 2018 (using threaded interrupts)
```

**Comment by brendandburns** [comment]
Actually, I found out there was a regression in the Azure kernel. The new azure kernel:

https://packages.ubuntu.com/xenial/kernel/linux-image-4.15.0-1039-azure

Should fix this.

**Comment by msalvaris** [comment]
@jberezanski-mdg Can confirm that it does

**Comment by jberezanski-mdg** [comment]
Yes, it looks like it does. I just booted up the same node I examined yesterday (which was turned off for the night) and kubectl shows the updated kernel and the correct amount of GPU resources:

```
Allocatable:
 cpu:                11901m
 ephemeral-storage:  28043041951
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             219233244Ki
 nvidia.com/gpu:     2
 pods:               110
System Info:
 Machine ID:                 d89f91cc5fd549479b09fa717eb8d39b
 System UUID:                AC686BC9-C865-8F4B-BE39-797F9FF0796D
 Boot ID:                    c3a17aa4-653a-42a2-9fe5-80c848009bb7
 Kernel Version:             4.15.0-1039-azure
 OS Image:                   Ubuntu 16.04.5 LTS
```

and on the node:

```
azureuser@aks-default-20518994-0:~$ /usr/local/nvidia/bin/nvidia-smi -L
GPU 0: Tesla P100-PCIE-16GB (UUID: GPU-308aa3cb-5533-8839-2f2f-8bf4289c84df)
GPU 1: Tesla P100-PCIE-16GB (UUID: GPU-b63be499-0bcf-f99e-0c7f-d05d81ab77e8)
```

**Comment by jberezanski-mdg** [comment]
I will test it further by actually scheduling some GPU workloads, but it looks promising.

**Comment by msalvaris** [comment]
Tested it with multi-GPU workload and all seems good to me

**Comment by jberezanski-mdg** [comment]
OK, a new AKS cluster (K8s version 1.11.7) still creates nodes with kernel 4.15.0-1037-azure and only one GPU visible. I'm not sure how to force node kernel upgrade.

**Comment by jberezanski-mdg** [comment]
After manually installing updates and rebooting the node, the correct GPU number shows up. I was able to run multiple GPU pods as well as run one pod with multiple GPUs. :thumbsup:

**Comment by msalvaris** [comment]
I installed Kured and it updated the kernel that evening https://docs.microsoft.com/en-us/azure/aks/node-updates-kured

**Comment by jberezanski-mdg** [comment]
Yes, it did for me too (eventually). I'm still looking for a way to ensure a newly created cluster (in a CI/CD workflow) is immediately provisioned with the full GPU capability.

**Comment by msalvaris** [comment]
Hopefully soon by default they will be on the new Kernel.

**Comment by jnoller** [comment]
The VHD was updated with the new Kernel:
https://github.com/Azure/aks-engine/blob/master/releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201903_2019.03.15.txt

This means clusters built with this week's CVE release: https://github.com/Azure/AKS/releases/tag/2019-04-04

And all clusters from this point on will get the new fixed kernel.
