### ISSUE TITLE
Timeout connecting to cluster

### ISSUE THREAD

**Issue by toddweb** [Azure/AKS#84]
kubectl commands (kubectl get nodes) are failing again all of a sudden in powershell, bash, and the azure cloud shell with the following error:

> Error from server (Timeout): the server was unable to return a response in the time allotted, but may still be processing the request

**Comment by slack** [comment]
Is `kubectl` still failing for your cluster?

**Comment by toddweb** [comment]
@slack No it seems to be working now. Any explanation of the issue? long time to be down

**Comment by slack** [comment]
If you could send cluster information to me (subscription, resource group) I can look for underlying events that would explain the apiserver failing its healthcheck. jason.hansen@microsoft.com

**Comment by seanknox** [comment]
Closing due inactivity. Feel free to re-open if still an issue.
