### ISSUE TITLE
Request: Watchdog restart/redeploy the AKS VMs

### ISSUE THREAD

**Issue by alanjcastonguay** [Azure/AKS#840]
**What happened**:

I believe existing health-checking stuff in AKS and/or Kubernetes tries to talk to dockerd periodically (can start container? can list containers?). If that doesn't work, the dockerd process is killed and restarted.

In #838 the AKS Node's dockerd stopped responding. However, in that case a `kill -9` of the dockerd process is ignored -- the process is blocked on an uninterruptible syscall that would never complete. A graceful reboot (eg; `reboot`) would also timeout waiting for dockerd to exit.

**What you expected to happen**:

Watchdog of kubelet/dockerd health from outside the VM which can swing a bigger hammer: Reset or redeploy the VM.

This kind of feature takes advantage of the fact that there's always going to be VMs, just like the scale knobs do.

(There is the possibility that a VM redeploy won't help, of course. And if so this could result in station with VMs oscillating uselessly through redeploys, just like the dockerd process may oscillate uselessly through service restarts today. But like that process-level watchdog, it's probably better than being unresponsive for sufficiently long period of time.)

**How to reproduce it (as minimally and precisely as possible)**:

Assume existence of a dockerd blocking on IO or some kernel spinlock or other long-running syscall. Kubernetes sees the node go NotReady. `docker ps` hangs. `kill -9 $(cat /run/docker.pid)` does nothing. `reboot` times out.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.7
- Size of cluster (how many worker nodes are in the cluster?) 8
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) HTTP miroservices in python/node/go
- Others:

**Comment by alanjcastonguay** [comment]
An alternative buff to the inside-vm watchdog script; after slaying dockerd doesn't work it could do something like

```
echo 1 > /proc/sys/kernel/sysrq 
echo s > /proc/sysrq-trigger
echo u > /proc/sysrq-trigger
echo b > /proc/sysrq-trigger
```

**Comment by alanjcastonguay** [comment]
This is very similar to #1003

**Comment by jluk** [comment]
Closing this as I believe the functionality being asked for will be captured by node auto-repair as mentioned in previous comment. Please direct feedback onto that issue if there is a scenario you believe not covered by the feature, thank you @alanjcastonguay for the feedback! Closing to avoid the dupe.
