### ISSUE TITLE
Setting service.spec.externalTrafficPolicy to Local

### ISSUE THREAD

**Issue by RehanSaeed** [Azure/AKS#844]
When setting `service.spec.externalTrafficPolicy` to `Local`, the official [docs](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/) mention:

> GCE/AWS load balancers do not provide weights for their target pools.
> 
> With the new functionality, the external traffic will not be equally load balanced across pods, but rather equally balanced at the node level (because GCE/AWS and other external LB implementations do not have the ability for specifying the weight per node, they balance equally across all target nodes, disregarding the number of pods on each node).
> 
> We can, however, state that for NumServicePods << NumNodes or NumServicePods >> NumNodes, a fairly close-to-equal distribution will be seen, even without weights.
> 
> Once the external load balancers provide weights, this functionality can be added to the LB programming path. Future Work: No support for weights is provided for the 1.4 release, but may be added at a future date

What is the situation with Azure AKS? Does AKS support proper weighted load spreading? Is there any negative impact to setting `service.spec.externalTrafficPolicy` to `Local`?

**Comment by jnoller** [comment]
This should work the same on AKS. The upstream docs are written by the community and Azure being omitted is accidental.
