### ISSUE TITLE
Add Support for a KMS provider for Encrypting Secrets

### ISSUE THREAD

**Issue by RehanSaeed** [Azure/AKS#845]
According to https://github.com/Azure/kubernetes-kms:

> We have added this feature to aks-engine so that you do not have to worry about any of the manual steps to set this up.

Does this mean Azure AKS encrypts secrets by default? I don't see a Key Vault being setup in the AKS resource group, so where are the keys stored? The above link also says:

> Currently KMS plugin for Kubernetes does not support KMS key rotation scenarios.

So keys are never rotated and hard coded from the start?

**Comment by dstrebel** [comment]
KMS is only available on AKS-Engine and not currently supported in AKS.

**Comment by RehanSaeed** [comment]
Updated title to be a feature request.

**Comment by bitsofinfo** [comment]
any timeline for when this will be available?

**Comment by jnoller** [comment]
@bitsofinfo Not at this time. We will be publishing a 6-12 month roadmap on this repo and we're discussing KMS / disk encryption and other requests.

**Comment by erewok** [comment]
Does this request relate to the [keyvault-flexvol project](https://github.com/Azure/kubernetes-keyvault-flexvol)?

**Comment by coreywagehoft** [comment]
Support for KMS would great effect my company from moving to AKS from aks-engine or another cloud provider.  It would be great if this were prioritized.

**Comment by stewartadam** [comment]
The Azure/kubernetes-kms README states that AKS does secret encryption at rest, but does so without KMS. However, I can't find any reference to that in the [AKS docs](https://docs.microsoft.com/en-us/azure/aks/concepts-security#kubernetes-secrets) and given this issue was deferred to the AKS+KMS feature request -- can we clarify what the current state is?

**Comment by zuehlke-dea** [comment]
We would also be interested in knowing that AKS does so.

**Comment by bitsofinfo** [comment]
not stale

**Comment by dhei** [comment]
Hello AKS folks,

Any update of when AKS will support KMS provider? This issue has been opened for almost 2 years, it would be great to get an ETA on this feature request.

Thank you.

**Comment by miwithro** [comment]
We are hoping to have a Public Preview by the end of Q3 2021.

**Comment by mosabami** [comment]
@miwithro do you have an updated ETA for this item?

**Comment by miwithro** [comment]
Targeting March 2022.

**Comment by PixelRobots** [comment]
Docs page https://docs.microsoft.com/en-us/azure/aks/use-kms-etcd-encryption

**Comment by GeorgeB66** [comment]
@miwithro do you know when this is likely to become GA? 
Many Thanks

**Comment by miwithro** [comment]
@JasonWhall thanks for the ask.  This would entail a very large engineering effort on the part of AKS and we have not seen alot of customer demand for this level of integration.  We will definetly continue to track this ask, and if there is further demand to decrease the implementation complexity, we can put this on our list.

**Comment by CocoWang-wql** [comment]
KMS integrated with AKS cluster is GA.
It allows us to enable encryption at rest for Kubernetes secrets in etcd using Azure Key Vault with the Key Management Service (KMS) plugin.
https://docs.microsoft.com/en-us/azure/aks/use-kms-etcd-encryption
