### ISSUE TITLE
Is it possible to have multi-master in AKS?

### ISSUE THREAD

**Issue by ryanlovett** [Azure/AKS#852]
The API server failed for us today. Is it possible to have multiple masters in AKS [as in aks-engine](https://github.com/Azure/aks-engine/blob/master/examples/multiple-masters/kubernetes-3-masters.json#L7).

This was also asked in #198.

**Comment by jnoller** [comment]
@ryanlovett we’re looking at this as we speak - did you file a support ticket? We have to examine the back end to see which components are being overloaded.

**Comment by ryanlovett** [comment]
Yep, I created the ticket yesterday. Was told:

> I reviewed the status of the cluster from backend and found some issues with apiserver/etcd
> I'll engage backend team to help look into this.

and when the master was responding again:

> Glad to hear it. There seems to be some issues within that region. They just mitigated it and will publish root cause later.

**Comment by jnoller** [comment]
Ah, so the ask is multiple masters across regions or fault domains since this was a service outage in a give region, and not API server overload.

**Comment by alanjcastonguay** [comment]
My needs may not match those of @ryanlovett but I'm looking for api master to be available across multiple fault domains (don't need multi-region - that's what multiple clusters are for).

#198 was specifically looking for *documentation* on the current architecture - that never manifested.

**Comment by ryanlovett** [comment]
@jnoller I should have also said that we were able to create, and pivot to, a new cluster in the same region during this outage. Short term I'd be happy with HA master in same region (what @alanjcastonguay said).

**Comment by jemag** [comment]
The documentation on the current master node setup is quite lackluster. 

I could not find any official documentation regarding the master(s) node(s) availability, whether it is on 1 or multiple VMs/fault domains, etc.

From various comments, I can only assume that it is running only a single master node and that there are no possibilities to augment that master node availability.

More documentation on this particular issue would be greatly appreciated. I also think that having multiple master nodes across fault domains should definitely be a possible option.

**Comment by jstafford5380** [comment]
A multi-master quorum would be game changing imo. For example, you have an east cluster and a west cluster. The masters for each talk to each other to coordinate workloads between regions. So if service A in the east region is unavailable, those requests can be served by the west region cluster. If any master goes down, the remaining masters can pick up the slack. I guess the challenge here would be peering those internal networks.

Bonus points for applying the same idea to deployments. For example, I deploy service A to any of the masters and it will roll out across all clusters, simplifying CICD.

**Comment by rajivml** [comment]
The multi master thing, is it now supported ?
