### ISSUE TITLE
Azure Portal let you create 2 aks cluster on the same subnet 

### ISSUE THREAD

**Issue by RotemEmergi** [Azure/AKS#853]
Hi ,

Azure Portal let you create 2 aks cluster on the same subnet after you choose advanced configuration under the Network scoop  .

How to reproduce it :
1. Add new aks.
2. Choose network scoop and then advanced network .
3. Choose exists virtual network .

You can see that the subnet/Kubernetes DNS/Kubernetes service cluster IPs not change and  can choose  same setting .

Best Regards

**Comment by RotemEmergi** [comment]
Hi , 

Any update ?

**Comment by jnoller** [comment]
Not yet, we'll be blocking this in a March release and it will be in the release notes

**Comment by jnoller** [comment]
This should now be patched/mitigated/blocked
