### ISSUE TITLE
AKS: deleted node not counted when scaling up

### ISSUE THREAD

**Issue by swapzero** [Azure/AKS#854]
**What happened**:
- for example, a scale up from 5 -> 7 did not take into consideration that one node was already out of cluster(drained and deleted) => added only 2 nodes

**What you expected to happen**:
- to have 7 nodes available

**How to reproduce it (as minimally and precisely as possible)**:
- create a 5 nodes cluster
- drain and delete node 5
```
kubectl drain aks-node-27255451-4
...

kubectl get nodes
NAME                  STATUS                     ROLES   AGE    VERSION
aks-node-27255451-0   Ready                      agent   153m   v1.12.5
aks-node-27255451-1   Ready                      agent   152m   v1.12.5
aks-node-27255451-2   Ready                      agent   153m   v1.12.5
aks-node-27255451-3   Ready                      agent   65m    v1.12.5
aks-node-27255451-4   Ready,SchedulingDisabled   agent   66m    v1.12.5

kubectl delete node aks-node-27255451-4
...
kubectl get nodes
NAME                  STATUS   ROLES   AGE    VERSION
aks-node-27255451-0   Ready    agent   154m   v1.12.5
aks-node-27255451-1   Ready    agent   153m   v1.12.5
aks-node-27255451-2   Ready    agent   154m   v1.12.5
aks-node-27255451-3   Ready    agent   66m    v1.12.5
```
- go to portal and scale to 7 nodes
- once finished, get the nodes
```
kubectl get nodes
NAME                  STATUS   ROLES   AGE    VERSION
aks-node-27255451-0   Ready    agent   171m   v1.12.5
aks-node-27255451-1   Ready    agent   170m   v1.12.5
aks-node-27255451-2   Ready    agent   171m   v1.12.5
aks-node-27255451-3   Ready    agent   83m    v1.12.5
aks-node-27255451-5   Ready    agent   12m    v1.12.5
aks-node-27255451-6   Ready    agent   12m    v1.12.5

```
Result: instead of 7 nodes, there are 6

**Environment**:
- kubernetes 1.12.5
- "azure" network plugin

**Comment by AlexandruSimandi** [comment]
i got the same thing in v1.8

**Comment by feiskyer** [comment]
`kubectl delete node aks-node-27255451-4` this only deletes the node object from Kubernetes API, but not Azure resources (e.g. virtual machine and its storage/network interface).

**Comment by jluk** [comment]
@swapzero is this still occurring for you and are you using a VMAS or VMSS backed cluster?

**Comment by jluk** [comment]
@swapzero I'm closing this due to no response for 3 weeks, if you still see this reproduce on a 1.13 or 1.14 version please open a new ticket. Thanks!
