### ISSUE TITLE
Pod deployment after scaling nodes fails with a 504 Gateway timeout error

### ISSUE THREAD

**Issue by sNathan13** [Azure/AKS#857]
**What happened**:
Pod deployment after scaling nodes in the AKS cluster fails with a 504 Gateway timeout error
**What you expected to happen**:
Web apps to be accessible.
**How to reproduce it (as minimally and precisely as possible)**:
Deploy an AKS cluster with internal lb using nginx/helm chart with node-count=1. (https://docs.microsoft.com/en-us/azure/aks/ingress-internal-ip) 

Deploy a simplehello world app with replica = 1

Accessing the app works as expected

Scale the cluster using the following command
az aks scale --resource-group <> --name <> --node-count 3 --nodepool-name <>

Scale the deployment of helloworld app by 
 kubectl scale deployment <app> --replicas=3

Delete the pod deployed during initial cluster creation before scaling

Accessing the app throws 504

**Anything else we need to know?**:
This is a private AKS cluster accessible within corporate n/w. 

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?) 1

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) 
Ruby on Rails apps
- Others:

**Comment by AlexandruSimandi** [comment]
check if the dns on the new node is healthy

**Comment by sNathan13** [comment]
@AlexandruSimandi yes they are healthy. I am going to try with a different subscription to rule out resource limitations. I will keep the thread posted with my findings. Thanks.

**Comment by sNathan13** [comment]
I moved to Name based virtual hosting and haven't seen the 504 error. I am closing this issue for now.

**Comment by paviad** [comment]
@sNathan13 can you please describe your solution? What is Name based virtual hosting?
