### ISSUE TITLE
Sporadic failure when starting port forwarding

### ISSUE THREAD

**Issue by xinyanmsft** [Azure/AKS#858]
**What happened**:
This only happens with certain clusters. The repro I have access to is: https://akscluster-akscluster-0228--412cb3-d651d464.hcp.canadaeast.azmk8s.io:443. 

We are creating a WebSocket object for port-forwarding. With this cluster, the call to create the WebSocket fails randomly. The repro code uses Kubernetes client library, which can be found / adopted here:
  https://github.com/kubernetes-client/csharp/blob/master/examples/portforward/PortForward.cs

With the above cluster, if I do a for-loop and invoke WebSocketNamespacedPodPortForwardAsync() method 10 times, typically it will fail with the 1st, 3rd, 5th, 7th, 9th time, and succeed in other cases. In the failure case, the error is caused by the below request returns 401/403, instead of a web socket switching protocol response. 

{wss://akscluster-akscluster-0228--412cb3-d651d464.hcp.canadaeast.azmk8s.io/api/v1/namespaces/default/pods/nj-webfrontend-1-6984f4df4d-zv29k/portforward?ports=80}

A sample failed response is 403, with header:
{Server: nginx/1.15.5
Date: Thu, 28 Feb 2019 21:46:18 GMT
Connection: keep-alive
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=15724800; includeSubDomains
}

**What you expected to happen**:
The above request should succeed at all times.

**How to reproduce it (as minimally and precisely as possible)**:
Use the sample code https://github.com/kubernetes-client/csharp/blob/master/examples/portforward/PortForward.cs. Target cluster akscluster-akscluster-0228--412cb3-d651d464.hcp.canadaeast.azmk8s.io, Add a for loop to call WebSocketNamespacedPodPortForwardAsync 10 times

            WebSocket webSocket = null;
            for (int i = 0; i < 10; i++)
            {
                Console.WriteLine($"i={i}");
                try
                {
                    webSocket = await client.WebSocketNamespacedPodPortForwardAsync(pod.Metadata.Name, "default", new int[] { 80 }, "v4.channel.k8s.io");
                    Console.WriteLine("Okay");
                }
                catch (WebSocketException ex)
                {
                    Console.WriteLine($"Exception {ex.Message}");
                }
            }

**Anything else we need to know?**:
We are start to see this since last of Feb in CanadaEast.

**Environment**:
- Kubernetes version 1.12.5
- Size of cluster (how many worker nodes are in the cluster?) 3 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)  HTTP microservices

**Comment by xinyanmsft** [comment]
should have add the above scenario works as expected with other clusters we have, with same K8s version and same region.

**Comment by jluk** [comment]
@xinyanmsft can you please open a support ticket to dive into this issue if it is still occurring? It's difficult to debug without getting hands on the cluster, I am going to close this issue as a result. Please do open a ticket if needed.
