### ISSUE TITLE
job persists after helm deleted a release

### ISSUE THREAD

**Issue by ryanlovett** [Azure/AKS#86]
I ran `helm delete --purge release_name` but a job persisted:
```
$ kubectl  get all
NAME                            DESIRED   SUCCESSFUL   AGE
jobs/pull--2982b5d-1513645548   3         3            13m


NAME             TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
svc/kubernetes   ClusterIP   10.0.0.1     <none>        443/TCP   4h
```
This was a job created by the helm install. I tried to delete it:
```
$ kubectl  delete job pull--2982b5d-1513645548


error: timed out waiting for "pull--2982b5d-1513645548" to be synced
```

I had to delete the cluster.

**Comment by slack** [comment]
Thanks for opening the issue. Few questions about the job:

* Was the job first created by Helm?
* Was the job still running, or had it exited completely?
* Did you notice any pods stuck in Terminating state for that job?

**Comment by ryanlovett** [comment]
- Yes, the job was first created by helm.
- The job was running when I issued `helm delete`.
- There were no pods stuck in Terminating by this point. 

If this isn't enough to go on, I can try to recreate the original condition.

**Comment by slack** [comment]
If you can get a reliable repro, that would be awesome.

**Comment by slack** [comment]
Closing this issue for now, please re-open if you find a repro.
