### ISSUE TITLE
Changes to the ConfigMap kube-dns are not being reflected

### ISSUE THREAD

**Issue by Newnton** [Azure/AKS#863]
Changes to the ConfigMap kube-dns (in the namespace kube-system) are not being reflected in the running instances of CoreDNS. This is a known issue, reference: 

https://github.com/Azure/AKS/issues/811
https://github.com/Azure/AKS/issues/811#issuecomment-465643538_

**Comment by jnoller** [comment]
You can not change the kube-dns config map on clusters running the CoreDNS system - please see https://github.com/Azure/AKS/releases/tag/2019-02-07
