### ISSUE TITLE
AKS : Call external services with different source ip addresses

### ISSUE THREAD

**Issue by MugosDynamic** [Azure/AKS#866]
**What happened**:
We try to deploy our multi microservice application to aks for a big company. But, company infrastructure team asks us to request their services with certain private ip addresses. We have a vpn connection between company network and azure virtual network. 

For example, we are calling company-service-1, company-service-2 and company-service-3 from one of our microservice, infra team says that, call company-service-1 with XXX.XXX.XXX.121 source ip, call company-service-2 with XXX.XXX.XXX.122 source ip and call company-service-3 with XXX.XXX.XXX.123 source ip. They had defined firewall rules for these ips and don't change them because of some security restrictions. 

We can do that via defining different network interfaces to virtual machine and creating some ip routings like "ip route add XXX.XXX.XXX.YYY/32 via 53.13.39.1 src XXX.XXX.XXX.123". But at that point, we are struggling with network interface addition limit. Because at the end of the day, we are going to call 20 different services with different ips.

So we try to that via egress load balancers. We try to add some loadbalancer via aks and it seems it get true ip addresses. But the problem is we can't define certain ip addresses for certain external endpoints. Every request from pods tries to go company web services directly without visiting load balancers and returning back from firewall with error.

![image](https://user-images.githubusercontent.com/954091/54207309-f978f280-44ea-11e9-9ed1-3b17e5aaca54.png)

Do you have any suggestions about this problem?

**What you expected to happen**:
Calling external services from different source ip addresses inside aks pods.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.13", GitCommit:"954ff68d59e9dc62fa8252ffa9023a90ff8a358c", GitTreeState:"clean", BuildDate:"2019-02-13T11:03:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster:  1 node
- General description of workloads in the cluster:  an application includes multiple java-spring boot microservices

**Comment by jnoller** [comment]
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
