### ISSUE TITLE
ACI pod cannot communicate with other pods

### ISSUE THREAD

**Issue by vedant-khandelwal** [Azure/AKS#868]
**What happened**:

Deployed an AKS cluster with virtual node enabled. The pods running in ACI get IP addresses not in the same range as AKS vnet. The ACI pod has a corresponding service and other pods also have corresponding services. As a result those pods are not able to communicate with other pods running in AKS.

**What you expected to happen**:

ACI pod should be able to communicate with other pods using service names. 

**How to reproduce it (as minimally and precisely as possible)**:

Just create an AKS cluster with virtual node enabled and run pods with services in both AKS nodes and ACI.

**Environment**:
- Kubernetes version : 1.13.5
- Size of cluster : 3 nodes
- General description of workloads in the cluster: HTTP microservices

**Comment by vedant-khandelwal** [comment]
I find that the virtual kubelet pod doesn't have ACI subnet defined, but when I try to edit the deployment, it gets reset and becomes empty so I can't set the subnet. Not sure how it got reset

**Comment by vedant-khandelwal** [comment]
disabled and re-enabled the virtual node feature in the cluster and set the subnet again. But the pod is still unable to discover services running on other nodes in the cluster.

**Comment by srrengar** [comment]
The ACI containers that are created on the virtual node are in their own delegated subnet but all within the same VNet as the AKS cluster. Are you creating the delegated subnet yourself or letting the portal do it for you? What errors are you seeing?

**Comment by vedant-khandelwal** [comment]
Azure created the subnet for me. I just enabled virtual node option on the
portal.

I'm seeing dns resolution failures for FQDN service names in pods running
in ACI

**Comment by srrengar** [comment]
@robbiezhang any reason why this would happen?

**Comment by robbiezhang** [comment]
@vedant-khandelwal  are you using FQDN ([service name].[namespace].svc.cluster.local) or the short form ([service name].[namespace])? Can you resolve public DNS?
Similar issue: https://github.com/virtual-kubelet/virtual-kubelet/issues/456

**Comment by vedant-khandelwal** [comment]
I'm using the FQDN. Could this issue be because we've configured the
kubernetes load balancer to route external requests internally

**Comment by vedant-khandelwal** [comment]
Yes this is still an issue. Can any of you please schedule a call to
discuss this issue? We have been unable to use ACI due to these issues.

**Comment by vedant-khandelwal** [comment]
Yes I have. I have also provided all the information they asked for.
Haven't heard back from them for quite a while now.

**Comment by jluk** [comment]
@vedant-khandelwal I am closing this issue due to 3 weeks since last ask. Please feel free to open another support ticket for this virtual nodes issue, which is better handled through support ticket than github issue anyways. Thanks!
