### ISSUE TITLE
Migrate from heapster to metrics-server. Metrics-server is paused.

### ISSUE THREAD

**Issue by arianitu** [Azure/AKS#869]
**What happened**:

metrics-server is paused somehow, the yaml looks like so:

```
spec:
  paused: true
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 0
```

because metrics-server is paused, I cannot do backups with Velero because of this issue: https://github.com/heptio/velero/issues/1283

I notice that Heapster is running instead of metrics-server. I think this is probably because Azure has an option to use the Kubernetes dashboard and that's not supported yet:

https://github.com/kubernetes/dashboard/issues/2986

So I have a few questions:

1. How do I move to metrics-server from heapster. If I move, I assume `az aks browse ` will stop working and we can no longer use the Kubernetes dashboard.
2. Can I have both metrics-server and heapster running at the same time. Did AKS disable metrics-server for me, or how did that happen?

I also notice I can't use `kubectl top` since that requires metrics-server. Also, we use `helm/prometheus` which uses https://github.com/kubernetes/kube-state-metrics.  I am unsure if that scrapes from Heapster as well and switching might cause issues there.

**Environment**:
AKS v1.11.5

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:47Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?)
6

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

Data cluster (Elasticsearch, etc.)

**Comment by arianitu** [comment]
We've also ran into another issue on AKS. The ClusterRole `cluster-admin` does not exist and is expected to exist. We also have a ClusterRoleBinding `metrics-server:system:auth-delegator` referring to `system:auth-delegator` which does no exist.

This creates a few issues for us when trying to create backups with Velero:

https://github.com/heptio/velero/issues/1403

**Comment by jnoller** [comment]
The role and permissions fixes needed to clear these errors are coming in planned AKS releases in May

**Comment by arianitu** [comment]
@jnoller Thank you, we have RBAC set to False in our cluster. I forgot about that detail, perhaps that's why `system:auth-delegator` does not exist in our cluster?

**Comment by palma21** [comment]
Fixed
