### ISSUE TITLE
Project Calico support

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#87]
Does AKS support the calico?  Seems to need access to the master nodes.
https://docs.projectcalico.org/v2.6/getting-started/kubernetes/

**Comment by slack** [comment]
We will be adding support for K8S Network Policy in early 2018.

**Comment by AceHack** [comment]
@slack when you say adding K8s network policy that's not really answering my question, K8s network policy is very limited as compared to Calico.  Do you mean it will support Calico, flannel, Canal, Weave, or Romana network plugins?  All of them, none of them?  Thanks.

**Comment by AceHack** [comment]
@slack Also why was this closed, do you already support it?  I would think closed means it's done, I see other open roadmap issues.  I am a little confused.  Thanks.

**Comment by slack** [comment]
Sorry, probably shouldn't have closed the issue.

Our use of calico in acs-engine (which is the basis for AKS) uses Calico primarily for network policy, which is why I jumped to conclusion. For example, we use `host-local` IPAM rather than `calico-ipam`. https://docs.projectcalico.org/v3.0/reference/public-cloud/azure

Network policy will likely be implemented via Calico for AKS GA. Still working through the details there.

**Comment by AceHack** [comment]
@slack In the document you reference I see

"Why doesn’t Azure support Calico networking?
Azure does not allow BGP, IPIP traffic, and traffic with unknown source IPs."

Does this mean supporting calico networking is no on the roadmap?

**Comment by AceHack** [comment]
Also when I look at the requirements for installing canal, I see the following:

- The Kubernetes cluster must be configured to provide serviceaccount tokens to pods.
- kubelets must be started with --network-plugin=cni and have --cni-conf-dir and --cni-bin-dir properly set
- The controller manager must be started with --cluster-cidr=10.244.0.0/16 and --allocate-node-cidrs=true.

Are these possible with AKS?

**Comment by slack** [comment]
Full Calico networking is not currently on the roadmap.

**Comment by naumvd95** [comment]
+1 to previous messages, Calico network policies support is planned on 2018?

**Comment by marrobi** [comment]
Cool. Will this work with Azure CNI as well as kubenet?

**Comment by cmendible** [comment]
Hi @slack did network policies made it to the GA? Thanks...

**Comment by kamalgrover** [comment]
@slack : Does AKS GA supports network policies through Project Calico?

**Comment by sauryadas** [comment]
Calico support is coming .. encourage you guys to add feature requests in the link below.

https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks

**Comment by 4c74356b41** [comment]
why do you close this, when is it actually coming? should we just use kube-router or wait couple of weeks?

**Comment by AceHack** [comment]
Yes it would be nice to see a roadmap with this on it.  Thanks.

**Comment by seanmck** [comment]
https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/35146135-support-for-network-policies-with-calico-integrati

**Comment by 4c74356b41** [comment]
thats literally telling everybody in this thread to gtfo as this links gives no data whatsoever.

```
We will be adding support for K8S Network Policy in early 2018.
Full Calico networking is not currently on the roadmap.
Calico support is coming .. encourage you guys to add feature requests in the link below.
Yep! We are working on integration with Calico and expect to have network policy as part of AKS GA.
```

whats the end game?

**Comment by seanmck** [comment]
I've added a comment in the feedback item. The PR is being merged right now and barring something unforeseen, the feature should be available in preview with the first release in 2019, so probably the 2nd week of January.

**Comment by bramvdklinkenberg** [comment]
Any update on when Calico (network policies) will be available?

**Comment by sauryadas** [comment]
You will most definitely have it available next week.. apologies for the delay

**Comment by 4c74356b41** [comment]
this work week or this week? this work week has like 12 hour work time left.

**Comment by cmendible** [comment]
Hi guys any news?

**Comment by 4c74356b41** [comment]
its live in some regions but doesnt work

**Comment by bramvdklinkenberg** [comment]
@4c74356b41 which region? and is automatically deployed with new clusters?

**Comment by seanmck** [comment]
It is rolling out now behind a feature flag. We will publish docs within the next day or two.

**Comment by 4c74356b41** [comment]
@seanmck can you update this thread with docs link? although, i'm not sure what there is to doc, its literally 1 line in the template.

**Comment by khawaga** [comment]
Any updates?

**Comment by chris-cmsoft** [comment]
@khawaga https://docs.microsoft.com/en-us/azure/aks/concepts-network#network-policies

**Comment by 4c74356b41** [comment]
you aware calico breaks `kubectl port-forward`? @chris-cmsoft

**Comment by chris-cmsoft** [comment]
@4c74356b41 Nope. I will check it out. Does it break when applying network policies or straight from provisioning ?

**Comment by 4c74356b41** [comment]
straight from provisioning @chris-cmsoft

**Comment by 4c74356b41** [comment]
https://stackoverflow.com/questions/54424018/only-0-0-0-0-0-block-works-in-ingress-network-policy take a look at this as well, if you can @chris-cmsoft

**Comment by chris-cmsoft** [comment]
I haven't used this extensively yet, so I cannot confirm why yours might not work, although I don't see any other issues popping up in search. 
Have you logged that support ticket ?

**Comment by 4c74356b41** [comment]
no, i usually dont do that. azure support is useless, unfortunately, only waste of my time.

**Comment by jnoller** [comment]
@4c74356b41 please file an azure support ticket, as we’ve invested heavily there as well as direct escalation methods to on call engineering.

**Comment by 4c74356b41** [comment]
deleting my comment wont make azure support any better, unfortunately.

**Comment by sauryadas** [comment]
> you aware calico breaks `kubectl port-forward`?

@feiskyer ^^^

**Comment by 4c74356b41** [comment]
I did report it in #sig-azure on slack, several product group people saw it, how can you not be aware of this?

**Comment by feiskyer** [comment]
> you aware calico breaks kubectl port-forward?

@4c74356b41 Any contexts of why port-forward not working? Port forward is going through kubelet APIs, which shouldn't be affected by calico.

**Comment by 4c74356b41** [comment]
no idea, how would I know, its a black box for me.

**Comment by RehanSaeed** [comment]
Looks like you have to have the Azure CNI plugin, so you have to use Azure's VNET. Is this restriction going to be lifted?

Also, it seems that you have to enable network policy on the AKS cluster via the az CLI. Can this be done using ARM templates?

**Comment by 4c74356b41** [comment]
@RehanSaeed http://4c74356b41.com/post5788

**Comment by feiskyer** [comment]
@RehanSaeed Yep, azure network plugin is required to use the network-policy feature. ARM templates are also working.

@4c74356b41 For issues, please provide the detailed errors, so I can help to dig the issues. (I have actually validated both port-forward and helm are working as expected).

**Comment by RehanSaeed** [comment]
@feiskyer Any plans to lift that restriction and allow network policies without Azure CNI? My scenario is that I have greenfield development with only Azure AKS, so don't need an Azure VNET to connect to other services.

**Comment by feiskyer** [comment]
@sauryadas for roadmaps.

**Comment by sauryadas** [comment]
@RehanSaeed  It is on the roadmap .. cant provide dates yet though.. want to observe CNI + Calico for reliability for the next 4 weeks and get it to GA

**Comment by bramvdklinkenberg** [comment]
Will it, in the future, also be possible to enable calico for existing aks cluster? at this point it is only available for new aks clusters.

**Comment by 4c74356b41** [comment]
probably not in any reasonable amount of time. aks requires redeployment to change pretty much anything
