### ISSUE TITLE
Error creating a AKS cluster 

### ISSUE THREAD

**Issue by GKarmakar** [Azure/AKS#872]
I am following the instructions of the tutorial here and found an error not seems to find an easy solution. Please suggest.
https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough
Command:
az aks create --resource-group myResourceGroup --name myAKSCluster --node-count 1 --enable-addons monitoring --generate-ssh-keys
Error:
The password must contain at least 1 special character. paramName: PasswordCredentials, paramValue: , objectType: Microsoft.Online.DirectoryServices.Application

**Comment by jnoller** [comment]
You used a password that did not meet security requirements. The error message notes you need at least 1 special character:

**The password must contain at least 1 special character. paramName: PasswordCredentials, paramValue: , objectType: Microsoft.Online.DirectoryServices.Application**
