### ISSUE TITLE
Each user has the same "Subject: O = system:masters, CN = masterclient"

### ISSUE THREAD

**Issue by adriancislo** [Azure/AKS#877]
Hi,

I have created Kubernetes cluster with rbac enabled (via portal UI). Then I have created application registrations based on instructions here https://docs.microsoft.com/en-us/azure/aks/aad-integration.

I have reset AADProfile with https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/resetaadprofile by providing in body client and server data

Now I can see everything is ok via https://resources.azure.com. aadProfile is in json.

I want to login user to cluster and see that new user does not have any permission to resources.

I add user to resource group by role assignment (no idea which role I should use here)
If I do not add role assignment for this user then I cannot get-credentials

When I login as this user by `az login` and then `az aks get-credentials` I can see that certificate has 
`        Subject: O = system:masters, CN = masterclient`

This group is already assigned to cluster-admin role in Kubernetes so user has a full access.

**What happened**:
Each user has the same privileges "Subject: O = system:masters, CN = masterclient"

**What you expected to happen**:
User has no permissions if no roles are bound to him.

**How to reproduce it (as minimally and precisely as possible)**:
Create aks with rbac enabled via portal UI, create application registrations, reset aadprofile, add role assignment to resource group, login via az login and get credentials.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 
`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by alanjcastonguay** [comment]
I believe I have exactly the same symptoms in a cluster. Can you clarify whether you're referring to the certificate written in `~/.kube/config`, and the exact command (OpenSSL?) you used to dump the human-readable fields?

**Comment by adriancislo** [comment]
Clarification:

- you're referring to the certificate written in ~/.kube/config
A: Yes. I refer to this certificate 

- the exact command (OpenSSL?) you used to dump the human-readable fields
A: First I decode base64 from `client-certificate-data` and save result in the file. Then run `openssl x509 -in crt.pem -noout -text`

- you're trying to enable AAD on an existing cluster; the aadprofile wasn't set at cluster creation
A: Indeed. Only RBAC option was enabled during cluster creation.

- whether you performed a cluster master version upgrade after updating the aadprofile field
A: Nope. I haven't done anything like that, just reset aadprofile several times... I also tried with newly created app registration... no results.. 

I also wanted to see logs in azure-portal for master api but don't know yet how to do that. Maybe there I would find that reset aadprofile ... failed due to some typo mistake or any other stupid reason

**Comment by alanjcastonguay** [comment]
Yup, same scenario.

As far as I can tell the aadprofile section options get rendered down to the oidc command line arguments on the master api-server at install time (and maybe at upgrade too). The reset obviously has to change them, though maybe there's some oidc-enabled-at-all flag that's not altered by the reset. That's pure conjecture on my part, though.

**Comment by alanjcastonguay** [comment]
See also https://github.com/Azure/AKS/issues/397

**Comment by adriancislo** [comment]
Thanks @alanjcastonguay 

I already saw topic #397 and I understood it is rather about differences between `--admin` flag and when it is omitted, security hole that everyone can use `--admin` and get admin permissions.

I have got already up and running cluster with some deployments so re-creating it is the last option I consider right now. Actually I already spent/wasted enough time trying to make it working so I could set up cluster once again (providing aad profile)... but who could expect such problems...

If you have already opened a support ticket then maybe we could expect the problem to be solved soon.

**Comment by adriancislo** [comment]
Do you maybe know whether there is an option to force restart api-server?

Maybe then the addprofile will be correctly configured.

If I understand correctly this slice of code, this function is executed when api-server starts.. to provide correct configuration values to api-server

**Comment by jnoller** [comment]
This is the same root issue as bug https://github.com/Azure/AKS/issues/756 which is a known issue with mapping Kubernetes roles to AAD. Certificate rolling/revocation is not currently supported, users can not modify/mutate or restart the API server as well. 

Automatically rolling/removing users disabled via AAD and then rolling the kubernetes certs given how kubernetes assigns those certs and roles currently means that if we were to 'quick fix' this in current state, all users would have their kubeconfig certificates removed. 

We are working in upstream, internally, and with the AAD team to resolve this.

**Comment by alanjcastonguay** [comment]
@adriancislo: Quick and dirty summary of all the certs as a one-liner, using https://yq.readthedocs.io/ + `openssl`, to avoid that intermediate file.

```
cat ~/.kube/config | yq -r '.users[] | {pem:.user["client-certificate-data"], "name"} | flatten | @tsv' | while read -r CERT NAME; do echo -n "$NAME: "; echo $CERT | base64 -D | openssl x509 -noout -subject -dates | tr "\n" " "; echo; done
```

```
clusterUser_resourcegroup-clustername: subject= /O=system:masters/CN=client notBefore=Nov 13 23:01:34 2018 GMT notAfter=Nov 12 23:01:34 2020 GMT 
docker-for-desktop: subject= /O=system:masters/CN=docker-for-desktop notBefore=Jul 30 22:34:21 2018 GMT notAfter=Mar 12 05:10:48 2020 GMT 
etc
```

**Comment by miwithro** [comment]
@norshtein FYI.
