### ISSUE TITLE
What is the expected lag time for new versions?

### ISSUE THREAD

**Issue by derekperkins** [Azure/AKS#88]
I'm curious what the target is for staying up with upstream kubernetes releases. 1.8.2 is the most recent version available, which is now 2 months old and 3 point releases behind. My experience with GKE is about a 2 week delay. Is that going to be a reasonable expectation as AKS approaches GA?

**Comment by brendandburns** [comment]
We're aiming for 1-2 weeks for point releases, and 1 month for a minor release (e.g. 1.9)

Obviously we're not quite there yet...

**Comment by derekperkins** [comment]
Thanks for the clarification, that's very helpful as we're evaluating AKS.
