### ISSUE TITLE
Support for Public IP Prefixes

### ISSUE THREAD

**Issue by cj-anthony** [Azure/AKS#880]
**What happened**:

Attempted to assign an IP from a Public IP Prefix to a k8s Service and the loadbalancer stuck on ensuring. Errors in loadbalancer log "Basic sku load balancer <my-lb> cannot reference Standard sku publicIP <my-ip>."

**What you expected to happen**:

Loadbalancer is ensured. Traffic is routed through service.

**How to reproduce it (as minimally and precisely as possible)**:

Create a public ip prefix in azure and add an ip within.
Reference this IP in a k8s service with the service.beta.kubernetes.io/azure-load-balancer-resource-group annotation
Check Alerts page of loadbalancer

**Anything else we need to know?**:

Suspect that these two things won't work together for now. You can't have a public ip prefix using a Basic SKU, and AKS loadbalancer don't support the standard SKU. Is there a workaround?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.5
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster: HTTP Microservices

**Comment by jnoller** [comment]
Standard load balancer are not currently supported but are on track for first half of this year

**Comment by delulu** [comment]
kindly ping on it, what's the latest status of this feature?
