### ISSUE TITLE
What should/shouldn't we monitor with Prometheus

### ISSUE THREAD

**Issue by Vandersteen** [Azure/AKS#883]
**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.6

As part of AKS is managed, I am unsure what we should or shouldn't be monitoring with prometheus on our end:

For example:

* kubeApiServer
* kubeControllerManager
* kubeEtcd
* kubeScheduler

Should we Scrape / Monitor these, and why ?

For now the only ones that I do not scrape / monitor is etcd, controllermanager & kube scheduler. As I cannot make it work with stable/prometheus-operator. 

I'd love to have recommendations from you guys

**Comment by jnoller** [comment]
Marking as a docs enhancement

**Comment by poochwashere** [comment]
I have the same question. Did you receive a response?

**Comment by tomkerkhove** [comment]
FYI @keikhara, this might interest you.

**Comment by keikhara** [comment]
@tomkerkhove  thanks. :D Let me also add that info as our guideline on what would be good with Prometheus with CI vs what is not and what is OOB + what is free.

**Comment by petenorth** [comment]
I am using https://github.com/helm/charts/blob/master/stable/prometheus-operator .

This helm chart will install without any problems but a number of alerts associated with the health of the master nodes will be in firing state after installation. To get a usable installation I set

kubeScheduler.enabled=false
kubeControllerManager.enabled=false

so it doesn't attempt to scrape these resources.

I couldn't see any documentation that explains why I need to do this on AKS.

The reason why I use the operator is that I get really useful alerts out of the box (deployment replica mismatches, job failures, rollouts stuck) .
