### ISSUE TITLE
Unable to create clusters without the http application routing addon (or remove it afterwards)

### ISSUE THREAD

**Issue by patkearney** [Azure/AKS#886]
**What happened**:
Created a new AKS version 1.12.6 cluster in UKSOUTH specifically not requesting Http Application routing. The addon was then added to the cluster on deployment.

Additionally, it is not possible to remove the addon using the az aks disable-addons command.

Additionally, it is not possible to remove the monitoring addon when in this scenario.

Additionally an existing cluster that has any change attempted to it's addons, for example removal of the monitoring addon, will have the Http application routing added to the cluster if it is not already present.

I initially logged this as an az cli issue but it seems wider.

**What you expected to happen**:
Not to have the http application routing addon arbitrarily added to the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new cluster without the Http routing cluster. List the objects within the kube-system namespace.

`kube-system   ds/kube-proxy          1         1         1         1            1           beta.kubernetes.io/os=linux   14m
kube-system   ds/kube-svc-redirect   1         1         1         1            1           beta.kubernetes.io/os=linux   14m

NAMESPACE     NAME                                                             DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deploy/addon-http-application-routing-default-http-backend       1         1         1            1           14m
kube-system   deploy/addon-http-application-routing-external-dns               1         1         1            1           14m
kube-system   deploy/addon-http-application-routing-nginx-ingress-controller   1         1         1            1           14m
kube-system   deploy/coredns                                                   2         2         2            2           14m
kube-system   deploy/coredns-autoscaler                                        1         1         1            1           14m
kube-system   deploy/heapster                                                  1         1         1            1           14m
kube-system   deploy/kubernetes-dashboard                                      1         1         1            1           14m
kube-system   deploy/metrics-server                                            1         1         1            1           14m
kube-system   deploy/tunnelfront                                               1         1         1            1           14m

NAMESPACE     NAME                                                                   DESIRED   CURRENT   READY     AGE
kube-system   rs/addon-http-application-routing-default-http-backend-8cdc9d7f7       1         1         1         14m
kube-system   rs/addon-http-application-routing-external-dns-f74cbbdc6               1         1         1         14m
kube-system   rs/addon-http-application-routing-nginx-ingress-controller-8f8cc4dcd   1         1         1         14m
kube-system   rs/coredns-754f947b4                                                   2         2         2         14m
kube-system   rs/coredns-autoscaler-6fcdb7d64                                        1         1         1         14m
kube-system   rs/heapster-5fb7488d97                                                 1         1         1         14m
kube-system   rs/kubernetes-dashboard-847bb4ddc6                                     1         1         1         14m
kube-system   rs/metrics-server-7b97f9cd9                                            1         1         1         14m
kube-system   rs/tunnelfront-6fd986769c                                              1         1         1         14m

NAMESPACE     NAME                                                                 READY     STATUS    RESTARTS   AGE
kube-system   po/addon-http-application-routing-default-http-backend-8cdc9dcl7xt   1/1       Running   0          14m
kube-system   po/addon-http-application-routing-external-dns-f74cbbdc6-t5hg2       1/1       Running   0          14m
kube-system   po/addon-http-application-routing-nginx-ingress-controller-8fnltzc   1/1       Running   0          14m
kube-system   po/coredns-754f947b4-j225v                                           1/1       Running   0          10m
kube-system   po/coredns-754f947b4-nhkvp                                           1/1       Running   0          14m
kube-system   po/coredns-autoscaler-6fcdb7d64-v8fq8                                1/1       Running   0          14m
kube-system   po/heapster-5fb7488d97-76nnb                                         2/2       Running   0          14m
kube-system   po/kube-proxy-4rnrx                                                  1/1       Running   0          11m
kube-system   po/kube-svc-redirect-xlxrr                                           2/2       Running   0          11m
kube-system   po/kubernetes-dashboard-847bb4ddc6-2fpp7                             1/1       Running   0          14m
kube-system   po/metrics-server-7b97f9cd9-5n58f                                    1/1       Running   0          14m
kube-system   po/tunnelfront-6fd986769c-nzzgg                                      1/1       Running   0          14m`

**Comment by fbeauche** [comment]
It seems to affect certain existing cluster as well. 

Two of our existing cluster add the addon pods and services added today ! 

It caused us some downtime since the  egress ip actually changed since we did not had any public ip load balancer in place.

**Comment by erewok** [comment]
I saw in the changelog that this is being worked on, but it would be cool to know when the fix is expected. We are currently putting on hold our plans to spin up a new prod cluster, which had been planned for this week, because we also cannot disable the add-on. @jnoller, any information you can provide on this one?

**Comment by poochwashere** [comment]
+1 
An ETA would be nice, even a rough one. This is holding back migration plans.

**Comment by borstibacon** [comment]
+1 
Same issue while using ARM template , I had used since month. Thought already Im kind of crazy....

**Comment by jnoller** [comment]
We're working on the fixes needed as we speak

**Comment by poochwashere** [comment]
Is there an estimate available as to when **Release 2019-03-29 (Hotfix)** will be available in **US West**?

**Comment by jnoller** [comment]
@poochwashere It should be there, but there was a new bug identified over the weekend specific to the http addon

**Comment by poochwashere** [comment]
@jnoller 
Strange, I just deployed in WestUS and I still see the add-ons being deployed despite this setting defined in my arm template. 
```json
"enableHttpApplicationRouting": {
            "defaultValue": false,
            "type": "bool",
            "metadata": {
                "description": "boolean flag to turn on and off of http application routing"
            }
```

Here is the "fresh" cluster.
```shell
az ❯ k get po --all-namespaces
NAMESPACE     NAME                                                              READY   STATUS    RESTARTS   AGE
kube-system   addon-http-application-routing-default-http-backend-8cdc9d4m2cz   1/1     Running   0          15m
kube-system   addon-http-application-routing-external-dns-794bbb4b4d-77lb2      1/1     Running   0          15m
kube-system   addon-http-application-routing-nginx-ingress-controller-8f9p8tt   1/1     Running   0          15m
```

**Comment by poochwashere** [comment]
W00t! I deployed a new cluster this morning and no more Http Application Routing! Thanks for resolving this.

**Comment by jnoller** [comment]
Well, that's good news, must mean it's not monday anymore :)
