### ISSUE TITLE
Setting for Garbage Collection Policy for Containers

### ISSUE THREAD

**Issue by unacao** [Azure/AKS#888]
**What happened**: After upgrading from 1.11.4 to 1.12.6, some of our exited containers will disappear.

I would like to find out the default setting used by AKS for the garbage collection policy of containers, specifically these 3 variables: MinAge, MaxPerPodContainer and MaxContainers.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.6
- Size of cluster (how many worker nodes are in the cluster?) 6
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jnoller** [comment]
The GC setting was changed to a lower value due to customers encountering issues with large numbers of jobs causing degradation of the cluster with the higher GC level. This was noted in the release notes here:

https://github.com/Azure/AKS/releases/tag/2019-03-21
