### ISSUE TITLE
Consider support IPv6 for IoT scenarios

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#89]
We are a large IoT software organization and are thinking of transitioning to K8s from service fabric for our cloud offering.  We target our devices via IPv6 address.  Not having IPv6 would be a big blocker for us.

Thanks.

**Comment by AceHack** [comment]
Any idea on timeframe this might be in?  This is very important to our full adoption of K8s.  Thanks.

**Comment by seanknox** [comment]
No ETA currently. For feature requests, please go here: https://aka.ms/aks/feedback
