### ISSUE TITLE
Cannot create Kubernetes cluster in Japan East

### ISSUE THREAD

**Issue by gaeshi** [Azure/AKS#891]
**What happened**: Got error "This container service is in a failed state. Click here to open a new support request." trying to create Kubernetes cluster in Japan East from Azure Portal.
Getting error `Code="ControlPlaneProvisioningInternalError" Message="Internal server error"` when trying to create aks cluster in Japan East using Azure CLI.

**What you expected to happen**: Cluster created successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Login to portal.
1. Open "Kubernetes services".
1. Press "Add" button. Create Kubernetes cluster blade opens.
1. Fill in "Kubernetes cluster name" field. For example, type "foo".
1. In Region, choose "Japan East". Leave the other fields with their default values.
1. Click "Review + Create" button. Wait until validation completes successfully, "Validation passed" text appears, and the "Create" button becomes active.
(Sometimes you'll see an error saying "The request timed out. Diagnostic information: timestamp 'some-timestamp', subscription id '', tracking id 'some-guid', request correlation id 'some-guid'. (Code: ServerTimeout)". Just retrying usually works fine.)
1. Click "Create" button.
After a while, the operation will fail, and the blade for the cluster will show the error message "This container service is in a failed state. Click here to open a new support request."

**Anything else we need to know?**:
The same procedure produces the expected result (Cluster created successfully), when choosing another region (I tried West Europe).

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.6
- Size of cluster (how many worker nodes are in the cluster?) 3 x Standard DS2 v2 (2 vcpus, 7 GB memory)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jnoller** [comment]
We have not received other reports of an issue failing creates in Japan West, I checked our internal QoS reports and have not seen corollary spikes. You tested across multiple regions, which means that this is possibly an issue with your Subscription's available quota, Service Principal, or another subscription specific issue.

Please open an azure technical support issue - I can not ask for the information needed to dig into your specific subscription.
