### ISSUE TITLE
[Feature] Node Image Upgrade

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#893]
**Status**: Public Preview

**Docs**: aka.ms/aks/nodeimageupgrade

AKS does not currently support upgrades for nodes unless there is a new K8s version upgrade available (refresh to latest node image components).

Tracking Feature/Functionality request:

AKS should support upgrades that:

- Refreshes, in-place all applicable component versions for a given node to the latest release compatible with that cluster's Kubernetes version.
- AKS should have a version file / API /etc that exposes the versions of all integrated components in a human/machine readable format

Currently, same-version upgrades (eg. 1.12.6 to 1.12.6) are blocked **unless** the cluster is in a Failed State (as noted by the Azure Portal or Azure CLI). In this scenario, AKS allows the same version upgrade through to assist in repairing a cluster impacted by transient issues.

**Comment by asubmani** [comment]
This should automatically handle draining of node pools. User can be warned that for nodes that have taints, minimally viable nodes with same VM/VMSS sku will be spun up with same taints (which may incur charge). Only if the user CHOOSES NOT to allow the upgrade to spin up necessary VM's/VMSS in node pools should the complexity increase (we have [kured](https://github.com/weaveworks/kured) for such cases anyways.)

Any identities assigned to the VM or VMSS **MUST** be retained. e.g.

VM
```shell
az vm identity assign -g <VM resource group name> -n <VM name> --identities <resource ID of managed identity>
````
VMSS
```shell
az vmss identity assign -g <VM resource group name> -n <VM name> --identities <resource ID of managed identity>
```
Please understand that if operators have to go out of the way to script *any* of this, then it is easier to  just use [kured](https://github.com/weaveworks/kured) and control all of the moving parts.

## Good to have: Query status of upgrade operations (not just activity log) via API or az cli command.  Would be great if this can be tracked similar to how we track deployments using -w parameter that shows progress.

**Comment by palma21** [comment]
Hi @asubmani. Thanks for your feedback

First part is totally in GA scope of this feature. Allowing to control the number of nodes used to buffer is something we definitely want to add, since as you mention the conservative approach of using a buffer node is not ideal for every use case, we have it as its own tracked feature. (including 0) https://github.com/Azure/AKS/issues/1594

Identities assigned directly using the IaaS APIs is not really something that is supported. Could you let us know a bit more about your use case? Could it not be accomplished by something like AAD Pod Identity? https://github.com/Azure/aad-pod-identity

You will be able to track the node upgrade using kubectl get nodes, we'll provide details on the documentation, but we can also look into additional CLI experience if the feedback is that's not enough.

**Comment by asubmani** [comment]
> Identities assigned directly using the IaaS APIs is not really something that is supported. Could you let us know a bit more about your use case? Could it not be accomplished by something like AAD Pod Identity? https://github.com/Azure/aad-pod-identity

Actually this is a pre-requisite for aad-pod-identity to work..  
My concern was that any plans to improve maintenance may reset the MI of the scalesets or VM. 
This would break "Aad-pod-identity" everytime a node maintenance ops is done.

Today the MIC component of "aadpodidentity" assigns this. I don't see a big issue here as every time the VM/VMSS get refreshed, they get new identities. (for the VM/VMSS) 
AKS cluster identities will remain the same

Issue comes with "Managed AAD" mode as described here.

https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.managed-mode.md

**Comment by tshak** [comment]
I'm glad that this is being looked into. For AKS VMSS I would prefer an immutable infrastructure approach that does not reduce the active node count in the pool. The upgrade process would work something like:
- Add an upgraded node to the pool
- Cordon a random old node from the pool
- After cordon is complete, delete the old node.

Thank you for your consideration 💪

**Comment by palma21** [comment]
Pod identity and managed aad will remain working as expected after the upgrade (similar to the k8s upgrade today)

@tshak that is indeed how its default behavior will perform (except the node choice is not exactly random 😊)

Thanks!

**Comment by Robert-Stam** [comment]
Two related questions:
1) Is there a way (preferably via an Azure API call) to get the latest image available? Like the versions.
2) Could the current used image added to the agent-pool type, so we don’t have to grep that from the node itself (it’s there in an annotation)? 

These 2 will help us in detecting if an update is available so we can apply that.

Thanks in advance!

**Comment by palma21** [comment]
There is. Does the below look like it matches your requirement?

https://docs.microsoft.com/en-us/rest/api/aks/agentpools/getupgradeprofile
```
{
  "id": "/subscriptions/subid1/resourcegroups/rg1/providers/Microsoft.ContainerService/managedClusters/clustername1/agentPools/agentpool1/upgradeprofiles/default",
  "name": "default",
  "properties": {
    "kubernetesVersion": "1.12.8",
    "osType": "Linux",
    "upgrades": [
      {
        "kubernetesVersion": "1.13.5"
      }
    ],
    "latestNodeImageVersion": "AKSUbuntu:1604:2020.03.11"
  },
  "type": "Microsoft.ContainerService/managedClusters/agentPools/upgradeProfiles"
}
```
And then on your pool you can always check the image with 

`az aks nodepool show -n nodepool1 --cluster-name aks -g aks --query nodeImageVersion`

**Comment by brobichaud** [comment]
I'm very interested in this as well, especially for my Windows nodepools. I just tried the az command line on my cluster, both the linux and windows nodepools and I get no output. It's clearly querying as it takes a few seconds, but then nothing. Here's what I see:

```
c:\>az aks nodepool show -n nodepool1 --cluster-name my-cluster -g my-resgrp --query nodeImageVersion
The behavior of this command has been altered by the following extension: aks-preview
```

I've got cli version 2.7. Any thoughts on why I get no output?

(as a side note, I'd love to remove the "preview" extensions as I no longer need them, but I don;t know how)

**Comment by jluk** [comment]
@gtxistxgao to confirm the output behavior, it should at least confirm completion of the operation if you're on the latest version

@brobichaud the preview extensions can be removed with `az extension -n aks-preview` but keep in mind all preview features only have CLI support in that preview ext. When the features move to GA, they get supported in CLI core without needing the extension.

Hope this helps.

**Comment by palma21** [comment]
What is the version on the extension you're using? That's probably it since it can be using an older API version. Try to update it with `az aks extension update -n aks-preview` and try again.

If that doesn't work, could you paste the output of your extension version and the output of az aks show (without the query)

**Comment by brobichaud** [comment]
@palma21 @jluk I updated my aks-preview extension to 0.4.53 and it is working now. Thanks for the help.

**Comment by adhodgson1** [comment]
Hi all,

Is there any documentation on how this new feature works with an ARM template?

If we submit an ARM template for an existing cluster and set properties.kubernetesVersion to the same version as already deployed, will that upgrade the image version for all node pools?

**Comment by hlarubi** [comment]
Also, the same question as above for Terraform.

Thanks!

**Comment by Robert-Stam** [comment]
This feature is already a while in preview, Is there an ETA for GA, or a ballpark estimate?

**Comment by jluk** [comment]
This feature is generally available now, thanks for feedback! Closing as a result.

Official docs are here: https://docs.microsoft.com/en-us/azure/aks/node-image-upgrade

GA Announce: https://azure.microsoft.com/en-us/updates/general-availability-azure-kubernetes-service-node-image-upgrade/

**Comment by Robert-Stam** [comment]
Hi Justin @jluk,

Thanks for the post.
