### ISSUE TITLE
Documentation: AKS Upgrade & Scale behaviors

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#894]
Currently the AKS documentation does not go into details around what components are upgraded/revised and when. For example:

- Are same version upgrades supported (no)
- On a default upgrade from 1.11.x to 1.11.y, what components (aks-engine, the base VHD, etc) are upgraded?
- On scale up, what versions of components do new nodes get (eg same k8s version, but newer moby?)
- How do users on the latest patch release get service updates on worker nodes?
- What (on Workers) is upgraded / refreshed in all cases

**Comment by jluk** [comment]
https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions
