### ISSUE TITLE
Still cannot create Kubernetes Cluster in Japan East region

### ISSUE THREAD

**Issue by fixergvb** [Azure/AKS#898]
Link to previous issue: https://github.com/Azure/AKS/issues/891

I have tried this from 2 completely separate accounts, the issue is the same.

I have got confirmation from MS Support Engineer that she can repeat the issue in her lab environment, too:

> Hello Victor,
> 
> I wanted to let you know that I was able to create an AKS cluster in Japan East successfully with version 1.11.8; however, when I tried to create an AKS cluster in Japan East with version 1.12.6, it failed.  It appears the issue has to do with the version in that region.
> 
> I am making sure our product group is aware of this behavior to determine why it will not allow for an AKS cluster to be created with version 1.12.6 in that region.
> 
> I will continue to keep you updated on our findings.
> 
> (signature removed) 

**What happened**: Got error "This container service is in a failed state. Click here to open a new support request." trying to create Kubernetes cluster in Japan East from Azure Portal.
Getting error `Code="ControlPlaneProvisioningInternalError" Message="Internal server error"` when trying to create aks cluster in Japan East using Azure CLI.

**What you expected to happen**: Cluster created successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Login to portal.
1. Open "Kubernetes services".
1. Press "Add" button. Create Kubernetes cluster blade opens.
1. Fill in "Kubernetes cluster name" field. For example, type "foo".
1. In Region, choose "Japan East". Leave the other fields with their default values.
1. Click "Review + Create" button. Wait until validation completes successfully, "Validation passed" text appears, and the "Create" button becomes active.
(Sometimes you'll see an error saying "The request timed out. Diagnostic information: timestamp 'some-timestamp', subscription id '', tracking id 'some-guid', request correlation id 'some-guid'. (Code: ServerTimeout)". Just retrying usually works fine.)
1. Click "Create" button.
After a while, the operation will fail, and the blade for the cluster will show the error message "This container service is in a failed state. Click here to open a new support request."

**Anything else we need to know?**:
The same procedure produces the expected result (Cluster created successfully), when choosing another region (I tried West Europe).

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.6. The problem seems to be specific to this version.
- Size of cluster (how many worker nodes are in the cluster?) 3 x Standard DS2 v2 (2 vcpus, 7 GB memory)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jnoller** [comment]
Can you post the support ticket number? It’s not sensitive information and I’ll chase this down today

**Comment by fixergvb** [comment]
@jnoller, thank you very much for looking into this. I've received the following email from MS Support Engineer I'm in contact with:

> Hello Victor,
> 
> I wanted to provide you with an update.  Originally I thought it had to do with the version; however, when I was informed that our product group could not reproduce the issue, I decided to go ahead and test this again creating two clusters with the same version of 1.12.6 as you have more than one AKS cluster in the Japan East region.  When I created the first cluster it was successful.  When I created the second cluster, it failed.
> 
> I have shared this information with our product group so they can investigate further as to why this is continuing to occur.  Also, I have added Jesse Noller as a contact so he now has the case number for your issue that he asked you for in the GitHub link (https://github.com/Azure/AKS/issues/898).
> 
> I will continue to keep you updated as I get more responses from our product group as well.
> 
> Thank you again for your patience in this matter while we determine why this is occurring and resolve it.
> 
> Best regards,
> (signature removed)

I haven't seen your email added to the list of recipients though, so please confirm if it is. If it's not - I can encrypt and share the ticket ID with you if you provide me your public key.

**Comment by jnoller** [comment]
@fixergvb Nope, I got it and the escalation. We're looking at it now, it's not tied to Kubernetes/AKS creation specifically. We're looking into a possible data replication issue. I'll follow up with support and on-call

**Comment by jnoller** [comment]
The root of this issue was a service principal data replication delay
