### ISSUE TITLE
Outbound traffic requirements during initial VM deployment

### ISSUE THREAD

**Issue by MXClyde** [Azure/AKS#899]
**What happened**:

Working at a customer to deploy a new AKS cluster on a custom VNet. They have restricted outbound IP traffic to only allow HTTPS out (443). This leads to the  following deployment error:

{  
   "code":"DeploymentFailed",
   "message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
   "details":[  
      {  
         "code":"Conflict",
         "message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"**We were not able to establish outbound connectivity, please make sure that your VNET allows outbound internet connectivity. See https://docs.microsoft.com/en-us/azure/aks/networking-overview#advanced-networking-prerequisites for more details**.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"**VM has reported a failure when processing extension 'cse-agent-0'**. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=50\\n[stdout]\\n\\n[stderr]\\n\\\".\"\r\n }\r\n ]\r\n }\r\n ]\r\n }\r\n}"
      }
   ]
}

Security policy at the customer prohibits them from opening up outbound connectivity to the whole world. They are willing to allow certain endpoints.

**Question**:
Can someone provide more specific pointers about what kind of traffic (except HTTPS) needs to be able to flow out into the internet during cluster VM deployment?

**Comment by jnoller** [comment]
Restricting / limiting outbound URLs and Ports is not currently supported. We will be posting a public roadmap on github soon which will encompass this (and historical) requests around egress limiting. We can not provide a list of urls and ports currently as that list is subject to change and can result in upgrades, creates and other actions failing.
