### ISSUE TITLE
Provide more information during creation/deletion of a cluster

### ISSUE THREAD

**Issue by OriYosefiMSFT** [Azure/AKS#9]
Creating (and to a lower extent deleting) an AKS cluster is a lengthy operation. Currently, one only sees "creating" for a couple of minutes. 
It would be nice if there were some indication of what's going on (e.g. creating resource, setting up network, installing binaries, ....). 
Even without understanding the entire process it would give a sense of progress and some understanding of why the process is taking long.
Not sure how easy it is to do with ARM deployment, but I think it would be an improved used experience.

**Comment by amanohar** [comment]
@OriYosefiMSFT thanks for the feedback. While it might not be possible to provide granularity like `installing binaries` but there is certainly scope for some additional granularity during long running operations. Will take this feedback to the team

**Comment by seanknox** [comment]
Closing due inactivity. Feel free to re-open.
