### ISSUE TITLE
az aks scale fails when virtual network has peerings

### ISSUE THREAD

**Issue by msdotnetclr** [Azure/AKS#90]
So I have this AKS cluster created, and one of the pod needs access to our on-prem LDAP server (on a 10.8.x.x VNET)  for authentication. So I worked with my network guy to change the AKS cluster VNET CIDR to something like 10.201.x.x so we can do Network Peering. All worked and my pods can talk to our  LDAP server now. However, when I attempted to scale the cluster, the deployment failed:
```bash
~$ az aks scale -g RG_AKS_PRESTO -n presto  -c 2
Deployment failed. Correlation ID: b71ab806-751e-4531-a87b-e90927848d17. Address space of the virtual network /subscriptions/*******/resourceGroups/MC_RG_AKS_PRESTO_presto_eastus/providers/Microsoft.Network/virtualNetworks/aks-vnet-19361140 cannot change when virtual network has peerings. 
```
Question: I know I can try to tear down peering, scale, and re-create peering, but this is massive PITA. Is there any other option?

**Comment by msdotnetclr** [comment]
OK, I removed peering but left other modifications in place, including a subnet called "aks-subnet-mod" which I created to replace the old 10.0.0.0/8 subnet created by the "az aks create" command. I received this error:

```bash
$ az aks scale -g RG_AKS_PRESTO -n presto  -c 2
Deployment failed. Correlation ID: 6301ae21-0196-4399-bdf5-1f514de85f9d. Subnet aks-subnet-mod is in use by /subscriptions/**************/resourceGroups/MC_RG_AKS_PRESTO_presto_eastus/providers/Microsoft.Network/networkInterfaces/aks-nodepool1-19361140-nic-0/ipConfigurations/ipconfig1 and cannot be deleted.
```

**Comment by msdotnetclr** [comment]
The question is, is it possible to have network peering on AKS cluster without disruptive effects like failing scaling? If so, how?

**Comment by slack** [comment]
@msdotnetclr we don't support VNET with peering in AKS today. We will be working on existing VNET support as part of our work in the early parts of this year.

Still sorting out the dependency tree. For example you can't update/add/change a User Defined Route (UDR) to a VNET with peering. This breaks `kubenet` deployments, and will require Azure IPAM (via CNI) to fully work.

Short answer, there isn't a stable workaround at the IaaS/VNET layer.

**Comment by msdotnetclr** [comment]
Thanks for the update. Currently, with AKS, is there any viable way to
consume services in another VNET, like Active Directory/LDAP services?

**Comment by slack** [comment]
At the moment, not without treating the AKS -> Service traffic as external.

**Comment by seanknox** [comment]
Closing due inactivity. Feel free to re-open if still an issue.

**Comment by cmilanf** [comment]
Sorry for resurrecting this old thread, has the issues commented here been resolved? I wonder if AKS with VNET peering is an officially supported scenario and if there are currently any limitations or constrains.

**Comment by msdotnetclr** [comment]
This is no longer an issue.

**Comment by cmilanf** [comment]
Good to know, thanks for the update :)

**Comment by nishitasikka1995** [comment]
> So I have this AKS cluster created, and one of the pod needs access to our on-prem LDAP server (on a 10.8.x.x VNET) for authentication. So I worked with my network guy to change the AKS cluster VNET CIDR to something like 10.201.x.x so we can do Network Peering. All worked and my pods can talk to our LDAP server now. However, when I attempted to scale the cluster, the deployment failed:
> 
> ```shell
> ~$ az aks scale -g RG_AKS_PRESTO -n presto  -c 2
> Deployment failed. Correlation ID: b71ab806-751e-4531-a87b-e90927848d17. Address space of the virtual network /subscriptions/*******/resourceGroups/MC_RG_AKS_PRESTO_presto_eastus/providers/Microsoft.Network/virtualNetworks/aks-vnet-19361140 cannot change when virtual network has peerings. 
> ```
> 
> Question: I know I can try to tear down peering, scale, and re-create peering, but this is massive PITA. Is there any other option?

How was this issue taken care of ?
