### ISSUE TITLE
Multi cluster pod communication

### ISSUE THREAD

**Issue by Tenseiga** [Azure/AKS#900]
HI All,

I have  2 AKS clusters running in two separate Vnets. Both the vnets are peered.
I want to achieve intra pod comminucation, i.e. Pods from one cluster can talk to pods in other cluster. 
I also tried creating two VMS in vnet1 and 2 and vnet1 VM can talk to pods in vnet2 and viceversa. But pods couldnt connect successfully

**Environment**:
- Kubernetes version (1.12`):
- Size of cluster 3 node)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by kim0** [comment]
@Tenseiga .. I'm not on the Azure team, but I suggest you try with [Advanced networking](https://docs.microsoft.com/en-us/azure/aks/concepts-network#azure-virtual-networks)

**Comment by arbreezy** [comment]
Do we have any update on this?
Having the same issue with two peered AKS clusters with azure cni network plugin.
