### ISSUE TITLE
Restrict Log Analytics logging per deployment or container

### ISSUE THREAD

**Issue by davenewza** [Azure/AKS#903]
We've seen our Log Analytics costs spike and found that the ContainerLog table had grown drastically. This appears to be from stdout/stderr logs from the containers.

Is it possible to restrict logging to this table, at least for some deployments or containers, without disabling Log Analytics on the cluster? We still want performance logging and insights.

**Comment by jnoller** [comment]
Hi @davenewza I spoke to my peer in the Container Insights team, and they confirmed this is on their roadmap as well as additional configurations and the ability to better control costs. I can not commit to a precise date yet, but it is coming.

**Comment by davenewza** [comment]
Thanks @jnoller.  

Possible workaround here:  https://stackoverflow.com/questions/55534204/restrict-log-analytics-logging-per-deployment-or-container

**Comment by Lesio777** [comment]
+1

**Comment by mariojacobo** [comment]
+1

**Comment by kaluzaaa** [comment]
+1

**Comment by jszwab** [comment]
+1

**Comment by mllab-nl** [comment]
You can disable container logs collection by monitoring plugin : 
Read here: https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-agent-config
