### ISSUE TITLE
az aks 'update' is not in command group

### ISSUE THREAD

**Issue by bq1756** [Azure/AKS#904]
**What happened**:
When I execute the command 'az aks update', I see a response "az aks: 'update' is not in the 'az aks' command group. See 'az aks --help'."

**What you expected to happen**:
I expected to update my aks cluster configuration.

**How to reproduce it (as minimally and precisely as possible)**:
type 'az aks update' on command prompt

**Anything else we need to know?**:
'az --version' shows "azure-cli                         2.0.61"
I installed az cli 2.0.61 via MSI installer
I installed azurerm via 'install-module azure'
I am attempting to add the k8s cluster autoscaler according to https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler.  This article instructs me to run

az aks update \
  --resource-group myResourceGroup \
  --name myAKSCluster \
  --enable-cluster-autoscaler \
  --min-count 1 \
  --max-count 3

**Environment**:
- PowerShell 6.0

**Comment by bq1756** [comment]
I solved the problem.  The GA version of az cli does not contain 'update'.  'update' is a preview feature.  To enable az cli preview features, I ran:
`az extension add --name aks -preview`

**Comment by bq1756** [comment]
I solved the problem. The GA version of az cli does not contain 'update'. 'update' is a preview feature. To enable az cli preview features, I ran:
az extension add --name aks -preview

**Comment by dstarosta** [comment]
There is no space before "-preview".
`az extension add --name aks-preview`

**Comment by gynet** [comment]
As there is no doc added in the Az Cli, I don't think it's valid to close the ticket  @bq1756
