### ISSUE TITLE
EKS vs AKS with additional CIDR blocks

### ISSUE THREAD

**Issue by sowsan** [Azure/AKS#906]
Do we have this capability mentioned for AWS EKS in Azure AKS? https://aws.amazon.com/about-aws/whats-new/2018/10/amazon-eks-now-supports-additional-vpc-cidr-blocks/

**Comment by jnoller** [comment]
All supported CIDR / CNI configuration options are available here: https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni
