### ISSUE TITLE
az aks create fails when aks-preview is added on CentOS 7.5

### ISSUE THREAD

**Issue by david618** [Azure/AKS#908]
**What happened**:
```
az aks create     --resource-group dj0409mp     --name dj0409mp-cluster     --enable-vmss     --node-count 3     --node-vm-size Standard_D8s_v3     --enable-addons monitoring     --admin-username azureuser     --ssh-key-value az.pub     --node-osdisk-size 100     --kubernetes-version 1.12.7
The command failed with an unexpected error. Here is the traceback:

super() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 274, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 266, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/root/.azure/cliextensions/aks-preview/azext_aks_preview/__init__.py", line 35, in load_arguments
    super().load_arguments(command)
TypeError: super() takes at least 1 argument (0 given)

To open an issue, please visit: https://aka.ms/azcli/issues
```

**What you expected to happen**:

Expected the creation of an AKS.  Same command worked on Ubuntu 18.04 and on Mac.

**How to reproduce it (as minimally and precisely as possible)**:

- Install AZ
Install Az on CentOS 7.5 using yum [instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest)

- Add aks-preview Extension

```
az extension add --name aks-preview
```

- Register Features

```
az feature register --name MultiAgentpoolPreview --namespace Microsoft.ContainerService
az feature register --name VMSSPreview --namespace Microsoft.ContainerService
```

- Create Resource Group

- Try to Create AKS

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  N/A
- Size of cluster (how many worker nodes are in the cluster?):  3 D8sv3 
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): N/A
- Others:

**Comment by mboersma** [comment]
@david618 it appears some Python3-specific syntax crept into the preview extension. I made [a PR](https://github.com/Azure/azure-cli-extensions/pull/641) to fix it. For now you may be able to work around it this way:

```
$ export EXT=aks-preview
$ pip install --upgrade --target ~/.azure/cliextensions/$EXT "git+https://github.com/mboersma/azure-cli-extensions.git@fix-aks-python2#subdirectory=src/$EXT&egg=$EXT"
```
