### ISSUE TITLE
Individual AKS agentpool name via ARM template and new API Version

### ISSUE THREAD

**Issue by borstibacon** [Azure/AKS#909]
Hi all!

I´m deploying AKS by using an ARM template. 
While looking trough new az aks commands, I recognized the possibility to define the name of the AKS nodes (default "agentpool"). 
So I tried to get this done by using my standard ARM template which will be called by a powershell script which handles all parameters like AKS Name, Node Count etc. 

Target is, to set the "name" of the agentPoolProfiles to the AKS-Name. This makes it easy to see in a list of nodes withtin the portal to which AKS the nodes belongs. 

I´ve tried several things:

1.Define in the ARM the "agentPoolProfiles" like this:
```
               "agentPoolProfiles": [
                    {
                        "name": "[parameters('aksName')]",
```

2.Define in the ARM the "agentPoolProfiles" and variables like this:
```
    "variables": {
        "poolname": "[parameters('aksName')]"
    }
                "agentPoolProfiles": [
                    {
                        "name": "[variables('poolname')]",
```

In both cases I´ve used the standard definition of the "aksName" Parameter:
```
        "aksName": {
            "type": "string",
            "minLength": 3,
            "maxLength": 31
```

3. Defined a new paramter, insert this into the "agentPoolProfiles" and call this parameter also from powershell with the necessary variable:
```
 "poolName": {
            "type": "string",
            "defaultValue" : "agentpool"
        }
```
Or

```
 "poolName": {
            "type": "string",
        }
defined in "agentPoolProfiles":
"agentPoolProfiles": [
                    {
                        "name": "[parameters('poolName')]",
```
 
The result was in all cases the same:

```
New-AzureRmResourceGroupDeployment : 14:32:22 - Error: Code=InvalidParameter; Message=Provisioning of resource(s) for container service K8S-MixedNetwork2 in resource 
group AKS-MixedNetwork failed. Message: {
  "code": "InvalidParameter",
  "message": "The value of parameter agentPoolProfile.name is invalid.",
  "target": "agentPoolProfile.name"
```

While defining directly a name in the ARM template like:
```
"agentPoolProfiles": [
                    {
                        "name": "hello",
```
or
```
    "variables": {
        "poolname": "HelloTest"
    }
                "agentPoolProfiles": [
                    {
                        "name": "[variables('poolname')]",
```

this is working fine.

Finally i recognized, that there is a new API version "2019-02-01".
Bit this doesnt changed the result.

Does anyone know, what I´m doing wrong?
Or is this still not possible?

One question regarding the new API version:
Was there any information about that? Cant find any news regarding that or even a documentation what has been change, so that I cant decide wether switch to the new version or not. 

Thanks for the Support!

Best regards,

René

**Comment by jnoller** [comment]
the new API version(s) are related to new preview features and other work coming into the product. Please re-test this setting when we release multiple agent pools in a few weeks, that should make naming it much simpler.

**Comment by borstibacon** [comment]
@jnoller 
Thanks for the answer.
But what does this mean exactly?
Is this not supported? Did I something wrong?

Thanks!
