### ISSUE TITLE
Can we configure multiple services using single internal loadbalancer

### ISSUE THREAD

**Issue by nishantjadhavinfosys** [Azure/AKS#914]
Hi Team,
This is not issue. Can we configure multiple services with single internal loadbalancer. As I understood, when we deployed Kubernetes service with type LoadBalancer then AKS create loadbalancer with unique available IP address asynchronously. Can we allocate same to different service within same namespace?

Regards,
Nishant

**Comment by chrisgahlert** [comment]
The way we did it: We deployed an Nginx Ingress Controller which is the only one with service type `LoadBalancer`. That way, our whole cluster gets only 1 external IP address. After that we just use the Ingress Resource to route the incoming requests to the correct service.

**Comment by nishantjadhavinfosys** [comment]
> The way we did it: We deployed an Nginx Ingress Controller which is the only one with service type `LoadBalancer`. That way, our whole cluster gets only 1 external IP address. After that we just use the Ingress Resource to route the incoming requests to the correct service.

Thanks for confirmation. We have already implemented using Ingress. Just wanted to checked any alternative way other than ingress controller.

**Comment by nishantjadhavinfosys** [comment]
Can anyone from Azure or AKS confirms our understanding

**Comment by seanmck** [comment]
You can have multiple services behind the same load balancer, but each service will get its own IP.

**Comment by nishantjadhavinfosys** [comment]
> You can have multiple services behind the same load balancer, but each service will get its own IP.

Thanks for confirmation
