### ISSUE TITLE
coredns: "Hosts" plugin support

### ISSUE THREAD

**Issue by bitsofinfo** [Azure/AKS#919]
Using AKS k8 1.12.7

Is the coredns "hosts plugin" functionality available in AKS and via the `coredns-custom` configmaps? 

https://github.com/coredns/coredns/tree/master/plugin/hosts

I've asked this in product support channels (per jesse's request https://github.com/Azure/AKS/issues/910#issuecomment-482191518), but given the answers I've gotten back from AKS support, I'm not sure my question/example is totally understood and they don't seem confident on their answers. Hence why I am asking here.

**Comment by mklettner** [comment]
> Is the coredns "hosts plugin" functionality available in AKS and via the `coredns-custom` configmaps?

Yes.

I had the same problem.
I've tried to overwrite the default server section in the coredns-custom config map with something like this:
```
  test.server: |
    . {
      hosts example.hosts example.org {
        10.0.0.1 example.org
        fallthrough
      }
```
Which resulted in this error:
`cannot serve dns://.:53 - it is already defined`

Until i saw `import custom/*.override` in the default section of the `coredns` configmap.
Using the override works for me:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom # this is the name of the configmap you can overwrite with your changes
  namespace: kube-system
data:
    test.override: |
          hosts example.hosts example.org {
              10.0.0.1 example.org
              fallthrough
          }
```

**Comment by jnoller** [comment]
Yes, it is supported. Adding docs label

**Comment by jnoller** [comment]
Adding this to the doc today

**Comment by jnoller** [comment]
PR is pending for the docs update

**Comment by bitsofinfo** [comment]
@jnoller and @mklettner 

I'm just trying the example listed here: https://docs.microsoft.com/en-us/azure/aks/coredns-custom#hosts-plugin

I applied the configmap on an AKS 1.13.5 cluster, i shell into a running container on a worker and lookup `example.org` and it resolves to a public ip that is different then 10.0.0.1 . 

Does not appear to work

**Comment by mklettner** [comment]
@bitsofinfo 
Sorry, I forgot to mention that i had to delete both coredns pods to force a config reload. I will edit my previous post.

Someone already opened an enhancement request for automatic config reload: https://github.com/Azure/AKS/issues/841

@jnoller I guess this should be mentioned in the docs too

**Comment by jnoller** [comment]
@mklettner Argh, Looks like I need to change the `kubectl delete pod --namespace kube-system --label k8s-app=kube-dns` command to `kubectl -n kube-system delete po -l k8s-app=kube-dns`
