### ISSUE TITLE
Static IP Outside Cluster Resource Group - 

### ISSUE THREAD

**Issue by antoinne85** [Azure/AKS#921]
I followed the directions at [https://docs.microsoft.com/en-us/azure/aks/static-ip#use-a-static-ip-address-outside-of-the-node-resource-group](https://docs.microsoft.com/en-us/azure/aks/static-ip#use-a-static-ip-address-outside-of-the-node-resource-group) to attach a static IP in a resource group other than the cluster's resource group to a `Service`.

My static IP is in a resource group named `aks-resources`.

I'll go on record saying that I suspect this is a simple permissioning issue, but as outlined below, I can't image what permissions my Service Principal is missing.

**What happened**:
The service fails to attach to the external IP with the following error:
`Error creating load balancer (will retry): failed to ensure load balancer for service ingress-nginx/ingress-nginx-ingress-controller: network.PublicIPAddressesClient#List: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '<myServicePrincipalId>' with object id '<myServicePrincipalId>' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourceGroups/<mySubscriptionId>/aks-resources/Microsoft.Network/read' over scope '/subscriptions/<mySubscriptionId>/resourceGroups/subscriptions/<mySubscriptionId>/resourceGroups/aks-resources/providers/Microsoft.Network/publicIPAddresses'."`

**What you expected to happen**:
I expected that the service would use the static IP as the external IP.

**How to reproduce it (as minimally and precisely as possible)**:
* Create a resource group
* Create a static IP in that resource group
* Deploy an AKS instance
* Provide the Owner role to the AKS Service Principal for the resource group you created the static IP address in
* Deploy the `nginx-ingress` Helm chart with the parameters `--set nginx-ingress.rbac.create=false --set nginx-ingress.controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-resource-group"=<yourResourceGroup> --set nginx-ingress.controller.service.loadBalancerIP=<yourIpAddress>`

**Anything else we need to know?**:
I don't know if it's worth mentioning, but I very carefully selected the use of the `myServicePrincipalId` and `myApplicationId` above. In the error message I'm receiving, the client ID specified is the ID of the Service Principal _not_ the Application ID.

I verified the permissions for my Service Principal with:
`az login --service-principal -u <myApplicationId> -p "<myServicePrincipalPassword>" --tenant <myActiveDirectoryTenantId>`
`az aks list` - My cluster is present.
`az resource list` - Both the resource group and the static IP are present.

`az role assignment list --scope /subscriptions/<mySubscriptionId>/resourceGroups/aks-resources` - The following roles are listed, in order of my increasing desperation:
* Network Contributor (as described in the documentation [https://docs.microsoft.com/en-us/azure/aks/static-ip#use-a-static-ip-address-outside-of-the-node-resource-group](https://docs.microsoft.com/en-us/azure/aks/static-ip#use-a-static-ip-address-outside-of-the-node-resource-group))
* Classic Network Contributor
* Contributor
* Owner

**Environment**:
- Kubernetes version: 1.12.7
- Size of cluster: 3
- General description of workloads in the cluster: Almost nothing, bringing up a fresh cluster
- Others: Cluster, service principal, role assignments all created with Terraform

**Comment by jnoller** [comment]
Pinging @iainfoulds - we've been looking at SP / AAD enhanced documentation

**Comment by iainfoulds** [comment]
What's the doc request here, @jnoller? If there's additional permissions to be noted, I just need to know what they are if the existing delegated network permissions aren't sufficient - https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal#delegate-access-to-other-azure-resources

**Comment by antoinne85** [comment]
@jnoller I may not fully understand the above exchange, but it seems there might be an issue (in this case) beyond just the documentation.

If my understanding is correct, the `Owner` role should grant the service principal what is effectively complete control over the resource group that contains my static IP, but I still get permissions errors when examining the `Service` object in Kubernetes.

Is there some other gotcha I should be aware of around the IP address?

**Comment by antoinne85** [comment]
It looks like the issue wound up being that I was fully qualifying the resource group name (e.g. `/subscriptions/xxx/resourceGroups/xxx`) when all I really needed was the resource group name.
