### ISSUE TITLE
Feature request: scripting friendly AAD auth

### ISSUE THREAD

**Issue by itowlson** [Azure/AKS#922]
**What happened**: When I run `kubectl` with an AAD cluster, it pauses with the `microsoft.com/devicelogin` prompt.  If I have a script or other client waiting for the `kubectl` output, this stalls the consumer indefinitely.  This is particularly nasty for my scenario where I have a GUI calling `kubectl` behind the scenes: the user cannot see the login prompt so is left waiting forever.

**What you expected to happen**:  More 'what would be nice' than 'what I expected' but...

It would be nice to be able to call `kubectl` with a non-interactive option, so that if the user needed to do a device login it could dump the prompt to stderr _and then exit_ rather than the consumer having to parse the output as it was produced.

This would allow scripts to fail fast, and GUIs to more easily detect the situation (and, if the user chose not to do the device login, to fail fast without needing to nuke the `kubectl` process).

**How to reproduce it (as minimally and precisely as possible)**: N/A

**Anything else we need to know?**: N/A

**Environment**: N/A

**Comment by lavanyaanbu001** [comment]
Need this feature

**Comment by weinong** [comment]
hey folks, can you chime in whether you like
1. service principal login
2. managed AAD user login
3. federated user login

thanks!

**Comment by itowlson** [comment]
@weinong What you're asking about is a slightly orthogonal issue - supporting AAD logins that can be baked into a script, e.g. via service principal credentials, or where the user doesn't need to log into kubectl at all, e.g. federated with the corporate AD.  That sounds great, but what I'm asking for is the ability to _detect_ if a login is required.  If the cluster owner is using AAD auth but _doesn't_ want to jump through the hoops of federation, I (as a script or tool calling kubectl) need the ability to recognise "hey, kubectl can't do this on the user's behalf in the current login state, I need to prompt them to log in."

The issue is about coming to the users _where they are_ - that is, using whatever kubectl setup they have - not about ways for them to reconfigure their cluster or use different credentials just so they can get the VS Code extension working.

Sorry the title and original explanation were confusing!

**Comment by JohnRusk** [comment]
@itowlson I noticed yesterday that there's a visible difference inside the config file in `<home>\.kube\config` before and after a successful kubectl login.  It's a bit ugly, but if you had no other solution, I wonder if you could check the contents of that file.
