### ISSUE TITLE
Calico logging is set to INFO

### ISSUE THREAD

**Issue by ams0** [Azure/AKS#925]
**What happened**:

Deploying calico in AKS the `calico-node` pods are set to log up to severity "INFO".

**What you expected to happen**:

A lower logging severity to avoid unnecessary waste of disk space.

**How to reproduce it (as minimally and precisely as possible)**:

Currently only available on up to 1.11 clusters because of #905 

```bash
az aks create ... --network-policy calico ...
```

**Comment by sauryadas** [comment]
@feiskyer  FYI

**Comment by feiskyer** [comment]
The INFO level would help for understanding what calico is working and troubleshooting calico issues if there's something wrong. Decrease the log level would lose such flexibility.

@ams0 How much disk space have you observed?

**Comment by palmerabollo** [comment]
related to https://github.com/Azure/aks-engine/issues/2111

In our k8s clusters (aks-engine), calico generates around 40% of the logs in the system !!

**Comment by nicksc423** [comment]
This might be better for a feature request, but the ability to change the log level would be nice

**Comment by palmerabollo** [comment]
Just in case it's useful, this is the fix in aks-engine https://github.com/Azure/aks-engine/pull/3396, making its log level configurable.

**Comment by TomGeske** [comment]
Thanks for your feedback.
I'm going ahead closing this one as it was open more than a year ago. Keep commenting or reopening if we need to revisit.

**Comment by palmerabollo** [comment]
@TomGeske I'd reopen it. For us is still an issue. Around 30% of our logs are generated by calico, so we have ended up discarding ALL its logs in the fluent-bit daemonset we use to gather our platform's logs.

**Comment by TomGeske** [comment]
+@jluk for visibility
