### ISSUE TITLE
Allow larger Pods allocation limit per node

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#93]
Please allow something more like 500 per node or at least choose something better based on node size.  I've chosen a beefy VM and I'm running out of node space much faster than CPU or Memory.

Thanks.

**Comment by slack** [comment]
Thanks for the request!

Notes:
* would require exposing `maxPods` in AKS API
* update to `--node-cidr-mask-size` in controller-manager for anything > 254
* cluster-wide pod limit with Azure CNI capped at 4096 default, up to 8192
* anything > 100 surpasses recommended k8s values https://kubernetes.io/docs/admin/cluster-large/

**Comment by Zimmergren** [comment]
Hey @slack is this something that's being considered for the roadmap ahead, or is it too risky to break the K8s defaults & recommendations?

When previously running with an other platform we had ~500 containers running on a node without any issues. We can theoretically keep the cost the same by lowering the size of the nodes and increasing the count instead, to fit the 500 pods into 5 nodes - but of course if there'll be native support for bigger deployments that'd be interesting to know too since we could then architect things a bit differently.

Thanks,
Tobias.

**Comment by slack** [comment]
Good news, we are working on exposing `maxPods` on each node pool. The first phase should land in mid-June-ish.

**Comment by seanmck** [comment]
A `--max-pods` switch is now available on `az aks create`.

**Comment by seanmck** [comment]
I believe we support it in the API now, but not in the CLI/portal. @sauryadas, can you confirm? Note that new clusters are all created with 110 by default, so there shouldn't much reason to change it going forward.

**Comment by IvanKirianov** [comment]
@sauryadas Please, could you describe workaround in details. 
Editing template is not allowed: 
{
  "code": "PropertyChangeNotAllowed",
  "message": "Changing property 'agentPoolProfile.kubernetesConfig.kubeletConfig.maxPods' is not allowed.",
  "target": "agentPoolProfile.kubernetesConfig.kubeletConfig.maxPods"
}

**Comment by IvanKirianov** [comment]
> I believe we support it in the API now, but not in the CLI/portal. @sauryadas, can you confirm? Note that new clusters are all created with 110 by default, so there shouldn't much reason to change it going forward.

If you are not create cluster with Advanced Network. This is allowed only 30 pods per node. 
Have no idea how to change it without cluster re-deploy....

Also, I have created case to MS support - update pod count on existing cluster - isn't in roadmap.

**Comment by AceHack** [comment]
@IvanKirianov it is in the API even for advanced networking. We had to blow away our cluster and start over to configure it for more than the default 30.

**Comment by mhabegger** [comment]
In case someone is searching for the terraform variant and ends up on this thread: 
https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#max_pods
