### ISSUE TITLE
Getting "Could not find member 'Sensitivity' on object of type 'TemplateResource' " Error message with  all aks binary  v0.32.0  to  v0.34.3 

### ISSUE THREAD

**Issue by satishsudhini** [Azure/AKS#932]
New aks engine version after v0.32.0 cluster installation failing with the below error message 

Azure Error: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Could not find member 'Sensitivity' on object of type 'TemplateResource'. Path 'properties.template.resources[12].Sensitivity', line 1, position 11293

**Comment by jnoller** [comment]
Please file aks-engine bugs on the AKS-Engine repository: https://github.com/Azure/aks-engine
