### ISSUE TITLE
Ability to apply node taints at node-pool level so that those taints are automatically applied to any new or replaced nodes in same node-pool

### ISSUE THREAD

**Issue by arsenvlad** [Azure/AKS#935]
**Feature Request** 

Ability to use node-pool or cluster level taints which are automatically applied to all nodes in the pool.

Taints applied to a node-pool should be automatically created when a new node is added to the pool or cluster (e.g. during autoscaling).

**Comment by Sam123ben** [comment]
Is this still open? Can anyone please test and merge it. This will be a big win

**Comment by Sam123ben** [comment]
BDW, I have my own small script which does the task nicely for aks/eks and gke. Though the EKS recently introduced the auto taint/label feature and its still a bit buggy though but it works. AKS we expect to have somehting similar.

**Comment by Benjiiim** [comment]
Isn't it related to https://github.com/Azure/AKS/issues/1061?
