### ISSUE TITLE
az aks browse hung

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#94]
az aks browse --name aks-use-arch-dev --resource-group rgp-use-arch-aks
Merged "aks-use-arch-dev" as current context in C:\Users\astainba\AppData\Local\Temp\tmp616qtw_9

Freezes at this point and never opens browser.  It's been working fine just started this behavior.

**Comment by AceHack** [comment]
I've tried rebooting and even on different computers, this seems to be a problem server side with the cluster not client side.

**Comment by AceHack** [comment]
I've manually reboot all the VMs involved in the MC_* resource group, this seems to have fixed the problem.

**Comment by mboersma** [comment]
@AceHack I'm glad you found a workaround. We haven't seen this in general and AKS has moved pretty fast. I'm going to close this issue, but please re-open if you see behavior like this again.
