### ISSUE TITLE
Kubernetes service deletion triggers the deletion of its resource group

### ISSUE THREAD

**Issue by MisterKatCodes** [Azure/AKS#942]
**What happened**: From Azure Portal a user deleted a Kubernetes Service and a operation of Deleting database accounts (as seen in the Monitor - Activity log ) started.

**What you expected to happen**: Only the Kubernetes Service to be deleted. 

**How to reproduce it (as minimally and precisely as possible)**: Create a resource group with a Kuberentes service. Associate a PostgreSQL server to it. Delete Kubernetes Service.

**Anything else we need to know?**: After the Delete Managed Cluster operation succeeded, a Delete database accounts operation started and succeeded. As seen in the operation information json for the delete database accounts the scope is "/subscriptions/{subscription_id}/resourcegroups/{kubernetes_cluster}" and the action is "Microsoft.Resources/subscriptions/resourcegroups/delete".

Am I missing out something here. Is this an expected behaviour?

**Comment by jnoller** [comment]
@MisterKatCodes Were you passing in a custom resource group, or the built in MC_ rg?

**Comment by MisterKatCodes** [comment]
@jnoller The build in MC_ rg

**Comment by jnoller** [comment]
Ok, so that is actually by design. The MC_* Resource group is not meant for users to use. When a delete occurs on the RG, it will cascade down to all resources that are part of MC_ in order to clean up all state and resources.
