### ISSUE TITLE
Unable to use the autoscale on VMSS backed AKS.

### ISSUE THREAD

**Issue by ana1993** [Azure/AKS#943]
I am trying to enable the autoscale feature on a AKS that i deployed via the portal using the az CLI using the command :

az aks update --resource-group <my-rg> --name <my-aks> --enable-cluster-autoscaler --min-count 1 --max-count 3

I am getting the following error:
Operation failed with status: 'Bad Request'. Details: Node pool update via managed cluster not allowed. Use per nodepool operations.

I was expecting that autoscaler can be enabled with VMSS backed AKS. 

- Kubernetes version : 1.12.7
- Size of cluster : 3

**Comment by jnoller** [comment]
Did you enable the preview features per: https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler, was this a pre-existing, or new cluster running on VMSS?

**Comment by jahstreet** [comment]
Have the same issue.
I've enabled the preview features as described in doc and created a new cluster with `--enable-vmss` flag, then I try to run `az aks update ...` with `--enable-cluster-autoscaler` flag and get the same error.
Kubernetes version 1.13.5, 2 nodepools with 1 node per each.

**Comment by lucaghersi** [comment]
Hi, I have the same issue here on a newly created cluster VMSS backed, 1.13.5, 1 node pool, az with aks-preview 0.4.1.

**Comment by palma21** [comment]
Yes, dup of #972. A fix for this is done and will roll out next week.

**Comment by jnoller** [comment]
Closing as duplicate
