### ISSUE TITLE
Kubernetes Audit Log Support

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#946]
This issue tracks the delivery state for Kubernetes Audit log support which is now in public preview, instructions can be found here: https://github.com/Azure/AKS/blob/master/previews.md#kubernetes-audit-log

**Comment by jnoller** [comment]
In public preview: https://github.com/Azure/AKS/blob/master/previews.md#virtual-machine-scale-sets-vmss--cluster-autoscaler

**Comment by jnoller** [comment]
Audit log support is now GA, enable master logging via: https://azure.microsoft.com/en-us/updates/aks-control-plane-audit-logs/

**Comment by alanjcastonguay** [comment]
https://azure.microsoft.com/en-us/updates/aks-control-plane-audit-logs/ still says it's Preview, not GA. Where's the GA documentation?

**Comment by andreygolev** [comment]
Are there any plans to include configurable audit webhook?
That would be helpful to leverage Falco for tracking kubernetes state changes.

**Comment by lukasmrtvy** [comment]
Unfortunatelly kube-apiserver (not only) logs (stderr) multilines and Azure Diagnostics ( dunno what is behind it) stores record per line ( linefeeds ). 
Not sure how to properly concatenate lines..

**Comment by Quiark** [comment]
The volume of audit logs is very large, more than 100 MB per day and most of them are internal calls. Any chance to make this configurable (see https://kubernetes.io/docs/tasks/debug-application-cluster/audit/) so that the volume can be made more manageable?

**Comment by shapeofarchitect** [comment]
@here May I know if we can still get some feedback on this issue , I couldn't find the documentation around the audit log enabled in AKS service configuration. It seem that Azure Log analytics and monitor has been placed which isn't abstracted and we are forced to use them , we don't know the backend storage of each event and couldn't figure the reference architecture around that event if we think of some future ideas around it. ? I would urge to re-open this and be able to track the work on audit log in AKS to be enabled by default/configurable in kube-apiserver.
