### ISSUE TITLE
Support for Cluster Autoscaler

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#947]
Tracking issue for current release state of Cluster Autoscaler support.

Note; CA support on AKS will require VMSS support as well. You can see the existing preview documentation here:

https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler

**Comment by kim0** [comment]
Any idea how far in the future this is happening? I'm planning a fairly large multi-region deployment that needs CA, and if it's not happening I'll be considering other (manual/painful) methods to resolve this issue. Thanks

**Comment by will-beta** [comment]
Can I ask when will this land in azure.cn?
Thanks!

**Comment by jnoller** [comment]
@kim0 the autoscaler is in preview, please see the link in the issue. Same for your question @will-beta. It’s in public preview, check the link.

**Comment by will-beta** [comment]
Hi, @jnoller ,as [Preview - Automatically scale a cluster to meet application demands on Azure Kubernetes Service (AKS)](https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler) mentioned, I executed the command `az feature register --name VMSSPreview --namespace Microsoft.ContainerService`, but got the following result:
```
Once the feature 'VMSSPreview' is registered, invoking 'az provider register -n Microsoft.ContainerService' is required to get the change propagated
The feature 'VMSSPreview' could not be found.
```
Does it mean the autoscaler in preview is still not available in azure.cn?

**Comment by kim0** [comment]
From my side, I was asking about the possible ETA to have this as GA. No
commitments ofc, just your best guess. Something like Q3 this year is what
I'm after.

**Comment by jnoller** [comment]
@will-beta Ah, I can not comment on preview feature availability in China regions as they do lag behind the public cloud regions and is still in public preview.

@kim0 We're planning on this going out in the next 1-2 months barring significant bug fixes (such as vmss integration, etc)

**Comment by will-beta** [comment]
@jnoller Any updates on the possible ETA?

**Comment by tomkerkhove** [comment]
Will it come with capability to configure cluster autoscaler via ARM / Azure Portal?

**Comment by chaos-panda** [comment]
Is there any ETA on having this GA?

**Comment by tomkerkhove** [comment]
@jluk Thanks! Looking forward to portal support!

**Comment by sowens81** [comment]
@jluk - do you have any more news on the GA for AKS AZ's. I have a customer in the UK who is keen on going live on AKS by December, but needs to reduce the risk of taking a preview feature into production.

**Comment by palma21** [comment]
To clarify this thread if for Cluster AutoScaler not AZs.

Nonetheless both will be GA before December. :)

**Comment by sowens81** [comment]
My apologies, I had both issues open and messaged in the wrong one. Thanks for the feedback.

**Comment by jluk** [comment]
This feature is now generally available. Closing, if you encounter any further questions or issues feel free to open a new issue.
