### ISSUE TITLE
Consider first class Istio Mesh Expansion support

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#95]
Also created a issues on Istio's site.
https://github.com/istio/istio/issues/2328

This would include updating setupMeshEx.sh and setupIstioVM.sh in istio or creating an Azure alternative that will support Azure LBs and such.

This also would indicate that private non-public IP LBs could be created in AKS and other VMs outside of AKS could reach those LBs.

Read here for more info on requirements.

https://istio.io/docs/setup/kubernetes/mesh-expansion.html

A good service mesh is something that's really needed in AKS.

**Comment by rajpolaris** [comment]
This will very helpful.

**Comment by seanmck** [comment]
Please add this request in our feedback forum:

https://aka.ms/aks/feedback

**Comment by alexsandro-xpt** [comment]
+1
