### ISSUE TITLE
Virtual Machine Scale Sets/Aks-Autoscaler via ARM template

### ISSUE THREAD

**Issue by adhodgson1** [Azure/AKS#950]
Hi,

I am looking to use the AKS Autoscaler feature alongside VMSS (preview features) on AKS 1.13.5.  I have these features working when using the Azure Command-Line tool as per the documentation, but I am trying to get this working using an ARM template.

Here is a fragment of the template I am using:

        "agentPoolProfiles": [
          {
[...]
            "maxCount": "3",
            "minCount": "1",
            "enableAutoScaling": "true",
            "type": "VirtualMachineScaleSets "
          }
        ]

When I do an Az aks show on the resource I see the following which is incorrect and seems like the default behaviour:

  "agentPoolProfiles": [
    {
      "availabilityZones": null,
      "enableAutoScaling": null,
      "maxCount": null,
      "minCount": null,
      "type": "AvailabilitySet",
[...]
    }
  ],

Is there anything I am missing?

**Comment by neumanndaniel** [comment]
Here is the AKS template reference:
- https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2019-02-01/managedclusters

Example ARM tempalte:
- https://github.com/neumanndaniel/armtemplates/blob/master/container/aks.json

**Comment by adhodgson1** [comment]
This turned out to be an API version issue where the CI was overwriting the API version with an older value.

**Comment by mohdumaira** [comment]
@adhodgson1 : Can you please share the ARM template and param file you are using. I am facing similar issue. Version seems to be correct as per document https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2019-02-01/managedclusters
