### ISSUE TITLE
How to retain VM specs on k8s version upgrade?

### ISSUE THREAD

**Issue by rewt** [Azure/AKS#953]
**What happened**:
`--node-vm-size` and `--node-osdisk-size` were upgraded after initial k8s cluster deployment.  Upon upgrading k8s version after aforementioned specs updated, VM size + os disk were reverted to initial deployment specs.

**What you expected to happen**:
k8s to upgrade and retain current settings (`--node-vm-size` and `--node-osdisk-size`)

**How to reproduce it (as minimally and precisely as possible)**:
upgrade k8s to latest version

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Elasticsearch + Prometheus + other microservices
- Others:

Is there a way to update existing saved AKS cluster build template?  It is not currently feasible to rebuild this cluster and would be nice to somehow retain current VM specs when performing k8s upgrades and other operations.

**Comment by jluk** [comment]
Closing this due to staleness and nodes cannot be customized in AKS. Any node level customization needed will require a daemonset run by the user to customize nodes or to open new asks on these issues for missing scenarios to be supported by the node.

#1532 is a more updated conversation
