### ISSUE TITLE
is forbidden: User "system:serviceaccount:default:***" when using Azure DevOps Release Pipeline

### ISSUE THREAD

**Issue by Li-Yanzhi** [Azure/AKS#954]
**What happened**:

When using Azure DevOps Release Pipeline to deploy resource to AKS cluster, get error message of: 

> [command]C:\...\kubectl.exe apply -n cmb -f "D:\a\r1\a\myapp\drop\sample-api.yaml" -o json
> Error from server (Forbidden): error when retrieving current configuration of:
Resource: "/v1, Resource=services", GroupVersionKind: "/v1, Kind=Service"
> Name: "sample-api", Namespace: "xyz"
> Object: &{map["apiVersion":"v1" "kind":"Service" "metadata":map["labels":map["api":"sample" "app":"myapp" "tier":"backend"] "name":"sample-api" "namespace":"xyz" "annotations":map["kubectl.kubernetes.io/last-applied-configuration":""]] "spec":map["ports":[map["port":'P' "targetPort":'\u1f90']] "selector":map["api":"sample" "app":"myapp" "tier":"backend"]]]}
> from server for: "D:\\a\\r1\\a\\myapp\\drop\\sample-api.yaml": **services "sample-api" is forbidden: User "system:serviceaccount:default:\*\*\*" cannot get resource "services" in API group "" in the namespace "xyz"**
>  ##[error]C:\hostedtoolcache\windows\kubectl\1.13.2\x64\kubectl.exe failed with return code: 1
> ##[section]Finishing: kubectl apply sample-api

**What you expected to happen**:

Deploy without error

**How to reproduce it (as minimally and precisely as possible)**:

1.  Create AKS cluster
2.  Setup Azure DevOps Release Pipeline with "Deploy to cluster" task

**Anything else we need to know?**:

I have use the following command to configure role for default:default and the error still exists:
> kubectl create clusterrolebinding default-admin --clusterrole cluster-admin --serviceaccount=default:default

I saw the use in error message is "system:serviceaccount:**default:\*\*\***" rather than **"default:default"**,  I cannot find any information what the user of "default:\*\*\*" is.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.7
- Size of cluster (how many worker nodes are in the cluster?) : 2 node
- Others:

**Comment by Li-Yanzhi** [comment]
Fixed issue by granting the read-only permission for group system:serviceaccounts:

`kubectl create clusterrolebinding azure-devops-deploy --clusterrole=view --group=system:serviceaccounts --namespace=xyz`

**Comment by Li-Yanzhi** [comment]
Issue fixed.

**Comment by tanwarsatya** [comment]
why these permissions are needed and if needed why they are not enabled by default when creating a service connection. Is this documented somewhere ?
