### ISSUE TITLE
Roll out aks-engine 0.33.6

### ISSUE THREAD

**Issue by victornoel** [Azure/AKS#957]
**What happened**:

Following the deployment of aks-engine 0.32.0 on AKS, the following bug started to appear for all Java-based containers that relies on cgroup: https://bugs.openjdk.java.net/browse/JDK-8217766

In practice this means that Java-based containers, instead of using as much memory as the limits specified in the pod resources, will use as much memory as the node has.

Luckily this happened only last week on our cluster (because the nodes hadn't been updated for some time), but pods started to crash repeatedly because of it.

**What you expected to happen**:

The containers to honour the limits imposed on them.
To achieve that, aks-engine 0.33.6 should be deployed as soon as possible.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a container with, for example, adoptopenjdk/openjdk11, and run on it:
```sh
java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
```

This will show that MaxHeapSize will be a percentage (MaxRAMFraction) of the node memory instead of the limits.

Run
```sh
java -Xlog:os+container=trace -version
```

An error message says:
```
[0.000s][trace][os,container] OSContainer::init: Initializing Container Support
[0.001s][debug][os,container] Required cgroup cpuset subsystem not found 
```

**Anything else we need to know?**:

I've opened a support request where it was said to me that aks-engine 0.33.6 was going to be deployed at the end of the month, but I believe it's too late since it potentially impact all of AKS users running Java-based containers.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.27
- Size of cluster (how many worker nodes are in the cluster?) : 6
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) : Java apps, 5 small memory footprint (~128M), 2 bigger memory footprint (~2G).
- Others: aks-engine 0.33.4

**Comment by jnoller** [comment]
Updating to a newer AKS-Engine release is targeted for next week's release barring any unforseen issues.

**Comment by jnoller** [comment]
The new AKS-Engine version with the fix is in Australia and Canada regions and will continue to rolling out to all regions

**Comment by victornoel** [comment]
@jnoller thanks for the heads up :)
