### ISSUE TITLE
Terraform aks to support preview features

### ISSUE THREAD

**Issue by evertonmc** [Azure/AKS#958]
there is currently no way to test VMSS, Multi Node Pool, and/or Autoscaler support for Terraform deployments

**Comment by evertonmc** [comment]
@jnoller would you please provide more information about the reason for you to "close" this issue? 
no dupe, no commit, no pr, no reason?

**Comment by jnoller** [comment]
Actually totally may bad, I was browsing on mobile, thanks for pinging 

As for terraform support for preview features; landing support for preview features outside of the AKS-preview CLI and ARM templates is not planned. Preview features, APIs etc are not stable and the terraform releases do not align well with AKS releases and functionality additions

We do track integration for our GA features. I can leave this here as an enhancement request

**Comment by evertonmc** [comment]
You are right. Probably terraform should support preview providers first. I hope it will be possible in the future, since nobody is really CLI'ing the cluster in CI/CD workflows nowadays

**Comment by neumanndaniel** [comment]
There is a PR for VMSS and cluster autoscaler support. Just waiting for to be merged.

- https://github.com/terraform-providers/terraform-provider-azurerm/pull/3174

**Comment by jnoller** [comment]
@evertonmc Minor correction, I am saying that support beyond the CLI and ARM is out of scope for Terraform, it is not prioritized due to what I outlined

**Comment by palma21** [comment]
Closing since the support for the requested feature is there

Any feature request for terraform support can be done directly in 
https://github.com/terraform-providers/terraform-provider-azurerm
