### ISSUE TITLE
Locked down cluster egress support

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#959]
Tracking issue for feature work

By default, AKS clusters have unrestricted outbound (egress) internet access. This level of network access allows nodes and services you run to access external resources as needed. If you wish to restrict egress traffic, a limited number of ports and addresses must be accessible to maintain healthy cluster maintenance tasks.

**Comment by jnoller** [comment]
This is now in public preview, please see:
https://github.com/Azure/AKS/blob/master/previews.md#locked-down-cluster-egress

**Comment by b4rkieMS** [comment]
Hi Jesse, any idea when this will GA? Also, what's the long term implications of managing a set of restrictions?  For example, if a new port/address is added or changed then what is the mechanism to get notified before a cluster potentially fails to update/patch?  Thanks.

**Comment by jnoller** [comment]
https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic#required-ports-and-addresses-for-aks-clusters - this document tracks all required ports and URLs.
