### ISSUE TITLE
Please create deep dive networking documentation for AKS

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#96]
Looking to cover topics like this

[The ins and outs of networking in Google Container Engine and Kubernetes (Google Cloud Next '17)](https://www.youtube.com/watch?v=y2bhV81MfKQ)
[Life of a Packet (Network Policy)](https://youtu.be/0Omvgd7Hg1I?t=1555)

And deeper too, like IPv6, daemon sets, service mesh, virtual kubelets, CNI plugins like calico and others, windows vs linux networking, IPAM, headless service, liveness probes, graceful termination, firewalls, ssl, cloud health checks, and please cover all these tops for linux and windows.

**Comment by slack** [comment]
Feedback noted on AKS networking. I will jot down some notes as we go into our next docs review.

Much of the vanilla Kubernetes functionality like headless services, liveness probes, and graceful termination are pretty well covered in upstream documentation.
