### ISSUE TITLE
Secure access to the API server using authorized IP address ranges

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#967]
Within AKS the default API server created as part of the customer cluster is assigned a public IP address. In order to provide more restricted access AKS should support setting a list of IP addresses (controlled by the customer) to allow or deny access to the API server.

Tracking issue for feature.

**Comment by poochwashere** [comment]
Hi Jesse,

We are very much looking forward to this functionality. Is there a _rough_ ETA as to when this may be GA? 

Thanks

**Comment by jnoller** [comment]
@sauryadas

**Comment by sauryadas** [comment]
possibly end of September.. but you should be able to use it now.. create a cluster with a SLB and whitelist the IP address created along with the CIDR range you want your api server accessed from. We are in the process of updating the API server authorized range docs with the above.
[SLB docs](https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard)

**Comment by poochwashere** [comment]
The problem with my org using the SLB is that we cannot preserve our sticky Public IPs that we need to control for partners to access our APIs.  

Per the SLB docs...
```
When using the Standard SKU for a load balancer in AKS, you cannot set your own public IP address for egress for the load balancer. You must use the IP address AKS assigns to your load balancer.
```

**Comment by jnoller** [comment]
This is now GA

**Comment by yaariyuval** [comment]
@jnoller where can we find documentation describing how to enable this feature?

**Comment by jnoller** [comment]
https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic

**Comment by slynickel** [comment]
Is that the right link? Limiting egress traffic controls outbound restrictions. This Github issue is tracking this feature, correct: https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges. Which would appear to still be in preview? Unless the doc on api-server-authorized-ip-ranges has fallen out of date?

**Comment by jnoller** [comment]
Oh heck (i stopped drinking coffee), you're right, and yes - the docs are not up to date (the ones you linked), we're waiting on the docs to build and publish.

**Comment by jnoller** [comment]
@slynickel You're right - I inverted it. @yaariyuval https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges is the link and will be going GA soon. I closed the wrong issue.

**Comment by matt-bentley** [comment]
is there any update on when this will be going GA please?

**Comment by slynickel** [comment]
Is this still in preview or is it now GA? I've noticed that the documentation for this features no longer states `(preview)` in the name and no longer requires turning on a preview feature gate. If this is not GA I'll open a doc issue.

https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges

**Comment by sauryadas** [comment]
Its GA now.. You can now enable the feature at create.. docs for that should be updated by early next week ... You can install the azure cli v 2.0.76 and try out the create scenario.
https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.0.76
