### ISSUE TITLE
Multi-nodepool AKS cluster with ARM template

### ISSUE THREAD

**Issue by marcinkoperski** [Azure/AKS#972]
**What happened**: 'm hitting an issue while deploying AKS cluster with multiple pools using ARM template (apiVersion 2019-02-01, type: Microsoft.ContainerService/managedClusters). Works fine for the first time, but when I try to run the same ARM template against already created AKS cluster (no change made to the ARM template) it fails with message: "{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"code\": \"OperationNotAllowed\",\r\n \"message\": \"Node pool update via managed cluster not allowed. Use per nodepool operations.\"\r\n}"}]}"

**What you expected to happen**: ARM template should be applied successfully when no change was made to the cluster (the same ARM template applied more than once). Ideally ARM template should be applied successfully when there are modifications to the cluster in it.

**How to reproduce it (as minimally and precisely as possible)**: Create ARM template type: Microsoft.ContainerService/managedClusters with more than 1 nodepool (apiVersion 2019-02-01). Deploy the ARM template at least twice without any changes to it.

**Anything else we need to know?**: Multiple nodepool support is in preview. Tested on 13.05.2019

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.5
- Size of cluster (how many worker nodes are in the cluster?): 2 node pools, 1 VM each.
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Empty cluster
- Others:

Cluster created by running this command:
az group deployment create --name kubernetes-01e2346b-94ed-4de1-8c97-29b26211cd83 --resource-group <> --template-file /ansible/roles/azure.aks/files/aks-arm-template.json --parameters resourceName=<> location=westeurope dnsPrefix=<> servicePrincipalClientId=<> linuxSshPublicKey=<> networkPlugin=azure serviceCidr=10.133.128.0/17 dnsServiceIP=10.133.128.4 dockerBridgeCidr=10.134.0.1/16 vnetSubnetID=<> maxPods=100 enableHttpApplicationRouting=false kubernetesVersion=1.13.5

ARM template file:
[aks-arm-template.json.txt](https://github.com/Azure/AKS/files/3176742/aks-arm-template.json.txt)

**Comment by sauryadas** [comment]
@jluk @xizhamsft Please take a look

**Comment by palma21** [comment]
I see you used Cluster Autoscaler with nodepools is that correct?

Currently during preview we're still ironing the CA support for nodepools. We've fixed the issue that triggers this error and that should come out on next week's release.

**Comment by marcinkoperski** [comment]
@palma21 Yes, I was using Autoscaler. After disabling the Autoscaler in ARM template, the issue is no longer visible. Thank you! When exactly this incompatibility will be fixed ?

**Comment by palma21** [comment]
Should be in next week's release. We'll drop a note here to confirm when it's rolled out to all regions and it will also be part of our release notes. 
Thanks for confirming!

**Comment by palma21** [comment]
Hi @kjarus 
What is your ARM template?

**Comment by kjarus** [comment]
Hi @palma21, this is my [template](https://gist.github.com/kjarus/d697d8bc5fbba31dc59722d7fe962ae6).

**Comment by kjarus** [comment]
Hi @palma21 - thanks for your attention. My ARM template can be found [here](https://gist.github.com/kjarus/d697d8bc5fbba31dc59722d7fe962ae6/revisions)

**Comment by xizhamsft** [comment]
Hi @kjarus, do you have autoscaler settings in your initial template? If so, then you will get the error even after you change enableAutoScale to false. This issue is fixed and will rollout soon. 
For now, if you don't need auto scaler, then just leave out all the auto scaler related settings from you arm template and apply it again should work. 
Note: you can't change ANY agent pool properties in the managed cluster template. With multi agentpool, any changes to agent pool should be through agent pool resource.

**Comment by RaghavendraSingh** [comment]
Hi @xizhamsft 

I got the same error while updating auto scale configs of a vmss aks deployment via kubectl aks

```az aks update   --resource-group <RG name>   --name <AKS name>   --update-cluster-autoscaler   --min-count 3   --max-count 6 --subscription <subs-id>

Operation failed with status: 'Bad Request'. Details: Node pool update via managed cluster not allowed. Use per nodepool operations.```

I have multi nodepool  enabled athough I only have 1 nodepool running

I am assuming the above fix should solve my problem as well
Is there an update on when this would get released?

**Comment by jahstreet** [comment]
Faced the same behavior, managed to setup autoscaling for multiple nodepools manually with Cluster Autoscaler Helm chart: https://github.com/helm/charts/tree/master/stable/cluster-autoscaler

Kubernetes v1.13.5 on AKS with RBAC enabled
Cluster Autoscaler chart v0.13.1

custom-values.yaml:
cloudProvider: azure
autoscalingGroups:
- name: aks-agentpool-xxxxxxxx-vmss # use VMSSs names rather than nodepool names
  minSize: 1
  maxSize: 10
- name: aks-sparkpool-xxxxxxxx-vmss # use VMSSs names rather than nodepool names
  minSize: 1
  maxSize: 10
azureVMType: vmss
azureClientID: "<client_id>"
azureClientSecret: "<client_secret>"
azureSubscriptionID: "<subscription_id>"
azureTenantID: "<tenant_id>"
azureResourceGroup: MC_<aks_rg>_<aks_nodes_rg>_<location>
rbac:
    create: true

Hope it will help.

**Comment by xizhamsft** [comment]
@RaghavendraSinghm, unfortunately, multi-agent pool cluster dose not work well with cluster auto scaler. I am working a fix. For now, please don't mix multi-agent pool cluster with auto scaler.

**Comment by marcinkoperski** [comment]
Hi @xizhamsft . I tried to create multi-nodepool cluster with ARM template with cluster autoscaler enabled only on the secondary nodepool, and it works well besides the possibility to do any changes to the nodepool with ARM template (i.e. changing "maxCount" fails with the known error: "OperationNotAllowed"). Do you know when can we expect fix for that ?

**Comment by xizhamsft** [comment]
@marcinkoperski . Yeap, I already fixed the auto scaler for mutli agent pool. Should go out with the next release. Probably next week.

**Comment by KIRY4** [comment]
Hi @xizhamsft. Could you please confirm that next release with your fix will be between 10-16 june? In our company we are waiting for this fix very much!

**Comment by neginmr** [comment]
Is this fix released?

**Comment by xizhamsft** [comment]
@neginmr, yes. It is released. Please give it a try

**Comment by KIRY4** [comment]
@xizhamsft hi maybe you know when autoscale for multiple node pools will be released? I mean for example I have 3 node pools and each of them autoscaling enabled and have min/max-count to limit autoscaling?

**Comment by xizhamsft** [comment]
@KIRY4 , per nodepool autoscaler release is done this week. You can start trying it now using azure cli extension. Make sure to remove and reinstall aks-preview to get the latest cli extention. The help will show you how to enable/disable/update per node pool auto scaler settings.

**Comment by kim0** [comment]
@xizhamsft .. Thanks just updated and see `az aks nodepool` has the needed options. Will a cluster created today, with multiple nodepools, and cluster-autoscaler, be upgradeable into a supported cluster once those features GA ? Thanks!

**Comment by jluk** [comment]
Closing this issue as the fix looks good.

@kim0 yes, if your cluster is only utilizing GA features then it will be a supported cluster. Please reference this document for full details: https://docs.microsoft.com/en-us/azure/aks/support-policies
