### ISSUE TITLE
AKS Autoscale Information

### ISSUE THREAD

**Issue by ChrisRG711** [Azure/AKS#975]
**What happened**:
We are working with the preview feature for AKS Cluster Autoscale. We have it all setup with the VMSS support. However in our tests it does not scale/add nodes. We get errors that 0/2 nodes are available and no more replicas can be added. A while later i did see it add one node but a lot of replicas are still red/failed. What is the best way to go about troubleshooting this. I looked at the autoscale status. but it did not show any errors. I recall doing something similar with the Regular Kubernetes autoscale and was able to pour through some logs to find the issues. But i cant find anything in the logs about this? What logs to look at? and if you are feeling generous. What are you seeing for amount of time the cluster takes to add a node and those pod add failures to go away?

Searching logs. add replicas slower

**What you expected to happen**:
i had expected to see that when a pod was unable to be scheduled due to resources, that the cluster would add another node so that the pod could be scheduled. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Running V 1.12.6 with cluster autoscale enabled minimum 2 maximum 6
**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by palma21** [comment]
Hi @Netdoc41, this is for Cluster Autoscaler correct?
Have you followed https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler without any issues? 

Could you check the controller-manager logs?
https://docs.microsoft.com/en-us/azure/aks/view-master-logs

And that your service principal credentials haven't expired?
https://docs.microsoft.com/en-us/azure/aks/update-credentials

Also please do open a support ticket with us so we can quickly take a look at your cluster.

**Comment by jluk** [comment]
@ChrisRG711 could you take a look at @palma21 advice above and let us know your findings if this is still occurring?

**Comment by ChrisRG711** [comment]
@palma21 @jluk  I opened a ticket with MS Support and ended up walking through several things including using the cloud shell and bash. The fix was 2 fold. something in cap sensitivity for the subnet name and then post that changing the service cidr to prevent a overlap with another subnet

**Comment by jluk** [comment]
@chrisrg711 thanks for confirming, I'm assuming this was resolved then so closing the ticket. If you need help with other service issues support tickets are always the fastest route to resolution, but we will try to respond to issues here as well. Thanks for initial report.
