### ISSUE TITLE
Please add support for Internal Load Balancer

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#98]
Please add support for Azure's internal load balancer

**Comment by evillgenius75** [comment]
There is support for an Internal Load Balancer. You need to add an annotation to your service manifest for any services you want exposed with an internal Load Balancer:
metadata:
    name: my-service
    annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
[...]

**Comment by slack** [comment]
Closing issue, will add note to update docs.

**Comment by torstenkuhn77** [comment]
I tried the Annotation tag but got an error on deployment. 
Is it possible to get type=Loadbalancer with a private IP adress?

**Comment by tslavik** [comment]
I have a problem with internal load balancer on AKS in westeurope (k8s 1.9.2) When I create a new service with service.beta.kubernetes.io/azure-load-balancer-internal: "true" no IP (External endpoint) is created. I can see "EnsuringLoadBalancer" from service controller over and over. For us it is a quite big issue, cause we upgrade cluster to 1.9.2 and now I can not dowgrade to working version.

**Comment by feiskyer** [comment]
There are some ILB issues in kubernetes 1.9.0-1.9.3, upgraded to 1.9.4 could fix the problem. But I'm afraid it needs some time for AKS adding the new version.

**Comment by tslavik** [comment]
OK. Could you tell some estimation when 1.9.4 will be available in AKS? And why we can't downgrade to 1.8.x? Is it still valid the term of GA for AKS? (1Q2018)

**Comment by alexvicegrab** [comment]
Also an issue for me.
