### ISSUE TITLE
Support for pre-created/provisioned Resource Group on create

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#981]
AKS Recently rolled out support to pass in the name (defined by the user) which is then applied to all resources within the AKS cluster.

This card tracks the ability to pass in a pre-provisioned (and configured) RG and to have that RG used by all resources within the cluster.

**Comment by AnassKartit** [comment]
Hi Jesser, does that mean we can now provision AKS clusters in an existing RG or in the same RG along with node pools?

**Comment by jluk** [comment]
Closing for now due to staleness, will revisit in the future if needed.
