### ISSUE TITLE
[Feature] Azure Spot support for AKS node pools

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#982]
Tracking issue for Azure Spot node pool support in AKS.

**Comment by jluk** [comment]
With the recent releases/updates to Azure low-priority and Spot, this feature is updating to the new Spot structure.

**Comment by jluk** [comment]
This has been released in public preview, visit aka.ms/aks/spot to learn more!

**Comment by soharaki** [comment]
Hi, I have a question.

How do I know if SpotInstance is 30 seconds away?

The [URL link](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/scheduled-events#endpoint-discovery) mentions an endpoint that can get the event. I have to keep calling the endpoint with polling, don't I?

Are there any other triggers that can register an eviction event?

**Comment by jayush** [comment]
Is there a timeline for when this feature will be GA'ed?

**Comment by thejosephstevens** [comment]
One note: thanks for releasing spot support in AKS! The specific limitations that are imposed on spot usage are a pain to work around though.

Specifically, tainting all the spot nodes and requiring the default pool to be standard priority are both unnecessary and frustrating to deal with. We have an extra dummy standard priority node in all of our compute clusters due solely to these requirements. Neither AWS nor GCP have these requirements and the added flexibility makes them much easier to customize for our use cases without any added complexity (and added points of failure) from mitigating the cloud provider limitations. Can these limitations be removed or at least made configurable?

**Comment by irniaxsep** [comment]
what is the ETA for the feature general availability?

**Comment by 4c74356b41** [comment]
@jluk hey, any updates to the Spot instances eviction events story? Are we supposed to have a custom scheduler to handle those? Can Azure implement something like [AWS node termination handler](https://github.com/aws/aws-node-termination-handler)?

**Comment by gkaleta** [comment]
Hey @jluk, can we move this to GA?

**Comment by mtparet** [comment]
It is still not possible to run critical components (kube proxy/corends/calico/metric server/tunnelfront) on spot instances so it cannot be considered as GA now as it prevents a correct usage of spot instances on production.

**Comment by 4c74356b41** [comment]
huh? why would it matter? thats the whole point of spot instances. you cant have same service but cheaper. running system services is not supported on user node pools, only on system node pools. system node pools cant be deployed using spot instances.  so I'm not sure what you are talking about @mtparet

**Comment by mtparet** [comment]
Because of this limitation in addition of `tolerations` to add everywhere, we also have to add `nodeSelector` to ensure pods will be running on the spot instance pools. Otherwise the no-spot instance pool could be filled up and critical components will failed to be scheduled.

**Comment by 4c74356b41** [comment]
you have priority classes for that, system components have a priority of 2000000000, you cant set such a high priority for non system\node components, so this doesn't matter as well.

**Comment by mtparet** [comment]
If the node is already filled up, it will not evict already running pods to run pending pods, so the priority is not useful in this case.

**Comment by mtparet** [comment]
I think this is linked to https://github.com/Azure/AKS/issues/1719

**Comment by 4c74356b41** [comment]
```
If the node is already filled up, it will not evict already running pods to run pending pods, so the priority is not useful in this case.
```

thats just not right

**Comment by mtparet** [comment]
cf https://github.com/Azure/AKS/issues/982#issuecomment-704182310
> Because of this limitation in addition of tolerations to add everywhere, we also have to add nodeSelector to ensure pods will be running on the spot instance pools. Otherwise the no-spot instance pool could be filled up and critical components will failed to be scheduled.

The system node pool could be filled up in this case and system services unable to be started because the system node pool is filled up.

> so this whole complaint doesnt make any sense.

Please stay nice, this does not help anyone.

**Comment by palma21** [comment]
A few updates

a) We just released pod toleration restriction to simplify the usage and the task of scheduling on Spot and other tainted pools
b) You can use https://github.com/awesomenix/drainsafe in order to listen to events and drain nodes automatically if an event comes in. We'll be working on having that by default on Spot Pools
c) GA is planned for November
