### ISSUE TITLE
[Feature] Assign a public IP per node in a node pool profile

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#983]
Tracking issue for AKS to support optional Public IPs per node in a node pool. This feature would allow customers to enable access to a given node directly as opposed to through a load balancer.

**Comment by dazmsft** [comment]
Can you confirm that this is for both Windows and Linux VM's in the node pool.

**Comment by jluk** [comment]
@dazmsft yes this should work for both, given it is in preview state let us know your findings though.

**Comment by jluk** [comment]
This is available today for basic load balancer configurations, but the support for standard load balancers is coming in early CY20Q2.

https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#assign-a-public-ip-per-node-in-a-node-pool

**Comment by jluk** [comment]
This feature is still in development and intending to GA.

A known issue in the experience is a reliance on the VMSS API to retrieve node public IPs. This is an active limitation of Azure Standard IP addresses not being supported by instance metadata service. Once this constraint is lifted, AKS will enable retrieval of IPs through AKS/K8s native methods.

**Comment by rchernobelskiy** [comment]
Hi @jluk, do you know if there are still plans to enable public IP retrieval from metadata service? Specifically I'm interested in being able to see the public IPs when for example doing `kubectl get nodes -owide`

**Comment by aristosvo** [comment]
@jluk How should we influence the NSG attached to the NICs of this IP? At this moment the only way seems to edit the AKS managed NSG manually, which seems a bit dangerous to me. See also: https://github.com/terraform-providers/terraform-provider-azurerm/issues/10233

**Comment by rchernobelskiy** [comment]
@palma21 do you happen to have an update on setting external ips on nodes so they're visible in k8s?
