### ISSUE TITLE
Add ability to unregister preview features

### ISSUE THREAD

**Issue by ToruMakabe** [Azure/AKS#984]
**What happened**:
After registration MultiAgentPoolPreview feature, unsupported tools such as Terraform fails. Also some features are disabled on Azure Portal. I would like to unregister the preview feature.

**What you expected to happen**:
Although there is a note of caution about the risk of preview on the doc, the issue have a high impact because it is subscription-wide problem. I hope Azure provide preview unregistration option through CLI/Portal/etc.

**How to reproduce it (as minimally and precisely as possible)**:
Azure CLI/Portal do not provide unregistration feature, so I tried to do it with REST API with armclient, but it seems unsupported with regard to MultiAgentpoolPreview. Not sure about the other preview features.

```
$ armclient post /subscriptions/mysubscription/providers/Microsoft.Features/providers/Microsoft.ContainerService/features/MultiAgentpoolPreview/unregister?api-version=2015-12-01
{
  "error": {
    "code": "FeatureUnregistrationUnsupported",
    "message": "The feature 'MultiAgentpoolPreview' being unregistered must be an Application Owned Feature."
  }
}
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.5
- Others:
Related issue https://github.com/Azure/azure-cli/issues/8941

**Comment by jnoller** [comment]
Currently we are working with the ARM team for the deregister work. It is not currently supported.

**Comment by ToruMakabe** [comment]
@jnoller I got it. Thanks!

**Comment by jnoller** [comment]
Reopening as de-registration is still in plan

**Comment by kim0** [comment]
@jnoller .. To be clear, is there absolutely no way today to un-register those preview features ? That would be a bummer!

**Comment by jnoller** [comment]
Correct

**Comment by masonhuemmer** [comment]
Would unregistering the Container Services Provider and re-registering provide a workaround to this issue?

**Comment by neumanndaniel** [comment]
Afaik not.

**Comment by jluk** [comment]
We've spoken with the ARM team who has acknowledged this ask and is working towards an ETA. FYI @KrisBash

**Comment by fhryo-msft** [comment]
Do we have an ETA on this?

**Comment by jluk** [comment]
@KrisBash any ETA on this?

**Comment by jluk** [comment]
Adding @ifeoluwaokunoren who has been delivering this to provide an update.

**Comment by scottstout** [comment]
@ifeoluwaokunoren any update on where this is? I see it is in 'public preview' but I'm not clear what is in public preview. I *think* this is the documentation for the REST api:
https://docs.microsoft.com/en-us/rest/api/resources/features/unregister

I haven't see anything on azure cli support.

**Comment by jluk** [comment]
The current estimate for ARM support of unregister in azure cli is planned for the month of May, ongoing.

**Comment by jluk** [comment]
The open PR is here, tracking for S171 release on 6/23

https://github.com/Azure/azure-cli/pull/13487

**Comment by jluk** [comment]
This has been released and is now supported from Azure CLI version 2.8.0. Closing as a result.
```
➜  ~ az feature -h
 
Group
    az feature : Manage resource provider features.
 
Commands:
    list       : List preview features.
    register   : Register a preview feature.
    show       : Gets the preview feature with the specified name.
  unregister : Unregister a preview feature.
```
