### ISSUE TITLE
Network profile error with virtual-node add-on

### ISSUE THREAD

**Issue by inuvano-labs** [Azure/AKS#986]
**What happened**:

After provisioning a new AKS - enabling the "virtual-node" via "az aks enable-addons" results in the aci-connector-linux pod in "CrashLoopBackoff" status.

Interrogating logs shows the following:

time="2019-05-17T08:54:54Z" level=fatal msg="Error initializing provider" error="error setting up network profile: subnet '/subscriptions/<subscriptionid>/resourceGroups/<resourcegroup>/providers/Microsoft.Network/virtualNetworks/<vnet_name>/subnets/aks-virtual-nodes' is not found in vnet '<vnet_name>' in resource group '<resourcegroup>' and subnet CIDR is not specified" namespace= node=virtual-node-aci-linux operatingSystem=Linux provider=azure"

(resource names redacted)

![image](https://user-images.githubusercontent.com/25332352/58018711-746a1500-7afb-11e9-9472-78903d1efa27.png)

**What you expected to happen**:

Following the tutorial on enabling virual-nodes via CLI (https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli), I run the enable-addons command which succeeds.

When executing "kubectl get pods --all-namespaces", the "aci-connector-linux" pod is in "Ready" status

**How to reproduce it (as minimally and precisely as possible)**:

Create the cluster:

`az aks create 
    --resource-group $resourceGroup 
    --name $name 
    --node-count 1 
    --generate-ssh-keys 
    --aad-server-app-id $serverApplicationId 
    --aad-server-app-secret $serverApplicationSecret 
    --aad-client-app-id $clientApplicationId 
    --aad-tenant-id $tenantId 
    --network-plugin azure 
    --service-cidr $serviceCidr 
    --dns-service-ip $dnsIpAddress 
    --docker-bridge-address 172.17.0.1/16 
    --vnet-subnet-id $vnetSubnetId 
    --service-principal $clusterApplicationId 
    --client-secret $clusterApplicationSecret 
    --kubernetes-version "1.12.6" `

Enable virtual-node addon:

`az aks enable-addons 
    --resource-group $resourceGroup 
    --name $name 
    --addons virtual-node 
    --subnet-name $virtualNodeSubnet`

**Anything else we need to know?**:

This AKS is RBAC enabled.

Originally using aks-preview, as I wanted to use VMSS. Uninstalling this extension makes no difference.

I have the "VMSSPreview" and "MultiAgentpoolPreview" enabled on the subscription.

I have verified:

- Resource ID to aks-virtual-nodes subnet is valid using "az resource"
- Enabled ContainerInstance delegation to the aks-virtual-nodes subnet (not sure whether this is required as article doesn't mention it, tired with/without)
- Run "kubectl describe pods <pod of aci-linux> --namespace kube-system"

`Name:               aci-connector-linux-5d545cb956-bq5mh
Namespace:          kube-system
Priority:           2000001000
PriorityClassName:  system-node-critical
Node:               aks-nodepool1-35111610-0/10.240.0.4
Start Time:         Mon, 20 May 2019 10:38:43 +0100
Labels:             app=aci-connector-linux
                    pod-template-hash=5d545cb956
Annotations:        checksum/cloud-provider-config=6e1d27358b97d194fd4642f8146aedf3b38954492366b808f880f9db5d5d9d24
Status:             Running
IP:                 10.240.0.16
Controlled By:      ReplicaSet/aci-connector-linux-5d545cb956
Containers:
  aci-connector-linux:
    Container ID:  docker://fa1d85559f566581ab1d78571d1a993b4ab2ca01ed5539d91ddccd13876ff826
    Image:         microsoft/virtual-kubelet:latest
    Image ID:      docker-pullable://microsoft/virtual-kubelet@sha256:efc397d741d7e590c892c0ea5dccc9a800656c3adb95da4dae25c1cdd5eb6d9f
    Port:          <none>
    Host Port:     <none>
    Command:
      virtual-kubelet
    Args:
      --provider
      azure
      --nodename
      virtual-node-aci-linux
      --os
      Linux
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 20 May 2019 10:42:04 +0100
      Finished:     Mon, 20 May 2019 10:42:05 +0100
    Ready:          False
    Restart Count:  5
    Environment:
      KUBELET_PORT:                  10250
      ACS_CREDENTIAL_LOCATION:       /etc/acs/azure.json
      AZURE_CLIENT_SECRET:           <set to the key 'clientSecret' in secret 'aci-connector-linux'>  Optional: false
      APISERVER_CERT_LOCATION:       /etc/virtual-kubelet/cert.pem
      APISERVER_KEY_LOCATION:        /etc/virtual-kubelet/key.pem
      VKUBELET_POD_IP:                (v1:status.podIP)
      ACI_EXTRA_USER_AGENT:          add-on/aks
      ACI_SUBNET_NAME:               /subscriptions/<subscription>/resourceGroups/<resourcegroup>/providers/Microsoft.Network/virtualNetworks/<vnet>/subnets/aks-virtual-nodes
      MASTER_URI:                    https://<redacted>.hcp.northeurope.azmk8s.io
      CLUSTER_CIDR:                  10.240.0.0/16
      KUBE_DNS_IP:                   10.0.0.10
      KUBERNETES_PORT_443_TCP_ADDR:  <redacted>.hcp.northeurope.azmk8s.io
      KUBERNETES_PORT:               tcp://<redacted>.hcp.northeurope.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://<redacted>.hcp.northeurope.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       <redacted>.hcp.northeurope.azmk8s.io
    Mounts:
      /etc/acs/azure.json from aks-credential (rw)
      /etc/virtual-kubelet from credentials (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from aci-connector-linux-token-kvm6c (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  aci-connector-linux
    Optional:    false
  aks-credential:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  aci-connector-linux-token-kvm6c:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  aci-connector-linux-token-kvm6c
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>`

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.6
- Size of cluster (how many worker nodes are in the cluster?) 1 node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.). Empty cluster, setup phase
- Others:

I have also tried the above with aks-preview and --enable-vmss, with the same result.

**Comment by srrengar** [comment]
@robbiezhang is there anything in the az aks create cmd above that would trigger this CrashLoopBackoff?
@inuvano-labs I'm assuming you assigned permissions to the VNet as described in the article right? 

Virtual Nodes isn't supported with Node Pools while the latter is in preview but I am not sure why it is failing in either case.

**Comment by dannymyers** [comment]
I am having this same problem as well. We're using Terraform to set up our environment if that makes any difference. Everything was working fine until I created a new cluster today.

**Comment by dannymyers** [comment]
Our problem turned out to be that we were using the ID of our subnet instead of the subnet name. 

The problem area is highlighted in green. This should be the name of the subnet (in our case aci-virtualnode-subnet), not the ID (/subscriptions/.../aci-virtualnode-subnet).

![image](https://user-images.githubusercontent.com/7907151/58599063-73d82980-8233-11e9-8861-d18a7fb7550b.png)

**Comment by robbiezhang** [comment]
@inuvano-labs 
The error indicates you didn't create the subnet (aks-virtual-nodes) in the AKS vnet. Please make sure you've run this command:
```bash
az network vnet subnet create \
    --resource-group myResourceGroup \
    --vnet-name myVnet \
    --name myVirtualNodeSubnet \
    --address-prefixes 10.241.0.0/16
```
https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli#create-a-virtual-network

**Comment by inuvano-labs** [comment]
I think @dannymyers has discovered the issue. We shouldn't be specifying the resource Id rather just the name of the subnet.

I will update my deployment code and report back as I'm using cli not tf

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by inuvano-labs** [comment]
I can confirm that this was the same issue for us too - specifying the resource Id of the subnet was the problem.
