### ISSUE TITLE
Integrate Service Mesh setup with the Azure AKS cluster 

### ISSUE THREAD

**Issue by Sudharma** [Azure/AKS#988]
**What happened**:

This is a feature request for making istio installation part of azure aks cli. The installation would ease the developers work without much thinking of the istio actually!

**What you expected to happen**:

I would be easily able to install the service mesh (Istio) on the AKS cluster.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jnoller** [comment]
Closing this request: We have plans on service meshes on AKS, however we are looking at the SMI spec as the needs of our customer base with Service Meshes are wildly variant. For the majority, LinkerD is sufficient, while Istio is overly complex, meanwhile there are valid cases for istio. Please watch this github repository for more information when we are ready to announce

**Comment by Sudharma** [comment]
that was quite quick! Will watch out this space!

**Comment by wmorgan** [comment]
Love this. Tons of happy Linkerd + AKS users. @jnoller and others, please feel free to reach out to me directly for any help with integration.
