### ISSUE TITLE
Adding Windows node pool fails with "NodesNotReady"

### ISSUE THREAD

**Issue by neginmr** [Azure/AKS#989]
**What happened**:
I'm trying to add a VMSS pool after enabling the preview feature for my subscription.
Adding the nod pool fails after about an hour with this error: 
"message":"The resource operation completed with terminal provisioning state 'Failed'.",
"details":[{\"code\":\"NodesNotReady\",\"message\":\"\"}]

I tried this a multiple times with different node types/sizes, and I faced the same issue. 

VMSS is created successfully in the other resource group, but kubectl get nodes does not list the windows nodes.

cmd used:
az aks nodepool add -g $resourceGroup --cluster-name $clusterName --os-type Windows --name wpool1 --node-count 3 --node-vm-size "Standard_D2_v2" --kubernetes-version 1.14.0

**Comment by smax48** [comment]
I have similar issue with adding Windows node pools... It doesn't work.
It started earlier this week. Last week (when everything was in private preview) all worked great.
Now I cannot add a new windows pool anymore :(

I tried 2 different regions in AU with the same result.

Also I tried using pre-exisisting VNet or without one...

In the cmd line I get the following:
```
Deployment failed. Correlation ID: 9f2767ed-e12e-4d43-8dff-8052152a2a56. Operation failed with status: 200. Details: Resource state Failed
```

**Comment by lavanyaanbuatgmaildotcom** [comment]
I have faced the same issue during the cluster creation with VMSS enabled.

"message":"The resource operation completed with terminal provisioning state 'Failed'.",
"details":[{"code":"NodesNotReady","message":""}]

**Comment by dejoost** [comment]
same here for westeurope, vmss deploy succeeded, after an hour the console returned:

`Deployment failed. Correlation ID: 65ad0957-3615-4811-afd8-d479692a09fe. Operation failed with status: 200. Details: Resource state Failed`

**Comment by stephenpope** [comment]
Same here. Adding windows nodes fails for 1.14.0. I am able to add them for 1.13.5 .. but then my containers fail with compatibility errors as I am using server2019 so i need 1.14.0.
I have tried upgrading the node pool 1.13.5 -> 1.14.0 but this also fails (the node seems to be created but there seems to be a DNS issue).

**Comment by MikkelHegn** [comment]
Thanks for reporting this. We are looking in to this now and will report back as soon as we know more.

**Comment by Bobbicus** [comment]
I'm seeing the same issue.  I added another Linux pool with no issue.  I was not able to add Windows node pools for either version 1.35.5 or 1.14.0.  When I list the pools I see the node pool in a failed state.  
```
az aks nodepool list
```
```
  {
    "agentPoolType": "VirtualMachineScaleSets",
    "availabilityZones": null,
    "count": 1,
    "enableAutoScaling": null,
    "id": "/subscriptions/000000000000-0000-0000-000000000000/resourcegroups/kube-rg03/providers/Microsoft.ContainerService/managedClusters/aks-cluster3/agentPo
ols/winnp1",
    "maxCount": null,
    "maxPods": 30,
    "minCount": null,
    "name": "winnp1",
    "orchestratorVersion": "1.14.0",
    "osDiskSizeGb": 100,
    "osType": "Windows",
    "provisioningState": "Failed",
    "resourceGroup": "kube-rg03",
    "type": "Microsoft.ContainerService/managedClusters/agentPools",
    "vmSize": "Standard_D2s_v3",
    "vnetSubnetId": null
  }
```

This was working on Monday 20/05

**Comment by zr-msft** [comment]
Since this problem is being tracked by another issue, #please-close

**Comment by zr-msft** [comment]
ignore previous comment, closing other issue

**Comment by MikkelHegn** [comment]
We have fixed this issue, and you should now be able to create windows node pools again in all regions. We're sorry about the inconvenience this may have caused - don't hesitate to let us know if you see other issues.

**Comment by Bobbicus** [comment]
Working well for me now.  Thank you

**Comment by smax48** [comment]
Yes, I can now create a Windows node pool! Thanks!

**Comment by rogersass** [comment]
Thank you for quickly resolving this issue, working for me as well!

**Comment by neginmr** [comment]
Thanks!
