### ISSUE TITLE
Please add support and documentation for CoreDNS

### ISSUE THREAD

**Issue by AceHack** [Azure/AKS#99]
I'm trying to follow the guide for CoreDNS here
https://github.com/coredns/deployment/tree/master/kubernetes

I can't find all the info need to for this work on Azure.

Actually it would be great to just create new AKS clusters using CoreDNS by default instead of KubeDNS.

Thanks.

**Comment by slack** [comment]
No plans to support replacing the dns services. We will track upstream as it transitions to coredns in a subsequent Kubernetes release:

Ref: https://github.com/kubernetes/community/pull/1100 https://github.com/kubernetes/features/issues/427

**Comment by justaugustus** [comment]
Linking this one as well: kubernetes/features#566

**Comment by adrianrbezzina** [comment]
With Kubernetes now making CoreDNS the default option starting with K8s 1.11, is there a plan to update the AKS version accordingly?

Thanks.

**Comment by AceHack** [comment]
I am also very interested

**Comment by Nilubkal** [comment]
kube-dns is still present though : 
![image](https://user-images.githubusercontent.com/24918985/52847826-8f4c7800-310d-11e9-8ebb-c1eeaea769eb.png)

**Comment by toutougabi** [comment]
delete the deployments related to kube-dns, i was with support last few days it was an error in the initial deployment. You only need coredns
