### ISSUE TITLE
Add metrics supported by kube-state-metrics to AKS 

### ISSUE THREAD

**Issue by victornoel** [Azure/AKS#990]
AKS supports metrics from metrics-server (or is it heapster, it's not clear) to be collected via log analytics.
It would be relevant to also have kube-state-metrics (see [this](https://github.com/kubernetes/kube-state-metrics#kube-state-metrics-vs-metrics-server) for the difference) on the nodes and its metrics collected.

One feature it provides not available on AKS is for example gathering data about killing event and their reason. It is currently not possible to know if a pod has been killed because of OOM.
kube-state-metrics brings this kind of features (see [this](https://stackoverflow.com/a/50563113/9046139) for example).

**Comment by andrewglind** [comment]
Hi all, I have this working by using the agent data collection for Azure Monitor. Detailed instructions are here: https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-agent-config. The relevant line to change in the ConfigMap is:

```
urls = ["http://$NODE_IP:9100/metrics", "http://10.22.0.9:8080/metrics"]
```

which exposes the kube-state-metrics metrics endpoint. Metrics will then become available in Log Analytics, e.g.

```
InsightsMetrics
| where Namespace == "prometheus"
| where Name contains "kube_"
```
