### ISSUE TITLE
Cluster admin role via Azure Active Directory support

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#992]
This is a tracking issue for AKS enhancements to Azure Active Directory integration to allow more seamless authentication and RBAC including:

* get-credentials --admin` will return kubeconfig using AAD auth mode instead of a client certificate. 
* Users will be able to create an AAD clientApp that will be used by kubectl for authentication to AAD using bearer tokens

**Comment by TomGeske** [comment]
We shipped AKS-managed AAD allowing you to bind an AAD group to your cluster. Take a look @ https://aka.ms/aks/managed-aad
