### ISSUE TITLE
Cluster managed identity

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#993]
Tracking issue for conversion from Service Principal authentication to Managed Identity within AKS.

**Comment by jnoller** [comment]
Related Issue #803

**Comment by J0F3** [comment]
Any news or an approximate ETA for this?
Thx!

**Comment by mkosieradzki** [comment]
https://azure.microsoft.com/en-us/updates/managed-identities-integration-in-azure-kubernetes-service-aks-is-now-in-preview/ - it seems to be live very soon.

However I see that it does only support System-assigned MI. If designed properly this should not cause any problems.

**Comment by sauryadas** [comment]
https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

**Comment by asubmani** [comment]
If we provision an AKS cluster today with MSI's AND keep the SPN for required services like monitoring etc. Can we AVOID a cluster re-deployment when the SPN dependency is no longer required?

**Comment by sauryadas** [comment]
@norshtein Can you confirm? will an upgrade clean up the SPN and have the addons refer to the UA MI ?

**Comment by norshtein** [comment]
After SPN dependency is no longer required, it's fine if you don't update current cluster. But disabling and re-enabling addons is needed, the purpose of this operation is to recreate addon pods and use new addon version to make addons use managed identity to authenticate. During this period, your addons will be offline for sometime but the cluster will keep online. If you don't disable and re-enable addons, your addons will still use SPN to authenticate and they will not work correctly after SPN expires.

**Comment by norshtein** [comment]
@sauryadas yes, an upgrading operation will clean up the SPN.

**Comment by ams0** [comment]
I tested this scenario today:

```
$> az ad sp create-for-rbac -n "uselesssp" --skip-assignment
$> az aks create -k 1.17.0  --load-balancer-sku Standard --network-plugin kubenet -c 2 -s Standard_B4ms  --nodepool-name base  -g k8s -n msi --enable-managed-identity --service-principal <uselesssp> --client-secret <uselesssecret>
```
It has to be a real SP - anything else, like a wrong password, will fail (it means the CLI or the RP does some sort of checking?). But once the cluster is running, it works fine (so far as I can test). It creates `LoadBalancer` type services and can use `azure-disk` PersistentVolumes.  Just wanted to share this little fact: you can have a functional cluster without assign the SP any role.

**Comment by colemickens** [comment]
How can that possibly be true? Isn't it more likely that the components are simply using managed identity (with provisioned permissions) since your command includes "--enable-managed-identity"? Seems more likely than Azure allowing someone to... modify all of your resources without permissions.

**Comment by jluk** [comment]
Managed identity is now GA, closing issue as a result.

https://github.com/Azure/AKS/releases/tag/2020-03-16

**Comment by zhiweiv** [comment]
The guide is not updated yet, will it come soon?
https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

**Comment by jluk** [comment]
Document update will be live by Monday, possibly earlier. Thanks for checking!

**Comment by sauryadas** [comment]
@zhiweiv Docs live now
https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

**Comment by jmcshane-optum** [comment]
Very brief question on this, according to the docs a route table is required for AKS deployment, but the permissions section linked from the docs page https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal#delegate-access-to-other-azure-resources doesn't mention anything specifically about configuring routes. Should I open a new issue somewhere on this? I just don't feel like the documentation on the AKS route table is very clear

**Comment by flamingboo** [comment]
@sauryadas  
Somehow I'm a bit confused about the updated guide:

"For creating and using your own VNet, static IP address, or attached Azure disk where the resources are outside of the MC_* resource group, use the PrincipalID of the cluster to perform a role assignment. For more information on role assignment, see Delegate access to other Azure resources."
Since I will be deploying with my own VNet (vnetSubnetID in ARM), how can I do - in advance - an assignment with the PrincipalID of cluster (principl ID of the system-assigned managed identity) generated during the deployement?
Unless I did not understand correctly the procedure?

**Comment by sauryadas** [comment]
@flamingboo you would create the cluster with the byo vnet and then perform the role assignment. Give it a shot and let us know

**Comment by flamingboo** [comment]
ok good. will you keep you updated.

**Comment by andyofengland** [comment]
Is there an ARM Template equivalent of the --enable-managed-identity command?

**Comment by bhicks329** [comment]
Under the resource at the top level you just need ...

```
"identity": {
      "type": "SystemAssigned"
  }
```

**Comment by andyofengland** [comment]
Fantastic, thank you!
Something to perhaps feed back to the documentation side of things as it wasn't clear the correlation between the CLI and the ARM version of the same thing.

**Comment by j03wang** [comment]
Are there plans for this to come to the other clouds (China, specifically)?

**Comment by jluk** [comment]
@j03wang yes this feature is being developed for access in AzChina and AzGov. When those have released those labels will be placed on this ticket. cc @thomas1206 / @TomGeske

**Comment by j03wang** [comment]
@jluk Thanks! Is there a time range I can expect this to come in?

**Comment by TomGeske** [comment]
@j03wang: MSI should be availble in China today. Do you see any error message while creating an MSI enabled cluster?

**Comment by j03wang** [comment]
Yes - I'm seeing this:

Creating cluster having identity type 'SystemAssigned' is not allowed in specified location chinanorth2

**Comment by TomGeske** [comment]
let me double check and come back.

**Comment by TomGeske** [comment]
@j03wang: I just checked. MSI. Current ETA for availability in China is mid-June.

**Comment by j03wang** [comment]
@TomGeske Thanks for checking. Might there be a preview flag or whitelist of sorts for China?

**Comment by TomGeske** [comment]
MSI support for AKS isn't deployed to China region, yet. Whitelisting is mainly used in public cloud regions only.

**Comment by TomGeske** [comment]
Just as a heads-up Managed Identity is now available in China.
