### ISSUE TITLE
Improved AKS Versioning

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#995]
Tracking issue for improved AKS version that includes:

* Discreet roll up AKS versions not tied to Kubernetes versions
* A manifest of all component versions - container insights, aks-engine, coreDNS, etc will have tracked version numbers 

Users will be able to download the manifest to look at which components are at which version (helps compatibility testing)

**Comment by palma21** [comment]
Deprecated for an upcoming different feature issue.
