### ISSUE TITLE
CIS Benchmark / Kube-bench compatibility

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#999]
Currently, if a user runs kube-bench or hand checks CIS benchmark checks for Kubernetes security best practices, those check may fail.

This is a tracking issue for CIS compliance within AKS- this includes mitigation for cited issues by the tool(s) as well as any changes required to clear any erroneus reports - for example, AKS runs Moby, not Docker in the fleet, so certain checks are incorrect

**Comment by bergerx** [comment]
I think this is a duplicate of #367, and can be closed.

**Comment by sauryadas** [comment]
https://github.com/aquasecurity/kube-bench#running-in-an-aks-cluster

There will be a couple of failed tests

**Comment by jluk** [comment]
Closing this in favor of the active thread on #367 mentioned.
